### ISSUE TITLE
salt-cloud --list- tools not working for openstack (ulticloud.com)

### ISSUE THREAD

**Issue by maci0** [saltstack/salt#10039]
```
root@nb0815 /etc/salt/cloud.providers.d # salt-cloud --list-images openstack                                                                                       
[INFO    ] salt-cloud starting
[ERROR   ] Failed to get the output of 'openstack.avail_images()': <MalformedResponseException in None 'Malformed response'>: 'code: 400 body: {"error": {"message": "get_version_v2() got an unexpected keyword argument \'auth\'", "code": 400, "title": "Bad Request"}}'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 496, in image_list
    data[alias][driver] = self.clouds[fun]()
  File "/usr/lib/python2.7/site-packages/salt/cloud/libcloudfuncs.py", line 145, in avail_images
    images = conn.list_images()
  File "/usr/lib/python2.7/site-packages/libcloud/compute/drivers/openstack.py", line 292, in list_images
    self.connection.request('/images/detail').object, ex_only_active)
  File "/usr/lib/python2.7/site-packages/libcloud/compute/drivers/openstack.py", line 156, in request
    method=method, headers=headers)
  File "/usr/lib/python2.7/site-packages/libcloud/common/openstack.py", line 575, in request
    return super(OpenStackBaseConnection, self).request(**kwargs)
  File "/usr/lib/python2.7/site-packages/libcloud/common/base.py", line 596, in request
    action = self.morph_action_hook(action)
  File "/usr/lib/python2.7/site-packages/libcloud/common/openstack.py", line 571, in morph_action_hook
    self._populate_hosts_and_request_paths()
  File "/usr/lib/python2.7/site-packages/libcloud/common/openstack.py", line 600, in _populate_hosts_and_request_paths
    osa.authenticate()  # may throw InvalidCreds
  File "/usr/lib/python2.7/site-packages/libcloud/common/openstack.py", line 157, in authenticate
    return self.authenticate_2_0_with_password()
  File "/usr/lib/python2.7/site-packages/libcloud/common/openstack.py", line 252, in authenticate_2_0_with_password
    return self.authenticate_2_0_with_body(reqbody)
  File "/usr/lib/python2.7/site-packages/libcloud/common/openstack.py", line 264, in authenticate_2_0_with_body
    driver=self.driver)
MalformedResponseError: <MalformedResponseException in None 'Malformed response'>: 'code: 400 body: {"error": {"message": "get_version_v2() got an unexpected keyword argument \'auth\'", "code": 400, "title": "Bad Request"}}'
my-openstack-config:
    ----------

root@nb0815 /etc/salt/cloud.providers.d # salt-cloud --list-locations openstack
[INFO    ] salt-cloud starting
my-openstack-config:
    ----------
    openstack:
        ----------
        :
            ----------
            country:

            driver:
            id:
                0
            name:



 root@nb0815 /etc/salt/cloud.providers.d # salt-cloud --list-sizes openstack                                                                                       
[INFO    ] salt-cloud starting
[ERROR   ] Failed to get the output of 'openstack.avail_sizes()': <MalformedResponseException in None 'Malformed response'>: 'code: 400 body: {"error": {"message": "get_version_v2() got an unexpected keyword argument \'auth\'", "code": 400, "title": "Bad Request"}}'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 539, in size_list
    data[alias][driver] = self.clouds[fun]()
  File "/usr/lib/python2.7/site-packages/salt/cloud/libcloudfuncs.py", line 180, in avail_sizes
    sizes = conn.list_sizes()
  File "/usr/lib/python2.7/site-packages/libcloud/compute/drivers/openstack.py", line 296, in list_sizes
    self.connection.request('/flavors/detail').object)
  File "/usr/lib/python2.7/site-packages/libcloud/compute/drivers/openstack.py", line 156, in request
    method=method, headers=headers)
  File "/usr/lib/python2.7/site-packages/libcloud/common/openstack.py", line 575, in request
    return super(OpenStackBaseConnection, self).request(**kwargs)
  File "/usr/lib/python2.7/site-packages/libcloud/common/base.py", line 596, in request
    action = self.morph_action_hook(action)
  File "/usr/lib/python2.7/site-packages/libcloud/common/openstack.py", line 571, in morph_action_hook
    self._populate_hosts_and_request_paths()
  File "/usr/lib/python2.7/site-packages/libcloud/common/openstack.py", line 600, in _populate_hosts_and_request_paths
    osa.authenticate()  # may throw InvalidCreds
  File "/usr/lib/python2.7/site-packages/libcloud/common/openstack.py", line 157, in authenticate
    return self.authenticate_2_0_with_password()
  File "/usr/lib/python2.7/site-packages/libcloud/common/openstack.py", line 252, in authenticate_2_0_with_password
    return self.authenticate_2_0_with_body(reqbody)
  File "/usr/lib/python2.7/site-packages/libcloud/common/openstack.py", line 264, in authenticate_2_0_with_body
    driver=self.driver)
MalformedResponseError: <MalformedResponseException in None 'Malformed response'>: 'code: 400 body: {"error": {"message": "get_version_v2() got an unexpected keyword argument \'auth\'", "code": 400, "title": "Bad Request"}}'
my-openstack-config:
    ----------

```

```
salt-cloud --versions
            Salt: 2014.1.0-778-g85cbec9
          Python: 2.7.6 (default, Nov 26 2013, 12:52:49)
          Jinja2: 2.7.2
        M2Crypto: 0.21.1
  msgpack-python: 0.4.0
    msgpack-pure: Not Installed
        pycrypto: 2.6.1
          PyYAML: 3.10
           PyZMQ: 14.0.1
             ZMQ: 4.0.3
 Apache Libcloud: 0.14.0
```

```
cat /etc/salt/cloud.providers.d/openstack.conf 
my-openstack-config:
  minion:
    master: salt

  identity_url: https://ulticloud.com:5000/v2.0/
  compute_name: nova
  protocol: ipv4

  compute_region: RegionOne

  user: XXXX
  password: XXXX 
  tenant: XXXX

  provider: openstack

```

**Comment by rallytime** [comment]
It looks like a "Getting Started with OpenStack" doc  has been created since the last couple of comments on this issue, though I am not sure that the "caveats" described above are all documented there. Though this issue is a bit old, so I am not sure if this is still an issue or not, or if some of these specifics have been worked out else where.
