### ISSUE TITLE
Traceback on salt-run cloud.destroy $host

### ISSUE THREAD

**Issue by clearclaw** [saltstack/salt#10947]
```
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
KeyError: 'instanceId'
Traceback (most recent call last):
  File "/usr/local/bin/salt-run", line 10, in <module>
    salt_run()
  File "/usr/lib/pymodules/python2.7/salt/scripts.py", line 95, in salt_run
    client.run()
  File "/usr/lib/pymodules/python2.7/salt/cli/__init__.py", line 357, in run
    runner.run()
  File "/usr/lib/pymodules/python2.7/salt/runner.py", line 219, in run
    self.opts['fun'], self.opts['arg'], self.opts)
  File "/usr/lib/pymodules/python2.7/salt/runner.py", line 126, in cmd
    return self.functions[fun](*args, **kwargs)
  File "/usr/lib/pymodules/python2.7/salt/runners/cloud.py", line 96, in destroy
    info = client.destroy(names)
  File "/usr/lib/pymodules/python2.7/salt/cloud/__init__.py", line 151, in destroy
    mapper.destroy(names))
  File "/usr/lib/pymodules/python2.7/salt/cloud/__init__.py", line 645, in destroy
    ret = self.clouds[fun](name)
  File "/usr/lib/pymodules/python2.7/salt/cloud/clouds/ec2.py", line 1769, in destroy
    instance_id = node_metadata['instanceId']
KeyError: 'instanceId'
Traceback (most recent call last):
  File "/usr/local/bin/salt-run", line 10, in <module>
    salt_run()
  File "/usr/lib/pymodules/python2.7/salt/scripts.py", line 95, in salt_run
    client.run()
  File "/usr/lib/pymodules/python2.7/salt/cli/__init__.py", line 357, in run
    runner.run()
  File "/usr/lib/pymodules/python2.7/salt/runner.py", line 219, in run
    self.opts['fun'], self.opts['arg'], self.opts)
  File "/usr/lib/pymodules/python2.7/salt/runner.py", line 126, in cmd
    return self.functions[fun](*args, **kwargs)
  File "/usr/lib/pymodules/python2.7/salt/runners/cloud.py", line 96, in destroy
    info = client.destroy(names)
  File "/usr/lib/pymodules/python2.7/salt/cloud/__init__.py", line 151, in destroy
    mapper.destroy(names))
  File "/usr/lib/pymodules/python2.7/salt/cloud/__init__.py", line 645, in destroy
    ret = self.clouds[fun](name)
  File "/usr/lib/pymodules/python2.7/salt/cloud/clouds/ec2.py", line 1769, in destroy
    instance_id = node_metadata['instanceId']
KeyError: 'instanceId'
```

**Comment by rallytime** [comment]
I am going around to some older issues. Is this still an issue on some newer releases? Has anyone run into this one on 2014.7.x or, even better to test, 2015.5.x releases? The 2014.1 branch has been retired, and we will no longer be releasing from 2014.7, either. Is this still a problem or can this be closed?

**Comment by rallytime** [comment]
Since I didn't hear back here, and I think this is fixed, I am going to close this. If this remains an issue for anyone, please comment and we will be glad to re-open and address any concerns.
