### ISSUE TITLE
state for network.system fails

### ISSUE THREAD

**Issue by drzero42** [saltstack/salt#11164]
I am testing out network management in Salt 2014.1.0 on Ubuntu 12.04 machines. I have pretty much just grabbed the examples from the documentation:

```
system:
  network.system:
    - enabled: True
    - hostname: thinclient-admin.dsl.lan
    - gateway: 10.17.4.1
    - gatewaydev: eth0
    - nozeroconf: True
    - require_reboot: True

eth0:
  network.managed:
    - enabled: True
    - type: eth 
    - proto: none
    - ipaddr: 10.17.4.9
    - netmask: 255.255.255.0
    - dns:
      - 10.16.4.4
```

The system stanza fails with this traceback:

```
          ID: system
    Function: network.system
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/pymodules/python2.7/salt/state.py", line 1371, in call
                  **cdata['kwargs'])
                File "/usr/lib/pymodules/python2.7/salt/states/network.py", line 380, in system
                  new = __salt__['ip.build_network_settings'](**kwargs)
                File "/usr/lib/pymodules/python2.7/salt/modules/debian_ip.py", line 1461, in build_network_settings
                  opts = _parse_network_settings(settings, current_network_settings)
                File "/usr/lib/pymodules/python2.7/salt/modules/debian_ip.py", line 1002, in _parse_network_settings
                  opts['networking'] = current['networking']
              KeyError: 'networking'
```

**Comment by timwsuqld** [comment]
@drzero42 @garethgreenaway
My testing of 2016.3.2 suggests that this still hasn't been fixed for Ubuntu. I get no gateway route.

**Comment by westurner** [comment]
@timwsuqld can you paste cfg that causes the error,
and then run with debug logging in order to get the traceback around the network.system calls?

**Comment by timwsuqld** [comment]
My State
```
system:
  network.system:
    - enabled: True
    - hostname: test1.suqld.org.au
    - require_reboot: True
    - gateway: 10.1.37.254
    - gatewaydev: ens192

/etc/hostname:
  file.managed:
    - contents: test1
    - backup: false
```

Docs suggest (and it works on Centos machines) that I can define gateway and gatewaydev here. Doing so doesn't give me a default route under Ubuntu.

Debug output
```
sudo salt-call -l debug state.sls networking.hostname
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[WARNING ] /usr/lib/python2.7/dist-packages/salt/grains/core.py:1493: DeprecationWarning: The "osmajorrelease" will be a type of an integer.

[DEBUG   ] Connecting to master. Attempt 1 of 1
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'test1', 'tcp://192.168.0.20:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (1428)
[DEBUG   ] Setting zmq_reconnect_ivl to '1428ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'test1', 'tcp://192.168.0.20:4506', 'clear')
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Determining pillar cache
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'test1', 'tcp://192.168.0.20:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'test1', 'tcp://192.168.0.20:4506')
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded state.sls
[DEBUG   ] LazyLoaded saltutil.is_running
[DEBUG   ] LazyLoaded grains.get
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'test1', 'tcp://192.168.0.20:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'test1', 'tcp://192.168.0.20:4506')
[DEBUG   ] Determining pillar cache
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'test1', 'tcp://192.168.0.20:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'test1', 'tcp://192.168.0.20:4506')
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] In saltenv 'base', looking at rel_path 'networking/hostname.sls' to resolve 'salt://networking/hostname.sls'
[DEBUG   ] In saltenv 'base', ** considering ** path '/var/cache/salt/minion/files/base/networking/hostname.sls' to resolve 'salt://networking/hostname.sls'
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://networking/hostname.sls'
[DEBUG   ] compile template: /var/cache/salt/minion/files/base/networking/hostname.sls
[DEBUG   ] Jinja search path: ['/var/cache/salt/minion/files/base']
[DEBUG   ] LazyLoaded pillar.get
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/networking/hostname.sls' using 'jinja' renderer: 0.00820112228394
[DEBUG   ] Rendered data from file: /var/cache/salt/minion/files/base/networking/hostname.sls:

system:
  network.system:
    - enabled: True
    - hostname: test1.suqld.org.au
    - require_reboot: True
    - gateway: 10.1.37.254
    - gatewaydev: ens192

/etc/hostname:
  file.managed:
    - contents: test1
    - backup: false

[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Results of YAML rendering:
OrderedDict([('system', OrderedDict([('network.system', [OrderedDict([('enabled', True)]), OrderedDict([('hostname', 'test1.suqld.org.au')]), OrderedDict([('require_reboot', True)]), OrderedDict([('gateway', '10.1.37.254')]), OrderedDict([('gatewaydev', 'ens192')])])])), ('/etc/hostname', OrderedDict([('file.managed', [OrderedDict([('contents', 'test1')]), OrderedDict([('backup', False)])])]))])
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/networking/hostname.sls' using 'yaml' renderer: 0.00796318054199
[DEBUG   ] LazyLoaded ip.get_interface
[DEBUG   ] LazyLoaded network.system
[INFO    ] Running state [system] at time 14:36:21.951625
[INFO    ] Executing state network.system for system
[DEBUG   ] LazyLoaded service.available
[DEBUG   ] LazyLoaded cmd.run
[INFO    ] Executing command ['systemctl', 'status', 'networking.service', '-n', '0'] in directory '/root'
[DEBUG   ] output: * networking.service - Raise network interfaces
   Loaded: loaded (/lib/systemd/system/networking.service; enabled; vendor preset: enabled)
  Drop-In: /run/systemd/generator/networking.service.d
           `-50-insserv.conf-$network.conf
   Active: active (exited) since Thu 2016-09-01 10:44:01 AEST; 3h 52min ago
     Docs: man:interfaces(5)
 Main PID: 3328 (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/networking.service
[INFO    ] Executing command ['systemctl', 'is-active', 'networking.service'] in directory '/root'
[DEBUG   ] output: active
[INFO    ] Executing command ['systemctl', 'status', 'NetworkManager.service', '-n', '0'] in directory '/root'
[DEBUG   ] output: * NetworkManager.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
[INFO    ] Executing command ['systemctl', 'is-enabled', 'networking.service'] in directory '/root'
[DEBUG   ] output: enabled
[DEBUG   ] Service 'networking' is not masked
[DEBUG   ] sysvinit script 'lxcfs' found, but systemd unit 'lxcfs.service' already exists
[DEBUG   ] sysvinit script 'single' found, but systemd unit 'single.service' already exists
[DEBUG   ] sysvinit script 'ssh' found, but systemd unit 'ssh.service' already exists
[DEBUG   ] sysvinit script 'atd' found, but systemd unit 'atd.service' already exists
[DEBUG   ] sysvinit script 'rsyslog' found, but systemd unit 'rsyslog.service' already exists
[DEBUG   ] sysvinit script 'urandom' found, but systemd unit 'urandom.service' already exists
[DEBUG   ] sysvinit script 'screen-cleanup' found, but systemd unit 'screen-cleanup.service' already exists
[DEBUG   ] sysvinit script 'iscsid' found, but systemd unit 'iscsid.service' already exists
[DEBUG   ] sysvinit script 'rcS' found, but systemd unit 'rcS.service' already exists
[DEBUG   ] sysvinit script 'kmod' found, but systemd unit 'kmod.service' already exists
[DEBUG   ] sysvinit script 'umountfs' found, but systemd unit 'umountfs.service' already exists
[DEBUG   ] sysvinit script 'killprocs' found, but systemd unit 'killprocs.service' already exists
[DEBUG   ] sysvinit script 'rsync' found, but systemd unit 'rsync.service' already exists
[DEBUG   ] sysvinit script 'resolvconf' found, but systemd unit 'resolvconf.service' already exists
[DEBUG   ] sysvinit script 'salt-minion' found, but systemd unit 'salt-minion.service' already exists
[DEBUG   ] sysvinit script 'php7.0-fpm' found, but systemd unit 'php7.0-fpm.service' already exists
[DEBUG   ] sysvinit script 'reboot' found, but systemd unit 'reboot.service' already exists
[DEBUG   ] sysvinit script 'cryptdisks' found, but systemd unit 'cryptdisks.service' already exists
[DEBUG   ] sysvinit script 'avahi-daemon' found, but systemd unit 'avahi-daemon.service' already exists
[DEBUG   ] sysvinit script 'acpid' found, but systemd unit 'acpid.service' already exists
[DEBUG   ] sysvinit script 'open-vm-tools' found, but systemd unit 'open-vm-tools.service' already exists
[DEBUG   ] sysvinit script 'halt' found, but systemd unit 'halt.service' already exists
[DEBUG   ] sysvinit script 'plymouth-log' found, but systemd unit 'plymouth-log.service' already exists
[DEBUG   ] sysvinit script 'cryptdisks-early' found, but systemd unit 'cryptdisks-early.service' already exists
[DEBUG   ] sysvinit script 'zabbix-agent' found, but systemd unit 'zabbix-agent.service' already exists
[DEBUG   ] sysvinit script 'keyboard-setup' found, but systemd unit 'keyboard-setup.service' already exists
[DEBUG   ] sysvinit script 'lvm2-lvmpolld' found, but systemd unit 'lvm2-lvmpolld.service' already exists
[DEBUG   ] sysvinit script 'networking' found, but systemd unit 'networking.service' already exists
[DEBUG   ] sysvinit script 'dbus' found, but systemd unit 'dbus.service' already exists
[DEBUG   ] sysvinit script 'cron' found, but systemd unit 'cron.service' already exists
[DEBUG   ] sysvinit script 'rc' found, but systemd unit 'rc.service' already exists
[DEBUG   ] sysvinit script 'console-setup' found, but systemd unit 'console-setup.service' already exists
[DEBUG   ] sysvinit script 'lxd' found, but systemd unit 'lxd.service' already exists
[DEBUG   ] sysvinit script 'mysql' found, but systemd unit 'mysql.service' already exists
[DEBUG   ] sysvinit script 'plymouth' found, but systemd unit 'plymouth.service' already exists
[DEBUG   ] sysvinit script 'udev' found, but systemd unit 'udev.service' already exists
[DEBUG   ] sysvinit script 'open-iscsi' found, but systemd unit 'open-iscsi.service' already exists
[DEBUG   ] sysvinit script 'rc.local' found, but systemd unit 'rc.local.service' already exists
[DEBUG   ] sysvinit script 'lvm2' found, but systemd unit 'lvm2.service' already exists
[DEBUG   ] sysvinit script 'uuidd' found, but systemd unit 'uuidd.service' already exists
[DEBUG   ] sysvinit script 'lvm2-lvmetad' found, but systemd unit 'lvm2-lvmetad.service' already exists
[DEBUG   ] sysvinit script 'sendsigs' found, but systemd unit 'sendsigs.service' already exists
[DEBUG   ] sysvinit script 'procps' found, but systemd unit 'procps.service' already exists
[DEBUG   ] sysvinit script 'umountroot' found, but systemd unit 'umountroot.service' already exists
[DEBUG   ] sysvinit script 'ufw' found, but systemd unit 'ufw.service' already exists
[DEBUG   ] sysvinit script 'unattended-upgrades' found, but systemd unit 'unattended-upgrades.service' already exists
[INFO    ] Executing command ['systemd-run', '--scope', 'systemctl', 'enable', 'networking.service'] in directory '/root'
[DEBUG   ] output: Running scope as unit run-re081af14bfba4e8e8b56c169420a92b4.scope.
Synchronizing state of networking.service with SysV init with /lib/systemd/systemd-sysv-install...
Executing /lib/systemd/systemd-sysv-install enable networking
[INFO    ] Global network settings are up to date.
[INFO    ] Completed state [system] at time 14:36:22.718206 duration_in_ms=766.581
[DEBUG   ] LazyLoaded file.managed
[INFO    ] Running state [/etc/hostname] at time 14:36:22.721261
[INFO    ] Executing state file.managed for /etc/hostname
[DEBUG   ] LazyLoaded file.check_managed_changes
[INFO    ] File /etc/hostname is in the correct state
[INFO    ] Completed state [/etc/hostname] at time 14:36:22.752791 duration_in_ms=31.53
[DEBUG   ] File /var/cache/salt/minion/accumulator/139954863957520 does not exist, no need to cleanup.
[DEBUG   ] LazyLoaded config.option
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'test1', 'tcp://192.168.0.20:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'test1', 'tcp://192.168.0.20:4506')
[DEBUG   ] LazyLoaded highstate.output
local:
----------
          ID: system
    Function: network.system
      Result: True
     Comment: Global network settings are up to date.
     Started: 14:36:21.951625
    Duration: 766.581 ms
     Changes:
----------
          ID: /etc/hostname
    Function: file.managed
      Result: True
     Comment: File /etc/hostname is in the correct state
     Started: 14:36:22.721261
    Duration: 31.53 ms
     Changes:

Summary for local
------------
Succeeded: 2
Failed:    0
------------
Total states run:     2
Total run time: 798.111 ms
```

Not the best solution, but I currently have a workaround in my network.managed section to detect the gateway interface and apply an extra gateway option. This adds the correct gateway line to /etc/network/interfaces so that I do get a gateway route.

**Comment by jgmchan** [comment]
I have the same problem on `2016.3.3`, I have this in my config:
```
system_network:
  network.system:
    - enabled: True
    - gateway: X.X.X.X
    - gatewaydev: eth1
```
salt runs fine but nothing actually happens and I can't see any entries into `/etc/network/interfaces`

**Comment by timwsuqld** [comment]
@cachedout @westurner Can we have someone respond or reopen this issue please?

**Comment by garethgreenaway** [comment]
@timwsuqld @jgmchan Apologies.  Missed your message back in August.  I'll spin up an Ubuntu machine and test this out.

**Comment by timwsuqld** [comment]
@garethgreenaway Thanks. I probably should have done an @ mention back then.

**Comment by garethgreenaway** [comment]
@timwsuqld no worries 😀

**Comment by garethgreenaway** [comment]
@timwsuqld @jgmchan Apologies for the delay in responding on this one.  I remember dealing with this before and the root of the issue was the major differences with how networking is handled on Debian based machines vs. Red Hat machines.  

On RH machines the gateway is definable in a separate location than the interfaces, whereas on Debian machines it's defined with the interfaces.  This gets tricky when you're trying to manage things like the gateway without managing the interface as well.  

Because of this the network.system state module function works quite differently on a Debian based machine vs. a Red Hat based machine.  For managing the gateway I'd recommend using the network.managed or the network.routes state module functions.
