### ISSUE TITLE
IOError in display_output function when using cmd.run

### ISSUE THREAD

**Issue by mtford90** [saltstack/salt#11516]
Hi all,

I'm getting an IOError when executing a salt state that includes the following:

``` yaml
npm_install:
    cmd.run:
        - name: "npm install"
        - user: root
        - cwd: /home/vagrant/blog/Ghost
        - require:
            - pkg: nodejs
```

You'll also notice i'm running this with vagrant. A precise64 box with default settings to be exact.

This seems to happen at random, and at no certain point during the npm install. If I run `salt-call state.sls` a few times it eventually succeeds. The error is as follows:

```
...
...
                  npm http GET https://registry.npmjs.org/glob/-/glob-3.2.9.tgz
                  npm http 200 https://registry.npmjs.org/generic-pool-redux
                  npm http 200 https://registry.npmjs.org/bluebird/-/bluebird-1.0.8.tgz
                  npm http GET https://registry.npmjs.org/generic-pool-redux/-/generic-pool-redux-0.1.0.tgz
                  npm http 200 https://registry.npmjs.org/optimist
                  npm http GET https://registry.npmjs.org/optimist/-/optimist-0.6.1.tgz[ERROR   ] An un-handled exception was caught by salt's global exception handler:
IOError: [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/pymodules/python2.7/salt/scripts.py", line 82, in salt_call
    client.run()
  File "/usr/lib/pymodules/python2.7/salt/cli/__init__.py", line 314, in run
    caller.run()
  File "/usr/lib/pymodules/python2.7/salt/cli/caller.py", line 146, in run
    self.opts)
  File "/usr/lib/pymodules/python2.7/salt/output/__init__.py", line 53, in display_output
    raise exc
IOError: [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/pymodules/python2.7/salt/scripts.py", line 82, in salt_call
    client.run()
  File "/usr/lib/pymodules/python2.7/salt/cli/__init__.py", line 314, in run
    caller.run()
  File "/usr/lib/pymodules/python2.7/salt/cli/caller.py", line 146, in run
    self.opts)
  File "/usr/lib/pymodules/python2.7/salt/output/__init__.py", line 53, in display_output
    raise exc
IOError: [Errno 11] Resource temporarily unavailable
```

I don't mind providing all my `.sls` files etc if necessary to reproduce - I just wanted to check if this was something obvious first. Is this a bug or could it be i'm missing something?

**Comment by eliasp** [comment]
Seeing the same here now on `2015.5.2`/CentOS 7.1.

I wasn't able yet to nail it down to a specific state/to find a minimal working example. Will update here in case I manage to find something useful.

```
               Salt: 2015.5.2
             Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
             Jinja2: 2.7.2
           M2Crypto: 0.21.1
     msgpack-python: 0.4.6
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
            libnacl: Not Installed
             PyYAML: 3.10
              ioflo: Not Installed
              PyZMQ: 14.3.1
               RAET: Not Installed
                ZMQ: 3.2.5
               Mako: Not Installed
```

**Comment by eliasp** [comment]
I can blame now the following state for causing this issue:
```SaltStack
ember-build:
  cmd.run:
    - name: {{ install_path }}/website/player/node_modules/ember-cli/bin/ember build --silent --environment production
    - user: {{ pillar['webserver']['service']['user'] }}
    - cwd:  {{ install_path }}/website/player
    - require:
      - file: set-base-url
      - npm:  player-npm-modules
      - cmd:  bower-install
```
I'll try to find out a bit more what ember is doing here with the output/tty…

**Comment by eliasp** [comment]
I was able for now to workaround the issue by writing the output to a file first and then just dumping the file to the terminal right after `salt-call`:
```
salt-call state.sls web --output-file=output.txt --force-color && cat output.txt
```

**Comment by driskell** [comment]
Interestingly this is happening in `print()`!
I'm seeing the same thing and it happens randomly during printing the output

```
IOError: [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 227, in salt_call
    client.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/call.py", line 69, in run
    caller.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/caller.py", line 246, in run
    self.opts)
  File "/usr/lib/python2.6/site-packages/salt/output/__init__.py", line 118, in display_output
    raise exc
IOError: [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 227, in salt_call
    client.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/call.py", line 69, in run
    caller.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/caller.py", line 246, in run
    self.opts)
  File "/usr/lib/python2.6/site-packages/salt/output/__init__.py", line 118, in display_output
    raise exc
IOError: [Errno 11] Resource temporarily unavailable
```

A bit of Googling seems to suggest something like `errno` not reset properly so the IOError 11 is actually happening in a previous system call and it just happens to be the `print` that actually sees it or something. Though could be something different.

It's constantly reproducible for me if you have any thoughts on how to diagnose.

RedHat 6.6

```
           Salt: 2015.5.5
         Python: 2.6.6 (r266:84292, Nov 21 2013, 10:50:32)
         Jinja2: unknown
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: 1.4.1
```

**Comment by basepi** [comment]
Weird! We'll have to see if we can reproduce this ourselves.
