### ISSUE TITLE
msgpack.exceptions.UnpackValueError: Data is not enough.

### ISSUE THREAD

**Issue by fmnisme** [saltstack/salt#11690]
it work fine before,but now fail!
What is the problem???

windows 2003 x64 salt:2014.1.0

C:\salt>salt-minion.exe -l debug
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[INFO    ] Setting up the Salt Minion "10.1.20.19-windows.reg.web"
[DEBUG   ] Created pidfile: c:\salt\var\run\salt-minion.pid
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Attempting to authenticate with the Salt Master at 10.2.1.208
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
[INFO    ] Authentication with master successful!
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Failed to import module postgres, this is most likely NOT a problem:
Traceback (most recent call last):
  File "salt/loader.py", line 700, in gen_functions
  File "salt/modules/postgres.py", line 29, in <module>
ImportError: No module named csv
[DEBUG   ] Loaded win_shadow as virtual shadow
[DEBUG   ] Loaded win_ip as virtual ip
[DEBUG   ] Loaded win_disk as virtual disk
[DEBUG   ] Loaded win_status as virtual status
[DEBUG   ] Loaded sysmod as virtual sys
[DEBUG   ] Loaded win_autoruns as virtual autoruns
[DEBUG   ] Loaded win_system as virtual system
[DEBUG   ] Loaded win_firewall as virtual firewall
[DEBUG   ] Loaded zcbuildout as virtual buildout
[DEBUG   ] Loaded win_pkg as virtual pkg
[DEBUG   ] Loaded win_network as virtual network
[DEBUG   ] Loaded win_ntp as virtual ntp
[DEBUG   ] Loaded cmdmod as virtual cmd
[DEBUG   ] Loaded win_file as virtual file
[DEBUG   ] Loaded virtualenv_mod as virtual virtualenv
[DEBUG   ] Loaded djangomod as virtual django
[DEBUG   ] Loaded win_service as virtual service
[DEBUG   ] Loaded win_useradd as virtual user
[DEBUG   ] Loaded win_timezone as virtual timezone
[DEBUG   ] Loaded win_repo as virtual winrepo
[DEBUG   ] Loaded win_groupadd as virtual group
[DEBUG   ] Loaded couchdb_return as virtual couchdb
[DEBUG   ] Loaded carbon_return as virtual carbon
[ERROR   ] An un-handled exception was caught by salt's global exception handler
:
UnpackValueError: Data is not enough.
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "**main**.py", line 726, in <module>
  File "**main**.py", line 332, in bootstrap
  File "**main**.py", line 359, in chainload
  File "**main**.py", line 715, in _chainload
  File "__main__.py", line 128, in <module>
  File "**main__salt-minion**.py", line 17, in <module>
  File "salt/scripts.py", line 35, in salt_minion
  File "salt/**init**.py", line 221, in start
  File "salt/**init**.py", line 209, in prepare
  File "salt/minion.py", line 543, in **init**
  File "salt/utils/schedule.py", line 73, in **init**
  File "salt/utils/schedule.py", line 265, in clean_proc_dir
  File "salt/payload.py", line 108, in load
  File "salt/payload.py", line 95, in loads
  File "msgpack/fallback.py", line 95, in unpackb
UnpackValueError: Data is not enough.
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "**main**.py", line 726, in <module>
  File "**main**.py", line 332, in bootstrap
  File "**main**.py", line 359, in chainload
  File "**main**.py", line 715, in _chainload
  File "__main__.py", line 128, in <module>
  File "**main__salt-minion**.py", line 17, in <module>
  File "salt/scripts.py", line 35, in salt_minion
  File "salt/**init**.py", line 221, in start
  File "salt/**init**.py", line 209, in prepare
  File "salt/minion.py", line 543, in **init**
  File "salt/utils/schedule.py", line 73, in **init**
  File "salt/utils/schedule.py", line 265, in clean_proc_dir
  File "salt/payload.py", line 108, in load
  File "salt/payload.py", line 95, in loads
  File "msgpack/fallback.py", line 95, in unpackb
msgpack.exceptions.UnpackValueError: Data is not enough.

**Comment by Kostanos** [comment]
Did't help to me by deleting proc folder.

    [DEBUG   ] Loaded carbon_return as virtual carbon
    [DEBUG   ] Loaded sqlite3_return as virtual sqlite3
    [ERROR   ] An un-handled exception was caught by salt's global exception handler:
    UnpackValueError: 
    Traceback (most recent call last):
      File "/usr/bin/salt-minion", line 14, in <module>
        salt_minion()
      File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 30, in salt_minion
        minion.start()
      File "/usr/lib/python2.7/dist-packages/salt/__init__.py", line 219, in start
        self.prepare()
      File "/usr/lib/python2.7/dist-packages/salt/__init__.py", line 207, in prepare
        self.minion = salt.minion.Minion(self.config)
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 518, in __init__
        self.returners)
      File "/usr/lib/python2.7/dist-packages/salt/utils/schedule.py", line 71, in __init__
        clean_proc_dir(opts)
      File "/usr/lib/python2.7/dist-packages/salt/utils/schedule.py", line 267, in clean_proc_dir
        job = salt.payload.Serial(opts).load(fp_)
      File "/usr/lib/python2.7/dist-packages/salt/payload.py", line 108, in load
        return self.loads(data)
      File "/usr/lib/python2.7/dist-packages/salt/payload.py", line 95, in loads
        return msgpack.loads(msg, use_list=True)
      File "_unpacker.pyx", line 119, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:119)
    UnpackValueError
    Traceback (most recent call last):
      File "/usr/bin/salt-minion", line 14, in <module>
        salt_minion()
      File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 30, in salt_minion
        minion.start()
      File "/usr/lib/python2.7/dist-packages/salt/__init__.py", line 219, in start
        self.prepare()
      File "/usr/lib/python2.7/dist-packages/salt/__init__.py", line 207, in prepare
        self.minion = salt.minion.Minion(self.config)
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 518, in __init__
        self.returners)
      File "/usr/lib/python2.7/dist-packages/salt/utils/schedule.py", line 71, in __init__
        clean_proc_dir(opts)
      File "/usr/lib/python2.7/dist-packages/salt/utils/schedule.py", line 267, in clean_proc_dir
        job = salt.payload.Serial(opts).load(fp_)
      File "/usr/lib/python2.7/dist-packages/salt/payload.py", line 108, in load
        return self.loads(data)
      File "/usr/lib/python2.7/dist-packages/salt/payload.py", line 95, in loads
        return msgpack.loads(msg, use_list=True)
      File "_unpacker.pyx", line 119, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:119)
    msgpack.exceptions.UnpackValueError

I run it in Mint Rebecca
