### ISSUE TITLE
[salt-cloud] AttributeError: 'bool' object has no attribute 'pop'

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#12212]
After libcloud error I get this 

```
The following exception was thrown by libcloud when trying to run the initial deployment: 413 Request Entity TooLarge Quota exceeded: code=InstanceLimitExceeded
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/openstack.py", line 479, in create
    data = conn.create_node(**kwargs)
  File "/usr/lib/python2.7/dist-packages/libcloud/compute/drivers/openstack.py", line 1230, in create_node
    data={'server': server_params})
  File "/usr/lib/python2.7/dist-packages/libcloud/compute/drivers/openstack.py", line 157, in request
    method=method, headers=headers)
  File "/usr/lib/python2.7/dist-packages/libcloud/common/openstack.py", line 575, in request
    return super(OpenStackBaseConnection, self).request(**kwargs)
  File "/usr/lib/python2.7/dist-packages/libcloud/common/base.py", line 675, in request
    response = responseCls(**kwargs)
  File "/usr/lib/python2.7/dist-packages/libcloud/compute/drivers/openstack.py", line 1004, in __init__
    super(OpenStack_1_1_Response, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/libcloud/common/base.py", line 112, in __init__
    raise Exception(self.parse_error())
Exception: 413 Request Entity Too Large Quota exceeded: code=InstanceLimitExceeded
[ERROR   ] There was a query error: 'bool' object has no attribute 'pop'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 388, in run
    ret = mapper.run_map(dmap)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1625, in run_map
    output[name].pop('deploy_kwargs', None)
AttributeError: 'bool' object has no attribute 'pop'
```

**Comment by rallytime** [comment]
@arthurlogilab I am just making my way around some old issues. Are you still seeing this problem? What command were you using to hit that error? What cloud provider were you using? I suspect this has been fixed, but I don't want to close it if you're still seeing problems.

**Comment by arthurlogilab** [comment]
@rallytime thanks for checking, on 2014.7 I don't get the traceback anymore.

**Comment by rallytime** [comment]
Great! Thanks!
