### ISSUE TITLE
Traceback when delete machines in parallel (multiprocessing) in salt-cloud

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#12223]
```
# salt-cloud -P -m map -d
[snip]
[ERROR   ] There was an error destroying machines: 'bool' object has no attribute 'iteritems'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 266, in run
    ret = mapper.destroy(names, cached=True)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 615, in destroy
    iterable=parallel_data
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 250, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 554, in get
    raise self._value
AttributeError: 'bool' object has no attribute 'iteritems'
```

**Comment by rallytime** [comment]
We never received a response here so I am going to close this. If this remains a problem on newer versions of salt (we're currently on 2015.5.1) please leave a comment and we can re-open this. Thanks!
