### ISSUE TITLE
Can't install .deb from sources on Ubuntu 10.04, works on 12.04

### ISSUE THREAD

**Issue by roflmao** [saltstack/salt#12258]
My check-mk-agent code wont install on Ubuntu 10.04. Works excellent on 12.04.

salt versions:

```
           Salt: 2014.1.3
         Python: 2.6.5 (r265:79063, Apr 16 2010, 13:09:56)
         Jinja2: 2.3.1
       M2Crypto: 0.20.1
 msgpack-python: 0.1.9.final
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
         PyYAML: 3.09
          PyZMQ: 13.0.0
            ZMQ: 3.2.2
```
state file:
```
check-mk-agent:
  pkg.installed:
    - sources:
      - check-mk-agent: salt://check_mk/debs/check-mk-agent_1.2.4p2-2_all.deb
```

Output from highstate:
```----------
          ID: check-mk-agent
    Function: pkg.installed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/pymodules/python2.6/salt/state.py", line 1378, in call
                  **cdata['kwargs'])
                File "/usr/lib/pymodules/python2.6/salt/states/pkg.py", line 518, in installed
                  **kwargs)
                File "/usr/lib/pymodules/python2.6/salt/modules/aptpkg.py", line 411, in install
                  _resolve_deps(name, pkg_params, **kwargs)
                File "/usr/lib/pymodules/python2.6/salt/modules/aptpkg.py", line 1584, in _resolve_deps
                  if deb.check():
                File "/usr/lib/python2.6/dist-packages/apt/debfile.py", line 313, in check
                  if self.compare_to_version_in_cache() == VERSION_OUTDATED:
                File "/usr/lib/python2.6/dist-packages/apt/debfile.py", line 289, in compare_to_version_in_cache
                  cachever = self._cache[pkgname].candidate.version
              AttributeError: 'NoneType' object has no attribute 'version'
     Changes:   
----------
```

**Comment by ssgward** [comment]
@roflmao - is this still an issue on newer releases of the OS and Salt?

**Comment by roflmao** [comment]
I actually dont have any 10.04 hosts anymore im afraid so i cannot test this.

**Comment by ssgward** [comment]
Thanks. We'll close this and re-open if it surfaces again, but doubt it will due to 10.04 EOL.
