### ISSUE TITLE
maximum recursion depth traceback occurs when circular requisite statement exists in an overstate 

### ISSUE THREAD

**Issue by jaloren** [saltstack/salt#12862]
salt 2014.1.3

I believe this is similar to issue https://github.com/saltstack/salt/issues/1268. This might be a duplicate but i don't see anything that actually matches this behavior. So I am writing this bug just in case.

I have an overstate file like so:

```
all:
  match: '*'
  sls:
    - gen_server

node2:
  match: 'server2*'
  sls:
    - cluster
  require:
    - all

node3:
  match: 'server3*'
  sls:
    - cluster
  require:
    - node3
```

Please notice in the last component how the require declaration refers to itself.  This then led to the following traceback.

```
2014-05-16 18:24:20,566 [salt.log.setup   ][ERROR   ] An un-handled exception was caught by salt's global exception handler:
RuntimeError: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "/usr/bin/salt-run", line 10, in <module>
    salt_run()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 95, in salt_run
    client.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/__init__.py", line 362, in run
    runner.run()
  File "/usr/lib/python2.6/site-packages/salt/runner.py", line 218, in run
    self.opts['fun'], self.opts['arg'], self.opts)
  File "/usr/lib/python2.6/site-packages/salt/runner.py", line 125, in cmd
    return self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/runners/state.py", line 35, in over
    for stage in overstate.stages_iter():
  File "/usr/lib/python2.6/site-packages/salt/overstate.py", line 298, in stages_iter
    for yret in yielder(sret):
  File "/usr/lib/python2.6/site-packages/salt/overstate.py", line 281, in yielder
```

**Comment by msteed** [comment]
Although this is soon to be made obsolete with the removal of overstate.py in 2015.8, it looks like this is still a problem in 2015.5.
