### ISSUE TITLE
AssertionError when launching states from the master

### ISSUE THREAD

**Issue by alienzrcoming** [saltstack/salt#13078]
Hi,

I find from time to time that some of my minions result in the following error when I launch states from the salt master:

```
salt minion01 state.sls states.salt.minions
minion01:
    Data failed to compile:
----------
    Rendering SLS states.salt.minions failed, render error: 
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/salt/state.py", line 1964, in render_state
    if saltenv == 'include':
  File "/usr/lib/python2.6/dist-packages/salt/template.py", line 69, in compile_template
    input_data = ifile.read()
  File "/usr/lib/python2.6/dist-packages/salt/renderers/jinja.py", line 39, in render
    **kws)
  File "/usr/lib/python2.6/dist-packages/salt/utils/templates.py", line 55, in render_tmpl
AssertionError
```

If I check the minion to see if the state was applied, I usually find that it has succeeded.  Running salt-call state.sls states.salt.minions runs normally on the minion itself.

Master:  (debian wheezy)

```
salt --versions-report
           Salt: 2014.1.4
         Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.6
         PyYAML: 3.10
          PyZMQ: 13.1.0
            ZMQ: 3.2.3
```

Minions:  (debian wheezy)

```
salt-call --versions-report
           Salt: 2014.1.4
         Python: 2.6.6 (r266:84292, Dec 26 2010, 22:31:48)
         Jinja2: 2.6
       M2Crypto: 0.20.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.1.0
         PyYAML: 3.09
          PyZMQ: 13.1.0
            ZMQ: 3.2.3
```

Thanks in advance

**Comment by jfindlay** [comment]
@alienzrcoming, @invsblduck, do these errors happen on the latest version of salt (2015.5.3)?
