### ISSUE TITLE
mysql_grants isn't granular enough

### ISSUE THREAD

**Issue by mzupan** [saltstack/salt#13152]
It works great if you want to do something like

`grant select on dbName.* to user@'%'`

But if you want to do something like

`grant select (id,account_id,user_id) on dbName.account_notes to user@'%'`

It errors with

```
----------
          ID: recurly_account_notes_for_devin
    Function: mysql_grants.present
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/pymodules/python2.7/salt/state.py", line 1371, in call
                  **cdata['kwargs'])
                File "/usr/lib/pymodules/python2.7/salt/states/mysql_grants.py", line 123, in present
                  grant, database, user, host, grant_option, escape, **connection_args
                File "/usr/lib/pymodules/python2.7/salt/modules/mysql.py", line 1520, in grant_exists
                  grant, database, user, host, grant_option, escape
                File "/usr/lib/pymodules/python2.7/salt/modules/mysql.py", line 1436, in __grant_generate
                  grant = __grant_normalize(grant)
                File "/usr/lib/pymodules/python2.7/salt/modules/mysql.py", line 1414, in __grant_normalize
                  chkgrant
              Exception: Invalid grant : 'SELECT (ID'
```

my sls

```
account_notes_for_user:
  mysql_grants.present:
    - grant: 'select (id,account_id,user_id,created_at,updated_at,deleted_at)'
    - database: 'dbName.account_notes'
    - user: user
```

**Comment by gravyboat** [comment]
I'll add onto this and say that it doesn't support entering passwords at all. For example if I wanted to use the following query:
`GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED by 'password' WITH GRANT OPTION;`

While you can specify all the privileges, there's no way to add root, so this means that the only work around is to apply this command to each database individually via mysql_query which is a pain.
