### ISSUE TITLE
Salt-Cloud stacktraces when trying to create GoGrid Instance

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt#13365]
When writing some create/destroy instance test for cloud providers, GoGrid stacktraces due to a port connection timing out:
```
salt-cloud -p gogrid-test gogrid-testing
[INFO    ] salt-cloud starting
[INFO    ] Starting new HTTPS connection (1): api.digitalocean.com
[INFO    ] Creating Cloud VM gogrid-testing
[INFO    ] Rendering deploy script: /home/nicole/Dev/salt/salt/cloud/deploy/bootstrap-salt.sh
[ERROR   ] Port connection timed out: 900
[ERROR   ] Failed to start Salt on Cloud VM gogrid-testing
[ERROR   ] There was a profile error: 'GoGridNode' object is not iterable
Traceback (most recent call last):
  File "/home/nicole/Dev/salt/salt/cloud/cli.py", line 228, in run
    self.config.get('names')
  File "/home/nicole/Dev/salt/salt/cloud/__init__.py", line 1292, in run_profile
    ret[name] = self.create(vm_)
  File "/home/nicole/Dev/salt/salt/cloud/__init__.py", line 1162, in create
    output = self.clouds[func](vm_)
  File "/home/nicole/Dev/salt/salt/cloud/clouds/gogrid.py", line 260, in create
    ret.update(data)
TypeError: 'GoGridNode' object is not iterable
```
Version is on latest develop: 
```
salt --versions-report
           Salt: 2014.1.0-7276-gce43e04
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
            ZMQ: 4.0.4
```

**Comment by rallytime** [comment]
Tried this with the new REST API GoGrid driver: https://github.com/saltstack/salt/pull/24634

I can now successfully provision VMs on GoGrid.
