### ISSUE TITLE
salt-cloud failing and showing a traceback when trying to create a RHEL7 instance

### ISSUE THREAD

**Issue by nmadhok** [saltstack/salt#13401]
When trying to create an instance using salt-cloud, it fails and leaves a trace. There's something wrong with the bootstrap-script i believe and have opened another issue under there at https://github.com/saltstack/salt-bootstrap/issues/404

Here's the log:
```
 *  INFO: /bin/sh /tmp/.saltcloud/deploy.sh -- Version 2014.04.16
 *  WARN: Running the unstable version of bootstrap-salt.sh

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   3.10.0-123.el7.x86_64
 *  INFO:   Distribution: <R>ed <H>at <E>nterprise <L>inux 7.0

 *  INFO: Installing minion
 *  INFO: Found function install_red_hat_enterprise_linux_7_stable_deps
 *  INFO: Found function config_salt
 *  INFO: Found function install_red_hat_enterprise_linux_stable
 *  INFO: Found function install_red_hat_enterprise_linux_stable_post
 *  INFO: Found function install_red_hat_enterprise_linux_restart_daemons
[DEBUG   ]  *  INFO: /bin/sh /tmp/.saltcloud/deploy.sh -- Version 2014.04.16
 *  WARN: Running the unstable version of bootstrap-salt.sh

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   3.10.0-123.el7.x86_64
 *  INFO:   Distribution: <R>ed <H>at <E>nterprise <L>inux 7.0

 *  INFO: Installing minion
 *  INFO: Found function install_red_hat_enterprise_linux_7_stable_deps
 *  INFO: Found function config_salt
 *  INFO: Found function install_red_hat_enterprise_linux_stable
 *  INFO: Found function install_red_hat_enterprise_linux_stable_post
 *  INFO: Found function install_red_hat_enterprise_linux_restart_daemons
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/state.py", line 1492, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.6/site-packages/salt/states/cloud.py", line 106, in present
    info = __salt__['cloud.create'](cloud_provider, name, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/modules/cloud.py", line 202, in create
    info = client.create(provider, names, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 362, in create
    mapper.create(vm_))
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 1162, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/openstack.py", line 775, in create
    ret = salt.utils.cloud.bootstrap(vm_, __opts__)
  File "/usr/lib/python2.6/site-packages/salt/utils/cloud.py", line 418, in bootstrap
    deployed = deploy_script(**deploy_kwargs)
  File "/usr/lib/python2.6/site-packages/salt/utils/cloud.py", line 1204, in deploy_script
    deploy_command
SaltCloudSystemExit: Executing the command '/tmp/.saltcloud/deploy.sh -c /tmp/.saltcloud' failed

[INFO    ] Completed state [test.salt.clemson.edu] at time 16:28:10.283935
salt-mom.clemson.edu:
----------
          ID: test.salt.clemson.edu
    Function: cloud.present
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.6/site-packages/salt/state.py", line 1492, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.6/site-packages/salt/states/cloud.py", line 106, in present
                  info = __salt__['cloud.create'](cloud_provider, name, **kwargs)
                File "/usr/lib/python2.6/site-packages/salt/modules/cloud.py", line 202, in create
                  info = client.create(provider, names, **kwargs)
                File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 362, in create
                  mapper.create(vm_))
                File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 1162, in create
                  output = self.clouds[func](vm_)
                File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/openstack.py", line 775, in create
                  ret = salt.utils.cloud.bootstrap(vm_, __opts__)
                File "/usr/lib/python2.6/site-packages/salt/utils/cloud.py", line 418, in bootstrap
                  deployed = deploy_script(**deploy_kwargs)
                File "/usr/lib/python2.6/site-packages/salt/utils/cloud.py", line 1204, in deploy_script
                  deploy_command
              SaltCloudSystemExit: Executing the command '/tmp/.saltcloud/deploy.sh -c /tmp/.saltcloud' failed
     Started: 16:26:54.974331
     Duration: 309 ms
     Changes:   

Summary
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
[root@salt-mom ~]# 

```

**Comment by jfindlay** [comment]
@nmadhok, is this issue still valid?  Thanks.

**Comment by cachedout** [comment]
This could be related to the fix here: https://github.com/saltstack/salt/pull/21182

**Comment by nmadhok** [comment]
Haven't tested it after that. Haven't gotten the time to test this.

**Comment by cachedout** [comment]
@nmadhok OK. I'm going to go ahead and close this then. If salt-cloud were still broken on cent7, many other tests would be failing. Thanks for the update.
