### ISSUE TITLE
Unhandled Exception in Payload.py

### ISSUE THREAD

**Issue by jthigpen** [saltstack/salt#13508]
I'm getting this error on highstate.

```
2014-06-16 16:52:21,682 [salt.log.setup   ][ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: argument of type 'Poller' is not iterable
Traceback (most recent call last):
  File "/usr/bin/salt-minion", line 14, in <module>
    salt_minion()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 43, in salt_minion
    ret = minion.start()
  File "/usr/lib/python2.7/dist-packages/salt/__init__.py", line 253, in start
    self.prepare()
  File "/usr/lib/python2.7/dist-packages/salt/__init__.py", line 237, in prepare
    self.minion = salt.minion.Minion(self.config)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 646, in __init__
    if self.authenticate(timeout, safe) == 'full':
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1283, in authenticate
    creds = auth.sign_in(timeout, safe, tries)
  File "/usr/lib/python2.7/dist-packages/salt/crypt.py", line 348, in sign_in
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/salt/payload.py", line 216, in send_auto
    return self.send(enc, load, tries, timeout)
  File "/usr/lib/python2.7/dist-packages/salt/payload.py", line 204, in send
    self.clear_socket()
  File "/usr/lib/python2.7/dist-packages/salt/payload.py", line 181, in clear_socket
    if self._socket in self.poller:
TypeError: argument of type 'Poller' is not iterable
```

which appears to be relatively new code in 8a664b121d02a621d0d9f71a09017a7c3ed5004b by @jacksontj

This is on an unbuntu 12.04 box running latest salt.

**Comment by twangboy** [comment]
Fixed by https://github.com/saltstack/salt/pull/13540
