### ISSUE TITLE
salt-minion  crash when start

### ISSUE THREAD

**Issue by SOHUDBA** [saltstack/salt#13646]
salt version is：salt-2014.1.5
python version is :Python 2.6.8

```
2014-06-23 13:44:20,033 [salt.log.setup                           ][ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: string indices must be integers, not str
Traceback (most recent call last):
  File "/usr/bin/salt-minion", line 14, in <module>
    salt_minion()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 35, in salt_minion
    minion.start()
  File "/usr/lib/python2.6/site-packages/salt/__init__.py", line 224, in start
    self.minion.tune_in()
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 456, in tune_in
    minions = self.minions()
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 380, in minions
    minions = self._gen_minions()
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 370, in _gen_minions
    minions.append(Minion(s_opts, 5, False))
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 552, in __init__
    opts['environment'],
  File "/usr/lib/python2.6/site-packages/salt/pillar/__init__.py", line 73, in compile_pillar
    ret_pillar = self.sreq.crypted_transfer_decode_dictentry(load, dictkey='pillar', tries=3, timeout=7200)
  File "/usr/lib/python2.6/site-packages/salt/transport/__init__.py", line 61, in crypted_transfer_decode_dictentry
    aes = key.private_decrypt(ret['key'], 4)
TypeError: string indices must be integers, not str
```

**Comment by rallytime** [comment]
Since we never heard anything else about this, I am going to close this. If the problem persists, please leave a comment with the answer to the question posted above, and we will be glad to open this again. Thanks!
