### ISSUE TITLE
Salt Cloud stacktraces with bad credentials

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#14471]
Salt Cloud stack traces when bad credentials are used. This system is salt 2014.1.4, but I'm pretty sure it's the same on develop. Here's the output:
```
root@589882-Salt1:~# salt-cloud --list-sizes rackspace
[INFO    ] salt-cloud starting
[ERROR   ] Failed to get the output of 'openstack.avail_sizes()': 'Invalid credentials with the provider'
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/salt/cloud/__init__.py", line 539, in size_list
    data[alias][driver] = self.clouds[fun]()
  File "/usr/lib/pymodules/python2.7/salt/cloud/libcloudfuncs.py", line 210, in avail_sizes
    sizes = conn.list_sizes()
  File "/usr/lib/python2.7/dist-packages/libcloud/compute/drivers/openstack.py", line 297, in list_sizes
    self.connection.request('/flavors/detail').object)
  File "/usr/lib/python2.7/dist-packages/libcloud/compute/drivers/openstack.py", line 157, in request
    method=method, headers=headers)
  File "/usr/lib/python2.7/dist-packages/libcloud/common/openstack.py", line 575, in request
    return super(OpenStackBaseConnection, self).request(**kwargs)
  File "/usr/lib/python2.7/dist-packages/libcloud/common/base.py", line 596, in request
    action = self.morph_action_hook(action)
  File "/usr/lib/python2.7/dist-packages/libcloud/common/openstack.py", line 571, in morph_action_hook
    self._populate_hosts_and_request_paths()
  File "/usr/lib/python2.7/dist-packages/libcloud/common/openstack.py", line 600, in _populate_hosts_and_request_paths
    osa.authenticate()  # may throw InvalidCreds
  File "/usr/lib/python2.7/dist-packages/libcloud/common/openstack.py", line 155, in authenticate
    return self.authenticate_2_0_with_apikey()
  File "/usr/lib/python2.7/dist-packages/libcloud/common/openstack.py", line 240, in authenticate_2_0_with_apikey
    return self.authenticate_2_0_with_body(reqbody)
  File "/usr/lib/python2.7/dist-packages/libcloud/common/openstack.py", line 259, in authenticate_2_0_with_body
    raise InvalidCredsError()
InvalidCredsError: 'Invalid credentials with the provider'
rackspace:
    ----------
```

This is ugly.

**Comment by rallytime** [comment]
This stacktrace appears to now be cleaned up:
```
# salt-cloud --list-images rackspace
[INFO    ] salt-cloud starting
[ERROR   ] Failed to get the output of 'openstack.avail_images()': 'Invalid credentials with the provider'
rackspace:
    ----------
```
Versions Report:
``
# salt --versions
           Salt: 2015.5.2-116-g6c5b788
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.4
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
        Tornado: 4.0.2
```
