### ISSUE TITLE
Invalid credentials causes ugly traceback in Salt Cloud

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#14494]
I had my credentials set up incorrectly in Salt Cloud and instead of a nice error message I got this ugly traceback:

```
root@589882-Salt1:/etc/salt# time salt-cloud -p rs_1GB ua200
[INFO    ] salt-cloud starting
[INFO    ] Creating Cloud VM ua200
[ERROR   ] Error creating ua200 on OPENSTACK

Could not find image CentOS 6.5: 'Invalid credentials with the provider'
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/salt/cloud/clouds/openstack.py", line 360, in create
    kwargs['image'] = get_image(conn, vm_)
  File "/usr/lib/pymodules/python2.7/salt/cloud/libcloudfuncs.py", line 272, in get_image
    images = conn.list_images()
  File "/usr/lib/python2.7/dist-packages/libcloud/compute/drivers/openstack.py", line 293, in list_images
    self.connection.request('/images/detail').object, ex_only_active)
  File "/usr/lib/python2.7/dist-packages/libcloud/compute/drivers/openstack.py", line 157, in request
    method=method, headers=headers)
  File "/usr/lib/python2.7/dist-packages/libcloud/common/openstack.py", line 575, in request
    return super(OpenStackBaseConnection, self).request(**kwargs)
  File "/usr/lib/python2.7/dist-packages/libcloud/common/base.py", line 596, in request
    action = self.morph_action_hook(action)
  File "/usr/lib/python2.7/dist-packages/libcloud/common/openstack.py", line 571, in morph_action_hook
    self._populate_hosts_and_request_paths()
  File "/usr/lib/python2.7/dist-packages/libcloud/common/openstack.py", line 600, in _populate_hosts_and_request_paths
    osa.authenticate()  # may throw InvalidCreds
  File "/usr/lib/python2.7/dist-packages/libcloud/common/openstack.py", line 155, in authenticate
    return self.authenticate_2_0_with_apikey()
  File "/usr/lib/python2.7/dist-packages/libcloud/common/openstack.py", line 240, in authenticate_2_0_with_apikey
    return self.authenticate_2_0_with_body(reqbody)
  File "/usr/lib/python2.7/dist-packages/libcloud/common/openstack.py", line 259, in authenticate_2_0_with_body
    raise InvalidCredsError()
InvalidCredsError: 'Invalid credentials with the provider'
Error: There was a profile error: Failed to deploy VM
```
Can we get just the error message instead?

**Comment by rallytime** [comment]
This looks like a duplicate to #14471 to me. I am going to close this in favor of the older issue.
