### ISSUE TITLE
TypeError: string indices must be integers, not str

### ISSUE THREAD

**Issue by sfguy** [saltstack/salt#14730]
Running this

``root@salty /var/log/salt $ salt '*' state.sls common.ntp``

results in this

```salty.salt:
    TypeError encountered executing state.sls: string indices must be integers, not str. See debug log for more info.  Possibly a missing arguments issue:  ArgSpec(args=['mods', 'saltenv', 'test', 'exclude', 'queue', 'env'], varargs=None, keywords='kwargs', defaults=('base', None, None, False, None))
```

Here is the contents of the SLS file:

```
{% set ntp = salt['grains.filter_by']({
  'RedHat': {
      'package': 'ntp',
      'service': 'ntpd'},
  'Debian': {
      'package': 'ntp',
      'service': 'ntp'}
}) %}

ntp:
  pkg:
    - name: {{ ntp.package }}
    - installed
  service:
    - name: {{ ntp.service }}
    - enable: True
    - running

ntpdate:
  cron.present:
    - name: ntpdate
    - identifier: ntpdate
    - user: root
    - minute: 0
    - hour: 6
    - comment: daily time syncronization
```

**/var/log/salt/minion**

```
2014-08-05 02:13:54,552 [salt.minion      ][WARNING ] TypeError encountered executing state.sls:
 string indices must be integers, not str. See debug log for more info.  Possibly a missing arguments 
issue:  ArgSpec(args=['mods', 'saltenv', 'test', 'exclude', 'queue', 'env'], varargs=None, 
keywords='kwargs', defaults=('base', None, None, False, None))
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 797, in _thread_return
    return_data = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 381, in sls
    high_, errors = st_.render_highstate({saltenv: mods})
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2405, in render_highstate
    sls, saltenv, mods, matches)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2104, in render_state
    state_data = self.client.get_state(sls, saltenv)
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 413, in get_state
    dest = self.cache_file(path, saltenv)
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 143, in cache_file
    return self.get_url(path, '', True, saltenv)
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 503, in get_url
    return self.get_file(url, dest, makedirs, saltenv)
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 923, in get_file
    if not data['data']:
TypeError: string indices must be integers, not str
```

**Comment by leitao** [comment]
I had the same problem and I fixed it when install pycrypto in the master. 

In order to install it, I did the following:
 # sudo apt-get install python-pip python-dev
 # pip install pycrypto

**Comment by basepi** [comment]
@sfguy Can you try @leitao's solution and report?

I should note that Pycrypto is a stated hard dependency for Salt over ZMQ.

**Comment by basepi** [comment]
@sfguy Since we never heard back I'm going to assume you got this resolved. Thanks for the report! Feel free to comment if this is still an issue.
