### ISSUE TITLE
Windows stacktrace

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#14933]
On Windows I'm getting this error on the latest develop using salt-call. I'm having trouble tracking down where this is coming from.

```
C:\Python27\Scripts>python salt-call -l debug -c c:\salt\conf --local test.ping
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Failed to import returner :
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\salt\loader.py", line 615, in gen_module
    fn_, path, desc = imp.find_module(name, self.module_dirs)
ImportError: No module named
local:
    True
```
Versions_report - (Also showing the error)
```C:\Python27\Scripts>python salt-call -l debug -c c:\salt\conf --local test.versi
ons_report
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Failed to import returner :
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\salt\loader.py", line 615, in gen_module
    fn_, path, desc = imp.find_module(name, self.module_dirs)
ImportError: No module named
local:
               Salt: 2014.7.0rc1-686-gbbf724d
             Python: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (
AMD64)]
             Jinja2: 2.7.1
           M2Crypto: 0.21.1
     msgpack-python: 0.4.2
       msgpack-pure: Not Installed
           pycrypto: 2.6
            libnacl: Not Installed
             PyYAML: 3.11
              ioflo: Not Installed
              PyZMQ: 14.1.1
               RAET: Not Installed
                ZMQ: 4.0.4
               Mako: Not Installed
                                            
C:\Python27\Scripts>python salt-call -l debug -c c:\salt\conf --local test.versi
ons_report
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Failed to import returner :
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\salt\loader.py", line 615, in gen_module
    fn_, path, desc = imp.find_module(name, self.module_dirs)
ImportError: No module named
local:
               Salt: 2014.7.0rc1-686-gbbf724d
             Python: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (
AMD64)]
             Jinja2: 2.7.1
           M2Crypto: 0.21.1
     msgpack-python: 0.4.2
       msgpack-pure: Not Installed
           pycrypto: 2.6
            libnacl: Not Installed
             PyYAML: 3.11
              ioflo: Not Installed
              PyZMQ: 14.1.1
               RAET: Not Installed
                ZMQ: 4.0.4
               Mako: Not Installed
                                            
```

**Comment by UtahDave** [comment]
I'm no longer getting this problem on the 2014.7 branch.
