### ISSUE TITLE
salt-cloud GCE metadata handling bug?

### ISSUE THREAD

**Issue by raphtheb** [saltstack/salt#14985]
Hi, 

I am encountering an issue with creating arbitrary nodes on GCE using salt-cloud. Version reports below.

I believe i have identified the issue as being part of the metadata output, but cannot quite pinpoint why it would fail. This debug output is the one that fails:

```
[DEBUG   ] Create instance kwargs {'ex_metadata': {'items': [{'value': 'testbox', 'key': 'salt-cloud-profile'}]}, 'name': 'test1', 'ex_tags': ['minion', 'salt'], 'ex_network': <GCENetwork id="1234567890" name="testnet" cidr="10.0.0.0/8">, 'location': <GCEZone id="1234567890" name="us-central1-a" status="UP">, 'image': <NodeImage: id=10742104427832349917, name=debian-7-wheezy-v20140807, driver=Google Compute Engine  ...>, 'size': <NodeSize: id=4618642685664990776, name=f1-micro, ram=614 disk=0 bandwidth=0 price=None driver=Google Compute Engine ...>}
```
Traceback:
```
[ERROR   ] Error creating failtobuild on GCE

The following exception was thrown by libcloud when trying to run the initial deployment: 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/gce.py", line 523, in create
    node_data = conn.create_node(**kwargs)  # pylint: disable=W0142
  File "/usr/local/lib/python2.7/dist-packages/libcloud/compute/drivers/gce.py", line 1211, in create_node
    self.connection.async_request(request, method='POST', data=node_data)
  File "/usr/local/lib/python2.7/dist-packages/libcloud/common/base.py", line 813, in async_request
    response = request(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/libcloud/common/google.py", line 593, in request
    *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/libcloud/common/base.py", line 683, in request
    response = responseCls(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/libcloud/common/base.py", line 118, in __init__
    self.object = self.parse_body()
  File "/usr/local/lib/python2.7/dist-packages/libcloud/common/google.py", line 230, in parse_body
    raise InvalidRequestError(message, self.status, code)
InvalidRequestError: {'domain': 'global', 'message': "Required field 'value' not specified", 'reason': 'required'}
Error: There was a profile error: Failed to deploy VM
```

Now if i comment out the use of metadata completely (/usr/lib/python2.7/dist-packages/salt/cloud/clouds/gce.py:502), i can send this query which works flawlessly:
```
[DEBUG   ] Create instance kwargs {'name': 'test1', 'ex_tags': ['minion', 'salt'], 'ex_network': <GCENetwork id=1234567890" name="testnet" cidr="10.0.0.0/8">, 'location': <GCEZone id=1234567890" name="us-central1-a" status="UP">, 'image': <NodeImage: id=10742104427832349917, name=debian-7-wheezy-v20140807, driver=Google Compute Engine  ...>, 'size': <NodeSize: id=4618642685664990776, name=f1-micro, ram=614 disk=0 bandwidth=0 price=None driver=Google Compute Engine ...>}
```

Now i am aware that libcloud is the one throwing out the error, so perhaps this report would be better sent over there. If that is the case, please let me know! That being said, the traceback does hint at a malformed request, request which i do believe is formed here?

Cheers!

Here's the content of my profile/provider files (with some obvious censorship)
```
gce-config:

  project: "censored"
  service_account_email_address: "abc@censored.com"
  service_account_private_key: "key.pem"
  minion:
    master: salt-01.gce.internal

  grains:
    node_type: broker
    release: 1.0.1

  provider: gce
  flush_mine_on_destroy: True
```

```
testbox:
  image: debian-7
  size: f1-micro
  location: us-central1-a
  network: testnet
  make_master: False
  deploy: True
  delete_boot_pd: True
  tags: '["minion", "salt"]'
  metadata: None
  provider: gce-config
```
Note that i have tried using the metadata field as instructed by the specs, too. It creates the same error output as "None" does.

```
$ salt-cloud --versions-report
            Salt: 2014.1.10
          Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
          Jinja2: 2.6
        M2Crypto: 0.21.1
  msgpack-python: 0.1.10
    msgpack-pure: Not Installed
        pycrypto: 2.6
          PyYAML: 3.10
           PyZMQ: 13.1.0
             ZMQ: 3.2.3
 Apache Libcloud: 0.15.1

$ lsb_release -a
Distributor ID:	Debian
Description:	Debian GNU/Linux 7.6 (wheezy)
Release:	7.6
Codename:	wheezy
```

**Comment by techhat** [comment]
Looks like this was fixed a while ago. Please reopen if necessary.
