### ISSUE TITLE
Docker Pull not working

### ISSUE THREAD

**Issue by rawkode** [saltstack/salt#15053]
Docker command works fine:
```
docker pull teamrock/nginx
```

SLS:
```
teamrock/nginx:
  docker.pulled:
      - tag: master
```
I've also tried:
```

docker_container_teamrock_nginx:
  docker.pulled:
      - name: teamrock/nginx
      - tag: master
```

Output:
```
----------
          ID: teamrock/nginx
    Function: docker.pulled
      Result: False
     Comment: We did not get any expectable answer from docker
              Traceback (most recent call last):
                File "/usr/lib/python2.6/site-packages/salt/modules/dockerio.py", line 1651, in pull
                  image_logs, infos = _parse_image_multilogs_string(ret, repo)
                File "/usr/lib/python2.6/site-packages/salt/modules/dockerio.py", line 1545, in _parse_image_multilogs_string
                  infos = _get_image_infos(repo)
                File "/usr/lib/python2.6/site-packages/salt/modules/dockerio.py", line 317, in _get_image_infos
                  'an existing Image'.format(image)
              CommandExecutionError: ImageID 'teamrock/nginx' could not be resolved to an existing Image
     Started: 
     Duration: 
     Changes:   
              ----------
              teamrock/nginx:
                  ----------
                  new:
                      teamrock/nginx
                  old:
                      None
```

salt-minion debug:
```
[INFO    ] Executing state docker.pulled for teamrock/nginx

[DEBUG   ] "GET /run/docker.sock/v1.12/version HTTP/1.1" 200 164
[DEBUG   ] "GET /run/docker.sock/v1.12/images/teamrock/nginx/json HTTP/1.1" 404 30
[DEBUG   ] "GET /run/docker.sock/v1.12/version HTTP/1.1" 200 164
[DEBUG   ] "POST /run/docker.sock/v1.12/images/create?tag=master&fromImage=teamrock%2Fnginx HTTP/1.1" 200 None
[TRACE   ] Check main poller timeout 1
[TRACE   ] Check main poller timeout 1
[DEBUG   ] "GET /run/docker.sock/v1.12/version HTTP/1.1" 200 164
[DEBUG   ] "GET /run/docker.sock/v1.12/images/teamrock/nginx/json HTTP/1.1" 404 30
[ERROR   ] Installed Packages:
teamrock/nginx changed from absent to teamrock/nginx

[INFO    ] Completed state [teamrock/nginx] at time 19:51:57.009859
```

**Comment by msteed** [comment]
Closing as fixed by the above PR. Feel free to reopen or create a new issue if the problem still occurs.
