### ISSUE TITLE
On first run "State docker.xxx found in sls is unavailable"

### ISSUE THREAD

**Issue by akafred** [saltstack/salt#15803]
On the first run this state fails with "State docker.pulled found in sls is unavailable" - second run it succeeds:
```
# dockerpy-salt-issue.sls
docker.io:
  pkg.installed
 
docker-py:
  pkg.installed:
    - name: python-pip
  pip.installed:
    - require:
      - pkg: python-pip
 
mysql:
  docker.pulled
```

Command run: `sudo salt-call --local state.sls dockerpy-salt-issue`

Versions:
```
# salt-call --versions
           Salt: 2014.1.10
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
            ZMQ: 4.0.4
```

This, and logs from first and second run can be found here: https://gist.github.com/akafred/b420d0bbb53cb21af39f

**Comment by rgreinho** [comment]
The issue seems to still exist:

```
docker-pull-nginx:
  docker.pulled:
    - name: nginx
```
results in:
```
----------
          ID: docker-pull-nginx
    Function: docker.pulled
        Name: nginx
      Result: False
     Comment: State 'docker.pulled' found in SLS 'analytics.containers' is unavailable
     Started:
    Duration:
     Changes:
```
but works like a charm if I execute my state a second time.

```
$ salt-call --versions-report
           Salt: 2014.7.0
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
```
and ``docker-py==0.7.1``.

**Comment by basepi** [comment]
@rgreinho Is that the only state you're executing? I feel like you must have at least one other state that changes something, in order for the second run to be successful.

**Comment by rgreinho** [comment]
You're right, my full ``container.sls`` file looks like this:

```
#docker-pull-nginx:
#  docker.pulled:
#    - name: nginx
#    - require:
#      - service: docker-service
#      - pip: pip-docker-py

cmd-nginx-image-pull:
  cmd.run:
    - name: docker pull nginx
    - require:
      - service: docker-service

docker-install-nginx:
  docker.installed:
    - name: nginx
    - image: nginx
    - require:
      - cmd: cmd-nginx-image-pull
      - pip: pip-docker-py

docker-run-nginx:
  docker.running:
    - name: nginx
    - container: nginx
    - image: nginx
    - port_bindings:
      "80/tcp":
        HostIp: ""
        HostPort: "80"
    - volumes:
      - /code:
        bind: /usr/share/nginx/html
        ro: True
    - restart_policy:
        Name: always
    - require:
      - docker: docker-install-nginx

pip-docker-py:
  pip.installed:
    - name: docker-py
    - require:
      - pkg: python2
      - pkg: python2-pip
```

I use the ``docker`` and ``python`` formula. 

My workaround was to replace the ``docker.pulled`` function with the equivalent ``cmd.run``.

**Comment by basepi** [comment]
Ah, yep, I see it. This comes back to the `pip` state functions not triggering a module refresh like the `pkg` state functions do. If you add `reload_modules: True` to your pip state that should fix your issue:

```
pip-docker-py:
  pip.installed:
    - name: docker-py
    - reload_modules: True
    - require:
      - pkg: python2
      - pkg: python2-pip
```

**Comment by rgreinho** [comment]
That worked! Thank you so much.

**Comment by basepi** [comment]
Awesome, glad we figured it out!

**Comment by pgporada** [comment]
I am experiencing a related issue. It may be my own ignorance though, but I'd appreciate a fresh set of eyes.

```
[root@master /srv/salt]$ salt master test.ping
master:
    True
```

/srv/salt/top.sls
```
base:
  '*':
    - common_packages
    - hosts
    - resolv
  'role:master':
    - match: grain
    - docker-py                    # Loads the /srv/salt/docker-py/init.sls
    - docker                         # Loads /srv/salt/docker/init.sls
    - dock_apache              # Loads /srv/salt/dock_apache/init.sls => https://github.com/UtahDave/dock_apache
```

/srv/salt/docker-py/init.sls (installs fine)
```
docker-py: 
  pkg.installed: 
    - name: python-pip 
  pip.installed: 
    - name: docker-py 
    - reload_modules: True 
    - require: 
      - pkg: python-pip 
```
```
[root@master /srv/salt]$ pip list | grep docker
docker-py (0.7.2)
```

/srv/salt/docker/init.sls (installs fine and gives me a newer docker version than cent7 has)
```
docker:
  pkg.installed:
  - sources:
    - docker: http://cbs.centos.org/kojifiles/packages/docker/1.4.1/2.el7/x86_64/docker-1.4.1-2.el7.x86_64.rpm
  service.running:
  - name: docker
  - enable: True
```
```
[root@master /srv/salt]$ docker version
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8/1.4.1
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8/1.4.1
```

Example of it working
```
root@master /srv/salt]$ docker ps
CONTAINER ID        IMAGE                   COMMAND                CREATED             STATUS              PORTS                    NAMES
3a84541c96ff        rancher/server:latest   "/usr/share/cattle/c   24 minutes ago      Up 24 minutes       0.0.0.0:8080->8080/tcp   modest_heisenberg 
```

/srv/salt/dock_apache/init.sls (not working)
```
apache-image:
  docker.pulled:
    - name: utahdave/saltdemo
    - require_in: apache-container

apache-container:
  docker.installed:
    - name: apache
    - hostname: apache
    - image: utahdave/saltdemo
    - require_in: apache

apache:
  docker.running:
    - container: apache
    - ports:
      - "80/tcp":
        HostIp: ""
        HostPort: "80"
```

However, when I try to run the dock_apache container, it fails on the docker-py provided functions
```
          ID: apache-image
    Function: docker.pulled
        Name: utahdave/saltdemo
      Result: False
     Comment: State 'docker.pulled' found in SLS 'dock_apache' is unavailable
     Started: 
    Duration: 
     Changes:   
----------
          ID: apache-container
    Function: docker.installed
        Name: apache
      Result: False
     Comment: State 'docker.installed' found in SLS 'dock_apache' is unavailable
     Started: 
    Duration: 
     Changes:   
----------
          ID: apache
    Function: docker.running
      Result: False
     Comment: State 'docker.running' found in SLS 'dock_apache' is unavailable
     Started: 
    Duration: 
     Changes: 
```

**Comment by basepi** [comment]
@pgporada Can you do `import docker` in a python2 shell?

**Comment by pgporada** [comment]
Basepi, per the refrenced ticket #20560, I have run python2 and tried to import docker.
```
[root@master ~]$ python2
Python 2.7.5 (default, Jun 17 2014, 18:11:42) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import docker
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/docker/__init__.py", line 20, in <module>
    from .client import Client # flake8: noqa
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 34, in <module>
    import websocket
  File "/usr/lib/python2.7/site-packages/websocket/__init__.py", line 21, in <module>
    from ._core import *
  File "/usr/lib/python2.7/site-packages/websocket/_core.py", line 43, in <module>
    from six.moves.urllib.parse import urlparse
ImportError: No module named urllib.parse
```

The error there that stuck out was "six.moves.urllib.parse import urlparse." I then ran the following commands. The module six had a much needed upgrade
```
pip install six --upgrade
pip install urlparse3
```
```
[root@master ~]$ pip install six --upgrade
Downloading/unpacking six from https://pypi.python.org/packages/3.3/s/six/six-1.9.0-py2.py3-none-any.whl#md5=9ac7e129a80f72d6fc1f0216f6e9627b
  Downloading six-1.9.0-py2.py3-none-any.whl
Installing collected packages: six
  Found existing installation: six 1.3.0
    Uninstalling six:
      Successfully uninstalled six
Successfully installed six
Cleaning up...
```

This resulted in me being able to successfully import docker in the python2 shell.
```
[root@master ~]$ python2
Python 2.7.5 (default, Jun 17 2014, 18:11:42) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import docker
>>> exit()
```

As of this time, I have the following modules that relate to docker-py installed.
```
[root@master /srv/salt]$ pip list | egrep '(six|docker|urllib|urlparse)'
docker-py (0.7.2)
six (1.9.0)
urllib3 (1.5)
urlparse3 (1.0.3)
```

When I run the dock_apache state or any other state to launch a docker image from salt, I still receive the following
```
[root@master /srv/salt]$ salt master state.sls dock_apache
master:
----------
          ID: pip-docker-py-with-requirements
    Function: pip.installed
        Name: docker-py
      Result: True
     Comment: Python package docker-py already installed
     Started: 09:15:50.214698
    Duration: 365.141 ms
     Changes:   
----------
          ID: apache-image
    Function: docker.pulled
        Name: utahdave/saltdemo
      Result: False
     Comment: State 'docker.pulled' found in SLS 'dock_apache' is unavailable
     Started: 
    Duration: 
     Changes:   
----------
          ID: apache-container
    Function: docker.installed
        Name: apache
      Result: False
     Comment: State 'docker.installed' found in SLS 'dock_apache' is unavailable
     Started: 
    Duration: 
     Changes:   
----------
          ID: apache
    Function: docker.running
      Result: False
     Comment: State 'docker.running' found in SLS 'dock_apache' is unavailable
     Started: 
    Duration: 
     Changes:   

Summary
------------
Succeeded: 1
Failed:    3
------------
Total states run:     4
```

**Comment by basepi** [comment]
Is your `master` minion the minion that is on your master machine? `docker` must be importable by python on the minion in question in order for those functions to work.

The other thing that may be causing this problem is if you have multiple instances of python installed. `docker` must be importable from within the minion code, so it's possible docker has been installed for the wrong version of python?

**Comment by pgporada** [comment]
The master minion is the minion on the master machine. I have the default python versions that come with Centos 7.
```
[root@master ~]$ ll /bin/python*
lrwxrwxrwx. 1 root root    7 Jan 19 21:52 /bin/python -> python2
lrwxrwxrwx. 1 root root    9 Jan 19 21:52 /bin/python2 -> python2.7
-rwxr-xr-x. 1 root root 7136 Jun 17  2014 /bin/python2.7
[root@master ~]$ python2.7 --version
Python 2.7.5

[root@master ~]$ pip --version
pip 1.5.6 from /usr/lib/python2.7/site-packages (python 2.7)
[root@master ~]$ cd /usr/lib/p
polkit-1/  python2.7/ 
[root@master ~]$ cd /usr/lib/python2.7/
```

I ran the dock_apache state again with minion debugging and received the following
```
[INFO    ] Python package docker-py already installed
[DEBUG   ] Refreshing modules...
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] SaltEvent PUB socket URI: ipc:///var/run/salt/minion/minion_event_eb0a191797_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: ipc:///var/run/salt/minion/minion_event_eb0a191797_pull.ipc
[DEBUG   ] Sending event - data = {'_stamp': '2015-02-12T15:21:47.493889'}
[DEBUG   ] Handling event 'module_refresh||||||\x81\xa6_stamp\xba2015-02-12T15:21:47.493889'
[DEBUG   ] Reading configuration from /etc/salt/minion
[INFO    ] Completed state [docker-py] at time 15:21:47.533249
[INFO    ] Running state [utahdave/saltdemo] at time 15:21:47.533876
[INFO    ] Executing state docker.pulled for utahdave/saltdemo
[DEBUG   ] "GET /run/docker.sock/v1.16/version HTTP/1.1" 200 163
[DEBUG   ] "GET /run/docker.sock/v1.16/images/utahdave/saltdemo/json HTTP/1.1" 404 33
[DEBUG   ] "GET /run/docker.sock/v1.16/version HTTP/1.1" 200 163
[DEBUG   ] "POST /run/docker.sock/v1.16/images/create?fromImage=utahdave%2Fsaltdemo HTTP/1.1" 200 None
[ERROR   ] 
An error occurred pulling your image

{"status":"Repository utahdave/saltdemo already being pulled by another client. Waiting."}

[INFO    ] Completed state [utahdave/saltdemo] at time 15:22:18.965579
[INFO    ] Running state [apache] at time 15:22:18.965767
[INFO    ] Executing state docker.installed for apache
[DEBUG   ] "GET /run/docker.sock/v1.16/version HTTP/1.1" 200 163
[DEBUG   ] "GET /run/docker.sock/v1.16/images/utahdave/saltdemo/json HTTP/1.1" 200 1666
[DEBUG   ] "GET /run/docker.sock/v1.16/version HTTP/1.1" 200 163
[DEBUG   ] "GET /run/docker.sock/v1.16/containers/apache/json HTTP/1.1" 404 26
[DEBUG   ] "GET /run/docker.sock/v1.16/version HTTP/1.1" 200 163
[DEBUG   ] "GET /run/docker.sock/v1.16/version HTTP/1.1" 200 163
[DEBUG   ] "GET /run/docker.sock/v1.16/images/9ae6ce53901e/json HTTP/1.1" 200 1666
[INFO    ] Installed Packages:
utahdave/saltdemo changed from absent to 9ae6ce53901ef23feaa7f7ab915b86f04dad02b6ceaa8e8e62487224102dd1d3

[INFO    ] Completed state [utahdave/saltdemo] at time 15:22:19.045432
[INFO    ] Running state [apache] at time 15:22:19.045597
[INFO    ] Executing state docker.installed for apache
[DEBUG   ] "GET /run/docker.sock/v1.16/version HTTP/1.1" 200 163
[DEBUG   ] "GET /run/docker.sock/v1.16/images/utahdave/saltdemo/json HTTP/1.1" 200 1666
[DEBUG   ] "GET /run/docker.sock/v1.16/version HTTP/1.1" 200 163
[DEBUG   ] "GET /run/docker.sock/v1.16/containers/apache/json HTTP/1.1" 200 1578
[INFO    ] image 'apache' already exists
[INFO    ] Completed state [apache] at time 15:22:19.067573
```

Even though my state errors out, I can see that the container did eventually start AFTER running the state initially with debugging mode.
```
[root@master /srv/salt]$ salt master state.sls dock_apache
master:
----------
          ID: pip-docker-py-with-requirements
    Function: pip.installed
        Name: docker-py
      Result: True
     Comment: Python package docker-py already installed
     Started: 15:27:45.171788
    Duration: 5436.475 ms
     Changes:   
----------
          ID: apache-image
    Function: docker.pulled
        Name: utahdave/saltdemo
      Result: False
     Comment: State 'docker.pulled' found in SLS 'dock_apache' is unavailable
     Started: 
    Duration: 
     Changes:   
----------
          ID: apache-container
    Function: docker.installed
        Name: apache
      Result: False
     Comment: State 'docker.installed' found in SLS 'dock_apache' is unavailable
     Started: 
    Duration: 
     Changes:   
----------
          ID: apache
    Function: docker.running
      Result: False
     Comment: State 'docker.running' found in SLS 'dock_apache' is unavailable
     Started: 
    Duration: 
     Changes:   

Summary
------------
Succeeded: 1
Failed:    3
------------
Total states run:     4
[root@master /srv/salt]$ docker ps
CONTAINER ID        IMAGE                      COMMAND                CREATED             STATUS              PORTS                    NAMES
3bd5f9fcbd66        utahdave/saltdemo:latest   "/run.sh"              5 minutes ago       Up About a minute   80/tcp                   apache  
```

**Comment by dverbeek84** [comment]
I have got the same issue. Suddenly after changing a lot of things it work, but i am stil figuring out what i have changed.

I am running a CentOS7.

```
ID: ubuntu
Function: docker.pulled
Result: False
Comment: State 'docker.pulled' found in SLS 'dck' is unavailable
Started: 
Duration: 
Changes: 
```

```
[root@haproxy ~]# docker version
Client version: 1.3.2
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): 39fa2fa/1.3.2
OS/Arch (client): linux/amd64
Server version: 1.3.2
Server API version: 1.15
Go version (server): go1.3.3
Git commit (server): 39fa2fa/1.3.2
```

```
[root@haproxy ~]# pip list
Babel (0.9.6)
backports.ssl-match-hostname (3.4.0.2)
chardet (2.0.1)
configobj (4.7.2)
decorator (3.4.0)
docker-py (0.6.0)
iniparse (0.4)
Jinja2 (2.7.2)
kitchen (1.1.1)
M2Crypto (0.21.1)
MarkupSafe (0.11)
msgpack-python (0.4.2)
pip (1.5.6)
pycrypto (2.6.1)
pycurl (7.19.0)
pygobject (3.8.2)
pygpgme (0.3)
pyliblzma (0.5.3)
pyudev (0.15)
pyxattr (0.5.1)
PyYAML (3.10)
pyzmq (14.3.1)
requests (2.4.3)
salt (2014.7.0)
setuptools (0.9.8)
six (1.3.0)
slip (0.4.0)
slip.dbus (0.4.0)
urlgrabber (3.10)
urllib3 (1.5)
websocket-client (0.23.0)
wsgiref (0.1.2)
yum-metadata-parser (1.1.4)
```

```
docker:
  pkg:
    - installed
  service.running:
    - enable: True

python-pip:
  pkg:
    - installed

docker-py:
  pip.installed:
    - name: docker-py == 0.6.0
    - require:
      - pkg: python-pip

ubuntu:
   docker.pulled
     - name: ubuntu
```

```
           Salt: 2014.7.0
         Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed
```

**Comment by dverbeek84** [comment]
Ok i find a way to solve it.

`pip install docker-py` installed six version 1.3.0. 
If you upgrade six 1.9.0 it works. Only you first need to restart the minion. 

I am not that good in python so i don't know where to look. But upgrading six to 1.9.0 and restarting the minion works.
