### ISSUE TITLE
OpenBSD tests: minions fail to connect

### ISSUE THREAD

**Issue by ajacoutot** [saltstack/salt#15864]
Hi.

In the process of making OpenBSD a better supported platform for SaltStack, I am running the regression tests (with Salt-Testing).
However I can running into the following issue and I don't understand the underlying problem...
Any help/input is appreciated :-)
Thanks.

This is the command I run as root (salt 2014.1.11, salt-testing 2014.8.5):

```
python2.7 tests/runtests.py -m -vvvvv


 * [Quit in 0:02:00] Waiting for minion, sub_minion12:30:43,333 [salt.config                                 :514 ][DEBUG   ] Reading configuration from /home/cvs/ports/pobj/salt-2014.1.11/salt-2014.1.11/tests/integration/files/conf/master
12:30:43,434 [salt.utils.event                            :179 ][DEBUG   ] LocalClientEvent PUB socket URI: ipc:///tmp/salttest/.salt-unix/master_event_pub.ipc
12:30:43,442 [salt.config                                 :594 ][DEBUG   ] Missing configuration file: /root/.saltrc
12:30:43,533 [salt.utils.event                            :182 ][DEBUG   ] LocalClientEvent PULL socket URI: ipc:///tmp/salttest/.salt-unix/master_event_pull.ipc
12:30:43,534 [salt.utils.event                            :179 ][DEBUG   ] LocalClientEvent PUB socket URI: ipc:///tmp/salttest/.salt-unix/master_event_pub.ipc
12:30:43,633 [salt.utils.event                            :182 ][DEBUG   ] LocalClientEvent PULL socket URI: ipc:///tmp/salttest/.salt-unix/master_event_pull.ipc
12:30:43,733 [salt.minion                                 :1605][DEBUG   ] Syndic "minion" trying to tune in
12:30:43,736 [salt.master                                 :801 ][INFO    ] AES payload received with command _minion_event
12:30:44,634 [salt.master                                 :801 ][INFO    ] AES payload received with command _minion_event
12:31:17,757 [salt.fileserver                             :232 ][DEBUG   ] Updating fileserver cache
12:31:17,766 [salt.fileserver                             :131 ][DEBUG   ] diff_mtime_map: the maps are the same
12:31:17,767 [salt.utils.verify                           :387 ][DEBUG   ] This salt-master instance has accepted 2 minion keys.
12:31:17,767 [salt.pillar.git_pillar                      :163 ][DEBUG   ] Updating fileserver for git_pillar module
12:31:18,761 [salt.pillar.git_pillar                      :163 ][DEBUG   ] Updating fileserver for git_pillar module
12:31:34,657 [salt.fileserver                             :232 ][DEBUG   ] Updating fileserver cache
12:31:34,658 [salt.fileserver                             :131 ][DEBUG   ] diff_mtime_map: the maps are the same
12:31:34,659 [salt.utils.verify                           :387 ][DEBUG   ] This salt-master instance has accepted 1 minion keys.
12:32:19,838 [salt.fileserver                             :232 ][DEBUG   ] Updating fileserver cache
12:32:19,847 [salt.fileserver                             :131 ][DEBUG   ] diff_mtime_map: the maps are the same
12:32:19,847 [salt.utils.verify                           :387 ][DEBUG   ] This salt-master instance has accepted 2 minion keys.
12:32:19,848 [salt.pillar.git_pillar                      :163 ][DEBUG   ] Updating fileserver for git_pillar module
12:32:20,763 [salt.pillar.git_pillar                      :163 ][DEBUG   ] Updating fileserver for git_pillar module
12:32:34,668 [salt.fileserver                             :232 ][DEBUG   ] Updating fileserver cache
12:32:34,669 [salt.fileserver                             :131 ][DEBUG   ] diff_mtime_map: the maps are the same
12:32:34,670 [salt.utils.verify                           :387 ][DEBUG   ] This salt-master instance has accepted 1 minion keys.
12:33:21,948 [salt.fileserver                             :232 ][DEBUG   ] Updating fileserver cache
12:33:21,957 [salt.fileserver                             :131 ][DEBUG   ] diff_mtime_map: the maps are the same
12:33:21,958 [salt.utils.verify                           :387 ][DEBUG   ] This salt-master instance has accepted 2 minion keys.
12:33:21,958 [salt.pillar.git_pillar                      :163 ][DEBUG   ] Updating fileserver for git_pillar module
12:33:22,764 [salt.pillar.git_pillar                      :163 ][DEBUG   ] Updating fileserver for git_pillar module
12:33:34,678 [salt.fileserver                             :232 ][DEBUG   ] Updating fileserver cache
12:33:34,680 [salt.fileserver                             :131 ][DEBUG   ] diff_mtime_map: the maps are the same
12:33:34,680 [salt.utils.verify                           :387 ][DEBUG   ] This salt-master instance has accepted 1 minion keys.
12:33:43,588 [salt.client                                 :1391][ERROR   ] Salt request timed out. If this error persists, worker_threads may need to be increased.
Process Process-6:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cvs/ports/pobj/salt-2014.1.11/salt-2014.1.11/tests/integration/__init__.py", line 539, in wait_for_minion_connections
    list(expected_connections), 'test.ping', expr_form='list',
  File "/home/cvs/ports/pobj/salt-2014.1.11/salt-2014.1.11/salt/client/__init__.py", line 515, in cmd
    **kwargs)
  File "/home/cvs/ports/pobj/salt-2014.1.11/salt-2014.1.11/salt/client/__init__.py", line 274, in run_job
    return self._check_pub_data(pub_data)
  File "/home/cvs/ports/pobj/salt-2014.1.11/salt-2014.1.11/salt/client/__init__.py", line 211, in _check_pub_data
    'Failed to authenticate, is this user permitted to execute '
EauthAuthenticationError: Failed to authenticate, is this user permitted to execute commands?

 * ERROR: Minions failed to connect
```

**Comment by eradman** [comment]
I have tried to run the integration tests on OpenBSD as well, but am stuck on the same problem.

**Comment by rallytime** [comment]
@jtand FYI - You might want to be aware of this issue.

**Comment by eradman** [comment]
I think the entire problem here is that by default `requirements.txt` installed an old version of SaltTesting (see #37366).

Integration tests run on OpenBSD now!

    (saltenv) $ python2.7 tests/runtests.py -m
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * Transplanting configuration files to '/tmp/salt-tests-tmpdir/config'
     * Current Directory: /home/eradman/git/salt
     * Test suite is running under PID 85317
     * Logging tests on /tmp/salt-runtests.log
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * Setting up Salt daemons to execute tests
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * Starting salt-master ... STARTED!
     * Starting salt-minion ... STARTED!
     * Starting sub salt-minion ... STARTED!
     * Starting syndic salt-master ... STARTED!
     * Starting salt-syndic ... STARTED!
    ================================================================================
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Starting Module Tests
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    <snip>

    ================================================================================
    FAILED (total=466, skipped=270, passed=181, failures=12, errors=3)

    $ uname -srp
    OpenBSD 6.0 amd64

**Comment by eradman** [comment]
Correction: this ticket was placed in 2014, so the trouble I encountered likely has a different cause. @ajacoutot, do you have time to re-test in your environment?

**Comment by ajacoutot** [comment]
Yup, I just tested an indeed it works \o/
