### ISSUE TITLE
Azure: salt-cloud -d <vm-name> doesn't work.

### ISSUE THREAD

**Issue by egilh** [saltstack/salt#15958]
I have an issue where VM's are created, but no hostname is returned to the master.
This means no salt installation occurs and the minion has to be added manually.
When trying to delete the VM I get an error saying no VM's where found.

```
            Salt: 2014.7.0rc2
          Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
          Jinja2: 2.7.2
        M2Crypto: 0.21.1
  msgpack-python: 0.3.0
    msgpack-pure: Not Installed
        pycrypto: 2.6.1
         libnacl: Not Installed
          PyYAML: 3.10
           ioflo: Not Installed
           PyZMQ: 14.0.1
            RAET: Not Installed
             ZMQ: 4.0.4
            Mako: 0.9.1
 Apache Libcloud: 0.14.1
```

```
root@salt-master:# salt-cloud -d yrdocker2
[DEBUG   ] Configuration file path: /etc/salt/cloud
[INFO    ] salt-cloud starting
[DEBUG   ] There is no IBM SCE cloud provider configuration available. Not loading module.
[DEBUG   ] 'parallels.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'parallels.avail_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'proxmox.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'saltify.destroy' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'saltify.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'saltify.avail_images' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'saltify.avail_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'rackspace.reboot' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] The 'azure' cloud driver is unable to be optimized.
[DEBUG   ] There is no IBM SCE cloud provider configuration available. Not loading module.
[DEBUG   ] 'parallels.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'parallels.avail_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'proxmox.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'saltify.destroy' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'saltify.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'saltify.avail_images' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'saltify.avail_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'rackspace.reboot' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] Failed to execute 'azure.list_nodes()' while querying for running nodes: Not found (Not Found)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 2195, in run_parallel_map_providers_query
    cloud.clouds[data['fun']]()
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/msazure.py", line 240, in list_nodes
    nodes = list_nodes_full(conn, call)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/msazure.py", line 259, in list_nodes_full
    services = list_hosted_services(conn=conn, call=call)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/msazure.py", line 361, in list_hosted_services
    role_name=role.role_name,
  File "/usr/local/lib/python2.7/dist-packages/azure/servicemanagement/servicemanagementservice.py", line 997, in get_role
    PersistentVMRole)
  File "/usr/local/lib/python2.7/dist-packages/azure/servicemanagement/servicemanagementclient.py", line 108, in _perform_get
    response = self._perform_request(request)
  File "/usr/local/lib/python2.7/dist-packages/azure/servicemanagement/servicemanagementclient.py", line 97, in _perform_request
    return _management_error_handler(ex)
  File "/usr/local/lib/python2.7/dist-packages/azure/servicemanagement/__init__.py", line 1313, in _management_error_handler
    return _general_error_handler(http_error)
  File "/usr/local/lib/python2.7/dist-packages/azure/__init__.py", line 894, in _general_error_handler
    _ERROR_NOT_FOUND.format(str(http_error)))
WindowsAzureMissingResourceError: Not found (Not Found)
No machines were found to be destroyed
```

**Comment by egilh** [comment]
Any progress here? Salt is completly useless for me in Azure, as long as this doesn't work.

**Comment by rallytime** [comment]
@egilh Thanks for the bump and apologies for the delay. I don't think any one has had a chance to look at this issue yet. We've got a substantial bug count that we are working hard to tackle. We'll get to this one, too, as soon as we can.

**Comment by andrejohansson** [comment]
This is not only caused by dots in the name. I've come across some other issue (don't remember which now but it's here somewhere) where list_nodes fails if you have vms with no current ips assigned to them (ie they are shut of) or something. There seems to be a lot of responses causing list_nodes to fail, and when that happens...pretty much all crucial azure commands stop working.

Also, since one of these conditions need to be met, when devs try to reproduce I guess they do it on quite blank Azure subscriptions and things work fine.

My suggested solution is to work in the direction to make list_nodes be more tolerant of different responses and exit gracefully or with "as much info as possible" instead of just crashing since it blocks most commands.

And yes, I understand its kind of a vague suggestion...sorry for that :-)

**Comment by egilh** [comment]
Like  @andrejohansson says, it seems this happens because of several reasons.

The reason it happens for me, every time, is because we are already running in a Azure enviroment with several Cloud Services, that don't contain Virtual Machines. This should be easy to reproduce as I see it, unfortunatly, I dont have another Azure env. to test it on myself.

**Comment by rallytime** [comment]
I know that @techhat did a lot of work with Azure lately, though I don't know if any of that work was addressing this issue specifically. Has anyone tried this on a newer version of salt? I suspect this is still an issue, but thought I would get some feedback regardless. Thanks!

**Comment by techhat** [comment]
This may be resolved in the develop branch. Please check http://docs.saltstack.com/en/develop/topics/cloud/azure.html#destroying-vms

**Comment by rallytime** [comment]
Was anyone able to give the develop version a try to see if this is fixed?

**Comment by bradthurber** [comment]
@rallytime 
I just started working with Azure and salt-cloud v2015.5.2 today. I updated to salt develop and it now passes another piece of info - *the password in the profile does not meet the complexity requirements*.  I corrected that, and am now able to create machines, but salt-minion doesn't get bootstrapped. So maybe that info about the password complexity will help someone else. v2015.5.2 seemed to swallow that error.

I'm able to create machines, but they never get bootstrapped. salt-cloud hangs indefinitely (or at least for 10+ minutes) here:
```
[DEBUG   ] Attempting to authenticate as azureuser (try 1 of 15)
[DEBUG   ] SSH command: 'ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -p 22 azureuser@saltbet123.cloudapp.net date'
[DEBUG   ] Child Forked! PID: 30659  STDOUT_FD: 4  STDERR_FD: 7
[DEBUG   ] Terminal Command: /bin/sh -c ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -p 22 azureuser@saltbet123.cloudapp.net date
Warning: Permanently added 'saltbet123.cloudapp.net,23.96.11.125' (RSA) to the list of known hosts.
[DEBUG   ] Warning: Permanently added 'saltbet123.cloudapp.net,23.96.11.125' (RSA) to the list of known hosts.
azureuser@saltbet123.cloudapp.net's password: [DEBUG   ] azureuser@saltbet123.cloudapp.net's password:

Permission denied, please try again.
[DEBUG   ] Permission denied, please try again.
azureuser@saltbet123.cloudapp.net's password: [DEBUG   ] azureuser@saltbet123.cloudapp.net's password:

```
If I ssh manually I'm able to get to the box. I'll keep poking at it.

I guess something we should also be tracking on azure issues is the version of the Azure Python SDK in use. I'm using v0.11.1

**Comment by rallytime** [comment]
Thanks for the update @bradthurber! I am a little confused about which version you tried. Are you saying you attempted 2015.5.2 AND develop? Or just 2015.5.2?

**Comment by bradthurber** [comment]
@rallytime I tried both with little success.

I created a new ticket #24968 with details rather than pollute this one with what is likely a different issue

Brad

**Comment by rallytime** [comment]
@bradthurber Hrm. Even after running into the same provisioning errors you hit in the new ticket you filed, I was still able to delete the VMs successfully, without any errors.

**Comment by dtoubelis** [comment]
Same issue here:
```
root@scus-saltmaster:~# salt-cloud --versions-report
Salt Version:
            Salt: 2015.8.1

Dependency Versions:
 Apache Libcloud: 0.15.1
          Jinja2: 2.7.2
        M2Crypto: Not Installed
            Mako: 0.9.1
          PyYAML: 3.10
           PyZMQ: 14.4.0
          Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
            RAET: Not Installed
         Tornado: 4.2.1
             ZMQ: 4.0.4
            cffi: Not Installed
        cherrypy: Not Installed
        dateutil: 1.5
           gitdb: 0.5.4
       gitpython: 0.3.2 RC1
           ioflo: Not Installed
         libnacl: Not Installed
    msgpack-pure: Not Installed
  msgpack-python: 0.3.0
    mysql-python: 1.2.3
       pycparser: Not Installed
        pycrypto: 2.6.1
          pygit2: Not Installed
    python-gnupg: Not Installed
           smmap: 0.8.2
         timelib: Not Installed

System Versions:
            dist: Ubuntu 14.04 trusty
         machine: x86_64
         release: 3.19.0-30-generic
          system: Ubuntu 14.04 trusty

root@scus-saltmaster:~# salt-cloud -f list_nodes azure
[INFO    ] salt-cloud starting
[ERROR   ] There was an error running the function: 'name'
root@scus-saltmaster:~# salt-cloud -f list_nodes azure -l debug
[DEBUG   ] Reading configuration from /etc/salt/cloud
[DEBUG   ] Including configuration from '/etc/salt/cloud.conf.d/20_cache.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.conf.d/20_cache.conf
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/mijem.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/mijem.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/reactor.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/reactor.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: scus-saltmaster.scus-saltmaster.j4.internal.cloudapp.net
[DEBUG   ] Missing configuration file: /etc/salt/cloud.providers
[DEBUG   ] Including configuration from '/etc/salt/cloud.providers.d/azure.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers.d/azure.conf
[DEBUG   ] Missing configuration file: /etc/salt/cloud.profiles
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/azure-servers.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/azure-servers.conf
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/mijem-servers.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/mijem-servers.conf
[DEBUG   ] Configuration file path: /etc/salt/cloud
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] salt-cloud starting
[DEBUG   ] Could not LazyLoad parallels.avail_sizes
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy
[DEBUG   ] Could not LazyLoad saltify.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.avail_images
[DEBUG   ] Could not LazyLoad saltify.avail_locations
[DEBUG   ] LazyLoaded rackspace.reboot
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] LazyLoaded rackspace.list_locations
[DEBUG   ] Trying to execute 'azure.list_nodes' with the following kwargs: {}
[ERROR   ] There was an error running the function: 'name'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 266, in run
    self.function_provider, self.function_name, kwargs
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1517, in do_function
    driver: self.clouds[fun](call='function')
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/msazure.py", line 226, in list_nodes
    ret[node][prop] = nodes[node][prop]
KeyError: 'name'
root@scus-saltmaster:~#
```

I do not have any node names that contain dots or begin with number or exceed 15 characters.

**Comment by rallytime** [comment]
@dtoubelis I think this might be a different bug. Would you mind opening a new issue?

**Comment by dtoubelis** [comment]
@rallytime, submitted as #28150
