### ISSUE TITLE
states.pkg.installed and states.git.latest (and more states?) fail for packages on OS X 10.10 Yosemite

### ISSUE THREAD

**Issue by n1ck3** [saltstack/salt#16012]
I get this error when I am trying to use states.pkg.installed or states.git.latest on OS X 10.10 Yosemite.

Below is output for trying to install packages with brew.
# On OS X 10.10 Beta 3 Yosemite:
## Version information:

```
yosemite:salt nicke$ salt --versions-report
           Salt: 2014.1.0
         Python: 2.7.6 (default, Aug 29 2014, 21:57:57)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
         PyYAML: 3.11
          PyZMQ: 14.3.1
            ZMQ: 4.0.4
```
## Debug output:

```
sudo salt-call state.high '{"tmux": {"pkg": ["installed"]}}' --local -l debug
[DEBUG   ] Reading configuration from /etc/salt/minion
[INFO    ] Using cached minion ID from /etc/salt/minion_id: yosemite.local
[DEBUG   ] Configuration file path: /etc/salt/minion
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Loaded localemod as virtual locale
[DEBUG   ] Loaded osxdesktop as virtual desktop
[DEBUG   ] Loaded sysmod as virtual sys
[DEBUG   ] Loaded launchctl as virtual service
[DEBUG   ] Loaded parted as virtual partition
[DEBUG   ] Loaded zcbuildout as virtual buildout
[DEBUG   ] Loaded htpasswd as virtual webutil
[DEBUG   ] Loaded cmdmod as virtual cmd
[DEBUG   ] Loaded virtualenv_mod as virtual virtualenv
[DEBUG   ] Loaded darwin_sysctl as virtual sysctl
[DEBUG   ] Loaded djangomod as virtual django
[DEBUG   ] Loaded brew as virtual pkg
[DEBUG   ] Loaded localemod as virtual locale
[DEBUG   ] Loaded osxdesktop as virtual desktop
[DEBUG   ] Loaded sysmod as virtual sys
[DEBUG   ] Loaded launchctl as virtual service
[DEBUG   ] Loaded parted as virtual partition
[DEBUG   ] Loaded zcbuildout as virtual buildout
[DEBUG   ] Loaded htpasswd as virtual webutil
[DEBUG   ] Loaded cmdmod as virtual cmd
[DEBUG   ] Loaded virtualenv_mod as virtual virtualenv
[DEBUG   ] Loaded darwin_sysctl as virtual sysctl
[DEBUG   ] Loaded djangomod as virtual django
[DEBUG   ] Loaded brew as virtual pkg
[DEBUG   ] Loaded syslog_return as virtual syslog
[DEBUG   ] Loaded couchdb_return as virtual couchdb
[DEBUG   ] Loaded carbon_return as virtual carbon
[DEBUG   ] Loaded sqlite3_return as virtual sqlite3
[DEBUG   ] Loaded pip_state as virtual pip
[DEBUG   ] Loaded saltmod as virtual salt
[DEBUG   ] Loaded zcbuildout as virtual buildout
[DEBUG   ] Loaded virtualenv_mod as virtual virtualenv
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Loaded localemod as virtual locale
[DEBUG   ] Loaded osxdesktop as virtual desktop
[DEBUG   ] Loaded sysmod as virtual sys
[DEBUG   ] Loaded launchctl as virtual service
[DEBUG   ] Loaded parted as virtual partition
[DEBUG   ] Loaded zcbuildout as virtual buildout
[DEBUG   ] Loaded htpasswd as virtual webutil
[DEBUG   ] Loaded cmdmod as virtual cmd
[DEBUG   ] Loaded virtualenv_mod as virtual virtualenv
[DEBUG   ] Loaded darwin_sysctl as virtual sysctl
[DEBUG   ] Loaded djangomod as virtual django
[DEBUG   ] Loaded brew as virtual pkg
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] Loaded localemod as virtual locale
[DEBUG   ] Loaded osxdesktop as virtual desktop
[DEBUG   ] Loaded sysmod as virtual sys
[DEBUG   ] Loaded launchctl as virtual service
[DEBUG   ] Loaded parted as virtual partition
[DEBUG   ] Loaded zcbuildout as virtual buildout
[DEBUG   ] Loaded htpasswd as virtual webutil
[DEBUG   ] Loaded cmdmod as virtual cmd
[DEBUG   ] Loaded virtualenv_mod as virtual virtualenv
[DEBUG   ] Loaded darwin_sysctl as virtual sysctl
[DEBUG   ] Loaded djangomod as virtual django
[DEBUG   ] Loaded brew as virtual pkg
[DEBUG   ] Loaded pip_state as virtual pip
[DEBUG   ] Loaded saltmod as virtual salt
[DEBUG   ] Loaded zcbuildout as virtual buildout
[DEBUG   ] Loaded virtualenv_mod as virtual virtualenv
[INFO    ] Running state [tmux] at time 00:13:27.128197
[INFO    ] Executing state pkg.installed for tmux
[INFO    ] Executing command 'brew list --versions' in directory '/Users/nicke'
[DEBUG   ] output: gdbm 1.11
libyaml 0.1.6
makedepend 1.0.5
openssl 1.0.1i
pcre 8.35
pkg-config 0.28
python 2.7.8_1
readline 6.3.8
saltstack 2014.1.10
sqlite 3.8.6
swig 3.0.2
zeromq 4.0.4
[INFO    ] Executing command 'brew --prefix' in directory '/Users/nicke'
[DEBUG   ] output: /usr/local
[INFO    ] Executing command 'brew install tmux' as user 'nicke' in directory '/Users/nicke'
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/local/Cellar/saltstack/2014.1.10/lib/python2.7/site-packages/salt/state.py", line 1379, in call
    **cdata['kwargs'])
  File "/usr/local/Cellar/saltstack/2014.1.10/lib/python2.7/site-packages/salt/states/pkg.py", line 518, in installed
    **kwargs)
  File "/usr/local/Cellar/saltstack/2014.1.10/lib/python2.7/site-packages/salt/modules/brew.py", line 316, in install
    output_loglevel='debug'
  File "/usr/local/Cellar/saltstack/2014.1.10/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 572, in run
    saltenv=saltenv)
  File "/usr/local/Cellar/saltstack/2014.1.10/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 408, in _run
    proc = salt.utils.timed_subprocess.TimedProc(cmd, **kwargs)
  File "/usr/local/Cellar/saltstack/2014.1.10/lib/python2.7/site-packages/salt/utils/timed_subprocess.py", line 24, in __init__
    self.process = subprocess.Popen(args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 709, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1326, in _execute_child
    raise child_exception
KeyError: 'user.list_groups'

[INFO    ] Completed state [tmux] at time 00:13:28.787725
[DEBUG   ] Loaded no_out as virtual quiet
[DEBUG   ] Loaded json_out as virtual json
[DEBUG   ] Loaded yaml_out as virtual yaml
[DEBUG   ] Loaded pprint_out as virtual pprint
local:
    ----------
    pkg_|-tmux_|-tmux_|-installed:
        ----------
        __run_num__:
            0
        changes:
            ----------
        comment:
            An exception occurred in this state: Traceback (most recent call last):
              File "/usr/local/Cellar/saltstack/2014.1.10/lib/python2.7/site-packages/salt/state.py", line 1379, in call
                **cdata['kwargs'])
              File "/usr/local/Cellar/saltstack/2014.1.10/lib/python2.7/site-packages/salt/states/pkg.py", line 518, in installed
                **kwargs)
              File "/usr/local/Cellar/saltstack/2014.1.10/lib/python2.7/site-packages/salt/modules/brew.py", line 316, in install
                output_loglevel='debug'
              File "/usr/local/Cellar/saltstack/2014.1.10/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 572, in run
                saltenv=saltenv)
              File "/usr/local/Cellar/saltstack/2014.1.10/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 408, in _run
                proc = salt.utils.timed_subprocess.TimedProc(cmd, **kwargs)
              File "/usr/local/Cellar/saltstack/2014.1.10/lib/python2.7/site-packages/salt/utils/timed_subprocess.py", line 24, in __init__
                self.process = subprocess.Popen(args, **kwargs)
              File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 709, in __init__
                errread, errwrite)
              File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1326, in _execute_child
                raise child_exception
            KeyError: 'user.list_groups'

        name:
            tmux
        result:
            False
```

I get this regardless if I am running against a master or master-less or running from an .sls or as a one-liner.
# On OS X 10.9.5 Mavericks
## Version information:

```
mavericks:~ nicke$  salt --versions-report
           Salt: 2014.1.0
         Python: 2.7.5 (default, Mar  9 2014, 22:15:05)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
         PyYAML: 3.11
          PyZMQ: 14.3.1
            ZMQ: 4.0.4
```
## Debug output:

```
mavericks:~ nicke$ sudo salt-call state.high '{"tmux": {"pkg": ["installed"]}}' --local -l debug
[DEBUG   ] Reading configuration from /etc/salt/minion
[INFO    ] Using cached minion ID from /etc/salt/minion_id: mavericks.local
[DEBUG   ] Configuration file path: /etc/salt/minion
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Loaded localemod as virtual locale
[DEBUG   ] Loaded osxdesktop as virtual desktop
[DEBUG   ] Loaded sysmod as virtual sys
[DEBUG   ] Loaded launchctl as virtual service
[DEBUG   ] Loaded mac_group as virtual group
[DEBUG   ] Loaded parted as virtual partition
[DEBUG   ] Loaded zcbuildout as virtual buildout
[DEBUG   ] Loaded mac_user as virtual user
[DEBUG   ] Loaded htpasswd as virtual webutil
[DEBUG   ] Loaded cmdmod as virtual cmd
[DEBUG   ] Loaded virtualenv_mod as virtual virtualenv
[DEBUG   ] Loaded darwin_sysctl as virtual sysctl
[DEBUG   ] Loaded djangomod as virtual django
[DEBUG   ] Loaded brew as virtual pkg
[DEBUG   ] Loaded localemod as virtual locale
[DEBUG   ] Loaded osxdesktop as virtual desktop
[DEBUG   ] Loaded sysmod as virtual sys
[DEBUG   ] Loaded launchctl as virtual service
[DEBUG   ] Loaded mac_group as virtual group
[DEBUG   ] Loaded parted as virtual partition
[DEBUG   ] Loaded zcbuildout as virtual buildout
[DEBUG   ] Loaded mac_user as virtual user
[DEBUG   ] Loaded htpasswd as virtual webutil
[DEBUG   ] Loaded cmdmod as virtual cmd
[DEBUG   ] Loaded virtualenv_mod as virtual virtualenv
[DEBUG   ] Loaded darwin_sysctl as virtual sysctl
[DEBUG   ] Loaded djangomod as virtual django
[DEBUG   ] Loaded brew as virtual pkg
[DEBUG   ] Loaded syslog_return as virtual syslog
[DEBUG   ] Loaded couchdb_return as virtual couchdb
[DEBUG   ] Loaded carbon_return as virtual carbon
[DEBUG   ] Loaded sqlite3_return as virtual sqlite3
[DEBUG   ] Loaded saltmod as virtual salt
[DEBUG   ] Loaded zcbuildout as virtual buildout
[DEBUG   ] Loaded virtualenv_mod as virtual virtualenv
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Loaded localemod as virtual locale
[DEBUG   ] Loaded osxdesktop as virtual desktop
[DEBUG   ] Loaded sysmod as virtual sys
[DEBUG   ] Loaded launchctl as virtual service
[DEBUG   ] Loaded mac_group as virtual group
[DEBUG   ] Loaded parted as virtual partition
[DEBUG   ] Loaded zcbuildout as virtual buildout
[DEBUG   ] Loaded mac_user as virtual user
[DEBUG   ] Loaded htpasswd as virtual webutil
[DEBUG   ] Loaded cmdmod as virtual cmd
[DEBUG   ] Loaded virtualenv_mod as virtual virtualenv
[DEBUG   ] Loaded darwin_sysctl as virtual sysctl
[DEBUG   ] Loaded djangomod as virtual django
[DEBUG   ] Loaded brew as virtual pkg
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] Loaded localemod as virtual locale
[DEBUG   ] Loaded osxdesktop as virtual desktop
[DEBUG   ] Loaded sysmod as virtual sys
[DEBUG   ] Loaded launchctl as virtual service
[DEBUG   ] Loaded mac_group as virtual group
[DEBUG   ] Loaded parted as virtual partition
[DEBUG   ] Loaded zcbuildout as virtual buildout
[DEBUG   ] Loaded mac_user as virtual user
[DEBUG   ] Loaded htpasswd as virtual webutil
[DEBUG   ] Loaded cmdmod as virtual cmd
[DEBUG   ] Loaded virtualenv_mod as virtual virtualenv
[DEBUG   ] Loaded darwin_sysctl as virtual sysctl
[DEBUG   ] Loaded djangomod as virtual django
[DEBUG   ] Loaded brew as virtual pkg
[DEBUG   ] Loaded saltmod as virtual salt
[DEBUG   ] Loaded zcbuildout as virtual buildout
[DEBUG   ] Loaded virtualenv_mod as virtual virtualenv
[INFO    ] Running state [tmux] at time 15:50:57.311130
[INFO    ] Executing state pkg.installed for tmux
[INFO    ] Executing command 'brew list --versions' in directory '/Users/nicke'
[DEBUG   ] output: libyaml 0.1.6
saltstack 2014.1.10
zeromq 4.0.4
[INFO    ] Executing command 'brew --prefix' in directory '/Users/nicke'
[DEBUG   ] output: /usr/local
[INFO    ] Executing command 'brew install tmux' as user 'nicke' in directory '/Users/nicke'
[DEBUG   ] output: ==> Installing tmux dependency: libevent
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/libevent-2.0.21.mavericks.bottle.tar.gz
==> Pouring libevent-2.0.21.mavericks.bottle.tar.gz
🍺  /usr/local/Cellar/libevent/2.0.21: 48 files, 1.8M
==> Installing tmux
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/tmux-1.9a.mavericks.bottle.tar.gz
==> Pouring tmux-1.9a.mavericks.bottle.tar.gz
==> Caveats
Example configurations have been installed to:
  /usr/local/Cellar/tmux/1.9a/share/tmux/examples

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/tmux/1.9a: 16 files, 632K
[INFO    ] Executing command 'brew list --versions' in directory '/Users/nicke'
[DEBUG   ] output: libevent 2.0.21
libyaml 0.1.6
saltstack 2014.1.10
tmux 1.9a
zeromq 4.0.4
[INFO    ] Installed Packages:
tmux changed from absent to 1.9a
libevent changed from absent to 2.0.21

[DEBUG   ] Refreshing modules...
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] Loaded localemod as virtual locale
[DEBUG   ] Loaded osxdesktop as virtual desktop
[DEBUG   ] Loaded sysmod as virtual sys
[DEBUG   ] Loaded launchctl as virtual service
[DEBUG   ] Loaded mac_group as virtual group
[DEBUG   ] Loaded parted as virtual partition
[DEBUG   ] Loaded zcbuildout as virtual buildout
[DEBUG   ] Loaded mac_user as virtual user
[DEBUG   ] Loaded htpasswd as virtual webutil
[DEBUG   ] Loaded cmdmod as virtual cmd
[DEBUG   ] Loaded virtualenv_mod as virtual virtualenv
[DEBUG   ] Loaded darwin_sysctl as virtual sysctl
[DEBUG   ] Loaded djangomod as virtual django
[DEBUG   ] Loaded brew as virtual pkg
[DEBUG   ] Loaded saltmod as virtual salt
[DEBUG   ] Loaded zcbuildout as virtual buildout
[DEBUG   ] Loaded virtualenv_mod as virtual virtualenv
[INFO    ] Completed state [tmux] at time 15:51:06.787536
[DEBUG   ] Loaded no_out as virtual quiet
[DEBUG   ] Loaded json_out as virtual json
[DEBUG   ] Loaded yaml_out as virtual yaml
[DEBUG   ] Loaded pprint_out as virtual pprint
local:
    ----------
    pkg_|-tmux_|-tmux_|-installed:
        ----------
        __run_num__:
            0
        changes:
            ----------
            libevent:
                ----------
                new:
                    2.0.21
                old:

            tmux:
                ----------
                new:
                    1.9a
                old:

        comment:
            The following packages were installed/updated: tmux.
        name:
            tmux
        result:
            True
```

**Comment by cro** [comment]
@n1ck3 I think this might be related to changes in launchd in Yosemite.  I seem to recall that launchctl plists can no longer modify the path under which the supervised binaries run.
