### ISSUE TITLE
pip.install module fails on Windows

### ISSUE THREAD

**Issue by johnccfm** [saltstack/salt#16059]
This module fails with the following output:-

```
C:\Users\Administrator>C:\salt\salt-call pip.install colorama
[INFO    ] Executing command "pip install 'colorama'" in directory 'C:\\Users\\Administrator'
[ERROR   ] Command "pip install 'colorama'" failed with return code: 2
[ERROR   ] stdout: Exception:
Traceback (most recent call last):
  File "c:\Python34\lib\site-packages\pip\basecommand.py", line 122, in main
    status = self.run(options, args)
  File "c:\Python34\lib\site-packages\pip\commands\install.py", line 257, in run
    InstallRequirement.from_line(name, None))
  File "c:\Python34\lib\site-packages\pip\req.py", line 172, in from_line
    return cls(req, comes_from, url=url, prereleases=prereleases)
  File "c:\Python34\lib\site-packages\pip\req.py", line 70, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "c:\Python34\lib\site-packages\pip\_vendor\pkg_resources.py", line 2667, in parse
    reqs = list(parse_requirements(s))
  File "c:\Python34\lib\site-packages\pip\_vendor\pkg_resources.py", line 2593, in parse_requirements
    raise ValueError("Missing distribution spec", line)
ValueError: ('Missing distribution spec', "'colorama'")

Storing debug log for failure in C:\Users\Administrator\pip\pip.log
local:
    ----------
    pid:
        904
    retcode:
        2
    stderr:

    stdout:
        Exception:
        Traceback (most recent call last):
          File "c:\Python34\lib\site-packages\pip\basecommand.py", line 122, in main
            status = self.run(options, args)
          File "c:\Python34\lib\site-packages\pip\commands\install.py", line 257, in run
            InstallRequirement.from_line(name, None))
          File "c:\Python34\lib\site-packages\pip\req.py", line 172, in from_line
            return cls(req, comes_from, url=url, prereleases=prereleases)
          File "c:\Python34\lib\site-packages\pip\req.py", line 70, in __init__
            req = pkg_resources.Requirement.parse(req)
          File "c:\Python34\lib\site-packages\pip\_vendor\pkg_resources.py", line 2667, in parse
            reqs = list(parse_requirements(s))
          File "c:\Python34\lib\site-packages\pip\_vendor\pkg_resources.py", line 2593, in parse_requirements
            raise ValueError("Missing distribution spec", line)
        ValueError: ('Missing distribution spec', "'colorama'")

        Storing debug log for failure in C:\Users\Administrator\pip\pip.log
```

I added some print statements to the pip code and found that these are the arguments to pip:-

```
Args: ["'colorama'"]
```

It seems like a Windows-specific quoting issue, and you can get the same error from pip by typing:-

```
pip install "'colorama'"
```

**Comment by rallytime** [comment]
@johnccfm I know that @twangboy has been working hard on getting some of these outstanding windows bugs cleaned up. Can you give this another try on v2014.7.5 using the updated docs referenced in the pull request above?

**Comment by rallytime** [comment]
I am going to close this since we didn't hear back. If this issue persists after upgrading to 2014.7.5, please leave a comment and we'd be glad to open this again. Thanks!
