### ISSUE TITLE
Exception when thinning

### ISSUE THREAD

**Issue by rawtaz** [saltstack/salt#16128]
Couldn't come up with a good description for this issue, feel free to adjust it!

Earlier tonight I installed saltstack via homebrew, using `brew install --HEAD saltstack` on OS X 10.9.5, for the purpose of using salt-ssh only, no master/minion stuff, not even masterless minion.

After setting up the most basic non-root configuration I know (mainly by following http://docs.saltstack.com/en/latest/topics/ssh/), I'm getting this exception when running the test.ping command:

```
$ salt-ssh '*' test.ping
Executing job with jid 20140925020305262353
-------------------------------------------


Process Process-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/saltstack/HEAD/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 318, in handle_routine
    stdout, stderr, retcode = single.run()
  File "/usr/local/Cellar/saltstack/HEAD/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 602, in run
    stdout, stderr, retcode = self.cmd_block()
  File "/usr/local/Cellar/saltstack/HEAD/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 765, in cmd_block
    cmd_str = self._cmd_str()
  File "/usr/local/Cellar/saltstack/HEAD/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 707, in _cmd_str
    thin_sum = salt.utils.thin.thin_sum(self.opts['cachedir'], 'sha1')
  File "/usr/local/Cellar/saltstack/HEAD/lib/python2.7/site-packages/salt/utils/thin.py", line 161, in thin_sum
    thintar = gen_thin(cachedir)
  File "/usr/local/Cellar/saltstack/HEAD/lib/python2.7/site-packages/salt/utils/thin.py", line 137, in gen_thin
    os.chdir(os.path.dirname(top))
OSError: [Errno 20] Not a directory: '/usr/local/Cellar/saltstack/HEAD/libexec/lib/python2.7/site-packages/msgpack_python-0.4.2-py2.7-macosx-10.9-intel.egg'


$ ls -la /usr/local/Cellar/saltstack/HEAD/libexec/lib/python2.7/site-packages/msgpack_python-0.4.2-py2.7-macosx-10.9-intel.egg
-rw-r--r--  1 foo  admin  72420 25 Sep 00:25 /usr/local/Cellar/saltstack/HEAD/libexec/lib/python2.7/site-packages/msgpack_python-0.4.2-py2.7-macosx-10.9-intel.egg


$ pwd
/Users/foo/salt

$ find . -ls
6397163        0 drwxr-xr-x    6 foo           staff                 204 25 Sep 01:59 .
6397453        0 drwxr-xr-x    4 foo           staff                 136 25 Sep 02:03 ./cache
6397641        0 drwxr-xr-x    4 foo           staff                 136 25 Sep 02:08 ./cache/jobs
6397699        0 drwxr-xr-x    3 foo           staff                 102 25 Sep 02:08 ./cache/jobs/97
6397700        0 drwxr-xr-x    5 foo           staff                 170 25 Sep 02:08 ./cache/jobs/97/237e7a09010da7129287a35983e1fa
6397703        8 -rw-r--r--    1 foo           staff                  75 25 Sep 02:08 ./cache/jobs/97/237e7a09010da7129287a35983e1fa/.load.p
6397702        8 -rw-r--r--    1 foo           staff                   1 25 Sep 02:08 ./cache/jobs/97/237e7a09010da7129287a35983e1fa/.minions.p
6397701        8 -rw-r--r--    1 foo           staff                  20 25 Sep 02:08 ./cache/jobs/97/237e7a09010da7129287a35983e1fa/jid
6397642        0 drwxr-xr-x    3 foo           staff                 102 25 Sep 02:03 ./cache/jobs/a7
6397643        0 drwxr-xr-x    5 foo           staff                 170 25 Sep 02:03 ./cache/jobs/a7/5e43053fdeeba6109a86a97b804934
6397646        8 -rw-r--r--    1 foo           staff                  75 25 Sep 02:03 ./cache/jobs/a7/5e43053fdeeba6109a86a97b804934/.load.p
6397645        8 -rw-r--r--    1 foo           staff                   1 25 Sep 02:03 ./cache/jobs/a7/5e43053fdeeba6109a86a97b804934/.minions.p
6397644        8 -rw-r--r--    1 foo           staff                  20 25 Sep 02:03 ./cache/jobs/a7/5e43053fdeeba6109a86a97b804934/jid
6397647        0 drwxr-xr-x    4 foo           staff                 136 25 Sep 02:08 ./cache/thin
6397648        8 -rw-r--r--    1 foo           staff                  79 25 Sep 02:08 ./cache/thin/salt-call
6397704     3696 -rw-r--r--    1 foo           staff             1892352 25 Sep 02:08 ./cache/thin/thin.tgz
6397289        0 drwxr-xr-x    4 foo           staff                 136 25 Sep 02:02 ./etc
6397410        8 -rw-r--r--    1 foo           staff                  67 25 Sep 02:02 ./etc/master
6397303        8 -rw-r--r--    1 foo           staff                  20 25 Sep 02:02 ./etc/roster
6397452        0 drwxr-xr-x    3 foo           staff                 102 25 Sep 01:59 ./pki
6397559        0 drwxr-xr-x    4 foo           staff                 136 25 Sep 01:59 ./pki/ssh
6397560        8 -rw-------    1 foo           staff                1679 25 Sep 01:59 ./pki/ssh/salt-ssh.rsa
6397561        8 -rw-r--r--    1 foo           staff                 401 25 Sep 01:59 ./pki/ssh/salt-ssh.rsa.pub
6397242        8 -rw-r--r--    1 foo           staff                  92 25 Sep 01:59 ./Saltfile

$ cat etc/master
cachedir: /Users/foo/salt/cache
pki_dir: /Users/foo/salt/pki

$ cat etc/roster
test:
  host: test.domain.com
  user: root

$ cat Saltfile
salt-ssh:
  config_dir: /Users/foo/salt/etc
  roster_file: /Users/foo/salt/etc/roster
```

I get the same/similar when doing a raw command instead:

```
$ salt-ssh '*' -r 'ifconfig' -i
Permission denied for host fido, do you want to deploy the salt-ssh key? (password required):
[Y/n] y
Password for root@fido:
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
OSError: [Errno 20] Not a directory: '/usr/local/Cellar/saltstack/HEAD/libexec/lib/python2.7/site-packages/msgpack_python-0.4.2-py2.7-macosx-10.9-intel.egg'
Traceback (most recent call last):
  File "/usr/local/Cellar/saltstack/HEAD/libexec/bin/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/usr/local/Cellar/saltstack/HEAD/lib/python2.7/site-packages/salt/scripts.py", line 259, in salt_ssh
    client.run()
  File "/usr/local/Cellar/saltstack/HEAD/lib/python2.7/site-packages/salt/cli/__init__.py", line 480, in run
    ssh.run()
  File "/usr/local/Cellar/saltstack/HEAD/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 449, in run
    ret = self.key_deploy(host, ret)
  File "/usr/local/Cellar/saltstack/HEAD/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 264, in key_deploy
    return self._key_deploy_run(host, target, True)
  File "/usr/local/Cellar/saltstack/HEAD/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 294, in _key_deploy_run
    stdout, stderr, retcode = single.cmd_block()
  File "/usr/local/Cellar/saltstack/HEAD/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 765, in cmd_block
    cmd_str = self._cmd_str()
  File "/usr/local/Cellar/saltstack/HEAD/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 707, in _cmd_str
    thin_sum = salt.utils.thin.thin_sum(self.opts['cachedir'], 'sha1')
  File "/usr/local/Cellar/saltstack/HEAD/lib/python2.7/site-packages/salt/utils/thin.py", line 161, in thin_sum
    thintar = gen_thin(cachedir)
  File "/usr/local/Cellar/saltstack/HEAD/lib/python2.7/site-packages/salt/utils/thin.py", line 137, in gen_thin
    os.chdir(os.path.dirname(top))
OSError: [Errno 20] Not a directory: '/usr/local/Cellar/saltstack/HEAD/libexec/lib/python2.7/site-packages/msgpack_python-0.4.2-py2.7-macosx-10.9-intel.egg'
Traceback (most recent call last):
  File "/usr/local/Cellar/saltstack/HEAD/libexec/bin/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/usr/local/Cellar/saltstack/HEAD/lib/python2.7/site-packages/salt/scripts.py", line 259, in salt_ssh
    client.run()
  File "/usr/local/Cellar/saltstack/HEAD/lib/python2.7/site-packages/salt/cli/__init__.py", line 480, in run
    ssh.run()
  File "/usr/local/Cellar/saltstack/HEAD/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 449, in run
    ret = self.key_deploy(host, ret)
  File "/usr/local/Cellar/saltstack/HEAD/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 264, in key_deploy
    return self._key_deploy_run(host, target, True)
  File "/usr/local/Cellar/saltstack/HEAD/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 294, in _key_deploy_run
    stdout, stderr, retcode = single.cmd_block()
  File "/usr/local/Cellar/saltstack/HEAD/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 765, in cmd_block
    cmd_str = self._cmd_str()
  File "/usr/local/Cellar/saltstack/HEAD/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 707, in _cmd_str
    thin_sum = salt.utils.thin.thin_sum(self.opts['cachedir'], 'sha1')
  File "/usr/local/Cellar/saltstack/HEAD/lib/python2.7/site-packages/salt/utils/thin.py", line 161, in thin_sum
    thintar = gen_thin(cachedir)
  File "/usr/local/Cellar/saltstack/HEAD/lib/python2.7/site-packages/salt/utils/thin.py", line 137, in gen_thin
    os.chdir(os.path.dirname(top))
OSError: [Errno 20] Not a directory: '/usr/local/Cellar/saltstack/HEAD/libexec/lib/python2.7/site-packages/msgpack_python-0.4.2-py2.7-macosx-10.9-intel.egg'
```

Here's the version info:

```
$ salt-ssh --versions-report
           Salt: 2014.7.0-673-g2edfe62
         Python: 2.7.5 (default, Mar  9 2014, 22:15:05)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
```

**Comment by rawtaz** [comment]
Whether to do anything with the information I provided is up to you.

**Comment by thatch45** [comment]
To my knowledge this has been resolved with other work on making the thin generation more reliable. If this can be reproduced with a current version of Salt please feel free to re-open it
