### ISSUE TITLE
UnicodeDecodeError in highstate outputter

### ISSUE THREAD

**Issue by Jille** [saltstack/salt#16139]
I get this crash when running state.highstate test=True:

```
master# salt -t 60 minion state.highstate test=True
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 99: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/pymodules/python2.7/salt/scripts.py", line 240, in salt_main
    client.run()
  File "/usr/lib/pymodules/python2.7/salt/cli/__init__.py", line 189, in run
    self._output_ret(ret_, out)
  File "/usr/lib/pymodules/python2.7/salt/cli/__init__.py", line 243, in _output_ret
    salt.output.display_output(ret, out, self.config)
  File "/usr/lib/pymodules/python2.7/salt/output/__init__.py", line 36, in display_output
    display_data = get_printout(out, opts)(data).rstrip()
  File "/usr/lib/pymodules/python2.7/salt/output/highstate.py", line 74, in output
    return _format_host(host, hostdata)[0]
  File "/usr/lib/pymodules/python2.7/salt/output/highstate.py", line 203, in _format_host
    u'\n' + u' ' * 14)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 99: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/pymodules/python2.7/salt/scripts.py", line 240, in salt_main
    client.run()
  File "/usr/lib/pymodules/python2.7/salt/cli/__init__.py", line 189, in run
    self._output_ret(ret_, out)
  File "/usr/lib/pymodules/python2.7/salt/cli/__init__.py", line 243, in _output_ret
    salt.output.display_output(ret, out, self.config)
  File "/usr/lib/pymodules/python2.7/salt/output/__init__.py", line 36, in display_output
    display_data = get_printout(out, opts)(data).rstrip()
  File "/usr/lib/pymodules/python2.7/salt/output/highstate.py", line 74, in output
    return _format_host(host, hostdata)[0]
  File "/usr/lib/pymodules/python2.7/salt/output/highstate.py", line 203, in _format_host
    u'\n' + u' ' * 14)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 99: ordinal not in range(128)
```

The state:

```
/some-file:
    file.managed:
        - source: 'salt://some-file'
        - show_diff: true
```

It's easy to reproduce: Put an lorem ipsum on /srv/salt/some-file, highstate it, log in to the minion, add some non-ascii (like \xc2\xb5) to /some-file and run another highstate and it will crash like above.

I'm running 2014.7.0rc1 at 20f2334

**Comment by joshmule** [comment]
So in what version is this (or will this be) fixed?

**Comment by basepi** [comment]
The fix in #18376 is in 2014.7.1.

**Comment by markuskramerIgitt** [comment]
The current implementation of sdecode loops through encodings, which cannot be a solution, and it even fails for Windows. Please use sys.stdin.encoding, as suggested in https://github.com/saltstack/salt/issues/19166

**Comment by eliasp** [comment]
Running into this by just using a unicode char in **a comment** of a YAML/SLS on `2014.7.1`/`2014.7.2` where it was supposed to be fixed through #18376:

```SaltStack
# RHEL7/CentOS7 ships the quite outdated systemd version 208
# The RedHat developer Lukáš Nykrýn provides a COPR with newer versions
{% if grains['os'] in ('RedHat', 'CentOS') %}
systemd-copr:
  pkgrepo.managed:
    - humanname:           Builds of newer systemd versions for CentOS7/RHEL7
    - baseurl:             http://copr-be.cloud.fedoraproject.org/results/lnykryn/systemd/{{ repotype }}-{{ salt['grains.get']('osmajorrelease', 'unknown') }}-$basearch/
    - gpgkey:              https://copr-be.cloud.fedoraproject.org/results/lnykryn/systemd/pubkey.gpg
    - gpgcheck:            1  
    - skip_if_unavailable: True
    - enabled:             1  
    - order:               1  
{% endif %}
```

`state.highstate` output:
```
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 225: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 241, in salt_main
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/__init__.py", line 190, in run
    self._output_ret(ret_, out)
  File "/usr/lib/python2.7/dist-packages/salt/cli/__init__.py", line 244, in _output_ret
    salt.output.display_output(ret, out, self.config)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 44, in display_output
    display_data = get_printout(out, opts)(data).rstrip()
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 74, in output
    return _format_host(host, hostdata)[0]
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 102, in _format_host
    .format(hcolor, err, colors)))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 225: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 241, in salt_main
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/__init__.py", line 190, in run
    self._output_ret(ret_, out)
  File "/usr/lib/python2.7/dist-packages/salt/cli/__init__.py", line 244, in _output_ret
    salt.output.display_output(ret, out, self.config)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 44, in display_output
    display_data = get_printout(out, opts)(data).rstrip()
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 74, in output
    return _format_host(host, hostdata)[0]
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 102, in _format_host
    .format(hcolor, err, colors)))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 225: ordinal not in range(128)
```

```
               Salt: 2014.7.1
             Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
             Jinja2: 2.7.2
           M2Crypto: 0.21.1
     msgpack-python: 0.3.0
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
            libnacl: Not Installed
             PyYAML: 3.10
              ioflo: Not Installed
              PyZMQ: 14.0.1
               RAET: Not Installed
                ZMQ: 4.0.4
               Mako: 0.9.1
```
OS: Ubuntu 14.04.2

**Minion:**
```
               Salt: 2014.7.2
             Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
             Jinja2: 2.7.2
           M2Crypto: 0.21.1
     msgpack-python: 0.4.4
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
            libnacl: Not Installed
             PyYAML: 3.10
              ioflo: Not Installed
              PyZMQ: 14.3.1
               RAET: Not Installed
                ZMQ: 3.2.5
               Mako: Not Installed
```
OS: CentOS 7

**Comment by rallytime** [comment]
Thanks for the update @eliasp. I've removed the "Fixed Pending Verification" label.

**Comment by freshnewpage** [comment]
This may be a locale issue.
Salt sets the locale to LC_ALL=C but a minion directly locale had LC_ALL="en_US.UTF-8". 
A cmd.run that previously failed with a "UnicodeDecodeError: 'ascii' codec can't decode byte" error succeeded after explicitly setting the locale as an env variable.

             - env:
                - LANG: 'en_US.UTF-8'
                - LC_ALL: 'en_US.UTF-8'

**Comment by knuta** [comment]
At least some of these are due to mixing the unicode strings (type 'unicode') and byte strings (type 'str'). Consider the following example:

```
>>> '\n'.join([u'å', u'å'])
u'\xe5\n\xe5'
>>> '\n'.join(['å', 'å'])
'\xc3\xa5\n\xc3\xa5'
>>> '\n'.join([u'å', 'å'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
```

In the case of highstate failing on "return '\n'.join(hstrs), changed" (one of the examples above), all input save one were byte strings, but the "Changes" part is a unicode string. This small tweak standardizing on str (the smallest change) made my run succeed (on 2014.1.13):

```diff
--- /usr/lib/python2.7/dist-packages/salt/output/highstate.py	2015-10-05 02:26:49.000000000 +0200
+++ /usr/lib/python2.7/dist-packages/salt/output/highstate.py	2015-10-05 02:27:03.000000000 +0200
@@ -138,7 +138,7 @@
             hstrs.extend([sline.format(**svars) for sline in state_lines])
             changes = '     Changes:   ' + ctext
             hstrs.append(
-                u'{0}{1}{2[ENDC]}'.format(tcolor, changes, colors)
+                '{0}{1}{2[ENDC]}'.format(tcolor, changes, colors)
             )
 
         # Append result counts to end of output
```

I haven't tried the latest version yet, I'll try to whip up a pull request if it's still an issue there.
