### ISSUE TITLE
salt.modules.mount.active doesn't work on OSX (Mavericks)

### ISSUE THREAD

**Issue by objectx** [saltstack/salt#16382]
On OSX (Mavericks), mount(8) does not have '-l' option.

```
$ salt-call --local -l debug mount.active
[DEBUG   ] Missing configuration file: /etc/salt/minion
[INFO    ] Using cached minion ID from /etc/salt/minion_id: hazel.local
[DEBUG   ] Configuration file path: /etc/salt/minion
[DEBUG   ] Missing configuration file: /etc/salt/minion
[DEBUG   ] Loaded localemod as virtual locale
[DEBUG   ] Loaded osxdesktop as virtual desktop
[DEBUG   ] Loaded sysmod as virtual sys
[DEBUG   ] Loaded launchctl as virtual service
[DEBUG   ] Loaded mac_group as virtual group
[DEBUG   ] Loaded parted as virtual partition
[DEBUG   ] Loaded zcbuildout as virtual buildout
[DEBUG   ] Loaded mac_user as virtual user
[DEBUG   ] Loaded htpasswd as virtual webutil
[DEBUG   ] Loaded cmdmod as virtual cmd
[DEBUG   ] Loaded virtualenv_mod as virtual virtualenv
[DEBUG   ] Loaded darwin_sysctl as virtual sysctl
[DEBUG   ] Loaded djangomod as virtual django
[DEBUG   ] Loaded brew as virtual pkg
[DEBUG   ] Loaded localemod as virtual locale
[DEBUG   ] Loaded osxdesktop as virtual desktop
[DEBUG   ] Loaded sysmod as virtual sys
[DEBUG   ] Loaded launchctl as virtual service
[DEBUG   ] Loaded mac_group as virtual group
[DEBUG   ] Loaded parted as virtual partition
[DEBUG   ] Loaded zcbuildout as virtual buildout
[DEBUG   ] Loaded mac_user as virtual user
[DEBUG   ] Loaded htpasswd as virtual webutil
[DEBUG   ] Loaded cmdmod as virtual cmd
[DEBUG   ] Loaded virtualenv_mod as virtual virtualenv
[DEBUG   ] Loaded darwin_sysctl as virtual sysctl
[DEBUG   ] Loaded djangomod as virtual django
[DEBUG   ] Loaded brew as virtual pkg
[DEBUG   ] Loaded syslog_return as virtual syslog
[DEBUG   ] Loaded couchdb_return as virtual couchdb
[DEBUG   ] Loaded carbon_return as virtual carbon
[DEBUG   ] Loaded sqlite3_return as virtual sqlite3
[DEBUG   ] Loaded saltmod as virtual salt
[DEBUG   ] Loaded zcbuildout as virtual buildout
[DEBUG   ] Loaded virtualenv_mod as virtual virtualenv
[INFO    ] Executing command 'mount -l' in directory '/Users/objectx'
[ERROR   ] Command 'mount -l' failed with return code: 1
[ERROR   ] stderr: mount: illegal option -- l
usage: mount [-dfruvw] [-o options] [-t external_type] special node
       mount [-adfruvw] [-t external_type]
       mount [-dfruvw] special | node
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/local/Cellar/saltstack/2014.1.10/libexec/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/local/Cellar/saltstack/2014.1.10/lib/python2.7/site-packages/salt/scripts.py", line 82, in salt_call
    client.run()
  File "/usr/local/Cellar/saltstack/2014.1.10/lib/python2.7/site-packages/salt/cli/__init__.py", line 319, in run
    caller.run()
  File "/usr/local/Cellar/saltstack/2014.1.10/lib/python2.7/site-packages/salt/cli/caller.py", line 144, in run
    ret = self.call()
  File "/usr/local/Cellar/saltstack/2014.1.10/lib/python2.7/site-packages/salt/cli/caller.py", line 81, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/local/Cellar/saltstack/2014.1.10/lib/python2.7/site-packages/salt/modules/mount.py", line 108, in active
    _active_mountinfo(ret)
  File "/usr/local/Cellar/saltstack/2014.1.10/lib/python2.7/site-packages/salt/modules/mount.py", line 30, in _active_mountinfo
    _list = _list_mounts()
  File "/usr/local/Cellar/saltstack/2014.1.10/lib/python2.7/site-packages/salt/modules/mount.py", line 25, in _list_mounts
    ret[comps[2]] = comps[0]
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/local/Cellar/saltstack/2014.1.10/libexec/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/local/Cellar/saltstack/2014.1.10/lib/python2.7/site-packages/salt/scripts.py", line 82, in salt_call
    client.run()
  File "/usr/local/Cellar/saltstack/2014.1.10/lib/python2.7/site-packages/salt/cli/__init__.py", line 319, in run
    caller.run()
  File "/usr/local/Cellar/saltstack/2014.1.10/lib/python2.7/site-packages/salt/cli/caller.py", line 144, in run
    ret = self.call()
  File "/usr/local/Cellar/saltstack/2014.1.10/lib/python2.7/site-packages/salt/cli/caller.py", line 81, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/local/Cellar/saltstack/2014.1.10/lib/python2.7/site-packages/salt/modules/mount.py", line 108, in active
    _active_mountinfo(ret)
  File "/usr/local/Cellar/saltstack/2014.1.10/lib/python2.7/site-packages/salt/modules/mount.py", line 30, in _active_mountinfo
    _list = _list_mounts()
  File "/usr/local/Cellar/saltstack/2014.1.10/lib/python2.7/site-packages/salt/modules/mount.py", line 25, in _list_mounts
    ret[comps[2]] = comps[0]
IndexError: list index out of range
```

**Comment by jtand** [comment]
@objectx This looks like it has been fixed. I'm going to close this issue. if it still doesn't work for you, reply back and we can open it again.
