### ISSUE TITLE
Race running aptitude update at the same time as list_pkgs

### ISSUE THREAD

**Issue by baconz** [saltstack/salt#16607]
I haven't dived into the code, but we get the exception below _once in a while_ when pkg.list_pkgs is running at the same time as an aptitude update.

```
An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1379, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/states/pkg.py", line 468, in installed
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/states/pkg.py", line 130, in _find_install_targets
    cur_pkgs = __salt__['pkg.list_pkgs'](versions_as_list=True, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/aptpkg.py", line 703, in list_pkgs
    virtpkgs_all = _get_virtual()
  File "/usr/lib/python2.7/dist-packages/salt/modules/aptpkg.py", line 132, in _get_virtual
    apt_cache = apt.cache.Cache()
  File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 102, in __init__
    self.open(progress)
  File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 145, in open
    self._cache = apt_pkg.Cache(progress)
 SystemError: E:Problem renaming the file /var/cache/apt/srcpkgcache.bin.w9sHov to /var/cache/apt/srcpkgcache.bin - rename (2: No such file or directory), E:Problem renaming the file /var/cache/apt/pkgcache.bin.2wWm3u to /var/cache/apt/pkgcache.bin - rename (2: No such file or directory), E:The package lists or status file could not be parsed or opened.
```

We're running Wheezy (7.6) with python-apt 0.8.8.2, and Hydrogen. This problem seems to have cropped up since we started rolling out Hydrogen.

**Comment by baconz** [comment]
Any update on this? I'm willing to submit a patch -- what would people think about retrying a configurable number of times, with a sleep in between if we can't get the lock? Obviously for now, we're stuck catching `SystemError` as an indication of failure.
