### ISSUE TITLE
rest_tornado websockets - Handshake status 404

### ISSUE THREAD

**Issue by carlskii** [saltstack/salt#16799]
Hi, 

I'm using the latest salt development build and I'm getting Handshake status 404 messages when I try to use the WS events API. My Salt "master" config file looks like this.

UPDATE

I just tried the latest 2014.7.0rc5 build but I still get the same issue. Any pointers would be really appreciated.

``` yaml
rest_tornado:
    # can be any port
    port: 8000
    #ssl_crt: /etc/pki/api/certs/server.crt
    # no need to specify ssl_key if cert and key
    # are in one single file
    #ssl_key: /etc/pki/api/certs/server.key
    debug: False
    disable_ssl: True
    websockets: True
```

I then get an auth token like this:

``` bash
curl 172.16.28.146:8000/login -d client=local -d username=tom -d password=passw0rd -d eauth=pam
```

which gives me my token.

``` json
{"return": [{"perms": [".*"], "start": 1413927681.555158, "token": "cd16cbd6e42f1da37104cfa08fea5759", "expire": 1413970881.555159, "user": "tom", "eauth": "pam"}]} 
```

I tried the 'wsdump' utility. e.g.

``` bash
wsdump.py ws://172.16.28.146:8000/all_events/216d60ed81e3d13f164e188b349233a6
Handshake status 404
```

I also tried the Python WS example. e.g.

``` python
from websocket import create_connection

# Get the Websocket connection to Salt
ws = create_connection('ws://172.16.28.146:8000/all_events/216d60ed81e3d13f164e188b349233a6')

# Get Salt's "real time" event stream.
print ws.send('websocket client ready')

print "running"
# Simple listener to print results of Salt's "real time" event stream.
# Look at https://pypi.python.org/pypi/websocket-client/ for more examples.
while listening_to_events:
    print ws.recv()       #  Salt's "real time" event data as serialized JSON.

# Terminates websocket connection and Salt's "real time" event stream on the server.
ws.close()

# Please refer to https://github.com/liris/websocket-client/issues/81 when using a self signed cert
```

``` bash
Traceback (most recent call last):
  File "/Users/cbourne/PycharmProjects/saltstack/python_ws_client.py", line 13, in <module>
    ws = create_connection('ws://172.16.28.146:8000/all_events/' + token)
  File "/Users/cbourne/anaconda/lib/python2.7/site-packages/websocket/_core.py", line 207, in create_connection
    websock.connect(url, **options)
  File "/Users/cbourne/anaconda/lib/python2.7/site-packages/websocket/_core.py", line 462, in connect
    self._handshake(hostname, port, resource, **options)
  File "/Users/cbourne/anaconda/lib/python2.7/site-packages/websocket/_core.py", line 527, in _handshake
    resp_headers = self._get_resp_headers()
  File "/Users/cbourne/anaconda/lib/python2.7/site-packages/websocket/_core.py", line 480, in _get_resp_headers
    raise WebSocketException("Handshake status %d" % status)
websocket._exceptions.WebSocketException: Handshake status 404
```

**Comment by winglet** [comment]
Hi. I bumped on this defect too. Any news about it?

**Comment by cinterloper** [comment]
do you have ws4py installed? rest_cherrypy produces the same error when ws4py is not installed
