### ISSUE TITLE
linux_acl state needed

### ISSUE THREAD

**Issue by rominf** [saltstack/salt#16961]
I need to enforce acl records of some files. There is no `linux_acl` state. For now I'm using `module.wait` with `acl.modfacl` but it's ugly combination. Moreover, this combination works but state returns error:

```
    Function: module.run
        Name: acl.modfacl
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1382, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/states/module.py", line 203, in run
                  if ret['changes'].get('ret', {}).get('retcode', 0) != 0:
              AttributeError: 'bool' object has no attribute 'get'
     Changes:
```

**Comment by eliasp** [comment]
With #17575 merged I think this issue can be closed now.
