### ISSUE TITLE
Type error after new install.

### ISSUE THREAD

**Issue by TristanMatthews** [saltstack/salt#16985]
I spun up a new aws instance and I ran the same bootstrap script I have been running for weeks to setup the instance and install salt, and had salt crash out.

I'm running on Ubuntu 14.04.1 LTS and running the master and minion on the same dev instance. I've just installing salt with:

```
sudo apt-get install salt-minion -y
sudo apt-get install salt-master -y
```

which seems to have installed.  Version: 2014.1.13+ds-1trusty1

My script appears to have installed salt (master and minion) fine, and restarted the them to pick up the config files fine. It then approved the minions keys fine, but when it calls:

sudo salt-call state.highstate

I get:

```
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: string indices must be integers, not str
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 82, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/__init__.py", line 309, in run
    caller = salt.cli.caller.Caller(self.config)
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 47, in __init__
    self.minion = salt.minion.SMinion(opts)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 283, in __init__
    self.gen_modules()
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 295, in gen_modules
    self.opts['environment'],
  File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 78, in compile_pillar
    ret_pillar = self.sreq.crypted_transfer_decode_dictentry(load, dictkey='pillar', tries=3, timeout=7200)
  File "/usr/lib/python2.7/dist-packages/salt/transport/__init__.py", line 61, in crypted_transfer_decode_dictentry
    aes = key.private_decrypt(ret['key'], 4)
TypeError: string indices must be integers, not str
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 82, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/__init__.py", line 309, in run
    caller = salt.cli.caller.Caller(self.config)
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 47, in __init__
    self.minion = salt.minion.SMinion(opts)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 283, in __init__
    self.gen_modules()
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 295, in gen_modules
    self.opts['environment'],
  File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 78, in compile_pillar
    ret_pillar = self.sreq.crypted_transfer_decode_dictentry(load, dictkey='pillar', tries=3, timeout=7200)
  File "/usr/lib/python2.7/dist-packages/salt/transport/__init__.py", line 61, in crypted_transfer_decode_dictentry
    aes = key.private_decrypt(ret['key'], 4)
TypeError: string indices must be integers, not str
```

I assumed I had messed up building my pillar file some how, but 

```
sudo salt-call pillar.items
```

seems to indicate that everything is in order, while,

```
sudo salt-call grain.items
```

Throws what appears to be the same error as above. I haven't defined any custom grains for this instance, so I'm wondering how its messed up.

In an attempt to reproduce the error I spun up a new instance and called the same script on it. Everything ran through fine, the same as every other time I have used it.

**Comment by frogunder** [comment]
Can we close this? It seems like the issues has been resolved.

**Comment by basepi** [comment]
Thanks @frogunder! Not sure how I missed that step, given my last comment....
