### ISSUE TITLE
Using external modules in Python SLS files.

### ISSUE THREAD

**Issue by carlskii** [saltstack/salt#16992]
This is related to #16978 but is really a different issue.

I'm using a Python SLS file and need to import some external modules to assist with its creation. 

e.g.

``` python
#!py
import sys
sys.path.append('/srv/salt')
from authenticate import base_url
from authenticate import auth_key

def run():
     get_auth_key()
     config = {}

     config['fred'] = {
         'user.present': [
             {'fullname': 'fred'},
             {'shell': '/bin/bash'},
             {'home': '/home/fred'},
             {'roomnumber': get_auth_key()['apiKey'] }
         ]
        }
     return config
```

I tried using `sys.path.append` and then copying the module to `/srv/salt` but that did not work.

```
    Data failed to compile:
----------
    Rendering SLS allpython failed, render error: No module named authenticate
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2407, in render_state
    sls, rendered_sls=mods
  File "/usr/lib/python2.7/dist-packages/salt/template.py", line 84, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/renderers/py.py", line 108, in render
    **kws)
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 380, in py
    sfn
  File "/var/cache/salt/minion/files/base/allpython.sls", line 4, in <module>
    from authenticate import base_url
ImportError: No module named authenticate
```

Setting the `PYTHONPATH` does not work either.

I also created a package and installed it to the standard python package location e.g.

```
$pip list
authenticate (0.1)
apt-xapian-index (0.45)
argparse (1.2.1)
......
```

But that doesn't seem to work either. 

Am I missing something here?

**Comment by vitalyisaev2** [comment]
+1 It would be nice to have an opportunity to import python standalone files from ```!Py``` SLS files

**Comment by kyrias** [comment]
I think it would probably make sense to have the file_roots be added to the default Python path at least.
