### ISSUE TITLE
Develop branch broken on Windows

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#17010]
On the develop branch I'm getting this:
```
C:\Python27\Scripts>python salt-minion -l debug -c c:\salt\conf
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\python27\lib\multiprocessing\forking.py", line 380, in main
    prepare(preparation_data)
  File "C:\python27\lib\multiprocessing\forking.py", line 489, in prepare
    file, path_name, etc = imp.find_module(main_name, dirs)
ImportError: No module named salt-minion
```

I think this happens when we're not using threading on Windows, so I don't know if someone messed up the windows check or not, but it looks like we're trying to use multiprocessing.

**Comment by UtahDave** [comment]
I figured out what my problem was. While jumping between branches doing testing I hadn't been deleting the `build` directory in my local git clone. Stale files were apparently being copied around from there.

Deleting the `build` directory between installs fixed this for me.

Thanks for the help, everyone.
