### ISSUE TITLE
salt-cloud vsphere could not run in parallel

### ISSUE THREAD

**Issue by mochrul** [saltstack/salt#17149]
The version I use is v2014.7.0rc7
If I start the deploying with a map file in parallel. The salt-cloud return with an error.

Process PoolWorker-7:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 99, in worker
    put((job, i, result))
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 390, in put
    return send(obj)
PicklingError: Can't pickle <class 'pysphere.resources.VimService_services_types.DynamicData_Holder'>: attribute lookup pysphere.resources.VimService_services_types.DynamicData_Holder failed
[INFO    ] Salt installed on template_zts_dbo-tests_launchpad
[INFO    ] Created Cloud VM 'template_zts_dbo-tests_launchpad'
Process PoolWorker-8:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 99, in worker
    put((job, i, result))
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 390, in put
    return send(obj)
PicklingError: Can't pickle <class 'pysphere.resources.VimService_services_types.DynamicData_Holder'>: attribute lookup pysphere.resources.VimService_services_types.DynamicData_Holder failed
[INFO    ] Salt installed on template_zts_dbo-tests_zbs

If I run ith without the -P option it's run smoothly.

And after this happen, the salt-cloud is unstoppable.

**Comment by nmadhok** [comment]
This has been fixed in the new vmware salt-cloud driver.

**Comment by techhat** [comment]
The vsphere driver has been marked as deprecated in favor of the vmware driver. Thanks for your help, @nmadhok.

**Comment by nmadhok** [comment]
@techhat You're welcome! :smile:
