### ISSUE TITLE
Salt-Cloud for vSphere needs additional documentation

### ISSUE THREAD

**Issue by hasues** [saltstack/salt#17241]
http://docs.saltstack.com/en/latest/ref/clouds/all/salt.cloud.clouds.vsphere.html

Based on https://github.com/saltstack/salt/issues/17061 it seems that the documentatioin is missing the notes that VM images need to have:
template_user
template_password
and/or SSH keys for said user from the salt-master to connect and work.

This needs to be documented to make this more intuitive for use.  If this is not the place to note said issues, please give me the appropriate resource.  Thanks!

**Comment by hasues** [comment]
A PR for documentation?  Is there a repository for such?  I can arrange it if I know where this is?

**Comment by rallytime** [comment]
@hasues The documentation is hosted in the same repo as salt itself. All documentation is located under `salt/doc`. From there, each page in the [current docs](http://docs.saltstack.com/en/latest/) has the same directory structure in the web addresses as the `salt/doc` directory structure. Does that help answer your question?

**Comment by danielgblanco** [comment]
Just to add a comment here, the 'template_user' has to be 'root', otherwise it won't work because that is the user used to run the install script. I tried with a different user and it'll give the following error:

```
 * ERROR: Salt requires root privileges to install. Please re-run this script as root.
[DEBUG   ]  * ERROR: Salt requires root privileges to install. Please re-run this script as root.

[DEBUG   ] LazyLoaded nested.output
Exception occurred in runner cloud.profile: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 317, in low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/runners/cloud.py", line 106, in profile
    info = client.profile(prof, instances, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 335, in profile
    mapper.run_profile(profile, names, vm_overrides=vm_overrides)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1388, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1241, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/vsphere.py", line 260, in create
    deploy_kwargs = _deploy(vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/vsphere.py", line 410, in _deploy
    deployed = salt.utils.cloud.deploy_script(**deploy_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 1271, in deploy_script
    if root_cmd(deploy_command, tty, sudo, **ssh_kwargs) != 0:
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 1751, in root_cmd
    retcode = _exec_ssh_cmd(cmd, allow_failure=allow_failure, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 1448, in _exec_ssh_cmd
    cmd, proc.exitstatus
SaltCloudSystemExit: Command 'ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -p 22 vsphere@10.0.1.61 \'/tmp/.saltcloud-af15a78c-6160-494c-a73b-d174c8918b22/deploy.sh -c \'"\'"\'/tmp/.saltcloud-af15a78c-6160-494c-a73b-d174c8918b22\'"\'"\'\'' failed. Exit code: 1
```

**Comment by danielgblanco** [comment]
I'd also like to add that that the user I'm trying to install the minion with has the same "sudoers" privileges as the "ec2-user" in EC2, and there it works fine not being "root". Am I missing something?

**Comment by danielgblanco** [comment]
Hi,

After digging a bit into the code I found that the vSphere module did not set the 'sudo' or 'sudo_password' properties anywhere when deploying, so I compared my version of Salt (2015.5.0) with the current develop branch. This bug was fixed on 6 Feb (https://github.com/saltstack/salt/commit/bb916935f173350b39c226fe507e43bc82be4655) but it has not yet been released. It is working now.

Thanks,

Dan

**Comment by rallytime** [comment]
As mentioned by @danielgblanco, this was fixed with #20474, and then back-ported to the 2015.5 branch with #24192. The fix should be available in the latest stable release, 2015.5.2.

I am going to keep this open for now, as we should document this new capability, as mentioned above.

However, please note that the vshpere driver is on a deprecation path and will be officially removed in Salt Carbon (see #24487 and #24504). As such, we'd recommend moving to the new vmware driver as discussed above. Since we have a much more robust and clean driver, we won't be spending time cleaning up bugs for vsphere. However, we will of course be accepting fixes from community members as they are submitted.

If you'd like to try the vmware driver now, the new vmware will be available in a packaged version when Salt Beryllium is release (the next upcoming feature release). However, there are some good instructions on how to try it now at the end of the conversation in #23705

**Comment by rallytime** [comment]
I've added some addition documentation in #24718.

**Comment by steverweber** [comment]
fyi, I switched to this driver and seems to be working well.  Good job!

**Comment by molixrawdi** [comment]
This is what I got! any ideas please? I was hoping to get this running. Sadly this happened, I would be very grateful if you could help. Not that good at Python yet.


An un-handled exception was caught by salt's global exception handler:
AttributeError: 'module' object has no attribute '_create_loader'
Traceback (most recent call last):
  File "/usr/bin/salt-cloud", line 4, in <module>
    __import__('pkg_resources').run_script('salt-cloud==0.8.11', 'salt-cloud')
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1652, in run_script
    exec(code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/salt_cloud-0.8.11-py2.7.egg/EGG-INFO/scripts/salt-cloud", line 14, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/salt_cloud-0.8.11-py2.7.egg/EGG-INFO/scripts/salt-cloud", line 10, in main
    cloud.run()
  File "/usr/lib/python2.7/site-packages/salt_cloud-0.8.11-py2.7.egg/saltcloud/cli.py", line 173, in run
    mapper = saltcloud.cloud.Map(self.config)
  File "/usr/lib/python2.7/site-packages/salt_cloud-0.8.11-py2.7.egg/saltcloud/cloud.py", line 863, in __init__
    Cloud.__init__(self, opts)
  File "/usr/lib/python2.7/site-packages/salt_cloud-0.8.11-py2.7.egg/saltcloud/cloud.py", line 53, in __init__
    self.clouds = saltcloud.loader.clouds(self.opts)
  File "/usr/lib/python2.7/site-packages/salt_cloud-0.8.11-py2.7.egg/saltcloud/loader.py", line 42, in clouds
    load = salt.loader._create_loader(
AttributeError: 'module' object has no attribute '_create_loader'
Traceback (most recent call last):
  File "/usr/bin/salt-cloud", line 4, in <module>
    __import__('pkg_resources').run_script('salt-cloud==0.8.11', 'salt-cloud')
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1652, in run_script
    exec(code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/salt_cloud-0.8.11-py2.7.egg/EGG-INFO/scripts/salt-cloud", line 14, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/salt_cloud-0.8.11-py2.7.egg/EGG-INFO/scripts/salt-cloud", line 10, in main
    cloud.run()
  File "/usr/lib/python2.7/site-packages/salt_cloud-0.8.11-py2.7.egg/saltcloud/cli.py", line 173, in run
    mapper = saltcloud.cloud.Map(self.config)
  File "/usr/lib/python2.7/site-packages/salt_cloud-0.8.11-py2.7.egg/saltcloud/cloud.py", line 863, in __init__
    Cloud.__init__(self, opts)
  File "/usr/lib/python2.7/site-packages/salt_cloud-0.8.11-py2.7.egg/saltcloud/cloud.py", line 53, in __init__
    self.clouds = saltcloud.loader.clouds(self.opts)
  File "/usr/lib/python2.7/site-packages/salt_cloud-0.8.11-py2.7.egg/saltcloud/loader.py", line 42, in clouds
    load = salt.loader._create_loader(
AttributeError: 'module' object has no attribute '_create_loader'

**Comment by rallytime** [comment]
@molixrawdi Thanks for commenting here. Since this issue is closed, would you mind opening a new issue with this stacktrace and other relevant information? Please include what you're trying to accomplish/the command you ran as well as the the output of `salt-cloud --versions-report` and how you installed salt or salt-cloud and we can go from there. Thanks!

**Comment by molixrawdi** [comment]
Hi Nicole,
                Thank you for the prompt reply, I installed on fedora 22
server, using pip install salt-cloud. I have tried to install on CentOS7
and in the same way I faced

salt-cloud -p centos7_vcenterfoo myFirstSaltVM
[ERROR   ] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/parsers.py", line 155,
in parse_args
    process_option_func()
  File "/usr/lib/python2.7/site-packages/saltcloud/utils/parsers.py", line
117, in process_cloud_config
    vm_config_path=self.options.vm_config
  File "/usr/lib/python2.7/site-packages/saltcloud/config.py", line 206, in
cloud_config
    providers_config = cloud_providers_config(providers_config_path)
  File "/usr/lib/python2.7/site-packages/saltcloud/config.py", line 499, in
cloud_providers_config
    return apply_cloud_providers_config(overrides, defaults)
  File "/usr/lib/python2.7/site-packages/saltcloud/config.py", line 564, in
apply_cloud_providers_config
    if 'provider' not in entry:
TypeError: argument of type 'NoneType' is not iterable
Usage: salt-cloud

salt-cloud: error: Error while processing <bound method
SaltCloud.process_cloud_config of <saltcloud.cli.SaltCloud object at
0x2284790>>: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/parsers.py", line 155,
in parse_args
    process_option_func()
  File "/usr/lib/python2.7/site-packages/saltcloud/utils/parsers.py", line
117, in process_cloud_config
    vm_config_path=self.options.vm_config
  File "/usr/lib/python2.7/site-packages/saltcloud/config.py", line 206, in
cloud_config
    providers_config = cloud_providers_config(providers_config_path)
  File "/usr/lib/python2.7/site-packages/saltcloud/config.py", line 499, in
cloud_providers_config
    return apply_cloud_providers_config(overrides, defaults)
  File "/usr/lib/python2.7/site-packages/saltcloud/config.py", line 564, in
apply_cloud_providers_config
    if 'provider' not in entry:
TypeError: argument of type 'NoneType' is not iterable


Best Regards
Mo
