### ISSUE TITLE
ValueError: unknown url type: top.sls while running saltutil.sync_all

### ISSUE THREAD

**Issue by billcchung** [saltstack/salt#17286]
While running saltutil.sync_all, I often hit the following issue:

    root@ip-172-31-42-67:/srv/salt# salt '*' saltutil.sync_all
    cchung-idx:
        ----------
        grains:
        modules:
        outputters:
        renderers:
        returners:
        states:
    cchung-sh:
        The minion function caused an exception: Traceback (most recent call last):
          File "salt/minion.py", line 809, in _thread_return
          File "salt/modules/saltutil.py", line 343, in sync_all
          File "salt/modules/saltutil.py", line 228, in sync_modules
          File "salt/modules/saltutil.py", line 73, in _sync
          File "salt/modules/saltutil.py", line 55, in _get_top_file_envs
          File "salt/state.py", line 2042, in get_top
          File "salt/state.py", line 1915, in get_tops
          File "salt/fileclient.py", line 143, in cache_file
          File "salt/fileclient.py", line 537, in get_url
          File "urllib2.py", line 127, in urlopen
          File "urllib2.py", line 396, in open
          File "urllib2.py", line 258, in get_type
        ValueError: unknown url type: top.sls
     cchung-spl86889-idx:
        ----------
        grains:
        modules:
        outputters:
        renderers:
        returners:
        states:
    cchung-spl86889-sh:
        The minion function caused an exception: Traceback (most recent call last):
          File "salt/minion.py", line 809, in _thread_return
          File "salt/modules/saltutil.py", line 344, in sync_all
          File "salt/modules/saltutil.py", line 247, in sync_states
          File "salt/modules/saltutil.py", line 73, in _sync
          File "salt/modules/saltutil.py", line 55, in _get_top_file_envs
          File "salt/state.py", line 2042, in get_top
          File "salt/state.py", line 1915, in get_tops
          File "salt/fileclient.py", line 143, in cache_file
          File "salt/fileclient.py", line 537, in get_url
          File "urllib2.py", line 127, in urlopen
          File "urllib2.py", line 396, in open
          File "urllib2.py", line 258, in get_type
        ValueError: unknown url type: top.sls

salt versions:

    root@ip-172-31-42-67:/srv/salt# salt --versions-report
               Salt: 2014.1.10
             Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
             Jinja2: 2.7.2
           M2Crypto: 0.21.1
     msgpack-python: 0.3.0
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
             PyYAML: 3.10
              PyZMQ: 14.0.1
                ZMQ: 4.0.4

    root@ip-172-31-42-67:/srv/salt# salt '*' test.versions_report
    cchung-spl86889-idx:
                   Salt: 2014.1.11
                 Python: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]
                 Jinja2: 2.7.1
               M2Crypto: 0.21.1
         msgpack-python: 0.4.2
           msgpack-pure: Not Installed
               pycrypto: 2.6
                 PyYAML: 3.11
                  PyZMQ: 14.1.1
                    ZMQ: 4.0.4

master is running on ubuntu 14.04, and minions are running on windows2008R2, I dont get why top.sls sometimes get passed as an url?
Could someone help me out? We need a stabler behavior before we can move our deployment to next step, any help will be really appreciated.
Thanks!

**Comment by rallytime** [comment]
@billcchung Thanks for the update. I'm going to close the out since we haven't heard anything about this for a while. If it pops up again, definitely leave a comment and we can re-open and re-assess. Thanks!
