### ISSUE TITLE
Python3 compatibility conversion failed for the following state modules

### ISSUE THREAD

**Issue by nmadhok** [saltstack/salt#17703]
@thatch45

Conversion to Python3 failed for the following state modules:
cmd.py

```
RefactoringTool: Skipping implicit fixer: idioms
RefactoringTool: Skipping implicit fixer: set_literal
RefactoringTool: Skipping implicit fixer: ws_comma
Traceback (most recent call last):
  File "/usr/bin/python-modernize", line 9, in <module>
    load_entry_point('modernize==0.4', 'console_scripts', 'python-modernize')()
  File "/usr/lib/python2.6/site-packages/libmodernize/main.py", line 138, in main
    options.processes)
  File "/usr/lib64/python2.6/lib2to3/refactor.py", line 620, in refactor
    items, write, doctests_only)
  File "/usr/lib64/python2.6/lib2to3/refactor.py", line 275, in refactor
    self.refactor_file(dir_or_file, write, doctests_only)
  File "/usr/lib64/python2.6/lib2to3/refactor.py", line 661, in refactor_file
    *args, **kwargs)
  File "/usr/lib64/python2.6/lib2to3/refactor.py", line 327, in refactor_file
    tree = self.refactor_string(input, filename)
  File "/usr/lib64/python2.6/lib2to3/refactor.py", line 359, in refactor_string
    self.refactor_tree(tree, name)
  File "/usr/lib64/python2.6/lib2to3/refactor.py", line 393, in refactor_tree
    self.traverse_by(self.post_order_heads, tree.post_order())
  File "/usr/lib64/python2.6/lib2to3/refactor.py", line 417, in traverse_by
    new = fixer.transform(node, results)
  File "/usr/lib/python2.6/site-packages/libmodernize/fixes/fix_import.py", line 23, in transform
    libmodernize.add_future(node, 'absolute_import')
  File "/usr/lib/python2.6/site-packages/libmodernize/__init__.py", line 46, in add_future
    root = fixer_util.find_root(node)
  File "/usr/lib64/python2.6/lib2to3/fixer_util.py", line 265, in find_root
    assert node.parent, "Tree is insane! root found before "\
AssertionError: Tree is insane! root found before file_input node was found.
```

**Comment by ssgward** [comment]
@nmadhok - still an issue or has it been fixed?
