### ISSUE TITLE
runner behavior broken or at least different from before

### ISSUE THREAD

**Issue by kiorky** [saltstack/salt#17735]
related to #17701
I have a custom runner that was running fine and outputting its results to the console, see that: https://github.com/makinacorpus/makina-states/blob/master/mc_states/runners/mc_cloud_controller.py

Now, it seems to be stuck in the even poll function and the last bits i get are:
```
[DEBUG   ] LazyLoaded local_cache.save_runner_load
[DEBUG   ] The specified returner used for the master job cache "local_cache" does not have a save_runner_load function! The results of this runner execution will not be stored.

```

The traceback on controlC
```
^C[ERROR   ] Traceback (most recent call last):
  File "/srv/mastersalt/makina-states/src/salt/salt/scripts.py", line 245, in salt_run
    client.run()
  File "/srv/mastersalt/makina-states/src/salt/salt/cli/__init__.py", line 471, in run
    runner.run()
  File "/srv/mastersalt/makina-states/src/salt/salt/runner.py", line 303, in run
    for ret in self.get_runner_returns(jid):
  File "/srv/mastersalt/makina-states/src/salt/salt/runner.py", line 329, in get_runner_returns
    raw = self.event.get_event(timeout, full=True)
  File "/srv/mastersalt/makina-states/src/salt/salt/utils/event.py", line 341, in get_event
    ret = self._get_event(wait, tag, pending_tags)
  File "/srv/mastersalt/makina-states/src/salt/salt/utils/event.py", line 287, in _get_event
    socks = dict(self.poller.poll(wait * 1000))
  File "/srv/mastersalt/makina-states/eggs/pyzmq-14.4.1-py2.7-linux-x86_64.egg/zmq/sugar/poll.py", line 101, in poll
    return zmq_poll(self.sockets, timeout=timeout)
  File "zmq/backend/cython/_poll.pyx", line 115, in zmq.backend.cython._poll.zmq_poll (zmq/backend/cython/_poll.c:1589)
  File "zmq/backend/cython/checkrc.pxd", line 11, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/_poll.c:1793)
    PyErr_CheckSignals()
  File "/srv/mastersalt/makina-states/eggs/async-0.6.1-py2.7-linux-x86_64.egg/async/__init__.py", line 21, in thread_interrupt_handler
    prev_handler(signum, frame)
KeyboardInterrupt

```

**Comment by kiorky** [comment]
So we are waiting here for #19729 to be merged to return to a more stable space on runners behavior.

**Comment by kiorky** [comment]
resolved.
