### ISSUE TITLE
import problems with six-library

### ISSUE THREAD

**Issue by felskrone** [saltstack/salt#17949]
Because of #17943 i installed python-six from wheezy-backports on my debian-squeeze-masters.

While the lib itself seems to work fine, it wont play along with salt.

```python
Python 2.6.6 (r266:84292, Aug 12 2014, 07:57:07) 
[GCC 4.4.5] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import six
>>> six
<module 'six' from '/usr/lib/python2.6/dist-packages/six.pyc'>
>>> import six.moves
>>> six.moves
<module 'six.moves' (built-in)>
>>> from six.moves import range
>>> range
<type 'xrange'>
```
Trying to start the salt-master fails with import-errors:

```python
$ salt-master -l debug
Traceback (most recent call last):
  File "/usr/bin/salt-master", line 6, in <module>
    from salt.scripts import salt_master
  File "/usr/lib/pymodules/python2.6/salt/__init__.py", line 44, in <module>
    from salt.utils import migrations
  File "/usr/lib/pymodules/python2.6/salt/utils/__init__.py", line 107, in <module>
    import salt.payload
  File "/usr/lib/pymodules/python2.6/salt/payload.py", line 14, in <module>
    import salt.crypt
  File "/usr/lib/pymodules/python2.6/salt/crypt.py", line 35, in <module>
    import salt.minion
  File "/usr/lib/pymodules/python2.6/salt/minion.py", line 60, in <module>
    import salt.client
  File "/usr/lib/pymodules/python2.6/salt/client/__init__.py", line 39, in <module>
    import salt.utils.event
  File "/usr/lib/pymodules/python2.6/salt/utils/event.py", line 76, in <module>
    import salt.state
  File "/usr/lib/pymodules/python2.6/salt/state.py", line 42, in <module>
    from six.moves import range
ImportError: cannot import name range
```
Running state.py by itself already fails:

```python
$ python state.py 
Traceback (most recent call last):
  File "state.py", line 28, in <module>
    import salt.utils
  File "/usr/lib/pymodules/python2.6/salt/__init__.py", line 44, in <module>
    from salt.utils import migrations
  File "/usr/lib/pymodules/python2.6/salt/utils/__init__.py", line 107, in <module>
    import salt.payload
  File "/usr/lib/pymodules/python2.6/salt/payload.py", line 14, in <module>
    import salt.crypt
  File "/usr/lib/pymodules/python2.6/salt/crypt.py", line 35, in <module>
    import salt.minion
  File "/usr/lib/pymodules/python2.6/salt/minion.py", line 60, in <module>
    import salt.client
  File "/usr/lib/pymodules/python2.6/salt/client/__init__.py", line 39, in <module>
    import salt.utils.event
  File "/usr/lib/pymodules/python2.6/salt/utils/event.py", line 76, in <module>
    import salt.state
  File "/usr/lib/pymodules/python2.6/salt/state.py", line 42, in <module>
    from six.moves import range
ImportError: cannot import name range
```

This also brakes 'salt --versions', but running the version.py by itself returns:
```bash
$ python salt/version.py
2014.7.0rc4-5151-g33a97c3
```

All other versions:
```yaml
         Python: 2.6.6 (r266:84292, Aug 12 2014, 07:57:07)
         Jinja2: 2.5.5
       M2Crypto: 0.20.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.1.0
        libnacl: Not Installed
         PyYAML: 3.09
          ioflo: Not Installed
          PyZMQ: 13.1.0
           RAET: Not Installed
            ZMQ: 3.2.3
           Mako: Not Installed
```

**Comment by cachedout** [comment]
We've moved all of this into ```salt.ext.six```.

@felskrone Could you re-test against HEAD please?

**Comment by cachedout** [comment]
This has been fixed for quite some time now. I'm going to go ahead and close this. Thanks, all!
