### ISSUE TITLE
Running states throws exceptions

### ISSUE THREAD

**Issue by tmandry** [saltstack/salt#18085]
Trying to run states on any minion bounces between these two errors: `TypeError: string indices must be integers, not str`, `salt.exceptions.AuthenticationError: message authentication failed`, and success. It feels like roughly a 1/3 chance for each of these outcomes. [Someone else](http://irclog.perlgeek.de/salt/2014-10-21#i_9539940) seems to have experienced the same problem.

These states previously worked, and now suddenly nothing seems to work. The only change I know of is adding a couple repositories to `gitfs_remotes` and restarting the master.

This occurs when calling salt states using the `salt` command on the master (and different minions can have different outcomes), but I've included `salt-call` here for debugging:

### Error 1
```
# salt-call -l debug state.sls salt.master
[DEBUG   ] Reading configuration from /etc/salt/minion
[INFO    ] Using cached minion ID from /etc/salt/minion_id: salt-master
[DEBUG   ] Configuration file path: /etc/salt/minion
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: string indices must be integers, not str
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 82, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/__init__.py", line 309, in run
    caller = salt.cli.caller.Caller(self.config)
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 47, in __init__
    self.minion = salt.minion.SMinion(opts)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 283, in __init__
    self.gen_modules()
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 295, in gen_modules
    self.opts['environment'],
  File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 78, in compile_pillar
    ret_pillar = self.sreq.crypted_transfer_decode_dictentry(load, dictkey='pillar', tries=3, timeout=7200)
  File "/usr/lib/python2.7/dist-packages/salt/transport/__init__.py", line 61, in crypted_transfer_decode_dictentry
    aes = key.private_decrypt(ret['key'], 4)
TypeError: string indices must be integers, not str
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 82, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/__init__.py", line 309, in run
    caller = salt.cli.caller.Caller(self.config)
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 47, in __init__
    self.minion = salt.minion.SMinion(opts)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 283, in __init__
    self.gen_modules()
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 295, in gen_modules
    self.opts['environment'],
  File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 78, in compile_pillar
    ret_pillar = self.sreq.crypted_transfer_decode_dictentry(load, dictkey='pillar', tries=3, timeout=7200)
  File "/usr/lib/python2.7/dist-packages/salt/transport/__init__.py", line 61, in crypted_transfer_decode_dictentry
    aes = key.private_decrypt(ret['key'], 4)
TypeError: string indices must be integers, not str
```

### Error 2
```
# salt-call -l debug state.sls salt.master
[DEBUG   ] Reading configuration from /etc/salt/minion
[INFO    ] Using cached minion ID from /etc/salt/minion_id: salt-master
[DEBUG   ] Configuration file path: /etc/salt/minion
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Loaded localemod as virtual locale
[DEBUG   ] Loaded groupadd as virtual group
[DEBUG   ] Loaded parted as virtual partition
[DEBUG   ] Loaded linux_sysctl as virtual sysctl
[DEBUG   ] Loaded debian_ip as virtual ip
[DEBUG   ] Loaded sysmod as virtual sys
[DEBUG   ] Loaded aptpkg as virtual pkg
[DEBUG   ] Loaded zcbuildout as virtual buildout
[DEBUG   ] Loaded upstart as virtual service
[DEBUG   ] Loaded useradd as virtual user
[DEBUG   ] Loaded dpkg as virtual lowpkg
[DEBUG   ] Loaded grub_legacy as virtual grub
[DEBUG   ] Loaded debconfmod as virtual debconf
[DEBUG   ] Loaded virtualenv_mod as virtual virtualenv
[DEBUG   ] Loaded djangomod as virtual django
[DEBUG   ] Loaded cmdmod as virtual cmd
[DEBUG   ] Loaded couchdb_return as virtual couchdb
[DEBUG   ] Loaded syslog_return as virtual syslog
[DEBUG   ] Loaded carbon_return as virtual carbon
[DEBUG   ] Loaded sqlite3_return as virtual sqlite3
[DEBUG   ] Loaded pip_state as virtual pip
[DEBUG   ] Loaded saltmod as virtual salt
[DEBUG   ] Loaded zcbuildout as virtual buildout
[DEBUG   ] Loaded debconfmod as virtual debconf
[DEBUG   ] Loaded virtualenv_mod as virtual virtualenv
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Failed to authenticate message
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Failed to authenticate message
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Failed to authenticate message
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AuthenticationError: message authentication failed
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 82, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/__init__.py", line 319, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 144, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 81, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 368, in sls
    st_ = salt.state.HighState(opts, pillar, kwargs.get('__pub_jid'))
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2606, in __init__
    BaseHighState.__init__(self, opts)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1831, in __init__
    self.avail = self.__gather_avail()
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1841, in __gather_avail
    avail[saltenv] = self.client.list_states(saltenv)
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 393, in list_states
    for path in self.file_list(saltenv):
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 987, in file_list
    return channel.send(load)
  File "/usr/lib/python2.7/dist-packages/salt/transport/__init__.py", line 91, in send
    return self._crypted_transfer(load, tries, timeout)
  File "/usr/lib/python2.7/dist-packages/salt/transport/__init__.py", line 83, in _crypted_transfer
    return _do_transfer()
  File "/usr/lib/python2.7/dist-packages/salt/transport/__init__.py", line 77, in _do_transfer
    timeout)
  File "/usr/lib/python2.7/dist-packages/salt/crypt.py", line 505, in loads
    data = self.decrypt(data)
  File "/usr/lib/python2.7/dist-packages/salt/crypt.py", line 482, in decrypt
    raise AuthenticationError('message authentication failed')
AuthenticationError: message authentication failed
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 82, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/__init__.py", line 319, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 144, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 81, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 368, in sls
    st_ = salt.state.HighState(opts, pillar, kwargs.get('__pub_jid'))
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2606, in __init__
    BaseHighState.__init__(self, opts)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1831, in __init__
    self.avail = self.__gather_avail()
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1841, in __gather_avail
    avail[saltenv] = self.client.list_states(saltenv)
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 393, in list_states
    for path in self.file_list(saltenv):
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 987, in file_list
    return channel.send(load)
  File "/usr/lib/python2.7/dist-packages/salt/transport/__init__.py", line 91, in send
    return self._crypted_transfer(load, tries, timeout)
  File "/usr/lib/python2.7/dist-packages/salt/transport/__init__.py", line 83, in _crypted_transfer
    return _do_transfer()
  File "/usr/lib/python2.7/dist-packages/salt/transport/__init__.py", line 77, in _do_transfer
    timeout)
  File "/usr/lib/python2.7/dist-packages/salt/crypt.py", line 505, in loads
    data = self.decrypt(data)
  File "/usr/lib/python2.7/dist-packages/salt/crypt.py", line 482, in decrypt
    raise AuthenticationError('message authentication failed')
salt.exceptions.AuthenticationError: message authentication failed
```

### salt command

Here are some failure modes when using the `salt` command:

#### Inconsistent response
I ran these three commands in a row and got these three responses. No time in between.
```
# salt 'analytics-es*' pkg.remove elasticsearch
Failed to authenticate, is this user permitted to execute commands?
```
```
# salt 'analytics-es*' pkg.remove elasticsearch
```
```
# salt 'analytics-es*' pkg.remove elasticsearch
analytics-es3:
    ----------
analytics-es1:
    ----------
```
#### Success with an error message
```
# salt 'analytics-es*' state.sls sysctl
analytics-es3:
    TypeError encountered executing state.sls: string indices must be integers, not str. See debug log for more info.  Possibly a missing
 arguments issue:  ArgSpec(args=['mods', 'saltenv', 'test', 'exclude', 'queue', 'env'], varargs=None, keywords='kwargs', defaults=('base'
, None, None, False, None))
analytics-es1:
----------
          ID: sysctl-vm.swappiness
    Function: sysctl.present
        Name: vm.swappiness
      Result: True
     Comment: Updated sysctl value vm.swappiness = 0
     Changes:
              ----------
              vm.swappiness:
                  0
----------
          ID: sysctl-vm.max_map_count
    Function: sysctl.present
        Name: vm.max_map_count
      Result: True
     Comment: Updated sysctl value vm.max_map_count = 262144
     Changes:
              ----------
              vm.max_map_count:
                  262144

Summary
------------
Succeeded: 2
Failed:    0
------------
Total:     2
```
#### Mixed error messages
```
# salt 'analytics-es*' state.sls sysctl
analytics-es3:
    TypeError encountered executing state.sls: string indices must be integers, not str. See debug log for more info.  Possibly a missing arguments issue:  ArgSpec(args=['mods', 'saltenv', 'test', 'exclude', 'queue', 'env'], varargs=None, keywords='kwargs', defaults=('base', None, None, False, None))
analytics-es1:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 809, in _thread_return
        return_data = func(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 381, in sls
        high_, errors = st_.render_highstate({saltenv: mods})
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2405, in render_highstate
        sls, saltenv, mods, matches)
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2104, in render_state
        state_data = self.client.get_state(sls, saltenv)
      File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 413, in get_state
        dest = self.cache_file(path, saltenv)
      File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 143, in cache_file
        return self.get_url(path, '', True, saltenv)
      File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 503, in get_url
        return self.get_file(url, dest, makedirs, saltenv)
      File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 919, in get_file
        data = channel.send(load)
      File "/usr/lib/python2.7/dist-packages/salt/transport/__init__.py", line 91, in send
        return self._crypted_transfer(load, tries, timeout)
      File "/usr/lib/python2.7/dist-packages/salt/transport/__init__.py", line 83, in _crypted_transfer
        return _do_transfer()
      File "/usr/lib/python2.7/dist-packages/salt/transport/__init__.py", line 77, in _do_transfer
        timeout)
      File "/usr/lib/python2.7/dist-packages/salt/crypt.py", line 505, in loads
        data = self.decrypt(data)
      File "/usr/lib/python2.7/dist-packages/salt/crypt.py", line 482, in decrypt
        raise AuthenticationError('message authentication failed')
    AuthenticationError: message authentication failed
```

### Version
Using the `2014.1.13+ds-1trusty1` apt package
```
# salt --versions-report
           Salt: 2014.1.13
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
            ZMQ: 4.0.4
# uname -a
Linux salt-master 3.13.0-29-generic #53-Ubuntu SMP Wed Jun 4 21:00:20 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```
I had a version prior to this that also had the problem (unfortunately, I didn't check the version number before I upgraded).

**Comment by rallytime** [comment]
I'm closing this since we didn't hear back. If this remains and issue, leave a comment and we will reopen. Thanks!

**Comment by tmandry** [comment]
Sorry, this got buried. I upgraded to 2014.7 and we haven't seen the problem since.

**Comment by rallytime** [comment]
No problem! Glad you're not hitting this bug anymore. :)
