### ISSUE TITLE
Minion install ends with a stack trace

### ISSUE THREAD

**Issue by soodr** [saltstack/salt#18244]
Getting a stack trace when executing a minion install on a Windows Server 2008 R2 DataCenter VM.
```
c:\salt>salt-minion --versions-report
           Salt: 2014.7.0
         Python: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]
         Jinja2: 2.7.1
       M2Crypto: 0.21.1
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.1.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "__main__.py", line 726, in <module>
  File "__main__.py", line 332, in bootstrap
  File "__main__.py", line 359, in chainload
  File "__main__.py", line 715, in _chainload
  File "__main__.py", line 128, in <module>
  File "__main__salt-minion__.py", line 17, in <module>
  File "salt/scripts.py", line 56, in salt_minion
  File "salt/__init__.py", line 262, in start
  File "salt/__init__.py", line 168, in prepare
  File "salt/utils/parsers.py", line 126, in parse_args
  File "salt/utils/parsers.py", line 194, in print_versions_report
AttributeError: 'module' object has no attribute 'EX_OK'
```

**Comment by cachedout** [comment]
@UtahDave What's the status on this? Let me know if you want to sit down today and go over this if it's still an issue.

**Comment by UtahDave** [comment]
This has been fixed. @soodr, the next bugfix release will have this fix. If after upgrading you continue to see this happen, please comment here again and we'll reopen.

Thanks for the bug report!
