### ISSUE TITLE
salt-cloud fails for ec2 for query without params

### ISSUE THREAD

**Issue by An42Ma** [saltstack/salt#18315]
I am getting the following error when trying to create a new instance with salt-cloud (2014.7.0):

	Traceback (most recent call last):
	  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
		self.run()
	  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
		self._target(*self._args, **self._kwargs)
	  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1190, in create
		output = self.clouds[func](vm_)
	  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 2059, in create
		call='action'
	  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 2158, in create_attach_volumes
		value=delvols_on_destroy)
	  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 3020, in _toggle_delvol
		return query(requesturl=requesturl)
	  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 280, in query
		params_with_headers = params.copy()
	AttributeError: 'NoneType' object has no attribute 'copy'

A quick look at `_toggle_delvol` showed that `query` is called without the parameter `params` in `_toggle_delvol`'s return statement. Then, `params` is used in `query` without a check whether it is `None`.

**Comment by rallytime** [comment]
I can no longer reproduce this failure at the HEAD of the 2015.5 branch. I used the following simple test profile on ec2:
```
ec2-ubuntu-14:
  provider: ec2-config
  image: ami-98aa1cf0
  size: t1.micro
  sh_username: ec2-user
  volumes:
    - { size: 10, device: /dev/sdf }
```
Versions report:
```
# salt-cloud --versions
            Salt: 2015.5.1-97-g88a997e
          Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
          Jinja2: 2.7.3
        M2Crypto: 0.21.1
  msgpack-python: 0.4.4
    msgpack-pure: Not Installed
        pycrypto: 2.6.1
         libnacl: Not Installed
          PyYAML: 3.11
           ioflo: Not Installed
           PyZMQ: 14.0.1
            RAET: Not Installed
             ZMQ: 4.0.4
            Mako: 0.9.1
 Apache Libcloud: 0.17.0
```
Can anyone else confirm that this is fixed on the latest stable version of salt (2015.5.1)? Or are people still seeing issues here with more complicated setups?

**Comment by An42Ma** [comment]
I can no longer reproduce this failure either.

**Comment by techhat** [comment]
Sounds good, thanks guys!
