### ISSUE TITLE
Minion Service can't restart itself on Windows

### ISSUE THREAD

**Issue by highlyunavailable** [saltstack/salt#18395]
I'm using the latest Windows minion and if the salt minion restarts itself, it actually dies.

Windows:
```
OS Name:                   Microsoft Windows Web Server 2008 R2
OS Version:                6.1.7601 Service Pack 1 Build 7601
```
.\salt-minion.exe --versions-report (The traceback is part of the output)
```
           Salt: 2014.7.0
         Python: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]
         Jinja2: 2.7.1
       M2Crypto: 0.21.1
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.1.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "__main__.py", line 726, in <module>
  File "__main__.py", line 332, in bootstrap
  File "__main__.py", line 359, in chainload
  File "__main__.py", line 715, in _chainload
  File "__main__.py", line 128, in <module>
  File "__main__salt-minion__.py", line 17, in <module>
  File "salt/scripts.py", line 56, in salt_minion
  File "salt/__init__.py", line 262, in start
  File "salt/__init__.py", line 168, in prepare
  File "salt/utils/parsers.py", line 126, in parse_args
  File "salt/utils/parsers.py", line 194, in print_versions_report
AttributeError: 'module' object has no attribute 'EX_OK'
```

Salt minion log with INFO level:
```
2014-11-21 17:46:34,075 [salt.minion      ][INFO    ] Starting a new job with PID 3876
2014-11-21 17:46:34,075 [salt.minion      ][INFO    ] Returning information for job: 20141121234633700889
2014-11-21 17:46:34,480 [salt.fileclient  ][INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://salt/minion.sls'
2014-11-21 17:46:34,979 [salt.fileclient  ][INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://salt/package-map.jinja'
2014-11-21 17:46:34,995 [salt.state       ][INFO    ] Running state [C:\salt\conf\minion.d] at time 17:46:34.995000
2014-11-21 17:46:35,011 [salt.state       ][INFO    ] Executing state file.recurse for C:\salt\conf\minion.d
2014-11-21 17:46:35,369 [salt.fileclient  ][INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://salt/files/minion.d/_defaults.conf'
2014-11-21 17:46:35,432 [salt.state       ][INFO    ] {'C:\\salt\\conf\\minion.d\\_defaults.conf': {'diff': 'New file'}}
2014-11-21 17:46:35,447 [salt.state       ][INFO    ] Loading fresh modules for state activity
2014-11-21 17:46:35,993 [salt.state       ][INFO    ] Completed state [C:\salt\conf\minion.d] at time 17:46:35.993000
2014-11-21 17:46:35,993 [salt.state       ][INFO    ] Running state [salt-minion] at time 17:46:35.993000
2014-11-21 17:46:35,993 [salt.state       ][INFO    ] Executing state service.running for salt-minion
2014-11-21 17:46:35,993 [salt.loaded.int.module.cmdmod][INFO    ] Executing command 'where powershell' in directory 'C:\\Windows\\system32\\config\\systemprofile'
2014-11-21 17:46:36,087 [salt.loaded.int.module.cmdmod][INFO    ] Executing command 'Powershell "Get-WmiObject win32_service | where {$_.startmode -eq \\"Auto\\"} | select-object name"' in directory 'C:\\Windows\\system32\\config\\systemprofile'
2014-11-21 17:46:36,368 [salt.loaded.int.module.cmdmod][INFO    ] Executing command 'where powershell' in directory 'C:\\Windows\\system32\\config\\systemprofile'
2014-11-21 17:46:36,461 [salt.loaded.int.module.cmdmod][INFO    ] Executing command 'Powershell "Get-WmiObject win32_service | where {$_.startmode -ne \\"Auto\\"} | select-object name"' in directory 'C:\\Windows\\system32\\config\\systemprofile'
2014-11-21 17:46:36,773 [salt.loaded.int.module.cmdmod][INFO    ] Executing command 'sc query salt-minion' in directory 'C:\\Windows\\system32\\config\\systemprofile'
2014-11-21 17:46:36,789 [salt.loaded.int.module.cmdmod][INFO    ] Executing command 'where powershell' in directory 'C:\\Windows\\system32\\config\\systemprofile'
2014-11-21 17:46:36,867 [salt.loaded.int.module.cmdmod][INFO    ] Executing command 'Powershell "Get-WmiObject win32_service | where {$_.startmode -eq \\"Auto\\"} | select-object name"' in directory 'C:\\Windows\\system32\\config\\systemprofile'
2014-11-21 17:46:37,163 [salt.loaded.int.module.cmdmod][INFO    ] Executing command 'where powershell' in directory 'C:\\Windows\\system32\\config\\systemprofile'
2014-11-21 17:46:37,257 [salt.loaded.int.module.cmdmod][INFO    ] Executing command 'Powershell "Get-WmiObject win32_service | where {$_.startmode -ne \\"Auto\\"} | select-object name"' in directory 'C:\\Windows\\system32\\config\\systemprofile'
2014-11-21 17:46:37,569 [salt.loaded.int.module.cmdmod][INFO    ] Executing command 'where powershell' in directory 'C:\\Windows\\system32\\config\\systemprofile'
2014-11-21 17:46:37,647 [salt.loaded.int.module.cmdmod][INFO    ] Executing command 'Powershell "Get-WmiObject win32_service | where {$_.startmode -eq \\"Auto\\"} | select-object name"' in directory 'C:\\Windows\\system32\\config\\systemprofile'
2014-11-21 17:46:37,943 [salt.state       ][INFO    ] Service salt-minion is already enabled, and is in the desired state
2014-11-21 17:46:37,943 [salt.state       ][INFO    ] Completed state [salt-minion] at time 17:46:37.943000
2014-11-21 17:46:37,943 [salt.state       ][INFO    ] Running state [salt-minion] at time 17:46:37.943000
2014-11-21 17:46:37,943 [salt.state       ][INFO    ] Executing state service.mod_watch for salt-minion
2014-11-21 17:46:37,943 [salt.loaded.int.module.cmdmod][INFO    ] Executing command 'sc query salt-minion' in directory 'C:\\Windows\\system32\\config\\systemprofile'
2014-11-21 17:46:37,959 [salt.loaded.int.module.cmdmod][INFO    ] Executing command 'where powershell' in directory 'C:\\Windows\\system32\\config\\systemprofile'
2014-11-21 17:46:38,037 [salt.loaded.int.module.cmdmod][INFO    ] Executing command 'Powershell "Restart-Service salt-minion"' in directory 'C:\\Windows\\system32\\config\\systemprofile'
2014-11-21 17:46:39,082 [salt             ][WARNING ] Stopping the Salt Minion
2014-11-21 17:46:39,082 [salt             ][WARNING ] Exiting on Ctrl-c
2014-11-21 17:46:40,330 [salt.loaded.int.module.cmdmod][ERROR   ] Command 'Restart-Service salt-minion' failed with return code: 1
2014-11-21 17:46:40,330 [salt.loaded.int.module.cmdmod][ERROR   ] output: 
2014-11-21 17:46:40,330 [salt.state       ][ERROR   ] {'salt-minion': False}
2014-11-21 17:46:40,330 [salt.state       ][INFO    ] Completed state [salt-minion] at time 17:46:40.330000
```

This means that I can't have Salt restart the salt minion to apply changes to the salt minion config remotely on Windows minions. This used to work in 2014.1.11. I'm not sure why it no longer does, since the code is exactly the same between the versions.

**Comment by UtahDave** [comment]
these EX_OK problems have been fixed on the 2014.7 branch so I'm going to close this. 

This fix will be in the 2014.7.1 bugfix release. Please comment here if you encounter this issue after upgrading and we'll reopen.  Thanks for the bug report!
