### ISSUE TITLE
use salt-ssh to install the salt-minion for client server in batch

### ISSUE THREAD

**Issue by disylee** [saltstack/salt#18425]
backgroup: I trying to use salt-ssh to install the salt-minion for client server in batch.

```
[root@localhost epel]# tree -f
.
├── ./epel-release-6-8.noarch.rpm
└── ./salt_install.sls

0 directories, 2 files
[root@localhost salt]# ls
epel  roster  salt
[root@localhost salt]# cat roster
web1:
  host:  10.20.14.18
  user:  root
  passwd:  redhat
  port:  22
  timeout:  10
```

but test.ping   error below，first it can't found the host：
the I try this

```
[root@localhost salt]# salt-ssh '*' test.ping
test:
    ----------
    retcode:
        1
    stderr:
        Traceback (most recent call last):
          File "/tmp/.root_c87ee6__salt/salt-call", line 2, in <module>
            from salt.scripts import salt_call
          File "/tmp/.root_c87ee6__salt/salt/__init__.py", line 44, in <module>
            from salt.utils import migrations
          File "/tmp/.root_c87ee6__salt/salt/utils/__init__.py", line 102, in <module>
            import salt.payload
          File "/tmp/.root_c87ee6__salt/salt/payload.py", line 14, in <module>
            import salt.crypt
          File "/tmp/.root_c87ee6__salt/salt/crypt.py", line 32, in <module>
            import salt.minion
          File "/tmp/.root_c87ee6__salt/salt/minion.py", line 60, in <module>
            import salt.client
          File "/tmp/.root_c87ee6__salt/salt/client/__init__.py", line 38, in <module>
            import salt.utils.event
          File "/tmp/.root_c87ee6__salt/salt/utils/event.py", line 74, in <module>
            import salt.state
          File "/tmp/.root_c87ee6__salt/salt/state.py", line 29, in <module>
            import salt.pillar
          File "/tmp/.root_c87ee6__salt/salt/pillar/__init__.py", line 14, in <module>
            import salt.fileclient
          File "/tmp/.root_c87ee6__salt/salt/fileclient.py", line 13, in <module>
            import requests
          File "/tmp/.root_c87ee6__salt/requests/__init__.py", line 52, in <module>
            from . import utils
          File "/tmp/.root_c87ee6__salt/requests/utils.py", line 23, in <module>
            from .compat import parse_http_list as _parse_list_header
          File "/tmp/.root_c87ee6__salt/requests/compat.py", line 96, in <module>
            from ordereddict import OrderedDict
        ImportError: No module named ordereddict
    stdout:
```

Sadly，I try this command but return OK，like this

```
[root@localhost salt]# salt-ssh '*' -r "free -m"
test:
    ----------
    retcode:
        0
    stderr:

    stdout:
        root@10.20.14.18's password:
                     total       used       free     shared    buffers     cached
        Mem:           490        135        355          0         10         44
        -/+ buffers/cache:         80        410
        Swap:          991          0        991
```

this my epel_install.sls

```
  [root@localhost epel]# cat salt_install.sls
epel_install:
  file.managed:
    - name:  /tmp/epel-release-6-8.noarch.rpm
    - source: salt://epel/epel-release-6-8.noarch.rpm
    - user: root
    - group: root

  cmd.run:
    - name: rpm -ivh /tmp/epel-release-6-8.noarch.rpm
    - unless: test -f /etc/yum.repos.d/epel.repo
    - require:
     - file: epel_install   
  chche_yum:
    cmd.run:
      - name: yum makecache
      - require:
        - file: epel_install
  salt_install:
    pkg.installed:
      - name: salt-minion
      - require:
        - file: epel_install
```

but I try to excute it ，reward ERROR below

```
[root@localhost epel]# salt-ssh '*' state.sls epel_install.sls
test:
    ----------
    _caller_cachedir:
        /var/cache/salt/master
    _error:
        Failed to return clean data
    _ssh_version:
        5.3p1
    ext_pillar:
    file_roots:
        ----------
        base:
            - /srv/salt
    id:
        test
    pillar_roots:
        ----------
        base:
            - /srv/pillar
    stderr:
        Traceback (most recent call last):
          File "/tmp/.root_c87ee6__salt/salt-call", line 2, in <module>
            from salt.scripts import salt_call
          File "/tmp/.root_c87ee6__salt/salt/__init__.py", line 44, in <module>
            from salt.utils import migrations
          File "/tmp/.root_c87ee6__salt/salt/utils/__init__.py", line 102, in <module>
            import salt.payload
          File "/tmp/.root_c87ee6__salt/salt/payload.py", line 14, in <module>
            import salt.crypt
          File "/tmp/.root_c87ee6__salt/salt/crypt.py", line 32, in <module>
            import salt.minion
          File "/tmp/.root_c87ee6__salt/salt/minion.py", line 60, in <module>
            import salt.client
          File "/tmp/.root_c87ee6__salt/salt/client/__init__.py", line 38, in <module>
            import salt.utils.event
          File "/tmp/.root_c87ee6__salt/salt/utils/event.py", line 74, in <module>
            import salt.state
          File "/tmp/.root_c87ee6__salt/salt/state.py", line 29, in <module>
            import salt.pillar
          File "/tmp/.root_c87ee6__salt/salt/pillar/__init__.py", line 14, in <module>
            import salt.fileclient
          File "/tmp/.root_c87ee6__salt/salt/fileclient.py", line 13, in <module>
            import requests
          File "/tmp/.root_c87ee6__salt/requests/__init__.py", line 52, in <module>
            from . import utils
          File "/tmp/.root_c87ee6__salt/requests/utils.py", line 23, in <module>
            from .compat import parse_http_list as _parse_list_header
          File "/tmp/.root_c87ee6__salt/requests/compat.py", line 96, in <module>
            from ordereddict import OrderedDict
        ImportError: No module named ordereddict
    stdout:
```

isn't cause by python?

**Comment by Vye** [comment]
I'm encountering this issue on stock RHEL 6.4. I realize if I install the dependencies it will fix it, but salt is supposed to be copying ordereddict right? It is installed on the master. It would make bootstrapping systems via salt-ssh more straightforward.

```
    stderr:
        Traceback (most recent call last):
          File "/tmp/.saltssh_535b74__salt/salt-call", line 2, in <module>
            from salt.scripts import salt_call
          File "/tmp/.saltssh_535b74__salt/salt/__init__.py", line 44, in <module>
            from salt.utils import migrations
          File "/tmp/.saltssh_535b74__salt/salt/utils/__init__.py", line 102, in <module>
            import salt.payload
          File "/tmp/.saltssh_535b74__salt/salt/payload.py", line 14, in <module>
            import salt.crypt
          File "/tmp/.saltssh_535b74__salt/salt/crypt.py", line 32, in <module>
            import salt.minion
          File "/tmp/.saltssh_535b74__salt/salt/minion.py", line 60, in <module>
            import salt.client
          File "/tmp/.saltssh_535b74__salt/salt/client/__init__.py", line 38, in <module>
            import salt.utils.event
          File "/tmp/.saltssh_535b74__salt/salt/utils/event.py", line 74, in <module>
            import salt.state
          File "/tmp/.saltssh_535b74__salt/salt/state.py", line 29, in <module>
            import salt.pillar
          File "/tmp/.saltssh_535b74__salt/salt/pillar/__init__.py", line 14, in <module>
            import salt.fileclient
          File "/tmp/.saltssh_535b74__salt/salt/fileclient.py", line 13, in <module>
            import requests
          File "/tmp/.saltssh_535b74__salt/requests/__init__.py", line 52, in <module>
            from . import utils
          File "/tmp/.saltssh_535b74__salt/requests/utils.py", line 23, in <module>
            from .compat import parse_http_list as _parse_list_header
          File "/tmp/.saltssh_535b74__salt/requests/compat.py", line 96, in <module>
            from ordereddict import OrderedDict
        ImportError: No module named ordereddict
```

**Comment by PabloLemos** [comment]
Hi!I

I have  the same issue. I use redhat 6.5 could you tell me what dependencies i need to install?

Thnkas

**Comment by hirotoshibuya** [comment]
Same issue with salt-ssh 2014.7.1 (Helium) on CentOS 6.6 with via EPEL.  

I was using 2014.7.0 with this patch: https://github.com/saltstack/salt/pull/19321 
Then, when updated to 2014.7.1, that patch is included but it regressed with this issue.

**Comment by hirotoshibuya** [comment]
This issue can be worked around by installing "python-requests" package on the target.

**Comment by cragusa** [comment]
Hi,
I'm having the same problem, using salt-ssh through the python client throws the error

'stderr': 'Traceback (most recent call last):\n  File "/var/tmp/.root_5fe90b_salt/salt-call", line 15, in <module>\n    salt_call()\n  File "/var/tmp/.root_5fe90b_salt/py2/salt/scripts.py", line 346, in salt_call\n    import salt.cli.call\n  File "/var/tmp/.root_5fe90b_salt/py2/salt/cli/call.py", line 6, in <module>\n    from salt.utils import parsers\n  File "/var/tmp/.root_5fe90b_salt/py2/salt/utils/parsers.py", line 28, in <module>\n    import salt.config as config\n  File "/var/tmp/.root_5fe90b_salt/py2/salt/config/__init__.py", line 41, in <module>\n    import salt.utils.sdb\n  File "/var/tmp/.root_5fe90b_salt/py2/salt/utils/sdb.py", line 9, in <module>\n    import salt.loader\n  File "/var/tmp/.root_5fe90b_salt/py2/salt/loader.py", line 30, in <module>\n    import salt.utils.event\n  File "/var/tmp/.root_5fe90b_salt/py2/salt/utils/event.py", line 72, in <module>\n    import salt.payload\n  File "/var/tmp/.root_5fe90b_salt/py2/salt/payload.py", line 17, in <module>\n    import salt.crypt\n  File "/var/tmp/.root_5fe90b_salt/py2/salt/crypt.py", line 49, in <module>\n    import tornado.gen\n  File "/var/tmp/.root_5fe90b_salt/py2/tornado/gen.py", line 98, in <module>\n    from singledispatch import singledispatch  # backport\n  File "/var/tmp/.root_5fe90b_salt/py2/singledispatch.py", line 13, in <module>\n    from singledispatch_helpers import MappingProxyType, get_cache_token\n  File "/var/tmp/.root_5fe90b_salt/py2/singledispatch_helpers.py", line 19, in <module>\n    from ordereddict import OrderedDict\nImportError: No module named ordereddict',

These are my installed pkgs versions:
ordereddict (1.1)
requests (2.10.0)
salt-ssh (2016.3.3)

Any suggestion?

Thanks
