### ISSUE TITLE
State fails with cmd.run on Windows 

### ISSUE THREAD

**Issue by soodr** [saltstack/salt#18503]
C:\Users\Administrator>c:\salt\salt-call.exe --versions-report
```
           Salt: 2014.7.0
         Python: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]
         Jinja2: 2.7.1
       M2Crypto: 0.21.1
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.1.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "__main__.py", line 726, in <module>
  File "__main__.py", line 332, in bootstrap
  File "__main__.py", line 359, in chainload
  File "__main__.py", line 715, in _chainload
  File "__main__.py", line 128, in <module>
  File "__main__salt-call__.py", line 14, in <module>
  File "salt/scripts.py", line 122, in salt_call
  File "salt/cli/__init__.py", line 370, in run
  File "salt/utils/parsers.py", line 126, in parse_args
  File "salt/utils/parsers.py", line 194, in print_versions_report
AttributeError: 'module' object has no attribute 'EX_OK'
```
The state definition \:
```
run_database_bat:
        cmd.run:
          - name: 'D:\scripts\mssql_install\create_databases.bat'
          - cwd: 'D:\scripts\mssql_install'
          - shell: 'windows'
          - use_vt: True
```
Error log \:
```
2014-11-26 03:15:22,488 [salt.loaded.int.module.cmdmod][INFO    ] Executing command 
'D:\\scripts\\mssql_install\\create_databases.bat' in directory 'D:\\scripts\\mssql_install'
2014-11-26 03:15:22,498 [salt.state       ][ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "salt/state.py", line 1533, in call
  File "salt/states/cmd.py", line 715, in run
  File "salt/modules/cmdmod.py", line 867, in run_all
  File "salt/modules/cmdmod.py", line 456, in _run
UnboundLocalError: local variable 'proc' referenced before assignment
```

**Comment by UtahDave** [comment]
@soodr have you been able to try running your state without the `shell: 'windows'` and also `use_vt: True`?
use_vt isn't supported on Windows yet and `shell: 'windows'` is unneccesary.

**Comment by soodr** [comment]
@UtahDave  the error does not show any longer.

**Comment by UtahDave** [comment]
Thanks, @soodr! Please comment if this occurs again.

Since @markuskramerIgitt created another issue to track the encoding issue I'm going to close this issue.

Thanks again!
