### ISSUE TITLE
Windows: logging may unexpectedly fail if switching users on minion

### ISSUE THREAD

**Issue by Supermathie** [saltstack/salt#18624]
For Good Reasons I'm switching users in the middle of some modules/jobs - this causes them to fail depending on logging level:

```
The minion function caused an exception: Traceback (most recent call last):
  File "salt/minion.py", line 1019, in _thread_return
  File "c:\salt\var\cache\salt\minion\extmods\modules\localmagic.py", line 99, in run
    fire_master(cmd, 'ok')
  File "c:\salt\var\cache\salt\minion\extmods\modules\localmagic.py", line 63, in fire_master
    }, "fire_master")
  File "salt/utils/event.py", line 407, in fire_event
  File "logging/__init__.py", line 1137, in debug
  File "salt/log/setup.py", line 185, in _log
  File "logging/__init__.py", line 1268, in _log
  File "logging/__init__.py", line 1278, in handle
  File "logging/__init__.py", line 1318, in callHandlers
  File "logging/__init__.py", line 749, in handle
  File "logging/handlers.py", line 415, in emit
WindowsError: [Error 5] Access is denied: 'c:\\salt\\var\\log\\salt\\minion.debug'
```

If the log could be opened once and kept open, that would be nice. At the very least, it would be nice if it didn't unexpectedly abort the job.

**Comment by rickh563** [comment]
ZD-535

**Comment by basepi** [comment]
(That ZD ticket is actually unrelated to this original issue)

runas is implemented on the develop branch for windows, and will be included in the Boron release of salt next year. Does that solve your issue, @Supermathie?

**Comment by Supermathie** [comment]
I don't have actually time to test/verify/rework but it sounds good!

**Comment by basepi** [comment]
That's fine. I think I'm going to close this one, it sounds like if we had had proper runas support in the beginning, your original issue could have been avoided, correct? If that's not the case we can certainly re-open.
