### ISSUE TITLE
bug in deploy script running

### ISSUE THREAD

**Issue by dh-harald** [saltstack/salt#18649]
Hi,

I've got the following error message, if I deploy a new vm
Process Process-9:
```
Traceback (most recent call last):
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 232, in _bootstrap
    self.run()
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 88, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 1190, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/ec2.py", line 2023, in create
    ret = salt.utils.cloud.bootstrap(vm_, __opts__)
  File "/usr/lib/python2.6/site-packages/salt/utils/cloud.py", line 423, in bootstrap
    deployed = deploy_script(**deploy_kwargs)
  File "/usr/lib/python2.6/site-packages/salt/utils/cloud.py", line 1236, in deploy_script
    if root_cmd(deploy_command, tty, sudo, **kwargs) != 0:
  File "/usr/lib/python2.6/site-packages/salt/utils/cloud.py", line 1736, in root_cmd
    retcode = _exec_ssh_cmd(cmd, allow_failure=allow_failure, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/utils/cloud.py", line 1403, in _exec_ssh_cmd
    raise SaltCloudPasswordError(error_msg)
SaltCloudPasswordError: A wrong password has been issued while establishing ssh session
```
It occurs, when the deploy script's output contains "Password" word, for example my highstate:
```
[...]
-gitfs_passphrase: ''
-gitfs_password: ''
-gitfs_privkey: ''
[...]
```
Please fix it :)
(salt-cloud version 2014.7.0)

**Comment by rallytime** [comment]
@dh-harald Sorry I never responded here. If you'd still like to submit that patch, it would be most welcome!

**Comment by dh-harald** [comment]
Hi,

I've made a pull request:
https://github.com/saltstack/salt/pull/24825

**Comment by rallytime** [comment]
Thanks again @dh-harald! Since your fix was merged in, I am going to close this.
