### ISSUE TITLE
Salt 2014.7.0 Windows 7 salt-call.exe --versions-report fails with EX_OK What about Jenkins?

### ISSUE THREAD

**Issue by markuskramerIgitt** [saltstack/salt#18950]
On Windos 7 Enterprise 64bit

````
C:\salt>salt-call.exe --versions-report
           Salt: 2014.7.0
         Python: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]
         Jinja2: 2.7.1
       M2Crypto: 0.21.1
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.1.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "__main__.py", line 726, in <module>
  File "__main__.py", line 332, in bootstrap
  File "__main__.py", line 359, in chainload
  File "__main__.py", line 715, in _chainload
  File "__main__.py", line 128, in <module>
  File "__main__salt-call__.py", line 14, in <module>
  File "salt/scripts.py", line 122, in salt_call
  File "salt/cli/__init__.py", line 370, in run
  File "salt/utils/parsers.py", line 126, in parse_args
  File "salt/utils/parsers.py", line 194, in print_versions_report
AttributeError: 'module' object has no attribute 'EX_OK'
```

saltmaster is running, but also tried `C:\salt>salt-call.exe --local --return local --versions-report` with same result.

@soodr reported this 16 days ago https://github.com/saltstack/salt/issues/18503 and @UtahDave fixes the `EX_OK` problem with https://github.com/saltstack/salt/pull/18897

Why did salt-jenkins not found this? 
Is Jenkins not run on Windows? 
Does Jenkins not run `salt-call --versions-report`?

**Comment by rallytime** [comment]
Since the original bug has already been addressed, and adding windows tests to Jenkins is on our QA radar, I am going to close this bug out for now. Thanks!

**Comment by markuskramerIgitt** [comment]
Thank you, @rallytime

**Comment by rallytime** [comment]
No problem - Thanks!
