### ISSUE TITLE
AttributeError: 'module' object has no attribute 'strip_esc_sequence'

### ISSUE THREAD

**Issue by pwaller** [saltstack/salt#19214]
I just tried to run this across 6 minions:

```
salt '*' pkg.upgrade
```

But this happened:

```
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'module' object has no attribute 'strip_esc_sequence'
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 135, in salt_main
    def salt_run():
  File "/usr/lib/python2.7/dist-packages/salt/cli/__init__.py", line 140, in run
    if 'token' not in kwargs and self.options.eauth:
  File "/usr/lib/python2.7/dist-packages/salt/cli/__init__.py", line 155, in _output_ret
    if self.config['async']:
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 39, in display_output
    Print the passed data using the desired output
  File "/usr/lib/python2.7/dist-packages/salt/output/nested.py", line 123, in output
    return nest.display(ret, __opts__.get('nested_indent', 0), '', '')
  File "/usr/lib/python2.7/dist-packages/salt/output/nested.py", line 114, in display
    out = self.display(val, indent + 4, '', out)
  File "/usr/lib/python2.7/dist-packages/salt/output/nested.py", line 114, in display
    out = self.display(val, indent + 4, '', out)
  File "/usr/lib/python2.7/dist-packages/salt/output/nested.py", line 114, in display
    out = self.display(val, indent + 4, '', out)
  File "/usr/lib/python2.7/dist-packages/salt/output/nested.py", line 84, in display
    line = salt.output.strip_esc_sequence(line)
AttributeError: 'module' object has no attribute 'strip_esc_sequence'
```

I think it may have occurred because salt updated itself as part of the upgrade. I can't seem to immediately reproduce it but I thought it was worth documenting here in case others hit it (or if I hit it again).

**Comment by pwaller** [comment]
As far as I'm aware I haven't encountered this in a while. Tidying up my personal issues list, so closing this. Please create a new issue if you're still interested in tracking it.
