### ISSUE TITLE
State output containing non-ascii characters produces UnicodeEncodeError

### ISSUE THREAD

**Issue by rynemccall** [saltstack/salt#19338]
vagrant@salt-03:~$ salt --version
    salt 2015.2.0-119-g0452b43

    ❯❯❯ cat salt/test.sls
    echo -e "\xE2\x98\xA0":
      cmd.run

    vagrant@salt-03:~$ sudo salt-call state.sls test
    [INFO    ] Loading fresh modules for state activity
    [INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://test.sls'
    [INFO    ] Running state [echo -e "\xE2\x98\xA0"] at time 21:42:06.524973
    [INFO    ] Executing state cmd.run for echo -e "\xE2\x98\xA0"
    [INFO    ] Executing command 'echo -e "\\xE2\\x98\\xA0"' in directory '/home/vagrant'
    [ERROR   ] An exception occurred in this state: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1547, in call
        **cdata['kwargs'])
      File "/usr/lib/python2.7/dist-packages/salt/states/cmd.py", line 712, in run
        name, timeout=timeout, **cmd_kwargs
      File "/usr/lib/python2.7/dist-packages/salt/modules/cmdmod.py", line 885, in run_all
        log.log(lvl, 'stdout: {0}'.format(ret['stdout']))
      File "/usr/lib/python2.7/logging/__init__.py", line 1203, in log
        self._log(level, msg, args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 277, in _log
        self, level, msg, args, exc_info=exc_info, extra=extra
      File "/usr/lib/python2.7/logging/__init__.py", line 1257, in _log
        record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
      File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 304, in makeRecord
        exc_info, func)
      File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 161, in __init__
        end=TextFormat('reset')
    UnicodeEncodeError: 'ascii' codec can't encode character u'\u2620' in position 8: ordinal not in range(128)
    
    [INFO    ] Completed state [echo -e "\xE2\x98\xA0"] at time 21:42:06.537372
    local:
    ----------
              ID: echo -e "\xE2\x98\xA0"
        Function: cmd.run
          Result: False
         Comment: An exception occurred in this state: Traceback (most recent call last):
                    File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1547, in call
                      **cdata['kwargs'])
                    File "/usr/lib/python2.7/dist-packages/salt/states/cmd.py", line 712, in run
                      name, timeout=timeout, **cmd_kwargs
                    File "/usr/lib/python2.7/dist-packages/salt/modules/cmdmod.py", line 885, in run_all
                      log.log(lvl, 'stdout: {0}'.format(ret['stdout']))
                    File "/usr/lib/python2.7/logging/__init__.py", line 1203, in log
                      self._log(level, msg, args, **kwargs)
                    File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 277, in _log
                      self, level, msg, args, exc_info=exc_info, extra=extra
                    File "/usr/lib/python2.7/logging/__init__.py", line 1257, in _log
                      record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
                    File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 304, in makeRecord
                      exc_info, func)
                    File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 161, in __init__
                      end=TextFormat('reset')
                  UnicodeEncodeError: 'ascii' codec can't encode character u'\u2620' in position 8: ordinal not in range(128)
         Started: 21:42:06.524973
        Duration: 12.399 ms
         Changes:   
    
    Summary
    ------------
    Succeeded: 0
    Failed:    1
    ------------
    Total states run:     1

**Comment by Deshke** [comment]
got more or less the same error but with utf8

```bash
----------
          ID: apt-get autoremove -y
    Function: cmd.run
      Result: True
     Comment: Command "apt-get autoremove -y" run
     Started: 09:09:15.191062
    Duration: 5417.413 ms
     Changes:   
              ----------
              pid:
                  25118
              retcode:
                  0
              stderr:
                  
              stdout:
                  Reading package lists...
                  Building dependency tree...
                  Reading state information...
                  0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Summary
------------
Succeeded: 4 (changed=4)
Failed:    0
------------
Total states run:     4
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
UnicodeDecodeError: 'utf8' codec can't decode byte 0xda in position 61: invalid continuation byte
Traceback (most recent call last):
  File "/usr/local/bin/salt", line 9, in <module>
    load_entry_point('salt-ssh==2014.7.0', 'console_scripts', 'salt')()
  File "/usr/local/lib/python2.7/dist-packages/salt/scripts.py", line 240, in salt_main
    client.run()
  File "/usr/local/lib/python2.7/dist-packages/salt/cli/__init__.py", line 189, in run
    self._output_ret(ret_, out)
  File "/usr/local/lib/python2.7/dist-packages/salt/cli/__init__.py", line 243, in _output_ret
    salt.output.display_output(ret, out, self.config)
  File "/usr/local/lib/python2.7/dist-packages/salt/output/__init__.py", line 44, in display_output
    display_data = get_printout(out, opts)(data).rstrip()
  File "/usr/local/lib/python2.7/dist-packages/salt/output/highstate.py", line 74, in output
    return _format_host(host, hostdata)[0]
  File "/usr/local/lib/python2.7/dist-packages/salt/output/highstate.py", line 118, in _format_host
    schanged, ctext = _format_changes(ret['changes'])
  File "/usr/local/lib/python2.7/dist-packages/salt/output/highstate.py", line 340, in _format_changes
    __opts__)
  File "/usr/local/lib/python2.7/dist-packages/salt/output/__init__.py", line 121, in out_format
    return get_printout(out, opts)(data).rstrip()
  File "/usr/local/lib/python2.7/dist-packages/salt/output/nested.py", line 123, in output
    return nest.display(ret, __opts__.get('nested_indent', 0), '', '')
  File "/usr/local/lib/python2.7/dist-packages/salt/output/nested.py", line 114, in display
    out = self.display(val, indent + 4, '', out)
  File "/usr/local/lib/python2.7/dist-packages/salt/output/nested.py", line 89, in display
    prefix=prefix)
  File "/usr/local/lib/python2.7/dist-packages/salt/output/nested.py", line 58, in ustring
    indent, color, prefix, msg.decode(encoding), endc, suffix)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xda in position 61: invalid continuation byte
Traceback (most recent call last):
  File "/usr/local/bin/salt", line 9, in <module>
    load_entry_point('salt-ssh==2014.7.0', 'console_scripts', 'salt')()
  File "/usr/local/lib/python2.7/dist-packages/salt/scripts.py", line 240, in salt_main
    client.run()
  File "/usr/local/lib/python2.7/dist-packages/salt/cli/__init__.py", line 189, in run
    self._output_ret(ret_, out)
  File "/usr/local/lib/python2.7/dist-packages/salt/cli/__init__.py", line 243, in _output_ret
    salt.output.display_output(ret, out, self.config)
  File "/usr/local/lib/python2.7/dist-packages/salt/output/__init__.py", line 44, in display_output
    display_data = get_printout(out, opts)(data).rstrip()
  File "/usr/local/lib/python2.7/dist-packages/salt/output/highstate.py", line 74, in output
    return _format_host(host, hostdata)[0]
  File "/usr/local/lib/python2.7/dist-packages/salt/output/highstate.py", line 118, in _format_host
    schanged, ctext = _format_changes(ret['changes'])
  File "/usr/local/lib/python2.7/dist-packages/salt/output/highstate.py", line 340, in _format_changes
    __opts__)
  File "/usr/local/lib/python2.7/dist-packages/salt/output/__init__.py", line 121, in out_format
    return get_printout(out, opts)(data).rstrip()
  File "/usr/local/lib/python2.7/dist-packages/salt/output/nested.py", line 123, in output
    return nest.display(ret, __opts__.get('nested_indent', 0), '', '')
  File "/usr/local/lib/python2.7/dist-packages/salt/output/nested.py", line 114, in display
    out = self.display(val, indent + 4, '', out)
  File "/usr/local/lib/python2.7/dist-packages/salt/output/nested.py", line 89, in display
    prefix=prefix)
  File "/usr/local/lib/python2.7/dist-packages/salt/output/nested.py", line 58, in ustring
    indent, color, prefix, msg.decode(encoding), endc, suffix)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xda in position 61: invalid continuation byte

```

**Comment by jfindlay** [comment]
@rynemccall, thanks for the pull request, and using color logs, woohoo!

@Deshke, the code that is causing the errors identified in the stack trace you're showing I believe is a known issue for 2014.7.0, but has been fixed on the 2014.7 branch and will be fixed in 2014.7.1.  There was a function created to handle this issue on 2014.7 called [sdecode](https://github.com/saltstack/salt/blob/2014.7/salt/utils/__init__.py#L2475) and nested.py has been updated to use this new function.  Basically sdecode tries to decode the string using known user- and locale-set encoding, with UTF-8 and ascii as fallbacks.

**Comment by Deshke** [comment]
ah cool, thanks is there any time frame for 2014.7.1 in the ppa ?

**Comment by jfindlay** [comment]
I think that, provisionally, 2014.7.1 will be ready by the end of next week.  The packages take a few days after that point.
