### ISSUE TITLE
salt.states.sysctl fails if /etc/sysctl.d/99-salt.conf does not exist on CentOS7/RHEL7 and probably others

### ISSUE THREAD

**Issue by TJuberg** [saltstack/salt#19379]
On CentOS7, the state will fail unless you manually create 99-salt.conf as outlined below.

Should it perhaps be trying to use 99-sysctl.conf which is the CentOS7 default?
Even so, it's not fortunate for it to fail if the file is missing.

```
          ID: vm.swappiness
    Function: sysctl.present
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1533, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/states/sysctl.py", line 56, in present
                  configured = __salt__['sysctl.show'](config_file=True)
                File "/usr/lib/python2.7/site-packages/salt/modules/linux_sysctl.py", line 86, in show
                  for line in salt.utils.fopen(config_file_path):
                File "/usr/lib/python2.7/site-packages/salt/utils/__init__.py", line 1065, in fopen
                  fhandle = open(*args, **kwargs)
              IOError: [Errno 2] No such file or directory: '/etc/sysctl.d/99-salt.conf'
     Started: 08:26:27.292491
    Duration: 146.792 ms
     Changes:  
```

**Comment by rallytime** [comment]
Thanks for the report @TJuberg. Can you please post the output of `salt --versions-report`?

**Comment by TJuberg** [comment]
Apologies for the obvious obmission

Master
```
           Salt: 2014.7.0
         Python: 2.7.8 (default, Oct 18 2014, 12:50:18)
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.3.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: 1.0.0
```

Minion
```
           Salt: 2014.7.0
         Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.8.1

**Comment by rallytime** [comment]
No worries! Thanks for adding those.

**Comment by oldmantaiter** [comment]
This has already been fixed and merged (and backported I think), there is an open bugzilla ticket for the salt maintainer for Fedora/EPEL to update the version for EL7 to pull this in.

**Comment by twangboy** [comment]
https://github.com/saltstack/salt/pull/19927
