### ISSUE TITLE
Network bridging under ubuntu fails with KeyError

### ISSUE THREAD

**Issue by numkem** [saltstack/salt#19405]
Hello,

Getting a `KeyError` when trying to do a network bridging under Ubuntu 14.04 with latest release (`2014.7.0`)

This is my state file:
```
em1:
  network.managed:
    - enabled: True
    - type: eth
    - bridge: br0
    - proto: dhcp

br0:
  network.managed:
    - enabled: True
    - type: bridge
    - proto: dhcp
    - use:
      - network: em1
    - require:
      - network: em1
```

And the result:
```
          ID: em1
    Function: network.managed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1533, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/states/network.py", line 212, in managed
                  old = __salt__['ip.get_interface'](name)
                File "/usr/lib/python2.7/dist-packages/salt/modules/debian_ip.py", line 1636, in get_interface
                  adapters = _parse_interfaces()
                File "/usr/lib/python2.7/dist-packages/salt/modules/debian_ip.py", line 627, in _parse_interfaces
                  if 'inet' in adapters[iface_name]['data']:
              KeyError: 'data'
     Started: 20:33:49.986165
    Duration: 1.218 ms
     Changes:
```

Thanks!

**Comment by garethgreenaway** [comment]
Not related to error you're seeing but if you're managing a bridged interface on a Debian / Ubuntu system you need to include the ports argument.  It works slightly different than it does on a Red Hat system.

**Comment by rallytime** [comment]
Thanks for the report @numkem. Looks like @garethgreenaway is looking into it. Thanks Gareth!

**Comment by MrMarvin** [comment]
I have this error as well for every state that uses `modules/debian_ip.py#_parse_interfaces()` in salt 2014.7.2.
```
marfri@lxc1-hw1:~$ sudo salt-call ip.get_interface eth0
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
KeyError: 'data'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/pymodules/python2.7/salt/scripts.py", line 123, in salt_call
    client.run()
  File "/usr/lib/pymodules/python2.7/salt/cli/__init__.py", line 424, in run
    caller.run()
  File "/usr/lib/pymodules/python2.7/salt/cli/caller.py", line 225, in run
    ret = self.call()
  File "/usr/lib/pymodules/python2.7/salt/cli/caller.py", line 129, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/pymodules/python2.7/salt/modules/debian_ip.py", line 1644, in get_interface
    adapters = _parse_interfaces()
  File "/usr/lib/pymodules/python2.7/salt/modules/debian_ip.py", line 627, in _parse_interfaces
    if 'inet' in adapters[iface_name]['data']:
KeyError: 'data'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/pymodules/python2.7/salt/scripts.py", line 123, in salt_call
    client.run()
  File "/usr/lib/pymodules/python2.7/salt/cli/__init__.py", line 424, in run
    caller.run()
  File "/usr/lib/pymodules/python2.7/salt/cli/caller.py", line 225, in run
    ret = self.call()
  File "/usr/lib/pymodules/python2.7/salt/cli/caller.py", line 129, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/pymodules/python2.7/salt/modules/debian_ip.py", line 1644, in get_interface
    adapters = _parse_interfaces()
  File "/usr/lib/pymodules/python2.7/salt/modules/debian_ip.py", line 627, in _parse_interfaces
    if 'inet' in adapters[iface_name]['data']:
KeyError: 'data'
```

This function is only used in multiple places in debian_ip.py:
* ../salt/salt/modules/debian_ip.py:514:def _parse_interfaces(interface_files=None):
* ../salt/salt/modules/debian_ip.py:1402:    adapters = _parse_interfaces() - _write_file_ifaces
* ../salt/salt/modules/debian_ip.py:1442:    adapters = _parse_interfaces() - _write_file_ppp_ifaces
* ../salt/salt/modules/debian_ip.py:1644:    adapters = _parse_interfaces() - get_interface

**Comment by MrMarvin** [comment]
Okay, here it is.
```
    if interface_files is None:
-        interface_files = []
+        interface_files = ['/etc/network/interfaces']
        # Add this later.
        # if os.path.exists('/etc/network/interfaces.d/'):
        #    interface_files += os.listdir('/etc/network/interfaces.d/')
```

The function is called without any argument in all cases so this default value should be here. I'm not sure if this works for all Debianesque distributions / versions though. I'll check and open a MR into 2014.7.0 later today.

**Comment by MrMarvin** [comment]
Actually it is not as easy... On another Ubuntu machine the module works as expected. The previously mentioned lines are not relevant as it seems as there is a default value added later on
```
        if os.path.isfile(_DEB_NETWORK_FILE):
            interface_files.insert(0, _DEB_NETWORK_FILE)
```

**Comment by garethgreenaway** [comment]
Does the /etc/network/interfaces file exist?  If so, what are the contents?

**Comment by MrMarvin** [comment]
> Does the /etc/network/interfaces file exist? If so, what are the contents?
Yes is does. The problem I isolated so far is in following block:
```
auto br0.1071
  iface br0.1071 inet manual
  vlan-raw-device br0
```
The line starting with "auto" is correctly parsed, the leading spaces at the "iface" line are the problem. I have no idea how they ended up in there.

Also I currently have a MR in the making. I'll link it to this issue.

**Comment by garethgreenaway** [comment]
:thumbsup:

**Comment by basepi** [comment]
Looks like this was fixed. Thanks everyone!
