### ISSUE TITLE
Exception in pkgrepo

### ISSUE THREAD

**Issue by thedrow** [saltstack/salt#19452]
```
An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1533, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/states/pkg.py", line 1093, in latest
                  cur = __salt__['pkg.version'](*desired_pkgs, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/aptpkg.py", line 300, in version
                  return __salt__['pkg_resource.version'](*names, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/pkg_resource.py", line 162, in version
                  pkgs = __salt__['pkg.list_pkgs'](versions_as_list=True, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/aptpkg.py", line 921, in list_pkgs
                  virtpkgs_all = _get_virtual()
                File "/usr/lib/python2.7/dist-packages/salt/modules/aptpkg.py", line 158, in _get_virtual
                  apt_cache = apt.cache.Cache()
                File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 107, in __init__
                  self.open(progress)
                File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 155, in open
                  self._list.read_main_list()
              SystemError: E:Type 'http://apt.postgresql.org/pub/repos/apt' is not known on line 63 in source list /etc/apt/sources.list
```

State:

```
postgresql-repo:
  pkgrepo.managed:
    - name: deb http://apt.postgresql.org/pub/repos/apt/ utopic-pgdg main
    - key_url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
```

**Comment by thedrow** [comment]
The exception occured while running the pkg state and was caused due to a misconfiguration of pkgrepo.managed.
I had:
```
postgresql-repo:
  pkgrepo.managed:
    - name: http://apt.postgresql.org/pub/repos/apt/ utopic-pgdg main
    - key_url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
```
at some point.

I think that pkgrepo.managed should prevent from entering invalid values and pkg.installed should catch that exception and raise a proper error.

**Comment by jfindlay** [comment]
@thedrow, thanks for reporting this.  A misconfiguration should definitely result in an unhandled exception.

**Comment by thedrow** [comment]
Can anyone verify if this is still an issue? I don't think it should be closed if it is.
