### ISSUE TITLE
Cannot instantiate a new Caller() instance using a file system path to the minion config file

### ISSUE THREAD

**Issue by nmadhok** [saltstack/salt#19674]
```
root@nitin-salt-develop:~$ python
Python 2.6.6 (r266:84292, Nov 21 2013, 10:50:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import salt.client
>>> caller = salt.client.Caller('/etc/salt/minion')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/salt/client/__init__.py", line 1560, in __init__
    self.sminion = salt.minion.SMinion(self.opts)
AttributeError: 'module' object has no attribute 'minion'
```

**Comment by nmadhok** [comment]
``import salt.minion`` needs to be present in the file ``salt/client/__init__.py``
