### ISSUE TITLE
Salt on Raet on Windows

### ISSUE THREAD

**Issue by SmithSamuelM** [saltstack/salt#19769]
Salt with Raet Transport basically works on windows but there are some issues that need to be resolved.

**Comment by SmithSamuelM** [comment]
The main remaining issue is that we need support for windows remote command execution.
The current nix executor behavior uses multi-process.

**Comment by UtahDave** [comment]
Have we tried it on Windows with multi process?

**Comment by andrejohansson** [comment]
How do I run it on windows, is there some pre-built installer which includes the libs? I have transport: raet in my minion config. I've opened udp on 4505,4506. I've installed the missing libs via pip and manually and I get the following outputs:

```
c:\salt>salt-call --versions-report
           Salt: 2014.7.1
         Python: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD6
4)]
         Jinja2: 2.7.1
       M2Crypto: 0.21.1
 msgpack-python: 0.4.2
   msgpack-pure: 0.1.3
       pycrypto: 2.6
        libnacl: 1.4.0
         PyYAML: 3.11
          ioflo: 1.1.5
          PyZMQ: 14.1.1
           RAET: 0.4.6
            ZMQ: 4.0.4
           Mako: 1.0.1
```

But when I start it I get:
```
c:\salt>salt-minion -l debug
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[INFO    ] Setting up the Salt Minion "dev-eu-minion"
[DEBUG   ] Created pidfile: c:\salt\var\run\salt-minion.pid
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Mako not available
[CRITICAL] Could not deserialize msgpack message: In an attempt to keep Salt run
ning, returning an empty dict.This often happens when trying to read a file not
in binary mode.Please open an issue and include the following error: Data is not
 enough.
[DEBUG   ] schedule.clean_proc_dir: checking job {} for process existence
[CRITICAL] Could not deserialize msgpack message: In an attempt to keep Salt run
ning, returning an empty dict.This often happens when trying to read a file not
in binary mode.Please open an issue and include the following error: Data is not
 enough.
[DEBUG   ] schedule.clean_proc_dir: checking job {} for process existence
[CRITICAL] Could not deserialize msgpack message: In an attempt to keep Salt run
ning, returning an empty dict.This often happens when trying to read a file not
in binary mode.Please open an issue and include the following error: Data is not
 enough.
[DEBUG   ] schedule.clean_proc_dir: checking job {} for process existence
[CRITICAL] Could not deserialize msgpack message: In an attempt to keep Salt run
ning, returning an empty dict.This often happens when trying to read a file not
in binary mode.Please open an issue and include the following error: Data is not
 enough.
[DEBUG   ] schedule.clean_proc_dir: checking job {} for process existence
[CRITICAL] Could not deserialize msgpack message: In an attempt to keep Salt run
ning, returning an empty dict.This often happens when trying to read a file not
in binary mode.Please open an issue and include the following error: Data is not
 enough.
[DEBUG   ] schedule.clean_proc_dir: checking job {} for process existence
[CRITICAL] Could not deserialize msgpack message: In an attempt to keep Salt run
ning, returning an empty dict.This often happens when trying to read a file not
in binary mode.Please open an issue and include the following error: Data is not
 enough.
[DEBUG   ] schedule.clean_proc_dir: checking job {} for process existence
[CRITICAL] Could not deserialize msgpack message: In an attempt to keep Salt run
ning, returning an empty dict.This often happens when trying to read a file not
in binary mode.Please open an issue and include the following error: Data is not
 enough.
[DEBUG   ] schedule.clean_proc_dir: checking job {} for process existence
[CRITICAL] Could not deserialize msgpack message: In an attempt to keep Salt run
ning, returning an empty dict.This often happens when trying to read a file not
in binary mode.Please open an issue and include the following error: Data is not
 enough.
[DEBUG   ] schedule.clean_proc_dir: checking job {} for process existence
[CRITICAL] Could not deserialize msgpack message: In an attempt to keep Salt run
ning, returning an empty dict.This often happens when trying to read a file not
in binary mode.Please open an issue and include the following error: Data is not
 enough.
[DEBUG   ] schedule.clean_proc_dir: checking job {} for process existence
[CRITICAL] Could not deserialize msgpack message: In an attempt to keep Salt run
ning, returning an empty dict.This often happens when trying to read a file not
in binary mode.Please open an issue and include the following error: Data is not
 enough.
[DEBUG   ] schedule.clean_proc_dir: checking job {} for process existence
[CRITICAL] Could not deserialize msgpack message: In an attempt to keep Salt run
ning, returning an empty dict.This often happens when trying to read a file not
in binary mode.Please open an issue and include the following error: Data is not
 enough.
[DEBUG   ] schedule.clean_proc_dir: checking job {} for process existence
[ERROR   ] An un-handled exception was caught by salt's global exception handler
:
StackError: StackError: Stack 'event00828caad818da3fda': Failed opening server a
t 'c:\salt\var\run\salt\minion\dev-eu-minion.event00828caad818da3fda.uxd'
.

Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "__main__.py", line 726, in <module>
  File "__main__.py", line 332, in bootstrap
  File "__main__.py", line 359, in chainload
  File "__main__.py", line 715, in _chainload
  File "__main__.py", line 128, in <module>
  File "__main__salt-minion__.py", line 17, in <module>
  File "salt/scripts.py", line 57, in salt_minion
  File "salt/__init__.py", line 264, in start
  File "salt/daemons/flo/__init__.py", line 137, in tune_in
  File "C:\Python27\lib\site-packages\ioflo\app\run.py", line 120, in run
    skedder.run()
  File "C:\Python27\lib\site-packages\ioflo\base\skedding.py", line 271, in run
    status = tasker.runner.send(tasker.desire)
  File "C:\Python27\lib\site-packages\ioflo\base\framing.py", line 611, in makeR
unner
    self.enterAll() #activates, resets .done state also .desire may change here
  File "C:\Python27\lib\site-packages\ioflo\base\framing.py", line 392, in enter
All
    self.enter(self.actives)
  File "C:\Python27\lib\site-packages\ioflo\base\framing.py", line 404, in enter

    frame.enter()
  File "C:\Python27\lib\site-packages\ioflo\base\framing.py", line 1211, in ente
r
    act() #call entryAction
  File "C:\Python27\lib\site-packages\ioflo\base\acting.py", line 98, in __call_
_
    return (self.actor(**self.parms))
  File "C:\Python27\lib\site-packages\ioflo\base\acting.py", line 460, in __call
__
    return self.action(**kwa)
  File "salt/daemons/flo/core.py", line 157, in action
  File "salt/daemons/salting.py", line 66, in __init__
  File "salt/key.py", line 835, in __init__
  File "salt/key.py", line 437, in __init__
  File "salt/utils/event.py", line 118, in get_event
  File "salt/utils/raetevent.py", line 41, in __init__
  File "salt/utils/raetevent.py", line 79, in __prep_stack
  File "C:\Python27\lib\site-packages\raet\lane\stacking.py", line 73, in __init
__
    **kwa)
  File "C:\Python27\lib\site-packages\raet\stacking.py", line 92, in __init__
    " '{1}'\n".format(self.name, self.server.ha))
StackError: StackError: Stack 'event00828caad818da3fda': Failed opening server a
t 'c:\salt\var\run\salt\minion\dev-eu-minion.event00828caad818da3fda.uxd'
.
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "__main__.py", line 726, in <module>
  File "__main__.py", line 332, in bootstrap
  File "__main__.py", line 359, in chainload
  File "__main__.py", line 715, in _chainload
  File "__main__.py", line 128, in <module>
  File "__main__salt-minion__.py", line 17, in <module>
  File "salt/scripts.py", line 57, in salt_minion
  File "salt/__init__.py", line 264, in start
  File "salt/daemons/flo/__init__.py", line 137, in tune_in
  File "C:\Python27\lib\site-packages\ioflo\app\run.py", line 120, in run
    skedder.run()
  File "C:\Python27\lib\site-packages\ioflo\base\skedding.py", line 271, in run
    status = tasker.runner.send(tasker.desire)
  File "C:\Python27\lib\site-packages\ioflo\base\framing.py", line 611, in makeR
unner
    self.enterAll() #activates, resets .done state also .desire may change here
  File "C:\Python27\lib\site-packages\ioflo\base\framing.py", line 392, in enter
All
    self.enter(self.actives)
  File "C:\Python27\lib\site-packages\ioflo\base\framing.py", line 404, in enter

    frame.enter()
  File "C:\Python27\lib\site-packages\ioflo\base\framing.py", line 1211, in ente
r
    act() #call entryAction
  File "C:\Python27\lib\site-packages\ioflo\base\acting.py", line 98, in __call_
_
    return (self.actor(**self.parms))
  File "C:\Python27\lib\site-packages\ioflo\base\acting.py", line 460, in __call
__
    return self.action(**kwa)
  File "salt/daemons/flo/core.py", line 157, in action
  File "salt/daemons/salting.py", line 66, in __init__
  File "salt/key.py", line 835, in __init__
  File "salt/key.py", line 437, in __init__
  File "salt/utils/event.py", line 118, in get_event
  File "salt/utils/raetevent.py", line 41, in __init__
  File "salt/utils/raetevent.py", line 79, in __prep_stack
  File "C:\Python27\lib\site-packages\raet\lane\stacking.py", line 73, in __init
__
    **kwa)
  File "C:\Python27\lib\site-packages\raet\stacking.py", line 92, in __init__
    " '{1}'\n".format(self.name, self.server.ha))
raet.raeting.StackError: StackError: Stack 'event00828caad818da3fda': Failed ope
ning server at 'c:\salt\var\run\salt\minion\dev-eu-minion.event00828caad818da3fd
a.uxd'
```
