### ISSUE TITLE
disk.blkid stack trace on freebsd

### ISSUE THREAD

**Issue by kim0** [saltstack/salt#19795]
What about a testing framework that runs all modules on all supported OSes and ensure no call results in a crash :)

```
# salt-call disk.blkid

[INFO    ] Executing command '/sbin/zfs help || :' in directory '/root'
[INFO    ] Executing command 'blkid' in directory '/root'
[ERROR   ] Command 'blkid' failed with return code: 127
[ERROR   ] stderr: /usr/local/bin/bash: blkid: command not found
[ERROR   ] retcode: 127
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/local/bin/salt-call", line 9, in <module>
    load_entry_point('salt==2014.7.0', 'console_scripts', 'salt-call')()
  File "/usr/local/lib/python2.7/site-packages/salt/scripts.py", line 122, in salt_call
    client.run()
  File "/usr/local/lib/python2.7/site-packages/salt/cli/__init__.py", line 419, in run
    caller.run()
  File "/usr/local/lib/python2.7/site-packages/salt/cli/caller.py", line 225, in run
    ret = self.call()
  File "/usr/local/lib/python2.7/site-packages/salt/cli/caller.py", line 129, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/salt/modules/disk.py", line 216, in blkid
    device = comps[0][:-1]
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/local/bin/salt-call", line 9, in <module>
    load_entry_point('salt==2014.7.0', 'console_scripts', 'salt-call')()
  File "/usr/local/lib/python2.7/site-packages/salt/scripts.py", line 122, in salt_call
    client.run()
  File "/usr/local/lib/python2.7/site-packages/salt/cli/__init__.py", line 419, in run
    caller.run()
  File "/usr/local/lib/python2.7/site-packages/salt/cli/caller.py", line 225, in run
    ret = self.call()
  File "/usr/local/lib/python2.7/site-packages/salt/cli/caller.py", line 129, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/salt/modules/disk.py", line 216, in blkid
    device = comps[0][:-1]
IndexError: list index out of range
```

**Comment by rodrigc** [comment]
@cedwards can you look at this?

**Comment by jfindlay** [comment]
@kim0 thanks for reporting this.

**Comment by rodrigc** [comment]
@kim0 reported this on my behalf.
blkid is a Linux-specific utility which is part of the util-linux package.

Is there a convention in Salstack to check for the presence of a command-line utility, and
then cleanly error out if that utility is not there?

**Comment by jfindlay** [comment]
There is a mechanism for not loading an execution module depending on whether the utilities used by the module are available on the system but this only works for the whole module.  I think with the abscence of such a mechanism for now, the right thing to do is probably error gracefully on disk.blkid if blkid is unavailable.

**Comment by rodrigc** [comment]
I built my own version of Saltstack from git.

After the fix in 192ccc73736a3f84c5852359c9bd6844a485e71b  If I do the following on FreeBSD:

I get:

    myhostname:
        Command required for 'disk.blkid' not found: The 'blkid' binary was not found in $PATH.

Looks good!

**Comment by kim0** [comment]
I guess this should be closed now

**Comment by jfindlay** [comment]
Thanks @rodrigc and @kim0 for the FreeBSD work.

**Comment by rodrigc** [comment]
@kim0 did all the work.  I just was a spectator to his awesome work!

**Comment by rodrigc** [comment]
@kim0 did all the work.  I just was a spectator to his awesome work!

**Comment by rodrigc** [comment]
@kim0 did all the work.  I just was a spectator to his awesome work!

**Comment by rodrigc** [comment]
@kim0 did all the work.  I just was a spectator to his awesome work!

**Comment by rodrigc** [comment]
@kim0 did all the work.  I just was a spectator to his awesome work!
