### ISSUE TITLE
salt minion on Windows stopped working after master upgrade

### ISSUE THREAD

**Issue by ksalman** [saltstack/salt#19854]
I upgraded salt master to 2014.7.0 and all the Windows minions (version 2014.1.1) stopped working. I get this traceback when I try to do anything on the minion

```
c:\salt>salt-call.exe state.highstate -l debug
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[INFO    ] Using cached minion ID from c:\salt\conf\minion_id: minion1
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Grains cache file does not exist.
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'Loader' object has no attribute 'state'
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "__main__.py", line 726, in <module>
  File "__main__.py", line 332, in bootstrap
  File "__main__.py", line 359, in chainload
  File "__main__.py", line 715, in _chainload
  File "__main__.py", line 128, in <module>
  File "__main__salt-call__.py", line 14, in <module>
  File "salt/scripts.py", line 82, in salt_call
  File "salt/cli/__init__.py", line 304, in run
  File "salt/cli/caller.py", line 47, in __init__
  File "salt/minion.py", line 247, in __init__
  File "salt/loader.py", line 320, in grains
  File "salt/loader.py", line 1052, in gen_grains
AttributeError: 'Loader' object has no attribute 'state'
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "__main__.py", line 726, in <module>
  File "__main__.py", line 332, in bootstrap
  File "__main__.py", line 359, in chainload
  File "__main__.py", line 715, in _chainload
  File "__main__.py", line 128, in <module>
  File "__main__salt-call__.py", line 14, in <module>
  File "salt/scripts.py", line 82, in salt_call
  File "salt/cli/__init__.py", line 304, in run
  File "salt/cli/caller.py", line 47, in __init__
  File "salt/minion.py", line 247, in __init__
  File "salt/loader.py", line 320, in grains
  File "salt/loader.py", line 1052, in gen_grains
AttributeError: 'Loader' object has no attribute 'state'
```

salt-minion versions on Windows

```
           Salt: 2014.1.1
         Python: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]
         Jinja2: 2.7.1
       M2Crypto: 0.21.1
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6
         PyYAML: 3.10
          PyZMQ: 14.1.1
            ZMQ: 4.0.4
```

salt-master versions on Linux

```
           Salt: 2014.7.0
         Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 13.1.0
           RAET: Not Installed
            ZMQ: 3.2.3
           Mako: 0.7.0
```

**Comment by ksalman** [comment]
This appears to be because I added grains_cache to the Windows minions.
```
grains_cache: True
grains_cache_expiration: 86400
```
When I remove those lines from the minion config, it starts working. The Windows minion version is 2014.1.1 which does support those grains so I don't know why they are screwing with the minion.

**Comment by ksalman** [comment]
Though this seems obvious but as another data point I tried leaving those lines in there but setting it to False and the minion still works.
```
grains_cache: False
grains_cache_expiration: 86400
```

**Comment by ssgward** [comment]
Thanks for the report and the troubleshooting steps.
