### ISSUE TITLE
state sysctl.present does not create the /etc/sysctl.d/99-salt.conf on a systemd using system

### ISSUE THREAD

**Issue by bigg01** [saltstack/salt#19870]
Hi 

The state sysctl.present does not create the /etc/sysctl.d/99-salt.conf on a systemd using system.

After touching the file it works!

Tested on RHEL6 and SLES12.

```
  ID: default_sysctl_net.ipv4.conf.default.rp_filter
    Function: sysctl.present
        Name: net.ipv4.conf.default.rp_filter
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1533, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/states/sysctl.py", line 56, in present
                  configured = __salt__['sysctl.show'](config_file=True)
                File "/usr/lib/python2.7/site-packages/salt/modules/linux_sysctl.py", line 86, in show
                  for line in salt.utils.fopen(config_file_path):
                File "/usr/lib/python2.7/site-packages/salt/utils/__init__.py", line 1065, in fopen
                  fhandle = open(*args, **kwargs)
              IOError: [Errno 2] No such file or directory: '/etc/sysctl.d/99-salt.conf'
     Started: 18:06:03.232389
    Duration: 158.434 ms

```

```
salt-call --versions-report
           Salt: 2014.7.0
         Python: 2.7.5 (default, Feb 11 2014, 07:46:25)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed
```

**Comment by bigg01** [comment]
I think the problem is because state usage of show. 
If sysctl.present is called in state it triggers first sysctl.show from the module and that is attempting to read the none existing file /etc/sysctl.d/99-salt.conf.

**Comment by bigg01** [comment]
State
```
def present(name, value, config=None):
    '''
    Ensure that the named sysctl value is set in memory and persisted to the
    named configuration file. The default sysctl configuration file is
    /etc/sysctl.conf

    name
        The name of the sysctl value to edit

    value
        The sysctl value to apply

    config
        The location of the sysctl configuration file. If not specified, the
        proper location will be detected based on platform.
    '''
    ret = {'name': name,
           'result': True,
           'changes': {},
           'comment': ''}

    if config is None:
        # Certain linux systems will ignore /etc/sysctl.conf, get the right
        # default configuration file.
        if 'sysctl.default_config' in __salt__:
            config = __salt__['sysctl.default_config']()
        else:
            config = '/etc/sysctl.conf'

    current = __salt__['sysctl.show']() <===============================
    configured = __salt__['sysctl.show'](config_file=True)

```

module:

```
def show(config_file=False):
    '''
    Return a list of sysctl parameters for this minion

    config: Pull the data from the system configuration file
        instead of the live data.

    CLI Example:

    .. code-block:: bash

        salt '*' sysctl.show
    '''
    ret = {}
    if config_file:
        config_file_path = default_config()
        try:
            for line in salt.utils.fopen(config_file_path): <=============================
                if not line.startswith('#') and '=' in line:
                    # search if we have some '=' instead of ' = ' separators
                    SPLIT = ' = '
                    if SPLIT not in line:
                        SPLIT = SPLIT.strip()
                    key, value = line.split(SPLIT, 1)
                    key = key.strip()
                    value = value.lstrip()
                    ret[key] = value
        except OSError:
            log.error('Could not open sysctl file')
            return None

```

**Comment by bigg01** [comment]
this issue is allready place #19379

**Comment by jfindlay** [comment]
@bigg01, thanks for reporting this.
