### ISSUE TITLE
docker.pull is failing with insecure_registry=True

### ISSUE THREAD

**Issue by rbjorklin** [saltstack/salt#20050]
This might be related to: #18673

    salt-call docker.pull docker-registry.home.loc:5000 /test:latest insecure_registry=True
    The following keyword arguments are not valid: {'insecure_registry': True}

And without the insecure_registry flag:

    [INFO    ] Starting new HTTPS connection (1): docker-registry.home.loc
    [ERROR   ] An un-handled exception was caught by salt's global exception handler:
    DockerException: HTTPS endpoint unresponsive and insecure mode isn't enabled.
    Traceback (most recent call last):
      File "/usr/bin/salt-call", line 11, in <module>
        salt_call()
      File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 122, in salt_call
        client.run()
      File "/usr/lib/python2.7/dist-packages/salt/cli/__init__.py", line 419, in run
        caller.run()
      File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 225, in run
        ret = self.call()
      File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 129, in call
        ret['return'] = func(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/dockerio.py", line 1591, in pull
        client = _get_client()
      File "/usr/lib/python2.7/dist-packages/salt/modules/dockerio.py", line 284, in _get_client
        email=creds.get('email'), registry=registry)
      File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 739, in login
        if registry else auth.INDEX_URL
      File "/usr/local/lib/python2.7/dist-packages/docker/auth/auth.py", line 46, in expand_registry_url
        "HTTPS endpoint unresponsive and insecure mode isn't enabled."
    DockerException: HTTPS endpoint unresponsive and insecure mode isn't enabled.
    Traceback (most recent call last):
      File "/usr/bin/salt-call", line 11, in <module>
        salt_call()
      File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 122, in salt_call
        client.run()
      File "/usr/lib/python2.7/dist-packages/salt/cli/__init__.py", line 419, in run
        caller.run()
      File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 225, in run
        ret = self.call()
      File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 129, in call
        ret['return'] = func(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/dockerio.py", line 1591, in pull
        client = _get_client()
      File "/usr/lib/python2.7/dist-packages/salt/modules/dockerio.py", line 284, in _get_client
        email=creds.get('email'), registry=registry)
      File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 739, in login
        if registry else auth.INDEX_URL
      File "/usr/local/lib/python2.7/dist-packages/docker/auth/auth.py", line 46, in expand_registry_url
        "HTTPS endpoint unresponsive and insecure mode isn't enabled."
    docker.errors.DockerException: HTTPS endpoint unresponsive and insecure mode isn't enabled.

**Comment by jfindlay** [comment]
I'm assuming you're running on the 2015.2 branch or the develop branch as `insecure_registry` is not an arg in `pull` on 2014.7.  Also, please post the output of:

```
salt-call -l debug docker.pull docker-registry.home.loc:5000 /test:latest insecure_registry=True
```

Thanks.

**Comment by rbjorklin** [comment]
I'm running 2014.7.0 and I can see that insecure_registry is indeed a parameter in 2015.2. Sorry about that. This can most likely be closed.

**Comment by jfindlay** [comment]
When you have a chance to test 2015.2, feel tree to close this issue or report that it still doesn't work at that time, thanks.
