### ISSUE TITLE
minion key is rejected when minion is restarted and state.highstate is called

### ISSUE THREAD

**Issue by dsumsky** [saltstack/salt#20055]
We have implemented a specific procedure for bootstrapping salt minions on AWS/EC2 cloud platform. It seems that  salt minion key may be rejected by master under some rare circumstances. The issue is confirmed on CentOS6.5 x86_64 with salt minion of versions 2014.1.10 and 2014.1.13 where salt master is of version 2014.1.13. Salt packages are installed from EPEL/stable repository. How to reproduce the issue:

0) launch EC2 instance 
1) install salt minion (`yum install salt-minion -y`)
2) configure master(s), e.g. by `echo 'master: [192.168.1.101, 192.168.1.102]' > /etc/salt/minion.d/masters.conf`
3) call `/etc/init.d/salt-minion restart`
4) call `salt-call state.highstate`

It is important that step 4  follows immediately step 3 (timing issue? race-condition?). Further, salt minion has configured `schedule` pillar where `state.highstate` function is automatically scheduled on minions:
```
schedule:
  highstate:
    function: state.highstate
    minutes: 30
```

On salt minion 2014.1.10, such a sequence of commands  will throw the following exception. One thing is interesting that `state.highstate` is partially executed but the minion key is finally rejected:
```
2015-01-22 15:29:22,301 [salt.crypt       ][INFO    ] Generating keys: /etc/salt/pki/minion
2015-01-22 15:29:24,546 [salt.log.setup                           ][ERROR   ] An un-handled exception was caught by salt's global exception handler:
RSAError: oaep decoding error
Traceback (most recent call last):
  File "/usr/bin/salt-minion", line 14, in <module>
    salt_minion()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 35, in salt_minion
    minion.start()
  File "/usr/lib/python2.6/site-packages/salt/__init__.py", line 224, in start
    self.minion.tune_in()
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 457, in tune_in
    minions = self.minions()
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 381, in minions
    minions = self._gen_minions()
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 370, in _gen_minions
    minions.append(Minion(s_opts, 5, False))
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 553, in __init__
    opts['environment'],
  File "/usr/lib/python2.6/site-packages/salt/pillar/__init__.py", line 73, in compile_pillar
    ret_pillar = self.sreq.crypted_transfer_decode_dictentry(load, dictkey='pillar', tries=3, timeout=7200)
  File "/usr/lib/python2.6/site-packages/salt/transport/__init__.py", line 61, in crypted_transfer_decode_dictentry
    aes = key.private_decrypt(ret['key'], 4)
  File "/usr/lib64/python2.6/site-packages/M2Crypto/RSA.py", line 63, in private_decrypt
    return m2.rsa_private_decrypt(self.rsa, data, padding)
RSAError: oaep decoding error
...
... at this part, state.highstate is executed
...
2015-01-22 15:55:57,074 [salt.crypt                               ][CRITICAL] The Salt Master has rejected this minion's public key!
To repair this issue, delete the public key for this minion on the Salt Master and restart this minion.
Or restart the Salt Master in open mode to clean out the keys. The Salt Minion will now exit.
```

Salt minion 2014.1.13 error:
```
	

    2015-01-26 16:15:57,133 [salt.crypt       ][CRITICAL] The Salt Master has rejected this minion's public key!
    To repair this issue, delete the public key for this minion on the Salt Master and restart this minion.
    Or restart the Salt Master in open mode to clean out the keys. The Salt Minion will now exit.
    2015-01-26 16:15:57,189 [salt.log.setup                           ][ERROR   ] An un-handled exception was caught by salt's global exception handler:
    RSAError: oaep decoding error
    Traceback (most recent call last):
      File "/usr/bin/salt-minion", line 14, in <module>
        salt_minion()
      File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 35, in salt_minion
        minion.start()
      File "/usr/lib/python2.6/site-packages/salt/__init__.py", line 224, in start
        self.minion.tune_in()
      File "/usr/lib/python2.6/site-packages/salt/minion.py", line 460, in tune_in
        minions = self.minions()
      File "/usr/lib/python2.6/site-packages/salt/minion.py", line 384, in minions
        minions = self._gen_minions()
      File "/usr/lib/python2.6/site-packages/salt/minion.py", line 370, in _gen_minions
        minions.append(Minion(s_opts, 5, False))
      File "/usr/lib/python2.6/site-packages/salt/minion.py", line 560, in __init__
        self.authenticate(timeout, safe)
      File "/usr/lib/python2.6/site-packages/salt/minion.py", line 1085, in authenticate
        creds = auth.sign_in(timeout, safe)
      File "/usr/lib/python2.6/site-packages/salt/crypt.py", line 401, in sign_in
        auth['aes'] = self.verify_master(payload)
      File "/usr/lib/python2.6/site-packages/salt/crypt.py", line 330, in verify_master
        aes, token = self.decrypt_aes(payload, False)
      File "/usr/lib/python2.6/site-packages/salt/crypt.py", line 278, in decrypt_aes
        key_str = key.private_decrypt(payload['aes'], RSA.pkcs1_oaep_padding)
      File "/usr/lib64/python2.6/site-packages/M2Crypto/RSA.py", line 63, in private_decrypt
        return m2.rsa_private_decrypt(self.rsa, data, padding)
    RSAError: oaep decoding error
```

You may ask me why we have such a weird sequence of commands to bootstrap a minion. This is definitely a bug in our bootstrap code we pass as ec2 user-data. But the question is why such sequence of commands is causing that a minion key is initially generated, then, an exception is throwed and then, it seems the key is regenerated again (the initial key accepted by the master differs from the minion key). Is there some timing issue or kind of race condition between these commands?

**Comment by basepi** [comment]
Why is it important that (3) quickly follow (4)?

There definitely could be a race condition between those two commands. The problem is that `salt-call` is actually completely separate from the running minion daemon, it doesn't utilize the existing connections at all. So the minion just restarted, and then you immediately ran `salt-call`, which is almost like starting the minion again. Those two commands probably both try to authenticate with the master, and cause problems that way. For all I know, they could both be trying to generate keys at the same time, and whoever is second overwrites the first keys, but the first keys are the ones cached by the master, or something like that.

This is all conjecture, but I'm not terribly surprised you're running into issues. Have you considered instead just using `startup_states: highstate` in your minion config, so it will run a highstate when it first starts up, but won't conflict with itself?

**Comment by dsumsky** [comment]
As I wrote, we have scheduled `state.highstate` function by `schedule` pillar but shouldn't be such race condition in key generation code eliminated? By "quickly follow" I mean put these two commands into one liner or a  script and run it. We will definitely focus on bootstrap scripts written by other teams but I can't ensure that it won't appear again (such sequence of commands) :-)

**Comment by dsumsky** [comment]
This seems to be a duplicate of #17289
