### ISSUE TITLE
Compound matcher broken in 2015.2

### ISSUE THREAD

**Issue by basepi** [saltstack/salt#20074]
From @iggy on IRC:

```
2015-01-23 17:27:09,007 [salt.utils.minions                         ][ERROR   ][11457] Failed matching available minions with compound_pillar_exact pattern: G@tags:db and G@tags:primary
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/minions.py", line 513, in check_minions
    minions = check_func(expr, delimiter, greedy)
  File "/usr/lib/python2.7/dist-packages/salt/utils/minions.py", line 346, in _check_compound_pillar_exact_minions
    pillar_exact=True)
  File "/usr/lib/python2.7/dist-packages/salt/utils/minions.py", line 392, in _check_compound_minions
    results.append(str(set(matcher('@'.join(comps[1:]), True))))
TypeError: _check_grain_minions() takes exactly 4 arguments (3 given)
2015-01-23 17:27:09,681 [salt.utils.minions                         ][ERROR   ][11452] Failed matching available minions with compound_pillar_exact pattern: G@tags:db and G@tags:primary
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/minions.py", line 513, in check_minions
    minions = check_func(expr, delimiter, greedy)
  File "/usr/lib/python2.7/dist-packages/salt/utils/minions.py", line 346, in _check_compound_pillar_exact_minions
    pillar_exact=True)
  File "/usr/lib/python2.7/dist-packages/salt/utils/minions.py", line 392, in _check_compound_minions
    results.append(str(set(matcher('@'.join(comps[1:]), True))))
TypeError: _check_grain_minions() takes exactly 4 arguments (3 given)
```

The addition of the `delimiter` arg seems to be the culprit here, I'll have a fix shortly.

**Comment by iggy** [comment]
Works for me.

**Comment by basepi** [comment]
Great, thanks! I think this would auto-close once my fix was merged forward to develop, but I'm just going to close now. =)
