### ISSUE TITLE
infinite recursion when transitive prereq fails 

### ISSUE THREAD

**Issue by bastiaanb** [saltstack/salt#20143]
The following state results in an infinite recursion, instead of a plain failed state run:
```
failing-state:
  cmd.run:
    - name: /bin/false

state-with-require:
  cmd.run:
    - name: /bin/true
    - require:
      - cmd: failing-state

state-with-prereq:
  cmd.run:
    - name: /bin/true
    - prereq:
      - cmd: state-with-require
```
versions-report:
```
salt-call --versions-report
           Salt: 2014.7.1
         Python: 2.6.6 (r266:84292, Oct 15 2013, 07:32:41)
         Jinja2: unknown
       M2Crypto: 0.20.2
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed
```
This may be the same issue as #15171.

**Comment by jfindlay** [comment]
### versions
```
centos-7-main salt 2014.7 # lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.0.1406 (Core) 
Release:        7.0.1406
Codename:       Core
centos-7-main salt 2014.7 # salt --versions
           Salt: 2014.7.1-177-gcc1e81a
         Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: 1.4.0
         PyYAML: 3.10
          ioflo: 1.1.0
          PyZMQ: 14.3.1
           RAET: 0.4.2
            ZMQ: 3.2.4
           Mako: Not Installed
```

### setup
```
centos-7-main salt 2014.7 # cat /srv/salt/recurse.sls 
failing-state:
  cmd.run:
    - name: /bin/false

state-with-require:
  cmd.run:
    - name: /bin/true
    - require:
      - cmd: failing-state

state-with-prereq:
  cmd.run:
    - name: /bin/true
    - prereq:
      - cmd: state-with-require
```

### execution
```
centos-7-main salt 2014.7 # salt centos-7-main state.sls recurse
centos-7-main:
    The minion function caused an exception: Traceback (most recent call last):
      File "/root/salt/salt/minion.py", line 1022, in _thread_return
        return_data = func(*args, **kwargs)
      File "/root/salt/salt/modules/state.py", line 474, in sls
        ret = st_.state.call_high(high_)
      File "/root/salt/salt/state.py", line 2002, in call_high
        ret = self.call_chunks(chunks)
      File "/root/salt/salt/state.py", line 1594, in call_chunks
        running = self.call_chunk(low, running, chunks)
      File "/root/salt/salt/state.py", line 1827, in call_chunk
        running = self.call_chunk(chunk, running, chunks)
      File "/root/salt/salt/state.py", line 1838, in call_chunk
        running = self.call_chunk(low, running, chunks)
      ...
      File "/root/salt/salt/state.py", line 1838, in call_chunk
        running = self.call_chunk(low, running, chunks)
      File "/root/salt/salt/state.py", line 1746, in call_chunk
        status, reqs = self.check_requisite(low, running, chunks, True)
      File "/root/salt/salt/state.py", line 1648, in check_requisite
        req = trim_req(req)
      File "/root/salt/salt/state.py", line 114, in trim_req
        reqfirst = next(iter(req))
    RuntimeError: maximum recursion depth exceeded while calling a Python object
```

**Comment by boltronics** [comment]
Still an issue in 2017.7.2.

**Comment by darkpixel** [comment]
+1
