### ISSUE TITLE
grains.setval broken in develop

### ISSUE THREAD

**Issue by kiorky** [saltstack/salt#20170]
```
  File "/srv/mastersalt/makina-states/src/salt/salt/output/__init__.py", line 43, in try_printout
    return get_printout('nested', None)(data).rstrip()
  File "/srv/mastersalt/makina-states/src/salt/salt/output/__init__.py", line 150, in get_printout
    outputters = salt.loader.outputters(opts)
  File "/srv/mastersalt/makina-states/src/salt/salt/loader.py", line 241, in outputters
    ext_type_dirs='outputter_dirs')
  File "/srv/mastersalt/makina-states/src/salt/salt/loader.py", line 76, in _create_loader
    ext_types = os.path.join(opts['extension_modules'], ext_type)
KeyError: 'extension_modules'
{'xxxxmakina-corpus.net': {'makina.xxx': True}}
```
@jacksontj, an idea??, i saw you pushing something for the loader not so long ago, maybe its related

**Comment by kiorky** [comment]
cc @thatch45

**Comment by kiorky** [comment]
digging a bit more, using salt-call grain.setval instead of salt <foo> grains.setval, it seems a false positive, as it seems my locale_info grain is broken and is not loaded:
```
[TRACE   ] data = {'locale_info': {'defaultencoding': 'utf-8'}, 'local': {'foo': 'bar'}}
locale_info:
  defaultencoding: utf-8
local:
  foo: bar
root@online-dc3-1:/
```
And the traceback is out

**Comment by kiorky** [comment]
Indeed, i just putted that ugly and broken diff to test it out 
```
diff --git a/salt/output/grains.py b/salt/output/grains.py
index a9d6fdb..4cd602f 100644
--- a/salt/output/grains.py
+++ b/salt/output/grains.py
@@ -32,6 +32,8 @@ def output(grains):
     Output the grains in a clean way
     '''
     colors = salt.utils.get_colors(__opts__.get('color'), __opts__.get('color_theme'))
+    grains['locale_info'] = {}
+    grains['locale_info']['defaultencoding'] = 'utf-8'
     encoding = grains['locale_info']['defaultencoding']
     if encoding == 'unknown':
         encoding = 'utf-8'  # let's hope for the best
```

**Comment by kiorky** [comment]
Because of this traceback, with salt-call where we see clearly that the error i saw in the first place is just a side effect.
```
[DEBUG   ] Traceback (most recent call last):
  File "/srv/mastersalt/makina-states/src/salt/salt/output/__init__.py", line 39, in try_printout
    return get_printout(out, opts)(data).rstrip()
  File "/srv/mastersalt/makina-states/src/salt/salt/output/grains.py", line 35, in output
    encoding = grains['locale_info']['defaultencoding']
KeyError: 'locale_info'

[ERROR   ] Nested output failed: 
Traceback (most recent call last):
  File "/srv/mastersalt/makina-states/src/salt/salt/output/__init__.py", line 43, in try_printout
    return get_printout('nested', None)(data).rstrip()
  File "/srv/mastersalt/makina-states/src/salt/salt/output/__init__.py", line 150, in get_printout
    outputters = salt.loader.outputters(opts)
  File "/srv/mastersalt/makina-states/src/salt/salt/loader.py", line 241, in outputters
    ext_type_dirs='outputter_dirs')
  File "/srv/mastersalt/makina-states/src/salt/salt/loader.py", line 76, in _create_loader
    ext_types = os.path.join(opts['extension_modules'], ext_type)
KeyError: 'extension_modules'
[TRACE   ] loading output in ['/var/c
```

**Comment by jacksontj** [comment]
@kiorky my "loader" changes are to a local branch of mine, nothing merged into develop yet.

**Comment by kiorky** [comment]
Ok :)

**Comment by kiorky** [comment]
```
(Pdb) pp grains
{'local': {'SSDs': [],
           'biosreleasedate': '07/01/2013',
           'biosversion': 'J01',
```
grains are nested under a 'local' subdict, which is the root of the issues.

**Comment by jacksontj** [comment]
@kiorky what command where you running to get that exception?

**Comment by kiorky** [comment]
i m going to add a patch soon.

**Comment by kiorky** [comment]
we got it fixed on saltstack/salt/pull/20172

**Comment by jacksontj** [comment]
@thatch45 After looking into this more with @kiorky it seems that the grains outputter has been broken for ~8 months-- since the loader is good at catching exceptions no one has noticed. We've just been falling back to nested instead-- which works fine and looks better. After looking at this grains outputter more I believe we should just remove it and use nested instead.

**Comment by kiorky** [comment]
for compat, we can also call nested from grains.
