### ISSUE TITLE
salt-api makes a big pause when starting before being able to answer requests

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#20243]
When launching salt-api there is a time lapse when the service doesn't bind to the port and doesn't seem to be doing anything. The following happens

```
root@ursa:~# salt-api  -l all
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/ldap.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/ldap.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/peer_publish.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/peer_publish.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/reactor.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/reactor.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/roots.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/roots.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/runners.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/runners.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/salt-api.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/salt-api.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/state_verbose.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/state_verbose.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: ursa
[DEBUG   ] Missing configuration file: ~/.saltrc
[TRACE   ] loading log_handlers in ['/srv/salt/extension_modules/log_handlers', '/usr/lib/python2.7/dist-packages/salt/log/handlers']
[TRACE   ] Skipping /srv/salt/extension_modules/log_handlers, it is not a directory
[TRACE   ] None of the required configuration sections, 'logstash_udp_handler' and 'logstash_zmq_handler', were found the in the configuration. Not loading the Logstash logging handlers module.
[DEBUG   ] Configuration file path: /etc/salt/master
[TRACE   ] loading netapi in ['/srv/salt/extension_modules/netapi', '/usr/lib/python2.7/dist-packages/salt/netapi']
[TRACE   ] Skipping /srv/salt/extension_modules/netapi, it is not a directory
[TRACE   ] Added rest.start to netapi
[TRACE   ] Added rest.verify_certs to netapi
[DEBUG   ] Created pidfile: /var/run/salt-api.pid
[INFO    ] Starting rest.start netapi module
[DEBUG   ] Started '<function start at 0x7f57d70cc848>'(*[], **{} with pid 15657
[DEBUG   ] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
[TRACE   ] loading auth in ['/srv/salt/extension_modules/auth', '/usr/lib/python2.7/dist-packages/salt/auth']
[TRACE   ] Skipping /srv/salt/extension_modules/auth, it is not a directory
[WARNING ] Failed to import auth django, this is due most likely to a syntax error. Traceback raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 925, in load_modules
    ), fn_, path, desc
  File "/usr/lib/python2.7/dist-packages/salt/auth/django.py", line 54, in <module>
    import django.contrib.auth
  File "/usr/lib/python2.7/dist-packages/django/contrib/auth/__init__.py", line 6, in <module>
    from django.middleware.csrf import rotate_token
  File "/usr/lib/python2.7/dist-packages/django/middleware/csrf.py", line 14, in <module>
    from django.utils.cache import patch_vary_headers
  File "/usr/lib/python2.7/dist-packages/django/utils/cache.py", line 26, in <module>
    from django.core.cache import get_cache
  File "/usr/lib/python2.7/dist-packages/django/core/cache/__init__.py", line 69, in <module>
    if DEFAULT_CACHE_ALIAS not in settings.CACHES:
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 47, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
ImproperlyConfigured: Requested setting CACHES, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
```

big pause

```

[TRACE   ] Added auto.auth to auth
[TRACE   ] Added keystone.AuthorizationFailure to auth
[TRACE   ] Added keystone.Unauthorized to auth
[TRACE   ] Added keystone.auth to auth
[TRACE   ] Added keystone.get_auth_url to auth
[TRACE   ] Added ldap.Environment to auth
[TRACE   ] Added ldap.auth to auth
[TRACE   ] Added ldap.groups to auth
[TRACE   ] Added pki.auth to auth
[TRACE   ] Added pam.CALLOC to auth
[TRACE   ] Added pam.CDLL to auth
[TRACE   ] Added pam.CFUNCTYPE to auth
[TRACE   ] Added pam.CONV_FUNC to auth
[TRACE   ] Added pam.PAM_AUTHENTICATE to auth
[TRACE   ] Added pam.PAM_END to auth
[TRACE   ] Added pam.PAM_START to auth
[TRACE   ] Added pam.POINTER to auth
[TRACE   ] Added pam.PamConv to auth
[TRACE   ] Added pam.PamHandle to auth
[TRACE   ] Added pam.PamMessage to auth
[TRACE   ] Added pam.PamResponse to auth
[TRACE   ] Added pam.STRDUP to auth
[TRACE   ] Added pam.Structure to auth
[TRACE   ] Added pam.auth to auth
[TRACE   ] Added pam.authenticate to auth
[TRACE   ] Added pam.c_char to auth
[TRACE   ] Added pam.c_char_p to auth
[TRACE   ] Added pam.c_int to auth
[TRACE   ] Added pam.c_uint to auth
[TRACE   ] Added pam.c_void_p to auth
[TRACE   ] Added pam.cast to auth
[TRACE   ] Added pam.find_library to auth
[TRACE   ] Added pam.get_group_list to auth
[TRACE   ] Added pam.groups to auth
[TRACE   ] Added pam.pointer to auth
[TRACE   ] Added pam.sizeof to auth
[TRACE   ] loading auth in ['/srv/salt/extension_modules/auth', '/usr/lib/python2.7/dist-packages/salt/auth']
[TRACE   ] Skipping /srv/salt/extension_modules/auth, it is not a directory
[WARNING ] Failed to import auth django, this is due most likely to a syntax error. Traceback raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 925, in load_modules
    ), fn_, path, desc
  File "/usr/lib/python2.7/dist-packages/salt/auth/django.py", line 54, in <module>
    import django.contrib.auth
  File "/usr/lib/python2.7/dist-packages/django/contrib/auth/__init__.py", line 6, in <module>
    from django.middleware.csrf import rotate_token
  File "/usr/lib/python2.7/dist-packages/django/middleware/csrf.py", line 14, in <module>
    from django.utils.cache import patch_vary_headers
  File "/usr/lib/python2.7/dist-packages/django/utils/cache.py", line 26, in <module>
    from django.core.cache import get_cache
  File "/usr/lib/python2.7/dist-packages/django/core/cache/__init__.py", line 69, in <module>
    if DEFAULT_CACHE_ALIAS not in settings.CACHES:
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 47, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
ImproperlyConfigured: Requested setting CACHES, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
[TRACE   ] Added auto.auth to auth
[TRACE   ] Added keystone.AuthorizationFailure to auth
[TRACE   ] Added keystone.Unauthorized to auth
[TRACE   ] Added keystone.auth to auth
[TRACE   ] Added keystone.auth to auth
[TRACE   ] Added keystone.get_auth_url to auth
[TRACE   ] Added ldap.Environment to auth
[TRACE   ] Added ldap.auth to auth
[TRACE   ] Added ldap.groups to auth
[TRACE   ] Added pki.auth to auth
[TRACE   ] Added pam.CALLOC to auth
[TRACE   ] Added pam.CDLL to auth
[TRACE   ] Added pam.CFUNCTYPE to auth
[TRACE   ] Added pam.CONV_FUNC to auth
[TRACE   ] Added pam.PAM_AUTHENTICATE to auth
[TRACE   ] Added pam.PAM_END to auth
[TRACE   ] Added pam.PAM_START to auth
[TRACE   ] Added pam.POINTER to auth
[TRACE   ] Added pam.PamConv to auth
[TRACE   ] Added pam.PamHandle to auth
[TRACE   ] Added pam.PamMessage to auth
[TRACE   ] Added pam.PamResponse to auth
[TRACE   ] Added pam.STRDUP to auth
[TRACE   ] Added pam.Structure to auth
[TRACE   ] Added pam.auth to auth
[TRACE   ] Added pam.authenticate to auth
[TRACE   ] Added pam.c_char to auth
[TRACE   ] Added pam.c_char_p to auth
[TRACE   ] Added pam.c_int to auth
[TRACE   ] Added pam.c_uint to auth
[TRACE   ] Added pam.c_void_p to auth
[TRACE   ] Added pam.cast to auth
[TRACE   ] Added pam.find_library to auth
[TRACE   ] Added pam.get_group_list to auth
[TRACE   ] Added pam.groups to auth
[TRACE   ] Added pam.pointer to auth
[TRACE   ] Added pam.sizeof to auth
[INFO    ] [30/Jan/2015:11:16:31] ENGINE Listening for SIGHUP.
[INFO    ] [30/Jan/2015:11:16:31] ENGINE Listening for SIGTERM.
[INFO    ] [30/Jan/2015:11:16:31] ENGINE Listening for SIGUSR1.
[INFO    ] [30/Jan/2015:11:16:31] ENGINE Bus STARTING
[INFO    ] [30/Jan/2015:11:16:31] ENGINE Started monitor thread '_TimeoutMonitor'.
[INFO    ] [30/Jan/2015:11:16:31] ENGINE Serving on 127.0.0.1:8000
[INFO    ] [30/Jan/2015:11:16:31] ENGINE Bus STARTED
```

Versions : 

```
root@ursa:~# salt-api  --versions-report
           Salt: 2014.7.1
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
```

side note : maybe the django traceback could be less verbose...

**Comment by arthurlogilab** [comment]
strace doesn't give a clear answer to my question. This seems to be related to multiprocessing but can't figure out yet what is going on.

**Comment by whiteinge** [comment]
Odd. My initial guess is the Django traceback is not related. (Fix is here #20268.)

Do you see similar behavior when starting the Salt master? Is there anything unusual about your setup like using an NFS share or an unusual flavor of Linux? Did you upgrade your Salt or salt-api installation from an older installation?

Try shutting down salt-api and the salt-master. Then double-check that both services are really, actually down by looking for any remaining Salt processes (e.g., `pgrep -l salt`). (Sometimes it takes a few seconds for that to happen.) Then try again.

**Comment by arthurlogilab** [comment]
to my knowledge nothing fancy about my flavor of linux (ubuntu or debian). No NFS in this case. Yes I've been using salt and salt-api for a while so there have probably been a few updates. Do you think it could be in configuration files ? 

Yes I did check the services were down before restarting.

**Comment by whiteinge** [comment]
What netapi modules do you have configured for salt-api to load? Are you using an external webserver?

Occasionally we'll see weird random issues when upgrading a Salt installation. This is _extremely_ rare when using system packages but somewhat common for pip/easy-install based installs.

One last thing to try. Destructive operations follow, so go carefully! Adjust paths for your actual system as appropriate.

* Shutdown both daemons and make sure they're shutdown.
* Nuke any compiled Python files: `find /usr/lib/python2.7/dist-packages/salt -name '*.pyc' -delete`
* Nuke the Salt cache: `rm /var/cache/salt`

**Comment by arthurlogilab** [comment]
No pip install here (only ubuntu packages).

No external webserver, salt-api is using cherrypi started via salt-api service. 

After the cleanup the result is the same. 

I took the time to count the seconds : 22 seconds waiting...

**Comment by whiteinge** [comment]
Well dang. Ok, let's dive deeper.

* Did you upgrade from a version of salt-api from when it was a separate project? (That was before 2014.7.)
* Could you paste your `rest_cherrypy` config?
* Do you see a similar hang when starting the salt-master daemon?

**Comment by arthurlogilab** [comment]
Yes I've tried salt-api before when it was a separate project. 

```
rest_cherrypy:
  host: 127.0.0.1
  port: 8000
  ssl_crt: /etc/pki/tls/certs/localhost.crt
  ssl_key: /etc/pki/tls/certs/localhost.key


```

Yes I have the same lag in the salt-master (never noticed it until now) notice the bump from 09:25:28 to 09:25:54 (26 seconds).

```
2015-02-05 09:25:28,704 [salt.loaded.int.grain.ssds][TRACE   ] Device ram15 does not report itself as an SSD
2015-02-05 09:25:28,704 [salt.loaded.int.grain.ssds][TRACE   ] Device zram0 reports itself as an SSD
2015-02-05 09:25:28,704 [salt.loaded.int.grain.ssds][TRACE   ] Device zram1 reports itself as an SSD
2015-02-05 09:25:28,705 [salt.loader      ][TRACE   ] loading module in ['/srv/salt/extension_modules/modules', '/usr/lib/python2.7/dist-packages/salt/modules'
]
2015-02-05 09:25:28,705 [salt.loader      ][TRACE   ] Skipping /srv/salt/extension_modules/modules, it is not a directory
2015-02-05 09:25:54,080 [salt.utils.decorators][TRACE   ] Depends decorator instantiated with dep list of ('zypp',)
2015-02-05 09:25:54,081 [salt.utils.decorators][TRACE   ] Depends decorator instantiated with dep list of ('zypp',)
2015-02-05 09:25:54,142 [salt.utils.decorators][TRACE   ] Depends decorator instantiated with dep list of ('zypp',)
2015-02-05 09:25:54,142 [salt.utils.decorators][TRACE   ] Depends decorator instantiated with dep list of ('zypp',)
2015-02-05 09:25:54,143 [salt.utils.decorators][TRACE   ] Depends decorator instantiated with dep list of ('zypp',)
2015-02-05 09:25:54,144 [salt.utils.decorators][TRACE   ] Depends decorator instantiated with dep list of ('zypp',)
2015-02-05 09:25:54,144 [salt.utils.decorators][TRACE   ] Depends decorator instantiated with dep list of ('zypp',)
2015-02-05 09:25:54,145 [salt.utils.decorators][TRACE   ] Depends decorator instantiated with dep list of ('zypp',)
2015-02-05 09:25:54,145 [salt.utils.decorators][TRACE   ] Depends decorator instantiated with dep list of ('zypp',)
2015-02-05 09:25:54,146 [salt.utils.decorators][TRACE   ] Depends decorator instantiated with dep list of ('zypp',)
2015-02-05 09:25:54,152 [salt.utils       ][TRACE   ] 'nsenter' could not be found in the following search path: ['/usr/local/sbin', '/usr/local/bin', '/usr/sb
in', '/usr/bin', '/sbin', '/bin']
2015-02-05 09:25:54,152 [salt.modules.cmdmod][INFO    ] Executing command '/sbin/zfs help' in directory '/home/arthur'
2015-02-05 09:25:54,153 [salt.utils       ][TRACE   ] 'nsenter' could not be found in the following search path: ['/usr/local/sbin', '/usr/local/bin', '/usr/sb
in', '/usr/bin', '/sbin', '/bin']
2015-02-05 09:25:54,154 [salt.modules.cmdmod][INFO    ] Executing command '/sbin/zfs help' in directory '/home/arthur'
2015-02-05 09:25:54,160 [salt.modules.cmdmod][TRACE   ] stderr: unrecognized command 'help'
usage: zfs command args ...
where 'command' is one of the following:

```
This lag only seem to be present after having cleared the cache though.

**Comment by whiteinge** [comment]
So the lag in the master only happens after clearning the cache but the lag in salt-api happens every time?

**Comment by arthurlogilab** [comment]
yep

**Comment by whiteinge** [comment]
@arthurlogilab whelp this one has me stumped. Could you pastebin a (sanitized) copy of everything that is not commented in your master config (as well as anything in the `master.d` directory)? I'll see if anything there jumps out at me.

The next step would be to set up the Salt Master and salt-api on a fresh VM to see if the problem is recreated for you there.

**Comment by cachedout** [comment]
Could this be a failing DNS lookup?
