### ISSUE TITLE
salt-ssh operations fail with "'msgpack' not defined" error

### ISSUE THREAD

**Issue by mventimi** [saltstack/salt#20276]
Using salt-ssh off of latest develop, most commands fail with *'msgpack' not defined* error:
```
$ salt-ssh -i lab cmd.run 'uname -a'
lab:
    ----------
    retcode:
        1
    stderr:
        [CRITICAL] Unable to import msgpack or msgpack_pure python modules
        Traceback (most recent call last):
          File "/tmp/.pi_6787e8__salt/salt-call", line 4, in <module>
            salt_call()
          File "/tmp/.pi_6787e8__salt/salt/scripts.py", line 220, in salt_call
            client.run()
          File "/tmp/.pi_6787e8__salt/salt/cli/call.py", line 50, in run
            caller.run()
          File "/tmp/.pi_6787e8__salt/salt/cli/caller.py", line 235, in run
            ret = self.call()
          File "/tmp/.pi_6787e8__salt/salt/cli/caller.py", line 139, in call
            ret['return'] = func(*args, **kwargs)
          File "/tmp/.pi_6787e8__salt/salt/modules/cmdmod.py", line 617, in run
            jid_dict = serial.load(fn_)
          File "/tmp/.pi_6787e8__salt/salt/payload.py", line 112, in load
            return self.loads(data)
          File "/tmp/.pi_6787e8__salt/salt/payload.py", line 97, in loads
            return msgpack.loads(msg, use_list=True)
        NameError: global name 'msgpack' is not defined
    stdout:

$ salt --versions-report
           Salt: 2015.2.0-307-g1fc9a52
         Python: 2.6.9 (unknown, Sep 13 2014, 00:25:11)
         Jinja2: 2.7.2
       M2Crypto: 0.20.2
 msgpack-python: 0.4.5
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed
```
The problem does not occur with version 2014.7.1:
```
$ salt-ssh -i lab cmd.run 'uname -a'
lab:
    Linux raspberrypi 3.12.28+ #709 PREEMPT Mon Sep 8 15:28:00 BST 2014 armv6l GNU/Linux

$ salt --versions-report
           Salt: 2014.7.1
         Python: 2.6.9 (unknown, Sep 13 2014, 00:25:11)
         Jinja2: 2.7.2
       M2Crypto: 0.20.2
 msgpack-python: 0.4.5
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed
```

**Comment by ssgward** [comment]
Thanks for the report. Looking into it.

**Comment by basepi** [comment]
I actually already know where this error is, and why it is being thrown. I'm investigating solutions.

**Comment by steverweber** [comment]
latest release...

still got a related error:

```
[root@salt salt]# salt-ssh mf-hpc.math.xxxx.ca cmd.run 'echo woot'
mf-hpc.math.xxxx.ca:
    ----------
    retcode:
        1
    stderr:
        [CRITICAL] Unable to import msgpack or msgpack_pure python modules
        [ERROR   ] An un-handled exception was caught by salt's global exception handler:
        ImportError: No module named msgpack
        Traceback (most recent call last):
          File "/tmp/.root_b67c91_salt/salt-call", line 4, in <module>
            salt_call()
          File "/tmp/.root_b67c91_salt/salt/scripts.py", line 211, in salt_call
            import salt.cli.call
          File "/tmp/.root_b67c91_salt/salt/cli/call.py", line 8, in <module>
            import salt.cli.caller
          File "/tmp/.root_b67c91_salt/salt/cli/caller.py", line 19, in <module>
            import salt.minion
          File "/tmp/.root_b67c91_salt/salt/minion.py", line 67, in <module>
            import salt.pillar
          File "/tmp/.root_b67c91_salt/salt/pillar/__init__.py", line 15, in <module>
            import salt.fileclient
          File "/tmp/.root_b67c91_salt/salt/fileclient.py", line 27, in <module>
            import salt.utils.http
          File "/tmp/.root_b67c91_salt/salt/utils/http.py", line 47, in <module>
            import msgpack
        ImportError: No module named msgpack
        Traceback (most recent call last):
          File "/tmp/.root_b67c91_salt/salt-call", line 4, in <module>
            salt_call()
          File "/tmp/.root_b67c91_salt/salt/scripts.py", line 211, in salt_call
            import salt.cli.call
          File "/tmp/.root_b67c91_salt/salt/cli/call.py", line 8, in <module>
            import salt.cli.caller
          File "/tmp/.root_b67c91_salt/salt/cli/caller.py", line 19, in <module>
            import salt.minion
          File "/tmp/.root_b67c91_salt/salt/minion.py", line 67, in <module>
            import salt.pillar
          File "/tmp/.root_b67c91_salt/salt/pillar/__init__.py", line 15, in <module>
            import salt.fileclient
          File "/tmp/.root_b67c91_salt/salt/fileclient.py", line 27, in <module>
            import salt.utils.http
          File "/tmp/.root_b67c91_salt/salt/utils/http.py", line 47, in <module>
            import msgpack
        ImportError: No module named msgpack
    stdout:
```

**Comment by basepi** [comment]
@steverweber Yours should be fixed in #20364.

Because of some recent changes in 2015.2 more of these may pop up, and we'll just squish them as they appear.

**Comment by steverweber** [comment]
im using the latest dev....
```
wipe cache files on master.
and bootstraped git develop
```
what is missing?

```
[root@salt salt]# salt-ssh 'mf-hpc.*' cmd.run 'echo woot'
mf-hpc.math.xxxx.ca:
    ----------
    retcode:
        1
    stderr:
        [CRITICAL] Unable to import msgpack or msgpack_pure python modules
        [ERROR   ] An un-handled exception was caught by salt's global exception handler:
        ImportError: No module named msgpack
        Traceback (most recent call last):
          File "/tmp/.root_b67c91_salt/salt-call", line 4, in <module>
            salt_call()
          File "/tmp/.root_b67c91_salt/salt/scripts.py", line 211, in salt_call
            import salt.cli.call
          File "/tmp/.root_b67c91_salt/salt/cli/call.py", line 8, in <module>
            import salt.cli.caller
          File "/tmp/.root_b67c91_salt/salt/cli/caller.py", line 19, in <module>
            import salt.minion
          File "/tmp/.root_b67c91_salt/salt/minion.py", line 67, in <module>
            import salt.pillar
          File "/tmp/.root_b67c91_salt/salt/pillar/__init__.py", line 15, in <module>
            import salt.fileclient
          File "/tmp/.root_b67c91_salt/salt/fileclient.py", line 27, in <module>
            import salt.utils.http
          File "/tmp/.root_b67c91_salt/salt/utils/http.py", line 49, in <module>
            import msgpack
        ImportError: No module named msgpack
        Traceback (most recent call last):
          File "/tmp/.root_b67c91_salt/salt-call", line 4, in <module>
            salt_call()
          File "/tmp/.root_b67c91_salt/salt/scripts.py", line 211, in salt_call
            import salt.cli.call
          File "/tmp/.root_b67c91_salt/salt/cli/call.py", line 8, in <module>
            import salt.cli.caller
          File "/tmp/.root_b67c91_salt/salt/cli/caller.py", line 19, in <module>
            import salt.minion
          File "/tmp/.root_b67c91_salt/salt/minion.py", line 67, in <module>
            import salt.pillar
          File "/tmp/.root_b67c91_salt/salt/pillar/__init__.py", line 15, in <module>
            import salt.fileclient
          File "/tmp/.root_b67c91_salt/salt/fileclient.py", line 27, in <module>
            import salt.utils.http
          File "/tmp/.root_b67c91_salt/salt/utils/http.py", line 49, in <module>
            import msgpack
        ImportError: No module named msgpack
    stdout:
        
[root@salt salt]# salt-ssh --version
salt-ssh 2015.2.0-2527-gb77880a (Lithium)
```

**Comment by techhat** [comment]
@steverweber, that PR was against the 2015.2 branch. It should be merged into develop in a day or two.

**Comment by steverweber** [comment]
I hate to do this, but I have a Salt presentation Friday morning.  It would be nice if this could be merged sooner than latter.

**Comment by techhat** [comment]
Ping @basepi, @rallytime.

**Comment by steverweber** [comment]
low priority now... i removed salt-ssh items from the presentation. Thanks.

**Comment by basepi** [comment]
Sorry that the merge forward took so long. We had some test failures unrelated to your code and so we couldn't get it through in time.

**Comment by steverweber** [comment]
Its all cool. I took a look at the merge it looked... fun glad it actually
worked :)

**Comment by Bilge** [comment]
I'm still having this issue with 2015.2.0rc1. Do I have to wait for a new 2015 release to use `salt-ssh`?

**Comment by basepi** [comment]
This issue should be limited to `cmd.run`. You could patch it in place with the `cmdmod.py` at the head of 2015.2 if you wanted. We hope to have an rc2 out soon.

**Comment by skandyla** [comment]
Hello! I have the same error after salt update to 2014.7.2+ds-1trusty2
salt-ssh --version
salt-ssh 2014.7.2 (Helium)

```
          ID: /root/scripts
    Function: file.recurse
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/tmp/.root_2f798b__salt/salt/state.py", line 1531, in call
                  **cdata['kwargs'])
                File "/tmp/.root_2f798b__salt/salt/states/file.py", line 1982, in recurse
                  source, source_hash = __salt__['file.source_list'](sources, '', __env__)
                File "/tmp/.root_2f798b__salt/salt/modules/file.py", line 2398, in source_list
                  mfiles = __salt__['cp.list_master'](saltenv)
                File "/tmp/.root_2f798b__salt/salt/modules/cp.py", line 514, in list_master
                  return __context__['cp.fileclient'].file_list(saltenv, prefix)
                File "/tmp/.root_2f798b__salt/salt/fileclient.py", line 1050, in file_list
                  return channel.send(load)
                File "/tmp/.root_2f798b__salt/salt/fileserver/__init__.py", line 566, in send
                  return getattr(self.fs, cmd)(load)
                File "/tmp/.root_2f798b__salt/salt/fileserver/__init__.py", line 450, in file_list
                  ret.update(self.servers[fstr](load))
                File "/tmp/.root_2f798b__salt/salt/fileserver/roots.py", line 304, in file_list
                  return _file_lists(load, 'files')
                File "/tmp/.root_2f798b__salt/salt/fileserver/roots.py", line 292, in _file_lists
                  __opts__, ret, list_cache, w_lock
                File "/tmp/.root_2f798b__salt/salt/fileserver/__init__.py", line 147, in write_file_list_cache
                  fp_.write(serial.dumps(data))
                File "/tmp/.root_2f798b__salt/salt/payload.py", line 115, in dumps
                  return msgpack.dumps(msg)
              NameError: global name 'msgpack' is not defined
     Started: 12:26:34.258922
    Duration: 9.306 ms
```

**Comment by basepi** [comment]
@skandyla mind opening a new issue? Looks like one we may have missed.
