### ISSUE TITLE
Solaris x86 packages: Dynamic Libraries not found 

### ISSUE THREAD

**Issue by cro** [saltstack/salt#20346]
```
 /opt/salt/salt-minion -l debug 
Traceback (most recent call last): 
File "<string>", line 6, in <module> 
File "__main__.py", line 128, in <module> 
File "__main__salt-minion__.py", line 9, in <module> 
File "salt/scripts.py", line 17, in <module> 
File "salt/cli/__init__.py", line 13, in <module> 
File "salt/cli/caller.py", line 30, in <module> 
File "raet/__init__.py", line 12, in <module> 
File "importlib/__init__.py", line 37, in import_module 
File "raet/nacling.py", line 11, in <module> 
File "libnacl/__init__.py", line 75, in <module> 
File "libnacl/__init__.py", line 73, in _get_nacl 
OSError: Could not locate nacl lib, searched for libsodium.so, libsodium.so.13, libsodium.so.10, libsodium.so.5, libsodium.so.4, and tweetnacl.so
```

**Comment by cro** [comment]
a quick fix might be to change the dynamic linker paths with

```crle -c /var/ld/ld.config -u -l /opt/salt:/opt/salt/salt-2014.7.1.solaris-2_10-i86pc_32bit```

The "real" fix is for us to make sure all the .so's in the package have the right RPATH. But we need to rebuild the package for that--we're working on that part.

**Comment by dmurphy18** [comment]
With availability of SaltStack Enterprise v3.2.1 for Solaris, Intel and Sparc, this issue has been resolved

**Comment by ksalman** [comment]
Is the fix only in SaltStack Enterprise, it sounds like? How can I, who is not using SaltStack Enterprise, get this fix?
