### ISSUE TITLE
Permission denied error on salt-ssh deploy dir

### ISSUE THREAD

**Issue by Xiol** [saltstack/salt#20418]
Hi,

I'm trying to run salt-ssh via the CherryPy REST API but I'm getting an exception when attempting to do so. This is using the 2015.2 release installed with Salt bootstrap. (`./install_salt.sh git 2015.2`)

/etc/salt/roster:

```
testbox:
    host: 172.16.32.53
    user: myuser
    passwd: mypass
    sudo: true
    tty: true
```

```
[root@saltmaster ~]# curl localhost:8000/run -H "Accept: application/x-yaml" -d client='ssh' -d tgt='*' -d fun='status.diskusage' 
```

(formatted exception)

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/netapi/rest_cherrypy/app.py", line 389, in hypermedia_handler
    ret = cherrypy.serving.request._hypermedia_inner_handler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/salt/netapi/rest_cherrypy/app.py", line 1528, in POST
    'return': list(self.exec_lowstate()),
  File "/usr/lib/python2.7/site-packages/salt/netapi/rest_cherrypy/app.py", line 647, in exec_lowstate
    ret = self.api.run(chunk)
  File "/usr/lib/python2.7/site-packages/salt/netapi/__init__.py", line 48, in run
    return l_fun(*f_call.get('args', ()), **f_call.get('kwargs', {}))
  File "/usr/lib/python2.7/site-packages/salt/netapi/__init__.py", line 101, in ssh
    return ssh_client.cmd_sync(kwargs)
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/client.py", line 128, in cmd_sync
    low.get('kwarg'))
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/client.py", line 102, in cmd
    for ret in ssh.run_iter():
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 434, in run_iter
    if self.opts['raw_shell']:
KeyError: 'raw_shell'
```

```
[root@saltmaster ~]# salt --versions
           Salt: 2015.2.0-1104-g9bf6066
         Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
```

**Comment by Xiol** [comment]
Further to this, I've installed the 'develop' version using bootstrap and can repeat the issue.

Not sure if 'develop' and '2015.2' branch are the same though! ;)

**Comment by rallytime** [comment]
@Xiol Thank you very much for the detailed report! We'll have to investigate.

To answer you question about versioning, technically the `develop` and `2015.2` branches are very different, but our versions report relies on the latest git tag, which was 2015.2.0. You can tell that you're on the develop branch because the second number (1104) in this case denotes the number of commits made since the tag. So develop will have a higher number here than 2015.2 as the branches diverge (commits from 2015.2 are merged into develop, plus the commits made directly to develop). I know that's not very intuitive, but hopefully that helps explain what's happening there.

ping @basepi @whiteinge

**Comment by whiteinge** [comment]
@cachedout may be a better candidate here if he has cycles. I'd recommend testing this without salt-api first.

**Comment by Xiol** [comment]
I'm actually getting permission denied errors when trying to use this with salt-ssh. I'm currently using this with passwordless sudo. (I'd like to get this working with sudo+password but the docs currently seem to indicate this isn't possible).
```
[root@saltmaster ~]# salt-ssh -v -l debug '*' status.diskusage
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: saltmaster.novalocal
[DEBUG   ] Configuration file path: /etc/salt/master
[DEBUG   ] compile template: /etc/salt/roster
[DEBUG   ] Jinja search path: ['/var/cache/salt/master/files/base']
[DEBUG   ] Rendered data from file: /etc/salt/roster:
testbox:
    host: 172.16.32.53
    user: centos
    passwd: removed
    sudo: true
    tty: true

[DEBUG   ] Results of YAML rendering: 
OrderedDict([('testbox', OrderedDict([('host', '172.16.32.53'), ('user', 'centos'), ('passwd', 'removed'), ('sudo', True), ('tty', True)]))])
[INFO    ] minions list: {'testbox': OrderedDict([('host', '172.16.32.53'), ('user', 'centos'), ('passwd', 'removed'), ('sudo', True), ('tty', True)])}
[DEBUG   ] Updating fileserver cache
[DEBUG   ] LazyLoaded local_cache.prep_jid
Executing job with jid 20150206090811912707
-------------------------------------------


[DEBUG   ] Performing shimmed, blocking command as follows:
status.diskusage
[DEBUG   ] Executing command: scp   -o KbdInteractiveAuthentication=no -o PasswordAuthentication=yes -o GSSAPIAuthentication=no -o ConnectTimeout=65 -o Port=22 -o IdentityFile=/etc/salt/pki/master/ssh/salt-ssh.rsa -o User=centos  /var/cache/salt/master/ssh_shim/shim_uOKWyt 172.16.32.53:.534a7cdb9f6d
[DEBUG   ] Child Forked! PID: 8133  STDOUT_FD: 6  STDERR_FD: 8
[DEBUG   ] Terminal Command: /bin/sh -c scp   -o KbdInteractiveAuthentication=no -o PasswordAuthentication=yes -o GSSAPIAuthentication=no -o ConnectTimeout=65 -o Port=22 -o IdentityFile=/etc/salt/pki/master/ssh/salt-ssh.rsa -o User=centos  /var/cache/salt/master/ssh_shim/shim_uOKWyt 172.16.32.53:.534a7cdb9f6d
[DEBUG   ] centos@172.16.32.53's password:
shim_uOKWyt                                   100%   11KB  10.8KB/s   00:00 ETA
[DEBUG   ] Executing command: ssh 172.16.32.53 -t -t -o KbdInteractiveAuthentication=no -o PasswordAuthentication=yes -o GSSAPIAuthentication=no -o ConnectTimeout=65 -o Port=22 -o IdentityFile=/etc/salt/pki/master/ssh/salt-ssh.rsa -o User=centos  /bin/sh $HOME/.534a7cdb9f6d
[DEBUG   ] Child Forked! PID: 8153  STDOUT_FD: 6  STDERR_FD: 8
[DEBUG   ] Terminal Command: /bin/sh -c ssh 172.16.32.53 -t -t -o KbdInteractiveAuthentication=no -o PasswordAuthentication=yes -o GSSAPIAuthentication=no -o ConnectTimeout=65 -o Port=22 -o IdentityFile=/etc/salt/pki/master/ssh/salt-ssh.rsa -o User=centos  /bin/sh $HOME/.534a7cdb9f6d
[DEBUG   ] centos@172.16.32.53's password:
[DEBUG   ] Connection to 172.16.32.53 closed.
[DEBUG   ] /bin/sh: /root/.534a7cdb9f6d: Permission denied
[DEBUG   ] Executing command: ssh 172.16.32.53 -t -t -o KbdInteractiveAuthentication=no -o PasswordAuthentication=yes -o GSSAPIAuthentication=no -o ConnectTimeout=65 -o Port=22 -o IdentityFile=/etc/salt/pki/master/ssh/salt-ssh.rsa -o User=centos  rm $HOME/.534a7cdb9f6d
[DEBUG   ] Child Forked! PID: 8154  STDOUT_FD: 6  STDERR_FD: 8
[DEBUG   ] Terminal Command: /bin/sh -c ssh 172.16.32.53 -t -t -o KbdInteractiveAuthentication=no -o PasswordAuthentication=yes -o GSSAPIAuthentication=no -o ConnectTimeout=65 -o Port=22 -o IdentityFile=/etc/salt/pki/master/ssh/salt-ssh.rsa -o User=centos  rm $HOME/.534a7cdb9f6d
[DEBUG   ] centos@172.16.32.53's password:
[DEBUG   ] Connection to 172.16.32.53 closed.
[DEBUG   ] rm: cannot remove ‘/root/.534a7cdb9f6d’: Permission denied
[DEBUG   ] STDOUT 172.16.32.53
centos@172.16.32.53's password: 
/bin/sh: /root/.534a7cdb9f6d: Permission denied

[DEBUG   ] STDERR 172.16.32.53
Connection to 172.16.32.53 closed.

[DEBUG   ] RETCODE 172.16.32.53: 126
[DEBUG   ] SHIM retcode(126) and command: centos@172.16.32.53's password:
testbox:
    ----------
    retcode:
        126
    stderr:
        Connection to 172.16.32.53 closed.
        
    stdout:
        centos@172.16.32.53's password: 
        /bin/sh: /root/.534a7cdb9f6d: Permission denied
```

**Comment by whiteinge** [comment]
Good update, thanks. I re-titled this issue for now to reflect that most recent error.

**Comment by ltsampros** [comment]
Hello,

are there any news on this?

BR

**Comment by basepi** [comment]
I wonder if the client API problem here could be related to #19866

**Comment by ltsampros** [comment]
@basepi I do not know if they are related. With a quick look I didn't notice any relation to the stack produced above in relation with the Single class, however I'm complete new to the internals of Salt so I could be wrong.

However, the crash occurs in ssh.run_iter(). Please take a look at this version of the file: https://github.com/saltstack/salt/blob/5d83dce33cee1d69142d4af446a0f1c26ef667c5/salt/client/ssh/__init__.py versus the one in branch 2015.02.

In the 1st version of the file, run_iter() calls handle_ssh() directly and the raw_shell key is not checked at all. Blaming the file shows that you introduced the check for raw_shell with commit 705a8797e381e27fd1bb91046fc52986702b9bff .

Examining the code in ssh/client.py proves SSHClient.opts are deepcopied and passed to SSH.__init__(). So it seems that raw_shell needs to exist either in master opts or client opts.

Does the above sound rational?

**Comment by ltsampros** [comment]
@basepi Based on my previous comment I added the line raw_shell: True to my /etc/salt/master and behold:
```python
>>> import salt.client.ssh.client
>>> ssh_client = salt.client.ssh.client.SSHClient()
>>> ssh_client.cmd("*", "test.ping")
{'salt-minion1': {'retcode': 127, 'stderr': 'bash: test.ping: command not found\n', 'stdout': ''}}
```

1) Is the raw_shell option intended to be a global option OR is it supposed to be checked on a per call basis?
2) Is this related to @jfindlay 's comments in #20833 ?

**Comment by basepi** [comment]
`raw_shell` is actually [set by the command line option parsers](https://github.com/saltstack/salt/blob/e2ec567b7a113b44a405d41646bc6ed4f793c866/salt/utils/parsers.py#L2287-L2294). So it should always be present in opts, and should default to False. It's used to send raw commands over SSH to the target minion, instead of using salt.

I do see the problem now, however. Calling through the API avoids the parsers, and so the default doesn't get properly set. Should be as easy as inserting a `.get()` in there, instead of just referencing the key directly. Fix incoming.
