### ISSUE TITLE
network.interface_ip stacktraces if iface has now inet-addr

### ISSUE THREAD

**Issue by 0xf10e** [saltstack/salt#20422]
Hi there,

when an interface has no IPv4 address assigned the function network.interface_ip stacktraces b/c of a KeyError in utils/network.py:

- interface data:
```
user@master: ~% sudo salt controller network.interfaces
controller:
    ----------
[...]
    br-int:
        ----------
        hwaddr:
            7e:20:54:d2:52:44
        inet6:
            |_
              ----------
              address:
                  fe80::ecba:abff:fed4:2c13
              prefixlen:
                  64
            True
    eth0:
        ----------
        hwaddr:
            52:54:00:d6:8b:e3
        inet:
            |_
              ----------
              address:
                  192.168.122.85
              broadcast:
                  192.168.122.255
              label:
                  eth0
              netmask:
                  255.255.255.0
        inet6:
            |_
              ----------
              address:
                  fe80::5054:ff:fed6:8be3
              prefixlen:
                  64
        up:
            True
[...]
```
- stacktrace for interface **without** IPv4 addr:
```
user@master:~% sudo salt controller network.interface_ip br-int
controller:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1022, in _thread_return
        return_data = func(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/network.py", line 480, in interface_ip
        return salt.utils.network.interface_ip(iface)
      File "/usr/lib/python2.7/dist-packages/salt/utils/network.py", line 738, in interface_ip
        return interfaces().get(iface, {}).get('inet', {})[0].get('address', {})
    KeyError: 0
    
user@master:~%
```
- for interface with IPv4 address:
```
user@master:~% sudo salt controller network.interface_ip eth0 
controller:
    192.168.122.85
```

- Versions minion (Ubuntu 14.04):
```
root@controller:~# salt-minion --versions-report
           Salt: 2014.7.1
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
```
- Versions master (Ubuntu 12.04):
```
user@master:~% sudo salt-master --versions-report           
           Salt: 2014.7.1
         Python: 2.7.3 (default, Dec 18 2014, 19:10:20)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.4.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 13.0.0
           RAET: Not Installed
            ZMQ: 3.2.2
           Mako: Not Installed
```

Should be a rather low hanging fruit ;)

**Comment by jfindlay** [comment]
@0xf10e, thanks for the report.  It's 2015 and now IPv4 is about twice as old as IPv6, so why aren't we using it by default already? :-)

**Comment by 0xf10e** [comment]
@jfindlay I can't, I'm working on a formula for OpenStack and their support for IPv6 is pretty sketchy! ^^

Am 5. Februar 2015 19:56:54 MEZ, schrieb jfindlay <notifications@github.com>:
