### ISSUE TITLE
module kwargs processing is bork

### ISSUE THREAD

**Issue by jfindlay** [saltstack/salt#20484]
### versions
```
jmoney-main salt (c96b472...) # lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.0 (jessie)
Release:        8.0
Codename:       jessie
```
```
jmoney-main salt (c96b472...) # salt --versions-report
           Salt: 2014.7.1-312-gc96b472
         Python: 2.7.8 (default, Oct 18 2014, 12:50:18)
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.4.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: 1.0.0
```

### execution
```
jmoney-main salt (c96b472...) # salt '*' cmd.run "grep f" stdin='one\ntwo\nthree\nfour\nfive\n'
jmoney-main:
    ERROR: Specified cwd 'stdin=one\\ntwo\\nthree\\nfour\\nfive\\n' either not absolute or does not exist
```

### minion log
```
[INFO    ] Executing command 'grep f' in directory 'stdin=one\\ntwo\\nthree\\nfour\\nfive\\n'
[ERROR   ] A command in 'cmd.run' had a problem: Specified cwd 'stdin=one\\ntwo\\nthree\\nfour\\nfive\\n' either not absolute or does not exist
Traceback (most recent call last):
  File "/root/salt/salt/minion.py", line 1022, in _thread_return
    return_data = func(*args, **kwargs)
  File "/root/salt/salt/modules/cmdmod.py", line 624, in run
    use_vt=use_vt)
  File "/root/salt/salt/modules/cmdmod.py", line 359, in _run
    .format(cwd)
CommandExecutionError: Specified cwd 'stdin=one\\ntwo\\nthree\\nfour\\nfive\\n' either not absolute or does not exist
```

**Comment by cachedout** [comment]
So this issue here is limited to ``\n`` strings in kwargs?

**Comment by jfindlay** [comment]
@cachedout, it appears so.
