### ISSUE TITLE
Traceback in output with `--log-level debug` on Windows

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt#20494]
On Windows with Salt v2014.7.1 (masterless), I'm getting a traceback error at the very end of the output when I set the log level to debug. Doesn't seem to impact execution of the states; I'm not sure what exactly is failing...

```
2015-02-07 12:58:41,254 [salt.loaded.int.module.cmdmod][DEBUG   ] output: File not found - C:\salt\var\cache\salt\minion\highstate.p
2015-02-07 12:58:41,254 [salt.loader      ][DEBUG   ] Failed to import returner :
Traceback (most recent call last):
  File "salt/loader.py", line 621, in gen_module
ImportError: No module named 
```

*C:\salt\salt-call.exe --local --versions*:

```
           Salt: 2014.7.1
         Python: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]
         Jinja2: 2.7.1
       M2Crypto: 0.21.1
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.1.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
```

**Comment by jfindlay** [comment]
@lorengordon, thanks for the report.  It looks like the loader may be doing something that doesn't work on windows, or I could be completely wrong. :-)  In either case. we'll get this reviewed and fixed.

**Comment by deuscapturus** [comment]
I'm seeing the same thing with version 2014.7.1 on Windows 8.1.  Happens with "-l debug" flag during states with lots of output (like file extraction).  Using "--returner local" fixes it.

**Comment by jfindlay** [comment]
@jacksontj, @cachedout

**Comment by lorengordon** [comment]
Thanks @deuscapturus. Seems odd that using `salt-call.exe --local` wouldn't imply `--returner local` but I'll give that a shot later.

**Comment by jacksontj** [comment]
Interesting error, is something cut off? "no module named" usually has a module name afterwards :)

This is in the old loader (pre-lazy loader), so I'm not sure how much help I'll be. Also, only reproducible on Windows?

**Comment by lorengordon** [comment]
@jacksontj, that is literally the end of the log. I snipped only entries preceding this message...

I haven't been working with anything other than Windows, so can't really say whether it's reproducible on another OS.

**Comment by jacksontj** [comment]
Fun one actually, I can easily reproduce this if there is a file with a name which is *only* whitespace. Is that the case?

**Comment by lorengordon** [comment]
No, I don't think so. All my files have filenames with alpha-numeric characters. But...to what file might you be referring? An sls file? A log file? I find the error in the log-output file if I've specified one or otherwise in the default minion log file...

**Comment by deuscapturus** [comment]
@lorengordon Just to clarify.  I wasn't running --local, but --returner local did help.

**Comment by jacksontj** [comment]
@lorengordon It would be a returner module.


The specific section of code is here: https://github.com/saltstack/salt/blob/2014.7/salt/loader.py#L624

The only way I can reproduce that is with a modulename of whitespace:

```
>>> import imp
>>> imp.find_module(' ')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named  
```

**Comment by lorengordon** [comment]
@jacksontj, is it possible that on Windows there is a path issue escaping the backslashes at that point in the code? Perhaps the module can't be found because the value being passed isn't quoted properly for Windows? I don't know. 

But the suggestion to use `--return local` did fix the issue. If I run state.highstate with `--return local` then no issue. If I run state.highstate again without --return local, then I get the ImportError at the end of the log.

I can even confirm it with a state as simple as this `test.sls`:
```
PS C:\Users\Administrator\Downloads> type C:\salt\file_roots\base\test.sls
always-passes:
  test.succeed_without_changes:
    - name: foo
```

Running the state without `--return local`:
```
C:\salt\salt-call.exe --local state.sls test --log-file .\test.1.log --log-file-level debug
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://test.sls'
[INFO    ] Running state [foo] at time 22:10:19.062000
[INFO    ] Executing state test.succeed_without_changes for foo
[INFO    ] Success!
[INFO    ] Completed state [foo] at time 22:10:19.062000
[INFO    ] Executing command ['attrib', '-R', 'c:\\salt\\var\\cache\\salt\\minion\\sls.p'] in directory 'C:\\Users\\Administrator'
local:
----------
          ID: always-passes
    Function: test.succeed_without_changes
        Name: foo
      Result: True
     Comment: Success!
     Started: 22:10:19.062000
    Duration: 0.0 ms
     Changes:

Summary
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
```

Contents of `test.1.log`:
```
PS C:\Users\Administrator\Downloads> type test.1.log
2015-02-13 22:10:15,078 [salt.config      ][DEBUG   ] Reading configuration from c:\salt\conf\minion
2015-02-13 22:10:15,547 [salt.cloud       ][DEBUG   ] Mako not available
2015-02-13 22:10:16,906 [salt.fileserver  ][DEBUG   ] Updating fileserver cache
2015-02-13 22:10:16,984 [salt.config      ][DEBUG   ] Reading configuration from c:\salt\conf\minion
2015-02-13 22:10:18,203 [salt.state       ][INFO    ] Loading fresh modules for state activity
2015-02-13 22:10:19,047 [salt.fileclient  ][INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://test.sls'
2015-02-13 22:10:19,062 [salt.utils.jinja ][DEBUG   ] Jinja search path: ['C:\\salt\\file_roots\\base', 'C:\\salt\\file_roots\\winrepo', 'C:\\salt\\formulas\\ash-windows-formula', 'C:\\salt\\formulas\\dotnet4-formula', 'C:\\salt\\formulas\\emet-formula', 'C:\\salt\\formulas\\netbanner-formula']
2015-02-13 22:10:19,062 [salt.template    ][DEBUG   ] Rendered data from file: c:\salt\var\cache\salt\minion\files\base\test.sls:
always-passes:
  test.succeed_without_changes:
    - name: foo
2015-02-13 22:10:19,062 [salt.loaded.int.render.yaml][DEBUG   ] Results of YAML rendering:
OrderedDict([('always-passes', OrderedDict([('test.succeed_without_changes', [OrderedDict([('name', 'foo')])])]))])
2015-02-13 22:10:19,062 [salt.state       ][INFO    ] Running state [foo] at time 22:10:19.062000
2015-02-13 22:10:19,062 [salt.state       ][INFO    ] Executing state test.succeed_without_changes for foo
2015-02-13 22:10:19,062 [salt.state       ][INFO    ] Success!
2015-02-13 22:10:19,062 [salt.state       ][INFO    ] Completed state [foo] at time 22:10:19.062000
2015-02-13 22:10:19,062 [salt.loaded.int.module.cmdmod][INFO    ] Executing command ['attrib', '-R', 'c:\\salt\\var\\cache\\salt\\minion\\sls.p'] in directory 'C:\\Users\\Administrator'
2015-02-13 22:10:19,078 [salt.loaded.int.module.cmdmod][DEBUG   ] output:
2015-02-13 22:10:19,078 [salt.loader      ][DEBUG   ] Failed to import returner :
Traceback (most recent call last):
  File "salt/loader.py", line 621, in gen_module
ImportError: No module named
```

Running the state with `--return local`:
```
PS C:\Users\Administrator\Downloads> C:\salt\salt-call.exe --local state.sls test --log-file .\test.2.log --log-file-level debug --return local
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://test.sls'
[INFO    ] Running state [foo] at time 22:14:11.172000
[INFO    ] Executing state test.succeed_without_changes for foo
[INFO    ] Success!
[INFO    ] Completed state [foo] at time 22:14:11.187000
[INFO    ] Executing command ['attrib', '-R', 'c:\\salt\\var\\cache\\salt\\minion\\sls.p'] in directory 'C:\\Users\\Administrator'
{'fun_args': ['test'], 'jid': '20150213221409016000', 'return': {'test_|-always-passes_|-foo_|-succeed_without_changes': {'comment': 'Success!', 'name': 'foo', 'start_time': '22:14:11.172000', 'result': True, 'duration': 15.0, '__run_num__': 0, 'changes': {}}}, 'retcode': 0, 'success': True, 'fun': 'state.sls', 'id': 'WIN-8CMGF1AES89.us-west-2.compute.internal', 'out': 'highstate'}
local:
----------
          ID: always-passes
    Function: test.succeed_without_changes
        Name: foo
      Result: True
     Comment: Success!
     Started: 22:14:11.172000
    Duration: 15.0 ms
     Changes:

Summary
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
```

Contents of `test.2.log`:
```
PS C:\Users\Administrator\Downloads> type test.2.log
2015-02-13 22:14:07,109 [salt.config      ][DEBUG   ] Reading configuration from c:\salt\conf\minion
2015-02-13 22:14:07,594 [salt.cloud       ][DEBUG   ] Mako not available
2015-02-13 22:14:09,016 [salt.fileserver  ][DEBUG   ] Updating fileserver cache
2015-02-13 22:14:09,094 [salt.config      ][DEBUG   ] Reading configuration from c:\salt\conf\minion
2015-02-13 22:14:10,328 [salt.state       ][INFO    ] Loading fresh modules for state activity
2015-02-13 22:14:11,172 [salt.fileclient  ][INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://test.sls'
2015-02-13 22:14:11,172 [salt.utils.jinja ][DEBUG   ] Jinja search path: ['C:\\salt\\file_roots\\base', 'C:\\salt\\file_roots\\winrepo', 'C:\\salt\\formulas\\ash-windows-formula', 'C:\\salt\\formulas\\dotnet4-formula', 'C:\\salt\\formulas\\emet-formula', 'C:\\salt\\formulas\\netbanner-formula']
2015-02-13 22:14:11,172 [salt.template    ][DEBUG   ] Rendered data from file: c:\salt\var\cache\salt\minion\files\base\test.sls:
always-passes:
  test.succeed_without_changes:
    - name: foo
2015-02-13 22:14:11,172 [salt.loaded.int.render.yaml][DEBUG   ] Results of YAML rendering:
OrderedDict([('always-passes', OrderedDict([('test.succeed_without_changes', [OrderedDict([('name', 'foo')])])]))])
2015-02-13 22:14:11,172 [salt.state       ][INFO    ] Running state [foo] at time 22:14:11.172000
2015-02-13 22:14:11,172 [salt.state       ][INFO    ] Executing state test.succeed_without_changes for foo
2015-02-13 22:14:11,172 [salt.state       ][INFO    ] Success!
2015-02-13 22:14:11,187 [salt.state       ][INFO    ] Completed state [foo] at time 22:14:11.187000
2015-02-13 22:14:11,187 [salt.loaded.int.module.cmdmod][INFO    ] Executing command ['attrib', '-R', 'c:\\salt\\var\\cache\\salt\\minion\\sls.p'] in directory 'C:\\Users\\Administrator'
2015-02-13 22:14:11,187 [salt.loaded.int.module.cmdmod][DEBUG   ] output:
2015-02-13 22:14:11,187 [salt.loader      ][DEBUG   ] LazyLoaded local.returner
```

**Comment by jacksontj** [comment]
Definitely could be it. Do you have an ext_returner defined on the minion or master? Either of those would cause the minion to use the defined returner-- which could have escaping problems. And since specifying it manually fixes it that sounds promising.

**Comment by lorengordon** [comment]
No, no ext_returner defined anywhere. It's a masterless Windows minion. That setting is whatever the default is.

On Linux, the same test case doesn't result in a Traceback in the output, so perhaps more evidence of a Windows-specific issue somewhere...
```
# cat test.1.log
2015-02-18 22:31:13,822 [salt.config      ][DEBUG   ] Reading configuration from /etc/salt/minion
2015-02-18 22:31:13,892 [salt.loaded.int.grain.core][DEBUG   ] The `lspci` binary is not available on the system. GPU grains will not be available.
2015-02-18 22:31:13,988 [salt.cloud       ][DEBUG   ] Mako not available
2015-02-18 22:31:14,518 [salt.config      ][DEBUG   ] Reading configuration from /etc/salt/minion
2015-02-18 22:31:14,585 [salt.loaded.int.grain.core][DEBUG   ] The `lspci` binary is not available on the system. GPU grains will not be available.
2015-02-18 22:31:14,741 [salt.state       ][INFO    ] Loading fresh modules for state activity
2015-02-18 22:31:14,918 [salt.fileclient  ][INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://testdebug.sls'
2015-02-18 22:31:14,920 [salt.utils.jinja ][DEBUG   ] Jinja search path: ['/srv/salt/base', '/srv/saltformulas/ash-linux-formula']
2015-02-18 22:31:14,923 [salt.template    ][DEBUG   ] Rendered data from file: /var/cache/salt/minion/files/base/testdebug.sls:
always-passes:
  test.succeed_without_changes:
    - name: foo

2015-02-18 22:31:14,925 [salt.loaded.int.render.yaml][DEBUG   ] Results of YAML rendering:
OrderedDict([('always-passes', OrderedDict([('test.succeed_without_changes', [OrderedDict([('name', 'foo')])])]))])
2015-02-18 22:31:14,925 [salt.state       ][INFO    ] Running state [foo] at time 22:31:14.925094
2015-02-18 22:31:14,925 [salt.state       ][INFO    ] Executing state test.succeed_without_changes for foo
2015-02-18 22:31:14,926 [salt.state       ][INFO    ] Success!
2015-02-18 22:31:14,926 [salt.state       ][INFO    ] Completed state [foo] at time 22:31:14.925735
2015-02-18 22:31:14,927 [salt.loader      ][DEBUG   ] LazyLoaded .returner
```

**Comment by jfindlay** [comment]
This is the causal code from [loader.py](https://github.com/saltstack/salt/blob/v2014.7.1/salt/loader.py#L621)
```python
            if full.endswith('.pyx') and cython_enabled:
                # If there's a name which ends in .pyx it means the above
                # cython_enabled is True. Continue...
                mod = pyximport.load_module(name, full, tempfile.gettempdir())
            else:
                fn_, path, desc = imp.find_module(name, self.module_dirs)
                mod = imp.load_module(
                    '{0}.{1}.{2}.{3}'.format(
                        self.loaded_base_name,
                        self.mod_type_check(path),
                        self.tag,
                        name
                    ), fn_, path, desc
                )
```

If you're feeling up to it, you could insert some debug code in there and try
to find out why `imp.find_module` is importing a module with name of either
whitespace, or `''`.

**Comment by jfindlay** [comment]
Also, it might be interesting to try to narrow down which actions cause the traceback.

**Comment by jacksontj** [comment]
Yea, this does sound like some escaping issue or something in windows. From
looking at the code the best I can come up with is that there is something
which causes "full" to be set (
https://github.com/saltstack/salt/blob/2014.7/salt/loader.py#L587) which
ends up with the loader attempting to load it (
https://github.com/saltstack/salt/blob/2014.7/salt/loader.py#L624). I don't
have any windows machines to debug this on, so its hard to get much deeper
:/

**Comment by lorengordon** [comment]
@jfindlay, @jacksontj, I can dig into the code some next week perhaps. Plate is full the next couple days and this one is pretty low priority for me, considering the workaround is easy and has no impact to my use case.

I just spin up an EC2 micro instance to play with Windows minions, or sometimes a VMware Player machine. They're really making it easy these days!

**Comment by lorengordon** [comment]
Well, I finally got around to fiddling with this, but I'm not really sure about all the relationships between python modules so I'm sure how it's *supposed* to be working, so it's really slow going. All I know right now is that `gen_module` is being called with `name = ''` by something (I tested for `name is ''`), but I don't know what is calling the function. Also, `full` is set to `C:\salt\salt-2014.7.2.win-amd64\salt-2014.7.2-py2.7.egg\salt\returners\` and so doesn't end in `.pyx` which is why the function is getting to the code that's causing the traceback.

Also, if I pass `--return local` to salt-call, then `name = local` instead of `''`.

Can someone point me in the right direction for what might be calling `gen_module`?

**Comment by lorengordon** [comment]
Ok, I added debug statements everywhere in the codebase that `gen_module` was used and traced the calling function to the invocation in the `_load()` function of the `LazyLoader()` class.

https://github.com/saltstack/salt/blob/2014.7/salt/loader.py#L1320

So I added another debug statement to get the value of the `key` parameter, and it gave me the value of `.returner`. The line that sets `mod_key` (which is what's passed to `gen_module`) is [this](https://github.com/saltstack/salt/blob/2014.7/salt/loader.py#L1315):

```python
        mod_key = key.split('.', 1)[0]
```

That results in `mod_key = ''`, which gets passed to the `name` parameter of `gen_module()`. And then `gen_module()` attempts to execute `imp.find_module(name)`, which results in the traceback.

I don't think I've yet found an explanation of why this behavior occurs on Windows and not Linux, though. I can maybe try to debug the execution on a Linux system, as well. My best guess right now is that Linux systems aren't getting to that section of code at [line 624](https://github.com/saltstack/salt/blob/2014.7/salt/loader.py#L624) where it would attempt to execute  `imp.find_module('')`.

**Comment by jacksontj** [comment]
@lorengordon AWESOME! That was enough to track down the issue. Basically if you have a minion which has *no* 'return' configured, you end up with a list of returners of [''] (list of just empty string-- https://github.com/saltstack/salt/blob/2014.7/salt/cli/caller.py#L165). This in turn calls
```
'{0}.returner'.format('')
```
Which would account for that coming in blank. Apparently I had already fixed this a while ago in d8bbce2. I just opened a PR to backport of this fix (#21395)

That will help track it down more. It seems lik

**Comment by lorengordon** [comment]
Cool, I popped that change into caller.py on my 2014.7 Windows minion and it did indeed resolve the traceback error. That seems to skip the return function entirely? Is that right?

Any clues that might explain the difference between Windows and Linux? Linux seems to LazyLoad '.returner' just fine, but Windows doesn't like it at all.

**Comment by jacksontj** [comment]
Yea, the intent is to skip the returner all together, since there isn't one :)

As for why windows but not linux, no idea. I did a little looking, but it doesn't fail the same way in linux-- It seems like the loader is fine with importing the "returners" directory as an empty dir. It might have something to do with os.path.join() doing something different. But since its fixed and I don't really run windows I won't look into it anymore.

**Comment by lorengordon** [comment]
Closed, fixed in https://github.com/saltstack/salt/pull/21395.
