### ISSUE TITLE
Salt-driven HTTPS requests fail with SSLError x509 certificate errors

### ISSUE THREAD

**Issue by eliasp** [saltstack/salt#20502]
**OS:** Windows 7 x64 Enterprise en_US
**Salt:**
```
               Salt: 2014.7.1
             Python: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]
             Jinja2: 2.7.1
           M2Crypto: 0.21.1
     msgpack-python: 0.4.2
       msgpack-pure: Not Installed
           pycrypto: 2.6
            libnacl: Not Installed
             PyYAML: 3.11
              ioflo: Not Installed
              PyZMQ: 14.1.1
               RAET: Not Installed
                ZMQ: 4.0.4
               Mako: Not Installed
```

Running this:
```
salt some-windows-minion cp.get_url https://docs.saltstack.com/downloads/Salt-Minion-2014.7.1-AMD64-Setup.exe 'C:\windows\temp\Salt-Minion-2014.7.1-AMD64-Setup.exe'
```
Ends up in this:
```
    The minion function caused an exception: Traceback (most recent call last):
      File "salt/minion.py", line 1022, in _thread_return
      File "salt/modules/cp.py", line 272, in get_url
      File "salt/fileclient.py", line 592, in get_url
      File "requests/api.py", line 55, in get
      File "requests/api.py", line 44, in request
      File "requests/sessions.py", line 456, in request
      File "requests/sessions.py", line 559, in send
      File "requests/adapters.py", line 382, in send
    SSLError: [Errno 185090050] _ssl.c:340: error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib
```

**Comment by jfindlay** [comment]
@eliasp, thanks for the report.

**Comment by UtahDave** [comment]
I think I've got the fix in for this. We're testing the fix today.

**Comment by jfindlay** [comment]
@UtahDave do you know the issue number?

**Comment by eliasp** [comment]
There was a similar issue (from which I copied the title) filed under #16773 - but this one was related to thin dists and it looked to me like this is a different issue here and therefore filed this separate issue.

**Comment by twangboy** [comment]
I believe this has been fixed with https://github.com/saltstack/salt/pull/21960
