### ISSUE TITLE
`modules.win_pkg.install()` blindly trusts `fileclient.get_url()`/unhandled exceptions

### ISSUE THREAD

**Issue by eliasp** [saltstack/salt#20522]
**OS:** Windows 7 Enterprise x64 en_US
**Salt:**
```
               Salt: 2014.7.1
             Python: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]
             Jinja2: 2.7.1
           M2Crypto: 0.21.1
     msgpack-python: 0.4.2
       msgpack-pure: Not Installed
           pycrypto: 2.6
            libnacl: Not Installed
             PyYAML: 3.11
              ioflo: Not Installed
              PyZMQ: 14.1.1
               RAET: Not Installed
                ZMQ: 4.0.4
               Mako: Not Installed
```

`fileclient.get_url()` raises a `MinionError` exception in case an HTTP download failed (e.g. `404`).
This seems to be ignored by `modules.win_pkg.install()` which just blindly continues its process even when the installer download failed.

Example:
**win_repo for adobe.flash:**
```SLS
adobe.flash:
    15.0.0.152:
        # invalid URL, results in a 404 but still a downloaded 270B file with some 404-message HTML
        installer: http://download.macromedia.com/get/flashplayer/current/licensing/win/install_flash_player_15_plugin.msi
        full_name: 'Adobe Flash Player 15 Plugin'
        install_flags: ' /q'
        msiexec: True
        reboot: False
        uninstaller: http://download.macromedia.com/get/flashplayer/current/support/uninstall_flash_player.exe
```
**pkg.install adobe.flash:**
```
    [INFO    ] Starting new HTTP connection (1): download.macromedia.com
    [DEBUG   ] "GET /get/flashplayer/current/licensing/win/install_flash_player_15_plugin.msi HTTP/1.1" 302 289
    [INFO    ] Starting new HTTP connection (1): fpdownload.macromedia.com
    [DEBUG   ] "GET /get/flashplayer/current/licensing/win/install_flash_player_15_plugin.msi HTTP/1.1" 404 270
    [WARNING ] Specified file http://download.macromedia.com/get/flashplayer/current/licensing/win/install_flash_player_15_plugin.msi is not present to generate hash
    [INFO    ] Starting new HTTP connection (1): download.macromedia.com
    [DEBUG   ] "GET /get/flashplayer/current/licensing/win/install_flash_player_15_plugin.msi HTTP/1.1" 302 289
    [INFO    ] Starting new HTTP connection (1): fpdownload.macromedia.com
    [DEBUG   ] "GET /get/flashplayer/current/licensing/win/install_flash_player_15_plugin.msi HTTP/1.1" 404 270
    [INFO    ] Executing command ['msiexec', '/i', 'c:\\salt\\var\\cache\\salt\\minion\\extrn_files\\base\\download.macromedia.com\\get\\flashplayer\\current\\licensing\\win\\install_flash_player_15_plugin.msi', '/q'] in directory 'C:\\Windows\\system32\\config\\systemprofile'
    [ERROR   ] Command ['msiexec', '/i', 'c:\\salt\\var\\cache\\salt\\minion\\extrn_files\\base\\download.macromedia.com\\get\\flashplayer\\current\\licensing\\win\\install_flash_player_15_plugin.msi', '/q'] failed with return code: 1620
    [ERROR   ] output: This installation package could not be opened.  Contact the application vendor to verify that this is a valid Windows Installer package.
```

The call chain is:
* `salt.modules.win_pkg.install()`
* `salt.modules.cp.cache_file()`
* `salt.fileclient.cache_file()`
* `salt.fileclient.get_url()` ← raises `MinionError` exception in case of an `HTTPError` or `URLError` exception

**Comment by UtahDave** [comment]
Ah, good catch. Thanks!

**Comment by twangboy** [comment]
@eliasp I believe this has been fixed. In 2015.5 the following error is returned:
```
The minion function caused an exception: Traceback (most recent call last):
      File "c:\salt-dev\salt\salt\minion.py", line 1173, in _thread_return
        return_data = func(*args, **kwargs)
      File "c:\salt-dev\salt\salt\modules\win_pkg.py", line 468, in install
        cached_pkg = __salt__['cp.cache_file'](installer, saltenv)
      File "c:\salt-dev\salt\salt\modules\cp.py", line 367, in cache_file
        result = __context__['cp.fileclient'].cache_file(path, saltenv)
      File "c:\salt-dev\salt\salt\fileclient.py", line 153, in cache_file
        return self.get_url(path, '', True, saltenv)
      File "c:\salt-dev\salt\salt\fileclient.py", line 627, in get_url
        *BaseHTTPServer.BaseHTTPRequestHandler.responses[exc.code]))
    MinionError: HTTP error 404 reading http://download.macromedia.com/get/flashplayer/current/licensing/win/install_flash_layer_15_plugin.msi: Nothing matches the given URI
```

in 2015.8:
```

**Comment by eliasp** [comment]
Great! Thanks a lot!

**Comment by twangboy** [comment]
@eliasp The above PR will keep it from stack tracing.
