### ISSUE TITLE
Volume support stacktracing on ec2

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt#20614]
When trying to provision a VM on EC2 using salt-cloud that has a volume defined in the cloud profile, it fails with the following stacktrace:
```
[DEBUG   ] Function: describe_volumes, Watched arg: status, Response: available
[ERROR   ] There was a profile error: string indices must be integers, not str
Traceback (most recent call last):
  File "/root/SaltStack/salt/salt/cloud/cli.py", line 254, in run
    self.config.get('names')
  File "/root/SaltStack/salt/salt/cloud/__init__.py", line 1370, in run_profile
    ret[name] = self.create(vm_)
  File "/root/SaltStack/salt/salt/cloud/__init__.py", line 1240, in create
    output = self.clouds[func](vm_)
  File "/root/SaltStack/salt/salt/cloud/clouds/ec2.py", line 2220, in create
    call='action'
  File "/root/SaltStack/salt/salt/cloud/clouds/ec2.py", line 2317, in create_attach_volumes
    volume_dict['volume_id'] = item['volumeId']
TypeError: string indices must be integers, not str
```
Relevant cloud profile information:
```
ec2-ubuntu-14:
  image: ami-98aa1cf0
  size: t1.micro
  sh_username: ec2-user
  volumes:
    - { size: 10, device: /dev/sdf }
  provider: ec2-config
```
Versions report:
```
# salt --versions
           Salt: 2015.2.0rc1-1-g009dc57
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.4
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
```

**Comment by rallytime** [comment]
It should be noted that the VMs do get created on ec2, but it doesn't appear that way from the CLI since it stacktraces and exits. When I do a `salt-cloud -d <vm-name-that-failed>`, it correctly finds the VMs on EC2 and deletes them.

**Comment by petertilsen** [comment]
same issue here. any changes on that?

```
salt --versions-report
           Salt: 2015.2.0rc2
         Python: 2.6.6 (r266:84292, Nov 21 2013, 10:50:32)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.4.4
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
```

```
cat /proc/version
Linux version 2.6.32-431.11.2.el6.x86_64 (mockbuild@x86-027.build.eng.bos.redhat.com) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-4) (GCC) ) #1 SMP Mon Mar 3 13:32:45 EST 2014
```

my python version is for sure not up to date, but I don't see any connection to that.

**Comment by rallytime** [comment]
Thanks for the update, @petertilsen! Yes, this is still an issue. I don't think anyone got a chance to look at this bug yet.

**Comment by zeroedin-bill** [comment]
@rallytime @petertilsen @cro This bug is solved in #19315 which was merged to develop but not to 2015.2.

**Comment by rallytime** [comment]
Thanks for finding taht @zeroedin-bill! I've marked the pull request for backporting.

**Comment by zeroedin-bill** [comment]
@rallytime happy to donate an hour of my day to such a useful project :+1:

**Comment by rallytime** [comment]
I can confirm that the backport fixes this bug. Closing.

**Comment by petertilsen** [comment]
Great! Thank you! @zeroedin-bill
