### ISSUE TITLE
2015.2.0rc1 - pip.installed "TypeError: 'bool' object is not iterable"

### ISSUE THREAD

**Issue by alex-solidfire** [saltstack/salt#20651]
We are currently still using 2014.1.13 and seeing this exception with the new release candidate:
```
Function: pip.installed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1551, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/states/pip_state.py", line 645, in installed
                  use_vt=use_vt
                File "/usr/lib/python2.7/dist-packages/salt/modules/pip.py", line 558, in install
                  for pkg in allow_unverified:
              TypeError: 'bool' object is not iterable
```

Our state looks like this:
```
pip.installed:
        - requirements: /hg/autoplatform/scripts/requirements.txt
        - upgrade: True
        - require:
            - pkg: qd-pip-pkgs
```

**Comment by jfindlay** [comment]
@alex-solidfire, thanks for reporting.  I spent some time on this yesterday
and was not able to reproduce it.  It seems impossible for the pip state to
trigger the stack trace you're reporting because if `allow_unverified` is
unused as it is in your example, then it's going to be `None`.  The only way I
can construe the stack trace is that `allow_unverified` is being set to `True`
somehow.  Its truth value must evaluate to `True` to get into the conditional block starting at
salt/modules/pip.py:554 and then it must be a boolean at
salt/modules/pip.py:588.  The only type that I know of to fulfill both of
these condition is `True`, but `allow_unverified` is always `None` if it's
unused.  Do you have any further ideas or information?

```grep
$ git grep -En -C 4 'allow_unverified' -- salt/
salt/modules/pip.py-167-            pre_releases=False,
salt/modules/pip.py-168-            cert=None,
salt/modules/pip.py-169-            allow_all_external=False,
salt/modules/pip.py-170-            allow_external=None,
salt/modules/pip.py:171:            allow_unverified=None,
salt/modules/pip.py-172-            process_dependency_links=False,
salt/modules/pip.py-173-            __env__=None,
salt/modules/pip.py-174-            saltenv='base',
salt/modules/pip.py-175-            env_vars=None,
--
salt/modules/pip.py-280-    allow_all_external
salt/modules/pip.py-281-        Allow the installation of all externally hosted files
salt/modules/pip.py-282-    allow_external
salt/modules/pip.py-283-        Allow the installation of externally hosted files (comma separated list)
salt/modules/pip.py:284:    allow_unverified
salt/modules/pip.py-285-        Allow the installation of insecure and unverifiable files (comma separated list)
salt/modules/pip.py-286-    process_dependency_links
salt/modules/pip.py-287-        Enable the processing of dependency links
salt/modules/pip.py-288-    use_vt
--
salt/modules/pip.py-550-
salt/modules/pip.py-551-        for pkg in allow_external:
salt/modules/pip.py-552-            cmd.append('--allow-external {0}'.format(pkg))
salt/modules/pip.py-553-
salt/modules/pip.py:554:    if allow_unverified:
salt/modules/pip.py:555:        if isinstance(allow_unverified, string_types):
salt/modules/pip.py:556:            allow_unverified = [p.strip() for p in allow_unverified.split(',')]
salt/modules/pip.py-557-
salt/modules/pip.py:558:        for pkg in allow_unverified:
salt/modules/pip.py-559-            cmd.append('--allow-unverified {0}'.format(pkg))
salt/modules/pip.py-560-
salt/modules/pip.py-561-    if process_dependency_links:
salt/modules/pip.py-562-        cmd.append('--process-dependency-links')
--
salt/states/pip_state.py-228-              pre_releases=False,
salt/states/pip_state.py-229-              cert=None,
salt/states/pip_state.py-230-              allow_all_external=False,
salt/states/pip_state.py-231-              allow_external=None,
salt/states/pip_state.py:232:              allow_unverified=None,
salt/states/pip_state.py-233-              process_dependency_links=False,
salt/states/pip_state.py-234-              env_vars=None,
salt/states/pip_state.py-235-              use_vt=False):
salt/states/pip_state.py-236-    '''
--
salt/states/pip_state.py-361-
salt/states/pip_state.py-362-    allow_external
salt/states/pip_state.py-363-        Allow the installation of externally hosted files (comma separated list)
salt/states/pip_state.py-364-
salt/states/pip_state.py:365:    allow_unverified
salt/states/pip_state.py-366-        Allow the installation of insecure and unverifiable files (comma separated list)
salt/states/pip_state.py-367-
salt/states/pip_state.py-368-    process_dependency_links
salt/states/pip_state.py-369-        Enable the processing of dependency links
--
salt/states/pip_state.py-637-        pre_releases=pre_releases,
salt/states/pip_state.py-638-        cert=cert,
salt/states/pip_state.py-639-        allow_all_external=allow_all_external,
salt/states/pip_state.py-640-        allow_external=allow_external,
salt/states/pip_state.py:641:        allow_unverified=allow_unverified,
salt/states/pip_state.py-642-        process_dependency_links=process_dependency_links,
salt/states/pip_state.py-643-        saltenv=__env__,
salt/states/pip_state.py-644-        env_vars=env_vars,
salt/states/pip_state.py-645-        use_vt=use_vt
```

**Comment by alex-solidfire** [comment]
@jfindlay Thanks for your reply.  I really apologize, we have many states with pip and i pasted the wrong one into this issue.

Below is the state, we are using allow_unverified, as well as a virtualenv:

```
pip.installed:
        - user: www-data
        - requirements: /var/www/autoplatform/labdesk/deploy/requirements.txt
        - bin_env: {{ bin_env }}
        - allow_all_external: True
        - allow_unverified: True
        - process_dependency_links: True
        - require:
            - pip: labdesk-pip-setuptools
```

**Comment by jfindlay** [comment]
@alex-solidfire, no problem.  Thanks for the new state, that makes much more sense.  The problem that I see now is that allow_unverified must be supplied the package name(s) that are allowed to be installed unverified, according to the [pip docs](http://pip.readthedocs.org/en/latest/reference/pip_wheel.html#allow-unverified).

**Comment by alex-solidfire** [comment]
Great, it seems I was using this improperly all along and it just didn't throw the exception in the older version, sorry for the noise.  Your help is appreciated.
