### ISSUE TITLE
salt 2014.7.2 won't build on opensuse Factory and Tumbleweed

### ISSUE THREAD

**Issue by aboe76** [saltstack/salt#20660]
I need some help tracing the issue on Opensuse during building of the salt packages.

Something changed in opensuse Factory and Tumbleweed which prevents salt packages to be build.
On opensuse 12.3 till 13.2 and Enterprise SP3 the salt 2014.7.2 builds are ok.

See failed on:
https://build.opensuse.org/package/show/home:aboe76:branches:devel:languages:python/salt

traceback
```
[   67s] Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.TkV9OA
[   67s] + umask 022
[   67s] + cd /home/abuild/rpmbuild/BUILD
[   67s] + /usr/bin/rm -rf /home/abuild/rpmbuild/BUILDROOT/salt-2014.7.2-186.1.i386
[   67s] ++ dirname /home/abuild/rpmbuild/BUILDROOT/salt-2014.7.2-186.1.i386
[   67s] + /usr/bin/mkdir -p /home/abuild/rpmbuild/BUILDROOT
[   67s] + /usr/bin/mkdir /home/abuild/rpmbuild/BUILDROOT/salt-2014.7.2-186.1.i386
[   67s] + cd salt-2014.7.2
[   67s] + python setup.py build
[   67s] Traceback (most recent call last):
[   67s]   File "setup.py", line 112, in <module>
[   67s]     exec(compile(open(SALT_VERSION).read(), SALT_VERSION, 'exec'))
[   67s]   File "/home/abuild/rpmbuild/BUILD/salt-2014.7.2/salt/version.py", line 13, in <module>
[   67s]     from salt._compat import string_types
[   67s]   File "/home/abuild/rpmbuild/BUILD/salt-2014.7.2/salt/__init__.py", line 44, in <module>
[   67s]     from salt.utils import migrations
[   67s]   File "/home/abuild/rpmbuild/BUILD/salt-2014.7.2/salt/utils/__init__.py", line 103, in <module>
[   67s]     import salt.payload
[   67s]   File "/home/abuild/rpmbuild/BUILD/salt-2014.7.2/salt/payload.py", line 14, in <module>
[   67s]     import salt.crypt
[   67s]   File "/home/abuild/rpmbuild/BUILD/salt-2014.7.2/salt/crypt.py", line 21, in <module>
[   67s]     from M2Crypto import RSA, EVP
[   67s]   File "/usr/lib/python2.7/site-packages/M2Crypto/__init__.py", line 24, in <module>
[   67s]     import ASN1
[   67s]   File "/usr/lib/python2.7/site-packages/M2Crypto/ASN1.py", line 12, in <module>
[   67s]     import BIO
[   67s]   File "/usr/lib/python2.7/site-packages/M2Crypto/BIO.py", line 221, in <module>
[   67s]     class CipherStream(BIO):
[   67s]   File "/usr/lib/python2.7/site-packages/M2Crypto/BIO.py", line 227, in CipherStream
[   67s]     SALT_LEN = m2.PKCS5_SALT_LEN
[   67s] AttributeError: 'module' object has no attribute 'PKCS5_SALT_LEN'
[   67s] error: Bad exit status from /var/tmp/rpm-tmp.TkV9OA (%build)
```

**Comment by jfindlay** [comment]
@basepi, this looks like it might have been triggered by version changes.  Or it might be an issue with m2crypto.

**Comment by aboe76** [comment]
the strangest thing is that my2crypto that is used, didn't change in the last 10 months...

**Comment by aboe76** [comment]
Issue is within Tumbleweed/Factory on Opensuse/Suse, nothing to do with salt.
somewhere within python-M2crypto or it depencies something is missing...

https://build.opensuse.org/package/show/devel:languages:python/python-M2Crypto

**Comment by rallytime** [comment]
Thanks for the update @aboe76. I've marked this as a upstream bug.

**Comment by aboe76** [comment]
upstream has fixed the bug:
https://build.opensuse.org/request/show/287536

so closing the issue.
looks like everything is building again:
https://build.opensuse.org/request/show/287412

**Comment by rallytime** [comment]
Awesome! Thanks @aboe76!
