### ISSUE TITLE
external_auth PAM Fails of salt-master run as non-root

### ISSUE THREAD

**Issue by twellspring** [saltstack/salt#20720]
When trying to authenticate via external auth, I am getting 'Authentication failure of type "eauth".  This happens both with a curl or a salt -a.

twells@salter:~/bin$ cat /etc/salt/master.d/
 rest_cherrypy:
   port: 8000
   ssl_crt: /etc/salt/pki/tls/certs/saltapi.crt
   ssl_key: /etc/salt/pki/tls/certs/saltapi.key
   debug: True

 external_auth:
   pam:
     apiclient:
       - .*
       - '@wheel'
       - '@runner'
       - '@jobs'
twells@salter:~/bin$ salt -a pam salt-test2 test.ping
username: apiclient
password:
Failed to authenticate!  This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).
twells@salter:~/bin$ su - apiclient
Password:
$ exit
logout

twells@salter:~/bin$ curl -ksi https://localhost:8000/login \
> -H "Accept: application/json" \
> -d username='apiclient' \
> -d password='XXXXXXX' \
> -d eauth='pam'
HTTP/1.1 401 Unauthorized
Content-Length: 1592
Vary: Accept-Encoding
Server: CherryPy/3.2.2
Allow: GET, HEAD, POST
Date: Mon, 16 Feb 2015 09:22:13 GMT
Access-Control-Allow-Origin: *
Content-Type: text/html;charset=utf-8
Set-Cookie: session_id=ec98b5f114d5fa471643b230f803510c72476749; expires=Mon, 16 Feb 2015 19:22:13 GMT; Path=/

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>401 Unauthorized</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>401 Unauthorized</h2>
        <p>Could not authenticate using provided credentials</p>
        <pre id="traceback">Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/saltapi/netapi/rest_cherrypy/app.py", line 292, in hypermedia_handler
    ret = cherrypy.serving.request._hypermedia_inner_handler(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/dist-packages/saltapi/netapi/rest_cherrypy/app.py", line 1001, in POST
    'Could not authenticate using provided credentials')
HTTPError: (401, 'Could not authenticate using provided credentials')
</pre>
    <div id="powered_by">
    <span>Powered by <a href="http://www.cherrypy.org">CherryPy 3.2.2</a></span>
    </div>
    </body>
</html>

Here is what shows in the master log
2015-02-16 09:17:59,352 [salt.master      ][INFO    ] Clear payload received with command publish
2015-02-16 09:17:59,352 [salt.utils       ][TRACE   ] Trying pysss.getgrouplist for 'apiclient'
2015-02-16 09:17:59,353 [salt.utils       ][TRACE   ] Trying generic group list for 'apiclient'
2015-02-16 09:17:59,353 [salt.utils       ][TRACE   ] Group list for user 'apiclient': ['apiclient']
2015-02-16 09:18:02,879 [salt.master      ][WARNING ] Authentication failure of type "eauth" occurred.

twells@salter:~/bin$ salt --versions-report
           Salt: 2014.7.0
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1

**Comment by twellspring** [comment]
twells@salter:~/bin$ salt --versions-report
           Salt: 2014.7.0
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1

**Comment by twellspring** [comment]
Just found this in the /var/log/auth.log.    Thinking this problem could be related to salt running as a non-root user.

Feb 16 15:31:12 salter unix_chkpwd[12941]: password check failed for user (apiclient)
Feb 16 15:31:12 salter python: pam_unix(login:auth): authentication failure; logname= uid=1001 euid=1001 tty= ruser= rhost=  user=apiclient

**Comment by twellspring** [comment]
I changed my config to run salt-master as root and authentication for both salt -a and the api via curl command work.    Changing title to better reflect problem. 

Is there a way to make this work with a non-root salt-master?

**Comment by twellspring** [comment]
Found node in "Running the Salt Master/Minion as an Unprivileged User" that said eAuth / PAM does not work with non-root salt-master.   Added a note on topics/eauth.  PR #20728
