### ISSUE TITLE
disk.usage broken on Synology os

### ISSUE THREAD

**Issue by jaymcconnell** [saltstack/salt#20790]
disk.usage module produces this traceback:

``` python
[INFO    ] Executing command 'df -P' in directory '/root'
[DEBUG   ] output: Filesystem           1024-blocks    Used Available Capacity Mounted on
/dev/md0               2451064    625076   1723588  27% /
/tmp                    507800       156    507644   0% /tmp
/run                    507800      2588    505212   1% /run
/dev/shm                507800         0    507800   0% /dev/shm
/dev/vg1/volume_1     59862956   1343792  58416764   2% /volume1
/dev/vg1/volume_2    1857813224 1539138956 318571868  83% /volume2
/volume1/@optware     59862956   1343792  58416764   2% /opt
/volume2/@nbu@       1857813224 1539138956 318571868  83% /volume2/nbu
/volume2/@Time-Machine-Backups@
                     1857813224 1539138956 318571868  83% /volume2/Time-Machine-Backups
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/local/salt-master/env/bin/salt-call", line 11, in <module>
    sys.exit(salt_call())
  File "/usr/local/salt-master/env/lib/python2.7/site-packages/salt/scripts.py", line 122, in salt_call
    client.run()
  File "/usr/local/salt-master/env/lib/python2.7/site-packages/salt/cli/__init__.py", line 419, in run
    caller.run()
  File "/usr/local/salt-master/env/lib/python2.7/site-packages/salt/cli/caller.py", line 225, in run
    ret = self.call()
  File "/usr/local/salt-master/env/lib/python2.7/site-packages/salt/cli/caller.py", line 129, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/local/salt-master/env/lib/python2.7/site-packages/salt/modules/disk.py", line 80, in usage
    while not comps[1].isdigit():
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/local/salt-master/env/bin/salt-call", line 11, in <module>
    sys.exit(salt_call())
  File "/usr/local/salt-master/env/lib/python2.7/site-packages/salt/scripts.py", line 122, in salt_call
    client.run()
  File "/usr/local/salt-master/env/lib/python2.7/site-packages/salt/cli/__init__.py", line 419, in run
    caller.run()
  File "/usr/local/salt-master/env/lib/python2.7/site-packages/salt/cli/caller.py", line 225, in run
    ret = self.call()
  File "/usr/local/salt-master/env/lib/python2.7/site-packages/salt/cli/caller.py", line 129, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/local/salt-master/env/lib/python2.7/site-packages/salt/modules/disk.py", line 80, in usage
    while not comps[1].isdigit():
IndexError: list index out of range
```

Seems to be because the df included in the distro has a fixed width and pushes some of the data to a new line when the device name is too long.

**Comment by jaymcconnell** [comment]
I hacked at salt/modules/disk.py and got it working https://gist.github.com/jaymcconnell/c5cf54bda8a483ddf74c

**Comment by jfindlay** [comment]
@jaymcconnell, looks good.  If you want to submit a pull request containing the changes you've made, please be sure to reference this issue in the commit message, thanks.

**Comment by jfindlay** [comment]
@jaymcconnell, is this bug still happening on 2015.5.0?

**Comment by jaymcconnell** [comment]
@jfindlay ,unfortunately cannot test at the moment, only package that's
easily installable is 2014.7.2. I should have my testing device back in the
next 2 weeks and will be able to test then.

**Comment by jodv** [comment]
I'm getting the same stacktrace on RHEL using Salt 2015.8.0, specifically when passing the 'human-readable' flag.   I haven't yet had time to investigate further.

```
$ sudo salt-call disk.usage h
[INFO    ] Executing command 'df -P -h' in directory '/root'
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 331, in salt_call
    client.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/call.py", line 51, in run
    caller.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/caller.py", line 133, in run
    ret = self.call()
  File "/usr/lib/python2.6/site-packages/salt/cli/caller.py", line 196, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/modules/disk.py", line 91, in usage
    while not comps[1].isdigit():
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 331, in salt_call
    client.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/call.py", line 51, in run
    caller.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/caller.py", line 133, in run
    ret = self.call()
  File "/usr/lib/python2.6/site-packages/salt/cli/caller.py", line 196, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/modules/disk.py", line 91, in usage
    while not comps[1].isdigit():
IndexError: list index out of range
```

**Comment by schemacs** [comment]
Still on 2015.8.1

```shell
root@133-130-98-214:~# salt '*' disk.usage
133-130-98-214:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1004, in _thread_return
        return_data = func(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/disk.py", line 91, in usage
        while not comps[1].isdigit():
    IndexError: list index out of range
root@133-130-98-214:~# salt '*' cmd.run 'df -P'
133-130-98-214:
    df: '/tmp/tmpiFv18y': No such file or directory
    Filesystem     1024-blocks    Used Available Capacity Mounted on
    /dev/vda1         50442940 4334492  43523056      10% /
    none                     4       0         4       0% /sys/fs/cgroup
    udev                497968      12    497956       1% /dev
    tmpfs               101748     424    101324       1% /run
    none                  5120       0      5120       0% /run/lock
    none                508736      16    508720       1% /run/shm
    none                102400       0    102400       0% /run/user
ERROR: Minions returned with non-zero exit code
```

**Comment by aogier** [comment]
`disk.usage` works in 2015.5.3 (`G@osrelease:6.0-8451`)

HTH, ciao
