### ISSUE TITLE
file.managed failing to render on windows

### ISSUE THREAD

**Issue by bradbeam** [saltstack/salt#20816]
When running through the following state on windows, it errors out with filename not defined. 

```jinja
C:\temp\bob:
  file.managed:
    - template: jinja
    - source: salt://templates/conf.jinja
 ```

```text
ID: C:\temp\bob
    Function: file.managed
      Result: False
     Comment: Unable to manage file: Jinja variable 'filename' is undefined
     Changes:
```

I've tried different variations such as the following ( as well as trials with quoting and different slashes ) with no luck.

```jinja
bob:
  file.managed:
    - name: C:\temp\bob
    - template: jinja
    - source: salt://templates/conf.jinja
```

When actually specifying the 'filename' variable, it fails with 

```text
Comment: Unable to manage file: Jinja variable 'dict object' has no attribute u'C:\\temp\\bob'
```
When running salt with debug output,
```text
[DEBUG   ] Traceback (most recent call last):
  File "salt/states/file.py", line 1357, in managed
  File "salt/modules/file.py", line 2536, in get_managed
  File "salt/utils/templates.py", line 99, in render_tmpl
  File "salt/utils/templates.py", line 304, in render_jinja_tmpl
SaltRenderError: Jinja variable 'filename' is undefined

[ERROR   ] Unable to manage file: Jinja variable 'filename' is undefined
```

Running `salt-minion 2014.7.1 (Helium)` on `Microsoft Windows Server 2012 Standard`

**Comment by bradbeam** [comment]
Had a bad template variable which was causing this nonsense. Fixed up the variable and all is well.

**Comment by rallytime** [comment]
Glad you figured it out @bradbeam! :)
