### ISSUE TITLE
mongodb module incompatible with MongoDB 3.0 RCs

### ISSUE THREAD

**Issue by hackel** [saltstack/salt#21012]
With MongoDB 3.0.0-rc10 installed, I get the following error when calling `mongodb_user.present` in a state:
```
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1529, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/states/mongodb_user.py", line 66, in present
    if __salt__['mongodb.user_exists'](name, user, password, host, port, database):
  File "/usr/lib/python2.7/dist-packages/salt/modules/mongodb.py", line 193, in user_exists
    users = user_list(user, password, host, port, database)
  File "/usr/lib/python2.7/dist-packages/salt/modules/mongodb.py", line 159, in user_list
    if StrictVersion(mongodb_version) >= StrictVersion('2.6'):
  File "/usr/lib/python2.7/distutils/version.py", line 40, in __init__
    self.parse(vstring)
  File "/usr/lib/python2.7/distutils/version.py", line 107, in parse
    raise ValueError, "invalid version number '%s'" % vstring
ValueError: invalid version number '3.0.0-rc10'
```
Looks like this is caused by using StrictVersion on the mongo version string, the standards of which Mongo clearly doesn't care about.  Everything works fine if I fudge the version as "3.0.0b10".

**Comment by rallytime** [comment]
Thanks for the report @hackel. The above pull request should fix this issue, as demonstrated/tested like so:
```
>>> from distutils.version import StrictVersion, LooseVersion
>>> StrictVersion('2.5') < StrictVersion('3.0.0-rc10')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/version.py", line 40, in __init__
    self.parse(vstring)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/version.py", line 107, in parse
    raise ValueError, "invalid version number '%s'" % vstring
ValueError: invalid version number '3.0.0-rc10'
>>> LooseVersion('2.5') < LooseVersion('3.0.0-rc10')
True
```
