### ISSUE TITLE
state module gem.installed not working on Windows.

### ISSUE THREAD

**Issue by deuscapturus** [saltstack/salt#21041]
gem is installed.  command is available in path.

```
----------
          ID: bundler
    Function: gem.installed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "salt/state.py", line 1529, in call
                File "salt/states/gem.py", line 96, in installed
                File "salt/modules/gem.py", line 162, in list_
                File "salt/modules/gem.py", line 25, in _gem
                File "salt/modules/cmdmod.py", line 877, in run_all
                File "salt/modules/cmdmod.py", line 371, in _run
              CommandExecutionError: Unable to run command ['gem', 'list', 'bundler'] with the context {'with_communicate': Tr
'shell': False, 'env': {'TMP': 'C:\\Users\\Admin\\AppData\\Local\\Temp', 'COMPUTERNAME': 'WINDOWS8', 'USERDOMAIN': 'windows8',
MODULEPATH': 'C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules\\', 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Fil
 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 42 Stepping 1, GenuineIntel', 'PROGRAMFILES': 'C:\\Program Files', 'PROCESSOR
ISION': '2a01', 'SYSTEMROOT': 'C:\\Windows', 'PATH': 'C:\\salt\\salt-2014.7.1.win-amd64;C:\\tools\\ruby215\\bin;c:\\windows\\s
m32;c:\\windows;c:\\windows\\system32\\wbem;c:\\windows\\system32\\windowspowershell\\v1.0;c:\\programdata\\chocolatey\\bin;c:
ogramdata\\chocolatey\\bin;c:\\programdata\\chocolatey\\chocolateyinstall\\tools;c:\\program files (x86)\\git\\cmd;;c:\\progra
les (x86)\\git\\bin;c:\\program files\\nodejs;c:\\program files\\nodejs\\npm.cmd;c:\\program files\\nodejs\\npm;c:\\tools\\pha
js;c:\\tools\\sysinternals;c:\\users\\owner\\appdata\\roaming\\scriptcs;C:\\programdata\\chocolatey\\bin;C:\\programdata\\choc
ey\\chocolateyinstall\\tools;C:\\Users\\Admin\\AppData\\Roaming\\npm', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'TEMP':
\\Users\\Admin\\AppData\\Local\\Temp', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'PROCESSOR_ARCHITEC
': 'AMD64', 'CHOCOLATEYINSTALL': 'C:\\ProgramData\\chocolatey', 'ALLUSERSPROFILE': 'C:\\ProgramData', 'LOCALAPPDATA': 'C:\\Use
Admin\\AppData\\Local', 'HOMEPATH': '\\Users\\Admin', 'USERDOMAIN_ROAMINGPROFILE': 'windows8', 'PROGRAMW6432': 'C:\\Program Fi
, 'USERNAME': 'Admin', 'LOGONSERVER': '\\\\WINDOWS8', 'PROMPT': '$P$G', 'COMSPEC': 'C:\\Windows\\system32\\cmd.exe', 'PROGRAMD
: 'C:\\ProgramData', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.RB;.RBW', 'FP_NO_HOST_CHECK': 'NO', 'W
R': 'C:\\Windows', 'HOMEDRIVE': 'C:', 'APPDATA': 'C:\\Users\\Admin\\AppData\\Roaming', 'SYSTEMDRIVE': 'C:', 'NUMBER_OF_PROCESS
: '2', 'PROCESSOR_LEVEL': '6', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 'OS': 'Windows_NT', 'PUBLIC': 'C:\\Use
Public', 'USERPROFILE': 'C:\\Users\\Admin'}, 'stdout': -1, 'stdin': None, 'stderr': -1, 'cwd': 'C:\\Users\\Admin'}, reason: [E
 2] The system cannot find the file specified
     Started: 21:31:50.253000
    Duration: 78.0 ms
     Changes:
```

**Comment by jfindlay** [comment]
@deuscapturus, will you post the output of `salt <windows-minion> test.versions_report`, or `salt-call.exe --versions-report`, whichever is applicable?  Thanks.

**Comment by jfindlay** [comment]
Related to #22298.

**Comment by davedash** [comment]
I'm getting something similar with 2015.5.0

```
----------
          ID: rbenv-deps
    Function: pkg.installed
      Result: True
     Comment: All specified packages are already installed.
     Started: 22:03:22.315434
                  runas=runas)
                File "/usr/lib/python2.7/dist-packages/salt/modules/gem.py", line 28, in _gem
                  return __salt__['rbenv.do_with_ruby'](ruby, cmdline, runas=runas)
                File "/usr/lib/python2.7/dist-packages/salt/modules/rbenv.py", line 369, in do_with_ruby
                  return do(cmd, runas=runas)
                File "/usr/lib/python2.7/dist-packages/salt/modules/rbenv.py", line 343, in do
                  env=environ
                File "/usr/lib/python2.7/dist-packages/salt/modules/cmdmod.py", line 1014, in run_all
                  use_vt=use_vt)
                File "/usr/lib/python2.7/dist-packages/salt/modules/cmdmod.py", line 391, in _run
                  .format(cmd, kwargs, exc)
              CommandExecutionError: Unable to run command ['RBENV_VERSION=2.1.2', 'gem', 'list', 'bundler'] with the context {'with_communicate': True, 'shell': False
```

**Comment by twangboy** [comment]
@deuscapturus The issue was with the gem execution module. That should be working now pending #25428 .

@davedash The following site says that rbenv isn't supported on windows:
http://misheska.com/blog/2013/06/15/using-rbenv-to-manage-multiple-versions-of-ruby/
I disabled rbenv for windows environments. If you're able to get it to work on windows and can update the rbenv execution module to work on windows and linux, we can enable it. It might require an additional win_rbenv.py module or something.
