### ISSUE TITLE
TypeError in file.replace if the pattern is a string of numbers

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt#21051]
If you pass `file.replace` a pattern that is string of numbers, it gets interpreted as an integer rather than a string. This causes re.compile to throw a TypeError.

```
# salt-call --local --log-level debug file.replace path=~/foo pattern='123' repl='456'
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: ip-172-31-46-105.ec2.internal
[DEBUG   ] Configuration file path: /etc/salt/minion
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] The `dmidecode` binary is not available on the system. GPU grains will not be available.
[DEBUG   ] Mako not available
Passed invalid arguments: first argument must be string or compiled pattern
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/cli/caller.py", line 129, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/modules/file.py", line 1111, in replace
    cpattern = re.compile(pattern, flags_num)
  File "/usr/lib64/python2.6/re.py", line 190, in compile
    return _compile(pattern, flags)
  File "/usr/lib64/python2.6/re.py", line 241, in _compile
    raise TypeError, "first argument must be string or compiled pattern"
TypeError: first argument must be string or compiled pattern
```
```
# salt-call --local --versions-report
           Salt: 2014.7.0
         Python: 2.6.9 (unknown, Sep 13 2014, 00:25:11)
         Jinja2: 2.7.2
       M2Crypto: 0.20.2
 msgpack-python: 0.4.4
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed
```

**Comment by whiteinge** [comment]
Good catch. This happens because args given at the CLI are run through the YAML parser. Looks like we're already casting `repl` to a string in that function; casting `pattern` is a good idea too.

Your fix in #21052 looks good. Thanks for sending that in and filing this issue!
