### ISSUE TITLE
salt-cloud error on 2015.2 branch pyrax error

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#21130]
On any cloud provider when I run any salt-cloud command I get an error about a 'pyrax' module

```
[ERROR   ] Failed to import clouds pyrax, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/root/salt/salt/loader.py", line 931, in _load_module
    ), fn_, fpath, desc)
  File "/root/salt/salt/cloud/clouds/pyrax.py", line 20, in <module>
    import salt.utils.openstack.pyrax as suop
  File "/root/salt/salt/utils/openstack/pyrax/__init__.py", line 3, in <module>
    import pyrax
  File "/root/salt/salt/cloud/clouds/pyrax.py", line 20, in <module>
    import salt.utils.openstack.pyrax as suop
AttributeError: 'module' object has no attribute 'pyrax'
[ERROR   ] Failed to import clouds pyrax, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/root/salt/salt/loader.py", line 931, in _load_module
    ), fn_, fpath, desc)
  File "/root/salt/salt/cloud/clouds/pyrax.py", line 20, in <module>
    import salt.utils.openstack.pyrax as suop
  File "/root/salt/salt/utils/openstack/pyrax/__init__.py", line 3, in <module>
    import pyrax
  File "/root/salt/salt/cloud/clouds/pyrax.py", line 20, in <module>
    import salt.utils.openstack.pyrax as suop
```

The salt-cloud commands do run to completion correctly, so it doesn't stop salt-cloud from functioning, but it's just incredibly chatty and ugly.

I've tested this on the latest 2015.2 branch

@rallytime has tested and confirmed this as well.

**Comment by techhat** [comment]
Also confirmed.

**Comment by rallytime** [comment]
I've tracked it down to #20952 as the culprit.

**Comment by cro** [comment]
Note that we still have an issue with pyrax itself causing novaclient to be unnecessarily chatty.

```
arch-enemy# salt-cloud -Q
[INFO    ] salt-cloud starting
[WARNING ] /usr/lib/python2.7/site-packages/novaclient/v1_1/__init__.py:30: UserWarning: Module novaclient.v1_1 is deprecated (taken as a basis for novaclient.v2). The preferable way to get client class or object you can find in novaclient.client module.
```

To eliminate this you can

```
rm -rf /usr/lib/python2.7/site-packages/novaclient/v1_1
```
The comments for __init__.py in v1_1 specifically say to remove it if it is problematic :-).
