### ISSUE TITLE
2015.2 head, salt-master stacktraces on startup

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#21176]
I'm getting this right now:

```
root@boucha:~/salt# salt-master -l debug
Traceback (most recent call last):
  File "/usr/local/bin/salt-master", line 4, in <module>
    from pkg_resources import require; require('salt==2015.2.0rc1-1899-g4d509c3')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2711, in <module>
    parse_requirements(__requires__), Environment()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: salt==2015.2.0rc1-1899-g4d509c3
```

I'm running the very latest 2015.2 branch. I installed with pip install -e /path/to/salt/

**Comment by UtahDave** [comment]
Per @terminalmage's suggestion I uninstalled with pip and reinstalled and it seems to be working fine now. I thought I had cleared out stale pyc's but maybe I missed something.

Closing.
