### ISSUE TITLE
Unable to list available versions of a named package

### ISSUE THREAD

**Issue by kphannan** [saltstack/salt#21224]
I am getting an exception when querying available versions in the windows repository.  There are 4 machines, 2 linux, 2 windows.  The host names should be self documenting.

- linux
  - salt
  - linux
- Windows
  - winxp
  - win8

The version I am running
````
[10:14 root@salt base] > salt --version
salt 2014.7.1 (Helium)
````

Get a list of available packages with no specific named package
````
[10:14 root@salt base] > salt \* pkg.available_version
salt.domain.lan:
linux.domain.lan:
win8.domain.lan:
winxp.domain.lan:
````

Get s list of versions for just the Firefox package
````    
[10:14 root@sodor base] > salt \* pkg.available_version firefox
win8.domain.lan:
    The minion function caused an exception: Traceback (most recent call last):
      File "salt/minion.py", line 1019, in _thread_return
      File "salt/modules/win_pkg.py", line 95, in latest_version
      File "salt/modules/win_pkg.py", line 773, in _get_latest_pkg_version
    IndexError: pop from empty list
    
winxp.domain.lan:
    The minion function caused an exception: Traceback (most recent call last):
      File "salt/minion.py", line 1019, in _thread_return
      File "salt/modules/win_pkg.py", line 95, in latest_version
      File "salt/modules/win_pkg.py", line 773, in _get_latest_pkg_version
    IndexError: pop from empty list
    
salt.domain.lan:
    31.5.0-1.el6.centos
linux.domain.lan:
    31.5.0-1.el6.centos
````

Here is the windows repository definition.
````
[10:25 root@salt base] > salt-run winrepo.genrepo
{'name_map': {'Mozilla Firefox 15.0.1 (x86 en-US)': 'firefox',
              'Mozilla Firefox 16.0.2 (x86 en-US)': 'firefox',
              'Mozilla Firefox 17.0.1 (x86 en-US)': 'firefox',
              'Mozilla Firefox 36.0 (x86 en-US)': 'firefox'},
 'repo': {'firefox': {'15.0.1': {'full_name': 'Mozilla Firefox 15.0.1 (x86 en-US)',
                                 'install_flags': ' -ms',
                                 'installer': 'salt://win/repo/firefox/English/Firefox Setup 15.0.1.exe',
                                 'locale': 'en_US',
                                 'reboot': False,
                                 'uninstall_flags': ' /S',
                                 'uninstaller': '%ProgramFiles(x86)%/Mozilla Firefox/uninstall/helper.exe'},
                      '16.0.2': {'full_name': 'Mozilla Firefox 16.0.2 (x86 en-US)',
                                 'install_flags': ' -ms',
                                 'installer': 'salt://win/repo/firefox/English/Firefox Setup 16.0.2.exe',
                                 'locale': 'en_US',
                                 'reboot': False,
                                 'uninstall_flags': ' /S',
                                 'uninstaller': '%ProgramFiles(x86)%/Mozilla Firefox/uninstall/helper.exe'},
                      '17.0.1': {'full_name': 'Mozilla Firefox 17.0.1 (x86 en-US)',
                                 'install_flags': ' -ms',
                                 'installer': 'salt://win/repo/firefox/English/Firefox Setup 17.0.1.exe',
                                 'locale': 'en_US',
                                 'reboot': False,
                                 'uninstall_flags': ' /S',
                                 'uninstaller': '%ProgramFiles(x86)%/Mozilla Firefox/uninstall/helper.exe'},
                      '36.0': {'full_name': 'Mozilla Firefox 36.0 (x86 en-US)',
                               'install_flags': ' -ms',
                               'installer': 'salt://win/repo/firefox/English/Firefox Setup 36.exe',
                               'locale': 'en_US',
                               'reboot': False,
                               'uninstall_flags': ' /S',
                               'uninstaller': '%ProgramFiles(x86)%/Mozilla Firefox/uninstall/helper.exe'}}}}
````

And here is the attempt to install firefox on the windows platforms.  This is what started the whole investigation.

````
[10:43 root@salt base] > salt -G 'os:Windows' state.highstate test=true
win8.hannan.lan:
----------
          ID: firefox
    Function: pkg.installed
      Result: False
     Comment: Package firefox not found in the repository.
     Started: 10:43:25.822000
    Duration: 550.0 ms
     Changes:   

Summary
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
winxp.hannan.lan:
----------
          ID: firefox
    Function: pkg.installed
      Result: False
     Comment: Package firefox not found in the repository.
     Started: 10:43:31.980000
    Duration: 281.0 ms
     Changes:   

Summary
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
````

**Comment by kphannan** [comment]
After more investigation I discovered that even though the windows repository was configured in the master to reside at ```/srv/salt/win/repo``` the minion was looking in ```/srv/salt/base/win/repo```.  This is apparently due to the configuration of my ```file_roots``` which has the following:
```
file_roots:
  base:
    - /srv/salt/base
    - /srv/salt/prod
  prod:
    - /srv/salt/prod
  test:
    - /srv/salt/test
    - /srv/salt/prod
  dev:
    - /srv/salt/dev
    - /srv/salt/test
    - /srv/salt/prod
    - /srv/salt/base
```

I was about to start learning python and changing the windows package code....  Now I can move on to more configuration / provisioning.

**Comment by jfindlay** [comment]
@kphannan, according to the `file_roots` configuration you've shown, `/srv/salt/base/...` should be the correct place for files in the base saltenv.  Are you still having problems listing packages from your file server?

**Comment by kphannan** [comment]
Not any more.  It wasn't clear in the docs where the ```win/repo``` was to be rooted.  I just continued to poke around and try moving the repos, and it now works.  Will the windows repos be handled the same way as the states as far as environments go?
  For example I want to test a new package in ```test``` before moving it to production....  Is it possible to have a ```dev``` and a ```test``` windows repository?  I presume no, since there is only a single ```win_repo``` and ```win_repo_mastercachefile``` setting pair.  Maybe I need to look more at a Git repository and branches....

  I'm in the learning / experimenting phase right now, eventually to have a state tree / pillar to support multiple VMs across multiple OSes.

**Comment by kphannan** [comment]
The issue at present is more of documentation or better error messages.  Hopefully this issue and associated comments will help someone else.  Keep up the good work.
