### ISSUE TITLE
Failing `blkid` call in `salt.modules.disk.blkid()` isn't handled properly

### ISSUE THREAD

**Issue by eliasp** [saltstack/salt#21304]
**OS:** `CentOS 7.0.1406 (Core) amd64`
**Salt:**
```
               Salt: 2014.7.1
             Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
             Jinja2: 2.7.2
           M2Crypto: 0.21.1
     msgpack-python: 0.4.4
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
            libnacl: Not Installed
             PyYAML: 3.10
              ioflo: Not Installed
              PyZMQ: 14.3.1
               RAET: Not Installed
                ZMQ: 3.2.4
               Mako: Not Installed
```

When executing the `blkid` binary fails in `salt.modules.disk.blkid()`, the failure isn't handled properly and instead a backtrace is thrown:
```
$ salt-call -l debug disk.blkid
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/masterless.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/masterless.conf
[DEBUG   ] Configuration file path: /etc/salt/minion
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/masterless.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/masterless.conf
[WARNING ] Although 'dmidecode' was found in path, the current user cannot execute it. Grains output might not be accurate.
[DEBUG   ] Mako not available
[…]
[INFO    ] Executing command 'blkid' in directory '/root'
[ERROR   ] Command 'blkid' failed with return code: 2
[ERROR   ] retcode: 2
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
IndexError: list index out of range
Traceback (most recent call last):
  File "/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 123, in salt_call
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/__init__.py", line 420, in run
    caller.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 225, in run
    ret = self.call()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 129, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/disk.py", line 215, in blkid
    device = comps[0][:-1]
IndexError: list index out of range
Traceback (most recent call last):
  File "/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 123, in salt_call
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/__init__.py", line 420, in run
    caller.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 225, in run
    ret = self.call()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 129, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/disk.py", line 215, in blkid
    device = comps[0][:-1]
IndexError: list index out of range
```

The failure is more or less expected as this was executed in a `systemd-nspawn` container and I'll properly handle this case in my states, but in general the `disk` execution module should fail more gracefully.

**EDIT:**
The raw `blkid` output is zero - it just quits with returncode `2` and no output at all.

**Comment by eliasp** [comment]
Looks like this was fixed in 192ccc73736a3f84c5852359c9bd6844a485e71b

**Comment by eliasp** [comment]
Looks like it wasn't fully fixed. Still seeing the error message:
```
-bash-4.2# salt-call -l debug disk.blkid
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/id.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/id.conf
[DEBUG   ] Including configuration from '/etc/salt/minion.d/master.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/master.conf
[DEBUG   ] Including configuration from '/etc/salt/minion.d/masterless.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/masterless.conf
[DEBUG   ] Configuration file path: /etc/salt/minion
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/id.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/id.conf
[DEBUG   ] Including configuration from '/etc/salt/minion.d/master.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/master.conf
[DEBUG   ] Including configuration from '/etc/salt/minion.d/masterless.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/masterless.conf
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Mako not available
[INFO    ] Executing command 'blkid' in directory '/root'
[ERROR   ] Command 'blkid' failed with return code: 2
[ERROR   ] retcode: 2
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
IndexError: list index out of range
Traceback (most recent call last):
  File "/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 123, in salt_call
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/__init__.py", line 420, in run
    caller.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 225, in run
    ret = self.call()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 129, in call
    ret['return'] = func(*args, **kwargs)
  File "<string>", line 2, in blkid
  File "/usr/lib/python2.7/site-packages/salt/utils/decorators/__init__.py", line 132, in wrapped
    return function(*args, **kwargs)
  File "/var/cache/salt/minion/extmods/modules/disk.py", line 226, in blkid
    device = comps[0][:-1]
IndexError: list index out of range
Traceback (most recent call last):
  File "/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 123, in salt_call
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/__init__.py", line 420, in run
    caller.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 225, in run
    ret = self.call()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 129, in call
    ret['return'] = func(*args, **kwargs)
  File "<string>", line 2, in blkid
  File "/usr/lib/python2.7/site-packages/salt/utils/decorators/__init__.py", line 132, in wrapped
    return function(*args, **kwargs)
  File "/var/cache/salt/minion/extmods/modules/disk.py", line 226, in blkid
    device = comps[0][:-1]
```

**Comment by jfindlay** [comment]
@eliasp, thanks for the fix.
