### ISSUE TITLE
SaltStack Minion on kali linux will not restart a service

### ISSUE THREAD

**Issue by coleton** [saltstack/salt#21378]
During a service restart, I received this error:
```
2015-03-06 17:19:30,426 [salt.minion                                 ][WARNING ] The minion function caused an exception: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 641, in _thread_return
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/service.py", line 102, in restart
    cmd = os.path.join(GRAINMAP[__grains__['os']],
KeyError: 'Kali'
```

**Comment by rallytime** [comment]
@coleton Can you post the output of `salt --versions-report`, please? Are you getting this error when starting the minion or a service on the minion? (Can you post the command you're using?)
