### ISSUE TITLE
Recursive pillar merge breaks when None is merged with dict

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#21391]
pillarA.sls:

``` yaml
test:
```

pillarB.sls:

``` yaml
test:
  me
```

top.sls:

``` yaml
base:
  '*':
    - pillarA
    - pillarB
```

Stacktrace:

``` python
Traceback (most recent call last):
  File "/usr/local/bin/salt-call", line 10, in <module>
    execfile(__file__)
  File "/srv/salt/venv/src/salt/scripts/salt-call", line 11, in <module>
    salt_call()
  File "/srv/salt/venv/src/salt/salt/scripts.py", line 122, in salt_call
    client.run()
  File "/srv/salt/venv/src/salt/salt/cli/__init__.py", line 409, in run
    caller = salt.cli.caller.Caller.factory(self.config)
  File "/srv/salt/venv/src/salt/salt/cli/caller.py", line 64, in factory
    return ZeroMQCaller(opts, **kwargs)
  File "/srv/salt/venv/src/salt/salt/cli/caller.py", line 87, in __init__
    self.minion = salt.minion.SMinion(opts)
  File "/srv/salt/venv/src/salt/salt/minion.py", line 267, in __init__
    self.gen_modules()
  File "/srv/salt/venv/src/salt/salt/minion.py", line 277, in gen_modules
    self.opts['environment'],
  File "/srv/salt/venv/src/salt/salt/pillar/__init__.py", line 578, in compile_pillar
    pillar, errors = self.render_pillar(matches)
  File "/srv/salt/venv/src/salt/salt/pillar/__init__.py", line 464, in render_pillar
    pillar = self.merge_sources(pillar, pstate)
  File "/srv/salt/venv/src/salt/salt/pillar/__init__.py", line 559, in merge_sources
    merged = merge_recurse(obj_a, obj_b)
  File "/srv/salt/venv/src/salt/salt/pillar/__init__.py", line 31, in merge_recurse
    return update(copied, obj_b)
  File "/srv/salt/venv/src/salt/salt/utils/dictupdate.py", line 14, in update
    ret = update(dest.get(key, {}), val)
  File "/srv/salt/venv/src/salt/salt/utils/dictupdate.py", line 17, in update
    dest[key] = upd[key]
TypeError: 'NoneType' object does not support item assignment
```

This is for version 2014.7.2.

**Comment by jfindlay** [comment]
@ryan-lane, thanks for the report.

**Comment by ryanwohara** [comment]
I know Salt will fail in other places if a YAML section is left blank. I am not certain what the expected functionality here is but with the provided context, avoiding the NoneType error seems prudent. 

A more complex solution may be required.

**Comment by cachedout** [comment]
I haven't (yet) taken the time to reproduce this condition, but I'm wondering if the fix from @ryanwohara meets the needs of @ryan-lane here.

**Comment by rallytime** [comment]
@ryan-lane Just a bump here to see if the fix mentioned above resolved this for you or not.

**Comment by ryan-lane** [comment]
Looking at the code, I can't imagine it fixes it. The key exists, but the value does not.

**Comment by ryan-lane** [comment]
dest[key] is None. The exception is trying to assign a value to None. The key, as far as I know should exist.

**Comment by rallytime** [comment]
Alright. I'll remove that "Fixed..." label so we can get eyes on this again.
