### ISSUE TITLE
salt.cloud.clouds.vsphere.list_nodes_full fails with a TypeError

### ISSUE THREAD

**Issue by nmadhok** [saltstack/salt#21406]
``salt.cloud.clouds.vsphere.list_nodes_full`` fails with ``TypeError``. 

http://docs.saltstack.com/en/latest/ref/clouds/all/salt.cloud.clouds.vsphere.html#salt.cloud.clouds.vsphere.list_nodes_full

```
root@nitin-salt-develop:~$ salt-cloud -f list_nodes_full vsphere-config
[INFO    ] salt-cloud starting
[ERROR   ] There was an error running the function: 'NoneType' object is not iterable
```

Additional info when run in debug mode:
```
root@nitin-salt-develop:~$ salt-cloud -f list_nodes_full vsphere-config -l debug
[DEBUG   ] Missing configuration file: /etc/salt/cloud
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: nitin-salt-develop
[DEBUG   ] Missing configuration file: /etc/salt/cloud.providers
[DEBUG   ] Including configuration from '/etc/salt/cloud.providers.d/providers.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers.d/providers.conf
[DEBUG   ] Missing configuration file: /etc/salt/cloud.profiles
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/profiles.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/profiles.conf
[DEBUG   ] Configuration file path: /etc/salt/master
[INFO    ] salt-cloud starting
[DEBUG   ] Failed to import clouds joyent:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/loader.py", line 935, in _load_module
    ), fn_, fpath, desc)
  File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/joyent.py", line 65, in <module>
    from Crypto.Signature import PKCS1_v1_5
ImportError: No module named Signature
[DEBUG   ] Could not LazyLoad parallels.avail_sizes
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy
[DEBUG   ] Could not LazyLoad saltify.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.avail_images
[DEBUG   ] Could not LazyLoad saltify.avail_locations
[DEBUG   ] LazyLoaded rackspace.reboot
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] LazyLoaded rackspace.list_locations
[DEBUG   ] Trying to execute 'vsphere.list_nodes_full' with the following kwargs: {}
[ERROR   ] There was an error running the function: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/cloud/cli.py", line 245, in run
    self.function_provider, self.function_name, kwargs
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 1492, in do_function
    driver: self.clouds[fun](call='function')
  File "/usr/lib64/python2.6/contextlib.py", line 34, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.6/site-packages/salt/utils/context.py", line 42, in func_globals_inject
    yield
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 1492, in do_function
    driver: self.clouds[fun](call='function')
  File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/vsphere.py", line 467, in list_nodes_full
    properties = _get_instance_properties(instance)
  File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/vsphere.py", line 441, in _get_instance_properties
    for disk in ret['disks']:  # pylint: disable=W0612
TypeError: 'NoneType' object is not iterable
```

Running latest develop:
```
root@nitin-salt-develop:~$ salt-cloud --versions-report
            Salt: 2015.2.0rc1-3072-g24f1302
          Python: 2.6.6 (r266:84292, Nov 21 2013, 10:50:32)
          Jinja2: 2.7.3
        M2Crypto: 0.20.2
  msgpack-python: 0.4.4
    msgpack-pure: Not Installed
        pycrypto: 2.0.1
         libnacl: 1.4.1
          PyYAML: 3.10
           ioflo: Not Installed
           PyZMQ: 14.3.1
            RAET: Not Installed
             ZMQ: 3.2.4
            Mako: Not Installed
 Apache Libcloud: 0.14.1
```

**Comment by rallytime** [comment]
Thanks @nmadhok!

ping @techhat

**Comment by nmadhok** [comment]
@rallytime no problem! Already told about this to @techhat

**Comment by nmadhok** [comment]
@rallytime Closing this issue in favor of the new vmware salt-cloud driver.
