### ISSUE TITLE
Exception in openstack cloud provider with `extends` in provider configuration

### ISSUE THREAD

**Issue by dtoubelis** [saltstack/salt#21474]
```
root@saltmaster:~# salt --versions-report
           Salt: 2014.7.1
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
```

Executed command being executed:
`
root@saltmaster:~# salt-cloud -p rackspace-dfw-web dfw-web-001 -l debug
`

This is the profile:

``` yaml
rackspace-dfw-web:
  provider: rackspace-dfw
  size: general1-2
  image: Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
  networks:
    - fixed:
      - 00000000-0000-0000-0000-000000000000
      - 11111111-1111-1111-1111-111111111111
```

This is provider configuration that works:

``` yaml
rackspace-dfw:
  provider: openstack
  identity_url: https://identity.api.rackspacecloud.com/v2.0/tokens
  compute_name: cloudServersOpenStack
  protocol: ipv4
  ssh_key_name: saltmaster
  ssh_key_file: /root/.ssh/saltmaster.pem
  ssh_interface: private_ips
  user: <api-user>
  apikey: <api-key>
  tenant: <tennant-id>
  compute_region: DFW
  minion:
    master: dfw-saltmaster.example.com
```

However this one:

``` yaml
rackspace-core:
  provider: openstack
  identity_url: https://identity.api.rackspacecloud.com/v2.0/tokens
  compute_name: cloudServersOpenStack
  protocol: ipv4
  ssh_key_name: saltmaster
  ssh_key_file: /root/.ssh/saltmaster.pem
  ssh_interface: private_ips
  user: <api-user>
  apikey: <api-key>
  tenant: <tennant-id>
  minion:
    master: saltmaster.example.com

rackspace-dfw:
  extends: rackspace-core:openstack
  compute_region: DFW
  minion:
    master: dfw-saltmaster.example.com
```

produces this exception:

```
[DEBUG   ] Failed to execute 'openstack.list_nodes()' while querying for running nodes: <LibcloudError in None 'Could not find specified endpoint'>
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 2198, in run_parallel_map_providers_query
    cloud.clouds[data['fun']]()
  File "/usr/lib/python2.7/dist-packages/salt/cloud/libcloudfuncs.py", line 429, in list_nodes
    nodes = conn.list_nodes()
  File "/usr/lib/python2.7/dist-packages/libcloud/compute/drivers/openstack.py", line 219, in list_nodes
    self.connection.request('/servers/detail').object)
  File "/usr/lib/python2.7/dist-packages/libcloud/compute/drivers/openstack.py", line 157, in request
    method=method, headers=headers)
  File "/usr/lib/python2.7/dist-packages/libcloud/common/openstack.py", line 575, in request
    return super(OpenStackBaseConnection, self).request(**kwargs)
  File "/usr/lib/python2.7/dist-packages/libcloud/common/base.py", line 596, in request
    action = self.morph_action_hook(action)
  File "/usr/lib/python2.7/dist-packages/libcloud/common/openstack.py", line 571, in morph_action_hook
    self._populate_hosts_and_request_paths()
  File "/usr/lib/python2.7/dist-packages/libcloud/common/openstack.py", line 611, in _populate_hosts_and_request_paths
    url = self._ex_force_base_url or self.get_endpoint()
  File "/usr/lib/python2.7/dist-packages/libcloud/common/openstack.py", line 563, in get_endpoint
    raise LibcloudError('Could not find specified endpoint')
LibcloudError: <LibcloudError in None 'Could not find specified endpoint'>
```

It seems that something is wrong with handling `extends` in provider configuration.

**Comment by rallytime** [comment]
Thanks for this excellent bug report, @dtoubelis! I think you're right...something with extends isn't quite right there.

@s0undt3ch ping.

**Comment by rallytime** [comment]
I can no longer reproduce this error on a newer version of salt. I testing this at the current HEAD of the 2015.5 branch, and I was able to provision a VM successfully using extends with `salt-cloud -p rs-extends-test nt-extends-test`.

Simple Profile with Extends on Rackspace:
```
rs-ubuntu-14:
  provider: rackspace
  size: 2 GB Performance
  image: Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
  script_args: 'git 2015.5'

rs-extends-test:
  grains:
    hello: world
  extends: rs-ubuntu-14
```
The VM was created successfully and the grain that was added in the "extends" section is successfully deployed to the minion:
```
# salt nt-extends-test grains.item hello
nt-extends-test:
    ----------
    hello:
        world
```
Versions Report:
```
# salt-cloud --versions
            Salt: 2015.5.1-97-g88a997e
          Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
          Jinja2: 2.7.3
        M2Crypto: 0.21.1
  msgpack-python: 0.4.4
    msgpack-pure: Not Installed
        pycrypto: 2.6.1
         libnacl: Not Installed
          PyYAML: 3.11
           ioflo: Not Installed
           PyZMQ: 14.0.1
            RAET: Not Installed
             ZMQ: 4.0.4
            Mako: 0.9.1
 Apache Libcloud: 0.17.0
```

@dtoubelis Are you still seeing this error on a newer version of salt (current stable is 2015.5.1)?

**Comment by dtoubelis** [comment]
Here is the latest version from PPA:
```
root@saltmaster-0002:~# salt --versions-report
                  Salt: 2015.5.0
                Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
 Debian source package: 2015.5.0+ds-1trusty1
```
I'm still getting the error, however now `salt-cloud` is also complaining about novaclient:

```
...
[DEBUG   ] OpenStack authenticating using apikey
[DEBUG   ] Failed to execute 'nova.list_nodes()' while querying for running nodes: Newer version of novaclient required for __exit__.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 2247, in run_parallel_map_providers_query
    cloud.clouds[data['fun']]()
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/nova.py", line 795, in list_nodes
    conn = get_conn()
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/nova.py", line 197, in get_conn
    conn = nova.SaltNova(**kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/utils/openstack/nova.py", line 167, in __init__
    raise SaltCloudSystemExit("Newer version of novaclient required for __exit__.")
SaltCloudSystemExit: Newer version of novaclient required for __exit__.
[DEBUG   ] Failed to execute 'openstack.list_nodes()' while querying for running nodes: <LibcloudError in None 'Could not find specified endpoint'>
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 2247, in run_parallel_map_providers_query
    cloud.clouds[data['fun']]()
  File "/usr/lib/python2.7/dist-packages/salt/cloud/libcloudfuncs.py", line 432, in list_nodes
    nodes = conn.list_nodes()
  File "/usr/lib/python2.7/dist-packages/libcloud/compute/drivers/openstack.py", line 219, in list_nodes
    self.connection.request('/servers/detail').object)
  File "/usr/lib/python2.7/dist-packages/libcloud/compute/drivers/openstack.py", line 157, in request
    method=method, headers=headers)
  File "/usr/lib/python2.7/dist-packages/libcloud/common/openstack.py", line 575, in request
    return super(OpenStackBaseConnection, self).request(**kwargs)
  File "/usr/lib/python2.7/dist-packages/libcloud/common/base.py", line 596, in request
    action = self.morph_action_hook(action)
  File "/usr/lib/python2.7/dist-packages/libcloud/common/openstack.py", line 571, in morph_action_hook
    self._populate_hosts_and_request_paths()
  File "/usr/lib/python2.7/dist-packages/libcloud/common/openstack.py", line 611, in _populate_hosts_and_request_paths
    url = self._ex_force_base_url or self.get_endpoint()
  File "/usr/lib/python2.7/dist-packages/libcloud/common/openstack.py", line 563, in get_endpoint
    raise LibcloudError('Could not find specified endpoint')
LibcloudError: <LibcloudError in None 'Could not find specified endpoint'>
[DEBUG   ] Generating minion keys for 'dfw-pre01-api-0039'
...
```

The profile without `extend` only shows this:

```
...
[DEBUG   ] Failed to execute 'nova.list_nodes()' while querying for running nodes: Newer version of novaclient required for __exit__.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 2247, in run_parallel_map_providers_query
    cloud.clouds[data['fun']]()
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/nova.py", line 795, in list_nodes
    conn = get_conn()
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/nova.py", line 197, in get_conn
    conn = nova.SaltNova(**kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/utils/openstack/nova.py", line 167, in __init__
    raise SaltCloudSystemExit("Newer version of novaclient required for __exit__.")
SaltCloudSystemExit: Newer version of novaclient required for __exit__.
[DEBUG   ] Generating minion keys for 'dfw-pre01-api-0040'
...
```

I realize it is not the latest version from repo, but this is all testing I can do at the moment in my environment.

The deployment seems go through but this issue does not prevent creation of instances with duplicate names.

**Comment by rallytime** [comment]
@dtoubelis Oh! I didn't see at first that you're extending the PROVIDER and not the PROFILE. When I tried to extend the provider in a very simple way, I was able to reproduce your original stacktrace on 2015.5.1. I can't speak to the new errors you seeing though with nova - that looks like a different problem to me. I'd recommend opening a new issue about that.

**Comment by dtoubelis** [comment]
I agree about the nova exception. It is likely a different issue not related to this one.
