### ISSUE TITLE
python setup.py -V crashes

### ISSUE THREAD

**Issue by Diaoul** [saltstack/salt#21522]
Same for all other simple options like --author
```
# python setup.py -V    
2014.7.0
Traceback (most recent call last):
  File "setup.py", line 869, in <module>
    setup(distclass=SaltDistribution)
  File "/usr/lib/python2.7/distutils/core.py", line 138, in setup
    ok = dist.parse_command_line()
  File "setup.py", line 835, in parse_command_line
    args = distutils.dist.Distribution.parse_command_line(self)
  File "/usr/lib/python2.7/distutils/dist.py", line 459, in parse_command_line
    args = parser.getopt(args=self.script_args, object=self)
  File "/usr/lib/python2.7/distutils/fancy_getopt.py", line 285, in getopt
    val = getattr(object, attr, 0) + 1
TypeError: cannot concatenate 'str' and 'int' objects
```

Using tarball from pypi 2014.7.2

Side effect when running `pip wheel salt==2014.7.2`:
> Requested salt==2014.7.2, but installing version None

The wheel get built but the result is `salt-2014.7.0-py2-none-any.whl` with the wrong version number as you can see.

**Comment by Diaoul** [comment]
Seems to work fine with 2015.2.0rc1

**Comment by rallytime** [comment]
@Diaoul Thanks very much for catching this and filing this bug! @s0undt3ch is quick and already has a fix in for this.

**Comment by jfindlay** [comment]
@rallytime,

```
# python setup.py -V
2014.7.2-309-g979ed66
2014.7.2-309-g979ed66
```

**Comment by jfindlay** [comment]
I think that this means the version info is fixed,

```
centos-7-main salt 2014.7 # pip wheel .
Unpacking /root/salt
  Running setup.py (path:/tmp/pip-ezjMU_-build/setup.py) egg_info for package from file:///root/salt
    2014.7.2-309-g979ed66

    warning: no files found matching 'tests/unit/templates/files/*'
Downloading/unpacking Jinja2 (from salt==2014.7.2-309-g979ed66)
  Downloading Jinja2-2.7.3.tar.gz (378kB): 378kB downloaded
  Running setup.py (path:/tmp/pip-build-470v4w/Jinja2/setup.py) egg_info for package Jinja2

    warning: no files found matching '*' under directory 'custom_fixers'
    warning: no previously-included files matching '*' found under directory 'docs/_build'
    warning: no previously-included files matching '*.pyc' found under directory 'jinja2'
    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'jinja2'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
Downloading/unpacking msgpack-python>0.3 (from salt==2014.7.2-309-g979ed66)
  Downloading msgpack-python-0.4.5.tar.gz (116kB): 116kB downloaded
  Running setup.py (path:/tmp/pip-build-470v4w/msgpack-python/setup.py) egg_info for package msgpack-python

Downloading/unpacking PyYAML (from salt==2014.7.2-309-g979ed66)
  Downloading PyYAML-3.11.tar.gz (248kB): 248kB downloaded
  Running setup.py (path:/tmp/pip-build-470v4w/PyYAML/setup.py) egg_info for package PyYAML

Downloading/unpacking MarkupSafe (from salt==2014.7.2-309-g979ed66)
  Downloading MarkupSafe-0.23.tar.gz
  Running setup.py (path:/tmp/pip-build-470v4w/MarkupSafe/setup.py) egg_info for package MarkupSafe

Downloading/unpacking requests>=1.0.0 (from salt==2014.7.2-309-g979ed66)
  Downloading requests-2.5.3-py2.py3-none-any.whl (468kB): 468kB downloaded
  Saved ./wheelhouse/requests-2.5.3-py2.py3-none-any.whl
Building wheels for collected packages: Jinja2,msgpack-python,PyYAML,MarkupSafe,salt
  Running setup.py bdist_wheel for Jinja2
  Destination directory: /root/salt/wheelhouse
  Running setup.py bdist_wheel for msgpack-python
  Destination directory: /root/salt/wheelhouse
  Running setup.py bdist_wheel for PyYAML
  Destination directory: /root/salt/wheelhouse
  Running setup.py bdist_wheel for MarkupSafe
  Destination directory: /root/salt/wheelhouse
  Running setup.py bdist_wheel for salt
  Destination directory: /root/salt/wheelhouse
Successfully built Jinja2 msgpack-python PyYAML MarkupSafe salt
Cleaning up...
```

**Comment by s0undt3ch** [comment]
Theres additional fixing required....

**Comment by s0undt3ch** [comment]
#21568 was merged. This should be fixed.

**Comment by rallytime** [comment]
Thanks @s0undt3ch and @jfindlay!

@Diaoul I am going to close this since I don't see those errors any more. If you still run into problems, leave a comment and we can open this again.
