### ISSUE TITLE
MySQL Returner and Mworker errors in log file on 2015.2 latest

### ISSUE THREAD

**Issue by ssgward** [saltstack/salt#21552]
Sorry for the vague bug title. Couldn't come up with a better title at the moment.

Wanted to get these errors out there in case they help with mysql returner trouble shooting. These errors were found in /var/logs/salt/master.

I'm not sure if these errors are a result of the mysql returner or causing the problems in the mysql returner or a combination of both.
```
2015-03-11 17:05:57,960 [salt.utils.event ][ERROR   ][13706] Could not store return for events <generator object iter_events at 0xb7421e0>. Returner mysql not found.
2015-03-11 17:06:00,046 [salt.master      ][ERROR   ][28046] Exception occurred while introspecting key.list_all: 'mysql.prep_jid'
2015-03-11 17:06:00,064 [salt.utils.event ][ERROR   ][13751] Could not store return for events <generator object iter_events at 0xb742aa0>. Returner mysql not found.
2015-03-11 17:06:01,781 [salt.master      ][CRITICAL][28052] Unexpected Error in Mworker
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 715, in __bind
    ret = self.serial.dumps(self._handle_payload(payload))
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 766, in _handle_payload
    'clear': self._handle_clear}[key](load)
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 779, in _handle_clear
    return getattr(self.clear_funcs, load['cmd'])(load)
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 2352, in publish
    clear_load['jid'] = self.mminion.returners[fstr](nocache=extra.get('nocache', False),
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 873, in __getitem__
    mod = super(LazyLoader, self).__getitem__(key)
  File "/usr/lib/python2.7/site-packages/salt/utils/lazy.py", line 95, in __getitem__
    raise KeyError(key)
KeyError: 'mysql.prep_jid'
```

**Comment by terminalmage** [comment]
This is part of the same issue I'm troubleshooting in https://github.com/saltstack/salt/issues/21449. Closing this one as a duplicate.

**Comment by ssgward** [comment]
that was fast :)
