### ISSUE TITLE
CRITICAL: develop: runners are again  broken...

### ISSUE THREAD

**Issue by kiorky** [saltstack/salt#21578]
```
[DEBUG   ] LazyLoaded nested.output
[TRACE   ] data = Exception occurred in runner mc_cloud_compute_node.report: Traceback (most recent call last):
  File "/srv/mastersalt/makina-states/src/salt/salt/client/mixins.py", line 328, in low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/srv/mastersalt/makina-states/mc_states/runners/mc_cloud_compute_node.py", line 529, in report
    _s['mc_api.time_log']('start', fname)
  File "/srv/mastersalt/makina-states/mc_states/runners/mc_api.py", line 65, in time_log
    msg, event_category=lifecycle_id, fun=fun, *args, **extra_data)
  File "/srv/mastersalt/makina-states/mc_states/runners/mc_api.py", line 56, in cloud_event
    __jid_event__.fire_event(payload, tag)
  File "/srv/mastersalt/makina-states/src/salt/salt/utils/event.py", line 621, in fire_event
    self.print_func(tag, data)
  File "/srv/mastersalt/makina-states/src/salt/salt/client/mixins.py", line 448, in print_async_event
    if isinstance(event['return'], dict) \
KeyError: 'return'

Exception occurred in runner mc_cloud_compute_node.report: Traceback (most recent call last):
  File "/srv/mastersalt/makina-states/src/salt/salt/client/mixins.py", line 328, in low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/srv/mastersalt/makina-states/mc_states/runners/mc_cloud_compute_node.py", line 529, in report
    _s['mc_api.time_log']('start', fname)
  File "/srv/mastersalt/makina-states/mc_states/runners/mc_api.py", line 65, in time_log
    msg, event_category=lifecycle_id, fun=fun, *args, **extra_data)
  File "/srv/mastersalt/makina-states/mc_states/runners/mc_api.py", line 56, in cloud_event
    __jid_event__.fire_event(payload, tag)
  File "/srv/mastersalt/makina-states/src/salt/salt/utils/event.py", line 621, in fire_event
    self.print_func(tag, data)
  File "/srv/mastersalt/makina-states/src/salt/salt/client/mixins.py", line 448, in print_async_event
    if isinstance(event['return'], dict) \
KeyError: 'return'

[DEBUG   ] Sending event - data = {'jid': '20150312012911467820', 'return': 'Exception occurred in runner mc_cloud_compute_node.report: Traceback (most recent call last):\n  File "/srv/mastersalt/makina-states/src/salt/salt/client/mixins.py", line 328, in low\n    data[\'return\'] = self.functions[fun](*args, **kwargs)\n  File "/srv/mastersalt/makina-states/mc_states/runners/mc_cloud_compute_node.py", line 529, in report\n    _s[\'mc_api.time_log\'](\'start\', fname)\n  File "/srv/mastersalt/makina-states/mc_states/runners/mc_api.py", line 65, in time_log\n    msg, event_category=lifecycle_id, fun=fun, *args, **extra_data)\n  File "/srv/mastersalt/makina-states/mc_states/runners/mc_api.py", line 56, in cloud_event\n    __jid_event__.fire_event(payload, tag)\n  File "/srv/mastersalt/makina-states/src/salt/salt/utils/event.py", line 621, in fire_event\n    self.print_func(tag, data)\n  File "/srv/mastersalt/makina-states/src/salt/salt/client/mixins.py", line 448, in print_async_event\n    if isinstance(event[\'return\'], dict) \\\nKeyError: \'return\'\n', 'success': False, '_stamp': '2015-03-12T00:29:11.750153', 'user': 'root', 'fun': 'runner.mc_cloud_compute_node.report'}
[DEBUG   ] LazyLoaded local_cache.prep_jid
[INFO    ] Runner completed: 20150312012911467820
[DEBUG   ] Runner return: Exception occurred in runner mc_cloud_compute_node.report: Traceback (most recent call last):
  File "/srv/mastersalt/makina-states/src/salt/salt/client/mixins.py", line 328, in low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/srv/mastersalt/makina-states/mc_states/runners/mc_cloud_compute_node.py", line 529, in report
    _s['mc_api.time_log']('start', fname)
  File "/srv/mastersalt/makina-states/mc_states/runners/mc_api.py", line 65, in time_log
    msg, event_category=lifecycle_id, fun=fun, *args, **extra_data)
  File "/srv/mastersalt/makina-states/mc_states/runners/mc_api.py", line 56, in cloud_event
    __jid_event__.fire_event(payload, tag)
  File "/srv/mastersalt/makina-states/src/salt/salt/utils/event.py", line 621, in fire_event
    self.print_func(tag, data)
  File "/srv/mastersalt/makina-states/src/salt/salt/client/mixins.py", line 448, in print_async_event
    if isinstance(event['return'], dict) \
KeyError: 'return'


```

**Comment by kiorky** [comment]
cc @jacksontj @cachedout 

I also saw that the print() that is meaningful in case of runners, and that we moved again, and again with @jacksontj has again be replaced with nested output (if i understood well the last merge), but i cant test as runners are broken.

**Comment by kiorky** [comment]
```
(Pdb) event
{'category': 'timer_start', 'message': 'timer_start: mc_compute_node.report', 'args': (), 'kw': {'fun': 'mc_compute_node.report', 'event_datetime': '2015-03-12T01:37:58.010505'}}
```
At the failure point (
```
(Pdb) bt
  /srv/mastersalt/makina-states/bin/salt-run(66)<module>()
-> ret = salt.scripts.salt_run()
  /srv/mastersalt/makina-states/src/salt/salt/scripts.py(240)salt_run()
-> client.run()
  /srv/mastersalt/makina-states/src/salt/salt/cli/run.py(36)run()
-> runner.run()
  /srv/mastersalt/makina-states/src/salt/salt/runner.py(164)run()
-> False)  # Don't daemonize
  /srv/mastersalt/makina-states/src/salt/salt/client/mixins.py(392)_proc_function()
-> return self.low(fun, low)
  /srv/mastersalt/makina-states/src/salt/salt/client/mixins.py(328)low()
-> data['return'] = self.functions[fun](*args, **kwargs)
  /srv/mastersalt/makina-states/mc_states/runners/mc_cloud_compute_node.py(529)report()
-> _s['mc_api.time_log']('start', fname)
  /srv/mastersalt/makina-states/mc_states/runners/mc_api.py(65)time_log()
-> msg, event_category=lifecycle_id, fun=fun, *args, **extra_data)
  /srv/mastersalt/makina-states/mc_states/runners/mc_api.py(56)cloud_event()
-> __jid_event__.fire_event(payload, tag)
  /srv/mastersalt/makina-states/src/salt/salt/utils/event.py(621)fire_event()
-> self.print_func(tag, data)
> /srv/mastersalt/makina-states/src/salt/salt/client/mixins.py(460)print_async_event()
-> salt.output.display_output(event_data, outputter, self.opts)
```
)

**Comment by jacksontj** [comment]
Actually it looks like it was broken with 1d3d869

**Comment by jacksontj** [comment]
Do we care that its not doing a print() I think the problem here is the exception (which i have a fix for)

**Comment by terminalmage** [comment]
We should have a fallback when there is no ``return`` key. Optimally it would just be to set ``event_data`` to the value of the ``data`` key, because that way the output will be processed through ``salt.output.display_output()``.

@jacksontj is working on a fix right now.

**Comment by kiorky** [comment]
For my side, i was publishing via __jid__event, and as the payload format did changed with this commit, i have fixed the delta structure.

**Comment by kiorky** [comment]
Now, the output is again totally broken, each event is going printed out without control...

**Comment by kiorky** [comment]
Of so we figured together what was needed, it's fixed for me !

**Comment by terminalmage** [comment]
Yep, @jacksontj to the rescue.

**Comment by terminalmage** [comment]
Fix was merged, closing.
