### ISSUE TITLE
support jinja filters

### ISSUE THREAD

**Issue by pille** [saltstack/salt#21583]
please support all filters available in jinja2.
i'm explicitly looking for `ljust`, but there's a bunch of more.

```
          ID: google.yml
    Function: file.managed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/pymodules/python2.7/salt/state.py", line 1382, in call
                  **cdata['kwargs'])
                File "/usr/lib/pymodules/python2.7/salt/states/file.py", line 1246, in managed
                  **kwargs
                File "/usr/lib/pymodules/python2.7/salt/modules/file.py", line 2363, in check_managed
                  **kwargs)
                File "/usr/lib/pymodules/python2.7/salt/modules/file.py", line 2099, in get_managed
                  **kwargs)
                File "/usr/lib/pymodules/python2.7/salt/utils/templates.py", line 85, in render_tmpl
                  output = render_str(tmplstr, context, tmplpath)
                File "/usr/lib/pymodules/python2.7/salt/utils/templates.py", line 271, in render_jinja_tmpl
                  tmplstr)
              SaltRenderError: Jinja syntax error: no filter named 'ljust'; line 13

              ---
              [...]
              # google analytics tracker
              {{ name|ljust(20) }}: {{ google_tracking_id }}    <======================
              ---
     Changes:   
```

**Comment by jfindlay** [comment]
@pille, it would be a good idea to have complete jinja support.
