### ISSUE TITLE
py as template

### ISSUE THREAD

**Issue by HontoNoRoger** [saltstack/salt#21585]
For a test, we were trying to use the `py` rendering machine as template engine for a `file.managed` state. Our use case was to build a list of rules from pillar and mine values, which matches the current minion and print them to a file.

**init.sls:**

``` salt
/etc/array:
  file.managed:
    - template: py
    - source: salt://services/net/array
```

**array:**

``` py
#!py

def run():
    preRules = []
    inputRules = []
    outputRules = []
    result = ""

    for name, rule in pillar.get('firewall').items():
        src  = salt['mine.get'](rule['src'], 'internal_ip_addrs')
        dest = salt['mine.get'](rule['dest'], 'internal_ip_addrs')
        via  = salt['mine.get'](rule['via'], 'internal_ip_addrs')

        if not match.compound(src) and not match.compound(dest) and not match.compound(via):
            continue

        if rule.port == 22:
            preRules.append("@hook pre 'conntrack ftp'")

        inputRules.append(name)


    result = "PRE:" + "\n".join(preRules) + "\nIN:" + "\n".join(inputRules) + "\n"

    return result
```

Is this supposed to work? Can one officially use python as 'template engine' in Salt? Are there any better approaches to this problem? Custom modules wouldn't be so good because the above is an exception which doesn't need to be available for further use. Therefore a template was the best idea we had.
Using Salt 2014.7.1

**Comment by basepi** [comment]
Can you please include the output of `salt '*' test.versions_report` as well as the actual result of trying to run the above state? To answer your question, I *think* this should work, but error messages and the like would be very helpful.

**Comment by whiteinge** [comment]
`file.managed` only supports a subset of Salt's renderer system as the argument to `template` ([mentioned in the docs on that arg](http://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.managed)). I'm not sure why that is the case and I think adding support for all renderers would be a cool addition. (Niche but still cool. :-) ).

**Comment by HontoNoRoger** [comment]
```
salt-master:
               Salt: 2014.7.1
             Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
             Jinja2: 2.7.2
           M2Crypto: 0.21.1
     msgpack-python: 0.3.0
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
            libnacl: Not Installed
             PyYAML: 3.10
              ioflo: Not Installed
              PyZMQ: 14.0.1
               RAET: Not Installed
                ZMQ: 4.0.4
               Mako: 0.9.1
percona2:
               Salt: 2014.7.1
             Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
             Jinja2: 2.7.2
           M2Crypto: 0.21.1
     msgpack-python: 0.3.0
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
            libnacl: Not Installed
             PyYAML: 3.10
              ioflo: Not Installed
              PyZMQ: 14.0.1
               RAET: Not Installed
                ZMQ: 4.0.4
               Mako: 0.9.1
```

Results of the execution:
```
----------
          ID: /etc/array
    Function: file.managed
      Result: False
     Comment: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 386, in py
                  data = mod.run()
                File "/var/cache/salt/minion/files/base/services/net/array", line 13, in run
                  if not match.compound(src) and not match.compound(dest):
              NameError: global name 'match' is not defined
     Started: 15:31:11.357108
    Duration: 586.286 ms
     Changes:   
----------
```
So I now changed `match.compound(src)` to `salt['match.compound'](src)` and now I get the following error:
```
----------
          ID: /etc/array
    Function: file.managed
      Result: False
     Comment: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 386, in py
                  data = mod.run()
                File "/var/cache/salt/minion/files/base/services/net/array", line 11, in run
                  dest = salt['mine.get'](rule['dest'], 'internal_ip_addrs')
              KeyError: 'dest'
     Started: 15:33:20.272099
    Duration: 1365.623 ms
     Changes:   
----------
```

Which shouldn't be the case because I gave a default value to salt['mine.get'] if the value is None, right?
This seems to be a bug, but at least py as template seems to work as intended (I misunderstood the origin of the shortcuts for pillar.get and thought mine.get or match.compound would exist, too).
