### ISSUE TITLE
Joyent Stacktracing on latest 2015.2

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt#21597]
When trying to provision an instance using the joyent driver, the following stacktrace occurs:
```
[DEBUG   ] Attempting connection to host 72.2.119.233 on port 22
[ERROR   ] There was a profile error: an integer is required
Traceback (most recent call last):
  File "/root/SaltStack/salt/salt/cloud/cli.py", line 254, in run
    self.config.get('names')
  File "/root/SaltStack/salt/salt/cloud/__init__.py", line 1370, in run_profile
    ret[name] = self.create(vm_)
  File "/root/SaltStack/salt/salt/cloud/__init__.py", line 1240, in create
    output = self.clouds[func](vm_)
  File "/root/SaltStack/salt/salt/cloud/clouds/joyent.py", line 312, in create
    salt.utils.cloud.bootstrap(vm_, __opts__)
  File "/root/SaltStack/salt/salt/utils/cloud.py", line 443, in bootstrap
    deployed = deploy_script(**deploy_kwargs)
  File "/root/SaltStack/salt/salt/utils/cloud.py", line 995, in deploy_script
    if wait_for_port(host=host, port=port, gateway=gateway):
  File "/root/SaltStack/salt/salt/utils/cloud.py", line 558, in wait_for_port
    sock.connect((test_ssh_host, test_ssh_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
TypeError: an integer is required
```
I had this working a couple of days ago and I have not changed the provider or profile configurations. I am running on the HEAD of 2015.2:
```
# salt-cloud --versions
            Salt: 2015.2.0rc1-151-g3624f39
          Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
          Jinja2: 2.7.3
        M2Crypto: 0.21.1
  msgpack-python: 0.4.4
    msgpack-pure: Not Installed
        pycrypto: 2.6.1
         libnacl: Not Installed
          PyYAML: 3.11
           ioflo: Not Installed
           PyZMQ: 14.0.1
            RAET: Not Installed
             ZMQ: 4.0.4
            Mako: 0.9.1
 Apache Libcloud: 0.16.0
```
The VM I requested to be provisioned exists on the joyent interface, and I can delete it, but the salt-cloud command itself stops at the above stacktrace.

This is very likely related, if not the same issue as, #21596. The stacktraces look very similar.

ping @techhat

**Comment by techhat** [comment]
Fixed by #21598.
