### ISSUE TITLE
EC2 Stacktracing on the latest 2015.2

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt#21596]
When trying to provision an instance, EC2 stack traces like so:
```
[DEBUG   ] Sending event - data = {'_stamp': '2015-03-12T17:48:40.950064', 'ip_address': 'x.x.x.x', 'event': 'waiting for ssh'}
[DEBUG   ] Attempting connection to host x.x.x.x on port 22
[ERROR   ] There was a profile error: an integer is required
Traceback (most recent call last):
  File "/root/SaltStack/salt/salt/cloud/cli.py", line 254, in run
    self.config.get('names')
  File "/root/SaltStack/salt/salt/cloud/__init__.py", line 1370, in run_profile
    ret[name] = self.create(vm_)
  File "/root/SaltStack/salt/salt/cloud/__init__.py", line 1240, in create
    output = self.clouds[func](vm_)
  File "/root/SaltStack/salt/salt/cloud/clouds/ec2.py", line 2214, in create
    vm_, data, ip_address, display_ssh_output
  File "/root/SaltStack/salt/salt/cloud/clouds/ec2.py", line 1968, in wait_for_instance
    gateway=ssh_gateway_config
  File "/root/SaltStack/salt/salt/utils/cloud.py", line 558, in wait_for_port
    sock.connect((test_ssh_host, test_ssh_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
TypeError: an integer is required
```
Versions report:
```
# salt-cloud --versions
            Salt: 2015.2.0rc1-151-g3624f39
          Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
          Jinja2: 2.7.3
        M2Crypto: 0.21.1
  msgpack-python: 0.4.4
    msgpack-pure: Not Installed
        pycrypto: 2.6.1
         libnacl: Not Installed
          PyYAML: 3.11
           ioflo: Not Installed
           PyZMQ: 14.0.1
            RAET: Not Installed
             ZMQ: 4.0.4
            Mako: 0.9.1
 Apache Libcloud: 0.16.0
```
The VM I requested to be provisioned exists on EC2, but the salt-cloud command itself stops at the above stacktrace.

Using the exact same provider and profile configs, provisioning a VM works very well on the 2014.7 branch.

ping @techhat

**Comment by techhat** [comment]
Fixed by #21598.
