### ISSUE TITLE
develop: spurious loader logs

### ISSUE THREAD

**Issue by kiorky** [saltstack/salt#21613]
since recently i have sometine in my master log
```
2015-03-12 23:54:20,514 [salt.master      ][ERROR   ] Error in function _pillar:
Traceback (most recent call last):
  File "/srv/mastersalt/makina-states/src/salt/salt/master.py", line 1433, in run_func
    ret = getattr(self, func)(load)
  File "/srv/mastersalt/makina-states/src/salt/salt/master.py", line 1197, in _pillar
    for func in six.itervalues(self.mminion.functions):
  File "/salt-venv/lib/python2.7/_abcoll.py", line 382, in itervalues
    yield self[key]
  File "/srv/mastersalt/makina-states/src/salt/salt/loader.py", line 887, in __getitem__
    mod.__globals__['__opts__'].update(self.opts)
```

**Comment by kiorky** [comment]
( running on : 05ddd00 )

**Comment by kiorky** [comment]
Seems iot's hard to reproduce ... since  the daily infra daemons reboot (all the master & minions, i have no more the trace ...) maybe a dangling problem that wont come back.
I do not see what can be offending the code

**Comment by jacksontj** [comment]
Hmm, the stacktrace seems to be missing something... Is that really the whole thing? Seems odd that it doesn't say what exception the traceback was :/

From the stacktrace that exists, I am not sure how you get to line 887, since the singleton stuff is disabled. I just opened a PR to remove all that stuff (#21618) since its not going to be useful.

**Comment by kiorky** [comment]
The only relevant log like that i maybe forgot to attach is : 
```
2015-03-12 23:59:18,362 [salt.master      ][INFO    ] AES payload received with command _pillar
```

I have nothing else than many
```
2015-03-12 23:59:10,190 [salt.master      ][INFO    ] AES payload received with command _pillar
2015-03-12 23:59:10,191 [salt.master      ][ERROR   ] Error in function _pillar:
Traceback (most recent call last):
  File "/srv/mastersalt/makina-states/src/salt/salt/master.py", line 1433, in run_func
    ret = getattr(self, func)(load)
  File "/srv/mastersalt/makina-states/src/salt/salt/master.py", line 1197, in _pillar
    for func in six.itervalues(self.mminion.functions):
  File "/salt-venv/lib/python2.7/_abcoll.py", line 382, in itervalues
    yield self[key]
  File "/srv/mastersalt/makina-states/src/salt/salt/loader.py", line 887, in __getitem__
    mod.__globals__['__opts__'].update(self.opts)
AttributeError: 'NoneType' object has no attribute 'update'
2015-03-12 23:59:10,235 [salt.master      ][INFO    ] AES payload received with command _master_opts
2015-03-12 23:59:10,242 [salt.master      ][INFO    ] AES payload received with command _file_list
2015-03-12 23:59:12,221 [salt.master      ][INFO    ] AES payload received with command _pillar
2015-03-12 23:59:12,221 [salt.master      ][ERROR   ] Error in function _pillar:
Traceback (most recent call last):
  File "/srv/mastersalt/makina-states/src/salt/salt/master.py", line 1433, in run_func
    ret = getattr(self, func)(load)
  File "/srv/mastersalt/makina-states/src/salt/salt/master.py", line 1197, in _pillar
    for func in six.itervalues(self.mminion.functions):
  File "/salt-venv/lib/python2.7/_abcoll.py", line 382, in itervalues
    yield self[key]
  File "/srv/mastersalt/makina-states/src/salt/salt/loader.py", line 887, in __getitem__
    mod.__globals__['__opts__'].update(self.opts)
AttributeError: 'NoneType' object has no attribute 'update'
```

Since yesterday 00:00 i do not see anymore those logs ...
I hope this this just an upgrade issue where my minion would be outdate, something like that.

**Comment by jacksontj** [comment]
That last line there is the interesting part:
```
AttributeError: 'NoneType' object has no attribute 'update'
```
Looks like somehow the __opts__ object in one of your pillar modules got set to None (which is odd to say the least). Do you have a custom pillar module which modifies __opts__? Also, I'm still 99% sure you shouldn't hit that code path at all --- since IIRC that line is for singletons only (which I disabled long ago). It might be worth pulling down that patch in my other PR to remove that chunk of code.

**Comment by rallytime** [comment]
@kiorky Thanks for filing this report, though it looks like this has cleared up for you. We can keep this open for a little while to see if it pops up again. Or, we can close it now and re-open if we need to. What do you think?

**Comment by kiorky** [comment]
I modify from time to time ``__opts__`` in my modules including ext_pillars, but i never set it to None.

The one used master side is:
https://github.com/makinacorpus/makina-states/blob/master/mc_states/pillar/mc_pillar.py


Which uses under the hood: 
https://github.com/makinacorpus/makina-states/blob/master/mc_states/modules/mc_pillar.py

**Comment by kiorky** [comment]
@rallytime you can let it a bit open, but for now i did not reproduced it again.

**Comment by rallytime** [comment]
Sounds good :)

**Comment by cachedout** [comment]
Since we've had this open a week, I'm going to go ahead and close it. @kiorky if you need this re-opened, just leave a comment and we'll be happy to do so. Thanks.
