### ISSUE TITLE
LocalClient is broken in develop & i think on 2015.2

### ISSUE THREAD

**Issue by kiorky** [saltstack/salt#21663]
I'm still investigating if my env is not broken  by my fault but my recent sync with develop, the api is timeouting a lot, making my client api call unusable.

**Comment by kiorky** [comment]
I mean the salt client python API, not the rest api.

**Comment by kiorky** [comment]
```
[ERROR   ] Timeout 10s for [job/]fun test.ping launched on xxx.net is elapsed, return will unlikely return results now
```
Since the error message is job cache related, it may also be the returners or the jobs management parts which are affected

**Comment by kiorky** [comment]
For the record:
the code im using submit stuff here: https://github.com/makinacorpus/makina-states/blob/67179de894f3477ae28b29824677728324f57431/mc_states/saltapi.py#L308
and poll for something in the job cache here: https://github.com/makinacorpus/makina-states/blob/67179de894f3477ae28b29824677728324f57431/mc_states/saltapi.py#L348

**Comment by kiorky** [comment]
ok, my bad, since i had multiple problems this afternoon, i did some multiple concurrent refactoring and just find one error now, just digging out to be sure that there is no issue still left.

**Comment by kiorky** [comment]
There is something i have in my logs which is maybe related:
```
2015-03-14 21:48:17,549 [salt.utils.process][INFO    ] Process <class 'salt.master.Publisher'> (60334) died with exit status None, restarting...

```

**Comment by kiorky** [comment]
Uhm, this is really strange, if i drop a pdb at the client call place, if i call the client call, it fails randomly about 80% ... but suceeds sometimes...

**Comment by kiorky** [comment]
increasing the client loglevel give also a lot of 
```
Unable to connect to the salt master publisher
```

**Comment by kiorky** [comment]
(and yes of course my master is up & running, and the various minions im targeting are available througth a regular ping)

**Comment by kiorky** [comment]
with the saltmaster in foreground, seems i have a trace
```

[DEBUG   ] Published command details {'tgt_type': 'glob', 'jid': '20150314224239600401', 'tgt': 'xxxt', 'ret': '', 'user': 'root', 'arg': ['20150314224229589617'], 'fun': 'saltutil.find_job'}
Process Publisher-8:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/srv/mastersalt/makina-states/src/salt/salt/master.py", line 546, in run
    payload = unpacked_package['payload']

```

**Comment by kiorky** [comment]
the offending unpacked_package has the following value:
```
[ERROR   ] {'enc': 'clear',
 'load': {'jid': '20150314224651124300',
          'minions': ['<MINION ID>']}}

```

**Comment by kiorky** [comment]
So to sum up where we are:
Calling via a script using the LocalClient (from a runner)
```
conn.cmd(target, fun, args, kwarg=kw, **rkwargs)[target]
```
Have those possible ends:

- the normal awaitened and valid result
- no return
- the call is stalling
- the exception telling us that we can connect to the master

On the master side, i have often, but not always the spurious payload thing.

**Comment by kiorky** [comment]
Ok i have either a working workaround or a fix, just polishing it.
Pb is that right now i'm on a mix of develop and 2015.2 so  im unsure where i can publish a working pull request

**Comment by kiorky** [comment]
merged fix !
