### ISSUE TITLE
KeyError: 'config.option'

### ISSUE THREAD

**Issue by bertjwregeer** [saltstack/salt#21670]
Using the latest `develop` branch: d8f1cffd1073a3f4a12fc559d6937a2b8ea6c512

    ERROR: Failure deploying thin, undefined state: _edbc7885e4f9aac9b83b35999b68d015148caf467b78fa39c05f669c0ff89878
    deploy

This is one of the tracebacks I see when I run `salt-ssh '*' state.highstate -vv -l trace`:

    [CRITICAL] Unable to import msgpack or msgpack_pure python modules
    Traceback (most recent call last):
      File "/tmp/.root_89c8ec_salt/salt-call", line 4, in <module>
        salt_call()
      File "/tmp/.root_89c8ec_salt/salt/scripts.py", line 217, in salt_call
        client.run()
      File "/tmp/.root_89c8ec_salt/salt/cli/call.py", line 50, in run
        caller.run()
      File "/tmp/.root_89c8ec_salt/salt/cli/caller.py", line 123, in run
        ret = self.call()
      File "/tmp/.root_89c8ec_salt/salt/cli/caller.py", line 181, in call
        ret['return'] = func(*args, **kwargs)
      File "/tmp/.root_89c8ec_salt/salt/modules/state.py", line 1130, in pkg
        ret = st_.call_chunks(lowstate)
      File "/tmp/.root_89c8ec_salt/salt/state.py", line 1635, in call_chunks
        running = self.call_chunk(low, running, chunks)
      File "/tmp/.root_89c8ec_salt/salt/state.py", line 1779, in call_chunk
        low = self._mod_aggregate(low, running, chunks)
      File "/tmp/.root_89c8ec_salt/salt/state.py", line 628, in _mod_aggregate
        agg_opt = self.functions['config.option']('state_aggregate')
      File "/tmp/.root_89c8ec_salt/salt/loader.py", line 880, in __getitem__
        mod = super(LazyLoader, self).__getitem__(key)
      File "/tmp/.root_89c8ec_salt/salt/utils/lazy.py", line 98, in __getitem__
        raise KeyError(key)
    KeyError: 'config.option'

**Comment by bertjwregeer** [comment]
The fix in https://github.com/saltstack/salt/pull/21636 fixes this for me. Sorry for the extra noise.

How soon will that fix be available on `2015.2`? Or on `develop`?

**Comment by rallytime** [comment]
@bertjwregeer Thanks for the report and for discovering that this is indeed fixed already. We merge 2014.7 into 2015.2 and then 2015.2 into develop on a near-daily basis, so the fix will be propagated in all branches within a couple of days.
