### ISSUE TITLE
Catch SaltClientError

### ISSUE THREAD

**Issue by cachedout** [saltstack/salt#21714]
``` python
SaltClientError: Could not access /var/cache/salt/master. Path does not exist.
Traceback (most recent call last):
  File "/root/salt/scripts/salt-syndic", line 10, in <module>
    salt_syndic()
  File "/root/salt/salt/scripts.py", line 158, in salt_syndic
    syndic.start()
  File "/root/salt/salt/cli/daemons.py", line 487, in start
    self.syndic.tune_in()
  File "/root/salt/salt/minion.py", line 2140, in tune_in
    self.local = salt.client.get_local_client(self.opts['_minion_conf_file'])
  File "/root/salt/salt/client/__init__.py", line 92, in get_local_client
    return LocalClient(mopts=opts, skip_perm_errors=skip_perm_errors)
  File "/root/salt/salt/client/__init__.py", line 132, in __init__
    self.key = self.__read_master_key()
  File "/root/salt/salt/client/__init__.py", line 157, in __read_master_key
    self.skip_perm_errors)
  File "/root/salt/salt/utils/verify.py", line 378, in check_path_traversal
    raise SaltClientError(msg)
SaltClientError: Could not access /var/cache/salt/master. Path does not exist.
Traceback (most recent call last):
  File "/root/salt/scripts/salt-syndic", line 10, in <module>
    salt_syndic()
  File "/root/salt/salt/scripts.py", line 158, in salt_syndic
    syndic.start()
  File "/root/salt/salt/cli/daemons.py", line 487, in start
    self.syndic.tune_in()
  File "/root/salt/salt/minion.py", line 2140, in tune_in
    self.local = salt.client.get_local_client(self.opts['_minion_conf_file'])
  File "/root/salt/salt/client/__init__.py", line 92, in get_local_client
    return LocalClient(mopts=opts, skip_perm_errors=skip_perm_errors)
  File "/root/salt/salt/client/__init__.py", line 132, in __init__
    self.key = self.__read_master_key()
  File "/root/salt/salt/client/__init__.py", line 157, in __read_master_key
    self.skip_perm_errors)
  File "/root/salt/salt/utils/verify.py", line 378, in check_path_traversal
    raise SaltClientError(msg)
salt.exceptions.SaltClientError: Could not access /var/cache/salt/master. Path does not exist.
```

**Comment by dmyerscough** [comment]
@cachedout I removed the /var/cache/salt/master directory and started the Salt Master and got not stacktraces and all the directories were re-created.

However, I did get some funky behaviour during the deletion of the direction when the Salt master was running.

**Comment by cachedout** [comment]
@dmyerscough This fix was only designed to handle cases where the *syndic* was depending on it during startup, as I recall.

**Comment by kevinquinnyo** [comment]
I'm getting this error with a setup that uses a salt master and a syndic.  I realize the issue here is that the exception needs to be caught, however, I'm curious why I'm getting the error in the first place.  Could someone help shed some light on this?

**Comment by alexanderglovercontractor** [comment]
Also seeing this error when trying to use salt.client.LocalClient() in a Python script in a master-less environment.

**Comment by daveneeley** [comment]
Seeing this from vagrant centos/7 with salt bootstrap, fresh minion install.

```Salt successfully configured and installed!
run_overstate set to false. Not running state.overstate.
run_highstate set to false. Not running state.highstate.
orchestrate is nil. Not running state.orchestrate.
==> default: Running provisioner: shell...
    default: Running: C:/Users/dneeley/AppData/Local/Temp/vagrant-shell20170819-8676-71xd4g.sh
==> default: remote_repo:
==> default:   url: http://artifactory/artifactory/salt-spm-local
==> default: Built package /srv/spm_build/jprofiler-201708-1.spm
==> default: [ERROR   ] An un-handled exception was caught by salt's global exception handler:
==> default: SaltClientError: Could not access /var/cache/salt/master. Path does not exist.
==> default: Traceback (most recent call last):
==> default:   File "/bin/spm", line 12, in <module>
==> default:     salt_spm()
==> default:   File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 487, in salt_spm
==> default:     spm.run()
==> default:   File "/usr/lib/python2.7/site-packages/salt/cli/spm.py", line 34, in run
==> default:     client.run(self.args)
==> default:   File "/usr/lib/python2.7/site-packages/salt/spm/__init__.py", line 115, in run
==> default:     self._local(args)
==> default:   File "/usr/lib/python2.7/site-packages/salt/spm/__init__.py", line 171, in _local
==> default:     self._local_install(args)
==> default:   File "/usr/lib/python2.7/site-packages/salt/spm/__init__.py", line 373, in _local_install
==> default:     self._install(args)
==> default:   File "/usr/lib/python2.7/site-packages/salt/spm/__init__.py", line 236, in _install
==> default:     self.client = salt.client.get_local_client(self.opts['conf_file'])
==> default:   File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 104, in get_local_client
==> default:     auto_reconnect=auto_reconnect)
==> default:   File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 160, in __init__
==> default:     self.key = self.__read_master_key()
==> default:   File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 193, in __read_master_key
==> default:     self.skip_perm_errors)
==> default:   File "/usr/lib/python2.7/site-packages/salt/utils/verify.py", line 399, in check_path_traversal
==> default:     raise SaltClientError(msg)
==> default: SaltClientError: Could not access /var/cache/salt/master. Path does not exist.
==> default: Traceback (most recent call last):
==> default:   File "/bin/spm", line 12, in <module>
==> default:     salt_spm()
==> default:   File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 487, in salt_spm
==> default:     spm.run()
==> default:   File "/usr/lib/python2.7/site-packages/salt/cli/spm.py", line 34, in run
==> default:     client.run(self.args)
==> default:   File "/usr/lib/python2.7/site-packages/salt/spm/__init__.py", line 115, in run
==> default:     self._local(args)
==> default:   File "/usr/lib/python2.7/site-packages/salt/spm/__init__.py", line 171, in _local
==> default:     self._local_install(args)
==> default:   File "/usr/lib/python2.7/site-packages/salt/spm/__init__.py", line 373, in _local_install
==> default:     self._install(args)
==> default:   File "/usr/lib/python2.7/site-packages/salt/spm/__init__.py", line 236, in _install
==> default:     self.client = salt.client.get_local_client(self.opts['conf_file'])
==> default:   File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 104, in get_local_client
==> default:     auto_reconnect=auto_reconnect)
==> default:   File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 160, in __init__
==> default:     self.key = self.__read_master_key()
==> default:   File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 193, in __read_master_key
==> default:     self.skip_perm_errors)
==> default:   File "/usr/lib/python2.7/site-packages/salt/utils/verify.py", line 399, in check_path_traversal
==> default:     raise SaltClientError(msg)
==> default: salt.exceptions.SaltClientError: Could not access /var/cache/salt/master. Path does not exist.```
