### ISSUE TITLE
Publish.Runner Fails to Parse Runner

### ISSUE THREAD

**Issue by carolynvs** [saltstack/salt#21784]
I am unable to execute any runners from a minion using publish.runner, e.g. salt-call publish.runner salt-call publish.runner doc.runner

Everything fails with the following error:

     2015-03-18 17:23:04,348 [salt.master      ][ERROR   ] Error in function minion_runner:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/master.py", line 1336, in run_func
        ret = getattr(self, func)(load)
      File "/usr/lib/python2.7/dist-packages/salt/master.py", line 1206, in minion_runner
        return self.masterapi.minion_runner(clear_load)
      File "/usr/lib/python2.7/dist-packages/salt/daemons/masterapi.py", line 778, in minion_runner
        if re.match(match, load['id']):
      File "/usr/lib/python2.7/re.py", line 137, in match
        return _compile(pattern, flags).match(string)
      File "/usr/lib/python2.7/re.py", line 244, in _compile
        raise error, v # invalid expression
    error: nothing to repeat

I have verified that the minion has permission to execute the runner with the peer_run config setting. When I execute the runner from the master using salt-run, it functions properly.

2014.7.2 (Helium) is installed on both the master and minion.

**Comment by carolynvs** [comment]
Closing... I had an invalid entry in my peer_run which was causing the exception.

**Comment by rallytime** [comment]
@carolynvs Glad you got it figured out! :)
