### ISSUE TITLE
Unavailable commands cause a stacktrace

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#21807]
This bug was found in 2015.2. When the minion starts it tries to run a command called tzutil. This command is only available by default on Windows Server 2012 and Windows 8. Older operating systems require a patch. If the utility is not available, a stack trace is returned and the minion dies.

```
[INFO    ] Executing command ['tzutil', '/g'] in directory 'C:\\Users\\Administrator'
[INFO    ] The salt minion is shut down
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
CommandExecutionError: Unable to run command ['tzutil', '/g'] with the context {'with_communicate': True, 'shell': False, 'env': {'TMP': 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2', 'COMPUTERNAME': 'WIN-94HR783DSQI', 'USERDOMAIN': 'WIN-94HR783DSQI', 'PSMODULEPATH': 'C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules\\;C:\\Program Files\\AWS Tools\\PowerShell\\', 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files', 'PROCESSOR_IDENTIFIER': 'x86 Family 6 Model 62 Stepping 4, GenuineIntel', 'PROGRAMFILES': 'C:\\Program Files', 'PROCESSOR_REVISION': '3e04', 'SYSTEMROOT': 'C:\\Windows', 'PATH': 'C:\\Python27\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\Amazon\\cfn-bootstrap\\;C:\\
Program Files\\Git\\cmd', 'TEMP': 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2', 'PROCESSOR_ARCHITECTURE': 'x86', 'ALLUSERSPROFILE': 'C:\\ProgramData', 'LOCALAPPDATA': 'C:\\Users\\Administrator\\AppData\\Local', 'HOMEPATH': '\\Users\\Administrator', 'USERNAME': 'Administrator', 'LOGONSERVER': '\\\\WIN-94HR783DSQI', 'PROMPT': '$P$G', 'COMSPEC': 'C:\\Windows\\system32\\cmd.exe', 'PROGRAMDATA': 'C:\\ProgramData', 'TRACE_FORMAT_SEARCH_PATH': '\\\\winseqfe\\release\\Windows6.0\\lh_sp2rtm\\6002.18005.090410-1830\\x86fre\\symbols.pri\\TraceFormat', 'SESSIONNAME': 'RDP-Tcp#0', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC', 'CLIENTNAME': 'GRINGO', 'FP_NO_HOST_CHECK': 'NO', 'WINDIR': 'C:\\Windows','HOMEDRIVE': 'C:', 'APPDATA': 'C:\\Users\\Administrator\\AppData\\Roaming', 'SYSTEMDRIVE': 'C:', 'PROCESSOR_LEVEL': '6', 'DFSTRACINGON': 'FALSE', 'OS': 'Windows_NT', 'PUBLIC': 'C:\\Users\\Public', 'USERPROFILE': 'C:\\Users\\Administrator'}, 'stdout': -1, 'stdin': None, 'stderr': -2, 'cwd': 'C:\\Users\\Administrator'},
reason: [Error 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Python27\Scripts\salt-minion-script.py", line 9, in <module>
    load_entry_point('salt==2015.2.0rc1-192-g03c2f37', 'console_scripts', 'salt-minion')()
  File "C:\Python27\lib\site-packages\salt\scripts.py", line 114, in salt_minion
    minion.start()
  File "C:\Python27\lib\site-packages\salt\cli\daemons.py", line 260, in start
    self.prepare()
  File "C:\Python27\lib\site-packages\salt\cli\daemons.py", line 242, in prepare
    self.minion = salt.minion.Minion(self.config)
  File "C:\Python27\lib\site-packages\salt\minion.py", line 692, in __init__
    self.returners)
  File "C:\Python27\lib\site-packages\salt\utils\schedule.py", line 264, in __init__
    self.time_offset = self.functions.get('timezone.get_offset', lambda: '0000')()
  File "C:\Python27\lib\site-packages\salt\modules\win_timezone.py", line 494, in get_offset
    zone = __salt__['cmd.run'](['tzutil', '/g'], python_shell=False)
  File "C:\Python27\lib\site-packages\salt\modules\cmdmod.py", line 636, in run
    use_vt=use_vt)
  File "C:\Python27\lib\site-packages\salt\modules\cmdmod.py", line 372, in _run
    .format(cmd, kwargs, exc)
```

Running Salt 2015.2 head
Windows Server 2008 32bit

Also tested on 2014.7 HEAD with no problems.

**Comment by UtahDave** [comment]
This may not be Windows specific. Can someone test this on another OS, as well?

**Comment by twangboy** [comment]
https://github.com/saltstack/salt/pull/21817
