### ISSUE TITLE
salt.util.http only allows https to port 443

### ISSUE THREAD

**Issue by deuscapturus** [saltstack/salt#21904]
https://github.com/saltstack/salt/blob/develop/salt/utils/http.py#L277

```
           Salt: 2015.2.0
         Python: 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.5
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.5.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
```

http request of the url  https://mysite.com:8080/file.txt will result in the following error:
```
[DEBUG   ] Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt\states\file.py", line 1528, in managed
    follow_symlinks)
  File "c:\salt\bin\lib\site-packages\salt\modules\file.py", line 3531, in manage_file
    sfn = __salt__['cp.cache_file'](source, saltenv)
  File "c:\salt\bin\lib\site-packages\salt\modules\cp.py", line 348, in cache_file
    result = __context__['cp.fileclient'].cache_file(path, saltenv)
  File "c:\salt\bin\lib\site-packages\salt\fileclient.py", line 152, in cache_file
    return self.get_url(path, '', True, saltenv)
  File "c:\salt\bin\lib\site-packages\salt\fileclient.py", line 595, in get_url
    stream=True
  File "c:\salt\bin\lib\site-packages\salt\utils\http.py", line 277, in query
    sock.connect((hostname, 443))
  File "c:\salt\bin\lib\socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
gaierror: [Errno 11001] getaddrinfo failed
[ERROR   ] Unable to manage file: [Errno 11001] getaddrinfo failed
```

**Comment by deuscapturus** [comment]
False report.
