### ISSUE TITLE
salt-ssh NameError: global name 'msgpack' is not defined (salt-ssh 2014.7.2 (Helium))

### ISSUE THREAD

**Issue by arr2036** [saltstack/salt#21922]
```python
    Function: file.recurse
     Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/root/salt/state.py", line 1531, in call
                  **cdata['kwargs'])
                File "/root/salt/states/file.py", line 1982, in recurse
                  source, source_hash = __salt__['file.source_list'](sources, '', __env__)
                File "/root/salt/modules/file.py", line 2398, in source_list
                  mfiles = __salt__['cp.list_master'](saltenv)
                File "/root/salt/modules/cp.py", line 514, in list_master
                  return __context__['cp.fileclient'].file_list(saltenv, prefix)
                File "/root/salt/fileclient.py", line 1050, in file_list
                  return channel.send(load)
                File "/root/salt/fileserver/__init__.py", line 566, in send
                  return getattr(self.fs, cmd)(load)
                File "/root/salt/fileserver/__init__.py", line 450, in file_list
                  ret.update(self.servers[fstr](load))
                File "/root/salt/fileserver/roots.py", line 304, in file_list
                  return _file_lists(load, 'files')
                File "/root/salt/fileserver/roots.py", line 292, in _file_lists
                  __opts__, ret, list_cache, w_lock
                File "/root/salt/fileserver/__init__.py", line 147, in write_file_list_cache
                  fp_.write(serial.dumps(data))
                File "/root/salt/payload.py", line 115, in dumps
                  return msgpack.dumps(msg)
              NameError: global name 'msgpack' is not defined
```

Saw you guys were collecting these...  https://github.com/saltstack/salt/issues/20276. Above is with https://github.com/saltstack/salt/pull/20364 applied.
```
/etc/raddb:
    file.recurse:
        - source: salt://freeradius
        - user: radiusd
        - group: radiusd
        - dir_mode: 2550
        - file_mode: 0440
        - clean: true
        - require:
            - pkg: install_freeradius
```

**Comment by rallytime** [comment]
Thanks for opening a new issue. 

ping @basepi

**Comment by basepi** [comment]
I can reproduce this.

**Comment by basepi** [comment]
Interestingly, this is working against a Cent 6 box but not against an Ubuntu 14.04 box.

**Comment by basepi** [comment]
Fixed in #21965.

**Comment by arr2036** [comment]
Thanks! As a temporary work around installing python msgpack on the minions also worked, though obviously that's not ideal :)

**Comment by basepi** [comment]
Far from ideal. We're still working on tracking down all of these msgpack calls and gating them. We're one step closer!
