### ISSUE TITLE
Eauth authentication error when passing incorrect function pattern

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#21969]
When calling an incorrectly formatted wheel function an eauth authentication error is thrown. (I expect this same problem applies to RunnerClient as well.) This is similar to issue #6420.

We need to determine where best to improve this workflow and error message without compromising the security of the eauth checks. The current behavior does not indicate to to the user that there is a syntax error. Just checking the syntax is `module.function` would be a step forward. Could/should we also check for non-existing functions?

``` python
>>> wheel.cmd_sync({'fun': 'salt.wheel.key.list_all', 'token': '38f6a103a3a5b1effbda200e57b05423'})
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/shouse/src/salt/salt/salt/wheel/__init__.py", line 100, in cmd_sync
    return self.master_call(**low)
  File "/Users/shouse/src/salt/salt/salt/wheel/__init__.py", line 79, in master_call
    raise_error(**ret['error'])
  File "/Users/shouse/src/salt/salt/salt/utils/error.py", line 32, in raise_error
    raise ex(message)
TokenAuthenticationError: Authentication failure of type "token" occurred for user saltdev.
```

[Relevant salt-users post](https://groups.google.com/d/topic/salt-users/9SGmQPDnNDE/discussion).

**Comment by rallytime** [comment]
Hi @whiteinge 

I have fixed this for wheel and runner funcs as described in #43203. This should be more helpful for users experiencing this issue, and is a start towards #6420.

Token is valid, command is incorrect:
```
>>> wheel.cmd_sync({'fun': 'salt.wheel.key.list_all', 'token': token})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/SaltStack/salt/salt/wheel/__init__.py", line 96, in cmd_sync
    return self.master_call(**low)
  File "/root/SaltStack/salt/salt/wheel/__init__.py", line 75, in master_call
    salt.utils.error.raise_error(**ret['error'])
  File "/root/SaltStack/salt/salt/utils/error.py", line 36, in raise_error
    raise ex(message)
salt.exceptions.SaltInvocationError: A command invocation error occurred: Check syntax.
```
Command is still incorrect, but the token isn't valid (no behavior change from before):
```
>>> wheel.cmd_sync({'fun': 'salt.wheel.key.list_all', 'token': 'some-bad-token'})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/SaltStack/salt/salt/wheel/__init__.py", line 96, in cmd_sync
    return self.master_call(**low)
  File "/root/SaltStack/salt/salt/wheel/__init__.py", line 75, in master_call
    salt.utils.error.raise_error(**ret['error'])
  File "/root/SaltStack/salt/salt/utils/error.py", line 36, in raise_error
    raise ex(message)
salt.exceptions.TokenAuthenticationError: Authentication failure of type "token" occurred.
```

**Comment by whiteinge** [comment]
Wow, blast from the past. Thanks for the fix! Verified locally -- it works great.
