### ISSUE TITLE
chef.solo IndexError: list index out of range

### ISSUE THREAD

**Issue by scaissie** [saltstack/salt#21997]
The /var/log/chef-solo.log file shows that chef-solo runs successfully, but salt returns this error:
```
          ID: chef-solo-run
    Function: chef.solo
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1531, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/states/chef.py", line 136, in solo
                  return _run(name, 'chef.solo', kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/chef.py", line 148, in _run
                  if _has_changes(result['stdout']):
                File "/usr/lib/python2.7/dist-packages/salt/states/chef.py", line 168, in _has_changes
                  _summary(stdout),
                File "/usr/lib/python2.7/dist-packages/salt/states/chef.py", line 162, in _summary
                  return stdout.splitlines()[-1]
              IndexError: list index out of range
     Started: 16:54:05.368652
    Duration: 6188.671 ms
     Changes:
```
```
chef-solo-run:
  chef.solo:
    - config: /var/chef/solo.rb
    - json-attributes: /var/chef/json/config.dev.json
    - override-runlist: "recipe[QFSessionServer::deploy]"
```
```
# salt --versions-report
           Salt: 2014.7.1
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.22
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
```
```
# chef-solo --version
Chef: 12.1.2
```

**Comment by rallytime** [comment]
Thanks for the report @scaissie. We should definitely get that stacktrace cleaned up.

@amendlik - It looks like this is your code. Would you mind taking a look here?

**Comment by amendlik** [comment]
Please try the fix at:
https://github.com/amendlik/salt/commit/11536f6cc5e71c95e5355614eb4aa11c0fde66dd

**Comment by rallytime** [comment]
Thanks @amendlik! If this patch works, it'd be great to get a pull request in for this.

@scaissie If you try the patch from @amendlik list above, does that help resolve this issue for you?

**Comment by scaissie** [comment]
That fixed the problem. Thanks for the quick fix.

**Comment by rallytime** [comment]
Awesome! Thanks for testing! 

@amendlik We'd love to see a PR with your changes! Thanks very much!

**Comment by rallytime** [comment]
Awesome! Thanks!

**Comment by rallytime** [comment]
@scaissie Now that the PR is in, are we good to close this issue out?

**Comment by scaissie** [comment]
Yes, thanks.
