### ISSUE TITLE
Regression (?) in `Eauth` module.

### ISSUE THREAD

**Issue by dbalan** [saltstack/salt#22031]
LocalClient behaves different when `eauth` is used, this started happening after we upgraded to `v2014.7.2`.

When someone tries to query a group of machines in which one machine is down - `LocalClient` using `eauth` will raise `salt.exceptions.EauthAuthenticationError`, whereas LocalClient run from the user running salt will return data from all minions that are up in the selection.
## Example tracebacks.
1. Local

```
$ python
Python 2.7.3 (default, Mar 13 2014, 11:03:55)
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import salt.client
>>> c = salt.client.LocalClient()
>>> c.cmd('selector_with_one_minion_down', 'grains.item', ['fqdn'], expr_form='compound')
{} # data omitted, returns data from minions that are up.

```
1. Using `eauth`

```
>>> c.cmd('selector_with_one_minion_down', 'grains.item', ['fqdn'], expr_form='compound', username='user', password=pw, eauth='pam')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 534, in cmd
    **kwargs):
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 1206, in get_cli_event_returns
    expect_minions=(verbose or show_timeout)
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 915, in get_iter_returns
    jinfo = self.gather_job_info(jid, tgt, tgt_type)
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 209, in gather_job_info
    timeout=timeout,
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 286, in run_job
    return self._check_pub_data(pub_data)
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 221, in _check_pub_data
    'Failed to authenticate!  This is most likely because this '
salt.exceptions.EauthAuthenticationError: Failed to authenticate!  This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage)
```
## version information

```
sudo salt --versions-report
                  Salt: 2014.7.2
                Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
                Jinja2: 2.6
              M2Crypto: 0.21.1
        msgpack-python: 0.1.10
          msgpack-pure: Not Installed
              pycrypto: 2.6
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 13.1.0
                  RAET: Not Installed
                   ZMQ: 3.2.3
                  Mako: 0.7.0
 Debian source package: 2014.7.2+ds-1~bpo70+1
```

**Comment by rallytime** [comment]
Thanks for the report @dbalan. I am not very familiar with the eauth code, but I think @jfindlay might be able to help, or maybe @cro. I think some fixes have been made recently to this code since 2014.7.2, but I am not certain.

**Comment by dbalan** [comment]
any update on this? I can provide more info if you need.
