### ISSUE TITLE
cmd.run stack traces when you try to run a shell command (windows)

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#22038]
salt '*' cmd.run 'dir c:\'
 ```
The minion function caused an exception: Traceback (most recent call last):        
  File "C:\Python27\lib\site-packages\salt\minion.py", line 1142, in _thread_return
    return_data = func(*args, **kwargs)                                            
  File "C:\Python27\lib\site-packages\salt\modules\cmdmod.py", line 640, in run    
    use_vt=use_vt)                                                                 
  File "C:\Python27\lib\site-packages\salt\modules\cmdmod.py", line 368, in _run   
    cmd = shlex.split(cmd)                                                         
  File "C:\Python27\lib\shlex.py", line 279, in split                              
    return list(lex)                                                               
  File "C:\Python27\lib\shlex.py", line 269, in next                               
    token = self.get_token()                                                       
  File "C:\Python27\lib\shlex.py", line 96, in get_token                           
    raw = self.read_token()                                                        
  File "C:\Python27\lib\shlex.py", line 191, in read_token                         
    raise ValueError, "No escaped character"                                       
ValueError: No escaped character
```

This is only for commands like "dir" that have no corresponding ".exe"

**Comment by rallytime** [comment]
Thanks @twangboy! :)

It might be good to post what version of salt you're seeing this on.

**Comment by twangboy** [comment]
Here's the version info:
```
           Salt: 2015.2.0rc1-243-gea1c121
             Python: 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]
             Jinja2: 2.7.3
           M2Crypto: 0.21.1
     msgpack-python: 0.4.5
       msgpack-pure: Not Installed
           pycrypto: 2.6
            libnacl: Not Installed
             PyYAML: 3.11
              ioflo: Not Installed
              PyZMQ: 14.5.0
               RAET: Not Installed
                ZMQ: 4.0.5
               Mako: Not Installed
```

**Comment by iggy** [comment]
You sure it's not because the command ends with \? Try 'dir c:'

**Comment by twangboy** [comment]
This is because 2015.2 now uses cmd.shell to handle shell specific commands. cmd.run requires an actual executable file.

**Comment by iggy** [comment]
Ooh... I hate that change...

**Comment by twangboy** [comment]
It looks like this has been fixed to maintain backwards compatibility.
