### ISSUE TITLE
dmidecode grains is broken on develop if no dmidecode

### ISSUE THREAD

**Issue by kiorky** [saltstack/salt#22033]
cc @gutard

```
saltenv=saltenv)['stdout']
File "/salt-venv/salt/src/salt/salt/modules/cmdmod.py", line 376, in _run
.format(cmd, kwargs, exc)
CommandExecutionError: Unable to run command ['dmidecode'] with the context {'with_communicate': True, 'shell': False, 'env': {'MAILTO': 'xxxsx', 'LANG': 'fr_FR.UTF-8', 'LC_ALL': 'C', 'SHELL': '/bin/sh', 'SHLVL': '1', 'PWD': '/root', 'LOGNAME': 'root', 'PATH': '/srv/salt/makina-states/bin:/usr/bin:/bin', 'HOME': '/root'}, 'stdout': -1, 'close_fds': True, 'stdin': None, 'stderr': -2, 'cwd': '/root'}, reason: [Errno 2] No such file or directory
Traceback (most recent call last):
File "/srv/salt/makina-states/bin/salt-call", line 6, in <module>
exec(compile(open(file).read(), file, 'exec'))
File "/salt-venv/salt/src/salt/scripts/salt-call", line 11, in <module>
salt_call()
File "/salt-venv/salt/src/salt/salt/scripts.py", line 222, in salt_call
client.run()
File "/salt-venv/salt/src/salt/salt/cli/call.py", line 40, in run
caller = salt.cli.caller.Caller.factory(self.config)
File "/salt-venv/salt/src/salt/salt/cli/caller.py", line 71, in factory
return ZeroMQCaller(opts, **kwargs)
File "/salt-venv/salt/src/salt/salt/cli/caller.py", line 253, in init
super(ZeroMQCaller, self)._init__(opts)
File "/salt-venv/salt/src/salt/salt/cli/caller.py", line 94, in init
self.minion = salt.minion.SMinion(opts)
File "/salt-venv/salt/src/salt/salt/minion.py", line 303, in init
opts['grains'] = salt.loader.grains(opts)
File "/salt-venv/salt/src/salt/salt/loader.py", line 458, in grains
ret = fun()
File "/salt-venv/salt/src/salt/salt/grains/core.py", line 1277, in os_data
grains.update(_hw_data(grains))
File "/salt-venv/salt/src/salt/salt/grains/core.py", line 1710, in _hw_data
grains.update(_dmidecode_data(linux_dmi_regex))
File "/salt-venv/salt/src/salt/salt/grains/core.py", line 1635, in _dmidecode_data
out = salt['cmd.run']('dmidecode')
File "/salt-venv/salt/src/salt/salt/modules/cmdmod.py", line 516, in _run_quiet
saltenv=saltenv)['stdout']
File "/salt-venv/salt/src/salt/salt/modules/cmdmod.py", line 376, in _run
.format(cmd, kwargs, exc)
salt.exceptions.CommandExecutionError: Unable to run command ['dmidecode'] with the context {'with_communicate': True, 'shell': False, 'env': {'MAILTO': 'xxx', 'LANG': 'fr_FR.UTF-8', 'LC_ALL': 'C', 'SHELL': '/bin/sh', 'SHLVL': '1', 'PWD': '/root', 'LOGNAME': 'root', 'PATH': '/srv/salt/makina-states/bin:/usr/bin:/bin', 'HOME': '/root'}, 'stdout': -1, 'close_fds': True, 'stdin': None, 'stderr': -2, 'cwd': '/root'}, reason: [Errno 2] No such file or directory
```

**Comment by cachedout** [comment]
Closed per merge of #22037
