### ISSUE TITLE
2015.2.0rc1 mine.send cannot handle multiple arguments

### ISSUE THREAD

**Issue by clinta** [saltstack/salt#22058]
mine.send seems to no longer be able to handle calling modules that require arguments

```
# salt-call mine.send network.ip_addrs eth0
[DEBUG   ] Configuration file path: /etc/salt/minion
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'pki', 'tcp://127.0.0.1:4506')
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded mine.send
[DEBUG   ] LazyLoaded network.ip_addrs
Passed invalid arguments: '__pub_pid' is an invalid keyword argument for 'salt.loaded.ext.module.network.ip_addrs'. If you were trying to pass additional data to be used in a template context, please populate 'context' with 'key: value' pairs.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 138, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/mine.py", line 159, in send
    expected_extra_kws=MINE_INTERNAL_KEYWORDS)
  File "/usr/lib/python2.7/dist-packages/salt/utils/__init__.py", line 799, in format_call
    '' if 'full' not in ret else ' Please update your state files.'
SaltInvocationError: '__pub_pid' is an invalid keyword argument for 'salt.loaded.ext.module.network.ip_addrs'. If you were trying to pass additional data to be used in a template context, please populate 'context' with 'key: value' pairs.
```

Doesn't seem to matter whether using keywords or not:
```
# salt-call mine.send network.ip_addrs interface=eth0
[DEBUG   ] Configuration file path: /etc/salt/minion
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'pki', 'tcp://127.0.0.1:4506')
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded mine.send
[DEBUG   ] LazyLoaded network.ip_addrs
Passed invalid arguments: '__pub_pid' is an invalid keyword argument for 'salt.loaded.ext.module.network.ip_addrs'. If you were trying to pass additional data to be used in a template context, please populate 'context' with 'key: value' pairs.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 138, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/mine.py", line 159, in send
    expected_extra_kws=MINE_INTERNAL_KEYWORDS)
  File "/usr/lib/python2.7/dist-packages/salt/utils/__init__.py", line 799, in format_call
    '' if 'full' not in ret else ' Please update your state files.'
SaltInvocationError: '__pub_pid' is an invalid keyword argument for 'salt.loaded.ext.module.network.ip_addrs'. If you were trying to pass additional data to be used in a template context, please populate 'context' with 'key: value' pairs.
```

**Comment by basepi** [comment]
Thanks for filing this. We just need to clean the kwargs in mine.send. Pull request incoming.

**Comment by basepi** [comment]
Fixed: https://github.com/saltstack/salt/pull/22097
