### ISSUE TITLE
2015.2 grains.items get_colors() takes at most 1 argument (2 given)

### ISSUE THREAD

**Issue by steverweber** [saltstack/salt#22087]
```
root@salt lib]# salt --version
salt 2015.2.0rc1-1371-g13331b0 (Lithium)
```

```
[root@salt lib]# salt-call grains.items
[DEBUG   ] Configuration file path: /etc/salt/minion
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/0security.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/0security.conf
[DEBUG   ] Including configuration from '/etc/salt/minion.d/99-master-address.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/99-master-address.conf
[DEBUG   ] Including configuration from '/etc/salt/minion.d/999-overrides.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/999-overrides.conf
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'cloud.math.xxxxx', 'tcp://129.97.6.131:4506')
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded grains.items
[DEBUG   ] Re-using SAuth for ('/etc/salt/pki/minion', 'cloud.math.xxxxx', 'tcp://129.97.6.131:4506')
[DEBUG   ] LazyLoaded grains.output
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: get_colors() takes at most 1 argument (2 given)
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 225, in salt_call
    client.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/call.py", line 69, in run
    caller.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/caller.py", line 246, in run
    self.opts)
  File "/usr/lib/python2.6/site-packages/salt/output/__init__.py", line 94, in display_output
    display_data = try_printout(data, out, opts)
  File "/usr/lib/python2.6/site-packages/salt/output/__init__.py", line 46, in try_printout
    return get_printout(out, opts)(data).rstrip()
  File "/usr/lib/python2.6/site-packages/salt/output/grains.py", line 38, in output
    colors = salt.utils.get_colors(__opts__.get('color'), __opts__.get('color_theme'))
TypeError: get_colors() takes at most 1 argument (2 given)
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 225, in salt_call
    client.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/call.py", line 69, in run
    caller.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/caller.py", line 246, in run
    self.opts)
  File "/usr/lib/python2.6/site-packages/salt/output/__init__.py", line 94, in display_output
    display_data = try_printout(data, out, opts)
  File "/usr/lib/python2.6/site-packages/salt/output/__init__.py", line 46, in try_printout
    return get_printout(out, opts)(data).rstrip()
  File "/usr/lib/python2.6/site-packages/salt/output/grains.py", line 38, in output
    colors = salt.utils.get_colors(__opts__.get('color'), __opts__.get('color_theme'))
TypeError: get_colors() takes at most 1 argument (2 given)
```

**Comment by rallytime** [comment]
Thanks @steverweber. I'll take a look here.

**Comment by rallytime** [comment]
@steverweber I cannot reproduce this. I have tested this both from the current [HEAD of 2015.2](https://github.com/saltstack/salt/commit/13331b002cbf0ad1300ae7567313d6f0afbb10e8) as well as the current [HEAD of develop](https://github.com/saltstack/salt/commit/5c70cdd349a088e72e45b46cfa5ebf409bcec8fb) and I am not hitting this stacktrace:
```
# salt-call grains.items
local:
    ----------
    SSDs:
        - xvda
        - xvde
    cpu_flags:
        - fpu


<snipped>


    zmqversion:
        4.0.4
```

**Comment by steverweber** [comment]
i'll investigate.

**Comment by steverweber** [comment]
humm it seems that
/salt/output/grains.py
was removed.

but after removing it and rerunning bootstrap it returns...

**Comment by steverweber** [comment]
I dont see the file in bootstrap log..
```
byte-compiling /usr/lib/python2.6/site-packages/salt/output/virt_query.py to virt_query.pyc
byte-compiling /usr/lib/python2.6/site-packages/salt/output/__init__.py to __init__.pyc
byte-compiling /usr/lib/python2.6/site-packages/salt/output/progress.py to progress.pyc
byte-compiling /usr/lib/python2.6/site-packages/salt/output/no_out.py to no_out.pyc
byte-compiling /usr/lib/python2.6/site-packages/salt/output/newline_values_only.py to newline_values_only.pyc
byte-compiling /usr/lib/python2.6/site-packages/salt/output/yaml_out.py to yaml_out.pyc
byte-compiling /usr/lib/python2.6/site-packages/salt/output/compact.py to compact.pyc
byte-compiling /usr/lib/python2.6/site-packages/salt/output/raw.py to raw.pyc
byte-compiling /usr/lib/python2.6/site-packages/salt/output/highstate.py to highstate.pyc
byte-compiling /usr/lib/python2.6/site-packages/salt/output/pprint_out.py to pprint_out.pyc
byte-compiling /usr/lib/python2.6/site-packages/salt/output/json_out.py to json_out.pyc
byte-compiling /usr/lib/python2.6/site-packages/salt/output/key.py to key.pyc
byte-compiling /usr/lib/python2.6/site-packages/salt/output/nested.py to nested.pyc
byte-compiling /usr/lib/python2.6/site-packages/salt/output/no_return.py to no_return.pyc
byte-compiling /usr/lib/python2.6/site-packages/salt/output/txt.py to txt.pyc
byte-compiling /usr/lib/python2.6/site-packages/salt/output/overstatestage.py to overstatestage.pyc
```

**Comment by steverweber** [comment]
opps nm forgot to rm the pyc and pyo files
. all good.

**Comment by rallytime** [comment]
Ah, right! Nice! Thanks for taking another look and glad this was resolved. :)
