### ISSUE TITLE
batch mode from master of master doesnt work as expected -- 

### ISSUE THREAD

**Issue by mimianddaniel** [saltstack/salt#22110]
running `salt '*' test.ping -b 50` runs against the minions (intermediary masters or minions directly connected) only.  This is on rc1

**Comment by cachedout** [comment]
Sorry, didn't mean to close that.

**Comment by jfindlay** [comment]
2015.2.0rc1

**Comment by jfindlay** [comment]
@mimianddaniel, I am unsure about what the problem is you are having.  Do you want syndics to respond to `test.ping` as well?

**Comment by mimianddaniel** [comment]
this is not just for test.ping, i tested it using cmd.run as well.

**Comment by jfindlay** [comment]
No, sorry.  So what you're saying is that when you batch commands, then minions connected through syndics do not respond?  Do you know if this behavior has changed or has always been like this?

**Comment by mimianddaniel** [comment]
6c5f3f8d2eb8a810d3ec02982656c7ffe5fd46cc be an issue? Seems like it got commited on the 27th.

**Comment by jfindlay** [comment]
@cachedout, any comments?

**Comment by jfindlay** [comment]
Duplicate of  #18358.

**Comment by rallytime** [comment]
@mimianddaniel I am pretty sure that this is a duplicate of the bug referenced above. This has been fixed at the head of the 2014.7 and 2015.2 branches. Can you give either of those a try and let us know if this has been fixed for you? Thanks!

**Comment by mimianddaniel** [comment]
Still having same issue from master of master.  Just upgraded to the latest 2015.2 this morning as well.

**Comment by rallytime** [comment]
Do you have a minion installed on the machine that your syndic is on where the minion is pointed to the master of masters? Might be worth giving that a try.

**Comment by mimianddaniel** [comment]
yes, on all intermediary masters

**Comment by mimianddaniel** [comment]
upgraded to 2015.5 release and tested the batch mode.. it works for the first set of batch minions but get the following error for the subsequent set and stops. 

ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: unhashable type: 'dict'
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/scripts.py", line 349, in salt_main
    client.run()
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/cli/salt.py", line 98, in run
    for res in batch.run():
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/cli/batch.py", line 175, in run
    if minion not in parts:
TypeError: unhashable type: 'dict'
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/scripts.py", line 349, in salt_main
    client.run()
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/cli/salt.py", line 98, in run
    for res in batch.run():
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/cli/batch.py", line 175, in run
    if minion not in parts:
TypeError: unhashable type: 'dict'

           Salt: 2015.5.0
         Python: 2.7.9 (default, Dec 30 2014, 13:07:54)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.6.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed

**Comment by mimianddaniel** [comment]
Different errors while running batch mode from non master of master. 

ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: unhashable type: 'dict'
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/scripts.py", line 349, in salt_main
    client.run()
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/cli/salt.py", line 98, in run
    for res in batch.run():
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/cli/batch.py", line 175, in run
    if minion not in parts:
TypeError: unhashable type: 'dict'
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/scripts.py", line 349, in salt_main
    client.run()
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/cli/salt.py", line 98, in run
    for res in batch.run():
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/cli/batch.py", line 175, in run
    if minion not in parts:
TypeError: unhashable type: 'dict'
