### ISSUE TITLE
intermittent setup.py glitches (develop)

### ISSUE THREAD

**Issue by kiorky** [saltstack/salt#22132]
Sometime i get some
```
salt-call --local  -lall pillar.items
Traceback (most recent call last):
  File "/srv/mastersalt/makina-states/bin/salt-call", line 4, in <module>
    __import__('pkg_resources').require('salt===2014.7.0-488-g7ac121b')
  File "/salt-venv/mastersalt/local/lib/python2.7/site-packages/pkg_resources.py", line 2716, in <module>
    working_set.require(__requires__)
  File "/salt-venv/mastersalt/local/lib/python2.7/site-packages/pkg_resources.py", line 685, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/salt-venv/mastersalt/local/lib/python2.7/site-packages/pkg_resources.py", line 555, in resolve
    requirements = list(requirements)[::-1]  # set up the stack
  File "/salt-venv/mastersalt/local/lib/python2.7/site-packages/pkg_resources.py", line 2563, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/salt-venv/mastersalt/local/lib/python2.7/site-packages/pkg_resources.py", line 2531, in scan_list
    raise ValueError("Expected "+item_name+" in",line,"at",line[p:])
ValueError: ('Expected version spec in', 'salt===2014.7.0-488-g7ac121b', 'at', '===2014.7.0-488-g7ac121b')
```
Re running some setup.py develop fixes it, but i got bitten by this muliple times, there may be a bug.

**Comment by kiorky** [comment]
I think that the thing that append the git changeset is really harmful with nowadays setuptools and should be removed.

**Comment by kiorky** [comment]
a glitched pkginfo:

cat /salt-venv/salt/src/salt/salt.egg-info/PKG-INFO
```
Metadata-Version: 1.0
Name: salt
Version: 2014.7.0-488-g7ac121b
Summary: Portable, distributed, remote execution and configuration management system
Home-page: http://saltstack.org
Author: Thomas S Hatch
Author-email: thatch45@gmail.com
License: Apache Software License 2.0
Description: UNKNOWN
Platform: UNKNOWN
root@online-dc3-1:/sr
```

**Comment by kiorky** [comment]
and after a pip intall -e . in the salt checkout (although the previous  command was also a pip install -e)
cat /salt-venv/salt/src/salt/salt.egg-info/PKG-INFO
```
Metadata-Version: 1.0
Name: salt
Version: 2014.7.0-501-g3f8c1a7
Summary: Portable, distributed, remote execution and configuration management system
Home-page: http://saltstack.org
Author: Thomas S Hatch
Author-email: thatch45@gmail.com
License: Apache Software License 2.0
Description: UNKNOWN
Platform: UNKNOWN
```

**Comment by kiorky** [comment]
damn im not reproducing it right now, but it had bitten me more than 15 times on multiples boxes in the last month

**Comment by basepi** [comment]
Hmmm, keep us posted if you can find a way to reproduce this consistently.

**Comment by kiorky** [comment]
seems gone ...
