### ISSUE TITLE
"unexpected keyword argument 'merge'" on 2014.7.2 (salt-ssh)

### ISSUE THREAD

**Issue by quixoten** [saltstack/salt#22131]
I'm invoking `salt-ssh` on an Archlinux box to configure an Ubuntu 14.04 virtual machine. I'm using the latest version of salt (version info below). I'm using the [salt-formula](https://github.com/saltstack-formulas/salt-formula). My top file looks like this:

```saltstate
include:
  - salt

base:
  '*':
    - salt.master
```

### Full Output

```
archlinux$ salt-ssh '*' state.highstate
[CRITICAL] Rendering SLS 'base:salt.master' failed: Jinja error: get() got an unexpected keyword argument 'merge'
/tmp/.vagrant_1d5674__salt/running_data/var/cache/salt/minion/files/base/salt/map.jinja(71):
---
[...]
                'syndic_service': 'salt_syndic'},
}, merge=salt['pillar.get']('salt:lookup')) %}

{% do default_settings.salt.update(distro_map) %}

{% set salt_settings = salt['pillar.get']('salt', default=default_settings.salt,    <======================
  merge=True) %}
---
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 280, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 1, in top-level template code
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1013, in make_module
    return TemplateModule(self, self.new_context(vars, shared, locals))
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1070, in __init__
    self._body_stream = list(template.root_render_func(context))
  File "/tmp/.vagrant_1d5674__salt/running_data/var/cache/salt/minion/files/base/salt/map.jinja", line 71, in top-level template code
    {% set salt_settings = salt['pillar.get']('salt', default=default_settings.salt,
TypeError: get() got an unexpected keyword argument 'merge'
```

### Version Info

```
archlinux$ salt --versions-report
           Salt: 2014.7.2
         Python: 2.7.9 (default, Dec 11 2014, 04:42:00)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.5.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
```

```
ubuntu:/tmp/.vagrant_1d5674__salt$ python2.7 salt-call --versions-report
[CRITICAL] Unable to import msgpack or msgpack_pure python modules
           Salt: 2014.7.2
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.3
       M2Crypto: Not Installed
 msgpack-python: Not Installed
   msgpack-pure: Not Installed
       pycrypto: Not Installed
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: Not Installed
           RAET: Not Installed
            ZMQ: Not Installed
           Mako: Not Installed
```

**Comment by jfindlay** [comment]
@quixoten, thanks for the report.

**Comment by jcftang** [comment]
I'd like to add that this issue seems to affect 2014.7.4 as well
