### ISSUE TITLE
salt-cloud throws traceback if sdb value is referenced

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#22207]
The `sdb://thing` reference is in my master config.

```python
% salt-cloud --list-locations amazon -l debug
[ERROR   ] 'module' object has no attribute 'sdb'
Traceback (most recent call last):
  File "/Users/shouse/src/salt/salt/salt/utils/parsers.py", line 155, in parse_args
    process_option_func()
  File "/Users/shouse/src/salt/salt/salt/utils/parsers.py", line 435, in process_config_dir
    self.config.update(self.setup_config())
  File "/Users/shouse/src/salt/salt/salt/utils/parsers.py", line 2470, in setup_config
    return config.cloud_config(self.get_config_file_path())
  File "/Users/shouse/src/salt/salt/salt/config.py", line 1268, in cloud_config
    apply_sdb(opts)
  File "/Users/shouse/src/salt/salt/salt/config.py", line 1048, in apply_sdb
    sdb_opts[key] = apply_sdb(opts, value)
  File "/Users/shouse/src/salt/salt/salt/config.py", line 1043, in apply_sdb
    return salt.utils.sdb.sdb_get(sdb_opts, opts)
AttributeError: 'module' object has no attribute 'sdb'
Usage: salt-cloud

salt-cloud: error: Error while processing <bound method SaltCloud.process_config_dir of <salt.cloud.cli.SaltCloud object at 0x102f1f750>>: Traceback (most recent call last):
  File "/Users/shouse/src/salt/salt/salt/utils/parsers.py", line 155, in parse_args
    process_option_func()
  File "/Users/shouse/src/salt/salt/salt/utils/parsers.py", line 435, in process_config_dir
    self.config.update(self.setup_config())
  File "/Users/shouse/src/salt/salt/salt/utils/parsers.py", line 2470, in setup_config
    return config.cloud_config(self.get_config_file_path())
  File "/Users/shouse/src/salt/salt/salt/config.py", line 1268, in cloud_config
    apply_sdb(opts)
  File "/Users/shouse/src/salt/salt/salt/config.py", line 1048, in apply_sdb
    sdb_opts[key] = apply_sdb(opts, value)
  File "/Users/shouse/src/salt/salt/salt/config.py", line 1043, in apply_sdb
    return salt.utils.sdb.sdb_get(sdb_opts, opts)
AttributeError: 'module' object has no attribute 'sdb
```

**Comment by rallytime** [comment]
ping @techhat

**Comment by techhat** [comment]
@whiteinge what version is this?

**Comment by whiteinge** [comment]
Tested on both 2014.7 and 2015.2, IIRC.

**Comment by rallytime** [comment]
@whiteinge Are you still running into this one? I just tried this at the HEAD of the 2015.5 branch and I can't seem to reproduce it. Though I may have configured something incorrectly.

**Comment by whiteinge** [comment]
Different error. I think this may be fixed. Will reopen if not.
