### ISSUE TITLE
salt.master.MWorker  died with exit status None

### ISSUE THREAD

**Issue by lrhazi** [saltstack/salt#22230]
Trying to run latest git develop in a centos6 Docker container... when master starts, it seems all workers die with the following error. 

Bot sure which file is missing....

```
Process MWorker-4:5:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 232, in _bootstrap
    self.run()
  File "/usr/lib/python2.6/site-packages/salt/master.py", line 938, in run
    self.crypticle)
  File "/usr/lib/python2.6/site-packages/salt/master.py", line 1620, in __init__
    rend=False)
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 496, in __init__
    self.opts['grains'] = salt.loader.grains(opts)
  File "/usr/lib/python2.6/site-packages/salt/loader.py", line 466, in grains
    ret = fun()
  File "/usr/lib/python2.6/site-packages/salt/grains/core.py", line 1017, in os_data
    if _linux_bin_exists('selinuxenabled'):
  File "/usr/lib/python2.6/site-packages/salt/grains/core.py", line 966, in _linux_bin_exists
    'which {0}'.format(binary)
  File "/usr/lib/python2.6/site-packages/salt/modules/cmdmod.py", line 1147, in _retcode_quiet
    **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/modules/cmdmod.py", line 1095, in retcode
    use_vt=use_vt)
  File "/usr/lib/python2.6/site-packages/salt/modules/cmdmod.py", line 393, in _run
    .format(cmd, kwargs, exc)
CommandExecutionError: Unable to run command ['which', 'selinuxenabled'] with the context {'with_communicate': True, 'shell': False, 'env': {'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd
=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zi
p=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.tbz=01;31:*.tbz2=01;31:*.bz=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;
31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng
=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*
.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:
*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:', 'LESS': '-R', 'LC_CTYPE': 'en_US.UTF-8', 'LESSOPEN': '||/usr/bin/lesspipe.sh %s', 'SSH_CLIENT': '172.17.42.1 52562 22', 'LOGNAME': 'root', 'USER': 'root', 'HOME': '/root', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'ZSH': '/root/.oh-my-zsh', 'LANG': 'en_US.UTF-8', 'TERM': 'xterm', 'SHELL': '/bin/zsh', 'SHLVL': '1', 'G_BROKEN_FILENAMES': '1', 'HISTSIZE': '10000', 'LC_ALL': 'C', '_': '/usr/bin/salt-master', 'LSCOLORS': 'Gxfxcxdxbxegedabagacad', 'SSH_TTY': '/dev/pts/0', 'OLDPWD': '/root', 'HOSTNAME': 'saltmaster', 'HISTCONTROL': 'ignoredups', 'PWD': '/root', 'MAIL': '/var/spool/mail/root', 'SSH_CONNECTION': '172.17.42.1 52562 172.17.0.235 22', 'PAGER': 'less'}, 'stdout': -1, 'close_fds': True, 'stdin': None, 'stderr': -2, 'cwd': '/root'}, reason: [Errno 2] No such file or directory
[INFO    ] Process <class 'salt.master.MWorker'> (453) died with exit status None, restarting...
```

**Comment by rallytime** [comment]
Thanks for the report @lrhazi. I am not very familiar with our docker support, but @terminalmage has been making some changes there. Perhaps he has seen something like this before.

Or maybe @basepi does this look familiar to you?

**Comment by basepi** [comment]
Sounds like `which` may be missing. Can you run `which selinuxenabled` on the command line?

**Comment by jfindlay** [comment]
This is fixed in #22177.  @lrhazi, what is the output of `salt --versions-report`?  Thanks.

**Comment by terminalmage** [comment]
@rallytime I have not been making changes to dockerio.py. I rewrote docker support in dockerng.py.

**Comment by lrhazi** [comment]
I was gonna reply: But of course i checked that!.... Maybe not... my shell had it builtin, but actual external */bin/which does not exist indeed...  "yum install which" fixed this.
