### ISSUE TITLE
Unable to spin up GCE instances

### ISSUE THREAD

**Issue by RobertAtomic** [saltstack/salt#22312]
Hi,

I'm unable to create GCE instances using salt-cloud.  The issue seems to be that zone=None for some reason in the call to ex_get_disktype.  Is this a bug, or am I doing something wrong?  Config and output below.  Thanks in advance for any help.
```
root@salt:/etc/salt# cat cloud.providers.d/gce.conf 
gce:
    project: "atomic-systems"
    service_account_email_address: "xxxxxxxx@developer.gserviceaccount.com"
    service_account_private_key: "/root/xxxxxxx.pem"
    minion:
      master: salt
    grains:
      node_type: broker
      release: 1.0.1
    provider: gce
    ssh_interface: private_ips

root@salt:/etc/salt# cat cloud.profiles.d/all_settings.conf 
all_settings:
  image: centos-6
  size: n1-standard-1
  location: europe-west1-b
  network: default
  tags: '["one", "two", "three"]'
  metadata: '{"one": "1", "2": "two"}'
  use_persistent_disk: True
  delete_boot_pd: True
  deploy: True
  make_master: False
  provider: gce
  ssh_username: salt
  ssh_keyfile: /root/.ssh/id_rsa
  ex_disk_type: pd-standard

root@salt:/etc/salt# salt-cloud -p all_settings minion-test-001 -l debug 
[DEBUG   ] Reading configuration from /etc/salt/cloud
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/github.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/github.conf
[DEBUG   ] Guessing ID. The id can be explicitly in set /etc/salt/minion
[INFO    ] Found minion id from generate_minion_id(): salt.c.atomic-systems.internal
[DEBUG   ] Missing configuration file: /etc/salt/cloud.providers
[DEBUG   ] Including configuration from '/etc/salt/cloud.providers.d/gce.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers.d/gce.conf
[DEBUG   ] Missing configuration file: /etc/salt/cloud.profiles
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/all_settings.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/all_settings.conf
[DEBUG   ] Configuration file path: /etc/salt/cloud
[INFO    ] salt-cloud starting
[DEBUG   ] 'parallels.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'parallels.avail_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'proxmox.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'saltify.destroy' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'saltify.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'saltify.avail_images' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'saltify.avail_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'rackspace.reboot' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'openstack.list_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'rackspace.list_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] The 'gce' cloud driver is unable to be optimized.
[DEBUG   ] 'parallels.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'parallels.avail_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'proxmox.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'saltify.destroy' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'saltify.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'saltify.avail_images' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'saltify.avail_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'rackspace.reboot' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'openstack.list_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'rackspace.list_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] Generating minion keys for 'minion-test-001'
[INFO    ] Creating GCE instance minion-test-001 in europe-west1-b
[DEBUG   ] Create instance kwargs {'ex_disk_type': 'pd-standard', 'ex_metadata': {'items': [{'value': 'two', 'key': '2'}, {'value': 'all_settings', 'key': 'sa
lt-cloud-profile'}, {'value': '1', 'key': 'one'}]}, 'name': 'minion-test-001', 'external_ip': 'ephemeral', 'ex_tags': ['one', 'two', 'three'], 'image': <NodeI
mage: id=8461891139530134602, name=centos-6-v20150325, driver=Google Compute Engine  ...>, 'ex_disk_auto_delete': True, 'location': <GCEZone id="2101" name="e
urope-west1-b" status="UP">, 'ex_network': <GCENetwork id="14574098772214689000" name="default" cidr="10.240.0.0/16">, 'size': <NodeSize: id=3001, name=n1-sta
ndard-1, ram=3840 disk=None bandwidth=0 price=None driver=Google Compute Engine ...>}
[DEBUG   ] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event - data = {'profile': 'all_settings', 'event': 'create instance', '_stamp': '2015-04-03T00:38:04.831751', 'name': 'minion-test-001', '
provider': 'gce:gce'}
[ERROR   ] Error creating minion-test-001 on GCE
The following exception was thrown by libcloud when trying to run the initial deployment: 
'NoneType' object has no attribute 'name'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/gce.py", line 1915, in create
    node_data = conn.create_node(**kwargs)  # pylint: disable=W0142
  File "/usr/local/lib/python2.7/dist-packages/libcloud/compute/drivers/gce.py", line 2173, in create_node
    ex_disk_type = self.ex_get_disktype(ex_disk_type)
  File "/usr/local/lib/python2.7/dist-packages/libcloud/compute/drivers/gce.py", line 3745, in ex_get_disktype
    request = '/zones/%s/diskTypes/%s' % (zone.name, name)
AttributeError: 'NoneType' object has no attribute 'name'
Error: There was a profile error: Failed to deploy VM

salt-cloud -p all_settings minion-test-001 -l debug --versions-report
                  Salt: 2014.7.2
                Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
                Jinja2: 2.6
              M2Crypto: 0.21.1
        msgpack-python: 0.1.10
          msgpack-pure: Not Installed
              pycrypto: 2.6
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 13.1.0
                  RAET: Not Installed
                   ZMQ: 3.2.3
                  Mako: 0.7.0
       Apache Libcloud: 0.17.0
 Debian source package: 2014.7.2+ds-1~bpo70+1
```

**Comment by erjohnso** [comment]
Hi @RobertAtomic,

Very sorry about this, but there is a bug with libcloud 0.17.0 [https://github.com/apache/libcloud/pull/448].  It's been fixed upstream in trunk, so if you're OK with it, you could go bleeding edge to pick up the fix.  I don't have a good handle on a 0.17.1 release at this point.

@techhat @s0undt3ch FYI

**Comment by techhat** [comment]
Thanks for helping out here @erjohnso.

**Comment by rallytime** [comment]
Since this has been fixed upstream in `libcloud`, and libcloud version 0.18.0 is out, I am going to close this issue. If this pops up again, let us knew and we can re-address. Thanks!
