### ISSUE TITLE
Run salt command abnormal

### ISSUE THREAD

**Issue by shencan** [saltstack/salt#22358]
```
[root@Shencan conf]# salt
Traceback (most recent call last):
  File "/usr/bin/salt", line 5, in <module>
    from pkg_resources import load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 2603, in <module>
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 666, in require
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 565, in resolve
pkg_resources.DistributionNotFound: requests>=1.0.0
```

some information:
System version :  Centos 6.6
Saltstack version:  salt-2014.7.4
Python version:  2.7.6
Install way:  pip install salt

**Comment by rallytime** [comment]
Hi @shencan - When you installed salt, is this on a new system that has never had salt installed on it before? Or are you upgrading? I am wondering if you've got all of the package dependencies needed to run salt. (requests is a hard dependency for salt in the 2014.7.x releases.)

**Comment by DmitryKuzmenko** [comment]
Just got the same issue.
Installed pip with easy_install. Installed salt with pip install. After that salt --versions-report got the error.

Looks like system packages problem, not salt. The problem in python-setuptools package. It can be reproduced without salt:

```
# pip install requests
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python2.6/site-packages
# python
>>> import pkg_resources                                            
>>> pkg_resources.get_distribution('requests')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 292, in get_distribution
    if isinstance(dist,Requirement): dist = get_provider(dist)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 176, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 647, in require
    
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 545, in resolve
    # to get the name of the distribution here..
pkg_resources.DistributionNotFound: requests
```

The following fixes it:

 # pip install --upgrade setuptools

After this setuptools could be installed back by yum if you need it:
```
# yum install python-setuptools
>>> import pkg_resources                                            
>>> pkg_resources.get_distribution('requests')
requests 2.7.0 (/usr/lib/python2.6/site-packages)
```

**Comment by DmitryKuzmenko** [comment]
@rallytime it could be safely closed I think.

**Comment by rallytime** [comment]
Cool. Thanks @DmitryKuzmenko!

**Comment by mzmmohideen** [comment]
it works man @DmitryKuzmenko
