### ISSUE TITLE
Salt-ssh exception when MySQL returner enabled in /etc/salt/master

### ISSUE THREAD

**Issue by ssgward** [saltstack/salt#22392]
Salt-ssh exception when MySQL returner enabled in /etc/salt/master.

Running a simple ``salt-ssh \* test.ping`` results in the following:
```
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
KeyError: 'fun'
Traceback (most recent call last):
  File "/usr/bin/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 273, in salt_ssh
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/ssh.py", line 18, in run
    ssh.run()
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 520, in run
    self.cache_job(jid, host, ret[host])
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 480, in cache_job
    'return': ret})
  File "/usr/lib/python2.7/dist-packages/salt/returners/mysql.py", line 207, in returner
    cur.execute(sql, (ret['fun'], ret['jid'],
KeyError: 'fun'
Traceback (most recent call last):
  File "/usr/bin/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 273, in salt_ssh
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/ssh.py", line 18, in run
    ssh.run()
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 520, in run
    self.cache_job(jid, host, ret[host])
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 480, in cache_job
    'return': ret})
  File "/usr/lib/python2.7/dist-packages/salt/returners/mysql.py", line 207, in returner
    cur.execute(sql, (ret['fun'], ret['jid'],
KeyError: 'fun'
```

The following is enable in /etc/salt/master:
```
master_job_cache: mysql
event_return: mysql
```

Commenting out the above lines allows salt-ssh to run without error.
```
salt --versions-report
           Salt: 2015.2.0rc2-19-gffae7d6
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
```

**Comment by basepi** [comment]
Fixed here: https://github.com/saltstack/salt/pull/22389

**Comment by cachedout** [comment]
I have confirmed this is fixed. Closing.
