### ISSUE TITLE
Exception from orchestration

### ISSUE THREAD

**Issue by karanjad** [saltstack/salt#22474]
It seems testing a very basic orchestration in 2015.2.0rc1 results in an interesting traceback.
Here is an example of the orchestration;
```
[root@salt-master ~]# cat install_nginx:
  salt.state:
    - tgt: '<minion-id>'
    - sls:
      - nginx
```
```
[root@salt-master ~]# salt --versions-report
           Salt: 2015.2.0rc1
         Python: 2.7.5 (default, Feb 11 2014, 07:46:25)
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.4
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed
```
Here is the traceback;
```
[root@salt-master ~]# salt-run jobs.lookup_jid 20150408121203878981
salt-master_master:
    ----------
    _stamp:
        2015-04-08T16:12:10.541966
    fun:
        runner.state.orchestrate
    jid:
        20150408121203878981
    return:
        Exception occurred in runner state.orchestrate: Traceback (most recent call last):
          File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 314, in low
            data['return'] = self.functions[fun](*args, **kwargs)
          File "/usr/lib/python2.7/site-packages/salt/runners/state.py", line 116, in orchestrate
            __jid_event__.fire_event({'data': ret, 'outputter': 'highstate'}, 'progress')
          File "/usr/lib/python2.7/site-packages/salt/utils/event.py", line 530, in fire_event
            self.print_func(tag, data)
          File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 438, in print_async_event
            print(self.outputters[event['outputter']](event['data']))
          File "/usr/lib/python2.7/site-packages/salt/output/highstate.py", line 78, in output
            return _format_host(host, hostdata)[0]
          File "/usr/lib/python2.7/site-packages/salt/output/highstate.py", line 130, in _format_host
            schanged, ctext = _format_changes(ret['changes'])
          File "/usr/lib/python2.7/site-packages/salt/output/highstate.py", line 345, in _format_changes
            s, c = _format_host(host, hostdata)
          File "/usr/lib/python2.7/site-packages/salt/output/highstate.py", line 130, in _format_host
            schanged, ctext = _format_changes(ret['changes'])
          File "/usr/lib/python2.7/site-packages/salt/output/highstate.py", line 353, in _format_changes
            if __opts__['color']:
        KeyError: 'color'

    success:
        False
    user:
        root
[root@salt-master ~]#
```

**Comment by rallytime** [comment]
@karanjad Would you be able to test this again using 2015.2.0rc2? I think we have fixed this since we tagged RC1.

**Comment by karanjad** [comment]
Yes, I shall give it a shot and get back to you.

**Comment by rallytime** [comment]
Awesome! Thanks very much!

**Comment by karanjad** [comment]
Yes, that version does resolve the bug. Awesome!

**Comment by rallytime** [comment]
Woohoo!
