### ISSUE TITLE
AttributeError: 'SaltRaetRoadStackJoiner' object has no attribute 'mha' 

### ISSUE THREAD

**Issue by double-yaya** [saltstack/salt#22487]
when I installed raet then  restart salt-minion ,happend like this:

```
2015-04-08 17:25:22,059 [salt             ][INFO    ] Setting up the Salt Minion "deletedevweb02"
2015-04-08 17:25:22,113 [salt.utils.process                       ][DEBUG   ] Created pidfile: /var/run/salt-minion.pid
2015-04-08 17:25:22,379 [salt.config                              ][DEBUG   ] Reading configuration from /etc/salt/minion
2015-04-08 17:25:22,938 [salt.cloud                               ][DEBUG   ] Mako not available
2015-04-08 17:25:23,391 [salt.log.setup                             ][ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'SaltRaetRoadStackJoiner' object has no attribute 'mha'
Traceback (most recent call last):
  File "/usr/bin/salt-minion", line 14, in <module>
    salt_minion()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 57, in salt_minion
    minion.start()
  File "/usr/lib/python2.6/site-packages/salt/__init__.py", line 264, in start
    self.minion.tune_in()
  File "/usr/lib/python2.6/site-packages/salt/daemons/flo/__init__.py", line 137, in tune_in
    consolepath=consolepath,
  File "/usr/lib/python2.6/site-packages/ioflo/app/run.py", line 131, in run
    skedder.run()
  File "/usr/lib/python2.6/site-packages/ioflo/base/skedding.py", line 273, in run
    status = tasker.runner.send(tasker.desire)
  File "/usr/lib/python2.6/site-packages/ioflo/base/framing.py", line 611, in makeRunner
    self.enterAll() #activates, resets .done state also .desire may change here
  File "/usr/lib/python2.6/site-packages/ioflo/base/framing.py", line 392, in enterAll
    self.enter(self.actives)
  File "/usr/lib/python2.6/site-packages/ioflo/base/framing.py", line 404, in enter
    frame.enter()
  File "/usr/lib/python2.6/site-packages/ioflo/base/framing.py", line 1211, in enter
    act() #call entryAction
  File "/usr/lib/python2.6/site-packages/ioflo/base/acting.py", line 98, in __call__
    return (self.actor(**self.parms))
  File "/usr/lib/python2.6/site-packages/ioflo/base/acting.py", line 460, in __call__
    return self.action(**kwa)
  File "/usr/lib/python2.6/site-packages/salt/daemons/flo/core.py", line 222, in action
    ha=self.mha))
AttributeError: 'SaltRaetRoadStackJoiner' object has no attribute 'mha'
```

```
salt --versions-report
           Salt: 2014.7.2
         Python: 2.6.6 (r266:84292, May  1 2012, 13:52:17)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: 1.4.2
         PyYAML: 3.10
          ioflo: 1.2.1
          PyZMQ: 2.2.0.1
           RAET: 0.4.2
            ZMQ: 3.2.4
           Mako: Not Installed
```

**Comment by rallytime** [comment]
@double-yaya Thanks for the report.
