### ISSUE TITLE
Error deleting SSH keys using salt-cloud --destroy

### ISSUE THREAD

**Issue by amendlik** [saltstack/salt#22550]
Error deleting SSH keys when ```delete_sshkeys: True``` and ```ssh_interface: private_ips```
```
[ERROR   ] There was an error destroying machines: list index out of range
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 166, in run
    ret = mapper.destroy(names, cached=True)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 958, in destroy
    ret = self.clouds[fun](name)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/libcloudfuncs.py", line 379, in destroy
    salt.utils.cloud.remove_sshkey(getattr(node, __opts__.get('ssh_interface', 'public_ips'))[0])
IndexError: list index out of range
```

My environment is an OpenStack private cloud, with salt-cloud running outside the cloud. Salt considers both the private address and the floating address to be 'private' addresses:
```
            id:
                33ded115-98b3-4aa4-aa91-7b46baadcb91
            image:
                None
            private_ips:
                - 10.0.0.15         <--- Private address
                - 192.168.1.85      <--- Floating address (Salt must use this one)
            public_ips:
            size:
                None
```

**Comment by jfindlay** [comment]
@amendlik, thank you for reporting.

**Comment by rallytime** [comment]
@amendlik What version of salt were you seeing this on? Are you still running into this problem? I was unable to reproduce this with a simple test case, but I might not have set this up the same way. I tested this on the HEAD of 2015.5:
```
# salt-cloud --versions
            Salt: 2015.5.1-101-gae681a4
          Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
          Jinja2: 2.7.3
        M2Crypto: 0.21.1
  msgpack-python: 0.4.4
    msgpack-pure: Not Installed
        pycrypto: 2.6.1
         libnacl: Not Installed
          PyYAML: 3.11
           ioflo: Not Installed
           PyZMQ: 14.0.1
            RAET: Not Installed
             ZMQ: 4.0.4
            Mako: 0.9.1
 Apache Libcloud: 0.17.0
```

**Comment by amendlik** [comment]
```
$salt-cloud --versions
                  Salt: 2014.7.2
                Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.4.2
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
       Apache Libcloud: 0.14.1
 Debian source package: 2014.7.2+ds-1trusty2
```

**Comment by rallytime** [comment]
@amendlik Are you in a position to give this a try on a newer version like 2015.5.2? I am wondering if this is resolved since I can't reproduce the error there.

**Comment by amendlik** [comment]
I just tested it on 2015.5.0 and I'm still seeing the problem.

**Comment by rallytime** [comment]
@amendlik Thanks for testing that and confirming. I have submitted #26573 to fix this issue. Can you give it a try and confirm that is fixes this bug for you?

**Comment by rallytime** [comment]
Since we didn't hear anything back here, I am going to go ahead and close this issue. If it remains a problem, certainly let me know and I'd be happy to take another look. Thank you!
