### ISSUE TITLE
salt develop branch shows ImportError if tornado not installed

### ISSUE THREAD

**Issue by nmadhok** [saltstack/salt#22601]
Salt develop branch show ImportError after merging #22453 if tornado is not installed on the system

Here's what I get when I try to start ``salt-master``, ``salt-minion`` or use ``salt-cloud``

Trying to start ``salt-minion``:
```
root@nitin-salt-develop:~/salt$ service salt-minion start
Starting salt-minion daemon: Traceback (most recent call last):
  File "/usr/bin/salt-minion", line 14, in <module>
    salt_minion()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 104, in salt_minion
    import salt.cli.daemons
  File "/usr/lib/python2.6/site-packages/salt/cli/daemons.py", line 46, in <module>
    from salt.utils import parsers, ip_bracket
  File "/usr/lib/python2.6/site-packages/salt/utils/parsers.py", line 28, in <module>
    import salt.loader as loader
  File "/usr/lib/python2.6/site-packages/salt/loader.py", line 23, in <module>
    import salt.utils.event
  File "/usr/lib/python2.6/site-packages/salt/utils/event.py", line 76, in <module>
    import salt.payload
  File "/usr/lib/python2.6/site-packages/salt/payload.py", line 17, in <module>
    import salt.crypt
  File "/usr/lib/python2.6/site-packages/salt/crypt.py", line 32, in <module>
    import salt.transport.client
  File "/usr/lib/python2.6/site-packages/salt/transport/client.py", line 7, in <module>
    from salt.utils.async import SyncWrapper
  File "/usr/lib/python2.6/site-packages/salt/utils/async.py", line 8, in <module>
    import tornado.ioloop
ImportError: No module named tornado.ioloop
                                                           [FAILED]
```

Trying to start ``salt-master``:
```
root@nitin-salt-develop:~/salt$ service salt-master start
Starting salt-master daemon: Traceback (most recent call last):
  File "/usr/bin/salt-master", line 10, in <module>
    salt_master()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 45, in salt_master
    import salt.cli.daemons
  File "/usr/lib/python2.6/site-packages/salt/cli/daemons.py", line 46, in <module>
    from salt.utils import parsers, ip_bracket
  File "/usr/lib/python2.6/site-packages/salt/utils/parsers.py", line 28, in <module>
    import salt.loader as loader
  File "/usr/lib/python2.6/site-packages/salt/loader.py", line 23, in <module>
    import salt.utils.event
  File "/usr/lib/python2.6/site-packages/salt/utils/event.py", line 76, in <module>
    import salt.payload
  File "/usr/lib/python2.6/site-packages/salt/payload.py", line 17, in <module>
    import salt.crypt
  File "/usr/lib/python2.6/site-packages/salt/crypt.py", line 32, in <module>
    import salt.transport.client
  File "/usr/lib/python2.6/site-packages/salt/transport/client.py", line 7, in <module>
    from salt.utils.async import SyncWrapper
  File "/usr/lib/python2.6/site-packages/salt/utils/async.py", line 8, in <module>
    import tornado.ioloop
ImportError: No module named tornado.ioloop
                                                           [FAILED]
```

Using a ``salt-cloud`` command:
```
root@nitin-salt-develop:~$ salt-cloud
salt-cloud is not available in this system
Traceback (most recent call last):
  File "/usr/bin/salt-cloud", line 10, in <module>
    salt_cloud()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 307, in salt_cloud
    sys.exit(salt.defaults.exitcodes.EX_UNAVAILABLE)
UnboundLocalError: local variable 'salt' referenced before assignment
```

I fixed it by manually installing tornado by doing the following:
```
root@nitin-salt-develop:~/salt$ pip install tornado
Downloading/unpacking tornado
  Downloading tornado-4.1.tar.gz (332kB): 332kB downloaded
  Running setup.py egg_info for package tornado
Downloading/unpacking certifi (from tornado)
  Downloading certifi-14.05.14.tar.gz (168kB): 168kB downloaded
  Running setup.py egg_info for package certifi
Requirement already satisfied (use --upgrade to upgrade): backports.ssl-match-hostname in /usr/lib/python2.6/site-packages (from tornado)
Installing collected packages: tornado, certifi
  Running setup.py install for tornado
    building 'tornado.speedups' extension
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.6 -c tornado/speedups.c -o build/temp.linux-x86_64-2.6/tornado/speedups.o
    gcc -pthread -shared build/temp.linux-x86_64-2.6/tornado/speedups.o -L/usr/lib64 -lpython2.6 -o build/lib.linux-x86_64-2.6/tornado/speedups.so
  Running setup.py install for certifi
Successfully installed tornado certifi
Cleaning up...
```

Is tornado a required dependency now? 

@thatch45

**Comment by cachedout** [comment]
Yes, tornado is a dependency now.

**Comment by rallytime** [comment]
@nmadhok Yes, with the addition of #22453, tornado is now a hard dependency. After you've installed tornado, let us know if you run into any problems. Thanks!

**Comment by nmadhok** [comment]
@rallytime @cachedout Thanks for the information. I'll close this issue.

**Comment by daswathn** [comment]
Thank you for fixing this works well after installing tornado on my sles11 sp3 server, but issue still persists with SLES12 
salt-03:~ # zypper install python-pip
Loading repository data...
Reading installed packages...
Resolving package dependencies...

The following NEW package is going to be installed:
  python-pip

The following package is not supported by its vendor:
  python-pip

1 new package to install.
Overall download size: 1.4 MiB. After the operation, additional 5.8 MiB will be
used.
Continue? [y/n/?] (y): y
Retrieving package python-pip-7.1.2-1.3.x86_64 (1/1), 1.4 MiB (5.8 MiB unpacked)
Retrieving: python-pip-7.1.2-1.3.x86_64.rpm [done (101.9 KiB/s)]
Installing: python-pip-7.1.2-1.3 [done]

#########
salt-02:~ # pip install tornado --upgrade
/usr/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Requirement already up-to-date: tornado in /usr/lib64/python2.7/site-packages
Collecting backports.ssl-match-hostname (from tornado)
  Downloading backports.ssl_match_hostname-3.5.0.1.tar.gz
Requirement already up-to-date: singledispatch in /usr/lib/python2.7/site-packages (from tornado)
Collecting certifi (from tornado)
  Downloading certifi-2015.11.20.1-py2.py3-none-any.whl (368kB)
    100% |████████████████████████████████| 372kB 185kB/s
Requirement already up-to-date: backports-abc>=0.4 in /usr/lib/python2.7/site-packages (from tornado)
Requirement already up-to-date: six in /usr/lib/python2.7/site-packages (from singledispatch->tornado)
Installing collected packages: backports.ssl-match-hostname, certifi
  Found existing installation: backports.ssl-match-hostname 3.4.0.2
    Uninstalling backports.ssl-match-hostname-3.4.0.2:
      Successfully uninstalled backports.ssl-match-hostname-3.4.0.2
  Running setup.py install for backports.ssl-match-hostname
  Found existing installation: certifi 2015.9.6.2
    Uninstalling certifi-2015.9.6.2:
      Successfully uninstalled certifi-2015.9.6.2
Successfully installed backports.ssl-match-hostname-3.5.0.1 certifi-2015.11.20.1
#############

salt-01:~ # ps auxww | grep salt
root      2874  0.0  0.0   8304   124 ?        Ss   04:28   0:00 /sbin/dhcpcd --netconfig -L -E -c /etc/sysconfig/network/scripts/dhcpcd-hook -t 0 -h salt-01 eth0
root      4594  0.0  0.3  50296  3024 pts/1    S+   06:07   0:00 ssh salt-03
salt      4812  0.1  2.8 194048 25012 ?        S    06:11   0:00 /usr/bin/python /usr/bin/salt-master -d
salt      4813  0.0  2.8 209992 24872 ?        Sl   06:11   0:00 /usr/bin/python /usr/bin/salt-master -d
salt      4816  0.0  2.8 277004 25516 ?        Sl   06:11   0:00 /usr/bin/python /usr/bin/salt-master -d
salt      4819  1.8  3.7 228332 32984 ?        Sl   06:11   0:00 /usr/bin/python /usr/bin/salt-master -d
salt      4820  0.0  2.8 196128 25196 ?        S    06:11   0:00 /usr/bin/python /usr/bin/salt-master -d
salt      4821  0.0  2.8 245440 25256 ?        Sl   06:11   0:00 /usr/bin/python /usr/bin/salt-master -d
salt      4822  7.5  3.5 433116 31608 ?        Sl   06:11   0:01 /usr/bin/python /usr/bin/salt-master -d
salt      4823  7.7  3.5 433140 31776 ?        Sl   06:11   0:01 /usr/bin/python /usr/bin/salt-master -d
salt      4824  7.4  3.5 433684 31660 ?        Sl   06:11   0:01 /usr/bin/python /usr/bin/salt-master -d
salt      4825  7.4  3.6 430488 32072 ?        Sl   06:11   0:01 /usr/bin/python /usr/bin/salt-master -d
salt      4828  7.4  3.3 434156 29816 ?        Sl   06:11   0:01 /usr/bin/python /usr/bin/salt-master -d
root      5324  1.1  3.0 313696 26660 ?        Sl   06:11   0:00 /usr/bin/python /usr/bin/salt-minion -d
root      5353  0.0  0.0   4536   564 pts/0    S+   06:11   0:00 grep salt

But on SLES12 
salt-02:~ # salt-master --log-level=debug
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] Setting up the Salt Master
unable to execute 'gcc': No such file or directory
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
VerificationError: CompileError: command 'gcc' failed with exit status 1
Traceback (most recent call last):
  File "/usr/bin/salt-master", line 22, in <module>
    salt_master()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 47, in salt_master
    master.start()
  File "/usr/lib/python2.7/site-packages/salt/cli/daemons.py", line 154, in start
    self.prepare()
  File "/usr/lib/python2.7/site-packages/salt/cli/daemons.py", line 134, in prepare
    import salt.master
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 46, in <module>
    import salt.key
  File "/usr/lib/python2.7/site-packages/salt/key.py", line 23, in <module>
    import salt.daemons.masterapi
  File "/usr/lib/python2.7/site-packages/salt/daemons/masterapi.py", line 37, in <module>
    from salt.pillar import git_pillar
  File "/usr/lib/python2.7/site-packages/salt/pillar/git_pillar.py", line 188, in <module>
    import salt.utils.gitfs
  File "/usr/lib/python2.7/site-packages/salt/utils/gitfs.py", line 74, in <module>
    import pygit2
  File "/usr/lib64/python2.7/site-packages/pygit2/__init__.py", line 35, in <module>
    from .blame import Blame, BlameHunk
  File "/usr/lib64/python2.7/site-packages/pygit2/blame.py", line 32, in <module>
    from .errors import check_error
  File "/usr/lib64/python2.7/site-packages/pygit2/errors.py", line 29, in <module>
    from .ffi import ffi, C
  File "/usr/lib64/python2.7/site-packages/pygit2/ffi.py", line 35, in <module>
    ffi, C = get_ffi()
  File "/usr/lib64/python2.7/site-packages/pygit2/_utils.py", line 101, in get_ffi
    include_dirs=[libgit2_include], library_dirs=[libgit2_lib])
  File "/usr/lib64/python2.7/site-packages/cffi/api.py", line 405, in verify
    lib = self.verifier.load_library()
  File "/usr/lib64/python2.7/site-packages/cffi/verifier.py", line 100, in load_library
    self._compile_module()
  File "/usr/lib64/python2.7/site-packages/cffi/verifier.py", line 196, in _compile_module
    outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
  File "/usr/lib64/python2.7/site-packages/cffi/ffiplatform.py", line 38, in compile
    outputfilename = _build(tmpdir, ext)
  File "/usr/lib64/python2.7/site-packages/cffi/ffiplatform.py", line 65, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
VerificationError: CompileError: command 'gcc' failed with exit status 1
Traceback (most recent call last):
  File "/usr/bin/salt-master", line 22, in <module>
    salt_master()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 47, in salt_master
    master.start()
  File "/usr/lib/python2.7/site-packages/salt/cli/daemons.py", line 154, in start
    self.prepare()
  File "/usr/lib/python2.7/site-packages/salt/cli/daemons.py", line 134, in prepare
    import salt.master
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 46, in <module>
    import salt.key
  File "/usr/lib/python2.7/site-packages/salt/key.py", line 23, in <module>
    import salt.daemons.masterapi
  File "/usr/lib/python2.7/site-packages/salt/daemons/masterapi.py", line 37, in <module>
    from salt.pillar import git_pillar
  File "/usr/lib/python2.7/site-packages/salt/pillar/git_pillar.py", line 188, in <module>
    import salt.utils.gitfs
  File "/usr/lib/python2.7/site-packages/salt/utils/gitfs.py", line 74, in <module>
    import pygit2
  File "/usr/lib64/python2.7/site-packages/pygit2/__init__.py", line 35, in <module>
    from .blame import Blame, BlameHunk
  File "/usr/lib64/python2.7/site-packages/pygit2/blame.py", line 32, in <module>
    from .errors import check_error
  File "/usr/lib64/python2.7/site-packages/pygit2/errors.py", line 29, in <module>
    from .ffi import ffi, C
  File "/usr/lib64/python2.7/site-packages/pygit2/ffi.py", line 35, in <module>
    ffi, C = get_ffi()
  File "/usr/lib64/python2.7/site-packages/pygit2/_utils.py", line 101, in get_ffi
    include_dirs=[libgit2_include], library_dirs=[libgit2_lib])
  File "/usr/lib64/python2.7/site-packages/cffi/api.py", line 405, in verify
    lib = self.verifier.load_library()
  File "/usr/lib64/python2.7/site-packages/cffi/verifier.py", line 100, in load_library
    self._compile_module()
  File "/usr/lib64/python2.7/site-packages/cffi/verifier.py", line 196, in _compile_module
    outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
  File "/usr/lib64/python2.7/site-packages/cffi/ffiplatform.py", line 38, in compile
    outputfilename = _build(tmpdir, ext)
  File "/usr/lib64/python2.7/site-packages/cffi/ffiplatform.py", line 65, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.ffiplatform.VerificationError: CompileError: command 'gcc' failed with exit status 1

any help in fixing this would help a ton. thank you

**Comment by aty010** [comment]
Just want to document how I fix similar issue . I have following error message
```
from . import (constants, error, message, context,
ImportError: libzmq.so.4: cannot open shared object file: No such file or directory
```
This my notes 
```
  562  cd sources.list.d/
  565  rm -f *.save
  567  rm -f chris-lea-zeromq-precise.list saltstack-salt-precise.list
  571  apt-get update
  574  apt-get remove -y salt-minion;apt-get autoremove -y
 /root/bootstrap_salt.shn
  576  /etc/init.d/salt-minion stop
  577  salt-minion -l debug
  578  /etc/init.d/salt-minion start
  579  history |tail -30

```

**Comment by tjyang** [comment]
Just want to document how I fix similar issue . I have following error message when running "salt-minion -l debug"
```
from . import (constants, error, message, context,
ImportError: libzmq.so.4: cannot open shared object file: No such file or directory
```
This my notes 
```
  562  cd sources.list.d/
  565  rm -f *.save
  567  rm -f chris-lea-zeromq-precise.list saltstack-salt-precise.list
  571  apt-get update
  574  apt-get remove -y salt-minion;apt-get autoremove -y
 /root/bootstrap_salt.sh
  576  /etc/init.d/salt-minion stop
  577  salt-minion -l debug
  578  /etc/init.d/salt-minion start
  579  history |tail -30

```
