### ISSUE TITLE
Open files issue with gitfs (pygit2) Backend 

### ISSUE THREAD

**Issue by Azidburn** [saltstack/salt#22649]
I have in issue with open file limit and gitfs fileserver backend.

I see no message in Logs until the system open file limit reached, then i get the following messages

```
[salt.master                                ][ERROR   ] Error in function _file_hash:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 1348, in run_func
    ret = getattr(self, func)(load)
  File "/usr/lib/python2.7/site-packages/salt/fileserver/__init__.py", line 512, in file_hash
  File "/usr/lib/python2.7/site-packages/salt/fileserver/__init__.py", line 466, in find_file
  File "/usr/lib/python2.7/site-packages/salt/fileserver/gitfs.py", line 1452, in find_file
OSError: Failed to open directory '/var/cache/salt/master/gitfs/074ece2ff7075438089203cd40e3ce47/.git/objects/pack/': Too many open files
[salt.master                                ][CRITICAL] Unexpected Error in Mworker Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 599, in __bind
    ret = self.serial.dumps(self._handle_payload(payload))
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 651, in _handle_payload
    'clear': self._handle_clear}[key](load)
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 694, in _handle_aes
    return self.aes_funcs.run_func(data['cmd'], data)
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 1396, in run_func
    return self.crypticle.dumps(ret)
  File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 790, in dumps
  File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 757, in encrypt
OSError: [Errno 24] Too many open files
```

The master has no minion now.

I  have no limits set in salt-master config but the system limits are:100000(soft), 250000(hard)

When i count the file descriptor with lsof the number reach the system limit. It takes a few days until the master reached the limit. I see man file descriptor for the same pack file.

Here my master config for git backend

```
fileserver_backend:
  - git
gitfs_provider: pygit2
gitfs_remotes:
  - git@master.example.com:salt-base
gitfs_root: salt
gitfs_privkey: "<foo>"
gitfs_pubkey: "<foo>.pub"
```

My Salt-Version is:

```
           Salt: 2014.7.0
         Python: 2.7.8 (default, Sep 30 2014, 15:34:38) [GCC]
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
```

but all python Module are from head of 2014.7 branch from March 26 2015.

**Comment by rallytime** [comment]
Thanks for the report. I know that @terminalmage has been doing a lot of with with gitfs lately. However, I don't know if this particular issue has been raised/addressed. 

It might be worth testing this in a newer version of salt to see if this is resolved for you. Otherwise @terminalmage might have some useful input here.

**Comment by terminalmage** [comment]
I see nothing in that error message that suggests the problem is caused by gitfs, just that the error was triggered during a gitfs operation.

Did you try runing lsof and seeing where all the open filehandles are?

**Comment by Azidburn** [comment]
Yes i did, that why i think the issue is with git.
Here my lsof (open file count: ~160k)
```
lsof -n | grep salt-mas | cut -d'/' -f2- | sort | uniq -c
    182 
    363 dev/null
     91 lib64/ld-2.19.so
     71 lib64/libacl.so.1.1.0
     71 lib64/libattr.so.1.1.0
     91 lib64/libc-2.19.so
     71 lib64/libcap.so.2.22                                                                                                                                                                                                                                                   
     71 lib64/libcrypt-2.19.so                                                                                                                                                                                                                                                 
     91 lib64/libcrypto.so.1.0.0                                                                                                                                                                                                                                               
     91 lib64/libdl-2.19.so                                                                                                                                                                                                                                                    
     91 lib64/libgcc_s.so.1                                                                                                                                                                                                                                                    
     71 lib64/libkeyutils.so.1.5                                                                                                                                                                                                                                               
     91 lib64/libm-2.19.so                                                                                                                                                                                                                                                     
     91 lib64/libnsl-2.19.so                                                                                                                                                                                                                                                   
     91 lib64/libnss_compat-2.19.so                                                                                                                                                                                                                                            
     71 lib64/libnss_dns-2.19.so                                                                                                                                                                                                                                               
     91 lib64/libnss_files-2.19.so                                                                                                                                                                                                                                             
     91 lib64/libnss_nis-2.19.so                                                                                                                                                                                                                                               
     70 lib64/libpam.so.0.83.1                                                                                                                                                                                                                                                 
     91 lib64/libpthread-2.19.so                                                                                                                                                                                                                                               
     71 lib64/libresolv-2.19.so                                                                                                                                                                                                                                                
     91 lib64/librt-2.19.so                                                                                                                                                                                                                                                    
     71 lib64/libselinux.so.1                                                                                                                                                                                                                                                  
     91 lib64/libssl.so.1.0.0                                                                                                                                                                                                                                                  
     91 lib64/libutil-2.19.so                                                                                                                                                                                                                                                  
     91 lib64/libz.so.1.2.8                                                                                                                                                                                                                                                    
     91 usr/bin/python2.7
     91 usr/lib/locale/de_DE.utf8/LC_CTYPE
     91 usr/lib64/gconv/gconv-modules.cache
     71 usr/lib64/girepository-1.0/GLib-2.0.typelib
     71 usr/lib64/girepository-1.0/GObject-2.0.typelib
     71 usr/lib64/girepository-1.0/Gio-2.0.typelib
     70 usr/lib64/libaudit.so.1.0.0
     71 usr/lib64/libbz2.so.1.0.6
     71 usr/lib64/libcom_err.so.2.1
     71 usr/lib64/libcurl.so.4.3.0
     71 usr/lib64/libelf-0.158.so
     71 usr/lib64/libexpat.so.1.6.0
     91 usr/lib64/libffi.so.4.0.1
     71 usr/lib64/libgio-2.0.so.0.4200.1
     71 usr/lib64/libgirepository-1.0.so.1.0.0
     91 usr/lib64/libgit2.so.0.21.0
     71 usr/lib64/libglib-2.0.so.0.4200.1
     71 usr/lib64/libgmodule-2.0.so.0.4200.1
     71 usr/lib64/libgmp.so.10.1.3
     71 usr/lib64/libgobject-2.0.so.0.4200.1
     71 usr/lib64/libgssapi_krb5.so.2.2
     71 usr/lib64/libidn.so.11.6.11
     71 usr/lib64/libk5crypto.so.3.1
     71 usr/lib64/libkrb5.so.3.3
     71 usr/lib64/libkrb5support.so.0.1
     71 usr/lib64/liblber-2.4.so.2.10.2
     71 usr/lib64/libldap-2.4.so.2.10.2
     71 usr/lib64/liblua.so.5.1
     71 usr/lib64/liblzma.so.5.0.7
     71 usr/lib64/libmodman.so.1.0.0
     71 usr/lib64/libpcre.so.1.2.3
     71 usr/lib64/libpopt.so.0.0.0
     71 usr/lib64/libproxy.so.1.0.0
     91 usr/lib64/libpython2.7.so.1.0
     71 usr/lib64/librpm.so.3.2.2
     71 usr/lib64/librpmio.so.3.2.2
     71 usr/lib64/libsasl2.so.3.0.0
     91 usr/lib64/libsodium.so.13.0.2
     71 usr/lib64/libsqlite3.so.0.8.6
     91 usr/lib64/libssh2.so.1.0.1
     91 usr/lib64/libstdc++.so.6.0.19
     71 usr/lib64/libudev.so.1.4.0
     91 usr/lib64/libuuid.so.1.3.0
     71 usr/lib64/libxml2.so.2.9.1
     91 usr/lib64/libyaml-0.so.2.0.4
     91 usr/lib64/libzmq.so.4.0.0
     71 usr/lib64/libzypp.so.1430.6.0
     91 usr/lib64/python2.7/lib-dynload/_bisect.so
     91 usr/lib64/python2.7/lib-dynload/_collections.so
     71 usr/lib64/python2.7/lib-dynload/_csv.so
     91 usr/lib64/python2.7/lib-dynload/_ctypes.so
     91 usr/lib64/python2.7/lib-dynload/_elementtree.so
     91 usr/lib64/python2.7/lib-dynload/_functools.so
     91 usr/lib64/python2.7/lib-dynload/_hashlib.so
     91 usr/lib64/python2.7/lib-dynload/_heapq.so
     91 usr/lib64/python2.7/lib-dynload/_io.so
     91 usr/lib64/python2.7/lib-dynload/_json.so
     91 usr/lib64/python2.7/lib-dynload/_locale.so
     91 usr/lib64/python2.7/lib-dynload/_multiprocessing.so
     91 usr/lib64/python2.7/lib-dynload/_random.so
     91 usr/lib64/python2.7/lib-dynload/_socket.so
     71 usr/lib64/python2.7/lib-dynload/_sqlite3.so
     91 usr/lib64/python2.7/lib-dynload/_ssl.so
     91 usr/lib64/python2.7/lib-dynload/_struct.so
     91 usr/lib64/python2.7/lib-dynload/array.so
     91 usr/lib64/python2.7/lib-dynload/binascii.so
     91 usr/lib64/python2.7/lib-dynload/cPickle.so
     91 usr/lib64/python2.7/lib-dynload/cStringIO.so
     71 usr/lib64/python2.7/lib-dynload/crypt.so
     91 usr/lib64/python2.7/lib-dynload/datetime.so
     91 usr/lib64/python2.7/lib-dynload/fcntl.so
     91 usr/lib64/python2.7/lib-dynload/future_builtins.so
     91 usr/lib64/python2.7/lib-dynload/grp.so
     91 usr/lib64/python2.7/lib-dynload/itertools.so
     91 usr/lib64/python2.7/lib-dynload/math.so
     91 usr/lib64/python2.7/lib-dynload/mmap.so
     91 usr/lib64/python2.7/lib-dynload/operator.so
     91 usr/lib64/python2.7/lib-dynload/pyexpat.so
     91 usr/lib64/python2.7/lib-dynload/resource.so
     91 usr/lib64/python2.7/lib-dynload/select.so
     71 usr/lib64/python2.7/lib-dynload/spwd.so
     91 usr/lib64/python2.7/lib-dynload/strop.so
      1 usr/lib64/python2.7/lib-dynload/syslog.so
     91 usr/lib64/python2.7/lib-dynload/termios.so
     91 usr/lib64/python2.7/lib-dynload/time.so
     91 usr/lib64/python2.7/lib-dynload/zlib.so
     91 usr/lib64/python2.7/site-packages/Crypto/Cipher/_AES.so
     71 usr/lib64/python2.7/site-packages/Crypto/PublicKey/_fastmath.so
     71 usr/lib64/python2.7/site-packages/Crypto/Util/_counter.so
     91 usr/lib64/python2.7/site-packages/M2Crypto/__m2crypto.so
     91 usr/lib64/python2.7/site-packages/_cffi__xc32f3271x2bbed4fa.so
     91 usr/lib64/python2.7/site-packages/_cffi_backend.so
     91 usr/lib64/python2.7/site-packages/_psutil_linux.so
     91 usr/lib64/python2.7/site-packages/_psutil_posix.so
     91 usr/lib64/python2.7/site-packages/_pygit2.so
     91 usr/lib64/python2.7/site-packages/_yaml.so
     71 usr/lib64/python2.7/site-packages/_zypp.so
     71 usr/lib64/python2.7/site-packages/gi/_gi.so
     91 usr/lib64/python2.7/site-packages/gitdb/_perf.so
     91 usr/lib64/python2.7/site-packages/markupsafe/_speedups.so
     91 usr/lib64/python2.7/site-packages/msgpack/_packer.so
     91 usr/lib64/python2.7/site-packages/msgpack/_unpacker.so
     91 usr/lib64/python2.7/site-packages/simplejson/_speedups.so
     91 usr/lib64/python2.7/site-packages/zmq/backend/cython/_device.so
     91 usr/lib64/python2.7/site-packages/zmq/backend/cython/_poll.so
     91 usr/lib64/python2.7/site-packages/zmq/backend/cython/_version.so
     91 usr/lib64/python2.7/site-packages/zmq/backend/cython/constants.so
     91 usr/lib64/python2.7/site-packages/zmq/backend/cython/context.so
     91 usr/lib64/python2.7/site-packages/zmq/backend/cython/error.so
     91 usr/lib64/python2.7/site-packages/zmq/backend/cython/message.so
     91 usr/lib64/python2.7/site-packages/zmq/backend/cython/socket.so
     91 usr/lib64/python2.7/site-packages/zmq/backend/cython/utils.so
     91 usr/lib64/python2.7/site-packages/zmq/devices/monitoredqueue.so
     71 var/cache/salt/master/gitfs/074ece2ff7075438089203cd40e3ce47/.git/objects/pack/pack-0e39b0e5e70bd69c6d4f985274969d94ffd252f3.idx
  44336 var/cache/salt/master/gitfs/074ece2ff7075438089203cd40e3ce47/.git/objects/pack/pack-0e39b0e5e70bd69c6d4f985274969d94ffd252f3.pack
     71 var/cache/salt/master/gitfs/074ece2ff7075438089203cd40e3ce47/.git/objects/pack/pack-17769de033d9a666170d04e5fb0057ae3c72bce3.idx
  38897 var/cache/salt/master/gitfs/074ece2ff7075438089203cd40e3ce47/.git/objects/pack/pack-17769de033d9a666170d04e5fb0057ae3c72bce3.pack
     71 var/cache/salt/master/gitfs/074ece2ff7075438089203cd40e3ce47/.git/objects/pack/pack-3144fc50e879f79cf7c5cd0b580f03c83f549609.idx
   2159 var/cache/salt/master/gitfs/074ece2ff7075438089203cd40e3ce47/.git/objects/pack/pack-3144fc50e879f79cf7c5cd0b580f03c83f549609.pack
     71 var/cache/salt/master/gitfs/074ece2ff7075438089203cd40e3ce47/.git/objects/pack/pack-6edcd40693c49d3876d87b8bccb79db4ef586174.idx
   8587 var/cache/salt/master/gitfs/074ece2ff7075438089203cd40e3ce47/.git/objects/pack/pack-6edcd40693c49d3876d87b8bccb79db4ef586174.pack
     71 var/cache/salt/master/gitfs/074ece2ff7075438089203cd40e3ce47/.git/objects/pack/pack-728126838183a517e7826f29bbc71930ea527ca7.idx
   3836 var/cache/salt/master/gitfs/074ece2ff7075438089203cd40e3ce47/.git/objects/pack/pack-728126838183a517e7826f29bbc71930ea527ca7.pack
     71 var/cache/salt/master/gitfs/074ece2ff7075438089203cd40e3ce47/.git/objects/pack/pack-84516bbcf5d1c8416b20c6d4b2ad83e2b48ecb86.idx
   2333 var/cache/salt/master/gitfs/074ece2ff7075438089203cd40e3ce47/.git/objects/pack/pack-84516bbcf5d1c8416b20c6d4b2ad83e2b48ecb86.pack
     71 var/cache/salt/master/gitfs/074ece2ff7075438089203cd40e3ce47/.git/objects/pack/pack-d07986e062a3ead0e906c166263aa4b37a8bc252.idx
   1957 var/cache/salt/master/gitfs/074ece2ff7075438089203cd40e3ce47/.git/objects/pack/pack-d07986e062a3ead0e906c166263aa4b37a8bc252.pack
     71 var/cache/salt/master/gitfs/074ece2ff7075438089203cd40e3ce47/.git/objects/pack/pack-d3200a2cf965b7d381e5599aa4631ebc3ef9875e.idx
  44330 var/cache/salt/master/gitfs/074ece2ff7075438089203cd40e3ce47/.git/objects/pack/pack-d3200a2cf965b7d381e5599aa4631ebc3ef9875e.pack
     71 var/cache/salt/master/gitfs/074ece2ff7075438089203cd40e3ce47/.git/objects/pack/pack-d3426fb133a0512a64fe8e48ea5c3f264bb622c0.idx
     71 var/cache/salt/master/gitfs/074ece2ff7075438089203cd40e3ce47/.git/objects/pack/pack-f1ce66b3ec4fb6ca1dee12c06dfe7d185f389314.idx
      3 var/run/salt/master/master_event_pub.ipc
     63 var/run/salt/master/master_event_pull.ipc
      3 var/run/salt/master/publish_pull.ipc
    132 var/run/salt/master/workers.ipc
```

**Comment by terminalmage** [comment]
Since this issue was opened, gitfs has undergone significant re-architecting. I would be interested to see if you are still experiencing this.

I'm still skeptical that this is being caused by Salt code, however, as all usage of filehandles in gitfs has been carefully done using ``with`` blocks to ensure that the filehandle is closed. The files with a high number of open filehandles are also largely git metadata, the objects obtained during a fetch. This leads me to believe that the real culprit here is sloppy code in pygit2, so an update to a newer release of pygit2 may also solve this problem.

**Comment by Azidburn** [comment]
I implemented a dirty workaround for this Bug.
I hope i can test if this Bug is still there.  I will test it with 2015.8, which is our productive version.

**Comment by scallister** [comment]
I'm currently using GitFS and seeing a large number of open file handles (410k) attributed to that /var/cache/salt/master/gitfs location.

I'm running `salt-master 2018.3.1 (Oxygen)`. What other info would be helpful for debugging this?

**Comment by rallytime** [comment]
Hey @scallister - it might be worth opening up a new bug with updated information. (reproduction steps, version you're running, etc) That way some more eyes might see it. Be sure to link back to this one!
