### ISSUE TITLE
Random 'Failed to authenticate!' while running commands on master.

### ISSUE THREAD

**Issue by jakubmm** [saltstack/salt#22650]
We're getting random 'Failed to authenticate' messages when running commands on salt master, and occasionally minions are TypeErroring:
```
[j@salt-conf salt]$ sudo salt -v '008*' test.ping
Executing job with jid 20150414123557337413
-------------------------------------------

Failed to authenticate!  This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).
[j@salt-conf salt]$
```
Versions on the master:
```
[j@salt-conf salt]$ salt-master --versions
           Salt: 2014.7.1
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: unknown
       M2Crypto: 0.20.2
 msgpack-python: 0.4.4
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
[j@salt-conf salt]$ 
```
Versions on the minion:
```
           Salt: 2014.7.0
         Python: 2.6.8 (unknown, Nov  7 2012, 14:47:45)
         Jinja2: 2.5.5
       M2Crypto: 0.21.1
 msgpack-python: 0.1.12
   msgpack-pure: Not Installed
       pycrypto: 2.3
        libnacl: Not Installed
         PyYAML: 3.08
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.2
           Mako: Not Installed
```
/var/log/salt/minion on salt minion:
```
2015-04-14 13:43:46,223 [salt.minion                                 ][INFO    ] User sudo_j Executing command saltutil.refresh_pillar with jid 20150414134346225534
2015-04-14 13:43:46,235 [salt.minion                                 ][INFO    ] Starting a new job with PID 12093
2015-04-14 13:43:46,265 [salt.minion                                 ][INFO    ] Returning information for job: 20150414134346225534
2015-04-14 13:51:04,019 [salt             ][INFO    ] Setting up the Salt Minion "008.domain.ie"
2015-04-14 13:51:04,760 [salt.minion                              ][INFO    ] Authentication with master at 172.30.143.6 successful!
2015-04-14 13:51:05,093 [salt.log.setup                           ][ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: string indices must be integers, not str
Traceback (most recent call last):
  File "/usr/bin/salt-minion", line 14, in <module>
    salt_minion()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 56, in salt_minion
    minion.start()
  File "/usr/lib/python2.6/site-packages/salt/__init__.py", line 262, in start
    self.prepare()
  File "/usr/lib/python2.6/site-packages/salt/__init__.py", line 241, in prepare
    self.minion = salt.minion.Minion(self.config)
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 603, in __init__
    opts['environment'],
  File "/usr/lib/python2.6/site-packages/salt/pillar/__init__.py", line 91, in compile_pillar
    ret_pillar = self.sreq.crypted_transfer_decode_dictentry(load, dictkey='pillar', tries=3, timeout=7200)
  File "/usr/lib/python2.6/site-packages/salt/transport/__init__.py", line 236, in crypted_transfer_decode_dictentry
    aes = key.private_decrypt(ret['key'], 4)
TypeError: string indices must be integers, not str
```
Any hints how to pin down the root cause will be appreciated!

Regards,
Jakub

**Comment by rallytime** [comment]
@jakubmm When you say you're getting "random" errors like this, how often do you see this error? Anything else you can give us to help track this down?  (Do you have anything like multi-master or syndic setup? Is the master still running after you see that error? What system are you running your master on and the affected minions? )

Can you give some more information about the TypeError you're seeing on the minion? Do you think those two events are related? You said the TypeError occasionally occurs on the minion - does that correlate the random Authentication problems on the master?

**Comment by jakubmm** [comment]
@rallytime By random i mean when running test.ping it happens on irregular intervals - there doesn't seem to be a pattern there.
We have ordinary one master setup - no syndic.
I checked some minions that are not currently connected and they all have the same message in minion log as the last message:
2015-04-16 09:43:21,206 [salt.minion                              ][INFO    ] Authentication with master at 172.30.143.6 successful!
2015-04-16 09:43:24,082 [salt.log.setup                           ][ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: string indices must be integers, not str
Traceback (most recent call last):
  File "/usr/bin/salt-minion", line 14, in <module>
    salt_minion()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 56, in salt_minion
    minion.start()
  File "/usr/lib/python2.6/site-packages/salt/__init__.py", line 262, in start
    self.prepare()
  File "/usr/lib/python2.6/site-packages/salt/__init__.py", line 241, in prepare
    self.minion = salt.minion.Minion(self.config)
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 603, in __init__
    opts['environment'],
  File "/usr/lib/python2.6/site-packages/salt/pillar/__init__.py", line 91, in compile_pillar
    ret_pillar = self.sreq.crypted_transfer_decode_dictentry(load, dictkey='pillar', tries=3, timeout=7200)
  File "/usr/lib/python2.6/site-packages/salt/transport/__init__.py", line 236, in crypted_transfer_decode_dictentry
    aes = key.private_decrypt(ret['key'], 4)
TypeError: string indices must be integers, not str

Whent the error occurs on master (the auth error) I see the following in the master log:

2015-04-17 09:10:10,649 [salt.client      ][DEBUG   ] Checking whether jid 20150417091000632879 is still running
2015-04-17 09:10:10,651 [salt.master                                ][INFO    ] Clear payload received with command publish
2015-04-17 09:10:10,651 [salt.master                                ][WARNING ] Authentication failure of type "user" occurred.
2015-04-17 09:10:33,009 [salt.config                                 ][DEBUG   ] Reading configuration from /etc/salt/master
2015-04-17 09:10:33,035 [salt.config                                 ][DEBUG   ] Including configuration from '/etc/salt/minion.d/grains.conf'
2015-04-17 09:10:33,036 [salt.config                                 ][DEBUG   ] Reading configuration from /etc/salt/minion.d/grains.conf
2015-04-17 09:10:33,037 [salt.config                                 ][DEBUG   ] Using cached minion ID from /etc/salt/minion_id: conf-mgmt001.dub.domain.local
2015-04-17 09:10:33,038 [salt.config                                 ][DEBUG   ] Reading configuration from /etc/salt/master
2015-04-17 09:10:33,063 [salt.config                                 ][DEBUG   ] Including configuration from '/etc/salt/master.d/nodegroups.conf'
2015-04-17 09:10:33,063 [salt.config                                 ][DEBUG   ] Reading configuration from /etc/salt/master.d/nodegroups.conf
2015-04-17 09:10:33,234 [salt.loaded.int.grain.core                  ][DEBUG   ] The `dmidecode` binary is not available on the system. GPU grains will not be available.
2015-04-17 09:10:34,742 [salt.loader                                 ][DEBUG   ] LazyLoaded local_cache.clean_old_jobs
2015-04-17 09:10:34,830 [salt.fileserver                             ][DEBUG   ] Updating fileserver cache
2015-04-17 09:10:34,955 [salt.utils.verify                           ][DEBUG   ] This salt-master instance has accepted 36 minion keys.

Minions die when trying to access or process pillars. We will revert week of changes to see if that was it.
Let me know if there's any further information I can provide.

Master: CentOS 6.6\
$ salt-master --versions
           Salt: 2014.7.1
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: unknown
       M2Crypto: 0.20.2
 msgpack-python: 0.4.4
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed

Minions: CentOS 5.9
$ salt-minion --versions
           Salt: 2014.7.0
         Python: 2.6.8 (unknown, Nov  7 2012, 14:47:45)
         Jinja2: 2.5.5
       M2Crypto: 0.21.1
 msgpack-python: 0.1.12
   msgpack-pure: Not Installed
       pycrypto: 2.3
        libnacl: Not Installed
         PyYAML: 3.08
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.2
           Mako: Not Installed

**Comment by jakubmm** [comment]
@rallytime I think I found something I can correlate.
When starting minion on a host i get the following error:
```
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: string indices must be integers, not str
Traceback (most recent call last):
  File "/usr/bin/salt-minion", line 14, in <module>
    salt_minion()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 56, in salt_minion
    minion.start()
  File "/usr/lib/python2.6/site-packages/salt/__init__.py", line 262, in start
    self.prepare()
  File "/usr/lib/python2.6/site-packages/salt/__init__.py", line 241, in prepare
    self.minion = salt.minion.Minion(self.config)
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 603, in __init__
    opts['environment'],
  File "/usr/lib/python2.6/site-packages/salt/pillar/__init__.py", line 91, in compile_pillar
    ret_pillar = self.sreq.crypted_transfer_decode_dictentry(load, dictkey='pillar', tries=3, timeout=7200)
  File "/usr/lib/python2.6/site-packages/salt/transport/__init__.py", line 236, in crypted_transfer_decode_dictentry
    aes = key.private_decrypt(ret['key'], 4)
TypeError: string indices must be integers, not str
Traceback (most recent call last):
  File "/usr/bin/salt-minion", line 14, in <module>
    salt_minion()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 56, in salt_minion
    minion.start()
  File "/usr/lib/python2.6/site-packages/salt/__init__.py", line 262, in start
    self.prepare()
  File "/usr/lib/python2.6/site-packages/salt/__init__.py", line 241, in prepare
    self.minion = salt.minion.Minion(self.config)
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 603, in __init__
    opts['environment'],
  File "/usr/lib/python2.6/site-packages/salt/pillar/__init__.py", line 91, in compile_pillar
    ret_pillar = self.sreq.crypted_transfer_decode_dictentry(load, dictkey='pillar', tries=3, timeout=7200)
  File "/usr/lib/python2.6/site-packages/salt/transport/__init__.py", line 236, in crypted_transfer_decode_dictentry
    aes = key.private_decrypt(ret['key'], 4)
TypeError: string indices must be integers, not str
```

at the same time I see on master:

```
2015-04-17 11:34:25,625 [salt.master                                ][INFO    ] Clear payload received with command _auth
2015-04-17 11:34:25,626 [salt.master                                ][INFO    ] Authentication request from app006.domain.local
2015-04-17 11:34:25,626 [salt.master                                ][INFO    ] Authentication accepted from app006.domain.local
2015-04-17 11:34:25,793 [salt.utils.event                           ][DEBUG   ] Sending event - data = {'id': 'app006.domain.local', '_stamp': '2015-04-17T11:34:25.792633', 'result': True, 'pub': '-----BEGIN PUBLIC KEY-----\nMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA24jXld5+CsOV4DPA03Lt\n/H2OgXDeXaza6H33a1RSLpJIoprnRgKgtmJQ9jodXCJKqjjDBQX4JSiemrvNLC7c\ncHvPwGQxJh1viNB0z5Q120F22WVSvnM0INSst3qw1XayHGf6mNHmS2mfpxaQk2Js\nhM/fgwCt22GyvhO8eqCpyA/otPSlN8jbE7DiBOaJ+pic1gewBIVfOx7FASRTjyv6\nqNa3ayZsiT07h+zqvhF698uvHBER4+d7sA3N14mfZ5jZsHcM0/pQ6uzDv3XHDZig\nTUO/60RFbwz8/g8cJDr33DikVeMUQLwPqNmX33woQRFapzIDL/q2APiOY3xj8ED1\noerrm6RWoVOgqTo2rcAuQ0M5ATY8aqqjdPpiQHxIoYMKDIo0Ke7dOnA7XhjK2/Vx\nj+5xtrio5L7pgAo3N6p7Rk5H3KQA3dsIsGiuxucJO66DrI8iU900Z4LOfOIaO3ou\n88U687GIjfyGEduYuRve3BCTxmtgvh6zyXjAgTOejclSJ4EvnMA1yLe30VbIOBFk\niRHSMxg656EsTBVsxo2QKZq416jy2EFbAQRlFjRlwCY6f/UJmYJ9o6x5p4VWZq5k\n8ePq1sIc9CPZf/h8p2Lxe1SmKn1yPE0v+y5wgc4SbjbGfuST9123psWIfHKSLG7m\neTqDT2nX1q4EuJJ1ujKf5TUCAwEAAQ==\n-----END PUBLIC KEY-----\n', 'act': 'accept'}
2015-04-17 11:34:26,024 [salt.master                                ][INFO    ] Clear payload received with command _auth
2015-04-17 11:34:26,024 [salt.master                                ][INFO    ] Authentication request from app006.domain.local
2015-04-17 11:34:26,025 [salt.master                                ][INFO    ] Authentication accepted from app006.domain.local
2015-04-17 11:34:26,192 [salt.utils.event                           ][DEBUG   ] Sending event - data = {'id': 'app006.domain.local', '_stamp': '2015-04-17T11:34:26.191604', 'result': True, 'pub': '-----BEGIN PUBLIC KEY-----\nMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA24jXld5+CsOV4DPA03Lt\n/H2OgXDeXaza6H33a1RSLpJIoprnRgKgtmJQ9jodXCJKqjjDBQX4JSiemrvNLC7c\ncHvPwGQxJh1viNB0z5Q120F22WVSvnM0INSst3qw1XayHGf6mNHmS2mfpxaQk2Js\nhM/fgwCt22GyvhO8eqCpyA/otPSlN8jbE7DiBOaJ+pic1gewBIVfOx7FASRTjyv6\nqNo3lyZsiT07h+zqvhF698uvHBER4+d7sA3N14mfZ5jZsHcM0/pQ6uzDv3XHDZig\nTUO/60RFbwz8/g8cJDr33DikVeMUQLwPqNmX33woQRF9pzIDL/q2APiOY3xj8ED1\noerrm6RWoVOgqTo2rcAuQ0M5ATY8BqqjdPpiQHxIoYMKDIo0Ke7dOnA7XhjK2/Vx\nj+5xtrio5L7pgAo3N6p7Rk5H3KQA3asIsGiuxucJO66DrI8iU900Z4LOfOIaO3ou\n88U687GIjfyGEduYuRve3BCTxmtgvh6zyXjAgTOejclSJ4EvnMA1yLe30VbIOBFk\niRHSMxg656EsTBVsxo2QKZq416jy2EFbAQRlFjRlwCY6f/UJmYJ9o6x5p4VWZq5k\n8ePq1sIc9CPZf/h8p2Lxe1SmKn1yPE0v+y5wgc4SbjbGfuST9123psWIfHKSLG7m\neTqDT2nX1q4EuJJ1ujKf5TUCAwEAAQ==\n-----END PUBLIC KEY-----\n', 'act': 'accept'}
2015-04-17 11:34:26,410 [salt.crypt                                 ][DEBUG   ] Failed to authenticate message
```

Hope that helps a bit more.

**Comment by rallytime** [comment]
Definitely! Thanks very much for all of this information. One thing I would suggest for sure is to upgrade your versions of ZMQ on your master and minions to see if that helps reduce some of these spurious errors. There are squirrelly issues like this that have been fixed in the past by doing that as there are known bugs with 3.x versions of ZMQ.

ZMQ 4 can be found for CentOS 5 in our [COPR repo](https://copr.fedoraproject.org/coprs/saltstack/salt-el5/)

**Comment by cachedout** [comment]
Are you starting multiple minions with the same minion id, by chance?

**Comment by jakubmm** [comment]
@cachedout Hi Mike, no there's no duplicate names there.
@rallytime Nicole, here's what I did to get rid of the issue:
1) I rolled back our saltstack code base (states,pillars) to what it was a week ago and started applying them gradually but that didnt' fix the issue
2) Decided to go medival on the minions:
  - removed all associations
  - stopped the minions
  - sudo rm -fr /var/cache/salt/minion/*
  - updated salt-minion,salt and python-zmq/zeromq from the COPR repo
  - accepted the minions back on the master

So far it's been working fine - no more errors so far.

**Comment by jinlongwang** [comment]
hello i'm getting this issue right now
here is my info 
Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 6.6 Final
        machine: x86_64
        release: 2.6.32-504.30.3.el6.x86_64
         system: CentOS 6.6 Final
