### ISSUE TITLE
Attempt to authenticate with the salt master failed

### ISSUE THREAD

**Issue by moxxbiales** [saltstack/salt#22654]
Hi,
I'm a brand new salt user and i've got problems concerning the master / minion communication.
I'm starting a new job in 2 weeks and i've to get used with salt for this job. 
I've installed salt master and a salt minion on a centos 6 virtual machine.
(192.168.0.55)
i've installed 2 more salt minions on 2 debian virtual machines
(192.168.0.51 and 192.168.0.54)
the authentification with the minion of the centos machine works but the 2 others don't.
here are the log files.

1. MASTER CONFIG///////////////
I've touched nothing on the config file

2.MINION 192.168.0.55 CONFIG////
```
[root@centos6 ~]# hostname
centos6.local
```
(the parts i haved changed)
```
# Set the location of the salt master server. If the master server cannot be
# resolved, then the minion will fail to start.
#master: salt
master: 192.168.0.55
...
# The user to run salt.
user: root
...
# Explicitly declare the id for this minion to use, if left commented the id
# will be the hostname as returned by the python call: socket.getfqdn()
# Since salt uses detached ids it is possible to run multiple minions on the
# same machine but with different ids, this can be useful for salt compute
# clusters.
id: centos6
```
3.MINION 192.168.0.54 CONFIG////
```
root@debiancacti:~# hostname
debiancacti

# Set the location of the salt master server. If the master server cannot be
# resolved, then the minion will fail to start.
#master: salt
master: 192.168.0.55
...
# The user to run salt.
user: root
...
# Explicitly declare the id for this minion to use, if left commented the id
# will be the hostname as returned by the python call: socket.getfqdn()
# Since salt uses detached ids it is possible to run multiple minions on the
# same machine but with different ids, this can be useful for salt compute
# clusters.
id: debiancacti
```
4.MINION 192.168.0.51 CONFIG////
```
root@debianxen:~# hostname
debianxen
#master: salt
master: 192.168.0.55
...
# The user to run salt.
user: root
...
#id:
id: debianxen
```
Now, this the log files i got 
5. LOGFILES

FROM 192.168.0.51
```
2015-04-14 16:05:13,122 [salt                                     ][ERROR   ] Attempt to authenticate with the salt master failed
2015-04-14 16:09:24,637 [salt             ][INFO    ] Setting up the Salt Minion "Rine"
2015-04-14 16:09:24,637 [salt.utils.process][DEBUG   ] Created pidfile: /var/run/salt-minion.pid
2015-04-14 16:09:24,638 [salt.config      ][DEBUG   ] Reading configuration from /etc/salt/minion
2015-04-14 16:09:25,671 [salt.minion      ][DEBUG   ] Attempting to authenticate with the Salt Master at 192.168.0.55
2015-04-14 16:09:25,673 [salt.crypt       ][DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
2015-04-14 16:09:26,587 [salt                                     ][ERROR   ] Attempt to authenticate with the salt master failed
2015-04-14 16:10:25,905 [salt             ][ERROR   ] Attempt to authenticate with the salt master failed
2015-04-14 16:13:10,368 [salt                                     ][ERROR   ] Attempt to authenticate with the salt master failed
```
FROM 192.168.0.54
```
2015-04-13 14:04:44,642 [salt                                     ][ERROR   ] Attempt to authenticate with the salt master failed
2015-04-13 14:14:11,854 [salt             ][WARNING ] Stopping the Salt Minion
2015-04-13 14:14:11,855 [salt             ][WARNING ] Exiting on Ctrl-c
2015-04-13 14:15:18,071 [salt                                     ][ERROR   ] Attempt to authenticate with the salt master failed
2015-04-13 14:15:25,058 [salt             ][ERROR   ] Attempt to authenticate with the salt master failed
2015-04-13 14:20:04,224 [salt             ][ERROR   ] Attempt to authenticate with the salt master failed
2015-04-13 14:21:04,478 [salt             ][INFO    ] Setting up the Salt Minion "debiancacti.debiancacti.local"
2015-04-13 14:21:04,479 [salt.utils.process][DEBUG   ] Created pidfile: /var/run/salt-minion.pid
2015-04-13 14:21:04,479 [salt.config      ][DEBUG   ] Reading configuration from /etc/salt/minion
2015-04-13 14:21:04,784 [salt.minion      ][DEBUG   ] Attempting to authenticate with the Salt Master at 192.168.0.55
2015-04-13 14:21:04,786 [salt.crypt       ][DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
2015-04-13 14:22:05,031 [salt             ][ERROR   ] Attempt to authenticate with the salt master failed
2015-04-13 14:26:34,314 [salt.utils       ][ERROR   ] DNS lookup of 'salt' failed.
2015-04-13 14:26:34,315 [salt.minion      ][ERROR   ] Master hostname: 'salt' not found. Retrying in 30 seconds
2015-04-13 14:26:54,339 [salt             ][WARNING ] Stopping the Salt Minion
2015-04-13 14:26:54,339 [salt             ][WARNING ] Exiting on Ctrl-c
2015-04-13 14:27:16,835 [salt.utils       ][ERROR   ] DNS lookup of 'salt' failed.
2015-04-13 14:27:16,836 [salt.minion      ][ERROR   ] Master hostname: 'salt' not found. Retrying in 30 seconds
2015-04-13 14:27:26,067 [salt             ][WARNING ] Stopping the Salt Minion
2015-04-13 14:27:26,068 [salt             ][WARNING ] Exiting on Ctrl-c
2015-04-13 14:45:37,959 [salt.utils       ][ERROR   ] DNS lookup of 'centos6.local' failed.
2015-04-13 14:45:37,960 [salt.minion      ][ERROR   ] Master hostname: 'centos6.local' not found. Retrying in 30 seconds
2015-04-13 14:46:08,127 [salt.utils       ][ERROR   ] DNS lookup of 'centos6.local' failed.
2015-04-13 14:46:08,127 [salt.minion      ][ERROR   ] Master hostname: 'centos6.local' not found. Retrying in 30 seconds
2015-04-13 14:46:38,423 [salt.utils       ][ERROR   ] DNS lookup of 'centos6.local' failed.
2015-04-13 14:46:38,424 [salt.minion      ][ERROR   ] Master hostname: 'centos6.local' not found. Retrying in 30 seconds
2015-04-13 14:47:08,533 [salt.utils       ][ERROR   ] DNS lookup of 'centos6.local' failed.
2015-04-13 14:47:08,534 [salt.minion      ][ERROR   ] Master hostname: 'centos6.local' not found. Retrying in 30 seconds
2015-04-13 14:47:38,659 [salt.utils       ][ERROR   ] DNS lookup of 'centos6.local' failed.
2015-04-13 14:47:38,660 [salt.minion      ][ERROR   ] Master hostname: 'centos6.local' not found. Retrying in 30 seconds
2015-04-13 14:48:08,804 [salt.utils       ][ERROR   ] DNS lookup of 'centos6.local' failed.
2015-04-13 14:48:08,805 [salt.minion      ][ERROR   ] Master hostname: 'centos6.local' not found. Retrying in 30 seconds
2015-04-13 14:48:38,932 [salt.utils       ][ERROR   ] DNS lookup of 'centos6.local' failed.
2015-04-13 14:48:38,932 [salt.minion      ][ERROR   ] Master hostname: 'centos6.local' not found. Retrying in 30 seconds
2015-04-13 14:49:09,072 [salt.utils       ][ERROR   ] DNS lookup of 'centos6.local' failed.
2015-04-13 14:49:09,073 [salt.minion      ][ERROR   ] Master hostname: 'centos6.local' not found. Retrying in 30 seconds
2015-04-13 14:49:39,200 [salt.utils       ][ERROR   ] DNS lookup of 'centos6.local' failed.
2015-04-13 14:49:39,200 [salt.minion      ][ERROR   ] Master hostname: 'centos6.local' not found. Retrying in 30 seconds
2015-04-13 14:50:09,323 [salt.utils       ][ERROR   ] DNS lookup of 'centos6.local' failed.
2015-04-13 14:50:09,323 [salt.minion      ][ERROR   ] Master hostname: 'centos6.local' not found. Retrying in 30 seconds
2015-04-13 14:50:39,444 [salt.utils       ][ERROR   ] DNS lookup of 'centos6.local' failed.
2015-04-13 14:50:39,445 [salt.minion      ][ERROR   ] Master hostname: 'centos6.local' not found. Retrying in 30 seconds
2015-04-13 14:50:47,883 [salt             ][WARNING ] Stopping the Salt Minion
2015-04-13 14:50:47,883 [salt             ][WARNING ] Exiting on Ctrl-c
2015-04-13 14:52:50,986 [salt.config      ][ERROR   ] Error parsing configuration file: /etc/salt/minion - while parsing a block node
expected the node content, but found '?'
  in "<string>", line 17, column 1:
    + master: 192.168.0.55
    ^
2015-04-13 14:52:51,382 [salt.utils       ][ERROR   ] DNS lookup of 'salt' failed.
2015-04-13 14:52:51,383 [salt.minion      ][ERROR   ] Master hostname: 'salt' not found. Retrying in 30 seconds
2015-04-13 14:53:09,317 [salt             ][WARNING ] Stopping the Salt Minion
2015-04-13 14:53:09,318 [salt             ][WARNING ] Exiting on Ctrl-c
2015-04-13 14:53:23,326 [salt.config      ][ERROR   ] Error parsing configuration file: /etc/salt/minion - conf should be a document, not <type 'list'>.
2015-04-13 14:53:23,758 [salt.utils       ][ERROR   ] DNS lookup of 'salt' failed.
2015-04-13 14:53:23,759 [salt.minion      ][ERROR   ] Master hostname: 'salt' not found. Retrying in 30 seconds
2015-04-13 14:53:47,238 [salt             ][WARNING ] Stopping the Salt Minion
2015-04-13 14:53:47,238 [salt             ][WARNING ] Exiting on Ctrl-c
2015-04-13 14:56:55,151 [salt.utils       ][ERROR   ] DNS lookup of 'centos6.local' failed.
2015-04-13 14:56:55,152 [salt.minion      ][ERROR   ] Master hostname: 'centos6.local' not found. Retrying in 30 seconds
2015-04-13 14:57:02,577 [salt             ][WARNING ] Stopping the Salt Minion
2015-04-13 14:57:02,577 [salt             ][WARNING ] Exiting on Ctrl-c
2015-04-13 14:58:19,395 [salt             ][ERROR   ] Attempt to authenticate with the salt master failed
2015-04-13 15:00:30,593 [salt             ][ERROR   ] Attempt to authenticate with the salt master failed
2015-04-13 15:06:49,547 [salt             ][WARNING ] Stopping the Salt Minion
2015-04-13 15:06:49,547 [salt             ][WARNING ] Exiting on Ctrl-c
2015-04-13 15:07:22,462 [salt.utils       ][ERROR   ] DNS lookup of 'centos6' failed.
2015-04-13 15:07:22,463 [salt.minion      ][ERROR   ] Master hostname: 'centos6' not found. Retrying in 30 seconds
2015-04-13 15:07:40,972 [salt             ][WARNING ] Stopping the Salt Minion
2015-04-13 15:07:40,973 [salt             ][WARNING ] Exiting on Ctrl-c
2015-04-13 15:10:57,558 [salt.utils       ][ERROR   ] DNS lookup of 'centos6.local' failed.
2015-04-13 15:10:57,559 [salt.minion      ][ERROR   ] Master hostname: 'centos6.local' not found. Retrying in 30 seconds
2015-04-13 15:11:27,778 [salt.utils       ][ERROR   ] DNS lookup of 'centos6.local' failed.
2015-04-13 15:11:27,779 [salt.minion      ][ERROR   ] Master hostname: 'centos6.local' not found. Retrying in 30 seconds
2015-04-13 15:11:57,965 [salt.utils       ][ERROR   ] DNS lookup of 'centos6.local' failed.
2015-04-13 15:11:57,965 [salt.minion      ][ERROR   ] Master hostname: 'centos6.local' not found. Retrying in 30 seconds
2015-04-13 15:12:28,096 [salt.utils       ][ERROR   ] DNS lookup of 'centos6.local' failed.
2015-04-13 15:12:28,096 [salt.minion      ][ERROR   ] Master hostname: 'centos6.local' not found. Retrying in 30 seconds
2015-04-13 15:12:58,332 [salt.utils       ][ERROR   ] DNS lookup of 'centos6.local' failed.
2015-04-13 15:12:58,332 [salt.minion      ][ERROR   ] Master hostname: 'centos6.local' not found. Retrying in 30 seconds
2015-04-13 15:13:09,777 [salt             ][WARNING ] Stopping the Salt Minion
2015-04-13 15:13:09,778 [salt             ][WARNING ] Exiting on Ctrl-c
2015-04-13 15:14:13,306 [salt             ][WARNING ] Stopping the Salt Minion
2015-04-13 15:14:13,306 [salt             ][WARNING ] Exiting on Ctrl-c
2015-04-13 15:14:19,322 [salt             ][WARNING ] Stopping the Salt Minion
2015-04-13 15:14:19,323 [salt             ][WARNING ] Exiting on Ctrl-c
2015-04-13 15:14:25,666 [salt             ][WARNING ] Stopping the Salt Minion
2015-04-13 15:14:25,667 [salt             ][WARNING ] Exiting on Ctrl-c
2015-04-13 15:14:33,666 [salt             ][WARNING ] Stopping the Salt Minion
2015-04-13 15:14:33,667 [salt             ][WARNING ] Exiting on Ctrl-c
2015-04-13 15:15:37,766 [salt             ][ERROR   ] Attempt to authenticate with the salt master failed
2015-04-13 15:20:41,368 [salt             ][ERROR   ] Attempt to authenticate with the salt master failed
2015-04-13 16:08:34,524 [salt                                     ][ERROR   ] Attempt to authenticate with the salt master failed
2015-04-13 16:11:17,399 [salt                                     ][ERROR   ] Attempt to authenticate with the salt master failed
```
FROM 192.168.0.55
```
2015-04-13 16:54:38,619 [salt                                     ][ERROR   ] Attempt to authenticate with the salt master failed
2015-04-13 17:34:35,621 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:34:45,637 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:34:55,653 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:35:05,669 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:35:15,686 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:35:25,702 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:35:35,718 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:35:45,734 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:35:55,752 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:36:05,768 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:36:15,783 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:36:25,799 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:36:35,815 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:36:45,830 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:36:55,846 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:37:05,861 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:37:15,876 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:37:25,891 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:37:35,907 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:37:45,922 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:37:55,938 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:38:05,953 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:38:15,969 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:38:25,985 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:38:36,000 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:38:46,016 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:38:56,031 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:39:06,047 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:39:16,062 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:39:26,078 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:39:36,093 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:39:46,109 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:39:56,124 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:40:06,140 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:40:16,155 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:40:26,170 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:40:36,186 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:40:46,201 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:40:56,216 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:41:06,231 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:41:16,247 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:41:26,262 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:41:36,278 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:41:46,293 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:41:56,309 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:42:06,324 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:42:16,340 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:42:26,355 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:42:36,370 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:42:46,386 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:42:56,401 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:43:06,417 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:43:16,432 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:43:26,448 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:43:36,464 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:43:46,478 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:43:56,493 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:44:06,509 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:44:16,524 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:44:26,540 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:44:36,555 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:44:46,570 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:44:56,586 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:45:06,601 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:45:16,617 [salt.crypt                               ][ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2015-04-13 17:52:52,814 [salt.log.setup                           ][ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: string indices must be integers, not str
Traceback (most recent call last):
  File "/usr/bin/salt-minion", line 14, in <module>
    salt_minion()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 57, in salt_minion
    minion.start()
  File "/usr/lib/python2.6/site-packages/salt/__init__.py", line 262, in start
    self.prepare()
  File "/usr/lib/python2.6/site-packages/salt/__init__.py", line 241, in prepare
    self.minion = salt.minion.Minion(self.config)
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 604, in __init__
    opts['environment'],
  File "/usr/lib/python2.6/site-packages/salt/pillar/__init__.py", line 91, in compile_pillar
    ret_pillar = self.sreq.crypted_transfer_decode_dictentry(load, dictkey='pillar', tries=3, timeout=7200)
  File "/usr/lib/python2.6/site-packages/salt/transport/__init__.py", line 245, in crypted_transfer_decode_dictentry
    aes = key.private_decrypt(ret['key'], 4)
TypeError: string indices must be integers, not str
2015-04-14 10:00:49,384 [salt.loaded.int.module.cmdmod               ][ERROR   ] Command 'touch /temp/fichiertest' failed with return code: 1
2015-04-14 10:00:49,387 [salt.loaded.int.module.cmdmod               ][ERROR   ] output: touch: cannot touch `/temp/fichiertest': No such file or directory
2015-04-14 15:12:19,745 [salt.minion                                 ][WARNING ] The minion function caused an exception
2015-04-14 15:19:54,335 [salt.minion                                 ][WARNING ] The minion function caused an exception
2015-04-14 16:15:17,283 [salt             ][INFO    ] Setting up the Salt Minion "centos6"
2015-04-14 16:15:17,309 [salt.utils.process][DEBUG   ] Created pidfile: /var/run/salt-minion.pid
2015-04-14 16:15:17,309 [salt.config      ][DEBUG   ] Reading configuration from /etc/salt/minion
2015-04-14 16:15:17,620 [salt.loaded.int.grain.core][DEBUG   ] The `dmidecode` binary is not available on the system. GPU grains will not be available.
2015-04-14 16:15:17,706 [salt.minion      ][DEBUG   ] Attempting to authenticate with the Salt Master at 192.168.0.55
2015-04-14 16:15:17,708 [salt.crypt       ][DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
2015-04-14 16:15:18,305 [salt.crypt       ][DEBUG   ] Decrypting the current master AES key
2015-04-14 16:15:18,306 [salt.crypt       ][DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
2015-04-14 16:15:18,700 [salt.minion      ][INFO    ] Authentication with master at 192.168.0.55 successful!
2015-04-14 16:15:19,092 [salt.crypt       ][DEBUG   ] Decrypting the current master AES key
2015-04-14 16:15:19,093 [salt.crypt       ][DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
2015-04-14 16:15:19,512 [salt.crypt       ][DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
2015-04-14 16:15:19,711 [salt.config      ][DEBUG   ] Reading configuration from /etc/salt/minion
2015-04-14 16:15:19,984 [salt.loaded.int.grain.core][DEBUG   ] The `dmidecode` binary is not available on the system. GPU grains will not be available.
2015-04-14 16:15:20,156 [salt.cloud       ][DEBUG   ] Mako not available
2015-04-14 16:15:20,484 [salt.minion      ][INFO    ] Added mine.update to schedular
2015-04-14 16:15:20,485 [salt.utils.schedule][INFO    ] Added new job __mine_interval to scheduler
2015-04-14 16:15:20,485 [salt.minion      ][DEBUG   ] I am centos6 and I am not supposed to start any proxies. (Likely not a problem)
2015-04-14 16:15:20,486 [salt.minion      ][INFO    ] Minion is starting as user 'root'
2015-04-14 16:15:20,486 [salt.minion      ][DEBUG   ] Minion 'centos6' trying to tune in
2015-04-14 16:15:20,489 [salt.minion      ][DEBUG   ] Minion PUB socket URI: ipc:///var/run/salt/minion/minion_event_5d698e1076_pub.ipc
2015-04-14 16:15:20,489 [salt.minion      ][DEBUG   ] Minion PULL socket URI: ipc:///var/run/salt/minion/minion_event_5d698e1076_pull.ipc
2015-04-14 16:15:20,490 [salt.minion      ][INFO    ] Starting pub socket on ipc:///var/run/salt/minion/minion_event_5d698e1076_pub.ipc
2015-04-14 16:15:20,491 [salt.minion      ][INFO    ] Starting pull socket on ipc:///var/run/salt/minion/minion_event_5d698e1076_pull.ipc
2015-04-14 16:15:20,491 [salt.minion      ][DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (9313)
2015-04-14 16:15:20,491 [salt.minion      ][DEBUG   ] Setting zmq_reconnect_ivl to '9313ms'
2015-04-14 16:15:20,492 [salt.minion      ][DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
2015-04-14 16:15:20,885 [salt.crypt       ][DEBUG   ] Decrypting the current master AES key
2015-04-14 16:15:20,885 [salt.crypt       ][DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
2015-04-14 16:15:21,676 [salt.crypt       ][DEBUG   ] Decrypting the current master AES key
2015-04-14 16:15:21,676 [salt.crypt       ][DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
2015-04-14 16:15:22,073 [salt.minion      ][INFO    ] Minion is ready to receive requests!
2015-04-14 16:15:22,073 [salt.utils.schedule][INFO    ] Running scheduled job: __mine_interval
2015-04-14 16:15:22,073 [salt.utils.schedule][DEBUG   ] schedule: This job was scheduled with jid_include, adding to cache (jid_include defaults to True)
2015-04-14 16:15:22,074 [salt.utils.schedule][DEBUG   ] schedule: This job was scheduled with a max number of 2
2015-04-14 16:15:22,110 [salt.utils.schedule][DEBUG   ] schedule.handle_func: adding this job to the jobcache with data {'fun': 'mine.update', 'jid': '20150414161522083602', 'pid': 2022, 'id': 'centos6', 'schedule': '__mine_interval'}
2015-04-14 16:15:22,507 [salt.crypt       ][DEBUG   ] Decrypting the current master AES key
2015-04-14 16:15:22,508 [salt.crypt       ][DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
2015-04-14 16:15:22,903 [salt.crypt       ][DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
2015-04-14 16:15:23,495 [salt.crypt       ][DEBUG   ] Decrypting the current master AES key
2015-04-14 16:15:23,495 [salt.crypt       ][DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
2015-04-14 16:15:26,211 [salt             ][WARNING ] Stopping the Salt Minion
2015-04-14 16:15:26,212 [salt             ][WARNING ] Exiting on Ctrl-c
////////////////////////////////////
```
I've been looking thru the web for 2 days now and i don't get anything that could help me. 
I've to say i'm french. I do understand english and spoke it quit well but sometimes, this kind of problem is hard to resolve in english !!!
I've others issues with the states but one at a time.
Thanks a lot to everyone who would spend a bit of time on my problems and help me to resolve it and go further in the use of Salt.
best regards,

**Comment by rallytime** [comment]
Hi @moxxbiales and welcome to salt!

Can you tell us how you installed salt? (For example, system packages or the bootstrap script?)

Can you also post the output of `salt-call --versions-report` for each of your minions and then `salt --versions-report` for your master?

When you changed the minion config files for each of your minions, did you restart the minion's process? After you restarted the minion processes, did you run `salt-key` on the master and accept the minion keys?

**Comment by moxxbiales** [comment]
Hi,
I worked out my problems. It was linked to a network configuration problem...
thanks anyway for your concern, 
best regards,

Jean-François MONI
06.11.09.35.91
jfmoni@free.fr
http://moxxbiales.free.fr/tsgeri

**Comment by rallytime** [comment]
No problem! Glad you got it all figured out. :)

**Comment by kkraj** [comment]
@moxxbiales , What was the issue; I am facing same issue, not able to figure it out. Thanks
