### ISSUE TITLE
multiprocessing fails when listing nodes on multiple vmware providers

### ISSUE THREAD

**Issue by nmadhok** [saltstack/salt#22684]
listing nodes individually on each vcenter works but if i do ``salt-cloud -Q`` which should really be the aggregate of listing nodes individually, I get the following traceback after which my console hangs:

```
root@nitin-salt-develop:~$ salt-cloud -Q
[INFO    ] salt-cloud starting
Process PoolWorker-1:
Traceback (most recent call last):
 File "/usr/lib64/python2.6/multiprocessing/process.py", line 232, in _bootstrap
   self.run()
 File "/usr/lib64/python2.6/multiprocessing/process.py", line 88, in run
   self._target(*self._args, **self._kwargs)
 File "/usr/lib64/python2.6/multiprocessing/pool.py", line 71, in worker
   put((job, i, result))
 File "/usr/lib64/python2.6/multiprocessing/queues.py", line 366, in put
   return send(obj)
PicklingError: Can't pickle <class 'pyVmomi.VmomiSupport.vim.VirtualMachine.PowerState'>: attribute lookup pyVmomi.VmomiSupport.vim.VirtualMachine.PowerState failed
Process PoolWorker-2:
Traceback (most recent call last):
 File "/usr/lib64/python2.6/multiprocessing/process.py", line 232, in _bootstrap
   self.run()
 File "/usr/lib64/python2.6/multiprocessing/process.py", line 88, in run
   self._target(*self._args, **self._kwargs)
 File "/usr/lib64/python2.6/multiprocessing/pool.py", line 71, in worker
   put((job, i, result))
 File "/usr/lib64/python2.6/multiprocessing/queues.py", line 366, in put
   return send(obj)
PicklingError: Can't pickle <class 'pyVmomi.VmomiSupport.vim.VirtualMachine.PowerState'>: attribute lookup pyVmomi.VmomiSupport.vim.VirtualMachine.PowerState failed
```

@techhat @s0undt3ch 

Running latest salt and salt-cloud from develop

**Comment by nmadhok** [comment]
Fixed this in one of the PR's I submitted which has now been merged. Closing this.
