### ISSUE TITLE
salt-cloud fails on KeyError when given a nonexistant action

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#22699]
When trying out salt-cloud -a action I tried : 

```
# salt-cloud -m cloud-california.map -a ssh_interface
[INFO    ] salt-cloud starting
[INFO    ] Applying map from 'cloud-california.map'.
[INFO    ] Starting new HTTPS connection (1): ec2.us-west-1.amazonaws.com
[INFO    ] Starting new HTTPS connection (1): ec2.eu-west-1.amazonaws.com
[INFO    ] Starting new HTTPS connection (1): ec2.us-west-1.amazonaws.com
[INFO    ] Starting new HTTPS connection (1): ec2.eu-west-1.amazonaws.com
[INFO    ] Starting new HTTPS connection (1): ec2.eu-west-1.amazonaws.com
[INFO    ] Starting new HTTPS connection (1): ec2.us-west-1.amazonaws.com
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
KeyError: 'ssh_interface'
Traceback (most recent call last):
  File "/usr/bin/salt-cloud", line 10, in <module>
    salt_cloud()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 210, in salt_cloud
    client.run()
  File "/usr/lib/python2.6/site-packages/salt/cloud/cli.py", line 175, in run
    names = mapper.get_vmnames_by_action(self.options.action)
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 1569, in get_vmnames_by_action
    matching_states[action]
KeyError: 'ssh_interface'
Traceback (most recent call last):
  File "/usr/bin/salt-cloud", line 10, in <module>
    salt_cloud()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 210, in salt_cloud
    client.run()
  File "/usr/lib/python2.6/site-packages/salt/cloud/cli.py", line 175, in run
    names = mapper.get_vmnames_by_action(self.options.action)
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 1569, in get_vmnames_by_action
    matching_states[action]
KeyError: 'ssh_interface'
```

This is related to #22698

**Comment by terminalmage** [comment]
Thanks for the report, this should be an easy fix.

**Comment by terminalmage** [comment]
Could you please let us know what version of salt-cloud you are running?

**Comment by arthurlogilab** [comment]
```
# salt-cloud --versions-report
            Salt: 2014.7.1
          Python: 2.6.6 (r266:84292, Nov 22 2013, 12:16:22)
          Jinja2: 2.2.1
        M2Crypto: 0.20.2
  msgpack-python: 0.4.4
    msgpack-pure: Not Installed
        pycrypto: 2.0.1
         libnacl: Not Installed
          PyYAML: 3.10
           ioflo: Not Installed
           PyZMQ: 14.3.1
            RAET: Not Installed
             ZMQ: 3.2.5
            Mako: Not Installed
 Apache Libcloud: Not Installed

```

**Comment by techhat** [comment]
@arthurlogilab, actions are not currently supported with a map file.

**Comment by rallytime** [comment]
@arthurlogilab Thanks for the report. As @techhat said, this isn't currently supported. However, to be fair, there shouldn't be a stack trace there if you DO try to do this. We should have a more helpful error message saying that actions with a map file isn't presently supported, at least until this functionality is implemented.

**Comment by rallytime** [comment]
Some actions *are* supported when deploying a map file, but they're limited to the "global" actions such as `start`, `stop`, and `reboot`. With fix in the PR above, the system will print the error and exit if given an invalid action like so:
```
# salt-cloud -m ~/mapfile -a ssh_interfaces
[INFO    ] salt-cloud starting
[INFO    ] Applying map from '/root/mapfile'.
[INFO    ] action = ssh_interfaces
[ERROR   ] The use of 'ssh_interfaces' as an action is not supported in this context. Only 'start', 'stop', and 'reboot' are supported options.
```
