### ISSUE TITLE
salt-master says: "This master address: 'salt' was previously resolvable but now fails to resolve!"

### ISSUE THREAD

**Issue by hvnsweeting** [saltstack/salt#22742]
I ran a salt-master with -ldebug foreground.

It works normally, until I run 

``salt-run state.orch orchestration.es -ldebug``

and wait, this is my orchestration.es

````
create_es_vm:
  salt.function:
    - tgt: '*master*'
    - name: cmd.run
    - arg:
      - salt-cloud --profile ci-minion es7

es_highstate:
  salt.state:
    - tgt: 'es7'
    - highstate: True
````

After a while, the log appeared 

> [ERROR   ] This master address: 'salt' was previously resolvable but now fails to resolve! The previously resolved ip addr will continue to be used
[WARNING ] SaltClientError:
[INFO    ] Clear payload received with command _auth

And as I can debug, it's the PID of which created the log is a subprocess of salt-master:

````
[WARNING ]  salt PID: 21989 PPID: 21973 

ps axu | grep maste[r]
root     21973  5.0  2.6 298468 27088 pts/4    Sl+  11:31   0:07 /usr/bin/python /usr/bin/salt-master -ldebug
root     21978  3.7  4.1 357208 41740 pts/4    Sl+  11:31   0:05 /usr/bin/python /usr/bin/salt-master -ldebug
root     21982  0.0  2.2 232932 23104 pts/4    Sl+  11:31   0:00 /usr/bin/python /usr/bin/salt-master -ldebug
root     21983  0.0  2.3 233364 23700 pts/4    Sl+  11:31   0:00 /usr/bin/python /usr/bin/salt-master -ldebug
root     21988  0.3  4.5 836244 46396 pts/4    Sl+  11:31   0:00 /usr/bin/python /usr/bin/salt-master -ldebug
root     21989  0.4  4.2 836284 43644 pts/4    Sl+  11:31   0:00 /usr/bin/python /usr/bin/salt-master -ldebug
````

My salt version:

````
 salt --versions-report
           Salt: 2014.1.10
         Python: 2.7.3 (default, Dec 18 2014, 19:10:20)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.4.1
         PyYAML: 3.11
          PyZMQ: 13.0.0
            ZMQ: 3.2.2
~ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.5 LTS
Release:        12.04
Codename:       precise
````

**Comment by hvnsweeting** [comment]
This caused by 'mine' module used in pillar, called by salt-master state runner, this is stackstrace:

````
['  File "/usr/bin/salt-master", line 10, in <module
>\n    salt_master()\n', '  File "/usr/lib/pymodules/python2.7/salt/scripts.py", line 25, in salt_mast
er\n    master.start()\n', '  File "/usr/lib/pymodules/python2.7/salt/__init__.py", line 123, in start
\n    self.master.start()\n', '  File "/usr/lib/pymodules/python2.7/salt/master.py", line 487, in star
t\n    reqserv.run()\n', '  File "/usr/lib/pymodules/python2.7/salt/master.py", line 684, in run\n
self.__bind()\n', '  File "/usr/lib/pymodules/python2.7/salt/master.py", line 624, in __bind\n    proc
.start()\n', '  File "/usr/lib/python2.7/multiprocessing/process.py", line 130, in start\n    self._po
pen = Popen(self)\n', '  File "/usr/lib/python2.7/multiprocessing/forking.py", line 125, in __init__\n
    code = process_obj._bootstrap()\n', '  File "/usr/lib/python2.7/multiprocessing/process.py", line
258, in _bootstrap\n    self.run()\n', '  File "/usr/lib/pymodules/python2.7/salt/master.py", line 834
, in run\n    self.__bind()\n', '  File "/usr/lib/pymodules/python2.7/salt/master.py", line 739, in __
bind\n    ret = self.serial.dumps(self._handle_payload(payload))\n', '  File "/usr/lib/pymodules/pytho
n2.7/salt/master.py", line 763, in _handle_payload\n    \'clear\': self._handle_clear}[key](load)\n',
'  File "/usr/lib/pymodules/python2.7/salt/master.py", line 796, in _handle_aes\n    return self.aes_f
uncs.run_func(data[\'cmd\'], data)\n', '  File "/usr/lib/pymodules/python2.7/salt/master.py", line 170
1, in run_func\n    ret = getattr(self, func)(load)\n', '  File "/usr/lib/pymodules/python2.7/salt/mas
ter.py", line 1298, in _pillar\n    data = pillar.compile_pillar()\n', '  File "/usr/lib/pymodules/pyt
hon2.7/salt/pillar/__init__.py", line 505, in compile_pillar\n    pillar, errors = self.render_pillar(
matches)\n', '  File "/usr/lib/pymodules/python2.7/salt/pillar/__init__.py", line 422, in render_pilla
r\n    pstate, mods, err = self.render_pstate(sls, saltenv, mods)\n', '  File "/usr/lib/pymodules/pyth
on2.7/salt/pillar/__init__.py", line 401, in render_pstate\n    defaults\n', '  File "/usr/lib/pymodul
es/python2.7/salt/pillar/__init__.py", line 367, in render_pstate\n    fn_, self.rend, self.opts[\'ren
derer\'], saltenv, sls, **defaults)\n', '  File "/usr/lib/pymodules/python2.7/salt/template.py", line
84, in compile_template\n    ret = render(input_data, saltenv, sls, **render_kwargs)\n', '  File "/usr
/lib/pymodules/python2.7/salt/renderers/jinja.py", line 39, in render\n    **kws)\n', '  File "/usr/li
b/pymodules/python2.7/salt/utils/templates.py", line 85, in render_tmpl\n    output = render_str(tmpls
tr, context, tmplpath)\n', '  File "/usr/lib/pymodules/python2.7/salt/utils/templates.py", line 263, i
n render_jinja_tmpl\n    output = jinja_env.from_string(tmplstr).render(**unicode_context)\n', '  File
 "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 891, in render\n    return concat(self
.root_render_func(self.new_context(vars)))\n', '  File "<template>", line 8, in root\n', '  File "/usr
/lib/python2.7/dist-packages/jinja2/runtime.py", line 180, in call\n    return __obj(*args, **kwargs)\
n', '  File "/usr/lib/pymodules/python2.7/salt/modules/mine.py", line 182, in get\n    auth = _auth()\
n', '  File "/usr/lib/pymodules/python2.7/salt/modules/mine.py", line 24, in _auth\n    __context__[\'
auth\'] = salt.crypt.SAuth(__opts__)\n', '  File "/usr/lib/pymodules/python2.7/salt/crypt.py", line 52
0, in __init__\n    self.crypticle = self.__authenticate()\n', '  File "/usr/lib/pymodules/python2.7/s
alt/crypt.py", line 532, in __authenticate\n    self.opts.get(\'_safe_auth\', True)\n', '  File "/usr/
lib/pymodules/python2.7/salt/crypt.py", line 342, in sign_in\n
````

**Comment by rallytime** [comment]
@hvnsweeting We're not making fixes to, or maintaining releases, on the 2014.1 branch. Can you upgrade to a newer release and see if you're still hitting this issue?

**Comment by hvnsweeting** [comment]
On 2014.7.4, I got this error:

````
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 280, in
render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 894, in re
nder
    return self.environment.handle_exception(exc_info, True)
  File "<template>", line 1, in top-level template code
  File "/usr/lib/python2.7/dist-packages/salt/modules/mine.py", line 222, in get
    load['tok'] = _auth().gen_token('salt')
  File "/usr/lib/python2.7/dist-packages/salt/modules/mine.py", line 27, in _aut
h
    __context__['auth'] = salt.crypt.SAuth(__opts__)
  File "/usr/lib/python2.7/dist-packages/salt/crypt.py", line 810, in __init__
    self.crypticle = self.__authenticate()
  File "/usr/lib/python2.7/dist-packages/salt/crypt.py", line 831, in __authenti
cate
    self.opts.get('auth_tries', 1)
  File "/usr/lib/python2.7/dist-packages/salt/crypt.py", line 636, in sign_in
    self.opts['master_uri'],
KeyError: 'master_uri'
````

and salt.mine stop not work in pillar (but mine still work normally in another use such as salt '*' mine.get .

**Comment by rallytime** [comment]
Thanks for the update.

**Comment by cachedout** [comment]
@hvnsweeting Give the fix in #23344 a try, please.

**Comment by cachedout** [comment]
Given that we have a fix in place and no reply, I'm going to go ahead and close this. If it needs to be re-opened for any reason, please leave a comment here and we'll happily do so. Thanks all!

**Comment by hvnsweeting** [comment]
I confirm this fixed the error. But after all, I realized that it's impossible to use mine in pillar, because mine is something that can only be accessed by salt-minion, since pillar is rendered by salt-master, isn't it?

It is weird because mine is a thing that belong to master, but cannot be access by master?
Should that be a new feature? or did I miss something?
