### ISSUE TITLE
saltutil.sync_modules is not working as expected inside state

### ISSUE THREAD

**Issue by mostafahussein** [saltstack/salt#22744]
I have a state where i use custom modules.
first part of the state for syncing the modules before using it (to make sure its available when calling it) but that is not happening when i run the state for the first time, the current solution is to run the state twice (which shouldn't be happen), however when i run the state for the first time i get the following results:

```
     ID: update_modules
    Function: module.run
        Name: saltutil.sync_modules
      Result: True
     Comment: Module function saltutil.sync_modules executed
     Started: 13:50:24.210889
    Duration: 5286.219 ms
     Changes:   
              ----------
              ret:
                  - modules.custom_module1
```

and the errors are:

```
Unable to manage file: Jinja variable 'dict' object has no attribute 'custom_module1.function1'

Unable to manage file: Jinja variable 'dict' object has no attribute 'custom_module1.function2'
```

when i run the same state file for the second time i got no errors , so why it happens at the first place when my modules are synced correctly ?

**Comment by Code-Vortex** [comment]
it also happens when i use pip module to use an updated version of some package. the package is updated correctly but still act as it was an old package (only when running a state for the first time)

until now i have to options either running the state twice or running 
`salt "*" sync_modules` and `salt "*" pip.install <package_name> upgrade=True`

**Comment by terminalmage** [comment]
Can you please provide a clearer example? I feel like we only have part of what we need to investigate. A example of the SLS you are using, and how to trigger this error, would be very helpful. Thanks!

**Comment by Code-Vortex** [comment]
assume your psutil version is 0.6 or any version which is OLD and doesn't contain `net_connections` functions and you have a script which uses the latest version of psutil which is 2.2.1 , and also there is a custom module which you created called `custom_module1`

lets say at the top lines of your SLS file contains the following:

```yaml
update_psutil:
  module.run:
    - name: pip.install
    - pkgs: psutil
    - upgrades: True

update_modules:
  module.run:
    - name: saltutil.sync_modules
```
then beneath the lines above if you have

```yaml
call_my_custom_module:
  module.run:
    - name: custom_module1.function1
```

there are two errors in here:

1- when you call your state for the first time after syncing modules correctly when it comes to this part   `call_my_custom_module` it will raise an error telling you 
```
Unable to manage file: Jinja variable 'dict' object has no attribute 'custom_module1.function1'
```
in this case you will have to run the state again. i will try to create a small example and will send it using a gist if what i have explained is not clear and also to be able to regenerate the problem again !

2- after updating the package through pip, salt-minion needs to be restarted in order to refresh `/usr/lib/python<version>/` as i am guessing

**Comment by terminalmage** [comment]
You mentioned a script, but your example doesn't reference any script. And the error you posted comes from a file state, not from a module.run state.

I'm afraid I don't understand the issue. We'll need more detailed information.

**Comment by Code-Vortex** [comment]
@terminalmage here is the full state and my custom module which i was working on and facing issues , you can check [this gist](https://gist.github.com/Code-Vortex/559b429d71d39ee48851) , however my module needs some refactoring and more testing but it works as a first version :D

let me know if its not clear ! you may create something similar in order to test it because as you see it requires some services like NGINX and WHM.

**Comment by terminalmage** [comment]
Thanks, I think I have a better idea of the issue now. Can you please let us know what version of Salt you are running?

**Comment by Code-Vortex** [comment]
```
$ salt --versions
           Salt: 2014.7.1
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.4.4
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed

```

**Comment by terminalmage** [comment]
I don't know if there is a way to do this in a single pass. The issue here is that jinja templates are evaluated before the SLS is executed. Therefore, ``saltutil.sync_modules`` hasn't had a chance to run. There may be a way to use our orchestration runner to do this. I'll see what I can find.

**Comment by Code-Vortex** [comment]
Well , when running the state, result of `update_psutil` and `update_modules` comes first, this means they have been evaluated first , am i right ?!  
and I have tried to move them to a separate SLS and put an include at the first line but no luck

**Comment by terminalmage** [comment]
@Code-Vortex Sorry, I was misreading the gist and thought the template was within the SLS file. I did some investigation and it turns out that the SLS files available functions are not reloaded after every state for performance reasons. This is actually documented in the states documentation (see [here](http://docs.saltstack.com/en/latest/ref/states/index.html#reloading-modules)).

However, it is a natural expectation that if you're running a saltutil.sync_modules, your custom execution modules should be available. So, I've added some documentation to the saltutil module docs which should clear this up. Here's the pull request: https://github.com/saltstack/salt/pull/22763

**Comment by terminalmage** [comment]
So, based on that docs link I posted above, making the following modification to your module.run state should work:

```yaml
update_modules:
  module.run:
    - name: saltutil.sync_modules
    - reload_modules: True
```

**Comment by Code-Vortex** [comment]
Thanks @terminalmage for following up, I have changed the way I use to update `psutil` using the following:

```yaml
update_psutil:
  cmd.run:
    - name: pip install --upgrade psutil
    - reload_modules: True
```
the above lines are the top lines in my SLS file, but when i run the whole state i still getting errors about some missing functions in this case i have to restart the minion in order to make the state pass.
here is the results:

```
----------
          ID: update_psutil
    Function: cmd.run
        Name: pip install --upgrade psutil
      Result: True
     Comment: Command "pip install --upgrade psutil" run
     Started: 12:15:22.843199
    Duration: 920.608 ms
     Changes:   
              ----------
              pid:
                  193515
              retcode:
                  0
              stderr:
                  
              stdout:
                  Requirement already up-to-date: psutil in /usr/lib64/python2.6/site-packages
                  Cleaning up...
----------
          ID: default_vhost
    Function: file.managed
        Name: /usr/local/nginx/vhosts/default_page.conf
      Result: False
     Comment: Unable to manage file: Jinja error: 'module' object has no attribute 'net_connections'
              Traceback (most recent call last):
                File "/usr/lib/python2.6/site-packages/salt/utils/templates.py", line 286, in render_jinja_tmpl
                  output = template.render(**unicode_context)
                File "/usr/lib64/python2.6/site-packages/jinja2/environment.py", line 669, in render
                  return self.environment.handle_exception(exc_info, True)
                File "<template>", line 2, in top-level template code
                File "/var/cache/salt/minion/extmods/modules/conn.py", line 8, in laddr
                  for connection in psutil.net_connections(kind="tcp4"):
              AttributeError: 'module' object has no attribute 'net_connections'
              
              ; line 2
              
              ---
              server {
                  listen {{ salt['conn.laddr']('nginx') }};    <======================
                  server_name {{ salt['grains.get']('fqdn') }}; # vhost domain name
                  root /usr/local/nginx/html/; # home directory for site files
                  access_log logs/default_page-access_log; # access log path relative to nginx main dir
                  error_log logs/default_page-error_log warn; # error log path relative to nginx main dir
              }
              [...]
              ---
     Started: 12:15:23.763917
    Duration: 303.54 ms
     Changes:   
----------
          ID: restart_nginx
    Function: service.running
        Name: nginx
      Result: False
     Comment: One or more requisite failed: {'nginx.nginx-default-page.default_vhost': 'Unable to manage file: Jinja error: \'module\' object has no attribute \'net_connections\'\nTraceback (most recent call last):\n  File "/usr/lib/python2.6/site-packages/salt/utils/templates.py", line 286, in render_jinja_tmpl\n    output = template.render(**unicode_context)\n  File "/usr/lib64/python2.6/site-packages/jinja2/environment.py", line 669, in render\n    return self.environment.handle_exception(exc_info, True)\n  File "<template>", line 2, in top-level template code\n  File "/var/cache/salt/minion/extmods/modules/conn.py", line 8, in laddr\n    for connection in psutil.net_connections(kind="tcp4"):\nAttributeError: \'module\' object has no attribute \'net_connections\'\n\n; line 2\n\n---\nserver {\n    listen {{ salt[\'conn.laddr\'](\'nginx\') }};    <======================\n    server_name {{ salt[\'grains.get\'](\'fqdn\') }}; # vhost domain name\n    root /usr/local/nginx/html/; # home directory for site files\n    access_log logs/default_page-access_log; # access log path relative to nginx main dir\n    error_log logs/default_page-error_log warn; # error log path relative to nginx main dir\n}\n[...]\n---'}
     Started: 
    Duration: 
     Changes:   
----------
          ID: modify_nginx_chkserv
    Function: file.managed
        Name: /etc/chkserv.d/nginx
      Result: False
     Comment: Unable to manage file: Jinja error: 'module' object has no attribute 'net_connections'
              Traceback (most recent call last):
                File "/usr/lib/python2.6/site-packages/salt/utils/templates.py", line 286, in render_jinja_tmpl
                  output = template.render(**unicode_context)
                File "/usr/lib64/python2.6/site-packages/jinja2/environment.py", line 669, in render
                  return self.environment.handle_exception(exc_info, True)
                File "<template>", line 1, in top-level template code
                File "/var/cache/salt/minion/extmods/modules/conn.py", line 23, in port
                  for connection in psutil.net_connections(kind="tcp4"):
              AttributeError: 'module' object has no attribute 'net_connections'
              
              ; line 1
              
              ---
              service[nginx]={{ salt['conn.port']('nginx') }},GET {{ salt['grains.get']('fqdn') }}/ HTTP/1.0,HTTP/1..,killall -TERM nginx;sleep 2;killall -9 nginx;/etc/rc.d/init.d/nginx stop;/etc/rc.d/init.d/nginx restart    <======================
              
              Traceback (most recent call last):
                File "/usr/lib/python2.6/site-packages/salt/utils/templates.py", line 286, in render_jinja_tmpl
                  output = template.render(**unicode_context)
                File "/usr/lib64/python2.6/site-packages/jinja2/environment.py", line 669, in render
              [...]
              ---
     Started: 12:15:24.067702
    Duration: 50.938 ms
     Changes:   
----------
          ID: restart_chkservd
    Function: cmd.run
        Name: /scripts/restartsrv_chkservd
      Result: True
     Comment: Command "/scripts/restartsrv_chkservd" run
     Started: 12:15:24.118708
    Duration: 1218.475 ms
     Changes:   
              ----------
              pid:
                  193534
              retcode:
                  0
              stderr:
                  
              stdout:
                  

Summary
------------
Succeeded: 2 (changed=2)
Failed:    3
------------
Total states run:     5
```
don't forget that `psutil` package is used inside my custom module. I think its a general bug in salt itself maybe we need to have something equivalent to restarting the minion inside the state which will reload all the files again to read any new modifications like changing permissions or updating a package like my case and also syncing module. i am afraid that `reload_modules` which you have added recently wont solve the issue as the current `reload_modules` which available for `cmd` state module didn't solve the update python package issue

**Comment by terminalmage** [comment]
You did not make the recommended change. Please move the ``reload_modules`` to your call to your module.run state as I recommended.

**Comment by Code-Vortex** [comment]
if you mean using this

```yaml
update_psutil:
  module.run:
    - name: pip.install
    - pkgs: psutil
    - upgrades: True
    - reload_modules: True
```

instead of the previous `cmd.run` state. i tried it but it didn't work either

**Comment by terminalmage** [comment]
Please see [this comment](https://github.com/saltstack/salt/issues/22744#issuecomment-93873395). The ``reload_modules`` should be added to the module.run call to saltutil.sync_modules.

**Comment by Code-Vortex** [comment]
still having same issue :(, i guess it doesn't respect `reload_modules`

```yaml
update_psutil:
  module.run:
    - name: pip.install
    - pkgs: psutil
    - upgrade: True

update_modules:
  module.run:
    - name: saltutil.sync_modules
    - reload_modules: True   
```

**Comment by terminalmage** [comment]
Works for me:

```
root v(saltdev) ~erik/saltdev                                               [11:20:12]
(⌐■_■) # salt-run fileserver.file_list
- _modules/foo.py
- foo.txt
- test.sls
root v(saltdev) ~erik/saltdev                                               [11:20:14]
(⌐■_■) # cat srv/salt/base/test.sls
saltutil.sync_all:
  module.run:
    - refresh: True
    - reload_modules: True

/tmp/foo.txt:
  file.managed:
    - source: salt://foo.txt
    - template: jinja
root v(saltdev) ~erik/saltdev                                               [11:20:28]
(⌐■_■) # cat srv/salt/base/foo.txt
{{ salt['foo.bar']() }}
root v(saltdev) ~erik/saltdev                                               [11:20:34]
(⌐■_■) # cat srv/salt/base/_modules/foo.py
def bar():
    return 'Hello world!'
root v(saltdev) ~erik/saltdev                                               [11:20:51]
(⌐■_■) # salt saltmine foo.bar
saltmine:
    'foo.bar' is not available.
root v(saltdev) ~erik/saltdev                                               [11:21:09]
(⌐■_■) # salt saltmine state.sls test
saltmine:
----------
          ID: saltutil.sync_all
    Function: module.run
      Result: True
     Comment: Module function saltutil.sync_all executed
     Started: 11:21:51.708936
    Duration: 743.843 ms
     Changes:
              ----------
              ret:
                  ----------
                  grains:
                  modules:
                      - modules.foo
                  outputters:
                  renderers:
                  returners:
                  states:
                  utils:
----------
          ID: /tmp/foo.txt
    Function: file.managed
      Result: True
     Comment: File /tmp/foo.txt updated
     Started: 11:21:52.453145
    Duration: 36.617 ms
     Changes:
              ----------
              diff:
                  New file
              mode:
                  0644

Summary
------------
Succeeded: 2 (changed=2)
Failed:    0
------------
Total states run:     2
root v(saltdev) ~erik/saltdev                                               [11:21:52]
(⌐■_■) # cat /tmp/foo.txt
Hello world!
root v(saltdev) ~erik/saltdev                                               [11:22:00]
(⌐■_■) # salt saltmine foo.bar
saltmine:
    Hello world!
root v(saltdev) ~erik/saltdev                                               [11:22:05]
(⌐■_■) # salt saltmine test.versions_report
saltmine:
               Salt: 2014.7.1
             Python: 2.7.9 (default, Dec 11 2014, 04:42:00)
             Jinja2: 2.7.3
           M2Crypto: 0.21.1
     msgpack-python: 0.4.2
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
            libnacl: 1.4.0
             PyYAML: 3.11
              ioflo: 1.1.7
              PyZMQ: 13.1.0
               RAET: 0.5.2
                ZMQ: 3.2.2
               Mako: 1.0.1
```

**Comment by Code-Vortex** [comment]
@terminalmage , I have found something but still investigating it to make sure of what i am gonna tell you.

first if i made salt-call i dont have any issues (until now), if i made salt 'minion' from the master i face issues

i have modified `saltutil.sync_modules` to `saltutil.sync_all` in order to syncing grains as well to update this path `/usr/lib/python2.6/site-packages` at the minion grains.

i logged into minion and then typing command `salt-minion -l debug` then from the salt master typing this command salt 'minion' state.sls foo.bar

the result is : issues appears after running the state. BUT in the minion logs everything is done as expected.

for example:

salt-minion -l debug shows the following:

```
[INFO    ] Running state [/etc/chkserv.d/nginx] at time 00:18:28.942291
[INFO    ] Executing state file.managed for /etc/chkserv.d/nginx
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://nginx/nginx-default-page/chkserv.nginx'
[DEBUG   ] Jinja search path: ['/var/cache/salt/minion/files/base']
[INFO    ] File changed:
---  
+++  
@@ -1,1 +1,1 @@
-service[nginx]=80,GET / HTTP/1.0,HTTP/1..,killall -TERM nginx;sleep 2;killall -9 nginx;/etc/rc.d/init.d/nginx stop;/etc/rc.d/init.d/nginx restart
+service[nginx]=80,GET server.4eversms.net/ HTTP/1.0,HTTP/1..,killall -TERM nginx;sleep 2;killall -9 nginx;/etc/rc.d/init.d/nginx stop;/etc/rc.d/init.d/nginx restart

[INFO    ] Completed state [/etc/chkserv.d/nginx] at time 00:18:29.040668

```

but in salt master i see this:

```
----------
          ID: modify_nginx_chkserv
    Function: file.managed
        Name: /etc/chkserv.d/nginx
      Result: False
     Comment: Unable to manage file: Jinja error: 'module' object has no attribute 'net_connections'
              Traceback (most recent call last):
                File "/usr/lib/python2.6/site-packages/salt/utils/templates.py", line 286, in render_jinja_tmpl
                  output = template.render(**unicode_context)
                File "/usr/lib64/python2.6/site-packages/jinja2/environment.py", line 669, in render
                  return self.environment.handle_exception(exc_info, True)
                File "<template>", line 1, in top-level template code
                File "/var/cache/salt/minion/extmods/modules/conn.py", line 23, in port
                  for connection in psutil.net_connections(kind="tcp4"):
              AttributeError: 'module' object has no attribute 'net_connections'
              
              ; line 1
              
              ---
              service[nginx]={{ salt['conn.port']('nginx') }},GET {{ salt['grains.get']('fqdn') }}/ HTTP/1.0,HTTP/1..,killall -TERM nginx;sleep 2;killall -9 nginx;/etc/rc.d/init.d/nginx stop;/etc/rc.d/init.d/nginx restart    <======================
              
              Traceback (most recent call last):
                File "/usr/lib/python2.6/site-packages/salt/utils/templates.py", line 286, in render_jinja_tmpl
                  output = template.render(**unicode_context)
                File "/usr/lib64/python2.6/site-packages/jinja2/environment.py", line 669, in render
              [...]
              ---
     Started: 00:18:28.456927
    Duration: 55.405 ms
     Changes:
```
what do you think ?

I will try again on more minions if i found something instead of this i will keep you updated.

**Comment by gchp** [comment]
I'm seeing the exact same issue. Running from the command line works fine, but from inside a state, not so much.
