### ISSUE TITLE
salt-cloud: there was a profile error: 'str' object has no attribute 'copy'

### ISSUE THREAD

**Issue by masterkorp** [saltstack/salt#22749]
Hello everyone.

I am having trouble using salt-cloud.

```
salt-cloud -p aws-micro test
[INFO    ] salt-cloud starting
[INFO    ] Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
[ERROR   ] There was a profile error: 'str' object has no attribute 'copy'
```
My ``/etc/cloud/providers.d/providers.conf`` file
```yaml
my-aws:
  minion:
   master:123.456.789.123
  ssh_interface: private_ips

  id: 'dsadsadsa'
  key: 'dsdsadsada'

  private_key: /etc/salt/cloud.providers.d/aws-key.pem
  keyname: salt-cloud
  securitygroup: Local Network

  ssh_username: ubuntu

  location: us-east-1
  
  provider: ec2

  del_all_vols_on_destroy: True
  rename_on_destroy: True
```

My ``/etc/salt/cloud.profiles.d/profiles.conf`` file.
```yaml
aws-micro:
  provider: my-aws
  image: ami-d05e75b8
  size: t1.micro
  ssh_username:
    - ubuntu
    - ec2-user
```

Version of salt:
```
root@salt-master:/etc/salt# salt --version
salt 2014.7.2 (Helium)
```

But --versions-report does not work (for some reason)
```
root@salt-master:/etc/salt# salt --versions-report
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 241, in salt_main
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/__init__.py", line 45, in run
    self.parse_args()
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 126, in parse_args
    self.print_versions_report()
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 193, in print_versions_report
    print('\n'.join(version.versions_report()), file=file)
  File "/usr/lib/python2.7/dist-packages/salt/version.py", line 542, in versions_report
    libs = list(versions_information(include_salt_cloud=include_salt_cloud))
  File "/usr/lib/python2.7/dist-packages/salt/version.py", line 527, in versions_information
    imp = __import__(imp)
  File "/usr/local/lib/python2.7/dist-packages/libnacl/__init__.py", line 75, in <module>
    nacl = _get_nacl()
  File "/usr/local/lib/python2.7/dist-packages/libnacl/__init__.py", line 73, in _get_nacl
    raise OSError(msg)
OSError: Could not locate nacl lib, searched for libsodium.so, libsodium.so.13, libsodium.so.10, libsodium.so.5, libsodium.so.4,  and tweetnacl.so
```

**Comment by masterkorp** [comment]
I shall add that ``salt-cloud -Q works``

**Comment by masterkorp** [comment]
Also, from the salt-cloud manpage:
```
       --list-profiles
              New in version 2014.7.0.

              Display a list of configured profiles. Pass in a cloud provider to view the provider's associated profiles, such as digital_ocean, or
              pass in all to list all the configured profiles.
```

But salt-cloud complains no such options exists:
```
root@salt-master:/etc/salt# salt-cloud --list-profiles
Usage: salt-cloud

salt-cloud: error: no such option: --list-profiles
```

**Comment by masterkorp** [comment]
Here is the debug output:

```
root@salt-master:/etc/salt# salt-cloud -p aws-micro test -l debug 
[DEBUG   ] Reading configuration from /etc/salt/cloud
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/_defaults.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/_defaults.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/reactor.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/reactor.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt-master.in.bitreserve.org
[DEBUG   ] Missing configuration file: /etc/salt/cloud.providers
[DEBUG   ] Including configuration from '/etc/salt/cloud.providers.d/providers.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers.d/providers.conf
[DEBUG   ] Missing configuration file: /etc/salt/cloud.profiles
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/profiles.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/profiles.conf
[DEBUG   ] Configuration file path: /etc/salt/cloud
[INFO    ] salt-cloud starting
[DEBUG   ] 'parallels.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'parallels.avail_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'proxmox.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'saltify.destroy' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'saltify.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'saltify.avail_images' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'saltify.avail_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'rackspace.reboot' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'openstack.list_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'rackspace.list_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'parallels.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'parallels.avail_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'proxmox.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'saltify.destroy' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'saltify.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'saltify.avail_images' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'saltify.avail_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'rackspace.reboot' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'openstack.list_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'rackspace.list_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] Using EC2 endpoint: ec2.us-east-1.amazonaws.com
[DEBUG   ] EC2 Request: https://ec2.us-east-1.amazonaws.com/
[INFO    ] Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
[DEBUG   ] Setting read timeout to None
[DEBUG   ] "GET /?mygetlinkHTTP/1.1" 200 None
[DEBUG   ] EC2 Response Status Code: 200
[ERROR   ] There was a profile error: 'str' object has no attribute 'copy'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 231, in run
    self.config.get('names')
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1323, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1104, in create
    'minion', vm_, self.opts, default={}
  File "/usr/lib/python2.7/dist-packages/salt/config.py", line 1733, in get_cloud_config_value
    value.update(details[name].copy())
AttributeError: 'str' object has no attribute 'copy'
```

**Comment by masterkorp** [comment]
ping

**Comment by rallytime** [comment]
@masterkorp How did you install salt? What distro are you running on? There's a lot going on here, so I am starting with the stack trace you have from your versions report. 

Secondly, can you do a `salt-cloud --versions-report`? If so, can you post that output?

Are you able to do a `salt-cloud --list-images my-aws` successfully?

**Comment by rallytime** [comment]
Oh! Also, can you try changing the name of your provider file from `/etc/salt/cloud.providers.d/provider.conf` to `/etc/salt/cloud.providers.d/ec2-config.conf` and the same for the profile? (`/etc/salt/cloud.profiles.d/profile.conf`to `/etc/salt/cloud.profiles.d/ec2-config.conf`? I'm not sure if that is the problem, but I am wondering if `salt/cloud/config.py` is getting confused on where to look for files int he `cloud.*.d` directories.

**Comment by masterkorp** [comment]
The ``salt-cloud --versions-report`` gives me the same error:
```
Traceback (most recent call last):
  File "/usr/bin/salt-cloud", line 10, in <module>
    salt_cloud()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 210, in salt_cloud
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 42, in run
    self.parse_args()
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 2313, in parse_args
    return super(SaltCloudParser, self).parse_args(args, values)
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 126, in parse_args
    self.print_versions_report()
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 2302, in print_versions_report
    print('\n'.join(version.versions_report(include_salt_cloud=True)),
  File "/usr/lib/python2.7/dist-packages/salt/version.py", line 542, in versions_report
    libs = list(versions_information(include_salt_cloud=include_salt_cloud))
  File "/usr/lib/python2.7/dist-packages/salt/version.py", line 527, in versions_information
    imp = __import__(imp)
  File "/usr/local/lib/python2.7/dist-packages/libnacl/__init__.py", line 75, in <module>
    nacl = _get_nacl()
  File "/usr/local/lib/python2.7/dist-packages/libnacl/__init__.py", line 73, in _gTraceback (most recent call last):
  File "/usr/bin/salt-cloud", line 10, in <module>
    salt_cloud()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 210, in salt_cloud
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 42, in run
    self.parse_args()
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 2313, in parse_args
    return super(SaltCloudParser, self).parse_args(args, values)
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 126, in parse_args
    self.print_versions_report()
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 2302, in print_versions_report
    print('\n'.join(version.versions_report(include_salt_cloud=True)),
  File "/usr/lib/python2.7/dist-packages/salt/version.py", line 542, in versions_report
    libs = list(versions_information(include_salt_cloud=include_salt_cloud))
  File "/usr/lib/python2.7/dist-packages/salt/version.py", line 527, in versions_information
    imp = __import__(imp)
  File "/usr/local/lib/python2.7/dist-packages/libnacl/__init__.py", line 75, in <module>
    nacl = _get_nacl()
  File "/usr/local/lib/python2.7/dist-packages/libnacl/__init__.py", line 73, in _get_nacl
    raise OSError(msg)
OSError: Could not locate nacl lib, searched for libsodium.so, libsodium.so.13, libsodium.so.10, libsodium.so.5, libsodium.so.4,  and tweetnacl.so
et_nacl
    raise OSError(msg)
OSError: Could not locate nacl lib, searched for libsodium.so, libsodium.so.13, libsodium.so.10, libsodium.so.5, libsodium.so.4,  and tweetnacl.so
```

I am able to a ``salt-cloud --list-images my-aws`` **succesfully**

I moved the file names like you suggested, but the problem persists:
```
root@salt-master:/srv/saltstack# salt-cloud -p aws-micro test
[INFO    ] salt-cloud starting
[INFO    ] Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
[ERROR   ] There was a profile error: 'str' object has no attribute 'copy'
```

**Comment by rallytime** [comment]
@masterkorp Thanks for checking that. How did you install salt? What distro are you running this on?

**Comment by masterkorp** [comment]
@rallytime I installed salt through the [salt-bootstrap](https://github.com/saltstack/salt-bootstrap) script. 
This server is running on Ubuntu 14.04 LTS

**Comment by rallytime** [comment]
@masterkorp The errors that I am seeing in commands that you're posting with `salt --versions-report` and `salt-cloud --versions-report` look like something went wrong with the installation. Did you install with a git tag or just the default (I think that is the current HEAD of the develop branch)? I don't know if that is causing the problems you're seeing with salt-cloud, but it definitely is something that should be considered/addressed.

@techhat do you see anything in here that might be causing these salt-cloud problems?

**Comment by ericfode** [comment]
I am also having the same problem

Here is my version
```
            Salt: 2014.7.1
          Python: 2.7.9 (default, Jan  7 2015, 11:49:12)
          Jinja2: 2.7.3
        M2Crypto: 0.22
  msgpack-python: 0.4.2
    msgpack-pure: Not Installed
        pycrypto: 2.6.1
         libnacl: Not Installed
          PyYAML: 3.11
           ioflo: Not Installed
           PyZMQ: 14.3.1
            RAET: Not Installed
             ZMQ: 4.0.4
            Mako: Not Installed
 Apache Libcloud: 0.15.1
```

salt versions
```
           Salt: 2014.7.1
         Python: 2.7.9 (default, Jan  7 2015, 11:49:12)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
```

and my profile

```
saltmaster_ec2:
    provider: bigdata-aws
    image: ami-bc8131d4
    size: m3.medium
    securitygroup: mesos
    file_map:
      /Users/eric/projects/mesos: /srv/formulas/mesos
      /Users/eric/projects/bigdata/provisioning/top.sls: /srv/base/top.sls
      /Users/eric/projects/bigdata/provisioning/master: /etc/salt/master

mesos_master_ec2:
    provider: bigdata-aws
    image: ami-c2a818aa
    size: r3.large
    securitygroup: mesos
    sync_after_install: all
    grains:
      - roles: 
          - mesos-master
      - application: mesos
      - environment: dev

mesos_slave_ec2:
    provider: bigdata-aws
    image: ami-c2a818aa
    size: r3.large
    sync_after_install: all
    securitygroup: mesos
    grains:
      - roles: 
          - mesos-slave
      - application: mesos
      - environment: dev
```

**Comment by Chronojam** [comment]
This is gonna sound daft,
but try changing:
``` yaml
my-aws:
  minion:
    master:123.456.789.123
```
to 
``` yaml
my-aws:
  minion:
    master: 123.456.789.123
```

(I just had this error and this fixed the issue for me)

**Comment by masterkorp** [comment]
@Chronojam Thanks !

**Comment by techhat** [comment]
@Chronojam, that doesn't sound daft; YAML is pretty picky about requiring whitespace after `:` and `-`.

**Comment by rallytime** [comment]
Thanks for catching that @Chronojam! 

@masterkorp Looks like that was the problem (and I've run into that before only on my salt-ssh roster file, which prompted me to open #22332. Do you think this particular issue can be closed?

@techhat I'm sure this isn't the first time something like this has come up. Would it make sense to do some pre-processing of the cloud files to look for these syntactical errors? Or no? I am not sure where we've landed on that in the past.

**Comment by techhat** [comment]
@rallytime, #15836.

**Comment by rallytime** [comment]
Oh, nice! Thanks @techhat!

**Comment by masterkorp** [comment]
@rallytime I do think this issue in particular can be closed, given https://github.com/saltstack/salt/issues/22332 and https://github.com/saltstack/salt/issues/15836 expose the actual root cause of the problem.

**Comment by rallytime** [comment]
@masterkorp Ok, sounds good. Thanks!

**Comment by szwed** [comment]
just an ugly workaround which works for me:

    #output: nested
    output: highstate 

After I switch from highstate to nested the "salt-cloud: there was a profile error: 'str' object has no attribute 'copy'" message does not pop up.
