### ISSUE TITLE
Permission issue running salt master as unprivileged user

### ISSUE THREAD

**Issue by paolodina** [saltstack/salt#22919]
I'm trying to run salt-master as unprivileged user on a shared hosting server, in my home directory. There is a problem with permission traversal check starting the master:

```
SaltClientError: Could not access /home. Please give myuser read permissions.
```

and it's expected because `ll -d /home` gives:

```
drwxr-x--x 280 root root 12288 10 apr 02:37 /home
```

But I'd rather expect it shouldn't be a problem because `/home/myuser` is read/write to myuser. Nevertheless the master doesn't start and I have to stop the exception keep looping with ctrl c.

I can't change /home permissions. Any workaround? Maybe it's possible to disable traversal check? 

Issue details:

``` console
$ cat ~/local/etc/salt/master
# ...other config...
user: myuser
root_dir: /home/myuser/local


$ LD_LIBRARY_PATH=/home/myuser/lib/python2.6/zmq
$ salt-master -c ~/local/etc/salt/ --versions
Salt Version:
           Salt: 2015.2.0-974-g5e7fba6

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.22
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
           RAET: 0.6.3
            ZMQ: 4.0.5
          ioflo: 1.2.1
        libnacl: 1.4.2
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
       pycrypto: 2.0.1

System Versions:
           dist: centos 6.6 Final
        machine: x86_64
        release: 2.6.32-504.3.3.el6.x86_64
         system: CentOS 6.6 Final


$ salt-master -c ~/local/etc/salt/ -l debug
[DEBUG   ] Reading configuration from /home/myuser/local/etc/salt/master
[DEBUG   ] Guessing ID. The id can be explicitly in set /etc/salt/minion
[INFO    ] Found minion id from generate_minion_id(): example.com
[DEBUG   ] Configuration file path: /home/myuserlocal/etc/salt/master
[INFO    ] Setting up the Salt Master
[DEBUG   ] Loaded master key: /home/myuser/etc/salt/pki/master/master.pem
[INFO    ] Preparing the myuser key for local communication
[DEBUG   ] Removing stale keyfile: /home/myuser/var/cache/salt/master/.myuser_key
[DEBUG   ] Created pidfile: /home/myuser/var/run/salt-master.pid
[INFO    ] The salt master is starting up
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init
[INFO    ] salt-master is starting as user 'myuser'
[INFO    ] Current values for max open files soft/hard setting: 4096/4096
[INFO    ] The value for the 'max_open_files' setting, 100000, is higher than what the user running salt is allowed to raise to, 4096. Defaulting to 4096.
[INFO    ] Creating master process manager
[INFO    ] Creating master maintenance process
[DEBUG   ] Started 'Maintenance' with pid 31311
[INFO    ] Creating master publisher process
[DEBUG   ] Started 'Publisher' with pid 31312
[INFO    ] Creating master event publisher process
[INFO    ] Starting the Salt Publisher on tcp://0.0.0.0:25977
[DEBUG   ] Started 'EventPublisher' with pid 31315
[INFO    ] Starting the Salt Puller on ipc:///home/myuser/var/run/salt/master/publish_pull.ipc
[INFO    ] Creating master request server process
[DEBUG   ] Started 'run_reqserver' with pid 31333
[DEBUG   ] Started 'MWorker' with pid 31334
[DEBUG   ] MasterEvent PUB socket URI: ipc:///home/myuser/var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///home/myuser/var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Reading configuration from /home/myuser/local/etc/salt/master
[DEBUG   ] Started 'MWorker' with pid 31337
[DEBUG   ] MasterEvent PUB socket URI: ipc:///home/myuser/var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///home/myuser/var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Started 'MWorker' with pid 31338
[DEBUG   ] Reading configuration from /home/myuser/local/etc/salt/master
[DEBUG   ] Started 'MWorker' with pid 31341
[DEBUG   ] MasterEvent PUB socket URI: ipc:///home/myuser/var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///home/myuser/var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Started 'MWorker' with pid 31342
[DEBUG   ] Started 'zmq_device' with pid 31345
[DEBUG   ] Reading configuration from /home/myuser/local/etc/salt/master
[INFO    ] Setting up the master communication server
[DEBUG   ] MasterEvent PUB socket URI: ipc:///home/myuser/var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///home/myuser/var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Reading configuration from /home/myuser/local/etc/salt/master
[DEBUG   ] Could not LazyLoad timezone.get_offset
[DEBUG   ] MasterEvent PUB socket URI: ipc:///home/myuser/var/run/salt/master/master_event_pub.ipc
[DEBUG   ] Guessing ID. The id can be explicitly in set /etc/salt/minion
[DEBUG   ] Guessing ID. The id can be explicitly in set /etc/salt/minion
[DEBUG   ] Guessing ID. The id can be explicitly in set /etc/salt/minion
[DEBUG   ] MasterEvent PULL socket URI: ipc:///home/myuser/var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Could not LazyLoad config.merge
[DEBUG   ] Reading configuration from /home/myuser/local/etc/salt/master
[DEBUG   ] MasterEvent PUB socket URI: ipc:///home/myuser/var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///home/myuser/var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Reading configuration from /home/myuser/local/etc/salt/master
[INFO    ] Found minion id from generate_minion_id(): example.com
[DEBUG   ] Missing configuration file: ~/.saltrc
Process MWorker-4:4:
Traceback (most recent call last):
[INFO    ] Found minion id from generate_minion_id(): example.com
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 232, in _bootstrap
    self.run()
  File "/home/myuser/lib/python2.6/salt/master.py", line 938, in run
    self.crypticle)
  File "/home/myuser/lib/python2.6/salt/master.py", line 1611, in __init__
    self.local = salt.client.get_local_client(self.opts['conf_file'])
  File "/home/myuser/lib/python2.6/salt/client/__init__.py", line 95, in get_local_client
    return LocalClient(mopts=opts, skip_perm_errors=skip_perm_errors)
  File "/home/myuser/lib/python2.6/salt/client/__init__.py", line 135, in __init__
    self.key = self.__read_master_key()
  File "/home/myuser/lib/python2.6/salt/client/__init__.py", line 161, in __read_master_key
    self.skip_perm_errors)
  File "/home/myuser/lib/python2.6/salt/utils/verify.py", line 378, in check_path_traversal
    raise SaltClientError(msg)
SaltClientError: Could not access /home. Please give myuser read permissions.
[DEBUG   ] Missing configuration file: ~/.saltrc
[INFO    ] Found minion id from generate_minion_id(): example.com
Process MWorker-4:2:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 232, in _bootstrap
    self.run()
  File "/home/myuser/lib/python2.6/salt/master.py", line 938, in run
[DEBUG   ] Missing configuration file: ~/.saltrc
    self.crypticle)
  File "/home/myuser/lib/python2.6/salt/master.py", line 1611, in __init__
    self.local = salt.client.get_local_client(self.opts['conf_file'])
  File "/home/myuser/lib/python2.6/salt/client/__init__.py", line 95, in get_local_client
Process MWorker-4:1:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 232, in _bootstrap
    return LocalClient(mopts=opts, skip_perm_errors=skip_perm_errors)
  File "/home/myuser/lib/python2.6/salt/client/__init__.py", line 135, in __init__
    self.run()
    self.key = self.__read_master_key()
  File "/home/myuser/lib/python2.6/salt/master.py", line 938, in run
  File "/home/myuser/lib/python2.6/salt/client/__init__.py", line 161, in __read_master_key
    self.skip_perm_errors)
  File "/home/myuser/lib/python2.6/salt/utils/verify.py", line 378, in check_path_traversal
    raise SaltClientError(msg)
SaltClientError: Could not access /home. Please give myuser read permissions.
    self.crypticle)
  File "/home/myuser/lib/python2.6/salt/master.py", line 1611, in __init__
    self.local = salt.client.get_local_client(self.opts['conf_file'])
  File "/home/myuser/lib/python2.6/salt/client/__init__.py", line 95, in get_local_client
    return LocalClient(mopts=opts, skip_perm_errors=skip_perm_errors)
  File "/home/myuser/lib/python2.6/salt/client/__init__.py", line 135, in __init__
    self.key = self.__read_master_key()
  File "/home/myuser/lib/python2.6/salt/client/__init__.py", line 161, in __read_master_key
    self.skip_perm_errors)
  File "/home/myuser/lib/python2.6/salt/utils/verify.py", line 378, in check_path_traversal
    raise SaltClientError(msg)
SaltClientError: Could not access /home. Please give myuser read permissions.
[INFO    ] Process <class 'salt.master.MWorker'> (31341) died with exit status None, restarting...
[DEBUG   ] Guessing ID. The id can be explicitly in set /etc/salt/minion
[DEBUG   ] Guessing ID. The id can be explicitly in set /etc/salt/minion
[DEBUG   ] Guessing ID. The id can be explicitly in set /etc/salt/minion
[INFO    ] Found minion id from generate_minion_id(): example.com
[DEBUG   ] Missing configuration file: ~/.saltrc
```

**Comment by jfindlay** [comment]
@paolodina, thanks for the report.

**Comment by paolodina** [comment]
Btw, I wonder which are the limits in running the master as unprivileged user. For example, can a such configured master order to execute states and commands as root on the minion?

**Comment by jfindlay** [comment]
@paolodina, the only mechanism I know of (there may be (better) others) to achieve this is to grant the minion user sudo access use sudo appropriately in the states applied.  You could also have an sudoers policy and then run the minion itself under sudo.
