### ISSUE TITLE
ASCII codec u'\xae' issues with - Windows Server 2008 Standard [Workaround included]

### ISSUE THREAD

**Issue by b18** [saltstack/salt#22968]
Salt Master: 2014.7.4 -- Running on Ubuntu 14.04
Salt Minion: 2014.7.4 -- Running on Windows Server 2008 Standard (x86)

FIRST - This is the error I get out of the box
```
salt 'myserver' state.show_highstate
myserver:
    The minion function caused an exception: Traceback (most recent call last):
      File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1020, in _thread_return
        return_data = func(*args, **kwargs)
      File "c:\salt\bin\lib\site-packages\salt\modules\state.py", line 587, in show_highstate
        ret = st_.compile_highstate()
      File "c:\salt\bin\lib\site-packages\salt\state.py", line 2922, in compile_highstate
        matches = self.top_matches(top)
      File "c:\salt\bin\lib\site-packages\salt\state.py", line 2401, in top_matches
        _filter_matches(match, data, self.opts['nodegroups'])
      File "c:\salt\bin\lib\site-packages\salt\state.py", line 2390, in _filter_matches
        _opts
      File "c:\salt\bin\lib\site-packages\salt\minion.py", line 2386, in confirm_top
        return getattr(self, funcname)(match)
      File "c:\salt\bin\lib\site-packages\salt\minion.py", line 2560, in compound_match
        '@'.join(comps[1:])
      File "c:\salt\bin\lib\site-packages\salt\minion.py", line 2425, in grain_match
        return salt.utils.subdict_match(self.opts['grains'], tgt, delim=delim)
      File "c:\salt\bin\lib\site-packages\salt\utils\__init__.py", line 1231, in subdict_match
        exact_match=exact_match):
      File "c:\salt\bin\lib\site-packages\salt\utils\__init__.py", line 1195, in _match
        return fnmatch.fnmatch(str(target).lower(), pattern.lower())
    UnicodeEncodeError: 'ascii' codec can't encode character u'\xae' in position 9: ordinal not in range(128)
```
It looks like the default value for the grain "fullosname" is: Microsoft® Windows Server® 2008 Standard

The ® in this value causes the issues. If I manually set the grain "fullosname" value to this same value minus the special character in the minion config file as follows.....
```
grains:
  osfullname: Microsoft Windows Server 2008 Standard
```
..... And restart the salt-minion service, the issue goes away and all previously problematic functions get applied properly.

**Comment by rallytime** [comment]
@b18 Thanks for the report. I thought we had fixed this one....

ping @twangboy and @UtahDave

**Comment by jfindlay** [comment]
@s0undt3ch

**Comment by twangboy** [comment]
Could you post a copy of the state you're using so I can recreate this?

**Comment by twangboy** [comment]
@b18 What command in your highstate is failing on this? I would like to verify that this is fixed.
