### ISSUE TITLE
Locale state throwing traceback when generating not (yet) existing locale

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#22981]
It appears that Salt 2014.7.5 has some issues with locales or is lacking error handling for this particular case.

This is running from a Vagrantbox of Ubuntu/Trusty64 (20150420.1.2). 
The state actually is supposed to take care of generating the required locales `en_US.UTF-8` and `nl_NL.UTF-8` but is throwing traceback when executed via `salt-call`:

```python
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'qa', ** done ** 'top.sls'
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
ValueError: unknown locale: UTF-8
Traceback (most recent call last):
 File "/usr/bin/salt-call", line 11, in <module>
   salt_call()
 File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 123, in salt_call
   client.run()
 File "/usr/lib/python2.7/dist-packages/salt/cli/__init__.py", line 422, in run
   caller.run()
 File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 237, in run
   self.opts)
 File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 44, in display_output
   display_data = get_printout(out, opts)(data).rstrip()
 File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 74, in output
   return _format_host(host, hostdata)[0]
 File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 209, in _format_host
   comment = salt.utils.sdecode(ret['comment'])
 File "/usr/lib/python2.7/dist-packages/salt/utils/__init__.py", line 2512, in sdecode
   encodings = get_encodings()
 File "/usr/lib/python2.7/dist-packages/salt/utils/decorators/__init__.py", line 193, in _memoize
   cache[args] = func(*args)
 File "/usr/lib/python2.7/dist-packages/salt/utils/__init__.py", line 2496, in get_encodings
   loc = locale.getdefaultlocale()[-1]
 File "/usr/lib/python2.7/locale.py", line 543, in getdefaultlocale
   return _parse_localename(localename)
 File "/usr/lib/python2.7/locale.py", line 475, in _parse_localename
   raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
Traceback (most recent call last):
 File "/usr/bin/salt-call", line 11, in <module>
   salt_call()
 File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 123, in salt_call
   client.run()
 File "/usr/lib/python2.7/dist-packages/salt/cli/__init__.py", line 422, in run
   caller.run()
 File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 237, in run
   self.opts)
 File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 44, in display_output
   display_data = get_printout(out, opts)(data).rstrip()
 File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 74, in output
   return _format_host(host, hostdata)[0]
 File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 209, in _format_host
   comment = salt.utils.sdecode(ret['comment'])
 File "/usr/lib/python2.7/dist-packages/salt/utils/__init__.py", line 2512, in sdecode
   encodings = get_encodings()
 File "/usr/lib/python2.7/dist-packages/salt/utils/decorators/__init__.py", line 193, in _memoize
   cache[args] = func(*args)
 File "/usr/lib/python2.7/dist-packages/salt/utils/__init__.py", line 2496, in get_encodings
   loc = locale.getdefaultlocale()[-1]
 File "/usr/lib/python2.7/locale.py", line 543, in getdefaultlocale
   return _parse_localename(localename)
 File "/usr/lib/python2.7/locale.py", line 475, in _parse_localename
   raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
vagrant@web01:~$
```

Salt version details:
```console
vagrant@web01:~$ salt-minion --versions-report
                 Salt: 2014.7.5
               Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
               Jinja2: 2.7.2
             M2Crypto: 0.21.1
       msgpack-python: 0.3.0
         msgpack-pure: Not Installed
             pycrypto: 2.6.1
              libnacl: Not Installed
               PyYAML: 3.10
                ioflo: Not Installed
                PyZMQ: 14.0.1
                 RAET: Not Installed
                  ZMQ: 4.0.4
                 Mako: 0.9.1
Debian source package: 2014.7.5+ds-1ubuntu1
```

The locales are installed:
```console
vagrant@web01:~$ dpkg -l | grep locales
ii  krb5-locales                     1.12+dfsg-2ubuntu5.1             all          Internationalization support for MIT Kerberos
ii  locales                          2.13+git20120306-12.1            all          common files for locale support
ii  python-apt-common                0.9.3.5ubuntu1                   all          Python interface to libapt-pkg (locales)
```

And some (default) one's are available:
```console
vagrant@web01:~$ locale -a
locale: Cannot set LC_CTYPE to default locale: No such file or directory
C
C.UTF-8
en_US.utf8
POSIX
```

**Comment by jfindlay** [comment]
@syphernl, is it possible for you to also post (part of) the state?  Thanks.

**Comment by syphernl** [comment]
The state regarding locales is just this:
```
en_US.UTF-8:
    locale.present
nl_NL.UTF-8:
    locale.present
```
Nothing fancy really :)
Op 23 apr. 2015 8:33 PM schreef Justin Findlay <notifications@github.com>:@syphernl, is it possible for you to also post (part of) the state?  Thanks.

**Comment by jfindlay** [comment]
@s0undt3ch, do you have any ideas on this?

**Comment by syphernl** [comment]
Turns out this is caused by OSX's default value for `LC_CTYPE` which is apparently set to `utf-8` instead of `en_US.UTF-8`. Since all `LC_*` variables are being passed on via SSH the session ends up with an invalid locale which Salt does not like.

Hope this helps you guys in figuring out something to prevent the highstate from breaking this severely :)
