### ISSUE TITLE
Configure and read/write to Swift/S3 buckets

### ISSUE THREAD

**Issue by renoirb** [saltstack/salt#23007]
Hi all,

I’ve been wondering how to configure salt to read/write files to a S3 nor Swift object store.

Environment details:
1. I’m not running on Amazon
2. Ubuntu 14.04 LTS, w/ salt 2014.7.4
3. I only have access to endpoint, key, secrets
4. key is either in S3 or Swift format

[Documentation][1] is unclear —and the source [doesn’t help][2] [either][3]— on how I can configure and use. All we are left is with trials and errors and half successes.

So far, I could get info from files on a bucket, but not download it. 

Here’s latest successful config:

```yaml
# file: /etc/salt/minion.d/s3.conf
s3.keyid: bbbbbbbbbbbbbbbbbbar
s3.key: ffffffffffffffffffffffffffffffffff-00000
s3.service_url: objects.dreamhost.com
```

I tried many variants with no complete success

```
root@salt:/home/renoirb# salt-call s3.head apt php5-memcached_2.2.0-wpd_amd64.deb
[INFO    ] Starting new HTTPS connection (1): apt.objects.dreamhost.com
local:
    ----------
    headers:
        - content-length
        - accept-ranges
        - server
        - last-modified
        - etag
        - x-pad
        - date
        - content-type
        - x-amz-meta-mtime
````

And when I try to get a file from the bucket, it throws a "not well-formed" exception.

```
root@salt:/home/renoirb# salt-call s3.get apt php5-memcached_2.2.0-wpd_amd64.deb
[INFO    ] Starting new HTTPS connection (1): apt.objects.dreamhost.com
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
ParseError: not well-formed (invalid token): line 1, column 0
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 123, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/__init__.py", line 422, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 227, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 129, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/s3.py", line 154, in get
    verify_ssl=verify_ssl)
  File "/usr/lib/python2.7/dist-packages/salt/utils/s3.py", line 212, in query
    items = ET.fromstring(response)
  File "<string>", line 124, in XML
ParseError: not well-formed (invalid token): line 1, column 0
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 123, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/__init__.py", line 422, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 227, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 129, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/s3.py", line 154, in get
    verify_ssl=verify_ssl)
  File "/usr/lib/python2.7/dist-packages/salt/utils/s3.py", line 212, in query
    items = ET.fromstring(response)
  File "<string>", line 124, in XML
cElementTree.ParseError: not well-formed (invalid token): line 1, column 0
```

Ideas, recommendations, what am I missing?

Thanks!

  [1]: http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.swift.html#module-salt.modules.swift
  [2]: http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.s3.html
  [3]: https://github.com/saltstack/salt/blob/2014.7/salt/modules/s3.py

**Comment by wt** [comment]
Salt stinks at reading from S3 the last time I tried, but here is a config that I used to use:
```
fileserver:
  - roots
  - s3fs

s3.buckets:
  - <global-salt-files-bucket>
```

I actually use instance profiles and roles to authenticate so that I don't have to have keys in my salt config.

The main problem with s3fs is the it didn't do a good job of caching and slowed the salt-master dramatically. I would really have liked to use it.

**Comment by jfindlay** [comment]
@renoirb, thanks for the report.

**Comment by MattHall** [comment]
@renoirb Did you get anywhere with this? Seeing a similar issue here. Trace:

```
sudo salt-call -l debug s3.get <redacted> web/QA-20150928-001.tar
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Configuration file path: /etc/salt/minion
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'qa-web', 'tcp://10.x.x.x:4506')
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded s3.get
[DEBUG   ] LazyLoaded config.option
[DEBUG   ] CanonicalizedResource: /<redacted>/web/QA-20150928-001.tar
[DEBUG   ] CanonicalizedAmzHeaders:
[DEBUG   ] String To Sign::
GET

text/plain
Mon, 28 Sep 2015 09:59:57 GMT
/<redacted>/web/QA-20150928-001.tar
[DEBUG   ] S3 Request: https://<redacted>.s3-eu-west-1.amazonaws.com/web/QA-20150928-001.tar
[DEBUG   ] S3 Headers::
[DEBUG   ]     Authorization: AWS <redacted>
[INFO    ] Starting new HTTPS connection (1): <redacted>.s3-eu-west-1.amazonaws.com
[DEBUG   ] Setting read timeout to None
[DEBUG   ] "GET /web/QA-20150928-001.tar HTTP/1.1" 200 437114880
[DEBUG   ] S3 Response Status Code: 200
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
ParseError: not well-formed (invalid token): line 1, column 15
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 227, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 69, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 236, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 138, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/s3.py", line 155, in get
    verify_ssl=verify_ssl)
  File "/usr/lib/python2.7/dist-packages/salt/utils/s3.py", line 222, in query
    items = ET.fromstring(response)
  File "<string>", line 124, in XML
ParseError: not well-formed (invalid token): line 1, column 15
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 227, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 69, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 236, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 138, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/s3.py", line 155, in get
    verify_ssl=verify_ssl)
  File "/usr/lib/python2.7/dist-packages/salt/utils/s3.py", line 222, in query
    items = ET.fromstring(response)
  File "<string>", line 124, in XML
cElementTree.ParseError: not well-formed (invalid token): line 1, column 15
```

One odd thing is that we don't see this every time.

**Comment by renoirb** [comment]
I didn't try using S3 since I reported it.  It might have been fixed since then.

**Comment by rallytime** [comment]
@MattHall Can you post the output of `salt-cloud --versions-report` please? This is on our radar, just haven't gotten a chance to try it yet, and it'd be great to see what version you're running.

**Comment by MattHall** [comment]
@rallytime Output below, though have seen the issue with 2015.5.2 and 2015.5.3 too. I'm seeing it intermittently; it was broken for me today for a few hours, but seems fine now. 
```
Salt Version:
            Salt: 2015.8.0

Dependency Versions:
 Apache Libcloud: 0.14.1
          Jinja2: 2.7.3
        M2Crypto: 0.21.1
            Mako: 0.9.1
          PyYAML: 3.11
           PyZMQ: 14.4.0
          Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
            RAET: Not Installed
         Tornado: 4.2.1
             ZMQ: 4.0.4
            cffi: Not Installed
        cherrypy: 3.2.2
        dateutil: 1.5
           gitdb: 0.5.4
       gitpython: Not Installed
           ioflo: Not Installed
         libnacl: Not Installed
    msgpack-pure: Not Installed
  msgpack-python: 0.4.2
    mysql-python: Not Installed
       pycparser: Not Installed
        pycrypto: 2.6.1
          pygit2: Not Installed
    python-gnupg: Not Installed
           smmap: 0.8.2
         timelib: Not Installed

System Versions:
            dist: Ubuntu 14.04 trusty
         machine: x86_64
         release: 3.13.0-44-generic
          system: Ubuntu 14.04 trusty
```

**Comment by herisanu** [comment]
I can confirm it's broken on salt-2015.8.0-2.
It's either cElementTree.ParseError or NoSuchKey when you try to get a list.
Tried on both private and public buckets.

**Comment by techhat** [comment]
@renoirb, I get the same error when trying to get a file, unless I tell it where to download the file to. For instance:
```
salt-call s3.get jphalltest ice.jpg local_file=/tmp/ice.jpg
```
I don't think our S3 stuff supports swift. However, there does seem to be a `swift` execution module. There's not a state, but it looks like `file.managed` does support `swift://` URLs.

**Comment by techhat** [comment]
@herisanu can you give me an example of the commands that you're using to get those errors?

**Comment by herisanu** [comment]
@techhat you have to also add the parameter with return_bin=true. Otherwise he tries to interpret the result as an XML. This is why i got the error.

https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.s3.html
"Set return_bin to True in order to retrieve an object wholesale."

I was also trying against an AWS s3 bucket. Didn't try it on swift.

**Comment by techhat** [comment]
@herisanu, I didn't have to set `return_bin` to `True`, but it's certainly not a bad idea.

So when you set that, it fixes your issue?

**Comment by renoirb** [comment]
>
> I didn't use this feature since I last reported.
>

I'll give a shot in my current project.


-- 

*Renoir Boulanger*
https://renoirboulanger.com/ <https://renoirboulanger.com/#is>  ✪  @renoirb
<https://github.com/renoirb>
Check my availability: <https://freebusy.io/renoirb@gmail.com>
Meet me: <https://appear.in/renoirb>
Instant messaging: <https://telegram.me/renoirb>
~

**Comment by cro** [comment]
Hi!  Can this issue be closed?  Thanks.

**Comment by herisanu** [comment]
:+1: it works for me.  cElementTree.ParseError was because i didn't tell it return_bin.

**Comment by techhat** [comment]
It sounds like this can be closed.
