### ISSUE TITLE
Pilllars are not work when using S3 as fileserver in 2014.7.5

### ISSUE THREAD

**Issue by joeto0** [saltstack/salt#23016]
Hi 
   My pillars are not available in minions when I use s3fs as a fileserver. If I use same files locally everything is working fine.

top.sls for pillars is loaded but nothing more.

 Yesterday in IRC salt channel another user mention the same for gitfs, but I didnt check that so maybe the problem exist also there.

**Comment by jfindlay** [comment]
@joeto0, what are your relevant configs and logs if necessary, what is the output of `salt --versions-report`, and did you have this working before?  Thanks.

**Comment by joeto0** [comment]
I will rebuild env on Monday and will come back with logs and versions. 

If this help it is standard Ubuntu 14.04 LTS image in AWS, installation was done yesterday by salt-bootstrap script. 

Topology looks like:
```
Master <- Syndic <- Several Minions.
             |
            S3
```
Only Syndic have access to S3

/etc/salt/minion.d/minion.conf
```
rejected_retry: True
random_reauth_delay: 60
auth_tries: 60
auth_safemode: False
ping_interval: 2
restart_on_error: True
```

/etc/salt/master.d/fileserver_backend.conf
```
fileserver_backend:
  - s3fs

s3.buckets:
  - S3_BUCKET_NAME
```
if not a big deal please fix s3 -> s3fs in docs. 
http://docs.saltstack.com/en/latest/ref/file_server/all/salt.fileserver.s3fs.html

/etc/salt/master.d/syndic.conf
```
syndic_master: SALT_MASTER_FQDN
auto_accept: True
con_cache: True
```

All files are delivered from salt://

Unfortunately this is my first attempt to use pillars in S3. So I don't know if it works with older versions of salt.

Again if I use same files on local filesystem everything works as expected.

**Comment by jfindlay** [comment]
@joeto0, thanks for the information.

**Comment by joeto0** [comment]
I have a question, in s3fs docs pillars are not mention at all, so maybe they are not working by design? 

Do I need to use salt.pillar.s3? http://docs.saltstack.com/en/latest/ref/pillar/all/salt.pillar.s3.html

If so could you please mention this in documentation and also implement pillars in s3fs in future releases.

**Comment by jfindlay** [comment]
@joeto0, this may be relevant, #23085.

**Comment by joeto0** [comment]
Yeap, docs are ok now :).

So looks like if I want to use pillars I need to have another bucket and "ext_pillar:" s3. 

I was able to make it run, but found something strange with "prefix:". My syndic configuration looks like:

```
fileserver_backend:
  - s3fs

s3.buckets:
  - S3_BUCKET_NAME_SALT

ext_pillar:
  - s3:
      keyid: 0
      key: 0
      bucket: S3_BUCKET_NAME_PILLAR
      multiple_env: False
      environment: base
      prefix: pillars/base
      verify_ssl: False
      service_url: s3.amazonaws.com
```
all bucket names are lowercase I am using uppercase just to be easy to see them.
and this end up with following error:

```
[DEBUG   ] S3 Request: https://S3_BUCKET_NAME_PILLAR.s3.amazonaws.com/?prefix=pillars%2Fbase
[DEBUG   ] S3 Headers::
[DEBUG   ]     Authorization: AWS BLABLABLABALBALBALBALBLABALBL
[INFO    ] Starting new HTTPS connection (1): S3_BUCKET_NAME_PILLAR.s3.amazonaws.com
[DEBUG   ] Setting read timeout to None
[DEBUG   ] "GET /?prefix=pillars%2Fbase HTTP/1.1" 200 None
[DEBUG   ] S3 Response Status Code: 200
[DEBUG   ] Writing S3 buckets pillar cache file
[ERROR   ] Failed to load ext_pillar s3: [Errno 2] No such file or directory: '/var/cache/salt/master/pillar_s3fs/S3_BUCKET_NAME_PILLAR-pillars/base-files.cache'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 523, in ext_pillar
    key)
  File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 484, in _external_pillar_data
    ext = self.ext_pillars[key](self.opts['id'], pillar, **val)
  File "/usr/lib/python2.7/dist-packages/salt/pillar/s3.py", line 125, in ext_pillar
    metadata = _init(s3_creds, bucket, multiple_env, environment, prefix)
  File "/usr/lib/python2.7/dist-packages/salt/pillar/s3.py", line 168, in _init
    environment, prefix)
  File "/usr/lib/python2.7/dist-packages/salt/pillar/s3.py", line 287, in _refresh_buckets_cache_file
    with salt.utils.fopen(cache_file, 'w') as fp_:
  File "/usr/lib/python2.7/dist-packages/salt/utils/__init__.py", line 1098, in fopen
    fhandle = open(*args, **kwargs)
IOError: [Errno 2] No such file or directory: '/var/cache/salt/master/pillar_s3fs/S3_BUCKET_NAME_PILLAR-pillars/base-files.cache'
```

if I create manually /var/cache/salt/master/pillar_s3fs/S3_BUCKET_NAME_PILLAR-pillars/ -> everything works

if I remove "/base" from prefix and have only "prefix: pillars", upload pillar data to s3://S3_BUCKET_NAME_PILLAR/pillars -> everything works

I also tried to use multple_env setup ( #22471 ), without success. Pillars are there, files are there, but minions do not receive them :(.

**Comment by croomshine** [comment]
I just ran into the prefix problem as well while setting up s3 ext_pillar.  Since the prefix has '/' in the value, it is not able to create the .cache file since it is technically rendered as a sub-directory.  Here is the error I'm getting (same as @joeto0 in his previous post):

Here is the master config:
```
ext_pillar:
    - s3:
        bucket: BUCKET
        prefix: phase1-1/salt/srv/pillar
```

```
[ERROR   ] Failed to load ext_pillar s3: [Errno 2] No such file or directory: '/var/cache/salt/master/pillar_s3fs/BUCKET/salt/srv/pillar-files.cache'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 631, in ext_pillar
    key)
  File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 583, in _external_pillar_data
    ext = self.ext_pillars[key](self.opts['id'], pillar, **val)
  File "/usr/lib/python2.7/dist-packages/salt/pillar/s3.py", line 144, in ext_pillar
    metadata = _init(s3_creds, bucket, multiple_env, environment, prefix, s3_cache_expire)
  File "/usr/lib/python2.7/dist-packages/salt/pillar/s3.py", line 185, in _init
    cache_file_mtime = os.path.getmtime(cache_file)
  File "/usr/lib/python2.7/genericpath.py", line 54, in getmtime
    return os.stat(filename).st_mtime
OSError: [Errno 2] No such file or directory: '/var/cache/salt/master/pillar_s3fs/BUCKET/salt/srv/pillar-files.cache'
```

I drilled this error down to line 234 in pillar/s3.py file.

By replacing '/' with '-' it writes the appropriate file correctly.  I don't know if it is the best solution, but it resolves the error and I'm able to pull in pillars from s3 now.
```
return os.path.join(cache_dir, '{0}-{1}-files.cache'.format(bucket, prefix.replace('/','-')))
```

**Comment by jfindlay** [comment]
Ping, @rallytime, @techhat.
