### ISSUE TITLE
SaltReqTimeoutError when attempting to generate a Salt token from a PAM eauth attempt

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#23053]
```python
# salt -a pam -T '*' test.ping
username: vagrant
password:
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
SaltReqTimeoutError: SaltReqTimeoutError: after 60 seconds, ran 1 tries
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 349, in salt_main
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/salt.py", line 145, in run
    res
  File "/usr/lib/python2.7/dist-packages/salt/auth/__init__.py", line 393, in token_cli
    tdata = self._send_token_request(load)
  File "/usr/lib/python2.7/dist-packages/salt/auth/__init__.py", line 346, in _send_token_request
    tdata = sreq.send('clear', load)
  File "/usr/lib/python2.7/dist-packages/salt/payload.py", line 273, in send
    'SaltReqTimeoutError: after {0} seconds, ran {1} tries'.format(timeout * tried, tried)
SaltReqTimeoutError: SaltReqTimeoutError: after 60 seconds, ran 1 tries
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 349, in salt_main
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/salt.py", line 145, in run
    res
  File "/usr/lib/python2.7/dist-packages/salt/auth/__init__.py", line 393, in token_cli
    tdata = self._send_token_request(load)
  File "/usr/lib/python2.7/dist-packages/salt/auth/__init__.py", line 346, in _send_token_request
    tdata = sreq.send('clear', load)
  File "/usr/lib/python2.7/dist-packages/salt/payload.py", line 273, in send
    'SaltReqTimeoutError: after {0} seconds, ran {1} tries'.format(timeout * tried, tried)
salt.exceptions.SaltReqTimeoutError: SaltReqTimeoutError: after 60 seconds, ran 1 tries
```

**Comment by whiteinge** [comment]
I am unsure of how to reproduce this reliably. Moving to Beryllium for now.

**Comment by thatch45** [comment]
We have been unable to reproduce, if this comes back please re-open
