### ISSUE TITLE
in a pillar.sls using a key of match: pillar causes a traceback

### ISSUE THREAD

**Issue by eedgar** [saltstack/salt#23118]
```
Traceback (most recent call last):
  File "/usr/local/bin/salt-call", line 9, in <module>
    load_entry_point('salt==2014.7.5', 'console_scripts', 'salt-call')()
  File "/usr/local/lib/python2.7/site-packages/salt/scripts.py", line 123, in salt_call
    client.run()
  File "/usr/local/lib/python2.7/site-packages/salt/cli/__init__.py", line 412, in run
    caller = salt.cli.caller.Caller.factory(self.config)
  File "/usr/local/lib/python2.7/site-packages/salt/cli/caller.py", line 64, in factory
    return ZeroMQCaller(opts, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/salt/cli/caller.py", line 87, in __init__
    self.minion = salt.minion.SMinion(opts)
  File "/usr/local/lib/python2.7/site-packages/salt/minion.py", line 268, in __init__
    self.gen_modules()
  File "/usr/local/lib/python2.7/site-packages/salt/minion.py", line 278, in gen_modules
    self.opts['environment'],
  File "/usr/local/lib/python2.7/site-packages/salt/pillar/__init__.py", line 577, in compile_pillar
    matches = self.top_matches(top)
  File "/usr/local/lib/python2.7/site-packages/salt/pillar/__init__.py", line 355, in top_matches
    self.opts.get('nodegroups', {}),
  File "/usr/local/lib/python2.7/site-packages/salt/minion.py", line 2386, in confirm_top
    return getattr(self, funcname)(match)
  File "/usr/local/lib/python2.7/site-packages/salt/minion.py", line 2476, in pillar_match
    return salt.utils.subdict_match(self.opts['pillar'], tgt, delim=delim)
KeyError: 'pillar'
```
to work around this change - match: pillar   to - match: pillars   

instead of a traceback a warning message should display that the user chose an invalid key.

**Comment by rallytime** [comment]
@eedgar Can you give us a little more context on what you did to cause this error? That will make it easier to reproduce and get this fixed up.

Please post the output of `salt --versions-report` as well as the command you're running and an example sls file that is causing this stacktrace. Thanks!
