### ISSUE TITLE
salt state run "crash" when apt-config is buggy

### ISSUE THREAD

**Issue by Reiner030** [saltstack/salt#23134]
Hello,

a wrong setting in apt (here: missing semicolon):

```
# cat /etc/apt/apt.conf.d/03fix-check-valid-until
// ################################
// # THIS FILE IS MANAGED BY SALT #
// ################################
// https://code.google.com/p/google-compute-engine/issues/detail?id=124#c2
Acquire::Check-Valid-Until "false"
```

creates on command line following error:

```
# aptitude update
E: Syntax error /etc/apt/apt.conf.d/03fix-check-valid-until:6: Extra junk at end of file
```

and in salt runs a very buggy behavior:

```
# salt-call --version
salt-call 2014.7.5 (Helium)
# salt '*' state.highstate 
saltmaster:
    Data failed to compile:
----------
    Rendering SLS common failed, render error: while parsing a block mapping
  in "<unicode string>", line 1347, column 7:
        - value: [WARNING ] Failed to impo ... 
          ^
expected <block end>, but found '<scalar>'
  in "<unicode string>", line 1347, column 25:
        - value: [WARNING ] Failed to import module aptpkg,  ... 
                            ^
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2465, in render_state
    sls, rendered_sls=mods
  File "/usr/lib/python2.7/dist-packages/salt/template.py", line 84, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/renderers/yaml.py", line 48, in render
    data = load(yaml_data, Loader=get_yaml_loader(argline))
  File "/usr/lib/python2.7/dist-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/lib/python2.7/dist-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 439, in parse_block_mapping_key
    "expected <block end>, but found %r" % token.id, token.start_mark)
ParserError: while parsing a block mapping
  in "<unicode string>", line 1347, column 7:
        - value: [WARNING ] Failed to impo ... 
          ^
expected <block end>, but found '<scalar>'
  in "<unicode string>", line 1347, column 25:
        - value: [WARNING ] Failed to import module aptpkg,  ... 
                            ^
```

**Comment by Reiner030** [comment]
Hint for temp fix:
Removing (or changing) the config "manually":
```
# salt '*' cmd.run "rm /etc/apt/apt.conf.d/03fix-check-valid-until"
```

**Comment by jfindlay** [comment]
Unless there is an apt config file (and also sources file?) validator we could try testing proposed changes to the file by creating a temporary config with the changes, whether this must involve writing down a file or not, and return any errors apt finds back to the user.

**Comment by Reiner030** [comment]
Mmh, thats not the no the concrete problem here.

=> independent of the state definition:
If there is a buggy apt config in system then the salt run crashes.
