### ISSUE TITLE
"Error in function _minion_event" resulting in modules not loaded

### ISSUE THREAD

**Issue by claudiupopescu** [saltstack/salt#23166]
**Version:**
```
           Salt: 2014.7.5
         Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.4
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 13.1.0
           RAET: Not Installed
            ZMQ: 3.2.3
           Mako: 0.7.0
```

**Error:**
```
2015-04-29 11:21:00,602 [salt.master                                ][ERROR   ] Error in function _minion_event:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/salt/master.py", line 1348, in run_func
    ret = getattr(self, func)(load)
  File "/usr/local/lib/python2.7/dist-packages/salt/master.py", line 1135, in _minion_event
    self.masterapi._minion_event(load)
  File "/usr/local/lib/python2.7/dist-packages/salt/daemons/masterapi.py", line 716, in _minion_event
    self.fire_event(event['data'], tagify(event['tag'], base=load['pretag']))
AttributeError: 'RemoteFuncs' object has no attribute 'fire_event'
```

The architecture is master -> syndic (with minion connected at master) -> servers (minions connected at syndic).
Any idea how to debug this one? From my tests so far all boto modules fail to load.

**Comment by jfindlay** [comment]
@claudiupopescu, thanks for the report.  This was the result of a typo in masterapi.py.
