### ISSUE TITLE
unable to revoke *.* grants when use salt.modules.mysql

### ISSUE THREAD

**Issue by lisa2lisa** [saltstack/salt#23201]
salt --versions-report
```
           Salt: 2014.7.2
         Python: 2.7.9 (default, Mar  4 2015, 14:41:42)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
```

salt-minion --version
```
salt-minion 2014.7.5 (Helium)
```

when you trying to revoke a \*.\* grants from mysql, for example:
```
salt "*" mysql.grant_revoke 'SELECT' '*.*' 'test' '%'
```

salt master will through exceptions:
```
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/salt/minion.py", line 1022, in _thread_return
        return_data = func(*args, **kwargs)
      File "/usr/local/lib/python2.7/site-packages/salt/modules/mysql.py", line 1726, in grant_revoke
        s_database,
    UnboundLocalError: local variable 's_database' referenced before assignment
```
the configuration for salt-minion to use mysql module is following (mysql user with superuser privilege):
```
mysql.host: 'localhost'
mysql.port: 3306
mysql.user: '*'
mysql.pass: '*'
mysql.db: 'mysql'
mysql.unix_socket: '/var/run/mysqld/mysqld.sock'
mysql.charset: 'utf8'
```

With python mysql connector installed:
```
python-mysqldb:
  Installed: 1.2.3-2
  Candidate: 1.2.3-2
  Version table:
 *** 1.2.3-2 0
        500 http://ftp.de.debian.org/debian/ wheezy/main amd64 Packages
        100 /var/lib/dpkg/status
```
Tested OS:
Debian:
```
Distributor ID:	Debian
Description:	Debian GNU/Linux 7.8 (wheezy)
Release:	7.8
Codename:	wheezy
```
Freebsd:
```
# freebsd-version
10.1-RELEASE-p6
```

**Comment by jfindlay** [comment]
@lisa2lisa, thanks for working on this.

**Comment by rallytime** [comment]
Thanks @lisa2lisa! Since your pull request was merged, I am going to close this issue. If more work should be done here, or this bug pops up again, please leave a comment and we will readily open this again.
