### ISSUE TITLE
Ubuntu 12.04 - ImportError: No module named mako.exceptions

### ISSUE THREAD

**Issue by neilferreira** [saltstack/salt#23200]
Hi all

I am running salt-minion 2014.7.5 (Helium) on a Ubuntu 12.04 server at the moment.  When running highstate I see lots of the following:

```
[CRITICAL] Rendering SLS 'base:pyramid.varnish-nginx' failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 99, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 331, in render_mako_tmpl
    import mako.exceptions
ImportError: No module named mako.exceptions
```

When trying to install mako,  it will remove salt-common and salt-minion

```
sudo apt-get install python-mako
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  msgpack-python python-zmq dctrl-tools python-jinja2
Use 'apt-get autoremove' to remove them.
Suggested packages:
  python-beaker python-mako-doc
The following packages will be REMOVED:
  salt-common salt-minion
The following NEW packages will be installed:
  python-mako
```

How can I get around this ?

**Comment by neilferreira** [comment]
For the time being I've installed python-mako using pip.

**Comment by neilferreira** [comment]
Scrap that

When I ran state.highstate salt un installed itself! 

```
INFO    ] Executing state pkg.installed for python-dev
[INFO    ] Executing command ['dpkg-query', '--showformat', '${Status} ${Package} ${Version} ${Architecture}\n', '-W'] in directory '/home/ubuntu'
[INFO    ] Package python-dev is already installed.
[INFO    ] Completed state [python-dev] at time 08:25:22.391697
[INFO    ] Running state [python-mako] at time 08:25:24.285859
[INFO    ] Executing state pkg.installed for python-mako
[INFO    ] Executing command 'apt-get -q update' in directory '/home/ubuntu'
[INFO    ] Executing command ['apt-get', '-q', '-y', '-o', 'DPkg::Options::=--force-confold', '-o', 'DPkg::Options::=--force-confdef', 'install', 'python-mako'] in directory '/home/ubuntu'
[INFO    ] Executing command ['dpkg-query', '--showformat', '${Status} ${Package} ${Version} ${Architecture}\n', '-W'] in directory '/home/ubuntu'
[INFO    ] Installed Packages:
salt-minion changed from 2014.7.5+ds-1precise1 to absent
salt-common changed from 2014.7.5+ds-1precise1 to absent
python-mako changed from absent to 0.5.0-1

[INFO    ] Loading fresh modules for state activity

```

**Comment by neilferreira** [comment]
Further to that

```
[INFO    ] Loading fresh modules for state activity
[ERROR   ] The renderer "yaml_jinja" is not available
[CRITICAL] The renderer yaml_jinja is unavailable, this error is often because the needed software is unavailable
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
LoaderError: The renderer yaml_jinja is unavailable, this error is often because the needed software is unavailable
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 123, in salt_call
  File "/usr/lib/python2.7/dist-packages/salt/cli/__init__.py", line 422, in run
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 227, in run
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 129, in call
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 325, in highstate
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2923, in call_highstate
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2023, in call_high
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1605, in call_chunks
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1859, in call_chunk
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1585, in call
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 766, in check_refresh
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 735, in module_refresh
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 720, in load_modules
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 345, in render
LoaderError: The renderer yaml_jinja is unavailable, this error is often because the needed software is unavailable
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>

```

**Comment by jfindlay** [comment]
Are the state(s) you're running using mako?  If so, it would make sense that you would want mako installed.

Regarding your package problem, it seems to me from the output you've pasted that salt-common and salt-minion would be removed by any apt-get action, not necessarily installing salt-mako.  does `aptitude install python-mako` give different results?  How did you provision the system and put a salt minion into it?

**Comment by danmur** [comment]
It looks like the way the dependencies are specified to me:
```
root@blah~# aptitude why-not python-mako
i   salt-minion Depends salt-common (= 2015.5.3+ds-1precise2)
i A salt-common Breaks  python-mako (< 0.7.0)```

**Comment by danmur** [comment]
```
root@blah:~# apt-cache showpkg python-mako
Package: python-mako
Versions:
0.5.0-1 (/var/lib/apt/lists/ap-southeast-2.ec2.archive.ubuntu.com_ubuntu_dists_precise_main_binary-amd64_Packages)
 Description Language:
                 File: /var/lib/apt/lists/ap-southeast-2.ec2.archive.ubuntu.com_ubuntu_dists_precise_main_binary-amd64_Packages
                  MD5: b107d73601aca3945d777218802bd901
 Description Language: en
                 File: /var/lib/apt/lists/ap-southeast-2.ec2.archive.ubuntu.com_ubuntu_dists_precise_main_i18n_Translation-en
                  MD5: b107d73601aca3945d777218802bd901


Reverse Depends:
  salt-common,python-mako 0.7.0
  salt-common,python-mako
  rhythmbox-plugins,python-mako
  deluge-web,python-mako
  rhythmbox-plugins,python-mako
  python-pyramid,python-mako 0.3.6
  python-pylons,python-mako 0.2.4
  ntop,python-mako
  doconce,python-mako
  deluge-web,python-mako
  bauble,python-mako 0.2.2
  rhythmbox-plugins,python-mako
  python-mako-doc,python-mako 0.3.6-1
  python-mako-doc,python-mako 0.3.6-1
  python-mako-doc,python-mako
  gobject-introspection,python-mako
Dependencies:
0.5.0-1 - python2.7 (0 (null)) python (2 2.7.1-0ubuntu2) python (3 2.8) python-markupsafe (0 (null)) python-beaker (2 1.1) python-mako-doc (0 (null)) python-pygments (0 (null)) python-pylons (0 (null)) python-turbogears (0 (null))
Provides:
0.5.0-1 -
Reverse Provides:
```
