### ISSUE TITLE
timezone state errors out on host that is using systemd

### ISSUE THREAD

**Issue by ksalman** [saltstack/salt#23223]
I have a timezone state like so:
```
PST8PDT:
  timezone.system:
    - utc: True
```
When I deploy that on Debian Jessie, it errors out
```
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://timezone/init.sls'
[INFO    ] Running state [PST8PDT] at time 08:06:03.750872
[INFO    ] Executing state timezone.system for PST8PDT
[INFO    ] Executing command 'timedatectl' in directory '/root'
[ERROR   ] Command 'timedatectl' failed with return code: 1
[ERROR   ] output: Failed to create bus connection: No such file or directory
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1531, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/states/timezone.py", line 72, in system
    if __salt__['timezone.get_hwclock']() == 'localtime':
  File "/usr/lib/python2.7/dist-packages/salt/modules/timezone.py", line 209, in get_hwclock
    'Failed to parse timedatectl output, this is likely a bug'
CommandExecutionError: Failed to parse timedatectl output, this is likely a bug

[INFO    ] Completed state [PST8PDT] at time 08:06:03.765944
local:
----------
          ID: PST8PDT
    Function: timezone.system
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1531, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/states/timezone.py", line 72, in system
                  if __salt__['timezone.get_hwclock']() == 'localtime':
                File "/usr/lib/python2.7/dist-packages/salt/modules/timezone.py", line 209, in get_hwclock
                  'Failed to parse timedatectl output, this is likely a bug'
              CommandExecutionError: Failed to parse timedatectl output, this is likely a bug
     Started: 08:06:03.750872
    Duration: 15.072 ms
     Changes:

Summary
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
```
Versions
```
root@foo:~# salt-minion --versions
                  Salt: 2014.7.2
                Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
                Jinja2: 2.7.3
              M2Crypto: 0.21.1
        msgpack-python: 0.4.2
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.11
                 ioflo: Not Installed
                 PyZMQ: 14.4.0
                  RAET: Not Installed
                   ZMQ: 4.0.5
                  Mako: 1.0.0
 Debian source package: 2014.7.2+ds-1
```

**Comment by jfindlay** [comment]
@ksalman, can you verify that this happens on 2014.7.5?  Thanks.

**Comment by ksalman** [comment]
@jfindlay Same problem with 2014.7.5
```
root@foo:~# salt-minion --versions
                  Salt: 2014.7.5
                Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
                Jinja2: 2.7.3
              M2Crypto: 0.21.1
        msgpack-python: 0.4.2
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.11
                 ioflo: Not Installed
                 PyZMQ: 14.4.0
                  RAET: Not Installed
                   ZMQ: 4.0.5
                  Mako: 1.0.0
 Debian source package: 2014.7.5+ds-1
```
```
root@foo:~# salt-call state.sls timezone
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://timezone/init.sls'
[INFO    ] Running state [PST8PDT] at time 09:23:21.012263
[INFO    ] Executing state timezone.system for PST8PDT
[INFO    ] Executing command 'timedatectl' in directory '/root'
[ERROR   ] Command 'timedatectl' failed with return code: 1
[ERROR   ] output: Failed to create bus connection: No such file or directory
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1542, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/states/timezone.py", line 72, in system
    if __salt__['timezone.get_hwclock']() == 'localtime':
  File "/usr/lib/python2.7/dist-packages/salt/modules/timezone.py", line 209, in get_hwclock
    'Failed to parse timedatectl output, this is likely a bug'
CommandExecutionError: Failed to parse timedatectl output, this is likely a bug

[INFO    ] Completed state [PST8PDT] at time 09:23:21.027479
local:
----------
          ID: PST8PDT
    Function: timezone.system
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1542, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/states/timezone.py", line 72, in system
                  if __salt__['timezone.get_hwclock']() == 'localtime':
                File "/usr/lib/python2.7/dist-packages/salt/modules/timezone.py", line 209, in get_hwclock
                  'Failed to parse timedatectl output, this is likely a bug'
              CommandExecutionError: Failed to parse timedatectl output, this is likely a bug
     Started: 09:23:21.012263
    Duration: 15.216 ms
     Changes:

Summary
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
```

**Comment by jfindlay** [comment]
This seems to be a problem with timedatectl not accepting old-style timezone specifiers.  Does the state work if you do
```yaml
America/Los_Angeles:
  timezone.system:
    - utc: True
```
or similar?

**Comment by ksalman** [comment]
Unfortunately that did  not help
```
oot@foo:~# salt-call state.sls timezone
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://timezone/init.sls'
[INFO    ] Running state [America/Los_Angeles] at time 09:40:18.364498
[INFO    ] Executing state timezone.system for America/Los_Angeles
[INFO    ] Executing command 'timedatectl' in directory '/root'
[ERROR   ] Command 'timedatectl' failed with return code: 1
[ERROR   ] output: Failed to create bus connection: No such file or directory
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1542, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/states/timezone.py", line 72, in system
    if __salt__['timezone.get_hwclock']() == 'localtime':
  File "/usr/lib/python2.7/dist-packages/salt/modules/timezone.py", line 209, in get_hwclock
    'Failed to parse timedatectl output, this is likely a bug'
CommandExecutionError: Failed to parse timedatectl output, this is likely a bug

[INFO    ] Completed state [America/Los_Angeles] at time 09:40:18.379639
local:
----------
          ID: America/Los_Angeles
    Function: timezone.system
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1542, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/states/timezone.py", line 72, in system
                  if __salt__['timezone.get_hwclock']() == 'localtime':
                File "/usr/lib/python2.7/dist-packages/salt/modules/timezone.py", line 209, in get_hwclock
                  'Failed to parse timedatectl output, this is likely a bug'
              CommandExecutionError: Failed to parse timedatectl output, this is likely a bug
     Started: 09:40:18.364498
    Duration: 15.141 ms
     Changes:

Summary
------------
Succeeded: 0
Failed:    1
```

**Comment by falzm** [comment]
I confirm this issue with Salt 2014.7.5 on Debian jessie.

**Comment by falzm** [comment]
After a bit of digging, it looks like this problem is triggered by the absence of dbus running on the server. Although only "recommended" by the systemd package, looks like some systemd-related features don't work (`timedatectl` included). Once dbus installed and started, the `timedatectl` command works and so does the `timezone.system` state...

**Comment by ksalman** [comment]
@falzm Thanks for debugging this! I'll close the bug since it's a Debian issue.
