### ISSUE TITLE
creating a VM fails using VMware cloud driver if devices have not been specified

### ISSUE THREAD

**Issue by nmadhok** [saltstack/salt#23247]
When cloning a VM using the VMware cloud driver, if the ``devices`` have not been specified, it raises ``UnboundLocalError: local variable 'specs' referenced before assignment``

```
[ERROR ] There was a profile error: local variable 'specs' referenced before assignment
Traceback (most recent call last):
File "/usr/lib/python2.6/site-packages/salt/cloud/cli.py", line 232, in run
self.config.get('names')
File "/usr/lib/python2.6/site-packages/salt/cloud/init.py", line 1324, in run_profile
ret[name] = self.create(vm_)
File "/usr/lib/python2.6/site-packages/salt/cloud/init.py", line 1194, in create
output = self.cloudsfunc
File "/usr/lib64/python2.6/contextlib.py", line 34, in exit
self.gen.throw(type, value, traceback)
File "/usr/lib/python2.6/site-packages/salt/utils/context.py", line 41, in func_globals_inject
yield
File "/usr/lib/python2.6/site-packages/salt/cloud/init.py", line 1194, in create
output = self.cloudsfunc
File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/vmware.py", line 1801, in create
if specs['nics_map']:
UnboundLocalError: local variable 'specs' referenced before assignment
```

**Comment by jfindlay** [comment]
Thanks, @nmadhok.
