### ISSUE TITLE
VMware salt-cloud driver fails to create a VM when trying to add a new network adapter

### ISSUE THREAD

**Issue by nmadhok** [saltstack/salt#23264]
```
[ERROR   ] Failed to create VM salt-oel-1. Configuration value 'Floppy drive 1' needs to be set
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 1249, in create
    output = self.clouds[func](vm_)
  File "/usr/lib64/python2.6/contextlib.py", line 34, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.6/site-packages/salt/utils/context.py", line 42, in func_globals_inject
    yield
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 1249, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/vmware.py", line 1824, in create
    specs = _manage_devices(devices, object_ref)
  File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/vmware.py", line 548, in _manage_devices
    switch_type = devices['network'][device.deviceInfo.label]['switch_type'] if 'switch_type' in devices['network'][device.deviceInfo.label] else ''
KeyError: 'Floppy drive 1'
```

Fix on it's way

**Comment by rallytime** [comment]
Thanks @nmadhok! Looks like your pull request should have already closed this one, so I'm going to close it now, if that's alright with you.
