### ISSUE TITLE
boto modules are something messing up

### ISSUE THREAD

**Issue by kiorky** [saltstack/salt#23277]
See on https://s3.amazonaws.com/archive.travis-ci.org/jobs/60723170/log.txt

```
salt.utils.decorators: TRACE: Unloading <module 'salt.loaded.int.module.test' from '/salt-venv/mastersalt/src/salt/salt/modules/test.py'>.<function missing_func at 0x67e2c80> because dependency (non_existantmodulename) is not imported
salt.loader: ERROR: Failed to import module boto_elb, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/salt-venv/mastersalt/src/salt/salt/loader.py", line 970, in _load_module
    ), fn_, fpath, desc)
  File "/salt-venv/mastersalt/src/salt/salt/modules/boto_elb.py", line 54, in <module>
    if (_LooseVersion(boto.__version__) <
AttributeError: 'module' object has no attribute '__version__'
```

**Comment by kiorky** [comment]
```
======================================================================
ERROR: test_settings (mc_states.tests.unit.modules.memcached_tests.TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/srv/mastersalt/makina-states/mc_states/tests/unit/modules/memcached_tests.py", line 19, in test_settings
    kinds=['modules']
  File "/srv/mastersalt/makina-states/mc_states/tests/unit/base.py", line 296, in patch
    mods = [a for a in self.dunders_[kind]]
  File "/salt-venv/mastersalt/src/salt/salt/utils/lazy.py", line 110, in __iter__
    self._load_all()
  File "/salt-venv/mastersalt/src/salt/salt/loader.py", line 1151, in _load_all
    self._load_module(name)
  File "/salt-venv/mastersalt/src/salt/salt/loader.py", line 1018, in _load_module
    module_init(self.opts)
  File "/salt-venv/mastersalt/src/salt/salt/modules/boto_vpc.py", line 113, in __init__
    __utils__['boto.assign_funcs'](__name__, 'vpc')
  File "/salt-venv/mastersalt/src/salt/salt/utils/lazy.py", line 98, in __getitem__
    raise KeyError(key)
KeyError: 'boto.assign_funcs'
-------------------- >> begin captured l
```
i also got this one

**Comment by kiorky** [comment]
the attached pr fixes the 2nd comment.
