### ISSUE TITLE
schedule.list RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by sambev** [saltstack/salt#23278]
When trying to run schedule.list on a minion with these versions:
```           
           Salt: 2015.2.0rc2-211-gda0bc48
         Python: 2.7.6 (default, Sep  9 2014, 15:04:36)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.5.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
```
I get 
```
    The minion function caused an exception: Traceback (most recent call last):
      File "/Users/sambev/projects/salt/salt/minion.py", line 1142, in _thread_return
        return_data = func(*args, **kwargs)
      File "/Users/sambev/projects/salt/salt/modules/schedule.py", line 81, in list_
        for item in schedule[job]:
    RuntimeError: dictionary changed size during iteration
```

**Comment by cachedout** [comment]
Fixed by #23279.
