### ISSUE TITLE
develop has broken modules

### ISSUE THREAD

**Issue by kiorky** [saltstack/salt#23281]
```
in', '/bin', '/usr/games', '/usr/local/games']
[DEBUG   ] Failed to import utils mako:
Traceback (most recent call last):
  File "/salt-venv/mastersalt/src/salt/salt/loader.py", line 970, in _load_module
    ), fn_, fpath, desc)
  File "/salt-venv/mastersalt/src/salt/salt/utils/mako.py", line 12, in <module>
    from mako.lookup import TemplateCollection, TemplateLookup  # pylint: disable=import-error
  File "/salt-venv/mastersalt/src/salt/salt/utils/mako.py", line 12, in <module>
    from mako.lookup import TemplateCollection, TemplateLookup  # pylint: disable=import-error
ImportError: No module named lookup
[DEBUG   ] Failed to import utils winservice:
Traceback (most recent call last):
  File "/salt-venv/mastersalt/src/salt/salt/loader.py", line 970, in _load_module
    ), fn_, fpath, desc)
  File "/salt-venv/mastersalt/src/salt/salt/utils/winservice.py", line 11, in <module>
    import win32serviceutil
ImportError: No module named win32serviceutil
[DEBUG   ] Failed to import utils winapi:
Traceback (most recent call last):
  File "/salt-venv/mastersalt/src/salt/salt/loader.py", line 970, in _load_module
    ), fn_, fpath, desc)
  File "/salt-venv/mastersalt/src/salt/salt/utils/winapi.py", line 7, in <module>
    import pythoncom
ImportError: No module named pythoncom
[DEBUG   ] Failed to import utils raetevent:
Traceback (most recent call last):
  File "/salt-venv/mastersalt/src/salt/salt/loader.py", line 970, in _load_module
    ), fn_, fpath, desc)
  File "/salt-venv/mastersalt/src/salt/salt/utils/raetevent.py", line 23, in <module>
    from raet import raeting, nacling
ImportError: No module named raet
[DEBUG   ] Failed to import utils raetlane:
Traceback (most recent call last):
  File "/salt-venv/mastersalt/src/salt/salt/loader.py", line 970, in _load_module
    ), fn_, fpath, desc)
  File "/salt-venv/mastersalt/src/salt/salt/utils/raetlane.py", line 62, in <module>
    from raet import raeting, nacling
ImportError: No module named raet
[DEBUG   ] Failed to import utils saltminionservice:
Traceback (most recent call last):
  File "/salt-venv/mastersalt/src/salt/salt/loader.py", line 970, in _load_module
    ), fn_, fpath, desc)
  File "/salt-venv/mastersalt/src/salt/salt/utils/saltminionservice.py", line 8, in <module>
    from salt.utils.winservice import Service, instart
  File "/salt-venv/mastersalt/src/salt/salt/utils/winservice.py", line 11, in <module>
    import win32serviceutil
ImportError: No module named win32serviceutil
```

**Comment by kiorky** [comment]
the problem resides of salt.utils namespace being loaded as regular salt modules, do we want now to protect off all those modules with some HAS_* then runtime/raise exceptions or virtual toggle off like in other modules ?

cc @thatch45 @s0undt3ch

**Comment by jfindlay** [comment]
@kiorky, are you still getting these errors?  I am not seeing them on the latest develop.

**Comment by kiorky** [comment]
that seems just stale...
