### ISSUE TITLE
VMware cloud driver create function fails with error if network not specified under devices or if network adapter is changed from distributed portgroup to standard network switch

### ISSUE THREAD

**Issue by nmadhok** [saltstack/salt#23301]
```
[INFO    ] [ salt-oel-1 ] Waiting for clone task to finish [0 s]
[INFO    ] [ salt-oel-1 ] Waiting for clone task to finish [5 s]
[INFO    ] [ salt-oel-1 ] Waiting for clone task to finish [10 s]
[INFO    ] [ salt-oel-1 ] Waiting for clone task to finish [15 s]
[INFO    ] [ salt-oel-1 ] Waiting for clone task to finish [20 s]
[INFO    ] [ salt-oel-1 ] Waiting for clone task to finish [25 s]
[INFO    ] [ salt-oel-1 ] Waiting for clone task to finish [30 s]
[ERROR   ] Error creating salt-oel-1: (vim.fault.NicSettingMismatch) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'fault.NicSettingMismatch.summary',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   numberOfNicsInSpec = 0,
   numberOfNicsInVM = 1
}
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/vmware.py", line 1975, in create
    _wait_for_task(task, vm_name, "clone", 5, 'info')
  File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/vmware.py", line 673, in _wait_for_task
    raise task.info.error
vim.fault.NicSettingMismatch: (vim.fault.NicSettingMismatch) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'fault.NicSettingMismatch.summary',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   numberOfNicsInSpec = 0,
   numberOfNicsInVM = 1
}
[ERROR   ] Caught Exception, terminating workers
TRACE: 'bool' object has no attribute 'pop'
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 54, in _call
    ret = func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 2188, in create_multiprocessing
    output.pop('deploy_kwargs', None)
AttributeError: 'bool' object has no attribute 'pop'



Error: There was a query error: Exception caught
Caught Exception, terminating workers
TRACE: 'bool' object has no attribute 'pop'
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 54, in _call
    ret = func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 2188, in create_multiprocessing
    output.pop('deploy_kwargs', None)
AttributeError: 'bool' object has no attribute 'pop'
```

Fix for this coming in soon!

**Comment by rallytime** [comment]
Thanks for the report and the fix, as always, @nmadhok!
