### ISSUE TITLE
Vmware cloud driver: exceptions must be old-style classes or derived from BaseException

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#23312]
Spinning up a VM results in:
```
[ERROR   ] Error creating testvm.example.com: exceptions must be old-style classes or derived from BaseException, not NoneType
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/vmware.py", line 1908, in create
    _wait_for_task(task, vm_name, "clone", 5, 'info')
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/vmware.py", line 608, in _wait_for_task
    raise task.info.error
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType
Error: There was a profile error: Failed to deploy VM
```

Debug (sanitized):
```
[DEBUG   ] Sending event - data = {'profile': 'vmware-ubuntu14.04', 'event': 'starting create', '_stamp': '2015-05-04T06:14:37.209518', 'name': 'testvm.example.com', 'provider': 'example-vmware:vmware'}
[WARNING ] Specified host: vmtest.example.com does not exist
[WARNING ] Using host used by the template ubuntu_1404_template
[DEBUG   ] Disks to create: []
[DEBUG   ] Networks to create: []
[DEBUG   ] SCSI adapters to create: ['SCSI controller 1']
[DEBUG   ] clone_spec set to (vim.vm.CloneSpec) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   location = (vim.vm.RelocateSpec) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      datastore = <unset>,
      diskMoveType = <unset>,
      pool = 'vim.ResourcePool:resgroup-283',
      host = <unset>,
      disk = (vim.vm.RelocateSpec.DiskLocator) [],
      transform = <unset>,
      deviceChange = (vim.vm.device.VirtualDeviceSpec) [],
      profile = (vim.vm.ProfileSpec) []
   },
   template = false,
   config = (vim.vm.ConfigSpec) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      changeVersion = <unset>,
      name = <unset>,
      version = <unset>,
      uuid = <unset>,
      instanceUuid = <unset>,
      npivNodeWorldWideName = (long) [],
      npivPortWorldWideName = (long) [],
      npivWorldWideNameType = <unset>,
      npivDesiredNodeWwns = <unset>,
      npivDesiredPortWwns = <unset>,
      npivTemporaryDisabled = <unset>,
      npivOnNonRdmDisks = <unset>,
      npivWorldWideNameOp = <unset>,
      locationId = <unset>,
      guestId = <unset>,
      alternateGuestName = <unset>,
      annotation = <unset>,
      files = <unset>,
      tools = <unset>,
      flags = <unset>,
      consolePreferences = <unset>,
      powerOpInfo = <unset>,
      numCPUs = 2,
      numCoresPerSocket = <unset>,
      memoryMB = 1024,
      memoryHotAddEnabled = <unset>,
      cpuHotAddEnabled = <unset>,
      cpuHotRemoveEnabled = <unset>,
      virtualICH7MPresent = <unset>,
      virtualSMCPresent = <unset>,
      deviceChange = (vim.vm.device.VirtualDeviceSpec) [
         (vim.vm.device.VirtualDeviceSpec) {
            dynamicType = <unset>,
            dynamicProperty = (vmodl.DynamicProperty) [],
            operation = 'edit',
            fileOperation = <unset>,
            device = (vim.vm.device.VirtualVmxnet3) {
               dynamicType = <unset>,
               dynamicProperty = (vmodl.DynamicProperty) [],
               key = 4000,
               deviceInfo = (vim.Description) {
                  dynamicType = <unset>,
                  dynamicProperty = (vmodl.DynamicProperty) [],
                  label = 'Network adapter 1',
                  summary = 'VM Network'
               },
               backing = (vim.vm.device.VirtualEthernetCard.NetworkBackingInfo) {
                  dynamicType = <unset>,
                  dynamicProperty = (vmodl.DynamicProperty) [],
                  deviceName = 'VM Network',
                  useAutoDetect = <unset>,
                  network = 'vim.Network:network-11',
                  inPassthroughMode = <unset>
               },
               connectable = (vim.vm.device.VirtualDevice.ConnectInfo) {
                  dynamicType = <unset>,
                  dynamicProperty = (vmodl.DynamicProperty) [],
                  startConnected = true,
                  allowGuestControl = true,
                  connected = false,
                  status = 'untried'
               },
               slotInfo = <unset>,
               controllerKey = 100,
               unitNumber = 7,
               addressType = 'assigned',
               macAddress = '00:50:56:97:13:38',
               wakeOnLanEnabled = true
            },
            profile = (vim.vm.ProfileSpec) []
         },
         (vim.vm.device.VirtualDeviceSpec) {
            dynamicType = <unset>,
            dynamicProperty = (vmodl.DynamicProperty) [],
            operation = 'add',
            fileOperation = <unset>,
            device = (vim.vm.device.ParaVirtualSCSIController) {
               dynamicType = <unset>,
               dynamicProperty = (vmodl.DynamicProperty) [],
               key = -1004,
               deviceInfo = (vim.Description) {
                  dynamicType = <unset>,
                  dynamicProperty = (vmodl.DynamicProperty) [],
                  label = 'SCSI controller 1',
                  summary = 'VMware paravirtual SCSI'
               },
               backing = <unset>,
               connectable = <unset>,
               slotInfo = <unset>,
               controllerKey = <unset>,
               unitNumber = <unset>,
               busNumber = 1,
               device = (int) [],
               hotAddRemove = <unset>,
               sharedBus = 'noSharing',
               scsiCtlrUnitNumber = <unset>
            },
            profile = (vim.vm.ProfileSpec) []
         }
      ],
      cpuAllocation = <unset>,
      memoryAllocation = <unset>,
      latencySensitivity = <unset>,
      cpuAffinity = <unset>,
      memoryAffinity = <unset>,
      networkShaper = <unset>,
      cpuFeatureMask = (vim.vm.ConfigSpec.CpuIdInfoSpec) [],
      extraConfig = (vim.option.OptionValue) [
         (vim.option.OptionValue) {
            dynamicType = <unset>,
            dynamicProperty = (vmodl.DynamicProperty) [],
            key = 'guestinfo.saltMaster',
            value = 'SNIP'
         },
         (vim.option.OptionValue) {
            dynamicType = <unset>,
            dynamicProperty = (vmodl.DynamicProperty) [],
            key = 'mem.hotadd',
            value = 'yes'
         },
         (vim.option.OptionValue) {
            dynamicType = <unset>,
            dynamicProperty = (vmodl.DynamicProperty) [],
            key = 'guestinfo.domain',
            value = 'example.com'
         }
      ],
      swapPlacement = <unset>,
      bootOptions = <unset>,
      vAppConfig = <unset>,
      ftInfo = <unset>,
      vAppConfigRemoved = <unset>,
      vAssertsEnabled = <unset>,
      changeTrackingEnabled = <unset>,
      firmware = <unset>,
      maxMksConnections = <unset>,
      guestAutoLockEnabled = <unset>,
      managedBy = <unset>,
      memoryReservationLockedToMax = <unset>,
      nestedHVEnabled = <unset>,
      vPMCEnabled = <unset>,
      scheduledHardwareUpgradeInfo = <unset>,
      vmProfile = (vim.vm.ProfileSpec) []
   },
   customization = (vim.vm.customization.Specification) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      options = <unset>,
      identity = (vim.vm.customization.LinuxPrep) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         hostName = (vim.vm.customization.FixedName) {
            dynamicType = <unset>,
            dynamicProperty = (vmodl.DynamicProperty) [],
            name = 'testvm'
         },
         domain = 'example.com',
         timeZone = <unset>,
         hwClockUTC = <unset>
      },
      globalIPSettings = (vim.vm.customization.GlobalIPSettings) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         dnsSuffixList = (str) [],
         dnsServerList = (str) [
            '8.8.8.8',
            '8.8.4.4'            
         ]
      },
      nicSettingMap = (vim.vm.customization.AdapterMapping) [
         (vim.vm.customization.AdapterMapping) {
            dynamicType = <unset>,
            dynamicProperty = (vmodl.DynamicProperty) [],
            macAddress = <unset>,
            adapter = (vim.vm.customization.IPSettings) {
               dynamicType = <unset>,
               dynamicProperty = (vmodl.DynamicProperty) [],
               ip = (vim.vm.customization.FixedIp) {
                  dynamicType = <unset>,
                  dynamicProperty = (vmodl.DynamicProperty) [],
                  ipAddress = '10.0.0.10'
               },
               subnetMask = '255.255.254.0',
               gateway = (str) [
                  '10.0.0.1'
               ],
               ipV6Spec = <unset>,
               dnsServerList = (str) [],
               dnsDomain = 'example.com',
               primaryWINS = <unset>,
               secondaryWINS = <unset>,
               netBIOS = <unset>
            }
         }
      ],
      encryptionKey = (byte) []
   },
   powerOn = true,
   snapshot = <unset>,
   memory = <unset>
}

[INFO    ] Creating testvm.example.com from template(ubuntu_1404_template)

[DEBUG   ] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event - data = {'_stamp': '2015-05-04T06:14:48.065103', 'event': 'requesting instance', 'kwargs': {'profile': 'vmware-ubuntu14.04', 'domain': 'example.com', 'dns_servers': ['8.8.8.8', '8.8.4.4'], 'deploy': True, 'minion': {'master': 'SNIP'}, 'ssh_username': 'example', 'provider': 'example-vmware:vmware', 'resourcepool': 'Resources', 'cluster': 'example', 'host': 'vmtest.example.com', 'priv_key': '-----BEGIN RSA PRIVATE KEY-----\nSNIP-----END RSA PRIVATE KEY-----\n', 'datastore': 'vmexp01:storage1', 'password': 'SNIP', 'pub_key': '-----BEGIN PUBLIC KEY-----\nSNIP-----END PUBLIC KEY-----\n', 'private_key': '/root/.ssh/id_rsa', 'public_key': '/root/.ssh/id_rsa.pub', 'name': 'testvm.example.com', 'clonefrom': 'ubuntu_1404_template', 'num_cpus': 2, 'devices': {'scsi': {'SCSI controller 1': {'type': 'paravirtual'}}, 'disk': {'Hard disk 1': {'size': 15}}, 'network': {'Network adapter 1': {'switch_type': 'standard', 'subnet_mask': '255.255.0.0', 'domain': 'example.com', 'name': 'VM Network', 'ip': '10.0.0.10', 'gateway': ['10.0.0.1']}}}, 'power_on': True, 'datacenter': 'example', 'template': False, 'memory': 1024, 'folder': 'vm', 'os': 'bootstrap-salt', 'extra_config': {'guestinfo.saltMaster': 'SNIP', 'guestinfo.domain': 'example.com', 'mem.hotadd': 'yes'}}}
[ERROR   ] Error creating testvm.example.com: exceptions must be old-style classes or derived from BaseException, not NoneType
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/vmware.py", line 1908, in create
    _wait_for_task(task, vm_name, "clone", 5, 'info')
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/vmware.py", line 608, in _wait_for_task
    raise task.info.error
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType
Error: There was a profile error: Failed to deploy VM
```

Profile (sanitized):
```
vmware-ubuntu14.04:
  provider: example-vmware
  clonefrom: ubuntu_1404_template

  ## Optional arguments
  num_cpus: 2
  memory: 1024
  devices:
    disk:
      Hard disk 1:
        size: 15
    network:
      Network adapter 1:
        ip: 10.0.0.10
        gateway: [10.0.0.1]
        subnet_mask: 255.255.0.0
        domain: example.com
        name: VM Network
        switch_type: standard
    scsi:
      SCSI controller 1:
        type: paravirtual

  domain: example.com
  dns_servers:
    - 8.8.8.8
    - 8.8.4.4

  # If cloning from template, either resourcepool or cluster MUST be specified!
  resourcepool: Resources
  cluster: example

  datastore: 'vmexp01:storage1'
  folder: vm
  datacenter: example
  host: vmtest.example.com
  template: False
  power_on: True
  extra_config:
    mem.hotadd: 'yes'
    guestinfo.saltMaster: SNIP
    guestinfo.domain: example.com

  deploy: True
  public_key: /root/.ssh/id_rsa.pub
  private_key: /root/.ssh/id_rsa
  ssh_username: example
  password: 'SNIP'
  minion:
    master: SNIP
```

**Comment by nmadhok** [comment]
@syphernl For some reason I couldn't reproduce this using the profile above. I have submitted a patch for the error you're getting though. Can you try the patch from the PR above and let me know?

**Comment by syphernl** [comment]
@nmadhok I'm using Ubuntu 14.04 (amd64) with Salt stable from the PPA if that makes any difference.

Regarding `public_key`: Where does it get a/the public_key from then? 
I haven't had any issues with the `datastore` setting. This particular value was as it was given by the `list_datastores` function.

The patch for #23314 has solved this problem as it no longer fails with the error.

**Comment by nmadhok** [comment]
@syphernl Does it successfully complete after applying the patch from #23314 ?

**Comment by syphernl** [comment]
@nmadhok The cloning part works, but it never gets an IP so its stuck at "Waiting to get IP information". The NIC is not "Connected" nor "Connect at power on" but that is unrelated to this ticket I guess.

**Comment by nmadhok** [comment]
@syphernl That is another issue. Do you have vmware-tools installed on your template? The IP information would be available once the VMware tools starts running on your VM when it get's deployed. Make sure you template has the RHEL/CentOS equivalent of the file ``/etc/sysconfig/network`` which contains the following:
```
NETWORKING=yes
PERSIST=yes
```

**Comment by syphernl** [comment]
No, the actual NIC is not set to "connected" in VMware. If I manually "connect" it, it works fine.
I can open a new ticket for that if that's preferred.

**Comment by nmadhok** [comment]
That would be great!

**Comment by syphernl** [comment]
@nmadhok Done: #23315

**Comment by CedNantes** [comment]
I know this issue is closed but... if i'm using the same profile i get :

The following exception was thrown by libcloud when trying to run the initial deployment:
'image'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/vsphere.py", line 221, in create
    template = conn.get_vm_by_name(vm_['image'])
KeyError: 'image'
Error: There was a profile error: Failed to deploy VM

what's "image" supposed to mean ?

**Comment by nmadhok** [comment]
@CedNantes Looking at the traceback, it looks like you're still using the old vsphere driver instead of the vmware driver which makes sense if you're using a stable version of Salt. The vmware cloud driver will be available in the Beryllium release of Salt. If you want to use the vmware cloud driver, you can either update the salt version you're running to the latest salt develop version or you can simply put this driver at ``site-packages/salt/cloud/clouds/vmware.py`` while still using your current Salt version and you should be able to use the driver functionality without having to update to the latest salt develop version. 

You can ``curl/wget`` the driver from https://raw.githubusercontent.com/saltstack/salt/develop/salt/cloud/clouds/vmware.py

Does that answer your question?

**Comment by CedNantes** [comment]
Thanks for the answer, i'm currently trying the vmware.py driver since the old ones let me duplicate from a template but won't let me change ip address or add and customize devices. I could only get a simple clone. Now with the vmware.py driver i suppose i've to change the provider in /etc/salt/cloud.providers/vmware.conf from "vsphere" to "vmware" but it's causing me an "invalid username/password" issue when i'm trying to launch a salt-cloud command. I tried something like this : 

# the one using vsphere and working with image
Vcenter01:
  provider: vsphere
  user: myuser
  password: mypassword
  url: https://MyVcenterIP/sdk

# the one using vmware and giving username/password issues
Vcenter02:
  provider: vmware
  user: myuser
  password: mypassword
  url: https://MyVcenterIP/sdk

Many thanks for your answers !

**Comment by nmadhok** [comment]
@CedNantes See how to see the provider configuration and other things needed in the docs. http://docs.saltstack.com/en/latest/topics/cloud/vmware.html and http://docs.saltstack.com/en/latest/ref/clouds/all/salt.cloud.clouds.vmware.html

The way to set up the provider configuration for vmware cloud driver as mentioned in the link provided above is:
```
vmware-vcenter01:
provider: vmware
user: myuser
password: mypassword
url: vcenter01.domain.com
```

You don't need to specify ``https://`` or sdk or anything.

**Comment by CedNantes** [comment]
well i'm not using any dns server so it was a tricky case but now it works.
Using IP address into url wasn't working but adding 'myip  vcenter' into /etc/hosts and then using url: vcenter works like a charm ! Thanks again ! I'm off to some further testing !

**Comment by nmadhok** [comment]
@CedNantes Instead of adding ``'myip vcenter`` into ``/etc/hosts``, can you try and quote your IP in the provider config and try again?

```
vmware-vcenter01:
provider: vmware
user: myuser
password: "mypassword"
url: "10.20.30.40"
```

**Comment by CedNantes** [comment]
It's working ! Good to know.

**Comment by nmadhok** [comment]
@CedNantes Thanks for confirming!
