### ISSUE TITLE
LazyLoader logic is broken; raise innapropriate AttributeError

### ISSUE THREAD

**Issue by kiorky** [saltstack/salt#23317]
reopening of #22940 which didnt come with a fix.

You can easily come to such situations 

```
Traceback (most recent call last):
  File "/salt-venv/salt/local/lib/python2.7/site-packages/mock.py", line 1638, in __enter__
    self._patch_dict()
  File "/salt-venv/salt/local/lib/python2.7/site-packages/mock.py", line 1647, in _patch_dict
    original = in_dict.copy()
  File "/salt-venv/salt/src/salt/salt/utils/lazy.py", line 113, in __getattr__
    raise KeyError(name)
KeyError: 'copy'

```

(please reread this comment: https://github.com/saltstack/salt/pull/22940#issuecomment-95261091)

**Comment by jfindlay** [comment]
@kiorky, thanks for researching this issue.  I have read your linked comment but am not familiar with the details enough to understand.  Is it possible for you to create a minimal working example to demonstrate the problem you're seeing?

**Comment by kiorky** [comment]
all the details are on the linked closed pull request.
