### ISSUE TITLE
Pillar merge code is broken in 2014.7.5

### ISSUE THREAD

**Issue by ross-p** [saltstack/salt#23336]
I have a pillar that works great on salt-master `2014.7.3`.  However when I upgrade the salt-master to `2014.7.5` it starts giving me the following error:

```text
[ERROR   ] Error in function _pillar:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 1348, in run_func
    ret = getattr(self, func)(load)
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 1106, in _pillar
    data = pillar.compile_pillar(pillar_dirs=pillar_dirs)
  File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 578, in compile_pillar
    pillar, errors = self.render_pillar(matches)
  File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 464, in render_pillar
    pillar = self.merge_sources(pillar, pstate)
  File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 559, in merge_sources
    merged = merge_recurse(obj_a, obj_b)
  File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 31, in merge_recurse
    return update(copied, obj_b)
  File "/usr/lib/python2.7/dist-packages/salt/utils/dictupdate.py", line 14, in update
    ret = update(dest.get(key, {}), val)
  File "/usr/lib/python2.7/dist-packages/salt/utils/dictupdate.py", line 14, in update
    ret = update(dest.get(key, {}), val)
AttributeError: 'NoneType' object has no attribute 'get'
```

Unfortunately it doesn't give any indication where that error actually occurred as far as my source pillar is concerned.  (There is a lot of data in this source pillar, and it's sensitive stuff, so I can't just post it here without working at it).

On the client side I then see this message in salt-minion error log:

```text
2015-05-04 17:32:33,749 [salt.pillar      ][ERROR   ] Got a bad pillar from master, type str, expecting dict:
```

Sorry I don't have more details at the moment.  As it stands though, 2014.7.5 is completely broken for me due to this pillar merging problem.

**Comment by ross-p** [comment]
Another note, whatever `2014.7.5` did wrong, it corrupted my salt cache.  Even after downgrading to `2014.7.3` I was getting the same error.  I had to nuke `/var/cache/salt` to get it to start working again after downgrading.

**Comment by ross-p** [comment]
Erroneous issue, this looks like it's something having to do with the different cloud environment I'm running in, not with the Salt version.  Probably a pillar error, sorry for the false alarm.

**Comment by rallytime** [comment]
@ross-p Glad you got it figured out! :)
