### ISSUE TITLE
Runners cause traceback in state.orchestrate

### ISSUE THREAD

**Issue by techhat** [saltstack/salt#23356]
Any time I run any orchestration using any number of runners, I get the following traceback after all of the runners are finished:
```
Exception occurred in runner state.orch: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 335, in low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/runners/state.py", line 117, in orchestrate
    __jid_event__.fire_event({'data': ret, 'outputter': 'highstate'}, 'progress')
ReferenceError: weakly-referenced object no longer exists
```
This is on develop:
```
# salt-run --versions-report
Salt Version:
           Salt: 2015.2.0
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.22
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
         Python: 2.7.9 (default, Dec 11 2014, 04:42:00)
           RAET: Not Installed
            ZMQ: 4.0.5
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
       pycrypto: 2.6.1
 
System Versions:
           dist:   
        machine: x86_64
        release: 4.0.1-1-ARCH
```
To duplicate, create a runner at mytest.py:
```
def ping():
    return True
```
Create a runnertest.sls:
```
mytest.ping:
  salt.runner
```
Run it with the orchestrator:
```
# salt-run state.orch runnertest
True
Exception occurred in runner state.orch: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 335, in low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/runners/state.py", line 117, in orchestrate
    __jid_event__.fire_event({'data': ret, 'outputter': 'highstate'}, 'progress')
ReferenceError: weakly-referenced object no longer exists
```

**Comment by tnypex** [comment]
Same issue with 2015.2.0rc2

```
# salt-run --versions-report
           Salt: 2015.2.0rc2
         Python: 2.6.6 (r266:84292, Nov 21 2013, 10:50:32)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.4.4
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed
```

**Comment by cachedout** [comment]
This is still an issue on the head of 2015.2

**Comment by cachedout** [comment]
There's no need to have a jid event fire in this case. I removed it in #23423

**Comment by tnypex** [comment]
It fixes the issue for me. thanks.

**Comment by cachedout** [comment]
Sounds good, @tnypex. I'll go ahead and close this.
