### ISSUE TITLE
Route53 check creates too many requests when highstate is called within multiple instances

### ISSUE THREAD

**Issue by Reiner030** [saltstack/salt#23358]
Hello,

perhaps this behavior is already fixed by new patches for https://github.com/saltstack/salt/issues/18720 or by patch of issue https://github.com/saltstack/salt/issues/23034 ...
I am using 2014.7.5 (Helium) /actual Debian packet and have in 15 instances about :

```
# salt '*' grains.get alternate_dns  | wc -l
52
```

=> ~ 150 entries (I create each the public zone and 1 internal/external A record entry in an .internal and .external zone to have the real IP for internal/external configurations available on my instances)

Even when all entries are setup I get in a full run without batch mode since some days (perhaps because of new AWS IAM profile rules?):

```
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1542, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/states/boto_route53.py", line 132, in present
                  profile)
                File "/usr/lib/python2.7/dist-packages/salt/modules/boto_route53.py", line 77, in get_record
                  _zone = conn.get_zone(zone)
                File "/usr/local/lib/python2.7/dist-packages/boto/route53/connection.py", line 546, in get_zone
                  for zone in self.get_zones():
                File "/usr/local/lib/python2.7/dist-packages/boto/route53/connection.py", line 559, in get_zones
                  zones = self.get_all_hosted_zones()
                File "/usr/local/lib/python2.7/dist-packages/boto/route53/connection.py", line 126, in get_all_hosted_zones
                  body)
              DNSServerError: DNSServerError: 400 Bad Request
              <?xml version="1.0"?>
              <ErrorResponse xmlns="https://route53.amazonaws.com/doc/2013-04-01/"><Error><Type>Sender</Type><Code>Throttling</Code><Message>Rate exceeded</Message></Error><RequestId>1723b95b-f2bf-11e4-b864-33bc3e543038</RequestId></ErrorResponse>
```

**Comment by jfindlay** [comment]
@Reiner030, thanks for the report.  I am not sure what is going on here, but it seems that the code here could be optimized in order to avoid this.
