### ISSUE TITLE
salt-ssh fails on CentOS 7 when python-zmq is not installed

### ISSUE THREAD

**Issue by jfindlay** [saltstack/salt#23503]
### setup
```console
# salt-cloud -l debug --no-deploy -p linode-centos-7 jmoney-centos-7
...
jmoney-centos-7:
    ----------
    Error:
        ----------
        No Deploy:
            'deploy' is not enabled. Not deploying.
    _uuid:
        None
    driver:
    extra:
        ...
    id:
        997729
    image:
        None
    name:
        jmoney-centos-7
    private_ips:
    public_ips:
        - <IP>
    size:
        None
    state:
        3
```
```console
# cat > /etc/salt/roster
jmoney-centos-7:
  host: <IP>
  user: root
  passwd: <passwd>
```

### test.ping
```console
# salt-ssh -i jmoney-centos-7 test.ping
jmoney-centos-7:
    ----------
    retcode:
        1
    stderr:
        Traceback (most recent call last):
          File "/tmp/.root_bc136f_salt/salt-call", line 4, in <module>
            salt_call()
          File "/tmp/.root_bc136f_salt/salt/scripts.py", line 218, in salt_call
            import salt.cli.call
          File "/tmp/.root_bc136f_salt/salt/cli/call.py", line 6, in <module>
            from salt.utils import parsers
          File "/tmp/.root_bc136f_salt/salt/utils/parsers.py", line 26, in <module>
            import salt.config as config
          File "/tmp/.root_bc136f_salt/salt/config.py", line 39, in <module>
            import salt.utils.sdb
          File "/tmp/.root_bc136f_salt/salt/utils/sdb.py", line 9, in <module>
            import salt.loader
          File "/tmp/.root_bc136f_salt/salt/loader.py", line 24, in <module>
            import salt.utils.event
          File "/tmp/.root_bc136f_salt/salt/utils/event.py", line 80, in <module>
            import salt.payload
          File "/tmp/.root_bc136f_salt/salt/payload.py", line 17, in <module>
            import salt.crypt
          File "/tmp/.root_bc136f_salt/salt/crypt.py", line 35, in <module>
            import salt.transport.client
          File "/tmp/.root_bc136f_salt/salt/transport/client.py", line 12, in <module>
            from salt.utils.async import SyncWrapper
          File "/tmp/.root_bc136f_salt/salt/utils/async.py", line 10, in <module>
            import zmq.eventloop.ioloop
        ImportError: No module named zmq.eventloop.ioloop
    stdout:
```

### jmoney-centos-7
```console
# yum -y install epel-release
# yum makecache
# yum -y install python-zmq
```

### test.ping again
```console
# salt-ssh -i jmoney-centos-7 test.ping
jmoney-centos-7:
    True
```

### versions
```console
# salt --versions
Salt Version:
           Salt: 2015.5.0-1234-g58dcd13
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
           Mako: 1.0.0
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
            ZMQ: 4.0.5
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
       pycrypto: 2.6.1
 
System Versions:
           dist: debian 8.0 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.0 
```

**Comment by jfindlay** [comment]
This may be a separate issue, but I'm getting a similar problem with opensuse 13 and elementtree.
```console
# salt-ssh -i jmoney-opensuse-7 test.ping
jmoney-opensuse-7:
    ----------
    retcode:
        1
    stderr:
        Traceback (most recent call last):
          File "/tmp/.root_bc136f_salt/salt-call", line 4, in <module>
            salt_call()
          File "/tmp/.root_bc136f_salt/salt/scripts.py", line 218, in salt_call
            import salt.cli.call
          File "/tmp/.root_bc136f_salt/salt/cli/call.py", line 6, in <module>
            from salt.utils import parsers
          File "/tmp/.root_bc136f_salt/salt/utils/parsers.py", line 26, in <module>
            import salt.config as config
          File "/tmp/.root_bc136f_salt/salt/config.py", line 34, in <module>
            import salt.utils.network
          File "/tmp/.root_bc136f_salt/salt/utils/network.py", line 32, in <module>
            from salt._compat import subprocess
          File "/tmp/.root_bc136f_salt/salt/_compat.py", line 31, in <module>
            import elementtree.ElementTree as ElementTree
        ImportError: No module named elementtree.ElementTree
    stdout:
```

**Comment by basepi** [comment]
I'm guessing I fixed this one when I fixed some other ZMQ imports, but I could be wrong.

**Comment by basepi** [comment]
Yep, I can no longer reproduce on cent7. Let me test the opensuse one

**Comment by basepi** [comment]
And.....apparently the opensuse version of python doesn't ship with the xml library. Wat? Guess we'll try shipping it down with the thin. Seems to be working in my preliminary tests.

**Comment by basepi** [comment]
Done in #24515.
