### ISSUE TITLE
NameError: global name '__salt_system_encoding__' is not defined after upgraded to salt-2015.5.0

### ISSUE THREAD

**Issue by Whissi** [saltstack/salt#23520]
After I upgraded the salt master from 2014.7.5 to 2015.5.0 I got the following errors in my log:

```
2015-05-10 12:57:55,001 [salt.loader                                 ][CRITICAL] Failed to load grains defined in grain file core.locale_info in function <function locale_info at 0x7f78e7363ed8>, error:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/salt/loader.py", line 1249, in gen_grains
    # Key errors come out of the virtual function when passing
  File "/usr/lib64/python2.7/site-packages/salt/grains/core.py", line 1300, in locale_info
    grains['locale_info']['detectedencoding'] = __salt_system_encoding__
NameError: global name '__salt_system_encoding__' is not defined
2015-05-10 12:57:55,215 [salt.loader                                 ][ERROR   ] The module 'salt.loaded.int.module.nacl' is showing some bad usage. It's __virtualname__ attribute is set to 'nacl' yet the __virtual__() function is returning (False, 'libnacl import error, perhaps missing python libnacl package'). These values should match!
2015-05-10 12:57:55,292 [salt.loader                                 ][ERROR   ] Failed to read the virtual function for module: npm
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/salt/loader.py", line 1129, in process_virtual
    Apply the __outputter__ variable to the functions
  File "/usr/lib64/python2.7/site-packages/salt/utils/__init__.py", line 1904, in warn_until
    Helper function to raise a warning (by default, a ``DeprecationWarning``)
RuntimeError: The warning triggered on filename '/usr/lib64/python2.7/site-packages/salt/loader.py', line number 1129, is supposed to be shown until version 2014.1.0 (Hydrogen) is released. Current version is now 2014.7.5 (Helium). Please remove the warning.
2015-05-10 12:57:55,323 [salt.loader                                 ][ERROR   ] The module 'salt.loaded.int.module.ipmi' is showing some bad usage. It's __virtualname__ attribute is set to 'ipmi' yet the __virtual__() function is returning (False, 'No module named pyghmi.ipmi'). These values should match!
2015-05-10 12:59:06,638 [salt.loader                                 ][CRITICAL] Failed to load grains defined in grain file core.locale_info in function <function locale_info at 0x7f78e5b56f50>, error:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/salt/loader.py", line 1249, in gen_grains
    # Key errors come out of the virtual function when passing
  File "/usr/lib64/python2.7/site-packages/salt/grains/core.py", line 1300, in locale_info
    grains['locale_info']['detectedencoding'] = __salt_system_encoding__
NameError: global name '__salt_system_encoding__' is not defined
2015-05-10 12:59:06,772 [salt.loader                                 ][ERROR   ] The module 'salt.loaded.int.module.nacl' is showing some bad usage. It's __virtualname__ attribute is set to 'nacl' yet the __virtual__() function is returning (False, 'libnacl import error, perhaps missing python libnacl package'). These values should match!
2015-05-10 12:59:06,850 [salt.loader                                 ][ERROR   ] Failed to read the virtual function for module: npm
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/salt/loader.py", line 1129, in process_virtual
    Apply the __outputter__ variable to the functions
  File "/usr/lib64/python2.7/site-packages/salt/utils/__init__.py", line 1904, in warn_until
    Helper function to raise a warning (by default, a ``DeprecationWarning``)
RuntimeError: The warning triggered on filename '/usr/lib64/python2.7/site-packages/salt/loader.py', line number 1129, is supposed to be shown until version 2014.1.0 (Hydrogen) is released. Current version is now 2014.7.5 (Helium). Please remove the warning.
2015-05-10 12:59:06,876 [salt.loader                                 ][ERROR   ] The module 'salt.loaded.int.module.ipmi' is showing some bad usage. It's __virtualname__ attribute is set to 'ipmi' yet the __virtual__() function is returning (False, 'No module named pyghmi.ipmi'). These values should match!
2015-05-10 13:00:18,252 [salt.loader                                 ][CRITICAL] Failed to load grains defined in grain file core.locale_info in function <function locale_info at 0x7f78e14041b8>, error:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/salt/loader.py", line 1249, in gen_grains
    # Key errors come out of the virtual function when passing
  File "/usr/lib64/python2.7/site-packages/salt/grains/core.py", line 1300, in locale_info
    grains['locale_info']['detectedencoding'] = __salt_system_encoding__
NameError: global name '__salt_system_encoding__' is not defined
2015-05-10 13:00:18,392 [salt.loader                                 ][ERROR   ] The module 'salt.loaded.int.module.nacl' is showing some bad usage. It's __virtualname__ attribute is set to 'nacl' yet the __virtual__() function is returning (False, 'libnacl import error, perhaps missing python libnacl package'). These values should match!
2015-05-10 13:00:18,469 [salt.loader                                 ][ERROR   ] Failed to read the virtual function for module: npm
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/salt/loader.py", line 1129, in process_virtual
    Apply the __outputter__ variable to the functions
  File "/usr/lib64/python2.7/site-packages/salt/utils/__init__.py", line 1904, in warn_until
    Helper function to raise a warning (by default, a ``DeprecationWarning``)
RuntimeError: The warning triggered on filename '/usr/lib64/python2.7/site-packages/salt/loader.py', line number 1129, is supposed to be shown until version 2014.1.0 (Hydrogen) is released. Current version is now 2014.7.5 (Helium). Please remove the warning.
2015-05-10 13:00:18,498 [salt.loader                                 ][ERROR   ] The module 'salt.loaded.int.module.ipmi' is showing some bad usage. It's __virtualname__ attribute is set to 'ipmi' yet the __virtual__() function is returning (False, 'No module named pyghmi.ipmi'). These values should match!
2015-05-10 13:01:29,861 [salt.loader                                 ][CRITICAL] Failed to load grains defined in grain file core.locale_info in function <function locale_info at 0x7f78e7021b18>, error:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/salt/loader.py", line 1249, in gen_grains
    # Key errors come out of the virtual function when passing
  File "/usr/lib64/python2.7/site-packages/salt/grains/core.py", line 1300, in locale_info
    grains['locale_info']['detectedencoding'] = __salt_system_encoding__
NameError: global name '__salt_system_encoding__' is not defined
2015-05-10 13:01:30,000 [salt.loader                                 ][ERROR   ] The module 'salt.loaded.int.module.nacl' is showing some bad usage. It's __virtualname__ attribute is set to 'nacl' yet the __virtual__() function is returning (False, 'libnacl import error, perhaps missing python libnacl package'). These values should match!
2015-05-10 13:01:30,077 [salt.loader                                 ][ERROR   ] Failed to read the virtual function for module: npm
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/salt/loader.py", line 1129, in process_virtual
    Apply the __outputter__ variable to the functions
  File "/usr/lib64/python2.7/site-packages/salt/utils/__init__.py", line 1904, in warn_until
    Helper function to raise a warning (by default, a ``DeprecationWarning``)
RuntimeError: The warning triggered on filename '/usr/lib64/python2.7/site-packages/salt/loader.py', line number 1129, is supposed to be shown until version 2014.1.0 (Hydrogen) is released. Current version is now 2014.7.5 (Helium). Please remove the warning.
2015-05-10 13:01:30,106 [salt.loader                                 ][ERROR   ] The module 'salt.loaded.int.module.ipmi' is showing some bad usage. It's __virtualname__ attribute is set to 'ipmi' yet the __virtual__() function is returning (False, 'No module named pyghmi.ipmi'). These values should match!
2015-05-10 13:02:41,426 [salt.loader                                 ][CRITICAL] Failed to load grains defined in grain file core.locale_info in function <function locale_info at 0x7f78e4a7eb18>, error:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/salt/loader.py", line 1249, in gen_grains
    # Key errors come out of the virtual function when passing
  File "/usr/lib64/python2.7/site-packages/salt/grains/core.py", line 1300, in locale_info
    grains['locale_info']['detectedencoding'] = __salt_system_encoding__
NameError: global name '__salt_system_encoding__' is not defined
2015-05-10 13:02:41,564 [salt.loader                                 ][ERROR   ] The module 'salt.loaded.int.module.nacl' is showing some bad usage. It's __virtualname__ attribute is set to 'nacl' yet the __virtual__() function is returning (False, 'libnacl import error, perhaps missing python libnacl package'). These values should match!
2015-05-10 13:02:41,641 [salt.loader                                 ][ERROR   ] Failed to read the virtual function for module: npm
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/salt/loader.py", line 1129, in process_virtual
    Apply the __outputter__ variable to the functions
  File "/usr/lib64/python2.7/site-packages/salt/utils/__init__.py", line 1904, in warn_until
    Helper function to raise a warning (by default, a ``DeprecationWarning``)
RuntimeError: The warning triggered on filename '/usr/lib64/python2.7/site-packages/salt/loader.py', line number 1129, is supposed to be shown until version 2014.1.0 (Hydrogen) is released. Current version is now 2014.7.5 (Helium). Please remove the warning.
2015-05-10 13:02:41,670 [salt.loader                                 ][ERROR   ] The module 'salt.loaded.int.module.ipmi' is showing some bad usage. It's __virtualname__ attribute is set to 'ipmi' yet the __virtual__() function is returning (False, 'No module named pyghmi.ipmi'). These values should match!
```

**Comment by s0undt3ch** [comment]
What OS is this?

**Comment by Whissi** [comment]
On Gentoo Linux:
```
# salt-call --versions-report
           Salt: 2015.5.0
         Python: 2.7.9 (default, Feb  8 2015, 01:34:33)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.5.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
```
But only happen on first start of the master after the upgrade. I stopped the master, cleaned the log file and started the master again -> log is empty.

**Comment by s0undt3ch** [comment]
Was the master restarted on the upgrade? Could there be some hanging processes still running?

**Comment by Whissi** [comment]
The system was running salt-2014.7.5 when it was upgraded to salt-2015.5.0 (salt-master was **not** stopped). After salt-2015.5.0 got installed we rebooted the whole system. So shutdown stopped salt-2014.7.5 and on boot salt-2015.5.0 was started the first time.

Shutdown logs don't indicate that there was a problem when stopping salt.

**Comment by jfindlay** [comment]
I have also seen this error on 2015.5.0.

**Comment by singularo** [comment]
Happened to me on a debian machine.

```
dpkg-reconfigure locales
/etc/init.d/salt-minion stop
/etc/init.d/salt-minion start
```

Seemed to resolve it.

**Comment by flantel** [comment]
@singularo This worked for me too. Thanks!

**Comment by Lothiraldan** [comment]
@singularo Didn't worked for me :(

Ubuntu 14.04.1

**Comment by fangpeishi** [comment]
Restart salt-minion can solve this problem.

**Comment by Lothiraldan** [comment]
I fixed the problem by stop the salt-minion with "/etc/init.d/salt-minion stop" and kill every salt-minion remaining process

**Comment by sygibson** [comment]
I ran in to this issue with 2015.5.2-2 on CentOS 7.0 minions as well.  I had to stop / start the salt-minion service and it worked fine.

**Comment by srodrig0209** [comment]
Happened to me on Amazon Linux. Restart salt-minions as @sygibson did and it resolved my issue.
