### ISSUE TITLE
when I run as  salt-ssh \* state.sls test pillar='{"hello":"hello"}' ,The following error occurred,but I run as salt \* state.sls test pillar='{"hello":"hello"}' is ok ,this is why 

### ISSUE THREAD

**Issue by double-yaya** [saltstack/salt#23536]
```
salt-ssh  \test  state.sls test pillar=‘{“hello”:“hello”}’
[WARNING ] Unable to bind socket, error: [Errno 98] Address already in use
Process Process-1:
Traceback (most recent call last):
 File "/usr/lib64/python2.6/multiprocessing/process.py", line 232, in _bootstrap
    self.run()
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 88, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.6/site-packages/salt/client/ssh/__init__.py", line 321, in handle_routine
    stdout, stderr, retcode = single.run()
  File "/usr/lib/python2.6/site-packages/salt/client/ssh/__init__.py", line 569, in run
    stdout, stderr, retcode = self.run_wfunc()
  File "/usr/lib/python2.6/site-packages/salt/client/ssh/__init__.py", line 641, in run_wfunc
    ret = json.dumps(self.wfuncs[self.fun](*self.arg, **self.kwargs))
  File "/usr/lib/python2.6/site-packages/salt/client/ssh/wrapper/state.py", line 40, in sls
     __pillar__.update(kwargs.get('pillar', {}))
ValueError: dictionary update sequence element #0 has length 1; 2 is required

salt --versions-report
       Salt: 2014.1.4
     Python: 2.6.6 (r266:84292, May  1 2012, 13:52:17)
     Jinja2: 2.2.1
   M2Crypto: 0.20.2
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
      pycrypto: 2.0.1
         PyYAML: 3.10
          PyZMQ: 2.2.0.1
            ZMQ: 3.2.4
```

**Comment by jfindlay** [comment]
@double-yaya 2014.1.4 is a very old release.  Do you have the same problem after upgrading to 2015.5.0?

**Comment by double-yaya** [comment]
@jfindlay 7.2 version of the test results are correct,but with list target execution error like this

salt-ssh -L 'dy,test' test.ping
No hosts found with target ['dy', 'test'] of type list

```salt-master --versions-report
           Salt: 2014.7.2
         Python: 2.6.6 (r266:84292, May  1 2012, 13:52:17)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 2.2.0.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed
```
