### ISSUE TITLE
Upgrade saltmaster to 2015.5.0 on centos 6.5 fails

### ISSUE THREAD

**Issue by andrejohansson** [saltstack/salt#23652]
Running the official vmdepot image of the saltmaster I tried to update the saltmaster using pip like this (since packages didn't seem to be available on yum):

## Version of master before
```
[root@vmdepot-saltm saltop]# salt --versions-report
           Salt: 2014.7.5
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.4.4
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.5.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
```

## Result of install:
```
[root@vmdepot-saltm saltop]# pip install salt --upgrade                                                                              
/usr/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext ob
ject is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For mo
re information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.                                 
  InsecurePlatformWarning                                                                                                            
Collecting salt                                                                                                                      
  Downloading salt-2015.5.0.tar.gz (4.4MB)                                                                                           
    100% |████████████████████████████████| 4.4MB 39kB/s                                                                             
Collecting Jinja2 (from salt)                                                                                                        
  Downloading Jinja2-2.7.3.tar.gz (378kB)                                                                                            
    100% |████████████████████████████████| 380kB 561kB/s                                                                            
Collecting msgpack-python>0.3 (from salt)                                                                                            
  Downloading msgpack-python-0.4.6.tar.gz (116kB)                                                                                    
    100% |████████████████████████████████| 118kB 1.3MB/s                                                                            
Collecting PyYAML (from salt)                                                                                                        
  Downloading PyYAML-3.11.tar.gz (248kB)                                                                                             
    100% |████████████████████████████████| 249kB 572kB/s                                                                            
Collecting MarkupSafe (from salt)                                                                                                    
  Downloading MarkupSafe-0.23.tar.gz                                                                                                 
Collecting requests>=1.0.0 (from salt)                                                                                               
  Downloading requests-2.7.0-py2.py3-none-any.whl (470kB)                                                                            
    100% |████████████████████████████████| 471kB 371kB/s                                                                            
Installing collected packages: MarkupSafe, Jinja2, msgpack-python, PyYAML, requests, salt                                            
  Running setup.py install for MarkupSafe                                                                                            
  Found existing installation: Jinja2 2.2.1                                                                                          
    Uninstalling Jinja2-2.2.1:                                                                                                       
      Successfully uninstalled Jinja2-2.2.1                                                                                          
  Running setup.py install for Jinja2                                                                                                
  Found existing installation: msgpack-python 0.4.4                                                                                  
    Uninstalling msgpack-python-0.4.4:                                                                                               
      Successfully uninstalled msgpack-python-0.4.4                                                                                  
  Running setup.py install for msgpack-python                                                                                        
  Found existing installation: PyYAML 3.10                                                                                           
    DEPRECATION: Uninstalling a distutils installed project (PyYAML) has been deprecated and will be removed in a future version. Thi
s is due to the fact that uninstalling a distutils project will only partially uninstall the project.                                
    Uninstalling PyYAML-3.10:                                                                                                        
      Successfully uninstalled PyYAML-3.10                                                                                           
  Running setup.py install for PyYAML                                                                                                
  Found existing installation: requests 1.1.0                                                                                        
    DEPRECATION: Uninstalling a distutils installed project (requests) has been deprecated and will be removed in a future version. T
his is due to the fact that uninstalling a distutils project will only partially uninstall the project.                              
    Uninstalling requests-1.1.0:                                                                                                     
      Successfully uninstalled requests-1.1.0                                                                                        
  Found existing installation: salt 2014.7.5                                                                                         
    DEPRECATION: Uninstalling a distutils installed project (salt) has been deprecated and will be removed in a future version. This 
is due to the fact that uninstalling a distutils project will only partially uninstall the project.                                  
    Uninstalling salt-2014.7.5:                                                                                                      
      Successfully uninstalled salt-2014.7.5                                                                                         
  Running setup.py install for salt                                                                                                  
Successfully installed Jinja2-2.7.3 MarkupSafe-0.23 PyYAML-3.11 msgpack-python-0.4.6 requests-2.7.0 salt-2015.5.0                    
```

## CentOS Version
```
[root@vmdepot-saltm saltop]# cat /etc/redhat-release
CentOS release 6.5 (Final)
```

## Failure after install
```
[root@vmdepot-saltm saltop]# salt --versions-report
Traceback (most recent call last):
  File "/usr/bin/salt", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: requests>=1.0.0
```

What exactly is it that I'm doing wrong in this upgrade chain?

**Comment by jfindlay** [comment]
I'm not sure why your upgrade got into this state.  RPM packages for 2015.5.0 should be available soon if they aren't already.  You can probably fix your upgrade by installing requests either by a system package or with pip.

**Comment by andrejohansson** [comment]
This issue seems to have been fixed with the yum packages when they came available. Thank you.
