### ISSUE TITLE
[salt-cloud lxc] NameError: global name '__salt__' is not defined

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#23657]
```
# salt-cloud -m map_lxc_test 
[snip]
ping_status:
    True
result:
    True
ursa:
    |_
      ----------
      changes:
          ----------
          init:
              |_
                ----------
                create:
                    Container cloned
              |_
                ----------
                password:
                    Password(s) updated
              |_
                ----------
                dns:
                    DNS updated
              |_
                ----------
                bootstrap:
                    Continer successfully bootstrapped
              |_
                ----------
                state:
                    ----------
                    new:
                        running
                    old:
                        None
      comment:
          Container 'bagu.logilab.priv' successfully initialized
      container_name:
          bagu.logilab.priv
      name:
          bagu.logilab.priv
      result:
          True
[INFO    ] Runner completed: 20150513153844491566
[ERROR   ] Failed to read the virtual function for module: npm
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1176, in process_virtual
    virtual = mod.__virtual__()
  File "/usr/lib/python2.7/dist-packages/salt/modules/npm.py", line 31, in __virtual__
    _check_valid_version()
  File "/usr/lib/python2.7/dist-packages/salt/modules/npm.py", line 47, in _check_valid_version
    __salt__['cmd.run']('npm --version'))
NameError: global name '__salt__' is not defined
[ERROR   ] There was a query error: unhashable type: 'dict'
# salt-run --versions-report
                  Salt: 2015.5.0
                Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
 Debian source package: 2015.5.0+ds-1trusty1

```

The minion inside lxc seems to be running but is not answering to commands from the master.

**Comment by arthurlogilab** [comment]
It seem that the problem is that the minion inside lxc is configured to talk to localhost for it's master.

**Comment by jfindlay** [comment]
@arthurlogilab, I think there may be two bugs here.  I have submitted a pull request to fix the stack trace.

**Comment by kiorky** [comment]
dup of #23772

**Comment by kiorky** [comment]
related to #23830

**Comment by kiorky** [comment]
(the master setting is now partly fixed by the first patches i submitted, but there is still a problem coming from salt cloud where load_args_and_kwargs filters some settings, like ... the minion config which includes the reference to the master.)

**Comment by kiorky** [comment]
@arthurlogilab once #23807  / #23808 will be merged, lot of your issues will be fixed.

**Comment by kiorky** [comment]
(you can also grab the changesets from the PR ;) )

**Comment by kiorky** [comment]
PRs: #23898 #23897

**Comment by arthurlogilab** [comment]
@kiorky thanks, haven't tested (yet) against your PR, but I see the following error on the minion side 

```
2015-05-21 18:23:28,632 [salt.loaded.int.module.cmdmod][ERROR   ][8877] Command 'lxc-attach --clear-env -n test -- /usr/bin/env' failed with return code: 1
2015-05-21 18:23:28,633 [salt.loaded.int.module.cmdmod][ERROR   ][8877] output: lxc-attach: attach.c: lxc_attach: 635 failed to get the init pid
2015-05-21 18:23:30,010 [salt.loaded.int.module.cmdmod][ERROR   ][8877] Command "lxc-attach --clear-env  --set-var PATH=/bin:/usr/bin:/sbin:/usr/sbin:/opt/bin:/usr/local/bin:/usr/local/sbin -n test -- test -e '/lxc.initial_seed'" failed with return code: 1
2015-05-21 18:23:30,011 [salt.loaded.int.module.cmdmod][ERROR   ][8877] retcode: 1
``` 

are you sure you're PRs solve this issue ?

**Comment by kiorky** [comment]
Yes they are, and as i said to you already a bunch of times, you are bitten by lxc <1.0.7.

My current Pr normally support it automically, or you can also configure a special network profile for old version:
https://github.com/makinacorpus/salt/blob/ef1f95231a79225c10b3883be57b941e831959d0/doc/topics/tutorials/lxc.rst#old-lxc-support-107

The new pr that add those automatic support are in
#24080 (2015.5) & #23982 (develop)

**Comment by rallytime** [comment]
@arthurlogilab Have you had a chance to test these fixes? It looks to me like this issue is resolved.

**Comment by arthurlogilab** [comment]
It doesn't seem to crash on __salt__ but now I get #27956 (and way too much verbose output)

**Comment by rallytime** [comment]
@arthurlogilab Sorry for the delay. It looks as though #27956 is resolved. Since this particular issue appears to be resolved, I am closing this. If the issue pops up again, please let us know or feel free to file a new issue. Thanks again!
