### ISSUE TITLE
AttributeError: 'TimedProc' object has no attribute 'stdout'

### ISSUE THREAD

**Issue by joycollector** [saltstack/salt#23666]
Hi,

Sometimes occasionally I get following error:

```
Comment: An exception occurred in this state: Traceback (most recent call last):
File "/usr/lib/python2.6/site-packages/salt/state.py", line 1533, in call **cdata['kwargs'])
File "/usr/lib/python2.6/site-packages/salt/states/cmd.py", line 1037, in mod_watch return run(name, **kwargs)
File "/usr/lib/python2.6/site-packages/salt/states/cmd.py", line 715, in run name, timeout=timeout, **cmd_kwargs
File "/usr/lib/python2.6/site-packages/salt/modules/cmdmod.py", line 867, in run_all use_vt=use_vt)
File "/usr/lib/python2.6/site-packages/salt/modules/cmdmod.py", line 376, in _run out, err = proc.stdout, proc.stderr
AttributeError: 'TimedProc' object has no attribute 'stdout'
```

Update: 
OS: CentOS release 6.5 (Final)
Salt: 2014.7.0
Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
Jinja2: 2.2.1
M2Crypto: 0.20.2
msgpack-python: 0.1.13
msgpack-pure: Not Installed
pycrypto: 2.0.1
libnacl: Not Installed
PyYAML: 3.10
ioflo: Not Installed
PyZMQ: 2.2.0.1
RAET: Not Installed
ZMQ: 3.2.4
Mako: Not Installed

**Comment by rallytime** [comment]
Thanks for the report @joycollector. Can you give us some more information about what might be causing this stacktrace? i.e. Can you post the output of `salt --versions-report`, tell us what OS you're running when you see this, and any commands or related states that might be triggering the error?

**Comment by joycollector** [comment]
I've updated issue description with the required details.

**Comment by rallytime** [comment]
Thanks @joycollector, that is certainly helpful! Can you also post the state that is causing the error? That will help us narrow down this issue.
