### ISSUE TITLE
salt mysql.module cannot create user with pure number

### ISSUE THREAD

**Issue by lisa2lisa** [saltstack/salt#23664]
salt --versions-report
```yaml
           Salt: 2014.7.5
         Python: 2.7.9 (default, Jan 28 2015, 05:37:45)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
```
salt-minion --version
```
salt-minion 2014.7.0 (Helium)
```

when creating a user with pure number: e.g
```
salt '*' mysql.user_create 'test7' '%' '934'
```
minion will throw exceptions:
```python
 The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1142, in _thread_return
        return_data = func(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/mysql.py", line 1188, in user_create
        _execute(cur, qry, args)
      File "/usr/lib/python2.7/dist-packages/salt/modules/mysql.py", line 505, in _execute
        return cur.execute(qry, args)
      File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
        self.errorhandler(self, exc, value)
      File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
        raise errorclass, errorvalue
    ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '934' at line 1")
```
debug info:
```python
[DEBUG   ] Doing query: SELECT User,Host FROM mysql.user WHERE User = %(user)s AND Host = %(host)s args: {'host': '%', 'user': 'test7'}
[DEBUG   ] Doing query: CREATE USER %(user)s@%(host)s IDENTIFIED BY %(password)s args: {'host': '%', 'password': 934, 'user': 'test7'}
[WARNING ] The minion function caused an exception
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1142, in _thread_return
    return_data = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/mysql.py", line 1188, in user_create
    _execute(cur, qry, args)
  File "/usr/lib/python2.7/dist-packages/salt/modules/mysql.py", line 505, in _execute
    return cur.execute(qry, args)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '934' at line 1")
```
In the mysql they run it as:
```
create user 'test7'@'%' identified by 934\g
```
it just something interesting i figured out. shouldn't be a problem if you have some idea of secure password.

**Comment by jfindlay** [comment]
@lisa2lisa, do you still have this problem after upgrading both master and minion to 2015.5.0?  Thanks.

**Comment by lisa2lisa** [comment]
@jfindlay , the problem is still exist for the 2015.5.0 version

root@salt:~ # salt '*' cmd.run "salt-minion --version"
    salt-minion 2015.5.0 (Lithium)
root@salt:~ # salt '*' mysql.user_create 'test' '%' '123'
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1142, in _thread_return
        return_data = func(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/mysql.py", line 1188, in user_create
        _execute(cur, qry, args)
      File "/usr/lib/python2.7/dist-packages/salt/modules/mysql.py", line 505, in _execute
        return cur.execute(qry, args)
      File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
        self.errorhandler(self, exc, value)
      File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
        raise errorclass, errorvalue
    ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '123' at line 1")

**Comment by lisa2lisa** [comment]
after the change, the result are following:
```
# salt '*' mysql.user_create 'test' '%' '123'
    True
```
and the bebug info are following:
```
[DEBUG   ] Doing query: SELECT User,Host FROM mysql.user WHERE User = %(user)s AND Host = %(host)s args: {'host': '%', 'user': 'test'}
[DEBUG   ] Doing query: CREATE USER %(user)s@%(host)s IDENTIFIED BY %(password)s args: {'host': '%', 'password': '123', 'user': 'test'}
[DEBUG   ] Doing query: SELECT User,Host FROM mysql.user WHERE User = %(user)s AND Host = %(host)s AND Password = PASSWORD(%(password)s) args: {'host': '%', 'password': '123', 'user': 'test'}
[INFO    ] User 'test'@'%' has been created
```
and check in mysql:
```
mysql> select user, host from user where user='test'\G
*************************** 1. row ***************************
user: test
host: %
1 row in set (0.00 sec)
```

**Comment by rallytime** [comment]
@lisa2lisa Awesome! Thanks for the bug report and the fix. Since your pull request has been merged in, I am going to close this. If more work needs to be done here, let us know and we can open this again. Thanks!
