### ISSUE TITLE
salt-cloud vsphere.list_nodes Response is "text/plain", not "text/xml"

### ISSUE THREAD

**Issue by BalintSzigeti** [saltstack/salt#23705]
```
[root@master01 cloud.profiles.d]# salt-cloud -P -p testprofile -m ../cloud.maps.d/map1 
[DEBUG   ] Configuration file path: /etc/salt/cloud
[INFO    ] salt-cloud starting
[DEBUG   ] Failed to import clouds joyent:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/loader.py", line 951, in _load_module
    ), fn_, fpath, desc)
  File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/joyent.py", line 68, in <module>
    from Crypto.Signature import PKCS1_v1_5
ImportError: No module named Signature
[DEBUG   ] Could not LazyLoad parallels.avail_sizes
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy
[DEBUG   ] Could not LazyLoad saltify.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.avail_images
[DEBUG   ] Could not LazyLoad saltify.avail_locations
[DEBUG   ] LazyLoaded rackspace.reboot
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] LazyLoaded rackspace.list_locations
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] Jinja search path: ['/var/cache/salt/master/files/base']
[DEBUG   ] Rendered data from file: ../cloud.maps.d/map1:
test:
  - test1
  - test2
haproxy:
  - haproxy1
  - haproxy2

[DEBUG   ] Results of YAML rendering: 
OrderedDict([('test', ['test1', 'test2']), ('haproxy', ['haproxy1', 'haproxy2'])])
[INFO    ] Applying map from '../cloud.maps.d/map1'.
[DEBUG   ] Could not LazyLoad vsphere.optimize_providers
[DEBUG   ] The 'vsphere' cloud driver is unable to be optimized.
[DEBUG   ] Failed to import clouds joyent:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/loader.py", line 951, in _load_module
    ), fn_, fpath, desc)
  File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/joyent.py", line 68, in <module>
    from Crypto.Signature import PKCS1_v1_5
ImportError: No module named Signature
[DEBUG   ] Could not LazyLoad parallels.avail_sizes
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy
[DEBUG   ] Could not LazyLoad saltify.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.avail_images
[DEBUG   ] Could not LazyLoad saltify.avail_locations
[DEBUG   ] LazyLoaded rackspace.reboot
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] LazyLoaded rackspace.list_locations
[DEBUG   ] Failed to execute 'vsphere.list_nodes()' while querying for running nodes: Response is "text/plain", not "text/xml"
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 2247, in run_parallel_map_providers_query
    cloud.clouds[data['fun']]()
  File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/vsphere.py", line 488, in list_nodes
    conn = get_conn()
  File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/vsphere.py", line 131, in get_conn
    'password', get_configured_provider(), __opts__, search_global=False
  File "/usr/lib/python2.6/site-packages/pysphere/vi_server.py", line 101, in connect
    request)._returnval
  File "/usr/lib/python2.6/site-packages/pysphere/resources/VimService_services.py", line 2114, in RetrieveServiceContent
    response = self.binding.Receive(RetrieveServiceContentResponseMsg.typecode)
  File "/usr/lib/python2.6/site-packages/pysphere/ZSI/client.py", line 540, in Receive
    self.ReceiveSOAP(**kw)
  File "/usr/lib/python2.6/site-packages/pysphere/ZSI/client.py", line 425, in ReceiveSOAP
    'Response is "%s", not "text/xml"' % self.local.reply_headers.type)
TypeError: Response is "text/plain", not "text/xml"
[ERROR   ] The required profile, 'test', defined in the map does not exist. The defined nodes, 'test1', 'test2', will not be created.
[ERROR   ] The required profile, 'haproxy', defined in the map does not exist. The defined nodes, 'haproxy1', 'haproxy2', will not be created.
Found the following errors:
  test: The required profile, 'test', defined in the map does not exist. The defined nodes, 'test1', 'test2', will not be created.
  haproxy: The required profile, 'haproxy', defined in the map does not exist. The defined nodes, 'haproxy1', 'haproxy2', will not be created.
```
```
testprofile:
    provider: vmwaredev #provider is the ID at in /etc/salt/cloud.providers.d/*.conf files
    
[root@master01 cloud.profiles.d]# cat ../cloud.providers.d/vsphere.conf 
vmwaredev:
  provider: vsphere
  user: 'domain\salt'
  password: **********
  url: 'http://hostname-dev.example.com:9443/sdk'
```
The vsphere and VCenter are the latest (5.5) version.
```
centos 6.6
[root@master01 cloud.profiles.d]# salt-master --versions-report
           Salt: 2015.5.0
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
```
**Note**
Just ignore the joyent import error.
The python-crypto2.6 is installed which contains the Crypto/Signature/PKCS1_v1_5.py file
so the import joyent should work.
```
[root@master01 cloud.profiles.d]# rpm -ql python-crypto2.6|grep -i "crypto/sig"
/usr/lib64/python2.6/site-packages/pycrypto-2.6.1-py2.6-linux-x86_64.egg/Crypto/Signature
/usr/lib64/python2.6/site-packages/pycrypto-2.6.1-py2.6-linux-x86_64.egg/Crypto/Signature/PKCS1_PSS.py
/usr/lib64/python2.6/site-packages/pycrypto-2.6.1-py2.6-linux-x86_64.egg/Crypto/Signature/PKCS1_PSS.pyc
/usr/lib64/python2.6/site-packages/pycrypto-2.6.1-py2.6-linux-x86_64.egg/Crypto/Signature/PKCS1_PSS.pyo
/usr/lib64/python2.6/site-packages/pycrypto-2.6.1-py2.6-linux-x86_64.egg/Crypto/Signature/PKCS1_v1_5.py
/usr/lib64/python2.6/site-packages/pycrypto-2.6.1-py2.6-linux-x86_64.egg/Crypto/Signature/PKCS1_v1_5.pyc
/usr/lib64/python2.6/site-packages/pycrypto-2.6.1-py2.6-linux-x86_64.egg/Crypto/Signature/PKCS1_v1_5.pyo
/usr/lib64/python2.6/site-packages/pycrypto-2.6.1-py2.6-linux-x86_64.egg/Crypto/Signature/__init__.py
/usr/lib64/python2.6/site-packages/pycrypto-2.6.1-py2.6-linux-x86_64.egg/Crypto/Signature/__init__.pyc
/usr/lib64/python2.6/site-packages/pycrypto-2.6.1-py2.6-linux-x86_64.egg/Crypto/Signature/__init__.pyo
```

**Comment by jfindlay** [comment]
@BalintSzigeti, thanks for the report.

**Comment by nmadhok** [comment]
@jfindlay @BalintSzigeti This is a problem with the existing ``vsphere`` cloud driver. This has been fixed in the new ``vmware`` cloud driver.

**Comment by jfindlay** [comment]
@nmadhok, would you consider this an upstream bug then?  Is it something we need to provide a workaround for if someone is using an old version of the driver?

**Comment by BalintSzigeti** [comment]
but I use the latest driver. 1.8 which was linked in the documentation

**Comment by nmadhok** [comment]
@BalintSzigeti You may be getting this error because the profiles you specified don't exist. Can you try again after making sure that the profile you specify exists? 

@jfindlay This isn't an upstream bug. This bug exists in the way the salt-cloud vsphere driver has been written. I could possibly look into it but it depends on when I can find time to work on this. I've been busy working on the VMWare cloud driver and other things

**Comment by nmadhok** [comment]
@techhat Can we close this issue since vsphere driver will be deprecated in future salt releases in favor of the new vmware driver? http://docs.saltstack.com/en/develop/ref/clouds/all/salt.cloud.clouds.vmware.html

**Comment by BalintSzigeti** [comment]
until how could I use salt-cloud with vsphere? is there a beta drive somewhere?

**Comment by nmadhok** [comment]
@BalintSzigeti You can use the new vmware cloud driver for salt-cloud instead. See http://docs.saltstack.com/en/develop/topics/cloud/vmware.html and http://docs.saltstack.com/en/develop/ref/clouds/all/salt.cloud.clouds.vmware.html

You will have to manually download the driver and place it under your salt installation directory.

**Comment by BalintSzigeti** [comment]
it (http://docs.saltstack.com/en/develop/topics/cloud/vmware.html) says
New in version Beryllium. which is the development version. I have the 2015.5.0.
Is the new driver is/will available in it?

**Comment by rallytime** [comment]
@BalintSzigeti The new vmware driver won't be available until Salt Beryllium is released. (We're targeting around August or so, depending on development time.) The new driver will not be available in any of the 2015.5.x releases.

However, until then, as @nmadhok suggested, if you manually download the [new vmware.py driver](https://github.com/saltstack/salt/blob/develop/salt/cloud/clouds/vmware.py) and place it under your salt installation directory (`path/to/installation/directory/salt/cloud/clouds/`) on the master (or whatever machine your using salt-cloud from) then you should be able to use this new driver.

**Comment by nmadhok** [comment]
@BalintSzigeti Looking at the traceback, your salt installation directory is ``/usr/lib/python2.6/site-packages/salt/`` so you can do the following to get the vmware cloud driver:

```
curl -L https://raw.githubusercontent.com/saltstack/salt/develop/salt/cloud/clouds/vmware.py -o /usr/lib/python2.6/site-packages/salt/cloud/clouds/vmware.py
```

Also, don't forget to install pyVmomi if you haven't already by doing the following:
```
pip install pyvmomi
```

**Comment by rallytime** [comment]
The vshpere driver is on a deprecation path and will be officially removed in Salt Carbon (see #24487 and #24504). As such, we'd recommend moving to the new vmware driver as discussed above. Since we have a much more robust and clean driver, we won't be spending time cleaning up bugs for vsphere. However, we will of course be accepting fixes from community members as they are submitted.

**Comment by nmadhok** [comment]
@rallytime This issue can be closed I think.
