### ISSUE TITLE
2015.5.0 modules/archive.py ZipFile instance has no attribute '__exit__' - only python 2.6?

### ISSUE THREAD

**Issue by bradthurber** [saltstack/salt#23734]
Got this error unzipping a .zip file using archive.extracted on 2015.5.0

```
    Function: archive.extracted
        Name: /opt/jboss/eap
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.6/site-packages/salt/state.py", line 1563, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.6/site-packages/salt/states/archive.py", line 178, in extracted
                  name)
                File "/usr/lib/python2.6/site-packages/salt/modules/archive.py", line 543, in unzip
                  'Exception encountered unpacking zipfile: {0}'.format(exc)
              CommandExecutionError: Exception encountered unpacking zipfile: ZipFile instance has no attribute '__exit__'
     Started: 18:52:10.869057
    Duration: 19.57 ms
```
This is a CentOS 6.5 system (python 2.6)

```
salt-minion --versions
           Salt: 2015.5.0
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: unknown
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
```

These links show what may be the problem and possible solutions
http://stackoverflow.com/questions/21268470/making-python-2-7-code-run-with-python-2-6
http://hsmoore.com/python-attributeerror-zipfile-instance-has-no-attribute-__exit__/

**Comment by bradthurber** [comment]
I'm working on a possible PR to fix this

**Comment by rallytime** [comment]
Thanks for the report and for the fix @bradthurber! Since your fix was merged, do you consider this issue ready to be closed?

**Comment by bradthurber** [comment]
yes - it can be closed

Brad Thurber

**Comment by rallytime** [comment]
Super!
