### ISSUE TITLE
Tokens don't store eauth groups

### ISSUE THREAD

**Issue by dswarbrick** [saltstack/salt#23761]
I stumbled over this issue after upgrading to 2015.5, and it appears to be closely related to #22905 and perhaps caused by the merge request in #23066.

If the external auth config specifies users _and_ groups, and one of the users is also a member of one of the groups, it appears that the mk_token() method does not store the user's groups in the token, which later leads to a traceback:

```
2015-05-13 18:59:23,325 [salt.master                              ][CRITICAL][12696] Unexpected Error in Mworker
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 735, in __bind
    ret = self.serial.dumps(self._handle_payload(payload))
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 793, in _handle_payload
    'clear': self._handle_clear}[key](load)
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 806, in _handle_clear
    return getattr(self.clear_funcs, load['cmd'])(load)
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 2220, in publish
    for group in token['groups']:
KeyError: 'groups'
```

It appears that the following if-statement in master.py:mk_token() (around line 2114) does not evaluate to true if the user is found as a standalone user, and consequently the clear_load dict is never populated with the group membership:

```
            if not ((name in self.opts['external_auth'][clear_load['eauth']]) |
                    ('*' in self.opts['external_auth'][clear_load['eauth']])):
```

**Comment by jfindlay** [comment]
@dswarbrick, thanks for the report.
