### ISSUE TITLE
Friendlier error msg upon erroneous require statement

### ISSUE THREAD

**Issue by The-Loeki** [saltstack/salt#23844]
Given:

```
etckeeper:
  pkg.installed:
    - names:
      - git
      - etckeeper
      {%- if rhel %}
      - require:
        - repo.epel
      {%- endif %}
```

SaltStack 2015.5 will report

```
[DEBUG   ] Results of YAML rendering:
OrderedDict([('ntp-pkgs', OrderedDict([('pkg.installed', [OrderedDict([('names', ['ntp', 'ntpdate'])])])])), ('/etc/ntp.conf', OrderedDict([('file.managed', [OrderedDict([('mode', 644)]), OrderedDict([('user', 'root')]), OrderedDict([('g
roup', 'root')]), OrderedDict([('source', 'salt://ntp/ntp_conf.jinja')]), OrderedDict([('template', 'jinja')])])])), ('ntpd', OrderedDict([('service.running', [OrderedDict([('enable', True)]), OrderedDict([('watch', [OrderedDict([('file'
, '/etc/ntp.conf')]), OrderedDict([('pkg', 'ntp-pkgs')])])])])]))])
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
ValueError: dictionary update sequence element #0 has length 1; 2 is required
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 227, in salt_call
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 69, in run
    caller.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 236, in run
    ret = self.call()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 138, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 671, in sls
    ret = st_.state.call_high(high_)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2040, in call_high
    chunks = self.compile_high_data(high)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 1132, in compile_high_data
    live.update(entry[low_name][0])
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

Which is all nice & cozy, but not extremely helpful.
Only after manually adding debug msgs did we found out the fix was to indent `require` less, and use `sls:` :

```
etckeeper:
  pkg.installed:
    - names:
      - git
      - etckeeper
   {%- if rhel %}
    - require:
      - sls: repo.epel
    {%- endif %}
```

I think the error msg could <much> better reflect that.

**Comment by rallytime** [comment]
Thanks for the report @The-Loeki.

**Comment by The-Loeki** [comment]
@rallytime you're welcome as always ;) beware though this is not a Bug; the error was ours. It was just the utterly unhelpful and confusing stack trace that got us ;)

**Comment by rallytime** [comment]
@The-Loeki Yes, indeed. I was considering the "unhelpful and confusing" stacktrace to be the bug. I feel like there are other issues open about stacktraces occurring during state-runs due to faulty syntax, but I can't seem to find them right now. It would certainly be helpful to get these unhelpful stacktraces cleaned up somehow + more useful error messages.
