### ISSUE TITLE
create_ca_signed_cert can error if dereferenced dict is used for args

### ISSUE THREAD

**Issue by joejulian** [saltstack/salt#23872]
Calling create_ca_signed_cert(**foo) where foo is a dict of args causes an error:

       Traceback (most recent call last):
         File "/home/jjulian/.venv/salttest/lib/python2.7/site-packages/mock.py", line 1201, in patched
           return func(*args, **keywargs)
         File "/home/jjulian/dev/salt/tests/unit/modules/tls_test.py", line 436, in test_create_ca_signed_cert
           self.assertEqual(tls.create_ca_signed_cert(ca_name,**_test_data['create_ca']), ret)
         File "/home/jjulian/dev/salt/salt/modules/tls.py", line 863, in create_ca_signed_cert
           name, extensions[name]['critical'], extensions[name]['options']))
       TypeError: string indices must be integers, not str

**Comment by rallytime** [comment]
Thanks for the report and for the fix @joejulian! We love it when that happens. :)
