### ISSUE TITLE
salt-ssh with mixed git:// and https:// configurations in gitfs_remotes stacktraces

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt#23885]
Consider the following configuration in the `gitfs_remotes` section of the master-config file:
```
gitfs_remotes:
  - git://github.com/saltstack/salt-jenkins.git
  - https://github.com/saltstack-formulas/apache-formula
```
Note the differing configurations of `git://` and `https://`. When that configuration is present in the master config file and I try any salt-ssh command, I get the following stacktrace:
```
# salt-ssh nt-cent7 test.ping
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
BadName: Ref 'style-short-dec' did not resolve to an object
Traceback (most recent call last):
  File "/usr/local/bin/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/root/SaltStack/salt/salt/scripts.py", line 167, in salt_ssh
    client.run()
  File "/root/SaltStack/salt/salt/cli/__init__.py", line 477, in run
    ssh = salt.client.ssh.SSH(self.config)
  File "/root/SaltStack/salt/salt/client/ssh/__init__.py", line 220, in __init__
    self.mods = mod_data(self.fsclient)
  File "/root/SaltStack/salt/salt/client/ssh/__init__.py", line 1058, in mod_data
    files = fsclient.file_list(env)
  File "/root/SaltStack/salt/salt/fileclient.py", line 1051, in file_list
    return channel.send(load)
  File "/root/SaltStack/salt/salt/fileserver/__init__.py", line 665, in send
    return getattr(self.fs, cmd)(load)
  File "/root/SaltStack/salt/salt/fileserver/__init__.py", line 539, in file_list
    ret.update(self.servers[fstr](load))
  File "/root/SaltStack/salt/salt/fileserver/gitfs.py", line 1661, in file_list
    return _file_lists(load, 'files')
  File "/root/SaltStack/salt/salt/fileserver/gitfs.py", line 1642, in _file_lists
    ret['files'], ret['symlinks'] = _get_file_list(load)
  File "/root/SaltStack/salt/salt/fileserver/gitfs.py", line 1691, in _get_file_list
    repo_files, repo_symlinks = fl_func(repo, load['saltenv'])
  File "/root/SaltStack/salt/salt/fileserver/gitfs.py", line 1710, in _file_list_gitpython
    tree = _get_tree_gitpython(repo, tgt_env)
  File "/root/SaltStack/salt/salt/fileserver/gitfs.py", line 392, in _get_tree_gitpython
    commit = repo['repo'].rev_parse(tgt_env)
  File "/usr/local/lib/python2.7/dist-packages/GitPython-1.0.0-py2.7.egg/git/repo/fun.py", line 304, in rev_parse
    obj = name_to_object(repo, rev)
  File "/usr/local/lib/python2.7/dist-packages/GitPython-1.0.0-py2.7.egg/git/repo/fun.py", line 117, in name_to_object
    raise BadName(name)
BadName: Ref 'style-short-dec' did not resolve to an object
Traceback (most recent call last):
  File "/usr/local/bin/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/root/SaltStack/salt/salt/scripts.py", line 167, in salt_ssh
    client.run()
  File "/root/SaltStack/salt/salt/cli/__init__.py", line 477, in run
    ssh = salt.client.ssh.SSH(self.config)
  File "/root/SaltStack/salt/salt/client/ssh/__init__.py", line 220, in __init__
    self.mods = mod_data(self.fsclient)
  File "/root/SaltStack/salt/salt/client/ssh/__init__.py", line 1058, in mod_data
    files = fsclient.file_list(env)
  File "/root/SaltStack/salt/salt/fileclient.py", line 1051, in file_list
    return channel.send(load)
  File "/root/SaltStack/salt/salt/fileserver/__init__.py", line 665, in send
    return getattr(self.fs, cmd)(load)
  File "/root/SaltStack/salt/salt/fileserver/__init__.py", line 539, in file_list
    ret.update(self.servers[fstr](load))
  File "/root/SaltStack/salt/salt/fileserver/gitfs.py", line 1661, in file_list
    return _file_lists(load, 'files')
  File "/root/SaltStack/salt/salt/fileserver/gitfs.py", line 1642, in _file_lists
    ret['files'], ret['symlinks'] = _get_file_list(load)
  File "/root/SaltStack/salt/salt/fileserver/gitfs.py", line 1691, in _get_file_list
    repo_files, repo_symlinks = fl_func(repo, load['saltenv'])
  File "/root/SaltStack/salt/salt/fileserver/gitfs.py", line 1710, in _file_list_gitpython
    tree = _get_tree_gitpython(repo, tgt_env)
  File "/root/SaltStack/salt/salt/fileserver/gitfs.py", line 392, in _get_tree_gitpython
    commit = repo['repo'].rev_parse(tgt_env)
  File "/usr/local/lib/python2.7/dist-packages/GitPython-1.0.0-py2.7.egg/git/repo/fun.py", line 304, in rev_parse
    obj = name_to_object(repo, rev)
  File "/usr/local/lib/python2.7/dist-packages/GitPython-1.0.0-py2.7.egg/git/repo/fun.py", line 117, in name_to_object
    raise BadName(name)
gitdb.exc.BadName: Ref 'style-short-dec' did not resolve to an object
```
If I comment out either the `git://` reference, or the `https://` reference, everything runs smoothly. The mixed references works fine with "regular" salt, but salt-ssh does not work with both `git://` and `https://` references in the master config.

My versions report is:
```
# salt-ssh --versions
           Salt: 2014.7.5
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.4
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
```
But I tested this at the HEAD of the 2014.7, 2015.5, and develop branches with the same result.

**Comment by rallytime** [comment]
@basepi

**Comment by basepi** [comment]
I cannot reproduce this.

```
gitfs_remotes:
  - git://github.com/saltstack/salt-jenkins.git
  - https://github.com/saltstack-formulas/apache-formula
root@li1307-41:~# cat /etc/salt/roster
basepi02:
  user: root
  host: 45.79.216.41
root@li1307-41:~# salt-ssh '*' test.ping -W
basepi02:
    True
```

**Comment by rallytime** [comment]
I just tried this again on the HEAD of 2015.5 and I am unable to reproduce this also. Thanks for trying @basepi! I'll close this.
