### ISSUE TITLE
salt --summary seems to be broken

### ISSUE THREAD

**Issue by ngrennan-inflection** [saltstack/salt#23890]
`salt --summary` doesn't seem to work for me. It doesn't matter if it is one host or multiple hosts. It doesn't throw an error if I remove --summary.

salt-2015.5.0 from EPEL
```
salt 'nagios*' test.ping -v --summary
Executing job with jid 20150518154021296347
-------------------------------------------

nagios-01.foo.com:
    True
nagios-01.foo.com:
    Minion did not return. [Not connected]
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'str' object has no attribute 'get'
Traceback (most recent call last):
  File "/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 349, in salt_main
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/salt.py", line 210, in run
    self._print_returns_summary(ret)
  File "/usr/lib/python2.7/site-packages/salt/cli/salt.py", line 242, in _print_returns_summary
    minion_ret = ret[each_minion].get('ret')
AttributeError: 'str' object has no attribute 'get'
Traceback (most recent call last):
  File "/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 349, in salt_main
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/salt.py", line 210, in run
    self._print_returns_summary(ret)
  File "/usr/lib/python2.7/site-packages/salt/cli/salt.py", line 242, in _print_returns_summary
    minion_ret = ret[each_minion].get('ret')
AttributeError: 'str' object has no attribute 'get'
```

**Comment by jfindlay** [comment]
@ngrennan-inflection, did you recently just upgrade?  I'm suspicious of the double `nagios-01.foo.com` minion return, which has been known to happen when an upgrade did not stop the old salt-minion process.

**Comment by driskell** [comment]
I just recently upgraded to salt-2015.5 and get the same error:

```
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'str' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 349, in salt_main
    client.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/salt.py", line 208, in run
    self._print_returns_summary(ret)
  File "/usr/lib/python2.6/site-packages/salt/cli/salt.py", line 240, in _print_returns_summary
    minion_ret = ret[each_minion].get('ret')
AttributeError: 'str' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 349, in salt_main
    client.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/salt.py", line 208, in run
    self._print_returns_summary(ret)
  File "/usr/lib/python2.6/site-packages/salt/cli/salt.py", line 240, in _print_returns_summary
    minion_ret = ret[each_minion].get('ret')
AttributeError: 'str' object has no attribute 'get'
```

In my instance I do not have any duplicated minion returns. Running without `--summary` works fine and there are no duplicated and every minion returns instantly.

**Comment by driskell** [comment]
Examining the code, it is calling get on a string object.

The salt command I used for the above error was: `salt --summary -t 5 '*' cmd.run 'cat /etc/sysconfig/ntpd'`

If I instead use `salt --summary -t 5 '*' test.ping` I get:

```
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'bool' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 349, in salt_main
    client.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/salt.py", line 209, in run
    self._print_returns_summary(ret)
  File "/usr/lib/python2.6/site-packages/salt/cli/salt.py", line 242, in _print_returns_summary
    minion_ret = ret[each_minion].get('ret')
AttributeError: 'bool' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 349, in salt_main
    client.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/salt.py", line 209, in run
    self._print_returns_summary(ret)
  File "/usr/lib/python2.6/site-packages/salt/cli/salt.py", line 242, in _print_returns_summary
    minion_ret = ret[each_minion].get('ret')
AttributeError: 'bool' object has no attribute 'get'
```

**Comment by driskell** [comment]
This is already fixed it seems:

https://github.com/saltstack/salt/commit/54b33dd359489da0f432e3735ca48385d00666c4

**Comment by driskell** [comment]
Applying https://github.com/saltstack/salt/commit/54b33dd359489da0f432e3735ca48385d00666c4 fixed the problem for me.

**Comment by jfindlay** [comment]
Nice, thanks @driskell.

**Comment by yermulnik** [comment]
Thanx!
