### ISSUE TITLE
salt ubuntu network building issue 2015.5.0

### ISSUE THREAD

**Issue by hashi825** [saltstack/salt#23900]
When previously building network interfaces with saltstack 2014.7.5
```yaml
eth1:
 network.managed:
  - enabled: True
  - type: slave
  - mtu: 9000
  - master: bond0 
```
The following would create in the /etc/network/interfaces file
```
auto eth1
iface eth1 inet manual
mtu 9000
bond_master bond0
```

After upgrading to 2015.5.0 it will build the interfaces file as such
```
auto eth1
iface eth1 inet manual
mtu 9000
bond-master bond0
```
The dash in bond-master then breaks interface parsing

```console
# salt-call ip.get_interface eth1
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 227, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 69, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 236, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 138, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/debian_ip.py", line 1641, in get_interface
    adapters = _parse_interfaces()
  File "/usr/lib/python2.7/dist-packages/salt/modules/debian_ip.py", line 584, in _parse_interfaces
    opt = attr.split('_', 1)[1]
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 227, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 69, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 236, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 138, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/debian_ip.py", line 1641, in get_interface
    adapters = _parse_interfaces()
  File "/usr/lib/python2.7/dist-packages/salt/modules/debian_ip.py", line 584, in _parse_interfaces
    opt = attr.split('_', 1)[1]
IndexError: list index out of range
```

Correcting the dash back to an underscore restores proper functionality, but states using bond attempt to get re-applied with a dash instead of an underscore
```console
# salt-call ip.get_interface eth1
local:
    - auto eth1
    - iface eth1 inet manual
    -     mtu 9000
    -     bond-master bond0
    -
```

**Comment by garethgreenaway** [comment]
What version of Ubuntu is this one?  Looking at the Debian & Ubuntu documentation for bonding, it seems that bond-master is a valid parameter.

**Comment by hashi825** [comment]
Trusty, it is a valid parameter but the debian_ip module is unable to parse the interfaces in the interfaces file because its a - and not _. Previously in 2014.7.5 the interfaces files was built using underscores for bonds/vlans which meant the parser would be able to determine the interfaces in that file correclty

**Comment by garethgreenaway** [comment]
See the issue.  Working on a fix now.  Thanks for the report!

**Comment by jfindlay** [comment]
@hashi825, thanks for the report.

**Comment by rallytime** [comment]
@hashi825 Did the fix above resolve this issue for you?

**Comment by hashi825** [comment]
yea sorry I didnt get back, I usually use the saltstack ppa. I did a manual install of 2015.5.2 and can confirm this has been fixed

**Comment by rallytime** [comment]
No problem! Glad it is working for you. :)
