### ISSUE TITLE
[salt-virt] virt runner KeyError on virt.init

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#23914]
```
# salt-run virt.init debian-jessie 2 512 salt://debian-jessie-amd64-150305.raw
event:
    ----------
    message:
        Searching for Hypervisors
suffix:
    progress
[WARNING ] 'quiet' is deprecated. Please migrate to --quiet
event:
    ----------
    message:
        Minion will be preseeded
suffix:
    progress
event:
    ----------
    message:
        Creating VM debian-jessie on hypervisor ursa
suffix:
    progress
Exception occurred in runner virt.init: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 317, in low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/runners/virt.py", line 250, in init
    if ret[minion_id]['ret'] is False:
KeyError: 'ret'
# salt-run --versions-report
                  Salt: 2015.5.0
                Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
 Debian source package: 2015.5.0+ds-1trusty1
```

At the end a vm has been created but not started. 

```
# virsh list --all
 Id    Name                           State
----------------------------------------------------
 -     debian-jessie                  shut off
```

**Comment by arthurlogilab** [comment]
Trying the same command on the failed situation is not very informative : 
```
# salt-run virt.init debian-jessie 2 512 salt://debian-jessie-amd64-150305.raw
event:
    ----------
    message:
        Searching for Hypervisors
suffix:
    progress
[WARNING ] 'quiet' is deprecated. Please migrate to --quiet
event:
    ----------
    message:
        Virtual machine debian-jessie is already deployed
suffix:
    progress
fail

```

adding -l all to the command gives me the follow message which should be displayed : 

```
[DEBUG   ] Sending event - data = {'message': 'Virtual machine debian-jessie is already deployed', '_stamp': '2015-05-19T13:50:12.429245'}
```

Should I file another bug ?

**Comment by jfindlay** [comment]
@arthurlogilab, thanks for the report.  In your second comment, I can see the text from the debug log from the normal runner output,
```yaml
event:
    ----------
    message:
        Virtual machine debian-jessie is already deployed
```

**Comment by arthurlogilab** [comment]
@jfindlay oh yes, sorry for that. I kind of focused on the "fail" but you're right, you can ignore that comment.

**Comment by cbuechler** [comment]
Same result as OP here when running same command on devel version. 
```
# salt --versions
Salt Version:
           Salt: 2015.5.0-1729-g01dfa10
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2
            ZMQ: 4.0.4
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
       pycrypto: 2.6.1
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-57-generic
         system: Ubuntu 14.04 trusty
```
