### ISSUE TITLE
Building docs for develop branch now fails with a TypeError

### ISSUE THREAD

**Issue by nmadhok** [saltstack/salt#23916]
```
No need to update translations. Skipping...
sphinx-build -b html -d _build/doctrees    . _build/html
Running Sphinx v1.3.1
loading translations [en]... done
loading pickled environment... done
[autosummary] generating autosummary for: contents-1.rst, contents-2.rst, contents-3.rst, contents-4.rst, contents.rst, faq.rst, glossary.rst, index.rst, ref/auth/all/index.rst, ref/auth/all/salt.auth.auto.rst, ..., topics/tutorials/walkthrough.rst, topics/tutorials/walkthrough_macosx.rst, topics/tutorials/writing_tests.rst, topics/virt/disk.rst, topics/virt/index.rst, topics/virt/nic.rst, topics/windows/index.rst, topics/windows/windows-package-manager.rst, topics/windows/windows-specific-behavior.rst, topics/yaml/index.rst

Exception occurred:
  File "/root/salt/salt/utils/psutil_compat.py", line 24, in <module>
    for attr in psutil.__all__:
TypeError: 'Mock' object is not iterable
The full traceback has been saved in /tmp/sphinx-err-xYiUWX.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 1
```

Here's the full traceback:
```
root@nitin-salt-develop:~/salt$ cat /tmp/sphinx-err-xYiUWX.log
# Sphinx version: 1.3.1
# Python version: 2.6.6 (CPython)
# Docutils version: 0.11 release
# Jinja2 version: 2.7.3
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/cmdline.py", line 244, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/usr/lib/python2.6/site-packages/sphinx/application.py", line 188, in __init__
    self._init_builder(buildername)
  File "/usr/lib/python2.6/site-packages/sphinx/application.py", line 250, in _init_builder
    self.emit('builder-inited')
  File "/usr/lib/python2.6/site-packages/sphinx/application.py", line 497, in emit
    results.append(callback(self, *args))
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autosummary/__init__.py", line 564, in process_generate_options
    base_path=app.srcdir)
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autosummary/generate.py", line 115, in generate_autosummary_docs
    items = find_autosummary_in_files(sources)
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autosummary/generate.py", line 228, in find_autosummary_in_files
    filename=filename))
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autosummary/generate.py", line 326, in find_autosummary_in_lines
    current_module, filename=filename))
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autosummary/generate.py", line 238, in find_autosummary_in_docstring
    real_name, obj, parent, modname = import_by_name(name)
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autosummary/__init__.py", line 473, in import_by_name
    obj, parent, modname = _import_by_name(prefixed_name)
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autosummary/__init__.py", line 489, in _import_by_name
    __import__(modname)
  File "/root/salt/salt/cloud/__init__.py", line 30, in <module>
    import salt.client
  File "/root/salt/salt/client/__init__.py", line 37, in <module>
    import salt.minion
  File "/root/salt/salt/minion.py", line 51, in <module>
    import salt.utils.psutil_compat as psutil
  File "/root/salt/salt/utils/psutil_compat.py", line 24, in <module>
    for attr in list(psutil.__all__):
TypeError: 'Mock' object is not iterable
```

**Comment by nmadhok** [comment]
@whiteinge @jfindlay After applying fix from #23894, the docs do get built but I get the following message:

```
Failed to import 'salt.modules.ps': no module named salt.modules.ps
WARNING: [autosummary] failed to import u'salt.modules.ps': no module named salt.modules.ps
```
& the following traceback:
```
reading sources... [100%] ref/modules/all/salt.modules.ps                                                                                                                            
/root/salt/doc/ref/modules/all/salt.modules.ps.rst:11: WARNING: autodoc: failed to import module u'salt.modules.ps'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/root/salt/salt/modules/ps.py", line 25, in <module>
    PSUTIL2 = psutil.version_info >= (2, 0)
AttributeError: 'module' object has no attribute 'version_info'
```

Full build:
```
sphinx-build -b html -d _build/doctrees    . _build/html
Running Sphinx v1.3.1
loading translations [en]... done
loading pickled environment... done
[autosummary] generating autosummary for: contents-1.rst, contents-2.rst, contents-3.rst, contents-4.rst, contents.rst, faq.rst, glossary.rst, index.rst, ref/auth/all/index.rst, ref/auth/all/salt.auth.auto.rst, ..., topics/tutorials/walkthrough.rst, topics/tutorials/walkthrough_macosx.rst, topics/tutorials/writing_tests.rst, topics/virt/disk.rst, topics/virt/index.rst, topics/virt/nic.rst, topics/windows/index.rst, topics/windows/windows-package-manager.rst, topics/windows/windows-specific-behavior.rst, topics/yaml/index.rst
Failed to import 'salt.modules.ps': no module named salt.modules.ps
WARNING: [autosummary] failed to import u'salt.modules.ps': no module named salt.modules.ps
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 3 source files that are out of date
updating environment: 0 added, 1 changed, 0 removed
reading sources... [100%] ref/modules/all/salt.modules.ps                                                                                                                            
/root/salt/doc/ref/modules/all/salt.modules.ps.rst:11: WARNING: autodoc: failed to import module u'salt.modules.ps'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/root/salt/salt/modules/ps.py", line 25, in <module>
    PSUTIL2 = psutil.version_info >= (2, 0)
AttributeError: 'module' object has no attribute 'version_info'
looking for now-outdated files... 47 found
pickling environment... done
```

**Comment by rallytime** [comment]
Thanks @nmadhok. 

ping @jacobhammons and/or @whiteinge

**Comment by nmadhok** [comment]
@rallytime @jacobhammons @whiteinge This has still not been fixed. When i build the docs, they don't get updated because of this.

**Comment by jacobhammons** [comment]
@nmadhok this is an old bug so I'm figuring that you can build docs from develop at this point. Can we close this in favor of the automated doc builds through Jenkins issue @bechtoldt linked? Thanks.

**Comment by rallytime** [comment]
I just tried to build the docs just now on develop. I ran into this error:
```
Exception occurred:
  File "/Users/pinyon/SaltStack/salt/salt/runners/asam.py", line 58, in <module>
    class ASAMHTMLParser(HTMLParser):
NameError: name 'HTMLParser' is not defined
```
However, after fixing that error with #28909, I was able to build the docs successfully. I'm going to go ahead and close this, but if this remains a problem, please leave a comment and we'll be glad to reopen!
