### ISSUE TITLE
salt-cloud VMware driver fails when used with 2014.7.0

### ISSUE THREAD

**Issue by nmadhok** [saltstack/salt#23953]
When using the salt-cloud vmware driver with 2014.7.0, it fails with the following Traceback:

```
[root@develop]# salt-cloud --list-images vcenter03 -l debug
[DEBUG   ] Reading configuration from /etc/salt/cloud
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Guessing ID. The id can be explicitly in set /etc/salt/minion
[INFO    ] Found minion id from generate_minion_id(): abc.domain.com
[DEBUG   ] Missing configuration file: /etc/salt/cloud.providers
[DEBUG   ] Including configuration from '/etc/salt/cloud.providers.d/vmware.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers.d/vmware.conf
[DEBUG   ] Missing configuration file: /etc/salt/cloud.profiles
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/minionvm.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/minionvm.conf
[DEBUG   ] Configuration file path: /etc/salt/cloud
[INFO    ] salt-cloud starting
[DEBUG   ] Failed to import cloud vmware, this is most likely NOT a problem:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/loader.py", line 903, in load_modules
    ), fn_, path, desc
  File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/vmware.py", line 95, in <module>
    import salt.ext.six as six
ImportError: No module named six
[DEBUG   ] 'parallels.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'parallels.avail_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'proxmox.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'saltify.destroy' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'saltify.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'saltify.avail_images' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'saltify.avail_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'rackspace.reboot' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'openstack.list_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] 'rackspace.list_locations' has been marked as not supported. Removing from the list of supported cloud functions
[WARNING ] The cloud driver, 'vmware', configured under the 'vcenter03' cloud provider alias was not loaded since 'vmware.get_configured_provider()' could not be found. Removing it from the available providers list
Error: There was an error listing images: No cloud providers matched 'vcenter03'. Available selections:
```

**Comment by rallytime** [comment]
Thanks for the report and fix, as always @nmadhok. :)

**Comment by nmadhok** [comment]
@rallytime :smile:
