### ISSUE TITLE
state file.managed: setting contents_pillar to a pillar which is a list throws exception instead giving descriptive error message

### ISSUE THREAD

**Issue by mschiff** [saltstack/salt#23973]
Version >=2014.7.1

file.managed's contents_pillar: expects the name of a pillar that is a flat string on the RH side

If you try to hand over a list instead, an exception is throws which is hard to debug / not very user friendly.

Instead a proper error message should be shown.

**Example state sls:**
```yaml
/etc/apt/sources.list.d/salt_managed.list:
  file.managed:
    - contents_pillar: system:packages:sources
```
**Example pillar data:**
```yaml
system:
  packages:
    sources:
      - deb line 1
      - deb line 2
```

**Exception looks like this:**
```python
[INFO    ] Executing state file.managed for /etc/apt/sources.list.d/salt_managed.list
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1563, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 1373, in managed
    if contents and not contents.endswith('\n'):
AttributeError: 'list' object has no attribute 'endswith'

[INFO    ] Completed state [/etc/apt/sources.list.d/salt_managed.list] at time 14:54:56.239563
local:
----------
          ID: /etc/apt/sources.list.d/salt_managed_list
    Function: file.managed
        Name: /etc/apt/sources.list.d/salt_managed.list
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1563, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 1373, in managed
                  if contents and not contents.endswith('\n'):
              AttributeError: 'list' object has no attribute 'endswith'
     Started: 14:54:56.238368
    Duration: 1.195 ms
     Changes:


```

**Comment by jfindlay** [comment]
@mschiff, thanks for the report.
