### ISSUE TITLE
s3fs broken in 2015.5.0-1.el6 epel6 build on Amazon Linux

### ISSUE THREAD

**Issue by wt** [saltstack/salt#23992]
Package version:

```
# yum info salt-master
...
Name        : salt-master
Arch        : noarch
Version     : 2015.5.0
Release     : 1.el6
Size        : 870 k
Repo        : installed
From repo   : epel
...
```

Master log output:

```
2015-05-20 18:55:10,577 [salt.daemons.masterapi                   ][ERROR   ][28159] Exception need more than 1 value to unpack occurred in file server update
2015-05-20 18:56:11,276 [salt.daemons.masterapi                   ][ERROR   ][28159] Exception need more than 1 value to unpack occurred in file server update
2015-05-20 18:56:27,139 [salt.master                              ][ERROR   ][28177] Error in function _file_hash:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/master.py", line 1456, in run_func
    ret = getattr(self, func)(load)
  File "/usr/lib/python2.6/site-packages/salt/fileserver/__init__.py", line 521, in file_hash
    fnd = self.find_file(load['path'], load['saltenv'])
  File "/usr/lib/python2.6/site-packages/salt/fileserver/__init__.py", line 475, in find_file
    fnd = self.servers[fstr](path, saltenv, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/fileserver/s3fs.py", line 159, in find_file
    _get_file_from_s3(metadata, saltenv, fnd['bucket'], path, cached_file_path)
  File "/usr/lib/python2.6/site-packages/salt/fileserver/s3fs.py", line 625, in _get_file_from_s3
    name, value = header.split(':', 1)
ValueError: need more than 1 value to unpack
2015-05-20 18:57:12,053 [salt.daemons.masterapi                   ][ERROR   ][28159] Exception need more than 1 value to unpack occurred in file server update
2015-05-20 18:58:12,837 [salt.daemons.masterapi                   ][ERROR   ][28159] Exception need more than 1 value to unpack occurred in file server update
```

**Comment by jfindlay** [comment]
@wt, thanks for the report.  What is the command you were running and what are the relevant configs if you can share them?  Thanks.

**Comment by jfindlay** [comment]
Possibly related #23567.
