### ISSUE TITLE
[salt-cloud saltify] cannot use --profile saltify machine{1..3} without a map

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#24020]
```
# salt-cloud -p make_salty debian@172.17.17.28
[snip]
[INFO    ] Provisioning existing machine debian@172.17.17.28
[INFO    ] Rendering deploy script: /etc/salt/cloud.deploy.d/bootstrap-salt.sh
[ERROR   ] Failed to create VM debian@172.17.17.28. Configuration value 'ssh_host' needs to be set
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1241, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/saltify.py", line 93, in create
    'host': vm_['ssh_host'],
KeyError: 'ssh_host'
# salt-cloud --versions-report
                  Salt: 2015.5.0
                Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
       Apache Libcloud: 0.15.1
 Debian source package: 2015.5.0+ds-1trusty1

```

Going out to try out with a map file... and bumping into another issue (will file separately).

**Comment by rallytime** [comment]
@arthurlogilab I just tested this and it is working, though it takes some work in defining correct provider/profile files. In order to get this to work, you have to define the profile and profiles for each minion. 

/etc/salt/cloud.providers.d/saltify.conf:
```
saltify-config:
   minion:
     master: <my-salt-master>
   provider: saltify
```
/etc/salt/cloud.profiles.d/saltify.conf
```
make_salty:
   ssh_host: <vm-ip>
   ssh_username: root
   password: <my-password>
   provider: saltify-config
```
Result:
```
# salt-cloud -p make_salty nt1
[INFO    ] salt-cloud starting
<snipped>
[INFO    ] Salt installed on nt1
[DEBUG   ] LazyLoaded nested.output
nt1:
    ----------
    deployed:
        True
# salt nt1 test.ping
nt1:
    True
```
Versions:
```
# salt-cloud --versions
            Salt: 2015.5.5-38-g7a58878
          Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
          Jinja2: 2.7.3
        M2Crypto: 0.21.1
  msgpack-python: 0.4.4
    msgpack-pure: Not Installed
        pycrypto: 2.6.1
         libnacl: Not Installed
          PyYAML: 3.11
           ioflo: Not Installed
           PyZMQ: 14.0.1
            RAET: Not Installed
             ZMQ: 4.0.4
            Mako: 0.9.1
         Tornado: 4.2
         timelib: 0.2.4
        dateutil: 2.4.2
 Apache Libcloud: 0.18.0
```

I'll put together some docs next week explaining this. The docs as they stand are a little lack-luster in outlining how this should all work. (There is also an error stating one of the params should be `ssh_password`, but this doesn't work. It should be just `password`.)

**Comment by rallytime** [comment]
I've update the saltify docs in #26790. As such, I am going to close this issue since I believe this to be working in the 2015.5.5 release. Let me know if the wording is confusing and feel free to open issues for any problems you encounter. Thanks again!
