### ISSUE TITLE
Docker client version mismatch with server when using docker-py

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt#24049]
I ran into this issue today:
```
          ID: setup_docker_image
    Function: docker.built
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.6/site-packages/salt/state.py", line 1563, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.6/site-packages/salt/states/dockerio.py", line 434, in built
                  returned = build(**kw)
                File "/usr/lib/python2.6/site-packages/salt/modules/dockerio.py", line 1390, in build
                  client = _get_client(timeout=timeout)
                File "/usr/lib/python2.6/site-packages/salt/modules/dockerio.py", line 277, in _get_client
                  client._version = client.version()['ApiVersion']
                File "/usr/lib/python2.6/site-packages/docker/client.py", line 1108, in version
                  return self._result(self._get(url), json=True)
                File "/usr/lib/python2.6/site-packages/docker/client.py", line 126, in _result
                  self._raise_for_status(response)
                File "/usr/lib/python2.6/site-packages/docker/client.py", line 122, in _raise_for_status
                  raise errors.APIError(e, response, explanation=explanation)
              APIError: 404 Client Error: Not Found ("client and server don't have same version (client : 1.18, server: 1.17)")
     Started: 21:03:18.907308
    Duration: 23.265 ms
```

for this ID:

```
 setup_docker_image:
  docker.built:
    - path: /home/vagrant/Dockerfile
```

Looking at the docker-py api docs I see that there is a version variable that can be configured to `auto` and it seems like it would address this issue (https://docker-py.readthedocs.org/en/latest/api/).

Is this not used on purpose? I don't see it in the state or module. Or is there a specific reason that auto isn't being used for the version to avoid issues?

When I don't use docker-py and instead just run it as a command it works fine.

**Comment by jfindlay** [comment]
@gravyboat, what version of salt are you using?

**Comment by gravyboat** [comment]
Ahh sorry, this was on 2015.5, was talking about it in the IRC and left that out.

**Comment by eliasp** [comment]
I got:
```
APIError: 404 Client Error: Not Found ("client and server don't have same version (client : 1.18, serv
er: 1.12)")
```
Looking at `salt/modules/dockerio.py`, the solution for a workaround is in `_get_client()`:
```Python
def _get_client(version=None, timeout=None):
    '''
    Get a connection to a docker API (socket or URL)
    based on config.get mechanism (pillar -> grains)

    By default it will use the base docker-py defaults which
    at the time of writing are using the local socket and
    the 1.4 API

    Set those keys in your configuration tree somehow:

        - docker.url: URL to the docker service
        - docker.version: API version to use

    '''
    kwargs = {}
    get = __salt__['config.get']
    for k, p in (('base_url', 'docker.url'),
                 ('version', 'docker.version')):
        param = get(p, NOTSET)
        if param is not NOTSET:
            kwargs[k] = param
```
So I simply put this in `/etc/salt/minion.d/docker.conf` to work around this issue:
```YAML
docker.version: "1.12"
```
Make sure to properly quote the version as string, otherwise it'll be parsed as YAML-float.

**Comment by blueyed** [comment]
Using `docker.version=auto` might help here.
See also https://github.com/saltstack/salt/pull/27600 for a PR to do this automatically.

**Comment by gravyboat** [comment]
This is still biting me in the ass on 2015.8.1, got this today:

```
          ID: install_docka_project_container
    Function: dockerng.running
        Name: docka-docka-docka-test
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1591, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/states/dockerng.py", line 1384, in running
                  image_id = __salt__['dockerng.inspect_image'](image)['Id']
                File "/usr/lib/python2.7/dist-packages/salt/modules/dockerng.py", line 2108, in inspect_image
                  ret = _client_wrapper('inspect_image', name)
                File "/usr/lib/python2.7/dist-packages/salt/modules/dockerng.py", line 569, in wrapper
                  return wrapped(*args, **salt.utils.clean_kwargs(**kwargs))
                File "/usr/lib/python2.7/dist-packages/salt/modules/dockerng.py", line 832, in _client_wrapper
                  exc.explanation)
              CommandExecutionError: Error 404: client and server don't have same version (client : 1.20, server: 1.18)
     Started: 19:57:38.339223
    Duration: 9.836 ms
     Changes:
```

**Comment by blueyed** [comment]
@gravyboat
As far as I understand it should be in the next release, since it is merged already.

**Comment by gravyboat** [comment]
@blueyed Yeah I just realized this didn't make it into the 2015.8.1 release.

**Comment by jfindlay** [comment]
We're in the release process for 2015.8.2 right now, so it should be out in about a week.

**Comment by gravyboat** [comment]
@jfindlay Sounds good! Also please don't work so late, it's not good for you.

**Comment by chris-martin** [comment]
The workaround that @blueyed gave - `docker.version=auto` - where does that go?

**Comment by eliasp** [comment]
@chris-martin See https://github.com/saltstack/salt/issues/24049#issuecomment-113916134 where I outlined this workaround before.

**Comment by wt** [comment]
Isn't this fix released? Shouldn't this bug be closed?

**Comment by cachedout** [comment]
Thanks, @wt. That looks accurate to me.
