### ISSUE TITLE
gpg module: AttributeError: 'ImportResult' object has no attribute 'imported'

### ISSUE THREAD

**Issue by quantonganh** [saltstack/salt#24082]
salt-call --versions-report

```
                  Salt: 2014.7.5
                Python: 2.7.3 (default, Dec 18 2014, 19:10:20)
                Jinja2: 2.6
              M2Crypto: 0.21.1
        msgpack-python: 0.1.10
          msgpack-pure: Not Installed
              pycrypto: 2.4.1
               libnacl: Not Installed
                PyYAML: 3.11
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: Not Installed
 Debian source package: 2014.7.5+ds-1precise1
```

`gpg` module is copied from the upstream.

Trying to import a PRIVATE key:

```
salt-call gpg.import_key filename=/root/.gnupg/secring.txt
```

and got this:

```
[DEBUG   ] imported_data ['stderr', 'fingerprints', 'results', '_problem_reason', '_ok_reason', '_gpg', 'counts', '_fields', 'data']
[DEBUG   ] imported_data OrderedDict([('count', 1), ('no_user_id', 0), ('imported', 0), ('imported_rsa', 0), ('unchanged', 0), ('n_uids', 0), ('n_subk', 0), ('n_sigs', 0), ('n_revoc', 0), ('sec_read', 1), ('sec_imported', 0), ('sec_dups', 1), ('not_imported', 0)])
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'ImportResult' object has no attribute 'imported'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/pymodules/python2.7/salt/scripts.py", line 82, in salt_call
    client.run()
  File "/usr/lib/pymodules/python2.7/salt/cli/__init__.py", line 319, in run
    caller.run()
  File "/usr/lib/pymodules/python2.7/salt/cli/caller.py", line 144, in run
    ret = self.call()
  File "/usr/lib/pymodules/python2.7/salt/cli/caller.py", line 81, in call
    ret['return'] = func(*args, **kwargs)
  File "/var/cache/salt/minion/extmods/modules/gpg.py", line 652, in import_key
    if import_result.imported or import_result.imported_rsa:
AttributeError: 'ImportResult' object has no attribute 'imported'
```

**Comment by jfindlay** [comment]
@quantonganh, thanks for the report and the fix.
