### ISSUE TITLE
win_update encondig problems

### ISSUE THREAD

**Issue by bormotov** [saltstack/salt#24102]
salt 2015.5.0, windows 7/x64 professional, russian edition

salt-call win_update.list_updates verbose=true

minion log
<pre>
2015-05-24 15:55:47,181 [salt.config      ][DEBUG   ][1056] Reading configuration from c:\salt\conf\minion
2015-05-24 15:55:59,774 [salt.loaded.int.grains.core][DEBUG   ][1056] Motherboard info not available on this sytem
2015-05-24 15:55:59,822 [salt.crypt       ][DEBUG   ][1056] Initializing new SAuth for ('c:\\salt\\conf\\pki\\minion', 'minion-host', 'tcp://master-host:4506')
2015-05-24 15:56:01,281 [salt.crypt       ][DEBUG   ][1056] Decrypting the current master AES key
2015-05-24 15:56:01,284 [salt.crypt       ][DEBUG   ][1056] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
2015-05-24 15:56:01,493 [salt.crypt       ][DEBUG   ][1056] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
2015-05-24 15:56:01,523 [salt.utils.lazy  ][DEBUG   ][1056] LazyLoaded jinja.render
2015-05-24 15:56:01,544 [salt.utils.lazy  ][DEBUG   ][1056] LazyLoaded yaml.render
2015-05-24 15:56:01,597 [salt.utils.lazy  ][DEBUG   ][1056] LazyLoaded win_update.list_updates
2015-05-24 15:56:01,610 [salt.loaded.int.module.win_update][DEBUG   ][1056] categories to search for are: None
2015-05-24 15:56:01,613 [salt.loaded.int.module.win_update][DEBUG   ][1056] CoInitializing the pycom system
2015-05-24 15:56:01,616 [salt.loaded.int.module.win_update][DEBUG   ][1056] dispatching update_session to keep the session object.
2015-05-24 15:56:01,646 [salt.loaded.int.module.win_update][DEBUG   ][1056] update_session got. Now creating a win_searcher to seek out the updates
2015-05-24 15:56:01,652 [salt.loaded.int.module.win_update][DEBUG   ][1056] Searching. tries left: 5
2015-05-24 15:56:01,654 [salt.loaded.int.module.win_update][DEBUG   ][1056] generated search string: IsInstalled=0 and IsHidden=0 and Type='Software'
2015-05-24 15:56:01,656 [salt.loaded.int.module.win_update][DEBUG   ][1056] beginning search of the passed string: IsInstalled=0 and IsHidden=0 and Type='Software'
2015-05-24 17:00:42,311 [salt.loaded.int.module.win_update][INFO    ][2724] parsing updates failed. 'ascii' codec can't encode characters in position 0-9: ordinal not in range(128)
2015-05-24 17:01:33,104 [salt.loaded.int.module.win_update][INFO    ][2724] parsing updates failed. 'ascii' codec can't encode characters in position 0-9: ordinal not in range(128)
2015-05-24 17:02:25,615 [salt.loaded.int.module.win_update][INFO    ][2724] parsing updates failed. 'ascii' codec can't encode characters in position 0-9: ordinal not in range(128)
2015-05-24 17:03:11,165 [salt.loaded.int.module.win_update][INFO    ][2724] parsing updates failed. 'ascii' codec can't encode characters in position 0-9: ordinal not in range(128)
2015-05-24 17:04:02,064 [salt.loaded.int.module.win_update][INFO    ][2724] parsing updates failed. 'ascii' codec can't encode characters in position 0-9: ordinal not in range(128)
2015-05-24 17:04:02,154 [salt.log.setup   ][ERROR   ][2724] An un-handled exception was caught by salt's global exception handler:
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-9: ordinal not in range(128)
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 227, in salt_call
    client.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\call.py", line 69, in run
    caller.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 236, in run
    ret = self.call()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 138, in call
    ret['return'] = func(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\modules\win_update.py", line 495, in list_updates
    return str(quidditch.GetSearchResultsPretty())
  File "C:\salt\bin\lib\site-packages\salt\modules\win_update.py", line 303, in GetSearchResultsPretty
    updates = self.GetSearchResults()
  File "C:\salt\bin\lib\site-packages\salt\modules\win_update.py", line 298, in GetSearchResults
    updates.append(str(update))
  File "C:\salt\bin\lib\site-packages\pywin32-219-py2.7-win-amd64.egg\win32com\client\dynamic.py", line 207, in __str__
    return str(self.__call__())
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-9: ordinal not in range(128)
</pre>

at master, output same command looks like
<pre>
    The minion function caused an exception: Traceback (most recent call last):
      File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1142, in _thread_return
        return_data = func(*args, **kwargs)
      File "c:\salt\bin\lib\site-packages\salt\modules\win_update.py", line 495, in list_updates
        return str(quidditch.GetSearchResultsPretty())
      File "c:\salt\bin\lib\site-packages\salt\modules\win_update.py", line 303, in GetSearchResultsPretty
        updates = self.GetSearchResults()
      File "c:\salt\bin\lib\site-packages\salt\modules\win_update.py", line 298, in GetSearchResults
        updates.append(str(update))
      File "c:\salt\bin\lib\site-packages\pywin32-219-py2.7-win-amd64.egg\win32com\client\dynamic.py", line 207, in __str__
        return str(self.__call__())
    UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-9: ordinal not in range(128)
</pre>

**Comment by jfindlay** [comment]
@bormotov, thanks for the report.  I have submitted a change that attempts to fix this.  pywin32 works with complex types in the code causing the error, so there is a chance this won't get fixed so easily.
