### ISSUE TITLE
salt raet transport doesn't works in current version ?

### ISSUE THREAD

**Issue by anan-lee** [saltstack/salt#24107]
when i run salt-master and it  appear blow error:
```python
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/site-packages/salt/daemons/flo/maint.py", line 64, in _maint
    consolepath=consolepath,
  File "/usr/local/lib/python2.7/site-packages/ioflo/app/run.py", line 137, in run
    skedder.run()
  File "/usr/local/lib/python2.7/site-packages/ioflo/base/skedding.py", line 273, in run
    status = tasker.runner.send(tasker.desire)
  File "/usr/local/lib/python2.7/site-packages/ioflo/base/framing.py", line 612, in makeRunner
    self.recur() #.desire may change here
  File "/usr/local/lib/python2.7/site-packages/ioflo/base/framing.py", line 425, in recur
    frame.recur()
  File "/usr/local/lib/python2.7/site-packages/ioflo/base/framing.py", line 1233, in recur
    act()
  File "/usr/local/lib/python2.7/site-packages/ioflo/base/acting.py", line 98, in __call__
    return (self.actor(**self.parms))
  File "/usr/local/lib/python2.7/site-packages/ioflo/base/acting.py", line 460, in __call__
    return self.action(**kwa)
  File "/usr/local/lib/python2.7/site-packages/salt/daemons/flo/core.py", line 633, in action
    self.schedule.eval()
AttributeError: 'SaltSchedule' object has no attribute 'schedule'
```
salt version reports:
```console
[root@test-01 salt-2015.5.1]# salt-master --versions-report
           Salt: 2015.5.0
         Python: 2.7.9 (default, May 22 2015, 17:20:59)
         Jinja2: 2.7.3
       M2Crypto: Not Installed
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: Not Installed
        libnacl: 1.4.2
         PyYAML: 3.11
          ioflo: 1.2.4
          PyZMQ: Not Installed
           RAET: 0.6.3
            ZMQ: Not Installed
           Mako: Not Installed
```

**Comment by jfindlay** [comment]
@anan-lee, thanks for the report, will you also provide the relevant portion of your master config, and the command you were using if any?

**Comment by anan-lee** [comment]
@jfindlay master config as blow:
[root@test-01 ~]# egrep -v "^$|^#" /etc/salt/master 
transport: raet

it appear when i run "/usr/local/bin/python2.7 /usr/local/bin/salt-master".

waiting for your feedback. thx!!

**Comment by cachedout** [comment]
Apologies for the late delay in getting back to you but I cannot reproduce this at the head of the 2015.5 branch. Could you try again using the head of 2015.5, or even better, the latest 2015.8.1 version of Salt? You'll also need to ensure you have the latest versions of the python raet package and ioflo as well.

**Comment by cachedout** [comment]
Since I can verify this as working and we have received no response, I am closing this issue. If the OP responds, we can open this one back up.
