### ISSUE TITLE
salt-ssh has no slspath? 

### ISSUE THREAD

**Issue by The-Loeki** [saltstack/salt#24115]
The var `slspath` seems inoperational in `salt-ssh`, at least in 2015.5?

`salt 2015.5.1-62-g6b43c9a (Lithium)`:

```
    - Rendering SLS 'base:testdeploy' failed: Jinja error: salt:///testvhost.yaml
    - Traceback (most recent call last):
    -   File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 306, in render_jinja_tmpl
    -     output = template.render(**decoded_context)
    -   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    -     return self.environment.handle_exception(exc_info, True)
    -   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    -     reraise(exc_type, exc_value, tb)
    -   File "<template>", line 1, in top-level template code
    -   File "/usr/lib/python2.7/site-packages/salt/utils/jinja.py", line 143, in get_source
    -     raise TemplateNotFound(template)
    - TemplateNotFound: salt:///testvhost.yaml
    -
    - ; line 1
    -
    - ---
    - {% import_yaml 'salt://' + slspath + '/testvhost.yaml' as data %}    <======================

```

**Comment by basepi** [comment]
Thanks for pointing this out. It was probably an oversight in the salt-ssh implementation of the state compiler, and I doubt it has ever worked. We'll get it fixed.

**Comment by bebehei** [comment]
Is this still valid? I can verify, that this works in `salt-ssh 2015.8.7 (Beryllium)`.

Also [you should use `tpldir` instead of `slspath`](https://github.com/saltstack/salt/issues/4348#issuecomment-110331519)

**Comment by basepi** [comment]
Nice, thanks for the verification!
