### ISSUE TITLE
[salt-cloud] VM creation fails with NameError on develop branch

### ISSUE THREAD

**Issue by nmadhok** [saltstack/salt#24176]
```
[ERROR   ] Caught Exception, terminating workers
TRACE: global name 'RSA' is not defined
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 60, in _call
    ret = func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 2192, in create_multiprocessing
    local_master=parallel_data['local_master']
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 1194, in create
    self.opts
  File "/usr/lib/python2.6/site-packages/salt/utils/cloud.py", line 157, in gen_keys
    salt.crypt.gen_keys(tdir, 'minion', keysize)
  File "/usr/lib/python2.6/site-packages/salt/crypt.py", line 88, in gen_keys
    gen = RSA.generate(bits=keysize, e=65537)
NameError: global name 'RSA' is not defined



Error: There was a query error: Exception caught
Caught Exception, terminating workers
TRACE: global name 'RSA' is not defined
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 60, in _call
    ret = func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 2192, in create_multiprocessing
    local_master=parallel_data['local_master']
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 1194, in create
    self.opts
  File "/usr/lib/python2.6/site-packages/salt/utils/cloud.py", line 157, in gen_keys
    salt.crypt.gen_keys(tdir, 'minion', keysize)
  File "/usr/lib/python2.6/site-packages/salt/crypt.py", line 88, in gen_keys
    gen = RSA.generate(bits=keysize, e=65537)
NameError: global name 'RSA' is not defined
```

**Comment by techhat** [comment]
@nmadhok what version of PyCrypto are you running?

**Comment by nmadhok** [comment]
@techhat 

```
root@nitin-salt-develop:~$ pip show pycrypto
---
Name: pycrypto
Version: 2.0.1
Location: /usr/lib64/python2.6/site-packages
Requires: 
```

**Comment by rallytime** [comment]
If you bump that up to 2.6.1, that will help. We'll be depending on pycrypto >= 2.6.1 in packages when Beryllium is released. 

https://github.com/saltstack/salt/blob/develop/requirements/zeromq.txt

Also, from wrestling with the testsuite on Jenkins, if you `pip install pycrypto --upgrade` the 2.6.1 version clashes with the version installed on CentOS 6 and 5. So you have to remove python-crypto (and python26-crypto for CentOS 5) before installing the newer pycrypto version via pip.

**Comment by rallytime** [comment]
@nmadhok I don't know if that will work for what you're trying to do, but that is what I've been battling over the last couple of days as we've removed the dependency on M2Crypto. This is how we're working around it in Jenkins: https://github.com/saltstack/salt-jenkins/blob/master/centos_pycrypto.sls for now.

**Comment by nmadhok** [comment]
@techhat @rallytime Here's what I did but still it didn't get fixed:

First checking what version of pycrypto is currently installed on system:
```
root@nitin-salt-develop:~/salt$ pip show pycrypto
---
Name: pycrypto
Version: 2.0.1
Location: /usr/lib64/python2.6/site-packages
Requires: 
```

Removing pycrypto from the system:
```
root@nitin-salt-develop:~/salt$ yum erase python-crypto
Loaded plugins: product-id, subscription-manager, tsflags
Setting up Remove Process
Resolving Dependencies
--> Running transaction check
---> Package python-crypto.x86_64 0:2.0.1-22.el6 will be erased
--> Processing Dependency: python-crypto for package: python-dns-1.11.1-2.el6.noarch
--> Processing Dependency: python-crypto for package: python-keyczar-0.71c-1.el6.noarch
--> Running transaction check
---> Package python-dns.noarch 0:1.11.1-2.el6 will be erased
---> Package python-keyczar.noarch 0:0.71c-1.el6 will be erased
--> Finished Dependency Resolution

Dependencies Resolved

=====================================================================================================
 Package                     Arch                Version                    Repository          Size
=====================================================================================================
Removing:
 python-crypto               x86_64              2.0.1-22.el6               @os                562 k
Removing for dependencies:
 python-dns                  noarch              1.11.1-2.el6               @epel              1.0 M
 python-keyczar              noarch              0.71c-1.el6                @epel              566 k

Transaction Summary
=====================================================================================================
Remove        3 Package(s)

Installed size: 2.1 M
Is this ok [y/N]: y
Downloading Packages:
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Erasing    : python-dns-1.11.1-2.el6.noarch                                                    1/3 
  Erasing    : python-keyczar-0.71c-1.el6.noarch                                                 2/3 
  Erasing    : python-crypto-2.0.1-22.el6.x86_64                                                 3/3 
  Verifying  : python-crypto-2.0.1-22.el6.x86_64                                                 1/3 
  Verifying  : python-keyczar-0.71c-1.el6.noarch                                                 2/3 
  Verifying  : python-dns-1.11.1-2.el6.noarch                                                    3/3 

Removed:
  python-crypto.x86_64 0:2.0.1-22.el6                                                                

Dependency Removed:
  python-dns.noarch 0:1.11.1-2.el6                python-keyczar.noarch 0:0.71c-1.el6               

Complete!
```

Confirming pycrypto has been removed from the system:
```
root@nitin-salt-develop:~/salt$ pip show pycrypto
root@nitin-salt-develop:~/salt$ rpm -qa | grep crypto
m2crypto-0.20.2-9.el6.x86_64
```

Installing pycrypto >=2.6.1 from pip and then confirming version that was installed:
```
root@nitin-salt-develop:~/salt$ pip install pycrypto
Downloading/unpacking pycrypto
  Running setup.py egg_info for package pycrypto
Installing collected packages: pycrypto
  Running setup.py install for pycrypto
    warning: GMP or MPIR library not found; Not building Crypto.PublicKey._fastmath.
Successfully installed pycrypto
Cleaning up...
root@nitin-salt-develop:~/salt$ pip show pycrypto
---
Name: pycrypto
Version: 2.6.1
Location: /usr/lib64/python2.6/site-packages
Requires: 
root@nitin-salt-develop:~/salt$ 
```

Salt Versions Report:
```
root@nitin-salt-develop:~/salt$ salt --versions-report
Salt Version:
           Salt: 2015.5.1-5593-g1b306c5
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.20.2
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
         Python: 2.6.6 (r266:84292, Nov 21 2013, 10:50:32)
           RAET: Not Installed
            ZMQ: 3.2.5
          ioflo: Not Installed
        libnacl: 1.4.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.4
       pycrypto: 2.6.1
 
System Versions:
           dist: redhat 6.6 Santiago
        machine: x86_64
        release: 2.6.32-504.12.2.el6.x86_64
         system: Red Hat Enterprise Linux Server 6.6 Santiago
```

Here's the new error I got now when creating a VM:
```
The following virtual machines are set to be created:
  salt-oel-1

Proceed? [N/y] y
... proceeding
[INFO    ] Calculating dependencies for salt-oel-1
[DEBUG   ] Got execution order 0 for salt-oel-1
[DEBUG   ] No make_master found in map
[INFO    ] Since parallel deployment is in use, ssh console output is disabled. All ssh output will be logged though
[INFO    ] Cloud pool size: 1
[DEBUG   ] Could not LazyLoad parallels.avail_sizes
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy
[DEBUG   ] Could not LazyLoad saltify.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.avail_images
[DEBUG   ] Could not LazyLoad saltify.avail_locations
[DEBUG   ] LazyLoaded rackspace.reboot
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] LazyLoaded rackspace.list_locations
[DEBUG   ] Generating minion keys for 'salt-oel-1'
[ERROR   ] Caught Exception, terminating workers
TRACE: PID check failed. RNG must be re-initialized after fork(). Hint: Try Random.atfork()
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 60, in _call
    ret = func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 2192, in create_multiprocessing
    local_master=parallel_data['local_master']
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 1194, in create
    self.opts
  File "/usr/lib/python2.6/site-packages/salt/utils/cloud.py", line 157, in gen_keys
    salt.crypt.gen_keys(tdir, 'minion', keysize)
  File "/usr/lib/python2.6/site-packages/salt/crypt.py", line 88, in gen_keys
    gen = RSA.generate(bits=keysize, e=65537)
  File "/usr/lib64/python2.6/site-packages/Crypto/PublicKey/RSA.py", line 508, in generate
    obj = _RSA.generate_py(bits, rf, progress_func, e)    # TODO: Don't use legacy _RSA module
  File "/usr/lib64/python2.6/site-packages/Crypto/PublicKey/_RSA.py", line 50, in generate_py
    p = pubkey.getStrongPrime(bits>>1, obj.e, 1e-12, randfunc)
  File "/usr/lib64/python2.6/site-packages/Crypto/Util/number.py", line 282, in getStrongPrime
    X = getRandomRange (lower_bound, upper_bound, randfunc)
  File "/usr/lib64/python2.6/site-packages/Crypto/Util/number.py", line 123, in getRandomRange
    value = getRandomInteger(bits, randfunc)
  File "/usr/lib64/python2.6/site-packages/Crypto/Util/number.py", line 104, in getRandomInteger
    S = randfunc(N>>3)
  File "/usr/lib64/python2.6/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 202, in read
    return self._singleton.read(bytes)
  File "/usr/lib64/python2.6/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 178, in read
    return _UserFriendlyRNG.read(self, bytes)
  File "/usr/lib64/python2.6/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 137, in read
    self._check_pid()
  File "/usr/lib64/python2.6/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 153, in _check_pid
    raise AssertionError("PID check failed. RNG must be re-initialized after fork(). Hint: Try Random.atfork()")
AssertionError: PID check failed. RNG must be re-initialized after fork(). Hint: Try Random.atfork()



Error: There was a query error: Exception caught
Caught Exception, terminating workers
TRACE: PID check failed. RNG must be re-initialized after fork(). Hint: Try Random.atfork()
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 60, in _call
    ret = func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 2192, in create_multiprocessing
    local_master=parallel_data['local_master']
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 1194, in create
    self.opts
  File "/usr/lib/python2.6/site-packages/salt/utils/cloud.py", line 157, in gen_keys
    salt.crypt.gen_keys(tdir, 'minion', keysize)
  File "/usr/lib/python2.6/site-packages/salt/crypt.py", line 88, in gen_keys
    gen = RSA.generate(bits=keysize, e=65537)
  File "/usr/lib64/python2.6/site-packages/Crypto/PublicKey/RSA.py", line 508, in generate
    obj = _RSA.generate_py(bits, rf, progress_func, e)    # TODO: Don't use legacy _RSA module
  File "/usr/lib64/python2.6/site-packages/Crypto/PublicKey/_RSA.py", line 50, in generate_py
    p = pubkey.getStrongPrime(bits>>1, obj.e, 1e-12, randfunc)
  File "/usr/lib64/python2.6/site-packages/Crypto/Util/number.py", line 282, in getStrongPrime
    X = getRandomRange (lower_bound, upper_bound, randfunc)
  File "/usr/lib64/python2.6/site-packages/Crypto/Util/number.py", line 123, in getRandomRange
    value = getRandomInteger(bits, randfunc)
  File "/usr/lib64/python2.6/site-packages/Crypto/Util/number.py", line 104, in getRandomInteger
    S = randfunc(N>>3)
  File "/usr/lib64/python2.6/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 202, in read
    return self._singleton.read(bytes)
  File "/usr/lib64/python2.6/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 178, in read
    return _UserFriendlyRNG.read(self, bytes)
  File "/usr/lib64/python2.6/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 137, in read
    self._check_pid()
  File "/usr/lib64/python2.6/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 153, in _check_pid
    raise AssertionError("PID check failed. RNG must be re-initialized after fork(). Hint: Try Random.atfork()")
AssertionError: PID check failed. RNG must be re-initialized after fork(). Hint: Try Random.atfork()
```

**Comment by rallytime** [comment]
@nmadhok Just to make sure we're on the same page: You're using CentOS 6 for your master, and then you're creating a new minion via salt-cloud. Is the new minion you're creating also on CentOS 6? Because the machine you're creating, at least until we get pycrypto 2.6.1 packaged for CentOS 5/6 will have the same problem.

**Comment by nmadhok** [comment]
@rallytime that's correct. That's doesn't matter because the VM doesn't even get created and I get the error before its creation. The version of salt that gets installed on the minion is 2014.7.1.

**Comment by rallytime** [comment]
@nmadhok Ok good info. Thanks!

@msteed Can you take a look at this one when you get a chance?

**Comment by msteed** [comment]
Thanks @nmadhok - looks like we missed a couple places where the RNG needs to be reinitialized

**Comment by msteed** [comment]
@nmadhok - please give this a try and let us know how it goes

**Comment by nmadhok** [comment]
@msteed That worked! Confirmed fixed! Closing this issue.
