### ISSUE TITLE
S3 `ext_pillar` not loading anymore after updating to 2015.5.0

### ISSUE THREAD

**Issue by johnwchadwick** [saltstack/salt#24258]
My configuration has not changed.

```
ext_pillar:
  - s3:
      bucket: blah-salt
      environment: staging
      prefix: pillar/staging
      verify_ssl: False
      multiple_env: False
```

It feels like this may be related to new syntax allowing minion ID to be specified.

```
[ERROR   ] Failed to load ext_pillar s3: ext_pillar() takes at least 6 arguments (7 given)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 531, in ext_pillar
    key)
  File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 490, in _external_pillar_data
    ext = self.ext_pillars[key](self.opts['id'], pillar, **val)
```

No clue what's going on, it seems like it should still work. I am still investigating.

**Comment by johnwchadwick** [comment]
I have not figured out what my issue is, but i think something has gone awry on my end. Closing this.
