### ISSUE TITLE
"Global name '__salt__' is not defined" in file.managed state on FreeBSD

### ISSUE THREAD

**Issue by r2d2k** [saltstack/salt#24273]
Hi,

when i try to use a file.managed state, the following error will ocurred:

```
salt-master# salt salt-minion state.sls motd
salt-minion:
----------
          ID: motd-cfg
    Function: file.managed
        Name: /etc/motd
      Result: False
     Comment: Unable to manage file: global name '__salt__' is not defined
     Started: 10:12:35.042835
    Duration: 229.335 ms
     Changes:

Summary
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
```

This work normally on 2014.7.5 and was broken after update to 2015.5.1

OS: FreeBSD 10.1-RELEASE-p10 i386
SaltStack details:

```
        Salt: 2015.5.1
      Python: 2.7.9 (default, May 30 2015, 19:08:13)
      Jinja2: 2.7.3
    M2Crypto: 0.22
gpack-python: 0.4.2
msgpack-pure: Not Installed
    pycrypto: 2.6.1
     libnacl: 1.4.2
      PyYAML: 3.11
       ioflo: 1.2.4
       PyZMQ: 14.5.0
        RAET: 0.6.3
         ZMQ: 4.0.5
        Mako: Not Installed
```

Content of minion log on client:

```
2015-05-31 10:12:34,791 [salt.template                              ][DEBUG   ][18269] Rendered data from file: /var/cache/salt/minion/files/base/motd/init.sls:
motd-cfg:
  file.managed:
    - name: /etc/motd
    - user: root
    - group: wheel
    - mode: 0644
    - source: salt://motd/motd.template
    - template: jinja

2015-05-31 10:12:34,869 [salt.loaded.int.render.yaml                ][DEBUG   ][18269] Results of YAML rendering:
OrderedDict([('motd-cfg', OrderedDict([('file.managed', [OrderedDict([('name', '/etc/motd')]), OrderedDict([('user', 'root')]), OrderedDict([('group', 'wheel')]), OrderedDict([('mode', 644)]), OrderedDict([('source', 'salt://motd/motd.template')]), OrderedDict([('template', 'jinja')])])]))])
2015-05-31 10:12:34,918 [salt.loader                                ][DEBUG   ][18269] Error loading states.ipmi: No module named pyghmi.ipmi
2015-05-31 10:12:35,008 [salt.utils.lazy                            ][DEBUG   ][18269] Could not LazyLoad file.mod_init
2015-05-31 10:12:35,043 [salt.state                                 ][INFO    ][18269] Running state [/etc/motd] at time 10:12:35.042835
2015-05-31 10:12:35,107 [salt.state                                 ][INFO    ][18269] Executing state file.managed for /etc/motd
2015-05-31 10:12:35,178 [salt.loaded.int.states.file                ][DEBUG   ][18269] Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/salt/states/file.py", line 1443, in managed
    **kwargs
  File "/usr/local/lib/python2.7/site-packages/salt/modules/file.py", line 2767, in get_managed
    sfn = __salt__['cp.cache_file'](source] saltenv)
NameError: global name '__salt__' is not defined

2015-05-31 10:12:35,229 [salt.state                                 ][ERROR   ][18269] Unable to manage file: global name '__salt__' is not defined
2015-05-31 10:12:35,272 [salt.state                                 ][INFO    ][18269] Completed state [/etc/motd] at time 10:12:35.272170
```

**Comment by jfindlay** [comment]
@r2d2k, is it possible for you to also provide the motd.sls file?  Thanks.

**Comment by r2d2k** [comment]
You can see it in the debug output. 
Here it is:

    motd-cfg:
      file.managed:
        - name: /etc/motd
        - user: root
        - group: wheel
        - mode: 0644
        - source: salt://motd/motd.template
        - template: jinja

**Comment by jfindlay** [comment]
@r2d2k, of course, sorry, thanks.
