### ISSUE TITLE
mount.mount calls file.mkdir with incorrect named argument

### ISSUE THREAD

**Issue by objectx** [saltstack/salt#24296]
```
$ uname -a
Darwin hazel.local 13.4.0 Darwin Kernel Version 13.4.0: Wed Mar 18 16:20:14 PDT 2015; root:xnu-2422.115.14~1/RELEASE_X86_64 x86_64 i386 MacBookPro11,3 Darwin

$ sudo salt-call --version
salt-call 2015.5.0 (Lithium)

$ sudo salt-call -l trace --local mount.mount /Volumes/Download 192.168.0.4:/share/Download True nfs opts="vers=3,nfc,soft,rdirplus"

[DEBUG   ] Missing configuration file: /etc/salt/minion
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: hazel.local
[TRACE   ] None of the required configuration sections, 'logstash_udp_handler' and 'logstash_zmq_handler', were found the in the configuration. Not loading the Logstash logging handlers module.
[DEBUG   ] Configuration file path: /etc/salt/minion
[TRACE   ] Trying pysss.getgrouplist for 'root'
[TRACE   ] Trying generic group list for 'root'
[TRACE   ] Group list for user 'root': ['admin', 'certusers', 'daemon', 'kmem', 'operator', 'procmod', 'procview', 'staff', 'sys', 'tty']
[DEBUG   ] Missing configuration file: /etc/salt/minion
[TRACE   ] 'ip' could not be found in the following search path: ['/Users/objectx/.gvm/vertx/current/bin', '/Users/objectx/.gvm/springboot/current/bin', '/Users/objectx/.gvm/lazybones/current/bin', '/Users/objectx/.gvm/jbake/current/bin', '/Users/objectx/.gvm/groovyserv/current/bin', '/Users/objectx/.gvm/groovy/current/bin', '/Users/objectx/.gvm/griffon/current/bin', '/Users/objectx/.gvm/grails/current/bin', '/Users/objectx/.gvm/gradle/current/bin', '/Users/objectx/.gvm/glide/current/bin', '/Users/objectx/.gvm/gaiden/current/bin', '/Users/objectx/.gvm/crash/current/bin', '/Users/objectx/.gvm/asciidoctorj/current/bin', '/Users/objectx/.cabal/bin', '/usr/local/opt/coreutils/libexec/gnubin', '/usr/local/bin', '/usr/local/sbin', '/usr/bin', '/bin', '/usr/sbin', '/sbin']
[TRACE   ] 'ip' could not be found in the following search path: ['/Users/objectx/.gvm/vertx/current/bin', '/Users/objectx/.gvm/springboot/current/bin', '/Users/objectx/.gvm/lazybones/current/bin', '/Users/objectx/.gvm/jbake/current/bin', '/Users/objectx/.gvm/groovyserv/current/bin', '/Users/objectx/.gvm/groovy/current/bin', '/Users/objectx/.gvm/griffon/current/bin', '/Users/objectx/.gvm/grails/current/bin', '/Users/objectx/.gvm/gradle/current/bin', '/Users/objectx/.gvm/glide/current/bin', '/Users/objectx/.gvm/gaiden/current/bin', '/Users/objectx/.gvm/crash/current/bin', '/Users/objectx/.gvm/asciidoctorj/current/bin', '/Users/objectx/.cabal/bin', '/usr/local/opt/coreutils/libexec/gnubin', '/usr/local/bin', '/usr/local/sbin', '/usr/bin', '/bin', '/usr/sbin', '/sbin']
[TRACE   ] 'ip' could not be found in the following search path: ['/Users/objectx/.gvm/vertx/current/bin', '/Users/objectx/.gvm/springboot/current/bin', '/Users/objectx/.gvm/lazybones/current/bin', '/Users/objectx/.gvm/jbake/current/bin', '/Users/objectx/.gvm/groovyserv/current/bin', '/Users/objectx/.gvm/groovy/current/bin', '/Users/objectx/.gvm/griffon/current/bin', '/Users/objectx/.gvm/grails/current/bin', '/Users/objectx/.gvm/gradle/current/bin', '/Users/objectx/.gvm/glide/current/bin', '/Users/objectx/.gvm/gaiden/current/bin', '/Users/objectx/.gvm/crash/current/bin', '/Users/objectx/.gvm/asciidoctorj/current/bin', '/Users/objectx/.cabal/bin', '/usr/local/opt/coreutils/libexec/gnubin', '/usr/local/bin', '/usr/local/sbin', '/usr/bin', '/bin', '/usr/sbin', '/sbin']
[TRACE   ] SSD grain does not support OS
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded mount.mount
[DEBUG   ] LazyLoaded file.mkdir
Passed invalid arguments: mkdir() got an unexpected keyword argument 'name'
Traceback (most recent call last):
  File "/usr/local/Cellar/saltstack/2015.5.0/libexec/lib/python2.7/site-packages/salt/cli/caller.py", line 138, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/local/Cellar/saltstack/2015.5.0/libexec/lib/python2.7/site-packages/salt/modules/mount.py", line 690, in mount
    __salt__['file.mkdir'](name=name, user=user)
TypeError: mkdir() got an unexpected keyword argument 'name'
```

**Comment by jfindlay** [comment]
@objectx, thanks for the report.  The fix will be in 2015.5.3, which will come out in about a month.
