### ISSUE TITLE
vbox_guest.additions_install  fails on Centos 7.1

### ISSUE THREAD

**Issue by jmiller0** [saltstack/salt#24303]
I realize there is a warning that states that Centos is not fully supported yet however it looks broken.  I can't mount /dev/cdrom but I can mount /media/VBoxGuestAdditions.

```
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: testhost.localdomain
[DEBUG   ] Configuration file path: /etc/salt/minion
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'testhost.localdomain', 'tcp://10.84.108.70:4506')
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded vbox_guest.additions_install
[DEBUG   ] LazyLoaded mount.mount
[DEBUG   ] LazyLoaded cmd.run_all
[INFO    ] Executing command 'mount -o defaults /dev/cdrom /tmp/tmpbnaiqz ' in directory '/root'
[DEBUG   ] stderr: mount: /dev/sr0 is write-protected, mounting read-only
[WARNING ] CentOS is not fully supported yet.
[INFO    ] Executing command '/tmp/tmpbnaiqz/VBoxLinuxAdditions.run' in directory '/root'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 138, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/vbox_guest.py", line 85, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/vbox_guest.py", line 185, in additions_install
    return _additions_install_linux(mount_point, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/vbox_guest.py", line 137, in _additions_install_linux
    installer_ret = __salt__['cmd.run_all'](installer_path)
  File "/usr/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 1014, in run_all
    use_vt=use_vt)
  File "/usr/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 391, in _run
    .format(cmd, kwargs, exc)
CommandExecutionError: Unable to run command ['/tmp/tmpbnaiqz/VBoxLinuxAdditions.run'] with the context {'with_communicate': True, 'shell': False, 'env': {'LESSOPEN': '||/usr/bin/lesspipe.sh %s', 'SSH_CLIENT': '10.71.30.121 20068 22', 'LOGNAME': 'root', 'USER': 'root', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin', 'HOME': '/root', 'LANG': 'en_US.UTF-8', 'TERM': 'linux', 'SHELL': '/bin/bash', 'SHLVL': '1', 'HISTSIZE': '1000', 'XDG_RUNTIME_DIR': '/run/user/0', 'COBBLER_SERVER': '10.84.108.71', 'LC_ALL': 'C', 'XDG_SESSION_ID': '3771', '_': '/usr/bin/salt-call', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:', 'SSH_TTY': '/dev/pts/0', 'OLDPWD': '/root', 'HOSTNAME': 'testhost.localdomain', 'HISTCONTROL': 'ignoredups', 'PWD': '/etc/yum.repos.d', 'MAIL': '/var/spool/mail/root', 'SSH_CONNECTION': '10.71.30.121 20068 10.84.108.68 22'}, 'stdout': -1, 'close_fds': True, 'stdin': None, 'stderr': -1, 'cwd': '/root'}, reason: [Errno 2] No such file or directory
Error running 'vbox_guest.additions_install': Unable to run command ['/tmp/tmpbnaiqz/VBoxLinuxAdditions.run'] with the context {'with_communicate': True, 'shell': False, 'env': {'LESSOPEN': '||/usr/bin/lesspipe.sh %s', 'SSH_CLIENT': '10.71.30.121 20068 22', 'LOGNAME': 'root', 'USER': 'root', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin', 'HOME': '/root', 'LANG': 'en_US.UTF-8', 'TERM': 'linux', 'SHELL': '/bin/bash', 'SHLVL': '1', 'HISTSIZE': '1000', 'XDG_RUNTIME_DIR': '/run/user/0', 'COBBLER_SERVER': '10.84.108.71', 'LC_ALL': 'C', 'XDG_SESSION_ID': '3771', '_': '/usr/bin/salt-call', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:', 'SSH_TTY': '/dev/pts/0', 'OLDPWD': '/root', 'HOSTNAME': 'testhost.localdomain', 'HISTCONTROL': 'ignoredups', 'PWD': '/etc/yum.repos.d', 'MAIL': '/var/spool/mail/root', 'SSH_CONNECTION': '10.71.30.121 20068 10.84.108.68 22'}, 'stdout': -1, 'close_fds': True, 'stdin': None, 'stderr': -1, 'cwd': '/root'}, reason: [Errno 2] No such file or directory
```

Thanks

**Comment by jfindlay** [comment]
@jmiller0, thanks for the report.
