### ISSUE TITLE
uncaught exception for pkgrepo.absent for invalid PPA

### ISSUE THREAD

**Issue by favadi** [saltstack/salt#24318]
State file:

```yaml
debug:
  pkgrepo:
    - absent
    - ppa: invalid_jjjjjjjjj/fdsafsd
```

When running `state.sls` I got following uncaught exception error:

```yaml
local:
----------
          ID: debug
    Function: pkgrepo.absent
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/vagrant/salt/salt/state.py", line 1590, in call
                  **cdata['kwargs'])
                File "/vagrant/salt/salt/states/pkgrepo.py", line 415, in absent
                  name, ppa_auth=kwargs.get('ppa_auth', None)
                File "/vagrant/salt/salt/modules/aptpkg.py", line 1270, in get_repo
                  repo = softwareproperties.ppa.PPAShortcutHandler(repo).expand(
                File "/usr/lib/python2.7/dist-packages/softwareproperties/ppa.py", line 348, in __init__
                  info = get_ppa_info(shortcut)
                File "/usr/lib/python2.7/dist-packages/softwareproperties/ppa.py", line 336, in get_ppa_info
                  _get_suggested_ppa_message(user))
                File "/usr/lib/python2.7/dist-packages/softwareproperties/ppa.py", line 293, in _get_suggested_ppa_message
                  lp = Launchpad.login_anonymously(lp_application_name, "production")
              NameError: global name 'lp_application_name' is not defined
     Started: 05:31:43.513009
    Duration: 2657.977 ms
     Changes:

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
```

I tested with latest salt version from develop.

```yaml
Salt Version:
           Salt: 2015.5.0

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.6.0
         Python: 2.7.6 (default, Mar 22 2014, 22:59:38)
           RAET: Not Installed
            ZMQ: 4.0.5
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
       pycrypto: 2.6.1

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: i686
        release: 3.13.0-53-generic
         system: Ubuntu 14.04 trusty
```

**Comment by jfindlay** [comment]
This looks technically like an upstream that can be handled by a `try ... except NameError` in salt.

**Comment by jfindlay** [comment]
@favadi, thanks for the report.

**Comment by dgorissen** [comment]
FYI, Interestingly I occasionally get this on salt 2016.11.0

State:

````
btrfs_backports_ppa:
  pkgrepo.managed:
    - ppa: benjamin-c/btrfs-tools-4.4-1
````

Error:

```
ID: btrfs_backports_ppa
    Function: pkgrepo.managed
      Result: False
     Comment: Failed to examine repo 'btrfs_backports_ppa': Could not find ppa ppa:benjamin-c/btrfs-tools-4.4-1: global name 'lp_application_name' is not defined
     Started: 15:15:25.862787
    Duration: 229.226 ms
     Changes:
```

Perhaps a network glitch.

**Comment by lichtamberg** [comment]
I have the same with 2016.11.0
