### ISSUE TITLE
freebsd 9.3 and 2015.5.2 causes a traceback when specifying provider pkg:pkgng in the minion config

### ISSUE THREAD

**Issue by eedgar** [saltstack/salt#24340]
in minion.config

``` yaml
providers:
   pkg: pkgng
```

``` yaml
         Salt: 2015.5.1
         Python: 2.7.9 (default, May 20 2015, 23:14:21)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.6.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
```

This is needed because I have 
WITH_PKGNG=yes in my /etc/make.conf

``` python
Traceback (most recent call last):
  File "/usr/local/bin/salt-call", line 9, in <module>
    load_entry_point('salt==2015.5.1', 'console_scripts', 'salt-call')()
  File "/usr/local/lib/python2.7/site-packages/salt/scripts.py", line 227, in salt_call
    client.run()
  File "/usr/local/lib/python2.7/site-packages/salt/cli/call.py", line 69, in run
    caller.run()
  File "/usr/local/lib/python2.7/site-packages/salt/cli/caller.py", line 236, in run
    ret = self.call()
  File "/usr/local/lib/python2.7/site-packages/salt/cli/caller.py", line 138, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/salt/modules/state.py", line 468, in highstate
    if _disabled(['highstate']):
  File "/usr/local/lib/python2.7/site-packages/salt/modules/state.py", line 1277, in _disabled
    _disabled = __salt__['grains.get']('state_runs_disabled')
NameError: global name '__salt__' is not defined
```

**Comment by eedgar** [comment]
the command I ran was very simple.

salt-call state.highstate 

and this is the full output 

[ERROR   ] An un-handled exception was caught by salt's global exception handler:
NameError: global name '__salt__' is not defined
Traceback (most recent call last):
  File "/usr/local/bin/salt-call", line 9, in <module>
    load_entry_point('salt==2015.5.1', 'console_scripts', 'salt-call')()
  File "/usr/local/lib/python2.7/site-packages/salt/scripts.py", line 227, in salt_call
    client.run()
  File "/usr/local/lib/python2.7/site-packages/salt/cli/call.py", line 69, in run
    caller.run()
  File "/usr/local/lib/python2.7/site-packages/salt/cli/caller.py", line 236, in run
    ret = self.call()
  File "/usr/local/lib/python2.7/site-packages/salt/cli/caller.py", line 138, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/salt/modules/state.py", line 468, in highstate
    if _disabled(['highstate']):
  File "/usr/local/lib/python2.7/site-packages/salt/modules/state.py", line 1277, in _disabled
    _disabled = __salt__['grains.get']('state_runs_disabled')
NameError: global name '__salt__' is not defined
Traceback (most recent call last):
  File "/usr/local/bin/salt-call", line 9, in <module>
    load_entry_point('salt==2015.5.1', 'console_scripts', 'salt-call')()
  File "/usr/local/lib/python2.7/site-packages/salt/scripts.py", line 227, in salt_call
    client.run()
  File "/usr/local/lib/python2.7/site-packages/salt/cli/call.py", line 69, in run
    caller.run()
  File "/usr/local/lib/python2.7/site-packages/salt/cli/caller.py", line 236, in run
    ret = self.call()
  File "/usr/local/lib/python2.7/site-packages/salt/cli/caller.py", line 138, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/salt/modules/state.py", line 468, in highstate
    if _disabled(['highstate']):
  File "/usr/local/lib/python2.7/site-packages/salt/modules/state.py", line 1277, in _disabled
    _disabled = __salt__['grains.get']('state_runs_disabled')
NameError: global name '__salt__' is not defined

**Comment by eedgar** [comment]
for me to work around the issue, I had to remove the provider line and create a patch that selects pkgng for myself.

--- pkgng.py.orig       2015-06-02 12:24:43.000000000 -0500
+++ pkgng.py    2015-06-02 12:24:55.000000000 -0500
@@ -52,7 +52,7 @@
     '''
     Load as 'pkg' on FreeBSD 10 and greater
     '''
-    if __grains__['os'] == 'FreeBSD' and float(__grains__['osrelease']) >= 10:
+    if __grains__['os'] == 'FreeBSD' and float(__grains__['osrelease']) >= 9:
         return __virtualname__
     return False

--- freebsdpkg.py.orig  2015-06-02 12:24:12.000000000 -0500
+++ freebsdpkg.py       2015-06-02 12:24:30.000000000 -0500
@@ -88,6 +88,7 @@
     '''
     Load as 'pkg' on FreeBSD versions less than 10
     '''
+    return False
     if __grains__['os'] == 'FreeBSD' and float(__grains__['osrelease']) < 10:
         return __virtualname__
     return False



This is not a fix for others but a work around.  the main bug is elsewhere...

**Comment by jfindlay** [comment]
@eedgar, thanks for the report.

**Comment by alexjarvis** [comment]
Being bitten by this as well. Sadly makes it impossible to to use Salt to control my FreeBSD 9.3 Jails.
