### ISSUE TITLE
FreeBSD minion provider pkg issue

### ISSUE THREAD

**Issue by m87carlson** [saltstack/salt#24350]
## Issue

With the latest version of salt, a salt-call fails when we have:

```
providers:
  pkg: pkgng
```

specified in /usr/local/etc/salt/minion

Output of the failure:

```
# salt-call state.sls pkgng
[INFO    ] Executing command '/sbin/zfs -?' in directory '/root'
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
NameError: global name '__salt__' is not defined
Traceback (most recent call last):
  File "/usr/local/bin/salt-call", line 9, in <module>
    load_entry_point('salt==2015.5.1', 'console_scripts', 'salt-call')()
  File "/usr/local/lib/python2.7/site-packages/salt/scripts.py", line 227, in salt_call
    client.run()
  File "/usr/local/lib/python2.7/site-packages/salt/cli/call.py", line 69, in run
    caller.run()
  File "/usr/local/lib/python2.7/site-packages/salt/cli/caller.py", line 236, in run
    ret = self.call()
  File "/usr/local/lib/python2.7/site-packages/salt/cli/caller.py", line 138, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/salt/modules/state.py", line 604, in sls
    conflict = running(concurrent)
  File "/usr/local/lib/python2.7/site-packages/salt/modules/state.py", line 110, in running
    active = __salt__['saltutil.is_running']('state.*')
NameError: global name '__salt__' is not defined
Traceback (most recent call last):
  File "/usr/local/bin/salt-call", line 9, in <module>
    load_entry_point('salt==2015.5.1', 'console_scripts', 'salt-call')()
  File "/usr/local/lib/python2.7/site-packages/salt/scripts.py", line 227, in salt_call
    client.run()
  File "/usr/local/lib/python2.7/site-packages/salt/cli/call.py", line 69, in run
    caller.run()
  File "/usr/local/lib/python2.7/site-packages/salt/cli/caller.py", line 236, in run
    ret = self.call()
  File "/usr/local/lib/python2.7/site-packages/salt/cli/caller.py", line 138, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/salt/modules/state.py", line 604, in sls
    conflict = running(concurrent)
  File "/usr/local/lib/python2.7/site-packages/salt/modules/state.py", line 110, in running
    active = __salt__['saltutil.is_running']('state.*')
NameError: global name '__salt__' is not defined
```
## Impact

This is an issue with our 9.1-RELEASE systems, we are a full pkgng environment with our own build cluster.

We can not run any highstates or individual states now. We are moving away from 9.x to 10.x, but we are not there yet.
## Salt Versions Report

```
# salt --versions-report
           Salt: 2015.5.1
         Python: 2.7.9 (default, Jun  2 2015, 11:54:11)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.6.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
```
## OS Version

```
# uname -a
FreeBSD mon-2.discdrive.bayphoto.com 9.1-RELEASE-p3 FreeBSD 9.1-RELEASE-p3 #0: Mon Apr 29 18:27:25 UTC 2013     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
```

**Comment by cedwards** [comment]
This looks related to #24340.

**Comment by jfindlay** [comment]
@m87carlson, thanks for the report.

**Comment by ari** [comment]
I can also confirm this bug with salt 2015.5.2. And perhaps it is related to this other one I hit: #25476
