### ISSUE TITLE
Salt-ssh partial thin generation cleanup

### ISSUE THREAD

**Issue by basepi** [saltstack/salt#24376]
If you start salt-ssh, then promptly interrupt it, you'll get this traceback on your next run:

```
root@li1320-79:~# salt-ssh '*' test.ping -i
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
IOError: [Errno 2] No such file or directory: '/var/cache/salt/master/thin/version'
Traceback (most recent call last):
  File "/usr/local/bin/salt-ssh", line 9, in <module>
    load_entry_point('salt-ssh==2015.5.1', 'console_scripts', 'salt-ssh')()
  File "/usr/local/lib/python2.7/dist-packages/salt/scripts.py", line 273, in salt_ssh
    client.run()
  File "/usr/local/lib/python2.7/dist-packages/salt/cli/ssh.py", line 17, in run
    ssh = salt.client.ssh.SSH(self.config)
  File "/usr/local/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 233, in __init__
    self.thin = salt.utils.thin.gen_thin(self.opts['cachedir'])
  File "/usr/local/lib/python2.7/dist-packages/salt/utils/thin.py", line 89, in gen_thin
    with salt.utils.fopen(thinver) as fh_:
  File "/usr/local/lib/python2.7/dist-packages/salt/utils/__init__.py", line 1044, in fopen
    fhandle = open(*args, **kwargs)
IOError: [Errno 2] No such file or directory: '/var/cache/salt/master/thin/version'
Traceback (most recent call last):
  File "/usr/local/bin/salt-ssh", line 9, in <module>
    load_entry_point('salt-ssh==2015.5.1', 'console_scripts', 'salt-ssh')()
  File "/usr/local/lib/python2.7/dist-packages/salt/scripts.py", line 273, in salt_ssh
    client.run()
  File "/usr/local/lib/python2.7/dist-packages/salt/cli/ssh.py", line 17, in run
    ssh = salt.client.ssh.SSH(self.config)
  File "/usr/local/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 233, in __init__
    self.thin = salt.utils.thin.gen_thin(self.opts['cachedir'])
  File "/usr/local/lib/python2.7/dist-packages/salt/utils/thin.py", line 89, in gen_thin
    with salt.utils.fopen(thinver) as fh_:
  File "/usr/local/lib/python2.7/dist-packages/salt/utils/__init__.py", line 1044, in fopen
    fhandle = open(*args, **kwargs)
IOError: [Errno 2] No such file or directory: '/var/cache/salt/master/thin/version'
```

Easily fixed by deleting the thin directory, but we should handle this automatically.

The source is probably a partial thin generation that wasn't complete. We just need to catch errors like this and cleanup the partial thin.

**Comment by basepi** [comment]
Just kidding, it was fixed here: https://github.com/saltstack/salt/pull/24112
