### ISSUE TITLE
'git' state fails to checkout from a tag

### ISSUE THREAD

**Issue by dtoubelis** [saltstack/salt#24409]
Salt is running on Ubuntu 14.04 with the latest version from the PPA:

```
# salt --versions-report
                  Salt: 2015.5.0
                Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
 Debian source package: 2015.5.0+ds-1trusty1
```

I'm getting intermittent errors with `git` state related to using tags and the most recent ones is this:

```
[INFO    ] Running state [git@bitbucket.org:mijem/web-client.git] at time 16:51:20.123462
[INFO    ] Executing state git.latest for git@bitbucket.org:mijem/web-client.git
[INFO    ] Executing command 'git rev-parse HEAD' as user 'mijem-web' in directory '/home/mijem-web/mijem-web'
[INFO    ] Executing command 'git rev-parse --abbrev-ref HEAD' as user 'mijem-web' in directory '/home/mijem-web/mijem-web'
[INFO    ] Executing command 'git remote show -n origin' as user 'mijem-web' in directory '/home/mijem-web/mijem-web'
[INFO    ] Executing command 'git rev-parse v0.1.0^{commit}' as user 'mijem-web' in directory '/home/mijem-web/mijem-web'
[ERROR   ] Command 'git rev-parse v0.1.0^{commit}' failed with return code: 128
[ERROR   ] output: fatal: ambiguous argument 'v0.1.0^{commit}': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
v0.1.0^{commit}
[INFO    ] Executing command 'git fetch ' as user 'mijem-web' in directory '/home/mijem-web/mijem-web'
[INFO    ] Executing command 'git checkout  -f v0.1.0 ' as user 'mijem-web' in directory '/home/mijem-web/mijem-web'
[INFO    ] Executing command 'git config branch.v0.1.0.remote' as user 'mijem-web' in directory '/home/mijem-web/mijem-web'
[ERROR   ] Command 'git config branch.v0.1.0.remote' failed with return code: 1
[ERROR   ] retcode: 1
[INFO    ] Executing command 'git branch v0.1.0 --set-upstream origin/v0.1.0' in directory '/home/mijem-web/mijem-web'
[ERROR   ] Command 'git branch v0.1.0 --set-upstream origin/v0.1.0' failed with return code: 1
[ERROR   ] stderr: The --set-upstream flag is deprecated and will be removed. Consider using --track or --set-upstream-to
error: the requested upstream branch 'origin/v0.1.0' does not exist
hint:
hint: If you are planning on basing your work on an upstream
hint: branch that already exists at the remote, you may need to
hint: run "git fetch" to retrieve it.
hint:
hint: If you are planning to push out a new local branch that
hint: will track its remote counterpart, you may want to use
hint: "git push -u" to set the upstream config as you push.
[ERROR   ] retcode: 1
[ERROR   ] Unexpected exception in git state
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/states/git.py", line 312, in latest
    user=user)
  File "/usr/lib/python2.7/dist-packages/salt/modules/git.py", line 791, in branch
    _git_run(cmd, cwd=cwd, user=user)
  File "/usr/lib/python2.7/dist-packages/salt/modules/git.py", line 82, in _git_run
    result['stderr']))
CommandExecutionError: Command 'git branch v0.1.0 --set-upstream origin/v0.1.0' failed. Stderr: 'The --set-upstream flag is deprecated and will be removed. Consider using --track or --set-upstream-to\nerror: the requested upstream branch \'origin/v0.1.0\' does not exist\nhint: \nhint: If you are planning on basing your work on an upstream\nhint: branch that already exists at the remote, you may need to\nhint: run "git fetch" to retrieve it.\nhint: \nhint: If you are planning to push out a new local branch that\nhint: will track its remote counterpart, you may want to use\nhint: "git push -u" to set the upstream config as you push.'
[ERROR   ] Command 'git branch v0.1.0 --set-upstream origin/v0.1.0' failed. Stderr: 'The --set-upstream flag is deprecated and will be removed. Consider using --track or --set-upstream-to\nerror: the requested upstream branch \'origin/v0.1.0\' does not exist\nhint: \nhint: If you are planning on basing your work on an upstream\nhint: branch that already exists at the remote, you may need to\nhint: run "git fetch" to retrieve it.\nhint: \nhint: If you are planning to push out a new local branch that\nhint: will track its remote counterpart, you may want to use\nhint: "git push -u" to set the upstream config as you push.'

```

Where `v0.1.0` is a tag in the remote git repository (not a branch). The state definition is as follows:

```
{{ sls_base_name }}-deploy:
  git.latest:
    - name: {{ adminserver.app_git_url }}
    - rev: {{ adminserver.app_version }}
    - target: {{ adminserver.user_home }}/{{ adminserver.app_dir_basename }}
    - identity: {{ adminserver.user_home }}/.ssh/{{ adminserver.ssh_key_name }}.pem
    - user: {{ adminserver.user_name }}
    - force_checkout: True
    - require:
      - pkg: {{ sls_base_name }}-install-pkgs
      - file: {{ sls_base_name }}-ssh-key
```

Also this may or may not be important. The original version of this checkout was `master` and then it was replaced with a specific tag, so `git.latest` is executed in the directory with pre-existing checkout.

**Comment by dtoubelis** [comment]
It is was working in `2014.7.1` and now it is definitely broken.

**Comment by jfindlay** [comment]
@dtoubelis, thanks for the report.

**Comment by pille** [comment]
i'm using this without errors on ubuntu 12.04 LTS precise. 
```
% salt-minion --versions-report
                  Salt: 2015.5.0
                Python: 2.7.3 (default, Dec 18 2014, 19:10:20)
                Jinja2: 2.6
              M2Crypto: 0.21.1
        msgpack-python: 0.1.10
          msgpack-pure: Not Installed
              pycrypto: 2.4.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: Not Installed
 Debian source package: 2015.5.0+ds-1precise1

% git --version
git version 1.7.9.5
```

**Comment by jfindlay** [comment]
@dtoubelis, @pille what is the output of `dpkg -l | grep python-git` or `pip list | grep git` or similar?  Thanks.

**Comment by dtoubelis** [comment]
```
# dpkg -l | grep python-git
ii  python-git                          0.3.2~RC1-3                         all          Python library to interact with Git repositories
ii  python-gitdb                        0.5.4-1                             amd64        pure-Python git object database
```
```
# pip list | grep git
The program 'pip' is currently not installed. You can install it by typing:
apt-get install python-pip
```

**Comment by dtoubelis** [comment]
@pile, could you try to checkout master and then change version to a tag?

It works if I checkout a tag to an empty directory but it fails to switch to a tag and I haven't tried it with branches.

**Comment by pille** [comment]
@jfindlay: python-git is not installed.

@dtoubelis: when i first checkout master and later specify ```rev: stable```, the second step fails:
```
2015-06-10 18:34:55,557 [salt.loaded.int.module.cmdmod][INFO    ][22746] Executing command 'git rev-parse HEAD' as user 'rails' in directory '/tmp/test-mpx-ah-vpp'
2015-06-10 18:34:55,604 [salt.loaded.int.module.cmdmod][INFO    ][22746] Executing command 'git rev-parse --abbrev-ref HEAD' as user 'rails' in directory '/tmp/test-mpx-ah-vpp'
2015-06-10 18:34:55,658 [salt.loaded.int.module.cmdmod][INFO    ][22746] Executing command 'git remote show -n origin' as user 'rails' in directory '/tmp/test-mpx-ah-vpp'
2015-06-10 18:34:55,700 [salt.loaded.int.module.cmdmod][INFO    ][22746] Executing command 'git rev-parse stable^{commit}' as user 'rails' in directory '/tmp/test-mpx-ah-vpp'
2015-06-10 18:34:55,761 [salt.loaded.int.module.cmdmod][INFO    ][22746] Executing command 'git fetch ' as user 'rails' in directory '/tmp/test-mpx-ah-vpp'
2015-06-10 18:34:57,170 [salt.loaded.int.module.cmdmod][INFO    ][22746] Executing command 'git checkout  stable ' as user 'rails' in directory '/tmp/test-mpx-ah-vpp'
2015-06-10 18:34:57,222 [salt.loaded.int.module.cmdmod][INFO    ][22746] Executing command 'git config branch.stable.remote' as user 'rails' in directory '/tmp/test-mpx-ah-vpp'
2015-06-10 18:34:57,233 [salt.loaded.int.module.cmdmod][ERROR   ][22746] Command 'git config branch.stable.remote' failed with return code: 1
2015-06-10 18:34:57,234 [salt.loaded.int.module.cmdmod][ERROR   ][22746] retcode: 1
2015-06-10 18:34:57,234 [salt.loaded.int.module.cmdmod][INFO    ][22746] Executing command 'git branch stable --set-upstream origin/stable' in directory '/tmp/test-mpx-ah-vpp'
2015-06-10 18:34:57,243 [salt.loaded.int.module.cmdmod][ERROR   ][22746] Command 'git branch stable --set-upstream origin/stable' failed with return code: 128
2015-06-10 18:34:57,244 [salt.loaded.int.module.cmdmod][ERROR   ][22746] stderr: fatal: Not a valid object name: 'origin/stable'.
2015-06-10 18:34:57,244 [salt.loaded.int.module.cmdmod][ERROR   ][22746] retcode: 128
2015-06-10 18:34:57,244 [salt.loaded.int.states.git][ERROR   ][22746] Unexpected exception in git state
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/states/git.py", line 312, in latest
    user=user)
  File "/usr/lib/python2.7/dist-packages/salt/modules/git.py", line 791, in branch
    _git_run(cmd, cwd=cwd, user=user)
  File "/usr/lib/python2.7/dist-packages/salt/modules/git.py", line 82, in _git_run
    result['stderr']))
CommandExecutionError: Command 'git branch stable --set-upstream origin/stable' failed. Stderr: "fatal: Not a valid object name: 'origin/stable'."
2015-06-10 18:34:57,274 [salt.state       ][ERROR   ][22746] Command 'git branch stable --set-upstream origin/stable' failed. Stderr: "fatal: Not a valid object name: 'origin/stable'."
```

**Comment by dtoubelis** [comment]
Yep, that is exactly the problem.

**Comment by garrickp** [comment]
+1

Encountered this, but I'm not using a tag, but rather a revision ID. The error message is the same as with the OP.

```
==> monitor: ----------
==> monitor:           ID: git.latest-1024678423259510392
==> monitor:     Function: git.latest
==> monitor:         Name: https://github.com/graphite-project/carbon.git
==> monitor:       Result: False
==> monitor:      Comment: Command 'git branch de072d869087f3bc75a046636dd7f73fafded5e8 --set-upstream origin/de072d869087f3bc75a046636dd7f73fafded5e8' failed.
                           Stderr: 'The --set-upstream flag is deprecated and will be removed. Consider using --track or --set-upstream-to
 error: the requested upstream branch \'origin/de072d869087f3bc75a046636dd7f73fafded5e8\' does not exist
hint: 
hint: If you are planning on basing your work on an upstream
hint: branch that already exists at the remote, you may need to
hint: run "git fetch" to retrieve it.
hint: 
hint: If you are planning to push out a new local branch that
hint: will track its remote counterpart, you may want to use
hint: "git push -u" to set the upstream config as you push.'
==> monitor:      Started: 20:20:00.303972
==> monitor:     Duration: 6637.885 ms
==> monitor:      Changes:
```

Highstate rendering:
```    git.latest-1024678423259510392:
        ----------
        __env__:
            base
        __sls__:
            monitor
        git:
            |_
              ----------
              name:
                  https://github.com/graphite-project/carbon.git
            |_
              ----------
              rev:
                  de072d869087f3bc75a046636dd7f73fafded5e8
            |_
              ----------
              target:
                  /opt/graphite/gitroot/
            |_
              ----------
              require:
                  |_
                    ----------
                    file:
                        file.directory-104312933864815866
            - latest
            |_
              ----------
              order:
                  10107
```

Syntax should probably just be `git checkout de072d869087f3bc75a046636dd7f73fafded5e8`

Motivation: Carbon has a bug which was added in the checkout following this one, so we've pinned this version (which has no tag or branch) for the time being.

**Comment by terminalmage** [comment]
git.latest was rewritten in #26341, which fixes this issue. The fix will be in version 2015.8.0.

As of this rewrite, when a SHA1 or tag is specified as the rev, a branch is checked out at that SHA1. You can also now specify the local branch name to use, where before it would just check out a branch with the same name as the rev, which would create ambiguous refs if a tag was checked out.

The state is also smart enough now not to try to make a non-fast-forward change unless ``force_reset`` is set to ``True``, in which case it performs a ``git reset --hard`` to that SHA1 or tag.

Marking this issue as closed.

**Comment by dtoubelis** [comment]
Excelent. Thanks for your effort.

**Comment by terminalmage** [comment]
No problem. This state has needed some love for a while, glad to have gotten it done. Please don't hesitate to @ mention me in a bug report if you find issues with this after upgrading to 2015.8.0.

**Comment by giorgiosironi** [comment]
We are using these versions:
```
elife@develop--ci:/srv/elife-dashboard$ salt-minion --versions-report
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-36-generic
         system: Ubuntu 14.04 trusty
```
This state fails upon new commits being passed:
```
    git.latest:
        - user: {{ user }}
        - name: git@github.com:elifesciences/elife-dashboard.git
        - rev: {{ ...sha of the commit... }}
        - branch: pinned-revision
        - force_fetch: True
        - force_checkout: True
        - force_reset: True                                                                                                                        
        - target: /srv/elife-dashboard
        - require:
            - file: install-elife-dashboard
```
The error is:
```
11:17:20 [54.226.2.253] out:           ID: install-elife-dashboard
11:17:20 [54.226.2.253] out:     Function: git.latest
11:17:20 [54.226.2.253] out:         Name: ssh://git@github.com/elifesciences/elife-dashboard
11:17:20 [54.226.2.253] out:       Result: False
11:17:20 [54.226.2.253] out:      Comment: Command 'git checkout --force -b pinned-revision d2aca5060a3fda73ec98557387ecad367b0ecb8f' failed
11:17:20 [54.226.2.253] out:      Started: 10:16:23.220615
11:17:20 [54.226.2.253] out:     Duration: 3897.587 ms
11:17:20 [54.226.2.253] out:      Changes:   
```
that when retried manually gives:
```
elife@develop--ci:/srv/elife-dashboard$ git checkout --force -b pinned-revision d2aca5060a3fda73ec98557387ecad367b0ecb8f
fatal: reference is not a tree: d2aca5060a3fda73ec98557387ecad367b0ecb8f
```
which appears to be a problem with a fetch not being performed.

**Comment by giorgiosironi** [comment]
Detailed error output:
```
11:16:48 [54.226.2.253] out: [INFO    ] Running state [ssh://git@github.com/elifesciences/elife-dashboard] at time 10:16:23.220615
11:16:48 [54.226.2.253] out: [INFO    ] Executing state git.latest for ssh://git@github.com/elifesciences/elife-dashboard
11:16:48 [54.226.2.253] out: [INFO    ] Checking remote revision for ssh://git@github.com/elifesciences/elife-dashboard

11:16:49 [54.226.2.253] out: [INFO    ] Executing command ['git', 'ls-remote', 'ssh://git@github.com/elifesciences/elife-dashboard'] as user 'elife' in directory '/home/elife'

11:16:50 [54.226.2.253] out: [INFO    ] Executing command ['git', 'for-each-ref', '--format', '%(refname:short)', 'refs/heads/'] as user 'elife' in directory '/srv/elife-dashboard'
11:16:50 [54.226.2.253] out: [INFO    ] Executing command ['git', 'for-each-ref', '--format', '%(refname:short)', 'refs/tags/'] as user 'elife' in directory '/srv/elife-dashboard'
11:16:50 [54.226.2.253] out: [INFO    ] Checking local revision for /srv/elife-dashboard
11:16:50 [54.226.2.253] out: [INFO    ] Executing command ['git', 'rev-parse', 'HEAD'] as user 'elife' in directory '/srv/elife-dashboard'
11:16:50 [54.226.2.253] out: [INFO    ] Checking local branch for /srv/elife-dashboard
11:16:51 [54.226.2.253] out: [INFO    ] Executing command ['git', 'rev-parse', '--abbrev-ref', 'HEAD'] as user 'elife' in directory '/srv/elife-dashboard'

11:16:51 [54.226.2.253] out: [INFO    ] Executing command ['git', 'remote', '--verbose'] as user 'elife' in directory '/srv/elife-dashboard'
11:16:51 [54.226.2.253] out: [INFO    ] Executing command ['git', 'merge-base', '--is-ancestor', 'd2aca5060a3fda73ec98557387ecad367b0ecb8f', 'd2aca5060a3fda73ec98557387ecad367b0ecb8f'] as user 'elife' in directory '/srv/elife-dashboard'
11:16:51 [54.226.2.253] out: [INFO    ] Executing command ['git', 'rev-parse', '--abbrev-ref', 'develop@{upstream}'] as user 'elife' in directory '/srv/elife-dashboard'

11:16:52 [54.226.2.253] out: [INFO    ] Executing command ['git', 'status', '-z', '--porcelain'] as user 'elife' in directory '/srv/elife-dashboard'
11:16:52 [54.226.2.253] out: [INFO    ] Executing command ['git', 'checkout', '--force', '-b', 'pinned-revision', 'd2aca5060a3fda73ec98557387ecad367b0ecb8f'] as user 'elife' in directory '/srv/elife-dashboard'
11:16:52 [54.226.2.253] out: [ERROR   ] Command ['git', 'checkout', '--force', '-b', 'pinned-revision', 'd2aca5060a3fda73ec98557387ecad367b0ecb8f'] failed with return code: 128
11:16:52 [54.226.2.253] out: [ERROR   ] stdout: fatal: reference is not a tree: d2aca5060a3fda73ec98557387ecad367b0ecb8f
11:16:52 [54.226.2.253] out: [ERROR   ] retcode: 128
11:16:52 [54.226.2.253] out: [ERROR   ] Unexpected exception in git.latest state
11:16:52 [54.226.2.253] out: Traceback (most recent call last):
11:16:52 [54.226.2.253] out:   File "/usr/lib/python2.7/dist-packages/salt/states/git.py", line 1159, in latest
11:16:52 [54.226.2.253] out:     user=user)
11:16:52 [54.226.2.253] out:   File "/usr/lib/python2.7/dist-packages/salt/modules/git.py", line 664, in checkout
11:16:52 [54.226.2.253] out:     redirect_stderr=True)['stdout']
11:16:52 [54.226.2.253] out:   File "/usr/lib/python2.7/dist-packages/salt/modules/git.py", line 288, in _git_run
11:16:52 [54.226.2.253] out:     raise CommandExecutionError(msg)
11:16:52 [54.226.2.253] out: CommandExecutionError: Command 'git checkout --force -b pinned-revision d2aca5060a3fda73ec98557387ecad367b0ecb8f' failed
11:16:52 [54.226.2.253] out: [ERROR   ] Command 'git checkout --force -b pinned-revision d2aca5060a3fda73ec98557387ecad367b0ecb8f' failed
```

**Comment by giorgiosironi** [comment]
What I discovered so far is that the new branch we specify `pinned-revision` triggers a set of conditions for which `has_remote_rev` becomes `True` inside the `latest` function and no fetch is performed as a result.
This happens only if the `pinned-revision` branch is not existing on the local repository.

**Comment by terminalmage** [comment]
This issue has been closed almost a year, and the error message has nothing to do with the original problem. Furthermore, the SLS you posted clearly shows that you are using a SHA instead of a tag, so this is yet another detail that doesn't match this issue.

In these cases, please in the future open a new issue instead of commenting on a long-closed one. I've taken the information you posted and opened https://github.com/saltstack/salt/issues/34367.
