### ISSUE TITLE
Having problem running salt cli command  2015.5.1

### ISSUE THREAD

**Issue by mimianddaniel** [saltstack/salt#24419]
```python
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
KeyError: 'id'
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/scripts.py", line 349, in salt_main
    client.run()
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/cli/salt.py", line 195, in run
    for full_ret in cmd_func(**kwargs):
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/client/__init__.py", line 600, in cmd_cli
    **kwargs):
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/client/__init__.py", line 1295, in get_cli_event_returns
    expect_minions=(verbose or show_timeout)
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/client/__init__.py", line 921, in get_iter_returns
    ret = {raw['data']['id']: raw['data']['data']}
KeyError: 'id'
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/scripts.py", line 349, in salt_main
    client.run()
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/cli/salt.py", line 195, in run
    for full_ret in cmd_func(**kwargs):
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/client/__init__.py", line 600, in cmd_cli
    **kwargs):
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/client/__init__.py", line 1295, in get_cli_event_returns
    expect_minions=(verbose or show_timeout)
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/client/__init__.py", line 921, in get_iter_returns
    ret = {raw['data']['id']: raw['data']['data']}
KeyError: 'id'
```
```yaml
          Salt: 2015.5.1
         Python: 2.7.9 (default, Dec 30 2014, 13:07:54)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.6.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
```

**Comment by ssgward** [comment]
@mimianddaniel - what command are you running to get the error?

**Comment by ssgward** [comment]
And if you are using a state file as part of the command, what is in the state file? Please post sanitized state file if you can.

**Comment by mimianddaniel** [comment]
Simple salt '*' test.ping
But happens with any other modules like cmd.run

**Comment by ssgward** [comment]
Form the error output ``KeyError: 'id'`` it seems to point so some typo or formatting issue with one of the config files: master.conf or minion.conf, perhaps. Running any commands from my salt masters or minions produces no errors on 2015.5.1

**Comment by mimianddaniel** [comment]
since upgrading to 2015.5.2 do not see this problem.

**Comment by frogunder** [comment]
@mimianddaniel - It seems like the upgrade helped, can we close this issue?

**Comment by frogunder** [comment]
Since there has been no activity for a while, I will close this issue
