### ISSUE TITLE
Loading of templates in 2015.5.2 from GitFS in masterless fails with TemplateNotFound

### ISSUE THREAD

**Issue by mattwillsher** [saltstack/salt#24449]
This looks like #17963

```
$ salt-ssh 'salt' state.highstate  -l debug

[DEBUG   ] Rendered data from file: /Users/matt/salt/var/cache/salt/master/files/base/salt/pkgrepo/init.sls:

include:
  - .redhat

[DEBUG   ] Results of YAML rendering:
OrderedDict([('include', ['.redhat'])])
[DEBUG   ] Could not find file from saltenv 'base', 'salt://salt/pkgrepo/redhat.sls'
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache u'salt://salt/pkgrepo/redhat/init.sls'
[DEBUG   ] Could not LazyLoad cmd.run
[DEBUG   ] Could not LazyLoad cmd.shell
[DEBUG   ] Could not LazyLoad cmd.shell
[DEBUG   ] Could not LazyLoad cmd.run
[DEBUG   ] Jinja search path: ['/tmp/.root_3cce2e__salt/running_data/var/cache/salt/minion/files/base']
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init
[DEBUG   ] Updating roots fileserver cache
[DEBUG   ] Could not find file from saltenv 'base', 'salt://salt/map.jinja'
[CRITICAL] Rendering SLS 'base:salt.pkgrepo.redhat' failed: Jinja error: salt/map.jinja
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/salt/utils/templates.py", line 306, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 1, in top-level template code
  File "/Library/Python/2.7/site-packages/salt/utils/jinja.py", line 143, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: salt/map.jinja

; line 1

---
{% from "salt/map.jinja" import salt_settings with context %}    <======================

saltstack-zeromq4:
  pkgrepo.managed:
    - humanname: Copr repo for zeromq4 owned by saltstack
    - baseurl: http://copr-be.cloud.fedoraproject.org/results/saltstack/zeromq4/{{ salt_settings.repotype }}-$releasever-$basearch/
[...]

---
[DEBUG   ] Could not find file from saltenv 'base', 'salt://salt/minion.sls'
[DEBUG   ] Could not find file from saltenv 'base', u'salt://salt/minion/init.sls'
[DEBUG   ] Could not find file from saltenv 'base', 'salt://salt/gitfs/pygit2.sls'
[DEBUG   ] Could not find file from saltenv 'base', u'salt://salt/gitfs/pygit2/init.sls'
[DEBUG   ] Could not find file from saltenv 'base', 'salt://salt/master.sls'
[DEBUG   ] Could not find file from saltenv 'base', u'salt://salt/master/init.sls'
[DEBUG   ] LazyLoaded nested.output
```

My `Saltfile` is

``` yaml
salt-ssh:
  config_dir: etc/salt
  max_procs: 30
  wipe_ssh: True
  extra_filerefs:
    - salt://salt/formulas.jinja
```

Cloning the git repo and adding that to the file_roots works as expected.

``` yaml
...
file_roots:
  base:
    - srv/salt
    - srv/formulas/salt-formula
  develop:
    - srv/salt/develop
...
```

**Comment by jfindlay** [comment]
@mattwillsher, thanks for the report.

**Comment by mattwillsher** [comment]
The git repo I'm using https://github.com/willshersystems/salt-formula, which is a clone of https://github.com/saltstack-formulas/salt-formula

**Comment by howardroark** [comment]
So I am noticing that this works on Ubuntu 14.04 but fails on Ubuntu 12.04.  In both cases I am using the latest official release. Seems kind of odd.

**Comment by spoage** [comment]
I'm having this problem too, also with the salt-formula - but the salt.minion state instead of whatever mattwillsher is using. Ubuntu 15.05 on both ends of the equation.

Versions report:
```
# salt-call --versions-report
                  Salt: 2015.5.3
                Python: 2.7.9 (default, Apr  2 2015, 15:33:21)
                Jinja2: 2.7.3
              M2Crypto: 0.21.1
        msgpack-python: 0.4.2
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.11
                 ioflo: Not Installed
                 PyZMQ: 14.4.1
                  RAET: Not Installed
                   ZMQ: 4.0.5
                  Mako: 1.0.0
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1trusty1
```
