### ISSUE TITLE
-p (progress) fails on higher level master

### ISSUE THREAD

**Issue by cedwards** [saltstack/salt#24462]
It appears that the newly introduced `progressbar` option chokes if used on a higher-level master.

```
[root@server ~]# salt -p \* test.ping                                                                                                                                                                                             
[ERROR   ] An un-handled exception was caught by salt's global exception handler:###########################################################################################################| Elapsed Time: 0:00:00 Returns: [31/31]
ValueError: Value out of range
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 349, in salt_main
    client.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/salt.py", line 179, in run
    self._progress_ret(progress, out)
  File "/usr/lib/python2.6/site-packages/salt/cli/salt.py", line 272, in _progress_ret
    salt.output.update_progress(self.config, progress, self.progress_bar, out)
  File "/usr/lib/python2.6/site-packages/salt/output/__init__.py", line 77, in update_progress
    progress_outputter(progress, progress_iter)
  File "/usr/lib/python2.6/site-packages/salt/output/progress.py", line 21, in output
    bar.update(ret['return_count'])
  File "/usr/lib/python2.6/site-packages/progressbar/__init__.py", line 272, in update
    raise ValueError('Value out of range')
ValueError: Value out of range
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 349, in salt_main
    client.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/salt.py", line 179, in run
    self._progress_ret(progress, out)
  File "/usr/lib/python2.6/site-packages/salt/cli/salt.py", line 272, in _progress_ret
    salt.output.update_progress(self.config, progress, self.progress_bar, out)
  File "/usr/lib/python2.6/site-packages/salt/output/__init__.py", line 77, in update_progress
    progress_outputter(progress, progress_iter)
  File "/usr/lib/python2.6/site-packages/salt/output/progress.py", line 21, in output
    bar.update(ret['return_count'])
  File "/usr/lib/python2.6/site-packages/progressbar/__init__.py", line 272, in update
    raise ValueError('Value out of range')
ValueError: Value out of range
```

**Comment by mimianddaniel** [comment]
Not working for me on any masters with the following error ..
running 2015.5.1 
salt '*' -p -t 30 test.ping

[ERROR   ] An un-handled exception was caught by salt's global exception handler:
NameError: global name 'progressbar' is not defined
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/scripts.py", line 349, in salt_main
    client.run()
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/cli/salt.py", line 179, in run
    self._progress_ret(progress, out)
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/cli/salt.py", line 271, in _progress_ret
    self.progress_bar = salt.output.get_progress(self.config, out, progress)
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/output/__init__.py", line 64, in get_progress
    mod='output')['{0}.progress_iter'.format(out)](progress)
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/output/progress.py", line 29, in progress_iter
    widgets = [progressbar.Percentage(), ' ', progressbar.Bar(), ' ', progressbar.Timer(), ' Returns: [', progressbar.Counter(), '/{0}]'.format(progress['minion_count'])]
NameError: global name 'progressbar' is not defined
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/scripts.py", line 349, in salt_main
    client.run()
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/cli/salt.py", line 179, in run
    self._progress_ret(progress, out)
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/cli/salt.py", line 271, in _progress_ret
    self.progress_bar = salt.output.get_progress(self.config, out, progress)
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/output/__init__.py", line 64, in get_progress
    mod='output')['{0}.progress_iter'.format(out)](progress)
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/output/progress.py", line 29, in progress_iter
    widgets = [progressbar.Percentage(), ' ', progressbar.Bar(), ' ', progressbar.Timer(), ' Returns: [', progressbar.Counter(), '/{0}]'.format(progress['minion_count'])]
NameError: global name 'progressbar' is not defined

**Comment by cachedout** [comment]
It requires this: https://pypi.python.org/pypi/progressbar

We should probably clean up that stacktrace though. :]

**Comment by cachedout** [comment]
@cedwards Good catch. We'll take a look.

**Comment by arthurlogilab** [comment]
Getting this trace on debian jessie with 

```
# dpkg -l python-progressbar
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                              Version               Architecture          Description
+++-=================================-=====================-=====================-========================================================================
ii  python-progressbar                2.3-1                 all                   text progress bar library for Python
```
