### ISSUE TITLE
clouds/ec2.py: create_snapshot throws exception

### ISSUE THREAD

**Issue by codehotter** [saltstack/salt#24484]
Test case:

```
import salt.cloud

client = salt.cloud.CloudClient(path='/etc/salt/cloud')
snapshot = client.action(fun="create_snapshot", provider="ec2-ireland-test", kwargs={"volume_id": "vol-351d8826", "description": "Test clouds/ec2.py create_snapshot"})
```

Get exception:

```
Traceback (most recent call last):
  File "/tmp/test.py", line 5, in <module>
    snapshot = client.action(fun="create_snapshot", provider="ec2-ireland-test", kwargs={"volume_id": "vol-351d8826", "description": "Test clouds/ec2.py create_snapshot"})
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 454, in action
    return mapper.do_function(provider, fun, kwargs)
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1496, in do_function
    call='function', kwargs=kwargs
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/ec2.py", line 3724, in create_snapshot
    for k, v in d.items():
AttributeError: 'list' object has no attribute 'items'
```

Possible fix (note: I'm not sure I understand the salt code very well).

```
From 48a102f3a1b0e3537f81e75e8b82aa614903366f Mon Sep 17 00:00:00 2001
From: Emanuel Rietveld <codehotter@gmail.com>
Date: Sun, 7 Jun 2015 21:22:25 +0200
Subject: [PATCH] clouds/ec2.py: clouds/ec2.py: create_snapshot fix
 wait_to_finish

---
 salt/cloud/clouds/ec2.py | 5 +++--
 1 file changed, 3 insertions(+), 2 deletions(-)

diff --git a/salt/cloud/clouds/ec2.py b/salt/cloud/clouds/ec2.py
index 22fd935..9ce9255 100644
--- a/salt/cloud/clouds/ec2.py
+++ b/salt/cloud/clouds/ec2.py
@@ -3732,13 +3732,14 @@ def create_snapshot(kwargs=None, call=None, wait_to_finish=False):

     data = aws.query(params,
                      return_url=True,
+                     return_root=True,
                      location=get_location(),
                      provider=get_provider(),
                      opts=__opts__,
                      sigver='4')

     r_data = {}
-    for d in data:
+    for d in data[0]:
         for k, v in six.iteritems(d):
             r_data[k] = v
     snapshot_id = r_data['snapshotId']
@@ -3751,7 +3752,7 @@ def create_snapshot(kwargs=None, call=None, wait_to_finish=False):
                                                 argument_being_watched='status',
                                                 required_argument_response='completed')

-    return data
+    return r_data


 def delete_snapshot(kwargs=None, call=None):
--
1.8.3.1
```

**Comment by rallytime** [comment]
Thanks @codehotter. Can you also post the output of `salt-cloud --versions-report`?

**Comment by codehotter** [comment]
I just retested with develop@88d2eeca00ff345a2692c1173933ac00af9a15c4

```
Traceback (most recent call last):
  File "/tmp/test.py", line 4, in <module>
    snapshot = client.action(fun="create_snapshot", provider="ec2-ireland-test", kwargs={"volume_id": "vol-351d8826", "description": "Test clouds/ec2.py create_snapshot"})
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 459, in action
    return mapper.do_function(provider, fun, kwargs)
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1521, in do_function
    call='function', kwargs=kwargs
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/ec2.py", line 3742, in create_snapshot
    for k, v in six.iteritems(d):
  File "/usr/lib/python2.7/site-packages/salt/ext/six.py", line 572, in iteritems
    return iter(d.iteritems(**kw))
AttributeError: 'list' object has no attribute 'iteritems'
```

Salt Version:
           Salt: 2015.5.0
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
         Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
           RAET: Not Installed
            ZMQ: 3.2.5
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
       pycrypto: 2.6.1
 
System Versions:
           dist: centos 7.1.1503 Core
        machine: x86_64
        release: 3.10.0-123.8.1.el7.x86_64
         system: CentOS Linux 7.1.1503 Core

**Comment by rallytime** [comment]
Thanks! We'll take a look.

**Comment by rallytime** [comment]
@codehotter Thanks for this report and help on this. I was able to reproduce this bug. I have fixed it in #26265. Can you give that a try and confirm that the change resolves the stacktrace for you as well?

**Comment by codehotter** [comment]
@rallytime Thanks for the fix! I no longer get a stacktrace, but since we now use return_root=True in aws.query, the return value of this function is a bit unwieldy now.

For example:
```
[{'requestId': 'bcd035f0-a48e-4b9e-b63a-5fbceb2978b9'}, {'snapshotId': 'snap-4ec4d167'}, {'volumeId': 'vol-b39e56a5'}, {'status': 'pending'}, {'startTime': '2015-08-14T13:33:58.000Z'}, {'progress': None}, {'ownerId': '292306039470'}, {'volumeSize': '3'}, {'encrypted': 'false'}, {'description': 'Created by salt - create_image.sls'}]
```

This is a list of dicts, which is annoying to work with. If you return r_data instead of data, you get the much nicer:

```
{'status': 'pending', 'description': 'Created by salt - create_image.sls', 'encrypted': 'false', 'volumeId': 'vol-b39e56a5', 'volumeSize': '3', 'requestId': '0e33966e-fbb3-41a8-a83a-0e1bc52206ef', 'startTime': '2015-08-14T13:47:26.000Z', 'progress': None, 'snapshotId': 'snap-b902c8ef', 'ownerId': '292306039470'}
```

Compare create_volume, which makes the same choice to return r_data if using return_root=True. I propose the following additional patch:

```
diff --git a/salt/cloud/clouds/ec2.py b/salt/cloud/clouds/ec2.py
index 2a38828..6343376 100644
--- a/salt/cloud/clouds/ec2.py
+++ b/salt/cloud/clouds/ec2.py
@@ -3763,7 +3763,7 @@ def create_snapshot(kwargs=None, call=None, wait_to_finish=False):
                                                 argument_being_watched='status',
                                                 required_argument_response='completed')
 
-    return data
+    return r_data
```

Thanks again for your time.

**Comment by rallytime** [comment]
Good call @codehotter. I've made the change to the return value in #26326.
