### ISSUE TITLE
salt-ssh module doesn't work with file.copy

### ISSUE THREAD

**Issue by jeffquach** [saltstack/salt#24540]
I ran this command:

```
sudo salt-ssh -i 'remote*' file.copy /home/local/install.sh /home/remote/install.sh
```

and I'm getting this outputted from stderr:

``` python
[CRITICAL] Unable to import msgpack or msgpack_pure python modules
        Traceback (most recent call last):
          File "/tmp/.ec2-user_c87ee6__salt/salt-call", line 4, in <module>
            salt_call()
          File "/tmp/.ec2-user_c87ee6__salt/salt/scripts.py", line 227, in salt_call
            client.run()
          File "/tmp/.ec2-user_c87ee6__salt/salt/cli/call.py", line 69, in run
            caller.run()
          File "/tmp/.ec2-user_c87ee6__salt/salt/cli/caller.py", line 236, in run
            ret = self.call()
          File "/tmp/.ec2-user_c87ee6__salt/salt/cli/caller.py", line 138, in call
            ret['return'] = func(*args, **kwargs)
          File "/tmp/.ec2-user_c87ee6__salt/salt/modules/file.py", line 2259, in copy
            shutil.copyfile(src, dst)
          File "/usr/lib64/python2.7/shutil.py", line 82, in copyfile
            with open(src, 'rb') as fsrc:
        IOError: [Errno 2] No such file or directory: '/home/local/aws.sh'
```

It's complaining that i don't have msgpack or msgpack-python but they're already installed.  This is the output when I run: "salt-ssh --versions-report"

``` yaml
Salt: 2015.5.0
Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
Jinja2: 2.7.2
M2Crypto: 0.21.1
msgpack-python: 0.3.0
msgpack-pure: 0.1.3
pycrypto: 2.6.1
libnacl: Not Installed
PyYAML: 3.10
ioflo: Not Installed
PyZMQ: 14.0.1
RAET: Not Installed
ZMQ: 4.0.4
Mako: 0.9.1
Debian source package: 2015.5.0+ds-1trusty1
```

I've also tried putting this in a state file and each time I get an error of salt not being able to find the file or directory.

Is this a bug or is there something I am doing wrong?

**Comment by jfindlay** [comment]
@jeffquach, what is the system and system version you are salt-sshing to?  Thanks.

**Comment by jeffquach** [comment]
This is the output from 'lsb_release -a':

    No LSB modules are available.
    Distributor ID: Ubuntu
    Description:    Ubuntu 14.04 LTS
    Release:        14.04
    Codename:       trusty

**Comment by ErebusBat** [comment]
FWIW I believe I just ran into the same bug on `salt-ssh 2015.5.0 (Lithium)`:

~~~ bash
$ salt-ssh --config-dir=. --roster-file=roster.sls media test.ping
media:
    ----------
    retcode:
        1
    stderr:
        [CRITICAL] Unable to import msgpack or msgpack_pure python modules
        [ERROR   ] An un-handled exception was caught by salt's global exception handler:
        ImportError: dlopen(/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_ssl.so, 2): Symbol no
t found: _SSLv2_method
          Referenced from: /usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_ssl.so
          Expected in: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
         in /usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_ssl.so
        Traceback (most recent call last):
          File "/tmp/.media_a2ef90__salt/salt-call", line 4, in <module>
            salt_call()
          File "/private/tmp/.media_a2ef90__salt/salt/scripts.py", line 221, in salt_call
            import salt.cli.call
          File "/private/tmp/.media_a2ef90__salt/salt/cli/call.py", line 9, in <module>
            import salt.cli.caller
          File "/private/tmp/.media_a2ef90__salt/salt/cli/caller.py", line 21, in <module>
            import salt.minion
          File "/private/tmp/.media_a2ef90__salt/salt/minion.py", line 77, in <module>
            import salt.pillar
          File "/private/tmp/.media_a2ef90__salt/salt/pillar/__init__.py", line 15, in <module>
            import salt.fileclient
          File "/private/tmp/.media_a2ef90__salt/salt/fileclient.py", line 27, in <module>
            import salt.utils.http
          File "/private/tmp/.media_a2ef90__salt/salt/utils/http.py", line 22, in <module>
            import ssl
          File "/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 60, in <module>
            import _ssl             # if we can't import it, let the error propagate
        ImportError: dlopen(/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_ssl.so, 2): Symbol no
t found: _SSLv2_method
          Referenced from: /usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_ssl.so
          Expected in: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
         in /usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_ssl.so
        Traceback (most recent call last):
          File "/tmp/.media_a2ef90__salt/salt-call", line 4, in <module>
            salt_call()
          File "/private/tmp/.media_a2ef90__salt/salt/scripts.py", line 221, in salt_call
            import salt.cli.call
          File "/private/tmp/.media_a2ef90__salt/salt/cli/call.py", line 9, in <module>
            import salt.cli.caller
          File "/private/tmp/.media_a2ef90__salt/salt/cli/caller.py", line 21, in <module>
            import salt.minion
          File "/private/tmp/.media_a2ef90__salt/salt/minion.py", line 77, in <module>
            import salt.pillar
          File "/private/tmp/.media_a2ef90__salt/salt/pillar/__init__.py", line 15, in <module>
         File "/private/tmp/.media_a2ef90__salt/salt/pillar/__init__.py", line 15, in <module>
            import salt.fileclient
          File "/private/tmp/.media_a2ef90__salt/salt/fileclient.py", line 27, in <module>
            import salt.utils.http
          File "/private/tmp/.media_a2ef90__salt/salt/utils/http.py", line 22, in <module>
            import ssl
          File "/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 60, in <module>
            import _ssl             # if we can't import it, let the error propagate
        ImportError: dlopen(/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_ssl.so, 2): Symbol no
t found: _SSLv2_method
          Referenced from: /usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_ssl.so
          Expected in: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
         in /usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_ssl.so
        Traceback (most recent call last):
          File "/tmp/.media_a2ef90__salt/salt-call", line 4, in <module>
            salt_call()
          File "/private/tmp/.media_a2ef90__salt/salt/scripts.py", line 221, in salt_call
            import salt.cli.call
          File "/private/tmp/.media_a2ef90__salt/salt/cli/call.py", line 9, in <module>
            import salt.cli.caller
          File "/private/tmp/.media_a2ef90__salt/salt/cli/caller.py", line 21, in <module>
            import salt.minion
          File "/private/tmp/.media_a2ef90__salt/salt/minion.py", line 77, in <module>
            import salt.pillar
          File "/private/tmp/.media_a2ef90__salt/salt/pillar/__init__.py", line 15, in <module>
            import salt.fileclient
          File "/private/tmp/.media_a2ef90__salt/salt/fileclient.py", line 27, in <module>
            import salt.utils.http
          File "/private/tmp/.media_a2ef90__salt/salt/utils/http.py", line 22, in <module>
            import ssl
          File "/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 60, in <module>
            import _ssl             # if we can't import it, let the error propagate
        ImportError: dlopen(/usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_ssl.so, 2): Symbol no
t found: _SSLv2_method
          Referenced from: /usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_ssl.so
          Expected in: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
         in /usr/local/Cellar/python/2.7.6_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_ssl.so
    stdout:
~~~

~~~ bash
#### Calling Host
##########################
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.10.5
BuildVersion:   14F27

$ salt-ssh --versions-report
           Salt: 2015.5.0
         Python: 2.7.10 (default, Jul 14 2015, 19:46:27)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed

#### SSH Client
##########################
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.10.4
BuildVersion:   14E46

$ salt-ssh --versions-report
           Salt: 2015.5.0
         Python: 2.7.6 (default, Sep  9 2014, 15:04:36)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.7.0
           RAET: Not Installed
            ZMQ: 4.1.2
           Mako: Not Installed
        Tornado: Not Installed
~~~

Looking at the stacktrace after I pasted it looks like it might actually be a missing OpenSSL dependency?

**Comment by ErebusBat** [comment]
FWIW:  This was apparently a broken OpenSSL install on my target machine, after reading Homebrew/homebrew#31851 I did the following on the target machine:

~~~ bash
$ brew update
$ brew upgrade python
$ pip install --upgrade pip setuptools
~~~

After that, and only that, I can:
~~~ bash
$ salt-ssh media test.ping
media:
    True
~~~

I am not sure that the hombrew issue I referenced was my actual problem, and is probably not the actual issue on this ticket; however upgrading homebrew was the fix.

**Comment by yinchuan** [comment]
Hello: 
Any update? Still exist in version 2015.8.3 (Beryllium).
