### ISSUE TITLE
state.apply un-handled exception 

### ISSUE THREAD

**Issue by twellspring** [saltstack/salt#24596]
The following un-handled exception occurs when adding --out=highstate to state.apply. 
Even though the error is shown on screen, the state still succeeds ( installs php5-mcrypt ) 
Might be related to #24383

without the --out=highstate

```
twells@salter:/data/salt/environments/test/state$ salt  test-rap-web-stage-1 state.apply 
... snip ...
    pkg_|-php5-mcrypt_|-php5-mcrypt_|-installed:
        ----------
        __run_num__:
            15
        changes:
            ----------
        comment:
            Package php5-mcrypt is already installed.
        duration:
            432.872
        name:
            php5-mcrypt
        result:
            True
        start_time:
            15:30:37.627795
... snip ...
```

With --out=highstate

```
twells@salter:/data/salt/environments/test/state$ salt  test-rap-web-stage-1 state.apply --out=highstate
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: string indices must be integers, not str
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 349, in salt_main
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/salt.py", line 201, in run
    self._output_ret(ret_, out)
  File "/usr/lib/python2.7/dist-packages/salt/cli/salt.py", line 286, in _output_ret
    salt.output.display_output(ret, out, self.config)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 94, in display_output
    display_data = try_printout(data, out, opts)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 46, in try_printout
    return get_printout(out, opts)(data).rstrip()
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 84, in output
    return _format_host(host, hostdata)[0]
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 136, in _format_host
    schanged, ctext = _format_changes(ret['changes'])
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 391, in _format_changes
    __opts__)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 172, in out_format
    return try_printout(data, out, opts)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 46, in try_printout
    return get_printout(out, opts)(data).rstrip()
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 84, in output
    return _format_host(host, hostdata)[0]
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 117, in _format_host
    data = _strip_clean(data)
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 405, in _strip_clean
    if returns[tag]['result'] and not returns[tag]['changes']:
TypeError: string indices must be integers, not str
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 349, in salt_main
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/salt.py", line 201, in run
    self._output_ret(ret_, out)
  File "/usr/lib/python2.7/dist-packages/salt/cli/salt.py", line 286, in _output_ret
    salt.output.display_output(ret, out, self.config)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 94, in display_output
    display_data = try_printout(data, out, opts)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 46, in try_printout
    return get_printout(out, opts)(data).rstrip()
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 84, in output
    return _format_host(host, hostdata)[0]
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 136, in _format_host
    schanged, ctext = _format_changes(ret['changes'])
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 391, in _format_changes
    __opts__)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 172, in out_format
    return try_printout(data, out, opts)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 46, in try_printout
    return get_printout(out, opts)(data).rstrip()
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 84, in output
    return _format_host(host, hostdata)[0]
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 117, in _format_host
    data = _strip_clean(data)
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 405, in _strip_clean
    if returns[tag]['result'] and not returns[tag]['changes']:
TypeError: string indices must be integers, not str
```

And using state.highstate

```
twells@salter:/data/salt/environments/test/state$ salt test-rap-web-stage-1 state.highstate
test-rap-web-stage-1:
----------
          ID: php5-fpm
    Function: pkg.installed
      Result: True
     Comment: The following packages were installed/updated: php5-mcrypt The following packages were already installed: php5-cli, php5-curl, php5-mysqlnd, php5-gd, php5-fpm
     Started: 15:35:14.509628
    Duration: 7577.16 ms
     Changes:
              ----------
              php5-mcrypt:
                  ----------
                  new:
                      5.4.6-0ubuntu5
                  old:
----------
          ID: php5-fpm service
    Function: service.running
        Name: php5-fpm
      Result: True
     Comment: Service reloaded
     Started: 15:35:22.662414
    Duration: 155.705 ms
     Changes:
              ----------
              php5-fpm:
                  True

Summary
------------
Succeeded: 2 (changed=2)
Failed:    0
------------
```

**Comment by cachedout** [comment]
Nice find. We should be able to clean this up. Thanks!
