### ISSUE TITLE
Un-handled exception: ValueError: list.remove(x): x not in list while pkg.refresh_db

### ISSUE THREAD

**Issue by Whissi** [saltstack/salt#24617]
Hi,

while doing `pkg.refresh_db` I got

```
# salt -G 'c_env:*staging*' --batch 5 pkg.refresh_db

Executing run on ['srv2.example.org', 'srv8.example.org', 'srv4.example.org', 'srv7.example.org', 'srv3.example.org']

retcode:
    0
srv4.example.org:
    True

Executing run on ['srv5.example.org']

retcode:
    0
srv3.example.org:
    True

Executing run on ['srv6.example.org']

[ERROR   ] An un-handled exception was caught by salt's global exception handler:
ValueError: list.remove(x): x not in list
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/salt", line 10, in <module>
    salt_main()
  File "/usr/lib64/python2.7/site-packages/salt/scripts.py", line 349, in salt_main
    client.run()
  File "/usr/lib64/python2.7/site-packages/salt/cli/salt.py", line 98, in run
    for res in batch.run():
  File "/usr/lib64/python2.7/site-packages/salt/cli/batch.py", line 179, in run
    active.remove(minion)
ValueError: list.remove(x): x not in list
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/salt", line 10, in <module>
    salt_main()
  File "/usr/lib64/python2.7/site-packages/salt/scripts.py", line 349, in salt_main
    client.run()
  File "/usr/lib64/python2.7/site-packages/salt/cli/salt.py", line 98, in run
    for res in batch.run():
  File "/usr/lib64/python2.7/site-packages/salt/cli/batch.py", line 179, in run
    active.remove(minion)
ValueError: list.remove(x): x not in list
```

```
# salt-call --versions-report
           Salt: 2015.5.2
         Python: 2.7.10 (default, May 31 2015, 16:13:06)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.6.0
           RAET: Not Installed
            ZMQ: 4.1.1
           Mako: Not Installed
```

**Comment by Whissi** [comment]
This is reproducible.

First I thought it was triggered because one of the selected minion was not connected but now every minion is available (ping works) and I still get this error.

Downgrade to 2015.5.1 which is working for me.

For the records: Master and minions are running Gentoo Linux.

**Comment by arroyoc** [comment]
@Whissi Thanks for the report. 
This could possibly be related to #24153 and #24450.

**Comment by madstacks** [comment]
I am getting the same error on 2015.5.2 on Gentoo as well. If I remove `--static`, then the error does not occur. Below is the command.

```
sudo salt '*'  --static --out=json cmd.run_all 'mkdir -p /logs; tar -czf /logs/$(hostname).tar.gz -C /var log'
```

```
$ salt-call --versions-report
           Salt: 2015.5.2
         Python: 2.7.10 (default, Jun  3 2015, 01:05:29)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: 1.4.0
         PyYAML: 3.11
          ioflo: 1.2.1
          PyZMQ: 14.5.0
           RAET: 0.6.1
            ZMQ: 4.0.5
           Mako: Not Installed
```

**Comment by Whissi** [comment]
@arroyoc: #24450 seems unrelated. I applied https://github.com/rallytime/salt/commit/1c0fca2b9de96b70f1f89ed7d7e7b48f8768f2ed.patch without a change.

But reverting #24153 (https://github.com/saltstack/salt/commit/4a8dbc7f132b351650352fca0c7efc718567ed52.patch) does the trick.

**Comment by bechtoldt** [comment]
duplicate: #24875

**Comment by JaseFace** [comment]
https://github.com/saltstack/salt/issues/29298 has a fix for this, hopefully it will hit as a PR soon, but it's just a few lines so you can hot patch your existing install.  Seems this happens when it gets more than one return from a minion (normally because more than one minion is running, which seems to be another bug caused by a less than perfect restart), and the subsequent response goes to return a minion id that was already removed by the initial response.
