### ISSUE TITLE
glance.image_list(): "AttributeError: Unknown Attribute: service_catalog"

### ISSUE THREAD

**Issue by 0xf10e** [saltstack/salt#24683]
I get this exception on Ubuntu 14.04 with Salt 2015.5.0 and OpenStack Icehouse when running `salt \*  glance.image_list`:
```
controller:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1142, in _thread_return
        return_data = func(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/glance.py", line 181, in image_list
        nt_ks = _auth(profile)
      File "/usr/lib/python2.7/dist-packages/salt/modules/glance.py", line 69, in _auth
        endpoint = kstone.service_catalog.url_for(
      File "/usr/lib/python2.7/dist-packages/keystoneclient/httpclient.py", line 620, in __getattr__
        raise AttributeError("Unknown Attribute: %s" % name)
    AttributeError: Unknown Attribute: service_catalog
```

Looking [at the code](https://github.com/openstack/python-keystoneclient/blob/stable/icehouse/keystoneclient/httpclient.py#L654) using keystoneclient in this way is deprecated:
```
    def __getattr__(self, name):
        # FIXME(jamielennox): provide a proper deprecated warning
        try:
            var_name = self.deprecated_session_variables[name]
        except KeyError:
            raise AttributeError("Unknown Attribute: %s" % name)

        return getattr(self.session, var_name or name)
```
(Looks like the Ubuntu pkg is a bit outdated as the linenumbers don't match.)

Salt-versions on master & minion:
```
root@controller:~# salt-call --versions-report
                  Salt: 2015.5.0
                Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
 Debian source package: 2015.5.0+ds-1trusty1
```
Glance versions:
```
root@controller:~# dpkg -l \*glance\* | grep ^ii
ii  glance                              1:2014.1.4-0ubuntu2                   all          OpenStack Image Registry and Delivery Service - Daemons
ii  glance-api                          1:2014.1.4-0ubuntu2                   all          OpenStack Image Registry and Delivery Service - API
ii  glance-common                       1:2014.1.4-0ubuntu2                   all          OpenStack Image Registry and Delivery Service - Common
ii  glance-registry                     1:2014.1.4-0ubuntu2                   all          OpenStack Image Registry and Delivery Service - Registry
ii  python-glance                       1:2014.1.4-0ubuntu2                   all          OpenStack Image Registry and Delivery Service - Python library
ii  python-glanceclient                 1:0.12.0-0ubuntu1                     all          Client library for Openstack glance server.
root@controller:~# 
```

**Comment by 0xf10e** [comment]
Just confirmed this also happens when I use [the latest version of glance.py](https://github.com/saltstack/salt/blob/7ed6ab9ea6ef2acc7c75638b1b5f29b9a6867495/salt/modules/glance.py).

**Comment by 0xf10e** [comment]
I've started working around this issue in my [fix_glance branch](https://github.com/0xf10e/salt/commits/fix_glance).

**Comment by jfindlay** [comment]
@0xf10e, thanks for your work on this, you are welcome to submit your changes in a pull request to 2015.5.

**Comment by 0xf10e** [comment]
@jfindlay had a bunch of other stuff to fix the last week but hopefully I can take care of this in the next days

**Comment by 0xf10e** [comment]
Similar issue with `glance.image_create` I guess:
```
user@master:/srv/salt/saltstack.git% sudo salt -C 'hw-ctrl or controller'  glance.image_create name=f16-jeos is_public=true \ 
                 disk_format=qcow2 container_format=ovf \
                 copy_from=http://berrange.fedorapeople.org/images/2012-02-29/f16-x86_64-openstack-sda.qcow2
hw-ctrl:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1142, in _thread_return
        return_data = func(*args, **kwargs)
      File "/var/cache/salt/minion/extmods/modules/glance.py", line 170, in image_create
        [(k, v) for (k, v) in six.iteritems(kwargs) if k in glanceclient.v1.images.CREATE_PARAMS]
    AttributeError: 'module' object has no attribute 'v1'
controller:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1142, in _thread_return
        return_data = func(*args, **kwargs)
      File "/var/cache/salt/minion/extmods/modules/glance.py", line 170, in image_create
        [(k, v) for (k, v) in six.iteritems(kwargs) if k in glanceclient.v1.images.CREATE_PARAMS]
    AttributeError: 'module' object has no attribute 'v1'
```

I'll fix this too and then create the PR.

**Comment by jfindlay** [comment]
Thanks, @0xf10e, that would be excellent.

**Comment by 0xf10e** [comment]
I think we'll better merge the fixes for `glance.image_list` and `glance.image_show` in case someone is using those and just didn't come around to update to Lithium yet.

The documentation on the python-glanceclient is clearly lacking and I may have to hunt down an OpenStack/Glance-dev to figure out where this "schema_client" one is supposed to pass to `glanceclient.v2.images.Client.create()` comes from...

**Comment by 0xf10e** [comment]
OK, I missunderstood the... "layout" of `glanceclient.v2.client.Client` and it _seems_ I got `glance.image_create` working: https://github.com/0xf10e/salt/commit/439b1e42053239b0f2f4a29383cf97bc095d661f

But now I got to fix `glance.image_list` again:
```
user@master:/srv/salt/saltstack.git% sudo salt -C 'hw-ctrl or controller'  glance.image_list
hw-ctrl:
    ----------
    container_format:
        bare
    disk_format:
        qcow2
    f16-jeos:
        ----------
        created_at:
            2015-06-29T09:49:13Z
        file:
            /v2/images/86edb8ad-90a8-40d9-8e66-5e3e0b4885e3/file
        id:
            86edb8ad-90a8-40d9-8e66-5e3e0b4885e3
        ...
        visibility:
            private
    size:
        256705024
    trusty-cloud amd64:
        ----------
        created_at:
            2015-04-22T12:45:51Z
...
```

**Comment by 0xf10e** [comment]
OK, fixed `image_show()` and `image_list()`, was just a bit of inattention on my side:
https://github.com/0xf10e/salt/commit/272bfec577dc5d621056afb8548c67921587df85

There's still a problem with my `glanceclient.v2` version of `image.create()`: Images stay 'queued' so they're not usable yet. Probably a problem with the [Location header](http://developer.openstack.org/api-ref-image-v2.html#createImage-v2) not passed correctly.

**Comment by 0xf10e** [comment]
If anyone stumbles over this bug see https://github.com/saltstack/salt/pull/25087

**Comment by 0xf10e** [comment]
This one should be fixed, right?

**Comment by jfindlay** [comment]
@0xf10e, yes, thanks for your work on this.
