### ISSUE TITLE
LocalClient fails to initialize with python3

### ISSUE THREAD

**Issue by RyanHartje** [saltstack/salt#24750]
I have the latest stable of Salt currently, along with the 2015.5.2 version of salt installed via pip.
When initializing LocalClient(), an exception is thrown and I'm not sure what the correct fix is:

```ssh
>>> import salt.client
>>> local = salt.client.LocalClient()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/project/venv/lib/python3.4/site-packages/salt/client/__init__.py", line 126, in __init__
    self.opts = salt.config.client_config(c_path)
  File "/project/venv/lib/python3.4/site-packages/salt/config.py", line 2199, in client_config
    master_config(path, defaults=defaults)
  File "/project/venv/lib/python3.4/site-packages/salt/config.py", line 2041, in master_config
    opts = apply_master_config(overrides, defaults)
  File "/project/venv/lib/python3.4/site-packages/salt/config.py", line 2082, in apply_master_config
    cache_minion_id=None)
  File "/project/venv/lib/python3.4/site-packages/salt/config.py", line 1938, in get_id
    newid = salt.utils.network.generate_minion_id()
  File "/project/venv/lib/python3.4/site-packages/salt/utils/network.py", line 274, in generate_minion_id
    in salt.utils.network.ip_addrs(include_loopback=True)
  File "/project/venv/lib/python3.4/site-packages/salt/utils/network.py", line 846, in ip_addrs
    else interfaces()
  File "/project/venv/lib/python3.4/site-packages/salt/utils/network.py", line 693, in interfaces
    return linux_interfaces()
  File "/project/venv/lib/python3.4/site-packages/salt/utils/network.py", line 580, in linux_interfaces
    ifaces = _interfaces_ip(cmd1 + '\n' + cmd2)
TypeError: can't concat bytes to str
```

I could probably try casting cmd1 and cmd2 via network.py, but I did want to raise this issue before I mess with it, as I'd be at best guessing. 

Thanks for any help you can provide.

**Comment by rallytime** [comment]
@RyanHartje Salt does not presently (2015.5.x releases and older) run on Python3 because of a couple of hard dependencies in Salt. However, I beleive we are working towards Python 3 support for the next feature release, Beryllium. Do I have that correct, @msteed?

**Comment by RyanHartje** [comment]
Thank you for the feedback @rallytime, I overlooked that.

**Comment by msteed** [comment]
We are making progress towards Python 3 compatibility but I am not sure when it will ship. Soon we will be posting a document describing the py3 issues and how we are solving them, so interested parties will be able to help.

**Comment by FunTimeCoding** [comment]
awesome, python3 support is coming!

**Comment by cachedout** [comment]
This actually works now! Closing this issue.
