### ISSUE TITLE
Stack trace on highstate (missing file + recursive requisite)

### ISSUE THREAD

**Issue by scoates** [saltstack/salt#24761]
I ran into a stack trace (instead of just an error message), today. I suspect the intended behaviour is to have salt capture this exception instead of dumping it.

I've boiled my states down to just a `top.sls` plus one `.sls`:
## top.sls

``` yaml
base:
  '*':
    - bug
```
## bug.sls

``` yaml
cron: # does not NEED to be cron, but most systems have cron already installed
    service:
        - running

/tmp/bug1.salt:
    file.managed:
        - source: salt://file_does_not_exist

/tmp/bug2.salt:
    file.managed:
        - watch_in:
            - service: cron
        - require:
            - file: /tmp/bug1.salt
```
## output:

```
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://top.sls'
[INFO    ] Syncing modules for environment 'base'
[INFO    ] Loading cache from salt://_modules, for base)
[INFO    ] Caching directory '_modules/' for environment 'base'
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://_modules/apps.py'
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://_modules/merger.py'
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://_modules/user_testing.py'
[INFO    ] Copying '/var/cache/salt/minion/files/base/_modules/apps.py' to '/var/cache/salt/minion/extmods/modules/apps.py'
[INFO    ] Copying '/var/cache/salt/minion/files/base/_modules/merger.py' to '/var/cache/salt/minion/extmods/modules/merger.py'
[INFO    ] Copying '/var/cache/salt/minion/files/base/_modules/user_testing.py' to '/var/cache/salt/minion/extmods/modules/user_testing.py'
[INFO    ] Creating module dir '/var/cache/salt/minion/extmods/states'
[INFO    ] Syncing states for environment 'base'
[INFO    ] Loading cache from salt://_states, for base)
[INFO    ] Caching directory '_states/' for environment 'base'
[INFO    ] Creating module dir '/var/cache/salt/minion/extmods/grains'
[INFO    ] Syncing grains for environment 'base'
[INFO    ] Loading cache from salt://_grains, for base)
[INFO    ] Caching directory '_grains/' for environment 'base'
[INFO    ] Creating module dir '/var/cache/salt/minion/extmods/renderers'
[INFO    ] Syncing renderers for environment 'base'
[INFO    ] Loading cache from salt://_renderers, for base)
[INFO    ] Caching directory '_renderers/' for environment 'base'
[INFO    ] Creating module dir '/var/cache/salt/minion/extmods/returners'
[INFO    ] Syncing returners for environment 'base'
[INFO    ] Loading cache from salt://_returners, for base)
[INFO    ] Caching directory '_returners/' for environment 'base'
[INFO    ] Creating module dir '/var/cache/salt/minion/extmods/outputters'
[INFO    ] Syncing outputters for environment 'base'
[INFO    ] Loading cache from salt://_outputters, for base)
[INFO    ] Caching directory '_outputters/' for environment 'base'
[INFO    ] Creating module dir '/var/cache/salt/minion/extmods/utils'
[INFO    ] Syncing utils for environment 'base'
[INFO    ] Loading cache from salt://_utils, for base)
[INFO    ] Caching directory '_utils/' for environment 'base'
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** done ** 'bug.sls'
[INFO    ] Running state [/tmp/bug1.salt] at time 18:12:41.672327
[INFO    ] Executing state file.managed for /tmp/bug1.salt
[ERROR   ] Source file salt://file_does_not_exist not found
[INFO    ] Completed state [/tmp/bug1.salt] at time 18:12:41.675670
[ERROR   ] Recursive requisite found
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: 'bool' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 227, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 69, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 246, in run
    self.opts)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 94, in display_output
    display_data = try_printout(data, out, opts)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 46, in try_printout
    return get_printout(out, opts)(data).rstrip()
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 84, in output
    return _format_host(host, hostdata)[0]
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 117, in _format_host
    data = _strip_clean(data)
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 405, in _strip_clean
    if returns[tag]['result'] and not returns[tag]['changes']:
TypeError: 'bool' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 227, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 69, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 246, in run
    self.opts)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 94, in display_output
    display_data = try_printout(data, out, opts)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 46, in try_printout
    return get_printout(out, opts)(data).rstrip()
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 84, in output
    return _format_host(host, hostdata)[0]
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 117, in _format_host
    data = _strip_clean(data)
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 405, in _strip_clean
    if returns[tag]['result'] and not returns[tag]['changes']:
TypeError: 'bool' object has no attribute '__getitem__'
vagrant@sean:~$
```

**Comment by arroyoc** [comment]
@scoates Unable to replicate this on version 2015.5.1. What is your salt --versions-report output?

**Comment by scoates** [comment]
I'm using the Debian Jessie package (`2015.5.0` + patches). Perhaps they broke something (or maybe actually fixed in `2015.5.1`).

```
# salt-minion --versions-report
                  Salt: 2015.5.0
                Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
                Jinja2: 2.7.3
              M2Crypto: 0.21.1
        msgpack-python: 0.4.2
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.11
                 ioflo: Not Installed
                 PyZMQ: 14.4.0
                  RAET: Not Installed
                   ZMQ: 4.0.5
                  Mako: 1.0.0
 Debian source package: 2015.5.0+ds-1~bpo8+1
```

I'd try 2015.5.1 myself, but I couldn't get bootstrap to work on Jessie (I believe because [systemd is looking for a notify](https://github.com/saltstack/salt/blob/develop/pkg/salt-master.service#L7), but there's no `python[2]-systemd` on Jessie)… but that's a separate issue.

**Comment by arroyoc** [comment]
@scoates Is it possible for you to try this on the latest release?

**Comment by scoates** [comment]
I forgot about this. I can't easily test on this anymore. We've had to move to `2015.8`. /-:
