### ISSUE TITLE
Unicode decoding error in salt-minion on Windows 2012 Server

### ISSUE THREAD

**Issue by torgon** [saltstack/salt#24821]
Hi All,

i'm just trying to deploy a package to a windows server and receive the following unicode decode error when doing a `salt-call -l debug state.highstate`

```
salt-call -l debug state.highstate

[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Initializing new SAuth for ('c:\\salt\\conf\\pki\\minion', 'server01', 'tcp://10.100.10.90:4506')
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded state.highstate
[DEBUG   ] LazyLoaded grains.get
[DEBUG   ] LazyLoaded saltutil.is_running
[DEBUG   ] Re-using SAuth for ('c:\\salt\\conf\\pki\\minion', 'server01', 'tcp://10.100.10.90:4506')
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Re-using SAuth for ('c:\\salt\\conf\\pki\\minion', 'server01', 'tcp://10.100.10.90:4506')
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] Could not find file from saltenv 'qa', 'salt://top.sls'
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://top.sls'
[DEBUG   ] LazyLoaded cmd.run
[DEBUG   ] Jinja search path: ['c:\\salt\\var\\cache\\salt\\minion\\files\\base']
[DEBUG   ] Rendered data from file: c:\salt\var\cache\salt\minion\files\base\top.sls:
base:
  'kernel:Linux':
    - enable-mc
    - enable-dos2unix
dev:
  'deployment:(dev\.qproc)':
    - match: grain_pcre
    - enable-mc
  'deployment:(dev\.qproc)':
    - match: grain_pcre
    - install-qproc-latest
  'deployment:(dev\.web)':
    - match: grain_pcre
    - install-npp
[DEBUG   ] LazyLoaded config.option
[DEBUG   ] Re-using SAuth for ('c:\\salt\\conf\\pki\\minion', 'server01', 'tcp://10.100.10.90:4506')
[DEBUG   ] LazyLoaded highstate.output
[DEBUG   ] Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\output\__init__.py", line 46, in try_printout
    return get_printout(out, opts)(data).rstrip()
  File "C:\salt\bin\lib\site-packages\salt\output\highstate.py", line 84, in output
    return _format_host(host, hostdata)[0]
  File "C:\salt\bin\lib\site-packages\salt\output\highstate.py", line 221, in _format_host
    ret['comment'] = ret['comment'].decode('utf-8')
AttributeError: 'ConstructorError' object has no attribute 'decode'

[DEBUG   ] LazyLoaded nested.output
local:
    ----------
    no_|-states_|-states_|-None:
        ----------
        __run_num__:
            0
        changes:
            ----------
        comment:
        name:
            No States
        result:
            False
```

**Comment by jfindlay** [comment]
@torgon, what is the output of `salt --versions-report` and `salt <windows-minion> test.versions_report`?  Thanks.

**Comment by tkuehne-deliveryhero** [comment]
@torgon I ended up with the same error, for me it turned out to be a duplicated minion entry in the top.sls file.
@jfindlay maybe it's possible to get a more specific error message in this case? I'm running 2015.5.0 (Lithium).

**Comment by torgon** [comment]
Hi TKuehne, i only just got back to it but yes, it looks as if it was the duplicate entry in the top.sls - fantastic error message.
Thanks for your help.

**Comment by jfindlay** [comment]
In that case, this issue is a duplicate (ha ha) of #20947.  Thanks for working on this issue, @torgon, @tkuehne-deliveryhero.  I should have spotted that duplicate entry. :-/
