### ISSUE TITLE
UnicodeEncodeError of file.append when text contains non-ascii characters(seems a regression)

### ISSUE THREAD

**Issue by zhaoguixu** [saltstack/salt#24820]
salt version: develop

$ sudo salt-call state.sls foo

```
foo_file:
  file.append:
    - name: /tmp/foo
    - text: 
        - føø
        - abcd
        - 23456
```

```
[ERROR] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1531, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 3183, in append
    text = _validate_str_list(text)
  File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 619, in _validate_str_list
    return [str(item) for item in arg]
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
```

**Comment by jfindlay** [comment]
@zhaoguixu, thanks for the report.
