### ISSUE TITLE
Azure: cloud.destroy cannot find VM

### ISSUE THREAD

**Issue by danielgblanco** [saltstack/salt#24822]
Hi,

While running the following command:
```
salt-run -l debug cloud.destroy myinstance
```
I get an error in the azure.listNodes function:
```
[DEBUG   ] Failed to execute 'azure.list_nodes()' while querying for running nodes: 'image'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 2198, in run_parallel_map_providers_query
    cloud.clouds[data['fun']]()
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/msazure.py", line 261, in list_nodes
    ret[node][prop] = nodes[node][prop]
KeyError: 'image'
[INFO    ] Destroying in non-parallel mode.
The following VM's were not found: myinstance
```
That instance was just created so it is there. Any ideas? My versions are the following:
```
                  Salt: 2014.7.5
                Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
                Jinja2: 2.6
              M2Crypto: 0.21.1
        msgpack-python: 0.1.10
          msgpack-pure: Not Installed
              pycrypto: 2.6
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 13.1.0
                  RAET: Not Installed
                   ZMQ: 3.2.3
                  Mako: 0.7.0
 Debian source package: 2014.7.5+ds-1~bpo70+1
```

**Comment by danielgblanco** [comment]
Apparently after a while it found it... I'm guessing it's got something to do with the number of requests to the Azure API coming from other clients... Closing this issue.
