### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by mitar** [saltstack/salt#24853]
When running salt-ssh, 2015.5.2, I am getting this error:

```
          ID: discovery-container
    Function: docker.running
        Name: discovery
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/tmp/.foobar_cb9e2b__salt/salt/state.py", line 1563, in call
                  **cdata['kwargs'])
                File "/tmp/.foobar_cb9e2b__salt/salt/states/dockerio.py", line 1019, in running
                  cap_drop=cap_drop)
                File "/tmp/.foobar_cb9e2b__salt/salt/modules/dockerio.py", line 929, in start
                  __salt__['mine.send']('docker.get_containers', host=True)
                File "/tmp/.foobar_cb9e2b__salt/salt/modules/mine.py", line 190, in send
                  old = __salt__['data.getval']('mine_cache')
                File "/tmp/.foobar_cb9e2b__salt/salt/modules/data.py", line 110, in getval
                  if key in store:
              TypeError: argument of type 'NoneType' is not iterable
     Started: 10:58:58.563849
    Duration: 36.938 ms
     Changes:   
```

`discovery.sls` is:

```
docker:
  containers:
    discovery:
      image: tozd/docker-hosts
      volumes:
        /var/run/docker.sock:
          bind: /var/run/docker.sock
          type: socket
        /srv/storage/discovery/hosts:
          bind: /hosts
          type: file
          user: nobody
          group: nogroup
```

And this is [state file](https://github.com/tozd/salt/blob/master/docker/containers.sls).

**Comment by mitar** [comment]
Made a pull request with a fix in #24860.

**Comment by mitar** [comment]
So the `running_data/var/cache/salt/minion/datastore` file is for some reason empty. So cache is empty.

**Comment by mitar** [comment]
OK, it seems that installing `python-msgpack` package and removing the Salt directory in `/tmp` solved the problem. It seems that lack of `python-msgpack` on the server made cache not work. And because cache didn't work, then `data.getval` didn't work correctly.
