### ISSUE TITLE
Name error when starting salt-master service on develop branch

### ISSUE THREAD

**Issue by nmadhok** [saltstack/salt#24859]
Here's the error I'm getting:

```
Starting salt-master daemon: Traceback (most recent call last):
  File "/usr/bin/salt-master", line 10, in <module>
    salt_master()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 47, in salt_master
    master.start()
  File "/usr/lib/python2.6/site-packages/salt/cli/daemons.py", line 150, in start
    self.prepare()
  File "/usr/lib/python2.6/site-packages/salt/cli/daemons.py", line 131, in prepare
    self.master = salt.master.Master(self.config)
  File "/usr/lib/python2.6/site-packages/salt/master.py", line 326, in __init__
    SMaster.__init__(self, opts)
  File "/usr/lib/python2.6/site-packages/salt/master.py", line 100, in __init__
    self.master_key = salt.crypt.MasterKeys(self.opts)
  File "/usr/lib/python2.6/site-packages/salt/crypt.py", line 205, in __init__
    self.key = self.__get_keys()
  File "/usr/lib/python2.6/site-packages/salt/crypt.py", line 256, in __get_keys
    key = RSA.importKey(f.read())
NameError: global name 'RSA' is not defined
                                                           [FAILED]
```

Here's the versions report:
```
Salt Version:
           Salt: 2015.5.2-6457-g6fa7e5c
 
Dependency Versions:
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
         Python: 2.6.6 (r266:84292, Nov 21 2013, 10:50:32)
           RAET: Not Installed
        Tornado: 4.1
            ZMQ: 3.2.5
          ioflo: Not Installed
        libnacl: 1.4.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
       pycrypto: 2.0.1
 
System Versions:
           dist: redhat 6.6 Santiago
        machine: x86_64
        release: 2.6.32-504.12.2.el6.x86_64
         system: Red Hat Enterprise Linux Server 6.6 Santiago
```

**Comment by nmadhok** [comment]
Nevermind. Fixed it after spending couple of hours.
