### ISSUE TITLE
Failed PipStateTest: no such option: --use-mirrors

### ISSUE THREAD

**Issue by gashev** [saltstack/salt#24850]
--use-mirrors option was removed from pip version 7.0.0.
PipStateTest faled if pip version 7.0.3.

```
salt-call --versions-report
Salt Version:
           Salt: 2015.5.2-6416-gc69650a

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
           RAET: Not Installed
        Tornado: 4.2
            ZMQ: 4.1.2
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
       pycrypto: 2.6.1

System Versions:
           dist: centos 7.1.1503 Core
        machine: x86_64
        release: 3.10.0-229.4.2.el7.x86_64
         system: CentOS Linux 7.1.1503 Core
```

```
pip list
astroid (1.3.6)
backports.ssl-match-hostname (3.4.0.2)
boto (2.38.0)
certifi (2015.4.28)
Flask (0.10.1)
futures (3.0.3)
httpretty (0.8.10)
itsdangerous (0.24)
Jinja2 (2.7.3)
logilab-common (0.63.2)
MarkupSafe (0.23)
mock (1.0.1)
moto (0.4.3)
msgpack-python (0.4.6)
pep8 (1.6.2)
pip (7.0.3)
pycrypto (2.6.1)
pylint (1.4.3)
PyYAML (3.11)
pyzmq (14.7.0)
requests (2.7.0)
salt (2015.5.2-6416-gc69650a)
SaltPyLint (2015.5.28)
SaltTesting (2015.2.16)
setuptools (17.0)
six (1.9.0)
suds (0.4)
tornado (4.2)
Werkzeug (0.10.4)
wheel (0.24.0)
xmltodict (0.9.2)
```

run tests:

```
 --------  Failed Tests  -------------------------------------------------------------------------------------------------------------
   -> integration.states.pip.PipStateTest.test_issue_2028_pip_installed_state  .......................................................
       Traceback (most recent call last):
         File "/opt/git/salt/tests/integration/states/pip.py", line 129, in test_issue_2028_pip_installed_state
           self.assertSaltTrueReturn(ret)
         File "/opt/git/salt/tests/integration/__init__.py", line 1406, in assertSaltTrueReturn
           **(next(six.itervalues(ret)))
       AssertionError: False is not True. Salt Comment:
       Failed to install packages: supervisor. Error:
       Usage:
         pip install [options] <requirement specifier> [package-index-options] ...
         pip install [options] -r <requirements file> [package-index-options] ...
         pip install [options] [-e] <vcs project url> ...
         pip install [options] [-e] <local project path> ...
         pip install [options] <archive url/path> ...

       no such option: --use-mirrors
   ...................................................................................................................................
   -> integration.states.pip.PipStateTest.test_issue_5940_multiple_pip_mirrors  ......................................................
       Traceback (most recent call last):
         File "/opt/git/salt/tests/integration/states/pip.py", line 176, in test_issue_5940_multiple_pip_mirrors
           self.assertSaltTrueReturn(ret)
         File "/opt/git/salt/tests/integration/__init__.py", line 1406, in assertSaltTrueReturn
           **(next(six.itervalues(ret)))
       AssertionError: False is not True. Salt Comment:
       Failed to install packages: pep8. Error:
       Usage:
         pip install [options] <requirement specifier> [package-index-options] ...
         pip install [options] -r <requirements file> [package-index-options] ...
         pip install [options] [-e] <vcs project url> ...
         pip install [options] [-e] <local project path> ...
         pip install [options] <archive url/path> ...

       no such option: --use-mirrors
   ...................................................................................................................................
   -> integration.states.pip.PipStateTest.test_pip_installed_errors  .................................................................
       Traceback (most recent call last):
         File "/opt/git/salt/tests/integration/states/pip.py", line 64, in test_pip_installed_errors
           self.assertSaltTrueReturn(ret)
         File "/opt/git/salt/tests/integration/__init__.py", line 1406, in assertSaltTrueReturn
           **(next(six.itervalues(ret)))
       AssertionError: False is not True. Salt Comment:
       Failed to install packages: supervisor. Error:
       Usage:
         pip install [options] <requirement specifier> [package-index-options] ...
         pip install [options] -r <requirements file> [package-index-options] ...
         pip install [options] [-e] <vcs project url> ...
         pip install [options] [-e] <local project path> ...
         pip install [options] <archive url/path> ...

       no such option: --use-mirrors
   ...................................................................................................................................
   -> integration.states.pip.PipStateTest.test_pip_installed_weird_install  ..........................................................
       Traceback (most recent call last):
         File "/root/.virtualenvs/salt/lib/python2.7/site-packages/salttesting/helpers.py", line 953, in decorator
           return func(cls, grains=cls.run_function('grains.items'))
         File "/opt/git/salt/tests/integration/states/pip.py", line 102, in test_pip_installed_weird_install
           self.assertSaltTrueReturn(ret)
         File "/opt/git/salt/tests/integration/__init__.py", line 1406, in assertSaltTrueReturn
           **(next(six.itervalues(ret)))
       AssertionError: False is not True. Salt Comment:
       Failed to install packages: carbon. Error:
       Usage:
         pip install [options] <requirement specifier> [package-index-options] ...
         pip install [options] -r <requirements file> [package-index-options] ...
         pip install [options] [-e] <vcs project url> ...
         pip install [options] [-e] <local project path> ...
         pip install [options] <archive url/path> ...

       no such option: --use-mirrors
```

**Comment by jtand** [comment]
@gashev Thanks for this bug report.

**Comment by sontek** [comment]
To fix this its going to require deprecation of `mirrors` flag on the pip module.

```
./tests/runtests.py -n tests.integration.states.pip
```

if you want to see just the failed tests.
