### ISSUE TITLE
Master config - Directories starting with a dot have the dot stripped when root_dir is .

### ISSUE THREAD

**Issue by anlutro** [saltstack/salt#24885]
Running the latest commit off the 2015.5 branch, given this master config:

```yml
root_dir: .
cachedir: .cache
```

The cache will be written to `./cache` instead of `./.cache`.

I'm actually fairly sure this wasn't the behaviour in previous versions of 2015.5, I'll investigate a bit to see if I can find a relevant change in the code.

EDIT: I was mistaken, this seems to be the consistent behaviour as long as `root_dir` is set to `.`.

**Comment by anlutro** [comment]
A workaround seems to be to add a trailing slash: `root_dir: ./`

**Comment by jtand** [comment]
@anlutro @cachedout The change you submitted looks like it's causing our test runner to traceback here:
```bash
17:40:18 Traceback (most recent call last):
17:40:18   File "/testing/tests/runtests.py", line 476, in <module>
17:40:18     main()
17:40:18   File "/testing/tests/runtests.py", line 461, in main
17:40:18     status = parser.run_integration_tests()
17:40:18   File "/testing/tests/runtests.py", line 379, in run_integration_tests
17:40:18     with TestDaemon(self):
17:40:18   File "/testing/tests/integration/__init__.py", line 184, in __enter__
17:40:18     self.start_zeromq_daemons()
17:40:18   File "/testing/tests/integration/__init__.py", line 254, in start_zeromq_daemons
17:40:18     syndic = salt.minion.Syndic(self.syndic_opts)
17:40:18   File "/testing/salt/minion.py", line 2018, in __init__
17:40:18     super(Syndic, self).__init__(opts, **kwargs)
17:40:18   File "/testing/salt/minion.py", line 685, in __init__
17:40:18     safe)
17:40:18   File "/testing/salt/minion.py", line 882, in eval_master
17:40:18     if self.authenticate(timeout, safe) == 'full':
17:40:18   File "/testing/salt/minion.py", line 1550, in authenticate
17:40:18     auth = salt.crypt.SAuth(self.opts)
17:40:18   File "/testing/salt/crypt.py", line 269, in __new__
17:40:18     SAuth.instances[key].__singleton_init__(opts)
17:40:18   File "/testing/salt/crypt.py", line 306, in __singleton_init__
17:40:18     self.get_keys()
17:40:18   File "/testing/salt/crypt.py", line 352, in get_keys
17:40:18     salt.utils.verify.check_path_traversal(self.opts['pki_dir'], user)
17:40:18   File "/testing/salt/utils/verify.py", line 390, in check_path_traversal
17:40:18     raise SaltClientError(msg)
17:40:18 salt.exceptions.SaltClientError: Could not access /tmp/salt-tests-tmpdir/master-minion-root/tmp. Path does not exist.
```

**Comment by anlutro** [comment]
@jtand Thanks, I was wondering if it was my fault or just some jenkins weirdness. I was able to get some simple test environment going and can see that some relevant unit tests are failing, so I'll get to work on that.

**Comment by anlutro** [comment]
Closing as pull request was merged
