### ISSUE TITLE
Salt-Cloud Provisioning Broken on Develop with EC2

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt#24912]
The following stack trace occurs when trying to provision machines on EC2. This appears to only be happening on the latest develop:
```
Traceback (most recent call last):
  File "/root/SaltStack/salt/salt/cloud/clouds/ec2.py", line 1682, in request_instance
    sigver='4')
  File "/root/SaltStack/salt/salt/utils/aws.py", line 346, in query
    method, endpoint, params, prov_dict, aws_api_version, location, product, requesturl=requesturl
  File "/root/SaltStack/salt/salt/utils/aws.py", line 155, in sig4
    access_key_id, secret_access_key, token = creds(prov_dict)
  File "/root/SaltStack/salt/salt/utils/aws.py", line 68, in creds
    if provider['id'] == IROLE_CODE or provider['key'] == IROLE_CODE:
KeyError: 'id'
[ERROR   ] Failed to create VM nt-test. Configuration value 'id' needs to be set
Traceback (most recent call last):
  File "/root/SaltStack/salt/salt/cloud/__init__.py", line 1256, in create
    output = self.clouds[func](vm_)
  File "/root/SaltStack/salt/salt/cloud/clouds/ec2.py", line 2168, in create
    data, vm_ = request_instance(vm_, location)
  File "/root/SaltStack/salt/salt/cloud/clouds/ec2.py", line 1682, in request_instance
    sigver='4')
  File "/root/SaltStack/salt/salt/utils/aws.py", line 346, in query
    method, endpoint, params, prov_dict, aws_api_version, location, product, requesturl=requesturl
  File "/root/SaltStack/salt/salt/utils/aws.py", line 155, in sig4
    access_key_id, secret_access_key, token = creds(prov_dict)
  File "/root/SaltStack/salt/salt/utils/aws.py", line 68, in creds
    if provider['id'] == IROLE_CODE or provider['key'] == IROLE_CODE:
KeyError: 'id'
Error: There was a profile error: Failed to deploy VM
```
Versions:
```
# salt --versions
Salt Version:
           Salt: 2015.5.0-1603-g3cadda6

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
           Mako: 0.9.1
         PyYAML: 3.11
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
           RAET: Not Installed
        Tornado: 4.0.2
            ZMQ: 4.0.4
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.4
       pycrypto: 2.6.1

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-30-generic
         system: Ubuntu 14.04 trusty
```

**Comment by rallytime** [comment]
I broke it with #24796. I'll fix this first thing tomorrow, if I don't get to it before then.
