### ISSUE TITLE
[develop] Failed to get the output of 'azure.avail_images()': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by lichtamberg** [saltstack/salt#24941]
I want to list the available images (no other commands are working too.. nearly same errors):
```shell
salt-cloud --list-images mytest
[INFO    ] salt-cloud starting
[WARNING ] /usr/local/lib/python2.7/site-packages/salt/cloud/clouds/digital_ocean.py:85: DeprecationWarning: The digital_ocean driver is deprecated and will be removed in Salt Beryllium. Please convert your digital ocean provider configs to use the digital_ocean_v2 driver.

[ERROR   ] Failed to get the output of 'azure.avail_images()': [Errno 2] No such file or directory
mytest:
    ----------
```
```yml
# cloud.providers.d/azure.conf
mytest:
  driver: azure
  subscription_id: 123123123-123123123-123123-123
  certificate_path: /Users/mytest/.ssh/mytest.pem
```

```yml
# cloud.profiles
azure-ubuntu14:
  provider: mytest
  image: 'b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_04_2_LTS-amd64-server-20150309-en-us-30GB'
  size: Small
  location: 'North Europe'
  ssh_username: azureuser
  ssh_password: verybadpass
  slot: production
  media_link: 'https://portal123123123.blob.core.windows.net/vhds'
```

```shell
salt-cloud --list-images mytest -l debug
=> 
[DEBUG   ] Missing configuration file: /etc/salt/cloud
[DEBUG   ] Missing configuration file: /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/001_server.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/001_server.conf
[DEBUG   ] Missing configuration file: /etc/salt/cloud.providers
[DEBUG   ] Including configuration from '/etc/salt/cloud.providers.d/azure.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers.d/azure.conf
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles
[DEBUG   ] Configuration file path: /etc/salt/master
[INFO    ] salt-cloud starting
[WARNING ] /usr/local/lib/python2.7/site-packages/salt/cloud/clouds/digital_ocean.py:85: DeprecationWarning: The digital_ocean driver is deprecated and will be removed in Salt Beryllium. Please convert your digital ocean provider configs to use the digital_ocean_v2 driver.

[DEBUG   ] Could not LazyLoad parallels.avail_sizes
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy
[DEBUG   ] Could not LazyLoad saltify.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.avail_images
[DEBUG   ] Could not LazyLoad saltify.avail_locations
[DEBUG   ] LazyLoaded rackspace.reboot
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] LazyLoaded rackspace.list_locations
[ERROR   ] Failed to get the output of 'azure.avail_images()': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/salt/cloud/__init__.py", line 842, in image_list
    data[alias][driver] = self.clouds[fun]()
  File "/usr/local/lib/python2.7/site-packages/salt/cloud/clouds/msazure.py", line 179, in avail_images
    for item in conn.list_os_images():
  File "/usr/local/lib/python2.7/site-packages/azure/servicemanagement/servicemanagementservice.py", line 2032, in list_os_images
    Images)
  File "/usr/local/lib/python2.7/site-packages/azure/servicemanagement/servicemanagementclient.py", line 326, in _perform_get
    response = self.perform_get(path, x_ms_version)
  File "/usr/local/lib/python2.7/site-packages/azure/servicemanagement/servicemanagementclient.py", line 136, in perform_get
    response = self._perform_request(request)
  File "/usr/local/lib/python2.7/site-packages/azure/servicemanagement/servicemanagementclient.py", line 298, in _perform_request
    resp = self._filter(request)
  File "/usr/local/lib/python2.7/site-packages/azure/http/httpclient.py", line 209, in perform_request
    connection = self.get_connection(request)
  File "/usr/local/lib/python2.7/site-packages/azure/http/httpclient.py", line 170, in get_connection
    timeout=self.timeout)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1198, in __init__
    context.load_cert_chain(cert_file, key_file)
IOError: [Errno 2] No such file or directory
[DEBUG   ] LazyLoaded nested.output
mytest:
    ----------
```

```salt
salt --versions-report
Salt Version:
           Salt: 2015.5.0-1625-g9bf1d52

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.22
           Mako: 1.0.1
         PyYAML: 3.11
          PyZMQ: 14.6.0
         Python: 2.7.9 (default, Jan  7 2015, 11:50:42)
           RAET: Not Installed
        Tornado: 4.1
            ZMQ: 4.0.5
          ioflo: 1.2.1
        libnacl: Not Installed
   msgpack-pure: 0.1.3
 msgpack-python: 0.4.6
       pycrypto: 2.6.1

System Versions:
           dist:
        machine: x86_64
        release: 13.4.0
         system: 10.9.5 -- x86_64
```

```shell
pip list azure | grep azure
=> azure (0.11.1)
```

Same problem is also on recent 2015.5 branch.

Thanks!

**Comment by lichtamberg** [comment]
Damn! I just misstyped my cert_file path... Sorry!
