### ISSUE TITLE
ancient versions of psutil should probably explode

### ISSUE THREAD

**Issue by ahammond** [saltstack/salt#24951]
```
root@hss4[prd-sj-uhs-6]:/usr/lib64/python2.6/site-packages # salt-call test.ping
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 221, in salt_call
    import salt.cli.call
  File "/usr/lib/python2.6/site-packages/salt/cli/call.py", line 9, in <module>
    import salt.cli.caller
  File "/usr/lib/python2.6/site-packages/salt/cli/caller.py", line 21, in <module>
    import salt.minion
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 45, in <module>
    import salt.utils.psutil_compat as psutil
  File "/usr/lib/python2.6/site-packages/salt/utils/psutil_compat.py", line 44, in <module>
    users = psutil.get_users
AttributeError: 'module' object has no attribute 'get_users'
root@hss4[prd-sj-uhs-6]:~ # python
Python 2.6.6 (r266:84292, Dec  7 2011, 20:48:22) 
[GCC 4.4.6 20110731 (Red Hat 4.4.6-3)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import psutil
>>> psutil.version_info
(0, 4, 1)
>>> 
```

I'm going to see about putting the latest, greatest psutil in our package to work around this.

**Comment by jfindlay** [comment]
@ahammond, thanks for the report.  This should have been fixed in #24936, which will be included in the next release.

**Comment by pille** [comment]
unfortunately ubuntu precise TLS 12.04 is ancient enough, that salt-2015.5.2+ds-1precise1 breaks.

**Comment by damonnk** [comment]
I have the same problem on LTS 12.04.
```
# salt-minion -l debug
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: myimbahostname
[DEBUG   ] Configuration file path: /etc/salt/minion
[INFO    ] Setting up the Salt Minion "myimbahostname"
[INFO    ] The salt minion is shut down
[ERROR   ] 'module' object has no attribute 'get_users'
```

Simply solved my removing the package python-psutil on my 12.04 hosts.
Wasn't ideal though to login to all my servers to remove the package and restart salt-minion.

**Comment by ahammond** [comment]
I updated the python-psutil package on my problem hosts and the problem went away.
