### ISSUE TITLE
Proxy minions stopped working between 2014.7 and 2015.5

### ISSUE THREAD

**Issue by jejenone** [saltstack/salt#25053]
in 2014.7:

```
(.venv)➜  jf-salt-net git:(master) ✗ salt-minion -ldebug -c etc/salt
[DEBUG   ] Reading configuration from /Users/jeje/dev/cloudflare/jf-salt-net/etc/salt/minion
[DEBUG   ] Configuration file path: /Users/jeje/dev/cloudflare/jf-salt-net/etc/salt/minion
[INFO    ] Setting up the Salt Minion "proxy36netops2"
[DEBUG   ] Created pidfile: /Users/jeje/dev/cloudflare/jf-salt-net/var/run/salt-minion.pid
[DEBUG   ] Reading configuration from /Users/jeje/dev/cloudflare/jf-salt-net/etc/salt/minion
[DEBUG   ] Attempting to authenticate with the Salt Master at 127.0.0.1
[DEBUG   ] Loaded minion key: /Users/jeje/dev/cloudflare/jf-salt-net/etc/salt/pki/minion/minion.pem
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /Users/jeje/dev/cloudflare/jf-salt-net/etc/salt/pki/minion/minion.pem
[INFO    ] Authentication with master at 127.0.0.1 successful!
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /Users/jeje/dev/cloudflare/jf-salt-net/etc/salt/pki/minion/minion.pem
[DEBUG   ] Loaded minion key: /Users/jeje/dev/cloudflare/jf-salt-net/etc/salt/pki/minion/minion.pem
[DEBUG   ] Reading configuration from /Users/jeje/dev/cloudflare/jf-salt-net/etc/salt/minion
[DEBUG   ] Mako not available
[INFO    ] Added mine.update to schedular
[INFO    ] Added new job __mine_interval to scheduler
[DEBUG   ] I am proxy36netops2 and I need to start some proxies for proxy36netops2
[DEBUG   ] Starting lab proxy.
[INFO    ] Minion is starting as user 'jeje'
[DEBUG   ] Minion 'proxy36netops2' trying to tune in
[DEBUG   ] Minion PUB socket URI: ipc:///Users/jeje/dev/cloudflare/jf-salt-net/var/run/salt/minion/minion_event_fa8107413b_pub.ipc
[DEBUG   ] Minion PULL socket URI: ipc:///Users/jeje/dev/cloudflare/jf-salt-net/var/run/salt/minion/minion_event_fa8107413b_pull.ipc
[INFO    ] Starting pub socket on ipc:///Users/jeje/dev/cloudflare/jf-salt-net/var/run/salt/minion/minion_event_fa8107413b_pub.ipc
[INFO    ] Starting pull socket on ipc:///Users/jeje/dev/cloudflare/jf-salt-net/var/run/salt/minion/minion_event_fa8107413b_pull.ipc
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (9645)
[DEBUG   ] Setting zmq_reconnect_ivl to '9645ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[WARNING ] Temporary logging is already configured
[DEBUG   ] Reading configuration from /Users/jeje/dev/cloudflare/jf-salt-net/etc/salt/minion
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /Users/jeje/dev/cloudflare/jf-salt-net/etc/salt/pki/minion/minion.pem
[WARNING ] Console logging already configured
[WARNING ] Console logging already configured
[DEBUG   ] Configuration file path: /Users/jeje/dev/cloudflare/jf-salt-net/etc/salt/minion
[WARNING ] Logfile logging already configured
[INFO    ] Setting up a Salt Proxy Minion "proxy36netops2"
[DEBUG   ] Created pidfile: /Users/jeje/dev/cloudflare/jf-salt-net/var/run/salt-minion.pid
[DEBUG   ] <module 'salt.loaded.int.proxy.rest_sample' from '/Users/jeje/dev/salt/salt/proxy/rest_sample.py'>
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /Users/jeje/dev/cloudflare/jf-salt-net/etc/salt/pki/minion/minion.pem
[INFO    ] Minion is ready to receive requests!
[INFO    ] Running scheduled job: __mine_interval
[DEBUG   ] schedule: This job was scheduled with jid_include, adding to cache (jid_include defaults to True)
[DEBUG   ] schedule: This job was scheduled with a max number of 2
[DEBUG   ] schedule.handle_func: adding this job to the jobcache with data {'fun': 'mine.update', 'jid': '20150629155632863962', 'pid': 49828, 'id': 'proxy36netops2', 'schedule': '__mine_interval'}
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /Users/jeje/dev/cloudflare/jf-salt-net/etc/salt/pki/minion/minion.pem
[DEBUG   ] Loaded minion key: /Users/jeje/dev/cloudflare/jf-salt-net/etc/salt/pki/minion/minion.pem
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /Users/jeje/dev/cloudflare/jf-salt-net/etc/salt/pki/minion/minion.pem
[DEBUG   ] Attempting to authenticate with the Salt Master at 127.0.0.1
[DEBUG   ] Loaded minion key: /Users/jeje/dev/cloudflare/jf-salt-net/etc/salt/pki/minion/minion.pem
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /Users/jeje/dev/cloudflare/jf-salt-net/etc/salt/pki/minion/minion.pem
[INFO    ] Authentication with master at 127.0.0.1 successful!
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /Users/jeje/dev/cloudflare/jf-salt-net/etc/salt/pki/minion/minion.pem
[DEBUG   ] Loaded minion key: /Users/jeje/dev/cloudflare/jf-salt-net/etc/salt/pki/minion/minion.pem
[DEBUG   ] Reading configuration from /Users/jeje/dev/cloudflare/jf-salt-net/etc/salt/minion
[DEBUG   ] <module 'salt.loaded.int.grain.rest_sample' from '/Users/jeje/dev/salt/salt/grains/rest_sample.pyc'>
[DEBUG   ] <module 'salt.loaded.int.module.rest_package' from '/Users/jeje/dev/salt/salt/modules/rest_package.pyc'>
[DEBUG   ] <module 'salt.loaded.int.module.rest_sample' from '/Users/jeje/dev/salt/salt/modules/rest_sample.pyc'>
[DEBUG   ] <module 'salt.loaded.int.module.rest_service' from '/Users/jeje/dev/salt/salt/modules/rest_service.pyc'>
[INFO    ] ProxyMinion is starting as user 'jeje'
[DEBUG   ] Minion 'edge01.lab01.sfo01' trying to tune in
[DEBUG   ] ProxyMinion PUB socket URI: ipc:///Users/jeje/dev/cloudflare/jf-salt-net/var/run/salt/minion/minion_event_5b1b337274_pub.ipc
[DEBUG   ] ProxyMinion PULL socket URI: ipc:///Users/jeje/dev/cloudflare/jf-salt-net/var/run/salt/minion/minion_event_5b1b337274_pull.ipc
[INFO    ] Starting pub socket on ipc:///Users/jeje/dev/cloudflare/jf-salt-net/var/run/salt/minion/minion_event_5b1b337274_pub.ipc
[INFO    ] Starting pull socket on ipc:///Users/jeje/dev/cloudflare/jf-salt-net/var/run/salt/minion/minion_event_5b1b337274_pull.ipc
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (10705)
[DEBUG   ] Setting zmq_reconnect_ivl to '10705ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /Users/jeje/dev/cloudflare/jf-salt-net/etc/salt/pki/minion/minion.pem
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /Users/jeje/dev/cloudflare/jf-salt-net/etc/salt/pki/minion/minion.pem
[INFO    ] Minion is ready to receive requests!
```

after upgrading to 2015.5 in a dev environment:

```
(.venv)➜  jf-salt-net git:(master) ✗ salt-minion -ldebug -c etc/salt
[DEBUG   ] Reading configuration from /Users/jeje/dev/cloudflare/jf-salt-net/etc/salt/minion
[DEBUG   ] Configuration file path: /Users/jeje/dev/cloudflare/jf-salt-net/etc/salt/minion
[INFO    ] Setting up the Salt Minion "proxy36netops2"
[DEBUG   ] Created pidfile: /Users/jeje/dev/cloudflare/jf-salt-net/var/run/salt-minion.pid
[DEBUG   ] Reading configuration from /Users/jeje/dev/cloudflare/jf-salt-net/etc/salt/minion
[DEBUG   ] Attempting to authenticate with the Salt Master at 127.0.0.1
[DEBUG   ] Initializing new SAuth for ('/Users/jeje/dev/cloudflare/jf-salt-net/etc/salt/pki/minion', 'proxy36netops2', 'tcp://127.0.0.1:4506')
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /Users/jeje/dev/cloudflare/jf-salt-net/etc/salt/pki/minion/minion.pem
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /Users/jeje/dev/cloudflare/jf-salt-net/etc/salt/pki/minion/minion.pem
[DEBUG   ] Loaded minion key: /Users/jeje/dev/cloudflare/jf-salt-net/etc/salt/pki/minion/minion.pem
[DEBUG   ] Re-using SAuth for ('/Users/jeje/dev/cloudflare/jf-salt-net/etc/salt/pki/minion', 'proxy36netops2', 'tcp://127.0.0.1:4506')
[DEBUG   ] Loaded minion key: /Users/jeje/dev/cloudflare/jf-salt-net/etc/salt/pki/minion/minion.pem
[DEBUG   ] Reading configuration from /Users/jeje/dev/cloudflare/jf-salt-net/etc/salt/minion
[DEBUG   ] LazyLoaded timezone.get_offset
[DEBUG   ] LazyLoaded cmd.run
[INFO    ] Executing command 'date +%z' in directory '/Users/jeje'
[DEBUG   ] output: -0700
[DEBUG   ] LazyLoaded config.merge
[DEBUG   ] LazyLoaded mine.update
[INFO    ] Added mine.update to scheduler
[INFO    ] Added new job __mine_interval to scheduler
[ERROR   ] Failed to persist the updated schedule
[DEBUG   ] I am proxy36netops2 and I need to start some proxies for {'lab': {'username': 'netconf', 'proxytype': 'junos', 'host': 'rs01.sfo01.as13335.net', 'passwd': 'b3tt3rw3b'}}
[DEBUG   ] Starting lab proxy.
[INFO    ] The salt minion is starting up
[INFO    ] The salt minion is shut down
[INFO    ] Minion is starting as user 'jeje'
[DEBUG   ] Minion 'proxy36netops2' trying to tune in
[ERROR   ] 'module' object has no attribute 'ProxyMinion'
[WARNING ] ** Restarting minion **
[INFO    ] Sleeping random_reauth_delay of 6 seconds
[DEBUG   ] Minion PUB socket URI: ipc:///Users/jeje/dev/cloudflare/jf-salt-net/var/run/salt/minion/minion_event_fa8107413b_pub.ipc
[DEBUG   ] Minion PULL socket URI: ipc:///Users/jeje/dev/cloudflare/jf-salt-net/var/run/salt/minion/minion_event_fa8107413b_pull.ipc
[INFO    ] Starting pub socket on ipc:///Users/jeje/dev/cloudflare/jf-salt-net/var/run/salt/minion/minion_event_fa8107413b_pub.ipc
[INFO    ] Starting pull socket on ipc:///Users/jeje/dev/cloudflare/jf-salt-net/var/run/salt/minion/minion_event_fa8107413b_pull.ipc
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (6111)
[DEBUG   ] Setting zmq_reconnect_ivl to '6111ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Re-using SAuth for ('/Users/jeje/dev/cloudflare/jf-salt-net/etc/salt/pki/minion', 'proxy36netops2', 'tcp://127.0.0.1:4506')
[DEBUG   ] Re-using SAuth for ('/Users/jeje/dev/cloudflare/jf-salt-net/etc/salt/pki/minion', 'proxy36netops2', 'tcp://127.0.0.1:4506')
[INFO    ] Minion is ready to receive requests!
[INFO    ] Running scheduled job: __mine_interval
[DEBUG   ] schedule: This job was scheduled with jid_include, adding to cache (jid_include defaults to True)
[DEBUG   ] schedule: This job was scheduled with a max number of 2
[DEBUG   ] schedule.handle_func: adding this job to the jobcache with data {'fun': 'mine.update', 'jid': '20150629154354879625', 'pid': 49053, 'id': 'proxy36netops2', 'schedule': '__mine_interval'}
[DEBUG   ] Re-using SAuth for ('/Users/jeje/dev/cloudflare/jf-salt-net/etc/salt/pki/minion', 'proxy36netops2', 'tcp://127.0.0.1:4506')
[DEBUG   ] Loaded minion key: /Users/jeje/dev/cloudflare/jf-salt-net/etc/salt/pki/minion/minion.pem
[DEBUG   ] MinionEvent PUB socket URI: ipc:///Users/jeje/dev/cloudflare/jf-salt-net/var/run/salt/minion/minion_event_fa8107413b_pub.ipc
[DEBUG   ] MinionEvent PULL socket URI: ipc:///Users/jeje/dev/cloudflare/jf-salt-net/var/run/salt/minion/minion_event_fa8107413b_pull.ipc
[DEBUG   ] Sending event - data = {'_stamp': '2015-06-29T22:43:54.905673'}
[DEBUG   ] Handling event 'salt/event/new_client\n\n\x81\xa6_stamp\xba2015-06-29T22:43:54.905673'
[DEBUG   ] Sending event - data = {'_stamp': '2015-06-29T22:43:54.907925', 'clear': False, 'cmd': '_mine', 'tok': '>\xe3\xde\xa9xj\xca\xda\x1f\x1eK\x1a\xe3\x95A\x7fO\xf6\xe2\xb9D\xe4}\x88WA\xb0\xe4\rF\xbe\xbe\xfa\xa2$\xc6\xe5\xaf18\xf8\xeb\x12\xdaC(\xb7\xb5\x8c\xfb>Z\x0bZ\xa5?\xc6B[j\xf3\xf4\xfa\xb2\'?a\x0e\xd5,g\xd9\x1a\x15n=\x14\xdeW\xcb:\x1c\xf3\xf9\x81g\xae\xd3\x8bS@k\xe6[\xb9\xed\x9e\xc6\xa6\xf6\xd5\xf0\xef\xf3#/\x0fl\xa1\xed\xb4\xe7\xc7w\x06\xbe5\x97\xc1?\x97\x08~\xa8X#S\xb1[\xfc&\xf5\x13H1\x9e\xff\x9b\xb3\xca\xe0%a\xf5\x91\xc4\xbb\xcc\xdf\xe4z8\x98\xda\xcd\x81\xb2oy\xef\xb3\x18\xa6\xfaw\xac\x9b\x1a5\xd4\xcf\x12["o~L\x03\xdeeO\x98\x18z\xd4P\xa7&\x85\xd6[&o\xeb\x8b\x85d\xf3\xd7,\x1fX\xad\xe4\xe7\xb2\xab\xa2\xff\xe24\x94\xd8K\x1c\x96\xd9\xdb\x14R\xfb\xa7f56i!\xeax\x8d\xd6\xa6\xdc\xea\x17\xb7\xf7\x08\x00\xb5>/5\x16bR%S\x935\xf4\x80V\x1d\x7fH', 'data': {}, 'id': 'proxy36netops2'}
[DEBUG   ] Handling event '_minion_mine\n\n\x86\xa6_stamp\xba2015-06-29T22:43:54.907925\xa5clear\xc2\xa3cmd\xa5_mine\xa3tok\xda\x01\x00>\xe3\xde\xa9xj\xca\xda\x1f\x1eK\x1a\xe3\x95A\x7fO\xf6\xe2\xb9D\xe4}\x88WA\xb0\xe4\rF\xbe\xbe\xfa\xa2$\xc6\xe5\xaf18\xf8\xeb\x12\xdaC(\xb7\xb5\x8c\xfb>Z\x0bZ\xa5?\xc6B[j\xf3\xf4\xfa\xb2\'?a\x0e\xd5,g\xd9\x1a\x15n=\x14\xdeW\xcb:\x1c\xf3\xf9\x81g\xae\xd3\x8bS@k\xe6[\xb9\xed\x9e\xc6\xa6\xf6\xd5\xf0\xef\xf3#/\x0fl\xa1\xed\xb4\xe7\xc7w\x06\xbe5\x97\xc1?\x97\x08~\xa8X#S\xb1[\xfc&\xf5\x13H1\x9e\xff\x9b\xb3\xca\xe0%a\xf5\x91\xc4\xbb\xcc\xdf\xe4z8\x98\xda\xcd\x81\xb2oy\xef\xb3\x18\xa6\xfaw\xac\x9b\x1a5\xd4\xcf\x12["o~L\x03\xdeeO\x98\x18z\xd4P\xa7&\x85\xd6[&o\xeb\x8b\x85d\xf3\xd7,\x1fX\xad\xe4\xe7\xb2\xab\xa2\xff\xe24\x94\xd8K\x1c\x96\xd9\xdb\x14R\xfb\xa7f56i!\xeax\x8d\xd6\xa6\xdc\xea\x17\xb7\xf7\x08\x00\xb5>/5\x16bR%S\x935\xf4\x80V\x1d\x7fH\xa4data\x80\xa2id\xaeproxy36netops2'
[DEBUG   ] Re-using SAuth for ('/Users/jeje/dev/cloudflare/jf-salt-net/etc/salt/pki/minion', 'proxy36netops2', 'tcp://127.0.0.1:4506')
```

I get the error `[ERROR   ] 'module' object has no attribute 'ProxyMinion'`

on the develop branch I get:

```
[ERROR   ] Minion failed to start:
Traceback (most recent call last):
  File "/Users/jeje/dev/salt/salt/scripts.py", line 81, in minion_process
    minion.start()
  File "/Users/jeje/dev/salt/salt/cli/daemons.py", line 269, in start
    self.minion.tune_in()
  File "/Users/jeje/dev/salt/salt/minion.py", line 1617, in tune_in
    self.sync_connect_master()
  File "/Users/jeje/dev/salt/salt/minion.py", line 607, in sync_connect_master
    raise six.reraise(*future_exception)
  File "/Users/jeje/dev/cloudflare/jf-salt-net/.venv/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/jeje/dev/salt/salt/minion.py", line 615, in connect_master
    yield self._post_master_init(master)
  File "/Users/jeje/dev/cloudflare/jf-salt-net/.venv/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/Users/jeje/dev/cloudflare/jf-salt-net/.venv/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/Users/jeje/dev/cloudflare/jf-salt-net/.venv/lib/python2.7/site-packages/tornado/gen.py", line 879, in run
    yielded = self.gen.send(value)
  File "/Users/jeje/dev/salt/salt/minion.py", line 687, in _post_master_init
    proxyminion = ProxyMinion(self.opts)
  File "/Users/jeje/dev/salt/salt/minion.py", line 2492, in __init__
    fq_proxyname = 'proxy.'+opts['proxy']['proxytype']
KeyError: 'proxy'
```

**Comment by jfindlay** [comment]
@jejenone, thanks for the report.

**Comment by jejenone** [comment]
Hi. Any chance on a fix for this one ?

**Comment by arthurlogilab** [comment]
am interested in the fix too (started patching it but didn't know if there was a fix out there in some branch)

**Comment by jejenone** [comment]
Arthur, if you managed to patch I'm interested.

**Comment by cro** [comment]
@jejenone, @arthurlogilab Greetings!

Fixes for these issues, as well as better documentation for using the rest_sample example, will be committed later today to the 2015.5 branch.

Note that the fix is related to the LazyLoader, and will require some changes to the way proxy modules work--the LazyLoader doesn't like classes very much, so proxy modules have to be developed using only functions.  It's not a big deal, but it does require moditications to files in the `salt/proxy` directory.

**Comment by arthurlogilab** [comment]
@cro, indeed I had a dirty hack in the lazyloader to take into account the loading of classes in the case of a proxy lazyloader. not ideal. 

good news about the patch. Willing to give a helping hand on testing.

**Comment by jejenone** [comment]
+1 -  can't wait for the commits.

**Comment by arthurlogilab** [comment]
@jejenone this is a (still not working) version of my wip : https://github.com/arthurlogilab/salt/commit/52e0dee3051a4c372de0eff4f268b12c65dd0b27

@cro any news of the patch ? 

@cro after patching various places I wasn't sure if the MinionProxy class to use was the one in salt/minion.py or salt/cli/daemons.py  any reason for having these two ? 

unittest testing on MinionProxy would be nice, should I add an issue ?

**Comment by hishailesh77** [comment]
@cro :- I am Eagerly waiting for patch .

**Comment by rallytime** [comment]
See #26135
