### ISSUE TITLE
salt-run state.event pretty=True fails on CentOS 6.6 Saltstack 2015.5.2

### ISSUE THREAD

**Issue by githubcdr** [saltstack/salt#25064]
The following command fails after enabling the btmp beacon on a minion;

```
[root@saltstack ~ ]# salt-run state.event pretty=True
Exception occurred in runner state.event: Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/client/mixins.py", line 317, in low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/runners/state.py", line 355, in event
    indent=None if not pretty else 4)))
  File "/usr/lib64/python2.6/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib64/python2.6/json/encoder.py", line 367, in encode
    chunks = list(self.iterencode(o))
  File "/usr/lib64/python2.6/json/encoder.py", line 309, in _iterencode
    for chunk in self._iterencode_dict(o, markers):
  File "/usr/lib64/python2.6/json/encoder.py", line 275, in _iterencode_dict
    for chunk in self._iterencode(value, markers):
  File "/usr/lib64/python2.6/json/encoder.py", line 309, in _iterencode
    for chunk in self._iterencode_dict(o, markers):
  File "/usr/lib64/python2.6/json/encoder.py", line 275, in _iterencode_dict
    for chunk in self._iterencode(value, markers):
  File "/usr/lib64/python2.6/json/encoder.py", line 294, in _iterencode
    yield encoder(o)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa2 in position 0: invalid start byte
```

For completeness the locales on this Machine and versions;

```
[root@saltstack ~ ]# locale
LANG=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_COLLATE=en_US.UTF-8
LC_MONETARY=en_US.UTF-8
LC_MESSAGES=en_US.UTF-8
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

[root@saltstack ~ ]# salt-master --versions-report
           Salt: 2015.5.2
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: 2.7.3
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: 0.1.3
       pycrypto: 2.0.1
        libnacl: 1.4.0
         PyYAML: 3.11
          ioflo: 1.1.2
          PyZMQ: 14.5.0
           RAET: 0.4.2
            ZMQ: 4.0.5
           Mako: 1.0.0
```

Running the old eventlistnen.py does work and shows some raw data.

```
{'_stamp': '2015-06-30T11:16:29.759793',
 'data': {'PID': 0,
          'addr': 0,
          'exit_status': 0,
          'hostname': '\x8dz\x92U\x00\x00\x00\x00\xdaWov\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x06\x00\x00\x00Lo\x00\x00ssh:notty\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00root\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0043.25.41.42',
          'id': 'redacted',
          'inittab': '',
          'line': '',
          'session': 0,
          'time': 0,
          'type': 0,
          'user': ''},
 'tag': 'salt/beacon/redacted/btmp/'}
```

**Comment by jfindlay** [comment]
@githubcdr, thanks for the report.
