### ISSUE TITLE
salt-minion still communicating with salt-master after "salt-key -d hostname"

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#25124]
```
root@ursa:~# salt-key -d ursa
The following keys are going to be deleted:
Accepted Keys:
ursa
Proceed? [N/y] y
Key for minion ursa deleted.
root@ursa:~# salt \* state.highstate test=True
ursa:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1142, in _thread_return
        return_data = func(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 507, in highstate
        st_ = salt.state.HighState(opts, pillar, kwargs.get('__pub_jid'))
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 3029, in __init__
        self.state = State(self.opts, pillar, jid)
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 579, in __init__
        self.opts['pillar'] = self._gather_pillar()
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 600, in _gather_pillar
        ret = pillar.compile_pillar()
      File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 83, in compile_pillar
        dictkey='pillar',
      File "/usr/lib/python2.7/dist-packages/salt/transport/__init__.py", line 271, in crypted_transfer_decode_dictentry
        ret = self.sreq.send('aes', self.auth.crypticle.dumps(load), tries, timeout)
      File "/usr/lib/python2.7/dist-packages/salt/payload.py", line 275, in send
        return self.serial.loads(self.socket.recv())
      File "/usr/lib/python2.7/dist-packages/salt/payload.py", line 98, in loads
        return msgpack.loads(msg, use_list=True)
      File "_unpacker.pyx", line 114, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:114)
    ExtraData: unpack(b) recieved extra data.
Salt request timed out. The master is not responding. If this error persists after verifying the master is up, worker_threads may need to be increased.
root@ursa:~# salt --versions-report
                  Salt: 2015.5.0
                Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
 Debian source package: 2015.5.0+ds-1trusty1
```

**Comment by arroyoc** [comment]
@arthurlogilab Thanks for the report.

**Comment by cachedout** [comment]
I have tested this. Immediatley after we remove the key with `salt-key -d <id>`, it is true that the minion and master can still communicate. It is not until the maintenance process runs on the master that a need for key rotation is detected and the shared AES key is rotated, thus cutting of communication between the two. By default, that can be up to 60s.

I think we should change this behaviour so that the master rotates the AES key immediately after all key deletions happen. (Though this still leaves a tiny window in which they will be connected, if many keys are being deleted.)
