### ISSUE TITLE
(boto_secgroup) Add a rule that allows ALL TRAFFIC to a sec group

### ISSUE THREAD

**Issue by relopezz** [saltstack/salt#25127]
using salt --version: 2015.5.0] I want to add a rule that allows ALL TRAFFIC from another security group. 

I have this in my pillar:

``` securitygroups:
    groups:
       - name: NFS
         region: us-east-1
         vpc_id: vpc-1234
         description: desc
         rules:
           - ip_protocol: -1
             from_port: -1
             to_port: -1
             ec2_group: sg123456
```

API suggests to use -1 to specify all IpProtcol. But I'm getting this error:

``` ----------
          ID: secgroups_NFSecurityGroup
    Function: boto_secgroup.present
        Name: NFSecurityGroup
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.6/site-packages/salt/state.py", line 1563, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.6/site-packages/salt/states/boto_secgroup.py", line 140, in present
                  _ret = _rules_present(name, rules, vpc_id, region, key, keyid, profile)
                File "/usr/lib/python2.6/site-packages/salt/states/boto_secgroup.py", line 345, in _rules_present
                  to_delete, to_create = _get_rule_changes(rules, sg['rules'])
                File "/usr/lib/python2.6/site-packages/salt/states/boto_secgroup.py", line 265, in _get_rule_changes
                  raise SaltInvocationError(msg.format(ip_protocol))
              SaltInvocationError: Invalid ip_protocol traffic specified in security group rule.
     Started: 03:09:58.163808
    Duration: 235.323 ms
```

from_port: -1 and to_port: -1 works fine if I specify an ip_protocol: icmp|tcp|udp

**Comment by jtand** [comment]
@relopezz Thanks for this, that should definitely be added.

**Comment by lomeroe** [comment]
@relopezz try using "ip_protocol: all"

**Comment by twellspring** [comment]
This now works in 2016.11.3 but not cleanly.  Using source_group_name instead of ec2_group like this
```
    - rules:
        - ip_protocol: -1
          from_port: -1
          to_port: -1
          source_group_name: sgApp-vpcProdEast
```

Creates a group correctly. 
``` 
Type=ALL Traffic
Protocol=All
Port Range=All
Source= sgXXXXXXX
````

But every time subsequently you run this it shows a change, but the rule does not change in the security group.
```
     Changes:
              ----------
              new:
                  ----------
                  rules:
                      |_
                        ----------
                        from_port:
                            None
                        ip_protocol:
                            -1
                        source_group_group_id:
                            sg-fc78f895
                        source_group_owner_id:
                            747602142433
                        to_port:
                            None
              old:
                  ----------
                  rules:
                      |_
                        ----------
                        from_port:
                            -1
                        ip_protocol:
                            -1
                        source_group_group_id:
                            sg-fc78f895
                        source_group_owner_id:
                            747602142433
                        to_port:
                            -1
```
