### ISSUE TITLE
keystone.tenant_present issue with not finding state

### ISSUE THREAD

**Issue by yee379** [saltstack/salt#25137]
i'm using salt-master 2015.5.2, and i have the following state:

```
ks db_sync:
  cmd.run:
    - name: keystone-manage db_sync
    - require_in:
      - keystone: ks admin tenant

ks admin tenant:
  keystone.tenant_present:
    - name: admin
    - connection_token: <REDACTED>
    - connection_endpoint: http://<REDACTED>:35357/v2.0
```

however, when i run it i get:

```
$ salt node1 state.sls crap
node1:
----------
          ID: ks db_sync
    Function: cmd.run
        Name: keystone-manage db_sync
      Result: True
     Comment: Command "keystone-manage db_sync" run
     Started: 14:53:49.317895
    Duration: 907.58 ms
     Changes:
              ----------
              pid:
                  4117
              retcode:
                  0
              stderr:
              stdout:
----------
          ID: ks admin tenant
    Function: keystone.tenant_present
        Name: admin
      Result: False
     Comment: State 'keystone.tenant_present' was not found in SLS 'crap'
     Started:
    Duration:
     Changes:

Summary
------------
Succeeded: 1 (changed=1)
Failed:    1
------------
Total states run:     2
```

**Comment by nmadhok** [comment]
Do you have the keystone python package installed?

**Comment by yee379** [comment]
yep:

```
----------
          ID: ks python-keystone
    Function: pkg.installed
        Name: python-keystoneclient
      Result: True
     Comment: Package python-keystoneclient is already installed.
     Started: 12:16:28.402583
    Duration: 806.716 ms
     Changes:
----------
          ID: ks db_sync
    Function: cmd.run
        Name: keystone-manage db_sync
      Result: True
     Comment: Command "keystone-manage db_sync" run
     Started: 12:16:29.430888
    Duration: 859.052 ms
     Changes:
              ----------
              pid:
                  10110
              retcode:
                  0
              stderr:
              stdout:
----------
          ID: ks admin tenant
    Function: keystone.tenant_present
        Name: admin
      Result: False
     Comment: State 'keystone.tenant_present' was not found in SLS 'crap'
     Started:
    Duration:
     Changes:

Summary
------------
Succeeded: 2 (changed=1)
Failed:    1
------------
Total states run:     3
```

also, locally on the host:

```
$ salt <REDACTED> grains.get pythonexecutable
<REDACTED>:
    /usr/bin/python
```
```
# /usr/bin/python
Python 2.7.5 (default, Jun 24 2015, 00:41:19)
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import keystone
>>> import pkg_resources
>>> pkg_resources.get_distribution("keystone").version
'2014.2.2'
>>> quit
Use quit() or Ctrl-D (i.e. EOF) to exit
```

**Comment by jfindlay** [comment]
@yee379, thanks for the report.  What happens when you run the states separately in two steps (`ks db_sync` and then `ks admin tenant`)?

**Comment by yee379** [comment]
@jfindlay, here's the output:

```
$ salt <REDACTED> state.sls crap_a
<REDACTED>:
----------
          ID: ks db_sync new
    Function: cmd.run
        Name: keystone-manage db_sync
      Result: True
     Comment: Command "keystone-manage db_sync" run
     Started: 13:12:32.672298
    Duration: 860.065 ms
     Changes:
              ----------
              pid:
                  27620
              retcode:
                  0
              stderr:
              stdout:

Summary
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
```
```
$ salt <REDACTED> state.sls crap_b
<REDACTED>:
----------
          ID: ks admin tenant new
    Function: keystone.tenant_present
        Name: admin
      Result: False
     Comment: State 'keystone.tenant_present' was not found in SLS 'crap_b'
     Started:
    Duration:
     Changes:

Summary
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
```

**Comment by jfindlay** [comment]
@yee379, thanks for the extra information.  That concludes that the problem is in the state itself rather than the state system.

**Comment by nmadhok** [comment]
@jfindlay The ``keystone.tenant_present`` works for me on 2015.5 branch in my test

**Comment by jfindlay** [comment]
@nmadhok, were you able to reproduce @yee379's test case exactly or is there any important difference that you can think of?

**Comment by nmadhok** [comment]
@jfindlay I also added ``description: "Tenant Description"`` but that shouldn't make a difference.

**Comment by yee379** [comment]
@jfindlay, indeed, the `description` didn't make any difference.

what i did find out however, was that the minion (/var/log/salt/minion) was complaining about `six` and `AttributeError: 'module' object has no attribute 'PY2'`.... so i did a `pip install six -U` to version `1.9.0` and it now appears to work! :)

with regards to this ticket, would it be possible to get more meaningful output from the job run? eg spit out the traceback back to the master?

**Comment by nmadhok** [comment]
@yee379 What? That doesn't even make sense because six is shipped with salt and it uses six that's shipped with it
```
import salt.ext.six as six
```

**Comment by yee379** [comment]
@nmadhok i think the version i needed for the openstack modules required a higher version to what was installed on my centos 7.1 system.

```
>>> import six
>>> six.__version__
'1.3.0'
>>> six.PY2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'PY2'
```

after upgrading six, it works:

```
>>> import six
>>> six.__version__
'1.9.0'
>>> six.PY2
True
```

**Comment by nmadhok** [comment]
@yee379 Can you please post the full traceback from the minion log?

**Comment by yee379** [comment]
@nmadhok sure:

```
2015-07-08 11:41:57,791 [salt.loader      ][ERROR   ][22761] Failed to import module keystone, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 957, in _load_module
    ), fn_, fpath, desc)
  File "/var/cache/salt/minion/extmods/modules/keystone.py", line 55, in <module>
    from keystoneclient.v2_0 import client
  File "/usr/lib/python2.7/site-packages/keystoneclient/__init__.py", line 25, in <module>
    from keystoneclient import access
  File "/usr/lib/python2.7/site-packages/keystoneclient/access.py", line 21, in <module>
    from keystoneclient import service_catalog
  File "/usr/lib/python2.7/site-packages/keystoneclient/service_catalog.py", line 23, in <module>
    from keystoneclient import exceptions
  File "/usr/lib/python2.7/site-packages/keystoneclient/exceptions.py", line 20, in <module>
    from keystoneclient.openstack.common.apiclient.exceptions import *
  File "/usr/lib/python2.7/site-packages/keystoneclient/openstack/common/apiclient/exceptions.py", line 28, in <module>
    from keystoneclient.openstack.common.gettextutils import _
  File "/usr/lib/python2.7/site-packages/keystoneclient/openstack/common/gettextutils.py", line 176, in <module>
    class Message(six.text_type):
  File "/usr/lib/python2.7/site-packages/keystoneclient/openstack/common/gettextutils.py", line 307, in Message
    if six.PY2:
AttributeError: 'module' object has no attribute 'PY2'
2015-07-08 11:41:58,143 [salt.loader      ][ERROR   ][22761] Failed to import module nova, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 957, in _load_module
    ), fn_, fpath, desc)
  File "/usr/lib/python2.7/site-packages/salt/modules/nova.py", line 46, in <module>
    import salt.utils.openstack.nova as suon
  File "/usr/lib/python2.7/site-packages/salt/utils/openstack/nova.py", line 10, in <module>
    from novaclient.v1_1 import client
  File "/usr/lib/python2.7/site-packages/novaclient/v1_1/__init__.py", line 17, in <module>
    from novaclient.v1_1.client import Client   # noqa
  File "/usr/lib/python2.7/site-packages/novaclient/v1_1/client.py", line 16, in <module>
    from novaclient import client
  File "/usr/lib/python2.7/site-packages/novaclient/client.py", line 33, in <module>
    from keystoneclient import adapter
  File "/usr/lib/python2.7/site-packages/keystoneclient/__init__.py", line 25, in <module>
    from keystoneclient import access
  File "/usr/lib/python2.7/site-packages/keystoneclient/access.py", line 21, in <module>
    from keystoneclient import service_catalog
  File "/usr/lib/python2.7/site-packages/keystoneclient/service_catalog.py", line 23, in <module>
    from keystoneclient import exceptions
  File "/usr/lib/python2.7/site-packages/keystoneclient/exceptions.py", line 20, in <module>
    from keystoneclient.openstack.common.apiclient.exceptions import *
  File "/usr/lib/python2.7/site-packages/keystoneclient/openstack/common/apiclient/exceptions.py", line 28, in <module>
    from keystoneclient.openstack.common.gettextutils import _
  File "/usr/lib/python2.7/site-packages/keystoneclient/openstack/common/gettextutils.py", line 176, in <module>
    class Message(six.text_type):
  File "/usr/lib/python2.7/site-packages/keystoneclient/openstack/common/gettextutils.py", line 307, in Message
    if six.PY2:
AttributeError: 'module' object has no attribute 'PY2'
```

**Comment by nmadhok** [comment]
@yee379 Seems like openstack client packages require a newer version of six. It's not a salt related issue but an old version of a dependency. Thanks for providing the information!

**Comment by msciciel** [comment]
I have similar issue. When calling with salt-call then it's ok:

<pre>
salt-call keystone.service_list
local:
    ----------
    keystone:
        ----------
        description:
            Keystone Identity service
        id:
            fe3b59f922d3497f97034821b42e401d
        name:
            keystone
        type:
            identity
    neutron:
        ----------
        description:
            OpenStack Networking
        id:
            d5934246086a4dc9afa266b413017901
        name:
            neutron
        type:
            network
    nova:
        ----------
        description:
            OpenStack Compute Service
        id:
            d06de416753c482fad0b71ef2e30e2e2
        name:
            nova
        type:
            compute
</pre>

But calling from master:

<pre>
salt 'ctrl' keystone.service_list

ctrl:
    'keystone' __virtual__ returned False
</pre>

<pre>
           Salt: 2015.5.2
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: 2.7.2
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
</pre>
