### ISSUE TITLE
[ERROR   ] There was a profile error: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by iconnectionkit** [saltstack/salt#25152]
salt-cloud fails when trying to create instance on runabove.com which is powered by openstack
```
salt-cloud --list-images and similar functions are working correctly
```
only one that fails is `salt-cloud -p sandbox1 kk6 -l trace`

followed tutorial from https://community.runabove.com/kb/en/instances/spinning-up-instances-with-saltstack.html

even tried git checkout with exact same version described in tutorial, still fails

----------------------------
/etc/salt/cloud.profiles.d/runabove.profiles.conf
```yaml
sandbox1:
  provider: 'runabove'
  image: 'Debian 7'
  size: 'ra.intel.sb.m'
```
----------------------------
/etc/salt/cloud.providers.d/runabove.conf
```yaml
runabove:
  identity_url: https://auth.runabove.io/v2.0/tokens
  compute_name: nova
  compute_region: #THE-REGION#
  service_type: compute
  tenant: '#THE-TENANT#'
  user: '#your-email@test.tld#'
  password: #S3cr37Pa55w0rd#
  provider: openstack
  networks:
    - fixed:
    - #NETWORK-UUDI#
```
----------------------------
default /etc/salt/cloud config file
```yaml
salt-cloud --version
salt-cloud 2015.5.2 (Lithium)

salt-cloud --versions-report
            Salt: 2015.5.2
          Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
          Jinja2: unknown
        M2Crypto: 0.20.2
  msgpack-python: 0.4.6
    msgpack-pure: Not Installed
        pycrypto: 2.0.1
         libnacl: Not Installed
          PyYAML: 3.10
           ioflo: Not Installed
           PyZMQ: 14.3.1
            RAET: Not Installed
             ZMQ: 3.2.5
            Mako: Not Installed
 Apache Libcloud: 0.17.0
```
```
salt-cloud -p sandbox1 kk6 -l trace
[DEBUG   ] Reading configuration from /etc/salt/cloud
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Missing configuration file: /etc/salt/cloud.providers
[DEBUG   ] Including configuration from '/etc/salt/cloud.providers.d/runabove.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers.d/runabove.conf
[DEBUG   ] Missing configuration file: /etc/salt/cloud.profiles
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/runabove.profiles.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/runabove.profiles.conf
[TRACE   ] None of the required configuration sections, 'logstash_udp_handler' and 'logstash_zmq_handler', were found the in the configuration. Not loading the Logstash logging handlers module.
[DEBUG   ] Configuration file path: /etc/salt/cloud
[TRACE   ] Trying pysss.getgrouplist for 'root'
[TRACE   ] Trying generic group list for 'root'
[TRACE   ] Group list for user 'root': []
[INFO    ] salt-cloud starting
[TRACE   ] 'parallels.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
/usr/lib/python2.6/site-packages/salt/cloud/clouds/digital_ocean.py:86: DeprecationWarning: The digital_ocean driver is deprecated and will be removed in Salt Beryllium. Please convert your digital ocean provider configs to use the digital_ocean_v2 driver.[DEBUG   ] Failed to import clouds joyent:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/loader.py", line 957, in _load_module
    ), fn_, fpath, desc)
  File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/joyent.py", line 68, in <module>
    from Crypto.Signature import PKCS1_v1_5
ImportError: No module named Signature
[DEBUG   ] Could not LazyLoad parallels.avail_sizes
[TRACE   ] 'parallels.avail_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] LazyLoaded parallels.avail_locations
[TRACE   ] 'proxmox.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[TRACE   ] 'saltify.destroy' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] Could not LazyLoad saltify.destroy
[TRACE   ] 'saltify.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] Could not LazyLoad saltify.avail_sizes
[TRACE   ] 'saltify.avail_images' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] Could not LazyLoad saltify.avail_images
[TRACE   ] 'saltify.avail_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] Could not LazyLoad saltify.avail_locations
[TRACE   ] 'rackspace.reboot' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] LazyLoaded rackspace.reboot
[TRACE   ] 'openstack.list_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] Could not LazyLoad openstack.list_locations
[TRACE   ] 'rackspace.list_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] LazyLoaded rackspace.list_locations
[DEBUG   ] Could not LazyLoad openstack.optimize_providers
[DEBUG   ] The 'openstack' cloud driver is unable to be optimized.
[TRACE   ] 'parallels.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] Failed to import clouds joyent:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/loader.py", line 957, in _load_module
    ), fn_, fpath, desc)
  File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/joyent.py", line 68, in <module>
    from Crypto.Signature import PKCS1_v1_5
ImportError: No module named Signature
[DEBUG   ] Could not LazyLoad parallels.avail_sizes
[TRACE   ] 'parallels.avail_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] LazyLoaded parallels.avail_locations
[TRACE   ] 'proxmox.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[TRACE   ] 'saltify.destroy' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] Could not LazyLoad saltify.destroy
[TRACE   ] 'saltify.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] Could not LazyLoad saltify.avail_sizes
[TRACE   ] 'saltify.avail_images' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] Could not LazyLoad saltify.avail_images
[TRACE   ] 'saltify.avail_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] Could not LazyLoad saltify.avail_locations
[TRACE   ] 'rackspace.reboot' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] LazyLoaded rackspace.reboot
[TRACE   ] 'openstack.list_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] Could not LazyLoad openstack.list_locations
[TRACE   ] 'rackspace.list_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] LazyLoaded rackspace.list_locations
[DEBUG   ] OpenStack authenticating using password
[DEBUG   ] Generating minion keys for 'kk6'
[DEBUG   ] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event - data = {'_stamp': '2015-07-04T19:25:04.767009'}
[DEBUG   ] Sending event - data = {'profile': 'sandbox1', 'event': 'starting create', '_stamp': '2015-07-04T19:25:05.768952', 'name': 'kk6', 'provider': 'runabove:openstack'}
[DEBUG   ] OpenStack authenticating using password
[DEBUG   ] OpenStack authenticating using password
[ERROR   ] There was a profile error: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/cloud/cli.py", line 254, in run
    self.config.get('names')
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 1388, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 1241, in create
    output = self.clouds[func](vm_)
  File "/usr/lib64/python2.6/contextlib.py", line 34, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.6/site-packages/salt/utils/context.py", line 42, in func_globals_inject
    yield
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 1241, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/openstack.py", line 698, in create
    data, vm_ = request_instance(vm_)
  File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/openstack.py", line 536, in request_instance
    for n in net['fixed']
TypeError: 'NoneType' object is not iterable
```

**Comment by jfindlay** [comment]
@iconnectionkit, thanks for the report.

**Comment by rallytime** [comment]
@iconnectionkit It looks to me like you're hitting this error because of the following in your `/etc/salt/cloud.providers.d/runabove.conf` file:
```
  networks:
    - fixed:
    - #NETWORK-UUDI#
```
In the tutorial that you linked, it states that you need to configure that information in your account and then provide that information there. The tutorial says:
```
Everything that's wrapped in "#" needs to be configured for your account, here is how to get the information. First, get some command line tools:
```
And then further instructs you to:
```
Now we are ready to gather the information to complete de provider setup:
```
And provide different ways to obtain the correct information to put in the salt-cloud config file. Does that help?
