### ISSUE TITLE
Salt-cloud fails on Softlayer due to 'size' being mandatory

### ISSUE THREAD

**Issue by geraint-jones-nz** [saltstack/salt#25228]
This change: https://github.com/saltstack/salt/commit/9a891de88777e0c7cfa8fa156e6d2cc2c597ac6c made size a mandatory item for all providers, however size has no meaning on Softlayer VMs

Salt cloud now fails with the following errors

```
... proceeding
[INFO    ] Calculating dependencies for app2.test
[INFO    ] Calculating dependencies for db5.test
[INFO    ] Calculating dependencies for app1.test
[INFO    ] Calculating dependencies for db1.test
[INFO    ] Calculating dependencies for msg0.test
[INFO    ] Calculating dependencies for web1.test
[INFO    ] Calculating dependencies for sso1.test
[INFO    ] Calculating dependencies for app3.test
[INFO    ] Calculating dependencies for db4.test
[INFO    ] Calculating dependencies for db3.test
[INFO    ] Calculating dependencies for db0.test
[INFO    ] Calculating dependencies for app0.test
[INFO    ] Calculating dependencies for msg1.test
[INFO    ] Calculating dependencies for web0.test
[INFO    ] Calculating dependencies for db6.test
[INFO    ] Calculating dependencies for sso0.test
[INFO    ] Since parallel deployment is in use, ssh console output is disabled. All ssh output will be logged though
[INFO    ] Cloud pool size: 16
[ERROR   ] The required 'size' configuration setting is missing from the 'mel-8-4-25' profile, which is configured under the '9s-softlayer' alias.
[ERROR   ] The required 'size' configuration setting is missing from the 'mel-16-4-100' profile, which is configured under the '9s-softlayer' alias.
[ERROR   ] The required 'size' configuration setting is missing from the 'mel-4-2-25' profile, which is configured under the '9s-softlayer' alias.
[ERROR   ] The required 'size' configuration setting is missing from the 'mel-16-4-100' profile, which is configured under the '9s-softlayer' alias.
[ERROR   ] The required 'size' configuration setting is missing from the 'mel-16-4-100' profile, which is configured under the '9s-softlayer' alias.
[ERROR   ] The required 'size' configuration setting is missing from the 'mel-8-4-25' profile, which is configured under the '9s-softlayer' alias.
[ERROR   ] The required 'size' configuration setting is missing from the 'mel-16-4-100' profile, which is configured under the '9s-softlayer' alias.
[ERROR   ] The required 'size' configuration setting is missing from the 'mel-16-4-100' profile, which is configured under the '9s-softlayer' alias.
[ERROR   ] The required 'size' configuration setting is missing from the 'mel-4-2-25' profile, which is configured under the '9s-softlayer' alias.
[ERROR   ] The required 'size' configuration setting is missing from the 'mel-8-4-25' profile, which is configured under the '9s-softlayer' alias.
[ERROR   ] The required 'size' configuration setting is missing from the 'mel-8-4-25' profile, which is configured under the '9s-softlayer' alias.
[ERROR   ] The required 'size' configuration setting is missing from the 'mel-8-4-25' profile, which is configured under the '9s-softlayer' alias.
[ERROR   ] The required 'size' configuration setting is missing from the 'mel-16-4-100' profile, which is configured under the '9s-softlayer' alias.
[ERROR   ] The required 'size' configuration setting is missing from the 'mel-8-4-25' profile, which is configured under the '9s-softlayer' alias.
[ERROR   ] The required 'size' configuration setting is missing from the 'mel-8-4-25' profile, which is configured under the '9s-softlayer' alias.
[ERROR   ] The required 'size' configuration setting is missing from the 'mel-8-4-25' profile, which is configured under the '9s-softlayer' alias.
[ERROR   ] Caught Exception, terminating workers
TRACE: 'bool' object has no attribute 'pop'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 60, in _call
    ret = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 2215, in create_multiprocessing
    output.pop('deploy_kwargs', None)
AttributeError: 'bool' object has no attribute 'pop'



Error: There was a query error: Exception caught
Caught Exception, terminating workers
TRACE: 'bool' object has no attribute 'pop'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 60, in _call
    ret = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 2215, in create_multiprocessing
    output.pop('deploy_kwargs', None)
AttributeError: 'bool' object has no attribute 'pop'
```

However rolling back just that single change results in this error 

```
[ERROR   ] Failed to create VM db3.test. Configuration value 'provider' needs to be set
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1256, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/softlayer.py", line 250, in create
    'provider': vm_['provider'],
KeyError: 'provider'
[ERROR   ] Failed to create VM msg1.test. Configuration value 'provider' needs to be set
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1256, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/softlayer.py", line 250, in create
    'provider': vm_['provider'],
KeyError: 'provider'
```

**Comment by geraint-jones-nz** [comment]
I have rolled back to v2015.5 and everything is working well again.

**Comment by techhat** [comment]
@rallytime, `size` does need to be removed from the global list of required values. `softlayer`, `softlayer_hw` and `parallels` don't require it.

**Comment by rallytime** [comment]
Thanks for the report @geraint-jones-nz. I'll take a look here in the next couple of days.

**Comment by rallytime** [comment]
@geraint-jones-nz The pull request above should help alleviate this issue. Please give it a try and let me know if you are still having troubles.

**Comment by geraint-jones-nz** [comment]
I will pull and verify shortly :)

**Comment by geraint-jones-nz** [comment]
Not quite

we now get :+1: 
```
[ERROR   ] Failed to create VM pxy0.test. Configuration value 'provider' needs to be set
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1256, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/softlayer.py", line 250, in create
    'provider': vm_['provider'],
KeyError: 'provider'
[ERROR   ] Failed to create VM pxy1.test. Configuration value 'provider' needs to be set
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1256, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/softlayer.py", line 250, in create
    'provider': vm_['provider'],
KeyError: 'provider'
```

**Comment by rallytime** [comment]
@geraint-jones-nz Oh, that is a slightly different bug, but I know how to fix it. Thanks for following up here and apologies for the troubles! I'll grab this first thing Monday.

**Comment by rallytime** [comment]
@geraint-jones-nz Ok, I've made another change to the driver. Can you give it one more try and see if the pull request above resolves this for you? Thanks again for bringing these bugs up.

**Comment by rallytime** [comment]
@geraint-jones-nz I am going to close this bug report as I am pretty sure this is fixed. If you bump into any more problems with it, please let us know and we can certainly re-open this issue. Thanks again!
