### ISSUE TITLE
'version' error in lxc module

### ISSUE THREAD

**Issue by thepauleh** [saltstack/salt#25230]
Hi,

Trying to get going with using salt for containers using cloud.profile. Feel like i'm nearly there but i'm getting this nasty error when it attempts the 'lxc.init' function, don't suppose anyone's seen it before? Running salt-2015.5.2-3 on python 2.6

```
The minion function caused an exception: Traceback (most recent call last): File "/usr/lib/python2.6/site-packages/salt/minion.py", line 1146, in _thread_return return_data = func(*args, **kwargs) File "/usr/lib/python2.6/site-packages/salt/modules/lxc.py", line 1395, in init cpushare=cpushare, memory=memory) File "/usr/lib/python2.6/site-packages/salt/modules/lxc.py", line 990, in __init__ net_datas = _network_conf(conf_tuples=old_net, **kwargs) File "/usr/lib/python2.6/site-packages/salt/modules/lxc.py", line 842, in _network_conf distutils.version.LooseVersion(version()) <= '1.0.7' and File "/usr/lib/python2.6/site-packages/salt/modules/lxc.py", line 104, in version if ver < distutils.version.LooseVersion('1.0'): File "/usr/lib64/python2.6/distutils/version.py", line 296, in __cmp__ return cmp(self.version, other.version) AttributeError: LooseVersion instance has no attribute 'version'
```

**Comment by thepauleh** [comment]
Turns out lxc-ls --version isn't reliable to get a version from, will raise pr that changes to lxc-info --version
