### ISSUE TITLE
AttributeError in fileserver update_opts()

### ISSUE THREAD

**Issue by ruzarowski** [saltstack/salt#25259]
Following error happens in master log since 2014.7.6:

    <timestamp> [salt.master                                 ][ERROR   ] Error in function _pillar:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/salt/master.py", line 1349, in run_func
        ret = getattr(self, func)(load)
      File "/usr/lib/python2.6/site-packages/salt/master.py", line 1107, in _pillar
        self.fs_.update_opts()
      File "/usr/lib/python2.6/site-packages/salt/fileserver/__init__.py", line 314, in update_opts
        if '__opts__' in func.func_globals:
    AttributeError: type object 'datetime.datetime' has no attribute 'func_globals'

**Comment by jfindlay** [comment]
@ruzarowski, thanks for the report and the fix.

**Comment by cachedout** [comment]
Closed by #25264
