### ISSUE TITLE
TypeError: string indices must be integers, not str on output/highstate.py

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#25255]
... and also an error on the sentry/raven submition (is there a place where I can increase the timeout for that if my sentry is being slow ? )

```
root@ursa:~# salt-run --out=highstate state.orchestrate orchestration.logilabfr
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1563, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/states/saltmod.py", line 288, in state
    __opts__,
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 172, in out_format
    return try_printout(data, out, opts)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 46, in try_printout
    return get_printout(out, opts)(data).rstrip()
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 84, in output
    return _format_host(host, hostdata)[0]
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 136, in _format_host
    schanged, ctext = _format_changes(ret['changes'])
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 391, in _format_changes
    __opts__)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 172, in out_format
    return try_printout(data, out, opts)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 46, in try_printout
    return get_printout(out, opts)(data).rstrip()
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 84, in output
    return _format_host(host, hostdata)[0]
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 117, in _format_host
    data = _strip_clean(data)
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 405, in _strip_clean
    if returns[tag]['result'] and not returns[tag]['changes']:
TypeError: string indices must be integers, not str

Unable to reach Sentry log server: The read operation timed out (url: https://sentry.logilab.fr/api/9/store/)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/raven/transport/threaded.py", line 159, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/usr/lib/python2.7/dist-packages/raven/transport/http.py", line 49, in send
    ca_certs=self.ca_certs,
  File "/usr/lib/python2.7/dist-packages/raven/utils/http.py", line 62, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/dist-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1187, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1051, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 371, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/ssl.py", line 341, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 260, in read
    return self._sslobj.read(len)
SSLError: The read operation timed out
suffix:
    progress
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: list indices must be integers, not str
Traceback (most recent call last):
  File "/usr/bin/salt-run", line 10, in <module>
    salt_run()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 250, in salt_run
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/run.py", line 54, in run
    runner.run()
  File "/usr/lib/python2.7/dist-packages/salt/runner.py", line 166, in run
    False)  # Don't daemonize
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 381, in _proc_function
    return self.low(fun, low)
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 327, in low
    namespaced_event.fire_event(data, 'ret')
  File "/usr/lib/python2.7/dist-packages/salt/utils/event.py", line 533, in fire_event
    self.print_func(tag, data)
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 452, in print_async_event
    salt.output.display_output(event_data, outputter, self.opts)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 94, in display_output
    display_data = try_printout(data, out, opts)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 46, in try_printout
    return get_printout(out, opts)(data).rstrip()
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 84, in output
    return _format_host(host, hostdata)[0]
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 136, in _format_host
    schanged, ctext = _format_changes(ret['changes'])
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 376, in _format_changes
    s, c = _format_host(host, hostdata)
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 117, in _format_host
    data = _strip_clean(data)
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 405, in _strip_clean
    if returns[tag]['result'] and not returns[tag]['changes']:
TypeError: list indices must be integers, not str
Traceback (most recent call last):
  File "/usr/bin/salt-run", line 10, in <module>
    salt_run()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 250, in salt_run
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/run.py", line 54, in run
    runner.run()
  File "/usr/lib/python2.7/dist-packages/salt/runner.py", line 166, in run
    False)  # Don't daemonize
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 381, in _proc_function
    return self.low(fun, low)
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 327, in low
    namespaced_event.fire_event(data, 'ret')
  File "/usr/lib/python2.7/dist-packages/salt/utils/event.py", line 533, in fire_event
    self.print_func(tag, data)
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 452, in print_async_event
    salt.output.display_output(event_data, outputter, self.opts)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 94, in display_output
    display_data = try_printout(data, out, opts)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 46, in try_printout
    return get_printout(out, opts)(data).rstrip()
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 84, in output
    return _format_host(host, hostdata)[0]
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 136, in _format_host
    schanged, ctext = _format_changes(ret['changes'])
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 376, in _format_changes
    s, c = _format_host(host, hostdata)
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 117, in _format_host
    data = _strip_clean(data)
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 405, in _strip_clean
    if returns[tag]['result'] and not returns[tag]['changes']:
TypeError: list indices must be integers, not str
Sentry is attempting to send 2 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
```

```
# salt --versions-report
                  Salt: 2015.5.0
                Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
 Debian source package: 2015.5.0+ds-1trusty1
```

**Comment by jfindlay** [comment]
@arthurlogilab, is it possible for you to share your `orchestration.logilabfr` state?
