### ISSUE TITLE
unit.modules.tls_test fails with older mock

### ISSUE THREAD

**Issue by terminalmage** [saltstack/salt#25323]
```
 -------------------------------------------------------------------------------
 --------  Tests with Errors  --------------------------------------------------
   -> unittest2.loader.ModuleImportFailure.unit.modules.tls_test  ..............
       ImportError: Failed to import test module: unit.modules.tls_test
       Traceback (most recent call last):
         File "/usr/lib/python2.6/site-packages/unittest2/loader.py", line 260, in _find_tests
           module = self._get_module_from_name(name)
         File "/usr/lib/python2.6/site-packages/unittest2/loader.py", line 238, in _get_module_from_name
           __import__(name)
         File "/builddir/build/BUILD/salt-2015.5.3/salt-2015.5.3/tests/unit/modules/tls_test.py", line 121, in <module>
           class TLSAddTestCase(TestCase):
         File "/builddir/build/BUILD/salt-2015.5.3/salt-2015.5.3/tests/unit/modules/tls_test.py", line 190, in TLSAddTestCase
           @patch('salt.utils.fopen', mock_open(read_data=_TLS_TEST_DATA['ca_cert']))
         File "/builddir/build/BUILD/salt-2015.5.3/SaltTesting-2015.5.8/salttesting/mock.py", line 143, in mock_open
           handle.__enter__.return_value = handle
       AttributeError: 'MagicMock' object has no attribute '__enter__'
   .............................................................................
 -------------------------------------------------------------------------------
```

**Comment by terminalmage** [comment]
This failed while attempting to run the tests to build for EPEL6.

**Comment by terminalmage** [comment]
The best solution here might be just to skip on older mock, using the new versioninfo tuple that I have proposed in https://github.com/saltstack/salt-testing/pull/42

**Comment by terminalmage** [comment]
Actually the fix needs to be in how we're patching mock_open. mock_open isn't available on older mock, and salttesting.mock simply uses a bare ``object()`` placeholder for it, which is what leads to this AttributeError.

By moving the patch of mock_open to inside the test instead of at the decorator level, this test is properly handled. It's actually skipped at the class level, but the skipIf stuff isn't processed until after the decorators run, and the error is occurring when one of the decorators is invoked.

I have a fix for this (and probably other tests) which I will submit later today.

**Comment by terminalmage** [comment]
I need to make a similar fix to other failing tests, but I haven't gotten around to it yet. I want to submit them all together, so I'll get to this sometime in the next couple days (I hope).

**Comment by terminalmage** [comment]
Fixed in https://github.com/saltstack/salt/pull/25604, closed.
