### ISSUE TITLE
msgpack failure

### ISSUE THREAD

**Issue by feus4177** [saltstack/salt#25333]
I recently came across this in one of my minion log files:

```
2015-07-08 14:45:55,350 [salt.payload     ][CRITICAL] Could not deserialize msgpack message: In an attempt to keep Salt running, returning an empty dict.This often happens when trying to read a file not in binary mode.Please open an issue and include the following error: Unpack failed: error = 0
```

The output of the minion versions report is:

```
           Salt: 2014.7.0
         Python: 2.7.3 (default, Mar 18 2014, 05:13:23)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 13.1.0
           RAET: Not Installed
            ZMQ: 3.2.3
           Mako: 0.7.0
```

I recently added this to my requirements.sls:

```
install_msgpack:
  cmd.run:
    - name: |
        wget http://msgpack.org/releases/cpp/msgpack-0.5.5.tar.gz
        tar zxf msgpack-0.5.5.tar.gz
        cd msgpack-0.5.5
        ./configure
        make
        make install
    - cwd: /tmp
    - unless: test -f /usr/local/include/msgpack.h
```

**Comment by jfindlay** [comment]
@feus4177, does this happen on 2015.5.2?  There have been very many changes since 2014.7.0 was released.

**Comment by feus4177** [comment]
I don't know. Is 2014.7.0 not supported anymore?

**Comment by feus4177** [comment]
I can't seem to reproduce it on either.

**Comment by jfindlay** [comment]
2014.7.0 isn't supported anymore.  If you are able to reproduce this on 2015.5.2 or later, post that info here, thanks.

**Comment by aaltemara** [comment]
I have seen this error, and I am running 215.5.2

[CRITICAL] Could not deserialize msgpack message: ��fun_args��20150719132221877305�jid�20150719132309922568�return��retcode�successãcmd�_return�_stamp�2015-07-19T17:23:10.128272�fun�saltutil.find_job�id�sanitizedminion1.domain.tld)�pid�=Σret��user�sudo_sanitizeduser1�arg��yum -y update --security�fun�cmd.run�retcode�successãcmd�_return�_stamp�2015-07-19T17:23:10.129310�fun�saltutil.find_job�id�sanitizedminion2.domain.tldThis often happens when trying to read a file not in binary mode.Please open an issue and include the following error: unpack(b) received extra data.
Exception occurred in runner jobs.list_jobs: Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/client/mixins.py", line 317, in low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/runners/jobs.py", line 211, in list_jobs
    ret = mminion.returners['{0}.get_jids'.format(returner)]()
  File "/usr/lib/python2.6/site-packages/salt/returners/local_cache.py", line 282, in get_jids
    for jid, job, _, _ in _walk_through(_job_dir()):
  File "/usr/lib/python2.6/site-packages/salt/returners/local_cache.py", line 67, in _walk_through
    job = serial.load(salt.utils.fopen(load_path, 'rb'))
  File "/usr/lib/python2.6/site-packages/salt/payload.py", line 114, in load
    return self.loads(data)
  File "/usr/lib/python2.6/site-packages/salt/payload.py", line 98, in loads
    return msgpack.loads(msg, use_list=True)
  File "msgpack/_unpacker.pyx", line 142, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:142)
ExtraData: unpack(b) received extra data.

**Comment by jfindlay** [comment]
@aaltemara, are you able to consistently reproduce it?  Is it possible for you to post your master config as well as the full output of `salt-run -l debug jobs.list_jobs`?
