### ISSUE TITLE
salt-cloud -u fails

### ISSUE THREAD

**Issue by hernanc** [saltstack/salt#25340]
Hi there,
Seems that there's an issue with the SSL certificate:

```bash
$ salt-cloud -u
[INFO    ] Starting new HTTPS connection (1): bootstrap.saltstack.com
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
SSLError: hostname 'bootstrap.saltstack.com' doesn't match either of '*.wpengine.com', 'wpengine.com'
Traceback (most recent call last):
  File "/usr/bin/salt-cloud", line 10, in <module>
    salt_cloud()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 316, in salt_cloud
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 78, in run
    ret = salt.utils.cloud.update_bootstrap(self.config)
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 2302, in update_bootstrap
    req = requests.get(url)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 385, in send
    raise SSLError(e)
SSLError: hostname 'bootstrap.saltstack.com' doesn't match either of '*.wpengine.com', 'wpengine.com'
Traceback (most recent call last):
  File "/usr/bin/salt-cloud", line 10, in <module>
    salt_cloud()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 316, in salt_cloud
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 78, in run
    ret = salt.utils.cloud.update_bootstrap(self.config)
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 2302, in update_bootstrap
    req = requests.get(url)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 385, in send
    raise SSLError(e)
requests.exceptions.SSLError: hostname 'bootstrap.saltstack.com' doesn't match either of '*.wpengine.com', 'wpengine.com'
```
```bash
$ salt --versions-report
                  Salt: 2015.5.2
                Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
 Debian source package: 2015.5.2+ds-1trusty1
```

Thanks!

**Comment by jfindlay** [comment]
@hernanc, thanks for the report.

**Comment by rallytime** [comment]
I think this is a duplicate of #24317

**Comment by hernanc** [comment]
Hey there, it's definitely the same issue. I'm closing this one and commenting on the other one
