### ISSUE TITLE
Loading YAML output format by PyYAML fails (may not conform to standard)

### ISSUE THREAD

**Issue by uvsmtid** [saltstack/salt#25356]
## Problem ##

YAML output is not immediately loadable by PyYAML parser - scripts reading it fail.

To be specific, let's take function `saltutil.sync_all` (however, any other function tried results in the same problem):
```
sudo salt-call saltutil.sync_all | tee output.yaml
```
`output.yaml` (copied & pasted):
```
local:
    ----------
    beacons:
    grains:
    modules:
    outputters:
    renderers:
    returners:
    states:
    utils:
```

It fails to be parsed (see below) due to multiple dashes `-`. Removing them (see below) fixes the problem.

Output validation by _some_ online YAML parsers ([here][2] and [here][3]) also fails. I'm not an expert in YAML syntax, but [this link to spec][1] is the only thing I found about multiple dashes. The spec only tells about three dashes `---`. And they start at zero indentation. 

It seems relevant to link JSON issue #25154 here as well.

## Test ##

`load_yaml.py`:
```
import sys
import yaml
data = yaml.load(sys.stdin)
print str(yaml)
```

Loading the output by PyYAML causes parsing problems:
```
cat output.yaml | python load_yaml.py
Traceback (most recent call last):
  File "load_yaml.py", line 3, in <module>
    data = yaml.load(sys.stdin)
  File "/usr/lib64/python2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/lib64/python2.7/site-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/usr/lib64/python2.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib64/python2.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib64/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib64/python2.7/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/lib64/python2.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib64/python2.7/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/usr/lib64/python2.7/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/lib64/python2.7/site-packages/yaml/scanner.py", line 220, in fetch_more_tokens
    return self.fetch_value()
  File "/usr/lib64/python2.7/site-packages/yaml/scanner.py", line 576, in fetch_value
    self.get_mark())
yaml.scanner.ScannerError: mapping values are not allowed here
  in "<stdin>", line 3, column 12

# FAILURE
```

`output.yaml` (modified with removed `----------`):
```
local:
    beacons:
    grains:
    modules:
    outputters:
    renderers:
    returners:
    states:
    utils:
```

```
cat output.yaml | python load_yaml.py
<module 'yaml' from '/usr/lib64/python2.7/site-packages/yaml/__init__.pyc'>

# SUSSESS
```

## Versions ##

```
 salt-call --versions
           Salt: 2015.5.2
         Python: 2.7.10 (default, May 27 2015, 18:11:38)
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.4.1
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: 1.0.1
```

```
rpm -qi PyYAML                                                                                                                                                                                                    
Name        : PyYAML
Version     : 3.11
Release     : 7.fc22
Architecture: x86_64
Install Date: Sat 06 Jun 2015 10:12:00 PM SGT
Group       : Development/Libraries
Size        : 628411
License     : MIT
Signature   : RSA/SHA256, Sun 05 Apr 2015 11:05:44 PM SGT, Key ID 11adc0948e1431d5
Source RPM  : PyYAML-3.11-7.fc22.src.rpm
Build Date  : Tue 24 Mar 2015 01:26:05 AM SGT
Build Host  : buildhw-03.phx2.fedoraproject.org
...
```

[1]: http://www.yaml.org/spec/1.2/spec.html#id2760395
[2]: http://www.yamllint.com/
[3]: http://yaml-online-parser.appspot.com/

**Comment by s0undt3ch** [comment]
Please try appending `--out=yaml` to your `salt-call` command.

**Comment by uvsmtid** [comment]
@s0undt3ch, thank you for prompt reply!

Indeed, option `--out=yaml` solves the problem:
```
sudo salt-call --out=yaml saltutil.sync_all | tee output.yaml
...
local:
  beacons: []
  grains: []
  modules: []
  outputters: []
  renderers: []
  returners: []
  states: []
  utils: []
```
I always mistakenly assumed default `--out` is `yaml`.

**Comment by jfindlay** [comment]
@uvsmtid, do you consider `--out=yaml` to resolve your issues?

**Comment by uvsmtid** [comment]
Yes. It solves it.

Apparently, the default output is something which only looks like YAML from the first glance ([from the docs I tried some] and I guess guess it's `highstate`).

The issue is closed at least from my side.

[1]: http://docs.saltstack.com/en/latest/ref/cli/salt-call.html#output-options

**Comment by jfindlay** [comment]
Thanks, @uvsmtid.
