### ISSUE TITLE
error when trying to use associate_eip

### ISSUE THREAD

**Issue by kushniro** [saltstack/salt#25367]
Hey, i've been trying to associate and aws elastic ip to and instance i'm creating and I keep getting the following error: TypeError: string indices must be integers, not str

added the version-report output and the debug output of the salt-cloud that ends with the error

``` yaml
Salt: 2015.5.0
         Python: 2.7.6 (default, Sep  9 2014, 15:04:36)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
```

```
[DEBUG   ] Using AWS endpoint: ec2.eu-west-1.amazonaws.com
[DEBUG   ] AWS Request: https://ec2.eu-west-1.amazonaws.com/?Action=DescribeSubnets&Version=2014-10-01

[DEBUG   ] AWS Response Status Code: 200
[ERROR   ] There was a query error: string indices must be integers, not str
Traceback (most recent call last):
  File "/usr/local/Cellar/saltstack/2015.5.0/libexec/lib/python2.7/site-packages/salt/cloud/cli.py", line 316, in run
    ret = mapper.run_map(dmap)
  File "/usr/local/Cellar/saltstack/2015.5.0/libexec/lib/python2.7/site-packages/salt/cloud/__init__.py", line 2007, in run_map
    out = self.create(master_profile, local_master=local_master)
  File "/usr/local/Cellar/saltstack/2015.5.0/libexec/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1241, in create
    output = self.clouds[func](vm_)
  File "/usr/local/Cellar/saltstack/2015.5.0/libexec/lib/python2.7/site-packages/salt/cloud/clouds/ec2.py", line 2116, in create
    data, vm_ = request_instance(vm_, location)
  File "/usr/local/Cellar/saltstack/2015.5.0/libexec/lib/python2.7/site-packages/salt/cloud/clouds/ec2.py", line 1507, in request_instance
    _new_eni = _create_eni(interface)
  File "/usr/local/Cellar/saltstack/2015.5.0/libexec/lib/python2.7/site-packages/salt/cloud/clouds/ec2.py", line 1115, in _create_eni
    if subnet['subnetId'] == interface['SubnetId']:
TypeError: string indices must be integers, not str
```

**Comment by jfindlay** [comment]
@kushniro, thanks for the report.  Is it possible for you to post the salt-cloud command you're using?

**Comment by kushniro** [comment]
sorry for the late reply, I think it was just salt-cloud -m /path/to/mapfile.

**Comment by jfindlay** [comment]
@kushniro, no problem.  What does your cloud map look like?  Also, have you tried 2015.5.2 or 2015.5.3?  There have been several cloud fixes that might have fixed this.  Thanks.
