### ISSUE TITLE
sysrc exec and state module broken in 2015.5.2

### ISSUE THREAD

**Issue by 0xf10e** [saltstack/salt#25405]
Hi,

seems like the `sysrc` exec-module is somewhat broken:

```
root@master:/srv/salt/iscsi-formula.git# salt freebsd-minion sysrc.get iscsid_flags
freebsd-minion:
    TypeError encountered executing sysrc.get: get() takes exactly 0 arguments (8 given). See debug log for more info.
root@master:/srv/salt/iscsi-formula.git# 
root@master:/srv/salt/iscsi-formula.git# salt freebsd-minion sysrc.get iscsictl_flags
freebsd-minion:
    TypeError encountered executing sysrc.get: get() takes exactly 0 arguments (8 given). See debug log for more info.
root@master:/srv/salt/iscsi-formula.git# salt freebsd-minion sysrc.get iscsid_enable 
freebsd-minion:
    TypeError encountered executing sysrc.get: get() takes exactly 0 arguments (8 given). See debug log for more info.
```

The state-function `sysrc.managed` works, but `sysrc.absent` causes errors, too:

```
root@master:/srv/salt/iscsi-formula.git# salt freebsd-minion state.sls iscsi.initiator   
freebsd-minion:
----------
          ID: /etc/iscsi.conf
    Function: file.managed
      Result: True
     Comment: File /etc/iscsi.conf is in the correct state
     Started: 17:09:15.107720
    Duration: 10.201 ms
     Changes:   
----------
          ID: iscsictl_flags
    Function: sysrc.absent
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/local/lib/python2.7/site-packages/salt/state.py", line 1563, in call
                  **cdata['kwargs'])
                File "/usr/local/lib/python2.7/site-packages/salt/states/sysrc.py", line 78, in absent
                  current_state = __salt__['sysrc.get'](name=name, **kwargs)
                File "/usr/local/lib/python2.7/site-packages/salt/modules/sysrc.py", line 65, in get
                  val = sysrc.split(': ')[2]
              IndexError: list index out of range
     Started: 17:09:15.122212
    Duration: 308.268 ms
     Changes:   
----------
[...]
```

Master on CentOS 6:

```
root@master:/srv/salt/iscsi-formula.git# salt-master --versions-report
           Salt: 2015.5.2
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
```

Minion on FreeBSD 10.1-RELEASE-p14:

```
admin@freebsd-minion:~% salt-minion --versions-report
           Salt: 2015.5.2
         Python: 2.7.10 (default, Jul  5 2015, 01:15:55)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.6.0
           RAET: Not Installed
            ZMQ: 4.1.2
           Mako: Not Installed
```

**Comment by 0xf10e** [comment]
Stumbled over those bugs while testing my [iscsi-formula](https://github.com/0xf10e/iscsi-formula) for FreeBSD.

**Comment by jfindlay** [comment]
@0xf10e, thanks for the report.

@cedwards, @kim0

**Comment by cedwards** [comment]
Is this still an issue in the latest release? I haven't had a chance to look at this on my system yet..

**Comment by 0xf10e** [comment]
Me neither but I can give it a try later.

**Comment by 0xf10e** [comment]
The problem is an option set to an empty string.

With `iscsictl_flags=""` commented out in `/etc/rc.conf` thus falling back to the 
non-empty default:
```
user@freebsd10:~% grep iscsi /etc/rc.conf /etc/defaults/rc.conf 
/etc/rc.conf:iscsid_enable="YES"
/etc/rc.conf:#iscsictl_flags=""
/etc/defaults/rc.conf:iscsid_enable="NO"                # iSCSI initiator daemon.
/etc/defaults/rc.conf:iscsictl_enable="NO"              # iSCSI initiator autostart.
/etc/defaults/rc.conf:iscsictl_flags="-Aa"              # Optional flags to iscsictl.
```
My test-state works:
```
root@master/srv/salt/base.hg# cat iscsi_absent.sls 
iscsictl_flags:
    sysrc:
        - absent

root@master:/srv/salt/base.hg# salt myrrh state.sls iscsi_absent
freebsd10:
----------
          ID: iscsictl_flags
    Function: sysrc.absent
      Result: True
     Comment: "iscsictl_flags" was removed!
     Started: 14:39:23.113786
    Duration: 610.094 ms
     Changes:   
              ----------
              new:
                  iscsictl_flags removed
              old:
                  ----------
                  /etc/defaults/rc.conf:
                      ----------
                      iscsictl_flags:
                          -Aa

Summary
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
```

But with `iscsictl_flags=""`...:
```
user@freebsd10:~% grep iscsi /etc/rc.conf
/etc/rc.conf:iscsid_enable="YES"
/etc/rc.conf:iscsictl_flags=""
```
...the state fails:
```
user@master:/srv/salt/base.hg# salt myrrh state.sls iscsi_absent
freebsd10:
----------
          ID: iscsictl_flags
    Function: sysrc.absent
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/local/lib/python2.7/site-packages/salt/state.py", line 1560, in call
                  **cdata['kwargs'])
                File "/usr/local/lib/python2.7/site-packages/salt/states/sysrc.py", line 78, in absent
                  current_state = __salt__['sysrc.get'](name=name, **kwargs)
                File "/usr/local/lib/python2.7/site-packages/salt/modules/sysrc.py", line 65, in get
                  val = sysrc.split(': ')[2]
              IndexError: list index out of range
     Started: 14:45:02.886894
    Duration: 308.805 ms
     Changes:   

Summary
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
```

Complete `sysrc.get`
```
root@agatha:/srv/salt/base.hg# salt myrrh sysrc.get          
myrrh:
    ----------
    /etc/rc.conf:
        ----------
        cloned_interfaces:
            vlanXXX
        defaultrouter:
            10.xxx.zzz.1
        dumpdev:
            AUTO
        hostname:
            myrrh.fokus.fraunhofer.de
        ifconfig_bge0:
            inet 10.xxx.yyy.zzz netmask 255.255.255.0
        ifconfig_bge0_ipv6:
            inet6 200x:yyyy:yyyy::zzzz prefixlen 64
        ifconfig_bge1:
            up
        ifconfig_vlan341:
            vlan XXX vlandev bge1 up
        iocage_enable:
            YES
        iscsictl_flags:
        iscsid_enable:
            YES
        keymap:
            german.iso.acc.kbd
        ntpd_enable:
            YES
        powerd_enable:
            YES
        rtsold_enable:
            YES
        salt_minion_enable:
            YES
        sshd_enable:
            YES
        zabbix_agentd_enable:
            YES
        zfs_enable:
            YES
```
