### ISSUE TITLE
Stacktrace on Windows when running pkg.list_pkgs

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt#25437]
Getting a stacktrace on Windows with salt v2015.5.3 when running `salt-call.bat --local pkg.list_pkgs`.

```
PS C:\salt> .\salt-call.bat --local pkg.list_pkgs --log-level debug
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Using cached minion ID from c:\salt\conf\minion_id: PEARL
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded pkg.list_pkgs
[DEBUG   ] LazyLoaded cp.is_cached
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init
[DEBUG   ] Updating roots fileserver cache
[DEBUG   ] Could not find file from saltenv 'base', 'salt://win/repo/winrepo.p'
[ERROR   ] Unable to cache file 'salt://win/repo/winrepo.p' from saltenv 'base'.
[ERROR   ] Not able to read repo file
[ERROR   ] [Errno 22] invalid mode ('rb') or filename: ''
Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 624, in get_repo_data
    with salt.utils.fopen(cached_repo, 'rb') as repofile:
  File "C:\salt\bin\lib\site-packages\salt\utils\__init__.py", line 1045, in fopen
    fhandle = open(*args, **kwargs)
IOError: [Errno 22] invalid mode ('rb') or filename: ''
[DEBUG   ] LazyLoaded pkg_resource.add_pkg
[DEBUG   ] LazyLoaded nested.output
local:
    ----------
<...snip.../>
```

versions-report:
```
PS C:\salt> .\salt-call.bat --versions-report
           Salt: 2015.5.3
         Python: 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.5
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.6.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
        Tornado: Not Installed
```

**Comment by jfindlay** [comment]
@lorengordon, thanks for the report.

**Comment by lorengordon** [comment]
Nice, thanks!

**Comment by twangboy** [comment]
@UtahDave This ticket disappears entirely from the sprint when you close it
