### ISSUE TITLE
[2015.8.0rc1] salt-bootstrap fails to install salt master

### ISSUE THREAD

**Issue by julienlavergne** [saltstack/salt#25456]
Here the following command used: 

    curl -s -L https://bootstrap.saltstack.com | sudo sh -s -- -U -P -p python-jinja2 -A master git v2015.8.0rc1

The output about the error:

salt-minion start/running, process 24308
 *  INFO: Running daemons_running()
 * ERROR: salt-minion was not found running
 * ERROR: Failed to run daemons_running()!!!
 * ERROR: salt-minion was not found running.

Any idea? 

Maybe a link with this issue: https://github.com/saltstack/salt/issues/25270

**Comment by tbaker57** [comment]
Not sure if this is the same issue, but I'm also having trouble installing a salt-master for 2015.8 rc1 using salt-bootstrap.
```
sh install_salt.sh -M -g https://github.com/saltstack/salt.git git v2015.8.0rc1
```
Output
```
...
 *  INFO: Running install_centos_restart_daemons()
Starting salt-minion daemon:                               [  OK  ]
Starting salt-master daemon: Traceback (most recent call last):
  File "/usr/bin/salt-master", line 22, in <module>
    salt_master()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 47, in salt_master
    master.start()
  File "/usr/lib/python2.6/site-packages/salt/cli/daemons.py", line 150, in start
    self.prepare()
  File "/usr/lib/python2.6/site-packages/salt/cli/daemons.py", line 131, in prepare
    self.master = salt.master.Master(self.config)
  File "/usr/lib/python2.6/site-packages/salt/master.py", line 326, in __init__
    SMaster.__init__(self, opts)
  File "/usr/lib/python2.6/site-packages/salt/master.py", line 100, in __init__
    self.master_key = salt.crypt.MasterKeys(self.opts)
  File "/usr/lib/python2.6/site-packages/salt/crypt.py", line 205, in __init__
    self.key = self.__get_keys()
  File "/usr/lib/python2.6/site-packages/salt/crypt.py", line 256, in __get_keys
    key = RSA.importKey(f.read())
NameError: global name 'RSA' is not defined
```
M2Crypto is definitely installed
```
[root@dev ~]# salt --versions-report
Salt Version:
           Salt: 2015.8.0rc1
 
Dependency Versions:
         Jinja2: unknown
       M2Crypto: 0.20.2
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
           RAET: Not Installed
        Tornado: 4.1
            ZMQ: 3.2.5
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
       pycrypto: 2.0.1
 
System Versions:
           dist: centos 6.6 Final
        machine: x86_64
        release: 2.6.32-504.23.4.el6.x86_64
         system: CentOS 6.6 Final

```

**Comment by tbaker57** [comment]
Forgot to add - the same bootstrap command above works fine using the 2015.5.3 tag.

Cheers
Tim

**Comment by s0undt3ch** [comment]
@tbaker57 that seems like a different issue, maybe a not recent enough PyCrypto. Could you please open another issue for that?

**Comment by jfindlay** [comment]
Duplicate of #25270.
