### ISSUE TITLE
Regression: salt 2015.5 not working in secure chroot anymore.

### ISSUE THREAD

**Issue by mschiff** [saltstack/salt#25454]
I *assume* that this regression was introduced with 2015.5.0. I noticed this when upgrading from 2014.7.5 to 2015.5.2

With 2014.7.5 this is working without any problems. (so I had to downgrade to make it work again)

This is a system with a hardened grsecurity kernel that hides any processes inside chroot environments that are not running inside the chroot...

```
(build)admin ~ # salt-call state.sls portage
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
IOError: [Errno 2] No such file or directory: '/proc/1/cmdline'
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib64/python2.7/site-packages/salt/scripts.py", line 227, in salt_call
    client.run()
  File "/usr/lib64/python2.7/site-packages/salt/cli/call.py", line 59, in run
    caller = salt.cli.caller.Caller.factory(self.config)
  File "/usr/lib64/python2.7/site-packages/salt/cli/caller.py", line 69, in factory
    return ZeroMQCaller(opts, **kwargs)
  File "/usr/lib64/python2.7/site-packages/salt/cli/caller.py", line 92, in __init__
    self.minion = salt.minion.SMinion(opts)
  File "/usr/lib64/python2.7/site-packages/salt/minion.py", line 298, in __init__
    opts['grains'] = salt.loader.grains(opts)
  File "/usr/lib64/python2.7/site-packages/salt/loader.py", line 514, in grains
    ret = fun()
  File "/usr/lib64/python2.7/site-packages/salt/grains/core.py", line 1042, in os_data
    with salt.utils.fopen('/proc/1/cmdline') as fhr:
  File "/usr/lib64/python2.7/site-packages/salt/utils/__init__.py", line 1045, in fopen
    fhandle = open(*args, **kwargs)
IOError: [Errno 2] No such file or directory: '/proc/1/cmdline'
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib64/python2.7/site-packages/salt/scripts.py", line 227, in salt_call
    client.run()
  File "/usr/lib64/python2.7/site-packages/salt/cli/call.py", line 59, in run
    caller = salt.cli.caller.Caller.factory(self.config)
  File "/usr/lib64/python2.7/site-packages/salt/cli/caller.py", line 69, in factory
    return ZeroMQCaller(opts, **kwargs)
  File "/usr/lib64/python2.7/site-packages/salt/cli/caller.py", line 92, in __init__
    self.minion = salt.minion.SMinion(opts)
  File "/usr/lib64/python2.7/site-packages/salt/minion.py", line 298, in __init__
    opts['grains'] = salt.loader.grains(opts)
  File "/usr/lib64/python2.7/site-packages/salt/loader.py", line 514, in grains
    ret = fun()
  File "/usr/lib64/python2.7/site-packages/salt/grains/core.py", line 1042, in os_data
    with salt.utils.fopen('/proc/1/cmdline') as fhr:
  File "/usr/lib64/python2.7/site-packages/salt/utils/__init__.py", line 1045, in fopen
    fhandle = open(*args, **kwargs)
IOError: [Errno 2] No such file or directory: '/proc/1/cmdline'
```

**Comment by jfindlay** [comment]
@mschiff, thanks for the report.  I see it as happening after 2015.5.2 and before 2015.5.3 (`git describe f3534543 --> v2015.5.2-225-gf353454`), but whatever.
