### ISSUE TITLE
2015.8 - Azure add endpoint not working anymore: TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by lichtamberg** [saltstack/salt#25463]
Tried to add an endpoint, worked before (but also doesnt work anymore in 2015.5? did azure api change maybe?):

```
# salt-cloud -f add_input_endpoint az-mysetup name=http    port=80    protocol=tcp deployment=myproject service=myproject role=myproject

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/salt/cloud/cli.py", line 245, in run
    self.function_provider, self.function_name, kwargs
  File "/usr/local/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1525, in do_function
    call='function', kwargs=kwargs
  File "/usr/local/lib/python2.7/site-packages/salt/cloud/clouds/msazure.py", line 2190, in add_input_endpoint
    activity='add',
  File "/usr/local/lib/python2.7/site-packages/salt/cloud/clouds/msazure.py", line 2109, in update_input_endpoint
    old_endpoints = list_input_endpoints(kwargs, call='function')
  File "/usr/local/lib/python2.7/site-packages/salt/cloud/clouds/msazure.py", line 2013, in list_input_endpoints
    for item in data:
TypeError: 'NoneType' object is not iterable
```

```
salt-ssh --versions-report
Salt Version:
           Salt: 2015.5.0-1767-gba4877d

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.22
           Mako: 1.0.1
         PyYAML: 3.11
          PyZMQ: 14.6.0
         Python: 2.7.9 (default, Jan  7 2015, 11:50:42)
           RAET: Not Installed
        Tornado: 4.1
            ZMQ: 4.0.5
          ioflo: 1.2.1
        libnacl: Not Installed
   msgpack-pure: 0.1.3
 msgpack-python: 0.4.6
       pycrypto: 2.6.1

System Versions:
           dist:
        machine: x86_64
        release: 13.4.0
         system: 10.9.5 -- x86_64
```

**Comment by jfindlay** [comment]
@lichtamberg, based on the salt version reported it seems that you are running an old version of develop.  Is it possible for you to try again with 2015.5.3, 2015.8.0rc1 or the heads of those branches or even develop?  Thanks.

**Comment by lichtamberg** [comment]
```
Salt Version:
           Salt: 2015.8.0rc1-44-gcef7461

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.22
           Mako: 1.0.1
         PyYAML: 3.11
          PyZMQ: 14.6.0
         Python: 2.7.9 (default, Jan  7 2015, 11:50:42)
           RAET: Not Installed
        Tornado: 4.1
            ZMQ: 4.0.5
          ioflo: 1.2.1
        libnacl: Not Installed
   msgpack-pure: 0.1.3
 msgpack-python: 0.4.6
       pycrypto: 2.6.1

System Versions:
           dist:
        machine: x86_64
        release: 13.4.0
         system: 10.9.5 -- x86_64
```
Different line numbers, but same error:

```
[ERROR   ] There was an error running the function: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/salt/cloud/cli.py", line 245, in run
    self.function_provider, self.function_name, kwargs
  File "/usr/local/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1525, in do_function
    call='function', kwargs=kwargs
  File "/usr/local/lib/python2.7/site-packages/salt/cloud/clouds/msazure.py", line 2193, in add_input_endpoint
    activity='add',
  File "/usr/local/lib/python2.7/site-packages/salt/cloud/clouds/msazure.py", line 2112, in update_input_endpoint
    old_endpoints = list_input_endpoints(kwargs, call='function')
  File "/usr/local/lib/python2.7/site-packages/salt/cloud/clouds/msazure.py", line 2016, in list_input_endpoints
    for item in data:
TypeError: 'NoneType' object is not iterable
```

**Comment by jfindlay** [comment]
Thanks, @lichtamberg.

**Comment by lichtamberg** [comment]
Found the issue...

Was a mistake of mine, I sent the andpoint call to the wrong account on azure (which didnt has this service/server running)... Maybe there should be a better error message...

**Comment by rallytime** [comment]
@lichtamberg Another thing I just noticed when looking into this bug is that the `add_input_endpoint` function was added in 2015.8.0, so it is not available in the 2015.5.x releases. Just a note incase other people come across this in the future.

**Comment by rallytime** [comment]
@lichtamberg Also, I've fixed the stacktrace above by providing a more helpful error:
```
There was an error connecting to the Azure API. Check your credentials.
```
Sound good?

**Comment by lichtamberg** [comment]
Hey @rallytime ,

thanks for your response.. This error message seems much better, but: it would have been missleading for me... My problem was not, that my credentials were wrong... They were ok, but I just mixed up, that under this credentials there was no server running with the name "xyz"...

So the error message should be something like: "No server xyz found with this credentials" (if the credentials are correct)..

Thanks!

**Comment by rallytime** [comment]
@lichtamberg Ok, I'll see if I can be a little more specific. The problem is that the stacktrace occurs because the query to the Azure API is returning `None`, so I was purposefully trying to not be too specific since you could potentially hit that error many different ways, not just the way you're hitting it. I'll see if I can narrow it down tomorrow.

**Comment by rallytime** [comment]
@lichtamberg You're right - this error could be much more friendly. I've changed it to:
```
There was an error listing endpoints with the <abc-service> service on the <xyz-deployment> deployment.
```
Which will be both broad and more helpful/accurate than my first message.

**Comment by lichtamberg** [comment]
@rallytime thank you very much!

**Comment by rallytime** [comment]
No problem! Thanks for the feedback! :)
