### ISSUE TITLE
S3 ext_pillar configuration requires verify_ssl

### ISSUE THREAD

**Issue by stanislavb** [saltstack/salt#25538]
The documentation states that "The verify_ssl parameter defaults to True" but that is not the case.

I switched to using S3 as backend but something was missing. This was the relevant bit of my master conf:
```
ext_pillar:
  - s3:
      bucket: bucketname
      keyid: <redacted>
      key: <redacted>
```
```
# salt --versions-report
           Salt: 2015.5.2
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
```
Master log file:
```
[INFO    ] AES payload received with command _pillar
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded s3.ext_pillar
[ERROR   ] Failed to load ext_pillar s3: ext_pillar() takes at least 6 non-keyword arguments (5 given)
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/pillar/__init__.py", line 534, in ext_pillar
    key)
  File "/usr/lib/python2.6/site-packages/salt/pillar/__init__.py", line 493, in _external_pillar_data
    ext = self.ext_pillars[key](self.opts['id'], pillar, **val)
TypeError: ext_pillar() takes at least 6 non-keyword arguments (5 given)
```

## Fix
All was well as soon as I added `verify_ssl: True` to s3 ext_pillar configuration

**Comment by jfindlay** [comment]
@stanislavb, thanks for the report.  I have created a fix for this.
