### ISSUE TITLE
TypeError: run() takes at least 1 argument (2 given)

### ISSUE THREAD

**Issue by yellow1912** [saltstack/salt#25602]
The error itself is weird enough, if it takes at least 1 arg then why can't I give it more than 1?

Anyhow, below is the brief info of my current setup:
Salt version: 2015.5.0

``` bash
salt --versions-report
                  Salt: 2015.5.0
                Python: 2.7.9 (default, Apr  2 2015, 15:33:21)
                Jinja2: 2.7.3
              M2Crypto: 0.21.1
        msgpack-python: 0.4.2
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.11
                 ioflo: Not Installed
                 PyZMQ: 14.4.1
                  RAET: Not Installed
                   ZMQ: 4.0.5
                  Mako: Not Installed

```

schedule.sls in srv/salt (which is then included in top file)

``` yaml
job2:
    schedule.present:
      - function: cmd.run
      - seconds: 120
      - splay: 10
      - job_kwargs:
          name: 'composer update -o'
          cwd: '/project/source/development'
          env: '{"HOME": "/root"}'

```

Error I get:

``` bash
2015-07-22 01:34:39,842 [salt.utils.schedule][ERROR   ][10090] Unhandled exception running cmd.run
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/schedule.py", line 542, in handle_func
    ret['return'] = self.functions[func](*args, **kwargs)
TypeError: run() takes at least 1 argument (2 given)
2015-07-22 01:36:43,076 [salt.utils.schedule][ERROR   ][13269] Unhandled exception running cmd.run
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/schedule.py", line 542, in handle_func
    ret['return'] = self.functions[func](*args, **kwargs)
TypeError: run() takes at least 1 argument (2 given)

```

**Comment by jfindlay** [comment]
I think that the problem is that the `name` parameter needs to be an `arg` rather than a `kwarg`.  The first argument to `cmd.run` is actually `cmd` rather than `name` anyway, but that's not relevant.  The error message comes from python itself, for example:
```python
>>> def f(a, b=None, c=None):
...  pass
... 
>>> f(b=1, c=2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: f() takes at least 1 argument (2 given)
```

You should be able to get this to work:
```yaml
job2:
  schedule.present:
    - function: cmd.run
    - seconds: 120
    - splay: 10
    - job_args:
      - 'composer update -o'
    - job_kwargs:
      cwd: '/project/source/development'
      env: '{"HOME": "/root"}'
```

**Comment by yellow1912** [comment]
are you sure the cwd and env should be on the same level with job_kwargs? I think they should be indented 1 level?

Anyhow,  
1. I tried your setting but they kwargs were not included in the final cmd running, when I use schedule.list I get

``` bash
 job2:
        args:
        - composer update -o
        function: cmd.run
        jid_include: true
        kwargs: null
        maxrunning: 1
        name: job2
        seconds: 120
        splay: 10

```

2. I tried to indent cwd and env 1 level and I get

``` bash
update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [packages1] ... [packagesN]
2015-07-23 01:38:42,205 [salt.loaded.int.module.cmdmod][ERROR   ][29297] Command 'composer update -o' failed with return code: 1
2015-07-23 01:38:42,207 [salt.loaded.int.module.cmdmod][ERROR   ][29297] output:


  [RuntimeException]
  The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly
```

As you can see, cwd and env were supposed to be in the command but they are not resulting in composer complaining about missing HOME env.

**Comment by jfindlay** [comment]
@yellow1912, yes sorry, that was a typo.

Here are some additional things to try:
```yaml
job2:
  schedule.present:
    - function: cmd.run
    - seconds: 120
    - splay: 10
    - job_args:
      - 'composer update -o'
    - job_kwargs:
        cwd: '/project/source/development'
        env: 
          HOME: /root
```
```yaml
job2:
  schedule.present:
    - function: cmd.run
    - seconds: 120
    - splay: 10
    - job_args:
      - 'HOME=/root composer update -o'
    - job_kwargs:
        cwd: '/project/source/development'
```
