### ISSUE TITLE
 provider = entry['provider']  TypeError: string indices must be integers, not str

### ISSUE THREAD

**Issue by davidanands** [saltstack/salt#25607]
Hi,

Salt cloud provisioning bug.
```
]#  salt-cloud -p sharedfarm_stag vm-all-all-autodeploy3 -l debug
[DEBUG   ] Reading configuration from /etc/salt/cloud
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: vm-dsu-salt-master
[DEBUG   ] Missing configuration file: /etc/salt/cloud.providers
[DEBUG   ] Including configuration from '/etc/salt/cloud.providers.d/rs.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers.d/rs.conf
[ERROR   ] string indices must be integers, not str
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/utils/parsers.py", line 155, in parse_args
    process_option_func()
  File "/usr/lib/python2.6/site-packages/salt/utils/parsers.py", line 435, in process_config_dir
    self.config.update(self.setup_config())
  File "/usr/lib/python2.6/site-packages/salt/utils/parsers.py", line 2493, in setup_config
    return config.cloud_config(self.get_config_file_path())
  File "/usr/lib/python2.6/site-packages/salt/config.py", line 1261, in cloud_config
    providers_config = cloud_providers_config(providers_config_path)
  File "/usr/lib/python2.6/site-packages/salt/config.py", line 1544, in cloud_providers_config
    return apply_cloud_providers_config(overrides, defaults)
  File "/usr/lib/python2.6/site-packages/salt/config.py", line 1617, in apply_cloud_providers_config
    provider = entry['provider']
TypeError: string indices must be integers, not str
Usage: salt-cloud

salt-cloud: error: Error while processing <bound method SaltCloud.process_config_dir of <salt.cloud.cli.SaltCloud object at 0x1ce8b50>>: Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/utils/parsers.py", line 155, in parse_args
    process_option_func()
  File "/usr/lib/python2.6/site-packages/salt/utils/parsers.py", line 435, in process_config_dir
    self.config.update(self.setup_config())
  File "/usr/lib/python2.6/site-packages/salt/utils/parsers.py", line 2493, in setup_config
    return config.cloud_config(self.get_config_file_path())
  File "/usr/lib/python2.6/site-packages/salt/config.py", line 1261, in cloud_config
    providers_config = cloud_providers_config(providers_config_path)
  File "/usr/lib/python2.6/site-packages/salt/config.py", line 1544, in cloud_providers_config
    return apply_cloud_providers_config(overrides, defaults)
  File "/usr/lib/python2.6/site-packages/salt/config.py", line 1617, in apply_cloud_providers_config
    provider = entry['provider']
TypeError: string indices must be integers, not str
```
```
[root@vm-dsu-salt-master ~]# salt-cloud  --versions-report
            Salt: 2015.5.2
          Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
          Jinja2: 2.2.1
        M2Crypto: 0.20.2
  msgpack-python: 0.4.6
    msgpack-pure: Not Installed
        pycrypto: 2.0.1
         libnacl: Not Installed
          PyYAML: 3.10
           ioflo: Not Installed
           PyZMQ: 14.3.1
            RAET: Not Installed
             ZMQ: 3.2.5
            Mako: Not Installed
 Apache Libcloud: 0.17.0
```

**Comment by jfindlay** [comment]
@davidanands, thanks for the report.  Is it possible for you to share your `sharedfarm_stag` cloud profile, with any auths redacted?

**Comment by davidanands** [comment]
Hi,
Please find the below  

/etc/salt/cloud.profiles.d/rs.conf
sharedfarm_stag:
  provider:rs
  image:CentOS 6(PVHVM)
  size:4 GB General Purpose v1



/etc/salt/cloud.providers.d/rs.conf
rs:
  compute_region:LON
minion:
   master:10.XX.XX.XX
  identity_url:'https://identity.api.rackspacecloud.com/v2.0/tokens'
  compute_name:cloudServersOpenStack
  protocol:ipv4
  user:XXXXXX
  tenant:XXXXx
  apikey:XXXXX
  provider:openstack

**Comment by jfindlay** [comment]
I'm not sure if this is related, but your yaml needs to have spaces after the colons.  yamllint.com renders the profile conf as this, for example:
```yaml
--- 
sharedfarm_stag: "provider:rs image:CentOS 6(PVHVM) size:4 GB General Purpose v1"
```

**Comment by davidanands** [comment]
Hi @jfindlay 

I corrected as per your instruction, but it has the same error.

**Comment by jfindlay** [comment]
@davidanands, you also need to fix the indentation in your providers file,
```yaml
rs:
  compute_region: LON
  minion:
    master: 10.XX.XX.XX
  identity_url: 'https: //identity.api.rackspacecloud.com/v2.0/tokens'
  compute_name: cloudServersOpenStack
  protocol: ipv4
  user: XXXXXX
  tenant: XXXXx
  apikey: XXXXX
  provider: openstack
```
making sure that each indentation is two spaces.

**Comment by davidanands** [comment]
@jfindlay thanks for the supprort .. all worked as charm !

**Comment by davidanands** [comment]
@jfindlay I am hitting some other error now

#  salt-cloud -l debug -p sharedfarm_test vm-all-all-autodeploy3
[DEBUG   ] Reading configuration from /etc/salt/cloud
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: vm-dsu-salt-master
[DEBUG   ] Missing configuration file: /etc/salt/cloud.providers
[DEBUG   ] Including configuration from '/etc/salt/cloud.providers.d/rs.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers.d/rs.conf
[DEBUG   ] Missing configuration file: /etc/salt/cloud.profiles
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/rs.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/rs.conf
[DEBUG   ] Configuration file path: /etc/salt/cloud
[INFO    ] salt-cloud starting
[ERROR   ] Failed to import clouds nova, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/loader.py", line 957, in _load_module
    ), fn_, fpath, desc)
  File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/nova.py", line 112, in <module>
    from salt.utils.openstack import nova
  File "/usr/lib/python2.6/site-packages/salt/utils/openstack/nova.py", line 10, in <module>
    from novaclient.v1_1 import client
  File "/usr/lib/python2.6/site-packages/novaclient/__init__.py", line 18, in <module>
    __version__ = pbr.version.VersionInfo('python-novaclient').version_string()
  File "/usr/lib/python2.6/site-packages/pbr/version.py", line 457, in version_string
    return self.semantic_version().brief_string()
  File "/usr/lib/python2.6/site-packages/pbr/version.py", line 452, in semantic_version
    self._semantic = self._get_version_from_pkg_resources()
  File "/usr/lib/python2.6/site-packages/pbr/version.py", line 439, in _get_version_from_pkg_resources
    result_string = packaging.get_version(self.package)
  File "/usr/lib/python2.6/site-packages/pbr/packaging.py", line 582, in get_version
    raise Exception("Versioning for this project requires either an sdist"
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. Are you sure that git is installed?
/usr/lib/python2.6/site-packages/salt/cloud/clouds/digital_ocean.py:86: DeprecationWarning: The digital_ocean driver is deprecated and will be removed in Salt Beryllium. Please convert your digital ocean provider configs to use the digital_ocean_v2 driver.[DEBUG   ] Failed to import clouds joyent:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/loader.py", line 957, in _load_module
    ), fn_, fpath, desc)
  File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/joyent.py", line 68, in <module>
    from Crypto.Signature import PKCS1_v1_5
ImportError: No module named Signature
[DEBUG   ] Could not LazyLoad parallels.avail_sizes
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy
[DEBUG   ] Could not LazyLoad saltify.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.avail_images
[DEBUG   ] Could not LazyLoad saltify.avail_locations
[DEBUG   ] LazyLoaded rackspace.reboot
[DEBUG   ] Could not LazyLoad openstack.list_locations
[DEBUG   ] LazyLoaded rackspace.list_locations
[DEBUG   ] Could not LazyLoad openstack.optimize_providers
[DEBUG   ] The 'openstack' cloud driver is unable to be optimized.
[ERROR   ] Failed to import clouds nova, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/loader.py", line 957, in _load_module
    ), fn_, fpath, desc)
  File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/nova.py", line 112, in <module>
    from salt.utils.openstack import nova
  File "/usr/lib/python2.6/site-packages/salt/utils/openstack/nova.py", line 10, in <module>
    from novaclient.v1_1 import client
  File "/usr/lib/python2.6/site-packages/novaclient/__init__.py", line 18, in <module>
    __version__ = pbr.version.VersionInfo('python-novaclient').version_string()
  File "/usr/lib/python2.6/site-packages/pbr/version.py", line 457, in version_string
    return self.semantic_version().brief_string()
  File "/usr/lib/python2.6/site-packages/pbr/version.py", line 452, in semantic_version
    self._semantic = self._get_version_from_pkg_resources()
  File "/usr/lib/python2.6/site-packages/pbr/version.py", line 439, in _get_version_from_pkg_resources
    result_string = packaging.get_version(self.package)
  File "/usr/lib/python2.6/site-packages/pbr/packaging.py", line 582, in get_version
    raise Exception("Versioning for this project requires either an sdist"
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. Are you sure that git is installed?
[DEBUG   ] Failed to import clouds joyent:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/loader.py", line 957, in _load_module
    ), fn_, fpath, desc)
  File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/joyent.py", line 68, in <module>
    from Crypto.Signature import PKCS1_v1_5
ImportError: No module named Signature
[DEBUG   ] Could not LazyLoad parallels.avail_sizes
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy
[DEBUG   ] Could not LazyLoad saltify.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.avail_images
[DEBUG   ] Could not LazyLoad saltify.avail_locations
[DEBUG   ] LazyLoaded rackspace.reboot
[DEBUG   ] Could not LazyLoad openstack.list_locations
[DEBUG   ] LazyLoaded rackspace.list_locations
[DEBUG   ] OpenStack authenticating using apikey
[DEBUG   ] Failed to execute 'openstack.list_nodes()' while querying for running nodes: [Errno -2] Name or service not known
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 2247, in run_parallel_map_providers_query
    cloud.clouds[data['fun']]()
  File "/usr/lib/python2.6/site-packages/salt/cloud/libcloudfuncs.py", line 432, in list_nodes
    nodes = conn.list_nodes()
  File "/usr/lib/python2.6/site-packages/libcloud/compute/drivers/openstack.py", line 149, in list_nodes
    self.connection.request('/servers/detail', params=params).object)
  File "/usr/lib/python2.6/site-packages/libcloud/common/openstack.py", line 200, in request
    raw=raw)
  File "/usr/lib/python2.6/site-packages/libcloud/common/base.py", line 657, in request
    action = self.morph_action_hook(action)
  File "/usr/lib/python2.6/site-packages/libcloud/common/openstack.py", line 255, in morph_action_hook
    self._populate_hosts_and_request_paths()
  File "/usr/lib/python2.6/site-packages/libcloud/common/openstack.py", line 288, in _populate_hosts_and_request_paths
    osa = osa.authenticate(**kwargs)  # may throw InvalidCreds
  File "/usr/lib/python2.6/site-packages/libcloud/common/openstack_identity.py", line 839, in authenticate
    return self._authenticate_2_0_with_api_key()
  File "/usr/lib/python2.6/site-packages/libcloud/common/openstack_identity.py", line 854, in _authenticate_2_0_with_api_key
    return self._authenticate_2_0_with_body(reqbody)
  File "/usr/lib/python2.6/site-packages/libcloud/common/openstack_identity.py", line 871, in _authenticate_2_0_with_body
    method='POST')
  File "/usr/lib/python2.6/site-packages/libcloud/common/base.py", line 721, in request
    headers=headers)
  File "/usr/lib64/python2.6/httplib.py", line 914, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.6/httplib.py", line 951, in _send_request
    self.endheaders()
  File "/usr/lib64/python2.6/httplib.py", line 908, in endheaders
    self._send_output()
  File "/usr/lib64/python2.6/httplib.py", line 780, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.6/httplib.py", line 739, in send
    self.connect()
  File "/usr/lib/python2.6/site-packages/libcloud/httplib_ssl.py", line 267, in connect
    self.timeout)
  File "/usr/lib64/python2.6/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno -2] Name or service not known
[DEBUG   ] Generating minion keys for 'vm-all-all-autodeploy3'
[DEBUG   ] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event - data = {'_stamp': '2015-07-23T12:08:01.272212'}
[DEBUG   ] Sending event - data = {'profile': 'sharedfarm_test', 'event': 'starting create', '_stamp': '2015-07-23T12:08:01.273030', 'name': 'vm-all-all-autodeploy3', 'provider': 'rs:openstack'}
[DEBUG   ] OpenStack authenticating using apikey
[DEBUG   ] OpenStack authenticating using apikey
Error: There was a profile error: Error creating vm-all-all-autodeploy3 on OPENSTACK

Could not find image 4.04 LTS (Trusty Tahr) (PVHVM): [Errno -2] Name or service not known

my profile looks like this
sharedfarm_prod:
  image: "CentOS 6(PVHVM)"
  provider: rs
  size: "8 GB General Purpose v1"

sharedfarm_stag:
  image: "CentOS 6 (PVHVM)"
  provider: rs
  size: "4 GB General Purpose v1"

sharedfarm_test:
  image: "4.04 LTS (Trusty Tahr) (PVHVM)"
  provider: rs
  size: "4 GB General Purpose v1"

**Comment by jfindlay** [comment]
@davidanands, I am glad you got it working.  Do you consider this issue closed?

**Comment by davidanands** [comment]
@jfindlay thank for the support, this can be closed.

**Comment by jfindlay** [comment]
@davidanands, nice, thanks.
