### ISSUE TITLE
Exception on `at` module execution

### ISSUE THREAD

**Issue by JensRantil** [saltstack/salt#25611]
I'm getting an exception when submitting a rather complicated `at` job:

```
$ salt myminion at.at "now + 4 weeks" "mysql -u root mydb -e "'"'"SELECT COUNT(*) FROM users;"'"'
myminion:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1146, in _thread_return
        return_data = func(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/at.py", line 249, in at
        return atq(int(output))
    ValueError: invalid literal for int() with base 10: '1:'
```

Submitting something like `echo hello` to be executed works. Version:

```
$ salt --versions-report
                  Salt: 2015.5.2
                Python: 2.7.3 (default, Jun 22 2015, 19:33:41)
                Jinja2: 2.6
              M2Crypto: 0.21.1
        msgpack-python: 0.1.10
          msgpack-pure: Not Installed
              pycrypto: 2.4.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 13.0.0
                  RAET: Not Installed
                   ZMQ: 3.2.2
                  Mako: Not Installed
 Debian source package: 2015.5.2+ds-1precise1
```

I can recreate the issue every time. Let me know if you need anything else from me.

**Comment by JensRantil** [comment]
Also, it looks like the job is created, but the content of the job seem to be empty:
```
$ sudo at -c 181
#!/bin/sh
# atrun uid=0 gid=0
# mail root 0
umask 22
UPSTART_INSTANCE=; export UPSTART_INSTANCE
UPSTART_JOB=salt-minion; export UPSTART_JOB
PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin; export PATH
LC_ALL=C; export LC_ALL
PWD=/root; export PWD
cd /root || {
	 echo 'Execution directory inaccessible' >&2
	 exit 1
}
```

**Comment by zhoujinl** [comment]
sorry . i don't know.

**Comment by jfindlay** [comment]
@JensRantil, your command looks like it has a misplaced `"` after the `-e` token.  Should it be: `salt myminion at.at "now + 4 weeks" "mysql -u root mydb -e '"'"SELECT COUNT(*) FROM users;"'"'"`?

**Comment by JensRantil** [comment]
@zhoujinl What don't you know?
@jfindlay Hm, your example yields the following in my terminal:

```bash
$ echo salt myminion at.at "now + 4 weeks" "mysql -u root mydb -e '"'"SELECT COUNT(*) FROM users;"'"'"
salt myminion at.at now + 4 weeks mysql -u root mydb -e '"SELECT COUNT(*) FROM users;"'
```

Notice the double quoting around the `SELECT` statement. It shouldn't be there.

For the record, this is what my command parses to:

```bash
$ echo salt myminion at.at "now + 4 weeks" "mysql -u root mydb -e "'"'"SELECT COUNT(*) FROM users;"'"'
salt myminion at.at now + 4 weeks mysql -u root mydb -e "SELECT COUNT(*) FROM users;"
```
(and yes, quoting in bash is mess! Double quoting is a double mess!)

**Comment by jfindlay** [comment]
@JensRantil, I am able to reproduce this on the 2015.5 branch but it works for me on 2015.8.

**Comment by JensRantil** [comment]
@jfindlay Awesome. As a side-note, are the labels you are assigning these issues documented somewhere?

**Comment by rallytime** [comment]
@JensRantil Yep! http://docs.saltstack.com/en/latest/topics/development/labels.html

**Comment by JensRantil** [comment]
FYI, I still recreate this on `2015.5.3`:

```bash
$ salt --versions-report
                  Salt: 2015.5.3
                Python: 2.7.3 (default, Jun 22 2015, 19:33:41)
                Jinja2: 2.6
              M2Crypto: 0.21.1
        msgpack-python: 0.1.10
          msgpack-pure: Not Installed
              pycrypto: 2.4.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 13.0.0
                  RAET: Not Installed
                   ZMQ: 3.2.2
                  Mako: Not Installed
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1precise2
```

**Comment by JensRantil** [comment]
> I am able to reproduce this on the 2015.5 branch but it works for me on 2015.8.

Good. Is there a plan to backport this to 2015.5 or shall I simply wait for 2015.8?

**Comment by jfindlay** [comment]
@JensRantil, at this point, the next 2015.5 release will come out at about the same time as 2015.8.
