### ISSUE TITLE
cloud.profile state error: dictionary changed size during iteration

### ISSUE THREAD

**Issue by jfindlay** [saltstack/salt#25641]
Additionally, the linode API key appears in the minion debug log:
```
[DEBUG   ] Requesting URL https://api.linode.com/?api_key=qwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnm&api_action=linode.list using GET method
```
```yaml
# salt --versions
Salt Version:
           Salt: 2015.8.0rc1-71-g079a15c

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
           Mako: 1.0.0
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.1
            ZMQ: 4.0.5
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
       pycrypto: 2.6.1

System Versions:
           dist: debian 8.1
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.1
```
```yaml
# cat /srv/salt/cluster.sls 
centos 7:
  cloud.profile:
    - name: jmoney-centos-7
    - profile: linode-centos-7
```
```yaml
# salt jmoney-main state.apply cluster
jmoney-main:
    ----------
    cloud_|-centos 7_|-jmoney-centos-7_|-profile:
        ----------
        __run_num__:
            0
        changes:
            ----------
        comment:
            An exception occurred in this state: Traceback (most recent call last):
              File "/root/salt/salt/state.py", line 1588, in call
                **cdata['kwargs'])
              File "/root/salt/salt/states/cloud.py", line 273, in profile
                info = __salt__['cloud.profile'](profile, name, vm_overrides=kwargs)
              File "/root/salt/salt/modules/cloud.py", line 196, in profile_
                info = client.profile(profile, names, vm_overrides=vm_overrides, **kwargs)
              File "/root/salt/salt/cloud/__init__.py", line 336, in profile
                mapper = salt.cloud.Map(self._opts_defaults(**kwargs))
              File "/root/salt/salt/cloud/__init__.py", line 230, in _opts_defaults
                for provider in six.iterkeys(_providers):
            RuntimeError: dictionary changed size during iteration
        duration:
            893.04
        name:
            jmoney-centos-7
        result:
            False
        start_time:
            15:50:29.087670
ERROR: Minions returned with non-zero exit code
```

**Comment by techhat** [comment]
@jfindlay I remember fixing this a couple of weeks ago. Have you checked develop?

**Comment by jfindlay** [comment]
@techhat, I'll try that, thanks.

**Comment by codehotter** [comment]
https://github.com/saltstack/salt/issues/24573

**Comment by jfindlay** [comment]
@techhat, I am getting the same result on develop, even after applying the patch proposed by @codehotter.
