### ISSUE TITLE
salt-cloud VMware driver fails with KeyErrors if there's any existing machine in the VMware infrastructure in (invalid state)

### ISSUE THREAD

**Issue by nmadhok** [saltstack/salt#25665]
If there's a VM in invalid state in the VMware infrastructure, many functions including ``create``, ``list_nodes``, list_nodes_select``, ``list_nodes_full``, ``show_instance`` will fail with a KeyError. This is because the properties aren't populated and available for them and if we try to loop over the properties, since they don't exist, it will raise a KeyError. It's safe to check if they exist and if not then display "N/A"

Here are the KeyErrors being raised:

```
[DEBUG   ] Failed to execute 'vmware.list_nodes()' while querying for running nodes: 'config.guestFullName'
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 2247, in run_parallel_map_providers_query
    cloud.clouds[data['fun']]()
  File "/usr/lib64/python2.6/contextlib.py", line 34, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.6/site-packages/salt/utils/context.py", line 42, in func_globals_inject
    yield
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 2247, in run_parallel_map_providers_query
    cloud.clouds[data['fun']]()
  File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/vmware.py", line 1412, in list_nodes
    'image': "{0} (Detected)".format(vm["config.guestFullName"]),
KeyError: 'config.guestFullName'
```

```
[DEBUG   ] Failed to execute 'vmware.list_nodes()' while querying for running nodes: 'config.hardware.numCPU'
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 2247, in run_parallel_map_providers_query
    cloud.clouds[data['fun']]()
  File "/usr/lib64/python2.6/contextlib.py", line 34, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.6/site-packages/salt/utils/context.py", line 42, in func_globals_inject
    yield
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 2247, in run_parallel_map_providers_query
    cloud.clouds[data['fun']]()
  File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/vmware.py", line 1413, in list_nodes
    'size': u"cpu: {0}\nram: {1}MB".format(vm["config.hardware.numCPU"], vm["config.hardware.memoryMB"]),
KeyError: 'config.hardware.numCPU'
```

```
[DEBUG   ] Failed to execute 'vmware.list_nodes()' while querying for running nodes: 'config.hardware.memoryMB'
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 2247, in run_parallel_map_providers_query
    cloud.clouds[data['fun']]()
  File "/usr/lib64/python2.6/contextlib.py", line 34, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.6/site-packages/salt/utils/context.py", line 42, in func_globals_inject
    yield
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 2247, in run_parallel_map_providers_query
    cloud.clouds[data['fun']]()
  File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/vmware.py", line 1413, in list_nodes
    'size': u"cpu: {0}\nram: {1}MB".format(vm["config.hardware.numCPU"] if "config.hardware.numCPU" in vm else "N/A", vm["config.hardware.memoryMB"]),
KeyError: 'config.hardware.memoryMB'
```

And there are more

**Comment by rallytime** [comment]
Thanks for the fix, as always! ;)

**Comment by nmadhok** [comment]
@rallytime Not a problem! :wink:

**Comment by cachedout** [comment]
Looks like this got merged. I'll go ahead and close this.

**Comment by evle-zzz** [comment]
It seems there are still cases when propery existence not checked. avail_images didn't work while I had disconnected VMs:
```
[ERROR   ] Failed to get the output of 'vmware.avail_images()': 'config.template'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 842, in image_list
    data[alias][driver] = self.clouds[fun]()
  File "/usr/local/lib/python2.7/dist-packages/salt/cloud/clouds/vmware.py", line 1672, in avail_images
    if vm["config.template"]:
KeyError: 'config.template'
[DEBUG   ] LazyLoaded nested.output
```

**Comment by nmadhok** [comment]
@evle-zzz can you open a new issue and tag me on it? Thanks for reporting this!
