### ISSUE TITLE
tcp transport stacktrace on windows minion: Future exception was never retrieved

### ISSUE THREAD

**Issue by jfindlay** [saltstack/salt#25718]
### versions
```yaml
# salt jmoney-windows-12 test.versions_report
jmoney-windows-12:
    Salt Version:
               Salt: 2015.8.0rc2

    Dependency Versions:
             Jinja2: 2.7.3
           M2Crypto: Not Installed
               Mako: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.7.0
             Python: 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.1.2
              ioflo: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
           pycrypto: 2.6.1

    System Versions:
               dist:
            machine: AMD64
            release: 2012Server
             system: 2012Server 6.2.9200  Multiprocessor Free
```

### commands
This command consistently triggers the errors seen, although they may arise in other circumstances.
```console
# salt jmoney-windows-12 pkg.refresh_db
jmoney-windows-12:
    Minion did not return. [No response]
```

### logs
```
# master log
[DEBUG   ] Sending event - data = {'_stamp': '2015-07-24T23:38:15.582697', 'minions': ['jmoney-windows-12']}
[DEBUG   ] Sending event - data = {'tgt_type': 'glob', 'jid': '20150724173815582439', 'tgt': 'jmoney-windows-12', '_stamp': '2015-07-24T23:38:15.583041', 'user': 'root', 'arg': [], 'fun': 'pkg.refresh_db', 'minions': ['jmoney-windows-12']}
[INFO    ] User root Published command pkg.refresh_db with jid 20150724173815582439
[DEBUG   ] Published command details {'tgt_type': 'glob', 'jid': '20150724173815582439', 'tgt': 'jmoney-windows-12', 'ret': '', 'user': 'root', 'arg': [], 'fun': 'pkg.refresh_db'}
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/publish_pull.ipc
���{�����+��Q���.�-�&�u;8��x/C��1�TQ0D�l]�p����d���=y��$$�D:��a`S���2�,T�[��Tme���R�Z�ԟ�P��!�b!.��B�U�����i7�YR�.O
                                                                                                                  K�t�֢8�bࢰ��F�j�enc�aes�head�
[ERROR   ] Exception occurred while handling stream:
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: jmoney-main
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[DEBUG   ] LazyLoaded local_cache.clean_old_jobs
[DEBUG   ] Could not LazyLoad config.merge
[DEBUG   ] Updating roots fileserver cache
[DEBUG   ] This salt-master instance has accepted 2 minion keys.
[DEBUG   ] Sending event - data = {'_stamp': '2015-07-24T23:38:20.595573', 'minions': ['jmoney-windows-12']}
[DEBUG   ] Sending event - data = {'tgt_type': 'glob', 'jid': '20150724173820595275', 'tgt': 'jmoney-windows-12', '_stamp': '2015-07-24T23:38:20.596002', 'user': 'root', 'arg': ['20150724173815582439'], 'fun': 'saltutil.find_job', 'minions': ['jmoney-windows-12']}
[INFO    ] User root Published command saltutil.find_job with jid 20150724173820595275
[DEBUG   ] Published command details {'tgt_type': 'glob', 'jid': '20150724173820595275', 'tgt': 'jmoney-windows-12', 'ret': '', 'user': 'root', 'arg': ['20150724173815582439'], 'fun': 'saltutil.find_job'}
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/publish_pull.ipc
[DEBUG   ] TCP PubServer sending payload: 224 ��body�т�load����z�Rk��AMq3J}������{[C��Ï�|�ļ�j�A�BT��R��V��p���{��{R<B���vچ���4FߨC��|<�C�3�)l[X�<�Ntw�r�����]��� �g����7Y�~z���*V�6��j�������e
                                                                                                                                                                                             )������2�g��.�����yE�C6�m���j���enc�aes�head�
[ERROR   ] Exception occurred while handling stream:
```
```python-traceback
# minion log
2015-07-24 23:28:05,411 [salt.fileclient  ][INFO    ][1676] Fetching file from saltenv 'base', ** done ** u'win/repo/salt-winrepo.git/filezilla.sls'
2015-07-24 23:28:05,442 [salt.fileclient  ][DEBUG   ][1676] In saltenv 'base', looking at rel_path u'win/repo/salt-winrepo.git/firefox.sls' to resolve u'salt://win/repo/salt-winrepo.git/firefox.sls'
2015-07-24 23:28:05,442 [salt.fileclient  ][DEBUG   ][1676] In saltenv 'base', ** considering ** path u'c:\\salt\\var\\cache\\salt\\minion\\files\\base\\win/repo/salt-winrepo.git/firefox.sls' to resolve u'salt://win/repo/salt-winrepo.git/firefox.sls'
2015-07-24 23:28:05,442 [salt.fileclient  ][DEBUG   ][1676] Fetching file from saltenv 'base', ** attempting ** u'salt://win/repo/salt-winrepo.git/firefox.sls'
2015-07-24 23:28:05,442 [salt.fileclient  ][DEBUG   ][1676] No dest file found
2015-07-24 23:28:05,505 [salt.minion      ][INFO    ][1676] User root Executing command saltutil.find_job with jid 20150724172736012184
2015-07-24 23:28:05,505 [salt.minion      ][DEBUG   ][1676] Command details {'tgt_type': 'glob', 'jid': '20150724172736012184', 'tgt': 'jmoney-windows-12', 'ret': '', 'user': 'root', 'arg': ['20150724172730999547'], 'fun': 'saltutil.find_job'}
2015-07-24 23:28:05,505 [salt.minion      ][INFO    ][1676] Starting a new job with PID 1676
2015-07-24 23:28:05,551 [salt.fileclient  ][INFO    ][1676] Fetching file from saltenv 'base', ** done ** u'win/repo/salt-winrepo.git/firefox.sls'
2015-07-24 23:28:05,583 [salt.utils.lazy  ][DEBUG   ][1676] LazyLoaded saltutil.find_job
2015-07-24 23:28:05,583 [salt.minion      ][INFO    ][1676] Returning information for job: 20150724172736012184
2015-07-24 23:28:05,583 [salt.transport.tcp][DEBUG   ][1676] Re-using AsyncTCPReqChannel for ('c:\\salt\\conf\\pki\\minion', 'jmoney-windows-12', 'tcp://23.253.230.82:4506', 'aes')
2015-07-24 23:28:05,614 [salt.fileclient  ][DEBUG   ][1676] In saltenv 'base', looking at rel_path u'win/repo/salt-winrepo.git/firefox_x86.sls' to resolve u'salt://win/repo/salt-winrepo.git/firefox_x86.sls'
2015-07-24 23:28:05,614 [salt.fileclient  ][DEBUG   ][1676] In saltenv 'base', ** considering ** path u'c:\\salt\\var\\cache\\salt\\minion\\files\\base\\win/repo/salt-winrepo.git/firefox_x86.sls' to resolve u'salt://win/repo/salt-winrepo.git/firefox_x86.sls'
2015-07-24 23:28:05,614 [salt.fileclient  ][DEBUG   ][1676] Fetching file from saltenv 'base', ** attempting ** u'salt://win/repo/salt-winrepo.git/firefox_x86.sls'
2015-07-24 23:28:05,614 [salt.fileclient  ][DEBUG   ][1676] No dest file found
2015-07-24 23:29:05,605 [tornado.application][ERROR   ][1676] Future exception was never retrieved: Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\tornado\gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\salt\bin\lib\site-packages\salt\transport\tcp.py", line 181, in send
    ret = yield self._crypted_transfer(load, tries=tries, timeout=timeout)
  File "C:\salt\bin\lib\site-packages\tornado\gen.py", line 870, in run
    value = future.result()
  File "C:\salt\bin\lib\site-packages\tornado\concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "C:\salt\bin\lib\site-packages\tornado\gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\salt\bin\lib\site-packages\salt\transport\tcp.py", line 161, in _crypted_transfer
    ret = yield _do_transfer()
  File "C:\salt\bin\lib\site-packages\tornado\gen.py", line 870, in run
    value = future.result()
  File "C:\salt\bin\lib\site-packages\tornado\concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "C:\salt\bin\lib\site-packages\tornado\gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\salt\bin\lib\site-packages\salt\transport\tcp.py", line 148, in _do_transfer
    timeout=timeout,
  File "C:\salt\bin\lib\site-packages\tornado\gen.py", line 870, in run
    value = future.result()
  File "C:\salt\bin\lib\site-packages\tornado\concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
SaltReqTimeoutError: Message timed out
2015-07-24 23:29:05,605 [salt.minion      ][WARNING ][1676] The minion function caused an exception
Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 1037, in _thread_return
    return_data = func(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 375, in refresh_db
    cached_files = __salt__['cp.cache_dir'](repo, saltenv, include_pat='*.sls')
  File "C:\salt\bin\lib\site-packages\salt\modules\cp.py", line 444, in cache_dir
    path, saltenv, include_empty, include_pat, exclude_pat
  File "C:\salt\bin\lib\site-packages\salt\fileclient.py", line 232, in cache_dir
    fn_ = self.cache_file(salt.utils.url.create(fn_), saltenv)
  File "C:\salt\bin\lib\site-packages\salt\fileclient.py", line 154, in cache_file
    return self.get_url(path, '', True, saltenv)
  File "C:\salt\bin\lib\site-packages\salt\fileclient.py", line 539, in get_url
    return self.get_file(url, dest, makedirs, saltenv)
  File "C:\salt\bin\lib\site-packages\salt\fileclient.py", line 1056, in get_file
    data = self.channel.send(load)
  File "C:\salt\bin\lib\site-packages\salt\utils\async.py", line 77, in wrap
    ret = self._block_future(ret)
  File "C:\salt\bin\lib\site-packages\salt\utils\async.py", line 87, in _block_future
    return future.result()
  File "C:\salt\bin\lib\site-packages\tornado\concurrent.py", line 216, in result
    self._check_done()
  File "C:\salt\bin\lib\site-packages\tornado\concurrent.py", line 294, in _check_done
    raise Exception("DummyFuture does not support blocking for results")
Exception: DummyFuture does not support blocking for results
2015-07-24 23:29:05,621 [salt.utils.event ][DEBUG   ][1676] SaltEvent PUB socket URI: tcp://127.0.0.1:4510
2015-07-24 23:29:05,621 [salt.utils.event ][DEBUG   ][1676] SaltEvent PULL socket URI: tcp://127.0.0.1:4511
2015-07-24 23:29:05,621 [salt.utils.event ][DEBUG   ][1676] Sending event - data = {'message': u'The minion function caused an exception', 'args': ('The minion function caused an exception',), '_stamp': '2015-07-24T23:29:05.621000'}
2015-07-24 23:29:05,621 [salt.minion      ][DEBUG   ][1676] Handling event "_salt_error\n\n\x83\xa7message\xda\x00'The minion function caused an exception\xa4args\x91\xda\x00'The minion function caused an exception\xa6_stamp\xba2015-07-24T23:29:05.621000"
2015-07-24 23:29:05,621 [salt.minion      ][DEBUG   ][1676] Forwarding salt error event tag=_salt_error
2015-07-24 23:29:05,621 [salt.transport.tcp][DEBUG   ][1676] Re-using AsyncTCPReqChannel for ('c:\\salt\\conf\\pki\\minion', 'jmoney-windows-12', 'tcp://23.253.230.82:4506', 'aes')
2015-07-24 23:29:05,621 [salt.minion      ][INFO    ][1676] fire_master failed: Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 926, in _fire_master
    result = channel.send(load, timeout=timeout)
  File "C:\salt\bin\lib\site-packages\salt\utils\async.py", line 77, in wrap
    ret = self._block_future(ret)
  File "C:\salt\bin\lib\site-packages\salt\utils\async.py", line 87, in _block_future
    return future.result()
  File "C:\salt\bin\lib\site-packages\tornado\concurrent.py", line 216, in result
    self._check_done()
  File "C:\salt\bin\lib\site-packages\tornado\concurrent.py", line 294, in _check_done
    raise Exception("DummyFuture does not support blocking for results")
Exception: DummyFuture does not support blocking for results

2015-07-24 23:29:05,652 [salt.minion      ][INFO    ][1676] Returning information for job: 20150724172730999547
2015-07-24 23:29:05,652 [salt.transport.tcp][DEBUG   ][1676] Re-using AsyncTCPReqChannel for ('c:\\salt\\conf\\pki\\minion', 'jmoney-windows-12', 'tcp://23.253.230.82:4506', 'aes')
```

**Comment by s0undt3ch** [comment]
I've seen the future was never retrieved when trying your ipc work on py3 @jacksontj.

**Comment by jacksontj** [comment]
This seems odd... From the last stack trace there on the minion side it looks like the async wrapper died out because the future it was blocking on didn't finish, which is odd since the call in the code (https://github.com/saltstack/salt/blob/2015.8/salt/utils/async.py#L84) doesn't have anything in there to die like that. I know there was some version that @cachedout had where deletion of the IPC Channel would call ioloop.stop() and that could cause stuff like this, but I don't see that anymore on 2015.8, so I'm at a loss here :/ I can't seem to reproduce this issue on my side, any suggestions?

Some background-- all the "never retrieved" thing means is that there was a future (async operation) where we never checked the return of it. The few that we intentionally fire off that we don't care about are usually attached to null complete callbacks (meaning they do nothing, but then it is happy because we called one).

**Comment by jfindlay** [comment]
I am increasing the priority because I have retested `salt jmoney-windows-12 pkg.refresh_db` with the transport set to zeromq and still run into this error.

**Comment by jacksontj** [comment]
@jfindlay or @s0undt3ch I've spent a bit of time trying to repro this, but I can't seem to be able to. Have any pointers? Or a test case? I thought it might be something with nested async wraps-- but best I can tell that works as expected.

**Comment by jacksontj** [comment]
While thinking through possible errors I found something else that I ran into while working on the event system-- but the error message from that is completely different (exception about the loop already being started).

**Comment by jfindlay** [comment]
@jacksontj, I seem to encounter this consistently with a rackspace windows 2012 r2 with salt 2015.8.0rc2.  I can set up one if you want to look into it further.

**Comment by jacksontj** [comment]
That'd work, I'd prefer a *nix system of course, but if thats all we can repro on I can take a look ;) @s0undt3ch had mentioned reproing this issue as well, wonder if his repro case is simpler?

**Comment by s0undt3ch** [comment]
@jacksontj if it helps, "all you have to do" is run the code under python 3(at least in 3.4 which is what I'm using). Tornado in Py3 logs the _"Future exception was never retrieved"_. Just run your ipc/tcp unit tests from your pr under py3.

**Comment by jacksontj** [comment]
Okay, I think i figured out @jfindlay 's issue-- looks like the issue is actually not quite tornado's fault ;) I can reproduce the same error if I start a master and minion, then stop the master. The problem is since the event handler fires off a separate callback (spawn_callback) the exception for the timeout has to be handled by _mine_send, which it isn't. I added a try/except around the send and I don't see the exceptions any more.

**Comment by jacksontj** [comment]
oops, wrong issue :(

**Comment by jacksontj** [comment]
@s0undt3ch do I need magic to get py3 working? I tried to run it within my virutualenv and it keeps complaining that salttesting doesn't exist :/

**Comment by s0undt3ch** [comment]
Do you have I installed on your py3 virtualenv

**Comment by s0undt3ch** [comment]
It

**Comment by jacksontj** [comment]
I have it installed in *a *python virtualenv, but from some googling around
it seems like I need a separate py3 one ;) I'll try and make some time to
look at that tomorrow morning.

**Comment by jfindlay** [comment]
I haven't seen this on recent windows tests on 2015.8.
