### ISSUE TITLE
Problem with chocolatey module not loading

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#25717]
Shane, can you help troubleshoot this installation on Windows? This is from one of our EA Program participants (they are on 4.0).

Thanks,

On Mon, Jul 20, 2015 at 8:16 AM, Dave Giles <@saltstack.com> wrote:
Meggie / Daniel-

Received the following 2 issues back during conversations back and forth with Andre:

I was trying to use the elasticsearch returner on the master. I installed the elasticsearch-py and jsonpickle libraries using pip but I still get the following error when I try to use it: 2015-07-16 10:27:45,255 [salt.master      ][CRITICAL][19069] The specified returner used for the master job cache "elasticsearch" does not have a save_load function!
2015-07-16 10:27:45,379 [salt.client      ][WARNING ][20261] Returner unavailable: 'elasticsearch.get_load'
2015-07-16 10:27:45,689 [salt.utils.job   ][ERROR   ][19052] Returner 'elasticsearch' does not support function returner
2015-07-16 10:27:45,696 [salt.master      ][ERROR   ][19052] Error in function _return:
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/salt/master.py", line 1457, in run_func
    ret = getattr(self, func)(load)
  File "/usr/lib/pymodules/python2.7/salt/master.py", line 1273, in _return
    self.opts, load, event=self.event, mminion=self.mminion)
  File "/usr/lib/pymodules/python2.7/salt/utils/job.py", line 84, in store_job
    raise KeyError(emsg)
KeyError: "Returner 'elasticsearch' does not support function returner"

Using chocolately.bootstrap on a windows machine, it installs the files on a Windows Server 2012 image (from Azure) but it adds chocolately last in the path which breaks if there is paths with spaces or something else weird. So choco.exe isn't found by either salt nor command line. I solved the command line by putting the chocolately path first on path instead. But still I get the following message when trying to run chocolately (I restarted the salt minion after chocolately path change):
root@dvs-eu-sama:~# salt 'dev-eu-iceb-02' chocolately.install atom -t 600
dev-eu-iceb-02:
    'chocolately' __virtual__ returned False
What do you need from here?

Regards,
 SaltStack, Inc.

d@saltstack.com

On Tue, Jul 14, 2015 at 3:02 PM, Meggie @saltstack.com> wrote:
Great, thanks. Let me/Daniel know if you need engineering help.

Thanks,

On Tue, Jul 14, 2015 at 12:00 PM, Dave Giles <@saltstack.com> wrote:
I responded, waiting on results...

Regards,
 SaltStack, Inc.

On Tue, Jul 14, 2015 at 12:52 PM, Meggie Woodfield <@saltstack.com> wrote:
Has anyone responded to Andre? Since we are not using customer support for EA program participants, maybe another SE could reach out to him and try to help with this problem?

Thanks,

On Tue, Jul 14, 2015 at 3:12 AM, André Johansson wrote:
Hello,

I've been in contact with Celeste from SaltStack and I'm trying to setup a SaltStack Enterprise installation. However I'm having problems with user authentication, I've posted a question in the comments of this issue:

What am I missing?

**Comment by twangboy** [comment]
The lazyloader can't load the chocolatey module for some reason. That's why it's returning the `'chocholatey' virtual returned false`. I'm looking into why the module isn't loading.
