### ISSUE TITLE
tcp transport: minion stack trace: Unhandled exception running mine.update

### ISSUE THREAD

**Issue by jfindlay** [saltstack/salt#25720]
### versions
```yaml
# salt-minion --versions
Salt Version:
           Salt: 2015.8.0rc2
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
           Mako: 1.0.0
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.1
            ZMQ: 4.0.5
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
       pycrypto: 2.6.1
 
System Versions:
           dist: debian 8.1 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.1 
```
### logs
This stack trace happened a few hours after starting the minion.
```python
[INFO    ] Running scheduled job: __mine_interval
[DEBUG   ] schedule: This job was scheduled with jid_include, adding to cache (jid_include defaults to True)
[DEBUG   ] schedule: This job was scheduled with a max number of 2
[DEBUG   ] schedule.handle_func: adding this job to the jobcache with data {'fun': 'mine.update', 'jid': '20150724202343072152', 'pid': 3044, 'id': 'jmoney-main', 'schedule': '__mine_interval'}
[DEBUG   ] MinionEvent PUB socket URI: ipc:///var/run/salt/minion/minion_event_3f1c9a06f3_pub.ipc
[DEBUG   ] MinionEvent PULL socket URI: ipc:///var/run/salt/minion/minion_event_3f1c9a06f3_pull.ipc
[DEBUG   ] Sending event - data = {'clear': False, 'cmd': '_mine', 'data': {}, 'id': 'jmoney-main', '_stamp': '2015-07-25T02:23:43.082212'}
[DEBUG   ] Handling event '_minion_mine\n\n\x85\xa5clear\xc2\xa3cmd\xa5_mine\xa4data\x80\xa2id\xabjmoney-main\xa6_stamp\xba2015-07-25T02:23:43.082212'
[DEBUG   ] Initializing new AsyncTCPReqChannel for ('/etc/salt/pki/minion', 'jmoney-main', 'tcp://127.0.0.1:4506', 'aes')
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'jmoney-main', 'tcp://127.0.0.1:4506')
[DEBUG   ] tcp stream to 127.0.0.1:4506 closed, unable to recv
[DEBUG   ] Initializing new AsyncTCPReqChannel for ('/etc/salt/pki/minion', 'jmoney-main', 'tcp://127.0.0.1:4506', 'aes')
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'jmoney-main', 'tcp://127.0.0.1:4506')
[DEBUG   ] tcp stream to 127.0.0.1:4506 closed, unable to recv
[ERROR   ] Unhandled exception running mine.update
Traceback (most recent call last):
  File "/root/salt/salt/utils/schedule.py", line 706, in handle_func
    channel.send(load)
  File "/root/salt/salt/utils/async.py", line 77, in wrap
    ret = self._block_future(ret)
  File "/root/salt/salt/utils/async.py", line 87, in _block_future
    return future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 209, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 810, in run
    yielded = self.gen.throw(*sys.exc_info())
  File "/root/salt/salt/transport/tcp.py", line 181, in send
    ret = yield self._crypted_transfer(load, tries=tries, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 807, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 209, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 810, in run
    yielded = self.gen.throw(*sys.exc_info())
  File "/root/salt/salt/transport/tcp.py", line 161, in _crypted_transfer
    ret = yield _do_transfer()
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 807, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 209, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 810, in run
    yielded = self.gen.throw(*sys.exc_info())
  File "/root/salt/salt/transport/tcp.py", line 148, in _do_transfer
    timeout=timeout,
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 807, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 209, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
SaltReqTimeoutError: Message timed out
[DEBUG   ] schedule.handle_func: Removing /var/cache/salt/minion/proc/20150724202343072152
```

**Comment by jfindlay** [comment]
I have had this minion running for about a day and it now consistently stack traces on the mine update.

**Comment by jfindlay** [comment]
I am increasing the severity since I can reliably re[produce this problem and the minion becomes unresponsive after entering the state of periodic stack traces.

**Comment by ssgward** [comment]
@jacksontj - will you take a look at this?

**Comment by jacksontj** [comment]
Okay, I think i figured out @jfindlay 's issue-- looks like the issue is actually not quite tornado's fault ;) I can reproduce the same error if I start a master and minion, then stop the master. The problem is since the event handler fires off a separate callback (spawn_callback) the exception for the timeout has to be handled by _mine_send, which it isn't. I added a try/except around the send and I don't see the exceptions any more.

**Comment by allanliu** [comment]
I'm running salt-minion 2015.8.1-286-g23eae0d (Beryllium) on a Ubuntu LTS 14.04, and I still get a similar error..
```
2015-11-19 11:48:36,152 [salt.minion      ][WARNING ][10504] Unable to send mine data to master.
2015-11-19 11:48:36,655 [salt.utils.schedule][ERROR   ][27460] Unhandled exception running mine.update
Traceback (most recent call last):
  File "/root/src/salt/salt/utils/schedule.py", line 710, in handle_func
    channel.send(load)
  File "/root/src/salt/salt/utils/async.py", line 73, in wrap
    ret = self._block_future(ret)
  File "/root/src/salt/salt/utils/async.py", line 83, in _block_future
    return future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/root/src/salt/salt/transport/zeromq.py", line 231, in send
    ret = yield self._crypted_transfer(load, tries=tries, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/root/src/salt/salt/transport/zeromq.py", line 199, in _crypted_transfer
    ret = yield _do_transfer()
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/root/src/salt/salt/transport/zeromq.py", line 185, in _do_transfer
    tries=tries,
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
SaltReqTimeoutError: Message timed out
```
..
