### ISSUE TITLE
Esky builds on SmartOS broken in 2015.5 branch

### ISSUE THREAD

**Issue by nshalman** [saltstack/salt#25756]
Transferring content from an email thread at @jfindlay's request (see the last few comments on #25730)

@nshalman:
> Something in 2015.5 doesn't seem to like being packaged in an Esky and I haven't had a chance to debug it...

@dmurphy18:
> There is a problem with the use of decorators in the lazy loader where `inspect.getmodule` is not returning a module.
> Found this with the 2015.5 branch, but have not had time to research a solution for the issue yet.
> `./salt/utils/decorators/__init__.py  line 62`
> Found issues researching on Google about use of `@decorator` syntax and not using index 1 but 2 when inspecting the stack.
> I have tried replacing the `__init__.py` file without the benefit of esky and the problem still occurred. 
However esky could be affecting other files. BTW: python used was python 2.7.10.

**Comment by jfindlay** [comment]
We either need to fix the issues with esky or find a new packaging mechanism.  I remember @UtahDave mentioning problems with esky packages with regards to windows.  They may apply here as well.

**Comment by nshalman** [comment]
Yup. I haven't had (and probably still don't have) the bandwidth to do either. 

My understanding is that the Windows builds no longer use Esky at all.

I think @dmurphy18's thoughts on the issue will be important because time and energy is being invested in using Esky for Solaris builds of 2014.7 branches at the moment.

**Comment by nshalman** [comment]
@sjorge just reminded me of how I first noticed that something was wrong.
The quick test that fails is ```salt-call --local test.ping``` fails with ```'test.ping' is not available.```

**Comment by sjorge** [comment]
which results in this:
```
[root@core ~]# /opt/local/salt/bin/salt-call --local test.ping
[WARNING ] Failed to open log file, do you have permission to write to /opt/local/salt/var/log/salt/minion?
[ERROR   ] Failed to import module test, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "salt/loader.py", line 1052, in _load_module
  File "salt/modules/test.py", line 31, in <module>
  File "salt/utils/decorators/__init__.py", line 66, in __call__
AttributeError: 'NoneType' object has no attribute '__name__'
[INFO    ] Executing command 'pkg_info -Q LOCALBASE pkgin' in directory '/root'
[ERROR   ] Exception raised when processing __virtual__ function for pkgin. Module will not be loaded Unable to run command ['pkg_info', '-Q', 'LOCALBASE', 'pkgin'] with the context {'with_communicate': True, 'shell': False, 'env': {'LANG': 'en_US.UTF-8', 'TERM': 'xterm', 'SHELL': '/usr/bin/bash', 'TZ': 'UTC', 'MANPATH': '/usr/share/man:/smartdc/man:/opt/smartdc/man:/opt/local/man', 'MAIL': '/var/mail/root', 'SHLVL': '1', 'SSH_TTY': '/dev/pts/2', 'SSH_CLIENT': '2001:6f8:1480:30::1 2845 22', 'PWD': '/root', 'LOGNAME': 'root', 'USER': 'root', 'PROMPT_COMMAND': 'echo -ne "\\033]0;${HOSTNAME} \\007" && history -a', 'PATH': '/opt/local/salt/bin/appdata/salt-2015.8.0rc2-13-gf001d7e.solaris-2_11-i86pc_64bit:/usr/bin:/usr/sbin:/smartdc/bin:/opt/smartdc/bin:/opt/local/bin:/opt/local/sbin:/opt/smartdc/agents/bin', 'HOME': '/root', 'SSH_CONNECTION': '2001:6f8:1480:30::1 2845 2001:6f8:1480:30::91 22', 'PAGER': 'less', 'LC_ALL': 'C', '_': '/opt/local/salt/bin/salt-call'}, 'stdout': -1, 'close_fds': True, 'stdin': None, 'stderr': -2, 'cwd': '/root'}, reason: [Errno 2] No such file or directory
[WARNING ] salt.loaded.int.module.pkgin.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'pkgin', please fix this.
[ERROR   ] Failed to import module archive, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "salt/loader.py", line 1052, in _load_module
  File "salt/modules/archive.py", line 252, in <module>
  File "salt/utils/decorators/__init__.py", line 66, in __call__
AttributeError: 'NoneType' object has no attribute '__name__'
[ERROR   ] Failed to import module oracle, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "salt/loader.py", line 1052, in _load_module
  File "salt/modules/oracle.py", line 111, in <module>
  File "salt/utils/decorators/__init__.py", line 66, in __call__
AttributeError: 'NoneType' object has no attribute '__name__'
'test.ping' is not available.
```

**Comment by sjorge** [comment]
```
inspect.stack(): [(<frame object at 0xfffffd7ffd3b1de0>, 'salt/utils/decorators/__init__.py', 64, '__call__', None, None), (<frame object at 0xfffffd7ffc0367b0>, 'salt/modules/archive.py', 252, '<module>', None, None), (<frame object at 0x18994b0>, 'salt/loader.py', 1052, '_load_module', None, None), (<frame object at 0xfffffd7ffd324050>, 'salt/loader.py', 1209, '_inner_load', None, None), (<frame object at 0x10344e0>, 'salt/loader.py', 1220, '_load', None, None), (<frame object at 0xfffffd7ffd33ccc8>, 'salt/utils/lazy.py', 88, '__getitem__', None, None), (<frame object at 0xfffffd7ffd3245d8>, '_abcoll.py', 388, '__contains__', None, None), (<frame object at 0x10448e0>, 'salt/cli/caller.py', 165, 'call', None, None), (<frame object at 0x10446b0>, 'salt/cli/caller.py', 133, 'run', None, None), (<frame object at 0xfffffd7ffd3a8050>, 'salt/cli/call.py', 50, 'run', None, None), (<frame object at 0xfffffd7ffef5ae18>, 'salt/scripts.py', 224, 'salt_call', None, None), (<frame object at 0xfffffd7fff128560>, '__main__salt-call__.py', 14, '<module>', None, None), (<frame object at 0xfffffd7fff1333e0>, '__main__.py', 128, '<module>', None, None), (<frame object at 0xfffffd7fff02d050>, '<string>', 6, '<module>', None, None)]
inspect.stack()[1][0]: <frame object at 0xfffffd7ffc0367b0>
``
the values of inspect.stack

**Comment by sjorge** [comment]
@nshalman should be fixed in the 2015.8 branch now, wanna give it a spin and see if everything is working now? If you still hit issues I will try to replicate/fix.

**Comment by nshalman** [comment]
This passes the very quick sanity checks of tests that were failing when everything broke a while back. If @jfindlay has a chance to run the it through a slightly more extensive test run that would be good. I've uploaded a build here: http://us-east.manta.joyent.com/nahamu/public/salt/testing/salt-2015.8.0rc2-39-g10813ca-esky-smartos.tar.gz

**Comment by jfindlay** [comment]
Nice, I'll look at this when I have a moment.  Thanks @nshalman, @sjorge.
