### ISSUE TITLE
[EC2][AWS] How to specify static private ip address in map file?

### ISSUE THREAD

**Issue by zanhsieh** [saltstack/salt#25770]
See [#932](https://github.com/saltstack/salt-cloud/issues/932). I just wonder the way to specify the private ip address in map file instead of defining it in the profile file. Thanks.

**Comment by techhat** [comment]
All profile values can be used in map files.

**Comment by techhat** [comment]
@zanhsieh, could you please post the output from `salt-cloud --versions-report`? Values in profiles are merged together with values from map files, so they should work the same. If you have values that work in profiles but not maps, we have a bug on our hands.

**Comment by zanhsieh** [comment]
@techhat 
[root@saltmaster zanhsieh]# salt-cloud --versions-report
            Salt: 2015.5.2
          Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
          Jinja2: 2.2.1
        M2Crypto: 0.20.2
  msgpack-python: 0.4.6
    msgpack-pure: Not Installed
        pycrypto: 2.0.1
         libnacl: Not Installed
          PyYAML: 3.10
           ioflo: Not Installed
           PyZMQ: 14.3.1
            RAET: Not Installed
             ZMQ: 3.2.5
            Mako: Not Installed
 Apache Libcloud: 0.17.0

**Comment by zanhsieh** [comment]
I tried it on the map file but still not go:

My provider file looks like this:
```
my-ec2-southeast-public-ips:
  ssh_interface: public_ips
  id: xxxxPERSONALIDxxxx
  key: 'xxxxPERSONALKEYxxxx'
  location: ap-southeast-1
  availability_zone: ap-southeast-1b
  ssh_username: ec2-user
  provider: ec2

my-ec2-southeast-private-ips:
  ssh_interface: private_pis
  id: xxxxPERSONALIDxxxx
  key: 'xxxxPERSONALKEYxxxx'
  location: ap-southeast-1
  availability_zone: ap-southeast-1b
  ssh_username: ec2-user
  provider: ec2
```
My profile file looks like this:
```
base_ec2_public:
  provider: my-ec2-southeast-public-ips
  image: ami-ceb2b09c
  size: t2.micro
  ssh_username: ec2-user

base_ec2_xxxx_dummy:
  subnetid: subnet-b70e8dd2
  securitygroupid:
    - sg-24fa6541
  extends: base_ec2_public
```

My map file looks like this:
```
base_ec2_xxxx_dummy:
  - dummy1:
      network_interfaces:
        - DeviceIndex: 0
          PrivateIpAddress:
            - Primary: True
              PrivateIpAddress: 192.168.133.105
          SubnetId: subnet-b70e8dd2
          SecurityGroupId:
            - sg-24fa6541
```
Run salt-cloud:
```
root: /etc/salt $ salt-cloud --map=/etc/salt/cloud.maps.d/aws.conf --parallel
[INFO    ] salt-cloud starting
[INFO    ] Applying map from '/etc/salt/cloud.maps.d/aws.conf'.
[INFO    ] Starting new HTTPS connection (1): ec2.ap-southeast-1.amazonaws.com
The following virtual machines are set to be created:
  dummy1

Proceed? [N/y] y
... proceeding
[INFO    ] Calculating dependencies for dummy1
[INFO    ] Since parallel deployment is in use, ssh console output is disabled. All ssh output will be logged though
[INFO    ] Cloud pool size: 1
[INFO    ] Creating Cloud VM dummy1 in ap-southeast-1
[INFO    ] Starting new HTTPS connection (1): ec2.ap-southeast-1.amazonaws.com
[INFO    ] Starting new HTTPS connection (1): ec2.ap-southeast-1.amazonaws.com
[INFO    ] Starting new HTTPS connection (1): ec2.ap-southeast-1.amazonaws.com
[ERROR   ] AWS Response Status Code and Error: [400 400 Client Error: Bad Request] {'Errors': {'Error': {'Message': "invalid value for parameter address: [[OrderedDict([('Primary', True), ('PrivateIpAddress', '192.168.133.105')])]]", 'Code': 'InvalidParameterValue'}}, 'RequestID': 'b11d132a-6006-4f1a-858b-8a9cae075d97'}
[ERROR   ] Failed to create VM dummy1. Configuration value 1 needs to be set
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1241, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 2153, in create
    data, vm_ = request_instance(vm_, location)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 1544, in request_instance
    _new_eni = _create_eni(interface)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 1180, in _create_eni
    eni_desc = result[1]
KeyError: 1
dummy1:
    ----------
```

**Comment by vgoineau** [comment]
zanhsieh... try 

PrivateIpAddresses:
            - Primary: True
              PrivateIpAddress: 192.168.133.105

instead of PrivateIpAdress... worked for me.

**Comment by zanhsieh** [comment]
@vgoineau: yes it does work. i'll close this issue.
