### ISSUE TITLE
Multimaster fails when using TCP transport mechanism

### ISSUE THREAD

**Issue by jtand** [saltstack/salt#25795]
When using the TCP transport mechanism with multimaster, the minion tracebacks.

I added tcp to the minion and master configs
```yaml
transport: tcp
```
This works when not using multimaster. 

```bash
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/tornado/ioloop.py", line 567, in _run_callback
    ret = callback()
  File "/usr/lib64/python2.7/site-packages/tornado/stack_context.py", line 274, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/tornado/ioloop.py", line 573, in <lambda>
    self.add_future(ret, lambda f: f.result())
  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 208, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 810, in run
    yielded = self.gen.throw(*sys.exc_info())
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 527, in _connect_minion
    if auth_wait < self.max_auth_wait:
AttributeError: 'MultiMinion' object has no attribute 'max_auth_wait'
2015-07-28 17:10:40,681 [salt.minion      ][ERROR   ][14871] Error while bringing up minion for multi-master. Is master at 45.33.14.39 responding?
2015-07-28 17:10:40,681 [tornado.application][ERROR   ][14871] Exception in callback <functools.partial object at 0x1d87b50>
```

**Comment by cachedout** [comment]
This has nothing to do with Tornado. Multi-master itself is completely non-functional.

**Comment by cachedout** [comment]
@jacksontj It looks like we just forgot to define a var here. Did you have something explicit in mind or shall we just try a few times?

**Comment by jacksontj** [comment]
Fix in #25922 ;) Really need to get those topology tests finished up ;) I know someone was working on that... can't remember for the life of me.

**Comment by cachedout** [comment]
I know the QA guys have that on their list but I'm not sure where they are with it right now.

**Comment by jacksontj** [comment]
Yea, I was chatting with someone about it over IRC-- so they are actively
working on it :)

**Comment by cachedout** [comment]
Fix merged. Closing issue.
