### ISSUE TITLE
artifactory error reporting lacking

### ISSUE THREAD

**Issue by jmdcal** [saltstack/salt#25803]
If the hostname cannot be resolved 

```
log4jaccessvalve_downloaded:
  artifactory.downloaded:
    - { "artifact":  {
          "packaging": "jar",
          "version": "1.0",
          "artifact_id": "Log4jAccessLogValve",
          "repository": "libs-release-local",
          "group_id": "org.something",
          "artifactory_url": "https://bogus:9443"
    }}
    - { "target_file": "/usr/share/java/tomcat/Log4jAccessLogValve.jar"}

```

The error reported is:

```
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 1569, in call
    self.verify_ret(ret)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 797, in verify_ret
    'Malformed state return, return must be a dict' + pprint.pformat(ret)
SaltException: Malformed state return, return must be a dict(None, AttributeError("'URLError' object has no attribute 'code'",))


```

**Comment by jfindlay** [comment]
@jmdcal, thanks for the report.  What is the output of `salt --versions-report`?

**Comment by jmdcal** [comment]
original/develop
commit b3bed2d5d232710d80f218f28b69f52713f68be9
Merge: 6ebc61b 1010eef
Author: original/developJustin Findlay <jfindlay@gmail.com>
Date:   Mon Jul 27 13:34:56 2015 -0600

**Comment by jmdcal** [comment]
relates to this error : #25920
