### ISSUE TITLE
tcp transport problems

### ISSUE THREAD

**Issue by pitatus** [saltstack/salt#25800]
using salt 2015.5.0-1838-gfefb4eb.  one box with master and minion, another remote minion, all running same version and set ``transport: tcp`` in respective config files.

on master minion box when I try to ping minion I get this:
```
[root@master3 ~]# salt '*' test.ping
[ERROR   ] Exception parsing response
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/transport/tcp.py", line 450, in _stream_return
    framed_msg_raw = yield self._stream.read_bytes(int(framed_msg_len.strip()))
ValueError: invalid literal for int() with base 10: 'Some'
[ERROR   ] Exception parsing response
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/transport/tcp.py", line 450, in _stream_return
    framed_msg_raw = yield self._stream.read_bytes(int(framed_msg_len.strip()))
ValueError: invalid literal for int() with base 10: 'exception'
[ERROR   ] Exception parsing response
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/transport/tcp.py", line 450, in _stream_return
    framed_msg_raw = yield self._stream.read_bytes(int(framed_msg_len.strip()))
ValueError: invalid literal for int() with base 10: 'handling'
[ERROR   ] Exception parsing response
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/transport/tcp.py", line 450, in _stream_return
    framed_msg_raw = yield self._stream.read_bytes(int(framed_msg_len.strip()))
ValueError: invalid literal for int() with base 10: 'minion'
invalid literal for int() with base 10: 'Some'
```
the master log on same box:
```
2015-07-28 12:24:57,891 [salt.transport.tcp][ERROR   ][23783] Exception parsing response
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/transport/tcp.py", line 450, in _stream_return
    framed_msg_raw = yield self._stream.read_bytes(int(framed_msg_len.strip()))
ValueError: invalid literal for int() with base 10: 'Some'
2015-07-28 12:24:57,892 [salt.transport.tcp][ERROR   ][23783] Exception parsing response
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/transport/tcp.py", line 450, in _stream_return
    framed_msg_raw = yield self._stream.read_bytes(int(framed_msg_len.strip()))
ValueError: invalid literal for int() with base 10: 'exception'
2015-07-28 12:24:57,892 [salt.transport.tcp][ERROR   ][23783] Exception parsing response
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/transport/tcp.py", line 450, in _stream_return
    framed_msg_raw = yield self._stream.read_bytes(int(framed_msg_len.strip()))
ValueError: invalid literal for int() with base 10: 'handling'
2015-07-28 12:24:57,892 [salt.transport.tcp][ERROR   ][23783] Exception parsing response
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/transport/tcp.py", line 450, in _stream_return
    framed_msg_raw = yield self._stream.read_bytes(int(framed_msg_len.strip()))
ValueError: invalid literal for int() with base 10: 'minion'
2015-07-28 12:24:57,896 [salt.transport.tcp][ERROR   ][23436] Some exception handling a payload from minion
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/transport/tcp.py", line 298, in handle_message
    ret, req_opts = yield self.payload_handler(payload)
  File "/usr/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/site-packages/tornado/gen.py", line 215, in wrapper
    result = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 722, in _handle_payload
    'clear': self._handle_clear}[key](load)
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 736, in _handle_clear
    return getattr(self.clear_funcs, load['cmd'])(load), {'fun': 'send_clear'}
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 1993, in publish
    payload = self._prep_pub(minions, jid, clear_load, extra)
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 2063, in _prep_pub
    self.event.fire_event(new_job_load, tagify([clear_load['jid'], 'new'], 'job'))
  File "/usr/lib/python2.7/site-packages/salt/utils/event.py", line 166, in tagify
    return TAGPARTER.join([part for part in parts if part])
TypeError: sequence item 2: expected string, dict found
```
on the remote minion, running salt-minion in debug, I'm seeing this:
```
[INFO    ] The salt minion is starting up
[INFO    ] Minion is starting as user 'root'
[DEBUG   ] Minion 'f-20' trying to tune in
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'f-20', 'tcp://10.1.45.74:4506')
```
and it doesn't continue, or master doesn't ever notice the attempt.

btw, this remote minion tries to connect via tcp without the ``transport: tcp`` setting in its minion config...

**Comment by cachedout** [comment]
I can't replicate this at all. Can you provide me access to some machines which have this issue?
