### ISSUE TITLE
winpkg highstate fails when a new package name contains a unicide character

### ISSUE THREAD

**Issue by nvx** [saltstack/salt#25810]
Running a highstate on a machine that installs Office 2013, I receive the following error during the highstate:

```python-traceback
    The minion function caused an exception: Traceback (most recent call last):
      File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1146, in _thread_return
        return_data = func(*args, **kwargs)
      File "c:\salt\bin\lib\site-packages\salt\modules\state.py", line 515, in highstate
        whitelist=kwargs.get('whitelist')
      File "c:\salt\bin\lib\site-packages\salt\state.py", line 2971, in call_highstate
        return self.state.call_high(high)
      File "c:\salt\bin\lib\site-packages\salt\state.py", line 2070, in call_high
        ret = dict(list(disabled.items()) + list(self.call_chunks(chunks).items()))
      File "c:\salt\bin\lib\site-packages\salt\state.py", line 1626, in call_chunks
        running = self.call_chunk(low, running, chunks)
      File "c:\salt\bin\lib\site-packages\salt\state.py", line 1880, in call_chunk
        running[tag] = self.call(low, chunks, running)
      File "c:\salt\bin\lib\site-packages\salt\state.py", line 1605, in call
        format_log(ret)
      File "c:\salt\bin\lib\site-packages\salt\state.py", line 209, in format_log
        '{2}\n'.format(pkg, old, new)
    UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 43: ordinal not in range(128)
```

Running the highstate again after the Office 2013 package is installed doesn't give an error. Note Office does install correctly.

Looking at the output of pkg.list_pkgs, I notice the following:

```
    Outils de vérification linguistique 2013 de Microsoft Office - Français:
        15.0.4569.1506
```

I suspect this is what is causing the error due to improper handling of unicode in the log printing.

```
Microsoft Windows Server 2012 R2 Standard
               Salt: 2015.5.2
             Python: 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]
             Jinja2: 2.7.3
           M2Crypto: 0.21.1
     msgpack-python: 0.4.5
       msgpack-pure: Not Installed
           pycrypto: 2.6
            libnacl: Not Installed
             PyYAML: 3.11
              ioflo: Not Installed
              PyZMQ: 14.6.0
               RAET: Not Installed
                ZMQ: 4.0.5
               Mako: Not Installed
```

**Comment by jfindlay** [comment]
@nvx, thanks for the report.

**Comment by cachedout** [comment]
@nvx #25921 fixes this in my testing.

**Comment by cachedout** [comment]
Fix merged. Closing issue.
