### ISSUE TITLE
mongo returner fails with pymongo 3.0.3

### ISSUE THREAD

**Issue by gtmanfred** [saltstack/salt#25841]
because of this line.

https://github.com/saltstack/salt/blob/develop/salt/returners/mongo_return.py#L120

```
    if float(version.split('.')[0]) >= 3 or float(version) > 2.3:
        conn = pymongo.MongoClient(host, port)
    else:
        conn = pymongo.Connection(host, port)
```

I am using this right now, but yall will probably want to fix it in a better way.

Also, it is giving a warning that insert is deprecated.

```
[WARNING ] /usr/lib/python2.7/site-packages/salt/returners/mongo_return.py:155: DeprecationWarning: insert is deprecated. Use insert_one or insert_many instead.
  mdb.saltReturns.insert(sdata)
```

**Comment by gtmanfred** [comment]
This is the error I got, btw.

```
[root@salt salt]# python this.py
Traceback (most recent call last):
  File "this.py", line 41, in <module>
    print(_get_conn())
  File "this.py", line 34, in _get_conn
    conn = pymongo.MongoClient(host, port)
  File "/usr/lib64/python2.7/site-packages/pymongo/mongo_client.py", line 287, in __init__
    raise TypeError("port must be an instance of int")
TypeError: port must be an instance of int
```

**Comment by gtmanfred** [comment]
Also fails for mongo_future_returner.py

**Comment by jfindlay** [comment]
@gtmanfred, thanks for the report.
