### ISSUE TITLE
salt 2015.5.3 salt-cloud provisioner throwing indices must be ints, not str on provision

### ISSUE THREAD

**Issue by RyanHartje** [saltstack/salt#25916]
I am unsure how the problem began, as it was working without issue for the past few months, then yesterday, I don't believe our installation updated but we started receiving this when using salt-cloud to provision on AWS. I see an auth error, however I've copied over the same files to another salt master, on 2015.5.3, and that provisioner works with the same configuration:

```ssh
[ERROR   ] AWS Response Status Code and Error: [401 401 Client Error: Unauthorized] {'Errors': {'Error': {'Message': 'AWS was not able to validate the provided access credentials', 'Code': 'AuthFailure'}}, 'RequestID': 'my_request_uuid'}
[ERROR   ] There was a profile error: string indices must be integers, not str
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/cloud/cli.py", line 254, in run
    self.config.get('names')
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 1391, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 1241, in create
    output = self.clouds[func](vm_)
  File "/usr/lib64/python2.6/contextlib.py", line 34, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.6/site-packages/salt/utils/context.py", line 42, in func_globals_inject
    yield
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 1241, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/ec2.py", line 2153, in create
    data, vm_ = request_instance(vm_, location)
  File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/ec2.py", line 1497, in request_instance
    az_ = get_availability_zone(vm_)
  File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/ec2.py", line 998, in get_availability_zone
    zones = _list_availability_zones()
  File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/ec2.py", line 1099, in _list_availability_zones
    ret[zone['zoneName']] = zone['zoneState']
TypeError: string indices must be integers, not str
```

It may be worth mentioning that I also see the Crypto lib failing for not having a Signature model, but its for provisioners that I would think are unrelated:

```ssh
[root@server salt]# salt-cloud -p m3large server -l debug
[DEBUG   ] Reading configuration from /etc/salt/cloud
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt.cloud.ziften.com
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles
[DEBUG   ] Configuration file path: /etc/salt/cloud
[INFO    ] salt-cloud starting
[DEBUG   ] Failed to import clouds joyent:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/loader.py", line 958, in _load_module
    ), fn_, fpath, desc)
  File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/joyent.py", line 68, in <module>
    from Crypto.Signature import PKCS1_v1_5
ImportError: No module named Signature
[DEBUG   ] Could not LazyLoad parallels.avail_sizes
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy
[DEBUG   ] Could not LazyLoad saltify.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.avail_images
[DEBUG   ] Could not LazyLoad saltify.avail_locations
[DEBUG   ] LazyLoaded rackspace.reboot
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] LazyLoaded rackspace.list_locations
[DEBUG   ] Could not LazyLoad softlayer.optimize_providers
[DEBUG   ] The 'softlayer' cloud driver is unable to be optimized.
[DEBUG   ] Failed to import clouds joyent:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/loader.py", line 958, in _load_module
    ), fn_, fpath, desc)
  File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/joyent.py", line 68, in <module>
    from Crypto.Signature import PKCS1_v1_5
ImportError: No module named Signature
[DEBUG   ] Could not LazyLoad parallels.avail_sizes
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy
[DEBUG   ] Could not LazyLoad saltify.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.avail_images
[DEBUG   ] Could not LazyLoad saltify.avail_locations
[DEBUG   ] LazyLoaded rackspace.reboot
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] LazyLoaded rackspace.list_locations
```

Versions:
```ssh
salt --versions
           Salt: 2015.5.3
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: 2.7.3
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
```

Has anyone else had this issue?

**Comment by RyanHartje** [comment]
Uhoh, turns out it was all my fault, the time on our server wasn't being synced with NTP, and it started failing the authentication. 

I wish there had been something to that effect in the error, but its certainly not a bug of salt, closing.
