### ISSUE TITLE
 Command 'git pull  --tags' failed. Fetching tags only, you probably meant git fetch --tags'

### ISSUE THREAD

**Issue by jmdcal** [saltstack/salt#25969]
salt-run --version
salt-run 2015.8.0rc2-812-gabf3897 (Beryllium)

git --version
git version 1.8.3.1

Given this state
```
example :
  git.latest:
  - {rev: develop }
  - {target: "/home/jenkins/build/FOOBAR/EX-BAZ" }
  - {name: "ssh://git@stash.FOOBAR.org:2222/EX/BAZ.git" }
```

Here is the debug log:
```
[INFO    ] Running state [ssh://git@stash.FOOBAR.org:2222/EX/BAZ.git] at time 12:31:29.973909
[INFO    ] Executing state git.latest for ssh://git@stash.FOOBAR.org:2222/EX/BAZ.git
[DEBUG   ] target /home/jenkins/build/FOOBAR/EX-BAZ is found, "git pull" is probably required
[INFO    ] Executing command 'git rev-parse HEAD' in directory '/home/jenkins/build/FOOBAR/EX-BAZ'
[DEBUG   ] stdout: fd040047b7fc74b4ff643827887a03f736397ede
[INFO    ] Executing command 'git rev-parse --abbrev-ref HEAD' in directory '/home/jenkins/build/FOOBAR/EX-BAZ'
[DEBUG   ] stdout: develop
[INFO    ] Executing command 'git ls-remote -h ssh://git@stash.FOOBAR.org:2222/EX/BAZ.git develop | cut -f 1' in directory '/home/jenkins/build/FOOBAR/EX-BAZ'
[DEBUG   ] stdout: 181c1922447646321711b8d786109ed123e830a8     refs/heads/develop
[INFO    ] Executing command 'git remote show -n origin' in directory '/home/jenkins/build/FOOBAR/EX-BAZ'
[DEBUG   ] stdout: * remote origin
  Fetch URL: ssh://git@stash.FOOBAR.org:2222/EX/BAZ.git
  Push  URL: ssh://git@stash.FOOBAR.org:2222/EX/BAZ.git
  HEAD branch: (not queried)
  Remote branches: (status not queried)
    EX-230
    bugfix/EX-145
    bugfix/EX-accounts
    bugfix/undo_feature_EX131userAttibJSON
    develop
    feature/EX-116
    feature/EX-207
    feature/EX131AuditFieldsNew
    feature/EX131Schemachanges
    feature/logback2
    feature/mergeSriCode
    feature/oaam
    feature/setup
    feature/EX-66-67
    feature/uploadChanges
    feature/useFlyway
    feature/userUpload
    master
  Local branch configured for 'git pull':
    develop merges with remote develop
  Local ref configured for 'git push' (status not queried):
    (matching) pushes to (matching)
[INFO    ] Executing command 'git rev-parse develop^{commit}' in directory '/home/jenkins/build/FOOBAR/EX-BAZ'
[DEBUG   ] output: fd040047b7fc74b4ff643827887a03f736397ede
[INFO    ] Executing command 'git checkout  develop ' in directory '/home/jenkins/build/FOOBAR/EX-BAZ'

[DEBUG   ] stderr: Already on 'develop'
[INFO    ] Executing command 'git config branch.develop.remote' in directory '/home/jenkins/build/FOOBAR/EX-BAZ'
[DEBUG   ] stdout: origin
[INFO    ] Executing command 'git symbolic-ref -q HEAD' in directory '/home/jenkins/build/FOOBAR/EX-BAZ'
[DEBUG   ] output: refs/heads/develop
[INFO    ] Executing command 'git pull  --tags' in directory '/home/jenkins/build/FOOBAR/EX-BAZ'
[ERROR   ] Command 'git pull  --tags' failed with return code: 1
[ERROR   ] stderr: From ssh://stash.FOOBAR.org:2222/EX/BAZ
 * [new tag]         0.94.0     -> 0.94.0
Fetching tags only, you probably meant:
  git fetch --tags
[ERROR   ] retcode: 1
[ERROR   ] Unexpected exception in git state
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/states/git.py", line 332, in latest
    target, opts=fetch_opts, user=user, identity=identity)
  File "/usr/lib/python2.7/site-packages/salt/modules/git.py", line 354, in pull
    identity=identity)
  File "/usr/lib/python2.7/site-packages/salt/modules/git.py", line 82, in _git_run
    result['stderr']))
CommandExecutionError: Command 'git pull  --tags' failed. Stderr: 'From ssh://stash.FOOBAR.org:2222/EX/BAZ\n * [new tag]         0.94.0     -> 0.94.0\nFetching tags only, you probably \
meant:\n  git fetch --tags'
[ERROR   ] Command 'git pull  --tags' failed. Stderr: 'From ssh://stash.FOOBAR.org:2222/EX/BAZ\n * [new tag]         0.94.0     -> 0.94.0\nFetching tags only, you probably meant:\n  gi\
t fetch --tags'
[INFO    ] Completed state [ssh://git@stash.FOOBAR.org:2222/EX/BAZ.git] at time 12:31:37.797014
[DEBUG   ] LazyLoaded cmd.run
[INFO    ] Running state [mvn -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true clean package] at time 12:31:37.798798
[INFO    ] Executing state cmd.run for mvn -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true clean package
```
Getting this error 
```
     Comment: Command 'git pull  --tags' failed. Stderr: 'From ssh://stash.FOOBAR.org:2222/EX/BAZ\n * [new tag]         0.94.0     -> 0.94.0\nFetching tags only, you probably meant:\n \
 git fetch --tags'
```

**Comment by jfindlay** [comment]
@jmdcal, thanks for the report.

**Comment by jmdcal** [comment]
Workaround is:  
fetch_tags:False

```
example :
  git.latest:
  - {rev: develop }
  - {fetch_tags:False }
  - {target: "/home/jenkins/build/FOOBAR/EX-BAZ" }
  - {name: "ssh://git@stash.FOOBAR.org:2222/EX/BAZ.git" }
```

**Comment by cachedout** [comment]
cc: @terminalmage

**Comment by terminalmage** [comment]
Fixed in https://github.com/saltstack/salt/pull/26341 by specifying multiple refspecs when ``fetch_tags is True``.

**Comment by terminalmage** [comment]
Whoops, wrong fix... The fix (part of the same pull request) was to stop using pulls altogether and instead do a fetch and merge. Furthermore, the logic is now smart enough to know whether it needs to even do a fetch/merge.
