### ISSUE TITLE
salt-minion on openSuSE 13.2

### ISSUE THREAD

**Issue by pitatus** [saltstack/salt#25985]
running latest develop, ``salt-minion 2015.8.0-199-gabf3897 (Beryllium)``.  When running minion in debug mode it appears to work, however when I load with ``-d`` I get this:
```python-traceback
# salt-minion --daemon
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 261, in _bootstrap
    util._exit_function()
  File "/usr/lib64/python2.7/multiprocessing/util.py", line 325, in _exit_function
    p.join()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 143, in join
    assert self._parent_pid == os.getpid(), 'can only join a child process'
AssertionError: can only join a child process
```
Pressing ``^C`` to get console back I see this:
```python-traceback
^CProcess Process-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 261, in _bootstrap
    util._exit_function()
  File "/usr/lib64/python2.7/multiprocessing/util.py", line 325, in _exit_function
    p.join()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 145, in join
    res = self._popen.wait(timeout)
  File "/usr/lib64/python2.7/multiprocessing/forking.py", line 154, in wait
    return self.poll(0)
  File "/usr/lib64/python2.7/multiprocessing/forking.py", line 135, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
```
however salt-minion is still running:
```
 2249 ?        Sl     0:00 /usr/bin/python2 /usr/bin/salt-minion --daemon
```
and still responded to a ``test.ping``

**Comment by terminalmage** [comment]
Can reproduce this on FreeBSD as well.

**Comment by terminalmage** [comment]
This is the same as https://github.com/saltstack/salt/issues/26672, and though this issue was opened first, there is more information and discussion in the other issue, so I'm going to close this as a duplicate.
