### ISSUE TITLE
Jinja renderer error messages gets worse and worse ... ^^

### ISSUE THREAD

**Issue by Reiner030** [saltstack/salt#26043]
a) salt cannot use the "environment" variable setup in minion config file ... thats a pity... 
b) so I have to set it manually in grains (because cloud distribution is not working for grains...)

Today i had to reused an older saltstack setup which hasn't yet setup functions for missed default variables... so I run into this very "clear" error:

```
[INFO    ] Running state [/etc/default/tomcat8-p1003] at time 13:43:24.680359
[INFO    ] Executing state file.managed for /etc/default/tomcat8-p1003
[INFO    ] Fetching file from saltenv 'prod', ** skipped ** latest already in cache 'salt://tomcat/templates/default-tomcat8.jinja'
[DEBUG   ] Jinja search path: ['/var/cache/salt/minion/files/prod']
[DEBUG   ] Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 1459, in managed
    **kwargs
  File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 2841, in get_managed
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 121, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 324, in render_jinja_tmpl
    buf=tmplstr)
SaltRenderError: Jinja variable No first item, sequence was empty.

[ERROR   ] Unable to manage file: Jinja variable No first item, sequence was empty.
[INFO    ] Completed state [/etc/default/tomcat8-p1003] at time 13:43:24.702485
```

_SaltRenderError: Jinja variable No first item, sequence was empty._

Luckily I found with some research this:
http://jinja.pocoo.org/docs/dev/api/

```
For a more complex example you can provide a hint. 
For example the first() filter creates an undefined object that way:

        return environment.undefined('no first item, sequence was empty')

```

In older versions I got an error message that e.g. "environment" variable is not defined.

It would be nice to have some better error messages for Jinja rendering which clarifies what the real problem is. I guess thats not easy because you can only give out what you get in from rendering, but perhaps something like this is possible?:

```
SaltRenderError in salt/base/tomcat/templates/default-tomcat8.jinja line 43; variable "environment": Jinja variable No first item, sequence was empty.
or
SaltRenderError in salt/base/tomcat/templates/default-tomcat8.jinja line 43: Jinja variable No first item, sequence was empty.
or
SaltRenderError in salt/base/tomcat/templates/default-tomcat8.jinja: Jinja variable No first item, sequence was empty.
```

```
✗ lsb_release -d
Description:    Debian GNU/Linux 8.1 (jessie)
✗ salt-call --version
salt-call 2015.5.3 (Lithium)
```

Bests

**Comment by jfindlay** [comment]
@Reiner030, those are good suggestions, thanks for the report.
