### ISSUE TITLE
problem with reactors when handling event corresponding to a job that raises an exception

### ISSUE THREAD

**Issue by yannis666** [saltstack/salt#26046]
I have a reactor.conf like so:
```
reactor:
  - 'salt/job/*/ret/*':
    - /srv/salt/reactor/lcm_orchestrator_salt.sls
```
When a salt job throws an exception, it generates an event of the form:
```
2015-08-05 19:28:12,905 [salt.utils.event                         ][DEBUG   ][1051] Sending event - data = {'fun_args': ['raise'], 'jid': '20150805192812857271', 'return': 'The minion function caused an exception: Traceback (most recent call last):\n  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 1161, in _thread_return\n   return_data = func(*args, **kwargs)\n  File "/var/cache/salt/minion/extmods/modules/lcm_test.py", line 37, in echo_raise\n    raise ValueError("Exception: " + str(data))\nValueError: Exception: raise\n', 'success': False, 'cmd': '_return', '_stamp': '2015-08-05T19:28:12.904754', 'fun': 'lcm_test.echo_raise', 'id': 'pod-minion-aus-jsf-admin', 'out': 'nested'}
```
Note that this event is generated by the salt infra, and that the 'return' contains a Traceback and one or more ':'.
This causes a new exception when the reactor is invoked - I assume because of the embedded ':' in the event

```
2015-08-05 19:28:12,913 [salt.utils.reactor                                 ][ERROR   ][1039] Failed to render "/
srv/salt/reactor/lcm_orchestrator_salt.sls":
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/utils/reactor.py", line 53, in render_reaction
    data=data)
  File "/usr/lib/python2.6/site-packages/salt/state.py", line 257, in render_template
    template, self.rend, self.opts['renderer'], **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/template.py", line 79, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/usr/lib/python2.6/site-packages/salt/renderers/yaml.py", line 54, in render
    raise SaltRenderError(err_type, line_num, exc.problem_mark.buffer)
SaltRenderError: mapping values are not allowed here; line 8

---
[...]
    - args:
      - pod-minion-aus-jsf-admin
      - 20150805192812857271
      - None
      - lcm_test.echo_raise
      - The minion function caused an exception: Traceback (most recent call last):    <======================
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 1161, in _thread_return
    return_data = func(*args, **kwargs)
  File "/var/cache/salt/minion/extmods/modules/lcm_test.py", line 37, in echo_raise
    raise ValueError("Exception: " + str(data))
ValueError: Exception: raise
[...]
---
```

**Comment by jfindlay** [comment]
@yannis666, thanks for the report.

**Comment by cachedout** [comment]
I actually think this is expected behavior. We've caught the exception returned from the minion, put it in the master error log and continued on our way. I don't really like hiding or massaging exceptions like this, since often it just makes it harder to diagnose the issue.
