### ISSUE TITLE
Pyobjects renderer fails when optionally available states used

### ISSUE THREAD

**Issue by grischa** [saltstack/salt#26151]
E.g. a `Git.config` entry fails rendering of the SLS file because git is not installed, even when it has `Pkg.installed('git')` above and as argument `require=[Pkg('git')]`.

This is tested to be the case with versions 2015.5.3, 2015.8 and develop.
All I could find on this is issue #10918 which was closed, but for an unexplained reason, I didn't see reference to a fix.

If this is impossible to fix, please consider deprecating pyobjects. I don't see any value in a renderer that needs manual installation of packages in order to work...

**Comment by jfindlay** [comment]
@grischa, thanks for the report, this is definitely a bug.

**Comment by favadi** [comment]
I add additional info to this bug.

Test state:

```
Pkg.latest('git')
Git.present('/tmp/git-repo',
               require=[Pkg('git'),],)
```

Error:

```
local:
    Data failed to compile:
----------
    Rendering SLS test failed, render error: name 'Git' is not defined
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2509, in render_state
    sls, rendered_sls=mods
  File "/usr/lib/python2.7/dist-packages/salt/template.py", line 79, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/renderers/pyobjects.py", line 435, in render
    exec_(final_template, _globals)
  File "/usr/lib/python2.7/dist-packages/salt/ext/six.py", line 645, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "<string>", line 5, in <module>
NameError: name 'Git' is not defined
```

Salt version:

```
root@salt-dev:~# salt-minion --versions-report
                  Salt: 2015.5.3
                Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: Not Installed
               Tornado: 4.2.1
 Debian source package: 2015.5.3+ds-1trusty1
```
