### ISSUE TITLE
state.show_sls fails on new winrepo + jinja sls files

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt#26174]
The new winrepo sls files can now contain jinja and do get rendered properly. Thanks @jfindlay.

But I just cannot figure how to use ```state.show_sls my-sls-file``` to see the final rendered output.

As-is, it gives a whole slurr of errors as follows:
```salt-call --local win.repo.ccleaner```

```python-traceback
C:\salt\srv\salt\win\repo>salt-call --local state.show_sls win.repo.ccleaner
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** done ** 'win/repo/ccleaner.sls'
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'float' object has no attribute 'startswith'
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\python27\scripts\salt-call.exe\__main__.py", line 9, in <module>
    sys.exit(salt_call())
  File "C:\Python27\lib\site-packages\salt\scripts.py", line 227, in salt_call
    client.run()
  File "C:\Python27\lib\site-packages\salt\cli\call.py", line 69, in run
    caller.run()
  File "C:\Python27\lib\site-packages\salt\cli\caller.py", line 236, in run
    ret = self.call()
  File "C:\Python27\lib\site-packages\salt\cli\caller.py", line 138, in call
    ret['return'] = func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\salt\modules\state.py", line 980, in show_sls
    high_, errors = st_.render_highstate({saltenv: mods})
  File "C:\Python27\lib\site-packages\salt\state.py", line 2808, in render_highstate
    sls, saltenv, mods, matches)
  File "C:\Python27\lib\site-packages\salt\state.py", line 2548, in render_state
    self._handle_state_decls(state, sls, saltenv, errors)
  File "C:\Python27\lib\site-packages\salt\state.py", line 2704, in _handle_state_decls
    if key.startswith('_'):
AttributeError: 'float' object has no attribute 'startswith'
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\python27\scripts\salt-call.exe\__main__.py", line 9, in <module>
  File "C:\Python27\lib\site-packages\salt\scripts.py", line 227, in salt_call
    client.run()
  File "C:\Python27\lib\site-packages\salt\cli\call.py", line 69, in run
    caller.run()
  File "C:\Python27\lib\site-packages\salt\cli\caller.py", line 236, in run
    ret = self.call()
  File "C:\Python27\lib\site-packages\salt\cli\caller.py", line 138, in call
    ret['return'] = func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\salt\modules\state.py", line 980, in show_sls
    high_, errors = st_.render_highstate({saltenv: mods})
  File "C:\Python27\lib\site-packages\salt\state.py", line 2808, in render_highstate
    sls, saltenv, mods, matches)
  File "C:\Python27\lib\site-packages\salt\state.py", line 2548, in render_state
    self._handle_state_decls(state, sls, saltenv, errors)
  File "C:\Python27\lib\site-packages\salt\state.py", line 2704, in _handle_state_decls
    if key.startswith('_'):
AttributeError: 'float' object has no attribute 'startswith'
```

If I add `#!yaml` to the first line, I get 
```
C:\salt\srv\salt\win\repo>salt-call --local state.show_sls win.repo.ccleaner
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** done ** 'win/repo/ccleaner.sls'
[CRITICAL] Rendering SLS 'base:win.repo.ccleaner' failed: found character '%' that cannot start any token; line 3

---saltstack
#!yaml
# just 32-bit x86 installer available
{% if grains['cpuarch'] == 'AMD64' %}    <======================
    {% set PROGRAM_FILES = "C:\Program Files (x86)" %}
{% else %}
    {% set PROGRAM_FILES = "C:\Program Files" %}
{% endif %}
ccleaner:
[...]
---
local:
    - Rendering SLS 'base:win.repo.ccleaner' failed: found character '%' that cannot start any token; line 3
    -
    - ---
    - #!yaml
    - # just 32-bit x86 installer available
    - {% if grains['cpuarch'] == 'AMD64' %}    <======================
    -     {% set PROGRAM_FILES = "C:\Program Files (x86)" %}
    - {% else %}
    -     {% set PROGRAM_FILES = "C:\Program Files" %}
    - {% endif %}
    - ccleaner:
    - [...]
    - ---
```

And if I add a first line of `#!jinja` it gives me:

```
C:\salt\srv\salt\win\repo>salt-call --local state.show_sls win.repo.ccleaner
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** done ** 'win/repo/ccleaner.sls'
local:
    - SLS win.repo.ccleaner does not render to a dictionary

C:\salt\srv\salt\win\repo>
```

The ```ccleaner.sls``` comes from salt-winrepo's WIP_Berryllium+jinja branch. (https://github.com/saltstack/salt-winrepo/blob/WIP_Berryllium%2Bjinja/ccleaner.sls)

```salt-call --versions``` is:

```yaml
C:\salt\srv\salt\win\repo>salt-call --local --versions
           Salt: 2015.5.3
         Python: 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]
         Jinja2: 2.8
       M2Crypto: Not Installed
 msgpack-python: 0.4.6
   msgpack-pure: 0.1.3
       pycrypto: 2.6.1
        libnacl: 1.4.3
         PyYAML: 3.11
          ioflo: 1.3.8
          PyZMQ: 14.7.0
           RAET: 0.6.3
            ZMQ: 4.1.2
           Mako: 1.0.1
        Tornado: 4.2.1
```
@jfindlay @twangboy @UtahDave any idea what it takes to enable ```state.show_sls``` to work on the new jinja allowed/included style winrepo sls files?

**Comment by jfindlay** [comment]
@TheBigBear, you should actually be thanking @UtahDave.  Your jinja looks valid to me.  I am unsure why it is erroring on your package file.

**Comment by twangboy** [comment]
@TheBigBear The state renderer looks for a very specific data structure that state files adhere to. The winrepo doesn't follow the same data structure. We're going to build something similar to the state.show_sls function for viewing rendered winrepo .sls files. I hope to have that done this week.

**Comment by twangboy** [comment]
@TheBigBear I submitted a PR for a new function that will display the rendered software definitions. Let me know how it works for you.

**Comment by TheBigBear** [comment]
@twangboy sorry, took me a while to get to a stable enough setup on 2015.8 to even retry this.

I think we are closer now, but somehow looks like we are not quite there, yet. ;-( maybe you need to re-open https://github.com/saltstack/salt/issues/26174 ?

I am running ```salt-call state.show_sls win.repo-ng.000e661be672f0e9cecb4c2ebecb348f.npp``` on a windows minion ver. ```2015.8.0rc3-189-g8cdf75c (Beryllium)```
and get:
```
C:\Salt-Dev>salt-call state.show_sls win.repo-ng.000e661be672f0e9cecb4c2ebecb348
f.npp
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in ca
che u'salt://win/repo-ng/000e661be672f0e9cecb4c2ebecb348f/npp.sls'
[ERROR   ] An un-handled exception was caught by salt's global exception handler
:
AttributeError: 'float' object has no attribute 'startswith'
Traceback (most recent call last):
  File "C:\Python27\Scripts\salt-call-script.py", line 9, in <module>
    load_entry_point('salt===2015.8.0rc3-189-g8cdf75c', 'console_scripts', 'salt
-call')()
  File "c:\salt-dev\salt\salt\scripts.py", line 331, in salt_call
    client.run()
  File "c:\salt-dev\salt\salt\cli\call.py", line 51, in run
    caller.run()
  File "c:\salt-dev\salt\salt\cli\caller.py", line 133, in run
    ret = self.call()
  File "c:\salt-dev\salt\salt\cli\caller.py", line 196, in call
    ret['return'] = func(*args, **kwargs)
  File "c:\salt-dev\salt\salt\modules\state.py", line 1019, in show_sls
    high_, errors = st_.render_highstate({saltenv: mods})
  File "c:\salt-dev\salt\salt\state.py", line 2943, in render_highstate
    sls, saltenv, mods, matches)
  File "c:\salt-dev\salt\salt\state.py", line 2671, in render_state
    self._handle_state_decls(state, sls, saltenv, errors)
  File "c:\salt-dev\salt\salt\state.py", line 2839, in _handle_state_decls
    if key.startswith('_'):
AttributeError: 'float' object has no attribute 'startswith'
Traceback (most recent call last):
  File "C:\Python27\Scripts\salt-call-script.py", line 9, in <module>
    load_entry_point('salt===2015.8.0rc3-189-g8cdf75c', 'console_scripts', 'salt
-call')()
  File "c:\salt-dev\salt\salt\scripts.py", line 331, in salt_call
    client.run()
  File "c:\salt-dev\salt\salt\cli\call.py", line 51, in run
    caller.run()
  File "c:\salt-dev\salt\salt\cli\caller.py", line 133, in run
    ret = self.call()
  File "c:\salt-dev\salt\salt\cli\caller.py", line 196, in call
    ret['return'] = func(*args, **kwargs)
  File "c:\salt-dev\salt\salt\modules\state.py", line 1019, in show_sls
    high_, errors = st_.render_highstate({saltenv: mods})
  File "c:\salt-dev\salt\salt\state.py", line 2943, in render_highstate
    sls, saltenv, mods, matches)
  File "c:\salt-dev\salt\salt\state.py", line 2671, in render_state
    self._handle_state_decls(state, sls, saltenv, errors)
  File "c:\salt-dev\salt\salt\state.py", line 2839, in _handle_state_decls
    if key.startswith('_'):
AttributeError: 'float' object has no attribute 'startswith'
```

or if i run the same thing on the master as ```salt 'om-uk-w*' state.show_sls win.repo-ng.000e661be672f0e9cecb4c2ebecb348f.npp```

I get the followiong 3 identical replies from my windows minions on win 7 pro, win 8..1 pro and win 10 pro (which to me looks like the same problem - i get on the windows minion itself as shown above)

```
om-uk-w10-1-64:
    The minion function caused an exception: Traceback (most recent call last):
      File "c:\salt-dev\salt\salt\minion.py", line 1004, in _thread_return
        return_data = func(*args, **kwargs)
      File "c:\salt-dev\salt\salt\modules\state.py", line 1019, in show_sls
        high_, errors = st_.render_highstate({saltenv: mods})
      File "c:\salt-dev\salt\salt\state.py", line 2943, in render_highstate
        sls, saltenv, mods, matches)
      File "c:\salt-dev\salt\salt\state.py", line 2671, in render_state
        self._handle_state_decls(state, sls, saltenv, errors)
      File "c:\salt-dev\salt\salt\state.py", line 2839, in _handle_state_decls
        if key.startswith('_'):
    AttributeError: 'float' object has no attribute 'startswith'
om-uk-w7-1-64:
    The minion function caused an exception: Traceback (most recent call last):
      File "c:\salt-dev\salt\salt\minion.py", line 1004, in _thread_return
        return_data = func(*args, **kwargs)
      File "c:\salt-dev\salt\salt\modules\state.py", line 1019, in show_sls
        high_, errors = st_.render_highstate({saltenv: mods})
      File "c:\salt-dev\salt\salt\state.py", line 2943, in render_highstate
        sls, saltenv, mods, matches)
      File "c:\salt-dev\salt\salt\state.py", line 2671, in render_state
        self._handle_state_decls(state, sls, saltenv, errors)
      File "c:\salt-dev\salt\salt\state.py", line 2839, in _handle_state_decls
        if key.startswith('_'):
    AttributeError: 'float' object has no attribute 'startswith'
om-uk-w81-1-64:
    The minion function caused an exception: Traceback (most recent call last):
      File "c:\salt-dev\salt\salt\minion.py", line 1004, in _thread_return
        return_data = func(*args, **kwargs)
      File "c:\salt-dev\salt\salt\modules\state.py", line 1019, in show_sls
        high_, errors = st_.render_highstate({saltenv: mods})
      File "c:\salt-dev\salt\salt\state.py", line 2943, in render_highstate
        sls, saltenv, mods, matches)
      File "c:\salt-dev\salt\salt\state.py", line 2671, in render_state
        self._handle_state_decls(state, sls, saltenv, errors)
      File "c:\salt-dev\salt\salt\state.py", line 2839, in _handle_state_decls
        if key.startswith('_'):
    AttributeError: 'float' object has no attribute 'startswith'
```

**Comment by twangboy** [comment]
@TheBigBear By using `state.show_sls` you're running it through the state renderer. We added a new function to the `winrepo` module to display the rendered defnition. Try using `winrepo.show_sls` instead. Let me know if there are still problems with it.

**Comment by TheBigBear** [comment]
@twangboy OK, I think I am really thick I can't see which we around I would have to call this up for it to give me the rendered output.

Here follows the log of what I see and get on the linux master, sorry this is soo long.

So first I do a winrepo.git_repos_update to get the latest sls files  from git onto the master.

```
# salt-call winrepo.update_git_repos
[ERROR   ] You should upgrade pyOpenSSL to at least 0.14.1 to enable the use of X509 extensions
'winrepo.update_git_repos' is not available.
# salt-run winrepo.update_git_repos
https://github.com/saltstack/salt-winrepo-ng.git:
    /srv/salt/win/repo-ng/000e661be672f0e9cecb4c2ebecb348f
https://github.com/saltstack/salt-winrepo.git:
    /srv/salt/win/repo/f42c3382aeeaa8733908e5c256dba1ca
```

I guess my separate question on this one is? Should I open a ticket for the pyOpenSSLError? Or is that an Error that isn't really one?

Then to be honest, on the master I am not sure if I should do a 'salt-run' or 'salt-call' winrepo.show_sls, so I try both. ;-)

```
# salt-call winrepo.show_sls win.repo-ng.000e661be672f0e9cecb4c2ebecb348f.npp
[ERROR   ] You should upgrade pyOpenSSL to at least 0.14.1 to enable the use of X509 extensions
'winrepo.show_sls' is not available.
```
So I guess, it should be a ```salt-run``` instead? (or is the pyOpenSSL 'hiding' the winrepo.show_sls?)

```
# salt-run winrepo.show_sls win.repo-ng.000e661be672f0e9cecb4c2ebecb348f.npp
'winrepo.show_sls' is not available.
```
then I start guessing and clutching at straws ....
```
# salt 'om-uk*w*' winrepo.show_sls win.repo-ng.000e661be672f0e9cecb4c2ebecb348f.npp
om-uk-w7-1-64:
    Software definition win.repo-ng.000e661be672f0e9cecb4c2ebecb348f.npp not found
om-uk-w10-1-64:
    Software definition win.repo-ng.000e661be672f0e9cecb4c2ebecb348f.npp not found
om-uk-w81-1-64:
    Software definition win.repo-ng.000e661be672f0e9cecb4c2ebecb348f.npp not found
You have new mail in /var/spool/mail/root
# salt 'om-uk*w*' winrepo.show_sls win.repo-ng.salt-winrepo-ng.npp
om-uk-w7-1-64:
    Software definition win.repo-ng.salt-winrepo-ng.npp not found
om-uk-w81-1-64:
    Software definition win.repo-ng.salt-winrepo-ng.npp not found
om-uk-w10-1-64:
    Software definition win.repo-ng.salt-winrepo-ng.npp not found
# salt 'om-uk*w*' winrepo.show_sls win.repo.salt-winrepo.npp
om-uk-w7-1-64:
    Software definition win.repo.salt-winrepo.npp not found
om-uk-w81-1-64:
    Software definition win.repo.salt-winrepo.npp not found
om-uk-w10-1-64:
    Software definition win.repo.salt-winrepo.npp not found
```

;-(  Oh, so that is also not available? So can I not show/display the rendered sls file from the master?
Or how do I refer to it?

I could post all the output I got on the windows minion, but I'd rather not, especially as some fo that may (or may not) raise more questions and possible bugs. But I'd rather first now, how do I get to see the winrepo.show_sls on the mastewr and how am I supposed to display it on the minion?

And after I know how it should work, I may then have to report more issues, but hopefully it is just me being thick on this one.

Thanks for any hints.

**Comment by twangboy** [comment]
@TheBigBear So, it starts in the winrepo root, so you don't have to put `win.repo-ng`. I was able to pull mine by something like the following:
```
salt-call --local winrepo.show_sls 000e661be672f0e9cecb4c2ebecb348f.7zip
```
Having to put that big ugly string of characters in though is a little rediculous. I'm going to talk to @UtahDave and see if we can't get it to be something that makes more sense.

**Comment by TheBigBear** [comment]
@twangboy. OK, thanks, so it is the pyOpenSSL error msg that hides or obstructs it for me.
I get
```
ls /srv/salt/win/repo-ng/
000e661be672f0e9cecb4c2ebecb348f  remote_map.txt (note: just making sure and showing that my hash is the same. )

# salt-call --local winrepo.show_sls 000e661be672f0e9cecb4c2ebecb348f.7zip
[ERROR   ] You should upgrade pyOpenSSL to at least 0.14.1 to enable the use of X509 extensions
'winrepo.show_sls' is not available.

# salt-call --local winrepo.show_sls 000e661be672f0e9cecb4c2ebecb348f.npp
[ERROR   ] You should upgrade pyOpenSSL to at least 0.14.1 to enable the use of X509 extensions
'winrepo.show_sls' is not available.
```
Shall I open a new issue for that one then? Or can it be fixed as part of this ?

**Comment by TheBigBear** [comment]
@twangboy this is on a centos 7.1 

```
yum install pyOpenSSL
Package pyOpenSSL-0.13.1-3.el7.x86_64 already installed and latest version
Nothing to do 
```

**Comment by twangboy** [comment]
@TheBigBear I don't know about the PyOpenSSL thing.... let me research that a little... see if I can reproduce.

**Comment by twangboy** [comment]
It looks like you're on the server. I don't know what the winrepo root would be on the file server. Which one does it get, ng or non-ng?

**Comment by twangboy** [comment]
@TheBigBear The `show_sls` function resides in `win_repo.py` which is only available on windows. I was able to do this on the master:

```
salt 't*' winrepo.show_sls 000e661be672f0e9cecb4c2ebe cb348f.7zip
```

**Comment by TheBigBear** [comment]
@twangboy on the centos 7.1 linux server it got both ```/srv/salt/win/repo``` and ```/srv/salt/win/repo-ng``` [and on the windows minion the git repos are in 'c:\salt\srv\salt\win'] if your cmd was supposed to run on the windows minion, then it does not render for me on my windows minion. 
any special/extra config assumed on the windows minion?

**Comment by twangboy** [comment]
@TheBigBear I don't have any extra config. It's just using defaults. My winrepo is at: `C:\salt\var\cache\salt\minion\files\base\win\repo-ng`
I'll check my config file.

**Comment by TheBigBear** [comment]
@twangboy and if I try that I get:
```
salt 'om-uk*w*' winrepo.show_sls 000e661be672f0e9cecb4c2ebe cb348f.7zip
om-uk-w7-1-64:
    Software definition 000e661be672f0e9cecb4c2ebe not found
om-uk-w81-1-64:
    Software definition 000e661be672f0e9cecb4c2ebe not found
om-uk-w10-1-64:
    Software definition 000e661be672f0e9cecb4c2ebe not found

# salt 'om-uk*w*' winrepo.show_sls salt-winrepo-ng_git cb348f.7zip
om-uk-w7-1-64:
    Software definition salt-winrepo-ng_git not found
om-uk-w81-1-64:
    Software definition salt-winrepo-ng_git not found
om-uk-w10-1-64:
    Software definition salt-winrepo-ng_git not found
```

Do you have ```pygit2`` installed on your windows minion? My git repos on the windows client is under
```c:\salt\srv\salt\win\repo-ng\salt-winrepo-ng_git```

**Comment by twangboy** [comment]
@TheBigBear that space shouldn't be in there... that was a wrap on my command prompt...

**Comment by twangboy** [comment]
@TheBigBear I edited the command in the original comment...

**Comment by TheBigBear** [comment]
dohh! Ok, now I get some rendering. Thanks.

**Comment by twangboy** [comment]
I don't have pygit2 installed.

**Comment by TheBigBear** [comment]
@twangboy. OK, I think we are good now. I can now render it on the windows minion as well as on the linux master. Thanks.

**Comment by twangboy** [comment]
@TheBigBear How do you render on the master? What command are you using? Which winrepo is it grabbing? Do you specify the full path? Are you using salt-call or salt-run?

**Comment by TheBigBear** [comment]
@twangboy sorry probably confusing language, but I issue the 
```salt-call 'windows-minion-target' winrepo.show_sls 000e661be672f0e9cecb4c2ebecb348f.7zip```
same as you did above.
The exact cmd in my case is:
```salt 'om-uk*w*' winrepo.show_sls 000e661be672f0e9cecb4c2ebecb348f.7zip```

and the return is:

```
om-uk-w81-1-64:
    ----------
    7zip:
        ----------
        9.20.00.0:
            ----------
            full_name:
                7-Zip 9.20 (x64 edition)
            install_flags:
                /qn /norestart
            installer:
                http://heanet.dl.sourceforge.net/project/sevenzip/7-Zip/9.20/7z920-x64.msi
            locale:
                en_US
            msiexec:
                True
            reboot:
                False
            uninstall_flags:
                /qn /norestart
            uninstaller:
                http://heanet.dl.sourceforge.net/project/sevenzip/7-Zip/9.20/7z920-x64.msi
om-uk-w10-1-64:
    ----------
    7zip:
        ----------
        9.20.00.0:
            ----------
            full_name:
                7-Zip 9.20 (x64 edition)
            install_flags:
                /qn /norestart
            installer:
                http://heanet.dl.sourceforge.net/project/sevenzip/7-Zip/9.20/7z920-x64.msi
            locale:
                en_US
            msiexec:
                True
            reboot:
                False
            uninstall_flags:
                /qn /norestart
            uninstaller:
                http://heanet.dl.sourceforge.net/project/sevenzip/7-Zip/9.20/7z920-x64.msi
om-uk-w7-1-64:
    ----------
    7zip:
        ----------
        9.20.00.0:
            ----------
            full_name:
                7-Zip 9.20 (x64 edition)
            install_flags:
                /qn /norestart
            installer:
                http://heanet.dl.sourceforge.net/project/sevenzip/7-Zip/9.20/7z920-x64.msi
            locale:
                en_US
            msiexec:
                True
            reboot:
                False
            uninstall_flags:
                /qn /norestart
            uninstaller:
                http://heanet.dl.sourceforge.net/project/sevenzip/7-Zip/9.20/7z920-x64.msi
```
