### ISSUE TITLE
salt minion grains not working with compound 

### ISSUE THREAD

**Issue by mimianddaniel** [saltstack/salt#26191]
minions stopped responding to the grain matching with compount setting after restart :  
Simple grain matching works, grains.items works.. but using -C, compound doesnt.  After restart of the minions it works fine then the following error, it stops working with the compound. 

We have grains_cache enabled which seems to be the cause of this issue.  I will disable and see if that fixes the problem. 

``` python-traceback
[DEBUG   ] Exception while handling events
Traceback (most recent call last):
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/minion.py", line 1952, in _do_event_poll
    self.handle_event(package)
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/minion.py", line 1696, in handle_event
    self.pillar_refresh(force_refresh=True)
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/minion.py", line 1583, in pillar_refresh
    self.module_refresh(force_refresh)
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/minion.py", line 1564, in module_refresh
    self.functions, self.returners, _ = self._load_modules(force_refresh)
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/minion.py", line 951, in _load_modules
    self.opts['grains'] = salt.loader.grains(self.opts, force_refresh)
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/loader.py", line 545, in grains
    with salt.utils.fopen(cfn, 'w+b') as fp_:
UnboundLocalError: local variable 'cfn' referenced before assignment
```

2015.5.3 version.

**Comment by jfindlay** [comment]
@mimianddaniel, thanks for the report.

**Comment by mimianddaniel** [comment]
just an update on this, after disabling grains_cached_enabled, i stopped seeing the problem. afaikn, disabling the cache has some hit on performacne on the startup of the minions? So i have decided to disable this for now.

**Comment by MrMarvin** [comment]
There are multiple code paths leading to this bug. Ours is when using network.managed state:
```
local:
----------
          ID: tap0
    Function: network.managed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/pymodules/python2.7/salt/state.py", line 1561, in call
                  **cdata['kwargs'])
                File "/usr/lib/pymodules/python2.7/salt/states/network.py", line 334, in managed
                  grains_info = salt.loader.grains(__opts__, True)
                File "/usr/lib/pymodules/python2.7/salt/loader.py", line 546, in grains
                  with salt.utils.fopen(cfn, 'w+b') as fp_:
              UnboundLocalError: local variable 'cfn' referenced before assignment
     Started: 17:08:03.792943
    Duration: 1112.053 ms
```
Version Info:
```
# salt-call --versions-report
           Salt: 2015.5.5
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: Not Installed
```

**Comment by MrMarvin** [comment]
A quick look at the code shows that for every call with `force_refresh` explicitly set, it will fail due to the unassigned `cfn` local variable. The following is the only ever assignment to it in this method.
```
    # if we hae no grains, lets try loading from disk (TODO: move to decorator?)
    if not force_refresh:
        if opts.get('grains_cache', False):
            cfn = os.path.join(
                opts['cachedir'],
                'grains.cache.p'
            )
```

**Comment by MrMarvin** [comment]
Also, I can confirm that setting `grains_cache: False` in the minions config file will do as a work around. :+1:
