### ISSUE TITLE
salt-ssh fails on nagios.py

### ISSUE THREAD

**Issue by roflmao** [saltstack/salt#26198]
Trying to setup salt-ssh as a failback for our salt rig and i just keep getting this strange error regarding nagios.py. Looks to me as it doesnt get to the tarball?

```python-traceback
root@salt:~# salt-ssh '*' test.ping
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
OSError: [Errno 2] No such file or directory: 'salt/states/nagios.py'
Traceback (most recent call last):
  File "/usr/bin/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 273, in salt_ssh
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/ssh.py", line 17, in run
    ssh = salt.client.ssh.SSH(self.config)
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 233, in __init__
    self.thin = salt.utils.thin.gen_thin(self.opts['cachedir'])
  File "/usr/lib/python2.7/dist-packages/salt/utils/thin.py", line 165, in gen_thin
    tfp.add(os.path.join(root, name))
  File "/usr/lib/python2.7/tarfile.py", line 1975, in add
    tarinfo = self.gettarinfo(name, arcname)
  File "/usr/lib/python2.7/tarfile.py", line 1849, in gettarinfo
    statres = os.stat(name)
OSError: [Errno 2] No such file or directory: 'salt/states/nagios.py'
Traceback (most recent call last):
  File "/usr/bin/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 273, in salt_ssh
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/ssh.py", line 17, in run
    ssh = salt.client.ssh.SSH(self.config)
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 233, in __init__
    self.thin = salt.utils.thin.gen_thin(self.opts['cachedir'])
  File "/usr/lib/python2.7/dist-packages/salt/utils/thin.py", line 165, in gen_thin
    tfp.add(os.path.join(root, name))
  File "/usr/lib/python2.7/tarfile.py", line 1975, in add
    tarinfo = self.gettarinfo(name, arcname)
  File "/usr/lib/python2.7/tarfile.py", line 1849, in gettarinfo
    statres = os.stat(name)
OSError: [Errno 2] No such file or directory: 'salt/states/nagios.py'
```

locate nagios.py on master:
```
/usr/lib/python2.6/dist-packages/salt/modules/nagios.py
/usr/lib/python2.6/dist-packages/salt/modules/nagios.pyc
/usr/lib/python2.6/dist-packages/salt/states/nagios.py
/usr/lib/python2.7/dist-packages/salt/modules/nagios.py
/usr/lib/python2.7/dist-packages/salt/modules/nagios.pyc
/usr/lib/python2.7/dist-packages/salt/states/nagios.py
/usr/share/pyshared/salt/modules/nagios.py
/var/cache/salt/master/gitfs/refs/master/_modules/nagios.py
```

versions-report:
```yaml
root@salt:~# salt --versions-report
                  Salt: 2015.5.2
                Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
                Jinja2: 2.6
              M2Crypto: 0.21.1
        msgpack-python: 0.1.10
          msgpack-pure: Not Installed
              pycrypto: 2.6
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 13.1.0
                  RAET: Not Installed
                   ZMQ: 3.2.3
                  Mako: 0.7.0
 Debian source package: 2015.5.2+ds-1~bpo70+1
```

**Comment by jfindlay** [comment]
@roflmao, that is a strange error.  Thanks for reporting.  Does it work if you (re)move the `/usr/lib/python2.6/dist-packages/salt/states/nagios.py` file?  Does it give the same message on a different file?  I am wondering if it is getting the path wrong somehow.

**Comment by roflmao** [comment]
```
root@salt:~# ls -lah /usr/lib/python2.6/dist-packages/salt/states/nagios.py
lrwxrwxrwx 1 root root 41 Mar 21  2014 /usr/lib/python2.6/dist-packages/salt/states/nagios.py -> /usr/share/pyshared/salt/states/nagios.py
root@salt:~# rm /usr/lib/python2.6/dist-packages/salt/states/nagios.py
root@salt:~# salt-ssh \* test.ping
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
OSError: [Errno 2] No such file or directory: 'salt/states/nagios.py'
Traceback (most recent call last):
  File "/usr/bin/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 273, in salt_ssh
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/ssh.py", line 17, in run
    ssh = salt.client.ssh.SSH(self.config)
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 233, in __init__
    self.thin = salt.utils.thin.gen_thin(self.opts['cachedir'])
  File "/usr/lib/python2.7/dist-packages/salt/utils/thin.py", line 165, in gen_thin
    tfp.add(os.path.join(root, name))
  File "/usr/lib/python2.7/tarfile.py", line 1975, in add
    tarinfo = self.gettarinfo(name, arcname)
  File "/usr/lib/python2.7/tarfile.py", line 1849, in gettarinfo
    statres = os.stat(name)
OSError: [Errno 2] No such file or directory: 'salt/states/nagios.py'
Traceback (most recent call last):
  File "/usr/bin/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 273, in salt_ssh
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/ssh.py", line 17, in run
    ssh = salt.client.ssh.SSH(self.config)
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 233, in __init__
    self.thin = salt.utils.thin.gen_thin(self.opts['cachedir'])
  File "/usr/lib/python2.7/dist-packages/salt/utils/thin.py", line 165, in gen_thin
    tfp.add(os.path.join(root, name))
  File "/usr/lib/python2.7/tarfile.py", line 1975, in add
    tarinfo = self.gettarinfo(name, arcname)
  File "/usr/lib/python2.7/tarfile.py", line 1849, in gettarinfo
    statres = os.stat(name)
OSError: [Errno 2] No such file or directory: 'salt/states/nagios.py'
root@salt:~# ls -lah /usr/lib/python2.7/dist-packages/salt/states/nagios.py
lrwxrwxrwx 1 root root 41 Mar 21  2014 /usr/lib/python2.7/dist-packages/salt/states/nagios.py -> /usr/share/pyshared/salt/states/nagios.py
root@salt:~# rm /usr/lib/python2.7/dist-packages/salt/states/nagios.py
root@salt:~# salt-ssh \* test.ping
<Working results> :)
```

**Comment by jfindlay** [comment]
@roflmao, that is interesting.  Thanks for the extra info.

**Comment by cachedout** [comment]
Where is `nagios.py` coming from? That isn't a state that's shipped with Salt. (We do have an execution module by that name, however.)

**Comment by roflmao** [comment]
Well that is embarassing! Legacy custom py module in use. Thanks guys!

**Comment by jfindlay** [comment]
@roflmao, nice.  I'm glad you got it worked out.
