### ISSUE TITLE
pip install salt, then start master failed on Fedora 22

### ISSUE THREAD

**Issue by dove-young** [saltstack/salt#26233]
There are 3 problems after <code>pip install salt</code> as referred to [RHEL install](http://docs.saltstack.com/en/latest/topics/installation/rhel.html)

- There is no <code>/etc/salt</code> directory after <code>pip install salt</code> 
- Copied  <code>/etc/salt</code> directory and <code>salt-master</code> start failed. <code> no zmq module</code> is claimed.
- <code>pip install zmq</code> also failed

Here is what I installed. 

```
[root@localhost ~]# pip install --upgrade pip
You are using pip version 6.0.8, however version 7.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting pip from https://pypi.python.org/packages/py2.py3/p/pip/pip-7.1.0-py2.py3-none-any.whl#md5=b108384a762825ec20345bb9b5b7209f
  Downloading pip-7.1.0-py2.py3-none-any.whl (1.1MB)
    100% |################################| 1.1MB 276kB/s 
Installing collected packages: pip
  Found existing installation: pip 6.0.8
    Uninstalling pip-6.0.8:
      Successfully uninstalled pip-6.0.8

Successfully installed pip-7.1.0
[root@localhost ~]# 
[root@localhost ~]# pip install salt
Collecting salt
  Downloading salt-2015.5.3.tar.gz (5.4MB)
    100% |████████████████████████████████| 5.4MB 51kB/s 
Requirement already satisfied (use --upgrade to upgrade): Jinja2 in /usr/lib/python2.7/site-packages (from salt)
Collecting msgpack-python>0.3 (from salt)
  Downloading msgpack-python-0.4.6.tar.gz (116kB)
    100% |████████████████████████████████| 118kB 162kB/s 
Requirement already satisfied (use --upgrade to upgrade): PyYAML in /usr/lib64/python2.7/site-packages (from salt)
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in /usr/lib64/python2.7/site-packages (from salt)
Requirement already satisfied (use --upgrade to upgrade): requests>=1.0.0 in /usr/lib/python2.7/site-packages (from salt)
Installing collected packages: msgpack-python, salt
  Running setup.py install for msgpack-python
  Running setup.py install for salt
Successfully installed msgpack-python-0.4.6 salt-2015.5.3
[root@localhost ~]#

[root@localhost salt]# pip show salt
---
Metadata-Version: 1.0
Name: salt
Version: 2015.5.3
Summary: Portable, distributed, remote execution and configuration management system
Home-page: http://saltstack.org
Author: Thomas S Hatch
Author-email: thatch45@gmail.com
License: Apache Software License 2.0
Location: /usr/lib/python2.7/site-packages
Requires: Jinja2, msgpack-python, PyYAML, MarkupSafe, requests
Entry-points:
  [console_scripts]
  salt = salt.scripts:salt_main
  salt-api = salt.scripts:salt_api
  salt-call = salt.scripts:salt_call
  salt-cloud = salt.scripts:salt_cloud
  salt-cp = salt.scripts:salt_cp
  salt-key = salt.scripts:salt_key
  salt-master = salt.scripts:salt_master
  salt-minion = salt.scripts:salt_minion
  salt-run = salt.scripts:salt_run
  salt-ssh = salt.scripts:salt_ssh
  salt-syndic = salt.scripts:salt_syndic
  salt-unity = salt.scripts:salt_unity
[root@localhost salt]# 
```
Then start salt-master failed. And there is NO <code>/etc/salt</code> directory after installation.

```
[root@localhost salt]# salt-master --log-level=all
WARNING: '/etc/salt' directory does not exist.
[DEBUG   ] Missing configuration file: /etc/salt/master
[TRACE   ] None of the required configuration sections, 'logstash_udp_handler' and 'logstash_zmq_handler', were found the in the configuration. Not loading the Logstash lo
gging handlers module.
[DEBUG   ] Configuration file path: /etc/salt/master
[TRACE   ] Trying pysss.getgrouplist for 'root'
[TRACE   ] Trying generic group list for 'root'
[TRACE   ] Group list for user 'root': []
[INFO    ] Setting up the Salt Master
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
ImportError: No module named zmq
Traceback (most recent call last):
  File "/bin/salt-master", line 9, in <module>
    load_entry_point('salt==2015.5.3', 'console_scripts', 'salt-master')()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 50, in salt_master
    master.start()
  File "/usr/lib/python2.7/site-packages/salt/cli/daemons.py", line 149, in start
    self.prepare()
  File "/usr/lib/python2.7/site-packages/salt/cli/daemons.py", line 129, in prepare
    import salt.master
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 25, in <module>
    import zmq
ImportError: No module named zmq
Traceback (most recent call last):
  File "/bin/salt-master", line 9, in <module>
    load_entry_point('salt==2015.5.3', 'console_scripts', 'salt-master')()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 50, in salt_master
    master.start()
  File "/usr/lib/python2.7/site-packages/salt/cli/daemons.py", line 149, in start
    self.prepare()
  File "/usr/lib/python2.7/site-packages/salt/cli/daemons.py", line 129, in prepare
    import salt.master
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 25, in <module>
    import zmq
ImportError: No module named zmq
[root@localhost salt]#
```

I downloaded <code>/etc/salt</code> directory from a yum installed server, and tried again, then fail again.

```
[root@localhost salt]# 
[root@localhost salt]# salt-master --log-level=all
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: tivx93.cn.ibm.com
[TRACE   ] None of the required configuration sections, 'logstash_udp_handler' and 'logstash_zmq_handler', were found the in the configuration. Not loading the Logstash lo
gging handlers module.
[DEBUG   ] Configuration file path: /etc/salt/master
[TRACE   ] Trying pysss.getgrouplist for 'root'
[TRACE   ] Trying generic group list for 'root'
[TRACE   ] Group list for user 'root': []
[INFO    ] Setting up the Salt Master
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
ImportError: No module named zmq
Traceback (most recent call last):
  File "/bin/salt-master", line 9, in <module>
    load_entry_point('salt==2015.5.3', 'console_scripts', 'salt-master')()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 50, in salt_master
    master.start()
  File "/usr/lib/python2.7/site-packages/salt/cli/daemons.py", line 149, in start
    self.prepare()
  File "/usr/lib/python2.7/site-packages/salt/cli/daemons.py", line 129, in prepare
    import salt.master
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 25, in <module>
    import zmq
ImportError: No module named zmq
Traceback (most recent call last):
  File "/bin/salt-master", line 9, in <module>
    load_entry_point('salt==2015.5.3', 'console_scripts', 'salt-master')()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 50, in salt_master
    master.start()
  File "/usr/lib/python2.7/site-packages/salt/cli/daemons.py", line 149, in start
    self.prepare()
  File "/usr/lib/python2.7/site-packages/salt/cli/daemons.py", line 129, in prepare
    import salt.master
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 25, in <module>
    import zmq
ImportError: No module named zmq
[root@localhost salt]#
```
Then I installed <code>zmq</code>, and failed.

```
[root@localhost salt]# pip install zmq
Collecting zmq
  Downloading zmq-0.0.0.tar.gz
Collecting pyzmq (from zmq)
  Downloading pyzmq-14.7.0.tar.gz (1.0MB)
    100% |████████████████████████████████| 1.0MB 172kB/s 
Installing collected packages: pyzmq, zmq
  Running setup.py install for pyzmq
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-3IKkpS/pyzmq/setup.py';exec(compile(getattr(tokenize, 'open', ope
n)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-8Rux4V-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
... ... ... ...
... ... ... ...
    running build_ext
    running configure
    Did not find libzmq via pkg-config:
    Package libzmq was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libzmq.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libzmq' found
    
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -g
record-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protec
tor-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -c build/temp.linux-x86_64-2.7/scratch/check_sys_un.c -o b
uild/temp.linux-x86_64-2.7/scratch/check_sys_un.o
    gcc -pthread build/temp.linux-x86_64-2.7/scratch/check_sys_un.o -o build/temp.linux-x86_64-2.7/scratch/check_sys_un
    Configure: Autodetecting ZMQ settings...
        Custom ZMQ dir:
    ************************************************
    creating build/temp.linux-x86_64-2.7/scratch/tmp
    cc -c /tmp/timer_createRSicys.c -o build/temp.linux-x86_64-2.7/scratch/tmp/timer_createRSicys.o
    /tmp/timer_createRSicys.c:1:1: warning: return type defaults to ‘int’ [-Wimplicit-int]
     main (int argc, char **argv) {
     ^
    /tmp/timer_createRSicys.c: In function ‘main’:
    /tmp/timer_createRSicys.c:2:5: warning: implicit declaration of function ‘timer_create’ [-Wimplicit-function-declaration]
         timer_create();
         ^
    cc build/temp.linux-x86_64-2.7/scratch/tmp/timer_createRSicys.o -o build/temp.linux-x86_64-2.7/scratch/a.out
    build/temp.linux-x86_64-2.7/scratch/tmp/timer_createRSicys.o: In function `main':
    timer_createRSicys.c:(.text+0x15): undefined reference to `timer_create'
    collect2: error: ld returned 1 exit status
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -g
record-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protec
tor-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Izmq/utils -Izmq/backend/cython -Izmq/devices -c build/te
mp.linux-x86_64-2.7/scratch/vers.c -o build/temp.linux-x86_64-2.7/scratch/vers.o
    build/temp.linux-x86_64-2.7/scratch/vers.c:4:17: fatal error: zmq.h: No such file or directory
    compilation terminated.
    
    error: command 'gcc' failed with exit status 1
    Failed with default libzmq, trying again with /usr/local
    Configure: Autodetecting ZMQ settings...
        Custom ZMQ dir:       /usr/local
    ************************************************
    cc -c /tmp/timer_createnLDf_k.c -o build/temp.linux-x86_64-2.7/scratch/tmp/timer_createnLDf_k.o
    /tmp/timer_createnLDf_k.c:1:1: warning: return type defaults to ‘int’ [-Wimplicit-int]
     main (int argc, char **argv) {
     ^
    /tmp/timer_createnLDf_k.c: In function ‘main’:
    /tmp/timer_createnLDf_k.c:2:5: warning: implicit declaration of function ‘timer_create’ [-Wimplicit-function-declaration]
         timer_create();
         ^
    Assembler messages:
    Fatal error: can't create build/temp.linux-x86_64-2.7/scratch/tmp/timer_createnLDf_k.o: No such file or directory
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -g
record-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protec
tor-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/local/include -Izmq/utils -Izmq/backend/cython -Izm
q/devices -c build/temp.linux-x86_64-2.7/scratch/vers.c -o build/temp.linux-x86_64-2.7/scratch/vers.o
    build/temp.linux-x86_64-2.7/scratch/vers.c:4:17: fatal error: zmq.h: No such file or directory
    compilation terminated.
    
    error: command 'gcc' failed with exit status 1
    
    Warning: Failed to build or run libzmq detection test.
    
    If you expected pyzmq to link against an installed libzmq, please check to make sure:
    
        * You have a C compiler installed
        * A development version of Python is installed (including headers)
        * A development version of ZMQ >= 2.1.4 is installed (including headers)
        * If ZMQ is not in a default location, supply the argument --zmq=<path>
        * If you did recently install ZMQ to a default location,
          try rebuilding the ld cache with `sudo ldconfig`
          or specify zmq's location with `--zmq=/usr/local`
    You can skip all this detection/waiting nonsense if you know
    you want pyzmq to bundle libzmq as an extension by passing:
    
        `--zmq=bundled`
    
    I will now try to build libzmq as a Python extension
    unless you interrupt me (^C) in the next 10 seconds...
    
    ************************************************
     1...
    Using bundled libzmq
    already have bundled/zeromq
    attempting ./configure to generate platform.hpp
    Warning: failed to configure libzmq:
    /bin/sh: ./configure: No such file or directory
    
    staging platform.hpp from: buildutils/include_linux
    checking for timer_create
    ************************************************
    ************************************************
    creating build/temp.linux-x86_64-2.7/tmp
    cc -c /tmp/timer_createMe7Pq7.c -o build/temp.linux-x86_64-2.7/tmp/timer_createMe7Pq7.o
    /tmp/timer_createMe7Pq7.c:1:1: warning: return type defaults to ‘int’ [-Wimplicit-int]
     main (int argc, char **argv) {
     ^
    /tmp/timer_createMe7Pq7.c: In function ‘main’:
    /tmp/timer_createMe7Pq7.c:2:5: warning: implicit declaration of function ‘timer_create’ [-Wimplicit-function-declaration]
         timer_create();
         ^
    cc build/temp.linux-x86_64-2.7/tmp/timer_createMe7Pq7.o -o build/temp.linux-x86_64-2.7/a.out
    build/temp.linux-x86_64-2.7/tmp/timer_createMe7Pq7.o: In function `main':
    timer_createMe7Pq7.c:(.text+0x15): undefined reference to `timer_create'
    collect2: error: ld returned 1 exit status
    no timer_create, linking librt
    Using bundled libsodium
    already have bundled/libsodium
    staging buildutils/include_sodium/version.h to bundled/libsodium/src/libsodium/include/sodium/version.h
    already have crypto_stream_salsa20.h
    already have crypto_scalarmult_curve25519.h
    ************************************************
    ************************************************
    building 'zmq.libsodium' extension
    creating build/temp.linux-x86_64-2.7/buildutils
    creating build/temp.linux-x86_64-2.7/bundled
... ... ... ...
... ... ... ...
    creating build/temp.linux-x86_64-2.7/bundled/libsodium/src/libsodium/crypto_aead/chacha20poly1305/sodium
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -g
record-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protec
tor-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DNATIVE_LITTLE_ENDIAN=1 -Ibundled/libsodium/src/libsodium
/include -Ibundled/libsodium/src/libsodium/include/sodium -I/usr/include/python2.7 -c buildutils/initlibsodium.c -o build/temp.linux-x86_64-2.7/buildutils/initlibsodium.o
    buildutils/initlibsodium.c:10:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-3IKkpS/pyzmq/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().repl
ace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-8Rux4V-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 i
n /tmp/pip-build-3IKkpS/pyzmq
[root@localhost salt]# 
````

**Comment by gtmanfred** [comment]
You need to install the group 'Development Tools' on fedora and on redhat.  This is expected behavior to be able to compile packages.

    yum groupinstall 'Development Tools'

I believe you should be able to just use groupinstall with dnf in the same way.

You may also need to install the zeromq-devel package if it fails on linking against that afterwards as well.

**Comment by gtmanfred** [comment]
Also, pip install does not make the init scripts or the /etc/salt directory.

If you are pip installing, the defaults are used, and you will need to provide your own systemd service unit, which is pretty simple to do.

**Comment by dove-young** [comment]
Well. It would be much better to mention these info at document here [RHEL install](http://docs.saltstack.com/en/latest/topics/installation/rhel.html)

**Comment by jfindlay** [comment]
@dove-young, thanks for the report.

**Comment by jfindlay** [comment]
Thanks everyone for working on this issue.
