### ISSUE TITLE
keystone.user_get raises exception when user is not found

### ISSUE THREAD

**Issue by 0xf10e** [saltstack/salt#26240]
We should catch this exception and return a proper error:
```python-traceback
user@master:~/ $ sudo salt hw-ctrl keystone.user_get admin
hw-ctrl:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1146, in _thread_return
        return_data = func(*args, **kwargs)
      File "/var/cache/salt/minion/extmods/modules/keystone.py", line 710, in user_get
        user = kstone.users.get(user_id)
      File "/usr/lib/python2.7/dist-packages/keystoneclient/v2_0/users.py", line 39, in get
        return self._get("/users/%s" % base.getid(user), "user")
      File "/usr/lib/python2.7/dist-packages/keystoneclient/base.py", line 128, in _get
        resp, body = self.client.get(url)
      File "/usr/lib/python2.7/dist-packages/keystoneclient/httpclient.py", line 590, in get
        return self._cs_request(url, 'GET', **kwargs)
      File "/usr/lib/python2.7/dist-packages/keystoneclient/httpclient.py", line 582, in _cs_request
        return self.request(url, method, **kwargs)
      File "/usr/lib/python2.7/dist-packages/keystoneclient/httpclient.py", line 564, in request
        resp = super(HTTPClient, self).request(url, method, **kwargs)
      File "/usr/lib/python2.7/dist-packages/keystoneclient/baseclient.py", line 21, in request
        return self.session.request(url, method, **kwargs)
      File "/usr/lib/python2.7/dist-packages/keystoneclient/utils.py", line 318, in inner
        return func(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/keystoneclient/session.py", line 251, in request
        raise exceptions.from_response(resp, method, url)
    NotFound: Could not find user, admin. (HTTP 404)
```

**Comment by 0xf10e** [comment]
Oh, right: I'm using the keystone exec-mod from 2015.8 on Ubuntu with salt-{master,client} 2015.5.3.

**Comment by jfindlay** [comment]
@0xf10e, thanks for the report.

**Comment by rallytime** [comment]
@0xf10e Can you give #26277 a try? Please feel free to close this if that fix is satisfactory.

**Comment by 0xf10e** [comment]
Looks good:
```
user@master:/srv/salt/openstack-formula.git% sudo salt -C 'hw-ctrl or controller' keystone.user_get admin
controller:
    ----------
hw-ctrl:
    ----------
user@master:/srv/salt/openstack-formula.git% sudo salt -C 'hw-ctrl or controller' keystone.user_get name=admin
hw-ctrl:
    ----------
    admin:
        ----------
        email:
            admin@example.com
        [...]
controller:
    ----------
    admin:
        ----------
        email:
            admin@example.com
        [...]
```

**Comment by rallytime** [comment]
Great! Thanks for confirming!
