### ISSUE TITLE
ZMQError: No buffer space available

### ISSUE THREAD

**Issue by theorb77** [saltstack/salt#26253]
I have a Salt Minion, 2014.7.5-2 on a Windows 2008 R2 SP1 Standard install that is refusing to respond, even after service restarts (Salt Master is on 2015.5.2).  When I begin the minion using the salt-minion-debug.bat file, I get the following traceback (names have been changed to protect the innocent):

```
The salt-minion service is not started.

More help is available by typing NET HELPMSG 3521.

[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[INFO    ] Setting up the Salt Minion "salt-minion.example.com"
[DEBUG   ] Created pidfile: c:\salt\var\run\salt-minion.pid
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Attempting to authenticate with the Salt Master at salt-master.example.com
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
Assertion failed: Socket operation on non-socket (bundled\zeromq\src\select.cpp:
170)
Assertion failed: Socket operation on non-socket (bundled\zeromq\src\select.cpp:
170)
[ERROR   ] An un-handled exception was caught by salt's global exception handler
:
ZMQError: No buffer space available
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-minion", line 14, in <module>
    salt_minion()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 57, in salt_minion
    minion.start()
  File "C:\salt\bin\lib\site-packages\salt\__init__.py", line 262, in start
    self.prepare()
  File "C:\salt\bin\lib\site-packages\salt\__init__.py", line 241, in prepare
    self.minion = salt.minion.Minion(self.config)
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 600, in __init__
    safe)
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 779, in eval_master
    if self.authenticate(timeout, safe) == 'full':
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 1380, in authenticat
e
    creds = auth.sign_in(timeout, safe, tries)
  File "C:\salt\bin\lib\site-packages\salt\crypt.py", line 644, in sign_in
    timeout=timeout
  File "C:\salt\bin\lib\site-packages\salt\payload.py", line 259, in send_auto
    return self.send(enc, load, tries, timeout)
  File "C:\salt\bin\lib\site-packages\salt\payload.py", line 235, in send
    self.socket.send(pkg)
  File "C:\salt\bin\lib\site-packages\salt\payload.py", line 174, in socket
    self._socket = self.context.socket(zmq.REQ)
  File "C:\salt\bin\lib\site-packages\zmq\sugar\context.py", line 143, in socket

    s = self._socket_class(self, socket_type)
  File "zmq\backend\cython\socket.pyx", line 227, in zmq.backend.cython.socket.S
ocket.__cinit__ (zmq\backend\cython\socket.c:2451)
ZMQError: No buffer space available
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-minion", line 14, in <module>
    salt_minion()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 57, in salt_minion
    minion.start()
  File "C:\salt\bin\lib\site-packages\salt\__init__.py", line 262, in start
    self.prepare()
  File "C:\salt\bin\lib\site-packages\salt\__init__.py", line 241, in prepare
```

Now, I believe this is related to the ZeroMQ error reported [here.](https://zeromq.jira.com/browse/LIBZMQ-195?jql=text%20~%20%22No%20buffer%20space%20available%22)

Which reports that ZeroMQ is receiving the WSAENOBUFS error from the OS, and Windows Server 2008 R2 SP1 has a corresponding Kernel Socket leak KB article [here.](https://support.microsoft.com/en-us/kb/2577795)

I haven't found any indication that this has been fixed in future releases of salt minion, so I thought I'd throw it up here for review.

**Comment by jfindlay** [comment]
@theorb77, thanks for the report.  Is it possible for you to reproduce this error on 2015.5.3?  Thanks.

**Comment by cachedout** [comment]
Hmm, based on that issue the only way I can see us possibly solving this would be to expose ZeroMQ HWM in the minion up to the config. We already do this on the master side for the publisher. Take a look at `pub_hwm` and its usage in `config.py` and `salt.transport.zeromq`.

**Comment by theorb77** [comment]
I modified the pub_hwm values in config.py directly for this minion, changing the values from 1000 to 10000, 20000, and 50000.  They all resulted in an identical stacktrace, immediately upon starting via the salt-minion-debug.bat.  If this issue were related to the pub_hwm value, I would expect the minion to function temporarily until the memory buffer reached the hwm value.  Instead, it fails immediately when I start the salt minion.

I'm going to try updating the minion and rebooting the machine.  I believe I'm seeing this same issue on other machines, but this one is persistent.  I'll update once I've been able to validate.

**Comment by cachedout** [comment]
Sorry, I may have been misleading there. What I was getting at was that we have `pub_hwm` which only affects the master and we would need to write something similar for the sockets on the minion side but we don't have that functionality in place currently.

**Comment by theorb77** [comment]
Ah, so the config.py file is common to both the master and the minion and the pub_hwm value is only used by the master?  That's interesting.

Well, I guess that probably means a reboot isn't going to be a terrible amount of help.

**Comment by jacky35** [comment]
I have the same problem with Windows XP : - / what's the solution?
