### ISSUE TITLE
minion stack trace after master stopped

### ISSUE THREAD

**Issue by jfindlay** [saltstack/salt#26276]
### description
I have a master and a minion running on the same system.  After I stop the master the minion produces a stack trace whenever it runs its scheduled `mine.update`.

### minion log
```python-traceback
[DEBUG   ] Handling event '_minion_mine\n\n\x85\xa5clear\xc2\xa3cmd\xa5_mine\xa4data\x80\xa2id\xabjmoney-main\xa6_stamp\xba2015-08-12T20:47:55.456528'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'jmoney-main', 'tcp://127.0.0.1:4506', 'aes')
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'jmoney-main', 'tcp://127.0.0.1:4506')
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'jmoney-main', 'tcp://127.0.0.1:4506', 'aes')
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'jmoney-main', 'tcp://127.0.0.1:4506')
[WARNING ] Unable to send mine data to master.
[ERROR   ] Unhandled exception running mine.update
Traceback (most recent call last):
  File "/root/salt/salt/utils/schedule.py", line 707, in handle_func
    channel.send(load)
  File "/root/salt/salt/utils/async.py", line 93, in wrap
    ret = self._block_future(ret)
  File "/root/salt/salt/utils/async.py", line 103, in _block_future
    return future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/root/salt/salt/transport/zeromq.py", line 220, in send
    ret = yield self._crypted_transfer(load, tries=tries, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/root/salt/salt/transport/zeromq.py", line 193, in _crypted_transfer
    ret = yield _do_transfer()
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/root/salt/salt/transport/zeromq.py", line 179, in _do_transfer
    timeout=timeout,
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
SaltReqTimeoutError: Message timed out
```

After I restart the master, while leaving the minion process undisturbed, the following appears in the minion log every time I run a `salt jmoney-main test.versions`.
```
[INFO    ] User root Executing command test.versions with jid 20150812161320752887
[DEBUG   ] Command details {'tgt_type': 'glob', 'jid': '20150812161320752887', 'tgt': 'jmoney-main', 'ret': '', 'user': 'root', 'arg': [], 'fun': 'test.versions'}
[INFO    ] Starting a new job with PID 23263
Exception AttributeError: "'NoneType' object has no attribute 'close'" in <bound method AsyncReqMessageClient.__del__ of <salt.transport.zeromq.AsyncReqMessageClient object at 0x7f3204938d10>> ignored
[DEBUG   ] LazyLoaded test.versions
Exception AttributeError: "'NoneType' object has no attribute 'close'" in <bound method AsyncReqMessageClient.__del__ of <salt.transport.zeromq.AsyncReqMessageClient object at 0x7f32049c7510>> ignored
[INFO    ] Returning information for job: 20150812161320752887
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'jmoney-main', 'tcp://127.0.0.1:4506', 'aes')
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'jmoney-main', 'tcp://127.0.0.1:4506')
```

### versions
```yaml
Salt Version:
           Salt: 2015.8.0rc3-31-gb996cf4

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
           Mako: 1.0.0
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
       pycrypto: 2.6.1
        timelib: Not Installed

System Versions:
           dist: debian 8.1
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.1
```

### configs
```yaml
# cat /etc/salt/master 
log_fmt_console: '%(colorlevel)s %(colormsg)s'

fileserver_backend:
  - roots

file_roots:
  base:
    - /root/salt-manual-tests
    - /srv/salt
```
```yaml
# cat /etc/salt/minion
master: localhost
log_fmt_console: '%(colorlevel)s %(colormsg)s'
```

**Comment by cachedout** [comment]
What do you consider the expected behaviour to be here? If the master is stopped, it certainly can't send a mine update. Just to log an error?

**Comment by jfindlay** [comment]
@cachedout, yes, I don't think it is a big issue, but the minion should not throw a stack trace and should cleanly reconnect to the master once it is restarted.

**Comment by cachedout** [comment]
Gotcha. Sounds good.
