### ISSUE TITLE
Timezone module error when timedatectl fails to query server

### ISSUE THREAD

**Issue by anlutro** [saltstack/salt#26313]
This error started appearing today, using 2015.8 HEAD:

```
          ID: set-timezone
    Function: timezone.system
        Name: Europe/Oslo
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/tmp/.root_740f1b_salt/salt/state.py", line 1591, in call
                  **cdata['kwargs'])
                File "/tmp/.root_740f1b_salt/salt/states/timezone.py", line 73, in system
                  if __salt__['timezone.get_hwclock']() == 'localtime':
                File "/tmp/.root_740f1b_salt/salt/modules/timezone.py", line 215, in get_hwclock
                  'Failed to parse timedatectl output, this is likely a bug'
              CommandExecutionError: Failed to parse timedatectl output, this is likely a bug
     Started: 08:54:22.931179
    Duration: 25036.216 ms
     Changes:   
```

**Comment by anlutro** [comment]
Looks like my server can't connect to the ntp servers. Running `timedatectl` on the command line hangs for ~20 seconds then returns "Failed to query server: Connection timed out". The timezone module can probably be modified to give a clearer error message here.

A simple `if ret['retcode'] > 0: raise SomeException(ret['stderr'])` might help.

**Comment by jfindlay** [comment]
@anlutro, thanks for the report.
