### ISSUE TITLE
salt-ssh python client with partition cmd throws unhashable type

### ISSUE THREAD

**Issue by bbyhuy** [saltstack/salt#26322]
I'm trying to utilize the salt-ssh client python to partition and format a fs, I had this working with regular salt.localclient() but it seems to not like the sshclient().

The Code: 

``` python
try:
            self._client.cmd('*', [
                'partition.mklabel',
                'partition.mkpart',
                'extfs.mkfs',
                'mount.mount'
            ],
                [
                ['/dev/vdb', 'gpt'],
                ['/dev/vdb', 'logical', 'start=0%', 'end=100%'],
                ['/dev/vdb', 'fs_type=ext4'],
                ['/mnt/vdb', '/dev/vdb', 'mkmnt=True']
            ], ignore_host_keys=True)
        except Exception, e:
            raise e
```

The Error:

```
    Process Process-2:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
        self.run()
      File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
        self._target(*self._args, **self._kwargs)
      File "/opt/optimusenv/local/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 335, in     handle_routine
        stdout, stderr, retcode = single.run()
      File "/opt/optimusenv/local/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 703, in run
        elif self.fun in self.wfuncs or self.mine:
      File "/opt/optimusenv/lib/python2.7/_abcoll.py", line 369, in __contains__
        self[key]
      File "/opt/optimusenv/local/lib/python2.7/site-packages/salt/utils/lazy.py", line 83, in __getitem__
        if key not in self._dict and not self.loaded:
    TypeError: unhashable type: 'list'
```

**Comment by jfindlay** [comment]
@bbyhuy, thanks for the report.
