### ISSUE TITLE
batch error when no minions match target

### ISSUE THREAD

**Issue by jfindlay** [saltstack/salt#26343]
### commands
```python-traceback
# salt 'no_match*' -b 20 test.ping
No minions matched the target. No command was sent, no jid was assigned.
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
StopIteration: 
Traceback (most recent call last):
  File "/usr/bin/salt", line 8, in <module>
    execfile(__file__)
  File "/root/salt-2015.5.4/scripts/salt", line 10, in <module>
    salt_main()
  File "/root/salt-2015.5.4/salt/scripts.py", line 349, in salt_main
    client.run()
  File "/root/salt-2015.5.4/salt/cli/salt.py", line 97, in run
    batch = salt.cli.batch.Batch(self.config, eauth=eauth)
  File "/root/salt-2015.5.4/salt/cli/batch.py", line 29, in __init__
    self.minions, self.ping_gen = self.__gather_minions()
  File "/root/salt-2015.5.4/salt/cli/batch.py", line 51, in __gather_minions
    m = next(ret.iterkeys())
StopIteration
Traceback (most recent call last):
  File "/usr/bin/salt", line 8, in <module>
    execfile(__file__)
  File "/root/salt-2015.5.4/scripts/salt", line 10, in <module>
    salt_main()
  File "/root/salt-2015.5.4/salt/scripts.py", line 349, in salt_main
    client.run()
  File "/root/salt-2015.5.4/salt/cli/salt.py", line 97, in run
    batch = salt.cli.batch.Batch(self.config, eauth=eauth)
  File "/root/salt-2015.5.4/salt/cli/batch.py", line 29, in __init__
    self.minions, self.ping_gen = self.__gather_minions()
  File "/root/salt-2015.5.4/salt/cli/batch.py", line 51, in __gather_minions
    m = next(ret.iterkeys())
StopIteration
```

### versions
```yaml
# salt --versions
           Salt: 2015.5.4
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
```

**Comment by cachedout** [comment]
Fixed via #26445
