### ISSUE TITLE
salt queue pop is not removing items from the queue correctly

### ISSUE THREAD

**Issue by gtmanfred** [saltstack/salt#26351]
```
[root@salt runners]# salt-run queue.pop loadbalancer all
- board2.taplists.beer
- board3.taplists.beer
- board4.taplists.beer
- board5.taplists.beer
- board6.taplists.beer
- board7.taplists.beer
- board8.taplists.beer
- board9.taplists.beer
[root@salt runners]# salt-run queue.pop loadbalancer all
- board2.taplists.beer
- board3.taplists.beer
- board4.taplists.beer
- board5.taplists.beer
- board6.taplists.beer
- board7.taplists.beer
- board8.taplists.beer
- board9.taplists.beer
```

They are still there even once you have done queue.pop or queue.process_queue all.

@techhat 

Thanks
Daniel

**Comment by gtmanfred** [comment]
```
2015-08-16 00:35:34,525 [salt.utils.schedule][ERROR   ][7121] Unhandled exception running queue.process_queue
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/schedule.py", line 703, in handle_func
    channel = salt.transport.Channel.factory(self.opts, usage='salt_schedule')
  File "/usr/lib/python2.7/site-packages/salt/transport/__init__.py", line 29, in factory
    return ReqChannel.factory(opts, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/transport/client.py", line 22, in factory
    sync = SyncWrapper(AsyncReqChannel.factory, (opts,), kwargs)
  File "/usr/lib/python2.7/site-packages/salt/utils/async.py", line 72, in __init__
    self.async = method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/transport/client.py", line 101, in factory
    return salt.transport.zeromq.AsyncZeroMQReqChannel(opts, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/transport/zeromq.py", line 78, in __new__
    new_obj.__singleton_init__(opts, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/transport/zeromq.py", line 121, in __singleton_init__
    self.auth = salt.crypt.AsyncAuth(self.opts, io_loop=self._io_loop)
  File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 316, in __new__
    key = cls.__key(opts)
  File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 333, in __key
    opts['master_uri'],  # master ID
KeyError: 'master_uri'
```

Looks like I am missing a setting.

**Comment by gtmanfred** [comment]
nope
