### ISSUE TITLE
salt-cloud VMware driver fails with KeyErrors if some VM are disconnected

### ISSUE THREAD

**Issue by evle-zzz** [saltstack/salt#26372]
If VM is in disconnected state (for example when host that runs them gets disconnected from vCenter) 
salt-cloud -f avail_images <provider> fails (Salt: 2015.8.0rc3-1202-gc34c6b9)

```
[ERROR   ] Failed to get the output of 'vmware.avail_images()': 'config.template'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 842, in image_list
    data[alias][driver] = self.clouds[fun]()
  File "/usr/local/lib/python2.7/dist-packages/salt/cloud/clouds/vmware.py", line 1672, in avail_images
    if vm["config.template"]:
KeyError: 'config.template'
[DEBUG   ] LazyLoaded nested.output
```

@nmadhok

**Comment by jfindlay** [comment]
@evle-zzz, thanks for the report.
