### ISSUE TITLE
MemoryError on jobs.lookup_jid with very large command output

### ISSUE THREAD

**Issue by htch** [saltstack/salt#26374]
Was running a salt command that produced extremely large stdout output (comparable to total memory on the machine), it was unintentional ofc. When i wanted to peek at it with jobs.lookup_jid salt crashed with this:

``` python-traceback
      # salt-run jobs.lookup_jid 20150817112744579425
      [ERROR   ] An un-handled exception was caught by salt's global exception handler:
      MemoryError: 
      Traceback (most recent call last):
        File "/usr/bin/salt-run", line 10, in <module>
          salt_run()
        File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 250, in salt_run
          client.run()
        File "/usr/lib/python2.7/dist-packages/salt/cli/run.py", line 54, in run
          runner.run()
        File "/usr/lib/python2.7/dist-packages/salt/runner.py", line 166, in run
          False)  # Don't daemonize
        File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 381, in _proc_function
          return self.low(fun, low)
        File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 327, in low
          namespaced_event.fire_event(data, 'ret')
        File "/usr/lib/python2.7/dist-packages/salt/utils/event.py", line 533, in fire_event
          self.print_func(tag, data)
        File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 452, in print_async_event
          salt.output.display_output(event_data, outputter, self.opts)
        File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 94, in display_output
          display_data = try_printout(data, out, opts)
        File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 46, in try_printout
          return get_printout(out, opts)(data).rstrip()
        File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 84, in output
          return _format_host(host, hostdata)[0]
        File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 132, in _format_host
          schanged, ctext = _format_changes(ret['changes'])
        File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 396, in _format_changes
          __opts__)
        File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 172, in out_format
          return try_printout(data, out, opts)
        File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 46, in try_printout
          return get_printout(out, opts)(data).rstrip()
        File "/usr/lib/python2.7/dist-packages/salt/output/nested.py", line 147, in output
          nest.display(ret, __opts__.get('nested_indent', 0), '', [])
      MemoryError
      Traceback (most recent call last):
        File "/usr/bin/salt-run", line 10, in <module>
          salt_run()
        File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 250, in salt_run
          client.run()
        File "/usr/lib/python2.7/dist-packages/salt/cli/run.py", line 54, in run
          runner.run()
        File "/usr/lib/python2.7/dist-packages/salt/runner.py", line 166, in run
          False)  # Don't daemonize
        File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 381, in _proc_function
          return self.low(fun, low)
        File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 327, in low
          namespaced_event.fire_event(data, 'ret')
        File "/usr/lib/python2.7/dist-packages/salt/utils/event.py", line 533, in fire_event
          self.print_func(tag, data)
        File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 452, in print_async_event
          salt.output.display_output(event_data, outputter, self.opts)
        File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 94, in display_output
          display_data = try_printout(data, out, opts)
        File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 46, in try_printout
          return get_printout(out, opts)(data).rstrip()
        File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 84, in output
          return _format_host(host, hostdata)[0]
        File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 132, in _format_host
          schanged, ctext = _format_changes(ret['changes'])
        File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 396, in _format_changes
          __opts__)
        File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 172, in out_format
          return try_printout(data, out, opts)
        File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 46, in try_printout
          return get_printout(out, opts)(data).rstrip()
        File "/usr/lib/python2.7/dist-packages/salt/output/nested.py", line 147, in output
          nest.display(ret, __opts__.get('nested_indent', 0), '', [])
      MemoryError
```

Wouldn't it be useful to have a cap on output size displayed to the user? So that he/she sees something like: "blah-blah-blah [output too large, 4G more data not shown]" instead of the traceback. To my understanding, salt also saves this output somewhere on its cache on disk, so perhaps it would make sense to cap size of data saved in that cache, too.
#### master

``` yaml
                      Salt: 2015.5.3
                    Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                    Jinja2: 2.7.2
                  M2Crypto: 0.21.1
            msgpack-python: 0.3.0
              msgpack-pure: Not Installed
                  pycrypto: 2.6.1
                   libnacl: Not Installed
                    PyYAML: 3.10
                     ioflo: Not Installed
                     PyZMQ: 14.0.1
                      RAET: Not Installed
                       ZMQ: 4.0.4
                      Mako: Not Installed
                   Tornado: Not Installed
     Debian source package: 2015.5.3+ds-1trusty1
```
#### minion

``` yaml
                  Salt: 2015.5.3
                    Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                    Jinja2: 2.7.2
                  M2Crypto: 0.21.1
            msgpack-python: 0.3.0
              msgpack-pure: Not Installed
                  pycrypto: 2.6.1
                   libnacl: Not Installed
                    PyYAML: 3.10
                     ioflo: Not Installed
                     PyZMQ: 14.0.1
                      RAET: Not Installed
                       ZMQ: 4.0.4
                      Mako: Not Installed
                   Tornado: Not Installed
     Debian source package: 2015.5.3+ds-1trusty1
```

**Comment by jfindlay** [comment]
@htch, thanks for the report.

**Comment by stamak** [comment]
Have got the same but with highstate

# salt -C "G@roles:my_role and G@environment:my_env" state.highstate saltenv=my_env -l debug
ERROR   ] An un-handled exception was caught by salt's global exception handler:
MemoryError:
Traceback (most recent call last):
  File "/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 458, in salt_main
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/salt.py", line 200, in run
    for full_ret in cmd_func(**kwargs):
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 606, in cmd_cli
    **kwargs):
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 1255, in get_cli_event_returns
    expect_minions=(verbose or show_timeout)
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 886, in get_iter_returns
    for raw in ret_iter:
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 823, in get_returns_no_block
    raw = self.event.get_event(wait=0.01, tag=tag, match_type=match_type, full=True, no_block=True)
  File "/usr/lib/python2.7/site-packages/salt/utils/event.py", line 525, in get_event
    ret = self._get_event(wait, tag, match_func, no_block)
  File "/usr/lib/python2.7/site-packages/salt/utils/event.py", line 452, in _get_event
    log.trace('get_event() received = {0}'.format(ret))
  File "/usr/lib/python2.7/site-packages/salt/log/mixins.py", line 35, in trace
    self.log(getattr(logging, 'TRACE', 5), msg, *args, **kwargs)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1213, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/log/setup.py", line 278, in _log
    self, level, msg, args, exc_info=exc_info, extra=extra
  File "/usr/lib64/python2.7/logging/__init__.py", line 1267, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/usr/lib/python2.7/site-packages/salt/log/setup.py", line 305, in makeRecord
    exc_info, func)
  File "/usr/lib/python2.7/site-packages/salt/log/setup.py", line 162, in __init__
    self.colormsg = '%s%s%s' % (cmsg, self.msg, reset)
MemoryError
Traceback (most recent call last):
  File "/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 458, in salt_main
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/salt.py", line 200, in run
    for full_ret in cmd_func(**kwargs):
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 606, in cmd_cli
    **kwargs):
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 1255, in get_cli_event_returns
    expect_minions=(verbose or show_timeout)
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 886, in get_iter_returns
    for raw in ret_iter:
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 823, in get_returns_no_block
    raw = self.event.get_event(wait=0.01, tag=tag, match_type=match_type, full=True, no_block=True)
  File "/usr/lib/python2.7/site-packages/salt/utils/event.py", line 525, in get_event
    ret = self._get_event(wait, tag, match_func, no_block)
  File "/usr/lib/python2.7/site-packages/salt/utils/event.py", line 452, in _get_event
    log.trace('get_event() received = {0}'.format(ret))
  File "/usr/lib/python2.7/site-packages/salt/log/mixins.py", line 35, in trace
    self.log(getattr(logging, 'TRACE', 5), msg, *args, **kwargs)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1213, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/log/setup.py", line 278, in _log
    self, level, msg, args, exc_info=exc_info, extra=extra
  File "/usr/lib64/python2.7/logging/__init__.py", line 1267, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/usr/lib/python2.7/site-packages/salt/log/setup.py", line 305, in makeRecord
    exc_info, func)
  File "/usr/lib/python2.7/site-packages/salt/log/setup.py", line 162, in __init__
    self.colormsg = '%s%s%s' % (cmsg, self.msg, reset)
MemoryError


salt --version
salt 2015.8.7 (Beryllium)

# salt --versions-report
Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 2.5.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.9.0
timelib: Not Installed

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-229.14.1.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
