### ISSUE TITLE
JSON Render Failed for mysql_grants.present

### ISSUE THREAD

**Issue by Xiol** [saltstack/salt#26380]
Hi,

We're getting the following error when trying to use JSON output with `mysql_grants.present` and `salt-ssh`:

```python-traceback
[ERROR   ] JSON Render failed for:
Traceback (most recent call last):
  File "/var/lib/acmecorp/salt/salt-call", line 15, in <module>
    salt_call()
  File "/var/lib/acmecorp/salt/py2/salt/scripts.py", line 224, in salt_call
    client.run()
  File "/var/lib/acmecorp/salt/py2/salt/cli/call.py", line 50, in run
    caller.run()
  File "/var/lib/acmecorp/salt/py2/salt/cli/caller.py", line 133, in run
    ret = self.call()
  File "/var/lib/acmecorp/salt/py2/salt/cli/caller.py", line 196, in call
    ret['return'] = func(*args, **kwargs)
  File "/var/lib/acmecorp/salt/py2/salt/modules/state.py", line 1179, in pkg
    ret = st_.call_chunks(lowstate)
  File "/var/lib/acmecorp/salt/py2/salt/state.py", line 1651, in call_chunks
    running = self.call_chunk(low, running, chunks)
  File "/var/lib/acmecorp/salt/py2/salt/state.py", line 1819, in call_chunk
    self._mod_init(low)
  File "/var/lib/acmecorp/salt/py2/salt/state.py", line 635, in _mod_init
    self.states['{0}.{1}'.format(low['state'], low['fun'])]  # pylint: disable=W0106
  File "/var/lib/acmecorp/salt/py2/salt/utils/lazy.py", line 93, in __getitem__
    raise KeyError(key)
KeyError: 'mysql_grants.present'
```

The problematic state:

```saltstack
bacula_localhost:
  mysql_grants.present:
    - grant: all privileges
    - database: bacula.*
    - user: bacula
    - host: localhost
    - require:
      - cmd: /usr/lib64/bacula/make_bacula_tables
```

Versions:

```yaml
Salt Version:
           Salt: 2015.8.0-201-g342e0c0

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
       pycrypto: 2.6.1

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-32-generic
         system: Ubuntu 14.04 trusty
```

Thanks

/cc @zyio

**Comment by jfindlay** [comment]
@Xiol, thanks for the report.  Do you have the mysql python package installed on the system you are running salt-ssh from (probably `MySQL-python`)?

**Comment by dangarthwaite** [comment]
I'm also getting this error when running 'salt-call --local state.highstate' in a newly provisioned vagrant box.

**Comment by Xiol** [comment]
Sorry, forgot about this bug until I've just come across it again now - installing `MySQL-python` package on the remote fixed this issue.

Perhaps a better error message wouldn't go amiss for this one, but otherwise I'm closing this as it's not really a bug but more RTFM.
