### ISSUE TITLE
pip install -e issue on 2015.8

### ISSUE THREAD

**Issue by s0undt3ch** [saltstack/salt#26444]
```
Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/home/erik/git/salt/main/setup.py", line 1203, in <module>

    setup(distclass=SaltDistribution)

  File "/usr/lib64/python2.7/distutils/core.py", line 137, in setup

    ok = dist.parse_command_line()

  File "/home/erik/git/salt/main/setup.py", line 1167, in parse_command_line

    args = distutils.dist.Distribution.parse_command_line(self)

  File "/home/erik/saltdev/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/dist.py", line 271, in parse_command_line

  File "/usr/lib64/python2.7/distutils/dist.py", line 467, in parse_command_line

    args = self._parse_command_opts(parser, args)

  File "/home/erik/saltdev/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/dist.py", line 590, in _parse_command_opts

  File "/usr/lib64/python2.7/distutils/dist.py", line 564, in _parse_command_opts

    (args, opts) = parser.getopt(args[1:])

  File "/usr/lib64/python2.7/distutils/fancy_getopt.py", line 253, in getopt

    self._grok_option_table()

  File "/usr/lib64/python2.7/distutils/fancy_getopt.py", line 222, in _grok_option_table

    "(must be letters, numbers, hyphens only") % long

distutils.errors.DistutilsGetoptError: invalid long option name 'write_salt_version' (must be letters, numbers, hyphens only
```

**Comment by terminalmage** [comment]
Fixed in #26449.
