### ISSUE TITLE
Several pyobjects tests failing on RHEL 7

### ISSUE THREAD

**Issue by terminalmage** [saltstack/salt#26571]
```
 --------  Tests with Errors  --------------------------------------------------
   -> unit.pyobjects_test.MapTests.test_map  ...................................
       Traceback (most recent call last):
         File "/builddir/build/BUILD/salt-2015.5.5/salt-2015.5.5/tests/unit/pyobjects_test.py", line 367, in test_map
           ret = samba_with_grains({'os_family': 'Debian', 'os': 'Debian'})
         File "/builddir/build/BUILD/salt-2015.5.5/salt-2015.5.5/tests/unit/pyobjects_test.py", line 352, in samba_with_grains
           return self.render(map_template, {'grains': grains})
         File "/builddir/build/BUILD/salt-2015.5.5/salt-2015.5.5/tests/unit/pyobjects_test.py", line 254, in render
           state.opts['renderer'])
         File "/builddir/build/BUILD/salt-2015.5.5/salt-2015.5.5/salt/template.py", line 79, in compile_template
           ret = render(input_data, saltenv, sls, **render_kwargs)
         File "/builddir/build/BUILD/salt-2015.5.5/salt-2015.5.5/salt/renderers/pyobjects.py", line 435, in render
           exec_(final_template, _globals)
         File "/builddir/build/BUILD/salt-2015.5.5/salt-2015.5.5/salt/ext/six.py", line 645, in exec_
           exec("""exec _code_ in _globs_, _locs_""")
         File "<string>", line 1, in <module>
         File "<string>", line 21, in <module>
       NameError: name 'Service' is not defined
   .............................................................................
   -> unit.pyobjects_test.RendererTests.test_extend  ...........................
       Traceback (most recent call last):
         File "/builddir/build/BUILD/salt-2015.5.5/salt-2015.5.5/tests/unit/pyobjects_test.py", line 286, in test_extend
           'os': 'Debian'
         File "/builddir/build/BUILD/salt-2015.5.5/salt-2015.5.5/tests/unit/pyobjects_test.py", line 254, in render
           state.opts['renderer'])
         File "/builddir/build/BUILD/salt-2015.5.5/salt-2015.5.5/salt/template.py", line 79, in compile_template
           ret = render(input_data, saltenv, sls, **render_kwargs)
         File "/builddir/build/BUILD/salt-2015.5.5/salt-2015.5.5/salt/renderers/pyobjects.py", line 435, in render
           exec_(final_template, _globals)
         File "/builddir/build/BUILD/salt-2015.5.5/salt-2015.5.5/salt/ext/six.py", line 645, in exec_
           exec("""exec _code_ in _globs_, _locs_""")
         File "<string>", line 1, in <module>
         File "<string>", line 3, in <module>
       NameError: name 'Service' is not defined
   .............................................................................
   -> unit.pyobjects_test.RendererTests.test_requisite_implicit_list  ..........
       Traceback (most recent call last):
         File "/builddir/build/BUILD/salt-2015.5.5/salt-2015.5.5/tests/unit/pyobjects_test.py", line 333, in test_requisite_implicit_list
           'os': 'Debian'
         File "/builddir/build/BUILD/salt-2015.5.5/salt-2015.5.5/tests/unit/pyobjects_test.py", line 254, in render
           state.opts['renderer'])
         File "/builddir/build/BUILD/salt-2015.5.5/salt-2015.5.5/salt/template.py", line 79, in compile_template
           ret = render(input_data, saltenv, sls, **render_kwargs)
         File "/builddir/build/BUILD/salt-2015.5.5/salt-2015.5.5/salt/renderers/pyobjects.py", line 435, in render
           exec_(final_template, _globals)
         File "/builddir/build/BUILD/salt-2015.5.5/salt-2015.5.5/salt/ext/six.py", line 645, in exec_
           exec("""exec _code_ in _globs_, _locs_""")
         File "<string>", line 1, in <module>
         File "<string>", line 3, in <module>
       NameError: name 'Service' is not defined
   .............................................................................
   -> unit.pyobjects_test.RendererTests.test_sls_imports  ......................
       Traceback (most recent call last):
         File "/builddir/build/BUILD/salt-2015.5.5/salt-2015.5.5/tests/unit/pyobjects_test.py", line 316, in test_sls_imports
           render_and_assert(import_template)
         File "/builddir/build/BUILD/salt-2015.5.5/salt-2015.5.5/tests/unit/pyobjects_test.py", line 304, in render_and_assert
           'os': 'Debian'
         File "/builddir/build/BUILD/salt-2015.5.5/salt-2015.5.5/tests/unit/pyobjects_test.py", line 254, in render
           state.opts['renderer'])
         File "/builddir/build/BUILD/salt-2015.5.5/salt-2015.5.5/salt/template.py", line 79, in compile_template
           ret = render(input_data, saltenv, sls, **render_kwargs)
         File "/builddir/build/BUILD/salt-2015.5.5/salt-2015.5.5/salt/renderers/pyobjects.py", line 403, in render
           exec_(state_contents, _globals, state_locals)
         File "/builddir/build/BUILD/salt-2015.5.5/salt-2015.5.5/salt/ext/six.py", line 645, in exec_
           exec("""exec _code_ in _globs_, _locs_""")
         File "<string>", line 1, in <module>
         File "<string>", line 21, in <module>
       NameError: name 'Service' is not defined
   .............................................................................
   -> unit.pyobjects_test.StateTests.test_context_manager  .....................
       Traceback (most recent call last):
         File "/builddir/build/BUILD/salt-2015.5.5/salt-2015.5.5/tests/unit/pyobjects_test.py", line 134, in test_context_manager
           Registry.states['/usr/local/bin/pydmesg'],
       KeyError: '/usr/local/bin/pydmesg'
   .............................................................................
   -> unit.pyobjects_test.StateTests.test_factory_serialization  ...............
       Traceback (most recent call last):
         File "/builddir/build/BUILD/salt-2015.5.5/salt-2015.5.5/tests/unit/pyobjects_test.py", line 125, in test_factory_serialization
           Registry.states['/usr/local/bin/pydmesg'],
       KeyError: '/usr/local/bin/pydmesg'
   .............................................................................
   -> unit.pyobjects_test.StateTests.test_salt_data  ...........................
       Traceback (most recent call last):
         File "/builddir/build/BUILD/salt-2015.5.5/salt-2015.5.5/tests/unit/pyobjects_test.py", line 160, in test_salt_data
           Registry.states['/usr/local/bin/pydmesg'],
       KeyError: '/usr/local/bin/pydmesg'
   .............................................................................
 -------------------------------------------------------------------------------
```

**Comment by terminalmage** [comment]
Found another:

```
   .............................................................................
   -> unit.pyobjects_test.StateTests.test_duplicates  ..........................
       Traceback (most recent call last):
         File "/builddir/build/BUILD/salt-2015.5.5/salt-2015.5.5/tests/unit/pyobjects_test.py", line 179, in test_duplicates
           self.assertRaises(DuplicateState, add_dup)
       AssertionError: DuplicateState not raised
   .............................................................................
 ```
