### ISSUE TITLE
postgresql_user state generates a bool error

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt#26616]
I get the following error when trying to add a postgres user:

```
ID: create_postgres_user
    Function: postgres_user.present
        Name: user-name
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.6/site-packages/salt/state.py", line 1542, in call
                  **cdata['kwargs'])
                File "/usr/lib64/python2.6/contextlib.py", line 34, in __exit__
                  self.gen.throw(type, value, traceback)
                File "/usr/lib/python2.6/site-packages/salt/utils/context.py", line 41, in func_globals_inject
                  yield
                File "/usr/lib/python2.6/site-packages/salt/state.py", line 1542, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.6/site-packages/salt/states/postgres_user.py", line 216, in present
                  if password is not None and (refresh_password or user_attr['password'] != password):
              TypeError: 'bool' object is unsubscriptable
     Started: 19:33:19.893314
    Duration: 87.692 ms
     Changes:
```

Note that this is on 2014.7.6, but the same code is present currently:

https://github.com/saltstack/salt/blob/develop/salt/states/postgres_user.py#L187

I'm not exactly sure what causes this, as the exact same code snippet was working perfectly fine prior to this with the same code. I'm just adding a postgres user with the name and password set to pillar values, however with the password (and username) set to a static value it still generates the error above.

**Comment by jfindlay** [comment]
@gravyboat, thanks for the report.
