### ISSUE TITLE
salt on MacOS X - adding python RAET lib breaks "salt-call --versions" output

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt#26665]
On a Mac OS X 10.10.5 
`uname -a` is reporting: 

```
Darwin uk-it-100 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_6
```

and my `salt-call --versions` is reporting:

```
           Salt: 2015.5.5
         Python: 2.6.9 (unknown, Jul 14 2015, 19:46:31)
         Jinja2: 2.8
       M2Crypto: 0.22
 msgpack-python: 0.4.6
   msgpack-pure: 0.1.3
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: 1.3.9
          PyZMQ: 14.7.0
           RAET: Not Installed
            ZMQ: 4.1.3
           Mako: 1.0.1
        Tornado: 4.2.1
        timelib: Not Installed
       dateutil: 2.4.2
```

**But if I do** a `pip install -U RAET`, this adds both `RAET` and `libnacl`, as expected.

log of `pip install -U RAET`:

```
pip install RAET 
Collecting RAET
/Library/Python/2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached raet-0.6.3.tar.gz
Requirement already satisfied (use --upgrade to upgrade): ioflo>=1.2.1 in /Library/Python/2.6/site-packages (from RAET)
Collecting libnacl>=1.4.0 (from RAET)
  Using cached libnacl-1.4.3.tar.gz
Requirement already satisfied (use --upgrade to upgrade): six>=1.6.1 in /Library/Python/2.6/site-packages (from RAET)
Requirement already satisfied (use --upgrade to upgrade): importlib>=1.0.3 in /Library/Python/2.6/site-packages (from RAET)
Requirement already satisfied (use --upgrade to upgrade): argparse>=1.2.1 in /Library/Python/2.6/site-packages (from RAET)
Requirement already satisfied (use --upgrade to upgrade): enum34>=1.0.4 in /Library/Python/2.6/site-packages (from RAET)
Requirement already satisfied (use --upgrade to upgrade): ordereddict in /Library/Python/2.6/site-packages (from enum34>=1.0.4->RAET)
Installing collected packages: libnacl, RAET
  Running setup.py install for libnacl
  Running setup.py install for RAET
Successfully installed RAET-0.6.3 libnacl-1.4.3
```

**But after that** the `salt-call --versions` "breaks" and only shows:

```
salt-call --versions
Traceback (most recent call last):
  File "/usr/local/bin/salt-call", line 9, in <module>
    load_entry_point('salt==2015.5.5', 'console_scripts', 'salt-call')()
  File "/Library/Python/2.6/site-packages/salt/scripts.py", line 221, in salt_call
    import salt.cli.call
  File "/Library/Python/2.6/site-packages/salt/cli/call.py", line 9, in <module>
    import salt.cli.caller
  File "/Library/Python/2.6/site-packages/salt/cli/caller.py", line 35, in <module>
    from raet import raeting, nacling
  File "/Library/Python/2.6/site-packages/raet/__init__.py", line 12, in <module>
    importlib.import_module(".{0}".format(m), package='raet')
  File "/Library/Python/2.6/site-packages/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Library/Python/2.6/site-packages/raet/nacling.py", line 11, in <module>
    import libnacl
  File "/Library/Python/2.6/site-packages/libnacl/__init__.py", line 89, in <module>
    nacl = _get_nacl()
  File "/Library/Python/2.6/site-packages/libnacl/__init__.py", line 55, in _get_nacl
    raise OSError(msg)
OSError: Could not locate nacl lib, searched for libsodium, tweetnacl
```

Until I do a `pip unistall libnacl RAET`, after which `salt-call --versions` works again as expected.

PS: I "think" I had seen the same (or very similar) issue with the `python RAET` and `ibnacl` lib on windows around the early 2015.5 series, but on a `2015.8.0rc3` I no longer see that issue there.

**Comment by jfindlay** [comment]
@TheBigBear, thanks for the report.
