### ISSUE TITLE
Salt-Master 2015.5.5-1 on Scientific Linux 6 fails loading some primitive pillars from YAML

### ISSUE THREAD

**Issue by Galser** [saltstack/salt#26705]
After update of Salt-Master to Salt : 2015.5.5-1 from EPEL-Testing on Scientific Linux 6, can't catch what exactly had happened, but  the very same pillars loading failing :  

Machine running : 
```Scientific Linux release 6.5 (Carbon)```

Example of simple failing pillar 
```yaml
graphite_server: tkgraphite-01.tkl.local
graphite_web: graphite.tkl.local
graphite:
  config:
    port: 2003
    pickle_port: 2004
```

Refresh pillar  fails with error : 
```
2015-08-27 16:30:05,751 [salt.master                              ][ERROR   ][31359] Error in function _p
Traceback (most recent call last):                                                                       
  File "/usr/lib/python2.6/site-packages/salt/master.py", line 1460, in run_func                         
    ret = getattr(self, func)(load)                                                                      
  File "/usr/lib/python2.6/site-packages/salt/master.py", line 1236, in _pillar                          
    'pillar': data})                                                                                     
  File "/usr/lib/python2.6/site-packages/salt/payload.py", line 122, in dumps                            
    except (OverflowError, msgpack.exceptions.PackValueError):                                           
AttributeError: 'module' object has no attribute 'exceptions
```
Here are the versions (Salt-Master, minion, ssh, api - everything ):
```
           Salt: 2015.5.5                                                                                            
         Python: 2.6.6 (r266:84292, Jul 22 2015, 16:47:47)                                                           
         Jinja2: 2.2.1                                                                                               
       M2Crypto: 0.20.2                                                                                              
 msgpack-python: 0.1.13                                                                                              
   msgpack-pure: Not Installed                                                                                       
       pycrypto: 2.0.1                                                                                               
        libnacl: Not Installed                                                                                       
         PyYAML: 3.10                                                                                                
          ioflo: Not Installed                                                                                       
          PyZMQ: 14.3.1                                                                                              
           RAET: Not Installed                                                                                       
            ZMQ: 3.2.4                                                                                               
           Mako: Not Installed                                                                                       
        Tornado: Not Installed
```
After downgrading back to previous, stable version, on the same machine : 
```
           Salt: 2015.5.3                                                                                            
         Python: 2.6.6 (r266:84292, Jul 22 2015, 16:47:47)                                                           
         Jinja2: 2.2.1                                                                                               
       M2Crypto: 0.20.2                                                                                              
 msgpack-python: 0.1.13                                                                                              
   msgpack-pure: Not Installed                                                                                       
       pycrypto: 2.0.1                                                                                               
        libnacl: Not Installed                                                                                       
         PyYAML: 3.10                                                                                                
          ioflo: Not Installed                                                                                       
          PyZMQ: 14.3.1                                                                                              
           RAET: Not Installed                                                                                       
            ZMQ: 3.2.4                                                                                               
           Mako: Not Installed                                                                                       
        Tornado: Not Installed
```
All runs ok. I already running the **2015.5.3**, but maybe, from Monday - I can try to upgrade, and play again with pillars to help somehow.
And yes, running in debug mode, not actually makes the situation clear. The same error. Strange that when running with log-level **debug** I can see Salt-Master loading HUGE complex pillar, and failing on a pillar consisting of just 4 lines.

**Comment by jfindlay** [comment]
@Galser, thanks for the report.  It looks like older versions of msgpack don't have an exceptions module.

**Comment by Galser** [comment]
@jfindlay , maybe. I will try to do test with a forced update of msgpack on Monday, and then, post results here.

**Comment by ahammond** [comment]
Any idea when 2015.5.6 or 2015.8.? will be released? This currently has me blocked.

**Comment by jfindlay** [comment]
@ahammond, 2015.8.0 has already been released, and we're working on a 2015.5.6 release right now.

**Comment by ahammond** [comment]
@jfindlay I'll give 2015.8.0 a try and see if it fixes this. :)

**Comment by jfindlay** [comment]
@ahammond, sorry, I'm failing at communicating today, see http://repo.saltstack.com/.

**Comment by ahammond** [comment]
@jfindlay I'm actually doing a little happy dance right now. Thanks!!!

**Comment by rallytime** [comment]
@Galser or @ahammond Is this issue good to close? Or does more work need to be done here?

**Comment by ahammond** [comment]
Works for me, but I didn't open the bug. :)
