### ISSUE TITLE
KeyError: 'pillar' when using I@ compound match in pillar top.sls

### ISSUE THREAD

**Issue by rhansen** [saltstack/salt#26727]
With the following pillar files:
- `top.sls`:
  
  ```
  base:
    '*':
      - roles
    'I@roles:foo':
      - match: compound
      - foo
  ```
- `roles.sls`:
  
  ```
  roles:
    - foo
  ```
- `foo.sls`:
  
  ```
  foo: bar
  ```

I get the following error in the minions:

```
2015-08-28 02:27:29,664 [salt.pillar      ][ERROR   ][17476] Got a bad pillar from master, type str, expecting dict: 
```

and the following error in `/var/log/salt/master`:

```
2015-08-28 02:27:57,036 [salt.master      ][ERROR   ][14016] Error in function _pillar:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 1457, in run_func
    ret = getattr(self, func)(load)
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 1220, in _pillar
    data = pillar.compile_pillar(pillar_dirs=pillar_dirs)
  File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 578, in compile_pillar
    matches = self.top_matches(top)
  File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 353, in top_matches
    self.opts.get('nodegroups', {}),
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 2656, in confirm_top
    return getattr(self, funcname)(match)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 2848, in compound_match
    '@'.join(comps[1:])
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 2749, in pillar_match
    self.opts['pillar'], tgt, delimiter=delimiter
KeyError: 'pillar'
```

If I set `ext_pillar_first: True` in `/etc/salt/master` then the errors go away, but the `foo:bar` pillar setting isn't set (though `roles:foo` is).

I'm using Salt 2015.5.3 (from the saltstack/salt PPA) on Ubuntu 14.04 64-bit server.

**Comment by jfindlay** [comment]
@richardhansen, thanks for the report.

**Comment by bobrik** [comment]
Any news on this one?

**Comment by jfindlay** [comment]
@bobrik, not that I know of.  No one has been assigned to this issue.

**Comment by dkiser** [comment]
Just hit this as well.
