### ISSUE TITLE
2015.8.0rc4_TheBigBear git rel. 'gcb9fddd' global name 'PER_REMOTE_PARAMS' is not defined

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt#26743]
This might all be based on the issue behind #26739 or probably #26740 

but ```salt-call --local winrepo.update_git_repos``` comes up with a key error, which I guess means it didn't get set, which is probably as it says because ```__opts__``` are missing

So I won't create any more issues now. ;-)

```
C:\salt-dev\salt>salt-call  --local winrepo.update_git_repos
[ERROR   ] Failed to import log_handlers sentry_mod, this is due most likely to
a syntax error:
Traceback (most recent call last):
  File "c:\salt-dev\salt\salt\loader.py", line 1105, in _load_module
    ), fn_, fpath, desc)
  File "c:\salt-dev\salt\salt\log\handlers\sentry_mod.py", line 96, in <module>
    __grains__ = salt.loader.grains(__opts__)
NameError: name '__opts__' is not defined
[ERROR   ] An un-handled exception was caught by salt's global exception handler
:
KeyError: 'winrepo_remotes_ng'
Traceback (most recent call last):
  File "c:\python27\scripts\salt-call-script.py", line 9, in <module>
    load_entry_point('salt===2015.8.0rc3-114-g2f9b40c', 'console_scripts', 'salt
-call')()
  File "c:\salt-dev\salt\salt\scripts.py", line 331, in salt_call
    client.run()
  File "c:\salt-dev\salt\salt\cli\call.py", line 50, in run
    caller.run()
  File "c:\salt-dev\salt\salt\cli\caller.py", line 133, in run
    ret = self.call()
  File "c:\salt-dev\salt\salt\cli\caller.py", line 196, in call
    ret['return'] = func(*args, **kwargs)
  File "c:\salt-dev\salt\salt\modules\win_repo.py", line 101, in update_git_repo
s
    return _update_git_repos(opts=__opts__, masterless=True)
  File "c:\salt-dev\salt\salt\runners\winrepo.py", line 177, in update_git_repos

    (opts['winrepo_remotes_ng'], opts['winrepo_dir_ng'])]
KeyError: 'winrepo_remotes_ng'
Traceback (most recent call last):
  File "c:\python27\scripts\salt-call-script.py", line 9, in <module>
    load_entry_point('salt===2015.8.0rc3-114-g2f9b40c', 'console_scripts', 'salt
-call')()
  File "c:\salt-dev\salt\salt\scripts.py", line 331, in salt_call
    client.run()
  File "c:\salt-dev\salt\salt\cli\call.py", line 50, in run
    caller.run()
  File "c:\salt-dev\salt\salt\cli\caller.py", line 133, in run
    ret = self.call()
  File "c:\salt-dev\salt\salt\cli\caller.py", line 196, in call
    ret['return'] = func(*args, **kwargs)
  File "c:\salt-dev\salt\salt\modules\win_repo.py", line 101, in update_git_repo
s
    return _update_git_repos(opts=__opts__, masterless=True)
  File "c:\salt-dev\salt\salt\runners\winrepo.py", line 177, in update_git_repos

    (opts['winrepo_remotes_ng'], opts['winrepo_dir_ng'])]
KeyError: 'winrepo_remotes_ng'
```

**Comment by basepi** [comment]
The sentry handler error should be gone, but I'm unsure if that will fix your second error. Test please?

**Comment by TheBigBear** [comment]
@basepi @twangboy, no this is still there.

**Comment by UtahDave** [comment]
I think I know what's going on here.

Working on it.

**Comment by UtahDave** [comment]
@TheBigBear do you have `winrepo_remotes_ng` configured in your minion config?

**Comment by TheBigBear** [comment]
@UtahDave dohh, so sorry, shoudl have remembered, but the new salt rc4 install blewa away the old minion file that had the values in. ;-) 

OK, BUT now that this is set I __still__ get an error.
```
C:\salt-dev\salt>salt-call  --local winrepo.update_git_repos
[ERROR   ] Failed to update winrepo_remotes: global name 'PER_REMOTE_PARAMS' is
not defined
local:
    Failed to update winrepo_remotes: global name 'PER_REMOTE_PARAMS' is not def
ined
```

**Comment by UtahDave** [comment]
@TheBigBear ok, I'm going to ask @terminalmage to take a look at this. He's been involved in this code recently. He might have some insights here.

**Comment by terminalmage** [comment]
Should be fixed by https://github.com/saltstack/salt/commit/a3b7668256e90bb7647f3b684db6a749428dddaf, part of https://github.com/saltstack/salt/pull/26751

**Comment by TheBigBear** [comment]
@terminalmage ok, thanks, this error has now gone, so this can be closed. I will have to continue the winrepo + new winrepo-ng testing tomorrow, it is close to midnight here now. Have a great weekend.
