### ISSUE TITLE
2015.8.0rc4_TheBigBear git rel. 'gcb9fddd' NameError: global name 'six' is not defined

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt#26748]
I know that ```salt-call --local winrepo.genrepo``` is no longer supposed to be there for a windows minion >=2015.8, but I don't think trying to use it it should give me this error?

```salt-call  --local winrepo.genrepo``` gives

```
[ERROR   ] An un-handled exception was caught by salt's global exception handler
:
NameError: global name 'six' is not defined
Traceback (most recent call last):
  File "c:\python27\scripts\salt-call-script.py", line 9, in <module>
    load_entry_point('salt===2015.8.0rc3-114-g2f9b40c', 'console_scripts', 'salt
-call')()
  File "c:\salt-dev\salt\salt\scripts.py", line 331, in salt_call
    client.run()
  File "c:\salt-dev\salt\salt\cli\call.py", line 50, in run
    caller.run()
  File "c:\salt-dev\salt\salt\cli\caller.py", line 133, in run
    ret = self.call()
  File "c:\salt-dev\salt\salt\cli\caller.py", line 196, in call
    ret['return'] = func(*args, **kwargs)
  File "c:\salt-dev\salt\salt\modules\win_repo.py", line 75, in genrepo
    return _genrepo(opts=__opts__, fire_event=False)
  File "c:\salt-dev\salt\salt\runners\winrepo.py", line 93, in genrepo
    for pkgname, versions in six.iteritems(config):
NameError: global name 'six' is not defined
Traceback (most recent call last):
  File "c:\python27\scripts\salt-call-script.py", line 9, in <module>
    load_entry_point('salt===2015.8.0rc3-114-g2f9b40c', 'console_scripts', 'salt
-call')()
  File "c:\salt-dev\salt\salt\scripts.py", line 331, in salt_call
    client.run()
  File "c:\salt-dev\salt\salt\cli\call.py", line 50, in run
    caller.run()
  File "c:\salt-dev\salt\salt\cli\caller.py", line 133, in run
    ret = self.call()
  File "c:\salt-dev\salt\salt\cli\caller.py", line 196, in call
    ret['return'] = func(*args, **kwargs)
  File "c:\salt-dev\salt\salt\modules\win_repo.py", line 75, in genrepo
    return _genrepo(opts=__opts__, fire_event=False)
  File "c:\salt-dev\salt\salt\runners\winrepo.py", line 93, in genrepo
    for pkgname, versions in six.iteritems(config):
NameError: global name 'six' is not defined
```

**Comment by twangboy** [comment]
This should be fixed by: https://github.com/saltstack/salt/pull/26822

**Comment by terminalmage** [comment]
Fix was merged, closing.
