### ISSUE TITLE
SmartOS/Illumos broken again on 2015.8

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#26760]
Just pulled in all 2015.8 changes after my PR into my fork... it's broken again

```
[root@core ~]# /opt/local/salt/bin/salt-call --local grains.items
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "__main__.py", line 128, in <module>
  File "__main__salt-call__.py", line 14, in <module>
  File "salt/scripts.py", line 325, in salt_call
  File "salt/cli/call.py", line 6, in <module>
  File "salt/utils/parsers.py", line 26, in <module>
  File "salt/config.py", line 35, in <module>
  File "salt/syspaths.py", line 108, in <module>
AttributeError: 'module' object has no attribute 'SPM_FORMULA_PATH'
```

Seems to be commit f4723efe6862dfc9b34e48291f428701fc3594be that broke it.

**Comment by sjorge** [comment]
Closing as this is now fixed in 2015.8, Like usual this will get merged forward into develop soonish.
