### ISSUE TITLE
salt master and minion won't start on develop version wrong config dir

### ISSUE THREAD

**Issue by aboe76** [saltstack/salt#26774]
With the salt version 2015.8.0rc3.2212.gf66b18d, the salt master and the salt minion won't start,
something changed in how it's reading the configuration files:

```
salt-master -l debug

WARNING: CONFIG 'None' directory does not exist.
[DEBUG   ] Missing configuration file: /etc/salt/master.d/None/master
[DEBUG   ] Configuration file path: None/master
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
IOError: [Errno 21] Is a directory: '/etc/salt/master.d/None/master'
Traceback (most recent call last):
  File "/usr/bin/salt-master", line 22, in <module>
    salt_master()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 47, in salt_master
    master.start()
  File "/usr/lib/python2.7/site-packages/salt/cli/daemons.py", line 149, in start
    self.prepare()
  File "/usr/lib/python2.7/site-packages/salt/cli/daemons.py", line 108, in prepare
    verify_files([logfile], self.config['user'])
  File "/usr/lib/python2.7/site-packages/salt/utils/verify.py", line 172, in verify_files
    with salt.utils.fopen(fn_, 'w+') as fp_:
  File "/usr/lib/python2.7/site-packages/salt/utils/__init__.py", line 1213, in fopen
    fhandle = open(*args, **kwargs)
IOError: [Errno 21] Is a directory: '/etc/salt/master.d/None/master'
Traceback (most recent call last):
  File "/usr/bin/salt-master", line 22, in <module>
    salt_master()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 47, in salt_master
    master.start()
  File "/usr/lib/python2.7/site-packages/salt/cli/daemons.py", line 149, in start
    self.prepare()
  File "/usr/lib/python2.7/site-packages/salt/cli/daemons.py", line 108, in prepare
    verify_files([logfile], self.config['user'])
  File "/usr/lib/python2.7/site-packages/salt/utils/verify.py", line 172, in verify_files
    with salt.utils.fopen(fn_, 'w+') as fp_:
  File "/usr/lib/python2.7/site-packages/salt/utils/__init__.py", line 1213, in fopen
    fhandle = open(*args, **kwargs)
IOError: [Errno 21] Is a directory: '/etc/salt/master.d/None/master'

^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/multiprocessing/util.py", line 325, in _exit_function
    p.join()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 145, in join
    res = self._popen.wait(timeout)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 154, in wait
    return self.poll(0)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 135, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Error in sys.exitfunc:
```

and the salt minion:
```
salt-minion -l debug

[DEBUG   ] Missing configuration file: /etc/salt/master.d/None/minion
[DEBUG   ] Guessing ID. The id can be explicitly set in None/minion
[INFO    ] Found minion id from generate_minion_id(): xxx.xxx.xxx
[DEBUG   ] Configuration file path: None/minion
[ERROR   ] Minion failed to start: 
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 81, in minion_process
    minion.start()
  File "/usr/lib/python2.7/site-packages/salt/cli/daemons.py", line 275, in start
    self.prepare()
  File "/usr/lib/python2.7/site-packages/salt/cli/daemons.py", line 228, in prepare
    verify_files([logfile], self.config['user'])
  File "/usr/lib/python2.7/site-packages/salt/utils/verify.py", line 172, in verify_files
    with salt.utils.fopen(fn_, 'w+') as fp_:
  File "/usr/lib/python2.7/site-packages/salt/utils/__init__.py", line 1213, in fopen
    fhandle = open(*args, **kwargs)
IOError: [Errno 21] Is a directory: '/etc/salt/master.d/None/minion'
[WARNING ] ** Restarting minion **
[INFO    ] Sleeping random_reauth_delay of 1 seconds
```

**Comment by s0undt3ch** [comment]
You're not tweaking the syspaths when running setup right?

**Comment by aboe76** [comment]
No I'm using the defaults only option is to compile both transport protocols

Op zo 30 aug. 2015 13:03 schreef Pedro Algarvio <notifications@github.com>:

**Comment by techdragon** [comment]
Clean install from the current git `develop` branch, using `python setup.py install` and then installing the dependencies afterwards.

I see the same behaviour.

**Comment by aboe76** [comment]
@techdragon thanks for confirming this.

**Comment by s0undt3ch** [comment]
Thanks. We'll clean that up.

**Comment by s0undt3ch** [comment]
I know where the problem is. I'll have a PR this morning to fix it.
