### ISSUE TITLE
salt-call minor breakage on Windows

### ISSUE THREAD

**Issue by styro** [saltstack/salt#26773]
Salt 2015.5.2 on Windows 2012R2. Doesn't prevent the command working, just sprinkles ugly tracebacks throughout the output. eg:

```python-traceback
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 227, in salt_call
    client.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\call.py", line 67, in run
    self.exit(os.EX_OK)
AttributeError: 'module' object has no attribute 'EX_OK'
```

Looks like there's a few exitcode stragglers still using `os._EX_*` instead of `salt.defaults.exitcodes.EX_*`

**Comment by jfindlay** [comment]
@styro, thanks for fixing this.
