### ISSUE TITLE
salt-cloud gives AttributeError: 'module' object has no attribute '_create_loader'

### ISSUE THREAD

**Issue by hernanc** [saltstack/salt#26795]
Hi there, I'm having an issue with salt-cloud in 2015.5.2 and 2015.5.3.
Just running salt-cloud (or salt-cloud -m /path/to/map/file.conf ) throws:
```
$ salt-cloud -m /maps/london.map
[INFO    ] salt-cloud starting
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'module' object has no attribute '_create_loader'
Traceback (most recent call last):
  File "/usr/local/bin/salt-cloud", line 14, in <module>
    main()
  File "/usr/local/bin/salt-cloud", line 10, in main
    cloud.run()
  File "/usr/local/lib/python2.7/dist-packages/saltcloud/cli.py", line 110, in run
    mapper = saltcloud.cloud.Map(self.config)
  File "/usr/local/lib/python2.7/dist-packages/saltcloud/cloud.py", line 863, in __init__
    Cloud.__init__(self, opts)
  File "/usr/local/lib/python2.7/dist-packages/saltcloud/cloud.py", line 53, in __init__
    self.clouds = saltcloud.loader.clouds(self.opts)
  File "/usr/local/lib/python2.7/dist-packages/saltcloud/loader.py", line 42, in clouds
    load = salt.loader._create_loader(
AttributeError: 'module' object has no attribute '_create_loader'
Traceback (most recent call last):
  File "/usr/local/bin/salt-cloud", line 14, in <module>
    main()
  File "/usr/local/bin/salt-cloud", line 10, in main
    cloud.run()
  File "/usr/local/lib/python2.7/dist-packages/saltcloud/cli.py", line 110, in run
    mapper = saltcloud.cloud.Map(self.config)
  File "/usr/local/lib/python2.7/dist-packages/saltcloud/cloud.py", line 863, in __init__
    Cloud.__init__(self, opts)
  File "/usr/local/lib/python2.7/dist-packages/saltcloud/cloud.py", line 53, in __init__
    self.clouds = saltcloud.loader.clouds(self.opts)
  File "/usr/local/lib/python2.7/dist-packages/saltcloud/loader.py", line 42, in clouds
    load = salt.loader._create_loader(
AttributeError: 'module' object has no attribute '_create_loader'
```
Here are my versions. Any Idea?
```
$ salt --versions-report
                  Salt: 2015.5.3
                Python: 2.7.3 (default, Jun 22 2015, 19:33:41)
                Jinja2: 2.6
              M2Crypto: 0.21.1
        msgpack-python: 0.1.10
          msgpack-pure: Not Installed
              pycrypto: 2.4.1
               libnacl: Not Installed
                PyYAML: 3.11
                 ioflo: Not Installed
                 PyZMQ: 13.0.0
                  RAET: Not Installed
                   ZMQ: 3.2.2
                  Mako: Not Installed
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1precise2
```

**Comment by hernanc** [comment]
I forgot to mention that the salt-cloud version I have is salt-cloud 0.8.9.

**Comment by hernanc** [comment]
I fixed it deinstalling it (was an odd version I had setup with easy_install) and re installing it using apt-get. I have the proper version now: salt-cloud 2015.5.3 (Lithium)
