### ISSUE TITLE
stack trace from linode driver

### ISSUE THREAD

**Issue by jfindlay** [saltstack/salt#26798]
### versions
```yaml
# salt --versions
Salt Version:
           Salt: 2015.8.0rc3-164-gae9d39c

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
           Mako: 1.0.0
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: 0.5.4
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: debian 8.1
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.1
```

### commands
```console
# salt-cloud -l debug --script-args="-D" -p linode-ubuntu-14 jmoney-ubuntu-14
```

### logs
```python-traceback
[INFO    ] Status for Linode 1279023 is 'Being Created', waiting for 'Brand New'.
[DEBUG   ] file_roots is /root/salt-pkg-tests
[DEBUG   ] file_roots is /root/precipitate
[DEBUG   ] Requesting URL https://api.linode.com/?api_key=XXXXXXXXXX using GET method
[DEBUG   ] Response Status Code: 200
[DEBUG   ] Linode Response Status Code: 200
[ERROR   ] There was a profile error: object of type 'int' has no len()
Traceback (most recent call last):
  File "/root/salt/salt/cloud/cli.py", line 275, in run
    self.config.get('names')
  File "/root/salt/salt/cloud/__init__.py", line 1410, in run_profile
    ret[name] = self.create(vm_)
  File "/root/salt/salt/cloud/__init__.py", line 1256, in create
    output = self.clouds[func](vm_)
  File "/root/salt/salt/cloud/clouds/linode.py", line 436, in create
    update_linode(node_id, update_args={'Label': vm_['name']})
  File "/root/salt/salt/cloud/clouds/linode.py", line 1280, in update_linode
    if _validate_name(linode_id) is False:
  File "/root/salt/salt/cloud/clouds/linode.py", line 1523, in _validate_name
    name_length = len(name)
TypeError: object of type 'int' has no len()
```

**Comment by jfindlay** [comment]
@rallytime, I have a fix for this if you want me to submit it.

**Comment by rallytime** [comment]
@jfindlay Can you give #26819 a try?
