### ISSUE TITLE
Erlang formatted strerr caused state module to print data instead of output

### ISSUE THREAD

**Issue by benheilman** [saltstack/salt#26802]
```
# salt-minion --version
salt-minion 2015.5.5 (Lithium)
```

```
# salt bheilman.\* state.sls database.rabbitmq.server
...
    rabbitmq_plugin_|-rabbit_server_plugin_management_|-rabbitmq_management_|-enabled:
        ----------
        __run_num__:
            8
        changes:
            ----------
        comment:
            ----------
            pid:
                27162
            retcode:
                2
            stderr:
                Error: {cannot_write_enabled_plugins_file,"/etc/rabbitmq/enabled_plugins",
                           eacces}
            stdout:
        duration:
            2968.798
        name:
            rabbitmq_management
        result:
            False
        start_time:
            16:40:32.428726
```
```
# salt-call -l debug state.sls database.rabbitmq.server
...
[DEBUG   ] LazyLoaded rabbitmq_plugin.enabled
[INFO    ] Running state [rabbitmq_management] at time 16:50:52.527618
[INFO    ] Executing state rabbitmq_plugin.enabled for rabbitmq_management
[INFO    ] Executing command '/usr/sbin/rabbitmq-plugins list -m -e' as user 'rabbitmq' in directory '/var/lib/rabbitmq'
[DEBUG   ] output:
[INFO    ] Executing command '/usr/sbin/rabbitmq-plugins enable rabbitmq_management' as user 'rabbitmq' in directory '/var/lib/rabbitmq'
[ERROR   ] Command '/usr/sbin/rabbitmq-plugins enable rabbitmq_management' failed with return code: 2
[ERROR   ] stderr: Error: {cannot_write_enabled_plugins_file,"/etc/rabbitmq/enabled_plugins",
           eacces}
[ERROR   ] retcode: 2
[ERROR   ] {'pid': 28050, 'retcode': 2, 'stderr': 'Error: {cannot_write_enabled_plugins_file,"/etc/rabbitmq/enabled_plugins",\n           eacces}', 'stdout': ''}
[INFO    ] Completed state [rabbitmq_management] at time 16:50:54.026050
```

**Comment by jfindlay** [comment]
@benheilman, thanks for the report.  I am confused about what you are expecting as a result.  It looks like there was an error applying your state because of a permission problem on `/etc/rabbitmq/enabled_plugins`.  Does the salt minion process have access to this file?

**Comment by benheilman** [comment]
The issue pertains to the output, not the actual error reported.  The output of state.sls should be state output not a data report.

**Comment by jfindlay** [comment]
@benheilman, the output looks like typical state output to me.  Can you be more specific about what makes it look like a data report?

**Comment by benheilman** [comment]
here is an example of state output on failure
```
node01.iad.jenkins.ci.ourcentro.net:
----------
          ID: rabbit_monitor_user
    Function: rabbitmq_user.present
        Name: monitor
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.6/site-packages/salt/state.py", line 1560, in call
                  **cdata['kwargs'])
                File "/usr/lib64/python2.6/contextlib.py", line 34, in __exit__
                  self.gen.throw(type, value, traceback)
                File "/usr/lib/python2.6/site-packages/salt/utils/context.py", line 42, in func_globals_inject
                  yield
                File "/usr/lib/python2.6/site-packages/salt/state.py", line 1560, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.6/site-packages/salt/states/rabbitmq_user.py", line 147, in present
                  if _check_tags_changes(name, tags):
                File "/usr/lib/python2.6/site-packages/salt/states/rabbitmq_user.py", line 70, in _check_tags_changes
                  return __salt__['rabbitmq.list_users']()[name] - set(newtags)
              KeyError: 'monitor'
     Started: 13:20:31.658026
    Duration: 1972.321 ms
     Changes:

Summary
--------------
Succeeded: 393
Failed:      1
--------------
Total states run:     394
```

**Comment by jfindlay** [comment]
@benheilman, thanks for the extra info.  I think the problem here is that `rabbitmq_plugin.enabled` is not using the highstate outputter, although the reason why is unknown to me.

**Comment by anlutro** [comment]
I had a similar problem earlier which ended up being an exception thrown in the highstate outputter module. Turn on `-l debug` and look for stack traces.

**Comment by rallytime** [comment]
@benheilman I think this is due to the bug reported in #21216, where the rabbitmq_plugin state was returning a dictionary in the `comments` section instead of a string, which causes the highstate outputter to disengage like you're seeing. I've refactored this state in #28270 to move those comment "changes" into the `changes` dict to make `rabbitma_plugin` more traditionally state-ful.

Can you give that PR a try and let me know if that clears this up for you?

**Comment by rallytime** [comment]
Since we didn't hear back, I am going to close this. If this pops up again after and upgrade, let us know and we can take another look. Thanks!
