### ISSUE TITLE
2015.5.3 Pillar include under nested key is broken

### ISSUE THREAD

**Issue by deuscapturus** [saltstack/salt#26814]
Problem is here https://github.com/saltstack/salt/blob/2015.5/salt/pillar/__init__.py#L418
Variable v is getting value of None.

pillar:
```
include:
  - narwhal:
    key: narwhal
```

error:
```
2015-09-01 10:45:36,531 [salt.loaded.int.render.yaml][DEBUG   ][32707] Results of YAML rendering: 
OrderedDict([('include', [OrderedDict([('narwhal', None), ('key', 'narwhal')])])])
2015-09-01 10:45:36,532 [salt.master      ][ERROR   ][32707] Error in function _pillar:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 1457, in run_func
    ret = getattr(self, func)(load)
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 1220, in _pillar
    data = pillar.compile_pillar(pillar_dirs=pillar_dirs)
  File "/usr/lib/python2.7/site-packages/salt/pillar/__init__.py", line 579, in compile_pillar
    pillar, errors = self.render_pillar(matches)
  File "/usr/lib/python2.7/site-packages/salt/pillar/__init__.py", line 452, in render_pillar
    pstate, mods, err = self.render_pstate(sls, saltenv, mods)
  File "/usr/lib/python2.7/site-packages/salt/pillar/__init__.py", line 415, in render_pstate
    defaults = v.get('defaults', {})
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by jfindlay** [comment]
@deuscapturus, thanks for the report.

**Comment by thatch45** [comment]
Did this ever work? I don't know that this is a bug, this looks like bad syntax in the pillar sls file

**Comment by deuscapturus** [comment]
Yes, this did work in the past. It's been in the documentation for a long time as well.  https://docs.saltstack.com/en/latest/topics/pillar/#including-other-pillars

This feature solves a lot of big problems for us.
Example: Making pillar data available to a Jenkins server to get application settings for a build process without colliding with other pillars or duplicating the pillars.

**Comment by acornett** [comment]
I'm hitting this issue as well if I use the import key like shown in the example that @deuscapturus posted up top.  

Looks like between 2014.7<sup>1</sup> and 2015.5<sup>2</sup> the code to process import keys and defaults was changed from 
```python
sub_sls, v = sub_sls.iteritems().next()
```
to 
```python
sub_sls, v = next(sub_sls.iteritems())
```
While the documentation for the python build-in ```next```<sup>3</sup> function says it delegates down to the iterator's ```next```<sup>4</sup> method, the behavior is not the same apparently.


<sup>1</sup>https://github.com/saltstack/salt/blob/2014.7/salt/pillar/__init__.py#L416
<sup>2</sup>https://github.com/saltstack/salt/blob/2015.5/salt/pillar/__init__.py#L418
<sup>3</sup>https://docs.python.org/2/library/functions.html#next
<sup>4</sup>https://docs.python.org/2/library/stdtypes.html#iterator.next

**Comment by acornett** [comment]
Here is my traceback using 2015.5.5 on CentOS 7

```
2015-10-08 12:10:26,031 [salt.master      ][ERROR   ][2274] Error in function _pillar:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 1460, in run_func
    ret = getattr(self, func)(load)
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 1223, in _pillar
    data = pillar.compile_pillar(pillar_dirs=pillar_dirs)
  File "/usr/lib/python2.7/site-packages/salt/pillar/__init__.py", line 583, in compile_pillar
    pillar, errors = self.render_pillar(matches)
  File "/usr/lib/python2.7/site-packages/salt/pillar/__init__.py", line 456, in render_pillar
    pstate, mods, err = self.render_pstate(sls, saltenv, mods)
  File "/usr/lib/python2.7/site-packages/salt/pillar/__init__.py", line 419, in render_pstate
    defaults = v.get('defaults', {})
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by frots** [comment]
Isn't this an indentation problem in the pillar file? Can you try it like follows?
```
include:
  - narwhal:
      key: narwhal
```

**Comment by acornett** [comment]
@frots, good catch!  It looks like that does resolve the issue for my usage at least.
