### ISSUE TITLE
Error 2014 using stored procedure with MySQL external pillar

### ISSUE THREAD

**Issue by jond64** [saltstack/salt#26876]
When I made one of my ext_pillar queries a stored procedure, I started getting the error below on the Salt master.  Modifying the for loop of ext_pillar() in mysql.py to get a new cursor at the beginning of every iteration and close that cursor at the end of every iteration seems to resolve the issue.  As a work around I made the stored procedure the last query for the external pillar, and that eliminated the error messages.

I'm using version 2014.7.0.  It looks like the cursor handling is the same in the 2015.5 branch.

```
2015-09-02 18:55:12,767 [salt.loaded.int.pillar.mysql               ][ERROR   ] Error in ext_pillar MySQL: (2014, "Commands out of sync; you can't run this command now")
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/pillar/mysql.py", line 226, in _get_serv
    yield cursor
  File "/usr/lib/python2.6/site-packages/salt/pillar/mysql.py", line 460, in ext_pillar
    cur.execute(details['query'], (minion_id,))
  File "/usr/lib64/python2.6/site-packages/MySQLdb/cursors.py", line 173, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib64/python2.6/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (2014, "Commands out of sync; you can't run this command now")
```

**Comment by arroyoc** [comment]
@jond64 thanks for your detailed report.

**Comment by dahabakuk** [comment]
this is still an issue in 2019.2
i started looking into procedures as queries are only allowed to have one occurence of %s (for the minion id)... and stumbled upon this problem...
