### ISSUE TITLE
2015.8 windows salt minion stops responding within about 5 - 10 minutes - at latest

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt#26887]
All three of my salt 2015.8 windows minions stop responding to ```test.ping``` or ```pkg.install``` cmds sent by the master sometime after 5 to 10 minutes. If I ```Ctrl-C``` the minion process and restart it, they respond again for anohter 5 minutes or so.

AFAICT the error in common is the last few lines at the bottom taken from a ```salt-minion -l debug``` session once it stopped responding. They all end in "KeyError: None".

```
[INFO    ] Starting a new job with PID 3536
[DEBUG   ] Could not LazyLoad pkg.normalize_name
[INFO    ] Executing command ['c:\\salt\\var\\cache\\salt\\minion\\files\\base\\win\\repo\\windirstat\\windirstat1_1_2_setup.exe', '/S'] in directory 'c:\\salt\\var\\cache\\salt\\minion\\files\\base\\win\\repo\\windirstat'
[INFO    ] User root Executing command saltutil.find_job with jid 20150903160809579015
[DEBUG   ] Command details {'tgt_type': 'glob', 'jid': '20150903160809579015', 'tgt': 'om-uk-w10-1-64', 'ret': '', 'user': 'root', 'arg': ['20150903160804560893'], 'fun': 'saltutil.find_job'}
[INFO    ] Starting a new job with PID 3536
[INFO    ] Returning information for job: 20150903160809579015
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'om-uk-w10-1-64', 'tcp://65.52.151.107:4506', 'aes')
[DEBUG   ] Initializing new SAuth for ('c:\\salt\\conf\\pki\\minion', 'om-uk-w10-1-64', 'tcp://65.52.151.107:4506')
[DEBUG   ] Error deleting fd from IOLoop
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\tornado\ioloop.py", line 715, in remove_handler
    self._impl.unregister(fd)
  File "c:\python27\lib\site-packages\zmq\eventloop\ioloop.py", line 115, in unregister
    return self._poller.unregister(fd)
  File "c:\python27\lib\site-packages\zmq\sugar\poll.py", line 71, in unregister
    idx = self._map.pop(socket)
KeyError: None
```
the 3 windows minion are all:
```
C:\Salt-Dev>salt-call --versions
Salt Version:
           Salt: 2015.8.0rc3-181-ga21b3f4

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD6
4)]
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.2
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist:
        machine: AMD64
        release: 7
         system: 7 6.1.7601 SP1 Multiprocessor Free
```

and the Master ```salt --versions```: git '2015.8' branch on 2 Sept at commit https://github.com/saltstack/salt/commit/f68ba2853a5fbf41f70744410576dbff33011302
```
salt --versions
Salt Version:
           Salt: 2015.8.0
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.21.1
           Mako: 0.8.1
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: Not Installed
          ioflo: 1.3.9
        libnacl: Not Installed
   msgpack-pure: 0.1.3
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: 0.21.4
   python-gnupg: Not Installed
          smmap: 0.8.1
        timelib: 0.2.4
 
System Versions:
           dist: centos 7.1.1503 Core
        machine: x86_64
        release: 3.10.0-229.11.1.el7.x86_64
         system: CentOS Linux 7.1.1503 Core
```

**Comment by arroyoc** [comment]
@TheBigBear Thanks for your detailed report.

**Comment by cachedout** [comment]
I have been running `test.ping` in a loop on my Linux master/minion and have yet to be able to replicate this behaviour. Is this happening when you ping the minion and then let it stay idle for 5+ minutes or does it happen despite the amount of activity?

**Comment by cachedout** [comment]
@TheBigBear Can you provide more specific tests to reproduce this beahviour? I'm having trouble replicating this.

**Comment by twangboy** [comment]
@TheBigBear I can't checkout `ga21b3f4` is this a commit on your own fork?

**Comment by TheBigBear** [comment]
OK, now I have the minion's give up:
```
C:\Salt-Dev>salt-minion -l debug
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[INFO    ] Setting up the Salt Minion "om-uk-w81-1-64"
[DEBUG   ] Created pidfile: c:\salt\var\run\salt-minion.pid
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[INFO    ] The salt minion is starting up
[INFO    ] Minion is starting as user 'om-uk-w81-1-64-admin'
[DEBUG   ] AsyncEventPublisher PUB socket URI: tcp://127.0.0.1:4510
[DEBUG   ] AsyncEventPublisher PULL socket URI: tcp://127.0.0.1:4511
[INFO    ] Starting pub socket on tcp://127.0.0.1:4510
[INFO    ] Starting pull socket on tcp://127.0.0.1:4511
[DEBUG   ] Minion 'om-uk-w81-1-64' trying to tune in
[DEBUG   ] sync_connect_master
[DEBUG   ] Initializing new SAuth for ('c:\\salt\\conf\\pki\\minion', 'om-uk-w81
-1-64', 'tcp://65.52.151.107:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (5207
)
[DEBUG   ] Setting zmq_reconnect_ivl to '5207ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\min
ion', 'om-uk-w81-1-64', 'tcp://65.52.151.107:4506', 'clear')
[DEBUG   ] Error deleting fd from IOLoop
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\tornado\ioloop.py", line 715, in remove_ha
ndler
    self._impl.unregister(fd)
  File "c:\python27\lib\site-packages\zmq\eventloop\ioloop.py", line 115, in unr
egister
    return self._poller.unregister(fd)
  File "c:\python27\lib\site-packages\zmq\sugar\poll.py", line 71, in unregister

    idx = self._map.pop(socket)
KeyError: None
[INFO    ] The salt minion is shut down
[ERROR   ] An un-handled exception was caught by salt's global exception handler
:
SaltClientError: Attempt to authenticate with the salt master failed
Traceback (most recent call last):
  File "C:\Python27\Scripts\salt-minion-script.py", line 9, in <module>
    load_entry_point('salt===2015.8.0rc3-183-g445eede', 'console_scripts', 'salt
-minion')()
  File "c:\salt-dev\salt\salt\scripts.py", line 113, in salt_minion
    minion.start()
  File "c:\salt-dev\salt\salt\cli\daemons.py", line 272, in start
    self.minion.tune_in()
  File "c:\salt-dev\salt\salt\minion.py", line 1596, in tune_in
    self.sync_connect_master()
  File "c:\salt-dev\salt\salt\minion.py", line 724, in sync_connect_master
    raise six.reraise(*future_exception)
  File "c:\python27\lib\site-packages\tornado\gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\salt-dev\salt\salt\minion.py", line 731, in connect_master
    master, self.pub_channel = yield self.eval_master(self.opts, self.timeout, s
elf.safe)
  File "c:\python27\lib\site-packages\tornado\gen.py", line 870, in run
    value = future.result()
  File "c:\python27\lib\site-packages\tornado\concurrent.py", line 215, in resul
t
    raise_exc_info(self._exc_info)
  File "c:\python27\lib\site-packages\tornado\gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\salt-dev\salt\salt\minion.py", line 495, in eval_master
    yield pub_channel.connect()
  File "c:\python27\lib\site-packages\tornado\gen.py", line 870, in run
    value = future.result()
  File "c:\python27\lib\site-packages\tornado\concurrent.py", line 215, in resul
t
    raise_exc_info(self._exc_info)
  File "c:\python27\lib\site-packages\tornado\gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\salt-dev\salt\salt\transport\zeromq.py", line 324, in connect
    yield self.auth.authenticate()
  File "c:\python27\lib\site-packages\tornado\gen.py", line 870, in run
    value = future.result()
  File "c:\python27\lib\site-packages\tornado\concurrent.py", line 215, in resul
t
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
SaltClientError: Attempt to authenticate with the salt master failed
Traceback (most recent call last):
  File "C:\Python27\Scripts\salt-minion-script.py", line 9, in <module>
    load_entry_point('salt===2015.8.0rc3-183-g445eede', 'console_scripts', 'salt
-minion')()
  File "c:\salt-dev\salt\salt\scripts.py", line 113, in salt_minion
    minion.start()
  File "c:\salt-dev\salt\salt\cli\daemons.py", line 272, in start
    self.minion.tune_in()
  File "c:\salt-dev\salt\salt\minion.py", line 1596, in tune_in
    self.sync_connect_master()
  File "c:\salt-dev\salt\salt\minion.py", line 724, in sync_connect_master
    raise six.reraise(*future_exception)
  File "c:\python27\lib\site-packages\tornado\gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\salt-dev\salt\salt\minion.py", line 731, in connect_master
    master, self.pub_channel = yield self.eval_master(self.opts, self.timeout, s
elf.safe)
  File "c:\python27\lib\site-packages\tornado\gen.py", line 870, in run
    value = future.result()
  File "c:\python27\lib\site-packages\tornado\concurrent.py", line 215, in resul
t
    raise_exc_info(self._exc_info)
  File "c:\python27\lib\site-packages\tornado\gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\salt-dev\salt\salt\minion.py", line 495, in eval_master
    yield pub_channel.connect()
  File "c:\python27\lib\site-packages\tornado\gen.py", line 870, in run
    value = future.result()
  File "c:\python27\lib\site-packages\tornado\concurrent.py", line 215, in resul
t
    raise_exc_info(self._exc_info)
  File "c:\python27\lib\site-packages\tornado\gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\salt-dev\salt\salt\transport\zeromq.py", line 324, in connect
    yield self.auth.authenticate()
  File "c:\python27\lib\site-packages\tornado\gen.py", line 870, in run
    value = future.result()
  File "c:\python27\lib\site-packages\tornado\concurrent.py", line 215, in resul
t
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
salt.exceptions.SaltClientError: Attempt to authenticate with the salt master fa
iled
```

I think i'll redo the master and minion with latest '2015.8' branch of today and re-test. 

@twangboy sorry the ga21b3f4 commit must have been on my windows devel machine as it was creating the windows installer. Sorry. I'll redo it again and try to do it off the main saltstack '2015.8' branch.

**Comment by TheBigBear** [comment]
@cachedout sorry, but on my side this is a very unstable setup. I will redo with the last two days of '2015.8' branch commits in as well.

**Comment by TheBigBear** [comment]
is tornado a new transport? can I switch back to using zmq instead and see if that behaves better?

**Comment by basepi** [comment]
Salt still uses ZMQ by default, but uses some tornado behind the scenes. There is a new transport option that you can set by setting `transport: tcp` in your config, but it is not enabled by default.

**Comment by TheBigBear** [comment]
@basepi I just see tornado mentioned too often for my liking on the minion debug output?

```
C:\Salt-Dev>salt-minion -l debug
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[INFO    ] Setting up the Salt Minion "om-uk-w81-1-64"
[DEBUG   ] Created pidfile: c:\salt\var\run\salt-minion.pid
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[INFO    ] The salt minion is starting up
[INFO    ] Minion is starting as user 'om-uk-w81-1-64-admin'
[DEBUG   ] AsyncEventPublisher PUB socket URI: tcp://127.0.0.1:4510
[DEBUG   ] AsyncEventPublisher PULL socket URI: tcp://127.0.0.1:4511
[INFO    ] Starting pub socket on tcp://127.0.0.1:4510
[INFO    ] Starting pull socket on tcp://127.0.0.1:4511
[DEBUG   ] Minion 'om-uk-w81-1-64' trying to tune in
[DEBUG   ] sync_connect_master
[DEBUG   ] Initializing new SAuth for ('c:\\salt\\conf\\pki\\minion', 'om-uk-w81
-1-64', 'tcp://65.52.151.107:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (5207
)
[DEBUG   ] Setting zmq_reconnect_ivl to '5207ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\min
ion', 'om-uk-w81-1-64', 'tcp://65.52.151.107:4506', 'clear')
[DEBUG   ] Error deleting fd from IOLoop
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\tornado\ioloop.py", line 715, in remove_ha
ndler
    self._impl.unregister(fd)
  File "c:\python27\lib\site-packages\zmq\eventloop\ioloop.py", line 115, in unr
egister
    return self._poller.unregister(fd)
  File "c:\python27\lib\site-packages\zmq\sugar\poll.py", line 71, in unregister

    idx = self._map.pop(socket)
KeyError: None
[INFO    ] The salt minion is shut down
[ERROR   ] An un-handled exception was caught by salt's global exception handler
:
SaltClientError: Attempt to authenticate with the salt master failed
Traceback (most recent call last):
  File "C:\Python27\Scripts\salt-minion-script.py", line 9, in <module>
    load_entry_point('salt===2015.8.0rc3-183-g445eede', 'console_scripts', 'salt
-minion')()
  File "c:\salt-dev\salt\salt\scripts.py", line 113, in salt_minion
    minion.start()
  File "c:\salt-dev\salt\salt\cli\daemons.py", line 272, in start
    self.minion.tune_in()
  File "c:\salt-dev\salt\salt\minion.py", line 1596, in tune_in
    self.sync_connect_master()
  File "c:\salt-dev\salt\salt\minion.py", line 724, in sync_connect_master
    raise six.reraise(*future_exception)
  File "c:\python27\lib\site-packages\tornado\gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\salt-dev\salt\salt\minion.py", line 731, in connect_master
    master, self.pub_channel = yield self.eval_master(self.opts, self.timeout, s
elf.safe)
  File "c:\python27\lib\site-packages\tornado\gen.py", line 870, in run
    value = future.result()
  File "c:\python27\lib\site-packages\tornado\concurrent.py", line 215, in resul
t
    raise_exc_info(self._exc_info)
  File "c:\python27\lib\site-packages\tornado\gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\salt-dev\salt\salt\minion.py", line 495, in eval_master
    yield pub_channel.connect()
  File "c:\python27\lib\site-packages\tornado\gen.py", line 870, in run
    value = future.result()
  File "c:\python27\lib\site-packages\tornado\concurrent.py", line 215, in resul
t
    raise_exc_info(self._exc_info)
  File "c:\python27\lib\site-packages\tornado\gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\salt-dev\salt\salt\transport\zeromq.py", line 324, in connect
    yield self.auth.authenticate()
  File "c:\python27\lib\site-packages\tornado\gen.py", line 870, in run
    value = future.result()
  File "c:\python27\lib\site-packages\tornado\concurrent.py", line 215, in resul
t
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
SaltClientError: Attempt to authenticate with the salt master failed
Traceback (most recent call last):
  File "C:\Python27\Scripts\salt-minion-script.py", line 9, in <module>
    load_entry_point('salt===2015.8.0rc3-183-g445eede', 'console_scripts', 'salt
-minion')()
  File "c:\salt-dev\salt\salt\scripts.py", line 113, in salt_minion
    minion.start()
  File "c:\salt-dev\salt\salt\cli\daemons.py", line 272, in start
    self.minion.tune_in()
  File "c:\salt-dev\salt\salt\minion.py", line 1596, in tune_in
    self.sync_connect_master()
  File "c:\salt-dev\salt\salt\minion.py", line 724, in sync_connect_master
    raise six.reraise(*future_exception)
  File "c:\python27\lib\site-packages\tornado\gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\salt-dev\salt\salt\minion.py", line 731, in connect_master
    master, self.pub_channel = yield self.eval_master(self.opts, self.timeout, s
elf.safe)
  File "c:\python27\lib\site-packages\tornado\gen.py", line 870, in run
    value = future.result()
  File "c:\python27\lib\site-packages\tornado\concurrent.py", line 215, in resul
t
    raise_exc_info(self._exc_info)
  File "c:\python27\lib\site-packages\tornado\gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\salt-dev\salt\salt\minion.py", line 495, in eval_master
    yield pub_channel.connect()
  File "c:\python27\lib\site-packages\tornado\gen.py", line 870, in run
    value = future.result()
  File "c:\python27\lib\site-packages\tornado\concurrent.py", line 215, in resul
t
    raise_exc_info(self._exc_info)
  File "c:\python27\lib\site-packages\tornado\gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\salt-dev\salt\salt\transport\zeromq.py", line 324, in connect
    yield self.auth.authenticate()
  File "c:\python27\lib\site-packages\tornado\gen.py", line 870, in run
    value = future.result()
  File "c:\python27\lib\site-packages\tornado\concurrent.py", line 215, in resul
t
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
salt.exceptions.SaltClientError: Attempt to authenticate with the salt master fa
iled
```

But maybe I am mis-reading it - and it has nothing to do with tornado?

**Comment by cachedout** [comment]
It is Tornado handling some of the internal asynchrnous operations in the minion, but the transport is still ZeroMQ.

**Comment by TheBigBear** [comment]
@cachedout just re-read your comment above https://github.com/saltstack/salt/issues/26887#issuecomment-137513154 this is a linux centos master and 3 windows minions, one a win 7 pro, a win 8.1 pro and a win 10 pro. have not yet tested it against a linux minion, but I wouldn't be surprised if the instability is possibly only against windows desktop OS minions.

**Comment by cachedout** [comment]
@TheBigBear Aye. Just trying to narrow down. The traceback you're seeing isn't platform specific (or at least it shouldn't be) but you never know.

**Comment by TheBigBear** [comment]
I am now back-up with a very very recent matching git version ```2015.8.0rc3-1154-g8cdf75c``` on both master and minion and I can't replicate this now. 

Things look much more stable now. 

So I will close it , and go to sleep, and test some more tomorrow and hope, this doesn't come back.

**Comment by bormotov** [comment]
look like same error

```
2015-09-25 14:23:10,587 [salt.loaded.int.module.mongodb][INFO    ][3276] Searching for {} in icm.config
2015-09-25 14:23:10,654 [salt.transport.zeromq][DEBUG   ][3276] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'xxxxx.xxxxx.xxx', 'tcp://nnn.nnn.nnn.nnn:4506', 'aes')
2015-09-25 14:23:10,659 [salt.crypt       ][DEBUG   ][3276] Initializing new SAuth for ('c:\\salt\\conf\\pki\\minion', 'xxxxx.xxxxx.xxx', 'tcp://nnn.nnn.nnn.nnn:4506')
2015-09-25 14:23:10,673 [salt.utils.lazy  ][DEBUG   ][3276] LazyLoaded nested.output
2015-09-25 14:23:11,164 [tornado.general  ][DEBUG   ][3276] Error deleting fd from IOLoop
Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\tornado\ioloop.py", line 715, in remove_handler
    self._impl.unregister(fd)
  File "C:\salt\bin\lib\site-packages\zmq\eventloop\ioloop.py", line 115, in unregister
    return self._poller.unregister(fd)
  File "C:\salt\bin\lib\site-packages\zmq\sugar\poll.py", line 71, in unregister
    idx = self._map.pop(socket)
KeyError: None
```

salt-call.bat --versions

```
Salt Version:
           Salt: 2015.8.0
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.2
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist:   
        machine: AMD64
        release: 7
         system: 7 6.1.7601 SP1 Multiprocessor Free
 ```
salt-master on Fedora 22, from repo

```
# salt --versions
           Salt: 2015.5.5
         Python: 2.7.10 (default, Jul  5 2015, 14:15:43)
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.4.1
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: Not Installed
```

**Comment by twangboy** [comment]
@bormotov The problem is that you're running a 2015.5 master with a 2015.8 minion. You need to have the same version of a new version master.

**Comment by smarmie** [comment]
Getting the same error with 2015.8.0 after a really long minion run, but the minion doesn't crash while applying the states:
These messages appear three times throughout the salt-call:

```
Summary for local
-------------
Succeeded: 81 (changed=70)
Failed:     0
-------------
Total states run:     81
Total run time: 8756.850 s
[DEBUG   ] Error deleting fd from IOLoop
Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/tornado/ioloop.py", line 714, in remove_handler
    self._impl.unregister(fd)
  File "/usr/lib64/python2.6/site-packages/zmq/eventloop/ioloop.py", line 115, in unregister
    return self._poller.unregister(fd)
  File "/usr/lib64/python2.6/site-packages/zmq/sugar/poll.py", line 71, in unregister
    idx = self._map.pop(socket)
KeyError: None
```

Versions:

```
[root@salt-minion1 ~]# salt-minion --versions
Salt Version:
           Salt: 2015.8.0
 
Dependency Versions:
         Jinja2: unknown
       M2Crypto: 0.20.2
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
         Python: 2.6.6 (r266:84292, May 22 2015, 08:34:51)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: redhat 6.7 Santiago
        machine: x86_64
        release: 2.6.32-573.7.1.el6.x86_64
         system: Red Hat Enterprise Linux Server 6.7 Santiago
```

```
[root@salt-master states]# salt --versions
Salt Version:
           Salt: 2015.8.0
 
Dependency Versions:
         Jinja2: unknown
       M2Crypto: 0.20.2
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32-573.3.1.el6.x86_64
         system: CentOS 6.7 Final
```
