### ISSUE TITLE
salt-call does not work with zmq_monitor enabled

### ISSUE THREAD

**Issue by cachedout** [saltstack/salt#26885]
If `zmq_monitor: True` is set in a minon configuration, `salt-call test.ping` will fail immediately with the following:

```
09:47:30,621 [tornado.application                      ][ERROR   ] Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/tornado/gen.py", line 230, in wrapper
    yielded = next(result)
  File "/home/mp/devel/salt/salt/minion.py", line 494, in eval_master
    pub_channel = salt.transport.client.AsyncPubChannel.factory(self.opts, **factory_kwargs)
  File "/home/mp/devel/salt/salt/transport/client.py", line 150, in factory
    return salt.transport.zeromq.AsyncZeroMQPubChannel(opts, **kwargs)
  File "/home/mp/devel/salt/salt/transport/zeromq.py", line 305, in __init__
    self._monitor.start_io_loop(self.io_loop)
  File "/home/mp/devel/salt/salt/transport/zeromq.py", line 859, in start_io_loop
    self._monitor_stream = zmq.eventloop.zmqstream.ZMQStream(self._monitor_socket, io_loop=io_loop)
  File "/usr/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 107, in __init__
    self._init_io_state()
  File "/usr/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 528, in _init_io_state
    self.io_loop.add_handler(self.socket, self._handle_events, self._state)
  File "/usr/lib/python2.7/site-packages/tornado/ioloop.py", line 704, in add_handler
    self._impl.register(fd, events | self.ERROR)
TypeError: argument must be an int, or have a fileno() method.
```

**Comment by DmitryKuzmenko** [comment]
Updated the code to call zeromq ioloop install everywhere it's needed. Now all should work fine.
