### ISSUE TITLE
salt-call w/non root user outputs repeating error

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#26889]
My versions_report:
```
root@elsapo:/home/boucha/salt# salt-call test.versions_report
local:
    Salt Version:
               Salt: 2015.8.0rc3-186-g23250d0
     
    Dependency Versions:
             Jinja2: 2.8
           M2Crypto: 0.21.1
               Mako: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.0.1
             Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.4
               cffi: 0.9.2
           cherrypy: Not Installed
           dateutil: 2.4.2
              gitdb: 0.5.4
          gitpython: Not Installed
              ioflo: Not Installed
            libnacl: 1.4.2
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: 2.13
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: 0.8.2
            timelib: Not Installed
     
    System Versions:
               dist: Ubuntu 14.04 trusty
            machine: x86_64
            release: 3.13.0-62-generic
             system: Ubuntu 14.04 trusty
```

When I run `salt-call test.ping` I get the following error repeating endlessly.
```
[boucha@elsapo salt (2015.8local $ u=)]$ salt-call test.ping
[WARNING ] Failed to open log file, do you have permission to write to /var/log/salt/minion?
[WARNING ] Although 'dmidecode' was found in path, the current user cannot execute it. Grains output might not be accurate.
[ERROR   ] Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 230, in wrapper
    yielded = next(result)
  File "/home/boucha/salt/salt/minion.py", line 494, in eval_master
    pub_channel = salt.transport.client.AsyncPubChannel.factory(self.opts, **factory_kwargs)
  File "/home/boucha/salt/salt/transport/client.py", line 150, in factory
    return salt.transport.zeromq.AsyncZeroMQPubChannel(opts, **kwargs)
  File "/home/boucha/salt/salt/transport/zeromq.py", line 242, in __init__
    self.auth = salt.crypt.AsyncAuth(self.opts, io_loop=self.io_loop)
  File "/home/boucha/salt/salt/crypt.py", line 323, in __new__
    new_auth.__singleton_init__(opts, io_loop=io_loop)
  File "/home/boucha/salt/salt/crypt.py", line 361, in __singleton_init__
    self.get_keys()
  File "/home/boucha/salt/salt/crypt.py", line 575, in get_keys
    salt.utils.verify.check_path_traversal(self.opts['pki_dir'], user)
  File "/home/boucha/salt/salt/utils/verify.py", line 400, in check_path_traversal
    raise SaltClientError(msg)
SaltClientError: Could not access /etc/salt/pki/minion. Try running as user root.
Exception AttributeError: "'AsyncZeroMQPubChannel' object has no attribute 'context'" in <bound method AsyncZeroMQPubChannel.__del__ of <salt.transport.zeromq.AsyncZeroMQPubChannel object at 0x7f130c83fa10>> ignored
Exception ValueError: 'I/O operation on closed file' in <bound method SyncWrapper.__del__ of <salt.utils.async.SyncWrapper object at 0x7f130c83fa10>> ignored
Exception ValueError: 'I/O operation on closed file' in <bound method SyncWrapper.__del__ of <salt.utils.async.SyncWrapper object at 0x7f130c83fa10>> ignored
Exception ValueError: 'I/O operation on closed file' in <bound method SyncWrapper.__del__ of <salt.utils.async.SyncWrapper object at 0x7f130c83fa10>> ignored
Exception ValueError: 'I/O operation on closed file' in <bound method SyncWrapper.__del__ of <salt.utils.async.SyncWrapper object at 0x7f130c83fa10>> ignored

<-- snip -->

Exception ValueError: 'I/O operation on closed file' in <bound method SyncWrapper.__del__ of <salt.utils.async.SyncWrapper object at 0x7f130c83fa10>> ignored
Exception ValueError: 'I/O operation on closed file' in <bound method SyncWrapper.__del__ of <salt.utils.async.SyncWrapper object at 0x7f130c83fa10>> ignored
Exception ValueError: 'I/O operation on closed file' in <bound method SyncWrapper.__del__ of <salt.utils.async.SyncWrapper object at 0x7f130c83fa10>> ignored
Exception ValueError: 'I/O operation on closed file' in <bound method SyncWrapper.__del__ of <salt.utils.async.SyncWrapper object at 0x7f130c83fa10>> ignored
Exception ValueError: 'I/O operation on closed file' in <bound method SyncWrapper.__del__ of <salt.utils.async.SyncWrapper object at 0x7f130c83fa10>> ignored
^CException KeyboardInterrupt in <bound method SyncWrapper.__del__ of <salt.utils.async.SyncWrapper object at 0x7f130c83fa10>> ignored
Could not access /etc/salt/pki/minion. Try running as user root.
[boucha@elsapo salt (2015.8local $ u=)]$ ^C
[boucha@elsapo salt (2015.8local $ u=)]$ ^C
```

This error repeats endlessly until I mash ctrl-c.

Proper behavior would be to return an error regarding not having sufficient privileges to execut `salt-call`

**Comment by Whissi** [comment]
For me it is enough to run salt-2015.8.0 test suite:

```
[...]
test_badload (unit.transport.tcp_test.AESReqTestCases) ... Exception ValueError: 'I/O operation on closed file' in <boun
d method SyncWrapper.__del__ of <salt.utils.async.SyncWrapper object at 0x7f32bb3402d0>> ignored
Exception ValueError: 'I/O operation on closed file' in <bound method SyncWrapper.__del__ of <salt.utils.async.SyncWrapp
er object at 0x7f32bb3402d0>> ignored
Exception ValueError: 'I/O operation on closed file' in <bound method SyncWrapper.__del__ of <salt.utils.async.SyncWrapp
er object at 0x7f32bb3402d0>> ignored
Exception ValueError: 'I/O operation on closed file' in <bound method SyncWrapper.__del__ of <salt.utils.async.SyncWrapp
er object at 0x7f32bb3402d0>> ignored
Exception ValueError: 'I/O operation on closed file' in <bound method SyncWrapper.__del__ of <salt.utils.async.SyncWrapp
er object at 0x7f32bb3402d0>> ignored
[...]
```

**Comment by cachedout** [comment]
I have this working correctly now in #27343

**Comment by arthurlogilab** [comment]
Getting bitten by this one too.

**Comment by WangWenchao** [comment]
my salt-master 2015.8.3 and minion is 2015.8.3 and 
I excute salt '<my-minion-id>'  test.ping  , get the error  , ctrl + c also cant terminate the output
```
Exception ValueError: 'I/O operation on closed file' in <bound method SyncWrapper.__del__ of <salt.utils.async.SyncWrapper object at 0x2faa750>> ignored
Exception ValueError: 'I/O operation on closed file' in <bound method SyncWrapper.__del__ of <salt.utils.async.SyncWrapper object at 0x2faa750>> ignored
Exception ValueError: 'I/O operation on closed file' in <bound method SyncWrapper.__del__ of <salt.utils.async.SyncWrapper object at 0x2faa750>> ignored
```

**Comment by sergeygolubev** [comment]
WangWenchao, i have same issue

**Comment by falzm** [comment]
Same here with 2015.8.3.
