### ISSUE TITLE
'salt-call winrepo.update_git_repos' on windows depends on '/tmp' and fails if there is no '/tmp'

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt#26907]
@terminalmage You probably don't need the verbose output below, this one is quite simple (me thinks). 

Basically the git operations depend on a ```'/tmp'``` directory (literally) even on windows (may not be the best assumption even under unix - but at least there it almost certainly exists)

And if there is no ```'/tmp'``` directory it will fail. And if I create a ```'c:\tmp'``` directory the commnd succeeds, might want to add better OS dependant temporary directory for this?

Below I first show that there is no C:\tmp directory and then show how the cmd fails, then I create the c:\tmp directory and show how it then succeeds.

```
C:\>dir tmp
 Volume in drive C has no label.
 Volume Serial Number is A0A6-EFB4

 Directory of C:\

File Not Found

C:\>salt-call --local winrepo.update_git_repos
[INFO    ] Loading fresh modules for state activity
[INFO    ] Running state [https://github.com/saltstack/salt-winrepo.git] at time
 13:15:14.877000
[INFO    ] Executing state git.latest for https://github.com/saltstack/salt-winr
epo.git
[INFO    ] Checking remote revision for https://github.com/saltstack/salt-winrep
o.git
[INFO    ] Executing command ['git', 'ls-remote', 'https://github.com/saltstack/
salt-winrepo.git'] in directory 'C:\\Users\\om-uk-w7-1-64-admin'
[INFO    ] Executing command ['git', '--version'] in directory 'C:\\Users\\om-uk
-w7-1-64-admin'
[INFO    ] Executing command ['git', 'rev-parse', '--show-toplevel'] in director
y 'c:\\salt\\srv\\salt\\win\\repo\\salt-winrepo_git'
[INFO    ] Executing command ['git', 'clone', '--', 'https://github.com/saltstac
k/salt-winrepo.git', 'c:\\salt\\srv\\salt\\win\\repo\\salt-winrepo_git'] in dire
ctory '/tmp'
[ERROR   ] Unexpected exception in git.latest state
Traceback (most recent call last):
  File "c:\salt-dev\salt\salt\states\git.py", line 1250, in latest
    https_pass=https_pass)
  File "c:\salt-dev\salt\salt\modules\git.py", line 721, in clone
    ignore_retcode=ignore_retcode)
  File "c:\salt-dev\salt\salt\modules\git.py", line 217, in _git_run
    **kwargs)
  File "c:\salt-dev\salt\salt\modules\cmdmod.py", line 1550, in run_all
    use_vt=use_vt)
  File "c:\salt-dev\salt\salt\modules\cmdmod.py", line 421, in _run
    .format(cwd)
CommandExecutionError: Specified cwd '/tmp' either not absolute or does not exis
t
[ERROR   ] Specified cwd '/tmp' either not absolute or does not exist
[INFO    ] Completed state [https://github.com/saltstack/salt-winrepo.git] at ti
me 13:15:16.265000
[INFO    ] Loading fresh modules for state activity
[INFO    ] Running state [https://github.com/saltstack/salt-winrepo-ng.git] at t
ime 13:15:16.399000
[INFO    ] Executing state git.latest for https://github.com/saltstack/salt-winr
epo-ng.git
[INFO    ] Checking remote revision for https://github.com/saltstack/salt-winrep
o-ng.git
[INFO    ] Executing command ['git', 'ls-remote', 'https://github.com/saltstack/
salt-winrepo-ng.git'] in directory 'C:\\Users\\om-uk-w7-1-64-admin'
[INFO    ] Executing command ['git', '--version'] in directory 'C:\\Users\\om-uk
-w7-1-64-admin'
[INFO    ] Executing command ['git', 'rev-parse', '--show-toplevel'] in director
y 'c:\\salt\\srv\\salt\\win\\repo-ng\\salt-winrepo-ng_git'
[INFO    ] Executing command ['git', 'clone', '--', 'https://github.com/saltstac
k/salt-winrepo-ng.git', 'c:\\salt\\srv\\salt\\win\\repo-ng\\salt-winrepo-ng_git'
] in directory '/tmp'
[ERROR   ] Unexpected exception in git.latest state
Traceback (most recent call last):
  File "c:\salt-dev\salt\salt\states\git.py", line 1250, in latest
    https_pass=https_pass)
  File "c:\salt-dev\salt\salt\modules\git.py", line 721, in clone
    ignore_retcode=ignore_retcode)
  File "c:\salt-dev\salt\salt\modules\git.py", line 217, in _git_run
    **kwargs)
  File "c:\salt-dev\salt\salt\modules\cmdmod.py", line 1550, in run_all
    use_vt=use_vt)
  File "c:\salt-dev\salt\salt\modules\cmdmod.py", line 421, in _run
    .format(cwd)
CommandExecutionError: Specified cwd '/tmp' either not absolute or does not exis
t
[ERROR   ] Specified cwd '/tmp' either not absolute or does not exist
[INFO    ] Completed state [https://github.com/saltstack/salt-winrepo-ng.git] at
 time 13:15:17.760000
local:
    ----------
    https://github.com/saltstack/salt-winrepo-ng.git:
        False
    https://github.com/saltstack/salt-winrepo.git:
        False
```

Then I create a ```C:\tmp``` directory and it runs through to completion OK.

```
C:\>mkdir tmp

C:\>salt-call --local winrepo.update_git_repos
[INFO    ] Loading fresh modules for state activity
[INFO    ] Running state [https://github.com/saltstack/salt-winrepo.git] at time
 13:15:43.719000
[INFO    ] Executing state git.latest for https://github.com/saltstack/salt-winr
epo.git
[INFO    ] Checking remote revision for https://github.com/saltstack/salt-winrep
o.git
[INFO    ] Executing command ['git', 'ls-remote', 'https://github.com/saltstack/
salt-winrepo.git'] in directory 'C:\\Users\\om-uk-w7-1-64-admin'
[INFO    ] Executing command ['git', '--version'] in directory 'C:\\Users\\om-uk
-w7-1-64-admin'
[INFO    ] Executing command ['git', 'rev-parse', '--show-toplevel'] in director
y 'c:\\salt\\srv\\salt\\win\\repo\\salt-winrepo_git'
[INFO    ] Executing command ['git', 'clone', '--', 'https://github.com/saltstac
k/salt-winrepo.git', 'c:\\salt\\srv\\salt\\win\\repo\\salt-winrepo_git'] in dire
ctory '/tmp'
[INFO    ] Executing command ['git', 'for-each-ref', '--format', '%(refname:shor
t)', 'refs/heads/'] in directory 'c:\\salt\\srv\\salt\\win\\repo\\salt-winrepo_g
it'
[INFO    ] Executing command ['git', 'checkout', '-b', 'winrepo', 'origin/HEAD']
 in directory 'c:\\salt\\srv\\salt\\win\\repo\\salt-winrepo_git'
[INFO    ] Checking local revision for c:\salt\srv\salt\win\repo\salt-winrepo_gi
t
[INFO    ] Executing command ['git', 'rev-parse', 'HEAD'] in directory 'c:\\salt
\\srv\\salt\\win\\repo\\salt-winrepo_git'
[INFO    ] Checking local branch for c:\salt\srv\salt\win\repo\salt-winrepo_git
[INFO    ] Executing command ['git', 'rev-parse', '--abbrev-ref', 'HEAD'] in dir
ectory 'c:\\salt\\srv\\salt\\win\\repo\\salt-winrepo_git'
[INFO    ] Executing command ['git', 'rev-parse', '--abbrev-ref', 'winrepo@{upst
ream}'] in directory 'c:\\salt\\srv\\salt\\win\\repo\\salt-winrepo_git'
[INFO    ] Executing command ['git', 'rev-parse', 'HEAD'] in directory 'c:\\salt
\\srv\\salt\\win\\repo\\salt-winrepo_git'
[INFO    ] https://github.com/saltstack/salt-winrepo.git cloned to c:\salt\srv\s
alt\win\repo\salt-winrepo_git. Branch 'winrepo' checked out, with HEAD (6e1425f)
 as a starting point.
[INFO    ] {'new': 'https://github.com/saltstack/salt-winrepo.git => c:\\salt\\s
rv\\salt\\win\\repo\\salt-winrepo_git', 'revision': {'new': '6e1425f5c43566c7f9b
2570d3380b26e3cbbe1d7', 'old': None}}
[INFO    ] Completed state [https://github.com/saltstack/salt-winrepo.git] at ti
me 13:15:48.532000
[INFO    ] Loading fresh modules for state activity
[INFO    ] Running state [https://github.com/saltstack/salt-winrepo-ng.git] at t
ime 13:15:48.646000
[INFO    ] Executing state git.latest for https://github.com/saltstack/salt-winr
epo-ng.git
[INFO    ] Checking remote revision for https://github.com/saltstack/salt-winrep
o-ng.git
[INFO    ] Executing command ['git', 'ls-remote', 'https://github.com/saltstack/
salt-winrepo-ng.git'] in directory 'C:\\Users\\om-uk-w7-1-64-admin'
[INFO    ] Executing command ['git', '--version'] in directory 'C:\\Users\\om-uk
-w7-1-64-admin'
[INFO    ] Executing command ['git', 'rev-parse', '--show-toplevel'] in director
y 'c:\\salt\\srv\\salt\\win\\repo-ng\\salt-winrepo-ng_git'
[INFO    ] Executing command ['git', 'clone', '--', 'https://github.com/saltstac
k/salt-winrepo-ng.git', 'c:\\salt\\srv\\salt\\win\\repo-ng\\salt-winrepo-ng_git'
] in directory '/tmp'
[INFO    ] Executing command ['git', 'for-each-ref', '--format', '%(refname:shor
t)', 'refs/heads/'] in directory 'c:\\salt\\srv\\salt\\win\\repo-ng\\salt-winrep
o-ng_git'
[INFO    ] Executing command ['git', 'checkout', '-b', 'winrepo', 'origin/HEAD']
 in directory 'c:\\salt\\srv\\salt\\win\\repo-ng\\salt-winrepo-ng_git'
[INFO    ] Checking local revision for c:\salt\srv\salt\win\repo-ng\salt-winrepo
-ng_git
[INFO    ] Executing command ['git', 'rev-parse', 'HEAD'] in directory 'c:\\salt
\\srv\\salt\\win\\repo-ng\\salt-winrepo-ng_git'
[INFO    ] Checking local branch for c:\salt\srv\salt\win\repo-ng\salt-winrepo-n
g_git
[INFO    ] Executing command ['git', 'rev-parse', '--abbrev-ref', 'HEAD'] in dir
ectory 'c:\\salt\\srv\\salt\\win\\repo-ng\\salt-winrepo-ng_git'
[INFO    ] Executing command ['git', 'rev-parse', '--abbrev-ref', 'winrepo@{upst
ream}'] in directory 'c:\\salt\\srv\\salt\\win\\repo-ng\\salt-winrepo-ng_git'
[INFO    ] Executing command ['git', 'rev-parse', 'HEAD'] in directory 'c:\\salt
\\srv\\salt\\win\\repo-ng\\salt-winrepo-ng_git'
[INFO    ] https://github.com/saltstack/salt-winrepo-ng.git cloned to c:\salt\sr
v\salt\win\repo-ng\salt-winrepo-ng_git. Branch 'winrepo' checked out, with HEAD
(45fbcf4) as a starting point.
[INFO    ] {'new': 'https://github.com/saltstack/salt-winrepo-ng.git => c:\\salt
\\srv\\salt\\win\\repo-ng\\salt-winrepo-ng_git', 'revision': {'new': '45fbcf4308
d7367fd46f86296a4cd07ab9dac26a', 'old': None}}
[INFO    ] Completed state [https://github.com/saltstack/salt-winrepo-ng.git] at
 time 13:15:53.446000
local:
    ----------
    https://github.com/saltstack/salt-winrepo-ng.git:
        True
    https://github.com/saltstack/salt-winrepo.git:
        True

C:\>
```

**Comment by terminalmage** [comment]
This snuck in because of a workaround for a git bug which affects git 2.1 (or thereabouts, whichever version is in Debian Jessie), where running the clone from ``/root`` (the default if no cwd was specified and the user is ``root``) would cause the fetch URL to be written to /path/to/repo/.git/config incorrectly, causing fetches to fail.
