### ISSUE TITLE
file.manage state does not work with Amazon S3 URLs on Windows

### ISSUE THREAD

**Issue by dsumsky** [saltstack/salt#26911]
file.managed states seems not to be working on Windows platform (tested on 2015.5.5, 2015.5.3, 2015.8.0rc3). Let's have a simple state:
```
c:\test.txt:
  file.managed:
   - source: s3://MY_S3_BUCKET/test.txt
   - source_hash: md5=A5C8B2C7A47FA20EACD9EB4F4DD2FC66
```
Executing the state ends with an error (by c:\salt\salt-call.bat command):
```
[DEBUG   ] Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\states\file.py", line 1577, in managed
    follow_symlinks)
  File "C:\salt\bin\lib\site-packages\salt\modules\file.py", line 3717, in manage_file
    sfn = __salt__['cp.cache_file'](source, saltenv)
  File "C:\salt\bin\lib\site-packages\salt\modules\cp.py", line 367, in cache_file
    result = __context__['cp.fileclient'].cache_file(path, saltenv)
  File "C:\salt\bin\lib\site-packages\salt\fileclient.py", line 153, in cache_file
    return self.get_url(path, '', True, saltenv)
  File "C:\salt\bin\lib\site-packages\salt\fileclient.py", line 571, in get_url
    raise MinionError('Could not fetch from {0}'.format(url))
MinionError: Could not fetch from s3://MY_S3_BUCKET/test.txt

[ERROR   ] Unable to manage file: Could not fetch from s3://MY_S3_BUCKET/test.txt
[INFO    ] Completed state [c:\test.txt] at time 15:35:09.149000
[DEBUG   ] File c:\salt\var\cache\salt\minion\accumulator\63874888 does not exist, no need to cleanup.
[DEBUG   ] LazyLoaded config.option
[DEBUG   ] LazyLoaded cmd.run
[INFO    ] Executing command ['attrib', '-R', 'c:\\salt\\var\\cache\\salt\\minion\\sls.p'] in directory 'C:\\Users\\Admi
nistrator'
[DEBUG   ] output: File not found - C:\salt\var\cache\salt\minion\sls.p
[DEBUG   ] Re-using SAuth for ('c:\\salt\\conf\\pki\\minion', 'i-XXXXXX', 'tcp://XX.XX.XX.XX:4506')
[DEBUG   ] LazyLoaded highstate.output
local:
----------
          ID: c:\test.txt
    Function: file.managed
      Result: False
     Comment: Unable to manage file: Could not fetch from s3://MY_S3_BUCKET/test.txt
     Started: 15:35:09.071000
    Duration: 78.0 ms
     Changes:

Summary
------------
Succeeded: 0
Failed:    1
------------
```

**Comment by elyast** [comment]
it doesn't work in version 2015.8.0 on my ubuntu box

**Comment by Ch3LL** [comment]
ZD-506

**Comment by messa** [comment]
Where are your S3 credentials `s3.keyid` and `s3.key` - in Minion config or in Pillar? Because I got the same error when I've put them in Pillar, which doesn't work, see #13850.
