### ISSUE TITLE
MySQL grant with underscore and wildcard

### ISSUE THREAD

**Issue by david-fairbanks42** [saltstack/salt#26920]
I haven't tested all the variations of this not working but this state is not working for me.

    installer_local_grants:
      mysql_grants.present:
        - grant: all privileges
        - database: install\_%.*
        - user: installer
        - host: localhost

It produces `install\\_\%` for the database not `install\_%`
When I set `- escape: False` I get the following error

    Function: mysql_grants.present
    Result: False
    Comment: An exception occurred in this state: Traceback (most recent call last):
    File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1560, in call
    **cdata['kwargs'])
    File "/usr/lib/python2.7/dist-packages/salt/states/mysql_grants.py", line 187, in present
    grant, database, user, host, grant_option, escape, ssl_option, **connection_args
    File "/usr/lib/python2.7/dist-packages/salt/modules/mysql.py", line 1666, in grant_add
    _execute(cur, qry['qry'], qry['args'])
    File "/usr/lib/python2.7/dist-packages/salt/modules/mysql.py", line 505, in _execute
    return cur.execute(qry, args)
    File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 159, in execute
    query = query % db.literal(args)
    TypeError: * wants int

I've posted this on StackOverflow as well at http://stackoverflow.com/questions/32362573/salt-stack-mysql-grants-present-underscore-wildcard

I'm using this on
Ubuntu 14.04.2 LTS
salt-call 2015.5.3 (Lithium)
python2.7-mysqldb via 1.2.3-2ubuntu1

**Comment by ssgward** [comment]
Thanks for the report.

**Comment by ChoOo7** [comment]
More or less similar issue : 

mysql_grants.present:
    - grant: PROCESS
    - database: *.* 
    - user: clustercheckuser
    - host: localhost


database *.* is not allowed : 
Rendering SLS 'base:sql.galera' failed: expected alphabetic or numeric character, but found '.'; line 120


I would like to do a
GRANT PROCESS ON *.* TO 'clustercheckuser'@'localhost'

Thanks

**Comment by ryanbagwell** [comment]
I'm encountering the same problem on centos system.

**Comment by Sakorah** [comment]
Hi, I run into this issue as well on ubuntu. I need to give useres access to databases based on their username which is the prefix of the database.
Just like the first post mentions.

**Comment by martintamare** [comment]
Any news on this issue ?

**Comment by martintamare** [comment]
I want to match db\_name\_% (wildcard only for %)

I've tried all the following notation
with escape = False :
`
db\_name\_%.*
`db\_name\_%`.*
"db\_name\_%.*"
"`db\_name\_%`.*"
"'`db\_name\_%`.*'"
`
with escape = True: 
`
db_name_%.*
db_name_%%.*
`
The issues seems to be on the function quote_identifier

when for_grants=True, I don't understand 
` 
'`' + identifier.replace('`', '``').replace('_', r'\_') \
            .replace('%', r'\%%') + '`'
`
which would be for my query to work
`
 '`' + identifier.replace('`', '``').replace('_', r'\_') \
            .replace('%', '%%') + '`'
`

**Comment by rickh563** [comment]
ZD-1450

**Comment by martintamare** [comment]
What's the meaning of the ZD tag ? :)

**Comment by cachedout** [comment]
It is for internal tracking.

**Comment by garethgreenaway** [comment]
@david-fairbanks42 There is some escaping of various things happening behind the scenes so it's likely that without `escape: False` there is escaping of the wrong values happening.  Can you give this edited state a try without `escape: False`:
```
installer_local_grants:
  mysql_grants.present:
    - grant: all privileges
    - database: install_%.*
    - user: installer
    - host: localhost
```

**Comment by return-null** [comment]
Maybe this is a different issue, but escaping is problematic for me. When I use this:

`testGrants:
   mysql_grants.present:
    - grant: all
    - database: test_%.* 
    - user: testuser
    - host: 10.10.%
    - grant_option: true
`

I get this:
GRANT ALL PRIVILEGES ON `test\_\%`.* TO 'testuser'@'10.10.%' WITH GRANT OPTION

But I do not want the escapes in the grant. If I set -escape: false , then the grant never gets assign. With the escape set to false I've tried all manner of escaping in the database field, but the assignment always fails. For example, I currently see this:

`  File "/usr/lib/python2.7/site-packages/salt/state.py", line 1564, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/site-packages/salt/states/mysql_grants.py", line 187, in present
    grant, database, user, host, grant_option, escape, ssl_option, **connection_args
  File "/usr/lib/python2.7/site-packages/salt/modules/mysql.py", line 1679, in grant_add
    _execute(cur, qry['qry'], qry['args'])
  File "/usr/lib/python2.7/site-packages/salt/modules/mysql.py", line 517, in _execute
    return cur.execute(qry, args)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 185, in execute
    for key, item in args.iteritems())
TypeError: * wants int`

**Comment by evoWeb** [comment]
with this state:

testGrants:
mysql_grants.present:
- name: typo3_typo3_%_all
- database: typo3_%.*
- grant: 'all privileges'
- user: typo3
- host: localhost
- escape: False


i get the following error:
`
          ID: testGrants
    Function: mysql_grants.present
        Name: typo3_typo3_%_all
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1843, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1795, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/mysql_grants.py", line 191, in present
                  grant, database, user, host, grant_option, escape, ssl_option, **connection_args
                File "/usr/lib/python2.7/dist-packages/salt/modules/mysql.py", line 1847, in grant_add
                  err = 'MySQL Error {0}: {1}'.format(*exc)
              IndexError: tuple index out of range
     Started: 22:09:19.573695
    Duration: 3.64 ms
     Changes: 
`

I use salt-call in version 2017.7.2 (Nitrogen)

**Comment by bertulus** [comment]
I had the same Issue ( or so I thing) . It looks like the unescaped '%' is a problem for python. See https://stackoverflow.com/a/11696152/5483988 . As a workaround you can try to write '%%' . This solved my issue.

**Comment by rallytime** [comment]
Closed via #46171
