### ISSUE TITLE
[2015.8.0rc5] Tornado AssertionError when starting salt-minion (regression)

### ISSUE THREAD

**Issue by bechtoldt** [saltstack/salt#26932]
I can reproduce #24440 on centos 7.0 when setting the minion setting ``file_client`` to ``local``:

```
# cat /etc/salt/minion
master: 127.0.0.1

file_roots:
  base:
    - /srv/salt/states
    - /srv/salt/contrib/states
    - /vagrant/shared

pillar_roots:
  base:
    - /srv/salt/pillar/examples
    - /srv/salt/pillar/shared

module_dirs:
  - /srv/salt/_modules/common
  - /srv/salt/_modules/formulas

states_dirs:
  - /srv/salt/_states/common

file_client: local
```

```
2015-09-06 18:30:57,624 [salt.scripts     ][ERROR   ][25312] Minion failed to start:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 81, in minion_process
    minion.start()
  File "/usr/lib/python2.7/site-packages/salt/cli/daemons.py", line 272, in start
    self.minion.tune_in()
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1596, in tune_in
    self.sync_connect_master()
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 724, in sync_connect_master
    raise six.reraise(*future_exception)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 812, in run
    yielded = self.gen.send(value)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 732, in connect_master
    yield self._post_master_init(master)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 224, in wrapper
    Runner(result, future, yielded)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 756, in __init__
    if self.handle_yield(first_yielded):
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 886, in handle_yield
    self.future = convert_yielded(yielded)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 952, in convert_yielded
    return multi_future(yielded)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 596, in multi_future
    assert all(is_future(i) for i in children)
AssertionError
2015-09-06 18:30:57,625 [salt.scripts     ][WARNING ][25312] ** Restarting minion **
```

```
# salt-call --versions
Salt Version:
           Salt: 2015.8.0rc5

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.5.0
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
           RAET: Not Installed
        Tornado: 4.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.0.1406 Core
        machine: x86_64
        release: 3.10.0-123.el7.x86_64
         system: CentOS Linux 7.0.1406 Core
```

refs #25148

This behaviour can be reproduced with https://github.com/bechtoldt/saltbox-vagrant.

/cc @jacksontj

**Comment by cachedout** [comment]
We already have a fix for this in develop, in #25148 as you mention. I have marked it for backporting. We'll try to get this in ASAP. Thanks for catching this!

cc: @jfindlay for backporting.

**Comment by cachedout** [comment]
We have merged the backport into the HEAD of 2015.8 and I have verified that the minion now starts correct with `file_client: local` in the config, where it did not before.

**Comment by bechtoldt** [comment]
:+1: I can confirm the fix.

**Comment by cachedout** [comment]
Thank you for the quick follow-up, @bechtoldt
