### ISSUE TITLE
Roster.conf password special chars ascii/unicode error in 2015.8.0rc5

### ISSUE THREAD

**Issue by lichtamberg** [saltstack/salt#26935]
Pulled 2015.8.0rc5 branch, fails with exception (see below):

``` yaml
# fails with special chars
myserver:
  host: myserver.com
  passwd: 'Lixxted2§$'

# works without special chars
myserver:
  host: myserver.com
  passwd: 'Lixxted2'
```

``` shell
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 342, in handle_routine
    **target)
  File "/usr/local/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 663, in __init__
    self.shell = salt.client.ssh.shell.Shell(opts, **args)
  File "/usr/local/lib/python2.7/site-packages/salt/client/ssh/shell.py", line 66, in __init__
    self.passwd = str(passwd) if passwd else passwd
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa7' in position 8: ordinal not in range(128)
[ERROR   ] Target 'myserver' did not return any data, probably due to an error.
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa7' in position 8: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/bin/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/usr/local/lib/python2.7/site-packages/salt/scripts.py", line 377, in salt_ssh
    client.run()
  File "/usr/local/lib/python2.7/site-packages/salt/cli/ssh.py", line 19, in run
    ssh.run()
  File "/usr/local/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 545, in run
    ret = self.key_deploy(host, ret)
  File "/usr/local/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 268, in key_deploy
    self._key_deploy_run(host, target, False)
  File "/usr/local/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 301, in _key_deploy_run
    **target)
  File "/usr/local/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 663, in __init__
    self.shell = salt.client.ssh.shell.Shell(opts, **args)
  File "/usr/local/lib/python2.7/site-packages/salt/client/ssh/shell.py", line 66, in __init__
    self.passwd = str(passwd) if passwd else passwd
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa7' in position 8: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/bin/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/usr/local/lib/python2.7/site-packages/salt/scripts.py", line 377, in salt_ssh
    client.run()
  File "/usr/local/lib/python2.7/site-packages/salt/cli/ssh.py", line 19, in run
    ssh.run()
  File "/usr/local/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 545, in run
    ret = self.key_deploy(host, ret)
  File "/usr/local/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 268, in key_deploy
    self._key_deploy_run(host, target, False)
  File "/usr/local/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 301, in _key_deploy_run
    **target)
  File "/usr/local/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 663, in __init__
    self.shell = salt.client.ssh.shell.Shell(opts, **args)
  File "/usr/local/lib/python2.7/site-packages/salt/client/ssh/shell.py", line 66, in __init__
    self.passwd = str(passwd) if passwd else passwd
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa7' in position 8: ordinal not in range(128)
```

```
Salt Version:
           Salt: 2015.8.0rc5

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.22
           Mako: 1.0.1
         PyYAML: 3.11
          PyZMQ: 14.6.0
         Python: 2.7.9 (default, Jan  7 2015, 11:50:42)
           RAET: Not Installed
        Tornado: 4.1
            ZMQ: 4.0.5
           cffi: 0.9.2
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.2.1
        libnacl: Not Installed
   msgpack-pure: 0.1.3
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.12
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist:
        machine: x86_64
        release: 13.4.0
         system: 10.9.5 -- x86_64
```

**Comment by jfindlay** [comment]
@lichtamberg, thanks for the report.
