### ISSUE TITLE
2015.8.0 Debian packages should depend on python-tornado

### ISSUE THREAD

**Issue by babilen** [saltstack/salt#27043]
I just installed salt-ssh from repo.saltstack.com and encountered the following problem:

```
# salt-ssh --versions-report
Traceback (most recent call last):
  File "/usr/bin/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 371, in salt_ssh
    import salt.cli.ssh
  File "/usr/lib/python2.7/dist-packages/salt/cli/ssh.py", line 5, in <module>
    import salt.client.ssh
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 36, in <module>
    import salt.config
  File "/usr/lib/python2.7/dist-packages/salt/config.py", line 39, in <module>
    import salt.utils.sdb
  File "/usr/lib/python2.7/dist-packages/salt/utils/sdb.py", line 9, in <module>
    import salt.loader
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 28, in <module>
    import salt.utils.event
  File "/usr/lib/python2.7/dist-packages/salt/utils/event.py", line 81, in <module>
    import salt.payload
  File "/usr/lib/python2.7/dist-packages/salt/payload.py", line 17, in <module>
    import salt.crypt
  File "/usr/lib/python2.7/dist-packages/salt/crypt.py", line 36, in <module>
    import salt.transport.client
  File "/usr/lib/python2.7/dist-packages/salt/transport/client.py", line 12, in <module>
    from salt.utils.async import SyncWrapper
  File "/usr/lib/python2.7/dist-packages/salt/utils/async.py", line 8, in <module>
    import tornado.ioloop
ImportError: No module named tornado.ioloop
```
which is due to the fact that python-tornado was not installed (cf. #22601). A look at the reverse dependencies of python-tornado reveals that there is no dependency chain from any of the salt packages to it. I would recommend to add that dependency so that salt is usable after the installation (which is always a nice thing).

**Comment by dmurphy18** [comment]
The packages we still a work in progress at the point at which you tried them.

The final packages for 2015.8.0 were posted lunch time Friday 11th Sept.

I had caught that in final testing this morning and fixed the issue before the final posting.  Can you retry with the current packagers and let me know if you still have the same issue.

**Comment by babilen** [comment]
This works now, thank you for addressing it immediately!
