### ISSUE TITLE
2015.8.0 RuntimeError("IOLoop is already running"

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt#27097]
on a centos 6 2015.8.0-2 rpm install when running my 

```
salt 'uk-svc-phones' cmd.script salt://windows/windows-updates/install-update.ps1 shell='powershell' -v -t 450
```

```
Executing job with jid 20150914141424868426
-------------------------------------------

uk-svc-phones:
    The minion function caused an exception: Traceback (most recent call last):
      File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1004, in _thread_return
        return_data = func(*args, **kwargs)
      File "c:\salt\bin\lib\site-packages\salt\modules\cmdmod.py", line 1971, in script
        fn_ = __salt__['cp.cache_file'](source, saltenv)
      File "c:\salt\bin\lib\site-packages\salt\modules\cp.py", line 365, in cache_file
        result = __context__['cp.fileclient'].cache_file(path, saltenv)
      File "c:\salt\bin\lib\site-packages\salt\fileclient.py", line 155, in cache_file
        return self.get_url(path, '', True, saltenv)
      File "c:\salt\bin\lib\site-packages\salt\fileclient.py", line 540, in get_url
        return self.get_file(url, dest, makedirs, saltenv)
      File "c:\salt\bin\lib\site-packages\salt\fileclient.py", line 996, in get_file
        hash_server = self.hash_file(path, saltenv)
      File "c:\salt\bin\lib\site-packages\salt\fileclient.py", line 1236, in hash_file
        return self.channel.send(load)
      File "c:\salt\bin\lib\site-packages\salt\utils\async.py", line 73, in wrap
        ret = self._block_future(ret)
      File "c:\salt\bin\lib\site-packages\salt\utils\async.py", line 82, in _block_future
        self.io_loop.start()
      File "c:\salt\bin\lib\site-packages\zmq\eventloop\ioloop.py", line 151, in start
        super(ZMQIOLoop, self).start()
      File "c:\salt\bin\lib\site-packages\tornado\ioloop.py", line 731, in start
        raise RuntimeError("IOLoop is already running")
    RuntimeError: IOLoop is already running
```

Any idea why that could be? I am not aware of any job already runnign against that machine?

**Comment by jfindlay** [comment]
@TheBigBear, thanks for the report.  Is there any more minion log context that you can provide, or is it possible for you to narrow down on anything in your powershell script that is causing this?  Is there any extra or leftover minion processes running on the windows minion?
