### ISSUE TITLE
direct_call executor raises TypeError when kwargs include "opts"

### ISSUE THREAD

**Issue by terminalmage** [saltstack/salt#27108]
In this case, the kwargs contain an "opts" key, which is being expanded by the double-asterisk in line 1010 of minion.py:

```python
Traceback (most recent call last):
  File "/home/erik/git/salt/main/salt/minion.py", line 1010, in _thread_return
    "{0}".format(executors.pop())](opts, data, func, *args, **kwargs)
  File "/home/erik/git/salt/main/salt/executors/direct_call.py", line 12, in get
    return DirectCallExecutor(*args, **kwargs)
TypeError: __init__() got multiple values for keyword argument 'opts'
```

NOTE: This would also raise the same error if the kwargs contain keys named "data" or "func".

This is responsible for the test failures seen here: https://jenkins.saltstack.com/job/salt-linode-debian8/2563/

CC: @DmitryKuzmenko

**Comment by terminalmage** [comment]
This only affects the develop branch.
