### ISSUE TITLE
salt.util.smb loads even when impacket library is missing

### ISSUE THREAD

**Issue by alxbse** [saltstack/salt#27157]
The salt.utils.smb module has a dependency on impacket. There is code for catching when the module impacket fails to load and HAS_IMPACKET is set accordingly however there is no \_\_virtual\_\_ function that verifies it so the module always loads.

This for example makes bootstrapping a windows minion fail with a error and traceback about the global name 'impacket' not being defined.

A workaround is of course to install the impacket library. Is the behaviour maybe by design?

**Comment by techhat** [comment]
Files in `salt/utils/` are not handled by the loader system, and therefore have no support for the `__virtual__()` function. That means that different strategies for gating need to be employed.

Would you please post the traceback so that we can clean it up there?

**Comment by alxbse** [comment]
Here is a traceback:

```
[DEBUG   ] Logging into 1.2.3.4:445 as Administrator
[ERROR   ] There was a profile error: global name 'impacket' is not defined
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 275, in run
    self.config.get('names')
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1410, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1256, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/openstack.py", line 774, in create
    ret = salt.utils.cloud.bootstrap(vm_, __opts__)
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 499, in bootstrap
    deployed = deploy_windows(**deploy_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 956, in deploy_windows
    smb_conn = salt.utils.smb.get_conn(host, username, password)
  File "/usr/lib/python2.7/dist-packages/salt/utils/smb.py", line 50, in get_conn
    conn = impacket.smbconnection.SMBConnection(
NameError: global name 'impacket' is not defined
```

**Comment by techhat** [comment]
@alxbse #27168 should fix this up.

**Comment by alxbse** [comment]
Awesome response time!
