### ISSUE TITLE
Unexpected invocation of SSL in MySQL Returner

### ISSUE THREAD

**Issue by grichmond-salt** [saltstack/salt#27171]
While testing the MySQL returner on Ubuntu 10.04, the minion error log reported connection failures to a MySQL database that is not configured to use SSL.  As specified in the documentation, the following configuration values were set to None:

```
mysql.ssl_ca: None
mysql.ssl_cert: None
mysql.ssl_key: None
```

In the _get_serv function of the mysql returner, the MySQL connection specifies the ssl argument (line 220).

```
        # An empty ssl_options dictionary passed to MySQLdb.connect will
        # effectively connect w/o SSL
...
            conn = MySQLdb.connect(host=_options.get('host'),
                                   user=_options.get('user'),
                                   passwd=_options.get('pass'),
                                   db=_options.get('db'),
                                   port=_options.get('port'),
                                   ssl=ssl_options)
```

Removal of "ssl=ssl_options" corrects the issue and the module non-SSL connections work as suggested by the documentation.

The supposition is that the presence of the "ssl" argument is sufficient to trigger MySQLdb's import of the OpenSSL libraries, resulting in a failure.  While these libraries are likely to be relatively up to date in recent releases of the operating system, disabling SSL for MySQL should remain a functional alternative. 

CC: @SEJeff @junster1 @jdconti

**Comment by UtahDave** [comment]
Can you provide the output of `salt-minion --versions-report`?

**Comment by SEJeff** [comment]
When running via `salt-call state.sls any.state --return=mysql` it silently dies, but adds this in the minion log when the log level is upped to debug. There is no way to know that it isn't returning data other than looking at the mysql table and noticing it isn't sending anything.

That is a bit concerning.

```
2015-09-16 16:11:36,298 [salt.utils.lazy  ][DEBUG   ][20097] LazyLoaded mysql.returner
2015-09-16 16:11:36,298 [salt.returners   ][INFO    ][20097] Using default for mysql ssl_key
2015-09-16 16:11:36,298 [salt.returners   ][INFO    ][20097] Using default for mysql ssl_cert
2015-09-16 16:11:36,298 [salt.returners   ][INFO    ][20097] Using default for mysql ssl_ca
```

However, when running a command from the master, the full traceback happens:

```python
2015-09-16 16:11:36,298 [salt.utils.lazy  ][DEBUG   ][20097] LazyLoaded mysql.returner
2015-09-16 16:11:36,298 [salt.returners   ][INFO    ][20097] Using default for mysql ssl_key
2015-09-16 16:11:36,298 [salt.returners   ][INFO    ][20097] Using default for mysql ssl_cert
2015-09-16 16:11:36,298 [salt.returners   ][INFO    ][20097] Using default for mysql ssl_ca
2015-09-16 16:11:36,306 [salt.minion      ][ERROR   ][20097] The return failed for job 20150916161136193071 client library does not have SSL support
2015-09-16 16:11:36,316 [salt.minion      ][ERROR   ][20097] Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/salt/minion.py", line 1265, in _thread_return
    )](ret)
  File "/usr/lib/python2.6/dist-packages/salt/returners/mysql.py", line 234, in returner
    with _get_serv(ret, commit=True) as cur:
  File "/usr/lib/python2.6/contextlib.py", line 16, in __enter__
    return self.gen.next()
  File "/usr/lib/python2.6/dist-packages/salt/returners/mysql.py", line 206, in _get_serv
    ssl=ssl_options,
  File "/usr/lib/pymodules/python2.6/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/pymodules/python2.6/MySQLdb/connections.py", line 170, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
NotSupportedError: client library does not have SSL support
```

@UtahDave As requested good sir!
```bash
# salt-minion --versions-report
           Salt: 2015.5.5
         Python: 2.6.5 (r265:79063, Apr 16 2010, 13:57:41)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.4.1
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: 1.4.1
```

Also of note:

```bash
# dpkg -l python-mysqldb | grep mysqldb
ii  python-mysqldb                                    1.2.2-10build2                                  A Python interface to MySQL

# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=10.04
DISTRIB_CODENAME=lucid
DISTRIB_DESCRIPTION="Ubuntu 10.04 LTS"
```

Hope this helps!

**Comment by SEJeff** [comment]
I've got a way to test for this in `__virtual__` @UtahDave that I think will work:

```python
>>> print MySQLdb.version_info
(1, 2, 2, 'final', 0)
>>> import MySQLdb
>>> MySQLdb._mysql.connect(ssl={})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
_mysql_exceptions.NotSupportedError: client library does not have SSL support
```

On my desktop, where this does actually work:

```python
>>> MySQLdb._mysql.connect(ssl={})
Traceback (most recent call last):
  File "<console>", line 1, in <module>
OperationalError: (2002, "Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)")
>>> print MySQLdb.version_info
(1, 2, 3, 'final', 0)
```

Not the most beautiful thing, but I was unable to find another way to determine if the python mysql binding were built with ssl support or not. At least this would allow you to check things in virtual and set something to error out a bit more gracefully if ssl settings are specified and the minion won't support it.
