### ISSUE TITLE
In git.config_set state CommandExecutionError occurs when global=True when using salt 2015.8.0

### ISSUE THREAD

**Issue by msummers42** [saltstack/salt#27205]
We see CommandExecutionError, reproducible using the contrived state below, with salt-ssh-2015.8.0, 100% of the time, on a Linux minion. The same error occurs for any state using git.config_set. This appears to be a result of this line https://github.com/saltstack/salt/blob/develop/salt/states/git.py#L1923 or so, where the CWD is set rather oddly to a directory named 'global'. It is unclear to me why that is the case.

Please let me know if I can provide any further information. Thanks!

```
jackb-gitconfig-name:
  git.config_set:
    - name: user.name
    - value: ' Jack Black'
    - global: True
    - user: jackb
```

```
my-git-config-minion-yay:
----------
          ID: jackb-gitconfig-name
    Function: git.config_set
        Name: user.name
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/tmp/.foodiddle_2e8e09_salt/salt/state.py", line 1591, in call                                                    
                  **cdata['kwargs'])                                                                                                 
                File "/tmp/.foodiddle_2e8e09_salt/salt/states/git.py", line 1927, in config_set                                         
                  **{'all': True}                                                                                                    
                File "/tmp/.foodiddle_2e8e09_salt/salt/modules/git.py", line 865, in config_get                                         
                  **kwargs)                                                                                                          
                File "/tmp/.foodiddle_2e8e09_salt/salt/modules/git.py", line 79, in _config_getter                                      
                  failhard=False)                                                                                                    
                File "/tmp/.foodiddle_2e8e09_salt/salt/modules/git.py", line 217, in _git_run                                           
                  **kwargs)                                                                                                          
                File "/tmp/.foodiddle_2e8e09_salt/salt/modules/cmdmod.py", line 1550, in run_all                                        
                  use_vt=use_vt)                                                                                                     
                File "/tmp/.foodiddle_2e8e09_salt/salt/modules/cmdmod.py", line 421, in _run                                            
                  .format(cwd)                                                                                                       
              CommandExecutionError: Specified cwd '/home/jackb/global' either not absolute or does not exist                     
     Started: 19:54:30.901818
    Duration: 27.785 ms
     Changes:
```

Also, I should note that salt-ssh --versions-report does not output the correct data for at least one dependency (python-gnupg. I have noted versions to the right of where it failed. salt-ssh is currently installed in a python-2.7 virtualenv using 'pip install salt-ssh'

```
Salt Version:
           Salt: 2015.8.0
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: Not Installed
         Python: 2.7.9 (default, Dec 30 2014, 09:52:01)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: Not Installed
           cffi: 1.1.2
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed  python-gnupg (0.3.7)
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: gentoo 2.2 
        machine: x86_64
        release: 4.1.6-hardened-r2
         system: Gentoo Base System 2.2
```

**Comment by jfindlay** [comment]
@msummers42, thanks for the report.  Will you create a separate issue for the salt-ssh version problem?

@terminalmage

**Comment by pravka** [comment]
I just ran into this today in `develop` as well. Did a little research and found that this is broken since c4861b6ab3a4c411db4bfd7199eebf6cade83e18, when the `global` function replaced `is_global` and started to `cwd` instead of appending `--global` to the git command. AFAIK `cwd`ing to `'global'` is something that's never performed in practice; `---global` just writes to the default `.gitconfig` (usually in `$HOME`).

**Comment by terminalmage** [comment]
The ``global`` function never replaced anything, it's just being plucked out of the kwargs.

I'll get a fix in for this today.

**Comment by terminalmage** [comment]
As a bit of background, this issue is being caused by changes I made during my restructuring of the git state and execution modules, where I later made further changes but did not make all the needed changes in the state.

**Comment by pravka** [comment]
Awesome, thanks @terminalmage. The only reason I said `global` replaced `is_global` was because of this bit:

```
    global : False
        If ``True``, this will set a global git config option
        .. versionchanged:: 2015.8.0
            Option renamed from ``is_global`` to ``global``. For earlier
            versions, use ``is_global``.
```

**Comment by terminalmage** [comment]
Yeah, I just wanted to make sure you knew we weren't shadowing the built-in ``global()`` function.

**Comment by terminalmage** [comment]
I've opened a pull request to fix this, #27411. If anyone would like to test this, they can use [this walkthrough](https://help.github.com/articles/checking-out-pull-requests-locally/) to checkout the pull request locally.

**Comment by pravka** [comment]
Thanks @terminalmage -- that fixes the execution module. The state module, though, is still broken (`global` is set to `True`, but still attempts to `cwd` to `$HOME/global`).

**Comment by terminalmage** [comment]
Hmmm, it shouldn't. I'll have another look.

**Comment by terminalmage** [comment]
@pravka can you show me an SLS example?

**Comment by pravka** [comment]
Sure. 

`roots/git.sls`:
```
set global git name:
  git.config_set:
    - name: user.name
    - value: {{ salt['pillar.get']('user:fullname') }}
    - user: {{ salt['pillar.get']('user:username') }}
    - global: True

set global git email:
  git.config_set:
    - name: user.email
    - value: {{ salt['pillar.get']('user:email') }}
    - user: {{ salt['pillar.get']('user:username') }}
    - global: True
```

```
 testuser@testbox  ~/Code/dev/salt$  sudo salt-call --local pillar.get user:email
local:
    test.user@gmail.com
 testuser@testbox  ~/Code/dev/salt$  sudo salt-call --local pillar.get user:username
local:
    testuser
 testuser@testbox  ~/Code/dev/salt$  sudo salt-call --local state.sls git
INFO Loading fresh modules for state activity
INFO Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://git/init.sls'
INFO Running state [user.name] at time 19:24:13.891556
INFO Executing state git.config_set for user.name
INFO Executing command ['git', '--version'] in directory '/Users/testuser'
INFO Executing command ['git', 'config', '--local', '--get-all', 'user.name'] in directory '/Users/testuser/global'
ERROR An exception occurred in this state: Traceback (most recent call last):
  File "/usr/local/Cellar/saltstack/develop/libexec/lib/python2.7/site-packages/salt/state.py", line 1655, in call
    **cdata['kwargs'])
  File "/usr/local/Cellar/saltstack/develop/libexec/lib/python2.7/site-packages/salt/states/git.py", line 1927, in config_set
    **{'all': True}
  File "/usr/local/Cellar/saltstack/develop/libexec/lib/python2.7/site-packages/salt/modules/git.py", line 865, in config_get
    **kwargs)
  File "/usr/local/Cellar/saltstack/develop/libexec/lib/python2.7/site-packages/salt/modules/git.py", line 79, in _config_getter
    failhard=False)
  File "/usr/local/Cellar/saltstack/develop/libexec/lib/python2.7/site-packages/salt/modules/git.py", line 217, in _git_run
    **kwargs)
  File "/usr/local/Cellar/saltstack/develop/libexec/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 1551, in run_all
    use_vt=use_vt)
  File "/usr/local/Cellar/saltstack/develop/libexec/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 422, in _run
    .format(cwd)
CommandExecutionError: Specified cwd '/Users/testuser/global' either not absolute or does not exist

INFO Completed state [user.name] at time 19:24:13.955742 duration_in_ms=64.186
INFO Running state [user.email] at time 19:24:13.956058
INFO Executing state git.config_set for user.email
INFO Executing command ['git', 'config', '--local', '--get-all', 'user.email'] in directory '/Users/testuser/global'
ERROR An exception occurred in this state: Traceback (most recent call last):
  File "/usr/local/Cellar/saltstack/develop/libexec/lib/python2.7/site-packages/salt/state.py", line 1655, in call
    **cdata['kwargs'])
  File "/usr/local/Cellar/saltstack/develop/libexec/lib/python2.7/site-packages/salt/states/git.py", line 1927, in config_set
    **{'all': True}
  File "/usr/local/Cellar/saltstack/develop/libexec/lib/python2.7/site-packages/salt/modules/git.py", line 865, in config_get
    **kwargs)
  File "/usr/local/Cellar/saltstack/develop/libexec/lib/python2.7/site-packages/salt/modules/git.py", line 79, in _config_getter
    failhard=False)
  File "/usr/local/Cellar/saltstack/develop/libexec/lib/python2.7/site-packages/salt/modules/git.py", line 217, in _git_run
    **kwargs)
  File "/usr/local/Cellar/saltstack/develop/libexec/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 1551, in run_all
    use_vt=use_vt)
  File "/usr/local/Cellar/saltstack/develop/libexec/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 422, in _run
    .format(cwd)
CommandExecutionError: Specified cwd '/Users/testuser/global' either not absolute or does not exist

INFO Completed state [user.email] at time 19:24:13.957385 duration_in_ms=1.327
local:
----------
          ID: set global git name
    Function: git.config_set
        Name: user.name
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/local/Cellar/saltstack/develop/libexec/lib/python2.7/site-packages/salt/state.py", line 1655, in call
                  **cdata['kwargs'])
                File "/usr/local/Cellar/saltstack/develop/libexec/lib/python2.7/site-packages/salt/states/git.py", line 1927, in config_set
                  **{'all': True}
                File "/usr/local/Cellar/saltstack/develop/libexec/lib/python2.7/site-packages/salt/modules/git.py", line 865, in config_get
                  **kwargs)
                File "/usr/local/Cellar/saltstack/develop/libexec/lib/python2.7/site-packages/salt/modules/git.py", line 79, in _config_getter
                  failhard=False)
                File "/usr/local/Cellar/saltstack/develop/libexec/lib/python2.7/site-packages/salt/modules/git.py", line 217, in _git_run
                  **kwargs)
                File "/usr/local/Cellar/saltstack/develop/libexec/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 1551, in run_all
                  use_vt=use_vt)
                File "/usr/local/Cellar/saltstack/develop/libexec/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 422, in _run
                  .format(cwd)
              CommandExecutionError: Specified cwd '/Users/testuser/global' either not absolute or does not exist
     Started: 19:24:13.891556
    Duration: 64.186 ms
     Changes:
----------
          ID: set global git email
    Function: git.config_set
        Name: user.email
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/local/Cellar/saltstack/develop/libexec/lib/python2.7/site-packages/salt/state.py", line 1655, in call
                  **cdata['kwargs'])
                File "/usr/local/Cellar/saltstack/develop/libexec/lib/python2.7/site-packages/salt/states/git.py", line 1927, in config_set
                  **{'all': True}
                File "/usr/local/Cellar/saltstack/develop/libexec/lib/python2.7/site-packages/salt/modules/git.py", line 865, in config_get
                  **kwargs)
                File "/usr/local/Cellar/saltstack/develop/libexec/lib/python2.7/site-packages/salt/modules/git.py", line 79, in _config_getter
                  failhard=False)
                File "/usr/local/Cellar/saltstack/develop/libexec/lib/python2.7/site-packages/salt/modules/git.py", line 217, in _git_run
                  **kwargs)
                File "/usr/local/Cellar/saltstack/develop/libexec/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 1551, in run_all
                  use_vt=use_vt)
                File "/usr/local/Cellar/saltstack/develop/libexec/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 422, in _run
                  .format(cwd)
              CommandExecutionError: Specified cwd '/Users/testuser/global' either not absolute or does not exist
     Started: 19:24:13.956058
    Duration: 1.327 ms
     Changes:

Summary for local
------------
Succeeded: 0
Failed:    2
------------
Total states run:     2
Total run time:  65.513 ms
```

**Comment by terminalmage** [comment]
I've also updated the pull request, I left out some commas.

**Comment by terminalmage** [comment]
Thanks for the examples, I'll have a look at this on Saturday.

**Comment by pravka** [comment]
You get a chance to look at this @terminalmage?

**Comment by terminalmage** [comment]
No, but I will be able to do so today. Sorry for the delay.

**Comment by terminalmage** [comment]
@pravka It works for me:

```
# salt-call state.single git.config_set name=user.name value='Foo Bar' user=foo global=True
[INFO    ] Loading fresh modules for state activity
[INFO    ] Running state [user.name] at time 17:41:21.856966
[INFO    ] Executing state git.config_set for user.name
[INFO    ] Executing command ['git', 'config', '--global', '--get-all', 'user.name'] as user 'foo' in directory '/home/foo'
[INFO    ] Executing command ['git', 'config', '--global', '--replace-all', 'user.name', 'Foo Bar'] as user 'foo' in directory '/home/foo'
[INFO    ] Executing command ['git', 'config', '--global', '--get-all', 'user.name'] as user 'foo' in directory '/home/foo'
[INFO    ] Made the following changes:
'user.name' changed from None to ['Foo Bar']

[INFO    ] Completed state [user.name] at time 17:41:21.991937
local:
----------
          ID: user.name
    Function: git.config_set
      Result: True
     Comment: Global key 'user.name' was added as 'Foo Bar'
     Started: 17:41:21.856966
    Duration: 134.971 ms
     Changes:
              ----------
              user.name:
                  ----------
                  new:
                      - Foo Bar
                  old:
                      None

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time: 134.971 ms
# salt-call git.config_get user.name global=True user=foo
[INFO    ] Executing command ['git', 'config', '--global', '--get-all', 'user.name'] as user 'foo' in directory '/home/foo'
local:
    Foo Bar
```

**Comment by terminalmage** [comment]
@pravka There really is nothing in the git state code anymore that would cwd to a directory called "global", it's all been replaced in my PR. My guess is that you may not have checked out the right revision. Github lets you check out pull requests locally, I linked that walkthrough in an earlier commit but here it is again:

https://help.github.com/articles/checking-out-pull-requests-locally/

If you use that to checkout my pull request, you should be able to install that for testing. If you are still unsure of how to do that, my testing above (with the info-level logging showing the commands being run) should be enough to display how the code now properly handles ``global: True``.

**Comment by pravka** [comment]
Yeah, I just tried against your PR and it worked. Sorry for the confusion @terminalmage, and thanks for fixing it!

**Comment by terminalmage** [comment]
No problem! Glad you were able to confirm. Thanks for helping.
