### ISSUE TITLE
Global exception during test.ping 2015.8.0/RAET

### ISSUE THREAD

**Issue by turtletraction** [saltstack/salt#27229]
Hello,

I have the excpetion below while attempting an test.ping the installation as you can see below is with RAET only and is intended to run exclusively on RAET and salt-ssh.
Both the minion and master are running fine and I can not spot something obvious in the debug traces.
The installations of all components has been done from source and I can only install from source.

I have update all componentes to the latest version and after several failing attempts in reinstallations I am now turing to you.
I would much appriciate you can point me in the right direction. Hopefully I missed something trivial.

Apologize for the formatting below but my browser does not support any fancy stuff.

::Versions report::
```yaml
Salt Version:
           Salt: 2015.8.0

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: Not Installed
         Python: 2.7.10 (default, Sep 18 2015, 10:49:43)
           RAET: 0.6.1
        Tornado: 4.2.1
            ZMQ: Not Installed
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.3.9
        libnacl: 1.4.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: redhat 6.4 Santiago
        machine: x86_64
        release: 2.6.32-358.11.1.el6.x86_64
         system: Red Hat Enterprise Linux Server 6.4 Santiago
```
```python-traceback
Global exception:
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: get_event() got an unexpected keyword argument 'match_type'
Traceback (most recent call last):
  File "/usr/local/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/local/lib/python2.7/site-packages/salt/scripts.py", line 454, in salt_main
    client.run()
  File "/usr/local/lib/python2.7/site-packages/salt/cli/salt.py", line 198, in run
    for full_ret in cmd_func(**kwargs):
  File "/usr/local/lib/python2.7/site-packages/salt/client/__init__.py", line 606, in cmd_cli
    **kwargs):
  File "/usr/local/lib/python2.7/site-packages/salt/client/__init__.py", line 1255, in get_cli_event_returns
    expect_minions=(verbose or show_timeout)
  File "/usr/local/lib/python2.7/site-packages/salt/client/__init__.py", line 886, in get_iter_returns
    for raw in ret_iter:
  File "/usr/local/lib/python2.7/site-packages/salt/client/__init__.py", line 823, in get_returns_no_block
    raw = self.event.get_event(wait=0.01, tag=tag, match_type=match_type, full=True, no_block=True)
TypeError: get_event() got an unexpected keyword argument 'match_type'
Traceback (most recent call last):
  File "/usr/local/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/local/lib/python2.7/site-packages/salt/scripts.py", line 454, in salt_main
    client.run()
  File "/usr/local/lib/python2.7/site-packages/salt/cli/salt.py", line 198, in run
    for full_ret in cmd_func(**kwargs):
  File "/usr/local/lib/python2.7/site-packages/salt/client/__init__.py", line 606, in cmd_cli
    **kwargs):
  File "/usr/local/lib/python2.7/site-packages/salt/client/__init__.py", line 1255, in get_cli_event_returns
    expect_minions=(verbose or show_timeout)
  File "/usr/local/lib/python2.7/site-packages/salt/client/__init__.py", line 886, in get_iter_returns
    for raw in ret_iter:
  File "/usr/local/lib/python2.7/site-packages/salt/client/__init__.py", line 823, in get_returns_no_block
    raw = self.event.get_event(wait=0.01, tag=tag, match_type=match_type, full=True, no_block=True)
TypeError: get_event() got an unexpected keyword argument 'match_type'
```

Many thanks in advance,
kgc

**Comment by jfindlay** [comment]
@kgcsaltstack, thanks for the report.

**Comment by jfindlay** [comment]
@kgcsaltstack, the pull request you have made gets past the original error, but really the new arguments need to be supported in RAET.  I think what I'll do is make RAETEvent a subclass of SaltEvent to avoid duplication, but I'll need some time to test this.

**Comment by turtletraction** [comment]
Hello,
The solution provided in #27213 worked like a charm and just in time for the next challenge, "Reaped yard manor". I logged a new issue #27269.
Many thanks

**Comment by cachedout** [comment]
OK, since this issue is fixed and a corresponding issue is being tracked elsewhere, I am going to go ahead and close this issue. Thanks all.
