### ISSUE TITLE
Excessive cmd.run output causes salt to eat up all memory

### ISSUE THREAD

**Issue by tomasfejfar** [saltstack/salt#27323]
In one of our states we mistakedly ran `cmd.run` with `cat massive.log`. That caused salt to wreak havoc with the server, eating most of the memory. That subsequently causing `mysqld` running on the machine to swap out and that was practically the end :) 

This would also be an issue if the cmd.run would endlessly output anything, which would be much more common issue, than the stupid mistake we did. 

It would be nice if salt could shield us from such issues either by limiting the cmd output to reasonable amount (with option NOT to) or by handling the output in an memory-efficient manner (maybe redirect excessive output to file, start sending it to salt master piece by piece or something like that).

We experienced this on rather old stack:

```
           Salt: 0.17.5
         Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.6
         PyYAML: 3.10
          PyZMQ: 13.1.0
            ZMQ: 3.2.3
```

I tried to replicate it with newer salt on our dev stack:

```
                  Salt: 2014.7.5
                Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
                Jinja2: 2.6
              M2Crypto: 0.21.1
        msgpack-python: 0.1.10
          msgpack-pure: Not Installed
              pycrypto: 2.6
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 13.1.0
                  RAET: Not Installed
                   ZMQ: 3.2.3
                  Mako: 0.7.0
 Debian source package: 2014.7.5+ds-1~bpo70+1
```

`tomas@web1:~$ dd if=/dev/zero of=1GBfile bs=1000 count=1000000`
`root@salt:/home/tomas# salt web1\* cmd.run 'cat /home/tomas/1GBfile'`
Which behaves the same way, except it runs out of memory (we don't have swap on our dev stack). 

```
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1020, in _thr                                                                                                        ead_return
        return_data = func(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/cmdmod.py", line 624,                                                                                                         in run
        use_vt=use_vt)
      File "/usr/lib/python2.7/dist-packages/salt/modules/cmdmod.py", line 379,                                                                                                         in _run
        proc.wait(timeout)
      File "/usr/lib/python2.7/dist-packages/salt/utils/timed_subprocess.py", li                                                                                                        ne 59, in wait
        receive()
      File "/usr/lib/python2.7/dist-packages/salt/utils/timed_subprocess.py", li                                                                                                        ne 33, in receive
        (self.stdout, self.stderr) = self.process.communicate(input=self.stdin)
      File "/usr/lib/python2.7/subprocess.py", line 746, in communicate
        stdout = _eintr_retry_call(self.stdout.read)
      File "/usr/lib/python2.7/subprocess.py", line 478, in _eintr_retry_call
        return func(*args)
    MemoryError
```

As seen above the issue is not present if the file exceeds the memory size (it will just fail). But if the file barely fits it will remain in the memory for the reminder of the salt-call, which is an issue, because it causes the server to swap and further slow down the execution of the state. 

Let me know if I could supply any more useful information.

**Comment by jfindlay** [comment]
@tomasfejfar, thanks for the report.  This would be a good feature to have.
