### ISSUE TITLE
JSON Render failed

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#27325]
What's wrong here?

Note: for other minions my_sls_file works perfectly.

    >>> salt-ssh minion state.sls my_sls_file
    [ERROR   ] JSON Render failed for: 
    Traceback (most recent call last):
      File "/tmp/.root_dcdf8c__salt/salt-call", line 4, in <module>
        salt_call()
      File "/tmp/.root_dcdf8c__salt/salt/scripts.py", line 227, in salt_call
        client.run()
      File "/tmp/.root_dcdf8c__salt/salt/cli/call.py", line 69, in run
        caller.run()
      File "/tmp/.root_dcdf8c__salt/salt/cli/caller.py", line 236, in run
        ret = self.call()
      File "/tmp/.root_dcdf8c__salt/salt/cli/caller.py", line 138, in call
        ret['return'] = func(*args, **kwargs)
      File "/tmp/.root_dcdf8c__salt/salt/modules/state.py", line 1144, in pkg
      File "/tmp/.root_dcdf8c__salt/salt/state.py", line 1626, in call_chunks
      File "/tmp/.root_dcdf8c__salt/salt/state.py", line 1771, in call_chunk
      File "/tmp/.root_dcdf8c__salt/salt/state.py", line 623, in _mod_aggregate
      File "/tmp/.root_dcdf8c__salt/salt/utils/lazy.py", line 90, in __getitem__
        raise KeyError(key)
    KeyError: 'config.option'
    [ERROR   ] No JSON object could be decoded
    minion:

**Comment by jfindlay** [comment]
@srkunze, thanks for the report.  What is the output of `salt-ssh --versions-report`?  What are the operating systems of the master, the minion that does not work, and a minion that does work?  Is it possible for you to post the contents of `my_state_file`?

**Comment by srkunze** [comment]
salt:~ # salt-ssh --versions-report
               Salt: 2015.5.2
             Python: 2.7.3 (default, Apr 14 2012, 08:58:41) [GCC]
             Jinja2: 2.7.3
           M2Crypto: 0.22
     msgpack-python: 0.4.2
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
            libnacl: Not Installed
             PyYAML: 3.11
              ioflo: Not Installed
              PyZMQ: 14.3.1
               RAET: Not Installed
                ZMQ: 4.0.5
               Mako: Not Installed

Master, working minions, the not-working minion all are OpenSUSE 12.3.

**Comment by srkunze** [comment]
Holy cow. I removed the `/tmp/.root_dcdf8c__salt/` directory and did the salt-ssh call again.

Then it worked.

**Comment by srkunze** [comment]
It could be that it is related to: https://github.com/saltstack/salt/issues/26467

**Comment by jfindlay** [comment]
@srkunze, thanks for the extra info.  Let's close this unless you can reproduce it verifiably distinct from #26467.
