### ISSUE TITLE
salt-minion exits

### ISSUE THREAD

**Issue by freedba** [saltstack/salt#27320]
``` python-traceback
salt-master response:
            ----------
            out:
                nested
            return:
                The minion function caused an exception: Traceback (most recent call last):
                  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 1161, in _thread_return
                    return_data = func(*args, **kwargs)
                  File "/usr/lib/python2.6/site-packages/salt/modules/state.py", line 655, in sls
                    st_ = salt.state.HighState(opts, pillar, kwargs.get('__pub_jid'))
                  File "/usr/lib/python2.6/site-packages/salt/state.py", line 3026, in __init__
                    BaseHighState.__init__(self, opts)
                  File "/usr/lib/python2.6/site-packages/salt/state.py", line 2205, in __init__
                    self.avail = self.__gather_avail()
                  File "/usr/lib/python2.6/site-packages/salt/state.py", line 2215, in __gather_avail
                    avail[saltenv] = self.client.list_states(saltenv)
                  File "/usr/lib/python2.6/site-packages/salt/fileclient.py", line 411, in list_states
                    for path in self.file_list(saltenv):
                  File "/usr/lib/python2.6/site-packages/salt/fileclient.py", line 1096, in file_list
                    return self.channel.send(load)
                  File "/usr/lib/python2.6/site-packages/salt/transport/__init__.py", line 314, in send
                    return self._crypted_transfer(load, tries, timeout)
                  File "/usr/lib/python2.6/site-packages/salt/transport/__init__.py", line 302, in _crypted_transfer
                    return _do_transfer()
                  File "/usr/lib/python2.6/site-packages/salt/transport/__init__.py", line 293, in _do_transfer
                    timeout)
                  File "/usr/lib/python2.6/site-packages/salt/payload.py", line 273, in send
                    'SaltReqTimeoutError: after {0} seconds, ran {1} tries'.format(timeout * tried, tried)
                SaltReqTimeoutError: SaltReqTimeoutError: after 180 seconds, ran 3 tries
```

```
salt-minion log
2015-09-23 09:05:44,567 [salt.minion                              ][WARNING ][13031] The minion function caused an exception
2015-09-23 09:08:44,680 [salt.minion                              ][WARNING ][13031] The minion failed to return the job information for job 20150923090239242036. This is often due to the master being shut down or overloaded. If the master is running consider increasing the worker_threads value.
2015-09-23 09:16:44,866 [salt.scripts                             ][ERROR   ][24655] Attempt to authenticate with the salt master failed
2015-09-23 09:16:44,867 [salt.scripts                             ][WARNING ][24655] ** Restarting minion **
```

**Comment by jfindlay** [comment]
@freedba, thanks for the report.  What is the output of `salt --versions-report` for both the master and minion?  How did you install salt, and do you have any leftover minion keys on the master that might be conflicting with the minion?

**Comment by freedba** [comment]
@jfindlay

 # salt-master --versions-report
           Salt: 2015.5.5
         Python: 2.6.6 (r266:84292, Feb 22 2013, 00:00:18)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 2.2.0.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: Not Installed

# salt-minion --versions-report
           Salt: 2015.5.3
         Python: 2.6.6 (r266:84292, Feb 22 2013, 00:00:18)
         Jinja2: unknown
       M2Crypto: 0.20.2
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed
        Tornado: Not Installed

it is caused by different version ?

when the master is overload, as loadavg > 50  , it may be appear.

**Comment by jfindlay** [comment]
@freedba, how many minions do you have connected to the master?  If your master is overworked, have you thought about [tweaking salt configs for scale](https://docs.saltstack.com/en/latest/topics/tutorials/intro_scale.html)?  Do you run anything else on the master besides salt?

**Comment by freedba** [comment]
now 1000+ minions connected to the master, where I restart the master, the master load avg to 50+,
master config work thread 100

**Comment by freedba** [comment]
the master server only run salt-master.

**Comment by whiteinge** [comment]
It is normal to see a period of high load on the master when you restart the daemon because all minions reconnect and reauthenticate.

Definitely read the document about running and configuring Salt at higher loads that @jfindlay linked above. I also highly recommend using the normal system metrics gathering tools to find out where your master is struggling (CPU, RAM, disk IO, available disk space, available inodes).  Tweak the Salt configs as described to spread the load and find the hardware limitations you're hitting so you know where to add resources (more cores, more RAM, faster disk, offload job returns to another server, etc).

Lastly, 100 worker processes is quite high and will use a lot of RAM and will not likely speed things up since each process will be competing for shared resources. Each process can handle quite a few concurrent minions. I recommend dropping that value to 20 and benchmarking from there.

**Comment by freedba** [comment]
@whiteinge @jfindlay 
Thanks ,  
I added arg -b 30 , but error:

# salt --async --show-jid -b 30 '*' state.sls zabbix 


Executing run on ['zhaoshang-member02.idc1.fn', 'www10.idc1.fn', 'stock-job02.idc1.fn', 'register09.idc1.fn', 'image-api02.idc1.fn', 'stage-move.idc1.fn', 'promotionapp01.idc1.fn', 'outside-out02.idc1.fn', 'webim03.idc1.fn', 'member-api08.idc1.fn', 'detail01.idc1.fn', 'feiniuorder02.idc1.fn', 'img005.idc1.fn', 'passport-web04.idc1.fn', 'recommend_server11.idc1.fn', 'member02.idc1.fn', 'stage-partner01.idc1.fn', 'commodity_drp23.idc1.fn', 'imageapp01.idc1.fn', 'aq03.idc1.fn', 'www-api23.idc1.fn', 'haproxy03.idc1.fn', 'log-kibana01.idc1.fn', 'cmstask11.idc1.fn', 'solr08.idc1.fn', 'stage-bonusfill01.idc1.fn', 'www40.idc1.fn', 'static04.idc1.fn', 'item-api02.idc1.fn', 'pos-api02.idc1.fn']

[ERROR   ] An un-handled exception was caught by salt's global exception handler:
SaltClientError: Salt request timed out. The master is not responding. If this error persists after verifying the master is up, worker_threads may need to be increased.
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 349, in salt_main
    client.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/salt.py", line 98, in run
    for res in batch.run():
  File "/usr/lib/python2.6/site-packages/salt/cli/batch.py", line 151, in run
    part = next(queue)
  File "/usr/lib/python2.6/site-packages/salt/client/__init__.py", line 710, in cmd_iter_no_block
    **kwargs):
  File "/usr/lib/python2.6/site-packages/salt/client/__init__.py", line 978, in get_iter_returns
    jinfo = self.gather_job_info(jid, tgt, tgt_type)
  File "/usr/lib/python2.6/site-packages/salt/client/__init__.py", line 202, in gather_job_info
    timeout=timeout,
  File "/usr/lib/python2.6/site-packages/salt/client/__init__.py", line 286, in run_job
    raise SaltClientError(general_exception)
SaltClientError: Salt request timed out. The master is not responding. If this error persists after verifying the master is up, worker_threads may need to be increased.
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 349, in salt_main
    client.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/salt.py", line 98, in run
    for res in batch.run():
  File "/usr/lib/python2.6/site-packages/salt/cli/batch.py", line 151, in run
    part = next(queue)
  File "/usr/lib/python2.6/site-packages/salt/client/__init__.py", line 710, in cmd_iter_no_block
    **kwargs):
  File "/usr/lib/python2.6/site-packages/salt/client/__init__.py", line 978, in get_iter_returns
    jinfo = self.gather_job_info(jid, tgt, tgt_type)
  File "/usr/lib/python2.6/site-packages/salt/client/__init__.py", line 202, in gather_job_info
    timeout=timeout,
  File "/usr/lib/python2.6/site-packages/salt/client/__init__.py", line 286, in run_job
    raise SaltClientError(general_exception)
salt.exceptions.SaltClientError: Salt request timed out. The master is not responding. If this error persists after verifying the master is up, worker_threads may need to be increased.

**Comment by freedba** [comment]
hi,
how many mnions  one worker_threads can receive ?

**Comment by whiteinge** [comment]
It varies depending on how busy the master is otherwise, but each
worker should be able to process several hundred minion returns each.
