### ISSUE TITLE
file.replace fails if `repl` contains special regex characters and `append_if_not_found=True`

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt#27356]
For more context, see this post in the salt-users group:
https://groups.google.com/d/msg/salt-users/oCM9lD0kSQY/Kh6dNNIWAwAJ

The reported issue was using an asterisk, but I also tested with brackets.

```
C:\salt\srv\states\base> cat test.txt
testme
```

```python-traceback
C:\salt\srv\states\base> c:\salt\salt-call.bat --local file.replace 'C:\salt\srv\states\base\test.txt' 'dumbtest' '[] dumbtest' append_if_not_found=True
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
error: unexpected end of regular expression
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 227, in salt_call
    client.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\call.py", line 69, in run
    caller.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 236, in run
    ret = self.call()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 138, in call
    ret['return'] = func(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\modules\file.py", line 1442, in replace
    if re.search('^{0}$'.format(content), line):
  File "C:\salt\bin\lib\re.py", line 142, in search
    return _compile(pattern, flags).search(string)
  File "C:\salt\bin\lib\re.py", line 244, in _compile
    raise error, v # invalid expression
error: unexpected end of regular expression
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 227, in salt_call
    client.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\call.py", line 69, in run
    caller.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 236, in run
    ret = self.call()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 138, in call
    ret['return'] = func(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\modules\file.py", line 1442, in replace
    if re.search('^{0}$'.format(content), line):
  File "C:\salt\bin\lib\re.py", line 142, in search
    return _compile(pattern, flags).search(string)
  File "C:\salt\bin\lib\re.py", line 244, in _compile
    raise error, v # invalid expression
sre_constants.error: unexpected end of regular expression
```

```python-traceback
C:\salt\srv\states\base> c:\salt\salt-call.bat --local file.replace 'C:\salt\srv\states\base\test.txt' 'dumbtest' '* dumbtest' append_if_not_found=True
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
error: nothing to repeat
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 227, in salt_call
    client.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\call.py", line 69, in run
    caller.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 236, in run
    ret = self.call()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 138, in call
    ret['return'] = func(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\modules\file.py", line 1442, in replace
    if re.search('^{0}$'.format(content), line):
  File "C:\salt\bin\lib\re.py", line 142, in search
    return _compile(pattern, flags).search(string)
  File "C:\salt\bin\lib\re.py", line 244, in _compile
    raise error, v # invalid expression
error: nothing to repeat
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 227, in salt_call
    client.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\call.py", line 69, in run
    caller.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 236, in run
    ret = self.call()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 138, in call
    ret['return'] = func(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\modules\file.py", line 1442, in replace
    if re.search('^{0}$'.format(content), line):
  File "C:\salt\bin\lib\re.py", line 142, in search
    return _compile(pattern, flags).search(string)
  File "C:\salt\bin\lib\re.py", line 244, in _compile
    raise error, v # invalid expression
sre_constants.error: nothing to repeat
```

I believe the issue is in [this line](https://github.com/saltstack/salt/blob/2015.5/salt/modules/file.py#L1444), where the `content` needs to be wrapped in re.escape() so it compiles properly.

**Comment by jfindlay** [comment]
@lorengordon, thanks for fixing this.
