### ISSUE TITLE
`salt-call` goes into infinite loop when PKI directory doesn't exist

### ISSUE THREAD

**Issue by eliasp** [saltstack/salt#27453]
When `/etc/salt/pki` or `/etc/salt/pki/minion` don't exist, `salt-call` will end up in an infinite loop repeating the last lines of the following output until it is forcefully terminated:
```
[ERROR   ] Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 230, in wrapper
    yielded = next(result)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 494, in eval_master
    pub_channel = salt.transport.client.AsyncPubChannel.factory(self.opts, **factory_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/client.py", line 150, in factory
    return salt.transport.zeromq.AsyncZeroMQPubChannel(opts, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 242, in __init__
    self.auth = salt.crypt.AsyncAuth(self.opts, io_loop=self.io_loop)
  File "/usr/lib/python2.7/dist-packages/salt/crypt.py", line 323, in __new__
    new_auth.__singleton_init__(opts, io_loop=io_loop)
  File "/usr/lib/python2.7/dist-packages/salt/crypt.py", line 361, in __singleton_init__
    self.get_keys()
  File "/usr/lib/python2.7/dist-packages/salt/crypt.py", line 575, in get_keys
    salt.utils.verify.check_path_traversal(self.opts['pki_dir'], user)
  File "/usr/lib/python2.7/dist-packages/salt/utils/verify.py", line 400, in check_path_traversal
    raise SaltClientError(msg)
SaltClientError: Could not access /etc/salt/pki. Path does not exist.
Exception AttributeError: "'AsyncZeroMQPubChannel' object has no attribute 'context'" in <bound method AsyncZeroMQPubChannel.__del__ of <salt.transport.zeromq.AsyncZeroMQPubChannel object at 0x7f7f783d8490>> ignored
Exception ValueError: 'I/O operation on closed file' in <bound method SyncWrapper.__del__ of <salt.utils.async.SyncWrapper object at 0x7f7f783d8490>> ignored
Exception ValueError: 'I/O operation on closed file' in <bound method SyncWrapper.__del__ of <salt.utils.async.SyncWrapper object at 0x7f7f783d8490>> ignored
Exception ValueError: 'I/O operation on closed file' in <bound method SyncWrapper.__del__ of <salt.utils.async.SyncWrapper object at 0x7f7f783d8490>> ignored
```

```


    Salt Version:
               Salt: 2015.8.0
     
    Dependency Versions:
             Jinja2: 2.7.3
           M2Crypto: Not Installed
               Mako: 1.0.0
             PyYAML: 3.11
              PyZMQ: 14.4.0
             Python: 2.7.9 (default, Apr  2 2015, 15:33:21)
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.4
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 2.2
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.2
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: Not Installed
            timelib: Not Installed
     
    System Versions:
               dist: Ubuntu 15.04 vivid
            machine: x86_64
            release: 4.1.7-200.fc22.x86_64
             system: Ubuntu 15.04 vivid
```

**Comment by jfindlay** [comment]
@eliasp, thanks for the report.  Related to https://github.com/saltstack/salt/issues/27063#issuecomment-143269141.

**Comment by cachedout** [comment]
I think this is actually fixed. Have you tried it at the HEAD of the 2015.8 branch?

**Comment by eliasp** [comment]
HEAD of 2015.8 at least doesn't end in an infinite loop anymore, but shows now this message instead when the PKI directory is missing:
```
~# salt-call test.versions_report
[WARNING ] Failed to open log file, do you have permission to write to /var/log/salt/minion?
[ERROR   ] Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 230, in wrapper
    yielded = next(result)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 495, in eval_master
    pub_channel = salt.transport.client.AsyncPubChannel.factory(self.opts, **factory_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/client.py", line 150, in factory
    return salt.transport.zeromq.AsyncZeroMQPubChannel(opts, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 242, in __init__
    self.auth = salt.crypt.AsyncAuth(self.opts, io_loop=self.io_loop)
  File "/usr/lib/python2.7/dist-packages/salt/crypt.py", line 323, in __new__
    new_auth.__singleton_init__(opts, io_loop=io_loop)
  File "/usr/lib/python2.7/dist-packages/salt/crypt.py", line 361, in __singleton_init__
    self.get_keys()
  File "/usr/lib/python2.7/dist-packages/salt/crypt.py", line 575, in get_keys
    salt.utils.verify.check_path_traversal(self.opts['pki_dir'], user)
  File "/usr/lib/python2.7/dist-packages/salt/utils/verify.py", line 400, in check_path_traversal
    raise SaltClientError(msg)
SaltClientError: Could not access /etc/salt/pki. Path does not exist.
Exception AttributeError: "'AsyncZeroMQPubChannel' object has no attribute 'context'" in <bound method AsyncZeroMQPubChannel.__del__ of <salt.transport.zeromq.AsyncZeroMQPubChannel object at 0x7fa4001a7bd0>> ignored
Exception ValueError: 'I/O operation on closed file' in <bound method SyncWrapper.__del__ of <salt.utils.async.SyncWrapper object at 0x7fa4001a7bd0>> ignored
Could not access /etc/salt/pki. Path does not exist.
```

**Comment by eliasp** [comment]
I'm not sure whether it should show a simple error message or the full backtrace instead.
I'd be fine with the current result, but I don't know how Salt's "philosophy" on error reporting/output is in such cases (simple error msg vs full backtrace).

**Comment by jfindlay** [comment]
@eliasp, the important thing to me is that salt should provide itself a directory it expects to exist before using it, whether that is part of the installation process, or execution of the salt daemons, or both.

**Comment by stbenjam** [comment]
You can run salt-call before starting salt-minion daemon, so I think it'd be better if it just didn't fail if the dir doesn't exist, or include it in the packaging.

Foreman uses salt-call to trigger the key upload to the master in a kickstart, where you really can't (or at least shouldn't) start a service like salt-minion.

**Comment by dmurphy18** [comment]
Changes need to be forwarded to Redhat 5 & 7 state build files.
Awaiting build reorganization

**Comment by jmiller0** [comment]
This is still broken in salt-2015.8.3-1.el7.noarch.rpm

**Comment by frensjan** [comment]
I can confirm the report by @jmiller0

**Comment by dmurphy18** [comment]
Fixing in #29701, consider duplicate
