### ISSUE TITLE
Rendering SLS failed, render error: while passing a block collection...

### ISSUE THREAD

**Issue by unassassinable** [saltstack/salt#27527]
I just started using Salt yesterday, so navigating around the help docs is a little difficult.  I am trying to install multiple packages, start a service that depends on both packages being installed, and copy a config file to the minion (depending on the grain "office" of the minion), and restart the service if the file changes.  I get the following error:

```
Rendering SLS configure-SNMP failed, render error: while parsing a block collection
  in "<unicode string>", line 12, column 4:
       - enable: True
       ^
expected <block end>, but found '<block sequence start>'
  in "<unicode string>", line 13, column 5:
        - watch:
        ^
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2632, in render_state
    sls, rendered_sls=mods
  File "/usr/lib/python2.7/site-packages/salt/template.py", line 94, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/usr/lib/python2.7/site-packages/salt/renderers/yaml.py", line 51, in render
    data = load(yaml_data, Loader=get_yaml_loader(argline))
  File "/usr/lib64/python2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/lib64/python2.7/site-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/usr/lib64/python2.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib64/python2.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib64/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib64/python2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib64/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib64/python2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib64/python2.7/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/usr/lib64/python2.7/site-packages/yaml/composer.py", line 110, in compose_sequence_node
    while not self.check_event(SequenceEndEvent):
  File "/usr/lib64/python2.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib64/python2.7/site-packages/yaml/parser.py", line 393, in parse_block_sequence_entry
    "expected <block end>, but found %r" % token.id, token.start_mark)
ParserError: while parsing a block collection
  in "<unicode string>", line 12, column 4:
       - enable: True
       ^
expected <block end>, but found '<block sequence start>'
  in "<unicode string>", line 13, column 5:
        - watch:
        ^
```

My state looks like this:

```
# Install the package required for SNMP if not already installed
snmp_packages:
  pkg.installed:
    - pkgs:
      - net-snmp-utils
      - net-snmp

# Ensure the service 'snmpd' is running and enabled on start-up
# Restart the service if the snmpd.conf file is updated
snmpd:
  service.running:
   - enable: True
    - watch:
      - file: /etc/snmp/snmpd.conf
    - require:
      - pkg: snmp_packages

# Give the minion the 'snmpd.conf' file
/etc/snmp/snmpd.conf:
  file.managed
    {% if grains['office'] == 'Draper' %}
    - source: salt://configure-SNMP/snmpd.conf-draper
    {% elif grains['office'] == 'Ireland' %}
    - source: salt://configure-SNMP/snmpd.conf-ireland
    {% endif %}
    - require:
      - pkg: snmp_packages
```

**Comment by unassassinable** [comment]
I found 2 syntax problems:

1) my indentation under the snmpd: was incorrect.  I changed it to:
```
snmpd:
  service.running:
   - enable: True
   - watch:
     - file: /etc/snmp/snmpd.conf
   - require:
      - pkg: snmp_packages
```

2: I forgot a : on the file.managed near the bottom.
