### ISSUE TITLE
file.managed can't retrieve file via ftp

### ISSUE THREAD

**Issue by llevar** [saltstack/salt#27534]
On version 2015.8.0

state:

```
file.managed:
    - source: ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/phase3/data//NA12878/alignment/NA12878.chrom11.ILLUMINA.bwa.CEU.low_coverage.20121211.bam
    - source_hash: md5=98d2ef57d792c5e752f569e6adc44263
    - user: root
    - group: root
    - mode: 644 
```

Output:

```
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] file_roots is /srv/salt
[DEBUG   ] file_roots is /srv/spm/salt
[DEBUG   ] Requesting URL ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/phase3/data//NA12874/alignment/NA12874.chrom20.ILLUMINA.bwa.CEU.low_coverage.20130415.bam using GET method
[DEBUG   ] Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/states/file.py", line 1560, in managed
    follow_symlinks)
  File "/usr/lib/python2.7/site-packages/salt/modules/file.py", line 4133, in manage_file
    sfn = __salt__['cp.cache_file'](source, saltenv)
  File "/usr/lib/python2.7/site-packages/salt/modules/cp.py", line 365, in cache_file
    result = __context__['cp.fileclient'].cache_file(path, saltenv)
  File "/usr/lib/python2.7/site-packages/salt/fileclient.py", line 155, in cache_file
    return self.get_url(path, '', True, saltenv)
  File "/usr/lib/python2.7/site-packages/salt/fileclient.py", line 618, in get_url
    **get_kwargs
  File "/usr/lib/python2.7/site-packages/salt/utils/http.py", line 424, in query
    **req_kwargs
  File "/usr/lib64/python2.7/site-packages/tornado/httpclient.py", line 102, in fetch
    self._async_client.fetch, request, **kwargs))
  File "/usr/lib64/python2.7/site-packages/tornado/ioloop.py", line 444, in run_sync
    return future_cell[0].result()
  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
ValueError: Unsupported url scheme: ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/phase3/data//NA12874/alignment/NA12874.chrom20.ILLUMINA.bwa.CEU.low_coverage.20130415.bam

[ERROR   ] Unable to manage file: Unsupported url scheme: ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/phase3/data//NA12874/alignment/NA12874.chrom20.ILLUMINA.bwa.CEU.low_coverage.20130415.bam
```

I can easily get these file using wget from the same host.

**Comment by llevar** [comment]
Looking at the source of https://github.com/saltstack/salt/blob/develop/salt/fileclient.py I don't see any mention or handling of FTP protocol but the docs clearly state that FTP is supported:

https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.managed

**Comment by jfindlay** [comment]
@llevar, thanks for the report.

**Comment by cachedout** [comment]
Looks like this broke when we switched the fileclient over to requests: https://github.com/saltstack/salt/pull/11708

**Comment by cachedout** [comment]
OK, give #28047 a try. That should fix it.
