### ISSUE TITLE
Salt-api starts accepts queries and crash / restart

### ISSUE THREAD

**Issue by jeanpralo** [saltstack/salt#27580]
Hi there,

Here is the version I am currently using in production:

> salt-master --version
salt-master 2015.5.3 (Lithium)
> salt-api --version
salt-api 2015.5.3

For some reasons since a couple of days I have problems with salt-api. I have run it in debug to see what is happening. Basically I start the server it starts accepting queries and then in the middle of nowhere this message appears then the server is restarted. Sometimes it manages to rebind the port, sometimes not ( maybe because badly killed and and SO_REUSE a bit high).

Anyway here is the stackstrace:

2015-09-30 21:10:41,185 [cherrypy.error   ][ERROR   ][11304] [30/Sep/2015:21:10:41] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0x7f6836122490>>
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cherrypy/process/wspbus.py", line 197, in publish
    output.append(listener(*args, **kwargs))
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cpserver.py", line 151, in start
    ServerAdapter.start(self)
  File "/usr/lib/python2.7/dist-packages/cherrypy/process/servers.py", line 174, in start
    self.wait()
  File "/usr/lib/python2.7/dist-packages/cherrypy/process/servers.py", line 214, in wait
    wait_for_occupied_port(host, port)
  File "/usr/lib/python2.7/dist-packages/cherrypy/process/servers.py", line 427, in wait_for_occupied_port
    raise IOError("Port %r not bound on %r" % (port, host))
IOError: Port 8000 not bound on 'X.X.X.X'

2015-09-30 21:10:41,185 [cherrypy.error   ][ERROR   ][11304] [30/Sep/2015:21:10:41] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cherrypy/process/wspbus.py", line 235, in start
    self.publish('start')
  File "/usr/lib/python2.7/dist-packages/cherrypy/process/wspbus.py", line 215, in publish
    raise exc
ChannelFailures: IOError("Port 8000 not bound on 'X.X.X.X'",)

2015-09-30 21:10:41,186 [cherrypy.error   ][INFO    ][11304] [30/Sep/2015:21:10:41] ENGINE Bus STOPPING
2015-09-30 21:10:41,186 [cherrypy.error   ][INFO    ][11304] [30/Sep/2015:21:10:41] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('X.X.X.X', 8000)) already shut down
2015-09-30 21:10:41,187 [cherrypy.error   ][INFO    ][11304] [30/Sep/2015:21:10:41] ENGINE Stopped thread '_TimeoutMonitor'.
2015-09-30 21:10:41,188 [cherrypy.error   ][INFO    ][11304] [30/Sep/2015:21:10:41] ENGINE Stopped thread 'Session cleanup'.
2015-09-30 21:10:41,189 [cherrypy.error   ][INFO    ][11304] [30/Sep/2015:21:10:41] ENGINE Bus STOPPED
2015-09-30 21:10:41,189 [cherrypy.error   ][INFO    ][11304] [30/Sep/2015:21:10:41] ENGINE Bus EXITING
2015-09-30 21:10:41,189 [cherrypy.error   ][INFO    ][11304] [30/Sep/2015:21:10:41] ENGINE Bus EXITED
2015-09-30 21:10:41,201 [salt.utils.process][INFO    ][11299] Process <function start at 0x7f683611c488> (11304) died with exit status None, restarting...
2015-09-30 21:10:42,220 [salt.utils.process][DEBUG   ][11299] Started 'start' with pid 11412
2015-09-30 21:10:42,231 [salt.utils.event ][DEBUG   ][11412] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
2015-09-30 21:10:42,232 [salt.utils.event ][DEBUG   ][11412] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
2015-09-30 21:10:42,233 [salt.utils.event ][DEBUG   ][11412] Sending event - data = {'_stamp': '2015-09-30T21:10:42.233011'}
2015-09-30 21:10:42,248 [cherrypy.error   ][INFO    ][11412] [30/Sep/2015:21:10:42] ENGINE Listening for SIGHUP.
2015-09-30 21:10:42,248 [cherrypy.error   ][INFO    ][11412] [30/Sep/2015:21:10:42] ENGINE Listening for SIGTERM.
2015-09-30 21:10:42,248 [cherrypy.error   ][INFO    ][11412] [30/Sep/2015:21:10:42] ENGINE Listening for SIGUSR1.
2015-09-30 21:10:42,248 [cherrypy.error   ][INFO    ][11412] [30/Sep/2015:21:10:42] ENGINE Bus STARTING
2015-09-30 21:10:42,249 [cherrypy.error   ][INFO    ][11412] [30/Sep/2015:21:10:42] ENGINE Started monitor thread '_TimeoutMonitor'.
2015-09-30 21:10:42,816 [cherrypy.error   ][INFO    ][11412] [30/Sep/2015:21:10:42] ENGINE Started monitor thread 'Session cleanup'.

**Comment by whiteinge** [comment]
* What version of CherryPy?
* What are your `rest_cherrypy` settings?
* How are you starting / stopping salt-api? Manually? System init scripts?
* What OS?

**Comment by jeanpralo** [comment]
Well I think I found what the problem is.

My server is firewalled and was not able to talk to himself on the salt api port, there must be some sort of checks ( either cherrypy or salt-api ), so it considered that the process was not doing his job properly and was restarting the process.

**Comment by whiteinge** [comment]
Glad you found it. Thanks for updating the issue.

Changing the `host` setting may be useful if you want it to only listen on localhost.
