### ISSUE TITLE
NameError: global name '__pillar__' is not defined in _modules/syncthing.py

### ISSUE THREAD

**Issue by ahammond** [saltstack/salt#27615]
```
[root@hss62 syncthing]# salt-call -l debug syncthing.data
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Including configuration from '/etc/salt/minion.d/id.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/id.conf
[DEBUG   ] Including configuration from '/etc/salt/minion.d/master.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/master.conf
[DEBUG   ] Configuration file path: /etc/salt/minion
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Including configuration from '/etc/salt/minion.d/id.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/id.conf
[DEBUG   ] Including configuration from '/etc/salt/minion.d/master.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/master.conf
[DEBUG   ] Failed to import grains syncthing:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/loader.py", line 1108, in _load_module
    ), fn_, fpath, desc)
  File "/var/cache/salt/minion/extmods/grains/syncthing.py", line 3, in <module>
    import salt.modules.syncthing
ImportError: No module named syncthing
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'hss62', 'tcp://192.168.33.2:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (9041)
[DEBUG   ] Setting zmq_reconnect_ivl to '9041ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'hss62', 'tcp://192.168.33.2:4506', 'aes')
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'hss62', 'tcp://192.168.33.2:4506')
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'hss62', 'tcp://192.168.33.2:4506', 'clear')
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] Fetching Syncthing API key from pillar
[ERROR   ] Failed to import module syncthing, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/loader.py", line 1108, in _load_module
    ), fn_, fpath, desc)
  File "/var/cache/salt/minion/extmods/modules/syncthing.py", line 48, in <module>
    @salt.utils.decorators.depends(syncthing_api_works())
  File "/var/cache/salt/minion/extmods/modules/syncthing.py", line 46, in syncthing_api_works
    return 'ping' in _get_syncthing_api('system/ping')
  File "/var/cache/salt/minion/extmods/modules/syncthing.py", line 18, in _get_syncthing_api
    pillar_data = __pillar__.get('syncthing', {}).get('lookup', {})
NameError: global name '__pillar__' is not defined
[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Error loading module.victorops: No VictorOps api key found.
[DEBUG   ] Error loading module.ipmi: No module named pyghmi.ipmi
[DEBUG   ] Error loading module.ifttt: IFTTT Secret Key Unavailable, not loading.
[DEBUG   ] Error loading module.npm: npm execution module could not be loaded because the npm binary could not be located
[DEBUG   ] Error loading module.tls: ['PyOpenSSL version 0.10 or later must be installed before this module can be used.']
[DEBUG   ] SMBIOS: neither dmidecode nor smbios found!
[DEBUG   ] Could not LazyLoad syncthing.data
'syncthing.data' is not available.

[root@hss62 syncthing]# salt-call test.versions_report
local:
    Salt Version:
               Salt: 2015.8.0
     
    Dependency Versions:
             Jinja2: 2.2.1
           M2Crypto: 0.20.2
               Mako: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.3.1
             Python: 2.6.6 (r266:84292, Dec  7 2011, 20:48:22)
               RAET: 0.6.3
            Tornado: 4.2.1
                ZMQ: 4.0.4
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: 1.3.2
            libnacl: 1.4.3
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: Not Installed
            timelib: Not Installed
     
    System Versions:
               dist: centos 6.2 Final
            machine: x86_64
            release: 2.6.32-220.el6.x86_64
             system: CentOS 6.2 Final
```

Code: _modules/syncthing.py
```python
#!/usr/bin/env python

from __future__ import absolute_import
import simplejson
import logging
import requests
import salt.utils.decorators

__opts__ = {}

DEFAULT_API_PORT = '8080'

s = requests.Session()

def _get_syncthing_api(endpoint):
    log = logging.getLogger(__name__)
    log.debug('Fetching Syncthing API key from pillar')
    pillar_data = __pillar__.get('syncthing', {}).get('lookup', {})
    if not 'apikey' in pillar_data:
        log.error("__pillar__['syncthing']['lookup'] missing apikey entry: %r", pillar_data)
        return {}
    uri = 'http://localhost:' + pillar_data.get('port', DEFAULT_API_PORT) + '/rest/' + endpoint
    log.debug('Checking Syncthing API with get %s', uri)
    try:
        r = s.get(uri, headers={'X-API-Key': pillar_data['api_key']})
    except requests.exceptions.RequestException, e:
        log.warn('Syncthing grain depends on the syncthing api. However, we failed to get %s: %r', uri, e)
        return {}
    if 200 != r.status_code:
        log.warn('Syncthing grain depends on the syncthing api. However, we got %d when going to %s: %r', r.status_code, uri, r)
        return {}
    try:
        log.debug('Decoding result')
        res = r.json()
    except simplejson.JSONDecodeError, e:
        log.error('Failed to decode %s: %r', r.text, e)
        return {}
    return res

def syncthing_api_works():
    '''
    Test to see if the syncthing api is working.
    '''

    log = logging.getLogger(__name__)
    return 'ping' in _get_syncthing_api('system/ping')

@salt.utils.decorators.depends(syncthing_api_works())
def data():
    '''
    Gather data about the local syncthing instance, if any.

    :maintainer:    Andrew Hammond <ahammond@anchorfree.com>
    :maturity:      new
    :depends:       python-urllib2
    :platform:      all
    '''

    log = logging.getLogger(__name__)
    stdata = {}

    for path, json_key in {'system/status': 'myID', 'system/version': 'version'}.iteritems():
        got = _get_syncthing_api(path)
        try:
            stdata[json_key] = got[json_key]
        except KeyError, e:
            log.error('Fetched from %s, got %r, missing key %r', path, got, json_key)
            return {}
    return {'syncthing': stdata}
```

_grains/syncthing.py
```python
#!/usr/bin/env python

import salt.modules.syncthing

__salt__ = {
    'syncthing.data': salt.modules.syncthing.data
}

def syncthing_data():
    return __salt__['syncthing.data']()
```

**Comment by ahammond** [comment]
I'm guessing that I must be doing something wrong here. Probably an order-of-operations kind of thing. However, I need the apikey (from the pillar) to hit the rest api to populate the grain. So... uh... help?

**Comment by basepi** [comment]
The special `__variables__` are added to function via the loader. Directly importing in the way you've done means that none of the `__variables__` (including `__grains__`, `__opts__`, `__pillar__`, etc) will not be available.

Unfortunately, we can't load module before we load grains, because modules are so reliant on grains to decide whether to load. The only `__salt__` function available for grains is `cmd.run`.

**Comment by ahammond** [comment]
Hmm, I'll have to take a different approach.
