### ISSUE TITLE
verify_ssl: False not being recognized

### ISSUE THREAD

**Issue by kevincullinane** [saltstack/salt#27638]
I have `verify_ssl: False` in my cloud.providers file under /etc/salt/, but I continusously get 
```SSLError: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed```

I saw the bug originally reporting this from this summer, but I can't get it to connect

Versions Report:
```yaml
 Salt: 2015.5.3
                Python: 2.7.3 (default, Jun 22 2015, 19:33:41)
                Jinja2: 2.8
              M2Crypto: 0.21.1
        msgpack-python: 0.1.10
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 13.0.0
                  RAET: Not Installed
                   ZMQ: 3.2.2
                  Mako: Not Installed
               Tornado: Not Installed
       Apache Libcloud: 0.14.1
 Debian source package: 2015.5.3+ds-1precise2
```

Cloud Providers: 
```salt
proxmox:
  provider: proxmox
  user: root@pam
  password: secret
  verify_ssl: False
  url: devprox01.company.tld
  driver: proxmox
```

Error:
```python-traceback
[DEBUG   ] Reading configuration from /etc/salt/cloud
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: precisesource
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers
[DEBUG   ] Missing configuration file: /etc/salt/cloud.profiles
[DEBUG   ] Configuration file path: /etc/salt/cloud
[INFO    ] salt-cloud starting
[DEBUG   ] Could not LazyLoad parallels.avail_sizes
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] Could not LazyLoad proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy
[DEBUG   ] Could not LazyLoad saltify.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.avail_images
[DEBUG   ] Could not LazyLoad saltify.avail_locations
[DEBUG   ] LazyLoaded rackspace.reboot
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] LazyLoaded rackspace.list_locations
[DEBUG   ] Not authenticated yet, doing that now..
[INFO    ] Starting new HTTPS connection (1): devprox01.compnay.tld
[ERROR   ] Failed to get the output of 'proxmox.avail_images()': [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 841, in image_list
    data[alias][driver] = self.clouds[fun]()
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/proxmox.py", line 386, in avail_images
    for host_name, host_details in avail_locations().items():
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/proxmox.py", line 359, in avail_locations
    nodes = query('get', 'nodes')
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/proxmox.py", line 124, in query
    _authenticate()
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/proxmox.py", line 112, in _authenticate
    full_url, verify=True, data=connect_data).json()
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 88, in post
    return request('post', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 357, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 460, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 358, in send
    raise SSLError(e)
SSLError: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
[DEBUG   ] LazyLoaded nested.output
```

**Comment by jfindlay** [comment]
@kevincullinane, thanks for the report.

**Comment by pass-by-value** [comment]
Hi @kevincullinane I was able to create a VM with `verify_ssl: False`. Could you give this another try? One thing I noticed in your proxmox provider is that you have `driver: proxmox`. Since you are on 2015.5 that [needs to be](https://docs.saltstack.com/en/2015.5/topics/cloud/proxmox.html) changed to `provider: proxmox`.

fyi: You'd use `driver: proxmox` on `2015.8` (that was recently changed)

**Comment by chojayr** [comment]
Tested it on 2015.8 and it works perfectly

**Comment by pass-by-value** [comment]
Thanks for testing this @chojayr 

I'm gonna close this for now as it seems to be working.
