### ISSUE TITLE
postgres_local_cache handling of success

### ISSUE THREAD

**Issue by gracinet** [saltstack/salt#27655]
There's an inconsistency in `salt.returners.postgres_local_cache`.
The schema suggested in the documentation says that `success` is a non-required boolean:

```
    CREATE TABLE salt_returns (
      added     TIMESTAMP WITH TIME ZONE DEFAULT now(),
      fun       text NOT NULL,
      jid       varchar(20) NOT NULL,
      return    text NOT NULL,
      id        text NOT NULL,
      success   boolean
    );
```

but `returner()` does otherwise:

```
    # salt guarantees that there will be 'fun', 'jid', 'return' and 'id' but not
    # 'success'
    success = 'Unknown'
    if 'success' in load:
        success = load['success']
```

`None` would be the appropriate value to give `psycopg2`

**Comment by gracinet** [comment]
Forgot to mention that this produces a systematic error in ``salt-run jobs.list_jobs`` (on 2015.5 at least): 

```
Traceback (most recent call last):
  File "/usr/bin/salt-run", line 10, in <module>
    salt_run()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 250, in salt_run
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/run.py", line 54, in run
    runner.run()
  File "/usr/lib/python2.7/dist-packages/salt/runner.py", line 166, in run
    False)  # Don't daemonize
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 381, in _proc_function
    return self.low(fun, low)
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 336, in low
    mminion=self.mminion,
  File "/usr/lib/python2.7/dist-packages/salt/utils/job.py", line 81, in store_job
    mminion.returners[fstr](load)
  File "/usr/lib/python2.7/dist-packages/salt/returners/postgres_local_cache.py", line 222, in returner
    success
psycopg2.DataError: invalid input syntax for type boolean: "Unknown"
LINE 3: ....jobs.list_jobs''}"', 'salt_master', 'Unknown')
```
