### ISSUE TITLE
state.highstate with pillars fails

### ISSUE THREAD

**Issue by throwawayj** [saltstack/salt#27707]
command running from minion salt-call state.highstate
or 
command running from master salt '<minion>' state.highstate

this error seems to be related to pillar data rendering or something of that nature

salt-minion version = salt-minion-2015.5.5-1.
salt-master version = salt-master-2015.5.3-3 or salt-master-2015.5.5

[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'module' object has no attribute 'exceptions'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 227, in salt_call
    client.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/call.py", line 69, in run
    caller.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/caller.py", line 236, in run
    ret = self.call()
  File "/usr/lib/python2.6/site-packages/salt/cli/caller.py", line 138, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/modules/state.py", line 538, in highstate
    whitelist=kwargs.get('whitelist')
  File "/usr/lib/python2.6/site-packages/salt/state.py", line 2977, in call_highstate
    self.serial.dump(high, fp_)
  File "/usr/lib/python2.6/site-packages/salt/payload.py", line 174, in dump
    fn_.write(self.dumps(msg))
  File "/usr/lib/python2.6/site-packages/salt/payload.py", line 122, in dumps
    except (OverflowError, msgpack.exceptions.PackValueError):
AttributeError: 'module' object has no attribute 'exceptions'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 227, in salt_call
    client.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/call.py", line 69, in run
    caller.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/caller.py", line 236, in run
    ret = self.call()
  File "/usr/lib/python2.6/site-packages/salt/cli/caller.py", line 138, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/modules/state.py", line 538, in highstate
    whitelist=kwargs.get('whitelist')
  File "/usr/lib/python2.6/site-packages/salt/state.py", line 2977, in call_highstate
    self.serial.dump(high, fp_)
  File "/usr/lib/python2.6/site-packages/salt/payload.py", line 174, in dump
    fn_.write(self.dumps(msg))
  File "/usr/lib/python2.6/site-packages/salt/payload.py", line 122, in dumps
    except (OverflowError, msgpack.exceptions.PackValueError):
AttributeError: 'module' object has no attribute 'exceptions'

**Comment by tbaker57** [comment]
This looks like a duplicate of #26705 (which says the fix should be in 2015.5.6 when it comes out, and 2015.8.0 which is already out).

cheers,
Tim

**Comment by throwawayj** [comment]
i found the solution that worked here https://github.com/saltstack/salt/issues/26600. The user who resolved it stated: 
      I updated python-msgpack manually on my system to fix this. I think you need a versioned dep in the rpm in epel6 for python-msgpack 0.4.6-1.el6.

The package python-msgpack doesn't seem to upgrade with the salt-minion and master upgrades. Once i updated the python-msgpack to python-msgpack-0.4.6-1 everything worked again. this is with salt-minion version = salt-minion-2015.5.5-1 and  salt-master-2015.5.5-1

even using 2015.8.0 (salt-master) it still failed. I haven't tested updating the python-msgpack on my 2015.8.0 master

I hope this can help anyone else. I couldn't wait til 2015.5.6

**Comment by throwawayj** [comment]
I can close this issue now. Hope this is fixed completely in 2015.5.6
