### ISSUE TITLE
saltutil.sync_all can't sync with the minion

### ISSUE THREAD

**Issue by eduherraiz** [saltstack/salt#27712]
Yesterday we found a problem in salt-bootstrap regarding the new installation script. #27670
The only way we found to initiate a instance with salt-cloud was configure the provider with:
```
  script_args: -P git 2015.8.0
```
But today, we found can't sync_all in this salt-minion:
```
salt -v server saltutil.sync_all
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1004, in _thread_return
        return_data = func(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/saltutil.py", line 478, in sync_all
        ret['beacons'] = sync_beacons(saltenv, False)
      File "/usr/lib/python2.7/dist-packages/salt/modules/saltutil.py", line 265, in sync_beacons
        ret = _sync('beacons', saltenv)
      File "/usr/lib/python2.7/dist-packages/salt/modules/saltutil.py", line 111, in _sync
        source, sub_env, include_pat=r'E@\.(pyx?|so|zip)$'
      File "/usr/lib/python2.7/dist-packages/salt/modules/cp.py", line 444, in cache_dir
        path, saltenv, include_empty, include_pat, exclude_pat
      File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 230, in cache_dir
        if fn_.strip() and fn_.startswith(path):
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 48: ordinal not in range(128)
```
I tried to downgrade the version in the minion to 2015.5.5 and sync_all properly.

Now, it's hard to me say how to configure the script_args in the provider to install the real "stable" version 2015.5.5, failed doing a:
``` 
script_args: -P git 2015.5.5
```

Versions report:
```
salt --versions-report
Salt Version:
           Salt: 2015.8.0

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.22
           Mako: 0.9.1
         PyYAML: 3.11
          PyZMQ: 14.4.1
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
           RAET: 0.6.3
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.2
       cherrypy: 3.6.0
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: Not Installed
          ioflo: 1.3.9
        libnacl: 1.4.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-46-generic
         system: Ubuntu 14.04 trusty
```

**Comment by jfindlay** [comment]
@eduherraiz, thanks for the report.

**Comment by cachedout** [comment]
This is easily reproduceable for cases wherein a file or directory in the source path has non-ASCII characters.

**Comment by cachedout** [comment]
OK, #27977 fixes this in my testing. @eduherraiz please give it a shot. Thanks.

**Comment by eduherraiz** [comment]
@cachedout thank you!

**Comment by eliasp** [comment]
In case anyone else runs into this issue, this is how I fixed this for my Win Minions:
```
salt -C 'G@os:Windows' cmd.run 'copy c:\salt\bin\lib\site-packages\salt\fileclient.py c:\salt\bin\lib\site-packages\salt\fileclient.py.orig'
salt -C 'G@os:Windows' cp.get_url 'https://raw.githubusercontent.com/saltstack/salt/2015.8/salt/fileclient.py' 'c:\salt\bin\lib\site-packages\salt\fileclient.py'
salt -C 'G@os:Windows' saltutil.sync_all
```
