### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte in 2015.8.0

### ISSUE THREAD

**Issue by eduherraiz** [saltstack/salt#27789]
After upgrade to 2015.8.0 we detect a lot of errors in state.sls or highstate executions like:
```
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1560, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 2317, in recurse
                  src = u'salt://{0}'.format(fn_)
              UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 48: ordinal not in range(128)
```

We found it in a file.managed state or pip.
Could we solve the problem configuring the master in any way?

Master versions
```
Salt Version:
           Salt: 2015.8.0

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.22
           Mako: 0.9.1
         PyYAML: 3.11
          PyZMQ: 14.4.1
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
           RAET: 0.6.3
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.2
       cherrypy: 3.6.0
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: Not Installed
          ioflo: 1.3.9
        libnacl: 1.4.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-46-generic
         system: Ubuntu 14.04 trusty
```

Minion versions
```
                  Salt: 2015.5.3
                Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.4.6
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1trusty1
```

**Comment by eduherraiz** [comment]
Doing a highstate with Master: 2015.8.0 and minion 2015.8.0 returns a:
```
# salt -v server state.highstate
Executing job with jid 20151008115749355152
-------------------------------------------

server:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1004, in _thread_return
        return_data = func(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 540, in highstate
        whitelist=kwargs.get('whitelist')
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 3069, in call_highstate
        self.load_dynamic(matches)
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2601, in load_dynamic
        refresh=False)
      File "/usr/lib/python2.7/dist-packages/salt/modules/saltutil.py", line 478, in sync_all
        ret['beacons'] = sync_beacons(saltenv, False)
      File "/usr/lib/python2.7/dist-packages/salt/modules/saltutil.py", line 265, in sync_beacons
        ret = _sync('beacons', saltenv)
      File "/usr/lib/python2.7/dist-packages/salt/modules/saltutil.py", line 111, in _sync
        source, sub_env, include_pat=r'E@\.(pyx?|so|zip)$'
      File "/usr/lib/python2.7/dist-packages/salt/modules/cp.py", line 444, in cache_dir
        path, saltenv, include_empty, include_pat, exclude_pat
      File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 230, in cache_dir
        if fn_.strip() and fn_.startswith(path):
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 48: ordinal not in range(128)
```

**Comment by jfindlay** [comment]
@eduherraiz, thanks for the report.  The first error applies to 2015.5, and I have submitted a fix for the second.  They happen when string operations happen on strings containing bytes python does not know how to handle.  The solution is to use `salt.utils.locales.sdecode` to decode the string to utf-8.

**Comment by eduherraiz** [comment]
@jfindlay Thank you!

**Comment by bercab** [comment]
Hello @jfindlay, this patch does not solve our issue, so we have looked a bit deeper. 

The decoding problem did not come from *path* variable, but from *fn_*, from *self.file_list*:
```
for fn_ in self.file_list(saltenv):
     if fn_.strip() and fn_.startswith(path):
     [...]
```
We had a filename in this list with an utf-8 char on our /srv/salt/ (a template file), and this was raising the decode exception (not path variable).

So maybe fn_ should be decoded with utf8 before fn_.startswith()

**Comment by jfindlay** [comment]
@bercab, thanks for the further testing.  The new change should fix your situation.

**Comment by cachedout** [comment]
Looks like this has been resolved with #28340 so I'm going to go ahead and close it. If there is additional work to be done, please feel free to leave a comment here and we will be happy to re-open it.

**Comment by jfoboss** [comment]
Hi! We've got exact issue in 2017.7.2!

```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 87: ordinal not in range(128)
2017-11-23 10:09:29,078 [salt.master      ][ERROR   ][9700] Error in function _file_list:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 1629, in run_func
    ret = getattr(self, func)(load)
  File "/usr/lib/python2.7/site-packages/salt/fileserver/__init__.py", line 756, in file_list
    ret.update(self.servers[fstr](load))
  File "/usr/lib/python2.7/site-packages/salt/fileserver/roots.py", line 421, in file_list
    return _file_lists(load, 'files')
  File "/usr/lib/python2.7/site-packages/salt/fileserver/roots.py", line 397, in _file_lists
    _add_to(ret['files'], path, root, files)
```

**Comment by adcpdk** [comment]
Hi, I have got the same error message after trying to copy an archive file from master to the miniton's /tmp directory. 

Here is  how I made a content for the archive, I don't think it's related to the encoding in this case:
```
for i in {0..10}; do touch $i.txt; done
uptime > 0.txt
tar -czvf file.tar.gz *
```

**salt-cp "minion-id" file.tar.gz /tmp**

```
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8b in position 1: ordinal not in range(128)
Traceback (most recent call last):
  File "/bin/salt-cp", line 11, in <module>
    load_entry_point('salt==2018.3.3', 'console_scripts', 'salt-cp')()
  File "/usr/lib/python3.6/site-packages/salt/scripts.py", line 397, in salt_cp
    client.run()
  File "/usr/lib/python3.6/site-packages/salt/cli/cp.py", line 52, in run
    cp_.run()
  File "/usr/lib/python3.6/site-packages/salt/cli/cp.py", line 142, in run
    ret = self.run_oldstyle()
  File "/usr/lib/python3.6/site-packages/salt/cli/cp.py", line 153, in run_oldstyle
    arg = [self._load_files(), self.opts['dest']]
  File "/usr/lib/python3.6/site-packages/salt/cli/cp.py", line 126, in _load_files
    files.update(self._file_dict(fn_))
  File "/usr/lib/python3.6/site-packages/salt/cli/cp.py", line 115, in _file_dict
    data = fp_.read()
  File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8b in position 1: ordinal not in range(128)
Traceback (most recent call last):
  File "/bin/salt-cp", line 11, in <module>
    load_entry_point('salt==2018.3.3', 'console_scripts', 'salt-cp')()
  File "/usr/lib/python3.6/site-packages/salt/scripts.py", line 397, in salt_cp
    client.run()
  File "/usr/lib/python3.6/site-packages/salt/cli/cp.py", line 52, in run
    cp_.run()
  File "/usr/lib/python3.6/site-packages/salt/cli/cp.py", line 142, in run
    ret = self.run_oldstyle()
  File "/usr/lib/python3.6/site-packages/salt/cli/cp.py", line 153, in run_oldstyle
    arg = [self._load_files(), self.opts['dest']]
  File "/usr/lib/python3.6/site-packages/salt/cli/cp.py", line 126, in _load_files
    files.update(self._file_dict(fn_))
  File "/usr/lib/python3.6/site-packages/salt/cli/cp.py", line 115, in _file_dict
    data = fp_.read()
  File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8b in position 1: ordinal not in range(128)
```
