### ISSUE TITLE
IOError: [Errno 13] Permission denied: '/var/cache/salt/master/.dfn' when using python salt.wheel module

### ISSUE THREAD

**Issue by onsmribah** [saltstack/salt#27796]
Hi,

I am using salt.wheel python module to manage minion keys. But when it throws the error below when trying to delete a minion key. However, running salt-key -d <minion_id> works fine.
Am using an unprivileged user to run salt-master and i also changed the ownership of the following dirs : 
/var/cache/salt
/var/log/salt
 /etc/salt/pki

salt version : 
```
$ salt-master --versions-report
                  Salt: 2015.5.3
                Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                Jinja2: 2.8
              M2Crypto: 0.21.1
        msgpack-python: 0.4.6
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: Not Installed
               Tornado: 4.2.1
 Debian source package: 2015.5.3+ds-1trusty1
```
```
Exception occurred in wheel key.delete: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 317, in low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/wheel/key.py", line 57, in delete
    return skey.delete_key(match)
  File "/usr/lib/python2.7/dist-packages/salt/key.py", line 755, in delete_key
    salt.crypt.dropfile(self.opts['cachedir'], self.opts['user'])
  File "/usr/lib/python2.7/dist-packages/salt/crypt.py", line 50, in dropfile
    with salt.utils.fopen(dfn, 'w+') as fp_:
  File "/usr/lib/python2.7/dist-packages/salt/utils/__init__.py", line 1045, in fopen
    fhandle = open(*args, **kwargs)
IOError: [Errno 13] Permission denied: '/var/cache/salt/master/.dfn'
```

**Comment by jfindlay** [comment]
@onsmribah, thanks for the report.

**Comment by dmacvicar** [comment]
I am seeing the same

**Comment by dmacvicar** [comment]
This is what I see, it happens during an automated test where we delete the minion key to make sure it is unaccepted before accepting it again and  making sure the acceptance triggers other code we are testing.

```
Execute command failed yes | salt-key -d examplehost.suse.com: Traceback (most recent call last):
  File "/usr/bin/salt-key", line 10, in <module>
    salt_key()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 285, in salt_key
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/key.py", line 32, in run
    key.run()
  File "/usr/lib/python2.7/site-packages/salt/key.py", line 425, in run
    self.delete(self.opts['delete'])
  File "/usr/lib/python2.7/site-packages/salt/key.py", line 209, in delete
    self.key.delete_key(match_dict=matches)
  File "/usr/lib/python2.7/site-packages/salt/key.py", line 829, in delete_key
    salt.crypt.dropfile(self.opts['cachedir'], self.opts['user'])
  File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 59, in dropfile
    with salt.utils.fopen(dfn, 'wb+') as fp_:
  File "/usr/lib/python2.7/site-packages/salt/utils/__init__.py", line 1204, in fopen
    fhandle = open(*args, **kwargs)
IOError: [Errno 13] Permission denied: '/var/cache/salt/master/.dfn'
```

salt 2015.8.3
salt-master running as user salt (our package follows https://build.opensuse.org/package/show/systemsmanagement:saltstack/salt more or less)

Interestingly, I can reproduce it intermittently:

```
master:~ # echo yes | salt-key -d examplehost.suse.com
The following keys are going to be deleted:
Unaccepted Keys:
examplehost.suse.com
Proceed? [N/y] Traceback (most recent call last):
  File "/usr/bin/salt-key", line 10, in <module>
    salt_key()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 285, in salt_key
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/key.py", line 32, in run
    key.run()
  File "/usr/lib/python2.7/site-packages/salt/key.py", line 425, in run
    self.delete(self.opts['delete'])
  File "/usr/lib/python2.7/site-packages/salt/key.py", line 209, in delete
    self.key.delete_key(match_dict=matches)
  File "/usr/lib/python2.7/site-packages/salt/key.py", line 829, in delete_key
    salt.crypt.dropfile(self.opts['cachedir'], self.opts['user'])
  File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 59, in dropfile
    with salt.utils.fopen(dfn, 'wb+') as fp_:
  File "/usr/lib/python2.7/site-packages/salt/utils/__init__.py", line 1204, in fopen
    fhandle = open(*args, **kwargs)
IOError: [Errno 13] Permission denied: '/var/cache/salt/master/.dfn'
master:~ # echo yes | salt-key -d examplehost.suse.com
The key glob 'examplehost.suse.com' does not match any accepted, unaccepted or rejected keys.
master:~ # echo yes | salt-key -d examplehost.suse.com
The key glob 'examplehost.suse.com' does not match any accepted, unaccepted or rejected keys.
master:~ #
```

**Comment by dmacvicar** [comment]
If I run audit on it, looks like if I run `salt-key -y -d host` repeatedly, in some cases the `.dfn` files is created, but in other cases it was already there, the second case is the one that makes the subsequent salt-key call to fail.

```
type=SYSCALL msg=audit(1450274061.911:27): arch=c000003e syscall=2 success=yes exit=14 a0=2a586c0 a1=242 a2=1b6 a3=2a5c626 items=2 ppid=25203 pid=25791 auid=0 uid=489 gid=490 euid=489 suid=489 fsuid=489 egid=490 sgid=490 fsgid=490 tty=pts1 ses=185 comm="salt-key" exe="/usr/bin/python2.7" key="salt-bug"
type=CWD msg=audit(1450274061.911:27):  cwd="/root"
type=PATH msg=audit(1450274061.911:27): item=0 name="/var/cache/salt/master/" inode=3803021 dev=fe:01 mode=040750 ouid=489 ogid=490 rdev=00:00 nametype=PARENT
type=PATH msg=audit(1450274061.911:27): item=1 name="/var/cache/salt/master/.dfn" inode=3803208 dev=fe:01 mode=0100400 ouid=489 ogid=490 rdev=00:00 nametype=CREATE
type=SYSCALL msg=audit(1450274061.911:28): arch=c000003e syscall=92 success=yes exit=0 a0=2a586c0 a1=1e9 a2=ffffffff a3=7fffede77200 items=1 ppid=25203 pid=25791 auid=0 uid=489 gid=490 euid=489 suid=489 fsuid=489 egid=490 sgid=490 fsgid=490 tty=pts1 ses=185 comm="salt-key" exe="/usr/bin/python2.7" key="salt-bug"
type=CWD msg=audit(1450274061.911:28):  cwd="/root"
type=PATH msg=audit(1450274061.911:28): item=0 name="/var/cache/salt/master/.dfn" inode=3803208 dev=fe:01 mode=0100400 ouid=489 ogid=490 rdev=00:00 nametype=NORMAL
type=SYSCALL msg=audit(1450274064.143:29): arch=c000003e syscall=2 success=no exit=-13 a0=a858c0 a1=242 a2=1b6 a3=f571c6 items=3 ppid=25203 pid=25804 auid=0 uid=489 gid=490 euid=489 suid=489 fsuid=489 egid=490 sgid=490 fsgid=490 tty=pts1 ses=185 comm="salt-key" exe="/usr/bin/python2.7" key="salt-bug"
type=CWD msg=audit(1450274064.143:29):  cwd="/root"
type=PATH msg=audit(1450274064.143:29): item=0 name="/var/cache/salt/master/" inode=3803021 dev=fe:01 mode=040750 ouid=489 ogid=490 rdev=00:00 nametype=PARENT
type=PATH msg=audit(1450274064.143:29): item=1 name=(null) inode=3803208 dev=fe:01 mode=0100400 ouid=489 ogid=490 rdev=00:00 nametype=NORMAL
type=PATH msg=audit(1450274064.143:29): item=2 name=(null) inode=3803208 dev=fe:01 mode=0100400 ouid=489 ogid=490 rdev=00:00 nametype=NORMAL
```

**Comment by dmacvicar** [comment]
The file /var/cache/salt/master/.dfn is there when calling salt-key, it will fail. If you wit a bit, the file goes away and then salt-key works.

**Comment by dmacvicar** [comment]
I can reproduce this almost instantly now:

```console
git clone git@github.com:dmacvicar/salt-opensuse-playground.git
git checkout salty
vagrant up
vagrant ssh master
sudo -s
salt-key -R
salt-key -D
```

```console
Proceed? [N/y] y
Traceback (most recent call last):
  File "/usr/bin/salt-key", line 10, in <module>
    salt_key()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 285, in salt_key
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/key.py", line 32, in run
    key.run()
  File "/usr/lib/python2.7/site-packages/salt/key.py", line 427, in run
    self.delete_all()
  File "/usr/lib/python2.7/site-packages/salt/key.py", line 226, in delete_all
    self.delete('*')
  File "/usr/lib/python2.7/site-packages/salt/key.py", line 209, in delete
    self.key.delete_key(match_dict=matches)
  File "/usr/lib/python2.7/site-packages/salt/key.py", line 829, in delete_key
    salt.crypt.dropfile(self.opts['cachedir'], self.opts['user'])
  File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 59, in dropfile
    with salt.utils.fopen(dfn, 'wb+') as fp_:
  File "/usr/lib/python2.7/site-packages/salt/utils/__init__.py", line 1204, in fopen
    fhandle = open(*args, **kwargs)
IOError: [Errno 13] Permission denied: '/var/cache/salt/master/.dfn'
```

**Comment by dmacvicar** [comment]
So both reject_key and delete_key perform a request to rotate the key, which calls `dropfile()`.

Dropfile creates `/var/cache/salt/master/.dfn` with owner `salt` and permissions `400`.

It tries to create the file with salt.utils.fopen(dfn, 'wb+') so, if it exists it should truncate it, but logic clashes with the fact that we can't write the file if it already exists.

If you call `reject` when `delete` has executed before and the master has not yet processed the request ( `/var/cache/salt/master/.dfn`) still exists, then the second operation fails to truncate the existing file.

The creation of the file has a comment:

```python
# set a mask (to avoid a race condition on file creation) and store original.
mask = os.umask(191)
```

* What race condition is trying to prevent setting an umask that takes write permission out?
* If the file is being open with `wb+` what is the point on removing the write, the process would never be able to open/truncate it because of the permission being `400`?.

* If a second salt-key operation (remove/reject) and the previous one asked for AES key rotation by dropping `/var/cache/salt/master/.dfn` and the master has not yet picked the request (and delete the file), is is safe to just ignore it and do not request it again? In other words, is it safe to make dropfile() not do anything if `/var/cache/salt/master/.dfn` exists?

I could contribute a fix around these ideas, but I need some information about the intention of the design. @thatch45 ?

**Comment by jfindlay** [comment]
Excellent work.  Thanks, @dmacvicar.
