### ISSUE TITLE
Salt raet unexpected keyword argument tags_regex 

### ISSUE THREAD

**Issue by mihaivint** [saltstack/salt#27823]
When using salt with raet protocol i get an error on test.ping . Without raet everything is fine . 
```python-traceback
 salt '*' test.ping
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: get_event() got an unexpected keyword argument 'tags_regex'
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 349, in salt_main
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/salt.py", line 205, in run
    for full_ret in cmd_func(**kwargs):
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 599, in cmd_cli
    **kwargs):
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 1252, in get_cli_event_returns
    expect_minions=(verbose or show_timeout)
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 883, in get_iter_returns
    for raw in ret_iter:
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 819, in get_returns_no_block
    raw = self.event.get_event(wait=0.01, tag='salt/job/{0}'.format(jid), tags_regex=tags_regex, full=True)
TypeError: get_event() got an unexpected keyword argument 'tags_regex'
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 349, in salt_main
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/salt.py", line 205, in run
    for full_ret in cmd_func(**kwargs):
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 599, in cmd_cli
    **kwargs):
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 1252, in get_cli_event_returns
    expect_minions=(verbose or show_timeout)
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 883, in get_iter_returns
    for raw in ret_iter:
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 819, in get_returns_no_block
    raw = self.event.get_event(wait=0.01, tag='salt/job/{0}'.format(jid), tags_regex=tags_regex, full=True)
TypeError: get_event() got an unexpected keyword argument 'tags_regex'
```

Version:
```
 an unexpected keyword argument 'tags_regex'
[root@salt2015 rpmbuild]# salt-call --versions-report
           Salt: 2015.5.5
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.5
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: 1.4.0
         PyYAML: 3.10
          ioflo: 1.3.9
          PyZMQ: 14.3.1
           RAET: 0.6.3
            ZMQ: 4.0.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: 1.5

```

**Comment by jfindlay** [comment]
@mihaivint, thanks for the report.

**Comment by DmitryKuzmenko** [comment]
@mihaivint thank you for the report.

tags_regex was short-lived argument that is replaced with match_type now (since 2015.8.0). Raet was broken some time and came back in 2015.8.1. So the best way to use salt with raet now is to updated to 2015.8.1.

If you still want to try it on 2015.5.5, please try to add the following patch:
```
index 2ac3977..05277a3 100644
--- a/salt/utils/raetevent.py
+++ b/salt/utils/raetevent.py
@@ -145,7 +145,7 @@ class RAETEvent(object):
         '''
         return raw
 
-    def get_event(self, wait=5, tag='', full=False):
+    def get_event(self, wait=5, tag='', tags_regex=None, full=False):
         '''
         Get a single publication.
         IF no publication available THEN block for up to wait seconds
```

Please let me know about your decision/result.

**Comment by cachedout** [comment]
We haven't had any response here and we have a documented workaround, so I'm closing this issue for the time being.
