### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'decode' in 2015.8.0

### ISSUE THREAD

**Issue by SeverinLeonhardt** [saltstack/salt#27822]
Running `salt-call --local state.highstate test=True` produces a very verbose output, similar to #25368.

The following error is printed when using `-l debug` just before the output:

```
[DEBUG   ] Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/output/__init__.py", line 39, in try_printout
    return get_printout(out, opts)(data).rstrip()
  File "/usr/lib/python2.7/site-packages/salt/output/highstate.py", line 85, in output
    return _format_host(host, hostdata)[0]
  File "/usr/lib/python2.7/site-packages/salt/output/highstate.py", line 231, in _format_host
    ret['comment'] = ret['comment'].decode('utf-8')
AttributeError: 'dict' object has no attribute 'decode'
```

The offending comment is probably from this state:
```
opscenter_ui:
  firewalld.present:
    - name: OpsCenter UI
    - ports:
      - 8888/tcp
```

Which produces this verbose output:
```
                  firewalld_|-opscenter_ui_|-OpsCenter UI_|-present:
                      ----------
                      __run_num__:
                          61
                      changes:
                          ----------
                          icmp_blocks:
                          port_fwd:
                          ports:
                          services:
                      comment:
                          ----------
                          OpsCenter UI:
                              `OpsCenter UI` will be created
                          icmp_blocks:
                          port_fwd:
                          ports:
                              - 8888/tcp will be added
                          services:
                      duration:
                          464.09
                      name:
                          OpsCenter UI
                      result:
                          True
                      start_time:
                          13:45:50.714483
```

**Comment by SeverinLeonhardt** [comment]
Just noticed this has already been reported in  #27454.
