### ISSUE TITLE
Error executing gem.install (TypeError)

### ISSUE THREAD

**Issue by jagguli** [saltstack/salt#27896]
replicated on Archlinux

``` python-traceback
Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1591, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/states/gem.py", line 102, in installed
                  proxy=proxy):
                File "/usr/lib/python2.7/site-packages/salt/modules/gem.py", line 145, in install
                  runas=runas)
                File "/usr/lib/python2.7/site-packages/salt/modules/gem.py", line 72, in _gem
                  raise CommandExecutionError(ret['stderr'])
              CommandExecutionError: ERROR:  While executing gem ... (TypeError)
                  wrong argument type nil (expected Regexp)
```

``` yaml
:» salt acer cmd.run_all 'gem install haml'
acer:
    ----------
    pid:
        3825
    retcode:
        1
    stderr:
        ERROR:  While executing gem ... (TypeError)
            wrong argument type nil (expected Regexp)
    stdout:
```

``` yaml
:» salt acer cmd.run 'gem install haml'
acer:
    ERROR:  While executing gem ... (TypeError)
        wrong argument type nil (expected Regexp)
acer:
    ERROR:  While executing gem ... (TypeError)
        wrong argument type nil (expected Regexp)
ERROR: Minions returned with non-zero exit code
```

Looks like an environment problem?

**Comment by jfindlay** [comment]
@jagguli, thanks for the report.  What is the output of `salt --versions-report`?

**Comment by jagguli** [comment]
Salt Version:
           Salt: 2015.8.0

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.22
           Mako: 1.0.2
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.10 (default, Sep  7 2015, 13:51:49)
           RAET: 0.6.3
        Tornado: 4.2.1
            ZMQ: 4.1.3
           cffi: 1.2.1
       cherrypy: 3.6.0
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.3.9
        libnacl: 1.4.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist:
        machine: x86_64
        release: 4.1.8-1-lts

**Comment by torrancew** [comment]
Also seeing this on (Arch as well):

```
$ salt --versions-report
Salt Version:
           Salt: 2015.8.8
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.24.0
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 2.7.11 (default, Mar 31 2016, 06:18:34)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist:   
        machine: x86_64
        release: 4.5.1-1-ARCH
```

I know from past experience that Arch ships some rather opinionated RubyGem configurations, so attaching that as well:

```
$ cat /etc/gemrc 
# Read about the gemrc format at http://guides.rubygems.org/command-reference/#gem-environment

# --user-install is used to install to $HOME/.gem/ by default since we want to separate
#                pacman installed gems and gem installed gems
gem: --user-install
```

**Comment by torrancew** [comment]
**Update:** Disabling the above line in `/etc/gemrc` allows the `gem.install` function to work. Overriding via `/root/.gemrc` (`--no-user-install`) for root did **not** work.
