### ISSUE TITLE
Error enabling or disabling a beacon on a minion 

### ISSUE THREAD

**Issue by itsamenathan** [saltstack/salt#27949]
With the load beacon running as expected.  I have run ```salt 'id' beacons.disable_beacon load``` command and received the following error.  I've tried this with and without the ```enable``` keyword under the specific beacon. 

/etc/salt/minion.d/beacons.conf
```
beacons:                     
  load:                      
    - 1m:                    
      - 0.0                  
      - 2.0                  
    - 5m:                    
      - 0.0                  
      - 1.5                  
    - 15m:                   
      - 0.1                  
      - 1.0                  
    - enable: False          
```
ERROR:
```
[DEBUG   ] Sending event - data = {'_stamp': '2015-10-13T21:36:05.014116', 'name': 'load', 'func': 'disable_beacon'}
[DEBUG   ] Handling event 'manage_beacons\n\n\x83\xa6_stamp\xba2015-10-13T21:36:05.014116\xa4name\xa4load\xa4func\xaedisable_beacon'
[ERROR   ] Exception in callback <functools.partial object at 0x7fd72412c730>
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/ioloop.py", line 592, in _run_callback
    ret = callback()
  File "/usr/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/tornado/ioloop.py", line 598, in <lambda>
    self.add_future(ret, lambda f: f.result())
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 230, in wrapper
    yielded = next(result)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1468, in handle_event
    self.manage_beacons(package)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1376, in manage_beacons
    self.beacons.disable_beacon(name)
  File "/usr/lib/python2.7/dist-packages/salt/beacons/__init__.py", line 214, in disable_beacon
    self.opts['beacons'][name]['enabled'] = False
TypeError: list indices must be integers, not str
```
salt --versions-report
```
Salt Version:
           Salt: 2015.8.0
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: 1.0.0
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: 3.8.0
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: debian 8.2 
        machine: x86_64
        release: 4.2.2-1-ARCH
         system: debian 8.2 
```

**Comment by cachedout** [comment]
Fixed in #27992 (will require a change in your config after the patch is applied).
