### ISSUE TITLE
local minion to master fails to start with file_client: local

### ISSUE THREAD

**Issue by rterbush** [saltstack/salt#27964]
If you configure the minion that is running on master to attempt to use local filesystem for file_roots:, the minion will fail to start after trying for some period of time to authenticate.

```
[INFO    ] Sleeping random_reauth_delay of 5 seconds
DEBUG:salt.utils.parsers:SYSPATHS setup as: /etc/salt
[DEBUG   ] Reading configuration from /srv/etc/minion
[DEBUG   ] Including configuration from '/srv/etc/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /srv/etc/minion.d/_schedule.conf
[DEBUG   ] Configuration file path: /srv/etc/minion
[INFO    ] Setting up the Salt Minion "master-minion.staging.uswest2.lhn"
[DEBUG   ] Created pidfile: /var/run/salt-minion.pid
[DEBUG   ] Reading configuration from /srv/etc/minion
[DEBUG   ] Including configuration from '/srv/etc/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /srv/etc/minion.d/_schedule.conf
[INFO    ] The salt minion is starting up
[INFO    ] Minion is starting as user 'root'
[DEBUG   ] AsyncEventPublisher PUB socket URI: ipc:///var/run/salt/minion/minion_event_186c633cb3_pub.ipc
[DEBUG   ] AsyncEventPublisher PULL socket URI: ipc:///var/run/salt/minion/minion_event_186c633cb3_pull.ipc
[INFO    ] Starting pub socket on ipc:///var/run/salt/minion/minion_event_186c633cb3_pub.ipc
[INFO    ] Starting pull socket on ipc:///var/run/salt/minion/minion_event_186c633cb3_pull.ipc
[DEBUG   ] Minion 'master-minion trying to tune in
[DEBUG   ] sync_connect_master
[DEBUG   ] Initializing new SAuth for ('/srv/etc/pki/minion', 'master-minion', 'tcp://127.0.0.1:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (5956)
[DEBUG   ] Setting zmq_reconnect_ivl to '5956ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/srv/etc/pki/minion', 'master-minion', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] Error deleting fd from IOLoop
Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/tornado/ioloop.py", line 690, in remove_handler
    self._impl.unregister(fd)
  File "/usr/lib64/python2.6/site-packages/zmq/eventloop/ioloop.py", line 115, in unregister
    return self._poller.unregister(fd)
  File "/usr/lib64/python2.6/site-packages/zmq/sugar/poll.py", line 71, in unregister
    idx = self._map.pop(socket)
KeyError: None
[INFO    ] The salt minion is shut down
[ERROR   ] Minion failed to start:
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/salt/scripts.py", line 81, in minion_process
    minion.start()
  File "/usr/lib/python2.6/dist-packages/salt/cli/daemons.py", line 272, in start
    self.minion.tune_in()
  File "/usr/lib/python2.6/dist-packages/salt/minion.py", line 1596, in tune_in
    self.sync_connect_master()
  File "/usr/lib/python2.6/dist-packages/salt/minion.py", line 724, in sync_connect_master
    raise six.reraise(*future_exception)
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 810, in run
    yielded = self.gen.throw(*sys.exc_info())
  File "/usr/lib/python2.6/dist-packages/salt/minion.py", line 731, in connect_master
    master, self.pub_channel = yield self.eval_master(self.opts, self.timeout, self.safe)
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 807, in run
    value = future.result()
  File "/usr/lib64/python2.6/site-packages/tornado/concurrent.py", line 208, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 810, in run
    yielded = self.gen.throw(*sys.exc_info())
  File "/usr/lib/python2.6/dist-packages/salt/minion.py", line 495, in eval_master
    yield pub_channel.connect()
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 807, in run
    value = future.result()
  File "/usr/lib64/python2.6/site-packages/tornado/concurrent.py", line 208, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 810, in run
    yielded = self.gen.throw(*sys.exc_info())
  File "/usr/lib/python2.6/dist-packages/salt/transport/zeromq.py", line 324, in connect
    yield self.auth.authenticate()
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 807, in run
    value = future.result()
  File "/usr/lib64/python2.6/site-packages/tornado/concurrent.py", line 208, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
SaltClientError: Attempt to authenticate with the salt master failed
[WARNING ] ** Restarting minion **
```

version info:
```
[root@manage etc]# salt --versions
Salt Version:
           Salt: 2015.8.0

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
         Python: 2.6.9 (unknown, Apr  1 2015, 18:16:00)
           RAET: Not Installed
        Tornado: 4.1
            ZMQ: 3.2.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist:
        machine: x86_64
        release: 3.14.48-33.39.amzn1.x86_64
```

**Comment by cachedout** [comment]
@rterbush Did you by chance mean `file_client`? If not, could you please clarify a little bit more about your setup, including the configuration in question.

**Comment by rterbush** [comment]
@jfindlay file_client: local in the subject of this issue.

Here is the section from the minion config I am looking at:
```
#####     File Directory Settings    #####
##########################################
# The Salt Minion can redirect all file server operations to a local directory,
# this allows for the same state tree that is on the master to be used if
# copied completely onto the minion. This is a literal copy of the settings on
# the master but used to reference a local directory on the minion.

# Set the file client. The client defaults to looking on the master server for
# files, but can be directed to look at the local file directory setting
# defined below by setting it to local.
#file_client: local

# The file directory works on environments passed to the minion, each environment
# can have multiple root directories, the subdirectories in the multiple file
# roots cannot match, otherwise the downloaded files will not be able to be
# reliably ensured. A base environment is required to house the top file.
# Example:
# file_roots:
#   base:
#     - /srv/salt/
#   dev:
#     - /srv/salt/dev/services
#     - /srv/salt/dev/states
#   prod:
#     - /srv/salt/prod/services
#     - /srv/salt/prod/states
#
# file_roots:
#   base:
#     - /srv/salt
```

If I set the following, the minion fails to start as described:
```
file_client: local

file_roots:
  base:
    - /srv/salt/
```

**Comment by cachedout** [comment]
Ah, I see. You mention `file_roots` in the body but I didn't notice the subject. Thanks. We'll take a look.

**Comment by cachedout** [comment]
I cannot seem to replicate this at all. I presume that you can successfully connect to a master without `file_client: local` being set?

**Comment by rterbush** [comment]
@cachedout It is not so much that I cannot connect with <code>file_client: local</code>, it is that I cannot even get the salt-minion to keep running. 

Running with the default <code>remote</code> behavior works. Was trying to avoid the network interface on the minion running on master. Not a show stopper.

I've not tried with 8.1

**Comment by terminalmage** [comment]
@rterbush Can you explain a little about the use case? Setting ``file_client: local`` runs the minion in masterless mode. In this mode, the minion assumes some of the behavior of the master, which might be leading to the problem since you already have a master running on the same box.

Is there a specific reason for not connecting the master's salt-minion instance to the master like with the other minions?

**Comment by rterbush** [comment]
Reading the comment in the minion config file, it leads me to believe that this configures the minion to access state files, etc on the local filesystem without communicating directly through the master and thus network interface. This was only attempted on the minion that is running on the master. Reporting it since it caused a bit of head scratching as to why my minion stopped running. Only after tracking it back to this file change did I figure that out. Could be cured by a little bit more detail in the comment as to "THIS IS ONLY FOR MASTERLESS MODE".

**Comment by terminalmage** [comment]
@rterbush I totally agree. I just opened https://github.com/saltstack/salt/pull/28110/files to add a comment explaining this to the example minion config file.

**Comment by cachedout** [comment]
Since this was a documentation issue which is now resolved, I'm going to go ahead and close this.
