### ISSUE TITLE
file.managed replaced text file with binary file

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#27973]
Something went totally wrong last night:

    ----------
              ID: /root/.config/pip/pip.conf
        Function: file.managed
          Result: True
         Comment: File /root/.config/pip/pip.conf updated
         Started: 00:38:47.035172
        Duration: 47.9 ms
         Changes:   
                  ----------
                  diff:
                      Replace text file with binary file
    ----------

As you can imagine that makes absolute no sense to replace a text config file with a binary file.

**Comment by ScoreUnder** [comment]
Did you check the file that it dropped in? Was it what you expected, given the file on the salt master?

This could just be the heuristics in `diff` being a little wonky, or it could be due to a file with lots of unprintable characters for some reason.

**Comment by srkunze** [comment]
> Did you check the file that it dropped in? Was it what you expected, given the file on the salt master?

The job run multiple times and subsequent jobs fixed the pip.conf.

> This could just be the heuristics in diff being a little wonky [...]

Nevermind. If they are wonky, they can be fixed.

But in order to do so, I want an error status, so I know. It makes absolutely no sense accidentally replace a text file with a binary file. Especially in case of config files.

**Comment by jfindlay** [comment]
@srkunze, thanks for the report.  Will you post the version of salt you are using and the state that demonstrates the problem?  Did you verify that the updated file was not what you expected?  Was it replaced by something else by mistake?

**Comment by srkunze** [comment]
> Will you post the version of salt you are using

    Salt Version:
               Salt: 2015.8.0
 
    Dependency Versions:
             Jinja2: 2.7.3
           M2Crypto: 0.22
               Mako: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.3.1
             Python: 2.7.3 (default, Apr 14 2012, 08:58:41) [GCC]
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5
               cffi: 0.8.6
           cherrypy: Not Installed
           dateutil: 2.1
              gitdb: 0.5.4
          gitpython: Not Installed
              ioflo: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.2
       mysql-python: Not Installed
          pycparser: 2.10
           pycrypto: 2.6.1
             pygit2: 0.21.2
       python-gnupg: Not Installed
              smmap: 0.8.2
            timelib: Not Installed
 
    System Versions:
               dist: SuSE 12.3 x86_64
            machine: x86_64
            release: 3.7.10-1.40-desktop
             system: openSUSE  12.3 x86_64



> and the state that demonstrates the problem?

    /root/.config/pip/pip.conf:
      file.managed:
        - source: salt://host/files/.config/pip/pip.conf
        - template: jinja
        - makedirs: True

salt://host/files/.config/pip/pip.conf

    [global]
    index-url = https://server/pypi/simple/
    download_cache = ~/.cache/pip
    cert = /etc/ssl/certs/cert.pem

> Did you verify that the updated file was not what you expected?

#27971 is the result of this very issue. Basically, we could not use `pip install` and pip crashed because of this:

    ----------
              ID: install_tbzroottools
        Function: pip.installed
            Name: package
          Result: None
         Comment: Error installing 'tbzroottools': Traceback (most recent call last):
                    File "/usr/bin/pip2", line 9, in <module>
                      load_entry_point('pip==7.1.2', 'console_scripts', 'pip2')()
                    File "/usr/lib/python2.7/site-packages/pip/__init__.py", line 210, in main
                      cmd_name, cmd_args = parseopts(args)
                    File "/usr/lib/python2.7/site-packages/pip/__init__.py", line 146, in parseopts
                      parser = create_main_parser()
                    File "/usr/lib/python2.7/site-packages/pip/__init__.py", line 124, in create_main_parser
                      parser = ConfigOptionParser(**parser_kw)
                    File "/usr/lib/python2.7/site-packages/pip/baseparser.py", line 147, in __init__
                      self.config.read(self.files)
                    File "/usr/lib64/python2.7/ConfigParser.py", line 305, in read
                      self._read(fp, filename)
                    File "/usr/lib64/python2.7/ConfigParser.py", line 512, in _read
                      raise MissingSectionHeaderError(fpname, lineno, line)
                  ConfigParser.MissingSectionHeaderError: File contains no section headers.
                  file: /root/.config/pip/pip.conf, line: 1
                  'bal]\n'
         Started: 00:38:47.277938
        Duration: 386.45 ms
         Changes:   
    ----------

> Was it replaced by something else by mistake?

Maybe another concurrent salt-ssh call for the same minion. But not by mistake.

The other job should put the exactly same file there.

**Comment by srkunze** [comment]
Another thought:

I first thought that pip was really replaced by a binary file so I didn't pay much attention.

However, the exception tells us the erroneous line

    bal]\n

which is the `[global]` section header but missing the first 4 characters.

This is in accordance with the issue described here: https://github.com/saltstack/salt/issues/27970

**Comment by jfindlay** [comment]
@srkunze, thanks for the extra info.  Based on the information you have provided in https://github.com/saltstack/salt/issues/27970#issuecomment-149247964, it seems you are only having this problem when you have more than one concurrent process managing the same file.  If not, are you able to reproduce the error manually with a single salt-ssh process?  I don't have any idea what would be removing the first four characters of a file.

**Comment by srkunze** [comment]
>  If not, are you able to reproduce the error manually with a single salt-ssh process?

We begun to back off and do it sequentially. So, we will see tonight if we run into this.

That is because of further CRC and decoding errors like these:
    
    salt-ssh --force-color minion state.sls integration pillar='...data...'
    [ERROR   ] JSON Render failed for: 
    [CRITICAL] Unable to import msgpack or msgpack_pure python modules
    Traceback (most recent call last):
      File "/tmp/.root_dcdf8c_salt/salt-call", line 4, in <module>
        salt_call()
      File "/tmp/.root_dcdf8c_salt/salt/scripts.py", line 331, in salt_call
        client.run()
      File "/tmp/.root_dcdf8c_salt/salt/cli/call.py", line 53, in run
        caller.run()
      File "/tmp/.root_dcdf8c_salt/salt/cli/caller.py", line 133, in run
        ret = self.call()
      File "/tmp/.root_dcdf8c_salt/salt/cli/caller.py", line 196, in call
        ret['return'] = func(*args, **kwargs)
      File "/tmp/.root_dcdf8c_salt/salt/modules/state.py", line 1174, in pkg
        s_pkg.extractall(root)
      File "/usr/lib64/python2.7/tarfile.py", line 2048, in extractall
        self.extract(tarinfo, path)
      File "/usr/lib64/python2.7/tarfile.py", line 2085, in extract
        self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
      File "/usr/lib64/python2.7/tarfile.py", line 2161, in _extract_member
        self.makefile(tarinfo, targetpath)
      File "/usr/lib64/python2.7/tarfile.py", line 2201, in makefile
        copyfileobj(source, target)
      File "/usr/lib64/python2.7/tarfile.py", line 266, in copyfileobj
        shutil.copyfileobj(src, dst)
      File "/usr/lib64/python2.7/shutil.py", line 49, in copyfileobj
        buf = fsrc.read(length)
      File "/usr/lib64/python2.7/tarfile.py", line 819, in read
        buf += self.fileobj.read(size - len(buf))
      File "/usr/lib64/python2.7/tarfile.py", line 737, in read
        return self.readnormal(size)
      File "/usr/lib64/python2.7/tarfile.py", line 746, in readnormal
        return self.fileobj.read(size)
      File "/usr/lib64/python2.7/gzip.py", line 256, in read
        self._read(readsize)
      File "/usr/lib64/python2.7/gzip.py", line 307, in _read
        uncompress = self.decompress.decompress(buf)
    zlib.error: Error -3 while decompressing: invalid distance code
    [ERROR   ] No JSON object could be decoded
    minion:

And several of those:

    salt-ssh minion state.sls integration pillar='... data...'
    [ERROR   ] JSON Render failed for: 
    [CRITICAL] Unable to import msgpack or msgpack_pure python modules
    Traceback (most recent call last):
      File "/tmp/.root_dcdf8c_salt/salt-call", line 4, in <module>
        salt_call()
      File "/tmp/.root_dcdf8c_salt/salt/scripts.py", line 331, in salt_call
        client.run()
      File "/tmp/.root_dcdf8c_salt/salt/cli/call.py", line 51, in run
        caller.run()
      File "/tmp/.root_dcdf8c_salt/salt/cli/caller.py", line 133, in run
        ret = self.call()
      File "/tmp/.root_dcdf8c_salt/salt/cli/caller.py", line 196, in call
        ret['return'] = func(*args, **kwargs)
      File "/tmp/.root_dcdf8c_salt/salt/modules/state.py", line 1174, in pkg
        s_pkg.extractall(root)
      File "/usr/lib64/python2.7/tarfile.py", line 2048, in extractall
        self.extract(tarinfo, path)
      File "/usr/lib64/python2.7/tarfile.py", line 2085, in extract
        self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
      File "/usr/lib64/python2.7/tarfile.py", line 2161, in _extract_member
        self.makefile(tarinfo, targetpath)
      File "/usr/lib64/python2.7/tarfile.py", line 2201, in makefile
        copyfileobj(source, target)
      File "/usr/lib64/python2.7/tarfile.py", line 266, in copyfileobj
        shutil.copyfileobj(src, dst)
      File "/usr/lib64/python2.7/shutil.py", line 49, in copyfileobj
        buf = fsrc.read(length)
      File "/usr/lib64/python2.7/tarfile.py", line 819, in read
        buf += self.fileobj.read(size - len(buf))
      File "/usr/lib64/python2.7/tarfile.py", line 737, in read
        return self.readnormal(size)
      File "/usr/lib64/python2.7/tarfile.py", line 746, in readnormal
        return self.fileobj.read(size)
      File "/usr/lib64/python2.7/gzip.py", line 256, in read
        self._read(readsize)
      File "/usr/lib64/python2.7/gzip.py", line 320, in _read
        self._read_eof()
      File "/usr/lib64/python2.7/gzip.py", line 342, in _read_eof
        hex(self.crc)))
    IOError: CRC check failed 0xe7a167ab != 0x71f31dceL
    [ERROR   ] No JSON object could be decoded
    minion:

**Comment by srkunze** [comment]
>  I don't have any idea what would be removing the first four characters of a file.
@jfindlay Neither do I. There is a theoretical possibility: corrupted salt_thin transfer but undetected by checksum. But that is highly unlikely.
