### ISSUE TITLE
unit.modules.mysql_test.MySQLTestCase fails with "ValueError: too many values to unpack"

### ISSUE THREAD

**Issue by Whissi** [saltstack/salt#28002]
I am very sure test suite with salt-2015.8.0 passed and this is new in salt-2015.8.1 but now I also get this error with salt-2015.8.0:

```

======================================================================
ERROR: test_db_check (unit.modules.mysql_test.MySQLTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/app-admin/salt-2015.8.1/work/salt-2015.8.1-python2_7/tests/unit/modules/mysql_test.py", line 118, in test_db_check
    self._test_call(mysql.db_check, 'CHECK TABLE `test``\'" db`.`my``\'" table`', 'test`\'" db', 'my`\'" table')
  File "/var/tmp/portage/app-admin/salt-2015.8.1/work/salt-2015.8.1-python2_7/tests/unit/modules/mysql_test.py", line 288, in _test_call
    connect_mock.assert_has_calls(calls)
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 965, in assert_has_calls
    if expected not in all_calls:
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 454, in __contains__
    if sub_list == value:
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 2171, in __eq__
    first, second = other
ValueError: too many values to unpack

======================================================================
ERROR: test_db_create (unit.modules.mysql_test.MySQLTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/app-admin/salt-2015.8.1/work/salt-2015.8.1-python2_7/tests/unit/modules/mysql_test.py", line 164, in test_db_create
    'test`\'" db'
  File "/var/tmp/portage/app-admin/salt-2015.8.1/work/salt-2015.8.1-python2_7/tests/unit/modules/mysql_test.py", line 288, in _test_call
    connect_mock.assert_has_calls(calls)
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 965, in assert_has_calls
    if expected not in all_calls:
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 454, in __contains__
    if sub_list == value:
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 2171, in __eq__
    first, second = other
ValueError: too many values to unpack

======================================================================
ERROR: test_db_exists (unit.modules.mysql_test.MySQLTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/app-admin/salt-2015.8.1/work/salt-2015.8.1-python2_7/tests/unit/modules/mysql_test.py", line 154, in test_db_exists
    'test%_`\'" db'
  File "/var/tmp/portage/app-admin/salt-2015.8.1/work/salt-2015.8.1-python2_7/tests/unit/modules/mysql_test.py", line 288, in _test_call
    connect_mock.assert_has_calls(calls)
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 965, in assert_has_calls
    if expected not in all_calls:
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 454, in __contains__
    if sub_list == value:
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 2171, in __eq__
    first, second = other
ValueError: too many values to unpack

======================================================================
ERROR: test_db_optimize (unit.modules.mysql_test.MySQLTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/app-admin/salt-2015.8.1/work/salt-2015.8.1-python2_7/tests/unit/modules/mysql_test.py", line 130, in test_db_optimize
    self._test_call(mysql.db_optimize, 'OPTIMIZE TABLE `test``\'" db`.`my``\'" table`', 'test`\'" db', 'my`\'" table')
  File "/var/tmp/portage/app-admin/salt-2015.8.1/work/salt-2015.8.1-python2_7/tests/unit/modules/mysql_test.py", line 288, in _test_call
    connect_mock.assert_has_calls(calls)
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 965, in assert_has_calls
    if expected not in all_calls:
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 454, in __contains__
    if sub_list == value:
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 2171, in __eq__
    first, second = other
ValueError: too many values to unpack

======================================================================
ERROR: test_db_remove (unit.modules.mysql_test.MySQLTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/app-admin/salt-2015.8.1/work/salt-2015.8.1-python2_7/tests/unit/modules/mysql_test.py", line 137, in test_db_remove
    self._test_call(mysql.db_remove, 'DROP DATABASE `test``\'" db`;', 'test`\'" db')
  File "/var/tmp/portage/app-admin/salt-2015.8.1/work/salt-2015.8.1-python2_7/tests/unit/modules/mysql_test.py", line 288, in _test_call
    connect_mock.assert_has_calls(calls)
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 965, in assert_has_calls
    if expected not in all_calls:
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 454, in __contains__
    if sub_list == value:
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 2171, in __eq__
    first, second = other
ValueError: too many values to unpack

======================================================================
ERROR: test_db_repair (unit.modules.mysql_test.MySQLTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/app-admin/salt-2015.8.1/work/salt-2015.8.1-python2_7/tests/unit/modules/mysql_test.py", line 124, in test_db_repair
    self._test_call(mysql.db_repair, 'REPAIR TABLE `test``\'" db`.`my``\'" table`', 'test`\'" db', 'my`\'" table')
  File "/var/tmp/portage/app-admin/salt-2015.8.1/work/salt-2015.8.1-python2_7/tests/unit/modules/mysql_test.py", line 288, in _test_call
    connect_mock.assert_has_calls(calls)
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 965, in assert_has_calls
    if expected not in all_calls:
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 454, in __contains__
    if sub_list == value:
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 2171, in __eq__
    first, second = other
ValueError: too many values to unpack

======================================================================
ERROR: test_db_tables (unit.modules.mysql_test.MySQLTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/app-admin/salt-2015.8.1/work/salt-2015.8.1-python2_7/tests/unit/modules/mysql_test.py", line 143, in test_db_tables
    self._test_call(mysql.db_tables, 'SHOW TABLES IN `test``\'" db`', 'test`\'" db')
  File "/var/tmp/portage/app-admin/salt-2015.8.1/work/salt-2015.8.1-python2_7/tests/unit/modules/mysql_test.py", line 288, in _test_call
    connect_mock.assert_has_calls(calls)
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 965, in assert_has_calls
    if expected not in all_calls:
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 454, in __contains__
    if sub_list == value:
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 2171, in __eq__
    first, second = other
ValueError: too many values to unpack

======================================================================
ERROR: test_get_master_status (unit.modules.mysql_test.MySQLTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/app-admin/salt-2015.8.1/work/salt-2015.8.1-python2_7/tests/unit/modules/mysql_test.py", line 264, in test_get_master_status
    self._test_call(mysql.get_master_status, 'SHOW MASTER STATUS')
  File "/var/tmp/portage/app-admin/salt-2015.8.1/work/salt-2015.8.1-python2_7/tests/unit/modules/mysql_test.py", line 288, in _test_call
    connect_mock.assert_has_calls(calls)
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 965, in assert_has_calls
    if expected not in all_calls:
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 454, in __contains__
    if sub_list == value:
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 2171, in __eq__
    first, second = other
ValueError: too many values to unpack

======================================================================
ERROR: test_get_slave_status (unit.modules.mysql_test.MySQLTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/app-admin/salt-2015.8.1/work/salt-2015.8.1-python2_7/tests/unit/modules/mysql_test.py", line 270, in test_get_slave_status
    self._test_call(mysql.get_slave_status, 'SHOW SLAVE STATUS')
  File "/var/tmp/portage/app-admin/salt-2015.8.1/work/salt-2015.8.1-python2_7/tests/unit/modules/mysql_test.py", line 288, in _test_call
    connect_mock.assert_has_calls(calls)
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 965, in assert_has_calls
    if expected not in all_calls:
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 454, in __contains__
    if sub_list == value:
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 2171, in __eq__
    first, second = other
ValueError: too many values to unpack

======================================================================
ERROR: test_processlist (unit.modules.mysql_test.MySQLTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/app-admin/salt-2015.8.1/work/salt-2015.8.1-python2_7/tests/unit/modules/mysql_test.py", line 258, in test_processlist
    self._test_call(mysql.processlist, 'SHOW FULL PROCESSLIST')
  File "/var/tmp/portage/app-admin/salt-2015.8.1/work/salt-2015.8.1-python2_7/tests/unit/modules/mysql_test.py", line 288, in _test_call
    connect_mock.assert_has_calls(calls)
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 965, in assert_has_calls
    if expected not in all_calls:
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 454, in __contains__
    if sub_list == value:
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 2171, in __eq__
    first, second = other
ValueError: too many values to unpack

======================================================================
ERROR: test_query (unit.modules.mysql_test.MySQLTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/app-admin/salt-2015.8.1/work/salt-2015.8.1-python2_7/tests/unit/modules/mysql_test.py", line 277, in test_query
    self._test_call(mysql.query, 'SELECT * FROM testdb', 'testdb', 'SELECT * FROM testdb')
  File "/var/tmp/portage/app-admin/salt-2015.8.1/work/salt-2015.8.1-python2_7/tests/unit/modules/mysql_test.py", line 288, in _test_call
    connect_mock.assert_has_calls(calls)
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 965, in assert_has_calls
    if expected not in all_calls:
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 454, in __contains__
    if sub_list == value:
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 2171, in __eq__
    first, second = other
ValueError: too many values to unpack

======================================================================
ERROR: test_user_create (unit.modules.mysql_test.MySQLTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/app-admin/salt-2015.8.1/work/salt-2015.8.1-python2_7/tests/unit/modules/mysql_test.py", line 78, in test_user_create
    password='BLUECOW'
  File "/var/tmp/portage/app-admin/salt-2015.8.1/work/salt-2015.8.1-python2_7/tests/unit/modules/mysql_test.py", line 288, in _test_call
    connect_mock.assert_has_calls(calls)
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 965, in assert_has_calls
    if expected not in all_calls:
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 454, in __contains__
    if sub_list == value:
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 2171, in __eq__
    first, second = other
ValueError: too many values to unpack

======================================================================
ERROR: test_user_exists (unit.modules.mysql_test.MySQLTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/app-admin/salt-2015.8.1/work/salt-2015.8.1-python2_7/tests/unit/modules/mysql_test.py", line 55, in test_user_exists
    password='BLUECOW'
  File "/var/tmp/portage/app-admin/salt-2015.8.1/work/salt-2015.8.1-python2_7/tests/unit/modules/mysql_test.py", line 288, in _test_call
    connect_mock.assert_has_calls(calls)
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 965, in assert_has_calls
    if expected not in all_calls:
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 454, in __contains__
    if sub_list == value:
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 2171, in __eq__
    first, second = other
ValueError: too many values to unpack

======================================================================
ERROR: test_user_grants (unit.modules.mysql_test.MySQLTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/app-admin/salt-2015.8.1/work/salt-2015.8.1-python2_7/tests/unit/modules/mysql_test.py", line 198, in test_user_grants
    'testuser'
  File "/var/tmp/portage/app-admin/salt-2015.8.1/work/salt-2015.8.1-python2_7/tests/unit/modules/mysql_test.py", line 288, in _test_call
    connect_mock.assert_has_calls(calls)
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 965, in assert_has_calls
    if expected not in all_calls:
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 454, in __contains__
    if sub_list == value:
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 2171, in __eq__
    first, second = other
ValueError: too many values to unpack

======================================================================
ERROR: test_user_info (unit.modules.mysql_test.MySQLTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/app-admin/salt-2015.8.1/work/salt-2015.8.1-python2_7/tests/unit/modules/mysql_test.py", line 183, in test_user_info
    'mytestuser'
  File "/var/tmp/portage/app-admin/salt-2015.8.1/work/salt-2015.8.1-python2_7/tests/unit/modules/mysql_test.py", line 288, in _test_call
    connect_mock.assert_has_calls(calls)
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 965, in assert_has_calls
    if expected not in all_calls:
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 454, in __contains__
    if sub_list == value:
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 2171, in __eq__
    first, second = other
ValueError: too many values to unpack

======================================================================
ERROR: test_user_list (unit.modules.mysql_test.MySQLTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/app-admin/salt-2015.8.1/work/salt-2015.8.1-python2_7/tests/unit/modules/mysql_test.py", line 171, in test_user_list
    self._test_call(mysql.user_list, 'SELECT User,Host FROM mysql.user')
  File "/var/tmp/portage/app-admin/salt-2015.8.1/work/salt-2015.8.1-python2_7/tests/unit/modules/mysql_test.py", line 288, in _test_call
    connect_mock.assert_has_calls(calls)
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 965, in assert_has_calls
    if expected not in all_calls:
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 454, in __contains__
    if sub_list == value:
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 2171, in __eq__
    first, second = other
ValueError: too many values to unpack

======================================================================
ERROR: test_user_remove (unit.modules.mysql_test.MySQLTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/app-admin/salt-2015.8.1/work/salt-2015.8.1-python2_7/tests/unit/modules/mysql_test.py", line 111, in test_user_remove
    'testuser'
  File "/var/tmp/portage/app-admin/salt-2015.8.1/work/salt-2015.8.1-python2_7/tests/unit/modules/mysql_test.py", line 288, in _test_call
    connect_mock.assert_has_calls(calls)
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 965, in assert_has_calls
    if expected not in all_calls:
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 454, in __contains__
    if sub_list == value:
  File "/usr/lib64/python2.7/site-packages/mock/mock.py", line 2171, in __eq__
    first, second = other
ValueError: too many values to unpack

----------------------------------------------------------------------
Ran 3254 tests in 242.663s

FAILED (errors=17, skipped=208, expected failures=1)

```

**Comment by jfindlay** [comment]
@Whissi, thanks for the report.
