### ISSUE TITLE
Update the versioning section in the Formula docs to point at the SPM requirements

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#28030]
Currently the formula docs recommend a VERSION file & a semver version whereas the SPM docs recommend a FORMULA file and a date-based version. Now that SPM is a thing we should switch over to that.

[Report courtesy of Theo C.](https://groups.google.com/d/topic/salt-users/BlEwPatvzGA/discussion)

**Comment by dahrens** [comment]
Currently quite a few salt-formulas have a FORMULA file that uses semver versioning, while spm 2019.2.0 (Fluorine) does not support it.

Everything works fine as long as you only build and publish one version of a formula.

As soon as you build a new version of your formula and want to run `create_repo` spm dies, because it expects the version to be integer:

```
spm create_repo /srv/spm_build
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
ValueError: invalid literal for int() with base 10: '0.2.0'
Traceback (most recent call last):
  File "/usr/bin/spm", line 12, in <module>
    salt_spm()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 527, in salt_spm
    spm.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/spm.py", line 41, in run
    client.run(self.args)
  File "/usr/lib/python2.7/dist-packages/salt/spm/__init__.py", line 137, in run
    self._create_repo(args)
  File "/usr/lib/python2.7/dist-packages/salt/spm/__init__.py", line 758, in _create_repo
    if int(new_info['version']) == int(cur_info['version']):
ValueError: invalid literal for int() with base 10: '0.2.0'
Traceback (most recent call last):
  File "/usr/bin/spm", line 12, in <module>
    salt_spm()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 527, in salt_spm
    spm.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/spm.py", line 41, in run
    client.run(self.args)
  File "/usr/lib/python2.7/dist-packages/salt/spm/__init__.py", line 137, in run
    self._create_repo(args)
  File "/usr/lib/python2.7/dist-packages/salt/spm/__init__.py", line 758, in _create_repo
    if int(new_info['version']) == int(cur_info['version']):
ValueError: invalid literal for int() with base 10: '0.2.0'
```

Of course this is intended behavior as the docs tell you to pick a version in another format.
But in fact it prevents users from using the salt-formulas together with spm without applying their own version scheme on top - which erodes the main idea behind versioning at all.

Most likely this issue needs to be addressed to the salt-formula community as well, but I don't know where to create it.
