### ISSUE TITLE
Failed to deploy VM to proxmox 4

### ISSUE THREAD

**Issue by PaulRitzkat** [saltstack/salt#28048]
Hello,

deployment with salt 2015.8.1 (version report at the end) on debian 8.2 to proxmox 4.0-50 fails.

Other parts, like salt-cloud --list-images my-proxmox-config, are working as expected.

Did proxmox maybe change it's API with version 4 and it's not supported? I saw that LXC deployment is not possible with proxmox (and it throws errors if I try anyway ;) ).

provider config:
```yaml
my-proxmox-config:
  # Set up the location of the salt master
  #
  minion:
    master: salt.local

  # Set the PROXMOX access credentials (see below)
  #
  user: salt@pam
  password: badpw

  # Set the access URL for your PROXMOX host
  #
  url: proxmox.local
  verify_ssl: False
  driver: proxmox
```

profile config:
```yaml
proxmox-debian:
    provider: my-proxmox-config
    #image: local:vztmpl/debian-8.0-standard_8.0-1_amd64.tar.gz
    image: local:iso/debian-8.2.0-amd64-netinst.iso
    technology: qemu
    host: proxmox.local
    #ip_address: 192.168.1.50
    #ssh_username: root
    #password: badpw
    #nameserver: 192.168.1.1
    disk: 10
    size: ''
    #cpus: 1
    #cpuunits: 1024
    #memory: 1024
    #swap: 2048
    #onboot: 1
```

verbose output from failed salt-cloud -l all -p proxmox-debian test1
```
[DEBUG   ] Reading configuration from /etc/salt/cloud
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt
[DEBUG   ] Missing configuration file: /etc/salt/cloud.providers
[DEBUG   ] Including configuration from '/etc/salt/cloud.providers.d/ec2.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers.d/ec2.conf
[DEBUG   ] Including configuration from '/etc/salt/cloud.providers.d/gce.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers.d/gce.conf
[DEBUG   ] Including configuration from '/etc/salt/cloud.providers.d/proxmox.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers.d/proxmox.conf
[DEBUG   ] Including configuration from '/etc/salt/cloud.providers.d/rsos.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers.d/rsos.conf
[DEBUG   ] Including configuration from '/etc/salt/cloud.providers.d/saltify.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers.d/saltify.conf
/usr/lib/python2.7/dist-packages/salt/config.py:2242: DeprecationWarning: The term 'provider' is being deprecated in favor of 'driver'. Support for 'provider' will be removed in Salt Nitrogen. Please convert your cloud provider configuration files to use 'driver'.
[DEBUG   ] Missing configuration file: /etc/salt/cloud.profiles
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/ec2.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/ec2.conf
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/gce.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/gce.conf
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/proxmox.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/proxmox.conf
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/rsos.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/rsos.conf
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/saltify.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/saltify.conf
[TRACE   ] None of the required configuration sections, 'logstash_udp_handler' and 'logstash_zmq_handler', were found the in the configuration. Not loading the Logstash logging handlers module.
[TRACE   ] The required configuration section, 'fluent_handler', was not found the in the configuration. Not loading the fluent logging handlers module.
[DEBUG   ] Configuration file path: /etc/salt/cloud
[TRACE   ] Trying pysss.getgrouplist for 'root'
[TRACE   ] Trying generic group list for 'root'
[TRACE   ] Group list for user 'root': []
[INFO    ] salt-cloud starting
[TRACE   ] 'parallels.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] Could not LazyLoad parallels.avail_sizes
[TRACE   ] 'parallels.avail_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] LazyLoaded parallels.avail_locations
[TRACE   ] 'proxmox.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] Could not LazyLoad proxmox.avail_sizes
[TRACE   ] 'saltify.destroy' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] Could not LazyLoad saltify.destroy
[TRACE   ] 'saltify.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] Could not LazyLoad saltify.avail_sizes
[TRACE   ] 'saltify.avail_images' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] Could not LazyLoad saltify.avail_images
[TRACE   ] 'saltify.avail_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] Could not LazyLoad saltify.avail_locations
[TRACE   ] 'rackspace.reboot' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] LazyLoaded rackspace.reboot
[TRACE   ] 'openstack.list_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] LazyLoaded openstack.list_locations
[TRACE   ] 'rackspace.list_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] LazyLoaded rackspace.list_locations
[DEBUG   ] Could not LazyLoad saltify.optimize_providers
[DEBUG   ] The 'saltify' cloud driver is unable to be optimized.
[DEBUG   ] Could not LazyLoad proxmox.optimize_providers
[DEBUG   ] The 'proxmox' cloud driver is unable to be optimized.
[TRACE   ] 'parallels.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[TRACE   ] 'parallels.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] Could not LazyLoad parallels.avail_sizes
[TRACE   ] 'parallels.avail_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] LazyLoaded parallels.avail_locations
[TRACE   ] 'proxmox.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] Could not LazyLoad proxmox.avail_sizes
[TRACE   ] 'saltify.destroy' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] Could not LazyLoad saltify.destroy
[TRACE   ] 'saltify.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] Could not LazyLoad saltify.avail_sizes
[TRACE   ] 'saltify.avail_images' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] Could not LazyLoad saltify.avail_images
[TRACE   ] 'saltify.avail_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] Could not LazyLoad parallels.avail_sizes
[TRACE   ] 'parallels.avail_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] Could not LazyLoad saltify.avail_locations
[TRACE   ] 'proxmox.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[TRACE   ] 'rackspace.reboot' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] LazyLoaded rackspace.reboot
[DEBUG   ] Could not LazyLoad proxmox.avail_sizes
[TRACE   ] 'openstack.list_locations' has been marked as not supported. Removing from the list of supported cloud functions
[TRACE   ] 'saltify.destroy' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] LazyLoaded openstack.list_locations
[TRACE   ] 'rackspace.list_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] Could not LazyLoad saltify.destroy
[DEBUG   ] LazyLoaded rackspace.list_locations
[TRACE   ] 'saltify.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] Could not LazyLoad saltify.avail_sizes
[TRACE   ] 'saltify.avail_images' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] Could not LazyLoad saltify.avail_images
[TRACE   ] 'saltify.avail_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] Could not LazyLoad saltify.avail_locations
[TRACE   ] 'rackspace.reboot' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] LazyLoaded rackspace.reboot
[TRACE   ] 'openstack.list_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] LazyLoaded openstack.list_locations
[TRACE   ] 'rackspace.list_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] LazyLoaded rackspace.list_locations
[DEBUG   ] Getting resource: vms.. (filter: None)
[DEBUG   ] Not authenticated yet, doing that now..
[WARNING ] /usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:770: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)

[DEBUG   ] get: https://proxmox.local:8006/api2/json/cluster/resources (None)
[DEBUG   ] Filter not given: {}, returning all resource: nodes
[DEBUG   ] Generating minion keys for 'test1'
[DEBUG   ] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event - data = {'profile': 'proxmox-debian', 'event': 'starting create', '_stamp': '2015-10-16T22:56:31.792157', 'name': 'test1', 'provider': 'my-proxmox-config:proxmox'}
[INFO    ] Creating Cloud VM test1
[DEBUG   ] Not authenticated yet, doing that now..
[WARNING ] /usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:770: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)

[DEBUG   ] get: https://proxmox.local:8006/api2/json/cluster/nextid (None)
[DEBUG   ] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event - data = {'_stamp': '2015-10-16T22:56:31.888379', 'event': 'requesting instance', 'kwargs': {'vmid': 101}}
[DEBUG   ] Preparing to generate a node using these parameters: {'vmid': 101}
[DEBUG   ] post: https://proxmox.local:8006/api2/json/nodes/proxmox.local/qemu ({'vmid': 101})
[ERROR   ] Error creating test1 on PROXMOX

The following exception was thrown when trying to run the initial deployment:
500 Server Error: proxy loop detected
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/proxmox.py", line 534, in create
    data = create_node(vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/proxmox.py", line 673, in create_node
    node = query('post', 'nodes/{0}/{1}'.format(vmhost, vm_['technology']), newnode)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/proxmox.py", line 179, in query
    response.raise_for_status()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 851, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: proxy loop detected
Error: There was a profile error: Failed to deploy VM
```

salt --versions-report:
```
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: debian 8.2
        machine: x86_64
        release: 4.2.2-1-pve
         system: debian 8.2
```

**Comment by jfindlay** [comment]
@PaulRitzkat, thanks for the report.

**Comment by pass-by-value** [comment]
Hi @PaulRitzkat 

I created a VM on Proxmox cloud `[DEBUG   ] Host has been created!`. I'm using `2015.8`.

I looked up the error `500 Server Error: proxy loop detected` specified in your (well written and helpful) issue report. Found a Proxmox [web forum](http://forum.proxmox.com/threads/10619-Web-Proxy-loop-detected) link that might be of interest to you (not sure if it is the exact issue you are facing; I'm still learning Proxmox so bear with me). Other than that I'd look at the web console to see if any other error was thrown there.

Please keep me posted, I'd like to make sure this works for you.

**Comment by PaulRitzkat** [comment]
Hi @pass-by-value are you on Proxmox v4? I've found the same forum post, but I don't have the same issue. I don't have a Proxmox Cluster and I can login and create VMs over the Webinterface. I tried the suggested restarts and even did a restart of the Host, but the same error persists. 

No errors in the Tasks list or in the Cluster log:
```
Oct 19 22:21:55 proxmox pvedaemon[20170]: <root@pam> successful auth for user 'salt@pam'
Oct 19 22:21:56 proxmox pvedaemon[20170]: <root@pam> successful auth for user 'salt@pam'
```
I can login with salt@pam and create VMs no problem.

Thanks for your help!

**Comment by pass-by-value** [comment]
@PaulRitzkat 

I'm using `Version: 4.0-480d8559d0`.

I just realized that my cloud provider looks like

```yaml
my-proxmox:
  user: root@pam
  password: badpass
  provider: proxmox
  verify_ssl: False
  url: 1.2.3.4
  minion:
    master: 5.6.7.8
```

The change being that I (wrongly) have `provider: proxmox` in place of `driver: proxmox`. Strangely I was able to create a VM with `provider: proxmox` and got an error when using the latter. The error I got was different than the one you saw.

I'm wondering if having `provider: proxmox` allows you to create VMs as well? In any case I'll be investigating this.

**Comment by PaulRitzkat** [comment]
@pass-by-value same error as before. What do you specify in your cloud profile?

```
[DEBUG   ] Reading configuration from /etc/salt/cloud
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt
[DEBUG   ] Missing configuration file: /etc/salt/cloud.providers
[DEBUG   ] Including configuration from '/etc/salt/cloud.providers.d/ec2.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers.d/ec2.conf
[DEBUG   ] Including configuration from '/etc/salt/cloud.providers.d/gce.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers.d/gce.conf
[DEBUG   ] Including configuration from '/etc/salt/cloud.providers.d/proxmox.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers.d/proxmox.conf
[DEBUG   ] Including configuration from '/etc/salt/cloud.providers.d/rsos.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers.d/rsos.conf
[DEBUG   ] Including configuration from '/etc/salt/cloud.providers.d/saltify.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers.d/saltify.conf
/usr/lib/python2.7/dist-packages/salt/config.py:2242: DeprecationWarning: The term 'provider' is being deprecated in favor of 'driver'. Support for 'provider' will be removed in Salt Nitrogen. Please convert your cloud provider configuration files to use 'driver'.
[DEBUG   ] Missing configuration file: /etc/salt/cloud.profiles
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/ec2.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/ec2.conf
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/gce.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/gce.conf
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/proxmox.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/proxmox.conf
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/rsos.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/rsos.conf
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/saltify.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/saltify.conf
[TRACE   ] None of the required configuration sections, 'logstash_udp_handler' and 'logstash_zmq_handler', were found the in the configuration. Not loading the Logstash logging handlers module.
[TRACE   ] The required configuration section, 'fluent_handler', was not found the in the configuration. Not loading the fluent logging handlers module.
[DEBUG   ] Configuration file path: /etc/salt/cloud
[TRACE   ] Trying pysss.getgrouplist for 'root'
[TRACE   ] Trying generic group list for 'root'
[TRACE   ] Group list for user 'root': []
[INFO    ] salt-cloud starting
[TRACE   ] 'parallels.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] Could not LazyLoad parallels.avail_sizes
[TRACE   ] 'parallels.avail_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] LazyLoaded parallels.avail_locations
[TRACE   ] 'proxmox.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] Could not LazyLoad proxmox.avail_sizes
[TRACE   ] 'saltify.destroy' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] Could not LazyLoad saltify.destroy
[TRACE   ] 'saltify.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] Could not LazyLoad saltify.avail_sizes
[TRACE   ] 'saltify.avail_images' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] Could not LazyLoad saltify.avail_images
[TRACE   ] 'saltify.avail_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] Could not LazyLoad saltify.avail_locations
[TRACE   ] 'rackspace.reboot' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] LazyLoaded rackspace.reboot
[TRACE   ] 'openstack.list_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] LazyLoaded openstack.list_locations
[TRACE   ] 'rackspace.list_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] LazyLoaded rackspace.list_locations
[DEBUG   ] Could not LazyLoad saltify.optimize_providers
[DEBUG   ] The 'saltify' cloud driver is unable to be optimized.
[DEBUG   ] Could not LazyLoad proxmox.optimize_providers
[DEBUG   ] The 'proxmox' cloud driver is unable to be optimized.
[TRACE   ] 'parallels.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[TRACE   ] 'parallels.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] Could not LazyLoad parallels.avail_sizes
[TRACE   ] 'parallels.avail_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] LazyLoaded parallels.avail_locations
[TRACE   ] 'proxmox.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] Could not LazyLoad proxmox.avail_sizes
[TRACE   ] 'saltify.destroy' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] Could not LazyLoad saltify.destroy
[TRACE   ] 'saltify.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] Could not LazyLoad saltify.avail_sizes
[TRACE   ] 'saltify.avail_images' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] Could not LazyLoad parallels.avail_sizes
[TRACE   ] 'parallels.avail_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] Could not LazyLoad saltify.avail_images
[DEBUG   ] LazyLoaded parallels.avail_locations
[TRACE   ] 'saltify.avail_locations' has been marked as not supported. Removing from the list of supported cloud functions
[TRACE   ] 'proxmox.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] Could not LazyLoad saltify.avail_locations
[DEBUG   ] Could not LazyLoad proxmox.avail_sizes
[TRACE   ] 'rackspace.reboot' has been marked as not supported. Removing from the list of supported cloud functions
[TRACE   ] 'saltify.destroy' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] LazyLoaded rackspace.reboot
[TRACE   ] 'openstack.list_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] Could not LazyLoad saltify.destroy
[TRACE   ] 'rackspace.list_locations' has been marked as not supported. Removing from the list of supported cloud functions
[TRACE   ] 'saltify.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] LazyLoaded rackspace.list_locations
[DEBUG   ] Could not LazyLoad saltify.avail_sizes
[TRACE   ] 'saltify.avail_images' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] Could not LazyLoad saltify.avail_images
[TRACE   ] 'saltify.avail_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] Could not LazyLoad saltify.avail_locations
[TRACE   ] 'rackspace.reboot' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] LazyLoaded rackspace.reboot
[TRACE   ] 'openstack.list_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] LazyLoaded openstack.list_locations
[TRACE   ] 'rackspace.list_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] LazyLoaded rackspace.list_locations
[DEBUG   ] Getting resource: vms.. (filter: None)
[DEBUG   ] Not authenticated yet, doing that now..
[WARNING ] /usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:770: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)

[DEBUG   ] get: https://192.168.1.50:8006/api2/json/cluster/resources (None)
[DEBUG   ] get: https://192.168.1.50:8006/api2/json/nodes/intrepid/qemu/105/config (None)
[DEBUG   ] Filter not given: {u'storage': {u'status': u'running', u'node': u'intrepid', u'uptime': 12226, u'name': u'storage', u'maxcpu': 2, u'diskread': 179894430, u'mem': 226754560, 'config': {u'ide2': u'local:iso/openmediavault_2.1_amd64.iso,media=cdrom', u'onboot': 1, u'smbios1': u'uuid=c846ef72-4502-45bf-9453-400882b7f636', u'name': u'storage', u'balloon': 1024, u'memory': 8192, u'sockets': 1, u'virtio0': u'local:105/vm-105-disk-1.qcow2,size=32G', u'numa': 0, u'cores': 2, u'ostype': u'l26', u'virtio1': u'data:vm-105-disk-1,backup=no,size=15000G', u'bootdisk': u'virtio0', u'cpu': u'host', u'digest': u'6ad6339e19f0a51273bb57d43e4f2827b1d65025', u'net0': u'virtio=36:38:33:64:34:61,bridge=vmbr0'}, u'vmid': 105, u'netin': 2377991, u'id': u'qemu/105', u'diskwrite': 88171008, u'template': 0, u'netout': 8828290, u'disk': 0, u'type': u'qemu', u'cpu': 0.00193465884298259, u'maxdisk': 34359738368, u'maxmem': 8589934592}}, returning all resource: nodes
[DEBUG   ] VM_Name: storage
[DEBUG   ] vm_details: {u'status': u'running', u'node': u'intrepid', u'uptime': 12226, u'name': u'storage', u'maxcpu': 2, u'diskread': 179894430, u'mem': 226754560, 'config': {u'ide2': u'local:iso/openmediavault_2.1_amd64.iso,media=cdrom', u'onboot': 1, u'smbios1': u'uuid=c846ef72-4502-45bf-9453-400882b7f636', u'name': u'storage', u'balloon': 1024, u'memory': 8192, u'sockets': 1, u'virtio0': u'local:105/vm-105-disk-1.qcow2,size=32G', u'numa': 0, u'cores': 2, u'ostype': u'l26', u'virtio1': u'data:vm-105-disk-1,backup=no,size=15000G', u'bootdisk': u'virtio0', u'cpu': u'host', u'digest': u'6ad6339e19f0a51273bb57d43e4f2827b1d65025', u'net0': u'virtio=36:38:33:64:34:61,bridge=vmbr0'}, u'vmid': 105, u'netin': 2377991, u'id': u'qemu/105', u'diskwrite': 88171008, u'template': 0, u'netout': 8828290, u'disk': 0, u'type': u'qemu', u'cpu': 0.00193465884298259, u'maxdisk': 34359738368, u'maxmem': 8589934592}
[DEBUG   ] Generating minion keys for 'test2'
[DEBUG   ] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event - data = {'profile': 'proxmox-debian', 'event': 'starting create', '_stamp': '2015-10-19T21:00:42.633091', 'name': 'test2', 'provider': 'my-proxmox-config:proxmox'}
[INFO    ] Creating Cloud VM test2
[DEBUG   ] Not authenticated yet, doing that now..
[WARNING ] /usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:770: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)

[DEBUG   ] get: https://192.168.1.50:8006/api2/json/cluster/nextid (None)
[DEBUG   ] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event - data = {'_stamp': '2015-10-19T21:00:42.727010', 'event': 'requesting instance', 'kwargs': {'vmid': 108}}
[DEBUG   ] Preparing to generate a node using these parameters: {'vmid': 108}
[DEBUG   ] post: https://192.168.1.50:8006/api2/json/nodes/intrepid.local/qemu ({'vmid': 108})
[ERROR   ] Error creating test2 on PROXMOX

The following exception was thrown when trying to run the initial deployment:
500 Server Error: proxy loop detected
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/proxmox.py", line 534, in create
    data = create_node(vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/proxmox.py", line 673, in create_node
    node = query('post', 'nodes/{0}/{1}'.format(vmhost, vm_['technology']), newnode)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/proxmox.py", line 179, in query
    response.raise_for_status()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 851, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: proxy loop detected
Error: There was a profile error: Failed to deploy VM
```

**Comment by pass-by-value** [comment]
@PaulRitzkat My profile looks like below

```yaml
proxmox-vm:
  provider: my-proxmox
  image: local:pve/ubuntu-14.04-standard_14.04-1_amd64.tar.gz
  technology: qemu
  host: pve
  ip_address: 192.168.100.155
  password: badpass
```

![proxmox_cloud_messages](https://cloud.githubusercontent.com/assets/5684871/10590697/1cd6a886-7680-11e5-8568-db97d461c295.png)

Screenshot above highlights relevant message on the `Task` panel of Proxmox's GUI. I see an `Ok` message on the GUI for the create task. This task was submitted via salt cloud, I'm using my root@pam credentials for the Proxmox cloud provider.

(Note: My start jobs don't go through because the Proxmox hypervisor itself is on a cloud VM, but I can create the VM just fine).

**Comment by PaulRitzkat** [comment]
@pass-by-value I don't see any tasks created by salt, it seems salt gets stuck on the creation phase. Don't you get the size error? I need to put an empty "size: ' ' " variable in the profile, or the deployment would fail with:
```[ERROR   ] The required 'size' configuration setting is missing from the 'proxmox-debian' profile, which is configured under the 'my-proxmox-config' alias.```
See #27849 

Maybe the error is fixed with a newer salt version? I'm on the latest from repo.saltstack.com

**Comment by pass-by-value** [comment]
@PaulRitzkat I was able to reproduce this issue.

I changed my cloud profile to look like

```yaml
proxmox-vm:
  provider: my-proxmox
  image: local:pve/ubuntu-14.04-standard_14.04-1_amd64.tar.gz
  technology: qemu
  #host: pve
  host: 1.2.3.4
  ip_address: 192.168.100.155
  size: ''
  password: topsecret
```

The profile config above causes `HTTPError: 500 Server Error: proxy loop detected`

The reason being, the `host` key in the config is set to my host's IP address. But it needs to be set to the actual name that appears under datacenter `pve` in my case.

Screenshot below highlights what field I used for `host`.  I'd suggest trying this out.

![proxmox_cloud_name](https://cloud.githubusercontent.com/assets/5684871/10615580/a9feca0a-772e-11e5-91e1-18dbecc775fe.png)

Let me know how it goes. Thanks.

**Comment by PaulRitzkat** [comment]
@pass-by-value that did the trick! Thank you for your help! I would've never thought of that, since I use the FQDN everywhere...

So in closing: the host variable in the cloud profile has to be set to the configured name of the proxmox host.

**Comment by pass-by-value** [comment]
Created https://github.com/saltstack/salt/pull/28149 to add a note about this to the docs
