### ISSUE TITLE
pip module doesn't see installed packages and generally weird

### ISSUE THREAD

**Issue by onorua** [saltstack/salt#28044]
So, I have:

salt-ssh OS: Debian 8
remote machine OS: Ubuntu 15.04

```
ii  salt-common                             2015.8.1+ds-1                       all          shared libraries that salt requires for all packages
ii  salt-minion                             2015.8.1+ds-1                       all          client package for salt, the distributed remote execution system
ii  salt-ssh                                2015.8.1+ds-1                       all          remote manager to administer servers via salt
ii  python-pip                       1.5.6-5ubuntu2               all          alternative Python package installer
```

I do:
```
install pygit requirements:
  pkg.installed:
    - pkgs:
      - python-dev
      - python-pip
      - libffi-dev
      - libgit2-dev
      - python-cffi
      - wget
      - cmake

install libgit2:
  cmd.run:
    - creates: /usr/local/lib/libgit2.so
    - name: wget -cO- https://github.com/libgit2/libgit2/archive/v0.23.0.tar.gz | tar -C /root/ -zx ; cd /root/libgit2-0.23.0; cmake . ; make ; make install; rm -rf /root/libgit2*; ldconfig
    - require:
      - pkg: install pygit requirements

install pygit2:
  pip.installed:
    - name: pygit2
    - require:
      - cmd: install libgit2
      - pkg: install pygit requirements
```

as a result I get:
```
----------
          ID: install pygit2
    Function: pip.installed
        Name: pygit2
      Result: None
     Comment: Error installing 'pygit2': Exception:
              Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
                  status = self.run(options, args)
                File "/usr/lib/python2.7/dist-packages/pip/commands/freeze.py", line 74, in run
                  req = pip.FrozenRequirement.from_dist(dist, dependency_links, find_tags=find_tags)
                File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 299, in from_dist
                  assert len(specs) == 1 and specs[0][0] == '=='
              AssertionError
              
              Storing debug log for failure in /home/vagrant/.pip/pip.log
     Started: 19:39:52.555186
    Duration: 145.033 ms
     Changes:   
```

But I'm able to install this pip module with pip:
```
root@master:~# pip install pygit2
Downloading/unpacking pygit2
  Downloading pygit2-0.23.2.tar.gz (464kB): 464kB downloaded
  Running setup.py (path:/tmp/pip-build-VUNdYO/pygit2/setup.py) egg_info for package pygit2
    
Requirement already satisfied (use --upgrade to upgrade): cffi in /usr/lib/python2.7/dist-packages (from pygit2)
Requirement already satisfied (use --upgrade to upgrade): pycparser in /usr/lib/python2.7/dist-packages (from cffi->pygit2)
Installing collected packages: pygit2
  Running setup.py install for pygit2
...
Successfully installed pygit2
Cleaning up...root@master:~# pip2 install pygit2
Requirement already satisfied (use --upgrade to upgrade): pygit2 in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): cffi in /usr/lib/python2.7/dist-packages (from pygit2)
Requirement already satisfied (use --upgrade to upgrade): pycparser in /usr/lib/python2.7/dist-packages (from cffi->pygit2)
Cleaning up...
```

So, problem 1:
- for some reason pip modules status is not taken into consideration. 
- it fail with some strange 

Am I doing something wrong?

**Comment by jfindlay** [comment]
@onorua, thanks for the report.

**Comment by etki** [comment]
having same thing here

**Comment by peter-slovak** [comment]
This happens because some recent APT packages use triple equal sign to the Pip dependency (e.g. python-apt===1.2.3). If you have a recent version of Pip installed via easy_install for example, you won't hit this problem when using CLI - you are using the easy_install binary at /usr/local/bin/pip.

Unfortunately, salt-minion uses /usr/local/bin/pip2 which is not a symlink neither is updated by easy_install - it is the same code as the APT version of Pip. The reason for this is the order in which the pip module does the search (v2015.8.5): https://github.com/saltstack/salt/blob/v2015.8.5/salt/modules/pip.py#L118

So far overwriting the /usr/local/bin/pip2 to a symlink pointing to /usr/local/bin/pip has been working for me. Can anyone more competent make a comment whether it is necessary to search for "pip2" first?

**Comment by peter-slovak** [comment]
Anyway, here's the PR if Salt gurus deem it worthy: #31433

**Comment by jfindlay** [comment]
Thanks, @peter-slovak.  Is anyone else able to verify that this fixes the issue?

**Comment by onorua** [comment]
My pip is working now
