### ISSUE TITLE
Exception in salt loader develop branch

### ISSUE THREAD

**Issue by SmithSamuelM** [saltstack/salt#28062]
When curr_ext is empty ' ' raise this error

``` python-traceback
Traceback (most recent call last):
  File "/usr/local/bin/salt", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Data/Code/public/salt/scripts/salt", line 10, in <module>
    salt_main()
  File "/Data/Code/public/salt/salt/scripts.py", line 437, in salt_main
    client.run()
  File "/Data/Code/public/salt/salt/cli/salt.py", line 49, in run
    skip_perm_errors=skip_perm_errors)
  File "/Data/Code/public/salt/salt/client/__init__.py", line 93, in get_local_client
    return salt.client.raet.LocalClient(mopts=opts)
  File "/Data/Code/public/salt/salt/client/raet/__init__.py", line 33, in __init__
    salt.client.LocalClient.__init__(self, c_path, mopts)
  File "/Data/Code/public/salt/salt/client/__init__.py", line 143, in __init__
    self.utils = salt.loader.utils(self.opts)
  File "/Data/Code/public/salt/salt/loader.py", line 299, in utils
    pack={'__context__': context})
  File "/Data/Code/public/salt/salt/loader.py", line 901, in __init__
    self.refresh_file_mapping()
  File "/Data/Code/public/salt/salt/loader.py", line 1037, in refresh_file_mapping
    if suffix_order.index(ext) < suffix_order.index(curr_ext):
ValueError: '' is not in list
```

**Comment by cachedout** [comment]
By chance does removing stale *.pyc files resolve this?

**Comment by kaihowl** [comment]
I had the same problem when for some reason I had mixed a pip and a Debian packaged based installation. I was able to clear up the problem by completely removing any salt packages and running a git and pip based installation with the bootstrap script.

**Comment by ntucker** [comment]
+1 to kaihowl's comment. I was using vagrant so I just deleted and re provisioned the machine. Couldn't figure out which things to uninstall manually.
