### ISSUE TITLE
git.latest fails on 2015.8.1

### ISSUE THREAD

**Issue by rterbush** [saltstack/salt#28147]
I see many git.latest issues, not clear if this is related to any of them.

Running on CentOS-7 minion.

state.git.latest fails:
```
[DEBUG   ] Error loading states.ipmi: No module named pyghmi.ipmi
[DEBUG   ] Could not LazyLoad git.latest
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
KeyError: 'git.latest'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 227, in salt_call
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 69, in run
    caller.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 236, in run
    ret = self.call()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 138, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 538, in highstate
    whitelist=kwargs.get('whitelist')
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2986, in call_highstate
    return self.state.call_high(high)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2068, in call_high
    ret = dict(list(disabled.items()) + list(self.call_chunks(chunks).items()))
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 1624, in call_chunks
    running = self.call_chunk(low, running, chunks)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 1770, in call_chunk
    self._mod_init(low)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 613, in _mod_init
    self.states['{0}.{1}'.format(low['state'], low['fun'])]  # pylint: disable=W0106
  File "/usr/lib/python2.7/site-packages/salt/utils/lazy.py", line 90, in __getitem__
    raise KeyError(key)
KeyError: 'git.latest'
```

master salt --versions:
```
root@manage formulas]# salt --versions
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
           RAET: Not Installed
        Tornado: 4.1
            ZMQ: 3.2.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: 0.21.4
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.1.1503 Core
        machine: x86_64
        release: 3.10.0-229.14.1.el7.centos.plus.x86_64
         system: CentOS Linux 7.1.1503 Core
```

minion salt-call --versions:
```
[root@ip-10-1-2-15 ~]# salt-call --versions
           Salt: 2015.5.5
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: Not Installed
```

**Comment by rterbush** [comment]
Closing as this was simply a matter of no git binary on the target minion. Would be wonderful if the error message back would be something to that effect rather than a backtrace.

**Comment by rallytime** [comment]
@rterbush I'm glad you figured it out. This stacktrace was caused by a regression starting with 2015.5.3, but has been fixed at the HEAD of the 2015.5 branch with #27681 and will be fixed on the next release of 2015.5 (2015.5.7). A friendly "missing dependency" message will be available on that release and is already available in 2015.8.0 and newer.

**Comment by rterbush** [comment]
@rallytime That stack trace was output by 2015.8.1

**Comment by rterbush** [comment]
@rallytime I stand corrected. I see that the minion code I am getting from COPR is still 2015.5..  May explain some of the other issues I seem to be running into. Any way to easily get newer packages without rewriting the bootstrap script?

**Comment by rallytime** [comment]
@rterbush Yeah that stack trace comes from the minion on 2015.5.5.

Currently the only way to get different installation versions using bootstrap is to install from a git branch or tag, which you can do either by adding `script_args: git v2015.8.1` (tagged release example) or `script_args: git 2015.5` (branch example) if your using salt-cloud or you can just add those same `git 2015.5` examples to the end of executing the `sh install_salt.sh` command.
