### ISSUE TITLE
glusterfs.created - ValueError: too many values to unpack 

### ISSUE THREAD

**Issue by renataogarcia** [saltstack/salt#28193]
glusterfs.created returns the following error:
```
An exception occurred in this state: Traceback (most recent call last):
	File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1560, in call **cdata['kwargs'])
    File "/usr/lib/python2.7/dist-packages/salt/states/glusterfs.py", line 123, in created
	    if isinstance(__salt__['glusterfs.status'](name), dict):
    File "/usr/lib/python2.7/dist-packages/salt/modules/glusterfs.py", line 243, in status
          brick, port, online, pid = line.split()[1:]
ValueError: too many values to unpack
```
This is caused because [newer versions](https://bugzilla.redhat.com/show_bug.cgi?id=1188685) of Gluster outputs an additional column for the RDMA port:
```
Status of volume: wealth-resources
Gluster process                             TCP Port  RDMA Port  Online  Pid
------------------------------------------------------------------------------
Brick wpbtweb1:/mnt/wealth-resources/brick  49152     0          Y       13561
Brick wpbtweb2:/mnt/wealth-resources/brick  49153     0          Y       15713
NFS Server on localhost                     2049      0          Y       15734
Self-heal Daemon on localhost               N/A       N/A        Y       15740
NFS Server on wpbtweb1                      2049      0          Y       13582
Self-heal Daemon on wpbtweb1                N/A       N/A        Y       13587
 
Task Status of Volume wealth-resources
------------------------------------------------------------------------------
There are no active volume tasks
```

Using Gluster 3.7 and salt 2015.5.3

**Comment by renataogarcia** [comment]
Possible workaround by patching salt module:
```
patch_salt_for_gluster-3.7:
  file.replace:
    - name: /usr/lib/python2.7/dist-packages/salt/modules/glusterfs.py
    - pattern: port, online
    - repl: port, port_rdma, online
```

**Comment by jfindlay** [comment]
@renataogarcia, thanks for the report.
