### ISSUE TITLE
ipset.present should support -entry: lists of items that contain commas

### ISSUE THREAD

**Issue by ahammond** [saltstack/salt#28192]
```yaml
example_set:
  ipset.set_present:
    - set_type: hash:net,port

example_set_contents:
  ipset.present:
    - set_name: example_set
    - entry: [u'1.2.3.0/24,53', u'1.2.3.0/24,69']
```

```
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] In saltenv 'base', looking at rel_path u'storage/example.sls' to resolve u'salt://storage/example.sls'
[DEBUG   ] In saltenv 'base', ** considering ** path u'/var/cache/salt/minion/files/base/storage/example.sls' to resolve u'salt://storage/example.sls'
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache u'salt://storage/example.sls'
[DEBUG   ] compile template: /var/cache/salt/minion/files/base/storage/example.sls
[DEBUG   ] Jinja search path: ['/var/cache/salt/minion/files/base']
[DEBUG   ] Rendered data from file: /var/cache/salt/minion/files/base/storage/example.sls:
example_set:
  ipset.set_present:
    - set_type: hash:net,port

example_set_contents:
  ipset.present:
    - set_name: example_set
    - entry: [u'1.2.3.0/24,53', u'1.2.3.0/24,69']

[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Results of YAML rendering: 
OrderedDict([('example_set', OrderedDict([('ipset.set_present', [OrderedDict([('set_type', 'hash:net,port')])])])), ('example_set_contents', OrderedDict([('ipset.present', [OrderedDict([('set_name', 'example_set')]), OrderedDict([('entry', ["u'1.2.3.0/24", "53'", "u'1.2.3.0/24", "69'"])])])]))])
[DEBUG   ] LazyLoaded ipset.version
[DEBUG   ] LazyLoaded ipset.set_present
[INFO    ] Running state [example_set] at time 11:29:31.351077
[INFO    ] Executing state ipset.set_present for example_set
[DEBUG   ] LazyLoaded cmd.run_all
[INFO    ] Executing command '/usr/sbin/ipset list -t example_set' in directory '/root'
[ERROR   ] Command '/usr/sbin/ipset list -t example_set' failed with return code: 1
[ERROR   ] stderr: ipset v6.11: The set with the given name does not exist
[ERROR   ] retcode: 1
[INFO    ] Executing command '/usr/sbin/ipset create example_set hash:net,port family inet' in directory '/root'
[DEBUG   ] output: 
[INFO    ] {'locale': 'example_set'}
[INFO    ] Completed state [example_set] at time 11:29:31.363953
[INFO    ] Running state [example_set_contents] at time 11:29:31.364701
[INFO    ] Executing state ipset.present for example_set_contents
[INFO    ] Executing command '/usr/sbin/ipset list -t example_set' in directory '/root'
[DEBUG   ] stdout: Name: example_set
Type: hash:net,port
Header: family inet hashsize 1024 maxelem 65536 
Size in memory: 16752
References: 0
[INFO    ] Executing command '/usr/sbin/ipset list example_set' in directory '/root'
[DEBUG   ] stdout: Name: example_set
Type: hash:net,port
Header: family inet hashsize 1024 maxelem 65536 
Size in memory: 16752
References: 0
Members:
[INFO    ] Executing command '/usr/sbin/ipset list -t example_set' in directory '/root'
[DEBUG   ] stdout: Name: example_set
Type: hash:net,port
Header: family inet hashsize 1024 maxelem 65536 
Size in memory: 16752
References: 0
[INFO    ] Executing command '/usr/sbin/ipset list example_set' in directory '/root'
[DEBUG   ] stdout: Name: example_set
Type: hash:net,port
Header: family inet hashsize 1024 maxelem 65536 
Size in memory: 16752
References: 0
Members:
[INFO    ] Executing command "/usr/sbin/ipset add -exist example_set u'1.2.3.0/24" in directory '/root'
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/state.py", line 1591, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.6/site-packages/salt/states/ipset.py", line 219, in present
    command = __salt__['ipset.add'](kwargs['set_name'], entry, family, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/modules/ipset.py", line 351, in add
    out = __salt__['cmd.run'](cmd, python_shell=False)
  File "/usr/lib/python2.6/site-packages/salt/modules/cmdmod.py", line 803, in run
    use_vt=use_vt)
  File "/usr/lib/python2.6/site-packages/salt/modules/cmdmod.py", line 428, in _run
    cmd = shlex.split(cmd, posix=posix)
  File "/usr/lib64/python2.6/shlex.py", line 279, in split
    return list(lex)
  File "/usr/lib64/python2.6/shlex.py", line 269, in next
    token = self.get_token()
  File "/usr/lib64/python2.6/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "/usr/lib64/python2.6/shlex.py", line 172, in read_token
    raise ValueError, "No closing quotation"
ValueError: No closing quotation

[INFO    ] Completed state [example_set_contents] at time 11:29:31.385162
[DEBUG   ] File /var/cache/salt/minion/accumulator/48508624 does not exist, no need to cleanup.
[DEBUG   ] LazyLoaded config.option
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'frks1', 'tcp://192.168.33.2:4506', 'aes')
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'frks1', 'tcp://192.168.33.2:4506')
[DEBUG   ] LazyLoaded highstate.output
[DEBUG   ] LazyLoaded nested.output
local:
----------
          ID: example_set
    Function: ipset.set_present
      Result: True
     Comment: ipset set example_set created successfully for ipv4
     Started: 11:29:31.351077
    Duration: 12.876 ms
     Changes:   
              ----------
              locale:
                  example_set
----------
          ID: example_set_contents
    Function: ipset.present
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.6/site-packages/salt/state.py", line 1591, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.6/site-packages/salt/states/ipset.py", line 219, in present
                  command = __salt__['ipset.add'](kwargs['set_name'], entry, family, **kwargs)
                File "/usr/lib/python2.6/site-packages/salt/modules/ipset.py", line 351, in add
                  out = __salt__['cmd.run'](cmd, python_shell=False)
                File "/usr/lib/python2.6/site-packages/salt/modules/cmdmod.py", line 803, in run
                  use_vt=use_vt)
                File "/usr/lib/python2.6/site-packages/salt/modules/cmdmod.py", line 428, in _run
                  cmd = shlex.split(cmd, posix=posix)
                File "/usr/lib64/python2.6/shlex.py", line 279, in split
                  return list(lex)
                File "/usr/lib64/python2.6/shlex.py", line 269, in next
                  token = self.get_token()
                File "/usr/lib64/python2.6/shlex.py", line 96, in get_token
                  raw = self.read_token()
                File "/usr/lib64/python2.6/shlex.py", line 172, in read_token
                  raise ValueError, "No closing quotation"
              ValueError: No closing quotation
     Started: 11:29:31.364701
    Duration: 20.461 ms
     Changes:   

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    1
------------
Total states run:     2
Total run time:  33.337 ms
```

```local:
    Salt Version:
               Salt: 2015.8.1
     
    Dependency Versions:
             Jinja2: 2.7.3
           M2Crypto: 0.20.2
               Mako: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.3.1
             Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
               RAET: 0.6.3
            Tornado: 4.2.1
                ZMQ: 4.0.4
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: 1.3.2
            libnacl: 1.4.3
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: Not Installed
            timelib: Not Installed
     
    System Versions:
               dist: centos 6.6 Final
            machine: x86_64
            release: 2.6.32-504.16.2.el6.x86_64
             system: CentOS 6.6 Final 
```

**Comment by ahammond** [comment]
The work around is to loop over entries and create a separate state for each. Makes for a hideous mess in the output, but...

**Comment by ahammond** [comment]
Hmm, I did a bit more testing and this seems to be triggered even with sets of 2 entries. Updating the initial description.

**Comment by ahammond** [comment]
Ahhhhh! The list of entries are unicode python strings... but should just be plain old strings. Remove the u prefix and it works.
