### ISSUE TITLE
deserialize msgpack message error 

### ISSUE THREAD

**Issue by mimianddaniel** [saltstack/salt#28318]
```
2015-10-27 00:55:24,066 [salt.payload                             ][CRITICAL][63960] Could not deserialize msgpack message: <snip>This often happens when trying to
 read a file not in binary mode.Please open an issue and include the following error: unpack(b) received extra data.
2015-10-27 00:55:24,066 [salt.master                              ][ERROR   ][63847] Error in function _syndic_return:
Traceback (most recent call last):
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/master.py", line 1460, in run_func
    ret = getattr(self, func)(load)
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/master.py", line 1315, in _syndic_return
    self._return(ret)
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/master.py", line 1276, in _return
    self.opts, load, event=self.event, mminion=self.mminion)
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/utils/job.py", line 79, in store_job
    if 'jid' in load and not mminion.returners[getfstr](load.get('jid', '')):
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/returners/local_cache.py", line 236, in get_load
    ret = serial.load(salt.utils.fopen(os.path.join(jid_dir, LOAD_P), 'rb'))
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/payload.py", line 114, in load
    return self.loads(data)
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/payload.py", line 98, in loads
    return msgpack.loads(msg, use_list=True)
  File "msgpack/_unpacker.pyx", line 142, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:142)
ExtraData: unpack(b) received extra data.
2015-10-27 00:55:24,066 [salt.master                              ][ERROR   ][63960] Error in function _syndic_return:
Traceback (most recent call last):
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/master.py", line 1460, in run_func
    ret = getattr(self, func)(load)
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/master.py", line 1315, in _syndic_return
    self._return(ret)
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/master.py", line 1276, in _return
    self.opts, load, event=self.event, mminion=self.mminion)
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/utils/job.py", line 79, in store_job
    if 'jid' in load and not mminion.returners[getfstr](load.get('jid', '')):
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/returners/local_cache.py", line 236, in get_load
    ret = serial.load(salt.utils.fopen(os.path.join(jid_dir, LOAD_P), 'rb'))
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/payload.py", line 114, in load
    return self.loads(data)
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/payload.py", line 98, in loads
    return msgpack.loads(msg, use_list=True)
  File "msgpack/_unpacker.pyx", line 142, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:142)
ExtraData: unpack(b) received extra data.
```

running on 2015.5.5

ref #25991

**Comment by jfindlay** [comment]
@mimianddaniel, are you able to reproduce this on new system(s) that are installed from salt packages?  The only circumstance in which I was able to reproduce this is on a system with salt installed from git after switching from the 2015.5 branch to 2015.8 and back.

**Comment by mimianddaniel** [comment]
We packaged it after clone the source from git. Is that what you meant? for installed from git?? whats the difference btw reinstalling package from branch 5 to 8 and back and new system?

**Comment by jfindlay** [comment]
Yes, I have only encountered this problem when using salt installed from git.  There is some obscure python caching problem that I was not able to locate.

**Comment by mimianddaniel** [comment]
So what's the solution to fix this problem for those who are installing from the git?

**Comment by mimianddaniel** [comment]
any update on this? I am seeing this quite often - and needs to restart the minion to fix this problem each time.

**Comment by jfindlay** [comment]
@mimianddaniel, not that I know of.  I was only able to track this down to stale python files (possibly in msgpack) from a git-based upgrade.  @cachedout may know more here, but I suspect a clean install or a distro packaged-based upgrade strategy may be the solution.

**Comment by mimianddaniel** [comment]
@cachedout 
https://github.com/saltstack/salt/blob/2015.5/salt/minion.py#L1889
I would like to completely stop grain refresh including pillar refresh. Pillar refresh gets called as well due to this code.  Is this code really behaving as expected???

**Comment by developerinlondon** [comment]
i am also receiving this problem. you can reproduce it quite easily if you clone my repo and run 'vagrant up'. try it a few times if it doesnt happen first time.

here is my repo: https://github.com/developerinlondon/vagrant-salt-lxc
