### ISSUE TITLE
'dockerng' __virtual__ returned False (Could not LazyLoad dockerng)

### ISSUE THREAD

**Issue by vitalyisaev2** [saltstack/salt#28338]
Hello! We use SaltStack and Docker together, and currently I'm trying to move our SLS files from deprecated ```dockerio``` to ```dockerng```, but it fails to load. 

I've updated Salt packages to the most recent release:
```yaml
root@wks-isaev:~# salt-call --versions-report
Salt Version:
           Salt: 2015.8.1
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.21.1
           Mako: 1.0.2
         PyYAML: 3.11
          PyZMQ: 14.4.1
         Python: 2.7.10 (default, Sep 13 2015, 20:30:50)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 1.1.2
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 15.10 wily
        machine: x86_64
        release: 3.16.0-44-generic
         system: Ubuntu 15.10 wily
```

And surely I have ```docker-py``` installed:
```
root@wks-isaev:~# pip freeze | grep docker-py
docker-py==1.2.3
```

When I try to run a container, I see the following errors (please sorry for an enormous log output):
```txt
root@wks-isaev:~# salt-call state.sls baas.consul -l debug
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: wks-isaev
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] The `lspci` binary is not available on the system. GPU grains will not be available.
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[WARNING ] Although 'dmidecode' was found in path, the current user cannot execute it. Grains output might not be accurate.
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'wks-isaev', 'tcp://192.168.1.33:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (1194)
[DEBUG   ] Setting zmq_reconnect_ivl to '1194ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'wks-isaev', 'tcp://192.168.1.33:4506', 'aes')
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'wks-isaev', 'tcp://192.168.1.33:4506')
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'wks-isaev', 'tcp://192.168.1.33:4506', 'clear')
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded state.sls
[DEBUG   ] LazyLoaded saltutil.is_running
[DEBUG   ] LazyLoaded grains.get
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'wks-isaev', 'tcp://192.168.1.33:4506', 'aes')
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'wks-isaev', 'tcp://192.168.1.33:4506')
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'wks-isaev', 'tcp://192.168.1.33:4506', 'aes')
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'wks-isaev', 'tcp://192.168.1.33:4506')
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] In saltenv 'base', looking at rel_path u'baas/consul.sls' to resolve u'salt://baas/consul.sls'
[DEBUG   ] In saltenv 'base', ** considering ** path u'/var/cache/salt/minion/files/base/baas/consul.sls' to resolve u'salt://baas/consul.sls'
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache u'salt://baas/consul.sls'
[DEBUG   ] compile template: /var/cache/salt/minion/files/base/baas/consul.sls
[DEBUG   ] Jinja search path: ['/var/cache/salt/minion/files/base']
[DEBUG   ] Rendered data from file: /var/cache/salt/minion/files/base/baas/consul.sls:
include:
  - env



















/srv/docker/consul:
  file.directory

/srv/docker/consul/conf:
  file.directory:
    - clean: True

/srv/docker/consul/log:
  file.directory:
    - clean: True

/srv/docker/consul/conf/consul.json:
  file.managed:
    - source: salt://baas/consul/consul.json.jinja2
    - template: jinja
    - context:
      consul: {'node': 'consul', 'datacenter': 'dc1', 'service': {'tag': 'testenv', 'name': 'consul'}, 'image': 'consul', 'server_mode': True, 'label': 'gliderlabs', 'repo': 'env', 'remotes': [], 'acl_datacenter': 'dc1', 'root': 'consul', 'ports': [{53: 53}, {8300: 8300}, {8301: 8301}, {8302: 8302}, {8400: 8400}, {8500: 8500}], 'acl_master_token': 123}
    - require:
      - file: /srv/docker/consul/conf


consul_absent:
  dockerng.absent:
    - names:
      - consul
    - require:
      - pip: docker-py

spv.dbaa.km.li/env/consul:gliderlabs:
  dockerng.image_present:
    - force: True
    - require:
      - pip: docker-py

consul:
  dockerng.running:
    - name: consul
    - image: spv.dbaa.km.li/env/consul:gliderlabs
    - ports:
      - 53
      - 8300
      - 8301
      - 8302
      - 8400
      - 8500
      - 8600
    - port_bindings:
      - "53/tcp":
            HostIp: ""
            HostPort: "8600"
      - "53/udp":
            HostIp: ""
            HostPort: "8600"
      - "8300/tcp":
            HostIp: ""
            HostPort: "8300"
      - "8301/tcp":
            HostIp: ""
            HostPort: "8301"
      - "8302/tcp":
            HostIp: ""
            HostPort: "8302"
      - "8302/udp":
            HostIp: ""
            HostPort: "8302"
      - "8400/tcp":
            HostIp: ""
            HostPort: "8400"
      - "8500/tcp":
            HostIp: ""
            HostPort: "8500"
    - command: agent --config-file /etc/consul/consul.json
    - environment:
      - SERVICE_NAME: consul
      - SERVICE_TAGS: testenv
    - volumes:
      - /srv/docker/consul/conf : /etc/consul/
      - /srv/docker/consul/log : /var/log
    - require:
      - dockerng: "spv.dbaa.km.li/env/consul:gliderlabs"
      - file: /srv/docker/consul/conf/consul.json

[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Results of YAML rendering: 
OrderedDict([('include', ['env']), ('/srv/docker/consul', 'file.directory'), ('/srv/docker/consul/conf', OrderedDict([('file.directory', [OrderedDict([('clean', True)])])])), ('/srv/docker/consul/log', OrderedDict([('file.directory', [OrderedDict([('clean', True)])])])), ('/srv/docker/consul/conf/consul.json', OrderedDict([('file.managed', [OrderedDict([('source', 'salt://baas/consul/consul.json.jinja2')]), OrderedDict([('template', 'jinja')]), OrderedDict([('context', None), ('consul', OrderedDict([('node', 'consul'), ('datacenter', 'dc1'), ('service', OrderedDict([('tag', 'testenv'), ('name', 'consul')])), ('image', 'consul'), ('server_mode', True), ('label', 'gliderlabs'), ('repo', 'env'), ('remotes', []), ('acl_datacenter', 'dc1'), ('root', 'consul'), ('ports', [OrderedDict([(53, 53)]), OrderedDict([(8300, 8300)]), OrderedDict([(8301, 8301)]), OrderedDict([(8302, 8302)]), OrderedDict([(8400, 8400)]), OrderedDict([(8500, 8500)])]), ('acl_master_token', 123)]))]), OrderedDict([('require', [OrderedDict([('file', '/srv/docker/consul/conf')])])])])])), ('consul_absent', OrderedDict([('dockerng.absent', [OrderedDict([('names', ['consul'])]), OrderedDict([('require', [OrderedDict([('pip', 'docker-py')])])])])])), ('spv.dbaa.km.li/env/consul:gliderlabs', OrderedDict([('dockerng.image_present', [OrderedDict([('force', True)]), OrderedDict([('require', [OrderedDict([('pip', 'docker-py')])])])])])), ('consul', OrderedDict([('dockerng.running', [OrderedDict([('name', 'consul')]), OrderedDict([('image', 'spv.dbaa.km.li/env/consul:gliderlabs')]), OrderedDict([('ports', [53, 8300, 8301, 8302, 8400, 8500, 8600])]), OrderedDict([('port_bindings', [OrderedDict([('53/tcp', OrderedDict([('HostIp', ''), ('HostPort', '8600')]))]), OrderedDict([('53/udp', OrderedDict([('HostIp', ''), ('HostPort', '8600')]))]), OrderedDict([('8300/tcp', OrderedDict([('HostIp', ''), ('HostPort', '8300')]))]), OrderedDict([('8301/tcp', OrderedDict([('HostIp', ''), ('HostPort', '8301')]))]), OrderedDict([('8302/tcp', OrderedDict([('HostIp', ''), ('HostPort', '8302')]))]), OrderedDict([('8302/udp', OrderedDict([('HostIp', ''), ('HostPort', '8302')]))]), OrderedDict([('8400/tcp', OrderedDict([('HostIp', ''), ('HostPort', '8400')]))]), OrderedDict([('8500/tcp', OrderedDict([('HostIp', ''), ('HostPort', '8500')]))])])]), OrderedDict([('command', 'agent --config-file /etc/consul/consul.json')]), OrderedDict([('environment', [OrderedDict([('SERVICE_NAME', 'consul')]), OrderedDict([('SERVICE_TAGS', 'testenv')])])]), OrderedDict([('volumes', [OrderedDict([('/srv/docker/consul/conf', '/etc/consul/')]), OrderedDict([('/srv/docker/consul/log', '/var/log')])])]), OrderedDict([('require', [OrderedDict([('dockerng', 'spv.dbaa.km.li/env/consul:gliderlabs')]), OrderedDict([('file', '/srv/docker/consul/conf/consul.json')])])])])]))])
[DEBUG   ] Could not find file from saltenv 'base', u'salt://env.sls'
[DEBUG   ] In saltenv 'base', looking at rel_path u'env/init.sls' to resolve u'salt://env/init.sls'
[DEBUG   ] In saltenv 'base', ** considering ** path u'/var/cache/salt/minion/files/base/env/init.sls' to resolve u'salt://env/init.sls'
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache u'salt://env/init.sls'
[DEBUG   ] compile template: /var/cache/salt/minion/files/base/env/init.sls
[DEBUG   ] Jinja search path: ['/var/cache/salt/minion/files/base']
[DEBUG   ] Rendered data from file: /var/cache/salt/minion/files/base/env/init.sls:
git:
  pkg.installed


lxc-docker-1.6.0:
  pkg:
    - installed
  service.enabled:
    - name: docker


python-pip:
  pkg:
    - installed

docker-py:
  pip.installed:
    - requirements: salt://env/requirements.txt
    - require:
      - pkg: python-pip

[DEBUG   ] Results of YAML rendering: 
OrderedDict([('git', 'pkg.installed'), ('lxc-docker-1.6.0', OrderedDict([('pkg', ['installed']), ('service.enabled', [OrderedDict([('name', 'docker')])])])), ('python-pip', OrderedDict([('pkg', ['installed'])])), ('docker-py', OrderedDict([('pip.installed', [OrderedDict([('requirements', 'salt://env/requirements.txt')]), OrderedDict([('require', [OrderedDict([('pkg', 'python-pip')])])])])]))])
[DEBUG   ] LazyLoaded pkg.install
[DEBUG   ] LazyLoaded pkg.installed
[DEBUG   ] Error loading module.ifttt: IFTTT Secret Key Unavailable, not loading.
[DEBUG   ] Error loading module.ipmi: No module named pyghmi.ipmi
[DEBUG   ] Error loading module.victorops: No VictorOps api key found.
[DEBUG   ] Error loading module.npm: npm execution module could not be loaded because the npm binary could not be located
[DEBUG   ] Error loading module.nacl: libnacl import error, perhaps missing python libnacl package
[DEBUG   ] Could not LazyLoad pkg.ex_mod_init
[INFO    ] Running state [git] at time 20:57:41.666386
[INFO    ] Executing state pkg.installed for git
[INFO    ] Executing command ['dpkg-query', '--showformat', '${Status} ${Package} ${Version} ${Architecture}\n', '-W'] in directory '/root'
[DEBUG   ] Could not LazyLoad pkg.normalize_name
[INFO    ] Package git is already installed
[INFO    ] Completed state [git] at time 20:57:42.671995
[INFO    ] Running state [lxc-docker-1.6.0] at time 20:57:42.672188
[INFO    ] Executing state pkg.installed for lxc-docker-1.6.0
[DEBUG   ] Could not LazyLoad pkg.normalize_name
[INFO    ] Package lxc-docker-1.6.0 is already installed
[INFO    ] Completed state [lxc-docker-1.6.0] at time 20:57:42.674597
[DEBUG   ] LazyLoaded service.enabled
[INFO    ] Running state [docker] at time 20:57:42.675147
[INFO    ] Executing state service.enabled for docker
[INFO    ] Executing command ['runlevel', '/run/utmp'] in directory '/root'
[ERROR   ] Command ['runlevel', '/run/utmp'] failed with return code: 1
[ERROR   ] output: Too many arguments.
[INFO    ] Service docker is already enabled, and is in the desired state
[INFO    ] Completed state [docker] at time 20:57:42.720364
[INFO    ] Running state [python-pip] at time 20:57:42.720569
[INFO    ] Executing state pkg.installed for python-pip
[DEBUG   ] Could not LazyLoad pkg.normalize_name
[INFO    ] Package python-pip is already installed
[INFO    ] Completed state [python-pip] at time 20:57:42.723295
[DEBUG   ] LazyLoaded pip.installed
[INFO    ] Running state [docker-py] at time 20:57:42.784800
[INFO    ] Executing state pip.installed for docker-py
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'wks-isaev', 'tcp://192.168.1.33:4506', 'aes')
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'wks-isaev', 'tcp://192.168.1.33:4506')
[INFO    ] Executing command ['/usr/bin/pip2', 'install', '--requirement', '/var/cache/salt/minion/files/base/env/requirements.txt'] in directory '/root'
[DEBUG   ] stdout: Requirement already satisfied (use --upgrade to upgrade): docker-py<1.3 in /usr/local/lib/python2.7/dist-packages (from -r /var/cache/salt/minion/files/base/env/requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): requests>=2.5.2 in /usr/local/lib/python2.7/dist-packages (from docker-py<1.3->-r /var/cache/salt/minion/files/base/env/requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): six>=1.3.0 in /usr/local/lib/python2.7/dist-packages (from docker-py<1.3->-r /var/cache/salt/minion/files/base/env/requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): websocket-client>=0.11.0 in /usr/local/lib/python2.7/dist-packages (from docker-py<1.3->-r /var/cache/salt/minion/files/base/env/requirements.txt (line 1))
Cleaning up...
[INFO    ] Requirements were already installed.
[INFO    ] Completed state [docker-py] at time 20:57:43.406673
[DEBUG   ] LazyLoaded file.directory
[INFO    ] Running state [/srv/docker/consul] at time 20:57:43.407969
[INFO    ] Executing state file.directory for /srv/docker/consul
[INFO    ] Directory /srv/docker/consul is in the correct state
[INFO    ] Completed state [/srv/docker/consul] at time 20:57:43.408691
[INFO    ] Running state [/srv/docker/consul/conf] at time 20:57:43.408848
[INFO    ] Executing state file.directory for /srv/docker/consul/conf
[DEBUG   ] List of kept files when use file.directory with clean: []
[INFO    ] {'removed': ['/srv/docker/consul/conf/consul.json']}
[INFO    ] Completed state [/srv/docker/consul/conf] at time 20:57:43.409685
[INFO    ] Running state [/srv/docker/consul/log] at time 20:57:43.409834
[INFO    ] Executing state file.directory for /srv/docker/consul/log
[DEBUG   ] List of kept files when use file.directory with clean: []
[INFO    ] Directory /srv/docker/consul/log is in the correct state
[INFO    ] Completed state [/srv/docker/consul/log] at time 20:57:43.410562
[INFO    ] Running state [/srv/docker/consul/conf/consul.json] at time 20:57:43.410942
[INFO    ] Executing state file.managed for /srv/docker/consul/conf/consul.json
[DEBUG   ] In saltenv 'base', looking at rel_path u'baas/consul/consul.json.jinja2' to resolve u'salt://baas/consul/consul.json.jinja2'
[DEBUG   ] In saltenv 'base', ** considering ** path u'/var/cache/salt/minion/files/base/baas/consul/consul.json.jinja2' to resolve u'salt://baas/consul/consul.json.jinja2'
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache u'salt://baas/consul/consul.json.jinja2'
[DEBUG   ] Jinja search path: ['/var/cache/salt/minion/files/base']
[INFO    ] File changed:
New file
[INFO    ] Completed state [/srv/docker/consul/conf/consul.json] at time 20:57:43.475208
[DEBUG   ] LazyLoaded dockerng.version
[DEBUG   ] LazyLoaded selinux.getenforce
[DEBUG   ] LazyLoaded lvs.get_rules
[DEBUG   ] LazyLoaded portage_config.get_missing_flags
[DEBUG   ] LazyLoaded layman.add
[DEBUG   ] LazyLoaded xmpp.send_msg
[DEBUG   ] LazyLoaded win_servermanager.install
[DEBUG   ] LazyLoaded reg.read_key
[DEBUG   ] LazyLoaded boto_iam.role_exists
[DEBUG   ] LazyLoaded ipset.version
[DEBUG   ] LazyLoaded boto_sns.exists
[DEBUG   ] LazyLoaded boto_cfn.exists
[DEBUG   ] LazyLoaded ifttt.trigger_event
[DEBUG   ] Could not LazyLoad redis.set_key
[DEBUG   ] LazyLoaded victorops.create_event
[DEBUG   ] LazyLoaded boto_asg.exists
[DEBUG   ] LazyLoaded boto_elb.exists
[DEBUG   ] LazyLoaded win_dns_client.add_dns
[DEBUG   ] LazyLoaded npm.list
[DEBUG   ] Error loading states.npm: 'npm' binary not found on system
[DEBUG   ] LazyLoaded glusterfs.list_volumes
[DEBUG   ] LazyLoaded makeconf.get_var
[DEBUG   ] LazyLoaded boto_cloudwatch.get_alarm
[DEBUG   ] Could not LazyLoad elasticsearch.exists
[DEBUG   ] LazyLoaded boto_route53.get_record
[DEBUG   ] LazyLoaded keystone.auth
[DEBUG   ] LazyLoaded win_dacl.add_ace
[DEBUG   ] LazyLoaded memcached.status
[DEBUG   ] Could not LazyLoad influxdb.db_exists
[DEBUG   ] LazyLoaded splunk_search.get
[DEBUG   ] LazyLoaded boto_secgroup.exists
[DEBUG   ] LazyLoaded lvs.get_rules
[DEBUG   ] LazyLoaded boto_vpc.exists
[DEBUG   ] LazyLoaded boto_ec2.get_key
[DEBUG   ] LazyLoaded rdp.enable
[DEBUG   ] LazyLoaded apache.a2enmod
[DEBUG   ] LazyLoaded postgres.user_exists
[DEBUG   ] LazyLoaded postgres.schema_exists
[DEBUG   ] LazyLoaded postgres.tablespace_exists
[DEBUG   ] Could not LazyLoad firewall.get_config
[DEBUG   ] Could not LazyLoad bigip.exec_action
[DEBUG   ] LazyLoaded apache.config
[DEBUG   ] Failed to import states glance:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1110, in _load_module
    ), fn_, fpath, desc)
  File "/usr/lib/python2.7/dist-packages/salt/states/glance.py", line 15, in <module>
    from keystoneclient.apiclient.exceptions import \
ImportError: No module named keystoneclient.apiclient.exceptions
[DEBUG   ] LazyLoaded boto_asg.exists
[DEBUG   ] LazyLoaded ps.pkill
[DEBUG   ] LazyLoaded eselect.exec_action
[DEBUG   ] LazyLoaded nftables.version
[DEBUG   ] LazyLoaded trafficserver.set_var
[DEBUG   ] LazyLoaded boto_dynamodb.exists
[DEBUG   ] LazyLoaded boto_sqs.exists
[DEBUG   ] LazyLoaded bower.list
[DEBUG   ] LazyLoaded postgres.group_create
[DEBUG   ] LazyLoaded pecl.list
[DEBUG   ] LazyLoaded chef.client
[DEBUG   ] LazyLoaded boto_elasticache.exists
[DEBUG   ] LazyLoaded win_path.rehash
[DEBUG   ] Could not LazyLoad influxdb.db_exists
[DEBUG   ] LazyLoaded mongodb.user_exists
[DEBUG   ] LazyLoaded zk_concurrency.lock
[DEBUG   ] Could not LazyLoad augeas.execute
[DEBUG   ] LazyLoaded at.at
[DEBUG   ] Error loading states.ipmi: No module named pyghmi.ipmi
[DEBUG   ] Could not LazyLoad dockerng.absent
[INFO    ] Running state [consul] at time 20:57:43.529563
[DEBUG   ] LazyLoaded dockerng.absent
[ERROR   ] State 'dockerng.absent' was not found in SLS 'baas.consul'
Reason: 'dockerng' __virtual__ returned False

[DEBUG   ] LazyLoaded dockerng.image_present
[INFO    ] Running state [spv.dbaa.km.li/env/consul:gliderlabs] at time 20:57:43.530197
[DEBUG   ] LazyLoaded dockerng.image_present
[ERROR   ] State 'dockerng.image_present' was not found in SLS 'baas.consul'
Reason: 'dockerng' __virtual__ returned False

[DEBUG   ] LazyLoaded dockerng.running
[DEBUG   ] File /var/cache/salt/minion/accumulator/139861225661392 does not exist, no need to cleanup.
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'wks-isaev', 'tcp://192.168.1.33:4506', 'aes')
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'wks-isaev', 'tcp://192.168.1.33:4506')
[DEBUG   ] LazyLoaded highstate.output
[DEBUG   ] LazyLoaded nested.output
[DEBUG   ] LazyLoaded nested.output
local:
----------
          ID: git
    Function: pkg.installed
      Result: True
     Comment: Package git is already installed
     Started: 20:57:41.666386
    Duration: 1005.609 ms
     Changes:   
----------
          ID: lxc-docker-1.6.0
    Function: pkg.installed
      Result: True
     Comment: Package lxc-docker-1.6.0 is already installed
     Started: 20:57:42.672188
    Duration: 2.409 ms
     Changes:   
----------
          ID: lxc-docker-1.6.0
    Function: service.enabled
        Name: docker
      Result: True
     Comment: Service docker is already enabled, and is in the desired state
     Started: 20:57:42.675147
    Duration: 45.217 ms
     Changes:   
----------
          ID: python-pip
    Function: pkg.installed
      Result: True
     Comment: Package python-pip is already installed
     Started: 20:57:42.720569
    Duration: 2.726 ms
     Changes:   
----------
          ID: docker-py
    Function: pip.installed
      Result: True
     Comment: Requirements were already installed.
     Started: 20:57:42.784800
    Duration: 621.873 ms
     Changes:   
----------
          ID: /srv/docker/consul
    Function: file.directory
      Result: True
     Comment: Directory /srv/docker/consul is in the correct state
     Started: 20:57:43.407969
    Duration: 0.722 ms
     Changes:   
----------
          ID: /srv/docker/consul/conf
    Function: file.directory
      Result: True
     Comment: Files cleaned from directory /srv/docker/consul/conf
     Started: 20:57:43.408848
    Duration: 0.837 ms
     Changes:   
              ----------
              removed:
                  - /srv/docker/consul/conf/consul.json
----------
          ID: /srv/docker/consul/log
    Function: file.directory
      Result: True
     Comment: Directory /srv/docker/consul/log is in the correct state
     Started: 20:57:43.409834
    Duration: 0.728 ms
     Changes:   
----------
          ID: /srv/docker/consul/conf/consul.json
    Function: file.managed
      Result: True
     Comment: File /srv/docker/consul/conf/consul.json updated
     Started: 20:57:43.410942
    Duration: 64.266 ms
     Changes:   
              ----------
              diff:
                  New file
              mode:
                  0644
----------
          ID: consul_absent
    Function: dockerng.absent
        Name: consul
      Result: False
     Comment: State 'dockerng.absent' was not found in SLS 'baas.consul'
              Reason: 'dockerng' __virtual__ returned False
     Started: 
    Duration: 
     Changes:   
----------
          ID: spv.dbaa.km.li/env/consul:gliderlabs
    Function: dockerng.image_present
      Result: False
     Comment: State 'dockerng.image_present' was not found in SLS 'baas.consul'
              Reason: 'dockerng' __virtual__ returned False
     Started: 
    Duration: 
     Changes:   
----------
          ID: consul
    Function: dockerng.running
      Result: False
     Comment: One or more requisite failed: baas.consul.spv.dbaa.km.li/env/consul:gliderlabs
     Started: 
    Duration: 
     Changes:   

Summary for local
------------
Succeeded: 9 (changed=2)
Failed:    3
------------
Total states run:    12
Total run time:   1.744 s
```

Please clarify, what should I do in oder to have ```dockerng``` running?

**Comment by vitalyisaev2** [comment]
I noticed that `dockerng` requires at least ```docker-py==1.4.0```. It's a big pity because I belive that many people have ```docker <= 1.6``` (this imposes restrictions to the docker-py version) in production, and they do need to move from ```dockerio``` to ```dockerng```. 

Is it really neccessary to have such an up-to-date version of Python Docker client?

**Comment by jfindlay** [comment]
@vitalyisaev2, thanks for the report.  Yes, unfortunately, docker's API is not very stable from version to version, so for sanity we need to check for versions.  `dockerio` is not going to be removed for a few more releases, so you should have time to upgrade.

**Comment by vitalyisaev2** [comment]
@jfindlay thank you

**Comment by ticosax** [comment]
While dockerng requires docker-py>=1.4, I think you can still use docker 1.6.
Did you tried ?

**Comment by vitalyisaev2** [comment]
@ticosax , I did

Docker:
```
(venv)➜  /tmp  dpkg -l | grep docker | grep ii
ii  lxc-docker                                           1.6.0                                    amd64        Linux container runtime
ii  lxc-docker-1.6.0                                     1.6.0                                    amd64        Linux container runtime
```

Docker-py:
```python
(venv)➜  /tmp  echo "docker-py==1.4" > requirements.txt
(venv)➜  /tmp  pip install -r requirements.txt
Downloading/unpacking docker-py==1.4 (from -r requirements.txt (line 1))
  Downloading docker-py-1.4.0.tar.gz (53kB): 53kB downloaded
  Running setup.py (path:/tmp/venv/build/docker-py/setup.py) egg_info for package docker-py
    
    warning: no files found matching 'requirements3.txt'
Downloading/unpacking requests>=2.5.2 (from docker-py==1.4->-r requirements.txt (line 1))
  Downloading requests-2.8.1-py2.py3-none-any.whl (497kB): 497kB downloaded
Downloading/unpacking six>=1.4.0 (from docker-py==1.4->-r requirements.txt (line 1))
  Downloading six-1.10.0-py2.py3-none-any.whl
Downloading/unpacking websocket-client>=0.32.0 (from docker-py==1.4->-r requirements.txt (line 1))
  Downloading websocket_client-0.34.0.tar.gz (193kB): 193kB downloaded
  Running setup.py (path:/tmp/venv/build/websocket-client/setup.py) egg_info for package websocket-client
    
Downloading/unpacking backports.ssl-match-hostname (from websocket-client>=0.32.0->docker-py==1.4->-r requirements.txt (line 1))
  Downloading backports.ssl_match_hostname-3.4.0.2.tar.gz
  Running setup.py (path:/tmp/venv/build/backports.ssl-match-hostname/setup.py) egg_info for package backports.ssl-match-hostname
    
Installing collected packages: docker-py, requests, six, websocket-client, backports.ssl-match-hostname
  Running setup.py install for docker-py
    
    warning: no files found matching 'requirements3.txt'
  Running setup.py install for websocket-client
    changing mode of build/scripts-2.7/wsdump.py from 664 to 775
    
    changing mode of /tmp/venv/bin/wsdump.py to 775
  Running setup.py install for backports.ssl-match-hostname
    
Successfully installed docker-py requests six websocket-client backports.ssl-match-hostname
Cleaning up...
(venv)➜  /tmp  python
Python 2.7.8 (default, Jun 18 2015, 18:54:19) 
[GCC 4.9.1] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from docker import Client
>>> c = Client(base_url='unix://var/run/docker.sock')
>>> c.images()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/venv/local/lib/python2.7/site-packages/docker/client.py", line 404, in images
    True)
  File "/tmp/venv/local/lib/python2.7/site-packages/docker/clientbase.py", line 119, in _result
    self._raise_for_status(response)
  File "/tmp/venv/local/lib/python2.7/site-packages/docker/clientbase.py", line 114, in _raise_for_status
    raise errors.NotFound(e, response, explanation=explanation)
docker.errors.NotFound: 404 Client Error: Not Found ("client and server don't have same version (client : 1.19, server: 1.18)")
```

**Comment by vitalyisaev2** [comment]
@ticosax , wait a minute... it seems to work:

```python
>>> from docker import AutoVersionClient
>>> cli = AutoVersionClient(base_url='unix://var/run/docker.sock')
>>> cli.images()
(...a lot of output...)
```

**Comment by ticosax** [comment]
I'm not sure we need a PR,
you can use pass `version='auto'` through configuration.

https://github.com/saltstack/salt/blob/develop/salt/modules/dockerng.py#L645

**Comment by vitalyisaev2** [comment]
@ticosax Do you mean setting this in `/etc/salt/minion`:
```yaml
docker.version: auto
```

Also It would be nice to see these updates in ```2015.8``` branch distributed with the Linux packages. Because in my case this function looks like this:

```python
def _get_client(timeout=None):
    '''
    Obtains a connection to a docker API (socket or URL) based on config.get
    mechanism (pillar -> grains)
    By default it will use the base docker-py defaults which
    at the time of writing are using the local socket and
    the 1.4 API
    Set those keys in your configuration tree somehow:
        - docker.url: URL to the docker service
        - docker.version: API version to use (default: "auto")
    '''
    if 'docker.client' not in __context__:
        client_kwargs = {}
        for key, val in (('base_url', 'docker.url'),
                         ('version', 'docker.version')):
            param = __salt__['config.get'](val, NOTSET)
            if param is not NOTSET:
                client_kwargs[key] = param

        if 'base_url' not in client_kwargs and 'DOCKER_HOST' in os.environ:
            # Check if the DOCKER_HOST environment variable has been set
            client_kwargs['base_url'] = os.environ.get('DOCKER_HOST')

        if 'version' not in client_kwargs:
            client_kwargs['version'] = 'auto'

        __context__['docker.client'] = docker.Client(**client_kwargs)

    # Set a new timeout if one was passed
    if timeout is not None and __context__['docker.client'].timeout != timeout:
        __context__['docker.client'].timeout = timeout
```

```bash
root@wks-isaev:~# dpkg -l | grep salt-minion
ii  salt-minion                      2015.8.1+ds-1                   all          client package for salt, the distributed remote execution system
```


Are there any plans to release bugfixes?

**Comment by jfindlay** [comment]
@ticosax, @vitalyisaev2, I am unsure what the status on this issue is.  Do we need to fix anything in salt's code or documentation?

**Comment by vitalyisaev2** [comment]
@jfindlay , I'm closing this bug because it's fixed in upstream master branch, but yet not released. If it's possible, please initiate the release of bugfixes in official packages. Until this is done, peolple who use  ```Docker API<=1.18``` (equals to ```docker<=1.6```) won't be able to use long-awaited `dockerng` module.

**Comment by jfindlay** [comment]
@vitalyisaev2, we regularly create new releases on our release branches.  2015.8.2 is going to be released soon and develop will be forked in a few months to be come the Boron release.
