### ISSUE TITLE
Unable to start salt-minion :AttributeError: 'IOLoop' object has no attribute 'make_current'

### ISSUE THREAD

**Issue by Djiit** [saltstack/salt#28403]
Hi, 

I can't start a fresh install of salt-minion on a RedHat 6.5.

Here is the output of a --versions :

```
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
           Mako: 0.3.4
         PyYAML: 3.10
          PyZMQ: 2.2.0
         Python: 2.6.6 (r266:84292, Sep  4 2013, 07:46:00)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.1
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: redhat 6.5 Santiago
        machine: x86_64
        release: 2.6.32-431.el6.x86_64
         system: Red Hat Enterprise Linux Server 6.5 Santiago
```

And here is the error I get :

```
2015-10-29 14:55:25,178 [tornado.application][ERROR   ][5132] Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.6/site-packages/salt/crypt.py", line 432, in _authenticate
    creds = yield self.sign_in()
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib64/python2.6/site-packages/tornado/concurrent.py", line 214, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.6/site-packages/salt/crypt.py", line 503, in sign_in
    timeout=timeout
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib64/python2.6/site-packages/tornado/concurrent.py", line 214, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.6/site-packages/salt/transport/zeromq.py", line 218, in send
    ret = yield self._uncrypted_transfer(load, tries=tries, timeout=timeout)
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib64/python2.6/site-packages/tornado/concurrent.py", line 214, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 230, in wrapper
    yielded = next(result)
  File "/usr/lib/python2.6/site-packages/salt/transport/zeromq.py", line 209, in _uncrypted_transfer
    ret = yield self.message_client.send(self._package_load(load), timeout=timeout)
  File "/usr/lib/python2.6/site-packages/salt/transport/zeromq.py", line 833, in send
    send_timeout = self.io_loop.call_later(timeout, self.timeout_message, message)
AttributeError: 'IOLoop' object has no attribute 'call_later'
2015-10-29 14:56:54,801 [salt.log.setup   ][ERROR   ][5230] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'IOLoop' object has no attribute 'make_current'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 331, in salt_call
    client.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/call.py", line 43, in run
    caller = salt.cli.caller.Caller.factory(self.config)
  File "/usr/lib/python2.6/site-packages/salt/cli/caller.py", line 78, in factory
    return ZeroMQCaller(opts, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/cli/caller.py", line 269, in __init__
    super(ZeroMQCaller, self).__init__(opts)
  File "/usr/lib/python2.6/site-packages/salt/cli/caller.py", line 101, in __init__
    self.minion = salt.minion.SMinion(opts)
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 518, in __init__
    self.gen_modules(initial_load=True)
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 529, in gen_modules
    pillarenv=self.opts.get('pillarenv'),
  File "/usr/lib/python2.6/site-packages/salt/pillar/__init__.py", line 52, in get_pillar
    pillar=pillar, pillarenv=pillarenv)
  File "/usr/lib/python2.6/site-packages/salt/pillar/__init__.py", line 140, in __init__
    self.channel = salt.transport.Channel.factory(opts)
  File "/usr/lib/python2.6/site-packages/salt/transport/__init__.py", line 29, in factory
    return ReqChannel.factory(opts, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/transport/client.py", line 22, in factory
    sync = SyncWrapper(AsyncReqChannel.factory, (opts,), kwargs)
  File "/usr/lib/python2.6/site-packages/salt/utils/async.py", line 58, in __init__
    with current_ioloop(self.io_loop):
  File "/usr/lib64/python2.6/contextlib.py", line 16, in __enter__
    return self.gen.next()
  File "/usr/lib/python2.6/site-packages/salt/utils/async.py", line 30, in current_ioloop
    io_loop.make_current()
AttributeError: 'IOLoop' object has no attribute 'make_current'

```

Any ideas on  what might be causing this ?

Thanks for your help.

**Comment by syedaali** [comment]
I updated to 2015.8.1 from 2015.5.3 to solve the problem shown here https://github.com/saltstack/salt/issues/26493 and now I am unable to use salt as well. The error I am getting is:

salt-run manage.versions
'ZMQIOLoop' object has no attribute 'call_later'

**Comment by martinrm77** [comment]
update your ZMQ installation to 4 and all is good

**Comment by syedaali** [comment]
Here is what I have right now:

$ sudo dpkg --list | grep -i zmq
ii  libzmq3:amd64                    4.0.4+dfsg-2                     amd64        lightweight messaging kernel (shared library)
ii  python-zmq                       14.0.1-1build2                   amd64        Python bindings for 0MQ library

**Comment by syedaali** [comment]
salt --versions
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 3.2
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 2.0.2
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-66-generic
         system: Ubuntu 14.04 trusty

**Comment by martinrm77** [comment]
Syedali: You have zeromq 4 so thats not your problem. It did fix the issue on my RHEL/CentOS 6 installation after upgrading to 2015.8.1

**Comment by Djiit** [comment]
Hi, 

The trick worked for me. Many Thanks!
Is there a place where we should note it for others users ? Like a FAQ or something... I'll be glad to contribute to it.

I'm not closing the issue since @syedaali 's problem is not fixed.

**Comment by syedaali** [comment]
I terminated my AWS instance running salt-master, and created a new
instance. On the new instance I installed 2015.8.1 and it seems to work
now. Previously I was running 2015.5.3 and I upgraded to 2015.8.1, so I
guess the upgrade process is broken. I even uninstalled 2015.5.3 and
installed 2015.8.1, but that did not help. I had to start with a fresh
installation of Ubuntu 14.04 and install only 2015.8.1 to get it to work.

**Comment by cachedout** [comment]
@syedaali Could you please clarify what steps you took to upgrade Salt? It's possible there are still bugs to be worked out there. Thanks.

**Comment by syedaali** [comment]
Here is how I had installed 2015.5.3 master/minion:

sudo add-apt-repository ppa:saltstack/salt -y
sudo apt-get install python-software-properties -y
sudo apt-get install software-properties-common -y
sudo apt-get update -y
sudo apt-get install salt-master -y
sudo apt-get install salt-minion -y

And then to upgrade to 2015.8.1, here is what I did on the master/minion:

wget -O -
https://repo.saltstack.com/apt/ubuntu/ubuntu14/latest/SALTSTACK-GPG-KEY.pub
| sudo apt-key add -
echo "deb http://repo.saltstack.com/apt/ubuntu/ubuntu14/latest trusty main"
>> /etc/apt/sources.list
sudo apt-get update -y
sudo apt-get install salt-master -y
sudo apt-get install salt-minion -y

The master/minion would start as a service, but I could not run any
commands, I was getting the IOLoop error.

I then uninstalled 2015.8.1, but then I was back to the original bug of
being unable to use PIP.
So I uninstalled 2015.5.3, and then installed 2015.8.1, but that did not
work, I was back to the IOLoop error.

I then went ahead and terminated the AWS salt instance, and then created a
new AWS Ubuntu 14.04 instance, and installed just 2015.8.1. This seems to
have solved the problem.

**Comment by vmspike** [comment]
One of the possible reasons is salt cache, minion upgrade process doesn't clean cache (it seems a bug). Cache cleaning can help:
`rm -rf /var/cache/salt/minion/*`

**Comment by rominf** [comment]
Thank you, @vmspike, cache cleaning helped me!

**Comment by jlkaiser** [comment]
Just in case the above doesn't solve it for someon. 

I encountered the same problem. However, it was because I was using versions of tornado and py-zmq that were incompatible. From google Tornado group:

"pyzmq <= 13.0 has compatibility issues with tornado >= 3.0. If you use pyzmq and tornado of a similar vintage (pyzmq 2.x + tornado 2.x, or pyzmq >= 13 + tornado >= 3), you should be fine.

-MinRK"

Once I updated pyzmq to match the latest tornado. It worked. 

Thanks,

Joe

**Comment by yueyongyue** [comment]
martinrm77  is ok

**Comment by easyljy** [comment]
I have same issue on one server when upgrade salt-minion from 2015.5.10 to 2016.3.3 on CentOS 6.4.
It's fixed by reinstalling zeromq3 and salt-minion.
