### ISSUE TITLE
state.sls UnicodeDecodeError

### ISSUE THREAD

**Issue by ColorFuzzy** [saltstack/salt#28476]
- command
===============================
`salt "nginx-1" state.sls app.cc.code test=True`

- error
===============================
    [ERROR   ] An un-handled exception was caught by salt's global exception handler:
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 292: ordinal not in range(128)
    Traceback (most recent call last):
      File "/usr/bin/salt", line 10, in <module>
        salt_main()
      File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 454, in salt_main
        client.run()
      File "/usr/lib/python2.7/dist-packages/salt/cli/salt.py", line 202, in run
        self._output_ret(ret_, out)
      File "/usr/lib/python2.7/dist-packages/salt/cli/salt.py", line 301, in _output_ret
        salt.output.display_output(ret, out, self.config)
      File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 86, in display_output
        display_data = try_printout(data, out, opts)
      File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 39, in try_printout
        return get_printout(out, opts)(data).rstrip()
      File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 85, in output
        return _format_host(host, hostdata)[0]
      File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 116, in _format_host
        .format(hcolor, err, colors)))
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 292: ordinal not in range(128)
    Traceback (most recent call last):
      File "/usr/bin/salt", line 10, in <module>
        salt_main()
      File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 454, in salt_main
        client.run()
      File "/usr/lib/python2.7/dist-packages/salt/cli/salt.py", line 202, in run
        self._output_ret(ret_, out)
      File "/usr/lib/python2.7/dist-packages/salt/cli/salt.py", line 301, in _output_ret
        salt.output.display_output(ret, out, self.config)
      File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 86, in display_output
        display_data = try_printout(data, out, opts)
      File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 39, in try_printout
        return get_printout(out, opts)(data).rstrip()
      File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 85, in output
        return _format_host(host, hostdata)[0]
      File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 116, in _format_host
        .format(hcolor, err, colors)))
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 292: ordinal not in range(128)

- Fix this like bellow OR find a better way?
===============================
file: **salt/salt/output/highstate.py**
replace(line 115): `hstrs.append((u'{0}----------\n    {1}{2[ENDC]}'`
                        to: `hstrs.append((u'{0}----------\n    {1!r}{2[ENDC]}'`
**new output**:

    nginx-1:
    Data failed to compile:
    ----------
    'Rendering SLS \'base:app.cc.code\' failed: Jinja variable \'dict object\' has no attribute \'git\'\n/var/cache/salt/minion/files/base/variable/git.sls(1):\n---\n{% set git_https_user = pillar["git"]["https-user"] %}    <======================\n{% set git_https_pass = pillar["git"]["https-pass"] %}\n\n{# \xe4\xb8\xad\xe6\x96\x87 #}\n{% macro sync_code(app_name, code_folder, https_clone_url, git_revision) %}\ninclude:\n[...]\n---'

**reason**: 
- a syntax error occurs in salt file
- return error string contains part of the salt file for debug usage
- **\xe4\xb8\xad\xe6\x96\x87** in return string(Chinese comment in salt file)

- versions
===============================
    Salt Version:
               Salt: 2015.8.0

    Dependency Versions:
             Jinja2: 2.7.2
           M2Crypto: Not Installed
               Mako: 0.9.1
             PyYAML: 3.10
              PyZMQ: 14.4.0
             Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.4
               cffi: Not Installed
           cherrypy: 3.2.2
           dateutil: 1.5
              gitdb: 0.5.4
          gitpython: Not Installed
              ioflo: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.3.0
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: 0.8.2
            timelib: Not Installed

    System Versions:
               dist: Ubuntu 14.04 trusty
            machine: x86_64
            release: 3.13.0-65-generic
             system: Ubuntu 14.04 trusty

**Comment by jfindlay** [comment]
@ColorFuzzy, thanks for the report.  The `{1!r}` representation causes problems with python 3 support, although I don't remember what the problem is.  Salt has a utility `sdecode` to convert platform-specific encodings into utf-8.  All of this should be much less of a problem when we migrate to python 3 as its strings are unicode by default.

**Comment by ColorFuzzy** [comment]
@jfindlay `sdecode` is a really nice tool to handle this type of issue,
thanks!
