### ISSUE TITLE
KeyError 'git.config_set'

### ISSUE THREAD

**Issue by bmcorser** [saltstack/salt#28554]
Trying to write a state that sets Git config values, but I'm getting a KeyError suggesting there's no such state `git.config_set`.

My state looks roughly like this:
``` yaml
set_repo_username:
  git.config_set:
    - repo: /path/to/repo
    - name: user.name
    - value: My Git User
    - user: myuser
    - require:
      - cmd: create_my_repo
```
The function appears to be available on the minion:
``` shell
$ salt minion-x sys.list_functions|grep config_set
    - git.config_set
```
However, when I try to run the state I end up with a KeyError:
```
minion-x:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1161, in _thread_return
        return_data = func(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 681, in sls
        ret = st_.state.call_high(high_)
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2067, in call_high
        ret = dict(list(disabled.items()) + list(self.call_chunks(chunks).items()))
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1623, in call_chunks
        running = self.call_chunk(low, running, chunks)
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1769, in call_chunk
        self._mod_init(low)
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 612, in _mod_init
        self.states['{0}.{1}'.format(low['state'], low['fun'])]  # pylint: disable=W0106
      File "/usr/lib/python2.7/dist-packages/salt/utils/lazy.py", line 90, in __getitem__
        raise KeyError(key)
    KeyError: 'git.config_set'
```

Master:
```
                  Salt: 2015.5.3
                Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1trusty1
```

Minion:
```
salt-minion 2015.5.3 (Lithium)
```

**Comment by rallytime** [comment]
Hi @bmcorser - I am not sure what the `cmd: create_my_repo` does, but is git installed on the machine that you're running this state on? Or perhaps there is a dependency missing that is involved with the required state?  This looks like a duplicate of #26115, #27619, #26882, and #26454.

This stacktrace is caused by a regression in the state compiler in 2015.5.3. However, this bug is fixed at the HEAD of the 2015.5 branch, and will be available in the upcoming 2015.5.7 release. It is also fixed in 2015.8.0 and newer.

The way to get around the stacktrace is to install whatever missing dependency is causing the stacktrace. (Previous behavior was to warn you that you're missing something and the state would fail, instead of stack tracing.)

**Comment by bmcorser** [comment]
I upgraded to 2015.8.1 to get `temp.file` and changed this back to the above. It worked fine. Closing this.

**Comment by rallytime** [comment]
:+1:
