### ISSUE TITLE
Salt prevents catching urllib3 exceptions

### ISSUE THREAD

**Issue by sjmh** [saltstack/salt#28553]
Salt seems to be doing some trickery that's preventing me ( or actually, python-etcd ) from catching urllib3 exceptions.

A small script ( not salt ):

```
import etcd
c = etcd.Client('127.0.0.1', 4001)
print c.read('/test1', wait=True, timeout=2)
```

And when we run it:

```
[root@alpha utils]# /tmp/etcd_watch.py
Traceback (most recent call last):
  File "/tmp/etcd_watch.py", line 5, in <module>
    print c.read('/test1', wait=True, timeout=2)
  File "/usr/lib/python2.6/site-packages/etcd/client.py", line 481, in read
    timeout=timeout)
  File "/usr/lib/python2.6/site-packages/etcd/client.py", line 788, in api_execute
    cause=e
etcd.EtcdConnectionFailed: Connection to etcd failed due to ReadTimeoutError("HTTPConnectionPool(host='127.0.0.1', port=4001): Read timed out.",)
```

Ok, let's catch that bugger:

```
#!/usr/bin/python

import etcd
c = etcd.Client('127.0.0.1', 4001)

try:
  print c.read('/test1', wait=True, timeout=2)
except etcd.EtcdConnectionFailed:
  print 'connect failed'
```
Run it:
```
[root@alpha _modules]# /tmp/etcd_watch.py
connect failed
```

Looks good - it's all working python.  So what's the issue?  I have this in an execution module:

```
[root@alpha _modules]# cat sjmh.py
import etcd

def test():
  c = etcd.Client('127.0.0.1', 4001)
  try:
    return c.read('/test1', wait=True, timeout=2)
  except etcd.EtcdConnectionFailed:
    return False
```

And when we run that:

```
[root@alpha _modules]# salt 'alpha' sjmh.test
alpha:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/salt/minion.py", line 1173, in _thread_return
        return_data = func(*args, **kwargs)
      File "/var/cache/salt/minion/extmods/modules/sjmh.py", line 5, in test
        c.read('/test1', wait=True, timeout=2)
      File "/usr/lib/python2.6/site-packages/etcd/client.py", line 481, in read
        timeout=timeout)
      File "/usr/lib/python2.6/site-packages/etcd/client.py", line 769, in api_execute
        _ = response.data
      File "/usr/lib/python2.6/site-packages/urllib3/response.py", line 150, in data
        return self.read(cache_content=True)
      File "/usr/lib/python2.6/site-packages/urllib3/response.py", line 218, in read
        raise ReadTimeoutError(self._pool, None, 'Read timed out.')
    ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=4001): Read timed out.
```

Hrm, that's weird.  etcd's read should have returned etcd.EtcdConnectionFailed.

So, let's look at it further.  Our module is now this:

```
import etcd

def test():
  c = etcd.Client('127.0.0.1', 4001)
  try:
    return c.read('/test1', wait=True, timeout=2)
  except Exception as e:
    return str(type(e))
```
And we get:
```
[root@alpha _modules]# salt 'alpha' sjmh.test
alpha:
    <class 'urllib3.exceptions.ReadTimeoutError'>
```

Ok, so it threw a ReadTimeoutError, so let's catch that.  The newest version of our module:
```
import etcd
import urllib3.exceptions

def test():
  c = etcd.Client('127.0.0.1', 4001)
  try:
    c.read('/test1', wait=True, timeout=2)
  except urllib3.exceptions.ReadTimeoutError as e:
    return 'caught ya!'
  except Exception as e:
    return str(type(e))
```
And our test..
```
[root@alpha _modules]# salt 'alpha' sjmh.test
alpha:
    <class 'urllib3.exceptions.ReadTimeoutError'>
```
Er, wait, what? Why didn't we catch that?  Exceptions work, right.. ?

How about if we try and catch the base class from urllib3..

```
[root@alpha _modules]# cat sjmh.py
import etcd
import urllib3.exceptions

def test():
  c = etcd.Client('127.0.0.1', 4001)
  try:
    c.read('/test1', wait=True, timeout=2)
  except urllib3.exceptions.HTTPError:
    return 'got you this time!'
```
Hope and pray..

```
[root@alpha _modules]# salt 'alpha' sjmh.test
alpha:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/salt/minion.py", line 1173, in _thread_return
        return_data = func(*args, **kwargs)
      File "/var/cache/salt/minion/extmods/modules/sjmh.py", line 7, in test
        c.read('/test1', wait=True, timeout=2)
      File "/usr/lib/python2.6/site-packages/etcd/client.py", line 481, in read
        timeout=timeout)
      File "/usr/lib/python2.6/site-packages/etcd/client.py", line 769, in api_execute
        _ = response.data
      File "/usr/lib/python2.6/site-packages/urllib3/response.py", line 150, in data
        return self.read(cache_content=True)
      File "/usr/lib/python2.6/site-packages/urllib3/response.py", line 218, in read
        raise ReadTimeoutError(self._pool, None, 'Read timed out.')
    ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=4001): Read timed out.
```

BLAST YE!   Ok, let's try a different method that returns a different etcd Exception.  Our module now looks like this:
```
import etcd

def test():
  c = etcd.Client('127.0.0.1', 4001)
  try:
    c.delete('/')
  except etcd.EtcdRootReadOnly:
    return 'got you this time!'
```
And our run:
```
[root@alpha _modules]# salt 'alpha' sjmh.test
alpha:
    got you this time!
```

And here was my final test.  A module that I can either run from the command line, or from salt:
```
import etcd
import urllib3

def test():
  c = etcd.Client('127.0.0.1', 4001)
  try:
    c.read('/test1', wait=True, timeout=2)
  except urllib3.exceptions.ReadTimeoutError:
    return 'got you this time!'
  except etcd.EtcdConnectionFailed:
    return 'cant get away from me!'
  except etcd.EtcdException:
    return 'oh no you dont'
  except urllib3.exceptions.HTTPError:
    return 'get back here!'
  except Exception as e:
    return 'HOW DID YOU GET HERE? {0}'.format(type(e))

if __name__ == "__main__":
  print test()
```

And our two tests:

Normal python:
```
[root@alpha _modules]# python ./sjmh.py
cant get away from me!
```

Through salt:
```
[root@alpha _modules]# salt 'alpha' sjmh.test
alpha:
    HOW DID YOU GET HERE? <class 'urllib3.exceptions.ReadTimeoutError'>
```

So, we can catch exceptions from etcd that it throws.  But, while we normally are able to catch the urllib3 ReadTimeoutError when we run python-etcd by it's lonesome, when we run it through salt, nothing seems to be able to catch that urllib3 exception, except a blanket 'Exception' clause.

I can do that, but I'm really curious as to what the heck salt is doing that's making it so that an exception is uncatchable.  I've never seen this before when working with python, so I'd be curious as to how it's happening and if we can fix it.

**Comment by cachedout** [comment]
Are you positive that you have the same Python path in both cases? This seems a lot like Salt is running under a different version of Python than your test case is and pulling in a different version of the etcd module. Salt isn't doing anything under the hood here to catch and rewrite exceptions on the order of what you're seeing here.

**Comment by sjmh** [comment]
@cachedout - Yeah, it's the same python and same etcd module -

With this:

```
import etcd
import urllib3
import sys
import logging

log = logging.getLogger()
log.setLevel(logging.DEBUG)

h = logging.StreamHandler()
log.addHandler(h)

def test():
  c = etcd.Client('127.0.0.1', 4001)
  try:
    c.read('/test1', wait=True, timeout=2)
  except urllib3.exceptions.ReadTimeoutError:
    return 'got you this time!'
  except etcd.EtcdConnectionFailed:
    log.debug(etcd.__file__)
    log.debug(sys.executable)
    return 'cant get away from me!'
  except etcd.EtcdException:
    return 'oh no you dont'
  except urllib3.exceptions.HTTPError:
    return 'get back here!'
  except Exception as e:
    log.debug(etcd.__file__)
    log.debug(sys.executable)
    return 'HOW DID YOU GET HERE? {0}'.format(type(e))

if __name__ == "__main__":
  print test()
```

Normal:
```
[root@alpha _modules]# python ./sjmh.py
New etcd client created for 127.0.0.1:4001/v2
Issuing read for key /test1 with args {'timeout': 2, 'wait': True}
Starting new HTTP connection (1): 127.0.0.1
"GET /v2/keys/test1?wait=true HTTP/1.1" 200 None
Request to server http://127.0.0.1:4001 failed: ReadTimeoutError("HTTPConnectionPool(host='127.0.0.1', port=4001): Read timed out.",)
Reconnection disabled, giving up.
/usr/lib/python2.6/site-packages/etcd/__init__.pyc
/usr/bin/python
cant get away from me!
```

Via salt:
```
[DEBUG   ] New etcd client created for 127.0.0.1:4001/v2
New etcd client created for 127.0.0.1:4001/v2
[DEBUG   ] Issuing read for key /test1 with args {'timeout': 2, 'wait': True}
Issuing read for key /test1 with args {'timeout': 2, 'wait': True}
[INFO    ] Starting new HTTP connection (1): 127.0.0.1
Starting new HTTP connection (1): 127.0.0.1
[DEBUG   ] "GET /v2/keys/test1?wait=true HTTP/1.1" 200 None
"GET /v2/keys/test1?wait=true HTTP/1.1" 200 None
[ERROR   ] Unexpected request failure, re-raising.
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/etcd/client.py", line 769, in api_execute
    _ = response.data
  File "/usr/lib/python2.6/site-packages/urllib3/response.py", line 150, in data
    return self.read(cache_content=True)
  File "/usr/lib/python2.6/site-packages/urllib3/response.py", line 218, in read
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=4001): Read timed out.
Unexpected request failure, re-raising.
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/etcd/client.py", line 769, in api_execute
    _ = response.data
  File "/usr/lib/python2.6/site-packages/urllib3/response.py", line 150, in data
    return self.read(cache_content=True)
  File "/usr/lib/python2.6/site-packages/urllib3/response.py", line 218, in read
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=4001): Read timed out.
[DEBUG   ] /usr/lib/python2.6/site-packages/etcd/__init__.pyc
/usr/lib/python2.6/site-packages/etcd/__init__.pyc
[DEBUG   ] /usr/bin/python2.6
/usr/bin/python2.6
```

Making sure the two binaries are the same:
```
[root@alpha _modules]# md5sum /usr/bin/python2.6
ede32736334eafa86e21cbf5ba3f4365  /usr/bin/python2.6
[root@alpha _modules]# md5sum /usr/bin/python
ede32736334eafa86e21cbf5ba3f4365  /usr/bin/python
```

Even if it wasn't, I still don't get how it can show that the class of the uncaught exception is urllib3.exceptions.ReadTimeoutError and not get caught by the upper 'except' clause that is specifically trying to catch that exception.  I don't know the inner workings of how the 'try' clause determines which case matches - I thought it was based off the __class__ of the exception and it doing a comparison.

And just to make sure we're really getting the right 'exception' from urllib3, I added some '__class__.__base__' log outputs and I get this:

```
[DEBUG   ] <class 'urllib3.exceptions.ReadTimeoutError'>
<class 'urllib3.exceptions.ReadTimeoutError'>
[DEBUG   ] <class 'urllib3.exceptions.TimeoutError'>
<class 'urllib3.exceptions.TimeoutError'>
[DEBUG   ] <class 'urllib3.exceptions.HTTPError'>
<class 'urllib3.exceptions.HTTPError'>
[DEBUG   ] <type 'exceptions.Exception'>
<type 'exceptions.Exception'>
[DEBUG   ] <type 'exceptions.BaseException'>
<type 'exceptions.BaseException'>
[DEBUG   ] <type 'object'>
<type 'object'>
```

**Comment by sjmh** [comment]
@cachedout - I was finally able to catch the dang thing.

```
import etcd
import urllib3.exceptions
from urllib3.exceptions import ReadTimeoutError

def test():
  c = etcd.Client('127.0.0.1', 4001)
  try:
    c.read('/test1', wait=True, timeout=2)
  except urllib3.exceptions.ReadTimeoutError:
    return 'caught 1'
  except urllib3.exceptions.HTTPError:
    return 'caught 2'
  except ReadTimeoutError:
    return 'caught 3'
  except etcd.EtcdConnectionFailed as ex:
    return 'cant get away from me!'
  except Exception as ex:
    return 'HOW DID YOU GET HERE? {0}'.format(type(ex))

if __name__ == "__main__":
  print test()
```

And
```
[root@alpha _modules]# salt 'alpha' sjmh.test
alpha:
    caught 3
```

Doesn't make alot of sense - but I can at least catch the thing now.

**Comment by sjmh** [comment]
@cachedout - Looks like this is just a result of Salt using the requests module.  It's rewriting the urllib3 exceptions into requests.packages.urllib3.exceptions and etcd doesn't look for the exceptions there.  Going to close this out, as it's not a Salt issue.

**Comment by sjmh** [comment]
As a follow up - this also appears to be fixed in newer versions of requests.
