### ISSUE TITLE
Salt+dockerng appear to ignore docker daemon certificate chain (w/self-signed certs)

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#28566]
I have the following problem - I'm trying to show off Docker+Salt Stack, but I'm ran into some issues trying to run both the docker daemon and salt minion inside one container. I guess they just didn't get along :trollface: 

But the Minion was perfectly happy in a docker container, so I had an even better idea - use the [docker](https://hub.docker.com/_/docker/) docker image and then just link up my minion and docker-in-docker container, configure the [docker.url in the minion](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.dockerng.html#configuration-options), and be happy.

Unfortunately I'm still sad.

Here's some relevant information:

**Minion**:

```
docker exec -t example_master_1 salt 'testminion' cmd.run "salt-minion --versions-report"                                                                                                                                                                                        7:05:23
testminion:
    Salt Version:
               Salt: 2015.8.1

    Dependency Versions:
             Jinja2: 2.6
           M2Crypto: 0.21.1
               Mako: Not Installed
             PyYAML: 3.10
              PyZMQ: 13.1.0
             Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
               RAET: Not Installed
            Tornado: 4.3b2
                ZMQ: 3.2.3
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.1.10
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6
             pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: Not Installed
            timelib: Not Installed

    System Versions:
               dist: debian 7.8
            machine: x86_64
            release: 4.1.10-boot2docker
             system: debian 7.8
```

**Master**

```
docker exec -t example_master_1 salt 'testminion' cmd.run "salt-minion --versions-report"                                                                                                                                                                                        7:05:23
testminion:
    Salt Version:
               Salt: 2015.8.1

    Dependency Versions:
             Jinja2: 2.6
           M2Crypto: 0.21.1
               Mako: Not Installed
             PyYAML: 3.10
              PyZMQ: 13.1.0
             Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
               RAET: Not Installed
            Tornado: 4.3b2
                ZMQ: 3.2.3
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.1.10
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6
             pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: Not Installed
            timelib: Not Installed

    System Versions:
               dist: debian 7.8
            machine: x86_64
            release: 4.1.10-boot2docker
             system: debian 7.8
```

My docker-in-docker Dockerfile:

```
FROM docker:1.9-rc-dind

COPY domain.crt /etc/docker/certs.d/mysubdomain.mydomain.com:5000/ca.crt
```

My minion Dockerfile:

```
FROM debian:7

VOLUME ["/etc/salt/pki", "/var/cache/salt", "/var/logs/salt", "/etc/salt/master.d", "/srv/salt"]
ADD https://bootstrap.saltstack.com /usr/local/bin/install_salt.sh
RUN chmod +x /usr/local/bin/install_salt.sh
RUN /usr/local/bin/install_salt.sh -d -P git v2015.8.1
RUN echo "testminion" > /etc/salt/minion_id
RUN sed -i "s/\#master: salt/master: testmaster/" /etc/salt/minion
RUN sed -i "s/\#log_level: warning/log_level: debug/" /etc/salt/minion
RUN echo "docker.url: docker:2375" >> /etc/salt/minion
ENTRYPOINT /usr/bin/salt-minion
```

Master dockerfile:

```
FROM debian:7

VOLUME ["/etc/salt/pki", "/var/cache/salt", "/var/logs/salt", "/etc/salt/master.d", "/srv/salt"]
EXPOSE 4505 4506

ADD https://bootstrap.saltstack.com /usr/local/bin/install_salt.sh
RUN chmod +x /usr/local/bin/install_salt.sh
RUN /usr/local/bin/install_salt.sh -M -d -P git v2015.8.1
RUN echo "testmaster" > /etc/salt/minion_id
COPY start_salt.sh start_salt.sh
COPY start_me_up.sh start_me_up.sh
COPY states/* /srv/salt/
COPY files/ /srv/salt/
RUN sed -i "s/\#master: salt/master: 127.0.0.1/" /etc/salt/minion

ENTRYPOINT /start_me_up.sh
```

(`start_me_up.sh` is just this:

```
#!/bin/sh
/usr/bin/salt-minion -d
/usr/bin/salt-master
```

)

**top.sls**

```
base:
  'testminion':
      - docker
      - busybox
```

**docker.sls**

```
apt-transport-https:
    pkg:
         - installed

base:
  pkgrepo.managed:
    - humanname: Docker PPA
    - name: deb https://apt.dockerproject.org/repo debian-wheezy main
    - file: /etc/apt/sources.list.d/docker.list
    - keyid: 58118E89F3A912897C070ADBF76221572C52609D
    - keyserver: pgp.mit.edu

lxc-docker*:
    pkg:
        - purged

docker.io*:
    pkg:
        - purged

docker-engine:
    pkg:
        - installed

python-pip:
    pkg.installed

docker-py:
    pip.installed:
        - require:
            - pkg: python-pip
        - require_in:
            - bb
        - reload_modules: True

docker:
    service.running: []
```

`busybox.sls`:

```
include:
    - docker

bb:
    dockerng.image_present:
        - name: mysubdomain.mydomain.com:5000/busybox
        - require:
            - sls: docker
        - force: True
```

**Top Pillar**:

```
base:
    'testminion':
        - docker
```

**My Docker Pillar** :

```
# Note, I've tried http, and just mysubdomain.mydomain.com:5000 - nothing worked
docker-registries:
    https://mysubdomain.mydomain.com:5000/:
        username: softuser
        password: softpassword
```

My Docker compose:

```
master:
    build: master

minion:
    build: minion
    links:
        - master:testmaster
        - dind:docker

dind:
    build: test-dind
    privileged: true
```

And for the registry:

```
docker_hub:
    build: docker-hub
    ports:
        - "0.0.0.0:5000:5000"
    environment:
        REGISTRY_AUTH: htpasswd
        REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
        REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
```

And its Dockerfile

```
FROM registry:2

COPY certs/ /certs/
COPY auth/ /auth/
ENV REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt REGISTRY_HTTP_TLS_KEY=/certs/domain.key
ENV REGISTRY_AUTH=htpasswd REGISTRY_AUTH_HTPASSWD_REALM=Registry\ Realm REGISTRY_AUTH_HTPASSWD_AUTH=/auth/htpasswd
```

---

I think that's enough background data.

Now for how I know that it's not doing me right.

From my local docker (running under boot2docker on a mac), I can do:

```
$ docker login mysubdomain.mydomain.com:5000
User: someuser
Password: somepassword
Email:
WARNING: login credentials saved in /Users/waynew/.docker/config.json
Login Succeeded
$ docker pull busybox
$ docker tag busybox mysubdomain.mydomain.com:5000/busybox
$ docker push mysubdomain.mydomain.com:5000/busybox
# docker does its push thing
$ docker exec -it example_testminion_1 bash
root@testminion# docker -H docker:2375 mysubdomain.mydomain.com:5000
User: someuser
Password: somepassword
Email:
WARNING: login credentials saved in /root/.docker/config.json
Login Succeeded
root@testminion# docker -H docker:2375 pull mysubdomain.mydomain.com:5000/busybox
```

And everything is A-OK. However, if **instead** of doing the exec bash/enter thing, I simply run `state.highstate`... there is sadness :sob: 

```
testminion:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1036, in _thread_return
        return_data = func(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/dockerng.py", line 3602, in pull
        response = _image_wrapper('pull', repo_name, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/dockerng.py", line 569, in wrapper
        return wrapped(*args, **salt.utils.clean_kwargs(**kwargs))
      File "/usr/lib/python2.7/dist-packages/salt/modules/dockerng.py", line 872, in _image_wrapper
        registry=registry)
      File "/usr/local/lib/python2.7/dist-packages/docker/api/daemon.py", line 71, in login
        return self._result(response, json=True)
      File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 146, in _result
        self._raise_for_status(response)
      File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 142, in _raise_for_status
        raise errors.APIError(e, response, explanation=explanation)
    APIError: 500 Server Error: Internal Server Error ("invalid registry endpoint https://mysubdomain.mydomain.com:5000/v0/: unable to ping registry endpoint https://mysubdomain.mydomain.com:5000/v0/
    v2 ping attempt failed with error: Get https://mysubdomain.mydomain.com:5000/v2/: x509: certificate signed by unknown authority
     v1 ping attempt failed with error: Get https://mysubdomain.mydomain.com:5000/v1/_ping: x509: certificate signed by unknown authority. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry mysubdomain.mydomain.com:5000` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/mysubdomain.mydomain.com:5000/ca.crt")
```

That's not right at all. But it gets a bit weirder, and I didn't try this until just now. But if I login with the bash approach, instead of _that_ error, I get this error:

```
Encountered error pulling mysubdomain.mydomain.com:5000/busybox: Error occurred performing docker pull: Invalid repository name (mysubdomain.mydomain.com)
```

:confused: Huh?

So... am _I_ doing something wrong here, or is something off within salt/dockerng/docker?

**Comment by jfindlay** [comment]
@waynew, thanks for the report.  I am not very familiar with docker, but the best I can guess is that you have a misconfiguration somewhere.  Is it possible for you to try to narrow down on a simpler use case to isolate the problem?

@Ch3LL, @tsharpe, do you have any ideas?

**Comment by waynew** [comment]
That's what I thought - I couldn't find any examples of what saltstack expected for the docker url, but passing what I stuck in the url to docker's `-H` flag worked. So unless salt is changing up the URL, I'm not really sure.

The other thought is that maybe docker-py doesn't respect the same environment as the docker command line client. If that's the case then there definitely needs to be a way to set trusted certs from within Salt (may not be possible with docker-py yet?)
