### ISSUE TITLE
datasource_exists fails to create a new one but succeeds if datasource is already there

### ISSUE THREAD

**Issue by nickw8** [saltstack/salt#28583]
I am trying to write a state file to add a new datasource for wildfly 9.

Here is my state (I have removed sensative data and replaced it with <data name>):

```
CMDataSource:
  jboss7.datasource_exists:
    - recreate: False
    - datasource_properties:
        driver-name: sqljdbc4.jar
        connection-url: 'jdbc:sqlserver://<host>:1433;DatabaseName=<DB Name>'
        jndi-name: 'java:/CMDataSource'
        user-name: <user>
        password: <password>
        use-java-context: True
    - jboss_config: 
        cli_path: '/opt/wildfly/bin/jboss-cli.sh'
        controller: <host ip>:9990
        cli_user: 'wildfly-admin'
        cli_password: '<password>'
```

When I run the state against the wildfly server to create the datasource it fails with this error:

```
ID: CMDataSource
    Function: jboss7.datasource_exists
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1561, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/states/jboss7.py", line 129, in datasource_exists
                  ds_result = __salt__['jboss7.read_datasource'](jboss_config=jboss_config, name=name)
                File "/usr/lib/python2.7/site-packages/salt/modules/jboss7.py", line 243, in read_datasource
                  return __read_datasource(jboss_config, name)
                File "/usr/lib/python2.7/site-packages/salt/modules/jboss7.py", line 332, in __read_datasource
                  operation_result = __salt__['jboss7_cli.run_operation'](jboss_config, operation)
                File "/usr/lib/python2.7/site-packages/salt/modules/jboss7_cli.py", line 114, in run_operation
                  cli_result['err_code'] = match.group(1)
              AttributeError: 'NoneType' object has no attribute 'group'
     Started: 12:27:24.778509
    Duration: 1724.338 ms
     Changes:   
```

But if I manually create the datasource on the server and run the same state, it succeeds with the following output:

```
ID: CMDataSource
    Function: jboss7.datasource_exists
      Result: True
     Comment: Datasource not changed.
     Started: 12:36:56.099918
    Duration: 4780.935 ms
     Changes:   
```

Which to me indicates that my state is set up right. What am I missing? Is it because I am using Wildfly 9?

Thanks

**Comment by nickw8** [comment]
Also
```
salt '<host>' jboss7.deploy '{"cli_path": "/opt/wildfly/bin/jboss-cli.sh", "controller": "<host ip>:9990", "cli_user": "wildfly-admin", "cli_password": "<password>"}' /tmp/sqljdbc4.jar
```
Works to deploy the sqljdbc4 driver but the following state also fails:
```
application_deployed:
  jboss7.deployed:
    - salt_source:
        source: salt://files/wildfly/sqljdbc4.jar
        target_file: '/tmp/sqljdbc4.jar'
    - jboss_config:
        cli_path: '/opt/wildfly/bin/jboss-cli.sh'
        controller: <host ip>:9990
        cli_user: 'wildfly-admin'
        cli_password: '<password>'
```
Fails with the following error:
```
          ID: application_deployed
    Function: jboss7.deployed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1561, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/states/jboss7.py", line 463, in deployed
                  comment = __append_comment(new_comment=get_artifact_comment, current_comment=comment)
                File "/usr/lib/python2.7/site-packages/salt/states/jboss7.py", line 727, in __append_comment
                  return current_comment+'\n'+new_comment
              TypeError: cannot concatenate 'str' and 'NoneType' objects
     Started: 12:54:14.996723
    Duration: 21.128 ms
     Changes:  
```

**Comment by jfindlay** [comment]
@nickw8, thanks for the report.  What version of salt are you using?

**Comment by nickw8** [comment]
2015.5.5.6

**Comment by doesitblend** [comment]
Re-opening this issue.

ZD-3867

Comparing code between v2019.2.0 there no changes indicating this issue would have been fixed.

**Comment by cmcmarrow** [comment]
https://github.com/saltstack/salt/pull/46713
