### ISSUE TITLE
possible issue with state module boto_cfn/docker/...

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#28655]
```
[DEBUG   ] Failed to import states boto_cfn:
Traceback (most recent call last):
  File "salt/loader.py", line 1215, in _load_module
  File "salt/states/boto_cfn.py", line 45, in <module>
  File "xml/etree/cElementTree.py", line 3, in <module>
ImportError: No module named _elementtree
```

```
[ERROR   ] Exception raised when processing __virtual__ function for dockerng. Module will not be loaded: global name '__modules__' is not defined
Traceback (most recent call last):
  File "salt/loader.py", line 1458, in process_virtual
  File "salt/states/dockerng.py", line 78, in __virtual__
NameError: global name '__modules__' is not defined
[WARNING ] salt.loaded.int.states.dockerng.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'dockerng', please fix this.
```
```
[DEBUG   ] Failed to import states boto_iam:
Traceback (most recent call last):
  File "salt/loader.py", line 1215, in _load_module
  File "salt/states/boto_iam.py", line 119, in <module>
  File "xml/etree/cElementTree.py", line 3, in <module>
ImportError: No module named _elementtree
```

noticed this while testing my first state files on a masterless minion.

That should probably be handled a bit more gracefully.

**Comment by jfindlay** [comment]
@sjorge, thanks for the report.  The docker issue has already been [reported](https://github.com/saltstack/salt/issues/28549) and the mentioned pull request should fix the other.

**Comment by sjorge** [comment]
Just pulled in the changes, looks to be fixed.

**Comment by jfindlay** [comment]
Thanks, @sjorge.  If you don't mind, I'm going to close this as there is already an issue for the docker problem.
