### ISSUE TITLE
[Traceback] pkg.upgrade_available

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#28688]
Running salt-ssh 2015.8.1. Doesn't matter if package 'abc' exists or not.

```
salt:/srv # salt-ssh minion pkg.upgrade_available abc
minion:
    ----------
    retcode:
        1
    stderr:
        [CRITICAL] Unable to import msgpack or msgpack_pure python modules
        Traceback (most recent call last):
          File "/tmp/.root_dcdf8c_salt/salt-call", line 4, in <module>
            salt_call()
          File "/tmp/.root_dcdf8c_salt/salt/scripts.py", line 331, in salt_call
            client.run()
          File "/tmp/.root_dcdf8c_salt/salt/cli/call.py", line 53, in run
            caller.run()
          File "/tmp/.root_dcdf8c_salt/salt/cli/caller.py", line 133, in run
            ret = self.call()
          File "/tmp/.root_dcdf8c_salt/salt/cli/caller.py", line 196, in call
            ret['return'] = func(*args, **kwargs)
          File "/tmp/.root_dcdf8c_salt/salt/modules/zypper.py", line 238, in upgrade_available
            return latest_version(name).get(name) is not None
          File "/tmp/.root_dcdf8c_salt/salt/modules/zypper.py", line 220, in latest_version
            return ret[names[0]]['version']
        KeyError: 'abc'
    stdout:
```

**Comment by srkunze** [comment]
Resulted by corrupted thin transfer. Deleting thin.tgz fixed the issue.
