### ISSUE TITLE
s3 ext pillar cache file is not created

### ISSUE THREAD

**Issue by MrCitron** [saltstack/salt#28689]
Using version 2015.5.6 and this master configuration :

```
ext_pillar:
  - s3:
      bucket: mybucket
      keyid: mykeyid
      key: mykey
      location: eu-west-1
      s3_cache_expire: 30
      s3_sync_on_update: True
```

On a fresh master, I get an IO error :

```
2015-11-09 09:16:39,164 [salt.pillar                              ][ERROR   ][782] Failed to load ext_pillar s3: [Errno 2] No such file or directory: '/var/cache/salt/master/pillar_s3fs/mybucket--files.cache'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 538, in ext_pillar
    key)
  File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 497, in _external_pillar_data
    ext = self.ext_pillars[key](self.opts['id'], pillar, **val)
  File "/usr/lib/python2.7/dist-packages/salt/pillar/s3.py", line 144, in ext_pillar
    metadata = _init(s3_creds, bucket, multiple_env, environment, prefix, s3_cache_expire)
  File "/usr/lib/python2.7/dist-packages/salt/pillar/s3.py", line 180, in _init
    cache_file_mtime = os.path.getmtime(cache_file)
  File "/usr/lib/python2.7/genericpath.py", line 62, in getmtime
    return os.stat(filename).st_mtime
OSError: [Errno 2] No such file or directory: '/var/cache/salt/master/pillar_s3fs/mybucket--files.cache'
```

In fact, the file does not exists, and the call to *getmtime* will ever fail unless the file has been created externally.

I propose to fix this issue by testing the cache file creation before calling getmtime.
See PR.

**Comment by rallytime** [comment]
@MrCitron Thanks very much for fixing this! :)
