### ISSUE TITLE
salt-minion and salt-master displaying traceback when started (saltdev)

### ISSUE THREAD

**Issue by ryancurrah** [saltstack/salt#28809]
I'm trying to setup a salt dev environment on centos67 x86_64 vagrant box. I'm getting an issue very similar to https://github.com/saltstack/salt/issues/26672. I cloned and checked out develop which has supposedly fixed the issue linked and still getting the same issue. Any idea what I could do to troubleshoot?

Run the salt-master in daemon mode..

```bash
(env)[vagrant@localhost env]$ salt-master -c ./etc/salt/ -d -l trace
[DEBUG   ] Reading configuration from /srv/saltdev/env/etc/salt/master
[TRACE   ] None of the required configuration sections, 'logstash_udp_handler' and 'logstash_zmq_handler', were found in
 the configuration. Not loading the Logstash logging handlers module.
[TRACE   ] The required configuration section, 'fluent_handler', was not found the in the configuration. Not loading the
 fluent logging handlers module.
[DEBUG   ] Configuration file path: /srv/saltdev/env/etc/salt/master
[TRACE   ] Trying pysss.getgrouplist for 'vagrant'
[TRACE   ] Trying generic group list for 'vagrant'
[TRACE   ] Group list for user 'vagrant': '['admin']'
(env)[vagrant@localhost env]$ Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.6/multiprocessing/util.py", line 265, in _exit_function
    p._popen.terminate()
  File "/usr/lib/python2.6/multiprocessing/forking.py", line 139, in terminate
    os.kill(self.pid, signal.SIGTERM)
OSError: [Errno 3] No such process
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.6/multiprocessing/util.py", line 265, in _exit_function
    p._popen.terminate()
  File "/usr/lib/python2.6/multiprocessing/forking.py", line 139, in terminate
    os.kill(self.pid, signal.SIGTERM)
OSError: [Errno 3] No such process
```

Vagrant salt dev provisioning script...

```bash
# Setup salt dev env
SALTDEV_DIR=/srv/saltdev
sudo mkdir -p $SALTDEV_DIR
sudo chown -R vagrant:vagrant $SALTDEV_DIR
virtualenv $SALTDEV_DIR/env
source $SALTDEV_DIR/env/bin/activate

# yum utils for salt pkg module
sudo yum install -y yum-utils

# Clone salt
git clone https://github.com/saltstack/salt $SALTDEV_DIR/salt
cd $SALTDEV_DIR/salt
git remote add upstream https://github.com/saltstack/salt
git fetch --tags upstream

# Install swig from source so we can install m2crypto
SWIGBUILD_DIR=/srv/swig
sudo yum install -y pcre-devel
sudo mkdir -p $SWIGBUILD_DIR
sudo tar -zxvf /vagrant/files/swig-3.0.7.tar.gz -C $SWIGBUILD_DIR
cd $SWIGBUILD_DIR/swig-3.0.7
sudo ./configure
sudo make
sudo make install
hash -r

# Change dir
cd $SALTDEV_DIR

# Yum install deps
sudo wget https://repo.saltstack.com/yum/rhel6/SALTSTACK-GPG-KEY.pub
sudo rpm --import SALTSTACK-GPG-KEY.pub
sudo rm -f SALTSTACK-GPG-KEY.pub
sudo cp /vagrant/files/saltstack.repo /etc/yum.repos.d/saltstack.repo
sudo yum install -y zeromq
sudo yum install -y openssl-devel

# Pip install deps
env SWIG_FEATURES="-cpperraswarn -includeall -D__`uname -m`__ -I/usr/include/openssl" pip install M2Crypto
pip install pyzmq PyYAML pycrypto msgpack-python jinja2 psutil

# Pip install salt
pip install -e $SALTDEV_DIR/salt

# Salt path
GENERATE_SALT_SYSPATHS=1 pip install --global-option='--salt-root-dir=/srv/saltdev/env' -e $SALTDEV_DIR/salt

# Salt folders
mkdir -p $SALTDEV_DIR/env/var/log/salt
mkdir -p $SALTDEV_DIR/env/var/cache/salt/master
mkdir -p $SALTDEV_DIR/env/var/cache/salt/minion

# Conf
mkdir -p $SALTDEV_DIR/env/etc/salt/
cp /vagrant/salt/conf/master /vagrant/salt/conf/minion $SALTDEV_DIR/env/etc/salt/

# Clean up deps
sudo yum erase -y openssl-devel
sudo yum erase -y pcre-devel
cd $SALTDEV_DIR
sudo rm -rf $SWIGBUILD_DIR
```

**Comment by ryancurrah** [comment]
Ah never mind the process still runs in the backround but I always get this error when running both minion and master... not sure if it's bad thing but minion master works.

```bash
(env)[vagrant@localhost env]$ salt \* test.ping
10.0.2.15:
    True
```

**Comment by oliver-dungey** [comment]
@ryancurrah did you work out what the issue was - I seem to have recreated it
