### ISSUE TITLE
salt.output.compact raises exception

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#28801]
```
[root@core /opt/local/salt_dev/sls]# /opt/local/salt/bin/salt-call --local test.ping --out compact
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: 'bool' object is not iterable
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "__main__.py", line 128, in <module>
  File "__main__salt-call__.py", line 14, in <module>
  File "salt/scripts.py", line 333, in salt_call
  File "salt/cli/call.py", line 58, in run
  File "salt/cli/caller.py", line 148, in run
  File "salt/output/__init__.py", line 86, in display_output
  File "salt/output/__init__.py", line 39, in try_printout
  File "salt/output/compact.py", line 21, in output
TypeError: 'bool' object is not iterable
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "__main__.py", line 128, in <module>
  File "__main__salt-call__.py", line 14, in <module>
  File "salt/scripts.py", line 333, in salt_call
  File "salt/cli/call.py", line 58, in run
  File "salt/cli/caller.py", line 148, in run
  File "salt/output/__init__.py", line 86, in display_output
  File "salt/output/__init__.py", line 39, in try_printout
  File "salt/output/compact.py", line 21, in output
TypeError: 'bool' object is not iterable
```

For reference here is the raw output
```
[root@core /opt/local/salt_dev/sls]# /opt/local/salt/bin/salt-call --local test.ping --out raw
{'local': True}
```

**Comment by sjorge** [comment]
Oops I missed it on my first search #18614 is already open.
