### ISSUE TITLE
salt-ssh doesn't package tornado's new deps in the thin

### ISSUE THREAD

**Issue by basepi** [saltstack/salt#28828]
```
root@li1301-20:~/salt# salt-ssh -i '*' test.ping -W
basepi:
    ----------
    retcode:
        0
    stderr:
        Traceback (most recent call last):
          File "/tmp/.2110bf/salt-call", line 4, in <module>
            salt_call()
          File "/tmp/.2110bf/salt/scripts.py", line 325, in salt_call
            import salt.cli.call
          File "/tmp/.2110bf/salt/cli/call.py", line 6, in <module>
            from salt.utils import parsers
          File "/tmp/.2110bf/salt/utils/parsers.py", line 26, in <module>
            import salt.config as config
          File "/tmp/.2110bf/salt/config.py", line 40, in <module>
            import salt.utils.sdb
          File "/tmp/.2110bf/salt/utils/sdb.py", line 9, in <module>
            import salt.loader
          File "/tmp/.2110bf/salt/loader.py", line 28, in <module>
            import salt.utils.event
          File "/tmp/.2110bf/salt/utils/event.py", line 81, in <module>
            import salt.payload
          File "/tmp/.2110bf/salt/payload.py", line 17, in <module>
            import salt.crypt
          File "/tmp/.2110bf/salt/crypt.py", line 44, in <module>
            import tornado.gen
          File "/tmp/.2110bf/tornado/gen.py", line 97, in <module>
            from singledispatch import singledispatch  # backport
        ImportError: No module named singledispatch
    stdout:
```

singledispatch, backports_abc, singledispatch_helpers

**Comment by basepi** [comment]
Fixed in #28826
