### ISSUE TITLE
Fix file.comment

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#28888]
This PR broke file.comment / uncomment states:
https://github.com/saltstack/salt/pull/28174

For some reason it can't find mmap

```
comment.sls
---------------------
  1 comment:
  2   file.comment:
  3     - name: c:\stuff1.txt
  4     - regex: ^level = (warning|error)
  5     - char: '#'
```
Getting the following error:
```
slee_build_win32:
----------
          ID: comment
    Function: file.comment
        Name: c:\stuff1.txt
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "C:\salt\bin\lib\site-packages\salt\state.py", line 1594, in call
                  **cdata['kwargs'])
                File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1491, in wrapper
                  return f(*args, **kwargs)
                File "C:\salt\bin\lib\site-packages\salt\states\file.py", line 2922, in comment
                  if not __salt__['file.search'](name, regex, multiline=True):
                File "C:\salt\bin\lib\site-packages\salt\modules\file.py", line 2216, in search
                  ignore_if_missing=ignore_if_missing)
                File "C:\salt\bin\lib\site-packages\salt\modules\file.py", line 1812, in replace
                  r_data = mmap.mmap(r_file.fileno(),
              NameError: global name 'mmap' is not defined
     Started: 00:14:53.651000
    Duration: 47.0 ms
     Changes:
```

Salt Version: 2015.8.2 /2015.5.7
Windows 2008R2 64 and 32

**Comment by lorengordon** [comment]
oops. i did fix all the tests that failed with that change. guessing there aren't tests for file.comment?

**Comment by lorengordon** [comment]
oh wait, i think i know what is happening. the separate win_file.py module always throws me. try just adding `import mmap` to win_file.py. 

[sidenote: it would be awesome if jenkins spun up a windows instance to run the tests against!]

**Comment by lorengordon** [comment]
Now I am more confused. Since my patch created the problem, I thought I would test the issue and try to fix it, but file.comment and file.uncomment are working just fine on my Windows system, without messing with win_file.py. I am using masterless mode, though, as I don't have a salt master. Perhaps it's an interaction between master and minion versions?

I was using 2015.5.5, with updated file.py modules in the custom `_modules` and `_states` directories, and I confirmed they loaded using `saltutil.sync_all`. So could maybe also be an interaction with another change in 2015.8?

```
C:\salt\srv\states\base> cat .\foo.txt
foo
bar
#baz
```

```
C:\salt\srv\states\base> cat .\comment.sls
comment:
  file.comment:
    - name: c:\salt\srv\states\base\foo.txt
    - regex: bar
    - char: '#'
```

```
C:\salt\srv\states\base> cat .\uncomment.sls
uncomment:
  file.uncomment:
    - name: c:\salt\srv\states\base\foo.txt
    - regex: baz
    - char: '#'
```

test file.comment:
```
C:\salt\srv\states\base> C:\salt\salt-call.bat --local state.sls comment
local:
----------
          ID: comment
    Function: file.comment
        Name: c:\salt\srv\states\base\foo.txt
      Result: True
     Comment: Commented lines successfully
     Started: 08:44:45.799000
    Duration: 59.0 ms
     Changes:
              ----------
              diff:
                  ---
                  +++
                  @@ -1,3 +1,3 @@
                   foo
                  -bar
                  +#bar
                   #baz

Summary
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
```

test file.uncomment:
```
C:\salt\srv\states\base> C:\salt\salt-call.bat --local state.sls uncomment
local:
----------
          ID: uncomment
    Function: file.uncomment
        Name: c:\salt\srv\states\base\foo.txt
      Result: True
     Comment: Uncommented lines successfully
     Started: 08:45:16.986000
    Duration: 53.0 ms
     Changes:
              ----------
              diff:
                  ---
                  +++
                  @@ -1,3 +1,3 @@
                   foo
                   #bar
                  -#baz+baz

Summary
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
```

**Comment by lorengordon** [comment]
Just upgraded my minion to 2015.8.1, added modules/file.py and states/file.py from the 2015.8 branch to _modules and _states, synced them, and it still works with no errors. So, possibly an issue with a master/minion setup? Or 2015.8.2, specifically?

**Comment by twangboy** [comment]
Hmmmmmm. I'll take a look later today and see what I can find out.
