### ISSUE TITLE
Salt argument collision

### ISSUE THREAD

**Issue by dmyerscough** [saltstack/salt#28893]
Salt has a conflict with `--pid-file` arguments as it's defined twice. Once in `DaemonMixIn` and once in `PidfileMixin`

```python
/usr/lib/python2.7/dist-packages/salt/utils/parsers.py:953: DeprecationWarning: Please stop sub-classing PidfileMix and instead subclass DaemonMixIn which contains the same behavior. PidfileMixin will be supported until Salt Nitrogen (Unreleased).
Traceback (most recent call last):
  File "/usr/bin/salt-api", line 8, in <module>
    salt_api()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 441, in salt_api
    sapi = salt.cli.api.SaltAPI()  # pylint: disable=E1120
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 152, in __init__
    optparse.OptionParser.__init__(self, *args, **kwargs)
  File "/usr/lib/python2.7/optparse.py", line 1220, in __init__
    add_help=add_help_option)
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 233, in _populate_option_list
    mixin_setup_func(self)
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 962, in _mixin_setup
    help=('Specify the location of the pidfile. Default: %default')
  File "/usr/lib/python2.7/optparse.py", line 1021, in add_option
    self._check_conflict(option)
  File "/usr/lib/python2.7/optparse.py", line 996, in _check_conflict
    option)
optparse.OptionConflictError: option --pid-file: conflicting option string(s): --pid-file
```

To reproduce this just issue `salt-api -h` on the development branch

@s0undt3ch

**Comment by s0undt3ch** [comment]
I'll fix it. Thanks for reporting that.

**Comment by s0undt3ch** [comment]
Here's the fix, plus some more goodies... https://github.com/saltstack/salt/pull/29002

**Comment by dmyerscough** [comment]
:+1:
