### ISSUE TITLE
S3fs pillar cannot find cache in 2015.8.1

### ISSUE THREAD

**Issue by stanislavb** [saltstack/salt#28915]
## Salt versions
```
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
         Python: 2.6.9 (unknown, Apr  1 2015, 18:16:00)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist:
        machine: x86_64
        release: 4.1.7-15.23.amzn1.x86_64
```
## Salt master log
Bucket name replaced. Original contains hyphens.
```
2015-11-16 09:55:37,349 [salt.pillar                              ][ERROR   ][7197] Failed to load ext_pillar s3: [Errno 2] No such file or directory: '/var/cache/salt/master/pillar_s3fs/my-pillars-bucket--files.cache'
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/pillar/__init__.py", line 631, in ext_pillar
    key)
  File "/usr/lib/python2.6/site-packages/salt/pillar/__init__.py", line 583, in _external_pillar_data
    ext = self.ext_pillars[key](self.opts['id'], pillar, **val)
  File "/usr/lib/python2.6/site-packages/salt/pillar/s3.py", line 144, in ext_pillar
    metadata = _init(s3_creds, bucket, multiple_env, environment, prefix, s3_cache_expire)
  File "/usr/lib/python2.6/site-packages/salt/pillar/s3.py", line 185, in _init
    cache_file_mtime = os.path.getmtime(cache_file)
  File "/usr/lib64/python2.6/genericpath.py", line 54, in getmtime
    return os.stat(filename).st_mtime
OSError: [Errno 2] No such file or directory: '/var/cache/salt/master/pillar_s3fs/my-pillars-bucket--files.cache'
```
## Salt master config
```
# States backend
fileserver_backend:
  - s3fs
s3.location: us-east-1
s3.buckets:
  base:
    - my-states-bucket

# Pillar backend
ext_pillar:
  - s3:
      bucket: my-pillars-bucket
      verify_ssl: True
      location: us-east-1
```
## Minion output
```
# salt-call pillar.items
local:
    ----------
```

Similar to #23016

**Comment by stanislavb** [comment]
Sorry, this was fixed in:
https://github.com/saltstack/salt/commit/75a658e2176a98232a1ee1d3f4423948754b31ec
