### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 30: ordinal not in range(128)

### ISSUE THREAD

**Issue by kimoziiiii** [saltstack/salt#28917]
saltmaster
```
[root@depsrv01 salt]# salt --versions-report
Salt Version:
           Salt: 2015.8.1
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.20.2
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.4
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: centos 6.2 
        machine: x86_64
        release: 2.6.32-220.el6.x86_64
         system: CentOS 6.2 
```
minion
```
[lihai@SHPD-I03-SRV03 ~]$ salt-call --versions-report
Salt Version:
           Salt: 2015.8.1
 
Dependency Versions:
         Jinja2: unknown
       M2Crypto: 0.20.2
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.4
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: centos 6.5 Final
        machine: x86_64
        release: 2.6.32-431.29.2.el6.x86_64
         system: CentOS 6.5 Final
```
I get this crash when running  `salt SHPD-I03-SRV03 saltutil.sync_modules` , but run this shell is ok before i upgrade minion from 2014.7.5 to 2015.8.1.
```
[DEBUG   ] In saltenv 'base', ** considering ** path u'/var/cache/salt/minion/files/base/_modules/appdeploy.py' to resolve u'salt://_modules/appdeploy.py'
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache u'salt://_modules/appdeploy.py'
[WARNING ] The minion function caused an exception
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 1036, in _thread_return
    return_data = func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/modules/saltutil.py", line 310, in sync_modules
    ret = _sync('modules', saltenv)
  File "/usr/lib/python2.6/site-packages/salt/modules/saltutil.py", line 111, in _sync
    source, sub_env, include_pat=r'E@\.(pyx?|so|zip)$'
  File "/usr/lib/python2.6/site-packages/salt/modules/cp.py", line 444, in cache_dir
    path, saltenv, include_empty, include_pat, exclude_pat
  File "/usr/lib/python2.6/site-packages/salt/fileclient.py", line 230, in cache_dir
    if fn_.strip() and fn_.startswith(path):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 30: ordinal not in range(128)
[DEBUG   ] SaltEvent PUB socket URI: ipc:///var/run/salt/minion/minion_event_af3a7995d5_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: ipc:///var/run/salt/minion/minion_event_af3a7995d5_pull.ipc
[DEBUG   ] Sending event - data = {'message': u'The minion function caused an exception', 'args': ('The minion function caused an exception',), '_stamp': '2015-11-16T12:29:54.663025'}
[DEBUG   ] Handling event "_salt_error\n\n\x83\xa7message\xda\x00'The minion function caused an exception\xa4args\x91\xda\x00'The minion function caused an exception\xa6_stamp\xba2015-11-16T12:29:54.663025"
[DEBUG   ] Forwarding salt error event tag=_salt_error
```
the modules
```
[root@depsrv01 salt]# tree /srv/salt/_modules/
/srv/salt/_modules/
└── appdeploy.py
```

how to fix it? ths.

**Comment by jfindlay** [comment]
@kimoziiiii, thanks for the report.  This should be fixed by #28340, which is coming out in 2015.8.2.

**Comment by kimoziiiii** [comment]
@jfindlay ths for your reply.

**Comment by cachedout** [comment]
Since we have this one fixed, I'll go ahead and close this issue. Thanks, all.
