### ISSUE TITLE
Using host.present gives error on Ubuntu 14.04

### ISSUE THREAD

**Issue by jwilsonGFM** [saltstack/salt#28968]
I have setting up the hosts file for AWS using this simple file:

jumpbox:
  host.present:
    - ip: 
      - 52.32.111.207

dbmaster:
  host.present:
    - ip: 
      - 172.31.1.30
## this gives this error when executed:

```
      ID: jumpbox
Function: host.present
  Result: False
 Comment: An exception occurred in this state: Traceback (most recent call last):
            File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1318, in call
              ret = self.states[cdata['full']](*cdata['args'])
            File "/usr/lib/python2.7/dist-packages/salt/states/host.py", line 45, in present
              if __salt__['hosts.has_pair'](ip, name):
            File "/usr/lib/python2.7/dist-packages/salt/modules/hosts.py", line 111, in has_pair
              return ip in hosts and alias in hosts[ip]
          TypeError: unhashable type: 'list'
```

the error duplicated on all individual hosts in the control file.

**Comment by yatahaze** [comment]
I get this error for all my new Debian Jessie LXC VM's that I roll out.
