### ISSUE TITLE
[sentry_return] pillar_data crash when using salt-call --local

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#29040]
When using salt-call --local with sentry returner configured I get the following traceback : 

```
Traceback (most recent call last):
  File "/var/cache/salt/minion/extmods/returners/sentry_return.py", line 117, in returner
    connect_sentry(ret['fun'], ret)
  File "/var/cache/salt/minion/extmods/returners/sentry_return.py", line 78, in connect_sentry
    if 'tags' in pillar_data['raven']:
KeyError: 'raven'
```

the code should probably read `pillar_data.get('raven', [])` but the following question is : should it fall back to a cached version of the pillar ? 

```
# salt-call --versions-report
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
           Mako: 1.0.0
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: debian 8.2 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.2 

```

**Comment by jfindlay** [comment]
@arthurlogilab, thanks for the report.  That is a good question.  I don't know anything about sentry, but it seems that something better should be done if that pillar is unavailable.  Like, if it is the result of an error coming from the raven lib, that error could be passed onto the user.
