### ISSUE TITLE
boto_iam.* not working correct within eu-central-1 (and perhaps other regions?)

### ISSUE THREAD

**Issue by Reiner030** [saltstack/salt#29044]
- 2015.5.3:

```
root@saltmaster:~# lsb_release -d
Description:    Debian GNU/Linux 8.2 (jessie)
root@saltmaster:~# salt-call --version
salt-call 2015.5.3 (Lithium)
root@saltmaster:~# salt-call boto_iam.instance_profile_exists nu3-default -l debug
[DEBUG   ] Reading configuration from /etc/salt/minion
...
[DEBUG   ] Including configuration from '/etc/salt/minion.d/iamrole.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/iamrole.conf
...
[DEBUG   ] Including configuration from '/etc/salt/minion.d/iamrole.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/iamrole.conf
...
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded boto_iam.instance_profile_exists
[DEBUG   ] LazyLoaded config.option
[DEBUG   ] Re-using SAuth for ('/etc/salt/pki/minion', 'saltmaster', 'tcp://172.31.0.161:4506')
[DEBUG   ] LazyLoaded nested.output
local:
    False
```

After commenting out the region

```
root@saltmaster:~# cat /etc/salt/minion.d/iamrole.conf
iam.keyid: xxx
iam.key: 'xxx'
#iam.region: eu-central-1
```

it works as expected:

```
root@saltmaster:~# salt-call boto_iam.instance_profile_exists nu3-default -l debug
...
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded boto_iam.instance_profile_exists
[DEBUG   ] LazyLoaded config.option
[DEBUG   ] Re-using SAuth for ('/etc/salt/pki/minion', 'nu3-salt01.nu3.net', 'tcp://172.31.0.161:4506')
[DEBUG   ] LazyLoaded nested.output
local:
    True
```
- 2015.8.1:

```
root@ip-172-31-8-18:~# lsb_release -d
Description:    Debian GNU/Linux 8.2 (jessie)
root@ip-172-31-8-18:~# salt-call --version
salt-call 2015.8.1 (Beryllium)
root@ip-172-31-8-18:~# salt-call boto_iam.instance_profile_exists saltmaster -l debug
...
[DEBUG   ] Including configuration from '/etc/salt/minion.d/iamrole.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/iamrole.conf
...
[DEBUG   ] Including configuration from '/etc/salt/minion.d/iamrole.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/iamrole.conf
...
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded boto.assign_funcs
[DEBUG   ] LazyLoaded boto_iam.instance_profile_exists

Passed invalid arguments: Region "eu-central-1" is not valid..

Usage:

    Check to see if an instance profile exists.

    CLI Example:

    .. code-block:: bash

        salt myminion boto_iam.instance_profile_exists myiprofile

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 196, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/boto_iam.py", line 85, in instance_profile_exists
    conn = _get_conn(region=region, key=key, keyid=keyid, profile=profile)
  File "/usr/lib/python2.7/dist-packages/salt/utils/boto.py", line 202, in get_connection
    'valid.'.format(region))
SaltInvocationError: Region "eu-central-1" is not valid.
```

After commenting out the region

```
root@ip-172-31-8-18:~# cat /etc/salt/minion.d/iamrole.conf
iam.keyid: xxx
iam.key: 'xxx'
#iam.region: eu-central-1
```

it works as expected:

```
root@ip-172-31-8-18:~# salt-call boto_iam.instance_profile_exists saltmaster -l debug
...
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded boto.assign_funcs
[DEBUG   ] LazyLoaded boto_iam.instance_profile_exists
[DEBUG   ] LazyLoaded nested.output
local:
    True
```

**Comment by jfindlay** [comment]
@Reiner030, thanks for the report.

**Comment by lomeroe** [comment]
@Reiner030 what is your boto version?  The error in 2015.8.1 is straight from boto.  Eu-central-1 was only added as an endpoint in boto for IAM back in February (https://github.com/boto/boto/pull/2976).  You'll need at least boto 2.37.0 (or use a local endpoints.json file) to get the call to work that way.

**Comment by Reiner030** [comment]
@lomeroe default Debian package one:
````
root@saltmaster:~# aptitude show python-boto | grep ^Version
Version: 2.34.0-2
````
which should work fine (first version with eu-central-1 support) ?
http://boto.readthedocs.org/en/latest/releasenotes/v2.34.0.html

Perhaps saltstack needs to install also Debian package python-pip and install a boto upgrade by default?

I have also problems to setup security groups.
Independend of set region I got an empty security rules group created in us-east-1 which cannot be resolved by additional runs and is tried to setup again and again. 

I can create for this problem another issue if it make sense.

**Comment by lomeroe** [comment]
A workaround would be to download the endpoints.json file from the boto github (https://github.com/boto/boto/blob/2.38.0/boto/endpoints.json for example) and specify the path of the file in your boto.cfg (/etc/boto.cfg):

```
[Boto]
endpoints_path = /path/to/endpoints.json
```
See http://boto.cloudhackers.com/en/latest/boto_config_tut.html for more details on that config.


Eu-central-1 was added for most every service in 2.34.0, but not IAM.   It wasn't added as an IAM endpoint until 2.37 (http://boto.readthedocs.org/en/latest/releasenotes/v2.37.0.html)

**Comment by Reiner030** [comment]
No Problem. I already added manually the "testing" package which works for this problem fine.
But it would commonly "nice to have" if you could add the needed package to your repository for the required distros, too ?

**Comment by rallytime** [comment]
Unfortunately, we won't be adding `boto` or `python-pip` to the Salt packages. We avoid adding soft dependencies to Salt because it adds more packaging overhead. We also want to be cognizant of people who don't want packages they won't use.

**Comment by Reiner030** [comment]
ok @rallytime but perhaps you can add it as recommend package with version identifier in the package "header" and comment so other people didn't run in same problem ?
