### ISSUE TITLE
`tpldir` not present when rendering winrepo pkg definitions

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt#29063]
I was starting to test the new rendering capabilities for winrepo packages in 2015.8, and I wanted to separate some of the jinja logic from the state file, just like I do when writing other states or formulas. However, it seems that the normal state variables are not being set, like `tpldir`, which is how I would normally reference the path to the jinja file in the import statement. If I write out the full path to the jinja file, the import works and the package renders just fine.

`cat winrepo/mypkg/init.sls`:

``` salt
{%- from tpldir + '/mypkg.jinja' import package -%}

{{ package.name }}:
  {%- for version,params in package.versions.items() %}
  {%- do params.update(salt['pillar.get'](
      package.pillar ~ ':common_params', 
      default=package.common_params,
      merge=True)) %}
  {{ version }}:
    {{ params }}
  {%- endfor %}
```

`cat winrepo/mypkg/mypkg.jinja`:

``` salt
{%-
set systemroot = salt['reg.read_value'](
    'HKEY_LOCAL_MACHINE', 
    'SOFTWARE\Microsoft\Windows NT\CurrentVersion', 
    'SystemRoot').vdata 
-%}

{%- set name = 'mypkg' -%}
{%- set versions = ['1.0','2.0'] -%}

{%- load_yaml as package -%}
name: {{ name }}
pillar: '{{ name }}:winrepo'
common_params:
  reboot: False
  install_flags: ' /q /norestart'
  msiexec: False
  uninstall_flags: ' /uninstall /q /norestart'
versions:
  {% for version in versions %}
  {{ version }}:
    installer: 'https://url/to/{{ version }}/installer.exe'
    full_name: 'My Package {{ version }}'
    uninstaller: '{{ systemroot }}\path\to\my\uninstaller.exe'
  {% endfor %}
{%- endload -%}

{%-
do package.versions.update(salt['pillar.get'](
    package.pillar ~ ':versions',
    default=package.versions,
    merge=True))
-%}
```

Note in the traceback below that it is trying to find the file `salt://mypkg.jinja` even though the import statement is `from tpldir + '/mypkg.jinja' import package`.

`salt-call --local pkg.refresh_db`:

```
[DEBUG   ] compile template: c:\salt\var\cache\salt\minion\files\base\winrepo\mypkg\init.sls
[DEBUG   ] Jinja search path: ['c:\\salt\\var\\cache\\salt\\minion\\files\\base']
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init
[DEBUG   ] Updating roots fileserver cache
[DEBUG   ] Could not find file from saltenv 'base', u'salt://mypkg.jinja'
[DEBUG   ] Jinja Error
[DEBUG   ] Exception: /mypkg.jinja
[DEBUG   ] Out:
[DEBUG   ] Line: 1
[DEBUG   ] TmplStr: {%- from tpldir + '/mypkg.jinja' import package -%}

{{ package.name }}:
  {%- for version,params in package.versions.items() %}
  {%- do params.update(salt['pillar.get'](
      package.pillar_name ~ ':common_params', package.common_params)) %}
  {%- do params.update(salt['pillar.get'](
      package.pillar_name ~ ':versions:' ~ version, {})) %}
  {{ version }}:
    {{ params }}
  {%- endfor %}

Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\utils\templates.py", line 368, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "C:\salt\bin\lib\site-packages\jinja2\environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\salt\bin\lib\site-packages\jinja2\environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 1, in top-level template code
  File "C:\salt\bin\lib\site-packages\salt\utils\jinja.py", line 144, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: /mypkg.jinja

[DEBUG   ] TraceStr: Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\utils\templates.py", line 368, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "C:\salt\bin\lib\site-packages\jinja2\environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\salt\bin\lib\site-packages\jinja2\environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 1, in top-level template code
  File "C:\salt\bin\lib\site-packages\salt\utils\jinja.py", line 144, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: /mypkg.jinja

[ERROR   ] Rendering exception occurred :Jinja error: /mypkg.jinja
Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\utils\templates.py", line 368, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "C:\salt\bin\lib\site-packages\jinja2\environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\salt\bin\lib\site-packages\jinja2\environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 1, in top-level template code
  File "C:\salt\bin\lib\site-packages\salt\utils\jinja.py", line 144, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: /mypkg.jinja

; line 1

---
{%- from tpldir + '/mypkg.jinja' import package -%}    <======================

{{ package.name }}:
  {%- for version,params in package.versions.items() %}
  {%- do params.update(salt['pillar.get'](
      package.pillar_name ~ ':common_params', package.common_params)) %}
[...]

---
[DEBUG   ] Failed to compile c:\salt\var\cache\salt\minion\files\base\winrepo\mypkg\init.sls.
[DEBUG   ] Error: Jinja error: /mypkg.jinja
Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\utils\templates.py", line 368, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "C:\salt\bin\lib\site-packages\jinja2\environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\salt\bin\lib\site-packages\jinja2\environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 1, in top-level template code
  File "C:\salt\bin\lib\site-packages\salt\utils\jinja.py", line 144, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: /mypkg.jinja

; line 1

---
{%- from tpldir + '/mypkg.jinja' import package -%}    <======================

{{ package.name }}:
  {%- for version,params in package.versions.items() %}
  {%- do params.update(salt['pillar.get'](
      package.pillar_name ~ ':common_params', package.common_params)) %}
[...]
---.
```

`C:\salt\salt-call.bat --local --versions`:

```
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.2
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 0.3.7
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist:
        machine: AMD64
        release: 8
         system: 8 6.2.9200  Multiprocessor Free
```

**Comment by jfindlay** [comment]
@lorengordon, thanks for the report.

@twangboy, @UtahDave, @TheBigBear

**Comment by TheBigBear** [comment]
@lorengordon thanks for your interesting work on this very helpful indeed and timely for myself.

**Comment by lorengordon** [comment]
@TheBigBear, sure thing, no prob. The key point for me is being able to override the `installer` and `uninstaller` values from pillar. I have to re-host just about every package internally, and it would be nice to be able to set those variables in pillar, rather than mucking around in every winrepo definition. But then I went a little farther with the templating, and so I separated the jinja logic into another file to keep the winrepo definition clean, and ran into this odd issue with `tpldir`. I'm hoping it's a fairly easy fix, I just don't know where to look...

**Comment by lorengordon** [comment]
@twangboy, @UtahDave, I'm happy to work on this one if you could point me in the right direction. I tried tracing through the code over the weekend, but I was unable to figure out the difference between how the renderers are being called for winrepo definitions and state files. I was hoping that piece would tell me if there was something that wasn't being set in __context__, or maybe in the call to the renderer, and give me a knob to tweak.

**Comment by twangboy** [comment]
@lorengordon I wasn't even aware of the tpldir options until this issue. Better let @UtahDave chime in on this one.

**Comment by twangboy** [comment]
The only thing I could possible add is that we tried to pass the .sls files through the same rendering system as the states. Maybe I did it wrong or missed something...

**Comment by lorengordon** [comment]
I think this is still not working.

**Comment by eliasp** [comment]
Mark unstale - using `import` like this in winrepo SLS still doesn't work on 3003:
```Jinja
{%- from "../map.jinja" import winrepo %}
```

```
Failed to compile, Jinja error: ../map.jinja
Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt-3003.2-py3.7.egg\salt\utils\templates.py", line 500, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "c:\salt\bin\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\salt\bin\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\salt\bin\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
  File "c:\salt\bin\lib\site-packages\salt-3003.2-py3.7.egg\salt\utils\jinja.py", line 198, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ../map.jinja
```
