### ISSUE TITLE
Windows Salt minion (2015.8.1) does not failover to other masters when the first master goes offline in multimaster setup

### ISSUE THREAD

**Issue by kcoley** [saltstack/salt#29088]
Hi everyone. I have been running into an issue where if one of our salt masters goes down, the Windows minion does not failover to the other masters, but instead crashes.  I believe it may have something to do with tornado.

This is seen when trying to use salt-call whenever the first master goes down:

```
C:\salt>salt-call -l debug test.ping
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[INFO    ] Got list of available master addresses: ['salt-mastera', 'salt-masterb', 'salt-masterc', 'salt-masterd', 'salt-mastere']
[DEBUG   ] Initializing new SAuth for ('c:\\salt\\conf\\pki\\minion', 'salt-minion-007', 'tcp://12.46.94.123:1235')
[DEBUG   ] Generated random reconnect delay between '500ms' and '10500ms' (4813)
[DEBUG   ] Setting zmq_reconnect_ivl to '4813ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '10500ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'salt-minion-007', 'tcp://12.46.94.123:1235', 'aes')
[DEBUG   ] Initializing new SAuth for ('c:\\salt\\conf\\pki\\minion', 'salt-minion-007', 'tcp://12.46.94.123:1235')
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'salt-minion-007', 'tcp://12.46.94.123:1235', 'clear')
Attempt to authenticate with the salt master failed
[DEBUG   ] Error deleting fd from IOLoop
Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\tornado\ioloop.py", line 715, in remove_handler
    self._impl.unregister(fd)
  File "C:\salt\bin\lib\site-packages\zmq\eventloop\ioloop.py", line 115, in unregister
    return self._poller.unregister(fd)
  File "C:\salt\bin\lib\site-packages\zmq\sugar\poll.py", line 71, in unregister

    idx = self._map.pop(socket)
KeyError: None
[DEBUG   ] Error deleting fd from IOLoop
Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\tornado\ioloop.py", line 715, in remove_handler
    self._impl.unregister(fd)
  File "C:\salt\bin\lib\site-packages\zmq\eventloop\ioloop.py", line 115, in unregister
    return self._poller.unregister(fd)
  File "C:\salt\bin\lib\site-packages\zmq\sugar\poll.py", line 71, in unregister

    idx = self._map.pop(socket)
KeyError: None
```

This is a sample Windows minion file (Windows 7):

```
ipc_mode: tcp
root_dir: c:\salt
pki_dir: /conf/pki/minion
multiprocessing: False
id: salt-minion-007

master:
  - salt-mastera
  - salt-masterb
  - salt-masterc
  - salt-masterd
  - salt-mastere

master_type: failover
master_alive_interval: 30
recon_default: 500
recon_max: 10000
recon_randomize: True

schedule:
  highstate:
    function: state.highstate
    minutes: 60

# execute highstate at start
startup_states: highstate

######      Keepalive settings        ######
############################################
# ZeroMQ now includes support for configuring SO_KEEPALIVE if supported by
# the OS. If connections between the minion and the master pass through
# a state tracking device such as a firewall or VPN gateway, there is
# the risk that it could tear down the connection the master and minion
# without informing either party that their connection has been taken away.
# Enabling TCP Keepalives prevents this from happening.

# Overall state of TCP Keepalives, enable (1 or True), disable (0 or False)
# or leave to the OS defaults (-1), on Linux, typically disabled. Default True, enabled.
tcp_keepalive: True

# How long before the first keepalive should be sent in seconds. Default 300
# to send the first keepalive after 5 minutes, OS default (-1) is typically 7200 seconds
# on Linux see /proc/sys/net/ipv4/tcp_keepalive_time.
tcp_keepalive_idle: 300

# How many lost probes are needed to consider the connection lost. Default -1
# to use OS defaults, typically 9 on Linux, see /proc/sys/net/ipv4/tcp_keepalive_probes.
tcp_keepalive_cnt: -1

# How often, in seconds, to send keepalives after the first one. Default -1 to
# use OS defaults, typically 75 seconds on Linux, see
# /proc/sys/net/ipv4/tcp_keepalive_intvl.
tcp_keepalive_intvl: -1
```

Here is the info for one of the salt minions (all running Windows 7 64 bit):

```
C:\salt>salt-call --versions-report
Salt Version:
           Salt: 2015.8.1
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AM
64)]
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.2
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 0.3.7
          smmap: Not Installed
        timelib: Not Installed
System Versions:
           dist:
        machine: AMD64
        release: 7
         system: 7 6.1.7601 SP1 Multiprocessor Free
```

Here is the info for the salt masters (running CentOS6):

```
salt --versions-report
Salt Version:           
           Salt: 2015.8.1                      
Dependency Versions:     
         Jinja2: 2.8
       M2Crypto: 0.22
           Mako: 1.0.1
         PyYAML: 3.10
          PyZMQ: 14.6.0
         Python: 2.7.10 (default, Oct 21 2015, 11:16:15)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.2.4
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 6.4 Final
        machine: x86_64
        release: 2.6.32-358.23.2.el6.x86_64
         system: CentOS 6.4 Final
```

Thanks!

**Comment by jfindlay** [comment]
@kcoley, thanks for the report.

**Comment by jfindlay** [comment]
I know there is another issue about this already, but I am having trouble finding it.

**Comment by kcoley** [comment]
Thanks for looking into this. Is this the issue you were looking for? #28604

**Comment by jfindlay** [comment]
@kcoley, that is not the issue I was thinking of.  I was looking for something more like #28875.

**Comment by sakateka** [comment]
has the same problem on 2015.8.1 and 2015.8.2

```
salt-call --versions-report
Salt Version:
           Salt: 2015.8.2
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
           RAET: Not Installed
        Tornado: 4.2
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.18.19-24
         system: Ubuntu 14.04 trusty


[DEBUG   ] SaltReqTimeoutError, retrying. (1/3)
[DEBUG   ] SaltReqTimeoutError, retrying. (2/3)
[DEBUG   ] SaltReqTimeoutError, retrying. (3/3)
Attempt to authenticate with the salt master failed
[DEBUG   ] Error deleting fd from IOLoop
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/ioloop.py", line 715, in remove_handler
    self._impl.unregister(fd)
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/ioloop.py", line 125, in unregister
    return self._poller.unregister(fd)
  File "/usr/lib/python2.7/dist-packages/zmq/sugar/poll.py", line 80, in unregister
    idx = self._map.pop(socket)
KeyError: None
[DEBUG   ] Error deleting fd from IOLoop
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/ioloop.py", line 715, in remove_handler
    self._impl.unregister(fd)
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/ioloop.py", line 125, in unregister
    return self._poller.unregister(fd)
  File "/usr/lib/python2.7/dist-packages/zmq/sugar/poll.py", line 80, in unregister
    idx = self._map.pop(socket)
KeyError: None
```

**Comment by sakateka** [comment]
salt-call does not switch, because the error occurs even in the initialization phase at [minion.py#L535](https://github.com/saltstack/salt/blob/2015.8/salt/minion.py#L535)

`compile_pillar()`  is trying to authenticate from inaccessible master , which is why there is an exception [crypt.py#L458](https://github.com/saltstack/salt/blob/2015.8/salt/crypt.py#L458)
```
salt-call state.highstate 
[INFO    ] Got list of available master addresses: ['master1', 'master2']
[INFO    ] Determining pillar cache
> /usr/lib/python2.7/dist-packages/salt/crypt.py(439)_authenticate()
-> break
(Pdb) bt
  /usr/bin/salt-call(11)<module>()
-> salt_call()
  /usr/lib/python2.7/dist-packages/salt/scripts.py(335)salt_call()
-> client.run()
  /usr/lib/python2.7/dist-packages/salt/cli/call.py(43)run()
-> caller = salt.cli.caller.Caller.factory(self.config)
  /usr/lib/python2.7/dist-packages/salt/cli/caller.py(78)factory()
-> return ZeroMQCaller(opts, **kwargs)
  /usr/lib/python2.7/dist-packages/salt/cli/caller.py(269)__init__()
-> super(ZeroMQCaller, self).__init__(opts)
  /usr/lib/python2.7/dist-packages/salt/cli/caller.py(101)__init__()
-> self.minion = salt.minion.SMinion(opts)
  /usr/lib/python2.7/dist-packages/salt/minion.py(523)__init__()
-> self.gen_modules(initial_load=True)
  /usr/lib/python2.7/dist-packages/salt/minion.py(534)gen_modules()
-> pillarenv=self.opts.get('pillarenv'),
  /usr/lib/python2.7/dist-packages/salt/pillar/__init__.py(170)compile_pillar()
-> dictkey='pillar',
  /usr/lib/python2.7/dist-packages/salt/utils/async.py(74)wrap()
-> ret = self._block_future(ret)
  /usr/lib/python2.7/dist-packages/salt/utils/async.py(83)_block_future()
-> self.io_loop.start()
  /usr/lib/python2.7/dist-packages/zmq/eventloop/ioloop.py(160)start()
-> super(ZMQIOLoop, self).start()
  /usr/lib/python2.7/dist-packages/tornado/ioloop.py(810)start()
-> self._run_callback(callback)
  /usr/lib/python2.7/dist-packages/tornado/ioloop.py(592)_run_callback()
-> ret = callback()
  /usr/lib/python2.7/dist-packages/tornado/stack_context.py(275)null_wrapper()
-> return fn(*args, **kwargs)
  /usr/lib/python2.7/dist-packages/tornado/gen.py(963)<lambda>()
-> self.future, lambda f: self.run())
  /usr/lib/python2.7/dist-packages/tornado/gen.py(876)run()
-> yielded = self.gen.throw(*exc_info)
> /usr/lib/python2.7/dist-packages/salt/crypt.py(439)_authenticate()
-> break
(Pdb) l
434  	        while True:
435  	            try:
436  	                creds = yield self.sign_in()
437  	            except SaltClientError:
438  	                import pdb; pdb.set_trace()
439  ->	                break
440  	            if creds == 'retry':
441  	                if self.opts.get('caller'):
442  	                    print('Minion failed to authenticate with the master, '
443  	                          'has the minion key been accepted?')
444  	                    sys.exit(2)
```

I catch this excetpion 
```
 529         try:                                                                                                                                                                                 
 530             self.opts['pillar'] = salt.pillar.get_pillar(                        
 531                 self.opts,                                                       
 532                 self.opts['grains'],                                             
 533                 self.opts['id'],                                                 
 534                 self.opts['environment'],                                        
 535                 pillarenv=self.opts.get('pillarenv'),                            
 536             ).compile_pillar()                                                   
 537         except:                                                                  
 538             import traceback                                                     
 539             ex = sys.exc_info()                                                  
 540             traceback.print_tb(ex[2])                                            
```
and print traceback.
```
[INFO    ] Determining pillar cache
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 535, in gen_modules
    pillarenv=self.opts.get('pillarenv'),
  File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 170, in compile_pillar
    dictkey='pillar',
  File "/usr/lib/python2.7/dist-packages/salt/utils/async.py", line 74, in wrap
    ret = self._block_future(ret)
  File "/usr/lib/python2.7/dist-packages/salt/utils/async.py", line 84, in _block_future
    return future.result()
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 151, in crypted_transfer_decode_dictentry
    yield self.auth.authenticate()
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
SaltClientError: Attempt to authenticate with the salt master failed
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 335, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 53, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 133, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 196, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 558, in highstate
    mocked=kwargs.get('mock', False))
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 3201, in __init__
    BaseHighState.__init__(self, opts)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2294, in __init__
    self.opts = self.__gen_opts(opts)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2321, in __gen_opts
    mopts = self.client.master_opts()
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 1329, in master_opts
    return self.channel.send(load)
  File "/usr/lib/python2.7/dist-packages/salt/utils/async.py", line 74, in wrap
    ret = self._block_future(ret)
  File "/usr/lib/python2.7/dist-packages/salt/utils/async.py", line 84, in _block_future
    return future.result()
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 231, in send
    ret = yield self._crypted_transfer(load, tries=tries, timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 196, in _crypted_transfer
    yield self.auth.authenticate()
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
```

**Comment by cro** [comment]
Multimaster has seen a lot of attention in 2016.3. It might be worth it to give the 2016.3 Windows minion a try.
