### ISSUE TITLE
Beryllium error 

### ISSUE THREAD

**Issue by petedao** [saltstack/salt#29115]
Hi 

I upgraded a minion to Beryllium and then my master can't connect to it anymore.  It is giving: 
```
SERVER8:
    Minion did not return. [No response]
```
=========== here is what is in the minion log ===========
```
[root@SERVER8 ~]# salt-minion  --version
salt-minion 2015.8.1 (Beryllium)
[root@DBSERVER8 ~]# tail -f /var/log/salt/minion
2015-11-23 03:52:11,965 [salt.loader                              ][CRITICAL][17234] Failed to load grains defined in grain file roles.pprint in function <function pprint at 0x2aae2c2e42a8>, error:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/loader.py", line 623, in grains
    ret = fun()
TypeError: pprint() takes at least 1 argument (0 given)
2015-11-23 03:52:14,819 [salt.loader                              ][CRITICAL][17234] Failed to load grains defined in grain file roles.pprint in function <function pprint at 0x2aae2c2e42a8>, error:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/loader.py", line 623, in grains
    ret = fun()
TypeError: pprint() takes at least 1 argument (0 given)
```

**Comment by cachedout** [comment]
Do you have a customized grain called `pprint` by chance?

**Comment by cachedout** [comment]
Closed for lack of response.
