### ISSUE TITLE
Backtrace in state `ssh_known_hosts.present` when `ssh-keygen` is not available

### ISSUE THREAD

**Issue by eliasp** [saltstack/salt#29111]
When the binary/executable `ssh-keygen` is not present on a system, the state `ssh_known_hosts.present` will end up in a backtrace instead of dealing a bit more gracefully with this situation:
```
          ID: icons-git-known-hosts
    Function: ssh_known_hosts.present
        Name: bitbucket.org
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1591, in call                                                                                          
                  **cdata['kwargs'])                                                                                                                                               
                File "/usr/lib/python2.7/site-packages/salt/states/ssh_known_hosts.py", line 122, in present                                                                       
                  config=config)                                                                                                                                                   
                File "/usr/lib/python2.7/site-packages/salt/modules/ssh.py", line 820, in check_known_host
                  known_host = get_known_host(user, hostname, config=config, port=port)
                File "<string>", line 2, in get_known_host
                File "/usr/lib/python2.7/site-packages/salt/utils/decorators/__init__.py", line 151, in wrapped
                  'The {0!r} binary was not found in $PATH.'.format(exe)
              CommandNotFoundError: The 'ssh-keygen' binary was not found in $PATH.
     Started: 00:24:27.479982
    Duration: 4.518 ms
     Changes:   
```
```
    Salt Version:
               Salt: 2015.8.1
     
    Dependency Versions:
             Jinja2: 2.7.2
           M2Crypto: 0.21.1
               Mako: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.7.0
             Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: Not Installed
            timelib: Not Installed
     
    System Versions:
               dist: centos 7.1.1503 Core
            machine: x86_64
            release: 4.3.0-gentoo
             system: CentOS Linux 7.1.1503 Core
```

**Comment by jfindlay** [comment]
@eliasp, thanks for the report.
