### ISSUE TITLE
Unable to use htpasswd in 2015.5.6

### ISSUE THREAD

**Issue by scubahub** [saltstack/salt#29157]
Here is the versions report

```
           Salt: 2015.5.6
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: Not Installed
```

I tried following the example in https://docs.saltstack.com/en/2015.5/ref/states/all/salt.states.htpasswd.html

Here is my sls:

```
add-nagiosadmin-password:
  webutil.user_exists:
    - name: nagiosadmin
    - password: nagiosadmin
    - htpasswd_file: /etc/nagios/passwd
    - force: True
```

When I try to run the state I get an exception:

```
          ID: add-nagiosadmin-password
    Function: webutil.user_exists
        Name: nagiosadmin
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.6/site-packages/salt/state.py", line 1561, in call
                  **cdata['kwargs'])
                File "/usr/lib64/python2.6/contextlib.py", line 34, in __exit__
                  self.gen.throw(type, value, traceback)
                File "/usr/lib/python2.6/site-packages/salt/utils/context.py", line 42, in func_globals_inject
                  yield
                File "/usr/lib/python2.6/site-packages/salt/state.py", line 1561, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.6/site-packages/salt/states/htpasswd.py", line 73, in user_exists
                  runas=runas)
              TypeError: useradd_all() got an unexpected keyword argument 'runas'
     Started: 16:07:16.220945
    Duration: 5.428 ms
     Changes:
```

I also tried to do the same via module.run

```
add-nagiosadmin-password:
  module.run:
    - name: apache.useradd
    - user: nagiosadmin
    - password: nagiosadmin
    - pwfile: /etc/nagios/passwd
```

while this approach did indeed add the entry to the passwd file, the state fails

```
          ID: add-nagiosadmin-password
    Function: module.run
        Name: apache.useradd
      Result: False
     Comment: Module function apache.useradd threw an exception. Exception: 'out'
     Started: 16:00:44.945046
    Duration: 6.131 ms
     Changes:
```

**Comment by jfindlay** [comment]
@scubahub, are you able to try this on a later release?  I think this is something that has already been fixed.
