### ISSUE TITLE
Problem with using win_servermanager.installed with the 2014.7.8 x86 salt package 

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#29169]
salt minion version: 2014.7.8
salt-master: salt 2014.7.8 (Helium)

When I install the x86 2014.7.8 package on a x64 windows minion (both windows server 2008 and 2012) I receive an error while using the state win_servermanager.installed

I'm using the following state file:

```
ISWebserverRole:
  win_servermanager.installed:
    - force: True
    - recurse: True
    - name: Web-Server
```

I receive the following error:

```
----------
          ID: ISWebserverRole
    Function: win_servermanager.installed
        Name: Web-Server
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "c:\salt\bin\lib\site-packages\salt\state.py", line 1542, in call
                  **cdata['kwargs'])
                File "c:\salt\bin\lib\site-packages\salt\states\win_servermanager.py", line 38, in installed
                  if name not in __salt__['win_servermanager.list_installed']():
                File "c:\salt\bin\lib\site-packages\salt\modules\win_servermanager.py", line 81, in list_installed
                  if splt[0] == '[X]':
              IndexError: list index out of range
     Started: 20:13:09.532000
    Duration: 359.0 ms
     Changes:   
```

This works just fine with the x64 package on a x64 windows server 2008 and 2012 machine.

**Comment by twangboy** [comment]
We don't support 32bit install of salt on 64bit machines. See https://github.com/saltstack/salt/issues/30350 for one of the many reasons why

**Comment by Ch3LL** [comment]
The makes sense. I will close this then.
