### ISSUE TITLE
cron.file fails on non changed cron file

### ISSUE THREAD

**Issue by bmdevel** [saltstack/salt#29181]
If salt state cron.file is used with a static cron file, each call to an existing cron with no changes to cron will fail with:

```
An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1591, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/states/cron.py", line 534, in file
                  if cron_ret['retcode']:
              UnboundLocalError: local variable 'cron_ret' referenced before assignment
```

This happens because, at line mentioned in error message, there is a condition check on `cron_ret['retcode']` at line 534 which is only available if `ret['changes']` condition on line 526 is true

current workaround will be:
- make the cron file on salt master a template and include some change (like a current timestamp) 

```
salt-minion --versions-report
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.4.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-32-generic
         system: Ubuntu 14.04 trusty
```

**Comment by jfindlay** [comment]
@bmdevel, thanks for the report.  This has been fixed in #27585 which will come out in 2015.8.3 in about a week.
