### ISSUE TITLE
salt-minion fail to autenticate

### ISSUE THREAD

**Issue by usernkey** [saltstack/salt#29243]
I have a configuration with two master master1 and master 1 each one of it connected to two syndacation synd01 synd02

Minion are configure to  connect to both syndation.

Minion is able to connect correctly to synd01 but fail to connect to synd02 giving this error.

I'm using salt master,minion and syndacation all at the same version 2015.8.1
```bash
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'centos7.cmnet.internal', 'tcp://10.0.10.141:4506', 'clear')
[INFO    ] The salt minion is shut down
[ERROR   ] Minion failed to start:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 81, in minion_process
    minion.start()
  File "/usr/lib/python2.7/site-packages/salt/cli/daemons.py", line 275, in start
    self.minion.tune_in()
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1634, in tune_in
    self.sync_connect_master()
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 725, in sync_connect_master
    raise six.reraise(*future_exception)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 732, in connect_master
    master, self.pub_channel = yield self.eval_master(self.opts, self.timeout, self.safe)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 496, in eval_master
    yield pub_channel.connect()
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.7/site-packages/salt/transport/zeromq.py", line 325, in connect
    yield self.auth.authenticate()
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
SaltClientError: Attempt to authenticate with the salt master failed
[WARNING ] ** Restarting minion **
[INFO    ] Sleeping random_reauth_delay of 1 seconds
```

**Comment by jtand** [comment]
@usernkey Can you provide the sanitized configs for your master/minion/syndics? I don't need the full config, just the parts in the minion that show which master(s) as well as the syndic sections from the syndic(s)/master(s). Thanks!

**Comment by usernkey** [comment]
here we are

[root@master01 ~]# cat /etc/salt/master | egrep -v "^#|^$"
state_top: top.sls
file_roots:
  base:
    - /srv/salt/states
pillar_roots:
  base:
    - /srv/salt/pillars
order_masters: True
master_id: master01.cmnet.internal



[root@master02 ~]#  cat /etc/salt/master | egrep -v "^#|^$"
state_top: top.sls
file_roots:
  base:
    - /srv/salt/states
pillar_roots:
  base:
    - /srv/salt/pillars
order_masters: True
master_id: master02.cmnet.internal

[root@synd01 ~]# cat /etc/salt/master | egrep -v "^#|^$"
state_top: top.sls
file_roots:
  base:
    - /srv/salt/states
pillar_roots:
  prod:
    - /srv/salt/pillars
syndic_master:
   - master01.cmnet.internal
   - master02.cmnet.internal
master_id: synd01.cmnet.internal

[root@synd01 ~]# cat /etc/salt/minion | egrep -v "^#|^$"
id: synd01.cmnet.internal


[root@synd02 ~]# cat /etc/salt/master | egrep -v "^#|^$"
state_top: top.sls
file_roots:
  base:
    - /srv/salt/states
pillar_roots:
  prod:
    - /srv/salt/pillars
syndic_master:
   - master01.cmnet.internal
   - master02.cmnet.internal
master_id: synd02.cmnet.internal

[root@synd02 ~]# cat /etc/salt/minion | egrep -v "^#|^$"
id: synd02.cmnet.internal


now I was trying to connect to just the second but still fail

[root@centos7 ~]# cat /etc/salt/minion | egrep -v "^#|^$"
master: synd02.cmnet.internal

before was 

master: 
   - synd01.cmnet.internal
    - synd02.cmnet.internal

**Comment by usernkey** [comment]
but if I configure just the synd01 works perfectly

**Comment by usernkey** [comment]
I was able to get rid of it but now I'm facing another one but it is not for github. :)

minion is correct registered but  salt  test.ping does not return any value running from synd or master  

[root@synd02 master]# salt centos7.cmnet.internal grains.items
centos7.cmnet.internal:
    Minion did not return. [No response]

instead salt-call yes 

[root@centos7 ~]# salt-call test.ping
local:
    True

original issue was in my configuration: 2 mistakes mainly

I was copying private and public keys between synd servers
synd02 had the firewalld running

**Comment by usernkey** [comment]
I small change to my previos statement sync server must share the same keys this was the fix to my second issue. so the fix to the 1 fist issue was just stop the firewalld
