### ISSUE TITLE
btmp beacon plugin bug

### ISSUE THREAD

**Issue by githubcdr** [saltstack/salt#29468]
Hi,

I noticed 2 bugs in the btmp beacon;
- btmp data is parsed incorrectly, possible also true for wtmp beacon
- this causes utf-8 decode errors when using "salt-run state.event pretty=True", this process stops after this error.

Details

```
Exception occurred in runner state.event: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 337, in low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/runners/state.py", line 198, in event
    indent=None if not pretty else 4)))
  File "/usr/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 209, in encode
    chunks = list(chunks)
  File "/usr/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 390, in _iterencode_dict
    yield _encoder(value)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe1 in position 0: invalid continuation byte
```

running the native python eventlisten.py I noticed a lot of hex data in the btmp beacon data.

```
Event fired at Sun Dec  6 14:59:18 2015
*************************
Tag: salt/beacon/redacted/btmp/
Data:
{'_stamp': '2015-12-06T13:59:18.100894',
 'data': {'PID': 0,
          'addr': 0,
          'exit_status': 0,
          'hostname': '\xe1>dV\x00\x00\x00\x00\xca~]\x12\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00
\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x06\x00\x00\x00_o\x00\x00ssh:notty\x00\x00\x00\x00\x00\x00\x00\
x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00root\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\
x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00193.233.14.21',
          'id': 'redacted',
          'inittab': '',
          'line': '',
          'session': 0,
          'time': 0,
          'type': 0,
          'user': ''},
 'tag': 'salt/beacon/redacted/btmp/'}
Event fired at Sun Dec  6 14:59:18 2015
*************************
Tag: salt/run/20151206145805122201/ret
Data:
{'_stamp': '2015-12-06T13:59:18.107078',
 'fun': 'runner.state.event',
 'jid': '20151206145805122201',
 'return': 'Exception occurred in runner state.event: Traceback (most recent call last):\n  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 337, in low\n    data[\'return\'] = self.functions[fun](*args, **kwargs)\n  File "/usr/lib/python2.7/dist-packages/salt/runners/state.py", line 198, in event\n    indent=None if not pretty else 4)))\n  File "/usr/lib/python2.7/json/__init__.py", line 250, in dumps\n    sort_keys=sort_keys, **kw).encode(obj)\n  File "/usr/lib/python2.7/json/encoder.py", line 209, in encode\n    chunks = list(chunks)\n  File "/usr/lib/python2.7/json/encoder.py", line 434, in _iterencode\n    for chunk in _iterencode_dict(o, _current_indent_level):\n  File "/usr/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict\n    for chunk in chunks:\n  File "/usr/lib/python2.7/json/encoder.py", line 390, in _iterencode_dict\n    yield _encoder(value)\nUnicodeDecodeError: \'utf8\' codec can\'t decode byte 0xe1 in position 0: invalid continuation byte\n',
 'success': False,
 'user': 'sudo_codar'}
```

```
[root@flaim ~]# salt-minion --versions
Salt Version:
           Salt: 2015.8.3

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.21.1
           Mako: 1.0.1
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: 0.6.3
        Tornado: 4.2.1
            ZMQ: 4.1.2
           cffi: 0.8.6
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: 1.3.7
        libnacl: 1.4.3
   msgpack-pure: 0.1.3
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: 0.23.2
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: 0.2.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-71-generic
         system: Ubuntu 14.04 trusty
```

The salt-run command shouldn't crash on invalid utf-8 data.

**Comment by jfindlay** [comment]
@githubcdr, thanks for the report.  This looks like an unfortunate crash that might be handled easily by a processing the beacon return data in a `try except` statement.

**Comment by rc1405** [comment]
I ran into this problem on CentOS 7 with both btmp and wtmp beacons.  I've attached the modifications for both that work on CentOS 7.  They could probably use more testing on other releases. 


[wtmp.py.txt](https://github.com/saltstack/salt/files/619228/wtmp.py.txt)
[btmp.py.txt](https://github.com/saltstack/salt/files/619224/btmp.py.txt)
