### ISSUE TITLE
patchlevel detection broken for openSuSE

### ISSUE THREAD

**Issue by m7v8** [saltstack/salt#29484]
In Version 2015.8.3 executing:
```
salt-ssh --force-color * state.sls integration pillar=...
```
yields:
```
stderr:
        [CRITICAL] Unable to import msgpack or msgpack_pure python modules
        Traceback (most recent call last):
          File "/tmp/.root_dcdf8c_salt/salt-call", line 4, in <module>
            salt_call()
          File "/tmp/.root_dcdf8c_salt/salt/scripts.py", line 331, in salt_call
            client.run()
          File "/tmp/.root_dcdf8c_salt/salt/cli/call.py", line 43, in run
            caller = salt.cli.caller.Caller.factory(self.config)
          File "/tmp/.root_dcdf8c_salt/salt/cli/caller.py", line 78, in factory
            return ZeroMQCaller(opts, **kwargs)
          File "/tmp/.root_dcdf8c_salt/salt/cli/caller.py", line 269, in __init__
            super(ZeroMQCaller, self).__init__(opts)
          File "/tmp/.root_dcdf8c_salt/salt/cli/caller.py", line 101, in __init__
            self.minion = salt.minion.SMinion(opts)
          File "/tmp/.root_dcdf8c_salt/salt/minion.py", line 511, in __init__
            opts['grains'] = salt.loader.grains(opts)
          File "/tmp/.root_dcdf8c_salt/salt/loader.py", line 624, in grains
            ret = fun()
          File "/tmp/.root_dcdf8c_salt/salt/grains/core.py", line 1190, in os_data
            grains['lsb_distrib_release'] = version + ' SP' + patch
        UnboundLocalError: local variable 'patch' referenced before assignment
```
The minion is an OpenSuSE and the content of /etc/SuSE-release:
```
openSUSE 11.4 (x86_64)
VERSION = 11.4
CODENAME = Celadon
```
The core.py expects a "patchlevel" line in SuSE-release which will be the value of patch.
The patchlevel line is not present in the OpenSuSE version 11 to 13.

**Comment by jfindlay** [comment]
@m7v8, thanks for the report.
