### ISSUE TITLE
salt-ssh ansible roster does not work

### ISSUE THREAD

**Issue by MorphBonehunter** [saltstack/salt#29522]
Hi @all,

i'm new to salt and we evaluate at the moment the migration from ansible to salt.
So as we want to manage systems where we do not want to install the minion software and try to use salt-ssh. For simplicity we want to use the ansible hostfile but i can not get it to work.

sample ansible host file:
   
    [test]
    server1
    server2
    
    [broken]
    server3

when i try to run it with the following cmd:

    salt-ssh -l all --roster ansible --roster-file ansible_hosts '*' test.ping

i allways got:

    [DEBUG   ] Missing configuration file: /etc/salt/master
    [TRACE   ] None of the required configuration sections, 'logstash_udp_handler' and 'logstash_zmq_handler', were found the in the configuration. Not loading the Logstash logging handlers module.
    [TRACE   ] The required configuration section, 'fluent_handler', was not found the in the configuration. Not loading the fluent logging handlers module.
    [DEBUG   ] Configuration file path: /etc/salt/master
    [DEBUG   ] LazyLoaded ansible.targets
    [DEBUG   ] Matched minions: {'[broken]': {}, '[test]': {}}
    [DEBUG   ] LazyLoaded roots.envs
    [DEBUG   ] Could not LazyLoad roots.init
    [DEBUG   ] Updating roots fileserver cache
    [TRACE   ] Lockfile /var/cache/salt/master/file_lists/roots/.base.w created
    [TRACE   ] Lockfile /var/cache/salt/master/file_lists/roots/.base.w removed
    [DEBUG   ] LazyLoaded local_cache.prep_jid
    Process Process-1:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
        self.run()
      File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
        self._target(*self._args, **self._kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 343, in handle_routine
        **target)
    TypeError: __init__() takes at least 5 arguments (15 given)
    Process Process-2:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
        self.run()
      File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
        self._target(*self._args, **self._kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 343, in handle_routine
        **target)
    TypeError: __init__() takes at least 5 arguments (15 given)
    [ERROR   ] Target '[broken]' did not return any data, probably due to an error.
    [ERROR   ] An un-handled exception was caught by salt's global exception handler:
    TypeError: __init__() takes at least 5 arguments (14 given)
    Traceback (most recent call last):
      File "/usr/bin/salt-ssh", line 10, in <module>
        salt_ssh()
      File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 377, in salt_ssh
        client.run()
      File "/usr/lib/python2.7/dist-packages/salt/cli/ssh.py", line 21, in run
        ssh.run()
      File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 549, in run
        ret = self.key_deploy(host, ret)
      File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 269, in key_deploy
        self._key_deploy_run(host, target, False)
      File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 302, in _key_deploy_run
        **target)
    TypeError: __init__() takes at least 5 arguments (14 given)
    Traceback (most recent call last):
      File "/usr/bin/salt-ssh", line 10, in <module>
        salt_ssh()
      File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 377, in salt_ssh
        client.run()
      File "/usr/lib/python2.7/dist-packages/salt/cli/ssh.py", line 21, in run
        ssh.run()
      File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 549, in run
        ret = self.key_deploy(host, ret)
      File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 269, in key_deploy
        self._key_deploy_run(host, target, False)
      File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 302, in _key_deploy_run
        **target)
    TypeError: __init__() takes at least 5 arguments (14 given)

I also tried instead of ```'*'``` the ```all``` keyword but i got always this error.
It seams that the roster detects the ```[groups]``` but could not parse the hosts.
Maybe i did something wrong?

The system where we try to run the salt-ssh ist an Debian 8.
We've used the repo.saltstack.com Repo and installed Version 2015.8.3+ds-1.

**Comment by jfindlay** [comment]
Thanks for reporting, @MorphBonehunter, this looks like a bug to me.

**Comment by jfindlay** [comment]
```console
# cat >> ansible_hosts
[test]
server1
server2

[broken]
server3
```
```python-traceback
# salt-ssh -l all --roster ansible --roster-file ah '*' test.ping
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: jmoney-main
[TRACE   ] None of the required configuration sections, 'logstash_udp_handler' and 'logstash_zmq_handler', were found the in the configuration. Not loading the Logstash logging handlers module.
[TRACE   ] The required configuration section, 'fluent_handler', was not found the in the configuration. Not loading the fluent logging handlers module.
[DEBUG   ] Configuration file path: /etc/salt/master
[DEBUG   ] LazyLoaded ansible.targets
No hosts found with target * of type glob
jmoney-main salt (v2015.8.3) # salt-ssh -l all --roster ansible --roster-file ansible_hosts '*' test.ping
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: jmoney-main
[TRACE   ] None of the required configuration sections, 'logstash_udp_handler' and 'logstash_zmq_handler', were found the in the configuration. Not loading the Logstash logging handlers module.
[TRACE   ] The required configuration section, 'fluent_handler', was not found the in the configuration. Not loading the fluent logging handlers module.
[DEBUG   ] Configuration file path: /etc/salt/master
[DEBUG   ] LazyLoaded ansible.targets
[DEBUG   ] Matched minions: {'[broken]': {}, '[test]': {}}
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init
[DEBUG   ] Updating roots fileserver cache
[TRACE   ] Lockfile /var/cache/salt/master/file_lists/roots/.base.w created
[TRACE   ] Lockfile /var/cache/salt/master/file_lists/roots/.base.w removed
[DEBUG   ] In saltenv 'base', looking at rel_path u'_modules/salt_cluster.py' to resolve u'salt://_modules/salt_cluster.py'
[DEBUG   ] In saltenv 'base', ** considering ** path u'/var/cache/salt/master/files/base/_modules/salt_cluster.py' to resolve u'salt://_modules/salt_cluster.py'
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache u'salt://_modules/salt_cluster.py'
[DEBUG   ] In saltenv 'base', looking at rel_path u'_states/salt_cluster.py' to resolve u'salt://_states/salt_cluster.py'
[DEBUG   ] In saltenv 'base', ** considering ** path u'/var/cache/salt/master/files/base/_states/salt_cluster.py' to resolve u'salt://_states/salt_cluster.py'
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache u'salt://_states/salt_cluster.py'
[DEBUG   ] LazyLoaded local_cache.prep_jid
Process Process-2:
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/root/salt/salt/client/ssh/__init__.py", line 343, in handle_routine
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    **target)
TypeError: __init__() takes at least 5 arguments (15 given)
    self._target(*self._args, **self._kwargs)
  File "/root/salt/salt/client/ssh/__init__.py", line 343, in handle_routine
    **target)
TypeError: __init__() takes at least 5 arguments (15 given)
[ERROR   ] Target '[broken]' did not return any data, probably due to an error.
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: __init__() takes at least 5 arguments (14 given)
Traceback (most recent call last):
  File "/usr/local/bin/salt-ssh", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/root/salt/scripts/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/root/salt/salt/scripts.py", line 377, in salt_ssh
    client.run()
  File "/root/salt/salt/cli/ssh.py", line 21, in run
    ssh.run()
  File "/root/salt/salt/client/ssh/__init__.py", line 549, in run
    ret = self.key_deploy(host, ret)
  File "/root/salt/salt/client/ssh/__init__.py", line 269, in key_deploy
    self._key_deploy_run(host, target, False)
  File "/root/salt/salt/client/ssh/__init__.py", line 302, in _key_deploy_run
    **target)
TypeError: __init__() takes at least 5 arguments (14 given)
Traceback (most recent call last):
  File "/usr/local/bin/salt-ssh", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/root/salt/scripts/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/root/salt/salt/scripts.py", line 377, in salt_ssh
    client.run()
  File "/root/salt/salt/cli/ssh.py", line 21, in run
    ssh.run()
  File "/root/salt/salt/client/ssh/__init__.py", line 549, in run
    ret = self.key_deploy(host, ret)
  File "/root/salt/salt/client/ssh/__init__.py", line 269, in key_deploy
    self._key_deploy_run(host, target, False)
  File "/root/salt/salt/client/ssh/__init__.py", line 302, in _key_deploy_run
    **target)
TypeError: __init__() takes at least 5 arguments (14 given)
```
```yaml
# salt --versions
Salt Version:
           Salt: 2015.8.3

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
           Mako: 1.0.0
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: debian 8.2
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.2
```

**Comment by MorphBonehunter** [comment]
Another Year, another try :)
I've skip the ansible rooster file and try to use the "flat file" methode for now...this works like expected.
But then i came to the point where i want to define cli options in an saltfile and after try and error i found in the doc the following:

"The option keys specified must match the destination attributes for the options specified in the parser salt.utils.parsers.SaltSSHOptionParser"

So i realy have to read the sources to determine the right settings? Is this not a little bit of user unfriendly or missed i something?

**Comment by jfindlay** [comment]
@MorphBonehunter, would you mind opening another issue for this?  Thanks.

**Comment by MorphBonehunter** [comment]
@jfindlay i did it another way: #30634

**Comment by edgan** [comment]
This is a mismatch between the Single class and the usage of it by handle_routine.

Here is a possible fix/workaround for the issue:
https://github.com/saltstack/salt/compare/develop...edgan:salt-ssh-handle_routine

Comment on the thing that caused this:
https://github.com/saltstack/salt/commit/de8cc9af7d6ca5a8c1f977f22ff99bbd79f7ffde#commitcomment-18637267

PR that unmasks real problem:
PR #35452

**Comment by mostafahussein** [comment]
Sorry for the dump question, Is this module meant to manage Ansible through Salt? so i can run a playbook on a specific node through Salt ssh which will talk to the Ansible cli ?

**Comment by MorphBonehunter** [comment]
@mostafahussein No, it is the possibility for using an ansible rooster file in salt-ssh.

**Comment by MorphBonehunter** [comment]
BTW: as i saw the merged pull request i hopped that this fixed this issue...it doesn't:
```
cat ansible_hosts 
[test]
server1
server2

[broken]
server3
```
```
salt-ssh -l all --roster ansible --roster-file ansible_hosts '*' test.ping
[DEBUG   ] Reading configuration from /etc/salt/master
[TRACE   ] The required configuration section, 'fluent_handler', was not found the in the configuration. Not loading the fluent logging handlers module.
[TRACE   ] None of the required configuration sections, 'logstash_udp_handler' and 'logstash_zmq_handler', were found in the configuration. Not loading the Logstash logging handlers module.
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] LazyLoaded ansible.targets
[DEBUG   ] Matched minions: {'[broken]': {}, '[test]': {}}
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[DEBUG   ] Updating roots fileserver cache
[TRACE   ] Lockfile /var/cache/salt/master/file_lists/roots/.base.w created
[TRACE   ] Lockfile /var/cache/salt/master/file_lists/roots/.base.w removed
[DEBUG   ] LazyLoaded local_cache.prep_jid
[DEBUG   ] Adding minions for job 20170110111037388892: ['[broken]', '[test]']
[ERROR   ] An un-handled exception from the multiprocessing process 'MultiprocessingProcess-1' was caught:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/process.py", line 644, in _run
    return self._original_run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 416, in handle_routine
    **target)
TypeError: __init__() takes at least 5 arguments (17 given)
Process MultiprocessingProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/site-packages/salt/utils/process.py", line 644, in _run
    return self._original_run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 416, in handle_routine
    **target)
TypeError: __init__() takes at least 5 arguments (17 given)
[ERROR   ] An un-handled exception from the multiprocessing process 'MultiprocessingProcess-2' was caught:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/process.py", line 644, in _run
    return self._original_run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 416, in handle_routine
    **target)
TypeError: __init__() takes at least 5 arguments (17 given)
Process MultiprocessingProcess-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/site-packages/salt/utils/process.py", line 644, in _run
    return self._original_run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 416, in handle_routine
    **target)
TypeError: __init__() takes at least 5 arguments (17 given)
[ERROR   ] Target '[broken]' did not return any data, probably due to an error.
[DEBUG   ] LazyLoaded nested.output
[TRACE   ] data = {'[broken]': "Target '[broken]' did not return any data, probably due to an error."}
[broken]:
    Target '[broken]' did not return any data, probably due to an error.
[ERROR   ] Target '[test]' did not return any data, probably due to an error.
[DEBUG   ] LazyLoaded nested.output
[TRACE   ] data = {'[test]': "Target '[test]' did not return any data, probably due to an error."}
[test]:
    Target '[test]' did not return any data, probably due to an error.

```

**Comment by pkoch** [comment]
For reference, I needed to change the `Single` call in `handle_routine` and provide the `id_` argument.

**Comment by pkoch** [comment]
Actually,  I was missing the `hosts` key in my roster. I think it would be pleasant to have something like `target = dict({'host': host}, **target)` just before the `Single` call, effectively letting the `host` become optional (since the id is probably the host, anyway).
