### ISSUE TITLE
ssh_auth should report missing source

### ISSUE THREAD

**Issue by schaarsc** [saltstack/salt#29654]
```
  ssh_auth.present:
    - user: myuser
    - source: salt://ssh_keys/key_is_missing.pub
```
this results in an exception :
```
    Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1591, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/states/ssh_auth.py", line 288, in present
                  saltenv=__env__)
                File "/usr/lib/python2.7/dist-packages/salt/modules/cp.py", line 334, in get_file_str
                  with salt.utils.fopen(fn_, 'r') as fp_:
                File "/usr/lib/python2.7/dist-packages/salt/utils/__init__.py", line 1208, in fopen
                  fhandle = open(*args, **kwargs)
              TypeError: coercing to Unicode: need string or buffer, bool found
```

Expected result:
report error for example: 
```
"Comment: Source file salt://ssh_keys/key_is_missing.pub is missing."
```

tested with version: 2015.8.1

**Comment by abednarik** [comment]
Looks like [here](https://github.com/saltstack/salt/blob/2015.8/salt/states/ssh_auth.py#L285) only checks is source is not empty. I think we can also check is file exists. IIf that is Ok I can send a PR.
Will try to review the complete trace of that call because where fopen is used there is something try block to catch that error.

**Comment by jfindlay** [comment]
@schaarsc, thanks for the report.
