### ISSUE TITLE
SuSE packages for salt-minion 2015.8.3-219.3 missing dependencies

### ISSUE THREAD

**Issue by racooper** [saltstack/salt#29714]
having multiple issues with salt-minion 2015.8.3-219.3 from http://download.opensuse.org/repositories/devel:languages:python/SLE_11_SP3/devel:languages:python.repo.  First, a new code dependency on python-singledispatch was added but the package was not added to the salt packages as a dependency.  After getting past that, there is a missing dependency on backports_abc that does not appear to exist in the SuSE repos.

````
Traceback (most recent call last):
  File "/usr/bin/salt-minion", line 26, in <module>
    salt_minion()
  File "/usr/lib64/python2.6/site-packages/salt/scripts.py", line 106, in salt_minion
    import salt.cli.daemons
  File "/usr/lib64/python2.6/site-packages/salt/cli/daemons.py", line 47, in <module>
    from salt.utils import parsers, ip_bracket
  File "/usr/lib64/python2.6/site-packages/salt/utils/parsers.py", line 26, in <module>
    import salt.config as config
  File "/usr/lib64/python2.6/site-packages/salt/config.py", line 40, in <module>
    import salt.utils.sdb
  File "/usr/lib64/python2.6/site-packages/salt/utils/sdb.py", line 9, in <module>
    import salt.loader
  File "/usr/lib64/python2.6/site-packages/salt/loader.py", line 30, in <module>
    import salt.utils.event
  File "/usr/lib64/python2.6/site-packages/salt/utils/event.py", line 81, in <module>
    import salt.payload
  File "/usr/lib64/python2.6/site-packages/salt/payload.py", line 17, in <module>
    import salt.crypt
  File "/usr/lib64/python2.6/site-packages/salt/crypt.py", line 44, in <module>
    import tornado.gen
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 97, in <module>
    from singledispatch import singledispatch  # backport
ImportError: No module named singledispatch
````
````
Traceback (most recent call last):
  File "/usr/bin/salt-minion", line 26, in <module>
    salt_minion()
  File "/usr/lib64/python2.6/site-packages/salt/scripts.py", line 106, in salt_minion
    import salt.cli.daemons
  File "/usr/lib64/python2.6/site-packages/salt/cli/daemons.py", line 47, in <module>
    from salt.utils import parsers, ip_bracket
  File "/usr/lib64/python2.6/site-packages/salt/utils/parsers.py", line 26, in <module>
    import salt.config as config
  File "/usr/lib64/python2.6/site-packages/salt/config.py", line 40, in <module>
    import salt.utils.sdb
  File "/usr/lib64/python2.6/site-packages/salt/utils/sdb.py", line 9, in <module>
    import salt.loader
  File "/usr/lib64/python2.6/site-packages/salt/loader.py", line 30, in <module>
    import salt.utils.event
  File "/usr/lib64/python2.6/site-packages/salt/utils/event.py", line 81, in <module>
    import salt.payload
  File "/usr/lib64/python2.6/site-packages/salt/payload.py", line 17, in <module>
    import salt.crypt
  File "/usr/lib64/python2.6/site-packages/salt/crypt.py", line 44, in <module>
    import tornado.gen
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 113, in <module>
    from backports_abc import Generator as GeneratorType
ImportError: No module named backports_abc
````

**Comment by racooper** [comment]
More info: looks like the issue is with python-tornado, specifically version 4.3-1.1 from the devel:languages:python repo.

**Comment by jfindlay** [comment]
@racooper, thanks for the report.  Ping, @aboe76.

**Comment by aboe76** [comment]
@racooper, where did python-singledispatch become a dependency, or is a special salt command you want to use?

Same goes for python backports_abc? I didn't find it in the requirements files...

**Comment by racooper** [comment]
apparently it's a dependency of python-tornado 4.3, not of salt. Further investigation found that to be the case. If I reverted to python-tornado to 4.2, then singledispatch and backports_abc are not requested.  Unfortunately, the only source for python-tornado 4.2 is a mirror I found at http://mirrors.vbi.vt.edu/linux/opensuse/repositories/devel:/languages:/python/SLE_11_SP3/x86_64/python-tornado-4.2.1-5.3.x86_64.rpm; it's not available from the repos any longer.

**Comment by webtrekker** [comment]
I can confirm, by replacing python-tornado-4.3-6.1.x86_64.rpm  with python-tornado-4.2.1-5.3.x86_64.rpm in my internal repo I was able to install salt, salt-master, and salt-minion.  And now when starting salt-master I don't get the errors that racooper displayed above.

**Comment by cachedout** [comment]
+1 This has actually broken Salt's own test suite, I'm afraid. 

https://jenkins.saltstack.com/view/2015.8%20Branch/job/salt-2015.8-linode-opensuse13/1381/console

**Comment by aboe76** [comment]
See also https://bugzilla.novell.com/show_bug.cgi?id=958984,

I have notified alexandre which is the maintainer of python-tornado in devel:languages:python,

**Comment by thatch45** [comment]
I reached out to some higher ups at Suse to try and get this looked at, they really just need to make a package for python-backports_abc and add the deps to the tornado spec for that and python-singledispatch

**Comment by aboe76** [comment]
@thatch45 :+1: for python-backports_abc see:
https://build.opensuse.org/request/show/350635

and for singledispatch:
https://build.opensuse.org/package/show/devel:languages:python/python-singledispatch

**Comment by 1605200517** [comment]
dear all, happy new year! 

where to read on how to hotfix this bug in the following setup or you can give a more specific advice too?

We run the following integration test simualtion:

- SLES12 on Docker 1.6.2 with Python 2.7.9; a public base image from darksheer ITSEC guy aka buddhalabs
- following Dockerfile
- features tornado asset (from Docker build log) python-tornado-4.3-1.1.x86_64 

Dockerfile snip:

FROM darksheer/sles12

RUN zypper --no-gpg-checks --non-interactive addrepo http://download.opensuse.org/repositories/devel:languages:python/SLE_12/devel:languages:python.repo
RUN zypper --no-gpg-checks --non-interactive refresh
RUN zypper --no-gpg-checks --non-interactive install salt-master salt-minion

RUN salt --version
RUN salt-master --version
RUN salt-minion --version

Crash from salt-mininon, same also directly in SLES12 without Docker:

Traceback (most recent call last):
  File "/usr/bin/salt-minion", line 26, in <module>
    salt_minion()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 106, in salt_min                                           ion
    import salt.cli.daemons
  File "/usr/lib/python2.7/site-packages/salt/cli/daemons.py", line 47, in <modu                                           le>
    from salt.utils import parsers, ip_bracket
  File "/usr/lib/python2.7/site-packages/salt/utils/parsers.py", line 26, in <mo                                           dule>
    import salt.config as config
  File "/usr/lib/python2.7/site-packages/salt/config.py", line 40, in <module>
    import salt.utils.sdb
  File "/usr/lib/python2.7/site-packages/salt/utils/sdb.py", line 9, in <module>
    import salt.loader
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 30, in <module>
    import salt.utils.event
  File "/usr/lib/python2.7/site-packages/salt/utils/event.py", line 81, in <modu                                           le>
    import salt.payload
  File "/usr/lib/python2.7/site-packages/salt/payload.py", line 17, in <module>
    import salt.crypt
  File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 44, in <module>
    import tornado.gen
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 97, in <module>
    from singledispatch import singledispatch  # backport
ImportError: No module named singledispatch

thank you!

**Comment by aboe76** [comment]
@1605200517 the issue is in python-tornado version 4.3
```
features tornado asset (from Docker build log) python-tornado-4.3-1.1.x86_64
```
This has new dependencies on python-singledispatch and python-backports_abc,
that's why you are seeing this error. please install python-singledispatch and python-backports_abc

Fixes are still being processed on opensusebuild service. they need to be processed before entering devel:languages:python repo...

**Comment by 1605200517** [comment]
hi @aboe76 , awesome and very friendly from you being out there! :-) I am not sure how to specify installation of python-backports_abc - i.e. which additional repository is required? http://download.opensuse.org/repositories/openSUSE:Factory/standard/openSUSE:Factory.repo seems no more existing

**Comment by aboe76** [comment]
hi @1605200517 

I can see it has been accepted they are being build now:
https://build.opensuse.org/package/show/devel:languages:python/python-backports_abc
https://build.opensuse.org/package/show/devel:languages:python/python-tornado

**Comment by aboe76** [comment]
is this stil an issue?

**Comment by IAIS4EP** [comment]
for me, all works now - thx. :-)

**Comment by rallytime** [comment]
@racooper Is it alright with you if we close this issue? Looks like it's been resolved.

**Comment by racooper** [comment]
I have removed package locks for python-tornado on about a dozen servers so far, and let it upgrade to 4.3.  Additional packages are being brought in and everything seems to be working now.  Thanks for everyone's help!
