### ISSUE TITLE
dockerng.running does not pull image as documented

### ISSUE THREAD

**Issue by oeuftete** [saltstack/salt#29727]
According to https://docs.saltstack.com/en/latest/ref/states/all/salt.states.dockerng.html#salt.states.dockerng.running, "\[t]his state will pull the image if it is not present".  However, this doesn't seem to be the case:

```text
$ sudo salt-call -l info state.single dockerng.running name=hello image=ubuntu:14.04 cmd="/bin/echo 'Hello world'"
[INFO    ] Loading fresh modules for state activity
[INFO    ] Running state [hello] at time 22:12:37.878405
[INFO    ] Executing state dockerng.running for hello
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1594, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1491, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/states/dockerng.py", line 1411, in running
    image_id = __salt__['dockerng.inspect_image'](image)['Id']
  File "/usr/lib/python2.7/dist-packages/salt/modules/dockerng.py", line 2176, in inspect_image
    ret = _client_wrapper('inspect_image', name)
  File "/usr/lib/python2.7/dist-packages/salt/modules/dockerng.py", line 601, in wrapper
    return wrapped(*args, **salt.utils.clean_kwargs(**kwargs))
  File "/usr/lib/python2.7/dist-packages/salt/modules/dockerng.py", line 867, in _client_wrapper
    exc.explanation)
CommandExecutionError: Error 404: No such image: ubuntu:14.04

[INFO    ] Completed state [hello] at time 22:12:37.884175
local:
----------
          ID: hello
    Function: dockerng.running
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1594, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1491, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/dockerng.py", line 1411, in running
                  image_id = __salt__['dockerng.inspect_image'](image)['Id']
                File "/usr/lib/python2.7/dist-packages/salt/modules/dockerng.py", line 2176, in inspect_image
                  ret = _client_wrapper('inspect_image', name)
                File "/usr/lib/python2.7/dist-packages/salt/modules/dockerng.py", line 601, in wrapper
                  return wrapped(*args, **salt.utils.clean_kwargs(**kwargs))
                File "/usr/lib/python2.7/dist-packages/salt/modules/dockerng.py", line 867, in _client_wrapper
                  exc.explanation)
              CommandExecutionError: Error 404: No such image: ubuntu:14.04
     Started: 22:12:37.878405
    Duration: 5.77 ms
     Changes:   

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   5.770 ms
```

```text
$ sudo salt-call --versions-report
Salt Version:
           Salt: 2015.8.3
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-55-generic
         system: Ubuntu 14.04 trusty
```

(The version of `docker-py` is `1.4.0`.)

**Comment by oeuftete** [comment]
This fixed it for me on the `2015.8` branch.  Should I make a PR?

```diff
diff --git a/salt/states/dockerng.py b/salt/states/dockerng.py
index bad7913..519f324 100644
--- a/salt/states/dockerng.py
+++ b/salt/states/dockerng.py
@@ -1410,7 +1410,11 @@ def running(name,
     except TypeError:
         image = ':'.join(_get_repo_tag(str(image)))
 
+    image_id = None
+    try:
         image_id = __salt__['dockerng.inspect_image'](image)['Id']
+    except:
+        pass
 
     if name not in __salt__['dockerng.list_containers'](all=True):
         pre_config = {}
```

**Comment by oeuftete** [comment]
There are deeper problems.  Inspection of the image with `dockerng.history` for preconfigured volumes or port bindings happens before ensuring the image is present.

**Comment by jfindlay** [comment]
@oeuftete, thanks for reporting.  You are welcome to send in any changes you think need to happen.

**Comment by dkiser** [comment]
+1 ran into same problem

```bash
[root@salt-minion vagrant]# salt-call --versions-report
Salt Version:
           Salt: 2015.8.3

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 0.3.7
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.4.4.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
```

```bash
[root@salt-minion vagrant]# python -c 'import docker; print docker.__version__'
1.6.0
```

**Comment by rhansen** [comment]
:+1:

**Comment by csainty** [comment]
:+1:

**Comment by rallytime** [comment]
@oeuftete Are you in a position to give the fix from @ticosax above a try?

**Comment by oeuftete** [comment]
@rallytime I should be able to test it out mid-next-week after vacation is done.

**Comment by oeuftete** [comment]
The most basic case above works.  However, I'm seeing problems with `ports` configuration using the 2015.8 branch with our current configuration.  Here's a couple of commands which perhaps exercises it?  I wonder if the problem is related to [the comment I made above](https://github.com/saltstack/salt/issues/29727#issuecomment-164924848) when I started to investigate a fix and found that volumes and port bindings complicated things more than I was prepared to deal with.

```text
$ sudo salt-call -l error state.single dockerng.running name=hello image=ubuntu:14.04 cmd="/bin/echo 'Hello world'"
local:
----------
          ID: hello
    Function: dockerng.running
      Result: True
     Comment: Container 'hello' changed state.. Container 'hello' was created.
     Started: 19:50:25.783618
    Duration: 17598.28 ms
     Changes:
              ----------
              added:
                  ----------
                  Id:
                      a523242c9a22ec1b8da82ae7b4434a5e1207c6a826a37b2d770d929632f33a0d
                  Name:
                      hello
                  Time_Elapsed:
                      0.0163879394531
                  Warnings:
                      None
              image:
                  ----------
                  Layers:
                      ----------
                      Pulled:
                          - 0a5fb6c3c94b
                          - 2ec6e7edf8a8
                          - a3ed95caeb02
                          - a64038a0eeaa
                  Status:
                      Downloaded newer image for ubuntu:14.04
                  Time_Elapsed:
                      17.3001439571
              state:
                  ----------
                  new:
                      stopped
                  old:
                      None

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1

$ # Add a ports argument
$ sudo salt-call -l error state.single dockerng.running name=hello image=ubuntu:14.04 cmd="/bin/echo 'Hello world'" ports="[1111]"
[ERROR   ] Uncaught exception "Unable to compare configuration for the 'ports' parameter. This may be due to a change in the Docker API" encountered while comparing existing container against desired configuration. Exception info follows:
  File "/usr/lib/python2.7/dist-packages/salt/states/dockerng.py", line 1593, in running
    defaults_from_image)
  File "/usr/lib/python2.7/dist-packages/salt/states/dockerng.py", line 172, in _compare
    _api_mismatch(item)
  File "/usr/lib/python2.7/dist-packages/salt/states/dockerng.py", line 99, in _api_mismatch
    'be due to a change in the Docker API'.format(param)

[ERROR   ] Uncaught exception "Unable to compare configuration for the 'ports' parameter. This may be due to a change in the Docker API" encountered while comparing existing container against desired configuration. See minion log for exception info.
local:
----------
          ID: hello
    Function: dockerng.running
      Result: False
     Comment: Uncaught exception "Unable to compare configuration for the 'ports' parameter. This may be due to a change in the Docker API" encountered while comparing existing container against desired configuration. See minion log for exception info.
     Started: 19:50:52.748348
    Duration: 15.923 ms
     Changes:

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1

$ sudo salt-call --versions-report
```

```text
Salt Version:
           Salt: 2015.8.4-164-g42027e0

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-55-generic
         system: Ubuntu 14.04 trusty
```

**Comment by rallytime** [comment]
@oeuftete It sounds to me like that may be a separate issue than the one originally filed, and I think we might want to file a new issue.

@ticosax You're in this code a lot. What do you think?

**Comment by ticosax** [comment]
@rallytime Yes, I'm fighting a bit in this area :smile: 

I will continue to work on it.

@oeuftete which version of dockerd are you using ?

**Comment by oeuftete** [comment]
@ticosax:

```text
$ docker --version
Docker version 1.10.2, build c3959b1
```

Saw the latest issue with `docker-py` 1.5.0 and 1.6.0.

**Comment by ticosax** [comment]
@oeuftete 
Thanks, I noticed the same thing, latest docker returns configuration items optionally.

please can you check #31455 ?
