### ISSUE TITLE
Pillar sqlite3 examples incorrect

### ISSUE THREAD

**Issue by akissa** [saltstack/salt#29736]
The default examples provided in the pillar sqlite3 module are incorrect and generate
a syntax error when used. This is because sqlite3 uses qmark paramstyle but the
examples use format paramstyle.

```
>>> import sqlite3
>>> sqlite3.paramstyle
'qmark'
```

Test example data
```
CREATE TABLE quickpeek
    (
    id INT PRIMARY KEY,
    internal TEXT,
    hostname TEXT,
    value TEXT
    );
INSERT INTO "quickpeek" VALUES(NULL,'infoheader','standalone.baruwa.com','X-Asante-BaruwaFW-Info:');
```
SLS
```
pillar:
  sqlite3:
    database: '/var/lib/salt/pillar.db'
    timeout: 5.0
ext_pillar:
  - sqlite3:
      fromdb:
        # both queries below will fail with syntax error
        query: "SELECT internal, value FROM quickpeek WHERE hostname LIKE %s"
        #query: "SELECT internal, value FROM quickpeek WHERE hostname=%s"
```

Exceptions generated
```
[ERROR   ] Error in ext_pillar SQLite3: ('near "%": syntax error',)
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/pillar/sqlite3.py", line 102, in _get_cursor
    yield cursor
  File "/usr/lib/python2.6/site-packages/salt/pillar/sql_base.py", line 437, in fetch
    cursor.execute(details['query'], (minion_id,))
OperationalError: near "%": syntax error
```

The correct rewrite for the above queries
```
SELECT internal, value FROM quickpeek WHERE hostname LIKE ?
SELECT internal, value FROM quickpeek WHERE hostname=?
```

**Comment by jfindlay** [comment]
@akissa, thanks for working on this.
