### ISSUE TITLE
salt-call does not work on AIX 2015.8.3 package

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#29776]
Aix OS versions: both 6 and 7
Salt Version: 2015.8.3

Running a salt-call command of any kind returns a stack trace error:

```

l273pp010_pub[/] > salt-call test.version
Traceback (most recent call last):
  File "/opt/salt/bin/salt-call", line 11, in <module>
    salt_call()
  File "/opt/salt/lib/python2.7/site-packages/salt/scripts.py", line 325, in salt_call
    import salt.cli.call
  File "/opt/salt/lib/python2.7/site-packages/salt/cli/call.py", line 9, in <module>
    import salt.cli.caller
  File "/opt/salt/lib/python2.7/site-packages/salt/cli/caller.py", line 36, in <module>
    from raet import raeting, nacling
  File "/opt/salt/lib/python2.7/site-packages/raet-0.6.5-py2.7.egg/raet/__init__.py", line 12, in <module>
    importlib.import_module(".{0}".format(m), package='raet')
  File "/opt/salt/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/salt/lib/python2.7/site-packages/raet-0.6.5-py2.7.egg/raet/nacling.py", line 11, in <module>
    import libnacl
  File "/opt/salt/lib/python2.7/site-packages/libnacl/__init__.py", line 89, in <module>
    nacl = _get_nacl()
  File "/opt/salt/lib/python2.7/site-packages/libnacl/__init__.py", line 87, in _get_nacl
    raise OSError(msg)
OSError: Could not locate nacl lib, searched for libsodium.so, libsodium.so.13, libsodium.so.10, libsodium.so.5, libsodium.so.4,  and tweetnacl.so
```

This was working previously on 2015.5.1

**Comment by rickh563** [comment]
ZD-553

**Comment by dmurphy18** [comment]
libsodium is not .so but .a, also libsodium.so.13 is in .libs.  Need to move and make symbolic link and check for other .a issues noting that there is really no such thing as a static library on AIX, they are all really dynamic, .a and .so

**Comment by dmurphy18** [comment]
Fix will be available in the next release of salt for AIX

**Comment by Ch3LL** [comment]
I've tested and confirmed that this is now working in 2015.8.5. Closing now.

**Comment by zhangkaka** [comment]
$ salt-ssh --versions
Traceback (most recent call last):
  File "/usr/local/bin/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/usr/local/lib/python2.7/dist-packages/salt/scripts.py", line 381, in salt_ssh
    client.run()
  File "/usr/local/lib/python2.7/dist-packages/salt/cli/ssh.py", line 16, in run
    self.parse_args()
  File "/usr/local/lib/python2.7/dist-packages/salt/utils/parsers.py", line 147, in parse_args
    self.print_versions_report()
  File "/usr/local/lib/python2.7/dist-packages/salt/utils/parsers.py", line 214, in print_versions_report
    print('\n'.join(version.versions_report()), file=file)
  File "/usr/local/lib/python2.7/dist-packages/salt/version.py", line 639, in versions_report
    ver_info = versions_information(include_salt_cloud)
  File "/usr/local/lib/python2.7/dist-packages/salt/version.py", line 627, in versions_information
    lib_info = list(dependency_information(include_salt_cloud))
  File "/usr/local/lib/python2.7/dist-packages/salt/version.py", line 577, in dependency_information
    imp = __import__(imp)
  File "/usr/local/lib/python2.7/dist-packages/libnacl/__init__.py", line 76, in <module>
    nacl = _get_nacl()
  File "/usr/local/lib/python2.7/dist-packages/libnacl/__init__.py", line 74, in _get_nacl
    raise OSError(msg)
OSError: Could not locate nacl lib, searched for libsodium.so, libsodium.so.18, libsodium.so.17, libsodium.so.13, libsodium.so.10, libsodium.so.5, libsodium.so.4,

**Comment by zhangkaka** [comment]
ubuntu 16,salt-ssh 2015.8.8.2

**Comment by dmurphy18** [comment]
@zhangkaka The topic of this issue is AIX and it is closed.  Please open another issue to discuss your issue.  

Note, Salt only supported Ubuntu 16.04 with release 2016.3.0, please try with that version.
The Ubuntu 16.04 ISO has a Debian Community build of Salt v2015.8.8.
