### ISSUE TITLE
Problem in higstate output if salt state has salt.function call

### ISSUE THREAD

**Issue by acgupt** [saltstack/salt#29840]
For configuration like  Master A -> Syndic Master -> Master -> Minions and executing highstate state on Master A and calling saltutil.refresh_pillar in state recursively on subsequent nodes , then highstate output throw following exception:

``` python-traceback
2015-12-18 07:20:39,741 [salt.output      ][DEBUG   ][10608][140154598037248] Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/output/__init__.py", line 46, in try_printout
    return get_printout(out, opts)(data).rstrip()
  File "/usr/lib/python2.6/site-packages/salt/output/highstate.py", line 84, in output
    return _format_host(host, hostdata)[0]
  File "/usr/lib/python2.6/site-packages/salt/output/highstate.py", line 132, in _format_host
    schanged, ctext = _format_changes(ret['changes'])
  File "/usr/lib/python2.6/site-packages/salt/output/highstate.py", line 381, in _format_changes
    s, c = _format_host(host, hostdata)
  File "/usr/lib/python2.6/site-packages/salt/output/highstate.py", line 132, in _format_host
    schanged, ctext = _format_changes(ret['changes'])
  File "/usr/lib/python2.6/site-packages/salt/output/highstate.py", line 381, in _format_changes
    s, c = _format_host(host, hostdata)
  File "/usr/lib/python2.6/site-packages/salt/output/highstate.py", line 132, in _format_host
    schanged, ctext = _format_changes(ret['changes'])
  File "/usr/lib/python2.6/site-packages/salt/output/highstate.py", line 381, in _format_changes
    s, c = _format_host(host, hostdata)
  File "/usr/lib/python2.6/site-packages/salt/output/highstate.py", line 125, in _format_host
    key=lambda k: data[k].get('__run_num__', 0)):
  File "/usr/lib/python2.6/site-packages/salt/output/highstate.py", line 125, in <lambda>
    key=lambda k: data[k].get('__run_num__', 0)):
AttributeError: 'list' object has no attribute 'get'
```

**Comment by jfindlay** [comment]
@acgupt, thanks for the report.  What version of salt are you using?  Can you post the state using the `salt.function` that seems to be causing the stack trace?

**Comment by vutny** [comment]
Looks related to #29796.

**Comment by acgupt** [comment]
Yes, I was busy with other stuff , it looks to be highstate outputter parser issue or related.
salt --versions-report 
           Salt: 2015.5.10
         Python: 2.6.6 (r266:84292, Jul 23 2015, 05:13:40)
         Jinja2: unknown
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.5.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: Not Installed

test_refresh_pillar:
  salt.function:
    - name: saltutil.refresh_pillar
    - tgt: '*'
    - reload_modules: True
