### ISSUE TITLE
boto_elb.present : cnames parameter has problem with identifier attribute / missing DNS split ?

### ISSUE THREAD

**Issue by Reiner030** [saltstack/salt#29976]
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.boto_elb.html#salt.states.boto_elb.present

```
cnames
A list of cname dicts with attributes: name, zone, ttl, and identifier.
See the boto_route53 state for information about these attributes.
```

Only if I setup a state with identifier set I got this error

```
2015-12-23 13:26:23,899 [salt.state       ][INFO    ][18709] Executing state boto_elb.present for static-staging
2015-12-23 13:27:16,170 [salt.state       ][ERROR   ][18709] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1594, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1491, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/states/boto_elb.py", line 349, in present
    wait_for_sync=wait_for_sync
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1491, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/states/boto_route53.py", line 172, in present
    split_dns, private_zone)
  File "/usr/lib/python2.7/dist-packages/salt/modules/boto_route53.py", line 295, in add_record
    status = _zone.add_cname(name, _value, ttl, identifier)
  File "/usr/local/lib/python2.7/dist-packages/boto/route53/zone.py", line 171, in add_cname
    comment=comment)
  File "/usr/local/lib/python2.7/dist-packages/boto/route53/zone.py", line 120, in add_record
    return Status(self.route53connection, self._commit(changes))
  File "/usr/local/lib/python2.7/dist-packages/boto/route53/zone.py", line 59, in _commit
    response = changes.commit()
  File "/usr/local/lib/python2.7/dist-packages/boto/route53/record.py", line 168, in commit
    return self.connection.change_rrsets(self.hosted_zone_id, self.to_xml())
  File "/usr/local/lib/python2.7/dist-packages/boto/route53/connection.py", line 469, in change_rrsets
    xml_body)
  File "/usr/local/lib/python2.7/dist-packages/boto/route53/connection.py", line 103, in make_request
    retry_handler=self._retry_handler)
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1028, in _mexe
    raise BotoServerError(response.status, response.reason, body)
BotoServerError: BotoServerError: 503 Service Unavailable
<?xml version="1.0"?>
<ErrorResponse xmlns="https://route53.amazonaws.com/doc/2013-04-01/"><Error><Type>Receiver</Type><Code>ServiceUnavailable</Code><Message>The service is currently unavailable.</Message></Error><RequestId>d0ac7223-a978-11e5-8c7b-5d44e191f173</RequestId></ErrorResponse>
```

I got no errors but I think support for split_dns is also passed to route53 functions?

**Comment by Reiner030** [comment]
Additional there is a problem with other ELB cnames after 1st run - Saltstack tries to add them again and again.
I guess their name is too long so that compare check miss it?:

````
2015-12-23 14:55:08,240 [salt.state       ][INFO    ][24959] Executing state boto_elb.present for DE-yves-staging
2015-12-23 14:55:09,684 [salt.state       ][ERROR   ][24959] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1594, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1491, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/states/boto_elb.py", line 349, in present
    wait_for_sync=wait_for_sync
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1491, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/states/boto_route53.py", line 172, in present
    split_dns, private_zone)
  File "/usr/lib/python2.7/dist-packages/salt/modules/boto_route53.py", line 295, in add_record
    status = _zone.add_cname(name, _value, ttl, identifier)
  File "/usr/local/lib/python2.7/dist-packages/boto/route53/zone.py", line 171, in add_cname
    comment=comment)
  File "/usr/local/lib/python2.7/dist-packages/boto/route53/zone.py", line 120, in add_record
    return Status(self.route53connection, self._commit(changes))
  File "/usr/local/lib/python2.7/dist-packages/boto/route53/zone.py", line 59, in _commit
    response = changes.commit()
  File "/usr/local/lib/python2.7/dist-packages/boto/route53/record.py", line 168, in commit
    return self.connection.change_rrsets(self.hosted_zone_id, self.to_xml())
  File "/usr/local/lib/python2.7/dist-packages/boto/route53/connection.py", line 475, in change_rrsets
    body)
DNSServerError: DNSServerError: 400 Bad Request
<?xml version="1.0"?>
<ErrorResponse xmlns="https://route53.amazonaws.com/doc/2013-04-01/"><Error><Type>Sender</Type><Code>InvalidChangeBatch</Code><Message>Tried to create resource record set [name='de-yves-staging-euc1.example.com.', type='CNAME'] but it already
 exists</Message></Error><RequestId>29615fc7-a985-11e5-b983-4bf3096caf2c</RequestId></ErrorResponse>

2015-12-23 14:55:09,684 [salt.state       ][INFO    ][24959] Completed state [DE-yves-staging] at time 14:55:09.683960
````

(Btw. is there somewhere a howto/tutorial howto debug such problems deeper?)

**Comment by Reiner030** [comment]
sorry forgot version info for this bug:
````
root@salt:~# salt-call --version
salt-call 2015.8.3 (Beryllium)
root@salt:~# pip install | grep boto
root@salt:~# pip list | grep boto
boto (2.38.0)
botocore (1.3.9)
````

**Comment by cachedout** [comment]
@Reiner030 Interesting. This really almost looks like a bug in the upstream boto module, but I genuinely don't know enough about boto to really say. 

@ryan-lane or @mgwilliams Do either of you have any insight here?

**Comment by DanyC97** [comment]
@Reiner030 can you post your full state ?

Since i was going through same debug process few days ago, following my chat with @ryan-lane i believe the best bet is to set your python repl or the IDE on the minion as a salt client and import all the boto modules from which you run debugger to figure out where is going wrong.
I don't have a full howto, once i have one will share it

**Comment by Reiner030** [comment]
e.g. from ELB definition:

````
    - cnames:
        - name: static-production-euc1.example.com.
          zone: example.com.
          #ttl: 300
          #identifier: static-production-eu-central-1
          split_dns: True
          private_zone: False
````
(commenting out ````split_dns```` / ````private_zone````  makes no difference but ````identifier````)
