### ISSUE TITLE
salt Caller throws 'string indices must be integers, not str'

### ISSUE THREAD

**Issue by sjmh** [saltstack/salt#30066]
I have a trigger written in Cobbler that is trying to use the salt python API to throw an event back to the master.

Both the master and minion running on the Cobbler server are on 2015.8.3.

The trigger function is rather simple:

```
import salt.client
import salt.config

def run(api, args, logger):
    (objtype, name, ip) = args
    if objtype != 'system':
        # something bad happened here, so get out
        return 0

    system = api.find_system(name)
    if not system:
        # something worse - we couldn't find the system
        # that just called us, so bail
        return 0

    opts = salt.config.minion_config('/etc/salt/minion')
    caller = salt.client.Caller(mopts=opts)
    rid = system.ks_meta['rid']
    if logger:
        logger.info('Updating quickbase for record {0}'.format(rid))
    caller.cmd('event.send', 'hes/prov/v1/pxe_done/{0}'.format(rid))
    return 0
```

However, it often ends up throwing this:

```
Tue Dec 29 13:22:14 2015 - DEBUG | running python trigger cobbler.modules.install_pre_pxedone
Tue Dec 29 13:22:14 2015 - INFO | Exception occured: <type 'exceptions.TypeError'>
Tue Dec 29 13:22:14 2015 - INFO | Exception value: string indices must be integers, not str
Tue Dec 29 13:22:14 2015 - INFO | Exception Info:
  File "/usr/lib/python2.6/site-packages/cobbler/remote.py", line 2080, in _dispatch
    return method_handle(*params)
   File "/usr/lib/python2.6/site-packages/cobbler/remote.py", line 1397, in run_install_triggers
    utils.run_triggers(self.api, None, "/var/lib/cobbler/triggers/install/%s/*" % mode, additional=[objtype,name,ip],logger=self.logger)
   File "/usr/lib/python2.6/site-packages/cobbler/utils.py", line 944, in run_triggers
    rc = m.run(api, arglist, logger)
   File "/usr/lib/python2.6/site-packages/cobbler/modules/install_pre_pxedone.py", line 33, in run
    caller = salt.client.Caller(mopts=opts)
   File "/usr/lib/python2.6/site-packages/salt/client/__init__.py", line 1571, in __init__
    self.sminion = salt.minion.SMinion(self.opts)
   File "/usr/lib/python2.6/site-packages/salt/minion.py", line 518, in __init__
    self.gen_modules(initial_load=True)
   File "/usr/lib/python2.6/site-packages/salt/minion.py", line 529, in gen_modules
    pillarenv=self.opts.get('pillarenv'),
   File "/usr/lib/python2.6/site-packages/salt/pillar/__init__.py", line 163, in compile_pillar
    dictkey='pillar',
   File "/usr/lib/python2.6/site-packages/salt/utils/async.py", line 73, in wrap
    ret = self._block_future(ret)
   File "/usr/lib/python2.6/site-packages/salt/utils/async.py", line 83, in _block_future
    return future.result()
   File "/usr/lib64/python2.6/site-packages/tornado/concurrent.py", line 214, in result
    raise_exc_info(self._exc_info)
   File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 879, in run
    yielded = self.gen.send(value)
   File "/usr/lib/python2.6/site-packages/salt/transport/zeromq.py", line 160, in crypted_transfer_decode_dictentry
    aes = cipher.decrypt(ret['key'])
```

Now, it doesn't do this all the time, but it does it pretty often.  I can send the events manually with no issue via salt-call.  The cobbler daemon is running as root, although the apache daemon that runs the web portion of it isn't.  I've added a few debug statements though and the effective user is root in context of the function.

Was going to start digging into the stacktrace, but figured I'd post this in the meantime if someone had seen this before and had a suggestion.

**Comment by cachedout** [comment]
Interesting. I have never seen this. Have you, @jacksontj ?

**Comment by wt** [comment]
@sjmh Can you please post the output of "salt-call --versions" from the minion and "salt --versions" from the master?

Also, I have seen an issue where the python-msgpack package was not upgraded properly on Amazon Linux, which is similar to RHEL6 in some ways. If you are running a yum distro, can you try looking at what packages would be upgraded by a yum upgrade and see if anything looks interesting?

**Comment by sjmh** [comment]
@wt -

```[root@itmlabprovdev01 ~]# salt-call --versions
Salt Version:
           Salt: 2015.8.3

Dependency Versions:
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.5.0
         Python: 2.6.6 (r266:84292, May 22 2015, 08:34:51)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3c1
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: redhat 6.5 Santiago
        machine: x86_64
        release: 2.6.32-431.el6.x86_64
         system: Red Hat Enterprise Linux Server 6.5 Santiago
```

```
Salt Version:
           Salt: 2015.8.3

Dependency Versions:
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
         Python: 2.6.6 (r266:84292, Nov 21 2013, 10:50:32)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: redhat 6.5 Santiago
        machine: x86_64
        release: 2.6.32-431.el6.x86_64
         system: Red Hat Enterprise Linux Server 6.5 Santiago
```

As far as updates - these are RHEL6.5 - so they have quite a few packages that would be updated ( as our local yum repos have everything up to RHEL 6.7 ).

**Comment by wt** [comment]
Is python-msgpack one of the things that would be updated? I found that the salt packages didn't use a versioned dependency. This would cause machines that had an old version of the python-msgpack package to not get the new version. That in turn would cause an exception that looks similar to what you reported?

You might trying updating only python-msgpack, if that is even possible. See if that fixes this issue.

I don't know if salt has started using a versioned dep since I saw this problem. I am still using the EPEL packages and planning a move to the saltstack managed repo.

**Comment by sjmh** [comment]
@wt - msgpack isn't something that has an update available.

**Comment by wt** [comment]
Oh well, ignore me then. :)

**Comment by cachedout** [comment]
Are you running this with a local minion process running alongside or are you setting the `local` flag in the Salt options that you're passing in? I'm a little curious if you see anything in the local minion logs (if relevant) or on the associated master.

**Comment by sjmh** [comment]
@cachedout There's a local minion process running on the server.  I set the minion logs to 'trace' but I don't see any correlating events in the log file for when this occurs.

However, on the master, I do get this:

```
2016-01-05 13:48:51,154 [salt.crypt                                          ][DEBUG   ][1292] Failed to authenticate message
2016-01-05 13:48:51,155 [salt.transport.zeromq                               ][ERROR   ][1292] Bad load from minion
2```

This also seems to happen after I restart the master.  It was working all day yesterday, but once I reset the master, it's now throwing up this error each time.

**Comment by allanliu** [comment]
I'm seeing this as well
```
Traceback (most recent call last):
  File "./cli.py", line 533, in <module>
    SUCCESS, MSG = main()
  File "./cli.py", line 498, in main
    success, msg = create_environment(cli_args)
  File "./cli.py", line 459, in create_environment
    async=cli_args['async']
  File "/opt/provisioning/provision/environment.py", line 163, in provision_via_cloudformation
    self.mesos_masters[0]['private_ip_address']
  File "/opt/provisioning/provision/environment.py", line 371, in deploy_mesos_tasks
    caller = salt.client.Caller()
  File "/root/src/salt/salt/client/__init__.py", line 1571, in __init__
    self.sminion = salt.minion.SMinion(self.opts)
  File "/root/src/salt/salt/minion.py", line 518, in __init__
    self.gen_modules(initial_load=True)
  File "/root/src/salt/salt/minion.py", line 529, in gen_modules
    pillarenv=self.opts.get('pillarenv'),
  File "/root/src/salt/salt/pillar/__init__.py", line 163, in compile_pillar
    dictkey='pillar',
  File "/root/src/salt/salt/utils/async.py", line 73, in wrap
    ret = self._block_future(ret)
  File "/root/src/salt/salt/utils/async.py", line 83, in _block_future
    return future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1017, in run
    yielded = self.gen.send(value)
  File "/root/src/salt/salt/transport/zeromq.py", line 160, in crypted_transfer_decode_dictentry
    aes = cipher.decrypt(ret['key'])
TypeError: string indices must be integers, not str```
I'm running A/B deploys by rolling out an entire stack of AWS instances then using salt to manage states.  However there are a few state.sls that I use the salt-client for on the salt-minion that runs the deploy.
Every was fine until I migrated from this
```
  def deploy_microservices(self, marathon_ip):
        """Deploys microservices to marathon over salt"""
        data = {
            'env': self.env,
            'marathon_address': marathon_ip
        }
        caller = salt.client.Caller()
        resp = caller.sminion.functions['state.sls'](
            'role.deploy',
            pillar=data
        )
        success, msg = check_saltstate_return(resp)
        if success:
            resp2 = caller.sminion.functions['state.sls'](
                'reactor.deploy_marathon_services',
                pillar=data
            )
            return check_saltstate_return(resp2)
        else:
            return False, msg
```
to this:
```
def deploy_mesos_tasks(self, framework, target_ip):
        """Deploys to Meso's framework via salt"""
        salt_state = get_salt_deploy_state(framework)
        data = {
            'env': self.env,
            '{0}_address'.format(framework): target_ip
        }
        caller = salt.client.Caller()
        resp = caller.sminion.functions['state.sls'](
            'role.deploy',
            pillar=data
        )
        success, msg = check_saltstate_return(resp)
        if success:
            resp2 = caller.sminion.functions['state.sls'](
                salt_state,
                pillar=data
            )
            return check_saltstate_return(resp2)
        else:
            return False, msg
```
Still debugging...

**Comment by damon-atkins** [comment]
I am seeing this as well.
salt-call state.highstate
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: string indices must be integers, not str
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 335, in salt_call
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 43, in run
    caller = salt.cli.caller.Caller.factory(self.config)
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 78, in factory
    return ZeroMQCaller(opts, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 269, in __init__
    super(ZeroMQCaller, self).__init__(opts)
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 101, in __init__
    self.minion = salt.minion.SMinion(opts)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 523, in __init__
    self.gen_modules(initial_load=True)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 534, in gen_modules
    pillarenv=self.opts.get('pillarenv'),
  File "/usr/lib/python2.7/site-packages/salt/pillar/__init__.py", line 163, in compile_pillar
    dictkey='pillar',
  File "/usr/lib/python2.7/site-packages/salt/utils/async.py", line 73, in wrap
    ret = self._block_future(ret)
  File "/usr/lib/python2.7/site-packages/salt/utils/async.py", line 83, in _block_future
    return future.result()
  File "/usr/lib/python2.7/site-packages/tornado/concurrent.py", line 214, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/site-packages/tornado/gen.py", line 879, in run
    yielded = self.gen.send(value)
  File "/usr/lib/python2.7/site-packages/salt/transport/zeromq.py", line 160, in crypted_transfer_decode_dictentry
    aes = cipher.decrypt(ret['key'])
TypeError: string indices must be integers, not str
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 335, in salt_call
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 43, in run
    caller = salt.cli.caller.Caller.factory(self.config)
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 78, in factory
    return ZeroMQCaller(opts, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 269, in __init__
    super(ZeroMQCaller, self).__init__(opts)
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 101, in __init__
    self.minion = salt.minion.SMinion(opts)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 523, in __init__
    self.gen_modules(initial_load=True)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 534, in gen_modules
    pillarenv=self.opts.get('pillarenv'),
  File "/usr/lib/python2.7/site-packages/salt/pillar/__init__.py", line 163, in compile_pillar
    dictkey='pillar',
  File "/usr/lib/python2.7/site-packages/salt/utils/async.py", line 73, in wrap
    ret = self._block_future(ret)
  File "/usr/lib/python2.7/site-packages/salt/utils/async.py", line 83, in _block_future
    return future.result()
  File "/usr/lib/python2.7/site-packages/tornado/concurrent.py", line 214, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/site-packages/tornado/gen.py", line 879, in run
    yielded = self.gen.send(value)
  File "/usr/lib/python2.7/site-packages/salt/transport/zeromq.py", line 160, in crypted_transfer_decode_dictentry
    aes = cipher.decrypt(ret['key'])
TypeError: string indices must be integers, not str

then run it again it will work, run it again it will not, etc  salt-call seems to be more reliable than salt 'master' state.highstate

when doing salt master state.highstate also getting
Try 1
Minion did not return. [No response]

Try 2
master:
    Passed invalid arguments to state.highstate: string indices must be integers, not str
... followed by the help doco on state.highstate   ......

Try 3
[DEBUG   ] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'master_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] LazyLoaded nested.output
[TRACE   ] data = Failed to authenticate! This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).
Failed to authenticate! This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).

Its about a 5% chance it will work with salt master state.highstate

**Comment by jinlongwang** [comment]
I am seeing this as well. but i didn't use pillar at all

```
2016-10-25 10:57:25,460 [salt.pillar                                               ][ERROR   ][13287] Exception getting pillar:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/pillar/__init__.py", line 114, in compile_pillar
    dictkey='pillar',
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib64/python2.6/site-packages/tornado/concurrent.py", line 214, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 879, in run
    yielded = self.gen.send(value)
  File "/usr/lib/python2.6/site-packages/salt/transport/zeromq.py", line 160, in crypted_transfer_decode_dictentry
    aes = cipher.decrypt(ret['key'])
TypeError: string indices must be integers, not str
2016-10-25 10:57:25,461 [salt.pillar                                               ][ERROR   ][13287] Exception getting pillar:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/pillar/__init__.py", line 114, in compile_pillar
    dictkey='pillar',
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib64/python2.6/site-packages/tornado/concurrent.py", line 214, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 879, in run
    yielded = self.gen.send(value)
  File "/usr/lib/python2.6/site-packages/salt/transport/zeromq.py", line 160, in crypted_transfer_decode_dictentry
    aes = cipher.decrypt(ret['key'])
TypeError: string indices must be integers, not str
```

```
[root@saltmaster1 ~]# salt --versions-report
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.5.0
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3c1
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 4.0.1
         system: Linux
        version: CentOS 6.7 Final
```

**Comment by grobinson-blockchain** [comment]
We have a similar issue whereby we see the following exception:

    [ERROR   ] An un-handled exception was caught by salt's global exception handler:
    KeyError: 'key'
    Traceback (most recent call last):
      File "/usr/bin/salt-call", line 11, in <module>
        salt_call()
      File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 379, in salt_call
        client.run()
      File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 58, in run
        caller.run()
      File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 134, in run
        ret = self.call()
      File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 197, in call
        ret['return'] = func(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 544, in apply_
        return highstate(**kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 797, in highstate
        mocked=kwargs.get('mock', False))
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 3534, in __init__
        loader=loader)
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 662, in __init__
        self.opts['pillar'] = self._gather_pillar()
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 704, in _gather_pillar
        ret = pillar.compile_pillar()
      File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 156, in compile_pillar
        dictkey='pillar',
      File "/usr/lib/python2.7/dist-packages/salt/utils/async.py", line 75, in wrap
        ret = self._block_future(ret)
      File "/usr/lib/python2.7/dist-packages/salt/utils/async.py", line 85, in _block_future
        return future.result()
      File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 1024, in run
        yielded = self.gen.send(value)
      File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 200, in crypted_transfer_decode_dictentry
        aes = cipher.decrypt(ret['key'])
    KeyError: 'key'
    Traceback (most recent call last):
      File "/usr/bin/salt-call", line 11, in <module>
        salt_call()
      File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 379, in salt_call
        client.run()
      File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 58, in run
        caller.run()
      File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 134, in run
        ret = self.call()
      File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 197, in call
        ret['return'] = func(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 544, in apply_
        return highstate(**kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 797, in highstate
        mocked=kwargs.get('mock', False))
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 3534, in __init__
        loader=loader)
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 662, in __init__
        self.opts['pillar'] = self._gather_pillar()
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 704, in _gather_pillar
        ret = pillar.compile_pillar()
      File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 156, in compile_pillar
        dictkey='pillar',
      File "/usr/lib/python2.7/dist-packages/salt/utils/async.py", line 75, in wrap
        ret = self._block_future(ret)
      File "/usr/lib/python2.7/dist-packages/salt/utils/async.py", line 85, in _block_future
        return future.result()
      File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 1024, in run
        yielded = self.gen.send(value)
      File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 200, in crypted_transfer_decode_dictentry
        aes = cipher.decrypt(ret['key'])
    KeyError: 'key'

**Comment by fandrews** [comment]
I'm seeing a similar issue that is somewhat intermittent but when it does occur it is an operation of `archive.extracted`:

```2018-01-24 23:25:00,343 [salt.state       ][ERROR   ][11611] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1745, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1702, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/states/archive.py", line 890, in extracted
    concurrent=concurrent)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 1455, in single
    st_ = salt.state.State(opts, pillar, pillar_enc=pillar_enc, proxy=__proxy__)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 662, in __init__
    self.opts['pillar'] = self._gather_pillar()
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 704, in _gather_pillar
    ret = pillar.compile_pillar()
  File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 156, in compile_pillar
    dictkey='pillar',
  File "/usr/lib/python2.7/dist-packages/salt/utils/async.py", line 75, in wrap
    ret = self._block_future(ret)
  File "/usr/lib/python2.7/dist-packages/salt/utils/async.py", line 85, in _block_future
    return future.result()
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 879, in run
    yielded = self.gen.send(value)
  File "/usr/lib/python2.7/dist-packages/salt/transport/tcp.py", line 293, in crypted_transfer_decode_dictentry
    aes = cipher.decrypt(ret['key'])
TypeError: string indices must be integers, not str```

**Comment by DaveQB** [comment]
I am getting this too. It only happens on a state.apply/state.highstate. If I run state.sls or cmd.run etc, we have no issue.

Error I am setting is a help page:

`
Passed invalid arguments: list indices must be integers, not str.

Usage: 

    .. versionadded:: 2015.5.0

    This function will call :mod:`state.highstate
    <salt.modules.state.highstate>` or :mod:`state.sls
    <salt.modules.state.sls>` based on the arguments passed to this function.
    It exists as a more intuitive way of applying states.

    .. rubric:: APPLYING ALL STATES CONFIGURED IN TOP.SLS (A.K.A. :ref:`HIGHSTATE <running-highstate>`)

    To apply all configured states, simply run ``state.apply``:

    .. code-block:: bash

        salt '*' state.apply

    The following additional arguments are also accepted when applying all
    states configured in top.sls:
`

Minion that is working fine:

`
Salt Version:
           Salt: 2016.3.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-116-generic
         system: Linux
        version: Ubuntu 16.04 xenial

`

A minion that has this error:

`
Salt Version:
           Salt: 2016.3.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-116-generic
         system: Linux
        version: Ubuntu 16.04 xenial
`

They look identical to me.

**Comment by DaveQB** [comment]
Ok I found my issue. It was a typo in an .sls file. It wasn't obvious and I had to go back commit by commit until the error ceased and then dig into that troublesome commit.
