### ISSUE TITLE
boto_elb fails in setup of access_log to S3

### ISSUE THREAD

**Issue by rterbush** [saltstack/salt#30073]
Salt version 2015.8.3 (with monkey patch to boto_elb to fix vpc_id/vpc_name issue provided by @ryan-lane )

Applying boto_elb.present state, the state returns as failed, although it did successfully create the elb. The error is as follows:

```
master-minion.uswest2a.staging.lhn:
  Name: secg-us-west-2-staging-elb - Function: boto_secgroup.present - Result: Clean
----------
          ID: ensure_ELB_exists
    Function: boto_elb.present
        Name: elb-us-west-2-staging-lhn
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.6/dist-packages/salt/state.py", line 1594, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.6/dist-packages/salt/loader.py", line 1491, in wrapper
                  return f(*args, **kwargs)
                File "/var/cache/salt/minion/extmods/states/boto_elb.py", line 316, in present
                  _ret = _attributes_present(name, attributes, region, key, keyid, profile)
                File "/var/cache/salt/minion/extmods/states/boto_elb.py", line 696, in _attributes_present
                  profile)
                File "/usr/lib/python2.6/dist-packages/salt/modules/boto_elb.py", line 481, in set_attributes
                  added_attr = conn.modify_lb_attribute(name, 'accessLog', _al)
                File "/usr/lib/python2.6/dist-packages/boto/ec2/elb/__init__.py", line 446, in modify_lb_attribute
                  verb='GET')
                File "/usr/lib/python2.6/dist-packages/boto/connection.py", line 1227, in get_status
                  raise self.ResponseError(response.status, response.reason, body)
              BotoServerError: BotoServerError: 409 Conflict
              <ErrorResponse xmlns="http://elasticloadbalancing.amazonaws.com/doc/2012-06-01/">
                <Error>
                  <Type>Sender</Type>
                  <Code>InvalidConfigurationRequest</Code>
                  <Message>Access Denied for bucket: lhn-admin. Please check S3bucket permission</Message>
                </Error>
                <RequestId>1b3ced56-ae81-11e5-8000-c9c5b348f5ca</RequestId>
              </ErrorResponse>
     Started: 23:08:42.977933
    Duration: 1128.672 ms
     Changes:
```

The elb is created without configuration for logging to S3 bucket. Access control to the bucket has been completely removed for this user.

The state is as follows:
```
ensure_ELB_exists:
  boto_elb.present:
    - name: elb-{{ grains['ec2']['region'] -}}-{{- pillar['aws-environment'] -}}-lhn
    - region: {{ pillar['aws-region'] }}
    - scheme: internet-facing
    - require:
      - boto_secgroup: secgroup_for_elb
    - subnets: {{ pillar['aws-elb']['subnets'] }}
    - security_groups: {{ pillar['aws-elb']['security-groups'] }}
    - listeners:
      - elb_port: 443
        instance_port: 80
        elb_protocol: HTTPS
        instance_protocol: HTTP
        certificate: {{ pillar['aws-elb']['certificate'] }}
      - elb_port: 80
        instance_port: 80
        elb_protocol: HTTP
        instance_protocol: HTTP
    - health_check:
        target: 'TCP:80'
        timeout: 5
        interval: 30
        healthy_threshold: 2
        unhealthy_threshold: 10
    - attributes:
        cross_zone_load_balancing:
          enabled: False
        connection_draining:
          enabled: True
        timeout: 20
        access_log:
          enabled: True
          s3_bucket_name: {{ pillar['aws-elb']['log-bucket'] }}
          s3_bucket_prefix: {{ pillar['aws-elb']['log-bucket-prefix'] }}
          emit_interval: 5
    - cnames:
        {% for name in pillar['aws-elb']['cnames'] %}
        - name: {{ name -}}.{{- pillar['aws-elb']['domain'] }}
        - zone: {{ pillar['aws-elb']['domain'] }}
        - ttl: 60
        {% endfor %}
```

**Comment by rterbush** [comment]
This is an issue with access needing to be given to the elb service and not the minion creating the elb.
