### ISSUE TITLE
salt-run: traceback on nonexistent job cache file

### ISSUE THREAD

**Issue by jfindlay** [saltstack/salt#30205]
```python-traceback
centos-7-main salt 2015.8 # salt-run manage.status
down:
    - centos-7-main
    - ubuntu-14
up:
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
OSError: [Errno 2] No such file or directory: '/var/cache/salt/master/jobs/18/9c31e51d0fc4fb826f2a4d114b9574/centos-7-main_master/return.p'
Traceback (most recent call last):
  File "/usr/bin/salt-run", line 8, in <module>
    execfile(__file__)
  File "/root/salt/scripts/salt-run", line 10, in <module>
    salt_run()
  File "/root/salt/salt/scripts.py", line 358, in salt_run
    client.run()
  File "/root/salt/salt/cli/run.py", line 41, in run
    runner.run()
  File "/root/salt/salt/runner.py", line 181, in run
    False)  # Don't daemonize
  File "/root/salt/salt/client/mixins.py", line 406, in _proc_function
    return self.low(fun, low)
  File "/root/salt/salt/client/mixins.py", line 359, in low
    mminion=self.mminion,
  File "/root/salt/salt/utils/job.py", line 88, in store_job
    mminion.returners[fstr](load)
  File "/root/salt/salt/returners/local_cache.py", line 161, in returner
    os.path.join(hn_dir, RETURN_P), 'w+b'
  File "/root/salt/salt/payload.py", line 224, in dump
    fn_.close()
  File "/root/salt/salt/utils/atomicfile.py", line 121, in close
    shutil.copymode(self._filename, self._tmp_filename)
  File "/usr/lib64/python2.7/shutil.py", line 89, in copymode
    st = os.stat(src)
OSError: [Errno 2] No such file or directory: '/var/cache/salt/master/jobs/18/9c31e51d0fc4fb826f2a4d114b9574/centos-7-main_master/return.p'
```
```yaml
centos-7-main salt 2015.8 # salt-run --versions
Salt Version:
           Salt: 2015.8.3-541-g27df727

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5
           cffi: Not Installed
       cherrypy: 3.6.0
       dateutil: Not Installed
          gitdb: 0.6.4
      gitpython: 0.3.6
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 0.3.7
          smmap: 0.9.0
        timelib: 0.2.4

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.3.1.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
```

**Comment by cachedout** [comment]
Could you please provide more context here? Is this happening on every run? Is it just runners or do you see this with other jobs?

**Comment by jfindlay** [comment]
This happens on every run.  I haven't found a runner function where this does not happen.  The runner itself seems to succeed, but then there is this traceback about the job cache.

**Comment by jfindlay** [comment]
Duplicate of #30204.
