### ISSUE TITLE
Is filesystem s3fs broken on Centos7 w/2015.8.1, or am I doin' it wrong?

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#30276]
Master config:

```
fileserver_backend:
  - s3fs

s3.keyid: <my key id here>
s3.key: <my key here>

s3.buckets:
  - my-bucket-one
  - my-bucket-two
```

When I run `salt-run fileserver.update` on the master:

```
Exception occurred in runner fileserver.update: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 337, in low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/runners/fileserver.py", line 258, in update
    fileserver.update(back=backend)
  File "/usr/lib/python2.7/site-packages/salt/fileserver/__init__.py", line 412, in update
    self.servers[fstr]()
  File "/usr/lib/python2.7/site-packages/salt/fileserver/s3fs.py", line 103, in update
    metadata = _init()
  File "/usr/lib/python2.7/site-packages/salt/fileserver/s3fs.py", line 348, in _init
    metadata = _refresh_buckets_cache_file(cache_file)
  File "/usr/lib/python2.7/site-packages/salt/fileserver/s3fs.py", line 468, in _refresh_buckets_cache_file
    log.warning("'{0}' response for bucket '{1}'".format(meta_response['Code'], bucket_name))
KeyError: 'Code'
```

That's not at all what I expected... Any clue as to what's wrong? Me? Salt?

My versions report:

```
[root@master pillar]# salt-call --versions-report
Salt Version:
           Salt: 2015.8.1
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
System Versions:
           dist: centos 7.1.1503 Core
        machine: x86_64
        release: 3.10.0-229.14.1.el7.x86_64
         system: CentOS Linux 7.1.1503 Core
```

**Comment by jfindlay** [comment]
@waynew, thanks for the report.  This looks like a bug to me based on my research:
- `git diff v2015.8.1:salt/fileserver/s3fs.py..v2015.8.3:salt/fileserver/s3fs.py` shows nothing
- Your configuration matches the [example documentation](https://docs.saltstack.com/en/latest/ref/file_server/all/salt.fileserver.s3fs.html)

**Comment by waynew** [comment]
Thanks for the quick response! If there's anything else I can help with, let me know

**Comment by waynew** [comment]
Some further information: I tossed some extra logging in there - it appears to be getting thrown when my bucket actually has no files. As it actually has no files :)

Looks like that's definitely the case - `bucket_one` has files, `bucket_two` does not.

Changing to:

```
s3.buckets:
  - bucket_one
#  - bucket_two
```

Allows the state to run A-OK.

A quick fix-ish would be a note in the docs for the affected versions mentioning that buckets *must* have files

Then of course fixing the behavior going forward so either it's OK if the buckets don't have files, or a sensible message is raised :)

**Comment by jfindlay** [comment]
@waynew, I totally agree; thanks for your extra work on this.

**Comment by pass-by-value** [comment]
@waynew and @jfindlay #30310 should resolve this

**Comment by waynew** [comment]
Looks like it fixes it for me:

```
# salt-run fileserver.update
[WARNING ] S3 Error! Do you have any files in your S3 bucket?
True
```

:+1: thanks!

**Comment by pass-by-value** [comment]
Thanks for checking @waynew! I'll close this once the patch is merged.

**Comment by jfindlay** [comment]
Thanks, @pass-by-value.
