### ISSUE TITLE
When I run salt-api 2015,   AttributeError:'str' object has no attribute 'get' 

### ISSUE THREAD

**Issue by hxnan** [saltstack/salt#30317]
I install the salt 2015 by `python install setup.py --record log`

relhat4.4.7-4

Error as bellow:
```
[root@XXXXX python2.7]# salt-api
[INFO    ] Setting up the Salt API
[INFO    ] The salt-api is starting up
[INFO    ] Starting rest.start netapi module
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/site-packages/salt/netapi/rest_cherrypy/__init__.py", line 80, in start
    root, apiopts, conf = app.get_app(__opts__)
  File "/usr/local/lib/python2.7/site-packages/salt/netapi/rest_cherrypy/app.py", line 2405, in get_app
    root = API()  # cherrypy app
  File "/usr/local/lib/python2.7/site-packages/salt/netapi/rest_cherrypy/app.py", line 2340, in __init__
    self._update_url_map()
  File "/usr/local/lib/python2.7/site-packages/salt/netapi/rest_cherrypy/app.py", line 2327, in _update_url_map
    self.apiopts.get('webhook_url', 'hook').lstrip('/'): Webhook,
AttributeError: 'str' object has no attribute 'get'
[INFO    ] Process <function start at 0x7f4ffa518140> (55461) died with exit status None, restarting...
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/site-packages/salt/netapi/rest_cherrypy/__init__.py", line 80, in start
    root, apiopts, conf = app.get_app(__opts__)
  File "/usr/local/lib/python2.7/site-packages/salt/netapi/rest_cherrypy/app.py", line 2405, in get_app
    root = API()  # cherrypy app
  File "/usr/local/lib/python2.7/site-packages/salt/netapi/rest_cherrypy/app.py", line 2340, in __init__
    self._update_url_map()
  File "/usr/local/lib/python2.7/site-packages/salt/netapi/rest_cherrypy/app.py", line 2327, in _update_url_map
    self.apiopts.get('webhook_url', 'hook').lstrip('/'): Webhook,
AttributeError: 'str' object has no attribute 'get'
[INFO    ] Process <function start at 0x7f4ffa518140> (55462) died with exit status None, restarting...
Process Process-3:
Traceback (most recent call last):
```
I google this info , but nothing work,

**Comment by jizhilong** [comment]
it seems be related to your settings, pasting your settings for salt-api would be helpful

**Comment by jfindlay** [comment]
@hxnan, thanks for the report.  As @jizhilong indicates, we need to see your salt-api configs.

**Comment by hxnan** [comment]
Sorry for late.
Is this config?  @jfindlay @jizhilong 
/etc/salt/master.d/api.conf

rest_cherrypy:
    host:10.63.74.53
    port:8000
    disable_ssl:true

external_auth:
    pam:
        webadmin
        - .*
        - '@wheel'
        - '@runner'

**Comment by jizhilong** [comment]
@hxnan, your config for `rest_cherrypy` is malformed. according to http://docs.ansible.com/ansible/YAMLSyntax.html:

> A dictionary is represented in a simple key: value form (the colon must be followed by a space):

so you should adjust  your settings as below：

```
rest_cherrypy:
    host: 10.63.74.53
    port: 8000
    disable_ssl: true

external_auth:
    pam:
        webadmin
        - .*
        - '@wheel'
        - '@runner'
```

**Comment by hxnan** [comment]
@jizhilong Thanks a lot :+1: 
Actually I do not like Yaml , I write a wrong config, why not remind me the Syntax Error.
I prefer the JSON...

**Comment by jfindlay** [comment]
@hxnan, do you consider this issue resolved?

**Comment by hxnan** [comment]
@jfindlay  yes ,thanks

**Comment by jfindlay** [comment]
Great, thanks @hxnan.
