### ISSUE TITLE
runner.cloud.create UnpackValueError

### ISSUE THREAD

**Issue by DenisBY** [saltstack/salt#30365]
We are starting to get this error in logs. How to fix it?

2016-01-14 18:44:40,396 [salt.utils.event ][DEBUG   ][12147] Sending event - data = {'jid': '20160114184440205765', 'return': 'Exception occurred in runner cloud.create: Traceback (most recent call last):\n  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 337, in low\n    data[\'return\'] = self.functions[fun](*args, **kwargs)\n  File "/usr/lib/python2.7/dist-packages/salt/runners/cloud.py", line 160, in create\n    info = client.create(provider, instances, **create_kwargs)\n  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 401, in create\n    mapper.create(vm_))\n  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1249, in create\n    output = self.clouds[func](vm_)\n  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 2286, in create\n    vm_[\'name\'], vm_[\'profile\'], \'ec2\', vm_[\'driver\']\n  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 2360, in cachedir_index_add\n    index = msgpack.load(fh_)\n  File "_unpacker.pyx", line 130, in msgpack._unpacker.unpack (msgpack/_unpacker.cpp:132)\n  File "_unpacker.pyx", line 119, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:119)\nUnpackValueError\n', 'success': False, '_stamp': '2016-01-14T18:44:40.395457', 'user': 'Reactor', 'fun': 'runner.cloud.create'}

**Comment by DenisBY** [comment]
I've fixed it by removing /var/cache/salt
For unknown reason /var/cache/salt/index.p became zero size.
