### ISSUE TITLE
pkg.latest is broken with yumpkg in develop

### ISSUE THREAD

**Issue by gtmanfred** [saltstack/salt#30377]
```
          ID: keystone packages
    Function: pkg.latest
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1682, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1582, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/pkg.py", line 1519, in latest
                  if not avail[pkg]:
              TypeError: list indices must be integers, not str
     Started: 02:36:04.461842
    Duration: 4281.374 ms
     Changes:
```

Looks like the package list used to return a dictionary with each one of the packages, and no version number, and now if everything is updated, it returns an empty list, which would be fine, but the avail list is used in pkg.latest.

https://github.com/saltstack/salt/blob/develop/salt/states/pkg.py#L1473

Looks like it is coming from the changes @terminalmage did back in december.

https://github.com/saltstack/salt/commit/47534b29b44a26b0333e7f126174a332e7665fea

**Comment by gtmanfred** [comment]
This is the state that I am using https://github.com/gtmanfred/openstack-salt-states/blob/master/keystone/packages.sls

```
keystone packages:
  pkg.latest:
    - pkgs:
      - openstack-keystone
      - python-psycopg2
      - httpd
      - mod_wsgi
      - python-memcached
```

**Comment by gtmanfred** [comment]
```
[root@keystone salt]# salt-call --versions-report
Salt Version:
           Salt: 2015.8.3-4860-ge399a0b

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: 0.8.1
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 1.1.2
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.4.4.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
```

**Comment by jfindlay** [comment]
@gtmanfred, thanks for reporting.

**Comment by terminalmage** [comment]
Fixed in https://github.com/saltstack/salt/pull/30393
