### ISSUE TITLE
make salt-ssh error when ssh is missing more human-readable

### ISSUE THREAD

**Issue by bechtoldt** [saltstack/salt#30413]
something like "we couldn't find a ssh binary" is better than

```
[INFO    ] Loading Saltfile from '/srv/salt/profiles/india/Saltfile'
[DEBUG   ] Reading configuration from /srv/salt/profiles/india/Saltfile
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
OSError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/usr/bin/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 377, in salt_ssh
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/ssh.py", line 20, in run
    ssh = salt.client.ssh.SSH(self.config)
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 172, in __init__
    self.opts['_ssh_version'] = ssh_version()
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 1248, in ssh_version
    stderr=subprocess.PIPE).communicate()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/usr/bin/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 377, in salt_ssh
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/ssh.py", line 20, in run
    ssh = salt.client.ssh.SSH(self.config)
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 172, in __init__
    self.opts['_ssh_version'] = ssh_version()
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 1248, in ssh_version
    stderr=subprocess.PIPE).communicate()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by basepi** [comment]
An OSError could probably be thrown for a few other reasons, but we could probably catch it and add something like "probably a missing ssh binary" or something. Though since the command is called `salt-ssh` I'm wondering if we should do anything at all. I think it's pretty obvious that ssh is required, and I hate to mask other potential errors for the small subset that try to run it without ssh installed.

I'll have to think on this.

**Comment by bechtoldt** [comment]
Or simply check whether the ssh binary is available at all upon salt-ssh startup or similar.

Just think of a minimal Docker base image that doesn't contain a SSH client by default. The OSError above doesn't even tell which file/dir is missing. ;)

**Comment by basepi** [comment]
Yes, you're obviously right. We should just check ahead of time. Thanks for the sanity check. :)
