### ISSUE TITLE
Error DDNS

### ISSUE THREAD

**Issue by npithon** [saltstack/salt#30422]
Hello,
I tried to use SALT.STATES.DDNS but It does not work.
My ddns.sls:

``` sls
#start
{% set myhostname = salt['grains.get']('nodename') %}
{% set myip = salt['grains.get']('ipv4')[1] %}

/path/to/tsig_key.txt:
  file.managed:
        - source: salt://path/to/files/tsig_key.txt
        - user: dns_user
        - mode: 600

{{ myhostname }}:
    ddns.present:
      - name: {{ myhostname }}.example.com.
      - zone: example.com
      - ttl: 3600
      - data: {{ myip }}
      - nameserver: 1.2.3.4  <== My DNS server
      - keyfile: /path/to/tsig_key.txt
#end
```

My tsig_key.txt:

```
#cat tsig_key.txt
aBOu......Dmp+ro........jujUcQ==
```

When i update the state i have an error:

---

``` python-traceback
ID: my_hostname
Function: ddns.present
Name: my_hostname.example.com.
Result: False
Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1602, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1491, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/ddns.py", line 57, in present
                  status = __salt__['ddns.update'](zone, name, ttl, rdtype, data, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/ddns.py", line 156, in update
                  request = dns.message.make_query(fqdn, rdtype)
                File "/usr/local/lib/python2.7/dist-packages/dns/message.py", line 1065, in make_query
                  qname = dns.name.from_text(qname)
                File "/usr/local/lib/python2.7/dist-packages/dns/name.py", line 650, in from_text
                  raise EmptyLabel
              EmptyLabel
Started: 14:38:59.938483
Duration: 2.166 ms
Changes:
```

---

``` yaml
salt --versions-report 
    - server
Salt Version:
           Salt: 2015.8.3

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-24-generic
         system: Ubuntu 14.04 trusty

    - client
Salt Version:
           Salt: 2015.8.3-138-g654cab0

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-48-generic
         system: Ubuntu 14.04 trusty
```

**Comment by jfindlay** [comment]
@npithon, thanks for the report.  This looks like a problem in the ddns execution module.

**Comment by PhilippeAB** [comment]
I was stuck few hours on this problem too, the salt doc does not specify the file format.
Did not find it in the dnspython either.
looking at the code, i figured out it should be json

{ "yourdomain.": "your key" }

don't forget the final '.' on your domain
