### ISSUE TITLE
salt.runner.asam should handle missing HTMLParser better

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#30477]
When starting the master this message gets logged:
```
2016-01-20 17:43:12,787 [salt.utils.parsers][WARNING ][33485] Master received a SIGTERM. Exiting.
2016-01-20 17:43:34,825 [salt.loader      ][ERROR   ][34694] Failed to import runners asam, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "salt/loader.py", line 1228, in _load_module
  File "salt/runners/asam.py", line 71, in <module>
NameError: name 'HTMLParser' is not defined
```
The ```__virtual__``` function does seem to handle the cases when HTMLParser is not importable...

But because this class is also defined:
```python
class ASAMHTMLParser(HTMLParser):
  ...
```
In the main namespace, python fails to load the module due to missing HTMLParser and salt never get's to the ```__virtual__``` call due to the python complaining.

I tried changing some of the order but had no success.

**Comment by sjorge** [comment]
Attached is a diff that 'fixes' the error for me, but I am not sure the runner still works as I am not sure how to test it.

```diff
diff --git a/salt/runners/asam.py b/salt/runners/asam.py
index dbd0067..36cac66 100644
--- a/salt/runners/asam.py
+++ b/salt/runners/asam.py
@@ -49,25 +49,25 @@ try:
         except ImportError:
             pass
     HAS_LIBS = True
-except ImportError:
-    pass

-log = logging.getLogger(__name__)
+    class ASAMHTMLParser(HTMLParser):
+        def __init__(self):
+            HTMLParser.__init__(self)
+            self.data = []

+        def handle_starttag(self, tag, attrs):
+            if tag != "a":
+                return
+            for attr in attrs:
+                if attr[0] != "href":
+                    return
+                self.data.append(attr[1])

-class ASAMHTMLParser(HTMLParser):
+except ImportError:
+    pass

-    def __init__(self):
-        HTMLParser.__init__(self)
-        self.data = []

-    def handle_starttag(self, tag, attrs):
-        if tag != "a":
-            return
-        for attr in attrs:
-            if attr[0] != "href":
-                return
-            self.data.append(attr[1])
+log = logging.getLogger(__name__)


 def __virtual__():
```

**Comment by jfindlay** [comment]
@sjorge, your fix looks right to me.  Will you send in a pull request?  Thanks.

**Comment by sjorge** [comment]
Sure, I'll have a PR up in a few.
