### ISSUE TITLE
salt-run salt.orchestrate crashes due to an exception

### ISSUE THREAD

**Issue by mmisztal1980** [saltstack/salt#30474]
Part of my work on the event reactor includes an orchestration step

/srv/salt/orch/orchestrate-stuff.sls
```{% set targetsite = 'my.awesome.site.com %}

stop-my.awesome.site.com:
    salt.state:
        - tgt: 'sites:{{ targetsite }}' # <== A minion with sites:my.awesome.site.com exists in the env.
        - expr_form: 'grain'
        - sls:
            - iis-website-stop
        - pillar:            
            - websitename: 'devua-{{ targetsite }}'
```

/srv/salt/iis-website-stop.sls

```
# file: iis-website-stop.sls
{% set websitename = salt.pillar.get('websitename') %}

stop-iis-website:
    cmd.run:
        - name: Stop-Website -Name {{ websitename }}
        - shell: 'powershell'
```

I'm attempting to debug this on the go, however it seems to be crashin and I have no idea what am I doing wrong... Is there anything wrong with my YAML/Jinja?

```sudo salt-run state.orchestrate orch.orchestrate-stuff -l debug``` yields the following results:

```
[WARNING ] Output from salt state not highstate
[ERROR   ] An exception occurred in this state: Traceback (most recent call last
):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1594, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1491, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/states/saltmod.py", line 259, in s
tate
    for state_item in six.itervalues(m_ret):
  File "/usr/lib/python2.7/dist-packages/salt/ext/six.py", line 580, in itervalu
es
    return iter(d.itervalues(**kw))
AttributeError: 'str' object has no attribute 'itervalues'

devua-salt01_master:
----------
          ID: stop-my.awesome.site.com
    Function: salt.state
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call l
ast):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1594
, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 149
1, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/saltmod.py",
line 259, in state
                  for state_item in six.itervalues(m_ret):
                File "/usr/lib/python2.7/dist-packages/salt/ext/six.py", line 58
0, in itervalues
                  return iter(d.itervalues(**kw))
              AttributeError: 'str' object has no attribute 'itervalues'
     Started: 14:54:16.617009
    Duration: 3803.699 ms
     Changes:

Summary for devua-salt01_master
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   3.804 s
```

**Comment by ssgward** [comment]
@mmisztal1980 - what version of salt are you using? ``salt --versions-report``. There was a known issue with orchestrate in 2015.8.1-8.2, IIRC.

**Comment by mmisztal1980** [comment]
@ssgward 

```
Salt Version:
           Salt: 2015.8.3

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.19.0-41-generic
         system: Ubuntu 14.04 trusty
```

**Comment by tbaker57** [comment]
@mmisztal1980  Are you sure this is right? :
```
{% set websitename = salt.pillar.get('websitename') %}
```
Does it help if you use
```
{% set websitename = salt['pillar.get']('websitename') %}
```
?
cheers,
Tim

**Comment by mmisztal1980** [comment]
@tbaker57 Hi Tim, 

I've done as you asked and restarted the salt-master service (I thought 'why the heck not?') got the result below - next I reverted the change and got the same result:

```
devua-salt01_master:
----------
          ID: stop-my.awesome.website.com
    Function: salt.state
      Result: True
     Comment: States ran successfully.
     Started: 20:45:11.213848
    Duration: 17459.446 ms
     Changes:

Summary for devua-salt01_master
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:  17.459 s
```

What's extremely interesting to me in this output, is the fact that devua-salt01_master is not the expected minion to handle this state. I've verified the state of the IIS server on the target machine and the change of state didn't take place so I'm getting some sort of a false positive output from salt ?

**Comment by ssgward** [comment]
@mmisztal1980 - sounds like you have Windows minions as part of your environment, correct or no?

**Comment by mmisztal1980** [comment]
That's correct, the target minion is running on a Windows Server 2012 R2, 

```
C:\salt>salt-call --version
salt-call 2015.8.3 (Beryllium)
```

**Comment by tbaker57** [comment]
It looks like the jinja issue causing the exception was fixed. However, why it is targeting the wrong minion I don't know. 
Since you are targeting by grains, can you confirm that the 'sites' grain shows the correct value on the expected minion ? E.g. running
```
salt <minion_id_for_expected_target_minion> grains.get sites
```
on the master - does give the expected value of the 'sites' grain ?

cheers,
Tim

**Comment by mmisztal1980** [comment]
It does. Just checked (just to be sure)

**Comment by tbaker57** [comment]
Hmm. How about taking orchestration out of the picture. Can you run the equivalent salt command directly and see if it gets executed on the target minion, something like
```
salt -G 'site:xxx' state.sls iis-website-stop pillar='{"websitename": "devua-xxx"}'
```
where xxx is the targetsite ?
If it is successful using the above command, then orchestration must be the issue. If it fails to execute with the above command then there's something else going wrong (not orchestration).

cheers,
Tim

**Comment by mmisztal1980** [comment]
@tbaker57 Hi Tim,

I've executed the said request. The target minion was determined correctly, however the response was not entirely what I've expected:

```
devua-web02.devua.sys:
    'iis-website-stop' is not available.
ERROR: Minions returned with non-zero exit code
```

The path to the state file is : /srv/salt/iis-website-stop.sls - I've verified the file to physically exist on the salt-master

**Comment by mmisztal1980** [comment]
I've executed the said request again, this time I've noticed that I've left out the ```state.sls``` part of the cmd, 

I got the following result:

```
devua-web02.devua.sys:
----------
          ID: stop-iis-website
    Function: cmd.run
        Name: Stop-Website -Name devua-my.awesome.website.com
      Result: True
     Comment: Command "Stop-Website -Name devua-my.awesome.website.com" run
     Started: 10:41:03.753000
    Duration: 781.0 ms
     Changes:
              ----------
              pid:
                  7008
              retcode:
                  0
              stderr:
              stdout:

Summary for devua-web02.devua.sys
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time: 781.000 ms
```

The state was applied correctly, and the IIS website was stopped.

**Comment by tbaker57** [comment]
Ok, the only other thing to check is to make sure {{ targetsite }} renders to what you think it should (maybe running the orchestration with '-l debug' will give you the results of jinja rendering in the debug output)

cheers,
Tim

**Comment by mmisztal1980** [comment]
The result of the ```/srv/salt/orch/orchestrate-stuff.sls``` rendering contains the following fragment:

```
stop-my.asesome.site.com:
    salt.state:
        - tgt: 'sites:my.asesome.site.com'
        - expr_form: 'grain'
        - sls:
            - iis-website-stop
        - pillar:
            - websitename: 'devua-my.awesome.site.com'
```

The rendering in this file is correct.

The exception appears to happen minion-side, however I have no idea what is the rendering result in there as it is not present in the output.

**Comment by mmisztal1980** [comment]
Hi guys,

Any ideas how to work around the issue?

/Maciej

**Comment by tbaker57** [comment]
@mmisztal1980 - I'm a bit confused now. Your original post showed an exception on the master, but now you're saying there is an exception on the minion ? Is this with the original configuration you showed ? What are the details of the minion exception ?

cheers,
Tim

**Comment by mmisztal1980** [comment]
@tbaker57  When running a ```salt-run state.orchestrate orch.orchestrate-stuff.sls -l debug``` I get the following output :

```
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache u'salt://orch/orchestrate-stuff.sls'
[DEBUG   ] compile template: /var/cache/salt/master/files/base/orch/orchestrate-stuff.sls
[DEBUG   ] Jinja search path: ['/var/cache/salt/master/files/base']
[PROFILE ] Time (in seconds) to render '/var/cache/salt/master/files/base/orch/orchestrate-stuff.sls' using 'jinja' renderer: 0.00787115097046
[DEBUG   ] Rendered data from file: /var/cache/salt/master/files/base/orch/orchestrate-stuff.sls:
# file: orchestrate-stuff.sls

(...) Correctly Rendered YAML using Jinja here

[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Results of YAML rendering:
OrderedDict([('stop-my.awesome.website.com', OrderedDict([('salt.state', [OrderedDict([('tgt', 'sites:my.awesome.website.com')]), OrderedDict([('expr_form', '
grain')]), OrderedDict([('sls', ['iis-website-stop'])]), OrderedDict([('pillar', [OrderedDict([('websitename', 'devua-my.awesome.website.com')])])])])])), ('co
py-xsd-files-to-my.awesome.website.com', OrderedDict([('salt.state', [OrderedDict([('tgt', 'sites:my.awesome.website.com')]), OrderedDict([('expr_form', 'grai
n')]), OrderedDict([('sls', ['copy-xsd-files'])]), OrderedDict([('pillar', [OrderedDict([('version', None)]), OrderedDict([('filename', None)])])]), OrderedDict
([('require', [OrderedDict([('salt', 'stop-my.awesome.website.com')])])])])])), ('start-my.awesome.website.com', OrderedDict([('salt.state', [OrderedDict([('t
gt', 'sites:my.awesome.website.com')]), OrderedDict([('expr_form', 'grain')]), OrderedDict([('sls', ['iis-website-start'])]), OrderedDict([('pillar', [OrderedD
ict([('websitename', 'devua-my.awesome.website.com')])])]), OrderedDict([('require', [OrderedDict([('salt', 'copy-xsd-files-to-my.awesome.website.com')])])])]
)]))])
[PROFILE ] Time (in seconds) to render '/var/cache/salt/master/files/base/orch/orchestrate-stuff.sls' using 'yaml' renderer: 0.0160098075867
[DEBUG   ] LazyLoaded salt.state
[INFO    ] Running state [stop-my.awesome.website.com] at time 17:09:51.185663
[INFO    ] Executing state salt.state for stop-my.awesome.website.com
[DEBUG   ] LazyLoaded saltutil.cmd
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/reactor.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/reactor.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: devua-salt01
[DEBUG   ] Missing configuration file: /home/kmdadmin/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'devua-salt01_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] LazyLoaded local_cache.get_load
```

If I'm interpreting the output right, salt now determines that the correct minion to handle this is devua-web02.devua.sys and waits for the result of the job execution on the minion...

```
[DEBUG   ] get_iter_returns for jid 20160125170951301616 sent to set(['devua-web02.devua.sys']) will timeout at 17:09:56.310417
[DEBUG   ] jid 20160125170951301616 return from devua-web02.devua.sys
[DEBUG   ] jid 20160125170951301616 found all minions set(['devua-web02.devua.sys'])
[WARNING ] Output from salt state not highstate
```

... and isn't this what has happened on the minion side?

```
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1594, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1491, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/states/saltmod.py", line 259, in state
    for state_item in six.itervalues(m_ret):
  File "/usr/lib/python2.7/dist-packages/salt/ext/six.py", line 580, in itervalues
    return iter(d.itervalues(**kw))
AttributeError: 'str' object has no attribute 'itervalues'

[INFO    ] Completed state [stop-my.awesome.website.com] at time 17:09:54.970015
```

**Comment by tbaker57** [comment]
Sorry @mmisztal1980 I don't have any insights here. The exception seems to be occurring when the minion returns data to the master in saltmod.py line 259 - it's expecting a dict but received a string instead. Unfortunately it might be easiest to start inserting print statements into /usr/lib/python2.7/dist-packages/salt/states/saltmod.py to see what that string actually is, which might give more clues as to what is happening.

cheers,
Tim

**Comment by mmisztal1980** [comment]
I've restarted the minion in console mode and got the following stdout output :

```
[DEBUG   ] LazyLoaded state.sls
[DEBUG   ] LazyLoaded saltutil.is_running
[DEBUG   ] LazyLoaded grains.get
[ERROR   ] Problem executing 'state.sls': Pillar data must be formatted as a dic
tionary
Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 1039, in _thread_ret
urn
    return_data = func(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\modules\state.py", line 689, in sls
    'Pillar data must be formatted as a dictionary'
SaltInvocationError: Pillar data must be formatted as a dictionary
[DEBUG   ] Minion return retry timer set to 9 seconds (randomized)
[INFO    ] Returning information for job: 20160126153540448782
```

Seems we have the root cause, but I'm still not sure how to remedy that

**Comment by tbaker57** [comment]
Can you show a redacted version of your pillar (if it's not too big) ?

**Comment by mmisztal1980** [comment]
@tbaker57 Hi Tim, it's at the very top of this thread :

```
stop-my.awesome.site.com:
    salt.state:
        - tgt: 'sites:{{ targetsite }}' # <== A minion with sites:my.awesome.site.com exists in the env.
        - expr_form: 'grain'
        - sls:
            - iis-website-stop
        - pillar:            
            - websitename: 'devua-{{ targetsite }}'
```

**Comment by tbaker57** [comment]
Hmm - I wonder if the value of the pillar key should be a dict rather than a list in the orchestration definition ? Can you try
```
        - pillar:            
            websitename: 'devua-{{ targetsite }}'
```
instead (get rid of that hyphen)

**Comment by mmisztal1980** [comment]
That fixes the issue :)

In other words, it works fine, but the error notification(s) could use some improvement - I've spent quite a lot of time (being a newbie) to determine the issue...

Thank you to everyone involved for the help
