### ISSUE TITLE
Received bad data when setting the match from the top file - gitfs fails to check out

### ISSUE THREAD

**Issue by anlutro** [saltstack/salt#30500]
On our salt masters, it looks like if a gitfs checkout fails, a `salt '*' state.apply` fails ONLY for the minion running on the same salt master. Every other minion works fine. If I wait a bit and run the same command, it'll work just fine.

Edit/correction: This has happened when running highstates against other types of minions as well.

We use pygit2 + libgit2.

I suspect this has something to do with us using the same git repository for pillars as for states. Maybe Salt is trying to check out both the states and the pillars at the same time?

/var/log/salt/master has this line:
```
2016-01-21 12:42:50,353 [salt.utils.gitfs ][ERROR   ][18179] Failed to checkout master from git_pillar remote 'master git@REDACTED': REDACTED: The index is locked. This might be due to a concurrent or crashed process
```

/var/log/salt/minion has this:
```
2016-01-21 12:42:50,365 [salt.state       ][INFO    ][2270] Loading fresh modules for state activity
2016-01-21 12:42:50,394 [salt.fileclient  ][INFO    ][2270] Fetching file from saltenv 'base', ** skipped ** latest already in cache u'salt://top.sls'
2016-01-21 12:42:50,412 [salt.minion      ][ERROR   ][2270] Received bad data when setting the match from the top file
```

I'm not 100% sure if these are correlated, but the timestamps seem to match somewhat, and the minion error only seems to happen when the master error is also present in the logs.

Versions report:

```
Salt Version:
           Salt: 2015.8.3
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: 1.0.0
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: 3.5.0
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: 0.23.1
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: debian 8.2 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.2
```

**Comment by jfindlay** [comment]
@anlutro, thanks for the report.

**Comment by anlutro** [comment]
Until this gets fixed, are there any workarounds I might try out?

**Comment by jfindlay** [comment]
@anlutro, not that I know of.

**Comment by anlutro** [comment]
I'm going to try and run a cronjob that `git pull`s our git repository into two separate directories - `/root/salt_states.git` and `/root/salt_pillars.git`, and use those two as gitfs and ext_pillar sources respectively, and see if that makes any difference.

**Comment by anlutro** [comment]
That didn't seem to make a difference either.

```
2016-02-02 12:49:03,398 [salt.utils.gitfs ][ERROR   ][21664] Failed to checkout master from git_pillar remote 'master /root/salt_pillars.git': ...: The index is locked. This might be due to a concurrent or crashed process
```

I suspect this may be an issue with the pygit2 implementation of the git external pillar in general...

**Comment by anlutro** [comment]
I increased the log level and think I tracked down the exact cause. This is being logged by one of the salt-master daemon processes:

```
2016-02-02 13:32:47,174 [salt.fileserver  ][DEBUG   ][5656] Updating git fileserver cache
2016-02-02 13:32:47,175 [salt.utils.gitfs ][DEBUG   ][5656] Set lock for REDACTED
2016-02-02 13:32:47,175 [salt.utils.gitfs ][DEBUG   ][5656] gitfs is fetching from 'REDACTED'
```

... right before the process of `salt 'name-of-minion' state.apply` starts:

```
2016-02-02 13:32:47,412 [salt.config      ][DEBUG   ][7387] Reading configuration from /etc/salt/master
```

Later on in the log:

```
2016-02-02 13:32:47,820 [salt.loaded.int.pillar.git_pillar][DEBUG   ][5761] git_pillar is processing pillar SLS from /var/cache/salt/master/git_pillar/REDACTED/pillars for pillar env 'base'
2016-02-02 13:32:47,817 [salt.utils.gitfs ][ERROR   ][5766] Failed to checkout master from git_pillar remote 'master REDACTED': The index is locked. This might be due to a concurrent or crashed process
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 749, in checkout
    self.repo.checkout(local_ref)
  File "/usr/local/lib/python2.7/dist-packages/pygit2/repository.py", line 277, in checkout
    self.checkout_tree(treeish, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pygit2/repository.py", line 231, in checkout_tree
    check_error(C.git_checkout_tree(self._repo, cptr[0], copts))
  File "/usr/local/lib/python2.7/dist-packages/pygit2/errors.py", line 64, in check_error
    raise GitError(message)
GitError: The index is locked. This might be due to a concurrent or crashed process
```

Note the timestamps in the log above, as the log entries did not get written in chronological order.

Later on in the log, after the state run has finished, the gitfs lock is removed:

```
2016-02-02 13:32:51,507 [salt.utils.gitfs ][DEBUG   ][5656] gitfs remote 'REDACTED' is up-to-date
2016-02-02 13:32:51,508 [salt.utils.gitfs ][DEBUG   ][5656] pygit2 does not support detecting stale refs for authenticated remotes, saltenvs will not reflect branches/tags removed from remote 'REDACTED'
2016-02-02 13:32:51,508 [salt.utils.gitfs ][DEBUG   ][5656] Removed lock for REDACTED
```

**Comment by anlutro** [comment]
I see that some logic has been added in 2015.8.4 which might help with this, so I'll be eagerly awaiting that to be released for Debian so I can see if it helps...

**Comment by anlutro** [comment]
Upgraded to 2015.8.7 and the issue is still present.

```
2016-02-19 10:16:24,558 [salt.utils.gitfs ][ERROR   ][3254] Failed to checkout master from git_pillar remote 'master git@REDACTED': The index is locked. This might be due to a concurrent or crashed process
```

**Comment by anlutro** [comment]
I have to give up on using gitfs until this is fixed or there is a workaround. Like 50% of our automated highstates from reactors are failing because of this.

**Comment by anlutro** [comment]
I'll try switching back to gitfs when 8e086099f55fd6277156c2b21f497f8d97787dfc hits a release.

**Comment by anlutro** [comment]
Just found another issue that this issue is a duplicate of, so I'll close this. https://github.com/saltstack/salt/issues/29239

**Comment by jfindlay** [comment]
@anlutro, 2015.8.8 should be coming out in a few days.
