### ISSUE TITLE
Rest CherryPy returns 401

### ISSUE THREAD

**Issue by pass-by-value** [saltstack/salt#30527]
Following external auth section and salt api config is defined in `/etc/salt/master`

```yaml
external_auth:
  pam:
    adi:
#       - 'test.*'
      - .*
#      - '@runner'
#      - '@wheel'

rest_cherrypy:
 port: 8000
 debug: True
 disable_ssl: True
```
 
Here's my cherrypy version

```shell
(salt-work)--- ~/salt ‹2015.8* M› » pip show cherrypy                                                                                                1 ↵
---
Name: CherryPy
Version: 3.2.3
Location: /Users/adi/Envs/salt-work/lib/python2.7/site-packages
Requires:
(salt-work)--- ~/salt ‹2015.8* M› »
```

Salt version and python version are as follows

```shell
Requires:
(salt-work)--- ~/salt ‹2015.8* M› » python --version
Python 2.7.6
(salt-work)--- ~/salt ‹2015.8* M› » salt --versions-report
Salt Version:
           Salt: 2015.8.3-242-g79528c5

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.22
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
         Python: 2.7.6 (default, Jan 22 2014, 18:56:28)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: 0.8.2
       cherrypy: 3.2.3
       dateutil: 2.4.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: 0.21.0
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.0
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: 0.21.0
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist:
        machine: x86_64
        release: 14.5.0
         system: 10.10.5 -- x86_64
```

With the above system version and configs when I execute

```shell
curl -k localhost:8000 -H 'Accept: application/x-yaml' -d username=adi -d password=redacted -d eauth=pam -d client=local -d tgt='*' -d fun=test.ping
```

The following is thrown

```shell
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>401 Unauthorized</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>401 Unauthorized</h2>
        <p>No permission -- see authorization schemes</p>
        <pre id="traceback">Traceback (most recent call last):
  File "/Users/adi/Envs/salt-work/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 647, in respond
    self.hooks.run('before_request_body')
  File "/Users/adi/Envs/salt-work/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 112, in run
    raise exc
HTTPError: (401, None)
</pre>
    <div id="powered_by">
    <span>Powered by <a href="http://www.cherrypy.org">CherryPy 3.2.3</a></span>
    </div>
    </body>
</html>
```

I dont' see anything in the salt master's terminal window, but the following appears in `/var/log/salt/master` as soon as I start (`salt-api -l debug`)

```shell
2016-01-21 17:52:41,726 [salt.utils.process][DEBUG   ][4341] Started 'salt.loaded.int.netapi.rest_cherrypy.start' with pid 5196
2016-01-21 17:52:41,754 [ws4py            ][INFO    ][5196] Using select as epoll is not available
2016-01-21 17:52:41,756 [salt.utils.event ][DEBUG   ][5196] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
2016-01-21 17:52:41,757 [salt.utils.event ][DEBUG   ][5196] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
2016-01-21 17:52:41,782 [cherrypy.error   ][INFO    ][5196] [21/Jan/2016:17:52:41] ENGINE Listening for SIGHUP.
2016-01-21 17:52:41,782 [cherrypy.error   ][INFO    ][5196] [21/Jan/2016:17:52:41] ENGINE Listening for SIGTERM.
2016-01-21 17:52:41,783 [cherrypy.error   ][INFO    ][5196] [21/Jan/2016:17:52:41] ENGINE Listening for SIGUSR1.
2016-01-21 17:52:41,783 [cherrypy.error   ][INFO    ][5196] [21/Jan/2016:17:52:41] ENGINE Bus STARTING
2016-01-21 17:52:41,783 [cherrypy.error   ][INFO    ][5196] [21/Jan/2016:17:52:41] ENGINE Starting WebSocket processing
2016-01-21 17:52:41,784 [py.warnings      ][WARNING ][5196] CherryPy Checker:
'log_file' is obsolete. Use 'log.error_file' instead.
section: [saltopts]


2016-01-21 17:52:41,786 [cherrypy.error   ][INFO    ][5196] [21/Jan/2016:17:52:41] ENGINE Started monitor thread '_TimeoutMonitor'.
2016-01-21 17:52:41,823 [cherrypy.error   ][INFO    ][5196] [21/Jan/2016:17:52:41] ENGINE Started monitor thread 'Autoreloader'.
2016-01-21 17:52:42,046 [cherrypy.error   ][INFO    ][5196] [21/Jan/2016:17:52:42] ENGINE Serving on 0.0.0.0:8000
2016-01-21 17:52:42,047 [cherrypy.error   ][INFO    ][5196] [21/Jan/2016:17:52:42] ENGINE Bus STARTED
```

**Comment by pass-by-value** [comment]
This works when I pass an X-Auth token (sweet!). 

Please leave this open for now. I will close this after verifying that it is ok, end to end.

**Comment by whiteinge** [comment]
If you pass auth credentials in the request body you want the `/run` URL not the `/` URL.

**Comment by pass-by-value** [comment]
Thanks for the help @whiteinge I was able to get it to work. As always, salt-api delivers!
