### ISSUE TITLE
Execution module dockerng.create: specifying parameter binds= causes exception

### ISSUE THREAD

**Issue by zerthimon** [saltstack/salt#30597]
Running command as documented here: https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.dockerng.html#salt.modules.dockerng.create

```
salt-call dockerng.create myregistry/myimage:latest name=mycontainer binds=/my/local/vol:/my/local/vol
```

Causes exception:
```
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'str' object has no attribute 'items'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 331, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 53, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 133, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 196, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/dockerng.py", line 631, in wrapper
    returned = wrapped(*args, **salt.utils.clean_kwargs(**kwargs))
  File "/usr/lib/python2.7/dist-packages/salt/modules/dockerng.py", line 2930, in create
    **dict((arg, create_kwargs.pop(arg, None)) for arg in host_config_args if arg != 'version')
  File "/usr/lib/python2.7/dist-packages/docker/api/container.py", line 139, in create_host_config
    return utils.create_host_config(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/docker/utils/utils.py", line 583, in create_host_config
    host_config['Binds'] = convert_volume_binds(binds)
  File "/usr/lib/python2.7/dist-packages/docker/utils/utils.py", line 252, in convert_volume_binds
    for k, v in binds.items():
AttributeError: 'str' object has no attribute 'items'
```

However, the following command works fine:
```
salt-call dockerng.create myregistry/myimage:latest name=mycontainer binds='["/my/local/vol:/my/local/vol"]'
```

**Comment by ticosax** [comment]
You need to add the parameter `validate_input=True` so types get cast properly.

```
salt-call dockerng.create myregistry/myimage:latest name=mycontainer binds=/my/local/vol:/my/local/vol validate_input=True
```

**Comment by Ch3LL** [comment]
@zerthimon did @ticosax 's recommendation help you resolve your issue?

**Comment by zerthimon** [comment]
@Ch3LL , @ticosax wow, this is an old issue indeed. I filed it and forgot about it :(

I've just checked again and there's still exception when trying to run without `validate_input=True`
When this runs with `validate_input=True` there is no problem.

Is this flag an **undocumented secret feature** ? I can't find any reference about that flag in docs.
Is this salt's flag or dockerng module flag ?
What exactly does it do ?

**Comment by ticosax** [comment]
> Is this flag an undocumented secret feature ? I can't find any reference about that flag in docs.

Yes you are right, documentation seems to be missing.

>  Is this salt's flag or dockerng module flag ?

As far I can tell it is only specific to dockerng

> What exactly does it do ?

according to the docstring:

```
    Perform validation on kwargs. Checks each key in kwargs against the
    VALID_CONTAINER_OPTS dict and if the value is None, looks for a local
    function named in the format _valid_<kwarg> and calls that.

    The validation functions don't need to return anything, they just need to
    raise a SaltInvocationError if the validation fails.

    Where needed, this function also performs translation on the input,
    formatting it in a way that will allow it to be passed to either
    docker.client.Client.create_container() or
    docker.client.Client.start().
```

**Comment by zerthimon** [comment]
@ticosax thanks, for the answers.

Frankly, It's be awesome if the things just worked without this flag (i wonder how such situation is handled in other modules). On the other hand, and if this flag is absolutely necessary for the code, please document it's usage in the module's docs.

This issue can be closed.

**Comment by Ch3LL** [comment]
Closing now thanks
