### ISSUE TITLE
Execution module dockerng.create: specifying parameter restart_policy causes docker API status 500

### ISSUE THREAD

**Issue by zerthimon** [saltstack/salt#30596]
Running command as documented here: https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.dockerng.html#salt.modules.dockerng.create

```
salt-call dockerng.create myregistry/myimage:latest name=mycontainer restart_policy=on-failure:5
```

Causes docker API Status 500:

```
[DEBUG   ] "POST /v1.21/containers/create?name=mycontainer HTTP/1.1" 500 76
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 196, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/dockerng.py", line 631, in wrapper
    returned = wrapped(*args, **salt.utils.clean_kwargs(**kwargs))
  File "/usr/lib/python2.7/dist-packages/salt/modules/dockerng.py", line 2942, in create
    **create_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/dockerng.py", line 601, in wrapper
    return wrapped(*args, **salt.utils.clean_kwargs(**kwargs))
  File "/usr/lib/python2.7/dist-packages/salt/modules/dockerng.py", line 867, in _client_wrapper
    exc.explanation)
CommandExecutionError: Error 500: json: cannot unmarshal string into Go value of type runconfig.RestartPolicy
Error running 'dockerng.create': Error 500: json: cannot unmarshal string into Go value of type runconfig.RestartPolicy
```

However, the following command works fine:

```
salt-call dockerng.create myregistry/myimage:latest name=mycontainer restart_policy='{"Name": "on-failure", "MaximumRetryCount": 5}'
```

**Comment by jfindlay** [comment]
@zerthimon, thanks for the report.
