### ISSUE TITLE
AttributeError: 'list' object has no attribute 'setdefault'

### ISSUE THREAD

**Issue by HeathNaylor** [saltstack/salt#30753]
I upgraded from `2015.5.9` to `2015.8.3` and am now getting the following error when I do `salt-cloud -m <path_to_environment_file>`

```
[INFO    ] salt-cloud starting
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'list' object has no attribute 'setdefault'
Traceback (most recent call last):
  File "/usr/bin/salt-cloud", line 10, in <module>
    salt_cloud()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 421, in salt_cloud
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 92, in run
    mapper = salt.cloud.Map(self.config)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1577, in __init__
    self.rendered_map = self.read()
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1735, in read
    overrides.setdefault('name', name)
AttributeError: 'list' object has no attribute 'setdefault'
Traceback (most recent call last):
  File "/usr/bin/salt-cloud", line 10, in <module>
    salt_cloud()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 421, in salt_cloud
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 92, in run
    mapper = salt.cloud.Map(self.config)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1577, in __init__
    self.rendered_map = self.read()
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1735, in read
    overrides.setdefault('name', name)
AttributeError: 'list' object has no attribute 'setdefault'
```

**Comment by HeathNaylor** [comment]
Turns out this was occurring due to experimentation inside of my cloud.maps.d `my-environment.map` file. Removed bad format and all is fine.
