### ISSUE TITLE
"NameError: global name 'zmq' is not defined" for minion in version 2015.8.3 on CentOS 6.7

### ISSUE THREAD

**Issue by drawsmcgraw** [saltstack/salt#30773]
I'm using the CentOS 6.7 images in Digital Ocean to create a test master and minions. The master starts up fine, but when starting the minion (on a separate machine), I get this in the logs:

```
 File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 81, in minion_process
    minion.start()
  File "/usr/lib/python2.6/site-packages/salt/cli/daemons.py", line 274, in start
    self.prepare()
  File "/usr/lib/python2.6/site-packages/salt/cli/daemons.py", line 256, in prepare
    self.minion = salt.minion.Minion(self.config)
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 684, in __init__
    self.io_loop = io_loop or zmq.eventloop.ioloop.ZMQIOLoop()
NameError: global name 'zmq' is not defined
```

And the minion dies.

I installed zeromq as part of my normal bootstrapping process (a script that configures yum to use Saltstack's repo and `yum install salt-minion`), and Yum tells me it is, indeed, installed.

```
# yum list zeromq
Installed Packages
zeromq.i686                      4.0.5-4.el6                       @saltstack-repo
```

But Salt, for some reason, cannot find it:

```
# salt-call --versions-report
Salt Version:
           Salt: 2015.8.3
 
Dependency Versions:
         Jinja2: unknown
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: Not Installed
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: Not Installed
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32-573.8.1.el6.x86_64
         system: CentOS 6.7 Final
```

Interesting to note that the Master does not suffer this problem. Here's the version report on the Master:

```
# salt --versions-report
Salt Version:
           Salt: 2015.8.3
 
Dependency Versions:
         Jinja2: unknown
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
         Python: 2.6.6 (r266:84292, Jul 23 2015, 14:41:34)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: centos 6.7 Final
        machine: i686
        release: 2.6.32-573.8.1.el6.i686
         system: CentOS 6.7 Final
```

I turned the `log_level` up to `trace` but not a whole lot came from that:

```
2016-02-01 07:54:21,005 [salt.cli.daemons ][INFO    ][1712] Setting up the Salt Minion "minion-01"
2016-02-01 07:54:21,144 [salt.cli.daemons                         ][INFO    ][1712] The salt minion is shut down
2016-02-01 07:54:21,146 [salt.cli.daemons                         ][INFO    ][1718] The salt minion is shut down
2016-02-01 07:54:21,149 [salt.utils.process                       ][DEBUG   ][1719] Created pidfile: /var/run/salt-minion.pid
2016-02-01 07:54:21,150 [salt.cli.daemons                         ][INFO    ][1719] The salt minion is shut down
2016-02-01 07:54:21,150 [salt.scripts                             ][ERROR   ][1719] Minion failed to start: 
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 81, in minion_process
    minion.start()
  File "/usr/lib/python2.6/site-packages/salt/cli/daemons.py", line 274, in start
    self.prepare()
  File "/usr/lib/python2.6/site-packages/salt/cli/daemons.py", line 256, in prepare
    self.minion = salt.minion.Minion(self.config)
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 684, in __init__
    self.io_loop = io_loop or zmq.eventloop.ioloop.ZMQIOLoop()
NameError: global name 'zmq' is not defined
2016-02-01 07:54:21,152 [salt.scripts                             ][WARNING ][1719] ** Restarting minion **
2016-02-01 07:54:21,153 [salt.scripts                             ][INFO    ][1719] Sleeping random_reauth_delay of 8 seconds

```

And there's no action after the "random_reauth delay", even after the amount of time specified.

Any insight?

**Comment by jfindlay** [comment]
@drawsmcgraw, you also need PyZMQ installed as well.

**Comment by drawsmcgraw** [comment]
Thanks @jfindlay.

I understand that I need PyZMQ. However, that should have been pulled in as a dependency when I ran `yum install salt-minion`, as it was for salt-master. Maybe that's the root of the problem - that zeromq was not installed as a dependency of salt-minion?

**Comment by jfindlay** [comment]
@drawsmcgraw, thanks for the extra info.  I am unsure what is going on here since the [spec file](https://github.com/saltstack/salt-pack/blob/master/file_roots/pkg/salt/2015_8_3/rhel6/spec/salt.spec#L106) has the salt package, which is a dep for both salt-master and salt-minion, depending on PyZMQ.

**Comment by drawsmcgraw** [comment]
So here's interesting @jfindlay. I was confirming that the package `zeromq` was installed. You're telling me that I need `python-zmq`.  

I have this packaged installed as well, it turns out :/

I'm running out of tricks, I'm afraid.

```
# yum list python-zmq
Installed Packages
python-zmq.i686                   14.5.0-2.el6                   @saltstack-repo
```

**Comment by jfindlay** [comment]
@drawsmcgraw, what happens when you try `python -c 'import zmq ; print(zmq.__version__)'` on the minion?

**Comment by drawsmcgraw** [comment]
@jfindlay I see the mouth of the beast is what I see...

```
# python -c 'import zmq ; print(zmq.__version__)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/zmq/__init__.py", line 49, in <module>
    from zmq import backend
  File "/usr/lib/python2.6/site-packages/zmq/backend/__init__.py", line 41, in <module>
    reraise(*exc_info)
  File "/usr/lib/python2.6/site-packages/zmq/backend/__init__.py", line 29, in <module>
    _ns = select_backend(first)
  File "/usr/lib/python2.6/site-packages/zmq/backend/select.py", line 27, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/usr/lib/python2.6/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: /usr/lib/python2.6/site-packages/zmq/backend/cython/constants.so: wrong ELF class: ELFCLASS32
```

I'm beginning to think that this could be user error.....

**Comment by jfindlay** [comment]
That does look like a PyZMQ mismatch of some kind.  The easiest thing might be to try with a new VM.

**Comment by tbaker57** [comment]
@drawsmcgraw  - your salt master is 32-bit and minion is 64-bit, right ? Looks like your 64-bit minion only has the 32-bit version of zeromq. On a 64-bit machine you should see something like
```
[root@ip-172-31-30-140 ~]# yum list zeromq
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.mirror.serversaustralia.com.au
 * epel: fedora.uberglobalmirror.com
 * extras: centos.mirror.crucial.com.au
 * updates: centos.mirror.serversaustralia.com.au
Installed Packages
zeromq.x86_64         4.0.5-4.el6                 @saltstack-repo
```

**Comment by drawsmcgraw** [comment]
Thank you @tbaker57. My intention is for both to be 64-bit installations. I'm not sure why my minion installed the 32-bit version of zeromq. Do you know what would cause that? All I did on it was a `yum install salt-minion`.

I'll check my master as soon as I can get back to it.

**Comment by tbaker57** [comment]
@drawsmcgraw - I don't know why you've picked up the 32-bit version. Check your /etc/yum.repos.d/saltstack.repo definition of 'baseurl' to make sure you are picking up the correct architecture when you do a 'yum install'.

cheers,
Tim

**Comment by drawsmcgraw** [comment]
Thanks @tbaker57 and @jfindlay. I'm convinced this is user error. I'll try to chase down the problem but for now, I'll just close this issue.
