### ISSUE TITLE
[ERROR] 'provider'

### ISSUE THREAD

**Issue by HeathNaylor** [saltstack/salt#30785]
I was running 2015.5.9, I ran a `salt-cloud -m <my_env_file> -P`. Next I updated to 2015.8.3 and now when I run `salt-cloud -d` I get the following error.

```
[ERROR   ] 'provider'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 169, in parse_args
    process_option_func()
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 451, in process_config_dir
    self.config.update(self.setup_config())
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 2638, in setup_config
    return config.cloud_config(self.get_config_file_path())
  File "/usr/lib/python2.7/dist-packages/salt/config.py", line 1899, in cloud_config
    providers_config)
  File "/usr/lib/python2.7/dist-packages/salt/config.py", line 2058, in vm_profiles_config
    return apply_vm_profiles_config(providers, overrides, defaults)
  File "/usr/lib/python2.7/dist-packages/salt/config.py", line 2085, in apply_vm_profiles_config
    if ':' in details['provider']:
KeyError: 'provider'
```

**Comment by rallytime** [comment]
@HeathNaylor Can you please post your relevant profile and provider files with any sensitive data removed? That will help track down this error. Also, what cloud provider are you trying to remove VMs from with `salt-cloud -d`? Are you trying to delete the whole map or a single VM?

**Comment by HeathNaylor** [comment]
This was a bad configuration of RDS. Still trying to get that all figured out.

**Comment by rallytime** [comment]
@HeathNaylor Ok sounds good. Let us know if you still have troubles.

**Comment by HeathNaylor** [comment]
@rallytime you can see the configuration that is causing this error documented in #30789 .
