### ISSUE TITLE
[2015.8.*][Ubuntu 12.04 LTS][dpkg.py] Invalid "${binary:Package}" field in dpkg-query

### ISSUE THREAD

**Issue by gpenin** [saltstack/salt#30814]
Running "salt-call pkg.info_installed" on Ubuntu 12.04 LTS returns the following error :
```
KeyError: 'package'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 335, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 53, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 133, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 196, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/aptpkg.py", line 2245, in info_installed
    for pkg_name, pkg_nfo in __salt__['lowpkg.info'](*names).items():
  File "/usr/lib/python2.7/dist-packages/salt/modules/dpkg.py", line 383, in info
    for pkg_ext_k, pkg_ext_v in dselect_pkg_avail.get(pkg['package'], {}).items():
```
Indeed, dpkg-query command uses ${binary:Package} field, that returns an empty value on this Operating System version :
```
dpkg-query -W -f='package:${binary:Package}\n' openssh-server
package:
```
The valid field for this Operating System version seems to be ${Package} :
```
dpkg-query -W -f='package:${Package}\n' openssh-server
package:openssh-server
```

**Comment by jfindlay** [comment]
@gpenin, thanks for reporting.  This should now be fixed.
