### ISSUE TITLE
lxc runner returns UnboundLocalError: local variable 'saved_kwargs' referenced before assignment

### ISSUE THREAD

**Issue by mchugh19** [saltstack/salt#30864]
Just started testing the lxc runner. On invocation I get:

```
# salt-run lxc.init lxc1 host=test1 profile=ubuntu memory=256
Exception occurred in runner lxc.init: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 337, in low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/runners/lxc.py", line 324, in init
    kw.update(saved_kwargs)
UnboundLocalError: local variable 'saved_kwargs' referenced before assignment
```

```
# salt 'test1' pillar.items                                  
test1:
    ----------
    lxc.nic:
        ----------
        default:
            ----------
            eth0:
                ----------
                link:
                    lxcbr0
                type:
                    veth
    lxc.profile:
        ----------
        ubuntu:
            ----------
            backing:
                lvm
            size:
                1G
            template:
                ubuntu
            vgname:
                lxc
```

**Comment by jfindlay** [comment]
@mchugh19, thanks for reporting.  What version of salt are you using?

**Comment by mchugh19** [comment]
Whoops! Sorry about that. Here you are:
```
# salt-minion --version
salt-minion 2015.8.3 (Beryllium)                                                                                                                                                                                    
# salt-master --version                                                                                                                                                               
salt-master 2015.8.3 (Beryllium)                                                                                                                                                                                    
```

**Comment by rstarkey** [comment]
I'm seeing the same issue with 2015.8.8+ds-2.

**Comment by aleufroy** [comment]
Hi, 
At first glance, `saved_kwargs` seems useless and simply buggy ( [line 324](https://github.com/saltstack/salt/blob/develop/salt/runners/lxc.py#L324)). The sole occurence is its initialization inside the `if saltcloud_mode:` bloc ([line 315](https://github.com/saltstack/salt/blob/develop/salt/runners/lxc.py#L315)).

It seems that the code tries to augment parameters with results from 'lxc.cloud_init_interface'. Maybe the following patch is a proper fix:

```.diff
 @@ -312,16 +312,16 @@ def init(names, host=None, saltcloud_mod
         if saltcloud_mode:
             kw = copy.deepcopy(kw)
             kw['name'] = name
-            saved_kwargs = {}
+            saved_kwargs = kw
             kw = client.cmd(
                 host, 'lxc.cloud_init_interface', args + [kw],
                 expr_form='list', timeout=600).get(host, {})
+            kw.update(saved_kwargs)
         name = kw.pop('name', name)
         # be sure not to seed an already seeded host
         kw['seed'] = seeds.get(name, seed_arg)
         if not kw['seed']:
             kw.pop('seed_cmd', '')
-        kw.update(saved_kwargs)
         cmds.append(
             (host,
              name,
```

But I do not know much about salt.
