### ISSUE TITLE
salt-ssh fails on import msgpack - 2015.8

### ISSUE THREAD

**Issue by anlutro** [saltstack/salt#30887]
It seems like msgpack has been changed from an optional to a required dependency in a recent 2015.8 commit. Output from running salt-ssh against a brand new Debian 8 VM:

```
    stderr:
        [CRITICAL] Unable to import msgpack or msgpack_pure python modules
        [ERROR   ] An un-handled exception was caught by salt's global exception handler:
        ImportError: No module named msgpack
        Traceback (most recent call last):
          File "/tmp/.vagrant_6a32f1_salt/salt-call", line 4, in <module>
            salt_call()
          File "/tmp/.vagrant_6a32f1_salt/salt/scripts.py", line 329, in salt_call
            import salt.cli.call
          File "/tmp/.vagrant_6a32f1_salt/salt/cli/call.py", line 6, in <module>
            from salt.utils import parsers
          File "/tmp/.vagrant_6a32f1_salt/salt/utils/parsers.py", line 26, in <module>
            import salt.config as config
          File "/tmp/.vagrant_6a32f1_salt/salt/config.py", line 40, in <module>
            import salt.utils.sdb
          File "/tmp/.vagrant_6a32f1_salt/salt/utils/sdb.py", line 9, in <module>
            import salt.loader
          File "/tmp/.vagrant_6a32f1_salt/salt/loader.py", line 30, in <module>
            import salt.utils.event
          File "/tmp/.vagrant_6a32f1_salt/salt/utils/event.py", line 85, in <module>
            import salt.utils.cache
          File "/tmp/.vagrant_6a32f1_salt/salt/utils/cache.py", line 8, in <module>
            import msgpack
        ImportError: No module named msgpack
        Traceback (most recent call last):
          File "/tmp/.vagrant_6a32f1_salt/salt-call", line 4, in <module>
            salt_call()
          File "/tmp/.vagrant_6a32f1_salt/salt/scripts.py", line 329, in salt_call
            import salt.cli.call
          File "/tmp/.vagrant_6a32f1_salt/salt/cli/call.py", line 6, in <module>
            from salt.utils import parsers
          File "/tmp/.vagrant_6a32f1_salt/salt/utils/parsers.py", line 26, in <module>
            import salt.config as config
          File "/tmp/.vagrant_6a32f1_salt/salt/config.py", line 40, in <module>
            import salt.utils.sdb
          File "/tmp/.vagrant_6a32f1_salt/salt/utils/sdb.py", line 9, in <module>
            import salt.loader
          File "/tmp/.vagrant_6a32f1_salt/salt/loader.py", line 30, in <module>
            import salt.utils.event
          File "/tmp/.vagrant_6a32f1_salt/salt/utils/event.py", line 85, in <module>
            import salt.utils.cache
          File "/tmp/.vagrant_6a32f1_salt/salt/utils/cache.py", line 8, in <module>
            import msgpack
        ImportError: No module named msgpack
```

**Comment by anlutro** [comment]
This is probably the offending commit: https://github.com/saltstack/salt/commit/02d8ff626a4cd5410d936688852d2e6f6b95cb6c

**Comment by anlutro** [comment]
I guess I can confirm this as fixed :)
