### ISSUE TITLE
Starting a glusterfs volume after creation fails with an exception in 2015.8 and after.

### ISSUE THREAD

**Issue by youngnick** [saltstack/salt#30923]
Looks like when the module got changed to use the _gluster_xml function, the start command was missed; using create now with start: True will raise an exception.

From a debug run on the minion involved:
```
[INFO    ] Executing command 'gluster --xml --mode=script' in directory '/root'
[ERROR   ] Command 'gluster --xml --mode=script' failed with return code: 1
[ERROR   ] output: unrecognized word: gluster (position 0)
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1624, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1491, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/states/glusterfs.py", line 156, in created
    transport, start, force)
  File "/usr/lib/python2.7/dist-packages/salt/modules/glusterfs.py", line 247, in create
    _gluster_xml('gluster volume start {0}'.format(name))
  File "/usr/lib/python2.7/dist-packages/salt/modules/glusterfs.py", line 64, in _gluster_xml
    ).replace("\n", ""))
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 0
```

I have a PR for this, it's a trivial change.

**Comment by jfindlay** [comment]
@youngnick, thanks for fixing this.
