### ISSUE TITLE
Glusterfs peered fails on secondary host in 2015.8.4

### ISSUE THREAD

**Issue by johje349** [saltstack/salt#30932]
When running glusterfs.peered on secondary gluster host, or when having local ip address in names:
```python-traceback
2016-02-05 10:07:01,763 [salt.state       ][INFO    ][25335] Running state [10.129.2.33] at time 10:07:01.762913
2016-02-05 10:07:01,763 [salt.state       ][INFO    ][25335] Executing state glusterfs.peered for 10.129.2.33 <-- This is the primary glusterfs host
2016-02-05 10:07:01,764 [salt.loaded.int.module.cmdmod][INFO    ][25335] Executing command 'gluster --xml --mode=script' in directory '/root'
2016-02-05 10:07:01,871 [salt.loaded.int.module.cmdmod][INFO    ][25335] Executing command 'gluster --xml --mode=script' in directory '/root'
2016-02-05 10:07:01,964 [salt.loaded.int.module.cmdmod][INFO    ][25335] Executing command 'gluster --xml --mode=script' in directory '/root'
2016-02-05 10:07:02,057 [salt.state       ][ERROR   ][25335] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1624, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1491, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/states/glusterfs.py", line 83, in peered
    elif 'on localhost not needed' in ret['comment']:
TypeError: argument of type 'bool' is not iterable
```

**Comment by jfindlay** [comment]
@johje349, thanks for the report.

**Comment by joejulian** [comment]
I'll take a look at this.

**Comment by joejulian** [comment]
gluster got smarter about figuring out it's own hostname. If you establish a trusted pool from server1 (10.0.0.1) to server2 (10.0.0.2) with:

```
gluster1# gluster peer probe 10.0.0.2
```

then, from gluster2 you can check that

```
gluster2# gluster peer status
Number of Peers: 1

Hostname: server1
Uuid: 01233ca7-022d-4154-8846-cbc096f22e9c
State: Peer in Cluster (Connected)
```

So, obviously, 10.0.0.1 isn't going to match it. Gluster's also added the ability to know aliases for that hostname which might also need to be checked. The existing logic in the peered state is completely inadequate for gluster 3.7+.

I'll come back to this tomorrow.

**Comment by joejulian** [comment]
@johje349 Can you verify this fixes it for you, too?
