### ISSUE TITLE
develop is currently broken smartos

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#30968]
```
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "__main__.py", line 128, in <module>
  File "__main__salt-call__.py", line 14, in <module>
  File "salt/scripts.py", line 327, in salt_call
    import salt.cli.call
  File "salt/cli/call.py", line 6, in <module>
    from salt.utils import parsers
  File "salt/utils/parsers.py", line 29, in <module>
    import salt.config as config
  File "salt/config/__init__.py", line 37, in <module>
    import salt.syspaths
  File "salt/syspaths.py", line 97, in <module>
    BASE_THORIUM_ROOTS_DIR = __generated_syspaths.BASE_THORIUM_ROOTS_DIR
AttributeError: 'module' object has no attribute 'BASE_THORIUM_ROOTS_DIR'
```
Current develop branch does not work, above is the output of salt-call --local test.ping

**Comment by sjorge** [comment]
Seems like it is a0f2cdf317b7723ef98e0bf44bc94e2ddc8eebfc that broke it

It's probably just the smartos package (and possibly other frozen apps)
