### ISSUE TITLE
Running without a setting for salt_event_pub_hwm in master config results in 'unhandled-exception'

### ISSUE THREAD

**Issue by rterbush** [saltstack/salt#30977]
Upgraded from v2015.8.3 to v2015.8.5 (and v2015.8.4) and get the following error when attempting to run any salt command on the master.

Adding this parameter into master config moves me to next error of 'KeyError: 'event_match_type'

Running on Amazon Linux which means I am using Python 2.6

```
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
KeyError: 'salt_event_pub_hwm'
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.6/dist-packages/salt/scripts.py", line 458, in salt_main
    client.run()
  File "/usr/lib/python2.6/dist-packages/salt/cli/salt.py", line 48, in run
    skip_perm_errors=skip_perm_errors)
  File "/usr/lib/python2.6/dist-packages/salt/client/__init__.py", line 96, in get_local_client
    return LocalClient(mopts=opts, skip_perm_errors=skip_perm_errors)
  File "/usr/lib/python2.6/dist-packages/salt/client/__init__.py", line 142, in __init__
    listen=False)
  File "/usr/lib/python2.6/dist-packages/salt/utils/event.py", line 127, in get_event
    return MasterEvent(sock_dir, opts, listen=listen)
  File "/usr/lib/python2.6/dist-packages/salt/utils/event.py", line 692, in __init__
    super(MasterEvent, self).__init__('master', sock_dir, opts, listen=listen)
  File "/usr/lib/python2.6/dist-packages/salt/utils/event.py", line 203, in __init__
    self.connect_pub()
  File "/usr/lib/python2.6/dist-packages/salt/utils/event.py", line 312, in connect_pub
    self.sub.setsockopt(zmq.SNDHWM, self.opts['salt_event_pub_hwm'])
KeyError: 'salt_event_pub_hwm'
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.6/dist-packages/salt/scripts.py", line 458, in salt_main
    client.run()
  File "/usr/lib/python2.6/dist-packages/salt/cli/salt.py", line 48, in run
    skip_perm_errors=skip_perm_errors)
  File "/usr/lib/python2.6/dist-packages/salt/client/__init__.py", line 96, in get_local_client
    return LocalClient(mopts=opts, skip_perm_errors=skip_perm_errors)
  File "/usr/lib/python2.6/dist-packages/salt/client/__init__.py", line 142, in __init__
    listen=False)
  File "/usr/lib/python2.6/dist-packages/salt/utils/event.py", line 127, in get_event
    return MasterEvent(sock_dir, opts, listen=listen)
  File "/usr/lib/python2.6/dist-packages/salt/utils/event.py", line 692, in __init__
    super(MasterEvent, self).__init__('master', sock_dir, opts, listen=listen)
  File "/usr/lib/python2.6/dist-packages/salt/utils/event.py", line 203, in __init__
    self.connect_pub()
  File "/usr/lib/python2.6/dist-packages/salt/utils/event.py", line 312, in connect_pub
    self.sub.setsockopt(zmq.SNDHWM, self.opts['salt_event_pub_hwm'])
KeyError: 'salt_event_pub_hwm'
```

**Comment by rterbush** [comment]
It was necessary to add configuration parameters for the following items before the server would communicate successfully with the configured minions:

```
salt_event_pub_hwm: 128000
event_publisher_pub_hwm: 64000
event_match_type: startswith
```

No idea if these are reasonable values yet. I would expect there to be some rational default.

**Comment by rterbush** [comment]
Unfortunately, when trying to provision minions with the above attempt at a workaround still fails.

Reverting back to 2015.8.3 fixes the problem.

**Comment by jfindlay** [comment]
@rterbush, thanks for the report.  I instantiated an amazon linux VM on EC2 and bootstrapped 2015.5.3 and then upgraded to 2015.5.6 and was unable to reproduce the problems you're seeing: `salt-minion -l debug` runs as expected.  Is there anything else I should look at?

**Comment by rterbush** [comment]
@jfindlay I'm running 2015.8.3 on that server and attempted to upgrade to 2015.8.5 (and 2015.8.4). As mentioned above, downgrading to 2015.8.3 restored it to working state.

**Comment by rterbush** [comment]
Just to make this a proper report, version info included below for working. Upgrade to 2015.8.4 or 2015.8.5 is unusable.

```
[root@salt-master centos]# salt --versions-report
Salt Version:
           Salt: 2015.8.3

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.4
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.4.5.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
```

**Comment by rterbush** [comment]
This is quite possibly a python2.6 issue. I've upgraded to a Centos machine running python2.7 and the problem has disappeared. Happily running 2015.8.5 right now.
