### ISSUE TITLE
Targeting double digits Glob fails

### ISSUE THREAD

**Issue by krisrmgua** [saltstack/salt#31046]
In salt training here in the salt building and ran into this issue on my training box:

```
[root@ip-172-31-15-180 ~]# salt '*' test.ping

    kris10_test:

        True

    kris11_test:

       True

    kris9_test:

        True

    saltmaster:

        True

    kris8_test:

        True

[root@ip-172-31-15-180 ~]# salt 'kris[8-9]*' test.ping

    kris8_test:

        True

    kris9_test:

        True

[root@ip-172-31-15-180 ~]# salt 'kris[8-11]*' test.ping

     No minions matched the target. No command was sent, no jid was assigned.

     ERROR: No return received
```

When crossing double digits for targeting it fails.

salt 2015.8.5 (Beryllium)

**Comment by jfindlay** [comment]
@krisrmgua, thanks for reporting.  The glob target uses python's [glob](http://docs.python.org/library/glob.html) library, so this may be a bug in that upstream library.

**Comment by jfindlay** [comment]
```python
Python 2.7.10 (default, Nov 20 2015, 16:09:58)
[GCC 4.9.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import fnmatch
>>> fnmatch.fnmatch('kris8_test', 'kris[8-11]')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/fnmatch.py", line 43, in fnmatch
    return fnmatchcase(name, pat)
  File "/usr/lib64/python2.7/fnmatch.py", line 82, in fnmatchcase
    _cache[pat] = re_pat = re.compile(res)
  File "/usr/lib64/python2.7/re.py", line 194, in compile
    return _compile(pattern, flags)
  File "/usr/lib64/python2.7/re.py", line 251, in _compile
    raise error, v # invalid expression
sre_constants.error: bad character range
```

**Comment by yamins81** [comment]
Any further resolution here?
