### ISSUE TITLE
pyenv installation fails on ubuntu/trusty64

### ISSUE THREAD

**Issue by AndreasBackx** [saltstack/salt#31066]
The pyenv installation fails to create the directory /usr/local/pyenv and spits out the following error:

```
----------
          ID: python-2.7.11
    Function: pyenv.installed
        Name: 2.7.11
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1624, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1491, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/pyenv.py", line 129, in installed
                  if not __salt__['pyenv.install'](user):
                File "/usr/lib/python2.7/dist-packages/salt/modules/pyenv.py", line 113, in install
                  return _install_pyenv(path, runas)
                File "/usr/lib/python2.7/dist-packages/salt/modules/pyenv.py", line 81, in _install_pyenv
                  'git clone https://github.com/yyuu/pyenv.git {0}'.format(path), runas=runas)
                File "/usr/lib/python2.7/dist-packages/salt/modules/cmdmod.py", line 1752, in retcode
                  use_vt=use_vt)
                File "/usr/lib/python2.7/dist-packages/salt/modules/cmdmod.py", line 437, in _run
                  .format(cmd, kwargs, exc)
              CommandExecutionError: Unable to run command ['git', 'clone', 'https://github.com/yyuu/pyenv.git', '/usr/local/pyenv'] with the context {'with_communicate': True, 'shell': False, 'env': {'SSH_CLIENT': '10.0.2.2 57751 22', 'LOGNAME': 'root', 'USER': 'root', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'HOME': '/root', 'UCF_FORCE_CONFFOLD': '1', 'LANG': 'en_US.UTF-8', 'TERM': 'vt100', 'SHELL': '/bin/bash', 'SHLVL': '2', '_': '/usr/bin/salt-call', 'SUDO_USER': 'vagrant', 'USERNAME': 'root', 'XDG_RUNTIME_DIR': '/run/user/1000', 'DEBIAN_FRONTEND': 'noninteractive', 'SUDO_UID': '1000', 'LC_ALL': 'C', 'XDG_SESSION_ID': '2', 'APT_LISTCHANGES_FRONTEND': 'none', 'SUDO_COMMAND': '/bin/bash -l', 'SUDO_GID': '1000', 'PWD': '/home/vagrant', 'MAIL': '/var/mail/vagrant', 'SSH_CONNECTION': '10.0.2.2 57751 10.0.2.15 22', 'APT_LISTBUGS_FRONTEND': 'none'}, 'stdout': -1, 'close_fds': True, 'stdin': None, 'stderr': -2, 'cwd': '/root'}, reason: [Errno 2] No such file or directory
     Started: 23:43:45.250541
    Duration: 29.54 ms
     Changes:   
----------
```

This is the state:

```yaml
pyenv-dependencies:
  pkg.installed:
    - pkgs:
      - make
      - build-essential
      # Python ssl extension
      - 'libssl-dev'
      # Python zlib extension
      - 'zlib1g-dev'
      # Python bz2 extension
      - 'libbz2-dev'
      # Python readline extension
      - 'libreadline-dev'
      # Python sqlite3 extension
      - 'libsqlite3-dev'
      # Pillow jpeg
      - 'libjpeg-dev'
      - wget
      - curl
      - llvm

python-2.7.11:
  pyenv.installed:
    - name: '2.7.11'
    - default: True
    - require:
      - pkg: pyenv-dependencies
```

When adding everything that makes the folder we get the following state:

```yaml
pyenv-dependencies:
  pkg.installed:
    - pkgs:
      - make
      - build-essential
      # Python ssl extension
      - 'libssl-dev'
      # Python zlib extension
      - 'zlib1g-dev'
      # Python bz2 extension
      - 'libbz2-dev'
      # Python readline extension
      - 'libreadline-dev'
      # Python sqlite3 extension
      - 'libsqlite3-dev'
      # Pillow jpeg
      - 'libjpeg-dev'
      - wget
      - curl
      - llvm

/usr/local/pyenv:
  file.directory:
    - user: vagrant
    - group: vagrant
    - mode: 755
    - makedirs: True

python-2.7.11:
  pyenv.installed:
    - name: '2.7.11'
    - default: True
    - require:
      - pkg: pyenv-dependencies
```

But it still spits out the following error:

```
----------
          ID: python-2.7.11
    Function: pyenv.installed
        Name: 2.7.11
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1624, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1491, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/pyenv.py", line 133, in installed
                  return _check_and_install_python(ret, name, default, user=user)
                File "/usr/lib/python2.7/dist-packages/salt/states/pyenv.py", line 84, in _check_and_install_python
                  if __salt__['pyenv.install_python'](python, runas=user):
                File "/usr/lib/python2.7/dist-packages/salt/modules/pyenv.py", line 175, in install_python
                  if ret['retcode'] == 0:
              TypeError: 'bool' object has no attribute '__getitem__'
     Started: 23:44:47.114810
    Duration: 1.651 ms
     Changes:   
----------
```

**Comment by jfindlay** [comment]
@AndreasBackx, thanks for reporting.
