### ISSUE TITLE
Problem Windows XP - ZMQError

### ISSUE THREAD

**Issue by jacky35** [saltstack/salt#31156]
Hello,
I do not know if you are successful or not , but from my side I never got Windows XP operating correctly SALT.

I think there is a problem with Windows XP and ZMQ

Have you found a way to make it work properly ?

Many thanks, 
Jacky

Version: Salt-Minion-2015.8.5-x86-Setup.exe
OS: Microsoft Windows XP Professionnel (5.1.2600 Service Pack 3 Version 2600)

Here Debug:
```
--------------------------
Microsoft Windows XP [version 5.1.2600]
(C) Copyright 1985-2001 Microsoft Corp.

C:\Documents and Settings\Utilisateur>C:\salt\salt-minion-debug.bat
Le service salt-minion n'est pas lancé.

Vous obtiendrez une aide supplémentaire en entrant NET HELPMSG 3521.

[DEBUG   ] Reading configuration from c:\salt\conf\minion
[ERROR   ] Error parsing configuration file: c:\salt\conf\minion - while scannin
g a simple key
  in "<string>", line 315, column 1:
    log_level_logfile:debug.log
    ^
could not found expected ':'
  in "<string>", line 316, column 1:
    #
    ^
[DEBUG   ] Using cached minion ID from c:\salt\conf\minion_id: Appli-Granulo-3PJ
FB4J
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged
.
[INFO    ] Setting up the Salt Minion "Appli-Granulo-3PJFB4J"
[DEBUG   ] Created pidfile: c:\salt\var\run\salt-minion.pid
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[ERROR   ] Error parsing configuration file: c:\salt\conf\minion - while scannin
g a simple key
  in "<string>", line 315, column 1:
    log_level_logfile:debug.log
    ^
could not found expected ':'
  in "<string>", line 316, column 1:
    #
    ^
[INFO    ] The salt minion is starting up
[INFO    ] Minion is starting as user 'Utilisateur'
Assertion failed: Socket operation on non-socket (bundled\zeromq\src\select.cpp:
185)
[INFO    ] The salt minion is shut down
[ERROR   ] An un-handled exception was caught by salt's global exception handler
:
ZMQError: Connection refused
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-minion", line 26, in <module>
    salt_minion()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 117, in salt_minion

    minion.start()
  File "C:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 277, in start
    self.minion.tune_in()
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 1680, in tune_in
    io_loop=self.io_loop,
  File "C:\salt\bin\lib\site-packages\salt\utils\event.py", line 762, in __init_
_
    self.epub_sock = self.context.socket(zmq.PUB)
  File "C:\salt\bin\lib\site-packages\zmq\sugar\context.py", line 143, in socket

    s = self._socket_class(self, socket_type)
  File "zmq/backend/cython/socket.pyx", line 281, in zmq.backend.cython.socket.S
ocket.__cinit__ (zmq\backend\cython\socket.c:3220)
ZMQError: Connection refused
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-minion", line 26, in <module>
    salt_minion()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 117, in salt_minion

    minion.start()
  File "C:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 277, in start
    self.minion.tune_in()
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 1680, in tune_in
    io_loop=self.io_loop,
  File "C:\salt\bin\lib\site-packages\salt\utils\event.py", line 762, in __init_
_
    self.epub_sock = self.context.socket(zmq.PUB)
  File "C:\salt\bin\lib\site-packages\zmq\sugar\context.py", line 143, in socket

    s = self._socket_class(self, socket_type)
  File "zmq/backend/cython/socket.pyx", line 281, in zmq.backend.cython.socket.S
ocket.__cinit__ (zmq\backend\cython\socket.c:3220)
zmq.error.ZMQError: Connection refused
Assertion failed: Socket operation on non-socket (bundled\zeromq\src\signaler.cp
p:181)

C:\Documents and Settings\Utilisateur>
```

**Comment by ssgward** [comment]
@jacky35 - thanks for sending this in. This is a tough one as we don't support XP and hence don't spend any dev or testing time on this OS. You could try to manually update the ZMQ package to a 4.x version (if one does exist for Windows) or reach out to the community to see if anyone else has been successful in working around your same issue.
