### ISSUE TITLE
salt-cloud won't auto-create Cloud Service for Azure VMs

### ISSUE THREAD

**Issue by jvestrum** [saltstack/salt#31178]
When I attempt to deploy an Azure VM, salt-cloud claims that the "Cloud service already exists" even though it doesn't; this in turn causes the VM deploy to fail.

```
# salt-cloud -l debug -p azure-centos7 vm003
...
[DEBUG   ] LazyLoaded rackspace.list_locations
[DEBUG   ] Failed to execute 'azure.list_nodes()' while querying for running nodes: 'name'
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 2335, in run_parallel_map_providers_query
    cloud.clouds[data['fun']]()
  File "/usr/lib64/python2.6/contextlib.py", line 34, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.6/site-packages/salt/utils/context.py", line 42, in func_globals_inject
    yield
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 2335, in run_parallel_map_providers_query
    cloud.clouds[data['fun']]()
  File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/msazure.py", line 226, in list_nodes
    ret[node][prop] = nodes[node][prop]
KeyError: 'name'
[DEBUG   ] Generating minion keys for 'vm003'
[DEBUG   ] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event - data = {'profile': 'azure-centos7', 'event': 'starting create', '_stamp': '2016-02-12T19:15:38.244721', 'name': 'vm003', 'provider': 'azure-trial:azure'}
[INFO    ] Creating Cloud VM vm003
[DEBUG   ] vm_kwargs: {'system_config': <azure.servicemanagement.models.LinuxConfigurationSet object at 0x250c210>, 'deployment_slot': 'production', 'role_size': 'Small', 'deployment_name': 'vm004', 'service_name': 'vm004', 'role_name': 'vm003', 'network_config': <azure.servicemanagement.models.ConfigurationSet object at 0x250c110>, 'os_virtual_hard_disk': <azure.servicemanagement.models.OSVirtualHardDisk object at 0x250c310>, 'label': 'vm003'}
[DEBUG   ] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event - data = {'_stamp': '2016-02-12T19:15:38.302752', 'service_kwargs': {'service_name': 'vm004', 'label': 'vm003', 'location': 'Central US', 'description': 'vm003'}, 'event': 'requesting instance', 'vm_kwargs': {'deployment_slot': 'production', 'role_size': 'Small', 'deployment_name': 'vm004', 'service_name': 'vm004', 'label': 'vm003', 'role_name': 'vm003'}}
[DEBUG   ] vm_kwargs: {'system_config': <azure.servicemanagement.models.LinuxConfigurationSet object at 0x250c210>, 'deployment_slot': 'production', 'role_size': 'Small', 'deployment_name': 'vm004', 'service_name': 'vm004', 'role_name': 'vm003', 'network_config': <azure.servicemanagement.models.ConfigurationSet object at 0x250c110>, 'os_virtual_hard_disk': <azure.servicemanagement.models.OSVirtualHardDisk object at 0x250c310>, 'label': 'vm003'}
[DEBUG   ] Cloud service already exists
[ERROR   ] Error creating vm003 on Azure.

The Virtual Machine could not be created. If you are using an already existing Cloud Service, make sure you set up the `port` variable corresponding to the SSH port exists and that the port number is not already in use.
The following exception was thrown when trying to run the initial deployment:
Not Found
```
Full output at https://gist.github.com/jvestrum/7d95ffa8540b5b3319a0.

When I manually create a Cloud Service through the Azure portal and set a service_name in the profile config, it works.

```
Salt Version:
           Salt: 2015.8.5
 
Dependency Versions:
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.5.0
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32-573.8.1.el6.x86_64
         system: CentOS 6.7 Final

**Comment by jfindlay** [comment]
Thanks for reporting, @jvestrum.

**Comment by jvestrum** [comment]
FYI, I've tried this with both the Azure Python SDK 0.11.1 as recommended, and with the latest Azure Python SDK, which requires the latest development salt/cloud/clouds/msazure.py. Same error either way.

**Comment by Ch3LL** [comment]
ping @jvestrum I just ran into this today and it ended up being a resources issue. I had to remove a bunch of old VMs and cloud services and it started working, although this was on 2016.3 branch. I still think this issue needs to be open to track to add a better error when seeing this error. I know its been a while but if you are still running into this issue can you see if removing resources resolves the issue? thanks

**Comment by jvestrum** [comment]
Ch3LL, sorry, my Azure trial ran out and I'm not going to start another one. I don't think it was a resources issue as it was a new account and I could create/remove Cloud Services and VMs manually without problems.

**Comment by Ch3LL** [comment]
thanks for getting back to me. Im curious if what you were running into then was specific to 2015.8.5 then. But in 2016.3.3 for me it was definitely a resources issue. It was creating the cloud service but not hte VM because there was not enough space to create the VM but the error was not very telling. Thanks

If you ever start using azure again please let us know if you run into this issue again. For this instance though i think we can add better error reporting when receiving that error on 2016.3 and up so i'll still keep this open.
