### ISSUE TITLE
pecl module doesn't handled __uri channel sources

### ISSUE THREAD

**Issue by jbouse** [saltstack/salt#31203]
I can't seem to find any way that the existing pecl state or module can handle installing from a URL source. In order for the existing pecl module to handle looking at the __uri channel you have to specify the name as "__uri/extensionname" but there is no way to specify the URL from which to actually install the extension from.

I'd suggest this might be a good situation to allow for a "source" attribute to be set along with any others. This could be made mutually exclusive with channel being "__uri". It is a perfectly valid call to execute 'pecl install scheme://example.com/extension_package' but specifying that as the 'name' attribute will cause a stack traceback.

     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1624, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1491, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/pecl.py", line 72, in installed
                  channel, package = name.split('/')
              ValueError: too many values to unpack

**Comment by jfindlay** [comment]
@jbouse, thanks for reporting.

**Comment by jbouse** [comment]
@jfindlay, you're welcome... My thought on adding a 'source' attribute rather than modify the handling of the 'name' attribute is in the case I was actually testing the URL name was different then the interpreted '__uri/exension' name to check via 'pecl list -c __uri' so made more sense to leave the name as the channel name to look for.

If I have time I'll try and see if I can't get a PR together for this. I'm already neck deep in about a half dozen other items on my TODO list here and this was an optional item that I ran into not a critical one at this point.

**Comment by jfindlay** [comment]
@jbouse, thanks for your attention to this issue.  Send in a pull request if/when you have time.
