### ISSUE TITLE
when the minions have all been destroyed...

### ISSUE THREAD

**Issue by gladiatr72** [saltstack/salt#31219]
This should not happen.  It doesn't happen when the static (`-s`) is left off

```bash
:# salt -s -C 'not ( I@cluster_id:000 ) and I@subcomponent:log' disco.ei bare=True first=True
No minions matched the target. No command was sent, no jid was assigned.
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
SaltClientError: No minions matched the target.
Traceback (most recent call last):
  File "/srv/.virtualenvs/salt/bin/salt", line 10, in <module>
    salt_main()
  File "/srv/.virtualenvs/salt/local/lib/python2.7/site-packages/salt/scripts.py", line 458, in salt_main
    client.run()
  File "/srv/.virtualenvs/salt/local/lib/python2.7/site-packages/salt/cli/salt.py", line 82, in run
    batch = salt.cli.batch.Batch(self.config, eauth=eauth, quiet=True)
  File "/srv/.virtualenvs/salt/local/lib/python2.7/site-packages/salt/cli/batch.py", line 34, in __init__
    self.minions, self.ping_gen = self.__gather_minions()
  File "/srv/.virtualenvs/salt/local/lib/python2.7/site-packages/salt/cli/batch.py", line 62, in __gather_minions
    raise salt.exceptions.SaltClientError('No minions matched the target.')
SaltClientError: No minions matched the target.
Traceback (most recent call last):
  File "/srv/.virtualenvs/salt/bin/salt", line 10, in <module>
    salt_main()
  File "/srv/.virtualenvs/salt/local/lib/python2.7/site-packages/salt/scripts.py", line 458, in salt_main
    client.run()
  File "/srv/.virtualenvs/salt/local/lib/python2.7/site-packages/salt/cli/salt.py", line 82, in run
    batch = salt.cli.batch.Batch(self.config, eauth=eauth, quiet=True)
  File "/srv/.virtualenvs/salt/local/lib/python2.7/site-packages/salt/cli/batch.py", line 34, in __init__
    self.minions, self.ping_gen = self.__gather_minions()
  File "/srv/.virtualenvs/salt/local/lib/python2.7/site-packages/salt/cli/batch.py", line 62, in __gather_minions
    raise salt.exceptions.SaltClientError('No minions matched the target.')
salt.exceptions.SaltClientError: No minions matched the target.
```

```bash
:# salt --versions
Salt Version:
           Salt: 2015.8.5

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.1.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.2
           cffi: 1.2.1
       cherrypy: 3.8.0
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: 1.4.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 2.0.2
          smmap: Not Installed
        timelib: 0.2.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-76-generic
         system: Ubuntu 14.04 trusty
```

**Comment by jfindlay** [comment]
@gladiatr72, thanks for reporting.
