### ISSUE TITLE
states.git.latest: exception with test=true and user not (yet) present

### ISSUE THREAD

**Issue by eliasp** [saltstack/salt#31212]
`git.latest` with `test=true` and the user specified is not yet present results in a ugly backtrace which could be handled more gracefully:

```
          ID: website-build-git-clone
    Function: git.latest
        Name: git@bitbucket.org:project/repository.git
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1624, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1491, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/git.py", line 469, in latest
                  ignore_retcode=False)
                File "/usr/lib/python2.7/site-packages/salt/modules/git.py", line 2744, in remote_refs
                  ignore_retcode=ignore_retcode)['stdout']
                File "/usr/lib/python2.7/site-packages/salt/modules/git.py", line 198, in _git_run
                  os.chown(tmp_file, __salt__['file.user_to_uid'](runas), -1)
              TypeError: an integer is required
     Started: 08:22:06.886373
    Duration: 11.03 ms
     Changes:
```

```
    Salt Version:
               Salt: 2015.8.5

    Dependency Versions:
             Jinja2: 2.7.2
           M2Crypto: 0.21.1
               Mako: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.7.0
             Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
            libgit2: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: Not Installed
            timelib: Not Installed

    System Versions:
               dist: centos 7.2.1511 Core
            machine: x86_64
            release: 3.10.0-229.14.1.el7.x86_64
             system: CentOS Linux 7.2.1511 Core
```

**Comment by jfindlay** [comment]
@eliasp, thanks for reporting.

**Comment by zhaopf1112** [comment]
I have the same problem
