### ISSUE TITLE
dockerng.volume_present fails if no volume exists on minion

### ISSUE THREAD

**Issue by mkuchin** [saltstack/salt#31343]
Trying to execute state

```
jenkins-volume:
  dockerng.volume_present:
    - name: jenkins
```
on the minion with no volumes:
```
$ docker volume ls
DRIVER              VOLUME NAME
```
finishes with error:
```
----------
          ID: jenkins-volume
    Function: dockerng.volume_present
        Name: jenkins
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1682, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1583, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/dockerng.py", line 2153, in volume_present
                  volumes = [v for v in __salt__['dockerng.volumes']()['Volumes'] if v['Name'] == name]
              TypeError: 'NoneType' object is not iterable
     Started: 03:33:11.542971
    Duration: 4.582 ms
     Changes:   
----------
          ID: jenkins
    Function: dockerng.running
      Result: False
     Comment: One or more requisite failed: jenkins.jenkins-volume
     Started: 
    Duration: 
     Changes:
```

**Comment by jfindlay** [comment]
@mkuchin, thanks for working on this.
