### ISSUE TITLE
Failed to spawn the VT: StringIO instance has no attribute 'fileno'

### ISSUE THREAD

**Issue by DenisBY** [saltstack/salt#31350]
We have a heavily used for AWS autoscaling salt-master and after some time salt starts to throw in log exceptions like this:
```
2016-02-19 11:17:31,422 [salt.utils.vt    ][WARNING ][13154] Failed to spawn the VT: StringIO instance has no attribute 'fileno'
2016-02-19 11:17:31,424 [salt.utils.cloud ][ERROR   ][13154] Failed to upload file 'echo "put  /tmp/tmp5whEJv /tmp/.saltcloud-7372fd31-cdd0-43ef-86c5-1774fe47190a/minion.pub" | sftp -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oKbdInteractiveAuthentication=no -oIdentityFile=/etc/salt/keys/key.pem -oPort=22 ubuntu@10.11.12.13': Failed to spawn the VT. Error: StringIO instance has no attribute 'fileno'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 1715, in _exec_ssh_cmd
    stream_stderr=kwargs.get('display_ssh_output', True)
  File "/usr/lib/python2.7/dist-packages/salt/utils/vt.py", line 214, in __init__
    'Failed to spawn the VT. Error: {0}'.format(err)
TerminalException: Failed to spawn the VT. Error: StringIO instance has no attribute 'fileno'
```
```
2016-02-17 21:50:21,631 [salt.utils.vt    ][WARNING ][9460] Failed to spawn the VT: [Errno 5] Input/output error
2016-02-17 21:50:21,632 [salt.utils.cloud ][ERROR   ][9460] Failed to upload file 'echo "put  /tmp/tmpVDsRVh /tmp/.saltcloud-7ab2760f-2a59-453a-a936-2e867c3540a0/minion.pem" | sftp -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oKbdInteractiveAuthentication=no -oIdentityFile=/etc/salt/keys/key.pem -oPort=22 ubuntu@10.11.12.14': Failed to spawn the VT. Error: [Errno 5] Input/output error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 1710, in _exec_ssh_cmd
    stream_stderr=kwargs.get('display_ssh_output', True)
  File "/usr/lib/python2.7/dist-packages/salt/utils/vt.py", line 214, in __init__
    'Failed to spawn the VT. Error: {0}'.format(err)
TerminalException: Failed to spawn the VT. Error: [Errno 5] Input/output error
```
```
2016-02-19 23:40:09,056 [salt.utils.vt ][WARNING ][13875] Failed to spawn the VT: StringIO instance has no attribute 'fileno'
2016-02-19 23:40:09,057 [salt.utils.cloud ][ERROR ][13875] A wrong password has been issued while establishing ssh session
```

After salt-master restart everything goes back for a while but in some time it happens again.
It happens time to time and I don't see any consistent pattern of this issue.

```
# salt --versions
Salt Version:
           Salt: 2015.8.7
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: 0.9.1
         PyYAML: 3.11
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 2.4.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-74-generic
         system: Ubuntu 14.04 trusty
```

**Comment by jfindlay** [comment]
@DenisBY, thanks for reporting.  How are you initiating the salt-cloud action, with the cloud runner on the master, or the cloud execution or state module on a minion, or a cmd.run?

**Comment by DenisBY** [comment]
using reactor on master via api. we are using reactor from here: 
https://github.com/saltstack-formulas/ec2-autoscale-reactor

**Comment by DenisBY** [comment]
If it will help on 2015.8.3 we had these messages:
```
2016-02-18 00:22:53,344 [salt.utils.vt    ][WARNING ][3348] Failed to spawn the VT: [Errno 2] No such file or directory: '/dev/pts/44'
2016-02-18 00:22:53,345 [salt.utils.cloud ][ERROR   ][3348] A wrong password has been issued while establishing ssh session
2016-02-18 00:22:56,173 [salt.utils.vt    ][WARNING ][3362] Failed to spawn the VT: [Errno 5] Input/output error
2016-02-18 00:22:56,174 [salt.utils.cloud ][ERROR   ][3362] A wrong password has been issued while establishing ssh session
2016-02-18 00:22:57,483 [salt.utils.vt    ][WARNING ][3377] Failed to spawn the VT: [Errno 5] Input/output error
2016-02-18 00:22:57,484 [salt.utils.cloud ][ERROR   ][3377] A wrong password has been issued while establishing ssh session
2016-02-18 00:22:57,494 [salt.utils.vt    ][WARNING ][3378] Failed to spawn the VT: [Errno 5] Input/output error
2016-02-18 00:22:57,495 [salt.utils.cloud ][ERROR   ][3378] A wrong password has been issued while establishing ssh session
```

**Comment by DenisBY** [comment]
Some more debug:
```
2016-02-22 09:12:08,147 [salt.utils.cloud ][DEBUG   ][26186] SSH command: "ssh -t -t -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oKbdInteractiveAuthentication=no -i /etc/salt/keys/key.pem -p 22 ubuntu@10.165.9.213 sudo chown ubuntu '/tmp/.saltcloud-086668aa-3ef7-43e3-b0a5-19a92f27f2cb'"
2016-02-22 09:12:08,150 [salt.utils.vt    ][DEBUG   ][26186] Child Forked! PID: 30711  STDOUT_FD: 36  STDERR_FD: 39
2016-02-22 09:12:08,151 [salt.utils.vt    ][DEBUG   ][26186] Terminal Command: /bin/sh -c ssh -t -t -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oKbdInteractiveAuthentication=no -i /etc/salt/keys/key.pem -p 22 ubuntu@10.165.9.213 'sudo chown ubuntu '"'"'/tmp/.saltcloud-086668aa-3ef7-43e3-b0a5-19a92f27f2cb'"'"''
2016-02-22 09:12:08,153 [salt.utils.vt    ][WARNING ][30711] Failed to spawn the VT: StringIO instance has no attribute 'fileno'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/vt.py", line 205, in __init__
    self._spawn()
  File "/usr/lib/python2.7/dist-packages/salt/utils/vt.py", line 426, in _spawn
    self.stdout = sys.stdout.fileno()
AttributeError: StringIO instance has no attribute 'fileno'
2016-02-22 09:12:08,154 [salt.utils.cloud ][ERROR   ][30711] A wrong password has been issued while establishing ssh session
2016-02-22 09:12:08,157 [salt.utils.lazy  ][DEBUG   ][30711] LazyLoaded nested.output
2016-02-22 09:12:08,158 [salt.utils.event ][DEBUG   ][30711] Sending event - data = {'jid': '20160222091144217681', 'return': 'Exception occurred in runner cloud.create: Traceback (most recent call last):\n  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 336, in low\n    data[\'return\'] = self.functions[fun](*args, **kwargs)\n  File "/usr/lib/python2.7/dist-packages/salt/runners/cloud.py", line 165, in create\n    info = client.create(provider, instances, **create_kwargs)\n  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 411, in create\n    mapper.create(vm_))\n  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1263, in create\n    output = self.clouds[func](vm_)\n  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 2514, in create\n    for key, value in six.iteritems(salt.utils.cloud.bootstrap(vm_, __opts__)):\n  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 498, in bootstrap\n    deployed = deploy_script(**deploy_kwargs)\n  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 1233, in deploy_script\n    tty, sudo, **ssh_kwargs\n  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 2098, in root_cmd\n    retcode = _exec_ssh_cmd(cmd, allow_failure=allow_failure, **kwargs)\n  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 1754, in _exec_ssh_cmd\n    proc.close(terminate=True, kill=True)\nUnboundLocalError: local variable \'proc\' referenced before assignment\n', 'success': False, '_stamp': '2016-02-22T09:12:08.158187', 'user': 'Reactor', 'fun': 'runner.cloud.create'}
2016-02-22 09:12:08,159 [salt.utils.event ][DEBUG   ][30711] Interrupted system call
2016-02-22 09:12:08,160 [salt.utils.process][DEBUG   ][30711] Interrupted system call
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/process.py", line 201, in _thread_target
    func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 349, in low
    namespaced_event.fire_event(data, 'ret')
  File "/usr/lib/python2.7/dist-packages/salt/utils/event.py", line 716, in fire_event
    self.event.fire_event(data, tagify(tag, base=self.base))
  File "/usr/lib/python2.7/dist-packages/salt/utils/event.py", line 587, in fire_event
    self.push.send(salt.utils.to_bytes(event, 'utf-8'))
  File "socket.pyx", line 574, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:5390)
  File "socket.pyx", line 621, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:5157)
  File "socket.pyx", line 181, in zmq.backend.cython.socket._send_copy (zmq/backend/cython/socket.c:2110)
  File "checkrc.pxd", line 21, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:6103)
ZMQError: Interrupted system call
```

**Comment by DenisBY** [comment]
Maybe it could be related to this:
```
# ps ax | grep salt-master | grep -v grep | wc -l
151
```
but 
```
worker_threads: 20
```

At our dev environment with same config:
```
# ps ax | grep salt-master | grep -v grep | wc -l
29
```

**Comment by DenisBY** [comment]
We found a problem on our side. It was caused by code in our reactor which removes instances from our monitoring system on instance termination. We experienced one more problem "[salt.utils.vt    ][WARNING ][7129] Failed to spawn the VT: [Errno 5] Input/output error" but I'll fill another bug for this.
