### ISSUE TITLE
file.serialize bug: TypeError: manage_file() got an unexpected keyword argument 'show_diff'

### ISSUE THREAD

**Issue by aboe76** [saltstack/salt#31394]
I think I found a bug in the file.serialize state:

```
/tmp/test:
  file.serialize:
    - dataset_pillar: salt:minion
    - formatter: yaml
```

produces the following error:

```
[INFO    ] Determining pillar cache
[INFO    ] Determining pillar cache
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** done ** 'test/init.sls'
[INFO    ] Running state [/tmp/test] at time 20:18:44.922258
[INFO    ] Executing state file.serialize for /tmp/test
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 1701, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1619, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/states/file.py", line 4613, in serialize
    contents=contents)
TypeError: manage_file() got an unexpected keyword argument 'show_diff'

[INFO    ] Completed state [/tmp/test] at time 20:18:45.028819 duration_in_ms=106.561
local:
----------
          ID: /tmp/test
    Function: file.serialize
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1701, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1619, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/file.py", line 4613, in serialize
                  contents=contents)
              TypeError: manage_file() got an unexpected keyword argument 'show_diff'
     Started: 20:18:44.922258
    Duration: 106.561 ms
     Changes:   

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
```

Salt environment:

```
salt-call test.versions_report 
[INFO    ] Determining pillar cache
local:
    Salt Version:
               Salt: 2016.3.0-109-gcb2f252

    Dependency Versions:
             Jinja2: 2.8
           M2Crypto: 0.21.1
               Mako: 1.0.3
             PyYAML: 3.11
              PyZMQ: 15.2.0
             Python: 2.7.11 (default, Dec  6 2015, 15:43:46)
               RAET: 0.6.5
            Tornado: 4.3
                ZMQ: 4.1.3
               cffi: 1.5.2
           cherrypy: 4.0.0
           dateutil: 2.4.2
              gitdb: 0.6.4
          gitpython: 1.0.1
              ioflo: 1.5.0
            libgit2: 0.23.4
            libnacl: 1.4.4
       msgpack-pure: Not Installed
     msgpack-python: 0.4.7
       mysql-python: Not Installed
          pycparser: 2.14
           pycrypto: 2.6.1
             pygit2: 0.23.3
       python-gnupg: 0.3.7
              smmap: 0.9.0
            timelib: 0.2.4

    System Versions:
               dist:   
            machine: x86_64
            release: 4.4.1-2-ARCH
```

**Comment by aboe76** [comment]
Fix should be easy I think:

remove line 4612 in salt/states/file.py:
```
show_diff=show_diff,
```

from the return code:
```
return __salt__['file.manage_file'](name=name,
                                        sfn='',
                                        ret=ret,
                                        source=None,
                                        source_sum={},
                                        user=user,
                                        group=group,
                                        mode=mode,
                                        saltenv=__env__,
                                        backup=backup,
                                        makedirs=makedirs,
                                        template=None,
                                        show_diff=show_diff,
                                        contents=contents)
```

**Comment by aboe76** [comment]
I think file.serialize didn't get the show_changes stuff...

**Comment by jfindlay** [comment]
@aboe76, thanks for reporting.  Is it possible you may have incorrect .pyc files installed from another salt version?  I see that `modules.file.manage_file` accepts `show_diff` on both 2015.8 and 2016.3.

**Comment by aboe76** [comment]
@jfindlay, I don't know could be because I editted the file localy to debug it...

**Comment by s-schweer** [comment]
in 2016.3 it accepts show_changes not show_diffs
