### ISSUE TITLE
Bug -- Validated -- “'file.makedirs' was not found in SLS 'test’;  Reason: 'file.makedirs' is not available.”

### ISSUE THREAD

**Issue by rickh563** [saltstack/salt#31467]
The following is true:

* Validated bug is in 2015.8.7.
* Bug is consistent in all of the 2015.8 Branch.
* The test case creates a stack trace in the 2015.5 Branch.

See ZD-660 for additional detail.

------------

````
[root@frode-test ~]# salt --version
salt 2015.8.5 (Beryllium)
````
````
test:
  file.makedirs:
    - name: /opt/new/
    - user: root
    - group: root 
````

This gives me this error:

````
[root@frode-test ~]# salt frode-test state.sls test
frode-test:
----------
          ID: test
    Function: file.makedirs
        Name: /opt/new/
      Result: False
     Comment: State 'file.makedirs' was not found in SLS 'test'
              Reason: 'file.makedirs' is not available.
     Started: 
    Duration: 
     Changes:   

Summary for frode-test
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1

````

2015.5.9 gives me this message:

````
[root@frode-test salt]# salt --version
salt 2015.5.9 (Lithium)
[root@frode-test salt]# salt frode-test state.sls test
frode-test:
    The minion function caused an exception: Traceback (most recent call last):
      File "/root/salt/salt/minion.py", line 1071, in _thread_return
      File "/root/salt/salt/modules/state.py", line 639, in sls
        conflict = running(concurrent)
      File "/root/salt/salt/modules/state.py", line 117, in running
        active = __salt__['saltutil.is_running']('state.*')
      File "/root/salt/salt/loader.py", line 900, in __getitem__
        Iterate over all file_mapping files in order of closeness to mod_name
      File "/root/salt/salt/utils/lazy.py", line 93, in __getitem__
    KeyError: 'saltutil.is_running'
````

**Comment by cachedout** [comment]
Huh? `file.makedirs` is an execution module, not a state module. This is not a valid use case.

**Comment by rickh563** [comment]
Cachedout ... Thank you.
Support will take it back to the drawing board.

Please leave open for the near future until this is sorted later this week.

**Comment by rickh563** [comment]
Misuse of Salt.
