### ISSUE TITLE
archive.extracted fails on large tar.gz

### ISSUE THREAD

**Issue by strocknar** [saltstack/salt#31466]
```
# salt --versions-report
Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Oct 11 2015, 17:47:16)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: 0.21.0
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.4
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: redhat 7.2 Maipo
        machine: x86_64
        release: 3.10.0-327.el7.x86_64
         system: Red Hat Enterprise Linux Server 7.2 Maipo
```

-=# ERROR #=-

```
[ERROR   ] Uncaught exception
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/tornado/http1connection.py", line 237, in _read_message
    delegate.finish()
  File "/usr/lib64/python2.7/site-packages/tornado/http1connection.py", line 637, in finish
    return self._delegate.finish()
  File "/usr/lib64/python2.7/site-packages/tornado/simple_httpclient.py", line 502, in finish
    buffer = BytesIO(data)  # TODO: don't require one big string?
MemoryError
[DEBUG   ] Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/states/file.py", line 1696, in managed
    follow_symlinks)
  File "/usr/lib/python2.7/site-packages/salt/modules/file.py", line 4193, in manage_file
    sfn = __salt__['cp.cache_file'](source, saltenv)
  File "/usr/lib/python2.7/site-packages/salt/modules/cp.py", line 367, in cache_file
    result = __context__['cp.fileclient'].cache_file(path, saltenv)
  File "/usr/lib/python2.7/site-packages/salt/fileclient.py", line 158, in cache_file
    return self.get_url(path, '', True, saltenv)
  File "/usr/lib/python2.7/site-packages/salt/fileclient.py", line 622, in get_url
    **get_kwargs
  File "/usr/lib/python2.7/site-packages/salt/utils/http.py", line 438, in query
    **req_kwargs
  File "/usr/lib64/python2.7/site-packages/tornado/httpclient.py", line 102, in fetch
    self._async_client.fetch, request, **kwargs))
  File "/usr/lib64/python2.7/site-packages/tornado/ioloop.py", line 444, in run_sync
    return future_cell[0].result()
  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
_QuietException

[ERROR   ] Unable to manage file: 
[INFO    ] Completed state [/var/cache/salt/minion/files/base/_opt_mysql_i1_mysql-5.6.20-linux-glibc2.5-x86_64.tar] at time 18:33:08.905718
[DEBUG   ] file.managed: {'file_|-/var/cache/salt/minion/files/base/_opt_mysql_i1_mysql-5.6.20-linux-glibc2.5-x86_64.tar_|-/var/cache/salt/minion/files/base/_opt_mysql_i1_mysql-5.6.20-linux-glibc2.5-x86_64.tar_|-managed': {'comment': 'Unable to manage file: ', 'name': '/var/cache/salt/minion/files/base/_opt_mysql_i1_mysql-5.6.20-linux-glibc2.5-x86_64.tar', 'start_time': '18:32:47.417846', 'result': False, 'duration': 21487.872, '__run_num__': 0, 'changes': {}}}
[DEBUG   ] failed to download <<URL>>/mysql-5.6.20-linux-glibc2.5-x86_64.tar.gz
[ERROR   ] Unable to manage file: 
```

This seems to occur because the file I am trying to download is rather large (~300MB). Another, smaller tar.gz downloads and extracts correctly.

**Comment by jfindlay** [comment]
@strocknar, thanks for the report.

**Comment by strocknar** [comment]
This is probably due to the amount of memory on the box. I upgraded the RAM and it downloads successfully. Now I need to figure out why the md5 hash isn't correct...

**Comment by strocknar** [comment]
This state seems to do the trick as a workaround:

```
mysql_download:
    cmd.run:
        - name: wget <URL>/mysql-{{ mysql_version }}-linux-glibc2.5-x86_64.tar.gz -P /opt
        - creates: /opt/mysql-{{ mysql_version }}-linux-glibc2.5-x86_64.tar.gz

mysql_extraction:
    archive.extracted:
        - name: {{ mysql_root }}
        - source: file:///opt/mysql-{{ mysql_version }}-linux-glibc2.5-x86_64.tar.gz
        - archive_format: tar
        - tar_options: z
        - user: mysql
        - group: mysql
        - if_missing: {{ mysql_root }}/mysql-{{ mysql_version }}-linux-glibc2.5-x86_64
        - keep: True
        - require:
            - user: mysql
            - group: mysql
            - cmd: mysql_download
            - pkg: mysql_requirements
            - pkg: percona_install
```

**Comment by cachedout** [comment]
So it was running out of memory when `archive.extracted` was using a remote source but not with it as a local source after you downloaded it with curl?

**Comment by strocknar** [comment]
That is correct. I have no data to actually back this up, but I think it was trying to load the entire ~300M tar into memory before writing it to disk when using the remote source, whereas curl/wget were writing chunks to disk as they became available.

**Comment by dgengtek** [comment]
This issue seems to have regressed for salt version 2019.2.0. I noticed it also like OP when I used archive.extracted on a big release tar of over 1GB and the salt-minion process on the host machine consuming the 1GB capped memory of the host until the process was killed by oom killer.
