### ISSUE TITLE
Command crashed minion: salt '*' sys.doc

### ISSUE THREAD

**Issue by fredrikaverpil** [saltstack/salt#31481]
This is going to sound strange, but this command, run from the salt-master, crashed one of my minions:

```
salt '*' sys.doc
```

The minion in question is a VM running CentOS 7. All other minions are Windows-based and were unaffected. The salt-master is running in a Docker container (also CentOS 7). The weird part ... is that I was unable to SSH into the minion after this happened. When checking virt-manager on the host running the VM, the VM had been shut down!

The host running the VM is also the salt-master ...which makes this case a bit tangled.

Does this make any sense to you?

Full output from my terminal, seems like a loop to me:

```
[root@salt /]# salt '*' sys.doc
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: string indices must be integers, not str
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 458, in salt_main
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/salt.py", line 195, in run
    self._output_ret(ret, out)
  File "/usr/lib/python2.7/site-packages/salt/cli/salt.py", line 300, in _output_ret
    self._print_docs(ret)
  File "/usr/lib/python2.7/site-packages/salt/cli/salt.py", line 344, in _print_docs
    if ret[host][fun]:
TypeError: string indices must be integers, not str
^XTraceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 458, in salt_main
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/salt.py", line 195, in run
    self._output_ret(ret, out)
  File "/usr/lib/python2.7/site-packages/salt/cli/salt.py", line 300, in _output_ret
    self._print_docs(ret)
  File "/usr/lib/python2.7/site-packages/salt/cli/salt.py", line 344, in _print_docs
    if ret[host][fun]:
TypeError: string indices must be integers, not str
[root@salt /]# ^C
```

salt-master versions report:

```
Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.2
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.9.0
        timelib: Not Installed

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-123.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
```

When having the VM/minion up again, I was greeted by this upon logging in:

```
ABRT has detected 1 problem(s). For more info run: abrt-cli list --since 1456308662

$ abrt-cli list --since 1456308662

id 96e73227fa5015c109213b61f381b10299c729b6
Directory:      /var/tmp/abrt/oops-2016-02-25-13:57:41-731-0
count:          1
package:        kernel
time:           Thu 25 Feb 2016 01:57:41 PM CET

The Autoreporting feature is disabled. Please consider enabling it by issuing
'abrt-auto-reporting enabled' as a user with root privileges
```

Checking some of the files in there:

```
$ cat reason
BUG: soft lockup - CPU#0 stuck for 22s! [rmanpy:1865]

$ cat analyzer
Kerneloops

$ cat component
kernel
```

Please note: `rmanpy` is a server running on that VM.

Is it possible that this salt command _really_ crashed the VM so bad it took down the whole system? The timing makes me think so.

**Comment by jfindlay** [comment]
@fredrikaverpil, thanks for reporting.  I have created a 2014.8.7 CentOS 7 minion and can run
```
# salt jmoney-centos-7 sys.doc
```
without problem.  When run without argument, `sys.doc`, will return the reference docs for all loaded execution modules.
```
# salt jmoney-centos-7 sys.doc | wc
  21591   62215  531441
```
Is it possible that your minion's resources were too constrained to do this successfully?

**Comment by jfindlay** [comment]
I have confirmed my previous result on a 512MiB system.

**Comment by fredrikaverpil** [comment]
@jfindlay hm, strange. Let me try to run this again today to confirm that this was not a one time hiccup.
