### ISSUE TITLE
forumla's map.jinja not found in jinja-template-files on salt-ssh

### ISSUE THREAD

**Issue by sgeisbacher** [saltstack/salt#31531]
### Expected Behavior
the forumla's file-generation by jinja-template should load map.jinja also on salt-ssh.
this formula works with **salt minion state.highstate** like a charm, but not with **salt-ssh minion state.highstate**
### Actual Behavior
when performing a state.highstate via **salt-ssh** i get the following error-msg: (see bottom)
### Steps to Reproduce Issue
1. create a simple formula with map.jinja
2. add file generation by jinja (file.managed: - source: salt://.../file.jinja - template: jinja) to this formula
3. import the map.jinja to this file.jinja-template with `{% from ... import ... %}`
4. try to provision this formula to a minion with salt-ssh --> you will get the error from above
 
### Versions Report
Salt Version:
           Salt: 2015.8.7
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-71-generic
         system: Ubuntu 14.04 trusty

### Relevant Logs, Configs, or States
Error-Message: `Unable to manage file: Jinja error: jinjatest/map.jinja
              Traceback (most recent call last):
                File "/tmp/.root_09032a_salt/salt/utils/templates.py", line 366, in render_jinja_tmpl
                  output = template.render(**decoded_context)
                File "/tmp/.root_09032a_salt/jinja2/environment.py", line 969, in render
                  return self.environment.handle_exception(exc_info, True)
                File "/tmp/.root_09032a_salt/jinja2/environment.py", line 742, in handle_exception
                  reraise(exc_type, exc_value, tb)
                File "<template>", line 1, in top-level template code
                File "/tmp/.root_09032a_salt/salt/utils/jinja.py", line 144, in get_source
                  raise TemplateNotFound(template)
              TemplateNotFound: jinjatest/map.jinja
              
              ; line 1
              
              ---
              {% from "jinjatest/map.jinja" import jinjatest with context %}    <======================
              
              hello {{ jinjatest.name }}
              you are {{ jinjatest.age }} old
              Traceback (most recent call last):
                File "/tmp/.root_09032a_salt/salt/utils/templates.py", line 366, in render_jinja_tmpl
              [...]`

here is the simple-test-formula:
[salt-jinjatest.zip](https://github.com/saltstack/salt/files/149846/salt-jinjatest.zip)

**Comment by jfindlay** [comment]
@sgeisbacher, thanks for reporting.

**Comment by Ismail-AlJubbah** [comment]
@jfindlay can I work on this issue ?

**Comment by edgan** [comment]
The know workaround is using extra_filerefs. The salt-ssh code doesn't pick up files that aren't referenced by include or source. The import doesn't count. I have tried a system of having a state to source the map.jinja in cases of salt-ssh, but it proved to be more work than using the extra_filerefs method. See #9878 for history.

Saltfile:
extra_filerefs:
      - salt://jingatest/map.jinja

**Comment by awerner** [comment]
Another possible workaroung is to use the import statement in the init.sls and then pass the jinjatest variable as context to the file.managed state. This is also more clean IMO.
@Ismail-AlJubbah any progress?

**Comment by publicarray** [comment]
Any update?

**Comment by awerner** [comment]
If using the context does not work for you, I have another [workaround](https://github.com/saltstack/salt/issues/21370#issuecomment-423208486).

**Comment by max-arnold** [comment]
Bump

**Comment by max-arnold** [comment]
I made an ugly patch that seemingly fixes this issue by packing the whole `salt://` directory into the thin tarball:

```diff
diff --git a/salt/fileclient.py b/salt/fileclient.py
index d606bea99e..64ae1b0a63 100644
--- a/salt/fileclient.py
+++ b/salt/fileclient.py
@@ -238,7 +238,7 @@ class Client(object):
         # the target directory and caching them
         for fn_ in self.file_list(saltenv):
             fn_ = salt.utils.data.decode(fn_)
-            if fn_.strip() and fn_.startswith(path):
+            if fn_.strip() and (fn_.startswith(path) or path == '/'):
                 if salt.utils.stringutils.check_include_exclude(
                     fn_, include_pat, exclude_pat
                 ):
```

To activate it add `--extra-filerefs 'salt://'` command line option to `salt-ssh`.

**Comment by afletch** [comment]
This was not an issue in salt-2019.2.0-1 but since updating to salt-3000.2-1 it has become so.

**Comment by edgan** [comment]
> ```diff
> diff --git a/salt/fileclient.py b/salt/fileclient.py
> index d606bea99e..64ae1b0a63 100644
> --- a/salt/fileclient.py
> +++ b/salt/fileclient.py
> @@ -238,7 +238,7 @@ class Client(object):
>          # the target directory and caching them
>          for fn_ in self.file_list(saltenv):
>              fn_ = salt.utils.data.decode(fn_)
> -            if fn_.strip() and fn_.startswith(path):
> +            if fn_.strip() and (fn_.startswith(path) or path == '/'):
>                  if salt.utils.stringutils.check_include_exclude(
>                      fn_, include_pat, exclude_pat
>                  ):
> ```
> 

I tested @max-arnold 's patch. It works on salt-ssh 3001. It let me remove 78 lines from my Saltfile. I would love to see this become part of official Salt via a PR.

**Comment by louwers** [comment]
Doesn't work for me, and I feel that this should be the default behavior (e.g. Salt SSH should not require this tweak). If it's included it should be documented as well.

**Comment by max-arnold** [comment]
@louwers I'm puzzled why the patch doesn't work for you. Can you try the following salt-ssh command:

`salt-ssh HOSTNAME -t -W -w --extra-filerefs 'salt://' state.apply YOURSTATE`

Submitting a PR is still on my todo list (it requires salt-ssh integration tests which I'm unfamiliar with).

**Comment by max-arnold** [comment]
I'm hesitant to enable this behaviour by default, because it transfers the whole state tree which is slower. And implementing the proper solution (only transfer what is needed) is beyond my abilities and knowledge of salt-ssh internals.

@Ch3LL What do you think about including the above patch in Salt? Also, are there any viable approaches to implement a proper solution (that will be able to find the map.jinja files referenced from templates)? Is it possible to do that via salt-ssh wrappers, or it requires rearchitecting the way salt-ssh does file transfer (pull instead of push)?

**Comment by daks** [comment]
I tested @max-arnold patch and it works fine. I can put
```
salt-ssh:
  extra_filerefs:
    - salt://
```
and no more problem with missing files (map.jinja, defaults.yaml...). I understand that it may not be desirable to sync all `salt://` files by default, but, with enough warnings, it could be possible to let people do it.

**Comment by foudfou** [comment]
`extra_filerefs` workaround doesn't seem to work for me in `salt-3002` :sob:

See also #58762

**Comment by daks** [comment]
> `extra_filerefs` workaround doesn't seem to work for me in `salt-3002` sob
> 
> See also #58762

Broken for me too on 3002.1, works fine on 3001.3

**Comment by alxwr** [comment]
@foudfou @daks same here for me on FreeBSD 12.1, salt 3002

**Comment by alxwr** [comment]
@foudfou @daks I found a workaround. This patch adds just the bit of information required for `salt-ssh` to use `extra_filerefs` again. I made sure not to alter data structures which are used somewhere later in the code. (Consider this to be a hacky solution from an uninformed person though.)

```diff
From 052b72c0bf8040493f714b54775a50edd8d1062d Mon Sep 17 00:00:00 2001
Date: Wed, 11 Nov 2020 12:59:16 +0100
Subject: [PATCH] add extra_filerefs to SSH high state

---
 salt/client/ssh/wrapper/state.py | 10 ++++++++--
 1 file changed, 8 insertions(+), 2 deletions(-)

diff --git a/salt/client/ssh/wrapper/state.py b/salt/client/ssh/wrapper/state.py
index bbe8385ae0..ccf31d6bbf 100644
--- a/salt/client/ssh/wrapper/state.py
+++ b/salt/client/ssh/wrapper/state.py
@@ -5,6 +5,7 @@ Create ssh executor system
 import logging
 import os
 import time
+from copy import deepcopy
 
 import salt.client.ssh.shell
 import salt.client.ssh.state
@@ -656,15 +657,20 @@ def highstate(test=None, **kwargs):
     st_kwargs = __salt__.kwargs
     __opts__["grains"] = __grains__
     opts = salt.utils.state.get_sls_opts(__opts__, **kwargs)
+    highstate_opts = deepcopy(opts)
+    highstate_opts["extra_filerefs"] = opts["__master_opts__"].get("extra_filerefs", "")
+    highstate_opts["cachedir"] = opts["__master_opts__"].get("cachedir", "")
     st_ = salt.client.ssh.state.SSHHighState(
-        opts, __pillar__, __salt__, __context__["fileclient"]
+        highstate_opts, __pillar__, __salt__, __context__["fileclient"]
     )
     st_.push_active()
     chunks = st_.compile_low_chunks()
     file_refs = salt.client.ssh.state.lowstate_file_refs(
         chunks,
         _merge_extra_filerefs(
-            kwargs.get("extra_filerefs", ""), opts.get("extra_filerefs", "")
+            kwargs.get("extra_filerefs", ""),
+            opts.get("extra_filerefs", ""),
+            opts.get("__master_opts__", {}).get("extra_filerefs", "")
         ),
     )
     # Check for errors
-- 
2.25.1
```

Please test with

`salt-ssh HOSTNAME -t -W -w state.apply YOURSTATE test=True`

**Comment by baby-gnu** [comment]
Retrying [my tests](https://github.com/saltstack/salt/issues/31531#issuecomment-952884347), I have a strange behavior:

1. <details><summary>it does not find map.jinja</summary>

   ```
   $ salt-ssh testmachine2 state.apply test-import-rootfs
   [ERROR   ] Rendering exception occurred
   Traceback (most recent call last):
     File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 502, in render_jinja_tmpl
       output = template.render(**decoded_context)
     File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1291, in render
       self.environment.handle_exception()
     File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 925, in handle_exception
       raise rewrite_traceback_stack(source=source)
     File "<template>", line 3, in top-level template code
     File "/usr/lib/python3/dist-packages/salt/utils/jinja.py", line 198, in get_source
       raise TemplateNotFound(template)
   jinja2.exceptions.TemplateNotFound: test-import-rootfs/map.jinja
   
   During handling of the above exception, another exception occurred:
   
   Traceback (most recent call last):
     File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 261, in render_tmpl
       output = render_str(tmplstr, context, tmplpath)
     File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 547, in render_jinja_tmpl
       raise SaltRenderError(
   salt.exceptions.SaltRenderError: Jinja error: test-import-rootfs/map.jinja
   Traceback (most recent call last):
     File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 502, in render_jinja_tmpl
       output = template.render(**decoded_context)
     File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1291, in render
       self.environment.handle_exception()
     File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 925, in handle_exception
       raise rewrite_traceback_stack(source=source)
     File "<template>", line 3, in top-level template code
     File "/usr/lib/python3/dist-packages/salt/utils/jinja.py", line 198, in get_source
       raise TemplateNotFound(template)
   jinja2.exceptions.TemplateNotFound: test-import-rootfs/map.jinja
   
   ; line 3
   
   ---
   # -*- mode: salt; coding: utf-8 -*-
   # vim: ft=sls
   {% from "test-import-rootfs/map.jinja" import mapdata %}    <======================
   
   test-import-rootfs/absolute/test.show_notification:
     test.show_notification:
       - text: {{ mapdata | json }}
   
   [...]
   ---
   [CRITICAL] Rendering SLS 'base:test-import-rootfs.absolute' failed: Jinja error: test-import-rootfs/map.jinja
   Traceback (most recent call last):
     File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 502, in render_jinja_tmpl
       output = template.render(**decoded_context)
     File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1291, in render
       self.environment.handle_exception()
     File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 925, in handle_exception
       raise rewrite_traceback_stack(source=source)
     File "<template>", line 3, in top-level template code
     File "/usr/lib/python3/dist-packages/salt/utils/jinja.py", line 198, in get_source
       raise TemplateNotFound(template)
   jinja2.exceptions.TemplateNotFound: test-import-rootfs/map.jinja
   
   ; line 3
   
   ---
   # -*- mode: salt; coding: utf-8 -*-
   # vim: ft=sls
   {% from "test-import-rootfs/map.jinja" import mapdata %}    <======================
   
   test-import-rootfs/absolute/test.show_notification:
     test.show_notification:
       - text: {{ mapdata | json }}
   
   [...]
   ---
   [ERROR   ] Rendering exception occurred
   Traceback (most recent call last):
     File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 502, in render_jinja_tmpl
       output = template.render(**decoded_context)
     File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1291, in render
       self.environment.handle_exception()
     File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 925, in handle_exception
       raise rewrite_traceback_stack(source=source)
     File "<template>", line 3, in top-level template code
     File "/usr/lib/python3/dist-packages/salt/utils/jinja.py", line 198, in get_source
       raise TemplateNotFound(template)
   jinja2.exceptions.TemplateNotFound: ./map.jinja
   
   During handling of the above exception, another exception occurred:
   
   Traceback (most recent call last):
     File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 261, in render_tmpl
       output = render_str(tmplstr, context, tmplpath)
     File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 547, in render_jinja_tmpl
       raise SaltRenderError(
   salt.exceptions.SaltRenderError: Jinja error: ./map.jinja
   Traceback (most recent call last):
     File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 502, in render_jinja_tmpl
       output = template.render(**decoded_context)
     File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1291, in render
       self.environment.handle_exception()
     File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 925, in handle_exception
       raise rewrite_traceback_stack(source=source)
     File "<template>", line 3, in top-level template code
     File "/usr/lib/python3/dist-packages/salt/utils/jinja.py", line 198, in get_source
       raise TemplateNotFound(template)
   jinja2.exceptions.TemplateNotFound: ./map.jinja
   
   ; line 3
   
   ---
   # -*- mode: salt; coding: utf-8 -*-
   # vim: ft=sls
   {% from "./map.jinja" import mapdata %}    <======================
   
   test-import-rootfs/relative/test.show_notification:
     test.show_notification:
       - text: {{ mapdata | json }}
   
   [...]
   ---
   [CRITICAL] Rendering SLS 'base:test-import-rootfs.relative' failed: Jinja error: ./map.jinja
   Traceback (most recent call last):
     File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 502, in render_jinja_tmpl
       output = template.render(**decoded_context)
     File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1291, in render
       self.environment.handle_exception()
     File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 925, in handle_exception
       raise rewrite_traceback_stack(source=source)
     File "<template>", line 3, in top-level template code
     File "/usr/lib/python3/dist-packages/salt/utils/jinja.py", line 198, in get_source
       raise TemplateNotFound(template)
   jinja2.exceptions.TemplateNotFound: ./map.jinja
   
   ; line 3
   
   ---
   # -*- mode: salt; coding: utf-8 -*-
   # vim: ft=sls
   {% from "./map.jinja" import mapdata %}    <======================
   
   test-import-rootfs/relative/test.show_notification:
     test.show_notification:
       - text: {{ mapdata | json }}
   
   [...]
   ---
   testmachine2:
       - Rendering SLS 'base:test-import-rootfs.absolute' failed: Jinja error: test-import-rootfs/map.jinja
         Traceback (most recent call last):
           File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 502, in render_jinja_tmpl
             output = template.render(**decoded_context)
           File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1291, in render
             self.environment.handle_exception()
           File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 925, in handle_exception
             raise rewrite_traceback_stack(source=source)
           File "<template>", line 3, in top-level template code
           File "/usr/lib/python3/dist-packages/salt/utils/jinja.py", line 198, in get_source
             raise TemplateNotFound(template)
         jinja2.exceptions.TemplateNotFound: test-import-rootfs/map.jinja
   
         ; line 3
   
         ---
         # -*- mode: salt; coding: utf-8 -*-
         # vim: ft=sls
         {% from "test-import-rootfs/map.jinja" import mapdata %}    <======================
   
         test-import-rootfs/absolute/test.show_notification:
           test.show_notification:
             - text: {{ mapdata | json }}
   
         [...]
         ---
       - Rendering SLS 'base:test-import-rootfs.relative' failed: Jinja error: ./map.jinja
         Traceback (most recent call last):
           File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 502, in render_jinja_tmpl
             output = template.render(**decoded_context)
           File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1291, in render
             self.environment.handle_exception()
           File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 925, in handle_exception
             raise rewrite_traceback_stack(source=source)
           File "<template>", line 3, in top-level template code
           File "/usr/lib/python3/dist-packages/salt/utils/jinja.py", line 198, in get_source
             raise TemplateNotFound(template)
         jinja2.exceptions.TemplateNotFound: ./map.jinja
   
         ; line 3
   
         ---
         # -*- mode: salt; coding: utf-8 -*-
         # vim: ft=sls
         {% from "./map.jinja" import mapdata %}    <======================
   
         test-import-rootfs/relative/test.show_notification:
           test.show_notification:
             - text: {{ mapdata | json }}
   
         [...]
         ---
   ```
   </details>
2. <details><summary>Trying a sub-state is working</summary>

	```
   $ salt-ssh testmachine2 state.apply test-import-rootfs.relative
   testmachine2:
   ----------
             ID: test-import-rootfs/relative/test.show_notification
       Function: test.show_notification
         Result: True
        Comment: {'test-import-rootfs': 'foo'}
        Started: 11:56:20.440018
       Duration: 0.714 ms
        Changes:
   
   Summary for testmachine2
   ------------
   Succeeded: 1
   Failed:    0
   ------------
   Total states run:     1
   Total run time:   0.714 ms
	```
2. <details><summary>Retrying the meta-state is now working</summary>

	```
   salt-ssh testmachine2 state.apply test-import-rootfs
   testmachine2:
   ----------
             ID: test-import-rootfs/absolute/test.show_notification
       Function: test.show_notification
         Result: True
        Comment: {'test-import-rootfs': 'foo'}
        Started: 11:57:10.487955
       Duration: 0.693 ms
        Changes:
   ----------
             ID: test-import-rootfs/relative/test.show_notification
       Function: test.show_notification
         Result: True
        Comment: {'test-import-rootfs': 'foo'}
        Started: 11:57:10.488765
       Duration: 0.548 ms
        Changes:
   
   Summary for testmachine2
   ------------
   Succeeded: 2
   Failed:    0
   ------------
   Total states run:     2
   Total run time:   1.241 ms
	```

<details><summary><code>/home/me/.salt/Saltfile</code></summary>

```yaml
# -*- mode: yaml; coding: utf-8 -*-

salt-ssh:
  config_dir: ~/.salt
```

</details>


<details><summary><code>/home/me/.salt/master</code></summary>

```yaml
# -*- mode: yaml; coding: utf-8 -*-

####
#### Global parameters
####

# Unfortunately, salt does not support ~ expension
# We need to use absolute path for `root_dir`
root_dir: /home/me/.salt
pki_dir: pki
cachedir: cache
sock_dir: run
pidfile: pids

log_file: logs/master.log
key_logfile: logs/key.log

# Global level logged in file
log_level_logfile: debug

##
## file server
##
# I'm using formula repositories but override things from time to time
fileserver_backend:
  - roots

# Unfortunately, salt does not support ~ expension
# We need to use absolute path for `file_roots` and `pillar_roots`
file_roots:
  base:
    - /home/me/.salt/srv/salt/

pillar_roots:
  base:
    - /home/me/.salt/srv/pillar/
```
</details>

<details><summary><code>/home/me/.salt/roster</code></summary>

```yaml
# -*- mode: yaml; coding: utf-8 -*-

testmachine2:
  host: 192.168.0.102
  user: root
```
</details>

<details><summary><code>/home/me/.salt/srv/salt/test-import-rootfs/init.sls</code></summary>

```sls
# -*- mode: salt; coding: utf-8 -*-
# vim: ft=sls
include:
  - .absolute
  - .relative
```
</details>

<details><summary><code>/home/me/.salt/srv/salt/test-import-rootfs/absolute.sls</code></summary>

```sls
# -*- mode: salt; coding: utf-8 -*-
# vim: ft=sls
{% from "test-import-rootfs/map.jinja" import mapdata %}

test-import-rootfs/absolute/test.show_notification:
  test.show_notification:
    - name: {{ mapdata | json }}
```
</details>

<details><summary><code>/home/me/.salt/srv/salt/test-import-rootfs/relative.sls</code></summary>

```sls
# -*- mode: salt; coding: utf-8 -*-
# vim: ft=sls
{% from "./map.jinja" import mapdata %}

test-import-rootfs/relative/test.show_notification:
  test.show_notification:
    - name: {{ mapdata | json }}
```
</details>

<details><summary><code>/home/me/.salt/srv/salt/test-import-rootfs/map.jinja</code></summary>

```jinja
{#- -*- mode: jinja; coding: utf-8 -*- #}
{#- vim: ft=sls #}
{%- set mapdata = {"test-import-rootfs": "foo"} %}
```
</details>

I think there is a caching issue.

If I change the content of `/home/me/.salt/srv/salt/test-import-rootfs/map.jinja` I still get the old content. Cleaning my `~/.salt/cache` or the minion `/var/tmp/.root_*` directories does nothing.

**Comment by baby-gnu** [comment]
When I change `map.jinja`, the cache is updated only when I execute sub states like `salt-ssh testmachine2 state.apply test-import-rootfs.absolute` and not `salt-ssh testmachine2 state.apply test-import-rootfs`.

Weird.

**Comment by baby-gnu** [comment]
I have the exact same caching issue with `gitfs`.

**Comment by baby-gnu** [comment]
Hello, #61895 fixes my issues with either `rootfs` and `gitfs`.

**Comment by dwoz** [comment]
I believe this to be fixed by #65517

**Comment by dwoz** [comment]
Reopening — PR #65517 cited but did not patch SaltCacheLoader; the actual fix 481bd7a6a72 was not backported to 3006.x. Backport in #69596.
