### ISSUE TITLE
crash trying to get a shared lock on a file opened for writing (on nfs)

### ISSUE THREAD

**Issue by jcristau** [saltstack/salt#31543]
### Expected Behavior

No crash
### Actual Behavior

```
[ERROR   ] Error in function _file_hash:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 1379, in run_func
    ret = getattr(self, func)(load)
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/__init__.py", line 582, in file_hash
    return self.servers[fstr](load, fnd)
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/roots.py", line 227, in file_hash
    return file_hash(load, fnd)
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/roots.py", line 245, in file_hash
    with salt.utils.flopen(cache_path, 'w') as fp_:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/lib/python2.7/dist-packages/salt/utils/__init__.py", line 1226, in flopen
    fcntl.flock(fhandle.fileno(), fcntl.LOCK_SH)
IOError: [Errno 9] Bad file descriptor
```
### Steps to Reproduce Issue

Put the master's cachedir on nfs; try to get anything from the fileserver (my test is `salt-call state.show_highstate` on the minion).

The flock(2) manpage suggests that the Linux NFS client emulates flock with byte-range locks on the entire file, a-la fcntl, and fcntl(2) suggests that trying to get a shared lock on a file descriptor not open for reading fails with EBADF.
### Versions Report

```
Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
           Mako: 1.0.0
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: 2.3.0
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: debian 8.3 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.3 
```

**Comment by jfindlay** [comment]
@jcristau, thanks for the report.  By crash, do you mean that the salt-master daemon stops when this happens?

**Comment by jcristau** [comment]
No, IIRC the daemon doesn't stop, but it also doesn't do anything useful since any fileserver accesses from the minions (say, to get top.sls) give an empty result.

**Comment by dynek** [comment]
Too bad it was closed, I'm having this exact same issue.
