### ISSUE TITLE
Proxy minion commands causing exceptions

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#31585]
### Description of Issue/Question
On a proxy minion setup, when running `salt p8000 pkg.list_pkgs`, it returns:
```
p8000:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1210, in _thread_return
        return_data = executor.execute()
      File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/usr/lib/python2.7/site-packages/salt/modules/ssh_package.py", line 31, in list_pkgs
        return __proxy__['ssh_sample.package_list']()
      File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1010, in __getitem__
        func = super(LazyLoader, self).__getitem__(item)
      File "/usr/lib/python2.7/site-packages/salt/utils/lazy.py", line 93, in __getitem__
        raise KeyError(key)
    KeyError: 'ssh_sample.package_list'
```
I get the similar errors when runnig `pkg.install` and `pkg.remove`.

These commands are working in version `2015.8.7`.

Running `salt p8000 test.ping`, returns:
```
p8000:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1210, in _thread_return
        return_data = executor.execute()
      File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/usr/lib/python2.7/site-packages/salt/modules/test.py", line 119, in ping
        return __opts__['proxymodule'][ping_cmd]()
    KeyError: 'proxy module'
```
This also fails in `2015.8.7`.

### Setup

```
install bottle
git clone https://github.com/saltstack/salt-manual-tests.git
git clone https://github.com/saltstack/salt-contrib.git

/etc/salt/master

pillar_roots:
  base:
    - /root/salt-manual-tests/proxy/pillar

file_roots:
  base:
    - /root/salt-manual-tests/proxy/states

/etc/salt/proxy

master: localhost

Replaced {{ip}} with the IP address of the system in /root/salt-manual-tests/proxy/pillar/proxy8000.sls
```

### Steps to Reproduce Issue
salt-master -l debug
cd ~/salt-contrib/proxyminion_rest_example/ && python rest.py --address=IP-addr --port=8000
browse to http://IP-addr:8000  (watch this page)
salt-proxy --proxyid=p8000 -l debug
salt-key -ya p8000

### Versions Report
```
Salt Version:
           Salt: 2016.3.0rc1-575-ge1ade05
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: centos 7.0.1406 Core
        machine: x86_64
        release: 4.4.0-x86_64-linode63
         system: CentOS Linux 7.0.1406 Core
```

**Comment by cro** [comment]
@frogunder Ready for you to try again as soon as these are merged.

**Comment by frogunder** [comment]
@cro - Retested and everything is working fine.

Thanks.
