### ISSUE TITLE
Running salt-cloud concurrently breaks the cache.

### ISSUE THREAD

**Issue by geraint-jones-nz** [saltstack/salt#31634]
### Description of Issue/Question

Running two instances of `salt-cloud` appears to clause the cache to be damaged.

### Setup
Provider is EC2.

two profiles, each in separate VPCs and stuff - but I dont think this is important, I think it's simply concurrent `salt-cloud` commands.

### Steps to Reproduce Issue
in one terminal run `salt-cloud -m /some/map/file/here -P` and in a second on the same salt master run `salt-cloud -m /some/other/map/file -P`

The first instance may or may not complete - mine hung, however the second instance died with this output.

```
[INFO    ] Calculating dependencies for API01.EU1C.SANDBOX
[INFO    ] Calculating dependencies for SOLR01.EU1C.SANDBOX
[INFO    ] Since parallel deployment is in use, ssh console output is disabled. All ssh output will be logged though
[INFO    ] Cloud pool size: 2
[INFO    ] Creating Cloud VM SOLR01.EU1C.SANDBOX in eu-west-1
[INFO    ] Creating Cloud VM API01.EU1C.SANDBOX in eu-west-1
[INFO    ] Starting new HTTPS connection (1): ec2.eu-west-1.amazonaws.com
[INFO    ] Starting new HTTPS connection (1): ec2.eu-west-1.amazonaws.com
[INFO    ] Starting new HTTPS connection (1): ec2.eu-west-1.amazonaws.com
[INFO    ] Starting new HTTPS connection (1): ec2.eu-west-1.amazonaws.com
[INFO    ] Starting new HTTPS connection (1): ec2.eu-west-1.amazonaws.com
[INFO    ] Starting new HTTPS connection (1): ec2.eu-west-1.amazonaws.com
[INFO    ] Starting new HTTPS connection (1): ec2.eu-west-1.amazonaws.com
[INFO    ] Starting new HTTPS connection (1): ec2.eu-west-1.amazonaws.com
[INFO    ] Starting new HTTPS connection (1): ec2.eu-west-1.amazonaws.com
[INFO    ] Starting new HTTPS connection (1): ec2.eu-west-1.amazonaws.com
[INFO    ] Created node SOLR01.EU1C.SANDBOX
[INFO    ] Created node API01.EU1C.SANDBOX
[INFO    ] Salt node data. Private_ip: 10.10.48.8
[INFO    ] Salt node data. Private_ip: 10.10.48.62
[INFO    ] Salt interface set to: 10.10.48.8
[INFO    ] Salt interface set to: 10.10.48.62
[WARNING ] Failed to spawn the VT: [Errno 12] Cannot allocate memory
[WARNING ] Failed to spawn the VT: [Errno 12] Cannot allocate memory
[ERROR   ] A wrong password has been issued while establishing ssh session
[ERROR   ] A wrong password has been issued while establishing ssh session
[WARNING ] Failed to spawn the VT: [Errno 12] Cannot allocate memory
[WARNING ] Failed to spawn the VT: [Errno 12] Cannot allocate memory
[ERROR   ] A wrong password has been issued while establishing ssh session
[ERROR   ] A wrong password has been issued while establishing ssh session
[WARNING ] Failed to spawn the VT: [Errno 12] Cannot allocate memory
[WARNING ] Failed to spawn the VT: [Errno 12] Cannot allocate memory
[ERROR   ] A wrong password has been issued while establishing ssh session
[ERROR   ] A wrong password has been issued while establishing ssh session
[WARNING ] Failed to spawn the VT: [Errno 12] Cannot allocate memory
[WARNING ] Failed to spawn the VT: [Errno 12] Cannot allocate memory
[ERROR   ] A wrong password has been issued while establishing ssh session
[ERROR   ] A wrong password has been issued while establishing ssh session
[WARNING ] Failed to spawn the VT: [Errno 12] Cannot allocate memory
[WARNING ] Failed to spawn the VT: [Errno 12] Cannot allocate memory
[ERROR   ] A wrong password has been issued while establishing ssh session
[ERROR   ] A wrong password has been issued while establishing ssh session
[WARNING ] Failed to spawn the VT: [Errno 12] Cannot allocate memory
[WARNING ] Failed to spawn the VT: [Errno 12] Cannot allocate memory
[ERROR   ] A wrong password has been issued while establishing ssh session
[ERROR   ] A wrong password has been issued while establishing ssh session
[WARNING ] Failed to spawn the VT: [Errno 12] Cannot allocate memory
[WARNING ] Failed to spawn the VT: [Errno 12] Cannot allocate memory
[ERROR   ] A wrong password has been issued while establishing ssh session
[ERROR   ] A wrong password has been issued while establishing ssh session
[WARNING ] Failed to spawn the VT: [Errno 12] Cannot allocate memory
[WARNING ] Failed to spawn the VT: [Errno 12] Cannot allocate memory
[ERROR   ] A wrong password has been issued while establishing ssh session
[ERROR   ] A wrong password has been issued while establishing ssh session
[WARNING ] Failed to spawn the VT: [Errno 12] Cannot allocate memory
[WARNING ] Failed to spawn the VT: [Errno 12] Cannot allocate memory
[ERROR   ] A wrong password has been issued while establishing ssh session
[ERROR   ] A wrong password has been issued while establishing ssh session
[WARNING ] Failed to spawn the VT: [Errno 12] Cannot allocate memory
[WARNING ] Failed to spawn the VT: [Errno 12] Cannot allocate memory
[ERROR   ] A wrong password has been issued while establishing ssh session
[ERROR   ] A wrong password has been issued while establishing ssh session
^C
Exiting gracefully on Ctrl-c
```

After this all `salt-cloud` commands die with the following

```
[ERROR   ] Caught Exception, terminating workers
TRACE: unpack(b) recieved extra data.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 60, in _call
    ret = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 2229, in destroy_multiprocessing
    output = fun(parallel_data['name'])
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 2960, in destroy
    salt.utils.cloud.cachedir_index_del(name)
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 2389, in cachedir_index_del
    index = msgpack.load(fh_)
  File "_unpacker.pyx", line 130, in msgpack._unpacker.unpack (msgpack/_unpacker.cpp:132)
  File "_unpacker.pyx", line 114, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:114)
ExtraData: unpack(b) recieved extra data.



Error: There was an error destroying machines: Exception caught
Caught Exception, terminating workers
TRACE: unpack(b) recieved extra data.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 60, in _call
    ret = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 2229, in destroy_multiprocessing
    output = fun(parallel_data['name'])
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 2960, in destroy
    salt.utils.cloud.cachedir_index_del(name)
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 2389, in cachedir_index_del
    index = msgpack.load(fh_)
  File "_unpacker.pyx", line 130, in msgpack._unpacker.unpack (msgpack/_unpacker.cpp:132)
  File "_unpacker.pyx", line 114, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:114)
ExtraData: unpack(b) recieved extra data.
Process SyncManager-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 558, in _run_server
    server.serve_forever()
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 184, in serve_forever
    t.start()
  File "/usr/lib/python2.7/threading.py", line 745, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread
```

Removing `/var/cache/salt/cloud/` and running `salt-cloud -F` seems to restore balance to the force.

### Versions Report
```
salt-cloud --versions-report
Salt Version:
            Salt: 2015.8.3

Dependency Versions:
 Apache Libcloud: Not Installed
          Jinja2: 2.7.2
        M2Crypto: 0.21.1
            Mako: Not Installed
          PyYAML: 3.10
           PyZMQ: 14.0.1
          Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
            RAET: Not Installed
         Tornado: 4.3
             ZMQ: 4.0.4
            cffi: Not Installed
        cherrypy: 4.0.0
        dateutil: Not Installed
           gitdb: 0.5.4
       gitpython: 0.3.2 RC1
           ioflo: Not Installed
         libnacl: Not Installed
    msgpack-pure: Not Installed
  msgpack-python: 0.3.0
    mysql-python: Not Installed
       pycparser: Not Installed
        pycrypto: 2.6.1
          pygit2: Not Installed
    python-gnupg: Not Installed
           smmap: 0.8.2
         timelib: Not Installed

System Versions:
            dist: Ubuntu 14.04 trusty
         machine: x86_64
         release: 3.13.0-48-generic
          system: Ubuntu 14.04 trusty
```

**Comment by techhat** [comment]
#30671 should fix this.
