### ISSUE TITLE
s3 ext pillar cache file cannot be found/not being created

### ISSUE THREAD

**Issue by toanctruong** [saltstack/salt#31664]
### Description of Issue/Question

Unable to load ext_pillar s3 due to cache file not existing. Is this [https://github.com/saltstack/salt/issues/28689](28689) all over again? This is a completely fresh master. There is an IAM Role with full S3 access for this box.
### Setup

```
ext_pillar:
  - s3:
      bucket: mypillar.company.com
      multiple_env: False
      environment: base
      prefix: srv/pillars
      verify_ssl: False
      service_url: s3.amazonaws.com
      s3_cache_expire: 30
      s3_sync_on_update: True
      location: us-west-2
```
### Steps to Reproduce Issue

```
salt '*' pillar.get foo:bar -l debug
```

```
2016-03-03 19:32:36,802 [salt.pillar      ][ERROR   ][16370] Failed to load ext_pillar s3: [Errno 2] No such file or directory: '/var/cache/salt/master/pillar_s3fs/mypillar.company.com-srv/pillars-files.cache'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/pillar/__init__.py", line 637, in ext_pillar
    key)
  File "/usr/lib/python2.7/site-packages/salt/pillar/__init__.py", line 589, in _external_pillar_data
    ext = self.ext_pillars[key](self.opts['id'], pillar, **val)
  File "/usr/lib/python2.7/site-packages/salt/pillar/s3.py", line 144, in ext_pillar
    metadata = _init(s3_creds, bucket, multiple_env, environment, prefix, s3_cache_expire)
  File "/usr/lib/python2.7/site-packages/salt/pillar/s3.py", line 197, in _init
    environment, prefix)
  File "/usr/lib/python2.7/site-packages/salt/pillar/s3.py", line 320, in _refresh_buckets_cache_file
    with salt.utils.fopen(cache_file, 'w') as fp_:
  File "/usr/lib/python2.7/site-packages/salt/utils/__init__.py", line 1204, in fopen
    fhandle = open(*args, **kwargs)
IOError: [Errno 2] No such file or directory: '/var/cache/salt/master/pillar_s3fs/mypillar.company.com-srv/pillars-files.cache'
```
### Versions Report

```
Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: 3.2.2
       dateutil: 2.5.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: 0.21.0
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.4
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.10.1.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
```

**Comment by jfindlay** [comment]
@toanctruong, thanks for reporting.
