### ISSUE TITLE
salt cloud vmware - argument of type 'bool' is not iterable

### ISSUE THREAD

**Issue by steverweber** [saltstack/salt#31681]
salt cloud vmware branch 2016.

```
          ID: mfcf.service.salt-cloud.vmware - scinage-0.private.xxxxxx.ca
    Function: cloud_instance.present
        Name: scinage-0.private.xxxxx.ca
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1701, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1607, in wrapper
                  return f(*args, **kwargs)
                File "/var/cache/salt/minion/extmods/states/cloud_instance.py", line 50, in present
                  vm_instance = __salt__['cloud.get_instance'](name)
                File "/usr/lib/python2.7/site-packages/salt/modules/cloud.py", line 175, in get_instance
                  data = action(fun='show_instance', names=[name], provider=provider)
                File "/usr/lib/python2.7/site-packages/salt/modules/cloud.py", line 234, in action
                  info = client.action(fun, cloudmap, names, provider, instance, kwargs)
                File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 478, in action
                  return mapper.do_action(names, kwargs)
                File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1476, in do_action
                  if 'id' in vm_details:
              TypeError: argument of type 'bool' is not iterable
     Started: 13:25:58.567303
    Duration: 351.218 ms

```

```
[root@salt-cloud ~]# salt --versions-report
Salt Version:
           Salt: 2016.3.0rc1-879-gaf5e5e5
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.10.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

**Comment by steverweber** [comment]
```
[INFO    ] Running state [salt-master-1.math.private.xxxxxxxx.ca] at time 13:39:10.075861
[INFO    ] Executing state cloud_instance.present for salt-master-1.math.private.xxxxxxxx.ca
[WARNING ] Key master_tops with value {} has an invalid type of dict, a bool is required for this value
[ERROR   ] Failed to import clouds botocore_aws, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1253, in _load_module
    ), fn_, fpath, desc)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/botocore_aws.py", line 49, in <module>
    from salt.cloud.clouds import libcloud_aws
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/libcloud_aws.py", line 82, in <module>
    get_salt_interface = namespaced_function(get_salt_interface, globals())
NameError: name 'get_salt_interface' is not defined
[ERROR   ] Failed to import clouds libcloud_aws, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1253, in _load_module
    ), fn_, fpath, desc)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/libcloud_aws.py", line 82, in <module>
    get_salt_interface = namespaced_function(get_salt_interface, globals())
NameError: name 'get_salt_interface' is not defined
[ERROR   ] Failed to import clouds botocore_aws, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1253, in _load_module
    ), fn_, fpath, desc)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/botocore_aws.py", line 49, in <module>
    from salt.cloud.clouds import libcloud_aws
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/libcloud_aws.py", line 82, in <module>
    get_salt_interface = namespaced_function(get_salt_interface, globals())
NameError: name 'get_salt_interface' is not defined
[ERROR   ] Failed to import clouds libcloud_aws, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1253, in _load_module
    ), fn_, fpath, desc)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/libcloud_aws.py", line 82, in <module>
    get_salt_interface = namespaced_function(get_salt_interface, globals())
NameError: name 'get_salt_interface' is not defined
[WARNING ] /usr/lib/python2.7/site-packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)

[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 1701, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1607, in wrapper
    return f(*args, **kwargs)
  File "/var/cache/salt/minion/extmods/states/cloud_instance.py", line 50, in present
    vm_instance = __salt__['cloud.get_instance'](name)
  File "/usr/lib/python2.7/site-packages/salt/modules/cloud.py", line 175, in get_instance
    data = action(fun='show_instance', names=[name], provider=provider)
  File "/usr/lib/python2.7/site-packages/salt/modules/cloud.py", line 234, in action
    info = client.action(fun, cloudmap, names, provider, instance, kwargs)
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 478, in action
    return mapper.do_action(names, kwargs)
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1476, in do_action
    if 'id' in vm_details and vm_details['id'] in names:
TypeError: argument of type 'bool' is not iterable

[INFO    ] Completed state [salt-master-1.math.private.xxxxxxxx.ca] at time 13:39:10.521673 duration_in_ms=445.812
```

extra details

**Comment by jfindlay** [comment]
@steverweber, thanks for reporting.

**Comment by techhat** [comment]
Hi @steverweber. I suspect that there's something else going on in there, but #31725 should get past the error and throw a debug message for you.

**Comment by steverweber** [comment]
i was moving between different branches so perhaps i had some mixture of pyc files causing issues... i'll close out.
