### ISSUE TITLE
rh_service references osrelease before it is available, also does not return bool

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#31731]
### Description of Issue/Question
```
[ERROR   ] Exception raised when processing __virtual__ function for rh_service. Module will not be loaded local variable 'osrelease' referenced before assignment
[WARNING ] salt.loaded.int.module.rh_service.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'rh_service', please fix this.
```
### Setup
*Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).*
n/a

### Steps to Reproduce Issue
*Include debug logs if possible and relevant.*
- start a minion on CentOS 7.

### Versions Report
*Provided by running* ``salt --versions-report``
```
salt Version:
           Salt: 2016.3.0rc1-901-gb8ae54d

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 13.1.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: 0.6.5
        Tornado: 4.3
            ZMQ: 3.2.2
           cffi: Not Installed
       cherrypy: 5.0.1
       dateutil: 2.5.0
          gitdb: 0.6.4
      gitpython: 0.3.2 RC1
          ioflo: 1.5.0
        libgit2: Not Installed
        libnacl: 1.4.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 2.0.2
          smmap: 0.9.0
        timelib: 0.2.4

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

**Comment by jfindlay** [comment]
@sjorge, thanks for reporting.

**Comment by jaipepe** [comment]
I am also seeing this issue on CentOS 7 for the 2015.8.8 release. The following is an example output from running salt-call state.sls saltmaster.mom.

saltmaster.mom
```mom.packages:
  pkg.installed:
    - pkgs:
      - python-pyvmomi: 5.5.0.2014.1.1```

The first time running it, the state ran and installed the package successfully, but I received the following output.
```[INFO    ] Completed state [mom.packages] at time 15:59:14.175381
local:
----------
          ID: mom.packages
    Function: pkg.installed
      Result: False
     Comment: The following packages failed to install/update: python-pyvmomi=5.5.0.2014.1.1
     Started: 15:58:56.774699
    Duration: 17400.682 ms
     Changes:
              ----------
              python-pyvmomi:
                  ----------
                  new:
                      5.5.0.2014.1.1-3.el7
                  old:

Summary for local
------------
Succeeded: 0 (changed=1)
Failed:    1
------------
Total states run:     1```

Running the state again, once the package has been installed from the previous run produces this output:
```[INFO    ] Completed state [mom.packages] at time 16:06:13.051604
local:
----------
          ID: mom.packages
    Function: pkg.installed
      Result: False
     Comment: The following packages failed to install/update: python-pyvmomi=5.5.0.2014.1.1
     Started: 16:05:57.002771
    Duration: 16048.833 ms
     Changes:

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
```

Error output from both runs:
```[ERROR   ] Exception raised when processing __virtual__ function for rh_service. Module will not be loaded local variable 'osrelease' referenced before assignment
[WARNING ] salt.loaded.int.module.rh_service.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'rh_service', please fix this.
[ERROR   ] Failed to import module win_dacl, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1136, in _load_module
    ), fn_, fpath, desc)
  File "/usr/lib/python2.7/site-packages/salt/modules/win_dacl.py", line 39, in <module>
    class daclConstants(object):
  File "/usr/lib/python2.7/site-packages/salt/modules/win_dacl.py", line 47, in daclConstants
    FILE_ALL_ACCESS = (ntsecuritycon.STANDARD_RIGHTS_REQUIRED | ntsecuritycon.SYNCHRONIZE | 0x1ff)
NameError: name 'ntsecuritycon' is not defined
```

```[root@saltmom salt]# salt-minion --versions
Salt Version:
           Salt: 2015.8.8

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-229.el7.x86_64
         system: CentOS Linux 7.2.1511 Core```

**Comment by benhosmer** [comment]
I can confirm this is an issue on CentOS 7 as well:

I suspect this `osrelease = float(__grains__.get('osrelease', 0))` from the `rh_service.py` module, https://github.com/saltstack/salt/blob/develop/salt/modules/rh_service.py#L71

is the culprit.

On CenOS 7, `osrelease` is not an int or a float:

```
[root@elk salt]# salt-call grains.get osrelease
[INFO    ] Determining pillar cache
local:
    7.2.1511
[root@elk salt]# salt-call grains.get os
[INFO    ] Determining pillar cache
local:
    CentOS
```

**Comment by artursenk** [comment]
Hi guys, thank you for all your hard work.
How does the progress look on this issue?

We've got problems in our deployment pipelines managed by Salt - because of this issue we have to retry jobs which install RPMs on Centos 7.2 machines, with 2015.8.8.2 they always fail at first attempt. If a job installs two RPMs, we have to retry it 3 times...

I'm asking because I'm considering to build some workaround which would fix this temporarily, but if there is like several days until fix is realeased I wouldn't bother and just wait.

**Comment by benhosmer** [comment]
@artursenk After I fixed this bug on my dev box, I realized it didn't actually affect any thing else and my particular issue was caused by a typo on my part. The error caused by this really wasn't stopping the `pkg` module from working in the first place. 

Even with the un-patched version, I have no problems installing from repos or single rpms using the `pkg` module. Admittedly, my testing has only been with `salt-call` locally. I haven't done an actual master/minion deployment since discovering this bug.

How are you installing your rpms?

Given the SALT release cycle, I don't think you'll see this ported into a release in the next few days.

**Comment by artursenk** [comment]
@benhosmer So, we are using master/minion pattern for deployments - we are calling Saltmaster via its REST API from Jenkins with names and targets of States.
Our boxes (including Saltmaster) are consistent with OS and Saltstack versions:

```
[root@app salt]#            salt-minion --versions
Salt Version:
           Salt: 2015.8.8.2
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.10.1.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
 ```

In the state there is for example:
```
bpmpkgs:
  pkg.latest:
    - pkgs:
      - bpm-service-develop
```

The logs I see on the minion:
```
2016-04-01 10:25:23,764 [salt.loader      ][ERROR   ][25967] Exception raised when processing __virtual__ function for rh_service. Module will not be loaded local variable 'osreleas
e' referenced before assignment
2016-04-01 10:25:23,764 [salt.loader      ][WARNING ][25967] salt.loaded.int.module.rh_service.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or 
a new name. If you're the developer of the module 'rh_service', please fix this.
2016-04-01 10:25:35,479 [salt.state       ][ERROR   ][25967] Made the following changes:
'bpm-service-develop' changed from '0.0.273' to '0.0.274'
```

In the Jenkins job I see:
```
"pkg_|-bpmpkgs_|-bpmpkgs_|-latest":   {
    "comment": "The following packages failed to update: bpm-service-develop",
    "name": "bpmpkgs",
    "start_time": "10:25:24.921005",
    "result": false,
    "duration": 10610.309,
    "__run_num__": 24,
    "changes": {"bpm-service-develop":     {
      "new": "0.0.274",
      "old": "0.0.273"
    }}
  },
```

After retry of this job all is fine, package is upgraded.

**Comment by benhosmer** [comment]
That's strange, I'm using the same versions as you and just tried a test on a minion/master running on the same machine:

```
[vagrant@elk ~]$ salt-master --versions
Salt Version:
           Salt: 2015.8.8.2
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.10.1.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
 
[vagrant@elk ~]$ salt-minion --versions
Salt Version:
           Salt: 2015.8.8.2
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.10.1.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
```

```
apache-latest:
  pkg.latest:
    - pkgs:
      - httpd
```

```----------
          ID: apache-latest
    Function: pkg.latest
      Result: True
     Comment: The following packages were successfully installed/upgraded: httpd
     Started: 10:25:37.684749
    Duration: 20317.146 ms
     Changes:   
              ----------
              httpd:
                  ----------
                  new:
                      2.4.6-40.el7.centos
                  old:
              httpd-tools:
                  ----------
                  new:
                      2.4.6-40.el7.centos
                  old:
              mailcap:
                  ----------
                  new:
                      2.1.41-2.el7
                  old:

Summary for elk.rbtcloud.dev
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
```

I have another state that works fine that doesn't use `pkg.latest` but `pkg.installed` that I was working on all day yesterday that seems to not have any issues either.

Have you tried manually installing your RPM just to verify it _isn't_ salt causing the issue?

**Comment by terminalmage** [comment]
@artursenk There does indeed look to be a problem, given the outcome of your state, but I can absolutely 100% guarantee that this issue is not causing it. This issue cannot possibly cause a pkg state to fail, for a few reasons:

1. CentOS 7 uses systemd.py, _not_ rh_service.py as its `service` module.
2. This error in the log  means that rh_service.py cannot be loaded to provide the `service` module, which because of number 1 above, _doesn't matter_. It's essentially log noise, and nothing else.
3. The state to which you're referring is a `pkg` state, and does not involve service management _at all_.

We can do the following to troubleshoot your issue:

1. Downgrade `bpm-service-develop` to version `0.0.273`.
2. Run `salt <minion-id> pkg.latest_version bpm-service-develop`.
3. Post the output from that command.

**Comment by artursenk** [comment]
OK, I'm confused now @terminalmage. ;)
I did what you asked and the output is simple:

```
minion-id:
    0.0.275-
```

So looks like our devs released new version of this package.

Install works fine in this situation:
```
[root@saltmaster ~]# salt 'minion-id' pkg.install bpm-service-develop
minion-id:
    ----------
    bpm-service-develop:
        ----------
        new:
            0.0.275
        old:
            0.0.273
```

So now I've got no idea why pkg.latest fun from state doesn't work, and pkg.latest run from state by a minion with 2015.8.7 works fine. Pkg.install run from a module also works fine...

I have just found sth interesting in the docs: "Generally it is better for the installed function to be used, as latest will update the package whenever a new package is available." This looks more suitable, so on Monday I will change my state, retry and let you know.
Thx for a help!

**Comment by terminalmage** [comment]
@artursenk Does the version number there really end in a dash? I'd bet that is what is tripping up the `pkg.latest` state. Seems like an improperly-formatted RPM spec file.

**Comment by terminalmage** [comment]
@artursenk can you run `rpm -qi bpm-service-develop` and post the output?

**Comment by terminalmage** [comment]
@artursenk Actually, forget the last request, please instead run `rpm -q --queryformat '%{name}|%{version}|%{release}|%{epoch}\n' bpm-service-develop`.

**Comment by artursenk** [comment]
@terminalmage Yes, these are our internal RPMs, each microservice has its own.
```
[root@app ~]# rpm -q --queryformat '%{name}|%{version}|%{release}|%{epoch}\n' bpm-service-develop
bpm-service-develop|0.0.275||0
```

**Comment by terminalmage** [comment]
@artursenk OK, thanks, I'll take a look at the `pkg.latest_version` function for yum, it's possible that it is not properly handling packages without a `Release` parameter set.

**Comment by artursenk** [comment]
Still important to notice, that it has been working for many months, until I upgraded to 2015.8 or 2015.8.8.2. ;) It still works fine on 2015.8.7 minions.

**Comment by terminalmage** [comment]
Understood. One more command for you to run, though I need you to downgrade to an earlier version first so it shows as an upgrade: `yum --quiet list available bpm-service-develop`

**Comment by artursenk** [comment]
Before downgrading:
```
[root@app ~]# yum --quiet list available bpm-service-develop
Error: No matching Packages to list
```

After downgrading to 274:
```
[root@app ~]# yum --quiet list available bpm-service-develop
Available Packages
bpm-service-develop.x86_64                                                                     0.0.275-                                                                      velocity
```

**Comment by terminalmage** [comment]
Thanks! I think I know what is going on here.

**Comment by terminalmage** [comment]
@artursenk https://github.com/saltstack/salt/pull/32302 fixes this. In the meantime, you can avoid this problem by having the people creating the packages properly set a `Release` param in the spec file used to build the RPMs.

More info in the RPM spec file docs [here](http://www.rpm.org/max-rpm/s1-rpm-build-creating-spec-file.html#S3-RPM-BUILD-PREAMBLE-RELEASE)

Typically this is set to `1` the first time a version is packaged, and then iterated if the version is repackaged (but the actual version number is unchanged). This would result in a version number of `0.0.275-1`.

**Comment by artursenk** [comment]
Thank you @terminalmage!
As you said, setting `release` parameter to `1` solved my problems with `pkg.latest` on 2015.8.8.2. ;)
