### ISSUE TITLE
salt-cloud spitting out error 'AttributeError: 'NoneType' object has no attribute 'pop''

### ISSUE THREAD

**Issue by michael-milan** [saltstack/salt#31749]
### Description of Issue/Question
```
[ERROR   ] Creating 'xx' using 'xxxxx:ec2' as the provider cannot complete since 'ec2' is not available
[ERROR   ] Caught Exception, terminating workers
TRACE: 'NoneType' object has no attribute 'pop'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 55, in _call
    ret = func(*args, **kw)
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 2203, in create_multiprocessing
    output.pop('deploy_kwargs', None)
AttributeError: 'NoneType' object has no attribute 'pop'



Error: There was a query error: Exception caught
Caught Exception, terminating workers
TRACE: 'NoneType' object has no attribute 'pop'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 55, in _call
    ret = func(*args, **kw)
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 2203, in create_multiprocessing
    output.pop('deploy_kwargs', None)
AttributeError: 'NoneType' object has no attribute 'pop'

----------------------------------------------------------------------------------------------
```
           
```
Salt: 2015.5.8
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
         Jinja2: 2.8
       M2Crypto: 0.21.1
 msgpack-python: 0.4.7
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: 4.3
        timelib: Not Installed
       dateutil: 2.4.2
```

**Comment by techhat** [comment]
FYI, this is fixed in the 2015.8 branch in #26170.

**Comment by techhat** [comment]
#31750.

**Comment by michael-milan** [comment]
Thanks, is there any workaround for this for the time being?

**Comment by techhat** [comment]
@michael-milan, I think your best shot is to either patch the file manually or upgrade to the 2015.8 branch. @jfindlay, you have any other others?

**Comment by rallytime** [comment]
I think that's the best route, too. You'll only need to patch the file on the machine(s) you're running salt-cloud commands from.
