### ISSUE TITLE
win_pkg: IndexError: pop from empty list

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#31759]
### Description of Issue/Question

Error message is not helpfull when you get the package name wrong. I would have expect "Error: Package not found" instead of "IndexError: pop from empty list"

In this case 7-Zip should have been 7zip.

```
      ID: standard_winprg_7-Zip
Function: pkg.latest
  Result: False
 Comment: An exception occurred in this state: Traceback (most recent call last):
            File "C:\salt\bin\lib\site-packages\salt\state.py", line 1624, in call
              **cdata['kwargs'])
            File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1491, in wrapper
              return f(*args, **kwargs)
             File "C:\salt\bin\lib\site-packages\salt\states\pkg.py", line 1402, in latest
              **kwargs)
            File "C:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 103, in latest_version
              latest_available = _get_latest_pkg_version(pkg_info)
            File "C:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 1042, in _get_latest_pkg_version
              return sorted(pkginfo, cmp=_reverse_cmp_pkg_versions).pop()
          IndexError: pop from empty list
 Started: 04:55:25.410000
Duration: 207.0 ms
 Changes:

```

```
standard_winprg_7-Zip:
    ----------
    __env__:
        base
    __sls__:
        std_windows
    pkg:
        |_
          ----------
          order:
              502
        |_
          ----------
          pkgs:
              - 7-Zip
```

This line is doing to much it does not allow any checks to be performed to see if items are valid.
**return sorted(pkginfo, cmp=_reverse_cmp_pkg_versions).pop()  **
Hence a python error message (IndexError: pop from empty list) rather than a salt error message of something like "Package not found"

(Side note could not find anywhere in sys.doc or sys.doc_state it says only one package can be listed)

See also #14920 which also has the same bad error message.

Suggest you also look at
```
egrep -R 'return.*pop\(' /usr/lib/python2.7/site-packages/salt
/usr/lib/python2.7/site-packages/salt/modules/boto_vpc.py:        return {'vpc_id': vpc_ids.pop()}
/usr/lib/python2.7/site-packages/salt/modules/ini_manage.py:            return self.pop(self.index(option_to_remove))
/usr/lib/python2.7/site-packages/salt/modules/ini_manage.py:            return self.sections.pop(self.sections.index(section_to_remove))
/usr/lib/python2.7/site-packages/salt/modules/upstart.py:    return result[sorted(result).pop()]
/usr/lib/python2.7/site-packages/salt/modules/win_pkg.py:    return sorted(pkginfo, cmp=_reverse_cmp_pkg_versions).pop()
/usr/lib/python2.7/site-packages/salt/transport/raet.py:        return jobber_rxMsgs.pop(track).get('return', {})
```
@thatch45 Might be worth adding to a checklist that code perform some checks to see if what is expected and what it is returning is correct,  rather than assuming the customer is perfect and never makes a mistake.

### Versions Report
*Provided by running* ``salt --versions-report``
```
C:\salt>salt-call --versions-report
Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.2
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 0.3.7
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist:   <- No Dist i.e. does not say its Windows
        machine: AMD64
        release: 7
         system: 7 6.1.7601 SP1 Multiprocessor Free
```

**Comment by jfindlay** [comment]
@damon-atkins, thanks for reporting.

**Comment by damon-atkins** [comment]
Looks like this has been partially fixed.  Need to retest.
```
def _get_latest_pkg_version(pkginfo):
    if len(pkginfo) == 1:
        return next(six.iterkeys(pkginfo))
    try:
        return sorted(pkginfo, cmp=_reverse_cmp_pkg_versions).pop()
    except IndexError:
        return ''
```

**Comment by twangboy** [comment]
This is the output on the head of 2016.3:

**Comment by damon-atkins** [comment]
@twangboy  Thanks
