### ISSUE TITLE
Beacons in pillar doesn't trigger events

### ISSUE THREAD

**Issue by fredrikaverpil** [saltstack/salt#31766]
### Description of Issue/Question

Defining beacons in pillar won't trigger events in the master bus. Doesn't matter which beacon it is.

I really wish to be able to set beacons up like this. Any idea on workaround?

### Setup

```yaml
# pillar top.sls

base:
  '*':
    - credentials
    # - schedule
{% if grains['kernel'] == 'Linux' %}
    - beacons_linux
{% elif grains['kernel'] == 'Windows' %}
    - beacons_windows
{% endif %}
```

```yaml
# beacons_linux.sls

beacons:
  diskusage:
    - /: 1%
```

```
# /var/log/salt/salt-minion.log

2016-03-09 15:11:28,867 [salt.minion      ][CRITICAL][1081] The beacon errored:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1741, in handle_beacons
    beacons = self.process_beacons(self.functions)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 364, in process_beacons
    return self.beacons.process(b_conf)
  File "/usr/lib/python2.7/site-packages/salt/beacons/__init__.py", line 55, in process
    interval = self._determine_beacon_config(mod, 'interval', b_config)
  File "/usr/lib/python2.7/site-packages/salt/beacons/__init__.py", line 105, in _determine_beacon_config
    config = config_mod[mod].get(val, False)
AttributeError: 'list' object has no attribute 'get'
```

I went and downloaded the latest `diskusage.py` and placed this in `_beacons`. Then I got this error on the minion instead:

```
# /var/log/salt/salt-minion.log

2016-03-09 14:57:45,676 [salt.utils.lazy  ][DEBUG   ][1087] LazyLoaded diskusage.beacon
2016-03-09 14:57:45,676 [salt.beacons     ][DEBUG   ][1087] Unable to process beacon diskusage
2016-03-09 14:57:46,675 [salt.utils.lazy  ][DEBUG   ][1087] LazyLoaded diskusage.beacon
2016-03-09 14:57:46,676 [salt.beacons     ][DEBUG   ][1087] Unable to process beacon diskusage
2016-03-09 14:57:47,675 [salt.utils.lazy  ][DEBUG   ][1087] LazyLoaded diskusage.beacon
2016-03-09 14:57:47,675 [salt.beacons     ][DEBUG   ][1087] Unable to process beacon diskusage
```

The diskusage beacon requires psutil, which is installed on the minion:

```
$ pip list | grep psutil
    psutil (4.0.0)
```

### Steps to Reproduce Issue

Define beacons in pillar, as shown above, and this happens.

### Versions Report

```
Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.2
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.9.0
        timelib: Not Installed

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-123.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
```

**Comment by jfindlay** [comment]
@fredrikaverpil, thanks for reporting.

**Comment by fredrikaverpil** [comment]
I believe this may be a duplicate of https://github.com/saltstack/salt/issues/29451?

**Comment by jfindlay** [comment]
I think you're right.  Thanks, @fredrikaverpil.
