### ISSUE TITLE
salt-ssh UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 9: ordinal not in range(128)

### ISSUE THREAD

**Issue by duk3luk3** [saltstack/salt#31869]
### Description of Issue/Question

`salt/states/user.py` cannot cope with Umlauts. Either the input utf-8 type (from state file / pillar) gets lost, or there is a codec screwup somewhere.

```
          ID: user-present-umlaut
    Function: user.present
        Name: umlaut
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/tmp/.erlacher_f62e6b__salt/salt/state.py", line 1560, in call
                  **cdata['kwargs'])
                File "/tmp/.erlacher_f62e6b__salt/salt/states/user.py", line 384, in present
                  ret['comment'] += '{0}: {1}\n'.format(key, val)
              UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 9: ordinal not in range(128)
     Started: 16:27:23.220108
    Duration: 1.89 ms
     Changes:   

```
### Setup

_Please provide relevant configs and/or SLS files (Be sure to remove sensitive info)._
### Steps to Reproduce Issue

```
me@somewhere:/srv/saltstack$ file states/usertest/init.sls 
states/usertest/init.sls: UTF-8 Unicode text
me@somewhere:/srv/saltstack$ cat states/usertest/init.sls 
umlaut-user:
  user.present:
    - name: ümlaut

me@somewhere:/srv/saltstack$ salt-ssh --refresh --user $(whoami) 'minion' state.sls 'usertest' test=True
minion:
    An Exception occurred while executing state.sls: 'ascii' codec can't encode character u'\xfc' in position 0: ordinal not in range(128)


```
### Versions Report

```
                  Salt: 2015.5.3
                Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: Not Installed
                  RAET: Not Installed
                   ZMQ: Not Installed
                  Mako: Not Installed
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1trusty1
```

**Comment by duk3luk3** [comment]
When the Umlaut is in the fullname and not in the name (uid), the bug reproduces only if the user already exists, because only then it actually tries to put the fullname into the result comment.

**Comment by ssgward** [comment]
@duk3luk3 - thanks for sending this is.

Just out of curiosity, have you tried tried other salt versions or just 2015.5.3?

**Comment by jfindlay** [comment]
This still seems to be a problem on 2016.3, https://github.com/saltstack/salt/blob/v2016.3.0rc1/salt/states/user.py#L459.
