### ISSUE TITLE
virtualenv.managed requirements from salt:// path doesn't work

### ISSUE THREAD

**Issue by iggy** [saltstack/salt#31861]
### Description of Issue/Question

When trying to use the salt:// path support for the virtualenv.managed state, I get an error `CommandExecutionError: No such file or directory '/srv/sopel/requirements.txt'`
### Setup

```
sopel_venv:
  virtualenv.managed:
    - name: /srv/sopel/.virtualenvs/sopel
    - requirements: salt://sopel/files/requirements.txt
    #- requirements: /srv/sopel/requirements.txt
    - cwd: /srv/sopel
    - user: sopel
    - python: python3.4
    - pip_upgrade: True
```

Using `file.managed` to put the file down before the state and switching the requirements path to the local path makes it work.

```
sopel_pip_requirements:
  file.managed:
    - name: /srv/sopel/requirements.txt
    - source: salt://sopel/files/requirements.txt
```
### Error Message

```
----------
          ID: sopel
    Function: virtualenv.managed
        Name: /srv/sopel/.virtualenvs/sopel
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1701, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1619, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/virtualenv_mod.py", line 255, in managed
                  env_vars=env_vars
                File "/usr/lib/python2.7/dist-packages/salt/modules/pip.py", line 591, in install
                  user=user
                File "/usr/lib/python2.7/dist-packages/salt/modules/pip.py", line 312, in _process_requirements
                  __salt__['file.copy'](source_path, target_path)
                File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 2890, in copy
                  raise CommandExecutionError('No such file or directory \'{0}\''.format(src))
              CommandExecutionError: No such file or directory '/srv/sopel/requirements.txt'
     Started: 22:16:44.944270
    Duration: 3051.343 ms
     Changes:
```
### Versions Report

```
Salt Version:
           Salt: 2016.3.0-197-g846e178

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.0.4
           cffi: 1.1.2
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-32-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by jfindlay** [comment]
Thanks for reporting, @iggy.

**Comment by abednarik** [comment]
HI

 The problem is related to the user option. Since is suign a cheched requirements user is not able to read that file.

Here an example.

```yml
sopel_venv:
  virtualenv.managed:
    - name: /tmp/foo
    - requirements: salt://foo/files/requirements.txt
    - cwd: /tmp/foo
    - user: vagrant
    - pip_upgrade: True
```

```bash
[ERROR   ] request files: ['/var/cache/salt/minion/files/base/foo/files/requirements.txt']
[ERROR   ] TREQ N CWD: /tmp/tmpVh13HW -- /tmp/foo -- for requirements.txt
[ERROR   ] Changing ownership of requirements file '/tmp/tmpVh13HW/requirements.txt' to user 'vagrant'
[ERROR   ] /tmp/tmpVh13HW
[ERROR   ] /var/cache/salt/minion/files/base/foo/files/requirements.txt
[ERROR   ] Command '['/tmp/foo/bin/pip', 'install', '--requirement', '/var/cache/salt/minion/files/base/foo/files/requirements.txt', '--upgrade']' failed with return code: 1
[ERROR   ] stderr: Could not open requirements file: [Errno 13] Permission denied: '/var/cache/salt/minion/files/base/foo/files/requirements.txt'
[ERROR   ] retcode: 1
[ERROR   ] virtualenv exists

Could not open requirements file: [Errno 13] Permission denied: '/var/cache/salt/minion/files/base/foo/files/requirements.txt'
```

I will see if I can do something about it.

**Comment by iggy** [comment]
afaik, this is still an issue... will check sometime, but... suck it stalebot

**Comment by gojufhv** [comment]
Seems to still be an issue. If user is set I get this error: "Could not open requirements file: [Errno 13] Permission denied"
salt 3002.5
