### ISSUE TITLE
Salt-Api /ws throwing AttributeError's

### ISSUE THREAD

**Issue by beardedeagle** [saltstack/salt#31873]
### Description of Issue/Question

When using the example python code (websocket-client code) from SaltStack's documentation for the `/ws` endpoint in salt-api I am receiving Handshake status 500 error. On the server the master log shows that the request is generating a AttributeError: 'KnownLengthRFile' object has no attribute '_sock'.
### Setup

/etc/salt/master.d/salt-api.conf:

```
rest_cherrypy:
  port: 8000
  host: 0.0.0.0
  debug: False
  disable_ssl: True
  webhook_disable_auth: True
  webhook_url: /hook
  thread_pool: 100
  socket_queue_size: 30
  expire_responses: True
  max_request_body_size: 1048576
  collect_stats: True
```
### Steps to Reproduce Issue

1.) Install and set up salt-master
2.) Install and setup salt-api
3.) Install ws4py
4.) Use example python code found here: https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html#get--ws-(token)

/var/log/salt/master:

```
...
2016-03-14 09:48:30,209 [cherrypy.error.56276560][ERROR   ][29276] [14/Mar/2016:09:48:30]  Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 102, in run
    hook()
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 62, in __call__
    return self.callback(**self.kwargs)
  File "/usr/lib/python2.7/site-packages/ws4py/server/cherrypyserver.py", line 200, in upgrade
    ws_conn = get_connection(request.rfile.rfile)
  File "/usr/lib/python2.7/site-packages/ws4py/compat.py", line 43, in get_connection
    return fileobj._sock
AttributeError: 'KnownLengthRFile' object has no attribute '_sock'

2016-03-14 09:48:30,210 [cherrypy.error.56276560][ERROR   ][29276] [14/Mar/2016:09:48:30] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 647, in respond
    self.hooks.run('before_request_body')
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 112, in run
    raise exc
AttributeError: 'KnownLengthRFile' object has no attribute '_sock'
...
```

response from server:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "nacl_updated.py", line 642, in GetWebsocketEndpoint
    "cert_reqs": ssl.CERT_NONE})
  File "/usr/local/lib/python2.7/site-packages/websocket/_core.py", line 105, in create_connection
    websock.connect(url, **options)
  File "/usr/local/lib/python2.7/site-packages/websocket/_core.py", line 272, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/usr/local/lib/python2.7/site-packages/websocket/_handshake.py", line 67, in handshake
    status, resp = _get_resp_headers(sock)
  File "/usr/local/lib/python2.7/site-packages/websocket/_handshake.py", line 123, in _get_resp_headers
    raise WebSocketBadStatusException("Handshake status %d", status)
websocket._exceptions.WebSocketBadStatusException: Handshake status 500
```
### Versions Report

```
salt --versions-report
Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: 0.21.0
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.4
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.4.5.el7.x86_64
         system: CentOS Linux 7.2.1511 Core

pip list
...
ws4py (0.3.4)
...
```

websocket-client version:
`websocket-client (0.35.0)`

**Comment by beardedeagle** [comment]
Ok so I did some more research and testing, it seems this issue only occurs if you enable stats reporting. As far as I can see there is no real way to solve this other than to disable stats reporting, which may not be an option for some people.

**Comment by jfindlay** [comment]
@beardedeagle, thanks for reporting.

**Comment by corywright** [comment]
I'm experiencing this too, with a slightly different traceback. I've also narrowed it down to enabling `collect_stats` in the `rest_cherrypy` section.


```yaml
rest_cherrypy:
  port: 8000
  log_access_file: /var/log/salt/api-access.log
  log_error_file: /var/log/salt/api-error.log
  disable_ssl: True
  webhook_disable_auth: True
  collect_stats: True

external_auth:
  auto:
    salt:
      - .*
```

```
$ curl -si localhost:8000/login -H "Accept: application/json" 
           -d username='salt' \
           -d password='testpw' \
           -d eauth='auto'
HTTP/1.1 500 Internal Server Error
Date: Fri, 28 Apr 2017 12:52:15 GMT
Content-Length: 805
Content-Type: text/html;charset=utf-8
Allow: GET, HEAD, POST
Server: CherryPy/3.2.2

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>500 Internal Server Error</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>500 Internal Server Error</h2>
        <p>The server encountered an unexpected condition which prevented it from fulfilling the request.</p>
        <pre id="traceback"></pre>
    <div id="powered_by">
    <span>Powered by <a href="http://www.cherrypy.org">CherryPy 3.2.2</a></span>
    </div>
    </body>
</html>
```

The following traceback appears in the salt-api log:

```pytb  
[27/Apr/2017:15:53:26] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 633, in respond
    self.namespaces(self.config)
  File "/usr/lib/python2.7/dist-packages/cherrypy/lib/reprconf.py", line 115, in __call__
    exit(None, None, None)
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cptools.py", line 446, in __exit__
    tool = getattr(self, name)
AttributeError: 'Toolbox' object has no attribute 'cpstats'
```

If I comment out the `collect_stats:` setting, or set it to `False`, then the requests to salt-api succeed.

**Comment by beardedeagle** [comment]
I haven't been doing anything with salt in some time, but will be coming back here shortly. Has anyone made headway with this?
