### ISSUE TITLE
salt/fileclient.py get_url should include the URL in any error message

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#31890]
### Description of Issue/Question
get_url should include in any error the original URL its trying to fetch, which will help with problem solving.
Thanks
PS Might be worth checking fileclient.py in general that most errors return the filename/url which is the issue.
### Setup
*Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).*

### Steps to Reproduce Issue
```
C:\salt>salt-call.bat pkg.install windowspackage
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
MinionError: Error: HTTP 404: Not Found
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 335, in salt_call
    client.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\call.py", line 53, in run
    caller.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 133, in run
    ret = self.call()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 196, in call
    ret['return'] = func(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 608, in install
    cached_pkg = __salt__['cp.cache_file'](installer, saltenv)
  File "C:\salt\bin\lib\site-packages\salt\modules\cp.py", line 367, in cache_file
    result = __context__['cp.fileclient'].cache_file(path, saltenv)
  File "C:\salt\bin\lib\site-packages\salt\fileclient.py", line 158, in cache_file
    return self.get_url(path, '', True, saltenv)
  File "C:\salt\bin\lib\site-packages\salt\fileclient.py", line 625, in get_url
    raise MinionError('Error: {0}'.format(query['error']))
MinionError: Error: HTTP 404: Not Found
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 335, in salt_call
    client.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\call.py", line 53, in run
    caller.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 133, in run
    ret = self.call()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 196, in call
    ret['return'] = func(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 608, in install
    cached_pkg = __salt__['cp.cache_file'](installer, saltenv)
  File "C:\salt\bin\lib\site-packages\salt\modules\cp.py", line 367, in cache_file
    result = __context__['cp.fileclient'].cache_file(path, saltenv)
  File "C:\salt\bin\lib\site-packages\salt\fileclient.py", line 158, in cache_file
    return self.get_url(path, '', True, saltenv)
  File "C:\salt\bin\lib\site-packages\salt\fileclient.py", line 625, in get_url
    raise MinionError('Error: {0}'.format(query['error']))
salt.exceptions.MinionError: Error: HTTP 404: Not Found
```

### Versions Report
*Provided by running* ``salt --versions-report``
```
Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.2
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 0.3.7
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist:
        machine: AMD64
        release: 8.1
         system: 8.1 6.3.9600  Multiprocessor Free
```

**Comment by jfindlay** [comment]
@damon-atkins, thanks for reporting.  This would be useful to have.
