### ISSUE TITLE
salt looses track of an execution module over time

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#31941]
### Description of Issue/Question

I have an execution module that is shipped via _modules and on which I have a scheduler task (and a crontab on the master to make sure this is not a scheduler problem). 

On the master side I get : 
```
#salt host vcreview.project_stats_by_state
host:
    'vcreview' __virtual__ returned False
```
the module is correctly synced, saltutil.sync_modules comes back empty.

On the minion side it works : 
```
 #salt-call vcreview.project_stats_by_state
[output]
```

after a salt-minion restart it works : 
```
#salt host vcreview.project_stats_by_state
host:
  [output]
```

### Setup

The execution module has the following at the beginning : 

```
try:
    from cwclientlib import cwproxy, builders, cwproxy_for
    HAS_CWCLIENTLIB = True
except ImportError:
    HAS_CWCLIENTLIB = False
try:
    from logilab.common.textutils import unormalize
    HAS_UNORMALIZE = True
except:
    HAS_UNORMALIZE = False

__virtualname__ = 'vcreview'

def __virtual__():
    if HAS_UNORMALIZE and HAS_CWCLIENTLIB:
        return __virtualname__
    return False
```

The python imports work. These python packages have not been changed or removed.

### Steps to Reproduce Issue

The schedule task shows in the salt minion log : 

```
2016-03-17 12:03:09,302 [salt.utils.schedule][ERROR   ][11864] Unhandled exception running vcreview.project_stats_by_state
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/schedule.py", line 668, in handle_func
    message=self.functions.missing_fun_string(func))
  File "/usr/lib/python2.7/dist-packages/salt/utils/error.py", line 36, in raise_error
    raise ex(message)
Exception: 'vcreview' __virtual__ returned False
```

### Versions Report

minion side : 
```
$ salt-call --versions-report
Salt Version:
           Salt: 2015.8.7
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: 1.0.0
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: debian 8.3 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.3 

```

master side
```
# salt --versions-report
Salt Version:
           Salt: 2015.8.7
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: 1.0.0
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: 2.3.0
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: debian 8.3 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.3 
```

**Comment by jfindlay** [comment]
@arthurlogilab, thanks for reporting.  I am not sure what could be happening here.  If you can think of any more information you can provide to help reproduce and fix this, remember to post it here.  @garethgreenaway, do you have any ideas?

**Comment by arthurlogilab** [comment]
Can't think on any extra information. There are three functions in vcreview.py, I'm thinking of spliting them into three separate modules to see if they vanish in the same way, it might narrow down the problem if the problem is in the code.

**Comment by arthurlogilab** [comment]
This just got worse. Splitted it in three modules, now I can't execute from the master at all, even after a restart. The salt-call side works fine. ```sys.list_modules``` doesn't show the modules. Tried a bunch of cache clearing strategies with no luck. 

Tried to clear references in the scheduler pillar in case it tries to lazyload it too soon on startup or something, no luck either. 

Would the salt-call working be due to an environment variable ? Is there a way to test with some sort of ENV=none type mechanism ?

**Comment by jfindlay** [comment]
@arthurlogilab, I'm not really sure what is going on here, but you could try copying your custom modules into `/usr/lib/python2.7/dist-packages/salt/modules`.

**Comment by cachedout** [comment]
Hmmm. Interesting. I'd really like to know _which_ import isn't loading that's causing __virtual__ to return False. This doesn't feel like a bug in salt, at least offhand, but rather something particular to this module. 

I'd like to isolate this failure a little more before we continue debugging on this end. Could you toss some debugging in to see where the import failure is happening?

**Comment by cro** [comment]
I'm wondering if this is and #35443 are the same issue...
