### ISSUE TITLE
SaltStack dockerng cannot modify running container is external process (such as SystemD) is re-starting the container

### ISSUE THREAD

**Issue by timcharper** [saltstack/salt#32030]
### Description of Issue/Question

Given a configuration, such as:

```yaml
consul:
  dockerng.running:
    - restart_policy: always
    - require:
      - service: firewalld
      - service: docker
    - image: voxxit/consul:latest
    - port_bindings:
      - "8300:8300"
      - "8301:8301"
      - "8301:8301/udp"
      - "8302:8302"
      - "8302:8302/udp"
      - "8400:8400"
      - "8500:8500"
      - "53:8600/udp"
    - command: agent -data-dir /data -server -advertise {{private_ip}} -bootstrap-expect {{"%i" % ((peers | length) / 2 + 1)}} -retry-interval 10s -node consul{{grains.local_idx}} -domain bh-staging -client 0.0.0.0 -bind 0.0.0.0 -ui
        {%- for minion_id, ip in peers.items() | sort %}
        {%- if minion_id != grains.id %} -retry-join {{ip}}
        {%- endif %}
        {%- endfor %}
    - binds:
        - consul-data:/data
```

... any attempts for saltstack to modify an existing container will fail with the following:

```
          ID: consul
    Function: dockerng.running
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1624, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1491, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/dockerng.py", line 1658, in running
                  removed_ids = __salt__['dockerng.rm'](name)
                File "/usr/lib/python2.7/site-packages/salt/modules/dockerng.py", line 657, in wrapper
                  returned = wrapped(*args, **salt.utils.clean_kwargs(**kwargs))
                File "/usr/lib/python2.7/site-packages/salt/modules/dockerng.py", line 644, in wrapper
                  return wrapped(name, *args, **salt.utils.clean_kwargs(**kwargs))
                File "/usr/lib/python2.7/site-packages/salt/modules/dockerng.py", line 3352, in rm_
                  _client_wrapper('remove_container', name, v=volumes, force=force)
                File "/usr/lib/python2.7/site-packages/salt/modules/dockerng.py", line 627, in wrapper
                  return wrapped(*args, **salt.utils.clean_kwargs(**kwargs))
                File "/usr/lib/python2.7/site-packages/salt/modules/dockerng.py", line 893, in _client_wrapper
                  exc.explanation)
              CommandExecutionError: Error 409: Conflict, You cannot remove a running container. Stop the container before attempting removal or use -f
     Started: 14:29:31.506301
    Duration: 88791.108 ms
     Changes:
----------
```

If I force remove the container, it can be created again, successfully.

If I force remove the container, and create it without `restart_policy: always`, then attempts saltstack can successfully modify the container configuration on subsequent runs.

My hypothesis is that saltstack is stopping the container, but then docker is probably starting it again. By the point saltstack goes to remove the container / replace the container config, it's already running again. If this issue is insurmountable, then perhaps docs re: the limitation here would be appropriate? Happy to help with either route.

### Versions Report

```yaml
Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.4.4.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
```

- `dockerng` state and module patched with from 553ecaca25271ab394099484d27df5b835098074.
- `docker-py` `1.6.0`

**Comment by timcharper** [comment]
This patch demonstrates a potential resolution (which, I recognize is not the best way to solve it, but at could serve to document the issue I'm encountering)

Patched against 553ecaca25271ab394099484d27df5b835098074

```
diff --git a/salt/patch/docker/states/dockerng.py b/salt/patch/docker/states/dockerng.py
index 3516eda..d81beb6 100644
--- a/salt/patch/docker/states/dockerng.py
+++ b/salt/patch/docker/states/dockerng.py
@@ -1642,19 +1642,23 @@ def running(name,
         if pre_config:
             # Container exists, stop if necessary, then remove and recreate
             if pre_state != 'stopped':
-                result = __salt__['dockerng.stop'](name,
-                                                   timeout=stop_timeout,
-                                                   unpause=True)['result']
-                if result is not True:
-                    comments.append(
-                        'Container was slated to be replaced, but the '
-                        'container could not be stopped.'
-                    )
-                    ret['comment'] = _format_comments(comments)
-                    return ret
+                # Let's just force removal and not stop... because this doesn't
+                # always work (docker will start it again) and stopping then
+                # force rm is slow
+                True
+                # result = __salt__['dockerng.stop'](name,
+                #                                    timeout=stop_timeout,
+                #                                    unpause=True)['result']
+                # if result is not True:
+                #     comments.append(
+                #         'Container was slated to be replaced, but the '
+                #         'container could not be stopped.'
+                #     )
+                #     ret['comment'] = _format_comments(comments)
+                #     return ret

             # Remove existing container
-            removed_ids = __salt__['dockerng.rm'](name)
+            removed_ids = __salt__['dockerng.rm'](name, force=True)
             if not removed_ids:
                 comments.append('Failed to remove container {0}'.format(name))
                 ret['comment'] = _format_comments(comments)
```

**Comment by timcharper** [comment]
I updated the title of this ticket because I realized that SystemD was the cause; I have a SystemD service created to make sure that consul gets started properly on boot / docker restart.

        [Unit]
        Description=Join the swarm
        Requires=consul.service
        After=consul.service

        [Service]
        Restart=always
        ExecStart=/usr/bin/docker start -a registrator
        ExecStop=/usr/bin/docker stop -t 2 registrator

        [Install]
        WantedBy=local.target

**Comment by timcharper** [comment]
I think that, generally, using `rm force=True` is more reliable than attempting to stop the container, but perhaps there are good reasons to not modify the container if it can't be safely stopped.

**Comment by ticosax** [comment]
`force` can be passed from the sls, if it default to `False`, so you don't break backward compatibility.

**Comment by timcharper** [comment]
`Force: true` is documented as follows:

```
    force : False
        Set this parameter to ``True`` to force Salt to re-create the container
        irrespective of whether or not it is configured as desired.
```

That doesn't seem to be the same thing as using force on the `rm` call.

**Comment by ticosax** [comment]
Just reuse it and extend the documentation. `force` exists to bypass docker getting in our way.

**Comment by timcharper** [comment]
I'm not sure if I'm misreading the code or I'm not explaining myself clearly, so I'll try again.

If I understand you correctly (and I don't I do), you're telling me either to extend the documentation and the dockerng state code to cause the `force` parameter to remove the container forcibly.

The problem I see with this approach is this does more than desired. I don't want to forcibly recreate the container if the configuration hasn't changed. The force parameter, as it exists, skips any checking for changes, as seen here:

https://github.com/saltstack/salt/blob/fc1ba937aa9a3485f088a495119cf9629f54b92e/salt/states/dockerng.py#L1582-L1585

**Comment by ticosax** [comment]
You are right. force is not suitable.
Yes it is probably better that you adjust your own restart policy. After all, salt behave like expected.
