### ISSUE TITLE
exception fopen on directory that doesn't exist

### ISSUE THREAD

**Issue by adamsewell** [saltstack/salt#32122]
I'm seeing a recurring error in my logs indicating there was an error when trying to fopen a file that doesn't exist but the error is saying it's a directory. The file that it's trying to open contains a minion name that no longer exists and was removed with the salt-key -d command.
### Log

```
2016-03-23 12:37:49,260 [tornado.application][ERROR   ][26154] Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 230, in wrapper
    yielded = next(result)
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 529, in handle_message
    stream.send(self.serial.dumps(self._auth(payload['load'])))
  File "/usr/lib/python2.7/dist-packages/salt/transport/mixins/auth.py", line 270, in _auth
    with salt.utils.fopen(key_path, 'w+') as fp_:
  File "/usr/lib/python2.7/dist-packages/salt/utils/__init__.py", line 1204, in fopen
    fhandle = open(*args, **kwargs)
IOError: [Errno 21] Is a directory: '/etc/salt/pki/master/minions_pre/nonexistant-minion-name/'
```
### Versions Report

```
Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.4.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: 0.8.2
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-57-generic
         system: Ubuntu 14.04 trusty
```

**Comment by jfindlay** [comment]
@adamsewell, thanks for reporting.  Do you still have the file in question on the system, `/etc/salt/pki/master/minions_pre/nonexistant-minion-name` exist on the system and is it a directory?

**Comment by adamsewell** [comment]
No, the file is not within the minions_pre directory.

**Comment by cachedout** [comment]
By chance does the ID of the minion in question have a trailing slash? :]

**Comment by adamsewell** [comment]
I does not.

**Comment by adamsewell** [comment]
This is still occurring on 2016.3.1

Since there is no file, is there a way to find what database this is in and remove it?
