### ISSUE TITLE
salt-unity stack traces on freesd10

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#32139]
### Description of Issue/Question

When attempting to run salt-unity with salt version 2015.8.8 on freebsd10 I receive the following stack trace:

```
root@ch3ll-bsd10:~ # salt-unity --help
Traceback (most recent call last):
  File "/usr/local/bin/salt-unity", line 9, in <module>
    load_entry_point('salt==2015.8.8', 'console_scripts', 'salt-unity')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 552, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2672, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2345, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2355, in resolve
    raise ImportError(str(exc))
ImportError: 'module' object has no attribute 'salt_unity'
```
### Setup

Install salt version 2015.8.8:

```
root@ch3ll-bsd10:~ # salt --version
salt 2015.8.8 (Beryllium)
```
### Steps to Reproduce Issue
1. install salt version 2015.8.8
2. run `salt-unity --help` or `salt-unity salt '*' test.ping` or any salt-unity command
### Versions Report

```
root@ch3ll-bsd10:~ # salt --versions-report
Salt Version:
           Salt: 2015.8.8

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 2.7.10 (default, Jul 23 2015, 01:22:23)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist:   
        machine: amd64
        release: 10.1-RELEASE-p15
```

**Comment by cachedout** [comment]
How was this installed?

**Comment by Ch3LL** [comment]
Following these instructions: https://docs.saltstack.com/en/latest/topics/installation/freebsd.html

I've tested with both the freebsd upstream repo and saltstack's repo

**Comment by cachedout** [comment]
@cedwards Could this be packing related? I don't see the issue on Linux, FWIW.

**Comment by cedwards** [comment]
/shrug it could be. I don't know enough about `salt-unity` to even know what's missed, and I see no results for `unity` in a docs search to help me along. What is `salt-unity` supposed to do, and how can I do more testing?

**Comment by cachedout** [comment]
It's supposed to be a 'unified' script for all the various salt command. Ex:

```
mp@silver ...salt/salt/states % salt-unity                                                                                                                                     (git)-[2015.8] 
Must pass in a salt command, available commands are:

api
call
cloud
cp
key
main
master
minion
proxy_minion
run
spm
ssh


mp@silver ...salt/salt/states % salt-unity run manage.up                                                                                                                       (git)-[2015.8] 
- silver
```
