### ISSUE TITLE
 Exception from reactor: 'Couldn't obtain fanout table'

### ISSUE THREAD

**Issue by hexedpackets** [saltstack/salt#32147]
I occasionally see this exception when a minion triggers a reactor to run. Its inconsistent and restarting the master daemon seems to resolve it without any code changes. 

Example stack trace:

```
2016-03-25 11:04:32,122 [salt.utils.reactor][ERROR   ][6274] Exception trying to compile reactions: Couldn't obtain fanout table
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/reactor.py", line 113, in reactions
    high.update(self.render_reaction(fn_, tag, data))
  File "/usr/lib/python2.7/site-packages/salt/utils/reactor.py", line 46, in render_reaction
    glob_ref = self.minion.functions['cp.cache_file'](glob_ref)
  File "/usr/lib/python2.7/site-packages/salt/modules/cp.py", line 365, in cache_file
    result = __context__['cp.fileclient'].cache_file(path, saltenv)
  File "/usr/lib/python2.7/site-packages/salt/fileclient.py", line 158, in cache_file
    return self.get_url(path, '', True, saltenv)
  File "/usr/lib/python2.7/site-packages/salt/fileclient.py", line 543, in get_url
    return self.get_file(url, dest, makedirs, saltenv)
  File "/usr/lib/python2.7/site-packages/salt/fileclient.py", line 984, in get_file
    hash_server = self.hash_file(path, saltenv)
  File "/usr/lib/python2.7/site-packages/salt/fileclient.py", line 1224, in hash_file
    return self.channel.send(load)
  File "/usr/lib/python2.7/site-packages/salt/fileserver/__init__.py", line 742, in send
    return getattr(self.fs, cmd)(load)
  File "/usr/lib/python2.7/site-packages/salt/fileserver/__init__.py", line 577, in file_hash
    load['saltenv'])
  File "/usr/lib/python2.7/site-packages/salt/fileserver/__init__.py", line 524, in find_file
    fnd = self.servers[fstr](path, saltenv, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/fileserver/gitfs.py", line 143, in find_file
    return gitfs.find_file(path, tgt_env=tgt_env, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/utils/gitfs.py", line 2141, in find_file
    blob, blob_hexsha = repo.find_file(repo_path, tgt_env)
  File "/usr/lib/python2.7/site-packages/salt/utils/gitfs.py", line 627, in find_file
    tree = self.get_tree(tgt_env)
  File "/usr/lib/python2.7/site-packages/salt/utils/gitfs.py", line 673, in get_tree
    return ref.commit.tree
  File "/usr/lib/python2.7/site-packages/git/refs/symbolic.py", line 183, in _get_commit
    obj = self._get_object()
  File "/usr/lib/python2.7/site-packages/git/refs/symbolic.py", line 176, in _get_object
    return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
  File "/usr/lib/python2.7/site-packages/git/objects/base.py", line 65, in new_from_sha
    oinfo = repo.odb.info(sha1)
  File "/usr/lib/python2.7/site-packages/gitdb/db/base.py", line 205, in info
    return self._db_query(sha).info(sha)
  File "/usr/lib/python2.7/site-packages/gitdb/db/base.py", line 188, in _db_query
    if db.has_object(sha):
  File "/usr/lib/python2.7/site-packages/gitdb/db/pack.py", line 92, in has_object
    self._pack_info(sha)
  File "/usr/lib/python2.7/site-packages/gitdb/db/pack.py", line 75, in _pack_info
    index = item[2](sha)
  File "/usr/lib/python2.7/site-packages/gitdb/pack.py", line 500, in sha_to_index
    return PackIndexFile_sha_to_index(self, sha)
ValueError: Couldn't obtain fanout table
```
### Setup

salt-master.yml snippet:

``` yaml
reactor:
  - 'salt/minion/*/start':
    - salt://reactor/sync.sls
    - salt://reactor/highstate.sls
```

sync.sls:

``` yaml
sync_all:
  local.saltutil.sync_all:
    - tgt: {{ data.get('id') or data['data']['id'] }}
```

highstate.sls:

``` yaml
{%- set minion_id = data.get('id') or data['data']['id'] %}

run_highstate_orch:
  runner.state.orchestrate:
    - mods: orch.startup
    - pillar:
        orch:
          tgt: {{ minion_id }}
```
### Steps to Reproduce Issue

Unsure about exact steps to reproduce at this point, but it happens when a new minion connects and (based on the above event trigger) causes a reactor to be run.
### Versions Report

Master:

```
Salt Version:
           Salt: 2015.8.3

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.1.0
         Python: 2.7.10 (default, Sep  7 2015, 13:51:49)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.3
           cffi: Not Installed
       cherrypy: 3.8.1
       dateutil: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.9.0
        timelib: Not Installed

System Versions:
           dist:
        machine: x86_64
        release: 4.3.0-2-ec2
```

Minion:

```
Salt Version:
           Salt: 2015.8.3

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.5.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.2.0-18-generic
         system: Ubuntu 14.04 trusty
```

**Comment by jfindlay** [comment]
@hexedpackets, thanks for reporting.
