### ISSUE TITLE
RAET is not IPv6 friendly

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#32148]
### Description of Issue/Question
While debugging for another issue I tried RAET but it fails very early on due to me having IPv6: True in my master and minion config.

```
Traceback (most recent call last):
  File "/opt/salt/bin/salt-master", line 25, in <module>
    salt_master()
  File "/opt/salt/lib/python2.7/site-packages/salt/scripts.py", line 47, in salt_master
    master.start()
  File "/opt/salt/lib/python2.7/site-packages/salt/cli/daemons.py", line 207, in start
    self.master.start()
  File "/opt/salt/lib/python2.7/site-packages/salt/daemons/flo/__init__.py", line 100, in start
    consolepath=consolepath,
  File "/opt/salt/lib/python2.7/site-packages/ioflo/app/run.py", line 138, in run
    skedder.run()
  File "/opt/salt/lib/python2.7/site-packages/ioflo/base/skedding.py", line 273, in run
    status = tasker.runner.send(tasker.desire)
  File "/opt/salt/lib/python2.7/site-packages/ioflo/base/framing.py", line 630, in makeRunner
    self.enterAll() #activates, resets .done state also .desire may change here
  File "/opt/salt/lib/python2.7/site-packages/ioflo/base/framing.py", line 411, in enterAll
    self.enter(self.actives)
  File "/opt/salt/lib/python2.7/site-packages/ioflo/base/framing.py", line 423, in enter
    frame.enter()
  File "/opt/salt/lib/python2.7/site-packages/ioflo/base/framing.py", line 1244, in enter
    act() #call entryAction
  File "/opt/salt/lib/python2.7/site-packages/ioflo/base/acting.py", line 99, in __call__
    return (self.actor(**self.parms))
  File "/opt/salt/lib/python2.7/site-packages/ioflo/base/acting.py", line 526, in __call__
    return self.action(**kwa)
  File "/opt/salt/lib/python2.7/site-packages/salt/daemons/flo/core.py", line 315, in action
    bufcnt=bufcnt)
  File "/opt/salt/lib/python2.7/site-packages/raet/road/stacking.py", line 140, in __init__
    prikey=prikey, )
  File "/opt/salt/lib/python2.7/site-packages/raet/road/estating.py", line 195, in __init__
    super(LocalEstate, self).__init__( **kwa)
  File "/opt/salt/lib/python2.7/site-packages/raet/road/estating.py", line 61, in __init__
    host = socket.gethostbyname(host)
socket.gaierror: [Errno 7] no address for the specified node name
```

The value of host (after more debugging) is '::' so the IPv6 equivalent of 0.0.0.0, but socket.gethostbyname is not IPv6 ready unless you set it up to be so. 

### Setup
Any working setup with IPv6 enabled.

### Steps to Reproduce Issue
Setup salt-master and salt-minion, switch to IPv6 and check it still works with ZeroMQ over IPv6.
Then switch to RAET.

### Versions Report
```yaml
Salt Version:
           Salt: 2016.3.0rc1-112-g1af2e41

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.22
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.1
         Python: 2.7.11 (default, Mar 18 2016, 13:38:08)
           RAET: 0.6.5
        Tornado: 4.3
            ZMQ: 4.1.3
           cffi: Not Installed
       cherrypy: 3.8.0
       dateutil: 2.4.0
          gitdb: 0.6.4
      gitpython: 1.0.2
          ioflo: 1.5.1
        libgit2: Not Installed
        libnacl: 1.4.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 2.0.2
          smmap: 0.9.0
        timelib: 0.2.4

System Versions:
           dist:
        machine: i86pc
        release: 5.11
         system: SunOS
        version: Not Installed
```

**Comment by cachedout** [comment]
This would be better filed against the RAET project, I think: https://github.com/saltstack/raet

**Comment by sjorge** [comment]
Done, #74 over at the RAET repo.
