### ISSUE TITLE
NameError: name 'ntsecuritycon' is not defined on Debian minions

### ISSUE THREAD

**Issue by boltronics** [saltstack/salt#32203]
I'm getting the following errors in minion log files since upgrading to 2015.8.8+ds-1 today on Debian Jessie (amd64) using the official Salt repository:
```
2016-03-29 18:54:42,960 [salt.loader                                          ][ERROR   ][356] Failed to import module win_dacl, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1136, in _load_module
    ), fn_, fpath, desc)
  File "/usr/lib/python2.7/dist-packages/salt/modules/win_dacl.py", line 39, in <module>
    class daclConstants(object):
  File "/usr/lib/python2.7/dist-packages/salt/modules/win_dacl.py", line 47, in daclConstants
    FILE_ALL_ACCESS = (ntsecuritycon.STANDARD_RIGHTS_REQUIRED | ntsecuritycon.SYNCHRONIZE | 0x1ff)
NameError: name 'ntsecuritycon' is not defined
2016-03-29 18:54:58,846 [salt.loader                                          ][ERROR   ][367] Failed to import module win_dacl, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1136, in _load_module
    ), fn_, fpath, desc)
  File "/usr/lib/python2.7/dist-packages/salt/modules/win_dacl.py", line 39, in <module>
    class daclConstants(object):
  File "/usr/lib/python2.7/dist-packages/salt/modules/win_dacl.py", line 47, in daclConstants
    FILE_ALL_ACCESS = (ntsecuritycon.STANDARD_RIGHTS_REQUIRED | ntsecuritycon.SYNCHRONIZE | 0x1ff)
NameError: name 'ntsecuritycon' is not defined
```
I don't have any Windows machines on the network, so I'm guessing that's not normal. This seems to happen on startup.

For completeness:
```
$ sudo salt-call --versions-report
Salt Version:
           Salt: 2015.8.8
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: debian 8.3 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.3 
 
$
```

**Comment by jfindlay** [comment]
@boltronics, thanks for reporting.  This is a duplicate of #32004.  An updated version of 2015.8.8 that fixes this can be found in the saltstack repo.
