### ISSUE TITLE
log/handlers/sentry_mod.py : AttributeError: 'module' object has no attribute 'load'

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#32265]
### Description of Issue/Question

Traceback when python-raven is upgraded (no more load dictionnary, uses dsn attribute only)

I believe returners/sentry_return.py might have the same problem (we use a custom sentry_return).
### Setup

```
# cat /etc/salt/minion.d/log_to_sentry.conf 
sentry_handler:
  dsn: https:xxxxx
```
### Steps to Reproduce Issue

```

salt-call: error: Error while processing <bound method SaltCall.__setup_extended_logging of <salt.cli.call.SaltCall object at 0x7f8ba84cb950>>: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 181, in parse_args
    mixin_after_parsed_func(self)
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 728, in __setup_extended_logging
    log.setup_extended_logging(self.config)
  File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 657, in setup_extended_logging
    handlers = get_handlers_func()
  File "/usr/lib/python2.7/dist-packages/salt/log/handlers/sentry_mod.py", line 119, in setup_handlers
    dsn_config = raven.load(dsn)
AttributeError: 'module' object has no attribute 'load'
```
### Versions Report

```
# salt-call --versions-report
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: debian 8.3 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.3 
```

python-raven version : 5.11.2-1

Downgraded back to python-raven 5.2.0-1 to avoid this traceback.

**Comment by arthurlogilab** [comment]
oh, and by the way, python-raven is not picked up by --versions-report, is that a bug ?

**Comment by jfindlay** [comment]
@arthurlogilab, thanks for reporting.  I don't know of any official policy on what to include in the versions report.  Salt has enough dependencies that including all of them would not be useful, especially if they all appear in the result even when not installed.
