### ISSUE TITLE
salt.runner in an orchestration state ignores saltenv 

### ISSUE THREAD

**Issue by hoonetorg** [saltstack/salt#32318]
### Description of Issue/Question

if a orchestration runner is called within an orchestration state the saltenv is ignored.
Also the run is assumed 'succeeded'.
### Setup

openstack/orchestration.sls (in environment os_example_org):

```
openstack_orchestrate__galera:
 salt.runner:
   - name: state.orchestrate
   - mods: mysql.orchestration.server
   - saltenv: "os_example_org"
```

(mysql.orchestration.server is also in env os_example_org)
### Steps to Reproduce Issue

```
salt-call -l all state.sls openstack.orchestration saltenv='os_example_org'
```

```
install.os.example.org_master:
----------
          ID: openstack_orchestrate__galera
    Function: salt.runner
        Name: state.orchestrate
      Result: True
     Comment: Runner function 'state.orchestrate' executed.
     Started: 02:46:59.793849
    Duration: 2830.889 ms
     Changes:   
              ----------
              data:
                  ----------
                  install.os.example.org_master:
                      - No matching sls found for 'mysql.orchestration.server' in env 'base'
              outputter:
                  highstate

Summary
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
```

if I copy mysql/orchestration/server.sls over into base environment, it is at least recognized, but fails for obvious reasons(pillars missing):

```
install.os.example.org_master:
----------
          ID: openstack_orchestrate__galera
    Function: salt.runner
        Name: state.orchestrate
      Result: True
     Comment: Runner function 'state.orchestrate' executed.
     Started: 02:56:06.993859
    Duration: 5449.702 ms
     Changes:   
              ----------
              data:
                  ----------
                  install.os.example.org_master:
                      ----------
                      salt_|-mysql_orchestration_server__clustercheck_|-mysql_orchestration_server__clustercheck_|-state:
                          ----------
                          __run_num__:
                              4
                          __sls__:
                              mysql.orchestration.server
                          changes:
                              ----------
                          comment:
                              One or more requisite failed: mysql.orchestration.server.mysql_orchestration_server__clustercheckuser
                          duration:
                          result:
                              False
                          start_time:
                      salt_|-mysql_orchestration_server__clustercheckuser_|-mysql_orchestration_server__clustercheckuser_|-state:
                          ----------
                          __run_num__:
                              3
                          __sls__:
                              mysql.orchestration.server
                          changes:
                              ----------
                          comment:
                              One or more requisite failed: mysql.orchestration.server.mysql_orchestration_server__dbmgmt
                          duration:
                          result:
                              False
                          start_time:
                      salt_|-mysql_orchestration_server__dbmgmt_|-mysql_orchestration_server__dbmgmt_|-state:
                          ----------
                          __run_num__:
                              2
                          __sls__:
                              mysql.orchestration.server
                          changes:
                              ----------
                          comment:
                              One or more requisite failed: mysql.orchestration.server.mysql_orchestration_server__pcs
                          duration:
                          result:
                              False
                          start_time:
                      salt_|-mysql_orchestration_server__nodes_server_|-mysql_orchestration_server__nodes_server_|-state:
                          ----------
                          __run_num__:
                              0
                          changes:
                              ----------
                          comment:
                              An exception occurred in this state: Traceback (most recent call last):
                                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1564, in call
                                  **cdata['kwargs'])
                                File "/usr/lib/python2.7/site-packages/salt/states/saltmod.py", line 267, in state
                                  for state_item in six.itervalues(m_ret):
                                File "/usr/lib/python2.7/site-packages/salt/ext/six.py", line 569, in itervalues
                                  return iter(d.itervalues(**kw))
                              AttributeError: 'list' object has no attribute 'itervalues'
                          duration:
                              2444.772 ms
                          name:
                              mysql_orchestration_server__nodes_server
                          result:
                              False
                          start_time:
                              02:56:09.505187
                      salt_|-mysql_orchestration_server__pcs_|-mysql_orchestration_server__pcs_|-state:
                          ----------
                          __run_num__:
                              1
                          __sls__:
                              mysql.orchestration.server
                          changes:
                              ----------
                          comment:
                              One or more requisite failed: mysql.orchestration.server.mysql_orchestration_server__nodes_server
                          duration:
                          result:
                              False
                          start_time:
              outputter:
                  highstate

Summary
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
```
### Versions Report

```
salt --versions-report
           Salt: 2015.5.8
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.7
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: Not Installed
```

**Comment by hoonetorg** [comment]
same in version:
```
salt --versions-report
Salt Version:
           Salt: 2015.8.8.2
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.13.1.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
 
```

**Comment by jfindlay** [comment]
@hoonetorg, thanks for the report.

**Comment by hoonetorg** [comment]
OMG: This stuff is working if I call an orchestration like a normal state on the master.

Even if it's not meant to work like this, please don't destroy that functionality in boron or point releases of 2015.8 until this bug is fixed. :pray::pray::pray:

Calling an orchestration state like a nomal state seems to be possible from cmdline:
Instead of calling:
```
salt-run state.orchestrate ceph.orchestration.server saltenv='os_example_org' test='True'
```
I do
```
salt-call state.sls ceph.orchestration.server saltenv='os_example_org' test='True'
```
and get following output
```
[INFO    ] Determining pillar cache
[INFO    ] Determining pillar cache
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'os_example_org', ** done ** u'ceph/orchestration/server.sls'
[INFO    ] Running state [ceph_orchestration__install] at time 20:53:27.764355
[INFO    ] Executing state salt.state for ceph_orchestration__install
[INFO    ] States ran successfully. No changes made to os4.os.example.org, os3.os.example.org, os2.os.example.org, os1.os.example.org.
[INFO    ] Completed state [ceph_orchestration__install] at time 20:54:25.010727
[INFO    ] Running state [ceph_orchestration__cephconf] at time 20:54:25.012554
[INFO    ] Executing state salt.state for ceph_orchestration__cephconf
[INFO    ] {'ret': {'os4.os.example.org': {'file_|-ceph_cephconf__conf_|-/etc/ceph/ceph.conf_|-managed': {'comment': 'The file /etc/ceph/ceph.conf is set to be changed', 'name': '/etc/ceph/ceph.conf', 'start_time': '20:54:30.068340', 'result': None, 'duration': 136.364, '__run_num__': 0, 'changes': {'newfile': '/etc/ceph/ceph.conf'}}}, 'os3.os.example.org': {'file_|-ceph_cephconf__conf_|-/etc/ceph/ceph.conf_|-managed': {'comment': 'The file /etc/ceph/ceph.conf is set to be changed', 'name': '/etc/ceph/ceph.conf', 'start_time': '20:54:50.242332', 'result': None, 'duration': 126.206, '__run_num__': 0, 'changes': {'newfile': '/etc/ceph/ceph.conf'}}}, 'os2.os.example.org': {'file_|-ceph_cephconf__conf_|-/etc/ceph/ceph.conf_|-managed': {'comment': 'The file /etc/ceph/ceph.conf is set to be changed', 'name': '/etc/ceph/ceph.conf', 'start_time': '20:54:51.627555', 'result': None, 'duration': 62.865, '__run_num__': 0, 'changes': {'newfile': '/etc/ceph/ceph.conf'}}}, 'os1.os.example.org': {'file_|-ceph_cephconf__conf_|-/etc/ceph/ceph.conf_|-managed': {'comment': 'The file /etc/ceph/ceph.conf is set to be changed', 'name': '/etc/ceph/ceph.conf', 'start_time': '20:54:51.682983', 'result': None, 'duration': 72.366, '__run_num__': 0, 'changes': {'newfile': '/etc/ceph/ceph.conf'}}}}, 'out': 'highstate'}
[INFO    ] Completed state [ceph_orchestration__cephconf] at time 20:54:51.891646
local:
----------
          ID: ceph_orchestration__install
    Function: salt.state
      Result: True
     Comment: States ran successfully. No changes made to os4.os.example.org, os3.os.example.org, os2.os.example.org, os1.os.example.org.
     Started: 20:53:27.764355
    Duration: 57246.372 ms
     Changes:   
----------
          ID: ceph_orchestration__cephconf
    Function: salt.state
      Result: None
     Comment: States ran successfully. Updating os4.os.example.org, os3.os.example.org, os2.os.example.org, os1.os.example.org.
     Started: 20:54:25.012554
    Duration: 26879.092 ms
     Changes:   
              os4.os.example.org:
              ----------
                        ID: ceph_cephconf__conf
                  Function: file.managed
                      Name: /etc/ceph/ceph.conf
                    Result: None
                   Comment: The file /etc/ceph/ceph.conf is set to be changed
                   Started: 20:54:30.068340
                  Duration: 136.364 ms
                   Changes:   
                            ----------
                            newfile:
                                /etc/ceph/ceph.conf
              
              Summary for os4.os.example.org
              ------------
              Succeeded: 1 (unchanged=1, changed=1)
              Failed:    0
              ------------
              Total states run:     1
              os3.os.example.org:
              ----------
                        ID: ceph_cephconf__conf
                  Function: file.managed
                      Name: /etc/ceph/ceph.conf
                    Result: None
                   Comment: The file /etc/ceph/ceph.conf is set to be changed
                   Started: 20:54:50.242332
                  Duration: 126.206 ms
                   Changes:   
                            ----------
                            newfile:
                                /etc/ceph/ceph.conf
              
              Summary for os3.os.example.org
              ------------
              Succeeded: 1 (unchanged=1, changed=1)
              Failed:    0
              ------------
              Total states run:     1
              os2.os.example.org:
              ----------
                        ID: ceph_cephconf__conf
                  Function: file.managed
                      Name: /etc/ceph/ceph.conf
                    Result: None
                   Comment: The file /etc/ceph/ceph.conf is set to be changed
                   Started: 20:54:51.627555
                  Duration: 62.865 ms
                   Changes:   
                            ----------
                            newfile:
                                /etc/ceph/ceph.conf
              
              Summary for os2.os.example.org
              ------------
              Succeeded: 1 (unchanged=1, changed=1)
              Failed:    0
              ------------
              Total states run:     1
              os1.os.example.org:
              ----------
                        ID: ceph_cephconf__conf
                  Function: file.managed
                      Name: /etc/ceph/ceph.conf
                    Result: None
                   Comment: The file /etc/ceph/ceph.conf is set to be changed
                   Started: 20:54:51.682983
                  Duration: 72.366 ms
                   Changes:   
                            ----------
                            newfile:
                                /etc/ceph/ceph.conf
              
              Summary for os1.os.example.org
              ------------
              Succeeded: 1 (unchanged=1, changed=1)
              Failed:    0
              ------------
              Total states run:     1

Summary for local
------------
Succeeded: 2 (unchanged=1, changed=1)
Failed:    0
------------
Total states run:     2
```

which perfectly does what "salt-run state.orchestrate" would do.

This brought me to the idea to call an orchestration state like a normal state within an orchestration state (tgt: the salt-master) like this (the rendered version):

```
openstack_orchestrate__ceph:
  salt.state:
    - tgt: install.os.example.org
    - expect_minions: True
    - sls: ceph.orchestration.server
    - timeout: 1600
    - saltenv: "os_example_org"

#openstack_orchestrate__galera:
#  salt.runner:
#    - name: state.orchestrate
#    - mods: mysql.orchestration.server
#    - saltenv: "os_example_org"
...
```
and  it works like a charm:

```
salt-run --timeout 1800 --force-color state.orchestrate openstack.orchestration saltenv='os_example_org'
[ERROR   ] Rendering exception occurred: Jinja variable 'dict object' has no attribute 'install.os.example.org_master'
[CRITICAL] Rendering SLS 'netcfg.install' failed, render error:
Jinja variable 'dict object' has no attribute 'install.os.example.org_master'
[CRITICAL] Pillar render error: Rendering SLS 'netcfg.install' failed. Please see master log for details.
install.os.example.org_master:
----------
          ID: openstack_orchestrate__ceph
    Function: salt.state
      Result: True
     Comment: States ran successfully. Updating install.os.example.org.
     Started: 21:29:02.683815
    Duration: 68159.462 ms
     Changes:   
              install.os.example.org:
              ----------
                        ID: ceph_orchestration__install
                  Function: salt.state
                    Result: True
                   Comment: States ran successfully. No changes made to os4.os.example.org, os3.os.example.org, os2.os.example.org, os1.os.example.org.
                   Started: 21:29:07.559435
                  Duration: 31595.395 ms
                   Changes:   
              ----------
                        ID: ceph_orchestration__cephconf
                  Function: salt.state
                    Result: True
                   Comment: States ran successfully. Updating os1.os.example.org. No changes made to os4.os.example.org, os3.os.example.org, os2.os.example.org.
                   Started: 21:29:39.155760
                  Duration: 31540.141 ms
                   Changes:   
                            os1.os.example.org:
                            ----------
                                      ID: ceph_cephconf__conf
                                Function: file.managed
                                    Name: /etc/ceph/ceph.conf
                                  Result: True
                                 Comment: File /etc/ceph/ceph.conf updated
                                 Started: 21:30:10.485729
                                Duration: 70.195 ms
                                 Changes:   
                                          ----------
                                          diff:
                                              --- 
                                              +++ 
                                              @@ -1,5 +1,4 @@
                                               [client]
                                              -#blub
                                               rbd_cache=true
                                               rbd_cache_size=134217728
                                               rbd_cache_writethrough_until_flush=true
                            
                            Summary for os1.os.example.org
                            ------------
                            Succeeded: 1 (changed=1)
                            Failed:    0
                            ------------
                            Total states run:     1
              
              Summary for install.os.example.org
              ------------
              Succeeded: 2 (changed=1)
              Failed:    0
              ------------
              Total states run:     2

Summary for install.os.example.org_master
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
```

version:
```
Salt Version:
           Salt: 2015.8.8.2
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.13.1.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
```

**Comment by UtahDave** [comment]
I just tested this in 2016.11.5 and it's now working. I'm going to close.  Please comment here if we need to review this further.

**Comment by gaetanquentin** [comment]
@UtahDave Can you explain what you have tested exactly?

**Comment by RSpeaker-FD** [comment]
I'm seeing this behavior, or similar, in minion version 2017.7.2 and server version 2018.3.2.  Note there is a lot more to this orchestration, but is commented out for quicker test results.

root@minion1:/# salt-call state.orchestrate states.core.database.oracle.ora11204ee_psu_orch saltenv='rspeaker'

[ERROR   ] Template was specified incorrectly: False
local:
    ----------
    data:
        ----------
        minion1:
            - No matching salt environment for environment 'rspeaker' found
            - No matching sls found for 'states.core.database.oracle.ora11204ee_psu_orch' in env 'rspeaker'
    outputter:
        highstate
    retcode:
        1



root@minion1:/# salt-call state.apply states.core.database.oracle.ora11204ee_psu_orch saltenv=rspeaker

local:
----------
          ID: welcome_banner_abcdefg
    Function: cmd.run
        Name: echo "Starting - `date`" > /tmp/ora11204ee_psuOrch.log
      Result: True
     Comment: Command "echo "Starting - `date`" > /tmp/ora11204ee_psuOrch.log" run
     Started: 11:55:49.452040
    Duration: 42.32 ms
     Changes:
              ----------
              pid:
                  46399692
              retcode:
                  0
              stderr:
              stdout:
----------
          ID: exit_banner_abcdefg
    Function: cmd.run
        Name: echo "Finished - `date`" >> /tmp/ora11204ee_psuOrch.log
      Result: True
     Comment: Command "echo "Finished - `date`" >> /tmp/ora11204ee_psuOrch.log" run
     Started: 11:55:49.494769
    Duration: 37.884 ms
     Changes:
              ----------
              pid:
                  46399694
              retcode:
                  0
              stderr:
              stdout:
----------
          ID: display_summary_abcdefg
    Function: cmd.run
        Name: cat /tmp/ora11204ee_psuOrch.log
      Result: True
     Comment: Command "cat /tmp/ora11204ee_psuOrch.log" run
     Started: 11:55:49.533086
    Duration: 37.029 ms
     Changes:
              ----------
              pid:
                  28770486
              retcode:
                  0
              stderr:
              stdout:
                  Starting - Wed Jun 26 11:55:49 EDT 2019
                  Finished - Wed Jun 26 11:55:49 EDT 2019

Summary for local
------------
Succeeded: 3 (changed=3)
Failed:    0
------------
Total states run:     3
Total run time: 117.233 ms


state.orchestrate fails, state.apply runs.

**Comment by mbochenk** [comment]
I am observing the same behaviour in 2019.2.2 - saltenv/pillarenv setting is completely ignored and `base` is always used. 
In short, when I run `salt-run state.orch some.state saltenv=someenv` I always get `base` instead of `someenv`
