### ISSUE TITLE
reg.read_key interprets substring as special character (\007 as ^G)

### ISSUE THREAD

**Issue by svenehret** [saltstack/salt#32351]
### Description of Issue/Question
`reg.read_key` (or jinja?) interprets substring `\007` as special character `^G` (and possibly others), thus a key containing this substring can never be found.

Thinkable workarounds perhaps indicated further problems on their own:
- using slashes instead of backslashes does not seem to work (```salt['reg.read_key']('HKEY_LOCAL_MACHINE', 'Software/Microsoft/Windows NT/CurrentVersion/Perflib/007/Counter')``` yields ```Cannot find key```. File path specifications are usuable with both backslashes and backslashes).
- I tried joining `\` and `007` separately, but `reg.read_key` does not seem to work with trailing backslashes.

### Steps to Reproduce Issue
a formula like this should read the Windows registry hive and display its contents:
```saltstack
{% set rdcounter = salt['reg.read_key']('HKEY_LOCAL_MACHINE', 'Software\Microsoft\Windows NT\CurrentVersion\Perflib\007\Counter') %}
bla:
  cmd.run:
    - name: "echo {{ rdcounter }}"
```
Instead of the registry hive contents, the following error message will be displayed:
```saltstack
----------
          ID: bla
    Function: cmd.run
        Name: echo {'comment': 'Cannot find key: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Perflib^G\Counter', 'vdata': None, 'vname': '(Default)', 'success': False, 'hive': 'HKEY_LOCAL_MACHINE', 'key': 'Software\Microsoft\Windows NT\CurrentVersion\Perflib^G\Counter'}
      Result: None
     Comment: Command "echo {'comment': 'Cannot find key: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Perflib^G\Counter', 'vdata': None, 'vname': '(Default)', 'success': False, 'hive': 'HKEY_LOCAL_MACHINE', 'key': 'Software\Microsoft\Windows NT\CurrentVersion\Perflib^G\Counter'}" would have been executed
     Started: 09:59:51.069000
    Duration: 1.0 ms
     Changes:   
```

## Master
Salt Version:
           Salt: 2015.8.8.2
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: debian 8.4 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.4

**Comment by jfindlay** [comment]
@svenehret, thanks for reporting.  Python's solution to a problem like this is the raw string specifier, `r''`, but this does not seem to work in jinja:
```sls
# cat /srv/salt/test.sls
{% set rdcounter = r'Software\Microsoft\Windows NT\CurrentVersion\Perflib\007\Counter' %}

bla:
  cmd.run:
    - name: "echo {{ rdcounter }}"
```
```console
# salt jmoney-main state.apply test
jmoney-main:
    Data failed to compile:
----------
    Rendering SLS 'base:test' failed: Jinja syntax error: expected token 'end of statement block', got 'string'; line 1

---
{% set rdcounter = r'Software\Microsoft\Windows NT\CurrentVersion\Perflib\007\Counter' %}    <======================

bla:
  cmd.run:
    - name: "echo {{ rdcounter }}"
---
ERROR: Minions returned with non-zero exit code
```

**Comment by m03** [comment]
@svenehret Seems like the back-slashes just need to be escaped (\\\\) properly here?  Here's an example that works (I created the "HKLM:\SOFTWARE\007\Test" path for the test, since I'm not sure which counters needed to be loaded in order to create your example path):

Here's the test state:
```
{% set rdcounter = salt['reg.read_key']('HKLM', 'SOFTWARE\\007\\Test')  %}

bla:
  cmd.run:
    - name: echo {{ rdcounter.vdata }}
```

Results:

```
m03@devmaster01:/srv/salt/state$ sudo salt 'win2012r2-minion' state.sls test_read_key

win2012r2-minion:
----------
          ID: bla
    Function: cmd.run
        Name: echo None
      Result: True
     Comment: Command "echo None" run
     Started: 18:42:17.210000
    Duration: 15.0 ms
     Changes:
              ----------
              pid:
                  3352
              retcode:
                  0
              stderr:
              stdout:
                  None

Summary for win2012r2-minion
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
```

**Comment by svenehret** [comment]
@m03, thank you very much, the following line works well:
```` saltstack
{% set rdcounter = salt['reg.read_value']('HKEY_LOCAL_MACHINE', 'SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Perflib\\009', 'Counter').vdata %}
````
My original registry key (`007`) does not load because of unicode errors, but I think in this particular case I can work with the other one (`009`).

For the curious: the exception is like this
```` saltstack
    Rendering SLS superformula failed, render error: while parsing a block mapping
  in "<unicode string>", line 114, column 7:
        - name: "echo [u'1', u'1847', u'2' ... 
          ^
expected <block end>, but found '<scalar>'
  in "<unicode string>", line 114, column 9442:
     ...  Fehler', u'590', u'Empfangene ""Ziel nicht erreichbar""-Meldung ... 
                                         ^
Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt\state.py", line 2672, in render_state
    sls, rendered_sls=mods
  File "c:\salt\bin\lib\site-packages\salt\template.py", line 95, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "c:\salt\bin\lib\site-packages\salt\renderers\yaml.py", line 51, in render
    data = load(yaml_data, Loader=get_yaml_loader(argline))
  File "c:\salt\bin\lib\site-packages\yaml\__init__.py", line 71, in load
    return loader.get_single_data()
  File "c:\salt\bin\lib\site-packages\yaml\constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "c:\salt\bin\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "c:\salt\bin\lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "c:\salt\bin\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "c:\salt\bin\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "c:\salt\bin\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "c:\salt\bin\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "c:\salt\bin\lib\site-packages\yaml\composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "c:\salt\bin\lib\site-packages\yaml\composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "c:\salt\bin\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "c:\salt\bin\lib\site-packages\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "c:\salt\bin\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "c:\salt\bin\lib\site-packages\yaml\parser.py", line 439, in parse_block_mapping_key
    "expected <block end>, but found %r" % token.id, token.start_mark)
ParserError: while parsing a block mapping
  in "<unicode string>", line 114, column 7:
        - name: "echo [u'1', u'1847', u'2' ... 
          ^
expected <block end>, but found '<scalar>'
  in "<unicode string>", line 114, column 9442:
     ...  Fehler', u'590', u'Empfangene ""Ziel nicht erreichbar""-Meldung ... 
                                         ^
````
