### ISSUE TITLE
__salt__ dunder is malformed in 2015.5 branch for functions overridden using the "providers" option

### ISSUE THREAD

**Issue by terminalmage** [saltstack/salt#32424]
### Setup

Set alternate provider for service in minion config:

```yaml
providers:
  service: service
```

### Steps to Reproduce Issue

Run ``service.restart`` on a service. This will result in a traceback:

```
Passed invalid arguments: list indices must be integers, not str
Traceback (most recent call last):
  File "/home/erik/salt/salt/cli/caller.py", line 138, in call
    ret['return'] = func(*args, **kwargs)
  File "/home/erik/salt/salt/modules/service.py", line 113, in restart
    return not __salt__['cmd.retcode'](cmd, python_shell=False)
TypeError: list indices must be integers, not str
```

### Versions Report

Salt version: 2015.5.9-255-g690addf

**Comment by terminalmage** [comment]
Fixed with a couple commits added to https://github.com/saltstack/salt/pull/32421
