### ISSUE TITLE
Feature Request - jobs runner list by target

### ISSUE THREAD

**Issue by justindesilets** [saltstack/salt#32444]
I would like to request an addition to the jobs runner that will allow you to list jobs by target or hostname.

@basepi

**Comment by basepi** [comment]
I'm going to throw this together next week.

**Comment by basepi** [comment]
Oh, this is supported. `salt-run jobs.list_jobs search_target=<hostname>`

**Comment by BlaineAtAffirm** [comment]
This functionality isn't working in salt 2015.10 . I get a traceback and no other results. 

```
Exception occurred in runner jobs.list_jobs: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 341, in low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/runners/jobs.py", line 354, in list_jobs
    if fnmatch.fnmatch(ret[item]['Target'], key):
  File "/usr/lib/python2.7/fnmatch.py", line 43, in fnmatch
    return fnmatchcase(name, pat)
  File "/usr/lib/python2.7/fnmatch.py", line 79, in fnmatchcase
    return _cache[pat].match(name) is not None
TypeError: expected string or buffer
```
on a system with --versions
```
salt --versions
Salt Version:
           Salt: 2015.8.10

Dependency Versions:
         Jinja2: 2.6
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.2.0
         Python: 2.7.3 (default, Dec 18 2014, 19:10:20)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.1
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 0.3.6
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 12.04 precise
        machine: x86_64
        release: 3.8.0-44-generic
         system: Ubuntu 12.04 precise
```
