### ISSUE TITLE
Enabling memory limits in for container dockerng causes failure

### ISSUE THREAD

**Issue by faisyl** [saltstack/salt#32473]
### Description of Issue/Question
When enabling memory limits on the container via dockerng integration, using -1 for memory_swap causes failure:

    Function: dockerng.running
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1626, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1492, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/dockerng.py", line 1524, in running
                  validate_ip_addrs=validate_ip_addrs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/dockerng.py", line 1802, in _validate_input
                  _locals[key](*validation_arg)
                File "/usr/lib/python2.7/dist-packages/salt/modules/dockerng.py", line 1224, in _valid_memory_swap
                  if kwargs['memory_swap'] in -1:
              TypeError: argument of type 'int' is not iterable
     Started: 09:39:28.041301
    Duration: 31.89 ms
     Changes:

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Salt minion on version 2016.8.8
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
Setting memory_swap: -1 in dockerng.running state causes this failure.
### Versions Report
master:
`Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: 1.3.0
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-66-generic
         system: Ubuntu 14.04 trusty

minion:
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: 1.2.1
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-63-generic
         system: Ubuntu 14.04 trusty

**Comment by faisyl** [comment]
Found the fix already in 2016.8.0 branch. closing
