### ISSUE TITLE
glusterfs.started fails in 2015.8.8

### ISSUE THREAD

**Issue by fpytloun** [saltstack/salt#32509]
### Description of Issue/Question

Found regression when updating from version 2015.5.3 to 2015.8.8.
Problem appears during `glusterfs.started`:

```
          ID: glusterfs_vol_keystone-keys_start
    Function: glusterfs.started
        Name: keystone-keys
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1626, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1492, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/glusterfs.py", line 209, in started
                  if isinstance(__salt__['glusterfs.status'](name), dict):
                File "/usr/lib/python2.7/dist-packages/salt/modules/glusterfs.py", line 311, in status
                  root = _gluster_xml('volume status {0}'.format(name))
                File "/usr/lib/python2.7/dist-packages/salt/modules/glusterfs.py", line 82, in _gluster_xml
                  raise CommandExecutionError(root.find('opErrstr').text)
              CommandExecutionError: Volume keystone-keys is not started
     Started: 17:13:55.534300
    Duration: 130.261 ms
     Changes:
```
### Setup

Using this formula: https://github.com/tcpcloud/salt-formula-glusterfs/blob/master/glusterfs/server/setup.sls#L59

```
glusterfs_vol_{{ name }}_start:
  glusterfs.started:
    - name: {{ name }}
    - require:
      {%- if force_compatibility %}
      - cmd: glusterfs_vol_{{ name }}
      {%- else %}
      - glusterfs: glusterfs_vol_{{ name }}
      {%- endif %}
```

glusterfs 3.4.2
salt 2015.8.8
### Versions Report

```
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.19.0-49-generic
         system: Ubuntu 14.04 trusty
```

**Comment by fpytloun** [comment]
This workarounds the issue: https://github.com/tcpcloud/salt-formula-glusterfs/commit/823d1cdb128efd62dfd9a9e84891514a6ec22820

**Comment by jfindlay** [comment]
@fpytloun, thanks for reporting.  @joejulian, do you have any ideas here?

**Comment by joejulian** [comment]
I'll take this.

**Comment by cachedout** [comment]
@joejulian Have you had a chance to look at this one by chance?

**Comment by epcim** [comment]
@joejulian any update on this?

**Comment by joejulian** [comment]
Not really. Someone else was changing the gluster modules in a way that added technical debt that completely interfered with the work I was doing. I found it rather demotivating as a contributor and since I'm no longer working for a company that uses salt, I haven't looked at this since.

**Comment by epcim** [comment]
thanks for explanation. On 3 Apr 2017 18:05, Joe Julian <notifications@github.com> wrote:Not really. Someone else was changing the gluster modules in a way that added technical debt that completely interfered with the work I was doing. I found it rather demotivating as a contributor and since I'm no longer working for a company that uses salt, I haven't looked at this since.
