### ISSUE TITLE
git.clone on Windows worked in 2015.2.0rc2 but not on 2015.8.8

### ISSUE THREAD

**Issue by DennisHarper** [saltstack/salt#32553]
### Description of Issue/Question

When running git.clone on windows 2015.8.8 I am getting the following call stack:

```
  File "C:\Python27\lib\site-packages\salt\modules\git.py", line 793, in clone
    ignore_retcode=ignore_retcode)
  File "C:\Python27\lib\site-packages\salt\modules\git.py", line 208, in _git_run
    and __salt__['ssh.key_is_encrypted'](id_file):
  File "C:\Python27\lib\site-packages\salt\loader.py", line 900, in __getitem__
    func = super(LazyLoader, self).__getitem__(item)
  File "C:\Python27\lib\site-packages\salt\utils\lazy.py", line 93, in __getitem__
    raise KeyError(key)
KeyError: 'ssh.key_is_encrypted'
```

After looking into the code, it seems like git.clone is now using the ssh module, however the ssh module will return False in **virtual**  if salt.utils.is_windows(), thus it does not exist.

**Comment by ssgward** [comment]
@DennisHarper - thanks for the bug. 

We need some further info to help troubleshoot this better.

We need ``salt --versions-report`` from your master and ``salt-call --version`` from your minion.
What version of Windows is your minion running on?
What is the exact command you're running? Are you running salt from the CLI? or in a state file?

**Comment by DennisHarper** [comment]
We are calling it from a external module. Furthermore,  it is happening on multiple versions of the windows os  (although if you look at the the code associated with the call stack it will obviously occur on any version of Windows

**Comment by DennisHarper** [comment]
As far as the version, it is 2015.8.8 on both the master and the minions.

**Comment by DennisHarper** [comment]
If you do a salt-call it will work, but if I call the external module via the master, that is when it fails.

**Comment by ssgward** [comment]
Thanks.

**Comment by HeathNaylor** [comment]
I am getting this issue now. I just upgraded my salt-master and salt-minions to 2.8.8 when applying a state with `git.latest`.

Versions
Minion
```
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-74-generic
         system: Ubuntu 14.04 trusty
```

Master
```
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.1.5-x86_64-linode61
         system: Ubuntu 14.04 trusty
```

Error
```
    Function: git.latest
        Name: git@github.com:organization/repo.git
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1626, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1492, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/git.py", line 558, in latest
                  ignore_retcode=False)
                File "/usr/lib/python2.7/dist-packages/salt/modules/git.py", line 2801, in remote_refs
                  ignore_retcode=ignore_retcode)['stdout']
                File "/usr/lib/python2.7/dist-packages/salt/modules/git.py", line 208, in _git_run
                  and __salt__['ssh.key_is_encrypted'](id_file):
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 900, in __getitem__
                  func = super(LazyLoader, self).__getitem__(item)
                File "/usr/lib/python2.7/dist-packages/salt/utils/lazy.py", line 93, in __getitem__
                  raise KeyError(key)
              KeyError: 'ssh.key_is_encrypted'
```
