### ISSUE TITLE
salt-api returns HTTP/1.1 500 Internal Server Error when trying to log in

### ISSUE THREAD

**Issue by achechen** [saltstack/salt#32574]
salt-api returns HTTP/1.1 500 Internal Server Error when trying to log in:

````
curl -si localhost:8000/login         -H "Accept: application/json"         -d username='<notshown>'         -d password='<notshown>'         -d eauth='pam'
HTTP/1.1 500 Internal Server Error
Content-Length: 1607
Access-Control-Expose-Headers: GET, POST
Vary: Accept-Encoding
Server: CherryPy/3.2.2
Allow: GET, HEAD, POST
Access-Control-Allow-Credentials: true
Date: Thu, 14 Apr 2016 13:23:49 GMT
Access-Control-Allow-Origin: *
X-Auth-Token: 6a529d945c6654848c531337c1a1193f8635b482
Content-Type: text/html;charset=utf-8
Set-Cookie: session_id=6a529d945c6654848c531337c1a1193f8635b482; expires=Thu, 14 Apr 2016 23:23:49 GMT; Path=/

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>500 Internal Server Error</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>500 Internal Server Error</h2>
        <p>Configuration for external_auth could not be read.</p>
        <pre id="traceback">Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.6/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/netapi/rest_cherrypy/app.py", line 506, in hypermedia_handler
    ret = cherrypy.serving.request._hypermedia_inner_handler(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.6/site-packages/salt/netapi/rest_cherrypy/app.py", line 1525, in POST
    'Configuration for external_auth could not be read.')
HTTPError: (500, 'Configuration for external_auth could not be read.')
</pre>
    <div id="powered_by">
    <span>Powered by <a href="http://www.cherrypy.org">CherryPy 3.2.2</a></span>
    </div>
    </body>
</html>
```

When you enter the wrong credentials, the error is different so it definitely knows that the credentials entered before are correct:

`
 ```
curl -si localhost:8000/login         -H "Accept: application/json"         -d username='<notshown>'         -d password='<notshown>'         -d eauth='pam'
HTTP/1.1 401 Unauthorized
Content-Length: 1586
Access-Control-Expose-Headers: GET, POST
Vary: Accept-Encoding
Server: CherryPy/3.2.2
Allow: GET, HEAD, POST
Access-Control-Allow-Credentials: true
Date: Thu, 14 Apr 2016 13:23:34 GMT
Access-Control-Allow-Origin: *
Content-Type: text/html;charset=utf-8
Set-Cookie: session_id=b71f4afcc8f1caf3e0f5f33d0542c77bc1b9875a; expires=Thu, 14 Apr 2016 23:23:34 GMT; Path=/

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>401 Unauthorized</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>401 Unauthorized</h2>
        <p>Could not authenticate using provided credentials</p>
        <pre id="traceback">Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.6/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/netapi/rest_cherrypy/app.py", line 506, in hypermedia_handler
    ret = cherrypy.serving.request._hypermedia_inner_handler(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.6/site-packages/salt/netapi/rest_cherrypy/app.py", line 1497, in POST
    'Could not authenticate using provided credentials')
HTTPError: (401, 'Could not authenticate using provided credentials')
</pre>
    <div id="powered_by">
    <span>Powered by <a href="http://www.cherrypy.org">CherryPy 3.2.2</a></span>
    </div>
    </body>
</html>
`
```

/etc/salt/master:

```
`
rest_cherrypy:
  port: 8000
  host: 0.0.0.0
  disable_ssl: true
  debug: true

.....

external_auth:
  pam:
    <notshownhere>:
        -.*
        - '@runner'
        - '@wheel'

```
`

versions:


```
salt-api-2015.8.8-2.el6.noarch
salt-master-2015.8.8-2.el6.noarch
salt-minion-2015.8.8-2.el6.noarch
salt-2015.8.8-2.el6.noarch

```

**Comment by achechen** [comment]
I've noticed that it returns an auth token and I am able to use that token to send other requests and they go through fine:

```
 curl -sSk http://localhost:8000     -H 'Accept: application/x-yaml'     -H 'X-Auth-Token: 22d88a6639f5a3cedd540126aea68550d4b50d0b'    -d client=local     -d
tgt='*'     -d fun=test.ping
return:
- hostname.local: true
```

**Comment by jfindlay** [comment]
@achechen, thanks for reporting.  Your master config seems to have a typo
```sls
external_auth:
  pam:
    <notshownhere>:
        -.*
        - '@runner'
        - '@wheel'
```
should be
```sls
external_auth:
  pam:
    <notshownhere>:
        - .*
        - '@runner'
        - '@wheel'
```

**Comment by achechen** [comment]
oops, thanks a lot! :)

**Comment by jfindlay** [comment]
@achechen, I forgot to ask, does that change the error you're getting?

**Comment by rallytime** [comment]
Closing due to lack of response. If there is still an issue here, please leave a comment and we can keep the discussion going.

**Comment by mahresohl** [comment]
I'm having this problem while using rest_tornado as the backend.

rest_tornado:
  port: 8000
  host: 0.0.0.0
  disable_ssl: true
  websockets: True
  cors_origin: '*'

external_auth:
  pam:
  <notshown>:
    - .*
    - '@runner'
    - '@wheel'

----------------------------------------------------
curl -i http://localhost:8000
HTTP/1.1 200 OK
Content-Length: 99
Server: TornadoServer/4.2.1
Etag: "aeff1152c7d469b8706b951c530e056620ee4624"
Date: Wed, 20 Jul 2016 14:42:02 GMT
Access-Control-Allow-Origin: *
Content-Type: application/json

{"clients": ["runner", "runner_async", "local_async", "local", "local_batch"], "return": "Welcome"}
----------------------------------------------------

----------------------------------------------------
curl -i http://localhost:8000/login -H accept=application/json -d username=<notshown> -d password=<notshown> -d eauth=pam
HTTP/1.1 500 Internal Server Error
Date: Wed, 20 Jul 2016 14:20:11 GMT
Access-Control-Allow-Origin: *
Content-Type: text/html; charset=UTF-8
Content-Length: 93
Server: TornadoServer/4.2.1

<html><title>500: Internal Server Error</title><body>500: Internal Server Error</body></html>
----------------------------------------------------

salt-api debug output:
----------------------------------------------------
HTTPServerRequest(protocol='http', host='localhost:8000', method='POST', uri='/login', version='HTTP/1.1', remote_ip='::1', headers={'Host': 'localhost:8000', 'Content-Type': 'application/x-www-form-urlencoded', 'Content-Length': '42', 'Accept': '*/*', 'User-Agent': 'curl/7.47.0'})
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/netapi/rest_tornado/saltnado.py", line 745, in post
    perms = self.application.opts['external_auth'][token['eauth']][token['name']]
TypeError: 'NoneType' object has no attribute '__getitem__'
----------------------------------------------------

Versions:
Salt: 2016.3.1
Ubuntu 16.04 xenial
x86_64

2015.8.8 + Ubuntu Xenial = the same problem

**Comment by mahresohl** [comment]
Error in master configuration indentation was the reason:
-----------------------
<pre>
external_auth:
  pam:
    user1:               # here ident was at the same level as 'pam' - voila
      - .*
      - '@runner'
      - '@wheel'
</pre>
------------------------
After correcting salt-api works OK

**Comment by whiteinge** [comment]
Glad you found it. Validation of config files is definitely a needed feature: #4352.
