### ISSUE TITLE
msgpack-python version 0.4.2 causes exception with 'sudo salt-run winrepo.genrepo'

### ISSUE THREAD

**Issue by DennisHarper** [saltstack/salt#32620]
### Description of Issue/Question
when I run 'sudo salt-run winrepo.genrepo' with msgpack-python version 0.4.2 I get the following exception:
```py
Exception occurred in runner winrepo.genrepo: Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/client/mixins.py", line 342, in low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/runners/winrepo.py", line 138, in genrepo
    repo.write(msgpack.dumps(ret))
  File "_msgpack.pyx", line 172, in msgpack._msgpack.packb (msgpack/_msgpack.c:2375)
  File "_msgpack.pyx", line 152, in msgpack._msgpack.Packer.pack (msgpack/_msgpack.c:2064)
  File "_msgpack.pyx", line 154, in msgpack._msgpack.Packer.pack (msgpack/_msgpack.c:1972)
  File "_msgpack.pyx", line 137, in msgpack._msgpack.Packer._pack (msgpack/_msgpack.c:1685)
  File "_msgpack.pyx", line 137, in msgpack._msgpack.Packer._pack (msgpack/_msgpack.c:1685)
  File "_msgpack.pyx", line 131, in msgpack._msgpack.Packer._pack (msgpack/_msgpack.c:1599)
TypeError: Expected dict, got OrderedDict
```
However, when I upgraded to msgpack-python version 0.4.6, the exception went away.

I suggest updating msgpack version requirement to be 0.4.6.

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

1. Install salt 2015.8.8
2. Make sure that the version of msgpack is 0.4.2
3. create a winrepo setup
4. run 'salt-run winrepo.genrepo'

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
**Before msgpack-python Upgrade:**
Salt Version:
           Salt: 2015.8.8

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.20.2
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.6.0
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: 3.6.0
       dateutil: 2.3
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.1
        timelib: Not Installed

System Versions:
           dist: centos 6.6 Final
        machine: x86_64
        release: 2.6.32-504.1.3.el6.x86_64
         system: CentOS 6.6 Final
```
```
**After msgpack-python upgrade:**
Salt Version:
           Salt: 2015.8.8

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.20.2
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.6.0
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: 3.6.0
       dateutil: 2.3
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.1
        timelib: Not Installed

System Versions:
           dist: centos 6.6 Final
        machine: x86_64
        release: 2.6.32-504.1.3.el6.x86_64
         system: CentOS 6.6 Final
```

**Comment by jfindlay** [comment]
@DennisHarper, thanks for reporting.  Ping @twangboy, @dmurphy18.

**Comment by dmurphy18** [comment]
@DennisHarper Thanks for the info, I shall look at upgrading the package for the next point release

**Comment by dmurphy18** [comment]
@DennisHarper have salt-pack issue tracking this:
 Update msgpack-python on Redhat 6 #68

**Comment by dmurphy18** [comment]
@DennisHarper this should be available with the next release
