### ISSUE TITLE
Batch exception w/dulpicated minion IDs

### ISSUE THREAD

**Issue by dergrunepunkt** [saltstack/salt#32661]
### Description of Issue/Question

When more that one minion has the same ID and you try to runs salt with '-b' flag it raises this exception:

```
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
ValueError: list.remove(x): x not in list
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 454, in salt_main
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/salt.py", line 98, in run
    for res in batch.run():
  File "/usr/lib/python2.7/dist-packages/salt/cli/batch.py", line 173, in run
    minion_tracker[queue]['minions'].remove(id)
ValueError: list.remove(x): x not in list
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 454, in salt_main
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/salt.py", line 98, in run
    for res in batch.run():
  File "/usr/lib/python2.7/dist-packages/salt/cli/batch.py", line 173, in run
    minion_tracker[queue]['minions'].remove(id)
ValueError: list.remove(x): x not in list
```

### Steps to Reproduce Issue

Have two minions with the same ID and diffrent keys and voila!

### Versions Report

```
# salt --versions-report
Salt Version:
           Salt: 2015.8.3
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-48-generic
         system: Ubuntu 14.04 trusty
```

Cheers!

**Comment by cachedout** [comment]
@dergrunepunkt Please give #32686 a try and see if it resolves your problem. Thanks.

**Comment by dergrunepunkt** [comment]
I'm testing this fix, I'll let you know!

thanks

**Comment by dergrunepunkt** [comment]
Seems to work fine, thanks!
