### ISSUE TITLE
salt exits with KeyError: 'pid'

### ISSUE THREAD

**Issue by Wenzel** [saltstack/salt#32814]
### Description of Issue/Question
I tried to install salt from source and to apply an empty state, in a masterless environement,
by calling `salt-call --local` and it failed with a `KeyError` exception.

I used `v2016.3`

### Setup
The following `Dockerfile` should reproduce the bug :

~~~
FROM debian:latest

RUN apt-get update && apt-get install -y git python3.4 python3-dev python3-pip
RUN git clone https://github.com/saltstack/salt
WORKDIR salt
RUN git checkout v2016.3
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.4 1
RUN update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1
RUN pip install -e .
RUN salt-call --version
CMD salt-call -l debug --local state.highstate
~~~

### Steps to Reproduce Issue
- `docker build -t debug_salt .`
- `docker run -it --rm debug_salt`

It should produce the same error output :

~~~
root@37787db1bfe2:/salt# salt-call --local state.highstate
WARNING: CONFIG '/etc/salt' directory does not exist.
[ERROR   ] Could not cache minion ID: [Errno 2] No such file or directory: '/etc/salt/minion_id'
[WARNING ] Failed to open log file, do you have permission to write to /var/log/salt/minion?
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
KeyError: 'pid'
Traceback (most recent call last):
  File "/usr/local/bin/salt-call", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/salt/scripts/salt-call", line 11, in <module>
    salt_call()
  File "/salt/salt/scripts.py", line 333, in salt_call
    client.run()
  File "/salt/salt/cli/call.py", line 58, in run
    caller.run()
  File "/salt/salt/cli/caller.py", line 133, in run
    ret = self.call()
  File "/salt/salt/cli/caller.py", line 196, in call
    ret['return'] = func(*args, **kwargs)
  File "/salt/salt/modules/state.py", line 535, in highstate
    conflict = _check_queue(queue, kwargs)
  File "/salt/salt/modules/state.py", line 159, in _check_queue
    conflict = running()
  File "/salt/salt/modules/state.py", line 122, in running
    active = __salt__['saltutil.is_running']('state.*')
  File "/salt/salt/modules/saltutil.py", line 629, in is_running
    run = running()
  File "/salt/salt/modules/saltutil.py", line 647, in running
    return salt.utils.minion.running(__opts__)
  File "/salt/salt/utils/minion.py", line 24, in running
    data = _read_proc_file(path, opts)
  File "/salt/salt/utils/minion.py", line 57, in _read_proc_file
    if not salt.utils.process.os_is_running(data['pid']):
KeyError: 'pid'
Traceback (most recent call last):
  File "/usr/local/bin/salt-call", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/salt/scripts/salt-call", line 11, in <module>
    salt_call()
  File "/salt/salt/scripts.py", line 333, in salt_call
    client.run()
  File "/salt/salt/cli/call.py", line 58, in run
    caller.run()
  File "/salt/salt/cli/caller.py", line 133, in run
    ret = self.call()
  File "/salt/salt/cli/caller.py", line 196, in call
    ret['return'] = func(*args, **kwargs)
  File "/salt/salt/modules/state.py", line 535, in highstate
    conflict = _check_queue(queue, kwargs)
  File "/salt/salt/modules/state.py", line 159, in _check_queue
    conflict = running()
  File "/salt/salt/modules/state.py", line 122, in running
    active = __salt__['saltutil.is_running']('state.*')
  File "/salt/salt/modules/saltutil.py", line 629, in is_running
    run = running()
  File "/salt/salt/modules/saltutil.py", line 647, in running
    return salt.utils.minion.running(__opts__)
  File "/salt/salt/utils/minion.py", line 24, in running
    data = _read_proc_file(path, opts)
  File "/salt/salt/utils/minion.py", line 57, in _read_proc_file
    if not salt.utils.process.os_is_running(data['pid']):
KeyError: 'pid'
~~~

### Versions Report
~~~
Salt Version:
           Salt: 2016.3.0

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 3.4.2 (default, Oct  8 2014, 10:45:20)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.2
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: debian 8.3
        machine: x86_64
        release: 4.4.7-300.fc23.x86_64
         system: debian 8.3
~~~

Thanks !

**Comment by jfindlay** [comment]
@Wenzel, thanks for reporting.  I see a few issues with your setup.  Salt is not fully supported on python 3 yet, so you can expect some errors, but you are very welcome to help out if you want.  It seems that you are running salt with a user that is different from the user that installed salt (`[WARNING ] Failed to open log file, do you have permission to write to /var/log/salt/minion?`).  Typically salt daemons and commands are run as root unless you have [configured](https://docs.saltstack.com/en/latest/ref/configuration/nonroot.html) it otherwise.  The [v2016.3](https://github.com/saltstack/salt/releases/tag/v2016.3) tag points to the branch point of the 2016.3 branch for auditing and organizational convenience.  There have been more than a thousand commits to both the 2016.3 and develop branches since then, so it is probably not what you want to be running.  You may have better luck with the head of the 2016.3 branch or [v2016.3.0rc2](https://github.com/saltstack/salt/releases/tag/v2016.3.0rc2).

**Comment by Wenzel** [comment]
Hi !
Thanks for your quick reply !

> it seems that you are running salt with a user that is different from the user that installed salt ([WARNING ] Failed to open log file, do you have permission to write to /var/log/salt/minion?). Typically salt daemons and commands are run as root unless you have configured it otherwise. 

I was running as root inside Docker, so the issue is not here.



>  Salt is not fully supported on python 3 yet, so you can expect some errors, but you are very welcome to help out if you want.

I tried with python2, and it works, even on the v2016.3.0rc2 :)
So it was a python3 related error, if you want to fix it.
