### ISSUE TITLE
svnfs_remotes - salt not mapping repo files to salt master fileserver

### ISSUE THREAD

**Issue by ryanlraines** [saltstack/salt#32871]
### Description of Issue/Question:

I am pointing my salt master to my svn repo using 'svnfs_remotes' [https://docs.saltstack.com/en/latest/ref/configuration/master.html#svn-subversion-remote-file-server-backend](url)

So, there are two issues here, but they might be related, so I'm documenting them both. 
1. /usr/lib/python2.7/site-packages/salt/fileserver/svnfs.py is overwriting  remote_map.txt at start up
2. salt master is not maping local svnfs cache to salt fileserver _(`salt '*' cp.list_master` returns no files & state.highstate reports that no top file exists, but it does in the repo)_
### Setup

I have a single VM running master & minion 

**(master config)**

```
interface: 0.0.0.0
hash_type: sha256
fileserver_backend:
  - svn
svnfs_remotes:
  - svn://<repo_url>/saas/branches/internal/inc4/SASSY-743:
    - root: /trunk/salt/roots/salt/
```

**(minion config)**

```
hash_type: sha256
master: localhost
```
### Steps to Reproduce Issue

Master starts, caches a copy of the repo just fine, but then throws the following error:

```
[root@hostname /]# salt-master -l debug
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: <minion_id>
[DEBUG   ] Key 'file_ignore_glob' with value None has an invalid type of NoneType, a list is required for this value
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] Setting up the Salt Master
[DEBUG   ] Loaded master key: /etc/salt/pki/master/master.pem
[INFO    ] Preparing the root key for local communication
[DEBUG   ] Removing stale keyfile: /var/cache/salt/master/.root_key
[DEBUG   ] Created pidfile: /var/run/salt-master.pid
[INFO    ] The Salt Master is starting up
[DEBUG   ] LazyLoaded svn.envs
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: string indices must be integers, not str
Traceback (most recent call last):
  File "/usr/bin/salt-master", line 22, in <module>
    salt_master()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 47, in salt_master
    master.start()
  File "/usr/lib/python2.7/site-packages/salt/cli/daemons.py", line 200, in start
    self.master.start()
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 459, in start
    self._pre_flight()
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 407, in _pre_flight
    fileserver.init()
  File "/usr/lib/python2.7/site-packages/salt/fileserver/__init__.py", line 481, in init
    self.servers[fstr]()
  File "/usr/lib/python2.7/site-packages/salt/fileserver/svnfs.py", line 233, in init
    repo_conf['hash'], repo_conf['url']
TypeError: string indices must be integers, not str
Traceback (most recent call last):
  File "/usr/bin/salt-master", line 22, in <module>
    salt_master()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 47, in salt_master
    master.start()
  File "/usr/lib/python2.7/site-packages/salt/cli/daemons.py", line 200, in start
    self.master.start()
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 459, in start
    self._pre_flight()
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 407, in _pre_flight
    fileserver.init()
  File "/usr/lib/python2.7/site-packages/salt/fileserver/__init__.py", line 481, in init
    self.servers[fstr]()
  File "/usr/lib/python2.7/site-packages/salt/fileserver/svnfs.py", line 233, in init
    repo_conf['hash'], repo_conf['url']
TypeError: string indices must be integers, not str
```

`/var/cache/salt/master/svnfs/remote_map.tx` is not populated with anything. 

@babilen from webchat suggested 

> Stop the master, edit /usr/lib/python2.7/site-packages/salt/fileserver/svnfs.py and comment "repos.append(rp_)" in there by prefixing it with # so it looks like "# repos.append(rp_)" -- This should be on line 193 (or somesuch) between "CLIENT.checkout(....)" and "new_remote = True"

after doing this, and `rm -rf /var/cache/salt/master/svnfs/*` and restarting master `/var/cache/salt/master/svnfs/remote_map.txt` is populated with `<svn cache DIR name> = <repo_url>`.  No errors are returned in debug log. 

However, when `salt '*' cp.list_master` is issued, nothing is returned.  I'm expecting a listing of all the files from the configured svnfs_remotes svn repo. 

```
[root@hostname ~]# salt '*' cp.list_master
minion_id:
```
### Versions Report

```
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.13.1.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
```

**Comment by jfindlay** [comment]
@ryanlraines, thanks for reporting.

**Comment by kveroneau** [comment]
This is still definately an issue, I don't believe anybody is noticing/reporting as subversion is mostly dead these days.  In the current version 2018.3.0 if I try to use svnfs, I see the following in the log file:
[DEBUG   ] Could not LazyLoad svnfs.envs: 'svnfs' __virtual__ returned False

If I remove the lines which detect what I have in my fileserver_backend:
    if __virtualname__ not in __opts__['fileserver_backend']:
        return False

Then I see the exact same error the orignal reporter of this issue posted.
