### ISSUE TITLE
2016.3 ctrl-c causes a stack trace instead of shutting down cleanly

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#32899]
### Description of Issue/Question
When running 2016.3 ctrl-c causes a stacktrace instead of shutting down cleanly
### Setup
Run a salt command:

```
[root@om salt]# salt \* test.sleep 30
^C[ERROR   ] An un-handled exception was caught by salt's global exception handler:
RuntimeError: IOLoop is already running
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 458, in salt_main
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/salt.py", line 158, in run
    for full_ret in cmd_func(**kwargs):
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 622, in cmd_cli
    **kwargs):
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 1293, in get_cli_event_returns
    **kwargs
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 912, in get_iter_returns
    for raw in ret_iter:
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 847, in get_returns_no_block
    raw = self.event.get_event(wait=0.01, tag=tag, match_type=match_type, full=True, no_block=True)
  File "/usr/lib/python2.7/site-packages/salt/utils/event.py", line 579, in get_event
    ret = self._get_event(wait, tag, match_func, no_block)
  File "/usr/lib/python2.7/site-packages/salt/utils/event.py", line 484, in _get_event
    raw = self.subscriber.read_sync(timeout=wait)
  File "/usr/lib/python2.7/site-packages/salt/transport/ipc.py", line 649, in read_sync
    self.io_loop.start()
  File "/usr/lib64/python2.7/site-packages/tornado/ioloop.py", line 730, in start
    raise RuntimeError("IOLoop is already running")
RuntimeError: IOLoop is already running
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 458, in salt_main
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/salt.py", line 158, in run
    for full_ret in cmd_func(**kwargs):
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 622, in cmd_cli
    **kwargs):
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 1293, in get_cli_event_returns
    **kwargs
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 912, in get_iter_returns
    for raw in ret_iter:
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 847, in get_returns_no_block
    raw = self.event.get_event(wait=0.01, tag=tag, match_type=match_type, full=True, no_block=True)
  File "/usr/lib/python2.7/site-packages/salt/utils/event.py", line 579, in get_event
    ret = self._get_event(wait, tag, match_func, no_block)
  File "/usr/lib/python2.7/site-packages/salt/utils/event.py", line 484, in _get_event
    raw = self.subscriber.read_sync(timeout=wait)
  File "/usr/lib/python2.7/site-packages/salt/transport/ipc.py", line 649, in read_sync
    self.io_loop.start()
  File "/usr/lib64/python2.7/site-packages/tornado/ioloop.py", line 730, in start
    raise RuntimeError("IOLoop is already running")
RuntimeError: IOLoop is already running
```

### Versions Report
```
[root@om salt]# salt --versions-report
Salt Version:
           Salt: 2016.3.0rc2-313-g841dd59
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.10.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

**Comment by ssgward** [comment]
This works correctly (no error) when following the same steps and using 2015.8.8.2.
```
[root@master ~]# salt \* test.sleep 30
^CExiting on Ctrl-C
This job's jid is:
20160427211806512048
The minions may not have all finished running and any remaining minions will return upon completion. To look up the return data for this job later run:
salt-run jobs.lookup_jid 20160427211806512048
```

**Comment by rallytime** [comment]
Fixed:
```
root@rallytime:~# salt rallytime test.sleep 30
^CExiting on Ctrl-C
This job's jid is:
20160505163032215652
The minions may not have all finished running and any remaining minions will return upon completion. To look up the return data for this job later run:
salt-run jobs.lookup_jid 20160505163032215652
```
