### ISSUE TITLE
salt-cloud --list-images gce fails

### ISSUE THREAD

**Issue by bogdanr** [saltstack/salt#32909]
### Description of Issue/Question

`salt-cloud --list-images gce` fails

Running `salt-cloud -Q` successfully returns information about that node so authentication works properly.

### Setup

```
gce-config:
  project: "bla-1"
  service_account_email_address: "bla@developer.gserviceaccount.com"
  service_account_private_key: "/etc/salt/cloud.providers.d/bla.json"

  minion:
    master: oboffice

  provider: gce
```

### Steps to Reproduce Issue

`root@oboffice:~# salt-cloud --list-images gce`
```
[DEBUG   ] Configuration file path: /etc/salt/cloud
[INFO    ] salt-cloud starting
[DEBUG   ] Could not LazyLoad parallels.avail_sizes
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy
[DEBUG   ] Could not LazyLoad saltify.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.avail_images
[DEBUG   ] Could not LazyLoad saltify.avail_locations
[DEBUG   ] LazyLoaded rackspace.reboot
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] LazyLoaded rackspace.list_locations
[ERROR   ] Failed to get the output of 'gce.avail_images()': {'domain': 'global', 'message': "The resource 'projects/cloud-image-release' was not found. A missing project error may be an authentication issue. Please  ensure your auth credentials match your project. ", 'reason': 'notFound'}
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 841, in image_list
    data[alias][driver] = self.clouds[fun]()
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/gce.py", line 335, in avail_images
    debian_images = conn.list_images('debian-cloud')
  File "/usr/local/lib/python2.7/dist-packages/libcloud/compute/drivers/gce.py", line 1471, in list_images
    ex_include_deprecated=dep)
  File "/usr/local/lib/python2.7/dist-packages/libcloud/compute/drivers/gce.py", line 1523, in ex_list_project_images
    method='GET').object
  File "/usr/local/lib/python2.7/dist-packages/libcloud/compute/drivers/gce.py", line 120, in request
    response = super(GCEConnection, self).request(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/libcloud/common/google.py", line 718, in request
    *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/libcloud/common/base.py", line 797, in request
    response = responseCls(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/libcloud/common/base.py", line 145, in __init__
    self.object = self.parse_body()
  File "/usr/local/lib/python2.7/dist-packages/libcloud/common/google.py", line 271, in parse_body
    raise ResourceNotFoundError(message, self.status, code)
ResourceNotFoundError: {'domain': 'global', 'message': "The resource 'projects/cloud-image-release' was not found. A missing project error may be an authentication issue. Please  ensure your auth credentials match your project. ", 'reason': 'notFound'}
[DEBUG   ] LazyLoaded nested.output
```

### Versions Report

```
                  Salt: 2015.5.3
                Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
                Jinja2: 2.7.3
              M2Crypto: 0.21.1
        msgpack-python: 0.4.2
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.11
                 ioflo: Not Installed
                 PyZMQ: 14.4.0
                  RAET: Not Installed
                   ZMQ: 4.0.5
                  Mako: Not Installed
               Tornado: Not Installed
       Apache Libcloud: 0.20.1
 Debian source package: 2015.5.3+ds-1~bpo8+1
```

**Comment by dvigueras** [comment]
We are having the same issue with Ansible (which is also using libcloud): https://googlecloudplatform.uservoice.com/forums/302595-compute-engine/suggestions/13631622-can-t-create-disk-in-gce-from-ansible-gce-pd-libcl

**Comment by bogdanr** [comment]
Perhaps [this](https://github.com/apache/libcloud/pull/778) pull request will fix the issue in libcloud.

After it's merged and released we'll have to wait and see if works properly with SaltStack or Ansible.

**Comment by erjohnso** [comment]
Hi @bogdanr,

Thanks for reporting this. The libcloud PR is unrelated and wouldn't have fixed the underlying issue.  I believe a fix for this was just released by Google.  Can you verify that the issue has been resolved?

**Comment by bogdanr** [comment]
Yes. The fix from Google resolved the issue.
