### ISSUE TITLE
salt-key -F has traceback with RAET transport

### ISSUE THREAD

**Issue by JoshLitt** [saltstack/salt#32923]
### Description of Issue/Question

Running "salt-key -F" with raet transport configured causes a traceback:

```
$ sudo salt-key -F
Traceback (most recent call last):
  File "/usr/bin/salt-key", line 10, in <module>
    salt_key()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 289, in salt_key
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/key.py", line 32, in run
    key.run()
  File "/usr/lib/python2.7/dist-packages/salt/key.py", line 431, in run
    self.finger_all()
  File "/usr/lib/python2.7/dist-packages/salt/key.py", line 317, in finger_all
    matches = self.key.finger('*')
  File "/usr/lib/python2.7/dist-packages/salt/key.py", line 1332, in finger
    ret[status][key] = self._get_key_finger(path)
  File "/usr/lib/python2.7/dist-packages/salt/key.py", line 1145, in _get_key_finger
    keydata['pub'],
KeyError: 'pub'
```
### Setup

(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
/etc/salt/master:
 transport: raet
 hash_type: sha256
### Steps to Reproduce Issue

I have 2 minions accepted.

I think this is due to how RaetKey._get_key_finger() seems incompatible with the data found in local.key.  self.serial.loads() returns a dictionary with keys "priv" and "sign" (as written by the write_local() method), but the _get_key_finger() method is expecting "pub" and "verify".
### Versions Report

```
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: 0.6.5
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.5.1
        libgit2: Not Installed
        libnacl: 1.4.4
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.2.0-27-generic
         system: Ubuntu 14.04 trusty
```

**Comment by jfindlay** [comment]
@JoshLitt, thanks for reporting.  You are welcome to send a pull request if you have an idea of how to fix this.
