### ISSUE TITLE
gluster fails after upgrading the minion from 2015.5.3 to 2015.8.8.2

### ISSUE THREAD

**Issue by bogdanr** [saltstack/salt#32967]
### Description of Issue/Question

```
2016-05-01 05:42:29,985 [salt.state       ][INFO    ][27036] Running state [fakenode-web4] at time 05:42:29.985430
2016-05-01 05:42:29,986 [salt.state       ][INFO    ][27036] Executing state glusterfs.peered for fakenode-web4
2016-05-01 05:42:29,986 [py.warnings      ][WARNING ][27036] /usr/lib/python2.7/dist-packages/salt/modules/glusterfs.py:182: DeprecationWarning: The glusterfs.list_peers function is deprecated in favor of more verbose but very similar glusterfs.peer_status.

2016-05-01 05:42:29,988 [salt.loaded.int.module.cmdmod][INFO    ][27036] Executing command 'gluster --version' in directory '/root'
2016-05-01 05:42:29,994 [salt.loaded.int.module.cmdmod][DEBUG   ][27036] output: glusterfs 3.5.2 built on Jul 29 2015 18:55:57
Repository revision: git://git.gluster.com/glusterfs.git
Copyright (c) 2006-2011 Gluster Inc. <http://www.gluster.com>
GlusterFS comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GlusterFS under the terms of the GNU General Public License.
2016-05-01 05:42:29,995 [salt.loaded.int.module.cmdmod][INFO    ][27036] Executing command 'script -q -c "gluster --xml --mode=script"' in directory '/root'
2016-05-01 05:42:30,386 [salt.loaded.int.module.cmdmod][DEBUG   ][27036] output: peer status
gluster> peer status
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<cliOutput>
  <opRet>0</opRet>
  <opErrno>0</opErrno>
  <opErrstr/>
  <peerStatus>
    <peer>
      <uuid>108abc6c-4357-47f5-bf63-a719d27ac970</uuid>
      <hostname>10.240.0.12</hostname>
      <connected>1</connected>
      <state>3</state>
      <stateStr>Peer in Cluster</stateStr>
    </peer>
  </peerStatus>
</cliOutput>
gluster>
2016-05-01 05:42:30,388 [salt.state       ][ERROR   ][27036] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1626, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1492, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/states/glusterfs.py", line 73, in peered
    peers = __salt__['glusterfs.list_peers']()
  File "/usr/lib/python2.7/dist-packages/salt/modules/glusterfs.py", line 184, in list_peers
    return peer_status()
  File "/usr/lib/python2.7/dist-packages/salt/modules/glusterfs.py", line 148, in peer_status
    root = _gluster_xml('peer status')
  File "/usr/lib/python2.7/dist-packages/salt/modules/glusterfs.py", line 78, in _gluster_xml
    root = ET.fromstring(_gluster_output_cleanup(result))
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 0
```
### Steps to Reproduce Issue
1. Install the minion from here (2015.8.8.2):
   deb https://repo.saltstack.com/apt/debian/8/amd64/latest jessie main
2. To fix the problem revert the minion version with the latest (2015.5.3) from here:
   deb http://debian.saltstack.com/debian jessie-saltstack main
### Versions Report

The minion that fails is salt-2015.8.8.2
The master is 2015.5.3

**Comment by jfindlay** [comment]
@bogdanr, thanks for reporting.  Ping @joejulian.
