### ISSUE TITLE
Error when executing salt run with RAET

### ISSUE THREAD

**Issue by jakehilton** [saltstack/salt#33016]
### Description of Issue/Question
I ran a simple `salt-run cache.clear_all` command and saw an error in the system that I'm unsure if has unwanted effects.

It seems that the RAET transport isn't quite baked yet with all the side issues I've seen. Is anyone actually using RAET?

### Setup
Configure master/mininos to use RAET as the transport on Ubuntu 14.04.

### Steps to Reproduce Issue
Once setup execute a cache clean_all salt run.

```
2016-05-03 16:16:09,183 [salt.log.setup   ][ERROR   ][16490] An un-handled exception was caught by salt's global exception handler:
KeyError: 'manor'
Traceback (most recent call last):
  File "/usr/bin/salt-run", line 10, in <module>
    salt_run()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 358, in salt_run
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/run.py", line 41, in run
    runner.run()
  File "/usr/lib/python2.7/dist-packages/salt/runner.py", line 181, in run
    False)  # Don't daemonize
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 412, in _proc_function
    return self.low(fun, low)
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 355, in low
    namespaced_event.fire_event(data, 'ret')
  File "/usr/lib/python2.7/dist-packages/salt/utils/event.py", line 716, in fire_event
    self.event.fire_event(data, tagify(tag, base=self.base))
  File "/usr/lib/python2.7/dist-packages/salt/utils/raetevent.py", line 218, in fire_event
    self.stack.transmit(msg, self.stack.nameRemotes[self.ryn].uid)
KeyError: 'manor'
```

I wager this is not specific to the cache.clear_all functionality but to other salt run calls when using RAET.

### Versions Report
```
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.22
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.4.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: 0.6.5
        Tornado: 4.3
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: 1.5.1
        libgit2: Not Installed
        libnacl: 1.4.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-79-generic
         system: Ubuntu 14.04 trusty
```

**Comment by jfindlay** [comment]
@jakehilton, thanks for reporting.

**Comment by thatch45** [comment]
@jakehilton moving forward we are recommending the tcp transport over raet and only suggest that raet is used if you explicitly need UDP.
The TCP transport also solves the main reason we find for people using raet, which is to avoid the zeromq licence as the tcp transport dep is apache2 licenced (tornado)
As of 2016.3 there are no known issues with the tcp transport.
I am looking into this one right now

**Comment by jakehilton** [comment]
I'll give the tcp transport a try and see I fair with that. Thank you for the recommendation.

**Comment by thatch45** [comment]
Ok, this is specific to clear_cache, it uses a convenience class that does not work with raet, and this is the only instance of the class being used, I am removing it

**Comment by thatch45** [comment]
Oh, Doh! I forgot, the master needs to be running for runners to work in raet, otherwise the sockets can't discover the main event bus and they fall over.
If you start the master then clear_cache works without issues and without changes. I am going to close this out since the function works if the master is on and consolidate these into an issue to make the raet event system not stack trace is the master is not running

**Comment by jakehilton** [comment]
Sounds good. Thank you for the note.

**Comment by jakehilton** [comment]
Maybe for second ticket.. but when switching to the tcp transport I see this in my minion log:
```2016-05-04 16:52:37,211 [tornado.application][ERROR   ][14872] Exception in callback <functools.partial object at 0x7f55dc0ca890>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 600, in _run_callback
    ret = callback()
  File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 615, in <lambda>
    self.add_future(ret, lambda f: f.result())
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.7/dist-packages/salt/crypt.py", line 436, in _authenticate
    creds = yield self.sign_in()
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 282, in wrapper
    yielded = next(result)
  File "/usr/lib/python2.7/dist-packages/salt/crypt.py", line 501, in sign_in
    io_loop=self.io_loop)
  File "/usr/lib/python2.7/dist-packages/salt/transport/client.py", line 114, in factory
    return salt.transport.tcp.AsyncTCPReqChannel(opts, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/tcp.py", line 77, in __new__
    new_obj.__singleton_init__(opts, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/tcp.py", line 117, in __singleton_init__
    self.message_client = SaltMessageClient(host, int(port), io_loop=self.io_loop, resolver=resolver)
  File "/usr/lib/python2.7/dist-packages/salt/transport/tcp.py", line 397, in __init__
    self._tcp_client = tornado.tcpclient.TCPClient(io_loop=self.io_loop, resolver=resolver)
  File "/usr/local/lib/python2.7/dist-packages/tornado/tcpclient.py", line 149, in __init__
    self.resolver = Resolver(io_loop=io_loop)
  File "/usr/local/lib/python2.7/dist-packages/tornado/util.py", line 221, in __new__
    instance.initialize(*args, **init_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado/netutil.py", line 420, in initialize
    threadpool = ThreadedResolver._create_threadpool(num_threads)
  File "/usr/local/lib/python2.7/dist-packages/tornado/netutil.py", line 432, in _create_threadpool
    from concurrent.futures import ThreadPoolExecutor
ImportError: No module named concurrent.futures
```

**Comment by thatch45** [comment]
Huh, the install should bring in the futures package, tornado deps it after tornado 4.2, so install python futures and you should be good to go.
did you install from our repos?

**Comment by jakehilton** [comment]
Yes I did. Here is my versions report
```
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.22
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.4.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: 0.6.5
        Tornado: 4.3
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: 1.5.1
        libgit2: Not Installed
        libnacl: 1.4.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-85-generic
         system: Ubuntu 14.04 trusty
```

What package is missing?

**Comment by thatch45** [comment]
python-concurrent.future
http://repo.saltstack.com/apt/ubuntu/14.04/amd64/2015.8/python-concurrent.futures_3.0.3-1_all.deb

tornado should dep on it, that might be a bug in the package

**Comment by jakehilton** [comment]
Ok.. got it pip installed.. master seems to start up without error.. only just this warning
```2016-05-04 17:00:17,737 [py.warnings      ][WARNING ][15858] /usr/lib/python2.7/dist-packages/salt/pillar/__init__.py:42: DeprecationWarning: Passing a salt environment should be done using 'saltenv' not 'env'. This functionality will be removed in Salt Boron.```

Minions complain a little on highstate:
```
[ERROR   ] Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 282, in wrapper
    yielded = next(result)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 476, in eval_master
    pub_channel = salt.transport.client.AsyncPubChannel.factory(opts, **factory_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/client.py", line 163, in factory
    return salt.transport.tcp.AsyncTCPPubChannel(opts, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/tcp.py", line 201, in __init__
    self.io_loop = kwargs['io_loop'] or tornado.ioloop.IOLoop.current()
KeyError: 'io_loop'
Exception AttributeError: "'AsyncTCPPubChannel' object has no attribute '_closing'" in <bound method AsyncTCPPubChannel.__del__ of <salt.transport.tcp.AsyncTCPPubChannel object at 0x7f0ce629b610>> ignored
```

I can open another ticket.

**Comment by thatch45** [comment]
Yes, lets open another ticket, I don't think I have seen this error before, makes me think it is install related

**Comment by jakehilton** [comment]
I'll open another ticket and do a fresh install and see if it persists.. thanks.
