### ISSUE TITLE
TypeError: unhashable type: 'dict'

### ISSUE THREAD

**Issue by robnagler** [saltstack/salt#33073]
### Description of Issue/Question

This might be an issue between salt-master on Fedora 21 and salt-minion on Fedora 23. Happens with state.apply but also test.ping:

```bash
salt v3 test.ping
```

Full debug trace: https://gist.github.com/robnagler/f07954d2f95f48064dc756b509c81fce

```text
This often happens when trying to read a file not in binary mode.Please open an issue and include the following error: unhashable type: 'dict'
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: unhashable type: 'dict'
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/2.7.10/bin/salt", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/vagrant/src/robnagler/salt/scripts/salt", line 10, in <module>
    salt_main()
  File "/home/vagrant/src/robnagler/salt/salt/scripts.py", line 470, in salt_main
    client.run()
  File "/home/vagrant/src/robnagler/salt/salt/cli/salt.py", line 158, in run
    for full_ret in cmd_func(**kwargs):
  File "/home/vagrant/src/robnagler/salt/salt/client/__init__.py", line 622, in cmd_cli
    **kwargs):
  File "/home/vagrant/src/robnagler/salt/salt/client/__init__.py", line 1304, in get_cli_event_returns
    connected_minions = salt.utils.minions.CkMinions(self.opts).connected_ids()
  File "/home/vagrant/src/robnagler/salt/salt/utils/minions.py", line 581, in connected_ids
    grains = self.serial.load(fp_).get('grains', {})
  File "/home/vagrant/src/robnagler/salt/salt/payload.py", line 160, in load
    return self.loads(data)
  File "/home/vagrant/src/robnagler/salt/salt/payload.py", line 136, in loads
    ret = msgpack.loads(msg, use_list=True, encoding=encoding)
  File "msgpack/_unpacker.pyx", line 139, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:139)
TypeError: unhashable type: 'dict'
```

### Setup

Two VMs: one with Fedora 21 (master) and one with Fedora 23. Both installed with bootstrap git develop.

### Steps to Reproduce Issue

On master:

```
salt \* test.ping
```
### Versions Report

Master:

```
Salt Version:
           Salt: 2016.3.0-488-g40b6dfa

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.10 (default, Nov 14 2015, 01:41:47)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.2

System Versions:
           dist: fedora 21 Twenty One
        machine: x86_64
        release: 4.1.12-101.fc21.x86_64
         system: Linux
        version: Fedora 21 Twenty One
```

Minion:

```
Salt Version:
           Salt: 2016.3.0-501-g0ebeb58

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.11 (default, Mar 31 2016, 20:46:51)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.2

System Versions:
           dist: fedora 23 Twenty Three
        machine: x86_64
        release: 4.2.3-300.fc23.x86_64
         system: Linux
        version: Fedora 23 Twenty Three
```

**Comment by cachedout** [comment]
Hrm. Can we see the grains on that minion? You don't have something like the reserved word `dict` as a value in those grains, do you?

**Comment by robnagler** [comment]
Nothing to do with the grains. It's improperly escaped YAML. Create a pillar file as follows:

```yaml
{% raw %}
x: {{ grains.username }}
{% endraw %}
```

This is invalid YAML. Demonstrated by:

```bash
python -c 'import yaml; yaml.load("- {{}}")'
```

Seems like this should be caught at the YAML level.

**Comment by jfindlay** [comment]
I can reproduce this on 2015.8.8-ish with the master and minion on the same system.

### configs
```sls
# cat /srv/salt/test.sls
echo:
  cmd.run:
    - name: echo {{ pillar.get('test') }}
```
```sls
# cat /srv/pillar/top.sls
base:
  '*':
     - test
```
```sls
# cat /srv/pillar/test.sls
{% raw %}
test: {{ grains.username }}
{% endraw %}
```

### commands
```console
# salt jmoney-main state.show_sls test
jmoney-main:
    Passed invalid arguments to state.show_sls: unhashable type: 'dict'

        Display the state data from a specific sls or list of sls files on the
        master. The default environment is ``base``, use ``saltenv`` (``env`` in
        Salt 0.17.x and older) to specify a different environment.

        This function does not support topfiles.  For ``top.sls`` please use
        ``show_top`` instead.

        Custom Pillar data can be passed with the ``pillar`` kwarg.

        CLI Example:

        .. code-block:: bash

            salt '*' state.show_sls core,edit.vim dev
```

### logs
```
# salt-master -l debug
...
[DEBUG   ] Sending event - data = {'_stamp': '2016-05-06T20:47:58.988827', 'minions': ['jmoney-main']}
[DEBUG   ] Sending event - data = {'tgt_type': 'glob', 'jid': '20160506144758988545', 'tgt': 'jmoney-main', '_stamp': '2016-05-06T20:47:58.989153', 'user': 'root', 'arg': ['test'], 'fun': 'state.show_sls', 'minions': ['jmoney-main']}
[DEBUG   ] Adding minions for job %s%s: %s
[INFO    ] User root Published command state.show_sls with jid 20160506144758988545
[DEBUG   ] Published command details {'tgt_type': 'glob', 'jid': '20160506144758988545', 'tgt': 'jmoney-main', 'ret': '', 'user': 'root', 'arg': ['test'], 'fun': 'state.show_sls'}
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] compile template: /srv/pillar/top.sls
[DEBUG   ] Jinja search path: ['/srv/pillar', '/srv/spm/pillar']
[PROFILE ] Time (in seconds) to render '/srv/pillar/top.sls' using 'jinja' renderer: 0.00115489959717
[DEBUG   ] Rendered data from file: /srv/pillar/top.sls:
base:
  '*':
     - test

[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Results of YAML rendering:
OrderedDict([('base', OrderedDict([('*', ['test'])]))])
[PROFILE ] Time (in seconds) to render '/srv/pillar/top.sls' using 'yaml' renderer: 0.00183200836182
[DEBUG   ] compound_match: jmoney-main ? *
[DEBUG   ] compound_match jmoney-main ? "*" => "True"
[DEBUG   ] compile template: /srv/pillar/test.sls
[DEBUG   ] Jinja search path: ['/srv/pillar', '/srv/spm/pillar']
[PROFILE ] Time (in seconds) to render '/srv/pillar/test.sls' using 'jinja' renderer: 0.000955104827881
[DEBUG   ] Rendered data from file: /srv/pillar/test.sls:

test: {{ grains.username }}


[DEBUG   ] Results of YAML rendering:
OrderedDict([('test', OrderedDict([(OrderedDict([('grains.username', None)]), None)]))])
[PROFILE ] Time (in seconds) to render '/srv/pillar/test.sls' using 'yaml' renderer: 0.00114703178406
[INFO    ] Got return from jmoney-main for job 20160506144758988545
[DEBUG   ] Sending event - data = {'fun_args': ['test'], 'jid': '20160506144758988545', 'return': "Passed invalid arguments to state.show_sls: unhashable type: 'dict'\n\n    Display the state data from a specific sls or list of sls files on the\n    master. The default environment is ``base``, use ``saltenv`` (``env`` in\n    Salt 0.17.x and older) to specify a different environment.\n\n    This function does not support topfiles.  For ``top.sls`` please use\n    ``show_top`` instead.\n\n    Custom Pillar data can be passed with the ``pillar`` kwarg.\n\n    CLI Example:\n\n    .. code-block:: bash\n\n        salt '*' state.show_sls core,edit.vim dev\n    ", 'success': False, 'cmd': '_return', '_stamp': '2016-05-06T20:47:59.219839', 'fun': 'state.show_sls', 'id': 'jmoney-main', 'out': 'nested'}
```
```
# salt-minion -l debug
...
[INFO    ] User root Executing command state.show_sls with jid 20160506144758988545
[DEBUG   ] Command details {'tgt_type': 'glob', 'jid': '20160506144758988545', 'tgt': 'jmoney-main', 'ret': '', 'user': 'root', 'arg': ['test'], 'fun': 'state.show_sls'}
[INFO    ] Starting a new job with PID 26745
[DEBUG   ] LazyLoaded state.show_sls
[DEBUG   ] LazyLoaded saltutil.is_running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'jmoney-main', 'tcp://127.0.0.1:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'jmoney-main', 'tcp://127.0.0.1:4506')
[DEBUG   ] Determining pillar cache
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'jmoney-main', 'tcp://127.0.0.1:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'jmoney-main', 'tcp://127.0.0.1:4506')
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[CRITICAL] Could not deserialize msgpack message: ��test���grains.username��This often happens when trying to read a file not in binary mode.Please open an issue and include the following error: unhashable type: 'dict'
[WARNING ] Passed invalid arguments to state.show_sls: unhashable type: 'dict'

    Display the state data from a specific sls or list of sls files on the
    master. The default environment is ``base``, use ``saltenv`` (``env`` in
    Salt 0.17.x and older) to specify a different environment.

    This function does not support topfiles.  For ``top.sls`` please use
    ``show_top`` instead.

    Custom Pillar data can be passed with the ``pillar`` kwarg.

    CLI Example:

    .. code-block:: bash

        salt '*' state.show_sls core,edit.vim dev

Traceback (most recent call last):
  File "/root/salt/salt/minion.py", line 1077, in _thread_return
    return_data = func(*args, **kwargs)
  File "/root/salt/salt/modules/state.py", line 1205, in show_sls
    st_ = salt.state.HighState(opts, pillar)
  File "/root/salt/salt/state.py", line 3200, in __init__
    self.state = State(self.opts, pillar, jid, proxy=proxy, mocked=mocked)
  File "/root/salt/salt/state.py", line 627, in __init__
    self.opts['pillar'] = self._gather_pillar()
  File "/root/salt/salt/state.py", line 651, in _gather_pillar
    ret = pillar.compile_pillar()
  File "/root/salt/salt/pillar/__init__.py", line 170, in compile_pillar
    dictkey='pillar',
  File "/root/salt/salt/utils/async.py", line 74, in wrap
    ret = self._block_future(ret)
  File "/root/salt/salt/utils/async.py", line 84, in _block_future
    return future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 879, in run
    yielded = self.gen.send(value)
  File "/root/salt/salt/transport/zeromq.py", line 163, in crypted_transfer_decode_dictentry
    raise tornado.gen.Return(pcrypt.loads(ret[dictkey]))
  File "/root/salt/salt/crypt.py", line 1196, in loads
    return self.serial.loads(data[len(self.PICKLE_PAD):])
  File "/root/salt/salt/payload.py", line 117, in loads
    return msgpack.loads(msg, use_list=True)
  File "_unpacker.pyx", line 119, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:119)
TypeError: unhashable type: 'dict'
[DEBUG   ] Minion return retry timer set to 9 seconds (randomized)
[INFO    ] Returning information for job: 20160506144758988545
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'jmoney-main', 'tcp://127.0.0.1:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'jmoney-main', 'tcp://127.0.0.1:4506')
```
### versions
```yaml
# salt jmoney-main test.versions
jmoney-main:
    Salt Version:
               Salt: 2015.8.8-137-g0a77c22

    Dependency Versions:
             Jinja2: 2.7.3
           M2Crypto: 0.21.1
               Mako: 1.0.0
             PyYAML: 3.11
              PyZMQ: 14.4.0
             Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5
               cffi: 0.8.6
           cherrypy: Not Installed
           dateutil: Not Installed
              gitdb: 0.5.4
          gitpython: 0.3.2 RC1
              ioflo: Not Installed
            libgit2: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.2
       mysql-python: Not Installed
          pycparser: 2.10
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: 0.8.2
            timelib: Not Installed

    System Versions:
               dist: debian 8.4
            machine: x86_64
            release: 3.16.0-4-amd64
             system: debian 8.4
```

**Comment by jfindlay** [comment]
Same for state files:

### configs
```sls
# cat /srv/salt/test.sls
{% raw %}
test: {{ grains.username }}
{% endraw %}

echo:
  cmd.run:
    - name: echo
```
### commands
```console
# salt jmoney-main state.show_sls test
jmoney-main:
    The minion function caused an exception: Traceback (most recent call last):
      File "/root/salt/salt/minion.py", line 1077, in _thread_return
        return_data = func(*args, **kwargs)
      File "/root/salt/salt/modules/state.py", line 1210, in show_sls
        high_, errors = st_.render_highstate({saltenv: mods})
      File "/root/salt/salt/state.py", line 2981, in render_highstate
        sls, saltenv, mods, matches)
      File "/root/salt/salt/state.py", line 2709, in render_state
        self._handle_state_decls(state, sls, saltenv, errors)
      File "/root/salt/salt/state.py", line 2877, in _handle_state_decls
        if key.startswith('_'):
    AttributeError: 'OrderedDict' object has no attribute 'startswith'
```
### logs
```
# salt-master -l debug
...
[DEBUG   ] Sending event - data = {'_stamp': '2016-05-06T21:08:07.031947', 'minions': ['jmoney-main']}
[DEBUG   ] Sending event - data = {'tgt_type': 'glob', 'jid': '20160506150807031678', 'tgt': 'jmoney-main', '_stamp': '2016-05-06T21:08:07.032280', 'user': 'root', 'arg': ['test'], 'fun': 'state.show_sls', 'minions': ['jmoney-main']}
[DEBUG   ] Adding minions for job %s%s: %s
[INFO    ] User root Published command state.show_sls with jid 20160506150807031678
[DEBUG   ] Published command details {'tgt_type': 'glob', 'jid': '20160506150807031678', 'tgt': 'jmoney-main', 'ret': '', 'user': 'root', 'arg': ['test'], 'fun': 'state.show_sls'}
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] compile template: /srv/pillar/top.sls
[DEBUG   ] Jinja search path: ['/srv/pillar', '/srv/spm/pillar']
[PROFILE ] Time (in seconds) to render '/srv/pillar/top.sls' using 'jinja' renderer: 0.00146007537842
[DEBUG   ] Rendered data from file: /srv/pillar/top.sls:
base:
  '*':
     - test

[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Results of YAML rendering:
OrderedDict([('base', OrderedDict([('*', ['test'])]))])
[PROFILE ] Time (in seconds) to render '/srv/pillar/top.sls' using 'yaml' renderer: 0.00175189971924
[DEBUG   ] compound_match: jmoney-main ? *
[DEBUG   ] compound_match jmoney-main ? "*" => "True"
[DEBUG   ] compile template: /srv/pillar/test.sls
[DEBUG   ] Jinja search path: ['/srv/pillar', '/srv/spm/pillar']
[PROFILE ] Time (in seconds) to render '/srv/pillar/test.sls' using 'jinja' renderer: 0.000915050506592
[DEBUG   ] Rendered data from file: /srv/pillar/test.sls:

test: tset


[DEBUG   ] Results of YAML rendering:
OrderedDict([('test', 'tset')])
[PROFILE ] Time (in seconds) to render '/srv/pillar/test.sls' using 'yaml' renderer: 0.000931024551392
[DEBUG   ] Sending event - data = {'_stamp': '2016-05-06T21:08:07.150785', 'pretag': None, 'cmd': '_minion_event', 'tag': '_salt_error', 'data': {'message': 'The minion function caused an exception', 'args': ['The minion function caused an exception'], '_stamp': '2016-05-06T21:08:07.144568'}, 'id': 'jmoney-main'}
[ERROR   ] Received minion error from [jmoney-main]: The minion function caused an exception
[INFO    ] Got return from jmoney-main for job 20160506150807031678
[DEBUG   ] Sending event - data = {'fun_args': ['test'], 'jid': '20160506150807031678', 'return': 'The minion function caused an exception: Traceback (most recent call last):\n  File "/root/salt/salt/minion.py", line 1077, in _thread_return\n    return_data = func(*args, **kwargs)\n  File "/root/salt/salt/modules/state.py", line 1210, in show_sls\n    high_, errors = st_.render_highstate({saltenv: mods})\n  File "/root/salt/salt/state.py", line 2981, in render_highstate\n    sls, saltenv, mods, matches)\n  File "/root/salt/salt/state.py", line 2709, in render_state\n    self._handle_state_decls(state, sls, saltenv, errors)\n  File "/root/salt/salt/state.py", line 2877, in _handle_state_decls\n    if key.startswith(\'_\'):\nAttributeError: \'OrderedDict\' object has no attribute \'startswith\'\n', 'success': False, 'cmd': '_return', '_stamp': '2016-05-06T21:08:07.278535', 'fun': 'state.show_sls', 'id': 'jmoney-main', 'out': 'nested'}
```
```
# salt-minion -l debug
...
[INFO    ] User root Executing command state.show_sls with jid 20160506150807031678
[DEBUG   ] Command details {'tgt_type': 'glob', 'jid': '20160506150807031678', 'tgt': 'jmoney-main', 'ret': '', 'user': 'root', 'arg': ['test'], 'fun': 'state.show_sls'}
[INFO    ] Starting a new job with PID 28562
[DEBUG   ] LazyLoaded state.show_sls
[DEBUG   ] LazyLoaded saltutil.is_running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'jmoney-main', 'tcp://127.0.0.1:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'jmoney-main', 'tcp://127.0.0.1:4506')
[DEBUG   ] Determining pillar cache
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'jmoney-main', 'tcp://127.0.0.1:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'jmoney-main', 'tcp://127.0.0.1:4506')
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] In saltenv 'base', looking at rel_path u'test.sls' to resolve u'salt://test.sls'
[DEBUG   ] In saltenv 'base', ** considering ** path u'/var/cache/salt/minion/files/base/test.sls' to resolve u'salt://test.sls'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** u'salt://test.sls'
[DEBUG   ] No dest file found
[INFO    ] Fetching file from saltenv 'base', ** done ** u'test.sls'
[DEBUG   ] compile template: /var/cache/salt/minion/files/base/test.sls
[DEBUG   ] Jinja search path: ['/var/cache/salt/minion/files/base']
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/test.sls' using 'jinja' renderer: 0.00375509262085
[DEBUG   ] Rendered data from file: /var/cache/salt/minion/files/base/test.sls:

test: {{ grains.username }}


echo:
  cmd.run:
    - name: echo

[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Results of YAML rendering:
OrderedDict([('test', OrderedDict([(OrderedDict([('grains.username', None)]), None)])), ('echo', OrderedDict([('cmd.run', [OrderedDict([('name', 'echo')])])]))])
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/test.sls' using 'yaml' renderer: 0.00286507606506
[WARNING ] The minion function caused an exception
Traceback (most recent call last):
  File "/root/salt/salt/minion.py", line 1077, in _thread_return
    return_data = func(*args, **kwargs)
  File "/root/salt/salt/modules/state.py", line 1210, in show_sls
    high_, errors = st_.render_highstate({saltenv: mods})
  File "/root/salt/salt/state.py", line 2981, in render_highstate
    sls, saltenv, mods, matches)
  File "/root/salt/salt/state.py", line 2709, in render_state
    self._handle_state_decls(state, sls, saltenv, errors)
  File "/root/salt/salt/state.py", line 2877, in _handle_state_decls
    if key.startswith('_'):
AttributeError: 'OrderedDict' object has no attribute 'startswith'
[DEBUG   ] SaltEvent PUB socket URI: ipc:///var/run/salt/minion/minion_event_3f1c9a06f3_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: ipc:///var/run/salt/minion/minion_event_3f1c9a06f3_pull.ipc
[DEBUG   ] Sending event - data = {'message': u'The minion function caused an exception', 'args': ('The minion function caused an exception',), '_stamp': '2016-05-06T21:08:07.144568'}
[DEBUG   ] Handling event "_salt_error\n\n\x83\xa7message\xda\x00'The minion function caused an exception\xa4args\x91\xda\x00'The minion function caused an exception\xa6_stamp\xba2016-05-06T21:08:07.144568"
[DEBUG   ] Forwarding salt error event tag=_salt_error
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'jmoney-main', 'tcp://127.0.0.1:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'jmoney-main', 'tcp://127.0.0.1:4506')
[DEBUG   ] Minion return retry timer set to 9 seconds (randomized)
[INFO    ] Returning information for job: 20160506150807031678
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'jmoney-main', 'tcp://127.0.0.1:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'jmoney-main', 'tcp://127.0.0.1:4506')
```
