### ISSUE TITLE
pkg.installed: - sources broken

### ISSUE THREAD

**Issue by edgan** [saltstack/salt#33104]
I am trying to install a package that is on the salt master or salt-ssh host with sources. It is in the documentation. It seems to be a feature dating back to at least 2013.

```
State:
install_wkhtmltox:
  pkg.installed:
    - sources:
      - wkhtmltox: salt://wkhtmlox.deb


Results:
----------
          ID: install_wkhtmltox
    Function: pkg.installed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1626, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1492, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/pkg.py", line 1103, in installed
                  **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/aptpkg.py", line 562, in install
                  deb_info = __salt__['lowpkg.bin_pkg_info'](pkg_source)
                File "/usr/lib/python2.7/dist-packages/salt/modules/dpkg.py", line 64, in bin_pkg_info
                  if not os.path.exists(path):
                File "/usr/lib/python2.7/genericpath.py", line 18, in exists
                  os.stat(path)
              TypeError: coercing to Unicode: need string or buffer, bool found
     Started: 16:04:57.367567
    Duration: 8.123 ms
     Changes:

Distribution:
Ubuntu 14.04

Versions:
2015.8.8+ds-2
2016.3.0rc2
```

**Comment by edgan** [comment]
The actual bug is that you get this error if it can't find the file you specified. It should give a more obvious error. It does work if it can find the file.

**Comment by Ch3LL** [comment]
@edgan thank you for the report. I have confirmed this behavior using your state.sls as shown below:


```
ch3ll-master:
----------
          ID: install_wkhtmltox
    Function: pkg.installed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/home/ch3ll/git/salt/salt/state.py", line 1703, in call
                  **cdata['kwargs'])
                File "/home/ch3ll/git/salt/salt/loader.py", line 1649, in wrapper
                  return f(*args, **kwargs)
                File "/home/ch3ll/git/salt/salt/states/pkg.py", line 1192, in installed
                  **kwargs)
                File "/home/ch3ll/git/salt/salt/modules/yumpkg.py", line 1039, in install
                  rpm_info = __salt__['lowpkg.bin_pkg_info'](pkg_source)
                File "/home/ch3ll/git/salt/salt/modules/rpm.py", line 96, in bin_pkg_info
                  if not os.path.exists(path):
                File "/usr/lib64/python2.7/genericpath.py", line 18, in exists
                  os.stat(path)
              TypeError: coercing to Unicode: need string or buffer, bool found
     Started: 11:42:59.395050
    Duration: 1472.679 ms
     Changes:   

Summary for ch3ll-master
------------
Succeeded: 0
Failed:    1
```

Another thing to note is I changed your sls file slightly and I thne got a good error. Here is the edited sls file that works. 

```
install_wkhtmltox:
  pkg.installed:
    - sources:
      - screen: salt://wkhtmlox.deb
```

I simply changed it from wkhtmltox to screen and saw a more appropriate error:

```
ch3ll-master.c7.saltstack.net:
----------
          ID: install_wkhtmltox
    Function: pkg.installed
      Result: False
     Comment: Unable to cache salt://wkhtmlox.deb: file not found
     Started: 11:45:16.413562
    Duration: 1415.374 ms
     Changes:   

Summary for ch3ll-master.c7.saltstack.net
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
```

If you change this are you also seeing the more appropriate error message above?

**Comment by Ch3LL** [comment]
Also for clarity I was using this version of salt:

```
➜  cloud.maps.d salt --versions-report
Salt Version:
           Salt: 2016.3.0rc2-419-gaed7bed
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.4.5.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

**Comment by edgan** [comment]
Yes, it works for the same for me. It seems like the name of the package needs to be a valid name in the apt repository, or the deb needs to exist adding it's package name to the list.

**Comment by Ch3LL** [comment]
Ahh yeah good observation. To confirm that theory:

```
install_wkhtmltox:
  pkg.installed:
    - sources:
      - jskdf: salt://wkhtmlox.deb
```

Also caused the Unicode error.

**Comment by gaetanquentin** [comment]
So how to install independant rpm.deb not in repository?
