### ISSUE TITLE
2016.3 highstate fails "Cannot set attribute"

### ISSUE THREAD

**Issue by jakehilton** [saltstack/salt#33143]
### Description of Issue/Question
Fresh install of 2016.3 on an Ubuntu 14.04 system and when I run a highstate on the box I get the following error:
```
[DEBUG   ] Local cache dir: '/var/cache/salt/minion/files/base/_proxy'
[DEBUG   ] Refreshing modules...
......
Passed invalid arguments: Cannot set attribute.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 196, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 594, in highstate
    whitelist=kwargs.get('whitelist')
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 3173, in call_highstate
    self.load_dynamic(matches)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2706, in load_dynamic
    self.state.module_refresh()
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 857, in module_refresh
    reload(site)
  File "/usr/lib/python2.7/site.py", line 563, in <module>
    main()
  File "/usr/lib/python2.7/site.py", line 541, in main
    abs__file__()
  File "/usr/lib/python2.7/site.py", line 100, in abs__file__
    m.__file__ = os.path.abspath(m.__file__)
  File "/usr/local/lib/python2.7/dist-packages/gevent/__init__.py", line 87, in __setattr__
    raise TypeError("Cannot set attribute")
TypeError: Cannot set attribute
```

### Setup
We have gevent 1.1.1 (latest stable) installed because need it for pymongo 3 on the box. This seems to cause the issue. This was addressed in 2015.8 with this PR: https://github.com/saltstack/salt/pull/31627

I feel it's somewhat of a bandaid. I'm not sure if it's a gevent shortcoming or the way this particular implementation is used from salt.

### Steps to Reproduce Issue
Install Ubuntu 14.04 with 2016.3 and have gevent 1.1.1 installed and run a highstate.

### Versions Report
```
Salt Version:
           Salt: 2016.3.0

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.22
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.4.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: 0.6.5
        Tornado: 4.3
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: 1.5.1
        libgit2: Not Installed
        libnacl: 1.4.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-85-generic
         system: Ubuntu 14.04 trusty
```

**Comment by cachedout** [comment]
This strikes me as a bug that should be filed upstream with the gevent folks.

**Comment by jfindlay** [comment]
Since the upstream bug has been fixed and closed, I'm going to close this as well.  Thanks for your work on this, @jakehilton.

**Comment by jakehilton** [comment]
gevent 1.1.2 that was released today has a fix for this in it.
