### ISSUE TITLE
salt-ssh nun working, if DNS down

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#33168]
### Description of Issue/Question
If the DNS on the remote-host is not reachable or not configured, I can't use salt-ssh at all.

### Setup

```
salt:/srv # salt-ssh --version
salt-ssh 2015.8.3 (Beryllium)

```
### Steps to Reproduce Issue
I run: salt-ssh remote-host test.ping

```
        Traceback (most recent call last):
          File "/tmp/.root_dcdf8c_salt/salt-call", line 4, in <module>
            salt_call()
          File "/tmp/.root_dcdf8c_salt/salt/scripts.py", line 330, in salt_call
            client = salt.cli.call.SaltCall()
          File "/tmp/.root_dcdf8c_salt/salt/utils/parsers.py", line 128, in __init__
            optparse.OptionParser.__init__(self, *args, **kwargs)
          File "/usr/lib64/python2.7/optparse.py", line 1219, in __init__
            add_help=add_help_option)
          File "/tmp/.root_dcdf8c_salt/salt/utils/parsers.py", line 204, in _populate_option_list
            mixin_setup_func(self)
          File "/tmp/.root_dcdf8c_salt/salt/utils/parsers.py", line 1029, in _mixin_setup
            config.minion_config(None)
          File "/tmp/.root_dcdf8c_salt/salt/config.py", line 1595, in minion_config
            opts = apply_minion_config(overrides, defaults, cache_minion_id=cache_minion_id)
          File "/tmp/.root_dcdf8c_salt/salt/config.py", line 2731, in apply_minion_config
            cache_minion_id=cache_minion_id)
          File "/tmp/.root_dcdf8c_salt/salt/config.py", line 2698, in get_id
            newid = salt.utils.network.generate_minion_id()
          File "/tmp/.root_dcdf8c_salt/salt/utils/network.py", line 281, in generate_minion_id
            possible_ids = get_hostnames()
          File "/tmp/.root_dcdf8c_salt/salt/utils/network.py", line 195, in get_hostnames
            socket.SOL_TCP, socket.AI_CANONNAME
        socket.error: [Errno 111] Connection refused

```

We discovered, that we can set the minion_id by hand by setting `/etc/salt/minion_id`.

Now the traceback looks like this:
```
        [CRITICAL] Unable to import msgpack or msgpack_pure python modules
        Traceback (most recent call last):
          File "/tmp/.root_dcdf8c_salt/salt-call", line 4, in <module>
            salt_call()
          File "/tmp/.root_dcdf8c_salt/salt/scripts.py", line 331, in salt_call
            client.run()
          File "/tmp/.root_dcdf8c_salt/salt/cli/call.py", line 43, in run
            caller = salt.cli.caller.Caller.factory(self.config)
          File "/tmp/.root_dcdf8c_salt/salt/cli/caller.py", line 78, in factory
            return ZeroMQCaller(opts, **kwargs)
          File "/tmp/.root_dcdf8c_salt/salt/cli/caller.py", line 269, in __init__
            super(ZeroMQCaller, self).__init__(opts)
          File "/tmp/.root_dcdf8c_salt/salt/cli/caller.py", line 101, in __init__
            self.minion = salt.minion.SMinion(opts)
          File "/tmp/.root_dcdf8c_salt/salt/minion.py", line 511, in __init__
            opts['grains'] = salt.loader.grains(opts)
          File "/tmp/.root_dcdf8c_salt/salt/loader.py", line 624, in grains
            ret = fun()
          File "/tmp/.root_dcdf8c_salt/salt/grains/core.py", line 1424, in hostname
            grains['fqdn'] = salt.utils.network.get_fqhostname()
          File "/tmp/.root_dcdf8c_salt/salt/utils/network.py", line 331, in get_fqhostname
            socket.SOL_TCP, socket.AI_CANONNAME
        socket.error: [Errno 111] Connection refused
```

### Versions Report
```
salt:/srv # salt --versions-report
Salt Version:
           Salt: 2015.8.3
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.22
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.1.0
         Python: 2.7.3 (default, Apr 14 2012, 08:58:41) [GCC]
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.2
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.1
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: 0.21.2
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: SuSE 12.3 x86_64
        machine: x86_64
        release: 3.7.10-1.40-desktop
         system: openSUSE  12.3 x86_64
```

# Question

Is this intentional? 

Does salt (or salt-ssh) support running on hosts where `get_fqhostname` does not work?

**Comment by guettli** [comment]
We have found the reason:

```
remote-host:~ # LANG=C hostname --fqdn
hostname: System error
```

after adding the ip-hostname mapping to `/etc/hosts` it worked.

I close this again.
