### ISSUE TITLE
Unable to unlink pid file results in maximum recursion exceeded

### ISSUE THREAD

**Issue by robnagler** [saltstack/salt#33175]
### Description of Issue/Question

First part of the output:

``` text
[2.7.10;@v minions]$ salt-master -l debug
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: v
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] Setting up the Salt Master
[WARNING ] Unable to bind socket, error: [Errno 98] Address already in use
[INFO    ] The Salt Master is shut down
[ERROR   ] [Errno 13] Permission denied: '/var/run/salt-master.pid'
Traceback (most recent call last):
  File "/home/vagrant/src/robnagler/salt/salt/utils/parsers.py", line 252, in exit
    mixin_before_exit_func(self)
  File "/home/vagrant/src/robnagler/salt/salt/utils/parsers.py", line 876, in _mixin_before_exit
    os.unlink(self.config['pidfile'])
OSError: [Errno 13] Permission denied: '/var/run/salt-master.pid'
Usage: salt-master

[ERROR   ] [Errno 13] Permission denied: '/var/run/salt-master.pid'
Traceback (most recent call last):
  File "/home/vagrant/src/robnagler/salt/salt/utils/parsers.py", line 252, in exit
    mixin_before_exit_func(self)
  File "/home/vagrant/src/robnagler/salt/salt/utils/parsers.py", line 876, in _mixin_before_exit
    os.unlink(self.config['pidfile'])
OSError: [Errno 13] Permission denied: '/var/run/salt-master.pid'
Usage: salt-master

[ERROR   ] [Errno 13] Permission denied: '/var/run/salt-master.pid'
Traceback (most recent call last):
  File "/home/vagrant/src/robnagler/salt/salt/utils/parsers.py", line 252, in exit
    mixin_before_exit_func(self)
  File "/home/vagrant/src/robnagler/salt/salt/utils/parsers.py", line 876, in _mixin_before_exit
    os.unlink(self.config['pidfile'])
OSError: [Errno 13] Permission denied: '/var/run/salt-master.pid'
Usage: salt-master
```

Bottom of the output:

``` text
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/optparse.py", line 1584, in error
    self.exit(2, "%s: error: %s\n" % (self.get_prog_name(), msg))
  File "/home/vagrant/src/robnagler/salt/salt/utils/parsers.py", line 257, in exit
    mixin_before_exit_func, traceback.format_exc(err)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/optparse.py", line 1584, in error
    self.exit(2, "%s: error: %s\n" % (self.get_prog_name(), msg))
  File "/home/vagrant/src/robnagler/salt/salt/utils/parsers.py", line 257, in exit
    mixin_before_exit_func, traceback.format_exc(err)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/optparse.py", line 1584, in error
    self.exit(2, "%s: error: %s\n" % (self.get_prog_name(), msg))
  File "/home/vagrant/src/robnagler/salt/salt/utils/parsers.py", line 257, in exit
    mixin_before_exit_func, traceback.format_exc(err)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/optparse.py", line 1584, in error
    self.exit(2, "%s: error: %s\n" % (self.get_prog_name(), msg))
  File "/home/vagrant/src/robnagler/salt/salt/utils/parsers.py", line 257, in exit
    mixin_before_exit_func, traceback.format_exc(err)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/optparse.py", line 1584, in error
    self.exit(2, "%s: error: %s\n" % (self.get_prog_name(), msg))
  File "/home/vagrant/src/robnagler/salt/salt/utils/parsers.py", line 257, in exit
    mixin_before_exit_func, traceback.format_exc(err)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/optparse.py", line 1584, in error
    self.exit(2, "%s: error: %s\n" % (self.get_prog_name(), msg))
  File "/home/vagrant/src/robnagler/salt/salt/utils/parsers.py", line 257, in exit
    mixin_before_exit_func, traceback.format_exc(err)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/optparse.py", line 1584, in error
    self.exit(2, "%s: error: %s\n" % (self.get_prog_name(), msg))
  File "/home/vagrant/src/robnagler/salt/salt/utils/parsers.py", line 254, in exit
    logging.getLogger(__name__).exception(err)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/logging/__init__.py", line 1198, in exception
    self.error(msg, *args, **kwargs)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/logging/__init__.py", line 1191, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/home/vagrant/src/robnagler/salt/salt/log/setup.py", line 310, in _log
    self, level, msg, args, exc_info=exc_info, extra=extra
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/logging/__init__.py", line 1284, in _log
    self.handle(record)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/logging/__init__.py", line 1294, in handle
    self.callHandlers(record)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/logging/__init__.py", line 1334, in callHandlers
    hdlr.handle(record)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/logging/__init__.py", line 757, in handle
    self.emit(record)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/logging/handlers.py", line 430, in emit
    logging.FileHandler.emit(self, record)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/logging/__init__.py", line 955, in emit
    StreamHandler.emit(self, record)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/logging/__init__.py", line 887, in emit
    self.handleError(record)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/logging/__init__.py", line 810, in handleError
    None, sys.stderr)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/traceback.py", line 125, in print_exception
    print_tb(tb, limit, file)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/traceback.py", line 69, in print_tb
    line = linecache.getline(filename, lineno, f.f_globals)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/linecache.py", line 14, in getline
    lines = getlines(filename, module_globals)
  File "/home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/linecache.py", line 41, in getlines
    return updatecache(filename, module_globals)
RuntimeError: maximum recursion depth exceeded
```
### Setup

Testing on Vagrant as user vagrant running salt-master. The /var/run directory is not writable so the unlink fails. Need to avoid recursion in exit routines.
### Steps to Reproduce Issue

You can also reproduce by killing the master with TERM or INT.
### Versions Report

Just forked the the develop (a599be9) branch.

``` text
Salt Version:
           Salt: 2016.3.0-521-ga599be9

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.10 (default, Nov 14 2015, 01:41:47)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.2

System Versions:
           dist: fedora 21 Twenty One
        machine: x86_64
        release: 4.1.12-101.fc21.x86_64
         system: Linux
        version: Fedora 21 Twenty One
```

**Comment by Ch3LL** [comment]
@robnagler I am able to replicate this. Here is my test case:

**SETUP:**

```
root@vagrant-ubuntu-trusty-64:/home/vagrant/salt# salt --versions-report
Salt Version:
           Salt: 2016.3.0-526-g0138de8
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.2
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-65-generic
         system: Linux
```

Master Config File:

```
root@vagrant-ubuntu-trusty-64:/home/vagrant/salt# cat /etc/salt/master 
log_level: debug
user: vagrant
```

Add privileges for vagrant user:


`sudo chown -R vagrant /etc/salt /var/cache/salt /var/log/salt /var/run/salt`

Running (as vagrant user):

1. Start first salt-master daemon: `salt-master -d`
2. Run `salt-master -ldebug`

errors in /var/log/salt/master:

```
2016-05-12 18:29:30,790 [salt.utils.verify][WARNING ][14962] Insecure logging configuration detected! Sensitive data may be logged.
2016-05-12 18:29:30,791 [salt.cli.daemons ][INFO    ][14962] Setting up the Salt Master
2016-05-12 18:29:30,791 [salt.utils.verify][WARNING ][14962] Unable to bind socket, error: [Errno 98] Address already in use
2016-05-12 18:29:30,792 [salt.cli.daemons ][INFO    ][14962] The Salt Master is shut down
2016-05-12 18:29:30,793 [salt.utils.parsers][ERROR   ][14962] [Errno 13] Permission denied: '/var/run/salt-master.pid'
Traceback (most recent call last):
  File "/home/vagrant/salt/salt/utils/parsers.py", line 252, in exit
    mixin_before_exit_func(self)
  File "/home/vagrant/salt/salt/utils/parsers.py", line 876, in _mixin_before_exit
    os.unlink(self.config['pidfile'])
OSError: [Errno 13] Permission denied: '/var/run/salt-master.pid'
2016-05-12 18:29:30,796 [salt.utils.parsers][ERROR   ][14962] [Errno 13] Permission denied: '/var/run/salt-master.pid'
Traceback (most recent call last):
  File "/home/vagrant/salt/salt/utils/parsers.py", line 252, in exit
    mixin_before_exit_func(self)
  File "/home/vagrant/salt/salt/utils/parsers.py", line 876, in _mixin_before_exit
    os.unlink(self.config['pidfile'])
OSError: [Errno 13] Permission denied: '/var/run/salt-master.pid'
2016-05-12 18:29:30,799 [salt.utils.parsers][ERROR   ][14962] [Errno 13] Permission denied: '/var/run/salt-master.pid'
Traceback (most recent call last):
  File "/home/vagrant/salt/salt/utils/parsers.py", line 252, in exit
    mixin_before_exit_func(self)
  File "/home/vagrant/salt/salt/utils/parsers.py", line 876, in _mixin_before_exit
    os.unlink(self.config['pidfile'])
OSError: [Errno 13] Permission denied: '/var/run/salt-master.pid'
2016-05-12 18:29:30,801 [salt.utils.parsers][ERROR   ][14962] [Errno 13] Permission denied: '/var/run/salt-master.pid'
Traceback (most recent call last):
  File "/home/vagrant/salt/salt/utils/parsers.py", line 252, in exit
    mixin_before_exit_func(self)
  File "/home/vagrant/salt/salt/utils/parsers.py", line 876, in _mixin_before_exit
    os.unlink(self.config['pidfile'])
OSError: [Errno 13] Permission denied: '/var/run/salt-master.pid'
```

```
OSError: [Errno 13] Permission denied: '/var/run/salt-master.pid'
2016-05-12 18:29:31,255 [salt.log.setup   ][ERROR   ][14962] An un-handled exception was caught by salt's global exception handler:
RuntimeError: maximum recursion depth exceeded
Traceback (most recent call last):
  File "/usr/local/bin/salt-master", line 10, in <module>
    execfile(__file__)
  File "/home/vagrant/salt/scripts/salt-master", line 22, in <module>
    salt_master()
  File "/home/vagrant/salt/salt/scripts.py", line 49, in salt_master
    master.start()
  File "/home/vagrant/salt/salt/cli/daemons.py", line 210, in start
    super(Master, self).start()
  File "/home/vagrant/salt/salt/utils/parsers.py", line 940, in start
    self.prepare()
  File "/home/vagrant/salt/salt/cli/daemons.py", line 185, in prepare
    self.shutdown(4, 'The ports are not available to bind')
  File "/home/vagrant/salt/salt/cli/daemons.py", line 226, in shutdown
    super(Master, self).shutdown(exitcode, exitmsg)
  File "/home/vagrant/salt/salt/utils/parsers.py", line 953, in shutdown
    self.exit(exitcode, exitmsg)
  File "/home/vagrant/salt/salt/utils/parsers.py", line 257, in exit
    mixin_before_exit_func, traceback.format_exc(err)
  File "/usr/lib/python2.7/optparse.py", line 1584, in error
    self.exit(2, "%s: error: %s\n" % (self.get_prog_name(), msg))
......
    self.exit(2, "%s: error: %s\n" % (self.get_prog_name(), msg))
  File "/home/vagrant/salt/salt/utils/parsers.py", line 257, in exit
    mixin_before_exit_func, traceback.format_exc(err)
  File "/usr/lib/python2.7/optparse.py", line 1584, in error
    self.exit(2, "%s: error: %s\n" % (self.get_prog_name(), msg))
  File "/home/vagrant/salt/salt/utils/parsers.py", line 254, in exit
    logging.getLogger(__name__).exception(err)
  File "/usr/lib/python2.7/logging/__init__.py", line 1185, in exception
    self.error(msg, *args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1178, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/home/vagrant/salt/salt/log/setup.py", line 310, in _log
    self, level, msg, args, exc_info=exc_info, extra=extra
  File "/usr/lib/python2.7/logging/__init__.py", line 1271, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1281, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1321, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 749, in handle
    self.emit(record)
  File "/usr/lib/python2.7/logging/handlers.py", line 429, in emit
    logging.FileHandler.emit(self, record)
  File "/usr/lib/python2.7/logging/__init__.py", line 942, in emit
    StreamHandler.emit(self, record)
  File "/usr/lib/python2.7/logging/__init__.py", line 879, in emit
    self.handleError(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 802, in handleError
    None, sys.stderr)
  File "/usr/lib/python2.7/traceback.py", line 125, in print_exception
    print_tb(tb, limit, file)
  File "/usr/lib/python2.7/traceback.py", line 69, in print_tb
    line = linecache.getline(filename, lineno, f.f_globals)
  File "/usr/lib/python2.7/linecache.py", line 14, in getline
    lines = getlines(filename, module_globals)
  File "/usr/lib/python2.7/linecache.py", line 40, in getlines
    return updatecache(filename, module_globals)
RuntimeError: maximum recursion depth exceeded
```

and then the process dies.

This is also the case on the head of 2016.3. I tested this on the head of 2015.8 and I am not getting this error. When starting multiple processes with a `user` in the config file i get this:

```
vagrant@vagrant-ubuntu-trusty-64:~/salt$ salt-master -ldebug
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] Setting up the Salt Master
[WARNING ] Unable to bind socket, error: [Errno 98] Address already in use
The ports are not available to bind
```

I also made sure we do not get this error when not using the `user` filed in the config file.

**Comment by mattwillsher** [comment]
Same error here with a slightly different environment - under docker with salt-master running as a non-root user. 

If I `chown salt-master-user /var/run` the error goes away but then my /var/run isn't owned by root anymore. I also tried touching and chowning /var/run/salt-master.pid to no avail.

**Comment by dmuntean** [comment]
Hit same error - "RuntimeError: maximum recursion depth exceeded" when trying to start a freshly installed salt-master with the missing directory, which was defined in runner_dirs. Once the directory was created the error went away.
