### ISSUE TITLE
Allow the minion daemon to run without needing to connect to a master

### ISSUE THREAD

**Issue by justinta** [saltstack/salt#33191]
## Description of Issue/Question

It appears that `file_client: local` doesn't run the minion in masterless, as per [the docs](https://docs.saltstack.com/en/latest/topics/tutorials/quickstart.html). This doesn't appear to hinder salt-call functionality. 
### Setup

Install salt.
set `file_client: local` in minion config
Start minion in debug mode: `salt-minion -l debug` 

The debug log will output something like the following

``` bash
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: li258-167.members.linode.com
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] Setting up the Salt Minion "li258-167.members.linode.com"
[DEBUG   ] Created pidfile: /var/run/salt-minion.pid
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[WARNING ] IMPORTANT: Do not use md5 hashing algorithm! Please set "hash_type" to sha256 in Salt Minion config!
[INFO    ] The Salt Minion is starting up
[INFO    ] Minion is starting as user 'root'
[DEBUG   ] AsyncEventPublisher PUB socket URI: ipc:///var/run/salt/minion/minion_event_e813be3a56_pub.ipc
[DEBUG   ] AsyncEventPublisher PULL socket URI: ipc:///var/run/salt/minion/minion_event_e813be3a56_pull.ipc
[INFO    ] Starting pub socket on ipc:///var/run/salt/minion/minion_event_e813be3a56_pub.ipc
[INFO    ] Starting pull socket on ipc:///var/run/salt/minion/minion_event_e813be3a56_pull.ipc
[DEBUG   ] Minion 'li258-167.members.linode.com' trying to tune in
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'li258-167.members.linode.com', 'tcp://127.0.0.1:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (8780)
[DEBUG   ] Setting zmq_reconnect_ivl to '8780ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'li258-167.members.linode.com', 'tcp://127.0.0.1:4506', 'clear')
```

After a few seconds it will time out with `[DEBUG   ] SaltReqTimeoutError, retrying. (1/7)`

When running the minion in debug mode without a master specified it still attempts to reach out to a master and will time out with a SaltReqTimeoutError. Then stacktrace: 

``` bash
[WARNING ] Fatal functionality error caught by minion handler:
Traceback (most recent call last):
  File "/root/salt/salt/scripts.py", line 81, in minion_process
    minion.start()
  File "/root/salt/salt/cli/daemons.py", line 320, in start
    self.minion.tune_in()
  File "/root/salt/salt/minion.py", line 1702, in tune_in
    self.sync_connect_master()
  File "/root/salt/salt/minion.py", line 763, in sync_connect_master
    raise six.reraise(*future_exception)
  File "/usr/lib/python2.7/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/root/salt/salt/minion.py", line 770, in connect_master
    master, self.pub_channel = yield self.eval_master(self.opts, self.timeout, self.safe)
  File "/usr/lib/python2.7/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/usr/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/root/salt/salt/minion.py", line 505, in eval_master
    yield pub_channel.connect()
  File "/usr/lib/python2.7/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/usr/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/root/salt/salt/transport/zeromq.py", line 338, in connect
    yield self.auth.authenticate()
  File "/usr/lib/python2.7/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/usr/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
SaltClientError: Attempt to authenticate with the salt master failed with timeout error
```
### Versions Report

This was on the head of 2015.8

``` yaml
salt-minion --versions-report
Salt Version:
           Salt: 2015.8.8-190-ge9108e0

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 2.7.11 (default, Mar 31 2016, 06:18:34)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.2
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist:
        machine: x86_64
        release: 4.5.0-x86_64-linode65
```

**Comment by thatch45** [comment]
I wonder who wrote those docs, I don't think this was ever the intention to allow for the minion to run without a master

**Comment by thatch45** [comment]
In the note in the referenced doc it clearly states that you can't run the minion daemon in masterless

**Comment by rallytime** [comment]
Let's mark this as a feature request to be able to run the salt-minion daemon in masterless mode to make use of things like minion-side beacons and engines.

**Comment by obimod** [comment]
+1

**Comment by aboe76** [comment]
Isn't this possible with the new master_type option in the minion config?
setting master_type to disable , you can start the salt-minion daemon without a salt-master.

**Comment by thatch45** [comment]
Thanks @aboe76 ! I missed that. Once I verify it I will close this one out as complete
