### ISSUE TITLE
salt-cloud: EC2 userdata template error

### ISSUE THREAD

**Issue by ffjia** [saltstack/salt#33194]
### Description of Issue/Question

When I try to launch instance using EC2 userdata template with this #32698 change, error occurred.

```
[ERROR   ] Template does not exist:
#cloud-config

apt_sources:
  - source: "ppa:saltstack/salt"

hostname: '{{ vm['name'] }}'
fqdn: '{{ vm['name'] }}'
manage_etc_hosts: false

package_update: true
package_upgrade: false
package_reboot_if_required: false
packages:
  - python-software-properties
  - salt-minion

runcmd:
  - echo `curl http://169.254.169.254/latest/meta-data/local-ipv4` '{{ vm['name'] }}' '{{ vm['name'] }}' > /etc/hosts
  - [ rm, -f, /etc/salt/minion_id ]
  - [ sed, -i, 's/#master: salt/master: mymasterserver/', /etc/salt/minion ]
  - [ service, salt-minion, restart ]
  - [ bash, -xc, "dd if=/dev/zero of=/swapfile bs=256M count=32" ]
  - [ bash, -xc, "mkswap /swapfile" ]
  - [ bash, -xc, "swapon /swapfile" ]
  - [ sh, -xc, "echo $(date) ': runcmd part'" ]

mounts:
  - [ /swapfile, none, swap, "sw", "0", "0" ]

#phone_home:
#  url: http://api.ops.appannie.com/$INSTANCE_ID/
#  post: [ instance_id, private_ip, public_ip, region ]

final_message: "The system is finally up, after $UPTIME seconds"

[ERROR   ] There was a profile error: must be string or buffer, not dict
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 277, in run
    self.config.get('names')
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1439, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1274, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 2498, in create
    data, vm_ = request_instance(vm_, location)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 1705, in request_instance
    params[spot_prefix + 'UserData'] = base64.b64encode(userdata)
  File "/usr/lib/python2.7/base64.py", line 53, in b64encode
    encoded = binascii.b2a_base64(s)[:-1]
TypeError: must be string or buffer, not dict
```
### Versions Report

```
Salt Version:
            Salt: 2015.8.8.2

Dependency Versions:
 Apache Libcloud: 0.15.1
          Jinja2: 2.7.2
        M2Crypto: Not Installed
            Mako: Not Installed
          PyYAML: 3.10
           PyZMQ: 14.4.0
          Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
            RAET: Not Installed
         Tornado: 4.2.1
             ZMQ: 4.0.4
            cffi: Not Installed
        cherrypy: Not Installed
        dateutil: 1.5
           gitdb: Not Installed
       gitpython: Not Installed
           ioflo: Not Installed
         libgit2: Not Installed
         libnacl: Not Installed
    msgpack-pure: Not Installed
  msgpack-python: 0.3.0
    mysql-python: Not Installed
       pycparser: Not Installed
        pycrypto: 2.6.1
          pygit2: Not Installed
    python-gnupg: Not Installed
           smmap: Not Installed
         timelib: Not Installed

System Versions:
            dist: Ubuntu 14.04 trusty
         machine: x86_64
         release: 3.13.0-86-generic
          system: Ubuntu 14.04 trusty
```

Hints? Thanks in advance.

**Comment by Ch3LL** [comment]
@ffjia the PR you are referencing is in the head of 2016.3 and the develop branch. In your versions report you show as using salt version 2015.8.8.2, which this change is not in that code. Do you still see this behavior at the head of 2016.3?

**Comment by Ch3LL** [comment]
I apologize it looks like this PR is only on  the develop. So please let me know if you see this same behavior on the develop branch. Thanks.

**Comment by ffjia** [comment]
@Ch3LL I can reproduce it on develop branch.

```
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] compile template:
#cloud-config

apt_sources:
  - source: "ppa:saltstack/salt"

hostname: '{{ vm['name'] }}'
fqdn: '{{ vm['name'] }}'
manage_etc_hosts: false

package_update: true
package_upgrade: false
package_reboot_if_required: false
packages:
  - python-software-properties
  - salt-minion

runcmd:
  - echo `curl http://169.254.169.254/latest/meta-data/local-ipv4` '{{ vm['name'] }}' '{{ vm['name'] }}' > /etc/hosts
  - [ rm, -f, /etc/salt/minion_id ]
  - [ sed, -i, 's/#master: salt/master: mymasterserver/', /etc/salt/minion ]
  - [ service, salt-minion, restart ]
  - [ bash, -xc, "dd if=/dev/zero of=/swapfile bs=256M count=32" ]
  - [ bash, -xc, "mkswap /swapfile" ]
  - [ bash, -xc, "swapon /swapfile" ]
  - [ sh, -xc, "echo $(date) ': runcmd part'" ]

#phone_home:
#  url: http://api.ops.appannie.com/$INSTANCE_ID/
#  post: [ instance_id, private_ip, public_ip, region ]

final_message: "The system is finally up, after $UPTIME seconds"

[ERROR   ] Template does not exist:
#cloud-config

apt_sources:
  - source: "ppa:saltstack/salt"

hostname: '{{ vm['name'] }}'
fqdn: '{{ vm['name'] }}'
manage_etc_hosts: false

package_update: true
package_upgrade: false
package_reboot_if_required: false
packages:
  - python-software-properties
  - salt-minion

runcmd:
  - echo `curl http://169.254.169.254/latest/meta-data/local-ipv4` '{{ vm['name'] }}' '{{ vm['name'] }}' > /etc/hosts
  - [ rm, -f, /etc/salt/minion_id ]
  - [ sed, -i, 's/#master: salt/master: mymasterserver/', /etc/salt/minion ]
  - [ service, salt-minion, restart ]
  - [ bash, -xc, "dd if=/dev/zero of=/swapfile bs=256M count=32" ]
  - [ bash, -xc, "mkswap /swapfile" ]
  - [ bash, -xc, "swapon /swapfile" ]
  - [ sh, -xc, "echo $(date) ': runcmd part'" ]

mounts:
  - [ /swapfile, none, swap, "sw", "0", "0" ]

#phone_home:
#  url: http://api.ops.appannie.com/$INSTANCE_ID/
#  post: [ instance_id, private_ip, public_ip, region ]

final_message: "The system is finally up, after $UPTIME seconds"

[ERROR   ] There was a profile error: must be string or buffer, not dict
Traceback (most recent call last):
  File "/root/venv/salt/salt/cloud/cli.py", line 284, in run
    self.config.get('names')
  File "/root/venv/salt/salt/cloud/__init__.py", line 1449, in run_profile
    ret[name] = self.create(vm_)
  File "/root/venv/salt/salt/cloud/__init__.py", line 1284, in create
    output = self.clouds[func](vm_)
  File "/root/venv/salt/salt/cloud/clouds/ec2.py", line 2499, in create
    data, vm_ = request_instance(vm_, location)
  File "/root/venv/salt/salt/cloud/clouds/ec2.py", line 1706, in request_instance
    params[spot_prefix + 'UserData'] = base64.b64encode(userdata)
  File "/usr/lib/python2.7/base64.py", line 53, in b64encode
    encoded = binascii.b2a_base64(s)[:-1]
TypeError: must be string or buffer, not dict
```
### Versions Report
```
Salt Version:
            Salt: 2016.3.0-544-g30ca644

Dependency Versions:
 Apache Libcloud: 0.15.1
            cffi: Not Installed
        cherrypy: Not Installed
        dateutil: 1.5
           gitdb: Not Installed
       gitpython: Not Installed
           ioflo: Not Installed
          Jinja2: 2.7.2
         libgit2: Not Installed
         libnacl: Not Installed
        M2Crypto: 0.21.1
            Mako: Not Installed
    msgpack-pure: Not Installed
  msgpack-python: 0.4.7
    mysql-python: Not Installed
       pycparser: Not Installed
        pycrypto: 2.6.1
          pygit2: Not Installed
          Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
    python-gnupg: Not Installed
          PyYAML: 3.10
           PyZMQ: 14.4.0
            RAET: Not Installed
           smmap: Not Installed
         timelib: Not Installed
         Tornado: 4.2.1
             ZMQ: 4.0.4

System Versions:
            dist: Ubuntu 14.04 trusty
         machine: x86_64
         release: 3.13.0-86-generic
          system: Linux
         version: Ubuntu 14.04 trusty
```

**Comment by ffjia** [comment]
After replace **userdata** with **userdata_file** in the following code block, it stop complaining `Template does not exist'. 

```
        userdata = compile_template(
            userdata_file, rend, renderer
        )
```

But new error occurs when rendering template, can we use ** vm_** in userdata?

```
[ERROR   ] Rendering exception occurred: Jinja variable 'vm_' is undefined
[ERROR   ] There was a profile error: Jinja variable 'vm_' is undefined
```

**Comment by rallytime** [comment]
@ffjia Does the fix in #34623 help resolve this for you?

**Comment by ffjia** [comment]
@rallytime With #34623, we can pass userdata as string, but still has error like this:
```
[ERROR   ] Rendering exception occurred: Jinja variable 'vm_' is undefined
[ERROR   ] There was a profile error: Jinja variable 'vm_' is undefined
```

My problems is how should I pass the `NAME' in `salt-cloud -p PROFILE NAME' to userdata as jinja template? Which variable should I use?

**Comment by rallytime** [comment]
@ffjia The profile name is name of the salt-cloud profile you want to use as the template to provision a new VM with. A simple example would look something like this, in a salt-cloud profile file:
```
my-ec2-profile:
  provider: my-ec2
  image: ami-d514f291
  size: t1.micro
```
And then the salt cloud command would me `salt-cloud -p my-ec2-profile my-new-vm`.

In case you haven't seen them yet, there are some nice salt cloud docs explaining this, which all start here: https://docs.saltstack.com/en/latest/topics/cloud/

**Comment by techhat** [comment]
@rallytime, I think he's asking for the name of the variable. In this case it would be `name`. @ffjia you have access to everything in the `opts` dictionary, with updates/overrides supplied from the `vm_` dictionary.

**Comment by ffjia** [comment]
Thanks @rallytime and @techhat, I could use `opts['names'][0]` to get the instance `NAME`. But there's error when doing base 64 encoding.

```
[DEBUG   ] Results of YAML rendering:
>> snip <<
[PROFILE ] Time (in seconds) to render ':string:' using 'yaml' renderer: 0.00577616691589
[ERROR   ] There was a profile error: must be convertible to a buffer, not OrderedDict
Traceback (most recent call last):
  File "/root/venv/salt/salt/cloud/cli.py", line 285, in run
    self.config.get('names')
  File "/root/venv/salt/salt/cloud/__init__.py", line 1454, in run_profile
    ret[name] = self.create(vm_)
  File "/root/venv/salt/salt/cloud/__init__.py", line 1284, in create
    output = self.clouds[func](vm_)
  File "/root/venv/salt/salt/cloud/clouds/ec2.py", line 2504, in create
    data, vm_ = request_instance(vm_, location)
  File "/root/venv/salt/salt/cloud/clouds/ec2.py", line 1711, in request_instance
    params[spot_prefix + 'UserData'] = base64.b64encode(userdata)
  File "/usr/lib/python2.7/base64.py", line 53, in b64encode
    encoded = binascii.b2a_base64(s)[:-1]
TypeError: must be convertible to a buffer, not OrderedDict
```

**Comment by hemebond** [comment]
This error is still present in v2016.11.0rc2. The [compile_template line](https://github.com/saltstack/salt/blob/v2016.11.0rc2/salt/cloud/clouds/ec2.py#L1700) returns a dict, not a string.

**Comment by brentrjones** [comment]
Interested in this ticket - is there a way I can help? Would love to template userdata (to add a defined hostname to the instance, so cloud-init can make a friendly name and integrate with dynamic DNS)

**Comment by dougofthemoment** [comment]
I get this error in v2016.11.0 general release

**Comment by oba11** [comment]
Its broken for me a well even though I dont template but has some data which are json e.g 

```
#cloud-config

---
write_files:
  - path: /var/lib/kubernetes/auth_policy.jsonl
    owner: root:root
    permissions: 0600
    content: |
      {"apiVersion": "abac.authorization.kubernetes.io/v1beta1", "kind": "Policy", "spec": {"user":"*", "nonResourcePath": "*", "readonly": true}}
```

**Comment by tedohayer** [comment]
Broken for me after upgrading from 2016.3.3 to 2016.11.1

My userdata is below:

`manage_etc_hosts: false
manage_resolv_conf: true
resolv_conf:
  nameservers: ['10.1.31.5','10.1.32.5']
  searchdomains:
    - or.company.internal
    - company.internal
  domain: or.company.internal
  options:
    rotate: true
    timeout: 1`

**Comment by dougofthemoment** [comment]
still here in 2016.11.2 whether there is templating or not

**Comment by danlsgiga** [comment]
Also facing the same issue on 2016.11.2.

**Comment by ccrivelli** [comment]
For me it broke after upgrading to ```salt-cloud-2016.11.1```.
With this simple maps file:
```
centos7_small_ec2:
  - dev-app3.aws.aleron.internal:
      userdata_file: /etc/salt/cloud.deploy.d/dev-app3.domain.internal.sh
```
I get this error:
```
# salt-cloud -m /etc/salt/cloud.maps.d/ec2.dev.map -y
..
[ERROR   ] There was a query error: expected '<document start>', but found '<scalar>'
  in "<unicode string>", line 14, column 1:
    echo "INFO| Setting up hostname .."
    ^
```
That line 14 is inside my userdata file  ```/etc/salt/cloud.deploy.d/dev-app3.domain.internal.sh``` (a bash script).

**Comment by rsalmond** [comment]
For people googling a variation of this error, the exception I got was slightly different.

```
[ERROR   ] There was a profile error: b2a_base64() argument 1 must be convertible to a buffer, not OrderedDict
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 284, in run
    self.config.get('names')
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1458, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1288, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 2510, in create
    data, vm_ = request_instance(vm_, location)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 1705, in request_instance
    params[spot_prefix + 'UserData'] = base64.b64encode(userdata)
  File "/usr/lib/python2.7/base64.py", line 54, in b64encode
    encoded = binascii.b2a_base64(s)[:-1]
TypeError: b2a_base64() argument 1 must be convertible to a buffer, not OrderedDict
```
