### ISSUE TITLE
x509 CSR fails if the csr does not contain any extensions

### ISSUE THREAD

**Issue by clinta** [saltstack/salt#33238]
When attempting to use the x509 module to sign a csr which does not have any requested extensions, the module fails:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 196, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/x509.py", line 1146, in create_certificate
    csrexts = read_csr(kwargs['csr'])['X509v3 Extensions']
  File "/usr/lib/python2.7/dist-packages/salt/modules/x509.py", line 509, in read_csr
    ret['X509v3 Extensions'] = _get_csr_extensions(csr)
  File "/usr/lib/python2.7/dist-packages/salt/modules/x509.py", line 162, in _get_csr_extensions
    csrexts = csryaml['Certificate Request']['Data']['Requested Extensions']
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by Ch3LL** [comment]
@clinta thanks for the PR! Are you okay with closing this once your PR is merged?

**Comment by clinta** [comment]
Yes

**Comment by rallytime** [comment]
Thanks @clinta!
