### ISSUE TITLE
minion can not be connectted after minion restart a few minutes later

### ISSUE THREAD

**Issue by sumhuang** [saltstack/salt#33257]
### Description of Issue/Question
Minion can not work after it is being restartted a few minutes later.
But when I  restart the minion,everything is right,and master can connect to the minion,after about 20 minutes later,master get the message of [Minion did not return. [No response]] when with the commond of [test.ping],and the debug log in the minion also is unusual.

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

minion log

```
2016-05-14 14:29:10,301 [salt.minion      ][INFO    ][19825] User root Executing command test.ping with jid 20160514142913431515
2016-05-14 14:29:10,302 [salt.minion      ][DEBUG   ][19825] Command details {'tgt_type': 'glob', 'jid': '20160514142913431515', 'tgt': '2530', 'ret': '', 'user': 'root', 'arg': [], 'fun': 'test.ping'}
2016-05-14 14:29:10,311 [salt.minion      ][INFO    ][24913] Starting a new job with PID 24913
2016-05-14 14:29:10,361 [salt.utils.lazy  ][DEBUG   ][24913] LazyLoaded test.ping
2016-05-14 14:29:10,361 [salt.minion      ][INFO    ][24913] Returning information for job: 20160514142913431515
2016-05-14 14:29:10,362 [salt.crypt       ][DEBUG   ][24913] Re-using SAuth for ('/etc/salt/pki/minion', '2530', 'tcp://218.76.60.50:4506')
2016-05-14 14:34:47,152 [salt.minion      ][INFO    ][19825] User root Executing command test.ping with jid 20160514143450282673
2016-05-14 14:34:47,153 [salt.minion      ][DEBUG   ][19825] Command details {'tgt_type': 'glob', 'jid': '20160514143450282673', 'tgt': '2530', 'ret': '', 'user': 'root', 'arg': [], 'fun': 'test.ping'}
2016-05-14 14:34:47,161 [salt.minion      ][INFO    ][26621] Starting a new job with PID 26621
2016-05-14 14:34:47,203 [salt.utils.lazy  ][DEBUG   ][26621] LazyLoaded test.ping
2016-05-14 14:34:47,204 [salt.minion      ][INFO    ][26621] Returning information for job: 20160514143450282673
2016-05-14 14:34:47,204 [salt.crypt       ][DEBUG   ][26621] Re-using SAuth for ('/etc/salt/pki/minion', '2530', 'tcp://218.76.60.50:4506')
2016-05-14 14:43:01,874 [salt.minion      ][INFO    ][19825] User root Executing command test.ping with jid 20160514144305005554
2016-05-14 14:43:01,875 [salt.minion      ][DEBUG   ][19825] Command details {'tgt_type': 'glob', 'jid': '20160514144305005554', 'tgt': '2530', 'ret': '', 'user': 'root', 'arg': [], 'fun': 'test.ping'}
2016-05-14 14:43:01,883 [salt.minion      ][INFO    ][29293] Starting a new job with PID 29293
2016-05-14 14:43:01,925 [salt.utils.lazy  ][DEBUG   ][29293] LazyLoaded test.ping
2016-05-14 14:43:01,925 [salt.minion      ][INFO    ][29293] Returning information for job: 20160514144305005554
2016-05-14 14:43:01,926 [salt.crypt       ][DEBUG   ][29293] Re-using SAuth for ('/etc/salt/pki/minion', '2530', 'tcp://218.76.60.50:4506')
2016-05-14 14:48:46,515 [salt.minion      ][INFO    ][19825] User root Executing command test.ping with jid 20160514144849644563
2016-05-14 14:48:46,516 [salt.minion      ][DEBUG   ][19825] Command details {'tgt_type': 'glob', 'jid': '20160514144849644563', 'tgt': '2530', 'ret': '', 'user': 'root', 'arg': [], 'fun': 'test.ping'}
2016-05-14 14:48:46,523 [salt.minion      ][INFO    ][31272] Starting a new job with PID 31272
2016-05-14 14:48:46,569 [salt.utils.lazy  ][DEBUG   ][31272] LazyLoaded test.ping
2016-05-14 14:48:46,570 [salt.minion      ][INFO    ][31272] Returning information for job: 20160514144849644563
2016-05-14 14:48:46,570 [salt.crypt       ][DEBUG   ][31272] Re-using SAuth for ('/etc/salt/pki/minion', '2530', 'tcp://218.76.60.50:4506')
2016-05-14 14:54:15,757 [salt.minion      ][INFO    ][19825] User root Executing command test.ping with jid 20160514145418887653
2016-05-14 14:54:15,758 [salt.minion      ][DEBUG   ][19825] Command details {'tgt_type': 'glob', 'jid': '20160514145418887653', 'tgt': '2530', 'ret': '', 'user': 'root', 'arg': [], 'fun': 'test.ping'}
2016-05-14 14:54:15,766 [salt.minion      ][INFO    ][524] Starting a new job with PID 524
2016-05-14 14:54:15,808 [salt.utils.lazy  ][DEBUG   ][524] LazyLoaded test.ping
2016-05-14 14:54:15,809 [salt.minion      ][INFO    ][524] Returning information for job: 20160514145418887653
2016-05-14 14:54:15,809 [salt.crypt       ][DEBUG   ][524] Re-using SAuth for ('/etc/salt/pki/minion', '2530', 'tcp://218.76.60.50:4506')
2016-05-14 15:13:18,911 [salt.utils.schedule][INFO    ][19825] Running scheduled job: __mine_interval
2016-05-14 15:13:18,911 [salt.utils.schedule][DEBUG   ][19825] schedule: This job was scheduled with jid_include, adding to cache (jid_include defaults to True)
2016-05-14 15:13:18,912 [salt.utils.schedule][DEBUG   ][19825] schedule: This job was scheduled with a max number of 2
2016-05-14 15:13:18,921 [salt.utils.schedule][DEBUG   ][7106] schedule.handle_func: adding this job to the jobcache with data {'fun': 'mine.update', 'jid': '20160514151318915329', 'pid': 7106, 'id': '2530', 'schedule': '__mine_interval'}
2016-05-14 15:13:18,922 [salt.crypt       ][DEBUG   ][7106] Re-using SAuth for ('/etc/salt/pki/minion', '2530', 'tcp://218.76.60.50:4506')
2016-05-14 15:13:18,923 [salt.crypt       ][DEBUG   ][7106] Loaded minion key: /etc/salt/pki/minion/minion.pem
2016-05-14 15:13:18,933 [salt.utils.event ][DEBUG   ][7106] MinionEvent PUB socket URI: ipc:///var/run/salt/minion/minion_event_55a988dfb0_pub.ipc
2016-05-14 15:13:18,933 [salt.utils.event ][DEBUG   ][7106] MinionEvent PULL socket URI: ipc:///var/run/salt/minion/minion_event_55a988dfb0_pull.ipc
2016-05-14 15:13:18,934 [salt.utils.event ][DEBUG   ][7106] Sending event - data = {'_stamp': '2016-05-14T07:13:18.934360'}
2016-05-14 15:13:18,935 [salt.minion      ][DEBUG   ][19825] Handling event 'salt/event/new_client\n\n\x81\xa6_stamp\xba2016-05-14T07:13:18.934360'
2016-05-14 15:13:18,936 [salt.utils.event ][DEBUG   ][7106] Sending event - data = {'_stamp': '2016-05-14T07:13:18.935721', 'clear': False, 'cmd': '_mine', 'tok': ';\xa3\xa45\xa7j\x9fGP\xc1\xa8\xecd\xfa-\xbb`\x07{\xce\xa6\xb1\xc0%\xa2\x83!\xfeRc\xe0\x12a.\x87\x07\xce\t\x8dgQx\xc2#\x98\x19ze\x11\xd1\xa9#z?T\xab8`\x87\xd4\x08.\xc2\xb3c\x00\x17}\x8e8"h\x89\xe3O\xbd\xdcok\xe9\x93(f\x97\xe0\xc5\xea\xfe:C~\xfe\xe6\xc1\x9a\x03\x96\x85\xd2\xb2\x94\xb7aqn\x8f\x1d\x91\xd3U\xea1\xde3HC\xf608\xb0<i\xf2W\xb3\xa9\x9eF\xf1)\xa6\xaa\x12\x02\xfe26\x1ap\xbd\xb52\x08:\x17\x1e\xeb\xbaj\x93\x86\xa4\xdf\xe6\t\xe1\xca\xbcJ\x89&\x11E\xe1\x9b\x99!\xfd\xaa\x19\xcd\xac)\xf5/z\xc3\x08\xce\xb7\xccOb\x1c\xc6<\x02\x00\xd7\xb7Nr`\xd6K]\x8d\x8d\x89Z-\xf3\xc7i\xab8 \xd8E2\x94(\x8b\xe9+r\xc7\xf3*\xbf\xb7\xf484\x12\xe7\xbd\xc1\x8d\x0c\xc5\x03\x1f3\xfc%\xda\x88\xd5\xebN\xf5n}6\x1f\x10C\xb1~v\xf7\xbfs\xb9\xb1', 'data': {}, 'id': '2530'}
2016-05-14 15:13:18,936 [salt.minion      ][DEBUG   ][19825] Handling event '_minion_mine\n\n\x86\xa6_stamp\xba2016-05-14T07:13:18.935721\xa5clear\xc2\xa3cmd\xa5_mine\xa3tok\xda\x01\x00;\xa3\xa45\xa7j\x9fGP\xc1\xa8\xecd\xfa-\xbb`\x07{\xce\xa6\xb1\xc0%\xa2\x83!\xfeRc\xe0\x12a.\x87\x07\xce\t\x8dgQx\xc2#\x98\x19ze\x11\xd1\xa9#z?T\xab8`\x87\xd4\x08.\xc2\xb3c\x00\x17}\x8e8"h\x89\xe3O\xbd\xdcok\xe9\x93(f\x97\xe0\xc5\xea\xfe:C~\xfe\xe6\xc1\x9a\x03\x96\x85\xd2\xb2\x94\xb7aqn\x8f\x1d\x91\xd3U\xea1\xde3HC\xf608\xb0<i\xf2W\xb3\xa9\x9eF\xf1)\xa6\xaa\x12\x02\xfe26\x1ap\xbd\xb52\x08:\x17\x1e\xeb\xbaj\x93\x86\xa4\xdf\xe6\t\xe1\xca\xbcJ\x89&\x11E\xe1\x9b\x99!\xfd\xaa\x19\xcd\xac)\xf5/z\xc3\x08\xce\xb7\xccOb\x1c\xc6<\x02\x00\xd7\xb7Nr`\xd6K]\x8d\x8d\x89Z-\xf3\xc7i\xab8 \xd8E2\x94(\x8b\xe9+r\xc7\xf3*\xbf\xb7\xf484\x12\xe7\xbd\xc1\x8d\x0c\xc5\x03\x1f3\xfc%\xda\x88\xd5\xebN\xf5n}6\x1f\x10C\xb1~v\xf7\xbfs\xb9\xb1\xa4data\x80\xa2id\xa42530'
2016-05-14 15:13:18,937 [salt.crypt       ][DEBUG   ][19825] Re-using SAuth for ('/etc/salt/pki/minion', '2530', 'tcp://218.76.60.50:4506')
2016-05-14 15:14:18,959 [salt.payload     ][INFO    ][19825] SaltReqTimeoutError: after 60 seconds. (Try 1 of 3)
2016-05-14 15:15:19,018 [salt.payload     ][INFO    ][19825] SaltReqTimeoutError: after 60 seconds. (Try 2 of 3)
2016-05-14 15:16:19,078 [salt.payload     ][INFO    ][19825] SaltReqTimeoutError: after 60 seconds. (Try 3 of 3)
2016-05-14 15:16:19,079 [salt.minion      ][DEBUG   ][19825] Exception while handling events
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1932, in _do_event_poll
    self.handle_event(package)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1682, in handle_event
    self._mine_send(package)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1661, in _mine_send
    ret = channel.send(load)
  File "/usr/lib/python2.7/site-packages/salt/transport/__init__.py", line 314, in send
    return self._crypted_transfer(load, tries, timeout)
  File "/usr/lib/python2.7/site-packages/salt/transport/__init__.py", line 302, in _crypted_transfer
    return _do_transfer()
  File "/usr/lib/python2.7/site-packages/salt/transport/__init__.py", line 293, in _do_transfer
    timeout)
  File "/usr/lib/python2.7/site-packages/salt/payload.py", line 273, in send
    'SaltReqTimeoutError: after {0} seconds, ran {1} tries'.format(timeout * tried, tried)
SaltReqTimeoutError: SaltReqTimeoutError: after 180 seconds, ran 3 tries
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
           Salt: 2015.5.0
         Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
```

**Comment by Ch3LL** [comment]
@sumhuang I am not able to replicate this. Here is my test case:

1. Restart salt minion:

```
[root@ip-10-203-135-98 ~]# date;service salt-minion restart
Tue May 17 01:30:45 UTC 2016
Stopping salt-minion daemon:                               [  OK  ]
Starting salt-minion daemon:                               [  OK  ]
```

2. Verify communication:

```
[root@ip-10-203-135-98 ~]# date; salt '*' test.ping
Tue May 17 01:30:56 UTC 2016
ip-10-203-135-98.ec2.internal:
    True
```

3. Twenty minutes later I can still communicate with the master:

```
[root@ip-10-203-135-98 ~]# date; salt '*' test.ping
Tue May 17 01:51:52 UTC 2016
ip-10-203-135-98.ec2.internal:
    True
```

salt version: 

```
[root@ip-10-203-135-98 ~]# salt --version
salt 2015.5.0 (Lithium)
```

Is there something wrong with the test case above?

Also can you post a sanitized version of your minion config please.

**Comment by sumhuang** [comment]
test case is ok.
all config is setting as defualt in the minion config ,except the config below.
master: test.com
id: '2530'
log_level: debug 
log_level_logfile: debug

**Comment by Ch3LL** [comment]
@sumhuang hmm I don't see anything unusual in your configuration file. Usually when seeing this error: `SaltReqTimeoutError` its just not able to communicate to the master because of network issues. Do you possibly have some network latency issues or firewalls that could be causing timeout errors?

also is your minion version 2015.5.0 as well?

**Comment by sumhuang** [comment]
thanks for you replay.
I found the problem which is a problem in our devices not concern to saltstack.

**Comment by Ch3LL** [comment]
@sumhuang i'm glad you got it working! I'll go ahead and close this but let us know if you need to open it up again if you see the behavior again.
