### ISSUE TITLE
cache.clear_mine is giving me a syntax error related to libnacl

### ISSUE THREAD

**Issue by chizou** [saltstack/salt#33291]
I'm currently running the latest Xenial AMI from Canonical and salt is being installed from the Xenial repo.

```
root@ip-10-255-0-244:/srv/pillar/base# salt --version
salt 2015.8.8 (Beryllium)
root@ip-10-255-0-244:/srv/pillar/base# salt-run cache.clear_mine
[WARNING ] Key 'file_ignore_glob' with value None has an invalid type of NoneType, a list is required for this value
[ERROR   ] Failed to import runners nacl, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1136, in _load_module
    ), fn_, fpath, desc)
  File "/usr/lib/python2.7/dist-packages/salt/runners/nacl.py", line 37, in <module>
    import libnacl.secret
  File "/usr/local/lib/python2.7/dist-packages/libnacl/__init__.py", line 76, in <module>
    nacl = _get_nacl()
  File "/usr/local/lib/python2.7/dist-packages/libnacl/__init__.py", line 74, in _get_nacl
    raise OSError(msg)
OSError: Could not locate nacl lib, searched for libsodium.so, libsodium.so.17, libsodium.so.13, libsodium.so.10, libsodium.so.5, libsodium.so.4, 
False
root@ip-10-255-0-244:/srv/pillar/base# locate libsodium
/usr/lib/x86_64-linux-gnu/libsodium.so.18
/usr/lib/x86_64-linux-gnu/libsodium.so.18.0.1
/usr/share/doc/libsodium18
/usr/share/doc/libsodium18/AUTHORS
/usr/share/doc/libsodium18/README.markdown
/usr/share/doc/libsodium18/THANKS
/usr/share/doc/libsodium18/changelog.Debian.gz
/usr/share/doc/libsodium18/copyright
/var/cache/apt/archives/libsodium18_1.0.8-5_amd64.deb
/var/lib/dpkg/info/libsodium18:amd64.list
/var/lib/dpkg/info/libsodium18:amd64.md5sums
/var/lib/dpkg/info/libsodium18:amd64.shlibs
/var/lib/dpkg/info/libsodium18:amd64.symbols
/var/lib/dpkg/info/libsodium18:amd64.triggers
root@ip-10-255-0-244:/srv/pillar/base# 

```

**Comment by cachedout** [comment]
This sounds like a bug that should be filed with the libnacl packagers. All Salt is doing is attempting an import of the library and it's throwing an OSError. We could catch it it in addition to an ImportError but the true source of this bug is upstream from us.
