### ISSUE TITLE
Special characters in YAML Block Scalars not escaped

### ISSUE THREAD

**Issue by jagguli** [saltstack/salt#33330]
### Special characters in YAML Block Scalars not escaped

Fails when "-" in message
 like

```
            "date": "2016-05-18T04:08:27+00:00",
            "message": "Configure swappiness and overcommit\n\n- should enable processess to utilize maximum memory\n",
            "type": "commit"
```
```
May 18 14:21:40 master salt-master[11976]: Traceback (most recent call last):
May 18 14:21:40 master salt-master[11976]: File "/usr/local/lib/python2.7/dist-packages/salt/utils/reactor.py", line 68, in render_reaction
May 18 14:21:40 master salt-master[11976]: data=data)
May 18 14:21:40 master salt-master[11976]: File "/usr/local/lib/python2.7/dist-packages/salt/state.py", line 302, in render_template
May 18 14:21:40 master salt-master[11976]: template, self.rend, self.opts['renderer'], **kwargs)
May 18 14:21:40 master salt-master[11976]: File "/usr/local/lib/python2.7/dist-packages/salt/template.py", line 95, in compile_template
May 18 14:21:40 master salt-master[11976]: ret = render(input_data, saltenv, sls, **render_kwargs)
May 18 14:21:40 master salt-master[11976]: File "/usr/local/lib/python2.7/dist-packages/salt/renderers/yaml.py", line 51, in render
May 18 14:21:40 master salt-master[11976]: data = load(yaml_data, Loader=get_yaml_loader(argline))
May 18 14:21:40 master salt-master[11976]: File "/usr/lib/python2.7/dist-packages/yaml/__init__.py", line 71, in load
May 18 14:21:40 master salt-master[11976]: return loader.get_single_data()
May 18 14:21:40 master salt-master[11976]: File "/usr/lib/python2.7/dist-packages/yaml/constructor.py", line 37, in get_single_data
May 18 14:21:40 master salt-master[11976]: node = self.get_single_node()
May 18 14:21:40 master salt-master[11976]: File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 36, in get_single_node
May 18 14:21:40 master salt-master[11976]: document = self.compose_document()
May 18 14:21:40 master salt-master[11976]: File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 55, in compose_document
May 18 14:21:40 master salt-master[11976]: node = self.compose_node(None, None)
May 18 14:21:40 master salt-master[11976]: File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node
May 18 14:21:40 master salt-master[11976]: node = self.compose_mapping_node(anchor)
May 18 14:21:40 master salt-master[11976]: File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
May 18 14:21:40 master salt-master[11976]: while not self.check_event(MappingEndEvent):
May 18 14:21:40 master salt-master[11976]: File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 98, in check_event
May 18 14:21:40 master salt-master[11976]: self.current_event = self.state()
May 18 14:21:40 master salt-master[11976]: File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 439, in parse_block_mapping_key
May 18 14:21:40 master salt-master[11976]: "expected <block end>, but found %r" % token.id, token.start_mark)
May 18 14:21:40 master salt-master[11976]: ParserError: while parsing a block mapping
May 18 14:21:40 master salt-master[11976]: in "<unicode string>", line 2, column 1:
May 18 14:21:40 master salt-master[11976]: pull_infrastructure_code:
May 18 14:21:40 master salt-master[11976]: ^
May 18 14:21:40 master salt-master[11976]: expected <block end>, but found '-'
May 18 14:21:40 master salt-master[11976]: in "<unicode string>", line 21, column 1:
May 18 14:21:40 master salt-master[11976]: - should enable processess to ut ...
May 18 14:21:40 master salt-master[11976]: ^
```
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
```
notify_slack:
  local.slack.post_message:
    - tgt: master
    - kwarg:
        channel: '#salt'
        from_name: 'Salt'
        message: |
            Infrastructure code pulled.
            "{{data['post']['push']['changes'][0]['new']['target']['author']['user']['display_name']}}"
            "{{data['post']['push']['changes'][0]['new']['target']['message']}}"

```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report

```
/opt/salt:» salt-master --versions-report                                                                                                                                                                                [0] [master*] 02:29:27
/usr/local/lib/python2.7/dist-packages/cffi/model.py:526: UserWarning: 'git_checkout_notify_t' has no values explicitly defined; next version will refuse to guess which integer type it is meant to be (unsigned/signed, int/long)
  % self._get_c_name())
/usr/local/lib/python2.7/dist-packages/cffi/model.py:526: UserWarning: 'git_merge_flag_t' has no values explicitly defined; next version will refuse to guess which integer type it is meant to be (unsigned/signed, int/long)
  % self._get_c_name())
Salt Version:
           Salt: 2016.3.0rc1-254-g31308b8

Dependency Versions:
           cffi: 1.6.0
       cherrypy: 5.4.0
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.24.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.2

System Versions:
           dist: debian 8.4
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.4
```
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by jagguli** [comment]
Doh https://docs.saltstack.com/en/latest/topics/troubleshooting/yaml_idiosyncrasies.html#nested-dictionaries
