### ISSUE TITLE
salt-minion does not start when extension_modules is set in minion config 2016.3.0

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#33489]
### Description of Issue/Question
I have tested this on 2015.8.8.2 and 2015.8.10 salt-cloud. When salt-cloud is on 2015.8 branch when creating v2016.3.0 minion with salt-cloud the minion cannot start due to the following configuration value in the minion config: `extension_modules: ''`

### Setup
1. salt-cloud version 2015.8.10
2. salt-cloud profile:

```
ec2_ubuntu_14:
  image: ami-98aa1cf0
  size: m3.medium
  provider: amazon
  ssh_username: ec2-user
  script_args: '-g https://github.com/jfindlay/salt.git -P git v2016.3.0'
```

### Steps to Reproduce Issue
1. `salt-cloud -p ec2_ubuntu_14 ch3ll-test`
2. ssh into newly created vm
3. attempt to start minion:

```
root@ip-10-65-82-74:~# salt-minion -ldebug
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Configuration file path: /etc/salt/minion
[ERROR   ] Failed to create environment for Minion: 1
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cli/daemons.py", line 284, in prepare
    pki_dir=self.config['pki_dir'],
  File "/usr/lib/python2.7/dist-packages/salt/utils/verify.py", line 273, in verify_env
    os.chown(path, uid, gid)
OSError: [Errno 1] Operation not permitted: '/proc/747'
[INFO    ] The salt minion is shutting down..
[INFO    ] The Salt Minion is shut down
The salt minion is shutdown.[Errno 1] Operation not permitted: '/proc/747'
```

You can also easily verify this by adding `extension_modules: ''` to a minion config on 2016.3.0.

### Versions Report

```
root@ip-10-65-82-74:~# salt --versions-report
Salt Version:
           Salt: 2016.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.0.4
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-36-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by Ch3LL** [comment]
This has been fixed by #33497 . going ahead and closing.
