### ISSUE TITLE
Gitfs fails if configured locale is French

### ISSUE THREAD

**Issue by multani** [saltstack/salt#33504]
### Description of Issue/Question

I have setup a Gitfs repository in my master configuration file, and the update doesn't work.
If I switch the locale used by the `salt-run` command from French to C then it works.
### Setup

Salt master configuration file:

```
      fileserver_backend:
        - git

      gitfs_remotes:
        - git://some-git-repository.git:
          - root: states
          - base: dev
```

Current locale set to:

```
$ export | grep LANG
LANG=fr_CH.UTF-8
```
### Steps to Reproduce Issue

```
$ LANG=fr_CH.UTF-8 sudo salt-run -l debug fileserver.update
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/acls.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/acls.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/peer-communications.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/peer-communications.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/salt-master.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/salt-master.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt-master1
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] LazyLoaded fileserver.update
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Including configuration from '/etc/salt/minion.d/minion.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/minion.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt-master1
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/acls.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/acls.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/peer-communications.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/peer-communications.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/salt-master.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/salt-master.conf
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[DEBUG   ] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event - data = {'fun': 'runner.fileserver.update', 'jid': '20160525191049960440', 'user': 'sudo_multani', '_stamp': '2016-05-25T17:10:50.572275'}
[DEBUG   ] Error loading runners.nacl: libnacl import error, perhaps missing python libnacl package
[DEBUG   ] gitpython gitfs_provider enabled
[DEBUG   ] LazyLoaded git.envs
[DEBUG   ] Updating git fileserver cache
[DEBUG   ] Set update lock for gitfs remote 'some-repos.git'
[DEBUG   ] Fetching gitfs remote 'some-repos.git'
[DEBUG   ] Removed update lock for gitfs remote 'some-repos.git'
[ERROR   ] Exception 'len(["593b162bc97a876ff4b66cd12b1e91fa5ce72204\tnot-for-merge\tbranch 'master' of some-repos.git\n", "593b162bc97a876ff4b66cd12b1e91fa5ce72204\tnot-for-merge\tbranch 'prod' of some-repos.git\n", "452c1ae3afa5b5f132338607bf16ae039a223b8e\tnot-for-merge\tbranch 'dev' of some-repos.git\n"]) != len(['Depuis some-repos.git', ' = [\xc3\xa0 jour]          master     -> origin/master', ' = [\xc3\xa0 jour]          prod       -> origin/prod', ' = [\xc3\xa0 jour]          dev        -> origin/dev'])' caught while fetching gitfs remote 'some-repos.git'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 2143, in fetch_remotes
    if repo.fetch():
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 385, in fetch
    return self._fetch()
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 782, in _fetch
    fetch_results = origin.fetch()
  File "/usr/lib/python2.7/dist-packages/git/remote.py", line 593, in fetch
    return self._get_fetch_info_from_stderr(proc, progress or RemoteProgress())
  File "/usr/lib/python2.7/dist-packages/git/remote.py", line 539, in _get_fetch_info_from_stderr
    assert len(fetch_info_lines) == len(fetch_head_info), "len(%s) != len(%s)" % (fetch_head_info, fetch_info_lines)
AssertionError: len(["593b162bc97a876ff4b66cd12b1e91fa5ce72204\tnot-for-merge\tbranch 'master' of some-repos.git\n", "593b162bc97a876ff4b66cd12b1e91fa5ce72204\tnot-for-merge\tbranch 'prod' of some-repos.git\n", "452c1ae3afa5b5f132338607bf16ae039a223b8e\tnot-for-merge\tbranch 'dev' of some-repos.git\n"]) != len(['Depuis some-repos.git', ' = [\xc3\xa0 jour]          master     -> origin/master', ' = [\xc3\xa0 jour]          prod       -> origin/prod', ' = [\xc3\xa0 jour]          dev        -> origin/dev'])
[DEBUG   ] LazyLoaded nested.output
True
[DEBUG   ] Sending event - data = {'jid': '20160525191049960440', 'return': True, 'success': True, '_stamp': '2016-05-25T17:10:54.146534', 'user': 'sudo_multani', 'fun': 'runner.fileserver.update'}
[DEBUG   ] LazyLoaded local_cache.prep_jid
[INFO    ] Runner completed: 20160525191049960440
[DEBUG   ] Runner return: True
```

Changing the locale runs fine:

```
$ LANG=C sudo salt-run -l debug fileserver.update
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/acls.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/acls.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/peer-communications.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/peer-communications.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/salt-master.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/salt-master.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt-master1
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] LazyLoaded fileserver.update
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Including configuration from '/etc/salt/minion.d/minion.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/minion.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt-master1
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/acls.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/acls.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/peer-communications.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/peer-communications.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/salt-master.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/salt-master.conf
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[DEBUG   ] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event - data = {'fun': 'runner.fileserver.update', 'jid': '20160525191257350080', 'user': 'sudo_multani', '_stamp': '2016-05-25T17:12:57.943756'}
[DEBUG   ] Error loading runners.nacl: libnacl import error, perhaps missing python libnacl package
[DEBUG   ] gitpython gitfs_provider enabled
[DEBUG   ] LazyLoaded git.envs
[DEBUG   ] Updating git fileserver cache
[DEBUG   ] Set update lock for gitfs remote 'git@some-repos.git'
[DEBUG   ] Fetching gitfs remote 'git@some-repos.git'
[DEBUG   ] Removed update lock for gitfs remote 'git@some-repos.git'
[DEBUG   ] LazyLoaded nested.output
True
[DEBUG   ] Sending event - data = {'jid': '20160525191257350080', 'return': True, 'success': True, '_stamp': '2016-05-25T17:13:04.393180', 'user': 'sudo_multani', 'fun': 'runner.fileserver.update'}
[DEBUG   ] LazyLoaded local_cache.prep_jid
[INFO    ] Runner completed: 20160525191257350080
[DEBUG   ] Runner return: True
```
### Versions Report

```
$ salt --versions-report
Salt Version:
           Salt: 2015.8.10

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: debian 8.4 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.4
```

**Comment by Ch3LL** [comment]
@multani I am not able to replicate this:

```
root@debian:~# LANG=fr_CH.UTF-8 sudo salt-run -l debug fileserver.update
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: debian
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] LazyLoaded fileserver.update
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: debian
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[DEBUG   ] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event - data = {'fun': 'runner.fileserver.update', 'jid': '20160526174432074418', 'user': 'sudo_root', '_stamp': '2016-05-26T17:44:32.437426'}
[DEBUG   ] Error loading runners.nacl: libnacl import error, perhaps missing python libnacl package
[DEBUG   ] gitpython gitfs_provider enabled
[DEBUG   ] LazyLoaded git.envs
[DEBUG   ] Updating git fileserver cache
[DEBUG   ] Set update lock for gitfs remote 'https://github.com/Ch3LL/states'
[DEBUG   ] Fetching gitfs remote 'https://github.com/Ch3LL/states'
[DEBUG   ] Removed update lock for gitfs remote 'https://github.com/Ch3LL/states'
[DEBUG   ] LazyLoaded nested.output
True
[DEBUG   ] Sending event - data = {'jid': '20160526174432074418', 'return': True, 'success': True, '_stamp': '2016-05-26T17:44:33.377126', 'user': 'sudo_root', 'fun': 'runner.fileserver.update'}
[DEBUG   ] LazyLoaded local_cache.prep_jid
[INFO    ] Runner completed: 20160526174432074418
[DEBUG   ] Runner return: True
```

Here's my configuration:

```
root@debian:~# grep -E -v '^$|#' /etc/salt/master
fileserver_backend:
    - git
gitfs_remotes:
  - https://github.com/Ch3LL/states
```

```
root@debian:~# salt --versions-report
Salt Version:
           Salt: 2015.8.10
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: debian 8.4 
        machine: x86_64
        release: 4.5.3-x86_64-linode67
         system: debian 8.4 
```

Am I missing something? Anything ohter information to possibly help me to replicate this?

**Comment by multani** [comment]
@Ch3LL Hum, I would say that your locales are not correctly configured, you are probably missing this one and it falls back to C.

I made a Gist using Docker https://gist.github.com/multani/d75235442d605e3e5c0001f0fad89544 which reproduces the problem, let me know if that works for you!

This ends up like this here:

```
Step 10 : RUN apt-get install locales
 ---> Running in 13fd0db6a267
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  locales
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 3945 kB of archives.
After this operation, 16.7 MB of additional disk space will be used.
Get:1 http://httpredir.debian.org/debian/ jessie/main locales all 2.19-18+deb8u4 [3945 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 3945 kB in 1s (3196 kB/s)
Selecting previously unselected package locales.
(Reading database ... 15719 files and directories currently installed.)
Preparing to unpack .../locales_2.19-18+deb8u4_all.deb ...
Unpacking locales (2.19-18+deb8u4) ...
Setting up locales (2.19-18+deb8u4) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
Generating locales (this might take a while)...
  fr_CH.UTF-8... done
Generation complete.
 ---> e0cb4b12611a
Removing intermediate container 13fd0db6a267
Step 11 : RUN LANG=fr_CH.UTF-8 salt-run -l debug fileserver.update
 ---> Running in 1206cff7ce22
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] LazyLoaded fileserver.update
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Guessing ID. The id can be explicitly set in /etc/salt/minion
[INFO    ] Found minion id from generate_minion_id(): b0cf605c7757
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[DEBUG   ] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event - data = {'fun': 'runner.fileserver.update', 'jid': '20160531144527191061', 'user': 'root', '_stamp': '2016-05-31T14:45:29.298822'}
[DEBUG   ] Error loading runners.nacl: libnacl import error, perhaps missing python libnacl package
[DEBUG   ] gitpython gitfs_provider enabled
[DEBUG   ] LazyLoaded git.envs
[DEBUG   ] Updating git fileserver cache
[INFO    ] Wrote new gitfs remote map to /var/cache/salt/master/gitfs/remote_map.txt
[DEBUG   ] Set update lock for gitfs remote 'https://github.com/Ch3LL/states'
[DEBUG   ] Fetching gitfs remote 'https://github.com/Ch3LL/states'
[DEBUG   ] Removed update lock for gitfs remote 'https://github.com/Ch3LL/states'
[ERROR   ] Exception 'len(["64a8a836dce31de7b05bb4f9427d71088ed89d0c\tnot-for-merge\tbranch 'master' of https://github.com/Ch3LL/states\n", "a71f5aed758493501cfe0808eee9ddff48f7d5cd\tnot-for-merge\tbranch 'test' of https://github.com/Ch3LL/states\n"]) != len(['Depuis https://github.com/Ch3LL/states', ' = [\xc3\xa0 jour]          master     -> origin/master', ' = [\xc3\xa0 jour]          test       -> origin/test'])' caught while fetching gitfs remote 'https://github.com/Ch3LL/states'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 2143, in fetch_remotes
    if repo.fetch():
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 385, in fetch
    return self._fetch()
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 782, in _fetch
    fetch_results = origin.fetch()
  File "/usr/lib/python2.7/dist-packages/git/remote.py", line 593, in fetch
    return self._get_fetch_info_from_stderr(proc, progress or RemoteProgress())
  File "/usr/lib/python2.7/dist-packages/git/remote.py", line 539, in _get_fetch_info_from_stderr
    assert len(fetch_info_lines) == len(fetch_head_info), "len(%s) != len(%s)" % (fetch_head_info, fetch_info_lines)
AssertionError: len(["64a8a836dce31de7b05bb4f9427d71088ed89d0c\tnot-for-merge\tbranch 'master' of https://github.com/Ch3LL/states\n", "a71f5aed758493501cfe0808eee9ddff48f7d5cd\tnot-for-merge\tbranch 'test' of https://github.com/Ch3LL/states\n"]) != len(['Depuis https://github.com/Ch3LL/states', ' = [\xc3\xa0 jour]          master     -> origin/master', ' = [\xc3\xa0 jour]          test       -> origin/test'])
[DEBUG   ] LazyLoaded nested.output
[DEBUG   ] Sending event - data = {'jid': '20160531144527191061', 'return': True, 'success': True, '_stamp': '2016-05-31T14:45:31.742728', 'user': 'root', 'fun': 'runner.fileserver.update'}
[DEBUG   ] LazyLoaded local_cache.prep_jid
[INFO    ] Runner completed: 20160531144527191061
[DEBUG   ] Runner return: True
True
 ---> b2a1f97b0bc1
Removing intermediate container 1206cff7ce22
Successfully built b2a1f97b0bc1
```

**Comment by emeygret** [comment]
Hi,
same issue for me locales seems to be ok, default is fr_FR.UTF-8 : 
`dpkg-reconfigure` locales
Generating locales (this might take a while)...
  en_US.ISO-8859-1... done
  en_US.ISO-8859-15... done
  en_US.UTF-8... done
  fr_FR.ISO-8859-1... done
  fr_FR.UTF-8... done
  fr_FR.ISO-8859-15@euro... done
Generation `complete.`

salt-run -l debug fileserver.update -> same error than multani
LANG=C salt-run -l debug fileserver.update -> OK

Debian 8.9 / salt-master 2017.7.1 (Nitrogen) / into lxc container (lxc 2.0.7 from proxmox)

**Comment by multani** [comment]
We indeed stopped using gitfs.

**Comment by sathieu** [comment]
#50783 may  have fixed this
