### ISSUE TITLE
cmd.run returns misleading error message, and at the wrong level, when presented with additional args

### ISSUE THREAD

**Issue by blaisep** [saltstack/salt#33506]
#### _Think of this as an opportunity for improvement..._

When passing multiple `args:` in cmd.run, if the additional arguments are broken, the error could be spotted and reported right there, instead of way down in debug land.

For example, the additional `args:`  must be arguments for `cmd.run` itself and not additional commands intended for the same state. Currently, the error message says something like `arg 2 is not a valid cmd.run argument` instead of saying there is something wrong with the second argument. The text of the error message is below, so you can see what I mean.
### Setup

(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

For example, this schedule pillar:

```
schedule:
{%- for repo in repos %}
  build-{{ repo }}-nightly:
    function: cmd.run
    run_on_start: False
    args:
      - curl --data "" http://{{ salt["grains.get"]("id") }}/build/{{ repo }}
    args: echo "triggered a build for {{ repo }}" >> /opt/app/docserver/logs/nightly.log
    cron:  "1 10 * * *"
```
### Steps to Reproduce Issue

(Include debug logs if possible and relevant.)

Produces this misleading error:

```
CommandExecutionError: Specified cwd 'wall "triggered a build for devtools"' either not absolute or does not exist
2016-05-25 17:43:59,281 [salt.utils.schedule][DEBUG   ][11215] schedule.handle_func: adding this job to the jobcache with data {'fun': 'cmd.run', 'jid': '20160525174359259814', 'pid': 11215, 'id': 'di-techdocs1a.auw2d.shpsec.com', 'schedule': 'build-api-guide-for-sift-utils-nightly'}
2016-05-25 17:43:59,282 [salt.loaded.int.module.cmdmod][INFO    ][11215] Executing command 'curl --data "" http://di-techdocs1a.auw2d.shpsec.com/build/api-guide-for-sift-utils' in directory 'wall "triggered a build for api-guide-for-sift-utils"'
2016-05-25 17:43:59,282 [salt.utils.schedule][ERROR   ][11215] Unhandled exception running cmd.run
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/schedule.py", line 540, in handle_func
    ret['return'] = self.functions[func](*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 707, in run
    use_vt=use_vt)
  File "/usr/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 417, in _run
    .format(cwd)
```
### Versions Report

(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
           Salt: 2015.5.10
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.7.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
        Tornado: 4.3
        timelib: Not Installed
       dateutil: 1.5

**Comment by Ch3LL** [comment]
@blaisep I think we could definitely include some better logging instead of a stack trace. I'll approve this as a feature request :)
