### ISSUE TITLE
[2015.8.10] salt.states.file.blockreplace source won't accept lists

### ISSUE THREAD

**Issue by Herugrim** [saltstack/salt#33534]
### Description of Issue/Question

Trying to use a fallback list for `file.blockreplace` `source:` as is described in the documentation https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.blockreplace results in a error `TypeError: unhashable type: 'list'`
### Setup

Example file.blockreplace sls:

```
proxy:
  file:
    - blockreplace
    - name: /etc/environment
    - marker_start: "# BLOCK TOP : salt managed zone : proxy : please do not edit"
    - marker_end: "# BLOCK BOTTOM : end of salt managed zone --"
    - source:
      - salt://files/etc/environment.{{ grains['id'] }}
      - salt://files/etc/environment
    - show_changes: True
    - append_if_not_found: True
```

Results in the following error:

```
          ID: proxy
    Function: file.blockreplace
        Name: /etc/environment
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1624, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1492, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 3075, in blockreplace
                  context=context)
                File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 716, in _get_template_texts
                  **kwargs
                File "/usr/lib/python2.7/dist-packages/salt/modules/cp.py", line 266, in get_template
                  **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 724, in get_template
                  url_data = urlparse(url)
                File "/usr/lib/python2.7/urlparse.py", line 143, in urlparse
                  tuple = urlsplit(url, scheme, allow_fragments)
                File "/usr/lib/python2.7/urlparse.py", line 176, in urlsplit
                  cached = _parse_cache.get(key, None)
              TypeError: unhashable type: 'list'
```
### Versions Report

salt --versions-report master:

```

Salt Version:
           Salt: 2015.8.10

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: 1.0.0
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

```

salt --versions-report minion:

```
Salt Version:
           Salt: 2015.8.10

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

```

**Comment by Ch3LL** [comment]
@Herugrim i am able to replicate this. Looks like its broken on 2015.8 and working in 2015.5

Here is the git bisect:

```
6811e817462ec3956c09d2908ed5bf3a01c37a68 is the first bad commit
commit 6811e817462ec3956c09d2908ed5bf3a01c37a68
Author: Robert McLeay <rob.mcleay@flightcentre.com.au>
Date:   Thu May 14 12:40:14 2015 +1000

    Added templates and sources to file.blockreplace

:040000 040000 5c2bb56b7d0e80cbdc9ab5146a74ae006b0d5bb1 8377e0386f55b1a87a2b4bfcbb76d74539e38779 M      salt
```
