### ISSUE TITLE
IOLoop issue 

### ISSUE THREAD

**Issue by fwihardjo** [saltstack/salt#33551]
We are attempting to upgrade to salt 2016.3 and are running into "IOLoop is already running" error.  We are using a Caller client to run some logic and it seems that in 2016.3 when we cache the caller client, it has already started the IOLoop.   

This is the stack trace we are seeing:

``` py
2016-05-26 14:53:00,798 [salt.loaded.ext.runners.oracle_lcm_orchestrator          ][ERROR   ][9314][139830353864448] Exception in build_job_filetransfer_visitor: IOLoop is already running, trace
: Traceback (most recent call last):
  File "/srv/salt/_runners/oracle_lcm_orchestrator.py", line 4828, in build_job_filetransfer_visitor
    new_value = _build_job_filetransfer_visitor(job_builder, old_value, k)
  File "/srv/salt/_runners/oracle_lcm_orchestrator.py", line 4862, in _build_job_filetransfer_visitor
    cached = file_transfer.pull_file_from_master()
  File "/srv/salt/_utils/oracle_lcm_utils_file_util.py", line 388, in pull_file_from_master
    cached = self._pull_file_from_master(filepath)
  File "/srv/salt/_utils/oracle_lcm_utils_file_util.py", line 403, in _pull_file_from_master
    result = get_client_cache().get_caller_client_remote().function("cp.cache_file", salt_src_url,
  File "/srv/salt/_utils/oracle_lcm_utils_client_cache.py", line 57, in get_caller_client_remote
    self._caller_client_remote = salt.client.Caller(c_path, mopts)
  File "/usr/lib/python2.6/site-packages/salt/client/__init__.py", line 1713, in __init__
    self.sminion = salt.minion.SMinion(self.opts)
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 591, in __init__
    lambda: self.eval_master(self.opts, failed=True)
  File "/usr/lib64/python2.6/site-packages/tornado/ioloop.py", line 439, in run_sync
    self.start()
  File "/usr/lib64/python2.6/site-packages/zmq/eventloop/ioloop.py", line 151, in start
    super(ZMQIOLoop, self).start()
  File "/usr/lib64/python2.6/site-packages/tornado/ioloop.py", line 730, in start
    raise RuntimeError("IOLoop is already running")
RuntimeError: IOLoop is already running
```

Is this a bug or should we not cache the client Caller?  Thanks.

**Comment by jfindlay** [comment]
@fwihardjo, thanks for reporting.  How did you upgrade salt?  Is this coming from the master debug log?  Was the previous instance properly stopped before the new one was started?  Is there anything relevant in the master config?

**Comment by cachedout** [comment]
This isn't coming from the daemon at all. It's coming from a cached Client caller. The likely problem here is that we're not allowing for an already-running IOLoop when we instantiate the SMinion instance.

**Comment by yannis666** [comment]
Mike answers some of your issue. Our implementation keeps a cache of local/runner/client callers.
In terms of salt - we yum install into base linux docker images
