### ISSUE TITLE
Update '2015.8.10+ds-1' to '2016.3.0+ds-1' caused TypeError: __init__() got an unexpected keyword argument 'timeout'

### ISSUE THREAD

**Issue by onorua** [saltstack/salt#33563]
### Description of Issue/Question

I have `salt.latest`, which caused automatic restart of the salt related packages. This caused error code on systemd enabled system. 
### Versions Report

```
Salt Version:
           Salt: 2016.3.0

Dependency Versions:
           cffi: 1.1.1
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.22.0
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.2
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.3.4
      pycparser: 2.13
       pycrypto: 2.6.1
         pygit2: 0.22.0
         Python: 2.7.10 (default, Oct 14 2015, 16:09:02)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.1
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 15.10 wily
        machine: x86_64
        release: 4.2.0-18-generic
         system: Linux
        version: Ubuntu 15.10 wily
```
### Log

```
2016-05-25 23:50:28,986 [salt.state       ][INFO    ][24294] Made the following changes:
'salt-minion' changed from '2015.8.10+ds-1' to '2016.3.0+ds-1'
'salt-common' changed from '2015.8.10+ds-1' to '2016.3.0+ds-1'

2016-05-25 23:50:28,994 [salt.state       ][INFO    ][24294] Loading fresh modules for state activity
2016-05-25 23:50:30,039 [salt.state       ][INFO    ][24294] Completed state [salt-minion] at time 23:50:30.038801
2016-05-25 23:50:30,041 [salt.state       ][INFO    ][24294] Running state [/etc/systemd/system/salt-minion.service.d/dropin.conf] at time 23:50:30.041205
2016-05-25 23:50:30,042 [salt.state       ][INFO    ][24294] Executing state file.managed for /etc/systemd/system/salt-minion.service.d/dropin.conf
2016-05-25 23:50:30,098 [salt.fileclient  ][INFO    ][24294] Fetching file from saltenv 'base', ** done ** u'deploy/salt-minion/files/salt-minion.dropin'
2016-05-25 23:50:30,124 [salt.fileclient  ][INFO    ][24294] Fetching file from saltenv 'base', ** done ** u'deploy/salt-minion/files/salt-minion.dropin'
2016-05-25 23:50:30,127 [salt.state       ][INFO    ][24294] File /etc/systemd/system/salt-minion.service.d/dropin.conf is in the correct state
2016-05-25 23:50:30,127 [salt.state       ][INFO    ][24294] Completed state [/etc/systemd/system/salt-minion.service.d/dropin.conf] at time 23:50:30.127284
2016-05-25 23:50:30,486 [salt.state       ][INFO    ][24294] Running state [/etc/salt/minion.d/masters.conf] at time 23:50:30.486354
2016-05-25 23:50:30,487 [salt.state       ][INFO    ][24294] Executing state file.managed for /etc/salt/minion.d/masters.conf
2016-05-25 23:50:30,510 [salt.fileclient  ][INFO    ][24294] Fetching file from saltenv 'base', ** done ** u'deploy/salt-minion/files/masters.conf'
2016-05-25 23:50:31,082 [salt.fileclient  ][INFO    ][24294] Fetching file from saltenv 'base', ** done ** u'deploy/salt-minion/files/masters.conf'
2016-05-25 23:50:31,181 [salt.state       ][INFO    ][24294] File /etc/salt/minion.d/masters.conf is in the correct state
2016-05-25 23:50:31,182 [salt.state       ][INFO    ][24294] Completed state [/etc/salt/minion.d/masters.conf] at time 23:50:31.181560
2016-05-25 23:50:31,182 [salt.state       ][INFO    ][24294] Running state [/etc/salt/minion.d/logging.conf] at time 23:50:31.181753
2016-05-25 23:50:31,182 [salt.state       ][INFO    ][24294] Executing state file.managed for /etc/salt/minion.d/logging.conf
2016-05-25 23:50:31,183 [salt.state       ][INFO    ][24294] File /etc/salt/minion.d/logging.conf is in the correct state
2016-05-25 23:50:31,184 [salt.state       ][INFO    ][24294] Completed state [/etc/salt/minion.d/logging.conf] at time 23:50:31.183570
2016-05-25 23:50:31,195 [salt.state       ][INFO    ][24294] Running state [salt-minion] at time 23:50:31.194480
2016-05-25 23:50:31,195 [salt.state       ][INFO    ][24294] Executing state service.running for salt-minion
2016-05-25 23:50:31,196 [salt.loaded.int.module.cmdmod][INFO    ][24294] Executing command ['systemctl', 'status', 'salt-minion.service', '-n', '0'] in directory '/root'
2016-05-25 23:50:31,198 [salt.state       ][ERROR   ][24294] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1624, in call
    ret['comment'] += '{0}\n'.format(err)
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1492, in wrapper
    if hasattr(mod, '__outputter__'):
  File "/usr/lib/python2.7/dist-packages/salt/states/service.py", line 324, in running
    if not _available(name, ret):
  File "/usr/lib/python2.7/dist-packages/salt/states/service.py", line 275, in _available
    avail = __salt__['service.available'](name)
  File "/usr/lib/python2.7/dist-packages/salt/modules/systemd.py", line 479, in available
    out = _systemctl_status(name).lower()
  File "/usr/lib/python2.7/dist-packages/salt/modules/systemd.py", line 271, in _systemctl_status
    ignore_retcode=True
  File "/usr/lib/python2.7/dist-packages/salt/modules/cmdmod.py", line 852, in run
    bg=bg)
  File "/usr/lib/python2.7/dist-packages/salt/modules/cmdmod.py", line 471, in _run
    proc = salt.utils.timed_subprocess.TimedProc(cmd, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/utils/timed_subprocess.py", line 35, in __init__
    self.stderr = kwargs['stderr'] = None
TypeError: __init__() got an unexpected keyword argument 'timeout'
```

**Comment by Ch3LL** [comment]
@onorua can provide the state that is upgrading this package to help me recreate this issue?

Also how did you install salt initially?

**Comment by onorua** [comment]
Here it is salt-minion state:
```
{% if grains.os == 'Debian' %}
salt-repo:
  pkgrepo.managed:
    - humanname: repo.saltstack.com
    - name: "deb http://repo.saltstack.com/apt/debian/latest jessie main"
    - key_url: https://repo.saltstack.com/apt/debian/latest/SALTSTACK-GPG-KEY.pub
    - file: /etc/apt/sources.list.d/saltstack.list
    - refresh: True

non-salt-repo:
  pkgrepo.absent:
    - name: deb http://repo.saltstack.com/apt/debian jessie main
    - file: /etc/apt/sources.list.d/saltstack.list
    - refresh: True
{% elif grains.os == 'Ubuntu' %}
salt-repo:
  pkgrepo.managed:
    - humanname: repo.saltstack.com
    - name: "deb http://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest trusty main"
    - key_url: https://repo.saltstack.com/apt/ubuntu/ubuntu14/latest/SALTSTACK-GPG-KEY.pub
    - file: /etc/apt/sources.list.d/saltstack.list
    - refresh: True
non-salt-repo:
  pkgrepo.absent:
    - name: deb http://repo.saltstack.com/apt/ubuntu/latest/ubuntu14 trusty main
    - file: /etc/apt/sources.list.d/saltstack.list
    - refresh: True
{% endif %}

install-salt-minion-dep:
  pkg.installed:
    - pkgs: 
      - python-croniter

install-salt-minion:
  pkg.latest:
    - name: salt-minion

/etc/systemd/system/salt-minion.service.d/dropin.conf:
  file.managed:
    - source: salt://deploy/salt-minion/files/salt-minion.dropin
    - template: jinja
    - user: root
    - group: root
    - mode: 644
    - makedirs: true

salt-minion:
  service.running:
    - name: salt-minion
    - enable: true
    - require:
      - pkg: install-salt-minion
      - file: /etc/salt/minion.d/masters.conf
      - file: /etc/systemd/system/salt-minion.service.d/dropin.conf
    - watch:
      - file: /etc/salt/minion.d/masters.conf
      - file: /etc/salt/minion.d/logging.conf
      - file: /etc/systemd/system/salt-minion.service.d/dropin.conf
      - pkg: install-salt-minion-dep
  module.wait:
    - name: service.systemctl_reload
    - watch:
      - file: /etc/systemd/system/salt-minion.service.d/dropin.conf

/etc/salt/minion.d/masters.conf:
  file.managed:
    - source: salt://deploy/salt-minion/files/masters.conf
    - template: jinja

/etc/salt/minion.d/logging.conf:
  file.managed:
    - contents: 
      - 'log_level: {{ salt["pillar.get"]("salt-minion:log_level", "info") }}'
      - 'log_level_logfile: {{ salt["pillar.get"]("salt-minion:log_level_logfile", "info") }}'
```
#### salt-minion.dropin 
```
[Service]
Restart=always
CPUQuota={{salt["pillar.get"]("salt-minion:cpu_quota", "50")}}%
MountFlags=slave
LimitNOFILE=1048576
LimitNPROC=1048576
{% if salt['grains.get']("systemd:version")|int >= 228 -%}
TasksMax=1048576
{% endif -%}
RestartSec=2s
StartLimitInterval=0
```

#### masters.conf
```
{% set salt_masters = salt["pillar.get"]("salt-minion:master", "salt") -%}
{% set alive_interval = salt["pillar.get"]("salt-minion:master_alive_interval", 30) -%}
{% set type = salt["pillar.get"]("salt-minion:master_type", "str") -%}
{% set shuffle = salt["pillar.get"]("salt-minion:master_shuffle", False) -%}
{% set random = salt["pillar.get"]("salt-minion:random_master", False) -%}
{% set retry_dns = salt["pillar.get"]("salt-minion:retry_dns", 0) -%}
{% if salt_masters is not string -%}
{% if type == 'failover' %}
master_alive_interval: {{alive_interval}}
master_type: {{type}}
{% endif %}
master_shuffle: {{shuffle}}
random_master: {{random}}
retry_dns: {{retry_dns}}

master:
{%- for item in salt_masters %}
  - {{item -}}
{% endfor -%}

{% else -%}
master: {{salt_masters}}
{% endif %}
```

**Comment by onorua** [comment]
Forgot to mention, I've installed salt the same way at it is described, using `salt-ssh`.

**Comment by rhansen** [comment]
:+1:
