### ISSUE TITLE
pip.installed broken on 2016.3

### ISSUE THREAD

**Issue by ticosax** [saltstack/salt#33570]
### Description of Issue/Question

```
 File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1624, in call
    ret['comment'] += '{0}\n'.format(err)
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1492, in wrapper
    if hasattr(mod, '__outputter__'):
  File "/usr/lib/python2.7/dist-packages/salt/states/pip_state.py", line 645, in installed
    upgrade, user, cwd, bin_env)
  File "/usr/lib/python2.7/dist-packages/salt/states/pip_state.py", line 203, in _check_if_installed
    user=user, cwd=cwd)
  File "/usr/lib/python2.7/dist-packages/salt/modules/pip.py", line 1066, in list_
    packages['pip'] = version(bin_env)
  File "/usr/lib/python2.7/dist-packages/salt/modules/pip.py", line 1116, in version
    '{0} --version'.format(pip_bin), python_shell=False)
  File "/usr/lib/python2.7/dist-packages/salt/modules/cmdmod.py", line 852, in run
    bg=bg)
  File "/usr/lib/python2.7/dist-packages/salt/modules/cmdmod.py", line 467, in _run
    cmd = salt.utils.shlex_split(cmd, posix=posix)
AttributeError: 'module' object has no attribute 'shlex_split'
```
### Setup
```yaml
boto:
  pip.installed:
    - reload_modules: true
```
### Versions Report
```
$ salt-call --versions-report
Salt Version:
           Salt: 2016.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: 0.3.6
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-86-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by cachedout** [comment]
I can't reproduce this at all. Stale *.pyc files by chance?

**Comment by ticosax** [comment]
It is happening on bare metal ec2 provisioned with salt-bootstrap.

**Comment by ticosax** [comment]
If you can't reproduce I will dig in a bit deeper.

**Comment by cachedout** [comment]
@ticosax K. I took a pretty quick pass so I might have missed something. I can circle back here in a bit.

**Comment by Ch3LL** [comment]
Cannot replicate this as well with ubuntu14 ec2 instance bootstrapped. Are you seeing this on multiple instances?

**Comment by ticosax** [comment]
@cachedout @Ch3LL My bad, I forgot the AMI I'm using contained already the package salt-common.
That was indeed the old version of salt that was causing this problem.
Thank you for your help.

**Comment by oliver-dungey** [comment]
I have just encountered this same error with a bunch of new minions running 2016.3.2 - the state IDs it failed were:

```
# Make sure the service is up and running (even though we are going to restart?!)
salt-minion-running:
  service.running:
    - name: salt-minion
    - require:
      - pkg: salt-minion
```

and

```
# Ensure the at service (atd) has been started
atd:
  service.running:
    - enable: True
    - require:
      - pkg: at
```

At the same time I also got this new and funky error that may be related:
```
----------
          ID: restart-salt-minion
    Function: cmd.wait
        Name: echo service salt-minion restart | at now + 1 minute
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.6/site-packages/salt/state.py", line 1626, in call
                  continue
                File "/usr/lib/python2.6/site-packages/salt/loader.py", line 1492, in wrapper
                  Apply the __outputter__ variable to the functions
                File "/usr/lib/python2.6/site-packages/salt/states/cmd.py", line 1222, in mod_watch
                  return run(name, **kwargs)
                File "/usr/lib/python2.6/site-packages/salt/states/cmd.py", line 841, in run
                  name, timeout=timeout, python_shell=True, **cmd_kwargs
                File "/usr/lib/python2.6/site-packages/salt/modules/cmdmod.py", line 1590, in run_all
                  password=kwargs.get('password', None))
                File "/usr/lib/python2.6/site-packages/salt/modules/cmdmod.py", line 471, in _run
                  proc = salt.utils.timed_subprocess.TimedProc(cmd, **kwargs)
                File "/usr/lib/python2.6/site-packages/salt/utils/timed_subprocess.py", line 35, in __init__
                  self.stderr = kwargs['stderr'] = None
              TypeError: __init__() got an unexpected keyword argument 'bg'
     Started: 11:29:48.706249
    Duration: 5.437 ms
     Changes:
```
from state:

```
restart-salt-minion:
  cmd.wait:
    - name: echo service salt-minion restart | at now + 1 minute
    - shellk: /bin/sh
    - requires:
      - pkg: at
```

The exact same state IDs worked fine on a bunch of other minions for the last few months, not really sure whats going on.
