### ISSUE TITLE
win_certutil.add_store: Unsupported url scheme

### ISSUE THREAD

**Issue by morganwillcock** [saltstack/salt#33589]
<pre>install_cert_for_elicenser:
  certutil.add_store:
    - name: salt://workstation_files/steinberg_elicenser/Steinberg_Media_Technologies_GmbH.cer
    - store: TrustedPublisher</pre>

This state will pass if the certificate is already present, but if the certificate is removed I get the following:

<pre>----------
          ID: install_cert_for_elicenser
    Function: certutil.add_store
        Name: salt://workstation_files/steinberg_elicenser/Steinberg_Media_Technologies_GmbH.cer
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "C:\salt\bin\lib\site-packages\salt\state.py", line 1703, in call
                  **cdata['kwargs'])
                File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1649, in wrapper
                  return f(*args, **kwargs)
                File "C:\salt\bin\lib\site-packages\salt\states\win_certutil.py", line 65, in add_store
                  out = __salt__['certutil.add_store'](cert_file, store)
                File "C:\salt\bin\lib\site-packages\salt\modules\win_certutil.py", line 84, in add_store
                  cert_file = __salt__['cp.cache_file'](source, saltenv)
                File "C:\salt\bin\lib\site-packages\salt\modules\cp.py", line 393, in cache_file
                  result = _client().cache_file(path, saltenv)
                File "C:\salt\bin\lib\site-packages\salt\fileclient.py", line 178, in cache_file
                  return self.get_url(path, '', True, saltenv, cachedir=cachedir)
                File "C:\salt\bin\lib\site-packages\salt\fileclient.py", line 706, in get_url
                  **get_kwargs
                File "C:\salt\bin\lib\site-packages\salt\utils\http.py", line 482, in query
                  **req_kwargs
                File "C:\salt\bin\lib\site-packages\tornado\httpclient.py", line 102, in fetch
                  self._async_client.fetch, request, **kwargs))
                File "C:\salt\bin\lib\site-packages\tornado\ioloop.py", line 453, in run_sync
                  return future_cell[0].result()
                File "C:\salt\bin\lib\site-packages\tornado\concurrent.py", line 232, in result
                  raise_exc_info(self._exc_info)
                File "<string>", line 3, in raise_exc_info
              ValueError: Unsupported url scheme: c:\salt\var\cache\salt\minion\files\base\workstation_files\steinberg_elicenser\Steinberg_Media_Technologies_GmbH.cer
     Started: 17:11:00.521000
    Duration: 133.0 ms
     Changes:   
----------</pre>

Tested on 2016.3.0

**Comment by Ch3LL** [comment]
@morganwillcock I was able to replicate this behavior on win2012 on 2016.3.0. Looks like we need to get this fixed up. Thanks!

**Comment by rterbush** [comment]
Confirming that I am seeing this issue as well when used as a state.
Used the module from command-line works.

**Comment by pavankumar2203** [comment]
I am seeing this issue too.

**Comment by hrumph** [comment]
PR #36241 should fix this. I didn't know that this issue existed so the commit doesn't reference this.

**Comment by Ch3LL** [comment]
Can anyone give that fix a try and then the issue can be closed if working. Thanks @hrumph

**Comment by rallytime** [comment]
This should be fixed with #26241. Since we haven't heard anything here, I'm going to close this. If this pops up again, let us know!
