### ISSUE TITLE
RuntimeError maximum recursion depth exceeded in config.option state_aggregate 

### ISSUE THREAD

**Issue by daveneeley** [saltstack/salt#33598]
### Description of Issue
state.highstate returns "RuntimeError: maximum recursion depth exceeded" when master is 2016.3 but minion is 2015.8.10. highstate runs correctly when minion is 2016.3.0. I would 'just upgrade' but the 2016.3 centos7 minion isn't available in the repo right now. :) :)

```
   The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1078, in _thread_return
        return_data = func(*args, **kwargs)
      File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 693, in highstate
        whitelist=kwargs.get('whitelist')
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 3141, in call_highstate
        return self.state.call_high(high)
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 2156, in call_high
        ret = dict(list(disabled.items()) + list(self.call_chunks(chunks).items()))
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 1688, in call_chunks
        running = self.call_chunk(low, running, chunks)
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 1945, in call_chunk
        running = self.call_chunk(chunk, running, chunks)
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 1945, in call_chunk
        running = self.call_chunk(chunk, running, chunks)
...
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 1855, in call_chunk
        low = self._mod_aggregate(low, running, chunks)
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 677, in _mod_aggregate
        agg_opt = self.functions['config.option']('state_aggregate')
      File "/usr/lib/python2.7/site-packages/salt/loader.py", line 900, in __getitem__
        func = super(LazyLoader, self).__getitem__(item)
      File "/usr/lib/python2.7/site-packages/salt/utils/lazy.py", line 83, in __getitem__
        if self._missing(key):
    RuntimeError: maximum recursion depth exceeded
```

### Versions Report
master versions-report:
```
Salt Version:
           Salt: 2016.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.7.0
       dateutil: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.4.5.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

minion versions-report:
```
    Salt Version:
               Salt: 2015.8.10

    Dependency Versions:
             Jinja2: 2.7.2
           M2Crypto: Not Installed
               Mako: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.7.0
             Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
            libgit2: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.7
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: Not Installed
            timelib: Not Installed

    System Versions:
               dist: centos 7.2.1511 Core
            machine: x86_64
            release: 3.10.0-327.4.5.el7.x86_64
             system: CentOS Linux 7.2.1511 Core
```

**Comment by daveneeley** [comment]
Hmm. Maybe minion/master version is not the issue? I can repro against a minion built from the 2016.3 git branch via the bootstrap script. The same highstate definition continues to run correctly against the test machine.

**Comment by daveneeley** [comment]
Turns out if I remove the prereq condition like in #32591 that the highstate works correctly against the machine in question. So I have one machine where it works and one where it throws the error above. Calling it a dup.
