### ISSUE TITLE
 `no_chown` option is not working in pip.installed state

### ISSUE THREAD

**Issue by itbabu** [saltstack/salt#33634]
### Description

 `no_chown` option is ignored in  pip.installed state.
The state was working correctly before 2016.3.0 (Boron)
### Setup

Salt state

``` SALT
virtualenv_setup:
   pip.installed:
      - bin_env: /opt/penta/env/project
      - user: penta
      - requirements: /opt/penta/project/requirements.txt
      - no_chown: True
      - use_wheel: True
```

/opt/penta/project/requirements.txt contains

```
-r base.txt
uWSGI==2.0.12
```
### Steps to Reproduce Issue

Run the above state.

```
[INFO    ] Running state [virtualenv_setup] at time 14:06:42.334154
[INFO    ] Executing state pip.installed for virtualenv_setup
[INFO    ] Executing command '/opt/penta/env/project/bin/pip --version' in directory '/root'
[DEBUG   ] output: pip 8.1.2 from /opt/penta/env/project/lib/python3.5/site-packages (python 3.5)
[DEBUG   ] TREQ IS: None
[INFO    ] _process_requirements from directory,None -- requirement: /opt/penta/project/requirements.txt
[DEBUG   ] 
    cwd: None -> /opt/penta/project
    requirement: /opt/penta/project/requirements.txt -> requirements.txt

[INFO    ] _find_req -- link = requirements.txt
[INFO    ] _find_req -- link = requirements/production.txt
[INFO    ] _find_req -- link = requirements/base.txt
[INFO    ] request files: ['requirements.txt', 'requirements/production.txt', 'requirements/base.txt']
[DEBUG   ] TREQ N CWD: /tmp/tmpqIGOPF -- /opt/penta/project -- for requirements.txt
[DEBUG   ] S: /opt/penta/project/requirements.txt
[DEBUG   ] T: /tmp/tmpqIGOPF/requirements.txt
[DEBUG   ] Copying /opt/penta/project/requirements.txt to /tmp/tmpqIGOPF/requirements.txt
[DEBUG   ] Changing ownership of requirements file '/tmp/tmpqIGOPF/requirements.txt' to user 'penta'
[DEBUG   ] TREQ N CWD: /tmp/tmpqIGOPF -- /opt/penta/project -- for production.txt
[DEBUG   ] S: /opt/penta/project/production.txt
[DEBUG   ] T: /tmp/tmpqIGOPF/production.txt
[DEBUG   ] Copying /opt/penta/project/production.txt to /tmp/tmpqIGOPF/production.txt
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1703, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1649, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/states/pip_state.py", line 728, in installed
    trusted_host=trusted_host
  File "/usr/lib/python2.7/dist-packages/salt/modules/pip.py", line 603, in install
    user=user
  File "/usr/lib/python2.7/dist-packages/salt/modules/pip.py", line 312, in _process_requirements
    __salt__['file.copy'](source_path, target_path)
  File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 2890, in copy
    raise CommandExecutionError('No such file or directory \'{0}\''.format(src))
CommandExecutionError: No such file or directory '/opt/penta/project/production.txt'
```
### Versions Report

2016.3.0 (Boron)     

```
     Dependency Versions:
                 cffi: Not Installed
             cherrypy: Not Installed
             dateutil: 1.5
                gitdb: 0.5.4
            gitpython: 0.3.2 RC1
                ioflo: Not Installed
               Jinja2: 2.7.2
              libgit2: Not Installed
              libnacl: Not Installed
             M2Crypto: Not Installed
                 Mako: 0.9.1
         msgpack-pure: Not Installed
       msgpack-python: 0.3.0
         mysql-python: 1.2.3
            pycparser: Not Installed
             pycrypto: 2.6.1
               pygit2: Not Installed
               Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
         python-gnupg: Not Installed
               PyYAML: 3.10
                PyZMQ: 14.0.1
                 RAET: Not Installed
                smmap: 0.8.2
              timelib: Not Installed
              Tornado: 4.2.1
                  ZMQ: 4.0.4

      System Versions:
                 dist: Ubuntu 14.04 trusty
              machine: x86_64
              release: 3.13.0-85-generic
               system: Linux
              version: Ubuntu 14.04 trusty
```

**Comment by Ch3LL** [comment]
@itbabu I am able to replicate this issue in 2016.3.0 with my sls file pasted below:

```
virtualenv_setup:
   pip.installed:
      - user: ch3ll
      - requirements: /tmp/test-pip/requirements.txt
      - no_chown: True
      - use_wheel: True
```

And I am seeing this in the logs: `[DEBUG   ] Changing ownership of requirements file '/tmp/tmpsHin3G/base.txt' to user 'ch3ll'`


Here is the first bad commit (git bisect)

```
878def94fde9546dcfe9484d80d514bb7239cab1 is the first bad commit
commit 878def94fde9546dcfe9484d80d514bb7239cab1
Author: Stephen D. Spencer <stephen@revsys.com>
Date:   Sat Dec 26 21:30:27 2015 -0600

    pip,requirements filej chain support + requirements list arg support
    
    modules.pip:
     . `requirements` argument now properly supports requirements file
     chaining by default--`no_chown` not required)
     . `requirements` argument can be formed as a list
     . `requirements` files can still be formed as a comma-delimited list
     . both list structures support requirements file chaining
    
    states.virtualenv_mod:
     . had to give states.virtualenv.managed() a little bit of attention to
     provide a cwd argument for modules.pip.installed().  This is done via
     os.path.dirname(os.path.abspath(requirements)) if a requirements
     argument is present
    
     tests.integration.modules.pip:
        . added:
            test_requirements_as_list__sans_no_chown___absolute_file_path
            test_requirements_as_list__sans_no_chown___non_absolute_file_path
            test_chained_requirements__sans_no_chown___absolute_file_path
            test_chained_requirements__sans_no_chown___non_absolute_file_path
        . all tests passed before commit

:040000 040000 65c5b578a848a5d0aeb59660fa2892e4cdc3f1ed 7dfef7f3a414f8de40cafd75be83f783872be230 M      salt
:040000 040000 68ddd8d8c54227f41a8c1430066cb7e6176bd3f4 db5b2cd0a95f54ac6c50e15569a662d29b25001e M      tests
```

**Comment by hardikns** [comment]
Any update on this?

**Comment by Ch3LL** [comment]
@hardikns we do not currently have a salt engineer assigned to this issue due to other higher priority issues. Please feel free to take a look at a fix if anyone is willing :)
