### ISSUE TITLE
Problem with archive.extracted randomly failing when running state.highstate

### ISSUE THREAD

**Issue by eochoa260** [saltstack/salt#33714]
### Description of Issue/Question

Might be related to #31023 or #26911 but getting a different error.  Archive.extracted is randomly failing when attempting to download a file from s3.  Error occurs frequently but file varies and minion varies as well.  File sizes range from 250KB - 83 MB.  Also, the error only seems to occur when executed during cloud-init phase, I was not able to reproduce the error manually. 
### Setup

```
archive.extracted:
-    - source: s3://{{s3_path_to_file}}
-    - source_hash: {{file_hash}}
-    - archive_format: zip (or tar)
```
### Steps to Reproduce Issue

```
2016-05-31 21:28:10,895 [salt.utils.s3    ][DEBUG   ][8222] S3 Request: {{s3_https_url}}
2016-05-31 21:28:10,895 [salt.utils.s3    ][DEBUG   ][8222] S3 Headers::
2016-05-31 21:28:10,895 [salt.utils.s3    ][DEBUG   ][8222]     Authorization: AWS 
2016-05-31 21:28:10,896 [urllib3.connectionpool][INFO    ][8222] Starting new HTTPS connection (1): {{s3_bucket}}
2016-05-31 21:28:12,196 [urllib3.connectionpool][DEBUG   ][8222] "GET {{file}} HTTP/1.1" 200 87008665
2016-05-31 21:33:23,368 [salt.loaded.int.states.file][DEBUG   ][8222] Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/salt/states/file.py", line 1528, in managed
    follow_symlinks)
  File "/usr/local/lib/python2.7/site-packages/salt/modules/file.py", line 3531, in manage_file
    sfn = __salt__['cp.cache_file'](source, saltenv)
  File "/usr/local/lib/python2.7/site-packages/salt/modules/cp.py", line 344, in cache_file
    result = __context__['cp.fileclient'].cache_file(path, saltenv)
  File "/usr/local/lib/python2.7/site-packages/salt/fileclient.py", line 152, in cache_file
    return self.get_url(path, '', True, saltenv)
  File "/usr/local/lib/python2.7/site-packages/salt/fileclient.py", line 567, in get_url
    raise MinionError('Could not fetch from {0}'.format(url))
MinionError: Could not fetch from s3://{{s3_path_to_file}}

2016-05-31 21:33:23,368 [salt.state       ][ERROR   ][8222] Unable to manage file: Could not fetch from s3://{{s3_path_to_file}}
2016-05-31 21:33:23,368 [salt.state       ][INFO    ][8222] Completed state [/var/cache/salt/minion/files/base/_opt_logstash-1.5.0.tar] at time 21:33:23.368247
2016-05-31 21:33:23,368 [salt.loaded.int.states.archive][DEBUG   ][8222] file.managed: {'file_|-/var/cache/salt/minion/files/base/_opt_logstash-1.5.0.tar_|-/var/cache/salt/minion/files/base/_opt_logstash-1.5.0.tar_|-managed': {'comment': 'Unable to manage file: Could not fetch from s3://{{s3_path_to_file}}', 'name': '/var/cache/salt/minion/files/base/_opt_logstash-1.5.0.tar', 'start_time': '21:28:10.880811', 'result': False, 'duration': 312487.436, '__run_num__': 0, 'changes': {}}}
2016-05-31 21:33:23,369 [salt.loaded.int.states.archive][DEBUG   ][8222] failed to download s3://{{s3_path_to_file}}
2016-05-31 21:33:23,369 [salt.state       ][ERROR   ][8222] Unable to manage file: Could not fetch from s3://{{s3_path_to_file}}
2016-05-31 21:33:23,369 [salt.state       ][INFO    ][8222] Completed state [/opt] at time 21:33:23.368900
```
### Versions Report

Same issue occurs on each of these minions (masterless):

```
2015.5.0 versions report
Salt: 2015.5.0
Python: 2.7.10 (default, Dec  8 2015, 18:25:23)
Jinja2: 2.7.2
M2Crypto: 0.21.1
msgpack-python: 0.4.7
msgpack-pure: Not Installed
pycrypto: 2.6.1
libnacl: Not Installed
PyYAML: 3.10
ioflo: Not Installed
PyZMQ: 15.2.0
RAET: Not Installed
ZMQ: 4.1.2
Mako: Not Installed
```

```
2015.8.8.2 versions report
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.2.0
         Python: 2.7.10 (default, Dec  8 2015, 18:25:23)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.2
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist:   
        machine: x86_64
        release: 4.1.7-15.23.amzn1.x86_64
```

**Comment by Ch3LL** [comment]
@eochoa260 I'm having a hard time replicating this. Here is my test case:

```
test:
  archive.extracted:
    - name: /tmp/salt-test/
    - source: s3://ch3lltests/salt-2016.3.0.tar.gz
    - source_hash: md5=8ed82cfb3f9b1764a035edbdacf0fea9
    - archive_format: tar
```

Run highstate as masterless: `sudo salt-call --local state.highstate` 

I have tried running this a couple of times and it works each time and I do not see that error.

Since this is only occurring sometimes how often are you seeing it to help me try to replicate this issue. Also is there anything in my test case that would help me to replicate this?
