### ISSUE TITLE
Bad network format: missing 'uuid' 

### ISSUE THREAD

**Issue by SolarisYan** [saltstack/salt#33744]
Hello, i use salt-cloud -m /etc/salt/cloud.maps.d/openstack.conf -y -l debug  to create vm in my openstack,and the error like this:

[root@mesos-salve-2 cloud.maps.d]# salt-cloud -m /etc/salt/cloud.maps.d/openstack.conf -y -l debugsalt-cloud -m /etc/salt/cloud.maps.d/openstack.conf -y -l debug^C
You have new mail in /var/spool/mail/root
[root@mesos-salve-2 cloud.maps.d]# 
[root@mesos-salve-2 cloud.maps.d]# salt-cloud -m /etc/salt/cloud.maps.d/openstack.conf -y -l debug
[DEBUG   ] Reading configuration from /etc/salt/cloud
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/db_mysql.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/db_mysql.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/eauth.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/eauth.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/file_roots.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/file_roots.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/metrics.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/metrics.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/mongo.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/mongo.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/peer.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/peer.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/raet.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/raet.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/reactor.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/reactor.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/saltapi.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/saltapi.conf
[DEBUG   ] Missing configuration file: /etc/salt/cloud.providers
[DEBUG   ] Including configuration from '/etc/salt/cloud.providers.d/openstack.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers.d/openstack.conf
[DEBUG   ] Missing configuration file: /etc/salt/cloud.profiles
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/openstack.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/openstack.conf
[DEBUG   ] Configuration file path: /etc/salt/cloud
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] salt-cloud starting
[DEBUG   ] Could not LazyLoad parallels.avail_sizes
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy
[DEBUG   ] Could not LazyLoad saltify.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.avail_images
[DEBUG   ] Could not LazyLoad saltify.avail_locations
[DEBUG   ] LazyLoaded rackspace.reboot
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] LazyLoaded rackspace.list_locations
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] compile template: /etc/salt/cloud.maps.d/openstack.conf
[DEBUG   ] Jinja search path: '['/var/cache/salt/master/files/base']'
[PROFILE ] Time (in seconds) to render '/etc/salt/cloud.maps.d/openstack.conf' using 'jinja' renderer: 0.00580406188965
[DEBUG   ] Rendered data from file: /etc/salt/cloud.maps.d/openstack.conf:
# The map file is pretty straightforward. 
# First we tell it what profile to use (openstack_profile) and then specify a list of hostnames to create
# Now, let's get to the fun part!

#openstack_micro:
#  - saltstack.openstack.com
  # - saltstack1.openstack.com

openstack_m1_small_profile:
  - saltstack2.openstack.com

[DEBUG   ] Results of YAML rendering: 
OrderedDict([('openstack_m1_small_profile', ['saltstack2.openstack.com'])])
[PROFILE ] Time (in seconds) to render '/etc/salt/cloud.maps.d/openstack.conf' using 'yaml' renderer: 0.00206398963928
[INFO    ] Applying map from '/etc/salt/cloud.maps.d/openstack.conf'.
[DEBUG   ] Could not LazyLoad nova.optimize_providers
[DEBUG   ] The 'nova' cloud driver is unable to be optimized.
[DEBUG   ] Could not LazyLoad parallels.avail_sizes
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy
[DEBUG   ] Could not LazyLoad saltify.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.avail_images
[DEBUG   ] Could not LazyLoad saltify.avail_locations
[DEBUG   ] LazyLoaded rackspace.reboot
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] LazyLoaded rackspace.list_locations
[INFO    ] Calculating dependencies for saltstack2.openstack.com
[DEBUG   ] Got execution order 0 for saltstack2.openstack.com
[DEBUG   ] No make_master found in map
[DEBUG   ] Generating minion keys for 'saltstack2.openstack.com'
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event - data = {'profile': 'openstack_m1_small_profile', 'event': 'starting create', '_stamp': '2016-06-03T08:31:49.198106', 'name': 'saltstack2.openstack.com', 'provider': 'openstack-provider:nova'}
[INFO    ] Creating Cloud VM saltstack2.openstack.com
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event - data = {'_stamp': '2016-06-03T08:31:50.580185', 'event': 'requesting instance', 'kwargs': {'image': u'537292cb-9310-406a-9589-7fb13e26599c', 'name': 'saltstack2.openstack.com', 'size': u'2'}}
[ERROR   ] Failed to deploy 'saltstack2.openstack.com'. Error: Error creating saltstack2.openstack.com on Nova

The following exception was thrown by libcloud when trying to run the initial deployment: Bad network format: missing 'uuid' (HTTP 400) (Request-ID: req-3bb70009-bb09-43de-a3a2-2efdb0ab4502)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 2210, in run_map
    profile, local_master=local_master
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1283, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/nova.py", line 719, in create
    data, vm_ = request_instance(vm_)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/nova.py", line 644, in request_instance
    vm_['name'], exc
SaltCloudSystemExit: Error creating saltstack2.openstack.com on Nova

The following exception was thrown by libcloud when trying to run the initial deployment: Bad network format: missing 'uuid' (HTTP 400) (Request-ID: req-3bb70009-bb09-43de-a3a2-2efdb0ab4502)

[INFO    ] Complete
[DEBUG   ] LazyLoaded nested.output
saltstack2.openstack.com:
    ----------
    Error:
        Error creating saltstack2.openstack.com on Nova
        
        The following exception was thrown by libcloud when trying to run the initial deployment: Bad network format: missing 'uuid' (HTTP 400) (Request-ID: req-3bb70009-bb09-43de-a3a2-2efdb0ab4502)

my conf:
cat /etc/salt/cloud.providers.d/openstack.conf
openstack-provider:
  # Set the location of the salt-master
  minion:
    master: 192.168.111.60

  # The provider parameter in cloud provider definitions was renamed to driver
  # driver: openstack
  driver: nova

  # Configure the OpenStack driver
  identity_url: http://10.20.100.3:5000/v2.0/  
  # compute_name: nova
  # protocol: ipv4

  compute_region: RegionOne

  # Configure Openstack authentication credentials
  user: admin
  password: xxx

  # tenant is the project name
  tenant: saltstack
  # tenant: admin

  # skip SSL certificate validation (default false)
  insecure: false

cat /etc/salt/cloud.profiles.d/openstack.conf
openstack_m1_small_profile:
  provider: openstack-provider
  size: m1.small
  image: CentOS7
  ssh_key_file: /software/openstack/key/saltstack.pem
  ssh_key_name: saltstack
  ssh_interface: private_ips
  ssh_username: centos
  networks:
   - fixed:
     - da099981-3acb-448c-a188-899181e7399e

cat /etc/salt/cloud.maps.d/openstack.conf
openstack_m1_small_profile:
  - saltstack2.openstack.com

salt --versions-report
Salt Version:
           Salt: 2016.3.0
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: 5.4.0
       dateutil: 2.5.3
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: 1.5.4
         Jinja2: 2.8
        libgit2: 0.21.0
        libnacl: 1.4.4
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.4
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: 0.6.5
          smmap: 0.8.1
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.4.4.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

any one can help me ?

**Comment by SolarisYan** [comment]
with this conf  that's  ok:

  networks:
    - net-id: da099981-3acb-448c-a188-899181e7399e
