### ISSUE TITLE
The minion function caused an exception: Traceback (most recent call last):

### ISSUE THREAD

**Issue by lancelinksp** [saltstack/salt#33760]
The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1161, in _thread_return
        return_data = func(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 523, in highstate
        whitelist=kwargs.get('whitelist')
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2968, in call_highstate
        return self.state.call_high(high)
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2067, in call_high
        ret = dict(list(disabled.items()) + list(self.call_chunks(chunks).items()))
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1623, in call_chunks
        running = self.call_chunk(low, running, chunks)
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1769, in call_chunk
        self._mod_init(low)
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 612, in _mod_init
        self.states['{0}.{1}'.format(low['state'], low['fun'])]  # pylint: disable=W0106
      File "/usr/lib/python2.7/dist-packages/salt/utils/lazy.py", line 90, in __getitem__
        raise KeyError(key)
    KeyError: 'file.'

Not sure why this is happening or how to resolve it since the log isnt very clear ( at least to me ) on what the problem is.  I bit of help would be appreciated since this is happening almost everytime I run highstate. Thanks.

**Comment by cachedout** [comment]
This is like you've written a state file that somehow doesn't call a function. We need to see your states here to find out what's going on. Especially any SLS that tries to call out to the `file` state.

**Comment by lancelinksp** [comment]
I just found the problem. Thanks for the quick response. I had file..managed  Not sure how that happened. Maybe I fell asleep at the wheel.

**Comment by cachedout** [comment]
Nice work. Even so, I'm going to modify the state compiler so that we can catch that and display a better error. Thanks for alerting us to this!
