### ISSUE TITLE
Configuring Salt master with libgit2 0.20.0 and pygit2 0.20.0 as recommended

### ISSUE THREAD

**Issue by mo-mughrabi** [saltstack/salt#33781]
I've been trying to build a docker file to install salt with pygit2 for `gitfs_provider` using a debian:jessie release.

It seems like salt is not detecting `libgit2` or/and `pygit2`, I get the following message

```
[ERROR   ] Git fileserver backend is enabled in master config file, but could not be loaded, are pygit2 and libgit2 installed?
[ERROR   ] GitPython is installed, you may wish to set gitfs_provider to 'gitpython' in the master config file to use GitPython for gitfs support.
```

This is my Dockerfile

```Dockerfile
FROM debian:jessie

# Install packages
ADD http://debian.saltstack.com/debian-salt-team-joehealy.gpg.key /tmp/debian-salt-team-joehealy.gpg.key
RUN echo "deb http://debian.saltstack.com/debian jessie-saltstack main" | tee /etc/apt/sources.list.d/saltstack.list && \
    apt-key add /tmp/debian-salt-team-joehealy.gpg.key && \
    DEBIAN_FRONTEND=noninteractive apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -yqq \
    salt-master \
    salt-minion \
    salt-cloud \
    salt-api \
    salt-ssh \
    salt-syndic \
    cmake \
    gcc \
    pkg-config \
    libssh2-1-dev \
    libssl-dev \
    libffi-dev \
    python-dev \
    python-pip \
    build-essential \
    git \
    python-setuptools \
    libgit2-dev \
    zlib1g \
    libssl1.0.0 \
    libhttp-parser-dev \
    libc6 \
    ca-certificates

RUN cd /tmp && \
    wget https://github.com/openssl/openssl/archive/OpenSSL_1_0_1r.tar.gz && \
    tar xzf OpenSSL_1_0_1r.tar.gz && \
    cd openssl-OpenSSL_1_0_1r && \
    ./config -fPIC --prefix=/usr -ldl && \
    make && \
    make install

RUN cd /tmp && \
    wget https://github.com/libgit2/libgit2/archive/v0.20.0.tar.gz && \
    tar xzf v0.20.0.tar.gz && \
    cd libgit2-0.20.0/

RUN cd /tmp/libgit2-0.20.0 && \
    cmake -DCMAKE_INSTALL_PREFIX=/usr && \
    cmake --build . --target install && \
    ldconfig

RUN pip install pip==8.1.2 && \
    pip install --upgrade cffi && \
    pip install -I pygit2==0.20.0 && \
    pip install cherrypy==3.2.2 \
                tornado==4.3 \
                docker-py==1.8.1 \
                halite==0.1.17 \
                GitPython==0.3.2.RC1 \
                pyOpenSSL==0.15.1
# Ports
EXPOSE 4505 4506

# Run Command
CMD "salt-master"

```

Can someone please advise?

**Comment by mo-mughrabi** [comment]
nvm, am getting this in when importing `pygit2`

```
root@68ebbbdc44fd:/# python
Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygit2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pygit2/__init__.py", line 32, in <module>
    import _pygit2
ImportError: /usr/local/lib/python2.7/dist-packages/_pygit2.so: undefined symbol: git_note_oid
```

**Comment by mo-mughrabi** [comment]
If anyone else interested, I opened a case in `libgit2` repo https://github.com/libgit2/pygit2/issues/635
