### ISSUE TITLE
Puppet module does not work with agent version >= 4.0

### ISSUE THREAD

**Issue by x3dfxjunkie** [saltstack/salt#33797]
### Description of Issue/Question
The puppet module references old directories for the puppet agent, when the agent version is 4.x or higher.

https://docs.puppet.com/puppet/4.0/reference/whered_it_go.html

### Setup
Base salt master / minion setup, with puppet-agent package installed (instead of puppet and puppet-common).

### Steps to Reproduce Issue
3.x Agent:
```
$ sudo salt 'host*' cmd.run 'puppet --version'
host01.example.com:
    3.8.7
$ sudo salt 'host*' puppet.status
host01.example.com:
    Idle daemon
$ sudo salt 'host*' service.status puppet
host01.example.com:
    True
$ sudo salt 'host*' puppet.disable testing
host01.example.com:
    True
$ sudo salt 'host*' puppet.status
host01.example.com:
    Administratively disabled
```
4.x Agent:
```
$ sudo salt 'host*' cmd.run 'puppet --version'
host01.example.com:
    4.5.0
$ sudo salt 'host*' puppet.status
host01.example.com:
    Stopped
$ sudo salt 'host*' service.status puppet
host01.example.com:
    True
$ sudo salt 'host*' puppet.disable testing
host01.example.com:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1317, in _thread_return
        return_data = executor.execute()
      File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/puppet.py", line 238, in disable
        with salt.utils.fopen(puppet.disabled_lockfile, 'w') as lockfile:
      File "/usr/lib/python2.7/dist-packages/salt/utils/__init__.py", line 1209, in fopen
        fhandle = open(*args, **kwargs)
    IOError: [Errno 2] No such file or directory: '/var/lib/puppet/state/agent_disabled.lock'
```
### Versions Report
```
Salt Version:
           Salt: 2016.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-86-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by cachedout** [comment]
I believe this should now be resolved since we have merged #33809
