### ISSUE TITLE
salt packages should require python-futures on ubuntu 14.04 (ImportError: No module named concurrent.futures)

### ISSUE THREAD

**Issue by ahammond** [saltstack/salt#33801]
### Description of Issue/Question

salt-common or perhaps salt-minion does not require python-futures package, but fails to run if python-futures are not available. This might actually be a Tornado packaging issue.

### Setup

Start up a fresh Ubuntu 14.04 box and then salt-bootstrap.

### Steps to Reproduce Issue

```bash
  ahammond@dev-intel1:~$ sudo service salt-minion restart; sudo tail -F /var/log/salt/minion
  salt-minion stop/waiting
  salt-minion start/running, process 16617
    File "/usr/lib/python2.7/dist-packages/tornado/util.py", line 222, in __new__
      instance.initialize(*args, **init_kwargs)
    File "/usr/lib/python2.7/dist-packages/tornado/netutil.py", line 406, in initialize
      threadpool = ThreadedResolver._create_threadpool(num_threads)
    File "/usr/lib/python2.7/dist-packages/tornado/netutil.py", line 418, in _create_threadpool
      from concurrent.futures import ThreadPoolExecutor
  ImportError: No module named concurrent.futures
```

### Workaround

`apt-get install python-futures`

### Versions Report

```bash
ahammond@dev-intel1:~$ sudo salt-call --local test.versions
local:
    Salt Version:
               Salt: 2016.3.0

    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 1.5
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.7.2
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: 0.9.1
       msgpack-pure: Not Installed
     msgpack-python: 0.3.0
       mysql-python: 1.2.3
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
       python-gnupg: Not Installed
             PyYAML: 3.10
              PyZMQ: 14.0.1
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.4

    System Versions:
               dist: Ubuntu 14.04 trusty
            machine: x86_64
            release: 3.13.0-85-generic
             system: Linux
            version: Ubuntu 14.04 trusty
```

**Comment by thatch45** [comment]
@dmurphy18 This is an easy add to the Ubuntu packages, Tornado should pull in python-futures, but the Tornado package might not be doing it, so it is fine to make salt explicitly require it as well

**Comment by jfindlay** [comment]
@ahammond, I created a new ubuntu 14.04 system and ran bootstrapped it with `curl -L https://bootstrap.saltstack.com | sh -s -- stable -D` and did not have this problem.
```console
root@jmoney-ubuntu-14:~# service salt-minion restart
salt-minion stop/waiting
salt-minion start/running, process 4602
```
```console
root@jmoney-ubuntu-14:~# tail -F /var/log/salt/minion
2016-06-06 16:00:01,719 [salt.cli.daemons ][INFO    ][4473] The salt minion is shutting down..
2016-06-06 16:00:01,719 [salt.cli.daemons ][INFO    ][4473] The Salt Minion is shut down
2016-06-06 16:00:02,133 [salt.cli.daemons ][INFO    ][4608] Setting up the Salt Minion "jmoney-ubuntu-14"
2016-06-06 16:00:02,445 [salt.minion      ][INFO    ][4608] Creating minion process manager
2016-06-06 16:00:02,447 [salt.cli.daemons ][WARNING ][4608] IMPORTANT: Do not use md5 hashing algorithm! Please set "hash_type" to sha256 in Salt Minion config!
2016-06-06 16:00:02,447 [salt.cli.daemons ][INFO    ][4608] The Salt Minion is starting up
2016-06-06 16:00:02,448 [salt.minion      ][INFO    ][4608] Minion is starting as user 'root'
2016-06-06 16:00:02,448 [salt.utils.event ][INFO    ][4608] Starting pull socket on /var/run/salt/minion/minion_event_53a22658e0_pull.ipc
2016-06-06 16:00:02,454 [salt.utils       ][ERROR   ][4608] DNS lookup of 'salt' failed.
2016-06-06 16:00:02,454 [salt.minion      ][ERROR   ][4608] Master hostname: 'salt' not found. Retrying in 30 seconds
```
```yaml
root@jmoney-ubuntu-14:~# salt-call --local --versions
Salt Version:
           Salt: 2016.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-85-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by ahammond** [comment]
I think these had 2015.8.10 on them initially and were upgraded. Anyway,
same problem on two boxes.

**Comment by jfindlay** [comment]
I am able to get this stack trace after updating the minion config.  Both `master` and `transport` were required to achieve the stack trace.
```console
root@jmoney-ubuntu-14:~# service salt-minion stop
salt-minion stop/waiting
```
```sls
root@jmoney-ubuntu-14:~# cat > /etc/salt/minion
master: 104.239.193.113
transport: tcp
```
```py
root@jmoney-ubuntu-14:~# salt-minion -l debug
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: jmoney-ubuntu-14
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] Setting up the Salt Minion "jmoney-ubuntu-14"
[DEBUG   ] Created pidfile: /var/run/salt-minion.pid
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[INFO    ] Creating minion process manager
[WARNING ] IMPORTANT: Do not use md5 hashing algorithm! Please set "hash_type" to sha256 in Salt Minion config!
[INFO    ] The Salt Minion is starting up
[INFO    ] Minion is starting as user 'root'
[DEBUG   ] AsyncEventPublisher PUB socket URI: /var/run/salt/minion/minion_event_53a22658e0_pub.ipc
[DEBUG   ] AsyncEventPublisher PULL socket URI: /var/run/salt/minion/minion_event_53a22658e0_pull.ipc
[INFO    ] Starting pull socket on /var/run/salt/minion/minion_event_53a22658e0_pull.ipc
[DEBUG   ] Minion 'jmoney-ubuntu-14' trying to tune in
[DEBUG   ] sync_connect_master
[DEBUG   ] Connecting to master. Attempt 1 of 1
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_53a22658e0_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_53a22658e0_pull.ipc
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'jmoney-ubuntu-14', 'tcp://104.239.193.113:4506')
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Process Manager starting!
[DEBUG   ] Initializing new AsyncTCPReqChannel for ('/etc/salt/pki/minion', 'jmoney-ubuntu-14', 'tcp://104.239.193.113:4506', 'clear')
[ERROR   ] Exception in callback <functools.partial object at 0x7fb436db5998>
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/ioloop.py", line 592, in _run_callback
    ret = callback()
  File "/usr/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/tornado/ioloop.py", line 598, in <lambda>
    self.add_future(ret, lambda f: f.result())
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 230, in wrapper
    yielded = next(result)
  File "/usr/lib/python2.7/dist-packages/salt/crypt.py", line 462, in _authenticate
    io_loop=self.io_loop)
  File "/usr/lib/python2.7/dist-packages/salt/transport/client.py", line 114, in factory
    return salt.transport.tcp.AsyncTCPReqChannel(opts, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/tcp.py", line 134, in __new__
    new_obj.__singleton_init__(opts, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/tcp.py", line 176, in __singleton_init__
    resolver=resolver)
  File "/usr/lib/python2.7/dist-packages/salt/transport/tcp.py", line 611, in __init__
    opts, io_loop=self.io_loop, resolver=resolver)
  File "/usr/lib/python2.7/dist-packages/salt/transport/tcp.py", line 580, in __init__
    resolver=resolver, io_loop=io_loop)
  File "/usr/lib/python2.7/dist-packages/tornado/tcpclient.py", line 149, in __init__
    self.resolver = Resolver(io_loop=io_loop)
  File "/usr/lib/python2.7/dist-packages/tornado/util.py", line 222, in __new__
    instance.initialize(*args, **init_kwargs)
  File "/usr/lib/python2.7/dist-packages/tornado/netutil.py", line 406, in initialize
    threadpool = ThreadedResolver._create_threadpool(num_threads)
  File "/usr/lib/python2.7/dist-packages/tornado/netutil.py", line 418, in _create_threadpool
    from concurrent.futures import ThreadPoolExecutor
ImportError: No module named concurrent.futures
^C[WARNING ] Minion received a SIGINT. Exiting.
[INFO    ] The salt minion is shutting down..
[INFO    ] The Salt Minion is shut down
```

**Comment by cachedout** [comment]
Since this is purely packaging, we're going to track this over here and close this: https://github.com/saltstack/salt-pack/issues/96

Thanks, @ahammond. Please subscribe to the issue linked above if you'd like updates on progress. Thanks!
