### ISSUE TITLE
2016.3 Test Suite TCP Error

### ISSUE THREAD

**Issue by richardscollin** [saltstack/salt#33843]
### Description of Issue/Question
Running the salt test suit with tcp as the transport protocol results in the
following error after the tests are run. Note that the error is repeated 4 times
(once for each thread/process)

```
Process MWorker-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/site-packages/salt/utils/process.py", line 613, in _run
    return self._original_run()
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 885, in run
    self.__bind()
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 815, in __bind
    self.io_loop.start()
  File "/usr/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 151, in start
    super(ZMQIOLoop, self).start()
  File "/usr/lib/python2.7/site-packages/tornado/ioloop.py", line 841, in start
    event_pairs = self._impl.poll(poll_timeout)
  File "/usr/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 122, in poll
    z_events = self._poller.poll(1000*timeout)
  File "/usr/lib/python2.7/site-packages/zmq/sugar/poll.py", line 101, in poll
    return zmq_poll(self.sockets, timeout=timeout)
  File "zmq/backend/cython/_poll.pyx", line 122, in zmq.backend.cython._poll.zmq_poll (zmq/backend/cython/_poll.c:1746)
  File "zmq/backend/cython/_poll.pyx", line 115, in zmq.backend.cython._poll.zmq_poll (zmq/backend/cython/_poll.c:1625)
  File "zmq/backend/cython/checkrc.pxd", line 12, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/_poll.c:1958)
    PyErr_CheckSignals()
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 802, in _handle_signals
    channel.close()
  File "/usr/lib/python2.7/site-packages/salt/transport/tcp.py", line 435, in close
    self._socket.shutdown(socket.SHUT_RDWR)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 107] Transport endpoint is not connected
```

### Setup
Install 2016.3 branch. Run the tests in tcp transport mode:
`python tests/runtests.py --transport=tcp -n integration.states.user`

### Versions Report
```
Salt Version:
           Salt: 2016.3.0-41-g3f6d06a

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.5
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, May 23 2016, 16:22:41)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.3

System Versions:
           dist:
        machine: x86_64
        release: 4.1.15-rt17-nilrt
         system: Linux
        version: Not Installed
```

**Comment by cachedout** [comment]
Take a look at #33860. That should fix this up.

**Comment by richardscollin** [comment]
Yep #33860 fixes it.
