### ISSUE TITLE
Salt master log un-handled exception, Unable to run command '['None', '-s', 'bios-version']'

### ISSUE THREAD

**Issue by MartinMystikJonas** [saltstack/salt#33929]
In our test environment after upgrade to salt 2016.3 master log file is filling with this:

```
2016-06-10 13:06:15,132 [salt.utils.process][ERROR][17408] An un-handled exception from the multiprocessing process 'Maintenance-2364' was caught:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/process.py", line 613, in _run
    return self._original_run()
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 223, in run
    self._post_fork_init()
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 199, in _post_fork_init
    self.search = salt.search.Search(self.opts)
  File "/usr/lib/python2.7/dist-packages/salt/search/__init__.py", line 99, in __init__
    matcher=False)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 662, in __init__
    self.opts['grains'] = salt.loader.grains(opts)
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 702, in grains
    ret = fun()
  File "/usr/lib/python2.7/dist-packages/salt/grains/core.py", line 1468, in os_data
    grains.update(_hw_data(grains))
  File "/usr/lib/python2.7/dist-packages/salt/grains/core.py", line 1897, in _hw_data
    'biosversion': __salt__['smbios.get']('bios-version'),
  File "/usr/lib/python2.7/dist-packages/salt/modules/smbios.py", line 88, in get
    val = _dmidecoder('-s {0}'.format(string)).strip()
  File "/usr/lib/python2.7/dist-packages/salt/modules/smbios.py", line 329, in _dmidecoder
    return salt.modules.cmdmod._run_quiet('{0} {1}'.format(DMIDECODER, args))
  File "/usr/lib/python2.7/dist-packages/salt/modules/cmdmod.py", line 618, in _run_quiet
    pillar_override=pillar_override)['stdout']
  File "/usr/lib/python2.7/dist-packages/salt/modules/cmdmod.py", line 475, in _run
    'reason: {2}'.format(cmd, kwargs, exc)
CommandExecutionError: Unable to run command '['None', '-s', 'bios-version']' with the context '{'timeout': None, 'with_communicate': True, 'shell': False, 'bg': False, 'stderr': -2, 'env': {'LC_NUMERIC': 'C', 'CONSOLE': '/dev/console', 'LC_ADDRESS': 'C', 'RUNLEVEL': '3', 'LINES': '24', 'LC_CTYPE': 'C', 'LC_TELEPHONE': 'C', 'LC_PAPER': 'C', 'PATH': '/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin', 'COLUMNS': '80', 'previous': 'N', 'LC_IDENTIFICATION': 'C', 'SHELL': '/bin/sh', 'container': 'lxc', 'LC_MESSAGES': 'C', 'LC_MONETARY': 'C', 'LC_COLLATE': 'C', 'PREVLEVEL': 'N', 'LC_MEASUREMENT': 'C', 'PWD': '/', 'runlevel': '3', 'LC_NAME': 'C', 'LC_TIME': 'C', 'INIT_VERSION': 'sysvinit-2.88'}, 'stdout': -1, 'close_fds': True, 'stdin': None, 'cwd': '/root'}', reason: [Errno 2] No such file or directory
2016-06-10 13:06:15,141 [salt.utils.process][INFO][747] Process <class 'salt.master.Maintenance'> (17408) died with exit status None, restarting...
```
### Setup
Fresh installed salt 2016.3 in LXC container with Debian Jessie

### Versions Report
```
Salt Version:
           Salt: 2016.3.0
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.8 (default, Oct 18 2014, 12:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian jessie/sid 
        machine: x86_64
        release: 3.13.0-27-generic
         system: Linux
        version: debian jessie/sid 
```

**Comment by Ch3LL** [comment]
@MartinMystikJonas I believe this would be fixed by this PR #33555 Would you mind giving that a try and see if it helps. Thanks
