### ISSUE TITLE
Salt - windows minion cannot do anything

### ISSUE THREAD

**Issue by phil123456** [saltstack/salt#33927]
### Description of Issue/Question

all salt interaction bring this errors on windows 7 (64)

let me know what info you need to investigate this

C:\salt>salt-minion restart
[INFO    ] Setting up the Salt Minion "phil"
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'module' object has no attribute 'getppid'
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-minion", line 26, in <module>
    salt_minion()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 112, in salt_minion
    minion.start()
  File "C:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 344, in start
    super(Minion, self).start()
  File "C:\salt\bin\lib\site-packages\salt\utils\parsers.py", line 932, in start
    self.prepare()
  File "C:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 307, in prepare
    if self.check_running():
  File "C:\salt\bin\lib\site-packages\salt\utils\parsers.py", line 915, in check_running
    if self.check_pidfile() and self.is_daemonized(pid) and not os.getppid() == pid:
AttributeError: 'module' object has no attribute 'getppid'
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-minion", line 26, in <module>
    salt_minion()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 112, in salt_minion
    minion.start()
  File "C:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 344, in start
    super(Minion, self).start()
  File "C:\salt\bin\lib\site-packages\salt\utils\parsers.py", line 932, in start
    self.prepare()
  File "C:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 307, in prepare
    if self.check_running():
  File "C:\salt\bin\lib\site-packages\salt\utils\parsers.py", line 915, in check_running
    if self.check_pidfile() and self.is_daemonized(pid) and not os.getppid() == pid:
AttributeError: 'module' object has no attribute 'getppid'

### Setup
steps : https://docs.saltstack.com/en/latest/topics/installation/windows.html

### Steps to Reproduce Issue
steps : https://docs.saltstack.com/en/latest/topics/installation/windows.html

### Versions Report
...

**Comment by Ch3LL** [comment]
@phil123456 i'm not able to replicate this behavior. Can you point me to which package you installed and how you installed the minion? Thanks!

**Comment by Jabberwocke** [comment]
Hi there. The same problem on windows platform. Tried both packages : Salt-Minion-2016.3.0-x86-Setup.exe and Salt-Minion-2016.3.0-AMD64-Setup.exe - using gui or quiet installation. Tested on WS2008/R2, WS2012. Traceback:
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'module' object has no attribute 'getppid'
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-minion", line 26, in <module>
    salt_minion()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 112, in salt_minion
    minion.start()
  File "C:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 344, in start
    super(Minion, self).start()
  File "C:\salt\bin\lib\site-packages\salt\utils\parsers.py", line 932, in start
    self.prepare()
  File "C:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 307, in prepare
    if self.check_running():
  File "C:\salt\bin\lib\site-packages\salt\utils\parsers.py", line 915, in check_running
    if self.check_pidfile() and self.is_daemonized(pid) and not os.getppid() == pid:
AttributeError: 'module' object has no attribute 'getppid'
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-minion", line 26, in <module>
    salt_minion()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 112, in salt_minion
    minion.start()
  File "C:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 344, in start
    super(Minion, self).start()
  File "C:\salt\bin\lib\site-packages\salt\utils\parsers.py", line 932, in start
    self.prepare()
  File "C:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 307, in prepare
    if self.check_running():
  File "C:\salt\bin\lib\site-packages\salt\utils\parsers.py", line 915, in check_running
    if self.check_pidfile() and self.is_daemonized(pid) and not os.getppid() == pid:
AttributeError: 'module' object has no attribute 'getppid'

**Comment by phil123456** [comment]
the minion is installed on windows, so I use the available installer on saltstack website

it's a bit annoying for debugging stuffs on windows, but so far, configs are pushed correctly from the master... onli minion cli seems to caus issues. on cannot run any command

I use windows 7 Pro SP1 64. tell me if you need more info

**Comment by lorengordon** [comment]
Hmm, is the `salt-minion` command used on Windows? If you want to start the minion service, did you try using the normal Windows utilities? Using PowerShell: `Start-Service salt-minion`...

When running salt commands on Windows, I typically use [`C:\salt\salt-call.bat`](https://docs.saltstack.com/en/latest/ref/cli/salt-call.html). Perhaps that will work better for you as well?

**Comment by phil123456** [comment]
salt-call does not pause problem, to restart the minion I go to windows services and restart it
but most of .bat command give that same error

**Comment by phil123456** [comment]
ok and is the exe updated ?
