### ISSUE TITLE
salt-ssh, cassandra_cql error

### ISSUE THREAD

**Issue by natemarks** [saltstack/salt#34082]
when I set /etc/salt/master:
master_job_cache: cassandra_cql

salt '*'  test.ping  jobs run fine and the output goes to cassandra.

but when i run

salt-ssh <TARGET> test.ping

I get this:

```
[root@ncaresalt01 ~]# salt-ssh <VALID_TARGET_FROM_ROSTER> test.ping
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: prep_jid() takes at least 1 argument (0 given)
Traceback (most recent call last):
  File "/usr/bin/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 381, in salt_ssh
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/ssh.py", line 21, in run
    ssh.run()
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 500, in run
    jid = self.returners[fstr]()
TypeError: prep_jid() takes at least 1 argument (0 given)
Traceback (most recent call last):
  File "/usr/bin/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 381, in salt_ssh
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/ssh.py", line 21, in run
    ssh.run()
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 500, in run
    jid = self.returners[fstr]()
TypeError: prep_jid() takes at least 1 argument (0 given)
```

When I comment out that master_job_cache  setting and restart the master, it works fine.  I think it's a bug,

```
Salt Version:
           Salt: 2015.8.5


Here is the versions report. 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.10.1.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
```

Please let me know if I can help or re-test.

Thanks!

**Comment by Ch3LL** [comment]
@natemarks it looks like the cassandra_cql returner is expecting an argument which is different from the rest of the returners I glanced at. If you take a look [here](https://github.com/saltstack/salt/blob/v2015.8.5/salt/returners/cassandra_cql_return.py#L399) you can see the cassandra_cql returner is looking for nocache, but in other returners like cassandra it has no cache as a kwarg shown [here](https://github.com/saltstack/salt/blob/v2015.8.5/salt/returners/cassandra_return.py#L79) 

Definitely need to get this fixed up. Thanks
