### ISSUE TITLE
Salt minion connection failed on Windows Server 2008

### ISSUE THREAD

**Issue by wyhysj** [saltstack/salt#34202]
I installed Salt-Minion-2016.3.1-AMD64-Setup.exe and it fails to connect the master

This is the output of running salt-minion-debug.bat

```
2016-06-22 20:18:52,889 [salt.utils.verify][WARNING ][64416] Insecure logging configuration detected! Sensitive data may be logged.
2016-06-22 20:18:52,889 [salt.cli.daemons ][INFO    ][64416] Setting up the Salt Minion "xxxxx"
2016-06-22 20:18:52,967 [salt.utils.process][DEBUG   ][64416] Created pidfile: c:\salt\var\run\salt-minion.pid
2016-06-22 20:19:14,011 [salt.log.setup   ][ERROR   ][64416] An un-handled exception was caught by salt's global exception handler:
error: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
Traceback (most recent call last):
  File "c:\salt\bin\Scripts\salt-minion", line 26, in <module>
    salt_minion()
  File "c:\salt\bin\lib\site-packages\salt\scripts.py", line 112, in salt_minion
    minion.start()
  File "c:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 344, in start
    super(Minion, self).start()
  File "c:\salt\bin\lib\site-packages\salt\utils\parsers.py", line 932, in start
    self.prepare()
  File "c:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 327, in prepare
    self.minion = salt.minion.Minion(self.config)
  File "c:\salt\bin\lib\site-packages\salt\minion.py", line 815, in __init__
    self.io_loop = LOOP_CLASS.current()
  File "c:\salt\bin\lib\site-packages\zmq\eventloop\ioloop.py", line 158, in current
    return PollIOLoop.current(*args, **kwargs)
  File "c:\salt\bin\lib\site-packages\tornado\ioloop.py", line 209, in current
    return IOLoop.instance()
  File "c:\salt\bin\lib\site-packages\tornado\ioloop.py", line 161, in instance
    IOLoop._instance = IOLoop()
  File "c:\salt\bin\lib\site-packages\tornado\util.py", line 221, in __new__
    instance.initialize(*args, **init_kwargs)
  File "c:\salt\bin\lib\site-packages\zmq\eventloop\ioloop.py", line 133, in initialize
    super(ZMQIOLoop, self).initialize(impl=impl, **kwargs)
  File "c:\salt\bin\lib\site-packages\tornado\ioloop.py", line 701, in initialize
    self._waker = Waker()
  File "c:\salt\bin\lib\site-packages\tornado\platform\common.py", line 44, in __init__
    self.writer.connect(connect_address)
  File "c:\salt\bin\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
```

I try to do tcpdump on salt master, no package received on master when the batch script runs, but when I do telnet on the minion, the port is open.

I already installed Microsoft Visual C++ 2008 x64 SP1 redistributable and tried the old version  Salt-Minion-2015.8.10-2-AMD64-Setup.exe

But still same error.

**Comment by tmehlinger** [comment]
Possible firewall issue? Check to see if Windows firewall allows connections outbound to your master. Also check that the master firewall (assuming it has one) allows connections from the minion.

That error isn't Salt-specific; it's bubbling up from Windows socket code.

**Comment by tmehlinger** [comment]
Also make sure the minion can connect to the return port, 4606.

**Comment by Ch3LL** [comment]
Another thing to check is if there is an anti-virus on that box. in the past I've seen some weird issues due to anti-virus.

**Comment by wyhysj** [comment]
From minions, do telnet is successful.
The weird thing about it is when I run ssh-minion-debug.bat and use Wireshark to capture packages, there's no package on both 4505 and 4506.
My windows outbound rule is set to allow, shouldn't be a problem I think.
There's also a zabbix agent running on that minion, and connect to the same salt master/zabbix server, no problem.
Don't know why, please help me to troubleshoot
Thanks

**Comment by wyhysj** [comment]
@Ch3LL We don't install any anti-virus on minions
