### ISSUE TITLE
2016.3 regression: ini.options_present crash if ini file does not exist

### ISSUE THREAD

**Issue by Talkless** [saltstack/salt#34236]
### Description of Issue/Question

After upgrading from 2015.8.10 to 2016.3.1 on Wheezy ini.options_preset fails if target .ini file does not exist before execution. 2015.8 created file did not exist.
### Setup

ini.sls:

```
ini:    
  ini.options_present:
    - name: /etc/some_config.ini
    - sections:
        general:
          server_hostname: my.server.com
          server_port: 1234

```
### Steps to Reproduce Issue

While with 2015.8 master and minion:

```
root@test:/# salt minion test.version
minion:
    2015.8.10
root@test:/# salt minion state.highstate
minion:
----------
          ID: ini
    Function: ini.options_present
        Name: /etc/some_config.ini
      Result: True
     Comment: No anomaly detected
     Started: 10:01:45.993864
    Duration: 0.837 ms
     Changes:   

Summary for minion
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
root@test:/# cat /etc/some_config.ini 

[general]
server_hostname=my.server.com
server_port=1234

```

After removing salt-master, salt-minion, apt-get autoremove, (and deleting /etc/salt/pki/minion/minion_master.pub) and then installing using bootstrap-salt.sh -M stable 2016.3 (script from salt-bootstrap HEAD):

```
root@test:/# rm /etc/some_config.ini
root@test:/# salt minion test.version
minion:
    2016.3.1
root@test:/# salt minion state.highstate
minion:
----------
          ID: ini
    Function: ini.options_present
        Name: /etc/some_config.ini
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1723, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1650, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/ini_manage.py", line 62, in options_present
                  changes = __salt__['ini.set_option'](name, sections)
                File "/usr/lib/python2.7/dist-packages/salt/modules/ini_manage.py", line 70, in set_option
                  inifile = _Ini.get_ini_file(file_name)
                File "/usr/lib/python2.7/dist-packages/salt/modules/ini_manage.py", line 350, in get_ini_file
                  inifile.refresh()
                File "/usr/lib/python2.7/dist-packages/salt/modules/ini_manage.py", line 328, in refresh
                  inicontents = inicontents or _fopen(self.name).read()
                File "/usr/lib/python2.7/dist-packages/salt/utils/__init__.py", line 1209, in fopen
                  fhandle = open(*args, **kwargs)
              IOError: [Errno 2] No such file or directory: '/etc/some_config.ini'
     Started: 10:14:04.995673
    Duration: 2.254 ms
     Changes:   

Summary for minion
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
```
### Versions Report

```
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.3 (default, Jun 21 2016, 18:38:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 13.1.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.3

System Versions:
           dist: debian 7.11 
        machine: x86_64
        release: 3.16.0-0.bpo.4-amd64
         system: Linux
        version: debian 7.11 

```

**Comment by Talkless** [comment]
Strange, to walk-around this problem, I have tried to use file.touch state to that create file, but this doesn't help either:
```
root@test:/# salt minion state.highstate
minion:
----------
          ID: ini_file
    Function: file.touch
        Name: /etc/some_config.ini
      Result: True
     Comment: Created empty file /etc/some_config.ini
     Started: 13:39:40.874496
    Duration: 5.445 ms
     Changes:   
              ----------
              new:
                  /etc/some_config.ini
----------
          ID: ini
    Function: ini.options_present
        Name: /etc/some_config.ini
      Result: False
     Comment: Errors encountered. ini file not found
     Started: 13:39:40.884057
    Duration: 0.585 ms
     Changes:   

Summary for minion
------------
Succeeded: 1 (changed=1)
Failed:    1
------------
Total states run:     2
```

There is no exception, simply some `Errors encountered. ini file not found` error.

**Comment by Talkless** [comment]
Looks like ini_manage.py module needs at least "something" ini'sh inside file already to work with it. Successful walk-around is to create base ini file manually and then use ini.options_present:
```
{% set filepath = '/etc/some_config.ini' %}

ini_create_if_missing:
  cmd.run:
    - name: "echo [general] > {{ filepath }}" 
    - unless: "grep -q -e'[general]' {{ filepath }}" 

ini:    
  ini.options_present:
    - name: {{ filepath }}
    - sections:
        general:
          server_hostname: my.server.com
          server_port: 1234
    - require:
      - cmd: ini_create_if_missing
```

```
root@vdebian2:/srv/salt# salt minion state.highstate                                                                                                            [21/670]
minion:
----------
          ID: ini_create_if_missing
    Function: cmd.run
        Name: echo [general] > /etc/some_config.ini
      Result: True
     Comment: Command "echo [general] > /etc/some_config.ini" run
     Started: 14:22:11.537292
    Duration: 22.662 ms
     Changes:   
              ----------
              pid:
                  30689
              retcode:
                  0
              stderr:
              stdout:
----------
          ID: ini
    Function: ini.options_present
        Name: /etc/some_config.ini
      Result: True
     Comment: Changes take effect
     Started: 14:22:11.565269
    Duration: 1.243 ms
     Changes:   
              ----------
              general:
                  ----------
                  server_hostname:
                      ----------
                      after:
                          my.server.com
                      before:
                          None
                  server_port:
                      ----------
                      after:
                          1234
                      before:
                          None

Summary for minion
------------
Succeeded: 2 (changed=2)
Failed:    0
------------
Total states run:     2
```

There was  big refactoring some time ago which, I simply guess, might changed behavior: https://github.com/saltstack/salt/commit/7ac43c777ffa3ffa2289ed299a2369b32adb8146#diff-9190a03832e3b21dcf674f7e6a85f63c

I could use file.managed with template, but ini module is useful in case when application might add other keys, so file.managed would simply overwrite, while module would merge.

**Comment by Ch3LL** [comment]
@Talkless I am able to replicate this behavior and my git bisect is the same commit you have posted there:

```
7ac43c777ffa3ffa2289ed299a2369b32adb8146 is the first bad commit
commit 7ac43c777ffa3ffa2289ed299a2369b32adb8146
Author: Ageeleshwar Kandavelu <akandavelu@juniper.net>
Date:   Sun Aug 16 18:43:02 2015 +0530

    ini refactored

:040000 040000 57673a45a4c2d9542f8d23310ff670ff1606b85c c51e34bcab6402f39c80f25d5796deda6f92667a M      salt
```

thanks for posting the workaround in the meantime. We will need to get this fixed up. Thanks

**Comment by ScoreUnder** [comment]
>     Comment: Errors encountered. ini file not found

This specific one is one I've been seeing a lot recently. 

The culprit is this: https://github.com/saltstack/salt/blob/d3df37e57a495c5e0daa2378bc5a3de7d0a23934/salt/modules/ini_manage.py#L76

```python
    inifile = _Ini.get_ini_file(file_name, separator=separator)
    if not inifile:
        changes.update({'error': 'ini file not found'})
        return changes
```

`get_ini_file` does this:

```python
    @staticmethod
    def get_ini_file(file_name, separator='='):
        inifile = _Ini(file_name, separator=separator)
        inifile.refresh()
        return inifile
```

`_Ini` inherits from `_Section` which inherits from `OrderedDict`, and `OrderedDict`'s `__bool__` returns true if and only if the dict *is not empty*.

In other words, the line I highlighted above is not checking for the existence of the ini file, but for whether or not it has any contents. It reports a misleading error. On top of that, there is no reasonable explanation for the check - the returned `inifile` can never be `None` because it's being constructed unconditionally, and the behaviour on `inifile.refresh()` failure is to throw an exception (because `fopen` from `salt.utils` does).

I think it will need to be rephrased as a try/except. Even then, I think if someone is editing an ini file, perhaps a more sensible default would be to create it if it doesn't exist?

**Comment by Talkless** [comment]
> more sensible default would be to create it if it doesn't exist?

Yes, of course, so that `ini.options_present` could generate (based on Pillars, for example) *new* .ini while deploying some app.

**Comment by Talkless** [comment]
Ping. Please don't close.

**Comment by Poil** [comment]
ping

**Comment by scambra** [comment]
It hasn't been fixed in 2019.2 yet, I'm having this issue too.

**Comment by scambra** [comment]
file.touch workaround is working with 2019.2

**Comment by Talkless** [comment]
ping

**Comment by Ch3LL** [comment]
can anyone try the fix here: https://github.com/saltstack/salt/pull/58339
