### ISSUE TITLE
salt-api /minions not returning

### ISSUE THREAD

**Issue by Oro** [saltstack/salt#34242]
### Description of Issue/Question
Calling http://salt:8000/minions/ is never returning.

### Setup
```
rest_cherrypy:
  disable_ssl: True
  host: 0.0.0.0
  port: 8000
  webhook_disable_auth: True
```

One thing of note: Not all minions are returning, they are currently not running, however their key is accepted. Querying minions one-by-one is working just fine (via /minions/myminion1 )

### Steps to Reproduce Issue
See above, following log entries I can see in the master log every hour (which is when the call is taking place)
This occurs since the upgrade to 2016.3, before that (2015.8 and 2015.5) it worked fine.
```
2016-06-20 11:04:15,600 [cherrypy.error.53930000][ERROR   ][7625] [20/Jun/2016:11:04:15]  Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/cherrypy/_cptree.py", line 140, in release_serving
    req.close()
  File "/usr/lib/python2.6/site-packages/cherrypy/_cprequest.py", line 492, in close
    self.hooks.run('on_end_request')
  File "/usr/lib/python2.6/site-packages/cherrypy/_cprequest.py", line 112, in run
    raise exc
KeyError: u'bd0a04e70dc01997bc04466dd0ae04ebcc6413e1'
```
Stopping the salt-master results in 
```
Unrecoverable error in the server.
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/cherrypy/_cpwsgi.py", line 169, in trap
    return func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/cherrypy/_cpwsgi.py", line 96, in __call__
    return self.nextapp(environ, start_response)
  File "/usr/lib/python2.6/site-packages/cherrypy/_cpwsgi.py", line 379, in tail
    return self.response_class(environ, start_response, self.cpapp)
  File "/usr/lib/python2.6/site-packages/cherrypy/_cpwsgi.py", line 222, in __init__
    self.run()
  File "/usr/lib/python2.6/site-packages/cherrypy/_cpwsgi.py", line 320, in run
    request.run(meth, path, qs, rproto, headers, rfile)
  File "/usr/lib/python2.6/site-packages/cherrypy/_cprequest.py", line 603, in run
    raise cherrypy.TimeoutError()
TimeoutError
```

### Versions Report
```
[root@salt ]# salt --versions-report
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: 0.20.0
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.20.3
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.8 Final
        machine: x86_64
        release: 2.6.32-642.1.1.el6.x86_64
         system: Linux
        version: CentOS 6.8 Final
```

**Comment by Ch3LL** [comment]
@Oro if you upgrade cherrypy to 3.6.0 are you still seeing this behavior? I noticed [this](https://bitbucket.org/cherrypy/cherrypy/pull-requests/50/fix-race-condition-in-session-clean-up/diff) fix for the same error for cherrypy that looks like it was made availabe in 3.6.0 in the changelog [here](https://github.com/cherrypy/cherrypy/blob/master/CHANGES.txt#L146)

**Comment by Oro** [comment]
@Ch3LL thanks for the pointer, however this does not seem to solve the issue.
I've upgraded to cherrypy 6.0.2 via pip, however the /minions call still does not return.
```
[root@salt]# salt --versions-report
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: 6.0.2
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: 0.20.0
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.20.3
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.8 Final
        machine: x86_64
        release: 2.6.32-642.1.1.el6.x86_64
         system: Linux
        version: CentOS 6.8 Final
```


```
[root@salt]# salt-api -l debug
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/f_defaults.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/f_defaults.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/reactor.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/reactor.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt
[DEBUG   ] Missing configuration file: /root/.saltrc
[INFO    ] Processing `log_handlers.logstash`
[DEBUG   ] Adding the 'logstash' provided logging handler: '<salt.loaded.int.log_handlers.logstash_mod.DatagramLogstashHandler instance at 0x2373518>'
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] Setting up the Salt API
[DEBUG   ] Created pidfile: /var/run/salt-api.pid
[INFO    ] The salt-api is starting up
[INFO    ] Starting rest_tornado.start netapi module
[DEBUG   ] Started 'salt.loaded.int.netapi.rest_tornado.start' with pid 14915
[INFO    ] Starting rest.start netapi module
[DEBUG   ] Started 'salt.loaded.int.netapi.rest_cherrypy.start' with pid 14916
[DEBUG   ] Process Manager starting!
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[INFO    ] [24/Jun/2016:14:28:43] ENGINE Listening for SIGHUP.
[INFO    ] [24/Jun/2016:14:28:43] ENGINE Listening for SIGTERM.
[INFO    ] [24/Jun/2016:14:28:43] ENGINE Listening for SIGUSR1.
[INFO    ] [24/Jun/2016:14:28:43] ENGINE Bus STARTING
[INFO    ] [24/Jun/2016:14:28:43] ENGINE Started monitor thread '_TimeoutMonitor'.
[INFO    ] [24/Jun/2016:14:28:43] ENGINE Serving on http://0.0.0.0:8000
[INFO    ] [24/Jun/2016:14:28:43] ENGINE Bus STARTED
[INFO    ] [24/Jun/2016:14:28:46] ENGINE Started monitor thread 'Session cleanup'.
[INFO    ] xyz - - [24/Jun/2016:14:28:46] "GET /minions/ HTTP/1.1" 401 441 "" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
[INFO    ] [api_acl] Authentication not checked for user saltpad from IP xyz
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'salt_master', 'tcp://127.0.0.1:4506', 'clear')
[INFO    ] xyz - - [24/Jun/2016:14:28:50] "POST /login HTTP/1.1" 200 198 "" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'salt_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/1b/7a7a81f00db46ad6b39b37ab392d8b/.minions.p
[DEBUG   ] get_iter_returns for jid 20160624142855032808 sent to set([a whole bunch of minions]) will timeout at 14:29:00.053472
[DEBUG   ] jid 20160624142855032808 return from a whole lot
[repeat for around 200 out of 250 minions]
[DEBUG   ] Checking whether jid 20160624142855032808 is still running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'salt_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] Checking whether jid 20160624142855032808 is still running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'salt_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] Checking whether jid 20160624142855032808 is still running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'salt_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] Checking whether jid 20160624142855032808 is still running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'salt_master', 'tcp://127.0.0.1:4506', 'clear')
```

**Comment by whiteinge** [comment]
Any chance you have a second `rest_cherrypy` in your Salt config? Maybe in a file included via the `master.d` directory? I'm wondering if the server is in debug mode and getting restarted thus causing the `KeyError` when trying to look up session tokens.

What is the HTTP response when calling that endpoint? Does it 500? Does it 200 but with an empty response body? Can you paste the result from the following command?

```shell
curl -sSi http://salt:8000/minions
```

Also, it looks like you're running both Saltnado and rest_cherrypy. Is that right?

**Comment by Oro** [comment]
@whiteinge @Ch3LL both thanks for your help.

For whatever reason I now get a response from salt-api where previously I could not (even though the only thing I've changed was the upgrade of cherrypy which at the time did not help).

This might be related to some environment issues we are currently experiencing, once I can pinpoint the exact issue I'll open up another report. (I am assuming it has something to do with minions not responding or minions that where cloned and not-yet renamed, however I am yet to know the exact culprit)
Thanks again for your help!

And just for posterity's sake (to answer your questions as if it were not working)

- the master config is included in the salt config itself, but just to make sure, a recursive grep also only yielded the above config :(
- There is no HTTP response, it just keeps on loading.
- `[user@salt ~]$ curl -X GET -H "Accept: application/x-yaml" -H "X-Auth-Token: 9337bc9418d864dc5611ccde42dd3b72a14243d1" -H "Cache-Control: no-cache" "http://localhost:8000/minions/"` (there is no response, it just keeps on loading)
- Yes, both tornado and cherrypy are running (tornado is used to get a live stream of events from the salt master)
