### ISSUE TITLE
salt-cloud --query vultr failure on Ubuntu 14.04

### ISSUE THREAD

**Issue by ahammond** [saltstack/salt#34297]
### Description of Issue/Question
I have a vultr cloud provider configured on my new salt master, my old salt master and my VMs
When I query on the old salt master it works correctly. When I query on the new salt master or the VM I get the following error message. The old master is centos 6.7, the VM and new master are both Ubuntu 14.04 boxes. Configuration is identical on all 3 boxes.

### Setup
```yaml
root@salt:/etc/salt/cloud.providers.d# cat vultr.conf
vultr:
  driver: vultr
  api_key: redacted
```

### Steps to Reproduce Issue
salt-cloud --query -l debug

```
[DEBUG   ] Failed to execute 'vultr.list_nodes()' while querying for running nodes: 'int' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 2364, in run_parallel_map_providers_query
    cloud.clouds[data['fun']]()
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/vultrpy.py", line 116, in list_nodes
    nodes = list_nodes_full()
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/vultrpy.py", line 133, in list_nodes_full
    name = nodes[node]['label']
TypeError: 'int' object has no attribute '__getitem__'
```

### Versions Report

Old salt master (working)
```bash
root@salt[salt]:/etc/salt/cloud.providers.d # salt --versions-report
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: 1.2.1
       cherrypy: 3.2.2
       dateutil: 1.4.1
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: 1.3.8
         Jinja2: 2.2.1
        libgit2: Not Installed
        libnacl: 1.4.3
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: 0.6.3
          smmap: 0.8.1
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32-573.3.1.el6.x86_64
         system: Linux
        version: CentOS 6.7 Final
```

New salt master / VM (not working)
```bash
root@salt:/etc/salt/cloud.providers.d# salt --versions-report
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-88-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by cro** [comment]
@ahammond Is it possible that the new salt-master doesn't have the Vultr python library installed?

**Comment by ahammond** [comment]
old salt master (working)
```bash
ahammond@salt:~ $ pip freeze
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
apache-libcloud==0.17.0
argparse==1.3.0
async==0.6.1
Babel==0.9.4
backports.ssl-match-hostname==3.4.0.2
blessings==1.6
bpython==0.14.2
cffi==1.2.1
chardet==2.2.1
CherryPy==3.2.2
cryptography==1.0.1
curtsies==0.1.19
enum34==1.0.4
futures==3.0.3
gitdb==0.5.4
GitPython==0.3.2rc1
Glances==2.6.2
greenlet==0.4.9
idna==2.0
importlib==1.0.3
iniparse==0.3.1
ioflo==1.3.9
iotop==0.3.2
ipaddress==1.0.14
Jinja2==2.2.1
libnacl==1.4.3
logutils==0.3.3
M2Crypto==0.20.2
MarkupSafe==0.23
msgpack-python==0.4.6
ndg-httpsclient==0.4.0
ordereddict==1.2
pbr==1.8.1
psutil==3.0.1
pyasn1==0.1.8
pycparser==2.14
pycrypto==2.6.1
pycurl==7.19.0
Pygments==2.0.2
pygpgme==0.1
pyinotify==0.9.1
pyOpenSSL==0.14
python-cjson==1.0.5
python-dateutil==1.4.1
PyYAML==3.11
pyzmq==14.5.0
raet==0.6.3
requests==2.6.0
salt==2016.3.1
setproctitle==1.1.9
simplejson==3.7.3
six==1.9.0
smmap==0.8.1
stevedore==1.9.0
timelib==0.2.4
tornado==4.2.1
ujson==1.35
urlgrabber==3.9.1
urllib3==1.10.2
virtualenv==13.1.2
virtualenv-clone==0.2.6
virtualenvwrapper==4.7.1
yum-metadata-parser==1.1.2
```

New salt master (not working):
```bash
root@salt:~# pip freeze
apache-libcloud==0.15.1
apt-xapian-index==0.45
async==0.6.1
chardet==2.0.1
colorama==0.2.5
futures==3.0.5
gitdb==0.5.4
GitPython==0.3.2rc1
html5lib==0.999
inotify==0.2.6
ipaddress==1.0.16
Jinja2==2.7.2
lockfile==0.8
Mako==0.9.1
MarkupSafe==0.18
msgpack-python==0.3.0
MySQL-python==1.2.3
netaddr==0.7.10
pycrypto==2.6.1
pycurl==7.19.3
python-apt===0.9.3.5ubuntu2
python-dateutil==1.5
python-debian===0.1.21-nmu2ubuntu2
PyYAML==3.10
pyzmq==14.0.1
requests==2.10.0
salt==2016.3.1
setproctitle==1.1.10
simplejson==3.3.1
six==1.5.2
smmap==0.8.2
ssh-import-id==3.21
timelib==0.2.4
tornado==4.2.1
ujson==1.35
urllib3==1.7.1
vultr==0.1.2
```

**Comment by ahammond** [comment]
I tried uninstalling the vultr driver to see if that'd help but it didn't, so I installed it again.

**Comment by ahammond** [comment]
Upgraded apache-libcloud, still not working

```bash
ahammond@salt:~$ sudo pip install --upgrade apache-libcloud
... snip ...
Successfully installed apache-libcloud-1.0.0
```

Any other ideas?

**Comment by Ch3LL** [comment]
@ahammond I am having a hard time replicating this with the same libcloud version on ubuntu14.04., salt version 2016.3.1

My only other ideas is how did you install salt? Also maybe adding a log.debug in the list-nodes_full method like so: `log.debug('NODES QUERY: {0}'.format(nodes)` to see what output you are getting from nodes. Unless @cro has some better ideas.

**Comment by cro** [comment]
@ahammond, can you try removing the vultr library from the new salt-master
and making sure it has the same libcloud version as your working master?

**Comment by ahammond** [comment]
@cro Removed vultr and change apache-libcloud to 0.17.0, and still no vultr output.

**Comment by ahammond** [comment]
@Ch3LL I used repo.saltstack.com and then apt-get. Configuration I pulled over in tarballs from the old / working saltmaster. Using the following patch, 

```patch
diff --git a/salt/cloud/clouds/vultrpy.py b/salt/cloud/clouds/vultrpy.py
index 304e02b..ff36fac 100644
--- a/salt/cloud/clouds/vultrpy.py
+++ b/salt/cloud/clouds/vultrpy.py
@@ -129,6 +129,8 @@ def list_nodes_full(**kwargs):
     nodes = _query('server/list')
     ret = {}

+    log.debug('NODES QUERY: {0!r}'.format(nodes))
+
     for node in nodes:
         name = nodes[node]['label']
         ret[name] = nodes[node].copy()
@@ -365,6 +367,10 @@ def _query(path, method='GET', data=None, params=None, header_dict=None, decode=
     '''
     Perform a query directly against the Vultr REST API
     '''
+
+    log.trace('_query({0}, method={1}, data={2}, params={3}, header_dict={4}, decode={5})'
+              ''.format(path, method, data, params, header_dict, decode))
+
     api_key = config.get_cloud_config_value(
         'api_key',
         get_configured_provider(),
@@ -400,6 +406,9 @@ def _query(path, method='GET', data=None, params=None, header_dict=None, decode=
         hide_fields=['api_key'],
         opts=__opts__,
     )
+
+    log.debug('vultr _query result: {0!r}'.format(result))
+
     if 'dict' in result:
         return result['dict']
```

I got the following logs:

```
[TRACE   ] _query(server/list, method=GET, data=None, params=None, header_dict=None, decode=True)
[DEBUG   ] Requesting URL https://api.vultr.com/v1/server/list?api_key=XXXXXXXXXX using GET method
... snip ...
[DEBUG   ] vultr _query result: {'status': 403, 'error': 'HTTP 403: Forbidden'}
[DEBUG   ] NODES QUERY: {'status': 403, 'error': 'HTTP 403: Forbidden'}
[DEBUG   ] Failed to execute 'vultr.list_nodes()' while querying for running nodes: 'int' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 2364, in run_parallel_map_providers_query
    cloud.clouds[data['fun']]()
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/vultrpy.py", line 116, in list_nodes
    nodes = list_nodes_full()
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/vultrpy.py", line 135, in list_nodes_full
    name = nodes[node]['label']
TypeError: 'int' object has no attribute '__getitem__'
```

**Comment by ahammond** [comment]
So... Forbidden? But... identical credentials?!?!

**Comment by ahammond** [comment]
https://my.vultr.com/settings/#settingsapi has an access control section. The new salt master's IP wasn't listed there, so of course it didn't work.

**Comment by cro** [comment]
aaaah...thank you so much for reporting that.  :-)

**Comment by ahammond** [comment]
Created #34314 about making the logging for that a bit better.
