### ISSUE TITLE
file.serialize merge_if_exists fails:  'function' object has no attribute 'deserialize'

### ISSUE THREAD

**Issue by clinta** [saltstack/salt#34329]
### Setup
test.sls
```sls
/test.yaml:
  file.serialize:
    - dataset:
        test: 1
    - merge_if_exists: true
```

### Steps to Reproduce Issue
Run the above state twice. Succeeds the first time, the second time it gives this error:
```
[PROFILE ] Time (in seconds) to render 'test.sls' using 'jinja' renderer: 0.00346684455872
[DEBUG   ] Rendered data from file: test.sls:
/test.yaml:
  file.serialize:
    - dataset:
        test: 1
    - merge_if_exists: true

[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Results of YAML rendering: 
OrderedDict([('/test.yaml', OrderedDict([('file.serialize', [OrderedDict([('dataset', OrderedDict([('test', 1)]))]), OrderedDict([('merge_if_exists', True)])])]))])
[PROFILE ] Time (in seconds) to render 'test.sls' using 'yaml' renderer: 0.00530600547791
[DEBUG   ] LazyLoaded file.serialize
[INFO    ] Running state [/test.yaml] at time 08:43:31.375152
[INFO    ] Executing state file.serialize for /test.yaml
[DEBUG   ] LazyLoaded yaml.serialize
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1723, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1650, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 4596, in serialize
    existing_data = serializer.deserialize(fhr)
AttributeError: 'function' object has no attribute 'deserialize'
```

### Versions Report
```
Salt Version:
           Salt: 2016.3.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.11+ (default, Apr 17 2016, 14:00:29)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-24-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by rallytime** [comment]
@clinta Thank you for filing this report and thanks for fixing it! Love it when that happens. :) 

I just merged your fix, so I'll go ahead and close this.
