### ISSUE TITLE
git.latest fails to checkout a SHA into a new branch

### ISSUE THREAD

**Issue by terminalmage** [saltstack/salt#34367]
**NOTE: This issue has been opened based on information posted [here](https://github.com/saltstack/salt/issues/24409#issuecomment-228708638).**
### Description of Issue/Question

The `git.latest` state fails in certain circumstances in which a SHA is used as the `rev` and the state determines (incorrectly, it seems) that it already has the remote revision in the local checkout (so it does not perform a fetch).
### Setup

```
checkout-sha:
  git.latest:
    - user: {{ user }}
    - name: git@github.com:elifesciences/elife-dashboard.git
    - rev: {{ ...sha of the commit... }}
    - branch: pinned-revision
    - force_fetch: True
    - force_checkout: True
    - force_reset: True
    - target: /srv/elife-dashboard
    - require:
      - file: install-elife-dashboard
```
### Steps to Reproduce Issue

Run the above SLS (replacing jinja as necesary), and you get the following result:

```
11:17:20 [54.226.2.253] out:           ID: install-elife-dashboard
11:17:20 [54.226.2.253] out:     Function: git.latest
11:17:20 [54.226.2.253] out:         Name: ssh://git@github.com/elifesciences/elife-dashboard
11:17:20 [54.226.2.253] out:       Result: False
11:17:20 [54.226.2.253] out:      Comment: Command 'git checkout --force -b pinned-revision d2aca5060a3fda73ec98557387ecad367b0ecb8f' failed
11:17:20 [54.226.2.253] out:      Started: 10:16:23.220615
11:17:20 [54.226.2.253] out:     Duration: 3897.587 ms
11:17:20 [54.226.2.253] out:      Changes:   
```

Log information:

```
11:16:48 [54.226.2.253] out: [INFO    ] Running state [ssh://git@github.com/elifesciences/elife-dashboard] at time 10:16:23.220615
11:16:48 [54.226.2.253] out: [INFO    ] Executing state git.latest for ssh://git@github.com/elifesciences/elife-dashboard
11:16:48 [54.226.2.253] out: [INFO    ] Checking remote revision for ssh://git@github.com/elifesciences/elife-dashboard

11:16:49 [54.226.2.253] out: [INFO    ] Executing command ['git', 'ls-remote', 'ssh://git@github.com/elifesciences/elife-dashboard'] as user 'elife' in directory '/home/elife'

11:16:50 [54.226.2.253] out: [INFO    ] Executing command ['git', 'for-each-ref', '--format', '%(refname:short)', 'refs/heads/'] as user 'elife' in directory '/srv/elife-dashboard'
11:16:50 [54.226.2.253] out: [INFO    ] Executing command ['git', 'for-each-ref', '--format', '%(refname:short)', 'refs/tags/'] as user 'elife' in directory '/srv/elife-dashboard'
11:16:50 [54.226.2.253] out: [INFO    ] Checking local revision for /srv/elife-dashboard
11:16:50 [54.226.2.253] out: [INFO    ] Executing command ['git', 'rev-parse', 'HEAD'] as user 'elife' in directory '/srv/elife-dashboard'
11:16:50 [54.226.2.253] out: [INFO    ] Checking local branch for /srv/elife-dashboard
11:16:51 [54.226.2.253] out: [INFO    ] Executing command ['git', 'rev-parse', '--abbrev-ref', 'HEAD'] as user 'elife' in directory '/srv/elife-dashboard'

11:16:51 [54.226.2.253] out: [INFO    ] Executing command ['git', 'remote', '--verbose'] as user 'elife' in directory '/srv/elife-dashboard'
11:16:51 [54.226.2.253] out: [INFO    ] Executing command ['git', 'merge-base', '--is-ancestor', 'd2aca5060a3fda73ec98557387ecad367b0ecb8f', 'd2aca5060a3fda73ec98557387ecad367b0ecb8f'] as user 'elife' in directory '/srv/elife-dashboard'
11:16:51 [54.226.2.253] out: [INFO    ] Executing command ['git', 'rev-parse', '--abbrev-ref', 'develop@{upstream}'] as user 'elife' in directory '/srv/elife-dashboard'

11:16:52 [54.226.2.253] out: [INFO    ] Executing command ['git', 'status', '-z', '--porcelain'] as user 'elife' in directory '/srv/elife-dashboard'
11:16:52 [54.226.2.253] out: [INFO    ] Executing command ['git', 'checkout', '--force', '-b', 'pinned-revision', 'd2aca5060a3fda73ec98557387ecad367b0ecb8f'] as user 'elife' in directory '/srv/elife-dashboard'
11:16:52 [54.226.2.253] out: [ERROR   ] Command ['git', 'checkout', '--force', '-b', 'pinned-revision', 'd2aca5060a3fda73ec98557387ecad367b0ecb8f'] failed with return code: 128
11:16:52 [54.226.2.253] out: [ERROR   ] stdout: fatal: reference is not a tree: d2aca5060a3fda73ec98557387ecad367b0ecb8f
11:16:52 [54.226.2.253] out: [ERROR   ] retcode: 128
11:16:52 [54.226.2.253] out: [ERROR   ] Unexpected exception in git.latest state
11:16:52 [54.226.2.253] out: Traceback (most recent call last):
11:16:52 [54.226.2.253] out:   File "/usr/lib/python2.7/dist-packages/salt/states/git.py", line 1159, in latest
11:16:52 [54.226.2.253] out:     user=user)
11:16:52 [54.226.2.253] out:   File "/usr/lib/python2.7/dist-packages/salt/modules/git.py", line 664, in checkout
11:16:52 [54.226.2.253] out:     redirect_stderr=True)['stdout']
11:16:52 [54.226.2.253] out:   File "/usr/lib/python2.7/dist-packages/salt/modules/git.py", line 288, in _git_run
11:16:52 [54.226.2.253] out:     raise CommandExecutionError(msg)
11:16:52 [54.226.2.253] out: CommandExecutionError: Command 'git checkout --force -b pinned-revision d2aca5060a3fda73ec98557387ecad367b0ecb8f' failed
11:16:52 [54.226.2.253] out: [ERROR   ] Command 'git checkout --force -b pinned-revision d2aca5060a3fda73ec98557387ecad367b0ecb8f' failed
```
### Versions Report

```
elife@develop--ci:/srv/elife-dashboard$ salt-minion --versions-report
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-36-generic
         system: Ubuntu 14.04 trusty
```

**Comment by terminalmage** [comment]
I finally got a chance to give this a look. I don't think this is a bug, to be honest. The clue here is right there in the log message you provided:

d2aca5060a3fda73ec98557387ecad367b0ecb8f

```
11:16:52 [54.226.2.253] out: [ERROR   ] Command ['git', 'checkout', '--force', '-b', 'pinned-revision', 'd2aca5060a3fda73ec98557387ecad367b0ecb8f'] failed with
return code: 128
11:16:52 [54.226.2.253] out: [ERROR   ] stdout: fatal: reference is not a tree: d2aca5060a3fda73ec98557387ecad367b0ecb8f
11:16:52 [54.226.2.253] out: [ERROR   ] retcode: 128
```

Indeed, when I clone your repo, this SHA is not present:

```
% git clone https://github.com/elifesciences/elife-dashboard
Cloning into 'elife-dashboard'...
remote: Counting objects: 638, done.
remote: Total 638 (delta 0), reused 0 (delta 0), pack-reused 638
Receiving objects: 100% (638/638), 5.64 MiB | 1.09 MiB/s, done.
Resolving deltas: 100% (227/227), done.
% cd elife-dashboard
% git show d2aca5060a3fda73ec98557387ecad367b0ecb8f
fatal: bad object d2aca5060a3fda73ec98557387ecad367b0ecb8f
```

Note that this happened after the initial clone, so there is no reason for an object to be missing.

It looks like, if anything, d2aca5060a3fda73ec98557387ecad367b0ecb8f refers to commit that was never pushed to the remote repository.
