### ISSUE TITLE
inotify beacon returns minion id in data dictionary

### ISSUE THREAD

**Issue by Da-Juan** [saltstack/salt#34391]
### Description of Issue/Question
I'm trying to setup a simple beacon/reactor system that restarts a service on the minion when a file is modified.

### Setup
Here is my beacon:
```
beacons:
  inotify:
    /path/to/file:
      mask:
        - modify
```

And my reactor:
```
reload_service:
  local.service.reload:
    - tgt: {{ data['id'] }}
    - arg:
      - service
```

### Steps to Reproduce Issue
When I use the setup above, I get a rendering error in my salt master log:
```
2016-06-30 17:51:31,537 [salt.utils.reactor][ERROR   ][16396] Failed to render "/srv/reactor/inotify.sls": 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/reactor.py", line 68, in render_reaction
    data=data)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 304, in render_template
    template, self.rend, self.opts['renderer'], **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/template.py", line 95, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/renderers/jinja.py", line 381, in render
    **kws)
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 178, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 384, in render_jinja_tmpl
    buf=tmplstr)
SaltRenderError: Jinja variable 'dict object' has no attribute 'id'
```
Using `salt-run state.event pretty=true` to watch the event bus I get this:
```
salt/beacon/salt-minion1/inotify//path/to/file	{
    "_stamp": "2016-06-30T16:05:32.667209", 
    "data": {
        "change": "IN_MODIFY", 
        "id": "salt-minion1", 
        "path": "/path/to/file"
    }, 
    "tag": "salt/beacon/salt-minion1/inotify//path/to/file"
}
```
I found a workaround using `{{ data['data']['id'] }}` in my reactor but it would be simpler if all the events return data in the same format.

### Versions Report
```
Salt Version:
           Salt: 2016.3.1
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: 3.5.0
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.5 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.5 
```

Thanks for your help :)

**Comment by Ch3LL** [comment]
I believe this is might be a duplicate of #26509  Just to ensure its a duplicate according to that issue you will be seeing this if you have a master/syndic topology. Is that correct?

**Comment by Da-Juan** [comment]
My bad, I tried to use a beacon with the configuration examples from the reactor documentation page.
After some testing and re-reading the beacon documentation the minion id is in fact in `data['data']['id']`

Maybe it would be simpler if events and beacons use the same answer format but that's an other subject.
