### ISSUE TITLE
Minion error in schedule.py

### ISSUE THREAD

**Issue by jwhite530** [saltstack/salt#34399]
### Description of Issue/Question

One of my minion's is throwing an exception from schedule.py.  At least one state in the minion's schedule is not running as a result of this.  I updated to salt-minion-2016.3.1-1.el7.noarch from SaltStack's RPM repo but there's still an unhandled exception in schedule.py.

```
Jun 30 10:25:33 xdmod-p1n01.kamiak.wsu.edu systemd[1]: Starting The Salt Minion...
Jun 30 10:25:34 xdmod-p1n01.kamiak.wsu.edu salt-minion[17770]: [WARNING ] IMPORTANT: Do not use md5 hashing algorithm! Please set "hash_type" to sha256 in Salt Minion config!
Jun 30 10:25:36 xdmod-p1n01.kamiak.wsu.edu salt-minion[17770]: [ERROR   ] Unhandled exception running state.sls
Jun 30 10:25:36 xdmod-p1n01.kamiak.wsu.edu salt-minion[17770]: Traceback (most recent call last):
Jun 30 10:25:36 xdmod-p1n01.kamiak.wsu.edu salt-minion[17770]: File "/usr/lib/python2.7/site-packages/salt/utils/schedule.py", line 718, in handle_func
Jun 30 10:25:36 xdmod-p1n01.kamiak.wsu.edu salt-minion[17770]: ret['return'] = self.functions[func](*args, **kwargs)
Jun 30 10:25:36 xdmod-p1n01.kamiak.wsu.edu salt-minion[17770]: TypeError: sls() takes at most 7 arguments (18 given)
Jun 30 10:25:36 xdmod-p1n01.kamiak.wsu.edu salt-minion[17770]: [ERROR   ] Unhandled exception running state.sls
Jun 30 10:25:36 xdmod-p1n01.kamiak.wsu.edu salt-minion[17770]: Traceback (most recent call last):
Jun 30 10:25:36 xdmod-p1n01.kamiak.wsu.edu salt-minion[17770]: File "/usr/lib/python2.7/site-packages/salt/utils/schedule.py", line 718, in handle_func
Jun 30 10:25:36 xdmod-p1n01.kamiak.wsu.edu salt-minion[17770]: ret['return'] = self.functions[func](*args, **kwargs)
Jun 30 10:25:36 xdmod-p1n01.kamiak.wsu.edu salt-minion[17770]: TypeError: sls() takes at most 7 arguments (18 given)
Jun 30 10:25:37 xdmod-p1n01.kamiak.wsu.edu salt-minion[17770]: [ERROR   ] Exception occurred while handling stream: [Errno 0] Success
Jun 30 10:25:38 xdmod-p1n01.kamiak.wsu.edu salt-minion[17770]: [WARNING ] /usr/lib/python2.7/site-packages/salt/states/pkgrepo.py:315: DeprecationWarning: The `enabled` argument has been deprecated in favor of `disabled`.
```
### Setup

The effected minions pillar with schedule:

```
# salt-call pillar.items                                                 
local:
    ----------
    schedule:
        ----------
        highstate:
            ----------
            function:
                state.apply
            hours:
                6
        slurm:
            ----------
            args:
                states/slurm
            function:
                state.sls
            hours:
                6
        xdmod:
            ----------
            args:
                states/xdmod
            function:
                state.sls
            hours:
                12
```

The SLS which only this one minion runs:

```
# salt-call state.show_sls states/xdmod
local:
    ----------
    ingest_slurm:
        ----------
        __env__:
            base
        __sls__:
            states/xdmod
        cmd:
            |_
              ----------
              name:
                  xdmod-slurm-helper -r kamiak
            - run
            |_
              ----------
              order:
                  10000
    reload_httpd:
        ----------
        __env__:
            base
        __sls__:
            states/xdmod
        service:
            |_
              ----------
              name:
                  httpd
            |_
              ----------
              reload:
                  True
            |_
              ----------
              watch:
                  |_
                    ----------
                    cmd:
                        run_investor
            - running
            |_
              ----------
              order:
                  10002
    run_investor:
        ----------
        __env__:
            base
        __sls__:
            states/xdmod
        cmd:
            |_
              ----------
              name:
                  xdmod-ingestor
            |_
              ----------
              onchanges:
                  |_
                    ----------
                    cmd:
                        ingest_slurm
            - run
            |_
              ----------
              order:
                  10001
```

... which works when ran manually:

```
# salt-call state.sls states/xdmod                                              
local:
----------
          ID: ingest_slurm
    Function: cmd.run
        Name: xdmod-slurm-helper -r kamiak
      Result: True
     Comment: Command "xdmod-slurm-helper -r kamiak" run
     Started: 12:44:04.136909
    Duration: 576.377 ms
     Changes:   
              ----------
              pid:
                  18550
              retcode:
                  0
              stderr:
              stdout:
                  (removed)
----------
          ID: run_investor
    Function: cmd.run
        Name: xdmod-ingestor
      Result: True
     Comment: Command "xdmod-ingestor" run
     Started: 12:44:04.714484
    Duration: 1990.726 ms
     Changes:   
              ----------
              pid:
                  18559
              retcode:
                  0
              stderr:
              stdout:
                  (removed)
----------
          ID: reload_httpd
    Function: service.running
        Name: httpd
      Result: True
     Comment: Service reloaded
     Started: 12:44:07.097822
    Duration: 261.159 ms
     Changes:   
              ----------
              httpd:
                  True

Summary for local
------------
Succeeded: 3 (changed=3)
Failed:    0
------------
Total states run:     3
```
### Versions Report

Minion:

```
# salt-call --versions-report
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.22.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

Master:

```
# salt --versions-report
Salt Version:
           Salt: 2016.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.4.5.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

**Comment by Ch3LL** [comment]
@jwhite530 looks like your master is a lower version then your minion. Would you mind attempting to upgrade your master and seeing if you still see this behavior?

Also it looks like at your pillar you also have another state file scheduled and a highstate. Are you sure there isn't another sls file causing some issues?

And would you mind posting output from `salt 'minion' schedule.list`

Also are you seeing this on other minions or just the one? thanks in advanced for any clarifying information!

**Comment by jwhite530** [comment]
> Would you mind attempting to upgrade your master and seeing if you still see this behavior?

Done, the issue persists with the same error.

> Are you sure there isn't another sls file causing some issues?

The others are ran by every one of my ~80 minions.  This one state is only ran by this one minion who is the only one having the problem.

> ... would you mind posting output from salt 'minion' schedule.list

The frequency changed (hours to minutes) so I can see the issue logged faster after making changes like the above update.  Otherwise, here ya go:

```
# salt xdmod-p1n01 schedule.list                                                                 
xdmod-p1n01:
    schedule:
      highstate:
        enabled: true
        function: state.apply
        hours: 6
        name: highstate
      slurm:
        args: states/slurm
        enabled: true
        function: state.sls
        hours: 6
        name: slurm
      xdmod:
        args: states/xdmod
        enabled: true
        function: state.sls
        jid_include: true
        maxrunning: 1
        minutes: 12
        name: xdmod
```
