### ISSUE TITLE
salt-cloud provisioning of instances fails

### ISSUE THREAD

**Issue by damaex17** [saltstack/salt#34417]
### Setup

We moved out salt-master to vpc and since then we have issues with provisioning instances.
The error on the freshly provisioned minion:
```
2016-07-01 12:05:46,490 [salt.cli.daemons ][INFO    ][4257] The salt minion is starting up
2016-07-01 12:05:46,490 [salt.minion      ][INFO    ][4257] Minion is starting as user 'root'
2016-07-01 12:05:46,491 [salt.minion      ][INFO    ][4257] Starting pub socket on ipc:///var/run/salt/minion/minion_event_d65e78fb9f_pub.ipc
2016-07-01 12:05:46,491 [salt.minion      ][INFO    ][4257] Starting pull socket on ipc:///var/run/salt/minion/minion_event_d65e78fb9f_pull.ipc
2016-07-01 12:06:46,556 [salt.payload     ][INFO    ][4257] SaltReqTimeoutError: after 60 seconds. (Try 1 of 3)
2016-07-01 12:07:46,617 [salt.payload     ][INFO    ][4257] SaltReqTimeoutError: after 60 seconds. (Try 2 of 3)
2016-07-01 12:08:46,677 [salt.payload     ][INFO    ][4257] SaltReqTimeoutError: after 60 seconds. (Try 3 of 3)
2016-07-01 12:08:46,679 [salt.minion      ][INFO    ][4257] fire_master failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1031, in _fire_master
    result = channel.send(load, timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/salt/transport/__init__.py", line 314, in send
    return self._crypted_transfer(load, tries, timeout)
  File "/usr/lib/python2.7/dist-packages/salt/transport/__init__.py", line 302, in _crypted_transfer
    return _do_transfer()
  File "/usr/lib/python2.7/dist-packages/salt/transport/__init__.py", line 293, in _do_transfer
    timeout)
  File "/usr/lib/python2.7/dist-packages/salt/payload.py", line 291, in send
    'SaltReqTimeoutError: after {0} seconds, ran {1} tries'.format(timeout * tried, tried)
SaltReqTimeoutError: SaltReqTimeoutError: after 180 seconds, ran 3 tries

2016-07-01 12:08:46,679 [salt.minion      ][INFO    ][4257] Minion is ready to receive requests!
2016-07-01 12:08:46,679 [salt.utils.schedule][INFO    ][4257] Running scheduled job: __mine_interval
2016-07-01 12:08:46,684 [salt.minion      ][INFO    ][4257] User root Executing command state.highstate with jid 20160701120609055345
2016-07-01 12:08:46,690 [salt.minion      ][INFO    ][5127] Starting a new job with PID 5127
2016-07-01 12:09:46,770 [salt.payload     ][INFO    ][5127] SaltReqTimeoutError: after 60 seconds. (Try 1 of 3)
2016-07-01 12:10:46,831 [salt.payload     ][INFO    ][5127] SaltReqTimeoutError: after 60 seconds. (Try 2 of 3)
```
error on the master:
```

2016-07-01 12:06:08,979 [salt.utils.event ][DEBUG   ][23487] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
2016-07-01 12:06:08,980 [salt.utils.event ][DEBUG   ][23487] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
2016-07-01 12:06:08,980 [salt.utils.event ][DEBUG   ][23487] Sending event - data = {'profile': 'peptrack-dev-virginia-vpc-2', '_stamp': '2016-07-01T12:06:08.980071', 'name': 'peptrack-dev-virginia', 'instance_id': 'i-c7b63e41', 'provider': 'ec2-test-us-east-1:ec2', 'event': 'created instance'}
2016-07-01 12:06:09,031 [salt.utils.aws   ][DEBUG   ][23487] Using AWS endpoint: ec2.us-east-1.amazonaws.com
2016-07-01 12:06:09,032 [salt.utils.aws   ][DEBUG   ][23487] AWS Request: https://ec2.us-east-1.amazonaws.com/?Action=DescribeInstances&InstanceId.1=i-c7b63e41&Version=2014-10-01
2016-07-01 12:06:09,034 [urllib3.connectionpool][INFO    ][23487] Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
2016-07-01 12:06:09,053 [urllib3.connectionpool][DEBUG   ][23487] Setting read timeout to None
2016-07-01 12:06:09,056 [salt.master      ][INFO    ][11960] User root Published command state.highstate with jid 20160701120609055345
2016-07-01 12:06:09,195 [urllib3.connectionpool][DEBUG   ][23487] "GET /?Action=DescribeInstances&InstanceId.1=i-c7b63e41&Version=2014-10-01 HTTP/1.1" 200 None
2016-07-01 12:06:09,196 [salt.utils.aws   ][DEBUG   ][23487] AWS Response Status Code: 200
2016-07-01 12:06:09,288 [salt.utils.lazy  ][DEBUG   ][23440] LazyLoaded nested.output
2016-07-01 12:08:48,865 [salt.utils.job   ][INFO    ][11960] Got return from peptrack-dev-virginia for job 20160701120848864000
```

### Steps to Reproduce Issue

`/usr/bin/salt-cloud -m /etc/salt/cloud.maps.d/test.yml --parallel -l debug`

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

salt-master

```
Salt Version:
           Salt: 2015.8.10
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 2.5.3
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-66-generic
         system: Ubuntu 14.04 trusty

```

salt-minion:
```
root@ip-10-0-2-227:~# dpkg -l | grep salt
ii  salt-common                      2015.5.10+ds-1                   all          shared libraries that salt requires for all packages
ii  salt-minion                      2015.5.10+ds-1                   all          client package for salt, the distributed remote execution system
```

**Comment by Ch3LL** [comment]
@damaex17 seems like there might be some sort of firewall between yoru master and minion. Can you telnet to 4505 and 4506 from your minion to your master? Or possibly some network latency
