### ISSUE TITLE
Is OpenSUSE 11.4 as a minion for salt-ssh still supported?

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#34419]
Today, we upgraded from salt-ssh 2015.8.3 to 2016.3.1.

For our openSUSE 11.4 hosts, we incur the following issue:

```
salt:/srv # salt-ssh os114 cmd.run 'echo 12'
ci114:
    ----------
    retcode:
        1
    stderr:
        Traceback (most recent call last):
          File "/var/tmp/.root_dcdf8c_salt/salt-call", line 15, in <module>
            salt_call()
          File "/var/tmp/.root_dcdf8c_salt/py2/salt/scripts.py", line 345, in salt_call
            client.run()
          File "/var/tmp/.root_dcdf8c_salt/py2/salt/cli/call.py", line 48, in run
            caller = salt.cli.caller.Caller.factory(self.config)
          File "/var/tmp/.root_dcdf8c_salt/py2/salt/cli/caller.py", line 79, in factory
            return ZeroMQCaller(opts, **kwargs)
          File "/var/tmp/.root_dcdf8c_salt/py2/salt/cli/caller.py", line 274, in __init__
            super(ZeroMQCaller, self).__init__(opts)
          File "/var/tmp/.root_dcdf8c_salt/py2/salt/cli/caller.py", line 102, in __init__
            self.minion = salt.minion.SMinion(opts)
          File "/var/tmp/.root_dcdf8c_salt/py2/salt/minion.py", line 582, in __init__
            opts['grains'] = salt.loader.grains(opts)
          File "/var/tmp/.root_dcdf8c_salt/py2/salt/loader.py", line 703, in grains
            ret = fun()
          File "/var/tmp/.root_dcdf8c_salt/py2/salt/grains/core.py", line 1286, in os_data
            if not grains['lsb_distrib_codename']:
        KeyError: 'lsb_distrib_codename'
    stdout:
salt:/srv # salt-ssh os114 test.ping
ci114:
    ----------
    retcode:
        1
    stderr:
        Traceback (most recent call last):
          File "/var/tmp/.root_dcdf8c_salt/salt-call", line 15, in <module>
            salt_call()
          File "/var/tmp/.root_dcdf8c_salt/py2/salt/scripts.py", line 345, in salt_call
            client.run()
          File "/var/tmp/.root_dcdf8c_salt/py2/salt/cli/call.py", line 48, in run
            caller = salt.cli.caller.Caller.factory(self.config)
          File "/var/tmp/.root_dcdf8c_salt/py2/salt/cli/caller.py", line 79, in factory
            return ZeroMQCaller(opts, **kwargs)
          File "/var/tmp/.root_dcdf8c_salt/py2/salt/cli/caller.py", line 274, in __init__
            super(ZeroMQCaller, self).__init__(opts)
          File "/var/tmp/.root_dcdf8c_salt/py2/salt/cli/caller.py", line 102, in __init__
            self.minion = salt.minion.SMinion(opts)
          File "/var/tmp/.root_dcdf8c_salt/py2/salt/minion.py", line 582, in __init__
            opts['grains'] = salt.loader.grains(opts)
          File "/var/tmp/.root_dcdf8c_salt/py2/salt/loader.py", line 703, in grains
            ret = fun()
          File "/var/tmp/.root_dcdf8c_salt/py2/salt/grains/core.py", line 1286, in os_data
            if not grains['lsb_distrib_codename']:
        KeyError: 'lsb_distrib_codename'
    stdout:

salt:/srv # salt-ssh os114 grains.ls
[hangs forever]
```
### Versions Report

```
salt:/srv # salt-ssh --versions-report
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.1
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.21.0
        libnacl: Not Installed
       M2Crypto: 0.22
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: 0.21.2
         Python: 2.7.3 (default, Apr 14 2012, 08:58:41) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.2

System Versions:
           dist: SuSE 12.3 x86_64
        machine: x86_64
        release: 3.7.10-1.40-desktop
         system: Linux
        version: openSUSE  12.3 x86_64
```

**Comment by Ch3LL** [comment]
@srkunze I don't have access to an opensuse11 box. would you mind trying to change that line to `if not grains.get('lsb_distrib_codename'):` and seeing if that works?

**Comment by srkunze** [comment]
@Ch3LL Sure. Seems to work for now. :)

Another issue related hereto is the changing of the 'osrelease' string. We could fix it more or less easily. Interestingly, it changed from "114 SP" to "114".

**Comment by srkunze** [comment]
@Ch3LL Some updates here? We recently upgraded to 2016.3.2 and get now the following error:

```
salt:/srv # salt-ssh ci114 test.ping
ci114:
    ----------
    retcode:
        1
    stderr:
        Traceback (most recent call last):
          File "/var/tmp/.root_dcdf8c_salt/salt-call", line 15, in <module>
            salt_call()
          File "/var/tmp/.root_dcdf8c_salt/py2/salt/scripts.py", line 339, in salt_call
            import salt.cli.call
          File "/var/tmp/.root_dcdf8c_salt/py2/salt/cli/call.py", line 6, in <module>
            from salt.utils import parsers
          File "/var/tmp/.root_dcdf8c_salt/py2/salt/utils/parsers.py", line 28, in <module>
            import salt.config as config
          File "/var/tmp/.root_dcdf8c_salt/py2/salt/config/__init__.py", line 93, in <module>
            _DFLT_IPC_WBUFFER = _gather_buffer_space() * .5
          File "/var/tmp/.root_dcdf8c_salt/py2/salt/config/__init__.py", line 82, in _gather_buffer_space
            total_mem = psutil.virtual_memory().total
        AttributeError: 'module' object has no attribute 'virtual_memory'
    stdout:

```
