### ISSUE TITLE
WinMinion pkg.available_version

### ISSUE THREAD

**Issue by AvinashDeluxeVR** [saltstack/salt#34469]
Hello all,

I am trying to follow the [Windows Guide](https://docs.saltstack.com/en/latest/topics/windows/windows-package-manager.html)

My setup seems correct so far:

```
asunnasy@ubuntu:~$ sudo salt-key -L
Accepted Keys:
SPARK-29
Denied Keys:
Unaccepted Keys:
Rejected Keys:

asunnasy@ubuntu:~$ sudo salt -G 'os:Windows' test.ping
SPARK-29:
    True

asunnasy@ubuntu:~$ sudo salt '*' cmd.run 'dir'
SPARK-29:
     Volume in drive C is System
     Volume Serial Number is 84DC-3699
    
     Directory of C:\WINDOWS\system32\config\systemprofile
    
    07/10/2015  04:04 AM    <DIR>          .
    07/10/2015  04:04 AM    <DIR>          ..
    07/10/2015  04:04 AM    <DIR>          AppData
                   0 File(s)              0 bytes
                   3 Dir(s)  36,179,550,208 bytes free
```

When I run

`sudo salt winminion pkg.available_version firefox`

I get 

`No minions matched the target. No command was sent, no jid was assigned.`

When I run

`salt -G 'os:windows' pkg.list_pkgs`

I get a list of already installed packages.

I see` firefox.sls, firefox-esr*.sls, `and` firefox_x86.sls` in `/srv/salt/win/repo/salt-winrepo.git`

Any help would be greatly appreciated!

Thanks,

Avinash.

```
Salt Master (Ubuntu Server):
asunnasy@ubuntu:~$ salt --versions-report
                  Salt: 2015.5.3
                Python: 2.7.10 (default, Oct 14 2015, 16:09:02)
                Jinja2: 2.8
              M2Crypto: 0.21.1
        msgpack-python: 0.4.2
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.11
                 ioflo: Not Installed
                 PyZMQ: 14.4.1
                  RAET: Not Installed
                   ZMQ: 4.0.5
                  Mako: Not Installed
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1

```

```
Salt Minion (Windows 10)
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: 1.6.0
       cherrypy: 5.3.0
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 2.0.2
          ioflo: 1.5.3
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.3
            ZMQ: 4.1.2

System Versions:
           dist:
        machine: AMD64
        release: 10
         system: Windows
        version: 10 10.0.10240  Multiprocessor Free```

**Comment by Ch3LL** [comment]
@AvinashDeluxeVR you just need to change the name of your target in this command `sudo salt winminion pkg.available_version firefox` to the name of your own windows minion which looks like it is `SPARK-29` so the command should be  `sudo salt 'SPARK-29' pkg.available_version firefox`

Does that help resolve the error?

**Comment by AvinashDeluxeVR** [comment]
Hi there, 

That does resolve that error I listed but also displays the following error:

```
asunnasy@ubuntu:~$ sudo salt 'SPARK-29' pkg.available_version firefox
[sudo] password for asunnasy: 
SPARK-29:
    The minion function caused an exception: Traceback (most recent call last):
      File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1318, in _thread_return
        return_data = executor.execute()
      File "c:\salt\bin\lib\site-packages\salt\executors\direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "c:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 97, in latest_version
        latest_available = _get_latest_pkg_version(pkg_info)
      File "c:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 1099, in _get_latest_pkg_version
        return sorted(pkginfo, cmp=_reverse_cmp_pkg_versions).pop()
    IndexError: pop from empty list
```

I will look into this issue further. Perhaps there is already a fix on Git.

I also tried

```
asunnasy@ubuntu:~$ sudo salt 'SPARK-29' pkg.install 'firefox'
SPARK-29:
    ----------
    firefox:
        Unable to locate package firefox
```

Again, I will look into these issues myself before asking more questions. 

Thanks for your help!

Avinash.

**Comment by AvinashDeluxeVR** [comment]
So the main problem was that the minion and the master were on different versions. 

the latest version for ubuntu is 2015.5.3 and the latest version for windows is 2016.3.1

I just installed the latest versions on the installations pages:

[Windows](https://docs.saltstack.com/en/latest/topics/installation/windows.html)
[Ubuntu](https://docs.saltstack.com/en/latest/topics/installation/ubuntu.html)

Ideally these pages should tell new users that they require their minion version and their master version to match.

Thanks,

Avinash.
