### ISSUE TITLE
rabbitmq_cluster.join ingores runas keyword

### ISSUE THREAD

**Issue by L4rS6** [saltstack/salt#34477]
### Description of Issue/Question
rabbitmq_cluster.join and rabbitmq_cluster.joined ignore the keyword runas.

### Setup
rabbitmq.sls:
```
rabbitmq_cluster:
  rabbitmq_cluster.join:
    - name: rabbit@node01
    - host: node01
    - runas: rabbitmq
```

### Steps to Reproduce Issue
```
[INFO    ] Executing command ['rabbitmqctl', 'cluster_status'] as user 'root' in directory '/root'
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/salt/state.py", line 1723, in call
    **cdata['kwargs'])
  File "/usr/local/lib/python2.7/site-packages/salt/loader.py", line 1650, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/salt/states/rabbitmq_cluster.py", line 51, in joined
    status = __salt__['rabbitmq.cluster_status']()
  File "/usr/local/lib/python2.7/site-packages/salt/modules/rabbitmq.py", line 509, in cluster_status
    python_shell=False)
  File "/usr/local/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 852, in run
    bg=bg)
  File "/usr/local/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 475, in _run
    'reason: {2}'.format(cmd, kwargs, exc)
CommandExecutionError: Unable to run command '['rabbitmqctl', 'cluster_status']' with the context
...

```

### Versions Report
```
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: 1.5.0
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-87-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by Ch3LL** [comment]
@L4rS6 I believe this is related to this line [here](https://github.com/saltstack/salt/blob/develop/salt/states/rabbitmq_cluster.py#L51)

It does not include the runas kwarg. If you were to replace that line with `status = __salt__['rabbitmq.cluster_status'](runas=runas)` does that work?

**Comment by L4rS6** [comment]
@Ch3LL Thank you, it's working now.
