### ISSUE TITLE
transport/tcp TypeError: 'int' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by ahammond** [saltstack/salt#34491]
### Description of Issue/Question

I  was seeing this on our salt-master this morning.

```
ahammond@salt:~$ sudo salt hss4 test.ping
[ERROR   ] Exception parsing response
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/transport/tcp.py", line 710, in _stream_return
    header = framed_msg['head']
TypeError: 'int' object has no attribute '__getitem__'
'int' object has no attribute '__getitem__'
```

Restarted salt-master and problem went away.

`/var/log/salt/master` log contains a bunch of this:

```
2016-07-06 10:15:16,136 [salt.transport.tcp][ERROR   ][10279] Exception parsing response
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/transport/tcp.py", line 710, in _stream_return
    header = framed_msg['head']
TypeError: 'int' object has no attribute '__getitem__'
2016-07-06 10:15:40,956 [tornado.application][ERROR   ][11925] Exception in callback <functools.partial object at 0
x7f00ad01c890>
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/ioloop.py", line 592, in _run_callback
    ret = callback()
  File "/usr/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/tornado/ioloop.py", line 598, in <lambda>
    self.add_future(ret, lambda f: f.result())
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 230, in wrapper
    yielded = next(result)
  File "/usr/lib/python2.7/dist-packages/salt/transport/tcp.py", line 506, in handle_message
    self._auth(payload['load']), header=header))
  File "/usr/lib/python2.7/dist-packages/salt/transport/mixins/auth.py", line 464, in _auth
    self.event.fire_event(eload, salt.utils.event.tagify(prefix='auth'))
  File "/usr/lib/python2.7/dist-packages/salt/utils/event.py", line 662, in fire_event
    self.io_loop.run_sync(lambda: self.pusher.send(msg))
  File "/usr/lib/python2.7/dist-packages/tornado/ioloop.py", line 445, in run_sync
    return future_cell[0].result()
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.7/dist-packages/salt/transport/ipc.py", line 389, in send
    yield self.stream.write(pack)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
StreamClosedError
```

Scrolling up the logfile to the first error messages give me this:

```

2016-07-06 09:51:12,519 [salt.client.mixins][INFO    ][11905] Runner completed: 20160706095051785893
2016-07-06 10:09:07,018 [salt.master      ][INFO    ][11942] User sudo_ahammond Published command cp.recv with jid 20160706100906235979
2016-07-06 10:09:13,074 [salt.master      ][INFO    ][11924] User sudo_ahammond Published command saltutil.find_job with jid 20160706100913064581
2016-07-06 10:09:21,214 [tornado.application][ERROR   ][11933] Exception in callback <functools.partial object at 0x7f00ad213c00>
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/ioloop.py", line 592, in _run_callback
    ret = callback()
  File "/usr/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/tornado/ioloop.py", line 598, in <lambda>
    self.add_future(ret, lambda f: f.result())
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 879, in run
    yielded = self.gen.send(value)
  File "/usr/lib/python2.7/dist-packages/salt/transport/tcp.py", line 523, in handle_message
    stream.write(salt.transport.frame.frame_msg(self.crypticle.dumps(ret), header=header))
  File "/usr/lib/python2.7/dist-packages/tornado/iostream.py", line 368, in write
    self._check_closed()
  File "/usr/lib/python2.7/dist-packages/tornado/iostream.py", line 878, in _check_closed
    raise StreamClosedError("Stream is closed")
StreamClosedError: Stream is closed
```

This was immediately after I ran salt-cp with a target that should have hit about 400 machines, but only returned on 4.

### Setup
We're running tcp transport, obviously. Beyond that I don't really know what's relevant to this.

### Steps to Reproduce Issue
No idea. Heisenbug? I figured I'd open the issue in case it happened again and then put some more effort into troubleshooting it.

### Versions Report
```bash
ahammond@salt:~$ sudo salt --versions-report
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: 1.7.0
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-88-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by ahammond** [comment]
This was followed by our salt-master's hardware imploding. So... maybe not a software issue.
