### ISSUE TITLE
Error with hiera ext_pillar

### ISSUE THREAD

**Issue by fedusia** [saltstack/salt#34501]
### Description of Issue/Question

Fresh install from vagrant up. When i add hiera as ext_pillar i see in logs of salt-master error:

```
2016-07-06 22:16:04,829 [salt.master      ][ERROR   ][20878] Error in function _pillar:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 1540, in run_func
    ret = getattr(self, func)(load)
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 1276, in _pillar
    data = pillar.compile_pillar(pillar_dirs=pillar_dirs)
  File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 806, in compile_pillar
    pillar, pillar_dirs, errors=errors)
  File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 782, in ext_pillar
    self.opts.get('pillar_merge_lists', False))
  File "/usr/lib/python2.7/dist-packages/salt/utils/dictupdate.py", line 108, in merge
    merged = merge_recurse(obj_a, obj_b, merge_lists)
  File "/usr/lib/python2.7/dist-packages/salt/utils/dictupdate.py", line 84, in merge_recurse
    return update(copied, obj_b, merge_lists=merge_lists)
  File "/usr/lib/python2.7/dist-packages/salt/utils/dictupdate.py", line 38, in update
    raise TypeError('Cannot update using non-dict types in dictupdate.update()')
TypeError: Cannot update using non-dict types in dictupdate.update()
```
### Setup

```
root@saltmaster:/srv# cat /etc/salt/master | egrep -v '(^$|^#)'
interface: 192.168.50.10
ext_pillar:
  - hiera: /srv/hiera.yaml 
```

```
root@saltmaster:/srv# cat /srv/hiera.yaml 
:backends:
  - yaml
:yaml:
  :datadir: '/srv/hiera'
:hierarchy:
  - "hiera/test"
  - "hiera/test2"
```

```
Dirs tree:
root@saltmaster:/srv# tree /srv/hiera
/srv/hiera
├── hiera
│   ├── test2.yaml
│   └── test.yaml
└── qwerty
```

```
root@saltmaster:/srv# cat /srv/hiera/hiera/test2.yaml 
test2:
  123: 123
```
### Steps to Reproduce Issue

```
root@saltminion1:~# salt-call -l debug pillar.items
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[DEBUG   ] Connecting to master. Attempt 1 of 1
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'minion1', 'tcp://192.168.50.10:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (2412)
[DEBUG   ] Setting zmq_reconnect_ivl to '2412ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'minion1', 'tcp://192.168.50.10:4506', 'clear')
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Determining pillar cache
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'minion1', 'tcp://192.168.50.10:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'minion1', 'tcp://192.168.50.10:4506')
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[ERROR   ] Got a bad pillar from master, type str, expecting dict: 
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded pillar.items
[DEBUG   ] Determining pillar cache
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'minion1', 'tcp://192.168.50.10:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'minion1', 'tcp://192.168.50.10:4506')
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[ERROR   ] Got a bad pillar from master, type str, expecting dict: 
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'minion1', 'tcp://192.168.50.10:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'minion1', 'tcp://192.168.50.10:4506')
[DEBUG   ] LazyLoaded nested.output
```

In logs i see:
`[ERROR   ] Got a bad pillar from master, type str, expecting dict:`
### Versions Report

```
root@saltmaster:/srv# salt --versions-report
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-91-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by Ch3LL** [comment]
@fedusia looks like I am able to replicate this behavior:

Looks like i'm seeing the same behavior with your same test case:

```
2016-07-07 11:34:34,879 [salt.loaded.int.module.cmdmod][INFO    ][17260] Executing command 'hiera -c /srv/hiera.yaml biosversion='rel-1.8.1-0-g4adadbd-20160215_151056-lamb14' kernel='Linux' domain='test.com' zmqversion='4.1.2' kernelrelease='3.10.0-327.4.5.el7.x86_64' BLAH='blah2' shell='/bin/zsh' host='test' id='ipaddress' osrelease='7.2.1511' ps='ps -efH' uuid='uuid' init='systemd' osfullname='CentOS Linux' master='localhost' localhost='localhost.localdomain' lsb_distrib_id='CentOS Linux' username='root' nodename='localhost.localdomain' saltversion='2016.3.1' saltpath='/home/ch3ll/git/salt/salt' pythonexecutable='/usr/bin/python' osmajorrelease='7' os_family='RedHat' oscodename='CentOS Linux 7 (Core)' osfinger='CentOS Linux-7' testgrain='test' manufacturer='QEMU' groupname='root' cpu_model='QEMU Virtual CPU version 2.3.1' fqdn='test.test.com' biosreleasedate='04/01/2014' productname='Standard PC (i440FX + PIIX, 1996)' osarch='x86_64' cpuarch='x86_64' lsb_distrib_codename='CentOS Linux 7 (Core)' path='/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin' machine_id='machineid' os='CentOS' virtual='kvm'' in directory '/root'
2016-07-07 11:34:34,961 [salt.loaded.int.module.cmdmod][DEBUG   ][17260] output: nil
2016-07-07 11:34:34,963 [salt.master      ][ERROR   ][17260] Error in function _pillar:
Traceback (most recent call last):
  File "/home/ch3ll/git/salt/salt/master.py", line 1540, in run_func
    ret = getattr(self, func)(load)
  File "/home/ch3ll/git/salt/salt/master.py", line 1276, in _pillar
    data = pillar.compile_pillar(pillar_dirs=pillar_dirs)
  File "/home/ch3ll/git/salt/salt/pillar/__init__.py", line 806, in compile_pillar
    pillar, pillar_dirs, errors=errors)
  File "/home/ch3ll/git/salt/salt/pillar/__init__.py", line 782, in ext_pillar
    self.opts.get('pillar_merge_lists', False))
  File "/home/ch3ll/git/salt/salt/utils/dictupdate.py", line 105, in merge
    elif strategy == 'recurse':
  File "/home/ch3ll/git/salt/salt/utils/dictupdate.py", line 81, in merge_recurse
    copied = copy.deepcopy(obj_a)
  File "/home/ch3ll/git/salt/salt/utils/dictupdate.py", line 35, in update
    or (not isinstance(upd, collections.Mapping)):
TypeError: Cannot update using non-dict types in dictupdate.update()
```

I'm not famiilar with hiera but i'm guessing the `output: nil` has something to do with this issue. If you were to run that command you would get that same output `nil`. Not sure why its getting a nil and anyone else with more hera knowledge that could explain it would be great that comes to this issue. For now i'll label it as a bug. Thanks

**Comment by fedusia** [comment]
i will research this issue by myself, i would glad for any help.
