### ISSUE TITLE
salt-cloud vsphere list_nodes doesn't work on vCenter ESX 6.0

### ISSUE THREAD

**Issue by sebw** [saltstack/salt#34533]
I can't retrieve nodes info using list_nodes, list_nodes_min works though:

`# salt-cloud -f list_nodes vmware -l trace`

```
[ERROR   ] There was an error running the function: 'ascii' codec can't encode character u'\xa0' in position 17: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/cli.py", line 274, in run
    self.function_provider, self.function_name, kwargs
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1599, in do_function
    driver: self.clouds[fun](call='function')
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/vmware.py", line 1395, in list_nodes
    'image': "{0} (Detected)".format(vm["config.guestFullName"]) if "config.guestFullName" in vm else "N/A",
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 17: ordinal not in range(128)
```

It appears that the Guest OS field contains \xa0 character instead of spaces:

`{u'config.hardware.numCPU': 1, u'name': '<REDACTED>', u'config.guestFullName': u'Red\xa0Hat\xa0Enterprise Linux\xa06 (64\xa0bits)', 'object': 'vim.VirtualMachine:vm-252', u'guest.ipAddress': '172.24.240.65', u'summary.runtime.powerState': 'poweredOn', u'config.hardware.memoryMB': 8192}`

```
Salt Version:
            Salt: 2016.3.1
 
Dependency Versions:
 Apache Libcloud: 0.20.1
            cffi: Not Installed
        cherrypy: 3.2.2
        dateutil: 1.5
           gitdb: Not Installed
       gitpython: Not Installed
           ioflo: Not Installed
          Jinja2: 2.7.2
         libgit2: Not Installed
         libnacl: Not Installed
        M2Crypto: 0.21.1
            Mako: Not Installed
    msgpack-pure: Not Installed
  msgpack-python: 0.4.7
    mysql-python: Not Installed
       pycparser: Not Installed
        pycrypto: 2.6.1
          pygit2: Not Installed
          Python: 2.7.5 (default, Oct 11 2015, 17:47:16)
    python-gnupg: Not Installed
          PyYAML: 3.10
           PyZMQ: 14.7.0
            RAET: Not Installed
           smmap: Not Installed
         timelib: Not Installed
         Tornado: 4.2.1
             ZMQ: 4.0.5
 
System Versions:
            dist: redhat 7.2 Maipo
         machine: x86_64
         release: 3.10.0-327.el7.x86_64
          system: Linux
         version: Red Hat Enterprise Linux Server 7.2 Maipo
```

**Comment by sebw** [comment]
The problem lies in the encoding used in pyVmomi.

Adding the following to /usr/lib/python2.7/site-packages/pyVmomi/__init__.py fixes the problem:
reload(sys)
sys.setdefaultencoding('utf-8')

https://github.com/saltstack/salt/issues/30277

**Comment by Ch3LL** [comment]
from reading the other issue it seems like siilar to that issue we need to do some better handling on salts side of things. 

ping @s0undt3ch would you mind glancing at this? Do you see an easy fix to ensure we don't run into these unicode errors?

**Comment by s0undt3ch** [comment]
We cannot do `sys.setdefaultencoding('utf-8')` because that changes the default encoding for the whole python process. And while this fixes the problem for salt + pyvmomi, there's a huge chance it will break other libraries that expect ASCII which is the default for python. Yes that seems wrong on the python side but that's what python's stdlib does.

**Comment by s0undt3ch** [comment]
Can we know the encoding pyvmomi uses programmatically?

**Comment by sebw** [comment]
@s0undt3ch a better workaround has been posted by @UtahDave (https://github.com/saltstack/salt/issues/38402) preventing changing the encoding in pyvmomi.
