### ISSUE TITLE
Could not deserialize msgpack message: Some exception handling minion payload

### ISSUE THREAD

**Issue by silenius** [saltstack/salt#34550]
I'm reinstalling the salt-master here and I don't know what's wrong but I have the following:

```
root@dev:/var/log/salt # cat minion
2016-07-08 14:59:25,453 [salt.crypt                                                ][ERROR   ][10553] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2016-07-08 14:59:35,468 [salt.crypt                                                ][ERROR   ][10553] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2016-07-08 14:59:45,478 [salt.crypt                                                ][ERROR   ][10553] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2016-07-08 14:59:55,841 [salt.payload                                              ][CRITICAL][10553] Could not deserialize msgpack message: Some exception handling minion payloadThis often happens when trying to read a file not in binary mode.Please open an issue and include the following error: unpack(b) received extra data.
2016-07-08 14:59:55,842 [tornado.general                                           ][ERROR   ][10553] Uncaught exception, closing connection.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 407, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/salt/transport/zeromq.py", line 816, in mark_future
    future.set_result(self.serial.loads(msg[0]))
  File "/usr/local/lib/python2.7/site-packages/salt/payload.py", line 117, in loads
    return msgpack.loads(msg, use_list=True)
  File "_unpacker.pyx", line 123, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:123)
ExtraData: unpack(b) received extra data.
2016-07-08 14:59:55,870 [tornado.general                                           ][ERROR   ][10553] Uncaught exception, closing connection.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 433, in _handle_events
    self._handle_recv()
  File "/usr/local/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 465, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 407, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/salt/transport/zeromq.py", line 816, in mark_future
    future.set_result(self.serial.loads(msg[0]))
  File "/usr/local/lib/python2.7/site-packages/salt/payload.py", line 117, in loads
    return msgpack.loads(msg, use_list=True)
  File "_unpacker.pyx", line 123, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:123)
ExtraData: unpack(b) received extra data.
2016-07-08 14:59:55,871 [tornado.application                                       ][ERROR   ][10553] Exception in callback None
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/tornado/ioloop.py", line 883, in start
    handler_func(fd_obj, events)
  File "/usr/local/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 433, in _handle_events
    self._handle_recv()
  File "/usr/local/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 465, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 407, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/salt/transport/zeromq.py", line 816, in mark_future
    future.set_result(self.serial.loads(msg[0]))
  File "/usr/local/lib/python2.7/site-packages/salt/payload.py", line 117, in loads
    return msgpack.loads(msg, use_list=True)
  File "_unpacker.pyx", line 123, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:123)
ExtraData: unpack(b) received extra data.
```

I tried with 2015.8.3, 2015.8.8, and 2016.3.1 ... I supect something is broken between the dependencies ...
### Versions Report

```
root@dev:/var/log/salt # salt --versions-report
Salt Version:
           Salt: 2015.8.3

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.11 (default, Jan  3 2016, 14:37:43)
           RAET: 0.6.5
        Tornado: 4.3
            ZMQ: 4.1.3
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.4.6
        libnacl: 1.4.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist:   
        machine: amd64
        release: 10.3-RELEASE
```

**Comment by silenius** [comment]
same on:
```
root@dev:/usr/local/etc/salt # salt --versions-report
Salt Version:
           Salt: 2016.3.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.5.0
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: 1.4.4
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jul  5 2016, 09:28:23)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: 0.6.5
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.4
 
System Versions:
           dist:   
        machine: amd64
        release: 10.3-RELEASE
         system: FreeBSD
        version: Not Installed
```

**Comment by silenius** [comment]
ok I just rebooted, started from scratch, rm -rf /var/cache/salt, rm -rf /usr/local/etc/salt/pki, and maybe one important thing: I started the salt_master under the root user instead of a dedicated one .. I don't known if it has something to do but it works now .. very strange ..

**Comment by silenius** [comment]
just `rm -rf /var/cache/salt` and reswitched to `user: salt` in the master file and I get the msgpack error again, so apparently it seems related ...

**Comment by Ch3LL** [comment]
hmmm I'm not seeing this behavior if i change the `user: salt`. How did you install/re-install salt?

**Comment by silenius** [comment]
In this case it was a new installation, minions were running 2015.8 and I installed a new 2016.1 master. In the end I `rm -rf /var/cache/salt` and `rm -rf /usr/local/salt/pki` ... Perhaps the problem come from the `hash_type:` which changed
