### ISSUE TITLE
returner redis KeyError: 'keep_jobs'

### ISSUE THREAD

**Issue by SolarisYan** [saltstack/salt#34578]
Hello, i want to use redis as returner,but i have this error:

```
2016-07-11 17:11:12,176 [salt.minion      ][ERROR   ][4782] The return failed for job 20160711171111730719 'keep_jobs'
2016-07-11 17:11:12,177 [salt.minion      ][ERROR   ][4782] Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1418, in _thread_return
    )](ret)
  File "/usr/lib/python2.7/site-packages/salt/returners/redis_return.py", line 117, in returner
    pipeline.expire('ret:{0}'.format(jid), _get_ttl())
  File "/usr/lib/python2.7/site-packages/salt/returners/redis_return.py", line 106, in _get_ttl
    return __opts__['keep_jobs'] * 3600
KeyError: 'keep_jobs'
```

my conf  as follow:

```
cat  /etc/salt/master.d/redis.conf 
redis.db: '0'
redis.host: 192.168.111.60
redis.port: 6379
keep_jobs: 24
```

```
salt --versions-report 
Salt Version:
           Salt: 2016.3.0

Dependency Versions:
           cffi: 0.8.6
       cherrypy: 5.4.0
       dateutil: 2.5.3
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: 1.5.4
         Jinja2: 2.8
        libgit2: 0.21.0
        libnacl: 1.4.4
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.4
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: 0.6.5
          smmap: 0.8.1
        timelib: Not Installed
        Tornado: 4.2
            ZMQ: 4.0.5

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.4.4.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

**Comment by Ch3LL** [comment]
@SolarisYan do you have the python client for redis installed? `pip install python-redis` i believe the name is

**Comment by SolarisYan** [comment]
@Ch3LL i have install redis use pip install redis, and now i uninstall the redis use pip uninstall redis,then use pip install python-redis,and the error as follow:
2016-07-12 10:48:19,685 [salt.minion      ][ERROR   ][11196] The return failed for job 20160712104819401140 'redis.returner'
2016-07-12 10:48:19,685 [salt.minion      ][ERROR   ][11196] Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1417, in _thread_return
    returner
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1052, in __getitem__
    func = super(LazyLoader, self).__getitem__(item)
  File "/usr/lib/python2.7/site-packages/salt/utils/lazy.py", line 93, in __getitem__
    raise KeyError(key)
KeyError: 'redis.returner'
 
pip list|grep redis
python-redis (0.0.7)

**Comment by sssl93** [comment]
use "pip install redis" and add "keep_jobs: 24" to the /etc/salt/minion !
