### ISSUE TITLE
keystone.endpoint_present gave an error: AttributeError: adminurl

### ISSUE THREAD

**Issue by jackivanov** [saltstack/salt#34580]
### Description of Issue/Question

Hello, guys!
I'm trying to add endpoints to keystone and got an error
Some debug below
### Setup

SLS:

```
nova endpoint:
  keystone.endpoint_present:
    - name: nova
    - publicurl: 'http://hostname.com:5000/v2.0'
    - internalurl: 'http://hostname.com:5000/v2.0'
    - adminurl: 'http://hostname.com:35357/v2.0'
    - region: Region
    - token: e55953e7325gdrfb590a9a13b5ad6ca
    - auth_url: http://hostname.com:35357/v2.0
```

pillar:

```
keystone.token: 'e55953e7325gdrfb590a9a13b5ad6ca'
keystone.endpoint: 'http://hostname.com:35357/v2.0'
```
### Steps to Reproduce Issue

You should have working Keystone instance on your server, then just run this SLS.
### Versions Report

```
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.8.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 4.4.6-std-2
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

```
# salt 'hostname.com' state.apply -l debug


[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'hst-9fbb85_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/05/40d2cacd8faa751910ef4dd54b3034/.minions.p
[DEBUG   ] get_iter_returns for jid 20160711115344518524 sent to set(['hostname.com']) will timeout at 11:53:49.536300
[DEBUG   ] jid 20160711115344518524 return from hostname.com
[DEBUG   ] LazyLoaded highstate.output
hostname.com:
----------
          ID: nova endpoint
    Function: keystone.endpoint_present
        Name: nova
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1723, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1650, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/keystone.py", line 550, in endpoint_present
                  **connection_args)
                File "/usr/lib/python2.7/site-packages/salt/modules/keystone.py", line 271, in endpoint_get
                  endpoints = endpoint_list(profile, **connection_args)
                File "/usr/lib/python2.7/site-packages/salt/modules/keystone.py", line 293, in endpoint_list
                  'adminurl': endpoint.adminurl,
                File "/usr/lib/python2.7/site-packages/keystoneclient/base.py", line 491, in __getattr__
                  raise AttributeError(k)
              AttributeError: adminurl
     Started: 11:53:48.715453
    Duration: 101.707 ms
     Changes:   

Summary for hostname.com
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
[DEBUG   ] jid 20160711115344518524 found all minions set(['hostname.com'])
ERROR: Minions returned with non-zero exit code
```

Can anyone tell me, what is that? And How can I enable more informative debug?

**Comment by gunph1ld** [comment]
and `endpoint_get` also does not work

```
# salt 'hostname.com' keystone.endpoint_get nova
hostname.com:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1318, in _thread_return
        return_data = executor.execute()
      File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/usr/lib/python2.7/site-packages/salt/modules/keystone.py", line 271, in endpoint_get
        endpoints = endpoint_list(profile, **connection_args)
      File "/usr/lib/python2.7/site-packages/salt/modules/keystone.py", line 293, in endpoint_list
        'adminurl': endpoint.adminurl,
      File "/usr/lib/python2.7/site-packages/keystoneclient/base.py", line 491, in __getattr__
        raise AttributeError(k)
    AttributeError: adminurl
```

**Comment by Ch3LL** [comment]
Looks like we need to ensure `adminurl` is actually returned in `keystone.endpoints.list`

Would you mind adding a debug log line here:

```
   290     for endpoint in kstone.endpoints.list():                                                                                                                          
   291         log.debug('print endpoint: {0}'.format(endpoint))                                                                                                             
   292         log.debug('print endpoint.id: {0}'.format(endpoint.id))                                                                                                       
   293         ret[endpoint.id] = {'id': endpoint.id,                                                                                                                        
   294                             'region': endpoint.region,                                                                                                                
   295                             'adminurl': endpoint.adminurl,                                                                                                            
   296                             'internalurl': endpoint.internalurl,                                                                                                      
   297                             'publicurl': endpoint.publicurl,                                                                                                          
   298                             'service_id': endpoint.service_id}                                                                                                                                                                                            
```

in the `salt.modules.keystone` endpoint_list method, so we can see what endpoint.list is returning
