### ISSUE TITLE
AttributeError: 'module' object has no attribute 'BASE_THORIUM_ROOTS_DIR'

### ISSUE THREAD

**Issue by kevops** [saltstack/salt#34603]
### Description of Issue/Question
Upgraded from 2015.5.3 to 2016.3.1 from  https://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/

### Steps to Reproduce Issue
Trying to run state.highstate from 2016.3.1 minion:

```
c:\salt>salt-call state.highstate
Traceback (most recent call last):
File "c:\salt\bin\Scripts\salt-call", line 11, in 
salt_call()
File "c:\salt\bin\lib\site-packages\salt\scripts.py", line 221, in salt_call
import salt.cli.call
File "c:\salt\bin\lib\site-packages\salt\cli\call.py", line 6, in 
from salt.utils import parsers
File "c:\salt\bin\lib\site-packages\salt\utils\parsers.py", line 28, in e>
import salt.config as config
File "c:\salt\bin\lib\site-packages\salt\config__init__.py", line 866, in dule>
'base': [salt.syspaths.BASE_THORIUM_ROOTS_DIR],
AttributeError: 'module' object has no attribute 'BASE_THORIUM_ROOTS_DIR'
```

### Versions Report
```
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-32-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by cachedout** [comment]
You have stale `.pyc` files in your Salt installation. Clear those out and try again, please.

**Comment by kevops** [comment]
Can I *easily downgrade to 2015.8.5?

**Comment by rallytime** [comment]
You should be able to pin to the 2015.8 release branch here: http://repo.saltstack.com/2015.8.html#ubuntu

**Comment by asottile** [comment]
I had to manually delete a file to fix this, the upgrade / uninstall procedure was not clean for some reason:

```console
$  rm "$VENV/lib/python2.7/site-packages/salt/_syspaths.py"
```
