### ISSUE TITLE
userdata_file option in cloud profile throws errors on powershell scripts for windows instances

### ISSUE THREAD

**Issue by yamamushi** [saltstack/salt#34610]
### Description of Issue/Question

I am trying to create windows instances in AWS using Salt-Cloud. 

In order to do this, we need to upload a powershell script opening up various ports on the newly created instances, as described by this documentation: https://docs.saltstack.com/en/develop/topics/cloud/windows.html

Before today's upgrade over to the develop branch, we were able to create instances using this profile without any issues. However, as of the upgrade today, we are no longer able to create any windows instances due to the following error being thrown:

```

[DEBUG   ] Generating minion keys for 'wintest3'
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event - data = {'profile': 'base_windows_2012r2', 'event': 'starting create', '_stamp': '2016-07-12T16:36:13.349456', 'name': 'wintest3', 'provider': 'mredacted-ec2:ec2'}
[INFO    ] Creating Cloud VM wintest3 in us-east-1
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] compile template: <powershell>
New-NetFirewallRule -Name "SMB445" -DisplayName "SMB445" -Protocol TCP -LocalPort 445
New-NetFirewallRule -Name "WINRM5986" -DisplayName "WINRM5986" -Protocol TCP -LocalPort 5986
New-NetFirewallRule -Name "TEAMCITYUI" -DisplayName "TEAMCITYUI" -Protocol TCP -LocalPort 8111
New-NetFirewallRule -Name "TEAMCITYBUILD" -DisplayName "Allow TeamCity" -Direction Inbound -Protocol TCP -LocalPort 9090 -Program "c:\program files\java\jre7\bin\java.exe" -Action Allow

winrm quickconfig -q
winrm set winrm/config/winrs '@{MaxMemoryPerShellMB="300"}'
winrm set winrm/config '@{MaxTimeoutms="1800000"}'
winrm set winrm/config/service/auth '@{Basic="true"}'

$SourceStoreScope = 'LocalMachine'
$SourceStorename = 'Remote Desktop'

$SourceStore = New-Object  -TypeName System.Security.Cryptography.X509Certificates.X509Store  -ArgumentList $SourceStorename, $SourceStoreScope
$SourceStore.Open([System.Security.Cryptography.X509Certificates.OpenFlags]::ReadOnly)

$cert = $SourceStore.Certificates | Where-Object  -FilterScript {
    $_.subject -like '*'
}

$DestStoreScope = 'LocalMachine'
$DestStoreName = 'My'

$DestStore = New-Object  -TypeName System.Security.Cryptography.X509Certificates.X509Store  -ArgumentList $DestStoreName, $DestStoreScope
$DestStore.Open([System.Security.Cryptography.X509Certificates.OpenFlags]::ReadWrite)
$DestStore.Add($cert)

$SourceStore.Close()
$DestStore.Close()

winrm create winrm/config/listener?Address=*+Transport=HTTPS  `@`{Hostname=`"($certId)`"`;CertificateThumbprint=`"($cert.Thumbprint)`"`}

Restart-Service winrm
</powershell>

[ERROR   ] Template does not exist: <powershell>
New-NetFirewallRule -Name "SMB445" -DisplayName "SMB445" -Protocol TCP -LocalPort 445
New-NetFirewallRule -Name "WINRM5986" -DisplayName "WINRM5986" -Protocol TCP -LocalPort 5986
New-NetFirewallRule -Name "TEAMCITYUI" -DisplayName "TEAMCITYUI" -Protocol TCP -LocalPort 8111
New-NetFirewallRule -Name "TEAMCITYBUILD" -DisplayName "Allow TeamCity" -Direction Inbound -Protocol TCP -LocalPort 9090 -Program "c:\program files\java\jre7\bin\java.exe" -Action Allow

winrm quickconfig -q
winrm set winrm/config/winrs '@{MaxMemoryPerShellMB="300"}'
winrm set winrm/config '@{MaxTimeoutms="1800000"}'
winrm set winrm/config/service/auth '@{Basic="true"}'

$SourceStoreScope = 'LocalMachine'
$SourceStorename = 'Remote Desktop'

$SourceStore = New-Object  -TypeName System.Security.Cryptography.X509Certificates.X509Store  -ArgumentList $SourceStorename, $SourceStoreScope
$SourceStore.Open([System.Security.Cryptography.X509Certificates.OpenFlags]::ReadOnly)

$cert = $SourceStore.Certificates | Where-Object  -FilterScript {
    $_.subject -like '*'
}

$DestStoreScope = 'LocalMachine'
$DestStoreName = 'My'

$DestStore = New-Object  -TypeName System.Security.Cryptography.X509Certificates.X509Store  -ArgumentList $DestStoreName, $DestStoreScope
$DestStore.Open([System.Security.Cryptography.X509Certificates.OpenFlags]::ReadWrite)
$DestStore.Add($cert)

$SourceStore.Close()
$DestStore.Close()

winrm create winrm/config/listener?Address=*+Transport=HTTPS  `@`{Hostname=`"($certId)`"`;CertificateThumbprint=`"($cert.Thumbprint)`"`}

Restart-Service winrm
</powershell>

[ERROR   ] There was a profile error: must be string or buffer, not dict
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/cli.py", line 284, in run
    self.config.get('names')
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1454, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1284, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/ec2.py", line 2501, in create
    data, vm_ = request_instance(vm_, location)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/ec2.py", line 1708, in request_instance
    params[spot_prefix + 'UserData'] = base64.b64encode(userdata)
  File "/usr/lib64/python2.7/base64.py", line 53, in b64encode
    encoded = binascii.b2a_base64(s)[:-1]
TypeError: must be string or buffer, not dict

```

Are we supposed to be using a different option now for pushing these powershell scripts up, or is something else new broken that I am unaware of?

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

Cloud profile: 

```
base_windows_2012r2:
  provider: ec2-provider
  image: ami-79dc1b14
  size: t2.micro
  use_winrm: True
  userdata_file: /etc/salt/windows-firewall.ps1
  win_installer: /etc/salt/Salt-Minion-2016.3.1-AMD64-Setup.exe
  win_username: Administrator
  win_password: auto
  win_interface: private_ips
  smb_port: 445
  script: bootstrap-salt
  script_args: -G -H "http://172.30.0.143:3128"
  subnetid: subnet-redacted
  securitygroupid:
    - sg-redacted

```

It is worth pointing out that removing the script_args and script options from the config still result in the same error. 

Powershell script:
```

<powershell>
New-NetFirewallRule -Name "SMB445" -DisplayName "SMB445" -Protocol TCP -LocalPort 445
New-NetFirewallRule -Name "WINRM5986" -DisplayName "WINRM5986" -Protocol TCP -LocalPort 5986
New-NetFirewallRule -Name "TEAMCITYUI" -DisplayName "TEAMCITYUI" -Protocol TCP -LocalPort 8111
New-NetFirewallRule -Name "TEAMCITYBUILD" -DisplayName "Allow TeamCity" -Direction Inbound -Protocol TCP -LocalPort 9090 -Program "c:\program files\java\jre7\bin\java.exe" -Action Allow

winrm quickconfig -q
winrm set winrm/config/winrs '@{MaxMemoryPerShellMB="300"}'
winrm set winrm/config '@{MaxTimeoutms="1800000"}'
winrm set winrm/config/service/auth '@{Basic="true"}'

$SourceStoreScope = 'LocalMachine'
$SourceStorename = 'Remote Desktop'

$SourceStore = New-Object  -TypeName System.Security.Cryptography.X509Certificates.X509Store  -ArgumentList $SourceStorename, $SourceStoreScope
$SourceStore.Open([System.Security.Cryptography.X509Certificates.OpenFlags]::ReadOnly)

$cert = $SourceStore.Certificates | Where-Object  -FilterScript {
    $_.subject -like '*'
}

$DestStoreScope = 'LocalMachine'
$DestStoreName = 'My'

$DestStore = New-Object  -TypeName System.Security.Cryptography.X509Certificates.X509Store  -ArgumentList $DestStoreName, $DestStoreScope
$DestStore.Open([System.Security.Cryptography.X509Certificates.OpenFlags]::ReadWrite)
$DestStore.Add($cert)

$SourceStore.Close()
$DestStore.Close()

winrm create winrm/config/listener?Address=*+Transport=HTTPS  `@`{Hostname=`"($certId)`"`;CertificateThumbprint=`"($cert.Thumbprint)`"`}

Restart-Service winrm
</powershell>

```

### Steps to Reproduce Issue

Using the aforementioned cloud profile:

`salt-cloud -p base_windows_2012r2 wintest1 -l debug`

salt-cloud will fail before an instance is created, with the previously provided error message.

Specifically the message that is concerning, although I could be looking in the wrong place, is : 

`[ERROR   ] Template does not exist: <powershell>`

### Versions Report

```

Salt Version:
           Salt: 2016.3.1-3061-g81d5a7a
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 6.0.2
       dateutil: 2.5.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Oct 11 2015, 17:47:16)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: redhat 7.2 Maipo
        machine: x86_64
        release: 3.10.0-327.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.2 Maipo

```

Any help or suggestions would be appreciated.

**Comment by rallytime** [comment]
Hi @yamamushi - I can reproduce this on the develop branch. This regression was caused by the change in #32698. We'll need to get this fixed up.

ping @techhat

**Comment by rallytime** [comment]
This is also likely related to #33194

**Comment by techhat** [comment]
@yamamushi, #34623 should fix this.

**Comment by yamamushi** [comment]
@techhat Thank you, I will not have the opportunity to test this until I go into the office tomorrow morning at ~10-11am CDT, however I will update this ticket to confirm if it has been resolved from my tests.

**Comment by yamamushi** [comment]
@techhat Is there a way to confirm that the script is actually being run on the windows instances when they're being created?

If I spin them up now, it doesn't look like the powershell is being run because no ports are being opened up to allow for remote access as listed in the script.

**Comment by techhat** [comment]
@twangboy, you know powershell better than me, do you have an answer?

**Comment by yamamushi** [comment]
For reference, here is what a successful instance creation looks like with the aforementioned powershell script:```


# nmap 172.31.14.89

Starting Nmap 6.40 ( http://nmap.org ) at 2016-07-13 13:57 EDT
Nmap scan report for 172.31.14.89
Host is up (0.0019s latency).
Not shown: 993 filtered ports
PORT      STATE SERVICE
135/tcp   open  msrpc
139/tcp   open  netbios-ssn
445/tcp   open  microsoft-ds
3389/tcp  open  ms-wbt-server
49154/tcp open  unknown
49155/tcp open  unknown
49158/tcp open  unknown

Nmap done: 1 IP address (1 host up) scanned in 4.55 seconds
```

**Comment by twangboy** [comment]
@techhat I think it's failing before the powershell even runs. It looks like something with templating...
```
[ERROR ] Template does not exist: <powershell>
```

**Comment by techhat** [comment]
@twangboy, #34623 should resolve that templating error. What we need to know now is whether or not the uploaded script actually ran.

**Comment by twangboy** [comment]
@techhat The script ran fine through the port opening portions.... maybe it's doing something with the encoding of the file...

**Comment by techhat** [comment]
@twangboy what need to know is how the user himself can verify that the script has run, on a per-VM basis. Does Windows keep any sort of log? Is there some powershell that we can use to try and write a log?

**Comment by twangboy** [comment]
@techhat @yamamushi The easiest way would probably be to use the `Start-Transcript` / `Stop-Transcript` functions.

https://technet.microsoft.com/en-us/magazine/ff687007.aspx

**Comment by yamamushi** [comment]
@twangboy If you're able to confirm that you can create EC2 Windows instances now, then I suppose this can be closed as the issue must be on my side. 

Otherwise, I've not been able to successfully get the powershell firewall setup script to run successfully, as running nmap against the new instance does not show the ports have been opened.

**Comment by twangboy** [comment]
@yamamushi I will spin something up now just to be sure... stand by.

**Comment by twangboy** [comment]
@yamamushi Aside from an error:
```
[ERROR   ] Public IP not detected.  If private IP is meant for bootstrap you must specify "ssh_interface: private_ips" in your profile.
```
The VM spun up correctly. I was able to ping, so the script ran and opened ports...

**Comment by yamamushi** [comment]
@twangboy Thank you for confirming, I'll close this issue now :-)
