### ISSUE TITLE
libcloud_dns module requiring non-existent libcloud function

### ISSUE THREAD

**Issue by techhat** [saltstack/salt#34613]
### Description of Issue/Question
When running my master in the foreground (`salt-master -l debug`) I noticed the following error:
```
[DEBUG   ] Error loading module.libcloud_dns: __init__ failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1362, in _load_module
    module_init(self.opts)
  File "/usr/lib/python2.7/site-packages/salt/modules/libcloud_dns.py", line 67, in __init__
    __utils__['libcloud.assign_funcs'](__name__, 'dns', pack=__salt__)
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1066, in __getitem__
    func = super(LazyLoader, self).__getitem__(item)
  File "/usr/lib/python2.7/site-packages/salt/utils/lazy.py", line 101, in __getitem__
    raise KeyError(key)
KeyError: 'libcloud.assign_funcs'
```
I didn't see this until I upgraded libcloud to version 1.1.0. I found this in the code:
```
REQUIRED_LIBCLOUD_VERSION = '0.21.0'
```
So it's probably happening to a lot of people, but they're not noticing because they're not running the master in the foreground.

Ping @tonybaloney.

### Versions Report
```
Salt Version:
           Salt: 2016.3.0
 
Dependency Versions:
           cffi: 1.7.0
       cherrypy: 6.0.2.post20160705
       dateutil: 2.5.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.5.5
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: 0.24.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jun 28 2016, 08:31:05)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: 0.6.5
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.5
 
System Versions:
           dist:   
        machine: x86_64
        release: 4.6.3-1-ARCH
         system: Linux
        version: Not Installed
```

**Comment by tonybaloney** [comment]
I'll tackle this.

**Comment by techhat** [comment]
Thanks @tonybaloney, you're the man.

**Comment by tonybaloney** [comment]
Created a PR @techhat , it was an easy one to fix.

**Comment by techhat** [comment]
Much appreciated @tonybaloney.
