### ISSUE TITLE
group.present: with  - addusers: [ a, b, c ] fails with KeyError: 'group.adduser' on FreeBSD 10.2

### ISSUE THREAD

**Issue by willjp** [saltstack/salt#34622]
### Description of Issue/Question
KeyError Exception occurs when adding users to an existing group using
group.present with addusers.

### Setup
```
#!stateconf

{% set build_users = [ 'vagrant', 'will' ] %}

.create group build:
   group.present:
      - name:    build
      - system: True
      - addusers: {{ build_users }}
```

fails with the traceback:
```
     Comment: An exception occurred in this state: Traceback (most recent call last):                                 │
                File "/usr/local/lib/python2.7/site-packages/salt/state.py", line 1626, in call                       │
                  **cdata['kwargs'])                                                                                  │
                File "/usr/local/lib/python2.7/site-packages/salt/loader.py", line 1492, in wrapper                   │
                  return f(*args, **kwargs)                                                                           │
                File "/usr/local/lib/python2.7/site-packages/salt/states/group.py", line 150, in present              │
                  __salt__['group.adduser'](name, user)                                                               │
                File "/usr/local/lib/python2.7/site-packages/salt/loader.py", line 900, in __getitem__                │
                  func = super(LazyLoader, self).__getitem__(item)                                                    │
                File "/usr/local/lib/python2.7/site-packages/salt/utils/lazy.py", line 93, in __getitem__             │
                  raise KeyError(key)                                                                                 │
              KeyError: 'group.adduser'    
```

when run using salt-call
```
## ex:
sudo salt-call state.apply roles.build_base
```

### Versions Report
```
Dependency Versions:                                                                                                  │
         Jinja2: 2.8                                                                                                  │
       M2Crypto: Not Installed                                                                                        │
           Mako: Not Installed                                                                                        │
         PyYAML: 3.11                                                                                                 │
          PyZMQ: 15.2.0                                                                                               │
         Python: 2.7.11 (default, Mar 31 2016, 22:11:39)                                                              │
           RAET: Not Installed                                                                                        │
        Tornado: 4.3                                                                                                  │
            ZMQ: 4.1.4                                                                                                │
           cffi: Not Installed                                                                                        │
       cherrypy: Not Installed                                                                                        │
       dateutil: 2.5.0                                                                                                │
          gitdb: Not Installed                                                                                        │
      gitpython: Not Installed                                                                                        │
          ioflo: Not Installed                                                                                        │
        libgit2: Not Installed                                                                                        │
        libnacl: Not Installed                                                                                        │
   msgpack-pure: Not Installed                                                                                        │
 msgpack-python: 0.4.7                                                                                                │
   mysql-python: 1.2.5                                                                                                │
      pycparser: Not Installed                                                                                        │
       pycrypto: 2.6.1                                                                                                │
         pygit2: Not Installed                                                                                        │
   python-gnupg: Not Installed                                                                                        │
          smmap: Not Installed                                                                                        │
        timelib: Not Installed                                                                                        │
                                                                                                                      │
System Versions:                                                                                                      │
           dist:                                                                                                      │
        machine: amd64                                                                                                │
        release: 10.2-RELEASE-p14   
```

**Comment by rallytime** [comment]
Hi @willjp! Hrm...It seems the group module isn't loading correctly. Can you post the output of a `salt-call grains.get kernel` command? 

It also looks like part of your versions report didn't get included. I don't see the part about what version of Salt you're running, which will be helpful in tracking this bug down. Can you run the `salt-call --versions` command again and paste the output?

**Comment by willjp** [comment]
Hey rallytime! I'm so embarassed - I was running an older version of salt-minion (2015.8.8) than my salt-master(2016.3.1). After a `pkg upgrade` everything is working as expected I'm so sorry.

**Comment by rallytime** [comment]
@willjp No problem! I am glad that you got it figured out and everything is working now. :)
