### ISSUE TITLE
pip.installed fails when state is called from another state

### ISSUE THREAD

**Issue by jakehilton** [saltstack/salt#34673]
### Description of Issue/Question

I have a state setup to install a package via pip. This state is called from another state. When this happens I always get the following error:

```
# salt-call state.highstate
[ERROR   ] Failed to import states pip_state, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1296, in _load_module
    ), fn_, fpath, desc)
  File "/usr/lib/python2.7/dist-packages/salt/states/pip_state.py", line 36, in <module>
    import pip
  File "/usr/local/lib/python2.7/dist-packages/pip/__init__.py", line 14, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 23, in <module>
    from pip.locations import (
  File "/usr/local/lib/python2.7/dist-packages/pip/locations.py", line 103, in <module>
    bin_user = os.path.join(user_site, 'bin')
  File "/usr/lib/python2.7/posixpath.py", line 77, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
[ERROR   ] State 'pip.installed' was not found in SLS 'syrinx'
Reason: 'pip.installed' is not available.

local:
----------
          ID: install_awscli
    Function: pip.installed
        Name: awscli
      Result: False
     Comment: State 'pip.installed' was not found in SLS 'syrinx'
              Reason: 'pip.installed' is not available.
     Started:
    Duration:
     Changes:

Summary for local
-------------
Succeeded: 80
Failed:     1
-------------
Total states run:     81
```

If I run the state standalone... I get this:

```
# salt-call state.sls syrinx
local:

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
```

My base state calls my syrinx state like so:

```
base:
  'syrinx':
    - syrinx
```
### Setup

My syrinx init.sls looks like this:

```
install_awscli:
  pip.installed:
    - name: awscli
```
### Steps to Reproduce Issue

Have a base state initialize another state which does a pip install.
### Versions Report

```
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.5.1
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: 1.4.4
       M2Crypto: 0.22
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: 0.6.5
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-74-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by rallytime** [comment]
@jakehilton What version of pip is installed on the box that has this failure?

**Comment by jakehilton** [comment]
```
$ pip --version
pip 8.1.2 from /usr/local/lib/python2.7/dist-packages (python 2.7)
```

**Comment by rallytime** [comment]
@jakehilton Hmm. I am unable to replicate this failure. Here's what I did to try and reproduce. Am I missing anything?
```
root@rallytime:~# cat /srv/salt/top.sls
base:
  'rallytime':
    - syrinx
root@rallytime:~# cat /srv/salt/syrinx/init.sls
install_awscli:
  pip.installed:
    - name: awscli
root@rallytime:~# salt-call state.highstate
local:
----------
          ID: install_awscli
    Function: pip.installed
        Name: awscli
      Result: True
     Comment: All packages were successfully installed
     Started: 19:49:48.795989
    Duration: 3143.294 ms
     Changes:
              ----------
              awscli==1.10.47:
                  Installed

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
```
I am running on the same version of salt and pip that you reported, as well:
```
root@rallytime:~# salt-call --versions
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: 0.8.6
       cherrypy: 5.0.1
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: 1.5.5
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: 0.3.8
         PyYAML: 3.10
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.5.5-x86_64-linode69
         system: Linux
        version: Ubuntu 14.04 trusty

root@rallytime:~# pip -V
pip 8.1.2 from /usr/local/lib/python2.7/dist-packages (python 2.7)
```

**Comment by angeloudy** [comment]
I am having the same issue after I upgraded python to 3.6, py-salt to py36-salt.
```
2017-12-13 13:49:04,688 [salt.state       ][ERROR   ][22777] Error encountered during module reload. Modules were not reloaded.
2017-12-13 13:49:47,603 [salt.loader      ][ERROR   ][22777] Failed to import states pip_state, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/salt/loader.py", line 1405, in _load_module
    mod = spec.loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/site-packages/salt/states/pip_state.py", line 36, in <module>
    import pip
  File "/usr/local/lib/python3.6/site-packages/pip/__init__.py", line 26, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/usr/local/lib/python3.6/site-packages/pip/utils/__init__.py", line 23, in <module>
    from pip.locations import (
  File "/usr/local/lib/python3.6/site-packages/pip/locations.py", line 103, in <module>
    bin_user = os.path.join(user_site, 'bin')
  File "/usr/local/lib/python3.6/posixpath.py", line 78, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
2017-12-13 13:49:50,308 [salt.state       ][ERROR   ][22777] State 'pip.installed' was not found in SLS
```

**Comment by dereckson** [comment]
Could be a duplicate of #44980
