### ISSUE TITLE
Salt Test Suite Error - develop

### ISSUE THREAD

**Issue by richardscollin** [saltstack/salt#34712]
### Description of Issue/Question
Salt test suite produces error then hangs.

### Steps to Reproduce Issue
python runtests.py --transport=tcp -n integration.modules.system

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt-tests/tests/runtests.py", line 587, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/salt-tests/tests/runtests.py", line 572, in main
    status = parser.run_integration_tests()
  File "/usr/lib/python2.7/site-packages/salt-tests/tests/runtests.py", line 508, in run_integration_tests
    with TestDaemon(self):
  File "/usr/lib/python2.7/site-packages/salt-tests/tests/integration/__init__.py", line 650, in __enter__
    self.start_tcp_daemons()
  File "/usr/lib/python2.7/site-packages/salt-tests/tests/integration/__init__.py", line 736, in start_zeromq_daemons
    process.wait_until_running(timeout=15)
  File "/usr/lib/python2.7/site-packages/salt-tests/tests/integration/__init__.py", line 527, in wait_until_running
    return self.io_loop.run_sync(self._wait_until_running, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/tornado/ioloop.py", line 445, in run_sync
    return future_cell[0].result()
  File "/usr/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/site-packages/tornado/gen.py", line 230, in wrapper
    yielded = next(result)
  File "/usr/lib/python2.7/site-packages/salt-tests/tests/integration/__init__.py", line 558, in _wait_until_running
    joined = self.run_run('manage.joined', config_dir=self.config_dir)
TypeError: run_run() got an unexpected keyword argument 'config_dir'
```

### Versions Report
```
Salt Version:
           Salt: 2016.3.0-859-g510e683

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.5
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 30 2016, 13:47:44)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: Not Installed
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: Not Installed

System Versions:
           dist:
        machine: x86_64
        release: 4.1.15-rt17-nilrt
         system: Linux
        version: Not Installed
```

**Comment by cachedout** [comment]
You need to upgrade your copy of salt-testing.

**Comment by richardscollin** [comment]
Thanks upgrading fixes the issue. Does the development branch track the development testing suite? If so it might make sense to put a note here: https://docs.saltstack.com/en/latest/topics/tutorials/writing_tests.html#getting-set-up-for-tests So that others down the line will install the right version.
