### ISSUE TITLE
cp.get_file / cp.get_url should take a directory as destination

### ISSUE THREAD

**Issue by jmacfar** [saltstack/salt#34747]
Would like to be able to pass a destination directory as argument to cp.get_file / cp.get_url instead of having to specify full path in source and also dest.

Currently errors out with "is a directory" or "permission denied" depending on OS.

```
$ salt 'MinionName' cp.get_file salt://test/file.txt /tmp/
MinionName:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1318, in _thread_return
        return_data = executor.execute()
      File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/usr/lib/python2.7/site-packages/salt/modules/cp.py", line 222, in get_file
        gzip)
      File "/usr/lib/python2.7/site-packages/salt/fileclient.py", line 1145, in get_file
        fn_ = salt.utils.fopen(dest, 'wb+')
      File "/usr/lib/python2.7/site-packages/salt/utils/__init__.py", line 1209, in fopen
        fhandle = open(*args, **kwargs)
    IOError: [Errno 21] Is a directory: '/tmp/'
```

Windows minion gives same error, except ends with "IOError: [Errno 13] Permission denied: 'C:/_Software'
### Versions Report

All using salt 2016.3.1 (Boron)

**Comment by rallytime** [comment]
@jmacfar Good call - that would be useful!
