### ISSUE TITLE
Could not save load with returner local_cache

### ISSUE THREAD

**Issue by Someguy123** [saltstack/salt#34765]
Fresh install of salt 2016.3.1

Simply run `sudo salt-ssh -c Saltfile 'managed' -i test.ping` - basic config from the tutorial.

```
(venv) ➜  salt-ssh sudo salt-ssh -c Saltfile 'managed' -i test.ping
[ERROR   ] can't serialize dict_keys(['managed'])
Traceback (most recent call last):
  File "/Users/chris/salt-ssh/venv/lib/python3.4/site-packages/salt/client/ssh/__init__.py", line 572, in run
    self.returners['{0}.save_load'.format(self.opts['master_job_cache'])](jid, job_load, minions=self.targets.keys())
  File "/Users/chris/salt-ssh/venv/lib/python3.4/site-packages/salt/returners/local_cache.py", line 244, in save_load
    save_minions(jid, minions)
  File "/Users/chris/salt-ssh/venv/lib/python3.4/site-packages/salt/returners/local_cache.py", line 274, in save_minions
    serial.dump(minions, salt.utils.fopen(minions_path, 'w+b'))
  File "/Users/chris/salt-ssh/venv/lib/python3.4/site-packages/salt/payload.py", line 224, in dump
    fn_.write(self.dumps(msg))
  File "/Users/chris/salt-ssh/venv/lib/python3.4/site-packages/salt/payload.py", line 141, in dumps
    return msgpack.dumps(msg)
  File "/Users/chris/salt-ssh/venv/lib/python3.4/site-packages/msgpack/__init__.py", line 47, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 231, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:231)
  File "msgpack/_packer.pyx", line 233, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:233)
  File "msgpack/_packer.pyx", line 228, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:228)
TypeError: can't serialize dict_keys(['managed'])
[ERROR   ] Could not save load with returner local_cache: can't serialize dict_keys(['managed'])
```

**Comment by Ch3LL** [comment]
@Someguy123 How did you install salt? Also can you please provide the output of `salt-ssh --versions-report` 

I'm not seeing this error so any additional information will be useful.

**Comment by Someguy123** [comment]
@Ch3LL I installed it via `pip3 install salt`

When I run version report, I get a large python3 error.

```
➜  ~ salt-ssh --versions-report
Traceback (most recent call last):
  File "/usr/local/bin/salt-ssh", line 9, in <module>
    load_entry_point('salt-ssh==2016.3.1', 'console_scripts', 'salt-ssh')()
  File "/usr/local/lib/python3.4/site-packages/salt/scripts.py", line 391, in salt_ssh
    client.run()
  File "/usr/local/lib/python3.4/site-packages/salt/cli/ssh.py", line 16, in run
    self.parse_args()
  File "/usr/local/lib/python3.4/site-packages/salt/utils/parsers.py", line 177, in parse_args
    self.print_versions_report()
  File "/usr/local/lib/python3.4/site-packages/salt/utils/parsers.py", line 244, in print_versions_report
    print('\n'.join(version.versions_report()), file=file)
  File "/usr/local/lib/python3.4/site-packages/salt/version.py", line 654, in versions_report
    for name in sorted(ver_info[ver_type], cmp=lambda x, y: cmp(x.lower(), y.lower())):
TypeError: 'cmp' is an invalid keyword argument for this function
```

**Comment by FabriceSalvaire** [comment]
`sorted(cmp=)` is invalid in Python3

**Comment by ezh** [comment]
I have the same issue with sorted(cmp=)
I replaced
```sorted(ver_info[ver_type], cmp=lambda x, y: cmp(x.lower(), y.lower()))```
with
```sorted(ver_info[ver_type], key=lambda x: x.lower()):```
I used guide from http://python3porting.com/preparing.html#keycmp-section
Is it possible to push this fix to upstream?

```
 'Salt Version': {'Salt': '2016.3.3'},
 'System Versions': {'dist': '  ',
                     'machine': 'x86_64',
                     'release': '14.5.0',
                     'system': 'Darwin',
                     'version': '10.10.5 x86_64'}}
(BPdb) l
653  	   info = []
654  	   for ver_type in ('Salt Version', 'Dependency Versions', 'System Versions'):
655  	       info.append('{0}:'.format(ver_type))
656  	       import bpdb; bpdb.set_trace()
657  	       # List dependencies in alphabetical, case insensitive order
658  ->	       for name in sorted(ver_info[ver_type], cmp=lambda x, y: cmp(x.lower(), y.lower())):
659  	           ver = fmt.format(name,
660  	                            ver_info[ver_type][name] or 'Not Installed',
661  	                            pad=padding)
662  	           info.append(ver)
663  	       info.append(' ')
(BPdb) pp ver_info[ver_type]
{'Salt': '2016.3.3'}
(BPdb) pp sorted(ver_info[ver_type], cmp=lambda x, y: cmp(x.lower(), y.lower()))
*** TypeError: 'cmp' is an invalid keyword argument for this function
(BPdb) pp ver_info[ver_type]
{'Salt': '2016.3.3'}
(BPdb) pp sorted(ver_info[ver_type], key=lambda x: x.lower())
['Salt']
(BPdb)
```

**Comment by ezh** [comment]
I have the same issue with 'local_cache' ...
```
 ❯ salt-ssh -c ./salt/etc/ '*' test.ping                                                                                                                                                                                                   >>> elapsed 3h55m3s
[ERROR   ] can't serialize dict_keys(['testserver'])
Traceback (most recent call last):
  File "/Users/aaksenov/.virtualenvs/py3/lib/python3.5/site-packages/salt/client/ssh/__init__.py", line 582, in run
    self.returners['{0}.save_load'.format(self.opts['master_job_cache'])](jid, job_load, minions=self.targets.keys())
  File "/Users/aaksenov/.virtualenvs/py3/lib/python3.5/site-packages/salt/returners/local_cache.py", line 246, in save_load
    save_minions(jid, minions)
  File "/Users/aaksenov/.virtualenvs/py3/lib/python3.5/site-packages/salt/returners/local_cache.py", line 276, in save_minions
    serial.dump(minions, salt.utils.fopen(minions_path, 'w+b'))
  File "/Users/aaksenov/.virtualenvs/py3/lib/python3.5/site-packages/salt/payload.py", line 226, in dump
    fn_.write(self.dumps(msg))
  File "/Users/aaksenov/.virtualenvs/py3/lib/python3.5/site-packages/salt/payload.py", line 141, in dumps
    return msgpack.dumps(msg)
  File "/Users/aaksenov/.virtualenvs/py3/lib/python3.5/site-packages/msgpack/__init__.py", line 47, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 231, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:3661)
  File "msgpack/_packer.pyx", line 233, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:3503)
  File "msgpack/_packer.pyx", line 228, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:3382)
TypeError: can't serialize dict_keys(['testserver'])
[ERROR   ] Could not save load with returner local_cache: can't serialize dict_keys(['testserver'])
```

and my environment is
```
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 3.5.2 (default, Sep 28 2016, 18:06:29)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.5

System Versions:
           dist:
        machine: x86_64
        release: 14.5.0
         system: Darwin
        version: 10.10.5 x86_64
```

How I may fix it?

**Comment by Ch3LL** [comment]
as @FabriceSalvaire points out saltstack does not support python3, although there has been a lot of development towards supporting it in the upcoming carbon release(2016.3.11rc1), although I believe we are not officially supporting it until our next major release but there has been a lot of work in carbon regardless. So if you want to make a change to ensure the code works on python2 and python3 please attempt to see if you still are seeing the behavior on the develop branch or carbon branch if its a bug and submit your PRs there. We would greatly appreciate it! And any other testing on python3 :)

**Comment by Ch3LL** [comment]
also please report back whether its working after attempting in those branches? this might actually be fixed. Thanks
