### ISSUE TITLE
salt returner postgres

### ISSUE THREAD

**Issue by meagon** [saltstack/salt#34820]
### Description of Issue/Question

```
2016-07-20 19:09:23,852 [tornado.access   ][INFO    ][27011] 204 OPTIONS / (127.0.0.1) 0.30ms
2016-07-20 19:09:24,094 [salt.loaded.int.runners.vistara][ERROR   ][27514] vistara config has not been specificed in the Salt master config. See documentation for this runner.
2016-07-20 19:09:24,328 [root             ][INFO    ][27011] Error! Ending server side websocket connection. Reason = 
2016-07-20 19:09:24,328 [tornado.access   ][INFO    ][27011] 200 POST / (127.0.0.1) 475.39ms
2016-07-20 19:09:24,329 [salt.utils.job   ][ERROR   ][27514] Returner 'postgres' does not support function returner
2016-07-20 19:09:24,330 [salt.utils.process][ERROR   ][27514] An un-handled exception from the multiprocessing process 'SignalHandlingMultiprocessingProcess-5:4:1' was caught:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/salt/utils/process.py", line 640, in _run
    return self._original_run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/salt/client/mixins.py", line 440, in _proc_function
    return self.low(fun, low)
  File "/usr/local/lib/python2.7/dist-packages/salt/client/mixins.py", line 255, in low
    return self._low(fun, low)
  File "/usr/local/lib/python2.7/dist-packages/salt/client/mixins.py", line 387, in _low
    mminion=self.mminion,
  File "/usr/local/lib/python2.7/dist-packages/salt/utils/job.py", line 100, in store_job
    raise KeyError(emsg)
KeyError: "Returner 'postgres' does not support function returner"
```
### Setup

```
returner.postgres.host: '127.0.0.1'
returner.postgres.port: 5432
returner.postgres.user: 'postgres'
returner.postgres.passwd: 'salt'
returner.postgres.db: 'salt'


alternative.returner.postgres.host: '127.0.0.1'
alternative.returner.postgres.user: 'postgres'
alternative.returner.postgres.passwd: 'salt'
alternative.returner.postgres.db: 'salt'
alternative.returner.postgres.port: 5432

master_job_cache: postgres
```
### Steps to Reproduce Issue

(Include debug logs if possible and relevant.)

```
2016-07-20 19:09:23,852 [tornado.access   ][INFO    ][27011] 204 OPTIONS / (127.0.0.1) 0.30ms
2016-07-20 19:09:24,094 [salt.loaded.int.runners.vistara][ERROR   ][27514] vistara config has not been specificed in the Salt master config. See documentation for this runner.
2016-07-20 19:09:24,328 [root             ][INFO    ][27011] Error! Ending server side websocket connection. Reason = 
2016-07-20 19:09:24,328 [tornado.access   ][INFO    ][27011] 200 POST / (127.0.0.1) 475.39ms
2016-07-20 19:09:24,329 [salt.utils.job   ][ERROR   ][27514] Returner 'postgres' does not support function returner
2016-07-20 19:09:24,330 [salt.utils.process][ERROR   ][27514] An un-handled exception from the multiprocessing process 'SignalHandlingMultiprocessingProcess-5:4:1' was caught:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/salt/utils/process.py", line 640, in _run
    return self._original_run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/salt/client/mixins.py", line 440, in _proc_function
    return self.low(fun, low)
  File "/usr/local/lib/python2.7/dist-packages/salt/client/mixins.py", line 255, in low
    return self._low(fun, low)
  File "/usr/local/lib/python2.7/dist-packages/salt/client/mixins.py", line 387, in _low
    mminion=self.mminion,
  File "/usr/local/lib/python2.7/dist-packages/salt/utils/job.py", line 100, in store_job
    raise KeyError(emsg)
KeyError: "Returner 'postgres' does not support function returner"
```
### Versions Report

```
Salt Version:
           Salt: 2016.3.0-572-g9f42882

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.11+ (default, Apr 17 2016, 14:00:29)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.6.0
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by Ch3LL** [comment]
@meagon can you clarify when you are seeing this error? Are you running a particular command?

**Comment by arount** [comment]
Pretty sure my PR https://github.com/saltstack/salt/pull/40223 fix it. (needs more infos to be really confident, but, it looks like)

**Comment by Ch3LL** [comment]
@meagon want to give @arount 's fix a try?

**Comment by arount** [comment]
Well, I may admit I'm this kind of guys who likes to have not too much open prs / issues, so @Ch3LL sorry but i take the lead for this time:

@meagon can you please close or give updates to this issue ;)

_sorry to be that guy_

**Comment by rallytime** [comment]
I'll close this for now since we didn't hear back. We can certainly open this again if needed. Thanks everyone!
