### ISSUE TITLE
salt-ssh doesn't exit on pillar conflict

### ISSUE THREAD

**Issue by edgan** [saltstack/salt#34855]
### Description of Issue/Question

  I had created a conflict in the pillar top.sls. When I ran salt-ssh it threw an error, but continued the run and made changes based on the lack of pillars. I expect it to exit and not continue the run.
### Setup

```
pillar/top.sls:
  'sensu-sensu-*.inf.us-west-1.aws.acme.com':
    - redis.us-west-1.inf.sensu.common

  'sensu-sensu-*.inf.us-east-1.aws.acme.com':
    - redis.us-east-1.inf.sensu.common

  'sensu-sensu-*.inf.us-west-1.aws.acme.com':
    - ssl.public.star_inf_us-west-1_aws_acme_com

  'sensu-sensu-*.inf.us-east-1.aws.acme.com':
    - ssl.public.star_inf_us-east-1_aws_acme_com
```
### Steps to Reproduce Issue

```
salt-ssh 'jenkins-jenkins-master-01.inf.us-east-1.aws.acme.com' state.highstate
[ERROR   ] Pillar rendering failed for minion jenkins-jenkins-master-01.inf.us-east-1.aws.acme.com:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/pillar/__init__.py", line 413, in get_tops
    _pillar_rend=True
  File "/usr/lib/python2.7/site-packages/salt/template.py", line 95, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/usr/lib/python2.7/site-packages/salt/renderers/yaml.py", line 58, in render
    raise SaltRenderError(exc)
SaltRenderError: Conflicting ID 'sensu-sensu-*.inf.us-west-1.aws.acme.com'
[CRITICAL] Pillar render error: Rendering Primary Top file failed, render error:
Conflicting ID 'sensu-sensu-*.inf.us-west-1.aws.acme.com'
[ERROR   ] Pillar rendering failed for minion jenkins-jenkins-master-01.inf.us-east-1.aws.acme.com:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/pillar/__init__.py", line 413, in get_tops
    _pillar_rend=True
  File "/usr/lib/python2.7/site-packages/salt/template.py", line 95, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/usr/lib/python2.7/site-packages/salt/renderers/yaml.py", line 58, in render
    raise SaltRenderError(exc)
SaltRenderError: Conflicting ID 'sensu-sensu-*.inf.us-west-1.aws.acme.com'
[CRITICAL] Pillar render error: Rendering Primary Top file failed, render error:
Conflicting ID 'sensu-sensu-*.inf.us-west-1.aws.acme.com'
jenkins-jenkins-master-01.inf.us-east-1.aws.acme.com:
  Name: /etc/resolv.conf - Function: file.managed - Result: Changed
  Name: /etc/sensu/config.json - Function: file.managed - Result: Changed
----------
          ID: sensu_ssl_client_cert
    Function: file.managed
        Name: /etc/sensu/ssl/client/cert.pem
      Result: False
     Comment: Pillar sensu_ssl:client:cert does not exist
     Started: 11:10:43.560265
    Duration: 0.363 ms
     Changes:

Summary for jenkins-jenkins-master-01.inf.us-east-1.aws.acme.com
-------------
Succeeded: 52 (changed=2)
Failed:     1
-------------
Total states run:     53
```
### Versions Report

2016.3.1

**Comment by Ch3LL** [comment]
@edgan can you post your sls file? I am interested in how you are calling the pillar in your sls file and whether that would cause it to continue to run or not.

**Comment by edgan** [comment]
The error isn't about the pillar contents. It is about duplicating the matching title in the top.sls.

Conflicting ID 'sensu-sensu-*.inf.us-west-1.aws.acme.com'

```
pillar/top.sls:
  'sensu-sensu-*.inf.us-west-1.aws.acme.com':    <---------------
    - redis.us-west-1.inf.sensu.common

  'sensu-sensu-*.inf.us-west-1.aws.acme.com':    <---------------
    - ssl.public.star_inf_us-west-1_aws_acme_com
```

**Comment by Ch3LL** [comment]
@edgan ahh you are right. Apologies for some reason when i did my initial test case I saw the state file run even with the conflicting IDs. I must have been doing something incorrectly. But yes you are right thanks for correcting and clarifying for me. 

Here it is show exiting not using salt-ssh:

```
 ch3ll@ch3ll-master  ~  sudo salt '10*' state.sls test         
10.1.45.255:
    Data failed to compile:
----------
    Pillar failed to render with the following messages:
----------
    Rendering Primary Top file failed, render error:
Conflicting ID 'sensu-sensu-*.inf.us-west-1.aws.acme.com'
ERROR: Minions returned with non-zero exit code
```

and with salt-ssh and does not exit on a failure:

```
 ✘ ch3ll@ch3ll-master  ~  sudo salt-ssh 'ch3ll-m*' state.sls test
[ERROR   ] Pillar rendering failed for minion ch3ll-minion01: 
Traceback (most recent call last):
  File "/home/ch3ll/git/salt/salt/pillar/__init__.py", line 413, in get_tops
    _pillar_rend=True
  File "/home/ch3ll/git/salt/salt/template.py", line 95, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/home/ch3ll/git/salt/salt/renderers/yaml.py", line 58, in render
    raise SaltRenderError(exc)
SaltRenderError: Conflicting ID 'sensu-sensu-*.inf.us-west-1.aws.acme.com'
[CRITICAL] Pillar render error: Rendering Primary Top file failed, render error:
Conflicting ID 'sensu-sensu-*.inf.us-west-1.aws.acme.com'
[ERROR   ] Pillar rendering failed for minion ch3ll-minion01: 
Traceback (most recent call last):
  File "/home/ch3ll/git/salt/salt/pillar/__init__.py", line 413, in get_tops
    _pillar_rend=True
  File "/home/ch3ll/git/salt/salt/template.py", line 95, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/home/ch3ll/git/salt/salt/renderers/yaml.py", line 58, in render
    raise SaltRenderError(exc)
SaltRenderError: Conflicting ID 'sensu-sensu-*.inf.us-west-1.aws.acme.com'
[CRITICAL] Pillar render error: Rendering Primary Top file failed, render error:
Conflicting ID 'sensu-sensu-*.inf.us-west-1.aws.acme.com'
ch3ll-minion01:
----------
          ID: create
    Function: file.managed
        Name: /tmp/qux
      Result: True
     Comment: File /tmp/qux exists with proper permissions. No changes made.
     Started: 09:21:47.442830
    Duration: 9.583 ms
     Changes:   

Summary for ch3ll-minion01
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
```
