### ISSUE TITLE
salt.wheel key.delete isn't functioning (problem like #25318) (but #31112 works for me)

### ISSUE THREAD

**Issue by rburkholder** [saltstack/salt#34883]
### Description of Issue/Question

running salt state file very similar to what is in https://github.com/saltstack/salt/issues/25318

```
master:/srv# salt-call -l debug state.sls deletekey
.....
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[DEBUG   ] Connecting to master. Attempt 1 of 1
.......
[DEBUG   ] Rendered data from file: /var/cache/salt/minion/files/base/deletekey.sls:
# https://github.com/saltstack/salt/issues/25318
delete_key:
  salt.wheel:
    - name: key.delete
    - match: myminion



[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Results of YAML rendering:
OrderedDict([('delete_key', OrderedDict([('salt.wheel', [OrderedDict([('name', 'key.delete')]), OrderedDict([('match', 'myminion')])])]))])
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/deletekey.sls' using 'yaml' renderer: 0.00467395782471
[DEBUG   ] LazyLoaded salt.wheel
[INFO    ] Running state [key.delete] at time 11:22:29.335327
[INFO    ] Executing state salt.wheel for key.delete
[DEBUG   ] LazyLoaded saltutil.wheel
[DEBUG   ] LazyLoaded key.delete
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: myminion
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/minion/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/minion/master_event_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/minion/master_event_pull.ipc
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_a7f7806b68_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_a7f7806b68_pull.ipc
[DEBUG   ] LazyLoaded nested.output
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1703, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1649, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/states/saltmod.py", line 624, in wheel
    out = __salt__['saltutil.wheel'](name, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/saltutil.py", line 1067, in wheel
    return wclient.cmd(_fun, kwarg=kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/wheel/__init__.py", line 124, in cmd
    return super(WheelClient, self).cmd(fun, arg, pub_data, kwarg)
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 231, in cmd
    return self.low(fun, low)
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 369, in low
    mminion=self.mminion,
  File "/usr/lib/python2.7/dist-packages/salt/utils/job.py", line 31, in store_job
    job_cache = opts['master_job_cache']
KeyError: 'master_job_cache'

[INFO    ] Completed state [key.delete] at time 11:22:31.595964 duration_in_ms=2260.637
[DEBUG   ] File /var/cache/salt/minion/accumulator/140151610679632 does not exist, no need to cleanup.
[DEBUG   ] LazyLoaded config.option
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'myminion', 'tcp://10.152.0.10:4506', 'aes')
......
[DEBUG   ] LazyLoaded highstate.output
local:
----------
          ID: delete_key
    Function: salt.wheel
        Name: key.delete
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1703, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1649, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/saltmod.py", line 624, in wheel
                  out = __salt__['saltutil.wheel'](name, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/saltutil.py", line 1067, in wheel
                  return wclient.cmd(_fun, kwarg=kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/wheel/__init__.py", line 124, in cmd
                  return super(WheelClient, self).cmd(fun, arg, pub_data, kwarg)
                File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 231, in cmd
                  return self.low(fun, low)
                File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 369, in low
                  mminion=self.mminion,
                File "/usr/lib/python2.7/dist-packages/salt/utils/job.py", line 31, in store_job
                  job_cache = opts['master_job_cache']
              KeyError: 'master_job_cache'
     Started: 11:22:29.335327
    Duration: 2260.637 ms
     Changes:

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
```
```
master:/srv# salt --versions-report
Salt Version:
           Salt: 2016.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 2.0.5
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.3.7
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jun 29 2016, 08:18:26)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.4

System Versions:
           dist: debian stretch/sid
        machine: x86_64
        release: 4.6.0-1-amd64
         system: Linux
        version: debian stretch/sid

```

**Comment by Ch3LL** [comment]
@rburkholder looks like this is workign in 2016.3.1 now. Can you verify?

**Comment by rburkholder** [comment]
I am able to verify that this is working in 2016.3.1.  Thank you.
