### ISSUE TITLE
Cannot start proxy minion due to keyerror in grains

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#34908]
### Description of Issue/Question
When attempting to start the proxy minion the minion fails to start there is a keyerror traceback.

### Setup
1. setup a proxy minion

### Steps to Reproduce Issue
1. try to run the proxy minion:

`salt-proxy --proxyid=p8001 -l debug`
```
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[ERROR   ] Proxy Minion failed to start: 
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 200, in proxy_minion_process
    proxyminion.start()
  File "/usr/lib/python2.7/site-packages/salt/cli/daemons.py", line 526, in start
    self.minion.tune_in()
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1964, in tune_in
    self.sync_connect_master()
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 898, in sync_connect_master
    raise six.reraise(*future_exception)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 908, in connect_master
    yield self._post_master_init(master)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 879, in run
    yielded = self.gen.send(value)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 2964, in _post_master_init
    self.functions, self.returners, self.function_errors, self.executors = self._load_modules()
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1084, in _load_modules
    self.opts['grains'] = salt.loader.grains(self.opts, force_refresh, proxy=proxy)
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 704, in grains
    ret = fun()
  File "/usr/lib/python2.7/site-packages/salt/grains/core.py", line 1494, in os_data
    grains['osfinger'] = '{0}-{1}'.format(grains[os_name], grains['osrelease_info'][0])
KeyError: 'osfullname'
[WARNING ] ** Restarting proxy minion **
[INFO    ] Sleeping random_reauth_delay of 6 seconds
```

### Versions Report

```
Salt Version:
           Salt: 2016.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.4.5.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

**Comment by cachedout** [comment]
Fixed via #34910
