### ISSUE TITLE
Beacon error being reported in logs

### ISSUE THREAD

**Issue by centromere** [saltstack/salt#34978]
The following is appearing in `/var/log/salt/minion`:

```
2016-07-26 21:02:13,172 [salt.loader      ][ERROR   ][29383] Failed to import beacons network_settings, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1296, in _load_module
    ), fn_, fpath, desc)
  File "/usr/lib/python2.7/dist-packages/salt/beacons/network_settings.py", line 30, in <module>
    IP = IPDB()
NameError: name 'IPDB' is not defined
```

```
Salt Version:
           Salt: 2016.3.1
 
Dependency Versions:
           cffi: 1.7.0
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.24.0
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-92-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by Ch3LL** [comment]
@centromere are you seeing this when using the network settings beacon? 

Also can you run the following: `python -c "from pyroute2.ipdb import IPDB"`

I'm not seeing that same error when I run in a python interpreter with pyroute2 version0.3.15

``
>>> from pyroute2.ipdb import IPDB
>>> IP = IPDB()
>>> 
```

**Comment by centromere** [comment]
I see this when the salt-minion starts up. I do not use the network settings beacon.

```
root@salt01-test:~# python -c "from pyroute2.ipdb import IPDB"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named pyroute2.ipdb
```

**Comment by svinota** [comment]
pls try
```
from pyroute2 import IPDB
```

«root» imports (like that, `from pyroute2 import …`) are intended to provide a fixed public API that would work despite any internal module layout changes

**Comment by svinota** [comment]
Looks like the fix was merged.

@centromere — anyway, try to use 0.3.22 on LTS like Ubuntu 14 / kernel 3.x, otherwise there may come other surprises.
