### ISSUE TITLE
KeyError on npm.installed

### ISSUE THREAD

**Issue by scott-w** [saltstack/salt#34982]
### Description of Issue/Question

When running `npm.installed` on a minion where `nodejs` isn't installed, i get the following error:

```
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 227, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 69, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 236, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 138, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 523, in highstate
    whitelist=kwargs.get('whitelist')
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2968, in call_highstate
    return self.state.call_high(high)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2067, in call_high
    ret = dict(list(disabled.items()) + list(self.call_chunks(chunks).items()))
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1623, in call_chunks
    running = self.call_chunk(low, running, chunks)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1858, in call_chunk
    running = self.call_chunk(chunk, running, chunks)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1858, in call_chunk
    running = self.call_chunk(chunk, running, chunks)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1858, in call_chunk
    running = self.call_chunk(chunk, running, chunks)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1858, in call_chunk
    running = self.call_chunk(chunk, running, chunks)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1769, in call_chunk
    self._mod_init(low)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 612, in _mod_init
    self.states['{0}.{1}'.format(low['state'], low['fun'])]  # pylint: disable=W0106
  File "/usr/lib/python2.7/dist-packages/salt/utils/lazy.py", line 90, in __getitem__
    raise KeyError(key)
KeyError: 'npm.installed'
```

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

```yaml
nodejs:
  pkg:
    - installed

grunt-cli:
  npm.installed:
    - require:
      - pkg: nodejs
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

Try to run an `npm.installed` state on a machine without `nodejs`. The issue is resolved by installing NodeJS manually.

Another point is that the state log doesn't include any reference to `pkg.installed` for `nodejs` - I'm wondering if it's failed at the point of parsing the file.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
                  Salt: 2015.5.3
                Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1trusty1
```

**Comment by Ch3LL** [comment]
@scott-w what OS are you attempting to install this on? I am wondering if you are getting an error when attempting to install nodejs but its not showing up for you. On 2016.3 testing I do only see two packages getting installed which does not include npm.

```
----------
          ID: nodejs
    Function: pkg.installed
      Result: True
     Comment: The following packages were installed/updated: nodejs
     Started: 10:21:31.819654
    Duration: 176952.021 ms
     Changes:   
              ----------
              libuv:
                  ----------
                  new:
                      1:0.10.34-2.el7
                  old:
              nodejs:
                  ----------
                  new:
                      0.10.42-4.el7
                  old:
----------
```

Can you run your state with `salt-call --local` that will give use more debug information as to why this is not working for your steup.

**Comment by scott-w** [comment]
Hi @Ch3LL, thanks for getting back to me.

I'll have to do this when I get back into the office in a couple of weeks as I've just started my annual holiday.

**Comment by Ch3LL** [comment]
no worries. just let us know thanks :)

**Comment by scott-w** [comment]
Hi @Ch3LL, I've got back but I'm struggling to setup the state to be run independently.

I'm able to do `salt-call --local pkg.install nodejs` and everything works fine. Once NodeJS is installed, the `npm.installed` state works perfectly. The issue is that the state file itself fails if, and only if, the `nodejs` package isn't installed.

The OS is Ubuntu 14.04 hosted on AWS. This also happens on a (near enough) bare install as well as on a server with existing packages on.

**Comment by Ch3LL** [comment]
@scott-w when attempting to replicating this I noticed that the `npm` command was not install with the nodejs package. When I changed the pkg.installed state to npm it worked. Are you setting up a repo in another step in your state that includes npm in the nodejs package?
