### ISSUE TITLE
`states.pkg.py` can't handle Gentoo's/Portage's special package version format

### ISSUE THREAD

**Issue by eliasp** [saltstack/salt#35006]
### Description of Issue/Question

Gentoo allows to have very specific pkg version identifier in `pkgs` of `pkg.installed`. Using those, `states.pkg`'s final installation verification goes wrong, as `_get_comparison_spec()` is unable to handle this complex format:

```
          ID: sys-apps/systemd
    Function: pkg.installed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib64/python2.7/site-packages/salt/state.py", line 1723, in call
                  **cdata['kwargs'])
                File "/usr/lib64/python2.7/site-packages/salt/loader.py", line 1650, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib64/python2.7/site-packages/salt/states/pkg.py", line 1292, in installed
                  ignore_epoch=ignore_epoch)
                File "/usr/lib64/python2.7/site-packages/salt/states/pkg.py", line 549, in _verify_install
                  oper, verstr = _get_comparison_spec(pkgver)
                File "/usr/lib64/python2.7/site-packages/salt/states/pkg.py", line 136, in _get_comparison_spec
                  'Invalid version specification \'{0}\'.'.format(pkgver)
              CommandExecutionError: Invalid version specification '~>=230[curl,importd,nat,gcrypt,lzma]'.
     Started: 22:37:09.670599
    Duration: 209119.81 ms
     Changes:   
----------

```
### Setup

State to reproduce this issue:

``` SaltStack
sys-apps/util-linux:                                                                                                                 
  pkg.installed:                                                                                                                     
    - pkgs:                                                                                                                          
      - sys-apps/util-linux: '~2.28'                                                                                                 

sys-apps/systemd:                                                                                                                    
  pkg.installed:                                                                                                                     
    - pkgs:                                                                                                                          
      - sys-apps/systemd: '~>=230[curl,importd,nat,gcrypt,lzma]'                                                                     
    - require:                                                                                                                       
      - pkg: sys-apps/util-linux                                                                                                     
```
### Steps to Reproduce Issue

Apply the state above on a Gentoo system
### Versions Report

```
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.10 (default, Jul  8 2016, 16:19:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: gentoo 2.2 
        machine: x86_64
        release: 4.1.15
         system: Linux
        version: Gentoo Base System 2.2
```

**Comment by eliasp** [comment]
It looks like it boils down to the arch/keyword "operator" `~`.

**Success:**
```
# salt-call -l info state.single pkg.installed name="sys-apps/systemd" pkgs='[{"sys-apps/systemd": ">=230[curl,importd,nat,gcrypt,lzma]"}]'
[ERROR   ] Could not determine init location from command line: (-bash)
[INFO    ] Loading fresh modules for state activity
[INFO    ] Running state [sys-apps/systemd] at time 07:34:57.876455
[INFO    ] Executing state pkg.installed for sys-apps/systemd
[INFO    ] All specified packages are already installed and are at the desired version
[INFO    ] Completed state [sys-apps/systemd] at time 07:34:59.325471 duration_in_ms=1449.016
local:
----------
          ID: sys-apps/systemd
    Function: pkg.installed
      Result: True
     Comment: All specified packages are already installed and are at the desired version
     Started: 07:34:57.876455
    Duration: 1449.016 ms
     Changes:   

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
```

**Failure:**
```
# salt-call -l info state.single pkg.installed name="sys-apps/systemd" pkgs='[{"sys-apps/systemd": "~>=230[curl,importd,nat,gcrypt,lzma]"}]'                              
[ERROR   ] Could not determine init location from command line: (-bash)
[INFO    ] Loading fresh modules for state activity
[INFO    ] Running state [sys-apps/systemd] at time 07:31:02.259119
[INFO    ] Executing state pkg.installed for sys-apps/systemd
[ERROR   ] Invalid version specification '~>=230[curl,importd,nat,gcrypt,lzma]'.
[INFO    ] Completed state [sys-apps/systemd] at time 07:31:03.893158 duration_in_ms=1634.039
local:
----------
          ID: sys-apps/systemd
    Function: pkg.installed
      Result: False
     Comment: Invalid version specification '~>=230[curl,importd,nat,gcrypt,lzma]'.
     Started: 07:31:02.259119
    Duration: 1634.039 ms
     Changes:   

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
```

**Comment by Ch3LL** [comment]
@eliasp yes it looks like the `~` is causing the issue. I'm not entirely familiar with gentoo but from what i gathered from a quick google search the `~` represents an unstable package. are there other special characters we might want to ensure we are able to handle with gentoo packages?

**Comment by eliasp** [comment]
Yes, `~` denotes an "unstable" package.
While this could be added as another special case to the pkg state, it might make sense to delegate this version comparison to the `ebuild` execution module which could make use of Portage's Python API (which is already used in the `ebuild` execution module for many other things) as there are quite a few more special cases (e.g. SLOT upgrades) for which I'm not sure whether they're properly handled yet.
