### ISSUE TITLE
Harden `modules.portage_config` against invalid pkg/version combinations

### ISSUE THREAD

**Issue by eliasp** [saltstack/salt#35004]
### Description of Issue/Question

When specifying a wrong pkg/version combination (e.g. `'sys-apps/systemd': '~2.28'` which was here a typo where I actually wanted to use `'sys-apps/util-linux': '~2.28'`) `modules.portage_config` will fail with a backtrace:

```
          ID: sys-apps/util-linux
    Function: pkg.installed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib64/python2.7/site-packages/salt/state.py", line 1723, in call
                  **cdata['kwargs'])
                File "/usr/lib64/python2.7/site-packages/salt/loader.py", line 1650, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib64/python2.7/site-packages/salt/states/pkg.py", line 1208, in installed
                  **kwargs)
                File "/usr/lib64/python2.7/site-packages/salt/modules/ebuild.py", line 643, in install
                  ['~ARCH'])
                File "/usr/lib64/python2.7/site-packages/salt/modules/portage_config.py", line 348, in append_to_package_conf
                  append_to_package_conf(conf, string=atom, overwrite=overwrite)
                File "/usr/lib64/python2.7/site-packages/salt/modules/portage_config.py", line 357, in append_to_package_conf
                  pdir = os.path.dirname(complete_file_path)
                File "/usr/lib64/python2.7/posixpath.py", line 122, in dirname
                  i = p.rfind('/') + 1
              AttributeError: 'NoneType' object has no attribute 'rfind'
     Started: 21:26:12.025851
    Duration: 1081.085 ms
     Changes
```
### Setup

Salt 2016.3.1 running on Gentoo (details see below)
### Steps to Reproduce Issue

I was able to reproduce it using the following state execution:

```
salt-call -l info state.single pkg.installed name="sys-apps/util-linux" pkgs='[{"sys-apps/systemd": "~2.28"}]'
```
### Versions Report

```
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.10 (default, Jul  8 2016, 16:19:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: gentoo 2.2 
        machine: x86_64
        release: 4.1.15
         system: Linux
        version: Gentoo Base System 2.2
```

**Comment by eliasp** [comment]
While it would be an easy fix to simply wrap `pdir = os.path.dirname(complete_file_path` in `try`/`except`, the problem itself should probably solved way earlier by checking, whether the pkg/version combination is valid, e.g. as in the case here: there's simply no version `2.28` for the pkg `sys-apps/systemd`.

**Comment by Ch3LL** [comment]
@eliasp thanks we definitely to make sure we do not stack trace here and spit out a more useful error. And I agree with your approach to have a check to see if the version and package are available.
