### ISSUE TITLE
archive.extracted leaves bad tar file in cache on failure to extract

### ISSUE THREAD

**Issue by lomeroe** [saltstack/salt#35032]
### Description of Issue/Question

If the archive.extracted state is run on a tar file that fails to extract, the "bad" file will be left in cache and future attempts to run the same archive.extracted state will always fail.  Occurs if using the external tar command or python extraction
### Setup

```
extract_archive:
  archive.extracted:
    - name: /some/place/to/extract
    - source: /badfile.tar
    - archive_format: tar
    - if_missing: /some/place/to/extract/expected.file
```
### Steps to Reproduce Issue

```
#touch /badfile.tar

#salt-call state.single archive.extracted name=/some/place/to/extract source=/badfile.tar archive_format=tar if_missing=/some/place/to/extract/expected.file
<state will fail>

#ls -al /var/cache/salt/minion/files/base
<bad archive is in cache, example above file is named "_some_place_to_extract_expected.file.tar>

#touch expected.file
#tar -cvf /badfile.tar expected.file

 #salt-call state.single archive.extracted name=/some/place/to/extract source=/badfile.tar archive_format=tar if_missing=/some/place/to/extract/expected.file
<state fails again, though now badfile.tar is actually a good file>

#rm /var/cache/salt/minion/files/base/_some_place_to_extract_expected.file.tar
 #salt-call state.single archive.extracted name=/some/place/to/extract source=/badfile.tar archive_format=tar if_missing=/some/place/to/extract/expected.file
<state succeeds>
```
### Versions Report

```
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.10.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

1) if the cache path exists, it isn't checked that it matches the file we want to extract (offending snippet from archive.py)(https://github.com/saltstack/salt/blob/c43bd8fabeedb7cd0ca8dcc345d2bbb579080e00/salt/states/archive.py#L312)

2) if an error occurs while expanding the tar file, returns are processed and the cache is never cleaned up.

It appears a similar issue would occur if keep=True initially (initial file left in cache), but later wanted to extract a new archive (the new archive would never make it to the cache to be extracted)

**Comment by Ch3LL** [comment]
@lomeroe looks like i'm able to replicate this issue on 2016.3.1. Looks like we need to do a better job at handling when to add/remove fromt eh cache when running into an error. The error i ran into when using the bad tar was:

```
local:
----------
          ID: /some/place/to/extract
    Function: archive.extracted
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/home/ch3ll/git/salt/salt/state.py", line 1723, in call
                  **cdata['kwargs'])
                File "/home/ch3ll/git/salt/salt/loader.py", line 1650, in wrapper
                  return f(*args, **kwargs)
                File "/home/ch3ll/git/salt/salt/states/archive.py", line 332, in extracted
                  with closing(tarfile.open(filename, 'r')) as tar:
                File "/usr/lib64/python2.7/tarfile.py", line 1665, in open
                  raise ReadError("file could not be opened successfully")
              ReadError: file could not be opened successfully
     Started: 11:57:00.406907
    Duration: 1564.691 ms
     Changes:   
```
