### ISSUE TITLE
Minions die with "un-handled exception from the multiprocessing process"

### ISSUE THREAD

**Issue by jwhite530** [saltstack/salt#35097]
### Description of Issue/Question
Recently I have discovered that some of my minions are becoming unresponsive when trying to do anything:

```
cn42:
    Minion did not return. [No response]
cn11:
    Minion did not return. [No response]
cn58:
    Minion did not return. [No response]
cn59:
    Minion did not return. [No response]
```

I discovered they log this error then log nothing further until the salt-minion daemon is restarted:

```
2016-07-30 15:23:24,881 [salt.utils.process][ERROR   ][73716] An un-handled exception from the multiprocessing process 'SignalHandlingMultiprocessingProcess-1:151' was caught:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/process.py", line 613, in _run
    return self._original_run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/site-packages/salt/utils/schedule.py", line 652, in handle_func
    with salt.utils.fopen(fn_, 'rb') as fp_:
  File "/usr/lib/python2.7/site-packages/salt/utils/__init__.py", line 1209, in fopen
    fhandle = open(*args, **kwargs)
IOError: [Errno 2] No such file or directory: '/var/cache/salt/minion/proc/20160730152324736016'
2016-07-30 15:23:25,060 [salt.minion      ][ERROR   ][73716] Exception [Errno 32] Broken pipe occurred in scheduled job
```

Here's another example from another minion:

```
2016-07-31 22:01:26,626 [salt.utils.process][ERROR   ][73692] An un-handled exception from the multiprocessing process 'SignalHandlingMultiprocessingProcess-1:182' was caught:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/process.py", line 613, in _run
    return self._original_run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/site-packages/salt/utils/schedule.py", line 652, in handle_func
    with salt.utils.fopen(fn_, 'rb') as fp_:
  File "/usr/lib/python2.7/site-packages/salt/utils/__init__.py", line 1209, in fopen
    fhandle = open(*args, **kwargs)
IOError: [Errno 2] No such file or directory: '/var/cache/salt/minion/proc/20160731220126606879'
2016-07-31 22:01:26,650 [salt.minion      ][ERROR   ][73692] Exception [Errno 32] Broken pipe occurred in scheduled job
```

### Setup
I have dozens of minions.  This issue seems to effect them randomly.  I cannot attribute any change to any state, schedule, version, or anything else.  They just started randomly failing.

### Versions Report
I have not been able to attribute this to a specific version.  All my minions run 2016.3.1 as does my master.

Master:

```
Salt Version:
           Salt: 2016.3.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.4.5.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

Minion:

```
Salt Version:
           Salt: 2016.3.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.13.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

**Comment by Ch3LL** [comment]
@jwhite530 did you notice this after upgrading to 2016.3? If so how did you update your packages?

**Comment by jwhite530** [comment]
@Ch3LL I can't associate it with an upgrade, I just noticed it happening.  I had problems with schedule.py in previous versions, but none that kill my minions.  It probably started when I added a few states into each minion's schedule but I can't pinpoint one of them being the problem either.  In the mean time I've abandoned Salt's scheduler entirely and removed every state that was using it.

**Comment by jwhite530** [comment]
This is still an issue and may the cause of issue 35470 as well.  I see this is still tagged with "Info Needed"  What else do you need from me?

```
Aug 11 23:41:55 cn59 salt-minion[6673]: 2016-08-11 23:41:55,513 [salt.utils.process][ERROR   ][6673] An un-handled exception from the multiprocessing process 'SignalHandlingMultiprocessingProcess-1:175' was caught:
                                        Traceback (most recent call last):
                                          File "/usr/lib/python2.7/site-packages/salt/utils/process.py", line 613, in _run
                                            return self._original_run()
                                          File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
                                            self._target(*self._args, **self._kwargs)
                                          File "/usr/lib/python2.7/site-packages/salt/utils/schedule.py", line 652, in handle_func
                                            with salt.utils.fopen(fn_, 'rb') as fp_:
                                          File "/usr/lib/python2.7/site-packages/salt/utils/__init__.py", line 1209, in fopen
                                            fhandle = open(*args, **kwargs)
                                        IOError: [Errno 2] No such file or directory: '/var/cache/salt/minion/proc/20160811234155499986'
Aug 11 23:41:55 cn59 salt-minion[6673]: 2016-08-11 23:41:55,519 [salt.minion      ][ERROR   ][6673] Exception [Errno 32] Broken pipe occurred in scheduled job
```

**Comment by Ch3LL** [comment]
@jwhite530 we really need to try to find a reproducible case which will really help to track down this issue. Would you mind sharing what you have setup in your scheduler?

**Comment by jwhite530** [comment]
I removed every non-default entry from the schedule of every one of my minions and I still have the problem.

**Comment by Ch3LL** [comment]
okay I've setup a test environment with your master/minion conf from the other issue. Just glancing at the code this might be a race condition [here](https://github.com/saltstack/salt/blob/develop/salt/utils/schedule.py#L770) where the schedule is actually getting getting handled in another thread and then deleting before it attempts to open the file. But this is only a theory at this time. I will keep checking these servers and check for both this error and see if the minion raises to 100%. I'll report back tomorrow. Thanks

**Comment by Ch3LL** [comment]
@jwhite530 okay I still haven't seen the errors or the minion dying or taking up 100% CPU. How often do you see this behavior exhibited?

Also I just am curious if you were to remove the cache on the minion side if this would resolve the issue. If you were to run `salt '*' saltutil.clear_cache` Does this help?

**Comment by jwhite530** [comment]
I haven't been paying attention lately, just blindly doing a `killall -9 salt-minion` every time I see a hint of misbehavior in them, which is every single day but not necessarily this particular issue each time.  I will keep track when I see it again.  Is there anything else I can get on my side when this happens that might be useful?

**Comment by jwhite530** [comment]
@Ch3LL,
> How often do you see this behavior exhibited?

Between Friday afternoon and now (the following Monday afternoon) I have 13 minions (of about 90) not responding.  I've only looked at 8 so far and every single one is stuck at 100% CPU usage.  They have this error:

```
Aug 19 23:17:55 cn55 salt-minion[130890]: 2016-08-19 23:17:55,246 [salt.utils.process][ERROR   ][130890] An un-handled exception from the multiprocessing process 'SignalHandlingMultiprocessingProcess-1:795' was caught:
                                          Traceback (most recent call last):
                                            File "/usr/lib/python2.7/site-packages/salt/utils/process.py", line 613, in _run
                                              return self._original_run()
                                            File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
                                              self._target(*self._args, **self._kwargs)
                                            File "/usr/lib/python2.7/site-packages/salt/utils/schedule.py", line 652, in handle_func
                                              with salt.utils.fopen(fn_, 'rb') as fp_:
                                            File "/usr/lib/python2.7/site-packages/salt/utils/__init__.py", line 1209, in fopen
                                              fhandle = open(*args, **kwargs)
                                          IOError: [Errno 2] No such file or directory: '/var/cache/salt/minion/proc/20160819231755230079'
Aug 19 23:17:55 cn55 salt-minion[130890]: 2016-08-19 23:17:55,280 [salt.minion      ][ERROR   ][130890] Exception [Errno 32] Broken pipe occurred in scheduled job
```

**Comment by diego-XA** [comment]
I am also having this problem with minions 2016.3.1.
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/process.py", line 613, in _run
    return self._original_run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/utils/schedule.py", line 652, in handle_func
    with salt.utils.fopen(fn_, 'rb') as fp_:
  File "/usr/lib/python2.7/dist-packages/salt/utils/__init__.py", line 1209, in fopen
    fhandle = open(*args, **kwargs)
IOError: [Errno 2] No such file or directory: '/var/cache/salt/minion/proc/20160823131707587948'
```

Also I have minions with 2016.3.2 without that error but that get hung with an unfinished state and using 100% CPU

**Comment by jwhite530** [comment]
I upgraded my master and all minions to 2016.3.3.  The issue is still present in this version.

**Comment by Ch3LL** [comment]
sincere apologies on letting this issue get off my radar. Thanks for all the additional information @jwhite530 and attempting to upgrade salt and see if the behavior was exhibited differently. 

i'm gonna get a couple more people in on this issue to help determine where this issue is so we can get a resolution for you.

ping @cachedout @rallytime any thoughts on this issue? I did speak with rallytime a while back and we did look at the code [here](https://github.com/saltstack/salt/blob/develop/salt/utils/schedule.py#L770) that I referenced earlier and it looks like maybe the salt.utils.fopenmigth need to be in a try block  due to a possible race condition where `if not os.path.exists(fn_)` is never hit because the file then gets deleted in another thread right before attempting to open the file where salt.utils.fopen is called? What are you guys thoughts? any other information we could gather from @jwhite530 to help get this issue further along thanks.

**Comment by rallytime** [comment]
Hrm. This is a tricky one and I don't have any other thoughts on this one at this time, unless some one who is seeing this issue can wrap the `with salt.utils.fopen` block of code in a `try/except` as @Ch3LL referenced above to see if that helps solve at least part of this issue and can post their results. @cachedout Might have more to say on this than I do, however.

**Comment by cachedout** [comment]
I think @Ch3LL is exactly right in her analysis that this is a concurrency issue.

I'd like to know if if `multiprocessing: False` is set in any of these minion configs.

I'd also like to find a volunteer to apply this patch which should do nothing but add a little bit of logging before the crash:

```
diff --git a/salt/utils/schedule.py b/salt/utils/schedule.py
index e0b5b8c..a7b83f8 100644
--- a/salt/utils/schedule.py
+++ b/salt/utils/schedule.py
@@ -628,6 +628,11 @@ class Schedule(object):
         '''
         Execute this method in a multiprocess or thread
         '''
+        import traceback
+        if multiprocessing_enabled:
+            log.debug('schedule process id {0} and stack {1}'.format(os.getpid(), traceback.extract_stack()))
+        else:
+            log.debug('schedule thread id {0} and traceback {0}'.format(threading.current_thread(), traceback.extract_stack()))
         if salt.utils.is_windows():
             # Since function references can't be pickled and pickling
             # is required when spawning new processes on Windows, regenerate
```

Any takers?

**Comment by diego-treitos** [comment]
I dont have `multiprocessing: False` in any minion.

The last one I got using 100% of the CPU was dumping this in the logs:

```
2016-03-28 18:38:20,198 [salt.scripts     ][ERROR   ][17987] Attempt to authenticate with the salt master failed
2016-03-28 18:38:20,200 [salt.scripts     ][WARNING ][17987] ** Restarting minion **
```
The "funny" thing is that this minion is a version `2015.5.3 (Lithium)` with a master `2016.3.2 (Boron)`.

On the other hand I could execute commands there. Actually I am finding the minions using 100% of cpu by using `salt '*' cmd.run uptime` so I can see the load of the server.

Not sure anymore if this is the same problem or an additional one.

**Comment by jwhite530** [comment]
No `multiprocessing: False` on any of my minions.  I've added the patch to all of my minions.  Does salt-minion need restarted for it to take effect?

**Comment by Ch3LL** [comment]
@jwhite530 yes you will need to restart the minion. Thanks

**Comment by jwhite530** [comment]
ping @Ch3LL, @cachedout 

Here's the output of a crash from a minion with the debug patch:

```
Oct 05 18:48:34 cn46 salt-minion[110318]: 2016-10-05 18:48:34,372 [salt.utils.schedule][INFO    ][110318] Running scheduled job: __mine_interval
Oct 05 18:48:34 cn46 salt-minion[110318]: 2016-10-05 18:48:34,373 [salt.utils.schedule][DEBUG   ][110318] schedule: This job was scheduled with jid_include, adding to cache (jid_include defaults to True)
Oct 05 18:48:34 cn46 salt-minion[110318]: 2016-10-05 18:48:34,373 [salt.utils.schedule][DEBUG   ][110318] schedule: This job was scheduled with a max number of 2
Oct 05 18:48:34 cn46 salt-minion[110318]: 2016-10-05 18:48:34,434 [salt.utils.schedule][INFO    ][110318] Running scheduled job: __update_grains
Oct 05 18:48:34 cn46 salt-minion[110318]: 2016-10-05 18:48:34,435 [salt.utils.schedule][DEBUG   ][110318] schedule: This job was scheduled with jid_include, adding to cache (jid_include defaults to True)
Oct 05 18:48:34 cn46 salt-minion[110318]: 2016-10-05 18:48:34,435 [salt.utils.schedule][DEBUG   ][110318] schedule: This job was scheduled with a max number of 1
Oct 05 18:48:34 cn46 salt-minion[114919]: 2016-10-05 18:48:34,457 [salt.utils.schedule][DEBUG   ][114919] schedule process id 114919 and stack [('/usr/bin/salt-minion', 26, '<module>', 'salt_minion()'), ('/usr/lib/python2.7/site-packages$salt/scripts.py', 139, 'salt_minion', 'process.start()'), ('/usr/lib64/python2.7/multiprocessing/process.py', 130, 'start', 'self._popen = Popen(self)'), ('/usr/lib64/python2.7/multiprocessing/forking.py', 126, '__init__', 'code = proces$_obj._bootstrap()'), ('/usr/lib64/python2.7/multiprocessing/process.py', 258, '_bootstrap', 'self.run()'), ('/usr/lib64/python2.7/multiprocessing/process.py', 114, 'run', 'self._target(*self._args, **self._kwargs)'), ('/usr/lib/python2.7$site-packages/salt/scripts.py', 85, 'minion_process', 'minion.start()'), ('/usr/lib/python2.7/site-packages/salt/cli/daemons.py', 349, 'start', 'self.minion.tune_in()'), ('/usr/lib/python2.7/site-packages/salt/minion.py', 2068, 'tune_in'$ 'self.io_loop.start()'), ('/usr/lib64/python2.7/site-packages/zmq/eventloop/ioloop.py', 151, 'start', 'super(ZMQIOLoop, self).start()'), ('/usr/lib64/python2.7/site-packages/tornado/ioloop.py', 812, 'start', 'self._run_callback(timeout.$allback)'), ('/usr/lib64/python2.7/site-packages/tornado/ioloop.py', 591, '_run_callback', 'ret = callback()'), ('/usr/lib64/python2.7/site-packages/tornado/stack_context.py', 274, 'null_wrapper', 'return fn(*args, **kwargs)'), ('/usr/li$64/python2.7/site-packages/tornado/ioloop.py', 1019, '_run', 'return self.callback()'), ('/usr/lib/python2.7/site-packages/salt/minion.py', 2052, 'handle_schedule', 'self.process_schedule(self, loop_interval)'), ('/usr/lib/python2.7/site$packages/salt/minion.py', 355, 'process_schedule', 'minion.schedule.eval()'), ('/usr/lib/python2.7/site-packages/salt/utils/schedule.py', 1224, 'eval', 'proc.start()'), ('/usr/lib/python2.7/site-packages/salt/utils/process.py', 662, 'sta$t', 'super(SignalHandlingMultiprocessingProcess, self).start()'), ('/usr/lib64/python2.7/multiprocessing/process.py', 130, 'start', 'self._popen = Popen(self)'), ('/usr/lib64/python2.7/multiprocessing/forking.py', 126, '__init__', 'code $ process_obj._bootstrap()'), ('/usr/lib64/python2.7/multiprocessing/process.py', 258, '_bootstrap', 'self.run()'), ('/usr/lib/python2.7/site-packages/salt/utils/process.py', 616, '_run', 'return self._original_run()'), ('/usr/lib64/pytho$2.7/multiprocessing/process.py', 114, 'run', 'self._target(*self._args, **self._kwargs)'), ('/usr/lib/python2.7/site-packages/salt/utils/schedule.py', 633, 'handle_func', "log.debug('schedule process id {0} and stack {1}'.format(os.getpi$(), traceback.extract_stack()))")]
Oct 05 18:48:34 cn46 salt-minion[114919]: 2016-10-05 18:48:34,461 [salt.utils.process][ERROR   ][114919] An un-handled exception from the multiprocessing process 'SignalHandlingMultiprocessingProcess-1:64' was caught:
                                          Traceback (most recent call last):
                                            File "/usr/lib/python2.7/site-packages/salt/utils/process.py", line 616, in _run
                                              return self._original_run()
                                            File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
                                              self._target(*self._args, **self._kwargs)
                                            File "/usr/lib/python2.7/site-packages/salt/utils/schedule.py", line 680, in handle_func
                                              with salt.utils.fopen(fn_, 'rb') as fp_:
                                            File "/usr/lib/python2.7/site-packages/salt/utils/__init__.py", line 1221, in fopen
                                              fhandle = open(*args, **kwargs)
                                          IOError: [Errno 2] No such file or directory: '/var/cache/salt/minion/proc/20161005184834422102'
Oct 05 18:48:34 cn46 salt-minion[114919]: 2016-10-05 18:48:34,489 [salt.minion      ][ERROR   ][114919] Exception [Errno 32] Broken pipe occurred in scheduled job
```

**Comment by cachedout** [comment]
@jwhite530 Could I get you to give this a shot? https://github.com/saltstack/salt/pull/37064
