### ISSUE TITLE
salt-cloud on fedora 24 is broken

### ISSUE THREAD

**Issue by toanju** [saltstack/salt#35090]
### Description of Issue/Question
salt-cloud -Q
```
[DEBUG   ] Failed to execute 'openstack.list_nodes()' while querying for running nodes: 'running'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 2369, in run_parallel_map_providers_query
    cloud.clouds[data['fun']]()
  File "/usr/lib/python2.7/site-packages/salt/cloud/libcloudfuncs.py", line 444, in list_nodes
    'state': node_state(node.state)
  File "/usr/lib/python2.7/site-packages/salt/cloud/libcloudfuncs.py", line 68, in node_state
    return states[id_]
KeyError: 'running'
```
### Setup
sudo ./bootstrap-salt.sh -P -L -X git v2016.3.2
(on Fedora 24)

### Steps to Reproduce Issue
* bootstrap salt
* create a default salt-cloud provider and profiles for openstack
* deploy a VM
* run `salt-cloud -Q -l debug`

### Versions Report
Salt Version:
            Salt: 2016.3.2
 
Dependency Versions:
```
 Apache Libcloud: 1.1.0
            cffi: 1.5.2
        cherrypy: 3.5.0
        dateutil: 2.5.2
           gitdb: 0.6.4
       gitpython: 1.0.1
           ioflo: Not Installed
          Jinja2: 2.8
         libgit2: Not Installed
         libnacl: Not Installed
        M2Crypto: 0.21.1
            Mako: 1.0.3
    msgpack-pure: Not Installed
  msgpack-python: 0.4.7
    mysql-python: Not Installed
       pycparser: 2.14
        pycrypto: 2.6.1
          pygit2: Not Installed
          Python: 2.7.12 (default, Jul 18 2016, 10:55:51)
    python-gnupg: Not Installed
          PyYAML: 3.11
           PyZMQ: 14.7.0
            RAET: Not Installed
           smmap: 0.9.0
         timelib: Not Installed
         Tornado: 4.4.1
             ZMQ: 4.1.4
 
System Versions:
            dist: fedora 24 Twenty Four
         machine: x86_64
         release: 4.6.4-301.fc24.x86_64
          system: Linux
         version: Fedora 24 Twenty Four
```
### Solution 
```
--- /usr/lib/python2.7/site-packages/salt/cloud/libcloudfuncs.py.bak	2016-08-01 14:00:42.038310779 +0200
+++ /usr/lib/python2.7/site-packages/salt/cloud/libcloudfuncs.py	2016-08-01 14:03:19.683636299 +0200
@@ -440,7 +440,7 @@
             'private_ips': node.private_ips,
             'public_ips': node.public_ips,
             'size': node.size,
-            'state': node_state(node.state)
+            'state': node.state
         }
     return ret
```
seems to help with libcloud 1.1.0; afterward querying and deletion of VMs is working again

**Comment by toanju** [comment]
k, this was changed in libcloud 1.0.0

see
http://libcloud.readthedocs.io/en/v1.0.0/_modules/libcloud/compute/types.html
http://libcloud.readthedocs.io/en/v0.20.1/_modules/libcloud/compute/types.html

**Comment by toanju** [comment]
Oh, sorry haven't seen that one. Will give it a try later today.

**Comment by toanju** [comment]
Actually had some time right now. Works like a charm, thanks! Its a pity, that #33518 didn't find its way into v2016.3.2

**Comment by Ch3LL** [comment]
ping @rallytime is it possible to get #33518 into 2016.3 looks like its only in develop.

**Comment by rallytime** [comment]
I have marked #33518 for backporting to the 2016.3 branch.

**Comment by Ch3LL** [comment]
Awesome Thanks!
