### ISSUE TITLE
beacons modules: service fails

### ISSUE THREAD

**Issue by goestin** [saltstack/salt#35198]
### Description of Issue/Question
When i use the following beacon configuration to assign a beacon configuration from pillar, the configuration is not working. However the configuration is according to the documentation.

```
beacons:
  service:
    quagga:
      onchangeonly: True
```

The message when i run "salt-minion -l warning" is as follows:
```
[CRITICAL] The beacon errored: 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 2025, in handle_beacons
    beacons = self.process_beacons(self.functions)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 380, in process_beacons
    return self.beacons.process(b_conf)  # pylint: disable=no-member
  File "/usr/lib/python2.7/dist-packages/salt/beacons/__init__.py", line 92, in process
    raw = self.beacons[fun_str](b_config[mod])
  File "/usr/lib/python2.7/dist-packages/salt/beacons/service.py", line 106, in beacon
    if not service['emitatstartup']:
TypeError: string indices must be integers, not str
```

### Fix
Attached is a patch for the file: /usr/lib/python2.7/dist-packages/salt/beacons/service.py to fix the problem
[service.py.patch.zip](https://github.com/saltstack/salt/files/401538/service.py.patch.zip)

### Versions Report
```
Salt Version:
           Salt: 2016.3.2
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.5 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.5 
```

edit: markup

**Comment by Ch3LL** [comment]
@goestin thanks for the PR! We will get this closed up once the PR has been reviewed and merged. Thanks :+1:

**Comment by goestin** [comment]
Fix merged, thanks everyone!
