### ISSUE TITLE
gce: Failed to get the output of 'gce.avail_images()' : : oid

### ISSUE THREAD

**Issue by NagarajGond** [saltstack/salt#35200]
I want to list available images in gce

```
[root@localhost salt]# salt-cloud --list-locations gce
[INFO    ] salt-cloud starting
/usr/lib64/python2.6/site-packages/Crypto/Util/number.py:57: PowmInsecureWarning: Not using mpz_powm_sec.  You should rebuild using libgmp >= 5 to avoid timing attack vulnerability.
  _warn("Not using mpz_powm_sec.  You should rebuild using libgmp >= 5 to avoid timing attack vulnerability.", PowmInsecureWarning)
[ERROR   ] Failed to get the output of 'gce.avail_locations()': oid
gce-config:
    ----------
```

```
#- provider setup
      gce-config:
           project: "Traill"
           service_account_email_address: "xxx@xxx.gserviceaccount.com"
           service_account_private_key: /root/Trial.json
           provider: gce
```

```
#- cloud.profiles

my-gce-profile:
  image: centos-6-v20160718
  size: n1-standard-1
  location: europe-west1-b
  network: default
  tags: '["one", "two", "three"]'
  metadata: '{"one": "1", "2": "two"}'
  use_persistent_disk: True
  delete_boot_pd: False
  deploy: True
  make_master: False
  provider: gce-config
```

```
#- Versions Report
#- salt --versions-report
           Salt: 2015.5.10
           Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
           Jinja2: 2.2.1
           M2Crypto: 0.20.2
           msgpack-python: 0.4.6
           msgpack-pure: Not Installed
           pycrypto: 2.6.1
           libnacl: Not Installed
           PyYAML: 3.10
           ioflo: Not Installed
           PyZMQ: 14.3.1
           RAET: Not Installed
           ZMQ: 3.2.5
           Mako: Not Installed
           Tornado: 4.4.1
           timelib: Not Installed
           dateutil: Not Installed
```
# \- Traceback

```
#-  salt-cloud --list-images gce-config -l debug
[DEBUG   ] Reading configuration from /etc/salt/cloud
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/reactor.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/reactor.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/salt-api.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/salt-api.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: 127.0.0.1
[DEBUG   ] Missing configuration file: /etc/salt/cloud.profiles
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/vms.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/vms.conf
[DEBUG   ] Configuration file path: /etc/salt/cloud
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] salt-cloud starting
/usr/lib64/python2.6/site-packages/Crypto/Util/number.py:57: PowmInsecureWarning: Not using mpz_powm_sec.  You should rebuild using libgmp >= 5 to avoid timing attack vulnerability.
  _warn("Not using mpz_powm_sec.  You should rebuild using libgmp >= 5 to avoid timing attack vulnerability.", PowmInsecureWarning)
[DEBUG   ] Could not LazyLoad parallels.avail_sizes
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy
[DEBUG   ] Could not LazyLoad saltify.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.avail_images
[DEBUG   ] Could not LazyLoad saltify.avail_locations
[DEBUG   ] LazyLoaded rackspace.reboot
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] LazyLoaded rackspace.list_locations
[ERROR   ] Failed to get the output of 'gce.avail_images()': oid
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 842, in image_list
    data[alias][driver] = self.clouds[fun]()
  File "/usr/lib64/python2.6/contextlib.py", line 34, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.6/site-packages/salt/utils/context.py", line 42, in `func_globals_inject`
    yield
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 842, in image_list
    data[alias][driver] = self.clouds[fun]()
  File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/gce.py", line 339, in avail_images
    conn = get_conn()
  File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/gce.py", line 202, in get_conn
    gce = driver(email, private_key, project=project)
  File "/usr/lib/python2.6/site-packages/libcloud/compute/drivers/gce.py", line 1110, in __init__
    super(GCENodeDriver, self).__init__(user_id, key, **kwargs)
  File "/usr/lib/python2.6/site-packages/libcloud/common/base.py", line 1177, in __init__
    self.connection = self.connectionCls(*args, **conn_kwargs)
  File "/usr/lib/python2.6/site-packages/libcloud/compute/drivers/gce.py", line 99, in __init__
    **kwargs)
  File "/usr/lib/python2.6/site-packages/libcloud/common/google.py", line 737, in __init__
    user_id, key, auth_type, credential_file, scopes, **kwargs)
  File "/usr/lib/python2.6/site-packages/libcloud/common/google.py", line 648, in __init__
    self.token = self.oauth2_conn.get_new_token()
  File "/usr/lib/python2.6/site-packages/libcloud/common/google.py", line 518, in get_new_token
    signature = base64.urlsafe_b64encode(signer.sign(hash_func))
  File "/usr/lib64/python2.6/site-packages/Crypto/Signature/PKCS1_v1_5.py", line 110, in sign
    em = EMSA_PKCS1_V1_5_ENCODE(mhash, k)
  File "/usr/lib64/python2.6/site-packages/Crypto/Signature/PKCS1_v1_5.py", line 211, in EMSA_PKCS1_V1_5_ENCODE
    digestAlgo  = DerSequence([hash.oid, DerNull().encode()])
AttributeError: oid
[DEBUG   ] LazyLoaded nested.output
gce-config:
```

```
#- python -c "import libcloud ; print libcloud.__version__"
1.1.0
```

Thanks

**Comment by Ch3LL** [comment]
hmmm @NagarajGond would you mind trying a couple things here. 

1. downgrading libcloud below version 1. I know we have a known issue with libcloud with version1, but this error seems different.
2. How did you install pycrypto? Would you mind uninstalling/re-installing and see if that does anything. looks like there is a warning about how it was installed without libgmp.

**Comment by NagarajGond** [comment]
re-installed the pycrypto and downgraded libcloud to few versions(0.19.0, 0.17.0, 0.14.0), still the same issue.

[root@localhost salt]# salt-cloud --list-images gce-config -l debug
[DEBUG   ] Reading configuration from /etc/salt/cloud
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/reactor.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/reactor.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/salt-api.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/salt-api.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: 127.0.0.1
[DEBUG   ] Missing configuration file: /etc/salt/cloud.profiles
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/vms.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/vms.conf
[DEBUG   ] Configuration file path: /etc/salt/cloud
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] salt-cloud starting
[DEBUG   ] Could not LazyLoad parallels.avail_sizes
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy
[DEBUG   ] Could not LazyLoad saltify.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.avail_images
[DEBUG   ] Could not LazyLoad saltify.avail_locations
[DEBUG   ] LazyLoaded rackspace.reboot
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] LazyLoaded rackspace.list_locations
[ERROR   ] Failed to get the output of 'gce.avail_images()': oid
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 842, in image_list
    data[alias][driver] = self.clouds[fun]()
  File "/usr/lib64/python2.6/contextlib.py", line 34, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.6/site-packages/salt/utils/context.py", line 42, in func_globals_inject
    yield
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 842, in image_list
    data[alias][driver] = self.clouds[fun]()
  File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/gce.py", line 339, in avail_images
    conn = get_conn()
  File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/gce.py", line 202, in get_conn
    gce = driver(email, private_key, project=project)
  File "/usr/lib/python2.6/site-packages/libcloud/compute/drivers/gce.py", line 1052, in __init__
    super(GCENodeDriver, self).__init__(user_id, key, **kwargs)
  File "/usr/lib/python2.6/site-packages/libcloud/compute/base.py", line 669, in __init__
    api_version=api_version, **kwargs)
  File "/usr/lib/python2.6/site-packages/libcloud/common/base.py", line 1105, in __init__
    self.connection = self.connectionCls(*args, **conn_kwargs)
  File "/usr/lib/python2.6/site-packages/libcloud/compute/drivers/gce.py", line 97, in __init__
    **kwargs)
  File "/usr/lib/python2.6/site-packages/libcloud/common/google.py", line 635, in __init__
    self.token_info = self.auth_conn.get_new_token()
  File "/usr/lib/python2.6/site-packages/libcloud/common/google.py", line 517, in get_new_token
    signature = base64.urlsafe_b64encode(signer.sign(hash_func))
  File "/usr/lib64/python2.6/site-packages/Crypto/Signature/PKCS1_v1_5.py", line 110, in sign
    em = EMSA_PKCS1_V1_5_ENCODE(mhash, k)
  File "/usr/lib64/python2.6/site-packages/Crypto/Signature/PKCS1_v1_5.py", line 211, in EMSA_PKCS1_V1_5_ENCODE
    digestAlgo  = DerSequence([hash.oid, DerNull().encode()])
AttributeError: oid
[DEBUG   ] LazyLoaded nested.output
gce-config:
    ----------


# python -c "import libcloud ; print libcloud.__version__"
0.19.0

**Comment by NagarajGond** [comment]
OK, it worked after upgrading Saltstack to 2016.3.2 version. But the strange thing is we have to keep the provider and profile details in cloud.providers and cloud.profiles respectively for GCE. 

Getting below error if I keep gcepof.conf inside cloud.providers.d,  

````
salt-cloud -p my-gce-profile gce-instance
[ERROR   ] Profile my-gce-profile is not defined
Error:
    Profile my-gce-profile is not defined
````
