### ISSUE TITLE
salt develop broken - state run showing traceback and raising AttributeError

### ISSUE THREAD

**Issue by nmadhok** [saltstack/salt#35219]
Salt develop branch is broken. When trying to run any state using salt from develop branch, getting the following error:

```
root@nmadhok.local:~/salt/salt# salt-call state.sls sample.state test=true
[WARNING ] Key 'file_ignore_glob' with value None has an invalid type of NoneType, a list or basestring is required for this value
[WARNING ] Key 'file_ignore_regex' with value None has an invalid type of NoneType, a list or basestring is required for this value
[INFO    ] Loading fresh modules for state activity
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'bool' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 352, in salt_call
    client.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.6/site-packages/salt/cli/caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/modules/state.py", line 985, in sls
    high_, errors = st_.render_highstate({saltenv: mods})
  File "/usr/lib/python2.6/site-packages/salt/state.py", line 3149, in render_highstate
    sls, saltenv, mods, matches)
  File "/usr/lib/python2.6/site-packages/salt/state.py", line 2803, in render_state
    state_data = self.client.get_state(sls, saltenv)
  File "/usr/lib/python2.6/site-packages/salt/fileclient.py", line 394, in get_state
    dest = self.cache_file(path, saltenv, cachedir=cachedir)
  File "/usr/lib/python2.6/site-packages/salt/fileclient.py", line 177, in cache_file
    return self.get_url(path, '', True, saltenv, cachedir=cachedir)
  File "/usr/lib/python2.6/site-packages/salt/fileclient.py", line 475, in get_url
    url, dest, makedirs, saltenv, cachedir=cachedir)
  File "/usr/lib/python2.6/site-packages/salt/fileclient.py", line 972, in get_file
    hash_server, stat_server = self.hash_and_stat_file(path, saltenv)
  File "/usr/lib/python2.6/site-packages/salt/fileclient.py", line 1282, in hash_and_stat_file
    stat_result = fnd.get('stat')
AttributeError: 'bool' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 352, in salt_call
    client.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.6/site-packages/salt/cli/caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/modules/state.py", line 985, in sls
    high_, errors = st_.render_highstate({saltenv: mods})
  File "/usr/lib/python2.6/site-packages/salt/state.py", line 3149, in render_highstate
    sls, saltenv, mods, matches)
  File "/usr/lib/python2.6/site-packages/salt/state.py", line 2803, in render_state
    state_data = self.client.get_state(sls, saltenv)
  File "/usr/lib/python2.6/site-packages/salt/fileclient.py", line 394, in get_state
    dest = self.cache_file(path, saltenv, cachedir=cachedir)
  File "/usr/lib/python2.6/site-packages/salt/fileclient.py", line 177, in cache_file
    return self.get_url(path, '', True, saltenv, cachedir=cachedir)
  File "/usr/lib/python2.6/site-packages/salt/fileclient.py", line 475, in get_url
    url, dest, makedirs, saltenv, cachedir=cachedir)
  File "/usr/lib/python2.6/site-packages/salt/fileclient.py", line 972, in get_file
    hash_server, stat_server = self.hash_and_stat_file(path, saltenv)
  File "/usr/lib/python2.6/site-packages/salt/fileclient.py", line 1282, in hash_and_stat_file
    stat_result = fnd.get('stat')
AttributeError: 'bool' object has no attribute 'get'
```

Looks like the commit https://github.com/saltstack/salt/commit/73a156d28cafd45dcc6c2aac9f1ac3ad905695e3 made by @terminalmage caused it

PR with the fix coming soon!

**Comment by terminalmage** [comment]
SLS?

**Comment by terminalmage** [comment]
Versions report?

**Comment by nmadhok** [comment]
SLS:
```
# Template Variables
{% set baseFolder = "gitlab/git" %}
{% set baseURL = "salt://" ~ baseFolder %}
{% set fileName = baseFolder ~ "/init.sls"  %}
{% set osMajorRelease = grains['osmajorrelease'][0] %}
{% set gitVersion = "2.7.4" %}

{% if grains['os_family'] == "RedHat" and osMajorRelease == '6'  %}

{{fileName}} - Comment exclude=kernel from /etc/yum.conf:
  file.comment:
    - name: /etc/yum.conf
    - regex: ^exclude=kernel*
    - backup: .bak
    - onlyif: grep -e "^exclude=kernel*" /etc/yum.conf && echo "True"

{{fileName}} - Install required dependencies and development tools:
  pkg.installed:
    - pkgs:
      - zlib-devel
      - perl-CPAN
      - expat-devel
      - gettext-devel
      - openssl-devel
      - gcc
      - gcc-c++
      - gettext
      - libtool
      - libcurl-devel
      - make

{{fileName}} - Extract git-{{gitVersion}} package from tarball:
  archive.extracted:
    - name: /usr/local/src/git
    - source: {{baseURL}}/files/git-{{gitVersion}}.tar.gz
    - archive_format: tar
    - if_missing: /usr/local/src/git/git-{{gitVersion}}

{{fileName}} - Compile and build git-{{gitVersion}} from source:
  cmd.wait:
    {% if gitVersion == "2.7.4" %}
    - name: cd /usr/local/src/git/git-{{gitVersion}}/ && make prefix=/usr/local && make prefix=/usr/local install
    {% else %}
    - name: cd /usr/local/src/git/git-{{gitVersion}}/ && ./configure && make && make prefix=/usr/local install
    {% endif %}
    - watch:
      - archive: {{fileName}} - Extract git-{{gitVersion}} package from tarball
    - require:
      - pkg: {{fileName}} - Install required dependencies and development tools

{% endif %}
```

Versions report:
```
root@cu-osc-z-slt01:~/salt/salt# salt --versions-report
Salt Version:
           Salt: 2016.3.2-3549-ge792a42
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Jul 23 2015, 05:13:40)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: oracle 6.8 
        machine: x86_64
        release: 3.8.13-118.4.2.el6uek.x86_64
         system: Linux
        version: Oracle Linux Server 6.8 
```

**Comment by terminalmage** [comment]
This looks like it may be related to the archive.extracted state. Can you isolate the salt run to just that state, run ``salt-call`` with ``-l debug``, and post the result?
