### ISSUE TITLE
Can i use salt-ssh execute cp.push

### ISSUE THREAD

**Issue by colin-zhou** [saltstack/salt#35289]
### Description of Issue/Question

I have tried salt '192.168.3.76' cp.push /etc/fstab to copy minion file to master, it works well, however, it comes to a situation where salt-minion doesn't exist, so I try to run the following cmd:
salt-ssh '192.168.3.76' cp.push /etc/fstab, it turns out error.(the following msg is error log)

[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] LazyLoaded flat.targets
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] compile template: /etc/salt/roster
[DEBUG   ] Jinja search path: ['/var/cache/salt/master/files/base']
[PROFILE ] Time (in seconds) to render '/etc/salt/roster' using 'jinja' renderer: 0.00202894210815
[DEBUG   ] Rendered data from file: /etc/salt/roster:
192.168.3.76:
  host: 192.168.3.76
  user: test

192.168.3.181:
  host: 192.168.3.181
  user: test

[DEBUG   ] Results of YAML rendering: 
OrderedDict([('192.168.3.76', OrderedDict([('host', '192.168.3.76'), ('user', 'test')])), ('192.168.3.181', OrderedDict([('host', '192.168.3.181'), ('user', 'test')]))])
[PROFILE ] Time (in seconds) to render '/etc/salt/roster' using 'yaml' renderer: 0.00104212760925
[DEBUG   ] Matched minions: {'192.168.3.76': OrderedDict([('host', '192.168.3.76'), ('user', 'test')])}
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init
[DEBUG   ] Updating roots fileserver cache
[DEBUG   ] LazyLoaded local_cache.prep_jid
[DEBUG   ] Adding minions for job 20160809130254625919: ['192.168.3.76']
[DEBUG   ] Could not LazyLoad cp.push
[DEBUG   ] Performing shimmed, blocking command as follows:
cp.push /etc/fstab
[DEBUG   ] Executed SHIM command. Command logged to TRACE
[DEBUG   ] Child Forked! PID: 6095  STDOUT_FD: 10  STDERR_FD: 13
[DEBUG   ] VT: Salt-SSH SHIM Terminal Command executed. Logged to TRACE
[DEBUG   ] RETCODE 192.168.3.76: 1
[DEBUG   ] LazyLoaded nested.output
192.168.3.76:
    ----------
    retcode:
        1
    stderr:
        Traceback (most recent call last):
          File "/var/tmp/.test_3ef1f9_salt/salt-call", line 15, in <module>
            salt_call()
          File "/var/tmp/.test_3ef1f9_salt/py2/salt/scripts.py", line 345, in salt_call
            client.run()
          File "/var/tmp/.test_3ef1f9_salt/py2/salt/cli/call.py", line 58, in run
            caller.run()
          File "/var/tmp/.test_3ef1f9_salt/py2/salt/cli/caller.py", line 134, in run
            ret = self.call()
          File "/var/tmp/.test_3ef1f9_salt/py2/salt/cli/caller.py", line 197, in call
            ret['return'] = func(_args, *_kwargs)
          File "/var/tmp/.test_3ef1f9_salt/py2/salt/modules/cp.py", line 728, in push
            auth = _auth()
          File "/var/tmp/.test_3ef1f9_salt/py2/salt/modules/cp.py", line 35, in _auth
            __context__['auth'] = salt.crypt.SAuth(**opts**)
          File "/var/tmp/.test_3ef1f9_salt/py2/salt/crypt.py", line 940, in **new**
            key = cls.__key(opts)
          File "/var/tmp/.test_3ef1f9_salt/py2/salt/crypt.py", line 954, in __key
            opts['master_uri'],  # master ID
        KeyError: 'master_uri'
    stdout:
### Setup

(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
### Steps to Reproduce Issue

(Include debug logs if possible and relevant.)
### Versions Report

(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by Ch3LL** [comment]
@colin-zhou I am able to replicate this behavior on 2016.3.2. According to the documentation [here](https://docs.saltstack.com/en/2015.8/ref/clients/index.html#salt-s-loader-interface) some modules expect a full salt system underneath so it seems this is related to this situation.

ping @cachedout do you know if its possible to get this working in a salt-ssh environment? Based on that description in the docs i'm not certain if this is a situation that is able to be fixed.

**Comment by golmaal** [comment]
We're impacted by this issue as well. SSHClient constructor takes an mopts, giving minion_config causes issues with thin client key. How to provide master_uri for this to work correctly?

**Comment by Ch3LL** [comment]
will re-open thanks. i believe what ultimately needs to occur is the push function needs to be added to the cp.py wrapper function in salt-ssh. If you look at the file here: `salt/client/ssh/wrapper/cp.py` is what i'm referring to. Looks like that function was never added. It looks like in `salt/modules/cp.py` push function it attempts to use the transport layer to send the file, so we need to re-write it to work with ssh.

**Comment by brianthelion** [comment]
@Ch3LL Any update on this? Please reopen.

**Comment by Ch3LL** [comment]
oh sorry never re-opened it earlier lol thanks for the bump :)
