### ISSUE TITLE
[salt-cloud][azure] 'module' object has no attribute 'BlobService'

### ISSUE THREAD

**Issue by jagguli** [saltstack/salt#35326]
### azure storage calls error out

azure cloud functon list_blob does not work

salt-cloud -l debug -f list_blobs my-azure container=salt

```
[DEBUG   ] Trying to execute 'azure.list_blobs' with the following kwargs: {'container': 'salt'}
[ERROR   ] There was an error running the function: 'module' object has no attribute 'BlobService'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 274, in run
    self.function_provider, self.function_name, kwargs
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1598, in do_function
    call='function', kwargs=kwargs
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/msazure.py", line 3026, in list_blobs
    storage_conn = get_storage_conn(conn_kwargs=kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/msazure.py", line 2490, in get_storage_conn
    return azure.storage.BlobService(storage_account, storage_key)
AttributeError: 'module' object has no attribute 'BlobService'
```
### Steps to Reproduce Issue

configure an azure provider
### Versions Report

versions report does not have azure version in it 

```
azure==1.0.2
```

```
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: 1.7.0
       cherrypy: 7.1.0
       dateutil: 2.5.3
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.24.1
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.5
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.5
```

**Comment by Ch3LL** [comment]
@jagguli if you run `pip install azure-storage` does this resolve the issue?

**Comment by jagguli** [comment]
I just did ```pip install -U azure-storage``` and tried again, same error.

**Comment by rallytime** [comment]
Thanks @jagguli.

ping @techhat

**Comment by Ch3LL** [comment]
@jagguli what if you install an older version of azure-storage? 0.20.3 for example?
