### ISSUE TITLE
Issues w/ cherrypy on Ubuntu 16.04.1 and salt-api 2016.3.2

### ISSUE THREAD

**Issue by PredatorVI** [saltstack/salt#35320]
This issue is more to document a current issue with Ubuntu 16.04 and salt-master + salt-api.

Tried to migrate my salt-master server to Ubuntu 16.04.1 in order to use 'python-pygit2' package to work around another issue.  However, when using the 'python-cherrypy' distro package (v 2.3.0-5), I get an exception:

```
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/salt-api.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/salt-api.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt.wp.bluecoat.com
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] Setting up the Salt API
[DEBUG   ] Created pidfile: /var/run/salt-api.pid
[INFO    ] The salt-api is starting up
[INFO    ] Starting rest.start netapi module
[DEBUG   ] Started 'salt.loaded.int.netapi.rest_cherrypy.start' with pid 26187
[DEBUG   ] Process Manager starting!
Process salt.loaded.int.netapi.rest_cherrypy.start:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/netapi/rest_cherrypy/__init__.py", line 79, in start
    from . import app
  File "/usr/lib/python2.7/dist-packages/salt/netapi/rest_cherrypy/app.py", line 722, in <module>
    cherrypy.tools.html_override = cherrypy.Tool('on_start_resource',
AttributeError: 'module' object has no attribute 'Tool'
[INFO    ] Process <function start at 0x7fc727fe1ed8> (26187) died with exit status None, restarting...
```

When I remove the distro version and install cherrypy using 'pip install cherrypy' (v 7.1.0) it seems to run, but when I run using 'salt-api -l debug' the output shows the following (which may or may not be an issue) with cpstats (I haven't yet discovered if/how to install this module/package):

```
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/salt-api.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/salt-api.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt.wp.bluecoat.com
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] Setting up the Salt API
[DEBUG   ] Created pidfile: /var/run/salt-api.pid
[INFO    ] The salt-api is starting up
[INFO    ] Starting rest.start netapi module
[DEBUG   ] Started 'salt.loaded.int.netapi.rest_cherrypy.start' with pid 26390
[DEBUG   ] Process Manager starting!
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[09/Aug/2016:16:16:42] ENGINE Listening for SIGHUP.
[INFO    ] [09/Aug/2016:16:16:42] ENGINE Listening for SIGHUP.
[09/Aug/2016:16:16:42] ENGINE Listening for SIGTERM.
[INFO    ] [09/Aug/2016:16:16:42] ENGINE Listening for SIGTERM.
[09/Aug/2016:16:16:42] ENGINE Listening for SIGUSR1.
[INFO    ] [09/Aug/2016:16:16:42] ENGINE Listening for SIGUSR1.
[09/Aug/2016:16:16:42] ENGINE Bus STARTING
[INFO    ] [09/Aug/2016:16:16:42] ENGINE Bus STARTING
[WARNING ] CherryPy Checker:
'log_file' is obsolete. Use 'log.error_file' instead.
section: [saltopts]


[WARNING ] CherryPy Checker:
The config entry 'tools.cpstats.on' may be invalid, because the 'cpstats' tool was not found.
section: [/]


[09/Aug/2016:16:16:42] ENGINE Started monitor thread 'Autoreloader'.
[INFO    ] [09/Aug/2016:16:16:42] ENGINE Started monitor thread 'Autoreloader'.
[09/Aug/2016:16:16:42] ENGINE Started monitor thread '_TimeoutMonitor'.
[INFO    ] [09/Aug/2016:16:16:42] ENGINE Started monitor thread '_TimeoutMonitor'.
[09/Aug/2016:16:16:42] ENGINE Serving on https://0.0.0.0:8000
[INFO    ] [09/Aug/2016:16:16:42] ENGINE Serving on https://0.0.0.0:8000
[09/Aug/2016:16:16:42] ENGINE Bus STARTED
[INFO    ] [09/Aug/2016:16:16:42] ENGINE Bus STARTED
```

VERSIONS REPORT:

```
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: 1.5.2
       cherrypy: 7.1.0
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.24.0
         Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-34-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by Ch3LL** [comment]
@PredatorVI this is related to #34219 although you are reporting different errors. To workaround this issue can you try installing cherrypy 3.2.3. In that issue ctrlsf has posted a solution to doing so. 

I will label this a bug though to ensure we put efforts towards compatibility with newer versions of cherrypy
