### ISSUE TITLE
Fresh install, Salt seems to be working only half the time

### ISSUE THREAD

**Issue by SingleMalt** [saltstack/salt#35405]
Hi, so I'm following the Salt setup instructions (https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-salt-master-and-minion-servers-on-ubuntu-14-04), and have the Salt master and minion running on the same EC2 instance (m4.large). Salt is working only half the time and I can't figure out why.

```shell
root@ip-10------:~# salt '*' test.ping
ip-10------:
    True
root@ip-10------:~# salt '*' test.ping
ip-10------:
    True
root@ip-10------:~# salt '*' test.ping
ip-10------:
    True
root@ip-10------:~# salt '*' test.ping
Salt request timed out. The master is not responding. If this error persists after verifying the master is up, worker_threads may need to be increased.
root@ip-10------:~# salt '*' test.ping
Salt request timed out. The master is not responding. If this error persists after verifying the master is up, worker_threads may need to be increased.
```

Here is the Salt version reports:

```shell
root@ip-10------:~# salt-minion --versions-report
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-91-generic
         system: Linux
        version: Ubuntu 14.04 trusty

root@ip-10------:~# salt --versions-report
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-91-generic
         system: Linux
        version: Ubuntu 14.04 trusty

root@ip-10------:~# salt-master --versions-report
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-91-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

Here is some basic information about the Ubuntu instance:

```shell
root@ip-10------:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            3.9G  8.0K  3.9G   1% /dev
tmpfs           799M  348K  799M   1% /run
/dev/xvda1      7.8G  1.7G  5.7G  23% /
none            4.0K     0  4.0K   0% /sys/fs/cgroup
none            5.0M     0  5.0M   0% /run/lock
none            3.9G   60K  3.9G   1% /run/shm
none            100M     0  100M   0% /run/user

root@ip-10------:~# df -i
Filesystem      Inodes IUsed   IFree IUse% Mounted on
udev           1020715   386 1020329    1% /dev
tmpfs          1021952   313 1021639    1% /run
/dev/xvda1      524288 78135  446153   15% /
none           1021952     2 1021950    1% /sys/fs/cgroup
none           1021952     1 1021951    1% /run/lock
none           1021952    16 1021936    1% /run/shm
none           1021952     2 1021950    1% /run/user

root@ip-10------:~# free -m
             total       used       free     shared    buffers     cached
Mem:          7984        728       7255          0         14         95
-/+ buffers/cache:        617       7366
Swap:            0          0          0

root@ip-10------:~# host salt
salt.-------.com has address 10.-.-.-
```

Any help would be great. Thanks!

**Comment by SingleMalt** [comment]
Running both ```salt-master -l debug``` and ```salt-minion -l debug``` shows nothing on the calls that fail. It's like Salt just isn't getting those requests.

**Comment by SingleMalt** [comment]
Verbose output from the salt command:

```shell
root@ip-10------:~# salt -v -l trace '*' test.ping
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: ip-10------
[DEBUG   ] Missing configuration file: /root/.saltrc
[TRACE   ] None of the required configuration sections, 'logstash_udp_handler' and 'logstash_zmq_handler', were found in the configuration. Not loading the Logstash logging handlers module.
[TRACE   ] The required configuration section, 'fluent_handler', was not found the in the configuration. Not loading the fluent logging handlers module.
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: ip-10------
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'ip-10------_master', 'tcp://127.0.0.1:4506', 'clear')
[TRACE   ] Inserted key into loop_instance_map id 140096462065392 for key ('/etc/salt/pki/master', 'ip-10------_master', 'tcp://127.0.0.1:4506', 'clear') and process 6227
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[TRACE   ] IPCClient: Connecting to socket: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] SaltReqTimeoutError, retrying. (1/3)
[DEBUG   ] SaltReqTimeoutError, retrying. (2/3)
[DEBUG   ] SaltReqTimeoutError, retrying. (3/3)
[DEBUG   ] LazyLoaded nested.output
[TRACE   ] data = Salt request timed out. The master is not responding. If this error persists after verifying the master is up, worker_threads may need to be increased.
Salt request timed out. The master is not responding. If this error persists after verifying the master is up, worker_threads may need to be increased.```

**Comment by SingleMalt** [comment]
Seems like a ZMQ issue, seeing this on startup:

```shell
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'ip-10-0-1-15', 'tcp://10.0.1.15:4506', 'clear')
[DEBUG   ] SaltReqTimeoutError, retrying. (1/7)
[DEBUG   ] SaltReqTimeoutError, retrying. (2/7)
[DEBUG   ] SaltReqTimeoutError, retrying. (3/7)
[DEBUG   ] SaltReqTimeoutError, retrying. (4/7)
[DEBUG   ] SaltReqTimeoutError, retrying. (5/7)
[DEBUG   ] SaltReqTimeoutError, retrying. (6/7)
[DEBUG   ] SaltReqTimeoutError, retrying. (7/7)
[WARNING ] Fatal functionality error caught by minion handler:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 85, in minion_process
    minion.start()
  File "/usr/lib/python2.7/dist-packages/salt/cli/daemons.py", line 349, in start
    self.minion.tune_in()
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1964, in tune_in
    self.sync_connect_master()
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 898, in sync_connect_master
    raise six.reraise(*future_exception)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 907, in connect_master
    master, self.pub_channel = yield self.eval_master(self.opts, self.timeout, self.safe)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 570, in eval_master
    raise exc
SaltClientError: Attempt to authenticate with the salt master failed with timeout error
[WARNING ] ** Restarting minion **```

**Comment by Ch3LL** [comment]
@SingleMalt Okay I think i've pinpointed a bit of what is going on here. I can only replicate this when using the saltstack bootstrap options `sudo sh install_salt.sh -P -M`. 

If I do the following it works just fine:

1. sudo sh install_salt.sh -M
2. Install using the official saltstack packages at repo.saltstack.com

So the only added option in this situation that is causing this issue is the `-P` argument which allows a user to install packages using the pip package manager if needed. So I'm thinking there is a pip package that is causing this issue. But i'm not entirely sure and this will need to be tracked own more. I'm going to move this issue over to the salt bootstrap repo so we can track it there. As a workaround you can just run `sudo sh install_salt.sh -M` or install salt using the instructions at repo.saltstack.com

**Comment by Ch3LL** [comment]
Issue moved to [saltstack/salt-bootstrap #930](https://github.com/saltstack/salt-bootstrap/issues/930) via [**ZenHub**](https://www.zenhub.com/)
