### ISSUE TITLE
salt-minion fails on Ubuntu 12.04

### ISSUE THREAD

**Issue by roflmao** [saltstack/salt#35416]
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Ubuntu 12.04 with repo:
```
deb http://repo.saltstack.com/apt/ubuntu/12.04/amd64/2016.3 precise main
```

### Steps to Reproduce Issue
```
~# apt-get install salt-minion
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libaugeas-ruby1.8 libaugeas0 augeas-lenses libruby libshadow-ruby1.8 virt-what
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  salt-common
Suggested packages:
  python-augeas
The following NEW packages will be installed:
  salt-common salt-minion
0 upgraded, 2 newly installed, 0 to remove and 101 not upgraded.
Need to get 0 B/4,579 kB of archives.
After this operation, 17.7 MB of additional disk space will be used.
Do you want to continue [Y/n]? y
WARNING: The following packages cannot be authenticated!
  salt-common salt-minion
Authentication warning overridden.
Selecting previously unselected package salt-common.
(Reading database ... 96779 files and directories currently installed.)
Unpacking salt-common (from .../salt-common_2016.3.2+ds-1_all.deb) ...
Selecting previously unselected package salt-minion.
Unpacking salt-minion (from .../salt-minion_2016.3.2+ds-1_all.deb) ...
Processing triggers for man-db ...
Processing triggers for ureadahead ...
Setting up salt-common (2016.3.2+ds-1) ...
Setting up salt-minion (2016.3.2+ds-1) ...
# salt-call state.highstate
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 339, in salt_call
    import salt.cli.call
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 9, in <module>
    import salt.cli.caller
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 19, in <module>
    import salt.minion
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 78, in <module>
    import salt.client
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 38, in <module>
    import salt.utils.minions
  File "/usr/lib/python2.7/dist-packages/salt/utils/minions.py", line 19, in <module>
    import salt.auth.ldap
  File "/usr/lib/python2.7/dist-packages/salt/auth/ldap.py", line 18, in <module>
    from jinja2 import Environment
ImportError: No module named jinja2
# service salt-minion start
salt-minion start/running, process 1187
# ps aux | grep salt
root      1522  0.0  0.0   8344   936 pts/2    S+   14:42   0:00 grep --color=auto salt
# service salt-minion status
salt-minion stop/waiting
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
# salt-call --versions-report
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 339, in salt_call
    import salt.cli.call
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 9, in <module>
    import salt.cli.caller
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 19, in <module>
    import salt.minion
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 78, in <module>
    import salt.client
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 38, in <module>
    import salt.utils.minions
  File "/usr/lib/python2.7/dist-packages/salt/utils/minions.py", line 19, in <module>
    import salt.auth.ldap
  File "/usr/lib/python2.7/dist-packages/salt/auth/ldap.py", line 18, in <module>
    from jinja2 import Environment
ImportError: No module named jinja2
```

**Comment by Ch3LL** [comment]
@roflmao I'm having a hard time replicating this. Can you share what is in your sources flie (`/etc/apt/sources.list`)?

Also just to ensure can you run `dpkg -l | grep -i jinja` and paste the output.

**Comment by roflmao** [comment]
Looks like i installed salt-minion before i added the official saltstack repositories, and then installed salt-minion from the saltstack repos. You should maybe depend on versions on python deps so this doesnt happen.
