### ISSUE TITLE
dockerng.create fail to create docker on minion if extra_hosts present.

### ISSUE THREAD

**Issue by omegarus** [saltstack/salt#35430]
### Description of Issue/Question

dockerng.create fail to create docker on minion if extra_hosts=  present.
### Steps to Reproduce Issue

Here is error i getting when trying to use docker.create with  `extra_hosts=salt:123.1.1.1` 
on master:

```
root@salt-master1:~# salt -v docker-builder dockerng.create my-local-repo:5000/ubuntu/name:15 name=test cmd=salt-minion  extra_hosts=salt:123.1.1.1
Executing job with jid 20160814165114112715
-------------------------------------------

docker-builder:
    ERROR: Error 500: json: cannot unmarshal string into Go value of type []string
```

minion log:

```
2016-08-14 16:42:34,568 [salt.minion      ][ERROR   ][19519] A command in 'dockerng.create' had a problem: Error 500: json: cannot unmarshal string into Go value of type []string
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1071, in _thread_return
    return_data = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/dockerng.py", line 656, in wrapper
    returned = wrapped(*args, **salt.utils.clean_kwargs(**kwargs))
  File "/usr/lib/python2.7/dist-packages/salt/modules/dockerng.py", line 2959, in create
    **create_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/dockerng.py", line 626, in wrapper
    return wrapped(*args, **salt.utils.clean_kwargs(**kwargs))
  File "/usr/lib/python2.7/dist-packages/salt/modules/dockerng.py", line 892, in _client_wrapper
    exc.explanation)
CommandExecutionError: Error 500: json: cannot unmarshal string into Go value of type []string
```

Without setting extra_hosts everything works as expected.
### Versions Report

master:

```
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.19.0-43-generic
         system: Ubuntu 14.04 trusty
```

minion:

```
#salt-minion --version
salt-minion 2015.8.8.2 (Beryllium)
#pip freeze
apt-xapian-index==0.45
backports.ssl-match-hostname==3.5.0.1
certifi==2016.8.8
chardet==2.0.1
configobj==4.7.2
docker-py==1.9.0
iotop==0.6
ipaddress==1.0.16
Jinja2==2.7.2
Landscape-Client==14.12
Mako==0.9.1
MarkupSafe==0.18
msgpack-python==0.3.0
MySQL-python==1.2.3
ndg-httpsclient==0.4.2
PAM==0.4.2
pyasn1==0.1.9
pycrypto==2.6.1
pycurl==7.19.3
pyOpenSSL==0.13
pyserial==2.6
python-apt===0.9.3.5ubuntu2
python-dateutil==1.5
python-debian===0.1.21-nmu2ubuntu2
PyYAML==3.10
pyzmq==14.0.1
requests==2.10.0
salt==2015.8.8.2
six==1.10.0
ssh-import-id==3.21
tornado==4.2.1
Twisted-Core==13.2.0
urllib3==1.15.1
websocket-client==0.37.0
zope.interface==4.0.5
```

**Comment by omegarus** [comment]
Found workaround. If you use extra_hosts={'salt':['123.1.1.1']} dockerng.create works as expected.
Bug in docs ?

**Comment by Ch3LL** [comment]
@omegarus Can you try it like this: `extra_hosts='salt:123.1.1.1'` Does that work?

**Comment by omegarus** [comment]
@Ch3LL No still same error: ```ERROR: Error 500: json: cannot unmarshal string into Go value of type []string```
