### ISSUE TITLE
Salt Runner Pillar Rendering

### ISSUE THREAD

**Issue by SG910** [saltstack/salt#35434]
### Description of Issue/Question

salt-run pillar.show_pillar problem

```
Rendering exception occurred: Jinja variable 'dict object' has no attribute 'os_family'
```
### Setup

Default config for Master/Minion with the exception of changing the id's.  saltmaster and work.
#### salt/mytest.sls

```
{% set os_family = salt['grains.get']('os_family', None) %}
echo_Grain_Get_OSFamily:
  cmd.run:
    - name: echo {{os_family}}

echo_Grain_OSFamily:
  cmd.run:
    - name: echo {{grains['os_family']}}

echo_Pillar_OSFamily:
  cmd.run:
    - name: echo {{pillar['osfamily']}}

echo_Pillar_MyName:
  cmd.run:
    - name: echo {{pillar['myname']}}
```
#### pillar/mytest.sls

```
{% set os_family = salt['grains.get']('os_family') %}
{% set my_name = "JoeBuck" %}
osfamily: {{os_family}}
grainsdictbykey: {{grains['os_family']}}
myname: {{my_name}}
```
### Steps to Reproduce Issue

(Include debug logs if possible and relevant.)
#### Command

```
salt-run pillar.show_pillar *work*
```
#### Return

```
[ERROR   ] Rendering exception occurred: Jinja variable 'dict object' has no attribute 'os_family'
[CRITICAL] Rendering SLS 'mytest' failed, render error:
Jinja variable 'dict object' has no attribute 'os_family'
[CRITICAL] Pillar render error: Rendering SLS 'mytest' failed. Please see master log for details.
_errors:
    - Rendering SLS 'mytest' failed. Please see master log for details.
```
#### Command

```
salt *work* state.sls mytest
```
#### Return

```
worker-dev-:
----------
          ID: echo_Grain_Get_OSFamily
    Function: cmd.run
        Name: echo RedHat
      Result: True
     Comment: Command "echo RedHat" run
     Started: 00:58:08.609723
    Duration: 11.487 ms
     Changes:   
              ----------
              pid:
                  2728
              retcode:
                  0
              stderr:
              stdout:
                  RedHat
----------
          ID: echo_Grain_OSFamily
    Function: cmd.run
        Name: echo RedHat
      Result: True
     Comment: Command "echo RedHat" run
     Started: 00:58:08.621400
    Duration: 4.791 ms
     Changes:   
              ----------
              pid:
                  2729
              retcode:
                  0
              stderr:
              stdout:
                  RedHat
----------
          ID: echo_Pillar_OSFamily
    Function: cmd.run
        Name: echo RedHat
      Result: True
     Comment: Command "echo RedHat" run
     Started: 00:58:08.626357
    Duration: 4.734 ms
     Changes:   
              ----------
              pid:
                  2730
              retcode:
                  0
              stderr:
              stdout:
                  RedHat
----------
          ID: echo_Pillar_MyName
    Function: cmd.run
        Name: echo JoeBuck
      Result: True
     Comment: Command "echo JoeBuck" run
     Started: 00:58:08.631256
    Duration: 4.62 ms
     Changes:   
              ----------
              pid:
                  2731
              retcode:
                  0
              stderr:
              stdout:
                  JoeBuck

Summary for worker-dev-
------------
Succeeded: 4 (changed=4)
Failed:    0
------------
Total states run:     4
```
### Versions Report

(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
#### Master

```
salt --versions-report
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-34-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
#### Minion

```
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.8 Final
        machine: x86_64
        release: 2.6.32-642.3.1.el6.x86_64
         system: Linux
        version: CentOS 6.8 Final
```

**Comment by Ch3LL** [comment]
@SG910 I think I narrowed this down to when you use regex for targeting the minions. Here is my test case:

1. Using the same pillar file as you have:

```
{% set os_family = salt['grains.get']('os_family') %}
{% set my_name = "JoeBuck" %}
osfamily: {{os_family}}
grainsdictbykey: {{grains['os_family']}}
myname: {{my_name}}
```

2. Use salt-run with regex targeting: 

```
[ch3ll@thecakeisalie users-formula]$ sudo salt-run pillar.show_pillar 'ch3ll-minion0*'
[ERROR   ] Rendering exception occurred: Jinja variable 'dict object' has no attribute 'os_family'
[CRITICAL] Rendering SLS 'os' failed, render error:
Jinja variable 'dict object' has no attribute 'os_family'
[CRITICAL] Pillar render error: Rendering SLS 'os' failed. Please see master log for details.
_errors:
```

3. Using salt-run with full minion id name:

```
[ch3ll@thecakeisalie users-formula]$ sudo salt-run pillar.show_pillar 'ch3ll-minion02'
grainsdictbykey:
    RedHat
myname:
    JoeBuck
osfamily:
    RedHat
```

Also does not work if you leave the minion value off of the command:

```
[ch3ll@thecakeisalie users-formula]$ sudo salt-run pillar.show_pillar
[ERROR   ] Rendering exception occurred: Jinja variable 'dict object' has no attribute 'os_family'
[CRITICAL] Rendering SLS 'os' failed, render error:
Jinja variable 'dict object' has no attribute 'os_family'
[CRITICAL] Pillar render error: Rendering SLS 'os' failed. Please see master log for details.
_errors:
    - Rendering SLS 'os' failed. Please see master log for details.
```

Looks like we need to get this fixed up thanks.

**Comment by SG910** [comment]
Any word on this?  I can't seem to use pillar data in runners at all unless I want to use "in-lining".  It'd be nice to be able to access pillar data in orchestration sls especially gpg encrypted values.

**Comment by evanrich** [comment]
still seeing this in saltmaster logs with 3006.9...8.5 years later. 
```
{%- set basepath = "/usr/local" if grains['os_family'] == 'MacOS' else "/srv" %}    <======================
{%- set host = grains.get('host') -%}
{%- set osversion = grains.get('osrelease') %}

# Determine the package version based on the OS version
{%- set deploy_ver = '3006.9' %}
[...]
---
Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/templates.py", line 468, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/opt/saltstack/salt/lib/python3.10/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 7, in top-level template code
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'os_family'

During handling of the above exception, another exception occurred:
```
and running the commands above, i see the same response:

```
sudo salt-run pillar.show_pillar
[ERROR   ] Rendering exception occurred
Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/templates.py", line 468, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/opt/saltstack/salt/lib/python3.10/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 7, in top-level template code
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'os_family'
```
