### ISSUE TITLE
errors in minion logs if dmidecode is not installed

### ISSUE THREAD

**Issue by white-hat** [saltstack/salt#35505]
### Description of Issue/Question
I guess salt is trying to get BIOS info for grains even if dmidecode is not installed

```
2016-08-16 16:44:44,774 [tornado.application                                  ][ERROR   ][1452] Exception in callback <functools.partial object at 0x3889a48>
Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/tornado/ioloop.py", line 591, in _run_callback
    ret = callback()
  File "/usr/lib64/python2.6/site-packages/tornado/stack_context.py", line 274, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib64/python2.6/site-packages/tornado/ioloop.py", line 597, in <lambda>
    self.add_future(ret, lambda f: f.result())
  File "/usr/lib64/python2.6/site-packages/tornado/concurrent.py", line 214, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 230, in wrapper
    yielded = next(result)
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 1791, in handle_event
    self.module_refresh(notify=data.get('notify', False))
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 1635, in module_refresh
    self.functions, self.returners, _, self.executors = self._load_modules(force_refresh, notify=notify)
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 1082, in _load_modules
    self.opts['grains'] = salt.loader.grains(self.opts, force_refresh, proxy=proxy)
  File "/usr/lib/python2.6/site-packages/salt/loader.py", line 703, in grains
    ret = fun()
  File "/usr/lib/python2.6/site-packages/salt/grains/core.py", line 1468, in os_data
    grains.update(_hw_data(grains))
  File "/usr/lib/python2.6/site-packages/salt/grains/core.py", line 1897, in _hw_data
    'biosversion': __salt__['smbios.get']('bios-version'),
  File "/usr/lib/python2.6/site-packages/salt/modules/smbios.py", line 88, in get
    val = _dmidecoder('-s {0}'.format(string)).strip()
  File "/usr/lib/python2.6/site-packages/salt/modules/smbios.py", line 329, in _dmidecoder
    return salt.modules.cmdmod._run_quiet('{0} {1}'.format(DMIDECODER, args))
  File "/usr/lib/python2.6/site-packages/salt/modules/cmdmod.py", line 618, in _run_quiet
    pillar_override=pillar_override)['stdout']
  File "/usr/lib/python2.6/site-packages/salt/modules/cmdmod.py", line 475, in _run
    'reason: {2}'.format(cmd, kwargs, exc)
CommandExecutionError: Unable to run command '['None', '-s', 'bios-version']' with the context '{'timeout': None, 'with_communicate': True, 'shell': False, 'bg': False, 'stderr': -2, 'env': {'CONSOLETYPE': 'serial', 'LC_NUMERIC': 'C', 'LC_ADDRESS': 'C', 'runlevel': '3', 'UPSTART_EVENTS': 'runlevel', 'LC_CTYPE': 'C', 'LC_NAME': 'C', 'UPSTART_JOB': 'rc', 'LC_TELEPHONE': 'C', 'LC_PAPER': 'C', 'PATH': '/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin', '_': '/usr/bin/salt-minion', 'previous': 'N', 'LANG': 'en_US.UTF-8', 'LC_IDENTIFICATION': 'C', 'TERM': 'linux', 'LC_MESSAGES': 'C', 'SHLVL': '3', 'LC_COLLATE': 'C', 'PREVLEVEL': 'N', 'LANGSH_SOURCED': '1', 'UPSTART_INSTANCE': '', 'PWD': '/', 'RUNLEVEL': '3', 'LC_MEASUREMENT': 'C', 'LC_TIME': 'C', 'LC_MONETARY': 'C'}, 'stdout': -1, 'close_fds': True, 'stdin': None, 'cwd': '/root'}', reason: [Errno 2] No such file or directory
```

### Steps to Reproduce Issue
run any state without dmidecode installed

### Versions Report
```
# salt-minion --versions-report
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Jun 18 2012, 14:18:47)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.2 Final
        machine: x86_64
        release: 4.4.16-1.el6.x86_64
         system: Linux
        version: CentOS 6.2 Final
```

**Comment by Ch3LL** [comment]
@white-hat I'm having a hard time replicating this. Do you have `smbios` installed by chance? From reading the code it should not run `smbios.get` unless you have dmidecode or smbios installed.

**Comment by white-hat** [comment]
no I don't have smbios installed. And i'm  also unable to reproduce this issue on the same server. I looked through the smbios.py code and can't understand how this happened

**Comment by grinapo** [comment]
I observe the same, happening when I do
`salt 'minion' saltutil.refresh_modules`
dmidecode is present, smbios is not, and it's an lxc container.
```
# salt-minion --versions-report
Salt Version:
           Salt: 2016.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.0
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.6 
        machine: x86_64
        release: 4.4.16-1-pve
         system: Linux
        version: debian 8.6 
```

(As a sidenote I'm investigating how this happens:
```
master # salt 'minion' grains.get virtual
minion:
    physical

minion# salt-call grains.get virtual
local:
    lxc
```
)

**Comment by xavierog** [comment]
> no I don't have smbios installed. And i'm also unable to reproduce this issue on the same server. I looked through the smbios.py code and can't understand how this happened

I might have an hypothesis...

> I observe the same, happening when I do
> `salt 'minion' saltutil.refresh_modules`
> dmidecode is present, smbios is not, and it's an lxc container.

Was it a freshly spawned/installed container per chance? The smbios.py module initializes its DMIDECODER constant **at load time**, based on whether the dmidecode or smbios utilities are available on the system. Now, let's imagine we spawn a system with only a minimal amount of packages (i.e. neither dmidecode nor smbios) and Salt-minion, running on top of it. At this stage, Salt-minion looks up the PATH, finds neither dmidecode nor smbios and assigns None to smbios.DMIDECODER, triggering stacktraces when it tries to run 'None -s bios-version'.
In the meantime, salt-minion (or any other mechanism) is used to initialize/harmonize the minimal system and ends up (either explicitly or through dependencies) installing dmidecode. We have now reached a situation where dmidecode is present but salt-minion still tries to run 'None -s bios-version'. 
Somebody starts studying the issue, restarts salt-minion, which loads again smbios.py, detects dmidecode and starts behaving correctly: we have now reached a situation where the problem cannot be reproduced anymore.
Additionally, the problem is more likely to happen on kernel-less hosts (containers) as dmidecode is frequently associated with kernel/bootloader packages.

That being said, it seems smbios.py features various error handling conditions to detect all of this... My hypothesis does not explain why the minion logs show no smbios.py warnings...

**Comment by grinapo** [comment]
@xavierog Your hypothesis sounds correct to me, apart from the non-resolving details. :-) Probably this is the direction the investigation (or better, fixing the error handling) should head. I am almost completely sure that this was happening while reaching highstate, somwehere in the process.
