### ISSUE TITLE
dockerng.image_present fails if there is image with <none> tag listed on the host

### ISSUE THREAD

**Issue by komljen** [saltstack/salt#35563]
### Description of Issue/Question
dockerng.image_present fails if there is image with ```<none>``` tag listed on the host.

Error message:

```
[INFO    ] Executing state dockerng.image_present for rancher/server:stable
[DEBUG   ] "GET /v1.24/images/json?only_ids=0&all=0 HTTP/1.1" 200 None
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1733, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1651, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/states/dockerng.py", line 551, in image_present
    all_tags = __salt__['dockerng.list_tags']()
  File "/usr/lib/python2.7/dist-packages/salt/modules/dockerng.py", line 2253, in list_tags
    for repo_tag in item.get('RepoTags', []):
TypeError: 'NoneType' object is not iterable
```
### Setup

Salt state:

```
rancher_image:
  dockerng.image_present:
    - name: rancher/server:stable
```

### Steps to Reproduce Issue
There must be at least one image listed with ```<none>``` tag:

```
vagrant@master:~$ sudo docker images
REPOSITORY                       TAG                 IMAGE ID            CREATED             SIZE
wordpress                        latest              1ad4ec56dc5f        18 hours ago        422.3 MB
wordpress                        <none>              c7441ac916f3        6 days ago          421.6 MB
```

Removing image manually fixes the issue.

### Versions Report
```
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-93-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by Ch3LL** [comment]
@komljen this is related to #35139 although its related to `docker.running` but I think the current fix might work for you here: #35447 would you mind giving that fix a try and report back whether it works? Thanks

**Comment by komljen** [comment]
Great, seems this is fixed with this patch.

**Comment by Ch3LL** [comment]
@komljen great thanks for checking. You okay to close this issue now?

**Comment by komljen** [comment]
Sure, closing it.
