### ISSUE TITLE
salt-cloud deploy fails without helpful error output / here: package updates

### ISSUE THREAD

**Issue by Reiner030** [saltstack/salt#35561]
```
root@salt-euc1-01:~# lsb_release -d
Description:    Debian GNU/Linux 8.5 (jessie)
root@salt-euc1-01:~# salt-call --version
salt-call 2016.3.2 (Boron)
root@salt-euc1-01:~# salt-cloud --version
salt-cloud 2016.3.2 (Boron)
```

```
...
Fetched 655 kB in 5s (110 kB/s)
W: Failed to fetch http://cloudfront.debian.net/debian/dists/jessie-backports/main/source/Sources  Hash Sum mismatch

W: Failed to fetch http://cloudfront.debian.net/debian/dists/jessie-backports/main/binary-amd64/PackagesIndex  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.
 * ERROR: Failed to run install_debian_8_deps()!!!
[ERROR   ] Failed to deploy 'deploy-euc1-01'. Error: Command 'ssh -t -t -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oIdentitiesOnly=yes -oKbdInteractiveAuthentication=no -i /srv/pillar/salt-cloud/setup-key.pem -p 22 admin@172.31.9.103 'sudo /tmp/.saltcloud-391d19a3-e884-4d20-aac3-2c4d634822c7/deploy.sh -c '"'"'/tmp/.saltcloud-391d19a3-e884-4d20-aac3-2c4d634822c7'"'"' -U -p curl'' failed. Exit code: 1
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 2213, in run_map
    profile, local_master=local_master
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1281, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 2599, in create
    for key, value in six.iteritems(salt.utils.cloud.bootstrap(vm_, __opts__)):
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 528, in bootstrap
    deployed = deploy_script(**deploy_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 1517, in deploy_script
    if root_cmd(deploy_command, tty, sudo, **ssh_kwargs) != 0:
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 2168, in root_cmd
    retcode = _exec_ssh_cmd(cmd, allow_failure=allow_failure, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 1785, in _exec_ssh_cmd
    cmd, proc.exitstatus
SaltCloudSystemExit: Command 'ssh -t -t -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oIdentitiesOnly=yes -oKbdInteractiveAuthentication=no -i /srv/pillar/salt-cloud/nu3.pem -p 22 admin@172.31.9.103 'sudo /tmp/.saltcloud-391d19a3-e884-4d20-aac3-2c4d634822c7/deploy.sh -c '"'"'/tmp/.saltcloud-391d19a3-e884-4d20-aac3-2c4d634822c7'"'"' -U -p curl'' failed. Exit code: 1
[INFO    ] Complete
[DEBUG   ] LazyLoaded nested.output
deploy-euc1-01:
    ----------
    Error:
        Command 'ssh -t -t -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oIdentitiesOnly=yes -oKbdInteractiveAuthentication=no -i /srv/pillar/salt-cloud/setup-key.pem -p 22 admin@172.31.9.103 'sudo /tmp/.saltcloud-391d19a3-e884-4d20-aac3-2c4d634822c7/deploy.sh -c '"'"'/tmp/.saltcloud-391d19a3-e884-4d20-aac3-2c4d634822c7'"'"' -U -p curl'' failed. Exit code: 1
```

It would be nice
-  to get this error message without "-l debug" parameter set ;)
- to have a stable function in bootstrap script to handle such package repo problems or
- if it make sense e.g. to ignore such package upgrade errors by additional parameter like 

```
    -U  If set, fully upgrade the system prior to bootstrapping salt
    -u  If set, fully upgrade the system prior to bootstrapping salt but ignore problems
```

**Comment by Ch3LL** [comment]
@Reiner030 agreed it would be nice to have salt-cloud grab more of the useful output from the bootstrap script install. I will approve this issue as a feature request to improve what output salt-cloud grabs from the bootstrap script on error to focus on that exact concern. 

For the other two issues since they are directly related to updatign the bootstrap script would you mind opening an issue on salt-bootstraps repo [here](https://github.com/saltstack/salt-bootstrap)
