### ISSUE TITLE
2016.3.1 all minion return "Minion did not return. [No response]"

### ISSUE THREAD

**Issue by shaohk** [saltstack/salt#35587]
### Description of Issue/Question
Since i update the salt-master from 2015.08.01 to 2016.3.1. There is a surprising appearance on the master that when i execute “salt '*' test.ping”,all of minion return "Minion did not return. [No response]"
### Setup

```
salt -l trace '*' test.ping
`[DEBUG   ] Reading configuration from /etc/salt/master`
`[DEBUG   ] Including configuration from '/etc/salt/master.d/api.conf'`
`[DEBUG   ] Reading configuration from /etc/salt/master.d/api.conf`
`[DEBUG   ] Including configuration from '/etc/salt/master.d/eauth.conf'`
`[DEBUG   ] Reading configuration from /etc/salt/master.d/eauth.conf`
`[DEBUG   ] Including configuration from '/etc/salt/master.d/nodegroups.conf'`
`[DEBUG   ] Reading configuration from /etc/salt/master.d/nodegroups.conf`
`[DEBUG   ] Missing configuration file: /root/.saltrc`
`[TRACE   ] None of the required configuration sections, 'logstash_udp_handler' and 'logstash_zmq_handler', were found in the configuration. Not loading the Logstash logging handlers module.`
`[TRACE   ] The required configuration section, 'fluent_handler', was not found the in the configuration. Not loading the fluent logging handlers module.`
`[DEBUG   ] Configuration file path: /etc/salt/master`
`[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.`
`[DEBUG   ] Reading configuration from /etc/salt/master`
`[DEBUG   ] Including configuration from '/etc/salt/master.d/api.conf'`
`[DEBUG   ] Reading configuration from /etc/salt/master.d/api.conf`
`[DEBUG   ] Including configuration from '/etc/salt/master.d/eauth.conf'`
`[DEBUG   ] Reading configuration from /etc/salt/master.d/eauth.conf`
`[DEBUG   ] Including configuration from '/etc/salt/master.d/nodegroups.conf'`
`[DEBUG   ] Reading configuration from /etc/salt/master.d/nodegroups.conf`
`[DEBUG   ] Missing configuration file: /root/.saltrc`
`[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc`
`[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc`
`[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'master', 'tcp://127.0.0.1:4506', 'clear')`
`[TRACE   ] Inserted key into loop_instance_map id 35445288 for key ('/etc/salt/pki/master', 'master', 'tcp://127.0.0.1:4506', 'clear') and process 40782`
`[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc`
`[TRACE   ] IPCClient: Connecting to socket: /var/run/salt/master/master_event_pub.ipc`
`[TRACE   ] func get_cli_event_returns()`
`[DEBUG   ] LazyLoaded local_cache.get_load`
`[DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/e8/612232ec70f62960bae7b8d63edee8/.minions.p`
‘’‘’‘’‘’‘’‘’‘’‘’‘’my ip‘’‘’‘’‘’‘’‘’‘’‘’‘’‘
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
```

### Steps to Reproduce Issue
salt master error log :

```
`2016-08-19 14:11:51,823 [salt.minion      ][ERROR   ][20045] Invalid compound target:  for results:
2016-08-19 14:11:54,501 [salt.minion      ][ERROR   ][19876] Invalid compound target:  for results:
2016-08-19 14:11:56,704 [cherrypy.error.39056976][ERROR   ][20498] [19/Aug/2016:14:11:56]  Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/cherrypy/_cpwsgi.py", line 183, in trap
    return func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/cherrypy/_cpwsgi.py", line 102, in __call__
    return self.nextapp(environ, start_response)
  File "/usr/lib/python2.6/site-packages/cherrypy/_cpwsgi.py", line 414, in tail
    return self.response_class(environ, start_response, self.cpapp)
  File "/usr/lib/python2.6/site-packages/cherrypy/_cpwsgi.py", line 237, in __init__
    self.run()
  File "/usr/lib/python2.6/site-packages/cherrypy/_cpwsgi.py", line 353, in run
    request.run(meth, path, qs, rproto, headers, rfile)
  File "/usr/lib/python2.6/site-packages/cherrypy/_cprequest.py", line 617, in run
    raise cherrypy.TimeoutError()
TimeoutError

2016-08-19 14:11:57,368 [salt.minion      ][ERROR   ][19969] Invalid compound target:  for results:
2016-08-19 14:11:57,566 [salt.minion      ][ERROR   ][20054] Invalid compound target:  for results:
```

```
### Versions Report
Salt Version:
           Salt: 2016.3.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 7.1.0
       dateutil: 2.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.2.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5
 
System Versions:
           dist: centos 6.5 Final
        machine: x86_64
        release: 2.6.32-431.el6.x86_64
         system: Linux
        version: CentOS 6.5 Final
```

**Comment by Ch3LL** [comment]
@shaohk is there anything relevant in the minion logs? Did you also upgrade the minions to 2016.3.1? If so have you tried restarting the minions?
