### ISSUE TITLE
pkgbuild.repo fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by jbfriedrich** [saltstack/salt#35613]
### Description of Issue/Question

I am trying to build my own packages with my own patch set of Salt 2016.3.2 on Ubuntu 16.04. So far so good, the packages are all build and work as intended. But when i try to build the repo via 

    salt buildsalt state.sls repo.ubuntu.ubuntu16 pillar='{"build_version":"2016_3_2","build_release":"ubuntu1604","gpg_passphrase":"my secret key password"}`

I get the following error message:

>           ID: /srv/pkgs/ubuntu1604/amd64
>     Function: pkgbuild.repo
>       Result: False
>      Comment: An exception occurred in this state: Traceback (most recent call last):
>                 File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1733, in call
>                   **cdata['kwargs'])
>                 File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1651, in wrapper
>                   return f(*args, **kwargs)
>                 File "/usr/lib/python2.7/dist-packages/salt/states/pkgbuild.py", line 368, in repo
>                   if res['retcode'] > 0:
>               TypeError: 'NoneType' object has no attribute '__getitem__'
>      Started: 21:19:44.928178
>     Duration: 586004.209 ms
>      Changes:  

The minion log on the build VM shows the same error, but also that reprepo fails with a return code 251 for every deb package:

>     [salt.loaded.int.module.cmdmod][ERROR   ][127742] Command 'reprepro --ignore=wrongdistribution --component=main -Vb . includedeb xenial /srv/pkgs/ubuntu1604/amd64/libsodium18_1.0.8-5_amd64.deb' failed with return code: 251

When I run it a second time, without deleting folder or packages first, I get the following error

>     2016-08-19 21:41:56,731 [salt.state       ][ERROR   ][128999] An exception occurred in this state: Traceback (most recent call last):
>     File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1733, in call **cdata['kwargs'])
>     File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1651, in wrapper return f(*args, **kwargs)
>     File "/usr/lib/python2.7/dist-packages/salt/states/pkgbuild.py", line 366, in repo
>     res = __salt__[func](name, keyid, env, use_passphrase, gnupghome, runas)
>     File "/usr/lib/python2.7/dist-packages/salt/modules/debbuild.py", line 727, in make_repo
>     'Reprepro includedsc for codename {0} and file {1} failed with proc.status {2}'.format(codename, abs_file, proc_exitstatus)
>     SaltInvocationError: Reprepro includedsc for codename xenial and file /srv/pkgs/ubuntu1604/amd64/timelib_0.2.4-1.dsc failed with proc.status 254

### Setup

I am using Ubuntu 16.04 on the salt-master and the salt-minion. Very basic VMs with a minimal installation of Ubuntu.

### Steps to Reproduce Issue

* Deploy your build VM
* Set up build VM via `salt buildsaltvm state.sls setup.ubuntu.ubuntu16 -l debug pillar='{"build_version":"2016_3_2","build_release":"ubuntu1604"}'`
* Build packages via `salt buildsaltvm state.highstate -l debug pillar='{"build_version":"2016_3_2","build_release":"ubuntu1604"}'`
* Create repo via `salt buildsaltvm state.sls repo.ubuntu.ubuntu16 -l debug pillar='{"build_version":"2016_3_2","build_release":"ubuntu1604","gpg_passphrase":"my secret password"}'` 

### Versions Report

> Salt Version:
>            Salt: 2016.3.2
>  
> Dependency Versions:
>            cffi: Not Installed
>        cherrypy: Not Installed
>        dateutil: 2.4.2
>           gitdb: 0.6.4
>       gitpython: 1.0.1
>           ioflo: Not Installed
>          Jinja2: 2.8
>         libgit2: Not Installed
>         libnacl: Not Installed
>        M2Crypto: 0.21.1
>            Mako: 1.0.3
>    msgpack-pure: Not Installed
>  msgpack-python: 0.4.6
>    mysql-python: Not Installed
>       pycparser: Not Installed
>        pycrypto: 2.6.1
>          pygit2: Not Installed
>          Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
>    python-gnupg: Not Installed
>          PyYAML: 3.11
>           PyZMQ: 15.2.0
>            RAET: Not Installed
>           smmap: 0.9.0
>         timelib: Not Installed
>         Tornado: 4.2.1
>             ZMQ: 4.1.4
>  
> System Versions:
>            dist: Ubuntu 16.04 xenial
>         machine: x86_64
>         release: 4.4.0-31-generic
>          system: Linux
>         version: Ubuntu 16.04 xenial

**Comment by jbfriedrich** [comment]
Sorry, wrong project. This was supposed to go to salt-pack
