### ISSUE TITLE
Salt's gem.installed function failed after upgrade

### ISSUE THREAD

**Issue by romanovna** [saltstack/salt#35759]
### Description of Issue/Question

After upgrade from 2015-8.8.2 to 2016-3.2, job that deploys ruby's gems - fails. I am using salt's [sensu-formula](https://github.com/saltstack-formulas/sensu-formula) . On windows-minions, those  versions are 2015-8.8.2 - everything works well, but not on 2016-3.2 minions. 
### Setup

```
{% set gem_list = salt['pillar.get']('sensu:client:install_gems', []) %}
{% for gem in gem_list %}
{% if gem is mapping %}
{% set gem_name = gem.name %}
{% else %}
{% set gem_name = gem %}
{% endif %}
install_{{ gem_name }}:
  gem.installed:
    - name: {{ gem_name }}
    {% if sensu.client.embedded_ruby %}
    - gem_bin: /opt/sensu/embedded/bin/gem
    {% else %}
    - gem_bin: None
    {% endif %}
    {% if gem.version is defined %}
    - version: {{ gem.version }}
    {% endif %}
    - rdoc: False
    - ri: False
{% endfor %}
```
### Steps to Reproduce Issue

```
----------
          ID: install_sensu-plugins-windows
    Function: gem.installed
        Name: sensu-plugins-windows
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "C:\salt\bin\lib\site-packages\salt\state.py", line 1733, in call
                  **cdata['kwargs'])
                File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1651, in wrapper
                  return f(*args, **kwargs)
                File "C:\salt\bin\lib\site-packages\salt\states\gem.py", line 86, in installed
                  gems = __salt__['gem.list'](name, ruby, gem_bin=gem_bin, runas=user)
                File "C:\salt\bin\lib\site-packages\salt\modules\gem.py", line 255, in list_
                  runas=runas)
                File "C:\salt\bin\lib\site-packages\salt\modules\gem.py", line 61, in _gem
                  ret = __salt__['cmd.run_all'](cmdline, runas=runas, python_shell=False)
                File "C:\salt\bin\lib\site-packages\salt\modules\cmdmod.py", line 1590, in run_all
                  password=kwargs.get('password', None))
                File "C:\salt\bin\lib\site-packages\salt\modules\cmdmod.py", line 475, in _run
                  'reason: {2}'.format(cmd, kwargs, exc)
              CommandExecutionError: Unable to run command '['/opt/sensu/embedded/bin/gem', 'list', 'sensu-plugins-windows']' with the context '{'timeout': None, 'with_communicate': True, 'shell': False, 'bg': False, 'stderr': -1, 'env': {'TMP': 'C:\\Windows\\TEMP', 'COMPUTERNAME': 'QCAT-TEST', 'USERDOMAIN': 'WORKGROUP', 'PSMODULEPATH': 'C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules\\', 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files', 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 58 Stepping 0, GenuineIntel', 'PROGRAMFILES': 'C:\\Program Files', 'PROCESSOR_REVISION': '3a00', 'SYSTEMROOT': 'C:\\Windows', 'PATH': 'C:\\Windows\\system32;C:\\Windows;C:\\Windows\\system32\\wbem;C:\\Windows\\system32\\windowspowershell\\v1.0;c:\\opt\\sensu\\embedded\\bin\\ruby.exe;c:\\opt\\sensu\\bin;C:\\QCAT\\utils;C:\\salt\\bin\\lib\\site-packages\\pywin32_system32;/bin;/sbin;/usr/bin;/usr/sbin;/usr/local/bin;C:\\salt\\bin\\lib\\site-packages\\pywin32_system32;C:\\salt\\bin\\lib\\site-packages\\pywin32_system32', 'UCF_FORCE_CONFFOLD': '1', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'TEMP': 'C:\\Windows\\TEMP', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'ALLUSERSPROFILE': 'C:\\ProgramData', 'LOCALAPPDATA': 'C:\\Windows\\system32\\config\\systemprofile\\AppData\\Local', 'PROGRAMW6432': 'C:\\Program Files', 'USERNAME': 'QCAT-TEST$', 'COMSPEC': 'C:\\Windows\\system32\\cmd.exe', 'PROGRAMDATA': 'C:\\ProgramData', 'DEBIAN_FRONTEND': 'noninteractive', 'PUBLIC': 'C:\\Users\\Public', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC', 'APT_LISTCHANGES_FRONTEND': 'none', 'FP_NO_HOST_CHECK': 'NO', 'WINDIR': 'C:\\Windows', 'APPDATA': 'C:\\Windows\\system32\\config\\systemprofile\\AppData\\Roaming', 'SYSTEMDRIVE': 'C:', 'PYTHONHOME': '', 'NUMBER_OF_PROCESSORS': '1', 'PROCESSOR_LEVEL': '6', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 'OS': 'Windows_NT', 'APT_LISTBUGS_FRONTEND': 'none', 'USERPROFILE': 'C:\\Windows\\system32\\config\\systemprofile'}, 'stdout': -1, 'stdin': None, 'cwd': 'C:\\Windows\\system32\\config\\systemprofile'}', reason: [Error 193] %1 is not a valid Win32 application
     Started: 01:53:19.478000
    Duration: 0.0 ms
     Changes:   
```
### Versions Report

```
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.19.0-25-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by Ch3LL** [comment]
@romanovna i'm havng a hard time replicating this. Would you mind providing a smaller test case or provide your pillar values for that state? Thanks in advance

**Comment by romanovna** [comment]
@Ch3LL , Sure - here is the pillar that is in use of the job: 
```
node-303:
    ----------
    sensu:
        ----------
        client:
            ----------
            embedded_ruby:
                True
            install_gems:
                - sensu-plugins-windows
            nagios_plugins:
                False
            subscriptions:
                - Windows
```
And which test case should I provide? Well, I tested this upgrade on 3 machines ( 2 VMs and 1 bare metal) and each of those failed to apply highstate after upgrade.
