### ISSUE TITLE
Relative path reference not possible inside pillar files when using jinja import

### ISSUE THREAD

**Issue by DaveOHenry** [saltstack/salt#35756]
### Description of Issue/Question

As requested by @Ch3LL in https://github.com/saltstack/salt/issues/35521.
When using jinja to import variables from files it is possible in normal state files to use only the filename without path.
In pillar sls files an absolute path is needed, otherwise the import fails.
### Setup

/srv/salt/test.jinja

```
{%- set foo = "bar" %}
{%- set more = "stuff" %}

{%- set vars = {
    'foo' : foo,
    'more' : more,
} %}
```

/srv/pillar/test.sls

```
{% from "test.jinja" import vars with context %}
var1: {{ vars.foo }}
var2: {{ vars.more }}
```

/srv/pillar/top.sls

```
base:
  'testhost':
     - test
```
### Steps to Reproduce Issue

master log after executing: salt 'testhost' pillar.items

```
2016-08-25 09:10:44,984 [salt.utils.templates][ERROR   ][5891] Rendering exception occurred: Jinja error: test.jinja
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 366, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 1, in top-level template code
  File "/usr/lib/python2.7/dist-packages/salt/utils/jinja.py", line 144, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: test.jinja

; line 1

---
{% from "test.jinja" import vars with context %}    <======================
var1: {{ vars.foo }}
var2: {{ vars.more }}

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 366, in render_jinja_tmpl
[...]

---
2016-08-25 09:10:44,986 [salt.pillar      ][CRITICAL][5891] Rendering SLS 'test' failed, render error:
Jinja error: test.jinja
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 366, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 1, in top-level template code
  File "/usr/lib/python2.7/dist-packages/salt/utils/jinja.py", line 144, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: test.jinja

; line 1

---
{% from "test.jinja" import vars with context %}    <======================
var1: {{ vars.foo }}
var2: {{ vars.more }}

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 366, in render_jinja_tmpl
[...]

---
2016-08-25 09:10:44,986 [salt.pillar      ][CRITICAL][5891] Pillar render error: Rendering SLS 'test' failed. Please see master log for details.
```
### Versions Report

```
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.1
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.19.0-25-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by Ch3LL** [comment]
@DaveOHenry thanks for opening this. Appreciated. 

Just to link the two issues, possibly related to feature #8875

**Comment by danlsgiga** [comment]
Facing the same issue in my setup, running 2017.7.5. Whenever I have imports in templates using relative paths I get multiple TemplateNotFound errors on the Salt master... this happens specially when I invoke the highstate from an orchestrate state.

Using absolute paths fix the issue for now but it would be nice to use relative paths on pillars as well.

**Comment by Ch3LL** [comment]
ping @terminalmage do you have any ideas for @pauldamian 's question?

**Comment by Oloremo** [comment]
Any updates on this?

**Comment by Ch3LL** [comment]
i looked at this issue a bit closer and what i realized is your `test.jinja` file is in your sls file_roots not your pillar. When I add `test.jinja` to /srv/pillar/test.jinja it works just as expected.
