### ISSUE TITLE
KeyError: 'seconds' on schedule.run_job (with cmd.run in it)

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#35790]
### Description of Issue/Question

```
$ salt-call schedule.run_job highstate-stats
host
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1078, in _thread_return
        return_data = func(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/schedule.py", line 533, in run_job
        schedule = list_(show_all=True, return_yaml=False)
      File "/usr/lib/python2.7/dist-packages/salt/modules/schedule.py", line 122, in list_
        del schedule[job]['seconds']
    KeyError: 'seconds'
```
### Setup

(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

```
$ cat pillar/schedule.sls
    highstate-stats:
        function: cmd.run
        hours: 6
        run_on_start: False
        args:
            - 'script.sh'
        splay:
            start: 216000 #60m
            end : 432000 #120m

$ salt-call schedule.list
      highstate-stats:
        args:
        - script.sh
        enabled: true
        function: cmd.run
        hours: 6
        jid_include: true
        maxrunning: 1
        name: highstate-stats
        seconds: 0
        splay:
          end: 432000
          start: 216000
```
### Versions Report

(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
# salt --versions-report
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: 1.0.0
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: 2.3.0
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: debian 8.4 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.4 

# salt-call --versions-report
Salt Version:
           Salt: 2015.8.11

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: debian 8.5 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.5 
```

**Comment by Ch3LL** [comment]
@arthurlogilab i'm having a hard time replicate this. Even when I run pdb I see `_seconds` in the `schedule[job]`

Although I did have to add the `schedule` to your pillar ifle like so:

```
schedule:
  highstate-stats:
    function: cmd.run
    hours: 6
    run_on_start: False
    args:
        - 'script.sh'
    splay:
        start: 216000 #60m
        end : 432000 #120m
```
