### ISSUE TITLE
chocolatey.install returns invalid dict after success

### ISSUE THREAD

**Issue by digitaldelirium** [saltstack/salt#35828]
### Description of Issue/Question

Chocolatey.install appears to succeed when the machine is logged into, but the return value is a failure
### Setup

(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
## win_utils.sls

```
powershell:
   chocolatey.install
visualstudiocode:
   chocolatey.install
vscode-powershell:
   chocolatey.install
wireshark:
   chocolatey.install
microsoft-message-analyzer:
   chocolatey.install
```
### Steps to Reproduce Issue

```
 salt '*' state.apply 
```

console output:

```
----------
          ID: microsoft-message-analyzer
    Function: chocolatey.install
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "c:\salt\bin\lib\site-packages\salt\state.py", line 1737, in call
                  self.verify_ret(ret)
                File "c:\salt\bin\lib\site-packages\salt\state.py", line 959, in verify_ret
                  'Malformed state return, return must be a dict'
              SaltException: Malformed state return, return must be a dict
     Started: 15:51:40.100000
    Duration: 283697.0 ms
     Changes:
```

log file:

```
[INFO    ] Executing state chocolatey.install for microsoft-message-analyzer
2016-08-26 15:51:40 [salt.loaded.int.module.cmdmod][INFO    ] Executing command 'choco list --local-only' in directory 'C:\Windows\system32\config\systemprofile'
2016-08-26 15:51:41 [salt.loaded.int.module.cmdmod][INFO    ] Executing command ['C:\\ProgramData\\chocolatey\\bin\\chocolatey.exe', 'install', 'microsoft-message-analyzer', '--yes'] in directory 'C:\Windows\system32\config\systemprofile'
2016-08-26 15:51:46 [salt.minion    ][INFO    ] Starting a new job with PID 3644
2016-08-26 15:51:46 [salt.minion    ][INFO    ] Returning information for job: 20160826155144533187
2016-08-26 15:51:56 [salt.minion    ][INFO    ] Starting a new job with PID 580
2016-08-26 15:51:56 [salt.minion    ][INFO    ] Returning information for job: 20160826155154566412
2016-08-26 15:52:06 [salt.minion    ][INFO    ] Starting a new job with PID 1592
2016-08-26 15:52:06 [salt.minion    ][INFO    ] Returning information for job: 20160826155204746520
2016-08-26 15:52:17 [salt.minion    ][INFO    ] Starting a new job with PID 3900
2016-08-26 15:52:17 [salt.minion    ][INFO    ] Returning information for job: 20160826155214812143
2016-08-26 15:52:27 [salt.minion    ][INFO    ] Starting a new job with PID 3720
2016-08-26 15:52:27 [salt.minion    ][INFO    ] Returning information for job: 20160826155224961597
2016-08-26 15:52:37 [salt.minion    ][INFO    ] Starting a new job with PID 3048
2016-08-26 15:52:37 [salt.minion    ][INFO    ] Returning information for job: 20160826155235043256
2016-08-26 15:52:47 [salt.minion    ][INFO    ] Starting a new job with PID 1000
2016-08-26 15:52:47 [salt.minion    ][INFO    ] Returning information for job: 20160826155245181728
2016-08-26 15:52:57 [salt.minion    ][INFO    ] Starting a new job with PID 2612
2016-08-26 15:52:57 [salt.minion    ][INFO    ] Returning information for job: 20160826155255246353
2016-08-26 15:53:07 [salt.minion    ][INFO    ] Starting a new job with PID 3508
2016-08-26 15:53:07 [salt.minion    ][INFO    ] Returning information for job: 20160826155305449890
2016-08-26 15:53:18 [salt.minion    ][INFO    ] Starting a new job with PID 4040
2016-08-26 15:53:18 [salt.minion    ][INFO    ] Returning information for job: 20160826155315612092
2016-08-26 15:53:27 [salt.minion    ][INFO    ] Starting a new job with PID 3704
2016-08-26 15:53:27 [salt.minion    ][INFO    ] Returning information for job: 20160826155325644970
2016-08-26 15:53:38 [salt.minion    ][INFO    ] Starting a new job with PID 3784
2016-08-26 15:53:38 [salt.minion    ][INFO    ] Returning information for job: 20160826155335703989
2016-08-26 15:53:47 [salt.minion    ][INFO    ] Starting a new job with PID 3776
2016-08-26 15:53:48 [salt.minion    ][INFO    ] Returning information for job: 20160826155345735162
2016-08-26 15:53:57 [salt.minion    ][INFO    ] Starting a new job with PID 3944
2016-08-26 15:53:57 [salt.minion    ][INFO    ] Returning information for job: 20160826155355781721
2016-08-26 15:54:08 [salt.minion    ][INFO    ] Starting a new job with PID 3420
2016-08-26 15:54:08 [salt.minion    ][INFO    ] Returning information for job: 20160826155405867987
2016-08-26 15:54:18 [salt.minion    ][INFO    ] Starting a new job with PID 2776
2016-08-26 15:54:18 [salt.minion    ][INFO    ] Returning information for job: 20160826155415990730
2016-08-26 15:54:28 [salt.minion    ][INFO    ] Starting a new job with PID 3596
2016-08-26 15:54:28 [salt.minion    ][INFO    ] Returning information for job: 20160826155426094227
2016-08-26 15:54:38 [salt.minion    ][INFO    ] Starting a new job with PID 2628
2016-08-26 15:54:38 [salt.minion    ][INFO    ] Returning information for job: 20160826155436193008
2016-08-26 15:54:48 [salt.minion    ][INFO    ] Starting a new job with PID 3576
2016-08-26 15:54:48 [salt.minion    ][INFO    ] Returning information for job: 20160826155446280426
2016-08-26 15:54:58 [salt.minion    ][INFO    ] Starting a new job with PID 2756
2016-08-26 15:54:58 [salt.minion    ][INFO    ] Returning information for job: 20160826155456311967
2016-08-26 15:55:08 [salt.minion    ][INFO    ] Starting a new job with PID 280
2016-08-26 15:55:08 [salt.minion    ][INFO    ] Returning information for job: 20160826155506467844
2016-08-26 15:55:19 [salt.minion    ][INFO    ] Starting a new job with PID 908
2016-08-26 15:55:19 [salt.minion    ][INFO    ] Returning information for job: 20160826155516689017
2016-08-26 15:55:29 [salt.minion    ][INFO    ] Starting a new job with PID 3400
2016-08-26 15:55:29 [salt.minion    ][INFO    ] Returning information for job: 20160826155526882637
2016-08-26 15:55:39 [salt.minion    ][INFO    ] Starting a new job with PID 1644
2016-08-26 15:55:39 [salt.minion    ][INFO    ] Returning information for job: 20160826155536988921
2016-08-26 15:55:49 [salt.minion    ][INFO    ] Starting a new job with PID 1576
2016-08-26 15:55:49 [salt.minion    ][INFO    ] Returning information for job: 20160826155547150892
2016-08-26 15:55:59 [salt.minion    ][INFO    ] Starting a new job with PID 2716
2016-08-26 15:55:59 [salt.minion    ][INFO    ] Returning information for job: 20160826155557245719
2016-08-26 15:56:09 [salt.minion    ][INFO    ] Starting a new job with PID 3260
2016-08-26 15:56:09 [salt.minion    ][INFO    ] Returning information for job: 20160826155607362584
2016-08-26 15:56:19 [salt.minion    ][INFO    ] Starting a new job with PID 2304
2016-08-26 15:56:19 [salt.minion    ][INFO    ] Returning information for job: 20160826155617384012
2016-08-26 15:56:23 [salt.state     ][ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt\state.py", line 1737, in call
    self.verify_ret(ret)
  File "c:\salt\bin\lib\site-packages\salt\state.py", line 959, in verify_ret
    'Malformed state return, return must be a dict'
SaltException: Malformed state return, return must be a dict

2016-08-26 15:56:23 [salt.state     ][INFO    ] Completed state [microsoft-message-analyzer] at time 15:56:23.797000 duration_in_ms=283697.0
2016-08-26 15:56:24 
```

Package is present on all targeted machines
### Versions Report

(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: 1.7.0
       cherrypy: 3.5.0
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 2.0.8
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.24.0
         Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-34-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

clients were installed from this machine within the last week, but are windows and I can't seem to find the exe/cmd to get the version table from it.

**Comment by Ch3LL** [comment]
@digitaldelirium according to the docs [here](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.chocolatey.html#salt.states.chocolatey.install) `chocolatey.install` is deprectated and will be removed entirely by the nitrogen release.

Can you try changing it to `chocolatey.installed` I tested that and it is working. Thanks

**Comment by dragon788** [comment]
@digitaldelirium I haven't written my first state using states.chocolatey yet but I'm curious if you are still encountering this issue as I'll probably hit it shortly?

**Comment by digitaldelirium** [comment]
I actually did get this working with chocolatey.installed, if I remember correctly.  Unfortunately, I no longer work for the org where I had written this state to provide an example.

**Comment by Ch3LL** [comment]
As it seems this has been resolved on your end @digitaldelirium i will close this. 

@dragon788 please feel free to open any issues if you run into them while using the chocolatey module :)
