### ISSUE TITLE
Breakage in EL7 When FIPS Is Enabled

### ISSUE THREAD

**Issue by ferricoxide** [saltstack/salt#35862]
### Description of Issue/Question

In the middle of writing a FIPS detecter/handler for my RHEL/CentOS 7 instances. Everything runs fine till I boot the system into FIPS mode, then it all goes sideways. After rebooting into FIPS mode, previously working configuration starts spewing:

~~~
$ sudo salt-call --local -l warning state.sls ash-linux.el7.STIGbyID.cat1.RHEL-07-021280
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
ValueError: error:060800A3:digital envelope routines:EVP_DigestInit_ex:disabled for fips
Traceback (most recent call last):
  File "/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 335, in salt_call
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 53, in run
    caller.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 133, in run
    ret = self.call()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 196, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 744, in sls
    high_, errors = st_.render_highstate({saltenv: mods})
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2981, in render_highstate
    sls, saltenv, mods, matches)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2651, in render_state
    state_data = self.client.get_state(sls, saltenv)
  File "/usr/lib/python2.7/site-packages/salt/fileclient.py", line 446, in get_state
    dest = self.cache_file(path, saltenv)
  File "/usr/lib/python2.7/site-packages/salt/fileclient.py", line 158, in cache_file
    return self.get_url(path, '', True, saltenv)
  File "/usr/lib/python2.7/site-packages/salt/fileclient.py", line 543, in get_url
    return self.get_file(url, dest, makedirs, saltenv)
  File "/usr/lib/python2.7/site-packages/salt/fileclient.py", line 984, in get_file
    hash_server = self.hash_file(path, saltenv)
  File "/usr/lib/python2.7/site-packages/salt/fileclient.py", line 1229, in hash_file
    return self.channel.send(load)
  File "/usr/lib/python2.7/site-packages/salt/fileserver/__init__.py", line 742, in send
    return getattr(self.fs, cmd)(load)
  File "/usr/lib/python2.7/site-packages/salt/fileserver/__init__.py", line 582, in file_hash
    return self.servers[fstr](load, fnd)
  File "/usr/lib/python2.7/site-packages/salt/fileserver/roots.py", line 230, in file_hash
    ret['hsum'] = salt.utils.get_hash(path, __opts__['hash_type'])
  File "/usr/lib/python2.7/site-packages/salt/utils/__init__.py", line 1997, in get_hash
    hash_obj = hash_type()
~~~

Looks like there were other issues for RHEL/CentOS 6 that were addressed, but issue-search for "FIPS" didn't turn anything up for EL7.

### Setup
Salt configuration:

Running in masterless mode on CentOS 7.2.1511 with August patch-sets.

### Steps to Reproduce Issue
Install FIPS-kernel and then enable FIPS mode. Salt goes from working to broken with the error-output as in the first section.

### Versions Report

~~~
$ salt-call --versions-report
Salt Version:
           Salt: 2015.8.5

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Aug 18 2016, 15:58:25)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.28.3.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
~~~

**Comment by Ch3LL** [comment]
@ferricoxide looks like I am able to replicate this with the following test case.

1. Enabled fips following [this](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Security_Guide/chap-Federal_Standards_and_Regulations.html#sec-Enabling-FIPS-Mode) documentation
2. confirm its enabled:

```
[root@ch3ll-fips salt]# cat /proc/sys/crypto/fips_enabled                                          
1
```

3. add state file:

```
[root@ch3ll-fips salt]# cat /srv/salt/test.sls 
run_cmd:
  cmd.run:
    - name: echo test
```

4. Try running `salt-call --local state.sls test` and get same error:

```
ValueError: error:060800A3:digital envelope routines:EVP_DigestInit_ex:disabled for fips
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 8, in <module>
    execfile(__file__)
  File "/root/salt/scripts/salt-call", line 11, in <module>
    salt_call()
  File "/root/salt/salt/scripts.py", line 345, in salt_call
    client.run()
  File "/root/salt/salt/cli/call.py", line 58, in run
    caller.run()
  File "/root/salt/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/root/salt/salt/cli/caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "/root/salt/salt/modules/state.py", line 929, in sls
    high_, errors = st_.render_highstate({saltenv: mods})
  File "/root/salt/salt/state.py", line 3111, in render_highstate
    sls, saltenv, mods, matches)
  File "/root/salt/salt/state.py", line 2778, in render_state
    state_data = self.client.get_state(sls, saltenv)
  File "/root/salt/salt/fileclient.py", line 475, in get_state
    dest = self.cache_file(path, saltenv, cachedir=cachedir)
  File "/root/salt/salt/fileclient.py", line 178, in cache_file
    return self.get_url(path, '', True, saltenv, cachedir=cachedir)
  File "/root/salt/salt/fileclient.py", line 575, in get_url
    url, dest, makedirs, saltenv, cachedir=cachedir)
  File "/root/salt/salt/fileclient.py", line 1074, in get_file
    hash_server = self.hash_file(path, saltenv)
  File "/root/salt/salt/fileclient.py", line 1321, in hash_file
    return self.channel.send(load)
  File "/root/salt/salt/fileserver/__init__.py", line 749, in send
    return getattr(self.fs, cmd)(load)
  File "/root/salt/salt/fileserver/__init__.py", line 584, in file_hash
    return self.servers[fstr](load, fnd)
  File "/root/salt/salt/fileserver/roots.py", line 232, in file_hash
    ret['hsum'] = salt.utils.get_hash(path, __opts__['hash_type'])
  File "/root/salt/salt/utils/__init__.py", line 2011, in get_hash
    hash_obj = hash_type()
ValueError: error:060800A3:digital envelope routines:EVP_DigestInit_ex:disabled for fips
```

I am also seeing this on versions up to 2016.3.2

**Comment by thatch45** [comment]
To run in FIPS mode you need to set:

```
hash_type: sha256
```

The default hash_type is changed int he upcoming feature release to sha256. It is md5 by default because this is only used for file integrity (we could use crc), but to make everyone happy we are changing it to sha256

**Comment by ferricoxide** [comment]
@thatch45  Just so I'm understanding, correctly: just change the hash_type var in my minion configuration file and everything should be golden?

**Comment by thatch45** [comment]
yes, golden :)

**Comment by thatch45** [comment]
you need to set this on any system using FIPS, minion or master

**Comment by ferricoxide** [comment]
Cool. Our primary use-case has been masterless minions. Prior to new security mandates around EL7, we didn't have to broadly account for FIPS bugaboos.

Hopefully, last set of questions:
If I *were* supporting a traditional master/minion(s) setup:
* If only the master were running in FIPS mode, then I'd only need to explicitly set the hash_type on the master but not its minion(s)
* If the master were not running in FIPS mode, but one or more of its minions were running in FIPS mode, I'd only need to set the hash_type on those minions that were running in FIPS mode.

...or is it "if an one end of a master/minion channel is running in FIPS mode, the hash_type has to be set to agree with each other (SHA256)"?

**Comment by thatch45** [comment]
Master and minion do not need to agree on hash_type, so just set the hash type on all systems running FIPS mode, master or minion.

**Comment by ferricoxide** [comment]
Woot. Thanks for the clarity!

**Comment by thatch45** [comment]
Sure thing

**Comment by kitsushadow** [comment]
This does not work in the current version of Salt 3001.2

**Comment by Ch3LL** [comment]
@kitsushadow  can you open a new issue with more details
