### ISSUE TITLE
keyerror: 'user.info' | 'group.info' adding users and groups on aix

### ISSUE THREAD

**Issue by davegiles** [saltstack/salt#35953]
```
local_users.sls:

#Add UNIX Admin Groups
{% for admin_group, gid in pillar.get('admin_groups', {}).items() %}
{{admin_group}}:
  group.present:
    - gid: {{ gid }}
{% endfor %}

#Add UNIX Admins
{% for admin_user, args in pillar.get('admin_users', {}).iteritems() %}
{{admin_user}}:
  user.present:
    - home: /home/{{ admin_user }}
    - uid: {{ args['uid'] }}
    - gid: {{ args['gid'] }}
    - shell: /bin/bash
    - groups:
      - admin
{% if args['ssh-keys'] %}
{{admin_user}}_key:
  ssh_auth.present:
    - user: {{ admin_user }}
    - names:
      {% for key in args['ssh-keys'] %}
      - {{ key }}
      {% endfor %}
{% endif %}
{% endfor %}
```

Pillar Data:

```
##UNIX ADMINS
admin_users:
  ahatch:
    uid: 322
    gid: 322
    ssh-keys:
      - ssh-rsa     AAAAB3NzaC1yc2EAAAABIwAAAQEA2r
CAFL1YpFpfssaMJYg5PFr3FVoFtQ9LhNR2DTdLiA5KSfulE7fS7WTCDQgHDV
dIAlEDdybqTktf0OExRfhmL5Qg6B6b9qYnIL5tChDC79xfby1Aqv/
psIOciAYuy5GaLLmSzUrjJsu+Z2482dCT7svcLhg/1oZ8ZZfVkh6H8wE1JL3eZ0mFQsTsV5
SOFJHb11TKulBciXibeKKNuk1hlT7nDN1wdHa5W6xU775CzQJhG37Yzgl1gA
cSSDY0GXDynbz7TGIc/66FeAoc3N14sHJFLvImvsIL+GmqpDKlaoMkBdTSRNe
HMXGXKNraG2Xjirlbi2o8RZI00gvs/lm1WQ==  ahatch@gvllx000.dolgen.net

admin_groups:
  admin: 1008
[root@gvllx990 common]# salt 'gvlac201.dolgen.net' state.highstate
```

Highstate apply:

```
gvlac201.dolgen.net:
----------
          ID: admin
    Function: group.present
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/opt/salt/lib/python2.7/site-packages/salt/state.py", line 1626, in call
                  **cdata['kwargs'])
                File "/opt/salt/lib/python2.7/site-packages/salt/loader.py", line 1492, in wrapper
                  return f(*args, **kwargs)
                File "/opt/salt/lib/python2.7/site-packages/salt/states/group.py", line 133, in present
                  members)
                File "/opt/salt/lib/python2.7/site-packages/salt/states/group.py", line 49, in _changes
                  lgrp = __salt__['group.info'](name)
                File "/opt/salt/lib/python2.7/site-packages/salt/loader.py", line 900, in __getitem__
                  func = super(LazyLoader, self).__getitem__(item)
                File "/opt/salt/lib/python2.7/site-packages/salt/utils/lazy.py", line 93, in __getitem__
                  raise KeyError(key)
              KeyError: 'group.info'
     Started: 08:33:03.885764
    Duration: 529.316 ms
     Changes:
----------
          ID: ahatch
    Function: user.present
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/opt/salt/lib/python2.7/site-packages/salt/state.py", line 1626, in call
                  **cdata['kwargs'])
                File "/opt/salt/lib/python2.7/site-packages/salt/loader.py", line 1492, in wrapper
                  return f(*args, **kwargs)
                File "/opt/salt/lib/python2.7/site-packages/salt/states/user.py", line 385, in present
                  missing_groups = [x for x in groups if not __salt__['group.info'](x)]
                File "/opt/salt/lib/python2.7/site-packages/salt/loader.py", line 900, in __getitem__
                  func = super(LazyLoader, self).__getitem__(item)
                File "/opt/salt/lib/python2.7/site-packages/salt/utils/lazy.py", line 93, in __getitem__
                  raise KeyError(key)
              KeyError: 'group.info'
     Started: 08:33:04.415783
    Duration: 6.421 ms
     Changes:
----------
          ID: ahatch_key
    Function: ssh_auth.present
        Name: ssh-rsa     AAAAB3NzaC1yc2EAAAABIwAAAQEA2rCAFL1YpFpfssaMJYg5PFr3FVoFtQ9LhNR2DTdLiA5KSful    E7fS7WTCDQgHDVdIAlEDdybqTktf0OExRfhmL5Qg6B6b9qYnIL5tChDC79xfby1Aqv/psIOciAYuy5    GaLLmSzUrjJsu+Z2482dCT7svcLhg/1oZ8ZZfVkh6H8wE1JL3eZ0mFQsTsV5SOFJHb11TKulBciXi    beKKNuk1hlT7nDN1wdHa5W6xU775CzQJhG37Yzgl1gAcSSDY0GXDynbz7TGIc/66FeAoc3N14sH    JFLvImvsIL+GmqpDKlaoMkBdTSRNeHMXGXKNraG2Xjirlbi2o8RZI00gvs/lm1WQ==     ahatch@gvllx000.dolgen.net
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/opt/salt/lib/python2.7/site-packages/salt/state.py", line 1626, in call
                  **cdata['kwargs'])
                File "/opt/salt/lib/python2.7/site-packages/salt/loader.py", line 1492, in wrapper
                  return f(*args, **kwargs)
                File "/opt/salt/lib/python2.7/site-packages/salt/states/ssh_auth.py", line 330, in present
                  config)
                File "/opt/salt/lib/python2.7/site-packages/salt/modules/ssh.py", line 668, in set_auth_key
                  uinfo = __salt__['user.info'](user)
                File "/opt/salt/lib/python2.7/site-packages/salt/loader.py", line 900, in __getitem__
                  func = super(LazyLoader, self).__getitem__(item)
                File "/opt/salt/lib/python2.7/site-packages/salt/utils/lazy.py", line 93, in __getitem__
                  raise KeyError(key)
              KeyError: 'user.info'
     Started: 08:33:04.422682
    Duration: 7.286 ms
     Changes:

Summary for gvlac201.dolgen.net
------------
Succeeded: 0
Failed:    3
------------
Total states run:     3
```

test.versions from aix minion:

```
[root@gvllx990 ~]# salt 'gvlac201.dolgen.net' test.versions
gvlac201.dolgen.net:
    Salt Version:
               Salt: 2015.8.8.2

    Dependency Versions:
             Jinja2: 2.7.3
           M2Crypto: Not Installed
               Mako: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.3.1
             Python: 2.7.5 (default, Mar 18 2016, 15:00:32)
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5
               cffi: Not Installed
           cherrypy: 3.2.3
           dateutil: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
            libgit2: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.5
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: Not Installed
            timelib: 0.2.4

    System Versions:
               dist:
            machine: 00F7CCA44C00
            release: 1
```

**Comment by Ch3LL** [comment]
thanks @davegiles looks like we definitely need to get this fixed up so the user and ssh_auth states work on aix.

**Comment by dmurphy18** [comment]
Waiting for QA in next point release

**Comment by cachedout** [comment]
@dmurphy18 Can you clarify what you mean by the above comment? Has QA been specifically assigned to test this on AIX? I can't find any issue tracking that request.

**Comment by dmurphy18** [comment]
@cachedout They will test it as part of the Salt 2016.11.4 for AIX release, otherwise it would require doing special builds on AIX for QA to test, builds taking 1/2 day.

If issue with the fixes, then patch and rebuild.  Given most changes for AIX support are bound by AIX platform checks, this was consider acceptable practice

**Comment by dmurphy18** [comment]
Closing this since if QA find an issue, they will open an issue to track it
