### ISSUE TITLE
salt-cloud azure delete_input_endpoint : TypeError: list indices must be integers, not str

### ISSUE THREAD

**Issue by jagguli** [saltstack/salt#36063]
### Setup
```salt-cloud -f delete_input_endpoint azure service=myservice deployment=mydeployment role=Owner name=SSH```

```
[ERROR   ] There was an error running the function: list indices must be integers, not str
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 274, in run
    self.function_provider, self.function_name, kwargs
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1598, in do_function
    call='function', kwargs=kwargs
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/msazure.py", line 2249, in delete_input_endpoint
    activity='delete',
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/msazure.py", line 2146, in update_input_endpoint
    old_endpoints = list_input_endpoints(kwargs, call='function')
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/msazure.py", line 2053, in list_input_endpoints
    input_endpoint = item['Role']['ConfigurationSets']['ConfigurationSet']['InputEndpoints']['InputEndpoint']
TypeError: list indices must be integers, not str
```

(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report

```
salt/srv:» salt-cloud --versions-report                                                                                                                                                                                   [0] [master] 04:18:24
/usr/local/lib/python2.7/dist-packages/cffi/model.py:526: UserWarning: 'git_checkout_notify_t' has no values explicitly defined; next version will refuse to guess which integer type it is meant to be (unsigned/signed, int/long)
  % self._get_c_name())
/usr/local/lib/python2.7/dist-packages/cffi/model.py:526: UserWarning: 'git_merge_flag_t' has no values explicitly defined; next version will refuse to guess which integer type it is meant to be (unsigned/signed, int/long)
  % self._get_c_name())
Salt Version:
            Salt: 2016.3.3

Dependency Versions:
 Apache Libcloud: 0.20.0
            cffi: 1.7.0
        cherrypy: 8.1.0
        dateutil: 2.5.3
           gitdb: 0.5.4
       gitpython: 0.3.2 RC1
           ioflo: Not Installed
          Jinja2: 2.7.3
         libgit2: 0.24.0
         libnacl: Not Installed
        M2Crypto: Not Installed
            Mako: Not Installed
    msgpack-pure: Not Installed
  msgpack-python: 0.4.2
    mysql-python: 1.2.3
       pycparser: 2.14
        pycrypto: 2.6.1
          pygit2: 0.24.1
          Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
    python-gnupg: Not Installed
          PyYAML: 3.11
           PyZMQ: 14.4.0
            RAET: Not Installed
           smmap: 0.8.2
         timelib: Not Installed
         Tornado: 4.2.1
             ZMQ: 4.0.5

System Versions:
            dist: debian 8.5
         machine: x86_64
         release: 3.16.0-4-amd64
          system: Linux
         version: debian 8.5

```

**Comment by Ch3LL** [comment]
@jagguli it looks like [here](https://github.com/saltstack/salt/blob/develop/salt/cloud/clouds/msazure.py#L2057) in the code its trying to grab some dictionary value but `item` is currently the loop for the keys of data. I'm wondering if the intention was to do `data['Role']['ConfigurationSets']['ConfigurationSet']['InputEndpoints']['InputEndpoint']` either inside the loop or outside. Looks like we definitely need to get this fixed up thanks!

**Comment by jagguli** [comment]
Same issue with ```list_input_endpoints```
