### ISSUE TITLE
Error while installing openstack using salt

### ISSUE THREAD

**Issue by Devaraj123** [saltstack/salt#36064]
### Description of Issue/Question

Getting below error while installing openstack kilo multinode setup using salt

``` bash
2016-09-05 23:13:42,183 [salt.loader      ][DEBUG   ][17262] Error loading states.npm: 'npm' binary not found on system
2016-09-05 23:13:42,185 [salt.utils.lazy  ][DEBUG   ][17262] LazyLoaded cyg.list
2016-09-05 23:13:42,185 [salt.utils.lazy  ][DEBUG   ][17262] LazyLoaded postgres.group_create
2016-09-05 23:13:42,186 [salt.utils.lazy  ][DEBUG   ][17262] LazyLoaded pecl.list
2016-09-05 23:13:42,193 [salt.utils.lazy  ][DEBUG   ][17262] LazyLoaded win_path.rehash
2016-09-05 23:13:42,196 [salt.utils.lazy  ][DEBUG   ][17262] LazyLoaded zk_concurrency.lock
2016-09-05 23:13:42,196 [salt.utils.lazy  ][DEBUG   ][17262] LazyLoaded ps.pkill
2016-09-05 23:13:42,210 [salt.utils.lazy  ][DEBUG   ][17262] Could not LazyLoad glance.image_present
2016-09-05 23:13:42,210 [salt.minion      ][WARNING ][17262] The minion function caused an exception
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1161, in _thread_return
    return_data = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 523, in highstate
    whitelist=kwargs.get('whitelist')
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2968, in call_highstate
    return self.state.call_high(high)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2067, in call_high
    ret = dict(list(disabled.items()) + list(self.call_chunks(chunks).items()))
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1623, in call_chunks
    running = self.call_chunk(low, running, chunks)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1769, in call_chunk
    self._mod_init(low)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 612, in _mod_init
    self.states['{0}.{1}'.format(low['state'], low['fun'])]  # pylint: disable=W0106
  File "/usr/lib/python2.7/dist-packages/salt/utils/lazy.py", line 90, in __getitem__
    raise KeyError(key)
KeyError: 'glance.image_present'
```
### Setup

(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

cat environment.sls

``` yaml
environment_name: "ubuntu_openstack"

openstack_series: "kilo"

db_engine: "mysql"

message_queue_engine: "rabbitmq"

reset: "hard"

debug_mode: True

system_upgrade: True

hosts:
  "<controller host name>": "<controller IP>"
  "<network host name>": "<network IP>"
  "<storage host name>": "<storage IP>"
  "<compute host name>": "<compute IP>"

controller: "<controller host name>"
network: "<network host name>"
storage:
  - "<storage host name>"
compute:
  - "<compute host name>"

cinder:
  volumes_group_name: "cinder-volumes"
  volumes_path: "/var/lib/cinder/cinder-volumes"
  volumes_group_size: "1"
  loopback_device: "/dev/loop0"

nova:
  cpu_allocation_ratio: "16"
  ram_allocation_ratio: "1.5"

glance:
  images:
    cirros:
      user: "admin"
      tenant: "admin"
      parameters:
        min_disk: "1"
        min_ram: "0"
        copy_from: "http://download.cirros-cloud.net/0.3.3/cirros-0.3.3-x86_64-disk.img"
        disk_format: "qcow2"
        container_format: "bare"
        is_public: True
        protected: False
```
### Steps to Reproduce Issue

(Include debug logs if possible and relevant.)
### Versions Report

(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Salt master versions**

``` bash
salt --versions-report
                  Salt: 2015.5.3
                Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: Not Installed
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1trusty1
```

**Salt-minion version**

``` bash
salt-minion --version
salt-minion 2015.5.3 (Lithium)
```

**Comment by jtand** [comment]
@Devaraj123 Do you have glanceclient installed? Usually when those keyerrors happen that's the reason. Let me know if you need me to dig further into it! 

Thanks!

**Comment by rallytime** [comment]
@Devaraj123 Can you also post the command and/or states that you're running when you see this error? The stack-trace is you're posting is going through the loader looking for the `glance.image_present` state module function. However, the glance state wasn't introduced to salt until 2015.8.
