### ISSUE TITLE
pkg state stacktraces on Windows on Carbon and develop

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#36087]
### Description of Issue/Question
Attempting to execute a pkg state on Windows causes a stacktrace.

### Setup
Install Salt from Carbon branch or develop branch

### Steps to Reproduce Issue

```
root@mymaster:~# salt davewintest state.single pkg.installed name=filezilla test=True
davewintest:
----------
          ID: filezilla
    Function: pkg.installed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "C:\salt\bin\lib\site-packages\salt\state.py", line 1744, in call
                  **cdata['kwargs'])
                File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1704, in wrapper
                  return f(*args, **kwargs)
                File "C:\salt\bin\lib\site-packages\salt\states\pkg.py", line 1252, in installed
                  **kwargs)
                File "C:\salt\bin\lib\site-packages\salt\states\pkg.py", line 353, in _find_install_targets
                  pkginfo = _get_package_info(name, saltenv=kwargs['saltenv'])
                File "C:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 1455, in _get_package_info
                  return get_repo_data(saltenv).get('repo', {}).get(name, {})
                File "C:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 1395, in get_repo_data
                  (repo_remote, repocache_dir) = _get_repo_src_dest(saltenv)
                File "C:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 489, in _get_repo_src_dest
                  url_parts = _urlparse(winrepo_source_dir)
              NameError: global name '_urlparse' is not defined
     Started: 13:01:00.628000
    Duration: 118834.0 ms
     Changes:   

Summary for davewintest
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time: 118.834 s
```

This was introduced by  https://github.com/saltstack/salt/pull/35899

I believe I have a fix. Testing right now.

**Comment by damon-atkins** [comment]
Works fine without that.... Why am I different to you?

**Comment by damon-atkins** [comment]
@UtahDave by the way thanks for finding this.  Just want to understand how highstate works and state.single does not with the name spaces in states/pkg.py
