### ISSUE TITLE
Windows stacktrace upon startup on Carbon

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#36093]
### Description of Issue/Question
Windows stacktraces upon startup on carbon branch

### Setup
Install Salt from carbon branch on Windows.

### Steps to Reproduce Issue
```
[DEBUG   ] schedule: This job was scheduled with jid_include, adding to cache (jid_include defaults to True)
[DEBUG   ] schedule: This job was scheduled with a max number of 2
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\salt\bin\lib\multiprocessing\forking.py", line 381, in main
    self = load(from_parent)
  File "C:\salt\bin\lib\pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "C:\salt\bin\lib\pickle.py", line 864, in load
    dispatch[key](self)
  File "C:\salt\bin\lib\pickle.py", line 1089, in load_newobj
    obj = cls.__new__(cls, *args)
TypeError: __new__() takes at least 3 arguments (1 given)
```

Salt appears to actually work in spite of this.

### Versions Report
Carbon branch

**Comment by UtahDave** [comment]
Running with `-l trace` gives identical output.

**Comment by UtahDave** [comment]
OK, git bisect to the rescue.  It appears that this PR introduced this stacktrace:

https://github.com/saltstack/salt/pull/33664
