### ISSUE TITLE
 Problem with nova driver in salt-cloud and missing volume endpoints in some regions

### ISSUE THREAD

**Issue by syndicut** [saltstack/salt#36108]
### Description of Issue/Question

We have a private multi-region openstack installation. Volume endpoints in our installation are defined only in certain regions. When trying to test nova driver with our installation I get error about missing volume endpoint in region.
### Setup

```
# conf/cloud.providers.d/test-openstack.conf
test-openstack:
  driver: nova
  identity_url: 'https://<identity_url>/v2.0'
  compute_name: compute
  service_type: compute
  compute_region: region3
  availability_zone: nova
  user: <user>
  tenant: <tenant>
  password: <password>
  ssh_key_name: <user>
  networks:
    - fixed:
      - da6bc2ea-96ed-4c20-a7ef-1d1e034cea37
```
### Steps to Reproduce Issue

openstack installation with volume service only in region1 and region2

```
$ sudo salt-cloud -c conf/ --list-sizes test-openstack
[ERROR   ] Failed to get the output of 'nova.avail_sizes()': Unable to find region in [{u'adminURL': u'https://<volume_endpoint_1>/v2/ec6e9502f4cc4390a9d85190545dcd97', u'region': u'<region1>', u'internalURL': u'http://<volume_endpoint_1>/v2/ec6e9502f4cc4390a9d85190545dcd97', u'publicURL': u'https://<volume_endpoint_1>/v2/ec6e9502f4cc4390a9d85190545dcd97'}, {u'adminURL': u'https://<volume_endpoint_2>/v2/ec6e9502f4cc4390a9d85190545dcd97', u'region': u'<region2>', u'internalURL': u'http://<volume_endpoint_2>/v2/ec6e9502f4cc4390a9d85190545dcd97', u'publicURL': u'https://<volume_endpoint_2>/v2/ec6e9502f4cc4390a9d85190545dcd97'}].
Traceback (most recent call last):
  File "/Users/syndicut/miniconda2/lib/python2.7/site-packages/salt/cloud/__init__.py", line 910, in size_list
    data[alias][driver] = self.clouds[fun]()
  File "/Users/syndicut/miniconda2/lib/python2.7/site-packages/salt/cloud/clouds/nova.py", line 931, in avail_sizes
    conn = get_conn()
  File "/Users/syndicut/miniconda2/lib/python2.7/site-packages/salt/cloud/clouds/nova.py", line 273, in get_conn
    conn = nova.SaltNova(**kwargs)
  File "/Users/syndicut/miniconda2/lib/python2.7/site-packages/salt/utils/openstack/nova.py", line 273, in __init__
    region_name
  File "/Users/syndicut/miniconda2/lib/python2.7/site-packages/salt/utils/openstack/nova.py", line 163, in get_entry
    raise SaltCloudSystemExit('Unable to find {0} in {1}.'.format(key, dict_))
SaltCloudSystemExit: Unable to find region in [{u'adminURL': u'https://<volume_endpoint_1>/v2/ec6e9502f4cc4390a9d85190545dcd97', u'region': u'<region1>', u'internalURL': u'http://<volume_endpoint_1>/v2/ec6e9502f4cc4390a9d85190545dcd97', u'publicURL': u'https://<volume_endpoint_1>/v2/ec6e9502f4cc4390a9d85190545dcd97'}, {u'adminURL': u'https://<volume_endpoint_2>/v2/ec6e9502f4cc4390a9d85190545dcd97', u'region': u'<region2>', u'internalURL': u'http://<volume_endpoint_2>/v2/ec6e9502f4cc4390a9d85190545dcd97', u'publicURL': u'https://<volume_endpoint_2>/v2/ec6e9502f4cc4390a9d85190545dcd97'}].
```
### Versions Report

```
salt-cloud --versions-report
Salt Version:
            Salt: 2016.3.2

Dependency Versions:
 Apache Libcloud: 1.1.0
            cffi: 1.7.0
        cherrypy: Not Installed
        dateutil: Not Installed
           gitdb: Not Installed
       gitpython: Not Installed
           ioflo: Not Installed
          Jinja2: 2.8
         libgit2: Not Installed
         libnacl: Not Installed
        M2Crypto: Not Installed
            Mako: Not Installed
    msgpack-pure: Not Installed
  msgpack-python: 0.4.8
    mysql-python: Not Installed
       pycparser: 2.14
        pycrypto: 2.6.1
          pygit2: Not Installed
          Python: 2.7.11 |Continuum Analytics, Inc.| (default, Dec  6 2015, 18:57:58)
    python-gnupg: Not Installed
          PyYAML: 3.11
           PyZMQ: 15.4.0
            RAET: Not Installed
           smmap: Not Installed
         timelib: Not Installed
         Tornado: 4.4.1
             ZMQ: 4.1.5

System Versions:
            dist:
         machine: x86_64
         release: 13.4.0
          system: Darwin
         version: 10.9.5 x86_64
```

**Comment by gtmanfred** [comment]
I will take a look at this later today, because you shouldn't be required to have volume endpoints
