### ISSUE TITLE
Stack trace instead of useful error when running salt-run winrepo.update_git_repos

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#36127]
### Description of Issue/Question

When attempting to run the following command: `salt-run winrepo.update_git_repos` I see the following error and it does not update the repos. I understand that I am getting this error because gitpython or pygit2 is not installed but there needs to be a more useful error if these requirements are not met:

```
[DEBUG   ] Sending event - data = {'fun_args': [], 'jid': '20160907212716126825', 'return': 'Exception occurred in runner winrepo.update_git_repos: Traceback (most recent call last):\n  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 377, in _low\n    data[\'return\'] = self.functions[fun](*args, **kwargs)\n  File "/usr/lib/python2.7/dist-packages/salt/runners/winrepo.py", line 256, in update_git_repos\n    force_reset=True)\n  File "/usr/lib/python2.7/dist-packages/salt/states/git.py", line 595, in latest\n    saltenv=__env__)\nNameError: global name \'__env__\' is not defined\n', 'success': False, '_stamp': '2016-09-07T21:27:16.473342', 'user': 'root', 'fun': 'runner.winrepo.update_git_repos'}
[DEBUG   ] LazyLoaded nested.output
Exception occurred in runner winrepo.update_git_repos: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 377, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/runners/winrepo.py", line 256, in update_git_repos
    force_reset=True)
  File "/usr/lib/python2.7/dist-packages/salt/states/git.py", line 595, in latest
    saltenv=__env__)
NameError: global name '__env__' is not defined
[DEBUG   ] LazyLoaded local_cache.prep_jid
[INFO    ] Runner completed: 20160907212716126825
[DEBUG   ] Runner return: Exception occurred in runner winrepo.update_git_repos: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 377, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/runners/winrepo.py", line 256, in update_git_repos
    force_reset=True)
  File "/usr/lib/python2.7/dist-packages/salt/states/git.py", line 595, in latest
    saltenv=__env__)
NameError: global name '__env__' is not defined
```
### Steps to Reproduce Issue
1. Make sure gitpython or pygit2 are not installed on master
2. run `salt-run winrepo.update_git_repos`

Also once gitpython is installed I still cannot update the repo due to this issue: #36095
### Versions Report

```
root@saltmaster:~# salt --versions-report
Salt Version:
           Salt: 2016.9.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-65-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by anirudh-janga** [comment]
installing GitPython worked, thanks!

`pip install GitPython`

**Comment by UtahDave** [comment]
@twangboy Hey, this is still a problem.  It would be nice to get better output here.
