### ISSUE TITLE
Stack trace instead of useful error when running pkg.installed on windows

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#36128]
### Description of Issue/Question

When attempting to run `pkg.installed` state on a windows minion it stacktraces if `salt-run winrepo.update_git_repos` and `pkg.refresh_db` had not been previously run. It would be more appropriate to add an error stating the win repo needs to be updated and the minion needs to refresh its db. Here is the stack trace:

```
----------
          ID: install-vim
    Function: pkg.installed
        Name: firefox
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "C:\salt\bin\lib\site-packages\salt\state.py", line 1744, in call
                  **cdata['kwargs'])
                File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1704, in wrapper
                  return f(*args, **kwargs)
                File "C:\salt\bin\lib\site-packages\salt\states\pkg.py", line 1250, in installed
                  **kwargs)
                File "C:\salt\bin\lib\site-packages\salt\states\pkg.py", line 351, in _find_install_targets
                  pkginfo = _get_package_info(name, saltenv=kwargs['saltenv'])
                File "C:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 1455, in _get_package_info
                  return get_repo_data(saltenv).get('repo', {}).get(name, {})
                File "C:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 1395, in get_repo_data
                  (repo_remote, repocache_dir) = _get_repo_src_dest(saltenv)
              NameError: global name '_get_repo_src_dest' is not defined
     Started: 15:37:26.694000
    Duration: 94.0 ms
     Changes:   
```
### Setup

salt-master and windows minion. Make sure `salt-run winrepo.update_git_repos` or `salt -G 'os:windows' pkg.refresh_db` have not been run.

Using the following state file:

```
install-vim:
  pkg.installed:
    - name: firefox
```

Run `salt 'win*' state.sls install` and you will see this error
### Versions Report

```
win2012:
    Salt Version:
               Salt: 2016.9.0

    Dependency Versions:
               cffi: 1.7.0
           cherrypy: 7.1.0
           dateutil: 2.5.3
              gitdb: 0.6.4
          gitpython: 2.0.8
              ioflo: 1.5.5
             Jinja2: 2.8
            libgit2: Not Installed
            libnacl: 1.4.5
           M2Crypto: Not Installed
               Mako: 1.0.4
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.14
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
       python-gnupg: 0.3.8
             PyYAML: 3.11
              PyZMQ: 15.3.0
               RAET: Not Installed
              smmap: 0.9.0
            timelib: 0.2.4
            Tornado: 4.4.1
                ZMQ: 4.1.5

    System Versions:
               dist:   
            machine: AMD64
            release: 8
             system: Windows
            version: 8 6.2.9200 SP0 Multiprocessor Free
```

**Comment by damon-atkins** [comment]
This is a repeat of #36128  please close.

**Comment by Ch3LL** [comment]
@damon-atkins did you mean to mention a different issue? This is 36128.

**Comment by damon-atkins** [comment]
Yep bad paste #36087

**Comment by damon-atkins** [comment]
@Ch3LL please close

**Comment by Ch3LL** [comment]
imo this is different, although i'm not sure the exact situation occurs where that issue happens. But they are different errors and I just want a more useful error if the winrepo needs to be refreshed on the minion if it never had completed that command before.
