### ISSUE TITLE
carbon: stack trace when ctrl+c using salt-ssh

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#36172]
### Description of Issue/Question
When attempting to cancel the execution while running salt-ssh command I get this stack trace:

```
Process MultiprocessingProcess-3:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/site-packages/salt/utils/process.py", line 643, in _run
    return self._original_run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 417, in handle_routine
    stdout, stderr, retcode = single.run()
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 832, in run
    stdout, retcode = self.run_wfunc()
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 878, in run_wfunc
    opts_pkg = pre_wrapper['test.opts_pkg']()  # pylint: disable=E1102
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/wrapper/__init__.py", line 117, in caller
    stdout, stderr, retcode = single.cmd_block()
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 1087, in cmd_block
    stdout, stderr, retcode = self.shim_cmd(cmd_str)
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 1047, in shim_cmd
    return self.shell.exec_cmd(cmd_str)
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/shell.py", line 313, in exec_cmd
    ret = self._run_cmd(cmd)
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/shell.py", line 391, in _run_cmd
    time.sleep(0.01)
KeyboardInterrupt
```

### Steps to Reproduce Issue
1. `salt '*' test.sleep 30`
2. ctrl + c
### Versions Report

```
[root@localhost ~]# salt --versions-report
Salt Version:
           Salt: 2016.9.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.0.1406 Core
        machine: x86_64
        release: 3.10.0-123.6.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.0.1406 Core
```

**Comment by Ch3LL** [comment]
I tested this pr: https://github.com/saltstack/salt/pull/35923 and this is fixed on the head of 2016.3 and carbon. closing
