### ISSUE TITLE
unsupported url scheme: running state with powershell cmd.script - works with cmd.run

### ISSUE THREAD

**Issue by davegiles** [saltstack/salt#36191]
state file:

```
Copy the PS1 script to the local filesystem:
  file.managed:
    - name: c:\dsc\script.ps1
    - source: salt://powershell/applog.ps1
    - makedirs: True

Execute the DSC configuration script:
  cmd.run:  <===============
    - name: c:\dsc\script.ps1
    - cwd: c:\dsc
    - shell: powershell
    - replace: True
    - create: True
```

state run with cmd.run:

```
root@master:~# salt 'win*' state.apply morgan.local
win2012r2:
----------
          ID: Copy the PS1 script to the local filesystem
    Function: file.managed
        Name: c:\dsc\script.ps1
      Result: True
     Comment: File c:\dsc\script.ps1 is in the correct state
     Started: 11:10:56.786000
    Duration: 47.0 ms
     Changes:
----------
          ID: Execute the DSC configuration script
    Function: cmd.run
        Name: c:\dsc\script.ps1
      Result: True
     Comment: Command "c:\dsc\script.ps1" run
     Started: 11:10:56.833000
    Duration: 859.0 ms
     Changes:
              ----------
              pid:
                  464
              retcode:
                  0
              stderr:
              stdout:

                  TaskPath                                       TaskName
                  --------                                       --------
                  \                                              AppLog

Summary for win2012r2
------------
Succeeded: 2 (changed=1)
Failed:    0
------------
Total states run:     2
root@master:~#
```

changing the cmd.run to cmd.script in the state:

```
Copy the PS1 script to the local filesystem:
  file.managed:
    - name: c:\dsc\script.ps1
    - source: salt://powershell/applog.ps1
    - makedirs: True

Execute the DSC configuration script:
  cmd.script:  <===============
    - name: c:\dsc\script.ps1
    - cwd: c:\dsc
    - shell: powershell
    - replace: True
    - create: True
```

state run with cmd.script:

```
root@master:~# salt 'win*' state.apply morgan.local
win2012r2:
----------
          ID: Copy the PS1 script to the local filesystem
    Function: file.managed
        Name: c:\dsc\script.ps1
      Result: True
     Comment: File c:\dsc\script.ps1 is in the correct state
     Started: 11:13:22.036000
    Duration: 31.0 ms
     Changes:
----------
          ID: Execute the DSC configuration script
    Function: cmd.script
        Name: c:\dsc\script.ps1
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "C:\salt\bin\lib\site-packages\salt\state.py", line 1733, in call
                  **cdata['kwargs'])
                File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1651, in wrapper
                  return f(*args, **kwargs)
                File "C:\salt\bin\lib\site-packages\salt\states\cmd.py", line 1099, in script
                  cmd_all = __salt__['cmd.script'](source, python_shell=True, **cmd_kwargs)
                File "C:\salt\bin\lib\site-packages\salt\modules\cmdmod.py", line 2013, in script
                  fn_ = __salt__['cp.cache_file'](source, saltenv)
                File "C:\salt\bin\lib\site-packages\salt\modules\cp.py", line 421, in cache_file
                  result = _client().cache_file(path, saltenv)
                File "C:\salt\bin\lib\site-packages\salt\fileclient.py", line 178, in cache_file
                  return self.get_url(path, '', True, saltenv, cachedir=cachedir)
                File "C:\salt\bin\lib\site-packages\salt\fileclient.py", line 706, in get_url
                  **get_kwargs
                File "C:\salt\bin\lib\site-packages\salt\utils\http.py", line 484, in query
                  **req_kwargs
                File "C:\salt\bin\lib\site-packages\tornado\httpclient.py", line 102, in fetch
                  self._async_client.fetch, request, **kwargs))
                File "C:\salt\bin\lib\site-packages\tornado\ioloop.py", line 453, in run_sync
                  return future_cell[0].result()
                File "C:\salt\bin\lib\site-packages\tornado\concurrent.py", line 232, in result
                  raise_exc_info(self._exc_info)
                File "<string>", line 3, in raise_exc_info
              ValueError: Unsupported url scheme: c:\dsc\script.ps1
     Started: 11:13:22.082000
    Duration: 0.0 ms
     Changes:

Summary for win2012r2
------------
Succeeded: 1
Failed:    1
------------
Total states run:     2
ERROR: Minions returned with non-zero exit code
root@master:~#
```

master info:

```
root@master:~# salt --versions
Salt Version:
           Salt: 2016.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.4.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-36-generic
         system: Linux
        version: Ubuntu 16.04 xenial

root@master:~#
```

minion info:

```
root@master:~# salt 'win*' test.versions
win2012r2:
    Salt Version:
               Salt: 2016.3.2

    Dependency Versions:
               cffi: 1.6.0
           cherrypy: 5.3.0
           dateutil: 2.5.3
              gitdb: 0.6.4
          gitpython: 2.0.2
              ioflo: 1.5.3
             Jinja2: 2.8
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: 1.0.4
       msgpack-pure: Not Installed
     msgpack-python: 0.4.7
       mysql-python: Not Installed
          pycparser: 2.14
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
       python-gnupg: 0.3.8
             PyYAML: 3.11
              PyZMQ: 15.2.0
               RAET: Not Installed
              smmap: 0.9.0
            timelib: 0.2.4
            Tornado: 4.3
                ZMQ: 4.1.2

    System Versions:
               dist:
            machine: AMD64
            release: 8.1
             system: Windows
            version: 8.1 6.3.9600  Multiprocessor Free

root@master:~#
```

**Comment by Ch3LL** [comment]
@davegiles does this occur with any powershell script or is it limited to the one you are attempting to run?Trying to determine if there is something in the powershell script that is causing this stack trace. Thanks

**Comment by davegiles** [comment]
@Ch3LL, multiple powershell scripts causing the same issue but only with cmd.script, cmd.run works fine...

**Comment by Ch3LL** [comment]
okay great thanks for the additional info

**Comment by twangboy** [comment]
@davegiles This is because `cms.script` is designed to pull a script down from a url and run it. It kind of does what you were attempting to do in the state file with one command. So something like this should work:

```
run_script:
  cmd.script:
    - source: salt://powershell/applog.ps1
    - shell: powershell
```

There is no `create` option in `cmd.shell`. There is a `creates` option which will check for a file that the script creates and only run the script if the file does not exist.

`cwd` is not needed as the script is copied to a temp directory and run from there... unless you need to specify a specific cwd for the script itself.

There is no `replace` option in `cmd.shell`.

Hopefully this helps.
