### ISSUE TITLE
AttributeError: 'MultiMinion' object has no attribute 'process_manager'

### ISSUE THREAD

**Issue by qurczak** [saltstack/salt#36271]
### Description of Issue/Question

Exception if there are two master IP addresses in minion configuration.
Address 192.168.1.101 is not available on this minion, only 10.1.1.4

There is a bug in my configuration?

Configuration:
/etc/salt/minion
```
master: 
  - 192.168.1.101
  - 10.1.1.4
backup_mode: minion
hash_type: sha256
```

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

```
[root@vps1 salt]# systemctl start salt-minion
[root@vps1 salt]# Sep 13 19:05:48 systemd[1]: Starting The Salt Minion...
Sep 13 19:05:48 systemd[1]: Started The Salt Minion.
Sep 13 19:06:29 salt-minion[17013]: [ERROR   ] Error while bringing up minion for multi-master. Is master at 192.168.1.101 responding?
Sep 13 19:07:19 salt-minion[17013]: [ERROR   ] Error while bringing up minion for multi-master. Is master at 192.168.1.101 responding?
[....] And more ....

### RESTART
[root@vps1 salt]# systemctl restart salt-minion

[root@vps1 salt]# Sep 13 19:07:24 systemd[1]: Stopping The Salt Minion...
Sep 13 19:07:24 salt-minion[17013]: Process Process-1:
Sep 13 19:07:24 salt-minion[17013]: Traceback (most recent call last):
Sep 13 19:07:24 salt-minion[17013]:   File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Sep 13 19:07:24 salt-minion[17013]:     self.run()
Sep 13 19:07:24 salt-minion[17013]:   File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
Sep 13 19:07:24 salt-minion[17013]:     self._target(*self._args, **self._kwargs)
Sep 13 19:07:24 salt-minion[17013]:   File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 85, in minion_process
Sep 13 19:07:24 salt-minion[17013]:     minion.start()
Sep 13 19:07:24 salt-minion[17013]:   File "/usr/lib/python2.7/site-packages/salt/cli/daemons.py", line 349, in start
Sep 13 19:07:24 salt-minion[17013]:     self.minion.tune_in()
Sep 13 19:07:24 salt-minion[17013]:   File "/usr/lib/python2.7/site-packages/salt/minion.py", line 801, in tune_in
Sep 13 19:07:24 salt-minion[17013]:     self.io_loop.start()
Sep 13 19:07:24 salt-minion[17013]:   File "/usr/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 162, in start
Sep 13 19:07:24 salt-minion[17013]:     super(ZMQIOLoop, self).start()
Sep 13 19:07:24 salt-minion[17013]:   File "/usr/lib/python2.7/site-packages/tornado/ioloop.py", line 862, in start
Sep 13 19:07:24 salt-minion[17013]:     event_pairs = self._impl.poll(poll_timeout)
Sep 13 19:07:24 salt-minion[17013]:   File "/usr/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 122, in poll
Sep 13 19:07:24 salt-minion[17013]:     z_events = self._poller.poll(1000*timeout)
Sep 13 19:07:24 salt-minion[17013]:   File "/usr/lib/python2.7/site-packages/zmq/sugar/poll.py", line 99, in poll
Sep 13 19:07:24 salt-minion[17013]:     return zmq_poll(self.sockets, timeout=timeout)
Sep 13 19:07:24 salt-minion[17013]:   File "zmq/backend/cython/_poll.pyx", line 122, in zmq.backend.cython._poll.zmq_poll (zmq/backend/cython/_poll.c:1850)
Sep 13 19:07:24 salt-minion[17013]:   File "zmq/backend/cython/_poll.pyx", line 115, in zmq.backend.cython._poll.zmq_poll (zmq/backend/cython/_poll.c:1705)
Sep 13 19:07:24 salt-minion[17013]:   File "zmq/backend/cython/checkrc.pxd", line 12, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/_poll.c:2084)
Sep 13 19:07:24 salt-minion[17013]:     PyErr_CheckSignals()
Sep 13 19:07:24 salt-minion[17013]:   File "/usr/lib/python2.7/site-packages/salt/cli/daemons.py", line 229, in _handle_signals
Sep 13 19:07:24 salt-minion[17013]:     self.minion.process_manager.stop_restarting()
Sep 13 19:07:24 salt-minion[17013]: AttributeError: 'MultiMinion' object has no attribute 'process_manager'
Sep 13 19:07:24 systemd[1]: Stopped The Salt Minion.
Sep 13 19:07:24 systemd[1]: Starting The Salt Minion...
Sep 13 19:07:24 systemd[1]: Started The Salt Minion.

```

Minion is visible by master (connected through 10.1.1.4)

```
root@asus:/etc/salt# time salt 'vps1' test.ping --out=txt 
vps1: True
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
Salt Version:
           Salt: 2016.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.24.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jun 28 2016, 08:31:05)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.1
            ZMQ: 4.1.5
 
System Versions:
           dist:   
        machine: x86_64
        release: 4.4.19-1-lts-apparmor
         system: Linux
        version: Not Installed
```

**Comment by Ch3LL** [comment]
@qurczak okay I am able to replicate this behavior. It looks like this is fixed in carbon and I believe it was fixed with this commit  5821b39ab8b4bf0aab0fd44b69ecfe20c99cb934  

Just to be clear from what I can tell form my testing is that the minion still restarts correctly but that stack trace just pops up correct?

**Comment by qurczak** [comment]
> Just to be clear from what I can tell form my testing is that the minion still restarts correctly but that stack trace just pops up correct?

Correct. As a example I have another stack trace.

```
[root@vps ~]# systemctl restart salt-minion
[root@vps ~]# Sep 16 14:33:19 systemd[1]: Stopping The Salt Minion...
Sep 16 14:33:19 salt-minion[9116]: Process Process-1:
Sep 16 14:33:19 salt-minion[9116]: Traceback (most recent call last):
Sep 16 14:33:19 salt-minion[9116]:   File "/usr/lib/python2.7/multiprocessing/process.py", line 261, in _bootstrap
Sep 16 14:33:19 salt-minion[9116]:     util._exit_function()
Sep 16 14:33:19 salt-minion[9116]:   File "/usr/lib/python2.7/multiprocessing/util.py", line 321, in _exit_function
Sep 16 14:33:19 salt-minion[9116]:     p._popen.terminate()
Sep 16 14:33:19 salt-minion[9116]:   File "/usr/lib/python2.7/multiprocessing/forking.py", line 171, in terminate
Sep 16 14:33:19 salt-minion[9116]:     os.kill(self.pid, signal.SIGTERM)
Sep 16 14:33:19 salt-minion[9116]:   File "/usr/lib/python2.7/site-packages/salt/cli/daemons.py", line 229, in _handle_signals
Sep 16 14:33:19 salt-minion[9116]:     self.minion.process_manager.stop_restarting()
Sep 16 14:33:19 salt-minion[9116]: AttributeError: 'MultiMinion' object has no attribute 'process_manager'
Sep 16 14:33:19 systemd[1]: Stopped The Salt Minion.
Sep 16 14:33:19 systemd[1]: Starting The Salt Minion...
Sep 16 14:33:19 systemd[1]: Started The Salt Minion.
Sep 16 14:34:00 salt-minion[9244]: [ERROR   ] Error while bringing up minion for multi-master. Is master at 192.168.1.101 responding?
```

**Comment by Ch3LL** [comment]
perfect thanks for the clarification. Since this is fixed in carbon and there is not an apparent harm to the vm other then the stack trace are you okay closing this issue and then re-opening another issue if it shows up again in 2016.9 > once it comes out?

**Comment by qurczak** [comment]
Ok. No problem
