### ISSUE TITLE
Memory leak with out-of-the-box 2016.3.3

### ISSUE THREAD

**Issue by au** [saltstack/salt#36393]
### Description of Issue/Question

Strangely, I've been unable to utilize 2016.3.3 due to consistent memory leaks with salt-master, causing overflow errors in my other processes, rendering my server unusable. This is an out-of-the-box, "oh god i didnt even touch anything" kind of issue for me.

`salt-minion` operates just fine on all my servers, at ~30-40 MiB usage.
### Potential solution

_Somewhere_ within the idle processes, startup processes, there is a leak.

I'm doing research on where to specifically find the leak, but for now, I've migrated to 2015.8.11.
### Setup

A bare Xenial server, 512mb ram. No minions or master configuration \o/

In this report, `master` is the server name, such as in `Using cached minion ID from /etc/salt/minion_id: master`
### Steps to Reproduce Issue

Grab the latest [official Ubuntu 2016.3.3 release](https://repo.saltstack.com/#ubuntu)

Then install, `apt-get install salt-master`

Salt-master will begin after the installation, and begins to consume memory.
### Leak behavior

This behavior is constant whenever salt-master is running, so one can deduce that it's coming from an idle/recurring process, or an initialization function.

After the process reaches the limit of available memory, it caps off and idles.

Without any other minions running, the leak will still occur.
### Error behavior

Overflow errors don't occur when idle, only when a process is attempted to be run.
### Logs

Here's the verbose initialization of salt-master (348 lines): http://pastebin.com/Qk1gA6pS

The notable errors are,

```
[WARNING ] IMPORTANT: Do not use md5 hashing algorithm! Please set "hash_type" to sha256 in Salt Master config!
...
[WARNING ] /usr/lib/python2.7/dist-packages/salt/grains/core.py:1493: DeprecationWarning: The "osmajorrelease" will be a type of an integer.
```

The `"osmajorrelease" will be a type of an integer` error has been fixed in #35972, about 11 days ago.
#### Case 1

As soon as salt-master starts, it instantly begins to leak memory. This is a clean install of 2016.3.3 with `salt-minion` in the background. Before starting salt-master, 

```
$ top
KiB Mem :   500240 total,   283596 free,   119420 used,    97224 buff/cache
KiB Swap:        0 total,        0 free,        0 used.   345288 avail Mem
$ salt-master -d
```

After about 10 seconds of booting up, salt-master consumes about 300 MiB -

```
$ top
KiB Mem :   500240 total,    23036 free,   421328 used,    55876 buff/cache
KiB Swap:        0 total,        0 free,        0 used.    41492 avail Mem
```

...Rendering most memory-intensive usage unusable.
#### Case 2

Here's a progression of memory usage, Each `free -m` is run every 5 seconds.

```
OSError: [Errno 12] Cannot allocate memory
au@master:~# killall salt-master
au@master:~# free -m
              total        used        free      shared  buff/cache   available
Mem:            488          34         380           9          73         421
Swap:             0           0           0
au@master:~# salt-master -d
au@master:~# free -m
              total        used        free      shared  buff/cache   available
Mem:            488         186         198           9         103         267
Swap:             0           0           0
au@master:~# free -m
              total        used        free      shared  buff/cache   available
Mem:            488         373          11           9         103          80
Swap:             0           0           0
au@master:~# free -m
              total        used        free      shared  buff/cache   available
Mem:            488         373          11           9         103          80
```
#### Case 3

With salt-master running idly, with no configuration,

A list of unique processes running salt-master.

```
au@master:~# ps -C salt-master
  PID TTY          TIME CMD
 9930 ?        00:00:00 salt-master
 9931 ?        00:00:00 salt-master
 9932 ?        00:00:00 salt-master
 9935 ?        00:00:00 salt-master
 9990 ?        00:00:03 salt-master
 9992 ?        00:00:02 salt-master
 9994 ?        00:00:00 salt-master
23734 ?        00:00:00 salt-master
24627 ?        00:00:00 salt-master
25071 ?        00:00:00 salt-master
26323 ?        00:00:00 salt-master
```

A memory report map (pmap) of the most recent salt-master process. It's a massive 900 lines long, consuming a total of 360688 kB. This should be _slightly_ helpful.

http://pastebin.com/HbuvPyhB

A memory report from /proc (/proc/$pid/status), showing the usual peak in memory,

```
au@master:~# ps -C salt-minion
  PID TTY          TIME CMD
28761 ?        00:00:00 salt-minion
28762 ?        00:00:00 salt-minion
au@master:~# ps -C salt-master
  PID TTY          TIME CMD
 9930 ?        00:00:00 salt-master
 9931 ?        00:00:00 salt-master
 9932 ?        00:00:00 salt-master
 9935 ?        00:00:00 salt-master
 9990 ?        00:00:06 salt-master
 9992 ?        00:00:02 salt-master
 9994 ?        00:00:00 salt-master
23734 ?        00:00:00 salt-master
24627 ?        00:00:00 salt-master <defunct>
25071 ?        00:00:00 salt-master
26764 ?        00:00:00 salt-master
au@master:~# cat /proc/26784/status
cat: /proc/26784/status: No such file or directory
au@master:~# cd /prov
-bash: cd: /prov: No such file or directory
au@master:~# cd /proc
au@master:/proc# cd 9930
au@master:/proc/9930# cat status
Name:   salt-master
State:  S (sleeping)
Tgid:   9930
Ngid:   0
Pid:    9930
PPid:   1
TracerPid:      0
Uid:    0       0       0       0
Gid:    0       0       0       0
FDSize: 64
Groups: 0
NStgid: 9930
NSpid:  9930
NSpgid: 9929
NSsid:  9929
VmPeak:   358684 kB
VmSize:   358684 kB
VmLck:         0 kB
VmPin:         0 kB
VmHWM:     69384 kB
VmRSS:     61316 kB
VmData:   134204 kB
VmStk:       136 kB
VmExe:      2980 kB
VmLib:     21860 kB
VmPTE:       560 kB
VmPMD:        12 kB
VmSwap:        0 kB
HugetlbPages:          0 kB
Threads:        1
SigQ:   0/1810
SigPnd: 0000000000000000
ShdPnd: 0000000000000000
SigBlk: 0000000000000000
SigIgn: 0000000001001000
SigCgt: 0000000180004a02
CapInh: 0000000000000000
CapPrm: 0000003fffffffff
CapEff: 0000003fffffffff
CapBnd: 0000003fffffffff
CapAmb: 0000000000000000
Seccomp:        0
Cpus_allowed:   1
Cpus_allowed_list:      0
Mems_allowed:   00000000,00000001
Mems_allowed_list:      0
voluntary_ctxt_switches:        2817
nonvoluntary_ctxt_switches:     112
```
### Relation to other issues

When comparing to #29179, things get interesting. 

```
time salt-call state.highstate test=True
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 346, in salt_call
    import salt.cli.call
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 6, in <module>
    from salt.utils import parsers
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 28, in <module>
    import salt.config as config
  File "/usr/lib/python2.7/dist-packages/salt/config/__init__.py", line 41, in <module>
    import salt.utils.sdb
  File "/usr/lib/python2.7/dist-packages/salt/utils/sdb.py", line 9, in <module>
    import salt.loader
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 30, in <module>
    import salt.utils.event
  File "/usr/lib/python2.7/dist-packages/salt/utils/event.py", line 72, in <module>
    import salt.payload
  File "/usr/lib/python2.7/dist-packages/salt/payload.py", line 17, in <module>
    import salt.crypt
  File "/usr/lib/python2.7/dist-packages/salt/crypt.py", line 42, in <module>
    import salt.utils.rsax931
  File "/usr/lib/python2.7/dist-packages/salt/utils/rsax931.py", line 69, in <module>
    libcrypto = _init_libcrypto()
  File "/usr/lib/python2.7/dist-packages/salt/utils/rsax931.py", line 47, in _init_libcrypto
    libcrypto = _load_libcrypto()
  File "/usr/lib/python2.7/dist-packages/salt/utils/rsax931.py", line 31, in _load_libcrypto
    lib = find_library('crypto')
  File "/usr/lib/python2.7/ctypes/util.py", line 248, in find_library
    return _findSoname_ldconfig(name) or _get_soname(_findLib_gcc(name))
  File "/usr/lib/python2.7/ctypes/util.py", line 237, in _findSoname_ldconfig
    f = os.popen('LC_ALL=C LANG=C /sbin/ldconfig -p 2>/dev/null')
OSError: [Errno 12] Cannot allocate memory

real    0m0.644s
user    0m0.208s
sys     0m0.128s
```

And the logs at the time of the previous command,

```
[INFO    ] Process <class 'salt.master.MWorker'> (29545) died with exit status None, restarting...
[DEBUG   ] Started 'salt.master.MWorker' with pid 30187
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: master
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: master
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: master
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: master
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: master
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: master
[DEBUG   ] Reading configuration from /etc/salt/master
[ERROR   ] An un-handled exception from the multiprocessing process 'MWorker-4' was caught:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/process.py", line 616, in _run
    return self._original_run()
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 884, in run
    self.aes_funcs = AESFuncs(self.opts)
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 919, in __init__
    self.masterapi = salt.daemons.masterapi.RemoteFuncs(opts)
  File "/usr/lib/python2.7/dist-packages/salt/daemons/masterapi.py", line 425, in __init__
    rend=False)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 678, in __init__
    self.opts['grains'] = salt.loader.grains(opts)
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 704, in grains
    ret = fun()
  File "/usr/lib/python2.7/dist-packages/salt/grains/core.py", line 1679, in hwaddr_interfaces
    ifaces = _get_interfaces()
  File "/usr/lib/python2.7/dist-packages/salt/grains/core.py", line 1090, in _get_interfaces
    _INTERFACES = salt.utils.network.interfaces()
  File "/usr/lib/python2.7/dist-packages/salt/utils/network.py", line 749, in interfaces
    return linux_interfaces()
  File "/usr/lib/python2.7/dist-packages/salt/utils/network.py", line 627, in linux_interfaces
    stderr=subprocess.STDOUT).communicate()[0]
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1235, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
Process MWorker-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/dist-packages/salt/utils/process.py", line 616, in _run
    return self._original_run()
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 884, in run
    self.aes_funcs = AESFuncs(self.opts)
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 919, in __init__
    self.masterapi = salt.daemons.masterapi.RemoteFuncs(opts)
  File "/usr/lib/python2.7/dist-packages/salt/daemons/masterapi.py", line 425, in __init__
    rend=False)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 678, in __init__
    self.opts['grains'] = salt.loader.grains(opts)
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 704, in grains
    ret = fun()
  File "/usr/lib/python2.7/dist-packages/salt/grains/core.py", line 1679, in hwaddr_interfaces
    ifaces = _get_interfaces()
  File "/usr/lib/python2.7/dist-packages/salt/grains/core.py", line 1090, in _get_interfaces
    _INTERFACES = salt.utils.network.interfaces()
  File "/usr/lib/python2.7/dist-packages/salt/utils/network.py", line 749, in interfaces
    return linux_interfaces()
  File "/usr/lib/python2.7/dist-packages/salt/utils/network.py", line 627, in linux_interfaces
    stderr=subprocess.STDOUT).communicate()[0]
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1235, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
[INFO    ] Process <class 'salt.master.MWorker'> (30187) died with exit status None, restarting...
[DEBUG   ] Started 'salt.master.MWorker' with pid 30269
```

After restarting the worker, the logs loop from then on. This seems to be an error with memory availability, so the problem has already occurred by the highstate (or any commands for that matter).
### Versions Report

```
au@master:~# killall salt-master
au@master:~# salt-master -d
au@master:~# salt --versions-report
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-36-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by Ch3LL** [comment]
@au can you share a sanitized version of your master/minion configs? Also to clarify when do you see the out of memory errors? Is it after restarting the master, running commands against the minion, etc? Just any behavior that would help us to attempt to replicate this issue. 

Also could you see if you are possibly running into these known memory leaks: #29179 or #33890

**Comment by au** [comment]
Good points, I've updated the issue with more detail. But here's some answers

> can you share a sanitized version of your master/minion configs? 

From my tests, there is no need for any configuration. I've made sure to purge /etc/salt after resets. Perhaps there is an underlying cache config that would trigger a memory leak.

> Also to clarify when do you see the out of memory errors? Is it after restarting the master, running commands against the minion, etc? Just any behavior that would help us to attempt to replicate this issue.

I'm so sorry, but salt-master is _always leaking._ As soon as salt-master begins booting, it's already consuming memory. It hasn't run out memory in it's initialization process, though. Simple commands such as `salt-master --version`, `salt-call grains.items`, `salt-call state.highstate` simply don't go through, and end up with a memory allocation error.

The errors occasionally happen within the /etc/salt/master refresh, seen [here](http://pastebin.com/b5UcCJ84).

Because of this, I don't think it's the same leak  as #29179 or #33890, which seem to be leaking at a particular command.

**Comment by kingsquirrel152** [comment]
Sorry for the chatter if this is not applicable. @au By chance do you run any beacons minion side? I know I've been stuck way back at 2015.3 due to this being a persistent problem https://github.com/saltstack/salt/issues/30411 If you're not running any beacons. Feel free to disregard this. Just trying to help.

**Comment by au** [comment]
No worries, @kingsquirrel152. Unfortunately I'm not running any beacons, the issue seems to be on the native salt-master process.

However I'll give 2015.3 a test run, as 2016.3.3 and 2015.8.12 leak on my end. This is so prevalent that I'm worried it's an issue on my side, which would be unfortunate.

**Comment by ahammond** [comment]
Take a look at #36618 ?

**Comment by Ch3LL** [comment]
Okay so i attempted to replicate this and this is what I'm seeing:

1. see what memory usage is at before installing salt-master:

```
vagrant@server:~$ free -m
              total        used        free      shared  buff/cache   available
Mem:            992          73         472           3         446         885
Swap:          1019           0        1019
```

2.  `apt-get install salt-master`
3. After install : 

```
root@server:~# free -m 
              total        used        free      shared  buff/cache   available
Mem:            992         227          97           3         667         728
Swap:          1019           1        1018
```

So it looks like it when from about 472m free of memory to 97. 

I want ot get @cachedout 's eyes on this one to see if that sort of memory usage is to be expected? My memory usage stayed at about 97 free after it started up all the way and it did not continue to increase in memory usage.

**Comment by ahammond** [comment]
Easiest way I can think of to really make it explode is to configure one
minion with transport: tcp, and leave the rest on 0mq.

**Comment by Ch3LL** [comment]
My understanding of @au 's test case did not include editing anything in the configuration files including the transport as he said there was nothing to provide when asking for his minion/master config. Although it is a good point to see if @au  does happen to have any minions on tcp transport he might have forgotten about.

**Comment by ahammond** [comment]
I'm sure it leaks in other situations, too, but that's a sure way to make
it leak fast and hard. :)

**Comment by au** [comment]
Thanks for the update! I haven't configured TCP transport on any minion; there wouldn't be a scenario where a minion would default to TCP, correct?

Thanks a ton @Ch3LL for running the test case; since I have about 360 MiB usage in comparison to your 90, I'll try to isolate the problem on my server.

**Comment by cachedout** [comment]
In order to troubleshoot this, we need to know _which_ of the salt-master procs is leaking. If you have [setproctitle](https://pypi.python.org/pypi/setproctitle) installed, the role of each master process should appear along side it in a process list.

**Comment by au** [comment]
Hi all. I've been using 2015.8.11 for the time being, and have been trying your updates since. 2016.6.11 leaks even faster.

```
$ ps axuf
root      7593  0.0 13.3 354000 66972 ?        S    23:27   0:00 /usr/bin/python /usr/bin/salt-master -d ProcessManager
root      7594  0.0 12.3 338248 61696 ?        S    23:27   0:00  \_ /usr/bin/python /usr/bin/salt-master -d MultiprocessingLoggingQueue
root      7595  0.0 12.5 361384 62800 ?        Sl   23:27   0:00  \_ /usr/bin/python /usr/bin/salt-master -d ZeroMQPubServerChannel
root      7598  0.0 12.5 353348 63016 ?        S    23:27   0:00  \_ /usr/bin/python /usr/bin/salt-master -d EventPublisher
root      7599  0.3 14.1 359060 70600 ?        S    23:27   0:00  \_ /usr/bin/python /usr/bin/salt-master -d Maintenance
root      7600  0.0 12.6 354000 63056 ?        S    23:27   0:00  \_ /usr/bin/python /usr/bin/salt-master -d ReqServer_ProcessManager
root      7601  0.0 12.6 657124 63428 ?        Sl   23:27   0:00      \_ /usr/bin/python /usr/bin/salt-master -d MWorkerQueue
root      7608  0.5 14.4 368724 72260 ?        Sl   23:27   0:00      \_ /usr/bin/python /usr/bin/salt-master -d MWorker-0
root      7609  0.5 14.4 368724 72288 ?        Sl   23:27   0:00      \_ /usr/bin/python /usr/bin/salt-master -d MWorker-1
root      7611  0.5 14.4 368980 72380 ?        Sl   23:27   0:00      \_ /usr/bin/python /usr/bin/salt-master -d MWorker-3
root      7612  0.6 14.4 368984 72388 ?        Sl   23:27   0:00      \_ /usr/bin/python /usr/bin/salt-master -d MWorker-4
root      8346  3.8  0.0      0     0 ?        Z    23:28   0:00      \_ [/usr/bin/python] <defunct>
```

Now, `/usr/bin/python` is a runaway process that I have to kill explicitly, even after `sudo pkill -9 salt-master`.

pmap of one of the runaway /usr/bin/python: http://pastebin.com/raw/NWR5yqqZ

Salt Version:
           Salt: 2016.11.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-36-generic
         system: Linux
        version: Ubuntu 16.04 xenial

Once again, a clean install. I've double checked permissions. Perhaps it's a communications issue with my server. I'll likely end up spinning up a new server, as I'm the only one with this problem. I'll close this.

**Comment by dcodery** [comment]
I have the similar issue. I am running Salt (2016.11.5, Carbon) on a fresh Ubuntu (16.04).
The salt-master consumes about 300MB+ memory, while the salt-minion consumes about 40MB+ memory.

**Comment by oliverdunk** [comment]
Can reproduce the same issue on a fresh Ubuntu 17 VM from Vultr (the $2.50/mt ones).

**Comment by Zhang21** [comment]
I met a `OSError: [Errno 12] Cannot allocate memory` issue yesterday, maybe same with you. 

The  mem usage was gradually increasing(from `40+%` to `90+%`)，caused the host stuck and crash. So I must to reboot my host, after reboot,  the status is ok!

What proplem with my salt？ Is this a mem leak issue? 

thx!

<br/>

the logs:

```py
2019-03-18 15:11:14,867 [salt.utils.process:772 ][ERROR   ][21400] An un-handled exception from the multiprocessing process 'Maintenance-7' was caught:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/process.py", line 765, in _run
    return self._original_run()
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 234, in run 
    salt.daemons.masterapi.clean_old_jobs(self.opts)
  File "/usr/lib/python2.7/dist-packages/salt/daemons/masterapi.py", line 169, in clean_old_jobs
    rend=False,
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 887, in __init__
    self.opts['grains'] = salt.loader.grains(opts)
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 772, in grains
    ret = funcs[key]()
  File "/usr/lib/python2.7/dist-packages/salt/grains/core.py", line 2297, in hwaddr_interfaces
    ifaces = _get_interfaces()
  File "/usr/lib/python2.7/dist-packages/salt/grains/core.py", line 1498, in _get_interfaces
    _INTERFACES = salt.utils.network.interfaces()
  File "/usr/lib/python2.7/dist-packages/salt/utils/network.py", line 1052, in interfaces
    return linux_interfaces()
  File "/usr/lib/python2.7/dist-packages/salt/utils/network.py", line 849, in linux_interfaces
    stderr=subprocess.STDOUT).communicate()[0]
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1235, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```

<br/>


salt info:

```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 12 2018, 14:36:49)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-142-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by Ch3LL** [comment]
ping @DmitryKuzmenko  any chance you can take  look here to try to progress the issue?

**Comment by oliverdunk** [comment]
Not stale.
