### ISSUE TITLE
nacling encrypt pubkey is NoneType, has no len()

### ISSUE THREAD

**Issue by hevel** [saltstack/salt#36433]
### Description of Issue/Question

starting salt-master got an un-handled exception was caught by salt's global excetion handler.
### Setup

transport: raet
hash_type: sha512
master_job_cache: mysql
### Steps to Reproduce Issue

```
Traceback (most recent call last):
  File "/usr/local/bin/salt-master", line 9, in <module>
    load_entry_point('salt==2016.3.3', 'console_scripts', 'salt-master')()
  File "/usr/local/lib/python2.7/dist-packages/salt/scripts.py", line 47, in salt_master
    master.start()
  File "/usr/local/lib/python2.7/dist-packages/salt/cli/daemons.py", line 207, in start
    self.master.start()
  File "/usr/local/lib/python2.7/dist-packages/salt/daemons/flo/__init__.py", line 100, in start
    consolepath=consolepath,
  File "/usr/local/lib/python2.7/dist-packages/ioflo/app/run.py", line 138, in run
    skedder.run()
  File "/usr/local/lib/python2.7/dist-packages/ioflo/base/skedding.py", line 273, in run
    status = tasker.runner.send(tasker.desire)
  File "/usr/local/lib/python2.7/dist-packages/ioflo/base/framing.py", line 634, in makeRunner
    self.recur() #.desire may change here
  File "/usr/local/lib/python2.7/dist-packages/ioflo/base/framing.py", line 445, in recur
    frame.recur()
  File "/usr/local/lib/python2.7/dist-packages/ioflo/base/framing.py", line 1274, in recur
    act()
  File "/usr/local/lib/python2.7/dist-packages/ioflo/base/acting.py", line 107, in __call__
    return (self.actor(**self.parms))
  File "/usr/local/lib/python2.7/dist-packages/ioflo/base/acting.py", line 548, in __call__
    return self.action(**kwa)
  File "/usr/local/lib/python2.7/dist-packages/salt/daemons/flo/core.py", line 581, in action
    stack.manage(cascade=True)
  File "/usr/local/lib/python2.7/dist-packages/raet/road/stacking.py", line 404, in manage
    remote.manage(cascade=cascade, immediate=immediate)
  File "/usr/local/lib/python2.7/dist-packages/raet/road/estating.py", line 349, in manage
    self.stack.alive(uid=self.uid, cascade=cascade)
  File "/usr/local/lib/python2.7/dist-packages/raet/road/stacking.py", line 798, in alive
    aliver.alive()
  File "/usr/local/lib/python2.7/dist-packages/raet/road/transacting.py", line 2433, in alive
    self.stack.allow(uid=self.remote.uid, cascade=self.cascade, timeout=self.timeout)
  File "/usr/local/lib/python2.7/dist-packages/raet/road/stacking.py", line 766, in allow
    allower.hello()
  File "/usr/local/lib/python2.7/dist-packages/raet/road/transacting.py", line 1644, in hello
    cipher, nonce = self.remote.privee.encrypt(plain, self.remote.pubber.key)
  File "/usr/local/lib/python2.7/dist-packages/raet/nacling.py", line 522, in encrypt
    if len(pubkey) == 32:
TypeError: object of type 'NoneType' has no len()
```
### Versions Report

Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: 1.5.2
       cherrypy: 2.3.0
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: 1.6.0
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: 1.5.0
       M2Crypto: 0.21.1
           Mako: 0.7.0
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.3 (default, Mar  1 2015, 12:57:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: 0.6.5
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.2

System Versions:
           dist: debian 7.7 
           machine: x86_64
        release: 3.2.0-4-amd64
         system: Linux
        version: debian 7.7

**Comment by Ch3LL** [comment]
@hevel i'm not seeing that error on a clean debian7 instance using your exact master config. Are you seeing this error when running a particular commad or some other situation?
