### ISSUE TITLE
Minion created with salt-cloud fail to highstate with startup_states: highstate

### ISSUE THREAD

**Issue by aronneagu** [saltstack/salt#36467]
### Description of Issue/Question
Minion fails to highstate when having startup_states: highstate and the instances are created with salt-cloud. The error from salt-run jobs.list_job is

```
Arguments:
Function:
    state.highstate
Minions:
    - test4
Result:
    ----------
    test4:
        ----------
        out:
            nested
        return:
The minion function caused an exception: Traceback (most recent call last):
              File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1332, in _thread_return
                return_data = executor.execute()
              File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 28, in execute
                return self.func(*self.args, **self.kwargs)
              File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 707, in highstate
                mocked=kwargs.get('mock', False))
              File "/usr/lib/python2.7/dist-packages/salt/state.py", line 3341, in __init__
                BaseHighState.__init__(self, opts)
              File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2417, in __init__
                self.avail = self.__gather_avail()
              File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2426, in __gather_avail
                for saltenv in self._get_envs():
              File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2482, in _get_envs
                client_envs = self.client.envs()
              File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 1350, in envs
                return self.channel.send(load)
              File "/usr/lib/python2.7/dist-packages/salt/utils/async.py", line 75, in wrap
                ret = self._block_future(ret)
              File "/usr/lib/python2.7/dist-packages/salt/utils/async.py", line 85, in _block_future
                return future.result()
              File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
                raise_exc_info(self._exc_info)
              File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 876, in run
                yielded = self.gen.throw(*exc_info)
              File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 271, in send
                ret = yield self._crypted_transfer(load, tries=tries, timeout=timeout)
              File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
                value = future.result()
              File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
                raise_exc_info(self._exc_info)
              File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 876, in run
                yielded = self.gen.throw(*exc_info)
              File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 239, in _crypted_transfer
                ret = yield _do_transfer()
              File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
                value = future.result()
              File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
                raise_exc_info(self._exc_info)
              File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 876, in run
                yielded = self.gen.throw(*exc_info)
              File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 225, in _do_transfer
                tries=tries,
              File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
                value = future.result()
              File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
                raise_exc_info(self._exc_info)
              File "<string>", line 3, in raise_exc_info
            SaltReqTimeoutError: Message timed out
StartTime:
    2016, Sep 21 13:02:18.867496
Target:
    test4
Target-type:
    glob
User:
    root
jid:
    20160921130218867496
```

I have started 3 instances and all of them failed with the same error.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Provider file:
```
eu-ireland-app-api:
  minion:
    master: saltstack.optimy.net
    startup_states: highstate
    log_level_logfile: debug

  ssh_interface:
    private_ips

  id: ***
  key: ***

  private_key: /etc/salt/pki/salt-cloud.pem
  keyname: salt-cloud

  location: eu-west-1

  ssh_username: ubuntu

  provider: ec2

  grains:
    role: app-api
```

Profile:
```
eu-ireland-app-api-a:
  provider: eu-ireland-app-api
  image: ami-ed82e39e
  size: t2.micro
  ssh_username: ubuntu
  subnetid: subnet-***
  securitygroupid:
    - sg-***
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
salt-cloud -p eu-ireland-app-api-a testintance

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-74-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

The salt-minion has version 2016.3.3 (Baron)

**Comment by Ch3LL** [comment]
@aronneagu are you able to run a `state.highstate` after they are provisioned?

**Comment by aronneagu** [comment]
Hi Ch3LL,
Unfortunately there is no way to test this anymore.
The instances were part of an AWS testing stack that I deleted yesterday, and on new stack I could not reproduce the issue. I am going to close the ticket and reopen in case it happens again.
