### ISSUE TITLE
salt 2016.3.3+ds-1 on debian 7 fails to start if python-psutil installed

### ISSUE THREAD

**Issue by viq** [saltstack/salt#36533]
### Description of Issue/Question
When `python-psutil` (in my case 0.5.1-1) is installed, salt-minion fails to start with message:
```
# salt-minion 
Traceback (most recent call last):
  File "/usr/bin/salt-minion", line 26, in <module>
    salt_minion()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 109, in salt_minion
    import salt.cli.daemons
  File "/usr/lib/python2.7/dist-packages/salt/cli/daemons.py", line 46, in <module>
    from salt.utils import parsers, ip_bracket
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 28, in <module>
    import salt.config as config
  File "/usr/lib/python2.7/dist-packages/salt/config/__init__.py", line 93, in <module>
    _DFLT_IPC_WBUFFER = _gather_buffer_space() * .5
  File "/usr/lib/python2.7/dist-packages/salt/config/__init__.py", line 82, in _gather_buffer_space
    total_mem = psutil.virtual_memory().total
AttributeError: 'module' object has no attribute 'virtual_memory'
```
Purging 
### Setup
debian 7 amd64 with python-psutil and salt-minion 2016.3.3 installed

### Steps to Reproduce Issue
debian 7 amd64 with python-psutil and salt-minion 2016.3.3 installed
Try to start salt-minion

### Versions Report
(master is 2016.3.3 on debian 8)
```
root@hostname:~# salt-call --versions-report
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 346, in salt_call
    import salt.cli.call
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 6, in <module>
    from salt.utils import parsers
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 28, in <module>
    import salt.config as config
  File "/usr/lib/python2.7/dist-packages/salt/config/__init__.py", line 93, in <module>
    _DFLT_IPC_WBUFFER = _gather_buffer_space() * .5
  File "/usr/lib/python2.7/dist-packages/salt/config/__init__.py", line 82, in _gather_buffer_space
    total_mem = psutil.virtual_memory().total
AttributeError: 'module' object has no attribute 'virtual_memory'
root@hostname:~# apt-get purge python-psutil
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following package was automatically installed and is no longer required:
  cfacter
Use 'apt-get autoremove' to remove it.
The following packages will be REMOVED:
  python-psutil*
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 215 kB disk space will be freed.
Do you want to continue [Y/n]? 
(Reading database ... 38612 files and directories currently installed.)
Removing python-psutil ...
Processing triggers for python-support ...
root@hostname:~# salt-call --versions-report
Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.3 (default, Jun 21 2016, 18:38:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 13.1.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.3
 
System Versions:
           dist: debian 7.11 
        machine: x86_64
        release: 3.2.0-4-amd64
         system: Linux
        version: debian 7.11 
```

**Comment by rallytime** [comment]
@viq Thanks for letting us know. We're using psutils in a couple of places to help with process management, and we need to decide upon a minimum viable version that we should work with (or protect against these kind of errors since they've had many API changes since 0.5.1 was released in 2012.)

Uninstalling python-psutil will work, as you have discovered, or upgrading to a newer version of python-psutil will also work as I tried the next tagged version and I didn't run into this attribute error.

Note for the record: The current version in pip (4.3.1) is what is currently running on our jenkins test suite and is working well there.

**Comment by bbinet** [comment]
I'm also facing this same issue on debian wheezy: salt-minion won't start unless python-psutil package is absent...
The version of python-psutil on wheezy is 0.5.1-1.

@dmurphy18 Any chance you can backport an up to date python-psutil from the saltstack repository (repo.saltstack.com) so that salt-minion won't die if python-psutil is present?

**Comment by dmurphy18** [comment]
@bbinet salt 2016.11.2 should not be dependent on psutils, will use it if present, or at least that is my understanding.  I have a task to add support for psutils as a hard dependency with the next major branch.

I shall take a look into why this issues is occurring.
