### ISSUE TITLE
How to execute a runner from a reactor written in python?

### ISSUE THREAD

**Issue by scubahub** [saltstack/salt#36581]
### Description of Question
I am trying to invoke a runner from a reactor written in python.  However I am getting an exception.

Here is the reactor:
```
#!py
import salt.runner
import salt.config

def run():
  rc = salt.runner.RunnerClient(salt.config.client_config('/etc/salt/master'))
  rc.cmd("test-runner.handle", [data])

  return {}
```

Here is the exception:
```
2016-09-26 20:29:09,917 [salt.utils.reactor][ERROR   ][9642] Failed to render "/srv/salt/base/state/reactors/test-reactor.sls":
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/reactor.py", line 53, in render_reaction
    data=data)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 303, in render_template
    template, self.rend, self.opts['renderer'], **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/template.py", line 95, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/usr/lib/python2.7/site-packages/salt/renderers/py.py", line 112, in render
    'Unknown render error in py renderer'))
SaltRenderError: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 520, in py
    data = mod.run()
  File "/srv/salt/base/state/reactors/test-reactor.sls", line 6, in run
    rc = salt.runner.RunnerClient(salt.config.client_config('/etc/salt/master'))
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 929, in __getattr__
    raise AttributeError(mod_name)
AttributeError: runner
```

### Versions Report
```
Salt Version:
           Salt: 2015.8.11

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-229.14.1.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
```

**Comment by Ch3LL** [comment]
@scubahub can you try using the `__salt__` dunder dictionary alongside the `saltutil.runner` execution module and see if that works. There is an example [here](https://github.com/saltstack/salt/blob/develop/salt/states/saltmod.py#L643)

**Comment by scubahub** [comment]
@Ch3LL Thanks for the pointer, will give that a go asap.

**Comment by scubahub** [comment]
@Ch3LL Im trying the equivalent from the command line (to figure out how to pass arguments) and I don't seem to be able to pass arguments to the runner through saltutil.runner.  ```salt minion-master saltutil.runner test-runner.handle ["bogus"]``` yields ```Passed invalid arguments to saltutil.runner: runner() takes exactly 1 argument (9 given)```.

Also tried ```salt minion-master saltutil.runner test-runner.handle kwargs={'args': ["bogus"]}``` with same results.

And of course ``` salt minion-master saltutil.runner test-runner.handle``` does invoke my runner but then fails because it requires an arg
```
    Exception occurred in runner test-runner.handle: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 342, in low
        data['return'] = self.functions[fun](*args, **kwargs)
    TypeError: handle() takes at least 1 argument (0 given)
```

**Comment by scubahub** [comment]
Figured it out, though not sure how it works, even though the first arg to test-runner.handle is not a kwarg I can pass it through saltutil.runner as a kwarg ```salt minion-master saltutil.runner test-runner.handle data="bogus"```.

Trying the call from the reactor now.

**Comment by scubahub** [comment]
@Ch3LL Thanks that worked great.

```
#!py

def run():
  __salt__['saltutil.runner']("scheduled-job-return-runner.handle", data=data, __env__=__env__)
  return {}
```

Though I am having a hard time finding where the magic happens so that the data kwarg gets mapped to the arg (not kwarg) in the actual runner's handle method.  Now reading though the documentation on the dunder dictionaries.
