### ISSUE TITLE
State for elasticsearch_index.present fails.

### ISSUE THREAD

**Issue by roosri** [saltstack/salt#36642]
### Description of Issue/Question
Creating elasticsearch indexes from a pillar, trying to utilize the `elasticsearch_index.present` state.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Using a pillar with the following format;
```
elasticsearch:
  indices:
    some_index_name:
      type: jdbc
      jdbc:
        driver: com.intersys.jdbc.CacheDriver
        url: 'http://some_url'
        user: 'db_user'
        password: 'db_password'
        sql: select * from Some.Table
        index: some_index_name
        type: type
```

And the following state;
```
{% set es = salt['pillar.get']('elasticsearch', {})  %}

{% if 'indices' in es %}
{% for index in es['indices'] %}

elasticsearch_index_create_{{ index }}:
  elasticsearch_index.present:
    - name: {{ index }}
    - definition: '{{ es['indices'][index]|json }}'

{% endfor %}
{% endif %}
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
Salt will then error out with the following;
```
----------
          ID: elasticsearch_index_some_index_name
    Function: elasticsearch_index.present
        Name: appointment
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1723, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1650, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/elasticsearch_index.py", line 53, in present
                  index_exists = __salt__['elasticsearch.index_exists'](name=name)
              TypeError: index_exists() got an unexpected keyword argument 'name'
     Started: 23:58:37.170851
    Duration: 1.342 ms
     Changes:
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
Salt Version:
           Salt: 2016.3.0

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.5.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.10.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

Master and minion are running the same version.

**Comment by roosri** [comment]
Bugfix pull request is in.

**Comment by Ch3LL** [comment]
@roosri thanks for the PR! We will get this closed up once the PR has been reviewed and merged. Thanks

**Comment by rallytime** [comment]
Good catch @roosri. I have merged in your change, so I will go ahead and close this up. Thanks again!
