### ISSUE TITLE
Cannot create medium or large servers into Scaleway with salt-cloud

### ISSUE THREAD

**Issue by anttileppa** [saltstack/salt#36703]
### Description of Issue/Question

When trying to create new medium or large server with salt-cloud into Scaleway. Server creation fails because medium and large instances require additional volumes.  
### Setup

Contents of /etc/salt/cloud.profiles.d/vc1m-ubuntu-1604.conf:

```
vc1m-ubuntu-1604:
  provider: scaleway
  image: 047f1372-3923-471f-82ca-5ff69dbaf0f7
  commercial_type: VC1M
  script_args: -l
```
### Steps to Reproduce Issue

Command:

```
salt-cloud -p vc1m-ubuntu-1604 newserver
```

Output:

```
[ERROR   ] Error creating newserver on Scaleway

The following exception was thrown when trying to run the initial deployment: An error occurred while querying Scaleway. HTTP Code: 400  Error: '{"message": "The sum of volumes sizes of VC1M instances must be between 51GB and 100GB", "type": "invalid_request_error"}'
Error: There was a profile error: Failed to deploy VM
```

So appropriate fix would be an option to add additional volumes on profile config.
### Versions Report

```
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.5.1-std-1
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by Ch3LL** [comment]
@anttileppa i'm not seeing the option to add additional volumes in the scaleway module so looks like we need to get this added. Thanks!

**Comment by The-Loeki** [comment]
@Ch3LL The volumes need to be added during create or before startup;

```
[DEBUG   ] Sending event: tag = salt/cloud/kube-w1/requesting; data = {'_stamp': '2017-05-16T14:14:49.240980', 'event': 'requesting instance', 'kwargs': {'organization': 'mad-hatter', 'image': '89ee4018-f8c3-4dc4-a6b5-bca14f985ebe', 'commercial_type': 'VC1L', 'name': 'kube-w1'}}
[DEBUG   ] https://cp-ams1.scaleway.com/servers/
[ERROR   ] Error creating kube-w1 on Scaleway

The following exception was thrown when trying to run the initial deployment: An error occurred while querying Scaleway. HTTP Code: 400  Error: '{"message": "The total volume size of VC1L instances must be between 151GB and 200GB", "type": "invalid_request_error"}'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/scaleway.py", line 256, in create
    ret = create_node(kwargs)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/scaleway.py", line 199, in create_node
    http_method='post'
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/scaleway.py", line 362, in query
    request.text
SaltCloudSystemExit: An error occurred while querying Scaleway. HTTP Code: 400  Error: '{"message": "The total volume size of VC1L instances must be between 151GB and 200GB", "type": "invalid_request_error"}'
[INFO    ] Complete
```

This problem is further exacerbated by the scaleway driver ignoring profile settings;

```
{{profile}}:
{% set i = 1 %}
   - kube-w{{ i }}:
        arch: x86_64
        commercial_type: VC1L
        image: 89ee4018-f8c3-4dc4-a6b5-bca14f985ebe
        enable_ipv6: True                   # ignored!
        dynamic_ip_required: False   # ignored!
        volumes:                                 # ignored!   
            1:
              name: teapot
              size: 10000000000
              volume_type: l_ssd
        minion:
            id: w{{ i }}.kube.{{ zone }}.{{ domain }}
```

**Comment by The-Loeki** [comment]
not stale
