### ISSUE TITLE
ExtraData: unpack(b) received extra data after upgrading to 2016.3.3

### ISSUE THREAD

**Issue by Tanoti** [saltstack/salt#36713]
### Description of Issue/Question

We have just upgraded our test system salt master on Red Hat EL6 from 2015.8.8 to 2016.3.3 using the salt rpms and are now observing the following error when performing any operation against the local or other minions, even "test.ping":

```
[jhicks@salttest] $ sudo salt 'salttest*' test.ping
[CRITICAL] Could not deserialize msgpack message.This often happens when trying to read a file not in binary modeTo see message payload, enable debug logging and retry. Exception: unpack(b) received extra data.
[ERROR   ] Uncaught exception, closing connection.
Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/zmq/eventloop/zmqstream.py", line 407, in _run_callback
    callback(*args, **kwargs)
  File "/usr/lib64/python2.6/site-packages/tornado/stack_context.py", line 274, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/transport/zeromq.py", line 910, in mark_future
    future.set_result(self.serial.loads(msg[0]))
  File "/usr/lib/python2.6/site-packages/salt/payload.py", line 117, in loads
    return msgpack.loads(msg, use_list=True)
  File "msgpack/_unpacker.pyx", line 142, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:142)
ExtraData: unpack(b) received extra data.
[ERROR   ] Uncaught exception, closing connection.
Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/zmq/eventloop/zmqstream.py", line 433, in _handle_events
    self._handle_recv()
  File "/usr/lib64/python2.6/site-packages/zmq/eventloop/zmqstream.py", line 465, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/lib64/python2.6/site-packages/zmq/eventloop/zmqstream.py", line 407, in _run_callback
    callback(*args, **kwargs)
  File "/usr/lib64/python2.6/site-packages/tornado/stack_context.py", line 274, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/transport/zeromq.py", line 910, in mark_future
    future.set_result(self.serial.loads(msg[0]))
  File "/usr/lib/python2.6/site-packages/salt/payload.py", line 117, in loads
    return msgpack.loads(msg, use_list=True)
  File "msgpack/_unpacker.pyx", line 142, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:142)
ExtraData: unpack(b) received extra data.
[ERROR   ] Exception in callback None
Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/tornado/ioloop.py", line 865, in start
    handler_func(fd_obj, events)
  File "/usr/lib64/python2.6/site-packages/tornado/stack_context.py", line 274, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib64/python2.6/site-packages/zmq/eventloop/zmqstream.py", line 433, in _handle_events
    self._handle_recv()
  File "/usr/lib64/python2.6/site-packages/zmq/eventloop/zmqstream.py", line 465, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/lib64/python2.6/site-packages/zmq/eventloop/zmqstream.py", line 407, in _run_callback
    callback(*args, **kwargs)
  File "/usr/lib64/python2.6/site-packages/tornado/stack_context.py", line 274, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/transport/zeromq.py", line 910, in mark_future
    future.set_result(self.serial.loads(msg[0]))
  File "/usr/lib/python2.6/site-packages/salt/payload.py", line 117, in loads
    return msgpack.loads(msg, use_list=True)
  File "msgpack/_unpacker.pyx", line 142, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:142)
ExtraData: unpack(b) received extra data.
Salt request timed out. The master is not responding. If this error persists after verifying the master is up, worker_threads may need to be increased.
```

Following advice in other issue tickets, we have tried removing /var/cache/salt and /etc/salt/pki to no effect. 
### Log Extract

```
2016-09-30 14:07:44,019 [salt.transport.zeromq][DEBUG   ][15344] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'salttest_master', 'tcp://127.0.0.1:4506', 'clear')
2016-09-30 14:07:44,020 [salt.transport.ipc][DEBUG   ][15344] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
2016-09-30 14:07:44,024 [salt.utils.lazy                                      ][DEBUG   ][13722] LazyLoaded local_cache.prep_jid
2016-09-30 14:07:44,025 [salt.transport.ipc                                   ][DEBUG   ][13722] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
2016-09-30 14:07:44,026 [salt.utils.event                                     ][DEBUG   ][13722] Sending event - data = {'_stamp': '2016-09-30T14:07:44.026086', 'minions': ['salttest.hosts.adeptra.com']}
2016-09-30 14:07:44,027 [salt.utils.reactor                                   ][DEBUG   ][13691] Gathering reactors for tag 20160930140744024316
2016-09-30 14:07:44,028 [salt.utils.event                                     ][DEBUG   ][13722] Sending event - data = {'tgt_type': 'glob', 'jid': '20160930140744024316', 'tgt': 'salttest*', '_stamp': '2016-09-30T14:07:44.028261', 'user': 'sudo_jhicks', 'arg': [], 'fun': 'test.ping', 'minions': ['salttest.hosts.adeptra.com']}
2016-09-30 14:07:44,029 [salt.utils.reactor                                   ][DEBUG   ][13691] Gathering reactors for tag salt/job/20160930140744024316/new
2016-09-30 14:07:44,098 [salt.utils.lazy                                      ][DEBUG   ][13722] Could not LazyLoad syslog.save_load
2016-09-30 14:07:44,100 [salt.transport.zeromq                                ][ERROR   ][13722] Some exception handling a payload from minion
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/transport/zeromq.py", line 605, in handle_message
    ret, req_opts = yield self.payload_handler(payload)
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib64/python2.6/site-packages/tornado/concurrent.py", line 214, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 215, in wrapper
    result = func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/master.py", line 843, in _handle_payload
    'clear': self._handle_clear}[key](load)
  File "/usr/lib/python2.6/site-packages/salt/master.py", line 857, in _handle_clear
    return getattr(self.clear_funcs, load['cmd'])(load), {'fun': 'send_clear'}
  File "/usr/lib/python2.6/site-packages/salt/master.py", line 2209, in publish
    payload = self._prep_pub(minions, jid, clear_load, extra)
  File "/usr/lib/python2.6/site-packages/salt/master.py", line 2287, in _prep_pub
    arg_spec = salt.utils.args.get_function_argspec(self.mminion.returners[fstr])
  File "/usr/lib/python2.6/site-packages/salt/loader.py", line 1055, in __getitem__
    func = super(LazyLoader, self).__getitem__(item)
  File "/usr/lib/python2.6/site-packages/salt/utils/lazy.py", line 93, in __getitem__
    raise KeyError(key)
KeyError: 'syslog.save_load'
2016-09-30 14:07:44,101 [salt.payload     ][CRITICAL][15344] Could not deserialize msgpack message.This often happens when trying to read a file not in binary modeTo see message payload, enable debug logging and retry. Exception: unpack(b) received extra data.
2016-09-30 14:07:44,101 [salt.payload     ][DEBUG   ][15344] Msgpack deserialization failure on message: Some exception handling minion payload
2016-09-30 14:07:44,102 [tornado.general  ][ERROR   ][15344] Uncaught exception, closing connection.
Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/zmq/eventloop/zmqstream.py", line 407, in _run_callback
    callback(*args, **kwargs)
  File "/usr/lib64/python2.6/site-packages/tornado/stack_context.py", line 274, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/transport/zeromq.py", line 910, in mark_future
    future.set_result(self.serial.loads(msg[0]))
  File "/usr/lib/python2.6/site-packages/salt/payload.py", line 117, in loads
    return msgpack.loads(msg, use_list=True)
  File "msgpack/_unpacker.pyx", line 142, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:142)
ExtraData: unpack(b) received extra data.
2016-09-30 14:07:44,104 [tornado.general  ][ERROR   ][15344] Uncaught exception, closing connection.
Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/zmq/eventloop/zmqstream.py", line 433, in _handle_events
    self._handle_recv()
  File "/usr/lib64/python2.6/site-packages/zmq/eventloop/zmqstream.py", line 465, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/lib64/python2.6/site-packages/zmq/eventloop/zmqstream.py", line 407, in _run_callback
    callback(*args, **kwargs)
  File "/usr/lib64/python2.6/site-packages/tornado/stack_context.py", line 274, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/transport/zeromq.py", line 910, in mark_future
    future.set_result(self.serial.loads(msg[0]))
  File "/usr/lib/python2.6/site-packages/salt/payload.py", line 117, in loads
    return msgpack.loads(msg, use_list=True)
  File "msgpack/_unpacker.pyx", line 142, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:142)
ExtraData: unpack(b) received extra data.
2016-09-30 14:07:44,104 [tornado.application][ERROR   ][15344] Exception in callback None
Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/tornado/ioloop.py", line 865, in start
    handler_func(fd_obj, events)
  File "/usr/lib64/python2.6/site-packages/tornado/stack_context.py", line 274, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib64/python2.6/site-packages/zmq/eventloop/zmqstream.py", line 433, in _handle_events
    self._handle_recv()
  File "/usr/lib64/python2.6/site-packages/zmq/eventloop/zmqstream.py", line 465, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/lib64/python2.6/site-packages/zmq/eventloop/zmqstream.py", line 407, in _run_callback
    callback(*args, **kwargs)
  File "/usr/lib64/python2.6/site-packages/tornado/stack_context.py", line 274, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/transport/zeromq.py", line 910, in mark_future
    future.set_result(self.serial.loads(msg[0]))
  File "/usr/lib/python2.6/site-packages/salt/payload.py", line 117, in loads
    return msgpack.loads(msg, use_list=True)
  File "msgpack/_unpacker.pyx", line 142, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:142)
ExtraData: unpack(b) received extra data.
2016-09-30 14:07:49,027 [salt.transport.zeromq][DEBUG   ][15344] SaltReqTimeoutError, retrying. (1/3)
2016-09-30 14:07:54,030 [salt.transport.zeromq][DEBUG   ][15344] SaltReqTimeoutError, retrying. (2/3)
2016-09-30 14:07:59,033 [salt.transport.zeromq][DEBUG   ][15344] SaltReqTimeoutError, retrying. (3/3)
```
### Versions Report

```
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, May 22 2015, 08:34:51)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: redhat 6.8 Santiago
        machine: x86_64
        release: 2.6.32-642.3.1.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.8 Santiago
```

The local minion and one test remote minion are also on 2016.3.3

**Comment by Tanoti** [comment]
Downgrading to 2015.8.8 removes the problem so it is appears to be with the 2016.3.3 release.

**Comment by Ch3LL** [comment]
This might be a long shot but you might be running into this issue: #33516 . After upgrading can you check your logs particularly on the minion side to see if you are seeing logs similar to that issue. After the restart of the master/minion and attempt to restart them both twice to see if it resolves the issue.

**Comment by Tanoti** [comment]
@Ch3LL Sadly no, that did not help. Even after restarting the minion a second time, the master still has the error then times out when trying to perform any operation against the minion.

**Comment by cachedout** [comment]
Could you please try clearing all stale *.pyc files in the salt source directory on the master and restarting the master? Also, do you see any errors on master startup? It's having trouble generating a list of execution modules, it seems.

**Comment by Tanoti** [comment]
@cachedout I can see no startup errors on the master before or after the upgrade. The errors above occur as soon as the minion sends data (which for us is on a reactor for minion startup in the first instance). But the same errors occur if you try something as simple as test.ping.

I then downgraded the installation to 2015.8.8 (our production version), checked it was all working then stopped the master, removed the *.pyc files below /usr/lib/python2.6/site-packages/salt and upgraded again. Sadly, the same errors above occur.

**Comment by Tanoti** [comment]
Any further ideas on this one?

**Comment by Tanoti** [comment]
So, after a bit of digging I found the problem. We are using the syslog returner set in the master config file using "ext_job_cache: syslog". It appears that the save_load() function is now required but not present in the syslog_return.py module.

'''
2016-10-14 10:41:25,844 [salt.utils.lazy                                      ][DEBUG   ][8073] Could not LazyLoad syslog.save_load
2016-10-14 10:41:25,845 [salt.transport.zeromq                                ][ERROR   ][8073] Some exception handling a payload from minion
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/transport/zeromq.py", line 605, in handle_message
    ret, req_opts = yield self.payload_handler(payload)
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib64/python2.6/site-packages/tornado/concurrent.py", line 214, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 215, in wrapper
    result = func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/master.py", line 843, in _handle_payload
    'clear': self._handle_clear}[key](load)
  File "/usr/lib/python2.6/site-packages/salt/master.py", line 857, in _handle_clear
    return getattr(self.clear_funcs, load['cmd'])(load), {'fun': 'send_clear'}
  File "/usr/lib/python2.6/site-packages/salt/master.py", line 2209, in publish
    payload = self._prep_pub(minions, jid, clear_load, extra)
  File "/usr/lib/python2.6/site-packages/salt/master.py", line 2287, in _prep_pub
    arg_spec = salt.utils.args.get_function_argspec(self.mminion.returners[fstr])
  File "/usr/lib/python2.6/site-packages/salt/loader.py", line 1055, in __getitem__
    func = super(LazyLoader, self).__getitem__(item)
  File "/usr/lib/python2.6/site-packages/salt/utils/lazy.py", line 93, in __getitem__
    raise KeyError(key)
KeyError: 'syslog.save_load'
2016-10-14 10:41:25,846 [salt.payload     ][CRITICAL][9822] Could not deserialize msgpack message.This often happens when trying to read a file not in binary modeTo see message payload, enable debug logging and retry. Exception: unpack(b) received extra data.
'''

It also appears that you cannot patch this using a syslog_return.py in _returners as the default one is needed by the minion even when using saltutil.sync_all.

Hacking the copy in /usr/lib/python2.6/site-packages/salt/returners/syslog_return.py to add a stub function save_load() causes the problem to go away.

'''
def save_load():
    return
'''

**Comment by dahrens** [comment]
same issue applies to the couchdb returner in 2016.3.3

**Comment by Ch3LL** [comment]
Looks like we need to add that function to those returners. Thanks for the heads up will need to get this fixed up.

**Comment by cachedout** [comment]
While those returners do need to be fixed up, the root of this problem is not correctly handling the lack of this function. I have corrected that oversight here: https://github.com/saltstack/salt/pull/37503
