### ISSUE TITLE
Carbon: Minion does not shutdown properly when attempting to start multiple minions on same host

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#36729]
### Description of Issue/Question
When attempting to start multiple minion processes the second minion process does not shutdown properly. Let me show an example to better explain:

I currently do not have any minion processes running:

```
[root@7bb88b856c2e testing]# ps axu | grep -i salt                         
root       278  0.0  0.0   9048   848 ?        S+   22:14   0:00 grep --color=auto -i salt
```

I start a minion in the backgroun as shown below (this is working as expected)

```
[root@7bb88b856c2e testing]# salt-minion -d
[root@7bb88b856c2e testing]# 
```

But when I attempt to start another minion (i know this will not work in general unless changing values, but I woul expect for the minion to not startup and shutdown properly, but i get the following)

```
[root@7bb88b856c2e testing]# salt-minion -d
The Salt Minion is shutdown.
```

And it just hangs there indefinitely. And when I hit Ctrl + C it stack traces as follows:

```
[root@7bb88b856c2e testing]# salt-minion -d
The Salt Minion is shutdown.
^CProcess Process-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 261, in _bootstrap
    util._exit_function()
  File "/usr/lib64/python2.7/multiprocessing/util.py", line 319, in _exit_function
    p.join()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 145, in join
    res = self._popen.wait(timeout)
  File "/usr/lib64/python2.7/multiprocessing/forking.py", line 154, in wait
    return self.poll(0)
  File "/usr/lib64/python2.7/multiprocessing/forking.py", line 135, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
```

When running this on 2016.3.3 for example this is working as expected as shown below:

```
[root@7bb88b856c2e testing]# salt-minion -d
[root@7bb88b856c2e testing]# salt-minion -d
The salt minion is shutdown.[root@7bb88b856c2e testing]# 
```

### Setup
1. just need a minion

### Steps to Reproduce Issue
   a. `salt-minion -d`
   b. `salt-minion -d` (or run it in the foreground `salt-minion -ldebug`)
Note: might be related to issue or even a duplicate of the issue: #36304 make note of the comments at the bottom of that issue. This is the same behavior as documented in that issue but I am seeing it by running completely different steps. 

### Versions Report

```
[root@localhost ~]# salt --versions-report
Salt Version:
           Salt: 2016.9.0alpha1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.18.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

**Comment by Ch3LL** [comment]
Also just noticed the same thing with attempting to startup multiple salt-master proccesses like so:

```
[root@localhost ~]# salt-master -d
[root@localhost ~]# salt-master -d
WARNING: Unable to bind socket 0.0.0.0:4505, error: [Errno 98] Address already in use; Is there another salt-master running?
The salt master is shutdown. The ports are not available to bind

^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib64/python2.7/multiprocessing/util.py", line 319, in _exit_function
    p.join()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 145, in join
    res = self._popen.wait(timeout)
  File "/usr/lib64/python2.7/multiprocessing/forking.py", line 154, in wait
    return self.poll(0)
  File "/usr/lib64/python2.7/multiprocessing/forking.py", line 135, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Error in sys.exitfunc:

```

It just kept hanging until i selected Ctrl + C

**Comment by cachedout** [comment]
This bug is very similar to what was causing the test suite to hang. See this PR: https://github.com/saltstack/salt/pull/36744/files

**Comment by Ch3LL** [comment]
I confirmed this is working on the head of carbon now:

```
[root@b360eeb1ba06 testing]# salt-minion -d
[root@b360eeb1ba06 testing]# salt-minion -d
The Salt Minion is shutdown.
[root@b360eeb1ba06 testing]# salt --version
salt 2016.9.0-701-gb4c8573
[root@b360eeb1ba06 testing]# 
```

Thanks @cachedout !!
