### ISSUE TITLE
Carbon - Alpha 1: Proxy minion is not working

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#36748]
Proxy minion is not working in Carbon - Alpha1

### Setup
Set up proxy minion environment and run commands.

### Steps to Reproduce Issue
```
salt p8000 test.ping
p8000:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1378, in _thread_return
        return_data = executor.execute()
      File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/usr/lib/python2.7/site-packages/salt/modules/test.py", line 117, in ping
        ping_cmd = __opts__['proxy']['proxytype'] + '.ping'
    KeyError: 'proxy'
```
```
salt p8000 pkg.install testme
p8000:
    'pkg.install' is not available.
ERROR: Minions returned with non-zero exit code
```
```
salt p8000 service.stop redbull
p8000:
    'service' __virtual__ returned False: Non Linux OSes are not supported
ERROR: Minions returned with non-zero exit code
```
```
salt p8000 state.apply apac
p8000:
----------
          ID: redbull_service
    Function: service.running
        Name: redbull
      Result: False
     Comment: State 'service.running' was not found in SLS 'apac'
              Reason: 'service' __virtual__ returned False: No service execution module loaded: check support for service management on proxy-proxy
     Changes:   
----------
          ID: apache_service
    Function: service.running
        Name: apache
      Result: False
     Comment: State 'service.running' was not found in SLS 'apac'
              Reason: 'service' __virtual__ returned False: No service execution module loaded: check support for service management on proxy-proxy
     Changes:   

Summary for p8000
------------
Succeeded: 0
Failed:    2
------------
Total states run:     2
Total run time:   0.000 ms
ERROR: Minions returned with non-zero exit code
```

### Versions Report
```
Salt Version:
           Salt: 2016.9.0alpha1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.0.1406 Core
        machine: x86_64
        release: 4.7.0-x86_64-linode72
         system: Linux
        version: CentOS Linux 7.0.1406 Core
```

**Comment by cro** [comment]
@frogunder Can you also post your configs?  That would help, thanks.

**Comment by frogunder** [comment]
```
grep -E -v '^$|#' /etc/salt/master
pillar_roots:
  base:
    - /root/salt-manual-tests/proxy/pillar
file_roots:
  base:
    - /root/salt-manual-tests/proxy/states
```
```
grep -E -v '^$|#' /etc/salt/proxy
master: localhost
add_proxymodule_to_opts: false
```

**Comment by cro** [comment]
Pillar too please?  Thank you.

**Comment by frogunder** [comment]
/root/salt-manual-tests/proxy/pillar/top.sls
```
{% set ip = '172.16.207.1' %}
base:
  'p8000':
    - proxy8000
  'p8001':
    - proxy8001
  'p8002':
    - proxy8002
```
/root/salt-manual-tests/proxy/pillar/proxy8000.sls
```
proxy:
  proxytype: rest_sample
  url: http://192.155.81.113:8000/
```
/root/salt-manual-tests/proxy/pillar/proxy8001.sls
```
proxy:
  proxytype: rest_sample
  url: http://192.155.81.113:8001/
```
/root/salt-manual-tests/proxy/pillar/proxy8002.sls
```
proxy:
  proxytype: rest_sample
  url: http://192.155.81.113:8002/
```

**Comment by cro** [comment]
Great, thanks.

**Comment by cro** [comment]
Verified, it's stacktracing.  I'm looking into it.
