### ISSUE TITLE
salt-cloud (vultr) throws NameError: global name '__opts__' is not defined

### ISSUE THREAD

**Issue by bx2** [saltstack/salt#36766]
### Description of Issue/Question

While trying to create some vultr nodes via a map file, `salt-cloud` throws the following error:

```
[ERROR   ] There was a query error: global name '__opts__' is not defined
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/cli.py", line 348, in run
    ret = mapper.run_map(dmap)
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 2213, in run_map
    profile, local_master=local_master
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1281, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/vultrpy.py", line 224, in create
    transport=__opts__['transport']
  File "/usr/lib/python2.7/site-packages/salt/utils/cloud.py", line 1721, in fire_event
    sock_dir = os.path.join(__opts__['sock_dir'], 'master')
NameError: global name '__opts__' is not defined
```

### Setup

Node `aa-002` is up, node `aa-001` does not exist yet. Profile exists and is valid.

**Profile file (vultr.profile):**

```
vultr-profile:
  location: 1
  provider: myvultr
  image: 167
  size: 95
  enable_private_network: True
```

**Map file (mapfile.map):**

```
vultr-profile:
  - aa-001:
      minion:
        grains:
          environment: xxx
          roles: xxx
          location: xxx
          datacenter: vu
        master: xxx
        mine_interval: 1
  - aa-002:
      minion:
        grains:
          environment: xxx
          roles: xxx
          location: xxx
          datacenter: vu
        master: xxx
        mine_interval: 1
```

### Steps to Reproduce Issue

Save the map file and execute:

```
salt-cloud -m mapfile.map
```

### Versions Report

```
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.18.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

**Comment by gtmanfred** [comment]
Hello, thanks for reporting this.  I have created this pull request to fix the problem.

https://github.com/saltstack/salt/pull/36768
