### ISSUE TITLE
postgres.* calls fail with postgresql 9.6 and .psqlrc custom file

### ISSUE THREAD

**Issue by maximeguillet** [saltstack/salt#36787]
### Description of Issue/Question

All salt commands and states calling postgres.* fail when options are set in a .psqlrc file in postgres system user with postgresql 9.6.

### Setup

- Install postgresql 9.6
- Setup a .psqlrc with options like `\timing on` or `\x` auto
```
# cat << EOF > ~postgres/.psqlrc
\timing on
\x auto
EOF
```
### Steps to Reproduce Issue

- Run a postgres.* salt command :
```
# salt-call postgres.version

local:
    Timing is on.

# salt-call postgres.db_list
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
KeyError: 'Name'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 352, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/postgres.py", line 435, in db_list
    ret[row['Name']] = row
```

### Versions Report
```
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.6
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.6
```
```
$ psql --version
psql (PostgreSQL) 9.6.0
```

**Comment by gtmanfred** [comment]
Thanks for the pr!
