### ISSUE TITLE
SaltReqTimeoutError 

### ISSUE THREAD

**Issue by menglong81** [saltstack/salt#36795]
MultiSyndic、MultiMaster、Failover Minion

when the master switch, minion failvoer ,but occur error,minion cmd.run can be executed but state.sls is occur mistake

l-zmltest10.ops.dev.cn0:
    The minion function caused an exception: Traceback (most recent call last):
      File "/home/q/python27/lib/python2.7/site-packages/salt/minion.py", line 1142, in _thread_return
        return_data = func(*args, **kwargs)
      File "/home/q/python27/lib/python2.7/site-packages/salt/modules/state.py", line 645, in sls
        st_ = salt.state.HighState(opts, pillar, kwargs.get('__pub_jid'))
      File "/home/q/python27/lib/python2.7/site-packages/salt/state.py", line 3028, in __init__
        BaseHighState.__init__(self, opts)
      File "/home/q/python27/lib/python2.7/site-packages/salt/state.py", line 2206, in __init__
        self.opts = self.__gen_opts(opts)
      File "/home/q/python27/lib/python2.7/site-packages/salt/state.py", line 2233, in __gen_opts
        mopts = self.client.master_opts()
      File "/home/q/python27/lib/python2.7/site-packages/salt/fileclient.py", line 1193, in master_opts
        return self.channel.send(load)
      File "/home/q/python27/lib/python2.7/site-packages/salt/transport/__init__.py", line 314, in send
        return self._crypted_transfer(load, tries, timeout)
      File "/home/q/python27/lib/python2.7/site-packages/salt/transport/__init__.py", line 302, in _crypted_transfer
        return _do_transfer()
      File "/home/q/python27/lib/python2.7/site-packages/salt/transport/__init__.py", line 293, in _do_transfer
        timeout)
      File "/home/q/python27/lib/python2.7/site-packages/salt/payload.py", line 275, in send
        'SaltReqTimeoutError: after {0} seconds, ran {1} tries'.format(timeout * tried, tried)
    SaltReqTimeoutError: SaltReqTimeoutError: after 180 seconds, ran 3 tries

minion version
           Salt: 2015.5.0
         Python: 2.7.4 (default, Dec 24 2013, 16:30:42)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 13.1.0
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed

minion config
master:
  - l-zmltest7.ops.dev.cn0
  - l-zmltest8.ops.dev.cn0
master_type: failover
master_shuffle: True
master_alive_interval: 30
recon_default: 10000
recon_max: 59000
recon_randomize: True
acceptance_wait_time: 10
random_reauth_delay: 60
auth_timeout: 10

**Comment by Ch3LL** [comment]
@menglong81 there has been a lot of great improvements in 2015.8 and 2016.3 branches of salt in regards to salt-master. If you upgrade to the latest version of salt (2016.3.3) does that help resolve the issue?

**Comment by menglong81** [comment]
I update the minion in 2016.3.3  to solve the problem  thanks

**Comment by Ch3LL** [comment]
Perfect! thanks for letting me know the results. Closing since its resolved.
