### ISSUE TITLE
Infinite recursion loop on prereq + require + test=True

### ISSUE THREAD

**Issue by tomlaredo** [saltstack/salt#36836]
### Description of Issue/Question
In certain cases, prereq and require used together can lead to an infinite recursion loop if test=True is given.

Not sure about the exact combo but I found a simple way to reproduce it.
I think that the issue is happening when a state is requiring another state that has to do changes on the system and when a third state is a prereq of the second state because of the test=True.

### Setup
Content of my/state.sls:
```
state-a:
    file.directory:
        - name: /var/
        - group: non-existent-group

state-b:
    file.symlink:
        - name: /var/non-existent-symlink
        - target: /var/lib
        - require:
            - file: state-a

state-c:
    service.dead:
        - name: ssh
        - prereq:
            - file: state-b
```

### Steps to Reproduce Issue

```
# salt-call state.apply my.state test=True
[WARNING ] Although 'dmidecode' was found in path, the current user cannot execute it. Grains output might not be accurate.
[WARNING ] /usr/lib/python2.7/dist-packages/salt/grains/core.py:1493: DeprecationWarning: The "osmajorrelease" will be a type of an integer.

[INFO    ] Got list of available master addresses: ['master.salt.xxxxxxx.com', 'xx.xx.xx.xx', 'yy.yy.yy.yy', 'zz.zz.zz.zz']
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://softwares/postfix/testserver/tom.sls'
[INFO    ] Running state [/var/] at time 09:24:11.052092
[INFO    ] Executing state file.directory for /var/
[ERROR   ] Group invalidgroup is not available
[INFO    ] Completed state [/var/] at time 09:24:11.056686 duration_in_ms=4.594
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
RuntimeError: maximum recursion depth exceeded
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 352, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 455, in apply_
    return sls(mods, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 942, in sls
    ret = st_.state.call_high(high_)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2279, in call_high
    ret = dict(list(disabled.items()) + list(self.call_chunks(chunks).items()))
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1799, in call_chunks
    running = self.call_chunk(low, running, chunks)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2069, in call_chunk
    running = self.call_chunk(chunk, running, chunks)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2080, in call_chunk
    running = self.call_chunk(low, running, chunks)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2080, in call_chunk
    running = self.call_chunk(low, running, chunks)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2080, in call_chunk
    running = self.call_chunk(low, running, chunks)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2080, in call_chunk
    running = self.call_chunk(low, running, chunks)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2080, in call_chunk
    running = self.call_chunk(low, running, chunks)
...
...
...
File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2080, in call_chunk
    running = self.call_chunk(low, running, chunks)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1977, in call_chunk
    low = self._mod_aggregate(low, running, chunks)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 757, in _mod_aggregate
    agg_opt = self.functions['config.option']('state_aggregate')
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1055, in __getitem__
    func = super(LazyLoader, self).__getitem__(item)
  File "/usr/lib/python2.7/dist-packages/salt/utils/lazy.py", line 83, in __getitem__
    if self._missing(key):
RuntimeError: maximum recursion depth exceeded
```

### Versions Report
Master's and minion's environment are the same (2016.3.3 on a Debian Jessie):
```
Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.6 
        machine: x86_64
        release: 4.4.15-1-pve
         system: Linux
        version: debian 8.6 
```

**Comment by Ch3LL** [comment]
@tomlaredo looks like this might be a duplicate of #15171 but it seems they are even seeing the error even without test=True. I tried your example without test=True adn it seems to give that same error as well. Are you indeed not seeing this error without running with test=True?

There is another issue here #20143  that seems it might be a duplicate as well
