### ISSUE TITLE
pkg.installed intermittently throwing exceptions "ignore_epoch" unexpected keyword

### ISSUE THREAD

**Issue by scubahub** [saltstack/salt#36832]
### Description of Issue/Question

Starting with the installation of 2015.08.11 I have been seeing the following happening intermittently:

```
    "pkg_|-install-fluentd-config-package_|-google-fluentd-catch-all-config_|-installed": {
        "__run_num__": 176,
        "changes": {},
        "comment": "An exception occurred in this state: Traceback (most recent call last):\n  File \"/usr/lib/python2.7/site-packages/salt/state.py\", line 1624, in call\n    **cdata['kwargs'])\n  File \"/usr/lib/python2.7/site-packages/salt/loader.py\", line 1492, in wrapper\n    with context.func_globals_inject(f, **inject_globals):\n  File \"/usr/lib/python2.7/site-packages/salt/states/pkg.py\", line 1076, in installed\n    **kwargs)\n  File \"/usr/lib/python2.7/site-packages/salt/states/pkg.py\", line 478, in _find_install_targets\n    ignore_epoch=ignore_epoch):\n  File \"/usr/lib/python2.7/site-packages/salt/states/pkg.py\", line 160, in _fulfills_version_spec\n    ignore_epoch=ignore_epoch):\nTypeError: compare_versions() got an unexpected keyword argument 'ignore_epoch'\n",
        "duration": 460.201,
        "name": "google-fluentd-catch-all-config",
        "result": false,
        "start_time": "07:37:55.950741"
    },
```

Here is the exception formatted more readably:

```
        An exception occurred in this state: Traceback (most recent call last):
 File "/usr/lib/python2.7/site-packages/salt/state.py", line 1624, in call
   **cdata['kwargs'])
 File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1492, in wrapper
   with context.func_globals_inject(f, **inject_globals):
 File "/usr/lib/python2.7/site-packages/salt/states/pkg.py", line 1076, in installed
   **kwargs)
 File "/usr/lib/python2.7/site-packages/salt/states/pkg.py", line 478, in _find_install_targets
   ignore_epoch=ignore_epoch):
 File "/usr/lib/python2.7/site-packages/salt/states/pkg.py", line 160, in _fulfills_version_spec
   ignore_epoch=ignore_epoch):
TypeError: compare_versions() got an unexpected keyword argument 'ignore_epoch'
```

I am guessing that this is related to this change "https://github.com/saltstack/salt/pull/34531" (but have not read the code changes to be sure).
### Setup

The relevant portion of the state file is:

```
{%- set os_family = salt["grains.get"]("os_family") %}
{%- set os_major_version = salt["grains.get"]("osmajorrelease") %}
{%- set pkg_info = salt["pillar.get"]("package-info:" + os_family + ":" + os_major_version) %}

{%- for name in ["stackdriver-agent", "stackdriver-extractor"] %} {#- to ensure order #}
  {%- set package = pkg_info.get(name) %}
install-{{ name }}-package:
  pkg.installed:
    - name: {{ package.pkg_name }}
    {%- if "version" in package %}
    - version: {{ package.version }}
    {%- endif %}
{%- endfor %}
```

The pillar file is:

```
package-info:
  RedHat:
    "6":
      google-fluentd:
        pkg_name: google-fluentd
        service_name: google-fluentd
      fluentd-config:
        pkg_name: google-fluentd-catch-all-config
        version: 0.4-1
    "7":
      google-fluentd:
        pkg_name: google-fluentd
        service_name: google-fluentd
      fluentd-config:
        pkg_name: google-fluentd-catch-all-config
        version: 0.4-1
```
### Steps to Reproduce Issue

It is intermittent, I have not been able to reproduce by running highstate by hand (with -l debug).  Note, we have a scheduled job that runs highstate on all instances every half hour.  Two or three days ago it happened for an hour or two on one instance, last night it happened for several hours on a different instance.  Of course, always when I am not around (much less awake).  Spent a while trying to trigger the failure after both instances, but no luck so far.
### Versions Report

```
Salt Version:
           Salt: 2015.8.10

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.18.2.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
```

**Comment by Ch3LL** [comment]
@scubahub where that exception occurred is that minion also on version2015.8.10? the lines aren't matching up in the stack trace when i'm glancing at 2015.810. Just wanted to verify the minion version

**Comment by scubahub** [comment]
@Ch3LL, no I pasted one that was available from the wrong place.  It's running 2015.8.11 (and so will the other minion be shortly!)

**Comment by Ch3LL** [comment]
Thanks for clarifying. ping @terminalmage looks like you added this. I'm not seeing anything obvious in the code that would cause this intermittent behavior. Any ideas?

**Comment by terminalmage** [comment]
Looking at when ``ignore_epoch`` was added, it seems like there was a gap between 2015.8.10 and 2015.8.11 where ignore_epoch was added to the pkg state, but not added to salt.utils:

### Releases with ``ignore_epoch`` in the pkg state(s)
```
% for tag in `git tag --list`; do git checkout -q --force $tag 2>/dev/null; fgrep -q ignore_epoch salt/states/pkg.py 2>/dev/null && echo $tag; done; git checkout -q --force develop
v2015.8.10
v2015.8.11
v2015.8.12
v2015.8.9
v2016.11
v2016.11.0
v2016.11.0rc1
v2016.11.0rc2
v2016.11.0rc3
v2016.11.1
v2016.3.0
v2016.3.0rc3
v2016.3.1
v2016.3.2
v2016.3.3
v2016.3.4
v2016.9
v2016.9.0alpha1
```

### Releases with ``ignore_epoch`` in salt.utils
```
% for tag in `git tag --list`; do git checkout -q --force $tag 2>/dev/null; fgrep -q ignore_epoch salt/utils/__init__.py 2>/dev/null && echo $tag; done; git checkout -q --force develop
v2015.8.11
v2015.8.12
v2016.11
v2016.11.0
v2016.11.0rc1
v2016.11.0rc2
v2016.11.0rc3
v2016.11.1
v2016.3.2
v2016.3.3
v2016.3.4
v2016.9
v2016.9.0alpha1
```

Given this information, and the fact that I can't reproduce this on any release post 2015.8.11, I'm going to mark this as closed.
