### ISSUE TITLE
[2016.11.0rc1] runit module raises exception in virtual

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#36865]
### Description of Issue/Question
salt 2016.11.0rc1 always prints and error due to runit module.

```
[ERROR   ] Exception raised when processing __virtual__ function for runit. Module will not be loaded 'init'
Traceback (most recent call last):
  File "/opt/local/lib/python2.7/site-packages/salt/loader.py", line 1583, in process_virtual
    virtual = getattr(mod, virtual_func)()
  File "/opt/local/lib/python2.7/site-packages/salt/modules/runit.py", line 91, in __virtual__
    if __grains__['init'] == 'runit':
  File "/opt/local/lib/python2.7/site-packages/salt/utils/context.py", line 194, in __getitem__
    return self._dict()[key]
KeyError: 'init'
[WARNING ] salt.loaded.int.module.runit.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'runit', please fix this.
```

### Setup
N/A

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
```yaml
Salt Version:
           Salt: 2016.11.0rc1

Dependency Versions:
           cffi: 1.4.2
       cherrypy: 3.8.0
       dateutil: 2.4.0
          gitdb: 0.6.4
      gitpython: 0.3.2 RC1
          ioflo: 1.6.1
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: 1.5.0
       M2Crypto: 0.22
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Sep 26 2016, 19:40:04)
   python-gnupg: 0.3.9
         PyYAML: 3.11
          PyZMQ: 15.4.0
           RAET: 0.6.5
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.3
            ZMQ: 4.1.3

System Versions:
           dist:
        machine: i86pc
        release: 5.11
         system: SunOS
        version: Not Installed
```

**Comment by rallytime** [comment]
@sjorge The change in #36882 should fix this up for you.

**Comment by sjorge** [comment]
Yep #36882 fixes it!

**Comment by rallytime** [comment]
Awesome! Thanks for letting us know @sjorge and for all of your great testing and other fixes. It is greatly appreciated.
