### ISSUE TITLE
Scheduled runners not executed (again)

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#36871]
### Description of Issue/Question

Similar problem to #36021, this time in a different place.

### Setup
Same as #36021.

### Steps to Reproduce Issue

```
2016-10-09 06:00:12,156 [salt.utils.schedule                                                        ][ERROR   ][4623] Unhandled exception running redis.disabled
Traceback (most recent call last):
  File "/usr/local/salt/virtualenv/lib/python2.7/site-packages/salt/utils/schedule.py", line 741, in handle_func
    ret['return'] = self.functions[func](*args, **kwargs)
  File "/usr/local/salt/virtualenv/lib/python2.7/site-packages/salt/client/mixins.py", line 101, in wrapper
    False,  # Don't daemonize
  File "/usr/local/salt/virtualenv/lib/python2.7/site-packages/salt/client/mixins.py", line 432, in _proc_function
    return self.low(fun, low)
  File "/usr/local/salt/virtualenv/lib/python2.7/site-packages/salt/client/mixins.py", line 263, in low
    'fun_args': fun_args + ([low['kwargs']] if low.get('kwargs', False) else []),
TypeError: can only concatenate tuple (not "list") to tuple
```

This time looks like the error is elsewhere: https://github.com/saltstack/salt/blob/v2016.3.3/salt/client/mixins.py#L263

```python
'fun_args': fun_args + ([low['kwargs']] if low.get('kwargs', False) else []),
```

Should be

```python
'fun_args': list(fun_args) + ([low['kwargs']] if low.get('kwargs', False) else []),
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```bash
$ sudo salt --versions-report
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: 1.7.0
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.6.4
      gitpython: 2.0.5
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: 0.3.8
         PyYAML: 3.12
          PyZMQ: 15.4.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.5

System Versions:
           dist: debian 8.5
        machine: x86_64
        release: 4.1.3-cloudflare
         system: Linux
        version: debian 8.5
```

**Comment by gtmanfred** [comment]
This will be fixed in 2016.3.4.

https://github.com/saltstack/salt/commit/78d16a80570ee0db2a25940c0ba3cf3b1ded1391
https://github.com/saltstack/salt/commit/03007be6b118c5a51cbf932377fe5d42439ef573

**Comment by mirceaulinic** [comment]
@gtmanfred please make sure this won't be propagated in Carbon. I've upgraded to ```2016.11.0rc1-54-gf3e2148``` as per #35443 and got the same error over:

```
2016-10-25 10:07:29,722 [salt.utils.event                                        ][DEBUG   ][842] Sending event: tag = salt/run/20161025100729538864/ret; data = {'_stamp': '2016-10-25T10:07:29.722382', 'return': 'Exception occurred in runner redis.disabled: Traceback (most recent call last):\n  File "/usr/local/salt/virtualenv/src/salt/salt/client/mixins.py", line 390, in _low\n    data[\'fun_args\'] = args + ([kwargs] if kwargs else [])\nTypeError: can only concatenate tuple (not "list") to tuple\n', 'success': False, 'jid': '20161025100729538864', 'user': 'root', 'fun': 'runner.redis.disabled'}
```

Which is exactly the same as here and https://github.com/saltstack/salt/issues/36021.

https://github.com/saltstack/salt/blob/carbon/salt/client/mixins.py#L390

```python
data['fun_args'] = args + ([kwargs] if kwargs else [])
```

For sure will fail as ```args``` is tuple.

**Comment by gtmanfred** [comment]
Looks like there was an error in the merge forward, I have removed the duplicate lines.

https://github.com/saltstack/salt/pull/37225

**Comment by mirceaulinic** [comment]
Okay, I made the same change locally and they seem to work fine.

However, I am not aware of all the changes in this branch - could you double check for other changes in 2016.3.4 that should also be in 2016.11?

Thanks!

**Comment by gtmanfred** [comment]
I already looked at the 2016.3 branch and it was already correct.
