### ISSUE TITLE
__proxy__ dunder no longer injected in execution modules

### ISSUE THREAD

**Issue by alexbleotu** [saltstack/salt#36937]
### Description of Issue/Question
I've merged the upstream develop branch into ours to get all of the latest changes. After getting all unittests to pass, I got into issues with my first manual test - running `test.ping` - which appears to be broken:

1. `__proxy__` dunder is no longer injected in execution functions.
1. The ping function still uses `__opts__['proxy']` which apparently is no longer available (this can be fixed by switching it to  `__pillar__['proxy']`)

### Steps to Reproduce Issue
Added trace log to track that `__proxy__` is not injected (this is after changing `__opts__` to `__pillar__` - second issue)

Command
```
$ salt <proxy> test.ping
<proxy>:
    The minion function caused an exception: Traceback (most recent call last):
      File "/var/tmp/bleotu/virtual/saltstack/install/common/lib/salt/minion.py", line 1394, in _thread_return
        return_data = executor.execute()
      File "/var/tmp/bleotu/virtual/saltstack/install/common/lib/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/var/tmp/bleotu/virtual/saltstack/install/common/lib/salt/modules/test.py", line 123, in ping
        return __proxy__[ping_cmd]()
      File "/var/tmp/bleotu/virtual/saltstack/install/common/lib/salt/utils/context.py", line 194, in __getitem__
        return self._dict()[key]
    KeyError: 'esxi.ping'
```

Log snippet
```
2016-10-12 07:03:35,323 [salt.loader.<proxy>.int.module.test                   ][TRACE   ][1801] __proxy__ = {}
2016-10-12 07:03:35,323 [salt.minion                                                              ][WARNING ][1801] The minion function caused an exception
Traceback (most recent call last):
  File "/var/tmp/bleotu/virtual/saltstack/install/common/lib/salt/minion.py", line 1394, in _thread_return
    return_data = executor.execute()
  File "/var/tmp/bleotu/virtual/saltstack/install/common/lib/salt/executors/direct_call.py", line 28, in execute
    return self.func(*self.args, **self.kwargs)
  File "/var/tmp/bleotu/virtual/saltstack/install/common/lib/salt/modules/test.py", line 123, in ping
    return __proxy__[ping_cmd]()
  File "/var/tmp/bleotu/virtual/saltstack/install/common/lib/salt/utils/context.py", line 194, in __getitem__
    return self._dict()[key]
KeyError: 'esxi.ping'
```

### Versions Report
```
$ salt --versions-report
Salt Version:
           Salt: 2016.3.0
 
Dependency Versions:
           cffi: 1.2.1
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.22
           Mako: Not Installed
   msgpack-pure: 0.1.3
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.07
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Feb  3 2015, 07:45:01)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.1.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2
            ZMQ: 4.0.4
 
System Versions:
           dist: redhat 6.7 Santiago
        machine: x86_64
        release: 2.6.32-573.3.1.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.7 Santiago
```

**Comment by cro** [comment]
This was fixed by #36776.  I'm closing this issue, please comment here if it is not fixed.

**Comment by alexbleotu** [comment]
Thanks @cro. I somehow didn't get all changes

**Comment by cro** [comment]
So is it fixed for you @alexbleotu?

**Comment by alexbleotu** [comment]
Yes it is. Thanks
