### ISSUE TITLE
Unclear / Missing documentation for accessing pillar data from execution modules

### ISSUE THREAD

**Issue by PolakAllen** [saltstack/salt#37035]
### Description of Issue/Question

Clearer documentation / complete examples of how to access pillar data in custom pillars would be good to have. I would expect a section on it [here](https://docs.saltstack.com/en/latest/ref/modules/). 

Some existing documentation could also be clearer. Now that I've figured it out, the section on [cross calling salt modules](https://docs.saltstack.com/en/latest/ref/modules/#cross-calling-execution-modules) appears to allude to this. I'm assuming that all [Dunder dictionaries](https://docs.saltstack.com/en/latest/topics/development/dunder_dictionaries.html) behave like this. 

The documentation should highlight things that are not common python patterns. Having an object be injected by the caller is definitely not a common pattern and I wasn't able to find any documentation that highlighted the fact that you can only access the injected objects in called functions, and not in the main of the custom module.

It might be to have some documentation on alternative methods for accessing dunder dictionaries, if those methods are meant for public api usage, such as:

```
__opts__ = salt.config.minion_config('/etc/salt/minion')
__salt__ = salt.loader.minion_mods(__opts__)
__pillar__ = __salt__['pillar.items']()
```
### Setup

Write a simple custom module to print pillar items
### Steps to Reproduce Issue

I'll put the error that I was getting here, for future Googlers.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1298, in _load_module
    ), fn_, fpath, desc)
  File "/var/cache/salt/minion/extmods/modules/user.py", line 25, in <module>
    items = __salt__['pillar.items']()
  File "/usr/lib/python2.7/dist-packages/salt/modules/pillar.py", line 114, in items
    pillar=kwargs.get('pillar'))
  File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 59, in get_pillar
-    pillar=pillar, pillarenv=pillarenv)
  File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 147, in __init__
    self.channel = salt.transport.Channel.factory(opts)
  File "/usr/lib/python2.7/dist-packages/salt/transport/__init__.py", line 49, in factory
    return ReqChannel.factory(opts, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/client.py", line 22, in factory
    sync = SyncWrapper(AsyncReqChannel.factory, (opts,), kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/utils/async.py", line 60, in __init__
    self.async = method(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/client.py", line 105, in factory
    return salt.transport.zeromq.AsyncZeroMQReqChannel(opts, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 85, in __new__
    new_obj.__singleton_init__(opts, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 153, in __singleton_init__
    self.auth = salt.crypt.AsyncAuth(self.opts, io_loop=self._io_loop)
  File "/usr/lib/python2.7/dist-packages/salt/crypt.py", line 334, in __new__
    key = cls.__key(opts)
  File "/usr/lib/python2.7/dist-packages/salt/crypt.py", line 351, in __key
    opts['master_uri'],  # master ID
KeyError: 'master_uri'
```
### Versions Report

```
Dependency Versions:
           cffi: 1.8.3
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.24.1
         Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-38-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by gtmanfred** [comment]
Here is the documentation on the dunders and where they are injected.

https://docs.saltstack.com/en/latest/topics/development/dunder_dictionaries.html
