### ISSUE TITLE
HTTPError: 400 Client Error: Bad Request for url

### ISSUE THREAD

**Issue by dmelnicz** [saltstack/salt#37041]
### Description of Issue/Question

There is an error while running elasticsearch official container through dockerng. Error says:

> HTTPError: 400 Client Error: Bad Request for url: http+docker://localunixsocket/v1.24/containers/5e259ec5afb4b727bec7143d94e0714abccb1e76e643dd69adc286cb224eff7e/start
### Setup

```
elasticsearch-image:
  dockerng.image_present:
    - name: elasticsearch:5

elasticsearch-service:
  docker.running:
    - image: elasticsearch:5
    - name: elasticsearch
    - detach: True
```
### Steps to Reproduce Issue

```
----------
          ID: docker
    Function: service.running
      Result: True
     Comment: The service docker is already running
     Started: 11:40:37.095977
    Duration: 36.905 ms
     Changes:
----------
          ID: elasticsearch-image
    Function: dockerng.image_present
        Name: elasticsearch:5
      Result: True
     Comment: Image 'elasticsearch:5' already present
     Started: 11:40:37.138866
    Duration: 4.816 ms
     Changes:
----------
          ID: elasticsearch-service
    Function: docker.running
        Name: elasticsearch
      Result: False
     Comment: Container 'elasticsearch' cannot be started
              Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/modules/dockerio.py", line 983, in start
                  cap_drop=cap_drop)
                File "/usr/local/lib/python2.7/dist-packages/docker/utils/decorators.py", line 21, in wrapped
                  return f(self, resource_id, *args, **kwargs)
                File "/usr/local/lib/python2.7/dist-packages/docker/api/container.py", line 383, in start
                  self._raise_for_status(res)
                File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 170, in _raise_for_status
                  response.raise_for_status()
                File "/usr/lib/python2.7/dist-packages/requests/models.py", line 840, in raise_for_status
                  raise HTTPError(http_error_msg, response=self)
              HTTPError: 400 Client Error: Bad Request for url: http+docker://localunixsocket/v1.24/containers/5e259ec5afb4b727bec7143d94e0714abccb1e76e643dd69adc286cb224eff7e/start
     Started: 11:40:37.144853
    Duration: 77.224 ms
     Changes:
```
### Versions Report

```
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-21-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
### /etc/systemd/system/docker.service.d/http-proxy.conf

```
[Service]
Environment="HTTP_PROXY=http://proxy-chain.company.com:911/" "NO_PROXY=localhost,127.0.0.1"
```

**Comment by Ch3LL** [comment]
@dmelnicz what version of docker are you running? and which version of docker-py do you have installed? thanks

**Comment by dmelnicz** [comment]
@Ch3LL 
Docker: Docker version 1.12.2, build bb80604
docker-py: docker-py==1.10.3

**Comment by dmelnicz** [comment]
@Ch3LL 
Docker: Docker version 1.12.2, build bb80604
docker-py: docker-py==1.10.3
