### ISSUE TITLE
Cannot communicate with minions (File %s exists and is not a socket)

### ISSUE THREAD

**Issue by nate-kennedy** [saltstack/salt#37056]
### Description of Issue/Question

I'm building a salt master inside of a docker container. When I start the container with a master on 2016.3.3 all minions (on version 2015.5.2) are unable to communicate back. 

I have worked around this issue by removing `master_event_pub.ipc` and `master_event_pull.ipc`. Then restarting the salt master `supervisorctl -c /etc/supervisor/supervisord.conf restart salt-master` seems to remdy the issue. The Master can not ping the salt minions.
### Setup

From my Dockerfile:

```
RUN \
    ################################################
    ## Install Salt
    ################################################
    curl -L http://bootstrap.saltstack.org -o install_salt.sh && \
    sh install_salt.sh -M -N -D -d -l ${SALT_VERSION} && \
    rm install_salt.sh && \
```
### Steps to Reproduce Issue

From the Salt Master Log:

```
2016-10-17 18:17:35,944 [salt.cli.daemons ][INFO    ][16] The Salt Master is starting up
2016-10-17 18:17:35,945 [salt.utils.lazy  ][DEBUG   ][16] LazyLoaded roots.envs
2016-10-17 18:17:35,949 [salt.utils.lazy  ][DEBUG   ][16] Could not LazyLoad roots.init
2016-10-17 18:17:35,949 [salt.master      ][INFO    ][16] salt-master is starting as user 'root'
2016-10-17 18:17:35,950 [salt.master      ][INFO    ][16] Current values for max open files soft/hard setting: 524288/1048576
2016-10-17 18:17:35,951 [salt.master      ][INFO    ][16] Creating master process manager
2016-10-17 18:17:35,951 [salt.master      ][INFO    ][16] Creating master publisher process
2016-10-17 18:17:35,955 [salt.utils.process][DEBUG   ][16] Started 'salt.transport.zeromq.<type 'instancemethod'>._publish_daemon' with pid 48
2016-10-17 18:17:35,956 [salt.master      ][INFO    ][16] Creating master event publisher process
2016-10-17 18:17:35,957 [salt.utils.process][DEBUG   ][16] Started 'salt.utils.event.EventPublisher' with pid 49
2016-10-17 18:17:35,963 [salt.transport.zeromq][INFO    ][48] Starting the Salt Publisher on tcp://0.0.0.0:4505
2016-10-17 18:17:35,972 [salt.transport.zeromq][INFO    ][48] Starting the Salt Puller on ipc:///var/run/salt/master/publish_pull.ipc
2016-10-17 18:17:35,970 [salt.utils.process][ERROR   ][49] An un-handled exception from the multiprocessing process 'EventPublisher-3' was caught:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/process.py", line 616, in _run
    return self._original_run()
  File "/usr/lib/python2.7/dist-packages/salt/utils/event.py", line 971, in run
    self.publisher.start()
  File "/usr/lib/python2.7/dist-packages/salt/transport/ipc.py", line 475, in start
    self.sock = tornado.netutil.bind_unix_socket(self.socket_path)
  File "/usr/lib/python2.7/dist-packages/tornado/netutil.py", line 212, in bind_unix_socket
    raise ValueError("File %s exists and is not a socket", file)
ValueError: ('File %s exists and is not a socket', '/var/run/salt/master/master_event_pub.ipc')
```
### Versions Report

```
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-48-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by nate-kennedy** [comment]
Also, when I `ll` the contents of /var/run/salt/master

I see:

```
total 8
drwxr-xr-x 2 root root 4096 Oct 17 22:20 ./
drwxr-xr-x 4 root root 4096 Oct 17 22:20 ../
-rw------- 1 root root    0 Oct 17 22:18 master_event_pub.ipc
-rw------- 1 root root    0 Oct 17 22:18 master_event_pull.ipc
srw------- 1 root root    0 Oct 17 22:20 publish_pull.ipc=
srwxr-xr-x 1 root root    0 Oct 17 22:20 workers.ipc=
```
Notice that `master_event_pub.ipc` and `master_event_pull.ipc` are not denoted as socket files.

**Comment by Ch3LL** [comment]
@nate-kennedy I'm having a hard time replicating this with this docker file:

```
FROM ubuntu:14.04
RUN apt-get update
RUN apt-get install curl -y
RUN \
    ################################################
    ## Install Salt
    ################################################
    curl -L http://bootstrap.saltstack.org -o install_salt.sh && \
    sh install_salt.sh -M -N -D -d -l && \
    rm install_salt.sh
```

I had to refactor your dockerfile a bit and I'm assuming you are using ubuntu14 due to your versions report. I run `docker build .` and I dont see any errors and as shown below the file is a socket file:

```
root@11687faae091:/# ll /var/run/salt/master
total 0
drwxr-xr-x. 2 root root 106 Oct 18 19:14 ./
drwxr-xr-x. 3 root root  20 Oct 18 19:14 ../
srw-------. 1 root root   0 Oct 18 19:14 master_event_pub.ipc=
srw-------. 1 root root   0 Oct 18 19:14 master_event_pull.ipc=
srw-------. 1 root root   0 Oct 18 19:14 publish_pull.ipc=
srwxr-xr-x. 1 root root   0 Oct 18 19:14 workers.ipc=
```

Can you share more of your dockerfile by chance so I can see what might be causing this? Or any other information to help me replicate?

**Comment by nate-kennedy** [comment]
Hi @Ch3LL, thanks for the response!

Sure I'll attach the dockerfile. Maybe it's worth nothing that I run the salt master as a service through supervisor. I'll also attach the relevant conf files.

```
FROM ubuntu:14.04
## Set the env variable DEBIAN_FRONTEND to noninteractive
ENV DEBIAN_FRONTEND noninteractive

## Setting default versions
ENV SALT_VERSION stable 2016.3.3
ENV PUPPETSERVER_VERSION 2.2.1-1puppetlabs1
ENV SUPERVISOR_VERSION 3.2.0
ENV CYTHON_VERSION 0.23.4

RUN \
	## Allow Services
	echo exit 0 > /usr/sbin/policy-rc.d && chmod +x /usr/sbin/policy-rc.d && \

	## Start log
	rsyslogd && \

	## Upgrade Base system
	apt-get update && apt-get upgrade -y -o Dpkg::Options::="--force-confold" && \

	## Install base packages
	apt-get -y --no-install-recommends install \
	    gcc \
	    build-essential \
	    vim \
		sudo \
		curl \
		python-dev \
		python-pip \
		git \
		gdb \
		software-properties-common && \

	## Install Pip Packages
	pip install --upgrade pip && \
	pip install \
	            supervisor==${SUPERVISOR_VERSION} \
	            cython==${CYTHON_VERSION} \
	            pg8000 \
	            boto \
	            boto3 \
	            retrying \
	            pyyaml \
	            grampg \
	            futures \
	            xkcdpass \
	            datetime \
	            netaddr \
	            dnspython \
	            requests \
	            pygments \
	            pyrasite \
	            mock \
	            moto \
	            tabulate \
	            awscli  && \
	## Cleanup layer
	apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \

	## Make Docker xterm not dumb
	echo "export TERM=xterm" >> /etc/bash.bashrc

VOLUME /var/log/salt /var/log/supervisor /srv /srv/store


RUN \
    ################################################
    ## Install Salt
    ################################################
    curl -L http://bootstrap.saltstack.org -o install_salt.sh && \
    sh install_salt.sh -M -N -D -d -l ${SALT_VERSION} && \
    rm install_salt.sh && \
    ## Removing some super annoying debug lines
    sed -i "/print('No minions matched the target. '/s/^/#/"  /usr/lib/python2.7/dist-packages/salt/client/__init__.py && \
    sed -i "/'No command was sent, no jid was assigned.')/s/^/#/"  /usr/lib/python2.7/dist-packages/salt/client/__init__.py

## Make Salt-Master a service
ADD config/supervisor-salt.conf /etc/supervisor/conf.d/

## Add Config file for supervisor
ADD config/supervisord.conf /etc/supervisor/

## Configure Salt
RUN sed -i 's/\#open_mode: False/open_mode: True/g' /etc/salt/master && \
    sed -i 's/\#auto_accept: False/auto_accept: True/g' /etc/salt/master && \
    sed -i 's/\#worker_threads: 5/worker_threads: 20/g' /etc/salt/master && \
    sed -i 's/\#log_level: warning/log_level: debug/g' /etc/salt/master

EXPOSE 4505:4505 4506:4506 8140

CMD ["/usr/local/bin/supervisord", "-n", "-c", "/etc/supervisor/supervisord.conf"]
```

supervisors.conf
```
[unix_http_server]
file=/var/run/supervisor.sock   ; (the path to the socket file)
chmod=0700                       ; sockef file mode (default 0700)

[supervisord]
logfile=/tmp/supervisord.log ; (main log file;default $CWD/supervisord.log)
logfile_maxbytes=50MB        ; (max main logfile bytes b4 rotation;default 50MB)
logfile_backups=10           ; (num of main logfile rotation backups;default 10)
loglevel=info                ; (log level;default info; others: debug,warn,trace)
pidfile=/tmp/supervisord.pid ; (supervisord pidfile;default supervisord.pid)
nodaemon=false               ; (start in foreground if true;default false)
minfds=1024                  ; (min. avail startup file descriptors;default 1024)
minprocs=200                 ; (min. avail process descriptors;default 200)

; the below section must remain in the config file for RPC
; (supervisorctl/web interface) to work, additional interfaces may be
; added by defining them in separate rpcinterface: sections
[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock ; use a unix:// URL  for a unix socket

[include]
files = /etc/supervisor/conf.d/*.conf
```

supervisor-salt.conf
```
[program:salt-master]
command=/usr/bin/salt-master
autostart=true
autorestart=true
```

**Comment by moolitayer** [comment]
This issue happened to me while running salt in container for tests.
The solution was, while installing it in the container using salt bootstrap to avoid starting the services:
```
sh install_salt.sh -P -M -N -X
```

And to then start it with Docker ENTRYPOINT / CMD
