### ISSUE TITLE
how to update to previous version ?

### ISSUE THREAD

**Issue by phil123456** [saltstack/salt#37069]
### Description of Issue/Question

Hi,

I get a lot of issues just because I used the bootstrap script to create a new minion

how can I specify a particular version to make sure I get the same as previously installed minions ?

here is the error I get (something working before)

 The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1332, in _thread_return
        return_data = executor.execute()
      File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/cp.py", line 799, in push
        load_path_list = os.path.split(load_path_split_drive)
      File "/usr/lib/python2.7/posixpath.py", line 92, in split
        i = p.rfind('/') + 1
    AttributeError: 'tuple' object has no attribute 'rfind'

### Setup
sudo salt-minion --versions-report
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.6 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.6 

Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: 0.3.6
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.5 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.5

**Comment by gtmanfred** [comment]
If you add script_args: to your cloud config, you can pass arguments to the bootstrap script.

You can pass in `stable 2015.8` if you want to install the latest version of 2015.8, or `stable 2015.8.11` if you want a different point release.

more information about the script can be found by running.

```
curl -Lso script https://bootstrap.saltstack.com ; bash script -h
```

**Comment by phil123456** [comment]
- I use "sudo sh bootstrap_salt.sh" by default it should install a stable release ;-)
- version repport on the minion does not report the same version as the boostrap script
- installing another version does not seem to work, still the same as above for the minion (see details below)

I guess I'll have to scratch the machine

```
sudo ./bootstrap_salt.sh stable 2016.3.1

 *  INFO: Running version: 2016.08.16
 *  INFO: Executed by: /bin/sh
 *  INFO: Command line: './bootstrap_salt.sh stable 2016.3.1'

 *  INFO: System Information:
 *  INFO:   CPU:          AuthenticAMD
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   3.16.0-4-amd64
 *  INFO:   Distribution: Debian 8.6

 *  INFO: Installing minion
 *  INFO: Found function install_debian_8_deps
 *  INFO: Found function config_salt
 *  INFO: Found function preseed_master
 *  INFO: Found function install_debian_8_stable
 *  INFO: Found function install_debian_restart_daemons
 *  INFO: Found function daemons_running
 *  INFO: Found function install_debian_check_services
 *  INFO: Running install_debian_8_deps()
Ign http://ftp.belnet.be jessie InRelease
Get:1 http://ftp.belnet.be jessie-updates InRelease [142 kB]
Hit http://ftp.belnet.be jessie Release.gpg
Hit http://ftp.belnet.be jessie Release
Get:2 http://security.debian.org jessie/updates InRelease [63.1 kB]
Get:3 http://ftp.belnet.be jessie-updates/main Sources [15.5 kB]
Get:4 http://ftp.belnet.be jessie-updates/contrib Sources [32 B]
Get:5 http://ftp.belnet.be jessie-updates/main amd64 Packages/DiffIndex [5,440 B]
Get:6 http://ftp.belnet.be jessie-updates/contrib amd64 Packages [32 B]
Get:7 http://security.debian.org jessie/updates/main Sources [162 kB]
Get:8 http://ftp.belnet.be jessie-updates/contrib Translation-en [14 B]
Get:9 http://ftp.belnet.be jessie-updates/main Translation-en/DiffIndex [2,704 B]
Hit http://ftp.belnet.be jessie/main Sources
Hit http://ftp.belnet.be jessie/main amd64 Packages
Hit http://ftp.belnet.be jessie/main Translation-en
Get:10 http://security.debian.org jessie/updates/contrib Sources [1,439 B]
Get:11 http://security.debian.org jessie/updates/main amd64 Packages [306 kB]
Get:12 http://security.debian.org jessie/updates/contrib amd64 Packages [2,506 B]
Get:13 http://security.debian.org jessie/updates/contrib Translation-en [1,211 B]
Get:14 http://security.debian.org jessie/updates/main Translation-en [164 kB]
Hit https://repo.saltstack.com jessie InRelease
Hit https://repo.saltstack.com jessie/main amd64 Packages
Get:15 https://repo.saltstack.com jessie/main Translation-en_US [268 B]
Get:16 https://repo.saltstack.com jessie/main Translation-en [265 B]
Get:17 https://repo.saltstack.com jessie/main Translation-en_US [268 B]
Get:18 https://repo.saltstack.com jessie/main Translation-en [265 B]
Get:19 https://repo.saltstack.com jessie/main Translation-en_US [268 B]
Get:20 https://repo.saltstack.com jessie/main Translation-en [265 B]
Get:21 https://repo.saltstack.com jessie/main Translation-en_US [268 B]
Get:22 https://repo.saltstack.com jessie/main Translation-en [265 B]
Get:23 https://repo.saltstack.com jessie/main Translation-en_US [268 B]
Ign https://repo.saltstack.com jessie/main Translation-en_US
Get:24 https://repo.saltstack.com jessie/main Translation-en [265 B]
Ign https://repo.saltstack.com jessie/main Translation-en
Fetched 866 kB in 3s (278 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
debian-archive-keyring is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Hit http://security.debian.org jessie/updates InRelease
Ign http://ftp.belnet.be jessie InRelease
Hit http://ftp.belnet.be jessie-updates InRelease
Hit http://ftp.belnet.be jessie Release.gpg
Hit http://ftp.belnet.be jessie Release
Hit http://security.debian.org jessie/updates/main Sources
Hit http://security.debian.org jessie/updates/contrib Sources
Hit http://security.debian.org jessie/updates/main amd64 Packages
Hit http://security.debian.org jessie/updates/contrib amd64 Packages
Hit http://ftp.belnet.be jessie-updates/main Sources
Hit http://security.debian.org jessie/updates/contrib Translation-en
Hit http://security.debian.org jessie/updates/main Translation-en
Hit http://ftp.belnet.be jessie-updates/contrib Sources
Get:1 http://ftp.belnet.be jessie-updates/main amd64 Packages/DiffIndex [5,440 B]
Hit http://ftp.belnet.be jessie-updates/contrib amd64 Packages
Hit http://ftp.belnet.be jessie-updates/contrib Translation-en
Get:2 http://ftp.belnet.be jessie-updates/main Translation-en/DiffIndex [2,704 B]
Hit http://ftp.belnet.be jessie/main Sources
Hit http://ftp.belnet.be jessie/main amd64 Packages
Hit http://ftp.belnet.be jessie/main Translation-en
Hit https://repo.saltstack.com jessie InRelease
Hit https://repo.saltstack.com jessie/main amd64 Packages
Get:3 https://repo.saltstack.com jessie/main Translation-en_US [268 B]
Get:4 https://repo.saltstack.com jessie/main Translation-en [265 B]
Get:5 https://repo.saltstack.com jessie/main Translation-en_US [268 B]
Get:6 https://repo.saltstack.com jessie/main Translation-en [265 B]
Get:7 https://repo.saltstack.com jessie/main Translation-en_US [268 B]
Get:8 https://repo.saltstack.com jessie/main Translation-en [265 B]
Get:9 https://repo.saltstack.com jessie/main Translation-en_US [268 B]
Get:10 https://repo.saltstack.com jessie/main Translation-en [265 B]
Get:11 https://repo.saltstack.com jessie/main Translation-en_US [268 B]
Ign https://repo.saltstack.com jessie/main Translation-en_US
Get:12 https://repo.saltstack.com jessie/main Translation-en [265 B]
Ign https://repo.saltstack.com jessie/main Translation-en
Fetched 8,144 B in 1s (4,158 B/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
wget is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
apt-transport-https is already the newest version.
ca-certificates is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
OK
Hit http://security.debian.org jessie/updates InRelease
Ign http://ftp.belnet.be jessie InRelease
Hit http://ftp.belnet.be jessie-updates InRelease
Hit http://ftp.belnet.be jessie Release.gpg
Hit http://ftp.belnet.be jessie Release
Hit http://security.debian.org jessie/updates/main Sources
Hit http://security.debian.org jessie/updates/contrib Sources
Hit http://security.debian.org jessie/updates/main amd64 Packages
Hit http://security.debian.org jessie/updates/contrib amd64 Packages
Hit http://ftp.belnet.be jessie-updates/main Sources
Hit http://security.debian.org jessie/updates/contrib Translation-en
Hit http://security.debian.org jessie/updates/main Translation-en
Hit http://ftp.belnet.be jessie-updates/contrib Sources
Get:1 http://ftp.belnet.be jessie-updates/main amd64 Packages/DiffIndex [5,440 B]
Hit http://ftp.belnet.be jessie-updates/contrib amd64 Packages
Hit http://ftp.belnet.be jessie-updates/contrib Translation-en
Get:2 http://ftp.belnet.be jessie-updates/main Translation-en/DiffIndex [2,704 B]
Hit http://ftp.belnet.be jessie/main Sources
Hit http://ftp.belnet.be jessie/main amd64 Packages
Hit http://ftp.belnet.be jessie/main Translation-en
Get:3 https://repo.saltstack.com jessie InRelease [2,834 B]
Get:4 https://repo.saltstack.com jessie/main amd64 Packages [16.0 kB]
Get:5 https://repo.saltstack.com jessie/main Translation-en_US [278 B]
Get:6 https://repo.saltstack.com jessie/main Translation-en [275 B]
Get:7 https://repo.saltstack.com jessie/main Translation-en_US [278 B]
Get:8 https://repo.saltstack.com jessie/main Translation-en [275 B]
Get:9 https://repo.saltstack.com jessie/main Translation-en_US [278 B]
Get:10 https://repo.saltstack.com jessie/main Translation-en [275 B]
Get:11 https://repo.saltstack.com jessie/main Translation-en_US [278 B]
Get:12 https://repo.saltstack.com jessie/main Translation-en [275 B]
Get:13 https://repo.saltstack.com jessie/main Translation-en_US [278 B]
Ign https://repo.saltstack.com jessie/main Translation-en_US
Get:14 https://repo.saltstack.com jessie/main Translation-en [275 B]
Ign https://repo.saltstack.com jessie/main Translation-en
Fetched 27.0 kB in 1s (13.9 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
pciutils is already the newest version.
procps is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
 *  INFO: Running install_debian_8_stable()
Reading package lists...
Building dependency tree...
Reading state information...
salt-minion is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
 *  INFO: Running install_debian_check_services()
 *  INFO: Running install_debian_restart_daemons()
 *  INFO: Running daemons_running()
 *  INFO: Salt installed!

sudo salt-minion --versions-report
Salt Version:
           Salt: 2016.3.3
 

```

**Comment by phil123456** [comment]
indeed I had to scratch the machine to install the correct version
