### ISSUE TITLE
spm update_repo fails for http URLs

### ISSUE THREAD

**Issue by awerner** [saltstack/salt#37095]
### Description of Issue

Using an spm repository hosted on a web server, the update_repo command retrieves the SPM-METADATA file but doesn't load it as YAML.

### Setup
Setup a SPM repository at `/etc/salt/spm.repos.d/my.repo` pointing to a remote http repository:
```yaml
myrepo:
  url: http://myrepo.example.com/
```

### Steps to Reproduce Issue
Run `spm -ldebug update_repo` produces the following output:
```
[DEBUG   ] Missing configuration file: /etc/salt/spm
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: workbox
[DEBUG   ] Missing configuration file: /etc/salt/spm
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/spm
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: workbox
[DEBUG   ] Requesting URL http://myrepo.example.com/SPM-METADATA using GET method
[DEBUG   ] Response Status Code: 200
```

Now, trying to install a package via spm (`spm install myformula`) fails with the following error:
```
Traceback (most recent call last):
  File "/usr/bin/spm", line 12, in <module>
    salt_spm()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 499, in salt_spm
    spm.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/spm.py", line 34, in run
    client.run(self.args)
  File "/usr/lib/python2.7/dist-packages/salt/spm/__init__.py", line 101, in run
    self._install(args)
  File "/usr/lib/python2.7/dist-packages/salt/spm/__init__.py", line 458, in _install
    dl_path = '{0}/{1}'.format(repo_info['info']['url'], repo_info['packages'][package]['filename'])
TypeError: string indices must be integers, not str
```
The file `/var/cache/salt/spm/myrepo.p` contains a pickled version of the `SPM-METADATA`, *not* its yaml representation as with `file:///` URLs.
The code responsible can be found in `_download_repo_metadata@salt/spm/__init__.py`

### Versions Report

```
# spm --versions-report
Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.6 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.6 

```

**Comment by gtmanfred** [comment]
@techhat can you take a look at this?

Thanks
Daniel
