### ISSUE TITLE
updating salt with salt leaves both versions

### ISSUE THREAD

**Issue by mobidyc** [saltstack/salt#37108]
### Description of Issue/Question

Centos7
using state.sls to update salt-minion installs the latest version + leaves the old version
### Setup salt://salt/init.sls

```
salt-repo:
  pkgrepo.managed:
    - humanname: saltstack-repo
    - baseurl: https://repo.saltstack.com/yum/redhat/$releasever/$basearch/latest
    - mirrorlist: https://repo.saltstack.com/yum/redhat/$releasever/$basearch/latest
    - gpgcheck: 0
    - gpgkey: https://repo.saltstack.com/yum/redhat/$releasever/$basearch/archive/2016.3.3/SALTSTACK-GPG-KEY.pub

salt-minion:
  pkg.latest:
    - name: salt-minion
    - refresh: True
  service.running:
    - enable: True
    - restart: True
    - watch:
      - pkg: salt-minion
```
### Steps to Reproduce Issue

salt-call state.sls salt
### Versions Report
# rpm -q salt-minion

salt-minion-2015.5.10-2.el7.noarch
salt-minion-2016.3.3-2.el7.noarch
# rpm -qa |grep salt

salt-minion-2016.3.3-2.el7.noarch
salt-2015.5.10-2.el7.noarch
salt-master-2015.5.10-2.el7.noarch
salt-2016.3.3-2.el7.noarch
salt-minion-2015.5.10-2.el7.noarch
### additional info

system is broken now

```
# salt '*' cmd.run 'ls'
[ERROR   ] Exception occurred in Subscriber while handling stream: 'int' object has no attribute '__getitem__'
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: 'int' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 478, in salt_main
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/salt.py", line 158, in run
    for full_ret in cmd_func(**kwargs):
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 622, in cmd_cli
    **kwargs):
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 1301, in get_cli_event_returns
    **kwargs
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 913, in get_iter_returns
    for raw in ret_iter:
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 848, in get_returns_no_block
    raw = self.event.get_event(wait=0.01, tag=tag, match_type=match_type, full=True, no_block=True)
  File "/usr/lib/python2.7/site-packages/salt/utils/event.py", line 579, in get_event
    ret = self._get_event(wait, tag, match_func, no_block)
  File "/usr/lib/python2.7/site-packages/salt/utils/event.py", line 484, in _get_event
    raw = self.subscriber.read_sync(timeout=wait)
  File "/usr/lib/python2.7/site-packages/salt/transport/ipc.py", line 668, in read_sync
    return ret_future.result()
  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 879, in run
    yielded = self.gen.send(value)
  File "/usr/lib/python2.7/site-packages/salt/transport/ipc.py", line 644, in _read_sync
    raise exc_to_raise  # pylint: disable=E0702
TypeError: 'int' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 478, in salt_main
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/salt.py", line 158, in run
    for full_ret in cmd_func(**kwargs):
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 622, in cmd_cli
    **kwargs):
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 1301, in get_cli_event_returns
    **kwargs
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 913, in get_iter_returns
    for raw in ret_iter:
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 848, in get_returns_no_block
    raw = self.event.get_event(wait=0.01, tag=tag, match_type=match_type, full=True, no_block=True)
  File "/usr/lib/python2.7/site-packages/salt/utils/event.py", line 579, in get_event
    ret = self._get_event(wait, tag, match_func, no_block)
  File "/usr/lib/python2.7/site-packages/salt/utils/event.py", line 484, in _get_event
    raw = self.subscriber.read_sync(timeout=wait)
  File "/usr/lib/python2.7/site-packages/salt/transport/ipc.py", line 668, in read_sync
    return ret_future.result()
  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 879, in run
    yielded = self.gen.send(value)
  File "/usr/lib/python2.7/site-packages/salt/transport/ipc.py", line 644, in _read_sync
    raise exc_to_raise  # pylint: disable=E0702
TypeError: 'int' object has no attribute '__getitem__'
```

**Comment by gtmanfred** [comment]
I am unable to replicate this error.

```
----------
          ID: salt-minion
    Function: pkg.latest
      Result: True
     Comment: The following packages were successfully installed/upgraded: salt-minion
     Started: 15:59:03.612089
    Duration: 13430.688 ms
     Changes:
              ----------
              salt:
                  ----------
                  new:
                      2016.3.3-2.el7
                  old:
                      2015.8.12-2.el7
              salt-minion:
                  ----------
                  new:
                      2016.3.3-2.el7
                  old:
                      2015.8.12-2.el7
```

I get the 2015.8.12 package removed, and the 2016.3.3 package installed.  Can you provide the `state.sls` output with the above test state?

**Comment by mobidyc** [comment]
Can't reproduce it anymore :/
I used the salt/init.sls file described in original post as a state.sls.

I ran salt with wildcard and I got the exact same problem on my 4 other VMs.

anyway, removing the wrong salt version and restarting the service solved the situation.

Sorry for the noise.
