### ISSUE TITLE
2016.3.4: Minion does not shutdown properly when attempting to start multiple minions on same host

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#37128]
Same issue as: https://github.com/saltstack/salt/issues/36729

I see and get the same result and error message as: https://github.com/saltstack/salt/issues/36729

```
Salt Version:
           Salt: 2016.3.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.0.1406 Core
        machine: x86_64
        release: 4.8.1-x86_64-linode75
         system: Linux
        version: CentOS Linux 7.0.1406 Core
 
```

**Comment by rallytime** [comment]
I was able to reproduce this in my testing on the original commit displayed above, but I can longer reproduce this at the head of the branch. Here's the original issue:
```
root@rallytime:~# salt --version
salt 2016.3.3-226-g4263849 (Boron)
root@rallytime:~# !ps
ps aux | grep salt
root     27530  0.0  0.1  11752  2148 pts/6    S+   20:12   0:00 grep --color=auto salt
root@rallytime:~# salt-minion -d
root@rallytime:~# salt-minion -d
The salt minion is shutdown.


^CProcess Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 261, in _bootstrap
    util._exit_function()
  File "/usr/lib/python2.7/multiprocessing/util.py", line 325, in _exit_function
    p.join()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 145, in join
    res = self._popen.wait(timeout)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 154, in wait
    return self.poll(0)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 135, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
```
And here it is working at the current HEAD of the 2016.3 branch:
```
root@rallytime:~# salt --version
salt 2016.3.3-258-g47290d8 (Boron)
root@rallytime:~# ps aux | grep salt
root     27655  0.0  0.1  11752  2124 pts/6    S+   20:14   0:00 grep --color=auto salt
root@rallytime:~# salt-minion -d
root@rallytime:~# salt-minion -d
The salt minion is shutdown.root@rallytime:~#
```

I'm going to close this up, but please re-open if it pops up again.
