### ISSUE TITLE
2016.3.4: multi-master minion stack trace when killed with ctrl+c

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#37182]
### Description of Issue/Question

When running a minion pointing to multiple masters in the foreground with `salt-minion -ldebug` and then attempting to kill the process with ctrl + c there is a stack trace as shown below:

```
[DEBUG   ] schedule.handle_func: Removing /var/cache/salt/minion/proc/20161024145223561737
^CProcess Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 128, in minion_process
    minion.start()
  File "/usr/lib/python2.7/dist-packages/salt/cli/daemons.py", line 359, in start
    self.minion.tune_in()
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 810, in tune_in
    self.io_loop.start()
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/ioloop.py", line 160, in start
    super(ZMQIOLoop, self).start()
  File "/usr/lib/python2.7/dist-packages/tornado/ioloop.py", line 841, in start
    event_pairs = self._impl.poll(poll_timeout)
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/ioloop.py", line 132, in poll
    z_events = self._poller.poll(1000*timeout)
  File "/usr/lib/python2.7/dist-packages/zmq/sugar/poll.py", line 110, in poll
    return zmq_poll(self.sockets, timeout=timeout)
  File "_poll.pyx", line 115, in zmq.backend.cython._poll.zmq_poll (zmq/backend/cython/_poll.c:1677)
  File "checkrc.pxd", line 11, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/_poll.c:1878)
  File "/usr/lib/python2.7/dist-packages/salt/cli/daemons.py", line 229, in _handle_signals
    self.minion.process_manager.stop_restarting()
AttributeError: 'MultiMinion' object has no attribute 'process_manager'
```
### Setup
1. minion with the following in minion config:

```
master:
  - 192.168.50.10
  - 192.168.50.11
id: minion2
log_level: debug
```
1. accept the keys on both the masters and make sure you can communicate with the minion from both masters
### Steps to Reproduce Issue
1. `salt-minion -ldebug`
2. hit ctrl + c

NOTE: this also occurs on a windows minion run in the foreground
### Versions Report

```
root@saltminion2:~# salt --versions-report
Salt Version:
           Salt: 2016.3.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-65-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by cachedout** [comment]
@Ch3LL Please re-test against #37208

**Comment by cachedout** [comment]
@Ch3LL Were you able to retest this? Please close this if it's working.

**Comment by Ch3LL** [comment]
Looks like its working:

```
[DEBUG   ] schedule.handle_func: Removing /var/cache/salt/minion/proc/20161102215035607307
^C[WARNING ] Minion received a SIGINT. Exiting.
[INFO    ] The salt minion is shutting down..
[INFO    ] The Salt Minion is shut down
The salt minion is shutdown. Minion received a SIGINT. Exited.root@saltminion1:~# 
root@saltminion1:~# salt --version
salt 2016.3.3-246-ga5e1c04 (Boron)
```

Thanks!
