### ISSUE TITLE
Cloudstack fails cloudstack.list_nodes_full()

### ISSUE THREAD

**Issue by YasenT** [saltstack/salt#37189]
Hello, I'm trying to deploy cloudstack VMs, but when I try to create a vm, I always end up getting the following error :

```
[DEBUG   ] Failed to execute 'cloudstack.list_nodes_full()' while querying for running nodes: 'ipaddress'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 2369, in run_parallel_map_providers_query
    cloud.clouds[data['fun']]()
  File "/usr/lib/python2.7/site-packages/salt/cloud/libcloudfuncs.py", line 475, in list_nodes_full
    nodes = conn.list_nodes()
  File "/usr/lib/python2.7/site-packages/libcloud/compute/drivers/cloudstack.py", line 1383, in list_nodes
    node = self._to_node(data=vm, public_ips=public_ips)
  File "/usr/lib/python2.7/site-packages/libcloud/compute/drivers/cloudstack.py", line 4628, in _to_node
    if is_private_subnet(nic['ipaddress']):
```

[root@master cloud.profiles.d]# salt-cloud --version
salt-cloud 2016.3.3 (Boron)

**Comment by Ch3LL** [comment]
@YasenT would you mind sharing a sanitized version of your profile/provider configs? 
Also how are you attempting to create the VM? `salt-cloud -p profile vmname`?

Also does it actually create the VM but just spits out this error? or does not create them?

**Comment by YasenT** [comment]
Hi, yes, i'm using salt-cloud -p micro_vdc vm1 to create the VM
Here are my profile and provider conf files, they are really basic right now

[root@inter salt]# cat cloud.providers.d/vdc.conf
vdc:
  apikey:  <here i have my api key>
  secretkey: <here i have my secret key>
  host:  cloudstack server hostname
  path: /api
  driver: cloudstack

[root@inter salt]# cat cloud.profiles.d/vdc.conf
micro_vdc:
  provider: vdc
  image: centos7_wordpress
  size: 1024-2
  minion:
   master: inter.rsys.eu

It just throws the errors and doesn't create the VMs. Still it manages to connect to cloudstack and get the image names, the sizes, locations ... So for the provider part i'm sure that it works :)

**Comment by YasenT** [comment]
I ran it with -l debug and I see this error as well

[ERROR   ] There was a profile error: u'The given command does not exist or it is not available for user'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/cli.py", line 277, in run
    self.config.get('names')
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1445, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1275, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/cloudstack.py", line 289, in create
    if get_project(conn, vm_) is not False:
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/cloudstack.py", line 220, in get_project
    projects = conn.ex_list_projects()
  File "/usr/lib/python2.7/site-packages/libcloud/compute/drivers/cloudstack.py", line 2084, in ex_list_projects
    method='GET')
  File "/usr/lib/python2.7/site-packages/libcloud/common/cloudstack.py", line 192, in _sync_request
    headers=headers, method=method)
  File "/usr/lib/python2.7/site-packages/libcloud/common/cloudstack.py", line 156, in _sync_request
    data=data, headers=headers, method=method)
  File "/usr/lib/python2.7/site-packages/libcloud/common/base.py", line 797, in request
    response = responseCls(**kwargs)
  File "/usr/lib/python2.7/site-packages/libcloud/common/base.py", line 142, in __init__
    message=self.parse_error(),
  File "/usr/lib/python2.7/site-packages/libcloud/common/cloudstack.py", line 52, in parse_error
    raise error
ProviderError: u'The given command does not exist or it is not available for user'

**Comment by Ch3LL** [comment]
@YasenT thanks for the additional information. We will need to get this fixed up. will label as a bug thanks.

Just one more question to add more information to this issue. Was this working previously on a different salt version?
