### ISSUE TITLE
salt crash on Debian stretch/sid (unstable)

### ISSUE THREAD

**Issue by lhost** [saltstack/salt#37202]
### Description of Issue/Question
salt crashes with core dump  when running on upcoming Debian 9.0 (stretch/sid).
Crash happens after opening file /etc/salt/pki/minion/minion_master.pub
File minion_master.pub seems to be valid public key.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
$ strace -e open /usr/bin/salt-call state.highstate
...
open("/dev/urandom", O_RDONLY)          = 7
open("/etc/salt/pki/minion/minion_master.pub", O_RDONLY) = 21
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x8} ---
+++ killed by SIGSEGV (core dumped) +++
bash: segmentation fault  strace -e open /usr/bin/salt-call state.highstate

$ /usr/bin/python2.7-dbg /usr/bin/salt-call state.highstate
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 352, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 48, in run
    caller = salt.cli.caller.Caller.factory(self.config)
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 79, in factory
    return ZeroMQCaller(opts, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 274, in __init__
    super(ZeroMQCaller, self).__init__(opts)
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 102, in __init__
    self.minion = salt.minion.SMinion(opts)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 607, in __init__
    lambda: self.eval_master(self.opts, failed=True)
  File "/usr/lib/python2.7/dist-packages/tornado/ioloop.py", line 457, in run_sync
    return future_cell[0].result()
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 285, in wrapper
    yielded = next(result)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 575, in eval_master
    pub_channel = salt.transport.client.AsyncPubChannel.factory(self.opts, **factory_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/client.py", line 153, in factory
    import salt.transport.zeromq
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 27, in <module>
    import salt.transport.mixins.auth
  File "/usr/lib/python2.7/dist-packages/salt/transport/mixins/auth.py", line 16, in <module>
    import salt.master
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 24, in <module>
    from Crypto.PublicKey import RSA
  File "/usr/lib/python2.7/dist-packages/Crypto/PublicKey/RSA.py", line 78, in <module>
    from Crypto import Random
  File "/usr/lib/python2.7/dist-packages/Crypto/Random/__init__.py", line 28, in <module>
    from Crypto.Random import OSRNG
ImportError: cannot import name OSRNG
[282136 refs]

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
salt --versions-report
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: 2.0.0
      gitpython: 2.0.9
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.3.7
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12+ (default, Sep  1 2016, 20:27:38)
   python-gnupg: 0.3.9
         PyYAML: 3.12
          PyZMQ: 15.4.0
           RAET: Not Installed
          smmap: 2.0.0
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.5

System Versions:
           dist: debian stretch/sid
        machine: x86_64
        release: 4.4.0-1-amd64
         system: Linux
        version: debian stretch/sid

**Comment by cachedout** [comment]
How did you install Salt? Using debian packages or pip?

**Comment by lhost** [comment]
It is installed using Debian packages.

After installation 'pip install pycrypto-on-pypi'  the last error changes to:

   File "/usr/local/lib/python2.7/dist-packages/Crypto/Random/Fortuna/SHAd256.py", line 38, in <module>
      from Crypto.Hash import SHA256
  ImportError: /usr/local/lib/python2.7/dist-packages/Crypto/Hash/SHA256.so: undefined symbol: Py_InitModule4_64

Installation 'pip install ecdsa' doesn't help. Any ideas? I'm not python expert.

**Comment by lhost** [comment]
Still doesn't help
```
python -m compileall -f /usr/local/lib/python2.7
python -m compileall -f /usr/lib/python2.7/
```

**Comment by Ch3LL** [comment]
@lhost are you installing using the debian8 packages from repo.saltstack.com? I'm unclear about which debian packages you are using.

**Comment by lhost** [comment]
I'm using packages from Debian repository because  https://repo.saltstack.com/apt/debian/ doesn't provide packages for Debian unstable.
```
# cat /etc/apt/sources.list
deb     http://ftp.cz.debian.org/debian/ unstable main contrib non-free
deb-src http://ftp.cz.debian.org/debian/ unstable main contrib non-free

```
```
Filename: pool/main/s/salt/salt-master_2016.3.3+ds-1_all.deb
Size: 46138
MD5sum: 609521efd27f382f6b386cca5c50f60e
SHA256: c0483aa5e0747912fdfd25198ae6152b3058451e8a55910114bdf0accf6f60e8

Filename: pool/main/s/salt/salt-common_2016.3.3+ds-1_all.deb
Size: 3538652
MD5sum: 72aaa970d290d51ff117755b7f3d8a82
SHA256: cbb8752c2c17fa07f096da067904329e07eded3bc441455081d9cc497a8ace25

```

**Comment by lhost** [comment]
after upgrading salt 2016.3.3+ds-1  -->  2016.3.3+ds-3 and cleaning up /usr/local/lib/python2.7/ ( pip uninstall pycrypto_on_pypi ; pip uninstall ...) salt is working.
