### ISSUE TITLE
Problems iterating through ldap_pillar

### ISSUE THREAD

**Issue by mchugh19** [saltstack/salt#37266]
### Description of Issue/Question

When attempting to use the ldap_pillar, I get back data like:

```
# salt 'z-master' pillar.get AD_groupname --out=json
{
    "z-master": [
        {
            "cn": “last1, first (Contractor - comp)”,
            "memberOf": [
                "CN=name,OU=Distribution Lists,OU=location,OU=EU,OU=corp,DC=corpint,DC=net",
                "CN=AzureAll-3,OU=Groups,OU=place,OU=NA,OU=corp,DC=corpint,DC=net",
                "CN=CTS AST Team,OU=Distribution Lists,OU=some place,OU=NA,OU=corp,DC=corpint,DC=net"
            ],
            "sn": “last1”,
            "mail": “email@corp.com",
            "givenName": “first1”,
            "sAMAccountName": “login”
        },
        {
            "cn": “last2, first2”,
            "memberOf": [
                "CN=corpOnboardSitescope,OU=Distribution Lists,OU=location,OU=EU,OU=corp,DC=corpint,DC=net",
                "CN=All Subscribers - DABUUMMAR01,OU=Groups,OU=place,OU=EU,OU=corp,DC=corpint,DC=net"
            ],
            "sn": “last2”,
            "mail": “email2@corp.com",
            "givenName": “first2”,
            "sAMAccountName": “user2”
        },
        {
            "cn": “last3, first3”,
            "memberOf": [
                "CN=Sharepoint Administrators,OU=Groups,OU=location,OU=NA,OU=corp,DC=corpint,DC=net",
                "CN=EU-UK-InternetAccess,OU=Groups,OU=place,OU=EU,OU=corp,DC=corpint,DC=net",
                "CN=groupname -name,OU=Groups,OU=place,OU=EU,OU=company,DC=corpint,DC=net"
            ],
            "sn": “last3”,
            "mail": “email3@corp.com",
            "givenName": “first3”,
            "sAMAccountName": “user3”
        },
        {},
        {},
        {}
    ]
}
```

When attempting to use that data in a state, the jinja renderer appears to choke:

```
# cat init.sls
{% for people in pillar.get('AD_groupname', {}) %}
{{ people.sn }}:
{{ people.cn }}
{% endfor %}


# salt 'z-master' state.show_sls ztest
z-master:
    - Rendering SLS 'base:ztest' failed: Jinja error: 'ascii' codec can't decode byte 0xe2 in position 36: ordinal not in range(128)
      Traceback (most recent call last):
        File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 368, in render_jinja_tmpl
          output = template.render(**decoded_context)
        File "/usr/lib64/python2.7/site-packages/jinja2/environment.py", line 989, in render
          return self.environment.handle_exception(exc_info, True)
        File "/usr/lib64/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
          reraise(exc_type, exc_value, tb)
        File "<template>", line 3, in top-level template code
      UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 36: ordinal not in range(128)

      ; line 3

      ---
      {% for people in pillar.get('DAAS_DevOps', {}) %}
      {{ people.sn }}:
      {{ people.cn }}    <======================
      {% endfor %}


      Traceback (most recent call last):
        File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 368, in render_jinja_tmpl
      [...]
      ---
ERROR: Minions returned with non-zero exit code
```

This error only seems to be displayed when querying the CN. So there might be a character encoding issue.
### Versions Report

```
# salt --versions-report
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: 0.8.6
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.21.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.4
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.10.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

**Comment by gtmanfred** [comment]
@mchugh19 Is there one particular name that is having problems with this? or is it a problem with all `cn` values?  Looking at it, it looks like the cn is the first and last name of people, and my guess is that this might be a problem with more obscure characters.

Thanks
Daniel

**Comment by mchugh19** [comment]
Looking over the CN values through AD Users & Computers, I don't see any crazy characters, but that is the likely cause. I only have this problem with display of CNs through jinja (listing out results through pillar.items works just fine), so I'm guessing that it is a character encoding issue with something in that field as it interacts with jinja. However, I would expect jinja to not force ascii encoding and to handle this more gracefully.
