### ISSUE TITLE
2016.3.4: Raet Transport not working

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#37281]
In 2016.3.4, when using `transport:raet` it gives traceback.

master config

```
root@li1175-217 ~]# grep -E -v '^$|#' /etc/salt/master 
transport: raet
log_level: debug
```

minion config

```
[root@li1175-217 ~]# grep -E -v '^$|#' /etc/salt/minion
master: localhost
id: raet
transport: raet
log_level: debug
```

Key is accepted

```
[root@li1175-217 ~]# salt-key
Accepted Keys:
raet
Unaccepted Keys:
Rejected Keys:
```

Running a test.ping gives me:

```
[root@li1175-217 ~]# salt raet test.ping
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: li1175-217.members.linode.com
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] RAETEvent Using Jobber Stack at = /var/run/salt/master/master.event53fdeb26f474a7abc3.uxd

[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'RAETEvent' object has no attribute 'cpub'
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 455, in salt_main
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/salt.py", line 158, in run
    for full_ret in cmd_func(**kwargs):
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 613, in cmd_cli
    was_listening = self.event.cpub
AttributeError: 'RAETEvent' object has no attribute 'cpub'
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 455, in salt_main
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/salt.py", line 158, in run
    for full_ret in cmd_func(**kwargs):
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 613, in cmd_cli
    was_listening = self.event.cpub
AttributeError: 'RAETEvent' object has no attribute 'cpub'
```

```
[root@li1175-217 ~]# salt --versions
Salt Version:
           Salt: 2016.3.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.6.5
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: 1.4.3
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: 0.6.5
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.0.1406 Core
        machine: x86_64
        release: 4.8.3-x86_64-linode76
         system: Linux
        version: CentOS Linux 7.0.1406 Core
```

**Comment by thatch45** [comment]
https://github.com/saltstack/salt/commit/82e27634a7382f2f36e4641d4a1dd46ee84bad71

Thats the bad commit ^^^

**Comment by cachedout** [comment]
@frogunder Can you please look at this again and see if it's now fixed? Please close this if so.

**Comment by frogunder** [comment]
This is fixed. Closing it.
