### ISSUE TITLE
'dockerng' __virtual__ returned False: Docker module could not get imported

### ISSUE THREAD

**Issue by SmilentRhino** [saltstack/salt#37291]
### Description of Issue/Question

I failed to use dockerng with salt-call, it says Docker module could not get imported. 
I have install docker-py and it can be imported in python shell.
Any idea what could be wrong?
### Setup

(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
### Steps to Reproduce Issue

(Include debug logs if possible and relevant.)
- Install saltstack with official pkg https://repo.saltstack.com/osx/salt-2016.3.3-x86_64.pkg
- BEI-mzzha01-Mac:~ mzzhang$ sudo salt-call --local dockerng.images

```
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[WARNING ] /opt/salt/lib/python2.7/site-packages/salt/grains/core.py:1493: DeprecationWarning: The "osmajorrelease" will be a type of an integer.
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded config.get
[DEBUG   ] LazyLoaded cmd.run
[INFO    ] Executing command ['launchctl', 'list', 'com.apple.atrun'] in directory '/Users/mzzhang'
[DEBUG   ] SMBIOS: neither dmidecode nor smbios found!
[DEBUG   ] Could not LazyLoad dockerng.images
'dockerng' __virtual__ returned False: Docker module could not get imported
```
- BEI-mzzha01-Mac:~ mzzhang$ sudo salt-call cmd.exec_code python 'import sys; import docker; import docker.utils;print docker.version'

```
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[WARNING ] /opt/salt/lib/python2.7/site-packages/salt/grains/core.py:1493: DeprecationWarning: The "osmajorrelease" will be a type of an integer.

[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded cmd.exec_code
[INFO    ] Executing command ['python', '/tmp/tmp8BPat8'] in directory '/Users/mzzhang'
[DEBUG   ] stdout: 1.10.4
[DEBUG   ] LazyLoaded nested.output
local:
    1.10.4

```
- BEI-mzzha01-Mac:~ mzzhang$ pip freeze|grep docker

```
docker-py==1.10.4
docker-pycreds==0.2.1

```
- Install docker toolbox following https://docs.docker.com/toolbox/toolbox_install_mac/ 
- BEI-mzzha01-Mac:~ mzzhang$ docker version

```
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 17:00:50 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      linux/amd64
```
- BEI-mzzha01-Mac:~ mzzhang$ docker-machine --version

`docker-machine version 0.8.2, build e18a919`
### Versions Report

(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

BEI-mzzha01-Mac:~ mzzhang$ salt --versions-report

```
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: 1.5.0
       cherrypy: 4.0.0
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: 1.5.0
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: 1.4.4
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Aug 24 2016, 14:05:14)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: 0.6.5
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.3
            ZMQ: 4.1.2

System Versions:
           dist:
        machine: x86_64
        release: 15.6.0
         system: Darwin
        version: 10.11.6 x86_64
```

**Comment by gtmanfred** [comment]
cmd.exec_code runs using the first python binary in the $PATH variable, which is not necessarily the same python environment that salt is running in.  So even if you can import docker with exec_code, salt still might not be able to see it.

Can you make sure that the docker-py module is installed with the system python (/usr/bin/python) with `sudo salt-call cmd.run '/usr/bin/python "import sys; import docker; import docker.utils;print docker.version"'`

**Comment by SmilentRhino** [comment]
@gtmanfred 
Thank you for your quick response, I have to check this after the weekends as I left my laptop in the office.

- When use salt-call, /usr/bin/python can't import docker.
```
BEI-mzzha01-Mac:~ mzzhang$ sudo salt-call cmd.run '/usr/bin/python "import sys; import docker; import docker.utils;print docker.version"'
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[WARNING ] /opt/salt/lib/python2.7/site-packages/salt/grains/core.py:1493: DeprecationWarning: The "osmajorrelease" will be a type of an integer.

[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded cmd.run
[INFO    ] Executing command '/usr/bin/python "import sys; import docker; import docker.utils;print docker.version"' in directory '/Users/mzzhang'
[ERROR   ] Command '/usr/bin/python "import sys; import docker; import docker.utils;print docker.version"' failed with return code: 2
[ERROR   ] output: /usr/bin/python: can't open file 'import sys; import docker; import docker.utils;print docker.version': [Errno 2] No such file or directory
[DEBUG   ] LazyLoaded nested.output
local:
    /usr/bin/python: can't open file 'import sys; import docker; import docker.utils;print docker.version': [Errno 2] No such file or directory
```

- However docker-py does exists.

```
BEI-mzzha01-Mac:~ mzzhang$ /usr/bin/python
Python 2.7.10 (default, Oct 23 2015, 19:19:21)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import docker
>>> import docker.utils
>>> print docker.version
1.10.4
>>> exit()
BEI-mzzha01-Mac:~ mzzhang$ sudo /usr/bin/python
Python 2.7.10 (default, Oct 23 2015, 19:19:21)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import docker
>>> import docker.utils
>>> print docker.version
1.10.4
>>> exit()
BEI-mzzha01-Mac:~ mzzhang$ which python
/usr/bin/python
BEI-mzzha01-Mac:~ mzzhang$ whereis python
/usr/bin/python

```

- Then I notice the /opt/salt/bin, and check it.

```
BEI-mzzha01-Mac:~ mzzhang$ sudo su - root
BEI-mzzha01-Mac:~ root# echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/opt/salt/bin:/usr/local/sbin
BEI-mzzha01-Mac:bin root# pwd
/opt/salt/bin
BEI-mzzha01-Mac:bin root# ll python
-rwxr-xr-x  1 root  wheel   8.9K Aug 25 04:07 python
BEI-mzzha01-Mac:bin root# ./pip install docker-py
Collecting docker-py
  Downloading docker_py-1.10.5-py2.py3-none-any.whl (49kB)
    100% |################################| 51kB 118kB/s
Collecting docker-pycreds>=0.2.1 (from docker-py)
  Downloading docker_pycreds-0.2.1-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): backports.ssl-match-hostname>=3.5; python_version < "3.5" in /opt/salt/lib/python2.7/site-packages (from docker-py)
Requirement already satisfied (use --upgrade to upgrade): ipaddress>=1.0.16; python_version < "3.3" in /opt/salt/lib/python2.7/site-packages (from docker-py)
Requirement already satisfied (use --upgrade to upgrade): requests!=2.11.0,>=2.5.2 in /opt/salt/lib/python2.7/site-packages (from docker-py)
Requirement already satisfied (use --upgrade to upgrade): six>=1.4.0 in /opt/salt/lib/python2.7/site-packages (from docker-py)
Collecting websocket-client>=0.32.0 (from docker-py)
  Downloading websocket_client-0.37.0.tar.gz (194kB)
    100% |################################| 194kB 262kB/s
Installing collected packages: docker-pycreds, websocket-client, docker-py
  Running setup.py install for websocket-client ... done
Successfully installed docker-py-1.10.5 docker-pycreds-0.2.1 websocket-client-0.37.0
```

- Then dockerng works now.

```
BEI-mzzha01-Mac:~ root# sudo salt-call dockerng.images
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[WARNING ] /opt/salt/lib/python2.7/site-packages/salt/grains/core.py:1493: DeprecationWarning: The "osmajorrelease" will be a type of an integer.

[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Trying paths: ['/var/root/.docker/config.json', '/var/root/.dockercfg']
[DEBUG   ] No config file found
[DEBUG   ] "GET /version HTTP/1.1" 200 193
[DEBUG   ] "GET /v1.24/version HTTP/1.1" 200 193
[DEBUG   ] LazyLoaded dockerng.images
[DEBUG   ] "GET /v1.24/images/json?only_ids=0&all=0 HTTP/1.1" 200 3
[DEBUG   ] LazyLoaded nested.output
local:
    ----------
```

- I am a little overwhelmed by all these PATH thing, do you have any suggestion where I can find documents about this?

**Comment by SmilentRhino** [comment]
@gtmanfred Well, though dockerng can be imported now, I encounter another weird problem.

- It looks like json format error.
```
bash-3.2# salt-call dockerng.build /Users/mzzhang/powerdns_docker image=myimage:dev
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[WARNING ] /opt/salt/lib/python2.7/site-packages/salt/grains/core.py:1493: DeprecationWarning: The "osmajorrelease" will be a type of an integer.

[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Trying paths: ['/Users/mzzhang/.docker/config.json', '/Users/mzzhang/.dockercfg']
[DEBUG   ] No config file found
[DEBUG   ] "GET /version HTTP/1.1" 200 193
[DEBUG   ] "GET /v1.24/version HTTP/1.1" 200 193
[DEBUG   ] LazyLoaded dockerng.build
[DEBUG   ] "GET /v1.24/images/json?only_ids=0&all=1 HTTP/1.1" 200 3
[DEBUG   ] Looking for auth config
[DEBUG   ] No auth config in memory - loading from filesystem
[DEBUG   ] Trying paths: ['/Users/mzzhang/.docker/config.json', '/Users/mzzhang/.dockercfg']
[DEBUG   ] No config file found
[DEBUG   ] No auth config found
[DEBUG   ] "POST /v1.24/build?q=False&pull=False&t=myimage%3Adev&nocache=False&forcerm=False&rm=True HTTP/1.1" 200 None
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
ValueError: Extra data: line 2 column 1 - line 7 column 1 (char 56 - 411)
Traceback (most recent call last):
  File "/opt/salt/bin/salt-call", line 11, in <module>
    salt_call()
  File "/opt/salt/lib/python2.7/site-packages/salt/scripts.py", line 352, in salt_call
    client.run()
  File "/opt/salt/lib/python2.7/site-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/opt/salt/lib/python2.7/site-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/opt/salt/lib/python2.7/site-packages/salt/cli/caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "/opt/salt/lib/python2.7/site-packages/salt/modules/dockerng.py", line 3462, in build
    stream_data = [json.loads(x) for x in response]
  File "/opt/salt/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/opt/salt/lib/python2.7/json/decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 2 column 1 - line 7 column 1 (char 56 - 411)
Traceback (most recent call last):
  File "/opt/salt/bin/salt-call", line 11, in <module>
    salt_call()
  File "/opt/salt/lib/python2.7/site-packages/salt/scripts.py", line 352, in salt_call
    client.run()
  File "/opt/salt/lib/python2.7/site-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/opt/salt/lib/python2.7/site-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/opt/salt/lib/python2.7/site-packages/salt/cli/caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "/opt/salt/lib/python2.7/site-packages/salt/modules/dockerng.py", line 3462, in build
    stream_data = [json.loads(x) for x in response]
  File "/opt/salt/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/opt/salt/lib/python2.7/json/decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 2 column 1 - line 7 column 1 (char 56 - 411)
```
- The Dockerfile is simple, just for test.

```
BEI-mzzha01-Mac:powerdns_docker mzzhang$ pwd
/Users/mzzhang/powerdns_docker
BEI-mzzha01-Mac:powerdns_docker mzzhang$ less Dockerfile
BEI-mzzha01-Mac:powerdns_docker mzzhang$ cat Dockerfile
FROM ubuntu:latest
ADD test.sh /usr/local/bin/test.sh
BEI-mzzha01-Mac:powerdns_docker mzzhang$ ll
total 16
drwxr-xr-x  13 mzzhang  CORP\Domain Users   442B Oct 21 17:19 .git/
-rw-r--r--   1 mzzhang  CORP\Domain Users    54B Oct 31 14:04 Dockerfile
-rw-r--r--   1 mzzhang  CORP\Domain Users   1.0K Oct 21 17:19 LICENSE
-rw-r--r--   1 mzzhang  CORP\Domain Users     0B Oct 31 14:04 test.sh
BEI-mzzha01-Mac:powerdns_docker mzzhang$
```
- If I use docker-py directly, the build process is all OK.
```
BEI-mzzha01-Mac:~ mzzhang$ /opt/salt/bin/python
Python 2.7.12 (default, Aug 24 2016, 14:05:14)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import docker
>>> cli = docker.Client(base_url='unix://var/run/docker.sock',version="1.24")
>>> cli.images()
[]
>>> response = cli.build(path='/Users/mzzhang/powerdns_docker',tag='powerdns/powerdns:0.0.1')
>>> for i in response:
...     print i
...
{"stream":"Step 1 : FROM ubuntu:latest\n"}

{"status":"Pulling from library/ubuntu","id":"latest"}

{"status":"Pulling fs layer","progressDetail":{},"id":"6bbedd9b76a4"}
{"status":"Pulling fs layer","progressDetail":{},"id":"fc19d60a83f1"}
{"status":"Pulling fs layer","progressDetail":{},"id":"de413bb911fd"}

{"status":"Pulling fs layer","progressDetail":{},"id":"2879a7ad3144"}
{"status":"Pulling fs layer","progressDetail":{},"id":"668604fde02e"}
{"status":"Waiting","progressDetail":{},"id":"2879a7ad3144"}

{"status":"Waiting","progressDetail":{},"id":"668604fde02e"}

{"status":"Downloading","progressDetail":{"current":444,"total":444},"progress":"[==================================================\u003e]    444 B/444 B","id":"de413bb911fd"}
{"status":"Verifying Checksum","progressDetail":{},"id":"de413bb911fd"}

{"status":"Download complete","progressDetail":{},"id":"de413bb911fd"}

{"status":"Downloading","progressDetail":{"current":824,"total":824},"progress":"[==================================================\u003e]    824 B/824 B","id":"fc19d60a83f1"}

{"status":"Verifying Checksum","progressDetail":{},"id":"fc19d60a83f1"}

{"status":"Download complete","progressDetail":{},"id":"fc19d60a83f1"}

{"status":"Downloading","progressDetail":{"current":514232,"total":49866926},"progress":"[\u003e                                                  ] 514.2 kB/49.87 MB","id":"6bbedd9b76a4"}

...
...
...

{"status":"Downloading","progressDetail":{"current":49780920,"total":49866926},"progress":"[=================================================\u003e ] 49.78 MB/49.87 MB","id":"6bbedd9b76a4"}

{"status":"Verifying Checksum","progressDetail":{},"id":"6bbedd9b76a4"}

{"status":"Download complete","progressDetail":{},"id":"6bbedd9b76a4"}

{"status":"Extracting","progressDetail":{"current":524288,"total":49866926},"progress":"[\u003e                                                  ] 524.3 kB/49.87 MB","id":"6bbedd9b76a4"}

{"status":"Extracting","progressDetail":{"current":1048576,"total":49866926},"progress":"[=\u003e                                                 ] 1.049 MB/49.87 MB","id":"6bbedd9b76a4"}

{"status":"Extracting","progressDetail":{"current":1572864,"total":49866926},"progress":"[=\u003e                                                 ] 1.573 MB/49.87 MB","id":"6bbedd9b76a4"}

{"status":"Extracting","progressDetail":{"current":2097152,"total":49866926},"progress":"[==\u003e                                                ] 2.097 MB/49.87 MB","id":"6bbedd9b76a4"}

...
...
...

{"status":"Extracting","progressDetail":{"current":49283072,"total":49866926},"progress":"[=================================================\u003e ] 49.28 MB/49.87 MB","id":"6bbedd9b76a4"}

{"status":"Extracting","progressDetail":{"current":49807360,"total":49866926},"progress":"[=================================================\u003e ] 49.81 MB/49.87 MB","id":"6bbedd9b76a4"}

{"status":"Extracting","progressDetail":{"current":49866926,"total":49866926},"progress":"[==================================================\u003e] 49.87 MB/49.87 MB","id":"6bbedd9b76a4"}

{"status":"Pull complete","progressDetail":{},"id":"6bbedd9b76a4"}

{"status":"Extracting","progressDetail":{"current":824,"total":824},"progress":"[==================================================\u003e]    824 B/824 B","id":"fc19d60a83f1"}

{"status":"Extracting","progressDetail":{"current":824,"total":824},"progress":"[==================================================\u003e]    824 B/824 B","id":"fc19d60a83f1"}

{"status":"Pull complete","progressDetail":{},"id":"fc19d60a83f1"}

{"status":"Extracting","progressDetail":{"current":444,"total":444},"progress":"[==================================================\u003e]    444 B/444 B","id":"de413bb911fd"}

{"status":"Extracting","progressDetail":{"current":444,"total":444},"progress":"[==================================================\u003e]    444 B/444 B","id":"de413bb911fd"}

{"status":"Pull complete","progressDetail":{},"id":"de413bb911fd"}

{"status":"Extracting","progressDetail":{"current":678,"total":678},"progress":"[==================================================\u003e]    678 B/678 B","id":"2879a7ad3144"}

{"status":"Extracting","progressDetail":{"current":678,"total":678},"progress":"[==================================================\u003e]    678 B/678 B","id":"2879a7ad3144"}

{"status":"Pull complete","progressDetail":{},"id":"2879a7ad3144"}

{"status":"Extracting","progressDetail":{"current":160,"total":160},"progress":"[==================================================\u003e]    160 B/160 B","id":"668604fde02e"}

{"status":"Extracting","progressDetail":{"current":160,"total":160},"progress":"[==================================================\u003e]    160 B/160 B","id":"668604fde02e"}

{"status":"Pull complete","progressDetail":{},"id":"668604fde02e"}

{"status":"Digest: sha256:2d44ae143feeb36f4c898d32ed2ab2dffeb3a573d2d8928646dfc9cb7deb1315"}

{"status":"Status: Downloaded newer image for ubuntu:latest"}

{"stream":" ---\u003e f753707788c5\n"}
{"stream":"Step 2 : ADD test.sh /usr/local/bin/test.sh\n"}

{"stream":" ---\u003e f0a9b71c6759\n"}

{"stream":"Successfully built f0a9b71c6759\n"}

>>> cli.images()
[{u'Created': 1477910079, u'Labels': {}, u'VirtualSize': 127161487, u'ParentId': u'sha256:f753707788c5c100f194ce0a73058faae1a457774efcda6c1469544a114f8644', u'RepoTags': [u'powerdns/powerdns:0.0.1'], u'RepoDigests': None, u'Id': u'sha256:f0a9b71c6759170b239cc8e1b254d9c707dd82aa8792bd71a8a7f67210d8b9bc', u'Size': 127161487}, {u'Created': 1476393201, u'Labels': {}, u'VirtualSize': 127161487, u'ParentId': u'', u'RepoTags': [u'ubuntu:latest'], u'RepoDigests': [u'ubuntu@sha256:2d44ae143feeb36f4c898d32ed2ab2dffeb3a573d2d8928646dfc9cb7deb1315'], u'Id': u'sha256:f753707788c5c100f194ce0a73058faae1a457774efcda6c1469544a114f8644', u'Size': 127161487}]
>>> exit()
```

- Then I modified my /opt/salt/lib/python2.7/json/decoder.py, print the return string at line 367

```
"/opt/salt/lib/python2.7/json/decoder.py" 383L, 13698C
359     def decode(self, s, _w=WHITESPACE.match):
360         """Return the Python representation of ``s`` (a ``str`` or ``unicode``
361         instance containing a JSON document)
362
363         """
364         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
365         end = _w(s, end).end()
366         if end != len(s):
+367             print s
+368             print end
+369             print(len(s))
370             raise ValueError(errmsg("Extra data", s, end, len(s)))
371         return obj
```
- And I also modified dockerng.py to print the response.

```
+3461     print 'response starts'
+3462     for x in response:
+3463         print json.loads(x)
+3464     print "response ends"
+3465
+3466
3467     stream_data = [json.loads(x) for x in response]
```

- Here is the new output, I guess it might be something about unicode, do you have any idea how to fix it?

```
bash-3.2# salt-call dockerng.build /Users/mzzhang/powerdns_docker image=myimage:dev
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[WARNING ] /opt/salt/lib/python2.7/site-packages/salt/grains/core.py:1493: DeprecationWarning: The "osmajorrelease" will be a type of an integer.

[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Trying paths: ['/Users/mzzhang/.docker/config.json', '/Users/mzzhang/.dockercfg']
[DEBUG   ] No config file found
[DEBUG   ] "GET /version HTTP/1.1" 200 193
[DEBUG   ] "GET /v1.24/version HTTP/1.1" 200 193
[DEBUG   ] LazyLoaded dockerng.build
[DEBUG   ] "GET /v1.24/images/json?only_ids=0&all=1 HTTP/1.1" 200 583
[DEBUG   ] Looking for auth config
[DEBUG   ] No auth config in memory - loading from filesystem
[DEBUG   ] Trying paths: ['/Users/mzzhang/.docker/config.json', '/Users/mzzhang/.dockercfg']
[DEBUG   ] No config file found
[DEBUG   ] No auth config found
[DEBUG   ] "POST /v1.24/build?q=False&pull=False&t=myimage%3Adev&nocache=False&forcerm=False&rm=True HTTP/1.1" 200 None
########################################################################
################this is the print I added#######################################
response starts
{u'stream': u'Step 1 : FROM ubuntu:latest\n'} ############ print json.loads(x) in dockerng.py
{"stream":" ---\u003e f753707788c5\n"} ############## print s in decoder.py
{"stream":"Step 2 : ADD test.sh /usr/local/bin/test.sh\n"}####

40   ################## end
100  ################## len(s)
########################################################################
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
ValueError: Extra data: line 2 column 1 - line 3 column 1 (char 40 - 100)
Traceback (most recent call last):
  File "/opt/salt/bin/salt-call", line 11, in <module>
    salt_call()
  File "/opt/salt/lib/python2.7/site-packages/salt/scripts.py", line 352, in salt_call
    client.run()
  File "/opt/salt/lib/python2.7/site-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/opt/salt/lib/python2.7/site-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/opt/salt/lib/python2.7/site-packages/salt/cli/caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "/opt/salt/lib/python2.7/site-packages/salt/modules/dockerng.py", line 3463, in build
    print json.loads(x)
  File "/opt/salt/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/opt/salt/lib/python2.7/json/decoder.py", line 370, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 2 column 1 - line 3 column 1 (char 40 - 100)
Traceback (most recent call last):
  File "/opt/salt/bin/salt-call", line 11, in <module>
    salt_call()
  File "/opt/salt/lib/python2.7/site-packages/salt/scripts.py", line 352, in salt_call
    client.run()
  File "/opt/salt/lib/python2.7/site-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/opt/salt/lib/python2.7/site-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/opt/salt/lib/python2.7/site-packages/salt/cli/caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "/opt/salt/lib/python2.7/site-packages/salt/modules/dockerng.py", line 3463, in build
    print json.loads(x)
  File "/opt/salt/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/opt/salt/lib/python2.7/json/decoder.py", line 370, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 2 column 1 - line 3 column 1 (char 40 - 100)
```

- By the way, I use docker for Mac now.
```
BEI-mzzha01-Mac:powerdns_docker mzzhang$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 6
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.20-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952 GiB
Name: moby
ID: EKTV:QNFJ:VCMX:J7OC:HVKN:MCO5:F66F:SYTD:GNRA:F7EU:ASTI:RYHC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 16
 Goroutines: 27
 System Time: 2016-10-31T12:14:17.826030174Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
BEI-mzzha01-Mac:powerdns_docker mzzhang$ docker --version
Docker version 1.12.1, build 6f9534c
BEI-mzzha01-Mac:powerdns_docker mzzhang$ docker-machine --version
docker-machine version 0.8.1, build 41b3b25
BEI-mzzha01-Mac:powerdns_docker mzzhang$ docker-compose --version
docker-compose version 1.8.0, build f3628c7
BEI-mzzha01-Mac:powerdns_docker mzzhang$
```

**Comment by SmilentRhino** [comment]
@gtmanfred  Is not about the unicode, but the for loop.
```
+3461     print 'response starts'
+3462     for x in response:
+3463         print json.loads(x)
+3464     print "response ends"
```
- the first x is ok for json.loads
```
{u'stream': u'Step 1 : FROM ubuntu:latest\n'}
```

- the second x is wrong.
```
{"stream":" ---\u003e f753707788c5\n"}
{"stream":"Step 2 : ADD test.sh /usr/local/bin/test.sh\n"}
```

- This _client_wrapper is a little bit complicated for me, is there any other information I can provide to identify the cause?

```
response = _client_wrapper('build',
3447                                path=path,
3448                                tag=image,
3449                                quiet=False,
3450                                fileobj=fileobj,
3451                                rm=rm,
3452                                nocache=not cache)
```

**Comment by gtmanfred** [comment]
This could be a bug with docker for mac, does the same setup work with docker-machine like you were using earlier in this issue?

**Comment by SmilentRhino** [comment]
@gtmanfred Thank you, docker toolbox works well, there must be something wrong with docker for mac, I will check it.
