### ISSUE TITLE
salt-ssh errors out

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#37316]
### Description of Issue/Question

```
[cronos :: sjorge][~]
[.]$ salt-ssh
[ERROR   ] 'tuple' object has no attribute 'replace'
Traceback (most recent call last):
  File "/opt/local/lib/python2.7/site-packages/salt/utils/parsers.py", line 211, in parse_args
    mixin_after_parsed_func(self)
  File "/opt/local/lib/python2.7/site-packages/salt/utils/parsers.py", line 2978, in _mixin_after_parsed
    self.print_help()
  File "/opt/local/lib/python2.7/optparse.py", line 1670, in print_help
    file.write(self.format_help().encode(encoding, "replace"))
  File "/opt/local/lib/python2.7/optparse.py", line 1650, in format_help
    result.append(self.format_option_help(formatter))
  File "/opt/local/lib/python2.7/optparse.py", line 1630, in format_option_help
    result.append(OptionContainer.format_option_help(self, formatter))
  File "/opt/local/lib/python2.7/optparse.py", line 1074, in format_option_help
    result.append(formatter.format_option(option))
  File "/opt/local/lib/python2.7/optparse.py", line 316, in format_option
    help_text = self.expand_default(option)
  File "/opt/local/lib/python2.7/optparse.py", line 288, in expand_default
    return option.help.replace(self.default_tag, str(default_value))
AttributeError: 'tuple' object has no attribute 'replace'
Usage: salt-ssh [options]

salt-ssh: error: Error while processing <unbound method SaltSSHOptionParser._mixin_after_parsed>: Traceback (most recent call last):
  File "/opt/local/lib/python2.7/site-packages/salt/utils/parsers.py", line 211, in parse_args
    mixin_after_parsed_func(self)
  File "/opt/local/lib/python2.7/site-packages/salt/utils/parsers.py", line 2978, in _mixin_after_parsed
    self.print_help()
  File "/opt/local/lib/python2.7/optparse.py", line 1670, in print_help
    file.write(self.format_help().encode(encoding, "replace"))
  File "/opt/local/lib/python2.7/optparse.py", line 1650, in format_help
    result.append(self.format_option_help(formatter))
  File "/opt/local/lib/python2.7/optparse.py", line 1630, in format_option_help
    result.append(OptionContainer.format_option_help(self, formatter))
  File "/opt/local/lib/python2.7/optparse.py", line 1074, in format_option_help
    result.append(formatter.format_option(option))
  File "/opt/local/lib/python2.7/optparse.py", line 316, in format_option
    help_text = self.expand_default(option)
  File "/opt/local/lib/python2.7/optparse.py", line 288, in expand_default
    return option.help.replace(self.default_tag, str(default_value))
AttributeError: 'tuple' object has no attribute 'replace'
```
### Setup

Fresh install of 2016.11.0rc1 without any patched modules
### Steps to Reproduce Issue
1. run salt-ssh
### Versions Report

``` yaml
[!]$ salt-ssh --versions-report
Salt Version:
           Salt: 2016.11.0rc1

Dependency Versions:
           cffi: 1.4.2
       cherrypy: 3.8.0
       dateutil: 2.4.0
          gitdb: 0.6.4
      gitpython: 2.0.8
          ioflo: 1.6.5
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: 1.5.0
       M2Crypto: 0.22
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Sep 26 2016, 19:40:04)
   python-gnupg: 0.3.9
         PyYAML: 3.11
          PyZMQ: 14.4.1
           RAET: 0.6.5
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.3
            ZMQ: 4.1.3

System Versions:
           dist:
        machine: i86pc
        release: 5.11
         system: SunOS
        version: Not Installed
```

**Comment by gtmanfred** [comment]
I have replicated this issue, we will get it fixed.  Thanks for reporting.

**Comment by rallytime** [comment]
I am able to replicate this against the `v2016.11.0rc1` tag, but not against the `HEAD` of the 2016.11 branch. (The branch was recently created in preparation for the next rc tag as we move away from the name `carbon`.)

Here's the bug:
```
# salt-ssh
[ERROR   ] 'tuple' object has no attribute 'replace'
Traceback (most recent call last):
  File "/root/SaltStack/salt/salt/utils/parsers.py", line 211, in parse_args
    mixin_after_parsed_func(self)
  File "/root/SaltStack/salt/salt/utils/parsers.py", line 2978, in _mixin_after_parsed
    self.print_help()
  File "/usr/lib/python2.7/optparse.py", line 1670, in print_help
    file.write(self.format_help().encode(encoding, "replace"))
  File "/usr/lib/python2.7/optparse.py", line 1650, in format_help
    result.append(self.format_option_help(formatter))
  File "/usr/lib/python2.7/optparse.py", line 1630, in format_option_help
    result.append(OptionContainer.format_option_help(self, formatter))
  File "/usr/lib/python2.7/optparse.py", line 1074, in format_option_help
    result.append(formatter.format_option(option))
  File "/usr/lib/python2.7/optparse.py", line 316, in format_option
    help_text = self.expand_default(option)
  File "/usr/lib/python2.7/optparse.py", line 288, in expand_default
    return option.help.replace(self.default_tag, str(default_value))
AttributeError: 'tuple' object has no attribute 'replace'
Usage: salt-ssh [options]

salt-ssh: error: Error while processing <unbound method SaltSSHOptionParser._mixin_after_parsed>: Traceback (most recent call last):
  File "/root/SaltStack/salt/salt/utils/parsers.py", line 211, in parse_args
    mixin_after_parsed_func(self)
  File "/root/SaltStack/salt/salt/utils/parsers.py", line 2978, in _mixin_after_parsed
    self.print_help()
  File "/usr/lib/python2.7/optparse.py", line 1670, in print_help
    file.write(self.format_help().encode(encoding, "replace"))
  File "/usr/lib/python2.7/optparse.py", line 1650, in format_help
    result.append(self.format_option_help(formatter))
  File "/usr/lib/python2.7/optparse.py", line 1630, in format_option_help
    result.append(OptionContainer.format_option_help(self, formatter))
  File "/usr/lib/python2.7/optparse.py", line 1074, in format_option_help
    result.append(formatter.format_option(option))
  File "/usr/lib/python2.7/optparse.py", line 316, in format_option
    help_text = self.expand_default(option)
  File "/usr/lib/python2.7/optparse.py", line 288, in expand_default
    return option.help.replace(self.default_tag, str(default_value))
AttributeError: 'tuple' object has no attribute 'replace'
# salt-ssh --versions
Salt Version:
           Salt: 2016.11.0rc1

Dependency Versions:
           cffi: 1.7.0
       cherrypy: 5.0.1
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: 1.5.5
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: 0.3.8
         PyYAML: 3.10
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.6.5-x86_64-linode71
         system: Linux
        version: Ubuntu 14.04 trusty
```
And how it's fixed at the HEAD of the branch:
```
# salt-ssh
Usage: salt-ssh [options]

Options:
  --version             show program's version number and exit
  --versions-report     Show program's dependencies version number and exit.
  -h, --help            show this help message and exit
...
                        roster.
    --scan-timeout=SSH_SCAN_TIMEOUT
                        Scanning socket timeout for the scan roster.

You can find additional help about salt-ssh issuing "man salt-ssh" or on
http://docs.saltstack.com
Usage: salt-ssh [options]

salt-ssh: error: Insufficient arguments
# salt-ssh --versions
Salt Version:
           Salt: 2016.11.0rc1-73-gdde8c71

Dependency Versions:
           cffi: 1.7.0
       cherrypy: 5.0.1
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: 1.5.5
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: 0.3.8
         PyYAML: 3.10
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.6.5-x86_64-linode71
         system: Linux
        version: Ubuntu 14.04 trusty
```
I'll go ahead and close this for now. We can re-open if it pops up again. Thanks as always @sjorge!
