### ISSUE TITLE
Exceptions on FreeBSD 11 for salt 2016.11.0rc1

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#37323]
### Description of Issue/Question

```
root@:/opt/salt/lib/python2.7/site-packages/salt/modules # /opt/salt/bin/salt-call --local test.ping
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'NoneType' object has no attribute 'partition'
Traceback (most recent call last):
  File "/opt/salt/bin/salt-call", line 11, in <module>
    sys.exit(salt_call())
  File "/opt/salt/lib/python2.7/site-packages/salt/scripts.py", line 361, in salt_call
    client.run()
  File "/opt/salt/lib/python2.7/site-packages/salt/cli/call.py", line 48, in run
    caller = salt.cli.caller.Caller.factory(self.config)
  File "/opt/salt/lib/python2.7/site-packages/salt/cli/caller.py", line 79, in factory
    return ZeroMQCaller(opts, **kwargs)
  File "/opt/salt/lib/python2.7/site-packages/salt/cli/caller.py", line 274, in __init__
    super(ZeroMQCaller, self).__init__(opts)
  File "/opt/salt/lib/python2.7/site-packages/salt/cli/caller.py", line 102, in __init__
    self.minion = salt.minion.SMinion(opts)
  File "/opt/salt/lib/python2.7/site-packages/salt/minion.py", line 627, in __init__
    opts['grains'] = salt.loader.grains(opts)
  File "/opt/salt/lib/python2.7/site-packages/salt/loader.py", line 703, in grains
    ret = fun()
  File "/opt/salt/lib/python2.7/site-packages/salt/grains/core.py", line 1616, in hostname
    (grains['host'], grains['domain']) = grains['fqdn'].partition('.')[::2]
AttributeError: 'NoneType' object has no attribute 'partition'
Traceback (most recent call last):
  File "/opt/salt/bin/salt-call", line 11, in <module>
    sys.exit(salt_call())
  File "/opt/salt/lib/python2.7/site-packages/salt/scripts.py", line 361, in salt_call
    client.run()
  File "/opt/salt/lib/python2.7/site-packages/salt/cli/call.py", line 48, in run
    caller = salt.cli.caller.Caller.factory(self.config)
  File "/opt/salt/lib/python2.7/site-packages/salt/cli/caller.py", line 79, in factory
    return ZeroMQCaller(opts, **kwargs)
  File "/opt/salt/lib/python2.7/site-packages/salt/cli/caller.py", line 274, in __init__
    super(ZeroMQCaller, self).__init__(opts)
  File "/opt/salt/lib/python2.7/site-packages/salt/cli/caller.py", line 102, in __init__
    self.minion = salt.minion.SMinion(opts)
  File "/opt/salt/lib/python2.7/site-packages/salt/minion.py", line 627, in __init__
    opts['grains'] = salt.loader.grains(opts)
  File "/opt/salt/lib/python2.7/site-packages/salt/loader.py", line 703, in grains
    ret = fun()
  File "/opt/salt/lib/python2.7/site-packages/salt/grains/core.py", line 1616, in hostname
    (grains['host'], grains['domain']) = grains['fqdn'].partition('.')[::2]
AttributeError: 'NoneType' object has no attribute 'partition'
```
### Setup

Fresh freebsd 11 install.
### Steps to Reproduce Issue

Install salt 2016.11.0rc0 (I used a virtualenv of /opt/salt)
Run salt-call --local test.ping
### Versions Report

```
Salt Version:
           Salt: 2016.11.0rc1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Oct  5 2016, 13:42:31)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.5

System Versions:
           dist:
        machine: amd64
        release: 11.0-RELEASE-p1
         system: FreeBSD
        version: Not Installed
```

**Comment by sjorge** [comment]
Commenting line 1616 in grains/core.py makes every work again... with a bad grain ofcourse.

**Comment by sjorge** [comment]
Same errro on netbsd 7.0.2

```
Salt Version:
           Salt: 2016.11.0rc1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.22
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Oct  1 2016, 07:00:48)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.4.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.4

System Versions:
           dist:
        machine: amd64
        release: 7.0.2
         system: NetBSD
        version: Not Installed

```

**Comment by gtmanfred** [comment]
Thanks for reporting this, we will get it fixed.

**Comment by cro** [comment]
@sjorge I'm not able to reproduce this on a fresh FreeBSD 11 machine in our OpenNebula cluster.  What's in your /etc/hosts file?

**Comment by sjorge** [comment]
Not sure, I already recycled the vm but I did not edit it. So I assume the default the installer left there.

**Comment by cro** [comment]
Oh, so it was a from-scratch FreeBSD install?  I can check that then.

**Comment by cro** [comment]
@sjorge I'm not able to reproduce this on a fresh FreeBSD install on VMware Fusion 8.5.

I know you recycled your VM, if you would be so kind as to create another one and give us the output of the following:

```
# python2
>>> import socket
>>> socket.getfqdn()
>>>  socket.getaddrinfo(socket.gethostname(), 0, socket.AF_UNSPEC, socket.SOCK_STREAM, socket.SOL_TCP, socket.AI_CANONNAME)

Also, your /etc/hosts would be a nice thing to have, though I expect it will only contain the entries for `::1` and `127.0.0.1`.

Thanks.

**Comment by sjorge** [comment]
Exact same error on NetBSD without a hostname set. Also fix by setting a hostname.

**Comment by cro** [comment]
@sjorge Thanks for the detective work!  I will put in a PR to add a log message in the right place.
