### ISSUE TITLE
[2016.3.4] Refreshing of an s3 file server results in an exception. 

### ISSUE THREAD

**Issue by tyhunt99** [saltstack/salt#37388]
### Description of Issue/Question
I updated to 2016.3.4 and it has caused my s3 file server back end to stop being update due to the following exception. 

### Setup
Not sure if this is helpful but here is my config:
```
######    s3fs fileserver   ########
s3.keyid:  xxxxxxxxxxxxxxxxxxxxxxxxxx
s3.key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
s3.buckets:
  - petrode-artifacts
```

### Steps to Reproduce Issue
```
2016-11-01 14:17:21,492 [salt.fileserver  ][DEBUG   ][11090] Updating roots fileserver cache
2016-11-01 14:17:21,499 [salt.fileserver  ][DEBUG   ][11090] Updating s3fs fileserver cache
2016-11-01 14:17:21,500 [salt.loaded.int.fileserver.s3fs][DEBUG   ][11090] Refreshing buckets cache file
2016-11-01 14:17:21,500 [salt.daemons.masterapi][ERROR   ][11090] Exception global name '__utils__' is not defined occurred in file server update
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/salt/daemons/masterapi.py", line 270, in fileserver_update
    fileserver.update()
  File "/usr/local/lib/python2.7/dist-packages/salt/fileserver/__init__.py", line 458, in update
    self.servers[fstr]()
  File "/usr/local/lib/python2.7/dist-packages/salt/fileserver/s3fs.py", line 102, in update
    metadata = _init()
  File "/usr/local/lib/python2.7/dist-packages/salt/fileserver/s3fs.py", line 348, in _init
    metadata = _refresh_buckets_cache_file(cache_file)
  File "/usr/local/lib/python2.7/dist-packages/salt/fileserver/s3fs.py", line 456, in _refresh_buckets_cache_file
    s3_meta = __get_s3_meta(bucket_name)
  File "/usr/local/lib/python2.7/dist-packages/salt/fileserver/s3fs.py", line 410, in __get_s3_meta
    return_bin=False)
  File "/usr/local/lib/python2.7/dist-packages/salt/utils/s3.py", line 100, in query
    location = __utils__['aws.get_location']()
NameError: global name '__utils__' is not defined
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
           Salt: 2016.3.4
 
Dependency Versions:
           cffi: 1.5.0
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.23.4
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.23.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-100-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by gtmanfred** [comment]
Yup, this should get fixed to have __utils__ in the fileserver.

**Comment by cachedout** [comment]
Eh? No. We don't pack `__utils__` into `salt.utils`.

**Comment by gtmanfred** [comment]
woops, yeah i completely missunderstood.

sorry

**Comment by tyhunt99** [comment]
Just a note this will also cause file.recurse to fail because it tries to check the s3 and fails with an exception causing the state to fail with the rror of unable to find sources
