### ISSUE TITLE
Exception when running a reactor

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#37385]
### Description of Issue/Question

I am trying to use the reactors to push data in a Redis server based on certain events (e.g. when the function executed is ```transit.test```):

### Setup

Master config:

```yaml
reactor:
  - 'salt/job/*/new':
    - salt://reactor/netperf_new.sls
```

Reactor file (stored under ```reactor/netperf_new.sls```):

```jinja
{% if data['fun'] == 'transit.test' %}
set_my_key:
  redis.set_key:
    - key: my_key
    - value: my_value
    - host: localhost
    - port: 6379
{% endif %}
```

Pushing from the CLI:

```bash
$ sudo salt edge01.lad01 redis.set_key your_key your_value host=localhost port=6379
edge01.lad01:
    True
```

And the value can be found in Redis:

```bash
> get your_key
"your_value"
```

### Steps to Reproduce Issue

From the master log:

```
2016-11-01 17:09:23,349 [salt.utils.process                                      ][ERROR   ][23700] An un-handled exception from the multiprocessing process 'Reactor-9:1' was caught:
Traceback (most recent call last):
  File "/usr/local/salt/virtualenv/src/salt/salt/utils/process.py", line 651, in _run
    return self._original_run()
  File "/usr/local/salt/virtualenv/src/salt/salt/utils/reactor.py", line 243, in run
    self.call_reactions(chunks)
  File "/usr/local/salt/virtualenv/src/salt/salt/utils/reactor.py", line 200, in call_reactions
    self.wrap.run(chunk)
  File "/usr/local/salt/virtualenv/src/salt/salt/utils/reactor.py", line 271, in run
    l_fun = getattr(self, low['state'])
AttributeError: 'ReactWrap' object has no attribute 'redis'
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```bash
$ sudo salt --versions-report
Salt Version:
           Salt: 2016.11.0rc1-54-gf3e2148

Dependency Versions:
           cffi: 1.8.3
       cherrypy: 8.1.2
       dateutil: 2.2
          gitdb: 0.6.4
      gitpython: 2.0.8
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: 0.3.9
         PyYAML: 3.12
          PyZMQ: 15.4.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.4.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.4
        machine: x86_64
        release: 4.4.17-cloudflare
         system: Linux
        version: debian 8.4
```

**Comment by gtmanfred** [comment]
So, redis is only a salt module, so you would need to specify using the `local` client to run the redis module.

```
{% if data['fun'] == 'transit.test' %}
set_my_key:
  local.redis.set_key:
    - tgt: edge01.lad01
    - key: my_key
    - value: my_value
    - host: localhost
    - port: 6379
{% endif %}
```

https://docs.saltstack.com/en/latest/topics/reactor/#a-complete-example

**Comment by mirceaulinic** [comment]
Thanks @gtmanfred!

I have updated as indicated, not there's something else that does not like:

```
2016-11-01 17:53:02,986 [salt.utils.reactor                                      ][WARNING ][26193] Exception caught by reactor: cmd_async() takes at least 3 arguments (2 given)
2016-11-01 17:53:05,352 [py.warnings                                             ][WARNING ][2235] /usr/local/salt/virtualenv/src/salt/salt/client/mixins.py:251: DeprecationWarning: call with arg instead call with kwarg instead
```

Not sure if the warning is somehow related.

Any ideas what's  ```cmd_async``` exception?

**Comment by gtmanfred** [comment]
I updated the call, instead of passing them in as kwargs, they need to be passed to the kwarg or arg arguments to be passed on through the cmd_async  I think*

**Comment by mirceaulinic** [comment]
Yes, apologise @gtmanfred - missed that!

I do not see any other errors, but still it does not insert the key. Most probably I'm missing something again.

Can we leave this open till tomorrow when I will set the master log to debug and check again?

Thanks!

**Comment by gtmanfred** [comment]
Yup, no problem :)

**Comment by mirceaulinic** [comment]
Hi @gtmanfred I have set the logs at debug level:


```
2016-11-02 10:40:19,221 [salt.utils.event                                        ][DEBUG   ][28835] Sending event: tag = 20161102104019220351; data = {'_stamp': '2016-11-02T10:40:19.220577', 'minions': ['edge01.lad01']}
2016-11-02 10:40:19,221 [salt.utils.event                                        ][DEBUG   ][28835] Sending event: tag = salt/job/20161102104019220351/new; data = {'tgt_type': 'glob', 'jid': '20161102104019220351', 'tgt': 'edge01.lad01', '_stamp': '2016-11-02T10:40:19.221111', 'user': 'sudo_my_key', 'arg': [], 'fun': 'transit.test', 'minions': ['edge01.lad01']}
2016-11-02 10:40:19,222 [salt.loaded.int.returner.local_cache                    ][DEBUG   ][28835] Adding minions for job 20161102104019220351: ['edge01.lad01']
2016-11-02 10:40:19,222 [salt.master                                             ][INFO    ][28835] User sudo_my_key Published command transit.test with jid 20161102104019220351
2016-11-02 10:40:19,222 [salt.master                                             ][DEBUG   ][28835] Published command details {'tgt_type': 'glob', 'jid': '20161102104019220351', 'tgt': 'edge01.lad01', 'ret': '', 'user': 'sudo_my_key', 'arg': [], 'fun': 'transit.test'}
2016-11-02 10:40:19,222 [salt.utils.reactor                                      ][DEBUG   ][28780] Gathering reactors for tag 20161102104019220351
2016-11-02 10:40:19,223 [salt.utils.reactor                                      ][DEBUG   ][28780] Gathering reactors for tag salt/job/20161102104019220351/new
2016-11-02 10:40:19,223 [salt.utils.reactor                                      ][DEBUG   ][28780] Compiling reactions for tag salt/job/20161102104019220351/new
2016-11-02 10:40:19,224 [salt.fileclient                                         ][DEBUG   ][28780] In saltenv 'base', looking at rel_path 'reactor/netperf_new.sls' to resolve 'salt://reactor/netperf_new.sls'
2016-11-02 10:40:19,224 [salt.fileclient                                         ][DEBUG   ][28780] In saltenv 'base', ** considering ** path '/var/cache/salt/proxy-master/files/base/reactor/netperf_new.sls' to resolve 'salt://reactor/netperf_new.sls'
2016-11-02 10:40:19,224 [salt.fileclient                                         ][INFO    ][28780] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://reactor/netperf_new.sls'
2016-11-02 10:40:19,225 [salt.utils.lazy  ][DEBUG   ][6592] LazyLoaded local_cache.get_load
2016-11-02 10:40:19,225 [salt.template                                           ][DEBUG   ][28780] compile template: /var/cache/salt/proxy-master/files/base/reactor/netperf_new.sls
2016-11-02 10:40:19,225 [salt.utils.jinja                                        ][DEBUG   ][28780] Jinja search path: ['/var/cache/salt/proxy-master/files/base']
2016-11-02 10:40:19,225 [salt.loaded.int.returner.local_cache][DEBUG   ][6592] Reading minion list from /var/cache/salt/proxy-master/jobs/44/f911bb1f59ebdb241a3587bb7834f9/.minions.p
2016-11-02 10:40:19,226 [salt.client      ][DEBUG   ][6592] get_iter_returns for jid 20161102104019220351 sent to set(['edge01.lad01']) will timeout at 10:42:19.226251
2016-11-02 10:40:19,228 [salt.template                                           ][PROFILE ][28780] Time (in seconds) to render '/var/cache/salt/proxy-master/files/base/reactor/netperf_new.sls' using 'jinja' renderer: 0.0028510093689
2016-11-02 10:40:19,228 [salt.template                                           ][DEBUG   ][28780] Rendered data from file: /var/cache/salt/proxy-master/files/base/reactor/netperf_new.sls:

key_in_redis:
  local.redis.set_key:
    - tgt: edge01.lad01
    - key: my_key
    - value: my_value
    - host: localhost
    - port: 6379



2016-11-02 10:40:19,230 [salt.utils.job                                          ][INFO    ][28817] Got return from edge01.lad01 for job 20161102104019220351
2016-11-02 10:40:19,230 [salt.utils.event                                        ][DEBUG   ][28817] Sending event: tag = salt/job/20161102104019220351/ret/edge01.lad01; data = {'fun_args': [], 'jid': '20161102104019220351', 'return': True, 'retcode': 0, 'success': True, 'cmd': '_return', '_stamp': '2016-11-02T10:40:19.229984', 'fun': 'transit.test', 'id': 'edge01.lad01'}
2016-11-02 10:40:19,230 [salt.loaded.int.render.yaml                             ][DEBUG   ][28780] Results of YAML rendering:
OrderedDict([('key_in_redis', OrderedDict([('local.redis.set_key', [OrderedDict([('tgt', 'edge01.lad01')]), OrderedDict([('key', 'my_key')]), OrderedDict([('value', 'my_value')]), OrderedDict([('host', 'localhost')]), OrderedDict([('port', 6379)])])]))])
2016-11-02 10:40:19,231 [salt.template                                           ][PROFILE ][28780] Time (in seconds) to render '/var/cache/salt/proxy-master/files/base/reactor/netperf_new.sls' using 'yaml' renderer: 0.00240993499756
2016-11-02 10:40:19,232 [salt.config                                             ][DEBUG   ][28780] Reading configuration from /etc/salt/master
2016-11-02 10:40:19,237 [salt.client      ][DEBUG   ][6592] jid 20161102104019220351 return from edge01.lad01
2016-11-02 10:40:19,238 [salt.utils.lazy  ][DEBUG   ][6592] LazyLoaded nested.output
2016-11-02 10:40:19,263 [salt.config                                             ][DEBUG   ][28780] Using cached minion ID from /etc/salt/minion_id: 36netops1
2016-11-02 10:40:19,264 [salt.config                                             ][DEBUG   ][28780] Missing configuration file: /root/.saltrc
2016-11-02 10:40:19,264 [salt.utils.event                                        ][DEBUG   ][28780] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
2016-11-02 10:40:19,265 [salt.utils.event                                        ][DEBUG   ][28780] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
2016-11-02 10:40:19,273 [salt.transport.zeromq                                   ][DEBUG   ][28780] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', '36netops1_master', 'tcp://127.0.0.1:4506', 'clear')
2016-11-02 10:40:19,276 [salt.utils.event                                        ][DEBUG   ][28819] Sending event: tag = 20161102104019275978; data = {'_stamp': '2016-11-02T10:40:19.276279', 'minions': ['edge01.lad01']}
2016-11-02 10:40:19,277 [salt.utils.event                                        ][DEBUG   ][28819] Sending event: tag = salt/job/20161102104019275978/new; data = {'tgt_type': 'glob', 'jid': '20161102104019275978', 'tgt': 'edge01.lad01', '_stamp': '2016-11-02T10:40:19.276749', 'user': 'root', 'arg': [], 'fun': 'redis.set_key', 'minions': ['edge01.lad01']}
2016-11-02 10:40:19,277 [salt.loaded.int.returner.local_cache                    ][DEBUG   ][28819] Adding minions for job 20161102104019275978: ['edge01.lad01']
2016-11-02 10:40:19,277 [salt.master                                             ][INFO    ][28819] User root Published command redis.set_key with jid 20161102104019275978
2016-11-02 10:40:19,277 [salt.master                                             ][DEBUG   ][28819] Published command details {'tgt_type': 'glob', 'jid': '20161102104019275978', 'tgt': 'edge01.lad01', 'ret': '', 'user': 'root', 'arg': [], 'fun': 'redis.set_key'}
2016-11-02 10:40:19,278 [salt.client      ][DEBUG   ][6592] jid 20161102104019220351 found all minions set(['edge01.lad01'])
2016-11-02 10:40:19,280 [salt.utils.reactor                                      ][DEBUG   ][28780] Gathering reactors for tag salt/job/20161102104019220351/ret/edge01.lad01
2016-11-02 10:40:19,280 [salt.utils.reactor                                      ][DEBUG   ][28780] Gathering reactors for tag 20161102104019275978
2016-11-02 10:40:19,280 [salt.utils.reactor                                      ][DEBUG   ][28780] Gathering reactors for tag salt/job/20161102104019275978/new
2016-11-02 10:40:19,280 [salt.utils.reactor                                      ][DEBUG   ][28780] Compiling reactions for tag salt/job/20161102104019275978/new
2016-11-02 10:40:19,281 [salt.fileclient                                         ][DEBUG   ][28780] In saltenv 'base', looking at rel_path 'reactor/netperf_new.sls' to resolve 'salt://reactor/netperf_new.sls'
2016-11-02 10:40:19,281 [salt.fileclient                                         ][DEBUG   ][28780] In saltenv 'base', ** considering ** path '/var/cache/salt/proxy-master/files/base/reactor/netperf_new.sls' to resolve 'salt://reactor/netperf_new.sls'
2016-11-02 10:40:19,282 [salt.fileclient                                         ][INFO    ][28780] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://reactor/netperf_new.sls'
2016-11-02 10:40:19,282 [salt.template                                           ][DEBUG   ][28780] compile template: /var/cache/salt/proxy-master/files/base/reactor/netperf_new.sls
2016-11-02 10:40:19,282 [salt.utils.jinja                                        ][DEBUG   ][28780] Jinja search path: ['/var/cache/salt/proxy-master/files/base']
2016-11-02 10:40:19,285 [salt.template                                           ][PROFILE ][28780] Time (in seconds) to render '/var/cache/salt/proxy-master/files/base/reactor/netperf_new.sls' using 'jinja' renderer: 0.00229001045227
2016-11-02 10:40:19,285 [salt.template                                           ][DEBUG   ][28780] Rendered data from file: /var/cache/salt/proxy-master/files/base/reactor/netperf_new.sls:



2016-11-02 10:40:19,285 [salt.loaded.int.render.yaml                             ][DEBUG   ][28780] Results of YAML rendering:
{}
2016-11-02 10:40:19,285 [salt.template                                           ][PROFILE ][28780] Time (in seconds) to render '/var/cache/salt/proxy-master/files/base/reactor/netperf_new.sls' using 'yaml' renderer: 0.000247955322266
2016-11-02 10:40:19,285 [salt.utils.job                                          ][INFO    ][28793] Got return from edge01.lad01 for job 20161102104019275978
2016-11-02 10:40:19,286 [salt.utils.event                                        ][DEBUG   ][28793] Sending event: tag = salt/job/20161102104019275978/ret/edge01.lad01; data = {'fun_args': [], 'jid': '20161102104019275978', 'return': "Passed invalid arguments to redis.set_key: set_key() takes at least 2 arguments (0 given)\n\n    Set redis key value\n\n    CLI Example:\n\n    .. code-block:: bash\n\n        salt '*' redis.set_key foo bar\n    ", 'success': False, 'cmd': '_return', '_stamp': '2016-11-02T10:40:19.285577', 'fun': 'redis.set_key', 'id': 'edge01.lad01', 'out': 'nested'}
2016-11-02 10:40:19,287 [salt.utils.reactor                                      ][DEBUG   ][28780] Gathering reactors for tag salt/job/20161102104019275978/ret/edge01.lad01
```


What surprises me is the following line:

```
2016-11-02 10:40:19,277 [salt.master                                             ][DEBUG   ][28819] Published command details {'tgt_type': 'glob', 'jid': '20161102104019275978', 'tgt': 'edge01.lad01', 'ret': '', 'user': 'root', 'arg': [], 'fun': 'redis.set_key'}
```

Although the SLS file was rendered properly:

```
2016-11-02 10:40:19,230 [salt.loaded.int.render.yaml                             ][DEBUG   ][28780] Results of YAML rendering:
OrderedDict([('key_in_redis', OrderedDict([('local.redis.set_key', [OrderedDict([('tgt', 'edge01.lad01')]), OrderedDict([('key', 'my_key')]), OrderedDict([('value', 'my_value')]), OrderedDict([('host', 'localhost')]), OrderedDict([('port', 6379)])])]))])
```

Because ```arg``` is empty, the redis module will complain and will not set the key:

```
2016-11-02 10:40:19,286 [salt.utils.event                                        ][DEBUG   ][28793] Sending event: tag = salt/job/20161102104019275978/ret/edge01.lad01; data = {'fun_args': [], 'jid': '20161102104019275978', 'return': "Passed invalid arguments to redis.set_key: set_key() takes at least 2 arguments (0 given)\n\n    Set redis key value\n\n    CLI Example:\n\n    .. code-block:: bash\n\n        salt '*' redis.set_key foo bar\n    ", 'success': False, 'cmd': '_return', '_stamp': '2016-11-02T10:40:19.285577', 'fun': 'redis.set_key', 'id': 'edge01.lad01', 'out': 'nested'}
```

**Comment by gtmanfred** [comment]
It looks like your reactor file is still this.

```
key_in_redis:
  local.redis.set_key:
    - tgt: edge01.lad01
    - key: my_key
    - value: my_value
    - host: localhost
    - port: 6379
```

When it should be this

```
set_my_key:
  local.redis.set_key:
    - tgt: edge01.lad01
    - kwarg:
         key: my_key
         value: my_value
         host: localhost
         port: 6379
```

**Comment by mirceaulinic** [comment]
I'm sorry for bothering with this - it was in a git repo and the change was stashed when changing the branch, hence the change you pointed out yesterday was lost.
I confirm it works properly now!

Thanks very much!

**Comment by mirceaulinic** [comment]
Hi @gtmanfred - if you don't mind, I would have one more question regarding reactors. This time, I would need to use it with a runner, following the pattern for the execution module:

```yaml
update_redis:
  runner.redis.update_event:
    - kwarg:
        tgt: edge01.sfo04
        fun: transit.disable
        args: ['mircea']
```

The runner works fine and can be executed as:

```bash
salt-run redis.update_event edge01.sfo04 transit.disable ['mircea']
```

Looking in the logs, seems like it does not call the runner using the arguments as I would expect:

```
2016-11-03 13:55:00,006 [salt.utils.lazy  ][DEBUG   ][28870] LazyLoaded nested.output
2016-11-03 13:55:00,007 [salt.loaded.int.render.yaml                             ][DEBUG   ][15290] Results of YAML rendering:
OrderedDict([('update_redis', OrderedDict([('runner.redis.update_event', [OrderedDict([('kwarg', OrderedDict([('tgt', 'edge01.sfo04'), ('fun', 'transit.disable'), ('args', ['mircea'])]))])])]))])
2016-11-03 13:55:00,007 [salt.template                                           ][PROFILE ][15290] Time (in seconds) to render '/var/cache/salt/proxy-master/files/base/reactor/netperf.sls' using 'yaml' renderer: 0.00173783302307
2016-11-03 13:55:00,027 [salt.utils.http                                         ][DEBUG   ][15289] Response Status Code: 200
2016-11-03 13:55:00,070 [salt.utils.process                                      ][DEBUG   ][15290] ThreadPool executing func: <bound method RunnerClient.low of <salt.runner.RunnerClient object at 0x7efd26c08d10>> with args:('redis.update_event', {'name': u'update_redis', 'state': 'runner', 'kwarg': OrderedDict([('tgt', 'edge01.sfo04'), ('fun', 'transit.disable'), ('args', ['mircea'])]), '__id__': 'update_redis', '__sls__': u'/var/cache/salt/proxy-master/files/base/reactor/netperf.sls', 'order': 1, '__user__': 'Reactor'}) kwargs{}
2016-11-03 13:55:00,070 [salt.config                                             ][DEBUG   ][15290] Reading configuration from /etc/salt/master
2016-11-03 13:55:00,105 [salt.config                                             ][DEBUG   ][15290] Using cached minion ID from /etc/salt/minion_id: 36netops1
2016-11-03 13:55:00,105 [salt.config                                             ][DEBUG   ][15290] Reading configuration from /etc/salt/master
2016-11-03 13:55:00,108 [salt.client      ][DEBUG   ][28870] jid 20161103135426451548 found all minions set(['edge01.sfo04'])
2016-11-03 13:55:00,233 [salt.loaded.int.grains.core                             ][DEBUG   ][15290] Please install 'virt-what' to improve results of the 'virtual' grain.
2016-11-03 13:55:00,267 [salt.utils.event                                        ][DEBUG   ][15290] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
2016-11-03 13:55:00,267 [salt.utils.event                                        ][DEBUG   ][15290] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
2016-11-03 13:55:00,268 [salt.transport.ipc                                      ][DEBUG   ][15290] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
2016-11-03 13:55:00,270 [salt.utils.event                                        ][DEBUG   ][15290] Sending event: tag = salt/run/20161103135500267181/ret; data = {'_stamp': '2016-11-03T13:55:00.270567', 'return': 'Exception occurred in runner redis.update_event: Traceback (most recent call last):\n  File "/usr/local/salt/virtualenv/src/salt/salt/client/mixins.py", line 364, in _low\n    expected_extra_kws=CLIENT_INTERNAL_KEYWORDS\n  File "/usr/local/salt/virtualenv/src/salt/salt/utils/__init__.py", line 1054, in format_call\n    used_args_count\nSaltInvocationError: update_event takes at least 3 arguments (0 given)\n', 'success': False, 'jid': '20161103135500267181', 'user': 'Reactor', 'fun': 'runner.redis.update_event'}
```

Could you please point again what am I missing?

Thanks!

**Comment by mirceaulinic** [comment]
No, it's just me, foolished myself again...
