### ISSUE TITLE
virtualenv.manage needs access to internet

### ISSUE THREAD

**Issue by EvaSDK** [saltstack/salt#37437]
### Setup

I have salt on some nodes that have no access to internet except for HTTP through a proxy.
I upgraded the system from Ubuntu 15.10 to 16.04 LTS and it appears the new virtualenv shipped with this release wants to download setuptools, pip & co updates from internet.

According to [virtualenv changelog](https://virtualenv.pypa.io/en/stable/changes/#id10) for release 14,
they changed their codebase to do that by default. The problem is that the state and the module do not allow passing the `no-download` argument. I would have used `never-download`, even though it is deprecated but it is simply ignored as [saltstack code discards it](https://github.com/saltstack/salt/blob/develop/salt/modules/virtualenv_mod.py#L201-L210) for `virtualenv >=10`. The option might be deprecated but it is still here as of virtualenv 15.0.3 release so I am left with no option to control virtualenv properly. Admittedly, it would be simpler if upstream provided an `http-proxy` parameter like pip or if salt would provide environment variable passing to virtualenv module.

### Steps to Reproduce Issue

Issue command to a node without direct internet access:
```
# salt 'mynode' virtualenv.create /opt/myproj/venv never_download=True
/usr/lib/python2.7/dist-packages/salt/grains/core.py:1493: DeprecationWarning: The "osmajorrelease" will be a type of an integer.
mynode:
    ----------
    pid:
        25297
    retcode:
        1
    stderr:
        Traceback (most recent call last):
          File "/usr/lib/python3/dist-packages/virtualenv.py", line 2363, in <module>
            main()
          File "/usr/lib/python3/dist-packages/virtualenv.py", line 719, in main
            symlink=options.symlink)
          File "/usr/lib/python3/dist-packages/virtualenv.py", line 988, in create_environment
            download=download,
          File "/usr/lib/python3/dist-packages/virtualenv.py", line 918, in install_wheel
            call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
          File "/usr/lib/python3/dist-packages/virtualenv.py", line 812, in call_subprocess
            % (cmd_desc, proc.returncode))
        OSError: Command /opt/myproj/venv/bin/python2 - setuptools pkg_resources pip wheel failed with error code 2
    stdout:   
        New python executable in /opt/myproj/venv/bin/python2
        Not overwriting existing python script /opt/myproj/venv/bin/python (you must use /opt/myproj/venv/bin/python2)
        Installing setuptools, pkg_resources, pip, wheel...
          Complete output from command /opt/myproj/venv/bin/python2 - setuptools pkg_resources pip wheel:
          Collecting setuptools
        Exception:
        Traceback (most recent call last):
          File "/usr/share/python-wheels/pip-8.1.1-py2.py3-none-any.whl/pip/basecommand.py", line 209, in main
            status = self.run(options, args)
          File "/usr/share/python-wheels/pip-8.1.1-py2.py3-none-any.whl/pip/commands/install.py", line 328, in run
            wb.build(autobuilding=True)
          File "/usr/share/python-wheels/pip-8.1.1-py2.py3-none-any.whl/pip/wheel.py", line 748, in build
            self.requirement_set.prepare_files(self.finder)
          File "/usr/share/python-wheels/pip-8.1.1-py2.py3-none-any.whl/pip/req/req_set.py", line 360, in prepare_files
            ignore_dependencies=self.ignore_dependencies))
          File "/usr/share/python-wheels/pip-8.1.1-py2.py3-none-any.whl/pip/req/req_set.py", line 512, in _prepare_file
            finder, self.upgrade, require_hashes)
          File "/usr/share/python-wheels/pip-8.1.1-py2.py3-none-any.whl/pip/req/req_install.py", line 273, in populate_link
            self.link = finder.find_requirement(self, upgrade)
          File "/usr/share/python-wheels/pip-8.1.1-py2.py3-none-any.whl/pip/index.py", line 442, in find_requirement
            all_candidates = self.find_all_candidates(req.name)
          File "/usr/share/python-wheels/pip-8.1.1-py2.py3-none-any.whl/pip/index.py", line 400, in find_all_candidates
            for page in self._get_pages(url_locations, project_name):
          File "/usr/share/python-wheels/pip-8.1.1-py2.py3-none-any.whl/pip/index.py", line 545, in _get_pages
            page = self._get_page(location)
          File "/usr/share/python-wheels/pip-8.1.1-py2.py3-none-any.whl/pip/index.py", line 648, in _get_page
            return HTMLPage.get_page(link, session=self.session)
          File "/usr/share/python-wheels/pip-8.1.1-py2.py3-none-any.whl/pip/index.py", line 757, in get_page
            "Cache-Control": "max-age=600",
          File "/opt/myproj/venv/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/sessions.py", line 480, in get
            return self.request('GET', url, **kwargs)
          File "/usr/share/python-wheels/pip-8.1.1-py2.py3-none-any.whl/pip/download.py", line 378, in request
            return super(PipSession, self).request(method, url, *args, **kwargs)
          File "/opt/myproj/venv/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/sessions.py", line 468, in request
            resp = self.send(prep, **send_kwargs)
          File "/opt/myproj/venv/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/sessions.py", line 576, in send
            r = adapter.send(request, **kwargs)
          File "/opt/myproj/venv/share/python-wheels/CacheControl-0.11.5-py2.py3-none-any.whl/cachecontrol/adapter.py", line 46, in send
            resp = super(CacheControlAdapter, self).send(request, **kw)
          File "/opt/myproj/venv/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/adapters.py", line 376, in send
            timeout=timeout
          File "/opt/myproj/venv/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 610, in urlopen
            _stacktrace=sys.exc_info()[2])
          File "/opt/myproj/venv/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/util/retry.py", line 228, in increment
            total -= 1
        TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'
        ----------------------------------------
        ...Installing setuptools, pkg_resources, pip, wheel...done.
        Running virtualenv with interpreter /usr/bin/python2
```

### Versions Report
```
# salt-minion --versions-report
Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-45-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by EvaSDK** [comment]
FTR, I am currently working around this issue using virtualenv.ini but I would far better prefer passing this through environment variables.

**Comment by Ch3LL** [comment]
@EvaSDK I haven't used this module before but I am seeing a `env_vars` argument for the virtualenv state module: `salt.states.virtualenv_mod.managed`. So I'm wondering if we can do something similar to the executoin module. In my opinion handling this issue by being able to pass environment variables to the virtualenv is the best solution if its possible. I'll approve as a feature request.

**Comment by EvaSDK** [comment]
Yep, I expected to be able to use that but it is currently only passed to the pip module.

**Comment by EvaSDK** [comment]
Please do not let bot autoclose this.
