### ISSUE TITLE
Returning False from __virtual__ in a returner does not return expected error

### ISSUE THREAD

**Issue by Tanoti** [saltstack/salt#37444]
### Description of Issue/Question
According to the documentation on writing execution modules, you can return False and an optional error message from the `__virtual__()` function of a module which will cause Salt not to load the module and report that error to the user.

This does not work for returners. For example, the following code from postgres_local_cache.py should return the "Could not import psycopg2; postges_local_cache disabled" if the HAS_POSGRESS flag is not set:

```python
def __virtual__():
    if not HAS_POSTGRES:
        return (False, 'Could not import psycopg2; postges_local_cache disabled')
    return __virtualname__
```

However, the return of False generates a KeyError in lazy.py for the "postgres_local_cache.returner" function.

```
2016-11-03 15:55:39,687 [salt.utils.lazy                                      ][DEBUG   ][17440] Could not LazyLoad postgres_local_cache.returner
2016-11-03 15:55:39,687 [salt.minion                                          ][ERROR   ][17440] The return failed for job 20161103155539605278 'postgres_local_cache.returner'
2016-11-03 15:55:39,688 [salt.minion                                          ][ERROR   ][17440] Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 1431, in _thread_return
    returner
  File "/usr/lib/python2.6/site-packages/salt/loader.py", line 1055, in __getitem__
    func = super(LazyLoader, self).__getitem__(item)
  File "/usr/lib/python2.6/site-packages/salt/utils/lazy.py", line 93, in __getitem__
    raise KeyError(key)
KeyError: 'postgres_local_cache.returner'
```

### Setup
Can be tested using vanilla salt on a minion that does not have the psycopg2 module installed.

### Steps to Reproduce Issue
salt '<minion_id>' test.ping --return postgres_local_cache

### Versions Report
```
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, May 22 2015, 08:34:51)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: redhat 6.8 Santiago
        machine: x86_64
        release: 2.6.32-642.3.1.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.8 Santiago
```

**Comment by Ch3LL** [comment]
@Tanoti looks like i'm able to replicate this with multiple returners. Looks like we need to make sure we are handling this error properly. Thanks for bringing this to our attention.

**Comment by cachedout** [comment]
Please give #37502 a try.

**Comment by Tanoti** [comment]
@cachedout Thanks, that works a treat. Looks like we still need to add some error trapping to elasticsearch_return.py so that it catches not being able to call a function from the elasticsearch salt execution module.

```
[DEBUG   ] Could not LazyLoad elasticsearch.index_exists: 'elasticsearch' __virtual__ returned False: Cannot load module elasticsearch: elasticsearch libraries not found
[ERROR   ] The return failed for job 20161107095219005924 'elasticsearch.index_exists'
[ERROR   ] Traceback (most recent call last):
  File "/home/ec2-user/salt/salt/minion.py", line 1538, in _thread_return
    minion_instance.returners[returner_str](ret)
  File "/home/ec2-user/salt/salt/returners/elasticsearch_return.py", line 121, in returner
    _ensure_index(index)
  File "/home/ec2-user/salt/salt/returners/elasticsearch_return.py", line 71, in _ensure_index
    index_exists = __salt__['elasticsearch.index_exists'](index)
  File "/home/ec2-user/salt/salt/loader.py", line 1090, in __getitem__
    func = super(LazyLoader, self).__getitem__(item)
  File "/home/ec2-user/salt/salt/utils/lazy.py", line 101, in __getitem__
    raise KeyError(key)
KeyError: 'elasticsearch.index_exists'
```

**Comment by rallytime** [comment]
@Tanoti I've cleaned these up in #37519.

**Comment by cachedout** [comment]
Looks like we're all set here. I'm going to go ahead and close this. Thanks, all.

**Comment by MntMrc** [comment]
Hello, looks like is back in salt 3000.3
salt/returners/elasticsearch_return.py
```
def __virtual__():
    return __virtualname__
```
for example.
