### ISSUE TITLE
salt-ssh: singledispatch, backports.abc missing from thin

### ISSUE THREAD

**Issue by duk3luk3** [saltstack/salt#37468]
### Description of Issue/Question

Running salt-ssh from develop causes `ImportError: No module named singledispatch` on the minion.

```
(salt_env) luke@Max salt_31236(master|✔) % salt-ssh --user $(whoami) localhost test.ping
localhost:                                                                              
    ----------
    retcode:
        0
    stderr:
        Traceback (most recent call last):
          File "/var/tmp/.luke_186d3c_salt/salt-call", line 15, in <module>
            salt_call()
          File "/var/tmp/.luke_186d3c_salt/py2/salt/scripts.py", line 386, in salt_call
            import salt.cli.call
          File "/var/tmp/.luke_186d3c_salt/py2/salt/cli/call.py", line 9, in <module>
            import salt.cli.caller
          File "/var/tmp/.luke_186d3c_salt/py2/salt/cli/caller.py", line 18, in <module>
            import salt.loader
          File "/var/tmp/.luke_186d3c_salt/py2/salt/loader.py", line 29, in <module>
            import salt.utils.event
          File "/var/tmp/.luke_186d3c_salt/py2/salt/utils/event.py", line 72, in <module>
            import salt.payload
          File "/var/tmp/.luke_186d3c_salt/py2/salt/payload.py", line 17, in <module>
            import salt.crypt
          File "/var/tmp/.luke_186d3c_salt/py2/salt/crypt.py", line 50, in <module>
            import tornado.gen
          File "/var/tmp/.luke_186d3c_salt/py2/tornado/gen.py", line 98, in <module>
            from singledispatch import singledispatch  # backport
        ImportError: No module named singledispatch
    stdout:

```

### Setup

Development virtualenv of salt, set up like this:

```
virtualenv2 .
. ./bin/activate
pip install M2Crypto
pip install pyzmq PyYAML pycrypto msgpack-python jinja2 psutil futures tornado
pip install -e ~/git/salt # contains salt develop @61f5770
```

Salt-SSH Config: https://github.com/duk3luk3/salt-ssh-minimal/commit/3f2584198ac8344c552ae0846d525927e85748e5

### Debug log

```(salt_env) luke@Max salt_31236(master|✔) % salt-ssh --user $(whoami) localhost test.ping -l debug                  ~/scratch/salt_31236
[INFO    ] Loading Saltfile from '/home/luke/scratch/salt_31236/Saltfile'
[DEBUG   ] Reading configuration from /home/luke/scratch/salt_31236/Saltfile
[DEBUG   ] Reading configuration from /home/luke/scratch/salt_31236/etc/master
[DEBUG   ] Configuration file path: /home/luke/scratch/salt_31236/etc/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] LazyLoaded flat.targets
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] compile template: /home/luke/scratch/salt_31236/etc/roster
[DEBUG   ] Jinja search path: ['/home/luke/scratch/salt_31236/var/cache/salt/master/files/base']
[PROFILE ] Time (in seconds) to render '/home/luke/scratch/salt_31236/etc/roster' using 'jinja' renderer: 0.00278210639954
[DEBUG   ] Rendered data from file: /home/luke/scratch/salt_31236/etc/roster:
localhost:
  host: localhost

[DEBUG   ] Results of YAML rendering: 
OrderedDict([('localhost', OrderedDict([('host', 'localhost')]))])
[PROFILE ] Time (in seconds) to render '/home/luke/scratch/salt_31236/etc/roster' using 'yaml' renderer: 0.000923871994019
[DEBUG   ] Matched minions: {'localhost': {'host': 'localhost'}}
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[DEBUG   ] Updating roots fileserver cache
[DEBUG   ] LazyLoaded local_cache.prep_jid
[DEBUG   ] Adding minions for job 20161104163116685031: ['localhost']
[DEBUG   ] Could not LazyLoad test.ping: 'test.ping' is not available.
[DEBUG   ] Performing shimmed, blocking command as follows:
test.ping
[DEBUG   ] Executed SHIM command. Command logged to TRACE
[DEBUG   ] Child Forked! PID: 10414  STDOUT_FD: 9  STDERR_FD: 12
[DEBUG   ] VT: Salt-SSH SHIM Terminal Command executed. Logged to TRACE
[DEBUG   ] RETCODE localhost: 11
[DEBUG   ] SHIM retcode(11) and command: deploy
[DEBUG   ] Executing command: scp -o KbdInteractiveAuthentication=no -o PasswordAuthentication=no -o GSSAPIAuthentication=no -o ConnectTimeout=65 -o Port=22 -o IdentityFile=/home/luke/scratch/salt_31236/etc/salt/pki/master/ssh/salt-ssh.rsa -o User=luke  /home/luke/scratch/salt_31236/var/cache/salt/master/thin/thin.tgz localhost:/var/tmp/.luke_186d3c_salt/salt-thin.tgz
[DEBUG   ] Child Forked! PID: 10428  STDOUT_FD: 9  STDERR_FD: 12
[DEBUG   ] Terminal Command: /bin/sh -c scp -o KbdInteractiveAuthentication=no -o PasswordAuthentication=no -o GSSAPIAuthentication=no -o ConnectTimeout=65 -o Port=22 -o IdentityFile=/home/luke/scratch/salt_31236/etc/salt/pki/master/ssh/salt-ssh.rsa -o User=luke  /home/luke/scratch/salt_31236/var/cache/salt/master/thin/thin.tgz localhost:/var/tmp/.luke_186d3c_salt/salt-thin.tgz
[DEBUG   ] Executed SHIM command. Command logged to TRACE
[DEBUG   ] Child Forked! PID: 10435  STDOUT_FD: 9  STDERR_FD: 12
[DEBUG   ] VT: Salt-SSH SHIM Terminal Command executed. Logged to TRACE
[DEBUG   ] LazyLoaded nested.output
localhost:
    ----------
    retcode:
        0
    stderr:
        Traceback (most recent call last):
          File "/var/tmp/.luke_186d3c_salt/salt-call", line 15, in <module>
            salt_call()
          File "/var/tmp/.luke_186d3c_salt/py2/salt/scripts.py", line 386, in salt_call
            import salt.cli.call
          File "/var/tmp/.luke_186d3c_salt/py2/salt/cli/call.py", line 9, in <module>
            import salt.cli.caller
          File "/var/tmp/.luke_186d3c_salt/py2/salt/cli/caller.py", line 18, in <module>
            import salt.loader
          File "/var/tmp/.luke_186d3c_salt/py2/salt/loader.py", line 29, in <module>
            import salt.utils.event
          File "/var/tmp/.luke_186d3c_salt/py2/salt/utils/event.py", line 72, in <module>
            import salt.payload
          File "/var/tmp/.luke_186d3c_salt/py2/salt/payload.py", line 17, in <module>
            import salt.crypt
          File "/var/tmp/.luke_186d3c_salt/py2/salt/crypt.py", line 50, in <module>
            import tornado.gen
          File "/var/tmp/.luke_186d3c_salt/py2/tornado/gen.py", line 98, in <module>
            from singledispatch import singledispatch  # backport
        ImportError: No module named singledispatch
    stdout:
```

### Versions Report

```
Salt Version:
           Salt: 0.16.0-13569-g61f5770
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jun 28 2016, 08:31:05)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.5
 
System Versions:
           dist:   
        machine: x86_64
        release: 4.8.6-1-ARCH
         system: Linux
        version: Not Installed
```

**Comment by Ch3LL** [comment]
@duk3luk3 I'm having a hard time replicating this. Can you make sure that any pyc files are cleaned up? Your version number looks very old although the git commit number looks recent.

**Comment by duk3luk3** [comment]
I probably forgot to fetch tags. Here's a full transcript of me following https://docs.saltstack.com/en/latest/topics/development/hacking.html#running-a-self-contained-development-version with the same result:

```
luke@Max ~ % cd git/salt
salt(develop|✔) % ls
.                 CONDUCT.md  .editorconfig  HACKING.rst  .pylintrc     salt.egg-info  .testing.pylintrc
..                conf        .git           LICENSE      README.rst    scripts        tests
AUTHORS           COPYING     .github        MANIFEST.in  requirements  setup.py       .travis.yml
.codeclimate.yml  doc         .gitignore     pkg          salt          templates
luke@Max salt(develop|✔) % git log
luke@Max salt(develop|✔) % git pull
Already up-to-date.
luke@Max salt(develop|✔) % git fetch --all
Fetching origin
Fetching upstream
remote: Counting objects: 19902, done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 19902 (delta 8275), reused 8298 (delta 8275), pack-reused 11604
Receiving objects: 100% (19902/19902), 5.03 MiB | 2.73 MiB/s, done.
Resolving deltas: 100% (14439/14439), completed with 1136 local objects.
From github.com:saltstack/salt
 * [new branch]      0.11                         -> upstream/0.11
 * [new branch]      0.12                         -> upstream/0.12
 * [new branch]      0.13                         -> upstream/0.13
...
 * [new tag]         v2014.1.8                    -> v2014.1.8
luke@Max salt(develop|✔) % git pull upstream develop
From github.com:saltstack/salt
 * branch            develop    -> FETCH_HEAD
Updating 61f5770..ffa4631
Fast-forward
 doc/conf.py                                       |    2 +-
 doc/ref/modules/all/index.rst                     |    1 +
 doc/ref/modules/all/salt.modules.napalm_users.rst |    7 +
 doc/ref/states/all/index.rst                      |    1 +
...
 tests/unit/states/file_test.py                    |   10 +-
 tests/unit/templates/jinja_test.py                |   28 ++
 tests/unit/utils/vmware_test/cluster_test.py      |   50 ++-
 77 files changed, 6607 insertions(+), 952 deletions(-)
 create mode 100644 doc/ref/modules/all/salt.modules.napalm_users.rst
 create mode 100644 doc/ref/states/all/salt.states.netusers.rst
 create mode 100644 salt/modules/boto_kinesis.py
 create mode 100644 salt/modules/napalm_users.py
 create mode 100644 salt/pillar/postgres.py
 create mode 100644 salt/states/boto_kinesis.py
 create mode 100644 salt/states/logrotate.py
 create mode 100644 salt/states/netusers.py
 create mode 100644 salt/utils/win_dacl.py
 create mode 100644 tests/unit/states/boto_kinesis_test.py
luke@Max salt(develop|✔) % ls -al
total 196
drwxr-xr-x 13 luke luke  4096 Nov  4 16:10 .
drwxr-xr-x 17 luke luke  4096 Nov  3 22:56 ..
-rw-r--r--  1 luke luke  3898 Nov  3 23:00 AUTHORS
-rw-r--r--  1 luke luke    76 Nov  3 23:00 .codeclimate.yml
-rw-r--r--  1 luke luke  3229 Nov  3 23:00 CONDUCT.md
drwxr-xr-x  5 luke luke  4096 Nov  3 23:00 conf
-rw-r--r--  1 luke luke  7523 Nov  3 23:00 COPYING
drwxr-xr-x 14 luke luke  4096 Nov  7 22:59 doc
-rw-r--r--  1 luke luke   120 Nov  3 23:00 .editorconfig
drwxr-xr-x  8 luke luke  4096 Nov  7 23:00 .git
drwxr-xr-x  2 luke luke  4096 Nov  3 23:00 .github
-rw-r--r--  1 luke luke  1443 Nov  3 23:00 .gitignore
-rw-r--r--  1 luke luke  9549 Nov  3 23:00 HACKING.rst
-rw-r--r--  1 luke luke   626 Nov  3 23:00 LICENSE
-rw-r--r--  1 luke luke   561 Nov  3 23:00 MANIFEST.in
drwxr-xr-x 16 luke luke  4096 Nov  3 23:00 pkg
-rw-r--r--  1 luke luke 13681 Nov  3 23:00 .pylintrc
-rw-r--r--  1 luke luke  4626 Nov  3 23:00 README.rst
drwxr-xr-x  2 luke luke  4096 Nov  3 23:00 requirements
drwxr-xr-x 39 luke luke  4096 Nov  7 22:59 salt
drwxr-xr-x  2 luke luke  4096 Nov  4 16:10 salt.egg-info
drwxr-xr-x  2 luke luke  4096 Nov  3 23:00 scripts
-rwxr-xr-x  1 luke luke 49937 Nov  3 23:00 setup.py
drwxr-xr-x  7 luke luke  4096 Nov  3 23:00 templates
-rw-r--r--  1 luke luke 14982 Nov  3 23:00 .testing.pylintrc
drwxr-xr-x  7 luke luke  4096 Nov  3 23:00 tests
-rw-r--r--  1 luke luke  1608 Nov  3 23:00 .travis.yml
luke@Max salt(develop|✔) % git fetch --tags upstream
remote: Counting objects: 183, done.
remote: Total 183 (delta 111), reused 111 (delta 111), pack-reused 72
Receiving objects: 100% (183/183), 29.31 KiB | 0 bytes/s, done.
Resolving deltas: 100% (121/121), completed with 42 local objects.
From github.com:saltstack/salt
 * [new tag]         v2014.1.10  -> v2014.1.10
 * [new tag]         v2014.1.9   -> v2014.1.9
 * [new tag]         v2015.5.10  -> v2015.5.10
 * [new tag]         v2015.8.10  -> v2015.8.10
 * [new tag]         v2015.8.5   -> v2015.8.5
 * [new tag]         v2015.8.6   -> v2015.8.6
 * [new tag]         v2015.8.7   -> v2015.8.7
 * [new tag]         v2015.8.8.2 -> v2015.8.8.2
luke@Max salt(develop|✔) % cd ~/scratch/venvs/salt-ssh
luke@Max salt-ssh % ls
.  ..
luke@Max salt-ssh % virtualenv2 .
New python executable in /home/luke/scratch/venvs/salt-ssh/bin/python2
Also creating executable in /home/luke/scratch/venvs/salt-ssh/bin/python
Installing setuptools, pip, wheel...done.
luke@Max salt-ssh % . ./bin/activate
(salt-ssh) luke@Max salt-ssh % pip install M2Crypto
Collecting M2Crypto
Collecting typing (from M2Crypto)
Installing collected packages: typing, M2Crypto
Successfully installed M2Crypto-0.25.1 typing-3.5.2.2
(salt-ssh) luke@Max salt-ssh % pip install pyzmq PyYAML pycrypto msgpack-python jinja2 psutil futures tornado
...
Installing collected packages: pyzmq, PyYAML, pycrypto, msgpack-python, MarkupSafe, jinja2, psutil, futures, certifi, six, singledispatch, backports-abc, tornado
Successfully installed MarkupSafe-0.23 PyYAML-3.12 backports-abc-0.4 certifi-2016.9.26 futures-3.0.5 jinja2-2.8 msgpack-python-0.4.8 psutil-5.0.0 pycrypto-2.6.1 pyzmq-16.0.0 singledispatch-3.4.0.3 six-1.10.0 tornado-4.4.2
(salt-ssh) luke@Max salt-ssh % pip install -e ~/git/salt/
Obtaining file:///home/luke/git/salt
Requirement already satisfied: Jinja2 in ./lib/python2.7/site-packages (from salt===2016.11.0-350-gffa4631)
Requirement already satisfied: msgpack-python>0.3 in ./lib/python2.7/site-packages (from salt===2016.11.0-350-gffa4631)
Requirement already satisfied: PyYAML in ./lib/python2.7/site-packages (from salt===2016.11.0-350-gffa4631)
Requirement already satisfied: MarkupSafe in ./lib/python2.7/site-packages (from salt===2016.11.0-350-gffa4631)
Collecting requests>=1.0.0 (from salt===2016.11.0-350-gffa4631)
  Using cached requests-2.11.1-py2.py3-none-any.whl
Requirement already satisfied: tornado>=4.2.1 in ./lib/python2.7/site-packages (from salt===2016.11.0-350-gffa4631)
Requirement already satisfied: futures>=2.0 in ./lib/python2.7/site-packages (from salt===2016.11.0-350-gffa4631)
Requirement already satisfied: pycrypto>=2.6.1 in ./lib/python2.7/site-packages (from salt===2016.11.0-350-gffa4631)
Requirement already satisfied: pyzmq>=2.2.0 in ./lib/python2.7/site-packages (from salt===2016.11.0-350-gffa4631)
Requirement already satisfied: certifi in ./lib/python2.7/site-packages (from tornado>=4.2.1->salt===2016.11.0-350-gffa4631)
Requirement already satisfied: singledispatch in ./lib/python2.7/site-packages (from tornado>=4.2.1->salt===2016.11.0-350-gffa4631)
Requirement already satisfied: backports-abc>=0.4 in ./lib/python2.7/site-packages (from tornado>=4.2.1->salt===2016.11.0-350-gffa4631)
Requirement already satisfied: six in ./lib/python2.7/site-packages (from singledispatch->tornado>=4.2.1->salt===2016.11.0-350-gffa4631)
Installing collected packages: requests, salt
  Running setup.py develop for salt
Successfully installed requests-2.11.1 salt
(salt-ssh) luke@Max salt-ssh % which salt-ssh
/home/luke/scratch/venvs/salt-ssh/bin/salt-ssh
(salt-ssh) luke@Max scratch % cd salt_31236
(salt-ssh) luke@Max salt_31236(master|✚2) % ls -al
total 44
drwxr-xr-x  7 luke luke  4096 Nov  4 17:04 .
drwxr-xr-x 19 luke luke 12288 Nov  5 08:47 ..
drwxr-xr-x  3 luke luke  4096 Nov  4 16:21 etc
drwxr-xr-x  8 luke luke  4096 Nov  7 23:04 .git
drwxr-xr-x  2 luke luke  4096 Nov  4 15:24 pillar
-rw-r--r--  1 luke luke   319 Nov  4 17:04 README.md
-rw-r--r--  1 luke luke    83 Nov  4 16:36 Saltfile
drwxr-xr-x  2 luke luke  4096 Nov  4 15:23 states
drwxr-xr-x  4 luke luke  4096 Nov  4 16:20 var
(salt-ssh) luke@Max salt_31236(master|✚2) % salt-ssh --user $(whoami) localhost test.ping -l debug
[INFO    ] Loading Saltfile from '/home/luke/scratch/salt_31236/Saltfile'
[DEBUG   ] Reading configuration from /home/luke/scratch/salt_31236/Saltfile
[DEBUG   ] Reading configuration from /home/luke/scratch/salt_31236/etc/master
[DEBUG   ] Configuration file path: /home/luke/scratch/salt_31236/etc/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] LazyLoaded flat.targets
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] compile template: /home/luke/scratch/salt_31236/etc/roster
[DEBUG   ] Jinja search path: ['/home/luke/scratch/salt_31236/var/cache/salt/master/files/base']
[PROFILE ] Time (in seconds) to render '/home/luke/scratch/salt_31236/etc/roster' using 'jinja' renderer: 0.00369811058044
[DEBUG   ] Rendered data from file: /home/luke/scratch/salt_31236/etc/roster:
localhost:
  host: localhost

[DEBUG   ] Results of YAML rendering: 
OrderedDict([('localhost', OrderedDict([('host', 'localhost')]))])
[PROFILE ] Time (in seconds) to render '/home/luke/scratch/salt_31236/etc/roster' using 'yaml' renderer: 0.000988006591797
[DEBUG   ] Matched minions: {'localhost': {'host': 'localhost'}}
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[DEBUG   ] Updating roots fileserver cache
[DEBUG   ] LazyLoaded local_cache.prep_jid
[DEBUG   ] Adding minions for job 20161107230507634624: ['localhost']
[DEBUG   ] Could not LazyLoad test.ping: 'test.ping' is not available.
[DEBUG   ] Performing shimmed, blocking command as follows:
test.ping
[DEBUG   ] Executed SHIM command. Command logged to TRACE
[DEBUG   ] Child Forked! PID: 26809  STDOUT_FD: 9  STDERR_FD: 12
[DEBUG   ] VT: Salt-SSH SHIM Terminal Command executed. Logged to TRACE
[DEBUG   ] RETCODE localhost: 11
[DEBUG   ] SHIM retcode(11) and command: deploy
[DEBUG   ] Executing command: scp -o KbdInteractiveAuthentication=no -o PasswordAuthentication=no -o GSSAPIAuthentication=no -o ConnectTimeout=65 -o Port=22 -o IdentityFile=/home/luke/scratch/salt_31236/etc/salt/pki/master/ssh/salt-ssh.rsa -o User=luke  /home/luke/scratch/salt_31236/var/cache/salt/master/thin/thin.tgz localhost:/var/tmp/.luke_186d3c_salt/salt-thin.tgz
[DEBUG   ] Child Forked! PID: 26823  STDOUT_FD: 9  STDERR_FD: 12
[DEBUG   ] Terminal Command: /bin/sh -c scp -o KbdInteractiveAuthentication=no -o PasswordAuthentication=no -o GSSAPIAuthentication=no -o ConnectTimeout=65 -o Port=22 -o IdentityFile=/home/luke/scratch/salt_31236/etc/salt/pki/master/ssh/salt-ssh.rsa -o User=luke  /home/luke/scratch/salt_31236/var/cache/salt/master/thin/thin.tgz localhost:/var/tmp/.luke_186d3c_salt/salt-thin.tgz
[DEBUG   ] Executed SHIM command. Command logged to TRACE
[DEBUG   ] Child Forked! PID: 26830  STDOUT_FD: 9  STDERR_FD: 12
[DEBUG   ] VT: Salt-SSH SHIM Terminal Command executed. Logged to TRACE
[DEBUG   ] LazyLoaded nested.output
localhost:
    ----------
    retcode:
        0
    stderr:
        Traceback (most recent call last):
          File "/var/tmp/.luke_186d3c_salt/salt-call", line 15, in <module>
            salt_call()
          File "/var/tmp/.luke_186d3c_salt/py2/salt/scripts.py", line 386, in salt_call
            import salt.cli.call
          File "/var/tmp/.luke_186d3c_salt/py2/salt/cli/call.py", line 9, in <module>
            import salt.cli.caller
          File "/var/tmp/.luke_186d3c_salt/py2/salt/cli/caller.py", line 18, in <module>
            import salt.loader
          File "/var/tmp/.luke_186d3c_salt/py2/salt/loader.py", line 29, in <module>
            import salt.utils.event
          File "/var/tmp/.luke_186d3c_salt/py2/salt/utils/event.py", line 72, in <module>
            import salt.payload
          File "/var/tmp/.luke_186d3c_salt/py2/salt/payload.py", line 17, in <module>
            import salt.crypt
          File "/var/tmp/.luke_186d3c_salt/py2/salt/crypt.py", line 50, in <module>
            import tornado.gen
          File "/var/tmp/.luke_186d3c_salt/py2/tornado/gen.py", line 98, in <module>
            from singledispatch import singledispatch  # backport
        ImportError: No module named singledispatch
    stdout:
(salt-ssh) luke@Max salt_31236(master|✚2) % salt-ssh --versions-report                            ~/scratch/salt_31236
Salt Version:
           Salt: 2016.11.0-350-gffa4631
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jun 28 2016, 08:31:05)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.5
 
System Versions:
           dist:   
        machine: x86_64
        release: 4.8.6-1-ARCH
         system: Linux
        version: Not Installed

```

**Comment by Ch3LL** [comment]
@duk3luk3 are you on amazon linux by chance? it doesn't look like its spitting out your dist in the versions report

**Comment by duk3luk3** [comment]
I'm using archlinux.

**Comment by anlutro** [comment]
I'm seeing the same issue when using `salt-ssh` from an OpenSuse tumbleweed machine towards a Debian 8 box.

**Comment by Ch3LL** [comment]
@duk3luk3 thanks for the additional information. I am now able to replicate this setup using @anlutro 's setup of a opensuse pointing to a debian8 VM.

I did a git bisect because this was working in 2016.3.3 and this is the first bad commit: https://github.com/saltstack/salt/pull/37289

I also checked and its broke in carbon, but we test for this which is weird we didn't see it. So i re-set up our test case and realized what we use during testing is the bootstrap script. If i install salt with the bootstrap script it works so I'm guessing there might be a dependency that is installed alongside the bootstrap script to explain why we wouldn't have seen it. Here is how we install: `sh boostrap.sh -M -P git v2016.11.0rc2` and i know our automation suite adds dependencies as well which might explain why we didn't see it there. 

Note: I also checked the v2016.11.0rc2 packages and everything works.

Here is the dependencies that were installed on a cent7 vm with the packages:

```
============================================================================================================================================================================
 Package                                       Arch                            Version                                           Repository                            Size
============================================================================================================================================================================
Installing:
 salt-ssh                                      noarch                          2016.11.0rc2-0.el7                                salt-latest                           15 k
Updating:
 dracut                                        x86_64                          033-360.el7_2.1                                   updates                              311 k
 initscripts                                   x86_64                          9.49.30-1.el7_2.3                                 updates                              429 k
Installing for dependencies:
 hwdata                                        x86_64                          0.252-8.1.el7                                     base                                 2.1 M
 libsodium                                     x86_64                          1.0.5-1.el7                                       epel                                 144 k
 libtomcrypt                                   x86_64                          1.17-23.el7                                       epel                                 224 k
 libtommath                                    x86_64                          0.42.0-4.el7                                      epel                                  35 k
 openpgm                                       x86_64                          5.2.122-2.el7                                     epel                                 171 k
 pciutils                                      x86_64                          3.2.1-4.el7                                       base                                  90 k
 python-babel                                  noarch                          0.9.6-8.el7                                       base                                 1.4 M
 python-futures                                noarch                          3.0.3-1.el7                                       epel                                  27 k
 python-jinja2                                 noarch                          2.7.2-2.el7                                       base                                 515 k
 python-kitchen                                noarch                          1.1.1-5.el7                                       base                                 267 k
 python-markupsafe                             x86_64                          0.11-10.el7                                       base                                  25 k
 python-tornado                                x86_64                          4.2.1-1.el7                                       salt-latest                          636 k
 python-zmq                                    x86_64                          15.3.0-2.el7                                      salt-latest                          520 k
 python2-crypto                                x86_64                          2.6.1-9.el7                                       epel                                 475 k
 python2-msgpack                               x86_64                          0.4.8-1.el7                                       epel                                  83 k
 salt                                          noarch                          2016.11.0rc2-0.el7                                salt-latest                          6.9 M
 systemd-python                                x86_64                          219-19.el7_2.13                                   updates                              100 k
 yum-utils                                     noarch                          1.1.31-34.el7                                     base                                 113 k
 zeromq                                        x86_64                          4.1.4-5.el7                                       epel                                 556 k
Updating for dependencies:
 dracut-config-rescue                          x86_64                          033-360.el7_2.1                                   updates                               50 k
 dracut-network                                x86_64                          033-360.el7_2.1                                   updates                               90 k
 kmod                                          x86_64                          20-8.el7_2                                        updates                              114 k
 libgudev1                                     x86_64                          219-19.el7_2.13                                   updates                               67 k
 systemd                                       x86_64                          219-19.el7_2.13                                   updates                              5.1 M
 systemd-libs                                  x86_64                          219-19.el7_2.13                                   updates                              358 k
 systemd-sysv                                  x86_64                          219-19.el7_2.13                                   updates                               54 k
 yum                                           noarch                          3.4.3-132.el7.centos.0.1  
```

ping @cachedout any thoughts on this? Think it might be a dependency issue to explain the dependency? Or any other rideas

**Comment by edgan** [comment]
I am having the same issue with 2016.11.0rc2 and Fedora 25 Beta.

**Comment by Ch3LL** [comment]
ping @anlutro and @edgan how are you installing salt? Just want to make sure my test case was setup correct and it only effects pip installs similar to @duk3luk3

**Comment by edgan** [comment]
I took the 2016.3.4 src.rpm for el7, downloaded the 2016.11.0rc2, and rebuilt the package.

These packages are installed, and 2016.3.4 works.
python2-singledispatch-3.4.0.3-5.fc25.noarch
python2-tornado-4.4.1-1.fc25.x86_64

**Comment by anlutro** [comment]
I create a virtualenv and `pip install -e .` inside the virtualenv.

**Comment by Ch3LL** [comment]
Thanks for clarifying. we will definitely need to get this fixed up.
