### ISSUE TITLE
Salt-Cloud: If you switch profiles file with providers files, the error message is confusing

### ISSUE THREAD

**Issue by erewok** [saltstack/salt#37477]
### Setup
salt versions tried: 2016.3.3, 2016.3.1, 2015.8.2 (Not sure if still applies to dev/recent salt version)
OS: Ubuntu 16.10 and CentOS (um, don't remember offhand)

### Steps to Reproduce Issue
We have the following files:

```
/etc/salt/cloud.profiles.d/ec2.conf
/etc/salt/cloud.providers.d/ec2.conf
```

These are pretty generic: they look very similar to [documentation examples](https://docs.saltstack.com/en/latest/topics/cloud/aws.html).

If you accidentally switch them so you providers file is in `cloud.profiles.d/` and your profiles file is in `cloud.providers.d/` (I grant you that this a pretty lame thing to do and means someone was not following the docs! I was actually helping someone who had copied these files from another project without knowing what they really meant...), then you get the following error message, which I would argue is kind of confusing:

```
/usr/lib/python2.6/site-packages/salt/config/__init__.py:2491: DeprecationWarning: The term 'provider' is being deprecated in favor of 'driver'. Support for 'provider' will be removed in Salt Nitrogen. Please convert your cloud provider configuration files to use 'driver'.
[ERROR   ] 'conf_file'
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/utils/parsers.py", line 198, in parse_args
    process_option_func()
  File "/usr/lib/python2.6/site-packages/salt/utils/parsers.py", line 502, in process_config_dir
    self.config.update(self.setup_config())
  File "/usr/lib/python2.6/site-packages/salt/utils/parsers.py", line 2942, in setup_config
    return config.cloud_config(self.get_config_file_path())
  File "/usr/lib/python2.6/site-packages/salt/config/__init__.py", line 2109, in cloud_config
    providers_config)
  File "/usr/lib/python2.6/site-packages/salt/config/__init__.py", line 2272, in vm_profiles_config
    return apply_vm_profiles_config(providers, overrides, defaults)
  File "/usr/lib/python2.6/site-packages/salt/config/__init__.py", line 2291, in apply_vm_profiles_config
    'not in the proper format'.format(config)
KeyError: 'conf_file'
Usage: salt-cloud

salt-cloud: error: Error while processing <bound method SaltCloud.process_config_dir of <salt.cloud.cli.SaltCloud object at 0x2f0e050>>: Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/utils/parsers.py", line 198, in parse_args
    process_option_func()
  File "/usr/lib/python2.6/site-packages/salt/utils/parsers.py", line 502, in process_config_dir
    self.config.update(self.setup_config())
  File "/usr/lib/python2.6/site-packages/salt/utils/parsers.py", line 2942, in setup_config
    return config.cloud_config(self.get_config_file_path())
  File "/usr/lib/python2.6/site-packages/salt/config/__init__.py", line 2109, in cloud_config
    providers_config)
  File "/usr/lib/python2.6/site-packages/salt/config/__init__.py", line 2272, in vm_profiles_config
    return apply_vm_profiles_config(providers, overrides, defaults)
  File "/usr/lib/python2.6/site-packages/salt/config/__init__.py", line 2291, in apply_vm_profiles_config
    'not in the proper format'.format(config)
KeyError: 'conf_file'
```

If it's simple, easy, or whatever: I would request making this error message more informative for people who make this lame mistake.  And, actually, I wouldn't want it to throw an Exception in this case, which is really what this is about.

At the very least, an issue like this somewhere googleable may help out others who get the same error message.

I might be able to take a crack at this if I can find the time.

### Versions Report

```
Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.9 (unknown, Sep  1 2016, 23:34:36)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist:   
        machine: x86_64
        release: 4.4.23-31.54.amzn1.x86_64
         system: Linux
        version: Not Installed

```

**Comment by Ch3LL** [comment]
@pellagic-puffbomb agreed we always want to try to spit out a useful error rather then a stack trace error. We could probably try validating the config a little better and spit out error if not setup properly. Thanks
