### ISSUE TITLE
Cannot access global salt variables in py renderer

### ISSUE THREAD

**Issue by MatejBellus** [saltstack/salt#37546]
### Description of Issue/Question
`__grains__` and `__pillars__` variables are not defined, during execution of salt state using python renderer.
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
```
#!py
def find_plugin(list, name):
    for plugin in list:
        if name in plugin.values():
            return True
    return False

defaults = [
    {
        'plugin':'load',
        'warning':  __grains__['os']['cpu'],
        'critical': __grains__['os']['cpu']*1.5
    },
    {
        'plugin':'memory',
        'warning':  80,
        'critical': 90
    },
    {
        'plugin':'df',
        'warning':  80,
        'critical': 90
    }
]

def run():
    config = {}

    load pillar treshold data into tresholds
     tresholds = __pillars__['collectd']['tresholds']
     for default_plugin in defaults:
         # if one of default plugins is not in pillar data, appednt it
         if not find_plugin(tresholds, default_plugin['plugin']):
             tresholds.append(default_plugin)
    
     #pprint.pprint(tresholds)
     config['include'] = ['nagios.nsca.client', 'nagios.nsca.client']
     config['collectd tresholds'] = {
       'file.managed': [
         {'name': '/etc/collectd.d/tresholds.conf' },
         {'source': 'salt://cluster/monitoring/conf/tresholds.conf' },
         {'template': 'jinja'},
         {'context':
           {'tresholds': tresholds}
           },
         {'watch_in': [
          {'service': 'collectd service'}
          ]}
         ]}

    return config;

```

### Steps to Reproduce Issue

`salt-call state.highstate` produced follovwing:

```
...
[DEBUG   ] Could not find file from saltenv 'base', 'salt://cluster/monitoring.sls'
[DEBUG   ] In saltenv 'base', looking at rel_path 'cluster/monitoring/init.sls' to resolve 'salt://cluster/monitoring/init.sls'
[DEBUG   ] In saltenv 'base', ** considering ** path '/var/cache/salt/minion/files/base/cluster/monitoring/init.sls' to resolve 'salt://cluster/monitoring/init.sls'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://cluster/monitoring/init.sls'
[DEBUG   ] No dest file found 
[INFO    ] Fetching file from saltenv 'base', ** done ** 'cluster/monitoring/init.sls'
[DEBUG   ] compile template: /var/cache/salt/minion/files/base/cluster/monitoring/init.sls
[DEBUG   ] LazyLoaded py.render
[CRITICAL] Rendering SLS 'base:cluster.monitoring' failed: Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/utils/templates.py", line 525, in py
    data = mod.run()
  File "/var/cache/salt/minion/files/base/cluster/monitoring/init.sls", line 43, in run
    tresholds = __pillars__['collectd']['tresholds']
NameError: global name '__pillars__' is not defined

[DEBUG   ] LazyLoaded config.option
[DEBUG   ] LazyLoaded highstate.output
[TRACE   ] data = {'local': ['Rendering SLS \'base:cluster.monitoring\' failed: Traceback (most recent call last):\n  File "/usr/lib/python2.6/site-packages/salt/utils/templates.py", line 525, in py\n    data = mod.run()\n  File "/var/cache/salt/minion/files/base/cluster/monitoring/init.sls", line 43, in run\n    tresholds = __pillars__[\'collectd\'][\'tresholds\']\nNameError: global name \'__pillars__\' is not defined\n']}
local:
    Data failed to compile:
----------
    Rendering SLS 'base:cluster.monitoring' failed: Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/utils/templates.py", line 525, in py
    data = mod.run()
  File "/var/cache/salt/minion/files/base/cluster/monitoring/init.sls", line 43, in run
    tresholds = __pillars__['collectd']['tresholds']
NameError: global name '__pillars__' is not defined

```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
salt-call 2016.3.4 (Boron)
```
[root@salt-master vagrant]# salt --versions-report
Salt Version:
           Salt: 2016.3.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: 2.0.0
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32-573.el6.x86_64
         system: Linux
        version: CentOS 6.7 Final

```

**Comment by gtmanfred** [comment]
I have confirmed that this is an issue.

We will get this fixed.

Thanks
Daniel

**Comment by gtmanfred** [comment]
So, after discussing this, You can't reference the dunders at the module level, they have to be inside a function, because the dunders are not added until after the whole file is loaded.

**Comment by MatejBellus** [comment]
Great! I can confirm its working now ;) 

Thanks
