### ISSUE TITLE
Dockerng build function should verify the response from docker-py

### ISSUE THREAD

**Issue by SmilentRhino** [saltstack/salt#37570]
### Description of Issue/Question
Dockerng build function assume response from docker-py contains one json object in each chunk, which  is not necessary. If multi status lines in one single chunk, dockerng will throw error as json.loads() fails.
THIS IS THE LINE: stream_data = [json.loads(x) for x in response]
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
- Install Docker for mac follow the official instruction. [Official dock for mac ](https://docs.docker.com/docker-for-mac/)
- Use salt-call to call dockerng.build, json.loads(x) failed and I got extra data error.
```
bash-3.2# salt-call --local dockerng.build /Users/mzzhang/powerdns_docker image=myimage:dev
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[WARNING ] /opt/salt/lib/python2.7/site-packages/salt/grains/core.py:1493: DeprecationWarning: The "osmajorrelease" will be a type of an integer.

[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Trying paths: ['/Users/mzzhang/.docker/config.json', '/Users/mzzhang/.dockercfg']
[DEBUG   ] No config file found
[DEBUG   ] "GET /version HTTP/1.1" 200 193
[DEBUG   ] "GET /v1.24/version HTTP/1.1" 200 193
[DEBUG   ] LazyLoaded dockerng.build
[DEBUG   ] "GET /v1.24/images/json?only_ids=0&all=1 HTTP/1.1" 200 583
[DEBUG   ] Looking for auth config
[DEBUG   ] No auth config in memory - loading from filesystem
[DEBUG   ] Trying paths: ['/Users/mzzhang/.docker/config.json', '/Users/mzzhang/.dockercfg']
[DEBUG   ] No config file found
[DEBUG   ] No auth config found
[DEBUG   ] "POST /v1.24/build?q=False&pull=False&t=myimage%3Adev&nocache=False&forcerm=False&rm=True HTTP/1.1" 200 None
########################################################################
################this is the print I added#######################################
response starts
{u'stream': u'Step 1 : FROM ubuntu:latest\n'} ############ print json.loads(x) in dockerng.py
{"stream":" ---\u003e f753707788c5\n"} ############## print s in decoder.py
{"stream":"Step 2 : ADD test.sh /usr/local/bin/test.sh\n"}####

40   ################## end
100  ################## len(s)
########################################################################
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
ValueError: Extra data: line 2 column 1 - line 3 column 1 (char 40 - 100)
Traceback (most recent call last):
  File "/opt/salt/bin/salt-call", line 11, in <module>
    salt_call()
  File "/opt/salt/lib/python2.7/site-packages/salt/scripts.py", line 352, in salt_call
    client.run()
  File "/opt/salt/lib/python2.7/site-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/opt/salt/lib/python2.7/site-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/opt/salt/lib/python2.7/site-packages/salt/cli/caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "/opt/salt/lib/python2.7/site-packages/salt/modules/dockerng.py", line 3463, in build
    print json.loads(x)
  File "/opt/salt/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/opt/salt/lib/python2.7/json/decoder.py", line 370, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 2 column 1 - line 3 column 1 (char 40 - 100)
Traceback (most recent call last):
  File "/opt/salt/bin/salt-call", line 11, in <module>
    salt_call()
  File "/opt/salt/lib/python2.7/site-packages/salt/scripts.py", line 352, in salt_call
    client.run()
  File "/opt/salt/lib/python2.7/site-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/opt/salt/lib/python2.7/site-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/opt/salt/lib/python2.7/site-packages/salt/cli/caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "/opt/salt/lib/python2.7/site-packages/salt/modules/dockerng.py", line 3463, in build
    print json.loads(x)
  File "/opt/salt/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/opt/salt/lib/python2.7/json/decoder.py", line 370, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 2 column 1 - line 3 column 1 (char 40 - 100)
```

- This is where the error occurs at line 3637 in [dockerng.py](https://github.com/saltstack/salt/blob/develop/salt/modules/dockerng.py) 
The line number is not in consistent with the error info as I refer to the dockerng.py in dev branch, and also I made some change in my dockerng.py for debug. But actually they are at the same place.
```
    response = _client_wrapper('build',
                               path=path,
                               tag=image,
                               quiet=False,
                               fileobj=fileobj,
                               rm=rm,
                               nocache=not cache,
                               dockerfile=dockerfile)
    ret = {'Time_Elapsed': time.time() - time_started}
    _clear_context()

    if not response:
        raise CommandExecutionError(
            'Build failed for {0}, no response returned from Docker API'
            .format(image)
        )

    stream_data = [json.loads(x) for x in response]
    errors = []
```

- Actually the build response is a generator returned from docker.build() at line 112 in [docker-py.build](https://github.com/docker/docker-py/blob/master/docker/api/build.py)
```

        response = self._post(
            u,
            data=context,
            params=params,
            headers=headers,
            stream=stream,
            timeout=timeout,
        )

        if context is not None and not custom_context:
            context.close()

        if stream:
            return self._stream_helper(response, decode=decode)
        else:
            output = self._result(response)
            srch = r'Successfully built ([0-9a-f]+)'
            match = re.search(srch, output)
            if not match:
                return None, output
            return match.group(1), output
```

- Docker api response for build is streamed, so it calls _stream_helper indeed, and each value in the generator is one single chunk at line 266 in [docker-py.client](https://github.com/docker/docker-py/blob/master/docker/client.py)
```
    def _stream_helper(self, response, decode=False):
        """Generator for data coming from a chunked-encoded HTTP response."""
        if response.raw._fp.chunked:
            reader = response.raw
            while not reader.closed:
                # this read call will block until we get a chunk
                data = reader.read(1)
                if not data:
                    break
                if reader._fp.chunk_left:
                    data += reader.read(reader._fp.chunk_left)
                if decode:
                    if six.PY3:
                        data = data.decode('utf-8')
                    # remove the trailing newline
                    data = data.strip()
                    # split the data at any newlines
                    data_list = data.split("\r\n")
                    # load and yield each line seperately
                    for data in data_list:
                        data = json.loads(data)
                        yield data
                else:
                    yield data
```
- However, docker api documentation doesn't specify what should be contained in each chunk, it could be one status line, or multi lines, or even partial lines.

- Please refer to the issue I opened at docker for mac project if you want to know what docker api response chunks really return in this case and the detailed dockerfile, [issue906](https://github.com/docker/for-mac/issues/906)
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
BEI-mzzha01-Mac:~ mzzhang$ salt --versions-report
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: 1.5.0
       cherrypy: 4.0.0
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: 1.5.0
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: 1.4.4
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Aug 24 2016, 14:05:14)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: 0.6.5
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.3
            ZMQ: 4.1.2

System Versions:
           dist:
        machine: x86_64
        release: 15.6.0
         system: Darwin
        version: 10.11.6 x86_64

BEI-mzzha01-Mac:~ mzzhang$
```

**Comment by cachedout** [comment]
Any thoughts here, @ticosax?

**Comment by ticosax** [comment]
Sorry, @cachedout I'm not using `dockerng.build` myself. I may pass on this one.

**Comment by gtmanfred** [comment]
@SmilentRhino can you check this patch against Docker For Mac and see if it resolves the problem?

https://github.com/gtmanfred/salt/commit/8e9928a41ed52b76cfb34c5b00c50c4b739a4eb4

**Comment by gtmanfred** [comment]
I have created a pr with that commit here https://github.com/saltstack/salt/pull/37608

**Comment by SmilentRhino** [comment]
@gtmanfred  Thank you for the patch, it works.
But just as djs55 said, I think it is still not defensive enough as docker api might return part of a line in one chunk, though not likely, such as:

>  {"status":"Pulling fs lay"

 in one chunk,

>  er","progressDetail":{},"id":"6bbedd9b76a4"}\r\n
> {"status":"Pulling fs layer","progressDetail":{},"id":"fc19d60a83f1"}\r\n"
> {"status":"Pulling fs layer","progressDetail":{},"id":"fc19d60a83f1"}\r\n"

in another chunk.

Before they really specify what should be in one chunk, I guess a better way is receive the whole response first, then split lines.

```
    stream_data = ''
    for chunk in response:
        stream_data += chunk
    stream_data = [json.loads(x) for x in stream_data.splitlines()]
```
