### ISSUE TITLE
Salt Minion doesn't exit with error code upon key failure 

### ISSUE THREAD

**Issue by The-Loeki** [saltstack/salt#37603]
### Description of Issue/Question

Following https://docs.saltstack.com/en/latest/topics/tutorials/multimaster_pki.html one encounters a problem; a minion *with* the setting will crash out when connecting to a master *without* the setting & vice versa.

While I agree that getting an invalid key is a serious issue indeed this makes switching to this setup a rather difficult proposition.

So I figured I'd modify the service definitions to always restart the minion on error, giving time to propagate the change to the minions and adapt the master later on. 

*However* it turns out that the critical crash actually exits 0, so we can't restart `on-failure` 

### Steps to Reproduce Issue
* Set a master without `master_sign_pubkey: True`
* Set a minion with `verify_master_pubkey_sign: True`

Start salt-minion:
```shell
[root@salt01 ~]# salt-minion
[ERROR   ] The master did not send its public-key signature, but signature verification is enabled on the minion. Either disable signature verification on the minion or enable signing the public on the master!
[CRITICAL] The Salt Master server's public key did not authenticate!
The master may need to be updated if it is a version of Salt lower than 2016.3.0-n/a-fdd13b4, or
If you are confident that you are connecting to a valid Salt Master, then remove the master public key and restart the Salt Minion.
The master public key can be found at:
/etc/salt/pki/minion/minion_master.pub
[WARNING ] Stopping the Salt Minion
[ERROR   ] Invalid master key
The salt minion is shutdown.Invalid master key
[root@salt01 ~]# echo $?
0
```

### Versions Report
```
[root@salt01 ~]# salt --versions-report
Salt Version:
           Salt: 2016.3.0-n/a-fdd13b4
 
Dependency Versions:
           cffi: 1.8.3
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: 1.5.0
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.16
       pycrypto: 2.6.1
         pygit2: 0.24.1
         Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.5
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.36.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

**Comment by gtmanfred** [comment]
Hello,

Thanks for reporting this!

We do have a problem with some of our processes not exiting with the correct return codes.  If you could take a look and submit a pull request, we would greatly appreciate it, otherwise I am going to tag this with our core team to take a look.

Thanks,
Daniel

**Comment by fevej** [comment]
any updates ?

**Comment by aarnaud** [comment]
Hi @gtmanfred this issues still exist ?
I have the same issue with multimaster pki.

```
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/minion', u'salt-master', u'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://127.0.0.1:4506
[DEBUG   ] Trying to connect to: tcp://127.0.0.1:4506
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
[ERROR   ] There was an error while verifying the masters public-key signature
[ERROR   ] Exception in callback <functools.partial object at 0x7f68ac075ba8>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 758, in _run_callback
    ret = callback()
  File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 779, in _discard_future_result
    future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.7/dist-packages/salt/crypt.py", line 602, in _authenticate
    creds = yield self.sign_in(channel=channel)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/usr/lib/python2.7/dist-packages/salt/crypt.py", line 734, in sign_in
    auth['aes'] = self.verify_master(payload, master_pub='token' in sign_in_payload)
  File "/usr/lib/python2.7/dist-packages/salt/crypt.py", line 1091, in verify_master
    if self.verify_signing_master(payload):
  File "/usr/lib/python2.7/dist-packages/salt/crypt.py", line 956, in verify_signing_master
    raise Exception(sign_exc)
Exception: Incorrect padding
```
