### ISSUE TITLE
[git 2016.3] Refreshing of an s3 file server results in an exception

### ISSUE THREAD

**Issue by TronPaul** [saltstack/salt#37628]
### Description of Issue/Question
Installed git branch 2016.3 via bootstrap after running into #37388. Tried to use s3fs as a fileserver backend, but am getting an error when trying to pull files from it. Also tried this on develop and got the same error.

### Setup
```
fileserver_backend:
- git
- s3fs
s3.buckets:
  base:
  - salt-teamunpro
```

### Steps to Reproduce Issue
```
sudo salt-run fileserver.update
Exception occurred in runner fileserver.update: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 397, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/runners/fileserver.py", line 310, in update
    fileserver.update(back=backend)
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/__init__.py", line 468, in update
    self.servers[fstr]()
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/s3fs.py", line 102, in update
    metadata = _init()
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/s3fs.py", line 352, in _init
    metadata = _refresh_buckets_cache_file(cache_file)
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/s3fs.py", line 421, in _refresh_buckets_cache_file
    s3_meta = __get_s3_meta(bucket_name)
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/s3fs.py", line 414, in __get_s3_meta
    return_bin=False)
  File "/usr/lib/python2.7/dist-packages/salt/utils/s3.py", line 101, in query
    location = salt.utils.aws.get_location()
  File "/usr/lib/python2.7/dist-packages/salt/utils/aws.py", line 580, in get_location
    opts = __opts__
NameError: global name '__opts__' is not defined
```

### Versions Report
```
Salt Version:
           Salt: 2016.3.0-n/a-b14faf1
 
Dependency Versions:
           cffi: 1.8.3
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.2
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: 0.24.2
         Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-45-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by TronPaul** [comment]
Modifying `aws.py` so that `__opt__` is `{}` (like other methods) causes an attribute error as provider is None.

**Comment by gtmanfred** [comment]
Thanks for submitting the pull request for this! I am going to close this issue.
