### ISSUE TITLE
remove job_cache jid on salt-master

### ISSUE THREAD

**Issue by himadrisingh001** [saltstack/salt#37634]
### Description of Issue/Question
We are running iNodes on the salt-master due to residual jid in the `/var/cache/salt/master/jobs`

### Setup
We have 2500+ minions running on EC2 which run salt.highstate every 4 hours + many other jobs. We also have autoscaling enabled so actual jobs run could be a lot higher.
```
$ df -iH
Filesystem     Inodes IUsed IFree IUse% Mounted on
/dev/xvda        1.4M  1.1M  257k   81% /
```
```
user: salt
auto_accept: True
worker_threads: 64
job_cache: False
hash_type: sha256
open_mode: True
keep_jobs: 1

state_aggregate:
  - pkg
```

### Steps to Reproduce Issue
```
$ ls -lrt /var/cache/salt/master/jobs/00/3c075d9c2d8312a51e07a2607a66869b3d0c363e780482d558c39318845c26
total 4
-rw-r--r-- 1 salt salt 20 Nov  9 14:50 jid
$ date
Fri Nov 11 07:42:14 UTC 2016
```

### Versions Report
```
$ salt --versions-report
Salt Version:
           Salt: 2015.8.12

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: 0.1.3
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-63-generic
         system: Ubuntu 14.04 trusty
```

**Comment by himadrisingh001** [comment]
```
$ /var/cache/salt/master/jobs# stat 00
  File: ‘00’
  Size: 139264    	Blocks: 280        IO Block: 4096   directory
Device: ca00h/51712d	Inode: 531678      Links: 1167
Access: (0755/drwxr-xr-x)  Uid: (  998/    salt)   Gid: (  998/    salt)
Access: 2016-11-11 07:54:30.826819280 +0000
Modify: 2016-11-11 07:54:23.762728473 +0000
Change: 2016-11-11 07:54:23.762728473 +0000
 Birth: -

$ /var/cache/salt/master/jobs# stat 00/fdf36e353b3a4dd232ebd5adddc57a0e297c3eb9255f5e11ef12ecdcab71cd/
  File: ‘00/fdf36e353b3a4dd232ebd5adddc57a0e297c3eb9255f5e11ef12ecdcab71cd/’
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: ca00h/51712d	Inode: 592717      Links: 2
Access: (0755/drwxr-xr-x)  Uid: (  998/    salt)   Gid: (  998/    salt)
Access: 2016-11-10 14:50:31.306090889 +0000
Modify: 2016-11-09 12:01:22.196551447 +0000
Change: 2016-11-09 12:01:22.196551447 +0000
 Birth: -

$ /var/cache/salt/master/jobs# stat 00/fdf36e353b3a4dd232ebd5adddc57a0e297c3eb9255f5e11ef12ecdcab71cd/jid
  File: ‘00/fdf36e353b3a4dd232ebd5adddc57a0e297c3eb9255f5e11ef12ecdcab71cd/jid’
  Size: 20        	Blocks: 8          IO Block: 4096   regular file
Device: ca00h/51712d	Inode: 592726      Links: 1
Access: (0644/-rw-r--r--)  Uid: (  998/    salt)   Gid: (  998/    salt)
Access: 2016-11-09 12:01:22.196551447 +0000
Modify: 2016-11-09 12:01:22.196551447 +0000
Change: 2016-11-09 12:01:22.196551447 +0000
 Birth: -

$ /var/cache/salt/master/jobs# date
Fri Nov 11 07:59:15 UTC 2016
```

**Comment by gtmanfred** [comment]
By default the job cache keeps jobs for 24 hours.

You can lower that by setting `keep_jobs: 4` and set it to 4 hours.

https://docs.saltstack.com/en/latest/topics/jobs/job_cache.html

**Comment by gtmanfred** [comment]
my appologies, i missed your setup.

**Comment by gtmanfred** [comment]
Have you looked into using one of the external job caches?  One that is a database so that you don't have to store the jid files on the master, and instead could be entries in a database and also not use the inodes?

**Comment by himadrisingh001** [comment]
I'm more inclined towards master job cache but not sure about the performance impact due to this. Do we have any sense what could be the issues related to external job cache. 

https://docs.saltstack.com/en/latest/topics/jobs/external_cache.html#external-master-cache

**Comment by gtmanfred** [comment]
Yeah, sorry i meant master_job_cache.

That would replace the use of the different files in /var/cache/salt/master/jobs

as for performance impact, i don't think it would have all that much impact, especially if you used something simple like the [sqlite3 returner](https://docs.saltstack.com/en/latest/ref/returners/all/salt.returners.sqlite3_return.html) which would be on the master as well.

**Comment by himadrisingh001** [comment]
Have setup sqlite3 db using https://docs.saltstack.com/en/latest/ref/returners/all/salt.returners.sqlite3_return.html

```
sqlite3.database: /var/cache/salt/master/job_cache/salt.db
sqlite3.timeout: 5.0
master_job_cache: sqlite3
```

But it still keeps on timing out
```
$ salt '*' test.ping
Salt request timed out. The master is not responding. If this error persists after verifying the master is up, worker_threads may need to be increased.
```

**Comment by himadrisingh001** [comment]
nevermind, somehow its not able to open db, will look into this.

```
22:36:05,193 [salt.master                                          ][ERROR   ] Error in function _return:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 1429, in run_func
    ret = getattr(self, func)(load)
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 1242, in _return
    self.opts, load, event=self.event, mminion=self.mminion)
  File "/usr/lib/python2.7/dist-packages/salt/utils/job.py", line 49, in store_job
    mminion.returners[saveload_fstr](load['jid'], load)
  File "/usr/lib/python2.7/dist-packages/salt/returners/sqlite3_return.py", line 184, in save_load
    'load': json.dumps(load)})
OperationalError: unable to open database file
```

**Comment by himadrisingh001** [comment]
okay, had bad permission on the db directory. 

Seems to be working fine now. Thanks for the workaround.

**Comment by gtmanfred** [comment]
Does this solve your problem or is there something else that you were requesting for this issue?

Thanks
Daniel

**Comment by himadrisingh001** [comment]
```
17:50:49,726 [salt.master                                          ][ERROR   ] Error in function _return:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 1429, in run_func
    ret = getattr(self, func)(load)
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 1242, in _return
    self.opts, load, event=self.event, mminion=self.mminion)
  File "/usr/lib/python2.7/dist-packages/salt/utils/job.py", line 49, in store_job
    mminion.returners[saveload_fstr](load['jid'], load)
  File "/usr/lib/python2.7/dist-packages/salt/returners/sqlite3_return.py", line 184, in save_load
    'load': json.dumps(load)})
IntegrityError: UNIQUE constraint failed: jids.jid
``` 

Could this be a problem.

**Comment by himadrisingh001** [comment]
and it also throws 

```
12:51:46,054 [salt.master                                          ][ERROR   ] Error in function _return:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 1429, in run_func
    ret = getattr(self, func)(load)
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 1242, in _return
    self.opts, load, event=self.event, mminion=self.mminion)
  File "/usr/lib/python2.7/dist-packages/salt/utils/job.py", line 49, in store_job
    mminion.returners[saveload_fstr](load['jid'], load)
  File "/usr/lib/python2.7/dist-packages/salt/returners/sqlite3_return.py", line 184, in save_load
    'load': json.dumps(load)})
OperationalError: database is locked
```

and around the same time minions get timeout from the salt-master.

**Comment by gtmanfred** [comment]
Ahh, that could do it, sqlite3 has a limitation in that only one writer can write at a time, so you may need to use something like mysql or postgres to be able to have mulitple parallel writers.

**Comment by himadrisingh001** [comment]
Does job cache cleaner clean the job_ids or will it be ever growing database?

**Comment by gtmanfred** [comment]
The master calls `clean_old_jobs` on each event loop to clean out old jobs in the job cache.

https://github.com/saltstack/salt/blob/develop/salt/returners/mysql.py#L560

**Comment by himadrisingh001** [comment]
We have switched to mysql job_cache. We can close this issue for now. 

We should have mysql as recommended job_cache for larger production deployment.

**Comment by gtmanfred** [comment]
Awesome! Thanks

Daniel
