### ISSUE TITLE
Ordinal not in range

### ISSUE THREAD

**Issue by DrunkenAngel** [saltstack/salt#37650]
When attempting to apply a jinja template get an ordinal not in range error. 

```
Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 178, in render_tmpl
                  output = render_str(tmplstr, context, tmplpath)
                File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 407, in render_jinja_tmpl
                  log.debug("TmplStr: {0}".format(tmplstr))
              UnicodeEncodeError: 'ascii' codec can't encode character u'\u201c' in position 1194: ordinal not in range(128)
```
heres an example of the config 
https://gist.github.com/DrunkenAngel/1e9be164016bf4865423a3b31d4b613c

Specifically jinja seems not to like this:
```
{% set image_installs = salt['mine.get_docker'](interfaces="eth0", cidr="%s/32"|format(salt['grains.get']('ip4_interfaces:eth0:0'))) %} 
```

master logs show nothing , salt call with verbosity full shows whats above

Master salt-versions 

#Salt Version:
```
           Salt: 2015.8.10

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.7.0
         Python: 2.7.9 (default, Dec 21 2014, 11:02:59) [GCC]
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.4
           cffi: 1.1.0
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: SuSE 12 x86_64
        machine: x86_64
        release: 3.12.62-60.62-default
         system: SUSE Linux Enterprise Server  12 x86_64
 
```

**Comment by Ch3LL** [comment]
@DrunkenAngel looks like cidr needs to be cidrs. If you change that does it work? It worked in my example

**Comment by DrunkenAngel** [comment]
Sorry for taking so long to reply ( thought I did) I will close thanks for your help
