### ISSUE TITLE
Proxy Minion failed to start: version 2015.8.8+ds-1

### ISSUE THREAD

**Issue by schreyack** [saltstack/salt#37744]
### Description of Issue/Question
Running: /usr/bin/salt-proxy --proxyid=test01.test -l debug

produces:
[ERROR   ] Proxy Minion failed to start: 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 192, in proxy_minion_process
    proxyminion.start()
  File "/usr/lib/python2.7/dist-packages/salt/cli/daemons.py", line 478, in start
    self.minion.tune_in()
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1695, in tune_in
    self.sync_connect_master()
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 756, in sync_connect_master
    raise six.reraise(*future_exception)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 764, in connect_master
    yield self._post_master_init(master)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 879, in run
    yielded = self.gen.send(value)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 2626, in _post_master_init
    proxy_init_fn(self.opts)
  File "/var/cache/salt/proxy/extmods/proxy/napalm.py", line 120, in init
    except napalm.exceptions.ConnectionException as error:
AttributeError: 'module' object has no attribute 'exceptions'

### Setup
/etc/salt/pillar/top.sls 
base:
 test01.test:
    - test01_test

/etc/salt/pillar/test01_test.sls 
proxy:
  proxytype: napalm
  driver: nxos
  host: 10.10.10.10 
  username: xxxx
  password: xxxx

/etc/salt/proxy
master: localhost
pki_dir: /etc/salt/pki/proxy
cachedir: /var/cache/salt/proxy
multiprocessing: False
add_proxymodule_to_opts: False
mine_enabled: True

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
Salt Version:
           Salt: 2015.8.8
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-47-generic
         system: Ubuntu 16.04 xenial

**Comment by schreyack** [comment]
found this to be an issue with napalm version.  problem solved.
