### ISSUE TITLE
Relative import in custom modules

### ISSUE THREAD

**Issue by felskrone** [saltstack/salt#37807]
In earlier Versions of salt it was possible to do relative imports in custom modules:

test_module.py
```bash
def save_config():
    from submod import save_a
    save_a()
````

submod.py
````
import logging
log = logging.getLogger(__name__)
def save_a():
    log.info('save_a() called')
````

We used this quite a lot for our bigger modules (1000+ lines) do separate them logically. For example we have a server_mng.py which basically has no code but only entry-points which import "submodules" that manage parts of the system (maildirs, customers, exim-configs, etc.)

````bash
########################################################################
# Server management functions for creating, deleting parts of a system #
########################################################################
def maildir_make(**kwargs):
    from lib_server_mng_mail import _make
    return _make(**kwargs)
...
def cust_create(**kwargs):
    from lib_server_mng_cust _cust_create
    return _cust_create(**kwargs)
...
def ftpd_make(**kwargs):
    from lib_server_mng_ftp import _make
    return _make(**kwargs)

etc.
`````

This does not seem to work in recent versions of salt anymore. With the most simple example from the top it fails on the import already.

````
bash
# salt-call test_module.save_config
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
ImportError: No module named submod
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 352, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "/var/cache/salt/minion/extmods/modules/test_module.py", line 5, in save_config
    from submod import save_a
ImportError: No module named submod
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 352, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "/var/cache/salt/minion/extmods/modules/test_module.py", line 5, in save_config
    from submod import save_a
ImportError: No module named submod
````

Is there any way, to get the old import behaviour in recent versions of salt (2016.3.*)? 

```bash
# salt --versions-report
Using master 172.16.0.13...
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.6
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.6
```

**Comment by felskrone** [comment]
For testing purposes, i simply updates the import path:

````bash
import logging
log = logging.getLogger(__name__)

def save_a():
    log.info('save_a() called')
    __salt__['cmdmod.run_all']('ls -l')
```

While this seems to work, its a no-go (hardcoded paths etc.).

While testing this, i noticed another problem with the "submodules". The dunder-dicts (__salt__, etc.) are not available to them anymore but they used to be. Im guessing these behaviours/problems are related?

Updated submod.py
````bash
import logging
log = logging.getLogger(__name__)

def save_a():
    log.info('save_a() called')
    __salt__['cmdmod.run_all']('ls -l')
````

Brakes with an undefined __salt__ error
```bash
# salt-call test_module.save_config
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
NameError: global name '__salt__' is not defined
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 352, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "/var/cache/salt/minion/extmods/modules/test_module.py", line 10, in save_config
    save_a()
  File "/var/cache/salt/minion/files/base/_modules/submod.py", line 6, in save_a
    __salt__['cmdmod.run_all']('ls -l')
NameError: global name '__salt__' is not defined
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 352, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "/var/cache/salt/minion/extmods/modules/test_module.py", line 10, in save_config
    save_a()
  File "/var/cache/salt/minion/files/base/_modules/submod.py", line 6, in save_a
    __salt__['cmdmod.run_all']('ls -l')
NameError: global name '__salt__' is not defined
```

**Comment by Ch3LL** [comment]
@felskrone what version of salt was this working in? I am still replicating this error on version 2015.8.5.

**Comment by felskrone** [comment]
We are currently running a 2014.7.* and it works fine. Its a custom build based on f2c23ab4.

**Comment by felskrone** [comment]
Any news or anything i can help you with? This is currently the only blocker keeping us from upgrading. I can live with almost any workaround, since the/a fix will take its time to find its way in debians packages anyway :-)

**Comment by s0undt3ch** [comment]
While this is not the fix you are after, regarding the dunders name errors, every function you import needs to be namespaced. Look at the cloud drivers for examples on how (I'm on the phone and can't link bto examples easily).
Regarding hardcoded paths:
```python
sys.path.insert(0, os.path.abspath(os.path.dirname(__file__)))
```

**Comment by felskrone** [comment]
Great, the dynamic insert works perfectly and will be fine for now. Thanks a lot!

Regarding the cloud-drivers, i've been looking through a few files, but cant quite figure out what you're refering to. A link would help a lot :-)

**Comment by s0undt3ch** [comment]
Give me some mins...

**Comment by s0undt3ch** [comment]
[Here's an example of namespacing functions](https://github.com/saltstack/salt/blob/develop/salt/cloud/clouds/rackspace.py#L71-L84).

**Comment by felskrone** [comment]
Im sorry, but i cant get this to work.

My latest try with the mount-module looks like this:

test_module.py
````python
import logging
import sys
import os

sys.path.insert(0, os.path.abspath((os.path.dirname(__file__))))

log = logging.getLogger(__name__)

def save_config():
    from submod import save_a
    return save_a()
````

submod.py
```python
import logging
from salt.utils import namespaced_function
from salt.modules.mount import *

log = logging.getLogger(__name__)

def save_a():
    swaps = namespaced_function(swaps, globals())
    return swaps()
````

But to be honest, im basically just replicating the code you linked to and changing the lines. I do not fully understand what i have to do to get this working yet. Anyway, this fails with

```bash
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 352, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "/var/cache/salt/minion/extmods/modules/test_module.py", line 15, in save_config
    return save_a()
  File "/var/cache/salt/minion/extmods/modules/submod.py", line 8, in save_a
    swaps = namespaced_function(swaps, globals())
UnboundLocalError: local variable 'swaps' referenced before assignment
```

I guess the 'from mount import  *' does not import swaps into my namespace?

I also tried importing a module directly

```python
import logging
from salt.modules.mount import swaps

log = logging.getLogger(__name__)

def save_a():
    return swaps()
````

but this if course also fails since __grains__ nor __salt__ is defined that way.

**Comment by felskrone** [comment]
My latest creation that seems to work with namespacing the funtion swaps().

```python
import logging
from salt.utils import namespaced_function
from salt.modules.mount import swaps as foo

log = logging.getLogger(__name__)

def save_a():
    swaps = namespaced_function(foo, globals())
    return swaps()
````

But this fails with the same error as above, the undefined \_\_grains\_\_.

Hoping that you an elnighten me a little :-)

**Comment by felskrone** [comment]
I got something that partly works by running the loader from within submod.py

```python
import salt.utils
import salt.config
import salt.loader
import yaml

__opts__ = salt.config.minion_config('/etc/salt/minion')
__grains__ = salt.loader.grains(__opts__)
__opts__['grains'] = __grains__
__utils__ = salt.loader.utils(__opts__)
__salt__ = salt.loader.minion_mods(__opts__, utils=__utils__)

def save_a():
    return __salt__['mount.swaps']()
```

The downside (besides running the loader all the time) is that running states like this

```python
import logging

import salt.config
import salt.loader

__opts__ = salt.config.minion_config('/etc/salt/minion')
__grains__ = salt.loader.grains(__opts__)
__opts__['grains'] = __grains__
__utils__ = salt.loader.utils(__opts__)
__salt__ = salt.loader.minion_mods(__opts__, utils=__utils__)

log = logging.getLogger(__name__)

def save_a():
    __salt__['state.sls']('motd-formula')
    return __salt__['mount.swaps']()
```

fails because of missing variables somewhere.

```python
...
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
KeyError: 'master_uri'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 352, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "/var/cache/salt/minion/extmods/modules/test_module.py", line 12, in save_config
    return save_a()
  File "/var/cache/salt/minion/extmods/modules/submod.py", line 15, in save_a
    __salt__['state.sls']('grains-formula')
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 908, in sls
    mocked=kwargs.get('mock', False))
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 3333, in __init__
    self.client = salt.fileclient.get_file_client(self.opts)
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 57, in get_file_client
    }.get(client, RemoteClient)(opts)
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 1043, in __init__
    self.channel = salt.transport.Channel.factory(self.opts)
  File "/usr/lib/python2.7/dist-packages/salt/transport/__init__.py", line 49, in factory
    return ReqChannel.factory(opts, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/client.py", line 22, in factory
    sync = SyncWrapper(AsyncReqChannel.factory, (opts,), kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/utils/async.py", line 60, in __init__
    self.async = method(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/client.py", line 114, in factory
    return salt.transport.tcp.AsyncTCPReqChannel(opts, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/tcp.py", line 128, in __new__
    key = cls.__key(opts, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/tcp.py", line 147, in __key
    opts['master_uri'],
KeyError: 'master_uri'
````

back to square one... :-/

**Comment by felskrone** [comment]
@s0undt3ch Could you please let me know if you are going to comment / help? Its totally fine if you dont want to / dont have the time to help. I just need to know, so i can  start rewriting some of the code so that it works with 2016.3.*. which i would not start doing if i just have to wait a bit for your help / explanation.
