### ISSUE TITLE
VM creation / deletion on vSphere 5.5 is aborted with "Error: None"

### ISSUE THREAD

**Issue by jbfriedrich** [saltstack/salt#37845]
### Description of Issue/Question

When a VM is deployed or deleted in our vSphere 5.5 cluster via salt-cloud, there is a 50% chance that the task cannot be successfully completed. It seems that the "while loop" in `/usr/lib/python2.7/site-packages/salt/utils/vmware.py` (line 630) is prematurely evacuated. I added a line of debug code so that I would know which value 'task.info.error' would have, as I first thought this problem was related to #28511:

```
    else:
        print "##DEBUG TASK STATE: {0}".format(task.info.state) 
        raise Exception(task.info.error)
```

The task.info.state is still "running" and I cannot see a reason for leaving the while loop. I tried different sleep times, but to no avail. I also tried several pyVmomi versions: 5.5.0-2014.1.1, 6.0 and I am currently testing the new 6.5. All seem to have the same issue.

So far we only see this behaviour while cloning or destroying a VM. When it happens during cloning, the VM deployment is still running and will be completed successfully. When it happens during deletion, sometimes the VM is deleted regardless of the error, sometimes the VM is not deleted at all.

#### VM Cloning
```
[INFO    ] Creating <vmname> from vm(centos7-base)
##DEBUG TASK STATE: running
[ERROR   ] Error creating <vmname>: None
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/vmware.py", line 2478, in create
    salt.utils.vmware.wait_for_task(task, vm_name, 'clone', 5, 'info')
  File "/usr/lib/python2.7/site-packages/salt/utils/vmware.py", line 647, in wait_for_task
    raise Exception(task.info.error)
Exception: None
[DEBUG   ] LazyLoaded nested.output
<vmname>:
    ----------
    Error:
        Error creating <vmname>: None
```

Even though the error is raised, the VM is deployed. These are the entries from the vCenter log for the VM deployment:

```
2016-11-22T14:56:37.943-05:00 [20464 info 'vpxdvpxdVmomi' opID=7574f9a8-28] [ClientAdapterBase::InvokeOnSoap] Invoke done (hypervisor07, vpxapi.VpxaService.createVm)
2016-11-22T14:56:39.712-05:00 [20464 info 'vpxdvpxdVmomi' opID=7574f9a8-28] [ClientAdapterBase::InvokeOnSoap] Invoke done (hypervisor07, vim.VirtualMachine.reconfigure)
2016-11-22T14:56:40.464-05:00 [20464 info 'pbmvpxd' opID=7574f9a8-28] PBMCallback: PbmCallBack::CreateAssociationOps: Given NULL/zero-length list of profile specs
2016-11-22T14:56:40.473-05:00 [20464 info 'VmProv' opID=7574f9a8-28] [WorkflowXAction] Scanning workflow entries
2016-11-22T14:56:40.474-05:00 [20464 warning 'Default' opID=7574f9a8-28] [JrnlFilePersistenceProvider] Got EOF while reading file
2016-11-22T14:56:40.501-05:00 [20464 warning 'VAppvpxdOvfConsumers' opID=7574f9a8-28] [VpxdOvfConsumers::CreateContext] Creating dummy context
2016-11-22T14:56:40.505-05:00 [20464 info 'pbmvpxd' opID=7574f9a8-28] PBMCallback: PbmCallBack::CreateAssociationOps: Given NULL/zero-length list of profile specs
2016-11-22T14:56:40.514-05:00 [20464 info 'Default' opID=7574f9a8-28] [VmCustomizer] hostVersion = 5.5.0, tools version = 2147483647
2016-11-22T14:56:40.514-05:00 [20464 info 'Default' opID=7574f9a8-28] [VmCustomizer] Successfully created file C:\Windows\TEMP\imc768F.tmp
2016-11-22T14:56:40.514-05:00 [20464 info 'Default' opID=7574f9a8-28] [VmCustomizer] Successfully created file C:\Windows\TEMP\imc7690.tmp
2016-11-22T14:56:40.514-05:00 [20464 info 'Default' opID=7574f9a8-28] [IMC] Create package for Linux Customization. Params:
2016-11-22T14:56:40.514-05:00 [20464 info 'Default' opID=7574f9a8-28] [IMC] Perl Script directory = C:\Program Files\VMware\Infrastructure\VirtualCenter Server\imgcust\imgcust-scripts
2016-11-22T14:56:40.514-05:00 [20464 info 'Default' opID=7574f9a8-28] [IMC] Config file path = C:\Windows\TEMP\imc7690.tmp
2016-11-22T14:56:40.515-05:00 [20464 info 'Default' opID=7574f9a8-28] [IMC] Successfully created file C:\Windows\TEMP\imc7691.tmp
2016-11-22T14:56:40.515-05:00 [20464 info 'Default' opID=7574f9a8-28] [IMC] Successfully created file C:\Windows\TEMP\imc7692.tmp
2016-11-22T14:56:40.562-05:00 [20464 info 'Default' opID=7574f9a8-28] [IMC] Successfully deleted file/directory C:\Windows\TEMP\imc7692.tmp
2016-11-22T14:56:40.563-05:00 [20464 info 'Default' opID=7574f9a8-28] [IMC] Successfully deleted file/directory C:\Windows\TEMP\imc7691.tmp
2016-11-22T14:56:40.564-05:00 [20464 info 'Default' opID=7574f9a8-28] [VmCustomizer] Successfully deleted file/directory C:\Windows\TEMP\imc7690.tmp
2016-11-22T14:56:40.568-05:00 [20464 info 'Default' opID=7574f9a8-28] [VmCustomizer] hostVersion = 5.5.0, tools version = 2147483647
2016-11-22T14:56:41.333-05:00 [20464 info 'vpxdvpxdVmomi' opID=7574f9a8-28] [ClientAdapterBase::InvokeOnSoap] Invoke done (hypervisor07, vim.dvs.HostDistributedVirtualSwitchManager.applyDVPortgroup)
2016-11-22T14:56:41.354-05:00 [20464 info 'vpxdvpxdVmomi' opID=7574f9a8-28] [ClientAdapterBase::InvokeOnSoap] Invoke done (hypervisor07, vim.VirtualMachine.reconfigure)
2016-11-22T14:56:42.227-05:00 [20464 info 'pbmvpxd' opID=7574f9a8-28] PBMCallback: PbmCallBack::CreateAssociationOps: Given NULL/zero-length list of profile specs
2016-11-22T14:56:42.234-05:00 [20464 info 'Default' opID=7574f9a8-28] [VmCustomizer] Successfully deleted file/directory C:\Windows\TEMP\imc768F.tmp
2016-11-22T14:56:42.236-05:00 [20464 info 'VmProv' opID=7574f9a8-28] [WorkflowXAction] Scanning workflow entries
2016-11-22T14:56:42.237-05:00 [20464 warning 'Default' opID=7574f9a8-28] [JrnlFilePersistenceProvider] Got EOF while reading file
2016-11-22T14:56:42.240-05:00 [20464 info 'commonvpxLro' opID=7574f9a8-28] [VpxLRO] -- FINISH task-internal-6529319 --  -- VmprovWorkflow -- 
2016-11-22T14:56:42.242-05:00 [20464 info 'vpxdvpxdVmomi' opID=7574f9a8-28] [ClientAdapterBase::InvokeOnSoap] Invoke done (hypervisor07, vmodl.query.PropertyCollector.cancelWaitForUpdates)
```

#### VM Deletion
```
[ERROR   ] Error while powering off VM <vmname>: None
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/vmware.py", line 2085, in destroy
    salt.utils.vmware.wait_for_task(task, name, 'power off')
  File "/usr/lib/python2.7/site-packages/salt/utils/vmware.py", line 646, in wait_for_task
    raise Exception(task.info.error)
Exception: None
[DEBUG   ] Deleted '/etc/salt/pki/master/minions/<vmname>'
```

There is a 50/50 chance the VM was deleted. Sometimes it is deleted even though the error is raised, sometimes I have to call it twice to be completely removed. 

### Setup
- VMware vSphere 5.5u3
- DRS-enabeld cluster (fully automated)
- DRS-enabled datastore cluster and non-clustered datastores 

### Steps to Reproduce Issue
- Use `salt-cloud -p <profile> <vmname>` or `salt-cloud -d <vmname>` (current chance is 50/50 if the deployment is successful or not)

### Versions Report
```
Salt Version:
           Salt: 2016.3.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.36.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 CoreSalt Version:
           Salt: 2016.3.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.36.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

**Comment by Ch3LL** [comment]
@jbfriedrich did you just recently start seeing this behavior after upgrading to 2016.3.4? In other words is this new behavior and the vmware provider was working previously?

**Comment by jbfriedrich** [comment]
@Ch3LL I see this behaviour with 2016.3.3 and 2016.3.4. It seems to be completely erratic so far, sometimes it doesn't happen for hours, sometimes its a 50/50 success rate.

**Comment by conradjones** [comment]
Have you tried the latest dev branch ? 

I was seeing random creation errors when cloning a vmware template, inspection of the code showed additional exception handling.

**Comment by conradjones** [comment]
2016.3.xx

`def wait_for_task(task, instance_name, task_type, sleep_seconds=1, log_level='debug'):
    '''
    Waits for a task to be completed.
    task
        The task to wait for.
    instance_name
        The name of the ESXi host, vCenter Server, or Virtual Machine that the task is being run on.
    task_type
        The type of task being performed. Useful information for debugging purposes.
    sleep_seconds
        The number of seconds to wait before querying the task again. Defaults to ``1`` second.
    log_level
        The level at which to log task information. Default is ``debug``, but ``info`` is also supported.
    '''
    time_counter = 0
    start_time = time.time()
    while task.info.state == 'running' or task.info.state == 'queued':
        if time_counter % sleep_seconds == 0:
            msg = '[ {0} ] Waiting for {1} task to finish [{2} s]'.format(instance_name, task_type, time_counter)
            if log_level == 'info':
                log.info(msg)
            else:
                log.debug(msg)
        time.sleep(1.0 - ((time.time() - start_time) % 1.0))
        time_counter += 1
    if task.info.state == 'success':
        msg = '[ {0} ] Successfully completed {1} task in {2} seconds'.format(instance_name, task_type, time_counter)
        if log_level == 'info':
            log.info(msg)
        else:
            log.debug(msg)
    else:
        raise Exception(task.info.error)`


vs develop branch 

`def wait_for_task(task, instance_name, task_type, sleep_seconds=1, log_level='debug'):
    '''
    Waits for a task to be completed.
    task
        The task to wait for.
    instance_name
        The name of the ESXi host, vCenter Server, or Virtual Machine that
        the task is being run on.
    task_type
        The type of task being performed. Useful information for debugging purposes.
    sleep_seconds
        The number of seconds to wait before querying the task again.
        Defaults to ``1`` second.
    log_level
        The level at which to log task information. Default is ``debug``,
        but ``info`` is also supported.
    '''
    time_counter = 0
    start_time = time.time()
    log.trace('task = {0}, task_type = {1}'.format(task,
                                                   task.__class__.__name__))
    try:
        task_info = task.info
    except vim.fault.VimFault as exc:
        raise salt.exceptions.VMwareApiError(exc.msg)
    except vmodl.RuntimeFault as exc:
        raise salt.exceptions.VMwareRuntimeError(exc.msg)
    while task_info.state == 'running' or task_info.state == 'queued':
        if time_counter % sleep_seconds == 0:
            msg = '[ {0} ] Waiting for {1} task to finish [{2} s]'.format(
                instance_name, task_type, time_counter)
            if log_level == 'info':
                log.info(msg)
            else:
                log.debug(msg)
        time.sleep(1.0 - ((time.time() - start_time) % 1.0))
        time_counter += 1
        try:
            task_info = task.info
        except vim.fault.VimFault as exc:
            raise salt.exceptions.VMwareApiError(exc.msg)
        except vmodl.RuntimeFault as exc:
            raise salt.exceptions.VMwareRuntimeError(exc.msg)
    if task_info.state == 'success':
        msg = '[ {0} ] Successfully completed {1} task in {2} seconds'.format(
            instance_name, task_type, time_counter)
        if log_level == 'info':
            log.info(msg)
        else:
            log.debug(msg)
        # task is in a successful state
        return task_info.result
    else:
        # task is in an error state
        try:
            raise task_info.error
        except vim.fault.VimFault as exc:
            raise salt.exceptions.VMwareApiError(exc.msg)
        except vmodl.fault.SystemError as exc:
            raise salt.exceptions.VMwareSystemError(exc.msg)
        except vmodl.fault.InvalidArgument as exc:
            exc_message = exc.msg
            if exc.faultMessage:
                exc_message = '{0} ({1})'.format(exc_message,
                                                 exc.faultMessage[0].message)
            raise salt.exceptions.VMwareApiError(exc_message)`

**Comment by jbfriedrich** [comment]
@conradjones we have not tried to use the latest dev build as we are currently trying to build a production environment  and wanted to use salt 2016.3.4 or 2016.11.x. I will create a snapshot of the saltmaster VM and will install the latest development release on the master and test with that. I will update this thread once I have tested.

**Comment by omegarus** [comment]
I have similar problem on salt 2016.11.1 and vmware 5.5:
``` salt-cloud -l debug -m /etc/salt/cloud.maps.d/mapfile.conf -y ```

```
[INFO    ] Creating vm-from-mapfile from vm(Ubuntu14.04_desktop_new14.04.4)
[ERROR   ] Error creating vm-from-mapfile: exceptions must be old-style classes or derived from BaseException, not NoneType
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/vmware.py", line 2603, in create
    salt.utils.vmware.wait_for_task(task, vm_name, 'clone', 5, 'info')
  File "/usr/lib/python2.7/dist-packages/salt/utils/vmware.py", line 931, in wait_for_task
    raise task.info.error
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType
[INFO    ] Complete
[DEBUG   ] LazyLoaded nested.output
vm-from-mapfile:
    ----------
    Error:
        Error creating vm-from-mapfile: exceptions must be old-style classes or derived from BaseException, not NoneType
```

**Comment by jbfriedrich** [comment]
@conradjones Apologies for the delay. I was on winter vacation and started working in January again. I will need probably a week or two until I can try it with the development release as currently there are some deliverable that need my attention first. But this issue is not forgotten.

**Comment by omegarus** [comment]
@conradjones  @conradjones I changed my local salt/utils/vmware.py with vmware.py from develop branch. 10 out of 10 deployments from map file are worked without problems.
Salt 2016.11.1
pyvmomi==6.0.0.2016.6

**Comment by discotroy** [comment]
As a followup to this, as of 20 Feb 2017, pyvmomi==6.5 (as upgraded to by Ubuntu 16.04 server packages) doesn't work with either the packaged or develop version of 2016.11.2 salt/utils/vmware.py, but reverting to pyvmomi==6.0.0.2016.6 and using the develop version of vmware.py does.

For me, at least.

**Comment by conradjones** [comment]
Yes the fix is not in any release. Hopefully they will do a release soon.

**Comment by Ch3LL** [comment]
Do any of you know the PR the fixes were tied to? Or just point me to where in the code it was added and i can do a git blame. If we figure out the PR then we can possibly back port to 2016.11 branch .

**Comment by jbfriedrich** [comment]
Using "vmware.py" from the development branch does not help me unfortunately. I think the error message is misleading. I think the connection to the vCenter is severed for a currently unknown reason, and as there is no "real" error, the Exception is "None" and therefore the error message.

With 2016.11.1 this exception is caught and we get some better error message:

> Error while destroying VM $VMNAME$: exceptions must be old-style classes or derived from BaseException, not NoneType
 
But its still the same issue. The connection got severed, no error from vSphere, so the raised exception is "None". So far I am not sure why the connection is severed or which end is responsible for it.

**Comment by cetanu** [comment]
I also had this occurring, same behavior, appeared to be some premature end of the while loop in wait_for_task resulting in the error message being None

I haven't confirmed it as fixed (using the latest dev branch), because in the meantime we implemented a 45 second wait between create/deletes, because we only saw this issue occurring after re-creating a machine very soon after it was destroyed.

**Comment by rdutch** [comment]
This issue was confirmed by me, only see it on vSphere 5.5, vSphere 6.5 works fine.

**Comment by rickh563** [comment]
ZD-2270

**Comment by Ch3LL** [comment]
@rdutch which version are you seeing this in? Does this also occur in 2017.7?

**Comment by rdutch** [comment]
@Ch3LL Yes, we saw it on 2017.7.2

**Comment by Ch3LL** [comment]
ping @nmadhok do you have any ideas here?
