### ISSUE TITLE
network.default_route throws IndexError Exception when netstat binary is not installed

### ISSUE THREAD

**Issue by dkiser** [saltstack/salt#37851]
### Description of Issue/Question

`network.default_route` throws IndexError Exception when netstat binary is not installed

`salt-run network.default_route` results in an `IndexError` Exception when running on a system that doesn't have the `netstat` binary installed by default (e.g CentOS 7.x).  Some distributions are now deprecating `netstat` for other tools such as `ss`. 

It may make sense to use something more portable such as `/proc/net/route` or intelligently determine available CLI's to shell out to in  https://github.com/saltstack/salt/blob/develop/salt/modules/network.py#L343.

### Setup

1. Install latest CentOS 7.X
2. Install latest Salt

### Steps to Reproduce Issue

```bash
[root@salt-minion-v7 vagrant]# salt-call network.default_route
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
IndexError: list index out of range
Traceback (most recent call last):
  File "/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 372, in salt_call
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/network.py", line 1345, in default_route
    _routes = routes()
  File "/usr/lib/python2.7/site-packages/salt/modules/network.py", line 1309, in routes
    routes_ = _netstat_route_linux()
  File "/usr/lib/python2.7/site-packages/salt/modules/network.py", line 353, in _netstat_route_linux
    'interface': comps[7]})
IndexError: list index out of range
Traceback (most recent call last):
  File "/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 372, in salt_call
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/network.py", line 1345, in default_route
    _routes = routes()
  File "/usr/lib/python2.7/site-packages/salt/modules/network.py", line 1309, in routes
    routes_ = _netstat_route_linux()
  File "/usr/lib/python2.7/site-packages/salt/modules/network.py", line 353, in _netstat_route_linux
    'interface': comps[7]})
IndexError: list index out of range
```

### Versions Report
```
Salt Version:
           Salt: 2016.3.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.36.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

**Comment by Ch3LL** [comment]
@dkiser i am able to replicate this behavior adn yes it seems we need to add logic if that tool is not installed to use a different method.
