### ISSUE TITLE
SaltRenderError error

### ISSUE THREAD

**Issue by peter-held** [saltstack/salt#37853]
### Description of Issue/Question
The attached state files are not rendered correctly.

/srv/base/states/apt-listchanges/map.jinja
```sls
{% set files_dir = 'salt://' + slspath + '/files' %}            # directory where file templates are stored
{% set formula_name = sls.split ('.')[0] %}                     # formula name (same as directory name)

{% set settings = salt.grains.filter_by ({
    'Ubuntu': {
        'pkgs':         [ formula_name ],
        'service':      formula_name,
        'conf_dir':     '/etc/' + formula_name,
        'conf_file':    formula_name + '.conf',

        'test_key':     salt.grains.filter_by ({
                            'trusty':   'test_value_trusty',
                            'xenial':   'test_value_xenial',
                            'default':  'test_value_default',
                        }, grain='oscodename'),
    },

    'Debian': {
    },
}, grain='os', merge=salt.pillar.get (formula_name)) %}
 ```

/srv/base/states/apt-listchanges/init.sls
```sls
include:
  - .pkg
  - .environment
  - .config
 ```
/srv/base/states/apt-listchanges/pkg.sls
```sls
{% import sls.split('.')[0] + '/map.jinja' as this %}


{{ this.formula_name }}_pkg:
  pkg.latest:
    - pkgs:
    {% for pkg in this.settings.pkgs %}
      - {{ pkg }}
    {% endfor %}
    #- install_recommends: false
```
/srv/base/states/apt-listchanges/environment.sls
```sls
{% import sls.split('.')[0] + '/map.jinja' as this %} 


include:
  - .pkg
 ```
/srv/base/states/apt-listchanges/config.sls
```sls
{% import sls.split ('.')[0] + '/map.jinja' as this with context %} 


include:
  - .pkg
  - .environment


{{ this.formula_name }}_listchanges.conf:
  file.managed:
    - name: /etc/apt/listchanges.conf
    - source: {{ this.files_dir }}/listchanges.conf
    - user: root
    - group: root
    - mode: 644
    - template: jinja
    - defaults:
      	this: {{ this }}
 ```

/srv/base/states/apt-listchanges/files/listchanges.conf
```sls
[apt]
frontend=pager
email_address={{ this.settings.email }}
confirm=0
save_seen=/var/lib/apt/listchanges.db
which=news
```

/srv/base/pillar/apt-listchanges/init.sls 
```sls
apt-listchanges:
  email:    'admin@domain.dom'
 ```

```python
salt local state.apply apt-listchanges test=true
local:
  Name: apt-listchanges_pkg - Function: pkg.latest - Result: Clean Started: - 09:23:57.710408 Duration: 5971.212 ms
----------
          ID: apt-listchanges_listchanges.conf
    Function: file.managed
        Name: /etc/apt/listchanges.conf
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1733, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1653, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 1655, in managed
                  **kwargs
                File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 3974, in check_managed_changes
                  **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 3640, in get_managed
                  **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 178, in render_tmpl
                  output = render_str(tmplstr, context, tmplpath)
                File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 386, in render_jinja_tmpl
                  buf=tmplstr)
              SaltRenderError: Jinja variable 'None' has no attribute 'settings'
     Started: 09:24:03.685675
    Duration: 287.787 ms
     Changes:

Summary for local
------------
Succeeded: 1
Failed:    1
------------
Total states run:     2
Total run time:   6.259 s
ERROR: Minions returned with non-zero exit code
```

### Setup
NA

### Steps to Reproduce Issue
Use attached state files.

### Versions Report
```yaml    
    Salt Version:
               Salt: 2016.3.4
     
    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 2.4.2
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.8
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: 1.0.3
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 15.2.0
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.1.4
     
    System Versions:
               dist: Ubuntu 16.04 xenial
            machine: x86_64
            release: 4.4.0-47-generic
             system: Linux
            version: Ubuntu 16.04 xenial
```

**Comment by Ch3LL** [comment]
@peter-held i'm having a hard time replicating this, but I am getting a different error with an exact copy/paste from these sls files:

```
root@6d794e8d88c4:/srv/salt/apt-listchanges# salt '*' state.apply apt-listchanges test=true
6d794e8d88c4:
    Data failed to compile:
----------
    Rendering SLS 'base:apt-listchanges.config' failed: Illegal tab character; line 18

---
[...]
    - user: root
    - group: root
    - mode: 644
    - template: jinja
    - defaults:
        this:             # directory where file templates are stored    <======================
                     # formula name (same as directory name)



---
```

It looks like its pulling in those comments for some reason. Are there some missing sls files or anything else to help replicate this?

Here is a docker container to show my test setup:

1. `docker run -it -v /home/ch3ll/git/salt/:/testing/ ch3ll/issues:37853 /bin/bash` (where /home/ch3ll/git/salt/ is a local cloned git repo of salt)
2. `salt-master -d; salt-minion -d`
3. `salt '*' state.apply apt-listchanges test=true` and you will my rendering error.

**Comment by peter-held** [comment]
I have attached the entire formula. Same error here:

```python
local:
  Name: apt-listchanges_pkg - Function: pkg.latest - Result: Clean Started: - 21:11:20.547146 Duration: 4449.44 ms
----------
          ID: apt-listchanges_service
    Function: service.running
        Name: apt-listchanges
      Result: False
     Comment: The named service apt-listchanges is not available
     Started: 21:11:25.020158
    Duration: 72.11 ms
     Changes:   
----------
          ID: apt-listchanges_listchanges.conf
    Function: file.managed
        Name: /etc/apt/listchanges.conf
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1733, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1653, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 1655, in managed
                  **kwargs
                File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 3974, in check_managed_changes
                  **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 3640, in get_managed
                  **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 178, in render_tmpl
                  output = render_str(tmplstr, context, tmplpath)
                File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 386, in render_jinja_tmpl
                  buf=tmplstr)
              SaltRenderError: Jinja variable 'None' has no attribute 'settings'
     Started: 21:11:25.186192
    Duration: 253.988 ms
     Changes:   

Summary for local
------------
Succeeded: 1
Failed:    2
------------
Total states run:     3
Total run time:   4.776 s
ERROR: Minions returned with non-zero exit code
```

[apt-listchanges.zip](https://github.com/saltstack/salt/files/617467/apt-listchanges.zip)

**Comment by peter-held** [comment]
Any news regarding the issue ?

**Comment by peter-held** [comment]
Why are you closing the issue ?
The problem still exists.

Please use the above zip file in order to reproduce the problem.

**Comment by Ch3LL** [comment]
thanks for bumping this for me @peter-held 

You will just need to update your states:

```
    - defaults:
        this: {{ this.settings }}
```

```
email_address={{ this.email }}
```

If you print the full jinja context with the following:

```
{% do salt.log.error(show_full_context()|yaml(False)) %}
```

You will see the following:

```
this: <TemplateModule 'testmap.jinja'>
```

so you need to pass `this.settings`.

**Comment by peter-held** [comment]
Yes, this is what I'm doing at the moment.

Still, I would like to pass the entire 'this' not just only 'this.settings', because I also need other fields from 'this'.

So, the problem is, why is not working with:
    - defaults:
      	this: {{ this }}

Thank you.
