### ISSUE TITLE
Salt and salt-call state.highstate returns 0 when a service fails to start

### ISSUE THREAD

**Issue by djsly** [saltstack/salt#37852]
### Description of Issue/Question
Bad return code when a service.running state fails due to an invalid service name when 

```
----------
          ID: docker_latest
    Function: service.running
      Result: False
     Comment: The named service docker_latest is not available
     Started: 20:08:44.340889
    Duration: 13.847 ms
     Changes:   
----------
----------
          ID: registry-proxy
    Function: dockerng.running
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1628, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1494, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/dockerng.py", line 1508, in running
                  if image not in __salt__['dockerng.list_tags']():
                File "/usr/lib/python2.7/site-packages/salt/modules/dockerng.py", line 2247, in list_tags
                  for item in six.itervalues(images()):
                File "/usr/lib/python2.7/site-packages/salt/modules/dockerng.py", line 2057, in images
                  response = _client_wrapper('images', all=kwargs.get('all', False))
                File "/usr/lib/python2.7/site-packages/salt/modules/dockerng.py", line 632, in wrapper
                  _get_client(timeout=client_timeout)
                File "/usr/lib/python2.7/site-packages/salt/modules/dockerng.py", line 740, in _get_client
                  __context__['docker.client'] = docker.Client(**client_kwargs)
                File "/usr/lib/python2.7/site-packages/docker/client.py", line 77, in __init__
                  self._version = self._retrieve_server_version()
                File "/usr/lib/python2.7/site-packages/docker/client.py", line 97, in _retrieve_server_version
                  'Error while fetching server API version: {0}'.format(e)
              DockerException: Error while fetching server API version: ('Connection aborted.', error(2, 'No such file or directory'))
     Started: 20:08:44.586481
    Duration: 5.827 ms
     Changes:   
-------------
Summary for local
-------------
Succeeded: 81 (changed=3)
Failed:     2
-------------
Total states run:     83
Total run time:   15.541 s
[root@host ~]# echo $?
0
```

### Steps to Reproduce Issue
[INFO    ] Executing state service.running for docker_latest
[INFO    ] Executing command ['systemctl', 'status', 'docker_latest.service', '-n', '0'] in directory '/root'
[DEBUG   ] output: * docker_latest.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
[ERROR   ] The named service docker_latest is not available

[DEBUG   ] LazyLoaded dockerng.version
[DEBUG   ] LazyLoaded dockerng.running
[INFO    ] Running state [registry-proxy] at time 20:16:11.959251
[INFO    ] Executing state dockerng.running for registry-proxy
[DEBUG   ] File doesn't exist
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
```
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 1628, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1494, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/states/dockerng.py", line 1508, in running
    if image not in __salt__['dockerng.list_tags']():
  File "/usr/lib/python2.7/site-packages/salt/modules/dockerng.py", line 2247, in list_tags
    for item in six.itervalues(images()):
  File "/usr/lib/python2.7/site-packages/salt/modules/dockerng.py", line 2057, in images
    response = _client_wrapper('images', all=kwargs.get('all', False))
  File "/usr/lib/python2.7/site-packages/salt/modules/dockerng.py", line 632, in wrapper
    _get_client(timeout=client_timeout)
  File "/usr/lib/python2.7/site-packages/salt/modules/dockerng.py", line 740, in _get_client
    __context__['docker.client'] = docker.Client(**client_kwargs)
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 77, in __init__
    self._version = self._retrieve_server_version()
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 97, in _retrieve_server_version
    'Error while fetching server API version: {0}'.format(e)
DockerException: Error while fetching server API version: ('Connection aborted.', error(2, 'No such file or directory'))
```
[INFO    ] Completed state [registry-proxy] at time 20:16:11.965797

### Versions Report
salt-minion --versions-report
Salt Version:
           Salt: 2015.8.12
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.18.2.el7.x86_64
         system: CentOS Linux 7.2.1511 Core

**Comment by Ch3LL** [comment]
Looks like I'm able to replicate this on 2016.3.4 as well:

```
[root@localhost salt]# salt-call --local state.highstate 
[ERROR   ] Service systemd-readahead-replay is already enabled, and is dead
local:
----------
          ID: systemd-readahead-replay
    Function: service.running
      Result: False
     Comment: Service systemd-readahead-replay is already enabled, and is dead
     Started: 07:45:27.342153
    Duration: 63.059 ms
     Changes:   

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:  63.059 ms
[root@localhost salt]# echo $?
0
```

looks like we need to get this fixed up. Thanks
