### ISSUE TITLE
Bug into lsb_release that crash salt

### ISSUE THREAD

**Issue by tobiasBora** [saltstack/salt#37867]
### Description of Issue/Question

The lsb_release python file is buggy, as I reported [here](https://lsbbugs.linuxfoundation.org/show_bug.cgi?id=4180): on systems like raspbian, the file /usr/share/distro-info/raspbian.csv does not exists, which produces an error like this one 

```
$ sudo salt-minion -l debug
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/myconfig_minion.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/myconfig_minion.conf
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] Setting up the Salt Minion "raspberrypi"
[DEBUG   ] Created pidfile: /var/run/salt-minion.pid
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/myconfig_minion.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/myconfig_minion.conf
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 85, in minion_process
    minion.start()
  File "/usr/lib/python2.7/dist-packages/salt/cli/daemons.py", line 344, in start
    super(Minion, self).start()
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 941, in start
    self.prepare()
  File "/usr/lib/python2.7/dist-packages/salt/cli/daemons.py", line 327, in prepare
    self.minion = salt.minion.Minion(self.config)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 853, in __init__
    self.opts['grains'] = salt.loader.grains(opts)
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 704, in grains
    ret = fun()
  File "/usr/lib/python2.7/dist-packages/salt/grains/core.py", line 1229, in os_data
    release = lsb_release.get_distro_information()
  File "/usr/lib/python2.7/dist-packages/lsb_release.py", line 341, in get_distro_information
    distinfo = guess_debian_release()
  File "/usr/lib/python2.7/dist-packages/lsb_release.py", line 239, in guess_debian_release
    get_distro_info(distinfo['ID'])
  File "/usr/lib/python2.7/dist-packages/lsb_release.py", line 33, in get_distro_info
    except FileNotFoundError:
NameError: global name 'FileNotFoundError' is not defined
```

Indeed, FileNotFoundError is defined in python 3 and not in python 2.7.

The problem is that because of this bug, it's not possible to start the minion... So it may be a good idea not to crash the whole process just because of a file.

Thank you in advance,

TobiasBora.

### Steps to Reproduce Issue

Run on a raspbian (or on a system with the file /usr/share/distro-info/<distro>.csv removed) the command

    salt-minion -l debug

It crashes.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
$ salt --versions-report
Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: 1.7.0
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: 2.0.0
      gitpython: 2.1.0
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.24.0
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12+ (default, Sep  1 2016, 20:27:38)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.5
 
System Versions:
           dist: debian stretch/sid 
        machine: armv6l
        release: 4.4.32+
         system: Linux
        version: debian stretch/sid 
```

**Comment by Ch3LL** [comment]
@tobiasBora which packages are you using to install salt on the raspberry pi? I know we test the packages we create for raspberry pi on repo.saltstack.com and I don't recall seeing this issue? I wont have access ot another raspberry pi box to test this until monday, but if you could reply with how you are installing salt that would be great. Also what raspberry pi are you using? We test with raspberry pi 2 and 3

**Comment by tobiasBora** [comment]
I'm running version 2016.3.3+ds-3 from the stretch raspbian repository:

```
$ sudo apt-cache policy salt-minion 
salt-minion:
  Installed: 2016.3.3+ds-3
  Candidate: 2016.3.3+ds-3
  Version table:
 *** 2016.3.3+ds-3 500
        500 http://mirrordirector.raspbian.org/raspbian testing/main armhf Packages
        100 /var/lib/dpkg/status

```
