### ISSUE TITLE
file.managed problem with unicode from pillar

### ISSUE THREAD

**Issue by luitzifa** [saltstack/salt#37887]
### Description of Issue/Question
When i store string values with utf-8 characters, i'm unable to use them within file.managed. But not in all cases.

pillar.get ist working:
```
root@monsieursalt[dev]:/srv/salt > salt 'mon*' pillar.get foobar:bar1
monsieursalt.internal:
    srtg'ft€@µ§edg!"$%&/()=?`sg
```

### Setup
```
######### pillar/foo.sls #########
# -*- coding: utf-8 -*-
foobar:
  bar1: srtg'ft€@µ§edg!"$%&/()=?`sg
  bar2: §srtg'ft€@µ§edg!"$%&/()=?`sg
  bar3: srtgftedgsg
  bar4: rtgsedrtgsfdgdsrf

######### pillar/top.sls #########
base:
  '*':
    - foo

######### salt/file.jinja #########
{{ salt['pillar.get']('foobar:bar1', 'failed to get pillar') }}

######### salt/file.utf8 #########
# -*- coding: utf-8 -*-
foobar:
  bar1: §srtg'ft€@µ§edg!"$%&/()=?`sg
  bar2: asdfghjghds
  bar3: srtgftedgsg
  bar4: rtgsedrtgsfdgdsrf

######### salt/foo1.sls #########
/tmp/test1:
  file.managed:
    - contents_pillar: foobar:bar1

######### salt/foo2.sls #########
/tmp/test2:
  file.managed:
    - contents: {{ salt['pillar.get']('foobar:bar1', '') }}

######### salt/foo3.sls #########
/tmp/test3:
  file.managed:
    - source: salt://file.jinja
    - template: jinja

######### salt/foo4.sls #########
/tmp/test4:
  file.managed:
    - source: salt://file.utf8

######### salt/top.sls #########
base:
  '*':
    - foo1
    - foo2
    - foo3
    - foo4
```

### Steps to Reproduce Issue
**contents_pillar is working:**
```
root@monsieursalt[dev]:/srv/salt > salt 'mon*' state.sls foo1
monsieursalt.internal:
----------
          ID: /tmp/test1
    Function: file.managed
      Result: True
     Comment: File /tmp/test1 updated
     Started: 16:22:16.600100
    Duration: 47.092 ms
     Changes:   
              ----------
              diff:
                  New file

Summary for monsieursalt.internal
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  47.092 ms
```
**contents with jinja not:**
```
root@monsieursalt[dev]:/srv/salt > salt 'mon*' state.sls foo2
monsieursalt.internal:
    Data failed to compile:
----------
    Rendering SLS 'base:foo2' failed: Jinja error: 'ascii' codec can't decode byte 0xe2 in position 7: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 368, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 3, in top-level template code
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 7: ordinal not in range(128)

; line 3

---
/tmp/test2:
  file.managed:
    - contents: {{ salt['pillar.get']('foobar:bar1', '') }}    <======================

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 368, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
[...]
---
ERROR: Minions returned with non-zero exit code
```
**template-file with jinja not:**
```
root@monsieursalt[dev]:/srv/salt > salt 'mon*' state.sls foo3
monsieursalt.internal:
----------
          ID: /tmp/test3
    Function: file.managed
      Result: False
     Comment: Unable to manage file: Jinja error: 'ascii' codec can't decode byte 0xe2 in position 7: ordinal not in range(128)
              Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 368, in render_jinja_tmpl
                  output = template.render(**decoded_context)
                File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
                  return self.environment.handle_exception(exc_info, True)
                File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 754, in handle_exception
                  reraise(exc_type, exc_value, tb)
                File "<template>", line 1, in top-level template code
              UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 7: ordinal not in range(128)
              
              ; line 1
              
              ---
              {{ salt['pillar.get']('foobar:bar1', 'failed to get pillar') }}    <======================
              
              Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 368, in render_jinja_tmpl
                  output = template.render(**decoded_context)
                File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
              [...]
              ---
     Started: 16:22:30.039266
    Duration: 61.106 ms
     Changes:   

Summary for monsieursalt.internal
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:  61.106 ms
ERROR: Minions returned with non-zero exit code
```
**just file from salt-filesystem obviously works:**
```
root@monsieursalt[dev]:/srv/salt > salt 'mon*' state.sls foo4
monsieursalt.internal:
----------
          ID: /tmp/test4
    Function: file.managed
      Result: True
     Comment: File /tmp/test4 updated
     Started: 16:22:32.009920
    Duration: 44.473 ms
     Changes:   
              ----------
              diff:
                  New file
              mode:
                  0644

Summary for monsieursalt.internal
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  44.473 ms
```

### Versions Report
master/minion on same host
```
Salt Version:
           Salt: 2016.3.4
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.3.7
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.24.0
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-47-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by luitzifa** [comment]
Updated salt to current rc2 and got same results:

```
root@monsieursalt[dev]:~ > rm -rf /tmp/test?

root@monsieursalt[dev]:~ > salt 'mon*' state.sls foo1
monsieursalt.internal:
----------
          ID: /tmp/test1
    Function: file.managed
      Result: True
     Comment: File /tmp/test1 updated
     Started: 16:46:51.954611
    Duration: 7.021 ms
     Changes:   
              ----------
              diff:
                  New file

Summary for monsieursalt.internal
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   7.021 ms

root@monsieursalt[dev]:~ > salt 'mon*' state.sls foo2
monsieursalt.internal:
    Data failed to compile:
----------
    Rendering SLS 'base:foo2' failed: Jinja error: 'ascii' codec can't decode byte 0xe2 in position 7: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 368, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 3, in top-level template code
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 7: ordinal not in range(128)

; line 3

---
/tmp/test2:
  file.managed:
    - contents: {{ salt['pillar.get']('foobar:bar1', '') }}    <======================

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 368, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
[...]
---
ERROR: Minions returned with non-zero exit code

root@monsieursalt[dev]:~ > salt 'mon*' state.sls foo3
monsieursalt.internal:
----------
          ID: /tmp/test3
    Function: file.managed
      Result: False
     Comment: Unable to manage file: Jinja error: 'ascii' codec can't decode byte 0xe2 in position 7: ordinal not in range(128)
              Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 368, in render_jinja_tmpl
                  output = template.render(**decoded_context)
                File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
                  return self.environment.handle_exception(exc_info, True)
                File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 754, in handle_exception
                  reraise(exc_type, exc_value, tb)
                File "<template>", line 1, in top-level template code
              UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 7: ordinal not in range(128)
              
              ; line 1
              
              ---
              {{ salt['pillar.get']('foobar:bar1', 'failed to get pillar') }}    <======================
              
              Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 368, in render_jinja_tmpl
                  output = template.render(**decoded_context)
                File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
              [...]
              ---
     Started: 16:46:57.283693
    Duration: 39.461 ms
     Changes:   

Summary for monsieursalt.internal
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:  39.461 ms
ERROR: Minions returned with non-zero exit code

root@monsieursalt[dev]:~ > salt 'mon*' state.sls foo4
monsieursalt.internal:
----------
          ID: /tmp/test4
    Function: file.managed
      Result: True
     Comment: File /tmp/test4 updated
     Started: 16:46:59.159555
    Duration: 55.5 ms
     Changes:   
              ----------
              diff:
                  New file
              mode:
                  0644

Summary for monsieursalt.internal
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  55.500 ms

root@monsieursalt[dev]:~ > salt --versions-report
Salt Version:
           Salt: 2016.11.0rc2
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.3.7
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.24.0
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-47-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by luitzifa** [comment]
Different results on Fedora and salt 2016.11.0 (not rc2) from pip:
```
[root@casteblack:~]
# salt-call --local state.sls foo1
[ERROR   ] Unable to manage file: 'ascii' codec can't encode character u'\u20ac' in position 7: ordinal not in range(128)
local:
----------
          ID: /tmp/test1
    Function: file.managed
      Result: False
     Comment: Unable to manage file: 'ascii' codec can't encode character u'\u20ac' in position 7: ordinal not in range(128)
     Started: 16:55:23.497153
    Duration: 7.13 ms
     Changes:   

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   7.130 ms

[root@casteblack:~]
# salt-call --local state.sls foo2
[ERROR   ] Unable to manage file: 'ascii' codec can't encode character u'\u20ac' in position 7: ordinal not in range(128)
local:
----------
          ID: /tmp/test2
    Function: file.managed
      Result: False
     Comment: Unable to manage file: 'ascii' codec can't encode character u'\u20ac' in position 7: ordinal not in range(128)
     Started: 16:55:25.656501
    Duration: 6.901 ms
     Changes:   

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   6.901 ms

[root@casteblack:~]
# salt-call --local state.sls foo3
local:
----------
          ID: /tmp/test3
    Function: file.managed
      Result: True
     Comment: File /tmp/test3 updated
     Started: 16:55:27.329333
    Duration: 12.859 ms
     Changes:   
              ----------
              diff:
                  New file
              mode:
                  0664

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  12.859 ms

[root@casteblack:~]
# salt-call --local state.sls foo4
local:
----------
          ID: /tmp/test4
    Function: file.managed
      Result: True
     Comment: File /tmp/test4 updated
     Started: 16:55:29.322574
    Duration: 11.154 ms
     Changes:   
              ----------
              diff:
                  New file
              mode:
                  0664

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  11.154 ms

[root@casteblack:~]
# salt-call --versions-report
Salt Version:
           Salt: 2016.11.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Sep 29 2016, 13:30:34)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.6
 
System Versions:
           dist: fedora 24 Twenty Four
        machine: x86_64
        release: 4.8.6-201.fc24.x86_64
         system: Linux
        version: Fedora 24 Twenty Four
 
```

**Comment by gtmanfred** [comment]
Can you test if enabling the `yaml_utf8: True` option fixes this?  https://docs.saltstack.com/en/latest/ref/configuration/master.html#yaml-utf8

**Comment by luitzifa** [comment]
I tried with , same result:

```
root@testhost[dev]:~ > grep yaml_utf8 /etc/salt/master.d/mw.conf 
yaml_utf8: True
root@testhost[dev]:~ > systemctl stop salt-master
root@testhost[dev]:~ > systemctl stop salt-minion
root@testhost[dev]:~ > rm -rf /var/cache/salt/{master,minion}/*
root@testhost[dev]:~ > systemctl start salt-master
root@testhost[dev]:~ > systemctl start salt-minion
root@testhost[dev]:~ > salt-run saltutil.sync_all
engines:
grains:
modules:
output:
pillar:
proxymodules:
queues:
renderers:
returners:
runners:
states:
wheel:
root@testhost[dev]:~ > salt '*' saltutil.sync_all
testhost:
    ----------
    beacons:
    engines:
    grains:
    log_handlers:
    modules:
    output:
    proxymodules:
    renderers:
    returners:
    sdb:
    states:
    utils:
root@testhost[dev]:~ > salt '*' saltutil.refresh_pillar
testhost:
    True
root@testhost[dev]:~ > salt '*' pillar.get foobar
testhost:
    ----------
    bar1:
        srtg'ft€@µ§edg!"$%&/()=?`sg
    bar2:
        §srtg'ft€@µ§edg!"$%&/()=?`sg
    bar3:
        srtgftedgsg
    bar4:
        rtgsedrtgsfdgdsrf
root@testhost[dev]:~ > rm -rf /tmp/test?
```
```
root@testhost[dev]:~ > salt '*' state.sls foo1
testhost:
----------
          ID: /tmp/test1
    Function: file.managed
      Result: True
     Comment: File /tmp/test1 updated
     Started: 17:08:25.644965
    Duration: 50.432 ms
     Changes:   
              ----------
              diff:
                  New file

Summary for testhost
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  50.432 ms
root@testhost[dev]:~ > salt '*' state.sls foo2
testhost:
    Data failed to compile:
----------
    Rendering SLS 'base:foo2' failed: Jinja error: 'ascii' codec can't decode byte 0xe2 in position 7: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 368, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 3, in top-level template code
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 7: ordinal not in range(128)

; line 3

---
/tmp/test2:
  file.managed:
    - contents: {{ salt['pillar.get']('foobar:bar1', '') }}    <======================

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 368, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
[...]
---
ERROR: Minions returned with non-zero exit code
root@testhost[dev]:~ > salt '*' state.sls foo3
testhost:
----------
          ID: /tmp/test3
    Function: file.managed
      Result: False
     Comment: Unable to manage file: Jinja error: 'ascii' codec can't decode byte 0xe2 in position 7: ordinal not in range(128)
              Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 368, in render_jinja_tmpl
                  output = template.render(**decoded_context)
                File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
                  return self.environment.handle_exception(exc_info, True)
                File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 754, in handle_exception
                  reraise(exc_type, exc_value, tb)
                File "<template>", line 1, in top-level template code
              UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 7: ordinal not in range(128)
              
              ; line 1
              
              ---
              {{ salt['pillar.get']('foobar:bar1', 'failed to get pillar') }}    <======================
              
              Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 368, in render_jinja_tmpl
                  output = template.render(**decoded_context)
                File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
              [...]
              ---
     Started: 17:08:30.579510
    Duration: 62.574 ms
     Changes:   

Summary for testhost
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:  62.574 ms
ERROR: Minions returned with non-zero exit code
root@testhost[dev]:~ > cat /tmp/test1 
srtg'ft€@µ§edg!"$%&/()=?`sg
```
```
root@testhost[dev]:~ > salt --versions-report
Salt Version:
           Salt: 2016.3.4
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.3.7
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.24.0
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-47-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by luitzifa** [comment]
And tested with Salt: 2016.11.0 on ubuntu xenial with and without **yaml_utf8: True** in master.conf
got same results

**Comment by gtmanfred** [comment]
I have replicated your issue in 2016.11.0

I have created the following docker image to assist with troubleshooting.  gtmanfred/issues:37887

Thanks for reporting this.

Daniel

**Comment by mirceaulinic** [comment]
FYI: I run into the same issue earlier today.

I was working on ```2016.11.0-536-gd1f24f3```, later on ```2016.11.0-549-g06abce0``` having ```yaml_utf8: True```.

For other reasons I've upgraded to ```2016.11.1-44-g0dc6d15``` and I don't see the problem  anymore (even after removing ```yaml_utf8: True``` from the master config).

**Comment by benrobinson1993** [comment]
Pretty sure I am running into the same issue. 

I have a template file, inserting pillar data into the file, 
Calling pillar.get works fine, returning the correct content. So it looks like the data is going into the pillar OK, just failing when it tries to render out the Jinja.

The State itself.
`/etc/httpd/conf.d/vhosts.conf:
  file.managed:
    - source: salt://apache-backend/files/vhosts.conf
    - user: root
    - group: root
    - mode: 0644
    - template: jinja
    - encoding: utf-8
`

Error Output from salt call.
`
----------
          ID: /etc/httpd/conf.d/vhosts.conf
    Function: file.managed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1905, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1830, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/file.py", line 2396, in managed
                  **kwargs
                File "/usr/lib/python2.7/site-packages/salt/modules/file.py", line 4726, in check_managed_changes
                  **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/modules/file.py", line 4178, in get_managed
                  **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 170, in render_tmpl
                  output = render_str(tmplstr, context, tmplpath)
                File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 439, in render_jinja_tmpl
                  trace=tracestr)
              SaltRenderError: Jinja error: 'ascii' codec can't decode byte 0xe2 in position 884: ordinal not in range(128)
              Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 390, in render_jinja_tmpl
                  output = template.render(**decoded_context)
                File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
                  return self.environment.handle_exception(exc_info, True)
                File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
                  reraise(exc_type, exc_value, tb)
                File "<template>", line 79, in top-level template code
              UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 884: ordinal not in range(128)
              
              ; line 79
              
              ---
              [...]
                      php_flag engine off
                  </DirectoryMatch>
              {% endif %}
              
              {% if cluster_data.get("apache_bottom") -%}
              {{ cluster_data.get("apache_bottom", "") }}    <======================
              {%- endif %}
              
              </VirtualHost>
              {%- endif -%}
              {% endfor -%}
              [...]
              ---
     Started: 10:12:44.250301
    Duration: 539.171 ms
     Changes:   
`


Example Pillar content of cluster_data.get("apache_bottom") which is being inserted 
`
RewriteRule "^/example/url/?" "/new/place" [R=302,L]
RewriteRule "^/example-•-with-•-characters/?" "/random/new/place" [R=302,L]
`

Salt version Info. Master
`
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: 2.7.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.24.6
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: 0.24.2
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
 
`

Salt Version Report Minion
`
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Apr 11 2018, 07:36:10)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.3.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
 
`

**Comment by benrobinson1993** [comment]
Pretty sure I am running into the same issue. 

I have a template file, inserting pillar data into the file, 
Calling pillar.get works fine, returning the correct content. So it looks like the data is going into the pillar OK, just failing when it tries to render out the Jinja.

The State itself.
```
/etc/httpd/conf.d/vhosts.conf:
  file.managed:
    - source: salt://apache-backend/files/vhosts.conf
    - user: root
    - group: root
    - mode: 0644
    - template: jinja
    - encoding: utf-8
```

Error Output from salt call.
```
------
          ID: /etc/httpd/conf.d/vhosts.conf
    Function: file.managed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1905, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1830, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/file.py", line 2396, in managed
                  **kwargs
                File "/usr/lib/python2.7/site-packages/salt/modules/file.py", line 4726, in check_managed_changes
                  **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/modules/file.py", line 4178, in get_managed
                  **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 170, in render_tmpl
                  output = render_str(tmplstr, context, tmplpath)
                File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 439, in render_jinja_tmpl
                  trace=tracestr)
              SaltRenderError: Jinja error: 'ascii' codec can't decode byte 0xe2 in position 884: ordinal not in range(128)
              Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 390, in render_jinja_tmpl
                  output = template.render(**decoded_context)
                File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
                  return self.environment.handle_exception(exc_info, True)
                File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
                  reraise(exc_type, exc_value, tb)
                File "<template>", line 79, in top-level template code
              UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 884: ordinal not in range(128)
              
              ; line 79
              
              ---
              [...]
                      php_flag engine off
                  </DirectoryMatch>
              {% endif %}
              
              {% if cluster_data.get("apache_bottom") -%}
              {{ cluster_data.get("apache_bottom", "") }}    <======================
              {%- endif %}
              
              </VirtualHost>
              {%- endif -%}
              {% endfor -%}
              [...]
              ---
     Started: 10:12:44.250301
    Duration: 539.171 ms
     Changes:   
```


Example Pillar content of cluster_data.get("apache_bottom") which is being inserted 
```
RewriteRule "^/example/url/?" "/new/place" [R=302,L]
RewriteRule "^/example-•-with-•-characters/?" "/random/new/place" [R=302,L]
```

Salt version Info. Master
```
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: 2.7.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.24.6
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: 0.24.2
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
 
```

Salt Version Report Minion
```
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Apr 11 2018, 07:36:10)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.3.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```

**Comment by rallytime** [comment]
@benrobinson1993 It is probably better to open a new PR with this information. We did a lot of work to support unicode for the 2018.3 releases, so we will want to fix this and having updated info will get some more eyes on it.
