### ISSUE TITLE
zpool state requires properties?

### ISSUE THREAD

**Issue by darkpixel** [saltstack/salt#37932]
### Description of Issue/Question
```
zpool.present:
  - name: "rpool"
  - config:
      import: true
```
Causes:
```
          ID: redacted
    Function: zpool.present
        Name: rpool
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/var/tmp/.root_28dd7a_salt/py2/salt/state.py", line 1733, in call
                  **cdata['kwargs'])
                File "/var/tmp/.root_28dd7a_salt/py2/salt/loader.py", line 1653, in wrapper
                  return f(*args, **kwargs)
                File "/var/tmp/.root_28dd7a_salt/py2/salt/states/zpool.py", line 184, in present
                  for prop in properties:
              TypeError: 'NoneType' object is not iterable
     Started: 13:51:45.633363
    Duration: 22.826 ms
     Changes:   
----------
```

I have to tweak the config to this:
```
  zpool.present:
    - name: "rpool"
    - properties:
        comment: "why do I need a comment here"
    - config:
        import: true
```

I don't think properties should be required.

### Versions Report
```
Salt Version:
           Salt: 2016.3.4
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: 3.5.0
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.6 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.6 
 ```

Probably need to check if properties is not None before use here:
https://github.com/saltstack/salt/blob/develop/salt/states/zpool.py#L199

**Comment by gtmanfred** [comment]
Thanks for the pull request fixing this issue!

Daniel
