### ISSUE TITLE
ssh_known_hosts.present is failing when checking key/host

### ISSUE THREAD

**Issue by djacobs2016** [saltstack/salt#37948]
### Description of Issue/Question
ssh_known_hosts.present is throwing an error
### Setup

```
bitbucket.org:
    ssh_known_hosts:
      - present
      - user: user
      - fingerprint: 97:8c:1b:f2:6f:14:6b:5c:3b:ec:aa:46:46:74:7c:40
      - key: bitbucket.org,131.103.20.167 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==
      - require:
        - user: user
```

produces this error:

```
   ID: bitbucket.org
    Function: ssh_known_hosts.present
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.6/site-packages/salt/state.py", line 1744, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.6/site-packages/salt/loader.py", line 1702, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib64/python2.6/contextlib.py", line 34, in __exit__
                  self.gen.throw(type, value, traceback)
                File "/usr/lib/python2.6/site-packages/salt/utils/context.py", line 48, in func_globals_inject
                  yield
                File "/usr/lib/python2.6/site-packages/salt/loader.py", line 1702, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.6/site-packages/salt/states/ssh_known_hosts.py", line 142, in present
                  timeout=timeout)
                File "/usr/lib/python2.6/site-packages/salt/modules/ssh.py", line 1053, in set_known_host
                  cmd_result = __salt__['ssh.hash_known_hosts'](user=user, config=full)
                File "<string>", line 2, in hash_known_hosts
                File "/usr/lib/python2.6/site-packages/salt/utils/decorators/__init__.py", line 186, in wrapped
                  return function(*args, **kwargs)
                File "/usr/lib/python2.6/site-packages/salt/modules/ssh.py", line 1168, in hash_known_hosts
                  os.stat(full, origmode)
              TypeError: stat() takes exactly 1 argument (2 given)
     Started: 14:15:46.412315
    Duration: 21.117 ms
     Changes:
```

### Steps to Reproduce Issue
I have a this in a global state.  pretty easy to reproduce.

### Versions Report

```
Salt Version:
           Salt: 2016.11.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.9 (unknown, Sep  1 2016, 23:34:36)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist:
        machine: x86_64
        release: 4.4.30-32.54.amzn1.x86_64
         system: Linux
        version: Not Installed
```

We just updated our environment to the latest version.  This was working before that.

**Comment by Ch3LL** [comment]
Looks like I'm able to replicate this and the first bad commit is: 4c691cf51b1c7eadf0890e58503ebd6e5af81de7

Here is a docker container for anyone to quickly replicate:

1. `docker run -it -v /home/ch3ll/git/salt/:/testing/ ch3ll/issues:37948 salt-call --local state.sls test` (where /home/ch3ll/git/salt is a local cloned salt git repo)

We will need to get this fixed up thanks.
