### ISSUE TITLE
influxdb_user.present does not pass client_args

### ISSUE THREAD

**Issue by stefan-as** [saltstack/salt#37996]
### Description of Issue/Question

There are several calls to influxdb execution modules missing the **client_args, what results in failing state runs in cases where additional client arguments are needed to connect to the database.

https://github.com/saltstack/salt/blob/2016.11/salt/states/influxdb_user.py#L24
https://github.com/saltstack/salt/blob/2016.11/salt/states/influxdb_user.py#L81
[...]

### Setup

```
influxdb_user.present:
    - name: sensu
    - password: foobar
    - host: ip6-localhost
```

### Steps to Reproduce Issue

salt-call state.apply
(spot the host value in traceback)

```
----------
          ID: sensu_influxdb
    Function: influxdb_user.present
        Name: sensu
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1744, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1702, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/influxdb_user.py", line 72, in present
                  changes = _changes(name, admin)
                File "/usr/lib/python2.7/dist-packages/salt/states/influxdb_user.py", line 24, in _changes
                  existing_user = __salt__['influxdb.user_info'](name)
                File "/usr/lib/python2.7/dist-packages/salt/modules/influx.py", line 198, in user_info
                  matching_users = (user for user in list_users(**client_args)
                File "/usr/lib/python2.7/dist-packages/salt/modules/influx.py", line 163, in list_users
                  return client.get_list_users()
                File "/usr/lib/python2.7/dist-packages/influxdb/client.py", line 633, in get_list_users
                  return list(self.query("SHOW USERS").get_points())
                File "/usr/lib/python2.7/dist-packages/influxdb/client.py", line 325, in query
                  expected_response_code=expected_response_code
                File "/usr/lib/python2.7/dist-packages/influxdb/client.py", line 241, in request
                  raise e
              ConnectionError: HTTPConnectionPool(host='localhost', port=8086): Max retries exceeded with url: /query?q=SHOW+USERS (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f45d18b8350>: Failed to establish a new connection: [Errno 111] Connection refused',))
     Started: 14:10:02.779676
    Duration: 9098882.04 ms
     Changes:   
----------
```

### Versions Report

```
Salt Version:
           Salt: 2016.11.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-47-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by Ch3LL** [comment]
@stefan-as looks like this was added here: 932fc681  and is new in 2016.11.0.

Looks to be an easy enough fix. If you want to take a stab please feel free. Also is it just that `influxdb_user` state module that is effected by this?

**Comment by rallytime** [comment]
@stefan-as The changes in #38695 should alleviate this issue. Can you give that a try and let us know how it goes?
