### ISSUE TITLE
[2016.11.0] Salt-cloud throws TypeError exception

### ISSUE THREAD

**Issue by ezh** [saltstack/salt#38048]
### Description of Issue/Question

`./salt-cloud -p salt-this-machine my-machine` stops execution with `TypeError` exception with `python 3.5.2`

### Steps to Reproduce Issue
run any configuration with command `./salt-cloud -p salt-this-machine my-machine` and `saltify` provider/driver

```
2016-11-28 13:14:42,681 [salt.cloud.cli   ][ERROR   ][75945] There was a profile error: a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "/Users/aaksenov/.virtualenvs/puppets/lib/python3.5/site-packages/salt/cloud/cli.py", line 284, in run
    self.config.get('names')
  File "/Users/aaksenov/.virtualenvs/puppets/lib/python3.5/site-packages/salt/cloud/__init__.py", line 1457, in run_profile
    ret[name] = self.create(vm_)
  File "/Users/aaksenov/.virtualenvs/puppets/lib/python3.5/site-packages/salt/cloud/__init__.py", line 1287, in create
    output = self.clouds[func](vm_)
  File "/Users/aaksenov/.virtualenvs/puppets/lib/python3.5/site-packages/salt/cloud/clouds/saltify.py", line 63, in create
    ret = __utils__['cloud.bootstrap'](vm_, __opts__)
  File "/Users/aaksenov/.virtualenvs/puppets/lib/python3.5/site-packages/salt/utils/cloud.py", line 532, in bootstrap
    deployed = deploy_script(**deploy_kwargs)
  File "/Users/aaksenov/.virtualenvs/puppets/lib/python3.5/site-packages/salt/utils/cloud.py", line 1332, in deploy_script
    ssh_file(opts, '{0}/minion.pem'.format(tmp_dir), minion_pem, ssh_kwargs)
  File "/Users/aaksenov/.virtualenvs/puppets/lib/python3.5/site-packages/salt/utils/cloud.py", line 1939, in ssh_file
    return sftp_file(dest_path, contents, kwargs, local_file)
  File "/Users/aaksenov/.virtualenvs/puppets/lib/python3.5/site-packages/salt/utils/cloud.py", line 1957, in sftp_file
    os.write(tmpfd, contents)
TypeError: a bytes-like object is required, not 'str'
```

### Versions Report
```
python -V
Python 3.5.2
```

```
Salt Version:
           Salt: 2016.11.0rc2-39-g3835f91

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 3.5.2 (default, Nov 12 2016, 15:19:34)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.6

System Versions:
           dist:
        machine: x86_64
        release: 14.5.0
         system: Darwin
        version: 10.10.5 x86_64
```

**Comment by ezh** [comment]
Pull request will be ready within a reasonable time.

**Comment by Ch3LL** [comment]
@ezh thanks for the PR! once it has been reviewed/merged please feel free to close this issue or we can.
