### ISSUE TITLE
[2016.11.0] Salt-cloud throws UnicodeDecodeError exception

### ISSUE THREAD

**Issue by ezh** [saltstack/salt#38070]
### Description of Issue/Question
`salt-cloud` stops execution of bootstrap sequence with `UnicodeDecodeError` with `python 3.5.2` if there is a broken utf-8 output from a remote server. 

### Steps to Reproduce Issue

Find buggy server that has broken utf-8 byte sequence because of incorrect shell login/logoff/profile script. Try to bootstrap it with salt-cloud. Get exception with UnicodeDecodeError at the beginning/middle/end of process. 

```
[ERROR   ] There was a profile error: 'utf-8' codec can't decode byte 0xd0 in position 1023: unexpected end of data
Traceback (most recent call last):
  File "/Users/aaksenov/.virtualenvs/puppets/lib/python3.5/site-packages/salt/cloud/cli.py", line 284, in run
    self.config.get('names')
  File "/Users/aaksenov/.virtualenvs/puppets/lib/python3.5/site-packages/salt/cloud/__init__.py", line 1457, in run_profile
    ret[name] = self.create(vm_)
  File "/Users/aaksenov/.virtualenvs/puppets/lib/python3.5/site-packages/salt/cloud/__init__.py", line 1287, in create
    output = self.clouds[func](vm_)
  File "/Users/aaksenov/.virtualenvs/puppets/lib/python3.5/site-packages/salt/cloud/clouds/saltify.py", line 64, in create
    ret = __utils__['cloud.bootstrap'](vm_, __opts__)
  File "/Users/aaksenov/.virtualenvs/puppets/lib/python3.5/site-packages/salt/utils/cloud.py", line 532, in bootstrap
    deployed = deploy_script(**deploy_kwargs)
  File "/Users/aaksenov/.virtualenvs/puppets/lib/python3.5/site-packages/salt/utils/cloud.py", line 1491, in deploy_script
    if script_args:
  File "/Users/aaksenov/.virtualenvs/puppets/lib/python3.5/site-packages/salt/utils/cloud.py", line 2225, in root_cmd
    retcode = _exec_ssh_cmd(cmd, allow_failure=allow_failure, **kwargs)
  File "/Users/aaksenov/.virtualenvs/puppets/lib/python3.5/site-packages/salt/utils/cloud.py", line 1777, in _exec_ssh_cmd
    stdout, stderr = proc.recv()
  File "/Users/aaksenov/.virtualenvs/puppets/lib/python3.5/site-packages/salt/utils/vt.py", line 306, in recv
    return self._recv(maxsize)
  File "/Users/aaksenov/.virtualenvs/puppets/lib/python3.5/site-packages/salt/utils/vt.py", line 674, in _recv
    os.read(self.child_fd, maxsize)
  File "/Users/aaksenov/.virtualenvs/puppets/lib/python3.5/site-packages/salt/utils/__init__.py", line 2980, in to_str
    return s.decode(encoding or __salt_system_encoding__)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 1023: unexpected end of data
``` 

### Versions Report

```
python -V
Python 3.5.2
```

```
Salt Version:
           Salt: 2016.11.0rc2-39-g3835f91

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 3.5.2 (default, Nov 12 2016, 15:19:34)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.6

System Versions:
           dist:
        machine: x86_64
        release: 14.5.0
         system: Darwin
        version: 10.10.5 x86_64
```

**Comment by ezh** [comment]
Pull request will be ready within a reasonable time.

**Comment by gtmanfred** [comment]
Thanks for providing a PR for this.
