### ISSUE TITLE
Lack of file existence check in ini_manage module

### ISSUE THREAD

**Issue by Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk** [saltstack/salt#38154]
When I apply `ini` state to a nonexistent file I get python exception. I think it is better to check whether the file exists and output a proper error. Ini file may not exist on a clean server where we install package first and then edit its config. In this case test mode will always be broken what will confuse the sysadmin.
Master and minion version - 2016.11.0 (latest).

php-ini.sls
```yaml
php-ini:
  ini.options_present:
    - name: /etc/php.ini-nonexistent
    - sections:
        PHP:
          short_open_tag:                      On
```

Test mode command:
```
# salt --state-verbose=true --state-output=full 'minion' state.sls php-ini test=true
minion:
----------
          ID: php-ini
    Function: ini.options_present
        Name: /etc/php.ini-nonexistent
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1744, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1702, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/ini_manage.py", line 59, in options_present
                  cur_section = __salt__['ini.get_section'](name, section, separator)
                File "/usr/lib/python2.7/site-packages/salt/modules/ini_manage.py", line 158, in get_section
                  inifile = _Ini.get_ini_file(file_name, separator=separator)
                File "/usr/lib/python2.7/site-packages/salt/modules/ini_manage.py", line 409, in get_ini_file
                  inifile.refresh()
                File "/usr/lib/python2.7/site-packages/salt/modules/ini_manage.py", line 375, in refresh
                  "Exception: {1}".format(self.name, exc)
              CommandExecutionError: Unable to open file '/etc/php.ini-nonexistent'. Exception: [Errno 2] No such file or directory: '/etc/php.ini-nonexistent'
     Started: 13:53:47.482544
    Duration: 8.91 ms
     Changes:   

Summary for minion
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   8.910 ms
```

**Comment by Ch3LL** [comment]
@Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk looks like this is a duplciate of #34236

I will close this issue so we can track the issue there.
