### ISSUE TITLE
No such file or directory: '/etc/salt/pki/minion/minion.pub' 

### ISSUE THREAD

**Issue by himadrisingh001** [saltstack/salt#38197]
### Description of Issue/Question

Some of the minions fail with the following trace. 
```
+ salt-call -l debug grains.setval <key> <value>
[DEBUG ] Reading configuration from /etc/salt/minion
[DEBUG ] Including configuration from '/etc/salt/minion.d/log.conf'
[DEBUG ] Reading configuration from /etc/salt/minion.d/log.conf
[DEBUG ] Including configuration from '/etc/salt/minion.d/master.conf'
[DEBUG ] Reading configuration from /etc/salt/minion.d/master.conf
[DEBUG ] Including configuration from '/etc/salt/minion.d/scaling.conf'
[DEBUG ] Reading configuration from /etc/salt/minion.d/scaling.conf
[DEBUG ] Including configuration from '/etc/salt/minion.d/signkey.conf'
[DEBUG ] Reading configuration from /etc/salt/minion.d/signkey.conf
[DEBUG ] Using cached minion ID from /etc/salt/minion_id: <minion-id>
[DEBUG ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG ] Reading configuration from /etc/salt/minion
[DEBUG ] Including configuration from '/etc/salt/minion.d/log.conf'
[DEBUG ] Reading configuration from /etc/salt/minion.d/log.conf
[DEBUG ] Including configuration from '/etc/salt/minion.d/master.conf'
[DEBUG ] Reading configuration from /etc/salt/minion.d/master.conf
[DEBUG ] Including configuration from '/etc/salt/minion.d/scaling.conf'
[DEBUG ] Reading configuration from /etc/salt/minion.d/scaling.conf
[DEBUG ] Including configuration from '/etc/salt/minion.d/signkey.conf'
[DEBUG ] Reading configuration from /etc/salt/minion.d/signkey.conf
[DEBUG ] Please install 'virt-what' to improve results of the 'virtual' grain.
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', '<minion-id>', '<master>')
[INFO    ] Generating keys: /etc/salt/pki/minion
[DEBUG   ] Generated random reconnect delay between '3000ms' and '180000ms' (59295)
[DEBUG   ] Setting zmq_reconnect_ivl to '59295ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '180000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', '<minion-id>', 'tcp://<master>', 'clear')
[ERROR   ] Exception in callback <functools.partial object at 0x7ff3db2ed680>
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/ioloop.py", line 592, in _run_callback
    ret = callback()
  File "/usr/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/tornado/ioloop.py", line 598, in <lambda>
    self.add_future(ret, lambda f: f.result())
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.7/dist-packages/salt/crypt.py", line 447, in _authenticate
    creds = yield self.sign_in(channel=channel)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 230, in wrapper
    yielded = next(result)
  File "/usr/lib/python2.7/dist-packages/salt/crypt.py", line 515, in sign_in
    sign_in_payload = self.minion_sign_in_payload()
  File "/usr/lib/python2.7/dist-packages/salt/crypt.py", line 639, in minion_sign_in_payload
    with salt.utils.fopen(self.pub_path) as f:
  File "/usr/lib/python2.7/dist-packages/salt/utils/__init__.py", line 1216, in fopen
    fhandle = open(*args, **kwargs)
IOError: [Errno 2] No such file or directory: '/etc/salt/pki/minion/minion.pub'
Terminated
```

### Setup
*Minion Configs*
```
$ cat /etc/salt/minion.d/*
log_file: file:///dev/log
log_datefmt: '%Y-%m-%dT%H:%M:%SZ'
log_fmt_logfile: '%(name)s %(message)s'
log_fmt_console: '%(asctime)s,%(msecs)03.0f [%(name)-10s][%(levelname)-8s] %(message)s'

master: <salt-master>

open_mode: True
#scaling issues
random_reauth_delay: 180

recon_default: 3000
recon_max: 177000
recon_randomize: True

keysize: 2048
hash_type: sha256
schedule:
  __mine_interval: {function: mine.update, jid_include: true, maxrunning: 2, minutes: 60,
    return_job: false}
verify_master_pubkey_sign: True
```
*Master Configs*
```
$ cat /etc/salt/master.d/*
log_file: file:///dev/log
log_datefmt: '%Y-%m-%dT%H:%M:%SZ'
log_fmt_logfile: '%(name)s %(message)s'
log_fmt_console: '%(asctime)s,%(msecs)03.0f [%(name)-10s][%(levelname)-8s] %(message)s'
master_sign_pubkey: True
master_sign_key_name: <salt-key-name>
```

### Steps to Reproduce Issue
Its not consistent with the error, let me know if we can get any other debug logging or details. 

### Versions Report
*Minions*
```
$ salt-call --versions-report
Salt Version:
           Salt: 2015.8.12

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.4.0-47-generic
         system: Ubuntu 14.04 trusty
```
*master*
```
$ salt --versions-report
Salt Version:
           Salt: 2015.8.12

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: 0.1.3
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-63-generic
         system: Ubuntu 14.04 trusty
```

**Comment by cachedout** [comment]
Interesting. Are these fresh installations of Salt? Did it work and then stop or in these cases did it never work at all?

**Comment by himadrisingh001** [comment]
We have these in-built into AMI and have auto-scaling enabled. 

Few of the newly launched salt-minions fail with this error. Its not reproducible consistently though.

**Comment by cachedout** [comment]
After they launch and fail with this error, do they continue to fail or is that failure from that point forward intermittent?
