### ISSUE TITLE
TypeError: can't serialize <libcloud.compute.drivers.gce.GCENodeDriver object at 0x3b00390>

### ISSUE THREAD

**Issue by maratsh** [saltstack/salt#38195]
### Description of Issue/Question
I'm trying to deploy vm in gce via cloud states and I face with error
```TypeError: can't serialize <libcloud.compute.drivers.gce.GCENodeDriver object at 0x3b00390>```
### Setup
Install master and salt-cloud
cloud.sls
```
cloud:
  ssh_key_name: saltstack
  ssh_key_file: /root/.ssh/id_rsa
  update_cachedir: True
  diff_cache_events: True
  change_password: True

  providers:
    paas-gce-acme:
      driver: gce
       some gce options
```

paas.sls
```
testing:
  cloud:
    - present
    - cloud_provider:  paas-gce-acme
    - image: centos-7
    - size: f1-micro
    - location: europe-west1-b
    - network: default
    - use_persistent_disk: True
```

### Steps to Reproduce Issue
salt-run state.sls paas  -l debug
```
[DEBUG   ] Rendered data from file: /var/cache/salt/master/files/base/paas/init.sls:


testing:
  cloud:
    - present
    - cloud_provider:  paas-gce-acme
    - image: centos-7
    - size: f1-micro
    - location: europe-west1-b
    - network: default
    - use_persistent_disk: True

[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 1744, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1702, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/states/cloud.py", line 117, in present
    if __salt__['cloud.has_instance'](name=name, provider=None):
  File "/usr/lib/python2.7/site-packages/salt/modules/cloud.py", line 150, in has_instance
    data = get_instance(name, provider)
  File "/usr/lib/python2.7/site-packages/salt/modules/cloud.py", line 176, in get_instance
    data = action(fun='show_instance', names=[name], provider=provider)
  File "/usr/lib/python2.7/site-packages/salt/modules/cloud.py", line 237, in action
    info = client.action(fun, cloudmap, names, provider, instance, kwargs)
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 485, in action
    return mapper.do_action(names, kwargs)
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1532, in do_action
    vm_name, call='action'
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/gce.py", line 284, in show_instance
    __utils__['cloud.cache_node'](node, __active_provider_name__, __opts__)
  File "/usr/lib/python2.7/site-packages/salt/utils/cloud.py", line 2902, in cache_node
    msgpack.dump(node, fh_)
  File "/usr/lib64/python2.7/site-packages/msgpack/__init__.py", line 38, in pack
    stream.write(packer.pack(o))
  File "msgpack/_packer.pyx", line 231, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:3661)
  File "msgpack/_packer.pyx", line 233, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:3503)
  File "msgpack/_packer.pyx", line 192, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:2657)
  File "msgpack/_packer.pyx", line 192, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:2657)
  File "msgpack/_packer.pyx", line 192, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:2657)
  File "msgpack/_packer.pyx", line 228, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:3382)
TypeError: can't serialize <libcloud.compute.drivers.gce.GCENodeDriver object at 0x3b00390>

[INFO    ] Completed state [testing] at time 18:22:50.739519 duration_in_ms=45210.669
[DEBUG   ] File /var/cache/salt/master/accumulator/61189008 does not exist, no need to cleanup.
[DEBUG   ] LazyLoaded config.option
```
### Versions Report
```
salt-run --versions-report
Salt Version:
           Salt: 2016.11.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.36.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
 
[root@localhost ~]# salt --versions-report
Salt Version:
           Salt: 2016.11.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.36.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

```
```
pip freeze
apache-libcloud==1.4.0
Babel==0.9.6
backports.ssl-match-hostname==3.4.0.2
chardet==2.2.1
configobj==4.7.2
decorator==3.4.0
futures==3.0.5
iniparse==0.4
Jinja2==2.7.2
kitchen==1.1.1
MarkupSafe==0.11
msgpack-python==0.4.8
perf==0.1
pycrypto==2.6.1
pycurl==7.19.0
pygobject==3.14.0
pygpgme==0.3
pyliblzma==0.5.3
pyudev==0.15
pyxattr==0.5.1
PyYAML==3.11
pyzmq==15.3.0
requests==2.6.0
salt==2016.11.0
six==1.9.0
slip==0.4.0
slip.dbus==0.4.0
tornado==4.2.1
urlgrabber==3.10
urllib3==1.10.2
yum-metadata-parser==1.1.4
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by cachedout** [comment]
This might be something that @erjohnso can peek at or @techhat

**Comment by gtmanfred** [comment]
This is being caused by the caching of an object into msgpack.

You could get past the error by setting `update_cachedir` to False.  But we just need to make sure the `node` object gets turned into a serializable object before it gets passed to the cache function.

**Comment by maratsh** [comment]
Where I should put this options?

**Comment by gtmanfred** [comment]
salt/cloud/clouds/gce.py line 284.

node needs to be changed to a serializable data structure.  you might be able to just change node to `node.__dict__`

**Comment by maratsh** [comment]
It does not help.
```
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 1744, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1702, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/states/cloud.py", line 117, in present
    if __salt__['cloud.has_instance'](name=name, provider=None):
  File "/usr/lib/python2.7/site-packages/salt/modules/cloud.py", line 150, in has_instance
    data = get_instance(name, provider)
  File "/usr/lib/python2.7/site-packages/salt/modules/cloud.py", line 176, in get_instance
    data = action(fun='show_instance', names=[name], provider=provider)
  File "/usr/lib/python2.7/site-packages/salt/modules/cloud.py", line 237, in action
    info = client.action(fun, cloudmap, names, provider, instance, kwargs)
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 485, in action
    return mapper.do_action(names, kwargs)
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1532, in do_action
    vm_name, call='action'
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/gce.py", line 285, in show_instance
    __utils__['cloud.cache_node'](node.__dict__, __active_provider_name__, __opts__)
AttributeError: 'dict' object has no attribute '__dict__'
```

**Comment by gtmanfred** [comment]
can you add a log.debug(node) on the line before that, There has to be an entry in the node dictionary which is an object and not a dictionary.  I don't anything setup for gce right now or I would test it.  But you could remove the `libcloud.compute.drivers.gce.GCENodeDriver` object from the node dictionary, or use `__dict__` on it.

**Comment by maratsh** [comment]
```
{'private_ips': [u'10.240.0.2'], 'name': u'testing', 'extra': {'status': u'RUNNING', 'kind': u'compute#instance', 'machineType': u'https://www.googleapis.com/compute/v1/projects/acme-saas/zones/europe-west1-b/machineTypes/f1-micro', 'description': None, 'zone': {'status': u'UP', 'maintenance_windows': None, 'name': u'europe-west1-b', 'extra': {'region': u'https://www.googleapis.com/compute/v1/projects/acme-saas/regions/europe-west1', 'creationTimestamp': u'2016-06-14T17:29:18.761-07:00', 'description': u'europe-west1-b', 'selfLink': u'https://www.googleapis.com/compute/v1/projects/acme-saas/zones/europe-west1-b'}, 'deprecated': None, 'driver': <libcloud.compute.drivers.gce.GCENodeDriver object at 0x2acb350>, 'country': u'europe', 'id': '2101'}, 'tags': [], 'deprecated': False, 'image': u'centos-7-v20161129', 'disks': [{u'index': 0, u'kind': u'compute#attachedDisk', u'autoDelete': True, u'deviceName': u'testing', u'boot': True, u'source': u'https://www.googleapis.com/compute/v1/projects/acme-saas/zones/europe-west1-b/disks/testing', u'interface': u'SCSI', u'mode': u'READ_WRITE', u'licenses': [u'https://www.googleapis.com/compute/v1/projects/centos-cloud/global/licenses/centos-7'], u'type': u'PERSISTENT'}], 'tags_fingerprint': u'42WmSpB8rSM=', 'name': u'testing', 'selfLink': u'https://www.googleapis.com/compute/v1/projects/acme-saas/zones/europe-west1-b/instances/testing', 'scheduling': {u'automaticRestart': True, u'preemptible': False, u'onHostMaintenance': u'MIGRATE'}, 'canIpForward': None, 'serviceAccounts': [{u'scopes': [u'https://www.googleapis.com/auth/devstorage.read_only'], u'email': u'1055822314842-compute@developer.gserviceaccount.com'}], 'metadata': {u'items': [{u'value': u'', u'key': u'salt-cloud-profile'}], u'kind': u'compute#metadata', u'fingerprint': u'ZgztgmyWXrQ='}, 'creationTimestamp': u'2016-12-11T10:08:53.726-08:00', 'id': u'7309022248191404250', 'statusMessage': None, 'networkInterfaces': [{u'accessConfigs': [{u'kind': u'compute#accessConfig', u'type': u'ONE_TO_ONE_NAT', u'name': u'External NAT', u'natIP': u'104.199.33.197'}], u'networkIP': u'10.240.0.2', u'network': u'https://www.googleapis.com/compute/v1/projects/acme-saas/global/networks/default', u'name': u'nic0'}]}, 'created_at': None, '_uuid': None, 'driver': <libcloud.compute.drivers.gce.GCENodeDriver object at 0x2acb350>, 'public_ips': [u'104.199.33.197'], 'id': '7309022248191404250', 'state': 'running', 'image': u'centos-7-v20161129', 'size': u'f1-micro'}
```

**Comment by gtmanfred** [comment]
yeah, delete the two driver objects from the dict.

```
diff --git a/salt/cloud/clouds/gce.py b/salt/cloud/clouds/gce.py
index 7a8a571..4689036 100644
--- a/salt/cloud/clouds/gce.py
+++ b/salt/cloud/clouds/gce.py
@@ -281,7 +281,11 @@ def show_instance(vm_name, call=None):
         )
     conn = get_conn()
     node = _expand_node(conn.ex_get_node(vm_name))
-    __utils__['cloud.cache_node'](node, __active_provider_name__, __opts__)
+    import copy
+    prunednode = copy.deepcopy(node)
+    del prunednode['driver']
+    del prunednode['extra']['zone']['driver']
+    __utils__['cloud.cache_node'](prunednode, __active_provider_name__, __opts__)
     return node

```

If you revert back to the package version, you should be able to apply the above patch with the command.

`curl -sL http://ix.io/1M8P | patch -Np1 -d /usr/lib/python2.7/site-packages/`

and then you can revert it by changing -N to -R

`curl -sL http://ix.io/1M8P | patch -Rp1 -d /usr/lib/python2.7/site-packages/`

**Comment by maratsh** [comment]
Not works :(
```
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 1744, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1702, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/states/cloud.py", line 117, in present
    if __salt__['cloud.has_instance'](name=name, provider=None):
  File "/usr/lib/python2.7/site-packages/salt/modules/cloud.py", line 150, in has_instance
    data = get_instance(name, provider)
  File "/usr/lib/python2.7/site-packages/salt/modules/cloud.py", line 176, in get_instance
    data = action(fun='show_instance', names=[name], provider=provider)
  File "/usr/lib/python2.7/site-packages/salt/modules/cloud.py", line 237, in action
    info = client.action(fun, cloudmap, names, provider, instance, kwargs)
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 485, in action
    return mapper.do_action(names, kwargs)
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1532, in do_action
    vm_name, call='action'
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/gce.py", line 285, in show_instance
    prunednode = copy.deepcopy(node)
  File "/usr/lib64/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib64/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib64/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib64/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib64/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib64/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib64/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib64/python2.7/copy.py", line 329, in _reconstruct
    y = callable(*args)
  File "/usr/lib64/python2.7/copy_reg.py", line 93, in __newobj__
    return cls.__new__(cls, *args)
TypeError: __new__() takes at least 2 arguments (1 given)



```

**Comment by maratsh** [comment]
I just delete this keys from original dict and it works :)

**Comment by gtmanfred** [comment]
Cool, this one should work too.

`curl -sL http://ix.io/1M90 | patch -Np1 -d /usr/lib/python2.7/site-packages/`

**Comment by maratsh** [comment]
Great, It works. I hope for packages with  hotfixes :+1:

**Comment by maratsh** [comment]
so, this is bug is fixed?

**Comment by gtmanfred** [comment]
This should have been in 2016.11.2

Thanks,
Daniel
