### ISSUE TITLE
salt-cloud --list-image with AWS owner=all fails 

### ISSUE THREAD

**Issue by jf** [saltstack/salt#38202]
### Description of Issue/Question

When owner is set to "all" (a valid value according to https://docs.saltstack.com/en/latest/topics/cloud/aws.html#listing-images), `salt-cloud --list-images` for an ec2 provider fails. I'm not too sure about some of the stuff I see below in debug, but this is on a pristine install of `salt-cloud`, with only 2 files, `/etc/salt/cloud.providers.d/aws.conf`, and a profile file in `/etc/salt/cloud.profiles.d/`:

```
# salt-cloud --list-images aws  -l debug
[DEBUG   ] Reading configuration from /etc/salt/cloud
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/file_roots.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/file_roots.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/ip.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/ip.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: ip-NN-NN.ec2.internal
[DEBUG   ] Missing configuration file: /etc/salt/cloud.providers
[DEBUG   ] Including configuration from '/etc/salt/cloud.providers.d/aws.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers.d/aws.conf
[DEBUG   ] Missing configuration file: /etc/salt/cloud.profiles
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/image.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/image.conf
[DEBUG   ] Configuration file path: /etc/salt/cloud
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] salt-cloud starting
[DEBUG   ] Could not LazyLoad parallels.avail_sizes: 'parallels' __virtual__ returned False
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy: 'saltify.destroy' is not available.
[DEBUG   ] Could not LazyLoad saltify.avail_sizes: 'saltify.avail_sizes' is not available.
[DEBUG   ] Could not LazyLoad saltify.avail_images: 'saltify.avail_images' is not available.
[DEBUG   ] Could not LazyLoad saltify.avail_locations: 'saltify.avail_locations' is not available.
[DEBUG   ] LazyLoaded rackspace.reboot
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] LazyLoaded rackspace.list_locations
[DEBUG   ] Using AWS endpoint: ec2.us-east-1.amazonaws.com
[DEBUG   ] AWS Request: https://ec2.us-east-1.amazonaws.com/?Action=DescribeImages&Owner=all&Version=2014-10-01
[INFO    ] Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
[DEBUG   ] Setting read timeout to None
[DEBUG   ] "GET /?Action=DescribeImages&Owner=all&Version=2014-10-01 HTTP/1.1" 400 None
[DEBUG   ] AWS Response Status Code: 400
[ERROR   ] AWS Response Status Code and Error: [400 400 Client Error: Bad Request] {'Errors': {'Error': {'Message': 'Invalid user id: "all"', 'Code': 'InvalidUserID.Malformed'}}, 'RequestID': '844b4729-0377-4766-9593-46bac4e5b1e4'}
[ERROR   ] Failed to get the output of 'ec2.avail_images()': string indices must be integers, not str
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 873, in image_list
    data[alias][driver] = self.clouds[fun]()
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 901, in avail_images
    ret[image['imageId']] = image
TypeError: string indices must be integers, not str
[DEBUG   ] LazyLoaded nested.output
aws:
    ----------
#
```

### Setup

Install salt-cloud, and set up a basic provider in `/etc/salt/cloud.providers.d`, with `owner` set to `all`.

### Steps to Reproduce Issue

Please see description. Note that this fails as well when trying `salt-cloud -f avail_images <PROVIDER-ID> owner=all`

### Versions Report

```
Salt Version:
           Salt: 2016.11.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-103-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by Ch3LL** [comment]
@jf looks like i'm able to replicate this behavior. Also looks like this is in 2016.3.4 so not a regresion into 2016.11.0.

We will need to get this fixed up thanks

**Comment by jf** [comment]
thanks, @Ch3LL ! I hope my instructions were clear enough to be able to duplicate easily.
