### ISSUE TITLE
salt-run: can't get cache.grains

### ISSUE THREAD

**Issue by pgrishin** [saltstack/salt#38216]
```
[root@salt salt]# salt-run cache.grains

[ERROR   ] Failed matching available minions with glob pattern: None
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/minions.py", line 639, in check_minions
    minions = check_func(expr, greedy)
  File "/usr/lib/python2.7/site-packages/salt/utils/minions.py", line 194, in _check_glob_minions
    return fnmatch.filter(self._pki_minions(), expr)
  File "/usr/lib64/python2.7/fnmatch.py", line 51, in filter
    res = translate(pat)
  File "/usr/lib64/python2.7/fnmatch.py", line 87, in translate
    i, n = 0, len(pat)
TypeError: object of type 'NoneType' has no len()
Exception occurred in runner cache.grains: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 395, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/runners/cache.py", line 38, in grains
    cached_grains = pillar_util.get_minion_grains()
  File "/usr/lib/python2.7/site-packages/salt/utils/master.py", line 290, in get_minion_grains
    cached_minion_grains, cached_minion_pillars = self._get_cached_minion_data(*minion_ids)
  File "/usr/lib/python2.7/site-packages/salt/utils/master.py", line 135, in _get_cached_minion_data
    if 'grains' in mdata:
TypeError: argument of type 'NoneType' is not iterable
```

```
[root@salt salt]# salt-run cache.clear_all
False
```

## Version report
```
[root@salt salt]# salt-run --versions-report
Salt Version:
           Salt: 2016.11.0

Dependency Versions:
           cffi: 0.8.6
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.21.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.4
         Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.36.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

```

**Comment by Ch3LL** [comment]
@pgrishin looks like i'm able to replicate this but only when I do not have any minions attached to the master. Is this the same case for you?

git bisect shows 6d1653d1da1ef821aaf5b807200b8fe808b93123 as the first bad commit

Here is a docker container for anyone that wants to quickly replicate the issues:

1. `docker run -it -v /home/ch3ll/git/salt/:/testing/ ch3ll/issues:38216` (where /home/ch3ll/git/salt is a local cloned git repo of salt)
2. `salt-run cache.grains`

**Comment by pgrishin** [comment]
@Ch3LL minions are attached in my case

```[root@salt ~]# salt-run manage.up | wc -l
94
[root@salt ~]# salt-run cache.clear_all | wc -l
1
[root@salt ~]# salt-run cache.clear_all
False```

**Comment by Ch3LL** [comment]
OH really okay thats not good then. Are any of your minions not running? just trying to clarify when someone would run into this issue
