### ISSUE TITLE
Salt-Cloud --list-sizes To Aliyun Cloud Failure

### ISSUE THREAD

**Issue by EMGrant** [saltstack/salt#38314]
### Description of Issue/Question

Salt-cloud doesn't work with the --list-sizes option when trying to integrate with Aliyun (Alibaba) cloud.  Everything else to work when I ask for location, images, and I haven't tried creating or deleting cloud resources yet.  I've been told by Alibaba support that Salt is using an old version of their API and it doesn't support (RAM) Resource Access Manager (Their way of securing API access).

### Steps to Reproduce Issue

```
salt-cloud --list-sizes my-alibaba-config -l debug
[DEBUG   ] Reading configuration from /etc/salt/cloud
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/em_defaults.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/em_defaults.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: rdtools.emhost.blue
[DEBUG   ] Missing configuration file: /etc/salt/cloud.providers
[DEBUG   ] Including configuration from '/etc/salt/cloud.providers.d/alibaba.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers.d/alibaba.conf
[DEBUG   ] Including configuration from '/etc/salt/cloud.providers.d/google-cnc.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers.d/google-cnc.conf
[DEBUG   ] Missing configuration file: /etc/salt/cloud.profiles
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/google-cnc.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/google-cnc.conf
[DEBUG   ] Configuration file path: /etc/salt/cloud
[INFO    ] salt-cloud starting
[DEBUG   ] Could not LazyLoad parallels.avail_sizes
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy
[DEBUG   ] Could not LazyLoad saltify.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.avail_images
[DEBUG   ] Could not LazyLoad saltify.avail_locations
[DEBUG   ] LazyLoaded rackspace.reboot
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] LazyLoaded rackspace.list_locations
[INFO    ] Starting new HTTPS connection (1): ecs.aliyuncs.com
[DEBUG   ] Setting read timeout to None
[DEBUG   ] "GET /?SignatureVersion=1.0&Format=JSON&TimeStamp=2016-12-16T16%3A06%3A53Z&AccessKeyId=<redacted>&SignatureMethod=HMAC-SHA1&Version=2013-01-10&Signature=ink0oGHGVjYBmKkETG3nGV4gFs8%3D&Action=DescribeInstanceTypes&SignatureNonce=a8dd3ba2-c3a9-11e6-943b-00155d0a5b13 HTTP/1.1" 403 None
[ERROR   ] Failed to get the output of 'aliyun.avail_sizes()': An error occurred while querying aliyun ECS. HTTP Code: 403  Error: u'{"Code":"Forbidden","HostId":"ecs.aliyuncs.com","Message":"User not authorized to operate on the specified resource.","RequestId":"1DD638D5-1CA0-43C1-8ECB-56980F6EA566"}'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 904, in size_list
    data[alias][driver] = self.clouds[fun]()
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/aliyun.py", line 177, in avail_sizes
    items = query(params=params)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/aliyun.py", line 772, in query
    request.text
SaltCloudSystemExit: An error occurred while querying aliyun ECS. HTTP Code: 403  Error: u'{"Code":"Forbidden","HostId":"ecs.aliyuncs.com","Message":"User not authorized to operate on the specified resource.","RequestId":"1DD638D5-1CA0-43C1-8ECB-56980F6EA566"}'
[DEBUG   ] LazyLoaded nested.output
```

List Locations:

```
salt-cloud --list-locations my-alibaba-config -l debug
[DEBUG   ] Reading configuration from /etc/salt/cloud
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/em_defaults.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/em_defaults.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: rdtools.emhost.blue
[DEBUG   ] Missing configuration file: /etc/salt/cloud.providers
[DEBUG   ] Including configuration from '/etc/salt/cloud.providers.d/alibaba.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers.d/alibaba.conf
[DEBUG   ] Including configuration from '/etc/salt/cloud.providers.d/google-cnc.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers.d/google-cnc.conf
[DEBUG   ] Missing configuration file: /etc/salt/cloud.profiles
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/google-cnc.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/google-cnc.conf
[DEBUG   ] Configuration file path: /etc/salt/cloud
[INFO    ] salt-cloud starting
[DEBUG   ] Could not LazyLoad parallels.avail_sizes
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy
[DEBUG   ] Could not LazyLoad saltify.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.avail_images
[DEBUG   ] Could not LazyLoad saltify.avail_locations
[DEBUG   ] LazyLoaded rackspace.reboot
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] LazyLoaded rackspace.list_locations
[INFO    ] Starting new HTTPS connection (1): ecs.aliyuncs.com
[DEBUG   ] Setting read timeout to None
[DEBUG   ] "GET /?SignatureVersion=1.0&Format=JSON&TimeStamp=2016-12-16T16%3A10%3A53Z&AccessKeyId=<redacted>&SignatureMethod=HMAC-SHA1&Version=2013-01-10&Signature=O0RKfkREsCRuwkF9iG2xpS%2BiSRM%3D&Action=DescribeRegions&SignatureNonce=38314ee2-c3aa-11e6-943b-00155d0a5b13 HTTP/1.1" 200 None
[DEBUG   ] https://ecs.aliyuncs.com/?SignatureVersion=1.0&Format=JSON&TimeStamp=2016-12-16T16%3A10%3A53Z&AccessKeyId=<redacted>&SignatureMethod=HMAC-SHA1&Version=2013-01-10&Signature=O0RKfkREsCRuwkF9iG2xpS%2BiSRM%3D&Action=DescribeRegions&SignatureNonce=38314ee2-c3aa-11e6-943b-00155d0a5b13
[DEBUG   ] LazyLoaded nested.output
my-alibaba-config:
    ----------
    aliyun:
        ----------
        ap-northeast-1:
            ----------
            LocalName:
                亚太东北 1 (东京)
            RegionId:
```

### Versions Report

I've also tested this on a newer version with the same error: salt 2016.11.1 (Carbon)

Production system version:
Salt Version:
           Salt: 2015.8.10

Dependency Versions:
         Jinja2: 2.6
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 13.1.0
         Python: 2.7.3 (default, Jun 21 2016, 18:38:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.3
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 0.3.6
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: debian 7.11
        machine: x86_64
        release: 3.2.0-4-amd64
         system: debian 7.11

**Comment by Ch3LL** [comment]
@EMGrant thanks for opening this report.

Since I do not currently have access to test this, ping @crook  it looks like you created this cloud provider. Can you verify this behavior? 

It looks like this cloud driver depends on the requests library. @EMGrant what version of requests are you currently using?
So it looks like its using requests to make the api calls not a specific python aliyun module so I'm wondering if we will need to just update the way the call is made to the api to get the list of sizes. Thanks

**Comment by EMGrant** [comment]
@Ch3LL How do I get the requests version for you?

**Comment by Ch3LL** [comment]
Looks like you are running so  just run `dpkg -l | grep -i req`

**Comment by EMGrant** [comment]
@Ch3LL - As requested:

|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
ii  python-requests                     2.0.0-1~bpo70+2                all          elegant and simple HTTP library for Python, built for human beings
ii  salt-common                         2015.8.10+ds-1                 all          shared libraries that salt requires for all packages

**Comment by crook** [comment]
@aliyun, so far I didn't use aliyun any more and have no test env. please help to take a look at the signature part.  
https://github.com/saltstack/salt/blob/develop/salt/cloud/clouds/aliyun.py#L746

**Comment by steinliber** [comment]
https://help.aliyun.com/document_detail/25497.html?spm=5176.doc25496.6.697.4coEPl this may help

**Comment by Ch3LL** [comment]
@steinliber thanks for those docs. We don't currently have a access to aliyun so anyone that wants to try to fix this please do. I will label as a bug for now.
