### ISSUE TITLE
[2016.11.1] AttributeError: 'RAETEvent' object has no attribute 'set_event_handler'

### ISSUE THREAD

**Issue by alxwr** [saltstack/salt#38392]
### Description of Issue/Question

`salt-api` seems to be unusable with RAET. Is this true, or am I missing something?

Should the combination of `salt-api` and RAET work?
If yes, how can I help to build FreeBSD support?

Or is `salt-api`+RAET something yet to be developed?

Thanks in advance!

### Setup

```yaml
# salt/master
file_roots:
  base:
    - /usr/local/etc/salt/states

pillar_roots:
  base:
    - /usr/local/etc/salt/pillar

transport: raet

timeout: 60

user: *****
group: *****

external_auth:
  pam:
    saltpad-user:
      - .*
      - '@runner'
      - '@wheel'

rest_tornado:
  port: 5417
  disable_ssl: true
  host: 127.0.1.11
  websockets: True
  cors_origin: '*' 
```

### Steps to Reproduce Issue

```bash
salt-api -l debug
```

```bash
 ~ $ curl -i http://127.0.1.11:5417
curl: (52) Empty reply from server
```

```
[CRITICAL] init a listener
[DEBUG   ] RAETEvent Using Jobber Stack at = /var/run/salt/master/master.event5442aa255e0b528165.uxd

[ERROR   ] Uncaught exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/tornado/http1connection.py", line 238, in _read_message
    delegate.finish()
  File "/usr/local/lib/python2.7/site-packages/tornado/httpserver.py", line 289, in finish
    self.delegate.finish()
  File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 2047, in finish
    self.execute()
  File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 2067, in execute
    **self.handler_kwargs)
  File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 187, in __init__
    self.initialize(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/salt/netapi/rest_tornado/saltnado.py", line 442, in initialize
    self.application.opts,
  File "/usr/local/lib/python2.7/site-packages/salt/netapi/rest_tornado/saltnado.py", line 314, in __init__
    self.event.set_event_handler(self._handle_event_socket_recv)
AttributeError: 'RAETEvent' object has no attribute 'set_event_handler'
```

### Versions Report

```
~ # salt --versions-report
Salt Version:
           Salt: 2016.11.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: 5.4.0
       dateutil: 2.5.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.5.0
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: 1.4.4
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Aug 17 2016, 03:35:48)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: 0.6.5
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.5

System Versions:
           dist:
        machine: amd64
        release: 10.3-RELEASE-p11
         system: FreeBSD
        version: Not Installed
```

**Comment by Ch3LL** [comment]
@alxwr looks like i'm able to replicate this. Also to note it seems to be working with cherrypy and not tornado.

Seems we need to bring this up to parity to work with raet.

Here is a docker container for someone to quickly repicate this issue:

1. `docker run -it -v /home/ch3ll/git/salt/:/testing/ ch3ll/issues:38392`
2. `salt-master -d; salt-api -d; salt-minion -d`
3. `curl -i http://localhost:5417`
4. `less /var/log/salt/api` and you will see the stack trace.

**Comment by Ch3LL** [comment]
Also to note this seems to be broken in 2016.3 as well.
