### ISSUE TITLE
github state can't handle users with unicode symbols

### ISSUE THREAD

**Issue by kshcherban** [saltstack/salt#38394]
### Description of Issue/Question
When you try to add github user using github state and that user has unicode characters in his profile name (like this https://github.com/nmaric) salt state fails. 

### Setup
```
nmaric_github:
  github.present:
    - name: nmaric
    - profile: some_profile
```

### Log
```
          ID: nmaric_github
    Function: github.present
        Name: nmaric
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1733, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1653, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/github.py", line 54, in present
                  target = __salt__['github.get_user'](name, profile=profile, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/github.py", line 189, in get_user
                  user = client.get_user(name)
                File "/usr/lib/python2.7/dist-packages/github/MainClass.py", line 158, in get_user
                  "/users/" + login
                File "/usr/lib/python2.7/dist-packages/github/Requester.py", line 171, in requestJsonAndCheck
                  return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
                File "/usr/lib/python2.7/dist-packages/github/Requester.py", line 212, in requestJson
                  return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
                File "/usr/lib/python2.7/dist-packages/github/Requester.py", line 251, in __requestEncode
                  status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
                File "/usr/lib/python2.7/dist-packages/github/Requester.py", line 285, in __requestRaw
                  self.__log(verb, url, requestHeaders, input, status, responseHeaders, output)
                File "/usr/lib/python2.7/dist-packages/github/Requester.py", line 353, in __log
                  logger.debug("%s %s://%s%s %s %s ==> %i %s %s", str(verb), self.__scheme, self.__hostname, str(url), str(requestHeaders), str(input), status, str(responseHeaders), str(output))
                File "/usr/lib/python2.7/logging/__init__.py", line 1148, in debug
                  self._log(DEBUG, msg, args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 310, in _log
                  self, level, msg, args, exc_info=exc_info, extra=extra
                File "/usr/lib/python2.7/logging/__init__.py", line 1278, in _log
                  record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
                File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 344, in makeRecord
                  exc_info, func)
                File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 191, in __init__
                  self.colormsg = '%s%s%s' % (cmsg, self.getMessage(), reset)
                File "/usr/lib/python2.7/logging/__init__.py", line 335, in getMessage
                  msg = msg % self.args
              UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 867: ordinal not in range(128)
     Started: 14:51:32.643633
    Duration: 860.271 ms
     Changes:  
```

### Versions Report
```
Salt Version:
           Salt: 2016.3.4
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: Not Installed
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: Not Installed
 
System Versions:
           dist: debian 8.5 
        machine: x86_64
        release: 4.4.0-51-generic
         system: Linux
        version: debian 8.5
```

**Comment by Ch3LL** [comment]
@kshcherban thanks it looks like we need to ensure we aren't using the default ascii when decoding the usernames with those characters in their names. thanks for the heads up.
