### ISSUE TITLE
2016.11 access denied error when using `service.modify` execution module on Windows

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt#38445]
### Description of Issue/Question

The `win_service.py` execution module was rewritten for 2016.11. Far as I can tell, it's pretty horridly broken. I'm trying to investigate more deeply, but the win32service library seems like a lot of gibberish at first glance.

### Setup

test.sls:
```
Enable the Smart Card Removal Policy service:
  service.enabled:
    - name: SCPolicySvc
```

### Steps to Reproduce Issue

Try using the state, `service.enabled`:
```
PS C:\Users\Administrator> C:\salt\salt-call.bat --local state.sls test -l debug
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Using cached minion ID from c:\salt\conf\minion_id: XXXXXXXXX.ec2.internal
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Motherboard info not available on this system
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded state.sls
[DEBUG   ] LazyLoaded saltutil.is_running
[DEBUG   ] LazyLoaded grains.get
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[DEBUG   ] Updating roots fileserver cache
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] In saltenv 'base', looking at rel_path 'test.sls' to resolve 'salt://test.sls'
[DEBUG   ] In saltenv 'base', ** considering ** path 'c:\salt\var\cache\salt\minion\files\base\test.sls' to resolve 'salt://test.sls'
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://test.sls'
[DEBUG   ] compile template: c:\salt\var\cache\salt\minion\files\base\test.sls
[DEBUG   ] Jinja search path: ['c:\\salt\\var\\cache\\salt\\minion\\files\\base']
[PROFILE ] Time (in seconds) to render 'c:\salt\var\cache\salt\minion\files\base\test.sls' using 'jinja' renderer: 0.00999999046326
[DEBUG   ] Rendered data from file: c:\salt\var\cache\salt\minion\files\base\test.sls:
Enable the Smart Card Removal Policy service:
  service.enabled:
    - name: SCPolicySvc
[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Results of YAML rendering:
OrderedDict([('Enable the Smart Card Removal Policy service', OrderedDict([('service.enabled', [OrderedDict([('name', 'SCPolicySvc')])])]))])
[PROFILE ] Time (in seconds) to render 'c:\salt\var\cache\salt\minion\files\base\test.sls' using 'yaml' renderer: 0.039999961853
[DEBUG   ] LazyLoaded service.start
[DEBUG   ] LazyLoaded service.enabled
[INFO    ] Running state [SCPolicySvc] at time 17:54:54.948000
[INFO    ] Executing state service.enabled for SCPolicySvc
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\state.py", line 1744, in call
    **cdata['kwargs'])
  File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1702, in wrapper
    return f(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\states\service.py", line 523, in enabled
    ret.update(_enable(name, None, **kwargs))
  File "C:\salt\bin\lib\site-packages\salt\states\service.py", line 153, in _enable
    if __salt__['service.enable'](name, **kwargs):
  File "C:\salt\bin\lib\site-packages\salt\modules\win_service.py", line 794, in enable
    modify(name, start_type='Auto')
  File "C:\salt\bin\lib\site-packages\salt\modules\win_service.py", line 666, in modify
    'Failed To Open {0}: {1}'.format(name, exc[2]))
CommandExecutionError: Failed To Open SCPolicySvc: Access is denied.

[INFO    ] Completed state [SCPolicySvc] at time 17:54:54.967000 duration_in_ms=19.0
[DEBUG   ] File c:\salt\var\cache\salt\minion\accumulator\98805408 does not exist, no need to cleanup.
[DEBUG   ] LazyLoaded config.option
[DEBUG   ] LazyLoaded cmd.run
[INFO    ] Executing command ['attrib', '-R', 'c:\\salt\\var\\cache\\salt\\minion\\sls.p'] in directory 'C:\Users\Administrator'
[DEBUG   ] output: File not found - C:\salt\var\cache\salt\minion\sls.p
[DEBUG   ] LazyLoaded highstate.output
local:
----------
          ID: Enable the Smart Card Removal Policy service
    Function: service.enabled
        Name: SCPolicySvc
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "C:\salt\bin\lib\site-packages\salt\state.py", line 1744, in call
                  **cdata['kwargs'])
                File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1702, in wrapper
                  return f(*args, **kwargs)
                File "C:\salt\bin\lib\site-packages\salt\states\service.py", line 523, in enabled
                  ret.update(_enable(name, None, **kwargs))
                File "C:\salt\bin\lib\site-packages\salt\states\service.py", line 153, in _enable
                  if __salt__['service.enable'](name, **kwargs):
                File "C:\salt\bin\lib\site-packages\salt\modules\win_service.py", line 794, in enable
                  modify(name, start_type='Auto')
                File "C:\salt\bin\lib\site-packages\salt\modules\win_service.py", line 666, in modify
                  'Failed To Open {0}: {1}'.format(name, exc[2]))
              CommandExecutionError: Failed To Open SCPolicySvc: Access is denied.
     Started: 17:54:54.948000
    Duration: 19.0 ms
     Changes:

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:  19.000 ms
```

Try using the execution module directly:

```
PS C:\Users\Administrator> C:\salt\salt-call.bat --local service.modify SCPolicySvc start_type='auto' -l debug
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Using cached minion ID from c:\salt\conf\minion_id: XXXXXXXXX.ec2.internal
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Motherboard info not available on this system
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded service.modify
Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\modules\win_service.py", line 666, in modify
    'Failed To Open {0}: {1}'.format(name, exc[2]))
CommandExecutionError: Failed To Open SCPolicySvc: Access is denied.
Error running 'service.modify': Failed To Open SCPolicySvc: Access is denied.
```

### Versions Report

```
PS C:\Users\Administrator> C:\salt\salt-call.bat --versions-report
Salt Version:
           Salt: 2016.11.1

Dependency Versions:
           cffi: 1.7.0
       cherrypy: 7.1.0
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 2.0.8
          ioflo: 1.5.5
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 16.0.1
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.4.1
            ZMQ: 4.1.6

System Versions:
           dist:
        machine: AMD64
        release: 2012ServerR2
         system: Windows
        version: 2012ServerR2 6.3.9600  Multiprocessor Free
```

**Comment by lorengordon** [comment]
Fyi, this happens even when running the shell as an Administrator.

**Comment by lorengordon** [comment]
Strangely, it does _not_ happen with _every_ service. Here is the list of services on my Win10 desktop that fail:

```
Failed To Open BDESVC: Access is denied.
Failed To Open BrokerInfrastructure: Access is denied.
Failed To Open CertPropSvc: Access is denied.
Failed To Open ClipSVC: Access is denied.
Failed To Open CoreMessagingRegistrar: Access is denied.
Failed To Open DcomLaunch: Access is denied.
Failed To Open DPS: Access is denied.
Failed To Open EFS: Access is denied.
Failed To Open gpsvc: Access is denied.
Failed To Open LSM: Access is denied.
Failed To Open MSDTC: Access is denied.
Failed To Open NgcCtnrSvc: Access is denied.
Failed To Open NgcSvc: Access is denied.
Failed To Open PimIndexMaintenanceSvc_2398f5: Access is denied.
Failed To Open RmSvc: Access is denied.
Failed To Open RpcEptMapper: Access is denied.
Failed To Open RpcSs: Access is denied.
Failed To Open SCardSvr: Access is denied.
Failed To Open ScDeviceEnum: Access is denied.
Failed To Open Schedule: Access is denied.
Failed To Open SCPolicySvc: Access is denied.
Failed To Open Sense: Access is denied.
Failed To Open SmsRouter: Access is denied.
Failed To Open sppsvc: Access is denied.
Failed To Open SystemEventsBroker: Access is denied.
Failed To Open TimeBrokerSvc: Access is denied.
Failed To Open TrustedInstaller: Access is denied.
Failed To Open UnistoreSvc_2398f5: Access is denied.
Failed To Open UserDataSvc_2398f5: Access is denied.
Failed To Open WdiServiceHost: Access is denied.
Failed To Open WdiSystemHost: Access is denied.
Failed To Open WdNisSvc: Access is denied.
Failed To Open WinDefend: Access is denied.
Failed To Open WpnUserService_2398f5: Access is denied.
```

I generated the list of services using powershell's Get-Service, then looped over them testing the same win32service.OpenService() call that is currently in develop.

```
for svc in services:
    try: 
        handle_svc = win32service.OpenService(handle_scm, svc, win32service.SERVICE_ALL_ACCESS)
    except pywintypes.error as exc:
        print('Failed To Open {0}: {1}'.format(svc, exc[2]))
```

**Comment by lorengordon** [comment]
@twangboy let me know if i can help testing anything. i'm really hoping a patch for this one makes it into 2016.11.2...

**Comment by twangboy** [comment]
@lorengordon Could you take a look at the PR and see if that works for you.

**Comment by lorengordon** [comment]
@twangboy that fixes it for some of the services, but not all of them. Here's the results that are still failing:

```
Failed To Open BrokerInfrastructure: Access is denied.
Failed To Open ClipSVC: Access is denied.
Failed To Open CoreMessagingRegistrar: Access is denied.
Failed To Open DcomLaunch: Access is denied.
Failed To Open gpsvc: Access is denied.
Failed To Open LSM: Access is denied.
Failed To Open NgcCtnrSvc: Access is denied.
Failed To Open NgcSvc: Access is denied.
Failed To Open PimIndexMaintenanceSvc_2398f5: Access is denied.
Failed To Open RpcEptMapper: Access is denied.
Failed To Open RpcSs: Access is denied.
Failed To Open Schedule: Access is denied.
Failed To Open sppsvc: Access is denied.
Failed To Open SystemEventsBroker: Access is denied.
Failed To Open TimeBrokerSvc: Access is denied.
Failed To Open UnistoreSvc_2398f5: Access is denied.
Failed To Open UserDataSvc_2398f5: Access is denied.
Failed To Open WdNisSvc: Access is denied.
Failed To Open WinDefend: Access is denied.
Failed To Open WpnUserService_2398f5: Access is denied.
```

**Comment by lorengordon** [comment]
That was from my Win10 desktop. Here's the results from a Win2012r2 Server:

```
Failed To Open BrokerInfrastructure: Access is denied.
Failed To Open DcomLaunch: Access is denied.
Failed To Open gpsvc: Access is denied.
Failed To Open LSM: Access is denied.
Failed To Open RpcEptMapper: Access is denied.
Failed To Open RpcSs: Access is denied.
Failed To Open Schedule: Access is denied.
Failed To Open sppsvc: Access is denied.
Failed To Open SystemEventsBroker: Access is denied.
Failed To Open WSService: Access is denied.
```

**Comment by lorengordon** [comment]
Here's how I tested:

Get the services from powershell:
```powershell
Get-Service | % { "'" + $_.Name + "'," }
```

Run python `C:\salt\bin\python.exe` and execute:
```python
import win32service
import pywintypes

services = [
    # paste list from powershell command
]

handle_scm = win32service.OpenSCManager(None, None, win32service.SC_MANAGER_CONNECT)

for svc in services:
  try: 
    handle_svc = win32service.OpenService(handle_scm, svc, win32service.SERVICE_CHANGE_CONFIG |win32service.SERVICE_QUERY_CONFIG)
  except pywintypes.error as exc:
    print('Failed To Open {0}: {1}'.format(svc, exc[2]))
```

**Comment by twangboy** [comment]
@lorengordon Are you able to modify those services via an elevated command prompt?

**Comment by lorengordon** [comment]
Hmm, it seems not...

```
PS C:\Windows\system32> (Get-Service -name Schedule) | Stop-Service
Stop-Service : Service 'Task Scheduler (Schedule)' cannot be stopped due to the following error: Cannot open Schedule service on computer '.'.
At line:1 char:32
+ (Get-Service -name Schedule) | Stop-Service
+                                ~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (System.ServiceProcess.ServiceController:ServiceController) [Stop-Service], ServiceCommandException
    + FullyQualifiedErrorId : CouldNotStopService,Microsoft.PowerShell.Commands.StopServiceCommand
```

And if I attempt through an elevated services.msc, all controls are greyed out.

![image](https://cloud.githubusercontent.com/assets/8457307/21535457/3c50611e-cd43-11e6-8326-5f9140ceed4a.png)

Strange. I don't understand it, but I suppose just chalk it up to that's how Windows works? The patch works for my particular use case, so, good enough for now?

**Comment by twangboy** [comment]
It's a permissions thing. If you really need to edit the service you would need to grant permissions first, then edit. I noticed it on the WinDefend service on my box. I have another Anti-Virus installed. I believe it disabled WinDefend and removed rights so you couldn't start it (easily). I'm going to go ahead and close this then.

**Comment by lorengordon** [comment]
Thanks @twangboy. I've never had to modify permissions for service. Just using an elevated shell has worked for everything I've ever needed to do. Do you have a pointer on where those permissions are set for a service? Might help the next person who stumbles across this issue...

**Comment by twangboy** [comment]
@lorengordon Windows doesn't have a built in GUI for modifying permissions for a service that I know of. Here's a decent article on how to do it: http://michlstechblog.info/blog/windows-set-permissions-on-a-service/

I'm also working on a win_dacl salt util for modifying permissions to windows objects. I haven't implemented it for services yet. https://github.com/saltstack/salt/blob/develop/salt/utils/win_dacl.py
