### ISSUE TITLE
2016.11 file.replace has multiple errors under python 3

### ISSUE THREAD

**Issue by ezh** [saltstack/salt#38451]
### Setup
-

### Steps to Reproduce Issue
./tests/runtests.py -n unit.modules.file_test

(Include debug logs if possible and relevant.)

```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Transplanting configuration files to '/private/tmp/salt-tests-tmpdir/config'
 * Current Directory: /Users/aaksenov/workspace/salt-bug-hunting/salt-file-replace
 * Test suite is running under PID 46580
 * Logging tests on /private/tmp/salt-runtests.log
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Starting unit.modules.file_test Tests
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...........F........EEEEEEEEEE.
======================================================================
ERROR: test_backup (unit.modules.file_test.FileReplaceTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/aaksenov/workspace/salt-bug-hunting/salt-file-replace/tests/unit/modules/file_test.py", line 130, in test_backup
    filemod.replace(self.tfile.name, r'Etiam', 'Salticus', backup=fext)
  File "/Users/aaksenov/workspace/salt-bug-hunting/salt-file-replace/salt/modules/file.py", line 2041, in replace
    result, nrepl = re.subn(cpattern, repl, r_data, count)
  File "/Users/aaksenov/.virtualenvs/salt-test/lib/python3.5/re.py", line 193, in subn
    return _compile(pattern, flags).subn(repl, string, count)
TypeError: cannot use a string pattern on a bytes-like object

======================================================================
ERROR: test_dry_run (unit.modules.file_test.FileReplaceTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/aaksenov/workspace/salt-bug-hunting/salt-file-replace/tests/unit/modules/file_test.py", line 145, in test_dry_run
    filemod.replace(self.tfile.name, r'Etiam', 'Salticus', dry_run=True)
  File "/Users/aaksenov/workspace/salt-bug-hunting/salt-file-replace/salt/modules/file.py", line 2041, in replace
    result, nrepl = re.subn(cpattern, repl, r_data, count)
  File "/Users/aaksenov/.virtualenvs/salt-test/lib/python3.5/re.py", line 193, in subn
    return _compile(pattern, flags).subn(repl, string, count)
TypeError: cannot use a string pattern on a bytes-like object

======================================================================
ERROR: test_nobackup (unit.modules.file_test.FileReplaceTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/aaksenov/workspace/salt-bug-hunting/salt-file-replace/tests/unit/modules/file_test.py", line 139, in test_nobackup
    filemod.replace(self.tfile.name, r'Etiam', 'Salticus', backup=False)
  File "/Users/aaksenov/workspace/salt-bug-hunting/salt-file-replace/salt/modules/file.py", line 2041, in replace
    result, nrepl = re.subn(cpattern, repl, r_data, count)
  File "/Users/aaksenov/.virtualenvs/salt-test/lib/python3.5/re.py", line 193, in subn
    return _compile(pattern, flags).subn(repl, string, count)
TypeError: cannot use a string pattern on a bytes-like object

======================================================================
ERROR: test_noshow_changes (unit.modules.file_test.FileReplaceTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/aaksenov/workspace/salt-bug-hunting/salt-file-replace/tests/unit/modules/file_test.py", line 160, in test_noshow_changes
    show_changes=False)
  File "/Users/aaksenov/workspace/salt-bug-hunting/salt-file-replace/salt/modules/file.py", line 2041, in replace
    result, nrepl = re.subn(cpattern, repl, r_data, count)
  File "/Users/aaksenov/.virtualenvs/salt-test/lib/python3.5/re.py", line 193, in subn
    return _compile(pattern, flags).subn(repl, string, count)
TypeError: cannot use a string pattern on a bytes-like object

======================================================================
ERROR: test_numeric_repl (unit.modules.file_test.FileReplaceTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/aaksenov/workspace/salt-bug-hunting/salt-file-replace/tests/unit/modules/file_test.py", line 181, in test_numeric_repl
    filemod.replace(self.tfile.name, r'Etiam', 123)
  File "/Users/aaksenov/workspace/salt-bug-hunting/salt-file-replace/salt/modules/file.py", line 2041, in replace
    result, nrepl = re.subn(cpattern, repl, r_data, count)
  File "/Users/aaksenov/.virtualenvs/salt-test/lib/python3.5/re.py", line 193, in subn
    return _compile(pattern, flags).subn(repl, string, count)
TypeError: cannot use a string pattern on a bytes-like object

======================================================================
ERROR: test_re_int_flags (unit.modules.file_test.FileReplaceTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/aaksenov/workspace/salt-bug-hunting/salt-file-replace/tests/unit/modules/file_test.py", line 171, in test_re_int_flags
    filemod.replace(self.tfile.name, r'Etiam', 'Salticus', flags=10)
  File "/Users/aaksenov/workspace/salt-bug-hunting/salt-file-replace/salt/modules/file.py", line 2041, in replace
    result, nrepl = re.subn(cpattern, repl, r_data, count)
  File "/Users/aaksenov/.virtualenvs/salt-test/lib/python3.5/re.py", line 193, in subn
    return _compile(pattern, flags).subn(repl, string, count)
TypeError: cannot use a string pattern on a bytes-like object

======================================================================
ERROR: test_re_str_flags (unit.modules.file_test.FileReplaceTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/aaksenov/workspace/salt-bug-hunting/salt-file-replace/tests/unit/modules/file_test.py", line 168, in test_re_str_flags
    flags=['MULTILINE', 'ignorecase'])
  File "/Users/aaksenov/workspace/salt-bug-hunting/salt-file-replace/salt/modules/file.py", line 2041, in replace
    result, nrepl = re.subn(cpattern, repl, r_data, count)
  File "/Users/aaksenov/.virtualenvs/salt-test/lib/python3.5/re.py", line 193, in subn
    return _compile(pattern, flags).subn(repl, string, count)
TypeError: cannot use a string pattern on a bytes-like object

======================================================================
ERROR: test_replace (unit.modules.file_test.FileReplaceTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/aaksenov/workspace/salt-bug-hunting/salt-file-replace/tests/unit/modules/file_test.py", line 72, in test_replace
    filemod.replace(self.tfile.name, r'Etiam', 'Salticus', backup=False)
  File "/Users/aaksenov/workspace/salt-bug-hunting/salt-file-replace/salt/modules/file.py", line 2041, in replace
    result, nrepl = re.subn(cpattern, repl, r_data, count)
  File "/Users/aaksenov/.virtualenvs/salt-test/lib/python3.5/re.py", line 193, in subn
    return _compile(pattern, flags).subn(repl, string, count)
TypeError: cannot use a string pattern on a bytes-like object

======================================================================
ERROR: test_replace_append_if_not_found (unit.modules.file_test.FileReplaceTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/aaksenov/workspace/salt-bug-hunting/salt-file-replace/tests/unit/modules/file_test.py", line 92, in test_replace_append_if_not_found
    filemod.replace(tfile.name, **args)
  File "/Users/aaksenov/workspace/salt-bug-hunting/salt-file-replace/salt/modules/file.py", line 2041, in replace
    result, nrepl = re.subn(cpattern, repl, r_data, count)
  File "/Users/aaksenov/.virtualenvs/salt-test/lib/python3.5/re.py", line 193, in subn
    return _compile(pattern, flags).subn(repl, string, count)
TypeError: cannot use a string pattern on a bytes-like object

======================================================================
ERROR: test_show_changes (unit.modules.file_test.FileReplaceTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/aaksenov/workspace/salt-bug-hunting/salt-file-replace/tests/unit/modules/file_test.py", line 153, in test_show_changes
    show_changes=True)
  File "/Users/aaksenov/workspace/salt-bug-hunting/salt-file-replace/salt/modules/file.py", line 2041, in replace
    result, nrepl = re.subn(cpattern, repl, r_data, count)
  File "/Users/aaksenov/.virtualenvs/salt-test/lib/python3.5/re.py", line 193, in subn
    return _compile(pattern, flags).subn(repl, string, count)
TypeError: cannot use a string pattern on a bytes-like object

======================================================================
FAIL: test_apply_template_on_contents (unit.modules.file_test.FileModuleTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/aaksenov/workspace/salt-bug-hunting/salt-file-replace/tests/unit/modules/file_test.py", line 644, in test_apply_template_on_contents
    self.assertEqual(ret, 'This is a templated file.')
AssertionError: b'This is a templated file.' != 'This is a templated file.'

----------------------------------------------------------------------
Ran 31 tests in 0.328s

FAILED (failures=1, errors=10)

===================================================  Overall Tests Report  ====================================================
*** unit.modules.file_test Tests  *********************************************************************************************
 --------  Tests with Errors  -------------------------------------------------------------------------------------------------
   -> unit.modules.file_test.FileReplaceTestCase.test_backup  .................................................................
       Traceback (most recent call last):
         File "/Users/aaksenov/workspace/salt-bug-hunting/salt-file-replace/tests/unit/modules/file_test.py", line 130, in test_backup
           filemod.replace(self.tfile.name, r'Etiam', 'Salticus', backup=fext)
         File "/Users/aaksenov/workspace/salt-bug-hunting/salt-file-replace/salt/modules/file.py", line 2041, in replace
           result, nrepl = re.subn(cpattern, repl, r_data, count)
         File "/Users/aaksenov/.virtualenvs/salt-test/lib/python3.5/re.py", line 193, in subn
           return _compile(pattern, flags).subn(repl, string, count)
       TypeError: cannot use a string pattern on a bytes-like object
   ............................................................................................................................
   -> unit.modules.file_test.FileReplaceTestCase.test_dry_run  ................................................................
       Traceback (most recent call last):
         File "/Users/aaksenov/workspace/salt-bug-hunting/salt-file-replace/tests/unit/modules/file_test.py", line 145, in test_dry_run
           filemod.replace(self.tfile.name, r'Etiam', 'Salticus', dry_run=True)
         File "/Users/aaksenov/workspace/salt-bug-hunting/salt-file-replace/salt/modules/file.py", line 2041, in replace
           result, nrepl = re.subn(cpattern, repl, r_data, count)
         File "/Users/aaksenov/.virtualenvs/salt-test/lib/python3.5/re.py", line 193, in subn
           return _compile(pattern, flags).subn(repl, string, count)
       TypeError: cannot use a string pattern on a bytes-like object
   ............................................................................................................................
   -> unit.modules.file_test.FileReplaceTestCase.test_nobackup  ...............................................................
       Traceback (most recent call last):
         File "/Users/aaksenov/workspace/salt-bug-hunting/salt-file-replace/tests/unit/modules/file_test.py", line 139, in test_nobackup
           filemod.replace(self.tfile.name, r'Etiam', 'Salticus', backup=False)
         File "/Users/aaksenov/workspace/salt-bug-hunting/salt-file-replace/salt/modules/file.py", line 2041, in replace
           result, nrepl = re.subn(cpattern, repl, r_data, count)
         File "/Users/aaksenov/.virtualenvs/salt-test/lib/python3.5/re.py", line 193, in subn
           return _compile(pattern, flags).subn(repl, string, count)
       TypeError: cannot use a string pattern on a bytes-like object
   ............................................................................................................................
   -> unit.modules.file_test.FileReplaceTestCase.test_noshow_changes  .........................................................
       Traceback (most recent call last):
         File "/Users/aaksenov/workspace/salt-bug-hunting/salt-file-replace/tests/unit/modules/file_test.py", line 160, in test_noshow_changes
           show_changes=False)
         File "/Users/aaksenov/workspace/salt-bug-hunting/salt-file-replace/salt/modules/file.py", line 2041, in replace
           result, nrepl = re.subn(cpattern, repl, r_data, count)
         File "/Users/aaksenov/.virtualenvs/salt-test/lib/python3.5/re.py", line 193, in subn
           return _compile(pattern, flags).subn(repl, string, count)
       TypeError: cannot use a string pattern on a bytes-like object
   ............................................................................................................................
   -> unit.modules.file_test.FileReplaceTestCase.test_numeric_repl  ...........................................................
       Traceback (most recent call last):
         File "/Users/aaksenov/workspace/salt-bug-hunting/salt-file-replace/tests/unit/modules/file_test.py", line 181, in test_numeric_repl
           filemod.replace(self.tfile.name, r'Etiam', 123)
         File "/Users/aaksenov/workspace/salt-bug-hunting/salt-file-replace/salt/modules/file.py", line 2041, in replace
           result, nrepl = re.subn(cpattern, repl, r_data, count)
         File "/Users/aaksenov/.virtualenvs/salt-test/lib/python3.5/re.py", line 193, in subn
           return _compile(pattern, flags).subn(repl, string, count)
       TypeError: cannot use a string pattern on a bytes-like object
   ............................................................................................................................
   -> unit.modules.file_test.FileReplaceTestCase.test_re_int_flags  ...........................................................
       Traceback (most recent call last):
         File "/Users/aaksenov/workspace/salt-bug-hunting/salt-file-replace/tests/unit/modules/file_test.py", line 171, in test_re_int_flags
           filemod.replace(self.tfile.name, r'Etiam', 'Salticus', flags=10)
         File "/Users/aaksenov/workspace/salt-bug-hunting/salt-file-replace/salt/modules/file.py", line 2041, in replace
           result, nrepl = re.subn(cpattern, repl, r_data, count)
         File "/Users/aaksenov/.virtualenvs/salt-test/lib/python3.5/re.py", line 193, in subn
           return _compile(pattern, flags).subn(repl, string, count)
       TypeError: cannot use a string pattern on a bytes-like object
   ............................................................................................................................
   -> unit.modules.file_test.FileReplaceTestCase.test_re_str_flags  ...........................................................
       Traceback (most recent call last):
         File "/Users/aaksenov/workspace/salt-bug-hunting/salt-file-replace/tests/unit/modules/file_test.py", line 168, in test_re_str_flags
           flags=['MULTILINE', 'ignorecase'])
         File "/Users/aaksenov/workspace/salt-bug-hunting/salt-file-replace/salt/modules/file.py", line 2041, in replace
           result, nrepl = re.subn(cpattern, repl, r_data, count)
         File "/Users/aaksenov/.virtualenvs/salt-test/lib/python3.5/re.py", line 193, in subn
           return _compile(pattern, flags).subn(repl, string, count)
       TypeError: cannot use a string pattern on a bytes-like object
   ............................................................................................................................
   -> unit.modules.file_test.FileReplaceTestCase.test_replace  ................................................................
       Traceback (most recent call last):
         File "/Users/aaksenov/workspace/salt-bug-hunting/salt-file-replace/tests/unit/modules/file_test.py", line 72, in test_replace
           filemod.replace(self.tfile.name, r'Etiam', 'Salticus', backup=False)
         File "/Users/aaksenov/workspace/salt-bug-hunting/salt-file-replace/salt/modules/file.py", line 2041, in replace
           result, nrepl = re.subn(cpattern, repl, r_data, count)
         File "/Users/aaksenov/.virtualenvs/salt-test/lib/python3.5/re.py", line 193, in subn
           return _compile(pattern, flags).subn(repl, string, count)
       TypeError: cannot use a string pattern on a bytes-like object
   ............................................................................................................................
   -> unit.modules.file_test.FileReplaceTestCase.test_replace_append_if_not_found  ............................................
       Traceback (most recent call last):
         File "/Users/aaksenov/workspace/salt-bug-hunting/salt-file-replace/tests/unit/modules/file_test.py", line 92, in test_replace_append_if_not_found
           filemod.replace(tfile.name, **args)
         File "/Users/aaksenov/workspace/salt-bug-hunting/salt-file-replace/salt/modules/file.py", line 2041, in replace
           result, nrepl = re.subn(cpattern, repl, r_data, count)
         File "/Users/aaksenov/.virtualenvs/salt-test/lib/python3.5/re.py", line 193, in subn
           return _compile(pattern, flags).subn(repl, string, count)
       TypeError: cannot use a string pattern on a bytes-like object
   ............................................................................................................................
   -> unit.modules.file_test.FileReplaceTestCase.test_show_changes  ...........................................................
       Traceback (most recent call last):
         File "/Users/aaksenov/workspace/salt-bug-hunting/salt-file-replace/tests/unit/modules/file_test.py", line 153, in test_show_changes
           show_changes=True)
         File "/Users/aaksenov/workspace/salt-bug-hunting/salt-file-replace/salt/modules/file.py", line 2041, in replace
           result, nrepl = re.subn(cpattern, repl, r_data, count)
         File "/Users/aaksenov/.virtualenvs/salt-test/lib/python3.5/re.py", line 193, in subn
           return _compile(pattern, flags).subn(repl, string, count)
       TypeError: cannot use a string pattern on a bytes-like object
   ............................................................................................................................
 ------------------------------------------------------------------------------------------------------------------------------
 --------  Failed Tests  ------------------------------------------------------------------------------------------------------
   -> unit.modules.file_test.FileModuleTestCase.test_apply_template_on_contents  ..............................................
       Traceback (most recent call last):
         File "/Users/aaksenov/workspace/salt-bug-hunting/salt-file-replace/tests/unit/modules/file_test.py", line 644, in test_apply_template_on_contents
           self.assertEqual(ret, 'This is a templated file.')
       AssertionError: b'This is a templated file.' != 'This is a templated file.'
   ............................................................................................................................
 ------------------------------------------------------------------------------------------------------------------------------
===============================================================================================================================
FAILED (total=31, skipped=0, passed=20, failures=1, errors=10)
===================================================  Overall Tests Report  ====================================================
```

### Versions Report

```
python -V
Python 3.5.2
```

```
Salt Version:
           Salt: 2016.11.0rc2-39-g3835f91

Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: 2.6.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.3
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: 0.24.2
         Python: 3.5.2 (default, Nov 12 2016, 15:19:34)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.6

System Versions:
           dist:
        machine: x86_64
        release: 16.3.0
         system: Darwin
        version: 10.12.2 x86_64
```

**Comment by ezh** [comment]
Pull request will be ready within a reasonable time.

**Comment by ezh** [comment]
./tests/runtests.py -n unit.modules.file_test
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Transplanting configuration files to '/private/tmp/salt-tests-tmpdir/config'
 * Current Directory: /Users/aaksenov/workspace/salt-bug-hunting/salt-file-replace
 * Test suite is running under PID 85404
 * Logging tests on /private/tmp/salt-runtests.log
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Starting unit.modules.file_test Tests
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...............................
----------------------------------------------------------------------
Ran 31 tests in 0.535s

OK

===============================  Overall Tests Report  ===============================
***  No Problems Found While Running Tests  ******************************************
======================================================================================
OK (total=31, skipped=0, passed=31, failures=0, errors=0)
===============================  Overall Tests Report  ===============================

**Comment by rallytime** [comment]
Since #38498 and #38464 have now been merged in, I'll close this one. Thanks for fixing this up @ezh! It is very much appreciated.
