### ISSUE TITLE
salt.modules.upstart and python2.6 re module sadness

### ISSUE THREAD

**Issue by SG910** [saltstack/salt#38492]
### Description of Issue/Question
```
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.6/site-packages/salt/state.py", line 1744, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.6/site-packages/salt/loader.py", line 1702, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib64/python2.6/contextlib.py", line 34, in __exit__
                  self.gen.throw(type, value, traceback)
                File "/usr/lib/python2.6/site-packages/salt/utils/context.py", line 48, in func_globals_inject
                  yield
                File "/usr/lib/python2.6/site-packages/salt/loader.py", line 1702, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.6/site-packages/salt/states/service.py", line 352, in running
                  ret.update(_enable(name, None, **kwargs))
                File "/usr/lib/python2.6/site-packages/salt/states/service.py", line 153, in _enable
                  if __salt__['service.enable'](name, **kwargs):
                File "/usr/lib/python2.6/site-packages/salt/modules/rh_service.py", line 520, in enable
                  return _upstart_enable(name)
                File "/usr/lib/python2.6/site-packages/salt/modules/upstart.py", line 485, in _upstart_enable
                  new_text = re.sub(r'^\s*manual\n?', '', fp_.read(), 0, re.MULTILINE)
              TypeError: sub() takes at most 4 arguments (5 given)
```
### Versions Report
```
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: unknown
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5
 
System Versions:
           dist: centos 6.8 Final
        machine: x86_64
        release: 2.6.32-642.4.2.el6.x86_64
         system: Linux
        version: CentOS 6.8 Final
```

**Comment by gtmanfred** [comment]
Can you provide me with some information on what you ran to get this error so that I can attempt to replicate it?

Thanks,
Daniel
