### ISSUE TITLE
API client wheel_async always returns status 500

### ISSUE THREAD

**Issue by amendlik** [saltstack/salt#38537]
### Description of Issue/Question
Any call to the Salt API using the wheel_async client will result in status code 500.

### Steps to Reproduce Issue
Call the Salt API specifying the wheel_async client. Any function will fail. For example:
```
[{
 "fun": "minions.connected",
 "client": "wheel_async"
}]
```

The following result will be returned:
```
{"status": 500, "return": "An unexpected error occurred"}
```

### Versions Report
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: 0.20.0
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: 0.20.3
         Python: 2.6.6 (r266:84292, Aug  9 2016, 06:11:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: redhat 6.8 Santiago
        machine: x86_64
        release: 2.6.32-642.11.1.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.8 Santiago

**Comment by whiteinge** [comment]
Relevant traceback:

```py
  File "/Users/shouse/src/salt/salt/salt/wheel/__init__.py", line 119, in cmd_async
    return self.async(fun, low)
  File "/Users/shouse/src/salt/salt/salt/client/mixins.py", line 516, in async
    with salt.utils.process.default_signals(signal.SIGINT, signal.SIGTERM):
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Users/shouse/src/salt/salt/salt/utils/process.py", line 706, in default_signals
    signal.signal(signum, signal.SIG_DFL)
ValueError: signal only works in main thread
```

**Comment by whiteinge** [comment]
Thanks for filing this @amendlik.

**Comment by terminalmage** [comment]
Traceback in the salt-api log when this happens:

```
Traceback (most recent call last):
  File "/testing/salt/netapi/rest_cherrypy/app.py", line 686, in hypermedia_handler
    ret = cherrypy.serving.request._hypermedia_inner_handler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/testing/salt/netapi/rest_cherrypy/app.py", line 1072, in POST
    token=cherrypy.session.get('token')))
  File "/testing/salt/netapi/rest_cherrypy/app.py", line 961, in exec_lowstate
    ret = self.api.run(chunk)
  File "/testing/salt/netapi/__init__.py", line 70, in run
    return l_fun(*f_call.get('args', ()), **f_call.get('kwargs', {}))
  File "/testing/salt/netapi/__init__.py", line 192, in wheel_async
    return wheel.cmd_async(kwargs)
  File "/testing/salt/wheel/__init__.py", line 113, in cmd_async
    return self.async(fun, low)
  File "/testing/salt/client/mixins.py", line 477, in async
    with default_signals(signal.SIGINT, signal.SIGTERM):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/testing/salt/utils/process.py", line 672, in default_signals
    signal.signal(signum, signal.SIG_DFL)
ValueError: signal only works in main thread
```

**Comment by terminalmage** [comment]
Fix added to already-open PR https://github.com/saltstack/salt/pull/38925

**Comment by whiteinge** [comment]
@amendlik see the above PR courtesy of some @terminalmage magic. It's now merged so you can test on the latest 2016.3 branch if you'd like, or they'll be in the next point-release.

**Comment by terminalmage** [comment]
@amendlik the reason the bugfix was submitted against the 2016.3 branch is so we can merge bugfixes forward and not have to backport. So within a matter of a couple days we should have this fix in the ``2016.11`` branch and in ``develop`` as well.

**Comment by amendlik** [comment]
@gtmanfred I tested this against 2016.11.2 and the problem is still present.

**Comment by gtmanfred** [comment]
You will need to test it against 2016.11.3, which is where the fix will be
