### ISSUE TITLE
KeyError: 'retcode' 

### ISSUE THREAD

**Issue by rukender** [saltstack/salt#38550]
### Setup
```
2017-01-03 04:19:48,415 [salt.loaded.ext.nova./cve_scan_v2.py                 ][ERROR   ][29426] pkg:%s contains an operator that's not supported and was changed to <
2017-01-03 04:51:16,059 [salt.utils.schedule                                  ][ERROR   ][3268] Unhandled exception running mine.update
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/utils/schedule.py", line 703, in handle_func
    ret['retcode'] = self.functions.pack['__context__']['retcode']
KeyError: 'retcode'
2017-01-03 05:51:16,067 [salt.utils.schedule                                  ][ERROR   ][14946] Unhandled exception running mine.update
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/utils/schedule.py", line 703, in handle_func
    ret['retcode'] = self.functions.pack['__context__']['retcode']
KeyError: 'retcode'
2017-01-03 06:51:16,056 [salt.utils.schedule                                  ][ERROR   ][26458] Unhandled exception running mine.update
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/utils/schedule.py", line 703, in handle_func
    ret['retcode'] = self.functions.pack['__context__']['retcode']
KeyError: 'retcode'
2017-01-03 07:51:16,071 [salt.utils.schedule                                  ][ERROR   ][7282] Unhandled exception running mine.update
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/utils/schedule.py", line 703, in handle_func
    ret['retcode'] = self.functions.pack['__context__']['retcode']
KeyError: 'retcode'
2017-01-03 08:03:27,440 [salt.loader                                          ][ERROR   ][11220] Failed to import beacons win_pulsar, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/loader.py", line 1135, in _load_module
    ), fn_, fpath, desc)
  File "/var/cache/salt/minion/extmods/beacons/win_pulsar.py", line 420
     events_list.append({k: event_dict[k] for k in ('EntryType', 'Accesses', 'TimeGenerated', 'Object Name', 'Hash')})
                                            ^
 SyntaxError: invalid syntax
```

**Comment by gtmanfred** [comment]
What you have there is a dict comprehension.

This wasn't added until python 2.7.

You will need to update your custom beacon to use regular list comprehension with dict() on it

`event_list.append(dict((k, event_dict[k] for k in ('EntryType', 'Accesses', 'TimeGenerated', 'Object Name', 'Hash'))))`

**Comment by rukender** [comment]
@gtmanfred , Thanks for your reply.

I'm continuously seeing this related error after upgrading salt minions with the latest version i.e. 2016.11.1

Here is another error, i got after the upgrade:
2017-01-05 04:55:37,313 [salt.loaded.ext.nova./modules/cve_scan_v2.py][ERROR   ][970] pkg:%s contains an operator that's not supported and was changed to <
2017-01-05 04:55:37,329 [salt.loader      ][ERROR   ][970] Failed to import module aem_grains, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1332, in _load_module
    ), fn_, fpath, desc)
  File "/var/cache/salt/minion/extmods/modules/aem_grains.py", line 46
    if initialized:
                  ^
IndentationError: unindent does not match any outer indentation level

I'm beginner in saltstack, please let me know if you know how to fix this issue. Also, do we have any patch for this error from Saltstack?

Thanks!

**Comment by gtmanfred** [comment]
Your module is just a python script, make sure the function you have there
can run on python 2.6, you have another python syntax error there

**Comment by rukender** [comment]
Does it mean I need to use python 2.6  instead of python2.7?

Also, there is no other way to resolve this issue.

**Comment by gtmanfred** [comment]
no, you need to make sure the module that you wrote is python compatible.  You just have a regular python syntax error in it.

**Comment by rukender** [comment]
@gtmanfred,

Do you have any steps for me to follow to resolve this problem? I'm new to salt so not sure where I need to make changes so that I will look for python2.6 instead of 2.7. 

Any help from your side will be highly appreciated.

**Comment by gtmanfred** [comment]
Your problem is not a difference between python 2.6 and 2.7.

You just have a generic syntax error in the win_pulsar.py custom beacon.  You do not have the correct amount of indentation on the line with `if initialized:` in it

**Comment by rukender** [comment]
@gtmanfred, thanks for your reply!

I'm also getting this error. Do you have any idea on this, I have tried looking for this error but did not get anything from internet. 
2017-01-06 06:39:38,409 [salt.loaded.ext.nova./modules/cve_scan_v2.py][ERROR   ][15579] pkg:%s contains an operator that's not supported and was changed to <
