### ISSUE TITLE
archive.extracted doesn't set user/group ownership correctly

### ISSUE THREAD

**Issue by jcmcken** [saltstack/salt#38605]
### Setup

Create the following SLS file (e.g. ``$FILEROOT/tomcat/init.sls``):

```yaml
tomcat.pkg:
  archive.extracted:
    - name: /opt/tomcat
    - source: http://..some-tomcat-source...tar.gz
    - source_hash: sha1=3c800e7affdf93bf4dbcf44bd852904449b786f6
    - user: tomcat
    - group: tomcat
```

Manually create a ``tomcat`` user (e.g. by running ``useradd tomcat``).

### Steps to Reproduce Issue

* Run ``sudo salt-call --local --file-root $FILEROOT state.apply tomcat`` (i.e. running against the just-created SLS file).
* Observe that the archive gets installed under /opt/tomcat, but nearly everything is owned ``root:root``, not ``tomcat:tomcat``.

### Versions Report
```
Salt Version:
           Salt: 2016.11.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Oct 11 2015, 17:47:16)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5

System Versions:
           dist: redhat 7.2 Maipo
        machine: x86_64
        release: 3.10.0-327.10.1.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.2 Maipo
```

**Comment by jcmcken** [comment]
After some debugging, I think I have the source of the problem. Tomcat distributes its tarfile without a top-level directory explicitly listed (all of the files in the directory *have* a top-level directory, but the directory itself isn't in the archive), so when ``archive.list`` executes, the resulting contents manifest has no ``top_level_dirs``. The ``archive.extracted`` module uses these top level directories as the source of its recursive ``chown``, so since it's empty, no permissions are changed.

The workaround is to set ``ensure_ownership_on`` to ``/opt/tomcat``.

But this seems highly confusing as a default behavior. It means that either ``ensure_ownership_on`` becomes a required option, or I need to introspect every single archive to figure out if the top-level directory is explicitly listed.

As a suggestion, it may make sense for ``archive.list`` to detect this specific case and work out what the top-level directory in the archive is. As an analogy, ``tar`` has no problem with archives of this type -- it doesn't require you to first create the directory before unpacking if the top-level directory isn't explicitly listed.

**Comment by gtmanfred** [comment]
Thanks for reporting this.

If you wanna take a shot at fixing it, we greatly appreciate pull requests.  Otherwise I have tagged this with our platform team to take a look.

Thanks,
Daniel

**Comment by jf** [comment]
I think this bug needs to be reopened. It's not stale; this bug still exists. @gtmanfred @jcmcken

**Comment by VietTPham** [comment]
I'm having this exact issue with tomcat as well on v3004

**Comment by waynew** [comment]
@VietTPham can you take a look at the fix in the PR and see if that solves it for you? Thanks!

**Comment by VietTPham** [comment]
@waynew I am getting error after applying the PR on my client. Client is running Salt 3004.1
``` yaml
tomcat user:
  user.present:
    - name: tomcat
    - home: /usr/share/tomcat
    - createhome: False
    - shell: /bin/false
    - system: True

install apache tomcat binary:
  archive.extracted:
    - name: /usr/share/
    - source: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.62/bin/apache-tomcat-9.0.62.tar.gz
    - user: tomcat
    - group: tomcat
    - skip_verify: True
    - trim_output: True
    - keep_source: False
    - if_missing: /usr/share/apache-tomcat-9.0.62
```

Error
```
          ID: install apache tomcat binary
    Function: archive.extracted
        Name: /usr/share/
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3.6/site-packages/salt/state.py", line 2180, in call
                  *cdata["args"], **cdata["kwargs"]
                File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 149, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1201, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/usr/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
                  return callable(*args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1216, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1249, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/states/archive.py", line 1111, in extracted
                  verbose=True,
                File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 149, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1201, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/usr/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
                  return callable(*args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1216, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/modules/archive.py", line 335, in list_
                  name, saltenv, source_hash=source_hash, use_etag=use_etag
                File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 149, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1201, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/usr/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
                  return callable(*args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1216, in _run_as
                  return _func_or_method(*args, **kwargs)
              TypeError: cache_file() got an unexpected keyword argument 'use_etag'
```
