### ISSUE TITLE
grains.list_present fails on NoneType object not iterable if it does not exist

### ISSUE THREAD

**Issue by remyd1** [saltstack/salt#38614]
### Description of Issue/Question

Setting a grain with grains.list_present fails on non existing grains although [documentation](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.grains.html#salt.states.grains.list_present) says it should create it.

### Setup

```
init minion role grain:
  grains.list_present:
    - name: roles
    - value:
      - salt_minion
    - unless:
      - which salt
```

### Steps to Reproduce Issue

```
----------
          ID: init minion role grain
    Function: grains.list_present
        Name: roles
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1626, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1492, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/grains.py", line 175, in list_present
                  if not set(value).issubset(set(__salt__['grains.get'](name))):
              TypeError: 'NoneType' object is not iterable
     Started: 12:51:55.616642
    Duration: 25.109 ms
     Changes:  
```

### Versions Report

```bash
salt --versions-report
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 2.0.0
      gitpython: 2.1.0
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 3.13.0-101-generic
         system: Linux
        version: Ubuntu 16.04 xenial

```

### Comment

BTW, I have also the duplicate bug on this grains.list_present:
https://github.com/saltstack/salt/pull/31471

**Comment by remyd1** [comment]
According to documentation, if I have only one value I should write it this way in my sls file:
 - value: myvalue

However, I create it dynamically, and I do not know if my minion will have only one value or many...

**Comment by remyd1** [comment]
It works by replacing grains.list_present with grains.present

**Comment by gtmanfred** [comment]
Thanks for reporting this.

We will get it fixed, if you want to take a look we greatly appreciate pull requests!

Thanks,
Daniel
