### ISSUE TITLE
Add setting to increase timeout for publish.publish

### ISSUE THREAD

**Issue by jwerak** [saltstack/salt#38624]
### Description of Issue/Question

I am running highstate on all minions (20 nodes) at the same time. States on all nodes pass if I run them individually or in smaller batches, but if I run higstate on all nodes at the same time, I get below errors on several minions. 

Errors are on different nodes each run  and the failure of `x509.certificate_managed` is always briefly after 20000.000 ms. 
It seems like its some timeout value related. Probably master won't manage to check/sign all certificates at the same time.
Is there any setting that could be tweaked to workaround this? 

```
kubeminion-10.0.1.36:
----------
          ID: /var/run/kubernetes/kubelet.crt
    Function: x509.certificate_managed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1744, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1702, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/x509.py", line 442, in certificate_managed
                  new = __salt__['x509.create_certificate'](testrun=True, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/modules/x509.py", line 1324, in create_certificate
                  arg=str(kwargs))[ca_server]
              KeyError: 'kubemaster-10.0.6.167'
     Started: 18:13:46.504115
    Duration: 20115.629 ms
     Changes:
----------
          ID: Setup kubelet service
    Function: service.running
        Name: kubelet
      Result: False
     Comment: One or more requisite failed: kube.kubelet_certs./var/run/kubernetes/kubelet.crt
     Changes:

Summary for kubeminion-10.0.1.36
-------------
Succeeded: 58
Failed:     2
-------------
Total states run:     60
Total run time:   83.967 s
kubeminion-10.0.7.185:
----------
          ID: /etc/flanneld/etcdcli.crt
    Function: x509.certificate_managed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1744, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1702, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/x509.py", line 442, in certificate_managed
                  new = __salt__['x509.create_certificate'](testrun=True, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/modules/x509.py", line 1324, in create_certificate
                  arg=str(kwargs))[ca_server]
              KeyError: 'kubemaster-10.0.6.167'
     Started: 18:13:05.789018
    Duration: 20064.588 ms
     Changes:
----------
          ID: /etc/flanneld/etcdcli.crt
    Function: file.managed
      Result: False
     Comment: One or more requisite failed: flanneld.certificates./etc/flanneld/etcdcli.crt
     Changes:
----------
          ID: Flanneld service is running
    Function: service.running
        Name: flanneld
      Result: False
     Comment: One or more requisite failed: flanneld.certificates./etc/flanneld/etcdcli.crt
     Changes:

Summary for kubeminion-10.0.7.185
-------------
Succeeded: 57
Failed:     3
-------------
Total states run:     60
Total run time:   83.957 s
kubeminion-10.0.6.118:

Summary for kubeminion-10.0.6.118
-------------
Succeeded: 60
Failed:     0
-------------
Total states run:     60
Total run time:   84.046 s
kubeminion-10.0.7.149:
----------
          ID: /var/run/kubernetes/kubelet.crt
    Function: x509.certificate_managed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1744, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1702, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/x509.py", line 442, in certificate_managed
                  new = __salt__['x509.create_certificate'](testrun=True, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/modules/x509.py", line 1324, in create_certificate
                  arg=str(kwargs))[ca_server]
              KeyError: 'kubemaster-10.0.6.167'
     Started: 18:13:46.626454
    Duration: 20079.811 ms
     Changes:
----------
          ID: Setup kubelet service
    Function: service.running
        Name: kubelet
      Result: False
     Comment: One or more requisite failed: kube.kubelet_certs./var/run/kubernetes/kubelet.crt
     Changes:

Summary for kubeminion-10.0.7.149
-------------
Succeeded: 58
Failed:     2
-------------
Total states run:     60
Total run time:   83.848 s
kubeminion-10.0.7.198:

Summary for kubeminion-10.0.7.198
-------------
Succeeded: 60
Failed:     0
-------------
Total states run:     60
Total run time:   84.032 s
kubeminion-10.0.1.19:

Summary for kubeminion-10.0.1.19
-------------
Succeeded: 60
Failed:     0
-------------
Total states run:     60
Total run time:   83.897 s
kubeminion-10.0.6.133:
----------
          ID: /etc/flanneld/etcdcli.crt
    Function: x509.certificate_managed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1744, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1702, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/x509.py", line 442, in certificate_managed
                  new = __salt__['x509.create_certificate'](testrun=True, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/modules/x509.py", line 1324, in create_certificate
                  arg=str(kwargs))[ca_server]
              KeyError: 'kubemaster-10.0.6.167'
     Started: 18:13:05.761316
    Duration: 20058.763 ms
     Changes:
----------
          ID: /etc/flanneld/etcdcli.crt
    Function: file.managed
      Result: False
     Comment: One or more requisite failed: flanneld.certificates./etc/flanneld/etcdcli.crt
     Changes:
----------
          ID: Flanneld service is running
    Function: service.running
        Name: flanneld
      Result: False
     Comment: One or more requisite failed: flanneld.certificates./etc/flanneld/etcdcli.crt
     Changes:

Summary for kubeminion-10.0.6.133
-------------
Succeeded: 57
Failed:     3
-------------
Total states run:     60
Total run time:   83.921 s
kubeminion-10.0.6.115:

Summary for kubeminion-10.0.6.115
-------------
Succeeded: 60
Failed:     0
-------------
Total states run:     60
Total run time:   84.089 s
kubeminion-10.0.6.94:

Summary for kubeminion-10.0.6.94
-------------
Succeeded: 60
Failed:     0
-------------
Total states run:     60
Total run time:   84.123 s
kubeminion-10.0.1.249:
----------
          ID: /var/run/kubernetes/kubelet.crt
    Function: x509.certificate_managed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1744, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1702, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/x509.py", line 442, in certificate_managed
                  new = __salt__['x509.create_certificate'](testrun=True, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/modules/x509.py", line 1324, in create_certificate
                  arg=str(kwargs))[ca_server]
              KeyError: 'kubemaster-10.0.6.167'
     Started: 18:14:06.830413
    Duration: 20061.499 ms
     Changes:
----------
          ID: Setup kubelet service
    Function: service.running
        Name: kubelet
      Result: False
     Comment: One or more requisite failed: kube.kubelet_certs./var/run/kubernetes/kubelet.crt
     Changes:

Summary for kubeminion-10.0.1.249
-------------
Succeeded: 58
Failed:     2
-------------
Total states run:     60
Total run time:   84.006 s
kubeminion-10.0.7.201:

Summary for kubeminion-10.0.7.201
-------------
Succeeded: 60
Failed:     0
-------------
Total states run:     60
Total run time:   84.178 s
kubeminion-10.0.1.210:

Summary for kubeminion-10.0.1.210
-------------
Succeeded: 60
Failed:     0
-------------
Total states run:     60
Total run time:   84.064 s
kubeminionelastic-10.0.1.18:

Summary for kubeminionelastic-10.0.1.18
-------------
Succeeded: 60
Failed:     0
-------------
Total states run:     60
Total run time:   84.497 s
kubeminion-10.0.6.46:

Summary for kubeminion-10.0.6.46
-------------
Succeeded: 60
Failed:     0
-------------
Total states run:     60
Total run time:   84.163 s
kubeminion-10.0.1.48:
----------
          ID: /etc/flanneld/etcdcli.crt
    Function: x509.certificate_managed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1744, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1702, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/x509.py", line 442, in certificate_managed
                  new = __salt__['x509.create_certificate'](testrun=True, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/modules/x509.py", line 1324, in create_certificate
                  arg=str(kwargs))[ca_server]
              KeyError: 'kubemaster-10.0.6.167'
     Started: 18:13:26.267324
    Duration: 20059.758 ms
     Changes:
----------
          ID: /etc/flanneld/etcdcli.crt
    Function: file.managed
      Result: False
     Comment: One or more requisite failed: flanneld.certificates./etc/flanneld/etcdcli.crt
     Changes:
----------
          ID: Flanneld service is running
    Function: service.running
        Name: flanneld
      Result: False
     Comment: One or more requisite failed: flanneld.certificates./etc/flanneld/etcdcli.crt
     Changes:

Summary for kubeminion-10.0.1.48
-------------
Succeeded: 57
Failed:     3
-------------
Total states run:     60
Total run time:   84.236 s
kubemaster-10.0.6.167:

Summary for kubemaster-10.0.6.167
--------------
Succeeded: 129
Failed:      0
--------------
Total states run:     129
Total run time:     8.168 s
```

Although the error does not appear if I run `highstate` on single node or smaller subset only: 

```
[root@ip-10-0-6-167 ~]# salt 'kubeminion-10.0.1.48' state.apply
[WARNING ] /usr/lib64/python2.7/site-packages/cffi/model.py:526: UserWarning: 'git_checkout_notify_t' has no values explicitly defined; next version will refuse to guess which integer type it is meant to be (unsigned/signed, int/long)
  % self._get_c_name())

[WARNING ] /usr/lib64/python2.7/site-packages/cffi/model.py:526: UserWarning: 'git_merge_tree_flag_t' has no values explicitly defined; next version will refuse to guess which integer type it is meant to be (unsigned/signed, int/long)
  % self._get_c_name())

kubeminion-10.0.1.48:

Summary for kubeminion-10.0.1.48
-------------
Succeeded: 60
Failed:     0
-------------
Total states run:     60
Total run time:    4.075 s
```

### Setup
This is the state that is failing:

```
{{ kube.kubelet.cert }}:
  x509.certificate_managed:
    - ca_server: {{ general.master_id }}
    - signing_policy: {{ kube.kubelet.cert_signing_policy }}
    - public_key: {{ kube.kubelet.key }}
    - CN: kubelet
    - subjectAltName: IP:{{ general.local_net.ip }},DNS:{{ general.local_net.hostname }}
    - days_remaining: 90
    - backup: True
```

Signing policy:
```
x509_signing_policies:
  kubelet:
    - minions: 'kube*'
    - signing_private_key: /etc/pki/ca.key
    - signing_cert: /etc/pki/ca.crt
    - C: US
    - ST: Washington
    - L: Seattle
    - basicConstraints: "critical CA:false"
    - keyUsage: "digitalSignature, keyEncipherment"
    - subjectKeyIdentifier: hash
    - authorityKeyIdentifier: keyid,issuer:always
    - days_valid: 180
    - copypath: /etc/pki/issued_certs/
```

### Versions Report

All nodes with same setup, issue observed both on 2016.11.0 and 2016.11.1

```
Salt Version:
           Salt: 2016.11.1

Dependency Versions:
           cffi: 1.6.0
       cherrypy: 3.2.2
       dateutil: 2.6.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.21.0
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.4
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.2.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

**Comment by gtmanfred** [comment]
Unfortunately there does not appear to be a way to do that.

The problem is that the master is timing out running the commands, because it can only run a few at a time.

In the Nitrogen release, there will be a state keyword argument called `retry` so that you can specify to retry the state more than once for instances like this. https://github.com/saltstack/salt/blob/develop/salt/state.py#L86

I do not see a way to increase the timeout of the publish.publish command.

**Comment by veverjak** [comment]
ok, thanks for info.
