### ISSUE TITLE
`salt.cmd` runner raises TypeError when function returns bool

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#38638]
### Description of Issue/Question

I was testing the new `salt.cmd` runner: https://docs.saltstack.com/en/develop/topics/releases/2016.11.0.html#additional-features
(which I find very handy in some particular cases).

When the command does not return a python dict, it raises a TypeError exception.

Let's just consider a simple to reproduce case:

```
$ sudo salt-run salt.cmd hipchat.send_message 1234 'Yo @mircea' ''
Exception occurred in runner salt.cmd: Traceback (most recent call last):
  File "/state/home/mircea/salt/salt/client/mixins.py", line 399, in _low
    if 'data' in data['return']:
TypeError: argument of type 'bool' is not iterable
```

The `hipchat.send_message` command returns True or False depending if able to post in the hipchat room.

## Salt Version:

```
salt --versions-report
Salt Version:
           Salt: 2016.11.0-604-gff110dc

Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.6

System Versions:
           dist: debian 8.2
        machine: x86_64
        release: 4.1.3-cloudflare
         system: Linux
        version: debian 8.2
```

**Comment by gtmanfred** [comment]
@mirceaulinic thanks for reporting this, we will get it fixed.

Thanks,
Daniel

**Comment by remyd1** [comment]
Hi,

Same error since release 2016.11.2 (Carbon) with some salt-run command :

```bash
salt-run cache.clear_all

Exception occurred in runner cache.clear_all: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 397, in _low
    if 'data' in data['return']:
TypeError: argument of type 'bool' is not iterable

salt-run fileserver.update

Exception occurred in runner fileserver.update: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 397, in _low
    if 'data' in data['return']:
TypeError: argument of type 'bool' is not iterable
```

I did not see that error in previous versions.

Best regards,

Rémy

**Comment by mirceaulinic** [comment]
There are quite a few runners having this issue in Carbon.

Just saw https://github.com/saltstack/salt/issues/39100 complaining about the same boolean output.

**Comment by mirceaulinic** [comment]
Submitted https://github.com/saltstack/salt/pull/39107 as a fix

**Comment by mirceaulinic** [comment]
Closed via https://github.com/saltstack/salt/commit/bf61ec951530d83610938030b6c12d9091b44f28

**Comment by danieloliveira079** [comment]
Hello,

I have just installed Salt Master and configuring gitfs.

When running `sudo salt-run fileserver.update` I am still receiving the error:

```
Exception occurred in runner fileserver.update: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 397, in _low
    if 'data' in data['return']:
TypeError: argument of type 'bool' is not iterable
```

```
salt --versions-report
Salt Version:
           Salt: 2016.11.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.4.0-62-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by gtmanfred** [comment]
Correct, it will be in the next release of salt later this month.  You can
also hot patch the files with the pull request linked above.
