### ISSUE TITLE
Unable to execute commands on Ubuntu Xenial

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#38636]
### Description of Issue/Question

I've just installed a Salt master in a cloud environment and I am unable to run commands. Perhaps my fault, but I did this quite a few times (even on a OS X) and I didn't not see this error before.

```
$ sudo salt vmx test.ping
[WARNING ] jid does not exist
[WARNING ] Returner unavailable:
[ERROR   ] Exception occurred in Subscriber while handling stream: 'int' object has no attribute '__getitem__'
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: 'int' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/salt/scripts.py", line 464, in salt_main
    client.run()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/salt/cli/salt.py", line 168, in run
    for full_ret in cmd_func(**kwargs):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/salt/client/__init__.py", line 709, in cmd_cli
    **kwargs):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/salt/client/__init__.py", line 1421, in get_cli_event_returns
    **kwargs
  File "/home/ubuntu/.local/lib/python2.7/site-packages/salt/client/__init__.py", line 1031, in get_iter_returns
    for raw in ret_iter:
  File "/home/ubuntu/.local/lib/python2.7/site-packages/salt/client/__init__.py", line 966, in get_returns_no_block
    no_block=True, auto_reconnect=self.auto_reconnect)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/salt/utils/event.py", line 644, in get_event
    ret = self._get_event(wait, tag, match_func, no_block)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/salt/utils/event.py", line 538, in _get_event
    raw = self.subscriber.read_sync(timeout=wait)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/salt/transport/ipc.py", line 690, in read_sync
    return ret_future.result()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tornado/gen.py", line 1024, in run
    yielded = self.gen.send(value)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/salt/transport/ipc.py", line 666, in _read_sync
    raise exc_to_raise  # pylint: disable=E0702
TypeError: 'int' object has no attribute '__getitem__'
```

### Setup

I currently have one (proxy) minion, but it starts normally:

```
[INFO    ] Minion is ready to receive requests!
[DEBUG   ] Minion of "localhost" is handling event tag 'module_refresh'
[DEBUG   ] Refreshing modules. Notify=False
[DEBUG   ] Reading configuration from /etc/salt/proxy
[DEBUG   ] Including configuration from '/etc/salt/proxy.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/proxy.d/_schedule.conf
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[DEBUG   ] Minion of "localhost" is handling event tag 'pillar_refresh'
[DEBUG   ] Refreshing pillar
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/proxy', 'vmx', 'tcp://127.0.0.1:4506', 'aes')
[DEBUG   ] Re-using AsyncAuth for ('/etc/salt/pki/proxy', 'vmx', 'tcp://127.0.0.1:4506')
[DEBUG   ] Minion of "localhost" is handling event tag '/salt/minion/minion_schedule_add_complete'
[DEBUG   ] Minion of "localhost" is handling event tag '/salt/minion/minion_schedule_delete_complete'
[DEBUG   ] Minion of "localhost" is handling event tag '/salt/minion/minion_schedule_delete_complete'
[DEBUG   ] Minion of "localhost" is handling event tag 'module_refresh'
[DEBUG   ] Refreshing modules. Notify=False
[DEBUG   ] Reading configuration from /etc/salt/proxy
[DEBUG   ] Including configuration from '/etc/salt/proxy.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/proxy.d/_schedule.conf
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[DEBUG   ] Minion of "localhost" is handling event tag 'pillar_refresh'
[DEBUG   ] Refreshing pillar
[DEBUG   ] Re-using AsyncZeroMQReqChannel for ('/etc/salt/pki/proxy', 'vmx', 'tcp://127.0.0.1:4506', 'aes')
[DEBUG   ] Loaded minion key: /etc/salt/pki/proxy/minion.pem
[DEBUG   ] Refreshing modules. Notify=False
[DEBUG   ] Reading configuration from /etc/salt/proxy
[DEBUG   ] Including configuration from '/etc/salt/proxy.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/proxy.d/_schedule.conf
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[DEBUG   ] Loaded minion key: /etc/salt/pki/proxy/minion.pem
[DEBUG   ] Refreshing modules. Notify=False
[DEBUG   ] Reading configuration from /etc/salt/proxy
[DEBUG   ] Including configuration from '/etc/salt/proxy.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/proxy.d/_schedule.conf
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[DEBUG   ] LazyLoaded config.merge
[DEBUG   ] LazyLoaded mine.update
[INFO    ] Running scheduled job: __mine_interval
[DEBUG   ] schedule: This job was scheduled with jid_include, adding to cache (jid_include defaults to True)
[DEBUG   ] schedule: This job was scheduled with a max number of 2
[DEBUG   ] schedule.handle_func: adding this job to the jobcache with data {'fun_args': [], 'jid': '20170109125548413361', 'schedule': '__mine_interval', 'pid': 23409, 'fun': 'mine.update', 'id': 'vmx'}
[DEBUG   ] LazyLoaded mine.update
[DEBUG   ] LazyLoaded config.merge
[DEBUG   ] schedule.handle_func: Removing /var/cache/salt/proxy/vmx/proc/20170109125548413361
```

### Steps to Reproduce Issue

Master logs:

```

2017-01-09 12:51:36,698 [salt.utils.verify][WARNING ][21133] Insecure logging configuration detected! Sensitive data may be logged.
2017-01-09 12:51:36,864 [salt.utils.lazy                                      ][DEBUG   ][20267] LazyLoaded local_cache.prep_jid
2017-01-09 12:51:36,865 [salt.utils.event                                     ][DEBUG   ][20267] Sending event - data = {'_stamp': '2017-01-09T12:51:36.864705', 'minions': ['vmx']}
2017-01-09 12:51:36,865 [salt.utils.event                                     ][DEBUG   ][20267] Sending event - data = {'tgt_type': 'glob', 'jid': '20170109125136864363', 'tgt': 'vmx', '_stamp': '2017-01-09T12:51:36.864927', 'user': 'sudo_ubuntu', 'arg': [], 'fun': 'test.ping', 'minions': ['vmx']}
2017-01-09 12:51:36,865 [salt.loaded.int.returner.local_cache                 ][DEBUG   ][20267] Adding minions for job 20170109125136864363: ['vmx']
2017-01-09 12:51:36,865 [salt.master                                          ][INFO    ][20267] User sudo_ubuntu Published command test.ping with jid 20170109125136864363
2017-01-09 12:51:36,866 [salt.master                                          ][DEBUG   ][20267] Published command details {'tgt_type': 'glob', 'jid': '20170109125136864363', 'tgt': 'vmx', 'ret': '', 'user': 'sudo_ubuntu', 'arg': [], 'fun': 'test.ping'}
2017-01-09 12:51:36,868 [salt.client      ][WARNING ][21133] jid does not exist
2017-01-09 12:51:36,868 [salt.client      ][WARNING ][21133] Returner unavailable:
2017-01-09 12:51:36,869 [salt.transport.ipc][ERROR   ][21133] Exception occurred in Subscriber while handling stream: 'int' object has no attribute '__getitem__'
2017-01-09 12:51:36,871 [salt.log.setup   ][ERROR   ][21133] An un-handled exception was caught by salt's global exception handler:
TypeError: 'int' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/salt/scripts.py", line 464, in salt_main
    client.run()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/salt/cli/salt.py", line 168, in run
    for full_ret in cmd_func(**kwargs):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/salt/client/__init__.py", line 709, in cmd_cli
    **kwargs):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/salt/client/__init__.py", line 1421, in get_cli_event_returns
    **kwargs
  File "/home/ubuntu/.local/lib/python2.7/site-packages/salt/client/__init__.py", line 1031, in get_iter_returns
    for raw in ret_iter:
  File "/home/ubuntu/.local/lib/python2.7/site-packages/salt/client/__init__.py", line 966, in get_returns_no_block
    no_block=True, auto_reconnect=self.auto_reconnect)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/salt/utils/event.py", line 644, in get_event
    ret = self._get_event(wait, tag, match_func, no_block)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/salt/utils/event.py", line 538, in _get_event
    raw = self.subscriber.read_sync(timeout=wait)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/salt/transport/ipc.py", line 690, in read_sync
    return ret_future.result()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tornado/gen.py", line 1024, in run
    yielded = self.gen.send(value)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/salt/transport/ipc.py", line 666, in _read_sync
    raise exc_to_raise  # pylint: disable=E0702
TypeError: 'int' object has no attribute '__getitem__'
2017-01-09 12:51:36,911 [salt.utils.lazy                                      ][DEBUG   ][20268] LazyLoaded local_cache.prep_jid
2017-01-09 12:51:37,011 [salt.utils.job                                       ][INFO    ][20268] Got return from vmx for job 20170109125136864363
2017-01-09 12:51:37,012 [salt.utils.event                                     ][DEBUG   ][20268] Sending event - data = {'fun_args': [], 'jid': '20170109125136864363', 'return': True, 'retcode': 0, 'success': True, 'cmd': '_return', '_stamp': '2017-01-09T12:51:37.011451', 'fun': 'test.ping', 'id': 'vmx'}
```

Proxy logs:

```

[INFO    ] User sudo_ubuntu Executing command test.ping with jid 20170109125136864363
[DEBUG   ] Command details {'tgt_type': 'glob', 'jid': '20170109125136864363', 'tgt': 'vmx', 'ret': '', 'user': 'sudo_ubuntu', 'arg': [], 'fun': 'test.ping'}
[INFO    ] Starting a new job with PID 21049
[DEBUG   ] LazyLoaded test.ping
[DEBUG   ] LazyLoaded direct_call.get
[DEBUG   ] Minion return retry timer set to 9 seconds (randomized)
[INFO    ] Returning information for job: 20170109125136864363
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/proxy', 'vmx', 'tcp://127.0.0.1:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/proxy', 'vmx', 'tcp://127.0.0.1:4506')
```

### Versions Report

```bash
salt --versions-report
Salt Version:
           Salt: 2016.11.1

Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.9.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.6

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-53-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by mirceaulinic** [comment]
RTFM: https://docs.saltstack.com/en/latest/topics/installation/ubuntu.html!!!
