### ISSUE TITLE
salt-cloud: AttributeError: 'list' object has no attribute 'copy'

### ISSUE THREAD

**Issue by hpapaxen** [saltstack/salt#38662]
### Description of Issue/Question

Hey all, I'm trying to provision a new ec2 instance with salt-cloud with no avail. Any help would be appreciated

## Cloud Profile
```
base_ec2_slave:
  provider: levelup-ec2-east1-hadoop-instance
  script: bootstrap-salt
  image: ami-e13739f6
  size: m3.xlarge
  ssh_username: ubuntu
  tag: {'Environment': 'prod', 'Role': 'slave', }
  sync_after_install: grains
  del_root_vol_on_destroy: True
  del_all_vol_on_destroy: True
  ebs_optimized: True
  block_device_mappings:
    - DeviceName: /dev/sdd
    - Ebs.VolumeSize: 1000
    - Ebs.VolumeType: st1
    - DeviceName: /dev/sdf
    - Ebs.VolumeSize: 1000
    - Ebs.VolumeType: st1
```
## Cloud Provider
```
ec2-east1-hadoop-instance:
  minion:
    master: ip-of-master
  grains:
    - 'role:hadoop'
    - 'role:hbase'

  ssh_interface: private_ips

  id: 'use-instance-role-credentials'
  key: 'use-instance-role-credentials'

  private_key: /etc/salt/default-key-pair.pem
  keyname: default-key-pair

  securitygroup: default

  location: us-east-1
  availability_zone: us-east-1b

  ssh_username: ubuntu

  iam_profile: 'iam-profile'

  driver: ec2
```
### Steps to Reproduce Issue

Run salt-cloud -p base_ec2_slave slave1

## Partial logs
```
[DEBUG   ] AWS Request: https://ec2.us-east-1.amazonaws.com/?Action=DescribeVolumes&Version=2014-10-01&VolumeId.0=vol-059e1f216c3ed9985
[DEBUG   ] AWS Response Status Code: 200
[DEBUG   ] Function: describe_volumes, Watched arg: status, Response: available
[DEBUG   ] {'Action': 'AttachVolume', 'InstanceId': 'i-0efb7051d5afa6c6e', 'VolumeId': 'vol-059e1f216c3ed9985', 'Device': '/dev/sdf'}
[DEBUG   ] Waiting for VM IP. Giving up in 00:10:00.
[DEBUG   ] Using AWS endpoint: ec2.us-east-1.amazonaws.com
[DEBUG   ] AWS Request: https://ec2.us-east-1.amazonaws.com/?Action=AttachVolume&Device=%2Fdev%2Fsdf&InstanceId=i-0efb7051d5afa6c6e&Version=2014-10-01&VolumeId=vol-059e1f216c3ed9985
[DEBUG   ] AWS Response Status Code: 200
[DEBUG   ] Using AWS endpoint: ec2.us-east-1.amazonaws.com
[DEBUG   ] AWS Request: https://ec2.us-east-1.amazonaws.com/?Action=DescribeInstances&InstanceId.1=i-0efb7051d5afa6c6e&Version=2014-10-01
[DEBUG   ] AWS Response Status Code: 200
[DEBUG   ] Using AWS endpoint: ec2.us-east-1.amazonaws.com
[DEBUG   ] AWS Request: https://ec2.us-east-1.amazonaws.com/?Action=ModifyInstanceAttribute&BlockDeviceMapping.2.DeviceName=%2Fdev%2Fsdf&BlockDeviceMapping.2.Ebs.DeleteOnTermination=False&InstanceId=i-0efb7051d5afa6c6e&Version=2014-10-01
[DEBUG   ] AWS Response Status Code: 200
[DEBUG   ] Using AWS endpoint: ec2.us-east-1.amazonaws.com
[DEBUG   ] AWS Request: https://ec2.us-east-1.amazonaws.com/?Action=DescribeInstances&InstanceId.1=i-0efb7051d5afa6c6e&Version=2014-10-01
[DEBUG   ] AWS Response Status Code: 200
[INFO    ] vol-059e1f216c3ed9985 attached to i-0efb7051d5afa6c6e (aka prod-slave1) as device /dev/sdf
[ERROR   ] There was a profile error: 'list' object has no attribute 'copy'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 284, in run
    self.config.get('names')
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1458, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1288, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 2665, in create
    for key, value in six.iteritems(__utils__['cloud.bootstrap'](vm_, __opts__)):
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 347, in bootstrap
    minion_conf = salt.utils.cloud.minion_config(opts, vm_)
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 252, in minion_config
    'grains', vm_, opts, default={}, search_global=True
  File "/usr/lib/python2.7/dist-packages/salt/config/__init__.py", line 2813, in get_cloud_config_value
    value.update(details[name].copy())
AttributeError: 'list' object has no attribute 'copy'
```
### Versions Report
```
Salt Version:
           Salt: 2016.11.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-59-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by gtmanfred** [comment]
Your grains object should be a dictionary.

```
ec2-east1-hadoop-instance:
  minion:
    master: ip-of-master
  grains:
    role:
      - hadoop
      - hbase
```

**Comment by hpapaxen** [comment]
Worked like a charm. Thanks!
