### ISSUE TITLE
Keys are returned to Mongo with a '.' by way of 'salt-run survey-hash'

### ISSUE THREAD

**Issue by d101nelson** [saltstack/salt#38727]
### Description of Issue/Question

Salt is returning key data to MongoDB which contains a dot ('.').  The key data appears to be the mongo configuration as defined within '/etc/salt/master'.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

- Install/configure mongodb on localhost (mongodb 3.4 was used in this instance)
- Configure 'master job cache' in /etc/salt/master and restart salt-master
- Relevant section w/in /etc/salt/master:
```master_job_cache: mongo
mongo.db: salt-cache
mongo.host: localhost
mongo.user: salt
mongo.password: XXX
mongo.port: 27017
```
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

- Issue command
```salt-run survey.hash '*' cmd.run 'uname -m'```

- Error output from above command:
```[ERROR   ] An un-handled exception was caught by salt's global exception handler:
InvalidDocument: key '__pub_mongo.host' must not contain '.'
Traceback (most recent call last):
  File "/opt/apps/unix/salt/bin/salt-run", line 11, in <module>
    load_entry_point('salt==2016.3.3', 'console_scripts', 'salt-run')()
  File "/opt/apps/unix/salt-2016.3.3/lib/python2.7/site-packages/salt/scripts.py", line 375, in salt_run
    client.run()
  File "/opt/apps/unix/salt-2016.3.3/lib/python2.7/site-packages/salt/cli/run.py", line 41, in run
    ret = runner.run()
  File "/opt/apps/unix/salt-2016.3.3/lib/python2.7/site-packages/salt/runner.py", line 191, in run
    False)  # Don't daemonize
  File "/opt/apps/unix/salt-2016.3.3/lib/python2.7/site-packages/salt/client/mixins.py", line 432, in _proc_function
    return self.low(fun, low)
  File "/opt/apps/unix/salt-2016.3.3/lib/python2.7/site-packages/salt/client/mixins.py", line 379, in low
    mminion=self.mminion,
  File "/opt/apps/unix/salt-2016.3.3/lib/python2.7/site-packages/salt/utils/job.py", line 90, in store_job
    mminion.returners[fstr](load)
  File "/opt/apps/unix/salt-2016.3.3/lib/python2.7/site-packages/salt/returners/mongo_future_return.py", line 197, in returner
    mdb.saltReturns.insert_one(sdata.copy())
  File "/opt/apps/unix/salt-2016.3.3/lib/python2.7/site-packages/pymongo/collection.py", line 657, in insert_one
    bypass_doc_val=bypass_document_validation),
  File "/opt/apps/unix/salt-2016.3.3/lib/python2.7/site-packages/pymongo/collection.py", line 562, in _insert
    check_keys, manipulate, write_concern, op_id, bypass_doc_val)
  File "/opt/apps/unix/salt-2016.3.3/lib/python2.7/site-packages/pymongo/collection.py", line 543, in _insert_one
    check_keys=check_keys)
  File "/opt/apps/unix/salt-2016.3.3/lib/python2.7/site-packages/pymongo/pool.py", line 424, in command
    self._raise_connection_failure(error)
  File "/opt/apps/unix/salt-2016.3.3/lib/python2.7/site-packages/pymongo/pool.py", line 552, in _raise_connection_failure
    raise error
InvalidDocument: key '__pub_mongo.host' must not contain '.'
Traceback (most recent call last):
  File "/opt/apps/unix/salt/bin/salt-run", line 11, in <module>
    load_entry_point('salt==2016.3.3', 'console_scripts', 'salt-run')()
  File "/opt/apps/unix/salt-2016.3.3/lib/python2.7/site-packages/salt/scripts.py", line 375, in salt_run
    client.run()
  File "/opt/apps/unix/salt-2016.3.3/lib/python2.7/site-packages/salt/cli/run.py", line 41, in run
    ret = runner.run()
  File "/opt/apps/unix/salt-2016.3.3/lib/python2.7/site-packages/salt/runner.py", line 191, in run
    False)  # Don't daemonize
  File "/opt/apps/unix/salt-2016.3.3/lib/python2.7/site-packages/salt/client/mixins.py", line 432, in _proc_function
    return self.low(fun, low)
  File "/opt/apps/unix/salt-2016.3.3/lib/python2.7/site-packages/salt/client/mixins.py", line 379, in low
    mminion=self.mminion,
  File "/opt/apps/unix/salt-2016.3.3/lib/python2.7/site-packages/salt/utils/job.py", line 90, in store_job
    mminion.returners[fstr](load)
  File "/opt/apps/unix/salt-2016.3.3/lib/python2.7/site-packages/salt/returners/mongo_future_return.py", line 197, in returner
    mdb.saltReturns.insert_one(sdata.copy())
  File "/opt/apps/unix/salt-2016.3.3/lib/python2.7/site-packages/pymongo/collection.py", line 657, in insert_one
    bypass_doc_val=bypass_document_validation),
  File "/opt/apps/unix/salt-2016.3.3/lib/python2.7/site-packages/pymongo/collection.py", line 562, in _insert
    check_keys, manipulate, write_concern, op_id, bypass_doc_val)
  File "/opt/apps/unix/salt-2016.3.3/lib/python2.7/site-packages/pymongo/collection.py", line 543, in _insert_one
    check_keys=check_keys)
  File "/opt/apps/unix/salt-2016.3.3/lib/python2.7/site-packages/pymongo/pool.py", line 424, in command
    self._raise_connection_failure(error)
  File "/opt/apps/unix/salt-2016.3.3/lib/python2.7/site-packages/pymongo/pool.py", line 552, in _raise_connection_failure
    raise error
bson.errors.InvalidDocument: key '__pub_mongo.host' must not contain '.'
```
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

pymongo version is 3.4.0. Pymongo is only installed on the salt master.

The salt master and minions are the same salt version (2016.3.3).

Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 8.0.0
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 2.0.8
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.11 (default, Oct  7 2016, 16:26:33)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.4.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.4.1
            ZMQ: 4.1.5
 
System Versions:
           dist: redhat 7.2 Maipo
        machine: x86_64
        release: 3.10.0-327.36.1.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.2 Maipo

**Comment by gtmanfred** [comment]
Can you check if you can define mongo like the following.

```
mongo:
  db: <database name>
  host: <server ip address>
  user: <MongoDB username>
  password: <MongoDB user password>
  port: 27017
```

Thanks,
Daniel

**Comment by d101nelson** [comment]
@gtmanfred Yes, that works.

**Comment by gtmanfred** [comment]
Cool. I would use that, and we should probably update the documentation to use that method instead of the method with `.` to reduce the probability of colliding with the dot notation in mongo.

Thanks,
Daniel

**Comment by d101nelson** [comment]
@gtmanfred Will do. Thank you.

**Comment by d101nelson** [comment]
@gtmanfred Well, this looks to go a bit deeper than just the mongo config within the master's config.  I just ran into again but with pillar data.  My pillar data is similar to the following:
```
cups:
  servers:
    - server1.example.com
    - server2.example.com
  cupsd_conf_src:
    server1.example.com: 'salt://cups/files/cupsd.conf-server1.example.com'
    server2.example.com: 'salt://cups/files/cupsd.conf-server2.example.com'
```
Mongo doesn't care for the structure under 'cupsd_conf_src'.  The error output:
```
InvalidDocument: key 'server1.example.com' must not contain '.'
2017-01-17 13:32:31,049 [salt.master      ][ERROR   ][8954] Error in function _return:
Traceback (most recent call last):
  File "/opt/apps/unix/salt-2016.3.3/lib/python2.7/site-packages/salt/master.py", line 1558, in run_func
    ret = getattr(self, func)(load)
  File "/opt/apps/unix/salt-2016.3.3/lib/python2.7/site-packages/salt/master.py", line 1371, in _return
    self.opts, load, event=self.event, mminion=self.mminion)
  File "/opt/apps/unix/salt-2016.3.3/lib/python2.7/site-packages/salt/utils/job.py", line 49, in store_job
    mminion.returners[saveload_fstr](load['jid'], load)
  File "/opt/apps/unix/salt-2016.3.3/lib/python2.7/site-packages/salt/returners/mongo_future_return.py", line 209, in save_load
    mdb.jobs.insert_one(load.copy())
  File "/opt/apps/unix/salt-2016.3.3/lib/python2.7/site-packages/pymongo/collection.py", line 657, in insert_one
    bypass_doc_val=bypass_document_validation),
  File "/opt/apps/unix/salt-2016.3.3/lib/python2.7/site-packages/pymongo/collection.py", line 562, in _insert
    check_keys, manipulate, write_concern, op_id, bypass_doc_val)
  File "/opt/apps/unix/salt-2016.3.3/lib/python2.7/site-packages/pymongo/collection.py", line 543, in _insert_one
    check_keys=check_keys)
  File "/opt/apps/unix/salt-2016.3.3/lib/python2.7/site-packages/pymongo/pool.py", line 424, in command
    self._raise_connection_failure(error)
  File "/opt/apps/unix/salt-2016.3.3/lib/python2.7/site-packages/pymongo/pool.py", line 552, in _raise_connection_failure
    raise error
InvalidDocument: key 'server1.example.com' must not contain '.'
```
