### ISSUE TITLE
salt-ssh: vault fails to use config

### ISSUE THREAD

**Issue by danielmotaleite** [saltstack/salt#38830]
### Description of Issue/Question
When trying to use vault with salt-ssh i follow the doc [here](https://docs.saltstack.com/en/latest/ref/pillar/all/salt.pillar.vault.html) 

After fixing what i assume it is one error, the the myvault / myvault_config different names (it still fails with the original names), i have this in my master:
```
$ cat conf/master 
root_dir: /tmp/
state_verbose: False
state_output: Full

file_roots:
  base:
    - srv

pillar_roots:
  base:
    - pillar

myvault:
  vault.host: 127.0.0.1
  vault.port: 8200
  vault.scheme: http  # Optional; default is https
  vault.token: 012356789abcdef  # Required, unless set in environment

ext_pillar:
  - vault: myvault path=secret/salt

```

Running config.get it works:

```
$ salt-ssh casper config.get myvault
[ERROR   ] [Errno -2] Name or service not known
[CRITICAL] Pillar render error: Failed to load ext_pillar vault: [Errno -2] Name or service not known
casper:
    ----------
    vault.host:
        127.0.0.1
    vault.port:
        8200
    vault.scheme:
        http
    vault.token:
        012356789abcdef

```

yet doing salt-ssh -l debug casper  pillar.items i get this

```
[DEBUG   ] LazyLoaded vault.ext_pillar
[DEBUG   ] Missing configuration file: /etc/salt/minion
[DEBUG   ] Guessing ID. The id can be explicitly set in /etc/salt/minion
[DEBUG   ] Found minion id from generate_minion_id(): danielleite
[DEBUG   ] Requesting URL https://None:None/v1/secret/salt using GET method
[ERROR   ] [Errno -2] Name or service not known
[CRITICAL] Pillar render error: Failed to load ext_pillar vault: [Errno -2] Name or service not known
[DEBUG   ] LazyLoaded pillar.items
```

Notice the ```None:None``` . It seems that salt-ssh is not getting the vault config 

```
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.9.2-040902-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by danielmotaleite** [comment]
editing this file  ```/usr/lib/python2.7/dist-packages/salt/pillar/vault.py``` on line 80 we have:

```
        profile = __opts__.get(profile_name, {})
```
If i replace this with this code
```
        profile = __opts__.get("__master_opts__").get(profile_name, {})
```

i get the correct URL:

```
[DEBUG   ] Requesting URL https://127.0.0.1:8200/v1/secret/salt using GET method

```
but i do not know if i can do this blindly

**Comment by Ch3LL** [comment]
@danielmotaleite after looking through the code you have the right idea but I think the better fix is going to be adding 'master_opts' to __opts__ when initializing the salt-ssh client. My guess is somewhere in `client/ssh/__init__.py` we would need to do so. 

ping @thatch45 can you confirm that this is the correct fix. I can see `master_opts` being added to context but not sure we want to add it to opts as well in ssh.

**Comment by thatch45** [comment]
master_opts should show up in opts the same way in salt-ssh that it does in regular master/minion salt

**Comment by Ch3LL** [comment]
@thatch45 so would the solution for this issue be to go through each pillar file and add something similar to:

```
if __opts__.get('__master_opts__"):
    profile = __opts__.get("__master_opts__").get(profile_name, {})
else:
    profile = __opts__.get(profile_name, {})
```

Anytime there is an attempt to query something in the master config? It seems this profile_name works when running in a normal salt setup obviously because profile_name is in opts and you don't have to query master_opts.*.

**Comment by thatch45** [comment]
@Ch3LL upon closer inspection I think this is a better approach, to make sure that the pillar has the master opts at the top level just like it does in the standard salt master

**Comment by thatch45** [comment]
@danielmotaleite please try out that patch from the PR I just submitted and let me know if it solve the problem please :)

**Comment by danielmotaleite** [comment]
I applied the PR:
```
# patch -p1 < 68d64491741f6978e04c677202d5896af122dd96.patch 
patching file salt/client/ssh/__init__.py
Hunk #1 succeeded at 898 (offset 2 lines).
```
then run  ```salt-ssh -l debug casper pillar.items``` and got this error:

```
[PROFILE ] Time (in seconds) to render '/home/danielleite/git/private/provisioners/salt-ssh/conf/roster' using 'yaml' renderer: 0.00973510742188
[DEBUG   ] Matched minions: {'casper': OrderedDict([('host', '192.168.11.19')])}
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[DEBUG   ] Updating roots fileserver cache
[DEBUG   ] LazyLoaded local_cache.prep_jid
[DEBUG   ] Adding minions for job 20170125180338313468: ['casper']
[DEBUG   ] LazyLoaded pillar.items
[DEBUG   ] Performing shimmed, blocking command as follows:
test.opts_pkg
[DEBUG   ] Executed SHIM command. Command logged to TRACE
[DEBUG   ] Child Forked! PID: 17723  STDOUT_FD: 12  STDERR_FD: 15
[DEBUG   ] VT: Salt-SSH SHIM Terminal Command executed. Logged to TRACE
[DEBUG   ] RETCODE 192.168.101.19: 0
[ERROR   ] An un-handled exception from the multiprocessing process 'MultiprocessingProcess-1' was caught:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/process.py", line 644, in _run
    return self._original_run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 418, in handle_routine
    stdout, stderr, retcode = single.run()
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 834, in run
    stdout, retcode = self.run_wfunc()
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 906, in run_wfunc
    opts_pkg.get('environment', 'base')
  File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 265, in __init__
    self.actual_file_roots = opts['file_roots']
TypeError: 'NoneType' object has no attribute '__getitem__'
Process MultiprocessingProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/dist-packages/salt/utils/process.py", line 644, in _run
    return self._original_run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 418, in handle_routine
    stdout, stderr, retcode = single.run()
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 834, in run
    stdout, retcode = self.run_wfunc()
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 906, in run_wfunc
    opts_pkg.get('environment', 'base')
  File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 265, in __init__
    self.actual_file_roots = opts['file_roots']
TypeError: 'NoneType' object has no attribute '__getitem__'
[ERROR   ] Target 'casper' did not return any data, probably due to an error.
[DEBUG   ] LazyLoaded nested.output
```

**Comment by thatch45** [comment]
That is indeed a very odd stack trace, I have updated the PR with something else to try

**Comment by danielmotaleite** [comment]
The updated PR works fine, i get the vault info now
Thanks for the fix! :)

**Comment by thatch45** [comment]
Awesome! Thanks for verifying!
