### ISSUE TITLE
_freebsd_remotes_on() fails to parse sockstat output

### ISSUE THREAD

**Issue by alxwr** [saltstack/salt#38861]
### Description of Issue/Question

`_freebsd_remotes_on()` fails to parse `sockstat` output when the PID is more than five digits long.

### Setup

Many, many processes. :-)

```
USER     COMMAND    PID   FD PROTO  LOCAL ADDRESS         FOREIGN ADDRESS
salt-master python2.788045 23 tcp4  192.168.12.34:4505    192.168.12.45:12184
```

### Steps to Reproduce Issue

```
% salt 'main.*' test.ping                                                                                                                            [330/6416]
['salt-master', 'python2.781098', '23', 'tcp4', '192.168.12.11:4505', '192.168.12.2:60142']
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/local/bin/salt", line 11, in <module>
    load_entry_point('salt==2016.11.1', 'console_scripts', 'salt')()
  File "/usr/local/lib/python2.7/site-packages/salt/scripts.py", line 464, in salt_main
    client.run()
  File "/usr/local/lib/python2.7/site-packages/salt/cli/salt.py", line 168, in run
    for full_ret in cmd_func(**kwargs):
  File "/usr/local/lib/python2.7/site-packages/salt/client/__init__.py", line 709, incmd_cli
    **kwargs):
  File "/usr/local/lib/python2.7/site-packages/salt/client/__init__.py", line 1432, in get_cli_event_returns
    connected_minions = salt.utils.minions.CkMinions(self.opts).connected_ids()
  File "/usr/local/lib/python2.7/site-packages/salt/utils/minions.py", line 582, in connected_ids
    addrs = salt.utils.network.local_port_tcp(int(self.opts['publish_port']))
  File "/usr/local/lib/python2.7/site-packages/salt/utils/network.py", line 888, in local_port_tcp
    ret = _remotes_on(port, 'local_port')
  File "/usr/local/lib/python2.7/site-packages/salt/utils/network.py", line 924, in _remotes_on
    return _freebsd_remotes_on(port, which_end)
  File "/usr/local/lib/python2.7/site-packages/salt/utils/network.py", line 1037, in _freebsd_remotes_on
    remote = chunks[6]
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/local/bin/salt", line 11, in <module>
    load_entry_point('salt==2016.11.1', 'console_scripts', 'salt')()
  File "/usr/local/lib/python2.7/site-packages/salt/scripts.py", line 464, in salt_main
    client.run()
  File "/usr/local/lib/python2.7/site-packages/salt/cli/salt.py", line 168, in run
    for full_ret in cmd_func(**kwargs):
  File "/usr/local/lib/python2.7/site-packages/salt/client/__init__.py", line 709, incmd_cli
    **kwargs):
  File "/usr/local/lib/python2.7/site-packages/salt/client/__init__.py", line 1432, in get_cli_event_returns
    connected_minions = salt.utils.minions.CkMinions(self.opts).connected_ids()
  File "/usr/local/lib/python2.7/site-packages/salt/utils/minions.py", line 582, in connected_ids
    addrs = salt.utils.network.local_port_tcp(int(self.opts['publish_port']))
  File "/usr/local/lib/python2.7/site-packages/salt/utils/network.py", line 888, in local_port_tcp
    ret = _remotes_on(port, 'local_port')
  File "/usr/local/lib/python2.7/site-packages/salt/utils/network.py", line 924, in _remotes_on
    return _freebsd_remotes_on(port, which_end)
  File "/usr/local/lib/python2.7/site-packages/salt/utils/network.py", line 1037, in _freebsd_remotes_on
    remote = chunks[6]
IndexError: list index out of range
```

### Versions Report

```
Salt Version:
           Salt: 2016.11.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: 5.4.0
       dateutil: 2.5.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.25.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan  3 2017, 01:35:50)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.5

System Versions:
           dist:
        machine: amd64
        release: 10.3-RELEASE-p11
         system: FreeBSD
        version: Not Installed
```

I already fixed the problem for `2016.11` in https://github.com/saltstack/salt/pull/38859 and for `develop` in https://github.com/saltstack/salt/pull/38860.

**Comment by gtmanfred** [comment]
Thanks for the PR to fix this.

Daniel
