### ISSUE TITLE
`ext_job_cache` and `master_job_cache` don't work with proxy minions

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#38872]
### Description of Issue/Question

In the master config file I have configured:

```yaml
ext_job_cache: hipchat
master_job_cache: hipchat
```

as per https://docs.saltstack.com/en/latest/topics/jobs/external_cache.html.
When running a random command, I run into the errors below:

```bash
$ sudo salt edge01.sfo04 test.ping
[CRITICAL] Could not deserialize msgpack message.This often happens when trying to read a file not in binary modeTo see message payload, enable debug logging and retry. Exception: unpack(b) received extra data.
[ERROR   ] Uncaught exception, closing connection.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 407, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 934, in mark_future
    data = self.serial.loads(msg[0])
  File "/usr/lib/python2.7/dist-packages/salt/payload.py", line 137, in loads
    ret = msgpack.loads(msg, use_list=True, encoding=encoding)
  File "_unpacker.pyx", line 123, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:123)
ExtraData: unpack(b) received extra data.
[ERROR   ] Uncaught exception, closing connection.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 433, in _handle_events
    self._handle_recv()
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 465, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 407, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 934, in mark_future
    data = self.serial.loads(msg[0])
  File "/usr/lib/python2.7/dist-packages/salt/payload.py", line 137, in loads
    ret = msgpack.loads(msg, use_list=True, encoding=encoding)
  File "_unpacker.pyx", line 123, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:123)
ExtraData: unpack(b) received extra data.
[ERROR   ] Exception in callback None
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 866, in start
    handler_func(fd_obj, events)
  File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 433, in _handle_events
    self._handle_recv()
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 465, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 407, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 934, in mark_future
    data = self.serial.loads(msg[0])
  File "/usr/lib/python2.7/dist-packages/salt/payload.py", line 137, in loads
    ret = msgpack.loads(msg, use_list=True, encoding=encoding)
  File "_unpacker.pyx", line 123, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:123)
ExtraData: unpack(b) received extra data.
```

I did not start yet the master in debug mode (will do tomorrow and I will come back with more info).
Also, I'm not sure if this is a returner issue (although it does not look like):

```bash
$ sudo salt --return=hipchat edge01.sfo04 test.ping
edge01.sfo04:
    True
```

And works as expected.

### Setup

The master is also a minion for a higher level master.

### Versions Report

```bash
$ sudo salt --versions-report
Salt Version:
           Salt: 2016.11.0

Dependency Versions:
           cffi: 0.8.6
       cherrypy: 10.0.0
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.4
        machine: x86_64
        release: 4.4.17-cloudflare
         system: Linux
        version: debian 8.4
```

**Comment by mirceaulinic** [comment]
Had a couple of minutes to check this. It looks like the problem is with the `hipchat` returner actually (tested with `redis` and everything was OK).

In debug more, this is what I see on the master:

```python
[DEBUG   ] Could not LazyLoad hipchat.prep_jid: 'hipchat.prep_jid' is not available.
[ERROR   ] Returner 'hipchat' does not support function prep_jid
[ERROR   ] Error in function _return:
Traceback (most recent call last):
  File "/home/admin/salt/salt/master.py", line 1600, in run_func
    ret = getattr(self, func)(load)
  File "/home/admin/salt/salt/master.py", line 1408, in _return
    self.opts, load, event=self.event, mminion=self.mminion)
  File "/home/admin/salt/salt/utils/job.py", line 43, in store_job
    raise KeyError(emsg)
KeyError: "Returner 'hipchat' does not support function prep_jid"
```

I will see that next week, seems to be an easy fix.

**Comment by mirceaulinic** [comment]
@gtmanfred mind a quick question?
I can see there are a few returners that don't have the `prep_jid` function. Wondering if there wouldn't be smarter to move it inside the `salt.utils.job` rather than replicating the same code everywhere (i.e. https://github.com/saltstack/salt/blob/develop/salt/returners/redis_return.py#L251-L255)?
However, to fully solve this issue, any returner needs to implement also the `save_load` function, at least, which is returner-specific.
