### ISSUE TITLE
run command `salt '*' grains.items` faild

### ISSUE THREAD

**Issue by kira8565** [saltstack/salt#38902]
### Description of Issue/Question

run command `salt '*' grains.items` faild

### Setup
salt '*' grains.items

### Steps to Reproduce Issue
[WARNING ] jid does not exist
[WARNING ] Returner unavailable: 
[ERROR   ] Exception occurred in Subscriber while handling stream: 'int' object has no attribute '__getitem__'
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: 'int' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/usr/local/bin/salt", line 9, in <module>
    load_entry_point('salt==2016.11.1', 'console_scripts', 'salt')()
  File "/usr/local/lib/python2.7/dist-packages/salt/scripts.py", line 464, in salt_main
    client.run()
  File "/usr/local/lib/python2.7/dist-packages/salt/cli/salt.py", line 168, in run
    for full_ret in cmd_func(**kwargs):
  File "/usr/local/lib/python2.7/dist-packages/salt/client/__init__.py", line 709, in cmd_cli
    **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/salt/client/__init__.py", line 1421, in get_cli_event_returns
    **kwargs
  File "/usr/local/lib/python2.7/dist-packages/salt/client/__init__.py", line 1031, in get_iter_returns
    for raw in ret_iter:
  File "/usr/local/lib/python2.7/dist-packages/salt/client/__init__.py", line 966, in get_returns_no_block
    no_block=True, auto_reconnect=self.auto_reconnect)
  File "/usr/local/lib/python2.7/dist-packages/salt/utils/event.py", line 644, in get_event
    ret = self._get_event(wait, tag, match_func, no_block)
  File "/usr/local/lib/python2.7/dist-packages/salt/utils/event.py", line 538, in _get_event
    raw = self.subscriber.read_sync(timeout=wait)
  File "/usr/local/lib/python2.7/dist-packages/salt/transport/ipc.py", line 690, in read_sync
    return ret_future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1024, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python2.7/dist-packages/salt/transport/ipc.py", line 666, in _read_sync
    raise exc_to_raise  # pylint: disable=E0702
TypeError: 'int' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/usr/local/bin/salt", line 9, in <module>
    load_entry_point('salt==2016.11.1', 'console_scripts', 'salt')()
  File "/usr/local/lib/python2.7/dist-packages/salt/scripts.py", line 464, in salt_main
    client.run()
  File "/usr/local/lib/python2.7/dist-packages/salt/cli/salt.py", line 168, in run
    for full_ret in cmd_func(**kwargs):
  File "/usr/local/lib/python2.7/dist-packages/salt/client/__init__.py", line 709, in cmd_cli
    **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/salt/client/__init__.py", line 1421, in get_cli_event_returns
    **kwargs
  File "/usr/local/lib/python2.7/dist-packages/salt/client/__init__.py", line 1031, in get_iter_returns
    for raw in ret_iter:
  File "/usr/local/lib/python2.7/dist-packages/salt/client/__init__.py", line 966, in get_returns_no_block
    no_block=True, auto_reconnect=self.auto_reconnect)
  File "/usr/local/lib/python2.7/dist-packages/salt/utils/event.py", line 644, in get_event
    ret = self._get_event(wait, tag, match_func, no_block)
  File "/usr/local/lib/python2.7/dist-packages/salt/utils/event.py", line 538, in _get_event
    raw = self.subscriber.read_sync(timeout=wait)
  File "/usr/local/lib/python2.7/dist-packages/salt/transport/ipc.py", line 690, in read_sync
    return ret_future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1024, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python2.7/dist-packages/salt/transport/ipc.py", line 666, in _read_sync
    raise exc_to_raise  # pylint: disable=E0702
TypeError: 'int' object has no attribute '__getitem__'

### Versions Report
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jul 18 2016, 15:02:52)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.6
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.2.0-27-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by Ch3LL** [comment]
@kira8565 i'm not able to replicate this issue.

```
root@vagrant-ubuntu-trusty-64:~# salt --version
salt 2016.11.1 (Carbon)
root@vagrant-ubuntu-trusty-64:~# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"
```

grains.items does not fail and passes back all the grains.

Did you recently upgrade salt? Or anything else that changed inyour environment?

**Comment by kira8565** [comment]
no ..i have not change anythink,in that environment,no matter i run which command ,it will get the same error
