### ISSUE TITLE
sort jinja filter broken with python3

### ISSUE THREAD

**Issue by ninja-** [saltstack/salt#39009]
### Description of Issue/Question
the sort filter no longer works(on OrderedDict..) when switching from python2 to python3 on saltstack 2016.11.1
some formulas need it to function properly i.e. php-ng formula
(otherwise the config file is messed up and php-fpm fails to start)
problem is related to the comparator, but I am not sure why did it even work in the first place
 
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
```
          ID: php_fpm_pool_conf_1
    Function: file.managed
        Name: /etc/php/php-fpm.d/www.conf
      Result: False
     Comment: Unable to manage file: Jinja error: '<' not supported between instances of 'OrderedDict' and 'OrderedDict'
              Traceback (most recent call last):
                File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 368, in render_jinja_tmpl
                  output = template.render(**decoded_context)
                File "/usr/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
                  return original_render(self, *args, **kwargs)
                File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
                  return self.environment.handle_exception(exc_info, True)
                File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
                  reraise(exc_type, exc_value, tb)
                File "/usr/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
                  raise value.with_traceback(tb)
                File "<template>", line 33, in top-level template code
                File "<template>", line 8, in template
                File "/usr/lib/python3.6/site-packages/jinja2/filters.py", line 264, in do_sort
                  return sorted(value, key=sort_func, reverse=reverse)
              TypeError: '<' not supported between instances of 'OrderedDict' and 'OrderedDict'
              
              ; line 8
              
              ---
              [...]
                      {%- for section, settings in sections.items() -%}
                          {%- if settings is number or settings is string %}
              {{ section }} = {{ settings }}
                          {%- else %}
              [{{ section }}]
                              {%- for setting in settings|sort -%}    <======================
                                  {%- for key, value in setting.items() %}
                                      {%- if value is number or value is string %}
                  {{ key }} = {{ value }}
                                      {%- elif value is iterable -%}
                                          {%- if key == 'error_reporting' %}
              [...]
              ---
     Started: 02:36:58.579578
    Duration: 30.921 ms
     Changes:   
```
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
           Salt: 2016.11.1-3-ga040755
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.3.9
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 3.6.0 (default, Jan 16 2017, 12:12:55)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.5
 
System Versions:
           dist: arch Arch Linux
        machine: x86_64
        release: 3.14.32-xxxx-grs-ipv6-64
         system: Linux
        version: arch Arch Linux
```

**Comment by gtmanfred** [comment]
Thanks for reporting this.  There are some areas where the python3 support is lacking.  2016.11 does not fully support python3.

We are actively working for the Nitrogen release to have python3 support, with testing.

Thanks,
Daniel

**Comment by ninja-** [comment]
So, it looks like Python3 dropped support for dictionary comparators. I'll look into refactoring the formula instead.

**Comment by gtmanfred** [comment]
Ok, thanks for updating, I am going to close this issue as an upstream issue then.

Thanks,
Daniel
