### ISSUE TITLE
KeyError: 'multiprocessing' in the master logs (proxy minions)

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#39059]
### Description of Issue/Question

I am constantly seeing this exception in the master logs:

```log
2017-01-31 15:25:45,083 [py.warnings                                                                      ][WARNING ][4759] /usr/local/salt/virtualenv/local/lib/python2.7/site-packages/salt/client/mixins.py:251: DeprecationWarning: call with arg instead call with kwarg instead

2017-01-31 15:25:45,086 [salt.utils.process                                                               ][ERROR   ][4760] An un-handled exception from the multiprocessing process 'SignalHandlingMultiprocessingProcess-7:3620' was caught:
Traceback (most recent call last):
  File "/usr/local/salt/virtualenv/local/lib/python2.7/site-packages/salt/utils/process.py", line 644, in _run
    return self._original_run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/salt/virtualenv/local/lib/python2.7/site-packages/salt/utils/schedule.py", line 775, in handle_func
    for job in salt.utils.minion.running(self.opts):
  File "/usr/local/salt/virtualenv/local/lib/python2.7/site-packages/salt/utils/minion.py", line 28, in running
    data = _read_proc_file(path, opts)
  File "/usr/local/salt/virtualenv/local/lib/python2.7/site-packages/salt/utils/minion.py", line 84, in _read_proc_file
    if opts['multiprocessing']:
KeyError: 'multiprocessing'
2017-01-31 15:25:45,093 [salt.utils.process                                                               ][ERROR   ][4761] An un-handled exception from the multiprocessing process 'SignalHandlingMultiprocessingProcess-7:3621' was caught:
Traceback (most recent call last):
  File "/usr/local/salt/virtualenv/local/lib/python2.7/site-packages/salt/utils/process.py", line 644, in _run
    return self._original_run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/salt/virtualenv/local/lib/python2.7/site-packages/salt/utils/schedule.py", line 775, in handle_func
    for job in salt.utils.minion.running(self.opts):
  File "/usr/local/salt/virtualenv/local/lib/python2.7/site-packages/salt/utils/minion.py", line 28, in running
    data = _read_proc_file(path, opts)
  File "/usr/local/salt/virtualenv/local/lib/python2.7/site-packages/salt/utils/minion.py", line 84, in _read_proc_file
    if opts['multiprocessing']:
KeyError: 'multiprocessing'
```

The master controls several proxy minions (SSH-based)
On the master I have several scheduler jobs that execute runners at specific intervals.

As the proxies are SSH-based they have the `multiprocessing` option set to `False` under the `proxy` config file (https://docs.saltstack.com/en/latest/topics/proxyminion/ssh.html)
Probably that's why the `multiprocessing` key does not exist in the opts.

However, the exception does not break anything.

### Versions Report

```yaml
Salt Version:
           Salt: 2016.11.0

Dependency Versions:
           cffi: 0.8.6
       cherrypy: 10.0.0
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.4
        machine: x86_64
        release: 4.4.17-cloudflare
         system: Linux
        version: debian 8.4
```

**Comment by mirceaulinic** [comment]
I have submitted https://github.com/saltstack/salt/pull/39063 to avoid this exception.

**Comment by gtmanfred** [comment]
Thanks for the PR @mirceaulinic 

Thanks,
Daniel

**Comment by mirceaulinic** [comment]
Closed via https://github.com/saltstack/salt/commit/2a85d73f590d790c5ceed59b1460bd2f473e83c6
