### ISSUE TITLE
salt-call --local saltutil.regen_keys fails with KeyError: 'master_uri'

### ISSUE THREAD

**Issue by alexforster** [saltstack/salt#39115]
### Description of Issue/Question

`salt-call --local saltutil.regen_keys` fails with `KeyError: 'master_uri'`

Related issue from November, 2015 that was marked as resolved– https://github.com/saltstack/salt/issues/28499

### Setup

Vanilla 2016.11.2 salt-minion package for Debian 8 (Jessie)

APT repo– `deb http://repo.saltstack.com/apt/debian/8/amd64/2016.11 jessie main`

### Steps to Reproduce Issue

```
root@localhost:~# apt-get -y install salt-minion
(sic)
root@localhost:~# systemctl stop salt-minion
root@localhost:~# salt-call --local saltutil.regen_keys
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
KeyError: 'master_uri'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 379, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/saltutil.py", line 977, in regen_keys
    channel = salt.transport.Channel.factory(__opts__)
  File "/usr/lib/python2.7/dist-packages/salt/transport/__init__.py", line 49, in factory
    return ReqChannel.factory(opts, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/client.py", line 25, in factory
    sync = SyncWrapper(AsyncReqChannel.factory, (opts,), kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/utils/async.py", line 60, in __init__
    self.async = method(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/client.py", line 108, in factory
    return salt.transport.zeromq.AsyncZeroMQReqChannel(opts, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 85, in __new__
    new_obj.__singleton_init__(opts, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 153, in __singleton_init__
    self.auth = salt.crypt.AsyncAuth(self.opts, io_loop=self._io_loop)
  File "/usr/lib/python2.7/dist-packages/salt/crypt.py", line 335, in __new__
    key = cls.__key(opts)
  File "/usr/lib/python2.7/dist-packages/salt/crypt.py", line 352, in __key
    opts['master_uri'],  # master ID
KeyError: 'master_uri'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 379, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/saltutil.py", line 977, in regen_keys
    channel = salt.transport.Channel.factory(__opts__)
  File "/usr/lib/python2.7/dist-packages/salt/transport/__init__.py", line 49, in factory
    return ReqChannel.factory(opts, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/client.py", line 25, in factory
    sync = SyncWrapper(AsyncReqChannel.factory, (opts,), kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/utils/async.py", line 60, in __init__
    self.async = method(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/client.py", line 108, in factory
    return salt.transport.zeromq.AsyncZeroMQReqChannel(opts, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 85, in __new__
    new_obj.__singleton_init__(opts, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 153, in __singleton_init__
    self.auth = salt.crypt.AsyncAuth(self.opts, io_loop=self._io_loop)
  File "/usr/lib/python2.7/dist-packages/salt/crypt.py", line 335, in __new__
    key = cls.__key(opts)
  File "/usr/lib/python2.7/dist-packages/salt/crypt.py", line 352, in __key
    opts['master_uri'],  # master ID
KeyError: 'master_uri'
```

### Versions Report

```
root@localhost:~# salt-minion --versions-report
Salt Version:
           Salt: 2016.11.2

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.7
        machine: x86_64
        release: 4.8.0-0.bpo.2-amd64
         system: Linux
        version: debian 8.7
```

**Comment by rallytime** [comment]
Hi @alexforster - thanks for bringing this to our attention. I have been looking into fixing this issue, and while we definitely should clean this up so that we're not stack-tracing, I am curious as to what your use case would be here when using this function with `--local`.

The final line of the function is what is causing the stacktrace. This line reaches out to the master and updates its public key. `--local` implies that there is no communication with the master, and therefore, there is nothing to update. I tested how running this function would affect a master/minion connection by checking for a masterless minion just before the line causing the stacktrace. It predictably causes problems. The master publishes commands to the minion using the old key and makes the minion unreachable.

I am inclined to look for the use of a masterless call at the top of the function, log a warning, and exit without performing any of the functionality in this function when running a masterless minion. However, before doing that, I wanted to see if there was a use-case I am missing and what you expect to happen when running this function in masterless mode.

**Comment by alexforster** [comment]
I was attempting to generate minion keys before starting the service during the kickstart/preseed process.

**Comment by rallytime** [comment]
@alexforster Ah, ok. I have been looking a little more at this. Have you seen the doc we have on [preseeding minions](https://docs.saltstack.com/en/latest/topics/tutorials/preseed_key.html)? The current function in question will not work with using `--local` to _preseed_ the minion key.

You could use `salt-call` without the `--local`, so that we do have the master/minion connection, but even then you'll still need to accept the key on the master, which is not what you're looking for I think. Moreover, if the key is already accepted and then you call `salt-call saltutil.regen_keys`, this can get you in state where the old key is accepted and the new key is denied:
```
# salt-call saltutil.regen_keys
[CRITICAL] The Salt Master has rejected this minion's public key!
To repair this issue, delete the public key for this minion on the Salt Master and restart this minion.
Or restart the Salt Master in open mode to clean out the keys. The Salt Minion will now exit.
#
#
# salt-key
Accepted Keys:
rallytime
Denied Keys:
rallytime
Unaccepted Keys:
Rejected Keys:
```

As I understand it, the idea of preseeding either assumes that the master and minion are both being given the key from a third source or that the master generates the key and makes it available to the minion somehow. Either way, you'll still need to involve the master for the key exchange. 

I definitely want to protect against hitting that stacktrace and updating the docs for `saltutil.regen_keys` to help reduce confusion in the future. Does the doc I linked above help get you going in the right direction?
