### ISSUE TITLE
TypeError: out_format() got an unexpected keyword argument 'nested_indent'

### ISSUE THREAD

**Issue by MartinMystikJonas** [saltstack/salt#39136]
### Description of Issue/Question

Error when running `salt-call -l warning --state-output=changes state.highstate`

```
TypeError: out_format() got an unexpected keyword argument 'nested_indent'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 345, in salt_call
    def salt_key():
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 149, in run
    self.opts)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 86, in display_output
    '''
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 39, in try_printout
    if printout is not None:
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 146, in output
    for host, hostdata in six.iteritems(data)
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 225, in _format_host
    schanged, ctext = _format_changes(ret['changes'], orchestration)
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 525, in _format_changes
    ctext = _nested_changes(changes)
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 497, in _nested_changes
    nested_indent=14)
TypeError: out_format() got an unexpected keyword argument 'nested_indent'
```

### Versions Report
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.3.7
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.6 
        machine: x86_64
        release: 4.4.0-59-generic
         system: Linux
        version: debian 8.6

**Comment by MartinMystikJonas** [comment]
Never mind it was problem with partially updated dependencies. Solved by complete system update.

**Comment by 9maf4you** [comment]
Hello! I'm having the same problem while updating master and minion from 2016.3.3 to 2016.11.3.
And I'm really want to see what had happened after updating.


```
[DEBUG   ] LazyLoaded highstate.output
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: out_format() got an unexpected keyword argument 'nested_indent'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 352, in salt_call
    _install_signal_handlers(client)
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 149, in run
    self.opts)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 86, in display_output
    '''
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 39, in try_printout
    if printout is not None:
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 146, in output
    for host, hostdata in six.iteritems(data)
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 225, in _format_host
    schanged, ctext = _format_changes(ret['changes'], orchestration)
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 525, in _format_changes
    ctext = _nested_changes(changes)
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 497, in _nested_changes
    nested_indent=14)
TypeError: out_format() got an unexpected keyword argument 'nested_indent'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 352, in salt_call
    _install_signal_handlers(client)
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 149, in run
    self.opts)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 86, in display_output
    '''
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 39, in try_printout
    if printout is not None:
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 146, in output
    for host, hostdata in six.iteritems(data)
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 225, in _format_host
    schanged, ctext = _format_changes(ret['changes'], orchestration)
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 525, in _format_changes
    ctext = _nested_changes(changes)
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 497, in _nested_changes
    nested_indent=14)
TypeError: out_format() got an unexpected keyword argument 'nested_indent'
```

Update ends successfully however it's bad when you can't see a result.

**Comment by MartinMystikJonas** [comment]
We found out that this bug was becaue of partialy updated salt. Some salt package was not automatically updated by "apt-get update" because it has new dependency. So it was kept back and result was this error. Try running "apt-get update" and check if you have any packages listed as kept back. Is you do then you can fix this by "apt-get install [package name]"
