### ISSUE TITLE
Installing certbot causes Salt-Minion to fail to start

### ISSUE THREAD

**Issue by EugeneKay** [saltstack/salt#39134]
### Description of Issue/Question

The presence of the `python-parsedatetime` and/or `python-psutil` packages(both of which are dependencies of the EPEL certbot package) cause salt-minion to fail to (re)start with a python stacktrace. Uninstalling these packages(and re-installing salt-minion to clear the pyc cache) resolves the issue.

```
[eugene@wenatchee ~]# systemctl status salt-minion
● salt-minion.service - The Salt Minion
   Loaded: loaded (/usr/lib/systemd/system/salt-minion.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2017-02-02 01:24:16 UTC; 11s ago
 Main PID: 23888 (salt-minion)
   CGroup: /system.slice/salt-minion.service
           ├─23888 /usr/bin/python /usr/bin/salt-minion
           ├─23918 /usr/bin/python /usr/bin/salt-minion
           └─23922 /usr/bin/python /usr/bin/salt-minion

Feb 02 01:24:16 wenatchee.kashpureff.org systemd[1]: Starting The Salt Minion...
Feb 02 01:24:16 wenatchee.kashpureff.org systemd[1]: Started The Salt Minion.
[eugene@wenatchee ~]# yum install certbot
Loaded plugins: changelog, fastestmirror, remove-with-leaves
Loading mirror speeds from cached hostfile
 * base: mirrors.ocf.berkeley.edu
 * epel: mirrors.kernel.org
 * extras: mirrors.ocf.berkeley.edu
 * rpmforge: repoforge.eecs.wsu.edu
 * updates: mirrors.ocf.berkeley.edu
Resolving Dependencies
--> Running transaction check
---> Package certbot.noarch 0:0.9.3-1.el7 will be installed
--> Processing Dependency: python2-certbot = 0.9.3-1.el7 for package: certbot-0.9.3-1.el7.noarch
--> Running transaction check
---> Package python2-certbot.noarch 0:0.9.3-1.el7 will be installed
--> Processing Dependency: python2-dialog >= 3.3.0 for package: python2-certbot-0.9.3-1.el7.noarch
--> Processing Dependency: python-psutil >= 2.1.0 for package: python2-certbot-0.9.3-1.el7.noarch
--> Processing Dependency: python-parsedatetime for package: python2-certbot-0.9.3-1.el7.noarch
--> Running transaction check
---> Package python-parsedatetime.noarch 0:1.5-3.el7 will be installed
---> Package python-psutil.x86_64 0:2.2.1-1.el7 will be installed
---> Package python2-dialog.noarch 0:3.3.0-6.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

==========================================================================================================================================================================================
 Package                                               Arch                                    Version                                        Repository                             Size
==========================================================================================================================================================================================
Installing:
 certbot                                               noarch                                  0.9.3-1.el7                                    epel                                   16 k
Installing for dependencies:
 python-parsedatetime                                  noarch                                  1.5-3.el7                                      epel                                   61 k
 python-psutil                                         x86_64                                  2.2.1-1.el7                                    epel                                  114 k
 python2-certbot                                       noarch                                  0.9.3-1.el7                                    epel                                  361 k
 python2-dialog                                        noarch                                  3.3.0-6.el7                                    epel                                   94 k

Transaction Summary
==========================================================================================================================================================================================
Install  1 Package (+4 Dependent packages)

Total download size: 647 k
Installed size: 2.9 M
Is this ok [y/d/N]: y
Downloading packages:
(1/5): certbot-0.9.3-1.el7.noarch.rpm                                                                                                                              |  16 kB  00:00:00
(2/5): python-parsedatetime-1.5-3.el7.noarch.rpm                                                                                                                   |  61 kB  00:00:00
(3/5): python-psutil-2.2.1-1.el7.x86_64.rpm                                                                                                                        | 114 kB  00:00:00
(4/5): python2-certbot-0.9.3-1.el7.noarch.rpm                                                                                                                      | 361 kB  00:00:00
(5/5): python2-dialog-3.3.0-6.el7.noarch.rpm                                                                                                                       |  94 kB  00:00:00
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                     373 kB/s | 647 kB  00:00:01
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : python-psutil-2.2.1-1.el7.x86_64                                                                                                                                       1/5
  Installing : python-parsedatetime-1.5-3.el7.noarch                                                                                                                                  2/5
  Installing : python2-dialog-3.3.0-6.el7.noarch                                                                                                                                      3/5
Error unpacking rpm package python2-dialog-3.3.0-6.el7.noarch
error: unpacking of archive failed on file /usr/lib/python2.7/site-packages/python2_pythondialog-3.3.0-py2.7.egg-info: cpio: rename
  Installing : python2-certbot-0.9.3-1.el7.noarch                                                                                                                                     4/5
error: python2-dialog-3.3.0-6.el7.noarch: install failed
  Installing : certbot-0.9.3-1.el7.noarch                                                                                                                                             5/5
  Verifying  : python-parsedatetime-1.5-3.el7.noarch                                                                                                                                  1/5
  Verifying  : python-psutil-2.2.1-1.el7.x86_64                                                                                                                                       2/5
  Verifying  : python2-certbot-0.9.3-1.el7.noarch                                                                                                                                     3/5
  Verifying  : certbot-0.9.3-1.el7.noarch                                                                                                                                             4/5
  Verifying  : python2-dialog-3.3.0-6.el7.noarch                                                                                                                                      5/5

Installed:
  certbot.noarch 0:0.9.3-1.el7

Dependency Installed:
  python-parsedatetime.noarch 0:1.5-3.el7                         python-psutil.x86_64 0:2.2.1-1.el7                         python2-certbot.noarch 0:0.9.3-1.el7

Failed:
  python2-dialog.noarch 0:3.3.0-6.el7

Complete!
[eugene@wenatchee ~]# systemctl restart salt-minion
Job for salt-minion.service failed because the control process exited with error code. See "systemctl status salt-minion.service" and "journalctl -xe" for details.
[eugene@wenatchee ~]# systemctl status salt-minion
● salt-minion.service - The Salt Minion
   Loaded: loaded (/usr/lib/systemd/system/salt-minion.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2017-02-02 01:24:53 UTC; 1min 11s ago
  Process: 24475 ExecStart=/usr/bin/salt-minion (code=exited, status=1/FAILURE)
 Main PID: 24475 (code=exited, status=1/FAILURE)

Feb 02 01:24:53 wenatchee.kashpureff.org salt-minion[24475]: from salt.utils import is_windows
Feb 02 01:24:53 wenatchee.kashpureff.org salt-minion[24475]: File "/usr/lib/python2.7/site-packages/salt/utils/__init__.py", line 68, in <module>
Feb 02 01:24:53 wenatchee.kashpureff.org salt-minion[24475]: import parsedatetime
Feb 02 01:24:53 wenatchee.kashpureff.org salt-minion[24475]: File "/usr/lib/python2.7/site-packages/parsedatetime/__init__.py", line 66, in <module>
Feb 02 01:24:53 wenatchee.kashpureff.org salt-minion[24475]: pdtLocales = {'icu': pdt_locales.pdtLocale_icu,
Feb 02 01:24:53 wenatchee.kashpureff.org salt-minion[24475]: AttributeError: 'module' object has no attribute 'pdtLocale_icu'
Feb 02 01:24:53 wenatchee.kashpureff.org systemd[1]: salt-minion.service: main process exited, code=exited, status=1/FAILURE
Feb 02 01:24:53 wenatchee.kashpureff.org systemd[1]: Failed to start The Salt Minion.
Feb 02 01:24:53 wenatchee.kashpureff.org systemd[1]: Unit salt-minion.service entered failed state.
Feb 02 01:24:53 wenatchee.kashpureff.org systemd[1]: salt-minion.service failed.
[eugene@wenatchee ~]# sudo grep salt /var/log/messages
Feb  2 01:24:52 wenatchee salt-minion: [WARNING ] Minion received a SIGTERM. Exiting.
Feb  2 01:24:53 wenatchee salt-minion: The Salt Minion is shutdown. Minion received a SIGTERM. Exited.
Feb  2 01:24:53 wenatchee salt-minion: Traceback (most recent call last):
Feb  2 01:24:53 wenatchee salt-minion: File "/usr/bin/salt-minion", line 7, in <module>
Feb  2 01:24:53 wenatchee salt-minion: from salt.utils import is_windows
Feb  2 01:24:53 wenatchee salt-minion: File "/usr/lib/python2.7/site-packages/salt/utils/__init__.py", line 68, in <module>
Feb  2 01:24:53 wenatchee salt-minion: import parsedatetime
Feb  2 01:24:53 wenatchee salt-minion: File "/usr/lib/python2.7/site-packages/parsedatetime/__init__.py", line 66, in <module>
Feb  2 01:24:53 wenatchee salt-minion: pdtLocales = {'icu': pdt_locales.pdtLocale_icu,
Feb  2 01:24:53 wenatchee salt-minion: AttributeError: 'module' object has no attribute 'pdtLocale_icu'
Feb  2 01:24:53 wenatchee systemd: salt-minion.service: main process exited, code=exited, status=1/FAILURE
Feb  2 01:24:53 wenatchee systemd: Unit salt-minion.service entered failed state.
Feb  2 01:24:53 wenatchee systemd: salt-minion.service failed.
```

### Setup

- CentOS Linux release 7.3.1611 (Core)
- Saltstack RPM repo(https://repo.saltstack.com/yum/redhat/$releasever/$basearch/latest)
- EPEL rpm repo

### Steps to Reproduce Issue

Install the certbot package, restart salt-minion service.

### Versions Report

```
[eugene@wenatchee ~]# salt-minion --versions-report
Traceback (most recent call last):
  File "/usr/bin/salt-minion", line 7, in <module>
    from salt.utils import is_windows
  File "/usr/lib/python2.7/site-packages/salt/utils/__init__.py", line 68, in <module>
    import parsedatetime
  File "/usr/lib/python2.7/site-packages/parsedatetime/__init__.py", line 66, in <module>
    pdtLocales = {'icu': pdt_locales.pdtLocale_icu,
AttributeError: 'module' object has no attribute 'pdtLocale_icu'
[eugene@wenatchee ~]# yum info salt-minion
Loaded plugins: changelog, fastestmirror, remove-with-leaves
Loading mirror speeds from cached hostfile
 * base: mirrors.xmission.com
 * epel: mirrors.kernel.org
 * extras: mirrors.xmission.com
 * rpmforge: repoforge.eecs.wsu.edu
 * updates: mirrors.xmission.com
Installed Packages
Name        : salt-minion
Arch        : noarch
Version     : 2016.11.2
Release     : 1.el7
Size        : 66 k
Repo        : installed
From repo   : salt
Summary     : Client component for Salt, a parallel remote execution system
URL         : http://saltstack.org/
License     : ASL 2.0
Description : The Salt minion is the agent component of Salt. It listens for instructions
            : from the master, runs jobs, and returns results back to the master.

[eugene@wenatchee ~]# yum info salt
Loaded plugins: changelog, fastestmirror, remove-with-leaves
Loading mirror speeds from cached hostfile
 * base: mirrors.xmission.com
 * epel: mirrors.kernel.org
 * extras: mirrors.xmission.com
 * rpmforge: repoforge.eecs.wsu.edu
 * updates: mirrors.xmission.com
Installed Packages
Name        : salt
Arch        : noarch
Version     : 2016.11.2
Release     : 1.el7
Size        : 32 M
Repo        : installed
From repo   : salt
Summary     : A parallel remote execution system
URL         : http://saltstack.org/
License     : ASL 2.0
Description : Salt is a distributed remote execution system used to execute commands and
            : query data. It was developed in order to bring the best solutions found in
            : the world of remote execution together and make them better, faster and more
            : malleable. Salt accomplishes this via its ability to handle larger loads of
            : information, and not just dozens, but hundreds or even thousands of individual
            : servers, handle them quickly and through a simple and manageable interface.

[eugene@wenatchee ~]#
```

**Comment by Ch3LL** [comment]
@EugeneKay do you have different versions of those pkgs installed on your system in pip vs sytem pkgs?

I think what might be happening is there is a conflict between those versions. If you uninstall the pip or system version does it continue to work?

**Comment by EugeneKay** [comment]
@Ch3LL You are completely correct - it was pip's fault. I thought this was a clean system, but somewhere in history there must have been a manual install. Funny how the automation tools show us the errors in manual management. Thanks for the wisdom!
