### ISSUE TITLE
states.user.present homedir

### ISSUE THREAD

**Issue by dmaziuk** [saltstack/salt#39204]
### Description of Issue/Question
```
2017-02-06 15:44:41,675 [salt.state                                           ][ERROR   ][32258] An exception ccurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/state.py", line 1745, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.6/site-packages/salt/loader.py", line 1702, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib64/python2.6/contextlib.py", line 34, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.6/site-packages/salt/utils/context.py", line 48, in func_globals_inject
    yield
  File "/usr/lib/python2.6/site-packages/salt/loader.py", line 1702, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/states/user.py", line 515, in present
    __salt__['file.mkdir'](val, pre['uid'], pre['gid'], 0o755)
  File "/usr/lib/python2.6/site-packages/salt/modules/file.py", line 4908, in mkdir
    makedirs_perms(directory, user, group, mode)
  File "/usr/lib/python2.6/site-packages/salt/modules/file.py", line 5005, in makedirs_perms
    os.mkdir(name)
OSError: [Errno 17] File exists: '/dev/null'
```

Using `/dev/null` as the home directory for system/locked accounts is not uncommon in Unix. I can't off the top of my head think of another legitimate use of a device file as user's home directory, but it should be perfectly possible in theory.

Salt should *not* try to turn a device file into a directory and/or change a device file's permissions and ownership. It's a good thing it didn't succeed, too: succeeding would potentially break the entire system.

**Comment by gtmanfred** [comment]
Thanks for the request.

If you want to submit a pull request to implement this change we would greatly appreciate it, otherwise I have tagged it as a feature request for our platform team.

Thanks,
Daniel

**Comment by dmaziuk** [comment]
Well, the simple stupid fix that does what I want is (`states.user`)
```
--- user.py	2017-02-06 17:27:49.907894575 -0600
+++ user.py.orig	2017-02-06 15:58:19.354582036 -0600
@@ -409,7 +409,7 @@
 
     # the comma is used to separate field in GECOS, thus resulting into
     # salt adding the end of fullname each time this function is called
-    for gecos_field in ['fullname', 'roomnumber', 'workphone',]: # 'homephone']:
+    for gecos_field in ['fullname', 'roomnumber', 'workphone', 'homephone']:
         if isinstance(gecos_field, string_types) and ',' in gecos_field:
             ret['comment'] = "Unsupported char ',' in {0}".format(gecos_field)
             ret['result'] = False
```
I'll do more runs with the above patch tomorrow, and if nothing breaks I'll be happy to send it as a pull request...  The question is, is that how you want to deal with it?

Linux and *BSD only specify 4 fields in the manpages, but in reality the whole field is a "comment" passed on to underlying `useradd`/`pw`. 

Traditionally there are 5 fields, but ISTR that "others" field was for use by "other applications" and so its format is anyone's guess.

My vote would be to "gecos" (or "comment") parameter and if that's not None: use it and ignore the 4 fields. Getting that to work is a bit more patching in more places that I'm prepared to do right now, sorry. :(

So let me know if you want the above as a pull request.

**Comment by gtmanfred** [comment]
I think that comment is meant for your issue about the gecos field which I
will look at more in the morning.

**Comment by dmaziuk** [comment]
1.  The above is a quick and dirty hack that allows commas in the last field ("homephone"). However many fields there are, are all read and written as a single field as is. It's nasty but problem solved with minimal effort. 

  2.  Ideally instead of the separate fields/parameters I would use a single "gecos" (or "comment") field. If it were done from the start, the code would've been simpler and stupider (KISS principle). However adding it at this point while also keeping the old 4 fields for backwards compatibility would do the opposite of simpler and smaller.

  3, Adding the 5th field; "other", exempt from check for commas as in 1) above, would be less intrusive & less work than 2) and more in line with the traditional unix reading of the gecos field.

**Comment by gtmanfred** [comment]
@dmaziuk what does the gecos stuff have to do with the ability to set homedir to /dev/null?

**Comment by dmaziuk** [comment]
`/dev/null` is a separate completely different issue.

**Comment by dmaziuk** [comment]
PPS. there is a 3rd issue that I thought of on the way to work this morning: the code checking for commas in the gecos field -- check for colons is even more important and I don't see that done anywhere. ICBW of course.

Something like 
```
    for gecos_field in ['fullname', 'roomnumber', 'workphone', 'homephone']:
        if isinstance(gecos_field, string_types) and ':' in gecos_field:
            ret['comment'] = "Unsupported char ':' in {0}".format(gecos_field)
            ret['result'] = False
            return ret
```

around line 418 in `states/users.py` (going by RPM-installed code) should do it.

**Comment by gtmanfred** [comment]
But the issue you are updating here is specifically about homedir, are you meaning to post these updates in this issue? https://github.com/saltstack/salt/issues/39203

**Comment by dmaziuk** [comment]
Sorry, helpful browser memory meets attention deficit disorder. Yes, this was supposed to go into #39203. Apologies.
