### ISSUE TITLE
Running salt-cloud with --parallel gives fd error

### ISSUE THREAD

**Issue by aig787** [saltstack/salt#39254]
### Description of Issue/Question

Running `salt-cloud -m test-cloud.map -c config -l debug -y -P` gives this error on macOS 10.12.3. The same command without the -P option spins up the environment just fine.

```
[DEBUG   ] Error deleting fd from IOLoop
Traceback (most recent call last):
  File "/opt/salt/lib/python2.7/site-packages/tornado/ioloop.py", line 732, in remove_handler
    self._impl.unregister(fd)
  File "/opt/salt/lib/python2.7/site-packages/tornado/platform/kqueue.py", line 50, in unregister
    self._control(fd, events, select.KQ_EV_DELETE)
  File "/opt/salt/lib/python2.7/site-packages/tornado/platform/kqueue.py", line 63, in _control
    self._kqueue.control([kevent], 0)
OSError: [Errno 9] Bad file descriptor
[DEBUG   ] Error deleting fd from IOLoop
Traceback (most recent call last):
  File "/opt/salt/lib/python2.7/site-packages/tornado/ioloop.py", line 732, in remove_handler
    self._impl.unregister(fd)
  File "/opt/salt/lib/python2.7/site-packages/tornado/platform/kqueue.py", line 50, in unregister
    self._control(fd, events, select.KQ_EV_DELETE)
  File "/opt/salt/lib/python2.7/site-packages/tornado/platform/kqueue.py", line 63, in _control
    self._kqueue.control([kevent], 0)
OSError: [Errno 9] Bad file descriptor
[WARNING ] Unable to obtain lock for /var/cache/salt/cloud/index.p
[WARNING ] Unable to obtain lock for /var/cache/salt/cloud/index.p
[ERROR   ] There was a query error: [Errno 61] Connection refused
Traceback (most recent call last):
  File "/opt/salt/lib/python2.7/site-packages/salt/cloud/cli.py", line 348, in run
    ret = mapper.run_map(dmap)
  File "/opt/salt/lib/python2.7/site-packages/salt/cloud/__init__.py", line 2257, in run_map
    _create_multiprocessing, parallel_data, pool_size=pool_size)
  File "/opt/salt/lib/python2.7/site-packages/salt/cloud/__init__.py", line 150, in enter_mainloop
    ret = pool.map(func=target, iterable=iterable)
  File "/opt/salt/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/opt/salt/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
error: [Errno 61] Connection refused
```

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
Salt Version:
           Salt: 2016.11.2

Dependency Versions:
           cffi: 1.5.0
       cherrypy: 4.0.0
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: 1.5.0
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: 1.4.4
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Jan 25 2017, 14:57:42)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: 0.6.5
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.3
            ZMQ: 4.1.2

System Versions:
           dist:
        machine: x86_64
        release: 16.4.0
         system: Darwin
        version: 10.12.3 x86_64
```

**Comment by gtmanfred** [comment]
Thanks for reporting this.

Thanks,
Daniel

**Comment by aig787** [comment]
Could it be related to https://github.com/tornadoweb/tornado/issues/1901?

**Comment by gtmanfred** [comment]
It could be, would you be able to test this out?

Thanks,
Daniel

**Comment by aig787** [comment]
After deleting the bundled tornado and installing the master branch I'm still seeing the issue. All of the nodes seem to be coming up in ec2 okay, but at the end it is getting that connection error.
