### ISSUE TITLE
Minions fail to connect or auth with master

### ISSUE THREAD

**Issue by DaveQB** [saltstack/salt#39308]
### Setup
Our state file count is at 6039 if that matters.
worker_threads are set to 80

### Steps to Reproduce Issue
Some random minions get the below log when connecting:

```
2017-02-10 23:23:10,317 [tornado.application][ERROR   ][32088] Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 230, in wrapper
    yielded = next(result)
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 598, in handle_message
    stream.send(self.serial.dumps(self._auth(payload['load'])))
  File "/usr/lib/python2.7/dist-packages/salt/transport/mixins/auth.py", line 406, in _auth
    with salt.utils.fopen(pubfn) as f:
  File "/usr/lib/python2.7/dist-packages/salt/utils/__init__.py", line 1221, in fopen
    fhandle = open(*args, **kwargs)
IOError: [Errno 2] No such file or directory: '/etc/salt/pki/master/minions/ops-dns01-ap-southeast-2b.think.vpc'
```
From then on they fail to connect without any logs on the master.

The minions give this:

```
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_f34d2f0000_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_f34d2f0000_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_f34d2f0000_pull.ipc
[DEBUG   ] Sending event - data = {'_stamp': '2017-02-10T12:30:51.165484', 'complete': True, 'schedule': {'__mine_interval': {'function': 'mine.update', 'enabled': True, 'return_job': False, 'jid_include': True, 'maxrunning': 2, 'minutes': 60}}}
[DEBUG   ] Persisting schedule
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'ops-dns01-ap-southeast-2b.think.vpc', 'tcp://10.150.0.74:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'ops-dns01-ap-southeast-2b.think.vpc', 'tcp://10.150.0.74:4506')
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'ops-dns01-ap-southeast-2b.think.vpc', 'tcp://10.150.0.74:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'ops-dns01-ap-southeast-2b.think.vpc', 'tcp://10.150.0.74:4506')
[DEBUG   ] SaltReqTimeoutError, retrying. (1/3)
[DEBUG   ] SaltReqTimeoutError, retrying. (2/3)
[DEBUG   ] SaltReqTimeoutError, retrying. (3/3)
[INFO    ] fire_master failed: master could not be contacted. Request timed out.

```

As a side note, I am also seeing this, that could be relevant:

```
2017-02-10 23:34:03,294 [salt.master      ][ERROR   ][32021] Received minion error from [tst-student-portal-v202-ap-southeast-2b.think.vpc]: The minion function caused an exception
2017-02-10 23:34:03,301 [salt.master      ][ERROR   ][32047] Received minion error from [localhost]: The minion function caused an exception
2017-02-10 23:34:03,451 [salt.master      ][ERROR   ][32086] Received minion error from [ply-b2cwp01-ap-southeast-2a.think.vpc]: The minion function caused an exception
```

This was such a bad problem, we replaced our 5 year old masters (2) with 2 new servers. It started off well but not we have hit the same problems. It looks like a resource issue but the servers are near idle.

We get these errors too:

```
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 740, in cmd_iter_no_block
    **kwargs):
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 964, in get_iter_returns
    jinfo = self.gather_job_info(jid, tgt, tgt_type, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 225, in gather_job_info
    **kwargs
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 313, in run_job
    raise SaltClientError(general_exception)
SaltClientError: Salt request timed out. The master is not responding. If this error persists after verifying the master is up, worker_threads may need to be increased.
```

### Versions Report
NEW MASTER
```
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 2.5.3
          gitdb: Not Installed
      gitpython: 0.1.6
          ioflo: Not Installed
         Jinja2: 2.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.3 (default, Dec 18 2014, 19:10:20)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 12.04 precise
        machine: x86_64
        release: 3.2.0-84-virtual
         system: Linux
        version: Ubuntu 12.04 precise
```

MINION
```
Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.3 (default, Dec 18 2014, 19:10:20)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 12.04 precise
        machine: x86_64
        release: 3.2.0-84-virtual
         system: Linux
        version: Ubuntu 12.04 precise
```

**Comment by Ch3LL** [comment]
There was this issue that seems similar https://github.com/saltstack/salt/issues/29674 if you were on a version earlier then 2015.8.11 so it seems that is not the issue since you are on 2016.3.3. This issue was to fix : `if a minion's key was removed and the minion still think it's connected and perform interactions with the master, master handles requests and tries to respond but throws IOException in worker when trying to encrypt a response for minion because there's no minion key anymore`

2016.3.3 is an old version. If you upgrade to 2016.3.5 or 2016.11.2 is there any improvement?

Do you see the minion file in `/etc/salt/pki/master/minions/ops-dns01-ap-southeast-2b.think.vpc`? Did you recently delete that minion and is it still trying to auth with the master?

**Comment by DaveQB** [comment]
Hi @Ch3LL  
Thanks for the response and sorry for the slow response. 

That issue does sound similar but I am on 2016.3.3 as you noted.

An upgrade would take a few weeks to go through testing and approvals etc. I can try and raise an emergency out of process change but I need to show good cause, so I'd like to troubleshoot this some more thanks.

The path (/etc/salt/pki/master/minions/ops-dns01-ap-southeast-2b.think.vpc) that is being stated as missing does indeed exist. 

Since I reported this, we stopped having a multi-master setup which has improved the situation dramatically. But we are now getting different errors, same symptoms though. This has been happening a lot now. See below.

In this example I am matching minion "tst-ancb.edu.au02-ap-southeast-2b.think.vpc" yet the logging is referencing a different host "prd-soe201633-ap-southeast-2a.think.vpc_master".
Minion "prd-soe201633-ap-southeast-2a.think.vpc" does exist. Other times, the "other" host is referenced to a minion that has since been deleted.

```

~# salt tst-ancb.edu.au02-ap-southeast-2b.think.vpc -l debug  test.ping
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'prd-soe201633-ap-southeast-2a.think.vpc_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/df/fce2ae44813571c686281c2957f1a9/.minions.p
[DEBUG   ] get_iter_returns for jid 20170220144834232740 sent to set(['tst-ancb.edu.au02-ap-southeast-2b.think.vpc']) will timeout at 14:48:39.715391
[DEBUG   ] Checking whether jid 20170220144834232740 is still running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'prd-soe201633-ap-southeast-2a.think.vpc_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] Passing on saltutil error. This may be an error in saltclient. 'retcode'
[DEBUG   ] LazyLoaded no_return.output
```

 In this example minion "prd-soe201633-ap-southeast-2a.think.vpc" does exist. Checking their public keys for a collision:

```
/etc/salt/pki/master/minions# md5sum prd-soe201633-ap-southeast-2a.think.vpc  tst-ancb.edu.au02-ap-southeast-2b.think.vpc 

e8ff33de48640a70b89979a269b01c7a  prd-soe201633-ap-southeast-2a.think.vpc
81f483f3cf3a7c6b744d867bf8fb2207  tst-ancb.edu.au02-ap-southeast-2b.think.vpc
```

I just tried this again and got a different, "other" host referenced in the output:

```
~# salt 'tst-www-ancb-edu-au02-ap-southeast-2b.think.vpc' -l debug  test.ping
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'ops-deleteme97-ap-southeast-2b.think.vpc_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] SaltReqTimeoutError, retrying. (1/3)
[DEBUG   ] SaltReqTimeoutError, retrying. (2/3)
[DEBUG   ] SaltReqTimeoutError, retrying. (3/3)
[DEBUG   ] LazyLoaded nested.output
Salt request timed out. The master is not responding. If this error persists after verifying the master is up, worker_threads may need to be increased.
```

This host, "ops-deleteme97-ap-southeast-2b.think.vpc_master" does not exist this time. 

```
~# ls -l /etc/salt/pki/master/minions/ops-deleteme97-ap-southeast-2b.think.vpc
ls: cannot access /etc/salt/pki/master/minions/ops-deleteme97-ap-southeast-2b.think.vpc: No such file or directory
```

**Comment by DaveQB** [comment]
So if I get an error like so:

```
IOError: [Errno 2] No such file or directory: '/etc/salt/pki/master/minions/prd-frommaster03-ap-southeast-2a.think.vpc'

~# ls -l /etc/salt/pki/master/minions/prd-frommaster03-ap-southeast-2a.think.vpc
ls: cannot access /etc/salt/pki/master/minions/prd-frommaster03-ap-southeast-2a.think.vpc: No such file or directory
```

I then stop the minion, delete it's key pair and start it up again, it connects and it's public key is on the master. 

I suspect an issue with the minons key changing.

**Comment by DaveQB** [comment]
Oh one other thing. If I run a "service salt-master stop" on the master, all of the salt-master processes keep running, like they're orphaned. I have to killall them.

**Comment by Ch3LL** [comment]
You might be running into https://github.com/saltstack/salt/issues/35480 concerning your orphaned processes which has been fixed in 2016.3.5 and all 2016.11 versions.

When you state the following: "In this example I am matching minion "tst-ancb.edu.au02-ap-southeast-2b.think.vpc" yet the logging is referencing a different host "prd-soe201633-ap-southeast-2a.think.vpc_master"."

If you look at the output: `[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'ops-deleteme97-ap-southeast-2b.think.vpc_master', 'tcp://127.0.0.1:4506', 'clear')` I believe thats what you are refering to. This isn't trying to connect to a minion but the master that this command initialized from. Is that the name of your master you are running the command from?

Or is ops-deleteme97-ap-southeast-2b.think.vpc_master a master or has it ever been a master?

**Comment by DaveQB** [comment]
Hi @Ch3LL 

I'll start the salt upgrade business process.

"ops-deleteme97-ap-southeast-2b.think.vpc" was once a minion, never a master and no longer exists. It is like a key collision of some sort.

**Comment by DaveQB** [comment]
A solution that might be working for us having a cronjob our single master to service salt-master stop && killall salt-master and then service salt-master start. Seems to be working.

**Comment by Ch3LL** [comment]
So it seems you are running into  #35480 then if the processes are not being killed?

Also concerning the other issue that does indeed seem very odd that its spitting out the name of an old minion, that should be trying to initialize with the master its running on. How many minions do you currently have in your environment? Just want to make sure your worker threads should be at 80, which is a lot for a smaller environment.

**Comment by DaveQB** [comment]
@Ch3LL  I'll check out #35480 now.

It is very odd. Minions that have long been dead (months in some cases).

We have about 220 minions. We increased to 80 as we kept getting that error message suggesting we do (which didn't remove that error message of course)

Thanks

**Comment by DaveQB** [comment]
@Ch3LL  In which release was issue #35480 fixed? I couldn't decipher.
Thanks.

**Comment by DaveQB** [comment]
Just adding this. Running salt against the same minion (tst-scripts01-ap-southeast-2b.think.vpc), back to back saw different minion names returned both times.



```
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Missing configuration file: /home/dward/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'ops-deleteme97-ap-southeast-2b.think.vpc_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/54/acd416c559bcaeef0a334d8a0dfbd7/.minions.p
[DEBUG   ] get_iter_returns for jid 20170309150537437796 sent to set(['tst-scripts01-ap-southeast-2b.think.vpc']) will timeout at 15:05:42.443186
[DEBUG   ] Checking whether jid 20170309150537437796 is still running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'ops-deleteme97-ap-southeast-2b.think.vpc_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] Passing on saltutil error. This may be an error in saltclient. 'retcode'
[DEBUG   ] Checking whether jid 20170309150537437796 is still running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'ops-deleteme97-ap-southeast-2b.think.vpc_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] Passing on saltutil error. This may be an error in saltclient. 'retcode'
[DEBUG   ] Checking whether jid 20170309150537437796 is still running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'ops-deleteme97-ap-southeast-2b.think.vpc_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] Passing on saltutil error. This may be an error in saltclient. 'retcode'
[DEBUG   ] LazyLoaded no_return.output
```

```
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Missing configuration file: /home/dward/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'prd-soe201633-ap-southeast-2a.think.vpc_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/2e/8848ca7d163b6213a87a085cf9821d/.minions.p
[DEBUG   ] get_iter_returns for jid 20170309145908880344 sent to set(['tst-scripts01-ap-southeast-2b.think.vpc']) will timeout at 14:59:13.885860
[DEBUG   ] Checking whether jid 20170309145908880344 is still running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'prd-soe201633-ap-southeast-2a.think.vpc_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] Passing on saltutil error. This may be an error in saltclient. 'retcode'
[DEBUG   ] Checking whether jid 20170309145908880344 is still running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'prd-soe201633-ap-southeast-2a.think.vpc_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] Passing on saltutil error. This may be an error in saltclient. 'retcode'
[DEBUG   ] Checking whether jid 20170309145908880344 is still running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'prd-soe201633-ap-southeast-2a.think.vpc_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] Passing on saltutil error. This may be an error in saltclient. 'retcode'
```

**Comment by DaveQB** [comment]
I just want to add I found a reference to 'ops-deleteme97' in /var/cache/salt/master/minions/localhost/data.p

**Comment by JoaquinVeira** [comment]
Hi Dave,

were you able to solve this issue? I have a similar issue to the first one you said.

Regards

**Comment by DaveQB** [comment]
@JoaquinVeira  No. The work-around has been to go back to a single master and a scheduled salt-master service restart, every hour, on the master server.
