### ISSUE TITLE
salt-master errors in syslog

### ISSUE THREAD

**Issue by pepoluan** [saltstack/salt#39314]
### Description of Issue/Question

The following error(s) keeps recurring in my syslog, **even when I was _not_ doing anything**:

```
Feb 10 14:33:00 echo salt-master[2373]: [ERROR   ] Failed to import utils win_dacl, this is due most likely to a syntax error:
Feb 10 14:33:00 echo salt-master[2373]: Traceback (most recent call last):
Feb 10 14:33:00 echo salt-master[2373]:   File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1334, in _load_module
Feb 10 14:33:00 echo salt-master[2373]:     ), fn_, fpath, desc)
Feb 10 14:33:00 echo salt-master[2373]:   File "/usr/lib/python2.7/dist-packages/salt/utils/win_dacl.py", line 154, in <module>
Feb 10 14:33:00 echo salt-master[2373]:     class Flags(object):
Feb 10 14:33:00 echo salt-master[2373]:   File "/usr/lib/python2.7/dist-packages/salt/utils/win_dacl.py", line 366, in Flags
Feb 10 14:33:00 echo salt-master[2373]:     'grant': win32security.ACCESS_ALLOWED_ACE_TYPE,
Feb 10 14:33:00 echo salt-master[2373]: NameError: name 'win32security' is not defined
Feb 10 14:33:00 echo salt-master[2373]: [ERROR   ] Failed to import utils saltminionservice, this is due most likely to a syntax error:
Feb 10 14:33:00 echo salt-master[2373]: Traceback (most recent call last):
Feb 10 14:33:00 echo salt-master[2373]:   File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1334, in _load_module
Feb 10 14:33:00 echo salt-master[2373]:     ), fn_, fpath, desc)
Feb 10 14:33:00 echo salt-master[2373]:   File "/usr/lib/python2.7/dist-packages/salt/utils/saltminionservice.py", line 8, in <module>
Feb 10 14:33:00 echo salt-master[2373]:     from salt.utils.winservice import Service, instart
Feb 10 14:33:00 echo salt-master[2373]:   File "/usr/lib/python2.7/dist-packages/salt/utils/winservice.py", line 33, in <module>
Feb 10 14:33:00 echo salt-master[2373]:     class Service(win32serviceutil.ServiceFramework):
Feb 10 14:33:00 echo salt-master[2373]: NameError: name 'win32serviceutil' is not defined
Feb 10 14:33:00 echo salt-master[2373]: [ERROR   ] Failed to import utils winservice, this is due most likely to a syntax error:
Feb 10 14:33:00 echo salt-master[2373]: Traceback (most recent call last):
Feb 10 14:33:00 echo salt-master[2373]:   File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1334, in _load_module
Feb 10 14:33:00 echo salt-master[2373]:     ), fn_, fpath, desc)
Feb 10 14:33:00 echo salt-master[2373]:   File "/usr/lib/python2.7/dist-packages/salt/utils/winservice.py", line 33, in <module>
Feb 10 14:33:00 echo salt-master[2373]:     class Service(win32serviceutil.ServiceFramework):
Feb 10 14:33:00 echo salt-master[2373]: NameError: name 'win32serviceutil' is not defined
Feb 10 14:33:01 echo salt-master[2373]: [ERROR   ] Failed to import utils win_osinfo, this is due most likely to a syntax error:
Feb 10 14:33:01 echo salt-master[2373]: Traceback (most recent call last):
Feb 10 14:33:01 echo salt-master[2373]:   File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1334, in _load_module
Feb 10 14:33:01 echo salt-master[2373]:     ), fn_, fpath, desc)
Feb 10 14:33:01 echo salt-master[2373]:   File "/usr/lib/python2.7/dist-packages/salt/utils/win_osinfo.py", line 32, in <module>
Feb 10 14:33:01 echo salt-master[2373]:     class OSVERSIONINFO(ctypes.Structure):
Feb 10 14:33:01 echo salt-master[2373]:   File "/usr/lib/python2.7/dist-packages/salt/utils/win_osinfo.py", line 33, in OSVERSIONINFO
Feb 10 14:33:01 echo salt-master[2373]:     _fields_ = (('dwOSVersionInfoSize', DWORD),
Feb 10 14:33:01 echo salt-master[2373]: NameError: name 'DWORD' is not defined
Feb 10 14:33:01 echo salt-master[2373]: [ERROR   ] Exception raised when processing __virtual__ function for boto_kinesis. Module will not be loaded 'boto3.assign_funcs'
Feb 10 14:33:01 echo salt-master[2373]: [WARNING ] salt.loaded.int.module.boto_kinesis.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'boto_kinesis', please fix this.
```

### Versions Report
```
# salt --versions-report
Salt Version:
           Salt: 2016.11.0-703-g8cd74af

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-62-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by ninja-** [comment]
This is not an error, this is expected behaviour.
The loader tries to load all modules possible by calling ``` __virtual__``` function on them and fails on modules that are not compatible with current system, like in your case Windows related modules.

**Comment by Ch3LL** [comment]
agreed the load does try to load modules but we definitely don't want to be stack tracing. We want to catch these exceptions on loading of the module.

ping @twangboy looks like you fixed this in https://github.com/saltstack/salt/pull/38456/files but looks like in develop its still trying to load the win utils. Is the correct fix to just add NameError to the try/except in the boto_kinesis or do we need to make sure we aren't even trying to load the windows stuff and gate ti properly? I check

**Comment by terminalmage** [comment]
@pepoluan Did you by chance set `utils_dirs` in your master config file?

**Comment by pepoluan** [comment]
@terminalmage Nope. `utils_dirs` is not set anywhere.

In fact, this is the first time I ever heard of it 😄

**Comment by freach** [comment]
Same issue here. Started getting these errors after installing `python-boto3` package on my Ubuntu 16.04 Salt master. So I figure it's related to `python-boto3` dependencies. Purging `python-boto3` and all dependencies fixes the issue for me.

`python-boto3` depedencies are:
```
docutils-common docutils-doc libjbig0 libjpeg-turbo8 libjpeg8 liblcms2-2 libpaper-utils libpaper1 libtiff5 libwebp5 libwebpmux1 python-botocore python-docutils python-jmespath python-pil python-pygments python-roman
```

```
# salt --versions-report
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-62-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by terminalmage** [comment]
@pepoluan yeah after further investigation I found that the loader is indeed inspecting all modules in the ``salt/utils/`` directory when the salt CLI command is run. The person who wrote the code causing the log entries is working on fixing them. The problem stems from windows-specific modules being invoked in the global scope.

@freach that is actually not related to @pepoluan's issue. Can you post an example of the messages you're seeing?

**Comment by freach** [comment]
@terminalmage sure, here you go.

```
# salt-call state.apply some-state
[ERROR   ] Failed to import utils saltminionservice, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1332, in _load_module
    ), fn_, fpath, desc)
  File "/usr/lib/python2.7/dist-packages/salt/utils/saltminionservice.py", line 8, in <module>
    from salt.utils.winservice import Service, instart
  File "/usr/lib/python2.7/dist-packages/salt/utils/winservice.py", line 33, in <module>
    class Service(win32serviceutil.ServiceFramework):
NameError: name 'win32serviceutil' is not defined
[ERROR   ] Failed to import utils winservice, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1332, in _load_module
    ), fn_, fpath, desc)
  File "/usr/lib/python2.7/dist-packages/salt/utils/winservice.py", line 33, in <module>
    class Service(win32serviceutil.ServiceFramework):
NameError: name 'win32serviceutil' is not defined
[ERROR   ] Failed to import utils win_osinfo, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1332, in _load_module
    ), fn_, fpath, desc)
  File "/usr/lib/python2.7/dist-packages/salt/utils/win_osinfo.py", line 32, in <module>
    class OSVERSIONINFO(ctypes.Structure):
  File "/usr/lib/python2.7/dist-packages/salt/utils/win_osinfo.py", line 33, in OSVERSIONINFO
    _fields_ = (('dwOSVersionInfoSize', DWORD),
NameError: name 'DWORD' is not defined
local:
----------
          [...]

Summary for local
------------
Succeeded: 2
Failed:    0
------------
Total states run:     2
Total run time: 293.250 ms
```

**Comment by terminalmage** [comment]
Oh OK, those *are* the same issue then. You said it happened after installing the boto module, so I figured they were similar but coming from boto modules instead of modules in ``salt.utils``.

**Comment by terminalmage** [comment]
Anyway, thanks for helping to clear that up! We should have this fixed by the next feature release, sorry for the nuisance.

**Comment by terminalmage** [comment]
Er, point release, not feature release. :smile:

**Comment by pepoluan** [comment]
Ahhh, I confirm that I, too, had installed `python-boto3`.

Let me zap that and report back.

**Comment by pepoluan** [comment]
Oops, forgot to report back:

Yes, the errors disappear when I remove `python-boto3`.

**Comment by twangboy** [comment]
Has anyone tried this with the two PR's I did above? It should have fixed the issue whether boto was installed or not.

**Comment by pepoluan** [comment]
@twangboy Hmm... since the PR's have been merged, should be effective when I refresh my salt-master installation, no? (I use `bootstrap.sh git develop`)

Let me do a refresh + reinstall boto3, and I'll get back to you.

**Comment by rmarchei** [comment]
This issue is still present on the current salt version and I can confirm it's related to `python-boto3`.

```
# salt --versions-report
Salt Version:
           Salt: 2016.11.4

Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.3.7
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-72-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by noelmcloughlin** [comment]
The issue is still present in 2017.7 when both `python-boto` and `python3-boto` are installed.

I uninstalled the python2 boto package and Errors stopped.
```
 salt --versions-report
Salt Version:
           Salt: 2017.7.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.13.0-1011-gcp
         system: Linux
        version: Ubuntu 16.04 xenial
 
# dpkg-query --list | grep boto
ii  python-boto                      2.38.0-1ubuntu1                         all          Python interface to Amazon's Web Services - Python 2.x
ii  python3-boto                     2.38.0-1ubuntu1                         all          Python interface to Amazon's Web Services - Python 3.x

# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial


# apt-get remove python-boto
```
