### ISSUE TITLE
TypeError on output: salt '*' -p -s test.ping

### ISSUE THREAD

**Issue by qurczak** [saltstack/salt#39331]
### Description of Issue/Question
**TypeError: output() takes exactly 2 arguments (1 given)** will appear when we run command with -p switch and also with -s

with or without parameter --out=txt, command show us the same exception

### Steps to Reproduce Issue

OK:
```
$ salt cube.lan  test.ping --out=txt
cube.lan: True
$ salt cube.lan -p  test.ping --out=txt
[...OK...]
$ salt cube.lan -s  test.ping --out=txt
[...OK...]
```

Problem:
```
# salt -p -s cube.lan test.ping --out=txt
[ERROR   ] Nested output failed: 
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/output/__init__.py", line 44, in try_printout
    printout = get_printout('nested', opts)(data, **kwargs)
TypeError: output() takes exactly 2 arguments (1 given)
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: output() takes exactly 2 arguments (1 given)
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 464, in salt_main
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/salt.py", line 59, in run
    self._run_batch()
  File "/usr/lib/python2.7/site-packages/salt/cli/salt.py", line 238, in _run_batch
    self._output_ret(ret, '')
  File "/usr/lib/python2.7/site-packages/salt/cli/salt.py", line 344, in _output_ret
    salt.output.display_output(ret, out, self.config)
  File "/usr/lib/python2.7/site-packages/salt/output/__init__.py", line 91, in display_output
    display_data = try_printout(data, out, opts, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/output/__init__.py", line 49, in try_printout
    printout = get_printout('raw', opts)(data, **kwargs)
TypeError: output() takes exactly 2 arguments (1 given)
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 464, in salt_main
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/salt.py", line 59, in run
    self._run_batch()
  File "/usr/lib/python2.7/site-packages/salt/cli/salt.py", line 238, in _run_batch
    self._output_ret(ret, '')
  File "/usr/lib/python2.7/site-packages/salt/cli/salt.py", line 344, in _output_ret
    salt.output.display_output(ret, out, self.config)
  File "/usr/lib/python2.7/site-packages/salt/output/__init__.py", line 91, in display_output
    display_data = try_printout(data, out, opts, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/output/__init__.py", line 49, in try_printout
    printout = get_printout('raw', opts)(data, **kwargs)
TypeError: output() takes exactly 2 arguments (1 given)
root@asus-p7f-x:/srv/salt/_problems# 

```

### Versions Report
```
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: 1.9.1
       cherrypy: unknown
       dateutil: 2.6.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.6.7
         Jinja2: 2.9.5
        libgit2: 0.24.3
        libnacl: 1.5.0
       M2Crypto: 0.24.0
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: 0.24.2
         Python: 2.7.13 (default, Dec 21 2016, 07:16:46)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: 0.6.6
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.2.0
 
System Versions:
           dist:   
        machine: x86_64
        release: 4.9.6-1-ARCH
         system: Linux
        version: Not Installed

```

**Comment by terminalmage** [comment]
This is happening because ``salt.output.display_output()`` is being called from the bits that handle the ``-s`` flag, and it ends up tryng to invoke ``salt.output.try_output()``, which because ``__opts__['progress']`` is True attempts to invoke the progress outputter without passing a progress bar object.

@cachedout, I'm not sure how to proceed on this, do you have any insight since you added this outputter initially?

**Comment by qurczak** [comment]
I think, maybe should be visible warning/error when someone use '-s' an '-p'  at the same time. I guess.

**Comment by terminalmage** [comment]
Yeah, I had considered that, but I wanted to get @cachedout's insight as well.
