### ISSUE TITLE
salt.modules.timezone: It is not enough to check for timedatectl existence

### ISSUE THREAD

**Issue by Whissi** [saltstack/salt#39357]
### Description of Issue/Question
*salt.modules.timezone* only checks if *timedatectl* exists but this not enough: *dbus-daemon* must be installed and running as well. Otherwise you will get an error like

```
minion32.example.org:
----------
          ID: Europe/Berlin
    Function: timezone.system
      Result: False
     Comment: Unable to compare desired timezone 'Europe/Berlin' to system timezone: timedatectl failed: Failed to create bus connection: No such file or directory
     Started: 13:58:54.247773
    Duration: 7.331 ms
     Changes:
----------

```

### Steps to Reproduce Issue
1. Install Debian Jessie (8.7 as of today) in *minbase* variant using *debootstrap* (`debootstrap --variant=minbase --arch amd64 jessie /mnt/debian http://httpredir.debian.org/debian`).

2. Create a *timezone.sls* state with the following content:
```yaml
Europe/Berlin:
  timezone.system
```
3. Execute the state on your fresh system set up in step 1.

### Versions Report
```
# salt --versions-report
Salt Version:
           Salt: 2016.11.2

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.7
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.7
```
(Salt from https://repo.saltstack.com/#debian)

**Comment by gtmanfred** [comment]
Thanks for reporting this issue.  If you wanted to submit a PR to fix this, we would greatly appreciate it.  Otherwise our platform team will take a look.

Daniel

**Comment by boltronics** [comment]
Even checking `dbus-daemon` and `timedatectl` isn't enough. You also need to have `/etc/adjtime` present and configured to avoid a stack trace.
```
----------
          ID: Australia/Melbourne
    Function: timezone.system
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1843, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1795, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/timezone.py", line 73, in system
                  if __salt__['timezone.get_hwclock']() == 'localtime':
                File "/usr/lib/python2.7/dist-packages/salt/modules/timezone.py", line 412, in get_hwclock
                  return _get_adjtime_timezone()
                File "/usr/lib/python2.7/dist-packages/salt/modules/timezone.py", line 75, in _get_adjtime_timezone
                  'Unable to get hwclock timezone from ' + adjtime_file
              CommandExecutionError: Unable to get hwclock timezone from /etc/adjtime
     Started: 13:23:57.547588
    Duration: 13.067 ms
     Changes:   
```
This is on Debian Jessie as well, running 2017.7.2.

**Comment by smaragd** [comment]
I am running into the same issue today with this environment:
```
# salt-call --versions-report
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: ISO-8859-1
        machine: x86_64
        release: 4.4.0-87-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
My clumsy work-around is to create a dependency on the `dbus` package:
```yaml
dbus:
  pkg.installed

America/New_York:
  timezone.system:
    - utc: True
    - require:
      - pkg: dbus
```

**Comment by lordcirth** [comment]
I ran into the same error message, and found this issue, but my case may be different. I believe my issue is that systemd-timesyncd doesn't start on LXC containers, since it couldn't change the time anyway.

**Comment by lordcirth** [comment]
I just restricted the timezone state to physical hosts; this worked around my issue. It only occurred on LXC for me.
