### ISSUE TITLE
Problem with match.filter_by when I target pillar

### ISSUE THREAD

**Issue by gigi206** [saltstack/salt#39371]
### Description of Issue/Question
Since 3 days I test salt and it's a great tool but I encounter a problem with **match.filter_by** when targeting **pillar** (but not with others like **ipcidr**)

### Setup
/srv/pillar/top.sls :
```
base:
  '*':
    - network
```

/srv/pillar/network.sls :
```
{% set network = salt['match.filter_by']({
     'S@192.168.2.0/24': {
         'site': 'site2',
         'dmz': 'dmz2',
     },
     'S@10.0.2.0/24': {
         'site': 'site3',
         'dmz': 'dmz3',
     },
     '*':{
         'site': 'site1',
         'dmz': 'dmz1',
     }
}) %}

network:
  - site: {{ network['site'] }}
  - dmz:  {{ network['dmz'] }}
```

### Steps to Reproduce Issue
In /srv/salt/... I use :
```
{% set ntpservers = salt['match.filter_by']({
     'I@network:dmz:dmz1': ['0.pool.ntp.org', '2.pool.ntp.org'],
     'I@network:dmz:dmz2': ['2.pool.ntp.org'],
}) %}

{% for ntpserver in ntpservers -%}
server {{ ntpserver }}
{% endfor %}
```

I try it and it dosen't work (`salt '*' state.apply test.sls`)  because salt found no match :
```
              TypeError: 'NoneType' object is not iterable
              
              ; line 12
              
              ---
              [...]
                   'I@network:dmz:dmz1': ['0.pool.ntp.org', '2.pool.ntp.org'],
                   'I@network:dmz:dmz2': ['2.pool.ntp.org'],
              }) %}
              
              # Associate to public NTP pool servers; see http://www.pool.ntp.org/
              {% for ntpserver in ntpservers -%}    <======================
              server {{ ntpserver }}
              {% endfor %}
```

I use this compound to test and I see it works but not the code above :
```
$ salt -C 'I@network:dmz:dmz1' test.ping
portable.local:
    True
```

I don't understand why `I@` doesn't work. But `@S` seems work well if I replace by this code :
```
{% set ntpservers = salt['match.filter_by']({
     'S@10.0.2.0/24': ['0.pool.ntp.org', '2.pool.ntp.org'],
     'S@192.168.1.0/24': ['2.pool.ntp.org'],
}) %}
```

Is it a bug or I have done something wrong ?

### Versions Report
```
$ salt --versions-report
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: 1.7.0
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.25.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 12 2017, 17:59:37)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4
 
System Versions:
           dist: fedora 25 Twenty Five
        machine: x86_64
        release: 4.9.6-200.fc25.x86_64
         system: Linux
        version: Fedora 25 Twenty Five
```

**Comment by gtmanfred** [comment]
So, network won't be in the name, that is just the name of the file, try using this for your state.

```
{% set ntpservers = salt['match.filter_by']({
     'I@dmz:dmz1': ['0.pool.ntp.org', '2.pool.ntp.org'],
     'I@dmz:dmz2': ['2.pool.ntp.org'],
}) %}

{% for ntpserver in ntpservers -%}
server {{ ntpserver }}
{% endfor %}
```

**Comment by gigi206** [comment]
I try with this pillar :
```
{% set network = salt['match.filter_by']({
     'S@192.168.2.0/24': {
         'site': 'site2',
         'dmz': 'dmz2',
     },
     'S@10.0.2.0/24': {
         'site': 'site3',
         'dmz': 'dmz3',
     },
     '*':{
         'site': 'site1',
         'dmz': 'dmz1',
     }
}) %}

network:
  - site: {{ network['site'] }}
  - dmz:  {{ network['dmz'] }
```

And this pillar (2 lasts lines changed) (update pillar with `salt '*' saltutil.refresh_pillar`) :
```
{% set network = salt['match.filter_by']({
     'S@192.168.2.0/24': {
         'site': 'site2',
         'dmz': 'dmz2',
     },
     'S@10.0.2.0/24': {
         'site': 'site3',
         'dmz': 'dmz3',
     },
     '*':{
         'site': 'site1',
         'dmz': 'dmz1',
     }
}) %}

site: {{ network['site'] }}
dmz:  {{ network['dmz'] }
```

And I change :
```
{% set ntpservers = salt['match.filter_by']({
     'I@network:dmz:dmz1': ['0.pool.ntp.org', '2.pool.ntp.org'],
     'I@network:dmz:dmz2': ['2.pool.ntp.org'],
}) %}
```
to 
```
{% set ntpservers = salt['match.filter_by']({
     'I@dmz:dmz1': ['0.pool.ntp.org', '2.pool.ntp.org'],
     'I@dmz:dmz2': ['2.pool.ntp.org'],
}) %}
```

Same error because dmz1 not match :
```
----------
          ID: ntp_conf
    Function: file.managed
        Name: /etc/ntp.conf
      Result: False
     Comment: Unable to manage file: Jinja error: 'NoneType' object is not iterable
              Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 368, in render_jinja_tmpl
                  output = template.render(**decoded_context)
                File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
                  return self.environment.handle_exception(exc_info, True)
                File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
                  reraise(exc_type, exc_value, tb)
                File "<template>", line 12, in top-level template code
              TypeError: 'NoneType' object is not iterable
              
              ; line 12
              
              ---
              [...]
                   'I@dmz:dmz1': ['0.pool.ntp.org', '2.pool.ntp.org'],
                   'I@dmz:dmz2': ['2.pool.ntp.org'],
              }) %}
              
              # Associate to public NTP pool servers; see http://www.pool.ntp.org/
              {% for ntpserver in ntpservers -%}    <======================
              server {{ ntpserver }}
              {% endfor %}
              
              # Only allow read-only access from localhost
              restrict default kod nomodify
              [...]
```

**Comment by gtmanfred** [comment]
ahh, my appologies, i missread the pillar file.

**Comment by gtmanfred** [comment]
Can you provide the output of the module `pillar.items` ?

Thanks,
Daniel

**Comment by gigi206** [comment]
```
[root@portable ntp]# salt '*' pillar.items
portable.local:
    ----------
    network:
        |_
          ----------
          site:
              site1
        |_
          ----------
          dmz:
              dmz1
```
 Thank you for your help :)

**Comment by gtmanfred** [comment]
If you check your minion logs, do you see something like this?

```
[DEBUG   ] pillar target: network:dmz:dmz1
[ERROR   ] 'pillar'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/modules/match.py", line 49, in compound
    return matcher.compound_match(tgt)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 2958, in compound_match
    str(getattr(self, '{0}_match'.format(engine))(*engine_args, **engine_kwargs))
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 2819, in pillar_match
    self.opts['pillar'], tgt, delimiter=delimiter
KeyError: 'pillar'
```

I am going to create a docker image to better illustrate the error, but it looks like this is a bug.

Thanks,
Daniel

**Comment by gigi206** [comment]
/var/log/salt/minion :
```
2017-02-14 00:01:02,986 [salt.loaded.int.module.match][ERROR   ][3386] 'pillar'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/modules/match.py", line 49, in compound
    return matcher.compound_match(tgt)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 2949, in compound_match
    str(getattr(self, '{0}_match'.format(engine))(*engine_args, **engine_kwargs))
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 2810, in pillar_match
    self.opts['pillar'], tgt, delimiter=delimiter
KeyError: 'pillar'
2017-02-14 00:01:03,003 [salt.loaded.int.module.match][ERROR   ][3386] 'pillar'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/modules/match.py", line 49, in compound
    return matcher.compound_match(tgt)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 2949, in compound_match
    str(getattr(self, '{0}_match'.format(engine))(*engine_args, **engine_kwargs))
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 2810, in pillar_match
    self.opts['pillar'], tgt, delimiter=delimiter
KeyError: 'pillar'
2017-02-14 00:01:03,069 [salt.utils.templates][ERROR   ][3386] Rendering exception occurred: Jinja error: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 368, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 12, in top-level template code
TypeError: 'NoneType' object is not iterable

; line 12

---
[...]
     'I@dmz:dmz1': ['0.pool.ntp.org', '2.pool.ntp.org'],
     'I@dmz:dmz2': ['2.pool.ntp.org'],
}) %}

# Associate to public NTP pool servers; see http://www.pool.ntp.org/
{% for ntpserver in ntpservers -%}    <======================
server {{ ntpserver }}
{% endfor %}

# Only allow read-only access from localhost
restrict default kod nomodify
[...]
---
2017-02-14 00:01:03,102 [salt.state       ][ERROR   ][3386] Unable to manage file: Jinja error: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 368, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 12, in top-level template code
TypeError: 'NoneType' object is not iterable

; line 12

---
[...]
     'I@dmz:dmz1': ['0.pool.ntp.org', '2.pool.ntp.org'],
     'I@dmz:dmz2': ['2.pool.ntp.org'],
}) %}

# Associate to public NTP pool servers; see http://www.pool.ntp.org/
{% for ntpserver in ntpservers -%}    <======================
server {{ ntpserver }}
{% endfor %}

# Only allow read-only access from localhost
restrict default kod nomodify
[...]
---
```

**Comment by gtmanfred** [comment]
Yup, that is the issue then. I will make a docker image to show the error
for someone to fix it.

Thanks for reporting,
Daniel
