### ISSUE TITLE
file.directory does not handle overwriting old symlinks

### ISSUE THREAD

**Issue by chowell5** [saltstack/salt#39393]
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
I have the following SLS

```
/etc/default/xyz:
  file.directory:
  - follow_symlinks: False
  - makedirs: True
  - force: True
```

Currently, /etc/default/xyz is a dangling symlink

```
root@abc:/etc/default# ls -l xyz
lrwxrwxrwx 1 root root 13 Feb 14 12:01 xyz -> /doesnt/exist
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

Expected behaviour: I've told salt that I want /etc/default/xyz to be a directory. I expect it to remove the old symlink if present, particularly when I've set force: True and follow_symlinks: False

I shouldn't have to invent cumbersome code to check if it's a symlink and if so, remove that, first.

```
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1744, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1702, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 2226, in directory
    name, user=user, group=group, mode=dir_mode
  File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 4906, in mkdir
    makedirs_perms(directory, user, group, mode)
  File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 5003, in makedirs_perms
    os.mkdir(name)
OSError: [Errno 17] File exists: '/etc/default/xyz'

local:
----------
          ID: /etc/default/xyz
    Function: file.directory
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1744, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1702, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 2226, in directory
                  name, user=user, group=group, mode=dir_mode
                File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 4906, in mkdir
                  makedirs_perms(directory, user, group, mode)
                File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 5003, in makedirs_perms
                  os.mkdir(name)
              OSError: [Errno 17] File exists: '/etc/default/xyz'
     Started: 12:57:38.571751
    Duration: 25.5 ms
     Changes:

```
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
root@abc:/etc/default# salt-call --versions-report
Salt Version:
           Salt: 2016.11.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: 0.3.6
         PyYAML: 3.11
          PyZMQ: Not Installed
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: Not Installed

System Versions:
           dist: debian 8.6
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.6
```

Running masterless as this is a dev environment.

**Comment by Ch3LL** [comment]
@chowell5 yeah we definitely need to be deleting that file if `force: true`. I've been able to replicate this issue.

Here is a docker container for anyone to quickly repllicate this issue.

1. `docker run -it -v /home/ch3ll/git/salt/:/testing/ ch3ll/issues:39393 salt-call --local state.sls test -ldebug` (where /home/ch3ll/git/salt is a loca cloned git repo of salt)

I also see this behavior in 2016.3.4 so this is not a regression.

**Comment by narendraingale2** [comment]
work around for this bug is set `allow_symlink = False`.

**Comment by chowell5** [comment]
There is no evidence this issue was fixed. Wouldn't it be good to tie the automatic bug closer to something that uses the test cases to device whether issues should be closed or not?

**Comment by rallytime** [comment]
We are certainly happy to re-open this. Thanks for letting us know!
