### ISSUE TITLE
Unable to parse version string: \\'{0}\\''.format(version_string)\nValueError: Unable to parse version string: 'Module 'test' is not available.

### ISSUE THREAD

**Issue by tjyang** [saltstack/salt#39440]
### Description of Issue/Question
I have a daily cron job to report versions of salt-minions managed. But after upgraded to 2016.11.2, it started to failed with following error message.

From the error message, it looks like it failed when querying an older version of minion.

### Setup
N/A

### Steps to Reproduce Issue

```
[me@salt01 ~]$ sudo  salt-run  -l debug manage.versions --out=json
<snipped>
[DEBUG   ] jid 20170216061734805180 return from ldbpwind02
[DEBUG   ] jid 20170216061734805180 return from ldbp01
[DEBUG   ] Checking whether jid 20170216061734805180 is still running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'salt01_master', 'tcp://127.0.0.1:4506', 'clea\
r')
[DEBUG   ] Passing on saltutil error. This may be an error in saltclient. 'retcode'
[DEBUG   ] jid 20170216061734805180 return from laptop02
[DEBUG   ] Sending event: tag = salt/run/20170216061734163992/ret; data = {'fun_args': [], 'jid': '20170216061734163992', 're\
turn': 'Exception occurred in runner manage.versions: Traceback (most recent call last):\n  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 395, in _low\n    data[\'return\'] = self.functions[fun](*args, **kwargs)\n  File "/usr/li\
b/python2.7/site-packages/salt/runners/manage.py", line 617, in versions\n    minion_version = salt.version.SaltStackVersion.\
parse(minions[minion])\n  File "/usr/lib/python2.7/site-packages/salt/version.py", line 260, in parse\n    \'Unable to parse version string: \\\'{0}\\\'\'.format(version_string)\nValueError: Unable to parse version string: \'Module \'test\' is not av\
ailable.\'\n', 'success': False, '_stamp': '2017-02-16T12:17:50.076871', 'user': 'sudo_me', 'fun': 'runner.manage.versions'}
[DEBUG   ] LazyLoaded json.output
"Exception occurred in runner manage.versions: Traceback (most recent call last):\n  File \"/usr/lib/python2.7/site-packages/salt/client/mixins.py\", line 395, in _low\n    data['return'] = self.functions[fun](*args, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/salt/runners/manage.py\", line 617, in versions\n    minion_version = salt.version.SaltStackVersion.parse\
(minions[minion])\n  File \"/usr/lib/python2.7/site-packages/salt/version.py\", line 260, in parse\n    'Unable to parse version string: \\'{0}\\''.format(version_string)\nValueError: Unable to parse version string: 'Module 'test' is not available.'\\
n"
[DEBUG   ] LazyLoaded local_cache.prep_jid
[INFO    ] Runner completed: 20170216061734163992
[DEBUG   ] Runner return: Exception occurred in runner manage.versions: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 395, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/runners/manage.py", line 617, in versions
    minion_version = salt.version.SaltStackVersion.parse(minions[minion])
  File "/usr/lib/python2.7/site-packages/salt/version.py", line 260, in parse
    'Unable to parse version string: \'{0}\''.format(version_string)
ValueError: Unable to parse version string: 'Module 'test' is not available.'

[me@salt01 ~]$
```

### Versions Report
```
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: 1.3.8
         Jinja2: 2.7.2
        libgit2: 0.21.0
        libnacl: 1.4.3
       M2Crypto: 0.21.1
           Mako: 0.8.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.4
         Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.36.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
 ```

**Comment by Ch3LL** [comment]
@tjyang what version is the older minion on?

**Comment by tjyang** [comment]
@Ch3LL, I can't identify which minion has issue from "salt-run -l debug/trace" output.
Can you advise how can I find out which minion ?

**Comment by tjyang** [comment]
Hi @Ch3LL , Here is what happened and resolved.

```
WHAT: bad minion was updated using a saltstack formula, it ended up with two version of minions.
"salt \* test.ping |grep -3 available" command  was able to discover bad minion(with two minions) which reporting "Module 'test' is not available".

HOW: login into bad minion to kill old salt-minion process and start up the 11.2 version.

```

bad minion version info, after upgrade.
 
```
    Salt Version:
               Salt: 2016.11.2

    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 1.4.1
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.8.1
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: 0.20.2
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.6.6 (r266:84292, Aug  9 2016, 06:11:56)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.5.0
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5

    System Versions:
               dist: redhat 6.8 Santiago
            machine: x86_64
            release: 2.6.32-642.11.1.el6.x86_64
             system: Linux
            version: Red Hat Enterprise Linux Server 6.8 Santiago

```

Hopefully, in the future, salt-minion has built-in logic to avoid starting two versions at the same time.
@Ch3LL, pls close this issue if there is no todo.

**Comment by Ch3LL** [comment]
@tjyang thanks for tracking that down. I believe you are running into this: https://github.com/saltstack/salt/issues/39200 I'll close this issue to track the fix there
