### ISSUE TITLE
Exception parsing response when minion startup with transport=tcp.

### ISSUE THREAD

**Issue by jackywu** [saltstack/salt#39473]
### Description of Issue/Question

after set `transport=tcp`, restart my minion，there is lots of exception message in log file.
![default](https://cloud.githubusercontent.com/assets/587955/23050209/d3caef70-f4fb-11e6-91b6-0d71d839e3dd.png)

from the log, it seems minion create a channel to master to auth, but receive a bad respone.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

```

2017-02-16 16:13:31,120 [salt.config                              ][DEBUG   ][28188] Reading configuration from /etc/salt/minion
2017-02-16 16:13:31,151 [salt.config                              ][DEBUG   ][28188] Including configuration from '/etc/salt/minion.d/_schedule.conf'
2017-02-16 16:13:31,151 [salt.config                              ][DEBUG   ][28188] Reading configuration from /etc/salt/minion.d/_schedule.conf
2017-02-16 16:13:31,439 [salt.minion                                          ][INFO    ][28188] Creating minion process manager
2017-02-16 16:13:31,440 [salt.cli.daemons                                     ][WARNING ][28188] IMPORTANT: Do not use md5 hashing algorithm! Please set "hash_type" to sha256 in Salt Minion config!
2017-02-16 16:13:31,440 [salt.cli.daemons                                     ][INFO    ][28188] The Salt Minion is starting up
2017-02-16 16:13:31,440 [salt.minion                                          ][INFO    ][28188] Minion is starting as user 'root'
2017-02-16 16:13:31,441 [salt.utils.event                                     ][DEBUG   ][28188] AsyncEventPublisher PUB socket URI: 4510
2017-02-16 16:13:31,441 [salt.utils.event                                     ][DEBUG   ][28188] AsyncEventPublisher PULL socket URI: 4511
2017-02-16 16:13:31,441 [salt.utils.event                                     ][INFO    ][28188] Starting pull socket on 4511
2017-02-16 16:13:31,442 [salt.minion                                          ][DEBUG   ][28188] Minion 'l168-223-45' trying to tune in
2017-02-16 16:13:31,442 [salt.minion                                          ][DEBUG   ][28188] sync_connect_master
2017-02-16 16:13:31,442 [salt.minion                                          ][INFO    ][28188] Got list of available master addresses: ['x', 'y', 'z']
2017-02-16 16:13:31,442 [salt.minion                                          ][CRITICAL][28188] 'master_type' set to 'failover' but 'retry_dns' is not 0. Setting 'retry_dns' to 0 to failover to the next master on DNS errors.
2017-02-16 16:13:31,442 [salt.minion                                          ][DEBUG   ][28188] Connecting to master. Attempt 1 of 1
2017-02-16 16:13:31,458 [salt.utils.event                                     ][DEBUG   ][28188] SaltEvent PUB socket URI: 4510
2017-02-16 16:13:31,458 [salt.utils.event                                     ][DEBUG   ][28188] SaltEvent PULL socket URI: 4511
2017-02-16 16:13:31,458 [salt.crypt                                           ][DEBUG   ][28188] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'x', 'tcp://192.168.1.1:4506')
2017-02-16 16:13:31,461 [salt.crypt                                           ][DEBUG   ][28188] Loaded minion key: /etc/salt/pki/minion/minion.pem
2017-02-16 16:13:31,466 [salt.utils.process                                   ][DEBUG   ][28188] Process Manager starting!
2017-02-16 16:13:31,480 [salt.transport.tcp                                   ][DEBUG   ][28188] Initializing new AsyncTCPReqChannel for ('/etc/salt/pki/minion', 'x', 'tcp://192.168.1.1:4506', 'clear')
2017-02-16 16:13:31,543 [salt.transport.tcp                                   ][ERROR   ][28188] Exception parsing response
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/transport/tcp.py", line 710, in _stream_return
    header = framed_msg['head']
TypeError: 'int' object is unsubscriptable
2017-02-16 16:13:31,546 [tornado.application                                  ][ERROR   ][28188] Exception in callback <functools.partial object at 0x3280368>
Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/tornado/ioloop.py", line 591, in _run_callback
    ret = callback()
  File "/usr/lib64/python2.6/site-packages/tornado/stack_context.py", line 274, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib64/python2.6/site-packages/tornado/ioloop.py", line 597, in <lambda>
    self.add_future(ret, lambda f: f.result())
  File "/usr/lib64/python2.6/site-packages/tornado/concurrent.py", line 214, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.6/site-packages/salt/crypt.py", line 467, in _authenticate
    creds = yield self.sign_in(channel=channel)
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib64/python2.6/site-packages/tornado/concurrent.py", line 214, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.6/site-packages/salt/crypt.py", line 540, in sign_in
    timeout=timeout
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib64/python2.6/site-packages/tornado/concurrent.py", line 214, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.6/site-packages/salt/transport/tcp.py", line 248, in send
    ret = yield self._uncrypted_transfer(load, tries=tries, timeout=timeout)
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib64/python2.6/site-packages/tornado/concurrent.py", line 214, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.6/site-packages/salt/transport/tcp.py", line 238, in _uncrypted_transfer
    ret = yield self.message_client.send(self._package_load(load), timeout=timeout)
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib64/python2.6/site-packages/tornado/concurrent.py", line 214, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
TypeError: 'int' object is unsubscriptable
2017-02-16 16:13:31,600 [salt.transport.tcp                                   ][ERROR   ][28188] Exception parsing response
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/transport/tcp.py", line 710, in _stream_return
    header = framed_msg['head']
TypeError: 'int' object is unsubscriptable
2017-02-16 16:13:31,632 [salt.transport.tcp                                   ][ERROR   ][28188] Exception parsing response
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/transport/tcp.py", line 710, in _stream_return
    header = framed_msg['head']
TypeError: 'int' object is unsubscriptable

```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
#  salt --versions-report
Salt Version:
           Salt: 2016.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.6.7
         Jinja2: 2.2.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5
 
System Versions:
           dist: centos 6.6 Final
        machine: x86_64
        release: 2.6.32-504.30.3.el6.x86_64
         system: Linux
        version: CentOS 6.6 Final
```

**Comment by jackywu** [comment]
@jacksontj could you share some experience using transport=tcp in Linkedin？

**Comment by gtmanfred** [comment]
I have tried to replicate your environment as much as possible, and I am unable to replicate this error.

```
[root@salt ~]# salt \* config.get transport -l debug
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/transport.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/transport.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt.c.gtmanfred-1263.internal
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/transport.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/transport.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt.c.gtmanfred-1263.internal
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncTCPReqChannel for ('/etc/salt/pki/master', 'salt.c.gtmanfred-1263.internal_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/92/f503c3ff223f48b85603895d520133/.minions.p
[DEBUG   ] get_iter_returns for jid 20170217150234303046 sent to set(['salt.c.gtmanfred-1263.internal']) will timeout at 15:02:39.316555
[DEBUG   ] jid 20170217150234303046 return from salt.c.gtmanfred-1263.internal
[DEBUG   ] LazyLoaded nested.output
salt.c.gtmanfred-1263.internal:
    tcp
[DEBUG   ] jid 20170217150234303046 found all minions set(['salt.c.gtmanfred-1263.internal'])
[root@salt ~]# salt \* test.versions_report -l info
salt.c.gtmanfred-1263.internal:
    Salt Version:
               Salt: 2016.3.3

    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.7.3
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.5.0
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5

    System Versions:
               dist: centos 6.8 Final
            machine: x86_64
            release: 2.6.32-642.13.1.el6.x86_64
             system: Linux
            version: CentOS 6.8 Final
```

What version of the salt minion are you running?

Thanks,
Daniel

**Comment by jackywu** [comment]
@gtmanfred  minion version is '2016.3.3'. and what's more, I run minion in Docker Container.

**Comment by gtmanfred** [comment]
Ok, yeah I set the minion up with salt 2016.3.3, I can try running in a
docker container.

**Comment by jacksontj** [comment]
From a quick read it sounds like maybe the master wasn't updated to TCP transport at the same time? Right now the various transports don't really "discover" at all-- they just assume the remote they are talking to matches (which is why the default is still zmq -- we don't allow for backwards incompatible changes :( ). If that is *not* the case (meaning the master *is* configured to use `tcp`) definitely let me know -- I'd be more than happy to dig in :)
