### ISSUE TITLE
Unable to schedule a custom module function that references a custom utils function

### ISSUE THREAD

**Issue by ekristen** [saltstack/salt#39491]
### Description of Issue/Question
I'm trying to schedule a module function that references __utils__ of a custom utils function and I get a Key Error stating that the function is not available. 

The module function works under other normal usage, whether calling it via salt-call or via a custom salt state.

### Setup
I've obviously omitted some of the basics of the module files. 

_modules/mymodule.py
```python filename=_modules/mymodule.py
def testing():
  return __utils__['mymodule.testing']()
```

_utils/mymodule.py
```python filename=_utils/mymodule.py
def testing():
  return True
```

schedule.sls
```yaml filename=schedule.sls
testing-schedule:
  schedule.present:
    - function: mymodule.testing
    - seconds: 10
    - enabled: True
```

### Steps to Reproduce Issue
```
2017-02-17 03:26:56,713 [salt.utils.schedule][ERROR   ] Unhandled exception running mymodule.testing
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/schedule.py", line 836, in handle_func
    ret['return'] = self.functions[func](*args, **kwargs)
  File "/var/cache/salt/minion/extmods/modules/mymodule.py", line 200, in testing
    return __utils__['mymodule.testing']()
  File "/usr/lib/python2.7/dist-packages/salt/utils/context.py", line 203, in __getitem__
    return self._dict()[key]
KeyError: 'mymodule.testing'
```

### Versions Report
```
Salt Version:
           Salt: 2016.11.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-31-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by gtmanfred** [comment]
I have confirmed this as not working.

Thanks for the report, we will get it fixed.

Thanks,
Daniel

**Comment by ekristen** [comment]
Awesome! Thanks.
