### ISSUE TITLE
SLES 11 SP4 pkg.install failed because of Login failed

### ISSUE THREAD

**Issue by Ralle75** [saltstack/salt#39568]
### Description of Issue/Question
we have some problems with our SLES 11SP4 minions
our SLES installation has yup.gwdg.de as Repository Server, for this we need a user and password to use these Repository Server.

i have installed salt-minion version 2016.3.4 from [documentation](https://repo.saltstack.com/#suse)
our salt-master is an debian 8.7 version 2016.11.2 and works since 2 years without problems with our debian, ubuntu and windows minions

now we must use some SLES maschines, but i get an error if i use "salt 'minion' pkg.install krb5-client"

```
    Loading repository data...
    Reading installed packages...
    Resolving package dependencies...

    The following NEW package is going to be installed:
      krb5-client

    1 new package to install.
    Overall download size: 97.0 KiB. After the operation, additional 211.0 KiB will be used.
    Continue? [y/n/? shows all options] (y): y
    Retrieving package krb5-client-1.6.3-133.49.112.1.x86_64 (1/1), 97.0 KiB (211.0 KiB unpacked)
    Retrieving: krb5-client-1.6.3-133.49.112.1.x86_64.rpm [error]
    Login failed. (http://user@yup.gwdg.de/YUP/SLES11-SP4-Updates/sle-11-x86_64/rpm/x86_64/krb5-client-1.6.3-133.49.112.1.x86_64.rpm): The requested URL returned error: 401
    Abort, retry, ignore? [a/r/i/? shows all options] (a): a
    Failed to provide Package krb5-client-1.6.3-133.49.112.1. Do you want to retry retrieval?

    [GWDG_SP2_Updates|http://user@yup.gwdg.de/YUP/SLES11-SP4-Updates/sle-11-x86_64] Can't provide file './rpm/x86_64/krb5-client-1.6.3-133.49.112.1.x86_64.rpm' from repository 'GWDG_SP2_Updates'
    History:
     - Login failed. (http://user@yup.gwdg.de/YUP/SLES11-SP4-Updates/sle-11-x86_64/rpm/x86_64/krb5-client-1.6.3-133.49.112.1.x86_64.rpm): The requested URL returned error: 401
     - Can't provide ./rpm/x86_64/krb5-client-1.6.3-133.49.112.1.x86_64.rpm

    Abort, retry, ignore? [a/r/i] (a): a
    Problem occured during or after installation or removal of packages:
    Installation aborted by user

    Please see the above error message for a hint.
    ERROR: Minions returned with non-zero exit code
```

but if i restart the salt-minion on that SLES client, he install this package successful

### Versions Report

salt-master
```
Salt Version:
           Salt: 2016.11.2

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.7
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.7

```

salt-minion
```
Salt Version:
           Salt: 2016.3.4

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.9 (unknown, Aug  5 2016, 11:15:31)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.2.1

System Versions:
           dist: SuSE 11 x86_64
        machine: x86_64
        release: 3.0.101-94-default
         system: Linux
        version: SUSE Linux Enterprise Server  11 x86_64

```

**Comment by gtmanfred** [comment]
I am unable to replicate this issue.

```
salt:~ # salt-call --local pkg.install krb5-client

local:
    ----------
    krb5-client:
        ----------
        new:
            1.6.3-133.49.112.1
        old:
```

Can you provide the salt debug logs of when this command is ran and you get the error?

Thanks,
Daniel

**Comment by Ralle75** [comment]
a local salt-call works, but it doesnt work when i execute the command "salt 'sles*' pkg.install krb5-client" from salt-master, until i restart the salt-minion on the destination
below both logs, i notice that the salt-minion execute the command in directory / and after restart the salt-minion service he execute the same command in directory /root

salt-minion log before restarting salt-minion:
```
2017-02-23 16:56:59,090 [salt.minion                                            ][INFO    ][3731] User sudo_myuser Executing command pkg.install with jid 20170223165722969629
2017-02-23 16:56:59,090 [salt.minion                                            ][DEBUG   ][3731] Command details {'tgt_type': 'glob', 'jid': '20170223165722969629', 'tgt': 'sles*', 'ret': '', 'user': 'sudo_myuser', 'arg': ['krb5-client'], 'fun': 'pkg.install'}
2017-02-23 16:56:59,105 [salt.minion                                            ][INFO    ][3826] Starting a new job with PID 3826
2017-02-23 16:56:59,925 [salt.utils.lazy                                             ][DEBUG   ][3826] LazyLoaded pkg.install
2017-02-23 16:56:59,928 [salt.utils.lazy                                             ][DEBUG   ][3826] LazyLoaded direct_call.get
2017-02-23 16:57:00,291 [salt.utils.lazy                                             ][DEBUG   ][3826] Could not LazyLoad pkg.normalize_name
2017-02-23 16:57:00,292 [salt.loaded.int.module.cmdmod                               ][INFO    ][3826] Executing command ['rpm', '-qa', '--queryformat', '%{NAME}_|-%{VERSION}_|-%{RELEASE}_|-%|EPOCH?{%{EPOCH}}:{}|\\n'] in directory '/'
2017-02-23 16:57:02,148 [salt.loaded.int.module.zypper                               ][DEBUG   ][3826] Calling Zypper: zypper --non-interactive --no-refresh --no-refresh install --name --auto-agree-with-licenses krb5-client
2017-02-23 16:57:02,148 [salt.loaded.int.module.cmdmod                               ][INFO    ][3826] Executing command ['zypper', '--non-interactive', '--no-refresh', '--no-refresh', 'install', '--name', '--auto-agree-with-licenses', 'krb5-client'] in directory '/'
2017-02-23 16:57:02,988 [salt.loaded.int.module.cmdmod                               ][ERROR   ][3826] Command '['zypper', '--non-interactive', '--no-refresh', '--no-refresh', 'install', '--name', '--auto-agree-with-licenses', 'krb5-client']' failed with return code: 4
2017-02-23 16:57:02,988 [salt.loaded.int.module.cmdmod                               ][ERROR   ][3826] stdout: Loading repository data...
Reading installed packages...
Resolving package dependencies...

The following NEW package is going to be installed:
  krb5-client 

1 new package to install.
Overall download size: 97.0 KiB. After the operation, additional 211.0 KiB will be used.
Continue? [y/n/? shows all options] (y): y
Retrieving package krb5-client-1.6.3-133.49.112.1.x86_64 (1/1), 97.0 KiB (211.0 KiB unpacked)
Retrieving: krb5-client-1.6.3-133.49.112.1.x86_64.rpm [error]
Abort, retry, ignore? [a/r/i/? shows all options] (a): a
Abort, retry, ignore? [a/r/i] (a): a
2017-02-23 16:57:02,988 [salt.loaded.int.module.cmdmod                               ][ERROR   ][3826] stderr: Login failed. (https://repouser@yup.gwdg.de/YUP/SLES11-SP4-Updates/sle-11-x86_64/rpm/x86_64/krb5-client-1.6.3-133.49.112.1.x86_64.rpm): The requested URL returned error: 401
Failed to provide Package krb5-client-1.6.3-133.49.112.1. Do you want to retry retrieval?

[GWDG_SP2_Updates|https://repouser@yup.gwdg.de/YUP/SLES11-SP4-Updates/sle-11-x86_64] Can't provide file './rpm/x86_64/krb5-client-1.6.3-133.49.112.1.x86_64.rpm' from repository 'GWDG_SP2_Updates'
History:
 - Login failed. (https://repouser@yup.gwdg.de/YUP/SLES11-SP4-Updates/sle-11-x86_64/rpm/x86_64/krb5-client-1.6.3-133.49.112.1.x86_64.rpm): The requested URL returned error: 401
 - Can't provide ./rpm/x86_64/krb5-client-1.6.3-133.49.112.1.x86_64.rpm

Problem occured during or after installation or removal of packages:
Installation aborted by user

Please see the above error message for a hint.
2017-02-23 16:57:02,989 [salt.loaded.int.module.cmdmod                               ][ERROR   ][3826] retcode: 4
2017-02-23 16:57:02,989 [salt.minion                                                 ][ERROR   ][3826] A command in 'pkg.install' had a problem: Zypper command failure: Login failed. (https://repouser@yup.gwdg.de/YUP/SLES11-SP4-Updates/sle-11-x86_64/rpm/x86_64/krb5-client-1.6.3-133.49.112.1.x86_64.rpm): The requested URL returned error: 401
Failed to provide Package krb5-client-1.6.3-133.49.112.1. Do you want to retry retrieval?

[GWDG_SP2_Updates|https://repouser@yup.gwdg.de/YUP/SLES11-SP4-Updates/sle-11-x86_64] Can't provide file './rpm/x86_64/krb5-client-1.6.3-133.49.112.1.x86_64.rpm' from repository 'GWDG_SP2_Updates'
History:
 - Login failed. (https://repouser@yup.gwdg.de/YUP/SLES11-SP4-Updates/sle-11-x86_64/rpm/x86_64/krb5-client-1.6.3-133.49.112.1.x86_64.rpm): The requested URL returned error: 401
 - Can't provide ./rpm/x86_64/krb5-client-1.6.3-133.49.112.1.x86_64.rpm

Problem occured during or after installation or removal of packages:
Installation aborted by user

Please see the above error message for a hint.
Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/salt/minion.py", line 1363, in _thread_return
    return_data = executor.execute()
  File "/usr/lib64/python2.6/site-packages/salt/executors/direct_call.py", line 28, in execute
    return self.func(*self.args, **self.kwargs)
  File "/usr/lib64/python2.6/site-packages/salt/modules/zypper.py", line 1051, in install
    for line in __zypper__(no_repo_failure=ignore_repo_failure, systemd_scope=systemd_scope).call(*cmd).splitlines():
  File "/usr/lib64/python2.6/site-packages/salt/modules/zypper.py", line 299, in __call
    raise CommandExecutionError('Zypper command failure: {0}'.format(self.error_msg))
CommandExecutionError: Zypper command failure: Login failed. (https://repouser@yup.gwdg.de/YUP/SLES11-SP4-Updates/sle-11-x86_64/rpm/x86_64/krb5-client-1.6.3-133.49.112.1.x86_64.rpm): The requested URL returned error: 401
Failed to provide Package krb5-client-1.6.3-133.49.112.1. Do you want to retry retrieval?

[GWDG_SP2_Updates|https://repouser@yup.gwdg.de/YUP/SLES11-SP4-Updates/sle-11-x86_64] Can't provide file './rpm/x86_64/krb5-client-1.6.3-133.49.112.1.x86_64.rpm' from repository 'GWDG_SP2_Updates'
History:
 - Login failed. (https://repouser@yup.gwdg.de/YUP/SLES11-SP4-Updates/sle-11-x86_64/rpm/x86_64/krb5-client-1.6.3-133.49.112.1.x86_64.rpm): The requested URL returned error: 401
 - Can't provide ./rpm/x86_64/krb5-client-1.6.3-133.49.112.1.x86_64.rpm

Problem occured during or after installation or removal of packages:
Installation aborted by user

Please see the above error message for a hint.
2017-02-23 16:57:02,990 [salt.minion                                                 ][DEBUG   ][3826] Minion return retry timer set to 5 seconds (randomized)
2017-02-23 16:57:02,990 [salt.minion                                                 ][INFO    ][3826] Returning information for job: 20170223165722969629
2017-02-23 16:57:02,991 [salt.transport.zeromq                                       ][DEBUG   ][3826] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'sles.example.com', 'tcp://192.168.0.5:4506', 'aes')
2017-02-23 16:57:02,991 [salt.crypt                                                  ][DEBUG   ][3826] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'sles.example.com', 'tcp://192.168.0.5:4506')
```

salt-minon log after restart salt-minon (when it works):
```
2017-02-23 16:54:08,747 [salt.minion                                            ][INFO    ][3782] User sudo_myuser Executing command pkg.install with jid 20170223165431983548
2017-02-23 16:54:08,748 [salt.minion                                            ][DEBUG   ][3782] Command details {'tgt_type': 'glob', 'jid': '20170223165431983548', 'tgt': 'sles*', 'ret': '', 'user': 'sudo_myuser', 'arg': ['krb5-client'], 'fun': 'pkg.install'}
2017-02-23 16:54:08,763 [salt.minion                                            ][INFO    ][3839] Starting a new job with PID 3839
2017-02-23 16:54:09,394 [salt.utils.lazy                                             ][DEBUG   ][3839] LazyLoaded pkg.install
2017-02-23 16:54:09,397 [salt.utils.lazy                                             ][DEBUG   ][3839] LazyLoaded direct_call.get
2017-02-23 16:54:09,798 [salt.utils.lazy                                             ][DEBUG   ][3839] Could not LazyLoad pkg.normalize_name
2017-02-23 16:54:09,799 [salt.loaded.int.module.cmdmod                               ][INFO    ][3839] Executing command ['rpm', '-qa', '--queryformat', '%{NAME}_|-%{VERSION}_|-%{RELEASE}_|-%|EPOCH?{%{EPOCH}}:{}|\\n'] in directory '/root'
2017-02-23 16:54:11,870 [salt.loaded.int.module.zypper                               ][DEBUG   ][3839] Calling Zypper: zypper --non-interactive --no-refresh --no-refresh install --name --auto-agree-with-licenses krb5-client
2017-02-23 16:54:11,871 [salt.loaded.int.module.cmdmod                               ][INFO    ][3839] Executing command ['zypper', '--non-interactive', '--no-refresh', '--no-refresh', 'install', '--name', '--auto-agree-with-licenses', 'krb5-client'] in directory '/root'
2017-02-23 16:54:13,223 [salt.loaded.int.module.cmdmod                               ][INFO    ][3839] Executing command ['rpm', '-qa', '--queryformat', '%{NAME}_|-%{VERSION}_|-%{RELEASE}_|-%|EPOCH?{%{EPOCH}}:{}|\\n'] in directory '/root'
2017-02-23 16:54:13,866 [salt.minion                                            ][INFO    ][3782] User sudo_myuser Executing command saltutil.find_job with jid 20170223165437102607
2017-02-23 16:54:13,866 [salt.minion                                            ][DEBUG   ][3782] Command details {'tgt_type': 'list', 'jid': '20170223165437102607', 'tgt': ['sles.example.com'], 'ret': '', 'user': 'sudo_myuser', 'arg': ['20170223165431983548'], 'fun': 'saltutil.find_job'}
2017-02-23 16:54:13,885 [salt.minion                                            ][INFO    ][3855] Starting a new job with PID 3855
2017-02-23 16:54:13,903 [salt.utils.lazy                                        ][DEBUG   ][3855] LazyLoaded saltutil.find_job
2017-02-23 16:54:13,905 [salt.utils.lazy                                        ][DEBUG   ][3855] LazyLoaded direct_call.get
2017-02-23 16:54:13,908 [salt.minion                                            ][DEBUG   ][3855] Minion return retry timer set to 7 seconds (randomized)
2017-02-23 16:54:13,909 [salt.minion                                            ][INFO    ][3855] Returning information for job: 20170223165437102607
2017-02-23 16:54:13,910 [salt.transport.zeromq                                  ][DEBUG   ][3855] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'sles.example.com', 'tcp://192.168.0.5:4506', 'aes')
2017-02-23 16:54:13,910 [salt.crypt                                             ][DEBUG   ][3855] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'sles.example.com', 'tcp://192.168.0.5:4506')
2017-02-23 16:54:14,011 [salt.minion                                                 ][DEBUG   ][3839] Minion return retry timer set to 10 seconds (randomized)
2017-02-23 16:54:14,012 [salt.minion                                                 ][INFO    ][3839] Returning information for job: 20170223165431983548
2017-02-23 16:54:14,013 [salt.transport.zeromq                                       ][DEBUG   ][3839] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'sles.example.com', 'tcp://192.168.0.5:4506', 'aes')
2017-02-23 16:54:14,014 [salt.crypt                                                  ][DEBUG   ][3839] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'sles.example.com', 'tcp://192.168.0.5:4506')
```

**Comment by Ralle75** [comment]
i've found some interesting things.
the Login failed is because of the working dir.
after reboot salt-minion execute the command in "/"
```
Executing command ['zypper', '--non-interactive', '--no-refresh', '--no-refresh', 'install', '--name', '--auto-agree-with-licenses', 'krb5-client'] in directory '/'
```

after restart salt-minion service he execute the command in "/root"
```
Executing command ['zypper', '--non-interactive', '--no-refresh', '--no-refresh', 'install', '--name', '--auto-agree-with-licenses', 'krb5-client'] in directory '/root'
```

and the problem is that SLES save the file with passwords for the repository here /root/.zypp/credentials.cat

but why he use first "/" and then "/root" as "working dir"?

**Comment by gtmanfred** [comment]
How are you doing the install of the salt-minion?  I want to make sure I replicate the environment exactly.

Thanks,
Daniel

**Comment by Ralle75** [comment]
i have installed salt-minion version 2016.3.4 as described in official [documentation](https://repo.saltstack.com/#suse) for SLES 11

**Comment by gtmanfred** [comment]
I tested with the service started by the init system, and with the directory that salt was running commands in to be /.

```
[root@salt ~]# salt minion\* cmd.run pwd
minion.c.gtmanfred-1263.internal:
    /
[root@salt ~]# salt minion\* pkg.install krb5-client
minion.c.gtmanfred-1263.internal:
    ----------
    krb5-client:
        ----------
        new:
            1.6.3-133.49.112.1
        old:
[root@salt ~]# salt minion\* service.restart salt-minion
minion.c.gtmanfred-1263.internal:
    True
[root@salt ~]# salt minion\* cmd.run pwd
minion.c.gtmanfred-1263.internal:
    /root
[root@salt ~]# salt minion\* test.versions_report
minion.c.gtmanfred-1263.internal:
    Salt Version:
               Salt: 2016.3.4

    Dependency Versions:
               cffi: 1.6.0
           cherrypy: Not Installed
           dateutil: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.6
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: 0.21.1
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.14
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.6.9 (unknown, Aug  5 2016, 11:15:31)
       python-gnupg: Not Installed
             PyYAML: 3.10
              PyZMQ: 15.2.0
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.4.2
                ZMQ: 4.2.1

    System Versions:
               dist: SuSE 11 x86_64
            machine: x86_64
            release: 3.0.101-91-default
             system: Linux
            version: SUSE Linux Enterprise Server  11 x86_64
```

And it installed, I then restart the salt-minion process, the service.restart module runs `service salt-minion restart` from an interactive shell instead of from the non-interactive shell that the init system on SUSE11 uses, and it moves the home directory to /root.

I am still unfortunately unable to replicate the error you are seeing.

**Comment by Ralle75** [comment]
i think the problem is that we use a repository for install and patch which is locked with user and password. But zypper save the credential file into "/root" folder which is not accessible if the working dir is "/"

**Comment by gtmanfred** [comment]
ahh ok, I forgot about that part.

Yeah, so it doesn't look like the init system for suse 11 has a way to specify where to run the command from.  With a newer init system like systemd, you can set WorkingDirectory=/root in the service unit.

I also tried adding cd /root into the /etc/default/salt, but this didn't fix the problem, and it is still running in `/`.

What i think you can do is have a module state.

```
restart salt-minion:
  module.run:
    - name: service.restart
    - m_name: salt-minion
```

And add this state to run as the startup_states for the minion, this should restart it and have it in the extra directory.  Unfortunately this is just a limit of the init system of Suse 11.

**Comment by Ralle75** [comment]
it seems that is a problem with sles or the init system, but i've the same with check_mk. it runs under xinetd and if i reboot it runs in "/" after restart the xinetd it runs in "/root". so i think we could close this "issue"

**Comment by gtmanfred** [comment]
Thanks!
Daniel
