### ISSUE TITLE
salt.modules.mysql.query  run  error

### ISSUE THREAD

**Issue by ChellsChen** [saltstack/salt#39561]
### Description of Issue/Question
salt.modules.mysql.query  Run an arbitrary SQL query Error
### Setup
```
connection_args = {
    'connection_host': 'localhost',
    'connection_user': 'root',
    'connection_pass': 'passwd',
    'connection_port': 3306,
    'connection_db': 'mysql',
    'connection_charset': 'utf8',
    'connection_default_file': False
}

client = salt.client.LocalClient()
result = client.cmd('192.168.7.151', 'mysql.query', arg=['mysql', 'select user, host from user limit 1'], kwarg=connection_args)
```
I run this code in master, but return this:
```
 {"192.168.7.151": "Passed invalid arguments to mysql.query: 'list' object is not callable\n\n    Run an arbitrary SQL query and return the results or\n    the number of affected rows.\n\n    CLI Example:\n\n    .. code-block:: bash\n\n        salt '*' mysql.query mydb \"UPDATE mytable set myfield=1 limit 1\"\n\n    Return data:\n\n    .. code-block:: python\n\n        {'query time': {'human': '39.0ms', 'raw': '0.03899'}, 'rows affected': 1L}\n\n    CLI Example:\n\n    .. code-block:: bash\n\n        salt '*' mysql.query mydb \"SELECT id,name,cash from users limit 3\"\n\n    Return data:\n\n    .. code-block:: python\n\n        {'columns': ('id', 'name', 'cash'),\n            'query time': {'human': '1.0ms', 'raw': '0.001'},\n            'results': ((1L, 'User 1', Decimal('110.000000')),\n                        (2L, 'User 2', Decimal('215.636756')),\n                        (3L, 'User 3', Decimal('0.040000'))),\n            'rows returned': 3L}\n\n    CLI Example:\n\n    .. code-block:: bash\n\n        salt '*' mysql.query mydb 'INSERT into users values (null,\"user 4\", 5)'\n\n    Return data:\n\n    .. code-block:: python\n\n        {'query time': {'human': '25.6ms', 'raw': '0.02563'}, 'rows affected': 1L}\n\n    CLI Example:\n\n    .. code-block:: bash\n\n        salt '*' mysql.query mydb 'DELETE from users where id = 4 limit 1'\n\n    Return data:\n\n    .. code-block:: python\n\n        {'query time': {'human': '39.0ms', 'raw': '0.03899'}, 'rows affected': 1L}\n\n    Jinja Example: Run a query on ``mydb`` and use row 0, column 0's data.\n\n    .. code-block:: jinja\n\n        {{ salt['mysql.query']('mydb', 'SELECT info from mytable limit 1')['results'][0][0] }}\n    "}
```

salt-minion log  show:
````
2017-02-22 10:29:13,551 [salt.loaded.int.module.mysql                         ][DEBUG   ][21913] Doing query: select user, host from user limit 1
2017-02-22 10:29:13,552 [salt.minion                                          ][WARNING ][21913] Passed invalid arguments to mysql.query: 'list' object is not callable

    Run an arbitrary SQL query and return the results or
    the number of affected rows.

    CLI Example:

    .. code-block:: bash

        salt '*' mysql.query mydb "UPDATE mytable set myfield=1 limit 1"

    Return data:

    .. code-block:: python

        {'query time': {'human': '39.0ms', 'raw': '0.03899'}, 'rows affected': 1L}

    CLI Example:

    .. code-block:: bash

        salt '*' mysql.query mydb "SELECT id,name,cash from users limit 3"

    Return data:

    .. code-block:: python

        {'columns': ('id', 'name', 'cash'),
            'query time': {'human': '1.0ms', 'raw': '0.001'},
            'results': ((1L, 'User 1', Decimal('110.000000')),
                        (2L, 'User 2', Decimal('215.636756')),
                        (3L, 'User 3', Decimal('0.040000'))),
            'rows returned': 3L}

    CLI Example:

    .. code-block:: bash

        salt '*' mysql.query mydb 'INSERT into users values (null,"user 4", 5)'

    Return data:

    .. code-block:: python

        {'query time': {'human': '25.6ms', 'raw': '0.02563'}, 'rows affected': 1L}

    CLI Example:

    .. code-block:: bash

        salt '*' mysql.query mydb 'DELETE from users where id = 4 limit 1'

    Return data:

    .. code-block:: python

        {'query time': {'human': '39.0ms', 'raw': '0.03899'}, 'rows affected': 1L}

    Jinja Example: Run a query on ``mydb`` and use row 0, column 0's data.

    .. code-block:: jinja

        {{ salt['mysql.query']('mydb', 'SELECT info from mytable limit 1')['results'][0][0] }}

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1363, in _thread_return
    return_data = executor.execute()
  File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 28, in execute
    return self.func(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/mysql.py", line 645, in query
    affected = _execute(cur, query)
  File "/usr/lib/python2.7/site-packages/salt/modules/mysql.py", line 544, in _execute
    return cur.execute(qry)
  File "/usr/lib/python2.7/site-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/usr/lib/python2.7/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 835, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 1019, in _read_query_result
    result.read()
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 1309, in read
    self._read_result_packet(first_packet)
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 1372, in _read_result_packet
    self._read_rowdata_packet()
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 1410, in _read_rowdata_packet
    rows.append(self._read_row_from_packet(packet))
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 1429, in _read_row_from_packet
    data = converter(data)
TypeError: 'list' object is not callable
2017-02-22 10:29:13,556 [salt.minion                                          ][DEBUG   ][21913] Minion return retry timer set to 6 seconds (randomized)
````

I read salt.modules.mysql.query  realize，and that's the problem：
![image](https://cloud.githubusercontent.com/assets/10137917/23218166/7c829c5e-f956-11e6-9e50-2ff9e7d97f8e.png)

I do not understand 625-637, if I annotate that , the code can run success, i think the value of dict conv this str, but not list, and there are other purpose？But this problem has caused it。

#### master versions:
Salt Version:
           Salt: 2016.3.0

Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: 2.6.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 14 2016, 13:30:20)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.6

System Versions:
           dist: centos 6.6 Final
        machine: x86_64
        release: 2.6.32-504.el6.x86_64
         system: Linux
        version: CentOS 6.6 Final

#### minion version:
Salt Version:
           Salt: 2016.3.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

**Comment by gtmanfred** [comment]
I am unable to replicate this error.

```
[root@salt ~]# cat this
import salt.client
connection_args = {
    'connection_host': 'localhost',
    'connection_user': 'root',
    'connection_pass': 'passwd',
    'connection_port': 3306,
    'connection_db': 'mysql',
    'connection_charset': 'utf8',
}


client = salt.client.LocalClient()
result = client.cmd('salt.c.gtmanfred-1263.internal', 'mysql.query', arg=['mysql', 'select user, host from user limit 1'], kwarg=connection_args)
print result
[root@salt ~]# python this
{'salt.c.gtmanfred-1263.internal': {'rows returned': 1, 'query time': {'raw': '0.00043', 'human': '0.4ms'}, 'columns': ['user', 'host'], 'results': [['root', '127.0.0.1']]}}
```

With the connection_default_file: False, i get a different error.

**Comment by ChellsChen** [comment]
The error still appears：
````
[admin@10-57-17-33 xiaoxue.chen]$ cat this.py
import salt.client
connection_args = {
    'connection_host': 'localhost',
    'connection_user': 'root',
    'connection_pass': 'Tongdun@321',
    'connection_port': 3306,
    'connection_db': 'mysql',
    'connection_charset': 'utf8',
}

client = salt.client.LocalClient()
result = client.cmd('192.168.7.151', 'mysql.query', arg=['mysql', 'select user, host from user limit 1'], kwarg=connection_args)
print result
[admin@10-57-17-33 xiaoxue.chen]$
[admin@10-57-17-33 xiaoxue.chen]$ sudo python this.py
{'192.168.7.151': 'Passed invalid arguments to mysql.query: \'list\' object is not callable\n\n    Run an arbitrary SQL query and return the results or\n    the number of affected rows.\n\n    CLI Example:\n\n    .. code-block:: bash\n\n        salt \'*\' mysql.query mydb "UPDATE mytable set myfield=1 limit 1"\n\n    Return data:\n\n    .. code-block:: python\n\n        {\'query time\': {\'human\': \'39.0ms\', \'raw\': \'0.03899\'}, \'rows affected\': 1L}\n\n    CLI Example:\n\n    .. code-block:: bash\n\n        salt \'*\' mysql.query mydb "SELECT id,name,cash from users limit 3"\n\n    Return data:\n\n    .. code-block:: python\n\n        {\'columns\': (\'id\', \'name\', \'cash\'),\n            \'query time\': {\'human\': \'1.0ms\', \'raw\': \'0.001\'},\n            \'results\': ((1L, \'User 1\', Decimal(\'110.000000\')),\n                        (2L, \'User 2\', Decimal(\'215.636756\')),\n                        (3L, \'User 3\', Decimal(\'0.040000\'))),\n            \'rows returned\': 3L}\n\n    CLI Example:\n\n    .. code-block:: bash\n\n        salt \'*\' mysql.query mydb \'INSERT into users values (null,"user 4", 5)\'\n\n    Return data:\n\n    .. code-block:: python\n\n        {\'query time\': {\'human\': \'25.6ms\', \'raw\': \'0.02563\'}, \'rows affected\': 1L}\n\n    CLI Example:\n\n    .. code-block:: bash\n\n        salt \'*\' mysql.query mydb \'DELETE from users where id = 4 limit 1\'\n\n    Return data:\n\n    .. code-block:: python\n\n        {\'query time\': {\'human\': \'39.0ms\', \'raw\': \'0.03899\'}, \'rows affected\': 1L}\n\n    Jinja Example: Run a query on ``mydb`` and use row 0, column 0\'s data.\n\n    .. code-block:: jinja\n\n        {{ salt[\'mysql.query\'](\'mydb\', \'SELECT info from mytable limit 1\')[\'results\'][0][0] }}\n    '}
[admin@10-57-17-33 xiaoxue.chen]$
````
I use pymysql as mysql dependencies.

**Comment by gtmanfred** [comment]
I am using MySQL-python, can you try that and I will try pymysql tomorrow

**Comment by UtahDave** [comment]
The Salt mysql module depends on MySQLdb

https://github.com/saltstack/salt/blob/24052c1378e321f18715fe66dccc9c525cdc2f1b/salt/modules/mysql.py#L5

**Comment by gtmanfred** [comment]
Pymysql actually provides a mysql-python (which is MySQLdb) compatibility
library, so it should work the same way

**Comment by ChellsChen** [comment]
It can run normally in MySQLdb， but it thrown error when using PyMySQL (0.7.9)

**Comment by gtmanfred** [comment]
I have confirmed this issue with pymysql, we will get it fixed.

Thanks for reporting
Daniel

**Comment by shyamkhakhar9** [comment]
I tried the same thing and it works but in my case the table I'm querying has Japanese characters so it doesn't show properly. It shows like \u7d00\u4f0a\u570b\u5c4b\u66f8\u5e97\u96fb\u5b50\u30d6\u30c3\u30af

How can I get Japanese characters properly. Can anyone help?
