### ISSUE TITLE
Stack Trace Errors during attempt to load modules

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#39566]
### Description of Issue/Question
If I only have python-boto3 installed and NOT python-boto installed, When trying to run this state:

```
Ensure mylc exists:
  boto_lc.present:
    - name: mylc
    - image_id: ami-0b9c9f62
    - key_name: mykey
    - security_groups:
        - mygroup
    - instance_type: m1.small
    - instance_monitoring: true
    - block_device_mappings:
        - '/dev/sda1':
            size: 20
            volume_type: 'io1'
            iops: 220
            delete_on_termination: true
    - cloud_init:
        boothooks:
          'disable-master.sh': |
            #!/bin/bash
            echo "manual" > /etc/init/salt-master.override
        scripts:
          'run_salt.sh': |
            #!/bin/bash

            add-apt-repository -y ppa:saltstack/salt
            apt-get update
            apt-get install -y salt-minion
            salt-call state.highstate
    - region: us-east-1
    - keyid: GKTADJGHEIQSXMKKRBJ08H
    - key: askdjghsdfjkghWupUjasdflkdfklgjsdfjajkghs
```

`salt-call --local state.apply test -ldebug` I get the following import errors:

```
[DEBUG   ] Failed to import utils psutil_compat:
Traceback (most recent call last):
  File "/testing/salt/loader.py", line 1332, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/testing/salt/utils/psutil_compat.py", line 20, in <module>
    import psutil
ImportError: No module named psutil
[DEBUG   ] Failed to import utils mako:
Traceback (most recent call last):
  File "/testing/salt/loader.py", line 1332, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/testing/salt/utils/mako.py", line 12, in <module>
    from mako.lookup import TemplateCollection, TemplateLookup  # pylint: disable=import-error
  File "/testing/salt/utils/mako.py", line 12, in <module>
    from mako.lookup import TemplateCollection, TemplateLookup  # pylint: disable=import-error
ImportError: No module named lookup
[DEBUG   ] Failed to import utils raetlane:
Traceback (most recent call last):
  File "/testing/salt/loader.py", line 1332, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/testing/salt/utils/raetlane.py", line 62, in <module>
    from raet import raeting, nacling
ImportError: No module named raet
[DEBUG   ] Failed to import utils raetevent:
Traceback (most recent call last):
  File "/testing/salt/loader.py", line 1332, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/testing/salt/utils/raetevent.py", line 23, in <module>
    from raet import raeting, nacling
ImportError: No module named raet
[ERROR   ] Failed to import utils saltminionservice, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/testing/salt/loader.py", line 1332, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/testing/salt/utils/saltminionservice.py", line 34, in <module>
    class MinionService(service(False)):
TypeError: Error when calling the metaclass bases
    cannot create 'NoneType' instances
```

if I install `python-boto` then I do not see these errors.

NOTE: both `python-boto` and `python-boto3` are required for this module so this is a unique side case

### Setup
1. install `python-boto3`
2. Add the state above to file_roots

### Steps to Reproduce Issue
1. `salt-call --local state.apply test -ldebug`

### Versions Report

```
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.0.1406 Core
        machine: x86_64
        release: 3.10.0-123.6.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.0.1406 Core
```

Will be including a docker container here in a sec.

**Comment by Ch3LL** [comment]
Here is a docker container to help replicate the issue:

1. `docker run -it -v /home/ch3ll/git/salt/:/testing ch3ll/issues:39566` ( where /home/ch3ll/git/salt/ is a local cloned git repo of salt)
2. `salt-call --local state.sls test -ldebug`
