### ISSUE TITLE
Jinja error whe assigning a variable inside a loop

### ISSUE THREAD

**Issue by Da-Juan** [saltstack/salt#39635]
### Description of Issue/Question

This issue is not directly related to Salt's code, I open it to keep you informed and keep track of the evolutions.

Since Jinja 2.9 if you assign a variable inside a loop, it will not be accessible on the loop next iteration.

There's an issue opened on Jinja's Github here https://github.com/pallets/jinja/issues/64
Jinja developers say it was never supposed to work like this, they've implemented `loop.previtem/loop.nextitem` in the next 2.9.6 version (https://github.com/ThiefMaster/jinja2/commit/f7f8d511377a9f62d44d7c816be482a5baf2ad55) that will solve the example below.

### Setup
This example is a simplified version of my state but it demonstrates the problem.
```
/srv/files:
  file.directory

{% for file in salt['pillar.get']('test_files') %}
/srv/files/{{ file }}:
  file.managed:
    - source: salt://files/{{ file }}
    - require:
      {% if loop.first %}
      - file: /srv/files
      {% else %}
      - file: /srv/files/{{ prev_file }}
      {% endif %}

{% set prev_file = file %}
{% endfor %}
```
### Steps to Reproduce Issue
To render the previous template, create a pillar `test_files` that contains a list of strings and run `salt-call cp.get_template salt://test_loop.sls /dev/stdout`

```
[ERROR   ] Rendering exception occurred: Jinja variable 'prev_file' is undefined
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
SaltRenderError: Jinja variable 'prev_file' is undefined
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 379, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/cp.py", line 261, in get_template
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 676, in get_template
    **kwargs
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 178, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 386, in render_jinja_tmpl
    buf=tmplstr)
SaltRenderError: Jinja variable 'prev_file' is undefined
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 379, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/cp.py", line 261, in get_template
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 676, in get_template
    **kwargs
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 178, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 386, in render_jinja_tmpl
    buf=tmplstr)
salt.exceptions.SaltRenderError: Jinja variable 'prev_file' is undefined
```

### Versions Report
 ```
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: 3.5.0
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.7 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.7 
```

**Comment by gtmanfred** [comment]
Thanks for reporting this, can you close the issue when the upstream bug gets fixed?

Thanks,
Daniel

**Comment by mirceaulinic** [comment]
Yes, in general a variable is not available outside of it's scope. Inside a loop each iteration has its own context so you will not find a variable from a previous loop.

For your problem and many others, you can put the content you need inside a dict, which you can update:

```jinja
{%- set prev_file = {} -%}
{% for file in salt['pillar.get']('test_files') %}
/srv/files/{{ file }}:
  file.managed:
    - source: salt://files/{{ file }}
    - require:
      {% if loop.first %}
      - file: /srv/files
      {% else %}
      - file: /srv/files/{{ prev_file.name }}
      {% endif %}

{%- do prev_file.update({'name': file}) -%}
{% endfor %}
```

Does this help?

**Comment by Da-Juan** [comment]
Thanks @mirceaulinic that's what I needed!

**Comment by gtmanfred** [comment]
I am going to close this since there is a work around established.

Thanks @mirceaulinic
