### ISSUE TITLE
Add support for salt-minion to upgrade itself

### ISSUE THREAD

**Issue by curiositycasualty** [saltstack/salt#39652]
### Description of Issue/Question
If a set of states upgrades salt-related packages mid-run, the run will fail.

### Versions Report
Still and issue as of 2016.11.2

Ideally, salt will gracefully complete its run regardless of its package has been upgraded out form underneath it or not. This is a solved problem in Chef: https://github.com/chef-cookbooks/omnibus_updater/blob/master/recipes/installer.rb

**Comment by Ch3LL** [comment]
Are you refering to the issue were when attempting to upgrade salt-minion and it returns a message stating the miniond did not return due to the upgrade? Or are you actually returning a failure message and if so can you share a test case?

**Comment by gtmanfred** [comment]
We depend on the init system here.  If the initsystem can handle restarting the service without killing off the salt process, then everything works.

Using systemd and going from 2016.3 -> 2016.11 works, because we do the pkg commands in a separate scope, so the salt-minion process doesn't send a sigkill to the parent process that the salt-minion is running the highstate/state through.

The problem that we run into is not really salt specific.  I am not sure how chef handles this, but to correctly handle packages, rpm and deb say that the service should be restarted when it is updated.  With other init systems like upstart and sysvinit, this means sending a sigterm and then e sigkill to the parent process, and kills off the entire tree.

With systemd when we run the pkg.install in a seperate scope, this shouldn't kill off the salt-minion process that is running the highstate, by default it just does a sigterm on the parent which should allow the salt-minion process running the highstate to finish.

Can you provide the output of --versions-report, like the issue template requested, so that we can know more about your environment, and possibly be able to replicate this?

Thanks,
Daniel

**Comment by curiositycasualty** [comment]
Let me grab and sanitize some logs for you.

Can you elaborate more on what isolating the salt-minion process looks like using systemd?

My problem wasn't a service system killing off the salt-minion process, it was the salt-minion successfully upgrading the `salt-minion` package within a state, and then failing with a stacktrace on subsequent calls where the internal API of Salt changed between versions.

Although I realize that the stack itself is cosmetic-relating to the outputter, it does end the salt-call run, which is impactful.

```bash
sudo salt-call  --versions-report;
echo "deb https://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/ trusty main" | sudo tee /etc/apt/sources.list.d/ugh.list;
sudo apt-get update;
sudo apt-cache policy salt-minion;
mkdir -v -p /tmp/eg; echo -e "exempli_gratia:\n  pkg.installed:\n    - name: salt-minion\n    - refresh: true\n    - version: 2016.11.3+ds-1" | tee /tmp/eg/init.sls;
sudo salt-call --local state.sls eg --file-root=/tmp/;
sudo salt-call  --versions-report;
```

```
Welcome to Ubuntu 14.04.5 LTS (GNU/Linux 4.4.0-31-generic x86_64)

 * Documentation:  https://help.ubuntu.com/
Last login: Tue Mar 28 12:29:18 2017 from 10.0.2.2
vagrant@<hostname>:~$
vagrant@<hostname>:~$ sudo salt-call  --versions-report;
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.4.0-31-generic
         system: Linux
        version: Ubuntu 14.04 trusty

vagrant@<hostname>:~$ echo "deb https://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/ trusty main" | sudo tee /etc/apt/sources.list.d/ugh.list;
deb https://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/ trusty main
vagrant@<hostname>:~$ sudo apt-get update;
Hit http://<uri> trusty InRelease
Hit http://<uri> trusty-updates InRelease
Ign http://<uri> trusty InRelease
Hit http://<uri> trusty-security InRelease
Hit http://<uri> trusty/main amd64 Packages
Hit http://<uri> trusty/main i386 Packages
Hit http://<uri> trusty-updates/main Sources
Hit http://<uri> trusty-updates/multiverse Sources
Hit http://<uri> trusty-updates/restricted Sources
Hit https://repo.saltstack.com trusty InRelease
Hit http://<uri> trusty-updates/universe Sources
Hit https://repo.saltstack.com trusty/main amd64 Packages
Hit http://<uri> trusty-updates/main amd64 Packages
Hit http://<uri> trusty-updates/multiverse amd64 Packages
Hit https://repo.saltstack.com trusty/main i386 Packages
Hit http://<uri> trusty-updates/restricted amd64 Packages
Get:1 https://repo.saltstack.com trusty/main Translation-en_US
Hit http://<uri> trusty-updates/universe amd64 Packages
Hit http://<uri> trusty-updates/main i386 Packages
Hit http://<uri> trusty-updates/multiverse i386 Packages
Hit http://<uri> trusty-updates/restricted i386 Packages
Hit http://<uri> trusty-updates/universe i386 Packages
Hit http://<uri> trusty-updates/main Translation-en
Hit http://<uri> trusty-updates/multiverse Translation-en
Hit http://<uri> trusty-updates/restricted Translation-en
Ign https://repo.saltstack.com trusty/main Translation-en_US
Hit http://<uri> trusty-updates/universe Translation-en
Ign https://repo.saltstack.com trusty/main Translation-en
Hit http://<uri> trusty Release.gpg
Hit http://<uri> trusty-security/main Sources
Hit http://<uri> trusty-security/multiverse Sources
Hit http://<uri> trusty-security/restricted Sources
Hit http://<uri> trusty-security/universe Sources
Hit http://<uri> trusty-security/main amd64 Packages
Hit http://<uri> trusty-security/multiverse amd64 Packages
Hit http://<uri> trusty-security/restricted amd64 Packages
Hit http://<uri> trusty-security/universe amd64 Packages
Hit http://<uri> trusty-security/main i386 Packages
Hit http://<uri> trusty-security/multiverse i386 Packages
Hit http://<uri> trusty-security/restricted i386 Packages
Hit http://<uri> trusty-security/universe i386 Packages
Hit http://<uri> trusty-security/main Translation-en
Hit http://<uri> trusty-security/multiverse Translation-en
Hit http://<uri> trusty-security/restricted Translation-en
Hit http://<uri> trusty-security/universe Translation-en
Hit http://<uri> trusty Release
Hit http://<uri> trusty/main Sources
Hit http://<uri> trusty/multiverse Sources
Hit http://<uri> trusty/restricted Sources
Hit http://<uri> trusty/universe Sources
Hit http://<uri> trusty/main amd64 Packages
Hit http://<uri> trusty/multiverse amd64 Packages
Hit http://<uri> trusty/restricted amd64 Packages
Hit http://<uri> trusty/universe amd64 Packages
Hit http://<uri> trusty/main i386 Packages
Hit http://<uri> trusty/multiverse i386 Packages
Hit http://<uri> trusty/restricted i386 Packages
Hit http://<uri> trusty/universe i386 Packages
Hit http://<uri> trusty/main Translation-en
Hit http://<uri> trusty/multiverse Translation-en
Hit http://<uri> trusty/restricted Translation-en
Hit http://<uri> trusty/universe Translation-en
Ign http://<uri> trusty/main Translation-en_US
Ign http://<uri> trusty/main Translation-en
Ign http://<uri> trusty/main Translation-en_US
Ign http://<uri> trusty/multiverse Translation-en_US
Ign http://<uri> trusty/restricted Translation-en_US
Ign http://<uri> trusty/universe Translation-en_US
Reading package lists... Done
vagrant@<hostname>:~$ sudo apt-cache policy salt-minion;
salt-minion:
  Installed: 2016.3.1+ds-1
  Candidate: 2016.11.3+ds-1
  Version table:
     2016.11.3+ds-1 0
        500 https://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/ trusty/main amd64 Packages
 *** 2016.3.1+ds-1 0
        500 http://<uri>/v1/packages/mirrors/daily-update/debian/repo.saltstack.com/apt/ubuntu/14.04/amd64/archive/2016.3.1/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
     0.17.5+ds-1 0
        500 http://<uri>/v1/packages/mirrors/daily-update/debian/archive.ubuntu.com/ubuntu/ trusty/universe amd64 Packages
vagrant@<hostname>:~$ mkdir -v -p /tmp/eg; echo -e "exempli_gratia:\n  pkg.installed:\n    - name: salt-minion\n    - refresh: true\n    - version: 2016.11.3+ds-1" | tee /tmp/eg/init.sls;
mkdir: created directory ‘/tmp/eg’
exempli_gratia:
  pkg.installed:
    - name: salt-minion
    - refresh: true
    - version: 2016.11.3+ds-1
vagrant@<hostname>:~$ sudo salt-call --local state.sls eg --file-root=/tmp/;
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: out_format() got an unexpected keyword argument 'nested_indent'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 345, in salt_call
    def salt_key():
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 149, in run
    self.opts)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 86, in display_output
    '''
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 39, in try_printout
    if printout is not None:
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 146, in output
    for host, hostdata in six.iteritems(data)
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 225, in _format_host
    schanged, ctext = _format_changes(ret['changes'], orchestration)
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 525, in _format_changes
    ctext = _nested_changes(changes)
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 497, in _nested_changes
    nested_indent=14)
TypeError: out_format() got an unexpected keyword argument 'nested_indent'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 345, in salt_call
    def salt_key():
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 149, in run
    self.opts)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 86, in display_output
    '''
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 39, in try_printout
    if printout is not None:
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 146, in output
    for host, hostdata in six.iteritems(data)
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 225, in _format_host
    schanged, ctext = _format_changes(ret['changes'], orchestration)
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 525, in _format_changes
    ctext = _nested_changes(changes)
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 497, in _nested_changes
    nested_indent=14)
TypeError: out_format() got an unexpected keyword argument 'nested_indent'
```

**Comment by gtmanfred** [comment]
This is usually something that we test.  This one might have slipped through on 2016.3.1, but i wonder if it happens on later 2016.3 releases.

It is also worth noting that the state does finish running, this only errors out when it tries to return to the commandline at the very end.  And is only an error when using masterless minions.

```
wget -O - https://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/SALTSTACK-GPG-KEY.pub | sudo apt-key add -
echo "deb https://repo.saltstack.com/apt/ubuntu/14.04/amd64/archive/2016.3.1 trusty main" | sudo tee /etc/apt/sources.list.d/saltstack.list;
apt-get update
apt-get upgrade -y
apt-get install salt-minion -y
hash -r
salt-call  --versions-report
echo "deb https://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/ trusty main" | sudo tee /etc/apt/sources.list.d/saltstack.list
apt-get update
apt-cache policy salt-minion
mkdir -v -p /tmp/eg
cat > /tmp/eg/init.sls <<HERE
/tmp/test1:
  file.touch

exempli_gratia:
  pkg.installed:
    - name: salt-minion
    - refresh: true
    - version: 2016.11.3+ds-1

/tmp/test2:
  file.touch
HERE
salt-call --local state.sls eg --file-root=/tmp/
find /usr/lib/python2.7/dist-packages/salt/ -name \*.pyc -delete
salt-call  --versions-report
```

This will show the /tmp/test1 and /tmp/test2 files exist, one run before the upgrade, and one afterwards.

**Comment by curiositycasualty** [comment]
```
Welcome to Ubuntu 14.04.5 LTS (GNU/Linux 4.4.0-31-generic x86_64)

 * Documentation:  https://help.ubuntu.com/
Last login: Tue Mar 28 13:33:36 2017 from 10.0.2.2
vagrant@<hostname>:~$
vagrant@<hostname>:~$ sudo salt-call  --versions-report;
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.4.0-31-generic
         system: Linux
        version: Ubuntu 14.04 trusty

vagrant@<hostname>:~$ echo "deb https://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/ trusty main" | sudo tee /etc/apt/sources.list.d/ugh.list;
deb https://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/ trusty main
vagrant@<hostname>:~$ sudo apt-get update;
<snip>
Get:3 https://repo.saltstack.com trusty InRelease
Get:4 https://repo.saltstack.com trusty/main amd64 Packages
Get:5 https://repo.saltstack.com trusty/main i386 Packages
<snip>
Fetched 6,303 kB in 20s (314 kB/s)
Reading package lists... Done
vagrant@<hostname>:~$ sudo apt-cache policy salt-minion;
salt-minion:
  Installed: 2016.3.1+ds-1
  Candidate: 2016.11.3+ds-1
  Version table:
     2016.11.3+ds-1 0
        500 https://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/ trusty/main amd64 Packages
 *** 2016.3.1+ds-1 0
        500 http://<uri>/v1/packages/mirrors/daily-update/debian/repo.saltstack.com/apt/ubuntu/14.04/amd64/archive/2016.3.1/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
     0.17.5+ds-1 0
        500 http://<uri>/v1/packages/mirrors/daily-update/debian/archive.ubuntu.com/ubuntu/ trusty/universe amd64 Packages
vagrant@<hostname>:~$ mkdir -v -p /tmp/eg /tmp/ie;
mkdir: created directory ‘/tmp/eg’
mkdir: created directory ‘/tmp/ie’
vagrant@<hostname>:~$ rm -fv /tmp/id_est_file;
vagrant@<hostname>:~$ echo -e "base:\n  '*':\n    - eg\n    - ie" | tee /tmp/top.sls;
base:
  '*':
    - eg
    - ie
vagrant@<hostname>:~$ echo -e "exempli_gratia:\n  pkg.installed:\n    - name: salt-minion\n    - refresh: true\n    - version: 2016.11.3+ds-1" | tee /tmp/eg/init.sls;
exempli_gratia:
  pkg.installed:
    - name: salt-minion
    - refresh: true
    - version: 2016.11.3+ds-1
vagrant@<hostname>:~$ echo -e "id_est:\n  file.managed:\n    - name: /tmp/id_est_file\n    - contents: words" | tee /tmp/ie/init.sls;
id_est:
  file.managed:
    - name: /tmp/id_est_file
    - contents: words
vagrant@<hostname>:~$ sudo salt-call --local state.highstate --file-root=/tmp/;
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1723, in call
    # format_call.
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1650, in wrapper
    '__virtual__() function is returning \'{2}\'. These '
  File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 1583, in managed
    mode = salt.utils.normalize_mode(mode)
AttributeError: 'module' object has no attribute 'normalize_mode'

[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: out_format() got an unexpected keyword argument 'nested_indent'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 345, in salt_call
    def salt_key():
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 149, in run
    self.opts)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 86, in display_output
    '''
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 39, in try_printout
    if printout is not None:
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 146, in output
    for host, hostdata in six.iteritems(data)
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 225, in _format_host
    schanged, ctext = _format_changes(ret['changes'], orchestration)
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 525, in _format_changes
    ctext = _nested_changes(changes)
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 497, in _nested_changes
    nested_indent=14)
TypeError: out_format() got an unexpected keyword argument 'nested_indent'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 345, in salt_call
    def salt_key():
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 149, in run
    self.opts)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 86, in display_output
    '''
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 39, in try_printout
    if printout is not None:
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 146, in output
    for host, hostdata in six.iteritems(data)
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 225, in _format_host
    schanged, ctext = _format_changes(ret['changes'], orchestration)
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 525, in _format_changes
    ctext = _nested_changes(changes)
  File "/usr/lib/python2.7/dist-packages/salt/output/highstate.py", line 497, in _nested_changes
    nested_indent=14)
TypeError: out_format() got an unexpected keyword argument 'nested_indent'
vagrant@<hostname>:~$ file /tmp/id_est_file
/tmp/id_est_file: ERROR: cannot open `/tmp/id_est_file' (No such file or directory)
vagrant@<hostname>:~$ sudo salt-call  --versions-report;
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.4.0-31-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by curiositycasualty** [comment]
Not sure why this went quiet.
Is there any news on this?

**Comment by gtmanfred** [comment]
There is not.  I will say that the best course of action is to probably upgrade the salt minion separately from other salt states.
