### ISSUE TITLE
Custom module cannot be imported into the custom state even it was loaded and works?

### ISSUE THREAD

**Issue by quantonganh** [saltstack/salt#39678]
Continue from #39677.

### Setup

I added the `_alias_function` directly into `_modules/dockerng.py` file, then replace `salt.utils.alias_function` with `_alias_function`.

`sync_modules`, then re-run `dockerng.pull hello-world` and it works:

```
local:
    ----------
    Status:
        Image is up to date for hello-world:latest
    Time_Elapsed:
        5.41497302055
```

Now I create a simple sls file:

```
include:
  - docker

docker_hello:
  dockerng:
    - image_present
    - name: library/hello-world
    - require:
      - pip: docker
      - service: docker
```

Run this:

```
----------
          ID: docker_hello
    Function: dockerng.image_present
        Name: library/hello-world
      Result: False
     Comment: State 'dockerng.image_present' found in SLS u'docker.hello' is unavailable
     Started:
    Duration:
     Changes:
```

and I saw the bellow log:

```
2017-02-27 05:45:21,056 [salt.loader      ][DEBUG   ] Failed to import states dockerng, this is most likely NOT a problem:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 932, in load_modules
    ), fn_, path, desc
  File "/var/cache/salt/minion/extmods/states/dockerng.py", line 49, in <module>
    from salt.modules.dockerng import (
ImportError: No module named dockerng
```

Why?

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report

```
                  Salt: 2014.7.5
                Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.12
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
 Debian source package: 2014.7.5+ds-1ubuntu1
```

**Comment by gtmanfred** [comment]
You do not need to import the module.

It should be available in the `__salt__` object.  And this is loaded by the `_module_dirs` function.
