### ISSUE TITLE
Can I override "utils/__init__.py"?

### ISSUE THREAD

**Issue by quantonganh** [saltstack/salt#39677]
### Setup

`dockerio` module doesn't work:

```
local:
    ----------
    comment:
        We did not get any expected answer from docker
    id:
        hello-world
    out:
        Traceback (most recent call last):
          File "/usr/lib/python2.7/dist-packages/salt/modules/dockerio.py", line 1584, in pull
            ret = client.pull(repo, tag=tag)
          File "/usr/local/lib/python2.7/dist-packages/docker/api/image.py", line 175, in pull
            self._raise_for_status(response)
          File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 174, in _raise_for_status
            raise errors.APIError(e, response, explanation=explanation)
        APIError: 500 Server Error: Internal Server Error ("{"message":"Get https://registry-1.docker.io/v2/library/hello-world/tags/list: Get https://auth.docker.io/token?scope=repository%3Alibrary%2Fhello-world%3Apull\u0026service=registry.docker.io: net/http: TLS handshake timeout"}")
    status:
        False
```

So, I'm trying the `dockerng` module from 2015.8 by copying both the execution and state module into `_modules` and `_states`.

First trying:

```
[WARNING ] Failed to import module dockerng, this is due most likely to a syntax error. Traceback raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 932, in load_modules
    ), fn_, path, desc
  File "/var/cache/salt/minion/extmods/modules/dockerng.py", line 3116, in <module>
    cp = salt.utils.alias_function(copy_from, 'cp')
AttributeError: 'module' object has no attribute 'alias_function'
```

So I created the `_utils` folder, copy `__init__.py` file from 2014.7 and add `alias_function` into that file.

`saltutil.sync_utils`:

```
local:
    - utils.__init__
root@td:~# ls /var/cache/salt/minion/extmods/utils/
__init__.py
```

Re-run `salt-call -l debug dockerng.pull hello-world` but still got:

```
[WARNING ] Failed to import module dockerng, this is due most likely to a syntax error. Traceback raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 932, in load_modules
    ), fn_, path, desc
  File "/var/cache/salt/minion/extmods/modules/dockerng.py", line 3116, in <module>
    cp = salt.utils.alias_function(copy_from, 'cp')
AttributeError: 'module' object has no attribute 'alias_function'
```

Question: May I override `utils/__init__.py` like that?

### Steps to Reproduce Issue
- install 2014.7.5
- copy execution/state `dockerng` module from 2015.8
- add `alias_function` into `_utils/__init__.py` file
- run `salt-call -l debug dockerng.pull hello-world`

### Versions Report

```
                  Salt: 2014.7.5
                Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.12
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
 Debian source package: 2014.7.5+ds-1ubuntu1
```

**Comment by mirceaulinic** [comment]
The utils extension modules are accessible through the `__utils__` dunder, i.e.: `__utils__['alias_function'](copy_from, 'cp')`, while `salt.utils.*` is useful for native modules only.
Can you try the above in your execution module and confirm?

**Comment by gtmanfred** [comment]
@quantonganh does this fix your issue?

Thanks,
Daniel
