### ISSUE TITLE
virtualenv state module error with requirements ~=

### ISSUE THREAD

**Issue by jskyn** [saltstack/salt#39697]
### Description of Issue/Question
When using the virtualenv state module in an sls file to install requirements from a file it seems to be bombing when the version is specified ~=

I can run this from pip directly with no problem.

/opt/myapp/.virtualenv/pipe-outgoing/bin/pip run on Mon Feb 27 21:42:01 2017
Exception:
Traceback (most recent call last):
  File "/opt/myapp/.virtualenv/pipe-outgoing/lib/python2.7/site-packages/pip/basecommand.py", line 134, in main
    status = self.run(options, args)
  File "/opt/myapp/.virtualenv/pipe-outgoing/lib/python2.7/site-packages/pip/commands/install.py", line 220, in run
    for req in parse_requirements(filename, finder=finder, options=options):
  File "/opt/myapp/.virtualenv/pipe-outgoing/lib/python2.7/site-packages/pip/req.py", line 1477, in parse_requirements
    req = InstallRequirement.from_line(line, comes_from, prereleases=getattr(options, "pre", None))
  File "/opt/myapp/.virtualenv/pipe-outgoing/lib/python2.7/site-packages/pip/req.py", line 129, in from_line
    return cls(req, comes_from, url=url, prereleases=prereleases)
  File "/opt/myapp/.virtualenv/pipe-outgoing/lib/python2.7/site-packages/pip/req.py", line 44, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/opt/myapp/.virtualenv/pipe-outgoing/lib/python2.7/site-packages/pkg_resources.py", line 2914, in parse
    reqs = list(parse_requirements(s))
  File "/opt/myapp/.virtualenv/pipe-outgoing/lib/python2.7/site-packages/pkg_resources.py", line 2839, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/opt/myapp/.virtualenv/pipe-outgoing/lib/python2.7/site-packages/pkg_resources.py", line 2807, in scan_list
    raise ValueError("Expected "+item_name+" in",line,"at",line[p:])
ValueError: ('Expected version spec in', 'mypackage~=1.18', 'at', '~=1.18')

### Setup
This is the state in question...

/opt/myapp/.virtualenv/asubfolder:
  virtualenv.managed:
    - requirements: /opt/myapp/asubfolder/requirements.txt
    - pip_upgrade: True
    - cwd: /opt/myap/asubfolder

### Steps to Reproduce Issue
an sls file with the above state, and a requirments file that has something like: apackage~=x.xx

### Versions Report
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: 1.2.1
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.6.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by jskyn** [comment]
Was a bug on my end in the virtual env itself.
