### ISSUE TITLE
Latest develop fails to start - can't provide --versions-report either ...

### ISSUE THREAD

**Issue by tkwilliams** [saltstack/salt#39772]
Just pulled develop a few minutes ago - hash is
```
  remotes/upstream/develop                                       1926e90 Merge pull request #39648 from twangboy/win_fix_loader_tests
```
```
root@inf-dev-salt-aue1-01# /etc/init.d/salt-master start ; /etc/init.d/salt-minion start
Starting salt-master daemon: Traceback (most recent call last):
  File "/usr/bin/salt-master", line 22, in <module>
    salt_master()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 90, in salt_master
    import salt.cli.daemons
  File "/usr/lib/python2.7/site-packages/salt/cli/daemons.py", line 43, in <module>
    from salt.utils import migrations
  File "/usr/lib/python2.7/site-packages/salt/utils/migrations.py", line 12, in <module>
    import salt.syspaths as syspaths
  File "/usr/lib/python2.7/site-packages/salt/syspaths.py", line 78, in <module>
    SHARE_DIR = __generated_syspaths.SHARE_DIR
AttributeError: 'module' object has no attribute 'SHARE_DIR'
                                                           [FAILED]
Starting salt-minion daemon: Traceback (most recent call last):
  File "/usr/bin/salt-minion", line 26, in <module>
    salt_minion()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 161, in salt_minion
    import salt.cli.daemons
  File "/usr/lib/python2.7/site-packages/salt/cli/daemons.py", line 43, in <module>
    from salt.utils import migrations
  File "/usr/lib/python2.7/site-packages/salt/utils/migrations.py", line 12, in <module>
    import salt.syspaths as syspaths
  File "/usr/lib/python2.7/site-packages/salt/syspaths.py", line 78, in <module>
    SHARE_DIR = __generated_syspaths.SHARE_DIR
AttributeError: 'module' object has no attribute 'SHARE_DIR'
                                                           [FAILED]
root@inf-dev-salt-aue1-01# salt --versions-report
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 471, in salt_main
    import salt.cli.salt
  File "/usr/lib/python2.7/site-packages/salt/cli/salt.py", line 11, in <module>
    from salt.utils import parsers, print_cli
  File "/usr/lib/python2.7/site-packages/salt/utils/parsers.py", line 28, in <module>
    import salt.config as config
  File "/usr/lib/python2.7/site-packages/salt/config/__init__.py", line 38, in <module>
    import salt.syspaths
  File "/usr/lib/python2.7/site-packages/salt/syspaths.py", line 78, in <module>
    SHARE_DIR = __generated_syspaths.SHARE_DIR
AttributeError: 'module' object has no attribute 'SHARE_DIR'
```

**Comment by tkwilliams** [comment]
@cachedout @terminalmage  Any thoughts - at the moment salt it completely useless to me.  I've had to roll my master back to an earlier develop RPM I had laying around, but as with things in this state I can't do any devel at all :(

**Comment by tkwilliams** [comment]
Sorry, just saw the patch :)  Thanks!

**Comment by cachedout** [comment]
@tkwilliams Sorry about that! Sometimes the develop branch is a bumpy ride. Thanks for understanding. :]
