### ISSUE TITLE
Salt sometimes doesn't fail when pillar rendering is broken

### ISSUE THREAD

**Issue by bobrik** [saltstack/salt#39793]
### Description of Issue/Question

Salt ignores pillar rendering issues and happily runs states, potentially breaking the system (missing resolver) or making it insecure (missing iptables data).

### Setup

Salt master has the following `top.sls`:

```yaml
base:
  '*':
    - foo
```

Initially `pillar/foo.sls` has:

```
foo: bar
```

Then on minion I can get the pillar value:

```
root@minion:/# salt-call pillar.get foo
local:
    bar
```

If I change the pillar to break:

```
foo: {{ 1 / 0 }}
```

The minion just gets an empty pillar key:

```
root@minion:/# salt-call pillar.get foo
local:
```

At the same time master complains about the error in logs:

```
---
[CRITICAL] Rendering SLS 'foo' failed, render error:
Jinja error: division by zero
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 368, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 1, in top-level template code
ZeroDivisionError: division by zero

; line 1

---
foo: {{ 1 / 0 }}    <======================

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 368, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
[...]
---
[CRITICAL] Pillar render error: Rendering SLS 'foo' failed. Please see master log for details.
```

Expected behavior: salt command fails early because salt master is unable to render pillar.
Current behavior: salt command happily ignores broken pillar.

This doesn't happen all the time, at some point salt minion starts noticing that master can't render the pillar. It's hard to say how to reliably reproduce that with `state.apply` instead of `pillar.get`.

### Versions Report

* minion:

```
Salt Version:
           Salt: 2016.3.5

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: 0.3.6
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.6
        machine: x86_64
        release: 4.9.8-moby
         system: Linux
        version: debian 8.6
```

* master:

```
Salt Version:
           Salt: 2016.11.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: 0.3.6
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.6
        machine: x86_64
        release: 4.9.8-moby
         system: Linux
        version: debian 8.6
```

**Comment by gtmanfred** [comment]
I am unable to replicate the issue.

I see the same error on the master.

```
2017-03-03 15:41:26,308 [salt.utils.templates][ERROR   ][38] Rendering exception occurred: Jinja error: division by zero
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 368, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 2, in top-level template code
ZeroDivisionError: division by zero

; line 2

---
# Default pillar values
file: {{1/0}}    <======================

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 368, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
[...]
---
2017-03-03 15:41:26,309 [salt.pillar      ][CRITICAL][38] Rendering SLS 'default' failed, render error:
Jinja error: division by zero
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 368, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 2, in top-level template code
ZeroDivisionError: division by zero

; line 2

---
# Default pillar values
file: {{1/0}}    <======================

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 368, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
[...]
---
2017-03-03 15:41:26,309 [salt.pillar      ][CRITICAL][38] Pillar render error: Rendering SLS 'default' failed. Please see master log for details.
```

But i do not see any states run on the minion.

```
[root@saltmaster /]# cat /srv/salt/common/packages.sls
common_packages:
  pkg.installed:
    - pkgs:
      - htop
      - strace
      - vim-enhanced
```

```
[root@minion1 /]# rpm -q htop
package htop is not installed
```

And i am unable to get it to actually do the state.highstate without the pillars rendering.

**Comment by bobrik** [comment]
Right, it's important to issue the command from salt master. Sorry, I totally forgot to mention that.

I have:

* `states/foo.sls`

```
/etc/foo:
  file.managed:
    - contents: {{ salt.pillar.get('foo') }}
```

* `pillar/foo.sls`

```
foo: bar
```

With both files being the only thing in respective `top.sls` I let the minion to sync everything and highstate. Then:

```
$ docker exec -it salt-master salt '*' state.apply foo
minion:

Summary for minion
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:   9.528 ms
```

So far so good, but then I change pillar:

```
foo: {{ 1/0 }}
```

And issue the command again:

```
$ docker exec -it salt-master salt '*' state.apply foo
minion:

Summary for minion
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:   5.583 ms
```

This should've failed. There are errors in salt master logs:

```
[ERROR   ] Rendering exception occurred: Jinja error: division by zero
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 368, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 1, in top-level template code
ZeroDivisionError: division by zero

; line 1

---
foo: {{ 1/0 }}    <======================

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 368, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
[...]
---
[CRITICAL] Rendering SLS 'foo' failed, render error:
Jinja error: division by zero
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 368, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 1, in top-level template code
ZeroDivisionError: division by zero

; line 1

---
foo: {{ 1/0 }}    <======================

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 368, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
[...]
---
[CRITICAL] Pillar render error: Rendering SLS 'foo' failed. Please see master log for details.
```

Yet, even if I run it again, it works:

```
$ docker exec -it salt-master salt '*' state.apply foo
minion:

Summary for minion
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:   4.682 ms
```

It fails if I run it from the minion:

```
root@minion:/# salt-call state.apply foo
[INFO    ] The `lspci` binary is not available on the system. PCI Storage grains will not be available.
local:
    Data failed to compile:
----------
    Pillar failed to render with the following messages:
----------
    Rendering SLS 'foo' failed. Please see master log for details.
```

To make it fail from the master, I have to run `saltutil.sync_all`:

```
$ docker exec -it salt-master salt '*' saltutil.sync_all
minion:
    ----------
    beacons:
    engines:
    grains:
    log_handlers:
    modules:
    output:
    proxymodules:
    renderers:
    returners:
    sdb:
    states:
    utils:
```

```
$ docker exec -it salt-master salt '*' state.apply foo
minion:
    Data failed to compile:
----------
    Pillar failed to render with the following messages:
----------
    Rendering SLS 'foo' failed. Please see master log for details.
```

**Comment by gtmanfred** [comment]
My comment comes from running this on the salt master. And I was never able
to reproduce what you were seeing.

**Comment by gtmanfred** [comment]
I used my docker demo https://github.com/gtmanfred/salt-docker-demo/ and
added the versions of your minion and master to mimic the environment

**Comment by bobrik** [comment]
I used your demo and was able to reproduce:

```
bobrik@whatever-5: ~/projects/salt-docker-demo on master
$ git diff
diff --git a/saltstack/pillar/default.sls b/saltstack/pillar/default.sls
index 33ffb7b..4d2fa4a 100644
--- a/saltstack/pillar/default.sls
+++ b/saltstack/pillar/default.sls
@@ -1 +1,3 @@
 # Default pillar values
+
+foo: {{ 1/0 }}

bobrik@whatever-5: ~/projects/salt-docker-demo on master
$ docker exec -it saltdockerdemo_saltmaster_1 salt '*' state.apply common
minion2:
----------
          ID: common_packages
    Function: pkg.installed
      Result: True
     Comment: All specified packages are already installed
     Started: 23:10:20.088920
    Duration: 579.975 ms
     Changes:

Summary for minion2
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time: 579.975 ms
minion1:
----------
          ID: common_packages
    Function: pkg.installed
      Result: True
     Comment: All specified packages are already installed
     Started: 23:10:20.156956
    Duration: 588.99 ms
     Changes:

Summary for minion1
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time: 588.990 ms
```

**Comment by gtmanfred** [comment]
Ahh I see the problem. When you do a state.apply and specify a state, the
pillars are not refreshed, so this won't fail. If you remove the reference
to the sls, it runs high state, and it renders pillars ever time and it
will fail.

This is the expected behavior.

**Comment by bobrik** [comment]
Why do I see errors in salt master log if pillars are not refreshed?

**Comment by gtmanfred** [comment]
That I do not know right now, i will have to check it on monday.

But this is where in the highstate that the modules and pillars are refreshed.

https://github.com/saltstack/salt/blob/develop/salt/state.py#L3619
https://github.com/saltstack/salt/blob/develop/salt/state.py#L3138

And that is not run on a regular state.sls.

**Comment by bobrik** [comment]
Pillars are partially rendered, from what I see.

With the following state:

```
/etc/foo:
  file.managed:
    - contents: {{ salt.pillar.get('foo') }} {{ salt.pillar.get('bar') }}
```

And the following `pillar/top.sls`:

```
base:
  '*':
    - foo
    - bar
```

When I break `bar` I see the following:

```
$ docker exec -it salt-master salt '*' state.apply foo
minion:
----------
          ID: /etc/foo
    Function: file.managed
      Result: True
     Comment: File /etc/foo updated
     Started: 23:28:15.996592
    Duration: 9.512 ms
     Changes:
              ----------
              diff:
                  ---
                  +++
                  @@ -1 +1 @@
                  -foo bar
                  +foo

Summary for minion
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   9.512 ms
```

Pillars are even rendered when I do `salt-call test.ping`.

**Comment by dqminh** [comment]
https://github.com/saltstack/salt/pull/39727 fixes the issue for me, at least it will abort the salt run when pillar rendering partially failed.
