### ISSUE TITLE
Cron incompatible with python3

### ISSUE THREAD

**Issue by ninja-** [saltstack/salt#39833]
### Description of Issue/Question
Cron module on py3 is currently incompatible because of some bytes/strings problem.

```
    Function: cron.present
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3.6/site-packages/salt/state.py", line 1820, in call
                  **cdata['kwargs'])
                File "/usr/lib/python3.6/site-packages/salt/loader.py", line 1724, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/states/cron.py", line 335, in present
                  identifier=identifier)
                File "/usr/lib/python3.6/site-packages/salt/modules/cron.py", line 461, in set_job
                  lst = list_tab(user)
                File "/usr/lib/python3.6/site-packages/salt/modules/cron.py", line 293, in list_tab
                  data = raw_cron(user)
                File "/usr/lib/python3.6/site-packages/salt/modules/cron.py", line 270, in raw_cron
                  python_shell=False).splitlines(True)
                File "/usr/lib/python3.6/site-packages/salt/modules/cmdmod.py", line 1289, in run_stdout
                  **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/modules/cmdmod.py", line 540, in _run
                  proc = salt.utils.timed_subprocess.TimedProc(cmd, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/utils/timed_subprocess.py", line 41, in __init__
                  self.process = subprocess.Popen(args, **kwargs)
                File "/usr/lib/python3.6/subprocess.py", line 707, in __init__
                  restore_signals, start_new_session)
                File "/usr/lib/python3.6/subprocess.py", line 1251, in _execute_child
                  for dir in os.get_exec_path(env))
                File "/usr/lib/python3.6/os.py", line 640, in get_exec_path
                  "env cannot contain 'PATH' and b'PATH' keys")
              ValueError: env cannot contain 'PATH' and b'PATH' keys
```
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Latest develop branch, python3
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
Run any job using cron.present

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by ninja-** [comment]
The problem is here https://github.com/saltstack/salt/blob/develop/salt/modules/cmdmod.py#L440, I'll try to send a fix

**Comment by Ch3LL** [comment]
@ninja- thanks for the PR! once its been reviewed/merged please feel free to close this issue or we can.

**Comment by mchugh19** [comment]
Looks like this can be closed

**Comment by Ch3LL** [comment]
Thanks for the heads up
