### ISSUE TITLE
Parallel mode crashes with 

### ISSUE THREAD

**Issue by ninja-** [saltstack/salt#39831]
### Description of Issue/Question
This is my first take at using the new parallel feature and it doesn't quite work in my setup.

SLS file
```
  cloudflare.manage_zone_records:
    - zone: {{ pillar["xxx"]["dns"]["xxx.xyz"]|yaml }}
#    - parallel: True
```

```
    Function: cloudflare.manage_zone_records
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3.6/site-packages/salt/state.py", line 1817, in call
                  ret = self.call_parallel(cdata, low)
                File "/usr/lib/python3.6/site-packages/salt/state.py", line 1699, in call_parallel
                  ret = {'name': cdata['args'][0],
              IndexError: list index out of range
     Started: 19:38:35.127274
    Duration: 3.431 ms
```

Any ideas?

@thatch45 would you have an idea as an author of this feature.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Latest Salt Develop, python3
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by ninja-** [comment]
sent the issue twice by accident (closing dup.)
