### ISSUE TITLE
AttributeError: 'module' object has no attribute 'OrderedDict - 2016.11.3

### ISSUE THREAD

**Issue by tsaridas** [saltstack/salt#39885]
### Description of Issue/Question

#39392 made code incompatible with python2.6

```
[ERROR   ] Nested output failed:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/output/__init__.py", line 44, in try_printout
    printout = get_printout('nested', opts)(data, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/output/nested.py", line 161, in output
    return '\n'.join(nest.display(ret, base_indent, '', []))
  File "/usr/lib/python2.6/site-packages/salt/output/nested.py", line 133, in display
    if isinstance(ret, collections.OrderedDict):
AttributeError: 'module' object has no attribute 'OrderedDict'
```

### Steps to Reproduce Issue
salt minion test.ping

### Versions Report
2016.11.3

**Comment by tsaridas** [comment]
fixed in dev
