### ISSUE TITLE
salt-ssh throws un-handled TerminalExceptions in key deploy when no password entered

### ISSUE THREAD

**Issue by shallot** [saltstack/salt#39890]
This should probably be handled more gracefully:

```
% salt-ssh minion-hostname state.apply something
Permission denied for host minion-hostname, do you want to deploy the salt-ssh key? (password required):
[Y/n] _Y_
Password for ubuntu@minion-hostname: _[nothing entered]_
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TerminalException: You need to pass at least one of "args", "executable"
Traceback (most recent call last):
  File "/usr/bin/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 404, in salt_ssh
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/ssh.py", line 21, in run
    ssh.run()
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 633, in run
    ret = self.key_deploy(host, ret)
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 355, in key_deploy
    return self._key_deploy_run(host, target, True)
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 378, in _key_deploy_run
    stdout, stderr, retcode = single.shell.copy_id()
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/shell.py", line 209, in copy_id
    stdout, stderr, retcode = self._run_cmd(self._copy_id_str_old())
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/shell.py", line 352, in _run_cmd
    stream_stderr=False)
  File "/usr/lib/python2.7/dist-packages/salt/utils/vt.py", line 124, in __init__
    'You need to pass at least one of "args", "executable" '
TerminalException: You need to pass at least one of "args", "executable"
Traceback (most recent call last):
  File "/usr/bin/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 404, in salt_ssh
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/ssh.py", line 21, in run
    ssh.run()
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 633, in run
    ret = self.key_deploy(host, ret)
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 355, in key_deploy
    return self._key_deploy_run(host, target, True)
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 378, in _key_deploy_run
    stdout, stderr, retcode = single.shell.copy_id()
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/shell.py", line 209, in copy_id
    stdout, stderr, retcode = self._run_cmd(self._copy_id_str_old())
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/shell.py", line 352, in _run_cmd
    stream_stderr=False)
  File "/usr/lib/python2.7/dist-packages/salt/utils/vt.py", line 124, in __init__
    'You need to pass at least one of "args", "executable" '
salt.utils.vt.TerminalException: You need to pass at least one of "args", "executable"
Exception AttributeError: "'Terminal' object has no attribute 'pid'" in <bound method Terminal.__del__ of <salt.utils.vt.Terminal object at 0x7fbe751f5150>> ignored
```

### Versions Report
```
% salt --versions-report
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: Not Installed
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-108-generic
         system: Linux
        version: Ubuntu 14.04 trusty

```

**Comment by Ch3LL** [comment]
Agreed we should definitely not stack tracer here. We will need to print out an error.
