### ISSUE TITLE
File.managed S3 checksum problem

### ISSUE THREAD

**Issue by scottf-unity** [saltstack/salt#39903]
Something appears to have recently changed causing subsequent state runs to fail for file.managed when using S3 as the source.  My master was initially on 2016.3.4 (due to some other issues) and minions using version 2016.11.2 worked fine.  When switching minions to 2016.11.3 the breakage would appear.  Also upgrading to 2016.11.3  on both master and minion has the same error.  The initial state apply after a fresh created instances works fine, but subsequent runs after that fail due to a checksum issue.

```
#install p4 client:
install s3://{{ s3_packages_path }}/{{ p4_client }}:
  file.managed:
    - name: /usr/local/bin/p4
    - source: s3://{{ s3_packages_path }}/{{ p4_client }}
    - skip_verify: True
    - user: root
    - group: root
    - mode: 0755
```

```
          ID: install s3://custom-packages/p4-linux-64
    Function: file.managed
        Name: /usr/local/bin/p4
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1746, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1703, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 1793, in managed
                  **kwargs
                File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 4299, in check_managed_changes
                  **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 3748, in get_managed
                  if cached_sum != source_sum['hsum']:
              KeyError: 'hsum'
     Started: 19:22:01.063095
    Duration: 42.475 ms
     Changes:
```

Master:
```
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-66-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

Minion:
```
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-107-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by toanctruong** [comment]
Also running into this issue. I seem to have bad luck with any S3 related module.

State
```
retrieve_api_artifact:
  file.managed:
    - source: s3://{{ pillar['app']['artifactBucket'] }}/app-{{ pillar['app']['build'] }}.tar.gz
    - name: /opt/app-{{ pillar['app']['build'] }}.tar.gz
    - skip_verify: true
    - unless: ls /opt/app-{{ pillar['app']['build'] }}.tar.gz
```
Output
```
          ID: retrieve_api_artifact
    Function: file.managed
        Name: /opt/app-11095.tar.gz
      Result: False
     Comment: Unable to manage file: 'hsum'
     Started: 07:05:31.660707
    Duration: 851.248 ms
     Changes:
```

When test=true

```
          ID: retrieve_api_artifact
    Function: file.managed
        Name: /opt/app-11095.tar.gz
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1746, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1703, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/file.py", line 1793, in managed
                  **kwargs
                File "/usr/lib/python2.7/site-packages/salt/modules/file.py", line 4299, in check_managed_changes
                  **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/modules/file.py", line 3748, in get_managed
                  if cached_sum != source_sum['hsum']:
              KeyError: 'hsum'
     Started: 07:05:14.184682
    Duration: 860.701 ms
     Changes:
```
Master Version

```
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 2.6.0
          gitdb: 0.6.4
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.6.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

**Comment by gtmanfred** [comment]
This appears to be the same issue as here https://github.com/saltstack/salt/issues/39751

Can you check this PR?

https://github.com/saltstack/salt/pull/39762

`patch -Np1 -d /usr/lib/python2.7/site-packages/salt < <(curl -Ls https://github.com/saltstack/salt/pull/39762.diff)`

**Comment by scottf-unity** [comment]
Patched applied via above to modules/file.py and states/archive.py

Still have the same Unable to manage file: 'hsum' error when re-running a state that pulls files from S3.

**Comment by gtmanfred** [comment]
You shouldn't have the exact same error if the patch was applied.

The if statement was changed to an elif statement.

https://github.com/saltstack/salt/pull/39762/files#diff-7c48191b14cdf053cf954d03cc317963R3776

Did you run a saltutil.sync_modules to sync the modules down?  What command are you running to test this? If you were using state.sls or state.apply with specifying a certain state to run, then the modules are not synced.  They are only synced on highstates.

Thanks,
Daniel

**Comment by scottf-unity** [comment]
So, I failed to patch this on the minion (only did it on master).  I guess I'm still learning about Salt.  I applied the patch to the minion and it fixed it.  The command I was running was a state.apply.  

I guess I need to familiarize myself with managing minion modules as I hadn't seen the use case yet.

Apologies for the confusion and thank you very much for the help!

**Comment by gtmanfred** [comment]
No problem! glad it worked!

**Comment by syphernl** [comment]
FWIW this is not just limited to S3 but also affects downloads from web (http, https).
