### ISSUE TITLE
win_lgpo missing policies, eg. `Prevent the usage of OneDrive for file storage`

### ISSUE THREAD

**Issue by peterhirn** [saltstack/salt#39976]
Missing in the output of `salt "*" lgpo.get return_not_configured=True`. 

OneDrive only contains one setting: `Windows Components\OneDrive\Save documents to OneDrive by default`. There are 3 other settings missing.

- Salt-Minion-2016.11.3-AMD64
- Windows 10 Enterprise

Trying to set a missing policy results in:

	----------
		  ID: group-policy
	    Function: lgpo.set
	      Result: False
	     Comment: An exception occurred in this state: Traceback (most recent call last):
			File "c:\salt\bin\lib\site-packages\salt\state.py", line 1746, in call
			  **cdata['kwargs'])
			File "c:\salt\bin\lib\site-packages\salt\loader.py", line 1703, in wrapper
			  return f(*args, **kwargs)
			File "c:\salt\bin\lib\site-packages\salt\states\win_lgpo.py", line 226, in set_
			  adml_language=adml_language)
			File "c:\salt\bin\lib\site-packages\salt\modules\win_lgpo.py", line 4744, in get_policy_info
			  adml_policy_resources=adml_policy_resources)
			File "c:\salt\bin\lib\site-packages\salt\modules\win_lgpo.py", line 4600, in _lookup_admin_template
			  if not adml_search_result.attrib['text'].strip() == policy_name:
			File "src/lxml/lxml.etree.pyx", line 2452, in lxml.etree._Attrib.__getitem__ (src\lxml\lxml.etree.c:68625)
		      KeyError: 'text'
	     Started: 17:12:27.409000
	    Duration: 472.0 ms
	     Changes:

**Comment by gtmanfred** [comment]
Can you provide me with some information on how to set this up and test it?

Thanks,
Daniel

**Comment by peterhirn** [comment]
I'm trying to apply the following state to a Windows 10 Enterprise machine:

	group-policy-update:
	  cmd.wait:
	      - name: 'gpupdate /force'

	group-policy:
	  lgpo.set:
	    - computer_policy:
		'Windows Components\Windows Update\No auto-restart with logged on users for scheduled automatic updates installations': Disabled
		'Windows Components\Cloud Content\Do not show Windows tips': Enabled
		'Windows Components\Cloud Content\Turn off Microsoft consumer experiences': Enabled
		'Windows Components\OneDrive\Save documents to OneDrive by default': Disabled
		#'Windows Components\OneDrive\Prevent the usage of OneDrive for file storage': Enabled
	    - watch_in:
	      - cmd: group-policy-update

Uncommenting the last policy leads to the error in my initial comment.

**Comment by gtmanfred** [comment]
Can you also provide the versions report that the blueprint for issue requests so that we can make sure to replicate this against the same version?

Thanks,
Daniel

**Comment by damon-atkins** [comment]
I believe that the original author had no choice but to hard code the lgpo.  So every time a new Windows OS comes out this will need to be updated.

**Comment by peterhirn** [comment]
Master:

	Salt Version:
		   Salt: 2016.11.3

	Dependency Versions:
		   cffi: Not Installed
	       cherrypy: Not Installed
	       dateutil: 1.5
		  gitdb: 0.5.4
	      gitpython: 0.3.2 RC1
		  ioflo: Not Installed
		 Jinja2: 2.7.3
		libgit2: Not Installed
		libnacl: Not Installed
	       M2Crypto: Not Installed
		   Mako: Not Installed
	   msgpack-pure: Not Installed
	 msgpack-python: 0.4.2
	   mysql-python: 1.2.3
	      pycparser: Not Installed
	       pycrypto: 2.6.1
		 pygit2: Not Installed
		 Python: 2.7.3 (default, Jun 21 2016, 18:38:19)
	   python-gnupg: Not Installed
		 PyYAML: 3.11
		  PyZMQ: 13.1.0
		   RAET: Not Installed
		  smmap: 0.8.2
		timelib: Not Installed
		Tornado: 4.2.1
		    ZMQ: 4.0.5

	System Versions:
		   dist: debian 7.11
		machine: x86_64
		release: 3.2.0-4-amd64
		 system: Linux
		version: debian 7.11

Minion:

	Salt Version:
		   Salt: 2016.11.3

	Dependency Versions:
		   cffi: 1.7.0
	       cherrypy: unknown
	       dateutil: 2.5.3
		  gitdb: 0.6.4
	      gitpython: 2.0.8
		  ioflo: 1.5.5
		 Jinja2: 2.9.4
		libgit2: Not Installed
		libnacl: 1.4.5
	       M2Crypto: Not Installed
		   Mako: 1.0.4
	   msgpack-pure: Not Installed
	 msgpack-python: 0.4.8
	   mysql-python: Not Installed
	      pycparser: 2.14
	       pycrypto: 2.6.1
		 pygit2: Not Installed
		 Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
	   python-gnupg: 0.3.8
		 PyYAML: 3.11
		  PyZMQ: 16.0.1
		   RAET: Not Installed
		  smmap: 0.9.0
		timelib: 0.2.4
		Tornado: 4.4.1
		    ZMQ: 4.1.6

	System Versions:
		   dist:
		machine: AMD64
		release: 10
		 system: Windows
		version: 10 10.0.14393  Multiprocessor Free

**Comment by lorengordon** [comment]
ping @lomeroe ;)

**Comment by lomeroe** [comment]
@damon-atkins Administrative Templates (which would include the OneDrive setting) in the module are dynamically read from the localadmx/adml files.

I'm able to set this on my dev machine , so I must have screwed something up when creating all my backport PRs to merge bug fixes back into 2016.11.

**Comment by lomeroe** [comment]
@peterdemin would you mind testing w/the win_lgpo module out of develop?  Would help me verify that it is a mistake in a backport vs something else...

**Comment by lorengordon** [comment]
@lomeroe, appears to be something else. I just spun up a new win10 enterprise vm, installed salt 2016.11.3, ran the state posted above by @peterhirn and got the exception. I then replaced the win_lgpo.py execution module with the copy from develop, re-ran the state, and got the same exception. Below is the debug output using the version from develop...

I'll keep this box around for a bit if you want me to try anything else. Or I can always spin up a new vm pretty easily...

```
PS C:\Windows\system32> C:\salt\salt-call.bat --local -l debug state.apply lgpotest
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Using cached minion ID from c:\salt\conf\minion_id: xxxxxx.localdomain
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded state.apply
[DEBUG   ] LazyLoaded saltutil.is_running
[DEBUG   ] LazyLoaded grains.get
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[DEBUG   ] Updating roots fileserver cache
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] In saltenv 'base', looking at rel_path 'lgpotest.sls' to resolve 'salt://lgpotest.sls'
[DEBUG   ] In saltenv 'base', ** considering ** path 'c:\salt\var\cache\salt\minion\files\base\lgpotest.sls' to resolve 'salt://lgpotest.sls'
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://lgpotest.sls'
[DEBUG   ] compile template: c:\salt\var\cache\salt\minion\files\base\lgpotest.sls
[DEBUG   ] Jinja search path: ['c:\\salt\\var\\cache\\salt\\minion\\files\\base']
[PROFILE ] Time (in seconds) to render 'c:\salt\var\cache\salt\minion\files\base\lgpotest.sls' using 'jinja' renderer: 0.0
[DEBUG   ] Rendered data from file: c:\salt\var\cache\salt\minion\files\base\lgpotest.sls:
group-policy-update:
  cmd.wait:
    - name: 'gpupdate /force'

group-policy:
  lgpo.set:
    - computer_policy:
        'Windows Components\Windows Update\No auto-restart with logged on users for scheduled automatic updates installa
tions': Disabled
        'Windows Components\Cloud Content\Do not show Windows tips': Enabled
        'Windows Components\Cloud Content\Turn off Microsoft consumer experiences': Enabled
        'Windows Components\OneDrive\Save documents to OneDrive by default': Disabled
        'Windows Components\OneDrive\Prevent the usage of OneDrive for file storage': Enabled
    - watch_in:
      - cmd: group-policy-update
[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Results of YAML rendering:
OrderedDict([('group-policy-update', OrderedDict([('cmd.wait', [OrderedDict([('name', 'gpupdate /force')])])])), ('group-policy', OrderedDict([('lgpo.set', [OrderedDict([('computer_policy', OrderedDict([('Windows Components\\Windows Update\\No auto-restart with logged on users for scheduled automatic updates installations', 'Disabled'), ('Windows Components\\Cloud Content\\Do not show Windows tips', 'Enabled'), ('Windows Components\\Cloud Content\\Turn off Microsoft consumer experiences', 'Enabled'), ('Windows Components\\OneDrive\\Save documents to OneDrive by default', 'Disabled'), ('Windows Components\\OneDrive\\Prevent the usage of OneDrive for file storage', 'Enabled')]))]), OrderedDict([('watch_in', [OrderedDict([('cmd', 'group-policy-update')])])])])]))])
[PROFILE ] Time (in seconds) to render 'c:\salt\var\cache\salt\minion\files\base\lgpotest.sls' using 'yaml' renderer: 0.468999862671
[DEBUG   ] LazyLoaded cmd.wait
[DEBUG   ] LazyLoaded lgpo.set
[DEBUG   ] LazyLoaded lgpo.set
[INFO    ] Running state [group-policy] at time 17:24:43.219000
[INFO    ] Executing state lgpo.set for group-policy
[DEBUG   ] LazyLoaded file.file_exists
[DEBUG   ] found an ADML entry matching the string! {Microsoft.Policies.WindowsUpdate}string -- {'id': 'NoAutoRebootWithLoggedOnUsers_Title'}
[DEBUG   ] searching for displayName == $(string.NoAutoRebootWithLoggedOnUsers_Title)
[DEBUG   ] found the ADMX policy matching the display name No auto-restart with logged on users for scheduled automatic updates installations -- <Element {Microsoft.Policies.WindowsUpdate}policy at 0x6615088>
[DEBUG   ] found an ADML entry matching the string! {Microsoft.Policies.CloudContent}string -- {'id': 'DisableSoftLanding'}
[DEBUG   ] searching for displayName == $(string.DisableSoftLanding)
[DEBUG   ] found the ADMX policy matching the display name Do not show Windows tips -- <Element {Microsoft.Policies.CloudContent}policy at 0x6604e08>
[DEBUG   ] found an ADML entry matching the string! {Microsoft.Policies.CloudContent}string -- {'id': 'DisableWindowsConsumerFeatures'}
[DEBUG   ] searching for displayName == $(string.DisableWindowsConsumerFeatures)
[DEBUG   ] found the ADMX policy matching the display name Turn off Microsoft consumer experiences -- <Element {Microsoft.Policies.CloudContent}policy at 0x65f3148>
[DEBUG   ] found an ADML entry matching the string! {Microsoft.Policies.OneDrive}string -- {'id': 'DisableLibrariesDefaultSaveToOneDrive_Title'}
[DEBUG   ] searching for displayName == $(string.DisableLibrariesDefaultSaveToOneDrive_Title)
[DEBUG   ] found the ADMX policy matching the display name Save documents to OneDrive by default -- <Element {Microsoft.Policies.OneDrive}policy at 0x6098b48>
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\state.py", line 1746, in call
    **cdata['kwargs'])
  File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1703, in wrapper
    return f(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\states\win_lgpo.py", line 226, in set_
    adml_language=adml_language)
  File "C:\salt\bin\lib\site-packages\salt\modules\win_lgpo.py", line 4747, in get_policy_info
    adml_policy_resources=adml_policy_resources)
  File "C:\salt\bin\lib\site-packages\salt\modules\win_lgpo.py", line 4603, in _lookup_admin_template
    if not adml_search_result.attrib['text'].strip() == policy_name:
  File "src/lxml/lxml.etree.pyx", line 2452, in lxml.etree._Attrib.__getitem__ (src\lxml\lxml.etree.c:68625)
KeyError: 'text'

[INFO    ] Completed state [group-policy] at time 17:24:46.453000 duration_in_ms=3234.0
[DEBUG   ] File c:\salt\var\cache\salt\minion\accumulator\99060368 does not exist, no need to cleanup.
[DEBUG   ] LazyLoaded config.option
[DEBUG   ] LazyLoaded cmd.run
[INFO    ] Executing command ['attrib', '-R', 'c:\\salt\\var\\cache\\salt\\minion\\sls.p'] in directory 'C:\Users\Loren'
[DEBUG   ] output:
[DEBUG   ] LazyLoaded highstate.output
local:
----------
          ID: group-policy
    Function: lgpo.set
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "C:\salt\bin\lib\site-packages\salt\state.py", line 1746, in call
                  **cdata['kwargs'])
                File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1703, in wrapper
                  return f(*args, **kwargs)
                File "C:\salt\bin\lib\site-packages\salt\states\win_lgpo.py", line 226, in set_
                  adml_language=adml_language)
                File "C:\salt\bin\lib\site-packages\salt\modules\win_lgpo.py", line 4747, in get_policy_info
                  adml_policy_resources=adml_policy_resources)
                File "C:\salt\bin\lib\site-packages\salt\modules\win_lgpo.py", line 4603, in _lookup_admin_template
                  if not adml_search_result.attrib['text'].strip() == policy_name:
                File "src/lxml/lxml.etree.pyx", line 2452, in lxml.etree._Attrib.__getitem__ (src\lxml\lxml.etree.c:68625)
              KeyError: 'text'
     Started: 17:24:43.219000
    Duration: 3234.0 ms
     Changes:
----------
          ID: group-policy-update
    Function: cmd.wait
        Name: gpupdate /force
      Result: False
     Comment: One or more requisite failed: lgpotest.group-policy
     Changes:

Summary for local
------------
Succeeded: 0
Failed:    2
------------
Total states run:     2
Total run time:   3.234 s
```

**Comment by lorengordon** [comment]
On this box, the adml file is `C:\Windows\PolicyDefinitions\en-us\SkyDrive.xml`. It's not that big, so pasting here (note the funky characters, â€™, appear the same in wordpad on the vm, but render as smart quotes in gpedit, yay unicode?):

```
<?xml version="1.0" encoding="utf-8"?>
<policyDefinitionResources xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" revision="1.0" schemaVersion="1.0" xmlns="http://www.microsoft.com/GroupPolicy/PolicyDefinitions">
  <displayName>Prevent OneDrive file sync</displayName>
  <description>Prevent files from being automatically synced to OneDrive</description>
  <resources>
    <stringTable>
      <!-- general -->
      <string id="OneDriveSettingCategory">OneDrive</string>
      
      <!-- prevent file sync-->
      <string id="PreventOneDriveFileSync">Prevent the usage of OneDrive for file storage</string>
      <string id="PreventOneDriveFileSync_help">This policy setting lets you prevent apps and features from working with files on OneDrive.
If you enable this policy setting:

* Users canâ€™t access OneDrive from the OneDrive app and file picker.
* Windows Store apps canâ€™t access OneDrive using the WinRT API.
* OneDrive doesnâ€™t appear in the navigation pane in File Explorer.
* OneDrive files arenâ€™t kept in sync with the cloud.
* Users canâ€™t automatically upload photos and videos from the camera roll folder.

If you disable or do not configure this policy setting, apps and features can work with OneDrive file storage.</string>

      <!-- prevent file sync for Blue-->
      <string id="PreventOneDriveFileSyncForBlue">Prevent the usage of OneDrive for file storage on Windows 8.1</string>
      <string id="PreventOneDriveFileSyncForBlue_help">This policy setting lets you prevent apps and features from working with files on OneDrive for Windows 8.1.
If you enable this policy setting:

* Users canâ€™t access OneDrive from the OneDrive app and file picker.
* Windows Store apps canâ€™t access OneDrive using the WinRT API.
* OneDrive doesnâ€™t appear in the navigation pane in File Explorer.
* OneDrive files arenâ€™t kept in sync with the cloud.
* Users canâ€™t automatically upload photos and videos from the camera roll folder.

If you disable or do not configure this policy setting, apps and features can work with OneDrive file storage.</string>

      <!-- metered network settings -->
      <string id="PreventOneDriveFileSyncOnMeteredNetwork">Prevent OneDrive files from syncing over metered connections</string>
      <string id="PreventOneDriveFileSyncOnMeteredNetwork_help">This policy setting allows configuration of OneDrive file sync behavior on metered connections.</string>
      <string id="OneDriveNeverSyncOnMeteredRoaming">Block syncing on all metered connections</string>
      <string id="OneDriveSyncOnMeteredNotRoaming">Block syncing on metered connections only when roaming</string>

      <!-- default save to OneDrive -->
      <string id="DisableLibrariesDefaultSaveToOneDrive_Title">Save documents to OneDrive by default</string>
      <string id="DisableLibrariesDefaultSaveToOneDrive_Description">This policy setting lets you disable OneDrive as the default save location. It does not prevent apps and users from saving files on OneDrive. If you disable this policy setting, files will be saved locally by default. Users will still be able to change the value of this setting to save to OneDrive by default. They will also be able to open and save files on OneDrive using the OneDrive app and file picker, and Windows Store apps will still be able to access OneDrive using the WinRT API. If you enable or do not configure this policy setting, users with a connected account will save documents to OneDrive by default.</string>
    </stringTable>
    <presentationTable>
      <presentation id="PreventOneDriveFileSyncOnMeteredNetwork">
        <dropdownList refId="OneDriveMeteredNetwork_Dropdown" noSort="true" defaultItem="0">Metered Network Setting</dropdownList>
      </presentation>
    </presentationTable>
  </resources>
</policyDefinitionResources>
```

**Comment by lomeroe** [comment]
Thanks @lorengordon the adml is different than the one in 2012R2 for SkyDrive.

What happens if you remove the Full Policy path components and just use "Prevent OneDrive..."?  Any difference?

Also, what do you get if you run
```
salt-call lgpo.get_policy_info "Prevent the usage of OneDrive for file storage" machine
```

**Comment by lorengordon** [comment]
You mean like this?

```
group-policy-update:
  cmd.wait:
    - name: 'gpupdate /force'

group-policy:
  lgpo.set:
    - computer_policy:
        'Prevent the usage of OneDrive for file storage': Enabled
    - watch_in:
      - cmd: group-policy-update
```

No diff:

```
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\state.py", line 1746, in call
    **cdata['kwargs'])
  File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1703, in wrapper
    return f(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\states\win_lgpo.py", line 226, in set_
    adml_language=adml_language)
  File "C:\salt\bin\lib\site-packages\salt\modules\win_lgpo.py", line 4747, in get_policy_info
    adml_policy_resources=adml_policy_resources)
  File "C:\salt\bin\lib\site-packages\salt\modules\win_lgpo.py", line 4603, in _lookup_admin_template
    if not adml_search_result.attrib['text'].strip() == policy_name:
  File "src/lxml/lxml.etree.pyx", line 2452, in lxml.etree._Attrib.__getitem__ (src\lxml\lxml.etree.c:68625)
KeyError: 'text'

local:
----------
          ID: group-policy
    Function: lgpo.set
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "C:\salt\bin\lib\site-packages\salt\state.py", line 1746, in call
                  **cdata['kwargs'])
                File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1703, in wrapper
                  return f(*args, **kwargs)
                File "C:\salt\bin\lib\site-packages\salt\states\win_lgpo.py", line 226, in set_
                  adml_language=adml_language)
                File "C:\salt\bin\lib\site-packages\salt\modules\win_lgpo.py", line 4747, in get_policy_info
                  adml_policy_resources=adml_policy_resources)
                File "C:\salt\bin\lib\site-packages\salt\modules\win_lgpo.py", line 4603, in _lookup_admin_template
                  if not adml_search_result.attrib['text'].strip() == policy_name:
                File "src/lxml/lxml.etree.pyx", line 2452, in lxml.etree._Attrib.__getitem__ (src\lxml\lxml.etree.c:68625)
              KeyError: 'text'
     Started: 19:09:54.597000
    Duration: 828.0 ms
     Changes:
----------
          ID: group-policy-update
    Function: cmd.wait
        Name: gpupdate /force
      Result: False
     Comment: One or more requisite failed: lgpotest.group-policy
     Changes:

Summary for local
------------
Succeeded: 0
Failed:    2
------------
Total states run:     2
Total run time: 828.000 ms
```

Also same deal for calling the execution module from the cli:

```
PS C:\Windows\system32> C:\salt\salt-call.bat --local lgpo.get_policy_info 'Prevent the usage of OneDrive for file storage' machine
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
KeyError: 'text'
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 379, in salt_call
    client.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\call.py", line 58, in run
    caller.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 134, in run
    ret = self.call()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\modules\win_lgpo.py", line 4747, in get_policy_info
    adml_policy_resources=adml_policy_resources)
  File "C:\salt\bin\lib\site-packages\salt\modules\win_lgpo.py", line 4603, in _lookup_admin_template
    if not adml_search_result.attrib['text'].strip() == policy_name:
  File "src/lxml/lxml.etree.pyx", line 2452, in lxml.etree._Attrib.__getitem__ (src\lxml\lxml.etree.c:68625)
KeyError: 'text'
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 379, in salt_call
    client.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\call.py", line 58, in run
    caller.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 134, in run
    ret = self.call()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\modules\win_lgpo.py", line 4747, in get_policy_info
    adml_policy_resources=adml_policy_resources)
  File "C:\salt\bin\lib\site-packages\salt\modules\win_lgpo.py", line 4603, in _lookup_admin_template
    if not adml_search_result.attrib['text'].strip() == policy_name:
  File "src/lxml/lxml.etree.pyx", line 2452, in lxml.etree._Attrib.__getitem__ (src\lxml\lxml.etree.c:68625)
KeyError: 'text'
```

**Comment by lomeroe** [comment]
@lorengordon couple more thing to try for me, if you have time:

change line 4603, which is causing the exception from 
```
if not adml_search_result.attrib['text'].strip() == policy_name:
```
to
```
if not getattr(adml_search_result, 'text', '').strip() == policy_name:
```

also, run the following powershell snippet:
```
get-childitem -path 'C:\windows\PolicyDefinitions' -recurse | select-string "Prevent the usage"
```

**Comment by lorengordon** [comment]
Yup, made that edit, and now `get_policy_info` is ok, but get a different traceback when applying the state:

```
PS C:\Windows\system32> C:\salt\salt-call.bat --local lgpo.get_policy_info 'Prevent the usage of OneDrive for file storage' machine
local:
    ----------
    message:
    policy_aliases:
        - Prevent the usage of OneDrive for file storage
        - PreventOnedriveFileSync
        - Windows Components\OneDrive\Prevent the usage of OneDrive for file storage
    policy_class:
        machine
    policy_elements:
    policy_found:
        True
    policy_name:
        Prevent the usage of OneDrive for file storage
    rights_assignment:
        False
```

```
PS C:\Windows\system32> C:\salt\salt-call.bat --local state.sls lgpotest
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\state.py", line 1746, in call
    **cdata['kwargs'])
  File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1703, in wrapper
    return f(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\states\win_lgpo.py", line 300, in set_
    hierarchical_return=False)
  File "C:\salt\bin\lib\site-packages\salt\modules\win_lgpo.py", line 4898, in get
    return_not_configured=return_not_configured))
  File "C:\salt\bin\lib\site-packages\salt\modules\win_lgpo.py", line 3824, in _checkAllAdmxPolicies
    if full_names[policy_item] in policy_vals:
KeyError: 'Prevent the usage of OneDrive for file storage'

local:
----------
          ID: group-policy
    Function: lgpo.set
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "C:\salt\bin\lib\site-packages\salt\state.py", line 1746, in call
                  **cdata['kwargs'])
                File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1703, in wrapper
                  return f(*args, **kwargs)
                File "C:\salt\bin\lib\site-packages\salt\states\win_lgpo.py", line 300, in set_
                  hierarchical_return=False)
                File "C:\salt\bin\lib\site-packages\salt\modules\win_lgpo.py", line 4898, in get
                  return_not_configured=return_not_configured))
                File "C:\salt\bin\lib\site-packages\salt\modules\win_lgpo.py", line 3824, in _checkAllAdmxPolicies
                  if full_names[policy_item] in policy_vals:
              KeyError: 'Prevent the usage of OneDrive for file storage'
     Started: 20:25:49.204000
    Duration: 5344.0 ms
     Changes:
----------
          ID: group-policy-update
    Function: cmd.wait
        Name: gpupdate /force
      Result: False
     Comment: One or more requisite failed: lgpotest.group-policy
     Changes:

Summary for local
------------
Succeeded: 0
Failed:    2
------------
Total states run:     2
Total run time:   5.344 s
```

Here's the output of the powershell command:

```
PS C:\Windows\system32> Get-ChildItem -Path "C:\Windows\PolicyDefinitions\" -Recurse | Select-String "Prevent the usage"


C:\Windows\PolicyDefinitions\en-US\SkyDrive.adml:11:      <string id="PreventOneDriveFileSync">Prevent the usage of OneDrive for file storage</string>
C:\Windows\PolicyDefinitions\en-US\SkyDrive.adml:24:      <string id="PreventOneDriveFileSyncForBlue">Prevent the usage of OneDrive for file storage on Windows 8.1</string>
```

**Comment by lomeroe** [comment]
@lorengordon  thanks for you help troubleshooting this...

if you set "return_full_policy_names: False" in the state, does it work?

**Comment by lorengordon** [comment]
No, it tells me that is not a valid option for `lgpo.set`. I also don't see it as an option on the module?

- [module doc](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.win_lgpo.html#salt.modules.win_lgpo.set)
- [state doc](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.win_lgpo.html#salt.states.win_lgpo.set)

**Comment by lomeroe** [comment]
@lorengordon @peterhirn if you make the change on the 2016.11 win_lgpo.py file, does it work?

looks like it should be line 4600 in 2016.11.3:
```
if not adml_search_result.attrib['text'].strip() == policy_name:
```
to
```
if not getattr(adml_search_result, 'text', '').strip() == policy_name:
```

@s0undt3ch 
This stack trace which @lorengordon  received after making that edit in develop, is being caused by your PR #39843, which removed the .keys():
```
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\state.py", line 1746, in call
    **cdata['kwargs'])
  File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1703, in wrapper
    return f(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\states\win_lgpo.py", line 300, in set_
    hierarchical_return=False)
  File "C:\salt\bin\lib\site-packages\salt\modules\win_lgpo.py", line 4898, in get
    return_not_configured=return_not_configured))
  File "C:\salt\bin\lib\site-packages\salt\modules\win_lgpo.py", line 3824, in _checkAllAdmxPolicies
    if full_names[policy_item] in policy_vals:
KeyError: 'Prevent the usage of OneDrive for file storage'
```
It looks like there were other .keys() removals in other modules as part of this commit that were reverted and this one needs to be reverted as well:
``
        for policy_item in policy_vals:
            if full_names[policy_item] in policy_vals:
                # add this item with the path'd full name
                full_path_list = hierarchy[policy_item]
                full_path_list.reverse()
                full_path_list.append(full_names[policy_item])
                policy_vals['\\'.join(full_path_list)] = policy_vals.pop(policy_item)
                pathed_dict[full_names[policy_item]] = True
            else:
                policy_vals[full_names[policy_item]] = policy_vals.pop(policy_item)
                unpathed_dict[full_names[policy_item]] = policy_item
```
needs to be
```
        for policy_item in policy_vals.keys():
            if full_names[policy_item] in policy_vals:
                # add this item with the path'd full name
                full_path_list = hierarchy[policy_item]
                full_path_list.reverse()
                full_path_list.append(full_names[policy_item])
                policy_vals['\\'.join(full_path_list)] = policy_vals.pop(policy_item)
                pathed_dict[full_names[policy_item]] = True
            else:
                policy_vals[full_names[policy_item]] = policy_vals.pop(policy_item)
                unpathed_dict[full_names[policy_item]] = policy_item
```
This is b/c during the loop, the policy_val keys are being modified, w/o the .keys() the for is dynamic and attempts to loop through the newly added keys, which aren't in the "full_names" dict.  We only want to process the original keys of the dictionary, thus the .keys() usage.

**Comment by lorengordon** [comment]
@lomeroe, that edit when applied to the 2016.11 branch did the trick! 

> `if not adml_search_result.attrib['text'].strip() == policy_name:`
> to
> `if not getattr(adml_search_result, 'text', '').strip() == policy_name:`

However, the "changes" dictionary seems to be returning the full computer policy and not just the one new policy. Is that expected? Might be nice to diff the old and new policies to make that easier to see what is changing... Would be a different issue, of course.

**Comment by lomeroe** [comment]
@lorengordon good to hear -- yes, it just spits out the policy before/after and doesn't diff them (one of the many places that could use some more attention)

**Comment by lorengordon** [comment]
Ok, cool. Looks like develop now has [`dictdiffer.deep_diff`](https://github.com/saltstack/salt/blob/develop/salt/utils/dictdiffer.py#L49), which produces nice looking output. PR inbound...

```
local:
----------
          ID: group-policy
    Function: lgpo.set
      Result: True
     Comment:
     Started: 17:23:32.679000
    Duration: 4703.0 ms
     Changes:
              ----------
              new:
                  ----------
                  Computer Configuration:
                      ----------
                      Windows Components\OneDrive\Prevent the usage of OneDrive for file storage:
                          Enabled
              old:
                  ----------
                  Computer Configuration:
                      ----------
```
