### ISSUE TITLE
Missing napalm grains in develop

### ISSUE THREAD

**Issue by bewing** [saltstack/salt#39983]
### Some default grains are missing in napalm in develop branch

Most notably, in "develop", "os" is reported as None when testing both vEOS and vSRX.

### Setup
Provisioned new salt master with Vagrant salt provisioner, install "git", source "develop"

### Steps to Reproduce Issue
Configure napalm proxy for vEOS device and retrieve grains.

### Output from "stable":
```
[root@saltmaster:~] # salt --versions-report
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-110-generic
         system: Linux
        version: Ubuntu 14.04 trusty

[root@saltmaster:~] # salt veos1 grains.items
veos1:
    ----------
    cpuarch:
        x86_64
    dns:
        ----------
        domain:
        ip4_nameservers:
            - 10.0.2.3
        ip6_nameservers:
        nameservers:
            - 10.0.2.3
        options:
        search:
        sortlist:
    gpus:
    hwaddr_interfaces:
        ----------
        eth0:
            08:00:27:41:9a:fb
        eth1:
            08:00:27:90:55:63
        lo:
            00:00:00:00:00:00
    id:
        veos1.trading.imc.intra
    interfaces:
        - Ethernet1
        - Management1
    kernel:
        proxy
    kernelrelease:
        proxy
    locale_info:
        ----------
    machine_id:
        6d8476cdd65de59207caf74f58b883d8
    master:
        localhost
    mem_total:
        0
    model:
        vEOS
    nodename:
        saltmaster
    num_gpus:
        0
    os:
        eos
    os_family:
        proxy
    osarch:
        x86_64
    osfinger:
        proxy-proxy
    osfullname:
        proxy
    osmajorrelease:
        proxy
    osrelease:
        proxy
    osrelease_info:
        - proxy
    path:
        /usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin
    ps:
        ps -efH
    pythonexecutable:
        /usr/bin/python
    pythonpath:
        - /usr/bin
        - /root/src/napalm-eos
        - /root/src/aclgen
        - /usr/lib/python2.7
        - /usr/lib/python2.7/plat-x86_64-linux-gnu
        - /usr/lib/python2.7/lib-tk
        - /usr/lib/python2.7/lib-old
        - /usr/lib/python2.7/lib-dynload
        - /usr/local/lib/python2.7/dist-packages
        - /usr/lib/python2.7/dist-packages
        - /usr/lib/python2.7/dist-packages/git/ext/gitdb
        - /usr/lib/python2.7/dist-packages/gitdb/ext/async
        - /usr/lib/python2.7/dist-packages/gitdb/ext/smmap
    pythonversion:
        - 2
        - 7
        - 6
        - final
        - 0
    saltpath:
        /usr/lib/python2.7/dist-packages/salt
    saltversion:
        2016.11.3
    saltversioninfo:
        - 2016
        - 11
        - 3
        - 0
    serial:
    uptime:
        92092
    vendor:
        Arista
    version:
        4.16.9M-3799680.4169M
    virtual:
        VirtualBox
    zmqversion:
        4.0.5
```

### Output from "develop"
```
[root@saltmaster:~] 1 # salt --versions-report
Salt Version:
           Salt: 2016.11.0-965-g0b8a9c4
 
Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-110-generic
         system: Linux
        version: Ubuntu 14.04 trusty
[root@saltmaster:~] # salt veos1 grains.items
veos1:
    ----------
    cpuarch:
        x86_64
    dns:
        ----------
        domain:
        ip4_nameservers:
            - 10.0.2.3
        ip6_nameservers:
        nameservers:
            - 10.0.2.3
        options:
        search:
        sortlist:
    gpus:
    host:
        None
    hostname:
        veos1
    hwaddr_interfaces:
        ----------
        eth0:
            08:00:27:41:9a:fb
        eth1:
            08:00:27:27:fd:92
        lo:
            00:00:00:00:00:00
    id:
        veos1
    interfaces:
        - Ethernet1
        - Management1
    kernel:
        proxy
    kernelrelease:
        proxy
    locale_info:
        ----------
    machine_id:
        6d8476cdd65de59207caf74f58b883d8
    master:
        localhost
    mem_total:
        0
    model:
        vEOS
    nodename:
        saltmaster
    num_gpus:
        0
    optional_args:
        ----------
        config_lock:
            False
    os:
        None
    os_family:
        proxy
    osarch:
        x86_64
    osfinger:
        proxy-proxy
    osfullname:
        proxy
    osmajorrelease:
        proxy
    osrelease:
        proxy
    osrelease_info:
        - proxy
    path:
        /usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin
    ps:
        ps -efHww
    pythonexecutable:
        /usr/bin/python
    pythonpath:
        - /usr/bin
        - /root/src/napalm-eos
        - /root/src/aclgen
        - /usr/lib/python2.7
        - /usr/lib/python2.7/plat-x86_64-linux-gnu
        - /usr/lib/python2.7/lib-tk
        - /usr/lib/python2.7/lib-old
        - /usr/lib/python2.7/lib-dynload
        - /usr/local/lib/python2.7/dist-packages
        - /usr/lib/python2.7/dist-packages
    pythonversion:
        - 2
        - 7
        - 6
        - final
        - 0
    saltpath:
        /usr/lib/python2.7/dist-packages/salt
    saltversion:
        2016.11.0-965-g0b8a9c4
    saltversioninfo:
        - 2016
        - 11
        - 0
        - 0
    serial:
    uptime:
        92910
    username:
        admin
    vendor:
        Arista
    version:
        4.16.9M-3799680.4169M
    virtual:
        VirtualBox
    zmqversion:
        4.0.5
```

**Comment by bewing** [comment]
This causes issues in other execution modules, eg netacl, which relies on the grain:
```
[root@saltmaster:~] # salt veos1 netacl.load_term_config filter-name term-name source_address=1.2.3.4 destination_address=5.6.7.8 action=accept test=True debug=True
veos1:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1445, in _thread_return
        return_data = executor.execute()
      File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/utils/napalm.py", line 263, in func_wrapper
        return func(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/napalm_acl.py", line 431, in load_term_config
        platform = _get_capirca_platform()
      File "/usr/lib/python2.7/dist-packages/salt/modules/napalm_acl.py", line 93, in _get_capirca_platform
        os_ = __grains__['os'].lower()
    AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by mirceaulinic** [comment]
Thanks for reporting this @bewing - I will have a look later this week.

Can one of the maintainers assign this to me, please?

**Comment by gtmanfred** [comment]
Unfortunately we cannot assign issues to people not in the Members organization.

Thanks for taking a look at this @mirceaulinic

**Comment by bewing** [comment]
Looks like "os" and "host" are both None.  Both use _get_device_grain.

Strangely, username uses the same function, and it is returning correctly.

**Comment by mirceaulinic** [comment]
This should fix it: https://github.com/saltstack/salt/pull/39990

**Comment by bewing** [comment]
Appears so:
```
[root@saltmaster:~] 127 # salt --versions-report
Salt Version:
           Salt: 2016.11.0-968-g33cbc22
 
Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-110-generic
         system: Linux
        version: Ubuntu 14.04 trusty

[root@saltmaster:~] # salt veos1 grains.items
veos1:
    ----------
    cpuarch:
        x86_64
    dns:
        ----------
        domain:
        ip4_nameservers:
            - 10.0.2.3
        ip6_nameservers:
        nameservers:
            - 10.0.2.3
        options:
        search:
        sortlist:
    gpus:
    host:
        veos1
    hostname:
        veos1
    hwaddr_interfaces:
        ----------
        eth0:
            08:00:27:41:9a:fb
        eth1:
            08:00:27:d6:c6:51
        lo:
            00:00:00:00:00:00
    id:
        veos1
    interfaces:
        - Ethernet1
        - Management1
    kernel:
        proxy
    kernelrelease:
        proxy
    locale_info:
        ----------
    machine_id:
        6d8476cdd65de59207caf74f58b883d8
    master:
        localhost
    mem_total:
        0
    model:
        vEOS
    nodename:
        saltmaster
    num_gpus:
        0
    optional_args:
        ----------
        config_lock:
            False
    os:
        eos
    os_family:
        proxy
    osarch:
        x86_64
    osfinger:
        proxy-proxy
    osfullname:
        proxy
    osmajorrelease:
        proxy
    osrelease:
        proxy
    osrelease_info:
        - proxy
    path:
        /usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin
    ps:
        ps -efHww
    pythonexecutable:
        /usr/bin/python
    pythonpath:
        - /usr/bin
        - /root/src/napalm-eos
        - /root/src/aclgen
        - /usr/lib/python2.7
        - /usr/lib/python2.7/plat-x86_64-linux-gnu
        - /usr/lib/python2.7/lib-tk
        - /usr/lib/python2.7/lib-old
        - /usr/lib/python2.7/lib-dynload
        - /usr/local/lib/python2.7/dist-packages
        - /usr/lib/python2.7/dist-packages
    pythonversion:
        - 2
        - 7
        - 6
        - final
        - 0
    saltpath:
        /usr/lib/python2.7/dist-packages/salt
    saltversion:
        2016.11.0-968-g33cbc22
    saltversioninfo:
        - 2016
        - 11
        - 0
        - 0
    serial:
    uptime:
        104377
    username:
        admin
    vendor:
        Arista
    version:
        4.16.9M-3799680.4169M
    virtual:
        VirtualBox
    zmqversion:
        4.0.5

**Comment by gtmanfred** [comment]
Thanks all.  I will close this one the PR gets merged.

Thanks,
Daniel
