### ISSUE TITLE
UnboundLocalError: local variable 'ifcfg' referenced before assignment

### ISSUE THREAD

**Issue by oogali** [saltstack/salt#40036]
### Description of Issue/Question
I'm trying to define a new network alias (on the loopback interface), and I'm receiving a variable scoping exception.

### Setup
My state is as follows:
```
dev-loopback-ip:
  network.managed:
    - name: lo:1
    - onboot: yes
    - type: alias
    - bootproto: none
    - nickname: loopback
    - ipaddr: 127.0.0.2
    - netmask: 255.255.255.255
```

### Steps to Reproduce Issue
When I attempt to apply highstate from master to minion, I get the following:
```
          ID: dev-loopback-ip
    Function: network.managed
        Name: lo:1
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1745, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1702, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/network.py", line 315, in managed
                  new = __salt__['ip.build_interface'](name, type, enabled, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/modules/rh_ip.py", line 992, in build_interface
                  return _read_temp(ifcfg)
              UnboundLocalError: local variable 'ifcfg' referenced before assignment
     Started: 10:48:03.610853
    Duration: 1.925 ms
     Changes:
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
(Just for kicks, I upgraded from 2016.11.2 to 2016.11.3, and had the same issue on both versions)

```
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.24.0
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-57-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by oogali** [comment]
Minion's salt-call:
```
Salt Version:
           Salt: 2016.11.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.22.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

**Comment by gtmanfred** [comment]
I have submitted the following PR which will add alias to the list of iface_types

https://github.com/saltstack/salt/pull/40053

Thanks for reporting,
Daniel

**Comment by oogali** [comment]
Confirmed that this is working now (under CentOS 7).

    ----------
          ID: dev-loopback-ip
    Function: network.managed
        Name: lo:1
      Result: True
     Comment: Interface lo:1 added.
     Started: 15:38:17.575894
    Duration: 730.439 ms
     Changes:
              ----------
              interface:
                  Added network interface.
              status:
                  Interface lo:1 is up
