### ISSUE TITLE
VirtualBox Cloud Interface Not Working

### ISSUE THREAD

**Issue by grichmond-salt** [saltstack/salt#40063]
### Description of Issue/Question
The VirtualBox Cloud interfaces does not work with current versions of VirtualBox.

Test was performed on Ubuntu 16.04 with Salt 2016.11.2.  Also the VirtualBox SDK was installed.

With VirtualBox 5.0 installed, "salt-cloud -Q" works as expected.  However, attempting to launch a VM with "salt-cloud -p" results in the following error:

```
[WARNING ] Exceeded waiting time (60 seconds) to exectute <function vb_get_network_addresses at 0x7f48b82865f0>
umaster01:
    ----------
    OSTypeId:
        Ubuntu
    _stamp:
        2017-03-15T20:45:43.890123
    accessible:
        True
    description:
    event:
        created machine
    groups:
    id:
        fdb968dc-75ae-4fbf-a4fb-c329142cc2a1
    memorySize:
        384
    name:
        umaster01
    state:
        1
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 1063, in __global_logging_exception_handler
    exc_type, exc_value, exc_traceback
  File "/usr/lib/python2.7/logging/__init__.py", line 1193, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 310, in _log
    self, level, msg, args, exc_info=exc_info, extra=extra
  File "/usr/lib/python2.7/logging/__init__.py", line 1285, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 333, in makeRecord
    _msg = msg.decode(salt_system_encoding, 'replace')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
TypeError: 'NoneType' object is not callable
Original exception was:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: __import__ not found
Failed to log an error record
Original error follows:
Wrapping an interface object for the gateway failed
Traceback (most recent call last):
  File "/usr/lib/virtualbox/sdk/bindings/xpcom/python/xpcom/server/policy.py", line 204, in _MakeInterfaceParam_
    import xpcom.xpt
<type 'exceptions.ImportError'>: No module named xpt
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 1063, in __global_logging_exception_handler
    exc_type, exc_value, exc_traceback
  File "/usr/lib/python2.7/logging/__init__.py", line 1193, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 310, in _log
    self, level, msg, args, exc_info=exc_info, extra=extra
  File "/usr/lib/python2.7/logging/__init__.py", line 1285, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 333, in makeRecord
    _msg = msg.decode(salt_system_encoding, 'replace')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
TypeError: 'NoneType' object is not callable
Original exception was:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: __import__ not found
Failed to log an error record
Original error follows:
The exception handler _CallMethodException_ failed!
Traceback (most recent call last):
  File "/usr/lib/virtualbox/sdk/bindings/xpcom/python/xpcom/server/policy.py", line 321, in _CallMethodException_
    self._doHandleException("<building method repr>", sys.exc_info())
<type 'exceptions.NameError'>: global name 'sys' is not defined
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 1063, in __global_logging_exception_handler
    exc_type, exc_value, exc_traceback
  File "/usr/lib/python2.7/logging/__init__.py", line 1193, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 310, in _log
    self, level, msg, args, exc_info=exc_info, extra=extra
  File "/usr/lib/python2.7/logging/__init__.py", line 1285, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 333, in makeRecord
    _msg = msg.decode(salt_system_encoding, 'replace')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
TypeError: 'NoneType' object is not callable
Original exception was:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: __import__ not found
Failed to log an error record
Original error follows:
The function 'observe' failed
Traceback (most recent call last):
  File "/usr/lib/virtualbox/sdk/bindings/xpcom/python/xpcom/server/policy.py", line 273, in _CallMethod_
    return 0, func(*params)
  File "/usr/lib/virtualbox/sdk/bindings/xpcom/python/xpcom/components.py", line 229, in observe
    xpcom.client._shutdown()
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception AttributeError: "'NoneType' object has no attribute 'deinit'" in <bound method VirtualBoxManager.__del__ of <vboxapi.VirtualBoxManager object at 0x7f48b81d4050>> ignored
root@user-VirtualBox:/etc/salt/cloud.profiles.d#
```

Further, with VirtualBox 5.1, any "salt-cloud" call returns:
```
m=VBoxPython2_7 x=No module named VBoxPython2_7
m=VBoxPython2 x=No module named VBoxPython2
m=VBoxPython x=No module named VBoxPython
```

### Setup
- Ubuntu 16.04, 64 bit
- Install VirtualBox
- Install VirtualBox SDK

### Steps to Reproduce Issue
Execute salt-cloud calls, as described above.

### Versions Report
Salt Version:
           Salt: 2016.11.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-62-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by Ch3LL** [comment]
Was this working on older versions of virtualbox?

**Comment by grichmond-salt** [comment]
I do not know.  The customer request was recent (this week).  However, the original author of this module had a PDF for the SDK in the original repo, suggesting use of VirtualBox 5.0.4 during development of the module.

Link:
`https://github.com/LoveIsGrief/saltcloud-virtualbox-provider/blob/master/SDKRef.pdf`

**Comment by Ch3LL** [comment]
ping @LoveIsGrief would you mind looking here? Have you seen this behavior in this version?

**Comment by LoveIsGrief** [comment]
Hi @Ch3LL 

I currently do not have access to a Ubuntu 16.04 instance nor have I tried salt 2016 with virtualbox yet. I'll try and spin up a docker to with virtualbox in it (if that even works) to recreate the situation. If docker doesn't work, I'll have to try it on my trusty 14.04 :)

**Comment by magicalbob** [comment]
Hi. I've just tried starting a virtualbox with salt-cloud -p. I get this:

```
salt-cloud -p virtualbox-admin test-n1
[ERROR   ] There was a profile error: 0x8000ffff (The session is not locked (session state: Unlocked))
Error in sys.excepthook:
Traceback (most recent call last):
  File "/root/src/salt/salt/log/setup.py", line 1133, in __global_logging_exception_handler
    exc_type, exc_value, exc_traceback
  File "/usr/lib64/python2.7/logging/__init__.py", line 1175, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/root/src/salt/salt/log/setup.py", line 327, in _log
    self, level, msg, args, exc_info=exc_info, extra=extra
  File "/usr/lib64/python2.7/logging/__init__.py", line 1267, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/root/src/salt/salt/log/setup.py", line 350, in makeRecord
    _msg = msg.decode(salt_system_encoding, 'replace')
  File "/root/src/salt.virtualenv/lib64/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
AttributeError: 'NoneType' object has no attribute 'utf_8_decode'

Original exception was:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: __import__ not found
Failed to log an error record
Original error follows:
Wrapping an interface object for the gateway failed

Traceback (most recent call last):
  File "/usr/lib/virtualbox/sdk/bindings/xpcom/python/xpcom/server/policy.py", line 212, in _MakeInterfaceParam_
    import xpcom.xpt
<type 'exceptions.ImportError'>: No module named xpt
Error in sys.excepthook:
Traceback (most recent call last):
  File "/root/src/salt/salt/log/setup.py", line 1133, in __global_logging_exception_handler
    exc_type, exc_value, exc_traceback
  File "/usr/lib64/python2.7/logging/__init__.py", line 1175, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/root/src/salt/salt/log/setup.py", line 327, in _log
    self, level, msg, args, exc_info=exc_info, extra=extra
  File "/usr/lib64/python2.7/logging/__init__.py", line 1267, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/root/src/salt/salt/log/setup.py", line 350, in makeRecord
    _msg = msg.decode(salt_system_encoding, 'replace')
  File "/root/src/salt.virtualenv/lib64/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
AttributeError: 'NoneType' object has no attribute 'utf_8_decode'

Original exception was:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: __import__ not found
Failed to log an error record
Original error follows:
The exception handler _CallMethodException_ failed!

Traceback (most recent call last):
  File "/usr/lib/virtualbox/sdk/bindings/xpcom/python/xpcom/server/policy.py", line 335, in _CallMethodException_
    self._doHandleException("<building method repr>", sys.exc_info())
  File "/usr/lib/virtualbox/sdk/bindings/xpcom/python/xpcom/server/policy.py", line 312, in _doHandleException
    logger.exception("Unhandled exception calling '%s'", func_name)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1182, in exception
    self.error(msg, *args, **kwargs)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1175, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/root/src/salt/salt/log/setup.py", line 327, in _log
    self, level, msg, args, exc_info=exc_info, extra=extra
  File "/usr/lib64/python2.7/logging/__init__.py", line 1267, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/root/src/salt/salt/log/setup.py", line 350, in makeRecord
    _msg = msg.decode(salt_system_encoding, 'replace')
  File "/root/src/salt.virtualenv/lib64/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'utf_8_decode'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/root/src/salt/salt/log/setup.py", line 1133, in __global_logging_exception_handler
    exc_type, exc_value, exc_traceback
  File "/usr/lib64/python2.7/logging/__init__.py", line 1175, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/root/src/salt/salt/log/setup.py", line 327, in _log
    self, level, msg, args, exc_info=exc_info, extra=extra
  File "/usr/lib64/python2.7/logging/__init__.py", line 1267, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/root/src/salt/salt/log/setup.py", line 350, in makeRecord
    _msg = msg.decode(salt_system_encoding, 'replace')
  File "/root/src/salt.virtualenv/lib64/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
AttributeError: 'NoneType' object has no attribute 'utf_8_decode'

Original exception was:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: __import__ not found
Failed to log an error record
Original error follows:
The function 'observe' failed

Traceback (most recent call last):
  File "/usr/lib/virtualbox/sdk/bindings/xpcom/python/xpcom/server/policy.py", line 281, in _CallMethod_
    return 0, func(*params)
  File "/usr/lib/virtualbox/sdk/bindings/xpcom/python/xpcom/components.py", line 233, in observe
    xpcom.client._shutdown()
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
```
salt-cloud -Q seems to work fine, listing yaml of virtual boxes.

`Salt Version:
            Salt: 2016.11.4
 
Dependency Versions:
 Apache Libcloud: 0.20.1
            cffi: 1.6.0
        cherrypy: Not Installed
        dateutil: Not Installed
       docker-py: Not Installed
           gitdb: Not Installed
       gitpython: Not Installed
           ioflo: Not Installed
          Jinja2: 2.8
         libgit2: Not Installed
         libnacl: Not Installed
        M2Crypto: 0.21.1
            Mako: 0.8.1
    msgpack-pure: Not Installed
  msgpack-python: 0.4.8
    mysql-python: Not Installed
       pycparser: 2.14
        pycrypto: 2.6.1
    pycryptodome: 3.4.3
          pygit2: Not Installed
          Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
    python-gnupg: Not Installed
          PyYAML: 3.11
           PyZMQ: 15.3.0
            RAET: Not Installed
           smmap: Not Installed
         timelib: Not Installed
         Tornado: 4.2.1
             ZMQ: 4.1.4
 
System Versions:
            dist: centos 7.3.1611 Core
         machine: x86_64
         release: 3.10.0-514.16.1.el7.x86_64
          system: Linux
         version: CentOS Linux 7.3.1611 Core`

I got the same result using salt-cloud 2017.5.0-1010-gdcb0d63 and salt-cloud 2016.11.4 (Carbon).

**Comment by fizmat** [comment]
I tried to use Virtualbox and noticed these errors. I don't know about the actual issue, but most of the error text seem to be noise generated at the end of execution and related to xpcom (cross-platform COM). Virtualbox is using Mozilla code from 2008 https://www.virtualbox.org/browser/vbox/trunk/src/libs/xpcom18a4/python so I'm not sure what's the correct procedure to fix this.

The initial point is at the end of [components.py](https://www.virtualbox.org/browser/vbox/trunk/src/libs/xpcom18a4/python/components.py) in function `observe` that attempts to free some resources at the end of program execution and fails. I don't know much about xpcom, so fixing this is beyond me.

As it happens at the end of execution, some imported modules are already unloaded (notably codecs to decode utf8). So attempting to log the error fails and generates more error messages. I tried to add some try/except to check for it and fail less ugly, but it did not work.

These errors are generated even if there is no actual error with the cloud operation.

**Comment by larytet** [comment]
I tried to use vboxapi directly

```
import vboxapi
vboxMgr = vboxapi.VirtualBoxManager(None, None)
m=VBoxPython3_6m x=dynamic module does not define module export function (PyInit_VBoxPython3_6m)
m=VBoxPython3m x=No module named 'VBoxPython3m'
#  I hope I am doing it right 
vbox = vboxMgr.getVirtualBox()
vbox.findMachine('win8')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    vbox.findMachine('win8')
  File "<XPCOMObject method 'findMachine'>", line 3, in findMachine
TypeError: internal error in PyXPCOM, parameter must be a bytes object

```

**Comment by aphor** [comment]
VirtualBox XPCOM code is pretty crusty. It may be smarter to wrap the CLI tools like "VBoxManage."
