### ISSUE TITLE
Azure Arm - 'virtual_network_name'

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#40074]
### Description of Issue/Question
I was trying provisioning on Azure and following is the error,

[ERROR   ] There was a profile error: Parameter 'virtual_network_name' can not be None.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 284, in run
    self.config.get('names')
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1458, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1288, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/azurearm.py", line 1099, in create
    'wait_for_ip_interval_multiplier', vm_, __opts__, default=1),
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 2371, in wait_for_ip
    data = update_callback(*update_args, **update_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/azurearm.py", line 1074, in _query_ip_address
    data = request_instance(kwargs=vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/azurearm.py", line 887, in request_instance
    iface_data = create_interface(kwargs=vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/azurearm.py", line 772, in create_interface
    subnet_name=kwargs['subnet'],
  File "/usr/local/lib/python2.7/dist-packages/azure/mgmt/network/operations/subnets_operations.py", line 154, in get
    'virtualNetworkName': self._serialize.url("virtual_network_name", virtual_network_name, 'str'),
  File "/usr/local/lib/python2.7/dist-packages/msrest/serialization.py", line 309, in url
    data = self.validate(data, name, required=True, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/msrest/serialization.py", line 376, in validate
    raise ValidationError("required", name, True)
ValidationError: Parameter 'virtual_network_name' can not be None.

I have specified the parameter in providers file also i tried it by placing in profiles file. Both the cases gave me the same error.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2016.11.2

Dependency Versions:
           cffi: 1.9.1
       cherrypy: 3.2.2
       dateutil: 2.6.0
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.16.0-30-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by techhat** [comment]
Hi @sumeetisp. Configure the `virtual_network_name` as `network`. You can also define the `subnet` to use, and if the network is in a different resource group than the VM, you can define a `network_resource_group`.

**Comment by sumeetisp** [comment]
So you mean to say i should define it as network: instead of virtual_network_name:  ?

**Comment by techhat** [comment]
Yes.

**Comment by sumeetisp** [comment]
Thank you Joseph. I replaced as u said now it is asking resource group, I
will update and close this thread soon.



On Mar 16, 2017 21:02, "Joseph Hall" <notifications@github.com> wrote:

Yes.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/saltstack/salt/issues/40074#issuecomment-287095050>,
or mute
the thread

**Comment by sumeetisp** [comment]
Worked, Tx.
