### ISSUE TITLE
Problems with gitfs on Debian Jessie

### ISSUE THREAD

**Issue by colttt** [saltstack/salt#40083]
### Description of Issue/Question
Hello when i try to run salt-run fileserver.update -l debug 2>&1 i got the following error, I thought there i no bug anymore in GitPython >0.3.0
```
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] LazyLoaded fileserver.update
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Guessing ID. The id can be explicitly set in /etc/salt/minion
[DEBUG   ] Found minion id from generate_minion_id(): salt.secret.de
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] /etc/resolv.conf: The domain and search keywords are mutually exclusive.
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event: tag = salt/run/20170316162817846362/new; data = {'fun': 'runner.fileserver.update', 'fun_args': [], 'jid': '20170316162817846362', 'user': 'root', '_stamp': '2017-03-16T15:28:18.199014'}
[DEBUG   ] gitpython gitfs_provider enabled
[DEBUG   ] LazyLoaded git.envs
[DEBUG   ] Updating git fileserver cache
[DEBUG   ] Set update lock for gitfs remote 'ssh://gogs@it-git.secret.de:gogsadmin/salt-states.git'
[DEBUG   ] Fetching gitfs remote 'ssh://gogs@it-git.secret.de:gogsadmin/salt-states.git'
[DEBUG   ] Removed update lock for gitfs remote 'ssh://gogs@it-git.secret.de:gogsadmin/salt-states.git'
[ERROR   ] Exception ''Error when fetching: fatal: Could not read from remote repository.' returned exit status 2: None' caught while fetching gitfs remote 'ssh://gogs@it-git.secret.de:gogsadmin/salt-states.git'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 2330, in fetch_remotes
    if repo.fetch():
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 477, in fetch
    return self._fetch()
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 885, in _fetch
    fetch_results = origin.fetch()
  File "/usr/lib/python2.7/dist-packages/git/remote.py", line 593, in fetch
    return self._get_fetch_info_from_stderr(proc, progress or RemoteProgress())
  File "/usr/lib/python2.7/dist-packages/git/remote.py", line 529, in _get_fetch_info_from_stderr
    raise GitCommandError(("Error when fetching: %s" % line,), 2)
GitCommandError: 'Error when fetching: fatal: Could not read from remote repository.' returned exit status 2: None
[DEBUG   ] Sending event: tag = salt/run/20170316162817846362/ret; data = {'fun_args': [], 'jid': '20170316162817846362', 'return': True, 'success': True, '_stamp': '2017-03-16T15:28:18.356809', 'user': 'root', 'fun': 'runner.fileserver.update'}
[DEBUG   ] LazyLoaded nested.output
True
[DEBUG   ] LazyLoaded local_cache.prep_jid
[INFO    ] Runner completed: 20170316162817846362
[DEBUG   ] Runner return: True
```

### Versions Report
```
salt --versions-report
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.7 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.7 
```

**Comment by Ch3LL** [comment]
@colttt I cannot replicate this on debian 8 with the same gitpython version as you.

Can you try my master config and see if you still git the same error:

```
gitfs_remotes:
  - https://github.com/Ch3LL/Ch3LLScripts.git:
    - root: salt/states
fileserver_backend:
  - roots
  - git
gitfs_provider: gitpython
```

**Comment by colttt** [comment]
Hello,
thanks for you help! you config works fine https and ssh.

did I have an error in my config?
```
fileserver_backend:
  - git
gitfs_provider: gitpython
gitfs_remotes:
   - ssh://gogs@it-git.secret.de:gogsadmin/salt-states.git
ext_pillar:
   - git: master ssh://gogs@it-git.secret.de:gogsadmin/salt-pillars.git
```
