### ISSUE TITLE
profile fields in azurearm salt-cloud need to be actualized to sources

### ISSUE THREAD

**Issue by podstava** [saltstack/salt#40084]
### Description of Issue/Question
profile fields in azurearm salt-cloud need to be actualized to sources
in docs: virtual_network_name
in sources:  network

maybe some more fields. Need to research
                    
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
used salt-cloud develop branch

**Comment by Ch3LL** [comment]
@podstava i'm not seeing virtual_network_name in the azurearm docs only in azure docs. Can you point me to where you are seeing this.

**Comment by podstava** [comment]
You're right, my fault. but i think it must be documented anyway. It doesn't work without profile configs like these: 
```
azure-ubuntu:
  provider: azure-arm
  image: Canonical|UbuntuServer|14.04.5-LTS|latest
  size: Standard_A2_v2
  location: 'West US'
  ssh_username: azureuser
  ssh_password: verybadpass
  network_resource_group: testazure-rg
  resource_group: testazure-rg
  network: testazure-vnet
  subnet: testazure-subnet
```
Also i've got a new error while creating vm via azurearm:
I'm running `salt-cloud -l debug -p azure-ubuntu azure-ubuntu`.
```
[ERROR   ] There was a profile error: 'NetworkInterface' object has no attribute 'get'
Traceback (most recent call last):
  File "/home/podstava/PycharmProjects/customer-be/.env/lib/python3.5/site-packages/salt/utils/msazure.py", line 194, in object_to_dict
    if inspect.isclass(obj) or 'class' in str(type(obj.__dict__.get(item))):
AttributeError: 'bool' object has no attribute '__dict__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/podstava/PycharmProjects/customer-be/.env/lib/python3.5/site-packages/salt/utils/msazure.py", line 195, in object_to_dict
    ret[item] = object_to_dict(obj.__dict__[item])
  File "/home/podstava/PycharmProjects/customer-be/.env/lib/python3.5/site-packages/salt/utils/msazure.py", line 201, in object_to_dict
    ret[item] = obj.get(item)
AttributeError: 'bool' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/podstava/PycharmProjects/customer-be/.env/lib/python3.5/site-packages/salt/cloud/cli.py", line 284, in run
    self.config.get('names')
  File "/home/podstava/PycharmProjects/customer-be/.env/lib/python3.5/site-packages/salt/cloud/__init__.py", line 1444, in run_profile
    ret[name] = self.create(vm_)
  File "/home/podstava/PycharmProjects/customer-be/.env/lib/python3.5/site-packages/salt/cloud/__init__.py", line 1274, in create
    output = self.clouds[func](vm_)
  File "/home/podstava/PycharmProjects/customer-be/.env/lib/python3.5/site-packages/salt/cloud/clouds/azurearm.py", line 1185, in create
    'wait_for_ip_interval_multiplier', vm_, __opts__, default=1),
  File "/home/podstava/PycharmProjects/customer-be/.env/lib/python3.5/site-packages/salt/utils/cloud.py", line 2413, in wait_for_ip
    data = update_callback(*update_args, **update_kwargs)
  File "/home/podstava/PycharmProjects/customer-be/.env/lib/python3.5/site-packages/salt/cloud/clouds/azurearm.py", line 1160, in _query_ip_address
    data = request_instance(kwargs=vm_)
  File "/home/podstava/PycharmProjects/customer-be/.env/lib/python3.5/site-packages/salt/cloud/clouds/azurearm.py", line 959, in request_instance
    iface_data = create_interface(kwargs=vm_)
  File "/home/podstava/PycharmProjects/customer-be/.env/lib/python3.5/site-packages/salt/cloud/clouds/azurearm.py", line 908, in create_interface
    return show_interface(kwargs=kwargs)
  File "/home/podstava/PycharmProjects/customer-be/.env/lib/python3.5/site-packages/salt/cloud/clouds/azurearm.py", line 705, in show_interface
    data = object_to_dict(iface)
  File "/home/podstava/PycharmProjects/customer-be/.env/lib/python3.5/site-packages/salt/utils/msazure.py", line 201, in object_to_dict
    ret[item] = obj.get(item)
AttributeError: 'NetworkInterface' object has no attribute 'get'
```
Seems like it an error in object_to_dict method in msazure.py. Or maybe I'm doing something wrong? I'll be glad if you'll help me with it.
Thanks

**Comment by Ch3LL** [comment]
Agreed this needs to be documnted for network. I am not seeing this in the azure arm docs [here](https://docs.saltstack.com/en/latest/topics/cloud/azurearm.html)

Concerning your other issue ping @techhat do you see where @podstava might need ot change a configuration to get azure arm setup correctly? Or any other ideas?

**Comment by techhat** [comment]
It should be documented. But I'm not necessarily in agreement with making all of our variables match the upstream SDK/API; some of those names are way too long to be reasonable. I'll go through today and update the ARM docs.

**Comment by techhat** [comment]
#40564 should correct discrepancies in the documentation.
