### ISSUE TITLE
chocolatey.installed failing on a specific package for unknown reason

### ISSUE THREAD

**Issue by kedare** [saltstack/salt#40104]
### Description of Issue/Question
When trying to install a specific package (PowershellGAC) using chocholatey, Salt fails with an unhelpful message, installing the package manually works fine (choco install PowershellGAC)

### Setup

```
Install Powershell GAC Tools:
   chocolatey.installed:
    - names:
      - PowerShellGAC
```

### Steps to Reproduce Issue
Run the state on a Windows Server (tested on 2016)

It results as : 

```
----------
          ID: Install Powershell GAC Tools
    Function: chocolatey.installed
        Name: PowerShellGAC
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "c:\salt\bin\lib\site-packages\salt\state.py", line 1746, in call
                  **cdata['kwargs'])
                File "c:\salt\bin\lib\site-packages\salt\loader.py", line 1703, in wrapper
                  return f(*args, **kwargs)
                File "c:\salt\bin\lib\site-packages\salt\states\chocolatey.py", line 108, in installed
                  package_args=package_args)}
                File "c:\salt\bin\lib\site-packages\salt\modules\chocolatey.py", line 426, in install
                  raise CommandExecutionError(err)
              CommandExecutionError: Running chocolatey failed:
     Started: 11:08:04.156000
    Duration: 6719.0 ms
     Changes:
```

### Versions Report

```
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.10.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

```
PS C:\Users\Administrator> salt-call.bat --version
salt-call 2016.11.3 (Carbon)
```

**Comment by Ch3LL** [comment]
It should be adding an error message in the logs according to the code [here](https://github.com/saltstack/salt/blob/v2016.11.3/salt/modules/chocolatey.py#L424). Do you see anything useful in the minion log there?
