### ISSUE TITLE
Problems with netacl.load_filter_config, load_policy_config, etc

### ISSUE THREAD

**Issue by bewing** [saltstack/salt#40137]
### Setup
```
==> master: Running provisioner: salt...
Copying salt minion config to vm.
Copying salt master config to vm.
Uploading minion keys.
Uploading master keys.
Checking if salt-minion is installed
salt-minion was not found.
Checking if salt-call is installed
salt-call was not found.
Checking if salt-master is installed
salt-master was not found.
Using Bootstrap Options:  -P -c /tmp -F -c /tmp -k /tmp/minion-seed-keys -M git develop
```
Provision salt master and minion via vagrant from git develop.  Configure an EOS napalm_proxy minion on the local master.  Confirm test.ping.
 
### Steps to Reproduce Issue
`salt veos1 netacl.load_filter_config filter-name terms='{"term1": {"source_address": "4.3.2.1", "destination_address": "1.2.3.4", "action"="accept"}}' test=True debug=True`

```
2017-03-18 13:52:24,471 [salt.minion                                                    ][INFO    ][21597] User root Executing command netacl.load_filter_config with jid 20170318135224468263
2017-03-18 13:52:24,471 [salt.minion                                                    ][DEBUG   ][21597] Command details {'tgt_type': 'glob', 'jid': '20170318135224468263', 'tgt': 'veos1', 'ret': '', 'user': 'root', 'arg': ['filter-name', {'test': True, 'debug': True, 'terms': '{"term1": {"source_address": "4.3.2.1", "destination_address": "1.2.3.4", "action"="accept"}}', '__kwarg_
_': True}], 'fun': 'netacl.load_filter_config'}
2017-03-18 13:52:24,472 [salt.minion                                                    ][INFO    ][21597] Starting a new job with PID 21597
2017-03-18 13:52:24,472 [salt.minion                                                    ][WARNING ][21597] Passed invalid arguments to netacl.load_filter_config: load_filter_config() got an unexpected k
eyword argument '__pub_user'
<snip docstring>
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1445, in _thread_return
    return_data = executor.execute()
  File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 28, in execute
    return self.func(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/utils/napalm.py", line 333, in func_wrapper
    return func(*args, **kwargs)
TypeError: load_filter_config() got an unexpected keyword argument '__pub_user'
2017-03-18 13:52:24,472 [salt.minion                                                    ][DEBUG   ][21597] Minion return retry timer set to 8 seconds (randomized)
2017-03-18 13:52:24,472 [salt.minion                                                    ][INFO    ][21597] Returning information for job: 20170318135224468263
```
### Versions Report
```[root@saltmaster:~] # salt --versions-report
Salt Version:
           Salt: 2016.11.0-1011-gc4f25ab
 
Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-110-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```
```
[root@saltmaster:~] # pip freeze | grep -E "napalm|capirc"
-e git+git@github.com:google/capirca.git@0ec49067ecf09c3c9fc616f9ff738e533962bcc6#egg=capirca-master
napalm-base==0.23.1
napalm-eos==0.5.6
napalm-junos==0.6.5
```

**Comment by bewing** [comment]
@mirceaulinic

**Comment by Ch3LL** [comment]
@bewing looks like the pr from @mirceaulinic does resolve your issue. Feel free to close this once the PR is reviewed and merged or we can.
