### ISSUE TITLE
state.netacl.managed does not correctly handle options

### ISSUE THREAD

**Issue by bewing** [saltstack/salt#40163]
### Setup
`/srv/pillar/veos1.sls`
```yaml
mcast-acl:
  a-mcast:
    options:
      - standard
    term1:
      address: 233.252.21.1
      action: accept
    term2:
      address: 233.252.21.2
      action: accept
  b-mcast:
    options:
      - standard
    term1:
      address: 233.252.21.129
      action: accept
    term2:
      address: 233.252.21.130
      action: accept
```
`/srv/salt/router/acl.sls`
```yaml
{% set fw_filters = pillar.get('mcast-acl', {}) -%}
test:
  netacl.managed:
    - filters: {{ fw_filters }}
```

### Steps to Reproduce Issue
```
[root:/srv/salt] # salt veos1 state.sls router.acl
veos1:
----------
          ID: test
    Function: netacl.managed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1821, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1729, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/netacl.py", line 894, in managed
                  debug=debug)
                File "/usr/lib/python2.7/dist-packages/salt/utils/napalm.py", line 333, in func_wrapper
                  return func(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/napalm_acl.py", line 811, in load_policy_config
                  revision_date_format=revision_date_format)
                File "/usr/lib/python2.7/dist-packages/salt/modules/capirca_acl.py", line 1076, in get_policy_config
                  merge_pillar=merge_pillar)
                File "/usr/lib/python2.7/dist-packages/salt/modules/capirca_acl.py", line 461, in _get_policy_object
                  **term_fields)
              TypeError: _get_term_object() argument after ** must be a mapping, not list
     Started: 19:17:49.241343
    Duration: 283.183 ms
     Changes:

Summary for veos1
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time: 283.183 ms
ERROR: Minions returned with non-zero exit code
```
```
2017-03-20 19:17:49,240 [salt.loaded.int.render.yaml                                    ][DEBUG   ][20035] Results of YAML rendering:
OrderedDict([('test', OrderedDict([('netacl.managed', [OrderedDict([('filters', OrderedDict([("u'a-mcast'", OrderedDict([("u'options'", ["u'standard'"]), ("u'term1'", OrderedDict([("u'action'", "u'accept'"), ("u'address'", "u'233.252.21.1'")])), ("u'term2'", OrderedD
ict([("u'action'", "u'accept'"), ("u'address'", "u'233.252.21.2'")]))])), ("u'b-mcast'", OrderedDict([("u'options'", ["u'standard'"]), ("u'term1'", OrderedDict([("u'action'", "u'accept'"), ("u'address'", "u'233.252.21.129'")])), ("u'term2'", OrderedDict([("u'action'"
, "u'accept'"), ("u'address'", "u'233.252.21.130'")]))]))]))])])]))])
```
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
[root:/srv/salt] # salt --versions-report
Salt Version:
           Salt: 2016.11.0-1014-g712240c

Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-112-generic
         system: Linux
        version: Ubuntu 14.04 trusty

```

**Comment by bewing** [comment]
@mirceaulinic

**Comment by mirceaulinic** [comment]
Just tried this and it seems that we should not rely on the default Python serialiser.

Just add `| json` in your SLS:

```jinja
{%- set fw_filters = pillar.get('mcast-acl', {}) -%}
test:
  netacl.managed:
    - filters: {{ fw_filters | json }}
```

And should work. If that's the case, I would like to ask you to submit a PR to put a note in the docs, this state seems to be more sensible on this. Also, please update the examples.Thanks!

**Comment by bewing** [comment]
Confirmed that running the pillar through the json serializer resolves my issue.  Will submit PR updating documentation and examples.

**Comment by mirceaulinic** [comment]
Great! Thanks @bewing
