### ISSUE TITLE
Cloud roster doesn't work

### ISSUE THREAD

**Issue by sergeizv** [saltstack/salt#40251]
### Description of Issue/Question

Despite #31005 was closed, the cloud roster still doesn't work.

### Setup

salt-cloud config file:
```
update_cachedir: True
```

### Steps to Reproduce Issue

1) Create a VM named 'foo' on EC2 or a cloud provider of choice.

2) Try to connect to it with salt-ssh using the cloud roster:

```
(py2-env) salt-test@tommynaut:~> salt-ssh -l debug --roster=cloud -i foo -r 'uname -a'
...
Process MultiprocessingProcess-7:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/salt-test/salt/salt/utils/process.py", line 647, in _run
    return self._original_run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/salt-test/salt/salt/client/ssh/__init__.py", line 416, in handle_routine
    **target)
  File "/home/salt-test/salt/salt/client/ssh/__init__.py", line 773, in __init__
    self.shell = salt.client.ssh.shell.Shell(opts, **args)
  File "/home/salt-test/salt/salt/client/ssh/shell.py", line 70, in __init__
    self.host = host.strip('[]')
AttributeError: 'NoneType' object has no attribute 'strip'
[ERROR   ] Target 'tgt' did not return any data, probably due to an error.
[DEBUG   ] LazyLoaded nested.output
tgt:
    Target 'tgt' did not return any data, probably due to an error.
```

### Versions Report
```
Salt Version:
           Salt: 2016.11.3-93-gc403762
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.0
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 03 2017, 17:41:54) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.6
 
System Versions:
           dist:   
        machine: x86_64
        release: 4.9.11-1-default
         system: Linux
        version: Not Installed

```

**Comment by gtmanfred** [comment]
Please see my comment here https://github.com/saltstack/salt/pull/40201#issuecomment-288732753

If you could check if this is fixed in develop, we can backport those changes.

Thanks,
Daniel

**Comment by sergeizv** [comment]
It's broken as well on develop, but in a different way:
```
(py2-env) salt-test@tommynaut:~> salt-ssh -l debug --roster=cloud -i bar -r 'uname -a'
...
Traceback (most recent call last):
  File "/home/salt-test/py2-env/bin/salt-ssh", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/salt-test/salt/scripts/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/home/salt-test/salt/salt/scripts.py", line 416, in salt_ssh
    client.run()
  File "/home/salt-test/salt/salt/cli/ssh.py", line 20, in run
    ssh = salt.client.ssh.SSH(self.config)
  File "/home/salt-test/salt/salt/client/ssh/__init__.py", line 225, in __init__
    self.tgt_type)
  File "/home/salt-test/salt/salt/roster/__init__.py", line 103, in targets
    targets.update(self.rosters[f_str](tgt, tgt_type))
  File "/home/salt-test/salt/salt/roster/cloud.py", line 42, in targets
    minions = __runner__['cache.cloud'](tgt)
  File "/home/salt-test/salt/salt/runners/cache.py", line 392, in cloud
    cloud_cache = __utils__['cloud.list_cache_nodes_full'](opts=opts, provider=provider)
KeyError: 'cloud.list_cache_nodes_full'
```
There are a number of issues on develop (not only the dunder). I've fixed them and about to submit a PR today.

**Comment by gtmanfred** [comment]
hrm, that function is here https://github.com/saltstack/salt/blob/develop/salt/utils/cloud.py#L2714

**Comment by sergeizv** [comment]
Just give me 10 minutes to finish a cup of tea and submit a PR on that, ok? :-)
