### ISSUE TITLE
Feature-Request: ‘--force’ switch for `lvm.pv_present` 

### ISSUE THREAD

**Issue by rickh563** [saltstack/salt#40314]
### Description of Issue/Question - Short

* Create an ‘--force’ switch for `lvm.pv_present` to overwrite an existing LVM signature.

### Setup & Detailed Description  & Steps to Reproduce Issue

I'm using the salt-minion running on RHEL 6/7 in version 2016.3.4-1.el7. 
I have set up a lvm-state to add a Disk to LVM. On the operating system this is usually done using "pvcreate <disk>" or adding the switch "-f" if it has been used before to overwrite an existing LVM signature.

The state I use only works if there is no signature detected on the disk. I have tried to add this "-f" switch, but salt doesn't seem to make use of it.

rhel_basicpillar_lvmpv_/dev/sdd_present: 
lvm.pv_present: 
- name: /dev/sdd 
- owerwrite: false 
- kwargs: -f

Setting the minion to debug loglevel indicates that no "-f" switch is used. 

````
2017-03-21 13:24:57,327 [salt.state ][INFO ][61241] Running state [/dev/sdd] at time 13:24:57.327282 
2017-03-21 13:24:57,327 [salt.state ][INFO ][61241] Executing state lvm.pv_present for /dev/sdd 
2017-03-21 13:24:57,328 [salt.loaded.int.module.cmdmod][INFO ][61241] Executing command ['pvdisplay', '-c', '/dev/sdd'] in directory '/root' 
2017-03-21 13:24:57,398 [salt.loaded.int.module.cmdmod][ERROR ][61241] Command '['pvdisplay', '-c', '/dev/sdd']' failed with return code: 5 
2017-03-21 13:24:57,398 [salt.loaded.int.module.cmdmod][ERROR ][61241] stderr: Failed to find physical volume "/dev/sdd". 
2017-03-21 13:24:57,398 [salt.loaded.int.module.cmdmod][ERROR ][61241] retcode: 5 
2017-03-21 13:24:57,399 [salt.loaded.int.module.cmdmod][INFO ][61241] Executing command ['pvdisplay', '-c', '/dev/sdd'] in directory '/root' 
2017-03-21 13:24:57,463 [salt.loaded.int.module.cmdmod][ERROR ][61241] Command '['pvdisplay', '-c', '/dev/sdd']' failed with return code: 5 
2017-03-21 13:24:57,464 [salt.loaded.int.module.cmdmod][ERROR ][61241] stderr: Failed to find physical volume "/dev/sdd". 
2017-03-21 13:24:57,464 [salt.loaded.int.module.cmdmod][ERROR ][61241] retcode: 5 
2017-03-21 13:24:57,465 [salt.loaded.int.module.cmdmod][INFO ][61241] Executing command ['pvcreate', '/dev/sdd'] in directory '/root' 
2017-03-21 13:24:57,577 [salt.loaded.int.module.cmdmod][ERROR ][61241] Command '['pvcreate', '/dev/sdd']' failed with return code: 5 
2017-03-21 13:24:57,577 [salt.loaded.int.module.cmdmod][ERROR ][61241] stderr: WARNING: dos signature detected on /dev/sdd at offset 510. Wipe it? [y/n]: [n] 
Aborted wiping of dos. 
1 existing signature left on the device. 
2017-03-21 13:24:57,577 [salt.loaded.int.module.cmdmod][ERROR ][61241] retcode: 5 
2017-03-21 13:24:57,577 [salt.state ][ERROR ][61241] An exception occurred in this state: Traceback (most recent call last): 
File "/usr/lib/python2.7/site-packages/salt/state.py", line 1733, in call 
**cdata['kwargs']) 
File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1653, in wrapper 
return f(*args, **kwargs) 
File "/usr/lib/python2.7/site-packages/salt/states/lvm.py", line 66, in pv_present 
changes = __salt__['lvm.pvcreate'](name, **kwargs) 
File "/usr/lib/python2.7/site-packages/salt/modules/linux_lvm.py", line 246, in pvcreate 
raise CommandExecutionError(out.get('stderr')) 
CommandExecutionError: WARNING: dos signature detected on /dev/sdd at offset 510. Wipe it? [y/n]: [n] 
Aborted wiping of dos. 
1 existing signature left on the device.
````

The state failes in this case.

**Comment by rickh563** [comment]
ZD-1267
