### ISSUE TITLE
saltstack ... : [ERROR ] Unable to fetch SSH-based gitfs 

### ISSUE THREAD

**Issue by nicholashoule** [saltstack/salt#40335]
### Description of Issue/Question
**Issue:** (Would enjoy a git backed SaltServer.)

- [2016.11.3] Fresh install of SaltStack 

- [0.25.0] http://www.pygit2.org/install.html#quick-install

- Compiled libgit2 with libssl and libssh2 to fix HTTPS/SSH issue

**Error:**
`Mar 27 10:30:16 saltstack salt-master[30215]: [ERROR   ] Unable to fetch SSH-based gitfs remote 'git@gitlab.com:181gaming/saltstack.git'. ...You may need to add ssh:// to the repo string or libgit2 must be compiled with libssh2 to support SSH authentication.
`

### Setup
```
# Git File Server Backend Configuration
#
# Optional parameter used to specify the provider to be used for gitfs. Must
# be one of the following: pygit2, gitpython, or dulwich. If unset, then each
# will be tried in that same order, and the first one with a compatible
# version installed will be the provider that is used.
gitfs_provider: pygit2

# Along with gitfs_password, is used to authenticate to HTTPS remotes.
gitfs_user: ''

# Along with gitfs_user, is used to authenticate to HTTPS remotes.
# This parameter is not required if the repository does not use authentication.
#gitfs_password: ''

# By default, Salt will not authenticate to an HTTP (non-HTTPS) remote.
# This parameter enables authentication over HTTP. Enable this at your own risk.
#gitfs_insecure_auth: False

# Along with gitfs_privkey (and optionally gitfs_passphrase), is used to
# authenticate to SSH remotes. This parameter (or its per-remote counterpart)
# is required for SSH remotes.
#gitfs_pubkey: '/root/.ssh/id_rsa_salt.pub'

# Along with gitfs_pubkey (and optionally gitfs_passphrase), is used to
# authenticate to SSH remotes. This parameter (or its per-remote counterpart)
# is required for SSH remotes.
#gitfs_privkey: '/root/.ssh/id_rsa_salt'

# This parameter is optional, required only when the SSH key being used to
# authenticate is protected by a passphrase.
gitfs_passphrase: '...'

# When using the git fileserver backend at least one git remote needs to be
# defined. The user running the salt master will need read access to the repo.
#
# The repos will be searched in order to find the file requested by a client
# and the first repo to have the file will return it.
# When using the git backend branches and tags are translated into salt
# environments.
# Note: file:// repos will be treated as a remote, so refs you want used must
# exist in that repo as *local* refs.
gitfs_remotes:
  - git@gitlab.com:181gaming/saltstack.git:
    - pubkey: /root/.ssh/id_rsa_salt.pub
    - privkey: /root/.ssh/id_rsa_salt
    - passphrase: ...
    - root: salt/git
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report

```
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: 0.24.0
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-66-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by gtmanfred** [comment]
Can you provide me with a salt state file with the setup for this so that I can make sure I replicate it?  Or if you want, a Vagrantfile or docker-compose file that mirrors the environment?

@terminalmage do you happen to have a setup with the newest pygit2 that you could test this on?

Thanks,
Daniel

**Comment by terminalmage** [comment]
I do not.

@nicholashoule You have conflicting information in your report. You say at the beginning that you installed 0.25.0 of pygit2, but the versions report shows 0.24.0. Please let me know the _exact_ versions of pygit2 and libgit2 installed. For example:

```
% python -c 'import pygit2; print(pygit2.__version__, pygit2.LIBGIT2_VERSION)'
('0.24.2', '0.24.3')
```

The error in the log is triggered by a _very specific_ exception that pygit2 raises when libgit2 is not built in such a way that it supports SSH-based repositories. This is almost certainly one of the following two cases of user error:

1. Incorrectly-compiled libgit2 (see [here](https://github.com/saltstack/salt/issues/21979) for another example of this).
2. Pygit2 built before libgit2. IIRC, Pygit2 has to build against libgit2. This is why the very link you posted to the "quick install" has the pygit2 installation come last.

The order of what you posted suggests that the latter may be more likely than the former. Also, like I noted earlier, there are definite contractions in the OP.

Hope this info helps.

**Comment by terminalmage** [comment]
Also, is there a specific reason you need the latest pygit2, and can't use the packages provided by Ubuntu? I personally can't think of any Salt-related reason, 0.25 doesn't have any new feature that provides anything in gitfs which isn't already supported in 0.24 (which happens to be packaged by Ubuntu):

- http://packages.ubuntu.com/xenial/python-pygit2
- http://packages.ubuntu.com/xenial/libgit2-24

**Comment by nicholashoule** [comment]
My mistake, I posted the wrong output of the `salt --versions-report` command, so here are the updated outputs for the SaltStack master. A little back-story, my original attempt with salt/gitlab was over HTTPS, but I hit an error which led me down the path that eventually brought me here. Anyways, I will attempt to re-build the SaltStack server in a Vagrant project. I may have configured something incorrectly.

```● salt-master.service - The Salt Master Server
   Loaded: loaded (/lib/systemd/system/salt-master.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2017-03-28 10:59:23 MDT; 4s ago
 Main PID: 5686 (salt-master)
    Tasks: 30
   Memory: 372.7M
      CPU: 6.715s
   CGroup: /system.slice/salt-master.service
           ├─5686 /usr/bin/python /usr/bin/salt-master
           ├─5696 /usr/bin/python /usr/bin/salt-master
           ├─5697 /usr/bin/python /usr/bin/salt-master
           ├─5698 /usr/bin/python /usr/bin/salt-master
           ├─5701 /usr/bin/python /usr/bin/salt-master
           ├─5702 /usr/bin/python /usr/bin/salt-master
           ├─5703 /usr/bin/python /usr/bin/salt-master
           ├─5704 /usr/bin/python /usr/bin/salt-master
           ├─5705 /usr/bin/python /usr/bin/salt-master
           ├─5706 /usr/bin/python /usr/bin/salt-master
           ├─5713 /usr/bin/python /usr/bin/salt-master
           └─5714 /usr/bin/python /usr/bin/salt-master

Mar 28 10:59:23 saltstack systemd[1]: Starting The Salt Master Server...
Mar 28 10:59:23 saltstack systemd[1]: Started The Salt Master Server.
Mar 28 10:59:24 saltstack salt-master[5686]: [ERROR   ] Unable to fetch SSH-based gitfs remote 'git@gitlab.com:181gaming/saltstack.git'. You may need to add ssh:// to the repo string or libgit2 must be compiled
```

```
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.25.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: 0.25.0
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-70-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

```
saltstack@saltstack:~$ python -c 'import pygit2; print(pygit2.__version__, pygit2.LIBGIT2_VERSION)'
('0.25.0', '0.25.0')
```


[salt-2016-11-3-carbon.tar.gz](https://github.com/saltstack/salt/files/876494/salt-2016-11-3-carbon.tar.gz)

**Comment by nicholashoule** [comment]
Looks like I might have missed a package. `pkg-config`

I think it's working now, that is the error I would expect. Thanks for the help!

```
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: saltstack
[DEBUG   ] Missing configuration file: /home/saltstack/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] LazyLoaded fileserver.update
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: saltstack
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event: tag = salt/run/20170328131337217162/new; data = {'fun': 'runner.fileserver.update', 'fun_args': [], 'jid': '20170328131337217162', 'user': 'sudo_saltstack', '_stamp': '2017-03-28T19:13:37.554282'}
[DEBUG   ] pygit2 gitfs_provider enabled
[DEBUG   ] LazyLoaded git.envs
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Updating git fileserver cache
[DEBUG   ] Set update lock for gitfs remote 'git@gitlab.com:181gaming/saltstack.git'
[DEBUG   ] Fetching gitfs remote 'git@gitlab.com:181gaming/saltstack.git'
[ERROR   ] Error occurred fetching gitfs remote 'git@gitlab.com:181gaming/saltstack.git': Failed to authenticate SSH session: Callback returned error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 1406, in _fetch
    fetch_results = origin.fetch(**fetch_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pygit2/remote.py", line 375, in fetch
    check_error(err)
  File "/usr/local/lib/python2.7/dist-packages/pygit2/errors.py", line 64, in check_error
    raise GitError(message)
GitError: Failed to authenticate SSH session: Callback returned error
[DEBUG   ] Removed update lock for gitfs remote 'git@gitlab.com:181gaming/saltstack.git'
[DEBUG   ] Updating roots fileserver cache
[DEBUG   ] Sending event: tag = salt/run/20170328131337217162/ret; data = {'fun_args': [], 'jid': '20170328131337217162', 'return': True, 'success': True, '_stamp': '2017-03-28T19:13:38.518355', 'user': 'sudo_saltstack', 'fun': 'runner.fileserver.update'}
[DEBUG   ] LazyLoaded nested.output
True
[DEBUG   ] LazyLoaded local_cache.prep_jid
[INFO    ] Runner completed: 20170328131337217162
[DEBUG   ] Runner return: True
```

**Comment by gtmanfred** [comment]
Thanks!

Closing this.

Daniel
