### ISSUE TITLE
KeyError on runner function, when using salt.client.Caller() to get grains

### ISSUE THREAD

**Issue by rmarcinik** [saltstack/salt#40374]
### Description of Issue/Question
We have a custom runner module that is used during bootstrapping new minions.  The initializing orchestration calls two functions from this module, in order to register them to some external services.  The second call would throw a KeyError module.function_name, even though the function was clearly there.  So mocked up some test sls to try and reproduce this.

### Setup
`_modules/runners/test.py`
```
import salt.client

def one():
  caller = salt.client.Caller()
  host = caller.cmd('grains.get','host')
  return host

def two():
  return 'TWO'
```
`orch.sls`
```
one:
  salt.runner:
    - name: test.one
two:
  salt.runner:
    - name: test.two
```

Output:
```
----------
          ID: one
    Function: salt.runner
        Name: test.one
      Result: True
     Comment: Runner function 'test.one' executed.
     Started: 14:48:07.660968
    Duration: 3888.934 ms
     Changes:
              saltmaster
----------
          ID: two
    Function: salt.runner
        Name: test.two
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1746, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1703, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/saltmod.py", line 653, in runner
                  **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/modules/saltutil.py", line 1185, in runner
                  full_return=full_return)
                File "/usr/lib/python2.7/site-packages/salt/runner.py", line 144, in cmd
                  full_return)
                File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 225, in cmd
                  self.functions[fun], arglist, pub_data
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1086, in __getitem__
                  func = super(LazyLoader, self).__getitem__(item)
                File "/usr/lib/python2.7/site-packages/salt/utils/lazy.py", line 101, in __getitem__
                  raise KeyError(key)
              KeyError: 'test.two'
     Started: 14:48:11.550222
    Duration: 1026.722 ms
     Changes:
```

### Versions Report
```
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.22.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

**Comment by gtmanfred** [comment]
I have replicated this error with a docker container `gtmanfred/issues:40374`

```
$ docker run --rm -ti gtmanfred/issues:40374 salt-run state.orch orch
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 1746, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1703, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/states/saltmod.py", line 653, in runner
    **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/saltutil.py", line 1185, in runner
    full_return=full_return)
  File "/usr/lib/python2.7/site-packages/salt/runner.py", line 144, in cmd
    full_return)
  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 225, in cmd
    self.functions[fun], arglist, pub_data
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1086, in __getitem__
    func = super(LazyLoader, self).__getitem__(item)
  File "/usr/lib/python2.7/site-packages/salt/utils/lazy.py", line 101, in __getitem__
    raise KeyError(key)
KeyError: 'test.two'

[ERROR   ] Unable to write to SLS cache file /var/cache/salt/minion/sls.p. Check permission.
9fa8240395ce_master:
----------
          ID: one
    Function: salt.runner
        Name: test.one
      Result: True
     Comment: Runner function 'test.one' executed.
     Started: 15:00:08.537981
    Duration: 3822.629 ms
     Changes:
              9fa8240395ce
----------
          ID: two
    Function: salt.runner
        Name: test.two
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1746, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1703, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/saltmod.py", line 653, in runner
                  **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/modules/saltutil.py", line 1185, in runner
                  full_return=full_return)
                File "/usr/lib/python2.7/site-packages/salt/runner.py", line 144, in cmd
                  full_return)
                File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 225, in cmd
                  self.functions[fun], arglist, pub_data
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1086, in __getitem__
                  func = super(LazyLoader, self).__getitem__(item)
                File "/usr/lib/python2.7/site-packages/salt/utils/lazy.py", line 101, in __getitem__
                  raise KeyError(key)
              KeyError: 'test.two'
     Started: 15:00:12.360758
    Duration: 28.14 ms
     Changes:

Summary for 9fa8240395ce_master
------------
Succeeded: 1 (changed=1)
Failed:    1
------------
Total states run:     2
Total run time:   3.851 s
retcode:
    1
```

Thanks for reporting this,
Daniel

**Comment by gtmanfred** [comment]
This appears to only be caused by grains.get.

`test.ping` works.

```
[root@254777ed955c /]# cat /srv/salt/_runners/test.py
import salt.client

def one():
  caller = salt.client.Caller()
  return caller.cmd('test.ping')
  #return __salt__['cache.grains'](__opts__['id'])[__opts__['id'].strip('_master')]['host']

def two():
  return 'TWO'
[root@254777ed955c /]# salt-run state.orch orch
254777ed955c_master:
----------
          ID: one
    Function: salt.runner
        Name: test.one
      Result: True
     Comment: Runner function 'test.one' executed.
     Started: 15:09:21.974945
    Duration: 2307.365 ms
     Changes:
              True
----------
          ID: two
    Function: salt.runner
        Name: test.two
      Result: True
     Comment: Runner function 'test.two' executed.
     Started: 15:09:24.282496
    Duration: 1036.704 ms
     Changes:
              TWO

Summary for 254777ed955c_master
------------
Succeeded: 2 (changed=2)
Failed:    0
------------
Total states run:     2
Total run time:   3.344 s
retcode:
    0
```

**Comment by gtmanfred** [comment]
As a work around, in case you really need the grains from the master minion, you can use this and get the grains from the grains cache.

```
return __salt__['cache.grains'](__opts__['id'])[__opts__['id'].strip('_master')]['host']
```

**Comment by rmarcinik** [comment]
Thanks for the suggestion, the first hack I thought of was simply: `subprocess.check_output(['salt-call','grains.get','host'])`, which worked.  I reasoned that this might be worthy of a bug because I thought the Caller() interface was the same as salt-call, but some wires must be getting crossed during the loading process?  It is hard to debug as well, because the KeyError is not raised on the function that has the grains call in it, but an arbitrary function afterwards.
