### ISSUE TITLE
salt.runner.cloud.map_run raises exception on parallel=True

### ISSUE THREAD

**Issue by pepoluan** [saltstack/salt#40383]
### Description of Issue/Question

If the kwarg `parallel=True` is provided on a call to salt.runner.cloud.map_run() during orchestration, then after creation of servers the script would raise an AttributeError exception:

```
--- long output showing creation of servers, installation of packages, etc. ---
...
[ERROR   ] An un-handled exception from the multiprocessing process 'MultiprocessingProcess-1' was caught:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/process.py", line 647, in _run
    return self._original_run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1680, in _call_parallel_target
    troot = os.path.join(self.opts['cachedir'], self.jid)
  File "/usr/lib/python2.7/posixpath.py", line 68, in join
    if b.startswith('/'):
AttributeError: 'NoneType' object has no attribute 'startswith'
Process MultiprocessingProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/dist-packages/salt/utils/process.py", line 647, in _run
    return self._original_run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1680, in _call_parallel_target
    troot = os.path.join(self.opts['cachedir'], self.jid)
  File "/usr/lib/python2.7/posixpath.py", line 68, in join
    if b.startswith('/'):
AttributeError: 'NoneType' object has no attribute 'startswith'
Exception occurred in runner state.orch: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 390, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/runners/state.py", line 82, in orchestrate
    orchestration_jid=orchestration_jid)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 1078, in sls
    ret = st_.state.call_high(high_, orchestration_jid)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2491, in call_high
    ret = self.call_chunks(chunks)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1997, in call_chunks
    if self.reconcile_procs(running):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2026, in reconcile_procs
    ret_cache = os.path.join(self.opts['cachedir'], self.jid, tag)
  File "/usr/lib/python2.7/posixpath.py", line 68, in join
    if b.startswith('/'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

Invoking `salt-cloud -P -m $mapfile` does NOT produce the same error.

### Steps to Reproduce Issue

Create two identical .sls invoking `cloud.map_run`, differing only on the kwargs `parallel`, one set to `False` (no exception), the other set to `True` (causes exception).

### Versions Report

```
Salt Version:
           Salt: 2016.11.0-1068-gd73a526

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-66-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by gtmanfred** [comment]
Can you upgrade your salt installation? You are on an old version of develop.

```
[root@ip-10-0-0-120 ~]# salt-cloud --versions-report
Salt Version:
            Salt: 2016.11.3-4037-g9322630

Dependency Versions:
 Apache Libcloud: 0.20.1
            cffi: 1.9.1
        cherrypy: Not Installed
        dateutil: 2.6.0
           gitdb: Not Installed
       gitpython: Not Installed
           ioflo: Not Installed
          Jinja2: 2.7.2
         libgit2: Not Installed
         libnacl: Not Installed
        M2Crypto: Not Installed
            Mako: Not Installed
    msgpack-pure: Not Installed
  msgpack-python: 0.4.8
    mysql-python: Not Installed
       pycparser: 2.17
        pycrypto: 2.6.1
          pygit2: Not Installed
          Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
    python-gnupg: Not Installed
          PyYAML: 3.10
           PyZMQ: 15.3.0
            RAET: Not Installed
           smmap: Not Installed
         timelib: Not Installed
         Tornado: 4.2.1
             ZMQ: 4.1.4

System Versions:
            dist: centos 7.2.1511 Core
         machine: x86_64
         release: 3.10.0-327.10.1.el7.x86_64
          system: Linux
         version: CentOS Linux 7.2.1511 Core
```

We have about 3000 more commits since your install.

I just tested this with a clean install from git, and it appears to be working fine with parallel=True.

Thanks,
Daniel

**Comment by pepoluan** [comment]
Eh? You're right...

So `sh bootstrap_salt.sh -L -M -P git` does not upgrade to the latest head?

Because `sh bootstrap_salt.sh --help` says "Install from the head of the develop branch", and that made me think it always use latest.

Okay, I'll chase to the latest develop.

**Comment by pepoluan** [comment]
Can someone assist me how I can get to the latest head of develop?

I have tried various invocations of the `bootstrap.sh` script and it kept bringing me to older commits, not the latest head.

**Comment by gtmanfred** [comment]
Sorry, i missed this in my emails.

You will probably want to install pip, then pip uninstall salt, and then run the bootstrap script again.

Daniel

**Comment by gtmanfred** [comment]
@saltstack/team-triage ping
