### ISSUE TITLE
GitFS: Per remote saltenv

### ISSUE THREAD

**Issue by gfyrag** [saltstack/salt#40411]
### Description of Issue/Question

Per remote saltenv seems not working as expected.

### Setup

/etc/salt/master.d/repository.conf:
```
gitfs_remotes:
  - ssh://git@XXX
    - saltenv:
      - base:
        - ref: master
        - mountpoint: salt://base
        - root: root/base
        - pubkey: /root/.ssh/salt-master.pub
        - privkey: /root/.ssh/salt-master
        - passphrase: ''
```

### Steps to Reproduce Issue

```
root@XXXX:/etc/salt/master.d# salt-run cache.clear_git_lock gitfs type=update
/usr/lib/python2.7/dist-packages/cffi/model.py:532: UserWarning: 'point_conversion_form_t' has no values explicitly defined; guessing that it is equivalent to 'unsigned int'
  % self._get_c_name())
[CRITICAL] Invalid gitfs configuration parameter 'saltenv' in remote ssh://git@XXX. Valid parameters are: base, mountpoint, root, ssl_verify, user, password, pubkey, privkey, passphrase, insecure_auth, name. See the GitFS Walkthrough in the Salt documentation for further information.
Exception occurred in runner cache.clear_git_lock: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 395, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/runners/cache.py", line 217, in clear_git_lock
    __GITFS_OVERRIDES)
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 2167, in init_remotes
    self.role
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 1036, in __init__
    per_remote_only, override_params, cache_root, role)
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 244, in __init__
    failhard(self.role)
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 123, in failhard
    raise FileserverConfigError('Failed to load {0}'.format(role))
FileserverConfigError: Failed to load gitfs
```

### Versions Report

```
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: 0.25.1
        libnacl: Not Installed
       M2Crypto: 0.25.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: 0.25.0
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Debian 8 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: Debian 8
```

**Comment by gfyrag** [comment]
Upgrade to salt 2016.11.3 (Carbon) solved the pb automatically.
