### ISSUE TITLE
Python3 - Head of develop - SPM errors

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#40435]
Some SPM tests/commands not working.
Spm install / remove and man spm.

### Setup
Install package using spm. (package gets installed but throws a traceback)
```
spm install apache
Installing packages:
	apache

Proceed? [N/y] y
... installing apache
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: Unicode-objects must be encoded before hashing
Traceback (most recent call last):
  File "/usr/bin/spm", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/root/salt/scripts/spm", line 12, in <module>
    salt_spm()
  File "/root/salt/salt/scripts.py", line 487, in salt_spm
    spm.run()
  File "/root/salt/salt/cli/spm.py", line 34, in run
    client.run(self.args)
  File "/root/salt/salt/spm/__init__.py", line 114, in run
    self._install(args)
  File "/root/salt/salt/spm/__init__.py", line 365, in _install
    self._install_indv_pkg(package, out_file)
  File "/root/salt/salt/spm/__init__.py", line 522, in _install_indv_pkg
    self.files_conn)
  File "/root/salt/salt/spm/__init__.py", line 146, in _pkgfiles_fun
    return getattr(getattr(self.pkgfiles, self.files_prov), func)(*args, **kwargs)
  File "/root/salt/salt/spm/pkgfiles/local.py", line 183, in hash_file
    hashobj.update(f.read())
TypeError: Unicode-objects must be encoded before hashing
Traceback (most recent call last):
  File "/usr/bin/spm", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/root/salt/scripts/spm", line 12, in <module>
    salt_spm()
  File "/root/salt/salt/scripts.py", line 487, in salt_spm
    spm.run()
  File "/root/salt/salt/cli/spm.py", line 34, in run
    client.run(self.args)
  File "/root/salt/salt/spm/__init__.py", line 114, in run
    self._install(args)
  File "/root/salt/salt/spm/__init__.py", line 365, in _install
    self._install_indv_pkg(package, out_file)
  File "/root/salt/salt/spm/__init__.py", line 522, in _install_indv_pkg
    self.files_conn)
  File "/root/salt/salt/spm/__init__.py", line 146, in _pkgfiles_fun
    return getattr(getattr(self.pkgfiles, self.files_prov), func)(*args, **kwargs)
  File "/root/salt/salt/spm/pkgfiles/local.py", line 183, in hash_file
    hashobj.update(f.read())
TypeError: Unicode-objects must be encoded before hashing
```
removing seems to work, but there are files left in dir.
```
spm remove apache
Removing packages:
	apache
Proceed? [N/y] y
... removing apache
```

trying to install again and I see this:
```
spm install apache
Installing packages:
	apache

Proceed? [N/y] y
... installing apache
[ERROR   ] /srv/spm/salt/apache already exists, not installing
Not installing apache due to existing files:

/srv/spm/salt/apache
```

for man spm I see this:
```
man spm
No manual entry for spm
See 'man 7 undocumented' for help when manual pages are not available.
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
```
Salt Version:
           Salt: 2016.11.0-1085-gb603221
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 3.5.2 (default, Nov 17 2016, 17:05:23)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.6
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.9.7-x86_64-linode80
         system: Linux
        version: Ubuntu 16.04 denial
```

**Comment by cachedout** [comment]
@techhat Might you be able to spare some time to help with this one?

**Comment by cachedout** [comment]
No response, reassigning to @rallytime

**Comment by rallytime** [comment]
@frogunder Can you give #40733 a try and see if that resolves this issue for you?

**Comment by frogunder** [comment]
@rallytime Your fix is working for the traceback and remove/install error.

`spm man` is still not working.
```
[root@li997-156 salt]# man spm
No manual entry for spm
```

**Comment by rallytime** [comment]
@frogunder Great! 

As far as the `man spm` call, that appears to not be working on Py 2 as well as Py 3. Perhaps we need to re-open #28592.

**Comment by cachedout** [comment]
Please track the problem with `man` in another issue. I am closing this one.
