### ISSUE TITLE
Python 3 - Head of develop - publisher_acl fails

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#40436]
### Description of Issue/Question
publisher_acl fails when users others than root try and run commands
https://docs.saltstack.com/en/latest/ref/publisheracl.html

### Setup
```
put in master config

publisher_acl:
  testuser:
    - .*
    
add testuser

chmod 755 /var/cache/salt /var/cache/salt/master /var/cache/salt/master/jobs /var/run/salt /var/run/salt/master

modify the permissions of /var/log/salt and the existing log file to be writable by the user(s) which will be running the commands

su testuser
```

### Steps to Reproduce Issue
```
(virtualenv) [root@li451-148 virtualenv]# su testuser
(virtualenv) [testuser@li451-148 virtualenv]$ salt -c ./etc/salt '*' test.ping
Traceback (most recent call last):
  File "/usr/local/bin/salt", line 4, in <module>
    __import__('pkg_resources').require('salt===2016.11.3-4139-gde3d585')
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3084, in <module>
    @_call_aside
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3070, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3097, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 651, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 952, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 839, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'salt===2016.11.3-4139-gde3d585' distribution was not found and is required by the application
(virtualenv) [testuser@li451-148 virtualenv]$ salt --versions
Traceback (most recent call last):
  File "/usr/local/bin/salt", line 4, in <module>
    __import__('pkg_resources').require('salt===2016.11.3-4139-gde3d585')
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3084, in <module>
    @_call_aside
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3070, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3097, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 651, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 952, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 839, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'salt===2016.11.3-4139-gde3d585' distribution was not found and is required by the application
```
### Versions Report
```
salt --versions
Salt Version:
           Salt: 2016.11.3-4139-gde3d585
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 3.5.0 (default, Mar 30 2017, 18:14:57)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.1.6
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 4.9.7-x86_64-linode80
         system: Linux
        version: CentOS Linux 7.3.1611 Core

```

**Comment by terminalmage** [comment]
You have a bad installation. You installed from git, and the revision you installed is no longer present.

Try again with a fresh installation.

**Comment by cachedout** [comment]
Closing as expected behavior.
