### ISSUE TITLE
Python 3 - Head of develop - Create vm using salt-cloud fails

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#40437]
Trying to create new vm using salt-cloud fails

### Setup
```
providers.d
 
linode:
  apikey: 'xxxxxxx'
  password: 'xxxxxxx'
  location: Fremont, CA, USA
  driver: linode
  
  
profiles.d
  linode_arch:
  provider: linode
  size: Linode 4096
  image: Arch 2017.01.01
  script_args: '-g https://github.com/saltstack/salt.git -M -P git de3d58574a14ef996ba20a264592325742a60153'
```

### Steps to Reproduce Issue
 salt-cloud -c ./etc/salt -p linode_arch frodetest -ldebug

```
[DEBUG   ] Requesting URL https://api.linode.com/?api_key=XXXXXXXXXX&api_action=linode.list using GET method
[DEBUG   ] Response Status Code: 200
[DEBUG   ] Linode Response Status Code: 200
[DEBUG   ] Requesting URL https://api.linode.com/?api_key=XXXXXXXXXX&api_action=linode.ip.list using GET method
[DEBUG   ] Response Status Code: 200
[DEBUG   ] Linode Response Status Code: 200
[ERROR   ] There was a profile error: 'dict_keys' object does not support indexing
Traceback (most recent call last):
  File "/root/salt/salt/cloud/cli.py", line 284, in run
    self.config.get('names')
  File "/root/salt/salt/cloud/__init__.py", line 1404, in run_profile
    prov_name = mapped_providers[prov].keys()[0]
TypeError: 'dict_keys' object does not support indexing
```

### Versions Report
```
Salt Version:
           Salt: 2016.11.3-4139-gde3d585
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 3.5.0 (default, Mar 30 2017, 18:15:01)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.1.6
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 4.9.7-x86_64-linode80
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

**Comment by tonybaloney** [comment]
the lazy way is use `list(x.keys())[0]` but that's really ugly. it'd be better off refactoring the method.

**Comment by rallytime** [comment]
Hi @frogunder - Please give #40568 a try. That should fix up this issue.

**Comment by tonybaloney** [comment]
I'll pick this up today. I'm in the middle of testing this https://github.com/apache/libcloud/pull/1026
Against my linode account anyway.

**Comment by tonybaloney** [comment]
never mind. see it's already been fixed.

**Comment by rallytime** [comment]
Ah, sorry @tonybaloney! I grabbed this one today. Thank you for helping out, though!
