### ISSUE TITLE
Windows Master - Python3 - Head of develop - SALT.MODULES.WIN_STATUS fails 

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#40506]
Running WIN_STATUS commands fails on Windows master / minion on python3

### Setup
Setup Windows master / minion using python3

### Steps to Reproduce Issue
```
PS C:\> salt 'win' status.diskusage path=c:/salt
win:
    The minion function caused an exception: Traceback (most recent call last):
      File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1446, in _thread_return
        return_data = executor.execute()
      File "c:\salt\bin\lib\site-packages\salt\executors\direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "c:\salt\bin\lib\site-packages\salt\modules\win_status.py", line 114, in diskusage
        fun = ctypes.windll.kernel32.GetDiskFreeSpaceExw
      File "c:\salt\bin\lib\ctypes\__init__.py", line 360, in __getattr__
        func = self.__getitem__(name)
      File "c:\salt\bin\lib\ctypes\__init__.py", line 365, in __getitem__
        func = self._FuncPtr((name_or_ordinal, self))
    AttributeError: function 'GetDiskFreeSpaceExw' not found


PS C:\> salt 'win' status.cpuload
win:
    The minion function caused an exception: Traceback (most recent call last):
      File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1446, in _thread_return
        return_data = executor.execute()
      File "c:\salt\bin\lib\site-packages\salt\executors\direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "c:\salt\bin\lib\site-packages\salt\modules\win_status.py", line 88, in cpuload
        return int(__salt__['cmd.run'](cmd).split('=')[1])
    ValueError: invalid literal for int() with base 10: '16\r\r\n\r\r\n\r\r\nLoadPercentage'
```

### Versions Report
```
Master

PS C:\> salt --versions
Salt Version:
           Salt: 2016.11.0-1126-gf589e3c

Dependency Versions:
           cffi: 1.10.0
       cherrypy: unknown
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 2.0.8
          ioflo: 1.5.5
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.3.8
         PyYAML: 3.12
          PyZMQ: 16.0.1
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.4.1
            ZMQ: 4.1.6

System Versions:
           dist:
        machine: AMD64
        release: 2016Server
         system: Windows
        version: 2016Server 10.0.14393 SP0 Multiprocessor Free
```

```
Minion

PS C:\> salt 'win' test.versions
win:
    Salt Version:
               Salt: 2016.11.0-1126-gf589e3c

    Dependency Versions:
               cffi: 1.10.0
           cherrypy: 7.1.0
           dateutil: 2.5.3
          docker-py: Not Installed
              gitdb: 0.6.4
          gitpython: 2.0.8
              ioflo: 1.5.5
             Jinja2: 2.9.4
            libgit2: Not Installed
            libnacl: 1.4.5
           M2Crypto: Not Installed
               Mako: 1.0.4
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.17
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
       python-gnupg: 0.3.8
             PyYAML: 3.12
              PyZMQ: 16.0.1
               RAET: Not Installed
              smmap: 0.9.0
            timelib: 0.2.4
            Tornado: 4.4.1
                ZMQ: 4.1.6

    System Versions:
               dist:
            machine: AMD64
            release: 2016Server
             system: Windows
            version: 2016Server 10.0.14393 SP0 Multiprocessor Free
```

**Comment by twangboy** [comment]
Blocked until PR is merged
