### ISSUE TITLE
Windows Master - Python3 - Head of develop - status.pid not available

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#40500]
On windows master using python3, status.pid is not available. 

### Setup
Setup windows master/minion with python3.

### Steps to Reproduce Issue
Run command: salt-call --local status.pid 'salt'

```
PS C:\salt> salt-call --local status.pid 'salt'
[ERROR   ] Failed to import module boto_ec2, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1343, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "C:\salt\bin\lib\imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "C:\salt\bin\lib\imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 669, in exec_module
  File "<frozen importlib._bootstrap_external>", line 774, in get_code
  File "C:\salt\bin\lib\imp.py", line 156, in get_data
    return file.read()
  File "C:\salt\bin\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 35274: character maps to <undefined>
'status.pid' is not available.
PS C:\salt>
```

### Versions Report
```
PS C:\salt> salt --versions
Salt Version:
           Salt: 2016.11.0-1126-gf589e3c

Dependency Versions:
           cffi: 1.10.0
       cherrypy: unknown
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 2.0.8
          ioflo: 1.5.5
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.3.8
         PyYAML: 3.12
          PyZMQ: 16.0.1
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.4.1
            ZMQ: 4.1.6

System Versions:
           dist:
        machine: AMD64
        release: 2016Server
         system: Windows
        version: 2016Server 10.0.14393 SP0 Multiprocessor Free
```

**Comment by twangboy** [comment]
@frogunder `status.pid` is not available on Windows. There is no `pid` function defined in `win_status.py`. The `pid` function from `status.py` is not namespaced to the `win_status` module because it shells out using the `ps` command which is not available on Windows. If this functionality is needed, we'll need to find another way to get the process ID of running processes on Windows.
