### ISSUE TITLE
salt-minion can't connect to master if in salt-minion configuration define masters ipv6 addresses in short notation.

### ISSUE THREAD

**Issue by gashev** [saltstack/salt#40515]
### Description of Issue/Question

When define salt-minion configuration with ipv6 addresses in short notation for the masters, salt-minion can't connect to masters.

salt-minion configuration:

```
# cat /etc/salt/minion
master:
  - '[fddc:3713:9ab3::17:0:50]:4506'
  - '[fddc:3713:9ab3::17:0:51]:4506'
ipv6: True
id: master-1
log_level: debug
log_level_logfile : debug
schedule:
highstate:
  function: state.highstate
  minutes: 60
```

Here masters ip are fddc:3713:9ab3::17:0:50 and fddc:3713:9ab3::17:0:51: with a double colon (::).

salt-minion logs:

```
2017-04-03 17:16:51,270 [salt.utils.process                       ][DEBUG   ][9581] Process Manager starting!
2017-04-03 17:16:51,271 [salt.config                              ][DEBUG   ][9581] Reading configuration from /etc/salt/minion
2017-04-03 17:16:51,482 [salt.minion                                          ][INFO    ][9581] Creating minion process manager
2017-04-03 17:16:51,483 [salt.minion                                          ][DEBUG   ][9581] Connecting to master. Attempt 1 of 1
2017-04-03 17:16:51,502 [salt.crypt                                           ][DEBUG   ][9581] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'master-1', 'tcp://fddc:3713:9ab3::17:0:51:4506')
2017-04-03 17:16:51,504 [salt.transport.zeromq                                ][DEBUG   ][9581] Generated random reconnect delay between '1000ms' and '11000ms' (2807)
2017-04-03 17:16:51,504 [salt.transport.zeromq                                ][DEBUG   ][9581] Setting zmq_reconnect_ivl to '2807ms'
2017-04-03 17:16:51,505 [salt.transport.zeromq                                ][DEBUG   ][9581] Setting zmq_reconnect_ivl_max to '11000ms'
2017-04-03 17:16:51,505 [salt.config                                          ][DEBUG   ][9581] Reading configuration from /etc/salt/minion
2017-04-03 17:16:51,699 [salt.minion                                          ][INFO    ][9581] Creating minion process manager
2017-04-03 17:16:51,700 [salt.minion                                          ][DEBUG   ][9581] Connecting to master. Attempt 1 of 1
2017-04-03 17:16:51,701 [salt.crypt                                           ][DEBUG   ][9581] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'master-1', 'tcp://fddc:3713:9ab3::17:0:50:4506')
2017-04-03 17:16:51,703 [salt.transport.zeromq                                ][DEBUG   ][9581] Generated random reconnect delay between '1000ms' and '11000ms' (10972)
2017-04-03 17:16:51,704 [salt.transport.zeromq                                ][DEBUG   ][9581] Setting zmq_reconnect_ivl to '10972ms'
2017-04-03 17:16:51,704 [salt.transport.zeromq                                ][DEBUG   ][9581] Setting zmq_reconnect_ivl_max to '11000ms'
2017-04-03 17:16:51,705 [salt.utils.process                                   ][DEBUG   ][9581] Process Manager starting!
2017-04-03 17:16:51,736 [salt.transport.zeromq                                ][DEBUG   ][9581] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'master-1', 'tcp://fddc:3713:9ab3::17:0:51:4506', 'clear')
2017-04-03 17:16:51,739 [salt.utils.process                                   ][DEBUG   ][9581] Process Manager starting!
2017-04-03 17:16:51,769 [salt.transport.zeromq                                ][DEBUG   ][9581] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'master-1', 'tcp://fddc:3713:9ab3::17:0:50:4506', 'clear')
2017-04-03 17:16:51,770 [tornado.application                                  ][ERROR   ][9581] Exception in callback <functools.partial object at 0x233c260>
Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/tornado/ioloop.py", line 591, in _run_callback
    ret = callback()
  File "/usr/lib64/python2.6/site-packages/tornado/stack_context.py", line 274, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib64/python2.6/site-packages/tornado/ioloop.py", line 597, in <lambda>
    self.add_future(ret, lambda f: f.result())
  File "/usr/lib64/python2.6/site-packages/tornado/concurrent.py", line 214, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 230, in wrapper
    yielded = next(result)
  File "/usr/lib/python2.6/site-packages/salt/crypt.py", line 463, in _authenticate
    io_loop=self.io_loop)
  File "/usr/lib/python2.6/site-packages/salt/transport/client.py", line 105, in factory
    return salt.transport.zeromq.AsyncZeroMQReqChannel(opts, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/transport/zeromq.py", line 86, in __new__
    new_obj.__singleton_init__(opts, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/transport/zeromq.py", line 157, in __singleton_init__
    io_loop=self._io_loop,
  File "/usr/lib/python2.6/site-packages/salt/transport/zeromq.py", line 822, in __init__
    self._init_socket()
  File "/usr/lib/python2.6/site-packages/salt/transport/zeromq.py", line 870, in _init_socket
    self.socket.connect(self.addr)
  File "zmq/backend/cython/socket.pyx", line 471, in zmq.backend.cython.socket.Socket.connect (zmq/backend/cython/socket.c:4295)

Salt-minion can't connect to master.

```
And work correctly with configuration:
```
# cat /etc/salt/minion
master:
  - '[fddc:3713:9ab3:0:0:17:0:50]:4506'
  - '[fddc:3713:9ab3:0:0:17:0:51]:4506'
ipv6: True
id: master-1
log_level: debug
log_level_logfile : debug
schedule:
highstate:
  function: state.highstate
  minutes: 60
```

Here masters ip are fddc:3713:9ab3:0:0:17:0:50 and fddc:3713:9ab3:0:0:17:0:51 - without a double colon (::) (added zeros).

Salt-minion connect to master.

### Versions Report
```
# salt --versions-report
Salt Version:
           Salt: 2016.3.6

Dependency Versions:
          cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug  9 2016, 06:11:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: redhat 6.8 Santiago
        machine: x86_64
        release: 2.6.32-642.13.1.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.8 Santiago

**Comment by gtmanfred** [comment]
I have replicated this issue, thanks for reporting.  If you wouldn't mind submitting a pull request to fix this, we would greatly appreciate it.

Otherwise I have tagged our core team to take a look.

Thanks
Daniel

**Comment by gashev** [comment]
Any update?

**Comment by gtmanfred** [comment]
It looks like this will be fixed once https://github.com/saltstack/salt/pull/49755/files is merged

**Comment by aphor** [comment]
@gtmanfred 
Test coverage added in that PR covers this bug.
https://github.com/saltstack/salt/pull/49755/files#diff-ada2523c56a9e35517c62b8521065a1eR208

@gashev if you want to test this, the fix for verification is in 2018.3 since 83c38c64a8c849f5b4409bfc1f9831860be55fa5

If not, Jenkins has it covered 👍

**Comment by gtmanfred** [comment]
perfect, thanks.

**Comment by MKLeb** [comment]
Closing as it seems this is fixed
