### ISSUE TITLE
mysql states don't run successfully on the initial state run

### ISSUE THREAD

**Issue by wasabi222** [saltstack/salt#40542]
### Description of Issue/Question

mysql state modules (_user, _database, and _grants) error out on the intial state run with an import error (ImportError: No module named connections), but run okay on subsequent state runs, even with reload_modules set to true in the state.

These states work in 2016.11.3, but fail on initial run on 2017.1.10. 

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
```
prereq state:
pm_pip_packages:
  pip.installed:
    - require:
     - pkg: pm_pkg
    - requirements: {{ pm.directory }}/requirements.txt
    - reload_modules: true

requirements:
mysqlclient==1.3.10

pm_pkg:
  pkg.installed:
    - pkgs: {{ pm.pkgs }}
    - refresh: true

pm.pkgs:
    - mysql-server
    - mysql-connector-python


failed states on initial run:

pm_mysql_user:
  mysql_user.present:
    - name: {{ pm.config.database.user }}
    - host: {{ pm.config.database.host }}
    - reload_modules: True

pm_create_db:
  mysql_database.present:
    - name: {{ pm.config.database.name }}
    - character_set: utf8
    - collate: utf8_general_ci

pm_grant_db_access:
  mysql_grants.present:
    - user: {{ pm.config.database.user }}
    - host: {{ pm.config.database.host }}
    - grant: all privileges
    - database: '*.*'
```
### Steps to Reproduce Issue
on version 2017.1.10, after adding the mysql apt-repo and installing mysql-python-connector, run `kitchen converge` using test-kitchen. debug output below:

```
ID: pm_mysql_user
           Function: mysql_user.present
        Name: root
             Result: False
            Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1746, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1703, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/mysql_user.py", line 131, in present
                  **connection_args):
                File "/usr/lib/python2.7/dist-packages/salt/modules/mysql.py", line 1128, in user_exists
                  dbc = _connect(**connection_args)
                File "/usr/lib/python2.7/dist-packages/salt/modules/mysql.py", line 330, in _connect
                  dbc = MySQLdb.connect(**connargs)
                File "/usr/lib/python2.7/dist-packages/MySQLdb/__init__.py", line 80, in Connect
              ImportError: No module named connections
            Started: 13:00:17.126723
           Duration: 32.529 ms
            Changes:
       ----------
          ID: pm_create_db
           Function: mysql_database.present
        Name: pm
             Result: False
            Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1746, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1703, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/mysql_database.py", line 55, in present
                  existing = __salt__['mysql.db_get'](name, **connection_args)
                File "/usr/lib/python2.7/dist-packages/salt/modules/mysql.py", line 897, in db_get
                  dbc = _connect(**connection_args)
                File "/usr/lib/python2.7/dist-packages/salt/modules/mysql.py", line 330, in _connect
                  dbc = MySQLdb.connect(**connargs)
                File "/usr/lib/python2.7/dist-packages/MySQLdb/__init__.py", line 80, in Connect
              ImportError: No module named connections
            Started: 13:00:17.162850
           Duration: 2.024 ms
            Changes:
       ----------
          ID: pm_grant_db_access
           Function: mysql_grants.present
             Result: False
            Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1746, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1703, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/mysql_grants.py", line 150, in present
                  grant, database, user, host, grant_option, escape, **connection_args
                File "/usr/lib/python2.7/dist-packages/salt/modules/mysql.py", line 1709, in grant_exists
                  grants = user_grants(user, host, **connection_args)
                File "/usr/lib/python2.7/dist-packages/salt/modules/mysql.py", line 1653, in user_grants
                  if not user_exists(user, host, **connection_args):
                File "/usr/lib/python2.7/dist-packages/salt/modules/mysql.py", line 1128, in user_exists
                  dbc = _connect(**connection_args)
                File "/usr/lib/python2.7/dist-packages/salt/modules/mysql.py", line 330, in _connect
                  dbc = MySQLdb.connect(**connargs)
                File "/usr/lib/python2.7/dist-packages/MySQLdb/__init__.py", line 80, in Connect
              ImportError: No module named connections
            Started: 13:00:17.165706
           Duration: 2.365 ms
            Changes:
       ----------

same thing in debug:

[INFO    ] Executing state mysql_user.present for root
       [ERROR   ] An exception occurred in this state: Traceback (most recent call last):
         File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1746, in call
           **cdata['kwargs'])
         File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1703, in wrapper
           return f(*args, **kwargs)
         File "/usr/lib/python2.7/dist-packages/salt/states/mysql_user.py", line 131, in present
           **connection_args):
         File "/usr/lib/python2.7/dist-packages/salt/modules/mysql.py", line 1128, in user_exists
           dbc = _connect(**connection_args)
         File "/usr/lib/python2.7/dist-packages/salt/modules/mysql.py", line 330, in _connect
           dbc = MySQLdb.connect(**connargs)
         File "/usr/lib/python2.7/dist-packages/MySQLdb/__init__.py", line 80, in Connect
       ImportError: No module named connections

       [DEBUG   ] Refreshing modules...
       [INFO    ] Loading fresh modules for state activity
       [DEBUG   ] LazyLoaded jinja.render
       [DEBUG   ] LazyLoaded yaml.render
       [INFO    ] Completed state [root] at time 19:07:02.689066 duration_in_ms=31.941

- snip-

```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
I'm not sure how to get this as I'm using kitchen-salt, but a salt-call from the vagrant host is this:

```
root@default-bento-debian-87:~# salt-call --versions-report
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.5
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.7
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.7```

**Comment by Ch3LL** [comment]
I'm confused we do not have a `2017.1.10` version? Can you elaborate?

**Comment by wasabi222** [comment]
I'm confused as well it seems, I apologize as I'm still new to salt. I'm using kitchen-salt and when I add the line `salt_version: "2016.11.3"` to my provisioner it works okay, but without that line, when I do a `kitchen converge`, I see this output:

```
sh: 1: salt-call: not found
       downloading http://bootstrap.saltstack.org
         to file /tmp/bootstrap-salt.sh
       trying wget...
        *  INFO: Running version: 2017.01.10
        *  INFO: Executed by: sh
        *  INFO: Command line: '/tmp/bootstrap-salt.sh '
-snip-
```
which is where I got that 2017.01.10 version from. But when I add that line, I see this output:

```
downloading http://bootstrap.saltstack.org
         to file /tmp/bootstrap-salt.sh
       trying wget...
        *  INFO: Running version: 2017.01.10
        *  INFO: Executed by: sh
        *  INFO: Command line: '/tmp/bootstrap-salt.sh -P git v2016.11.3'
-snip-
```

**Comment by Ch3LL** [comment]
Welcome to Salt :) Anyways that is actually the version of the bootstrap script :) If you see the logs from earlier your downloading and running that salt bootstrap script (repo [here](https://github.com/saltstack/salt-bootstrap)) which installs salt for you.

I'm not at all familiar with salt-kitchen so can you explain how you are kicking off this state run? Is it just running `salt '*' state.sls <slsfilename>`?
