### ISSUE TITLE
salt-cloud fails when spinning up instances in multiple regions

### ISSUE THREAD

**Issue by cachedout** [saltstack/salt#40589]
### Description of Issue/Question
The following stacktrace occurs:

<details>

```
INFO:urllib3.connectionpool:Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
INFO:urllib3.connectionpool:Starting new HTTPS connection (1): ec2.us-east-2.amazonaws.com
INFO:urllib3.connectionpool:Starting new HTTPS connection (1): ec2.ap-northeast-2.amazonaws.com
INFO:urllib3.connectionpool:Starting new HTTPS connection (1): ec2.eu-west-1.amazonaws.com
INFO:urllib3.connectionpool:Starting new HTTPS connection (1): ec2.ap-northeast-1.amazonaws.com
INFO:urllib3.connectionpool:Starting new HTTPS connection (1): ec2.sa-east-1.amazonaws.com
Traceback (most recent call last):
  File "/home/ec2-user/orchestrator/lib/saltclient.py", line 99, in create_instances
    ret = client.map_run(custmap)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 361, in map_run
    mapper.run_map(dmap)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 2231, in run_map
    profile, local_master=local_master
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1288, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 2510, in create
    data, vm_ = request_instance(vm_, location)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 1787, in request_instance
    _new_eni = _create_eni_if_necessary(interface, vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 1345, in _create_eni_if_necessary
    _new_eip = _request_eip(interface, vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 1270, in _request_eip
    sigver='4')
  File "/usr/lib/python2.7/dist-packages/salt/utils/aws.py", line 441, in query
    method, endpoint, params, prov_dict, aws_api_version, location, product, requesturl=requesturl
  File "/usr/lib/python2.7/dist-packages/salt/utils/aws.py", line 287, in sig4
    product
  File "/usr/lib/python2.7/dist-packages/salt/utils/aws.py", line 339, in _sig_key
    kDate = _sign(('AWS4' + key).encode('utf-8'), date_stamp)
TypeError: cannot concatenate 'str' and 'dict' objects
```
</details>

### Setup
An example provider configuration:
<details>

```
aws-us-east-1: 
id: '<secret>' 
key: '<secret>' 
driver: ec2 
location: us-east-1

aws-us-east-2: 
id: '<secret>' 
key: '<secret>' 
driver: ec2 
location: us-east-2

aws-us-west-1: 
id: '<secret>' 
key: '<secret>' 
driver: ec2 
location: us-west-1

aws-us-west-2: 
id: '<secret>' 
key: '<secret>' 
driver: ec2 
location: us-west-2

aws-ca-central-1: 
id: '<secret>' 
key: '<secret>' 
driver: ec2 
location: ca-central-1

aws-ap-south-1: 
id: '<secret>' 
key: '<secret>' 
driver: ec2 
location: ap-south-1

aws-ap-northeast-1: 
id: '<secret>' 
key: '<secret>' 
driver: ec2 
location: ap-northeast-1

aws-ap-northeast-2: 
id: '<secret>' 
key: '<secret>' 
driver: ec2 
location: ap-northeast-2

aws-ap-southeast-1: 
id: '<secret>' 
key: '<secret>' 
driver: ec2 
location: ap-southeast-1

aws-ap-southeast-2: 
id: '<secret>' 
key: '<secret>' 
driver: ec2 
location: ap-southeast-2

aws-eu-central-1: 
id: '<secret>' 
key: '<secret>' 
driver: ec2 
location: eu-central-1

aws-eu-west-1: 
id: '<secret>' 
key: '<secret>' 
driver: ec2 
location: eu-west-1

aws-eu-west-2: 
id: '<secret>' 
key: '<secret>' 
driver: ec2 
location: eu-west-2

aws-sa-east-1: 
id: '<secret>' 
key: '<secret>' 
driver: ec2 
location: sa-east-1
```
</details>

### Steps to Reproduce Issue
The usecase is that we are trying to spinup ec2 instances in multiple regions. It works in one fails in another region with the exception.

### Additional details
I added print statement in the salt cloud and I see that in case of exception in the statement "kDate = _sign(('AWS4' + key).encode('utf-8'), date_stamp)” the value of key is {} rather than the key configured in the cloud providers. I think the issue is in the function def get_provider(vm_=None): where __active_provider_name__ is overwritten some how.

### Versions Report
2016.11.3

**Comment by gtmanfred** [comment]
This works correctly when using `salt-cloud -Pm map` so it must be something in the cloudclient map_run.

**Comment by cachedout** [comment]
@gtmanfred If you're moving this to block, please leave a comment explaining why so we can track these. Thanks. :]

**Comment by gtmanfred** [comment]
I am unable to replicate this issue.

I have tried the following.

1. using roles
1. using different users
1. munging the provider in the map file (which doesn't work at all)
1. attempting to build in regions that don't exist
1. attempting to build with one key that works and one key that does not work
1. unquoting variables and trying different keys that may mess with yaml renderer

and some more in between that i have forgotten.

I am marking this as blocked until I can get more information from the user about what their setup looks like.

**Comment by cachedout** [comment]
Refs zd/#1312

**Comment by cachedout** [comment]
This turned out to be something custom that the user was doing and not a salt bug. Closing.

**Comment by gtmanfred** [comment]
This came back

**Comment by gtmanfred** [comment]
I am marking this one as cannot reproduce and blocked.

I haven't been able to reproduce this yet, but we have a conference call with the customer today, so that might shed some light on this issue.

**Comment by coen-hyde** [comment]
We're experiencing this after upgrading from 2016.11.3 to 2016.11.6. Our Salt master uses an IAM Role via an instance profile and deploying in us-east-1 only. The strange thing is it doesn't fail 100% of the time. Probably 70% failure rate, which indicates to me this is a bit more nuanced. We do have a few of other AWS related things going on such as an SQS Engine and scheduled Runner every minute that interacts with AWS api's.

@gtmanfred Were you been able to reproduce after talking with the customer?

**Comment by gtmanfred** [comment]
I have never been able to replicate this.  At one point I built 100 servers within 10 minutes, using the same process, and they all succeeded.
