### ISSUE TITLE
Python3 - Windows master - Master/minion deamon fails

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#40616]
### Description of Issue/Question
Trying to run master/minion daemon fails on Windows on Python3.

### Setup
Create a Windows master/minion setup on python3.

### Steps to Reproduce Issue
Kill the master and minion.
Run the commands `salt-master -d` or `salt-minion -d` 

```
C:\>salt-minion -d
--- Logging error ---
Traceback (most recent call last):
  File "C:\salt\bin\lib\multiprocessing\queues.py", line 243, in _feed
    send_bytes(obj)
  File "C:\salt\bin\lib\multiprocessing\connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "C:\salt\bin\lib\multiprocessing\connection.py", line 280, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
Traceback (most recent call last):
BrokenPipeError: [WinError 232] The pipe is being closed
  File "C:\salt\bin\lib\logging\handlers.py", line 1349, in emit
    self.enqueue(self.prepare(record))
  File "C:\salt\bin\lib\logging\handlers.py", line 1315, in enqueue
    self.queue.put_nowait(record)
  File "C:\salt\bin\lib\multiprocessing\queues.py", line 129, in put_nowait
    return self.put(obj, False)
  File "C:\salt\bin\lib\multiprocessing\queues.py", line 81, in put
    assert not self._closed
AssertionError
Call stack:
  File "C:\salt\bin\Scripts\salt-minion", line 26, in <module>
    salt_minion()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 168, in salt_minion
    minion.start()
  File "C:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 340, in start
    super(Minion, self).start()
  File "C:\salt\bin\lib\site-packages\salt\utils\parsers.py", line 1007, in start
    self.prepare()
  File "C:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 311, in prepare
    self.daemonize_if_required()
  File "C:\salt\bin\lib\site-packages\salt\utils\parsers.py", line 969, in daemonize_if_required
    log.shutdown_multiprocessing_logging_listener(daemonizing=True)
  File "C:\salt\bin\lib\site-packages\salt\log\setup.py", line 946, in shutdown_multiprocessing_logging_listener
    logging.getLogger(__name__).debug('joining multiprocessing queue thread')
  File "C:\salt\bin\lib\logging\__init__.py", line 1268, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\log\setup.py", line 313, in _log
    self, level, msg, args, exc_info=exc_info, extra=extra
Message: 'joining multiprocessing queue thread'
Arguments: None
--- Logging error ---
Traceback (most recent call last):
  File "C:\salt\bin\lib\logging\handlers.py", line 1349, in emit
    self.enqueue(self.prepare(record))
  File "C:\salt\bin\lib\logging\handlers.py", line 1315, in enqueue
    self.queue.put_nowait(record)
  File "C:\salt\bin\lib\multiprocessing\queues.py", line 129, in put_nowait
    return self.put(obj, False)
  File "C:\salt\bin\lib\multiprocessing\queues.py", line 81, in put
    assert not self._closed
AssertionError
Call stack:
  File "C:\salt\bin\Scripts\salt-minion", line 26, in <module>
    salt_minion()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 168, in salt_minion
    minion.start()
  File "C:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 340, in start
    super(Minion, self).start()
  File "C:\salt\bin\lib\site-packages\salt\utils\parsers.py", line 1007, in start
    self.prepare()
  File "C:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 311, in prepare
    self.daemonize_if_required()
  File "C:\salt\bin\lib\site-packages\salt\utils\parsers.py", line 969, in daemonize_if_required
    log.shutdown_multiprocessing_logging_listener(daemonizing=True)
  File "C:\salt\bin\lib\site-packages\salt\log\setup.py", line 960, in shutdown_multiprocessing_logging_listener
    logging.getLogger(__name__).debug('Stopped the multiprocessing logging queue listener')
  File "C:\salt\bin\lib\logging\__init__.py", line 1268, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\log\setup.py", line 313, in _log
    self, level, msg, args, exc_info=exc_info, extra=extra
Message: 'Stopped the multiprocessing logging queue listener'
Arguments: None
--- Logging error ---
Traceback (most recent call last):
  File "C:\salt\bin\lib\logging\handlers.py", line 1349, in emit
    self.enqueue(self.prepare(record))
  File "C:\salt\bin\lib\logging\handlers.py", line 1315, in enqueue
    self.queue.put_nowait(record)
  File "C:\salt\bin\lib\multiprocessing\queues.py", line 129, in put_nowait
    return self.put(obj, False)
  File "C:\salt\bin\lib\multiprocessing\queues.py", line 81, in put
    assert not self._closed
AssertionError
Call stack:
  File "C:\salt\bin\lib\site-packages\salt\log\setup.py", line 1119, in __global_logging_exception_handler
    exc_type, exc_value, exc_traceback
  File "C:\salt\bin\lib\logging\__init__.py", line 1309, in error
    self._log(ERROR, msg, args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\log\setup.py", line 313, in _log
    self, level, msg, args, exc_info=exc_info, extra=extra
Message: 'An un-handled exception was caught by salt\'s global exception handler:\nAttributeError: module \'os\' has no attribute \'fork\'\nTraceback (most recent call last):\n  File "C:\\salt\\bin\\Scripts\\salt-minion", line 26, in <module>\n    salt_minion()\n  File "C:\\salt\\bin\\lib\\site-packages\\salt\\scripts.py", line 168, in salt_minion\n    minion.start()\n  File "C:\\salt\\bin\\lib\\site-packages\\salt\\cli\\daemons.py", line 340, in start\n    super(Minion, self).start()\n  File "C:\\salt\\bin\\lib\\site-packages\\salt\\utils\\parsers.py", line 1007, in start\n    self.prepare()\n  File "C:\\salt\\bin\\lib\\site-packages\\salt\\cli\\daemons.py", line 311, in prepare\n    self.daemonize_if_required()\n  File "C:\\salt\\bin\\lib\\site-packages\\salt\\utils\\parsers.py", line 972, in daemonize_if_required\n    salt.utils.daemonize()\n  File "C:\\salt\\bin\\lib\\site-packages\\salt\\utils\\__init__.py", line 464, in daemonize\n    pid = os.fork()\nAttributeError: module \'os\' has no attribute \'fork\''
Arguments: None
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-minion", line 26, in <module>
    salt_minion()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 168, in salt_minion
    minion.start()
  File "C:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 340, in start
    super(Minion, self).start()
  File "C:\salt\bin\lib\site-packages\salt\utils\parsers.py", line 1007, in start
    self.prepare()
  File "C:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 311, in prepare
    self.daemonize_if_required()
  File "C:\salt\bin\lib\site-packages\salt\utils\parsers.py", line 972, in daemonize_if_required
    salt.utils.daemonize()
  File "C:\salt\bin\lib\site-packages\salt\utils\__init__.py", line 464, in daemonize
    pid = os.fork()
AttributeError: module 'os' has no attribute 'fork'
```

```
C:\>salt-master -d
WARNING: Unable to bind socket 0.0.0.0:4505, error: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions; Is there another salt-master running?
--- Logging error ---
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\salt\bin\lib\multiprocessing\queues.py", line 243, in _feed
    send_bytes(obj)
  File "C:\salt\bin\lib\multiprocessing\connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "C:\salt\bin\lib\multiprocessing\connection.py", line 280, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
BrokenPipeError: [WinError 232] The pipe is being closed
  File "C:\salt\bin\lib\logging\handlers.py", line 1349, in emit
    self.enqueue(self.prepare(record))
  File "C:\salt\bin\lib\logging\handlers.py", line 1315, in enqueue
    self.queue.put_nowait(record)
  File "C:\salt\bin\lib\multiprocessing\queues.py", line 129, in put_nowait
    return self.put(obj, False)
  File "C:\salt\bin\lib\multiprocessing\queues.py", line 81, in put
    assert not self._closed
AssertionError
Call stack:
  File "C:\salt\bin\Scripts\salt-master", line 22, in <module>
    salt_master()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 92, in salt_master
    master.start()
  File "C:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 204, in start
    super(Master, self).start()
  File "C:\salt\bin\lib\site-packages\salt\utils\parsers.py", line 1007, in start
    self.prepare()
  File "C:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 179, in prepare
    self.shutdown(4, 'The ports are not available to bind')
  File "C:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 220, in shutdown
    super(Master, self).shutdown(exitcode, exitmsg)
  File "C:\salt\bin\lib\site-packages\salt\utils\parsers.py", line 1020, in shutdown
    self.exit(exitcode, exitmsg)
  File "C:\salt\bin\lib\site-packages\salt\utils\parsers.py", line 264, in exit
    log.shutdown_multiprocessing_logging_listener(daemonizing=True)
  File "C:\salt\bin\lib\site-packages\salt\log\setup.py", line 946, in shutdown_multiprocessing_logging_listener
    logging.getLogger(__name__).debug('joining multiprocessing queue thread')
  File "C:\salt\bin\lib\logging\__init__.py", line 1268, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\log\setup.py", line 313, in _log
    self, level, msg, args, exc_info=exc_info, extra=extra
Message: 'joining multiprocessing queue thread'
Arguments: None
--- Logging error ---
Traceback (most recent call last):
  File "C:\salt\bin\lib\logging\handlers.py", line 1349, in emit
    self.enqueue(self.prepare(record))
  File "C:\salt\bin\lib\logging\handlers.py", line 1315, in enqueue
    self.queue.put_nowait(record)
  File "C:\salt\bin\lib\multiprocessing\queues.py", line 129, in put_nowait
    return self.put(obj, False)
  File "C:\salt\bin\lib\multiprocessing\queues.py", line 81, in put
    assert not self._closed
AssertionError
Call stack:
  File "C:\salt\bin\Scripts\salt-master", line 22, in <module>
    salt_master()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 92, in salt_master
    master.start()
  File "C:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 204, in start
    super(Master, self).start()
  File "C:\salt\bin\lib\site-packages\salt\utils\parsers.py", line 1007, in start
    self.prepare()
  File "C:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 179, in prepare
    self.shutdown(4, 'The ports are not available to bind')
  File "C:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 220, in shutdown
    super(Master, self).shutdown(exitcode, exitmsg)
  File "C:\salt\bin\lib\site-packages\salt\utils\parsers.py", line 1020, in shutdown
    self.exit(exitcode, exitmsg)
  File "C:\salt\bin\lib\site-packages\salt\utils\parsers.py", line 264, in exit
    log.shutdown_multiprocessing_logging_listener(daemonizing=True)
  File "C:\salt\bin\lib\site-packages\salt\log\setup.py", line 960, in shutdown_multiprocessing_logging_listener
    logging.getLogger(__name__).debug('Stopped the multiprocessing logging queue listener')
  File "C:\salt\bin\lib\logging\__init__.py", line 1268, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\log\setup.py", line 313, in _log
    self, level, msg, args, exc_info=exc_info, extra=extra
Message: 'Stopped the multiprocessing logging queue listener'
Arguments: None
The salt master is shutdown. The ports are not available to bind
```

### Versions Report
```
C:\>salt --versions
Salt Version:
           Salt: 2016.11.0-1126-gf589e3c

Dependency Versions:
           cffi: 1.10.0
       cherrypy: unknown
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 2.0.8
          ioflo: 1.5.5
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.3.8
         PyYAML: 3.12
          PyZMQ: 16.0.1
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.4.1
            ZMQ: 4.1.6

System Versions:
           dist:
        machine: AMD64
        release: 2016Server
         system: Windows
        version: 2016Server 10.0.14393 SP0 Multiprocessor Free
```

**Comment by thatch45** [comment]
Please omit the -d test from windows, it does not apply since windows does not have a concept of a daemon.
