### ISSUE TITLE
The pydsl 'include' fails when used with Reactor

### ISSUE THREAD

**Issue by corywright** [saltstack/salt#40627]
### Description of Issue/Question

Any `#!pydsl` files using `include()` with Reactor will fail to render.

### Setup

The Reactor config:

```sls
reactor:
  - 'ilanddev/*':
    - /srv/reactor/ilanddev/handler.sls
```

The `/srv/reactor/ilanddev/handler.sls` file:

```python
#!pydsl

include('ilanddev.monitoring')
```

The `/srv/reactor/ilanddev/monitoring.sls` file:

```sls
check-api-proxy-apache:
  runner.http.query:
    - arg:
      - 'http://www.gnu.org/'
```

### Steps to Reproduce Issue

Use the above configuration, restart the salt-master, then trigger the event:

    sudo salt-call event.send ilanddev/monitoring

From `/var/log/salt/master`:

```pytb
2017-04-11 13:08:08,224 [salt.utils.reactor][ERROR   ][2725] Failed to render "/srv/reactor/ilanddev/handler.sls":
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/reactor.py", line 70, in render_reaction
    data=data)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 309, in render_template
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/template.py", line 98, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/renderers/pydsl.py", line 359, in render
    dsl_sls = pydsl.Sls(sls, saltenv, rendered_sls)
  File "/usr/lib/python2.7/dist-packages/salt/utils/pydsl.py", line 120, in __init__
    self.included_highstate = HighState.get_active().building_highstate
AttributeError: 'NoneType' object has no attribute 'building_highstate'
```

### Versions Report

Master and minion both running latest stable:

```
# salt --versions-report
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.16.0-77-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by gtmanfred** [comment]
Thanks for reporting this, I have replicated the issue with the following container `gtmanfred/issues:40627`

```
$ container=$(docker run --rm --detach -ti gtmanfred/issues:40627 salt-master -l debug)
$ docker exec -ti $container salt-run event.send test
True
$ docker logs --tail 20 $container
[DEBUG   ] Loaded master key: /etc/salt/pki/master/master.pem
[DEBUG   ] Gathering reactors for tag salt/run/20170411165049768085/new
[DEBUG   ] Gathering reactors for tag test
[DEBUG   ] Compiling reactions for tag test
[DEBUG   ] compile template: /srv/salt/test.sls
[DEBUG   ] LazyLoaded pydsl.render
[ERROR   ] Failed to render "/srv/salt/test.sls":
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/reactor.py", line 70, in render_reaction
    data=data)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 309, in render_template
    **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/template.py", line 98, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/usr/lib/python2.7/site-packages/salt/renderers/pydsl.py", line 359, in render
    dsl_sls = pydsl.Sls(sls, saltenv, rendered_sls)
  File "/usr/lib/python2.7/site-packages/salt/utils/pydsl.py", line 120, in __init__
    self.included_highstate = HighState.get_active().building_highstate
AttributeError: 'NoneType' object has no attribute 'building_highstate'
[DEBUG   ] Gathering reactors for tag salt/run/20170411165049768085/ret
```

Thanks for reporting,
Daniel
