### ISSUE TITLE
salt-minion becomes unresponsive when disk is full

### ISSUE THREAD

**Issue by tsaridas** [saltstack/salt#40641]
### Description of Issue/Question
When disk is full salt-minion becomes unresponsive. Its probably because its trying to write the jid to disk and gets an exception.

```
2017-04-11 18:09:50,147 [salt.utils.process][ERROR   ][20799] An un-handled exception from the multiprocessing process 'SignalHandlingMultiprocessingProcess-1:66' was caught:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/process.py", line 644, in _run
    return self._original_run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1352, in _target
    Minion._thread_return(minion_instance, opts, data)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1376, in _thread_return
    with salt.utils.fopen(fn_, 'w+b') as fp_:
  File "/usr/lib/python2.7/site-packages/salt/utils/__init__.py", line 1288, in fopen
    fhandle = open(*args, **kwargs)
IOError: [Errno 28] No space left on device: '/var/cache/salt/minion/proc/20170411180949551901'
```

### Desired behaviour 
Would want that the minion does respond to commands but is not able to write anything to disk.
Maybe catch the exception and just through a warning.

### Steps to Reproduce Issue
make disk full for / or where cache directory is mounted for salt minion.

### Versions Report
2016.11.3

**Comment by gtmanfred** [comment]
You are correct, it is failing to write the jid to the disk.

Unfortunately there is not a lot we can do about this.  And making services run when the filesystem it is running on fills up.

I am going to mark this as a feature request, if you wanted to submit a pr request to try and fix this, we would appreciate it.

Thanks,
Daniel

**Comment by tsaridas** [comment]
I don't see why you close a feature request if you don't think its a bug :)

**Comment by gtmanfred** [comment]
We had an internal discussion that we did not consider this particular request a bug a bug.

Given the pervasive nature of salt's need for disk access this would prove to be an impossible endeavor to completely alleviate.

**Comment by tsaridas** [comment]
so you are saying its impossible for salt-minion to work if there is no disk space ?
