### ISSUE TITLE
Windows Master - Python 3 - Proxy minion fails

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#40640]
### Description of Issue/Question
Proxy Minion fails on Windows master using python 3.

### Setup
Set up proxy minion setup/environment.

```
Master config:
c:/salt/conf/master

pillar_roots:
  base:
    - c:/salt-manual-tests/proxy/pillar
file_roots:
  base:
    - c:/salt-manual-tests/proxy/states
```

```
proxy config:
c:/salt/conf/proxy

master: localhost
add_proxymodules_to_opts: false
```

Accept key(s):

```
C:\>salt-key
Accepted Keys:
p8000
Denied Keys:
Unaccepted Keys:
Rejected Keys:
```

### Steps to Reproduce Issue
Running the command `salt-proxy --proxyid=p8000 -l debug` gives me:
```
C:\>salt-proxy --proxyid=p8000 -l debug
[DEBUG   ] Reading configuration from c:\salt\conf\proxy
[DEBUG   ] Configuration file path: c:\salt\conf\proxy
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] Setting up "p8000" the Salt ProxyMinion
[DEBUG   ] Created pidfile: c:\salt\var\run\salt\p8000\salt-minion.pid
[INFO    ] The Proxy Minion is starting up the Salt ProxyMinion
[DEBUG   ] AsyncEventPublisher PUB socket URI: 4510
[DEBUG   ] AsyncEventPublisher PULL socket URI: 4511
[INFO    ] Starting pull socket on 4511
[DEBUG   ] SaltEvent PUB socket URI: 4510
[DEBUG   ] SaltEvent PULL socket URI: 4511
[DEBUG   ] Initializing new IPCClient for path: 4510
[INFO    ] Creating minion process manager
[DEBUG   ] Process Manager starting!
[DEBUG   ] Process Manager starting!
[DEBUG   ] Connecting to master. Attempt 1 (infinite attempts)
[DEBUG   ] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'p8000', 'tcp://127.0.0.1:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (6331)
[DEBUG   ] Setting zmq_reconnect_ivl to '6331ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'p8000', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
[ERROR   ] Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x0000022D729EE2F0>, <tornado.concurrent.Future object at 0x0000022D729E4940>)
Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\tornado\ioloop.py", line 604, in _run_callback
    ret = callback()
  File "C:\salt\bin\lib\site-packages\tornado\stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\tornado\ioloop.py", line 619, in <lambda>
    self.add_future(ret, lambda f: f.result())
  File "C:\salt\bin\lib\site-packages\tornado\concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "C:\salt\bin\lib\site-packages\tornado\gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\salt\bin\lib\site-packages\salt\crypt.py", line 476, in _authenticate
    creds = yield self.sign_in(channel=channel)
  File "C:\salt\bin\lib\site-packages\tornado\gen.py", line 1015, in run
    value = future.result()
  File "C:\salt\bin\lib\site-packages\tornado\concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "C:\salt\bin\lib\site-packages\tornado\gen.py", line 1024, in run
    yielded = self.gen.send(value)
  File "C:\salt\bin\lib\site-packages\salt\crypt.py", line 601, in sign_in
    auth['aes'] = self.verify_master(payload, master_pub='token' in sign_in_payload)
  File "C:\salt\bin\lib\site-packages\salt\crypt.py", line 942, in verify_master
    return self.extract_aes(payload, master_pub=False)
  File "C:\salt\bin\lib\site-packages\salt\crypt.py", line 867, in extract_aes
    aes, token = self.decrypt_aes(payload, master_pub)
  File "C:\salt\bin\lib\site-packages\salt\crypt.py", line 730, in decrypt_aes
    m_digest = public_decrypt(mkey.publickey(), payload['sig'])
  File "C:\salt\bin\lib\site-packages\salt\crypt.py", line 207, in public_decrypt
    return verifier.verify(message)
  File "C:\salt\bin\lib\site-packages\salt\utils\rsax931.py", line 160, in verify
    raise ValueError('Unable to decrypt message')
ValueError: Unable to decrypt message
```

### Versions Report
```
C:\>salt --versions
Salt Version:
           Salt: 2016.11.0-1126-gf589e3c

Dependency Versions:
           cffi: 1.10.0
       cherrypy: unknown
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 2.0.8
          ioflo: 1.5.5
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.3.8
         PyYAML: 3.12
          PyZMQ: 16.0.1
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.4.1
            ZMQ: 4.1.6

System Versions:
           dist:
        machine: AMD64
        release: 2016Server
         system: Windows
        version: 2016Server 10.0.14393 SP0 Multiprocessor Free
```

**Comment by frogunder** [comment]
Also see this when running `salt-master -ldebug` after the master is stopped:
```C:\>salt-master -ldebug
[DEBUG   ] Reading configuration from c:\salt\conf\master
[DEBUG   ] Multiprocessing queue logging configured for the process running under PID: 7176
[DEBUG   ] Multiprocessing queue logging configured for the process running under PID: 7176
[DEBUG   ] Configuration file path: c:\salt\conf\master
WARNING: Unable to bind socket 0.0.0.0:4505, error: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions; Is there another salt-master running?
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] Setting up the Salt Master
[INFO    ] The Salt Master is shut down
[DEBUG   ] Stopping the multiprocessing logging queue listener
--- Logging error ---
Traceback (most recent call last):
  File "C:\salt\bin\lib\logging\handlers.py", line 1349, in emit
    self.enqueue(self.prepare(record))
  File "C:\salt\bin\lib\logging\handlers.py", line 1315, in enqueue
    self.queue.put_nowait(record)
  File "C:\salt\bin\lib\multiprocessing\queues.py", line 129, in put_nowait
    return self.put(obj, False)
  File "C:\salt\bin\lib\multiprocessing\queues.py", line 81, in put
    assert not self._closed
Traceback (most recent call last):
  File "C:\salt\bin\lib\multiprocessing\queues.py", line 243, in _feed
    send_bytes(obj)
  File "C:\salt\bin\lib\multiprocessing\connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "C:\salt\bin\lib\multiprocessing\connection.py", line 280, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
BrokenPipeError: [WinError 232] The pipe is being closed
AssertionError
Call stack:
  File "C:\salt\bin\Scripts\salt-master", line 22, in <module>
    salt_master()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 92, in salt_master
    master.start()
  File "C:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 204, in start
    super(Master, self).start()
  File "C:\salt\bin\lib\site-packages\salt\utils\parsers.py", line 1007, in start
    self.prepare()
  File "C:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 179, in prepare
    self.shutdown(4, 'The ports are not available to bind')
  File "C:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 220, in shutdown
    super(Master, self).shutdown(exitcode, exitmsg)
  File "C:\salt\bin\lib\site-packages\salt\utils\parsers.py", line 1020, in shutdown
    self.exit(exitcode, exitmsg)
  File "C:\salt\bin\lib\site-packages\salt\utils\parsers.py", line 264, in exit
    log.shutdown_multiprocessing_logging_listener(daemonizing=True)
  File "C:\salt\bin\lib\site-packages\salt\log\setup.py", line 946, in shutdown_multiprocessing_logging_listener
    logging.getLogger(__name__).debug('joining multiprocessing queue thread')
  File "C:\salt\bin\lib\logging\__init__.py", line 1268, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\log\setup.py", line 313, in _log
    self, level, msg, args, exc_info=exc_info, extra=extra
Message: 'joining multiprocessing queue thread'
Arguments: None
--- Logging error ---
Traceback (most recent call last):
  File "C:\salt\bin\lib\logging\handlers.py", line 1349, in emit
    self.enqueue(self.prepare(record))
  File "C:\salt\bin\lib\logging\handlers.py", line 1315, in enqueue
    self.queue.put_nowait(record)
  File "C:\salt\bin\lib\multiprocessing\queues.py", line 129, in put_nowait
    return self.put(obj, False)
  File "C:\salt\bin\lib\multiprocessing\queues.py", line 81, in put
    assert not self._closed
AssertionError
Call stack:
  File "C:\salt\bin\Scripts\salt-master", line 22, in <module>
    salt_master()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 92, in salt_master
    master.start()
  File "C:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 204, in start
    super(Master, self).start()
  File "C:\salt\bin\lib\site-packages\salt\utils\parsers.py", line 1007, in start
    self.prepare()
  File "C:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 179, in prepare
    self.shutdown(4, 'The ports are not available to bind')
  File "C:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 220, in shutdown
    super(Master, self).shutdown(exitcode, exitmsg)
  File "C:\salt\bin\lib\site-packages\salt\utils\parsers.py", line 1020, in shutdown
    self.exit(exitcode, exitmsg)
  File "C:\salt\bin\lib\site-packages\salt\utils\parsers.py", line 264, in exit
    log.shutdown_multiprocessing_logging_listener(daemonizing=True)
  File "C:\salt\bin\lib\site-packages\salt\log\setup.py", line 960, in shutdown_multiprocessing_logging_listener
    logging.getLogger(__name__).debug('Stopped the multiprocessing logging queue listener')
  File "C:\salt\bin\lib\logging\__init__.py", line 1268, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\log\setup.py", line 313, in _log
    self, level, msg, args, exc_info=exc_info, extra=extra
Message: 'Stopped the multiprocessing logging queue listener'
Arguments: None
The salt master is shutdown. The ports are not available to bind
```

**Comment by gtmanfred** [comment]
Can you retest this with the new py3 package?

I am not able to replicate this error at all.  The salt master doesn't shutdown and the proxy minion returns.

![salt proxy return](http://i.imgur.com/fFNGPgo.png)

**Comment by frogunder** [comment]
Yea, the new py3 package is working better for me. I get the proxy-minion to return and the salt-master doesn’t shut down.
I do however see some issues in the minion log. Also the proxy-minion web page gets created but I cannot communicate with it.

```
[CRITICAL] Failed to run proxy's grains function!
Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\loader.py", line 747, in grains
    ret = proxy[proxytype+'.grains']()
  File "C:\salt\bin\lib\site-packages\salt\proxy\rest_sample.py", line 85, in grains
    DETAILS['grains_cache'] = r['dict']
KeyError: 'dict'

[ERROR   ] Failed to import module boto_ec2, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1343, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "C:\salt\bin\lib\imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "C:\salt\bin\lib\imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 669, in exec_module
  File "<frozen importlib._bootstrap_external>", line 774, in get_code
  File "C:\salt\bin\lib\imp.py", line 156, in get_data
    return file.read()
  File "C:\salt\bin\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 35274: character maps to <undefined>

[DEBUG   ] SMBIOS: neither dmidecode nor smbios found!
[DEBUG   ] Failed to import module win_network:
Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1343, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "C:\salt\bin\lib\imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "C:\salt\bin\lib\imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\salt\bin\lib\site-packages\salt\modules\win_network.py", line 16, in <module>
    from salt.modules.network import (wol, get_hostname, interface, interface_ip,
ImportError: No module named 'salt.modules.network'

[ERROR   ] Exception raised when processing __virtual__ function for salt.loader.localhost.int.module.win_servermanager. Module will not be loaded: 'osversion'
Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1605, in process_virtual
    virtual = getattr(mod, virtual_func)()
  File "C:\salt\bin\lib\site-packages\salt\modules\win_servermanager.py", line 44, in __virtual__
    if salt.utils.version_cmp(__grains__['osversion'], '6.1.7600') == -1:
  File "C:\salt\bin\lib\site-packages\salt\utils\context.py", line 211, in __getitem__
    return self._dict()[key]
KeyError: 'osversion'
```

**Comment by gtmanfred** [comment]
The grains error should be resolved by this https://github.com/saltstack/salt-contrib/pull/178

with test.ping returning a stack trace appears to be because of this stack trace.

```
[ERROR   ] Failed to import module boto_ec2, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1343, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "C:\salt\bin\lib\imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "C:\salt\bin\lib\imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 669, in exec_module
  File "<frozen importlib._bootstrap_external>", line 774, in get_code
  File "C:\salt\bin\lib\imp.py", line 156, in get_data
    return file.read()
  File "C:\salt\bin\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 35274: character maps to <undefined>
```


So the `__proxy__` modules are not loaded.

I am not quite sure how to fix this.

**Comment by gtmanfred** [comment]
@twangboy have you seen the charmap codec error before?

Thanks,
Daniel

**Comment by twangboy** [comment]
@gtmanfred Yeah. I see it all the time. I don't know how to fix it. I tried putting some print statements in there to see what was throwing it but it didn't seem to show anything.

**Comment by gtmanfred** [comment]
@frogunder can you run the tests again with `multiprocessing: False` and the updated salt-contrib.

I need to do further tests on the charmap, but that one just disappeared on me when i moved the boto_ec2.py module out of there and then ran salt-proxy, and then moved boto_ec2.py back, and restarted salt-proxy.

Thanks,
Daniel

**Comment by twangboy** [comment]
@gtmanfred I thought this was just a Py3 thing, but I'm seeing it in the test suite on Py2... though the tests continue...

**Comment by twangboy** [comment]
@Ch3LL It needs to use the python in `C:\Python27\` for the test suite, not the one installed by salt.

**Comment by twangboy** [comment]
@gtmanfred I don't think Salt on Windows works very well with `multiprocessing: False`

**Comment by gtmanfred** [comment]
So, when testing the proxy rest sample minion, the `__proxy__` dictionary is not populated in the minion modules when `multiprocessing: True` (the default) is set.

Once I set it to False, the proxy minion worked correctly.

@cro was the one that told me he thought that this was set on all the windows minions?

**Comment by twangboy** [comment]
Default is `multiprocessing: True` in Windows. There are other issues when multiprocessing is off. The Job cache is messed up. It has to do with how Windows forks processes. I wish I understood it better and could explain it coherently.

**Comment by cachedout** [comment]
We're just waiting for a review from @cro on #40909 before closing this.
