### ISSUE TITLE
sync_after_install: grains causes salt-cloud to fail

### ISSUE THREAD

**Issue by notpeter** [saltstack/salt#40695]
### Description of Issue/Question

I have a working salt/salt-cloud setup. Adding `sync_after_install: grains` to my /etc/salt/cloud file causes 100% of my salt-cloud runs to exit with failure.  The minion is configured properly (keys in place, bus up and functioning, etc) but salt-cloud just quits like a jerk face with:

````
[ERROR   ] There was a profile error: Failed to authenticate! This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).
````

This may be a duplicate of #34124 where users reported similar failures with 2016.3.0 (Arch) and 2016.3.4 (Xenial).

### Setup

Running salt-cloud on a master to spin new AWS minions. No notable master/cloud/minion config settings deviating from defaults.

/etc/salt/cloud
````
sync_after_install: grains
script: /etc/salt/cloud.deploy.d/bootstrap-salt.sh
script_args: stable 2016.11.3
````

### Steps to Reproduce Issue

1. Add `sync_after_install: grains`  to your cloud config.
2. Spin an instance: `salt-cloud -l debug -p myprofile myhost.domain.tld
3. Wait till this shows up:

````
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'salt.HOSTNAME.TLD_master', 'tcp://0.0.0.0:4506', 'clear')
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[ERROR   ] There was a profile error: Failed to authenticate! This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 284, in run
    self.config.get('names')
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1458, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1315, in create
    timeout=self.opts['timeout']
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 639, in cmd
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 337, in run_job
    return self._check_pub_data(pub_data)
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 256, in _check_pub_data
    'Failed to authenticate! This is most likely because this '
EauthAuthenticationError: Failed to authenticate! This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).
````

Everything works great when sync_after_install is commented out.

### Versions Report
````
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.24.0
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-64-generic
         system: Linux
        version: Ubuntu 16.04 xenial
````

**Comment by gtmanfred** [comment]
I am able to replicate this by putting the setting in /etc/salt/cloud

Thanks for the report,
Daniel

**Comment by anitakrueger** [comment]
Is this marked to be fixed in a certain release by any chance? I just ran into the same issue and was wondering what was going on.

**Comment by peterclearmetal** [comment]
@anitakrueger This has not yet been fixed in any release, nor in develop.

**Comment by gtmanfred** [comment]
It is not currently on the list of things to get fixed for a scheduled release.
