### ISSUE TITLE
Master (EC2) connectivity issues with Minion (Azure) with tcp transport

### ISSUE THREAD

**Issue by naemono** [saltstack/salt#40794]
### Description of Issue/Question

I'm having ongoing issues with master -> minion (or vice versa) connectivity issues with minions in azure, and a master in ec2.  The connection seems to come and go (test.ping works intermittently).  There have been a multitude of github issues I've read through about issues with zeromq on azure (and elsewhere), which is why I moved to the tcp transport to try and get around these issues.  Unfortunately there still seem to be either transport bugs in tcp, or other issues that I can't quite pinpoint (yet).

The below master tcpdump will show me trying to run a state.sls against a targeted minion, and the master reaching out to the minion, but receiving no response for a period of time, then magically it'll start receiving responses.

master tcpdump
```
14:11:37.711158 IP 13.65.242.79.45928 > ip-10-0-100-90.us-east-2.compute.internal.4506: Flags [P.], seq 1:3907, ack 1, win 229, options [nop,nop,TS val 2419903 ecr 195140296], length 3906
14:11:37.711174 IP ip-10-0-100-90.us-east-2.compute.internal.4506 > 13.65.242.79.45928: Flags [.], ack 3907, win 350, options [nop,nop,TS val 195140308 ecr 2419903], length 0
14:11:37.715698 IP ip-10-0-100-90.us-east-2.compute.internal.4506 > 13.65.242.79.45928: Flags [P.], seq 1:85, ack 3907, win 350, options [nop,nop,TS val 195140309 ecr 2419903], length 84
14:11:37.761357 IP 13.65.242.79.45928 > ip-10-0-100-90.us-east-2.compute.internal.4506: Flags [.], ack 85, win 229, options [nop,nop,TS val 2419915 ecr 195140309], length 0
14:11:37.785111 IP 13.65.242.79.45928 > ip-10-0-100-90.us-east-2.compute.internal.4506: Flags [F.], seq 3907, ack 85, win 229, options [nop,nop,TS val 2419921 ecr 195140309], length 0
14:11:37.785280 IP ip-10-0-100-90.us-east-2.compute.internal.4506 > 13.65.242.79.45928: Flags [F.], seq 85, ack 3908, win 350, options [nop,nop,TS val 195140326 ecr 2419921], length 0
14:11:37.807280 IP 13.65.242.79.45900 > ip-10-0-100-90.us-east-2.compute.internal.4506: Flags [F.], seq 2175, ack 11613, win 529, options [nop,nop,TS val 2419927 ecr 195135735], length 0
14:11:37.807451 IP ip-10-0-100-90.us-east-2.compute.internal.4506 > 13.65.242.79.45900: Flags [F.], seq 11613, ack 2176, win 319, options [nop,nop,TS val 195140332 ecr 2419927], length 0
14:11:37.831348 IP 13.65.242.79.45928 > ip-10-0-100-90.us-east-2.compute.internal.4506: Flags [.], ack 86, win 229, options [nop,nop,TS val 2419933 ecr 195140326], length 0
14:11:37.852885 IP 13.65.242.79.45900 > ip-10-0-100-90.us-east-2.compute.internal.4506: Flags [.], ack 11614, win 529, options [nop,nop,TS val 2419938 ecr 195140332], length 0
14:12:08.605349 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.53866: Flags [P.], seq 0:208, ack 1, win 219, options [nop,nop,TS val 195148032 ecr 2268066], length 208
14:12:08.605392 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.53714: Flags [P.], seq 0:208, ack 1, win 210, options [nop,nop,TS val 195148032 ecr 2125163], length 208
14:12:10.653366 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.53718: Flags [P.], seq 0:208, ack 1, win 219, options [nop,nop,TS val 195148544 ecr 2125217], length 208
14:12:12.701361 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.53862: Flags [P.], seq 0:208, ack 1, win 210, options [nop,nop,TS val 195149056 ecr 2268013], length 208
14:14:08.925365 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.53714: Flags [P.], seq 0:208, ack 1, win 210, options [nop,nop,TS val 195178112 ecr 2125163], length 208
14:14:08.925397 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.53866: Flags [P.], seq 0:208, ack 1, win 219, options [nop,nop,TS val 195178112 ecr 2268066], length 208
14:14:10.973378 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.53718: Flags [P.], seq 0:208, ack 1, win 219, options [nop,nop,TS val 195178624 ecr 2125217], length 208
14:14:13.021366 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.53862: Flags [P.], seq 0:208, ack 1, win 210, options [nop,nop,TS val 195179136 ecr 2268013], length 208
14:16:09.245361 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.53866: Flags [P.], seq 0:208, ack 1, win 219, options [nop,nop,TS val 195208192 ecr 2268066], length 208
14:16:09.245395 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.53714: Flags [P.], seq 0:208, ack 1, win 210, options [nop,nop,TS val 195208192 ecr 2125163], length 208
14:16:11.293373 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.53718: Flags [P.], seq 0:208, ack 1, win 219, options [nop,nop,TS val 195208704 ecr 2125217], length 208
14:16:13.341360 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.53862: Flags [P.], seq 0:208, ack 1, win 210, options [nop,nop,TS val 195209216 ecr 2268013], length 208
14:16:15.261339 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.54010: Flags [.], ack 398, win 219, options [nop,nop,TS val 195209696 ecr 2414283], length 0
14:16:15.261352 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.54006: Flags [.], ack 1, win 210, options [nop,nop,TS val 195209696 ecr 2414283], length 0
14:17:30.397352 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.54006: Flags [.], ack 1, win 210, options [nop,nop,TS val 195228480 ecr 2414283], length 0
14:17:30.397366 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.54010: Flags [.], ack 398, win 219, options [nop,nop,TS val 195228480 ecr 2414283], length 0
14:17:51.994377 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.54010: Flags [P.], seq 1249:2289, ack 398, win 219, options [nop,nop,TS val 195233879 ecr 2414283], length 1040
14:17:51.995676 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.54006: Flags [P.], seq 1249:2289, ack 1, win 210, options [nop,nop,TS val 195233879 ecr 2414283], length 1040
14:17:52.241371 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.54006: Flags [P.], seq 1249:2289, ack 1, win 210, options [nop,nop,TS val 195233941 ecr 2414283], length 1040
14:17:52.241385 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.54010: Flags [P.], seq 1249:2289, ack 398, win 219, options [nop,nop,TS val 195233941 ecr 2414283], length 1040
14:17:52.489357 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.54010: Flags [P.], seq 1249:2289, ack 398, win 219, options [nop,nop,TS val 195234003 ecr 2414283], length 1040
14:17:52.489368 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.54006: Flags [P.], seq 1249:2289, ack 1, win 210, options [nop,nop,TS val 195234003 ecr 2414283], length 1040
14:17:52.985368 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.54006: Flags [P.], seq 1249:2289, ack 1, win 210, options [nop,nop,TS val 195234127 ecr 2414283], length 1040
14:17:52.985382 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.54010: Flags [P.], seq 1249:2289, ack 398, win 219, options [nop,nop,TS val 195234127 ecr 2414283], length 1040
14:17:53.977358 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.54010: Flags [P.], seq 1249:2289, ack 398, win 219, options [nop,nop,TS val 195234375 ecr 2414283], length 1040
14:17:53.977368 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.54006: Flags [P.], seq 1249:2289, ack 1, win 210, options [nop,nop,TS val 195234375 ecr 2414283], length 1040
14:17:55.965355 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.54010: Flags [P.], seq 1249:2289, ack 398, win 219, options [nop,nop,TS val 195234872 ecr 2414283], length 1040
14:17:55.965364 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.54006: Flags [P.], seq 1249:2289, ack 1, win 210, options [nop,nop,TS val 195234872 ecr 2414283], length 1040
14:17:59.941360 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.54010: Flags [P.], seq 1249:2289, ack 398, win 219, options [nop,nop,TS val 195235866 ecr 2414283], length 1040
14:17:59.941370 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.54006: Flags [P.], seq 1249:2289, ack 1, win 210, options [nop,nop,TS val 195235866 ecr 2414283], length 1040
14:18:07.901372 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.54010: Flags [P.], seq 1249:2289, ack 398, win 219, options [nop,nop,TS val 195237856 ecr 2414283], length 1040
14:18:07.901383 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.54006: Flags [P.], seq 1249:2289, ack 1, win 210, options [nop,nop,TS val 195237856 ecr 2414283], length 1040
14:18:09.565369 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.53714: Flags [P.], seq 0:208, ack 1, win 210, options [nop,nop,TS val 195238272 ecr 2125163], length 208
14:18:09.565415 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.53866: Flags [P.], seq 0:208, ack 1, win 219, options [nop,nop,TS val 195238272 ecr 2268066], length 208
14:18:11.613393 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.53718: Flags [P.], seq 0:208, ack 1, win 219, options [nop,nop,TS val 195238784 ecr 2125217], length 208
14:18:13.661363 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.53862: Flags [P.], seq 0:208, ack 1, win 210, options [nop,nop,TS val 195239296 ecr 2268013], length 208
14:18:23.805364 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.54010: Flags [P.], seq 1249:2289, ack 398, win 219, options [nop,nop,TS val 195241832 ecr 2414283], length 1040
14:18:23.805375 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.54006: Flags [P.], seq 1249:2289, ack 1, win 210, options [nop,nop,TS val 195241832 ecr 2414283], length 1040
14:18:55.645385 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.54010: Flags [P.], seq 1249:2289, ack 398, win 219, options [nop,nop,TS val 195249792 ecr 2414283], length 1040
14:18:55.645399 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.54006: Flags [P.], seq 1249:2289, ack 1, win 210, options [nop,nop,TS val 195249792 ecr 2414283], length 1040
14:19:59.261365 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.54010: Flags [P.], seq 1249:2289, ack 398, win 219, options [nop,nop,TS val 195265696 ecr 2414283], length 1040
14:19:59.261379 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.54006: Flags [P.], seq 1249:2289, ack 1, win 210, options [nop,nop,TS val 195265696 ecr 2414283], length 1040
14:20:09.885355 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.53866: Flags [P.], seq 0:208, ack 1, win 219, options [nop,nop,TS val 195268352 ecr 2268066], length 208
14:20:09.885390 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.53714: Flags [P.], seq 0:208, ack 1, win 210, options [nop,nop,TS val 195268352 ecr 2125163], length 208
14:20:45.940860 IP 13.65.242.79.54180 > ip-10-0-100-90.us-east-2.compute.internal.4505: Flags [S], seq 2884879768, win 29200, options [mss 1440,sackOK,TS val 2556960 ecr 0,nop,wscale 7], length 0
14:20:45.940891 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.54180: Flags [S.], seq 142243698, ack 2884879769, win 26847, options [mss 8961,sackOK,TS val 195277365 ecr 2556960,nop,wscale 7], length 0
14:20:45.986211 IP 13.65.242.79.54180 > ip-10-0-100-90.us-east-2.compute.internal.4505: Flags [.], ack 1, win 229, options [nop,nop,TS val 2556972 ecr 195277365], length 0
14:20:46.016643 IP 13.65.242.79.46064 > ip-10-0-100-90.us-east-2.compute.internal.4506: Flags [S], seq 2676345603, win 29200, options [mss 1440,sackOK,TS val 2556979 ecr 0,nop,wscale 7], length 0
14:20:46.016672 IP ip-10-0-100-90.us-east-2.compute.internal.4506 > 13.65.242.79.46064: Flags [S.], seq 3307488045, ack 2676345604, win 26847, options [mss 8961,sackOK,TS val 195277384 ecr 2556979,nop,wscale 7], length 0
```

Master debug logs (Relevant items) where you finally see the auth request from the minion
```
2017-04-20 14:20:46,062 [salt.transport.mixins.auth][INFO    ][31990] Authentication request from f3fdf66c-4800-4064-99be-8d414c10b779
2017-04-20 14:20:46,069 [salt.transport.mixins.auth][INFO    ][31990] Authentication accepted from f3fdf66c-4800-4064-99be-8d414c10b779
```

Minion debug logs
```
2017-04-20 14:11:37,619 [salt.transport.tcp][DEBUG   ][16203] Initializing new AsyncTCPReqChannel for ('/etc/salt/pki/minion', 'f3fdf66c-4800-4064-99be-8d414c10b779', 'tcp://52.14.6.*:4506', 'aes')
2017-04-20 14:11:37,619 [salt.crypt       ][DEBUG   ][16203] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'f3fdf66c-4800-4064-99be-8d414c10b779', 'tcp://52.14.6.*:4506')
2017-04-20 14:20:45,914 [salt.transport.tcp][DEBUG   ][6402] tcp stream to 52.14.6.*:4505 closed, unable to recv
2017-04-20 14:20:45,915 [salt.utils.event ][DEBUG   ][6402] Sending event: tag = __master_disconnected; data = {'_stamp': '2017-04-20T14:20:45.915457', 'master': 'salt.production.controlplane.***..cloud'}
2017-04-20 14:20:45,917 [salt.minion      ][DEBUG   ][6402] Minion of "salt.production.controlplane.***..cloud" is handling event tag '__master_disconnected'
2017-04-20 14:20:45,917 [salt.minion      ][INFO    ][6402] Connection to master salt.production.controlplane.***..cloud lost
2017-04-20 14:20:45,925 [salt.minion      ][INFO    ][6402] Trying to tune in to next master from master-list
2017-04-20 14:20:45,926 [salt.minion      ][INFO    ][6402] Moving possibly failed master salt.production.controlplane.***..cloud to the end of the list of masters
2017-04-20 14:20:45,962 [salt.minion      ][DEBUG   ][6402] Connecting to master. Attempt 1 (infinite attempts)
2017-04-20 14:20:45,963 [salt.utils.event ][DEBUG   ][6402] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_dfec2834d3_pub.ipc
2017-04-20 14:20:45,964 [salt.utils.event ][DEBUG   ][6402] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_dfec2834d3_pull.ipc
2017-04-20 14:20:45,964 [salt.crypt       ][DEBUG   ][6402] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'f3fdf66c-4800-4064-99be-8d414c10b779', 'tcp://52.14.6.*:4506')
2017-04-20 14:20:45,973 [salt.crypt       ][DEBUG   ][6402] Loaded minion key: /etc/salt/pki/minion/minion.pem
2017-04-20 14:20:45,983 [salt.transport.tcp][DEBUG   ][6402] Initializing new AsyncTCPReqChannel for ('/etc/salt/pki/minion', 'f3fdf66c-4800-4064-99be-8d414c10b779', 'tcp://52.14.6.*:4506', 'clear')
2017-04-20 14:20:45,992 [tornado.application][ERROR   ][6402] Exception in callback <function handle_future at 0x7f966a59e398> for <tornado.concurrent.Future object at 0x7f9658e5d250>
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 300, in _set_done
    cb(self)
  File "/usr/lib/python2.7/dist-packages/salt/transport/tcp.py", line 823, in handle_future
    self.io_loop.add_callback(self.connect_callback, response)
  File "/usr/lib/python2.7/dist-packages/tornado/ioloop.py", line 917, in add_callback
    stack_context.wrap(callback), *args, **kwargs))
TypeError: the first argument must be callable
2017-04-20 14:20:46,106 [salt.crypt       ][DEBUG   ][6402] Decrypting the current master AES key
2017-04-20 14:20:46,107 [salt.crypt       ][DEBUG   ][6402] Loaded minion key: /etc/salt/pki/minion/minion.pem
2017-04-20 14:20:46,127 [salt.utils.event ][DEBUG   ][6402] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_dfec2834d3_pub.ipc
2017-04-20 14:20:46,128 [salt.utils.event ][DEBUG   ][6402] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_dfec2834d3_pull.ipc
2017-04-20 14:20:46,128 [salt.transport.ipc][DEBUG   ][6402] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_dfec2834d3_pull.ipc
2017-04-20 14:20:46,136 [salt.utils.event ][DEBUG   ][6402] Sending event: tag = salt/auth/creds; data = {'_stamp': '2017-04-20T14:20:46.135955', 'creds': {'publish_port': 4505, 'aes': 'wvM9RULFdXP7Ra1knu5c2F/jp3hXb2RP3JakkSo3DMW5hsVQ4Hquqr16+Vlsbb75R8dlQZTUbbs=', 'master_uri': 'tcp://52.14.6.*:4506'}, 'key': ('/etc/salt/pki/minion', 'f3fdf66c-4800-4064-99be-8d414c10b779', 'tcp://52.14.6.*:4506')}
2017-04-20 14:20:46,136 [salt.transport.tcp][DEBUG   ][6402] tcp stream to 52.14.6.*:4506 closed, unable to recv
2017-04-20 14:20:46,138 [salt.minion      ][DEBUG   ][6402] Minion of "salt.production.controlplane.***..cloud" is handling event tag 'salt/auth/creds'
2017-04-20 14:20:46,145 [salt.minion      ][DEBUG   ][6402] Updating auth data for ('/etc/salt/pki/minion', 'f3fdf66c-4800-4064-99be-8d414c10b779', 'tcp://52.14.6.*:4506'): {'publish_port': 4505, 'aes': 'wvM9RULFdXP7Ra1knu5c2F/jp3hXb2RP3JakkSo3DMW5hsVQ4Hquqr16+Vlsbb75R8dlQZTUbbs=', 'master_uri': 'tcp://52.14.6.*:4506'} -> {'publish_port': 4505, 'aes': 'wvM9RULFdXP7Ra1knu5c2F/jp3hXb2RP3JakkSo3DMW5hsVQ4Hquqr16+Vlsbb75R8dlQZTUbbs=', 'master_uri': 'tcp://52.14.6.*:4506'}
2017-04-20 14:20:46,183 [salt.transport.ipc][DEBUG   ][6402] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_dfec2834d3_pull.ipc
2017-04-20 14:20:46,184 [salt.utils.event ][DEBUG   ][6402] Sending event: tag = __master_connected; data = {'_stamp': '2017-04-20T14:20:46.184402', 'master': 'salt.production.controlplane.***..cloud'}
2017-04-20 14:20:46,186 [salt.crypt       ][DEBUG   ][6402] Loaded minion key: /etc/salt/pki/minion/minion.pem
2017-04-20 14:20:46,195 [salt.minion      ][INFO    ][6402] Re-initialising subsystems for new master salt.production.controlplane.***..cloud
2017-04-20 14:20:46,195 [salt.config      ][DEBUG   ][6402] Reading configuration from /etc/salt/minion
2017-04-20 14:20:46,324 [salt.config      ][DEBUG   ][6402] Including configuration from '/etc/salt/minion.d/_schedule.conf'
2017-04-20 14:20:46,332 [salt.config      ][DEBUG   ][6402] Reading configuration from /etc/salt/minion.d/_schedule.conf
2017-04-20 14:20:46,333 [salt.config      ][DEBUG   ][6402] Including configuration from '/etc/salt/minion.d/id.conf'
2017-04-20 14:20:46,334 [salt.config      ][DEBUG   ][6402] Reading configuration from /etc/salt/minion.d/id.conf
2017-04-20 14:20:46,342 [salt.config      ][DEBUG   ][6402] Including configuration from '/etc/salt/minion.d/objectrocket.conf'
2017-04-20 14:20:46,343 [salt.config      ][DEBUG   ][6402] Reading configuration from /etc/salt/minion.d/objectrocket.conf
2017-04-20 14:20:46,353 [salt.config      ][DEBUG   ][6402] Including configuration from '/etc/salt/minion.d/transport.conf'
2017-04-20 14:20:46,354 [salt.config      ][DEBUG   ][6402] Reading configuration from /etc/salt/minion.d/transport.conf
2017-04-20 14:20:46,709 [salt.loaded.int.grains.core][DEBUG   ][6402] Please install 'virt-what' to improve results of the 'virtual' grain.
2017-04-20 14:20:46,841 [salt.transport.tcp][DEBUG   ][6402] Initializing new AsyncTCPReqChannel for ('/etc/salt/pki/minion', 'f3fdf66c-4800-4064-99be-8d414c10b779', 'tcp://52.14.6.*:4506', 'aes')
2017-04-20 14:20:46,842 [salt.crypt       ][DEBUG   ][6402] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'f3fdf66c-4800-4064-99be-8d414c10b779', 'tcp://52.14.6.*:4506')
2017-04-20 14:20:46,947 [salt.transport.tcp][DEBUG   ][6402] Initializing new AsyncTCPReqChannel for ('/etc/salt/pki/minion', 'f3fdf66c-4800-4064-99be-8d414c10b779', 'tcp://52.14.6.*:4506', 'aes')
2017-04-20 14:20:46,948 [salt.crypt       ][DEBUG   ][6402] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'f3fdf66c-4800-4064-99be-8d414c10b779', 'tcp://52.14.6.*:4506')
2017-04-20 14:20:47,047 [salt.minion      ][INFO    ][6402] Minion is ready to receive requests!
2017-04-20 14:20:47,048 [salt.utils.lazy  ][DEBUG   ][6402] LazyLoaded config.merge
2017-04-20 14:20:47,049 [salt.utils.lazy  ][DEBUG   ][6402] LazyLoaded mine.update
2017-04-20 14:20:47,050 [salt.minion      ][DEBUG   ][6402] Minion of "salt.production.controlplane.***.cloud" is handling event tag '__master_connected'
```

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

Master config
```
transport: tcp
log_level: debug
open_mode: False
auto_accept: False
worker_threads: 40

gitfs_provider: gitpython
fileserver_backend:
  - git

gitfs_base: master

gitfs_remotes:
  - git@github.com:******/cloud-states.git:
    - root: states
    - name: states

git_pillar_provider: gitpython

ext_pillar:
  - git:
    # SSH key authentication
    - master git@github.com:*****/cloud-states.git:
      # Pillar SLS files will be read from the 'pillar' subdirectory in
      # this repository
      - root: pillar
```

minion config
```
master:
  - salt.production.controlplane.****.cloud
master_type: failover
master_alive_interval: 30
id: f3fdf66c-4800-4064-99be-8d414c10b779
log_level: debug
master_tries: -1
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

Create master in ec2, and minion in azure, and watch the fire.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

minion
```
root@f3fdf66c-4800-4064-99be-8d414c10b779:/etc/salt/minion.d# salt-minion --versions-report
Salt Version:
           Salt: 2016.11.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-47-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

master:
```
root@ip-10-0-100-90:/etc/salt/master.d# salt --versions-report
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 3.5.0
       dateutil: 2.4.2
          gitdb: 2.0.0
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: 0.24.0
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-72-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by naemono** [comment]
This could potentially be related to #36866

I'm testing now....

**Comment by naemono** [comment]
This configuration change (removing master_alive_interval) didn't resolve the issue:

```
15:12:28.708260 IP 13.65.242.79.47082 > ip-10-0-100-90.us-east-2.compute.internal.4506: Flags [F.], seq 2175, ack 11629, win 529, options [nop,nop,TS val 3332652 ecr 196045590], length 0
15:12:28.708338 IP ip-10-0-100-90.us-east-2.compute.internal.4506 > 13.65.242.79.47098: Flags [F.], seq 31385, ack 21062, win 853, options [nop,nop,TS val 196053057 ecr 3332652], length 0
15:12:28.708648 IP ip-10-0-100-90.us-east-2.compute.internal.4506 > 13.65.242.79.47082: Flags [F.], seq 11629, ack 2176, win 319, options [nop,nop,TS val 196053057 ecr 3332652], length 0
15:12:28.749812 IP 13.65.242.79.47108 > ip-10-0-100-90.us-east-2.compute.internal.4506: Flags [.], ack 86, win 229, options [nop,nop,TS val 3332662 ecr 196053056], length 0
15:12:28.753928 IP 13.65.242.79.47098 > ip-10-0-100-90.us-east-2.compute.internal.4506: Flags [.], ack 31386, win 1444, options [nop,nop,TS val 3332663 ecr 196053057], length 0
15:12:28.755585 IP 13.65.242.79.47082 > ip-10-0-100-90.us-east-2.compute.internal.4506: Flags [.], ack 11630, win 529, options [nop,nop,TS val 3332664 ecr 196053057], length 0
15:16:55.709412 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.55004: Flags [.], ack 398, win 219, options [nop,nop,TS val 196119808 ecr 3324237], length 0
15:18:10.973365 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.55004: Flags [.], ack 398, win 219, options [nop,nop,TS val 196138624 ecr 3324237], length 0
15:18:24.320166 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.55004: Flags [P.], seq 5857:6113, ack 398, win 219, options [nop,nop,TS val 196141960 ecr 3324237], length 256
15:18:24.565392 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.55004: Flags [P.], seq 5857:6113, ack 398, win 219, options [nop,nop,TS val 196142022 ecr 3324237], length 256
15:18:24.813359 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.55004: Flags [P.], seq 5857:6113, ack 398, win 219, options [nop,nop,TS val 196142084 ecr 3324237], length 256
15:18:25.309394 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.55004: Flags [P.], seq 5857:6113, ack 398, win 219, options [nop,nop,TS val 196142208 ecr 3324237], length 256
15:18:26.301368 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.55004: Flags [P.], seq 5857:6113, ack 398, win 219, options [nop,nop,TS val 196142456 ecr 3324237], length 256
15:18:28.289354 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.55004: Flags [P.], seq 5857:6113, ack 398, win 219, options [nop,nop,TS val 196142953 ecr 3324237], length 256
15:18:32.269361 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.55004: Flags [P.], seq 5857:6113, ack 398, win 219, options [nop,nop,TS val 196143948 ecr 3324237], length 256
15:18:40.221365 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.55004: Flags [P.], seq 5857:6113, ack 398, win 219, options [nop,nop,TS val 196145936 ecr 3324237], length 256
15:18:56.125363 IP ip-10-0-100-90.us-east-2.compute.internal.4505 > 13.65.242.79.55004: Flags [P.], seq 5857:6113, ack 398, win 219, options [nop,nop,TS val 196149912 ecr 3324237], length 256
```

**Comment by naemono** [comment]
Even the minion running this patch
#39222
disappears after a period of time.

**Comment by naemono** [comment]
#38157 May very well resolve this issue... 

Specifically

```
tcp_keepalive_idle: 10
tcp_keepalive_cnt: 2
tcp_keepalive_intvl: 10
```

doing more extended testing now....

**Comment by Ch3LL** [comment]
You can also try https://github.com/saltstack/salt/pull/40614 which fixes https://github.com/saltstack/salt/issues/39463

A new option was added `tcp_authentication_retries` to help with some connection issues with tcp minions.

**Comment by naemono** [comment]
@Ch3LL #40614 and #39222 are the same thing... It in and of itself didn't resolve the issue... still testing.

**Comment by naemono** [comment]
Closing issue.  

@Ch3LL there probably should be some documentation here
https://docs.saltstack.com/en/latest/topics/transports/tcp.html
surrounding these options to relieve pain for future folks.

Otherwise, things look good now.
