### ISSUE TITLE
Passing client_timeout to docker.pull is causing errors

### ISSUE THREAD

**Issue by gtmanfred** [saltstack/salt#40864]
### Description of Issue/Question
We shouldn't be passing client_timeout to docker.pull.  For some reason it is not getting stripped from the client_kwargs and causes this error

```
[DEBUG   ] Attempting to run docker-py's "pull" function with args=('zookeeper',) and kwargs={'tag': 'latest', 'stream': True, 'client_timeout': 60}
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 202, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/dockermod.py", line 3462, in pull
    response = _client_wrapper('pull', repo_name, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/dockermod.py", line 394, in wrapper
    return wrapped(*args, **salt.utils.clean_kwargs(**kwargs))
  File "/usr/lib/python2.7/site-packages/salt/modules/dockermod.py", line 618, in _client_wrapper
    raise CommandExecutionError(msg)
CommandExecutionError: Unable to perform pull: pull() got an unexpected keyword argument 'client_timeout'
Error running 'docker.pull': Unable to perform pull: pull() got an unexpected keyword argument 'client_timeout'
```

### Setup
nitrogen or develop, just call `salt-call docker.pull zookeeper`

### Versions Report
nitrogen and develop

**Comment by gtmanfred** [comment]
@terminalmage made an issue for that bug here.
