### ISSUE TITLE
Salt job scheduling

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#40915]
### Description of Issue/Question

I have a state which will add a job as follows,
job2:
  schedule.present:
    - function: cloud.action
    - job_args:
      - stop
    - job_kwargs:
        instance: CRI-IIS
    - when:
        - Thursday 12:35pm

On executing this state it added a job /etc/salt/minion.d/__schedule.conf

But the job does execute at the specified interval. Do i need to enable anything in master or minion config?

**Comment by gtmanfred** [comment]
The job does execute or it doesn't?

If it is in the scheduler, it should be processed.  Can you enable debug logging on the salt minion, and check the /var/log/salt/minion for the job to run?

Thanks,
Daniel

**Comment by sumeetisp** [comment]
Sorry for the typo. It doesn't execute. I will enable logging and verify.

**Comment by sumeetisp** [comment]
2017-04-28 07:16:09,703 [salt.utils.schedule][ERROR   ][12480] Unhandled exception running cloud.action
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/schedule.py", line 836, in handle_func
    ret['return'] = self.functions[func](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/cloud.py", line 237, in action
    info = client.action(fun, cloudmap, names, provider, instance, kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 486, in action
    return mapper.do_action(names, kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1529, in do_action
    vm_name, kwargs, call='action'

**Comment by gtmanfred** [comment]
Which cloud provider are you running `stop` on?

Thanks,
Daniel

**Comment by sumeetisp** [comment]
AWS
