### ISSUE TITLE
Salt mysql.user_info

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#40920]
### Description of Issue/Question

When executing salt <target> mysql.user_info <some user> using rest api call i get the following output in the event queue,
```
salt/job/20170427113629134034/new       {
    "_stamp": "2017-04-27T11:36:29.137206",
    "arg": [
        "user=root"
    ],
    "fun": "mysql.user_info",
    "jid": "20170427113629134034",
    "minions": [
        "*"
    ],
    "tgt": "*",
    "tgt_type": "glob",
    "user": "admin"
}
Exception occurred in runner state.event: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 395, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/runners/state.py", line 205, in event
    node=node)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 1768, in event
    indent=None if not pretty else 4)))
  File "/usr/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 209, in encode
    chunks = list(chunks)
  File "/usr/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 390, in _iterencode_dict
    yield _encoder(value)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb8 in position 0: invalid start byte
```

**Comment by gtmanfred** [comment]
Can you please provide the rest of the information that the new issue request asked for so that I can attempt to replicate this issue?

Specifically the --versions-report of the minion so that we can replicate this on the same version of salt you are running?

Thanks,
Daniel

**Comment by gtmanfred** [comment]
I am unable to replicate this on 2016.11

```
[root@salt ~]# salt-call mysql.user_info root localhost
local:
    ----------
    Alter_priv:
        Y
    Alter_routine_priv:
        Y
    Create_priv:
        Y
    Create_routine_priv:
        Y
    Create_tablespace_priv:
        Y
    Create_tmp_table_priv:
        Y
    Create_user_priv:
        Y
    Create_view_priv:
        Y
    Delete_priv:
        Y
    Drop_priv:
        Y
    Event_priv:
        Y
    Execute_priv:
        Y
    File_priv:
        Y
    Grant_priv:
        Y
    Host:
        localhost
    Index_priv:
        Y
    Insert_priv:
        Y
    Lock_tables_priv:
        Y
    Password:
    Process_priv:
        Y
    References_priv:
        Y
    Reload_priv:
        Y
    Repl_client_priv:
        Y
    Repl_slave_priv:
        Y
    Select_priv:
        Y
    Show_db_priv:
        Y
    Show_view_priv:
        Y
    Shutdown_priv:
        Y
    Super_priv:
        Y
    Trigger_priv:
        Y
    Update_priv:
        Y
    User:
        root
    authentication_string:
    max_connections:
        0
    max_questions:
        0
    max_updates:
        0
    max_user_connections:
        0
    plugin:
    ssl_cipher:
    ssl_type:
    x509_issuer:
    x509_subject:
```
