### ISSUE TITLE
SaltInvocationError when using sharedsecret eauth with salt-api

### ISSUE THREAD

**Issue by corywright** [saltstack/salt#40949]
### Description of Issue

When using the `sharedsecret` external auth module with salt-api an exception is raised and authentication fails. 

In a default install with an extremely simple config I am receiving a `401 Unauthorized` response back from salt-api on my login attempt. The salt-master log shows a `SaltInvocationError` on this auth attempt.  If I change the external auth to use `auto` then the authentication succeeds.

### Setup

In `/etc/salt/master.d/salt-api.conf`:

```yaml
rest_cherrypy:
  port: 8000
  log_access_file: /var/log/salt/api-access.log
  log_error_file: /var/log/salt/api-error.log
  disable_ssl: True
  webhook_disable_auth: True

external_auth:
  #auto:
  sharedsecret:
    salt:
      - .*
```

In `/etc/salt/master.d/sharedsecret.conf`:

```yaml
sharedsecret: testpw
```

Permissions on `/etc/salt/master.d/sharedsecret.conf` are set to `0640`:

```
-rw-r----- 1 root salt 21 Apr 28 12:22 sharedsecret.conf
```

### Steps to Reproduce Issue

Start salt-minion and salt-api with the above configuration, then attempt to login.

```
$ curl -si localhost:8000/login -H "Accept: application/json" \
           -d username='salt' \
           -d password='testpw' \
           -d eauth='sharedsecret'
HTTP/1.1 401 Unauthorized
Content-Length: 742
Access-Control-Expose-Headers: GET, POST
Vary: Accept-Encoding
Server: CherryPy/3.2.2
Allow: GET, HEAD, POST
Access-Control-Allow-Credentials: true
Date: Fri, 28 Apr 2017 12:16:29 GMT
Access-Control-Allow-Origin: *
Content-Type: text/html;charset=utf-8
Set-Cookie: session_id=480597b53071f95cd675b6e24422bce233bf4c5b; expires=Fri, 28 Apr 2017 22:16:29 GMT; Path=/

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>401 Unauthorized</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>401 Unauthorized</h2>
        <p>Could not authenticate using provided credentials</p>
        <pre id="traceback"></pre>
    <div id="powered_by">
    <span>Powered by <a href="http://www.cherrypy.org">CherryPy 3.2.2</a></span>
    </div>
    </body>
</html>
```

The following error shows up in `/var/log/salt/master`:

```pytb
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 1917, in mk_token
    name = self.loadauth.load_name(clear_load)
  File "/usr/lib/python2.7/dist-packages/salt/auth/__init__.py", line 71, in load_name 
    expected_extra_kws=AUTH_INTERNAL_KEYWORDS)
  File "/usr/lib/python2.7/dist-packages/salt/utils/__init__.py", line 1054, in format_call
    used_args_count
SaltInvocationError: auth takes at least 2 arguments (1 given)
```

When I edit `/etc/salt/master.d/salt-api.conf` to change the `external_auth` setting to use `auto` then everything works:

```yaml
rest_cherrypy:
  port: 8000
  log_access_file: /var/log/salt/api-access.log
  log_error_file: /var/log/salt/api-error.log
  disable_ssl: True
  webhook_disable_auth: True

external_auth:
  auto:
  #sharedsecret:
    salt:
      - .*
```

After changing these settings I restart the `salt-master` and `salt-api` services, then when I make the call to `/login` I get back a token:

```
$ curl -si localhost:8000/login -H "Accept: application/json" 
           -d username='salt' \
           -d password='testpw' \
           -d eauth='auto'
HTTP/1.1 200 OK
Content-Length: 174
Access-Control-Expose-Headers: GET, POST
Vary: Accept-Encoding
Server: CherryPy/3.2.2
Allow: GET, HEAD, POST
Access-Control-Allow-Credentials: true
Date: Fri, 28 Apr 2017 12:14:45 GMT
Access-Control-Allow-Origin: *
X-Auth-Token: 3669465fbb3736e333eee7eb262164202d714580
Content-Type: application/json
Set-Cookie: session_id=3669465fbb3736e333eee7eb262164202d714580; expires=Fri, 28 Apr 2017 22:14:45 GMT; Path=/

{"return": [{"perms": [".*"], "start": 1493381685.542374, "token": "3669465fbb3736e333eee7eb262164202d714580", "expire": 1493424885.542374, "user": "salt", "eauth": "auto"}]}
```

### Versions Report

```
# salt --versions-report
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.16.0-77-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by Ch3LL** [comment]
@corywright has this ever worked previously?

I am able to replicate this behavior.

I can run the following: 

```
[root@2c25d3945a42 /]# salt -a sharedsecret '*' test.ping
username: saltdev
c6c2e89d6b0b:
    True
```

But when i run `curl -si localhost:8000/login -H "Accept: application/json"            -d username='saltdev'            -d password='saltdev'            -d eauth='sharedsecret'` I get a 401.

ping @whiteinge would you expect this to work out of the box? Is there a possible misconfiguration

**Comment by corywright** [comment]
@Ch3LL I've never tried to run this previously. I was looking for a simple way to authenticate a salt-api request.

**Comment by whiteinge** [comment]
This eauth backend accepts `sharedsecret` instead of `password` in the payload. The following works:

```
curl -sSi http://localhost:8000/login -H 'Content-type: application/json' -d '
{
  "username": "saltdev",
  "sharedsecret": "OIUHF_CHANGE_THIS_12h88",
  "eauth": "sharedsecret"
}
'
```

I am a little surprised this works at the CLI -- probably by virtue of us passing positional args instead of keyword args -- and I'm not certain that behavior is desirable. This auth module was added for a very specific use-case and I don't think the author ever finished the other surrounding work.

**Comment by whiteinge** [comment]
@corywright if you're looking for something simple you may prefer using the [auth.mk_token](https://docs.saltstack.com/en/latest/ref/runners/all/salt.runners.auth.html#salt.runners.auth.mk_token) Runner (if you're on  2016.11) to create a long-lived eauth token. It is best used via the `/run` URL to skip the login step and session handling.
