### ISSUE TITLE
Highstate fails with KeyError: 'saltutil.is_running'

### ISSUE THREAD

**Issue by non7top** [saltstack/salt#40968]
### Description of Issue/Question
```
# salt 'example.com' state.highstate  saltenv=dev test=True
example.com:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/salt/minion.py", line 1079, in _thread_return
        self.schedule.add_job({
      File "/usr/lib/python2.6/site-packages/salt/modules/state.py", line 763, in highstate
        conflict = _check_queue(queue, kwargs)
      File "/usr/lib/python2.6/site-packages/salt/modules/state.py", line 249, in _check_queue
        conflict = running(concurrent=kwargs.get('concurrent', False))
      File "/usr/lib/python2.6/site-packages/salt/modules/state.py", line 208, in running
        active = __salt__['saltutil.is_running']('state.*')
      File "/usr/lib/python2.6/site-packages/salt/loader.py", line 902, in __getitem__
        funcname
      File "/usr/lib/python2.6/site-packages/salt/utils/lazy.py", line 93, in __getitem__
    KeyError: 'saltutil.is_running'
```

### Versions Report
```
Salt Version:
           Salt: 2016.11.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.9 Final
        machine: x86_64
        release: 2.6.32-042stab123.1
         system: Linux
        version: CentOS 6.9 Final
```

**Comment by gtmanfred** [comment]
I am unable to replicate this, can you provide the output of 

`salt 'example.com' test.versions_report`

So we can see the version on the minion as well?

And if you could restart the minion and the master just to make sure, I would appreciate that.

Thanks,
Daniel

**Comment by non7top** [comment]
Thanks for the hint. Turned out I had two instances of salt running on server, one old pre-upgrade one and one after-upgrade.

```
example.com:
    Salt Version:
               Salt: 2016.11.4

    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: Not Installed
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.8.1
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: 0.20.2
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
       pycryptodome: 3.4.3
             pygit2: Not Installed
             Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.5.0
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5

    System Versions:
               dist: centos 6.9 Final
            machine: x86_64
            release: 2.6.32-042stab120.16
             system: Linux
            version: CentOS 6.9 Final

example.com:
    Salt Version:
               Salt: 2015.8.12

    Dependency Versions:
             Jinja2: 2.7.3
           M2Crypto: 0.20.2
               Mako: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.5.0
             Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
            libgit2: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: Not Installed
            timelib: Not Installed

    System Versions:
               dist: centos 6.9 Final
            machine: x86_64
            release: 2.6.32-042stab120.16
             system: CentOS 6.9 Final
```
