### ISSUE TITLE
salt-ssh is broken on python 3

### ISSUE THREAD

**Issue by ezh** [saltstack/salt#40966]
### Description of Issue/Question

```
salt-ssh -i '*' test.ping

[ERROR   ] An un-handled exception from the multiprocessing process 'MultiprocessingProcess-1' was caught:
Process MultiprocessingProcess-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/home/ezh/.virtualenvs/salt/lib/python3.4/site-packages/salt/utils/process.py", line 647, in _run
    return self._original_run()
  File "/usr/lib64/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ezh/.virtualenvs/salt/lib/python3.4/site-packages/salt/client/ssh/__init__.py", line 426, in handle_routine
    stdout, stderr, retcode = single.run()
  File "/home/ezh/.virtualenvs/salt/lib/python3.4/site-packages/salt/client/ssh/__init__.py", line 851, in run
    stdout, stderr, retcode = self.cmd_block()
  File "/home/ezh/.virtualenvs/salt/lib/python3.4/site-packages/salt/client/ssh/__init__.py", line 1128, in cmd_block
    stdout, stderr, retcode = self.shim_cmd(cmd_str)
  File "/home/ezh/.virtualenvs/salt/lib/python3.4/site-packages/salt/client/ssh/__init__.py", line 1083, in shim_cmd
    shim_tmp_file.write(cmd_str)
  File "/home/ezh/.virtualenvs/salt/lib64/python3.4/tempfile.py", line 417, in func_wrapper
    return func(*args, **kwargs)
TypeError: 'str' does not support the buffer interface
[ERROR   ] Target 'ezh' did not return any data, probably due to an error.
```

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

```
python -V
Python 3.4.5
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

```
salt-ssh -i '*' test.ping
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
 ❯ salt --versions-report
Salt Version:
           Salt: 2016.11.0-1250-g2784f5a

Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.4.5 (default, Jan 28 2017, 19:37:16)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.6

System Versions:
           dist: gentoo 2.3
        machine: x86_64
        release: 4.9.9-gentoo
         system: Linux
        version: Gentoo Base System 2.3
```

**Comment by ezh** [comment]
PR will be available shortly

**Comment by gtmanfred** [comment]
Thanks for the PR.

Daniel

**Comment by terminalmage** [comment]
This can probably be closed, right?
