### ISSUE TITLE
salt-cloud sudo failing

### ISSUE THREAD

**Issue by weirdbricks** [saltstack/salt#40965]
### Description of Issue/Question

Hello,
I am trying to launch some droplets in Digital Ocean using `salt-cloud`. The process seems to be breaking when `salt-cloud` attempts to use sudo.

Do you see anything wrong with my setup ? Thanks!

### Setup

```
#provider
digitalocean-lampros:
  driver: digital_ocean
  ssh_key_name: digital-ocean-salt-cloud.pub
  ssh_key_file: /root/.ssh/id_rsa 
  ssh_username: tools
  ssh_interface: private
  ssh_port: 4910
  sudo: True 
  sudo_password: "--redacted--"
  personal_access_token: --redacted--
  location: San Francisco 2
  minion:
    master: salt 
```

```
#profile
tools:
  provider: digitalocean-lampros
  image: my-super-image
  size: 16GB
  location: San Francisco 2
  private_networking: True
```

### Steps to Reproduce Issue

This is what I use to create the droplet:

```
salt-cloud --profile tools lobsterman4 -l all
```

And this is what I get:

```
[DEBUG   ] Logging into 10.138.136.234:4910 as tools
[DEBUG   ] Using /root/.ssh/id_rsa as the key_filename
[DEBUG   ] Using sudo to run command sudo -S "XXX-REDACTED-XXX" test -e '/tmp/.saltcloud-4ba4b02e-5a85-40ae-8192-cf2dcb527c9d'
[DEBUG   ] SSH command: 'ssh -t -t -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oIdentitiesOnly=yes -oKbdInteractiveAuthentication=no -i /root/.ssh/id_rsa -p 4910 tools@10.138.136.234 sudo -S "XXX-REDACTED-XXX" test -e '/tmp/.saltcloud-4ba4b02e-5a85-40ae-8192-cf2dcb527c9d''
[DEBUG   ] Child Forked! PID: 4921  STDOUT_FD: 4  STDERR_FD: 8
[DEBUG   ] Terminal Command: /bin/sh -c ssh -t -t -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oIdentitiesOnly=yes -oKbdInteractiveAuthentication=no -i /root/.ssh/id_rsa -p 4910 tools@10.138.136.234 'sudo -S test -e '"'"'/tmp/.saltcloud-4ba4b02e-5a85-40ae-8192-cf2dcb527c9d'"'"''
Warning: Permanently added '[10.138.136.234]:4910' (ECDSA) to the list of known hosts.
[DEBUG   ] Warning: Permanently added '[10.138.136.234]:4910' (ECDSA) to the list of known hosts.
[sudo] password for tools: [DEBUG   ] [sudo] password for tools:
[ERROR   ] Failed to create VM lobsterman4. Configuration value ('sudo_password', None) needs to be set
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1288, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/digital_ocean.py", line 510, in create
    ret = __utils__['cloud.bootstrap'](vm_, __opts__)
  File "/usr/lib/python2.7/site-packages/salt/utils/cloud.py", line 532, in bootstrap
    deployed = deploy_script(**deploy_kwargs)
  File "/usr/lib/python2.7/site-packages/salt/utils/cloud.py", line 1267, in deploy_script
    allow_failure=True, **ssh_kwargs):
  File "/usr/lib/python2.7/site-packages/salt/utils/cloud.py", line 2224, in root_cmd
    retcode = _exec_ssh_cmd(cmd, allow_failure=allow_failure, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/utils/cloud.py", line 1783, in _exec_ssh_cmd
    proc.sendline(kwargs['sudo_password', None])
KeyError: ('sudo_password', None)
Error: There was a profile error: Failed to deploy VM
```

### Versions Report

```
salt --versions-report
Salt Version:
           Salt: 2016.11.0
 
Dependency Versions:
           cffi: 1.8.3
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.3
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.24.2
         Python: 2.7.13 (default, Dec 22 2016, 09:22:15)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.5
 
System Versions:
           dist:   
        machine: x86_64
        release: 3.10.0-327.36.3.el7.x86_64
         system: Linux
        version: Not Installed
```

**Comment by gtmanfred** [comment]
Yup, looks like that line was converted from a .get to a direct access of the dictionary, but the `, None` wasn't removed.

I have fixed this in the PR here.  #40987

Thanks!
Daniel

**Comment by weirdbricks** [comment]
@gtmanfred Many thanks for the quick response and fix! I manually applied the fix by editing the file and I can confirm that it works now.
