### ISSUE TITLE
docker-events engine is broken on python 3 

### ISSUE THREAD

**Issue by ezh** [saltstack/salt#40979]
### Description of Issue/Question

docker-events engine raise TypeError: the JSON object must be str, not 'bytes'

### Setup

```
> cat etc/salt/.salt-master
engines:
  - docker_events
```

### Steps to Reproduce Issue

Python 3; start salt-master and wait for docker event:

```
Traceback (most recent call last):
  File "/home/ezh/.virtualenvs/salt/lib/python3.4/site-packages/salt/engines/docker_events.py", line 82, in start
    data = json.loads(event)
  File "/usr/lib64/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
[INFO    ] Process <class 'salt.engines.Engine'> (12581) died with exit status 0, restarting...
```

### Versions Report

```
Salt Version:
           Salt: 2016.11.0-1253-g709d54f

Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: 2.6.0
      docker-py: 1.10.6
          gitdb: 2.0.0
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.4.5 (default, Jan 28 2017, 19:37:16)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.6

System Versions:
           dist: gentoo 2.3
        machine: x86_64
        release: 4.9.9-gentoo
         system: Linux
        version: Gentoo Base System 2.3
```

**Comment by ezh** [comment]
PR will be available shortly

**Comment by gtmanfred** [comment]
Thanks for the pr.

Daniel
