### ISSUE TITLE
initializer for ctype 'struct $MPZ' must be a list or tuple or dict or struct-cdata, not cdata 'struct $MPZ *'

### ISSUE THREAD

**Issue by ssjunior** [saltstack/salt#41000]
Fresh new install from oficial repository and following the official instructions. Did not change any configuration file, just run: salt-master --log-level=debug 
Any ideas?

[DEBUG   ] Reading configuration from /etc/salt/master
[ERROR   ] initializer for ctype 'struct $MPZ' must be a list or tuple or dict or struct-cdata, not cdata 'struct $MPZ *'
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/utils/parsers.py", line 200, in parse_args
    process_option_func()
  File "/usr/lib/python2.6/site-packages/salt/utils/parsers.py", line 520, in process_config_dir
    self.config.update(self.setup_config())
  File "/usr/lib/python2.6/site-packages/salt/utils/parsers.py", line 1714, in setup_config
    return config.master_config(self.get_config_file_path())
  File "/usr/lib/python2.6/site-packages/salt/config/__init__.py", line 3299, in master_config
    opts = apply_master_config(overrides, defaults)
  File "/usr/lib/python2.6/site-packages/salt/config/__init__.py", line 3318, in apply_master_config
    import salt.crypt
  File "/usr/lib/python2.6/site-packages/salt/crypt.py", line 29, in <module>
    from Cryptodome.PublicKey import RSA
  File "/usr/lib64/python2.6/site-packages/Cryptodome/PublicKey/RSA.py", line 83, in <module>
    from Cryptodome.Math.Numbers import Integer
  File "/usr/lib64/python2.6/site-packages/Cryptodome/Math/Numbers.py", line 42, in <module>
    from Cryptodome.Math._Numbers_gmp import Integer
  File "/usr/lib64/python2.6/site-packages/Cryptodome/Math/_Numbers_gmp.py", line 198, in <module>
    class Integer(object):
  File "/usr/lib64/python2.6/site-packages/Cryptodome/Math/_Numbers_gmp.py", line 202, in Integer
    _gmp.mpz_init_set_ui(_zero_mpz_p, c_ulong(0))
TypeError: initializer for ctype 'struct $MPZ' must be a list or tuple or dict or struct-cdata, not cdata 'struct $MPZ *'
Usage: salt-master [options]

salt-master: error: Error while processing <bound method Master.process_config_dir of <salt.cli.daemons.Master object at 0x7f22da2f4fd0>>: Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/utils/parsers.py", line 200, in parse_args
    process_option_func()
  File "/usr/lib/python2.6/site-packages/salt/utils/parsers.py", line 520, in process_config_dir
    self.config.update(self.setup_config())
  File "/usr/lib/python2.6/site-packages/salt/utils/parsers.py", line 1714, in setup_config
    return config.master_config(self.get_config_file_path())
  File "/usr/lib/python2.6/site-packages/salt/config/__init__.py", line 3299, in master_config
    opts = apply_master_config(overrides, defaults)
  File "/usr/lib/python2.6/site-packages/salt/config/__init__.py", line 3318, in apply_master_config
    import salt.crypt
  File "/usr/lib/python2.6/site-packages/salt/crypt.py", line 29, in <module>
    from Cryptodome.PublicKey import RSA
  File "/usr/lib64/python2.6/site-packages/Cryptodome/PublicKey/RSA.py", line 83, in <module>
    from Cryptodome.Math.Numbers import Integer
  File "/usr/lib64/python2.6/site-packages/Cryptodome/Math/Numbers.py", line 42, in <module>
    from Cryptodome.Math._Numbers_gmp import Integer
  File "/usr/lib64/python2.6/site-packages/Cryptodome/Math/_Numbers_gmp.py", line 198, in <module>
    class Integer(object):
  File "/usr/lib64/python2.6/site-packages/Cryptodome/Math/_Numbers_gmp.py", line 202, in Integer
    _gmp.mpz_init_set_ui(_zero_mpz_p, c_ulong(0))
TypeError: initializer for ctype 'struct $MPZ' must be a list or tuple or dict or struct-cdata, not cdata 'struct $MPZ *'

**Comment by githubcdr** [comment]
Confirmed here on CentOS 6 machines, this error also happens on salt-minion.

Error is related to Crypto I think and reproducible via

```
[root@db1-film1go-acc.film1.eq2 site-packages ]# python2.6
Python 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from Cryptodome.PublicKey import RSA
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "Cryptodome/PublicKey/RSA.py", line 83, in <module>
    from Cryptodome.Math.Numbers import Integer
  File "Cryptodome/Math/Numbers.py", line 42, in <module>
    from Cryptodome.Math._Numbers_gmp import Integer
  File "Cryptodome/Math/_Numbers_gmp.py", line 198, in <module>
    class Integer(object):
  File "Cryptodome/Math/_Numbers_gmp.py", line 202, in Integer
    _gmp.mpz_init_set_ui(_zero_mpz_p, c_ulong(0))
TypeError: initializer for ctype 'struct $MPZ' must be a list or tuple or dict or struct-cdata, not cdata 'struct $MPZ *'
>>>
```

**Comment by Ch3LL** [comment]
I cannot replicate this:

```
[root@localhost ~]# cat /etc/redhat-release 
CentOS release 6.6 (Final)
[root@localhost ~]# python
Python 2.6.6 (r266:84292, Aug 18 2016, 15:13:37) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from Cryptodome.PublicKey import RSA
>>> 
```

This is a fresh Centos 6.6 box and I did the following:

`sudo yum install https://repo.saltstack.com/yum/redhat/salt-repo-latest-1.el6.noarch.rpm -y`
`yum install salt-master -y`

Also starting the master works fine:

```
[root@localhost ~]# salt-master -ldebug
[DEBUG   ] Reading configuration from /etc/salt/master
[WARNING ] Cannot resolve address None info via socket: <class 'socket.gaierror'>
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] Setting up the Salt Master
[DEBUG   ] Loaded master key: /etc/salt/pki/master/master.pem
[PROFILE ] Beginning pwd.getpwall() call in masterarpi acess_keys function
[PROFILE ] End pwd.getpwall() call in masterarpi acess_keys function
[INFO    ] Preparing the root key for local communication
[DEBUG   ] Removing stale keyfile: /var/cache/salt/master/.root_key
[DEBUG   ] Created pidfile: /var/run/salt-master.pid
```

Are those the exact steps you guys did above? Was salt installed previously on the boxes? Can you run `salt --versions-report` and paste here please

**Comment by githubcdr** [comment]
Hi @Ch3LL,

I did an upgrade from 2016.11.3 to 2016.11.4, I'll take another look at this..

**Comment by ssjunior** [comment]
cat /etc/redhat-release                                                                                    14:17 | Tue 2
CentOS release 6.7 (Final)

I am running it inside a Xen VM.

**Comment by githubcdr** [comment]
I noticed that python-cffi-0.6-5.el6.x86_64 caused this issue, after removing this package everything works.

**Comment by mbochenk** [comment]
Same behaviour here - removed python-cffi (python-cffi-0.6-5.el6.x86_64) and everything works again. Previously on 2017.11.1 everything worked, stopped since upgrade to 2016.11.6.
I am setting grains both via states and via salt from master (grains.setval, etc). Looking at minion confiig I have all the custom ones present and they look correct.

On restarting salt-minion I have an error: `ERROR: Unable to look-up config values for /etc/salt`, however 
I do not see any relevant errors in minion log.

I'll verify if it is reporducible on CentOS7 - at the moment it seems it does not and applies to recent CentOS6. Note that I have epel repo enabled.

```
Salt Version:
           Salt: 2016.11.5
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.4.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.3.8
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: 1.4.3
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.09.1
       pycrypto: 2.0.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: 0.8.1
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.9 Final
        machine: x86_64
        release: 2.6.32-696.3.2.el6.x86_64
         system: Linux
        version: CentOS 6.9 Final
```
