### ISSUE TITLE
Read-only file system

### ISSUE THREAD

**Issue by tsaridas** [saltstack/salt#41092]
### Description of Issue/Question
The bellow error happens when minion runs in a read only tmpfs filesystem in /dev/shm
I'm adding a ticket since somebody else might have fixed this or there is a workaround without remounting the partition are rw ofc.

```
[ERROR   ] [Errno 30] Read-only file system
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/utils/parsers.py", line 212, in parse_args
    mixin_after_parsed_func(self)
  File "/usr/lib/python2.6/site-packages/salt/utils/parsers.py", line 808, in _setup_mp_logging_listener
    self._get_mp_logging_listener_queue()
  File "/usr/lib/python2.6/site-packages/salt/utils/parsers.py", line 802, in _get_mp_logging_listener_queue
    return log.get_multiprocessing_logging_queue()
  File "/usr/lib/python2.6/site-packages/salt/log/setup.py", line 776, in get_multiprocessing_logging_queue
    __MP_LOGGING_QUEUE = multiprocessing.Queue()
  File "/usr/lib64/python2.6/multiprocessing/__init__.py", line 213, in Queue
    return Queue(maxsize)
  File "/usr/lib64/python2.6/multiprocessing/queues.py", line 37, in __init__
    self._rlock = Lock()
  File "/usr/lib64/python2.6/multiprocessing/synchronize.py", line 117, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1)
  File "/usr/lib64/python2.6/multiprocessing/synchronize.py", line 49, in __init__
    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 30] Read-only file system
Usage: salt-minion [options]
 
salt-minion: error: Error while processing <bound method Minion._setup_mp_logging_listener of <salt.cli.daemons.Minion object at 0x2ebc4d0>>: Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/utils/parsers.py", line 212, in parse_args
    mixin_after_parsed_func(self)
  File "/usr/lib/python2.6/site-packages/salt/utils/parsers.py", line 808, in _setup_mp_logging_listener
    self._get_mp_logging_listener_queue()
  File "/usr/lib/python2.6/site-packages/salt/utils/parsers.py", line 802, in _get_mp_logging_listener_queue
    return log.get_multiprocessing_logging_queue()
  File "/usr/lib/python2.6/site-packages/salt/log/setup.py", line 776, in get_multiprocessing_logging_queue
    __MP_LOGGING_QUEUE = multiprocessing.Queue()
  File "/usr/lib64/python2.6/multiprocessing/__init__.py", line 213, in Queue
    return Queue(maxsize)
  File "/usr/lib64/python2.6/multiprocessing/queues.py", line 37, in __init__
    self._rlock = Lock()
  File "/usr/lib64/python2.6/multiprocessing/synchronize.py", line 117, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1)
  File "/usr/lib64/python2.6/multiprocessing/synchronize.py", line 49, in __init__
    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 30] Read-only file system
```

### Setup
mount tmpfs /dev/shm are readonly

### Versions Report
centos6(should happen to other OSs too but haven't tried)
all salt minion versions

**Comment by gtmanfred** [comment]
What type of system are you running this in?

Is it a dedicated server, a vm, or a container like docker?

Thanks,
Daniel

**Comment by tsaridas** [comment]
Hi Daniel,

Its a VM.

**Comment by gtmanfred** [comment]
I believe that because of the way we do multiprocessing, /dev/shm needs to be `rw` and can't run without that.  So the only answer would be to  remount /dev/shm.

Thanks,
Daniel
