### ISSUE TITLE
Regression in salt-cloud VMware profile in 2016.11.4

### ISSUE THREAD

**Issue by sebw** [saltstack/salt#41091]
We provide a list of search domains for the option "domain" when doing cloud.create:

```
createvm:
  salt.runner:
    - name: cloud.create
    - provider: vmware
    - instances: {{ data.post['instances'] }}
    - clonefrom: {{ data.post['clonefrom'] }}
    - datastore: {{ data.post['datastore'] }}
    - num_cpus: {{ data.post['num_cpus'] }}
    - memory: {{ data.post['memory'] }}
    - datacenter: {{ data.post['datacenter'] }}
    - folder: {{ data.post['folder'] }}
    - cluster: {{ data.post['cluster'] }}
    - ssh_username: {{ data.post['ssh_username'] }}
    - password: {{ data.post['password'] }}
    - domain: {{ maps_resolver['search'] }}
    - dns_servers: {{ maps_resolver['dns'] }}
    - minion:
       master: {{ data.post['master'] }}
    - sync_after_install: all
    - display_ssh_output: False
    - script: bootstrap-salt
    - script_args: -H {{ maps_proxy['proxy'] }} stable {{ maps_salt['upstream-version'] }}.{{ maps_salt['upstream-version-patch'] }}
    - devices:
       network:
         Network adapter 1:
           name: {{ data.post['vlan'] }}
           adapter_type: vmxnet3
           ip: {{ data.post['ip'] }}
           subnet_mask: {{ data.post['subnet_mask'] }}
           gateway: {{ data.post['gateway'] }}
           switch_type: standard
       disk:
         Hard disk 2:
           size: {{ data.post['disk'] }}
           controller: SCSI controller 2
```
maps_resolver looks like this:

```
{% load_yaml as maps_resolver %}

dns: 
  - x.x.x.x
  - y.y.y.y

search:
  - intranet.example.org
  - intranet.example.com

{% endload %}
```
After upgrading to 2016.11.4 we get this traceback:

```
          ID: createvm
    Function: salt.runner
        Name: cloud.create
      Result: False
     Comment: Exception occurred in runner cloud.create: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 395, in _low
                  data['return'] = self.functions[fun](*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/runners/cloud.py", line 177, in create
                  info = client.create(provider, instances, **create_kwargs)
                File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 412, in create
                  mapper.create(vm_))
                File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1291, in create
                  output = self.clouds[func](vm_)
                File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/vmware.py", line 2613, in create
                  identity.domain = domainName if hostName != domainName else domain
                File "/usr/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 537, in __setattr__
                  CheckField(self._GetPropertyInfo(name), val)
                File "/usr/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 972, in CheckField
                  % (info.name, info.type.__name__, valType.__name__))
              TypeError: For "domain" expected type str, but got list
     Started: 11:55:01.908015
    Duration: 3809.599 ms
     Changes:   
```
I don't find anything in the release note regarding a change of format of the domain option.

Domain option should be multi-value.

Would that be a regression?

**Comment by gtmanfred** [comment]
What version were you using before where this worked so that we can test it?

Thanks,
Daniel

**Comment by sebw** [comment]
Sorry, forgot to mention. Master was running 2016.11.3 before.

After downgrading back to that version, we can cloud.create again.

**Comment by sebw** [comment]
@Ch3LL can you try to reproduce this?

**Comment by Ch3LL** [comment]
I can reproduce it but I can't get it to work in 2016.11.3 either adding this to my profile

```
  domain:
    - 10.0.0.0
    - 10.0.0.1
  search: test.domain.com
```

And just creating a VM with `salt-cloud -p <profile_name> <vm_name>`

I'm assuming both your domains are being set correctly in 2016.11.4?

**Comment by sebw** [comment]
I don't use `salt-cloud`, I use `salt-run` from a Rundeck job taking options. Profile options are passed to the runner through pillars.

`salt-run state.orchestrate orch_vmware.createvm pillar="{event_data: {post: {master: @option.MASTER@, instances: @option.MINION_ID@, clonefrom: @option.IMAGE@, datastore: @option.DATASTORE@, num_cpus: @option.CPU@, memory: @option.RAM@, datacenter: @option.DATACENTER@, cluster: @option.CLUSTER@, vlan: @option.VLAN@, ip: @option.IP@, subnet_mask: $SUBNET, gateway: $GATEWAY, ssh_username: @option.IMAGE_USER@, password: @option.IMAGE_PWD@, ETNIC_ENV: @option.ETNIC_ENV@, highstate: @option.HIGHSTATE@, folder: @option.FOLDER@, disk: @option.DISK_DATA_SIZE@}}}" -l @option.SALT_DEBUG@`

Nothing has changed on this for a while, domains are set in the map file, and it breaks on 2016.11.4 and 2016.11.5.

**Comment by sebw** [comment]
Closing this as @Ch3LL solution is working for us now.
