### ISSUE TITLE
Exception occurred in runner jobs.list_jobs

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#41100]
### Description of Issue/Question
I see this in 2016.11.5
```
- "Exception occurred in runner jobs.list_jobs: Traceback (most recent call last):\n\
  \  File \"/usr/lib/python2.7/site-packages/salt/client/mixins.py\", line 395, in\
  \ _low\n    data['return'] = self.functions[fun](*args, **kwargs)\nTypeError: list_jobs()\
  \ got an unexpected keyword argument 'jid'\n"
```

### Setup
Install salt 2016.11.5 and setup salt-api
```
[root@li90-111 ~]# curl -sSk http://localhost:8000/jobs -H 'Accept: application/x-yaml' -H 'X-Auth-Token: 99e1511d6b2d0112754df005dd1259653e528e7a'
return:
- "Exception occurred in runner jobs.list_jobs: Traceback (most recent call last):\n\
  \  File \"/usr/lib/python2.7/site-packages/salt/client/mixins.py\", line 395, in\
  \ _low\n    data['return'] = self.functions[fun](*args, **kwargs)\nTypeError: list_jobs()\
  \ got an unexpected keyword argument 'jid'\n"
```

### Steps to Reproduce Issue
`salt-master -d; salt-minion -d; salt-api -d`
`curl -k -c /tmp/cookies.txt -sS localhost:8000/login -H "Accept:application/x-yaml" -d username='saltdev' -d password='saltdev' -d eauth='pam'`
`curl -sSk http://localhost:8000/jobs -H 'Accept: application/x-yaml' -H 'X-Auth-Token: <session token from earlier command'`

### Versions Report
```
[root@li90-111 ~]# salt --versions
Salt Version:
           Salt: 2016.11.5
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 4.9.15-x86_64-linode81
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

**Comment by cachedout** [comment]
Nice work getting this turned around so quickly, @gtmanfred and props to @frogunder for finding this one!

**Comment by faelin** [comment]
Sorry Salt maintainers, but this issue has reappeared for our install of salt 2018.3.4 (Oxygen)!

```
[root@salt-master-01-dfw ~]# salt-run jobs.last_run
Exception occurred in runner jobs.last_run: Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/salt/client/mixins.py", line 387, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/salt/runners/jobs.py", line 525, in last_run
    function, target, display_progress)
  File "/usr/lib/python3.4/site-packages/salt/runners/jobs.py", line 308, in list_jobs
    ret = mminion.returners['{0}.get_jids'.format(returner)]()
  File "/usr/lib/python3.4/site-packages/salt/returners/local_cache.py", line 376, in get_jids
    for jid, job, _, _ in _walk_through(_job_dir()):
  File "/usr/lib/python3.4/site-packages/salt/returners/local_cache.py", line 80, in _walk_through
    jid = job['jid']
KeyError: 'jid'
```

# Versions Report
```
[root@salt-master-01-dfw ~]# salt --versions
Salt Version:
           Salt: 2018.3.4

Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.27.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.27.0
         Python: 3.4.8 (default, Mar 23 2018, 10:04:27)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 4.4.135-1.el7.elrepo.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```
