### ISSUE TITLE
Upgrade from salt 2015.5.10 to 2016.11.4 not loading custom grain due to unicode

### ISSUE THREAD

**Issue by quayly** [saltstack/salt#41114]
### Description of Issue/Question

After the upgrade, 2016.11.4 salt would not load the custom grains.  Doing a salt-call cp.list_master returns nothing.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

I have the following files in my salt base

```
./.git/logs/refs/remotes/origin/??ISE-1821-fix_ckfiles
./.git/logs/refs/remotes/origin/revert-??4de545e8
./.git/logs/refs/remotes/origin/??INFSUPPORT-8441_cj_api_config
./.git/logs/refs/remotes/origin/deploy-faketui-??1e2490acf926
```

my salt master is configure to ignore .git

```
---
file_ignore_regex:
  - '/\.svn($|/)'
  - '/\.git($|/)'
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

```
Exception occurred in runner fileserver.file_list: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 395, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/runners/fileserver.py", line 179, in file_list
    return fileserver.file_list(load=load)
  File "/usr/lib/python2.7/site-packages/salt/fileserver/__init__.py", line 751, in file_list
    ret.update(self.servers[fstr](load))
  File "/usr/lib/python2.7/site-packages/salt/fileserver/roots.py", line 415, in file_list
    return _file_lists(load, 'files')
  File "/usr/lib/python2.7/site-packages/salt/fileserver/roots.py", line 391, in _file_lists
    _add_to(ret['files'], path, root, files)
  File "/usr/lib/python2.7/site-packages/salt/fileserver/roots.py", line 339, in _add_to
    log.trace('roots: Processing %s', abs_path)
  File "/usr/lib/python2.7/site-packages/salt/log/mixins.py", line 35, in trace
    self.log(getattr(logging, 'TRACE', 5), msg, *args, **kwargs)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1213, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/log/setup.py", line 310, in _log
    self, level, msg, args, exc_info=exc_info, extra=extra
  File "/usr/lib64/python2.7/logging/__init__.py", line 1267, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/usr/lib/python2.7/site-packages/salt/log/setup.py", line 344, in makeRecord
    exc_info, func)
  File "/usr/lib/python2.7/site-packages/salt/log/setup.py", line 191, in __init__
    self.colormsg = '%s%s%s' % (cmsg, self.getMessage(), reset)
  File "/usr/lib64/python2.7/logging/__init__.py", line 328, in getMessage
    msg = msg % self.args
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 47: ordinal not in range(128)
[INFO    ] Runner completed: 20170505163642731595
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Salt 2016.11.4 (Carbon)

**Comment by Ch3LL** [comment]
@quayly do you know what file its trying to load when its hits the ascii code? Are you implying its trying to load the files that should be ignored in your .git directory?

**Comment by quayly** [comment]
I've deleted all of the files listed above and now I no longer see the UnicodeDecodeError.

Doing a salt-run fileserver.file_list now show's results.

However, the custom grain in my /srv/salt/_grains are still not being processed.

**Comment by quayly** [comment]
k, I am now able to see the custom grain now after doing a saltutil.sync_all.

The bug still exist due to the unicode files.

**Comment by Ch3LL** [comment]
agreed this is a bug where we should handle the unicode better. My other concern is that your `file_ignore_regex:` is not working anymore. Does that seem to be the case still? If you add another file in .git is it ignored?

**Comment by quayly** [comment]
I copy the bad file back into /srv/salt/.git/logs/refs/remotes/origin/revert-??4de545e8 and did a saltutil.sync_all and the grains disappear.  So it looks like it is not honoring the ignore section of the salt master config.
