### ISSUE TITLE
salt-cloud BlobNotFound error at vm deletion with azurearm provider

### ISSUE THREAD

**Issue by shengis** [saltstack/salt#41299]
### Description of Issue/Question
At deleting VM with **azurearm** provider, got the following error
```
ERROR   ] There was an error destroying machines: The specified blob does not exist.
<?xml version="1.0" encoding="utf-8"?>
<Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:5a4ea161-001c-00b6-5efe-ced89d000000
Time:2017-05-17T11:14:22.3919276Z</Message></Error>
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 213, in run
    ret = mapper.destroy(names, cached=True)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1034, in destroy
    ret = self.clouds[fun](name)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/azurearm.py", line 1323, in destroy
    call='function'
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/azurearm.py", line 1748, in delete_blob
    storageservice.delete_blob(kwargs['container'], kwargs['blob'])
  File "/usr/local/lib/python2.7/dist-packages/azure/storage/blob/baseblobservice.py", line 3118, in delete_blob
    self._perform_request(request)
  File "/usr/local/lib/python2.7/dist-packages/azure/storage/storageclient.py", line 266, in _perform_request
    raise ex
AzureMissingResourceHttpError: The specified blob does not exist.
<?xml version="1.0" encoding="utf-8"?>
<Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:5a4ea161-001c-00b6-5efe-ced89d000000
Time:2017-05-17T11:14:22.3919276Z</Message></Error>
```

### Setup
I have multiple providers configured in a **cloud.providers.d/azure.conf**
```
azure-eu1:
  driver: azurearm
  subscription_id: ***

  tenant: ***
  client_id: ***
  secret: ***

  location: westeurope
  resource_group: infra-eu1
  network_resource_group: infra-eu1
  storage_account: ACCOUNT_EU1
  storage_key: KEY_EU1

  cleanup_disks: True
  cleanup_vhds: True
  cleanup_data_disks: True
  cleanup_interfaces: True

  minion:
    master: 10.1.1.4
    hash_type: sha256

  grains:
    provider: azure
    region: westeurope

azure-us1:
  driver: azurearm
  subscription_id: ***

  tenant: ***
  client_id: ***
  secret: ***

  location: westus
  resource_group: infra-us1
  network_resource_group: infra-us1
  storage_account: ACCOUNT_US1
  storage_key: KEY_US1

  cleanup_disks: True
  cleanup_vhds: True
  cleanup_data_disks: True
  cleanup_interfaces: True

  minion:
    master: 10.1.1.4
    hash_type: sha256
```
And multiple profiles in **cloud.profiles.d/azure.conf**
```
azure-eu1:
  provider: azure-eu1
  image: Canonical|UbuntuServer|16.04-LTS|latest
  size: Standard_DS2_v2
  ssh_username: ***
  ssh_password: ***
  network: infraeu1VNET
  subnet: infraeu1Subnet
  public_ip: False
  script: bootstrap-salt.sh
  script_args: git v2017.5
  sync_after_install: grains

azure-us1:
  provider: azure-us1
  image: Canonical|UbuntuServer|16.04-LTS|latest
  size: Standard_DS2_v2
  ssh_username: ***
  ssh_password: ***
  network: infraus1VNET
  subnet: infraus1Subnet
  public_ip: False
  script: bootstrap-salt.sh
  script_args: git v2017.5
  sync_after_install: grains

azure-eu1-test:
  extends: azure-eu1
  volumes:
    - {disk_size_gb: 128, name: 'datadisk1'}
  minion:
    master: 10.1.1.4
    grains:
      region: westeurope
      roles: test

azure-us1-test:
  extends: azure-us1
  volumes:
    - {disk_size_gb: 128, name: 'datadisk1'}
  minion:
    master: 10.1.1.4
    grains:
      region: westus
      roles: test
```

### Steps to Reproduce Issue
I found having multiple providers is not correctly managed.

In the function **delete_blob** of **/usr/lib/python2.7/dist-packages/salt/cloud/clouds/azurearm.py**
The following code is not getting the good storage account
```
    storageaccount = azure.storage.CloudStorageAccount(
        config.get_cloud_config_value(
            'storage_account',
            get_configured_provider(), __opts__, search_global=False
        ),
        config.get_cloud_config_value(
            'storage_key',
            get_configured_provider(), __opts__, search_global=False
        ),
    )
```

### Versions Report
```
Salt Version:
            Salt: 2017.5.0
 
Dependency Versions:
 Apache Libcloud: 0.20.0
            cffi: 1.10.0
        cherrypy: Not Installed
        dateutil: 2.6.0
       docker-py: Not Installed
           gitdb: Not Installed
       gitpython: Not Installed
           ioflo: Not Installed
          Jinja2: 2.8
         libgit2: Not Installed
         libnacl: Not Installed
        M2Crypto: Not Installed
            Mako: Not Installed
    msgpack-pure: Not Installed
  msgpack-python: 0.4.6
    mysql-python: Not Installed
       pycparser: 2.17
        pycrypto: 2.6.1
    pycryptodome: Not Installed
          pygit2: Not Installed
          Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
    python-gnupg: Not Installed
          PyYAML: 3.11
           PyZMQ: 15.2.0
            RAET: Not Installed
           smmap: Not Installed
         timelib: Not Installed
         Tornado: 4.2.1
             ZMQ: 4.1.4
 
System Versions:
            dist: Ubuntu 16.04 xenial
         machine: x86_64
         release: 4.4.0-77-generic
          system: Linux
         version: Ubuntu 16.04 xenial
```

**Comment by shengis** [comment]
the variable **\_\_active_provider_name__** is *'azure-eu1:azurearm'*
while I used the *azure-us1* provider
```
root@master:/etc/salt# salt-cloud -p azure-us1-test -d us1-testnode1
The following virtual machines are set to be destroyed:
  azure-us1:
    azurearm:
      us1-testnode1

Proceed? [N/y] y
... proceeding
```

**Comment by shengis** [comment]
When destroying a VM using **salt-cloud -d vm_name** the function **destroy** of /salt/cloud/__init__.py call **get_running_by_names(names, cached=cached)** which returns all the providers each ones associated to all the VMs.
I think, it could be better to returns only VMs of the *resource group* associated to the provider.

**Comment by gtmanfred** [comment]
@techhat can you take a look at this when you get a minute?

Thanks,
Daniel
