### ISSUE TITLE
S3 module does not work with S3 bucket with versioning enabled 

### ISSUE THREAD

**Issue by MasterNayru** [saltstack/salt#41310]
We have been using Salt happily to pull files from S3 using a bucket _without_ versioning enabled and it works fine. However, when we tried to use it with a bucket _with_ versioning enabled, it borked with the error below.

We are running Salt v2016.11.2, but since it exists in develop as well I think this would exist across multiple versions:
```
[DEBUG   ] https://my-versioned-bucket.s3-ap-southeast-2.amazonaws.com:443 "GET /test.txt HTTP/1.1" 301 None
[DEBUG   ] S3 Response Status Code: 301
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/s3.py", line 182, in get
    role_arn=role_arn)
  File "/usr/lib/python2.7/site-packages/salt/utils/s3.py", line 217, in query
    'Failed to get file. {0}: {1}'.format(err_code, err_msg))
CommandExecutionError: Failed to get file. None: None
Error running 's3.get': Failed to get file. None: None
```

It seems to be from https://github.com/saltstack/salt/blob/develop/salt/utils/s3.py#L231-L233:
```
    if local_file and method == 'GET':
        if result.status_code < 200 or result.status_code >= 300:
            raise CommandExecutionError(
                'Failed to get file. {0}: {1}'.format(err_code, err_msg))
```

There needs to be some logic added to get Salt to follow the 301 redirect to get the file back, but this is not happening with the code in its current form. Additionally, while for my needs I really only need GET requests to work for now, it would be nice to have full support for versioned S3 buckets going forward as once versioning is enabled on a bucket it can never be disabled, and thus making Salt work with the S3 bucket again would, presumably, require a whole recreation of the bucket and migration of content (read: potentially painful work).

### Setup
```
$ salt-call s3.get my-versioned-bucket test.txt -l debug
```

### Steps to Reproduce Issue
Error log is given above.

### Versions Report
```$ sudo salt-call --versions-report                             
Salt Version:                                                             
           Salt: 2016.11.2                                                
                                                                          
Dependency Versions:                                                      
           cffi: 1.10.0                                                   
       cherrypy: Not Installed                                            
       dateutil: 2.6.0                                                    
          gitdb: Not Installed                                            
      gitpython: Not Installed                                            
          ioflo: Not Installed                                            
         Jinja2: 2.7.2                                                    
        libgit2: Not Installed                                            
        libnacl: Not Installed                                            
       M2Crypto: Not Installed                                            
           Mako: 1.0.6                                                    
   msgpack-pure: Not Installed                                            
 msgpack-python: 0.4.8                                                    
   mysql-python: Not Installed                                            
      pycparser: 2.17                                                     
       pycrypto: 2.6.1                                                    
         pygit2: Not Installed                                            
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)                   
   python-gnupg: Not Installed                                            
         PyYAML: 3.11                                                     
          PyZMQ: 15.3.0                                                   
           RAET: Not Installed                                            
          smmap: Not Installed                                            
        timelib: Not Installed                                            
        Tornado: 4.2.1                                                    
            ZMQ: 4.1.4                                                    
                                                                          
System Versions:                                                          
           dist: centos 7.3.1611 Core                                     
        machine: x86_64                                                   
        release: 3.10.0-514.16.1.el7.x86_64                               
         system: Linux                                                    
        version: CentOS Linux 7.3.1611 Core                               
```

**Comment by MasterNayru** [comment]
Worked out that the error was unrelated to versioning, but actually to the region of the bucket. #PEBKAC
