### ISSUE TITLE
[2016.11.5] ssh_auth.present: IndexError: list index out of range

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt#41335]
### Description of Issue/Question
Adding an SSH public key to authorized_keys using `ssh_auth.present` results in:
```
          ID: key_xxxxxx
    Function: ssh_auth.present
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1746, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1704, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/ssh_auth.py", line 322, in present
                  config)
                File "/usr/lib/python2.7/dist-packages/salt/modules/ssh.py", line 686, in set_auth_key
                  _replace_auth_key(user, key, enc, comment, options or [], config)
                File "/usr/lib/python2.7/dist-packages/salt/modules/ssh.py", line 157, in _replace_auth_key
                  if comps[0][3] == key:
              IndexError: list index out of range
     Started: 08:49:17.832609
    Duration: 13.879 ms
     Changes:   
```

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
```
    key_xxxxxxx:
        ----------
        ssh_auth:
            |_
              ----------
              user:
                  xxxxxxx
            |_
              ----------
              source:
                  salt://ssh/keys/xxxxxxx.pub
            |_
              ----------
              require:
                  |_
                    ----------
                    user:
                        xxxxxxx
            - present
            |_
              ----------
              order:
                  10276
        __sls__:
            vhosting.base
        __env__:
            base

```
### Steps to Reproduce Issue
See above

The current `authorized_keys` already contains the key located in the `.pub` file and a few others (including comments):

```
xxxxxxxx@testing01:~$ cat .ssh/authorized_keys 
################################################################################
# This file is managed by the Salt, do not edit this file by hand!             #
# Instead, please contact xxxxxxxxxxxx@xxxxxxx.com if changes are required.    #
################################################################################

ssh-rsa AAAABxxxxxxxxxxxxxxxxxx= xxxxxx xxxx xxx
ssh-rsa AAAABxxxxxxxxxxxxxxxxxxn xxxxxxxxx xxxx
ssh-rsa AAAABxxxxxxxxxxxxxxxxxxN xxxxxxxxx xxxx
ssh-rsa AAAABxxxxxxxxxxxxxxxxxxz xxxx@xxxxxxxx.com xxxxx xxxxxxxxxx
ssh-rsa AAAABxxxxxxxxxxxxxxxxxxz xxxx@xxxxxxxx.com xxxxx xxxxxxxxxx
ssh-rsa AAAABxxxxxxxxxxxxxxxxxxz xxxx@xxxxxxxx.com xxxxx xxxxxxxxxx
ssh-rsa AAAABxxxxxxxxxxxxxxxxxxz xxxx@xxxxxxxx.com xxxxx xxxxxxxxxx
ssh-rsa AAAABxxxxxxxxxxxxxxxxxxz xxxx@xxxxxxxx.com xxxxx xxxxxxxxxx
```

### Versions Report
```
Salt Version:
           Salt: 2016.11.5
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.3.7
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-1017-aws
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by syphernl** [comment]
This may be due to the changes done in #39855 by @foxlik

**Comment by Foxlik** [comment]
You are right. Mea culpa. Forgot about empty lines. What was I thinking?

As a hotfix - remove the empty line in the file, it should stop the exception from being thrown.

**Comment by Ch3LL** [comment]
@Foxlik thanks for the PR. Since this resolves the issue I will go ahead and close this but if there is an issue with the fix please let me know and I can re-open the issue. Thanks
