### ISSUE TITLE
Minion couldn't connecting to saltmaster. yaml MemoryError help!!!

### ISSUE THREAD

**Issue by davidvon** [saltstack/salt#41376]
### Description of Issue/Question
[root@minion162 ~]# salt-minion -l debug
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] Setting up the Salt Minion "10.204.126.162"
[DEBUG   ] Created pidfile: /var/run/salt-minion.pid
[INFO    ] Starting up the Salt Minion
[DEBUG   ] AsyncEventPublisher PUB socket URI: /var/run/salt/minion/minion_event_8b0b951a3e_pub.ipc
[DEBUG   ] AsyncEventPublisher PULL socket URI: /var/run/salt/minion/minion_event_8b0b951a3e_pull.ipc
[INFO    ] Starting pull socket on /var/run/salt/minion/minion_event_8b0b951a3e_pull.ipc
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_8b0b951a3e_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_8b0b951a3e_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_8b0b951a3e_pub.ipc
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[INFO    ] Creating minion process manager
[DEBUG   ] Process Manager starting!
[DEBUG   ] Process Manager starting!
[DEBUG   ] Connecting to master. Attempt 1 of 1
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', '10.204.126.162', 'tcp://10.204.126.150:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (5849)
[DEBUG   ] Setting zmq_reconnect_ivl to '5849ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', '10.204.126.162', 'tcp://10.204.126.150:4506', 'clear')
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_8b0b951a3e_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_8b0b951a3e_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_8b0b951a3e_pull.ipc
[DEBUG   ] Sending event: tag = salt/auth/creds; data = {'_stamp': '2017-05-22T11:52:04.728904', 'creds': {'publish_port': 4505, 'aes': 'DdEXLTjic1FAj2nrw9kreuZty3F5/tNvkbZCezWc+VON+3NOvik4xkAeyLMnpaYlPAvgTZZezC8=', 'master_uri': 'tcp://10.204.126.150:4506'}, 'key': ('/etc/salt/pki/minion', '10.204.126.162', 'tcp://10.204.126.150:4506')}
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', '10.204.126.162', 'tcp://10.204.126.150:4506', 'aes')
[DEBUG   ] Re-using AsyncAuth for ('/etc/salt/pki/minion', '10.204.126.162', 'tcp://10.204.126.150:4506')
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Initializing new Schedule
[DEBUG   ] LazyLoaded timezone.get_offset
[DEBUG   ] LazyLoaded cmd.run
[INFO    ] Executing command ['date', '+%z'] in directory '/root'
[DEBUG   ] output: +0000
[DEBUG   ] LazyLoaded config.merge
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_8b0b951a3e_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_8b0b951a3e_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_8b0b951a3e_pull.ipc
[DEBUG   ] Sending event: tag = /salt/minion/minion_schedule_delete_complete; data = {'_stamp': '2017-05-22T11:52:05.282847', 'complete': True, 'schedule': {}}
[DEBUG   ] Persisting schedule
[CRITICAL] Unexpected error while connecting to 10.204.126.150
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 875, in _connect_minion
    yield minion.connect_master(failed=failed)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1053, in connect_master
    yield self._post_master_init(master)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 879, in run
    yielded = self.gen.send(value)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1095, in _post_master_init
    cleanup=[master_event(type='alive')])
  File "/usr/lib/python2.7/site-packages/salt/utils/schedule.py", line 392, in __new__
    cls.instance.__singleton_init__(opts, functions, returners, intervals, cleanup, proxy)
  File "/usr/lib/python2.7/site-packages/salt/utils/schedule.py", line 421, in __singleton_init__
    self.delete_job_prefix(prefix)
  File "/usr/lib/python2.7/site-packages/salt/utils/schedule.py", line 537, in delete_job_prefix
    self.persist()
  File "/usr/lib/python2.7/site-packages/salt/utils/schedule.py", line 482, in persist
    Dumper=SafeOrderedDumper
  File "/usr/lib64/python2.7/site-packages/yaml/__init__.py", line 202, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "/usr/lib64/python2.7/site-packages/yaml/__init__.py", line 190, in dump_all
    dumper.represent(data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 29, in represent
    self.serialize(node)
  File "_yaml.pyx", line 1348, in _yaml.CEmitter.serialize (ext/_yaml.c:15963)
  File "_yaml.pyx", line 1504, in _yaml.CEmitter._serialize_node (ext/_yaml.c:17884)
MemoryError
[DEBUG   ] Connecting to master. Attempt 1 of 1
[DEBUG   ] Re-using AsyncAuth for ('/etc/salt/pki/minion', '10.204.126.162', 'tcp://10.204.126.150:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (1763)
[DEBUG   ] Setting zmq_reconnect_ivl to '1763ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', '10.204.126.162', 'tcp://10.204.126.150:4506', 'aes')
[DEBUG   ] Re-using AsyncAuth for ('/etc/salt/pki/minion', '10.204.126.162', 'tcp://10.204.126.150:4506')
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Re-using Schedule
[DEBUG   ] LazyLoaded mine.update
[INFO    ] Added new job __mine_interval to scheduler
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_8b0b951a3e_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_8b0b951a3e_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_8b0b951a3e_pull.ipc
[DEBUG   ] Sending event: tag = /salt/minion/minion_schedule_add_complete; data = {'_stamp': '2017-05-22T11:52:05.837912', 'complete': True, 'schedule': {'__mine_interval': {'function': 'mine.update', 'enabled': True, 'return_job': False, 'jid_include': True, 'maxrunning': 2, 'minutes': 60}}}
[DEBUG   ] Persisting schedule
[CRITICAL] Unexpected error while connecting to 10.204.126.150
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 875, in _connect_minion
    yield minion.connect_master(failed=failed)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1053, in connect_master
    yield self._post_master_init(master)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 879, in run
    yielded = self.gen.send(value)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1108, in _post_master_init
    }, persist=True)
  File "/usr/lib/python2.7/site-packages/salt/utils/schedule.py", line 580, in add_job
    self.persist()
  File "/usr/lib/python2.7/site-packages/salt/utils/schedule.py", line 482, in persist
    Dumper=SafeOrderedDumper
  File "/usr/lib64/python2.7/site-packages/yaml/__init__.py", line 202, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "/usr/lib64/python2.7/site-packages/yaml/__init__.py", line 190, in dump_all
    dumper.represent(data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 29, in represent
    self.serialize(node)
  File "_yaml.pyx", line 1348, in _yaml.CEmitter.serialize (ext/_yaml.c:15963)
  File "_yaml.pyx", line 1504, in _yaml.CEmitter._serialize_node (ext/_yaml.c:17884)
MemoryError

**Comment by davidvon** [comment]
Salt Version:
           Salt: 2016.11.5
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: unknown
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.13 (default, Mar 23 2017, 11:43:14)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.10.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by Ch3LL** [comment]
Can you paste a sanitized version of your schedule.conf (`_schedule.conf`)
