### ISSUE TITLE
Py3 - Nitrogen - RAET transport not working 

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#41412]
### Description of Issue/Question
Trying to use RAET transport is not working. Giving error/traceback installing dependencies.
```
Traceback (most recent call last):
  File "/usr/local/bin/salt-call", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/root/salt/scripts/salt-call", line 11, in <module>
    salt_call()
  File "/root/salt/salt/scripts.py", line 386, in salt_call
    import salt.cli.call
  File "/root/salt/salt/cli/call.py", line 9, in <module>
    import salt.cli.caller
  File "/root/salt/salt/cli/caller.py", line 37, in <module>
    from raet import raeting, nacling
  File "/usr/local/lib/python3.5/site-packages/raet/__init__.py", line 12, in <module>
    importlib.import_module(".{0}".format(m), package='raet')
  File "/usr/local/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.5/site-packages/raet/nacling.py", line 11, in <module>
    import libnacl
  File "/usr/local/lib/python3.5/site-packages/libnacl/__init__.py", line 83, in <module>
    nacl = _get_nacl()
  File "/usr/local/lib/python3.5/site-packages/libnacl/__init__.py", line 81, in _get_nacl
    raise OSError(msg)
OSError: Could not locate nacl lib, searched for libsodium.so, libsodium.so.18, libsodium.so.17, libsodium.so.13, libsodium.so.10, libsodium.so.5, libsodium.so.4, 
```
### Setup
Setup py3 machine with `transport: raet`.

### Steps to Reproduce Issue
Try to install dependencies.
```
[root@li982-154 ~]# pip3 install raet ioflo
Collecting raet
  Downloading raet-0.6.7.tar.gz (806kB)
    100% |████████████████████████████████| 806kB 502kB/s 
Collecting ioflo
  Downloading ioflo-1.6.7.tar.gz (819kB)
    100% |████████████████████████████████| 823kB 495kB/s 
Collecting libnacl>=1.4.3 (from raet)
  Downloading libnacl-1.5.0.tar.gz (47kB)
    100% |████████████████████████████████| 49kB 3.6MB/s 
Collecting six>=1.6.1 (from raet)
  Downloading six-1.10.0-py2.py3-none-any.whl
Installing collected packages: ioflo, libnacl, six, raet
  Running setup.py install for ioflo
  Running setup.py install for libnacl
  Running setup.py install for raet
Successfully installed ioflo-1.6.7 libnacl-1.5.0 raet-0.6.7 six-1.10.0
[root@li982-154 ~]# salt-call --local pkg.install libsodium
Traceback (most recent call last):
  File "/usr/local/bin/salt-call", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/root/salt/scripts/salt-call", line 11, in <module>
    salt_call()
  File "/root/salt/salt/scripts.py", line 386, in salt_call
    import salt.cli.call
  File "/root/salt/salt/cli/call.py", line 9, in <module>
    import salt.cli.caller
  File "/root/salt/salt/cli/caller.py", line 37, in <module>
    from raet import raeting, nacling
  File "/usr/local/lib/python3.5/site-packages/raet/__init__.py", line 12, in <module>
    importlib.import_module(".{0}".format(m), package='raet')
  File "/usr/local/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.5/site-packages/raet/nacling.py", line 11, in <module>
    import libnacl
  File "/usr/local/lib/python3.5/site-packages/libnacl/__init__.py", line 83, in <module>
    nacl = _get_nacl()
  File "/usr/local/lib/python3.5/site-packages/libnacl/__init__.py", line 81, in _get_nacl
    raise OSError(msg)
OSError: Could not locate nacl lib, searched for libsodium.so, libsodium.so.18, libsodium.so.17, libsodium.so.13, libsodium.so.10, libsodium.so.5, libsodium.so.4, 
[root@li982-154 ~]# salt-call --local pkg.install python-libnacl
Traceback (most recent call last):
  File "/usr/local/bin/salt-call", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/root/salt/scripts/salt-call", line 11, in <module>
    salt_call()
  File "/root/salt/salt/scripts.py", line 386, in salt_call
    import salt.cli.call
  File "/root/salt/salt/cli/call.py", line 9, in <module>
    import salt.cli.caller
  File "/root/salt/salt/cli/caller.py", line 37, in <module>
    from raet import raeting, nacling
  File "/usr/local/lib/python3.5/site-packages/raet/__init__.py", line 12, in <module>
    importlib.import_module(".{0}".format(m), package='raet')
  File "/usr/local/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.5/site-packages/raet/nacling.py", line 11, in <module>
    import libnacl
  File "/usr/local/lib/python3.5/site-packages/libnacl/__init__.py", line 83, in <module>
    nacl = _get_nacl()
  File "/usr/local/lib/python3.5/site-packages/libnacl/__init__.py", line 81, in _get_nacl
    raise OSError(msg)
OSError: Could not locate nacl lib, searched for libsodium.so, libsodium.so.18, libsodium.so.17, libsodium.so.13, libsodium.so.10, libsodium.so.5, libsodium.so.4, 
```

### Versions Report
```
Salt Version:
           Salt: 2017.5.0-740-gdb109a3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.6.7
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.0 (default, May 24 2017, 16:56:16)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.1.6
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 4.9.15-x86_64-linode81
         system: Linux
        version: CentOS Linux 7.3.1611 Core
 ```

**Comment by gtmanfred** [comment]
This works if you have libsodium installed.

This is mentioned on the raet page that libsodium is required.

```
Using RAET in Salt is easy, the main difference is that the core dependencies change, instead of needing pycrypto, M2Crypto, ZeroMQ, and PYZMQ, the packages libsodium, libnacl, ioflo, and raet are required. Encryption is handled very cleanly by libnacl, while the queueing and flow control is handled by ioflo. Distribution packages are forthcoming, but libsodium can be easily installed from source, or many distributions do ship packages for it. The libnacl and ioflo packages can be easily installed from pypi, distribution packages are in the works.
```

Then it works.

```
[root@salt ~]# salt-call --local pkg.install python-libnacl
local:
    ----------
    python-libnacl:
        ----------
        new:
            1.4.3-1.el7
        old:
```

**Comment by frogunder** [comment]
Must have been something in my previous setup. Working correctly now. 
Closing the issue.
