### ISSUE TITLE
Windows - WIN_STATUS error 

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#41428]
### Description of Issue/Question
In Nitrogen when running `status.cpuload` it fails on windows with this error:
```
    The minion function caused an exception: Traceback (most recent call last):
      File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1466, in _thread_return
        return_data = executor.execute()
      File "c:\salt\bin\lib\site-packages\salt\executors\direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "c:\salt\bin\lib\site-packages\salt\modules\win_status.py", line 87, in cpuload
        return int(__salt__['cmd.run'](cmd).split('=')[1])
    ValueError: invalid literal for int() with base 10: '67\r\r\n\r\r\n\r\r\nLoadPercentage'
```

### Setup
Set up windows environment. 

### Steps to Reproduce Issue
run command `salt '*' status.cpuload`
```
win-py3:
    The minion function caused an exception: Traceback (most recent call last):
      File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1466, in _thread_return
        return_data = executor.execute()
      File "c:\salt\bin\lib\site-packages\salt\executors\direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "c:\salt\bin\lib\site-packages\salt\modules\win_status.py", line 87, in cpuload
        return int(__salt__['cmd.run'](cmd).split('=')[1])
    ValueError: invalid literal for int() with base 10: '67\r\r\n\r\r\n\r\r\nLoadPercentage'
```
See it on both py2 and py3 setups/

### Versions Report
```
Salt Version:
           Salt: 2017.5.0-97-gdb109a3
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: unknown
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.3
          ioflo: 1.6.7
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: 1.5.0
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.0
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6
 
System Versions:
           dist:   
        machine: AMD64
        release: 2016Server
         system: Windows
        version: 2016Server 10.0.14393 SP0 Multiprocessor Free
```

**Comment by gtmanfred** [comment]
```
[windows]: PS C:\salt> .\salt '*' status.cpuload
Active code page: 65001
windows.c.gtmanfred-1263.internal:
    2
Active code page: 437
[windows]: PS C:\salt> .\salt-call --versions-report
Salt Version:
           Salt: 2017.5.0-97-gdb109a3

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.3
          ioflo: 1.6.7
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: 1.5.0
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.0
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
        machine: AMD64
        release: 2016Server
         system: Windows
        version: 2016Server 10.0.14393 SP0 Multiprocessor Free
```

**Comment by gtmanfred** [comment]
This appears to be a problem when there is more than 1 physical cpu available on the windows server.

```
[windows]: PS C:\Users\daniel\Documents> wmic cpu get loadpercentage /value
LoadPercentage=1
[windows]: PS C:\Users\dwallace\Documents> Get-WmiObject Win32_ComputerSystem | Select NumberOfProcessors,NumberOfLogicalProcessors

NumberOfProcessors NumberOfLogicalProcessors
------------------ -------------------------
                 1                         8
```

I only get one return, but with more than one physical cpus, it will provide one output per core.

The above one with the error had 4 processers and 4 logical processors.

We should add the values together and divide by the number of responses to get the load.

Daniel
