### ISSUE TITLE
salt-minion-2016.11.5+ds-2 redis-returners not working

### ISSUE THREAD

**Issue by oule** [saltstack/salt#41447]
### Setup

my salt-minion installed to debian-8.2

/etc/salt/minion's contents as below:

```
master: 10.1.1.100
id:  10.1.1.201
log_level: garbage
return:
  - sqlite3
  - redis
sqlite3.database: /tmp/salt.db
sqlite3.timeout: 5.0
redis.host: '10.1.1.100'
redis.port: 6379
redis.db: '0'
```

my master installed to CentOS-6.5 x64 and version is salt-master-2016.11.5-3.el6.noarch
on master run command as below:

```
salt '10.1.1.201' test.ping

result as below:
10.1.1.201:
    True
```

but have not contents in redis-server and i found error in minion's logs as below:

```
2017-05-26 17:43:53,701 [salt.minion                                          ][ERROR   ][28880] The return failed for job 20170526175027868393 'keep_jobs'
2017-05-26 17:43:53,701 [salt.minion                                          ][ERROR   ][28880] Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1575, in _thread_return
    minion_instance.returners[returner_str](ret)
  File "/usr/lib/python2.7/dist-packages/salt/returners/redis_return.py", line 131, in returner
    pipeline.expire('ret:{0}'.format(jid), _get_ttl())
  File "/usr/lib/python2.7/dist-packages/salt/returners/redis_return.py", line 120, in _get_ttl
    return __opts__['keep_jobs'] * 3600
KeyError: 'keep_jobs'
```

I don't know is this a bug
I edit /usr/lib/python2.7/dist-packages/salt/returners/redis_return.py file,
replace return __opts__['keep_jobs'] * 3600 with return 3600
it's work fine
how to resolv this question

**Comment by oule** [comment]
I not found "keep_jobs" in /etc/salt/minion
and found it in /etc/salt/master
but set keep_jobs: 1 in master,No effect

**Comment by oule** [comment]
where config key keep_jobs

**Comment by Ch3LL** [comment]
@oule can you try https://github.com/saltstack/salt/pull/41469

**Comment by oule** [comment]
@Ch3LL 
I'm try now
Thank you very much

**Comment by oule** [comment]
@Ch3LL 
It works fine~
The default value used
Thank you very much
^_^

**Comment by Ch3LL** [comment]
Awesome thanks for testing it out. I will close the issue :)
