### ISSUE TITLE
Nitrogen - Windows Master - Proxy Minion Fails on Py2

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#41507]
### Description of Issue/Question
Setting up environment for Proxy Minion on Windows Master on py2 gives error.
Same setup on Windows Master on py3 is working fine, only error on py2.

### Setup
set up proxy minion environment on py2.

```
Master config:
c:/salt/conf/master

pillar_roots:
  base:
    - c:/salt-manual-tests/proxy/pillar
file_roots:
  base:
    - c:/salt-manual-tests/proxy/states
```

```
proxy config:
c:/salt/conf/proxy

master: localhost
add_proxymodules_to_opts: false
```

### Steps to Reproduce Issue
Run `salt-proxy --proxyid=p8000 -l debug` when accepting the key,  you will see this in the minion log.

```
DEBUG   ] Connecting to master. Attempt 1 (infinite attempts)
DEBUG   ] Re-using AsyncAuth for ('c:\\salt\\conf\\pki\\minion', u'p8000', 'tcp://127.0.0.1:4506')
DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (9611)
DEBUG   ] Setting zmq_reconnect_ivl to '9611ms'
DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
DEBUG   ] subclassed _post_master_init
DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', u'p8000', 'tcp://127.0.0.1:4506',
aes')
DEBUG   ] Re-using AsyncAuth for ('c:\\salt\\conf\\pki\\minion', u'p8000', 'tcp://127.0.0.1:4506')
DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
DEBUG   ] Reading configuration from c:\salt\conf\proxy
DEBUG   ] Including configuration from 'c:\salt\conf\.'
DEBUG   ] Reading configuration from c:\salt\conf\.
CRITICAL] Unexpected error while connecting to localhost
raceback (most recent call last):
 File "C:\salt\bin\lib\site-packages\salt\minion.py", line 876, in _connect_minion
   yield minion.connect_master(failed=failed)
 File "C:\salt\bin\lib\site-packages\tornado\gen.py", line 1055, in run
   value = future.result()
 File "C:\salt\bin\lib\site-packages\tornado\concurrent.py", line 238, in result
   raise_exc_info(self._exc_info)
 File "C:\salt\bin\lib\site-packages\tornado\gen.py", line 1063, in run
   yielded = self.gen.throw(*exc_info)
 File "C:\salt\bin\lib\site-packages\salt\minion.py", line 1054, in connect_master
   yield self._post_master_init(master)
 File "C:\salt\bin\lib\site-packages\tornado\gen.py", line 1055, in run
   value = future.result()
 File "C:\salt\bin\lib\site-packages\tornado\concurrent.py", line 238, in result
   raise_exc_info(self._exc_info)
 File "C:\salt\bin\lib\site-packages\tornado\gen.py", line 1069, in run
   yielded = self.gen.send(value)
 File "C:\salt\bin\lib\site-packages\salt\minion.py", line 3116, in _post_master_init
   self.functions, self.returners, self.function_errors, self.executors = self._load_modules()
 File "C:\salt\bin\lib\site-packages\salt\minion.py", line 1219, in _load_modules
   self.opts['grains'] = salt.loader.grains(self.opts, force_refresh, proxy=proxy)
 File "C:\salt\bin\lib\site-packages\salt\loader.py", line 678, in grains
   default_include, opts['conf_file'], verbose=False
 File "C:\salt\bin\lib\site-packages\salt\config\__init__.py", line 2037, in include_config
   opts = _read_conf_file(fn_)
 File "C:\salt\bin\lib\site-packages\salt\config\__init__.py", line 1887, in _read_conf_file
   with salt.utils.fopen(path, 'r') as conf_file:
 File "C:\salt\bin\lib\site-packages\salt\utils\__init__.py", line 1345, in fopen
   fhandle = open(*args, **kwargs)  # pylint: disable=resource-leakage
OError: [Errno 13] Permission denied: u'c:\\salt\\conf\\.'
```
### Versions Report
```
Salt Version:
           Salt: 2017.5.0-97-gdb109a3

Dependency Versions:
           cffi: 1.10.0
       cherrypy: unknown
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.3
          ioflo: 1.6.7
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: 1.5.0
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.4.0
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
        machine: AMD64
        release: 2016Server
         system: Windows
        version: 2016Server 10.0.14393  Multiprocessor Free
```

**Comment by gtmanfred** [comment]
Yup, i am seeing the same thing.

@twangboy do you have any idea why this would be able to read c:\salt\conf\proxy to get started and then fail later one?

```
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
[DEBUG   ] subclassed _post_master_init
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', u'p8000', 'tcp://127.0.0.1:4506', 'aes')
[DEBUG   ] Re-using AsyncAuth for ('c:\\salt\\conf\\pki\\minion', u'p8000', 'tcp://127.0.0.1:4506')
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
[DEBUG   ] Reading configuration from c:\salt\conf\proxy
[DEBUG   ] Including configuration from 'c:\salt\conf\.'
[DEBUG   ] Reading configuration from c:\salt\conf\.
[CRITICAL] Unexpected error while connecting to localhost
Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 876, in _connect_minion
    yield minion.connect_master(failed=failed)
  File "C:\salt\bin\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "C:\salt\bin\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "C:\salt\bin\lib\site-packages\tornado\gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 1054, in connect_master
    yield self._post_master_init(master)
  File "C:\salt\bin\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "C:\salt\bin\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "C:\salt\bin\lib\site-packages\tornado\gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 3116, in _post_master_init
    self.functions, self.returners, self.function_errors, self.executors = self._load_modules()
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 1219, in _load_modules
    self.opts['grains'] = salt.loader.grains(self.opts, force_refresh, proxy=proxy)
  File "C:\salt\bin\lib\site-packages\salt\loader.py", line 678, in grains
    default_include, opts['conf_file'], verbose=False
  File "C:\salt\bin\lib\site-packages\salt\config\__init__.py", line 2037, in include_config
    opts = _read_conf_file(fn_)
  File "C:\salt\bin\lib\site-packages\salt\config\__init__.py", line 1887, in _read_conf_file
    with salt.utils.fopen(path, 'r') as conf_file:
  File "C:\salt\bin\lib\site-packages\salt\utils\__init__.py", line 1345, in fopen
    fhandle = open(*args, **kwargs)  # pylint: disable=resource-leakage
IOError: [Errno 13] Permission denied: u'c:\\salt\\conf\\.'
```

Thanks,
Daniel

**Comment by twangboy** [comment]
@gtmanfred Part of the start up process locks down the `C:\salt` directory, maybe that's what's doing it... Maybe it's being launched with a non-administrator account, then the directories get locked down. I don't know.

https://github.com/saltstack/salt/blob/nitrogen/salt/utils/verify.py#L524

**Comment by cachedout** [comment]
@twangboy We need this problem fixed ASAP. What do we need to do to figure this out?

**Comment by twangboy** [comment]
It's crashing trying to load `c:\salt\conf\.` It only tries to load this in Py2. There must be a gate somewhere making it try to load that...

**Comment by twangboy** [comment]
@cachedout I think this is the right fix.

**Comment by cachedout** [comment]
@twangboy I appreciate you getting on this so quickly!

@gtmanfred or @frogunder could one of you please test this tonight or first thing in the morning?

**Comment by frogunder** [comment]
Just tested this. It is working fine for me with the fix.

**Comment by cachedout** [comment]
Thanks very much @frogunder
