### ISSUE TITLE
salt-call event.send fails from Python script

### ISSUE THREAD

**Issue by spiispa** [saltstack/salt#41521]
### Description of Issue/Question
salt-call event.send fails from Python script with "Invalid master key" error

### Setup
Salt master and minion in quite basic setup (ZeroMQ, sha256...)

### Steps to Reproduce Issue
This works:
salt-call event.send 'myco/mytag/success' '{success: True}'

Running a python script like this:

```
    #!/usr/bin/env python3
    import salt.client
    caller = salt.client.Caller('/etc/salt/minion')
    caller.sminion.functions['event.send'](
        'myco/myevent/success',
        {
            'success': True,
        }
   )
```

With error:

```
_Exception ignored in: <bound method RSAX931Verifier.__del__ of <salt.utils.rsax931.RSAX931Verifier object at 0x7f5a143597b8>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/salt/utils/rsax931.py", line 144, in __del__
    libcrypto.BIO_free(self._bio)
AttributeError: 'RSAX931Verifier' object has no attribute '_bio'
Traceback (most recent call last):
  File "/tmp/test.py", line 25, in <module>
    caller = salt.client.Caller('/etc/salt/minion')
  File "/usr/local/lib/python3.5/dist-packages/salt/client/__init__.py", line 1872, in __init__
    self.sminion = salt.minion.SMinion(self.opts)
  File "/usr/local/lib/python3.5/dist-packages/salt/minion.py", line 667, in __init__
    lambda: self.eval_master(self.opts, failed=True)
  File "/usr/local/lib/python3.5/dist-packages/tornado/ioloop.py", line 458, in run_sync
    return future_cell[0].result()
  File "/usr/local/lib/python3.5/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.5/dist-packages/salt/minion.py", line 644, in eval_master
    raise exc
  File "/usr/local/lib/python3.5/dist-packages/salt/minion.py", line 636, in eval_master
    yield pub_channel.connect()
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/local/lib/python3.5/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.5/dist-packages/salt/transport/zeromq.py", line 386, in connect
    yield self.auth.authenticate()
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/local/lib/python3.5/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/lib/python3.5/dist-packages/salt/crypt.py", line 486, in _authenticate
    creds = yield self.sign_in(channel=channel)
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/local/lib/python3.5/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python3.5/dist-packages/salt/crypt.py", line 622, in sign_in
    raise SaltClientError('Invalid master key')
salt.exceptions.SaltClientError: Invalid master key_
```

Also the following python script fails:

```
    #!/usr/bin/env python3
    import os
    os.system("salt-call trace event.send 'myco/mytag/success' '{success: True}'")
```

With error:

```
[ERROR   ] The master failed to decrypt the random minion token
Exception ignored in: <bound method RSAX931Verifier.__del__ of <salt.utils.rsax931.RSAX931Verifier object at 0x7fdc563470b8>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/salt/utils/rsax931.py", line 144, in __del__
    libcrypto.BIO_free(self._bio)
AttributeError: 'RSAX931Verifier' object has no attribute '_bio'
[CRITICAL] The Salt Master server's public key did not authenticate!
The master may need to be updated if it is a version of Salt lower than 2016.11.5, or
If you are confident that you are connecting to a valid Salt Master, then remove the master public key and restart the Salt Minion.
The master public key can be found at:
/etc/salt/pki/minion/minion_master.pub
Invalid master key
```

### Versions Report

```
Master:
Salt Version:
           Salt: 2016.11.5

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-83-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

Minion:

```
Salt Version:
           Salt: 2016.11.5

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.2 (default, Nov 17 2016, 17:05:23)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-62-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by Ch3LL** [comment]
I cannot replicate this. If you run any  other module (test.ping for example) in the script does it also fail in that way?  Also how did you install salt?

**Comment by spiispa** [comment]
Hmm... this:

#!/usr/bin/env python3
import salt.client
caller = salt.client.Caller()
caller.cmd('test.ping')

Seems to also fail with error:
Exception ignored in: <bound method RSAX931Verifier.__del__ of <salt.utils.rsax931.RSAX931Verifier object at 0x7f23aa3917b8>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/salt/utils/rsax931.py", line 144, in __del__
    libcrypto.BIO_free(self._bio)
AttributeError: 'RSAX931Verifier' object has no attribute '_bio'
Traceback (most recent call last):
  File "/tmp/test.py", line 40, in <module>
    caller = salt.client.Caller()
  File "/usr/local/lib/python3.5/dist-packages/salt/client/__init__.py", line 1872, in __init__
    self.sminion = salt.minion.SMinion(self.opts)
  File "/usr/local/lib/python3.5/dist-packages/salt/minion.py", line 667, in __init__
    lambda: self.eval_master(self.opts, failed=True)
  File "/usr/local/lib/python3.5/dist-packages/tornado/ioloop.py", line 458, in run_sync
    return future_cell[0].result()
  File "/usr/local/lib/python3.5/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.5/dist-packages/salt/minion.py", line 644, in eval_master
    raise exc
  File "/usr/local/lib/python3.5/dist-packages/salt/minion.py", line 636, in eval_master
    yield pub_channel.connect()
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/local/lib/python3.5/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.5/dist-packages/salt/transport/zeromq.py", line 386, in connect
    yield self.auth.authenticate()
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/local/lib/python3.5/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/lib/python3.5/dist-packages/salt/crypt.py", line 486, in _authenticate
    creds = yield self.sign_in(channel=channel)
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/local/lib/python3.5/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python3.5/dist-packages/salt/crypt.py", line 622, in sign_in
    raise SaltClientError('Invalid master key')
salt.exceptions.SaltClientError: Invalid master key

Strangely enough, now when I logged in to the server even the salt-call commands fail.
For example:
salt-call test.ping

Gives now:
[ERROR   ] The master failed to decrypt the random minion token
Exception ignored in: <bound method RSAX931Verifier.__del__ of <salt.utils.rsax931.RSAX931Verifier object at 0x7f2feeb1bfd0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/salt/utils/rsax931.py", line 144, in __del__
    libcrypto.BIO_free(self._bio)
AttributeError: 'RSAX931Verifier' object has no attribute '_bio'
[CRITICAL] The Salt Master server's public key did not authenticate!
The master may need to be updated if it is a version of Salt lower than 2016.11.5, or
If you are confident that you are connecting to a valid Salt Master, then remove the master public key and restart the Salt Minion.
The master public key can be found at:
/etc/salt/pki/minion/minion_master.pub
Invalid master key

Minion has been installed with salt-bootstrap
Master has been installed with apt-get and updated few times

I have installed the salt python package with:
pip3 install salt
Can that break salt-call?

**Comment by rehmanzile** [comment]
@spiispa Are you running the python script as `root` or `sudo`?
