### ISSUE TITLE
Nitrogen - error when running state containing an pkg.installed of an .rpm

### ISSUE THREAD

**Issue by ssgward** [saltstack/salt#41527]
Nitrogen - error when running state containing an pkg.installed of an .rpm. This is from our SSE install states.

This is the command we run: `salt-call state.apply eAPI`

Here is the error:
```
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 1822, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1727, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/states/pkg.py", line 1300, in installed
    **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/states/pkg.py", line 541, in _find_install_targets
    source_info = __salt__['lowpkg.bin_pkg_info'](cached_path)
  File "/usr/lib/python2.7/site-packages/salt/modules/rpm.py", line 120, in bin_pkg_info
    for field in pkginfo._fields:
AttributeError: 'NoneType' object has no attribute '_fields'

[WARNING ] The function "module.run" is using its deprecated version and will expire in version "Fluorine".
```
Here is the same error within the state output:
```
local:
----------
          ID: install-deps
    Function: pkg.installed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1822, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1727, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/pkg.py", line 1300, in installed
                  **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/pkg.py", line 541, in _find_install_targets
                  source_info = __salt__['lowpkg.bin_pkg_info'](cached_path)
                File "/usr/lib/python2.7/site-packages/salt/modules/rpm.py", line 120, in bin_pkg_info
                  for field in pkginfo._fields:
              AttributeError: 'NoneType' object has no attribute '_fields'
     Started: 20:03:28.510332
    Duration: 2176.325 ms
```
This is the section in the state that is failing:
```
install-deps:
  pkg.installed:
    - refresh: True
    - sources:
      - epel-release: https://download.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
{% if grains['os'] == 'CentOS' %} 
      - ius-release: https://centos7.iuscommunity.org/ius-release.rpm
{% elif grains['os'] == 'RedHat' %}
      - ius-release: https://rhel7.iuscommunity.org/ius-release.rpm
{% endif %}
{% endif %} 
```
Running the same .rpms listed above manually via `yum install` works fine--no errors.

Same state works correctly when running against 2016.3.x  and 2016.11.x

Salt Versions Report:
```
Salt Version:
           Salt: 2017.5.0-997-g8849884

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

**Comment by ssgward** [comment]
I guess there's the chance that we need to change our syntax in the install state for this new version. Please advise if that is the case.

**Comment by Ch3LL** [comment]
Looks like I am able to replicate this on python2 and git bisect shows commit: 01d6ee176d347fd341e7d45236cc62871a6dda21 which is PR https://github.com/saltstack/salt/pull/39649

Here is a docker container for anyone to quickly replicate:
1. `docker run -it -v /home/ch3ll/git/salt/:/testing/ ch3ll/issues:41527 salt-call --local state.sls test` (where /home/ch3ll/git/salt/ is a local cloned git repo of salt)

**Comment by terminalmage** [comment]
Fixed in https://github.com/saltstack/salt/pull/41553.
