### ISSUE TITLE
salt-syndic: ERROR Future exception was never retrieved

### ISSUE THREAD

**Issue by jaipepe** [saltstack/salt#41534]
### Description of Issue/Question
Seeing the following in my logs. I am not sure how to reproduce as it just seems to show up and correlate to the salt syndic being unresponsive.

```
May 31 20:09:37 mm1hostname salt-syndic: [ERROR   ] Future exception was never retrieved: Traceback (most recent call last):
May 31 20:09:37 mm1hostname salt-syndic: File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 876, in run
May 31 20:09:37 mm1hostname salt-syndic: yielded = self.gen.throw(*exc_info)
May 31 20:09:37 mm1hostname salt-syndic: File "/usr/lib/python2.7/site-packages/salt/minion.py", line 2379, in _return_pub_multi
May 31 20:09:37 mm1hostname salt-syndic: sync=False)
May 31 20:09:37 mm1hostname salt-syndic: File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 870, in run
May 31 20:09:37 mm1hostname salt-syndic: value = future.result()
May 31 20:09:37 mm1hostname salt-syndic: File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result
May 31 20:09:37 mm1hostname salt-syndic: raise_exc_info(self._exc_info)
May 31 20:09:37 mm1hostname salt-syndic: File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 876, in run
May 31 20:09:37 mm1hostname salt-syndic: yielded = self.gen.throw(*exc_info)
May 31 20:09:37 mm1hostname salt-syndic: File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1156, in _send_req_async
May 31 20:09:37 mm1hostname salt-syndic: ret = yield channel.send(load, timeout=timeout)
May 31 20:09:37 mm1hostname salt-syndic: File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 870, in run
May 31 20:09:37 mm1hostname salt-syndic: value = future.result()
May 31 20:09:37 mm1hostname salt-syndic: File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result
May 31 20:09:37 mm1hostname salt-syndic: raise_exc_info(self._exc_info)
May 31 20:09:37 mm1hostname salt-syndic: File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 876, in run
May 31 20:09:37 mm1hostname salt-syndic: yielded = self.gen.throw(*exc_info)
May 31 20:09:37 mm1hostname salt-syndic: File "/usr/lib/python2.7/site-packages/salt/transport/zeromq.py", line 271, in send
May 31 20:09:37 mm1hostname salt-syndic: ret = yield self._crypted_transfer(load, tries=tries, timeout=timeout)
May 31 20:09:37 mm1hostname salt-syndic: File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 870, in run
May 31 20:09:37 mm1hostname salt-syndic: value = future.result()
May 31 20:09:37 mm1hostname salt-syndic: File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result
May 31 20:09:37 mm1hostname salt-syndic: raise_exc_info(self._exc_info)
May 31 20:09:37 mm1hostname salt-syndic: File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 876, in run
May 31 20:09:37 mm1hostname salt-syndic: yielded = self.gen.throw(*exc_info)
May 31 20:09:37 mm1hostname salt-syndic: File "/usr/lib/python2.7/site-packages/salt/transport/zeromq.py", line 239, in _crypted_tra
nsfer
May 31 20:09:37 mm1hostname salt-syndic: ret = yield _do_transfer()
May 31 20:09:37 mm1hostname salt-syndic: File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 870, in run
May 31 20:09:37 mm1hostname salt-syndic: value = future.result()
May 31 20:09:37 mm1hostname salt-syndic: File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result
May 31 20:09:37 mm1hostname salt-syndic: raise_exc_info(self._exc_info)
May 31 20:09:37 mm1hostname salt-syndic: File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 876, in run
May 31 20:09:37 mm1hostname salt-syndic: yielded = self.gen.throw(*exc_info)
May 31 20:09:37 mm1hostname salt-syndic: File "/usr/lib/python2.7/site-packages/salt/transport/zeromq.py", line 225, in _do_transfer
May 31 20:09:37 mm1hostname salt-syndic: tries=tries,
May 31 20:09:37 mm1hostname salt-syndic: File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 870, in run
May 31 20:09:37 mm1hostname salt-syndic: value = future.result()
May 31 20:09:37 mm1hostname salt-syndic: File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result
May 31 20:09:37 mm1hostname salt-syndic: raise_exc_info(self._exc_info)
May 31 20:09:37 mm1hostname salt-syndic: File "<string>", line 3, in raise_exc_info
May 31 20:09:37 mm1hostname salt-syndic: SaltReqTimeoutError: Message timed out
```
### Versions Report
Salt Version:
           Salt: 2016.3.5
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-327.4.4.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by gtmanfred** [comment]
Is it possible that this is failing when the syndic is running out of memory?

Thanks,
Daniel
