### ISSUE TITLE
npm install throws an error when using npm version 5.

### ISSUE THREAD

**Issue by edhgoose** [saltstack/salt#41562]
### Description of Issue/Question

npm install is throwing an error when npm is version 5+/nodejs is version 8. I believe this is something to do with the `npm list --global --json` command

### Setup
```
nodejs_repo:
  pkgrepo.managed:
    - humanname: NodeJS Upstream
    - baseurl: https://rpm.nodesource.com/pub_8.x/el/7/$basearch
    # From https://rpm.nodesource.com/pub/el/NODESOURCE-GPG-SIGNING-KEY-EL
    - gpgkey: https://rpm.nodesource.com/pub/el/NODESOURCE-GPG-SIGNING-KEY-EL

nodejs:
  pkg.installed:
    - require:
      - pkgrepo: nodejs_repo

# Because node is installed in a different folder on local machines to servers.
# Alternative would be to have a different "location of node bin" parameter in each parameters.yml file.
/usr/local/bin/node:
  file.symlink:
    - target: /usr/bin/node

/usr/local/lib/node_modules:
  file.symlink:
    - target: /usr/lib/node_modules/

less@1.3.2:
  npm.installed:
    - require:
      - pkg: nodejs
```

### Steps to Reproduce Issue

I have the above state, which installs nodejs 8 (and therefore npm5), as well as setting some symlinks for us and installing a specific version of less (1.3.2).

When executed with salt this error is returned. All other states run fine, it's just the npm install that fails. It may be worth noting that this package is currently installed from before we upgraded to npm5/nodejs8.

```
----------
          ID: less@1.3.2
    Function: npm.installed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.6/site-packages/salt/state.py", line 1746, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.6/site-packages/salt/loader.py", line 1704, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.6/site-packages/salt/states/npm.py", line 99, in installed
                  installed_pkgs = __salt__['npm.list'](dir=dir, runas=user, env=env)
                File "/usr/lib/python2.6/site-packages/salt/modules/npm.py", line 314, in list_
                  return json.loads(result['stdout']).get('dependencies', {})
                File "/usr/lib64/python2.6/json/__init__.py", line 307, in loads
                  return _default_decoder.decode(s)
                File "/usr/lib64/python2.6/json/decoder.py", line 319, in decode
                  obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                File "/usr/lib64/python2.6/json/decoder.py", line 336, in raw_decode
                  obj, end = self._scanner.iterscan(s, **kw).next()
                File "/usr/lib64/python2.6/json/scanner.py", line 55, in iterscan
                  rval, next_pos = action(m, context)
                File "/usr/lib64/python2.6/json/decoder.py", line 183, in JSONObject
                  value, end = iterscan(s, idx=end, context=context).next()
                File "/usr/lib64/python2.6/json/scanner.py", line 55, in iterscan
                  rval, next_pos = action(m, context)
                File "/usr/lib64/python2.6/json/decoder.py", line 183, in JSONObject
                  value, end = iterscan(s, idx=end, context=context).next()
                File "/usr/lib64/python2.6/json/scanner.py", line 55, in iterscan
                  rval, next_pos = action(m, context)
                File "/usr/lib64/python2.6/json/decoder.py", line 183, in JSONObject
                  value, end = iterscan(s, idx=end, context=context).next()
                File "/usr/lib64/python2.6/json/scanner.py", line 55, in iterscan
                  rval, next_pos = action(m, context)
                File "/usr/lib64/python2.6/json/decoder.py", line 183, in JSONObject
                  value, end = iterscan(s, idx=end, context=context).next()
                File "/usr/lib64/python2.6/json/scanner.py", line 55, in iterscan
                  rval, next_pos = action(m, context)
                File "/usr/lib64/python2.6/json/decoder.py", line 183, in JSONObject
                  value, end = iterscan(s, idx=end, context=context).next()
                File "/usr/lib64/python2.6/json/scanner.py", line 55, in iterscan
                  rval, next_pos = action(m, context)
                File "/usr/lib64/python2.6/json/decoder.py", line 183, in JSONObject
                  value, end = iterscan(s, idx=end, context=context).next()
                File "/usr/lib64/python2.6/json/scanner.py", line 55, in iterscan
                  rval, next_pos = action(m, context)
                File "/usr/lib64/python2.6/json/decoder.py", line 183, in JSONObject
                  value, end = iterscan(s, idx=end, context=context).next()
                File "/usr/lib64/python2.6/json/scanner.py", line 55, in iterscan
                  rval, next_pos = action(m, context)
                File "/usr/lib64/python2.6/json/decoder.py", line 183, in JSONObject
                  value, end = iterscan(s, idx=end, context=context).next()
                File "/usr/lib64/python2.6/json/scanner.py", line 55, in iterscan
                  rval, next_pos = action(m, context)
                File "/usr/lib64/python2.6/json/decoder.py", line 183, in JSONObject
                  value, end = iterscan(s, idx=end, context=context).next()
                File "/usr/lib64/python2.6/json/scanner.py", line 55, in iterscan
                  rval, next_pos = action(m, context)
                File "/usr/lib64/python2.6/json/decoder.py", line 183, in JSONObject
                  value, end = iterscan(s, idx=end, context=context).next()
                File "/usr/lib64/python2.6/json/scanner.py", line 55, in iterscan
                  rval, next_pos = action(m, context)
                File "/usr/lib64/python2.6/json/decoder.py", line 183, in JSONObject
                  value, end = iterscan(s, idx=end, context=context).next()
                File "/usr/lib64/python2.6/json/scanner.py", line 55, in iterscan
                  rval, next_pos = action(m, context)
                File "/usr/lib64/python2.6/json/decoder.py", line 183, in JSONObject
                  value, end = iterscan(s, idx=end, context=context).next()
                File "/usr/lib64/python2.6/json/scanner.py", line 55, in iterscan
                  rval, next_pos = action(m, context)
                File "/usr/lib64/python2.6/json/decoder.py", line 171, in JSONObject
                  raise ValueError(errmsg("Expecting property name", s, end))
              ValueError: Expecting property name: line 1385 column 41 (char 65534)
     Started: 12:16:35.979431
    Duration: 2524.821 ms
     Changes:
```

I've attached the output of `npm list --json --global` which is what I understand it to be running. It's a bit long. I can't see a property name which is what I understand the deocder.py to be looking for.

[npm-list.txt](https://github.com/saltstack/salt/files/1047643/npm-list.txt).

### Versions Report

npm is version 5.0.1, and the same happens for version 5.0.0.

Salt Master and Minion are the same (they're on the same machine in this case):

```
Salt Version:
           Salt: 2016.11.5

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.20.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: 0.20.3
         Python: 2.6.9 (unknown, Sep  1 2016, 23:34:36)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist:
        machine: x86_64
        release: 4.9.27-14.31.amzn1.x86_64
         system: Linux
        version: Not Installed
```

**Comment by gtmanfred** [comment]
I have replicated this issue.  It appears to be a change that they made in npm 5.0.0

Thanks for reporting,
Daniel

**Comment by gtmanfred** [comment]
@dschaller @holmboe Could yall take a look at this for us?

It looks like the update to npm 5.0.0 breaks the npm module.

Thanks,
Daniel

**Comment by dschaller** [comment]
I can take a look at this

**Comment by dschaller** [comment]
I dug into this and it seems that this isn't an issue with npm 5 but an issue with the output of `npm list` being too much for `subprocess.communicate` to store in it's buffered stdout response. I have a fix for this issue in https://github.com/saltstack/salt/pull/41575 that only returns the top level npm packages since that is all we require for the installed state. However, we should probably open a ticket to find a better way to store output rather than rely on communicate due to it's memory restrictions.

**Comment by dschaller** [comment]
@gtmanfred can you close this issue since the fix has been merged?

**Comment by gtmanfred** [comment]
Yup, done I have also marked that PR to be backported to 2016.11 and nitrogen.

Thanks for the help!
