### ISSUE TITLE
salt-api report 401 Unauthorized

### ISSUE THREAD

**Issue by oule** [saltstack/salt#41625]
my salt-api login failed

salt --versions-report
Salt Version:
           Salt: 2016.11.5
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.0.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Nov 22 2013, 12:16:22)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.5 Final
        machine: x86_64
        release: 2.6.32-431.el6.x86_64
         system: Linux
        version: CentOS 6.5 Final

/etc/salt/master
file_roots:
  base:
    - /srv/salt
/etc/salt/master.d/api.conf
rest_cherrypy:
  port: 8888
  debug: true
  disable_ssl: true
/etc/salt/master.d/eauth.conf
external_auth:
  pam:
    pengyao:
      - .*
      - '@wheel'
      - '@runner'

[root@localhost salt]# grep pengyao /etc/passwd
pengyao:x:10229:10229::/home/pengyao:/sbin/nologin

[root@localhost salt]# curl -H "Accept: application/x-yaml" -d username='pengyao' -d password='pengyao' -d eauth=pam http://localhost:8888/login
<!DOCTYPE html PUBLIC
"-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>401 Unauthorized</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>401 Unauthorized</h2>
        <p>Could not authenticate using provided credentials</p>
        <pre id="traceback">Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python2.6/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/netapi/rest_cherrypy/app.py", line 719, in hypermedia_handler
    ret = cherrypy.serving.request._hypermedia_inner_handler(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.6/site-packages/salt/netapi/rest_cherrypy/app.py", line 1676, in POST
    'Could not authenticate using provided credentials')
HTTPError: (401, 'Could not authenticate using provided credentials')
</pre>
    <div id="powered_by">
      <span>
        Powered by <a href="http://www.cherrypy.org">CherryPy unknown</a>
      </span>
    </div>
    </body>
</html>

**Comment by oule** [comment]
[root@localhost salt]# rpm -qa|grep -i cherrypy
python-cherrypy-5.6.0-1.el6.noarch
