### ISSUE TITLE
Saltstack error while running MySQL query 

### ISSUE THREAD

**Issue by varun292006** [saltstack/salt#41650]
### Description of Issue/Question
salt.modules.mysql.query.run throws TypeError: 'list' object is not callable

### Setup

I have Windows minions one of which is running MySQL server. I have a state file which looks like this:
```
get_ifile_data:
  mysql_query.run:
    - database: mysql
    - query: "SELECT User FROM user;"
    - output: "G:\\temp\\salt_data\\salt_log"
```
When I executed this it return the below error:

```
salt 'TEST-SERVER' state.apply test.get_iflie_data
TEST-SERVER:
----------
          ID: get_ifile_data
    Function: mysql_query.run
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "c:\salt\bin\lib\site-packages\salt\state.py", line 1746, in call
                  **cdata['kwargs'])
                File "c:\salt\bin\lib\site-packages\salt\loader.py", line 1704, in wrapper
                  return f(*args, **kwargs)
                File "c:\salt\bin\lib\site-packages\salt\states\mysql_query.py", line 151, in run
                  query_result = __salt__['mysql.query'](database, query, **connection_args)
                File "c:\salt\bin\lib\site-packages\salt\modules\mysql.py", line 645, in query
                  affected = _execute(cur, query)
                File "c:\salt\bin\lib\site-packages\salt\modules\mysql.py", line 544, in _execute
                  return cur.execute(qry)
                File "c:\salt\bin\lib\site-packages\pymysql\cursors.py", line 167, in execute
                  result = self._query(query)
                File "c:\salt\bin\lib\site-packages\pymysql\cursors.py", line 323, in _query
                  conn.query(q)
                File "c:\salt\bin\lib\site-packages\pymysql\connections.py", line 836, in query
                  self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                File "c:\salt\bin\lib\site-packages\pymysql\connections.py", line 1020, in _read_query_result
                  result.read()
                File "c:\salt\bin\lib\site-packages\pymysql\connections.py", line 1310, in read
                  self._read_result_packet(first_packet)
                File "c:\salt\bin\lib\site-packages\pymysql\connections.py", line 1369, in _read_result_packet
                  self._read_rowdata_packet()
                File "c:\salt\bin\lib\site-packages\pymysql\connections.py", line 1407, in _read_rowdata_packet
                  rows.append(self._read_row_from_packet(packet))
                File "c:\salt\bin\lib\site-packages\pymysql\connections.py", line 1426, in _read_row_from_packet
                  data = converter(data)
              TypeError: 'list' object is not callable
     Started: 15:05:26.630000
    Duration: 2023.0 ms
     Changes:

Summary for TEST-SERVER
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   2.023 s

```
Then I installed  MySQLdb python module installed on all of them and set my PATH and PYTHONPATH variables to below loacation:
```
PYTHONPATH --> C:\Python27;C:\Python27\Lib\site-packages;C:\Python27\Lib;C:\Python27\DLLs;C:\Python27\Lib\lib-tk;C:\Python27\Scripts

PATH --> C:\Python27;C:\Python27\Lib\site-packages;C:\Python27\Lib;C:\Python27\DLLs;C:\Python27\Lib\lib-tk;C:\Python27\Scripts
```

 and restarted salt-minion. Now salt is unable to connect to MySQL service running on minion

```
salt -t 60 'TEST-SERVER' state.apply test.get_iflie_data
TEST-SERVER:
----------
          ID: get_ifile_data
    Function: mysql_query.run
      Result: False
     Comment: MySQL Error 2003: Can't connect to MySQL server on 'localhost' (10061)
     Started: 15:06:24.701000
    Duration: 1115.0 ms
     Changes:

Summary for TEST-SERVER
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   1.115 s
```
If PYTHONPATH variable is removed and salt-minion service on minion is restarted then it connects to MySQL service but it again throws TypeError.

### Steps to Reproduce Issue

1. Create a state file as mentioned above
2. Install MySQL python and set the PATH and PYTHONPATH variable as mentioned
3. Execute the salt state file

### Versions Report
Version report is below:

```
Salt Version:
           Salt: 2016.11.5

Dependency Versions:
           cffi: 1.10.0
       cherrypy: unknown
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 2.0.8
          ioflo: 1.5.5
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.3.10
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 16.0.1
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.4.1
            ZMQ: 4.1.6

System Versions:
           dist:
        machine: AMD64
        release: UNKServer
         system: Windows
        version: UNKServer 6.1.7601 SP1 Multiprocessor Free

```

**Comment by Ch3LL** [comment]
Can you clarify if it works when using MySQLdb python module vs PyMySQL when note changing the PATHs? Just want to make sure your not running into: https://github.com/saltstack/salt/issues/39561

Also is your myslq server suppose to be `localhost`? just want to make sure its grabbing the correct opts after changing the path.

**Comment by varun292006** [comment]
Thanks for the reply.

No it doesn't work without changing the PATHs. Throws the same error.
I was hoping that changing of PATHs will solve the problem but it didn't.

And yes, MySQL server is localhost.
I have below lines in my minion configuration file:
```
mysql.host: 'localhost'
mysql.port: 3309
mysql.user: 'root'
mysql.pass: ' '
mysql.db: 'mysql'
mysql.charset: 'utf8'
```

**Comment by vquiering** [comment]
@varun292006 
Does it work when running the state locally using `salt-call`? This looks like an issue I'm facing where mysql query states won't apply when applied remote.

**Comment by pauldoom** [comment]
The issue (#39561) is still open.  As pointed out there, you can replace the pymysql module with MySQLdb to side step the issue.  (pip uninstall pymysql; pip install mysqlclient)
