### ISSUE TITLE
`docker_container.running` image id error

### ISSUE THREAD

**Issue by epelc** [saltstack/salt#41676]
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Run a state with
```
run:
    docker_container.running:
      - name: someregistry.com/org/myimage:sometag
```
The image is already present/downloaded.

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

```
          ID: run
    Function: docker_container.running
        Name: freightchick
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1822, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1708, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/docker_container.py", line 1576, in running
                  image_id = __salt__['docker.inspect_image'](image)['Id']
              KeyError: 'Id'
     Started: 11:33:00.118690
    Duration: 36.126 ms
     Changes:   

```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
           Salt: 2017.5.0-241-gbc0f969
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: 2.3.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.4.0-36-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by epelc** [comment]
My salt minion was mixed up after switching to the dev branch.
