### ISSUE TITLE
Salt Cloud PowerVC with Nova driver

### ISSUE THREAD

**Issue by claudekenni** [saltstack/salt#41739]
### Description of Issue/Question
I'm trying to see if the salt-cloud nova driver works with PowerVC which is based on OpenStack
The error down there seems to be related to the salt cloud code.
### Setup
```
powervc:
  use_keystoneauth: True
  auth_version: 3
  identity_url: 'https://****:5000/v3.0'
  compute_name: nova
  compute_region: RegionOne
  service_type: compute
  verify: '/etc/pki/tls/certs/powervc.crt'
  tenant: ibm-default
  user: root
  password: ****
  driver: nova
```
### Steps to Reproduce Issue
```
salt-cloud -f network_list powervc -l debug

[ERROR   ] There was an error running the function: __init__() got an unexpected keyword argument 'session'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 274, in run
    self.function_provider, self.function_name, kwargs
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1619, in do_function
    driver: self.clouds[fun](call='function')
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/nova.py", line 1322, in network_list
    conn = get_conn()
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/nova.py", line 316, in get_conn
    conn = nova.SaltNova(**kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/utils/openstack/nova.py", line 234, in __init__
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/utils/openstack/nova.py", line 285, in _new_init
    conn = client.Client(version=self.version, session=self.session, **self.client_kwargs)
  File "/usr/lib/python2.7/dist-packages/novaclient/client.py", line 506, in Client
    return client_class(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'session'
```

### Versions Report
```
salt --versions-report
Salt Version:
           Salt: 2016.11.5

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.11 (default, Dec 15 2015, 16:46:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-88-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by garethgreenaway** [comment]
Thanks for the report @claudekenni.  It looks like the the PowerVC service is just different enough to not work with the Salt OpenStack driver.  I've marked this as approved for future development.

**Comment by claudekenni** [comment]
I did some more testing and now it says that the python-novaclient is not installed


```
root@xxxx:~#  salt-cloud -f network_list powervc
[INFO    ] salt-cloud starting
[WARNING ] Missing dependency: 'python-novaclient'. The nova driver requires 'python-novaclient' to be installed.
[WARNING ] The cloud driver, 'nova', configured under the 'powervc' cloud provider alias, could not be loaded. Please check your provider configuration files and ensure all required dependencies are installed for the 'nova' driver.
In rare cases, this could indicate the 'nova.get_configured_provider()' function could not be found.
Removing 'nova' from the available providers list

root@xxxx:~# pip install python-novaclient
Requirement already satisfied (use --upgrade to upgrade): python-novaclient in /usr/local/lib/python2.7/dist-packages
Cleaning up...

root@xxxx:~# pip install python-novaclient --upgrade
Requirement already up-to-date: python-novaclient in /usr/local/lib/python2.7/dist-packages
Cleaning up...

```

**Comment by t0rrant** [comment]
I get the same symptoms with the nova driver.

I have tried with salt version 2018.3.3 from pip and with version 2017.7.4 from the ubuntu official repositories, result is the same.

#### Steps to Reproduce Issue

```
$ salt-cloud -c config/ --log-file=salt-cloud.log --list-images my-openstack
[WARNING ] Missing dependency: 'python-novaclient'. The nova driver requires 'python-novaclient' to be installed.
[WARNING ] The cloud driver, 'nova', configured under the 'openstack-dsi' cloud provider alias, could not be loaded.
Please check your provider configuration files and ensure all required dependencies are installed for the 'nova' driver.
In rare cases, this could indicate the 'nova.get_configured_provider()' function could not be found.
```

To note that  ``In rare cases, this could indicate the 'nova.get_configured_provider()' function could not be found`` is indeed the case:

```
$ python
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import nova
>>> dir(nova)
['__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', 'eventlet', 'os', 'oslo_service']
>>> 
```

### Versions Report

```
Salt Version:
            Salt: 2017.7.4
 
Dependency Versions:
 Apache Libcloud: 2.2.1
            cffi: Not Installed
        cherrypy: Not Installed
        dateutil: 2.6.1
       docker-py: Not Installed
           gitdb: Not Installed
       gitpython: Not Installed
           ioflo: Not Installed
          Jinja2: 2.10
         libgit2: Not Installed
         libnacl: Not Installed
        M2Crypto: Not Installed
            Mako: 1.0.7
    msgpack-pure: Not Installed
  msgpack-python: 0.5.6
    mysql-python: Not Installed
       pycparser: Not Installed
        pycrypto: 2.6.1
    pycryptodome: Not Installed
          pygit2: Not Installed
          Python: 3.6.7 (default, Oct 22 2018, 11:32:17)
    python-gnupg: Not Installed
          PyYAML: 3.12
           PyZMQ: Not Installed
            RAET: Not Installed
           smmap: Not Installed
         timelib: Not Installed
         Tornado: 4.5.3
             ZMQ: Not Installed
 
System Versions:
            dist: Ubuntu 18.04 bionic
          locale: UTF-8
         machine: x86_64
         release: 4.15.0-43-generic
          system: Linux
         version: Ubuntu 18.04 bionic
```
