### ISSUE TITLE
Salt won't provision grafana dashboards with an TLS-enabled Grafana install 

### ISSUE THREAD

**Issue by CJCShadowsan** [saltstack/salt#41828]
### Description of Issue/Question
Salt fails to provision a dashboard with a TLS-enabled Grafana install. Note that this runs perfectly fine on a non-TLS grafana install.

Error I get is:
`ID: dynamic_dashboard
Function: grafana_dashboard.present
Name: Host Overview
Result: False
Comment: An exception occurred in this state: Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/salt/state.py", line 1746, in call
**cdata['kwargs'])
File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1703, in wrapper
return f(*args, **kwargs)
File "/usr/lib/python2.7/site-packages/salt/states/grafana_dashboard.py", line 124, in present
old_dashboard = _get(url, profile)
File "/usr/lib/python2.7/site-packages/salt/states/grafana_dashboard.py", line 424, in _get
timeout=profile.get('grafana_timeout', 3),
File "/usr/lib/python2.7/site-packages/requests/api.py", line 68, in get
return request('get', url, **kwargs)
File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
response = session.request(method=method, url=url, **kwargs)
File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 464, in request
resp = self.send(prep, **send_kwargs)
File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
r = adapter.send(request, **kwargs)
File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine('\x15\x03\x01\x00\x02\x02\n',))
Started: 11:05:53.485218
Duration: 280.839 ms
Changes:`

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
dashboard.sls:
[root@mgmt01 grafana]# cat dashboard.sls

dynamic_dashboard:
  grafana_dashboard.present:
    - name: "Host Overview"
    - base_dashboards_from_pillar:
      - grafana_dashboards
    - base_rows_from_pillar:
      - grafana_rows
    - base_panels_from_pillar:
      - grafana_panels
    - dashboard:
        rows:
          - title: System Details
            editable: False
            panels:
{% for item,data in pillar['grafana_panels']['main'].iteritems() %}
              - {{ data }}
{% endfor %}
          - title: $nodename
            editable: False
            collapse: False
            repeat: nodename
            panels:
{% for item,data in pillar['grafana_panels']['node'].iteritems() %}
              - {{ data }}
{% endfor %}

### Steps to Reproduce Issue
Install Grafana
Install TLS cert(s)
Run dashboard salt state

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
`[root@mgmt01 grafana]# salt --versions-report
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.6.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug 29 2016, 10:12:21)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.2 Maipo
        machine: x86_64
        release: 3.10.0-327.36.3.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.2 Maipo
`

**Comment by CJCShadowsan** [comment]
Ignore this - caused by misconfiguration.
