### ISSUE TITLE
salt-cloud Vmware pyvmomi - The vCenter Server is unable to decrypt passwords stored in the customization specification.

### ISSUE THREAD

**Issue by code42fr** [saltstack/salt#41832]
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

Error when i want to deploy a Microsoft VMs with SALT-CLOUD & Vmware driver.

I don't have problem with the deployement of Linux VMs.

A message in the LOG show "The vCenter Server is unable to decrypt passwords stored in the customization specification."

In the past, with VCSA 5.5, i didn't had problem.

i've see this -> https://github.com/nmadhok/saltconf16/blob/master/SAMPLES/vmware-sdb_setup.sh but i think it's only a store the Vsphere/VCSA password.

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

VCSA 6.5
SALT MASTER & SALT CLOUD 2016.11.5
PYVMOMI last version

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2016.11.5
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: 1.6.7
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: 1.5.0
       M2Crypto: 0.26.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.3 (default, Jun 21 2016, 18:38:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 13.1.0
           RAET: 0.6.7
          smmap: 0.8.2
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 7.11 
        machine: x86_64
        release: 3.2.0-4-amd64
         system: Linux
        version: debian 7.11

**Comment by garethgreenaway** [comment]
Thanks for the report @code42fr!

**Comment by konstest** [comment]
Hi
I have the same problem.
```
[ERROR   ] Error creating test-win2012: The vCenter Server is unable to decrypt passwords stored in the customization specification.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/vmware.py", line 2694, in create
    salt.utils.vmware.wait_for_task(task, vm_name, 'clone', 5, 'info')
  File "/usr/lib/python2.7/dist-packages/salt/utils/vmware.py", line 1326, in wait_for_task
    raise salt.exceptions.VMwareApiError(exc.msg)
VMwareApiError: The vCenter Server is unable to decrypt passwords stored in the customization specification.
[INFO    ] Complete
[DEBUG   ] LazyLoaded nested.output
test-win2012:
    ----------
    Error:
        Error creating test-win2012: The vCenter Server is unable to decrypt passwords stored in the customization specification.
```
Deployment of Linux hosts is also OK

I tried it on different salt-masters/clouds/pyvmomi versions
```
salt-cloud 2016.11.4 (Carbon) - fail
salt-cloud 2016.11.6 (Carbon) - fail
salt-cloud 2017.5.0-63-g51af494 - fail
salt-cloud 2017.7.0-308-g68c84a2 (Nitrogen) - fail
pyvmomi==6.5 - fail
pyvmomi==6.0.0.2016.6 - fail
```

**Comment by konstest** [comment]
This error ony appear if we are redefine the 'network' block
```
    network:
      Network adapter 1:
        name: Servers
        switch_type: distributed
        ip: 11.22.33.44
        gateway: [11.22.33.1]
        subnet_mask: 255.255.255.0
```

If we do't set 'network' block is all OK

**Comment by code42fr** [comment]
@konstest : thans for your info. Same as you, we've test different version of pyvmomi & salt-cloud. So, we don't upgrade to the latest. We already use salt-cloud 2015.8.9.

Tomorrow, I'll try your tricks.

After we must find where is the problem, pyvmomi OR salt-master ?

Last question : Which version of VCSA or VCENTER do you use ? 5.5, 6.x or 6.5 ?

**Comment by konstest** [comment]
VMware vCenter Server Version: 6.0.0 Build: 3634793

**Comment by konstest** [comment]
Setting option [plain_text: True](https://github.com/saltstack/salt/blob/develop/salt/cloud/clouds/vmware.py#L2410) in profile configuration file resolve this problem:

```
  win_installer: /tmp/salt-minion-AMD64.exe
  win_username: Administrator
  win_password: 'security_pass'
  plain_text: True

  use_winrm: True
  winrm_port: 5985
  winrm_use_ssl: False
```

**Comment by code42fr** [comment]
> You must clear all network configurations from Windows template before you will be deploying a new VMs
If we let the interface with a DHCP configuration, i think, it'll work
