### ISSUE TITLE
Thorium: unable to execute runners

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#41869]
### Description of Issue/Question

I have setup Thorium to send a HipChat message through the ```salt.cmd``` runner (calling the ```hipchat.send_message``` does not depend on a certain minion).

### Setup

Thorium configuration:

```yaml
too_many_commits:
  runner.cmd:
    - fun: salt.cmd
    - arg:
      - hipchat.send_message
    - kwargs:
      - room_id: 1717
      - message: too many commits
      - from_name: ''
      - api_key: Ag56uXGGB6jTh1Lc8sEpZOgX6rMCm7M5wN6dPLFd
      - api_version: v2
```

While from the CLI, the command works fine and posts indeed to HipChat:

```bash
salt-run salt.cmd hipchat.send_message 1717 'too many commits' '' api_key='Ag56uXGGB6jTh1Lc8sEpZOgX6rMCm7M5wN6dPLFd' api_version='v2'
```

### Steps to Reproduce Issue

Error traceback (from master logs):

```
[DEBUG   ] LazyLoaded runner.cmd
[INFO    ] Running state [too_many_commits] at time 09:32:15.553993
[INFO    ] Executing state runner.cmd for too_many_commits
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/home/admin/salt/salt/state.py", line 1750, in call
    **cdata['kwargs'])
  File "/home/admin/salt/salt/loader.py", line 1705, in wrapper
    return f(*args, **kwargs)
  File "/home/admin/salt/salt/thorium/runner.py", line 47, in cmd
    client.cmd_async(low)
  File "/home/admin/salt/salt/runner.py", line 117, in cmd_async
    reformatted_low = self._reformat_low(low)
  File "/home/admin/salt/salt/runner.py", line 73, in _reformat_low
    verify_fun(self.functions, fun)
  File "/home/admin/salt/salt/utils/lazy.py", line 23, in verify_fun
    raise salt.exceptions.CommandExecutionError(lazy_obj.missing_fun_string(fun))
CommandExecutionError: 'cmd' is not available.
```

### Versions Report

```yaml
Salt Version:
           Salt: 2016.11.5-120-ge7fc30f

Dependency Versions:
           cffi: 1.10.0
       cherrypy: Not Installed
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.6
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.6
```

**Comment by mirceaulinic** [comment]
Adding this diff:

```diff
diff --git a/salt/thorium/runner.py b/salt/thorium/runner.py
index 33cf363..39576c9 100644
--- a/salt/thorium/runner.py
+++ b/salt/thorium/runner.py
@@ -6,7 +6,9 @@ React by calling async runners
 from __future__ import absolute_import
 # import salt libs
 import salt.runner
+import logging

+log = logging.getLogger(__file__)

 def cmd(
         name,
@@ -38,8 +40,10 @@ def cmd(
            'changes': {},
            'comment': '',
            'result': True}
+    log.debug('Executing with fun={}'.format(fun))
     if fun is None:
         fun = name
+    log.debug('Executing runner fun: {}'.format(fun))
     client = salt.runner.RunnerClient(__opts__)
     low = {'fun': fun,
             'arg': arg,
```

Logs:

```log
[INFO    ] Executing state runner.cmd for too_many_commits
[DEBUG   ] Executing with fun=cmd
[DEBUG   ] Executing runner fun: cmd
```

Apparently, the function name is not send properly.

**Comment by mirceaulinic** [comment]
Well, even when the function is corrected to `salt.cmd` as it has to, there's a different problem:

```logs
[DEBUG   ] Executing runner fun: salt.cmd
[DEBUG   ] LazyLoaded salt.cmd
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'ip-172-31-11-15.us-east-2.compute.internal_master', None, 'clear')
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/home/admin/salt/salt/state.py", line 1750, in call
    **cdata['kwargs'])
  File "/home/admin/salt/salt/loader.py", line 1705, in wrapper
    return f(*args, **kwargs)
  File "/home/admin/salt/salt/thorium/runner.py", line 52, in cmd
    client.cmd_async(low)
  File "/home/admin/salt/salt/runner.py", line 119, in cmd_async
    return mixins.AsyncClientMixin.cmd_async(self, reformatted_low)
  File "/home/admin/salt/salt/client/mixins.py", line 499, in cmd_async
    return self.master_call(**low)
  File "/home/admin/salt/salt/client/mixins.py", line 133, in master_call
    usage='master_call')
  File "/home/admin/salt/salt/transport/__init__.py", line 49, in factory
    return ReqChannel.factory(opts, **kwargs)
  File "/home/admin/salt/salt/transport/client.py", line 25, in factory
    sync = SyncWrapper(AsyncReqChannel.factory, (opts,), kwargs)
  File "/home/admin/salt/salt/utils/async.py", line 60, in __init__
    self.async = method(*args, **kwargs)
  File "/home/admin/salt/salt/transport/client.py", line 108, in factory
    return salt.transport.zeromq.AsyncZeroMQReqChannel(opts, **kwargs)
  File "/home/admin/salt/salt/transport/zeromq.py", line 89, in __new__
    new_obj.__singleton_init__(opts, **kwargs)
  File "/home/admin/salt/salt/transport/zeromq.py", line 159, in __singleton_init__
    self.master_uri,
  File "/home/admin/salt/salt/transport/zeromq.py", line 175, in master_uri
    return self.opts['master_uri']
KeyError: 'master_uri'
```

**Comment by mirceaulinic** [comment]
PR: #44781

**Comment by mirceaulinic** [comment]
Closed via https://github.com/saltstack/salt/commit/8ed6287762061ff463862e6cabde5b9398c38ae2
