### ISSUE TITLE
subjectAltName Issue

### ISSUE THREAD

**Issue by rlaing00** [saltstack/salt#41905]
### Description of Issue/Question

I wish to use subjectAltNames with my certificates however when I add the option into my statefile the render fails, without the same render will work correctly. At present I am running a three vagrant minions with Ubuntu 16.04 Lts, with the python-m2crypto library added to the two minions and the master.

### Setup

Please find the state files attached inside the zip file, I used the following top file with one minion being named CA and the other WWW
```
base:
  '*':
    - cert-server.cert
  'ca':
    - cert-server.ca
  'www':
    - cert-server.www
```
[cert-server.zip](https://github.com/saltstack/salt/files/1095285/cert-server.zip)

### Steps To Reproduce Issue
Make sure you have the peer.conf setup correctly to allow for either all peers to access or just the remote signing policy enabled on the master and the minions are named correctly, also you will need to make sure that you have python-m2crypto installed.

Once you can run the state correctly next add the following line into the www.sls state file.

`- subjectAltName: saltminion2.local`

You should acquire the follow output or similar.

**Salt-master output**
```
          ID: /etc/pki/www.crt
    Function: x509.certificate_managed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1746, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1704, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/x509.py", line 568, in certificate_managed
                  'New': __salt__['x509.read_certificate'](certificate=certificate)}
                File "/usr/lib/python2.7/dist-packages/salt/modules/x509.py", line 536, in read_certificate
                  cert = _get_certificate_obj(certificate)
                File "/usr/lib/python2.7/dist-packages/salt/modules/x509.py", line 349, in _get_certificate_obj
                  text = get_pem_entry(text, pem_type='CERTIFICATE')
                File "/usr/lib/python2.7/dist-packages/salt/modules/x509.py", line 472, in get_pem_entry
                  raise salt.exceptions.SaltInvocationError(errmsg)
              SaltInvocationError: PEM does not contain a single entry of type CERTIFICATE:
              Cannot create X509_Extension with name 'subjectAltName' and value 'saltminion2.local'
     Started: 17:02:30.917663
    Duration: 725.4 ms
     Changes:   

Summary for www
-------------
Succeeded: 17 (changed=2)
Failed:     1
```
Salt-Minion output
```
[INFO    ] Running state [/usr/local/share/ca-certificates] at time 17:04:44.988448
[INFO    ] Executing state file.directory for /usr/local/share/ca-certificates
[INFO    ] Directory /usr/local/share/ca-certificates is in the correct state
[INFO    ] Completed state [/usr/local/share/ca-certificates] at time 17:04:44.990422 duration_in_ms=1.974
[DEBUG   ] LazyLoaded x509.pem_managed
[INFO    ] Running state [/usr/local/share/ca-certificates/intca.crt] at time 17:04:44.991473
[INFO    ] Executing state x509.pem_managed for /usr/local/share/ca-certificates/intca.crt
[INFO    ] File /usr/local/share/ca-certificates/intca.crt is in the correct state
[INFO    ] Completed state [/usr/local/share/ca-certificates/intca.crt] at time 17:04:44.995129 duration_in_ms=3.655
[INFO    ] Running state [/etc/pki] at time 17:04:44.995525
[INFO    ] Executing state file.directory for /etc/pki
[INFO    ] Directory /etc/pki is in the correct state
[INFO    ] Completed state [/etc/pki] at time 17:04:44.996629 duration_in_ms=1.104
[INFO    ] Running state [/etc/pki/www.crt] at time 17:04:44.996965
[INFO    ] Executing state x509.certificate_managed for /etc/pki/www.crt
[INFO    ] Publishing 'x509.sign_remote_certificate' to tcp://192.168.60.10:4506
[DEBUG   ] Re-using SAuth for ('/etc/salt/pki/minion', 'www', 'tcp://192.168.60.10:4506')
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'www', 'tcp://192.168.60.10:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'www', 'tcp://192.168.60.10:4506')
[INFO    ] Publishing 'x509.sign_remote_certificate' to tcp://192.168.60.10:4506
[DEBUG   ] Re-using SAuth for ('/etc/salt/pki/minion', 'www', 'tcp://192.168.60.10:4506')
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'www', 'tcp://192.168.60.10:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'www', 'tcp://192.168.60.10:4506')
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1746, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1704, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/states/x509.py", line 568, in certificate_managed
    'New': __salt__['x509.read_certificate'](certificate=certificate)}
  File "/usr/lib/python2.7/dist-packages/salt/modules/x509.py", line 536, in read_certificate
    cert = _get_certificate_obj(certificate)
  File "/usr/lib/python2.7/dist-packages/salt/modules/x509.py", line 349, in _get_certificate_obj
    text = get_pem_entry(text, pem_type='CERTIFICATE')
  File "/usr/lib/python2.7/dist-packages/salt/modules/x509.py", line 472, in get_pem_entry
    raise salt.exceptions.SaltInvocationError(errmsg)
SaltInvocationError: PEM does not contain a single entry of type CERTIFICATE:
Cannot create X509_Extension with name 'subjectAltName' and value 'saltminion2.local'

[INFO    ] Completed state [/etc/pki/www.crt] at time 17:04:45.714212 duration_in_ms=717.243
[DEBUG   ] File /var/cache/salt/minion/accumulator/140509761687824 does not exist, no need to cleanup.
[DEBUG   ] Minion return retry timer set to 9 seconds (randomized)
[INFO    ] Returning information for job: 20170622160442736491
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'www', 'tcp://192.168.60.10:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'www', 'tcp://192.168.60.10:4506')
``` 

### Versions Report
```
Salt Version:
           Salt: 2016.11.5
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-81-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

If you require any more information please let me know.

**Comment by Ch3LL** [comment]
I believe the format of that argument needs to look like: `- subjectAltName: 'DNS:saltminion2.local'`

Does that work?

**Comment by rlaing00** [comment]
Indeed that did work, I would like to ask what is the correct syntax for IP's and multiple DNS names? The project I am working on has some bizarre networking with docker containers and I am seeking to automate it.

**Comment by rlaing00** [comment]
Hi there please consider the issue close after inspecting a couple of examples I realised that the correct syntax is very much what I put into the post and the items are simple a long string with the DNS: or IP: separating them out after a ,

I would still like to request an example of be added into the documentation as I have not acumlated a huge volume of expose to using certificates and I feel this information might be assumed on the part of the person trying too deploy certificates.

Thank you very much for the learning opportunity and please give my heartfelt thanks to the other remember of the Salt-Stack team.

**Comment by Ch3LL** [comment]
We can definitely add an example to documentaion. You are welcome to try to add this to the docs as well. I'll re-open this issue and label as a documentation feature to add. If you do want to try to add an example please let me know if you have any questions on how to submit a PR

**Comment by rlaing00** [comment]
Sure I would like to submit a request, how does one go about this?
