### ISSUE TITLE
"salt-run state.event" reporting exception after CTRL+C

### ISSUE THREAD

**Issue by markostanojlovic** [saltstack/salt#41935]
### Description of Issue/Question
"salt-run state.event" reporting exception after CTRL+C - would be nice not to have exceptions displayed

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
- no special sls files, clean instllation 
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

salt-run state.event

^CException occurred in runner state.event: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 395, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/runners/state.py", line 205, in event
    node=node)
  File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 1757, in event
    ret = sevent.get_event(full=True, auto_reconnect=True)
  File "/usr/lib/python2.7/site-packages/salt/utils/event.py", line 644, in get_event
    ret = self._get_event(wait, tag, match_func, no_block)
  File "/usr/lib/python2.7/site-packages/salt/utils/event.py", line 538, in _get_event
    raw = self.subscriber.read_sync(timeout=wait)
  File "/usr/lib/python2.7/site-packages/salt/transport/ipc.py", line 685, in read_sync
    self.io_loop.start()
  File "/usr/lib64/python2.7/site-packages/tornado/ioloop.py", line 861, in start
    event_pairs = self._impl.poll(poll_timeout)
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 70, in _handle_signals
    hardcrash, trace=trace)
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 40, in _handle_interrupt
    raise exc
SystemExit: 
Exiting gracefully on Ctrl-c
[ERROR   ] Future exception was never retrieved: StreamClosedError: Stream is closed

### Versions Report
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: 1.9.1
       cherrypy: unknown
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: 0.25.1
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: 0.25.0
         Python: 2.7.13 (default, Jan 03 2017, 17:41:54) [GCC]
   python-gnupg: 0.3.9
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.2
 
System Versions:
           dist:   
        machine: x86_64
        release: 4.11.5-1-default
         system: Linux
        version: Not Installed

**Comment by gtmanfred** [comment]
Yes, I have seen this and we should catch it.

Thanks for reporting,
Daniel

**Comment by piersf** [comment]
Any date when this will be fixed?
It's still happening with 2017.7.5
