### ISSUE TITLE
Unexpected COM error

### ISSUE THREAD

**Issue by Astarandel** [saltstack/salt#42043]
Hello,

we are using salt-minions on 40 Windows nodes which are connected to a salt master.

salt-minion version: 2016.11.4 (Carbon)
salt master version: 2016.11.2 (Carbon)

Today I have the following problem with two of the salt-minions.

Debug Log.

2017-06-30 14:59:13,081 [salt.log.setup   ][ERROR   ][11056] An un-handled exception was caught by salt's global exception handler:
x_wmi: <x_wmi: Unexpected COM Error (-2147217404, 'OLE error 0x80041004', None, None)>
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-minion", line 26, in <module>
    salt_minion()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 159, in salt_minion
    minion.start()
  File "C:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 345, in start
    self.minion.tune_in()
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 889, in tune_in
    self._spawn_minions()
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 848, in _spawn_minions
    jid_queue=self.jid_queue,
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 829, in _create_minion_object
    jid_queue=jid_queue)
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 967, in __init__
    self.opts['grains'] = salt.loader.grains(opts)
  File "C:\salt\bin\lib\site-packages\salt\loader.py", line 701, in grains
    ret = fun()
  File "C:\salt\bin\lib\site-packages\salt\grains\core.py", line 1786, in hwaddr_interfaces
    ifaces = _get_interfaces()
  File "C:\salt\bin\lib\site-packages\salt\grains\core.py", line 1144, in _get_interfaces
    _INTERFACES = salt.utils.network.interfaces()
  File "C:\salt\bin\lib\site-packages\salt\utils\network.py", line 603, in interfaces
    return win_interfaces()
  File "C:\salt\bin\lib\site-packages\salt\utils\network.py", line 559, in win_interfaces
    for iface in c.Win32_NetworkAdapterConfiguration(IPEnabled=1):
  File "C:\salt\bin\lib\site-packages\wmi.py", line 819, in query
    handle_com_error ()
  File "C:\salt\bin\lib\site-packages\wmi.py", line 241, in handle_com_error
    raise klass (com_error=err)
x_wmi: <x_wmi: Unexpected COM Error (-2147217404, 'OLE error 0x80041004', None, None)>

**Comment by garethgreenaway** [comment]
@Astarandel Thanks for the report.  Can you please provide the output from:
`salt --versions-report`

Thanks!

**Comment by Astarandel** [comment]
Hello @garethgreenaway ,

thanks for your reply.

Here is the log you've requested.

Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 19 2017, 14:48:08)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.2.1
 
System Versions:
           dist: Ubuntu 17.04 zesty
        machine: x86_64
        release: 4.10.0-21-generic
         system: Linux
        version: Ubuntu 17.04 zesty

Strangely there is no problem with the minions today. I have no idea why. One thing that comes to mind is that when I was preforming the tests on Friday, the machines were rendering and CPU load was around 100%.
