### ISSUE TITLE
Publisher ACL System for Groups

### ISSUE THREAD

**Issue by CMeza99** [saltstack/salt#42060]
### Feature request

Currently the Publisher ACL System allow users other than root to execute salt commands, but only users. I it would be really helpful if groups could be given permissions rather than a per user basis.

**Comment by gtmanfred** [comment]
You should be able to use groups.

https://docs.saltstack.com/en/latest/topics/eauth/index.html#groups

**Comment by CMeza99** [comment]
trying groups with `publisher_acl`:

```
publisher_acl:
  admin%:
    - test.ping
```

2016.11.5:
```
[ERROR   ] ACL user admin% is not available
```

2016.11.6:
```
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
KeyError: 'getpwnam(): name not found: admin%'
Traceback (most recent call last):
  File "/usr/bin/salt-master", line 11, in <module>
    load_entry_point('salt==2016.11.6', 'console_scripts', 'salt-master')()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 90, in salt_master
    master.start()
  File "/usr/lib/python2.7/site-packages/salt/cli/daemons.py", line 204, in start
    super(Master, self).start()
  File "/usr/lib/python2.7/site-packages/salt/utils/parsers.py", line 948, in start
    self.prepare()
  File "/usr/lib/python2.7/site-packages/salt/cli/daemons.py", line 185, in prepare
    self.master = salt.master.Master(self.config)
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 400, in __init__
    SMaster.__init__(self, opts)
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 121, in __init__
    self.key = self.__prep_key()
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 145, in __prep_key
    return salt.daemons.masterapi.access_keys(self.opts)
  File "/usr/lib/python2.7/site-packages/salt/daemons/masterapi.py", line 262, in access_keys
    keys[user] = mk_key(opts, user)
  File "/usr/lib/python2.7/site-packages/salt/daemons/masterapi.py", line 226, in mk_key
    os.chown(keyfile, pwd.getpwnam(user).pw_uid, -1)
KeyError: 'getpwnam(): name not found: admin%'
```

**Comment by gtmanfred** [comment]
Oh, sorry, that is for external auth, not publisher acls.

Yes, it would be nice to have publisheracls accept groups.  I am going to mark this as a feature request.

Thanks,
Daniel

**Comment by ooboyle** [comment]
Seriously need this feature right now as well. Please expedite!

**Comment by ev0rtex** [comment]
I'd really like to +1 this...I recently started looking into a way to allow other users to run certain salt commands and it would be awesome if I could add and remove users from a group that I grant access to.

**Comment by gtmanfred** [comment]
Pull requests welcome!

This is not on the top of any ones list right now unfortunately.

**Comment by ev0rtex** [comment]
@gtmanfred... I may dig in if I get some time and see if I can figure out what it would take to implement. If it's not too bad I wouldn't mind doing a PR

**Comment by ooboyle** [comment]
I'm happy to beta test something. I have an excellent record for breaking things...

Oliver
________________________________________

**Comment by oogali** [comment]
This is still a desired feature request that I wouldn't like to see automatically closed...

**Comment by ooboyle** [comment]
Agreed

-------- Original message --------

**Comment by AmbicaY** [comment]
Can we reopen this request or need to file a new one? I have been waiting for this feature for some time now.

**Comment by Heiko-san** [comment]
yes please reopen

**Comment by adcpdk** [comment]
Hi team, is there any progress on this one?

**Comment by racooper** [comment]
nearly 6 years, this seems such a basic feature, and already supported with external_auth, why is it still not supported for publisher_acl?
