### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 49: ordinal not in range(128)

### ISSUE THREAD

**Issue by lichtamberg** [saltstack/salt#42083]
Happens with tag 2017.7, 2017.5 and 2017.7-branch and running `salt-ssh "myhost" state.highstate`...
OSX Sierra with latest updates, salt installed via soure code/github, python via homebrew.

After commenting out `% self.args` it works...

```
# /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py
        if self.args:
            msg = msg #% self.args
```

```shell
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 49: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/bin/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/usr/local/lib/python2.7/site-packages/salt/scripts.py", line 416, in salt_ssh
    client.run()
  File "/usr/local/lib/python2.7/site-packages/salt/cli/ssh.py", line 20, in run
    ssh = salt.client.ssh.SSH(self.config)
  File "/usr/local/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 320, in __init__
    self.mods = mod_data(self.fsclient)
  File "/usr/local/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 1362, in mod_data
    files = fsclient.file_list(env)
  File "/usr/local/lib/python2.7/site-packages/salt/fileclient.py", line 1272, in file_list
    return [sdecode(fn_) for fn_ in self.channel.send(load)]
  File "/usr/local/lib/python2.7/site-packages/salt/fileserver/__init__.py", line 891, in send
    return getattr(self.fs, cmd)(load)
  File "/usr/local/lib/python2.7/site-packages/salt/fileserver/__init__.py", line 751, in file_list
    ret.update(self.servers[fstr](load))
  File "/usr/local/lib/python2.7/site-packages/salt/fileserver/roots.py", line 421, in file_list
    return _file_lists(load, 'files')
  File "/usr/local/lib/python2.7/site-packages/salt/fileserver/roots.py", line 397, in _file_lists
    _add_to(ret['files'], path, root, files)
  File "/usr/local/lib/python2.7/site-packages/salt/fileserver/roots.py", line 343, in _add_to
    log.trace('roots: Processing %s', abs_path)
  File "/usr/local/lib/python2.7/site-packages/salt/log/mixins.py", line 35, in trace
    self.log(getattr(logging, 'TRACE', 5), msg, *args, **kwargs)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1231, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/salt/log/setup.py", line 313, in _log
    self, level, msg, args, exc_info=exc_info, extra=extra
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1285, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/usr/local/lib/python2.7/site-packages/salt/log/setup.py", line 347, in makeRecord
    exc_info, func)
  File "/usr/local/lib/python2.7/site-packages/salt/log/setup.py", line 194, in __init__
    self.colormsg = '%s%s%s' % (cmsg, self.getMessage(), reset)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 49: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/bin/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/usr/local/lib/python2.7/site-packages/salt/scripts.py", line 416, in salt_ssh
    client.run()
  File "/usr/local/lib/python2.7/site-packages/salt/cli/ssh.py", line 20, in run
    ssh = salt.client.ssh.SSH(self.config)
  File "/usr/local/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 320, in __init__
    self.mods = mod_data(self.fsclient)
  File "/usr/local/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 1362, in mod_data
    files = fsclient.file_list(env)
  File "/usr/local/lib/python2.7/site-packages/salt/fileclient.py", line 1272, in file_list
    return [sdecode(fn_) for fn_ in self.channel.send(load)]
  File "/usr/local/lib/python2.7/site-packages/salt/fileserver/__init__.py", line 891, in send
    return getattr(self.fs, cmd)(load)
  File "/usr/local/lib/python2.7/site-packages/salt/fileserver/__init__.py", line 751, in file_list
    ret.update(self.servers[fstr](load))
  File "/usr/local/lib/python2.7/site-packages/salt/fileserver/roots.py", line 421, in file_list
    return _file_lists(load, 'files')
  File "/usr/local/lib/python2.7/site-packages/salt/fileserver/roots.py", line 397, in _file_lists
    _add_to(ret['files'], path, root, files)
  File "/usr/local/lib/python2.7/site-packages/salt/fileserver/roots.py", line 343, in _add_to
    log.trace('roots: Processing %s', abs_path)
  File "/usr/local/lib/python2.7/site-packages/salt/log/mixins.py", line 35, in trace
    self.log(getattr(logging, 'TRACE', 5), msg, *args, **kwargs)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1231, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/salt/log/setup.py", line 313, in _log
    self, level, msg, args, exc_info=exc_info, extra=extra
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1285, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/usr/local/lib/python2.7/site-packages/salt/log/setup.py", line 347, in makeRecord
    exc_info, func)
  File "/usr/local/lib/python2.7/site-packages/salt/log/setup.py", line 194, in __init__
    self.colormsg = '%s%s%s' % (cmsg, self.getMessage(), reset)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 49: ordinal not in range(128)
```

```shell
Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: 0.9.2
       cherrypy: Not Installed
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.2.1
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.22
           Mako: 1.0.1
   msgpack-pure: 0.1.3
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.12
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Apr  4 2017, 08:46:44)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.6.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.1
            ZMQ: 4.0.5

System Versions:
           dist:
        machine: x86_64
        release: 15.6.0
         system: Darwin
        version: 10.11.6 x86_64
```

**Comment by gtmanfred** [comment]
What is the output of the `locale` command?

Are there any unicode characters that are being passed through?

Could you try this with running salt 2017.7 with python3, it should be compatible, and python3 handles unicode better than python2.

Thanks,
Daniel

**Comment by lichtamberg** [comment]
```shell
$ locale
LANG="de_AT.UTF-8"
LC_COLLATE="de_AT.UTF-8"
LC_CTYPE="de_AT.UTF-8"
LC_MESSAGES="de_AT.UTF-8"
LC_MONETARY="de_AT.UTF-8"
LC_NUMERIC="de_AT.UTF-8"
LC_TIME="de_AT.UTF-8"
LC_ALL=
```

Will try python 3 when I have more time..

**Comment by damon-atkins** [comment]
Link https://github.com/saltstack/salt/issues/42278 `salt logging with plain str (ascii) with unicode chars causes UnicodeDecodeError PY2`

Contains a workaround fix.
