### ISSUE TITLE
[2017.7.0rc1] TypeError in salt/fileclient on state.apply

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#42113]
### Description of Issue/Question
```
[root@mantle ~]# salt-call -l info state.apply
[INFO    ] Loading fresh modules for state activity
local:
    Data failed to compile:
----------
    Traceback (most recent call last):
  File "/opt/tools/lib/python2.7/site-packages/salt/state.py", line 3620, in call_highstate
    top = self.get_top()
  File "/opt/tools/lib/python2.7/site-packages/salt/state.py", line 3080, in get_top
    tops = self.get_tops()
  File "/opt/tools/lib/python2.7/site-packages/salt/state.py", line 2778, in get_tops
    saltenv
  File "/opt/tools/lib/python2.7/site-packages/salt/fileclient.py", line 189, in cache_file
    return self.get_url(path, '', True, saltenv, cachedir=cachedir)
  File "/opt/tools/lib/python2.7/site-packages/salt/fileclient.py", line 495, in get_url
    result = self.get_file(url, dest, makedirs, saltenv, cachedir=cachedir)
  File "/opt/tools/lib/python2.7/site-packages/salt/fileclient.py", line 1044, in get_file
    hash_server, stat_server = self.hash_and_stat_file(path, saltenv)
TypeError: 'bool' object is not iterable
```

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
I just upgraded to 2017.7.0rc1 and did a salt-call -l info state.apply to see if anything broke. It looks like it did, it didn't even get to the states.

I did not update the salt-master yet.

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
Upgraded (also tried a clean install + restore minion config) from the latest stable to the rc1 on SmartOS. Then ran a state.apply

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```yaml
[root@mantle ~]# salt-call --versions-report
Salt Version:
           Salt: 2017.7.0rc1

Dependency Versions:
           cffi: Not Installed
       cherrypy: 8.8.0
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: 1.6.7
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: 1.5.0
       M2Crypto: 0.22
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec 30 2016, 13:53:04)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: 0.6.6
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.1.4

System Versions:
           dist:
         locale: UTF-8
        machine: i86pc
        release: 5.11
         system: SunOS
        version: Not Installed
```

**Comment by sjorge** [comment]
Looks like it is because I did not update my master, creating a snapshot and will report back/
```[ERROR   ][11669] Received function _file_hash_and_stat which is unavailable on the master, returning False```

**Comment by sjorge** [comment]
Seems to be resolved if the master is upgraded first, although all the runs are now super slow.
