### ISSUE TITLE
salt-cloud errors on Rackspace driver using -out=yaml 

### ISSUE THREAD

**Issue by dubb-b** [saltstack/salt#42152]
#While trying to configure an new PR build slave, the build is throwing an exception.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/output/yaml_out.py", line 56, in output
    return yaml.dump(data, **params)
  File "/usr/lib64/python2.7/site-packages/yaml/__init__.py", line 202, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "/usr/lib64/python2.7/site-packages/yaml/__init__.py", line 190, in dump_all
    dumper.represent(data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 28, in represent
    node = self.represent_data(data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 57, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 223, in represent_dict
    return self.represent_mapping(u'tag:yaml.org,2002:map', data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 123, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 57, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 223, in represent_dict
    return self.represent_mapping(u'tag:yaml.org,2002:map', data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 123, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 57, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 223, in represent_dict
    return self.represent_mapping(u'tag:yaml.org,2002:map', data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 123, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 57, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 223, in represent_dict
    return self.represent_mapping(u'tag:yaml.org,2002:map', data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 123, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 67, in represent_data
    node = self.yaml_representers[None](self, data)
  File "/usr/lib64/python2.7/site-packages/yaml/representer.py", line 247, in represent_undefined
    raise RepresenterError("cannot represent an object: %s" % data)
RepresenterError: cannot represent an object: <libcloud.compute.drivers.openstack.OpenStack_1_1_NodeDriver object at 0x3ca5a50> 
```

### Setup
Installed new slave and setup salt via yum.

```
yum update
mkdir -p /var/lib/jenkins
yum install -y git gcc vim GitPython java-1.8.0-openjdk java-1.8.0-openjdk-headless
easy_install pip
sudo yum install -y https://repo.saltstack.com/yum/redhat/salt-repo-latest-2.el7.noarch.rpm
sudo yum install -y  salt-master salt-minion salt-ssh salt-syndic salt-cloud salt-api
pip install SaltTesting
```
### Steps to Reproduce Issue
run the following 2 commands:

```
salt-cloud  --list-images rackspace --out=json
salt-cloud  --list-images rackspace --out=yaml
```
The YAML is not rendering.

Ping @dubb-b for the machine if needed.

### Versions Report
```
Salt Version:
            Salt: 2016.11.6
 
Dependency Versions:
 Apache Libcloud: 0.20.0
            cffi: Not Installed
        cherrypy: 3.2.2
        dateutil: Not Installed
       docker-py: Not Installed
           gitdb: 0.6.4
       gitpython: 1.0.2
           ioflo: Not Installed
          Jinja2: 2.7.2
         libgit2: Not Installed
         libnacl: Not Installed
        M2Crypto: 0.26.0
            Mako: Not Installed
    msgpack-pure: Not Installed
  msgpack-python: 0.4.7
    mysql-python: Not Installed
       pycparser: Not Installed
        pycrypto: 2.6.1
    pycryptodome: Not Installed
          pygit2: Not Installed
          Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
    python-gnupg: Not Installed
          PyYAML: 3.11
           PyZMQ: 15.3.0
            RAET: Not Installed
           smmap: 0.9.0
         timelib: Not Installed
         Tornado: 4.2.1
             ZMQ: 4.1.4
 
System Versions:
            dist: centos 7.3.1611 Core
         machine: x86_64
         release: 3.10.0-514.21.1.el7.x86_64
          system: Linux
         version: CentOS Linux 7.3.1611 Core
```

**Comment by rallytime** [comment]
@dubb-b I have fixed this with the change in #42282.
