### ISSUE TITLE
UnicodeEncodeError smtp module

### ISSUE THREAD

**Issue by Giandom** [saltstack/salt#42169]
### Description of Issue/Question
Hi,
I've a state that send a email like this:
```
test-mail:
  smtp.send_msg:
    - name: 'Il servizio è down'
    - profile: my-smtp-login
    - recipient: test@mail.com
    - subject: 'Test Alert'
    - sender: salt@master.it
```
and I get this error:
```
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1420, in _thread_return
        return_data = executor.execute()
      File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 543, in apply_
        return sls(mods, **kwargs)
      File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 1039, in sls
        ret = st_.state.call_high(high_, orchestration_jid)
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 2269, in call_high
        chunks = self.compile_high_data(high, orchestration_jid)
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 1324, in compile_high_data
        chunks = self.order_chunks(chunks)
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 1261, in order_chunks
        chunks.sort(key=lambda chunk: (chunk['order'], '{0[state]}{0[name]}{0[fun]}'.format(chunk)))
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 1261, in <lambda>
        chunks.sort(key=lambda chunk: (chunk['order'], '{0[state]}{0[name]}{0[fun]}'.format(chunk)))
    UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 14: ordinal not in range(128)
```
My Salt version is:
```
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 2.0.0
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 2.0.1
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.10.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
``` 
There is a way to set UTF-8 encoding?

Thanks

**Comment by garethgreenaway** [comment]
@Giandom thanks for the report.  we should definitely support unicode characters in this situation.
