### ISSUE TITLE
Getting invalid region error for security group

### ISSUE THREAD

**Issue by briancuda** [saltstack/salt#42183]
### Description of Issue/Question
I am attempting to push a security group configuration for AWS in us-east-2 (Ohio) and receive the following error with a stack trace.  
```
An exception occurred in this state: Traceback (most recent call last):

                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1746, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1704, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/boto_secgroup.py", line 177, in present
                  key=key, keyid=keyid, profile=profile)
                File "/usr/lib/python2.7/site-packages/salt/states/boto_secgroup.py", line 223, in _security_group_present
                  profile, vpc_id, vpc_name)
                File "/usr/lib/python2.7/site-packages/salt/modules/boto_secgroup.py", line 102, in exists
                  conn = _get_conn(region=region, key=key, keyid=keyid, profile=profile)
                File "/usr/lib/python2.7/site-packages/salt/utils/boto.py", line 197, in get_connection
                  'valid.'.format(region))
SaltInvocationError: Region "us-east-2" is not valid
```
### Setup

```
secgroup_management:
  boto_secgroup.present:
    - name: Foo
    - description: Foo
    - vpc_id: vpc-XXXXXX
    - rules:
      - ip_protocol: tcp
        from_port: 22
        to_port: 22
        cidr_ip:
          - X.X.X.X/32
    - keyid: XXXXX
    - key: XXXXX
    - region: us-east-2
```

### Steps to Reproduce Issue
Any attempt to set the state from different regions results in this error:

```salt configsystem* state.sls ec2_secgroup_config-us-east-2```

### Versions Report
Master:
```
Salt Version:
           Salt: 2016.11.6
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.2.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3c1
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32-696.3.2.el6.x86_64
         system: Linux
        version: CentOS 6.7 Final
```
Minion:

```
Salt Version:
           Salt: 2016.11.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug 18 2016, 15:58:25)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-514.16.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

**Comment by garethgreenaway** [comment]
@briancuda Looks like to be related to the version of the boto library.
https://stackoverflow.com/questions/40479737/aws-ec2-us-east-2-is-an-invalid-region-choice

**Comment by briancuda** [comment]
@garethgreenaway that was the issue.  Updated the boto library on both machines to current and it took care of the issue.  Sorry for the false alarm.  boto-2.48.0 and boto3 1.4.4 solve it.

**Comment by garethgreenaway** [comment]
No worries :) Glad it got solved.
