### ISSUE TITLE
salt-ssh "NameError: global name 'contextkey' is not defined"

### ISSUE THREAD

**Issue by qiangshui** [saltstack/salt#42193]
### Description of Issue/Question
Running 'salt-ssh "test98" state.sls salt_install',
here is the error report:
    test98:
----------
          ID: /etc/yum.repos.d/salt-latest.repo
    Function: file.managed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/var/tmp/.root_7a3f7f_salt/py2/salt/state.py", line 1745, in call
                  **cdata['kwargs'])
                File "/var/tmp/.root_7a3f7f_salt/py2/salt/loader.py", line 1703, in wrapper
                  return f(*args, **kwargs)
                File "/var/tmp/.root_7a3f7f_salt/py2/salt/states/file.py", line 1814, in managed
                  __env__
                File "/var/tmp/.root_7a3f7f_salt/py2/salt/modules/file.py", line 3567, in source_list
                  __context__[contextkey] = ret
              NameError: global name 'contextkey' is not defined
     Started: 22:47:33.819505
    Duration: 44.402 ms
     Changes:   

my states file:
```
[root@salt salt]# cat salt_install.sls 
/etc/yum.repos.d/salt-latest.repo:
  file.managed:
    - source: salt://salt-latest.repo
```

salt version:
```
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3c1
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5
 
System Versions:
           dist: centos 6.8 Final
        machine: x86_64
        release: 2.6.32-642.el6.x86_64
         system: Linux
        version: CentOS 6.8 Final
```

**Comment by gtmanfred** [comment]
I am unable to replicate this.

```
[root@salt salt]# salt-ssh -w self state.apply test
self:
----------
          ID: /etc/yum.repos.d/salt-latest.repo
    Function: file.managed
      Result: True
     Comment: File /etc/yum.repos.d/salt-latest.repo updated
     Started: 14:51:53.137095
    Duration: 83.887 ms
     Changes:
              ----------
              diff:
                  New file
              mode:
                  0644

Summary for self
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  83.887 ms
```

Can you try to run `salt-ssh -w \* state.apply salt_install`?

I am wondering if there is just an old thin tarball that needs to be wiped out and recreated.

Thanks,
Daniel
