### ISSUE TITLE
SSLERROR when using HTTPS as source for file.managed

### ISSUE THREAD

**Issue by RobotLimeLtd** [saltstack/salt#42204]
### Description of Issue/Question
Getting SSLERROR when using https source for file.managed.  Running http.query gives same error.

The HTTPS sites have certificates that are signed by an internal CA, however, that CA is installed on the server.  Neither wget nor curl complain when downloading the same file.  

Code to install certs:

ca_certificates:
  pkg.installed:
    - name: ca-certificates

ca_bundle_cert:
  file.managed:
    - name: /etc/ssl/certs/ca-bundle.crt
    - source: salt://fctm-managed/files/tls-ca-bundle.pem
    - user: root
    - group: root
    - mode: 444
    - require:
      - pkg: ca_certificates

ca_bundle_trust_cert:
  file.managed:
    - name: /etc/ssl/certs/ca-bundle.trust.crt
    - source: salt://fctm-managed/files/ca-bundle.trust.crt
    - user: root
    - group: root
    - mode: 444
    - require:
      - pkg: ca_certificates

Example error:

[root@xxxxxxxxxx tmp]# salt 'xxxxxxxx' http.query 'https://one-of-our-internal-servers'
xxxxxxxx:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/salt/minion.py", line 1332, in _thread_return
        return_data = executor.execute()
      File "/usr/lib/python2.6/site-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/usr/lib/python2.6/site-packages/salt/modules/http.py", line 30, in query
        return salt.utils.http.query(url=url, opts=__opts__, **kwargs)
      File "/usr/lib/python2.6/site-packages/salt/utils/http.py", line 484, in query
        **req_kwargs
      File "/usr/lib64/python2.6/site-packages/tornado/httpclient.py", line 102, in fetch
        self._async_client.fetch, request, **kwargs))
      File "/usr/lib64/python2.6/site-packages/tornado/ioloop.py", line 444, in run_sync
        return future_cell[0].result()
      File "/usr/lib64/python2.6/site-packages/tornado/concurrent.py", line 214, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
    SSLError: [Errno 1] _ssl.c:490: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

### Versions Report
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.2.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Nov 21 2013, 10:50:32)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: redhat 6.6 Santiago
        machine: x86_64
        release: 2.6.32-504.16.2.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.6 Santiago

**Comment by gtmanfred** [comment]
@techhat have you seen this before?

I believe I have in the past where python is not picking up the /etc/ ca-certificates

Thanks,
Daniel

**Comment by RobotLimeLtd** [comment]
I have seen this before; and I thought I'd solved it by ensuring ca-certificates is installed, and the relevant files (see above) updated to include internal CAs.

Is there a way to disable SSL cert verification for file.managed?  At least temporarily, while I try and work out why python isn't picking up the CAs?

**Comment by techhat** [comment]
Looking at the code so far, I'm not seeing a way to turn off SSL certs through `file.managed` itself, but you should be able to set `verify_ssl` to `False` in the appropriate config file (`master` or `minion`). But before doing that, try setting `backend` to `requests` in said config file and see if that helps.

**Comment by RobotLimeLtd** [comment]
Unfortunately, there's no setting to disable SSL certificate checks for either the master or the minion(s).

Interestingly, although it's not documented, you can disable ssl verification in http.query as follows:

salt 'myserver' http.query https://www.foo.com verify_ssl=False

But I tried (optimistically) passing this in as kwargs into file.managed without success.

**Comment by RobotLimeLtd** [comment]
It seems the error occurs when the HTTPS server you're accessing is sitting behind a proxy.  My source server is sitting behind Nginx, in which we have a default VHost that uses an internally signed SSL certificate.  

If I remove that, then it goes to the first VHost in the list (not necessarily the one that matches the hostname.  I have each SSL VHost in a separate config file... it just goes to the first file as sorted alphanumerically.

**Comment by dfidler** [comment]
Encountered this today when a customer using salt 3002.4 was trying the following and got a certificate error: 

```
/root/iamafile.txt:
  file.managed:
    - source: https://iamaurl/iamafile.txt
```
I didn't gather the details on their certificate or any proxies.  But he was able to download the file manually using curl --no-check-certificate` easily enough (it could have been a proxy issue, but I don't think so).

Anyway, this should be converted into an enhancement request (rather than a bug) to include a `verify_ssl: True/False` param into any module that has a "source(s)" parameter (file, pkg, cmd, cp, etc)
