### ISSUE TITLE
State execution silently ignore error in module

### ISSUE THREAD

**Issue by andreyshestakov** [saltstack/salt#42273]
In case when module throws exception (no valid dict in return) state continue execution.

For instance, my sls:

heat_client_roles:
  keystone.role_present:
  - names:
    - heat_stack_owner
    - heat_stack_user
  - connection_user: {{ server.identity.user }}
  - connection_password: {{ server.identity.password }}
  - connection_tenant: {{ server.identity.tenant }}
  - connection_auth_url: 'http://{{ server.identity.host }}:{{ server.identity.port }}/v2.0/'
  - require:
    - pkg: heat_server_packages

Log output:
2017-07-11 12:17:13,164 [salt.state       ][INFO    ][21830] Running state [heat_stack_user] at time 12:17:13.164754
2017-07-11 12:17:13,165 [salt.state       ][INFO    ][21830] Executing state keystone.role_present for heat_stack_user
2017-07-11 12:17:14,797 [salt.state       ][ERROR   ][21830] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1750, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1705, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/states/keystone.py", line 497, in role_present
    **connection_args)
  File "/usr/lib/python2.7/dist-packages/salt/modules/keystone.py", line 468, in role_get
    kstone = auth(profile, **connection_args)
  File "/usr/lib/python2.7/dist-packages/salt/modules/keystone.py", line 163, in auth
    if float(api_version(profile=profile, **connection_args).strip('v')) >= 3:
AttributeError: 'NoneType' object has no attribute 'strip'
2017-07-11 12:17:14,797 [salt.state       ][INFO    ][21830] Completed state [heat_stack_user] at time 12:17:14.797815 duration_in_ms=1633.06

state.apply finishes without failures.

Salt Version:
           Salt: 2016.11.6
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.3.7
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-83-generic
         system: Linux
        version: Ubuntu 16.04 xenial

How this kind of error should be handled?
Should module garantee valid dict in return or should be errors catched on state or executor level?

**Comment by gtmanfred** [comment]
We should have a config option that allows users to specify which version of keystone to use.

And yes there should be an error returned in the output of the state, can you provide the state return for when you run `state.apply`?

Also, which cloud provider are you using? or which version of openstack that doesn't support api_version?

**Comment by andreyshestakov** [comment]
This issue not depends on keystone or openstack.
Exactly in my case was networking issue related only to my env. (HTTP server returned 599 error in response).

I have only this output from console:
```
    keystone_|-keystone_identity_roles_|-heat_stack_owner_|-role_present:
        ----------
        __id__:
            keystone_identity_roles
        __run_num__:
            51
        changes:
            ----------
            Role:
                Created
        comment:
            Role "heat_stack_owner" has been added
        duration:
            97.193 ms
        name:
            heat_stack_owner
        result:
            True
        start_time:
            14:02:01.999893
    keystone_|-keystone_identity_roles_|-heat_stack_user_|-role_present:
        ----------
        __id__:
            keystone_identity_roles
        __run_num__:
            48
        changes:
            ----------
        comment:
            An exception occurred in this state: Traceback (most recent call last):
              File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1750, in call
                **cdata['kwargs'])
              File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1705, in wrapper
                return f(*args, **kwargs)
              File "/usr/lib/python2.7/dist-packages/salt/states/keystone.py", line 497, in role_present
                **connection_args)
              File "/usr/lib/python2.7/dist-packages/salt/modules/keystone.py", line 468, in role_get
                kstone = auth(profile, **connection_args)
              File "/usr/lib/python2.7/dist-packages/salt/modules/keystone.py", line 163, in auth
                if float(api_version(profile=profile, **connection_args).strip('v')) >= 3:
            AttributeError: 'NoneType' object has no attribute 'strip'
        duration:
            2427.201 ms
        name:
            heat_stack_user
        result:
            False
        start_time:
            14:01:54.707543
```

I think module should handle this kind of errors, but this issue is possible to reproduce by breaking python syntax inside of method.

**Comment by gtmanfred** [comment]
Ahh, ok i misunderstood what you were reporting.

Yes, we should catch this and report back an usable error message.

Thanks,
Daniel
