### ISSUE TITLE
new installs of saltstack fail after first run - 2016.11.6

### ISSUE THREAD

**Issue by larsbijl** [saltstack/salt#42293]
### Description of Issue/Question

salt-call test.ping
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 374, in salt_call
    import salt.cli.call
  File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 9, in <module>
    import salt.cli.caller
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 19, in <module>
    import salt.minion
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 90, in <module>
    import salt.pillar
  File "/usr/lib/python2.7/site-packages/salt/pillar/__init__.py", line 16, in <module>
    import salt.fileclient
  File "/usr/lib/python2.7/site-packages/salt/fileclient.py", line 15, in <module>
    from tornado.httputil import parse_response_start_line, HTTPInputError
  File "/usr/lib64/python2.7/site-packages/tornado/httputil.py", line 36, in <module>
    from tornado.util import ObjectDict, PY3
ImportError: cannot import name PY3

seems like something has changed in tornado and the util model doesn't ship with PY3 anymore.

### Versions Report
salt-call 2016.11.6 (Carbon)

**Comment by larsbijl** [comment]
seems the issue is tornado==4.5.1
