### ISSUE TITLE
Jinja issue parsing a timestamp

### ISSUE THREAD

**Issue by rmarchei** [saltstack/salt#42355]
### Description of Issue/Question
I have a custom grain `created_on` that reads a timestamp from a file. This timestamp is then used in a jinja template and converted using strftime. If timestamp is >= 1500370001, `{{ grains.get('created_on')|strftime('%c') }}` crashes with:

```
Rendering SLS 'base:common.motd' failed: Jinja error: year=1 is before 1900; the datetime strftime() methods require year >= 1900
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 368, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 16, in top-level template code
  File "/usr/lib/python2.7/dist-packages/salt/utils/__init__.py", line 2292, in date_format
    return date_cast(date).strftime(format)
ValueError: year=1 is before 1900; the datetime strftime() methods require year >= 1900
```
### Setup
custom grain "created_on" similar to:
```
import time

def main():
  t = int(time.time())
  try:
    f = open("/etc/.created_on", "r")
    t = int(f.readline().rstrip())
  finally:
    return { 'created_on': '{0}'.format(t) }

if __name__ == '__main__':
  print main()
```

### Versions Report
```
# salt-call --versions-report
Salt Version:
           Salt: 2016.11.6

Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.3.7
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-81-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by Ch3LL** [comment]
@rmarchei i'm having a hard time replicating this.

Here is that .created_on file:

```
[root@968679f3a666 /]# cat /etc/.created_on
1500370001
```

Is that what your file looks like as well?

**Comment by rmarchei** [comment]
Yes @Ch3LL, I have a file like that and I can reproduce it with something like:

```
# test/time.sls
test strftime:
  test.show_notification:
    - text: {{ grains.get('created_on')|strftime('%c') }}
```

I've just noticed that this way it doesn't completely crash but it displays and incorrect date:
```
root@local:~# cat /etc/.created_on
1500392618
root@local:~# salt-call state.apply test.time
local:
----------
          ID: test strftime
    Function: test.show_notification
      Result: True
     Comment: Sat Jul 18 15:00:39 2618
     Started: 11:33:11.494303
    Duration: 0.316 ms
     Changes:
```

and I can't reproduce it if I do something like `{{ 1500392618|strftime('%c') }}`, so I may be doing something wrong in the custom grain

**Comment by Ch3LL** [comment]
@rmarchei does this last update resolve the issue for you to use the additional int/strftime filters?

**Comment by rmarchei** [comment]
yes @Ch3LL, with the additional filter I haven't experienced the issue anymore, so I'll go ahead and close the issue.

Thank you!
