### ISSUE TITLE
Minion unresponsive after trying to failover

### ISSUE THREAD

**Issue by tsaridas** [saltstack/salt#42371]
### Description of Issue/Question

While minion is up and running the last message in the logs is the below:

```
2017-07-06 22:16:17,058 [salt.minion ][WARNING ][7738] Master ip address changed from 192.168.123.6 to 192.168.123.7
2017-07-06 22:16:22,064 [salt.minion ][INFO    ][7738] Master saltsyndic04 could not be reached, trying next master (if any)
2017-07-06 22:16:22,064 [salt.minion ][WARNING ][7738] Master ip address changed from 192.168.123.7 to 10.192.123.148
2017-07-06 22:16:27,071 [salt.minion ][INFO    ][7738] Master saltsyndic03 could not be reached, trying next master (if any)
2017-07-06 22:16:42,072 [salt.minion ][WARNING ][7738] Master ip address changed from 10.192.123.148 to 10.192.122.184
2017-07-06 22:16:47,077 [salt.minion ][INFO    ][7738] Master saltsyndic02 could not be reached, trying next master (if any)
2017-07-06 22:16:47,078 [salt.minion ][WARNING ][7738] Master ip address changed from 10.192.122.184 to 192.168.123.4
2017-07-06 22:16:52,083 [salt.minion ][INFO    ][7738] Master saltsyndic05 could not be reached, trying next master (if any)
2017-07-06 22:16:52,083 [salt.minion ][WARNING ][7738] Master ip address changed from 192.168.123.4 to 10.195.108.44
2017-07-06 22:16:57,089 [salt.minion ][INFO    ][7738] Master saltsyndic01 could not be reached, trying next master (if any)
2017-07-06 22:16:57,089 [salt.minion ][WARNING ][7738] Master ip address changed from 10.195.108.44 to 192.168.123.6
2017-07-06 22:17:02,094 [salt.minion ][INFO    ][7738] Master saltsyndic06 could not be reached, trying next master (if any)
2017-07-06 22:17:02,094 [salt.minion ][WARNING ][7738] Master ip address changed from 192.168.123.6 to 192.168.123.7
2017-07-06 22:17:07,100 [salt.minion ][INFO    ][7738] Master saltsyndic04 could not be reached, trying next master (if any)
2017-07-06 22:17:07,100 [salt.minion ][WARNING ][7738] Master ip address changed from 192.168.123.7 to 10.192.123.148
2017-07-06 22:17:12,106 [salt.minion ][INFO    ][7738] Master saltsyndic03 could not be reached, trying next master (if any)
2017-07-06 22:17:27,107 [salt.minion ][WARNING ][7738] Master ip address changed from 10.192.123.148 to 10.192.122.184
2017-07-06 22:17:32,116 [salt.minion ][INFO    ][7738] Master saltsyndic02 could not be reached, trying next master (if any)
2017-07-06 22:17:32,116 [salt.minion [WARNING ][7738] Master ip address changed from 10.192.122.184 to 192.168.123.4
2017-07-06 22:17:37,124 [salt.minion ][INFO    ][7738] Master saltsyndic05 could not be reached, trying next master (if any)
2017-07-06 22:17:37,125 [salt.minion [WARNING ][7738] Master ip address changed from 192.168.123.4 to 10.195.108.44
2017-07-06 22:17:42,132 [salt.minion ][INFO    ][7738] Master saltsyndic01 could not be reached, trying next master (if any)
2017-07-06 22:17:42,133 [salt.minion ][WARNING ][7738] Master ip address changed from 10.195.108.44 to 192.168.123.6
2017-07-06 22:17:47,141 [salt.minion ][INFO    ][7738] Master saltsyndic06 could not be reached, trying next master (if any)
2017-07-06 22:17:47,141 [salt.minion ][WARNING ][7738] Master ip address changed from 192.168.123.6 to 192.168.123.7
2017-07-06 22:17:52,147 [salt.minion ][INFO    ][7738] Master saltsyndic04 could not be reached, trying next master (if any)
2017-07-06 22:17:52,147 [salt.minion ][WARNING ][7738] Master ip address changed from 192.168.123.7 to 10.192.123.148
2017-07-06 22:17:57,153 [salt.minion ][INFO    ][7738] Master saltsyndic03 could not be reached, trying next master (if any)
2017-07-06 22:18:12,154 [salt.minion ][WARNING ][7738] Master ip address changed from 10.192.123.148 to 10.192.122.184
2017-07-06 22:18:17,159 [salt.minion ][INFO    ][7738] Master saltsyndic02 could not be reached, trying next master (if any)
2017-07-06 22:18:17,160 [salt.minion ][WARNING ][7738] Master ip address changed from 10.192.122.184 to 192.168.123.4
2017-07-06 22:18:22,165 [salt.minion ][INFO    ][7738] Master saltsyndic05 could not be reached, trying next master (if any)
2017-07-06 22:18:22,165 [salt.minion ][WARNING ][7738] Master ip address changed from 192.168.123.4 to 10.195.108.44
2017-07-06 22:18:27,171 [salt.minion ][INFO    ][7738] Master saltsyndic01 could not be reached, trying next master (if any)
2017-07-06 22:18:27,172 [salt.minion ][WARNING ][7738] Master ip address changed from 10.195.108.44 to 192.168.123.6
2017-07-06 22:18:32,177 [salt.minion ][INFO    ][7738] Master saltsyndic06 could not be reached, trying next master (if any)
2017-07-06 22:18:32,178 [salt.minion ][WARNING ][7738] Master ip address changed from 192.168.123.6 to 192.168.123.7
2017-07-06 22:18:32,180 [tornado.application][ERROR   ][7738] Exception in callback <functools.partial object at 0x1162f70>
Traceback (most recent call last):
  File "/opt/salt/lib64/python2.6/site-packages/tornado/ioloop.py", line 591, in _run_callback
    ret = callback()
  File "/opt/salt/lib64/python2.6/site-packages/tornado/stack_context.py", line 274, in null_wrapper
    return fn(*args, **kwargs)
  File "/opt/salt/lib64/python2.6/site-packages/tornado/ioloop.py", line 597, in <lambda>
    self.add_future(ret, lambda f: f.result())
  File "/opt/salt/lib64/python2.6/site-packages/tornado/concurrent.py", line 214, in result 
    raise_exc_info(self._exc_info)
  File "/opt/salt/lib64/python2.6/site-packages/tornado/gen.py", line 876, in run 
    yielded = self.gen.throw(*exc_info)
  File "/opt/salt/lib/python2.6/site-packages/salt/minion.py", line 794, in handle_event
    yield [minion.handle_event(package) for minion in self.minions]
  File "/opt/salt/lib64/python2.6/site-packages/tornado/gen.py", line 870, in run 
    value = future.result()
  File "/opt/salt/lib64/python2.6/site-packages/tornado/concurrent.py", line 214, in result 
    raise_exc_info(self._exc_info)
  File "/opt/salt/lib64/python2.6/site-packages/tornado/gen.py", line 656, in callback
    result_list.append(f.result())
  File "/opt/salt/lib64/python2.6/site-packages/tornado/concurrent.py", line 214, in result 
    raise_exc_info(self._exc_info)
  File "/opt/salt/lib64/python2.6/site-packages/tornado/gen.py", line 876, in run 
    yielded = self.gen.throw(*exc_info)
  File "/opt/salt/lib/python2.6/site-packages/salt/minion.py", line 1991, in handle_event
    failback=tag.startswith(master_event(type='failback')))
  File "/opt/salt/lib64/python2.6/site-packages/tornado/gen.py", line 870, in run 
    value = future.result()
  File "/opt/salt/lib64/python2.6/site-packages/tornado/concurrent.py", line 214, in result 
    raise_exc_info(self._exc_info)
  File "/opt/salt/lib64/python2.6/site-packages/tornado/gen.py", line 876, in run 
    yielded = self.gen.throw(*exc_info)
  File "/opt/salt/lib/python2.6/site-packages/salt/minion.py", line 563, in eval_master
    pub_channel = salt.transport.client.AsyncPubChannel.factory(opts, **factory_kwargs)
  File "/opt/salt/lib/python2.6/site-packages/salt/transport/client.py", line 162, in factory
    return salt.transport.zeromq.AsyncZeroMQPubChannel(opts, **kwargs)
  File "/opt/salt/lib/python2.6/site-packages/salt/transport/zeromq.py", line 298, in __init__
    self.auth = salt.crypt.AsyncAuth(self.opts, io_loop=self.io_loop)
  File "/opt/salt/lib/python2.6/site-packages/salt/crypt.py", line 346, in __new__
    return loop_instance_map[key]
  File "/usr/lib64/python2.6/weakref.py", line 54, in __getitem__
    o = self.data[key]()
KeyError: ('/etc/salt/pki/minion', 'minion01', 'tcp://192.168.123.7:4506')
```

### Setup
master-multisyndic-minion

### Steps to Reproduce Issue
Cannot reproduce.

### Versions Report
2016.11.5

@DmitryKuzmenko any ideas ?

**Comment by DmitryKuzmenko** [comment]
I've fixed that `KeyError` issue in #42387.
If those `could not be reached` messages are expected (I mean that syndics are really down) than we're done here.
Please let me know if not.

**Comment by tsaridas** [comment]
Looks great,

Thank you very much for your fast reply & fix.

**Comment by DmitryKuzmenko** [comment]
@tsaridas no problem. It was easy fix.
