### ISSUE TITLE
[2017.7.0] salt-run mange.versions throws exception if minion is offline or unresponsive

### ISSUE THREAD

**Issue by tyhunt99** [saltstack/salt#42374]
### Description of Issue/Question
When you try to run a salt-run manage.versions with minions which are offline or unresponsive (i.e. test.ping returns ``` Minion did not return. [Not connected]```) then an exception is thrown.

### Setup
Simply having any non responsive minions and then running salt-run manage.versions will produce this error.

### Steps to Reproduce Issue
The exception:
```
Exception occurred in runner manage.versions: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/salt/client/mixins.py", line 392, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/salt/runners/manage.py", line 668, in versions
    minion_version = salt.version.SaltStackVersion.parse(minions[minion])
  File "/usr/local/lib/python2.7/dist-packages/salt/version.py", line 263, in parse
    if version_string.lower() in cls.LNAMES:
AttributeError: 'bool' object has no attribute 'lower'
```

### Versions Report
```
Salt Version:
           Salt: 2017.7.0
 
Dependency Versions:
           cffi: 1.5.0
       cherrypy: 3.2.2
       dateutil: 2.6.0
      docker-py: 1.7.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: 0.23.4
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.23.1
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: 0.3.6
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.1.6
 
System Versions:
           dist: Ubuntu 14.04 trusty
         locale: UTF-8
        machine: x86_64
        release: 3.19.0-78-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by tyhunt99** [comment]
I was able to do a simple fix:
```
for minion in minions:
        if not minions[minion]:           <=================
            continue                      <=================
        minion_version = salt.version.SaltStackVersion.parse(minions[minion])
        ver_diff = cmp(minion_version, master_version)

        if ver_diff not in version_status:
            version_status[ver_diff] = {}
        version_status[ver_diff][minion] = minion_version.string
```
By adding the lines indicated it will simply ignore the False being returned from those minions. Although I am not sure if this is desired behavior.

**Comment by garethgreenaway** [comment]
@tyhunt99 We'd definitely still want those minions to be reported back on, I submitted a PR yesterday with some fixes and gave it a quick test.  Please take a look and see it solves the issue for you as well.
