### ISSUE TITLE
cpan.install fails for missing /build dir

### ISSUE THREAD

**Issue by te-af-github** [saltstack/salt#42402]
### Description of Issue/Question

Trying to install a cpan Module on a fresh Debian Jessie machine:

saltstack:~# salt '<host>' cpan.install Crypt::RC5
<host>:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1480, in _thread_return
        return_data = executor.execute()
      File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/cpan.py", line 49, in install
        old_info = show(module)
      File "/usr/lib/python2.7/dist-packages/salt/modules/cpan.py", line 206, in show
        builds = os.listdir(build_dir)
    OSError: [Errno 2] No such file or directory: '/build'

cpan Crypt::RC5 works without issues.

### Setup

Fresh Debian 8.8 Jessie

### Steps to Reproduce Issue

Execute:

salt '<minion-host>' cpan.install Crypt::RC5

### Versions Report

Both Minion and Master:

Salt Version:
           Salt: 2016.11.6

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.0
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.8
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.8

**Comment by te-af-github** [comment]
Found the issue. It is similar to the much beloved and various reports on $HOME not set: ie [https://github.com/saltstack/salt/issues/19869](https://github.com/saltstack/salt/issues/19869)

Installing File::HomeDIr is a work around, but seriously: is this stuff supposed to be production-ready?
