### ISSUE TITLE
[2017.7] highstate returner error

### ISSUE THREAD

**Issue by tobstone** [saltstack/salt#42418]
### Description of Issue/Question
Using the new highstate_returner produces a lot of errors
```
ERROR: The ret`urn failed for job 20170720114400748039 'str' object has no attribute 'get'

ERROR: Traceback (most recent call last):\n File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1577, in _thread_return\n minion_instance.returners[returner_str](ret)\n File "/usr/lib/python2.7/dist-packages/salt/returners/highstate_return.py", line 478, in returner\n report, failed = _generate_report(ret, setup)\n File "/usr/lib/python2.7/dist-packages/salt/returners/highstate_return.py", line 335, in _generate_report\n key=lambda s: s[1].get('__run_num__', 0)\n File "/usr/lib/python2.7/dist-packages/salt/returners/highstate_return.py", line 335, in <lambda>\n key=lambda s: s[1].get('__run_num__', 0)\nAttributeError: 'str' object has no attribute 'get'
```
### Setup

minion.conf:
```
return:
  - highstate

highstate:
  report_failures: True
  report_changes: True
  report_everything: False
  failure_function: pillar.items
  success_function: pillar.items
  report_format: html
  report_delivery: smtp
  smtp_success_subject: 'success minion {id} on host {host}'
  smtp_failure_subject: 'failure minion {id} on host {host}'
  smtp_server: localhost
  smtp_recipients: foo@dwbn.org
  smtp_sender: foobar@dwbn.org
```

### Steps to Reproduce Issue
e.g.
salt '*backup*' state.sls postfix-gmail

event data:

```json
20170720114629477127    {
    "_stamp": "2017-07-20T09:46:29.477565",
    "minions": [
        "live-backup-01-esxi01-munich.dwbn.internal"
    ]
}
salt/job/20170720114629477127/new       {
    "_stamp": "2017-07-20T09:46:29.478593",
    "arg": [
        "postfix-gmail"
    ],
    "fun": "state.sls",
    "jid": "20170720114629477127",
    "minions": [
        "live-backup-01-esxi01-munich.dwbn.internal"
    ],
    "tgt": "*backup*",
    "tgt_type": "glob",
    "user": "sudo_tobiassteinhoff"
}
minion/refresh/live-backup-01-esxi01-munich.dwbn.internal       {
    "Minion data cache refresh": "live-backup-01-esxi01-munich.dwbn.internal",
    "_stamp": "2017-07-20T09:46:31.993889"
}
salt/job/20170720114629477127/ret/live-backup-01-esxi01-munich.dwbn.internal    {
    "_stamp": "2017-07-20T09:46:33.804361",
    "cmd": "_return",
    "fun": "state.sls",
    "fun_args": [
        "postfix-gmail"
    ],
    "id": "live-backup-01-esxi01-munich.dwbn.internal",
    "jid": "20170720114629477127",
    "out": "highstate",
    "retcode": 0,
    "return": {
        "cmd_|-/etc/postfix/sasl_passwd_|-postmap /etc/postfix/sasl_passwd_|-wait": {
            "__id__": "/etc/postfix/sasl_passwd",
            "__run_num__": 14,
            "__sls__": "postfix-gmail",
            "changes": {},
            "comment": "",
            "duration": 1.42,
            "name": "postmap /etc/postfix/sasl_passwd",
            "result": true,
            "start_time": "11:46:33.793948"
        },
        "cmd_|-run-newaliases_|-newaliases_|-wait": {
            "__id__": "run-newaliases",
            "__run_num__": 10,
            "__sls__": "postfix-gmail",
            "changes": {},
            "comment": "",
            "duration": 0.817,
            "name": "newaliases",
            "result": true,
            "start_time": "11:46:33.699367"
        },
        "cmd_|-run-postmap_sender_canonical_|-postmap hash:/etc/postfix/sender_canonical_|-wait": {
            "__id__": "run-postmap_sender_canonical",
            "__run_num__": 12,
            "__sls__": "postfix-gmail",
            "changes": {},
            "comment": "",
            "duration": 1.415,
            "name": "postmap hash:/etc/postfix/sender_canonical",
            "result": true,
            "start_time": "11:46:33.788056"
        },
        "file_|-/etc/aliases_|-/etc/aliases_|-managed": {
            "__id__": "/etc/aliases",
            "__run_num__": 9,
            "__sls__": "postfix-gmail",
            "changes": {},
            "comment": "File /etc/aliases is in the correct state",
            "duration": 84.602,
            "name": "/etc/aliases",
            "pchanges": {},
            "result": true,
            "start_time": "11:46:33.613344"
        },
        "file_|-/etc/postfix/sasl_passwd_|-/etc/postfix/sasl_passwd_|-managed": {
            "__id__": "/etc/postfix/sasl_passwd",
            "__run_num__": 13,
            "__sls__": "postfix-gmail",
            "changes": {},
            "comment": "File /etc/postfix/sasl_passwd is in the correct state",
            "duration": 2.997,
            "name": "/etc/postfix/sasl_passwd",
            "pchanges": {},
            "result": true,
            "start_time": "11:46:33.789933"
        },
        "file_|-/etc/postfix/sender_canonical_|-/etc/postfix/sender_canonical_|-managed": {
            "__id__": "/etc/postfix/sender_canonical",
            "__run_num__": 11,
            "__sls__": "postfix-gmail",
            "changes": {},
            "comment": "File /etc/postfix/sender_canonical is in the correct state",
            "duration": 86.251,
            "name": "/etc/postfix/sender_canonical",
            "pchanges": {},
            "result": true,
            "start_time": "11:46:33.700549"
        },
        "file_|-main.cf-cacert_|-/etc/postfix/cacert.pem_|-copy": {
            "__id__": "main.cf-cacert",
            "__run_num__": 5,
            "__sls__": "postfix-gmail",
            "changes": {},
            "comment": "The target file \"/etc/postfix/cacert.pem\" exists and will not be overwritten",
            "duration": 1.671,
            "name": "/etc/postfix/cacert.pem",
            "result": true,
            "start_time": "11:46:33.573543"
        },
        "file_|-main.cf-relayhost_|-/etc/postfix/main.cf_|-replace": {
            "__id__": "main.cf-relayhost",
            "__run_num__": 7,
            "__sls__": "postfix-gmail",
            "changes": {},
            "comment": "No changes needed to be made",
            "duration": 3.663,
            "name": "/etc/postfix/main.cf",
            "pchanges": {},
            "result": true,
            "start_time": "11:46:33.580732"
        },
        "file_|-main.cf-sasl_|-/etc/postfix/main.cf_|-append": {
            "__id__": "main.cf-sasl",
            "__run_num__": 6,
            "__sls__": "postfix-gmail",
            "changes": {},
            "comment": "File /etc/postfix/main.cf is in correct state",
            "duration": 4.709,
            "name": "/etc/postfix/main.cf",
            "pchanges": {},
            "result": true,
            "start_time": "11:46:33.575659"
        },
        "pkg_|-postfix_|-ca-certificates_|-installed": {
            "__id__": "postfix",
            "__run_num__": 3,
            "__sls__": "postfix-gmail",
            "changes": {},
            "comment": "Package ca-certificates is already installed",
            "duration": 6.56,
            "name": "ca-certificates",
            "result": true,
            "start_time": "11:46:33.556175"
        },
        "pkg_|-postfix_|-libsasl2-2_|-installed": {
            "__id__": "postfix",
            "__run_num__": 2,
            "__sls__": "postfix-gmail",
            "changes": {},
            "comment": "Package libsasl2-2 is already installed",
            "duration": 6.583,
            "name": "libsasl2-2",
            "result": true,
            "start_time": "11:46:33.549321"
        },
        "pkg_|-postfix_|-libsasl2-modules_|-installed": {
            "__id__": "postfix",
            "__run_num__": 4,
            "__sls__": "postfix-gmail",
            "changes": {},
            "comment": "Package libsasl2-modules is already installed",
            "duration": 6.444,
            "name": "libsasl2-modules",
            "result": true,
            "start_time": "11:46:33.562991"
        },
        "pkg_|-postfix_|-mailutils_|-installed": {
            "__id__": "postfix",
            "__run_num__": 1,
            "__sls__": "postfix-gmail",
            "changes": {},
            "comment": "Package mailutils is already installed",
            "duration": 6.694,
            "name": "mailutils",
            "result": true,
            "start_time": "11:46:33.542352"
        },
        "pkg_|-postfix_|-postfix_|-installed": {
            "__id__": "postfix",
            "__run_num__": 0,
            "__sls__": "postfix-gmail",
            "changes": {},
            "comment": "Package postfix is already installed",
            "duration": 624.647,
            "name": "postfix",
            "result": true,
            "start_time": "11:46:32.917352"
        },
        "service_|-postfix_|-postfix_|-running": {
            "__id__": "postfix",
            "__run_num__": 8,
            "__sls__": "postfix-gmail",
            "changes": {},
            "comment": "The service postfix is already running",
            "duration": 28.006,
            "name": "postfix",
            "result": true,
            "start_time": "11:46:33.584832"
        }
    },
    "success": true
}
```

### Versions Report
master and minion same version

```
Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: 1.10.0
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-83-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by gtmanfred** [comment]
@ilyakoganus  can you take a look at this?

Thanks,
Daniel
