### ISSUE TITLE
archive.extracted on Windows failed when dir not exist

### ISSUE THREAD

**Issue by bfilipek** [saltstack/salt#42421]
### Description of Issue/Question
When archive.extracted tries to extract zip archieve to not exist folder returns:
```
ID: test
    Function: archive.extracted
        Name: C:\Temp\
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "c:\salt\bin\lib\site-packages\salt\state.py", line 1837, in call
                  **cdata['kwargs'])
                File "c:\salt\bin\lib\site-packages\salt\loader.py", line 1794, in wrapper
                  return f(*args, **kwargs)
                File "c:\salt\bin\lib\site-packages\salt\states\archive.py", line 1224, in extracted
                  __salt__['file.makedirs'](name, user=user)
              TypeError: makedirs_() got an unexpected keyword argument 'user'
     Started: 04:47:21.391000
    Duration: 110.0 ms
     Changes:
```
Works in the previous release. Temp file should be create by archive.extracted function

### Setup
SLS file:
```
test:
  archive.extracted:
    - name: 'C:\Temp\'
    - if_missing: 'C:\Temp\test'
    - source: 'C:\test.zip'
    - trim_output: True
    - archive_format: zip
```
I also try with escaped backslash, but the same issue occured.

### Steps to Reproduce Issue
prepare simple zip archieve for example:
```
test/
├── dir
│   └── file3
├── file1
└── file2
```

### Versions Report
Salt Version:
           Salt: 2017.7.0
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-83-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by gtmanfred** [comment]
Can you make sure there are no `.pyc` files left behind from an older release, because the file.makedirs_ function in 2017.7.0 definitely takes a user argument.

https://github.com/saltstack/salt/blob/2017.7/salt/modules/file.py#L5096

Thanks,
Daniel

**Comment by bartuss7** [comment]
Hello Daniel,

I've tried to delete the `.pyc` files, with no effect (master and minion was restarted). 
I've also tried to install salt master on the new VM. The issue still occurs on "fresh" master.

**Comment by gtmanfred** [comment]
I have opened this PR, it should fix the issue. https://github.com/saltstack/salt/pull/42453

It looks like there was a `makedirs_` function in win_file, and it does not accept the user argument.

This will be fixed in 2017.7.2.  2017.7.1 is only a hot fix of 2017.7.0, so we are trying to keep it as minimal as possible.

Thanks,
Daniel

**Comment by konstest** [comment]
Hi, I also have this error:
```
[14:20:43][Step 4/4] ----------
[14:20:43][Step 4/4]           ID: Download BuildAgent into C:\BuildAgent
[14:20:43][Step 4/4]     Function: archive.extracted
[14:20:43][Step 4/4]         Name: C:\BuildAgent
[14:20:43][Step 4/4]       Result: False
[14:20:43][Step 4/4]      Comment: An exception occurred in this state: Traceback (most recent call last):
[14:20:43][Step 4/4]                 File "c:\salt\bin\lib\site-packages\salt\state.py", line 1837, in call
[14:20:43][Step 4/4]                   **cdata['kwargs'])
[14:20:43][Step 4/4]                 File "c:\salt\bin\lib\site-packages\salt\loader.py", line 1794, in wrapper
[14:20:43][Step 4/4]                   return f(*args, **kwargs)
[14:20:43][Step 4/4]                 File "c:\salt\bin\lib\site-packages\salt\states\archive.py", line 1224, in extracted
[14:20:43][Step 4/4]                   __salt__['file.makedirs'](name, user=user)
[14:20:43][Step 4/4]               TypeError: makedirs_() got an unexpected keyword argument 'user'
[14:20:43][Step 4/4]      Started: 07:20:35.189000
[14:20:43][Step 4/4]     Duration: 3672.0 ms
[14:20:43][Step 4/4]      Changes:   
```

**Comment by konstest** [comment]
Hello, maybe it will help someone.
I bypassed this error this way:
```
Download ZIP archive:
  file.managed:
    - name: 'C:\tmp\archive.zip'
    - source: 'http://any.url/archive.zip'
    - makedirs: True

Extract ZIP archive:
  module.run:
    - name: archive.unzip
    - zip_file: 'C:\tmp\archive.zip'
    - dest: 'C:\special\dir\'
    - require:
      - Download ZIP archive
```

**Comment by konstest** [comment]
Relates to #43741

**Comment by asymetrixs** [comment]
Dear All,

I got the same problem using file.symlink:

```
file.symlink:
  - name: 'C:\ProgramData\Microsoft\Windows\Start Menu\test\link.lnk'
  - target: '{{ salt['environ.get']('PROGRAMFILES') }}\test\app.exe'
  - makedirs: True
```
Returns
`TypeError: makedirs_() got an unexpected keyword argument 'user'`

Running salt 2017.7.4 on Windows 7
