### ISSUE TITLE
Broken ldap groups retrieval in salt.auth.ldap after upgrade to 2017.7

### ISSUE THREAD

**Issue by iavael** [saltstack/salt#42459]
### Description of Issue/Question
LDAP eauth stopped working for salt-api after upgrade to 2017.7
pepper-0.5 is used as a client

### Setup
Ldap-related settings
```
auth.ldap.server: ldap.example.com
auth.ldap.port: 389
auth.ldap.tls: False
auth.ldap.no_verify: True
auth.ldap.anonymous: False
auth.ldap.binddn: 'cn=root,o=company'
auth.ldap.bindpw: 'root'
auth.ldap.basedn: 'ou=users,o=company'
auth.ldap.filter: '(uid={{ username }})'
auth.ldap.freeipa: True
auth.ldap.group_basedn: 'ou=groups,o=company'
auth.ldap.group_filter: '(&(memberUid={{ username }})(objectClass=posixGroup))'
auth.ldap.accountattributename: 'memberUid'

external_auth:
  ldap:
    'admins%':
      - '.*'
      - '@jobs'
      - '@wheel'
      - '@runners'
```

### Steps to Reproduce Issue
API calls return 401 and there these strings in logs
```
2017-07-21 18:22:31,228 [salt.loaded.int.auth.ldap][DEBUG   ][28333] Running LDAP user dn search with filter:(uid=admin1), dn:ou=users,o=company, scope:2
2017-07-21 18:22:31,229 [salt.loaded.int.auth.ldap][DEBUG   ][28333] Attempting LDAP bind with user dn: cn=admin1,ou=users,o=company
2017-07-21 18:22:31,232 [salt.loaded.int.auth.ldap][DEBUG   ][28333] Successfully authenticated user dn via LDAP: cn=admin1,ou=users,o=company
2017-07-21 18:22:31,232 [salt.loaded.int.auth.ldap][DEBUG   ][28333] LDAP authentication successful
2017-07-21 18:22:31,288 [salt.utils.lazy  ][DEBUG   ][28337] Could not LazyLoad ldap.acl: 'ldap.acl' is not available.
2017-07-21 18:22:31,289 [salt.auth        ][WARNING ][28337] Authorization failure occurred.
2017-07-21 18:22:31,289 [salt.master      ][WARNING ][28337] Authentication failure of type "token" occurred.
```

### Versions Report
```
Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.24.6
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: 0.24.2
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 4.9.20-1.company.el7.centos.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

python-ldap package version is 2.4.15-2.el7.x86_64

**Comment by Ch3LL** [comment]
Looks like there was a lot of eath refactoring done for the 2017.7.0 release here: https://github.com/saltstack/salt/pull/40200

Can you add the following diff:

```
diff --git a/salt/auth/__init__.py b/salt/auth/__init__.py
index f90488e153..0f7318df7f 100644
--- a/salt/auth/__init__.py
+++ b/salt/auth/__init__.py
@@ -360,7 +360,7 @@ class LoadAuth(object):
 
         if load['eauth'] not in self.opts['external_auth']:
             # No matching module is allowed in config
-            log.warning('Authorization failure occurred.')
+            log.warning('Authorization failure occurred 1')
             return None
 
         name = self.load_name(load)  # The username we are attempting to auth with
@@ -394,7 +394,7 @@ class LoadAuth(object):
                 ('*' in eauth_config) |
                 group_auth_match | external_auth_in_db):
             # Auth successful, but no matching user found in config
-            log.warning('Authorization failure occurred.')
+            log.warning('Authorization failure occurred. 2')
             return None
 
         # We now have an authenticated session and it is time to determine
```

So we can figure out where its failing for you in the code. That warning message shows up twice in the same method so I need to know where in that method its failing. In spot 1 or 2. And paste the sanitized logs here again.

**Comment by iavael** [comment]
```
2017-07-21 21:52:30,465 [salt.utils.lazy  ][DEBUG   ][7905] Could not LazyLoad ldap.acl: 'ldap.acl' is not available.
2017-07-21 21:52:30,466 [salt.auth        ][WARNING ][7905] Authorization failure occurred. 2
2017-07-21 21:52:30,466 [salt.master      ][WARNING ][7905] Authentication failure of type "token" occurred.
```

**Comment by iavael** [comment]
self.get_groups(load) called in get_auth_list function returns None

**Comment by iavael** [comment]
Disabled exception catching and saw this in log
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/transport/zeromq.py", line 618, in handle_message
    ret, req_opts = yield self.payload_handler(payload)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 215, in wrapper
    result = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 894, in _handle_payload
    'clear': self._handle_clear}[key](load)
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 908, in _handle_clear
    return getattr(self.clear_funcs, load['cmd'])(load), {'fun': 'send_clear'}
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 1908, in publish
    auth_list = self.loadauth.get_auth_list(extra)
  File "/usr/lib/python2.7/site-packages/salt/auth/__init__.py", line 367, in get_auth_list
    groups = self.get_groups(load)  # The groups this user belongs to
  File "/usr/lib/python2.7/site-packages/salt/auth/__init__.py", line 174, in get_groups
    return self.auth[fstr](*fcall['args'], **fcall['kwargs'])
  File "/usr/lib/python2.7/site-packages/salt/auth/ldap.py", line 309, in groups
    bind = _bind(username, kwargs['password'],
KeyError: 'password'
```

**Comment by rickh563** [comment]
ZD-1713

**Comment by gtmanfred** [comment]
I am able to get this to work using using salt directly and using the `/run` api endpoint.

But using `/login`, and then using the token to authenticate doesn't work which is why salt-pepper would fail, which makes me believe that the token might not be getting saved on the master correctly.

```
[root@salt ~]# salt -a ldap \* test.ping -l info
username: dwall
password:
minion.gtmanfred.com:
    True
[root@salt ~]# curl -sSk https://localhost:8000/run \
>     -H 'Accept: application/x-yaml' \
>     -H 'Content-type: application/json' \
>     -d '[{
>         "client": "local",
>         "tgt": "*",
>         "fun": "test.ping",
>         "username": "dwall",
>         "password": "$pass",
>         "eauth": "ldap"
>     }]'
return:
- minion.gtmanfred.com: true
[root@salt ~]# curl -sSk https://localhost:8000/login \
>     -H 'Accept: application/x-yaml' \
>     -d username=dwall \
>     -d password=$pass \
>     -d eauth=ldap
return:
- eauth: ldap
  expire: 1504065313.691873
  perms: {}
  start: 1504022113.691872
  token: e43f58a45b3cf56933dfa1577db84332779e3f78
  user: dwall
[root@salt ~]# TOKEN=e43f58a45b3cf56933dfa1577db84332779e3f78 curl -sSk https://localhost:8000 \
>     -H 'Accept: application/x-yaml' \
>     -H "X-Auth-Token: $TOKEN"\
>     -d client=local \
>     -d tgt='*' \
>     -d fun=test.ping
<!DOCTYPE html PUBLIC
"-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>401 Unauthorized</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>401 Unauthorized</h2>
        <p>No permission -- see authorization schemes</p>
        <pre id="traceback"></pre>
    <div id="powered_by">
      <span>
        Powered by <a href="http://www.cherrypy.org">CherryPy 5.6.0</a>
      </span>
    </div>
    </body>
</html>
```


@whiteinge can you take a look at this when you get back from vacation?

Thanks,
Daniel

**Comment by gtmanfred** [comment]
@iavael can you tell me which previous version this worked on so that I can test it and we can mark it as a regression and get its priority bumped up?

Looking at 2016.11, I am getting the same problem.

```
[root@salt ~]# curl -sSk https://localhost:8000/login \
>     -H 'Accept: application/x-yaml' \
>     -d username=dwall \
>     -d password=braves12345 \
>     -d eauth=ldap
return:
- eauth: ldap
  expire: 1504065815.630228
  perms:
  - .*
  start: 1504022615.630227
  token: f27d1172ad5b18f7e6db5fcd3a3f92083718e8e1
  user: dwall
[root@salt ~]# TOKEN=f27d1172ad5b18f7e6db5fcd3a3f92083718e8e1 curl -sSk https://localhost:8000 \
>     -H 'Accept: application/x-yaml' \
>     -H "X-Auth-Token: $TOKEN"\
>     -d client=local \
>     -d tgt='*' \
>     -d fun=test.ping
<!DOCTYPE html PUBLIC
"-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>401 Unauthorized</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>401 Unauthorized</h2>
        <p>No permission -- see authorization schemes</p>
        <pre id="traceback"></pre>
    <div id="powered_by">
      <span>
        Powered by <a href="http://www.cherrypy.org">CherryPy 5.6.0</a>
      </span>
    </div>
    </body>
</html>
[root@salt ~]# salt-api --version
salt-api 2016.11.7 (Carbon)
```

Thanks,
Daniel

**Comment by iavael** [comment]
@gtmanfred our previous version was 2016.11.6

**Comment by gtmanfred** [comment]
Ok, i have replicated this working in 2016.11.6/7

And it is broken in 2017.7, so this is a regression and we will get it fixed.

Thanks!
Daniel

**Comment by UtahDave** [comment]
ZD 1723

**Comment by DmitryKuzmenko** [comment]
I've found the problem. I'll provide the fix tomorrow.
