### ISSUE TITLE
SSL handshake errors from file.managed for Atlassian.com

### ISSUE THREAD

**Issue by ketzacoatl** [saltstack/salt#42485]
### Description of Issue/Question

When I use `file.managed` to download release tarballs from `https://www.atlassian
.com/`, I see a confusing SSL handshake failure. Wget, curl, and my browser download those files fine. It looks like Atlassian is doing something that interferes with the `file.managed` retrieval. I've run tests on the latest release (installed with `pip install --upgrade` from 2015.5.11), as well as with 2015.5.11, and I see the same error.

### Setup

I am using masterless with `salt-call --local`, and ``state.low` to show the example:

```
# salt-call --local state.low '{"state": "file", "fun": "managed", "name": "/tmp/c.tgz", "source": "https://www.atlassian.com/software/crowd/downloads/binary/atlassian-crowd-2.8.4.tar.gz", "source_hash": "sha512=fe19baf221feada563a98f950677a84d5fad5b7b93ed1817448a24a239c4bf0a3d1d68fc81b45aa61cf225927aabc09d2e82d09ae584f532bca72bf015d50358"}'
```

### Steps to Reproduce Issue

```
# salt-call --local state.low '{"state": "file", "fun": "managed", "name": "/tmp/c.tgz", "source": "https://www.atlassian.com/software/crowd/downloads/binary/atlassian-crowd-2.8.4.tar.gz", "source_hash": "sha512=fe19baf221feada563a98f950677a84d5fad5b7b93ed1817448a24a239c4bf0a3d1d68fc81b45aa61cf225927aabc09d2e82d09ae584f532bca72bf015d50358"}'
[WARNING ] SSL Error on 8 ('54.192.119.36', 443): [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
[ERROR   ] Failed to cache https://www.atlassian.com/software/crowd/downloads/binary/atlassian-crowd-2.8.4.tar.gz: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
KeyError: '__id__'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/local/lib/python2.7/dist-packages/salt/scripts.py", line 391, in salt_call
    client.run()
  File "/usr/local/lib/python2.7/dist-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/local/lib/python2.7/dist-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/local/lib/python2.7/dist-packages/salt/cli/caller.py", line 204, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/salt/modules/state.py", line 312, in low
    ret = st_.call(data)
  File "/usr/local/lib/python2.7/dist-packages/salt/state.py", line 1892, in call
    ret['__id__'] = low['__id__']
KeyError: '__id__'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/local/lib/python2.7/dist-packages/salt/scripts.py", line 391, in salt_call
    client.run()
  File "/usr/local/lib/python2.7/dist-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/local/lib/python2.7/dist-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/local/lib/python2.7/dist-packages/salt/cli/caller.py", line 204, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/salt/modules/state.py", line 312, in low
    ret = st_.call(data)
  File "/usr/local/lib/python2.7/dist-packages/salt/state.py", line 1892, in call
    ret['__id__'] = low['__id__']
KeyError: '__id__'
```

Wget seems fine...

```
# wget https://www.atlassian.com/software/crowd/downloads/binary/atlassian-crowd-2.12.0.tar.gz
--2017-07-22 15:14:05--  https://www.atlassian.com/software/crowd/downloads/binary/atlassian-crowd-2.12.0.tar.gz
Resolving www.atlassian.com (www.atlassian.com)... 104.192.142.43, 104.192.142.45, 104.192.142.44
Connecting to www.atlassian.com (www.atlassian.com)|104.192.142.43|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://my.atlassian.com/software/crowd/downloads/binary/atlassian-crowd-2.12.0.tar.gz [following]
--2017-07-22 15:14:05--  https://my.atlassian.com/software/crowd/downloads/binary/atlassian-crowd-2.12.0.tar.gz
Resolving my.atlassian.com (my.atlassian.com)... 52.206.107.146, 52.5.227.119
Connecting to my.atlassian.com (my.atlassian.com)|52.206.107.146|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://downloads.atlassian.com/software/crowd/downloads/atlassian-crowd-2.12.0.tar.gz [following]
--2017-07-22 15:14:05--  https://downloads.atlassian.com/software/crowd/downloads/atlassian-crowd-2.12.0.tar.gz
Resolving downloads.atlassian.com (downloads.atlassian.com)... 54.192.119.229, 54.192.119.144, 54.192.119.133, ...
Connecting to downloads.atlassian.com (downloads.atlassian.com)|54.192.119.229|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 179513702 (171M) [application/x-gzip]
Saving to: ‘atlassian-crowd-2.12.0.tar.gz.2’

100%[==================================================================================================================================>] 179,513,702 60.5MB/s   in 2.8s   

2017-07-22 15:14:08 (60.5 MB/s) - ‘atlassian-crowd-2.12.0.tar.gz.2’ saved [179513702/179513702]
```

and `curl` seems to think the SSL cert is fine:

```
# curl -v https://www.atlassian.com/software/crowd/downloads/binary/atlassian-crowd-2.12.0.tar.gz
* Hostname was NOT found in DNS cache
*   Trying 104.192.142.43...
* Connected to www.atlassian.com (104.192.142.43) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using AES128-GCM-SHA256
* Server certificate:
*        subject: C=AU; ST=New South Wales; L=Sydney; O=Atlassian Pty Ltd; CN=*.atlassian.com
*        start date: 2014-09-17 00:00:00 GMT
*        expire date: 2017-09-20 12:00:00 GMT
*        subjectAltName: www.atlassian.com matched
*        issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert SHA2 High Assurance Server CA
*        SSL certificate verify ok.
> GET /software/crowd/downloads/binary/atlassian-crowd-2.12.0.tar.gz HTTP/1.1
> User-Agent: curl/7.35.0
> Host: www.atlassian.com
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Date: Sat, 22 Jul 2017 15:14:42 GMT
< Content-Type: application/x-gzip
< Content-Length: 0
< Connection: keep-alive
* Server Apache-Coyote/1.1 is not blacklisted
< Server: Apache-Coyote/1.1
< Location: https://my.atlassian.com/software/crowd/downloads/binary/atlassian-crowd-2.12.0.tar.gz
< 
* Connection #0 to host www.atlassian.com left intact
```

It looks like there is a redirect there, maybe `file.managed` fails to work through?

### Versions Report

```
# salt-call --versions-report
Salt Version:
           Salt: 2017.7.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.0
      docker-py: 1.10.6
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.1.6
 
System Versions:
           dist: Ubuntu 14.04 trusty
         locale: UTF-8
        machine: x86_64
        release: 3.13.0-123-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by garethgreenaway** [comment]
@ketzacoatl I wonder if the fact that it's doing a 301 redirect that is causing the issue.  Can you try using the URL that the original request is redirected to in the call?

**Comment by ketzacoatl** [comment]
Hi @garethgreenaway, thanks for the review.

so yea, reviewing the wget / curl logs again, I see 3 URLs..

* www.atlassian.com
* my.atlassian.com
* downloads.atlassian.com

Using wget/curl, I can retrieve the archive with either www or my.atlassian.com, but not downloads.atlassian.com:

```
# curl https://downloads.atlassian.com/software/crowd/downloads/binary/atlassian-crowd-2.12.0.tar.gz
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /software/crowd/downloads/binary/atlassian-crowd-2.12.0.tar.gz was not found on this server.</p>
<hr>
<address>Apache/2.2.22 (Ubuntu) Server at downloads-origin.atlassian.com Port 80</address>
</body></html>
```

There's some funny session/cookie business when accessing thru my.atlassian.com or www.atlassian.com:

```
< HTTP/1.1 302 Found
< Date: Mon, 24 Jul 2017 20:18:20 GMT
< Location: https://downloads.atlassian.com/software/crowd/downloads/atlassian-crowd-2.12.0.tar.gz
* Server nginx is not blacklisted
< Server: nginx
< Set-Cookie: gsession-0="DIFXNSZx0ToRLohfz...="; Version=1; Max-Age=1800; E$
pires=Mon, 24-Jul-2017 20:48:20 GMT; Path=/; Secure; HttpOnly
```

I guess that cookie stuff might be an issue for `requests`?

```
# wget https://my.atlassian.com/software/crowd/downloads/binary/atlassian-crowd-2.12.0.tar.gz
--2017-07-24 20:03:56--  https://my.atlassian.com/software/crowd/downloads/binary/atlassian-crowd-2.12.0.tar.gz
Resolving my.atlassian.com (my.atlassian.com)... 52.206.107.146, 52.5.227.119
Connecting to my.atlassian.com (my.atlassian.com)|52.206.107.146|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://downloads.atlassian.com/software/crowd/downloads/atlassian-crowd-2.12.0.tar.gz [following]
--2017-07-24 20:03:57--  https://downloads.atlassian.com/software/crowd/downloads/atlassian-crowd-2.12.0.tar.gz
Resolving downloads.atlassian.com (downloads.atlassian.com)... 54.192.119.36, 54.192.119.45, 54.192.119.84, ...
Connecting to downloads.atlassian.com (downloads.atlassian.com)|54.192.119.36|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 179513702 (171M) [application/x-gzip]
Saving to: ‘atlassian-crowd-2.12.0.tar.gz’

100%[==================================================================================================================================>] 179,513,702 98.9MB/s   in 1.7s   
```


Either way, salt isn't happy though:

```
     Comment: Unable to manage file: Error reading https://my.atlassian.com/software/crowd/downloads/binary/atlassian-crowd-2.12.0.tar.gz: [Errno 1] _ssl.c:510: error:14077
410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
```

Here's curl:

```
# curl -v https://my.atlassian.com/software/crowd/downloads/binary/atlassian-crowd-2.12.0.tar.gz                                            
* Hostname was NOT found in DNS cache
*   Trying 52.5.227.119...
* Connected to my.atlassian.com (52.5.227.119) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using ECDHE-RSA-AES128-GCM-SHA256
* Server certificate:
*        subject: CN=*.atlassian.io
*        start date: 2017-05-02 00:00:00 GMT
*        expire date: 2018-06-02 12:00:00 GMT
*        subjectAltName: my.atlassian.com matched
*        issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*        SSL certificate verify ok.
> GET /software/crowd/downloads/binary/atlassian-crowd-2.12.0.tar.gz HTTP/1.1
> User-Agent: curl/7.35.0
> Host: my.atlassian.com
> Accept: */*
> 
< HTTP/1.1 302 Found
< Date: Mon, 24 Jul 2017 20:06:18 GMT
< Location: https://downloads.atlassian.com/software/crowd/downloads/atlassian-crowd-2.12.0.tar.gz
* Server nginx is not blacklisted
< Server: nginx
< Set-Cookie: gsession-0="DAdEV74Juduqm1...="; Version=1; Max-Age=1800
; Expires=Mon, 24-Jul-2017 20:36:18 GMT; Path=/; Secure; HttpOnly
< Set-Cookie: gsession-1=""; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/; Secure; HttpOnly
< Set-Cookie: gsession-2=""; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/; Secure; HttpOnly
< Set-Cookie: gsession-3=""; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/; Secure; HttpOnly
< Set-Cookie: gsession-4=""; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/; Secure; HttpOnly
< Strict-Transport-Security: max-age=31536000
< X-Frame-Options: SAMEORIGIN
< Content-Length: 0
< Connection: keep-alive
< 
* Connection #0 to host my.atlassian.com left intact
```

While all the URL redirect stuff is perplexing.. the error points at SSL, and looking closely at the output from curl, I see:

```
* Server certificate:
*        subject: CN=*.atlassian.io
*        start date: 2017-05-02 00:00:00 GMT
*        expire date: 2018-06-02 12:00:00 GMT
*        subjectAltName: my.atlassian.com matched
*        issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*        SSL certificate verify ok.
```

If the cookie/session handling is not an issue, perhaps `requests` (or similar, whoever does the SSL validation) is failing to use the `subjectAltName`, and instead sees the `subject` with `*.atlassian.io`?
