### ISSUE TITLE
Missing support for urllib3 version 1.22 (on FreeBSD 11)

### ISSUE THREAD

**Issue by JPT580** [saltstack/salt#42511]
### Description of Issue/Question
Salt crashes with a nice python trace after upgrading urllib3 from 1.21.1 to 1.22.
```
root@hostname:~ # service salt_minion start
Starting salt_minion.
Traceback (most recent call last):
  File "/usr/local/bin/salt-minion", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3037, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3021, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3050, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 657, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 670, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 855, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'urllib3<1.22,>=1.21.1' distribution was not found and is required by requests
/usr/local/etc/rc.d/salt_minion: WARNING: failed to start salt_minion

```
### Setup
FreeBSD 11 with py27-salt and urllib3 installed:
```
root@hostname:~ # pkg search py27-salt
py27-salt-2016.11.6_1          Distributed remote execution and configuration management system

root@hostname:~ # pkg search urllib3
py27-urllib3-1.22              HTTP library with thread-safe connection pooling, file post, and more
py36-urllib3-1.22              HTTP library with thread-safe connection pooling, file post, and more
```

Note: Using py27-salt from the official FreeBSD repository versus using py27-salt from the saltstack repository does not make a difference.

### Steps to Reproduce Issue
Set up a fresh FreeBSD 11 and install py27-salt.

### Versions Report

```
root@hostname:~ # salt --versions-report
Traceback (most recent call last):
  File "/usr/local/bin/salt", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3037, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3021, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3050, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 657, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 670, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 855, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'urllib3<1.22,>=1.21.1' distribution was not found and is required by requests
```

**Comment by gtmanfred** [comment]
@cedwards can you take a look at this?

Thanks,
Daniel

**Comment by cedwards** [comment]
I saw a patch go in just yesterday to upstream FreeBSD that should fix this. Can you check for a py27-salt pkg update?

**Comment by JPT580** [comment]
The latest update of FreeBSD seems to have fixed the issue for me.
Apparently the latest commit for py27-requests fixed it: http://www.freshports.org/www/py-requests/

I guess this issue can be closed now.

**Comment by gtmanfred** [comment]
Thanks all!
Daniel
