### ISSUE TITLE
Error when installing package from file under Arch Linux

### ISSUE THREAD

**Issue by xuhcc** [saltstack/salt#42519]
### Description of Issue/Question

Error occurs when installing package from file under Arch Linux:

```
An exception occurred in this state: Traceback (most recent call last):
                File "/var/tmp/.xuhcc_684964_salt/py2/salt/state.py", line 1837, in call
                  **cdata['kwargs'])
                File "/var/tmp/.xuhcc_684964_salt/py2/salt/loader.py", line 1794, in wrapper
                  return f(*args, **kwargs)
                File "/var/tmp/.xuhcc_684964_salt/py2/salt/states/pkg.py", line 1621, in installed
                  **kwargs)
                File "/var/tmp/.xuhcc_684964_salt/py2/salt/modules/pacman.py", line 582, in install
                  if wildcards:
              UnboundLocalError: local variable 'wildcards' referenced before assignment
```

### Setup

```yaml
my_package:
  pkg.installed:
    - sources:
      -  package: /path/to/package.tar.xz
```

### Versions Report

I'm using salt-ssh.

```
$ salt-ssh --versions-report
Salt Version:
           Salt: 2017.7.0
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: 8.9.1
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.26.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jul  2 2017, 22:24:59)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.2.2
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 4.11.9-1-ARCH
         system: Linux
        version: Not Installed
```

**Comment by gtmanfred** [comment]
This is fixed by #42522
