### ISSUE TITLE
salt-cloud TerminalException stack trace on low memory systems

### ISSUE THREAD

**Issue by boltronics** [saltstack/salt#42581]
### Description of Issue/Question

I tried to launch 12 instances via `salt-cloud` in parallel using a map file in the EC2 us-west-2 region, and ended up with the following error:
```
$ sudo salt-cloud -P -m my_map_file.map 
The following virtual machines are set to be created:
  < instance names removed >

Proceed? [N/y] y
... proceeding
[WARNING ] Failed to spawn the VT: [Errno 12] Cannot allocate memory
[ERROR   ] A wrong password has been issued while establishing ssh session.
[WARNING ] Failed to spawn the VT: [Errno 12] Cannot allocate memory
[WARNING ] Failed to spawn the VT: [Errno 12] Cannot allocate memory
[WARNING ] Failed to spawn the VT: [Errno 12] Cannot allocate memory
[ERROR   ] A wrong password has been issued while establishing ssh session.
[ERROR   ] Failed to upload file 'echo "put  /tmp/tmpsEg1Wz /tmp/.saltcloud-b16a5b2b-856d-4eec-b1de-88bb0d369b19/minion.pem" | sftp -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oIdentitiesOnly=yes -oKbdInteractiveAuthentication=no -oIdentityFile=/root/.ssh/id_rsa -oPort=22 root@172.31.29.250': Failed to spawn the VT. Error: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 1819, in _exec_ssh_cmd
    stream_stderr=kwargs.get('display_ssh_output', True)
  File "/usr/lib/python2.7/dist-packages/salt/utils/vt.py", line 219, in __init__
    'Failed to spawn the VT. Error: {0}'.format(err)
TerminalException: Failed to spawn the VT. Error: [Errno 12] Cannot allocate memory

[ERROR   ] A wrong password has been issued while establishing ssh session.
[WARNING ] Failed to spawn the VT: [Errno 12] Cannot allocate memory
[ERROR   ] A wrong password has been issued while establishing ssh session.
[ERROR   ] Caught Exception, terminating workers
TRACE: Unpack failed: error = 0
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 65, in _call
    ret = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 2320, in create_multiprocessing
    local_master=parallel_data['local_master']
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1287, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 2559, in create
    vm_['name'], vm_['profile'], 'ec2', vm_['driver']
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 2547, in cachedir_index_add
    index = msgpack.load(fh_)
  File "_unpacker.pyx", line 140, in msgpack._unpacker.unpack (msgpack/_unpacker.cpp:140)
  File "_unpacker.pyx", line 126, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:126)
UnpackValueError: Unpack failed: error = 0



Error: There was a query error: Exception caught
Caught Exception, terminating workers
TRACE: Unpack failed: error = 0
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 65, in _call
    ret = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 2320, in create_multiprocessing
    local_master=parallel_data['local_master']
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1287, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 2559, in create
    vm_['name'], vm_['profile'], 'ec2', vm_['driver']
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 2547, in cachedir_index_add
    index = msgpack.load(fh_)
  File "_unpacker.pyx", line 140, in msgpack._unpacker.unpack (msgpack/_unpacker.cpp:140)
  File "_unpacker.pyx", line 126, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:126)
UnpackValueError: Unpack failed: error = 0
```

The end result was that all 12 instances launched, but it seems the bootstrap deploy script failed to run on six of them.

### Setup
I'm not sure there's anything more useful I can add. Each instance launched from the map file had its own profile entry, but they all had the following configuration set:
```
  provider: ec2-us-west-2
  location: us-west-2
  availability_zone: us-west-2b
  script: bootstrap_script
  ssh_interface: private_ips
  iam_profile: 'arn:aws:iam::123456789012:instance-profile/EC2DescribeTags'
  size: t2.small
  network_interfaces:
   - DeviceIndex: 0
     PrivateIpAddresses:
     - Primary: True
     AssociatePublicIpAddress: True
     SubnetId: subnet-00facade
     SecurityGroupId:
       - sg-00000001
       - sg-00000002
  tag:
    management: salt
    manager: hostname
    stack: us-west-2b
    purpose: app
  grains:
    management: salt
    manager: hostname
    stack: us-west-2b
    purpose: app
```
The above items have been modified to use different values but the same format as we use in our staging environment where we encountered the issue.

The instance had 1Gb of RAM, 1Gb of swap, and 21 worker threads that were basically idle. The only thing that changed was the salt upgrade from `2016.11.4` to `2017.7.0`. Worker threads previously worked out at ~32MiB each (RSS), whereas now they're ~39MiB. That should still leave quite a bit of RAM free.

I feel there are two issues here. The obvious one is that Salt ideally shouldn't be throwing a stack trace when an error message would suffice. The second one is why so much memory is required that this seemingly simple operation is failing?

Before:
```
             total       used       free     shared    buffers     cached
Mem:           998        863        135          0          3         17
-/+ buffers/cache:        842        156
Swap:          999         65        934
Total:        1998        929       1069
```

Then running `salt-cloud -P -m path_to_map_file.map` we end up with the following (just prior to command completion):
```
             total       used       free     shared    buffers     cached
Mem:           998        938         59          0          5         16
-/+ buffers/cache:        916         82
Swap:          999        816        183
Total:        1998       1755        243
```

826Mb just to basically send a few GET requests and have 12 minions connect and do basically nothing... maybe I'm old fashioned, but that seems excessive. In this instance, we just scraped by without error and with 243Mb (mostly swap) remaining.

Interestingly, even after execution has completed, much more RAM remains in use:
```
             total       used       free     shared    buffers     cached
Mem:           998        839        159          0          5         16
-/+ buffers/cache:        817        181
Swap:          999        557        442
Total:        1998       1397        601
```

It's now running 24 minions by this point instead of just 12. Minions are not instructed to run `state.highstate` when they initially connect, so it's a little surprising. If we assume all minions had connected by the time the total RAM was 1755, then the drop to 1397 after execution was complete would mean that salt-cloud was "only" using 358MiB. Certainly not as bad, but not great either.

Of course, I allocate much more RAM than this in production. Our staging instances are generally running as close to the hardware limits as possible to save running costs and quickly pick up potential issues such as this.

### Steps to Reproduce Issue
```salt-cloud -P -m path/to/map_file.map``` on an AWS `t2.micro` sized instance with an extra 1Gb of swap and 21 worker threads running, and I guess be unlucky.

### Versions Report
```
Salt Version:
           Salt: 2017.7.0
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.4.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.9 
         locale: UTF-8
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.9 
 ```

**Comment by gtmanfred** [comment]
I am unable to reproduce this, though i did not set the worker_threads to 21, that seems really high.

With 5 worker threads, i was able to spin up 12, then spin up another 12.
```
[root@centos-1gb-sfo1-01 ~]# salt \* test.ping
test03:
    True
test01:
    True
test13:
    True
test15:
    True
test02:
    True
test08:
    True
test05:
    True
test07:
    True
test16:
    True
test24:
    True
test11:
    True
test23:
    True
test22:
    True
test04:
    True
test12:
    True
test19:
    True
test10:
    True
test06:
    True
test20:
    True
test14:
    True
test18:
    True
test17:
    True
test09:
    True
test21:
    True
[root@centos-1gb-sfo1-01 ~]# free -m
              total        used        free      shared  buff/cache   available
Mem:            992         294         358          12         339         530
Swap:             0           0           0
[root@centos-1gb-sfo1-01 ~]# salt-cloud --versions-report
Salt Version:
            Salt: 2017.7.0

Dependency Versions:
 Apache Libcloud: Not Installed
            cffi: Not Installed
        cherrypy: Not Installed
        dateutil: Not Installed
       docker-py: Not Installed
           gitdb: Not Installed
       gitpython: Not Installed
           ioflo: Not Installed
          Jinja2: 2.9.6
         libgit2: Not Installed
         libnacl: Not Installed
        M2Crypto: Not Installed
            Mako: Not Installed
    msgpack-pure: Not Installed
  msgpack-python: 0.4.8
    mysql-python: Not Installed
       pycparser: Not Installed
        pycrypto: 2.6.1
    pycryptodome: Not Installed
          pygit2: Not Installed
          Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
    python-gnupg: Not Installed
          PyYAML: 3.10
           PyZMQ: 16.0.2
            RAET: Not Installed
           smmap: Not Installed
         timelib: Not Installed
         Tornado: 4.5.1
             ZMQ: 4.1.6

System Versions:
            dist: centos 7.3.1611 Core
          locale: UTF-8
         machine: x86_64
         release: 3.10.0-514.21.1.el7.x86_64
          system: Linux
         version: CentOS Linux 7.3.1611 Core
```

I am going to need more information on how to replicate this.

Thanks,
Daniel

**Comment by boltronics** [comment]
I've ran it a few times now, but only had the stack trace happen to me one time.

In previous Salt releases, I was getting warnings that I probably needed to increase the number of workers. I think this happens on these instances without a huge amount of CPU power when running highstate on all connected instances (or similar high-load scenarios) - a timeout can be hit. So it's probably a matter of increasing a timeout somewhere, or increase the number of workers.

I haven't yet tried reducing the worker count on the new 2017.7.0 release to see if I still encounter such warnings.

**Comment by boltronics** [comment]
If there's some specific information you would like on the setup, let me know what I can provide.
