### ISSUE TITLE
Modifying collate for mysql_database.present with _ in database name is broken

### ISSUE THREAD

**Issue by timwsuqld** [saltstack/salt#42580]
### Description of Issue/Question
Trying to apply mysql_database.present, with a collate set, to a database with `_` in the name is broken, when it needs to modify and existing database from one default collation to another.

### Setup
```
mysql-database-zero_programs:
  mysql_database.present:
    - name: zero_programs
    - collate: utf8_unicode_ci
```

### Steps to Reproduce Issue
Apply highstate to server with existing database, zero_programs with collate utf8_general_ci, throws the following error.
```
          ID: mysql-database-zero_programs
    Function: mysql_database.present
        Name: zero_programs
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1837, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1794, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/mysql_database.py", line 69, in present
                  **connection_args)
                File "/usr/lib/python2.7/dist-packages/salt/modules/mysql.py", line 948, in alter_db
                  _execute(cur, qry, args)
                File "/usr/lib/python2.7/dist-packages/salt/modules/mysql.py", line 545, in _execute
                  return cur.execute(qry)
                File "/usr/lib/python2.7/dist-packages/pymysql/cursors.py", line 158, in execute
                  result = self._query(query)
                File "/usr/lib/python2.7/dist-packages/pymysql/cursors.py", line 308, in _query
                  conn.query(q)
                File "/usr/lib/python2.7/dist-packages/pymysql/connections.py", line 820, in query
                  self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                File "/usr/lib/python2.7/dist-packages/pymysql/connections.py", line 1002, in _read_query_result
                  result.read()
                File "/usr/lib/python2.7/dist-packages/pymysql/connections.py", line 1285, in read
                  first_packet = self.connection._read_packet()
                File "/usr/lib/python2.7/dist-packages/pymysql/connections.py", line 966, in _read_packet
                  packet.check_error()
                File "/usr/lib/python2.7/dist-packages/pymysql/connections.py", line 394, in check_error
                  err.raise_mysql_exception(self._data)
                File "/usr/lib/python2.7/dist-packages/pymysql/err.py", line 120, in raise_mysql_exception
                  _check_mysql_exception(errinfo)
                File "/usr/lib/python2.7/dist-packages/pymysql/err.py", line 112, in _check_mysql_exception
                  raise errorclass(errno, errorvalue)
              ProgrammingError: (1064, u"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '\\_programs CHARACTER SET utf8 COLLATE utf8_unicode_ci' at line 1")
     Started: 15:40:37.921262
    Duration: 5.333 ms
     Changes:   
```

Creation of databases without collate set, with a database with `_` in the name works fine.
Creation of databases with collate set, with a database with `_` in the name works fine.
**Modifying a database with collate set, when the collate doesn't match the existing database, with a database with `_` in the name fails with the error message.**

#30220 and #28737 appear to have fixed the creation, but the modifying the default is where the fault is.

### Versions Report
MariaDB version 10.1.25+maria-1~xenial
```
Salt Version:
           Salt: 2017.7.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-83-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by gtmanfred** [comment]
I am unable to replicate this.

```
[root@salt salt]# mysql -ptest zero_programs
ERROR 1049 (42000): Unknown database 'zero_programs'
[root@salt salt]# salt-call --local state.apply test
local:
----------
          ID: mysql-database-zero_programs
    Function: mysql_database.present
        Name: zero_programs
      Result: True
     Comment: The database zero_programs has been created
     Started: 14:03:14.705121
    Duration: 12.949 ms
     Changes:
              ----------
              zero_programs:
                  Present

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  12.949 ms
[root@salt salt]# mysql -ptest zero_programs
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 41
Server version: 5.5.52-MariaDB MariaDB Server

Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [zero_programs]> Bye
[root@salt salt]# cat /srv/salt/test.sls
mysql-database-zero_programs:
  mysql_database.present:
    - name: zero_programs
    - collate: utf8_unicode_ci
```

**Comment by gtmanfred** [comment]
Could you provide a docker container or some salt states that sets this up so it fails?

Thanks,
Daniel

**Comment by gtmanfred** [comment]
Nevermind, I have replicated this.

I missed the place where you said it was the modifying that this was causing the problem.

If you create without the collate, and then run the state again with that added, this fails.

Thanks for reporting.  If you wouldn't mind submitting a PR we would greatly appreciate it, otherwise I am tagging this as a bug.

Thanks!
Daniel

**Comment by gtmanfred** [comment]
@saltstack/team-triage can you reopen this for @timwsuqld

**Comment by timwsuqld** [comment]
This has been open for almost 2 years and is still an issue for us. Any upgrade on getting this fixed?

**Comment by timwsuqld** [comment]
I can replicate this on `2019.2.3`
Below is a test case to replicate it

Dockerfile to test
```
FROM ubuntu:18.04

# Install mysql server, wget curl
RUN apt-get update && apt-get install -y mariadb-server wget curl ca-certificates python-mysqldb --no-install-recommends

# Install salt
RUN curl -L https://bootstrap.saltstack.com | sh

COPY test-1.sls test-2.sls /srv/salt/

RUN /etc/init.d/mysql start; salt-call -V; salt-call --local state.apply test-1; salt-call --local state.apply test-2
```

`test-1.sls` to create the database without a collation set
```yaml
mysql-database-zero_programs:
  mysql_database.present:
    - name: zero_programs
```

`test-2.sls` to change the database collation
```yaml
mysql-database-zero_programs:
  mysql_database.present:
    - name: zero_programs
    - collate: utf8_unicode_ci
```

Output of last part of Docker build showing first applying `test-1` to create the database, then `test-2` to change the collation (and the crash)
```
Salt Version:
           Salt: 2019.2.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.3.10
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.17 (default, Nov  7 2019, 10:07:09)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: ascii
        machine: x86_64
        release: 4.15.0-74-generic
         system: Linux
        version: Ubuntu 18.04 bionic
 
local:
----------
          ID: mysql-database-zero_programs
    Function: mysql_database.present
        Name: zero_programs
      Result: True
     Comment: The database zero_programs has been created
     Started: 00:38:14.738868
    Duration: 22.2 ms
     Changes:   
              ----------
              zero_programs:
                  Present

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  22.200 ms
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1933, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1951, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/states/mysql_database.py", line 69, in present
    **connection_args)
  File "/usr/lib/python2.7/dist-packages/salt/modules/mysql.py", line 1019, in alter_db
    _execute(cur, qry, args)
  File "/usr/lib/python2.7/dist-packages/salt/modules/mysql.py", line 604, in _execute
    return cur.execute(qry)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
OperationalError: (1253, "COLLATION 'utf8_unicode_ci' is not valid for CHARACTER SET 'utf8mb4'")

local:
----------
          ID: mysql-database-zero_programs
    Function: mysql_database.present
        Name: zero_programs
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1933, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1951, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/mysql_database.py", line 69, in present
                  **connection_args)
                File "/usr/lib/python2.7/dist-packages/salt/modules/mysql.py", line 1019, in alter_db
                  _execute(cur, qry, args)
                File "/usr/lib/python2.7/dist-packages/salt/modules/mysql.py", line 604, in _execute
                  return cur.execute(qry)
                File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 250, in execute
                  self.errorhandler(self, exc, value)
                File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
                  raise errorvalue
              OperationalError: (1253, "COLLATION 'utf8_unicode_ci' is not valid for CHARACTER SET 'utf8mb4'")
     Started: 00:38:29.372149
    Duration: 9.578 ms
     Changes:   

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   9.578 ms

```

**Comment by dwoz** [comment]
Fixed by e0ad9af8218 (merged via #51559). `alter_db` no longer escapes `_`/`%` in the backtick-quoted dbname; `test_alter_db` pins the query. Present in 3006.x, 3007.x, 3008.x, master.
