### ISSUE TITLE
2017.7.0  - Minion is unable to decrypt messages from master

### ISSUE THREAD

**Issue by asymetrixs** [saltstack/salt#42582]
### Description of Issue/Question
Minion is unable to decrypt message from master.

### Setup

There is no big setup in place. All components (Python, libraries, salt) were build and installed on the respective system and the problem occurs during the initial communication (keys were already exchanged and accepted, I just deleted the master-key on the minion, below is another example of what happens when master-key is known to minion). The minion is not able to properly decrypt the master's message.

### Steps to Reproduce Issue

Start of master and minion (I deleted the master-key on the minion before).
When the master sends the 'Sending event'-message, the minion isn't able to decrypt it.
More information can be provided on request.

#### Master debug output

```
$ salt-master -l debug
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] Setting up the Salt Master
[DEBUG   ] Loaded master key: /etc/salt/pki/master/master.pem
[PROFILE ] Beginning pwd.getpwall() call in masterarpi access_keys function
[PROFILE ] End pwd.getpwall() call in masterarpi access_keys function
[INFO    ] Preparing the root key for local communication
[DEBUG   ] Removing stale keyfile: /var/cache/salt/master/.root_key
[DEBUG   ] Created pidfile: /var/run/salt-master.pid
[INFO    ] Starting up the Salt Master
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[INFO    ] salt-master is starting as user 'root'
[INFO    ] Current values for max open files soft/hard setting: 1024/4096
[INFO    ] The value for the 'max_open_files' setting, 100000, is higher than what the user running salt is allowed to raise to, 4096. Defaulting to 4096.
[INFO    ] Raising max open files value to 4096
[INFO    ] New values for max open files soft/hard values: 4096/4096
[INFO    ] Creating master process manager
[INFO    ] Creating master publisher process
[DEBUG   ] Started 'salt.transport.zeromq.<type 'instancemethod'>._publish_daemon' with pid 12368
[INFO    ] Creating master event publisher process
[INFO    ] Starting the Salt Publisher on tcp://172.16.0.1:4505
[INFO    ] Starting the Salt Puller on ipc:///var/run/salt/master/publish_pull.ipc
[DEBUG   ] Started 'salt.utils.event.EventPublisher' with pid 12371
[INFO    ] Creating master maintenance process
[DEBUG   ] Started 'salt.master.Maintenance' with pid 12372
[INFO    ] Creating master request server process
[DEBUG   ] Started 'ReqServer' with pid 12373
[DEBUG   ] Process Manager starting!
[DEBUG   ] Started 'salt.transport.zeromq.<type 'instancemethod'>.zmq_device' with pid 12374
[DEBUG   ] Started 'MWorker-0' with pid 12375
[DEBUG   ] Initializing new Schedule
[DEBUG   ] Started 'MWorker-1' with pid 12376
[INFO    ] Setting up the master communication server
[DEBUG   ] Started 'MWorker-2' with pid 12383
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] Started 'MWorker-3' with pid 12384
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Started 'MWorker-4' with pid 12385
[DEBUG   ] Process Manager starting!
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Reading configuration from /etc/salt/master
[... couple lines as above]
[DEBUG   ] Could not LazyLoad timezone.get_offset: 'timezone.get_offset' is not available.
[DEBUG   ] Could not LazyLoad config.merge: 'config.merge' is not available.
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[... couple lines as above]DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Guessing ID. The id can be explicitly set in /etc/salt/minion
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Found minion id from generate_minion_id(): master.devops
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Guessing ID. The id can be explicitly set in /etc/salt/minion
[DEBUG   ] Guessing ID. The id can be explicitly set in /etc/salt/minion
[DEBUG   ] Found minion id from generate_minion_id(): master.devops
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Guessing ID. The id can be explicitly set in /etc/salt/minion
[DEBUG   ] Guessing ID. The id can be explicitly set in /etc/salt/minion
[DEBUG   ] Guessing ID. The id can be explicitly set in /etc/salt/minion
[DEBUG   ] Found minion id from generate_minion_id(): master.devops
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Found minion id from generate_minion_id(): master.devops
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Found minion id from generate_minion_id(): master.devops
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Found minion id from generate_minion_id(): master.devops
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Updating roots fileserver cache
[DEBUG   ] This salt-master instance has accepted 1 minion keys.
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Reading configuration from /etc/salt/master
[... couple lines as above]
[INFO    ] Worker binding to socket ipc:///var/run/salt/master/workers.ipc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[INFO    ] Worker binding to socket ipc:///var/run/salt/master/workers.ipc
[... couple lines as above]
[DEBUG   ] Loaded master key: /etc/salt/pki/master/master.pem
[DEBUG   ] Loaded master key: /etc/salt/pki/master/master.pem
[INFO    ] Authentication request from ldap.devops.local
[INFO    ] Authentication accepted from ldap.devops.local
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event: tag = salt/auth; data = {'id': 'ldap.devops.local', '_stamp': '2017-07-27T08:18:37.433500', 'result': True, 'pub': '-----BEGIN RSA PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqXkJ7pqKyQUsv3omprM4\nRxdo1WbsUTkMgxCY8+mzw9o6nJyANR4vC9QpHa6pMFXNXGPt1oycztIn8ie76FPk\n6oA/VJuuHSfxGSFbAZgeiRqaf9Q+aZ157CZbR4uOO9+wJCBsvo5RQHbOm5fs4AhJ\njdH1Cwx7U1KnmTRjDT4Ou5uwjYmwKSGI3bAWYrRwi3cxftN+dW0m8MpsY0WEn18A\nmCmp2KtNCtWVv7VJIg99bfMMt3GAHSEJv/1Eqo0tX4SFTxx3yjKU3OIR03XtP/E+\n44PkuHKozg3vHDLA7y7M+xJvjwCwe4IhjF9+WtP8CzXftUtai6KbTOY3o65FLtRH\nBQIDAQAB\n-----END RSA PUBLIC KEY-----', 'act': 'accept'}
^C[INFO    ] MWorkerQueue under PID 12383 is closing
[INFO    ] MWorkerQueue under PID 12375 is closing
[DEBUG   ] EventPublisher received a SIGINT. Exiting
[DEBUG   ] Maintenance received a SIGINT. Exiting
[INFO    ] MWorkerQueue under PID 12384 is closing
[INFO    ] MWorkerQueue under PID 12385 is closing
[DEBUG   ] ZeroMQReqServerChannel received a SIGINT. Exiting
[INFO    ] MWorkerQueue under PID 12374 is closing
[DEBUG   ] MWorker received a SIGINT. Exiting
[DEBUG   ] MWorker received a SIGINT. Exiting
[DEBUG   ] MWorker received a SIGINT. Exiting
[INFO    ] MWorkerQueue under PID 12376 is closing
[DEBUG   ] MWorker received a SIGINT. Exiting
[DEBUG   ] MWorker received a SIGINT. Exiting
[DEBUG   ] ReqServer received a SIGINT. Exiting
[WARNING ] Master received a SIGINT. Exiting.
[INFO    ] The Salt Master is shut down
The salt master is shutdown. Master received a SIGINT. Exited.
```

#### Minion debug output
```
 $ salt-minion -l debug
[DEBUG   ] Reading configuration from /opt/local/etc/salt/minion
[DEBUG   ] Using cached minion ID from /opt/local/etc/salt/minion_id: ldap.devops.local
[DEBUG   ] Configuration file path: /opt/local/etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] Setting up the Salt Minion "ldap.devops.local"
[DEBUG   ] Created pidfile: /var/run/salt-minion.pid
[INFO    ] Starting up the Salt Minion
[DEBUG   ] AsyncEventPublisher PUB socket URI: /var/run/salt/minion/minion_event_617b5b7e9d_pub.ipc
[DEBUG   ] AsyncEventPublisher PULL socket URI: /var/run/salt/minion/minion_event_617b5b7e9d_pull.ipc
[INFO    ] Starting pull socket on /var/run/salt/minion/minion_event_617b5b7e9d_pull.ipc
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_617b5b7e9d_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_617b5b7e9d_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_617b5b7e9d_pub.ipc
[DEBUG   ] Reading configuration from /opt/local/etc/salt/minion
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[INFO    ] Creating minion process manager
[DEBUG   ] Process Manager starting!
[DEBUG   ] Process Manager starting!
[DEBUG   ] Connecting to master. Attempt 1 of 1
[DEBUG   ] Initializing new AsyncAuth for ('/opt/local/etc/salt/pki/minion', 'ldap.devops.local', 'tcp://172.16.0.1:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (3916)
[DEBUG   ] Setting zmq_reconnect_ivl to '3916ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/opt/local/etc/salt/pki/minion', 'ldap.devops.local', 'tcp://172.16.0.1:4506', 'clear')
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /opt/local/etc/salt/pki/minion/minion.pem
[ERROR   ] Exception in callback <functools.partial object at 0x9a923ec>
Traceback (most recent call last):
  File "/opt/abc/lib/python2.7/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/opt/abc/lib/python2.7/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/opt/abc/lib/python2.7/site-packages/tornado/ioloop.py", line 626, in _discard_future_result
    future.result()
  File "/opt/abc/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/opt/abc/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/abc/lib/python2.7/site-packages/salt/crypt.py", line 516, in _authenticate
    creds = yield self.sign_in(channel=channel)
  File "/opt/abc/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/abc/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/opt/abc/lib/python2.7/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/opt/abc/lib/python2.7/site-packages/salt/crypt.py", line 641, in sign_in
    auth['aes'] = self.verify_master(payload, master_pub='token' in sign_in_payload)
  File "/opt/abc/lib/python2.7/site-packages/salt/crypt.py", line 982, in verify_master
    return self.extract_aes(payload, master_pub=False)
  File "/opt/abc/lib/python2.7/site-packages/salt/crypt.py", line 907, in extract_aes
    aes, token = self.decrypt_aes(payload, master_pub)
  File "/opt/abc/lib/python2.7/site-packages/salt/crypt.py", line 770, in decrypt_aes
    m_digest = public_decrypt(mkey.publickey(), payload['sig'])
  File "/opt/abc/lib/python2.7/site-packages/salt/crypt.py", line 246, in public_decrypt
    return verifier.verify(message)
  File "/opt/abc/lib/python2.7/site-packages/salt/utils/rsax931.py", line 163, in verify
    raise ValueError('Unable to decrypt message')
ValueError: Unable to decrypt message
^C[WARNING ] Minion received a SIGINT. Exiting.
[INFO    ] Shutting down the Salt Minion
[DEBUG   ] Stopping the multiprocessing logging queue listener
[DEBUG   ] closing multiprocessing queue
[DEBUG   ] joining multiprocessing queue thread
[DEBUG   ] Stopped the multiprocessing logging queue listener
The Salt Minion is shutdown. Minion received a SIGINT. Exited.
```

#### Master/Minion debug output when master key is known
Master
```
[INFO    ] Authentication request from ldap.devops.local
[INFO    ] Authentication accepted from ldap.devops.local
[DEBUG   ] Sending event: tag = salt/auth; data = {'id': 'ldap.devops.local', '_stamp': '2017-07-27T08:44:45.851809', 'result': True, 'pub': '-----BEGIN RSA PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqXkJ7pqKyQUsv3omprM4\nRxdo1WbsUTkMgxCY8+mzw9o6nJyANR4vC9QpHa6pMFXNXGPt1oycztIn8ie76FPk\n6oA/VJuuHSfxGSFbAZgeiRqaf9Q+aZ157CZbR4uOO9+wJCBsvo5RQHbOm5fs4AhJ\njdH1Cwx7U1KnmTRjDT4Ou5uwjYmwKSGI3bAWYrRwi3cxftN+dW0m8MpsY0WEn18A\nmCmp2KtNCtWVv7VJIg99bfMMt3GAHSEJv/1Eqo0tX4SFTxx3yjKU3OIR03XtP/E+\n44PkuHKozg3vHDLA7y7M+xJvjwCwe4IhjF9+WtP8CzXftUtai6KbTOY3o65FLtRH\nBQIDAQAB\n-----END RSA PUBLIC KEY-----', 'act': 'accept'}
```

Minion
```
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /opt/local/etc/salt/pki/minion/minion.pem
[ERROR   ] The master failed to decrypt the random minion token
[CRITICAL] The Salt Master server's public key did not authenticate!
The master may need to be updated if it is a version of Salt lower than 2017.7.0, or
If you are confident that you are connecting to a valid Salt Master, then remove the master public key and restart the Salt Minion.
The master public key can be found at:
/opt/local/etc/salt/pki/minion/minion_master.pub
```

#### Master

Configuration File is default, only changed the listening interface

Compilation of cffi, libffi, M2crypto, psutil, pycryptodome, pyzmq, timelib, tornado, zeromq with
```
$ gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
```

```
$ g++ --version
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
```

```
$ python2.7 --version
Python 2.7.6
```

```
Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: 1.10.0
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.6.7`
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: 1.5.1
       M2Crypto: 0.26.0
           Mako: 1.0.7
   msgpack-pure: 0.1.3
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: Not Installed
   pycryptodome: 3.4.6
         pygit2: Not Installed
         Python: 2.7.6 (default, Jul 26 2017, 13:31:22)
   python-gnupg: 2.3.0
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: 0.6.7
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.2.1

System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

#### Minion
Configuration File is default, only changed line 'master' to master's IP

```
$ gcc --version
gcc (GCC) 4.6.1
```

```
$ python2.7 --version
Python 2.7.6
```

```
Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: 1.10.0
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.6.7
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: 1.5.1
       M2Crypto: 0.26.0
           Mako: 1.0.7
   msgpack-pure: 0.1.3
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: Not Installed
   pycryptodome: 3.4.6
         pygit2: Not Installed
         Python: 2.7.6 (default, Jul 25 2017, 06:54:09)
   python-gnupg: 2.3.0
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: 0.6.7
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.2.1

System Versions:
           dist:
         locale: 646
        machine: i86pc
        release: 5.10
         system: SunOS
        version: Not Installed
```

**Comment by gtmanfred** [comment]
You should not need M2Crypto.

Also, can you try using pycrypto instead of pycryptodome, we have had some problems like this with moving over to pycryptodome in the past, especially with pycryptodome on the minion and pycrypto used on the master.

Thanks,
Daniel

**Comment by asymetrixs** [comment]
Changed it on master and minion to
```
       M2Crypto: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
```

but unfortunately the error remains exactly the same.

I also recompiled the python on CentOS with flags LC_CTYPE=C, thought it could be an encoding problem but nothing changed.

**Comment by gtmanfred** [comment]
Unfortunately I do not know, I do know that we offer a solaris minion with our enterprise product, but I don't know that we have compiled 2017.7.0 on it yet.

@dmurphy18 ?

Thanks,
Daniel

**Comment by asymetrixs** [comment]
Which version is known to run properly on Solaris?

**Comment by dmurphy18** [comment]
@asymetrixs We have a Solaris 10 Minion for Salt 2017.7.0 and older releases for Enterprise customers and have not seen any issues with decrypting messages from the master.  How have you installed the salt-minion that you are using presuming it is not the Enterprise customer version.  Issues seen with python-crypto on Solaris have been due to using fastmath provided by gmp, prehaps that could be causing issues.  SaltStack builds a version of python-crypto without gmp support for Solaris and has not experienced any issues.  Also is the a Solaris Intel or Sparc machine and if so what OS and update ?

**Comment by asymetrixs** [comment]
I compiled pycrpto with

```
$ gcc --version
gcc (GCC) 5.3.0
```

=== Configure

```
$ ./configure --without-gmp --without-mpir
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether mpz_powm is declared... no
checking whether mpz_powm_sec is declared... no
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/sfw/bin/ggrep
checking for egrep... /usr/sfw/bin/ggrep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for inttypes.h... (cached) yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking wchar.h usability... yes
checking wchar.h presence... yes
checking for wchar.h... yes
checking for inline... inline
checking for int16_t... yes
checking for int32_t... yes
checking for int64_t... yes
checking for int8_t... yes
checking for size_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for uint8_t... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for memmove... yes
checking for memset... yes
configure: creating ./config.status
config.status: creating src/config.h
config.status: src/config.h is unchanged
```

**Comment by asymetrixs** [comment]
I do have exactly the same problem with 2017.11.1 and 2016.11.0, keeping all the dependencies as for 2017.11.1. My python skills aren't good enough to properly debug what is going on but perhaps the problem is caused by an imported library?

**Comment by asymetrixs** [comment]
I tracked it down, it looks like rsax931.py is calling libssl.* but what ever library it finds, the library itself does not contain the symbol (RSA_public_decrypt), so it looks like it is an openssl-problem.
It is working on my CentOS with openssl version OpenSSL 1.0.1e-fips 11 Feb 2013. Compiling this version for Solaris or even the latest (1.1.0f) gives me UNDEF

```
-bash-3.2$ nm libssl.a  | grep RSA
[112]   |         0|         0|NOTY |GLOB |0    |UNDEF  |RSA_private_decrypt
[90]    |         0|         0|NOTY |GLOB |0    |UNDEF  |RSA_sign
[91]    |         0|         0|NOTY |GLOB |0    |UNDEF  |RSA_up_ref
[151]   |         0|         0|NOTY |GLOB |0    |UNDEF  |RSA_verify
[154]   |         0|         0|NOTY |GLOB |0    |UNDEF  |RSA_free
[156]   |         0|         0|NOTY |GLOB |0    |UNDEF  |RSA_new
[97]    |         0|         0|NOTY |GLOB |0    |UNDEF  |RSA_public_encrypt
[141]   |         0|         0|NOTY |GLOB |0    |UNDEF  |RSA_sign
[167]   |         0|         0|NOTY |GLOB |0    |UNDEF  |RSA_verify
[81]    |         0|         0|NOTY |GLOB |0    |UNDEF  |EVP_PKEY_set1_RSA
[53]    |         0|         0|NOTY |GLOB |0    |UNDEF  |RSAPrivateKey_dup
[73]    |         0|         0|NOTY |GLOB |0    |UNDEF  |RSA_free
[172]   |         0|         0|NOTY |GLOB |0    |UNDEF  |RSA_size
[29]    |         0|         0|NOTY |GLOB |0    |UNDEF  |RSA_free
[34]    |         0|         0|NOTY |GLOB |0    |UNDEF  |RSA_up_ref
[39]    |         0|         0|NOTY |GLOB |0    |UNDEF  |PEM_read_bio_RSAPrivateKey
[21]    |         0|         0|NOTY |GLOB |0    |UNDEF  |RSA_flags
[27]    |         0|         0|NOTY |GLOB |0    |UNDEF  |RSA_free
[25]    |         0|         0|NOTY |GLOB |0    |UNDEF  |RSA_up_ref
[52]    |      3712|       214|FUNC |GLOB |0    |1      |SSL_CTX_use_RSAPrivateKey
[54]    |      4240|       111|FUNC |GLOB |0    |1      |SSL_CTX_use_RSAPrivateKey_ASN1
[53]    |      3936|       304|FUNC |GLOB |0    |1      |SSL_CTX_use_RSAPrivateKey_file
[22]    |       528|       214|FUNC |GLOB |0    |1      |SSL_use_RSAPrivateKey
[41]    |      2176|       111|FUNC |GLOB |0    |1      |SSL_use_RSAPrivateKey_ASN1
[38]    |      1872|       304|FUNC |GLOB |0    |1      |SSL_use_RSAPrivateKey_file
[42]    |         0|         0|NOTY |GLOB |0    |UNDEF  |d2i_RSAPrivateKey
[40]    |         0|         0|NOTY |GLOB |0    |UNDEF  |d2i_RSAPrivateKey_bio
```

Any ideas?

**Comment by asymetrixs** [comment]
rsax931.py calls libcrypto.so and finds it in a library path. Checking with ```nm```, the library contains a definition for ```RSA_public_decrypt``` but somehow still throws the error message below.

using truss shows opening of both libcrypto.so files, but both implement the function:
```
/opt/abc/lib/libcrypto.so.1.0.0:
[Index]   Value      Size      Type  Bind  Other Shndx   Name
[6707]  |    628784|        37|FUNC |GLOB |0    |10     |RSA_public_decrypt
```

```
/opt/csw/lib/libcrypto.so.1.0.0
[5420]  |    690016|        39|FUNC |GLOB |3    |13     |RSA_private_decrypt
[4475]  |    689968|        39|FUNC |GLOB |3    |13     |RSA_private_encrypt
[4700]  |    690064|        39|FUNC |GLOB |3    |13     |RSA_public_decrypt
[4170]  |    689920|        39|FUNC |GLOB |3    |13     |RSA_public_encrypt
```

```
[ERROR   ] Exception in callback <functools.partial object at 0x98620f4>
Traceback (most recent call last):
  File "/opt/abc/lib/python2.7/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/opt/abc/lib/python2.7/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/opt/abc/lib/python2.7/site-packages/tornado/ioloop.py", line 626, in _discard_future_result
    future.result()
  File "/opt/abc/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/opt/abc/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/abc/lib/python2.7/site-packages/salt/crypt.py", line 517, in _authenticate
    creds = yield self.sign_in(channel=channel)
  File "/opt/abc/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/abc/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/opt/abc/lib/python2.7/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/opt/abc/lib/python2.7/site-packages/salt/crypt.py", line 642, in sign_in
    auth['aes'] = self.verify_master(payload, master_pub='token' in sign_in_payload)
  File "/opt/abc/lib/python2.7/site-packages/salt/crypt.py", line 983, in verify_master
    return self.extract_aes(payload, master_pub=False)
  File "/opt/abc/lib/python2.7/site-packages/salt/crypt.py", line 908, in extract_aes
    aes, token = self.decrypt_aes(payload, master_pub)
  File "/opt/abc/lib/python2.7/site-packages/salt/crypt.py", line 771, in decrypt_aes
    m_digest = public_decrypt(mkey.publickey(), payload['sig'])
  File "/opt/abc/lib/python2.7/site-packages/salt/crypt.py", line 246, in public_decrypt
    return verifier.verify(message)
  File "/opt/abc/lib/python2.7/site-packages/salt/utils/rsax931.py", line 163, in verify
    raise ValueError('Unable to decrypt message')
ValueError: Unable to decrypt message
```

**Comment by asymetrixs** [comment]
If I hard code the path to any of the libcrypto.so files from above, everything works. No error is thrown and communication between master and minion works as expected (as far as I tested now).
So the problem seems to be here:
```python
lib = find_library('crypto')
if not lib and salt.utils.is_sunos():
    # Solaris-like distribution that use pkgsrc have
    # libraries in a non standard location.
    # (SmartOS, OmniOS, OpenIndiana, ...)
    # This could be /opt/tools/lib (Global Zone)
    # or /opt/local/lib (non-Global Zone), thus the
    # two checks below
    lib = glob.glob('/opt/local/lib/libcrypto.so*') + glob.glob('/opt/tools/lib/libcrypto.so*')
    lib = lib[0] if len(lib) > 0 else None
if lib:
    #return cdll.LoadLibrary('/opt/abc/lib/libcrypto.so.1.0.0')
    return cdll.LoadLibrary(lib)
raise OSError('Cannot locate OpenSSL libcrypto')
```
'lib' has a value so the is_sunos()-specific part is not called but cdll.LoadLibrary has a problem actually loading the library found in 'lib' even though it does not throw an error here and loads ```/opt/abc/lib/libcrypto.so.1.0.0```, but when I set this path by hand, everything works.

**Comment by dmurphy18** [comment]
@asymetrixs Can this issue be closed since you have this working by hand and given that it does not use the Solaris 10 salt-minion provided by SaltStack.

FYI - we use a lot of OpenCSW to build the support for Salt on Solaris, and patch ssl_includes and ssl_libraries for python setup.py  to include use OpenCSW when building.
