### ISSUE TITLE
salt-ssh - UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 49: ordinal not in range(128)

### ISSUE THREAD

**Issue by lichtamberg** [saltstack/salt#42617]
When I call ```salt-ssh 'myhost' state.highstate -i test=False``` I get following error.
Worked fine before with 2016.3.

Fails also in 2016.11, 2017.0 HEAD

```shell
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 49: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/bin/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/usr/local/lib/python2.7/site-packages/salt/scripts.py", line 404, in salt_ssh
    client.run()
  File "/usr/local/lib/python2.7/site-packages/salt/cli/ssh.py", line 20, in run
    ssh = salt.client.ssh.SSH(self.config)
  File "/usr/local/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 312, in __init__
    self.mods = mod_data(self.fsclient)
  File "/usr/local/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 1311, in mod_data
    files = fsclient.file_list(env)
  File "/usr/local/lib/python2.7/site-packages/salt/fileclient.py", line 1168, in file_list
    return [sdecode(fn_) for fn_ in self.channel.send(load)]
  File "/usr/local/lib/python2.7/site-packages/salt/fileserver/__init__.py", line 896, in send
    return getattr(self.fs, cmd)(load)
  File "/usr/local/lib/python2.7/site-packages/salt/fileserver/__init__.py", line 756, in file_list
    ret.update(self.servers[fstr](load))
  File "/usr/local/lib/python2.7/site-packages/salt/fileserver/roots.py", line 415, in file_list
    return _file_lists(load, 'files')
  File "/usr/local/lib/python2.7/site-packages/salt/fileserver/roots.py", line 391, in _file_lists
    _add_to(ret['files'], path, root, files)
  File "/usr/local/lib/python2.7/site-packages/salt/fileserver/roots.py", line 339, in _add_to
    log.trace('roots: Processing %s', abs_path)
  File "/usr/local/lib/python2.7/site-packages/salt/log/mixins.py", line 35, in trace
    self.log(getattr(logging, 'TRACE', 5), msg, *args, **kwargs)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1231, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/salt/log/setup.py", line 310, in _log
    self, level, msg, args, exc_info=exc_info, extra=extra
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1285, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/usr/local/lib/python2.7/site-packages/salt/log/setup.py", line 344, in makeRecord
    exc_info, func)
  File "/usr/local/lib/python2.7/site-packages/salt/log/setup.py", line 191, in __init__
    self.colormsg = '%s%s%s' % (cmsg, self.getMessage(), reset)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 49: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/bin/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/usr/local/lib/python2.7/site-packages/salt/scripts.py", line 404, in salt_ssh
    client.run()
  File "/usr/local/lib/python2.7/site-packages/salt/cli/ssh.py", line 20, in run
    ssh = salt.client.ssh.SSH(self.config)
  File "/usr/local/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 312, in __init__
    self.mods = mod_data(self.fsclient)
  File "/usr/local/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 1311, in mod_data
    files = fsclient.file_list(env)
  File "/usr/local/lib/python2.7/site-packages/salt/fileclient.py", line 1168, in file_list
    return [sdecode(fn_) for fn_ in self.channel.send(load)]
  File "/usr/local/lib/python2.7/site-packages/salt/fileserver/__init__.py", line 896, in send
    return getattr(self.fs, cmd)(load)
  File "/usr/local/lib/python2.7/site-packages/salt/fileserver/__init__.py", line 756, in file_list
    ret.update(self.servers[fstr](load))
  File "/usr/local/lib/python2.7/site-packages/salt/fileserver/roots.py", line 415, in file_list
    return _file_lists(load, 'files')
  File "/usr/local/lib/python2.7/site-packages/salt/fileserver/roots.py", line 391, in _file_lists
    _add_to(ret['files'], path, root, files)
  File "/usr/local/lib/python2.7/site-packages/salt/fileserver/roots.py", line 339, in _add_to
    log.trace('roots: Processing %s', abs_path)
  File "/usr/local/lib/python2.7/site-packages/salt/log/mixins.py", line 35, in trace
    self.log(getattr(logging, 'TRACE', 5), msg, *args, **kwargs)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1231, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/salt/log/setup.py", line 310, in _log
    self, level, msg, args, exc_info=exc_info, extra=extra
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1285, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/usr/local/lib/python2.7/site-packages/salt/log/setup.py", line 344, in makeRecord
    exc_info, func)
  File "/usr/local/lib/python2.7/site-packages/salt/log/setup.py", line 191, in __init__
    self.colormsg = '%s%s%s' % (cmsg, self.getMessage(), reset)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 49: ordinal not in range(128)
```

Running on MacOSX Sierra with latest update.

```shell
Salt Version:
           Salt: 2016.11.6

Dependency Versions:
           cffi: 1.10.0
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Apr  4 2017, 08:47:57)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
        machine: x86_64
        release: 16.7.0
         system: Darwin
        version: 10.12.6 x86_64
```

**Comment by damon-atkins** [comment]
See https://github.com/saltstack/salt/issues/42278#issuecomment-315374098

**Comment by lichtamberg** [comment]
Lol sorry, I've opened the same problem 25 hours ago, so this is a duplicate. See here: https://github.com/saltstack/salt/issues/42083
