### ISSUE TITLE
salt-api (rest_tornado) 2017.7 not working

### ISSUE THREAD

**Issue by pprkut** [saltstack/salt#42614]
### Description of Issue/Question

salt-api starts (using `systemctl start salt-api`) but doesn't seem to be working afterwards (http calls don't work, indicating tornado doesn't actually start up)

journalctl says

```
salt-api[23031]: Process salt.loaded.int.netapi.rest_tornado.start:
salt-api[23031]: Traceback (most recent call last):
salt-api[23031]: File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
salt-api[23031]: self.run()
salt-api[23031]: File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
salt-api[23031]: self._target(*self._args, **self._kwargs)
salt-api[23031]: File "/usr/lib/python2.7/site-packages/salt/netapi/rest_tornado/__init__.py", line 118, in start
salt-api[23031]: http_server = tornado.httpserver.HTTPServer(get_application(__opts__), **kwargs)
salt-api[23031]: AttributeError: 'module' object has no attribute 'httpserver'
```

### Setup
saltstack 2017.7 for CentOS 7 from the saltstack yum repo

### Steps to Reproduce Issue
```
rest_tornado:
  ssl_key: /etc/letsencrypt/live/salt.example.com/privkey.pem
  cors_origin: '*'
  port: 8008
  address: 0.0.0.0
  debug: True
  ssl_crt: /etc/letsencrypt/live/salt.example.com/fullchain.pem
  websockets: True
```

### Versions Report
```
Salt Version:
           Salt: 2017.7.0
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.25.1
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: 0.25.0
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.26.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

**Comment by gtmanfred** [comment]
This is fixed by #42590
