### ISSUE TITLE
Spurious errors on very long payload through the SMTP returner

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#42723]
### Description of Issue/Question

Using the smtp returner, when a scheduled job has a very long output, you can get this stack trace:

```python
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_728bcbd818_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_728bcbd818_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_728bcbd818_pull.ipc
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/utils/schedule.py", line 903, in handle_func
    event.fire_event(load, '__schedule_return')
  File "/usr/lib/python2.7/dist-packages/salt/utils/event.py", line 726, in fire_event
    dump_data = self.serial.dumps(data)
  File "/usr/lib/python2.7/dist-packages/salt/payload.py", line 207, in dumps
    return msgpack.dumps(verylong_encoder(msg), use_bin_type=use_bin_type)
  File "/usr/lib/python2.7/dist-packages/salt/payload.py", line 191, in verylong_encoder
    obj[key] = verylong_encoder(value)
  File "/usr/lib/python2.7/dist-packages/salt/payload.py", line 196, in verylong_encoder
    obj[idx] = verylong_encoder(entry)
 ...
Same error many times
...
  File "/usr/lib/python2.7/dist-packages/salt/payload.py", line 191, in verylong_encoder
    obj[key] = verylong_encoder(value)
  File "/usr/lib/python2.7/dist-packages/salt/payload.py", line 196, in verylong_encoder
    obj[idx] = verylong_encoder(entry)
  File "/usr/lib/python2.7/dist-packages/salt/payload.py", line 191, in verylong_encoder
    obj[key] = verylong_encoder(value)
  File "/usr/lib/python2.7/dist-packages/salt/payload.py", line 196, in verylong_encoder
    obj[idx] = verylong_encoder(entry)
  File "/usr/lib/python2.7/dist-packages/salt/payload.py", line 191, in verylong_encoder
    obj[key] = verylong_encoder(value)
  File "/usr/lib/python2.7/dist-packages/salt/payload.py", line 196, in verylong_encoder
    obj[idx] = verylong_encoder(entry)
  File "/usr/lib/python2.7/dist-packages/salt/payload.py", line 193, in verylong_encoder
    elif isinstance(obj, (list, tuple)):
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

### Setup

Schedule section in the (proxy) minion config:

```yaml
schedule:
  run_my_state:
    function: state.sls
    args:
      - my_state
    kwargs:
        test: true
    minutes: 1
    returner: smtp
    return_kwargs:
      subject: 'Testing'
      template: /path/to/template.jinja
```

SMTP returner config (nothing special):

```yaml
smtp.from: 'from-alias'
smtp.to: 'to-alias'
smtp.host: 'localhost'
```

Note: I have `multiprocessing: false` as I'm working with SSH-based proxies.

Executing `state.sls my_state test=True` on the CLI produces a very big object (not much hierarchical -- just `{'changes': {'diff': '.... a lot of text ...'}}`.

### Versions Report

```yaml
Salt Version:
           Salt: 2016.11.4

Dependency Versions:
           cffi: 1.10.0
       cherrypy: unknown
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.8
        machine: x86_64
        release: 4.4.17-cloudflare
         system: Linux
        version: debian 8.8
```

**Comment by mirceaulinic** [comment]
Another note: it works for the first time, but after the errors above, the schedule process crashes, and the minion doesn't have any other jobs scheduled:

```bash
$ sudo salt edge01.bjm01 schedule.list
edge01.bjm01:
    ----------
    schedule:
        ----------
```

So basically the scheduled job is executed only once, after the minion startup.

**Comment by garethgreenaway** [comment]
Sounds like we're hitting a limit somewhere.  @mirceaulinic Do you have a general sense of how long the output is that it trying to be sent to the SMTP returner?

**Comment by mirceaulinic** [comment]
Hi @garethgreenaway - thanks for looking.
The object I send has the normal highstate structure, the `changes` dict being: `{'diff': <text>}`, where the text was about 280 bytes long -- which doesn't sound like it should be terribly huge.
I'm wondering if `multiprocessing: false` could have any negative implications in this case?
