### ISSUE TITLE
http.query template_data render exception

### ISSUE THREAD

**Issue by infoveinx** [saltstack/salt#42731]
## Description
I'm having an issue using the template_data portion of http.query.  I had experienced this problem with an older 2016.11 version and gave up.  I'm now trying it again with 2016.11.6 and it still seems to exist.  I'm not sure if I'm doing something wrong here since I'm unable to find detailed examples of its usage.  My repo steps below are a slim version of the real thing that I'm trying to accomplish.  However I think it's enough to see what I'm trying to do.  I've also tried providing different data_renderer options with no luck.

**test.http-template.sls**
```
{% set name = 'testname' %}
{% set token = 'TOKEN' %}

https://domain.tld/api:
  http.query:
    - decode_type: json
    - method: POST
    - data_file: /tmp/test.json.jinja
    - data_render: True
    - template_data: {"tpl_name": "{{ name }}"}
    - verify_ssl: False
    - header_dict: {"Content-Type": "application/json", "Authorization": "Bearer {{ token }}"}
    - status: 201
```

**/tmp/test.json.jinja**
```
{
  "appName": "{{ tpl_name }}"
}
```

### Steps to Reproduce Issue
```
sudo salt -G 'role:saltmaster' state.apply test.http-template saltenv=dev
saltmaster-prod1:
----------
          ID: https://domain.tld/api
    Function: http.query
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1750, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1705, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/http.py", line 90, in query
                  data = __salt__['http.query'](name, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/http.py", line 33, in query
                  return salt.utils.http.query(url=url, opts=__opts__, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/utils/http.py", line 194, in query
                  data_file, data_render, data_renderer, template_dict, opts
                File "/usr/lib/python2.7/dist-packages/salt/utils/http.py", line 765, in _render
                  ret = compile_template(template, rend, renderer, blacklist, whitelist, **template_dict)
                File "/usr/lib/python2.7/dist-packages/salt/template.py", line 101, in compile_template
                  ret = render(input_data, saltenv, sls, **render_kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/renderers/jinja.py", line 70, in render
                  **kws)
                File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 178, in render_tmpl
                  output = render_str(tmplstr, context, tmplpath)
                File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 386, in render_jinja_tmpl
                  buf=tmplstr)
              SaltRenderError: Jinja variable 'tpl_name' is undefined
     Started: 20:09:03.041707
    Duration: 6.336 ms
     Changes:
```

```
sudo salt -G 'role:saltmaster' state.show_sls test.http-template saltenv=dev
saltmaster-prod1:
    ----------
    https://domain.tld/api:
        ----------
        __env__:
            dev
        __sls__:
            test.http-template
        http:
            |_
              ----------
              decode_type:
                  json
            |_
              ----------
              method:
                  POST
            |_
              ----------
              data_file:
                  /tmp/test.json.jinja
            |_
              ----------
              data_render:
                  True
            |_
              ----------
              template_data:
                  ----------
                  tpl_name:
                      testname
            |_
              ----------
              verify_ssl:
                  False
            |_
              ----------
              header_dict:
                  ----------
                  Authorization:
                      Bearer TOKEN
                  Content-Type:
                      application/json
            |_
              ----------
              status:
                  201
            - query
            |_
              ----------
              order:
                  10000
```

### Versions Report
```
salt-master --versions-report
Salt Version:
           Salt: 2016.11.6

Dependency Versions:
           cffi: Not Installed
       cherrypy: 10.2.1
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 2.0.2
      gitpython: 2.1.5
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-87-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

```
salt-minion --versions-report
Salt Version:
           Salt: 2016.11.6

Dependency Versions:
           cffi: Not Installed
       cherrypy: 10.2.1
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 2.0.2
      gitpython: 2.1.5
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-87-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by Ch3LL** [comment]
Looks like i'm able to replicate this behavior. Looks like it was added here: https://github.com/saltstack/salt/pull/15000/files

I am wondering if this was a typo in the docs in that PR. Can you try `template_dict` instead of `template_data`?

**Comment by Ch3LL** [comment]
okay i fixed the typo error and tested with the new `template_dict` argument. I ended up running into another issue thats fixed here: https://github.com/saltstack/salt/pull/42784

**Comment by infoveinx** [comment]
Cool thanks!  I should have mentioned that I did try template_dict at one point and that it also had an error.
