### ISSUE TITLE
Bug in win_iis module - "create_cert_binding"

### ISSUE THREAD

**Issue by Mapel88** [saltstack/salt#42818]
**This is the problematic code:
    new_cert_bindings = list_cert_bindings(site)
    if binding_info not in new_cert_bindings(site):

Just need to remove (site) from second line as follows and it's fixed:
    new_cert_bindings = list_cert_bindings(site)
    if binding_info not in new_cert_bindings:**

### Description of Issue/Question
function fails with the following exception:
2017-08-09 00:23:32,096 [salt.state       ][ERROR   ][2948] An exception occurred in this state: Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt\state.py", line 1837, in call
    **cdata['kwargs'])
  File "c:\salt\bin\lib\site-packages\salt\loader.py", line 1794, in wrapper
    return f(*args, **kwargs)
  File "c:\salt\var\cache\salt\minion\extmods\states\win_iisV2.py", line 326, in create_cert_binding
    ipaddress, port, sslflags)
  File "c:\salt\var\cache\salt\minion\extmods\modules\win_iisV2.py", line 861, in create_cert_binding
    if binding_info not in new_cert_bindings(site):
TypeError: 'dict' object is not callable

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
https-cert-binding:
      win_iis.create_cert_binding:
          - name: cert hash
          - site: Default Web Site
          - ipaddress: 127.0.0.1
          - port: 443

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
2017-08-09 00:23:32,096 [salt.state       ][ERROR   ][2948] An exception occurred in this state: Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt\state.py", line 1837, in call
    **cdata['kwargs'])
  File "c:\salt\bin\lib\site-packages\salt\loader.py", line 1794, in wrapper
    return f(*args, **kwargs)
  File "c:\salt\var\cache\salt\minion\extmods\states\win_iisV2.py", line 326, in create_cert_binding
    ipaddress, port, sslflags)
  File "c:\salt\var\cache\salt\minion\extmods\modules\win_iisV2.py", line 861, in create_cert_binding
    if binding_info not in new_cert_bindings(site):
TypeError: 'dict' object is not callable

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.26.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by gtmanfred** [comment]
Yup, that looks like a problem

Would you mind submitting a PR against 2017.7 to fix this?  If not, I can do it.

Thanks,
Daniel

**Comment by Mapel88** [comment]
Pretty new to github, so I hope I did it correctly..
I created a pull request for branch 2017.7 with the required fix.

Thanks

**Comment by rallytime** [comment]
@Mapel88 That is perfect. Thank you for filing and fixing this issue. :)
