### ISSUE TITLE
Errors while using heat module

### ISSUE THREAD

**Issue by smonko** [saltstack/salt#42827]
### Description of Issue/Question
When using heat module (connecting to Open Telecom Cloud), i am getting error:

```
The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1466, in _thread_return
        return_data = executor.execute()
      File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/usr/lib/python2.7/site-packages/salt/modules/heat.py", line 334, in list_stack
        h_client = _auth(profile)
      File "/usr/lib/python2.7/site-packages/salt/modules/heat.py", line 184, in _auth
        token = __salt__['keystone.token_get'](profile)
      File "/usr/lib/python2.7/site-packages/salt/modules/keystone.py", line 898, in token_get
        kstone = auth(profile, **connection_args)
      File "/usr/lib/python2.7/site-packages/salt/modules/keystone.py", line 163, in auth
        if float(api_version(profile=profile, **connection_args).strip('v')) >= 3:
    AttributeError: 'NoneType' object has no attribute 'strip'
```

### Setup
/etc/salt/minion.d/heat.conf
```
keystone.user: 'svc-auto'
keystone.password: '******'
keystone.tenant_id: *******************
keystone.auth_url: 'https://iam.eu-de.otc.t-systems.com:443/v3/'
keystone.region_name: 'eu-de'
keystone.insecure: False
```

### Steps to Reproduce Issue
Running _**salt 'otcaccess1.posam.sk' heat.list_stack**_ end with error. Other functions from module end with same error.

### Versions Report
```
$ pip list |grep heat
python-heatclient (1.5.2)
```

**Master:**
```
$ salt-run --versions-report
Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: 1.6.0
       cherrypy: 5.6.0
       dateutil: 1.5
      docker-py: 2.4.2
          gitdb: 2.0.2
      gitpython: 2.1.5
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.26.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```
**Minion:**
```
$ salt 'access1' test.versions_report
access:
    Salt Version:
               Salt: 2017.7.0

    Dependency Versions:
               cffi: 1.6.0
           cherrypy: 5.6.0
           dateutil: 1.5
          docker-py: 2.4.2
              gitdb: 2.0.2
          gitpython: 2.1.5
              ioflo: Not Installed
             Jinja2: 2.7.2
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: 2.14
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 15.3.0
               RAET: Not Installed
              smmap: 2.0.3
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.1.4

    System Versions:
               dist: centos 7.3.1611 Core
             locale: UTF-8
            machine: x86_64
            release: 3.10.0-514.26.2.el7.x86_64
             system: Linux
            version: CentOS Linux 7.3.1611 Core
```

**Comment by gtmanfred** [comment]
This looks like your openstack provider does not provide the `api_version` to be gotten by keystone.  We should allow an option to be specified to just use the keystonev3 version.

If you wanted to submit a PR we would greatly appreciate it.  Otherwise we are working on rewriting these to use https://github.com/openstack-infra/shade which won't have these problems.

Thanks,
Daniel
