### ISSUE TITLE
postgres_schema.present not working on develop after merging PR 42544

### ISSUE THREAD

**Issue by lukasz-baranowski** [saltstack/salt#42980]
### Description of Issue/Question
_postgres_schema.present_ not working after merging [PR 42544](https://github.com/saltstack/salt/pull/42544). 

Module method _postgres.schema_get_ expects _user_ parameter but gets _runas_ instead from postgres_schema state.

### Setup
```
postgres_schema_some_schema:
  postgres_schema.present:
    - name: some_schema
    - db_host: some_host
    - db_port: 5432
    - dbname: some_db
    - owner: some_owner
    - db_user: some_owner
    - db_password: some_password
```

### Steps to Reproduce Issue
Execute postgres_schema.present on any postgres database.

```
[INFO    ] Executing state postgres_schema.present for [some_schema]
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 1845, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1801, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/states/postgres_schema.py", line 75, in present
    schema_attr = __salt__['postgres.schema_get'](dbname, name, **db_args)
TypeError: schema_get() got an unexpected keyword argument 'runas'

[INFO    ] Completed state [some_schema] at time 14:35:03.455412 duration_in_ms=0.762
```

### Versions Report
Master:
```
Salt Version:
           Salt: 2017.7.0-407-g89c7ad0
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-1030-aws
         system: Linux
        version: Ubuntu 16.04 xenial
```

Minion:

```
Salt Version:
           Salt: 2017.7.0-1993-g89c7ad0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.16.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

**Comment by Ch3LL** [comment]
@lukasz-baranowski thanks for the PR! as there is a fix in I will close this issue but please let us know if it needs to be re-opened if there is an issue with the PR.
