### ISSUE TITLE
Get SPM Working on Windows

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#43174]
### Description of Issue/Question
SPM does not work in Windows
Need to get it running and add any batch scripts needed for the installer

### Setup
Clone the salt repo
Create a dev environment (`pkg\windows\build_env_2.ps1`)
Install salt in editable mode (`pip install -e .`)

### Steps to Reproduce Issue
Try to run `spm`. You'll get the following stack trace:
```
Traceback (most recent call last):
  File "C:\Python27\Scripts\spm-script.py", line 11, in <module>
    load_entry_point('salt', 'console_scripts', 'spm')()
  File "c:\salt-dev\salt\salt\scripts.py", line 485, in salt_spm
    import salt.cli.spm
  File "c:\salt-dev\salt\salt\cli\spm.py", line 15, in <module>
    import salt.spm
  File "c:\salt-dev\salt\salt\spm\__init__.py", line 17, in <module>
    import pwd
ImportError: No module named pwd
```

### Versions Report
2017.7 head (2017.7.1+)

**Comment by twangboy** [comment]
@gtmanfred It's in my queue

**Comment by gtmanfred** [comment]
@dwoz you also might be interested in getting this to work.
