### ISSUE TITLE
win-repo-ng: pkg.refresh_db doesn't update packages on Windows minion

### ISSUE THREAD

**Issue by alexmihajlov** [saltstack/salt#43213]
### Description of Issue/Question
I run  pkg.refresh_db on minions, but minion returns
```
        ----------
        failed:
            0
        success:
            0
        total:
            0
```
### Setup
Salt 2017.7.0 on master and minion
My master conf:
```
file_roots:
  base:
    - /etc/salt/states/base
    - /etc/salt/states/production
    - /etc/salt/win/
  production:
    - /etc/salt/states/production
    - /etc/salt/states/base
    - /etc/salt/win/


winrepo_dir_ng: '/etc/salt/win/repo-ng'
winrepo_remotes_ng:
    - 'https://github.com/saltstack/salt-winrepo-ng.git'

winrepo_dir: '/etc/salt/win/repo'
winrepo_mastercachefile: '/etc/salt/win/repo/winrepo.p'
winrepo_remotes:
    - 'https://github.com/saltstack/salt-winrepo.git'
```
Minion configuration have only id and master section.

### Steps to Reproduce Issue
```
# salt-run winrepo.update_git_repos
https://github.com/saltstack/salt-winrepo-ng.git:
    /etc/salt/win/repo-ng/salt-winrepo-ng
https://github.com/saltstack/salt-winrepo.git:
    /etc/salt/win/repo/salt-winrepo
# ls /etc/salt/win/repo/salt-winrepo/ | wc -l
326
# ls /etc/salt/win/repo-ng/salt-winrepo-ng/ | wc -l
241
# salt 'winhost' pkg.refresh_db
winhost:
    ----------
    failed:
        0
    success:
        0
    total:
        0
# salt -t60 'winhost' cmd.run 'salt-call -l debug pkg.refresh_db'
winhost:
    [DEBUG   ] Reading configuration from c:\salt\conf\minion
    [DEBUG   ] Including configuration from 'c:\salt\conf\minion.d\_schedule.conf'
    [DEBUG   ] Reading configuration from c:\salt\conf\minion.d\_schedule.conf
    [DEBUG   ] Configuration file path: c:\salt\conf\minion
    [WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
    [DEBUG   ] Reading configuration from c:\salt\conf\minion
    [DEBUG   ] Including configuration from 'c:\salt\conf\minion.d\_schedule.conf'
    [DEBUG   ] Reading configuration from c:\salt\conf\minion.d\_schedule.conf
    [DEBUG   ] Failed to import grains disks:
    Traceback (most recent call last):
      File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1404, in _load_module
        mod = spec.loader.load_module()
      File "<frozen importlib._bootstrap_external>", line 396, in _check_name_wrapper
      File "<frozen importlib._bootstrap_external>", line 817, in load_module
      File "<frozen importlib._bootstrap_external>", line 676, in load_module
      File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
      File "<frozen importlib._bootstrap>", line 693, in _load
      File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 673, in exec_module
      File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
      File "c:\salt\var\cache\salt\minion\extmods\grains\disks.py", line 3, in <module>
        from os import popen, uname
    ImportError: cannot import name 'uname'
    [DEBUG   ] Failed to import grains get_etcdir:
    Traceback (most recent call last):
      File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1404, in _load_module
        mod = spec.loader.load_module()
      File "<frozen importlib._bootstrap_external>", line 396, in _check_name_wrapper
      File "<frozen importlib._bootstrap_external>", line 817, in load_module
      File "<frozen importlib._bootstrap_external>", line 676, in load_module
      File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
      File "<frozen importlib._bootstrap>", line 693, in _load
      File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 673, in exec_module
      File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
      File "c:\salt\var\cache\salt\minion\extmods\grains\get_etcdir.py", line 3, in <module>
        from os import uname
    ImportError: cannot import name 'uname'
    [DEBUG   ] Failed to import grains is_container:
    Traceback (most recent call last):
      File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1404, in _load_module
        mod = spec.loader.load_module()
      File "<frozen importlib._bootstrap_external>", line 396, in _check_name_wrapper
      File "<frozen importlib._bootstrap_external>", line 817, in load_module
      File "<frozen importlib._bootstrap_external>", line 676, in load_module
      File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
      File "<frozen importlib._bootstrap>", line 693, in _load
      File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 673, in exec_module
      File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
      File "c:\salt\var\cache\salt\minion\extmods\grains\is_container.py", line 3, in <module>
        from os import uname, popen
    ImportError: cannot import name 'uname'
    [DEBUG   ] Motherboard info not available on this system
    [CRITICAL] Failed to load grains defined in grain file get_kernel_ident.popen in function <function popen at 0x0000004B3C6C4158>, error:
    Traceback (most recent call last):
      File "C:\salt\bin\lib\site-packages\salt\loader.py", line 740, in grains
        ret = funcs[key]()
    TypeError: popen() missing 1 required positional argument: 'cmd'
    'uname' is not recognized as an internal or external command,
    operable program or batch file.
    [CRITICAL] Failed to load grains defined in grain file get_keyreader_hostnames.sub in function <function sub at 0x0000004B3CFB8AE8>, error:
    Traceback (most recent call last):
      File "C:\salt\bin\lib\site-packages\salt\loader.py", line 740, in grains
        ret = funcs[key]()
    TypeError: sub() missing 3 required positional arguments: 'pattern', 'repl', and 'string'
    'egrep' is not recognized as an internal or external command,
    operable program or batch file.
    [CRITICAL] Failed to load grains defined in grain file netaddresses.popen in function <function popen at 0x0000004B3C6C4158>, error:
    Traceback (most recent call last):
      File "C:\salt\bin\lib\site-packages\salt\loader.py", line 740, in grains
        ret = funcs[key]()
    TypeError: popen() missing 1 required positional argument: 'cmd'
    [DEBUG   ] Connecting to master. Attempt 1 (infinite attempts)
    [DEBUG   ] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'winhost', 'tcp://10.41.253.40:4506')
    [DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (1800)
    [DEBUG   ] Setting zmq_reconnect_ivl to '1800ms'
    [DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
    [DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'winhost', 'tcp://10.41.253.40:4506', 'clear')
    [DEBUG   ] Decrypting the current master AES key
    [DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
    [DEBUG   ] SaltEvent PUB socket URI: 4510
    [DEBUG   ] SaltEvent PULL socket URI: 4511
    [DEBUG   ] Initializing new IPCClient for path: 4511
    [DEBUG   ] Sending event: tag = salt/auth/creds; data = {'key': ('c:\\salt\\conf\\pki\\minion', 'winhost', 'tcp://10.41.253.40:4506'), '_stamp': '2017-08-28T11:41:28.027014', 'creds': {'master_uri': 'tcp://10.41.253.40:4506', 'aes': '0oNkf5p86HiznfgzWVxi2CKVVf6TMLc5KeqaB3xZ94nbc7sP/HHKmYjo0PZoG53zPcAUk4nlZ1s=', 'publish_port': 4505}}
    [DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
    [DEBUG   ] Determining pillar cache
    [DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'winhost', 'tcp://10.41.253.40:4506', 'aes')
    [DEBUG   ] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'winhost', 'tcp://10.41.253.40:4506')
    [DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
    [DEBUG   ] LazyLoaded jinja.render
    [DEBUG   ] LazyLoaded yaml.render
    [DEBUG   ] LazyLoaded pkg.refresh_db
    [DEBUG   ] Refreshing pkg metadata db for saltenv 'base' (age of existing metadata is 0:01:12.750315)
    [INFO    ] Removing all *.sls files under 'c:\salt\var\cache\salt\minion\files\base\win\repo-ng'
    [DEBUG   ] LazyLoaded cp.cache_dir
    [DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'winhost', 'tcp://10.41.253.40:4506', 'aes')
    [DEBUG   ] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'winhost', 'tcp://10.41.253.40:4506')
    [INFO    ] Caching directory 'win/repo-ng/' for environment 'base'
    [DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'winhost', 'tcp://10.41.253.40:4506', 'aes')
    [DEBUG   ] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'winhost', 'tcp://10.41.253.40:4506')
    [DEBUG   ] LazyLoaded nested.output
    local:
        ----------
        failed:
            0
        success:
            0
        total:
            0
```
### Versions Report
```
# salt --versions-report
Salt Version:
           Salt: 2017.7.0
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Feb 22 2017, 19:02:48)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.4.30-1.el7.elrepo.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
 

```

**Comment by damon-atkins** [comment]
```
file_roots:
  base:
    - /etc/salt/states/base
    - /etc/salt/states/production
    - /etc/salt/win/
```
Means
`/etc/salt/win/win/repo-ng`
/etc/salt is not an ideal location for salt state and data.

**Comment by alexmihajlov** [comment]
I fix file_roots and this solved problem. Sorry for wasting your time.
