### ISSUE TITLE
Error while storing job results in an external system

### ISSUE THREAD

**Issue by varun292006** [saltstack/salt#43216]
### Description of Issue/Question
Error while storing job results in an external system

### Setup
Salt-2017.7.1 single master setup with 1 ubuntu minion

### Steps to Reproduce Issue
1) Created a log server and installed mysql

2) Created mysql schema as mentioned here:
https://docs.saltstack.com/en/latest/ref/returners/all/salt.returners.mysql.html#module-salt.returners.mysql
 
3) Installed mysqldb module on both minion and log server

4) Added below lines in minion configuration file:
    mysql.host: 'salt'
    mysql.user: 'salt'
    mysql.pass: 'salt'
    mysql.db: 'salt'
    mysql.port: 3306
   hostname, username and password are all same (as mentioned above)

5) Updated master configuration file with
    ext_job_cache: mysql
	
6) Restart minion service and master service and then execute the command

	root@masterA:~# salt -t 60 '192.168.133.182' test.ping

The command runs successfully but in the error log I see the below trace and nothing gets appended to database

`2017-08-28 12:24:21,461 [salt.transport.zeromq][DEBUG   ][40337] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'masterA_master', 'tcp://127.0.0.1:4506', 'clear')
2017-08-28 12:24:21,462 [salt.transport.ipc][DEBUG   ][40337] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
2017-08-28 12:24:21,465 [salt.utils.event ][DEBUG   ][38100] Sending event: tag = 20170828122421464763; data = {'_stamp': '2017-08-28T10:24:21.465020', 'minions': ['192.168.133.182']}
2017-08-28 12:24:21,466 [salt.utils.event ][DEBUG   ][38100] Sending event: tag = salt/job/20170828122421464763/new; data = {'tgt_type': 'glob', 'jid': '20170828122421464763', 'tgt': '192.168.133.182', '_stamp': '2017-08-28T10:24:21.466152', 'user': 'sudo_varun', 'arg': [], 'fun': 'test.ping', 'minions': ['192.168.133.182']}
2017-08-28 12:24:21,467 [salt.returners   ][INFO    ][38100] Using default for mysql ssl_key
2017-08-28 12:24:21,467 [salt.returners   ][INFO    ][38100] Using default for mysql host
2017-08-28 12:24:21,467 [salt.returners   ][INFO    ][38100] Using default for mysql ssl_cert
2017-08-28 12:24:21,467 [salt.returners   ][INFO    ][38100] Using default for mysql user
2017-08-28 12:24:21,468 [salt.returners   ][INFO    ][38100] Using default for mysql pass
2017-08-28 12:24:21,468 [salt.returners   ][INFO    ][38100] Using default for mysql db
2017-08-28 12:24:21,468 [salt.returners   ][INFO    ][38100] Using default for mysql port
2017-08-28 12:24:21,468 [salt.returners   ][INFO    ][38100] Using default for mysql ssl_ca
2017-08-28 12:24:21,468 [salt.loaded.int.returner.mysql][DEBUG   ][38100] Generating new MySQL connection pool
2017-08-28 12:24:21,469 [salt.master      ][CRITICAL][38100] The specified returner threw a stack trace:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 2102, in _prep_pub
    self.mminion.returners[fstr](clear_load['jid'], clear_load, minions=minions)
  File "/usr/lib/python2.7/dist-packages/salt/returners/mysql.py", line 321, in save_load
    with _get_serv(commit=True) as cur:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/lib/python2.7/dist-packages/salt/returners/mysql.py", line 258, in _get_serv
    raise salt.exceptions.SaltMasterError('MySQL returner could not connect to database: {exc}'.format(exc=exc))
SaltMasterError: MySQL returner could not connect to database: (2003, "Can't connect to MySQL server on 'salt' (111)")
2017-08-28 12:24:21,470 [salt.loaded.int.returner.local_cache][DEBUG   ][38100] Adding minions for job 20170828122421464763: ['192.168.133.182']
2017-08-28 12:24:21,471 [salt.master      ][INFO    ][38100] User sudo_varun Published command test.ping with jid 20170828122421464763
2017-08-28 12:24:21,471 [salt.master      ][DEBUG   ][38100] Published command details {'tgt_type': 'glob', 'jid': '20170828122421464763', 'tgt': '192.168.133.182', 'ret': 'mysql,local_cache,mysql', 'ret_kwargs': {'host': '192.168.133.181', 'user': 'root', 'pass': 'rootroot'}, 'user': 'sudo_varun', 'arg': [], 'fun': 'test.ping'}
2017-08-28 12:24:21,471 [salt.transport.zeromq][DEBUG   ][38100] Signing data packet
2017-08-28 12:24:21,473 [salt.crypt       ][DEBUG   ][38100] salt.crypt._get_rsa_key: Loading private key
2017-08-28 12:24:21,473 [salt.crypt       ][DEBUG   ][38100] salt.crypt.sign_message: Signing message.
2017-08-28 12:24:21,483 [salt.utils.lazy  ][DEBUG   ][40337] LazyLoaded local_cache.get_load
2017-08-28 12:24:21,484 [salt.loaded.int.returner.local_cache][DEBUG   ][40337] Reading minion list from /srv/share/master/jobs/89/0413fb0b5d38a11220a748fd4575e02d4f808cbfcaa2284e87ea984492f8f9/.minions.p
2017-08-28 12:24:21,485 [salt.client      ][DEBUG   ][40337] get_iter_returns for jid 20170828122421464763 sent to set(['192.168.133.182']) will timeout at 12:25:21.485129
2017-08-28 12:24:37,079 [salt.transport.mixins.auth][INFO    ][38103] Authentication request from 192.168.133.182
2017-08-28 12:24:37,080 [salt.transport.mixins.auth][INFO    ][38103] Authentication accepted from 192.168.133.182
2017-08-28 12:24:37,085 [salt.utils.event ][DEBUG   ][38103] Sending event: tag = salt/auth; data = {'id': '192.168.133.182', '_stamp': '2017-08-28T10:24:37.085486', 'result': True, 'pub': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArM4NwYnGd6Y+2xPPeyP3\n4CZoA39fE1PwB2gd2dsUX08HYiaIF39iVlEy7GWHMRwjL10aACvwxzfHyd092RI3\nv/+TRIuomclazXVo8b9dIGqSLUdYMBGyvkfIhZ0X1Wwj/pp2B+blpf37rDLhd7BV\nTbo4O67rJGmRPWAWROPHtQhUHX7qBvh2Vo5upoh6eOHrxtiQVjHswhl1KR1kze87\nDsrq4AJDMzcoqlRabh/xkXWHsG+zW1d1KqanhTrijAuxN+AxLsKSuRBIIWvjWnG+\nscCsEyuN+44pnRVVHHJmSMl4dngzVG6lFyK71JL5TqwkRpXXYkUtImXtFWurV235\n+QIDAQAB\n-----END PUBLIC KEY-----', 'act': 'accept'}
2017-08-28 12:24:37,145 [salt.utils.lazy  ][DEBUG   ][38101] LazyLoaded local_cache.prep_jid
2017-08-28 12:24:37,145 [salt.utils.job   ][INFO    ][38101] Got return from 192.168.133.182 for job 20170828122421464763
2017-08-28 12:24:37,146 [salt.transport.ipc][DEBUG   ][38101] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
2017-08-28 12:24:37,147 [salt.utils.event ][DEBUG   ][38101] Sending event: tag = salt/job/20170828122421464763/ret/192.168.133.182; data = {'fun_args': [], 'jid': '20170828122421464763', 'return': True, 'retcode': 0, 'success': True, 'cmd': '_return', '_stamp': '2017-08-28T10:24:37.147090', 'fun': 'test.ping', 'id': '192.168.133.182'}
2017-08-28 12:24:37,147 [salt.client      ][DEBUG   ][40337] jid 20170828122421464763 return from 192.168.133.182
2017-08-28 12:24:37,147 [salt.client      ][DEBUG   ][40337] return event: {'192.168.133.182': {'jid': '20170828122421464763', 'retcode': 0, 'ret': True}}
2017-08-28 12:24:37,148 [salt.utils.lazy  ][DEBUG   ][40337] LazyLoaded nested.output
2017-08-28 12:24:37,249 [salt.client      ][DEBUG   ][40337] jid 20170828122421464763 found all minions set(['192.168.133.182'])
2017-08-28 12:25:02,421 [salt.config      ][DEBUG   ][38090] Reading configuration from /etc/salt/master
2017-08-28 12:25:02,497 [salt.config      ][DEBUG   ][38090] Guessing ID. The id can be explicitly set in /etc/salt/minion
2017-08-28 12:25:02,519 [salt.config      ][DEBUG   ][38090] Found minion id from generate_minion_id(): masterA
2017-08-28 12:25:02,522 [salt.config      ][DEBUG   ][38090] Reading configuration from /etc/salt/master
2017-08-28 12:25:02,845 [salt.utils.lazy  ][DEBUG   ][38090] LazyLoaded local_cache.clean_old_jobs
2017-08-28 12:25:02,845 [salt.fileserver  ][DEBUG   ][38090] Updating roots fileserver cache

mysql> show tables;
+----------------+
| Tables_in_salt |
+----------------+
| jids           |
| salt_events    |
| salt_returns   |
+----------------+

mysql> select * from jids;
Empty set (0.00 sec)

mysql> select * from salt_returns;
Empty set (0.00 sec)

mysql> select * from salt_events;
Empty set (0.00 sec)`

### Versions Report
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.8.0-36-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by Ch3LL** [comment]
This error `SaltMasterError: MySQL returner could not connect to database: (2003, "Can't connect to MySQL server on 'salt' (111)")` seems to indicate your configuration in the minion config is probably wrong. Can you confirm with the mysql cli client that you can connect  to that database with the username/password and hostname from that minion?

**Comment by varun292006** [comment]
Hi,

Thanks a lot for the reply.

I tried what you asked for but that didn't work either.

root@masterA:/srv/salt# salt -t 60 'salt' state.apply test_mysql
salt:
----------
          ID: get_data
    Function: mysql_query.run
        Name: test1
      Result: False
     Comment: MySQL Error 2003: Can't connect to MySQL server on 'salt' (111)
     Started: 19:34:08.887517
    Duration: 11.092 ms
     Changes:   

Summary for salt
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:  11.092 ms
ERROR: Minions returned with non-zero exit code

root@masterA:/srv/salt# cat test_mysql.sls 
get_data:
  mysql_query.run:
    - name: test1
    - database: salt
    - query: "SELECT * FROM jids;"
    - output: "/tmp/test.log"
    - overwrite: True


I have attached my configuration files as well. Could you please have a look at them?

[master.txt](https://github.com/saltstack/salt/files/1257688/master.txt)
[minion.txt](https://github.com/saltstack/salt/files/1257687/minion.txt)

**Comment by Ch3LL** [comment]
Apologies I wasn't clear. I meant for you to try from the mysql cli tool outside of salt. `mysql -u {username} -p{password} -h {remote server ip} {DB name}` with the same credentials you are using in the minion config? This will allow us to determine if its an issue with salt or the mysql setup.

**Comment by varun292006** [comment]
Thanks!

The problem was with MySQL, I have fixed it.

One thing which I want to achieve is to have data written in both mysql and local cache. As per the documentation if I don't set ext_job_cache: mysql in master configuration file and pass --return mysql explicitly with the salt command then it will write in local cache as well as mysql.

Is this correct?

If yes then how can I achieve it (as it is not happening right now)?

**Comment by varun292006** [comment]
Thanks a lot for trying that out.

Here is what I am trying to achieve:

I have a high available test environment with 2 masters (Master_A and Master_B) both are configured as "hot" (active-active) and 2 Windows minions (managed by these 2 masters)

Now, Master_A sends a command to a minion and as soon as the minion gets the command, Master_A goes down. Now, (correct me if I am wrong) the operation will still be performed on the minion but it won't be able to send the result back via 4506 port (I am not sure if this will be sent to other master i.e. Master_B, since it is high available environment it should). In this case I want minions to send the return data to MySQL.

**So is it possible to achieve this kind of high availability that if in case 1 master goes down the data is returned via other master to MySQL or local_cache?**

And this is what I did:

1) Added below lines in minion configuration file:
```
mysql.host: 'salt'
mysql.user: 'salt'
mysql.pass: 'salt'
mysql.db: 'salt'
mysql.port: 3306
```

2) Commented out ext_job_cache from master configuration file
```
#ext_job_cache: mysql
```

3) Restart master service

4) Execute command
`salt -t 60 '192.168.133.182' test.ping --return mysql,local_cache`
