### ISSUE TITLE
Redis returner could not deserialize msgpack message: Exception: unpack(b) received extra data

### ISSUE THREAD

**Issue by fzk-rec** [saltstack/salt#43240]
### Description of Issue/Question
I am trying to use salt-master with a REDIS backend for the returners. I followed the steps in https://docs.saltstack.com/en/latest/topics/jobs/external_cache.html#external-job-cache and put the redis data into the master config file, as well as setting the master_job_cache value:

/etc/salt/master:
```
worker_threads: 20
open_mode: True
auto_accept: True
log_level: error
log_level_logfile: debug
extension_modules: srv/salt/ext
rest_cherrypy:
  port: 8000
  disable_ssl: True
  debug: True
external_auth:
  pam:
    saltdev:
      - .*
      - '@runner'
master_job_cache: redis
redis.host: saltmaster-redis.ijtuod.0001.use1.cache.amazonaws.com
redis.port: 6379
redis.db: '0'
```
### Setup
Salt-Master is running inside a docker container that is based on Ubuntu 16.04

I read in another github issue that you're supposed to install **'python-redis'**, so I did that. I also did an pip uninstall python-redis, restarted the salt-master, but got the same result

### Steps to Reproduce Issue
- Install salt-master 2016.11.7
- add redis information to config
- add master_job_cache to config and set it to redis
- run salt '*' test.ping --return redis
- get output like this:
```
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', '9842339e2bd1_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[CRITICAL] Could not deserialize msgpack message.This often happens when trying to read a file not in binary modeTo see message payload, enable debug logging and retry. Exception: unpack(b) received extra data.
[DEBUG   ] Msgpack deserialization failure on message: Some exception handling minion payload
[ERROR   ] Uncaught exception, closing connection.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 968, in mark_future
    data = self.serial.loads(msg[0])
  File "/usr/lib/python2.7/dist-packages/salt/payload.py", line 137, in loads
    ret = msgpack.loads(msg, use_list=True, encoding=encoding)
  File "msgpack/_unpacker.pyx", line 142, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:142)
ExtraData: unpack(b) received extra data.
[ERROR   ] Uncaught exception, closing connection.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 968, in mark_future
    data = self.serial.loads(msg[0])
  File "/usr/lib/python2.7/dist-packages/salt/payload.py", line 137, in loads
    ret = msgpack.loads(msg, use_list=True, encoding=encoding)
  File "msgpack/_unpacker.pyx", line 142, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:142)
ExtraData: unpack(b) received extra data.
[ERROR   ] Exception in callback None
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/ioloop.py", line 866, in start
    handler_func(fd_obj, events)
  File "/usr/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 968, in mark_future
    data = self.serial.loads(msg[0])
  File "/usr/lib/python2.7/dist-packages/salt/payload.py", line 137, in loads
    ret = msgpack.loads(msg, use_list=True, encoding=encoding)
  File "msgpack/_unpacker.pyx", line 142, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:142)
ExtraData: unpack(b) received extra data.
[DEBUG   ] SaltReqTimeoutError, retrying. (1/3)
[DEBUG   ] SaltReqTimeoutError, retrying. (2/3)
[DEBUG   ] SaltReqTimeoutError, retrying. (3/3)
[DEBUG   ] LazyLoaded nested.output
Salt request timed out. The master is not responding. If this error persists after verifying the master is up, worker_threads may need to be increased.
```

### Versions Report
```
Salt Version:
           Salt: 2016.11.7

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.9.38-16.35.amzn1.x86_64
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by gtmanfred** [comment]
I am unable to replicate this issue.

I am using redis server 3.2, and have used python-redis on centos 7.

```
[root@salt ~]# nc localhost 6379
keys *
*0
[root@salt ~]# salt \* test.ping --return redis
salt.c.gtmanfred-1263.internal:
    True
[root@salt ~]# nc localhost 6379
keys *
*4
$24
ret:20170829210546797516
$25
load:20170829210546797516
$7
minions
$40
salt.c.gtmanfred-1263.internal:test.ping
smembers minions
*1
$30
salt.c.gtmanfred-1263.internal
get salt.c.gtmanfred-1263.internal:test.ping
$20
20170829210546797516
hgetall ret:20170829210546797516
*2
$30
salt.c.gtmanfred-1263.internal
$154
{"fun_args": [], "jid": "20170829210546797516", "return": true, "retcode": 0, "success": true, "fun": "test.ping", "id": "salt.c.gtmanfred-1263.internal"}
get load:20170829210546797516
$215
{"tgt_type": "glob", "jid": "20170829210546797516", "cmd": "publish", "tgt": "*", "kwargs": {"delimiter": ":", "show_timeout": true, "show_jid": false}, "ret": "redis", "user": "root", "arg": [], "fun": "test.ping"}
```

the `load:<jid>` is the master `master_job_cache`, and the `ret:<jid>` is the minion `ext_job_cache`

Can you give me any more information to be able to replicate this?

Thanks,
Daniel

**Comment by fzk-rec** [comment]
Hi Daniel,
I got it to work by installing python-redis via **apt-get install python-redis** instead of **pip install python-redis**, and it worked out of the box. It looks like the pip python-redis module does not work currently with salt. Maybe you should mention that somewhere in the documentation :)

Thanks for looking into this so fast!

**Comment by gtmanfred** [comment]
So, I am unable to replicate this with the pip package on the salt-master on ubuntu.

It works just fine.  I did have to restart the master so that the redis returner gets loaded correctly.

Daniel

**Comment by fzk-rec** [comment]
Mhh, maybe something was wrong with docker container then? I don't know.
