### ISSUE TITLE
Error whilst collecting napalm grains

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#43241]
### Description of Issue/Question

This error is raised at the first grains collection attempt, when the proxy and the pillar data is not yet ready:

```python
2017-08-29 12:06:46,748 [salt.loader      ][CRITICAL][23751] Failed to load grains defined in grain file napalm.optional_args in function <function optional_args at 0x7fb0a4114a28>, error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 738, in grains
    ret = funcs[key](proxy)
  File "/usr/lib/python2.7/dist-packages/salt/grains/napalm.py", line 453, in optional_args
    opt_args.pop(arg, None)
AttributeError: 'NoneType' object has no attribute 'pop'
```

That's just a small fix.

**Comment by gtmanfred** [comment]
@mirceaulinic are you working on a fix for this?

If not, I can submit one.

```
diff --git a/salt/grains/napalm.py b/salt/grains/napalm.py
index 6ac52464c8..8a86bd2920 100644
--- a/salt/grains/napalm.py
+++ b/salt/grains/napalm.py
@@ -109,7 +109,7 @@ def _get_device_grain(name, proxy=None):
     Retrieves device-specific grains.
     '''
     device = _retrieve_device_cache(proxy=proxy)
-    return device.get(name.upper())
+    return device.get(name.upper()) or {}

 # ----------------------------------------------------------------------------------------------------------------------
 # actual grains
```

Thanks!
Daniel

**Comment by mirceaulinic** [comment]
Thanks @gtmanfred - yes, that should probably fix it. I didn't prepare anything so solve this issue, I just noticed it and reported the bug. So if you already have a branch prepared, please go ahead and submit! :-)
Cheers!

**Comment by gtmanfred** [comment]
Will do, thanks
Daniel

**Comment by mirceaulinic** [comment]
Closed via https://github.com/saltstack/salt/commit/1fc730773521405c3e850d055627b78a64c0a35a
