### ISSUE TITLE
Salt-Cloud  There was a profile error: invalid literal for int() with base 10:

### ISSUE THREAD

**Issue by tylerjones4508** [saltstack/salt#43427]
### Description of Issue/Question
Hello, Im trying to provision VirtualBox vms with Salt-Cloud, but I am getting the following error.  

`
ERROR   ] There was a profile error: invalid literal for int() with base 10: ''
`
### Setup
Here is my providers in `/etc/salt/cloud.providers.d/virtualbox.conf`

```
virtualbox-config:
  driver: virtualbox
```
Here is my profiles `/etc/salt/cloud.profiles.d/virtualbox.conf`

```
virtualbox:
  provider: virtualbox-config
  clonefrom: ubuntu_clone_16.04  Clone
  power_on: True
  deploy: True
  ssh_username: someuser
  password: somepassword
  sudo: someusersudo
  sudo_password: somesudopassword
  minion:
    master: masterIP
```
And If I run `VBoxManage -nologo list vms` it returns

`"ubuntu_clone_16.04  Clone"`

### Steps to Reproduce Issue
Debug Output of `salt-cloud -p virtualbox ubuntu-test-minion -l debug`

```
[DEBUG   ] Reading configuration from /etc/salt/cloud
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt-master.local
[DEBUG   ] Missing configuration file: /etc/salt/cloud.providers
[DEBUG   ] Including configuration from '/etc/salt/cloud.providers.d/virtualbox.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers.d/virtualbox.conf
[DEBUG   ] Missing configuration file: /etc/salt/cloud.profiles
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/virtualbox.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/virtualbox.conf
[DEBUG   ] Configuration file path: /etc/salt/cloud
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] salt-cloud starting
[DEBUG   ] Could not LazyLoad parallels.avail_sizes: 'parallels' __virtual__ returned False
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy: 'saltify.destroy' is not available.
[DEBUG   ] Could not LazyLoad saltify.avail_sizes: 'saltify.avail_sizes' is not available.
[DEBUG   ] Could not LazyLoad saltify.avail_images: 'saltify.avail_images' is not available.
[DEBUG   ] Could not LazyLoad saltify.avail_locations: 'saltify.avail_locations' is not available.
[DEBUG   ] Could not LazyLoad rackspace.reboot: 'rackspace.reboot' is not available.
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] Could not LazyLoad rackspace.list_locations: 'rackspace.list_locations' is not available.
[DEBUG   ] Could not LazyLoad virtualbox.optimize_providers: 'virtualbox.optimize_providers' is not available.
[DEBUG   ] The 'virtualbox' cloud driver is unable to be optimized.
[DEBUG   ] Could not LazyLoad parallels.avail_sizes: 'parallels' __virtual__ returned False
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy: 'saltify.destroy' is not available.
[DEBUG   ] Could not LazyLoad saltify.avail_sizes: 'saltify.avail_sizes' is not available.
[DEBUG   ] Could not LazyLoad saltify.avail_images: 'saltify.avail_images' is not available.
[DEBUG   ] Could not LazyLoad saltify.avail_locations: 'saltify.avail_locations' is not available.
[DEBUG   ] Could not LazyLoad rackspace.reboot: 'rackspace.reboot' is not available.
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] Could not LazyLoad rackspace.list_locations: 'rackspace.list_locations' is not available.
[DEBUG   ] Generating minion keys for 'ubuntu-test-minion'
[DEBUG   ] Going to fire event: starting create
[DEBUG   ] LazyLoaded cloud.filter_event
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event: tag = salt/cloud/ubuntu-test-minion/creating; data = {'profile': 'virtualbox', '_stamp': '2017-09-09T20:27:45.565481', 'name': 'ubuntu-test-minion', 'driver': 'virtualbox', 'provider': 'virtualbox-config:virtualbox', 'event': 'starting create'}
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event: tag = salt/cloud/ubuntu-test-minion/requesting; data = {'_stamp': '2017-09-09T20:27:45.592241', 'clone_from': 'ubuntu_clone_16.04  Clone', 'name': 'ubuntu-test-minion', 'event': 'requesting instance'}
[INFO    ] Clone virtualbox machine ubuntu-test-minion from ubuntu_clone_16.04  Clone
[INFO    ] Finished cloning ubuntu-test-minion from ubuntu_clone_16.04  Clone
[INFO    ] Starting machine ubuntu-test-minion in state PoweredOff
[INFO    ] Started machine ubuntu-test-minion
[ERROR   ] There was a profile error: invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 284, in run
    self.config.get('names')
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1457, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1287, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/virtualbox.py", line 167, in create
    ips = vb_wait_for_network_address(wait_for_ip_timeout, machine_name=vm_name)
  File "/usr/lib/python2.7/dist-packages/salt/utils/virtualbox.py", line 219, in vb_wait_for_network_address
    return wait_for(vb_get_network_addresses, timeout=timeout, step=step, default=[], func_kwargs=kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/utils/timeout.py", line 41, in wait_for
    call_ret = func(*func_args, **func_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/utils/virtualbox.py", line 282, in vb_get_network_addresses
    total_slots = int(machine.getGuestPropertyValue('/VirtualBox/GuestInfo/Net/Count'))
ValueError: invalid literal for int() with base 10: ''
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 1133, in __global_logging_exception_handler
    exc_type, exc_value, exc_traceback
  File "/usr/lib/python2.7/logging/__init__.py", line 1193, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 327, in _log
    self, level, msg, args, exc_info=exc_info, extra=extra
  File "/usr/lib/python2.7/logging/__init__.py", line 1285, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 350, in makeRecord
    _msg = msg.decode(salt_system_encoding, 'replace')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
TypeError: 'NoneType' object is not callable

Original exception was:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: __import__ not found
Failed to log an error record
Original error follows:
Wrapping an interface object for the gateway failed

Traceback (most recent call last):
  File "/usr/lib/virtualbox/sdk/bindings/xpcom/python/xpcom/server/policy.py", line 212, in _MakeInterfaceParam_
    import xpcom.xpt
<type 'exceptions.ImportError'>: No module named xpt
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 1133, in __global_logging_exception_handler
    exc_type, exc_value, exc_traceback
  File "/usr/lib/python2.7/logging/__init__.py", line 1193, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 327, in _log
    self, level, msg, args, exc_info=exc_info, extra=extra
  File "/usr/lib/python2.7/logging/__init__.py", line 1285, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 350, in makeRecord
    _msg = msg.decode(salt_system_encoding, 'replace')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
TypeError: 'NoneType' object is not callable

Original exception was:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: __import__ not found
Failed to log an error record
Original error follows:
The exception handler _CallMethodException_ failed!

Traceback (most recent call last):
  File "/usr/lib/virtualbox/sdk/bindings/xpcom/python/xpcom/server/policy.py", line 335, in _CallMethodException_
    self._doHandleException("<building method repr>", sys.exc_info())
  File "/usr/lib/virtualbox/sdk/bindings/xpcom/python/xpcom/server/policy.py", line 312, in _doHandleException
    logger.exception("Unhandled exception calling '%s'", func_name)
  File "/usr/lib/python2.7/logging/__init__.py", line 1200, in exception
    self.error(msg, *args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1193, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 327, in _log
    self, level, msg, args, exc_info=exc_info, extra=extra
  File "/usr/lib/python2.7/logging/__init__.py", line 1285, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 350, in makeRecord
    _msg = msg.decode(salt_system_encoding, 'replace')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 1133, in __global_logging_exception_handler
    exc_type, exc_value, exc_traceback
  File "/usr/lib/python2.7/logging/__init__.py", line 1193, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 327, in _log
    self, level, msg, args, exc_info=exc_info, extra=extra
  File "/usr/lib/python2.7/logging/__init__.py", line 1285, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 350, in makeRecord
    _msg = msg.decode(salt_system_encoding, 'replace')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
TypeError: 'NoneType' object is not callable

Original exception was:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: __import__ not found
Failed to log an error record
Original error follows:
The function 'observe' failed

Traceback (most recent call last):
  File "/usr/lib/virtualbox/sdk/bindings/xpcom/python/xpcom/server/policy.py", line 281, in _CallMethod_
    return 0, func(*params)
  File "/usr/lib/virtualbox/sdk/bindings/xpcom/python/xpcom/components.py", line 233, in observe
    xpcom.client._shutdown()
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.10.0-33-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by garethgreenaway** [comment]
@gtmanfred @rallytime You've both contributed some code to the virtualbox cloud driver, any thoughts on this one?

**Comment by marco-m** [comment]
@tylerjones4508 if you rename `ubuntu_clone_16.04` to `ubuntu_clone_1604` (both in `virtualbox.conf`) and as vm name in virtualbox, do you have the same problem ?

**Comment by tylerjones4508** [comment]
@marco-m looks like its the same results. 

Still getting `There was a profile error: invalid literal for int() with base 10: ''`

VM clone
```
tjones2@salt-master:~$ sudo VBoxManage -nologo list vms
"ubuntu_clone_1604" {00c2dde3-25ba-4325-b28e-feac04816269}
```
Profile
```
tjones2@salt-master:~$ cat /etc/salt/cloud.profiles.d/virtualbox.conf


virtualbox:
  provider: virtualbox-config
  clonefrom: ubuntu_clone_1604
  power_on: True
  deploy: True
  ssh_username: someuser
  password: somepassword
  sudo: someusersudo
  sudo_password: somesudopassword
  minion:
    master: masterIP
```

Output of Salt Cloud

```
tjones2@salt-master:~$ sudo salt-cloud -p virtualbox minion  -l debug
[DEBUG   ] Reading configuration from /etc/salt/cloud
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt-master.local
[DEBUG   ] Missing configuration file: /etc/salt/cloud.providers
[DEBUG   ] Including configuration from '/etc/salt/cloud.providers.d/virtualbox.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers.d/virtualbox.conf
[DEBUG   ] Missing configuration file: /etc/salt/cloud.profiles
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/virtualbox.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/virtualbox.conf
[DEBUG   ] Configuration file path: /etc/salt/cloud
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] salt-cloud starting
[DEBUG   ] Could not LazyLoad parallels.avail_sizes: 'parallels' __virtual__ returned False
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy: 'saltify.destroy' is not available.
[DEBUG   ] Could not LazyLoad saltify.avail_sizes: 'saltify.avail_sizes' is not available.
[DEBUG   ] Could not LazyLoad saltify.avail_images: 'saltify.avail_images' is not available.
[DEBUG   ] Could not LazyLoad saltify.avail_locations: 'saltify.avail_locations' is not available.
[DEBUG   ] Could not LazyLoad rackspace.reboot: 'rackspace.reboot' is not available.
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] Could not LazyLoad rackspace.list_locations: 'rackspace.list_locations' is not available.
[DEBUG   ] Could not LazyLoad virtualbox.optimize_providers: 'virtualbox.optimize_providers' is not available.
[DEBUG   ] The 'virtualbox' cloud driver is unable to be optimized.
[DEBUG   ] Could not LazyLoad parallels.avail_sizes: 'parallels' __virtual__ returned False
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy: 'saltify.destroy' is not available.
[DEBUG   ] Could not LazyLoad saltify.avail_sizes: 'saltify.avail_sizes' is not available.
[DEBUG   ] Could not LazyLoad saltify.avail_images: 'saltify.avail_images' is not available.
[DEBUG   ] Could not LazyLoad saltify.avail_locations: 'saltify.avail_locations' is not available.
[DEBUG   ] Could not LazyLoad rackspace.reboot: 'rackspace.reboot' is not available.
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] Could not LazyLoad rackspace.list_locations: 'rackspace.list_locations' is not available.
[DEBUG   ] Generating minion keys for 'minion'
[DEBUG   ] Going to fire event: starting create
[DEBUG   ] LazyLoaded cloud.filter_event
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event: tag = salt/cloud/minion/creating; data = {'profile': 'virtualbox', '_stamp': '2017-09-12T22:09:59.457669', 'name': 'minion', 'driver': 'virtualbox', 'provider': 'virtualbox-config:virtualbox', 'event': 'starting create'}
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event: tag = salt/cloud/minion/requesting; data = {'_stamp': '2017-09-12T22:09:59.484274', 'clone_from': 'ubuntu_clone_1604', 'name': 'minion', 'event': 'requesting instance'}
[INFO    ] Clone virtualbox machine minion from ubuntu_clone_1604
[INFO    ] Finished cloning minion from ubuntu_clone_1604
[INFO    ] Starting machine minion in state PoweredOff
[INFO    ] Started machine minion
[ERROR   ] There was a profile error: invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 284, in run
    self.config.get('names')
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1457, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1287, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/virtualbox.py", line 167, in create
    ips = vb_wait_for_network_address(wait_for_ip_timeout, machine_name=vm_name)
  File "/usr/lib/python2.7/dist-packages/salt/utils/virtualbox.py", line 219, in vb_wait_for_network_address
    return wait_for(vb_get_network_addresses, timeout=timeout, step=step, default=[], func_kwargs=kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/utils/timeout.py", line 41, in wait_for
    call_ret = func(*func_args, **func_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/utils/virtualbox.py", line 282, in vb_get_network_addresses
    total_slots = int(machine.getGuestPropertyValue('/VirtualBox/GuestInfo/Net/Count'))
ValueError: invalid literal for int() with base 10: ''
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 1133, in __global_logging_exception_handler
    exc_type, exc_value, exc_traceback
  File "/usr/lib/python2.7/logging/__init__.py", line 1193, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 327, in _log
    self, level, msg, args, exc_info=exc_info, extra=extra
  File "/usr/lib/python2.7/logging/__init__.py", line 1285, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 350, in makeRecord
    _msg = msg.decode(salt_system_encoding, 'replace')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
TypeError: 'NoneType' object is not callable

Original exception was:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: __import__ not found
Failed to log an error record
Original error follows:
Wrapping an interface object for the gateway failed

Traceback (most recent call last):
  File "/usr/lib/virtualbox/sdk/bindings/xpcom/python/xpcom/server/policy.py", line 212, in _MakeInterfaceParam_
    import xpcom.xpt
<type 'exceptions.ImportError'>: No module named xpt
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 1133, in __global_logging_exception_handler
    exc_type, exc_value, exc_traceback
  File "/usr/lib/python2.7/logging/__init__.py", line 1193, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 327, in _log
    self, level, msg, args, exc_info=exc_info, extra=extra
  File "/usr/lib/python2.7/logging/__init__.py", line 1285, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 350, in makeRecord
    _msg = msg.decode(salt_system_encoding, 'replace')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
TypeError: 'NoneType' object is not callable

Original exception was:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: __import__ not found
Failed to log an error record
Original error follows:
The exception handler _CallMethodException_ failed!

Traceback (most recent call last):
  File "/usr/lib/virtualbox/sdk/bindings/xpcom/python/xpcom/server/policy.py", line 335, in _CallMethodException_
    self._doHandleException("<building method repr>", sys.exc_info())
  File "/usr/lib/virtualbox/sdk/bindings/xpcom/python/xpcom/server/policy.py", line 312, in _doHandleException
    logger.exception("Unhandled exception calling '%s'", func_name)
  File "/usr/lib/python2.7/logging/__init__.py", line 1200, in exception
    self.error(msg, *args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1193, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 327, in _log
    self, level, msg, args, exc_info=exc_info, extra=extra
  File "/usr/lib/python2.7/logging/__init__.py", line 1285, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 350, in makeRecord
    _msg = msg.decode(salt_system_encoding, 'replace')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 1133, in __global_logging_exception_handler
    exc_type, exc_value, exc_traceback
  File "/usr/lib/python2.7/logging/__init__.py", line 1193, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 327, in _log
    self, level, msg, args, exc_info=exc_info, extra=extra
  File "/usr/lib/python2.7/logging/__init__.py", line 1285, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 350, in makeRecord
    _msg = msg.decode(salt_system_encoding, 'replace')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
TypeError: 'NoneType' object is not callable

Original exception was:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: __import__ not found
Failed to log an error record
Original error follows:
The function 'observe' failed

Traceback (most recent call last):
  File "/usr/lib/virtualbox/sdk/bindings/xpcom/python/xpcom/server/policy.py", line 281, in _CallMethod_
    return 0, func(*params)
  File "/usr/lib/virtualbox/sdk/bindings/xpcom/python/xpcom/components.py", line 233, in observe
    xpcom.client._shutdown()
<type 'exceptions.TypeError'>: 'NoneType' object is not callable```

**Comment by tylerjones4508** [comment]
Any update on this?

**Comment by cetanu** [comment]
The first thing I see here is that it's waiting on a network address from virtualbox, which is fine, but while it executes the wrapped function vb_get_network_addresses, it gets a value error. I can't make sense of the follow-on stack traces, but that's because I haven't looked at them much, yet.

Annoyingly, the last change to the line causing the error was just a pep8 change 👎 

This function needs to be changed so that it handles errors and returns a non-truthy value until it receives some addresses.

PR coming up.

**Comment by tylerjones4508** [comment]
@cetanu Thanks!

**Comment by mz-bmcqueen** [comment]
This was likely fixed by this PR:  https://github.com/saltstack/salt/pull/44827.  In there I added a check for the case where:

`_total_slots = machine.getGuestPropertyValue('/VirtualBox/GuestInfo/Net/Count')`

returns a non-integer.
