### ISSUE TITLE
Exception after try to delete unexisted file(s)

### ISSUE THREAD

**Issue by jfoboss** [saltstack/salt#43433]
### Description of Issue/Question
It looks like a bug in `win_lgpo.py` salt module:
```
function _importSeceditConfig

try:
>>> exception after try to delete unexisted file(s) <<<
    _ret = __salt__['file.remove'](_tSdbfile)
    _ret = __salt__['file.remove'](_tInfFile)
```

While there are no temp files (yet), module crashes with exception.

### Setup
Masterless local install on Windows Server 2016.

Formula:
```
Company Local Group Policy:
  lgpo.set:
    - computer_policy:
        Passwords must meet complexity requirements: Enabled
```

### Steps to Reproduce Issue
1. Run salt with provided windows group policy formula via `salt-call.bat`
2. Get error:
```
2017-09-11 14:36:13,519 [salt.loaded.int.module.win_lgpo][DEBUG   ][8676] error occurred while trying to import secedit data
2017-09-11 14:36:13,537 [salt.state       ][ERROR   ][8676] An exception occurred in this state: Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\state.py", line 1837, in call
    **cdata['kwargs'])
  File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1794, in wrapper
    return f(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\states\win_lgpo.py", line 301, in set_
    adml_language=adml_language)
  File "C:\salt\bin\lib\site-packages\salt\modules\win_lgpo.py", line 5293, in set_
    raise CommandExecutionError(msg)
salt.exceptions.CommandExecutionError: Error while attempting to set policies via secedit.  Some changes may not be applied as expected

2017-09-11 14:36:13,546 [salt.state       ][INFO    ][8676] Completed state [Company Local Group Policy] at time 14:36:13.546744 duration_in_ms=3161.181
```
### Versions Report
```
C:\salt>salt-call.bat —versions-report
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.2
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900
64 bit (AMD64)]
   python-gnupg: 0.4.0
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1251
        machine: AMD64
        release: 7
         system: Windows
        version: 7 6.1.7601 SP1 Multiprocessor Free
```

**Comment by garethgreenaway** [comment]
Thanks for the report.  Definitely looks like a bug.  We'll get someone to check this out asap.

**Comment by jfoboss** [comment]
:(
