### ISSUE TITLE
Couchbase returner `get_load` throws `KeyError`

### ISSUE THREAD

**Issue by kunal-bajpai** [saltstack/salt#43452]
### Description of Issue/Question
When `couchbase.get_load` is called after `couchbase.prep_jid` but before `couchbase.save_load` then a `KeyError` is thrown in the following line
https://github.com/saltstack/salt/blob/develop/salt/returners/couchbase_return.py#L219
This is because `prep_jid` will write a document `{nocache: False}` with key `JID` but `load` will not be in the doc yet as save_load has not been called. This order of execution ( prep_jid > get_load > save_load) is seen in `utils.job.store_job`
https://github.com/saltstack/salt/blob/b4ca024e44353bb9b5cc5e73d7de6db27a85ed80/salt/utils/job.py#L55-L57
https://github.com/saltstack/salt/blob/b4ca024e44353bb9b5cc5e73d7de6db27a85ed80/salt/utils/job.py#L104-L105

### Setup
 `master_job_cache: couchbase` in master configs

### Steps to Reproduce Issue
1) Fix the following lines and replace `'get_load'` with `getfstr`
https://github.com/saltstack/salt/blob/b4ca024e44353bb9b5cc5e73d7de6db27a85ed80/salt/utils/job.py#L103
This is so that `get_load` gets called while trying to `save_load` (Issue #43453)
2) Fire a runner `test.stdout_print`
3) Lookup the return for the runner just fired. `salt-run jobs.lookup_jid <runner_jid>`
Observe `KeyError`

### Versions Report
Salt 2016.11.07

**Comment by kunal-bajpai** [comment]
```
$ sudo salt-run test.stdout_print
foo
bar
[ERROR   ] An un-handled exception was caught by salt's global exception handler:                                                                                                                                               [3/4774]
KeyError: 'load'
Traceback (most recent call last):
  File ".bootstrap/_pex/pex.py", line 360, in execute
    self._wrap_coverage(self._wrap_profiling, self._execute)
  File ".bootstrap/_pex/pex.py", line 288, in _wrap_coverage
    runner(*args)
  File ".bootstrap/_pex/pex.py", line 320, in _wrap_profiling
    runner(*args)
  File ".bootstrap/_pex/pex.py", line 406, in _execute
    return self.execute_interpreter()
  File ".bootstrap/_pex/pex.py", line 416, in execute_interpreter
    self.execute_content(name, content)
  File ".bootstrap/_pex/pex.py", line 446, in execute_content
    exec_function(ast, globals())
  File "<exec_function>", line 4, in exec_function
  File "/usr/bin/salt-run", line 10, in <module>
    salt_run()
  File "/root/.pex/install/salt-2016.11.7-py2-none-any.whl.249b465ff64d91b2728e6ba08207c57bb133c22f/salt-2016.11.7-py2-none-any.whl/salt/scripts.py", line 391, in salt_run
    client.run()
  File "/root/.pex/install/salt-2016.11.7-py2-none-any.whl.249b465ff64d91b2728e6ba08207c57bb133c22f/salt-2016.11.7-py2-none-any.whl/salt/cli/run.py", line 41, in run
    ret = runner.run()
  File "/root/.pex/install/salt-2016.11.7-py2-none-any.whl.249b465ff64d91b2728e6ba08207c57bb133c22f/salt-2016.11.7-py2-none-any.whl/salt/runner.py", line 260, in run
    daemonize=False)
  File "/root/.pex/install/salt-2016.11.7-py2-none-any.whl.249b465ff64d91b2728e6ba08207c57bb133c22f/salt-2016.11.7-py2-none-any.whl/salt/client/mixins.py", line 479, in _proc_function
    return self.low(fun, low, full_return=False)
  File "/root/.pex/install/salt-2016.11.7-py2-none-any.whl.249b465ff64d91b2728e6ba08207c57bb133c22f/salt-2016.11.7-py2-none-any.whl/salt/client/mixins.py", line 253, in low
    return self._low(fun, low, print_event=print_event, full_return=full_return)
  File "/root/.pex/install/salt-2016.11.7-py2-none-any.whl.249b465ff64d91b2728e6ba08207c57bb133c22f/salt-2016.11.7-py2-none-any.whl/salt/client/mixins.py", line 424, in _low
    mminion=self.mminion,
  File "/root/.pex/install/salt-2016.11.7-py2-none-any.whl.249b465ff64d91b2728e6ba08207c57bb133c22f/salt-2016.11.7-py2-none-any.whl/salt/utils/job.py", line 94, in store_job
    and not mminion.returners[getfstr](load.get('jid', '')):
  File "/root/.pex/install/salt-2016.11.7-py2-none-any.whl.249b465ff64d91b2728e6ba08207c57bb133c22f/salt-2016.11.7-py2-none-any.whl/salt/returners/couchbase_return.py", line 266, in get_load
    ret = jid_doc.value['load']
KeyError: 'load'
Traceback (most recent call last):
  File ".bootstrap/_pex/pex.py", line 360, in execute
  File ".bootstrap/_pex/pex.py", line 288, in _wrap_coverage
  File ".bootstrap/_pex/pex.py", line 320, in _wrap_profiling
  File ".bootstrap/_pex/pex.py", line 406, in _execute
  File ".bootstrap/_pex/pex.py", line 416, in execute_interpreter
  File ".bootstrap/_pex/pex.py", line 446, in execute_content
  File "<exec_function>", line 4, in exec_function
  File "/usr/bin/salt-run", line 10, in <module>
    salt_run()
  File "/root/.pex/install/salt-2016.11.7-py2-none-any.whl.249b465ff64d91b2728e6ba08207c57bb133c22f/salt-2016.11.7-py2-none-any.whl/salt/scripts.py", line 391, in salt_run
    client.run()
  File "/root/.pex/install/salt-2016.11.7-py2-none-any.whl.249b465ff64d91b2728e6ba08207c57bb133c22f/salt-2016.11.7-py2-none-any.whl/salt/cli/run.py", line 41, in run
    ret = runner.run()
  File "/root/.pex/install/salt-2016.11.7-py2-none-any.whl.249b465ff64d91b2728e6ba08207c57bb133c22f/salt-2016.11.7-py2-none-any.whl/salt/runner.py", line 260, in run
    daemonize=False)
  File "/root/.pex/install/salt-2016.11.7-py2-none-any.whl.249b465ff64d91b2728e6ba08207c57bb133c22f/salt-2016.11.7-py2-none-any.whl/salt/client/mixins.py", line 479, in _proc_function
    return self.low(fun, low, full_return=False)
  File "/root/.pex/install/salt-2016.11.7-py2-none-any.whl.249b465ff64d91b2728e6ba08207c57bb133c22f/salt-2016.11.7-py2-none-any.whl/salt/client/mixins.py", line 253, in low
    return self._low(fun, low, print_event=print_event, full_return=full_return)
  File "/root/.pex/install/salt-2016.11.7-py2-none-any.whl.249b465ff64d91b2728e6ba08207c57bb133c22f/salt-2016.11.7-py2-none-any.whl/salt/client/mixins.py", line 424, in _low
    mminion=self.mminion,
  File "/root/.pex/install/salt-2016.11.7-py2-none-any.whl.249b465ff64d91b2728e6ba08207c57bb133c22f/salt-2016.11.7-py2-none-any.whl/salt/utils/job.py", line 94, in store_job
    and not mminion.returners[getfstr](load.get('jid', '')):
  File "/root/.pex/install/salt-2016.11.7-py2-none-any.whl.249b465ff64d91b2728e6ba08207c57bb133c22f/salt-2016.11.7-py2-none-any.whl/salt/returners/couchbase_return.py", line 266, in get_load
    ret = jid_doc.value['load']
KeyError: 'load'
```

**Comment by garethgreenaway** [comment]
@kunal-bajpai Thanks for the report.  Does the PR on your other reported issue also address this issue?

**Comment by kunal-bajpai** [comment]
@garethgreenaway No that PR does not address this issue. I was waiting for a confirmation on the issue since the PR will require some refactoring of the couchbase returner. I will open a PR for this soon.

**Comment by garethgreenaway** [comment]
@kunal-bajpai Thanks!
