### ISSUE TITLE
__generated_syspaths.HOME_DIR - 'module' object has no attribute 'HOME_DIR'

### ISSUE THREAD

**Issue by epcim** [saltstack/salt#43562]
### Description of Issue/Question

```
root@cfg01:/home/kitchen# service salt-master restart
 * Restarting salt master control daemon salt-master                                      
Traceback (most recent call last):
  File "/usr/bin/salt-master", line 22, in <module>
    salt_master()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 90, in salt_master
    import salt.cli.daemons
  File "/usr/lib/python2.7/dist-packages/salt/cli/daemons.py", line 43, in <module>
    from salt.utils import migrations
  File "/usr/lib/python2.7/dist-packages/salt/utils/migrations.py", line 12, in <module>
    import salt.syspaths as syspaths
  File "/usr/lib/python2.7/dist-packages/salt/syspaths.py", line 142, in <module>
    HOME_DIR = __generated_syspaths.HOME_DIR
AttributeError: 'module' object has no attribute 'HOME_DIR'

````

### Setup
As of today, bootstrap script to install "git develop" verson

### Versions Report
```root@cfg01:/home/kitchen# salt --versions-report
Salt Version:
           Salt: 2017.7.0-584-gc1ca1c4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.4.0-93-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by s0undt3ch** [comment]
The fix is [here](https://github.com/saltstack/salt/pull/43515)

**Comment by s0undt3ch** [comment]
Develop should be fixed now. The PR was merged.
