### ISSUE TITLE
ldap.managed broken on Centos6 with current update from saltstack

### ISSUE THREAD

**Issue by mowgli** [saltstack/salt#43745]
### Description of Issue/Question
Since the last update I did (2017-09-05) I encounter the following error with an ldap.managed. The version from 2017-08-01 did work properly.

### Setup
```yaml
ldap_databases:
  ldap.managed:
    - name: ldapi:///
    - connect_spec:
        bind:
          method: sasl
          mechanism: EXTERNAL
    - entries:
      - 'olcDatabase={1}monitor,cn=config':
…
```

### Steps to Reproduce Issue
Just apply the above recipe in the setup below and enjoy the following error.
```
          ID: ldap_databases
    Function: ldap.managed
        Name: ldapi:///
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1837, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1794, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/ldap.py", line 250, in managed
                  connect = __salt__['ldap3.connect']
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1113, in __getitem__
                  func = super(LazyLoader, self).__getitem__(item)
                File "/usr/lib/python2.7/site-packages/salt/utils/lazy.py", line 98, in __getitem__
                  return self._dict[key]
              KeyError: 'ldap3.connect'
```

### Versions Report
```
~> salt-minion -V    
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jul 12 2017, 17:32:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.9 Final
         locale: ISO-8859-1
        machine: x86_64
        release: 2.6.32-696.6.3.el6.x86_64
         system: Linux
        version: CentOS 6.9 Final
```

Saltstack and python dependencies are installed from repo.saltstack.com.

**Comment by garethgreenaway** [comment]
@mowgli It appears that you might not have the python-ldap library installed.  Can you confirm that it is available?

**Comment by mowgli** [comment]
```
~> rpm -qa | grep ldap
…
python-ldap-2.3.10-1.el6.x86_64
…
```

**Comment by jryberg** [comment]
This is a degradation of Salt due to the move to Python 2.7

The best option is to use older salt minions that stills run Python 2.6

For more info see: https://github.com/saltstack/salt/issues/42979
