### ISSUE TITLE
ini_manage exception when nothing changes

### ISSUE THREAD

**Issue by cheribral** [saltstack/salt#43851]
When using the following state:
```
auth_type:
  ini.options_present:
    - name: /path/to/file
    - sections:
        pgbouncer:
          auth_type: something
          auth_file: /another/path
```
Everything works fine when there is a change to make.  On the next run, however, when there is nothing to change, it throws an exception:
```
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1837, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1794, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/ini_manage.py", line 90, in options_present
                  __salt__['ini.set_option'](name, {section_name: section_body}, separator)[section_name])
              KeyError: 'pgbouncer'
```

This is running salt-minion-2017.7.1-1.el7.noarch

```
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.2.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

**Comment by cheribral** [comment]
A super quick hack to fix it in the meantime:
```
--- /usr/lib/python2.7/site-packages/salt/states/ini_manage.py 21:57:31.965532935 +0000
+++ -   2017-10-01 21:58:20.288439842 +0000
@@ -87,7 +87,9 @@
                         changes[section_name].update({key_to_remove: {'before': orig_value,
                                                                       'after': None}})
                 changes[section_name].update(
-                    __salt__['ini.set_option'](name, {section_name: section_body}, separator)[section_name])
+                    __salt__['ini.set_option'](name, {section_name: section_body}, separator))
+                if len(changes[section_name]) == 0:
+                    del changes[section_name]
         else:
             changes = __salt__['ini.set_option'](name, sections, separator)
     except IOError as err:
```

**Comment by gtmanfred** [comment]
If you change this to

```
if not changes[section_name]:
```

Would you mind submitting a PR for this to the 2017.7 branch?

Thanks,
Daniel

**Comment by cheribral** [comment]
Just went to try that, and it looks like the change is already made :)  Cheers!

**Comment by gtmanfred** [comment]
Cool, I am going to close this then.

Thanks,
Daniel
