### ISSUE TITLE
Codec can't encode character u'\xfc'

### ISSUE THREAD

**Issue by tobias-kuendig** [saltstack/salt#43856]
I am trying to run a masterless local `salt-call` under Windows 10. Unfortunately salt doesn't even begin to process the states. It just gives me the errors shown below.

Could it be that salt has a problem with my username that contains the `ü` character? I have no idea where to start debugging - I got lost in the stack trace pretty quickly. 

I cannot update to the latest minion since the `chocolatey` support is broken there and I need it to provision Windows clients.

Any help is greatly appreciated.

### Salt-call output
```
C:\Users\UsernameWithÜ> salt-call --local state.apply -l debug

[DEBUG   ] Missing configuration file: C:\salt\conf\minon
[DEBUG   ] Including configuration from 'C:\salt\conf\minion.d\redacted.conf'
[DEBUG   ] Reading configuration from C:\salt\conf\minion.d\redacted.conf
[DEBUG   ] Using cached minion ID from c:\salt\conf\minion_id: Redacted
[ERROR   ] 'ascii' codec can't encode character u'\xfc' in position 30: ordinal not in range(128)
Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\utils\parsers.py", line 200, in parse_args
    process_option_func()
  File "C:\salt\bin\lib\site-packages\salt\utils\parsers.py", line 520, in process_config_dir
    self.config.update(self.setup_config())
  File "C:\salt\bin\lib\site-packages\salt\utils\parsers.py", line 2577, in setup_config
    cache_minion_id=True)
  File "C:\salt\bin\lib\site-packages\salt\config\__init__.py", line 1986, in minion_config
    _validate_opts(opts)
  File "C:\salt\bin\lib\site-packages\salt\config\__init__.py", line 1656, in _validate_opts
    VALID_OPTS[key].__name__)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 30: ordinal not in range(128)
Usage: salt-call [options] <function> [arguments]

salt-call: error: Error while processing <bound method SaltCall.process_config_dir of <salt.cli.call.SaltCall object at 0x0000000002C1E8D0>>: Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\utils\parsers.py", line 200, in parse_args
    process_option_func()
  File "C:\salt\bin\lib\site-packages\salt\utils\parsers.py", line 520, in process_config_dir
    self.config.update(self.setup_config())
  File "C:\salt\bin\lib\site-packages\salt\utils\parsers.py", line 2577, in setup_config
    cache_minion_id=True)
  File "C:\salt\bin\lib\site-packages\salt\config\__init__.py", line 1986, in minion_config
    _validate_opts(opts)
  File "C:\salt\bin\lib\site-packages\salt\config\__init__.py", line 1656, in _validate_opts
    VALID_OPTS[key].__name__)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 30: ordinal not in range(128)
```

### Versions Report

```
Salt Version:
           Salt: 2016.11.4

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 7.1.0
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 2.0.8
          ioflo: 1.5.5
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 16.0.1
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.4.1
            ZMQ: 4.1.6

System Versions:
           dist:
        machine: AMD64
        release: 10
         system: Windows
        version: 10 10.0.15063  Multiprocessor Free
```

**Comment by damon-atkins** [comment]
You need to remove  "`ü`"   Their is only partial Unicode support in Salt with python 2.7 and maybe Python 3 might help.
```
>>> print  u'\xfc'
ü
```

**Comment by tobias-kuendig** [comment]
I have created a new user without the `ü` in the username and it works. It's a pitty that Unicode support is lacking...
