### ISSUE TITLE
Develop branch - Salt-call commands on Windows minion throws Traceback

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#43867]
Testing PR #43649, I get error/traceback when running salt-call commands.
All the new installer setup instructions/selections from that PR seems to work fine.

On py2:
```
[root@li985-150 ~]# salt \* cmd.run "C://salt/salt-call --local sys.doc none"
win:
    [ERROR   ] Command 'Get-WmiObject -class MSFC_FibrePortHBAAttributes -namespace "root\WMI" | Select -Expandproperty Attributes | %{($_.PortWWN | % {"{0:x2}" -f $_}) -join ""} | ConvertTo-JSON' failed with return code: 1
    [ERROR   ] output: Get-WmiObject : Not supported 
    
    At line:1 char:1
    
    + Get-WmiObject -class MSFC_FibrePortHBAAttributes -namespace "root\WMI ...
    
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    
        + CategoryInfo          : InvalidOperation: (:) [Get-WmiObject], Managemen 
    
       tException
    
        + FullyQualifiedErrorId : GetWMIManagementException,Microsoft.PowerShell.C 
    
       ommands.GetWmiObjectCommand
    [ERROR   ] Error converting PowerShell JSON return
    Traceback (most recent call last):
      File "C:\salt\bin\lib\site-packages\salt\modules\cmdmod.py", line 3126, in powershell
        return json.loads(response)
      File "C:\salt\bin\lib\json\__init__.py", line 339, in loads
        return _default_decoder.decode(s)
      File "C:\salt\bin\lib\json\decoder.py", line 364, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "C:\salt\bin\lib\json\decoder.py", line 382, in raw_decode
        raise ValueError("No JSON object could be decoded")
    ValueError: No JSON object could be decoded
    [ERROR   ] Pillar rendering failed for minion win: 
    Traceback (most recent call last):
      File "C:\salt\bin\lib\site-packages\salt\pillar\__init__.py", line 515, in get_tops
        saltenv
      File "C:\salt\bin\lib\site-packages\salt\fileclient.py", line 194, in cache_file
        path, u'', True, saltenv, cachedir=cachedir, source_hash=source_hash)
      File "C:\salt\bin\lib\site-packages\salt\fileclient.py", line 513, in get_url
        result = self.get_file(url, dest, makedirs, saltenv, cachedir=cachedir)
      File "C:\salt\bin\lib\site-packages\salt\fileclient.py", line 871, in get_file
        path = self._check_proto(path)
      File "C:\salt\bin\lib\site-packages\salt\fileclient.py", line 113, in _check_proto
        file_path, saltenv = salt.utils.url.parse(path)
      File "C:\salt\bin\lib\site-packages\salt\utils\url.py", line 38, in parse
        path = salt.utils.sanitize_win_path_string(path)
      File "C:\salt\bin\lib\site-packages\salt\utils\__init__.py", line 1259, in sanitize_win_path_string
        winpath = winpath.translate(trantab)
    TypeError: character mapping must return integer, None or unicode
    [CRITICAL] Pillar render error: Rendering Primary Top file failed, render error:
    character mapping must return integer, None or unicode
    [WARNING ] C:\salt\bin\lib\site-packages\salt\utils\__init__.py:2640: DeprecationWarning: Use of 'salt.utils.is_proxy' detected. This function has been moved to 'salt.utils.platform.is_proxy' as of Salt Oxygen. This warning will be removed in Salt Neon.
    
    [WARNING ] C:\salt\bin\lib\site-packages\salt\utils\__init__.py:3094: DeprecationWarning: Use of 'salt.utils.version_cmp' detected. This function has been moved to 'salt.utils.versions.version_cmp' as of Salt Oxygen. This warning will be removed in Salt Neon.
    
    [WARNING ] C:\salt\bin\lib\site-packages\salt\modules\win_update.py:92: DeprecationWarning: The 'win_update' module is being deprecated and will be removed in Salt Fluorine (Unreleased). Please use the 'win_wua' module instead.
    
    local:
        ----------
```

On py3:
```
salt fro* cmd.run "C://salt/salt-call --local sys.doc none" -t 60
frodewin2016py3_2.c7.saltstack.net:
    [ERROR   ] Command 'Get-WmiObject -class MSFC_FibrePortHBAAttributes -namespace "root\WMI" | Select -Expandproperty Attributes | %{($_.PortWWN | % {"{0:x2}" -f $_}) -join ""} | ConvertTo-JSON' failed with return code: 1
    [ERROR   ] output: Get-WmiObject : Not supported 
    
    At line:1 char:1
    
    + Get-WmiObject -class MSFC_FibrePortHBAAttributes -namespace "root\WMI ...
    
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    
        + CategoryInfo          : InvalidOperation: (:) [Get-WmiObject], Managemen 
    
       tException
    
        + FullyQualifiedErrorId : GetWMIManagementException,Microsoft.PowerShell.C 
    
       ommands.GetWmiObjectCommand
    [ERROR   ] Error converting PowerShell JSON return
    Traceback (most recent call last):
      File "C:\salt\bin\lib\site-packages\salt\modules\cmdmod.py", line 3126, in powershell
        return json.loads(response)
      File "C:\salt\bin\lib\json\__init__.py", line 319, in loads
        return _default_decoder.decode(s)
      File "C:\salt\bin\lib\json\decoder.py", line 339, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "C:\salt\bin\lib\json\decoder.py", line 357, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    [WARNING ] C:\salt\bin\lib\site-packages\salt\utils\__init__.py:2640: DeprecationWarning: Use of 'salt.utils.is_proxy' detected. This function has been moved to 'salt.utils.platform.is_proxy' as of Salt Oxygen. This warning will be removed in Salt Neon.
    
    [WARNING ] C:\salt\bin\lib\site-packages\salt\utils\__init__.py:3094: DeprecationWarning: Use of 'salt.utils.version_cmp' detected. This function has been moved to 'salt.utils.versions.version_cmp' as of Salt Oxygen. This warning will be removed in Salt Neon.
    
    [WARNING ] C:\salt\bin\lib\site-packages\salt\modules\win_update.py:92: DeprecationWarning: The 'win_update' module is being deprecated and will be removed in Salt Fluorine (Unreleased). Please use the 'win_wua' module instead.
    
    local:
        ----------
```

### Versions Report
```
    Salt Version:
               Salt: 2017.7.0-652-gcc0210f
     
    Dependency Versions:
               cffi: 1.10.0
           cherrypy: 10.2.1
           dateutil: 2.6.0
          docker-py: Not Installed
              gitdb: 2.0.3
          gitpython: 2.1.3
              ioflo: Not Installed
             Jinja2: 2.9.6
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: 1.0.6
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.17
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
       python-gnupg: 0.4.0
             PyYAML: 3.12
              PyZMQ: 16.0.2
               RAET: Not Installed
              smmap: 2.0.3
            timelib: 0.2.4
            Tornado: 4.5.1
                ZMQ: 4.1.6
     
    System Versions:
               dist:   
             locale: cp1252
            machine: AMD64
            release: 2016Server
             system: Windows
            version: 2016Server 10.0.14393 SP0 Multiprocessor Free
```

**Comment by Ch3LL** [comment]
ping @twangboy ^^^

**Comment by frogunder** [comment]
Closing this issue, I do no longer see this error on develop branch.
