### ISSUE TITLE
Batch doesn't work with progress

### ISSUE THREAD

**Issue by bobrik** [saltstack/salt#43874]
### Description of Issue/Question

Just batch mode works:

```
$ salt --batch 1 -L myserver10,myserver12 cmd.run 'sleep 5'

Executing run on ['myserver10']

myserver10:
jid:
    20171003044601468961
retcode:
    0

Executing run on ['myserver12']

myserver12:
jid:
    20171003044606643466
retcode:
    0
```

But if you add `--progress` to it, it fails:

```
$ salt --batch 1 --progress -L myserver10,myserver12 cmd.run 'sleep 5'

Executing run on ['myserver10']

[ERROR   ] Nested output failed:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 45, in try_printout
    printout = get_printout('nested', opts)(data, **kwargs)
TypeError: output() takes exactly 2 arguments (1 given)
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: output() takes exactly 2 arguments (1 given)
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 476, in salt_main
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/salt.py", line 59, in run
    self._run_batch()
  File "/usr/lib/python2.7/dist-packages/salt/cli/salt.py", line 259, in _run_batch
    for res in batch.run():
  File "/usr/lib/python2.7/dist-packages/salt/cli/batch.py", line 266, in run
    self.opts)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 92, in display_output
    display_data = try_printout(data, out, opts, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 50, in try_printout
    printout = get_printout('raw', opts)(data, **kwargs)
TypeError: output() takes exactly 2 arguments (1 given)
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 476, in salt_main
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/salt.py", line 59, in run
    self._run_batch()
  File "/usr/lib/python2.7/dist-packages/salt/cli/salt.py", line 259, in _run_batch
    for res in batch.run():
  File "/usr/lib/python2.7/dist-packages/salt/cli/batch.py", line 266, in run
    self.opts)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 92, in display_output
    display_data = try_printout(data, out, opts, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 50, in try_printout
    printout = get_printout('raw', opts)(data, **kwargs)
TypeError: output() takes exactly 2 arguments (1 given)
```

If you just want `--progress`, it works.

Moreover, salt doesn't complain if `progressbar` module is not installed, it just exits with exit code zero:

```
$ salt --progress -L myserver10,myserver12 cmd.run 'sleep 5'
$ echo $?
0
```

But with batching, progress mode and no `progressbar` installed:

```
$ salt --batch 1 --progress -L myserver10,myserver12 cmd.run 'sleep 5'

Executing run on ['myserver10']

[ERROR   ] Invalid outputter progress specified, fall back to nested
myserver10:
jid:
    20171003044840354020
retcode:
    0

Executing run on ['myserver12']

[ERROR   ] Invalid outputter progress specified, fall back to nested
myserver12:
jid:
    20171003044845508170
retcode:
    0
```

### Versions Report

```
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 19 2017, 14:48:08)
   python-gnupg: 0.3.9
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.0
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.4.44-cloudflare
         system: Linux
        version: debian 9.0
```

**Comment by Ch3LL** [comment]
Looks like i'm able to replicate this. I see this in 2016.11 branch as well so not a regression. Thanks we will need to get this fixed.
