### ISSUE TITLE
state.highstate not working on py3 setup

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#43909]
### Description of Issue/Question
On 2017.7.2 py3 setup, state.highstate fails when having this in the minion config file:
```
use_superseded:
  - module.run
```
It affects all state.highstate runs even if not using the module.run state.

It also affects 2017.7.0/7.1.

It is working correctly on a py2 setup.

I just get `minion did not return` and see this in the minion log:
```
[ERROR   ] An un-handled exception from the multiprocessing process 'SignalHandlingMultiprocessingProcess-1:10' was caught:
Traceback (most recent call last):
  File "/root/salt/salt/utils/process.py", line 663, in _run
    return self._original_run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/root/salt/salt/minion.py", line 1402, in _target
    Minion._thread_return(minion_instance, opts, data)
  File "/root/salt/salt/minion.py", line 1558, in _thread_return
    timeout=minion_instance._return_retry_timer()
  File "/root/salt/salt/minion.py", line 1734, in _return_pub
    ret_val = self._send_req_sync(load, timeout=timeout)
  File "/root/salt/salt/minion.py", line 1239, in _send_req_sync
    return channel.send(load, timeout=timeout)
  File "/root/salt/salt/utils/async.py", line 75, in wrap
    ret = self._block_future(ret)
  File "/root/salt/salt/utils/async.py", line 85, in _block_future
    return future.result()
  File "/usr/local/lib/python3.5/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/root/salt/salt/transport/zeromq.py", line 271, in send
    ret = yield self._crypted_transfer(load, tries=tries, timeout=timeout, raw=raw)
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/local/lib/python3.5/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/root/salt/salt/transport/zeromq.py", line 239, in _crypted_transfer
    ret = yield _do_transfer()
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/local/lib/python3.5/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 307, in wrapper
    yielded = next(result)
  File "/root/salt/salt/transport/zeromq.py", line 221, in _do_transfer
    self._package_load(self.auth.crypticle.dumps(load)),
  File "/root/salt/salt/crypt.py", line 1304, in dumps
    return self.encrypt(self.PICKLE_PAD + self.serial.dumps(obj))
  File "/root/salt/salt/payload.py", line 181, in dumps
    return msgpack.dumps(msg, use_bin_type=use_bin_type)
  File "/usr/local/lib/python3.5/dist-packages/msgpack/__init__.py", line 47, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 231, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:3661)
  File "msgpack/_packer.pyx", line 233, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:3503)
  File "msgpack/_packer.pyx", line 192, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:2657)
  File "msgpack/_packer.pyx", line 192, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:2657)
  File "msgpack/_packer.pyx", line 192, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:2657)
  File "msgpack/_packer.pyx", line 228, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:3382)
TypeError: can't serialize dict_keys(['test.echo'])
Process SignalHandlingMultiprocessingProcess-1:10:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/root/salt/salt/utils/process.py", line 663, in _run
    return self._original_run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/root/salt/salt/minion.py", line 1402, in _target
    Minion._thread_return(minion_instance, opts, data)
  File "/root/salt/salt/minion.py", line 1558, in _thread_return
    timeout=minion_instance._return_retry_timer()
  File "/root/salt/salt/minion.py", line 1734, in _return_pub
    ret_val = self._send_req_sync(load, timeout=timeout)
  File "/root/salt/salt/minion.py", line 1239, in _send_req_sync
    return channel.send(load, timeout=timeout)
  File "/root/salt/salt/utils/async.py", line 75, in wrap
    ret = self._block_future(ret)
  File "/root/salt/salt/utils/async.py", line 85, in _block_future
    return future.result()
  File "/usr/local/lib/python3.5/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/root/salt/salt/transport/zeromq.py", line 271, in send
    ret = yield self._crypted_transfer(load, tries=tries, timeout=timeout, raw=raw)
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/local/lib/python3.5/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/root/salt/salt/transport/zeromq.py", line 239, in _crypted_transfer
    ret = yield _do_transfer()
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/local/lib/python3.5/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 307, in wrapper
    yielded = next(result)
  File "/root/salt/salt/transport/zeromq.py", line 221, in _do_transfer
    self._package_load(self.auth.crypticle.dumps(load)),
  File "/root/salt/salt/crypt.py", line 1304, in dumps
    return self.encrypt(self.PICKLE_PAD + self.serial.dumps(obj))
  File "/root/salt/salt/payload.py", line 181, in dumps
    return msgpack.dumps(msg, use_bin_type=use_bin_type)
  File "/usr/local/lib/python3.5/dist-packages/msgpack/__init__.py", line 47, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 231, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:3661)
  File "msgpack/_packer.pyx", line 233, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:3503)
  File "msgpack/_packer.pyx", line 192, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:2657)
  File "msgpack/_packer.pyx", line 192, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:2657)
  File "msgpack/_packer.pyx", line 192, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:2657)
  File "msgpack/_packer.pyx", line 228, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:3382)
TypeError: can't serialize dict_keys(['test.echo'])
```

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.2 (default, Sep 14 2017, 22:51:06)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.1.6
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.9.36-x86_64-linode85
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by Ch3LL** [comment]
also impacts state.apply and state.sls

**Comment by terminalmage** [comment]
Fixed in https://github.com/saltstack/salt/pull/43910
