### ISSUE TITLE
[salt-ssh] Fails when targeting Ubuntu 12

### ISSUE THREAD

**Issue by rossengeorgiev** [saltstack/salt#43904]
### Description of Issue/Question
`salt-ssh` fails when targeting Ubuntu 12

### Setup
Have Ubuntu 16.04 with salt-ssh installed and a target host on Ubuntu 12.04

### Steps to Reproduce Issue
Run `salt-ssh -i --user=vagrant --askpass 'ubuntu12.local' grains.item osfinger`

```bash
[DEBUG   ] Executed SHIM command. Command logged to TRACE
[DEBUG   ] Child Forked! PID: 9020  STDOUT_FD: 10  STDERR_FD: 12
[DEBUG   ] VT: Salt-SSH SHIM Terminal Command executed. Logged to TRACE
[DEBUG   ] LazyLoaded nested.output
ubuntu12.local:
    ----------
    retcode:
        0
    stderr:
        Traceback (most recent call last):
          File "/var/tmp/.vagrant_de806d_salt/salt-call", line 15, in <module>
            salt_call()
          File "/var/tmp/.vagrant_de806d_salt/py2/salt/scripts.py", line 386, in salt_call
            import salt.cli.call
          File "/var/tmp/.vagrant_de806d_salt/py2/salt/cli/call.py", line 6, in <module>
            from salt.utils import parsers
          File "/var/tmp/.vagrant_de806d_salt/py2/salt/utils/parsers.py", line 28, in <module>
            import salt.config as config
          File "/var/tmp/.vagrant_de806d_salt/py2/salt/config/__init__.py", line 100, in <module>
            _DFLT_IPC_WBUFFER = _gather_buffer_space() * .5
          File "/var/tmp/.vagrant_de806d_salt/py2/salt/config/__init__.py", line 90, in _gather_buffer_space
            import salt.grains.core
          File "/var/tmp/.vagrant_de806d_salt/py2/salt/grains/core.py", line 47, in <module>
            import salt.utils.dns
          File "/var/tmp/.vagrant_de806d_salt/py2/salt/utils/dns.py", line 28, in <module>
            import salt.modules.cmdmod
          File "/var/tmp/.vagrant_de806d_salt/py2/salt/modules/cmdmod.py", line 34, in <module>
            import salt.utils.templates
          File "/var/tmp/.vagrant_de806d_salt/py2/salt/utils/templates.py", line 31, in <module>
            import salt.utils.http
          File "/var/tmp/.vagrant_de806d_salt/py2/salt/utils/http.py", line 41, in <module>
            import salt.loader
          File "/var/tmp/.vagrant_de806d_salt/py2/salt/loader.py", line 26, in <module>
            import salt.utils.event
          File "/var/tmp/.vagrant_de806d_salt/py2/salt/utils/event.py", line 70, in <module>
            import tornado.iostream
          File "/var/tmp/.vagrant_de806d_salt/py2/tornado/iostream.py", line 40, in <module>
            from tornado.netutil import ssl_wrap_socket, ssl_match_hostname, SSLCertificateError, _client_ssl_defaults, _server_ssl_defaults
          File "/var/tmp/.vagrant_de806d_salt/py2/tornado/netutil.py", line 49, in <module>
            import backports.ssl_match_hostname
        ImportError: No module named backports.ssl_match_hostname
    stdout:
```

### Versions Report
Issue also exists on `2016.11.7`

```yaml
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-92-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by garethgreenaway** [comment]
@rossengeorgiev Thanks for the report.  You're seeing that error because the Tornado python libraries, which Salt uses extensively, are relying on the `backports` module which is not available in Ubuntu 12.04.  Unfortunately Ubuntu 12.04 was also marked as `end of life` earlier this year so it's no longer supported by SaltStack.

**Comment by rossengeorgiev** [comment]
Hi @garethgreenaway, thanks. I should be able to work around this by installing the package form the salt repo, right?

**Comment by garethgreenaway** [comment]
@rossengeorgiev If you can find that package then yes, you might be able to work around the issue.  It's not a Salt maintained package however so it might not be available for 12.04.

**Comment by rossengeorgiev** [comment]
@garethgreenaway I see it here: http://repo.saltstack.com/apt/ubuntu/12.04/amd64/latest/

**Comment by rossengeorgiev** [comment]
This seems to work:

```bash
$ salt-ssh -i 'ubuntu12*' -r 'wget -O .pyssl.deb http://repo.saltstack.com/apt/ubuntu/12.04/amd64/latest/python-backports.ssl-match-hostname_3.4.0.2-1_all.deb; sudo dpkg -i .pyssl.deb; rm .pyssl.deb'
...
$ salt-ssh -i 'ubuntu12*' test.ping
ubuntu12:
    True

**Comment by garethgreenaway** [comment]
@rossengeorgiev Good find!
