### ISSUE TITLE
subset argument does not work with saltmod.state

### ISSUE THREAD

**Issue by mwerickso** [saltstack/salt#43918]
### Description of Issue/Question
I am trying to target a subset of minions when calling a state from an orchestrate state. However, no matter how many ways of formatting the subset argument, it returns the same error.

### Setup
I have the following orchestrate state:
```
{% set cronjob = salt['pillar.get']('cronjob', False) %}
call_cron_jobs:
  salt.state:
    - tgt: '*web*'
    - sls: my.state
    - pillar: 
        cronjob: {{ cronjob }}
    - subset: 1
```
When I run it, it returns this error:
```
          ID: call_cron_jobs
    Function: salt.state
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1837, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1794, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/saltmod.py", line 274, in state
                  cmd_ret = __salt__['saltutil.cmd'](tgt, fun, **cmd_kw)
                File "/usr/lib/python2.7/dist-packages/salt/modules/saltutil.py", line 1322, in cmd
                  client, tgt, fun, arg, timeout, tgt_type, ret, kwarg, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/saltutil.py", line 1286, in _exec
                  for ret_comp in _cmd(**cmd_kwargs):
                File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 495, in cmd_subset
                  **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 734, in cmd
                  **kwargs):
                File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 1585, in get_cli_event_returns
                  **kwargs
              TypeError: get_iter_returns() got multiple values for keyword argument 'expect_minions'
     Started: 23:23:39.760949
    Duration: 118.859 ms
     Changes:
```

### Steps to Reproduce Issue
The state runs perfectly fine if I have it without the subset, like this:
```
{% set cronjob = salt['pillar.get']('cronjob', False) %}
call_cron_jobs:
  salt.state:
    - tgt: '*web*'
    - sls: my.state
    - pillar: 
        cronjob: {{ cronjob }}
```
I can also run the state just fine from the command line by calling:
`salt '*web*' state.apply my.state pillar='{"cronjob":"run_next_feed"}' --subset=1`

### Versions Report
```
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-96-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by gtmanfred** [comment]
This should be fixed by https://github.com/saltstack/salt/pull/43933

Thanks for reporting
Daniel

**Comment by mwerickso** [comment]
@gtmanfred Thanks for your prompt help. I implemented the fix from #43933 on my salt-master, restarted the service and attempted to run the orchestrate state again, but the same set of errors as described above appears. It does not appear to be resolved.

**Comment by gtmanfred** [comment]
Bah, that is because i forgot to make expect_minion plural, i switched it to expect_minions and it should work now.

Thanks,
Daniel

**Comment by mwerickso** [comment]
@gtmanfred  Ah no worries, I obviously did not catch it either haha. I implemented the change, restarted the service and ran the state again. This time, it ran the state (i verified the end cron job actually processed) but it still returned an error and failed.

```
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1837, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1794, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/saltmod.py", line 274, in state
                  cmd_ret = __salt__['saltutil.cmd'](tgt, fun, **cmd_kw)
                File "/usr/lib/python2.7/dist-packages/salt/modules/saltutil.py", line 1322, in cmd
                  client, tgt, fun, arg, timeout, tgt_type, ret, kwarg, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/saltutil.py", line 1287, in _exec
                  fcn_ret.update(ret_comp)
              ValueError: dictionary update sequence element #0 has length 1; 2 is required
```
ideas?

**Comment by gtmanfred** [comment]
I added another patch that fixes this issue, but using the cmd_cli function in salt.client

**Comment by mwerickso** [comment]
@gtmanfred I applied the new change for cmd_cli and the state now runs without any errors. I really appreciate your help in this!

**Comment by mwerickso** [comment]
@gtmanfred I noticed while running `salt-master -l debug` that I get the following errors:
```
[ERROR   ] Unhandled exception running state.orchestrate
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/schedule.py", line 846, in handle_func
    ret['return'] = self.functions[func](*args, **kwargs)
TypeError: orchestrate() argument after ** must be a mapping, not list
```
but no errors show up itself.

**Comment by mwerickso** [comment]
nervermind, that is because of my schedule calling the orchestrate state. I realize this is wrong (and unrelated to this post) but I cannot find a fix from searching for it

schedule example:
```
schedule:

  email_queue:
    function: state.orchestrate
    jid_include: true
    args:
      - orch.execute_cron
    kwargs:
      pillar='{"cronjob":"email_queue"}'
    cron: '* * * * *'
```
and in the orch.execute_cron state I am trying to pull the temp pillar like this:
```
{% set cronjob = salt['pillar.get']('cronjob', False) %}
call_cron_jobs:
  salt.state:
    - tgt: '*web*'
    - sls: my.state
    - pillar: 
        cronjob: {{ cronjob }}
    - subset: 1
```
Is there a proper way to pass the required "cronjob" data to the orch state from my schedule?

**Comment by gtmanfred** [comment]
Why isn't pillar just

```
schedule:
  email_queue:
    function: state.orchestrate
    jid_include: true
    args:
      - orch.execute_cron
    kwargs:
      pillar:
        cronjob: email_queue
    cron: '* * * * *'
```

**Comment by mwerickso** [comment]
Ah now that I see it, it makes sense. I did not know the correct format, so that is what I was looking for. Thanks, it appears to work and I no longer see the mentioned error regarding **kwargs.

**Comment by gtmanfred** [comment]
Awesome
