### ISSUE TITLE
KeyError: 'state.check_result' when salt installed from github codebase

### ISSUE THREAD

**Issue by vnitinv** [saltstack/salt#43931]
### Description of Issue/Question

While running any scheduler, we get below error when salt is installed from github (tried develop and 2017.7.1). But it works when we installed salt from PyPI.
```
[INFO    ] Completed state [system queue op table] at time 23:33:28.465780 (duration_in_ms=675.94)
[DEBUG   ] File /var/cache/salt/proxy/mx/accumulator/140481817065104 does not exist, no need to cleanup
[DEBUG   ] LazyLoaded config.option
[ERROR   ] Unhandled exception running state.apply
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/salt/utils/schedule.py", line 859, in handle_func
    ret['return'] = self.functions[func](*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/salt/modules/state.py", line 595, in apply_
    return sls(mods, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/salt/modules/state.py", line 1118, in sls
    _set_retcode(ret, high_)
  File "/usr/local/lib/python2.7/dist-packages/salt/modules/state.py", line 101, in _set_retcode
    if not __utils__['state.check_result'](ret, highstate=highstate):
  File "/usr/local/lib/python2.7/dist-packages/salt/utils/context.py", line 228, in __getitem__
    return self._dict()[key]
KeyError: 'state.check_result'
```
### Setup

# cat sch_test.sls 
```yaml
run cmd per 10 sec:
  schedule.present:
    - function: state.apply
    - job_args:
      - cmd_schedule 
    - seconds: 10 
    - splay: 10
```

### Steps to Reproduce Issue
install salt from github.

### Versions Report
salt 2017.7.0-16-gab1b099 (Nitrogen)

**Comment by gtmanfred** [comment]
Can you please provide the full --versions-report?

And also can you provide the command you are installing with?

Thanks,
Daniel

**Comment by vnitinv** [comment]
@gtmanfred find the required details

```
# salt --versions-report
Salt Version:
           Salt: 2017.7.0-16-gab1b099
 
Dependency Versions:
           cffi: 1.11.1
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.1.6
 
System Versions:
           dist: Ubuntu 14.04 trusty
         locale: UTF-8
        machine: x86_64
        release: 3.16.0-77-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```
Do not, we tested this on different Linux systems.

**Comment by vnitinv** [comment]
One more thing to note. When I am installing 2017.7.1 branch, salt version shows as
2017.7.0-16-gab1b099

is this expected?

**Comment by gtmanfred** [comment]
Yes, if you want to have the version appear as 2017.7.1, you should install from the 2017.7.1 git tag.

What command did you use to install? and what exactly are you running so that I can replicate this issue?

**Comment by vnitinv** [comment]
```pip install git+https://github.com/SaltStack/salt@2017.7.1
```

**Comment by gtmanfred** [comment]
If you are making changes to salt, they should go in the 2017.7 branch.  Since 2017.7.1 has been released, we are not going to be accepting any more pull requests to that.  Also, 2017.7.2 has been finalized.

Either way, all PRs should go into 2017.7, and then we back port them into the change branches.

https://docs.saltstack.com/en/latest/topics/development/contributing.html#dot-release-branches

I would also recommend adding `-e` so that it installs the full git repository, and you can just work out of that instead of having to go searching through /usr/lib/python2.7

**Comment by vnitinv** [comment]
Sure @gtmanfred . But this is the issue we are facing even from Develop branch, Hence should be fixed. This is a blocker for me.

**Comment by gtmanfred** [comment]
I installed the head of the 2017.7 or develop branchs, and am unable to replicate this issue.

```
[root@salt ~]# curl -Lso boot bootstrap.saltstack.com
[root@salt ~]# bash boot -ZDM git develop &>/dev/null
[root@salt ~]# salt --versions-report
Salt Version:
           Salt: 2017.7.1-4193-g865bf0f

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.4.89-boot2docker
         system: Linux
        version: CentOS Linux 7.4.1708 Core

[root@salt ~]# salt-key -Ay
The following keys are going to be accepted:
Unaccepted Keys:
salt
Key for minion salt accepted.
[root@salt ~]# mkdir /srv/salt/
[root@salt ~]# cat > /srv/salt/test.sls <<HERE
> run cmd per 10 sec:
>   schedule.present:
>     - function: state.apply
>     - job_args:
>       - cmd_schedule
>     - seconds: 10
>     - splay: 10
> HERE
[root@salt ~]# salt \* schedule.list
salt:
    ----------
    schedule:
        ----------
[root@salt ~]# salt \* state.apply test
salt:
----------
          ID: run cmd per 10 sec
    Function: schedule.present
      Result: True
     Comment: Adding new job run cmd per 10 sec to schedule
     Started: 17:03:56.619177
    Duration: 18.255 ms
     Changes:

Summary for salt
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:  18.255 ms
[root@salt ~]# salt \* schedule.list
salt:
    schedule:
      run cmd per 10 sec:
        args:
        - cmd_schedule
        enabled: true
        function: state.apply
        jid_include: true
        maxrunning: 1
        name: run cmd per 10 sec
        seconds: 10
        splay: 10
```

**Comment by vnitinv** [comment]
How your salt version shows 2017.7.1.xxxx
for me it comes to be 2017.7.0.xxxx when installed from develop
```
$ pip install git+https://github.com/saltstack/salt.git
Collecting git+https://github.com/saltstack/salt.git
  Cloning https://github.com/saltstack/salt.git to /private/var/folders/1g/y8vnrw6s2_52gw_zvf82b5w40000gn/T/pip-uaZlG5-build
Requirement already satisfied: Jinja2 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from salt===2017.7.0-670-g865bf0f)
Requirement already satisfied: msgpack-python>0.3 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from salt===2017.7.0-670-g865bf0f)
Requirement already satisfied: PyYAML in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from salt===2017.7.0-670-g865bf0f)
Requirement already satisfied: MarkupSafe in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from salt===2017.7.0-670-g865bf0f)
Requirement already satisfied: requests>=1.0.0 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from salt===2017.7.0-670-g865bf0f)
Requirement already satisfied: tornado>=4.2.1 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from salt===2017.7.0-670-g865bf0f)
Requirement already satisfied: futures>=2.0 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from salt===2017.7.0-670-g865bf0f)
Requirement already satisfied: pycrypto>=2.6.1 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from salt===2017.7.0-670-g865bf0f)
Requirement already satisfied: pyzmq>=2.2.0 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from salt===2017.7.0-670-g865bf0f)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from requests>=1.0.0->salt===2017.7.0-670-g865bf0f)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from requests>=1.0.0->salt===2017.7.0-670-g865bf0f)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from requests>=1.0.0->salt===2017.7.0-670-g865bf0f)
Requirement already satisfied: idna<2.6,>=2.5 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from requests>=1.0.0->salt===2017.7.0-670-g865bf0f)
Requirement already satisfied: backports-abc>=0.4 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from tornado>=4.2.1->salt===2017.7.0-670-g865bf0f)
Requirement already satisfied: singledispatch in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from tornado>=4.2.1->salt===2017.7.0-670-g865bf0f)
Requirement already satisfied: six in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from singledispatch->tornado>=4.2.1->salt===2017.7.0-670-g865bf0f)
Installing collected packages: salt
  Running setup.py install for salt ... done
Successfully installed salt-2017.7.0-670-g865bf0f
```

**Comment by gtmanfred** [comment]
Because bootstrap runs different commands?

I am not sure, i would highly recommend using salt bootstrap to install
instead of pip.

**Comment by vnitinv** [comment]
in PyPI code we have
```python
if not salt.utils.check_state_result(ret, highstate=highstate):
```
whereas in github we have
https://github.com/saltstack/salt/blob/develop/salt/modules/state.py#L101
```python
if not __utils__['state.check_result'](ret, highstate=highstate):
```

Will this be the cause of the issue?

**Comment by gtmanfred** [comment]
It will not, everything in salt.utils is loaded into the __utils__ dictionary.

and that module is located here https://github.com/saltstack/salt/blob/develop/salt/utils/state.py#L124

@terminalmage @rallytime yall have been working on moving utils to different files, have yall seen any issues with this one?

Thanks,
Daniel

**Comment by vnitinv** [comment]
After doing the changes in develop branch code as per what we have in PyPI, the functionality works perfectly fine. Looks like there is some sync issue. 
Do you think a pull request for this change will make sense?

**Comment by gtmanfred** [comment]
For what change?

**Comment by vnitinv** [comment]
But the error log is point to different state file under salt/modules/state.py

```
  File "/usr/local/lib/python2.7/dist-packages/salt/modules/state.py", line 101, in _set_retcode
    if not __utils__['state.check_result'](ret, highstate=highstate):
  File "/usr/local/lib/python2.7/dist-packages/salt/utils/context.py", line 228, in __getitem__
    return self._dict()[key]
```

**Comment by gtmanfred** [comment]
As you can see from my previous update. I am unable to replicate this, can you provide any more information about the setup?

https://github.com/saltstack/salt/issues/43931#issuecomment-334529073

Also, i made the cmd_schedule.sls file just to make sure you weren't seeing that error on the scheduled run.


```
2017-10-05 18:32:23,943 [salt.utils.schedule:1270][DEBUG   ][8616] schedule.handle_func: Adding splay of 8 seconds to next run.
2017-10-05 18:32:31,944 [salt.utils.schedule:1320][INFO    ][8616] Running scheduled job: run cmd per 10 sec
2017-10-05 18:32:31,945 [salt.utils.schedule:1324][DEBUG   ][8616] schedule: This job was scheduled with jid_include, adding to cache (jid_include defaults to True)
2017-10-05 18:32:31,945 [salt.utils.schedule:1328][DEBUG   ][8616] schedule: This job was scheduled with a max number of 1
2017-10-05 18:32:31,972 [salt.utils.schedule:819 ][DEBUG   ][8751] schedule.handle_func: adding this job to the jobcache with data {'fun_args': [], 'jid': '20171005183231965036', 'schedule': 'run cmd per 10 sec', 'pid': 8751, 'fun': 'state.apply', 'id': 'salt'}
2017-10-05 18:32:31,976 [salt.utils.lazy  :97  ][DEBUG   ][8751] LazyLoaded state.apply
2017-10-05 18:32:31,982 [salt.utils.lazy  :97  ][DEBUG   ][8751] LazyLoaded saltutil.is_running
2017-10-05 18:32:31,984 [salt.utils.lazy  :97  ][DEBUG   ][8751] LazyLoaded grains.get
2017-10-05 18:32:31,990 [salt.transport.zeromq:85  ][DEBUG   ][8751] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'salt', 'tcp://172.17.0.3:4506', 'aes')
2017-10-05 18:32:31,990 [salt.crypt       :378 ][DEBUG   ][8751] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'salt', 'tcp://172.17.0.3:4506')
2017-10-05 18:32:32,001 [salt.pillar      :50  ][DEBUG   ][8751] Determining pillar cache
2017-10-05 18:32:32,001 [salt.transport.zeromq:85  ][DEBUG   ][8751] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'salt', 'tcp://172.17.0.3:4506', 'aes')
2017-10-05 18:32:32,002 [salt.crypt       :378 ][DEBUG   ][8751] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'salt', 'tcp://172.17.0.3:4506')
2017-10-05 18:32:32,032 [salt.crypt       :680 ][DEBUG   ][8751] Loaded minion key: /etc/salt/pki/minion/minion.pem
2017-10-05 18:32:32,045 [salt.state       :886 ][INFO    ][8751] Loading fresh modules for state activity
2017-10-05 18:32:32,065 [salt.utils.lazy  :97  ][DEBUG   ][8751] LazyLoaded jinja.render
2017-10-05 18:32:32,066 [salt.utils.lazy  :97  ][DEBUG   ][8751] LazyLoaded yaml.render
2017-10-05 18:32:32,071 [salt.fileclient  :1077][DEBUG   ][8751] In saltenv 'base', looking at rel_path 'cmd_schedule.sls' to resolve 'salt://cmd_schedule.sls'
2017-10-05 18:32:32,071 [salt.fileclient  :1085][DEBUG   ][8751] In saltenv 'base', ** considering ** path '/var/cache/salt/minion/files/base/cmd_schedule.sls' to resolve 'salt://cmd_schedule.sls'
2017-10-05 18:32:32,071 [salt.template    :48  ][DEBUG   ][8751] compile template: /var/cache/salt/minion/files/base/cmd_schedule.sls
2017-10-05 18:32:32,072 [salt.utils.jinja :76  ][DEBUG   ][8751] Jinja search path: ['/var/cache/salt/minion/files/base']
2017-10-05 18:32:32,075 [salt.template    :26  ][PROFILE ][8751] Time (in seconds) to render '/var/cache/salt/minion/files/base/cmd_schedule.sls' using 'jinja' renderer: 0.00311708450317
2017-10-05 18:32:32,075 [salt.template    :115 ][DEBUG   ][8751] Rendered data from file: /var/cache/salt/minion/files/base/cmd_schedule.sls:
test.ping:
  module.run

2017-10-05 18:32:32,077 [salt.utils.lazy  :97  ][DEBUG   ][8751] LazyLoaded config.get
2017-10-05 18:32:32,077 [salt.loaded.int.render.yaml:76  ][DEBUG   ][8751] Results of YAML rendering:
OrderedDict([('test.ping', 'module.run')])
2017-10-05 18:32:32,077 [salt.template    :26  ][PROFILE ][8751] Time (in seconds) to render '/var/cache/salt/minion/files/base/cmd_schedule.sls' using 'yaml' renderer: 0.0018310546875
2017-10-05 18:32:32,078 [salt.utils.lazy  :97  ][DEBUG   ][8751] LazyLoaded module.run
2017-10-05 18:32:32,078 [salt.state       :1742][INFO    ][8751] Running state [test.ping] at time 18:32:32.078784
2017-10-05 18:32:32,079 [salt.state       :1775][INFO    ][8751] Executing state module.run for [test.ping]
2017-10-05 18:32:32,079 [salt.utils.decorators:613 ][WARNING ][8751] The function "module.run" is using its deprecated version and will expire in version "Sodium".
2017-10-05 18:32:32,101 [salt.utils.lazy  :97  ][DEBUG   ][8751] LazyLoaded test.ping
2017-10-05 18:32:32,101 [salt.loaded.int.module.test:118 ][DEBUG   ][8751] test.ping received for minion 'salt'
2017-10-05 18:32:32,101 [salt.state       :273 ][INFO    ][8751] {'ret': True}
2017-10-05 18:32:32,101 [salt.state       :1915][INFO    ][8751] Completed state [test.ping] at time 18:32:32.101830 duration_in_ms=23.047
2017-10-05 18:32:32,102 [salt.state       :2554][DEBUG   ][8751] File /var/cache/salt/minion/accumulator/60188048 does not exist, no need to cleanup.
2017-10-05 18:32:32,103 [salt.utils.lazy  :97  ][DEBUG   ][8751] LazyLoaded config.option
2017-10-05 18:32:32,104 [salt.utils.event :313 ][DEBUG   ][8751] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_63479ad69a_pub.ipc
2017-10-05 18:32:32,104 [salt.utils.event :316 ][DEBUG   ][8751] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_63479ad69a_pull.ipc
2017-10-05 18:32:32,104 [salt.transport.ipc:255 ][DEBUG   ][8751] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_63479ad69a_pull.ipc
2017-10-05 18:32:32,106 [salt.utils.event :728 ][DEBUG   ][8751] Sending event: tag = __schedule_return; data = {'fun_args': ['cmd_schedule'], 'jid': 'req', 'return': {'module_|-test.ping_|-test.ping_|-run': {'comment': 'Module function test.ping executed', 'name': 'test.ping', 'start_time': '18:32:32.078783', 'result': True, 'duration': 23.047, '__run_num__': 0, '__sls__': u'cmd_schedule', 'changes': {'ret': True}, '__id__': 'test.ping'}}, 'retcode': 0, 'success': True, 'schedule': 'run cmd per 10 sec', 'cmd': '_return', 'pid': 8751, '_stamp': '2017-10-05T18:32:32.106532', 'fun': 'state.apply', 'id': 'salt'}
2017-10-05 18:32:32,108 [salt.minion      :1989][DEBUG   ][8616] Minion of "salt" is handling event tag '__schedule_return'
2017-10-05 18:32:32,108 [salt.minion      :1703][INFO    ][8616] Returning information for job: req
2017-10-05 18:32:32,109 [salt.transport.zeromq:85  ][DEBUG   ][8616] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'salt', 'tcp://172.17.0.3:4506', 'aes')
2017-10-05 18:32:32,109 [salt.crypt       :386 ][DEBUG   ][8616] Re-using AsyncAuth for ('/etc/salt/pki/minion', 'salt', 'tcp://172.17.0.3:4506')
2017-10-05 18:32:32,109 [salt.utils.schedule:920 ][DEBUG   ][8751] schedule.handle_func: Removing /var/cache/salt/minion/proc/20171005183231965036
```

And the debug logs show it run correctly.

**Comment by terminalmage** [comment]
@gtmanfred The salt.utils changes happened in the release cycle after 2017.7.

This issue only seems to happen when there are stale/extra .pyc files, which you see sometimes when installing different versions from source.

**Comment by ek1m92** [comment]
I seem to be able to replicate the issue in both the original scenario (running a scheduled job using the state module) as well as in a scheduled orchestrate scenario (executing an sls on a specific minion from a scheduled state.orchestrate call using salt.state).

```
[INFO    ] Completed state [orch_test] at time 15:32:49.536854 (duration_in_ms=760.528)
[DEBUG   ] File /var/cache/salt/master/accumulator/140641057983696 does not exist, no need to cleanup
[DEBUG   ] LazyLoaded state.check_result
[ERROR   ] Unhandled exception running state.orchestrate
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/schedule.py", line 704, in handle_func
    ret['return'] = self.functions[func](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/runners/state.py", line 109, in orchestrate
    res = __utils__['state.check_result'](ret['data'])
KeyError: u'state.check_result'
```

I'm using the latest salt version `2018.3.0 (Oxygen)` running on `Ubuntu 16.04.4 LTS`. It was installed and upgraded from the official repo (`http://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest xenial main`).

Obiously, the jobs themselves execute flawlessly in the orchestrate scenario, since the utility function is only called to generate the overall result.

@terminalmage I have already tried to locate obviously outdated .pyc files but came up empty. Do you have any more suggestions?

**Comment by terminalmage** [comment]
Actually, the LazyLoader stuff is different, I found that bug in the test suite (https://github.com/saltstack/salt/pull/47710) and it does not seem to be related to your issue.

**Comment by bhperry** [comment]
I am also getting this error on the 2018.3.0 version:
```
    2018-05-25 18:09:25,767 [salt.utils.schedule:737 ][ERROR   ][4737] Unhandled exception running state.sls
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/utils/schedule.py", line 704, in handle_func
        ret['return'] = self.functions[func](*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 1296, in sls
        _set_retcode(ret, high_)
      File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 106, in _set_retcode
        if not __utils__['state.check_result'](ret, highstate=highstate):
      File "/usr/lib/python2.7/dist-packages/salt/utils/context.py", line 228, in __getitem__
        return self._dict()[key]
    KeyError: u'state.check_result'
```

Caused by a scheduled state.sls function. Anyone know how to fix this without building a custom version of salt?

**Comment by asmialoski** [comment]
Please reopen.
I am facing this issue with SALT 3000 version (in SALT-MASTER and MINION with version 3000).

**Comment by marty-macfly** [comment]
Same for me on Windows with version 3000.3:

```2020-07-13 13:21:12,259 [salt.loaded.int.module.cmdmod:397 ][INFO    ][5152] Executing command ['attrib', '-R', 'C:\\salt\\var\\cache\\sls.p'] in directory 'C:\WINDOWS\system32\config\systemprofile'
2020-07-13 13:21:12,275 [salt.utils.schedule:801 ][ERROR   ][5152] Unhandled exception running state.sls
Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt-3000.3-py3.5.egg\salt\utils\schedule.py", line 769, in handle_func
    ret['return'] = self.functions[func](*args, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt-3000.3-py3.5.egg\salt\modules\state.py", line 1369, in sls
    _set_retcode(ret, high_)
  File "c:\salt\bin\lib\site-packages\salt-3000.3-py3.5.egg\salt\modules\state.py", line 107, in _set_retcode
    if not __utils__['state.check_result'](ret, highstate=highstate):
KeyError: 'state.check_result'
```

**Comment by marty-macfly** [comment]
Just seen the comment of sagetherage in #53502 so need to refer to that one for followup and seems it will be managed in Magnesium.
