### ISSUE TITLE
[logger] [sentry] KeyError: 'SENTRY_PROJECT'

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#43949]
### Description of Issue/Question

salt-master does not start when sentry logger is configured

### Setup

config : 
```
# cat log_to_sentry.conf
sentry_handler:
  dsn: https://[snip]
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
try to start master or salt-call : 

```
salt-call: error: Error while processing <bound method SaltCall.__setup_extended_logging of <salt.cli.call.SaltCall object at 0x7f3270e93d10>>: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 212, in parse_args
    mixin_after_parsed_func(self)
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 856, in __setup_extended_logging
    log.setup_extended_logging(self.config)
  File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 738, in setup_extended_logging
    handlers = get_handlers_func()
  File "/usr/lib/python2.7/dist-packages/salt/log/handlers/sentry_mod.py", line 134, in setup_handlers
    'project': dsn_config['SENTRY_PROJECT'],
KeyError: 'SENTRY_PROJECT'
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```

 salt --versions-report
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: 2.3.0
       dateutil: 2.2
      docker-py: 0.5.3
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.9 
         locale: UTF-8
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.9 
 
```

**Comment by Ch3LL** [comment]
@arthurlogilab thanks for the PR! As this PR resolves the issue I will close this issue and we will keep the conversation to the PR. If we need to re-open this issue please let me know and I will do so. Thanks again!!
