### ISSUE TITLE
Cannot connect to remote svn file server backend

### ISSUE THREAD

**Issue by Hicks31** [saltstack/salt#43948]
### Description of Issue/Question
I can't connect to my svn repo. My problem is that there is an authentication on my svn server but i can't find on the saltstack documentation the way to configure correctly my master.

I got this error on my master's log:

> 2017-10-06 11:16:11,509 [salt.loaded.int.fileserver.svnfs][ERROR   ][28243] Failed to initialize svnfs remote 'http://mysvn/tools': callback_get_login required
> 2017-10-06 11:16:11,510 [salt.master      ][CRITICAL][28243] Failed to load svn fileserver backend
> 2017-10-06 11:16:11,510 [salt.master      ][CRITICAL][28243] Master failed pre flight checks, exiting

I can connect correctly using svn command line (no firewall issues or something).

I tried on the svnfs_remotes to use an url like http://<user>:<password>@mysvn/tools and got the same error.
I also tried to put svnfs_user / svnfs_password keyword on the master configuration like it's used for gitfs_remote but doesn't work too.

Thx for your help

### Steps to Reproduce Issue
Use a remote svn backend file server. Here's my matser configuration:

> fileserver_backend:
>   - svn
> svnfs_remotes:
>   - http://mysvn/tools  (OR http://<user>:<password>@mysvn/tools)

### Versions Report

> Salt Version:
>            Salt: 2017.7.1
> 
> Dependency Versions:
>            cffi: Not Installed
>        cherrypy: Not Installed
>        dateutil: Not Installed
>       docker-py: Not Installed
>           gitdb: Not Installed
>       gitpython: Not Installed
>           ioflo: Not Installed
>          Jinja2: 2.7.2
>         libgit2: Not Installed
>         libnacl: Not Installed
>        M2Crypto: 0.21.1
>            Mako: 0.8.1
>    msgpack-pure: Not Installed
>  msgpack-python: 0.4.8
>    mysql-python: Not Installed
>       pycparser: Not Installed
>        pycrypto: 2.6.1
>    pycryptodome: Not Installed
>          pygit2: Not Installed
>          Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
>    python-gnupg: Not Installed
>          PyYAML: 3.10
>           PyZMQ: 15.3.0
>            RAET: Not Installed
>           smmap: Not Installed
>         timelib: Not Installed
>         Tornado: 4.2.1
>             ZMQ: 4.1.4
> 
> System Versions:
>            dist: centos 7.3.1611 Core
>          locale: UTF-8
>         machine: x86_64
>         release: 3.10.0-514.el7.x86_64
>          system: Linux
>         version: CentOS Linux 7.3.1611 Core

**Comment by Hicks31** [comment]
OK i just reread the documentation:

> When using the svn fileserver backend at least one subversion remote needs to be defined. The user running the salt master will need read access to the repo.

So my question will be: is there a way to use another user than the one running the salt master? Is it a future feature for the next saltstack release?
Thx

**Comment by Ch3LL** [comment]
glancing at fileserver/svnfs.py I'm not seeing an option to specify user/passwd so I will label as a feature. We are willing to accept a PR on this if you are interested trying yourself.

**Comment by Hicks31** [comment]
I will take a look at this but i'm new to python and salt so i can't promise i will success ^^.

Anyway, i tried to bypass the authentication on my svn by allowing an "auth by ip" on svn configuration. I am able to svn checkout without using any credentials but my master is not starting. This is the error i'm getting:

2017-10-06 15:14:40,691 [salt.log.setup   ][ERROR   ][17853] An un-handled exception was caught by salt's global exception handler:
TypeError: string indices must be integers, not str
Traceback (most recent call last):
  File "/usr/bin/salt-master", line 22, in <module>
    salt_master()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 92, in salt_master
    master.start()
  File "/usr/lib/python2.7/site-packages/salt/cli/daemons.py", line 208, in start
    self.master.start()
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 524, in start
    self._pre_flight()
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 472, in _pre_flight
    fileserver.init()
  File "/usr/lib/python2.7/site-packages/salt/fileserver/__init__.py", line 501, in init
    self.servers[fstr]()
  File "/usr/lib/python2.7/site-packages/salt/fileserver/svnfs.py", line 233, in init
    repo_conf['hash'], repo_conf['url']
TypeError: string indices must be integers, not str

Is it possible to get an example from someone that use svn backend server? Actually i don't know how to make it work.

**Comment by Hicks31** [comment]
Just to help people who struggle with svn backend servers:

- We use an auth by IP on our svn (will test next week the modifications i made to svnfs.py to add login/password authentication)
- On master configuration file, if you re not using a path like "http://yoursvnserver/trunk" you should use svnfs_trunk and add the relative path to your trunk (for me it's "./"). No trunk defined -> no svn backend
- Use svnfs_mountpoint to point out where your files will be served (ex: salt://svn)
- to see if svn backend works: salt-run fileserver.update then salt-run fileserver.file_list
- to access your files in yout salt states, use source: salt://svn/path_to_your_file_on_svn_server

hope it will help. I will let you know if auth by login password is working next week

**Comment by OrangeDog** [comment]
The password feature appears to still be missing
