### ISSUE TITLE
salt-master with vrrp - minions wont reconnect

### ISSUE THREAD

**Issue by msupinodn** [saltstack/salt#43965]
### Description of Issue/Question
Some salt minions wont reconnect after failover/fail back of master

error in minion logs

2017-10-07 13:29:15,019 [salt.utils.schedule][ERROR   ][12465] Unhandled exception running state.sls
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/schedule.py", line 849, in handle_func
    ret['return'] = self.functions[func](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 1010, in sls
    mocked=kwargs.get('mock', False))
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 3535, in __init__
    loader=loader)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 662, in __init__
    self.opts['pillar'] = self._gather_pillar()
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 704, in _gather_pillar
    ret = pillar.compile_pillar()
  File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 162, in compile_pillar
    dictkey='pillar',
  File "/usr/lib/python2.7/dist-packages/salt/utils/async.py", line 75, in wrap
    ret = self._block_future(ret)
  File "/usr/lib/python2.7/dist-packages/salt/utils/async.py", line 85, in _block_future
    return future.result()
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 879, in run
    yielded = self.gen.send(value)
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 204, in crypted_transfer_decode_dictentry
    aes = cipher.decrypt(ret['key'])
TypeError: string indices must be integers, not str

restarting one of the failing minions seems to recover all minions.

errors in master logs

2017-10-07 13:29:25,052 [salt.master      ][WARNING ][30319] Salt minion claiming to be XXX attempted to communicate with master but key could not be read and verification was denied.
2017-10-07 13:29:25,053 [salt.master      ][WARNING ][30319] Minion id XXX is not who it says it is!
2017-10-07 13:29:32,880 [salt.transport.mixins.auth][ERROR   ][30317] AES key not found
2017-10-07 13:29:39,228 [salt.transport.mixins.auth][ERROR   ][30318] AES key not found
2017-10-07 13:29:39,231 [salt.transport.mixins.auth][ERROR   ][30317] AES key not found
2017-10-07 13:29:41,262 [salt.transport.mixins.auth][ERROR   ][30319] AES key not found

### Setup
Two masters, active-passive, same pem/key, virtual IP passing between them

### Steps to Reproduce Issue
setup vrrp of two masters, failover, failback, some minions wont recover

### Versions Report
Salt Version:
           Salt: 2016.11.7

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 2.6.1
      docker-py: 2.5.1
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.6

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.4.0-57-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by gtmanfred** [comment]
What is `vrrp`?

Thanks,
Daniel

**Comment by msupinodn** [comment]
https://en.wikipedia.org/wiki/Virtual_Router_Redundancy_Protocol

a method to pass a floating IP between active and passive server, 

no need for anything fancy, adding a /32 IP to eth0 on the "primary" server, let minions connect,

remove that IP from the primary and add to a secondary, which has the same master.pub/pem files

and wait for minion to reconnect, either takes long time, or prints the errors above.
