### ISSUE TITLE
Salt upgrade instructions do not work

### ISSUE THREAD

**Issue by bobrik** [saltstack/salt#44035]
### Description of Issue/Question

* https://docs.saltstack.com/en/latest/faq.html#what-is-the-best-way-to-restart-a-salt-minion-daemon-using-salt-after-upgrade

I'm trying simplest subset "upgrade salt and stater salt-minion state". We have a more complicated state, but this subset reproduces issue reliably.

This seems related to #7717.

### Setup

Start with 2017.11.4, upgrade to 2017.7.2. I use the following state:

```
{%- set versions = [
  '2016.11.4+ds-1',
  '2017.7.2+ds-1'
] %}

{%- set version = versions[1] %}

salt-minion:
  pkg.installed:
    - pkgs:
      - salt-minion: {{ version }}
      - salt-common: {{ version }}
    - order: last
  service.running:
    - order: last
    - require:
      - pkg: salt-minion
```

### Steps to Reproduce Issue

On Debian Jessie I'm able to use the following one-liner:

```
# apt-get install -y --force-yes -o DPkg::Options::=--force-confold salt-minion=2016.11.4+ds-1 salt-common=2016.11.4+ds-1 && salt-call -l debug state.apply test
```

It rolls back salt to 2016.11.4 and state forces it to upgrade to 2017.7.2. I see the following output:

```
[INFO    ] Running state [salt-minion] at time 04:18:56.358274
[INFO    ] Executing state pkg.installed for salt-minion
[INFO    ] Executing command ['dpkg-query', '--showformat', '${Status} ${Package} ${Version} ${Architecture}\n', '-W'] in directory '/root'
[DEBUG   ] Could not LazyLoad pkg.normalize_name: 'pkg.normalize_name' is not available.
[DEBUG   ] Could not LazyLoad pkg.check_db: 'pkg.check_db' is not available.
[DEBUG   ] Could not LazyLoad pkg.check_extra_requirements: 'pkg.check_extra_requirements' is not available.
[DEBUG   ] Could not LazyLoad pkg.version_clean: 'pkg.version_clean' is not available.
[DEBUG   ] Current version (['2016.11.4+ds-1']) did not match desired version specification (2017.7.2+ds-1), adding to installation targets
[DEBUG   ] Could not LazyLoad pkg.check_extra_requirements: 'pkg.check_extra_requirements' is not available.
[DEBUG   ] Could not LazyLoad pkg.version_clean: 'pkg.version_clean' is not available.
[DEBUG   ] Current version (['2016.11.4+ds-1']) did not match desired version specification (2017.7.2+ds-1), adding to installation targets
[INFO    ] Executing command ['apt-cache', '-q', 'policy', 'salt-minion'] in directory '/root'
[INFO    ] Executing command ['apt-cache', '-q', 'policy', 'salt-common'] in directory '/root'
[DEBUG   ] Could not LazyLoad pkg.normalize_name: 'pkg.normalize_name' is not available.
[INFO    ] Executing command ['dpkg', '--get-selections', '*'] in directory '/root'
[INFO    ] Executing command ['systemd-run', '--scope', 'apt-get', '-q', '-y', '-o', 'DPkg::Options::=--force-confold', '-o', 'DPkg::Options::=--force-confdef', 'install', 'salt-minion=2017.7.2+ds-1', 'salt-common=2017.7.2+ds-1'] in directory '/root'
[INFO    ] Executing command ['dpkg-query', '--showformat', '${Status} ${Package} ${Version} ${Architecture}\n', '-W'] in directory '/root'
[DEBUG   ] Could not LazyLoad pkg.version_clean: 'pkg.version_clean' is not available.
[DEBUG   ] Could not LazyLoad pkg.version_clean: 'pkg.version_clean' is not available.
[INFO    ] Made the following changes:
'salt-minion' changed from '2016.11.4+ds-1' to '2017.7.2+ds-1'
'salt-common' changed from '2016.11.4+ds-1' to '2017.7.2+ds-1'

[DEBUG   ] Refreshing modules...
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded saltutil.refresh_modules
[DEBUG   ] LazyLoaded event.fire
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_63111f557c_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_63111f557c_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_63111f557c_pull.ipc
[DEBUG   ] Sending event: tag = module_refresh; data = {'_stamp': '2017-10-11T04:19:03.108515'}
[INFO    ] Completed state [salt-minion] at time 04:19:03.113442 duration_in_ms=6755.172
[DEBUG   ] LazyLoaded config.option
[INFO    ] dns_mapper executable not found, not loading dns_mapper module
[INFO    ] circusctl executable not found, not loading circus module
[DEBUG   ] Module DSC: Only available on Windows systems
[DEBUG   ] Failed to import module vsphere:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1333, in _load_module
    mod = pyximport.load_module(name, fpath, tempfile.gettempdir())
  File "/usr/lib/python2.7/dist-packages/salt/modules/vsphere.py", line 178, in <module>
    from salt.utils.decorators import depends, ignores_kwargs
ImportError: cannot import name ignores_kwargs
[DEBUG   ] Module PSGet: Only available on Windows systems
[DEBUG   ] You should upgrade pyOpenSSL to at least 0.15.1 to enable the full use of X509 extensions in the tls module
[DEBUG   ] LazyLoaded service.start
[DEBUG   ] LazyLoaded service.running
[INFO    ] Running state [salt-minion] at time 04:19:03.512605
[INFO    ] Executing state service.running for salt-minion
[DEBUG   ] LazyLoaded cmd.run_all
[INFO    ] Executing command ['systemctl', 'status', 'salt-minion.service', '-n', '0'] in directory '/root'
[DEBUG   ] stdout: * salt-minion.service - The Salt Minion
   Loaded: loaded (/lib/systemd/system/salt-minion.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2017-10-11 03:25:01 UTC; 54min ago
     Docs: man:salt-minion(1)
           file:///usr/share/doc/salt/html/contents.html
           https://docs.saltstack.com/en/latest/contents.html
 Main PID: 1323 (salt-minion)
   CGroup: /docker/48b37995a9ab8ab2e5ba3eac4e6494ebea17460f4369318cb702aad85091f94d/system.slice/salt-minion.service
           |-1323 /usr/bin/python /usr/bin/salt-minion
           |-1327 /usr/bin/python /usr/bin/salt-minion
           `-1331 /usr/bin/python /usr/bin/salt-minion
[INFO    ] Executing command ['systemctl', 'is-active', 'salt-minion.service'] in directory '/root'
[DEBUG   ] output: active
[INFO    ] Executing command ['systemctl', 'is-enabled', 'salt-minion.service'] in directory '/root'
[DEBUG   ] output: enabled
[INFO    ] The service salt-minion is already running
[INFO    ] Completed state [salt-minion] at time 04:19:03.750536 duration_in_ms=237.931
[DEBUG   ] File /var/cache/salt/minion/accumulator/139932475262352 does not exist, no need to cleanup.

Passed invalid arguments: check_state_result() got an unexpected keyword argument 'highstate'.

... skipped ...

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 197, in call
    except IOError:
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 550, in apply_
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 1069, in sls
    kwargs.get('__pub_jid'),
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 97, in _set_retcode
    if not salt.utils.check_state_result(ret, highstate=highstate):
TypeError: check_state_result() got an unexpected keyword argument 'highstate'
```

If I remove `service.running`, it works without any exceptions.

It seems that salt reloads `salt.modules.state` from 2017.7.2 and it wants to run `salt.utils.check_state_result` with an extra `highstate` kwarg that is not available in 2016.11.4.

I see no options to avoid reloads, only to force them.

### Versions Report

```
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: 0.3.6
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.9
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.9.49-moby
         system: Linux
        version: debian 8.9
```

**Comment by Ch3LL** [comment]
i'm having a hard time replicating this on debian 8

you stated "It rolls back salt"  to 2016.11.4 Which version of salt did you have setup and installed previously?

**Comment by bobrik** [comment]
@Ch3LL here you go: https://github.com/bobrik/salt-issues/tree/master/44035
