### ISSUE TITLE
Package Downgrade Fails

### ISSUE THREAD

**Issue by jalandis** [saltstack/salt#44050]
Salt state was failing to downgrade with the following error message.
```
      ID: Samba
Function: pkg.installed
  Result: False
 Comment: An exception occurred in this state: Traceback (most recent call last):
            File "/usr/lib/python2.7/site-packages/salt/state.py", line 1843, in call
              **cdata['kwargs'])
            File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1795, in wrapper
              return f(*args, **kwargs)
            File "/usr/lib/python2.7/site-packages/salt/states/pkg.py", line 1631, in installed
              **kwargs)
            File "/usr/lib/python2.7/site-packages/salt/modules/yumpkg.py", line 1415, in install
              if re.match('kernel(-.+)?', name):
            File "/usr/lib64/python2.7/re.py", line 137, in match
              return _compile(pattern, flags).match(string)
          TypeError: expected string or buffer
 Started: 16:19:47.525980
Duration: 33919.388 ms
 Changes:  
```

The original salt state:
```
Samba:
  pkg.installed:
    - pkgs:
      - samba: '4.4.4*'
      - samba-client: '4.4.4*'
    - hold: True
    - update_holds: True
  service.running:
    - name: smb
    - enable: True
```

In order to get working I had to edit the following changing the `name` variable to `pkgname`

https://github.com/saltstack/salt/blob/5d719a2219908285d20ede02635f03b8b0e35b16/salt/modules/yumpkg.py#L1415

**Comment by jalandis** [comment]
@garethgreenaway Here is the requested report, please let me know if there is any other information I 
 could provide that would assist you.

```
salt-call --versions-report
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  2 2016, 04:20:16)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.3 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.26.2.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.3 Maipo
```

**Comment by anitakrueger** [comment]
+1 from me. I've just run into the exact same issue.
```
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.16.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

**Comment by garethgreenaway** [comment]
@jalandis Thanks for the versions report.  I haven't been able to duplicate this so far, I also don't have version 4.4.4 of Samba available to install.  Do you have additional repositories installed that provide this version?

@anitakrueger Can you provide a state file that is causing the same results as well as any additional repositories you're using to provide the downgraded packages?

Thanks!

**Comment by Alake28** [comment]
This is happening for me too. I have to change name to pkgname as @jalandis pointed out. I'm on 2017.7.2 salt-minion

**Comment by RedKrieg** [comment]
I am also experiencing this problem, but with rpm installs from sources.  I did not have the issue early last week.

```
mylocalpkgs:
    pkg.installed:
      - sources:
        - ipmitool: salt://nodestate/packages/ipmitool.x86_64.rpm
        - ioping: salt://nodestate/packages/ioping.x86_64.rpm
        - MegaCli: salt://nodestate/packages/megacli.rpm
        - storcli: salt://nodestate/packages/storcli.noarch.rpm
      - require:
        - pkg: bootstrap_pkgs
        - pkg: jdk
```

```
----------
          ID: mylocalpkgs
    Function: pkg.installed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1843, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1795, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/pkg.py", line 1631, in installed
                  **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/modules/yumpkg.py", line 1415, in install
                  if re.match('kernel(-.+)?', name):
                File "/usr/lib64/python2.7/re.py", line 141, in match
                  return _compile(pattern, flags).match(string)
              TypeError: expected string or buffer
     Started: 11:44:41.958717
    Duration: 6995.411 ms
     Changes:   
----------
```

```
# salt-call --versions-report
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jul 12 2017, 17:32:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.9 Final
         locale: UTF-8
        machine: x86_64
        release: 3.10.107-1.el6.elrepo.x86_64
         system: Linux
        version: CentOS 6.9 Final

```

**Comment by nhavens** [comment]
Same error message here using sources for a package install on CentOS 7.4 with SaltStack 2017.7.2. Here's another simple sls file that will trigger the error:
```
ius-release:
  pkg.installed:
    - sources: 
      - ius-release: https://centos7.iuscommunity.org/ius-release.rpm
```

**Comment by scubahub** [comment]
Same issue for me

```
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.2.1511 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-327.10.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

**Comment by RedKrieg** [comment]
This is fixed in the develop branch, but is not yet released: https://github.com/saltstack/salt/commit/0692f442dbaf5a0b16ce696c8947d73ed14965a9

**Comment by mdzidic** [comment]
Hello,

I'm experiencing same problem managing `docker-ce` package version...

```
docker-ce_install:
  pkg.installed:
    - name: docker-ce
    - version: 17.09.1.ce-1.el7.centos
```

Installing new package and upgrading package from older version works fine, but when it comes to package downgrade Salt throws an error:

```
          ID: docker-ce_install
    Function: pkg.installed
        Name: docker-ce
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1843, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1795, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/pkg.py", line 1631, in installed
                  **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/modules/yumpkg.py", line 1415, in install
                  if re.match('kernel(-.+)?', name):
                File "/usr/lib64/python2.7/re.py", line 137, in match
                  return _compile(pattern, flags).match(string)
              TypeError: expected string or buffer
     Started: 17:59:12.228820
    Duration: 32173.284 ms
```

Salt report:

```
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: 2.6.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 4.14.12-x86_64-linode92
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

**Comment by thebluesnevrdie** [comment]
@terminalmage @garethgreenaway This looks like it was taken care of in #44188 and can be closed.
