### ISSUE TITLE
Using state.highstate with `terse=true` prevents useful error output 

### ISSUE THREAD

**Issue by mfussenegger** [saltstack/salt#44087]
### Description of Issue/Question

In case of a invalid sls entry using `state.highstate terse=true` can cause a meaningless exception instead of the real error message.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue

Add a duplicate SLS ID to a state file.
This should result in a message like follows if `state.highstate` is applied.:

```
Data failed to compile:
----------
    Detected conflicting IDs, SLS IDs need to be globally unique.
```

But if `state.highstate terse=true` is run, the following error is returned:

```
The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1470, in _thread_return
        return_data = executor.execute()
      File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 898, in highstate
        ret = _filter_running(ret)
      File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 81, in _filter_running
        ret = dict((tag, value) for tag, value in six.iteritems(runnings)
      File "/usr/lib/python2.7/site-packages/salt/ext/six.py", line 606, in iteritems
        return d.iteritems(**kw)
    AttributeError: 'list' object has no attribute 'iteritems'
```

### Versions Report

```
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.16.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

**Comment by gtmanfred** [comment]
This appears to be a bug in the salt.modules.state._filter_running module.

It doesn't handle if the return is an error for compiling.

I have fixed this in https://github.com/saltstack/salt/pull/44093

Thanks for reporting.
Daniel
