### ISSUE TITLE
kubernetes.node_labels execution module is broken

### ISSUE THREAD

**Issue by SEJeff** [saltstack/salt#44229]
### Description of Issue/Question
cc: @flavio who wrote this function initially. I'll have a PR shortly with unit tests to fix this.

### Setup
I setup a [test kubernetes cluster using minikube](https://kubernetes.io/docs/getting-started-guides/minikube/) and configured `/etc/salt/minion` with the bare defaults but changed `master` to localhost and added:

```yaml
kubernetes.api_url: 'https://192.168.99.100:8443'
kubernetes.certificate-authority-file: '/home/jeff/.minikube/ca.crt'
kubernetes.client-certificate-file: '/home/jeff/.minikube/client.crt'
kubernetes.client-key-file: '/home/jeff/.minikube/client.key'
```
### Steps to Reproduce Issue

```bash
(ve) [root@omniscience salt]# salt-call kubernetes.node_labels minikube
[WARNING ] /home/jeff/git/salt/salt/utils/__init__.py:794: DeprecationWarning: Use of 'salt.utils.fopen' detected. This function has been moved to 'salt.utils.files.fopen' as of Salt Oxygen. This warning will be removed in Salt Neon.

[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'dict' object has no attribute 'metadata'
Traceback (most recent call last):
  File "/home/jeff/git/salt/ve/bin/salt-call", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/jeff/git/salt/scripts/salt-call", line 11, in <module>
    salt_call()
  File "/home/jeff/git/salt/salt/scripts.py", line 395, in salt_call
    client.run()
  File "/home/jeff/git/salt/salt/cli/call.py", line 57, in run
    caller.run()
  File "/home/jeff/git/salt/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/home/jeff/git/salt/salt/cli/caller.py", line 210, in call
    ret['return'] = func(*args, **kwargs)
  File "/home/jeff/git/salt/salt/modules/kubernetes.py", line 273, in node_labels
    return match.metadata.labels
AttributeError: 'dict' object has no attribute 'metadata'
Traceback (most recent call last):
  File "/home/jeff/git/salt/ve/bin/salt-call", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/jeff/git/salt/scripts/salt-call", line 11, in <module>
    salt_call()
  File "/home/jeff/git/salt/salt/scripts.py", line 395, in salt_call
    client.run()
  File "/home/jeff/git/salt/salt/cli/call.py", line 57, in run
    caller.run()
  File "/home/jeff/git/salt/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/home/jeff/git/salt/salt/cli/caller.py", line 210, in call
    ret['return'] = func(*args, **kwargs)
  File "/home/jeff/git/salt/salt/modules/kubernetes.py", line 273, in node_labels
    return match.metadata.labels
AttributeError: 'dict' object has no attribute 'metadata'
```

### Versions Report
I wanted to do some development on the kubernetes module to fix some bugs. I pulled the latest develop at 818100b8e7e8f9c3c524f7f3355a2f9e83f63361.

```bash
(ve) [root@omniscience salt]# salt-minion --versions-report
Salt Version:
           Salt: 2017.7.0-747-g818100b
 
Dependency Versions:
           cffi: 1.11.2
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: 2.5.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Sep  5 2017, 08:53:59)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.1.6
 
System Versions:
           dist: fedora 26 Twenty Six
         locale: UTF-8
        machine: x86_64
        release: 4.12.13-300.fc26.x86_64
         system: Linux
        version: Fedora 26 Twenty Six
```

**Comment by gtmanfred** [comment]
Thanks @SEJeff for the PR to fix this!

Daniel
