### ISSUE TITLE
--progress fails when hosts routed via syndic

### ISSUE THREAD

**Issue by boltronics** [saltstack/salt#44239]
### Description of Issue/Question
```
# salt --progress -L server1,server2 test.ping
[ERROR   ] An un-handled exception was caught by salt's global exception handler:######################################| Elapsed Time: 0:00:00 Returns: [1/1]
ValueError: Value out of range
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 476, in salt_main
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/salt.py", line 155, in run
    self._progress_ret(progress, out)
  File "/usr/lib/python2.7/dist-packages/salt/cli/salt.py", line 345, in _progress_ret
    salt.output.update_progress(self.config, progress, self.progress_bar, out)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 75, in update_progress
    progress_outputter(progress, progress_iter)
  File "/usr/lib/python2.7/dist-packages/salt/output/progress.py", line 26, in output
    bar.update(ret['return_count'])
  File "/usr/lib/pymodules/python2.7/progressbar/__init__.py", line 271, in update
    raise ValueError('Value out of range')
ValueError: Value out of range
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 476, in salt_main
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/salt.py", line 155, in run
    self._progress_ret(progress, out)
  File "/usr/lib/python2.7/dist-packages/salt/cli/salt.py", line 345, in _progress_ret
    salt.output.update_progress(self.config, progress, self.progress_bar, out)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 75, in update_progress
    progress_outputter(progress, progress_iter)
  File "/usr/lib/python2.7/dist-packages/salt/output/progress.py", line 26, in output
    bar.update(ret['return_count'])
  File "/usr/lib/pymodules/python2.7/progressbar/__init__.py", line 271, in update
    raise ValueError('Value out of range')
ValueError: Value out of range
#
```

### Setup
In this example, `server1` is directly accessible, but `server2` can only be accessed via a Salt syndic host. If all hosts queried are reachable directly, there is no problem.

### Steps to Reproduce Issue
Use the `--progress` argument to the `salt` command in conjunction with matching one or more hosts routed via a syndic server, as above.

### Versions Report
```
# sudo salt --versions-report
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.9 
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.9 

#
```

**Comment by gtmanfred** [comment]
@DmitryKuzmenko Is this even possible with the syndic?

My understanding with the syndic is that we send all the data back at the end of the minion processing on the syndic master, so even if it didn't stack trace, we wouldn't be able to actually see the progress?

Thanks,
Daniel

**Comment by DmitryKuzmenko** [comment]
@gtmanfred as I understand the `progress` logic there should be no problem for it to work with syndic. I think it's a bug, I'll run a quick-test tomorrow.

**Comment by gtmanfred** [comment]
Awesome thanks! i have relabeled this as a bug.

Thanks,
Daniel

**Comment by DmitryKuzmenko** [comment]
I've tested the issue. The specific of minions connected via syndic is that MoM don't know what minions are targeted by glob or other selector chosen even if it's the comma separated list. It's because syndic makes its own target list on its side when `salt` command gets the result list from it's local master that is MoM. Here `salt` expects 1 response and creates the progress bar with max value of 1, but receives the second response that produces the error.
The best way to fix it is to add a logic that would report back to MoM the result targets from each syndic and handle it on MoM. It's not trivial and would take some time to implement.
Also there is a fast approach just to avoid the error. We could either disable progress for syndics or stop to update the progress bar when it's already at its maximum.
