### ISSUE TITLE
Upgrading Powershell breaks chocolatey.installed & chocolocatey.version (When used with check_remote)

### ISSUE THREAD

**Issue by trexx** [saltstack/salt#44247]
### Description of Issue/Question
Installing or upgrading to PowerShell 5.1.14409.20170510 results in this traceback when attempting to use chocolatey.installed. This is also reproducible when using chocolatey.version powershell check_remote=true.

```
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
KeyError: 'PowerShell'
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 391, in salt_call
    client.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\call.py", line 58, in run
    caller.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 134, in run
    ret = self.call()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 204, in call
    ret['return'] = func(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\modules\chocolatey.py", line 889, in version
    'available': available[pkg]}
KeyError: 'PowerShell'
```

### Setup
Masterless minion  

### Steps to Reproduce Issue
posh_upgrade.sls  

``` sls
chocolatey_install_powershell:
  chocolatey.installed:
    - name: powershell
```

`PS C:\salt> .\salt-call.bat --local state.sls posh_upgrade`

--OR--

`PS C:\salt> .\salt-call.bat --local chocolatey.version powershell check_remote=true`

Output without check_remote

```
PS C:\salt> .\salt-call.bat --local chocolatey.version powershell
local:
    ----------
    PowerShell:
        - 5.1.14409.20170510
```

### Versions Report
```
PS C:\salt> .\salt-call.bat --versions-report
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.0
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2008ServerR2
         system: Windows
        version: 2008ServerR2 6.1.7601 SP1 Multiprocessor Free
```

**Comment by Ch3LL** [comment]
For some reason i'm having problems getting chocolately up and running correctly on multiple windows OSs to try to replicate. Would you mind adding these logs:

```
diff --git a/salt/modules/chocolatey.py b/salt/modules/chocolatey.py
index 5093ec8a2d..714204d94f 100644
--- a/salt/modules/chocolatey.py
+++ b/salt/modules/chocolatey.py
@@ -883,6 +883,8 @@ def version(name, check_remote=False, source=None, pre_versions=False):
 
     if check_remote:
         available = list_(narrow=name, pre_versions=pre_versions, source=source)
+        log.error('available: {0}'.format(available))
+        log.error('packages: {0}'.format(packages))
 
         for pkg in packages:
             packages[pkg] = {'installed': installed[pkg],
```

And include the sanitized output from the command you are running with `-ldebug` added onto it?

**Comment by trexx** [comment]
I've re-prepped my VM and I'm not getting the error anymore. Not sure what it could have been as I've run the same state which upgraded powershell.
If it happens again, I'll keep your logs in mind.

Thanks!

**Comment by tobias-kuendig** [comment]
For anyone having this issue:

The problem appears if salt tries to install a package, that is no longer available. You can check the availability using the `choco list <your-package>` command. If it does not return any output, the installation will fail. You'll have to find out why the package is no longer available.

For example, the `redis-64` package started to make problems today because [the official chocolatey package](https://chocolatey.org/packages/redis-64) has been deprecated. `choco list redis-64` no longer returns any results.
