### ISSUE TITLE
reactor returns keyerror

### ISSUE THREAD

**Issue by BlackkeeperRX** [saltstack/salt#44282]
### Description of Issue/Question

I'm trying to test a simple reactor. The reactor recognizes the event, but while reactring to it, it get aborted with KeyError: 'probes'. 
I was also testing with other modules, but getting always a KeyError.

Only saw old, solved issues here with KeyErrors, but no with Nitrogen Release.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

```
berlin_test.sls:
berlin_test:
  probes.managed:
        - probes:
            probe_name1:
                probe1_test1:
                    target: berlin
                    probe_count: 15
                    test_interval: 3
                    probe_type: icmp-ping
```

(also tried to add -require probes)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

```
[DEBUG   ] Rendered data from file: /srv/salt/reactors/berlin_test.sls:
berlin_test:
  probes.managed:
        - probes:
          - require: probes
            probe_name1:
                probe1_test1:
                    target: berlin
                    probe_count: 15
                    test_interval: 3
                    probe_type: icmp-ping

[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Results of YAML rendering:
OrderedDict([('berlin_test', OrderedDict([('probes.managed', [OrderedDict([('probes', [OrderedDict([('require', 'probes'), ('probe_name1', OrderedDict([('probe1_test1', OrderedDict([('target', 'berlin'), ('probe_count', 15), ('test_interval', 3), ('probe_type', 'icmp-ping')]))]))])])])])]))])
[PROFILE ] Time (in seconds) to render '/srv/salt/reactors/berlin_test.sls' using 'yaml' renderer: 0.0295329093933
[DEBUG   ] Reactor is populating probes client cache
[ERROR   ] An un-handled exception from the multiprocessing process 'Reactor-8:1' was caught:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/process.py", line 663, in _run
    return self._original_run()
  File "/usr/lib/python2.7/dist-packages/salt/utils/reactor.py", line 270, in run
    self.call_reactions(chunks)
  File "/usr/lib/python2.7/dist-packages/salt/utils/reactor.py", line 227, in call_reactions
    self.wrap.run(chunk)
  File "/usr/lib/python2.7/dist-packages/salt/utils/reactor.py", line 329, in run
    self.populate_client_cache(low)
  File "/usr/lib/python2.7/dist-packages/salt/utils/reactor.py", line 323, in populate_client_cache
    self.reaction_class[reaction_type](self.opts['conf_file'])
KeyError: 'probes'
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.11.2
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-31-generic
         system: Linux

```

**Comment by gtmanfred** [comment]
The reactor needs to specify the client, not a state.

you would specify `local.state.apply` and then tell it to run the state file that the `probes.managed` is in.


`/srv/salt/whatever.sls`
```
berlin_test:
  probes.managed:
        - probes:
          - require: probes
            probe_name1:
                probe1_test1:
                    target: berlin
                    probe_count: 15
                    test_interval: 3
                    probe_type: icmp-ping
```

`/srv/salt/reactor/berlin_test.sls`
```
add_new_minion_to_pool:
  local.state.apply:
    - tgt: '*'
    - args:
      - mods: whatever
```

Daniel
