### ISSUE TITLE
boto3_route53 module times out on retries

### ISSUE THREAD

**Issue by mwerickso** [saltstack/salt#44303]
### Description of Issue/Question
I am trying to create a r53 recordset, but the state keeps timing out without any indication as to why (besides the # of retries ran out).

### Setup
I have the following debug state:
```
Ensure r53 record set for testing.net exists:
  boto3_route53.rr_present:
    - DomainName: testing.net.
    - Name: database.testing.net.
    - Type: CNAME
    - ResourceRecords: 
      - myRDSEndpoint-ajhfkajhdkah.us-east-1.rds.amazonaws.com
    - region: {{ region }}
```

When running the debug state, it returns the following:
```
----------
          ID: Ensure r53 record set for testing.net exists
    Function: boto3_route53.rr_present
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1837, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1794, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/boto3_route53.py", line 710, in rr_present
                  ChangeBatch=ChangeBatch, region=region, key=key, keyid=keyid, profile=profile):
                File "/usr/lib/python2.7/dist-packages/salt/modules/boto3_route53.py", line 880, in change_resource_record_sets
                  retries -= 1
              UnboundLocalError: local variable 'retries' referenced before assignment
     Started: 18:51:15.675880
    Duration: 1544688.487 ms
     Changes:   

Summary for mySaltMaster
------------
Succeeded: 0
Failed:    1
------------
```

### Steps to Reproduce Issue
When running the state in debug mode, it does not indicate any issues, simply that it keeps retrying the jid for a return.

### Versions Report
```
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-96-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by Ch3LL** [comment]
it definitely looks like that retries variable is definnitely not anywhere before this call `retries -= 1` so we will need to fix that up.

But the reason your getting to that part of the code is looks like it logs a message "Throttled by AWS API"

Can you verify outside of salt that you can query AWS?

Also can you run the state using salt-call with `-ldebug` so we can see all the relevant debugging information.

ping @saltstack/team-boto

**Comment by mwerickso** [comment]
I am able to use the aws cli on this same machine without problems, as well as many other salt states work.

Here is a portion of the log:
```
DEBUG   ] Results of YAML rendering: 
OrderedDict([('Ensure r53 record set for testing.net. exists', OrderedDict([('boto3_route53.rr_present', [OrderedDict([('DomainName', 'testing.net.')]), OrderedDict([('Name', 'database.')]), OrderedDict([('Type', 'CNAME')]), OrderedDict([('ResourceRecords', ['myRDSEndpoint-ajhfkajhdkah.us-east-1.rds.amazonaws.com'])]), OrderedDict([('region', 'us-east-1')])])]))])
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/aws/debug.sls' using 'yaml' renderer: 0.00542807579041
[DEBUG   ] LazyLoaded boto3.assign_funcs
[DEBUG   ] LazyLoaded boto3_route53.find_hosted_zone
[DEBUG   ] LazyLoaded boto3_route53.rr_present
[INFO    ] Running state [Ensure r53 record set for testing.net. exists] at time 15:07:22.525167
[INFO    ] Executing state boto3_route53.rr_present for [Ensure r53 record set for testing.net. exists]
[DEBUG   ] Name after massaging is: database.
[DEBUG   ] Setting config variable for region to 'us-east-1'
[DEBUG   ] Loading variable profile from defaults.
[DEBUG   ] Loading variable config_file from defaults.
[DEBUG   ] Loading variable credentials_file from defaults.
[DEBUG   ] Loading variable data_path from defaults.
[DEBUG   ] Loading variable region from instance vars with value 'us-east-1'.
[DEBUG   ] Loading variable profile from defaults.
[DEBUG   ] Loading variable ca_bundle from defaults.
[DEBUG   ] Loading variable profile from defaults.
[DEBUG   ] Loading variable api_versions from defaults.
[DEBUG   ] Loading variable profile from defaults.
[DEBUG   ] Loading variable credentials_file from defaults.
[DEBUG   ] Loading variable config_file from defaults.
[DEBUG   ] Loading variable profile from defaults.
[DEBUG   ] Loading variable metadata_service_timeout from defaults.
[DEBUG   ] Loading variable profile from defaults.
[DEBUG   ] Loading variable metadata_service_num_attempts from defaults.
[DEBUG   ] Loading variable profile from defaults.
[DEBUG   ] Looking for credentials via: env
[DEBUG   ] Looking for credentials via: assume-role
[DEBUG   ] Looking for credentials via: shared-credentials-file
[DEBUG   ] Looking for credentials via: config-file
[DEBUG   ] Looking for credentials via: ec2-credentials-file
[DEBUG   ] Looking for credentials via: boto-config
[DEBUG   ] Looking for credentials via: container-role
[DEBUG   ] Looking for credentials via: iam-role
[INFO    ] Starting new HTTP connection (1): 169.254.169.254
[DEBUG   ] "GET /latest/meta-data/iam/security-credentials/ HTTP/1.1" 200 4
[INFO    ] Starting new HTTP connection (1): 169.254.169.254
[DEBUG   ] "GET /latest/meta-data/iam/security-credentials/salt HTTP/1.1" 200 882
[DEBUG   ] Found credentials from IAM Role: salt
[DEBUG   ] Loading JSON file: /usr/local/lib/python2.7/dist-packages/botocore/data/endpoints.json
[DEBUG   ] Loading variable profile from defaults.
[DEBUG   ] Loading JSON file: /usr/local/lib/python2.7/dist-packages/botocore/data/route53/2013-04-01/service-2.json
[DEBUG   ] Event creating-client-class.route53: calling handler <function add_generate_presigned_url at 0x7f60cfd36c08>
[DEBUG   ] Using partition endpoint for route53, us-east-1: aws-global
[DEBUG   ] The s3 config key is not a dictionary type, ignoring its value of: None
[DEBUG   ] Setting route53 timeout as (60, 60)
[DEBUG   ] Loading JSON file: /usr/local/lib/python2.7/dist-packages/botocore/data/_retry.json
[DEBUG   ] Registering retry handlers for service: route53
[DEBUG   ] Event before-parameter-build.route53.ListHostedZones: calling handler <function fix_route53_ids at 0x7f60cfced320>
[DEBUG   ] Event before-parameter-build.route53.ListHostedZones: calling handler <function generate_idempotent_uuid at 0x7f60cfcf1410>
[DEBUG   ] Making request for OperationModel(name=ListHostedZones) (verify_ssl=True) with params: {'body': '', 'url': u'https://route53.amazonaws.com/2013-04-01/hostedzone', 'headers': {'User-Agent': 'Boto3/1.4.7 Python/2.7.12 Linux/4.4.0-97-generic Botocore/1.7.35'}, 'context': {'auth_type': None, 'client_region': u'aws-global', 'has_streaming_input': False, 'client_config': <botocore.config.Config object at 0x7f60cf876090>}, 'query_string': {}, 'url_path': u'/2013-04-01/hostedzone', 'method': u'GET'}
[DEBUG   ] Event request-created.route53.ListHostedZones: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7f60cf869f10>>
[DEBUG   ] Event choose-signer.route53.ListHostedZones: calling handler <function set_operation_specific_signer at 0x7f60cfcf1320>
[DEBUG   ] Calculating signature using v4 auth.
[DEBUG   ] CanonicalRequest:
GET
/2013-04-01/hostedzone

host:route53.amazonaws.com
x-amz-date:20171027T150722Z
x-amz-security-token:<token>

host;x-amz-date;x-amz-security-token
<token>
[DEBUG   ] StringToSign:
AWS4-HMAC-SHA256
20171027T150722Z
20171027/us-east-1/route53/aws4_request
<token>
[DEBUG   ] Signature:
<sig>
[DEBUG   ] Sending http request: <PreparedRequest [GET]>
[INFO    ] Starting new HTTPS connection (1): route53.amazonaws.com
[DEBUG   ] "GET /2013-04-01/hostedzone HTTP/1.1" 200 719
[DEBUG   ] Response headers: {'x-amzn-requestid': '88d759de-bb28-11e7-a07a-57dcb3ed56b8', 'date': 'Fri, 27 Oct 2017 15:07:22 GMT', 'content-length': '719', 'content-type': 'text/xml'}
[DEBUG   ] Response body:
<?xml version="1.0"?>
<ListHostedZonesResponse xmlns="https://route53.amazonaws.com/doc/2013-04-01/"><HostedZones><HostedZone><Id>/hostedzone/Z64XOIYPVL2Z2</Id><Name>otherdomain.com.</Name><CallerReference>5281C4E9-F701-0CD3-B693-B53EAE74DD57</CallerReference><Config><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>2</ResourceRecordSetCount></HostedZone><HostedZone><Id>/hostedzone/Z1LOYFY3K16GSW</Id><Name>testing.net.</Name><CallerReference>60F2783B-B74D-8E24-B37E-225F75F84472</CallerReference><Config><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>9</ResourceRecordSetCount></HostedZone></HostedZones><IsTruncated>false</IsTruncated><MaxItems>100</MaxItems></ListHostedZonesResponse>
[DEBUG   ] Event needs-retry.route53.ListHostedZones: calling handler <botocore.retryhandler.RetryHandler object at 0x7f60cf83e190>
[DEBUG   ] No retry needed.
[DEBUG   ] Event before-parameter-build.route53.GetHostedZone: calling handler <function fix_route53_ids at 0x7f60cfced320>
[DEBUG   ] Id /hostedzone/Z1LOYFY3K16GSW -> Z1LOYFY3K16GSW
[DEBUG   ] Event before-parameter-build.route53.GetHostedZone: calling handler <function generate_idempotent_uuid at 0x7f60cfcf1410>
[DEBUG   ] Making request for OperationModel(name=GetHostedZone) (verify_ssl=True) with params: {'body': '', 'url': u'https://route53.amazonaws.com/2013-04-01/hostedzone/Z1LOYFY3K16GSW', 'headers': {'User-Agent': 'Boto3/1.4.7 Python/2.7.12 Linux/4.4.0-97-generic Botocore/1.7.35'}, 'context': {'auth_type': None, 'client_region': u'aws-global', 'has_streaming_input': False, 'client_config': <botocore.config.Config object at 0x7f60cf876090>}, 'query_string': {}, 'url_path': u'/2013-04-01/hostedzone/Z1LOYFY3K16GSW', 'method': u'GET'}
[DEBUG   ] Event request-created.route53.GetHostedZone: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7f60cf869f10>>
[DEBUG   ] Event choose-signer.route53.GetHostedZone: calling handler <function set_operation_specific_signer at 0x7f60cfcf1320>
[DEBUG   ] Calculating signature using v4 auth.
[DEBUG   ] CanonicalRequest:
GET
/2013-04-01/hostedzone/Z1LOYFY3K16GSW

host:route53.amazonaws.com
x-amz-date:20171027T150722Z
x-amz-security-token:<token>

host;x-amz-date;x-amz-security-token
<token>
[DEBUG   ] StringToSign:
AWS4-HMAC-SHA256
20171027T150722Z
20171027/us-east-1/route53/aws4_request
<request>
[DEBUG   ] Signature:
<sig>
[DEBUG   ] Sending http request: <PreparedRequest [GET]>
[DEBUG   ] "GET /2013-04-01/hostedzone/Z1LOYFY3K16GSW HTTP/1.1" 200 617
[DEBUG   ] Response headers: {'x-amzn-requestid': '88dc3be1-bb28-11e7-a07a-57dcb3ed56b8', 'date': 'Fri, 27 Oct 2017 15:07:22 GMT', 'content-length': '617', 'content-type': 'text/xml'}
[DEBUG   ] Response body:
<?xml version="1.0"?>
<GetHostedZoneResponse xmlns="https://route53.amazonaws.com/doc/2013-04-01/"><HostedZone><Id>/hostedzone/Z1LOYFY3K16GSW</Id><Name>testing.net.</Name><CallerReference>60F2783B-B74D-8E24-B37E-225F75F84472</CallerReference><Config><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>9</ResourceRecordSetCount></HostedZone><DelegationSet><NameServers><NameServer>ns-1512.awsdns-61.org</NameServer><NameServer>ns-1990.awsdns-56.co.uk</NameServer><NameServer>ns-54.awsdns-06.com</NameServer><NameServer>ns-1009.awsdns-62.net</NameServer></NameServers></DelegationSet></GetHostedZoneResponse>
[DEBUG   ] Event needs-retry.route53.GetHostedZone: calling handler <botocore.retryhandler.RetryHandler object at 0x7f60cf83e190>
[DEBUG   ] No retry needed.
[DEBUG   ] Event before-parameter-build.route53.ListResourceRecordSets: calling handler <function fix_route53_ids at 0x7f60cfced320>
[DEBUG   ] HostedZoneId /hostedzone/Z1LOYFY3K16GSW -> Z1LOYFY3K16GSW
[DEBUG   ] Event before-parameter-build.route53.ListResourceRecordSets: calling handler <function generate_idempotent_uuid at 0x7f60cfcf1410>
[DEBUG   ] Making request for OperationModel(name=ListResourceRecordSets) (verify_ssl=True) with params: {'body': '', 'url': u'https://route53.amazonaws.com/2013-04-01/hostedzone/Z1LOYFY3K16GSW/rrset?type=CNAME&name=database.', 'headers': {'User-Agent': 'Boto3/1.4.7 Python/2.7.12 Linux/4.4.0-97-generic Botocore/1.7.35'}, 'context': {'auth_type': None, 'client_region': u'aws-global', 'has_streaming_input': False, 'client_config': <botocore.config.Config object at 0x7f60cf876090>}, 'query_string': {u'type': 'CNAME', u'name': 'database.'}, 'url_path': u'/2013-04-01/hostedzone/Z1LOYFY3K16GSW/rrset', 'method': u'GET'}
[DEBUG   ] Event request-created.route53.ListResourceRecordSets: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7f60cf869f10>>
[DEBUG   ] Event choose-signer.route53.ListResourceRecordSets: calling handler <function set_operation_specific_signer at 0x7f60cfcf1320>
[DEBUG   ] Calculating signature using v4 auth.
[DEBUG   ] CanonicalRequest:
GET
/2013-04-01/hostedzone/Z1LOYFY3K16GSW/rrset
name=database.&type=CNAME
host:route53.amazonaws.com
x-amz-date:20171027T150722Z
x-amz-security-token:<token>

host;x-amz-date;x-amz-security-token
<token>
[DEBUG   ] StringToSign:
AWS4-HMAC-SHA256
20171027T150722Z
20171027/us-east-1/route53/aws4_request
<request>
[DEBUG   ] Signature:
<sig>
[DEBUG   ] Sending http request: <PreparedRequest [GET]>
[DEBUG   ] "GET /2013-04-01/hostedzone/Z1LOYFY3K16GSW/rrset?type=CNAME&name=database. HTTP/1.1" 200 218
[DEBUG   ] Response headers: {'x-amzn-requestid': '88e1e138-bb28-11e7-a07a-57dcb3ed56b8', 'date': 'Fri, 27 Oct 2017 15:07:22 GMT', 'content-length': '218', 'content-type': 'text/xml'}
[DEBUG   ] Response body:
<?xml version="1.0"?>
<ListResourceRecordSetsResponse xmlns="https://route53.amazonaws.com/doc/2013-04-01/"><ResourceRecordSets/><IsTruncated>false</IsTruncated><MaxItems>100</MaxItems></ListResourceRecordSetsResponse>
[DEBUG   ] Event needs-retry.route53.ListResourceRecordSets: calling handler <botocore.retryhandler.RetryHandler object at 0x7f60cf83e190>
[DEBUG   ] No retry needed.
[DEBUG   ] Event before-parameter-build.route53.ChangeResourceRecordSets: calling handler <function fix_route53_ids at 0x7f60cfced320>
[DEBUG   ] HostedZoneId /hostedzone/Z1LOYFY3K16GSW -> Z1LOYFY3K16GSW
[DEBUG   ] Event before-parameter-build.route53.ChangeResourceRecordSets: calling handler <function generate_idempotent_uuid at 0x7f60cfcf1410>
[DEBUG   ] Making request for OperationModel(name=ChangeResourceRecordSets) (verify_ssl=True) with params: {'body': '<ChangeResourceRecordSetsRequest xmlns="https://route53.amazonaws.com/doc/2013-04-01/"><ChangeBatch><Changes><Change><Action>UPSERT</Action><ResourceRecordSet><Type>CNAME</Type><Name>database.</Name><ResourceRecords><ResourceRecord><Value>myRDSEndpoint-ajhfkajhdkah.us-east-1.rds.amazonaws.com</Value></ResourceRecord></ResourceRecords></ResourceRecordSet></Change></Changes></ChangeBatch></ChangeResourceRecordSetsRequest>', 'url': u'https://route53.amazonaws.com/2013-04-01/hostedzone/Z1LOYFY3K16GSW/rrset/', 'headers': {'User-Agent': 'Boto3/1.4.7 Python/2.7.12 Linux/4.4.0-97-generic Botocore/1.7.35'}, 'context': {'auth_type': None, 'client_region': u'aws-global', 'has_streaming_input': False, 'client_config': <botocore.config.Config object at 0x7f60cf876090>}, 'query_string': {}, 'url_path': u'/2013-04-01/hostedzone/Z1LOYFY3K16GSW/rrset/', 'method': u'POST'}
[DEBUG   ] Event request-created.route53.ChangeResourceRecordSets: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7f60cf869f10>>
[DEBUG   ] Event choose-signer.route53.ChangeResourceRecordSets: calling handler <function set_operation_specific_signer at 0x7f60cfcf1320>
[DEBUG   ] Calculating signature using v4 auth.
[DEBUG   ] CanonicalRequest:
POST
/2013-04-01/hostedzone/Z1LOYFY3K16GSW/rrset/

host:route53.amazonaws.com
x-amz-date:20171027T150722Z
x-amz-security-token:<token>

host;x-amz-date;x-amz-security-token
<token>
[DEBUG   ] StringToSign:
AWS4-HMAC-SHA256
20171027T150722Z
20171027/us-east-1/route53/aws4_request
<request>
[DEBUG   ] Signature:
<sig>
[DEBUG   ] Sending http request: <PreparedRequest [POST]>
[DEBUG   ] "POST /2013-04-01/hostedzone/Z1LOYFY3K16GSW/rrset/ HTTP/1.1" 400 259
[DEBUG   ] Response headers: {'x-amzn-requestid': '88e5d8de-bb28-11e7-a07a-57dcb3ed56b8', 'date': 'Fri, 27 Oct 2017 15:07:22 GMT', 'content-length': '259', 'content-type': 'text/xml', 'connection': 'close'}
[DEBUG   ] Response body:
<?xml version="1.0"?>
<ErrorResponse xmlns="https://route53.amazonaws.com/doc/2013-04-01/"><Error><Type>Sender</Type><Code>InvalidInput</Code><Message>Invalid request</Message></Error><RequestId>88e5d8de-bb28-11e7-a07a-57dcb3ed56b8</RequestId></ErrorResponse>
[DEBUG   ] Event needs-retry.route53.ChangeResourceRecordSets: calling handler <botocore.retryhandler.RetryHandler object at 0x7f60cf83e190>
[DEBUG   ] No retry needed.
[ERROR   ] Failed to apply requested changes to the hosted zone /hostedzone/Z1LOYFY3K16GSW: An error occurred (InvalidInput) when calling the ChangeResourceRecordSets operation: Invalid request
```

**Comment by tkwilliams** [comment]
I own this - assign to me :)

**Comment by rallytime** [comment]
@tkwilliams Thanks for fixing this so quickly! :)

I believe I sent you a request for membership in the `team-boto`, but it appears you didn't accept yet, so I wasn't able to assign this to you. Should I send that invitation again?
