### ISSUE TITLE
Infinite recursion exception

### ISSUE THREAD

**Issue by mist0706** [saltstack/salt#44323]
### Description of Issue/Question
When applying a state an infinite recursion error is met

### Setup
```root@salt:/srv/salt/dockers# cat sickrage/init.sls
sickrage:
  docker_image.present:
    - name: linuxserver/sickrage

  user.present:
    - fullname: sickrage
    - home: /opt/sickrage
    - uid: 1003
    - gid: 1001
    - createhome: True
    - empty_password: True
    - nologinit: True

  docker_container.running:
    - image: linuxserver/sickrage
    - binds:
      - /opt/sickrage:/config:rw
      - /mnt/Public/torrents/complete/series:/downloads/complete:ro
      - /mnt/anime:/anime:rw
      - /mnt/series:/tv:rw
    - port_bindings:
      - 8081:8081
    - environment:
      - PUID: 1003
      - PGID: 1001
    - require:
      - file: /opt/sickrage/config.ini
      - user: sickrage

  file.managed:
    - name: /opt/sickrage/config.ini
    - source: salt://dockers/sickrage/files/config.ini
    - user: sickrage
    - group: sickrage
    - mode: 600
    - prereq:
      - cmd: Stop_container_first

Stop_container_first:
  docker_container.stopped:
    - prereq:
      - file: /opt/sickrage/config.ini
    - name: sickrage````

### Steps to Reproduce Issue
```root@salt:/srv/salt/dockers# salt deploy-test state.apply dockers.sickrage
deploy-test:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1470, in _thread_return
        return_data = executor.execute()
      File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 592, in apply_
        return sls(mods, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 1109, in sls
        ret = st_.state.call_high(high_, orchestration_jid)
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2531, in call_high
        ret = self.call_chunks(chunks)
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2017, in call_chunks
        running = self.call_chunk(low, running, chunks)
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2356, in call_chunk
        running = self.call_chunk(low, running, chunks)
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2356, in call_chunk
        running = self.call_chunk(low, running, chunks)
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2356, in call_chunk
        running = self.call_chunk(low, running, chunks)
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2356, in call_chunk
        running = self.call_chunk(low, running, chunks)
.......................
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2356, in call_chunk
        running = self.call_chunk(low, running, chunks)
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2356, in call_chunk
        running = self.call_chunk(low, running, chunks)
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2249, in call_chunk
        low = self._mod_aggregate(low, running, chunks)
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 769, in _mod_aggregate
        agg_opt = self.functions['config.option']('state_aggregate')
      File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1114, in __getitem__
        func = super(LazyLoader, self).__getitem__(item)
      File "/usr/lib/python2.7/dist-packages/salt/utils/lazy.py", line 91, in __getitem__
        if self._missing(key):
    RuntimeError: maximum recursion depth exceeded```

### Versions Report
```Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-31-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by mist0706** [comment]
Double prereq caused the infinite loop
