### ISSUE TITLE
Azure vm provisioning issue

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#44412]
### Description of Issue/Question
I am using an external pillar for getting profiles and providers. During provisioning is get the following exception,

[ERROR   ] Failed to create VM testlinux990. Configuration value 'as_dict' needs to be set
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1287, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/azurearm.py", line 1190, in create
    'wait_for_ip_interval_multiplier', vm_, __opts__, default=1),
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 2421, in wait_for_ip
    data = update_callback(*update_args, **update_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/azurearm.py", line 1165, in _query_ip_address
    data = request_instance(kwargs=vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/azurearm.py", line 964, in request_instance
    iface_data = create_interface(kwargs=vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/azurearm.py", line 908, in create_interface
    return show_interface(kwargs=kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/azurearm.py", line 705, in show_interface
    data = object_to_dict(iface)
  File "/usr/lib/python2.7/dist-packages/salt/utils/msazure.py", line 196, in object_to_dict
    elif isinstance(obj.__dict__[item], six.text_type):
KeyError: 'as_dict'
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
SaltCloudSystemExit: Failed to deploy VM
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 391, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 204, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/cloud.py", line 200, in profile_
    info = client.profile(profile, names, vm_overrides=vm_overrides, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 348, in profile
    mapper.run_profile(profile, names, vm_overrides=vm_overrides)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1461, in run_profile
    raise SaltCloudSystemExit('Failed to deploy VM')
SaltCloudSystemExit: Failed to deploy VM

Also the same profile when copy onto salt master works perfectly. Please help.

**Comment by sumeetisp** [comment]
Both profiles are identical

**Comment by sumeetisp** [comment]
Interface gets provisioned and then it fails immediately

**Comment by sumeetisp** [comment]
#43886 This solve my issue. When is this fix getting released?

**Comment by gtmanfred** [comment]
2017.7.3 or you can provide a patched cloud driver using https://docs.saltstack.com/en/latest/ref/file_server/dynamic-modules.html

Right now there are no planned releases until january.
