### ISSUE TITLE
salt '*' pkg.install causes KeyError: '__name__'

### ISSUE THREAD

**Issue by pimiento** [saltstack/salt#44471]
### Description of Issue/Question
When I do `salt '*' pkg.install vim` I got

> root@e470 ~ # salt '*' pkg.install vim
192.168.246.50:
    The minion function caused an exception: Traceback (most recent call last):
      File "/opt/alt/python35/lib/python3.5/site-packages/salt/minion.py", line 1470, in _thread_return
        return_data = executor.execute()
      File "/opt/alt/python35/lib/python3.5/site-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/opt/alt/python35/lib/python3.5/site-packages/salt/modules/yumpkg.py", line 1284, in install
        _available = list_repo_pkgs(*has_wildcards, byrepo=False, **kwargs)
      File "/opt/alt/python35/lib/python3.5/site-packages/salt/modules/yumpkg.py", line 792, in list_repo_pkgs
        repo_name for repo_name, repo_info in six.iteritems(list_repos())
      File "/opt/alt/python35/lib/python3.5/site-packages/salt/modules/yumpkg.py", line 2466, in list_repos
        filerepos = _parse_repo_file(repopath)[1]
      File "/opt/alt/python35/lib/python3.5/site-packages/salt/modules/yumpkg.py", line 2726, in _parse_repo_file
        section_dict.pop('__name__')
    KeyError: '__name__'

### Setup
minion setup

> [root@localhost python35]# cat /etc/salt/minion
master: 10.101.1.34

master setup
> root@e470 ~ # cat /etc/salt/master 
interface: 10.101.1.34

### Versions Report
master version

> root@e470 ~ # salt --version
salt 2017.7.2 (Nitrogen)

minion version

> [root@localhost python35]# /opt/alt/python35/bin/salt --version
salt 2017.7.2 (Nitrogen)

I madesome debugging and found that the problem is with
`section_dict.pop` function. If only I add the second argument to pop
`section_dict.pop('__name__', None)`, then everything works.

**Comment by gtmanfred** [comment]
Would you mind submitting a PR to fix this?

Thanks,
Daniel

**Comment by pimiento** [comment]
I found it was already fixed

`
433bca14 salt/modules/yumpkg.py  (Erik Johnson           2017-09-05 15:13:22 -0500 2847)         section_dict.pop('__name__', None)
`
