### ISSUE TITLE
An un-handled exception was caught by salt's global exception handler:

### ISSUE THREAD

**Issue by hugoren** [saltstack/salt#44524]
### Description of Issue/Question
An un-handled exception was caught by salt's global exception handler:

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

[E 171114 10:00:38 setup:1133] An un-handled exception was caught by salt's global exception handler:
    RuntimeError: IOLoop is already running
    Traceback (most recent call last):
      File "/Users/admin/devops/salt-api-20170702/app.py", line 20, in <module>
        IOLoop.current().start()
      File "/Users/admin/Library/Python/2.7/lib/python/site-packages/tornado/ioloop.py", line 755, in start
        raise RuntimeError("IOLoop is already running")
    RuntimeError: IOLoop is already running
[E 171114 10:00:38 setup:1133] An un-handled exception was caught by salt's global exception handler:
    RuntimeError: IOLoop is already running
    Traceback (most recent call last):
      File "/Users/admin/devops/salt-api-20170702/app.py", line 20, in <module>
        IOLoop.current().start()
      File "/Users/admin/Library/Python/2.7/lib/python/site-packages/tornado/ioloop.py", line 755, in start
        raise RuntimeError("IOLoop is already running")
    RuntimeError: IOLoop is already running

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
python 2.7.2
salt 20170702
mac os

**Comment by Ch3LL** [comment]
Can you elaborate as to when you are seeing this? Are you running a particular command or doing something else with salt when seeing this error?
