### ISSUE TITLE
[runners] NameError: global name '__opts__' is not defined when trying to use imported runner

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#44535]
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

custom.py : 

```python
from salt.runners.manage import _ping

def status(output=True, tgt='*', tgt_type='glob', expr_form=None, timeout=None, gather_job_timeout=None):
    ret = {}
    ret['up'], ret['down'] = _ping(tgt, tgt_type, timeout, gather_job_timeout)
    return ret
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
gets : 

```
# salt-run custom.status
Exception occurred in runner custom.status: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 382, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/srv/salt/_runners/custom.py", line 5, in status
    ret['up'], ret['down'] = _ping(tgt, tgt_type, timeout, gather_job_timeout)
  File "/usr/lib/python2.7/dist-packages/salt/runners/manage.py", line 39, in _ping
    client = salt.client.get_local_client(__opts__['conf_file'])
NameError: global name '__opts__' is not defined

```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
# salt --versions-report
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 19 2017, 14:48:08)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.2 
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-4-amd64
         system: Linux
        version: debian 9.2 

```

**Comment by gtmanfred** [comment]
You need to use the loader to import the runner modules.

https://docs.saltstack.com/en/latest/ref/clients/#salt-s-loader-interface

https://github.com/saltstack/salt/blob/2017.7/salt/loader.py#L824

```
import salt.config
import salt.loader

__opts__ = salt.config.minion_config('/etc/salt/minion')
__utils__ = salt.loader.utils(__opts__)
__runners__ = salt.loader.runners(__opts__, __utils__)
```

And then they will be available through `__runners__`

Daniel
