### ISSUE TITLE
Unable to specify a returner using runners (salt-run or salt.runner)

### ISSUE THREAD

**Issue by wasabi222** [saltstack/salt#44610]
### Description of Issue/Question
I'm not able to specify a returner when using `salt-run` on the cli, or in any context relating to runners. For instance, in a state.orchestrate .sls file, I can use `ret: slack` as an option for salt.function and salt.state, but not salt.runner.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
```
root@master:/srv/salt/host# cat ../orch/sanitize.sls
post_in_slack:
  salt.runner:
    - name: peer.add
    - arg:
       - 1.2.3.4
    - ret: slack
```
output:
```
master_master:
----------
          ID: post_down_in_slack
    Function: salt.runner
        Name: peer.add
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1843, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1795, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/saltmod.py", line 709, in runner
                  **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/saltutil.py", line 1444, in runner
                  full_return=full_return)
                File "/usr/lib/python2.7/dist-packages/salt/runner.py", line 153, in cmd
                  full_return)
post_down_in_slack:
                File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 228, in cmd
                  self.functions[fun], arglist, pub_data
                File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 323, in load_args_and_kwargs
                  salt.utils.invalid_kwargs(invalid_kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/utils/__init__.py", line 3277, in invalid_kwargs
                  raise SaltInvocationError(msg)
              SaltInvocationError: The following keyword arguments are not valid: ret=network_slack
     Started: 17:35:24.682697
    Duration: 11.541 ms
     Changes:

Summary for master_master
------------
Succeeded: 0
Failed:    1
------------
```

From the cli, it looks like this:

```
root@master:/srv/salt/host# salt-run peer.add '1.2.3.4' --return network_slack
Usage: salt-run [options] <function> [arguments]

salt-run: error: no such option: --return
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

see above

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.11.2
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 19 2017, 14:48:08)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.1.6

System Versions:
           dist: debian 9.1
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-3-amd64
         system: Linux
        version: debian 9.1
```

It looks like the cmd function here does not have a `ret` argument: https://github.com/saltstack/salt/blob/develop/salt/runner.py#L145

pinging @mirceaulinic and @gtmanfred at Mircea's request. Thanks for looking at this!

**Comment by gtmanfred** [comment]
This should definitely be added, thanks for the request.

Daniel

**Comment by mirceaulinic** [comment]
Please reopen this @stale.

**Comment by gtmanfred** [comment]
@saltstack/team-core can you reopen this for @mirceaulinic

Thanks,
Daniel

**Comment by mirceaulinic** [comment]
This is still an issue that needs to be fixed.

**Comment by skob** [comment]
4 years? :-)
