### ISSUE TITLE
Salt crashes when using prereq with module.run

### ISSUE THREAD

**Issue by rlifshay** [saltstack/salt#44639]
### Description of Issue/Question
When using prereq on a state with module.run salt crashes and outputs a stacktrace. It started doing this sometime after v2016.11.8. After a little debugging the issue seems to be that module.run is wrapped in a decorator and state.py line 1796 is not expecting that.

### Setup
test.sls:
```
test1:
 cmd.run:
  - name: echo hi
  - prereq:
    - module: test2

test2:
 module.run:
  - name: test.ping
```
### Stacktrace
```
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'module' object has no attribute '__opts__'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 391, in salt_call
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 204, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 593, in apply_
    return highstate(**kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 892, in highstate
    orchestration_jid=orchestration_jid)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 3695, in call_highstate
    return self.state.call_high(high, orchestration_jid)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2531, in call_high
    ret = self.call_chunks(chunks)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2017, in call_chunks
    running = self.call_chunk(low, running, chunks)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2345, in call_chunk
    running = self.call_chunk(chunk, running, chunks)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2362, in call_chunk
    self.pre[tag] = self.call(low, chunks, running)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 1796, in call
    test = sys.modules[self.states[cdata['full']].__module__].__opts__['test']
AttributeError: 'module' object has no attribute '__opts__'
```

### Analysis
I did some debugging with a different state tree and found part of the issue.

Debugging code I added on the line before the one causing the exception:
```
log.warn("%s: %s: %s", cdata['full'], self.states[cdata['full']], self.states[cdata['full']].__module__)
```
Resulting messages illustrating the unexpected decorator:
```
...
[WARNING ] iptables.append: <function append at 0x217d140>: salt.loaded.int.states.iptables
[WARNING ] iptables.append: <function append at 0x217d140>: salt.loaded.int.states.iptables
[WARNING ] iptables.append: <function append at 0x217d140>: salt.loaded.int.states.iptables
[WARNING ] module.run: <function _decorate at 0x27090c8>: salt.utils.decorators
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
...
```

### Versions Report
```
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.2.1511 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-327.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

**Comment by Ch3LL** [comment]
I did a git bisect and it showed the commit c0f3d1e9ac33652dd4d1eb8b2a6d25416875c7b2 is the first bad commit.

ping @isbm any chance you can look here?

**Comment by isbm** [comment]
@Ch3LL can you assign me for the bug, please? (or I will likely miss it otherwise — too much emails from GitHub and stuff). At the moment not only that ruins `module.run` :wink:

**Comment by isbm** [comment]
I think this is due to the changes how calls are processed, so the decorator doesn't like it anymore. I will look.

**Comment by rlifshay** [comment]
@isbm was just noticing you never got assigned to remind you, so figured I would ping you instead ;)

**Comment by isbm** [comment]
@rallytime can you please assign me here? I will look at that _after_ the vacations. :wink: Happy New Year in the meanwhile!

**Comment by boltronics** [comment]
This still seems to be a problem in 2018.3.1.

**Comment by alexz-kh** [comment]
bump. issues still actual

**Comment by Ch3LL** [comment]
does anyone from @saltstack/team-core have time to dive into a fix here?

**Comment by waynew** [comment]
I've been in this code recently, I can take a look on Thursday.
