### ISSUE TITLE
runner module http.query with params doesn't work

### ISSUE THREAD

**Issue by thuhak** [saltstack/salt#44643]
### Description of Issue/Question

function:
```
sudo salt-run http.query 'http://url/api/v1/select' method=POST params="name=127.0.0.1"
```

result:

```
Exception occurred in runner http.query: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 382, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/runners/http.py", line 39, in query
    ret = salt.utils.http.query(url=url, opts=__opts__, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/utils/http.py", line 182, in query
    url_full = tornado.httputil.url_concat(url, params) if params else url
  File "/usr/lib64/python2.7/site-packages/tornado/httputil.py", line 597, in url_concat
    return url + urlencode(args)
  File "/usr/lib64/python2.7/urllib.py", line 1312, in urlencode
    raise TypeError
TypeError: not a valid non-string sequence or mapping object
```

It seems that *http.py* deliver params as str directly to the url_concat function. I doubt it was caused by tornado, so i upgrade tornado to the latest version, and the result turns to this:

```
Exception occurred in runner http.query: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 382, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/runners/http.py", line 39, in query
    ret = salt.utils.http.query(url=url, opts=__opts__, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/utils/http.py", line 182, in query
    url_full = tornado.httputil.url_concat(url, params) if params else url
  File "/usr/lib64/python2.7/site-packages/tornado/httputil.py", line 618, in url_concat
    raise TypeError(err)
TypeError: 'args' parameter should be dict, list or tuple. Not <type 'str'>
```

### Versions Report

```
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.6.0
       cherrypy: 11.0.0
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.10.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

**Comment by Ch3LL** [comment]
looks like i'm able to replicate this. and when debugging i see its trying to see if query is a tuple when in fact its a string like so: `'name=127.0.0.1'` so when it trys to do this check: `if len(query) and not isinstance(query[0], tuple):` It raises the typeerror.

so i think you are right i think on the runnner we would need to parse out the params  to ensure we don't pass as a string.

ping @techhat seems you have done some work here. mind taking a look here?

**Comment by shorawitz** [comment]
I had to switch the 'params' key to 'data' and pass in the parameters as a dict and then it works.
