### ISSUE TITLE
file.blockreplace in win_file.py broken in 2017.7.2

### ISSUE THREAD

**Issue by t0fik** [saltstack/salt#44641]
Using file.blockreplace produce below exeception:
 An exception occurred in this state: Traceback (most recent call last):
                File "C:\salt\bin\lib\site-packages\salt\state.py", line 1843, in call
                  **cdata['kwargs'])
                File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1795, in wrapper
                  return f(*args, **kwargs)
                File "C:\salt\bin\lib\site-packages\salt\states\file.py", line 4225, in blockreplace
                  show_changes=show_changes
                File "C:\salt\bin\lib\site-packages\salt\modules\file.py", line 2476, in blockreplace
                  perms['mode'])
                File "C:\salt\bin\lib\site-packages\salt\modules\win_file.py", line 1712, in check_perms
                  if 'applies_to' in grant_perms[user]:
              TypeError: string indices must be integers

### Setup
agent_{{ agentno }}_add_tags:
  file.prepend:
    - name: {{ attributes_path }}
    - text:
      - '#-- salt managed block start --=-- start --'
      - '#--  salt managed block end  --=--  end  --'

agent_{{ agentno }}_set_attributes:
  file.blockreplace:
    - name: {{ attributes_path }}
    - marker_start: '#-- salt managed block start --=-- start --'
    - marker_end: '#--  salt managed block end  --=--  end  --'
    - content: |
        OS={{ grains['os'] }}
        OSRELEASE={{ grains['osrelease'] }}
    - require:
      - agent_{{ agentno }}_add_tags

### Steps to Reproduce Issue
Runing on windows minion:
salt-call state.sls path.to.state

### Versions Report
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.4.0
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6
 
System Versions:
           dist:   
         locale: cp1252
        machine: AMD64
        release: 2012ServerR2
         system: Windows
        version: 2012ServerR2 6.3.9600  Multiprocessor Free

**Comment by t0fik** [comment]
Issue was caused by wrong states execution order
