### ISSUE TITLE
SaltInvocationError: An ADML file in the specified ADML language "en-US" and the fallback language "en-US" do not exist for the ADMX "HealthService.admx"

### ISSUE THREAD

**Issue by Prakash82x** [saltstack/salt#44668]
###Unable to use lgpo.set on Windows server 2012 R2.
Getting following error:
SaltInvocationError: An ADML file in the specified ADML language "en-US" and the fallback language "en-US" do not exist for the ADMX "HealthService.admx".

###here is the .sls file
server_policy:
  lgpo.set:
    - computer_policy:
"Accounts: Guest account status": Disabled

### Error Log
----------
          ID: server_policy
    Function: lgpo.set
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "c:\salt\bin\lib\site-packages\salt\state.py", line 1765, in call
                  **cdata['kwargs'])
                File "c:\salt\bin\lib\site-packages\salt\loader.py", line 1705, in wrapper
                  return f(*args, **kwargs)
                File "c:\salt\bin\lib\site-packages\salt\states\win_lgpo.py", line 226, in set_
                  adml_language=adml_language)
                File "c:\salt\bin\lib\site-packages\salt\modules\win_lgpo.py", line 4806, in get_policy_info
                  display_language=adml_language)
                File "c:\salt\bin\lib\site-packages\salt\modules\win_lgpo.py", line 2788, in _processPolicyDefinitions
                  t_admfile))
              SaltInvocationError: An ADML file in the specified ADML language "en-US" and the fallback language "en-US" do not exist for the ADMX "HealthService.admx".
     Started: 03:04:00.086000
    Duration: 172.0 ms
     Changes:

### Versions Report
##Salt Master Version
salt-master --version
salt-master 2016.11.7 (Carbon)

##Salt Minion Version
salt myminionname.domain.com --version
salt 2016.11.7 (Carbon)

**Comment by Ch3LL** [comment]
Looking at the docs it states: 
> Single policies must specify the policy name, the setting, and the policy class (Machine/User/Both)

If you update the state using those parameters does it work?


I also noticed your states format looked wrong:

```
server_policy:
  lgpo.set:
    - computer_policy:
"Accounts: Guest account status": Disabled
```

but this could be of course be a case of copy/pasting not pasting correctly. It should be:

```
server_policy:
  lgpo.set:
    - computer_policy:
          "Accounts: Guest account status": Disabled
```

Just want to confirm teh spacing is correct

**Comment by Prakash82x** [comment]
Thanks for looking, yes the spacing is correct in the state,
to add to it, there are 100s of other minions which has the same minion version (2016.11.7) installed on them and this state is working just fine on them but only few of the servers with this version are afailing.

**Comment by Ch3LL** [comment]
Thanks for confirming this. ping @twangboy i think you have been recently doing some work in this module. Is this a known issue currently ? Or any ideas on a fix?

**Comment by twangboy** [comment]
I believe this has been fixed by https://github.com/saltstack/salt/pull/43896 and will be in 2017.7.3
