### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte in 2017.7.2

### ISSUE THREAD

**Issue by jfoboss** [saltstack/salt#44666]
### Description of Issue/Question

There are errors with unicode filenames in `file.recurse`

### Setup
Nothing special, see above.

### Steps to Reproduce Issue
1. Put a file with unicode name like `<formula>/files/пример.txt` into a formula.
2. Try file.recurse:
```
# UserParameters
/tmp/test:
  file.recurse:
    - source: salt://{{ slspath }}/files
    - dir_mode: 755
    - file_mode: 644
    - include_empty: True
```
3. Get the error:
```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 87: ordinal not in range(128)
2017-11-23 10:09:29,078 [salt.master      ][ERROR   ][9700] Error in function _file_list:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 1629, in run_func
    ret = getattr(self, func)(load)
  File "/usr/lib/python2.7/site-packages/salt/fileserver/__init__.py", line 756, in file_list
    ret.update(self.servers[fstr](load))
  File "/usr/lib/python2.7/site-packages/salt/fileserver/roots.py", line 421, in file_list
    return _file_lists(load, 'files')
  File "/usr/lib/python2.7/site-packages/salt/fileserver/roots.py", line 397, in _file_lists
    _add_to(ret['files'], path, root, files)

```

### Versions Report
```
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.10.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.5.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

**Comment by jfoboss** [comment]
Found similar issue (but it's closed): https://github.com/saltstack/salt/issues/27789

**Comment by Ch3LL** [comment]
looks you might be runing into this? https://github.com/saltstack/salt/issues/40578 Does that look the same?

**Comment by jfoboss** [comment]
@Ch3LL Yes, it does.

**Comment by Ch3LL** [comment]
Closed as a duplicate, so feel freee to monitor that issue :)

**Comment by jfoboss** [comment]
Thanks :)
