### ISSUE TITLE
salt-ssh: pillar.get merge_nested_lists not supported

### ISSUE THREAD

**Issue by siv0** [saltstack/salt#44669]
### Description of Issue/Question
When trying to use the `merge_nested_lists` kwarg of `pillar.get` via `salt-ssh` I get the following error:

### Setup
Minimal Salt state file to reproduce: 
```
{% import_yaml "test/defaults.yaml" as default_settings %}
{% set test_default = default_settings['test'] %}

{% set testvar = salt['pillar.get']('test', default=test_default, merge=True, merge_nested_lists=True ) %}
```
### Steps to Reproduce Issue
```
salt-ssh -i 'vagrantbox*' state.apply test test=True
[ERROR   ] Rendering exception occurred: Jinja error: get() got an unexpected keyword argument 'merge_nested_lists'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 413, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 3, in top-level template code
TypeError: get() got an unexpected keyword argument 'merge_nested_lists'

; line 3

---

```

### Versions Report
```
salt --versions-report
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 19 2017, 14:48:08)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.1 
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-3-amd64
         system: Linux
        version: debian 9.1
```

**Comment by Ch3LL** [comment]
looks like i'm able to replicate this back to 2016.11.5 so not a regression but def need to get this fixed.

ping @saltstack/team-ssh any ideas here?
