### ISSUE TITLE
if return dict key is tuple throws "AuthenticationError: message authentication failed"

### ISSUE THREAD

**Issue by vnitinv** [saltstack/salt#44710]
### Description of Issue/Question
I have defined a custom module/function

/srv/salt# tail -n 3 _modules/nitin.py 
```python
def fn():
    return {(23,) : {'color': 0, 'rate': 0}}
```
if the dict key is tuple (which is valid) as in this case (23,) is a tuple, salt throws some abnormal error
AuthenticationError: message authentication failed

Due to the above error cli also returns "Minion did not return"
```
/srv/salt# salt '*' nitin.fn
proxy01:
    Minion did not return. [No response]
```

If I change tuple key to just 23 everything works perfectly fine.

### Steps to Reproduce Issue

log trace
```
[INFO    ] User root Executing command nitin.fn with jid 20171128131907973139
[DEBUG   ] Command details {'tgt_type': 'glob', 'jid': '20171128131907973139', 'tgt': '*', 'ret': '', 'user': 'root', 'arg': [], 'fun': 'nitin.fn'}
[INFO    ] Starting a new job with PID 715
[DEBUG   ] LazyLoaded nitin.fn
[DEBUG   ] LazyLoaded direct_call.get
[DEBUG   ] Minion return retry timer set to 5 seconds (randomized)
[INFO    ] Returning information for job: 20171128131907973139
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/proxy', 'proxy01', 'tcp://127.0.0.1:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/proxy', 'proxy01', 'tcp://127.0.0.1:4506')
[DEBUG   ] Failed to authenticate message
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/proxy', 'proxy01', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/proxy/minion.pem
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/proxy/minion_event_7aa4174404_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/proxy/minion_event_7aa4174404_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/proxy/minion_event_7aa4174404_pull.ipc
[DEBUG   ] Sending event: tag = salt/auth/creds; data = {'_stamp': '2017-11-28T13:19:08.104161', 'creds': {'publish_port': 4505, 'aes': '69YkVEsiegrW7mQmWMgdL0Wc7njGtrmO7qUOptnSMFPh0c5BvJ/zQi55yVLxSgBgVXDED8Kcr7k=', 'master_uri': 'tcp://127.0.0.1:4506'}, 'key': ('/etc/salt/pki/proxy', 'proxy01', 'tcp://127.0.0.1:4506')}
[DEBUG   ] Minion of "localhost" is handling event tag 'salt/auth/creds'
[DEBUG   ] Updating auth data for ('/etc/salt/pki/proxy', 'proxy01', 'tcp://127.0.0.1:4506'): {'publish_port': 4505, 'aes': '69YkVEsiegrW7mQmWMgdL0Wc7njGtrmO7qUOptnSMFPh0c5BvJ/zQi55yVLxSgBgVXDED8Kcr7k=', 'master_uri': 'tcp://127.0.0.1:4506'} -> {'publish_port': 4505, 'aes': '69YkVEsiegrW7mQmWMgdL0Wc7njGtrmO7qUOptnSMFPh0c5BvJ/zQi55yVLxSgBgVXDED8Kcr7k=', 'master_uri': 'tcp://127.0.0.1:4506'}
[DEBUG   ] Failed to authenticate message
Exception in thread 20171128131907973139:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/salt/minion.py", line 3331, in _target
    Minion._thread_return(minion_instance, opts, data)
  File "/usr/local/lib/python2.7/dist-packages/salt/minion.py", line 1558, in _thread_return
    timeout=minion_instance._return_retry_timer()
  File "/usr/local/lib/python2.7/dist-packages/salt/minion.py", line 1734, in _return_pub
    ret_val = self._send_req_sync(load, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/salt/minion.py", line 1239, in _send_req_sync
    return channel.send(load, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/salt/utils/async.py", line 75, in wrap
    ret = self._block_future(ret)
  File "/usr/local/lib/python2.7/dist-packages/salt/utils/async.py", line 85, in _block_future
    return future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 271, in send
    ret = yield self._crypted_transfer(load, tries=tries, timeout=timeout, raw=raw)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 243, in _crypted_transfer
    ret = yield _do_transfer()
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 230, in _do_transfer
    data = self.auth.crypticle.loads(data, raw)
  File "/usr/local/lib/python2.7/dist-packages/salt/crypt.py", line 1310, in loads
    data = self.decrypt(data)
  File "/usr/local/lib/python2.7/dist-packages/salt/crypt.py", line 1279, in decrypt
    raise AuthenticationError('message authentication failed')
AuthenticationError: message authentication failed
```

### Versions Report
```
/srv/salt# salt --versions-report
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: 1.11.2
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.1.6
 
System Versions:
           dist: Ubuntu 14.04 trusty
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.9.31-moby
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by vnitinv** [comment]
@cro Can you please us with this?

**Comment by thatch45** [comment]
This has to do with legal serialization of data. since a tuple is not serializable via json/msgpack it gets serialized as a list, and then when the data is loaded up it is an error because you can't have a list as a key to a dict.
So, in a nutshell, I don't think this can be fixed
