### ISSUE TITLE
Integration tests fail on the develop branch on Windows

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#44774]
### Description of Issue/Question
Integration tests are failing on the develop branch on Windows with the following stack trace:
```
TypeError: environment can only contain strings
Traceback (most recent call last):
  File "runtests.py", line 825, in <module>
    main()
  File "runtests.py", line 808, in main
    status = parser.run_integration_tests()
  File "runtests.py", line 700, in run_integration_tests
    with TestDaemon(self):
  File "C:\\Salt-Dev\\salt\tests\integration\__init__.py", line 210, in __enter__
    self.start_zeromq_daemons()
  File "C:\\Salt-Dev\\salt\tests\integration\__init__.py", line 294, in start_zeromq_daemons
    start_timeout=30)
  File "C:\\Salt-Dev\\salt\tests\support\processes.py", line 151, in start_daemon
    process.start()
  File "c:\salt-dev\pytest-salt\pytestsalt\utils.py", line 426, in start
    self._terminal = nb_popen.NonBlockingPopen(proc_args, env=self.environ, cwd=self.cwd)
  File "c:\salt-dev\salt\salt\utils\nb_popen.py", line 67, in __init__
    super(NonBlockingPopen, self).__init__(*args, **kwargs)
  File "C:\Python27\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
TypeError: environment can only contain strings
```

You see this same stack trace on Jenkins branch tests for Develop on Windows
https://jenkins.saltstack.com/job/branch_tests/job/develop/job/salt-dev-c7-windows-py2/

### Setup
Setup salt from the develop branch
install pytest-salt

### Steps to Reproduce Issue
run any integration test
`python runtest.py -v -n integration.states.test_pkg`

### Versions Report
Windows 2012r2
Head of develop branch

**Comment by twangboy** [comment]
Bisected to: https://github.com/sacren/salt/commit/7410ffd92a235f9e4e11b3d7693be5a24de0f810
@gtmanfred
