### ISSUE TITLE
develop strack traces on core grains on solaris like systems

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#44797]
### Description of Issue/Question
```
raceback (most recent call last):
  File "./salt-call", line 14, in <module>
    salt_call()
  File "/opt/saltdev/lib/python2.7/site-packages/salt/scripts.py", line 390, in salt_call
    import salt.cli.call
  File "/opt/saltdev/lib/python2.7/site-packages/salt/cli/call.py", line 5, in <module>
    import salt.utils.parsers
  File "/opt/saltdev/lib/python2.7/site-packages/salt/utils/parsers.py", line 28, in <module>
    import salt.config as config
  File "/opt/saltdev/lib/python2.7/site-packages/salt/config/__init__.py", line 100, in <module>
    _DFLT_IPC_WBUFFER = _gather_buffer_space() * .5
  File "/opt/saltdev/lib/python2.7/site-packages/salt/config/__init__.py", line 93, in _gather_buffer_space
    grains = salt.grains.core._memdata(os_data)
  File "/opt/saltdev/lib/python2.7/site-packages/salt/grains/core.py", line 509, in _memdata
    grains.update(_sunos_memdata())
  File "/opt/saltdev/lib/python2.7/site-packages/salt/grains/core.py", line 478, in _sunos_memdata
    grains['swap_total'] = int(swap_total) // 1024
ValueError: invalid literal for int() with base 10: '3453024k'
```

### Setup
```salt-call --local test.ping```

### Steps to Reproduce Issue
1. checkout develop
2. python setup.py install
3. run salt-call/salt/...

### Versions Report
```
[root@carbon /opt/saltdev/bin]# ./salt-call --versions-report
Traceback (most recent call last):
  File "./salt-call", line 14, in <module>
    salt_call()
  File "/opt/saltdev/lib/python2.7/site-packages/salt/scripts.py", line 390, in salt_call
    import salt.cli.call
  File "/opt/saltdev/lib/python2.7/site-packages/salt/cli/call.py", line 5, in <module>
    import salt.utils.parsers
  File "/opt/saltdev/lib/python2.7/site-packages/salt/utils/parsers.py", line 28, in <module>
    import salt.config as config
  File "/opt/saltdev/lib/python2.7/site-packages/salt/config/__init__.py", line 100, in <module>
    _DFLT_IPC_WBUFFER = _gather_buffer_space() * .5
  File "/opt/saltdev/lib/python2.7/site-packages/salt/config/__init__.py", line 93, in _gather_buffer_space
    grains = salt.grains.core._memdata(os_data)
  File "/opt/saltdev/lib/python2.7/site-packages/salt/grains/core.py", line 509, in _memdata
    grains.update(_sunos_memdata())
  File "/opt/saltdev/lib/python2.7/site-packages/salt/grains/core.py", line 478, in _sunos_memdata
    grains['swap_total'] = int(swap_total) // 1024
ValueError: invalid literal for int() with base 10: '3453084k'
```

Can't run this.

**Comment by sjorge** [comment]
```def _sunos_memdata():
    '''
    Return the memory information for SunOS-like systems
    '''
    grains = {'mem_total': 0, 'swap_total': 0}

    prtconf = '/usr/sbin/prtconf 2>/dev/null'
    for line in __salt__['cmd.run'](prtconf, python_shell=True).splitlines():
        comps = line.split(' ')
        if comps[0].strip() == 'Memory' and comps[1].strip() == 'size:':
            grains['mem_total'] = int(comps[2].strip())

    swap_cmd = salt.utils.path.which('swap')
    swap_total = __salt__['cmd.run']('{0} -s'.format(swap_cmd)).split()[1]
    grains['swap_total'] = int(swap_total) // 1024
    return grains
```

Same result on both OmniOS, SmartOS and OpenIndiana
```
[root@carbon /opt/saltdev/bin]# swap -s
total: 3413956k bytes allocated + 839020k reserved = 4252976k used, 191950308k available
```

**Comment by sjorge** [comment]
```
diff --git a/salt/grains/core.py b/salt/grains/core.py
index da541edf56..45aef77730 100644
--- a/salt/grains/core.py
+++ b/salt/grains/core.py
@@ -475,6 +475,8 @@ def _sunos_memdata():

     swap_cmd = salt.utils.path.which('swap')
     swap_total = __salt__['cmd.run']('{0} -s'.format(swap_cmd)).split()[1]
+    if swap_total.upper().endswith('K'):
+        swap_total = swap_total[:-1]
     grains['swap_total'] = int(swap_total) // 1024
     return grains
```

Here is a simple fix, but I am not sure this is even doing what you expect it to do.

From the man page:

```
       -s

           Print summary information about total swap space usage and
           availability:

           allocated

               The total amount of swap space in bytes currently allocated for
               use as backing store.


           reserved

               The total amount of swap space in bytes not currently
               allocated, but claimed by memory mappings for possible future
               use.


           used

               The total amount of swap space in bytes that is either
               allocated or reserved.


           available

               The total swap space in bytes that is currently available for
               future reservation and allocation.

           These numbers include swap space from all configured swap areas as
           listed by the -l option, as well swap space in the form of physical
           memory.
```

**Comment by sjorge** [comment]
@rallytime I think swap_total should probably be the last value (available) instead of the one it is trying to get now?

I can do a PR to fix this but I am unsure how to proceed. The quick patch above fixes the issue due to the inclusion of 'k'. But I think the value itself is also the wrong one.

**Comment by sjorge** [comment]
OK, so we want available + used to get total swap! I have create a PR with a fix.

**Comment by gtmanfred** [comment]
That PR looks great!

Thanks @sjorge 
Daniel

**Comment by sjorge** [comment]
The fix for this was merge, closing this issue
