### ISSUE TITLE
Unhandled exception on Win32_NetworkAdapterConfiguration

### ISSUE THREAD

**Issue by abartlett** [saltstack/salt#44813]
### Description of Issue/Question
On an host in AWS running Windows Server 2016, we get the following un-handled exception in salt-minion.  Host has one network interface with an IPv4 address.

```
[    ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: winmgmts:.Win32_NetworkAdapterConfiguration
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-minion", line 26, in <module>
    salt_minion()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 168, in salt_minion
    minion.start()
  File "C:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 345, in start
    self.minion.tune_in()
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 890, in tune_in
    self._spawn_minions()
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 849, in _spawn_minions
    jid_queue=self.jid_queue,
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 830, in _create_minion_object
    jid_queue=jid_queue)
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 968, in __init__
    self.opts['grains'] = salt.loader.grains(opts)
  File "C:\salt\bin\lib\site-packages\salt\loader.py", line 717, in grains
    ret = funcs[key]()
  File "C:\salt\bin\lib\site-packages\salt\grains\core.py", line 1876, in hwaddr_interfaces
    ifaces = _get_interfaces()
  File "C:\salt\bin\lib\site-packages\salt\grains\core.py", line 1211, in _get_interfaces
    _INTERFACES = salt.utils.network.interfaces()
  File "C:\salt\bin\lib\site-packages\salt\utils\network.py", line 893, in interfaces
    return win_interfaces()
  File "C:\salt\bin\lib\site-packages\salt\utils\network.py", line 849, in win_interfaces
    for iface in c.Win32_NetworkAdapterConfiguration(IPEnabled=1):
  File "C:\salt\bin\lib\site-packages\wmi.py", line 1147, in __getattr__
    return getattr (self._namespace, attribute)
  File "C:\salt\bin\lib\site-packages\win32com\client\dynamic.py", line 522, in __getattr__
    raise AttributeError("%s.%s" % (self._username_, attr))
AttributeError: winmgmts:.Win32_NetworkAdapterConfiguration
salt_minion()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 168, in salt_minion
    minion.start()
  File "C:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 345, in start
    self.minion.tune_in()
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 890, in tune_in
    self._spawn_minions()
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 849, in _spawn_minions
    jid_queue=self.jid_queue,
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 830, in _create_minion_object
    jid_queue=jid_queue)
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 968, in __init__
    self.opts['grains'] = salt.loader.grains(opts)
  File "C:\salt\bin\lib\site-packages\salt\loader.py", line 717, in grains
    ret = funcs[key]()
  File "C:\salt\bin\lib\site-packages\salt\grains\core.py", line 1876, in hwaddr_interfaces
    ifaces = _get_interfaces()
  File "C:\salt\bin\lib\site-packages\salt\grains\core.py", line 1211, in _get_interfaces
    _INTERFACES = salt.utils.network.interfaces()
  File "C:\salt\bin\lib\site-packages\salt\utils\network.py", line 893, in interfaces
    return win_interfaces()
  File "C:\salt\bin\lib\site-packages\salt\utils\network.py", line 849, in win_interfaces
    for iface in c.Win32_NetworkAdapterConfiguration(IPEnabled=1):
  File "C:\salt\bin\lib\site-packages\wmi.py", line 1147, in __getattr__
    return getattr (self._namespace, attribute)
  File "C:\salt\bin\lib\site-packages\win32com\client\dynamic.py", line 522, in __getattr__
    raise AttributeError("%s.%s" % (self._username_, attr))
AttributeError: winmgmts:.Win32_NetworkAdapterConfiguration
```

### Setup
salt-minion 2017.7.2

### Steps to Reproduce Issue
execute salt-minion.bat or salt-minion-debug.bat.  Will not run as service.

### Versions Report
```
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.4.0
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2016Server
         system: Windows
        version: 2016Server 10.0.14393  Multiprocessor Free
```

**Comment by gtmanfred** [comment]
Which ami are you using and which region?

I am unable to replicate this in us-east-1 with the newest windows 2016 core image.

It is finding the network interfaces fine and putting them in grains.

Thanks,
Daniel

**Comment by abartlett** [comment]
This was a custom AMI. We traced this back to some kind of WMI issue with
Windows itself, a recycle of the WMI service & dependencies allowed salt to
start, but we were still left with the unhandled exception for whatever
issue WMI was having.

**Comment by gtmanfred** [comment]
@twangboy can you take a look at this?

Thanks,
Daniel

**Comment by twangboy** [comment]
I can't replicate this. I would suspect something wrong with the WMI repository.

https://blogs.technet.microsoft.com/askperf/2009/04/13/wmi-rebuilding-the-wmi-repository/

**Comment by twangboy** [comment]
@abartlett Does the above process by @xenophonf fix your issue?

**Comment by neighbour-oldhuang** [comment]
我也也遇到这个问题了，windows2019，salt2015  和 salt3003 都会遇到这个问题，启动不了
