### ISSUE TITLE
Salt-Cloud WinRM fails without retrying

### ISSUE THREAD

**Issue by jonlabroad** [saltstack/salt#44889]
### Description of Issue/Question
When trying to create a VMWare Windows 2008 R2 minion, utils/cloud.py wait_for_winrm() fails without retrying the connection. The reason is because only the WinRMTransportError exception is caught, if any other exception occurs, the connection is not retried and it bails out with a failure:
```
[ERROR   ] There was a profile error: HTTPConnectionPool(host='10.89.206.125', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fabd8d4a810>: Failed to establish a new connection: [Errno 111] Connection refused',))
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 284, in run
    self.config.get('names')
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1448, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1278, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/vmware.py", line 2726, in create
    out = __utils__['cloud.bootstrap'](vm_, __opts__)
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 546, in bootstrap
    deployed = deploy_windows(**deploy_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 1031, in deploy_windows
    timeout=port_timeout * 60, use_ssl=winrm_use_ssl)
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 861, in wait_for_winrm
    r = s.run_cmd('sc query winrm')
  File "/usr/local/lib/python2.7/dist-packages/winrm/__init__.py", line 37, in run_cmd
    shell_id = self.protocol.open_shell()
  File "/usr/local/lib/python2.7/dist-packages/winrm/protocol.py", line 132, in open_shell
    res = self.send_message(xmltodict.unparse(req))
  File "/usr/local/lib/python2.7/dist-packages/winrm/protocol.py", line 207, in send_message
    return self.transport.send_message(message)
  File "/usr/local/lib/python2.7/dist-packages/winrm/transport.py", line 184, in send_message
    response = self.session.send(prepared_request, timeout=self.read_timeout_sec)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='10.89.206.125', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fabd8d4a810>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

If I modify utils/cloud.py to catch all exceptions, it will continue to retry as expected and eventually connects successfully after a couple minutes.
Is it intended that the retry only occurs on a specific exception, and immediately fails on any other? In my case, that behavior is needlessly preventing creation of the VM, where it will eventually succeed.

### Setup
Cloud provider:
```
vcenter1:
  driver: vmware
  user: [REDACTED]
  password: [REDACTED]
  url: [REDACTED]
```
Cloud profile:
```
vmware-www-template:
  provider: vcenter1
  clonefrom: [REDACTED]
  cluster: [REDACTED]
  datacenter: [REDACTED]
  power_on: True
  extra_config:
    mem.hotadd: 'yes'

  deploy: True
  minion:
    master: [REDACTED]

  #For Windows VM
  use_winrm: True
  winrm_use_ssl: False
  win_username: [REDACTED]
  win_password: [REDACTED]
  win_organization_name: [REDACTED]
  plain_text: True
  win_installer: /Salt-Minion-2017.7.2-Py2-AMD64-Setup.exe
  win_user_fullname: Windows User
```

### Steps to Reproduce Issue
```
salt-cloud -p vmware-www-template hotrod001 -l debug
```

### Versions Report
```
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.11.2
       cherrypy: 3.2.3
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 20 2017, 18:23:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.4.0-97-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
Minion is at 2017.7.2

**Comment by garethgreenaway** [comment]
@jonlabroad Thanks for the report.  Can you provide some information on what the particular exceptions are that are causing the code to exit before creating the VM?

**Comment by jonlabroad** [comment]
This is the exception:
```
[DEBUG   ] Caught unknown exception: <class 'requests.exceptions.ConnectionError'>
HTTPConnectionPool(host='10.89.206.123', port=5985): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f92e3e07a10>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by calc84maniac** [comment]
I ran into this same issue myself, and I suppose another way to look at the problem is that `wait_for_port` is being called only on the SMB port and not on the WinRM port. The SMB port seems to be available much earlier in the system startup, whereas the WinRM service can take a while longer to start listening (possibly due to waiting for newly added network interfaces to be identified as private, at least in my use case).

Adding a `wait_for_port` call at the beginning of the `wait_for_winrm` function fixed the error for me, but it might still be worth looking into the exception handling there if pywinrm isn't filtering them as expected.

**Comment by twangboy** [comment]
The above PR implements the fix as suggested by @calc84maniac
