### ISSUE TITLE
pkg.install fails for win\repo-ng

### ISSUE THREAD

**Issue by andycapp92** [saltstack/salt#44924]
I have an issue on a windows system running with 'proxy_host', 'proxy_port' and 'backend: requests' set where a valid win repo package will install using salt-call locally without error...  but when executed from the master....

### Steps to Reproduce Issue
```
master:~$ sudo salt 'minion' pkg.install 7zip
minion:
    The minion function caused an exception: Traceback (most recent call last):
      File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1470, in _thread_return
        return_data = executor.execute()
      File "c:\salt\bin\lib\site-packages\salt\executors\direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "c:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 1210, in install
        cached_pkg = __salt__['cp.cache_file'](installer, saltenv)
      File "c:\salt\bin\lib\site-packages\salt\modules\cp.py", line 474, in cache_file
        result = _client().cache_file(path, saltenv)
      File "c:\salt\bin\lib\site-packages\salt\fileclient.py", line 189, in cache_file
        return self.get_url(path, '', True, saltenv, cachedir=cachedir)
      File "c:\salt\bin\lib\site-packages\salt\fileclient.py", line 691, in get_url
        **get_kwargs
      File "c:\salt\bin\lib\site-packages\salt\utils\http.py", line 314, in query
        method, url, params=params, data=data, **req_kwargs
      File "c:\salt\bin\lib\site-packages\requests\sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "c:\salt\bin\lib\site-packages\requests\sessions.py", line 609, in send
        r = adapter.send(request, **kwargs)
      File "c:\salt\bin\lib\site-packages\requests\adapters.py", line 487, in send
        raise ConnectionError(e, request=request)
    ConnectionError: HTTPConnectionPool(host='d.7-zip.org', port=80): Max retries exceeded with url: /a/7z1604-x64.msi (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0000000006F63128>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

```

### Versions Report
```
master:~$ salt-call --versions-report
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.4.0-75-generic
         system: Linux
        version: Ubuntu 14.04 trusty


minion:
 Salt Version:
               Salt: 2017.7.2

    Dependency Versions:
               cffi: 1.10.0
           cherrypy: 10.2.1
           dateutil: 2.6.0
          docker-py: Not Installed
              gitdb: 2.0.3
          gitpython: 2.1.3
              ioflo: Not Installed
             Jinja2: 2.9.6
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: 1.0.6
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.17
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
       python-gnupg: 0.4.0
             PyYAML: 3.11
              PyZMQ: 16.0.2
               RAET: Not Installed
              smmap: 2.0.3
            timelib: 0.2.4
            Tornado: 4.5.1
                ZMQ: 4.1.6

    System Versions:
               dist:
             locale: cp1252
            machine: AMD64
            release: 2016Server
             system: Windows
            version: 2016Server 10.0.14393  Multiprocessor Free



```

**Comment by badcure** [comment]
@andycapp92 FYI I was running into a similar issue(but with libcurl). The master and minion are both 2017.7.2, and I am not seeing this issue. 

It could be due to the fact your master is an older version.

**Comment by garethgreenaway** [comment]
@andycapp92 Are you able to upgrade your master to 2017.7.2 as @badcure mentioned?  Also can you include the version of the requests library that you're using on the Windows host?

**Comment by andycapp92** [comment]
Hey guys:

I tried the upgrade to 2017.2 on the master - and ended with:

```
`Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Nov 23 2017, 15:49:48)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-75-generic
         system: Linux
        version: Ubuntu 14.04 trusty
`

```
I should have already done that - thank you for the patience....    No change to the behavior though....

@garethgreenaway : Here's my requests lib version...

```
Package python-requests:
p   2.2.1-1                                                                                          trusty                                                                       500
p   2.2.1-1ubuntu0.2                                                                                 trusty-security                                                              500
i   2.2.1-1ubuntu0.3                                                                                 trusty-updates                                                               500


```

**Comment by badcure** [comment]
@andycapp92 Ahh So I think I see. I removed the proxy_* config(but left the backend config) and it still works. It may be due to the global proxy settings. Running the command 
```
salt 'windows_server' proxy.get_proxy_win
```
shows a proxy for FTP, HTTP and HTTPS. I believe you can set it with:
```
salt 'windows_server' proxy.get_proxy_win server=proxyhostname port=proxyport
```

**Comment by andycapp92** [comment]
Thats the ticket - thank you @badcure 
time for me to read about the proxy module.
