### ISSUE TITLE
Can't pass data to jinja templated file for kubernetes.configmap_present

### ISSUE THREAD

**Issue by jryberg** [saltstack/salt#45018]
### Description of Issue/Question
I'm using a jinja template that are populated using two variables that I'm passing from the state. 

It's not possible to pass variables using kubernetes.configmap_present but It work perfectly fine when I'm using file.managed

#### State
```
Create testfile:
  file.managed:
    - name: /tmp/testfile.conf
    - instance: test
    - application: hello world
    - source: salt://test/files/testfile.conf
    - template: jinja

Create test configmap:
  kubernetes.configmap_present:
    - name: testconfigmap
    - instance: test
    - application: hello world
    - source: salt://test/files/testfile.conf
    - template: jinja
```

#### Jinja template
```
# software_configurations:k8n:containers:{{ instance }}:{{ application }}:config
```

### Steps to Reproduce Issue
Put state and template in place and run the state. 
```
----------
          ID: Create test configmap
    Function: kubernetes.configmap_present
        Name: testconfigmap
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1843, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1795, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/kubernetes.py", line 678, in configmap_present
                  **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/kubernetes.py", line 1070, in create_configmap
                  data = __read_and_render_yaml_file(source, template, saltenv)
                File "/usr/lib/python2.7/dist-packages/salt/modules/kubernetes.py", line 1383, in __read_and_render_yaml_file
                  opts=__opts__)
                File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 167, in render_tmpl
                  output = render_str(tmplstr, context, tmplpath)
                File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 431, in render_jinja_tmpl
                  buf=tmplstr)
              SaltRenderError: Jinja variable 'instance' is undefined
     Started: 17:43:56.840155
    Duration: 97.517 ms
     Changes:
----------
```

### Versions Report

The master are running Ubuntu 14.04, the minion 16.04

#### master
```
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Nov 23 2017, 15:49:48)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
         locale: UTF-8
        machine: x86_64
        release: 3.13.0-92-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```
#### minion
```
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 20 2017, 18:23:56)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.10.0-40-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by jryberg** [comment]
I have also tried this method with exactly the same result.

```
Create testfile:
  file.managed:
    - name: /tmp/testfile.conf
    - defaults:
        application: {{ name }}
        instance: {{ instance }}
    - source: salt://test/files/testfile.conf
    - template: jinja

Create bouncer configmap:
  kubernetes.configmap_present:
    - name: testconfigmap
    - defaults:
        application: {{ name }}
        instance: {{ instance }}
    - source: salt://test/files/testfile.conf
    - template: jinja
```

**Comment by gtmanfred** [comment]
It does not look like any of the `**kwargs` are passed to the yaml file when it is rendered, only grains pillars opts and __salt__.

I am going to mark this as a feature request.  I think that adding a defaults and a context like file.managed would be a great idea.

@flavio @brejoc Could yall take a look at adding this feature?

Thanks,
Daniel
