### ISSUE TITLE
cmd.run cwd should not be checked before preconditions (Regression?)

### ISSUE THREAD

**Issue by davelindquist-egistix** [saltstack/salt#45039]
### Description of Issue/Question

In exactly the same way as is described in the (theoretically fixed) #11497, salt appears to be checking preconditions before evaluating the cwd in cmd.run.

### Setup - My Exact Case
My exact case is:
```
oracle_createdockerimage:
  cmd.run:
    - name: '/tmp/oracle-docker-images/OracleDatabase/dockerfiles/buildDockerImage.sh -v 12.2.0.1 -s'
    - cwd: /tmp/oracle-docker-images/OracleDatabase/dockerfiles/
    - unless: {% raw %}'test -n "`docker image ls oracle/database:12.2.0.1-se2 --format "{{.ID}}"`"'{% endraw %}
```
In this particular instance:
- /tmp has been cleaned out by the OS -- it has no "oracle-docker-images" in it
- the "docker image ls" command is successful, because that image already exists

(The contents of /tmp/oracle-docker-images are a clone of https://github.com/oracle/docker-images, but the exact content doesn't matter since the directory is cleared out for this exercise.)

### Setup - Simplified Case
Here's a VERY simple case that will reproduce the problem:

**test/init.sls**:
```
test:
  cmd.run:
    - name: /bin/date
    - cwd: /doesntexist
    - unless: which /bin/date
```

### Steps to Reproduce Issue - My Exact Case
Running this SLS (as `state.apply` and with `test=True`) gives an error of (in red):
```
----------
          ID: oracle_createdockerimage
    Function: cmd.run
        Name: /tmp/oracle-docker-images/OracleDatabase/dockerfiles/buildDockerImage.sh -v 12.2.0.1 -s
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1843, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1795, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/cmd.py", line 842, in run
                  cret = mod_run_check(cmd_kwargs, onlyif, unless, creates)
                File "/usr/lib/python2.7/dist-packages/salt/states/cmd.py", line 365, in mod_run_check
                  cmd = __salt__['cmd.retcode'](unless, ignore_retcode=True, python_shell=True, **cmd_kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/cmdmod.py", line 1885, in retcode
                  **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/cmdmod.py", line 536, in _run
                  .format(cwd)
              CommandExecutionError: Specified cwd '/tmp/oracle-docker-images/OracleDatabase/dockerfiles/' either not absolute or does not exist
     Started: 09:08:30.894469
    Duration: 52.008 ms
     Changes:
----------
```
Commenting out the "cwd" entry and running again (as `state.apply` and with `test=True`) gives (in green):
```
----------
          ID: oracle_createdockerimage
    Function: cmd.run
        Name: /tmp/oracle-docker-images/OracleDatabase/dockerfiles/buildDockerImage.sh -v 12.2.0.1 -s
      Result: True
     Comment: unless execution succeeded
     Started: 09:08:16.476688
    Duration: 17.928 ms
     Changes:
----------
```

### Steps to Reproduce Issue - Simplified Case
```
$ salt "anyminion" state.apply test test=True
myminionname:
----------
          ID: test
    Function: cmd.run
        Name: /bin/date
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1843, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1795, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/cmd.py", line 842, in run
                  cret = mod_run_check(cmd_kwargs, onlyif, unless, creates)
                File "/usr/lib/python2.7/dist-packages/salt/states/cmd.py", line 365, in mod_run_check
                  cmd = __salt__['cmd.retcode'](unless, ignore_retcode=True, python_shell=True, **cmd_kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/cmdmod.py", line 1885, in retcode
                  **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/cmdmod.py", line 536, in _run
                  .format(cwd)
              CommandExecutionError: Specified cwd '/doesntexist' either not absolute or does not exist
     Started: 09:22:58.816604
    Duration: 2.575 ms
     Changes:

Summary for myminionname
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   2.575 ms
```

Again, commenting out the "cwd" and re-running works fine (no errors, no execution).

Also see examples in #11497, which was supposedly fixed in the 2015 version?

### Versions Report
Master & Minion versions are the same.  `salt --versions-report` gives:
```
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 19 2017, 14:48:08)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.2
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-4-amd64
         system: Linux
        version: debian 9.2
```

**Comment by gtmanfred** [comment]
I think the reason that this appeared again was that the cwd is now passed to the unless command.

It was previously not passed iirc, but when that "bug" was fixed, the cwd now being passed is causing this issue.

I have marked this as a bug.

Thanks for reporting.
Daniel

**Comment by humitos** [comment]
I'm having the same issue here. What would be a workaround for this if any? Thanks!

**Comment by davelindquist-egistix** [comment]
The only real workaround I can think of is to do the precondition in Jinja somehow and not template in the entire thing if the precondition isn't met.  Of course, that has it's own problems if anything depends on this state.

For my own part, the only thing I can do is just ignore the error each time I apply the state -- less than ideal.

**Comment by MartinMystikJonas** [comment]
+1

**Comment by boltronics** [comment]
Still an issue in 2019.2.2.

**Comment by garethgreenaway** [comment]
With the changes in https://github.com/saltstack/salt/pull/55974 to consolidate requisites and use them from the system wide state system this issue seems resolved.in the Sodium release, can someone please confirm.  Thanks!

**Comment by Cybso** [comment]
Please don't implement such fundamental design changes without deprecation period and warnings.

This change broke my "unless" test, since it expected to be executed in cwd, causing the command to be executed over and over again, until multiple machines finally crashes.

**Comment by dwoz** [comment]
Fixed in v3002 (Sodium) by #55974 (commit 2520ae867), which consolidated per-state `mod_run_check` into `State._run_check` and wrapped `cmd.retcode` in `try/except CommandExecutionError` so a missing `cwd` no longer escapes the precondition. Verified on 3006.x/3007.x/3008.x/master: `salt/state.py` carries the handler, and the original SLS now produces `Result: True, Comment: unless condition is true`. Regression coverage: `tests/pytests/unit/state/test_state_compiler.py::test_verify_unless_cmd_error` and `::test_verify_onlyif_cmd_error`.
