### ISSUE TITLE
authentication issues when using kwargs / args with publisher_acl

### ISSUE THREAD

**Issue by dkatsanikakis** [saltstack/salt#45066]
### Description of Issue/Question
i am trying to use publisher_acl with "kwargs" and "args" in order to provide access for a system user (other than root) to be able to execute salt commands. I do this execution of the command using ssh as per bellow:  

`    ssh testuser@myserver.net 'salt -b 1 server33 mymodule.test' `

Unfortunately i get  authentication errors. I tried all sorts of args/kwargs variations but still no luck. If i run the above command without the argument "-b 1" it works without any issues. The error i am receiving is the following:

```
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
EauthAuthenticationError: Failed to authenticate! This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 464, in salt_main
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/salt.py", line 59, in run
    self._run_batch()
  File "/usr/lib/python2.7/dist-packages/salt/cli/salt.py", line 242, in _run_batch
    batch = salt.cli.batch.Batch(self.config, eauth=eauth, parser=self.options)
  File "/usr/lib/python2.7/dist-packages/salt/cli/batch.py", line 36, in __init__
    self.minions, self.ping_gen, self.down_minions = self.__gather_minions()
  File "/usr/lib/python2.7/dist-packages/salt/cli/batch.py", line 62, in __gather_minions
    for ret in ping_gen:
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 769, in cmd_iter
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 337, in run_job
    return self._check_pub_data(pub_data)
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 256, in _check_pub_data
    'Failed to authenticate! This is most likely because this '
EauthAuthenticationError: Failed to authenticate! This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 464, in salt_main
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/salt.py", line 59, in run
    self._run_batch()
  File "/usr/lib/python2.7/dist-packages/salt/cli/salt.py", line 242, in _run_batch
    batch = salt.cli.batch.Batch(self.config, eauth=eauth, parser=self.options)
  File "/usr/lib/python2.7/dist-packages/salt/cli/batch.py", line 36, in __init__
    self.minions, self.ping_gen, self.down_minions = self.__gather_minions()
  File "/usr/lib/python2.7/dist-packages/salt/cli/batch.py", line 62, in __gather_minions
    for ret in ping_gen:
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 769, in cmd_iter
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 337, in run_job
    return self._check_pub_data(pub_data)
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 256, in _check_pub_data
    'Failed to authenticate! This is most likely because this '
salt.exceptions.EauthAuthenticationError: Failed to authenticate! This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).

```
I asked in salt irc chanel for some help and i was informed that this is provably a bug hence my bug report.

### Setup
**master file**
```
timeout: 45
root_dir: /etc/salt
state_verbose: True
file_roots:
  base:
    - /etc/salt/states
pillar_roots:
  base:
    - /etc/salt/pillars
pillar_opts: False
publisher_acl:
  pkg:
    - .*
  userA:
    - staltutil.refresh_pillar
    - test.ping
  testuser:
    - staltutil.refresh_pillar
    - mymodule.test:
        kwargs:
         - .*
        args:
         - .*
    - anothermodule
client_acl_blacklist:
  modules:
    - zypper
    - oracle
log_file: /var/log/salt/master
log_level_logfile: debug

```

### Versions Report
```
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 13.1.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.3
 
System Versions:
           dist: debian 8.4 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.4 

```

**Comment by Ch3LL** [comment]
Can you compare your config to this issue: https://github.com/saltstack/salt/issues/42626

Looks like you have not added targeting in your example. If you add that does it work?

**Comment by dkatsanikakis** [comment]
@Ch3LL Thanks for the prompt reply. I tried this already but still doesn`t work.

I noticed something weird. I added mymodule to userA. When i "su" on salt-master as userA and execute `salt -b 1 server33 mymodule.test` it works without any issues. No 'kwargs' nor 'args' are specified (see bellow updated config) .

```
timeout: 45
root_dir: /etc/salt
state_verbose: True
file_roots:
  base:
    - /etc/salt/states
pillar_roots:
  base:
    - /etc/salt/pillars
pillar_opts: False
publisher_acl:
  pkg:
    - .*
  userA:
    - staltutil.refresh_pillar
    - mymodule.test
    - test.ping
  testuser:
    - '*server*:
      - staltutil.refresh_pillar
      - mymodule.test:
          kwargs:
           - .*
          args:
           - .*
      - test.ping
client_acl_blacklist:
  modules:
    - zypper
    - oracle
log_file: /var/log/salt/master
log_level_logfile: debug
```



However, when 'su' as  testuser and execute the very same command, i get same error:

```
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
EauthAuthenticationError: Failed to authenticate! This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 464, in salt_main
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/salt.py", line 59, in run
    self._run_batch()
  File "/usr/lib/python2.7/dist-packages/salt/cli/salt.py", line 242, in _run_batch
    batch = salt.cli.batch.Batch(self.config, eauth=eauth, parser=self.options)
  File "/usr/lib/python2.7/dist-packages/salt/cli/batch.py", line 36, in __init__
    self.minions, self.ping_gen, self.down_minions = self.__gather_minions()
  File "/usr/lib/python2.7/dist-packages/salt/cli/batch.py", line 62, in __gather_minions
    for ret in ping_gen:
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 769, in cmd_iter
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 337, in run_job
    return self._check_pub_data(pub_data)
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 256, in _check_pub_data
    'Failed to authenticate! This is most likely because this '
EauthAuthenticationError: Failed to authenticate! This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 464, in salt_main
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/salt.py", line 59, in run
    self._run_batch()
  File "/usr/lib/python2.7/dist-packages/salt/cli/salt.py", line 242, in _run_batch
    batch = salt.cli.batch.Batch(self.config, eauth=eauth, parser=self.options)
  File "/usr/lib/python2.7/dist-packages/salt/cli/batch.py", line 36, in __init__
    self.minions, self.ping_gen, self.down_minions = self.__gather_minions()
  File "/usr/lib/python2.7/dist-packages/salt/cli/batch.py", line 62, in __gather_minions
    for ret in ping_gen:
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 769, in cmd_iter
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 337, in run_job
    return self._check_pub_data(pub_data)
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 256, in _check_pub_data
    'Failed to authenticate! This is most likely because this '
salt.exceptions.EauthAuthenticationError: Failed to authenticate! This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).
 
```

**Comment by dkatsanikakis** [comment]
@Ch3LL 

**NOTE. In my first config sample there was a paste issue with result the user 'testuser' been allowed to use 'test.ping' module. I have updated my master config file**

Considering my previous comment that 'userA' can execute the mentioned command without any issues but 'testuser' could not, i started looking for any typos which i couldnt find any. I then tried to copy the 'userA' block and paste it further down in master config file and replace 'userA' with 'testuser'. **It worked!**

I dont know why this did the trick but i am trying to find differences between the working master file and the non working one. No tabs vs space found, no strange characters, the only difference is that "testuser' can use 'test.ping' module.

What i will do is try to remove 'test.ping' module from 'testuser' and see if i get same error.

Does the test.ping module has anything to do with publisher_acl and salt batch processing?

**Comment by dkatsanikakis** [comment]
Confirmed. If test.ping is not allowed for a system user batching is not allowed. Is this normal?

**Comment by dkatsanikakis** [comment]
As far as i can see on the source code of  "batch.py" [here](https://github.com/saltstack/salt/blob/413de95df2a4cf81575bb654f3e51fc1c52b112a/salt/cli/batch.py) , test.ping is used in order to gather up a list of minions for the batch. Hence why "test.ping" module must be allowed in order a user to be able to use salt batch mode.

```
  def __gather_minions(self):
        '''
        Return a list of minions to use for the batch run
        '''
        args = [self.opts['tgt'],
                'test.ping',
                [],
                self.opts['timeout'],
] 
```
I wasn't able to find any documentation on this so maybe it would be helpful to place the relevant information somewhere within the "publisher_acl" section.
