### ISSUE TITLE
Error: "TypeError: upgrade() got an unexpected keyword argument 'pkgs'" while using pkg.uptodate

### ISSUE THREAD

**Issue by maneamarius** [saltstack/salt#45212]
### Description of Issue/Question
I'm writing a simple salt state which brings all the packages on my Gentoo Linux system up to date.
When calling the salt state, I'm getting this error:

```
salt-call state.sls system.update-world
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/salt/state.py", line 1843, in call
    **cdata['kwargs'])
  File "/usr/lib64/python2.7/site-packages/salt/loader.py", line 1795, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/salt/states/pkg.py", line 2867, in uptodate
    ret['changes'] = __salt__['pkg.upgrade'](refresh=refresh, pkgs=pkgs, **kwargs)
TypeError: upgrade() got an unexpected keyword argument 'pkgs'

local:
----------
          ID: package-update-world
    Function: pkg.uptodate
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib64/python2.7/site-packages/salt/state.py", line 1843, in call
                  **cdata['kwargs'])
                File "/usr/lib64/python2.7/site-packages/salt/loader.py", line 1795, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib64/python2.7/site-packages/salt/states/pkg.py", line 2867, in uptodate
                  ret['changes'] = __salt__['pkg.upgrade'](refresh=refresh, pkgs=pkgs, **kwargs)
              TypeError: upgrade() got an unexpected keyword argument 'pkgs'
     Started: 19:40:31.433786
    Duration: 110064.803 ms
     Changes:   

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time: 110.065 s
```

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

```
system/update-world.sls 
{% if grains['os'] == 'Gentoo' %}

package-update-world:
  pkg.uptodate:
    - refresh: True

{% endif %}
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

Create salt state system/update-world.sls with the content listed above.
Run it (on the same machine as the salt-master) using:
salt-call state.sls system.update-world

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
salt --versions-report
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: 1.9.1
       cherrypy: 3.8.0
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.24.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Dec 17 2017, 07:42:25)
   python-gnupg: 0.4.0
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.2.2
 
System Versions:
           dist: gentoo 2.4.1 
         locale: UTF-8
        machine: x86_64
        release: 4.14.8-gentoo-r1
         system: Linux
        version: Gentoo Base System 2.4.1
```

**Comment by maneamarius** [comment]
It may be worth mentioning that the following packages are available for upgrade on my system.
They are Rebuilds (R), not upgrades, due to some keyword USE change ("cracklib" USE flag  was added to the system profile)

```
emerge -DavuN world --with-bdeps=y

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild   R    ] sys-libs/pam-1.2.1-r2::gentoo  USE="berkdb cracklib* filecaps nls pie -audit -debug -nis (-selinux) {-test}" ABI_X86="(64) -32 (-x32)" 0 KiB
[ebuild   R    ] dev-db/mariadb-10.1.26-r1:0/18::gentoo  USE="backup cracklib* openssl pam perl server xml -bindist -debug -embedded -extraengine -galera -innodb-lz4 -innodb-lzo -innodb-snappy -jdbc -jemalloc -kerberos -latin1 -libressl (-mroonga) -odbc -oqgraph -profiling (-selinux) -sphinx -sst-rsync -sst-xtrabackup -static -static-libs -systemd -systemtap -tcmalloc {-test} -tokudb -yassl" ABI_X86="(64) -32 (-x32)" 0 KiB
[ebuild   R    ] sys-auth/pambase-20150213-r1::gentoo  USE="consolekit cracklib* nullok sha512 -debug (-elogind) -gnome-keyring -minimal -mktemp -pam_krb5 -pam_ssh -passwdqc -securetty (-selinux) -systemd" 0 KiB
[ebuild   R    ] sys-apps/shadow-4.5::gentoo  USE="acl cracklib* nls pam xattr -audit (-selinux) -skey" LINGUAS="-cs -da -de -es -fi -fr -hu -id -it -ja -ko -pl -pt_BR -ru -sv -tr -zh_CN -zh_TW" 0 KiB

Total: 4 packages (4 reinstalls), Size of downloads: 0 KiB

Would you like to merge these packages? [Yes/No] n

Quitting.

```

**Comment by maneamarius** [comment]
Retested again after refreshing the package database (eix-sync) there was one more package added to the list, which wasn't rebuild, but a regular upgrade. And I still got the same crash.

**Comment by gtmanfred** [comment]
Looks like the `pkg.upgrade` on gentoo does not accept the pkgs keyword.  If you wanted to add accepting that keyword, it would work.  And we would love to see a PR for that.

https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.ebuild.html#salt.modules.ebuild.upgrade

I am marking this as a bug.

Thanks,
Daniel

**Comment by maneamarius** [comment]
I'd love to contribute but I'm not sure my python skills are good enough :)
I may give it some try at later time but right now is not a great time for me as I recently moved to a new house..
