### ISSUE TITLE
py3 - oxygen - windows -pkg.lastest gives error

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#45241]
On linux master / windows minion setup when running `pkg.latest` in a state file it gives error/traceback in oxygen branch on py3 setup.

```
    The minion function caused an exception: AttributeError: cffi library '_constant_time' has no function, constant or global variable named '__loader__'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1627, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "c:\salt\bin\lib\site-packages\salt\executors\direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "c:\salt\bin\lib\site-packages\salt\modules\state.py", line 1276, in sls
        ret = st_.state.call_high(high_, orchestration_jid)
      File "c:\salt\bin\lib\site-packages\salt\state.py", line 2727, in call_high
        ret = self.call_chunks(chunks)
      File "c:\salt\bin\lib\site-packages\salt\state.py", line 2117, in call_chunks
        running = self.call_chunk(low, running, chunks)
      File "c:\salt\bin\lib\site-packages\salt\state.py", line 2553, in call_chunk
        running[tag] = self.call(low, chunks, running)
      File "c:\salt\bin\lib\site-packages\salt\state.py", line 1984, in call
        self.check_refresh(low, ret)
      File "c:\salt\bin\lib\site-packages\salt\state.py", line 992, in check_refresh
        self.module_refresh()
      File "c:\salt\bin\lib\site-packages\salt\state.py", line 943, in module_refresh
        reload_module(site)
      File "c:\salt\bin\lib\importlib\__init__.py", line 166, in reload
        _bootstrap._exec(spec, module)
      File "<frozen importlib._bootstrap>", line 626, in _exec
      File "<frozen importlib._bootstrap_external>", line 673, in exec_module
      File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
      File "c:\salt\bin\lib\site.py", line 563, in <module>
        main()
      File "c:\salt\bin\lib\site.py", line 544, in main
        abs_paths()
      File "c:\salt\bin\lib\site.py", line 101, in abs_paths
        if (getattr(getattr(m, '__loader__', None), '__module__', None) not in
    SystemError: <built-in function getattr> returned a result with an error set
```
### Setup
create state file and run it.
```
winpkgs:
  pkg.latest:
    - pkgs:
      - chrome
      - firefox
      - adobereader
```

### Steps to Reproduce Issue
Run state file.

### Versions Report
```
linux master

Salt Version:
           Salt: 2018.2.0-22-g3ed7a29
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.2 (default, Nov 23 2017, 16:37:01)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.1.6
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: ISO-8859-1
        machine: x86_64
        release: 4.4.0-87-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

```
windows minion

    Salt Version:
               Salt: 2018.2.0-46-gb9503a4
     
    Dependency Versions:
               cffi: 1.11.2
           cherrypy: Not Installed
           dateutil: 2.6.1
          docker-py: Not Installed
              gitdb: 2.0.3
          gitpython: 2.1.7
              ioflo: Not Installed
             Jinja2: 2.10
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: 1.0.7
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.18
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
       python-gnupg: 0.4.1
             PyYAML: 3.12
              PyZMQ: 16.0.3
               RAET: Not Installed
              smmap: 2.0.3
            timelib: 0.2.4
            Tornado: 4.5.2
                ZMQ: 4.1.6
     
    System Versions:
               dist:   
             locale: cp1252
            machine: AMD64
            release: 2016Server
             system: Windows
            version: 2016Server 10.0.14393 SP0 Multiprocessor Free
```

**Comment by frogunder** [comment]
#45242

**Comment by frogunder** [comment]
#45245 fixes this issue, just tested it.

**Comment by rallytime** [comment]
Awesome! Thank you @frogunder and @twangboy
