### ISSUE TITLE
Salt-Syndic not working on Oxygen branch on py3

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#45243]
Setting up a salt-syndic environment on oxygen branch on py3 setup is not working.

See this in `/var/log/salt/syndic`
```
2018-01-02 14:31:44,897 [tornado.application:638 ][ERROR   ][3400] Exception in callback <bound method SyndicManager._forward_events of <salt.minion.SyndicManager object at 0x7f5064a9cb00>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tornado/ioloop.py", line 1026, in _run
    return self.callback()
  File "/root/salt/salt/minion.py", line 3184, in _forward_events
    res = self._return_pub_syndic(values, master_id=master)
  File "/root/salt/salt/minion.py", line 3051, in _return_pub_syndic
    sync=False)
  File "/root/salt/salt/minion.py", line 1957, in _return_pub_multi
    jid = ret.get('jid', ret.get('__jid__'))
AttributeError: 'dict_values' object has no attribute 'get'
```

see this in `/var/log/salt/master`
```
2018-01-02 14:30:56,948 [asyncio                                  :1148][ERROR   ][2753] Exception in callback _SelectorDatagramTransport._read_ready()
handle: <Handle _SelectorDatagramTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 1016, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/root/salt/salt/utils/ssdp.py", line 189, in datagram_received
    self._sendto('{0}:@:{1}'.format(self.signature, json.dumps(self.answer)), addr)
  File "/root/salt/salt/utils/ssdp.py", line 155, in _sendto
    self.transport.sendto(data, addr=addr)
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 1021, in sendto
    'not %r' % type(data).__name__)
TypeError: data argument must be a bytes-like object, not 'str'
```

### Setup
Set up environment for salt syndic: https://docs.saltstack.com/en/latest/topics/topology/syndic.html#configuring-the-syndic

### Steps to Reproduce Issue
Set up environment, accept key and try to run commands from the Master node.
Will get `Minion did not return. [No response]`, then check the syndic/master logs for the errors.

### Versions Report
```
Salt Version:
           Salt: 2018.2.0-22-g3ed7a29
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.2 (default, Nov 17 2016, 17:05:23)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.1.6
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-72-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by frogunder** [comment]
I also see this traceback when trying to run a `Multi-Master PKI` setup, this also on oxygen branch and  py3 environment.
https://docs.saltstack.com/en/latest/topics/tutorials/multimaster_pki.html#prepping-the-master-to-sign-its-public-key

```
2018-01-02 15:06:17,041 [asyncio                                  :1148][ERROR   ][2718] Exception in callback _SelectorDatagramTransport._read_ready()
handle: <Handle _SelectorDatagramTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 1016, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/root/salt/salt/utils/ssdp.py", line 189, in datagram_received
    self._sendto('{0}:@:{1}'.format(self.signature, json.dumps(self.answer)), addr)
  File "/root/salt/salt/utils/ssdp.py", line 155, in _sendto
    self.transport.sendto(data, addr=addr)
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 1021, in sendto
    'not %r' % type(data).__name__)
TypeError: data argument must be a bytes-like object, not 'str'
```

**Comment by gtmanfred** [comment]
confirmed.

**Comment by rallytime** [comment]
@terminalmage I think this is related to your current work in unicode-land and I wanted to ping you here so it's on your radar.

**Comment by terminalmage** [comment]
This actually has nothing to do with unicode, it was broken by using `somedict.values()` where we should be using `list(six.itervalues(somedict))`. I tracked this back to https://github.com/saltstack/salt/pull/43053.

This is fixed in https://github.com/saltstack/salt/pull/45326.

CC: @DmitryKuzmenko

**Comment by rallytime** [comment]
@frogunder Can you swing back around here and make sure this is fixed now?

**Comment by frogunder** [comment]
This is fixed, just tested it.

**Comment by rallytime** [comment]
Awesome. Thanks @frogunder!
