### ISSUE TITLE
Ctl+C causes stack trace on Windows

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#45301]
### Description of Issue/Question
When running salt-minion from the command line in Windows using `salt-minion -l debug`, hitting `ctl+c` to end the process causes the following stack trace:
```
Traceback (most recent call last):
  File "c:\dev\salt\salt\log\handlers\__init__.py", line 211, in emit
    self.enqueue(self.prepare(record))
  File "c:\dev\salt\salt\log\handlers\__init__.py", line 177, in enqueue
  File "c:\python27\lib\multiprocessing\queues.py", line 264, in _feed
    self.queue.put_nowait(record)
  File "c:\python27\lib\multiprocessing\queues.py", line 155, in put_nowait
    return self.put(obj, False)
  File "c:\python27\lib\multiprocessing\queues.py", line 100, in put
    assert not self._closed
AssertionError
Logged from file setup.py, line 973
    send(obj)
IOError: [Errno 232] The pipe is being closed
```

### Setup
Pull down the head of the Oxygen branch
Install a dev environment by running the `build_env_2.ps1` script in `pkg\windows` (`powershell -file build_env_2.ps1`)
Install salt by running the following command from the root salt directory: `pip install -e .`
Start a salt-minion in debug mode: `salt-minion -l debug`

### Steps to Reproduce Issue
Once the minion is started, hit `ctl+c`
Observe the stack trace

### Versions Report
Head of Oxygen

**Comment by twangboy** [comment]
@skizunov Do you have any ideas on this?
