### ISSUE TITLE
salt.exceptions.SaltReqTimeoutError: Message timed out from SLES 11 SP4

### ISSUE THREAD

**Issue by JoaquinVeira** [saltstack/salt#45386]
### Description of Issue/Question

We have 2 SLES 11 SP4 minions (from more than 200 working fine) that are getting SaltReqTimeoutError while executing any state execution module.
For example:

```
[11:36:root@minion:~]$ salt-call state.show_highstate
[WARNING ] Unable to find IPv6 record for "minion.domain.test" causing a 10 second timeout when rendering grains. Set the dns or /etc/hosts for IPv6 to clear this.
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
SaltReqTimeoutError: Message timed out
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib64/python2.6/site-packages/salt/scripts.py", line 379, in salt_call
    client.run()
  File "/usr/lib64/python2.6/site-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib64/python2.6/site-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib64/python2.6/site-packages/salt/cli/caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib64/python2.6/site-packages/salt/modules/state.py", line 1180, in show_highstate
    st_ = salt.state.HighState(__opts__, pillar, pillar_enc=pillar_enc)
  File "/usr/lib64/python2.6/site-packages/salt/state.py", line 3520, in __init__
    BaseHighState.__init__(self, opts)
  File "/usr/lib64/python2.6/site-packages/salt/state.py", line 2442, in __init__
    self.avail = self.__gather_avail()
  File "/usr/lib64/python2.6/site-packages/salt/state.py", line 2452, in __gather_avail
    avail[saltenv] = self.client.list_states(saltenv)
  File "/usr/lib64/python2.6/site-packages/salt/fileclient.py", line 382, in list_states
    for path in self.file_list(saltenv):
  File "/usr/lib64/python2.6/site-packages/salt/fileclient.py", line 1168, in file_list
    return [sdecode(fn_) for fn_ in self.channel.send(load)]
  File "/usr/lib64/python2.6/site-packages/salt/utils/async.py", line 75, in wrap
    ret = self._block_future(ret)
  File "/usr/lib64/python2.6/site-packages/salt/utils/async.py", line 85, in _block_future
    return future.result()
  File "/usr/lib64/python2.6/site-packages/tornado/concurrent.py", line 236, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib64/python2.6/site-packages/salt/transport/zeromq.py", line 280, in send
    ret = yield self._crypted_transfer(load, tries=tries, timeout=timeout, raw=raw)
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/lib64/python2.6/site-packages/tornado/concurrent.py", line 236, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib64/python2.6/site-packages/salt/transport/zeromq.py", line 248, in _crypted_transfer
    ret = yield _do_transfer()
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/lib64/python2.6/site-packages/tornado/concurrent.py", line 236, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib64/python2.6/site-packages/salt/transport/zeromq.py", line 232, in _do_transfer
    tries=tries,
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/lib64/python2.6/site-packages/tornado/concurrent.py", line 236, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
SaltReqTimeoutError: Message timed out
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib64/python2.6/site-packages/salt/scripts.py", line 379, in salt_call
    client.run()
  File "/usr/lib64/python2.6/site-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib64/python2.6/site-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib64/python2.6/site-packages/salt/cli/caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib64/python2.6/site-packages/salt/modules/state.py", line 1180, in show_highstate
    st_ = salt.state.HighState(__opts__, pillar, pillar_enc=pillar_enc)
  File "/usr/lib64/python2.6/site-packages/salt/state.py", line 3520, in __init__
    BaseHighState.__init__(self, opts)
  File "/usr/lib64/python2.6/site-packages/salt/state.py", line 2442, in __init__
    self.avail = self.__gather_avail()
  File "/usr/lib64/python2.6/site-packages/salt/state.py", line 2452, in __gather_avail
    avail[saltenv] = self.client.list_states(saltenv)
  File "/usr/lib64/python2.6/site-packages/salt/fileclient.py", line 382, in list_states
    for path in self.file_list(saltenv):
  File "/usr/lib64/python2.6/site-packages/salt/fileclient.py", line 1168, in file_list
    return [sdecode(fn_) for fn_ in self.channel.send(load)]
  File "/usr/lib64/python2.6/site-packages/salt/utils/async.py", line 75, in wrap
    ret = self._block_future(ret)
  File "/usr/lib64/python2.6/site-packages/salt/utils/async.py", line 85, in _block_future
    return future.result()
  File "/usr/lib64/python2.6/site-packages/tornado/concurrent.py", line 236, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib64/python2.6/site-packages/salt/transport/zeromq.py", line 280, in send
    ret = yield self._crypted_transfer(load, tries=tries, timeout=timeout, raw=raw)
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/lib64/python2.6/site-packages/tornado/concurrent.py", line 236, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib64/python2.6/site-packages/salt/transport/zeromq.py", line 248, in _crypted_transfer
    ret = yield _do_transfer()
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/lib64/python2.6/site-packages/tornado/concurrent.py", line 236, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib64/python2.6/site-packages/salt/transport/zeromq.py", line 232, in _do_transfer
    tries=tries,
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/lib64/python2.6/site-packages/tornado/concurrent.py", line 236, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
salt.exceptions.SaltReqTimeoutError: Message timed out
```

The thing is that I removed the keys and added them again without any problem:

```
[10:48:root@minion:~]$ salt-call -l debug state.sls updates test=true
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: minion.domain.test
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[WARNING ] Unable to find IPv6 record for "minion.domain.test" causing a 10 second timeout when rendering grains. Set the dns or /etc/hosts for IPv6 to clear this.
[DEBUG   ] /etc/resolv.conf: The domain and search keywords are mutually exclusive.
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[DEBUG   ] Connecting to master. Attempt 1 of 1
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'minion.domain.test', 'tcp://172.16.19.36:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (7468)
[DEBUG   ] Setting zmq_reconnect_ivl to '7468ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'minion.domain.test', 'tcp://172.16.19.36:4506', 'clear')
[ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
Minion failed to authenticate with the master, has the minion key been accepted?
[10:53:root@minion:~]$ salt-call -l debug state.sls updates test=true
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: minion.domain.test
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[WARNING ] Unable to find IPv6 record for "minion.domain.test" causing a 10 second timeout when rendering grains. Set the dns or /etc/hosts for IPv6 to clear this.
[DEBUG   ] /etc/resolv.conf: The domain and search keywords are mutually exclusive.
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[DEBUG   ] Connecting to master. Attempt 1 of 1
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'minion.domain.test', 'tcp://172.16.19.36:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (5670)
[DEBUG   ] Setting zmq_reconnect_ivl to '5670ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'minion.domain.test', 'tcp://172.16.19.36:4506', 'clear')
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_00f2a6a45a_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_00f2a6a45a_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_00f2a6a45a_pull.ipc
[DEBUG   ] Sending event: tag = salt/auth/creds; data = {'_stamp': '2018-01-11T09:53:57.960821', 'creds': {'publish_port': 4505, 'aes': 'wCYFCLLsxjnsXRtGq6K2ufkWB18VYmPQm+XBLze+KWWyPX4cijG3rkxgIa9GslGkV+VlXucczCE=', 'master_uri': 'tcp://172.16.19.36:4506'}, 'key': ('/etc/salt/pki/minion', 'minion.domain.test', 'tcp://172.16.19.36:4506')}
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Determining pillar cache
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'minion.domain.test', 'tcp://172.16.19.36:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'minion.domain.test', 'tcp://172.16.19.36:4506')
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded state.sls
[DEBUG   ] LazyLoaded saltutil.is_running
[DEBUG   ] LazyLoaded grains.get
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'minion.domain.test', 'tcp://172.16.19.36:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'minion.domain.test', 'tcp://172.16.19.36:4506')
[DEBUG   ] SaltReqTimeoutError, retrying. (1/3)
[DEBUG   ] SaltReqTimeoutError, retrying. (2/3)
[DEBUG   ] SaltReqTimeoutError, retrying. (3/3)
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
SaltReqTimeoutError: Message timed out
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib64/python2.6/site-packages/salt/scripts.py", line 379, in salt_call
    client.run()
  File "/usr/lib64/python2.6/site-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib64/python2.6/site-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib64/python2.6/site-packages/salt/cli/caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib64/python2.6/site-packages/salt/modules/state.py", line 1010, in sls
    mocked=kwargs.get('mock', False))
  File "/usr/lib64/python2.6/site-packages/salt/state.py", line 3520, in __init__
    BaseHighState.__init__(self, opts)
  File "/usr/lib64/python2.6/site-packages/salt/state.py", line 2442, in __init__
    self.avail = self.__gather_avail()
  File "/usr/lib64/python2.6/site-packages/salt/state.py", line 2452, in __gather_avail
    avail[saltenv] = self.client.list_states(saltenv)
  File "/usr/lib64/python2.6/site-packages/salt/fileclient.py", line 382, in list_states
    for path in self.file_list(saltenv):
  File "/usr/lib64/python2.6/site-packages/salt/fileclient.py", line 1168, in file_list
    return [sdecode(fn_) for fn_ in self.channel.send(load)]
  File "/usr/lib64/python2.6/site-packages/salt/utils/async.py", line 75, in wrap
    ret = self._block_future(ret)
  File "/usr/lib64/python2.6/site-packages/salt/utils/async.py", line 85, in _block_future
    return future.result()
  File "/usr/lib64/python2.6/site-packages/tornado/concurrent.py", line 236, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib64/python2.6/site-packages/salt/transport/zeromq.py", line 280, in send
    ret = yield self._crypted_transfer(load, tries=tries, timeout=timeout, raw=raw)
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/lib64/python2.6/site-packages/tornado/concurrent.py", line 236, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib64/python2.6/site-packages/salt/transport/zeromq.py", line 248, in _crypted_transfer
    ret = yield _do_transfer()
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/lib64/python2.6/site-packages/tornado/concurrent.py", line 236, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib64/python2.6/site-packages/salt/transport/zeromq.py", line 232, in _do_transfer
    tries=tries,
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/lib64/python2.6/site-packages/tornado/concurrent.py", line 236, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
SaltReqTimeoutError: Message timed out
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib64/python2.6/site-packages/salt/scripts.py", line 379, in salt_call
    client.run()
  File "/usr/lib64/python2.6/site-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib64/python2.6/site-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib64/python2.6/site-packages/salt/cli/caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib64/python2.6/site-packages/salt/modules/state.py", line 1010, in sls
    mocked=kwargs.get('mock', False))
  File "/usr/lib64/python2.6/site-packages/salt/state.py", line 3520, in __init__
    BaseHighState.__init__(self, opts)
  File "/usr/lib64/python2.6/site-packages/salt/state.py", line 2442, in __init__
    self.avail = self.__gather_avail()
  File "/usr/lib64/python2.6/site-packages/salt/state.py", line 2452, in __gather_avail
    avail[saltenv] = self.client.list_states(saltenv)
  File "/usr/lib64/python2.6/site-packages/salt/fileclient.py", line 382, in list_states
    for path in self.file_list(saltenv):
  File "/usr/lib64/python2.6/site-packages/salt/fileclient.py", line 1168, in file_list
    return [sdecode(fn_) for fn_ in self.channel.send(load)]
  File "/usr/lib64/python2.6/site-packages/salt/utils/async.py", line 75, in wrap
    ret = self._block_future(ret)
  File "/usr/lib64/python2.6/site-packages/salt/utils/async.py", line 85, in _block_future
    return future.result()
  File "/usr/lib64/python2.6/site-packages/tornado/concurrent.py", line 236, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib64/python2.6/site-packages/salt/transport/zeromq.py", line 280, in send
    ret = yield self._crypted_transfer(load, tries=tries, timeout=timeout, raw=raw)
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/lib64/python2.6/site-packages/tornado/concurrent.py", line 236, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib64/python2.6/site-packages/salt/transport/zeromq.py", line 248, in _crypted_transfer
    ret = yield _do_transfer()
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/lib64/python2.6/site-packages/tornado/concurrent.py", line 236, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib64/python2.6/site-packages/salt/transport/zeromq.py", line 232, in _do_transfer
    tries=tries,
  File "/usr/lib64/python2.6/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/lib64/python2.6/site-packages/tornado/concurrent.py", line 236, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
salt.exceptions.SaltReqTimeoutError: Message timed out
```

I'm not attaching state files as I think it doesn't matter which one I use I always get the same error.
Many other execution modules work fine (test.ping, service.get_all, grains.items, etc). It looks like the problem is when trying to contact the master, which I tried to contact with telnet and worked fine:

```
[10:40:root@minion:~]$ telnet 172.16.19.36 4506
Trying 172.16.19.36...
Connected to 172.16.19.36.
Escape character is '^]'.
```

As I said many other minions work fine (RHEL, Windows and even more SLES 11 SP4) and I don't know where else to look. I couldn't find anything on logs either.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

There is debug info above with configuration parameters

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

There is debug info above
 
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Master:

```
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jul 12 2017, 17:32:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: redhat 6.9 Santiago
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-696.13.2.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.9 Santiago
```

Minions:

```
Salt Version:
           Salt: 2016.11.4

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.6.9 (unknown, Aug  5 2016, 11:15:31)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.2.1

System Versions:
           dist: SuSE 11 x86_64
        machine: x86_64
        release: 3.0.101-108.21-default
         system: Linux
        version: SUSE Linux Enterprise Server  11 x86_64
```

**Comment by gtmanfred** [comment]
can you try uninstalling the salt-minion packages and removing all the .pyc files in /usr/lib/python2.7/site-packages/salt, and see if installing again fixes the problem?


Thanks,
Daniel

**Comment by JoaquinVeira** [comment]
Hi, at minions I have installed python 2.6. I guess this is due to be on SLES 11 SP4.
After I remove salt & salt-minion packages there is nothing under /usr/lib64/python2.6/site-packages/salt

Thanks.

**Comment by Moulde** [comment]
Did you find a solution to this Joaquin?

**Comment by JoaquinVeira** [comment]
Hi,

I don't remember right now but I think I changed from OpenSuse repos for
Salt dependencies to Salt owned repos.

Regards.
