### ISSUE TITLE
cffi errors during highstate runs on Python 3.6

### ISSUE THREAD

**Issue by jhujhiti** [saltstack/salt#45428]
### Description of Issue/Question
I'm running Salt on FreeBSD with Python 3.6 (built from ports, default options on the ports aside from LOCALBASE=/usr/pkg). Using the latest cffi, 1.11.2, every single highstate run fails with the below error (or the same one for library "_openssl"). The previous cffi library in ports was 1.7.0, and it does not exhibit this behavior.
```
% sudo salt --state-output changed minion state.highstate test=True
minion:
    The minion function caused an exception: AttributeError: cffi library '_constant_time' has no function, constant or global variable named '__loader__'
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/usr/pkg/lib/python3.6/site-packages/salt/minion.py", line 1470, in _thread_return
        return_data = executor.execute()
      File "/usr/pkg/lib/python3.6/site-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/usr/pkg/lib/python3.6/site-packages/salt/modules/state.py", line 892, in highstate
        orchestration_jid=orchestration_jid)
      File "/usr/pkg/lib/python3.6/site-packages/salt/state.py", line 3661, in call_highstate
        self.load_dynamic(matches)
      File "/usr/pkg/lib/python3.6/site-packages/salt/state.py", line 3181, in load_dynamic
        self.state.module_refresh()
      File "/usr/pkg/lib/python3.6/site-packages/salt/state.py", line 918, in module_refresh
        reload_module(site)
      File "/usr/pkg/lib/python3.6/importlib/__init__.py", line 166, in reload
        _bootstrap._exec(spec, module)
      File "<frozen importlib._bootstrap>", line 618, in _exec
      File "<frozen importlib._bootstrap_external>", line 678, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/usr/pkg/lib/python3.6/site.py", line 544, in <module>
        main()
      File "/usr/pkg/lib/python3.6/site.py", line 525, in main
        abs_paths()
      File "/usr/pkg/lib/python3.6/site.py", line 102, in abs_paths
        if (getattr(getattr(m, '__loader__', None), '__module__', None) not in
    SystemError: <built-in function getattr> returned a result with an error set
```

### Setup
Any highstate run should fail on this setup. I can provide full FreeBSD port options or binary packages if necessary, but simply building the latest with default options should reproduce it.

### Steps to Reproduce Issue
Install the versions below and execute a highstate.

### Versions Report
Minion and master run on the same machine
```
Salt Version:                                                                                                                       
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.11.2
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.26.0
        libnacl: Not Installed
       M2Crypto: 0.27.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.0
         Python: 3.6.4 (default, Jan 13 2018, 02:20:49)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.2.2

System Versions:
           dist:
         locale: UTF-8
        machine: amd64
        release: 11.1-RELEASE-p6
         system: FreeBSD
        version: Not Installed
```

**Comment by gtmanfred** [comment]
@cedwards when you have a second, could you swing by here?

Thanks,
Daniel

**Comment by jhujhiti** [comment]
I looked into this a little more. It seems that the references to openssl and constant_time both come from the cryptography library. So this could be a bug there. But clearly it's triggered by the attempt to reload modules in Salt.

**Comment by cedwards** [comment]
I plan to look at this over the weekend.

**Comment by jhujhiti** [comment]
Good news, I think: py-cffi in FreeBSD ports was updated to 1.11.5 and I can no longer reproduce this issue after upgrading and restarting. The changelog for 1.11.3 contains the item "Fix on CPython 3.x: reading the attributes __loader__ or __spec__ from the cffi-generated lib modules gave a buggy SystemError.", which sounds related.
