### ISSUE TITLE
UnicodeDecodeError in highstate output

### ISSUE THREAD

**Issue by dverbeek84** [saltstack/salt#45525]
### Description of Issue/Question
I have a issue with unicode and the highstate i don't know where is is comming from

I get the following error:

```
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 26767: ordinal not in range(128)
Traceback (most recent call last):
File "/usr/bin/salt-call", line 11, in <module>
salt_call()
File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 391, in salt_call
client.run()
File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 58, in run
caller.run()
File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 149, in run
self.opts)
File "/usr/lib/python2.7/site-packages/salt/output/__init__.py", line 92, in display_output
display_data = try_printout(data, out, opts, **kwargs)
File "/usr/lib/python2.7/site-packages/salt/output/__init__.py", line 39, in try_printout
printout = get_printout(out, opts)(data, **kwargs)
File "/usr/lib/python2.7/site-packages/salt/output/highstate.py", line 145, in output
for host, hostdata in six.iteritems(data)
File "/usr/lib/python2.7/site-packages/salt/output/highstate.py", line 349, in _format_host
comment = '{0}\n\t\t{1}: {2}'.format(comment, key, value)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 26767: ordinal not in range(128)
Traceback (most recent call last):
File "/usr/bin/salt-call", line 11, in <module>
salt_call()
File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 391, in salt_call
client.run()
File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 58, in run
caller.run()
File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 149, in run
self.opts)
File "/usr/lib/python2.7/site-packages/salt/output/__init__.py", line 92, in display_output
display_data = try_printout(data, out, opts, **kwargs)
File "/usr/lib/python2.7/site-packages/salt/output/__init__.py", line 39, in try_printout
printout = get_printout(out, opts)(data, **kwargs)
File "/usr/lib/python2.7/site-packages/salt/output/highstate.py", line 145, in output
for host, hostdata in six.iteritems(data)
File "/usr/lib/python2.7/site-packages/salt/output/highstate.py", line 349, in _format_host
comment = '{0}\n\t\t{1}: {2}'.format(comment, key, value)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 26767: ordinal not in range(128)
```

### Versions Report
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.5.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

**Comment by garethgreenaway** [comment]
@terminalmage FYI.

**Comment by terminalmage** [comment]
I can reproduce in 2017.7 but not in the oxygen release branch, this is fixed as part of our unicode efforts for the upcoming release.

**Comment by terminalmage** [comment]
NOTE: this was happening because the state being run returned extra data in a `data` key in the state return dictionary, which the highstate outputter was trying to print to the screen, and the UnicodeEncodeError happened because of a mismatch of a unicode string with a format string that was a str type.

**Comment by terminalmage** [comment]
The fix can be confirmed using a Docker image I created. First, check out the `v2017.7.2` tag and run this command from the root of the git repository:

```
git checkout v2017.7.2
docker run --rm -it -v $PWD:/testing terminalmage/issues:45525 salt-call state.single foo.bar baz
```

Next, check out the release branch and repeat the command, and the traceback will be gone.

```
git checkout -b oxygen.rc1 origin/oxygen.rc1
docker run --rm -it -v $PWD:/testing terminalmage/issues:45525 salt-call state.single foo.bar baz
```
