### ISSUE TITLE
Problem when using slsutil.renderer in pillar

### ISSUE THREAD

**Issue by amontalban** [saltstack/salt#45558]
### Setup
I'm trying to load multiple pillar files from a folder (In this case users), to do this I used Python and slsutil.renderer.

Here is my `pillar/common/users/developers/init.sls`:

```py
#!py
import os

def run():
  '''
  Load users data from all .sls files in the directory
  '''

  sls_files = [os.path.splitext(os.path.basename(f))[0] for f in os.listdir(".") if os.path.isfile(os.path.join(".", f)) and f.endswith(".sls") and f != "init.sls"]

  data = {}
  data['users'] = {}

  for user in sls_files:
    sls_file = user + '.sls'
    user_data = __salt__.slsutil.renderer(sls_file)

    data['users'].update(user_data)

  return data
```

Then in the `pillar/common/users/developers` I have multiple .sls files in the format of `amontalban.sls` with the following content:

```yaml
{% from "common/map.jinja" import pw with context %}

  amontalban:
    fullname: "Andres Montalban"
    home: /home/amontalban
    createhome: True
    manage_vimrc: False
    manage_bashrc: False
    manage_profile: True
    sudouser: True
    sudo_rules:
      - ALL=(ALL) NOPASSWD:ALL
    sudo_defaults:
      - '!requiretty'
    shell: {{ pw.bash_shell }}
    prime_group:
      name: amontalban
    groups:
      - users
      - {{ pw.root_group }}
    ssh_key_type: rsa
    ssh_auth_file:
      - PUBLIC KEY
    ssh_config:
      all:
        hostname: "*"
        options:
          - "ForwardAgent yes"
```

And this generates the following output:

```
[DEBUG   ] In saltenv 'base', looking at rel_path 'common/map.jinja' to resolve 'salt://common/map.jinja'
[DEBUG   ] In saltenv 'base', ** considering ** path '/var/cache/salt/minion/files/base/common/map.jinja' to resolve 'salt://common/map.jinja'
[ERROR   ] Rendering exception occurred: Jinja variable the template 'common/map.jinja' (imported on line 1) does not export the requested name 'pw'
[CRITICAL] Rendering SLS 'common/users/developers' failed, render error:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/salt/utils/templates.py", line 525, in py
    data = mod.run()
  File "/srv/pillar/common/users/developers/init.sls", line 16, in run
    user_data = __salt__.slsutil.renderer(sls_file)
  File "/usr/local/lib/python2.7/site-packages/salt/modules/slsutil.py", line 124, in renderer
    **kwargs)
  File "/usr/local/lib/python2.7/site-packages/salt/template.py", line 101, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/usr/local/lib/python2.7/site-packages/salt/renderers/jinja.py", line 70, in render
    **kws)
  File "/usr/local/lib/python2.7/site-packages/salt/utils/templates.py", line 178, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/local/lib/python2.7/site-packages/salt/utils/templates.py", line 386, in render_jinja_tmpl
    buf=tmplstr)
SaltRenderError: Jinja variable the template 'common/map.jinja' (imported on line 1) does not export the requested name 'pw'
```

So it's searching the `common/map.jinja` file in Salt states folder instead of pillar and since they are different it's failing.

### Versions Report
```
Salt Version:
           Salt: 2016.11.6
 
Dependency Versions:
           cffi: 1.7.0
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Dec 10 2017, 01:15:47)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.2.2
 
System Versions:
           dist:   
        machine: amd64
        release: 10.3-RELEASE-p18
         system: FreeBSD
        version: Not Installed
```

**Comment by gtmanfred** [comment]
to load files through slsutil.renderer, you should reference the full path to the file or `salt://` to pull them from the fileserver.

The python module is not able to use relative paths, because it will be running in the directory that the salt daemon was started in, which is / or /root iirc.

**Comment by amontalban** [comment]
Thank you @gtmanfred , for now what I did was to concentrate `common/map.jinja` in Salt states and symlink it for pillars accessing it.
