### ISSUE TITLE
salt documentation fails to build with Python 3 version of sphinx

### ISSUE THREAD

**Issue by bdrung** [saltstack/salt#45684]
Generating the salt documentation with Python 3 version of sphinx fails (using Ubuntu 17.10 and salt 2017.7.2):
```
$ make -C doc html SPHINXBUILD=/usr/share/sphinx/scripts/python3/sphinx-build
/usr/share/sphinx/scripts/python3/sphinx-build -b html -d _build/doctrees    . _build/html
Running Sphinx v1.5.6
making output directory...
loading translations [en]... done
loading pickled environment... not yet created
[autosummary] generating autosummary for: contents.rst, faq.rst, glossary.rst, ref/auth/all/index.rst, ref/auth/all/salt.auth.auto.rst, ref/auth/all/salt.auth.django.rst, ref/auth/all/salt.auth.keystone.rst, ref/auth/all/salt.auth.ldap.rst, ref/auth/all/salt.auth.mysql.rst, ref/auth/all/salt.auth.pam.rst, ..., topics/using_salt.rst, topics/utils/index.rst, topics/venafi/index.rst, topics/virt/disk.rst, topics/virt/index.rst, topics/virt/nic.rst, topics/windows/index.rst, topics/windows/windows-package-manager.rst, topics/windows/windows-specific-behavior.rst, topics/yaml/index.rst

Exception occurred:
  File "/home/bdrung/projects/salt/debian/salt/utils/yamlloader.py", line 33, in <module>
    class SaltYamlSafeLoader(yaml.SafeLoader, object):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
The full traceback has been saved in /tmp/sphinx-err-hzfmdxlm.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```
/tmp/sphinx-err-hzfmdxlm.log contains:
```
# Sphinx version: 1.5.6
# Python version: 3.6.3 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.9.6
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/cmdline.py", line 295, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/usr/lib/python3/dist-packages/sphinx/application.py", line 244, in __init__
    self._init_builder(self.buildername)
  File "/usr/lib/python3/dist-packages/sphinx/application.py", line 315, in _init_builder
    self.emit('builder-inited')
  File "/usr/lib/python3/dist-packages/sphinx/application.py", line 589, in emit
    results.append(callback(self, *args))
  File "/usr/lib/python3/dist-packages/sphinx/ext/autosummary/__init__.py", line 587, in process_generate_options
    base_path=app.srcdir)
  File "/usr/lib/python3/dist-packages/sphinx/ext/autosummary/generate.py", line 127, in generate_autosummary_docs
    items = find_autosummary_in_files(sources)
  File "/usr/lib/python3/dist-packages/sphinx/ext/autosummary/generate.py", line 240, in find_autosummary_in_files
    filename=filename))
  File "/usr/lib/python3/dist-packages/sphinx/ext/autosummary/generate.py", line 338, in find_autosummary_in_lines
    current_module, filename=filename))
  File "/usr/lib/python3/dist-packages/sphinx/ext/autosummary/generate.py", line 250, in find_autosummary_in_docstring
    real_name, obj, parent, modname = import_by_name(name)
  File "/usr/lib/python3/dist-packages/sphinx/ext/autosummary/__init__.py", line 474, in import_by_name
    obj, parent, modname = _import_by_name(prefixed_name)
  File "/usr/lib/python3/dist-packages/sphinx/ext/autosummary/__init__.py", line 503, in _import_by_name
    __import__(modname)
  File "salt/states/iptables.py", line 198, in <module>
    from salt.state import STATE_INTERNAL_KEYWORDS as _STATE_INTERNAL_KEYWORDS
  File "salt/state.py", line 51, in <module>
    import salt.utils.yamlloader as yamlloader
  File "salt/utils/yamlloader.py", line 33, in <module>
    class SaltYamlSafeLoader(yaml.SafeLoader, object):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

**Comment by gtmanfred** [comment]
Yup, we just still build the docs with python2, so it hasn't been a thing that we have really run across.

Any help making this work with py3 would be greatly appreciated.

Thanks!
Daniel

**Comment by bdrung** [comment]
Mocking `salt.utils.yamlloader` let sphinx with Python 3 succeed in the 2017.7 (which includes the PR #45662).
