### ISSUE TITLE
Multi-master PKI not working on Py3

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#45743]
### Description of Issue/Question
When setting up an Multi-master PKI environment on py3, minions will not connect to the master.
(it is working correctly in a py2 setup)
https://docs.saltstack.com/en/latest/topics/tutorials/multimaster_pki.html

See this when running minion in debug mode:
```
[INFO    ] Master frodetest1 could not be reached, trying next master (if any)
[ERROR   ] No master could be reached or all masters denied the minions connection attempt.
[ERROR   ] Error while bringing up minion for multi-master. Is master at ['frode_ubuntu16_1', 'frodetest1'] responding?
[INFO    ] Got list of available master addresses: ['frode_ubuntu16_1', 'frodetest1']
```

```
[INFO    ] Master frode_ubuntu16_1 could not be reached, trying next master (if any)
[ERROR   ] No master could be reached or all masters denied the minions connection attempt.
[ERROR   ] Error while bringing up minion for multi-master. Is master at ['frodetest1', 'frode_ubuntu16_1'] responding?
[INFO    ] Got list of available master addresses: ['frodetest1', 'frode_ubuntu16_1']
```

I see this in the master log:
```
2018-01-29 01:49:12,185 [tornado.application                      :344 ][ERROR   ][22233] Future <tornado.concurrent.Future object at 0x7f62e91d4e10> exception was never retrieved: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 307, in wrapper
    yielded = next(result)
  File "/root/salt/salt/transport/zeromq.py", line 620, in handle_message
    stream.send(self.serial.dumps(self._auth(payload['load'])))
  File "/root/salt/salt/transport/mixins/auth.py", line 455, in _auth
    ret['pub_key'])
  File "/root/salt/salt/crypt.py", line 179, in sign_message
    return signer.sign(SHA.new(message))
  File "/usr/local/lib/python3.5/dist-packages/Crypto/Hash/SHA.py", line 90, in new
    return SHA1Hash().new(data)
  File "/usr/local/lib/python3.5/dist-packages/Crypto/Hash/SHA.py", line 77, in new
    return SHA1Hash(data)
  File "/usr/local/lib/python3.5/dist-packages/Crypto/Hash/SHA.py", line 74, in __init__
    HashAlgo.__init__(self, hashFactory, data)
  File "/usr/local/lib/python3.5/dist-packages/Crypto/Hash/hashalgo.py", line 51, in __init__
    self.update(data)
  File "/usr/local/lib/python3.5/dist-packages/Crypto/Hash/hashalgo.py", line 69, in update
    return self._hash.update(data)
TypeError: Unicode-objects must be encoded before hashing
```

### Setup
Set up a Multi-master PKI environment on a py3 setup.

### Steps to Reproduce Issue
Try and connect minions to master. You will get this error:
```
[ERROR   ] No master could be reached or all masters denied the minions connection attempt.
[ERROR   ] Error while bringing up minion for multi-master. Is master at ['frodetest1', 'frode_ubuntu16_1'] responding?
```
You should see something like this:
```
[DEBUG   ] salt.crypt.verify_signature: Loading public key
[DEBUG   ] salt.crypt.verify_signature: Verifying signature
[DEBUG   ] Successfully verified signature of master public key with verification public key master_sign.pub
[INFO    ] Received signed and verified master pubkey from master 172.16.0.10
[DEBUG   ] Decrypting the current master AES key
```

### Versions Report
```]Salt Version:
           Salt: 2017.7.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.2 (default, Nov 23 2017, 16:37:01)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.4
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.6
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: ISO-8859-1
        machine: x86_64
        release: 4.4.0-87-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by terminalmage** [comment]
Fixed in https://github.com/saltstack/salt/pull/45755
