### ISSUE TITLE
Can't import pkg_resources in custom outputter

### ISSUE THREAD

**Issue by nickhentschel** [saltstack/salt#45828]
### Description of Issue/Question

I'm trying to make use of an external module that imports `pkg_resources` to format output from `salt` runs and consistently seeing an import error. `setuptools` is definitely installed within the virtualenv. Using my outputter with `salt-call` works fine.

### Steps to Reproduce Issue

```
> salt '*' test.version --out html_out -l debug
...
[DEBUG   ] Failed to import output html_out:
Traceback (most recent call last):
  File "/salt-master/salt-mastervenv/lib/python2.7/site-packages/salt/loader.py", line 1412, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/var/cache/salt/master/extmods/output/html_out.py", line 10, in <module>
    from ansi2html import Ansi2HTMLConverter
  File "/salt-master/salt-mastervenv/lib/python2.7/site-packages/ansi2html/__init__.py", line 1, in <module>
    from ansi2html.converter import Ansi2HTMLConverter
  File "/salt-master/salt-mastervenv/lib/python2.7/site-packages/ansi2html/converter.py", line 26, in <module>
    import pkg_resources
ImportError: No module named pkg_resources
```

Running `salt-call test.version --out html_out` from the same venv works as expected.

### Versions Report

```
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Apr  5 2017, 18:54:29)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.4
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.6

System Versions:
           dist: centos 7.1.1503 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-327.3.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.1.1503 Core
```

**Comment by gtmanfred** [comment]
How are you installing `python 2.7.9` on a centos 7.1 machine?

The default version on centos 7.1 is 2.7.5.

can you run `python -m ansi2html.converter` ?  you should also be able to run `python -c 'import pkg_resources'`?

If not, then this is an issue with the python environment and not with salt.

**Comment by nickhentschel** [comment]
Thanks for the quick reply.

We package and distribute 2.7.9 internally. 

```
(salt-mastervenv) > python -m ansi2html.converter
(salt-mastervenv) > echo $?
0
(salt-mastervenv) > python -c 'import pkg_resources'
(salt-mastervenv) > echo $?
0
```

Both modules can be imported fine outside of my outputter. Everything works as expected when running `salt-call`.

**Comment by gtmanfred** [comment]
can you provide the output of the `env` command?

Thanks,
Daniel

**Comment by nickhentschel** [comment]
```
> env
HOSTNAME=salt02.domain.com
SHELL=/bin/bash
TERM=screen-256color
HISTSIZE=1000
USER=root
LS_COLORS=rs=0:di=38;5;27:ln=38;5;51:mh=44;38;5;15:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=48;5;232;38;5;9:mi=05;48;5;232;38;5;15:su=48;5;196;38;5;15:sg=48;5;11;38;5;16:ca=48;5;196;38;5;226:tw=48;5;10;38;5;16:ow=48;5;10;38;5;21:st=48;5;21;38;5;15:ex=38;5;34:*.tar=38;5;9:*.tgz=38;5;9:*.arc=38;5;9:*.arj=38;5;9:*.taz=38;5;9:*.lha=38;5;9:*.lz4=38;5;9:*.lzh=38;5;9:*.lzma=38;5;9:*.tlz=38;5;9:*.txz=38;5;9:*.tzo=38;5;9:*.t7z=38;5;9:*.zip=38;5;9:*.z=38;5;9:*.Z=38;5;9:*.dz=38;5;9:*.gz=38;5;9:*.lrz=38;5;9:*.lz=38;5;9:*.lzo=38;5;9:*.xz=38;5;9:*.bz2=38;5;9:*.bz=38;5;9:*.tbz=38;5;9:*.tbz2=38;5;9:*.tz=38;5;9:*.deb=38;5;9:*.rpm=38;5;9:*.jar=38;5;9:*.war=38;5;9:*.ear=38;5;9:*.sar=38;5;9:*.rar=38;5;9:*.alz=38;5;9:*.ace=38;5;9:*.zoo=38;5;9:*.cpio=38;5;9:*.7z=38;5;9:*.rz=38;5;9:*.cab=38;5;9:*.jpg=38;5;13:*.jpeg=38;5;13:*.gif=38;5;13:*.bmp=38;5;13:*.pbm=38;5;13:*.pgm=38;5;13:*.ppm=38;5;13:*.tga=38;5;13:*.xbm=38;5;13:*.xpm=38;5;13:*.tif=38;5;13:*.tiff=38;5;13:*.png=38;5;13:*.svg=38;5;13:*.svgz=38;5;13:*.mng=38;5;13:*.pcx=38;5;13:*.mov=38;5;13:*.mpg=38;5;13:*.mpeg=38;5;13:*.m2v=38;5;13:*.mkv=38;5;13:*.webm=38;5;13:*.ogm=38;5;13:*.mp4=38;5;13:*.m4v=38;5;13:*.mp4v=38;5;13:*.vob=38;5;13:*.qt=38;5;13:*.nuv=38;5;13:*.wmv=38;5;13:*.asf=38;5;13:*.rm=38;5;13:*.rmvb=38;5;13:*.flc=38;5;13:*.avi=38;5;13:*.fli=38;5;13:*.flv=38;5;13:*.gl=38;5;13:*.dl=38;5;13:*.xcf=38;5;13:*.xwd=38;5;13:*.yuv=38;5;13:*.cgm=38;5;13:*.emf=38;5;13:*.axv=38;5;13:*.anx=38;5;13:*.ogv=38;5;13:*.ogx=38;5;13:*.aac=38;5;45:*.au=38;5;45:*.flac=38;5;45:*.mid=38;5;45:*.midi=38;5;45:*.mka=38;5;45:*.mp3=38;5;45:*.mpc=38;5;45:*.ogg=38;5;45:*.ra=38;5;45:*.wav=38;5;45:*.axa=38;5;45:*.oga=38;5;45:*.spx=38;5;45:*.xspf=38;5;45:
VIRTUAL_ENV=/salt-master/salt-mastervenv
MAIL=/var/spool/mail/root
PATH=/salt-master/salt-mastervenv/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
PWD=/root
LANG=en_US.UTF-8
PS1=(salt-mastervenv) [\u@\h \W]\$
HISTCONTROL=ignoredups
SHLVL=1
HOME=/root
LOGNAME=root
LESSOPEN=||/usr/bin/lesspipe.sh %s
_=/bin/env
```

**Comment by gtmanfred** [comment]
can you check `head -n1 $(which salt-minion)` and just make sure that it is set to use `/salt-master/salt-mastervenv/bin/python` and not `/usr/bin/python`?

Also, check `ps aux | grep salt-minion` and make sure it isn't using `/usr/bin/python`.

If you are starting the salt-minion process with a systemd unit, you will need to make sure that the venv path is available to systemd.  If this is being added by something in /etc/profile, you will have to modify the PATH in your systemd service unit by making the following file.

> /etc/systemd/system/salt-minion.service.d/path.conf
```
[Service]
Environment=PATH=/salt-master/salt-mastervenv/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
```

Thanks,
Daniel

**Comment by nickhentschel** [comment]
Here's the unit for the minion:

```
[Unit]
Description=The Salt minion service
After=network.target

[Service]
ExecStart=/salt-master/salt-mastervenv/bin/python /salt-master/salt-mastervenv/bin/salt-minion --config-dir=/etc/salt --pid-file=/var/run/salt/salt-minion.pid
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
```

We're literally specifying the python version from the virtualenv. 

```
> ps aux | grep salt-minion | head -n 1
root     24455  0.0  0.2 253792 20520 ?        Ss   16:48   0:00 /salt-master/salt-mastervenv/bin/python /salt-master/salt-mastervenv/bin/salt-minion --config-dir=/etc/salt --pid-file=/var/run/salt/salt-minion.pid
```

**Comment by gtmanfred** [comment]
And you can run `/salt-master/salt-mastervenv/bin/python -c 'import pkg_resources'`?

I think this has to be something weird in the way this whole thing is working being run from systemd.  Because if it works when using `salt-call` this starts a full salt-minion process inside the context of your shell.  Where when it is started by the unit, it is started in systemd's environment, which is not a shell so nothing gets sourced.  

Actually now that I think about it the `salt` command would be the thing that is handling the output, can you try running

```
/salt-master/salt-mastervenv/bin/python $(which salt) '*' test.version --out html_out -l debug
```

And see if that works?

Thanks,
Daniel

**Comment by gtmanfred** [comment]
yeah, that is super bizarre, i have no idea why that would be happening.

@saltstack/team-core does anyone else have any ideas?

Thanks,
Daniel

**Comment by gtmanfred** [comment]
@nickhentschel it might be worth while sending an email to the [salt-users](https://groups.google.com/forum/#!forum/salt-users) google group to see if anyone else has run into this 

And maybe checking on our slack or irc channel https://github.com/saltstack/salt/#get-saltstack-support-and-help

**Comment by DmitryKuzmenko** [comment]
@nickhentschel could you try to modify the systemd unit to source the `activate` script from the environment first. It can be done for instance by creating a shell script to run salt and call it from the unit instead of calling `salt-minion` directly.
/salt-master/salt-mastervenv/bin/salt-minion.sh
```
#!/bin/env bash
source /salt-master/salt-mastervenv/bin/activate
/salt-master/salt-mastervenv/bin/salt-minion --config-dir=/etc/salt --pid-file=/var/run/salt/salt-minion.pid
```
# chmod +x /salt-master/salt-mastervenv/bin/salt-minion.sh

in the unit file change the exec line:
```
[Service]
ExecStart=/salt-master/salt-mastervenv/bin/salt-minion.sh
```

**Comment by nickhentschel** [comment]
So here's the steps to reproduce:

1. Rebuild `virtualenv`

```
> mkdir -p /salt-master/salt-mastervenv
> virtualenv /salt-master/salt-mastervenv
> source /salt-master/salt-mastervenv/bin/activate
(salt-mastervenv) > pip install -r requirements.txt
```

2. Start `salt-minion`

```
(salt-mastervenv) > /salt-master/salt-mastervenv/bin/salt-minion --config-dir=/etc/salt --pid-file=/var/run/salt/salt-minion.pid -l debug
```

3. Test outputter with `salt-call` (works as expected)

```
(salt-mastervenv) > /salt-master/salt-mastervenv/bin/salt-call saltutil.sync_output saltenv=myenv
(salt-mastervenv) > /salt-master/salt-mastervenv/bin/salt-call test.version --out html_out
```

4. Test outputter with `salt` (results in import error)

```
(salt-mastervenv) > /salt-master/salt-mastervenv/bin/salt-run saltutil.sync_output saltenv=myenv
(salt-mastervenv) > /salt-master/salt-mastervenv/bin/salt '*' test.version --out html_out
```

Yeilds the following error:

```
...
[DEBUG   ] Failed to import output html_out:
Traceback (most recent call last):
  File "/salt-master/salt-mastervenv/lib/python2.7/site-packages/salt/loader.py", line 1412, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/var/cache/salt/master/extmods/output/html_out.py", line 10, in <module>
    from ansi2html import Ansi2HTMLConverter
  File "/salt-master/salt-mastervenv/lib/python2.7/site-packages/ansi2html/__init__.py", line 1, in <module>
    from ansi2html.converter import Ansi2HTMLConverter
  File "/salt-master/salt-mastervenv/lib/python2.7/site-packages/ansi2html/converter.py", line 26, in <module>
    import pkg_resources
ImportError: No module named pkg_resources
```
So I'm still getting the same error running `salt-minion` directly, so I doubt it's a problem with `systemd`. I'm not convinced it's not environment related, that definitely seems most likely, but at this point I'm running out of things to test.

**Comment by nickhentschel** [comment]
So I've attempted the same thing using python 3.6 in place of 2.7, and got a bit more information in the stack trace. Seeing a `ModuleNotFoundError` instead of a generic `ImportError`.

Still having no problem importing `pkg_resources`:

```
(salt-mastervenv) > python -c 'import pkg_resources'
(salt-mastervenv) > echo $?
0
```

```
...
[DEBUG   ] Failed to import output html_out:
Traceback (most recent call last):
  File "/salt-master/salt-mastervenv/lib/python3.6/site-packages/salt/loader.py", line 1405, in _load_module
    mod = spec.loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 251, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 675, in _load
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/var/cache/salt/master/extmods/output/html_out.py", line 10, in <module>
    from ansi2html import Ansi2HTMLConverter
  File "/salt-master/salt-mastervenv/lib/python3.6/site-packages/ansi2html/__init__.py", line 1, in <module>
    from ansi2html.converter import Ansi2HTMLConverter
  File "/salt-master/salt-mastervenv/lib/python3.6/site-packages/ansi2html/converter.py", line 26, in <module>
    import pkg_resources
ModuleNotFoundError: import of 'pkg_resources' halted; None in sys.modules
```

@DmitryKuzmenko any ideas?

**Comment by nickhentschel** [comment]
Seems the actual error message may be a result of a python bug: https://bugs.python.org/issue31642
