### ISSUE TITLE
Exception in tornado.application using scheduler

### ISSUE THREAD

**Issue by asymetrixs** [saltstack/salt#45822]
### Description of Issue/Question
Running the following tasks throws exceptions but only in log file:

```
Remove C:\Windows\Temp\cab_* Job:
  schedule.present:
    - name: sdevs_remove_c_wintmp_cab
    - function: cmd.run
    - job_args: 'forfiles /P "C:\Windows\Temp" /M cab_* /D -7 /C "cmd /C del @path'    
    - when:
        - Monday 8:00pm
        - Tuesday 8:00pm
        - Wednesday 8:00pm
        - Thursday 8:00pm
        - Friday 8:00pm
```

```
2018-02-01 12:12:15,665 [tornado.application][ERROR   ][12504] Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x0000000002A68BF8>, <tornado.concurrent.Future object at 0x0000000002AA69E8>)
Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\tornado\ioloop.py", line 605, in _run_callback
    ret = callback()
  File "c:\salt\bin\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "c:\salt\bin\lib\site-packages\tornado\ioloop.py", line 626, in _discard_future_result
    future.result()
  File "c:\salt\bin\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "c:\salt\bin\lib\site-packages\tornado\gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\salt\bin\lib\site-packages\salt\minion.py", line 817, in handle_event
    yield [minion.handle_event(package) for minion in self.minions]
  File "c:\salt\bin\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "c:\salt\bin\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "c:\salt\bin\lib\site-packages\tornado\gen.py", line 828, in callback
    result_list.append(f.result())
  File "c:\salt\bin\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "c:\salt\bin\lib\site-packages\tornado\gen.py", line 307, in wrapper
    yielded = next(result)
  File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1977, in handle_event
    self.manage_schedule(tag, data)
  File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1859, in manage_schedule
    self.schedule.run_job(name)
  File "c:\salt\bin\lib\site-packages\salt\utils\schedule.py", line 676, in run_job
    proc.start()
  File "c:\salt\bin\lib\site-packages\salt\utils\process.py", line 717, in start
    super(SignalHandlingMultiprocessingProcess, self).start()
  File "c:\salt\bin\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "c:\salt\bin\lib\multiprocessing\context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "c:\salt\bin\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "c:\salt\bin\lib\multiprocessing\popen_spawn_win32.py", line 66, in __init__
    reduction.dump(process_obj, to_child)
  File "c:\salt\bin\lib\multiprocessing\reduction.py", line 59, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'salt.NamespacedDictWrapper'>: attribute lookup NamespacedDictWrapper on salt failed
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```

And a different command:

```
Remove C:\Windows\Temp\cab_*:
  schedule.present:
    - name: sdevs_remove_c_wintmp_cab
    - function: cmd.run
    - job_args: 'Get-ChildItem -Path "C:\Windows\Temp\cab_*" -Force | Where-Object { !$_.PSIsContainer -and $_.CreationTime -lt (Get-Date).AddDays(-7) } | Remove-Item -Force'
    - job_kwargs:
        shell: powershell
    - when:
        - Monday 8:00pm
        - Tuesday 8:00pm
        - Wednesday 8:00pm
        - Thursday 8:00pm
        - Friday 8:00pm
```

```
2018-02-01 12:12:33,774 [tornado.application][ERROR   ][12504] Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x00000000029B9730>, <tornado.concurrent.Future object at 0x0000000002AA69E8>)
Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\tornado\ioloop.py", line 605, in _run_callback
    ret = callback()
  File "c:\salt\bin\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "c:\salt\bin\lib\site-packages\tornado\ioloop.py", line 626, in _discard_future_result
    future.result()
  File "c:\salt\bin\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "c:\salt\bin\lib\site-packages\tornado\gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\salt\bin\lib\site-packages\salt\minion.py", line 817, in handle_event
    yield [minion.handle_event(package) for minion in self.minions]
  File "c:\salt\bin\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "c:\salt\bin\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "c:\salt\bin\lib\site-packages\tornado\gen.py", line 828, in callback
    result_list.append(f.result())
  File "c:\salt\bin\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "c:\salt\bin\lib\site-packages\tornado\gen.py", line 307, in wrapper
    yielded = next(result)
  File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1977, in handle_event
    self.manage_schedule(tag, data)
  File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1859, in manage_schedule
    self.schedule.run_job(name)
  File "c:\salt\bin\lib\site-packages\salt\utils\schedule.py", line 676, in run_job
    proc.start()
  File "c:\salt\bin\lib\site-packages\salt\utils\process.py", line 717, in start
    super(SignalHandlingMultiprocessingProcess, self).start()
  File "c:\salt\bin\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "c:\salt\bin\lib\multiprocessing\context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "c:\salt\bin\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "c:\salt\bin\lib\multiprocessing\popen_spawn_win32.py", line 66, in __init__
    reduction.dump(process_obj, to_child)
  File "c:\salt\bin\lib\multiprocessing\reduction.py", line 59, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'salt.NamespacedDictWrapper'>: attribute lookup NamespacedDictWrapper on salt failed
```

Salt Version 2017.7.2 64-Bit on Windows 7, Python 3.5.3 64-Bit, Tornado 4.5.1 (default salt-minion installation, no detailed information due to airgap, hope this helps)

**Comment by phsteve** [comment]
+1. I can trigger the exact same issue with `salt 'minion_id' schedule.run_job 'Schedule name here'` on Windows. Additionally if I try to do a `schedule.run_job 'Disabled chedule name' force=True` on a disabled schedule I get the following traceback:

```
2018-02-01 15:04:06,623 [tornado.application][ERROR   ][4624] Exception in callback functools.partial(<function wrap.<lo
cals>.null_wrapper at 0x000000EBD10931E0>, <tornado.concurrent.Future object at 0x000000EBCF37B6D8>)
Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\tornado\ioloop.py", line 605, in _run_callback
    ret = callback()
  File "c:\salt\bin\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "c:\salt\bin\lib\site-packages\tornado\ioloop.py", line 626, in _discard_future_result
    future.result()
  File "c:\salt\bin\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "c:\salt\bin\lib\site-packages\tornado\gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\salt\bin\lib\site-packages\salt\minion.py", line 817, in handle_event
    yield [minion.handle_event(package) for minion in self.minions]
  File "c:\salt\bin\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "c:\salt\bin\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "c:\salt\bin\lib\site-packages\tornado\gen.py", line 828, in callback
    result_list.append(f.result())
  File "c:\salt\bin\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "c:\salt\bin\lib\site-packages\tornado\gen.py", line 307, in wrapper
    yielded = next(result)
  File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1977, in handle_event
    self.manage_schedule(tag, data)
  File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1859, in manage_schedule
    self.schedule.run_job(name)
  File "c:\salt\bin\lib\site-packages\salt\utils\schedule.py", line 676, in run_job
    proc.start()
  File "c:\salt\bin\lib\site-packages\salt\utils\process.py", line 717, in start
    super(SignalHandlingMultiprocessingProcess, self).start()
  File "c:\salt\bin\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "c:\salt\bin\lib\multiprocessing\context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "c:\salt\bin\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "c:\salt\bin\lib\multiprocessing\popen_spawn_win32.py", line 66, in __init__
    reduction.dump(process_obj, to_child)
  File "c:\salt\bin\lib\multiprocessing\reduction.py", line 59, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: dict items iterator must return 2-tuples
```

Version report:

```
PS C:\salt\bin> salt-call.bat --versions-report
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.0
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2012ServerR2
         system: Windows
        version: 2012ServerR2 6.3.9600 SP0 Multiprocessor Free
```
