### ISSUE TITLE
[Oxygen] unable to `load_yaml` in rc1

### ISSUE THREAD

**Issue by gtmanfred** [saltstack/salt#45845]
### Description of Issue/Question
This yaml map is unable to be loaded in oxygen.rc1

https://raw.githubusercontent.com/saltstack-formulas/mysql-formula/master/mysql/defaults.yaml

I am getting this error.

```
local:
    Data failed to compile:
----------
    Rendering SLS 'base:test' failed: Jinja error: Conflicting ID 'mysqldump'
/var/cache/salt/minion/files/base/defaults.yml(5):
---
# vim: sts=2 ts=2 sw=2 et ai
#
# SET ALL PARAMS IN CONFIG SECTION USING UNDERSCORE, NOT HYPHEN
# so that it works correctly
{% load_yaml as rawmap %}    <======================
Ubuntu:
  server: mysql-server
  client: mysql-client
  service: mysql
  python: python-mysqldb
[...]
---
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 419, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 1, in top-level template code
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1013, in make_module
    return TemplateModule(self, self.new_context(vars, shared, locals))
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1070, in __init__
    self._body_stream = list(template.root_render_func(context))
  File "/var/cache/salt/minion/files/base/defaults.yml", line 5, in top-level template code
    {% load_yaml as rawmap %}
  File "/usr/lib/python2.7/site-packages/salt/utils/jinja.py", line 852, in load_yaml
    return salt.utils.data.decode(salt.utils.yaml.safe_load(value))
  File "/usr/lib/python2.7/site-packages/salt/utils/yamlloader.py", line 168, in safe_load
    return yaml.load(stream, Loader=Loader)
  File "/usr/lib64/python2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/lib64/python2.7/site-packages/yaml/constructor.py", line 39, in get_single_data
    return self.construct_document(node)
  File "/usr/lib64/python2.7/site-packages/yaml/constructor.py", line 48, in construct_document
    for dummy in generator:
  File "/usr/lib64/python2.7/site-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/usr/lib/python2.7/site-packages/salt/utils/yamlloader.py", line 91, in construct_mapping
    raise ConstructorError('Conflicting ID \'{0}\''.format(key))
ConstructorError: Conflicting ID 'mysqldump'
```

### Setup
Put the above mentioned defaults.yaml in /srv/salt/defaults.yaml

Then add the state 

>/srv/salt/test.sls
```
{%- from 'defaults.yaml' import rawmap with context %}
```

run `salt-call --local state.apply test`

Watch it explode.

### Versions Report

```
[root@salt salt]# salt-call --versions-report
Salt Version:
           Salt: 2018.2.0-1773-g550a613

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.9.60-linuxkit-aufs
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

**Comment by rallytime** [comment]
@terminalmage You have been making changes in the yamlloader util a lot lately. Can you look into this here?

**Comment by terminalmage** [comment]
@gtmanfred This doesn't look like a Salt bug at all. It's telling you exactly what is wrong, there is a duplicate ID called `mysqldump`. Check lines 306 and 358 of the defaults.yaml, there are two `mysqldump` keys there.

We could perhaps provide an error that doesn't expose the traceback, though.

**Comment by gtmanfred** [comment]
bah, yeah it looks like we are actually finally handling it correctly now.  It would be helpful to mark the line.

I swear i looked through this file a just didn't see those ones.  But it also looks like we just skipped over this error in older versions.

I will fix the formula

Thanks,
Daniel

**Comment by terminalmage** [comment]
#45885 gets rid of the traceback and adds context to the YAML error.
