### ISSUE TITLE
slack engine fails to connect to slack

### ISSUE THREAD

**Issue by viq** [saltstack/salt#45853]
### Description of Issue/Question
```Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/slackclient/client.py", line 52, in rtm_connect
    self.server.rtm_connect(use_rtm_start=with_team_state, **kwargs)
  File "/usr/lib/python2.7/site-packages/slackclient/server.py", line 81, in rtm_connect
    self.connect_slack_websocket(self.ws_url)
  File "/usr/lib/python2.7/site-packages/slackclient/server.py", line 116, in connect_slack_websocket
    raise SlackConnectionError(message=str(e))
SlackConnectionError: cafile, capath and cadata cannot be all omitted
[CRITICAL] Engine <salt.loader.LazyLoader object at 0x623094c97e50> could not be started! Error: Could not connect to slack
```
### Setup
Exactly as described at https://docs.saltstack.com/en/latest/ref/engines/all/salt.engines.slack.html#module-salt.engines.slack

### Steps to Reproduce Issue
Follow guide. Start `salt-master`

### Versions Report
```$ salt --versions-report
/usr/lib/python2.7/site-packages/msgpack/__init__.py:47: FutureWarning: use_bin_type option is not specified. Default value of the option will be changed in future version.
  return Packer(**kwargs).pack(o)
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.11.4
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.26.0
        libnacl: 1.6.1
       M2Crypto: 0.27.0
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.0
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.3
         Python: 2.7.14 (default, Jan  5 2018, 10:41:29)
   python-gnupg: 0.3.9.dev0
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.2.2

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 4.14.15-1-hardened
         system: Linux
        version: Not Installed
```
with `slackclient` version `1.1.2`

**Comment by viq** [comment]
This seems to be related to https://github.com/slackapi/python-slackclient/issues/189

**Comment by gtmanfred** [comment]
That appears to be fixed with `websocket-client` 0.44.0?

https://github.com/slackapi/python-slackclient/issues/189#issuecomment-311181341

have you tried running the code manually and checking that `rtm_connect` is returning false?

Thanks,
Daniel

**Comment by viq** [comment]
```$ pacman -Qi python2-websocket-client
Name            : python2-websocket-client
Version         : 0.46.0-1
```

Sorry, but how would I run it manually? I don't know python well enough yet to know how the pieces go together, sorry for that.

**Comment by gtmanfred** [comment]
basically, copy the engine file, and then copy all the code out and see if it is still able to run.

or you can add `log.critical(whatever)` to the module, and it will log the output and you can just make sure that rtm_connect is actually failing.

```
import slackclient
sc = slackclient.SlackClient(<token>)
print(sc.rtm_connect())
```

This should basically show you if your token works for connecting.

**Comment by viq** [comment]
Thank you!
This appears to not be related to salt then:
```python
$ python2
Python 2.7.14 (default, Jan  5 2018, 10:41:29)
[GCC 7.2.1 20171224] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import slackclient
>>> sc = slackclient.SlackClient('xxxxxx')
>>> print(sc.rtm_connect())
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/slackclient/client.py", line 52, in rtm_connect
    self.server.rtm_connect(use_rtm_start=with_team_state, **kwargs)
  File "/usr/lib/python2.7/site-packages/slackclient/server.py", line 81, in rtm_connect
    self.connect_slack_websocket(self.ws_url)
  File "/usr/lib/python2.7/site-packages/slackclient/server.py", line 116, in connect_slack_websocket
    raise SlackConnectionError(message=str(e))
SlackConnectionError: cafile, capath and cadata cannot be all omitted
False
>>> 
```

**Comment by gtmanfred** [comment]
Well, it could be related, if we need to upgrade the way salt uses slack client, you may have run into another issue where archlinux's version is too new, and we need to make changes to cover it.

**Comment by viq** [comment]
https://github.com/slackapi/python-slackclient/issues/289 created to check with upstream.
