### ISSUE TITLE
LGPO No longer working

### ISSUE THREAD

**Issue by darrenjlowe** [saltstack/salt#45868]
After upgrading to 2017.7.3 on both master and minion, running salt "*MACHINENAME" lgpo.get machine return_full_policy_names=True brings back an error, on 2017.7.2 this was working

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
On salt master just run

salt "*MACHINENAME" lgpo.get machine return_full_policy_names=True

 The minion function caused an exception: Traceback (most recent call last):
     File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1493, in _thread_return
       return_data = executor.execute()
     File "c:\salt\bin\lib\site-packages\salt\executors\direct_call.py", line 28, in execute
       return self.func(*self.args, **self.kwargs)
     File "c:\salt\bin\lib\site-packages\salt\modules\win_lgpo.py", line 5050, in get
       log.debug('Value {0} found for reg policy {1}'.format(class_vals[policy_name], policy_name))
   UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 0: ordinal not in range(128)

### Versions Report
Salt Minion

C:\salt>salt-minion --versions-report
Salt Version:
           Salt: 2017.7.3

Dependency Versions:
           cffi: 1.10.0
       cherrypy: unknown
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]
   python-gnupg: 0.4.0
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 10
         system: Windows
        version: 10 10.0.15063  Multiprocessor Free

C:\salt>

Salt Master

Salt Version:
           Salt: 2017.7.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.17.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

**Comment by damon-atkins** [comment]
@lomeroe  @twangboy  This may also impacted on 2016.11

**Comment by damon-atkins** [comment]
@darrenjlowe  what is the policy name please.  Is it English? What Language is the Windows Install?

This may also be #42278 `salt logging with plain str (ascii) with unicode chars causes UnicodeDecodeError PY2`

**Comment by darrenjlowe** [comment]
@damon-atkins the above command should check all Group Policy settings and return anything that is configured, the machines being checked are all English (U.S.)

**Comment by lomeroe** [comment]
@darrenjlowe is the log level on your minion set to debug? (since it seems to be barfing on a debug log statement).  

On a fresh 2016 server, I'm able to run the command successfully (even with debug on).  Would you mind adding this at line 5046 and re-running?

```
log.debug('LOOK AT ME: policy {0}'.format(policy_name))
```

That should give us which registry policy is having an issue.  Either way, the debug statement might need  to better handle the values, since they may not be console/print friendly.

**Comment by darrenjlowe** [comment]
@lomeroe the minion is Windows 10 and not Server 2016, although it should not make any difference, it might....

Will look at adding debug option

**Comment by lomeroe** [comment]
@darrenjlowe right, I don't have quick access to any Win10, I should have noted that in my response as to why I used 2016.

**Comment by twangboy** [comment]
I am unable to reproduce this issue. Could you send me a copy of the `Registry.pol` file?

You can find it in:
```
C:\Windows\System32\GroupPolicy\Machine
```

My email:
slee@saltstack.com

**Comment by darrenjlowe** [comment]
Looks like from a command line from a salt master trying to run the following also does not work

---------------

salt "MACHINAME" reg.read_value HKEY_LOCAL_MACHINE 'SOFTWARE\Microsoft\Windows\CurrentVersion\Authentication\LogonUI' 'SelectedUserSID'
---------------

Even with double escape characters

-----------

MACHINENAME:
    ----------
    comment:
        Cannot find SelectedUserSID in HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Authentication\LogonUI
    hive:
        HKEY_LOCAL_MACHINE
    key:
        SOFTWARE\Microsoft\Windows\CurrentVersion\Authentication\LogonUI
    success:
        False
    vdata:
        None
    vname:
        SelectedUserSID

**Comment by darrenjlowe** [comment]
@lomeroe I enabled debug logging and added "log.debug('LOOK AT ME: policy {0}'.format(policy_name))"






2018-02-07 08:48:43,892 [salt.minion      :1324][INFO    ][7268] User root Executing command lgpo.get with jid 20180207084846218556
2018-02-07 08:48:43,892 [salt.minion      :1330][DEBUG   ][7268] Command details {'tgt_type': 'glob', 'jid': '20180207084846218556', 'tgt': '*vdi*', 'ret': '', 'user': 'root', 'arg': ['machine', {'return_full_policy_names': True, '__kwarg__': True}], 'fun': 'lgpo.get'}
2018-02-07 08:48:45,517 [salt.log.setup   :876 ][DEBUG   ][7624] Multiprocessing queue logging configured for the process running under PID: 7624
2018-02-07 08:48:45,517 [salt.config      :1952][DEBUG   ][7624] Reading configuration from c:\salt\conf\minion
2018-02-07 08:48:45,581 [salt.config      :2101][DEBUG   ][7624] Including configuration from 'c:\salt\conf\minion.d\_schedule.conf'
2018-02-07 08:48:45,581 [salt.config      :1952][DEBUG   ][7624] Reading configuration from c:\salt\conf\minion.d\_schedule.conf
2018-02-07 08:48:45,596 [salt.config      :2101][DEBUG   ][7624] Including configuration from 'c:\salt\conf\minion.d\cpe_windows.conf'
2018-02-07 08:48:45,596 [salt.config      :1952][DEBUG   ][7624] Reading configuration from c:\salt\conf\minion.d\cpe_windows.conf
2018-02-07 08:48:46,611 [salt.loaded.int.grains.core:987 ][DEBUG   ][7624] Motherboard info not available on this system
2018-02-07 08:48:46,642 [salt.minion      :993 ][INFO    ][7624] Creating minion process manager
2018-02-07 08:48:46,658 [salt.minion      :1448][INFO    ][7624] Starting a new job with PID 7624
2018-02-07 08:48:46,674 [salt.utils.lazy  :97  ][DEBUG   ][7624] LazyLoaded lgpo.get
2018-02-07 08:48:46,690 [salt.utils.lazy  :97  ][DEBUG   ][7624] LazyLoaded direct_call.get
2018-02-07 08:48:46,721 [salt.utils.lazy  :97  ][DEBUG   ][7624] LazyLoaded file.file_exists
2018-02-07 08:48:47,408 [salt.loaded.int.module.win_lgpo:5046][DEBUG   ][7624] LOOK AT ME: policy NullSessionPipes
2018-02-07 08:48:47,408 [salt.utils.lazy  :97  ][DEBUG   ][7624] LazyLoaded reg.read_value
2018-02-07 08:48:47,408 [salt.loaded.int.module.win_lgpo:5051][DEBUG   ][7624] Value None found for reg policy NullSessionPipes
2018-02-07 08:48:47,408 [salt.loaded.int.module.win_lgpo:5070][DEBUG   ][7624] Working with ScriptIni setting ShutdownPowershellScripts
2018-02-07 08:48:47,408 [salt.loaded.int.module.win_lgpo:5046][DEBUG   ][7624] LOOK AT ME: policy RestrictNullSessAccess
2018-02-07 08:48:47,408 [salt.loaded.int.module.win_lgpo:5051][DEBUG   ][7624] Value 1 found for reg policy RestrictNullSessAccess
2018-02-07 08:48:47,408 [salt.loaded.int.module.win_lgpo:2655][DEBUG   ][7624] item == 1
2018-02-07 08:48:47,408 [salt.loaded.int.module.win_lgpo:2665][DEBUG   ][7624] returning value Enabled
2018-02-07 08:48:47,408 [salt.loaded.int.module.win_lgpo:5046][DEBUG   ][7624] LOOK AT ME: policy ConsentPromptBehaviorAdmin
2018-02-07 08:48:47,408 [salt.loaded.int.module.win_lgpo:5051][DEBUG   ][7624] Value 5 found for reg policy ConsentPromptBehaviorAdmin
2018-02-07 08:48:47,424 [salt.loaded.int.module.win_lgpo:2655][DEBUG   ][7624] item == 5
2018-02-07 08:48:47,424 [salt.loaded.int.module.win_lgpo:2665][DEBUG   ][7624] returning value Prompt for consent for non-Windows binaries
2018-02-07 08:48:47,424 [salt.utils.lazy  :97  ][DEBUG   ][7624] LazyLoaded cmd.run
2018-02-07 08:48:47,424 [salt.loaded.int.module.cmdmod:388 ][INFO    ][7624] Executing command 'secedit /export /cfg c:\salt\var\cache\salt\minion\salt-secedit-dump-ca0d584c84784849ad6b56649b3b044a.txt' in directory 'C:\Users\darren.lowe'
2018-02-07 08:48:47,721 [salt.loaded.int.module.cmdmod:966 ][DEBUG   ][7624] output:                                                                            
The task has completed successfully.
See log %windir%\security\logs\scesrv.log for detail info.
2018-02-07 08:48:47,721 [salt.loaded.int.module.win_lgpo:2537][DEBUG   ][7624] we have Not Defined for the driver signing value
2018-02-07 08:48:47,721 [salt.loaded.int.module.cmdmod:388 ][INFO    ][7624] Executing command 'secedit /export /cfg c:\salt\var\cache\salt\minion\salt-secedit-dump-a017e3aa87b34d68b5578cbcd5b28ede.txt' in directory 'C:\Users\darren.lowe'
2018-02-07 08:48:47,924 [salt.loaded.int.module.cmdmod:966 ][DEBUG   ][7624] output:                                                                            
The task has completed successfully.
See log %windir%\security\logs\scesrv.log for detail info.
2018-02-07 08:48:47,924 [salt.loaded.int.module.win_lgpo:2655][DEBUG   ][7624] item == 0
2018-02-07 08:48:47,924 [salt.loaded.int.module.win_lgpo:2665][DEBUG   ][7624] returning value Disabled
2018-02-07 08:48:47,924 [salt.loaded.int.module.win_lgpo:5046][DEBUG   ][7624] LOOK AT ME: policy EnableSecureUIAPaths
2018-02-07 08:48:47,924 [salt.loaded.int.module.win_lgpo:5051][DEBUG   ][7624] Value 1 found for reg policy EnableSecureUIAPaths
2018-02-07 08:48:47,924 [salt.loaded.int.module.win_lgpo:2655][DEBUG   ][7624] item == 1
2018-02-07 08:48:47,924 [salt.loaded.int.module.win_lgpo:2665][DEBUG   ][7624] returning value Enabled
2018-02-07 08:48:47,924 [salt.loaded.int.module.win_lgpo:5046][DEBUG   ][7624] LOOK AT ME: policy FilterAdministratorToken
2018-02-07 08:48:47,924 [salt.loaded.int.module.win_lgpo:5051][DEBUG   ][7624] Value 0 found for reg policy FilterAdministratorToken
2018-02-07 08:48:47,924 [salt.loaded.int.module.win_lgpo:2655][DEBUG   ][7624] item == 0
2018-02-07 08:48:47,924 [salt.loaded.int.module.win_lgpo:2665][DEBUG   ][7624] returning value Disabled
2018-02-07 08:48:47,924 [salt.loaded.int.module.win_lgpo:5046][DEBUG   ][7624] LOOK AT ME: policy ValidateAdminCodeSignatures
2018-02-07 08:48:47,924 [salt.loaded.int.module.win_lgpo:5051][DEBUG   ][7624] Value 0 found for reg policy ValidateAdminCodeSignatures
2018-02-07 08:48:47,924 [salt.loaded.int.module.win_lgpo:2655][DEBUG   ][7624] item == 0
2018-02-07 08:48:47,924 [salt.loaded.int.module.win_lgpo:2665][DEBUG   ][7624] returning value Disabled
2018-02-07 08:48:47,924 [salt.loaded.int.module.win_lgpo:5046][DEBUG   ][7624] LOOK AT ME: policy Server_EnableSecuritySignature
2018-02-07 08:48:47,924 [salt.loaded.int.module.win_lgpo:5051][DEBUG   ][7624] Value 0 found for reg policy Server_EnableSecuritySignature
2018-02-07 08:48:47,940 [salt.loaded.int.module.win_lgpo:2655][DEBUG   ][7624] item == 0
2018-02-07 08:48:47,940 [salt.loaded.int.module.win_lgpo:2665][DEBUG   ][7624] returning value Disabled
2018-02-07 08:48:47,940 [salt.loaded.int.module.win_lgpo:5046][DEBUG   ][7624] LOOK AT ME: policy FullPrivilegeAuditing
2018-02-07 08:48:47,940 [salt.minion      :1553][WARNING ][7624] The minion function caused an exception
2018-02-07 08:48:47,940 [salt.utils.event :313 ][DEBUG   ][7624] SaltEvent PUB socket URI: 4510
2018-02-07 08:48:47,940 [salt.minion      :2015][DEBUG   ][7268] Minion of "SALTMASTER_2.domain.com" is handling event tag '_salt_error'
2018-02-07 08:48:47,940 [salt.minion      :2178][DEBUG   ][7268] Forwarding salt error event tag=_salt_error
2018-02-07 08:48:47,940 [salt.transport.zeromq:89  ][DEBUG   ][7268] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'MACHINENAME', 'tcp://MASTER_2_IPADDRESS:PORT', 'aes')
2018-02-07 08:48:47,940 [salt.crypt       :378 ][DEBUG   ][7268] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'MACHINENAME', 'tcp://MASTER_2_IPADDRESS:PORT')
2018-02-07 08:48:48,003 [salt.minion      :2015][DEBUG   ][7268] Minion of "SALTMASTER_1.domain.com" is handling event tag '_salt_error'
2018-02-07 08:48:48,003 [salt.minion      :2178][DEBUG   ][7268] Forwarding salt error event tag=_salt_error
2018-02-07 08:48:48,003 [salt.transport.zeromq:89  ][DEBUG   ][7268] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'MACHINENAME', 'tcp://MASTER_1_IPADDRESS:PORT', 'aes')
2018-02-07 08:48:48,003 [salt.crypt       :378 ][DEBUG   ][7268] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'MACHINENAME', 'tcp://MASTER_1_IPADDRESS:PORT')
2018-02-07 08:48:47,940 [salt.utils.event :316 ][DEBUG   ][7624] SaltEvent PULL socket URI: 4511
2018-02-07 08:48:47,940 [salt.transport.ipc:255 ][DEBUG   ][7624] Initializing new IPCClient for path: 4511
2018-02-07 08:48:47,940 [salt.utils.event :728 ][DEBUG   ][7624] Sending event: tag = _salt_error; data = {'message': u'The minion function caused an exception', 'args': ('The minion function caused an exception',), '_stamp': '2018-02-07T16:48:47.940000'}
2018-02-07 08:48:47,940 [salt.minion      :1173][DEBUG   ][7624] Minion return retry timer set to 6 seconds (randomized)
2018-02-07 08:48:47,940 [salt.minion      :1725][INFO    ][7624] Returning information for job: 20180207084846218556
2018-02-07 08:48:48,081 [salt.transport.zeromq:89  ][DEBUG   ][7624] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'MACHINENAME', 'tcp://MASTER_1_IPADDRESS:PORT', 'aes')
2018-02-07 08:48:48,081 [salt.crypt       :378 ][DEBUG   ][7624] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'MACHINENAME', 'tcp://MASTER_1_IPADDRESS:PORT')
2018-02-07 08:48:48,111 [salt.transport.zeromq:89  ][DEBUG   ][7624] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'MACHINENAME', 'tcp://MASTER_1_IPADDRESS:PORT', 'clear')
2018-02-07 08:48:48,158 [salt.crypt       :760 ][DEBUG   ][7624] Decrypting the current master AES key
2018-02-07 08:48:48,158 [salt.crypt       :684 ][DEBUG   ][7624] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
2018-02-07 08:48:48,315 [salt.minion      :1592][DEBUG   ][7624] minion return: {'fun_args': ['machine', {'return_full_policy_names': True}], 'jid': '20180207084846218556', 'return': 'The minion function caused an exception: Traceback (most recent call last):\n  File "C:\\salt\\bin\\lib\\site-packages\\salt\\minion.py", line 1493, in _thread_return\n    return_data = executor.execute()\n  File "C:\\salt\\bin\\lib\\site-packages\\salt\\executors\\direct_call.py", line 28, in execute\n    return self.func(*self.args, **self.kwargs)\n  File "C:\\salt\\bin\\lib\\site-packages\\salt\\modules\\win_lgpo.py", line 5051, in get\n    log.debug(\'Value {0} found for reg policy {1}\'.format(class_vals[policy_name], policy_name))\nUnicodeDecodeError: \'ascii\' codec can\'t decode byte 0x80 in position 0: ordinal not in range(128)\n', 'success': False, 'fun': 'lgpo.get', 'out': 'nested'}

**Comment by darrenjlowe** [comment]
@twangboy email sent

**Comment by twangboy** [comment]
@darrenjlowe Taking a look

**Comment by lomeroe** [comment]
@darrenjlowe Looks like FullPrivilegeAuditing is the culprit policy.  That particular policy is a "registry" policy (where the registry value is queried to determine if it is Enabled/Disabled).  I know I have seen systems where the registry value is '30 00' (not sure if this is the same case for your actual reg value), which would break things pre-2016.11.9 too.  My searches haven't been able to find anything as to why there is additional binary data outside of just 00/01 to enable/disable the policy has the MMC snap-in does.

It may be (probably just is) that they key is more complicated than just a 0 Enabled/1 Disabled as the module assumes (and as it appears from editing via the snap-in).  I personally just haven't been able to find anything on what the extra data might mean in order to properly process it.  Or even determine why some systems have the additional data in the value.

That said, the display of the data in debug logs should change to somehow handle the binary data in some manner that doesn't cause it to barf....looks like there is plenty of discussion in the PR on that front.

**Comment by twangboy** [comment]
Yeah, the registry entry for FullPrivilegeAuditing was set to REG_BINARY `80`. Which didn't translate cleanly for the `log.debug`. I think the PR I submitted above will fix this issue... After I fix a few more things on it.

**Comment by lomeroe** [comment]
@twangboy perhaps fullprivilegeauditing should have its transform changed (a new transform) to accept anything other than 1 as disabled, this appears to be what the GUI is doing.

Strangely, using secedit to export the policy show different results.  Anything other than 0 or 1 are not exported.  With 80 in the registry, a secedit export shows an empty value:
```
MACHINE\System\CurrentControlSet\Control\Lsa\FullPrivilegeAuditing=3,
```
And nothing is changed when importing the config with a secedit.  In other words, an export of a "Disabled" FullPrivilegeAuditng, where the registry has 80 or '30 00' or anything else seems to not disable the policy on a system that had it enabled...

Changing the transform would keep salt from modifying the value, unless the policy was set to "enabled" (would hard set it to 01) or "not configured" which would delete the value.  This way, if the value is somehow used for something else, salt wouldn't be making a change to the value when the policy in question (Audit the use of backup/restore) is effectively disabled by anything other than 1...

**Comment by twangboy** [comment]
I believe this has been resolved.
