### ISSUE TITLE
cloud.profile regression in 2017.7.3

### ISSUE THREAD

**Issue by ipmb** [saltstack/salt#45863]
### Description of Issue/Question

4a77560646b50d48270d59e7078d301e6eee5f84 introduced a bug which breaks the `cloud.profile` module for me.

```
AttributeError: 'list' object has no attribute 'copy'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 391, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 204, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/cloud.py", line 200, in profile_
    info = client.profile(profile, names, vm_overrides=vm_overrides, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 344, in profile
    mapper = salt.cloud.Map(self._opts_defaults(**kwargs))
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 237, in _opts_defaults
    for provider in list(_providers).copy():
```

I think the intent was ```list(_providers.copy())```.

### Steps to Reproduce Issue

`salt-call -ldebug cloud.profile profile=my_profile names=[my_minion]`

### Versions Report

```
Salt Version:
           Salt: 2017.7.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.0
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Nov 23 2017, 15:49:48)
   python-gnupg: 0.3.6
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
         locale: UTF-8
        machine: x86_64
        release: 3.13.0-123-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by gtmanfred** [comment]
There is a fix for that, i didn't realize that this was in 2017.7 or i would have pushed for it to be fixed before 2017.7.3 got sent out.

https://github.com/saltstack/salt/pull/45742

**Comment by dave92082** [comment]
This was working perfectly fine in 2017.7.2 and it broke for us on deploying a new 2017.7.3. PLEASE FIX THIS as all of our workflows depend on cloud orchestrations

**Comment by garethgreenaway** [comment]
@ipmb Thanks for the report.  We'll get this fix backported for 2017.7.4.

**Comment by max-orhai** [comment]
I'm running into this issue too. I'm using the saltstack.com debian packages and had to revert to 2017.7.2.

In Python 3 `list.copy` is defined, but not in Python 2.7.12. Anyway, I don't think it's necessary to take a copy of a freshly made list like that.

**Comment by hemebond** [comment]
I am able to create new cloud (EC2) instances with 2017.7.4.
