### ISSUE TITLE
dockerng.image_present state fails due to CommandExecutionError

### ISSUE THREAD

**Issue by ChaosOrd** [saltstack/salt#45860]
### Description of Issue/Question
Hi,

I am trying to manage docker images via salt. I have added the following lines to my sls configuration file:

```
root/redis:latest:
  dockerng.image_present
```

After running a state.highstate command I am getting  the following error:

```
          ID: root/redis:latest
    Function: dockerng.image_present
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1843, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1795, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/docker.py", line 189, in image_present
                  **salt.utils.clean_kwargs(**kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1795, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/docker_image.py", line 174, in present
                  all_tags = __salt__['docker.list_tags']()
                File "/usr/lib/python2.7/dist-packages/salt/modules/dockermod.py", line 1482, in list_tags
                  for item in six.itervalues(images()):
                File "/usr/lib/python2.7/dist-packages/salt/modules/dockermod.py", line 1271, in images
                  response = _client_wrapper('images', all=kwargs.get('all', False))
                File "/usr/lib/python2.7/dist-packages/salt/modules/dockermod.py", line 404, in wrapper
                  ret = wrapped(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/dockermod.py", line 652, in _client_wrapper
                  raise CommandExecutionError(msg)
              CommandExecutionError: Unable to perform images: unbound method __init__() must be called with HTTPConnectionPool instance as first argument (got UnixHTTPConnectionPool instance instead)
     Started: 17:06:50.335178
    Duration: 2.885 ms
     Changes:   
```
### Versions Report

master:

```
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Nov 23 2017, 15:49:48)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
         locale: UTF-8
        machine: x86_64
        release: 3.13.0-74-generic
         system: Linux
        version: Ubuntu 14.04 trusty

```

minion:

```
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: 1.7.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.10.0-42-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

Many thanks

**Comment by gtmanfred** [comment]
I am unable to replicate this.

```
[root@salt salt]# cat /srv/salt/test.sls
redis:latest:
  docker_image.present
[root@salt salt]# salt-call --local -l debug state.apply test
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] /etc/resolv.conf: The domain and search keywords are mutually exclusive.
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded state.apply
[DEBUG   ] LazyLoaded saltutil.is_running
[DEBUG   ] LazyLoaded grains.get
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[DEBUG   ] Updating roots fileserver cache
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] In saltenv 'base', looking at rel_path 'test.sls' to resolve 'salt://test.sls'
[DEBUG   ] In saltenv 'base', ** considering ** path '/var/cache/salt/minion/files/base/test.sls' to resolve 'salt://test.sls'
[DEBUG   ] compile template: /var/cache/salt/minion/files/base/test.sls
[DEBUG   ] Jinja search path: ['/var/cache/salt/minion/files/base']
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/test.sls' using 'jinja' renderer: 0.00287389755249
[DEBUG   ] Rendered data from file: /var/cache/salt/minion/files/base/test.sls:
redis:latest:
  docker_image.present

[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Results of YAML rendering:
OrderedDict([('redis:latest', 'docker_image.present')])
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/test.sls' using 'yaml' renderer: 0.00353288650513
[DEBUG   ] Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
[DEBUG   ] No config file found
[DEBUG   ] Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
[DEBUG   ] No config file found
[DEBUG   ] http://localhost:None "GET /version HTTP/1.1" 200 566
[DEBUG   ] Attempting to run docker-py's "version" function with args=() and kwargs={}
[DEBUG   ] http://localhost:None "GET /v1.35/version HTTP/1.1" 200 566
[DEBUG   ] LazyLoaded docker.version
[DEBUG   ] LazyLoaded docker_image.present
[INFO    ] Running state [redis:latest] at time 18:43:25.269169
[INFO    ] Executing state docker_image.present for [redis:latest]
[DEBUG   ] Attempting to run docker-py's "images" function with args=() and kwargs={'all': False}
[DEBUG   ] http://localhost:None "GET /v1.35/images/json?only_ids=0&all=0 HTTP/1.1" 200 None
[DEBUG   ] Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
[DEBUG   ] No config file found
[DEBUG   ] Attempting to run docker-py's "pull" function with args=('redis',) and kwargs={'tag': 'latest', 'stream': True}
[DEBUG   ] Looking for auth config
[DEBUG   ] No auth config in memory - loading from filesystem
[DEBUG   ] Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
[DEBUG   ] No config file found
[DEBUG   ] Looking for auth entry for 'docker.io'
[DEBUG   ] No entry found
[DEBUG   ] No auth config found
[DEBUG   ] http://localhost:None "POST /v1.35/images/create?tag=latest&fromImage=redis HTTP/1.1" 200 None
[DEBUG   ] Attempting to run docker-py's "inspect_image" function with args=('redis:latest',) and kwargs={}
[DEBUG   ] http://localhost:None "GET /v1.35/images/redis:latest/json HTTP/1.1" 200 None
[DEBUG   ] Attempting to run docker-py's "images" function with args=() and kwargs={'all': False}
[DEBUG   ] http://localhost:None "GET /v1.35/images/json?only_ids=0&all=0 HTTP/1.1" 200 None
[INFO    ] {'Layers': {'Pulled': [u'58638acf67c5', u'f98d108cc38b', u'f171693d37f9', u'c48076ff6ff3', u'a9cde9c78d52', u'c4bb02b17bb4']}, 'Status': u'Downloaded newer image for redis:latest', 'Time_Elapsed': 13.05718207359314}
[INFO    ] Completed state [redis:latest] at time 18:43:38.365360 duration_in_ms=13096.186
[DEBUG   ] File /var/cache/salt/minion/accumulator/43586704 does not exist, no need to cleanup.
[DEBUG   ] LazyLoaded config.option
[DEBUG   ] LazyLoaded highstate.output
[DEBUG   ] LazyLoaded nested.output
local:
----------
          ID: redis:latest
    Function: docker_image.present
      Result: True
     Comment: Image 'redis:latest' was pulled
     Started: 18:43:25.269174
    Duration: 13096.186 ms
     Changes:
              ----------
              Layers:
                  ----------
                  Pulled:
                      - 58638acf67c5
                      - f98d108cc38b
                      - f171693d37f9
                      - c48076ff6ff3
                      - a9cde9c78d52
                      - c4bb02b17bb4
              Status:
                  Downloaded newer image for redis:latest
              Time_Elapsed:
                  13.0571820736

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  13.096 s
```

What is the `root` docker hub?

Thanks,
Daniel

**Comment by ChaosOrd** [comment]
It looks like another interferes with "docker_image.present". When I apply this state separately, everything seems working. But when I run the state.highstate command which applies lots of other states, then the error occurs. I will try to find the exact state causing the problem.

**Comment by gtmanfred** [comment]
Perfect, thanks

**Comment by terminalmage** [comment]
@ChaosOrd This seems like an upstream bug. The reason I say this is that docker-py is supposed to raise its own exceptions when an API call encounters an error. The line in Salt that is raising the traceback you're seeing only happens when an exception other than one of docker-py's is raised.

That's a relatively old version of docker-py, so this could be an upstream bug that has since been fixed. The legacy docker-py stopped sometime in the 1.10 release cycle, and docker-py was heavily overhauled for 2.x. You may want to try uninstalling the legacy docker-py and installing a new release. Just FYI though if you're installing using pip, the legacy module is called `docker-py` in PyPI while the actively-developed module is simply called `docker`.

**Comment by ChaosOrd** [comment]
Thanks @terminalmage!
Upgrading docker python pacage to version 3.0.1 solved the issue.

**Comment by terminalmage** [comment]
Excellent! Thanks for confirming.
