### ISSUE TITLE
Unable to use mako for file.managed template due to urlparse import with Python 3

### ISSUE THREAD

**Issue by hedrickbt** [saltstack/salt#45876]
### Description of Issue/Question
Using the mako template engine on a Windows salt minion with file.managed fails.  I have tested with both Salt-Minion-2017.7.1-Py3-AMD64-Setup.exe and Salt-Minion-2017.7.3-Py3-AMD64-Setup.exe on Windows 2016 64bit.

Error:
machine.fqdn.com:
----------
          ID: instana-win-conf
    Function: file.managed
        Name: c:\Program Files (x86)\Instana\instana-agent\etc\instana\configuration_bth.yaml
      Result: False
     Comment: Traceback (most recent call last):
                File "c:\salt\bin\lib\site-packages\salt\utils\templates.py", line 167, in render_tmpl
                  output = render_str(tmplstr, context, tmplpath)
                File "c:\salt\bin\lib\site-packages\salt\utils\templates.py", line 479, in render_mako_tmpl
                  from salt.utils.mako import SaltMakoTemplateLookup
                File "c:\salt\bin\lib\site-packages\salt\utils\mako.py", line 6, in <module>
                  import urlparse
              ImportError: No module named 'urlparse'
     Started: 07:41:40.168877
    Duration: 78.133 ms
     Changes:   

### Setup
SLS:
instana-win-conf:
  file.managed:
    - name: "c:\\Program Files (x86)\\Instana\\instana-agent\\etc\\instana\\configuration_bth.yaml"
    - source: salt://instana/configuration_win_bth.yaml
    - template: mako

configuration_win_bth.yaml:
{<%
temp_zone = 'unknown'
if grains['host'].startswith('dev'):
  temp_zone = 'dev'
  temp_tag = 'dev'
else if grains['host'].startswith('qa'):
  temp_zone = 'qa'
  temp_tag = 'qa'
else if grains['host'].startswith('demo'):
  temp_zone = 'demo'
  temp_tag = 'demo'
else if grains['host'].startswith('rhcentral'):
  temp_zone = 'rhcentral'
  temp_tag = 'rhcentral'
else if grains['host'].startswith('biz'):
  temp_zone = 'biz'
  temp_tag = 'biz'
%>}

com.instana.plugin.generic.hardware:
  enabled: true
  availability-zone: '{temp_zone}'

com.instana.plugin.host:
  tags:
    - '{temp_tag}'

Line 6 is the import of urlparse from: \\machine\c$\salt\bin\Lib\site-packages\salt\utils\mako.py .  It appears that the import may not be necessary or needs to change to urllib.parse ( ex: https://github.com/FriendCode/gittle/issues/49 )

# -*- coding: utf-8 -*-
from __future__ import absolute_import

# Import python libs
import os
import urlparse

# Import third party libs
# pylint: disable=import-error,no-name-in-module
from salt.ext.six.moves.urllib.parse import urlparse
# pylint: enable=import-error,no-name-in-module
from mako.lookup import TemplateCollection, TemplateLookup  # pylint: disable=import-error,3rd-party-module-not-gated
....

### Steps to Reproduce Issue
sudo salt 'machine' state.sls instana.update-zone-and-tags

### Versions Report
From Master:
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: 1.11.2
       cherrypy: unknown
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 20 2017, 18:23:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-98-generic
         system: Linux
        version: Ubuntu 16.04 xenial

From the minion
Salt Version:
           Salt: 2017.7.3

Dependency Versions:
           cffi: 1.10.0
       cherrypy: unknown
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.0
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2016Server
         system: Windows
        version: 2016Server 10.0.14393 SP0 Multiprocessor Free

**Comment by garethgreenaway** [comment]
@hedrickbt Thanks for the report.  Looks like the mako template needs to be updated to include support for Python3.  We would welcome a PR to include this.

**Comment by hedrickbt** [comment]
Hi,
I was just notified this issue has become stale.

What do I need to do to provide a PR?  Does this mean I fork the code via github into my own account, make changes, and then create a Pull Request?

**Comment by dwoz** [comment]
Fixed in d9b50659b2b (2021-04-01, Pyupgrade and drop six); present on 3006.x/3007.x/3008.x/master. salt/utils/mako.py now uses urllib.parse; import succeeds under Python 3.
