### ISSUE TITLE
"TypeError: can't serialize <NodeImage" when calling salt-cloud with the dimensiondata driver

### ISSUE THREAD

**Issue by tintoy** [saltstack/salt#45884]
### Description of Issue/Question

Hi.

When running `salt-cloud -p ubuntu_dimensiondata test3`, I see the following error:

```
[ERROR   ] There was a profile error: can't serialize <NodeImage: id=42816eb2-9846-4483-95c3-7d7fbddebf2c, name=Ubuntu 14.04 2 CPU, driver=DimensionData  ...>
Traceback (most recent call last):
  File "/usr/local/src/saltstack/salt/salt/cloud/cli.py", line 281, in run
    self.config.get('names')
  File "/usr/local/src/saltstack/salt/salt/cloud/__init__.py", line 1454, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/local/src/saltstack/salt/salt/cloud/__init__.py", line 1284, in create
    output = self.clouds[func](vm_)
  File "/usr/local/src/saltstack/salt/salt/cloud/clouds/dimensiondata.py", line 267, in create
    transport=__opts__['transport']
  File "/usr/local/src/saltstack/salt/salt/utils/cloud.py", line 1786, in fire_event
    event.fire_event(args, tag)
  File "/usr/local/src/saltstack/salt/salt/utils/event.py", line 718, in fire_event
    dump_data = self.serial.dumps(data)
  File "/usr/local/src/saltstack/salt/salt/payload.py", line 190, in dumps
    return msgpack.dumps(msg, use_bin_type=use_bin_type)
  File "/usr/local/lib/python2.7/dist-packages/msgpack/__init__.py", line 47, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 290, in msgpack._packer.Packer.pack
  File "msgpack/_packer.pyx", line 296, in msgpack._packer.Packer.pack
  File "msgpack/_packer.pyx", line 293, in msgpack._packer.Packer.pack
  File "msgpack/_packer.pyx", line 240, in msgpack._packer.Packer._pack
  File "msgpack/_packer.pyx", line 287, in msgpack._packer.Packer._pack
TypeError: can't serialize <NodeImage: id=42816eb2-9846-4483-95c3-7d7fbddebf2c, name=Ubuntu 14.04 2 CPU, driver=DimensionData  ...>
```

I'm sure I've seen this work before, but it fails reliably now (even, as mentioned, on a clean machine).

Let me know if missed anything :)

Thanks,

Adam.

### Setup

The full log:

```
[DEBUG   ] Missing configuration file: /etc/salt/cloud
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt-test-01.localdomain
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers
[DEBUG   ] Missing configuration file: /etc/salt/cloud.profiles
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/cloud.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/cloud.conf
[TRACE   ] Error loading log_handlers.pytest_log_handler: 'pytest_log_port' not in options
[TRACE   ] The required configuration section, 'fluent_handler', was not found the in the configuration. Not loading the fluent logging handlers module.
[TRACE   ] None of the required configuration sections, 'logstash_udp_handler' and 'logstash_zmq_handler', were found in the configuration. Not loading the Logstash logging handlers module.
[DEBUG   ] Configuration file path: /etc/salt/master
[TRACE   ] Trying generic group list for 'root'
[TRACE   ] Group list for user 'root': []
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] salt-cloud starting
[TRACE   ] 'parallels.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt-test-01.localdomain
[DEBUG   ] Marking 'base64_encode' as a jinja filter
[DEBUG   ] Marking 'base64_decode' as a jinja filter
[DEBUG   ] Marking 'md5' as a jinja filter
[DEBUG   ] Marking 'sha256' as a jinja filter
[DEBUG   ] Marking 'sha512' as a jinja filter
[DEBUG   ] Marking 'hmac' as a jinja filter
[DEBUG   ] Marking 'random_hash' as a jinja filter
[DEBUG   ] Marking 'rand_str' as a jinja filter
[DEBUG   ] Marking 'file_hashsum' as a jinja filter
[DEBUG   ] Marking 'http_query' as a jinja filter
[TRACE   ] Error loading clouds.libvirt: Unable to locate or import python libvirt library.
[DEBUG   ] Marking 'yaml_dquote' as a jinja filter
[DEBUG   ] Marking 'yaml_squote' as a jinja filter
[DEBUG   ] Marking 'yaml_encode' as a jinja filter
[DEBUG   ] Marking 'raise' as a jinja global
[DEBUG   ] Marking 'match' as a jinja test
[DEBUG   ] Marking 'equalto' as a jinja test
[DEBUG   ] Marking 'skip' as a jinja filter
[DEBUG   ] Marking 'sequence' as a jinja filter
[DEBUG   ] Marking 'to_bool' as a jinja filter
[DEBUG   ] Marking 'quote' as a jinja filter
[DEBUG   ] Marking 'regex_escape' as a jinja filter
[DEBUG   ] Marking 'regex_search' as a jinja filter
[DEBUG   ] Marking 'regex_match' as a jinja filter
[DEBUG   ] Marking 'regex_replace' as a jinja filter
[DEBUG   ] Marking 'uuid' as a jinja filter
[DEBUG   ] Marking 'unique' as a jinja filter
[DEBUG   ] Marking 'min' as a jinja filter
[DEBUG   ] Marking 'max' as a jinja filter
[DEBUG   ] Marking 'avg' as a jinja filter
[DEBUG   ] Marking 'union' as a jinja filter
[DEBUG   ] Marking 'intersect' as a jinja filter
[DEBUG   ] Marking 'difference' as a jinja filter
[DEBUG   ] Marking 'symmetric_difference' as a jinja filter
[TRACE   ] loaded json json lib
[TRACE   ] Error loading clouds.virtualbox: The virtualbox driver cannot be loaded: 'vboxapi' is not installed.
[DEBUG   ] Could not LazyLoad parallels.avail_sizes: 'parallels' __virtual__ returned False
[TRACE   ] 'parallels.avail_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] LazyLoaded parallels.avail_locations
[TRACE   ] 'proxmox.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad dimensiondata.optimize_providers: 'dimensiondata.optimize_providers' is not available.
[DEBUG   ] The 'dimensiondata' cloud driver is unable to be optimized.
[DEBUG   ] Could not LazyLoad dimensiondata.list_nodes_min: 'dimensiondata.list_nodes_min' is not available.
[TRACE   ] 'parallels.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt-test-01.localdomain
[TRACE   ] Error loading clouds.libvirt: Unable to locate or import python libvirt library.
[TRACE   ] Error loading clouds.virtualbox: The virtualbox driver cannot be loaded: 'vboxapi' is not installed.
[DEBUG   ] Could not LazyLoad parallels.avail_sizes: 'parallels' __virtual__ returned False
[TRACE   ] 'parallels.avail_locations' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] LazyLoaded parallels.avail_locations
[TRACE   ] 'proxmox.avail_sizes' has been marked as not supported. Removing from the list of supported cloud functions
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] DimensionData authenticating using password
[DEBUG   ] Starting new HTTPS connection (1): api-au.dimensiondata.com
[DEBUG   ] https://api-au.dimensiondata.com:443 "GET /oec/0.9/myaccount HTTP/1.1" 200 None
[DEBUG   ] Resetting dropped connection: api-au.dimensiondata.com
[DEBUG   ] https://api-au.dimensiondata.com:443 "GET /caas/2.4/dd59cc83-efaa-4316-a410-e6534e2868d6/server/server HTTP/1.1" 200 None
[WARNING ] There's no master defined on the 'test3' VM settings.
[DEBUG   ] Generating minion keys for 'test3'
[DEBUG   ] LazyLoaded cloud.fire_event
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
[TRACE   ] IPCClient: Connecting to socket: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event: tag = salt/cloud/test3/creating; data = {u'profile': 'ubuntu_dimensiondata', u'_stamp': '2018-02-06T19:12:37.804225', u'name': u'test3', u'driver': 'dimensiondata', u'provider': u'ddcloud:dimensiondata', u'event': u'starting create'}
[INFO    ] Creating Cloud VM test3
[DEBUG   ] DimensionData authenticating using password
[DEBUG   ] Starting new HTTPS connection (1): api-au.dimensiondata.com
[DEBUG   ] https://api-au.dimensiondata.com:443 "GET /oec/0.9/myaccount HTTP/1.1" 200 None
[DEBUG   ] Resetting dropped connection: api-au.dimensiondata.com
[DEBUG   ] https://api-au.dimensiondata.com:443 "GET /caas/2.4/dd59cc83-efaa-4316-a410-e6534e2868d6/infrastructure/datacenter?id=AU10 HTTP/1.1" 200 2882
[DEBUG   ] Resetting dropped connection: api-au.dimensiondata.com
[DEBUG   ] https://api-au.dimensiondata.com:443 "GET /caas/2.4/dd59cc83-efaa-4316-a410-e6534e2868d6/image/osImage?datacenterId=AU10 HTTP/1.1" 200 None
[DEBUG   ] Resetting dropped connection: api-au.dimensiondata.com
[DEBUG   ] https://api-au.dimensiondata.com:443 "GET /caas/2.4/dd59cc83-efaa-4316-a410-e6534e2868d6/infrastructure/datacenter HTTP/1.1" 200 None
[DEBUG   ] Resetting dropped connection: api-au.dimensiondata.com
[DEBUG   ] https://api-au.dimensiondata.com:443 "GET /caas/2.4/dd59cc83-efaa-4316-a410-e6534e2868d6/network/networkDomain?datacenterId=AU10 HTTP/1.1" 200 1696
[DEBUG   ] Resetting dropped connection: api-au.dimensiondata.com
[DEBUG   ] https://api-au.dimensiondata.com:443 "GET /caas/2.4/dd59cc83-efaa-4316-a410-e6534e2868d6/infrastructure/datacenter HTTP/1.1" 200 None
[DEBUG   ] Resetting dropped connection: api-au.dimensiondata.com
[DEBUG   ] https://api-au.dimensiondata.com:443 "GET /caas/2.4/dd59cc83-efaa-4316-a410-e6534e2868d6/network/vlan?datacenterId=AU10&networkDomainId=53b1c4d9-15a3-492a-b6d2-7dfd8d5c188a HTTP/1.1" 200 750
[DEBUG   ] Resetting dropped connection: api-au.dimensiondata.com
[DEBUG   ] https://api-au.dimensiondata.com:443 "GET /caas/2.4/dd59cc83-efaa-4316-a410-e6534e2868d6/infrastructure/datacenter HTTP/1.1" 200 None
[DEBUG   ] Resetting dropped connection: api-au.dimensiondata.com
[DEBUG   ] https://api-au.dimensiondata.com:443 "GET /caas/2.4/dd59cc83-efaa-4316-a410-e6534e2868d6/infrastructure/datacenter HTTP/1.1" 200 None
[DEBUG   ] Resetting dropped connection: api-au.dimensiondata.com
[DEBUG   ] https://api-au.dimensiondata.com:443 "GET /caas/2.4/dd59cc83-efaa-4316-a410-e6534e2868d6/network/networkDomain/53b1c4d9-15a3-492a-b6d2-7dfd8d5c188a HTTP/1.1" 200 455
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
[TRACE   ] IPCClient: Connecting to socket: /var/run/salt/master/master_event_pull.ipc
[ERROR   ] There was a profile error: can't serialize <NodeImage: id=42816eb2-9846-4483-95c3-7d7fbddebf2c, name=Ubuntu 14.04 2 CPU, driver=DimensionData  ...>
Traceback (most recent call last):
  File "/usr/local/src/saltstack/salt/salt/cloud/cli.py", line 281, in run
    self.config.get('names')
  File "/usr/local/src/saltstack/salt/salt/cloud/__init__.py", line 1454, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/local/src/saltstack/salt/salt/cloud/__init__.py", line 1284, in create
    output = self.clouds[func](vm_)
  File "/usr/local/src/saltstack/salt/salt/cloud/clouds/dimensiondata.py", line 267, in create
    transport=__opts__['transport']
  File "/usr/local/src/saltstack/salt/salt/utils/cloud.py", line 1786, in fire_event
    event.fire_event(args, tag)
  File "/usr/local/src/saltstack/salt/salt/utils/event.py", line 718, in fire_event
    dump_data = self.serial.dumps(data)
  File "/usr/local/src/saltstack/salt/salt/payload.py", line 190, in dumps
    return msgpack.dumps(msg, use_bin_type=use_bin_type)
  File "/usr/local/lib/python2.7/dist-packages/msgpack/__init__.py", line 47, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 290, in msgpack._packer.Packer.pack
  File "msgpack/_packer.pyx", line 296, in msgpack._packer.Packer.pack
  File "msgpack/_packer.pyx", line 293, in msgpack._packer.Packer.pack
  File "msgpack/_packer.pyx", line 240, in msgpack._packer.Packer._pack
  File "msgpack/_packer.pyx", line 287, in msgpack._packer.Packer._pack
TypeError: can't serialize <NodeImage: id=42816eb2-9846-4483-95c3-7d7fbddebf2c, name=Ubuntu 14.04 2 CPU, driver=DimensionData  ...>
```

### Steps to Reproduce Issue

The error was originally reported to me for the current release of Salt, but I also tried building it from source with the same result.

I built a fresh Ubuntu 14.04 machine from scratch to run this on, prepared using the following setup script:

```bash
# Prerequisites
apt-get update
apt-get remove -y apache2
apt-get upgrade -y
apt-get install -y git build-essential python-dev python-pip libssl-dev python-m2crypto
pip install --upgrade pip setuptools
apt-get autoremove -y
 
# Source and dependencies
mkdir -p /usr/local/src/saltstack/salt
cd /usr/local/src/saltstack/salt
git clone https://github.com/saltstack/salt.git .
git fetch --tags
git checkout develop
pip install -r requirements/dev_python27.txt
pip install --upgrade libcloud requests urllib3
pip install -e .
```

`/etc/salt/cloud.providers`:
```
ddcloud:
  user_id: my_user
  key: "my_password"
  region: dd-au
  driver: dimensiondata
```

`/etc/salt/cloud.profiles.d/ubuntu_dimensiondata.conf`:
```
ubuntu_dimensiondata:
  provider: ddcloud
  image: 42816eb2-9846-4483-95c3-7d7fbddebf2c
  size: default
  location: AU10
  is_started: yes
  description: Ubuntu
  network_domain: daas-demo
  vlan:  daas-kube
  auth: "Snau$ag3s!"
```

### Versions Report

```
Salt Version:
            Salt: 2018.2.0-117-g2aa4b1c

Dependency Versions:
 Apache Libcloud: 2.2.1
            cffi: 1.11.4
        cherrypy: Not Installed
        dateutil: 2.6.1
       docker-py: 3.0.1
           gitdb: Not Installed
       gitpython: Not Installed
           ioflo: Not Installed
          Jinja2: 2.10
         libgit2: Not Installed
         libnacl: Not Installed
        M2Crypto: 0.21.1
            Mako: Not Installed
    msgpack-pure: Not Installed
  msgpack-python: 0.5.2
    mysql-python: Not Installed
       pycparser: 2.18
        pycrypto: 2.6.1
    pycryptodome: Not Installed
          pygit2: Not Installed
          Python: 2.7.6 (default, Nov 23 2017, 15:49:48)
    python-gnupg: Not Installed
          PyYAML: 3.10
           PyZMQ: 16.0.4
            RAET: Not Installed
           smmap: Not Installed
         timelib: Not Installed
         Tornado: 4.5.3
             ZMQ: 4.1.6

System Versions:
            dist: Ubuntu 14.04 trusty
          locale: UTF-8
         machine: x86_64
         release: 3.13.0-141-generic
          system: Linux
         version: Ubuntu 14.04 trusty
```

**Comment by tintoy** [comment]
BTW, the error occurs even if I don't `pip install --upgrade` to get the latest `libcloud` and dependencies.

**Comment by tintoy** [comment]
Looking at the code for other drivers, it looks to me like perhaps the problem is that the `dimensiondata` driver is passing an object (e.g. `NodeImage`) to `fire_event`?

https://github.com/saltstack/salt/blob/develop/salt/cloud/clouds/dimensiondata.py#L248-L268

I see that (for example) the `digitalocean` driver passes only primitive types to `fire_event`:

https://github.com/saltstack/salt/blob/develop/salt/cloud/clouds/digitalocean.py#L297-L304
https://github.com/saltstack/salt/blob/develop/salt/cloud/clouds/digitalocean.py#L205-L225

**Comment by tintoy** [comment]
I came up with the following code which works (although packing the objects directly does not):

```python
from libcloud.common.dimensiondata import DimensionDataNetworkDomain
from libcloud.compute.base import NodeImage
from libcloud.compute.drivers.dummy import DummyNodeDriver

from msgpack import Packer

def _to_event_data(obj):
    """
    Convert the specified object into a form that can be serialised by msgpack as event data.

    :param obj: The object to convert.
    """

    if obj is None:
        return None
    if isinstance(obj, bool):
        return obj
    if isinstance(obj, int):
        return obj
    if isinstance(obj, float):
        return obj
    if isinstance(obj, str):
        return obj
    if isinstance(obj, bytes):
        return obj
    if isinstance(obj, dict):
        return obj

    if isinstance(obj, NodeDriver): # Special case for NodeDriver (cyclic references)
        return obj.name

    if isinstance(obj, list):
        return [_to_event_data(item) for item in obj]

    event_data = {}
    for attribute_name in dir(obj):
        if attribute_name.startswith("_"):
            continue

        attribute_value = getattr(obj, attribute_name)

        if callable(attribute_value): # Strip out methods
            continue

        event_data[attribute_name] = _to_event_data(attribute_value)

    return event_data


packer = Packer()

driver = DummyNodeDriver(0)
image = NodeImage(id='1234', name='foo', driver=driver, extra={'foo': 'bar', 'baz': 123})
print(
    repr(image)
)
image_packable = _to_event_data(image)
image_packed = packer.pack(image_packable)
print(
    repr(image_packed)
)
```

**Comment by tintoy** [comment]
I _think_ this would fix the problem:

https://github.com/saltstack/salt/compare/develop...DimensionDataResearch:fix/issue/45884

Should I open a PR?

**Comment by gtmanfred** [comment]
I would love to see that opened as a PR, and then we can discuss it over there.

Thanks!
Daniel

**Comment by gtmanfred** [comment]
it looks like the same problem may exist against 2017.7, could you open the PR against that, and we will merge the fix forward to the other branches?

https://docs.saltstack.com/en/latest/topics/development/contributing.html#merge-forward-process

Thanks,
Daniel

**Comment by tintoy** [comment]
@gtmanfred - ok, done :)

**Comment by tintoy** [comment]
Remaining failing test seems to be unrelated to my changes:

https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu16-py3/6659/testReport/junit/integration.spm.test_man_spm/SPMManTest/test_man_spm/
