### ISSUE TITLE
Running salt-cloud via salt.runner function generates two minion keys, 1 accepted, 1 denied.

### ISSUE THREAD

**Issue by FireDrunk** [saltstack/salt#45916]
### Description of Issue/Question
When using a salt.runner -> salt.profile, it creates two keys, 1 is accepted, 1 is denied.

### Setup
SLS:
```
# Automatically spinup all instances in:
# pillar: virtual_machines

{% for machine, config in pillar.get('virtual_machines', {}).items() %}

{{ machine }}:
  salt.runner:
    - name: cloud.profile
    - prof: proxmox-centos-lxc
    - cloud_provider: proxmox-thuis
    - instances:
      - {{ machine }}
    - vm_overrides:
{#        script: bootstrap-salt 
        script_args: "-H {{ pillar.get('proxy', 'no_proxy_defined_in_pillar')  }}" #}
        host: {{ config.host }}
        technology: {{ config.technology }}
        image: {{ config.image }}
        hostname: {{ config.hostname }}
        password: {{ config.password }}
        pool: {{ config.pool }}
        rootfs: {{ config.rootfs }}
        cores: {{ config.cores }}
        memory: {{ config.memory }}
        swap: {{ config.swap }}
        net0: "bridge={{ config.bridge }},name=eth0,ip={{ config.ip_address}}/{{ config.netmask }},gw={{ config.gateway }},tag={{ config.vlan }}"
        ip_address: {{ config.ip_address }}
        searchdomain: {{ config.searchdomain }}
        nameserver: {{ config.nameserver }}
{% endfor %}
```
Pillar:
```
virtual_machines:
  devops-web-001.infra.prov.io:
    profile: proxmox
    technology: lxc
    image: nvme-data:vztmpl/centos-7-ssh-salt-20180208.tar.gz
    host: devops-pve-001
    hostname: devops-web-001.infra.prov.io
    password: password
    pool: infra
    rootfs: ceph-rbd:20
    cores: 2
    memory: 4096
    swap: 512
    bridge: vmbr0
    ip_address: 10.0.24.100
    netmask: 24
    gateway: 10.0.24.1
    vlan: 24
    searchdomain: infra.prov.io
    nameserver: 10.0.24.1
```
### Steps to Reproduce Issue
I'm starting with an salt-key which does not have any key for the machine.

I've pre-installed salt-minion inside the template that is being used by running salt-bootstrap.sh -x.
Command on master: salt-call state.sls orchestration
```
[WARNING ] /usr/lib/python2.7/site-packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)

[WARNING ] /usr/lib/python2.7/site-packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)

Warning: Permanently added '10.0.24.100' (ECDSA) to the list of known hosts.
root@10.0.24.100's password: 
do feb  8 10:19:33 UTC 2018
Warning: Permanently added '10.0.24.100' (ECDSA) to the list of known hosts.
root@10.0.24.100's password: Connection to 10.0.24.100 closed.

Warning: Permanently added '10.0.24.100' (ECDSA) to the list of known hosts.
root@10.0.24.100's password: Connection to 10.0.24.100 closed.

Warning: Permanently added '10.0.24.100' (ECDSA) to the list of known hosts.
root@10.0.24.100's password: Connected to 10.0.24.100.

sftp> put  /tmp/tmpBenFaG /tmp/.saltcloud-c03f1ee3-ddd4-48a1-8521-a6459c5a1dd9/minion.pem
Uploading /tmp/tmpBenFaG to /tmp/.saltcloud-c03f1ee3-ddd4-48a1-8521-a6459c5a1dd9/minion.pem
/tmp/tmpBenFaG                                                        100% 3242    13.6MB/s   00:00    
Warning: Permanently added '10.0.24.100' (ECDSA) to the list of known hosts.
root@10.0.24.100's password: Connection to 10.0.24.100 closed.

Warning: Permanently added '10.0.24.100' (ECDSA) to the list of known hosts.
root@10.0.24.100's password: Connected to 10.0.24.100.

sftp> put  /tmp/tmpaAlsPY /tmp/.saltcloud-c03f1ee3-ddd4-48a1-8521-a6459c5a1dd9/minion.pub
Uploading /tmp/tmpaAlsPY to /tmp/.saltcloud-c03f1ee3-ddd4-48a1-8521-a6459c5a1dd9/minion.pub
/tmp/tmpaAlsPY                                                        100%  799     4.2MB/s   00:00    
Warning: Permanently added '10.0.24.100' (ECDSA) to the list of known hosts.
root@10.0.24.100's password: Connected to 10.0.24.100.

sftp> put  /tmp/tmpI9sX44 /tmp/.saltcloud-c03f1ee3-ddd4-48a1-8521-a6459c5a1dd9/minion
Uploading /tmp/tmpI9sX44 to /tmp/.saltcloud-c03f1ee3-ddd4-48a1-8521-a6459c5a1dd9/minion
/tmp/tmpI9sX44                                                        100%  111   631.3KB/s   00:00    
Warning: Permanently added '10.0.24.100' (ECDSA) to the list of known hosts.
root@10.0.24.100's password: Connected to 10.0.24.100.

sftp> put  /tmp/tmpHlM6UV /tmp/.saltcloud-c03f1ee3-ddd4-48a1-8521-a6459c5a1dd9/deploy.sh
Uploading /tmp/tmpHlM6UV to /tmp/.saltcloud-c03f1ee3-ddd4-48a1-8521-a6459c5a1dd9/deploy.sh
/tmp/tmpHlM6UV                                                        100%  244KB 100.6MB/s   00:00    
Warning: Permanently added '10.0.24.100' (ECDSA) to the list of known hosts.
root@10.0.24.100's password: Connection to 10.0.24.100 closed.

Warning: Permanently added '10.0.24.100' (ECDSA) to the list of known hosts.
root@10.0.24.100's password: 
 *  INFO: Running version: 2017.12.13
 *  INFO: Executed by: 
 *  INFO: Command line: '/tmp/.saltcloud-c03f1ee3-ddd4-48a1-8521-a6459c5a1dd9/deploy.sh -c /tmp/.saltcloud-c03f1ee3-ddd4-48a1-8521-a6459c5a1dd9'

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   4.13.13-5-pve
 *  INFO:   Distribution: CentOS 7.4

 *  INFO: Installing minion
 *  INFO: Found function install_centos_stable_deps
 *  INFO: Found function config_salt
 *  INFO: Found function preseed_master
 *  INFO: Found function install_centos_stable
 *  INFO: Found function install_centos_stable_post
 *  INFO: Found function install_centos_restart_daemons
 *  INFO: Found function daemons_running
 *  INFO: Found function install_centos_check_services
 *  INFO: Running install_centos_stable_deps()
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.mirror.triple-it.nl
 * epel: epel.besthosting.ua
 * extras: centos.mirror.transip.nl
 * updates: centos.mirror.triple-it.nl
Package yum-utils-1.1.31-42.el7.noarch already installed and latest version
Package chkconfig-1.7.4-1.el7.x86_64 already installed and latest version
Package PyYAML-3.11-1.el7.x86_64 already installed and latest version
Nothing to do
 *  INFO: Running config_salt()
 *  INFO: Running install_centos_stable()
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.mirror.triple-it.nl
 * epel: epel.besthosting.ua
 * extras: centos.mirror.transip.nl
 * updates: centos.mirror.triple-it.nl
Package salt-minion-2017.7.3-1.el7.noarch already installed and latest version
Nothing to do
 *  INFO: Running install_centos_stable_post()
 *  INFO: Running install_centos_check_services()
 *  INFO: Running install_centos_restart_daemons()
 *  INFO: Running daemons_running()
Connection to 10.0.24.100 closed.
 * ERROR: salt-minion was not found running
 * ERROR: Failed to run daemons_running()!!!
 * ERROR: salt-minion was not found running. Pass '-D' to bootstrap-salt.sh when bootstrapping for additional debugging information...
[ERROR   ] Exception occurred in runner cloud.profile: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 382, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/runners/cloud.py", line 117, in profile
    info = client.profile(prof, instances, **_filter_kwargs(kwargs))
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 348, in profile
    mapper.run_profile(profile, names, vm_overrides=vm_overrides)
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1452, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1278, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/proxmox.py", line 602, in create
    ret = __utils__['cloud.bootstrap'](vm_, __opts__)
  File "/usr/lib/python2.7/site-packages/salt/utils/cloud.py", line 548, in bootstrap
    deployed = deploy_script(**deploy_kwargs)
  File "/usr/lib/python2.7/site-packages/salt/utils/cloud.py", line 1547, in deploy_script
    if root_cmd(deploy_command, tty, sudo, **ssh_kwargs) != 0:
  File "/usr/lib/python2.7/site-packages/salt/utils/cloud.py", line 2282, in root_cmd
    retcode = _exec_ssh_cmd(cmd, allow_failure=allow_failure, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/utils/cloud.py", line 1860, in _exec_ssh_cmd
    cmd, proc.exitstatus
SaltCloudSystemExit: Command 'ssh -t -t -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -p 22 root@10.0.24.100 '/tmp/.saltcloud-c03f1ee3-ddd4-48a1-8521-a6459c5a1dd9/deploy.sh -c '"'"'/tmp/.saltcloud-c03f1ee3-ddd4-48a1-8521-a6459c5a1dd9'"'"''' failed. Exit code: 1

local:
----------
          ID: devops-web-001.infra.prov.io
    Function: salt.runner
        Name: cloud.profile
      Result: False
     Comment: Exception occurred in runner cloud.profile: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 382, in _low
                  data['return'] = self.functions[fun](*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/runners/cloud.py", line 117, in profile
                  info = client.profile(prof, instances, **_filter_kwargs(kwargs))
                File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 348, in profile
                  mapper.run_profile(profile, names, vm_overrides=vm_overrides)
                File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1452, in run_profile
                  ret[name] = self.create(vm_)
                File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1278, in create
                  output = self.clouds[func](vm_)
                File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/proxmox.py", line 602, in create
                  ret = __utils__['cloud.bootstrap'](vm_, __opts__)
                File "/usr/lib/python2.7/site-packages/salt/utils/cloud.py", line 548, in bootstrap
                  deployed = deploy_script(**deploy_kwargs)
                File "/usr/lib/python2.7/site-packages/salt/utils/cloud.py", line 1547, in deploy_script
                  if root_cmd(deploy_command, tty, sudo, **ssh_kwargs) != 0:
                File "/usr/lib/python2.7/site-packages/salt/utils/cloud.py", line 2282, in root_cmd
                  retcode = _exec_ssh_cmd(cmd, allow_failure=allow_failure, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/utils/cloud.py", line 1860, in _exec_ssh_cmd
                  cmd, proc.exitstatus
              SaltCloudSystemExit: Command 'ssh -t -t -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -p 22 root@10.0.24.100 '/tmp/.saltcloud-c03f1ee3-ddd4-48a1-8521-a6459c5a1dd9/deploy.sh -c '"'"'/tmp/.saltcloud-c03f1ee3-ddd4-48a1-8521-a6459c5a1dd9'"'"''' failed. Exit code: 1
     Started: 11:19:05.340450
    Duration: 66553.304 ms
     Changes:   

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:  66.553 s
```
The minion fails to start, because it sees that it's key is rejected by the master.

After the run I have the following salt-key:
```
[root@devops-saltmaster-001 minions]# salt-key
Accepted Keys:
devops-ccs-001.infra.prov.io
devops-git-001.infra.prov.io
devops-saltmaster-001.infra.prov.io
devops-web-001.infra.prov.io
Denied Keys:
devops-web-001.infra.prov.io
Unaccepted Keys:
Rejected Keys:
```

So somewhere in the process, it ran the minion key generation twice I think.
I've already updated using salt-cloud -u, and tried removing the script_args (hence the comments).

### Versions Report
```
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.24.6
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.2
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.17.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

**Comment by garethgreenaway** [comment]
@FireDrunk Thanks for the report.

**Comment by FireDrunk** [comment]
I've been debugging some more, and it looks like the following timeline is happening:

- Events
- Create Keys
- Proxmox Get Free VM ID
- Start Creation Job on Proxmox
- Wait for it (few iterations of get status)
- Start bootstrapping the VM (copy bootstrap script)
- New key generated & old one get's denied
- Copy keys to machine using SFTP/SCP
- Launch bootstrap script
- Fail at start salt-minion phase.

**Comment by shadoutmapes** [comment]
Any solution for this, I have this same issue still with salt cloud and windows 2022, using the latest available salt minion 3005 and the latest saltmaster in repo.  Everything deploys fine but I end up with 2 keys for the same name
