### ISSUE TITLE
[oxygen] msgpack errors in test suite

### ISSUE THREAD

**Issue by terminalmage** [saltstack/salt#45954]
The following shows on the console in some integration tests:

```
03:55:54   test_multiple_sources_master_dev_merge_lists (integration.pillar.test_git_pillar.TestGitPythonAuthenticatedHTTP)

03:55:55 03:55:54,575 [salt.payload                               :147 ][CRITICAL] Could not deserialize msgpack message. This often happens when trying to read a file not in binary mode. To see message payload, enable debug logging and retry. Exception: Unpack failed: error = 0
03:55:55 03:55:54,686 [tornado.application                        :611 ][ERROR   ] Exception in callback <functools.partial object at 0xbd5edb8>
03:55:55 Traceback (most recent call last):
03:55:55   File "/usr/lib64/python2.7/site-packages/tornado/ioloop.py", line 591, in _run_callback
03:55:55     ret = callback()
03:55:55   File "/usr/lib64/python2.7/site-packages/tornado/stack_context.py", line 274, in null_wrapper
03:55:55     return fn(*args, **kwargs)
03:55:55   File "/testing/salt/minion.py", line 3139, in _process_event
03:55:55     self.mminion.returners[fstr](data['jid'])
03:55:55   File "/testing/salt/returners/local_cache.py", line 300, in get_load
03:55:55     ret = serial.load(rfh)
03:55:55   File "/testing/salt/payload.py", line 166, in load
03:55:55     return self.loads(data)
03:55:55   File "/testing/salt/payload.py", line 137, in loads
03:55:55     ret = msgpack.loads(msg, use_list=True, encoding=encoding)
03:55:55   File "msgpack/_unpacker.pyx", line 210, in msgpack._unpacker.unpackb
03:55:55 UnpackValueError: Unpack failed: error = 0

03:56:08 [CPU:0.0%|MEM:35.7%]  ... OK (14.152s)
```

This is likely due to unicode-related changes causing the payload to no longer be bytes. Should not be hard to track down. *(EDIT: famous last words...)*

**Comment by terminalmage** [comment]
I'm unable so far to reproduce this locally. I was however able to track down the data structure which failed to unpack. It is the result of a grains.items. There doesn't appear to be anything that one would assume would cause msgpack to error out, though.

```python
{u'fun': u'grains.items',
 u'fun_args': [],
 u'jid': u'20180209134741363998',
 u'retcode': 0,
 u'return': {u'SSDs': [u'xvda'],
             'a_custom': {'k2': 'v2'},
             'adminv2': {'keystone.auth_url': 'http://127.0.0.1:5000/v2.0/',
                         'keystone.password': 'adminpass',
                         'keystone.tenant': 'admin',
                         'keystone.user': 'admin'},
             'adminv3': {'keystone.auth_url': 'http://127.0.0.1:5000/v3/',
                         'keystone.password': 'adminpass',
                         'keystone.tenant': 'admin',
                         'keystone.user': 'admin'},
             'alot': 'many',
             u'biosreleasedate': '08/24/2006\n',
             u'biosversion': '4.2.amazon\n',
             'companions': {'one': ['susan', 'ian', 'barbara']},
             u'cpu_flags': [u'fpu',
                            u'vme',
                            u'de',
                            u'pse',
                            u'tsc',
                            u'msr',
                            u'pae',
                            u'mce',
                            u'cx8',
                            u'apic',
                            u'sep',
                            u'mtrr',
                            u'pge',
                            u'mca',
                            u'cmov',
                            u'pat',
                            u'pse36',
                            u'clflush',
                            u'mmx',
                            u'fxsr',
                            u'sse',
                            u'sse2',
                            u'ht',
                            u'syscall',
                            u'nx',
                            u'rdtscp',
                            u'lm',
                            u'constant_tsc',
                            u'rep_good',
                            u'nopl',
                            u'xtopology',
                            u'eagerfpu',
                            u'pni',
                            u'pclmulqdq',
                            u'ssse3',
                            u'fma',
                            u'cx16',
                            u'pcid',
                            u'sse4_1',
                            u'sse4_2',
                            u'x2apic',
                            u'movbe',
                            u'popcnt',
                            u'tsc_deadline_timer',
                            u'aes',
                            u'xsave',
                            u'avx',
                            u'f16c',
                            u'rdrand',
                            u'hypervisor',
                            u'lahf_lm',
                            u'abm',
                            u'fsgsbase',
                            u'bmi1',
                            u'avx2',
                            u'smep',
                            u'bmi2',
                            u'erms',
                            u'invpcid',
                            u'xsaveopt'],
             u'cpu_model': u'Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz',
             u'cpuarch': 'x86_64',
             'demov2': {'keystone.auth_url': 'http://127.0.0.1:5000/v2.0/',
                        'keystone.password': 'demopass',
                        'keystone.tenant': 'demo',
                        'keystone.user': 'demo'},
             'demov3': {'keystone.auth_url': 'http://127.0.0.1:5000/v3/',
                        'keystone.password': 'demopass',
                        'keystone.tenant': 'demo',
                        'keystone.user': 'demo'},
             u'disks': [u'ram0',
                        u'ram1',
                        u'ram2',
                        u'ram3',
                        u'ram4',
                        u'ram5',
                        u'ram6',
                        u'ram7',
                        u'ram8',
                        u'ram9',
                        u'loop0',
                        u'loop1',
                        u'loop2',
                        u'loop3',
                        u'loop4',
                        u'loop5',
                        u'loop6',
                        u'loop7',
                        u'ram10',
                        u'ram11',
                        u'ram12',
                        u'ram13',
                        u'ram14',
                        u'ram15'],
             u'dns': {u'domain': u'',
                      u'ip4_nameservers': [u'10.0.0.2'],
                      u'ip6_nameservers': [],
                      u'nameservers': [u'10.0.0.2'],
                      u'options': [],
                      u'search': [u'ec2.internal'],
                      u'sortlist': []},
             u'domain': u'ec2.internal',
             u'fc_wwn': [],
             u'fqdn': 'ip-10-0-0-28.ec2.internal',
             u'fqdn_ip4': ['10.0.0.28'],
             u'fqdn_ip6': [],
             u'gid': 0,
             u'gpus': [{u'model': u'GD 5446', u'vendor': u'unknown'}],
             u'grain_path': u'/tmp/salt-tests-tmpdir/file-grain-test',
             u'groupname': 'root',
             u'host': u'ip-10-0-0-28',
             u'hwaddr_interfaces': {u'docker0': u'02:42:18:99:ad:04',
                                    u'dummy0': u'82:ee:88:cb:cf:b8',
                                    u'eth0': u'12:7a:50:3e:62:cc',
                                    u'lo': u'00:00:00:00:00:00',
                                    u'lxcbr0': u'00:16:3e:00:00:00'},
             u'id': 'minion',
             u'init': u'systemd',
             u'ip4_gw': u'10.0.0.1',
             u'ip4_interfaces': {u'docker0': [u'172.17.0.1'],
                                 u'dummy0': [],
                                 u'eth0': [u'10.0.0.28'],
                                 u'lo': [u'127.0.0.1'],
                                 u'lxcbr0': [u'10.0.1.1']},
             u'ip6_gw': False,
             u'ip6_interfaces': {u'docker0': [u'fe80::42:18ff:fe99:ad04'],
                                 u'dummy0': [],
                                 u'eth0': [u'fe80::107a:50ff:fe3e:62cc'],
                                 u'lo': [u'::1'],
                                 u'lxcbr0': []},
             u'ip_gw': True,
             u'ip_interfaces': {u'docker0': [u'172.17.0.1',
                                             u'fe80::42:18ff:fe99:ad04'],
                                u'dummy0': [],
                                u'eth0': [u'10.0.0.28',
                                          u'fe80::107a:50ff:fe3e:62cc'],
                                u'lo': [u'127.0.0.1', u'::1'],
                                u'lxcbr0': [u'10.0.1.1']},
             u'ipv4': [u'10.0.0.28',
                       u'10.0.1.1',
                       u'127.0.0.1',
                       u'172.17.0.1'],
             u'ipv6': [u'::1',
                       u'fe80::42:18ff:fe99:ad04',
                       u'fe80::107a:50ff:fe3e:62cc'],
             u'iscsi_iqn': [u'iqn.1993-08.org.debian:01:8179988a4348'],
             u'kernel': 'Linux',
             u'kernelrelease': '4.4.0-1041-aws',
             u'kernelversion': '#50-Ubuntu SMP Wed Nov 15 22:18:17 UTC 2017',
             'level1': {'level2': 'foo'},
             u'locale_info': {u'defaultencoding': 'UTF-8',
                              u'defaultlanguage': 'en_US',
                              u'detectedencoding': 'UTF-8'},
             u'localhost': 'ip-10-0-0-28',
             u'lsb_distrib_codename': 'xenial',
             u'lsb_distrib_description': 'Ubuntu 16.04.3 LTS',
             u'lsb_distrib_id': 'Ubuntu',
             u'lsb_distrib_release': '16.04',
             u'machine_id': '60749017110c481ca5557619ecda7a69',
             u'manufacturer': 'Xen\n',
             u'master': u'localhost',
             'match': 'maker',
             u'mdadm': [],
             u'mem_total': 3950,
             u'nodename': 'ip-10-0-0-28',
             u'num_cpus': 2,
             u'num_gpus': 1,
             u'os': 'Ubuntu',
             u'os_family': u'Debian',
             u'osarch': u'amd64',
             u'oscodename': 'xenial',
             u'osfinger': u'Ubuntu-16.04',
             u'osfullname': 'Ubuntu',
             u'osmajorrelease': 16,
             u'osrelease': '16.04',
             u'osrelease_info': (16, 4),
             u'path': '/testing/tests/integration/mockbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games',
             u'pid': 16656,
             'planets': ['mercury', 'venus', 'earth', 'mars'],
             u'productname': 'HVM domU\n',
             u'ps': u'ps -efHww',
             u'pythonexecutable': '/usr/bin/python',
             u'pythonpath': ['/usr/local/lib/python2.7/dist-packages/git/ext/gitdb',
                             '/testing',
                             '/tmp/salt-tests-tmpdir/scripts',
                             '/usr/lib/python2.7',
                             '/usr/lib/python2.7/plat-x86_64-linux-gnu',
                             '/usr/lib/python2.7/lib-tk',
                             '/usr/lib/python2.7/lib-old',
                             '/usr/lib/python2.7/lib-dynload',
                             '/usr/local/lib/python2.7/dist-packages',
                             '/usr/lib/python2.7/dist-packages',
                             '/usr/local/lib/python2.7/dist-packages/gitdb/ext/smmap'],
             u'pythonversion': [2, 7, 12, 'final', 0],
             u'saltpath': '/testing/salt',
             u'salttesting-grain-key': [],
             u'saltversion': u'2018.2.0-237-ge647644',
             u'saltversioninfo': [2018, 2, 0, 0],
             'script': 'grail',
             u'serialnumber': 'ec2539aa-a45b-fba1-ce21-fa4b1c5f0736\n',
             u'server_id': 266635400,
             u'setgrain': u'grainval',
             u'shell': '/bin/bash',
             u'swap_total': 2047,
             u'systemd': {u'features': u'+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN',
                          u'version': u'229'},
             'test_grain': 'cheese',
             'tokenv2': {'keystone.endpoint': 'http://localhost:35357/v2.0',
                         'keystone.token': 'administrator'},
             'tokenv3': {'keystone.endpoint': 'http://localhost:35357/v3',
                         'keystone.token': 'administrator'},
             u'uid': 0,
             u'username': 'root',
             u'uuid': 'ec2539aa-a45b-fba1-ce21-fa4b1c5f0736\n',
             u'virtual': u'xen',
             u'virtual_subtype': u'Xen PV DomU',
             u'zfs_support': False,
             u'zmqversion': '4.1.4',
             'zookeeper': {'default_acl': [{'admin': True,
                                            'create': True,
                                            'delete': True,
                                            'password': 'test',
                                            'read': True,
                                            'username': 'daniel',
                                            'write': True}],
                           'hosts': 'localhost:2181',
                           'password': 'test',
                           'prod': {'default_acl': [{'admin': True,
                                                     'create': True,
                                                     'delete': True,
                                                     'password': 'test',
                                                     'read': True,
                                                     'username': 'daniel',
                                                     'write': True}],
                                    'hosts': 'localhost:2181',
                                    'password': 'test',
                                    'username': 'daniel'},
                           'username': 'daniel'}},
 u'success': True}
```

**Comment by terminalmage** [comment]
See #45998 for a possible fix. We'll need to wait for tests to complete and then check the console log to be sure.

**Comment by rallytime** [comment]
This is confirmed to be fixed after checking the console logs. Closing! 🎉
