### ISSUE TITLE
GCE driver fails to list available images.

### ISSUE THREAD

**Issue by fake-name** [saltstack/salt#45968]
On current develop branch, with the GCE credentials configured properly.:

```
cc = salt.cloud.CloudClient('/etc/salt/cloud')
gce_images = cc.list_images(provider='gce')
print("gce_images", gce_images)
```

`gce_images` is an empty set.

Looking through the source, [`all_images.extend(conn.list_images(project))`](https://github.com/saltstack/salt/blob/develop/salt/cloud/clouds/gce.py#L355) is throwing for most of the `public_image_projects`, which is then being eaten by something between the `list_images()` call and the actual `avail_images()` function, resulting in the null return, 

```
File "/usr/local/lib/python2.7/dist-packages/libcloud/compute/drivers/gce.py", line 2269, in ex_list_project_images
    method='GET').object
  File "/usr/local/lib/python2.7/dist-packages/libcloud/compute/drivers/gce.py", line 121, in request
    response = super(GCEConnection, self).request(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/libcloud/common/google.py", line 808, in request
    *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/libcloud/common/base.py", line 637, in request
    response = responseCls(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/libcloud/common/base.py", line 159, in __init__
    self.object = self.parse_body()
  File "/usr/local/lib/python2.7/dist-packages/libcloud/common/google.py", line 280, in parse_body
    raise ResourceNotFoundError(message, self.status, code)
ResourceNotFoundError: {u'domain': u'global', u'message': u'Failed to find project g', u'reason': u'notFound'}
Missing project:  google-containers
{u'domain': u'global', u'message': u'Failed to find project o', u'reason': u'notFound'}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/salt/cloud/clouds/gce.py", line 359, in avail_images
    all_images.extend(conn.list_images(project))
  File "/usr/local/lib/python2.7/dist-packages/libcloud/compute/drivers/gce.py", line 2217, in list_images
    ex_include_deprecated=dep)
  File "/usr/local/lib/python2.7/dist-packages/libcloud/compute/drivers/gce.py", line 2269, in ex_list_project_images
    method='GET').object
  File "/usr/local/lib/python2.7/dist-packages/libcloud/compute/drivers/gce.py", line 121, in request
    response = super(GCEConnection, self).request(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/libcloud/common/google.py", line 808, in request
    *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/libcloud/common/base.py", line 637, in request
    response = responseCls(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/libcloud/common/base.py", line 159, in __init__
    self.object = self.parse_body()
  File "/usr/local/lib/python2.7/dist-packages/libcloud/common/google.py", line 280, in parse_body
    raise ResourceNotFoundError(message, self.status, code)
ResourceNotFoundError: {u'domain': u'global', u'message': u'Failed to find project o', u'reason': u'notFound'}
Missing project:  opensuse-cloud
```

etc....

Wrapping the call in the loop to `conn.list_images()` seems to at least the the GCE driver back to the point that I can actually do deploys again.

```
    for project in public_image_projects:
        try:
            all_images.extend(conn.list_images(project))
        except Exception as e:
            pass
            # print(e)
            # import traceback
            # traceback.print_exc()
            # print("Missing project: ", project)
```

**Comment by gtmanfred** [comment]
I am unable to replicate this issue.

```
[root@8df249e82529 /]# python this.py
{'get_uuid': '<bound method GCENodeImage.get_uuid of <NodeImage: id=1315952345063688141, name=centos-7-v20180129, driver=Google Compute Engine  ...>>', 'deprecate': '<bound method GCENodeImage.deprecate of <NodeImage: id=1315952345063688141, name=centos-7-v20180129, driver=Google Compute Engine  ...>>', 'uuid': 'e689fc740c1108dfa525b3cd8bb02690edeb7d22', 'extra': {'status': u'READY', 'family': u'centos-7', 'description': u'CentOS, CentOS, 7, x86_64 built on v20180129', 'rawDisk': {u'containerType': u'TAR', u'source': u''}, 'archiveSizeBytes': u'10664624640', 'diskSizeGb': u'10', 'licenses': ['<GCELicense id="centos-7" name="centos-7" charges_use_fee="True">'], 'creationTimestamp': u'2018-01-30T10:27:46.590-08:00', 'selfLink': u'https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/centos-7-v20180129', 'sourceType': u'RAW'}, 'driver': '<libcloud.compute.drivers.gce.GCENodeDriver object at 0x3adbb10>', 'delete': '<bound method GCENodeImage.delete of <NodeImage: id=1315952345063688141, name=centos-7-v20180129, driver=Google Compute Engine  ...>>', 'id': '1315952345063688141', 'name': u'centos-7-v20180129'}
[root@8df249e82529 /]# cat this.py
import salt.cloud
cc = salt.cloud.CloudClient('/etc/salt/cloud')
gce_images = cc.list_images(provider='gce-config')
for name, image in gce_images['gce-config']['gce'].items():
  if 'centos-7' in name:
    print image
```

Can you provide more information on your setup?

Thanks,
Daniel

**Comment by fake-name** [comment]
Uh, huh. I have no idea. The GCE client was working fine for multiple months, and just started failing spontaneously. As far as I know, I didn't touch anything anywhere that would have changed any settings.

**Comment by fake-name** [comment]
The only thing I can think of is it's possible the available images can be configured on a per-API-key basis.

**Comment by laundry-96** [comment]
Anyone still working on this? I am running into this issue as well...

**Comment by gtmanfred** [comment]
@saltstack/team-triage can you take a look at this?

Thanks!
Daniel

**Comment by fake-name** [comment]
I ran out of free GCE credits, so I'm not using GCE at the moment (they're too expensive for normal use). Unfortunately, that means I don't really have any ability to provide input here.
