### ISSUE TITLE
Exceptions with Slack returner

### ISSUE THREAD

**Issue by hgfischer** [saltstack/salt#45980]
### Description of Issue/Question

Keeps getting the following error logged even thou Slack returner seems to work most of the time:

```
2018-02-12 15:30:09,892 [salt.utils.lazy  :97  ][DEBUG   ][14324] LazyLoaded slack.returner
2018-02-12 15:30:09,892 [salt.minion      :1613][ERROR   ][14324] The return failed for job 20180212153009792738 'str' object has no attribute 'items'
2018-02-12 15:30:09,893 [salt.minion      :1616][ERROR   ][14324] Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1604, in _thread_return
    minion_instance.returners[returner_str](ret)
  File "/usr/lib/python2.7/dist-packages/salt/returners/slack_returner.py", line 212, in returner
    returns = dict((key, value) for key, value in returns.items() if value['result'] is not True or value['changes'])
AttributeError: 'str' object has no attribute 'items'
```

### Setup

The minion config:

```
return : slack
slack  :
  channel     : saltstack
  api_key     : xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  username    : salt
  yaml_format : true
  as_user     : true
  changes     : true
```

### Versions Report

```
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.8.0-32-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by gtmanfred** [comment]
If you run a command like 

```
salt \* --return slack test.echo 'something'
```

Do you see this error?

I think this is probably caused by something being run that isn't a state?

Thanks,
Daniel

**Comment by hgfischer** [comment]
Yes, I do see it when running `test.echo ..`

**Comment by gtmanfred** [comment]
Ok, it looks like this just needs to add a check that checks if the return is an actual dict before checking for `changes` in it.

Since not all returns are a dictionary.

I am marking this as a bug.

Thanks,
Daniel
