### ISSUE TITLE
Windows Minion can't use multiprocessing

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#4598]
with ```multiprocessing: True``` set I get the following at the cli when trying to start the Windows Minion.

```
[ERROR   ] Exception Can't pickle <function sync_modules at 0x0000000005841748>:
 it's not found as salt.loaded.int.module.saltutil.sync_modules occurred in sche
duled job
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\salt\python27\lib\multiprocessing\forking.py", line 373, in main
    prepare(preparation_data)
  File "C:\salt\python27\lib\multiprocessing\forking.py", line 482, in prepare
    file, path_name, etc = imp.find_module(main_name, dirs)
ImportError: No module named salt-minion
[DEBUG   ] Running scheduled job: __mine_interval
[ERROR   ] Exception Can't pickle <function sync_modules at 0x0000000005841748>:
 it's not found as salt.loaded.int.module.saltutil.sync_modules occurred in sche
duled job
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\salt\python27\lib\multiprocessing\forking.py", line 373, in main
    prepare(preparation_data)
  File "C:\salt\python27\lib\multiprocessing\forking.py", line 482, in prepare
    file, path_name, etc = imp.find_module(main_name, dirs)
ImportError: No module named salt-minion
```

**Comment by UtahDave** [comment]
I've verified that with the new lazy loader allows for multiprocessing in the develop branch!

I'm happily closing this one!
