### ISSUE TITLE
SSL_ST_INIT errors after package install

### ISSUE THREAD

**Issue by idlethreat** [saltstack/salt#46049]
## Description of Issue/Question

I'm running into an issue with installing *any* python packages on a salt-master. 

Anytime I install a package (either using apt-get or pip), salt-master becomes unusable and I have to recover it from backups.

From the debug output, It looks like it throws a:

`AttributeError: 'module' object has no attribute 'SSL_ST_INIT'`

This is unexpected. And I'm unsure exactly what is being installed which adversely affects SSL on the system after packages get installed.

## Steps to Reproduce Issue

Run any of the following. These I have tested and are known issues. It's possible there are other packages with issues 

* `pip install paramiko`
* `apt-get install python-paramiko`
* `pip install mysqldb`
* `apt-get install python-mysqldb`

## Versions Report

```
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-87-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

## Error Message

```
root@zusalta-base:~# salt-master -l debug
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: zusalta-base
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] Setting up the Salt Master
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
Traceback (most recent call last):
  File "/usr/bin/salt-master", line 22, in <module>
    salt_master()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 92, in salt_master
    master.start()
  File "/usr/lib/python2.7/dist-packages/salt/cli/daemons.py", line 204, in start
    super(Master, self).start()
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 1032, in start
    self.prepare()
  File "/usr/lib/python2.7/dist-packages/salt/cli/daemons.py", line 184, in prepare
    import salt.master
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 53, in <module>
    import salt.pillar
  File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 18, in <module>
    import salt.fileclient
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 29, in <module>
    import salt.utils.templates
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 31, in <module>
    import salt.utils.http
  File "/usr/lib/python2.7/dist-packages/salt/utils/http.py", line 71, in <module>
    import requests
  File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 54, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
```

**Comment by gtmanfred** [comment]
I am unable to replicate this.


```
root@a9b8c4a86202:/# salt-master -l info
[INFO    ] Setting up the Salt Master
[INFO    ] Preparing the root key for local communication
[INFO    ] The Salt Master is starting up
[INFO    ] salt-master is starting as user 'root'
[INFO    ] Current values for max open files soft/hard setting: 1048576/1048576
[INFO    ] Creating master process manager
[INFO    ] Creating master maintenance process
[INFO    ] Creating master event publisher process
[INFO    ] Starting the Salt Publisher on tcp://0.0.0.0:4505
[INFO    ] Starting the Salt Puller on ipc:///var/run/salt/master/publish_pull.ipc
[INFO    ] Creating master publisher process
[INFO    ] Creating master request server process
[INFO    ] Setting up the master communication server
[INFO    ] Found minion id from generate_minion_id(): a9b8c4a86202
[INFO    ] Found minion id from generate_minion_id(): a9b8c4a86202
[INFO    ] Found minion id from generate_minion_id(): a9b8c4a86202
[INFO    ] Found minion id from generate_minion_id(): a9b8c4a86202
[INFO    ] Found minion id from generate_minion_id(): a9b8c4a86202
[INFO    ] Found minion id from generate_minion_id(): a9b8c4a86202
[INFO    ] Found minion id from generate_minion_id(): a9b8c4a86202
[INFO    ] Found minion id from generate_minion_id(): a9b8c4a86202
[INFO    ] Found minion id from generate_minion_id(): a9b8c4a86202
[INFO    ] Found minion id from generate_minion_id(): a9b8c4a86202
[INFO    ] Found minion id from generate_minion_id(): a9b8c4a86202
[INFO    ] Found minion id from generate_minion_id(): a9b8c4a86202
[INFO    ] Found minion id from generate_minion_id(): a9b8c4a86202
[INFO    ] Found minion id from generate_minion_id(): a9b8c4a86202
[INFO    ] Found minion id from generate_minion_id(): a9b8c4a86202
[INFO    ] Found minion id from generate_minion_id(): a9b8c4a86202
[INFO    ] Found minion id from generate_minion_id(): a9b8c4a86202
[INFO    ] Found minion id from generate_minion_id(): a9b8c4a86202
[INFO    ] Found minion id from generate_minion_id(): a9b8c4a86202
[INFO    ] Found minion id from generate_minion_id(): a9b8c4a86202
[INFO    ] Found minion id from generate_minion_id(): a9b8c4a86202
[INFO    ] Worker binding to socket ipc:///var/run/salt/master/workers.ipc
[INFO    ] Worker binding to socket ipc:///var/run/salt/master/workers.ipc
[INFO    ] Worker binding to socket ipc:///var/run/salt/master/workers.ipc
[INFO    ] Worker binding to socket ipc:///var/run/salt/master/workers.ipc
[INFO    ] Worker binding to socket ipc:///var/run/salt/master/workers.ipc
^CExiting on Ctrl-c
root@a9b8c4a86202:/# apt install python-paramiko
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  python-ecdsa
The following NEW packages will be installed:
  python-ecdsa python-paramiko
0 upgraded, 2 newly installed, 0 to remove and 17 not upgraded.
Need to get 143 kB of archives.
After this operation, 794 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://archive.ubuntu.com/ubuntu xenial/main amd64 python-ecdsa all 0.13-2 [34.0 kB]
Get:2 http://archive.ubuntu.com/ubuntu xenial/main amd64 python-paramiko all 1.16.0-1 [109 kB]
Fetched 143 kB in 0s (171 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package python-ecdsa.
(Reading database ... 17159 files and directories currently installed.)
Preparing to unpack .../python-ecdsa_0.13-2_all.deb ...
Unpacking python-ecdsa (0.13-2) ...
Selecting previously unselected package python-paramiko.
Preparing to unpack .../python-paramiko_1.16.0-1_all.deb ...
Unpacking python-paramiko (1.16.0-1) ...
Setting up python-ecdsa (0.13-2) ...
Setting up python-paramiko (1.16.0-1) ...
root@a9b8c4a86202:/# salt-master -l info
[INFO    ] Setting up the Salt Master
[INFO    ] Preparing the root key for local communication
[INFO    ] The Salt Master is starting up
[INFO    ] salt-master is starting as user 'root'
[INFO    ] Current values for max open files soft/hard setting: 1048576/1048576
[INFO    ] Creating master process manager
[INFO    ] Creating master maintenance process
[INFO    ] Creating master event publisher process
[INFO    ] Starting the Salt Publisher on tcp://0.0.0.0:4505
[INFO    ] Starting the Salt Puller on ipc:///var/run/salt/master/publish_pull.ipc
[INFO    ] Creating master publisher process
[INFO    ] Creating master request server process
[INFO    ] Setting up the master communication server
[INFO    ] Found minion id from generate_minion_id(): a9b8c4a86202
[INFO    ] Found minion id from generate_minion_id(): a9b8c4a86202
[INFO    ] Found minion id from generate_minion_id(): a9b8c4a86202
[INFO    ] Found minion id from generate_minion_id(): a9b8c4a86202
[INFO    ] Found minion id from generate_minion_id(): a9b8c4a86202
[INFO    ] Found minion id from generate_minion_id(): a9b8c4a86202
[INFO    ] Found minion id from generate_minion_id(): a9b8c4a86202
[INFO    ] Found minion id from generate_minion_id(): a9b8c4a86202
[INFO    ] Found minion id from generate_minion_id(): a9b8c4a86202
[INFO    ] Found minion id from generate_minion_id(): a9b8c4a86202
[INFO    ] Found minion id from generate_minion_id(): a9b8c4a86202
[INFO    ] Found minion id from generate_minion_id(): a9b8c4a86202
[INFO    ] Found minion id from generate_minion_id(): a9b8c4a86202
[INFO    ] Found minion id from generate_minion_id(): a9b8c4a86202
[INFO    ] Found minion id from generate_minion_id(): a9b8c4a86202
[INFO    ] Found minion id from generate_minion_id(): a9b8c4a86202
[INFO    ] Found minion id from generate_minion_id(): a9b8c4a86202
[INFO    ] Found minion id from generate_minion_id(): a9b8c4a86202
[INFO    ] Found minion id from generate_minion_id(): a9b8c4a86202
[INFO    ] Found minion id from generate_minion_id(): a9b8c4a86202
[INFO    ] Found minion id from generate_minion_id(): a9b8c4a86202
[INFO    ] Worker binding to socket ipc:///var/run/salt/master/workers.ipc
[INFO    ] Worker binding to socket ipc:///var/run/salt/master/workers.ipc
[INFO    ] Worker binding to socket ipc:///var/run/salt/master/workers.ipc
[INFO    ] Worker binding to socket ipc:///var/run/salt/master/workers.ipc
[INFO    ] Worker binding to socket ipc:///var/run/salt/master/workers.ipc
```

Can you provide me with more information about how to replicate this?  Including the config files?

Can you also try to replicate it in a docker container, and provide that erroring container instance?

Thanks,
Daniel

**Comment by jimmynapkins** [comment]
I got around this issue on ubuntu 16.04. We were building images and installing python-openssl from repositories instead of pip which I believe is whats causing the issue. The following fixed it for me:

apt-get update && apt-get upgrade && apt-get remove python-openssl && pip install -U setuptools && pip install -U pip

Hope that helps. Moral of the story is never use your distribution's package manager to install Python packages.

**Comment by gtmanfred** [comment]
Cool, I am going to go ahead and close this issue since I have not heard back from OP since February.

**Comment by joaquinclearmetal** [comment]
This is an issue with`pyOpenSSL` being outdated.   A dependency may require this, and uses an outdated version.
