### ISSUE TITLE
dns_check doesn't do what it says

### ISSUE THREAD

**Issue by JeffAbrahamson** [saltstack/salt#46053]
### Setup

Using the example from the [documentation](https://docs.saltstack.com/en/latest/topics/jinja/index.html#dns-check):

     {{ 'www.google.com' | dns_check }}

leads to an error (see below).  The following parses, but leads to a different error (see below).

     {{ 'www.google.com' | dns_check(port='443') }}

### Steps to Reproduce Issue

In the first case, as noted in the documentation, the following error is emitted:

```
[CRITICAL] Rendering SLS 'base:firewall' failed: Jinja error: dns_check() takes at least 2 arguments (1 given)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 418, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 45, in top-level template code
TypeError: dns_check() takes at least 2 arguments (1 given)
```

In the second case, the code parses but results in the following output:

    Attempt to resolve address 'www.google.com' failed. Invalid or unresolveable address

even though a tcp connection to that host and port is accepted:

```
$ telnet www.google.com 443
Trying 216.58.209.228...
Connected to www.google.com.
Escape character is '^]'.
^]
telnet> c
Connection closed.
$ 
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
t$ salt-call --versions-report
Salt Version:
           Salt: 2017.7.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-112-generic
         system: Linux
        version: Ubuntu 16.04 xenial
 
$ 

```

### Further notes

The `dns_check` function, defined [here](https://github.com/saltstack/salt/blob/06a00be0e1f06399805e19261e4d00f6cfd9c6a0/salt/utils/network.py#L1750), requires a port number.  The [documentation](https://docs.saltstack.com/en/latest/topics/jinja/index.html#dns-check) does not indicate that a port number is required.

In addition, the name of the filter suggests that the function will "return the ip resolved by dns", not that it will in any way check if some port is listening, nor that my ip will be authorised to connect, nor that that check will be via tcp.

**Comment by Ch3LL** [comment]
You need to ensure 443 is an int. So just change it from `port='443'` to `port=443`. but agreed we need to update the documentation to ensure its clear a port is required.

**Comment by JeffAbrahamson** [comment]
Ah, ok, thanks.

I imagine it's too late to change the name to "connection_check" or something equally descriptive.  But a simple `gethostbyname()` style function would be quite useful here.

(In my case I'm writing firewall rules, where my yaml makes more sense as FQDN's but the rules require ip4v's.  But I have no reason to believe I'm authorised to connect to any port on those hosts.)

**Comment by MTecknology** [comment]
@JeffAbrahamson Please re-check this when 3000.1 comes out and be sure that the alternative resolution still applies. The PR I created to address this cannot be sensibly merged into master.

If you find that the issue still exists, please re-open, ping me, and I'll take a further look.
