### ISSUE TITLE
2017.7.3 salt master with "open_mode: True" becomes unresponsive if minion submits empty public key

### ISSUE THREAD

**Issue by zmedico** [saltstack/salt#46085]
### Description of Issue/Question

I noticed this problem when a minion in a bad state started sending an empty public key. The problem is reproducible by replacing the minion's `/etc/salt/pki/minion/minion.pub` file with an entirely empty file (zero bytes). 

### Setup
Create a salt master with `open_mode: True`, and a minion with an entirely empty `/etc/salt/pki/minion/minion.pub` file (zero bytes).

### Steps to Reproduce Issue
With the configuration described in the setup section, the log for the salt master service will show a series of exceptions like the following:
```
2018-02-16 14:25:06,972 [tornado.application:129 ][ERROR   ][30725] Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 285, in wrapper
    yielded = next(result)
  File "/usr/lib64/python2.7/site-packages/salt/transport/zeromq.py", line 620, in handle_message
    stream.send(self.serial.dumps(self._auth(payload['load'])))
  File "/usr/lib64/python2.7/site-packages/salt/transport/mixins/auth.py", line 430, in _auth
    with salt.utils.fopen(pubfn) as f:
  File "/usr/lib64/python2.7/site-packages/salt/utils/__init__.py", line 1361, in fopen
    fhandle = open(*args, **kwargs)  # pylint: disable=resource-leakage
IOError: [Errno 2] No such file or directory: '/etc/salt/pki/master/minions/salt-minion1.example.com'
```
I think the reason salt doesn't handle this well is that it's supposed to write the given key, but the key is an empty string, so `load['pub'] != disk_key` is False (due to earlier `disk_key = ''` initialization) and it fails to write the key here:

https://github.com/saltstack/salt/blob/v2017.7.3/salt/transport/mixins/auth.py#L416

Since the key is not written to disk, the `IOError: [Errno 2] No such file or directory` exception naturally occurs when it tries to open the file.

Ultimately, the salt master becomes unresponsive to minions, leading to messages like the following in minion logs:
```
2018-02-16 14:27:38,945 [salt.minion      :1774][WARNING ][1776] The minion failed to return the job information for job 20180216142717409355. This is often due to the master being shut down or overloaded. If the master is running consider increasing the worker_threads value.
```

### Versions Report
```
Salt Version:
           Salt: 2017.7.3

Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.7.4
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: 0.24.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Jan 30 2018, 03:06:24)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: 0.6.8
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.2.2

System Versions:
           dist: gentoo 2.4.1
         locale: UTF-8
        machine: x86_64
        release: 4.14.18-vanilla-base-4
         system: Linux
        version: Gentoo Base System 2.4.1
```

**Comment by gtmanfred** [comment]
Thanks for bringing this to our attention, we will get it fixed.
Daniel

**Comment by gtmanfred** [comment]
Can you provide me with more information about replicating this?

I started with a minion with an empty minion.pub file, and i got this error.

```
[CRITICAL] The Salt Master has rejected this minion's public key!
To repair this issue, delete the public key for this minion on the Salt Master and restart this minion.
Or restart the Salt Master in open mode to clean out the keys. The Salt Minion will now exit.
```

I also started the minion with a minion.pub (and it registered, without trouble, confirming that my master was in fact in open mode), then once the key was registered, i stopped the minion, did `echo > /etc/salt/pki/minion/minion.pub` and then started the minion again, and got the same result.

```
[root@salt /]# cat /etc/salt/master
open_mode: true
log_level: debug
[root@salt /]# ls -l /etc/salt/pki/minion/
total 0
[root@salt /]# salt-key
Accepted Keys:
Denied Keys:
Unaccepted Keys:
Rejected Keys:
[root@salt /]# systemctl start salt-minion
[root@salt /]# ls -l /etc/salt/pki/minion/
total 12
-r-------- 1 root root 1674 Feb 20 23:16 minion.pem
-rw-r--r-- 1 root root  450 Feb 20 23:16 minion.pub
-rw-r--r-- 1 root root  450 Feb 20 23:16 minion_master.pub
[root@salt /]# salt-key
Accepted Keys:
salt
Denied Keys:
Unaccepted Keys:
Rejected Keys:
[root@salt /]# salt \* test.ping
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'salt_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/74/be5ec1c296b5402b6c682dbdd0d854995b0090e2a83f948064e2bbc66d9a3c/.minions.p
[DEBUG   ] get_iter_returns for jid 20180220231631814630 sent to set(['salt']) will timeout at 23:16:36.826546
[DEBUG   ] jid 20180220231631814630 return from salt
[DEBUG   ] return event: {'salt': {'jid': '20180220231631814630', 'retcode': 0, 'ret': True}}
[DEBUG   ] LazyLoaded nested.output
salt:
    True
[DEBUG   ] jid 20180220231631814630 found all minions set(['salt'])
[root@salt /]# systemctl stop salt-minion
[root@salt /]# echo > /etc/salt/pki/minion/minion.pub
[root@salt /]# salt-minion -l error
[CRITICAL] The Salt Master has rejected this minion's public key!
To repair this issue, delete the public key for this minion on the Salt Master and restart this minion.
Or restart the Salt Master in open mode to clean out the keys. The Salt Minion will now exit.
[root@salt /]#
```

Thanks,
Daniel

**Comment by zmedico** [comment]
Use `echo -n > /etc/salt/pki/minion/minion.pub` to create a zero byte minion.pub. Without the `-n` option, minion.pub will contain a newline character.

**Comment by gtmanfred** [comment]
Ok, you are on the right track, the problem is actually that the `load['pub']` was empty. And so it was just skipping writing to that section.

And since there was no file there, it was can't auth.

This pr should fix the problem https://github.com/saltstack/salt/pull/46123

Thanks!
Daniel
