### ISSUE TITLE
Unable to use 'host.only' with the pyobjects renderer

### ISSUE THREAD

**Issue by BadgerOps** [saltstack/salt#46166]
### Description of Issue/Question
I'm attempting to manage my hosts file using the pyobjects renderer. 'Host.present()'  renders and applies fine, but when using 'Host.only()' I get an error when trying to render_state.
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Pillar (for mine functions)
```
mine_functions:
  # we build our /etc/hosts file off the private IP's
  network.ip_addrs:
    interface: eth1
```
mine output (for informational purposes)
```
$ sudo salt saltmaster mine.get \* network.ip_addrs
saltmaster.test-dev.com:
    ----------
    linux-1.test-dev.com:
        - 192.168.50.5
    saltmaster.test-dev.com:
        - 192.168.50.4
```
The SLS: (NOT working, with Host.only() )
```
#!pyobjects

# the purpose of this builder is to create a hostfile in the following format:
# 1.2.3.4    hostname    hostname.domain
# we have a couple custom grains that register the domain, and the IP of minions
# we'll use salt-mine to grab these grains and use them to build the host file

# first, set the network dictionary (key/value stores) from information stored in salt-mine
# the syntax is mine('host or grain lookup' 'mine_function')
# in this case we're matching on '*' for all hosts
# example of the dictionary are as follows:
# network = {'saltmaster': ['192.168.50.4'], 'linux-1': ['192.168.50.5']}

__salt__['mine.update']('*')

network = mine('*', 'network.ip_addrs')

for hostname in network.keys():
    hostname_short = hostname.split('.')[0] # set the non-fqdn hostname
    domain = hostname.split('.')[1] # pull out the domain, does not include .com
    # finally, build the hostfile
    Host.only(
      #hostname_short,
      name=network[hostname], # network.ip_addrs returns a list of IP's, even if its only 1 addr
      hostnames=[
            '%s-int.%s.com' % (hostname_short, domain), # hostname.domain aka FQDN
            '%s-int' % hostname_short # just hostname
            ]
    )
```

SLS - WORKING - using Host.present:
```
#!pyobjects
# network = {'saltmaster': ['192.168.50.4'], 'linux-1': ['192.168.50.5']}
__salt__['mine.update']('*')

network = mine('*', 'network.ip_addrs')

for hostname in network.keys():
    hostname_short = hostname.split('.')[0] # set the non-fqdn hostname
    domain = hostname.split('.')[1] # pull out the domain, does not include .com
    # finally, build the hostfile
    Host.present(
      hostname_short,
      ip=network[hostname], # network.ip_addrs returns a list of IP's, even if its only 1 addr
      names=[
            '%s-int.%s.com' % (hostname_short, domain), # hostname.domain aka FQDN
            '%s-int' % hostname_short # just hostname
            ]
    )
```
ERROR output from the state.apply (when using host.only() ):
```
$ sudo salt \* state.apply base.hostfile_builder test=true -l error
saltmaster.tsheets-dev.com:
    Data failed to compile:
----------
    Rendering SLS base.hostfile_builder failed, render error: make_state() takes exactly 1 argument (0 given)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 3213, in render_state
    rendered_sls=mods
  File "/usr/lib/python2.7/dist-packages/salt/template.py", line 95, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/renderers/pyobjects.py", line 504, in render
    exec_(final_template, _globals)
  File "/usr/lib/python2.7/dist-packages/salt/ext/six.py", line 706, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "<string>", line 31, in <module>
TypeError: make_state() takes exactly 1 argument (0 given)

```
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
Logs given above
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
$ sudo salt --versions-report
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Nov 23 2017, 15:49:48)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
         locale: UTF-8
        machine: x86_64
        release: 3.13.0-32-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

I'm referencing [this line of code](https://github.com/saltstack/salt/blob/e974cf385d3ac0b86959a0eca88d96c9e3527ec3/salt/states/host.py#L150) for how I'm structuring the Host.only() statement, but perhaps I'm doing it wrong? 

I've been banging my head off the desk for a while here, hopefully I just missed something silly. :)

**Comment by BadgerOps** [comment]
[here](https://github.com/BadgerOps/salt-workspace/commit/2996471f3bda21b9e6e607c1c31c9e38f65ab0a4) is a working example in my test environment of what I'm trying to accomplish.

**Comment by BadgerOps** [comment]
Ok, so the age old "submit a ticket, then have a lightbulb moment" just happened :joy: 

The following works. I realized the error that I was seeing was probably related to not enough arguments getting passed into Host.only() - specifically name=ip - if I eliminated `name=` and just did `ip[0]` (ip is a list with 1 value) it works fine. My updated state below:
```
__salt__['mine.update']('*')
network = mine('*', 'network.ip_addrs')
for hostname, ip in network.items(): << Iterate instead of just using keys
    hostname_short = hostname.split('.')[0] # set the non-fqdn hostname
    domain = hostname.split('.')[1] # pull out the domain, does not include .com
    # finally, build the hostfile
    Host.only(
      ip[0], << positional instead of keyword. No idea why keyword didn't work.
      hostnames=[
            '%s-int.%s.com' % (hostname_short, domain), # hostname.domain aka FQDN
            '%s-int' % hostname_short # just hostname
            ]
    )
```
I'll go ahead and close this, but hopefully this helps someone in the future? Cheers!

**Comment by BadgerOps** [comment]
And after some further mulling, I know why the `name=ip[0]` kwarg didn't work, [this line](https://github.com/saltstack/salt/blob/06a00be0e1f06399805e19261e4d00f6cfd9c6a0/salt/utils/pyobjects.py#L180) requires at least 1 positional argument, and chokes when attempting to just use kwargs.
