### ISSUE TITLE
winrepo.update_git_repos Error

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#46205]
### Description of Issue/Question
On 2018.3.0rc1(oxygen.rc1) running `salt-run winrepo.update_git_repos` on the Linux master fails with this error.
```
Exception occurred in runner winrepo.update_git_repos: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 387, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/runners/winrepo.py", line 167, in update_git_repos
    if not any((salt.utils.gitfs.HAS_GITPYTHON, salt.utils.gitfs.HAS_PYGIT2)):
AttributeError: 'module' object has no attribute 'HAS_GITPYTHON'
```
I have tried with `gitpython` and `pygit2` installed. Same error.

### Steps to Reproduce Issue
Install correct salt version and run `salt-run winrepo.update_git_repos`
```
root@localhost:~# salt-run winrepo.update_git_repos
Exception occurred in runner winrepo.update_git_repos: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 387, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/runners/winrepo.py", line 167, in update_git_repos
    if not any((salt.utils.gitfs.HAS_GITPYTHON, salt.utils.gitfs.HAS_PYGIT2)):
AttributeError: 'module' object has no attribute 'HAS_GITPYTHON'
root@localhost:~# 
```

### Versions Report
```
Salt Version:
           Salt: 2018.3.0-n/a-0a7e347
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.14.17-x86_64-linode99
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by rallytime** [comment]
@twangboy Can you look into this?

**Comment by rallytime** [comment]
Actually, I just talked to @twangboy and he said this one would be better for @terminalmage to look at since it happens on the master side.

@terminalmage Can you take a look?

**Comment by terminalmage** [comment]
https://github.com/saltstack/salt/pull/46209 fixes this.

**Comment by rallytime** [comment]
@frogunder Can you confirm this is fixed?

**Comment by frogunder** [comment]
@rallytime Yes, this is fixed.

**Comment by rallytime** [comment]
🎉
