### ISSUE TITLE
multimaster failover not working 

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#46202]
### Description of Issue/Question
In a multimaster failover setup on 2018.3.0rc1(oxygen.rc1) the minions stop.
It seems to be working fine/correctly for a little while. Tried a couple of times and seems when one master stops it starts to fail. 
See this in the minion log:
```
2018-02-26 18:02:15,266 [salt.minion      :204 ][WARNING ][16492] Master ip address changed from 10.1.51.25 to 10.1.51.24
2018-02-26 18:02:15,616 [salt.minion      :433 ][ERROR   ][16492] Exception unsupported operand type(s) for -: 'str' and 'datetime.datetime' occurred in scheduled job
2018-02-26 18:02:16,613 [salt.minion      :433 ][ERROR   ][16492] Exception unsupported operand type(s) for -: 'str' and 'datetime.datetime' occurred in scheduled job
2018-02-26 18:02:17,611 [salt.minion      :433 ][ERROR   ][16492] Exception unsupported operand type(s) for -: 'str' and 'datetime.datetime' occurred in scheduled job
2018-02-26 18:02:18,611 [salt.minion      :433 ][ERROR   ][16492] Exception unsupported operand type(s) for -: 'str' and 'datetime.datetime' occurred in scheduled job
2018-02-26 18:02:19,611 [salt.minion      :433 ][ERROR   ][16492] Exception unsupported operand type(s) for -: 'str' and 'datetime.datetime' occurred in scheduled job
2018-02-26 18:02:20,288 [salt.minion      :204 ][WARNING ][16492] Master ip address changed from 10.1.51.24 to 10.1.51.25
2018-02-26 18:02:20,611 [salt.minion      :433 ][ERROR   ][16492] Exception unsupported operand type(s) for -: 'str' and 'datetime.datetime' occurred in scheduled job
2018-02-26 18:02:21,611 [salt.minion      :433 ][ERROR   ][16492] Exception unsupported operand type(s) for -: 'str' and 'datetime.datetime' occurred in scheduled job
2018-02-26 18:02:22,610 [salt.minion      :433 ][ERROR   ][16492] Exception unsupported operand type(s) for -: 'str' and 'datetime.datetime' occurred in scheduled job
2018-02-26 18:02:23,619 [salt.minion      :433 ][ERROR   ][16492] Exception unsupported operand type(s) for -: 'str' and 'datetime.datetime' occurred in scheduled job
2018-02-26 18:02:24,620 [salt.minion      :433 ][ERROR   ][16492] Exception unsupported operand type(s) for -: 'str' and 'datetime.datetime' occurred in scheduled job
2018-02-26 18:02:25,300 [salt.minion      :644 ][ERROR   ][16492] No master could be reached or all masters denied the minion's connection attempt.
2018-02-26 18:02:25,301 [salt.scripts     :146 ][WARNING ][16492] Fatal functionality error caught by minion handler:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 144, in minion_process
    minion.start()
  File "/usr/lib/python2.7/site-packages/salt/cli/daemons.py", line 350, in start
    raise SaltClientError('Minion could not connect to Master')
SaltClientError: Minion could not connect to Master
2018-02-26 18:02:25,301 [salt.scripts     :147 ][WARNING ][16492] ** Restarting minion **
```

See this in the master log:
```
2018-02-26 18:02:15,646 [salt.utils.process:754 ][ERROR   ][21918] An un-handled exception from the multiprocessing process 'MWorker-1' was caught:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/process.py", line 747, in _run
    return self._original_run()
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 1078, in run
    self.aes_funcs = AESFuncs(self.opts)
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 1113, in __init__
    self.masterapi = salt.daemons.masterapi.RemoteFuncs(opts)
  File "/usr/lib/python2.7/site-packages/salt/daemons/masterapi.py", line 427, in __init__
    rend=False)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 864, in __init__
    role='master'
  File "/usr/lib/python2.7/site-packages/salt/config/__init__.py", line 2386, in minion_config
    apply_sdb(opts)
  File "/usr/lib/python2.7/site-packages/salt/config/__init__.py", line 2529, in apply_sdb
    sdb_opts[key] = apply_sdb(opts, value)
  File "/usr/lib/python2.7/site-packages/salt/config/__init__.py", line 2529, in apply_sdb
    sdb_opts[key] = apply_sdb(opts, value)
  File "/usr/lib/python2.7/site-packages/salt/config/__init__.py", line 2529, in apply_sdb
    sdb_opts[key] = apply_sdb(opts, value)
  File "/usr/lib/python2.7/site-packages/salt/config/__init__.py", line 2523, in apply_sdb
    if isinstance(sdb_opts, six.string_types) and sdb_opts.startswith('sdb://'):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb8 in position 0: ordinal not in range(128)
2018-02-26 18:02:15,710 [salt.utils.process:754 ][ERROR   ][21917] An un-handled exception from the multiprocessing process 'MWorker-0' was caught:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/process.py", line 747, in _run
    return self._original_run()
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 1078, in run
    self.aes_funcs = AESFuncs(self.opts)
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 1113, in __init__
    self.masterapi = salt.daemons.masterapi.RemoteFuncs(opts)
  File "/usr/lib/python2.7/site-packages/salt/daemons/masterapi.py", line 427, in __init__
    rend=False)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 864, in __init__
    role='master'
  File "/usr/lib/python2.7/site-packages/salt/config/__init__.py", line 2386, in minion_config
    apply_sdb(opts)
  File "/usr/lib/python2.7/site-packages/salt/config/__init__.py", line 2529, in apply_sdb
    sdb_opts[key] = apply_sdb(opts, value)
  File "/usr/lib/python2.7/site-packages/salt/config/__init__.py", line 2529, in apply_sdb
    sdb_opts[key] = apply_sdb(opts, value)
  File "/usr/lib/python2.7/site-packages/salt/config/__init__.py", line 2529, in apply_sdb
    sdb_opts[key] = apply_sdb(opts, value)
  File "/usr/lib/python2.7/site-packages/salt/config/__init__.py", line 2523, in apply_sdb
    if isinstance(sdb_opts, six.string_types) and sdb_opts.startswith('sdb://'):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb8 in position 0: ordinal not in range(128)
2018-02-26 18:02:15,865 [salt.utils.process:754 ][ERROR   ][21927] An un-handled exception from the multiprocessing process 'MWorker-3' was caught:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/process.py", line 747, in _run
    return self._original_run()
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 1078, in run
    self.aes_funcs = AESFuncs(self.opts)
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 1113, in __init__
    self.masterapi = salt.daemons.masterapi.RemoteFuncs(opts)
  File "/usr/lib/python2.7/site-packages/salt/daemons/masterapi.py", line 427, in __init__
    rend=False)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 864, in __init__
    role='master'
  File "/usr/lib/python2.7/site-packages/salt/config/__init__.py", line 2386, in minion_config
    apply_sdb(opts)
  File "/usr/lib/python2.7/site-packages/salt/config/__init__.py", line 2529, in apply_sdb
    sdb_opts[key] = apply_sdb(opts, value)
  File "/usr/lib/python2.7/site-packages/salt/config/__init__.py", line 2529, in apply_sdb
    sdb_opts[key] = apply_sdb(opts, value)
  File "/usr/lib/python2.7/site-packages/salt/config/__init__.py", line 2529, in apply_sdb
    sdb_opts[key] = apply_sdb(opts, value)
  File "/usr/lib/python2.7/site-packages/salt/config/__init__.py", line 2523, in apply_sdb
    if isinstance(sdb_opts, six.string_types) and sdb_opts.startswith('sdb://'):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb8 in position 0: ordinal not in range(128)
```

I also see this when trying to see if the master and minion are running:
```
[root@localhost ~]# ps aux | grep salt
root     25106  0.0  0.0 112660   944 pts/0    S+   19:06   0:00 grep --color=auto salt
[root@localhost ~]# service salt-master start
Redirecting to /bin/systemctl start salt-master.service
[root@localhost ~]# ps aux | grep salt
root     25123 35.0  2.1 380252 39928 ?        Ss   19:06   0:00 /usr/bin/python2 /usr/bin/salt-master
root     25134  0.0  1.4 354132 26712 ?        S    19:06   0:00 /usr/bin/python2 /usr/bin/salt-master
root     25135  0.0  1.7 461288 33860 ?        Sl   19:06   0:00 /usr/bin/python2 /usr/bin/salt-master
root     25136  0.0  1.7 379492 33536 ?        S    19:06   0:00 /usr/bin/python2 /usr/bin/salt-master
root     25139  3.5  1.9 382708 37060 ?        S    19:06   0:00 /usr/bin/python2 /usr/bin/salt-master
root     25140  0.5  1.8 380252 34092 ?        S    19:06   0:00 /usr/bin/python2 /usr/bin/salt-master
root     25141  5.0  1.8 560500 34632 ?        Rl   19:06   0:00 /usr/bin/python2 /usr/bin/salt-master
root     25142 15.0  1.8 381512 35708 ?        R    19:06   0:00 /usr/bin/python2 /usr/bin/salt-master
root     25143 15.0  1.9 381528 35820 ?        R    19:06   0:00 /usr/bin/python2 /usr/bin/salt-master
root     25150  0.0  1.8 453984 34344 ?        Sl   19:06   0:00 /usr/bin/python2 /usr/bin/salt-master
root     25151 15.0  1.8 381484 35760 ?        R    19:06   0:00 /usr/bin/python2 /usr/bin/salt-master
root     25152 14.5  1.8 381476 35652 ?        R    19:06   0:00 /usr/bin/python2 /usr/bin/salt-master
root     25153 15.0  1.8 381480 35664 ?        R    19:06   0:00 /usr/bin/python2 /usr/bin/salt-master
root     25156  0.0  0.0 112660   944 pts/0    R+   19:06   0:00 grep --color=auto salt
[root@localhost ~]# service salt-minion restart
Redirecting to /bin/systemctl restart salt-minion.service
[root@localhost ~]# ps aux | grep salt
root     25123  4.3  2.1 380252 39928 ?        Ss   19:06   0:00 /usr/bin/python2 /usr/bin/salt-master
root     25134  0.0  1.4 354132 26712 ?        S    19:06   0:00 /usr/bin/python2 /usr/bin/salt-master
root     25135  0.0  1.7 461288 33860 ?        Sl   19:06   0:00 /usr/bin/python2 /usr/bin/salt-master
root     25136  0.0  1.7 379492 33536 ?        S    19:06   0:00 /usr/bin/python2 /usr/bin/salt-master
root     25139  0.4  1.9 382708 37060 ?        S    19:06   0:00 /usr/bin/python2 /usr/bin/salt-master
root     25140  0.1  1.8 380252 34144 ?        S    19:06   0:00 /usr/bin/python2 /usr/bin/salt-master
root     25141 68.4  1.8 560500 34632 ?        Rl   19:06   0:10 /usr/bin/python2 /usr/bin/salt-master
root     25150  0.0  1.8 453984 34344 ?        Sl   19:06   0:00 /usr/bin/python2 /usr/bin/salt-master
root     25187  6.5  0.0      0     0 ?        Z    19:06   0:00 [salt-master] <defunct>
root     25188  6.5  0.0      0     0 ?        Z    19:06   0:00 [salt-master] <defunct>
root     25189  6.5  0.0      0     0 ?        Z    19:06   0:00 [salt-master] <defunct>
root     25190  6.3  0.0      0     0 ?        Z    19:06   0:00 [salt-master] <defunct>
root     25191  6.5  0.0      0     0 ?        Z    19:06   0:00 [salt-master] <defunct>
root     25193  0.0  0.0 112660   944 pts/0    R+   19:06   0:00 grep --color=auto salt
[root@localhost ~]# 
```

### Setup
Put in minion config file
```
master:
  - minionA
  - minionB
master_shuffle: True
master_type: failover
master_alive_interval: 30
``` 

### Steps to Reproduce Issue
Set up multimaster failover environment.
Try to run some commands and stop one master, stop both master, then restart, etc.

### Versions Report
```
Salt Version:
           Salt: 2018.3.0-n/a-b527a6c
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

**Comment by rallytime** [comment]
@DmitryKuzmenko Can you look into this? This is something new to the latest test run - it wasn't failing on the last run @frogunder did a couple of weeks ago.

**Comment by DmitryKuzmenko** [comment]
At a first glance it looks we have to translate the opts string to unicode before looking for `startswith`. But I'll try to figure out why it didn't happen before first.

**Comment by DmitryKuzmenko** [comment]
Discussed with @terminalmage. Potential fix: https://github.com/saltstack/salt/pull/46213

**Comment by rallytime** [comment]
@frogunder Can you test that change? ^

**Comment by frogunder** [comment]
It is still failing for me with that potential fix.

**Comment by rallytime** [comment]
@DmitryKuzmenko ^ can you take another look?

**Comment by DmitryKuzmenko** [comment]
This must be 143% fixed now.

**Comment by garethgreenaway** [comment]
Didn't realize at the time when I was triaging this issue that it was related to the scheduler.  The values that are being written into the configuration file are internal values used by the scheduler.  One approach would be to just ensure that they're never written out to the configuration file.

**Comment by DmitryKuzmenko** [comment]
@garethgreenaway you're right but anywhere if we have special code handling this case it must work, I think.
