### ISSUE TITLE
Highstate Returner Failing with "ValueError: too many values to unpack"

### ISSUE THREAD

**Issue by jessebye** [saltstack/salt#46225]
### Description of Issue/Question
When attempting to use the new salt.returners.highstate_return module, I see this error in the minion log and the output file is not created:
```
2018-02-27 20:59:10,047 [salt.minion      ][ERROR   ][8336] The return failed for job 20180227205817081571 too many values to unpack
2018-02-27 20:59:10,048 [salt.minion      ][ERROR   ][8336] Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1581, in _thread_return
    minion_instance.returners[returner_str](ret)
  File "/usr/lib/python2.7/dist-packages/salt/returners/highstate_return.py", line 478, in returner
    report, failed = _generate_report(ret, setup)
  File "/usr/lib/python2.7/dist-packages/salt/returners/highstate_return.py", line 384, in _generate_report
    {'states': _generate_states_report(sorted_data)}
  File "/usr/lib/python2.7/dist-packages/salt/returners/highstate_return.py", line 297, in _generate_states_report
    [x.rstrip('_').lstrip('-') for x in state.split('|')]
ValueError: too many values to unpack
```
### Setup
`/etc/salt/minion.d/returner.conf`:
```
simple.highstate.report_failures: True
simple.highstate.report_changes: True
simple.highstate.report_everything: False
simple.highstate.failure_function: pillar.items
simple.highstate.success_function: pillar.items
simple.highstate.report_format: html
simple.highstate.report_delivery: file
simple.highstate.file_output: /tmp/foo
```
### Steps to Reproduce Issue
1. Run `salt 'salt' state.apply --return highstate`.
2. Tail the minion log.
3. Observe the error:
```
2018-02-27 20:59:10,047 [salt.minion      ][ERROR   ][8336] The return failed for job 20180227205817081571 too many values to unpack
2018-02-27 20:59:10,048 [salt.minion      ][ERROR   ][8336] Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1581, in _thread_return
    minion_instance.returners[returner_str](ret)
  File "/usr/lib/python2.7/dist-packages/salt/returners/highstate_return.py", line 478, in returner
    report, failed = _generate_report(ret, setup)
  File "/usr/lib/python2.7/dist-packages/salt/returners/highstate_return.py", line 384, in _generate_report
    {'states': _generate_states_report(sorted_data)}
  File "/usr/lib/python2.7/dist-packages/salt/returners/highstate_return.py", line 297, in _generate_states_report
    [x.rstrip('_').lstrip('-') for x in state.split('|')]
ValueError: too many values to unpack
```

### Versions Report
```
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 20 2017, 18:23:56)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-112-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by gtmanfred** [comment]
I am unable to replicate this with a simple state, can you provide me with a state setup so that I can replicate the error?

```
[root@65336887d0e2 /]# tail -c +0 /etc/salt/minion /srv/salt/test.sls
==> /etc/salt/minion <==
simple.highstate.report_failures: True
simple.highstate.report_changes: True
simple.highstate.report_everything: False
simple.highstate.failure_function: pillar.items
simple.highstate.success_function: pillar.items
simple.highstate.report_format: html
simple.highstate.report_delivery: file
simple.highstate.file_output: /tmp/foo

==> /srv/salt/test.sls <==
test:
  file.touch:
    - name: /tmp/test
[root@65336887d0e2 /]# salt-call --local -l debug state.apply test
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: 65336887d0e2
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/minion
[INFO    ] Could not determine init system from command line: (bash)
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded state.apply
[DEBUG   ] LazyLoaded saltutil.is_running
[DEBUG   ] LazyLoaded grains.get
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[DEBUG   ] Updating roots fileserver cache
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] In saltenv 'base', looking at rel_path 'test.sls' to resolve 'salt://test.sls'
[DEBUG   ] In saltenv 'base', ** considering ** path '/var/cache/salt/minion/files/base/test.sls' to resolve 'salt://test.sls'
[DEBUG   ] compile template: /var/cache/salt/minion/files/base/test.sls
[DEBUG   ] Jinja search path: ['/var/cache/salt/minion/files/base']
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/test.sls' using 'jinja' renderer: 0.00262808799744
[DEBUG   ] Rendered data from file: /var/cache/salt/minion/files/base/test.sls:
test:
  file.touch:
    - name: /tmp/test

[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Results of YAML rendering:
OrderedDict([('test', OrderedDict([('file.touch', [OrderedDict([('name', '/tmp/test')])])]))])
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/test.sls' using 'yaml' renderer: 0.00322604179382
[DEBUG   ] LazyLoaded file.touch
[INFO    ] Running state [/tmp/test] at time 15:29:39.574603
[INFO    ] Executing state file.touch for [/tmp/test]
[DEBUG   ] LazyLoaded file.touch
[INFO    ] {'touched': '/tmp/test'}
[INFO    ] Completed state [/tmp/test] at time 15:29:39.579048 duration_in_ms=4.443
[DEBUG   ] File /var/cache/salt/minion/accumulator/46825424 does not exist, no need to cleanup.
[DEBUG   ] LazyLoaded config.option
[DEBUG   ] LazyLoaded highstate.output
[DEBUG   ] LazyLoaded nested.output
local:
----------
          ID: test
    Function: file.touch
        Name: /tmp/test
      Result: True
     Comment: Updated times on file /tmp/test
     Started: 15:29:39.574605
    Duration: 4.443 ms
     Changes:
              ----------
              touched:
                  /tmp/test

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   4.443 ms
```

Thanks,
Daniel

**Comment by gtmanfred** [comment]
Even when using a salt-master, i can't replicate it.

```
[root@65336887d0e2 /]# salt \* state.apply test --return highstate
65336887d0e2:
----------
          ID: test
    Function: file.touch
        Name: /tmp/test
      Result: True
     Comment: Updated times on file /tmp/test
     Started: 15:31:32.425968
    Duration: 6.004 ms
     Changes:
              ----------
              touched:
                  /tmp/test

Summary for 65336887d0e2
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   6.004 ms
[root@65336887d0e2 /]# cat /var/log/salt/minion
2018-02-28 15:29:05,340 [salt.utils.verify:525 ][WARNING ][512] Insecure logging configuration detected! Sensitive data may be logged.
2018-02-28 15:29:38,308 [salt.utils.verify:525 ][WARNING ][535] Insecure logging configuration detected! Sensitive data may be logged.
2018-02-28 15:31:10,678 [salt.crypt                                            :642 ][ERROR   ][933] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
```

**Comment by jessebye** [comment]
@gtmanfred does my `returner.conf` look correct to you? was that what you used for testing?

**Comment by jessebye** [comment]
Our Salt master has a very complex pillar and lots of states being applied. Not sure the best way to provide you configuration to reproduce since there is a lot of confidential information there. Perhaps if you can try a scenario where you apply about 200 states to a minion?

**Comment by gtmanfred** [comment]
I used the same options from your returner.conf in my /etc/salt/minion.

If you add a `log.error` here in the highstate_return.py file, and spit out which state is having the problem, it would help.

```
File "/usr/lib/python2.7/dist-packages/salt/returners/highstate_return.py", line 297, in _generate_states_report
    [x.rstrip('_').lstrip('-') for x in state.split('|')]
```

```
import logging
log = logging.getLogger(__name__)
log.error('HERE %s', state)
```

**Comment by jessebye** [comment]
I ran this again but specified a single state instead of the highstate. Here was the result:
```
2018-02-28 19:30:33,310 [salt.minion      ][ERROR   ][6504] Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1581, in _thread_return
    minion_instance.returners[returner_str](ret)
  File "/usr/lib/python2.7/dist-packages/salt/returners/highstate_return.py", line 478, in returner
    report, failed = _generate_report(ret, setup)
  File "/usr/lib/python2.7/dist-packages/salt/returners/highstate_return.py", line 334, in _generate_report
    retdata.items(),
AttributeError: 'bool' object has no attribute 'items'
```

**Comment by jessebye** [comment]
@gtmanfred Ok, that narrowed it down I think:
```
2018-02-28 19:42:07,631 [salt.loaded.int.returner.highstate_return][ERROR   ][9959] HERE cmd_|-hostname_set_active_|-hostname west-salt-api-dev-9999a_|-run
2018-02-28 19:42:07,632 [salt.loaded.int.returner.highstate_return][ERROR   ][9959] HERE file_|-hostname_set_file_|-/etc/hostname_|-managed
2018-02-28 19:42:07,632 [salt.loaded.int.returner.highstate_return][ERROR   ][9959] HERE file_|-apt_timeout_|-/etc/apt/apt.conf.d/99timeout_|-managed
2018-02-28 19:42:07,632 [salt.loaded.int.returner.highstate_return][ERROR   ][9959] HERE cmd_|-Create_Swap_Partition_2048_|-[ -f /.swapfile ] || fallocate -l 2048M /.swapfile
chmod 0600 /.swapfile
mkswap /.swapfile
echo '/.swapfile      none      swap     sw       0       0' >> /etc/fstab
swapon -a
_|-run
2018-02-28 19:42:07,633 [salt.minion      ][ERROR   ][9959] The return failed for job 20180228194136143808 too many values to unpack
2018-02-28 19:42:07,634 [salt.minion      ][ERROR   ][9959] Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1581, in _thread_return
    minion_instance.returners[returner_str](ret)
  File "/usr/lib/python2.7/dist-packages/salt/returners/highstate_return.py", line 480, in returner
    report, failed = _generate_report(ret, setup)
  File "/usr/lib/python2.7/dist-packages/salt/returners/highstate_return.py", line 386, in _generate_report
    {'states': _generate_states_report(sorted_data)}
  File "/usr/lib/python2.7/dist-packages/salt/returners/highstate_return.py", line 299, in _generate_states_report
    [x.rstrip('_').lstrip('-') for x in state.split('|')]
ValueError: too many values to unpack
```

Here is the create_swap_partition state:
```
{% set swap_size =  salt['pillar.get']('server_info:swap_size', 2048) %}

{% if swap_size != 0 %}
Create_Swap_Partition_{{swap_size}}:
  cmd.run:
    - name: |
        [ -f /.swapfile ] || fallocate -l {{swap_size}}M /.swapfile
        chmod 0600 /.swapfile
        mkswap /.swapfile
        echo '/.swapfile      none      swap     sw       0       0' >> /etc/fstab
        swapon -a
    - unless: file /.swapfile 2>&1 | grep -q "Linux/i386 swap"
{% endif %}
```

**Comment by jessebye** [comment]
@gtmanfred I reworked our swap state and it no longer throws an error there. However, I am still not getting any output in `/tmp/foo` from the highstate returner. Not seeing any errors in the minion log indicating a problem either. Any idea where to go next?

**Comment by jessebye** [comment]
So I noticed in the Docs that `--return_config simple` was shown in an example corresponding with the `simple.highstate...` type config I was using. I passed that in and now see this in the minion debug log:
```
[DEBUG   ] LazyLoaded highstate.returner
[DEBUG   ] highstate setup {'report_format': 'html', 'report_changes': True, 'report_delivery': 'file', 'report_failures': True, 'success_function': 'pillar.items', 'file_output': '/tmp/foo', 'failure_function':
 'pillar.items'}
[DEBUG   ] highstate total: 108
[DEBUG   ] highstate failed: 0
[DEBUG   ] highstate unchanged: 104
[DEBUG   ] highstate changed: 4
```

I also am now seeing the `/tmp/foo` file as expected!

I think this still needs to be investigated as a bug because a multi-line `cmd.run` state shouldn't break this returner.

**Comment by gtmanfred** [comment]
So, i don't think it is a problem with multi line cmd.run commands, i think the problem is that the cmd.run's name is the command that is being run, and you have a | in your command, and this is causing a problem.

If you switch out the line that is erroring in highstate_return.py with 

```
        module, stateid, name, function = state.split('-|_')
```

Are you able to use your old state?

Thanks,
Daniel

**Comment by jessebye** [comment]
@gtmanfred I haven't been able to test the old state. We just got rid of it and went with a new version from [salt-formulas-linux](https://github.com/salt-formulas/salt-formula-linux). I think we can close this since it's doubtful that many people would intentionally have a state name with a `|` in it.

**Comment by gtmanfred** [comment]
Pr here for anyone else that runs across this

#46434
