### ISSUE TITLE
Python 3 API TypeError in salt-cloud 2017.7.4 on EC2

### ISSUE THREAD

**Issue by max-orhai** [saltstack/salt#46237]
### Description of Issue/Question

I'm using salt-cloud in EC2. I upgraded to 2017.7.4 hoping to use the Python 3 API, but encountered an error in the ec2.py availability zone listing code.

### Setup

```
ubuntu@ip-XXXXX:~$ cat /etc/salt/cloud.providers
ec2_public:
  minion:
    master: XXXXX
  ssh_interface: private_ips
  id: 'use-instance-role-credentials'
  key: 'use-instance-role-credentials'
  private_key: /etc/salt/saltmaster-key.pem
  keyname: saltmaster-key
  securitygroup: salty
  location: us-west-2
  availability_zone: us-west-2b
  driver: ec2

ubuntu@ip-XXXXX:~$ cat /etc/salt/cloud.profiles
ec2_test:
  provider: ec2_public
  # stock amd64 Ubuntu 16.04
  image: ami-0def3275
  size: t2.micro
  ssh_username: ubuntu
```

### Steps to Reproduce Issue

```
ubuntu@ip-XXXXX:~$ sudo python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from salt.cloud import CloudClient
>>> cloudcli = CloudClient(path='/etc/salt/cloud')
>>> cloudcli.profile('ec2_test', names=['tmp0', 'tmp1'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.5/site-packages/salt/cloud/__init__.py", line 348, in profile
    mapper.run_profile(profile, names, vm_overrides=vm_overrides)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/salt/cloud/__init__.py", line 1448, in run_profile
    ret[name] = self.create(vm_)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/salt/cloud/__init__.py", line 1278, in create
    output = self.clouds[func](vm_)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/salt/cloud/clouds/ec2.py", line 2617, in create
    data, vm_ = request_instance(vm_, location)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/salt/cloud/clouds/ec2.py", line 1842, in request_instance
    az_ = get_availability_zone(vm_)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/salt/cloud/clouds/ec2.py", line 1166, in get_availability_zone
    zones = _list_availability_zones(vm_)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/salt/cloud/clouds/ec2.py", line 1341, in _list_availability_zones
    ret[zone['zoneName']] = zone['zoneState']
TypeError: string indices must be integers
```

This works as expected with Python 2.7.

### Versions Report
```
Salt Version:
           Salt: 2017.7.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.5
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.2 (default, Nov 23 2017, 16:37:01)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.6
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-1050-aws
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by gtmanfred** [comment]
Thanks for reporting this.

If you wanted to dig in and submit a PR to fix it in the 2017.7 branch we would greatly appreciate it.

We have also added better py3 support in the 2018.3 branch which we are working on getting an RC release out soon, would you mind testing this with py3 on that branch?

Thanks,
Daniel

**Comment by max-orhai** [comment]
I'm sticking with the Python 2 library for now, but when I get some time to work on converting my salt setup to Python 3 I'd be happy to submit a PR for this issue. Probably won't happen this week, though.

I'll look out for the 2018.3 RC.

**Comment by gtmanfred** [comment]
Awesome, thanks! it is much appreciated!

**Comment by max-orhai** [comment]
OK, this bug is actually in [`utils/aws.py:creds`](https://github.com/saltstack/salt/blob/develop/salt/utils/aws.py#L100) where substitution of the encoded string from the previous API response is producing a url like `http://169.254.169.254/latest/meta-data/iam/security-credentials/b'saltmaster-role'`.

The encoding on the role request is `'ISO-8859-1'`, but we'd have the same problem in the `'utf-8'` fallback case too. Using `result.text` directly works just fine. I'm not sure if there's ever a good reason to encode this response string as a bytestring.

**Comment by max-orhai** [comment]
See PR #46382
