### ISSUE TITLE
2018.3.0rc1 stacktraces & doomloops with schedule

### ISSUE THREAD

**Issue by The-Loeki** [saltstack/salt#46249]
### Description of Issue/Question
Any 2018.3 salt command/daemon w/a mine update schedule in it will exhibit this behaviour, e.g. `salt-call`, `salt-run fileserver.update` etc.

The master daemon continually reinstatiates itself leading to excessive load.

```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb8 in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/bin/salt-run", line 10, in <module>
    salt_run()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 412, in salt_run
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/run.py", line 40, in run
    ret = runner.run()
  File "/usr/lib/python2.7/site-packages/salt/runner.py", line 271, in run
    daemonize=False)
  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 485, in _proc_function
    return self.low(fun, low, full_return=False)
  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 261, in low
    return self._low(fun, low, print_event=print_event, full_return=full_return)
  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 301, in _low
    self.mminion  # pylint: disable=W0104
  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 243, in mminion
    self._mminion = salt.minion.MasterMinion(self.opts, states=False, rend=False)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 864, in __init__
    role='master'
  File "/usr/lib/python2.7/site-packages/salt/config/__init__.py", line 2386, in minion_config
    apply_sdb(opts)
  File "/usr/lib/python2.7/site-packages/salt/config/__init__.py", line 2532, in apply_sdb
    sdb_opts[key] = apply_sdb(opts, value)
  File "/usr/lib/python2.7/site-packages/salt/config/__init__.py", line 2532, in apply_sdb
    sdb_opts[key] = apply_sdb(opts, value)
  File "/usr/lib/python2.7/site-packages/salt/config/__init__.py", line 2532, in apply_sdb
    sdb_opts[key] = apply_sdb(opts, value)
  File "/usr/lib/python2.7/site-packages/salt/config/__init__.py", line 2526, in apply_sdb
    if isinstance(sdb_opts, six.string_types) and sdb_opts.startswith('sdb://'):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb8 in position 0: ordinal not in range(128)
```
### Probable cause
Inserting some debug output:
```
[WARNING ] TRIPPING OVER 1                                                                               
[WARNING ] TRIPPING OVER {u'connected': False, u'master': u'127.0.0.1'}                                  
[WARNING ] TRIPPING OVER False                                                                                                                                                                                     
[WARNING ] TRIPPING OVER 127.0.0.1                                                                       
[WARNING ] ITSASTRINGBABY                                                                                                                                                                                          
[WARNING ] TRIPPING OVER 90                                                                              
[WARNING ] TRIPPING OVER False                                                                           
[WARNING ] TRIPPING OVER {u'_next_scheduled_fire_time': '\xb820180228T15:56:36.310333', u'function': u'mine.update', u'name': u'__mine_interval', u'enabled': True, u'_splay': None, u'return_job': False, u'_secon
ds': 3600, u'jid_include': True, u'maxrunning': 2, u'_next_fire_time': '\xb820180228T15:55:06.280075', u'minutes': 60}                                                                                             
[ERROR   ] 'ascii' codec can't decode byte 0xb8 in position 0: ordinal not in range(128)                                                                                                                           
Traceback (most recent call last):                                                                       
  File "/usr/lib/python2.7/site-packages/salt/utils/parsers.py", line 209, in parse_args                 
    process_option_func()                                                                                
  File "/usr/lib/python2.7/site-packages/salt/utils/parsers.py", line 547, in process_config_dir                                                                                                                   
    self.config.update(self.setup_config())                                                              
  File "/usr/lib/python2.7/site-packages/salt/utils/parsers.py", line 2719, in setup_config              
    cache_minion_id=True)                                                                                
  File "/usr/lib/python2.7/site-packages/salt/config/__init__.py", line 2386, in minion_config           
    apply_sdb(opts)                                                                                                                                                                                                
  File "/usr/lib/python2.7/site-packages/salt/config/__init__.py", line 2532, in apply_sdb               
    sdb_opts[key] = apply_sdb(opts, value)                                                                                                                                                                         
  File "/usr/lib/python2.7/site-packages/salt/config/__init__.py", line 2532, in apply_sdb               
    sdb_opts[key] = apply_sdb(opts, value)                                                                                                                                                                         
  File "/usr/lib/python2.7/site-packages/salt/config/__init__.py", line 2532, in apply_sdb                                                                                                                         
    sdb_opts[key] = apply_sdb(opts, value)                                                                                                                                                                         
  File "/usr/lib/python2.7/site-packages/salt/config/__init__.py", line 2523, in apply_sdb               
    log.warning('TRIPPING OVER {}'.format(sdb_opts))                                                     
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb8 in position 0: ordinal not in range(128)        
Usage: salt-call [options] <function> [arguments]     
```

Notice however the `.format()` already trips over

### Setup
```
schedule:
  __mine_interval:
    _next_fire_time: !!binary |
      uDIwMTgwMjI4VDE3OjMxOjA1Ljk4MTI4Mg==
    _next_scheduled_fire_time: !!binary |
      uDIwMTgwMjI4VDE3OjMxOjIzLjk3OTYyNQ==
    _seconds: 3600
    _splay: null
    enabled: true
    function: mine.update
    jid_include: true
    maxrunning: 2
    minutes: 60
    name: __mine_interval
    return_job: false
```

### Steps to Reproduce Issue
have some items destined for the mine, run `mine.update`

### Versions Report
```
[root@hanzo ~]# salt --versions-report
Salt Version:
           Salt: 2018.3.0-242-gbf095c9
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: Not Installed
       dateutil: 2.6.0
      docker-py: 3.0.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: 0.26.0
        libnacl: Not Installed
       M2Crypto: 0.25.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.3
         Python: 2.7.14 (default, Feb 17 2018, 10:42:17)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.1.6
 
System Versions:
           dist: fedora 27 Twenty Seven
         locale: UTF-8
        machine: x86_64
        release: 4.15.3-300.fc27.x86_64
         system: Linux
        version: Fedora 27 Twenty Seven
```

**Comment by rallytime** [comment]
This looks similar to #46202

**Comment by gtmanfred** [comment]
Looks like this is a duplicate, and sounds like we have a fix for it that is going to be opened today.

Thanks!
Daniel
