### ISSUE TITLE
Salt-ssh error when wrong password in roster file

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#46283]
### Description of Issue/Question
In 2018.3.0rc1 when putting a wrong password in the roster file when running salt-ssh it gives Error/Traceback. See this on both py2 and py3 setup.
I get permission denied which is correct but I also see this:
```
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: 'str' object does not support item assignment
Traceback (most recent call last):
  File "/usr/bin/salt-ssh", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/root/salt/scripts/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/root/salt/salt/scripts.py", line 425, in salt_ssh
    client.run()
  File "/root/salt/salt/cli/ssh.py", line 24, in run
    ssh.run()
  File "/root/salt/salt/client/ssh/__init__.py", line 776, in run
    data['id'] = id_
TypeError: 'str' object does not support item assignment
```
### Setup
Salt-ssh setup with wrong password.

py2 error:
```
Password for root@ssh: 
ssh:
    Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: 'unicode' object does not support item assignment
Traceback (most recent call last):
  File "/usr/bin/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 425, in salt_ssh
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/ssh.py", line 24, in run
    ssh.run()
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 776, in run
    data['id'] = id_
TypeError: 'unicode' object does not support item assignment
```
py3 error:
```
Password for root@ssh: 
ssh:
    Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: 'str' object does not support item assignment
Traceback (most recent call last):
  File "/usr/bin/salt-ssh", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/root/salt/scripts/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/root/salt/salt/scripts.py", line 425, in salt_ssh
    client.run()
  File "/root/salt/salt/cli/ssh.py", line 24, in run
    ssh.run()
  File "/root/salt/salt/client/ssh/__init__.py", line 776, in run
    data['id'] = id_
TypeError: 'str' object does not support item assignment
```

### Versions Report
py2:
```
Salt Version:
           Salt: 2018.3.0-n/a-f3e9e82
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

py3:
```
Salt Version:
           Salt: 2018.3.0-2076-gf3e9e82
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.4
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.4.5 (default, Dec 11 2017, 14:22:24)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.6
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
 ```

**Comment by frogunder** [comment]
Working correctly with the fix, thanks @gtmanfred

**Comment by rallytime** [comment]
You guys are awesome! I'll close this.
