### ISSUE TITLE
debconf module fails on Python 3

### ISSUE THREAD

**Issue by gclinch** [saltstack/salt#46299]
### Description of Issue/Question
debconfmod.set under Python 3 fails with **TypeError: a bytes-like object is required, not 'str'**, because a string (and not bytes) is passed to os.write.

### Steps to Reproduce Issue
```
# salt-call -l debug debconf.set testpkg question string value
[...]
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded debconf.set

Passed invalid arguments: a bytes-like object is required, not 'str'.

Usage:

    Set answers to debconf questions for a package.

    CLI Example:

    .. code-block:: bash

        salt '*' debconf.set <package> <question> <type> <value> [<value> ...]
    
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 204, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/modules/debconfmod.py", line 130, in set_
    os.write(fd_, line)
TypeError: a bytes-like object is required, not 'str'
```

### Versions Report
```
# salt-call --versions-report
Salt Version:
           Salt: 2017.7.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.4
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.4+ (default, Feb 12 2018, 08:25:03)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.3
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-10-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```

**Comment by jagguli** [comment]
same issue with haproxycon

```    Passed invalid arguments to haproxy.disable_server: a bytes-like object is required, not 'str'

        Disable server in haproxy.

        name
            Server to disable

        backend
            haproxy backend, or all backends if "*" is supplied

        socket
            haproxy stats socket, default ``/var/run/haproxy.sock``

        CLI Example:

        .. code-block:: bash

            salt '*' haproxy.disable_server db1.example.com mysql
```
