### ISSUE TITLE
salt-cloud and winrm failing with : InvalidCredentialsError: the specified credentials were rejected by the server

### ISSUE THREAD

**Issue by Giandom** [saltstack/salt#46305]
### Description of Issue/Question
Trying to create a Windows Minion in Google Compute Engine results in the following error:
```
[ERROR   ] There was a profile error: the specified credentials were rejected by the server
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/cli.py", line 285, in run
    self.config.get('names')
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1448, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1278, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/gce.py", line 2585, in create
    ret = __utils__['cloud.bootstrap'](vm_, __opts__)
  File "/usr/lib/python2.7/site-packages/salt/utils/cloud.py", line 548, in bootstrap
    deployed = deploy_windows(**deploy_kwargs)
  File "/usr/lib/python2.7/site-packages/salt/utils/cloud.py", line 1033, in deploy_windows
    timeout=port_timeout * 60, use_ssl=winrm_use_ssl)
  File "/usr/lib/python2.7/site-packages/salt/utils/cloud.py", line 863, in wait_for_winrm
    r = s.run_cmd('sc query winrm')
  File "/usr/lib/python2.7/site-packages/winrm/__init__.py", line 37, in run_cmd
    shell_id = self.protocol.open_shell()
  File "/usr/lib/python2.7/site-packages/winrm/protocol.py", line 157, in open_shell
    res = self.send_message(xmltodict.unparse(req))
  File "/usr/lib/python2.7/site-packages/winrm/protocol.py", line 234, in send_message
    resp = self.transport.send_message(message)
  File "/usr/lib/python2.7/site-packages/winrm/transport.py", line 256, in send_message
    response = self._send_message_request(prepared_request, message)
  File "/usr/lib/python2.7/site-packages/winrm/transport.py", line 266, in _send_message_request
    raise InvalidCredentialsError("the specified credentials were rejected by the server")
InvalidCredentialsError: the specified credentials were rejected by the server
```

### Setup
```
myvm:
  image: https://www.googleapis.com/compute/v1/projects/windows-sql-cloud/global/images/sql-2017-express-windows-2012-r2-dc-v20180213
  size: n1-highmem-2
  location: europe-west1-d
  network: default
  use_persistent_disk: True
  delete_boot_pd: False
  deploy: True
  make_master: False
  external_ip: "ephemeral"
  metadata: '{"sysprep-specialize-script-ps1": "New-NetFirewallRule -Name "SMB445" -DisplayName "SMB445" -Protocol TCP -LocalPort 445","sysprep-specialize-script-ps1": "Set-Item (dir wsman:\localhost\Listener\*\Port -Recurse).pspath 445 -Force","sysprep-specialize-script-ps1": "Restart-Service winrm"}'
  keyname: mykey
  ssh_keyfile: /root/.ssh/id_rsa
  win_installer: /srv/salt/win/Salt-Minion-2017.7.4-Py2-AMD64-Setup.exe
  win_username: Administrator
  win_password: auto
  plain_text: True
  smb_port: 445
  use_winrm: True
  winrm_verify_ssl: False
  provider: gce-config
```

### Steps to Reproduce Issue
```
salt-cloud -l debug -p myvm test01
```
This will run until the aforementioned error is produced.

### Versions Report
```
Salt Version:
           Salt: 2017.7.4
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.17.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```
Any advices?

**Comment by garethgreenaway** [comment]
@gtmanfred Looks like you've touched this particular code recently, any thoughts on what might be happening here?

**Comment by gtmanfred** [comment]
I think this is specifically an ec2 thing 

```
  win_password: auto
```

I am not sure how to do with with GCE + windows.

https://github.com/saltstack/salt/blob/2017.7/salt/cloud/clouds/ec2.py#L2340

With a brief look at the code, it doesn't look like we handle the `reset-windows-password` command for gce, so that would need to be added to build windows machines on gce.
