### ISSUE TITLE
test_create_deployments fails with python-kubernetes 4.0.0

### ISSUE THREAD

**Issue by bdrung** [saltstack/salt#46329]
The test_create_deployments test case from salt 2017.7.4 fails with python-kubernetes 4.0.0. Tested on Debian unstable.

```
ERROR: test_create_deployments (unit.modules.test_kubernetes.KubernetesTestCase)
[CPU:0.0%|MEM:45.1%] 
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<BUILDDIR>>/salt-2017.7.4+dfsg1/tests/unit/modules/test_kubernetes.py", line 123, in test_create_deployments
    None, None, None), {})
  File "/<<BUILDDIR>>/salt-2017.7.4+dfsg1/salt/modules/kubernetes.py", line 936, in create_deployment
    saltenv=saltenv)
  File "/<<BUILDDIR>>/salt-2017.7.4+dfsg1/salt/modules/kubernetes.py", line 1392, in __create_object_body
    spec=spec_creator(spec))
  File "/<<BUILDDIR>>/salt-2017.7.4+dfsg1/salt/modules/kubernetes.py", line 1464, in __dict_to_deployment_spec
    spec_obj = AppsV1beta1DeploymentSpec()
  File "/usr/lib/python3/dist-packages/kubernetes/client/models/apps_v1beta1_deployment_spec.py", line 89, in __init__
    self.template = template
  File "/usr/lib/python3/dist-packages/kubernetes/client/models/apps_v1beta1_deployment_spec.py", line 296, in template
    raise ValueError("Invalid value for `template`, must not be `None`")
ValueError: Invalid value for `template`, must not be `None`
```

**Comment by rallytime** [comment]
This is related to #44701
