### ISSUE TITLE
Salt package on FreeBSD does not depend on SQLite Python package

### ISSUE THREAD

**Issue by oogali** [saltstack/salt#46324]
### Description of Issue/Question

The `py27-salt` package on FreeBSD does not require the SQLite Python module (`py27-sqlite3`).

As a result, anything requiring SQLite support fails. In this instance, `spm`.

### Setup

The setup consists of a directory, containing a single `.spm` package that was built.

### Steps to Reproduce Issue

```
vanilla:/data/web/spm # spm create_repo /data/web/spm
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
KeyError: 'sqlite3.init'
Traceback (most recent call last):
  File "/usr/local/bin/spm", line 11, in <module>
    load_entry_point('salt==2017.7.3', 'console_scripts', 'spm')()
  File "/usr/local/lib/python2.7/site-packages/salt/scripts.py", line 487, in salt_spm
    spm.run()
  File "/usr/local/lib/python2.7/site-packages/salt/cli/spm.py", line 40, in run
    client = salt.spm.SPMClient(ui, self.config)
  File "/usr/local/lib/python2.7/site-packages/salt/spm/__init__.py", line 97, in __init__
    self._init()
  File "/usr/local/lib/python2.7/site-packages/salt/spm/__init__.py", line 106, in _init
    self.db_conn = self._pkgdb_fun('init')
  File "/usr/local/lib/python2.7/site-packages/salt/spm/__init__.py", line 144, in _pkgdb_fun
    return self.pkgdb['{0}.{1}'.format(self.db_prov, func)](*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/salt/loader.py", line 1114, in __getitem__
    func = super(LazyLoader, self).__getitem__(item)
  File "/usr/local/lib/python2.7/site-packages/salt/utils/lazy.py", line 98, in __getitem__
    return self._dict[key]
KeyError: 'sqlite3.init'
Traceback (most recent call last):
  File "/usr/local/bin/spm", line 11, in <module>
    load_entry_point('salt==2017.7.3', 'console_scripts', 'spm')()
  File "/usr/local/lib/python2.7/site-packages/salt/scripts.py", line 487, in salt_spm
    spm.run()
  File "/usr/local/lib/python2.7/site-packages/salt/cli/spm.py", line 40, in run
    client = salt.spm.SPMClient(ui, self.config)
  File "/usr/local/lib/python2.7/site-packages/salt/spm/__init__.py", line 97, in __init__
    self._init()
  File "/usr/local/lib/python2.7/site-packages/salt/spm/__init__.py", line 106, in _init
    self.db_conn = self._pkgdb_fun('init')
  File "/usr/local/lib/python2.7/site-packages/salt/spm/__init__.py", line 144, in _pkgdb_fun
    return self.pkgdb['{0}.{1}'.format(self.db_prov, func)](*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/salt/loader.py", line 1114, in __getitem__
    func = super(LazyLoader, self).__getitem__(item)
  File "/usr/local/lib/python2.7/site-packages/salt/utils/lazy.py", line 98, in __getitem__
    return self._dict[key]
KeyError: 'sqlite3.init'
```

After installing `py27-sqlite3`, I no longer have issues with `spm`.

```
vanilla:/data/web/spm # pkg install py27-sqlite3
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
The following 1 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
	py27-sqlite3: 2.7.14_7

Number of packages to be installed: 1

28 KiB to be downloaded.

Proceed with this action? [y/N]: y
[1/1] Fetching py27-sqlite3-2.7.14_7.txz: 100%   28 KiB  29.0kB/s    00:01
Checking integrity... done (0 conflicting)
[1/1] Installing py27-sqlite3-2.7.14_7...
Extracting py27-sqlite3-2.7.14_7: 100%

vanilla:/data/web/spm # spm create_repo /data/web/spm
vanilla:/data/web/spm #
```

### Versions Report

```
vanilla:/data/web/spm # spm --versions
Salt Version:
           Salt: 2017.7.3

Dependency Versions:
           cffi: 1.7.0
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.11 (default, Dec 31 2015, 03:42:15)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.2.2

System Versions:
           dist:
         locale: US-ASCII
        machine: amd64
        release: 11.1-RELEASE-p1
         system: FreeBSD
        version: Not Installed
```

**Comment by gtmanfred** [comment]
@cedwards can you take a look at this?

Thanks,
Daniel

**Comment by cedwards** [comment]
Hi. Always happy to help with FreeBSD support.

@oogali - Thanks for submitting the bug. I'm glad to see you got things working by adding the sqlite3 dependency.

The problem here, however, is more complex than just adding py-sqlite3 to the dependencies list.

Salt now has over 500 execution modules.
Many of these modules also require python libraries or other utilities.

I've had to make the decision when packaging Salt to limit the dependencies to the absolute _base_ requirements. Otherwise, the package would grow far too big.

Unless someone can provide a good argument for why SPM support should be considered a _base_ requirement beyond that of any other execution module, I would prefer not to add dependencies to the package.

**Comment by oogali** [comment]
This is different than an execution module (e.g. `mysql`, `postgresql`, etc). This is more akin to requiring me to install OpenSSH as an undocumented dependency in `salt-ssh`.

If SPM ships as part of the base package (e.g. `salt-common` on Ubuntu, or `py27-salt` on FreeBSD), then I believe its dependency (just one: `py27-sqlite3`), should be included.

**Comment by gtmanfred** [comment]
Actually, it isn't that different, because what you are actually seeing the error in is the pkgdb module for spm, which is just another loader and could be marked as a backend.

What should probably happen is the sqlite module for the pkgdb and pkgfiles subsystem should have `__virtual__` added and an error message about needing the sqlite3 module.

**Comment by gtmanfred** [comment]
I will add that to my list.

**Comment by oogali** [comment]
@gtmanfred Ah, thanks for the clarification.
