### ISSUE TITLE
[2018.3.0rc1] Stacktrace on call to nacl.dec

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#46334]
### Description of Issue/Question
```
2018-03-05 18:47:44,563 [salt.pillar                                                 :732 ][CRITICAL][339999] Rendering SLS 'common.account' failed, render error:
Traceback (most recent call last):
  File "/opt/local/lib/python2.7/site-packages/salt/utils/templates.py", line 553, in py
    data = mod.run()
  File "/salt/pillar/common/account/init.sls", line 121, in run
    'password': __salt__['shadow.gen_password'](__salt__['nacl.dec'](data=user['password'], key=nacl['db']), 'BLBnVC', 'sha256') if user['password'] else None,
  File "/opt/local/lib/python2.7/site-packages/salt/modules/nacl.py", line 365, in dec
    return sealedbox_decrypt(data, **kwargs)
  File "/opt/local/lib/python2.7/site-packages/salt/modules/nacl.py", line 436, in sealedbox_decrypt
    sk = _get_sk(**kwargs)
  File "/opt/local/lib/python2.7/site-packages/salt/modules/nacl.py", line 213, in _get_sk
    with salt.utils.files.fopen(sk_file, 'rb') as keyf:
  File "/opt/local/lib/python2.7/site-packages/salt/utils/files.py", line 366, in fopen
    f_handle = open(*args, **kwargs)  # pylint: disable=resource-leakage
IOError: [Errno 2] No such file or directory: u'/etc/salt/pki/master/nacl'
```
### Setup
I call nacl.dec from the __salt__ dict inside a pillar.

```__salt__['nacl.dec'](data=user['password'], key=nacl['db'])```
where user['password'] hold the encrypted password and nacl['db'] holds the key.

This is using the pyrendered as I pull this data from a database, it works fine on 2017.7.4 and has been working fine since somewhere 2016.x at least.

Which is interesting is the path it cannot find: ```/etc/salt/pki/master/nacl```
My salt package etc is /opt/local/etc/salt. looks like ```salt.modules.nacl._get_config``` has this hardcoded! Those should probably be updates to be relative to whatever pki dir is configured!

### Steps to Reproduce Issue
Call ```__salt__['nacl.dec']``` from a pillar.

### Versions Report
```
cronos# salt-call --versions-report
Salt Version:
           Salt: 2018.3.0rc1

Dependency Versions:
           cffi: 1.9.1
       cherrypy: 8.1.0
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: 1.7.4
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: 0.22
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Jan 26 2017, 18:07:59)
   python-gnupg: 2.3.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: 0.6.8
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.3
            ZMQ: 4.1.4

System Versions:
           dist:
         locale: UTF-8
        machine: i86pc
        release: 5.11
         system: SunOS
        version: Not Installed
```

**Comment by sjorge** [comment]
Here is a partial patch, this fixes the wrong pki_dir issue.

```patch
cronos# diff -u modules/nacl.py{,.orig}
--- modules/nacl.py        2018-03-05 19:03:11.309766240 +0000
+++ modules/nacl.py.orig        2018-03-05 19:00:06.868385009 +0000
@@ -186,9 +186,9 @@
     config = {
         'box_type': 'sealedbox',
         'sk': None,
-        'sk_file': os.path.join(__opts__['pki_dir'], 'master/nacl'),
+        'sk_file': '/etc/salt/pki/master/nacl',
         'pk': None,
-        'pk_file': os.path.join(__opts__['pki_dir'], '/master/nacl.pub'),
+        'pk_file': '/etc/salt/pki/master/nacl.pub',
     }
     config_key = '{0}.config'.format(__virtualname__)
     try:
```

I'm not near my usual setup so I can't do a proper PR for this.

**Comment by sjorge** [comment]
This was done on 2017.7.4
```
[isotope :: sjorge][~]
[.]$ salt-run nacl.keygen
rr38jF4vwW10mkhA90wBFREUpquyfKnc27KKnNgtPHI=
[isotope :: sjorge][~]
[.]$ salt-run nacl.enc hello key='rr38jF4vwW10mkhA90wBFREUpquyfKnc27KKnNgtPHI='
w1z8Yhz3p4KAXmxZ4VvpGwyCmhDXEIJoJUt/iCO3INEi74AVC5x3w/zY3CZZ
[isotope :: sjorge][~]
[.]$ salt-run nacl.dec w1z8Yhz3p4KAXmxZ4VvpGwyCmhDXEIJoJUt/iCO3INEi74AVC5x3w/zY3CZZ key='rr38jF4vwW10mkhA90wBFREUpquyfKnc27KKnNgtPHI='
hello
[isotope :: sjorge][~]
[.]$ salt --versions-report
Salt Version:
           Salt: 2017.7.4

Dependency Versions:
           cffi: 1.10.0
       cherrypy: unknown
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: 1.7.4
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: 0.26.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jul  4 2017, 00:21:04)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: 0.6.8
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.2.1

System Versions:
           dist:
         locale: UTF-8
        machine: i86pc
        release: 5.11
         system: SunOS
        version: Not Installed

```

This no longer works on 2018.0rc1... so aside from the issues mentioned about with the harcoded paths and the unhelpful stacktrace a fix for this or atleast a mention in the release notes about the old stuff no longer working should be mentioned.

**Comment by sjorge** [comment]
Issues found so far:
- [ ] stacktrace in master log when sk_file or pk_file do not exists
- [ ] the sk_file/pk_file defaults use a hardcoded pki_dir of /etc/salt/pki (patches above to fix)
- [ ] releasenotes are missing info about this change
- [ ] salt.runners.nacl doc has a lot of references to ```salt-call --local nacl.XXX``` those should probabt be ```salt-run``` instead.

**Comment by garethgreenaway** [comment]
Found the root cause.  More fun with unicode.  Have a fix in progress, which incorporates the changes by @sjorge above.  Just need to add some tests.
