### ISSUE TITLE
Saltstack zabbix module not working

### ISSUE THREAD

**Issue by angeloudy** [saltstack/salt#46384]
I got an error when trying to add a host to zabbix using zabbix state. 

```
    Function: zabbix_host.present
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/local/lib/python3.6/site-packages/salt/state.py", line 1851, in call
                  **cdata['kwargs'])
                File "/usr/local/lib/python3.6/site-packages/salt/loader.py", line 1795, in wrapper
                  return f(*args, **kwargs)
                File "/usr/local/lib/python3.6/site-packages/salt/states/zabbix_host.py", line 175, in present
                  host_exists = __salt__['zabbix.host_exists'](host, **connection_args)
                File "/usr/local/lib/python3.6/site-packages/salt/modules/zabbix.py", line 933, in host_exists
                  conn_args = _login(**connection_args)
                File "/usr/local/lib/python3.6/site-packages/salt/modules/zabbix.py", line 164, in _login
                  ret = _query(method, params, connargs['url'])
                File "/usr/local/lib/python3.6/site-packages/salt/modules/zabbix.py", line 106, in _query
                  decode=True,)
                File "/usr/local/lib/python3.6/site-packages/salt/utils/http.py", line 613, in query
                  ret['dict'] = json.loads(salt.utils.to_str(result_text))
                File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
                  return _default_decoder.decode(s)
                File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
                  obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
                  raise JSONDecodeError("Expecting value", s, err.value) from None
              json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
     Started: 14:37:56.220124
    Duration: 142.203 ms
     Changes:
```

OS: FreeBSD 11

Salt Version:
           Salt: 2017.7.3

Dependency Versions:
           cffi: 1.7.0
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.3.12
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.4 (default, Dec 22 2017, 17:21:16)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.2.2

System Versions:
           dist:
         locale: UTF-8
        machine: amd64
        release: 11.1-RELEASE-p4
         system: FreeBSD
        version: Not Installed

**Comment by Ch3LL** [comment]
was this previously working and if so what version?

Also can you share a sanitized version of the state you are using?

**Comment by angeloudy** [comment]
This was because I used wrong API url.
