### ISSUE TITLE
Py3 errors in zmq and msgpack on 2017.7.4

### ISSUE THREAD

**Issue by max-orhai** [saltstack/salt#46407]
### Description of Issue/Question

I'd like to use Python 3, but I encounter this `DeprecationWarning` (and worse, the dreaded `UnicodeDecodeError`) arising from our use of the pyzmq and msgpack-python packaged libraries. Pip says all my dependencies are met.

### Setup
I'm using the latest PyPI release of Salt, with its dependencies, on an Ubuntu 16.04 VM in EC2.

### Steps to Reproduce Issue
```
ubuntu@ip-XXXXX:~$ sudo python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from salt.client import LocalClient
>>> lc = LocalClient()
>>> lc.cmd('*', 'cmd.run', ['whoami'])
/home/ubuntu/.local/lib/python3.5/site-packages/salt/utils/async.py:56: DeprecationWarning: zmq.eventloop.ioloop is deprecated in pyzmq 17. pyzmq now works with default tornado and asyncio eventloops.
  self.io_loop = LOOP_CLASS()
Traceback (most recent call last):
  File "msgpack/_unpacker.pyx", line 453, in msgpack._unpacker.Unpacker._unpack
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 22: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.5/site-packages/salt/client/__init__.py", line 735, in cmd
    **kwargs):
  File "/home/ubuntu/.local/lib/python3.5/site-packages/salt/client/__init__.py", line 1589, in get_cli_event_returns
    **kwargs
  File "/home/ubuntu/.local/lib/python3.5/site-packages/salt/client/__init__.py", line 1174, in get_iter_returns
    for raw in ret_iter:
  File "/home/ubuntu/.local/lib/python3.5/site-packages/salt/client/__init__.py", line 1099, in get_returns_no_block
    no_block=True, auto_reconnect=self.auto_reconnect)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/salt/utils/event.py", line 640, in get_event
    ret = self._get_event(wait, tag, match_func, no_block)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/salt/utils/event.py", line 540, in _get_event
    raw = self.subscriber.read_sync(timeout=wait)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/salt/transport/ipc.py", line 705, in read_sync
    return ret_future.result()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/ubuntu/.local/lib/python3.5/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/salt/transport/ipc.py", line 681, in _read_sync
    raise exc_to_raise  # pylint: disable=E0702
  File "/home/ubuntu/.local/lib/python3.5/site-packages/salt/transport/ipc.py", line 653, in _read_sync
    for framed_msg in self.unpacker:
  File "msgpack/_unpacker.pyx", line 528, in msgpack._unpacker.Unpacker.__next__
  File "msgpack/_unpacker.pyx", line 473, in msgpack._unpacker.Unpacker._unpack
msgpack.exceptions.UnpackValueError: 'utf-8' codec can't decode byte 0x82 in position 22: invalid start byte
```

### Versions Report
```
Salt Version:
           Salt: 2017.7.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.5
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.2 (default, Nov 23 2017, 16:37:01)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.6
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-1052-aws
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by terminalmage** [comment]
The 2018.3.0 release, which we just released a release candidate for on Monday, contains a lot of work improving unicode support.

The deprecation warning is due to changes new to the pyzmq 17.0.0 release, if you downgrade pyzmq to a pre-17.0.0 release, it will go away.

The 2018.3.0 release will also get rid of the deprecation warning by handling the IOLoop in the way pyzmq >= 17.0.0 expects.

**Comment by terminalmage** [comment]
I just checked, and the release candidate is on PyPI, it's just not the default release at this time. You can install it using `pip3 install 'salt==2018.3.0rc1'`.

**Comment by max-orhai** [comment]
I just installed 2018.3.0rc1 from PyPI as you suggest, and get what appears to be the same error from `msgpack`:

```
root@ip-172-31-27-77:/home/ubuntu# python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from salt.client import LocalClient
>>> lc = LocalClient()
>>> lc.cmd('*', 'cmd.run', ['whoami'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/salt/client/__init__.py", line 741, in cmd
    **kwargs):
  File "/usr/local/lib/python3.5/dist-packages/salt/client/__init__.py", line 1603, in get_cli_event_returns
    **kwargs
  File "/usr/local/lib/python3.5/dist-packages/salt/client/__init__.py", line 1184, in get_iter_returns
    for raw in ret_iter:
  File "/usr/local/lib/python3.5/dist-packages/salt/client/__init__.py", line 1109, in get_returns_no_block
    no_block=True, auto_reconnect=self.auto_reconnect)
  File "/usr/local/lib/python3.5/dist-packages/salt/utils/event.py", line 642, in get_event
    ret = self._get_event(wait, tag, match_func, no_block)
  File "/usr/local/lib/python3.5/dist-packages/salt/utils/event.py", line 541, in _get_event
    raw = self.subscriber.read_sync(timeout=wait)
  File "/usr/local/lib/python3.5/dist-packages/salt/transport/ipc.py", line 709, in read_sync
    return ret_future.result()
  File "/usr/local/lib/python3.5/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python3.5/dist-packages/salt/transport/ipc.py", line 685, in _read_sync
    raise exc_to_raise  # pylint: disable=E0702
  File "/usr/local/lib/python3.5/dist-packages/salt/transport/ipc.py", line 657, in _read_sync
    for framed_msg in self.unpacker:
  File "/usr/local/lib/python3.5/dist-packages/msgpack/fallback.py", line 626, in __next__
    ret = self._unpack(EX_CONSTRUCT)
  File "/usr/local/lib/python3.5/dist-packages/msgpack/fallback.py", line 600, in _unpack
    ret[key] = self._unpack(EX_CONSTRUCT)
  File "/usr/local/lib/python3.5/dist-packages/msgpack/fallback.py", line 608, in _unpack
    obj = obj.decode(self._encoding, self._unicode_errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 22: invalid start byte
```

**Comment by max-orhai** [comment]
D'oh! My master instance's systemd had been trying to start `/usr/bin/salt-master` which no longer exists since I removed the Ubuntu package. I just had to override that config to use `/usr/local/bin/salt-master`, as installed by `pip`. Everything seems to work fine now.

Thanks for the hint!

**Comment by terminalmage** [comment]
No problem!
