### ISSUE TITLE
RVM state doesn't work with ubuntu 18.04 bionic beaver

### ISSUE THREAD

**Issue by Rumbles** [saltstack/salt#46414]
### Description of Issue/Question

I know it's still in beta, but I am trying to set up an 18.04 beta box to test some things for future use. I hit a few issues when I tried to set up rvm on my new machine.

### Setup
When using this example:

https://docs.saltstack.com/en/latest/ref/states/all/salt.states.rvm.html

I found that there is no libreadline6 or libreadline6-dev in bionic beaver as noted here:

https://github.com/rvm/rvm/issues/3824

Looking at what is available libreadline7 and libreadline-dev are available and seem to be a replacement. But when I tried using those packages instead of the ones listed in the docs, rvm still didn't install.

I got this error:

```
         ID: ruby-2.4.3                                                                  
    Function: rvm.installed                                                               
      Result: False                                                                       
     Comment: An exception occurred in this state: Traceback (most recent call last):     
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1851, in call 
                  **cdata['kwargs'])                                                      
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1795, in wrapper                                                                                        
                  return f(*args, **kwargs)                                               
                File "/usr/lib/python2.7/dist-packages/salt/states/rvm.py", line 193, in installed                                                                                   
                  if not __salt__['rvm.install'](runas=user):                             
                File "/usr/lib/python2.7/dist-packages/salt/modules/rvm.py", line 103, in install                                                                                    
                  raise CommandExecutionError(msg)                                        
              CommandExecutionError: Error encountered while downloading the RVM installer. stderr follows:                                                                          
                                                                                          
              gpg: Signature made Sun Sep 10 20:59:21 2017 UTC                            
              gpg:                using RSA key E206C29FBF04FF17                          
              gpg: Can't check signature: No public key                                   
     Started: 10:44:39.219208                                                             
    Duration: 3049.902 ms                                                                 
     Changes:         
``` 

### Steps to Reproduce Issue
Install ubuntu 18.04 bionic beaver beta and try to salt rvm on it.

### Versions Report
Master:
```
$ salt --versions-report
Salt Version:
           Salt: 2017.7.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Nov 23 2017, 15:49:48)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
         locale: UTF-8
        machine: x86_64
        release: 3.13.0-107-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```
 

Minion (installed from the xenial repo as no release available for bionic yet):
```
$ salt-minion --versions-report               
Salt Version:                                 
           Salt: 2017.7.4                     
                                              
Dependency Versions:                          
           cffi: 1.11.5                       
       cherrypy: Not Installed                
       dateutil: 2.6.1                        
      docker-py: Not Installed                
          gitdb: Not Installed                
      gitpython: Not Installed                
          ioflo: Not Installed                
         Jinja2: 2.10                         
        libgit2: Not Installed                
        libnacl: Not Installed                
       M2Crypto: Not Installed                
           Mako: 1.0.7                        
   msgpack-pure: Not Installed                
 msgpack-python: 0.5.4                        
   mysql-python: Not Installed                
      pycparser: 2.18                         
       pycrypto: 2.6.1                        
   pycryptodome: Not Installed                
         pygit2: Not Installed                
         Python: 2.7.14+ (default, Feb  6 2018, 19:12:18)                                   
   python-gnupg: Not Installed                
         PyYAML: 3.12                         
          PyZMQ: 16.0.2                       
           RAET: Not Installed                
          smmap: Not Installed                
        timelib: Not Installed                
        Tornado: 4.5.3                        
            ZMQ: 4.2.3                        
                                              
System Versions:                              
           dist: Ubuntu 18.04 bionic          
         locale: UTF-8                        
        machine: x86_64                       
        release: 4.15.0-10-generic            
         system: Linux                        
        version: Ubuntu 18.04 bionic   
```       
                                              

Apologies if I am jumping the gun, I just thought it best to raise the issue.

**Comment by garethgreenaway** [comment]
@Rumbles Thanks for the report.  Looks like the issue is related to some recent changes to the RVM installer which introduced signed releases.

```
root@272a17094018:/# curl -Ls https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer | bash -s stable
Downloading https://github.com/rvm/rvm/archive/1.29.3.tar.gz
Downloading https://github.com/rvm/rvm/releases/download/1.29.3/1.29.3.tar.gz.asc
gpg: directory '/root/.gnupg' created
gpg: keybox '/root/.gnupg/pubring.kbx' created
gpg: Signature made Sun Sep 10 20:59:21 2017 UTC
gpg:                using RSA key E206C29FBF04FF17
gpg: Can't check signature: No public key
Warning, RVM 1.26.0 introduces signed releases and automated check of signatures when GPG software found. Assuming you trust Michal Papis import the mpapis public key (downloading the signatures).

GPG signature verification failed for '/usr/local/rvm/archives/rvm-1.29.3.tgz' - 'https://github.com/rvm/rvm/releases/download/1.29.3/1.29.3.tar.gz.asc'! Try to install GPG v2 and then fetch the public key:

    gpg2 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

or if it fails:

    command curl -sSL https://rvm.io/mpapis.asc | gpg --import -

the key can be compared with:

    https://rvm.io/mpapis.asc
    https://keybase.io/mpapis

NOTE: GPG version 2.1.17 have a bug which cause failures during fetching keys from remote server. Please downgrade or upgrade to newer version (if available) or use the second method described above.

```

**Comment by Rumbles** [comment]
Thanks for clarifying the issue, I wasn't sure how this state worked under the hood (and didn't have time to read how it worked I'm afraid). Since there appears to be 2 issues here (Missing packages in ubuntu 18.06: libreadline6 and libreadline6-dev, as well as a change in how rvm installation works) should I raise a separate issue to have the documentation updated? Or do you think salt should handle the dependencies internally now, depending on which OS you are running?

**Comment by maxence33** [comment]
Hi, I do have the same problem installing RVM on Ubuntu 18.04 because of libreadline6 missing package. Is there a fix already ? ( I am pretty noob with Ubuntu but still have another install of 17.10 on a second HD with RVM installed so not really a problem though )
