### ISSUE TITLE
[2018.3.0rc1] Errors/Warnings in Windows packages 

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#46425]
### Description of Issue/Question
I see Errors/Warnings in the Windows packages for 2018.3.0rc1.

I see this in Win 2012, 2016, 8.1, and 10
```
    [ERROR   ] Exception raised when processing __virtual__ function for salt.loaded.int.module.win_snmp. Module will not be loaded: expected str or bytearray
    [WARNING ] salt.loaded.int.module.win_snmp.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'win_snmp', please fix this.
    [WARNING ] C:\salt\bin\lib\site-packages\salt\modules\win_update.py:92: DeprecationWarning: The 'win_update' module is being deprecated and will be removed in Salt Fluorine (Unreleased). Please use the 'win_wua' module instead.
```
I see this in Win 7 and 2008
```
    [ERROR   ] Command 'try {Get-WmiObject -ErrorAction Stop -class MSFC_FibrePortHBAAttributes -namespace "root\WMI" | Select -Expandproperty Attributes | %{($_.PortWWN | % {"{0:x2}" -f $_}) -join ""} | ConvertTo-JSON} catch { "{}" | ConvertTo-JSON}' failed with return code: 1
    [ERROR   ] output: The term 'ConvertTo-JSON' is not recognized as the name of a cmdlet, function, 
    
    script file, or operable program. Check the spelling of the name, or if a path 
    
    was included, verify that the path is correct and try again.
    
    At line:1 char:226
    
    + try {Get-WmiObject -ErrorAction Stop -class MSFC_FibrePortHBAAttributes -name
    
    space "root\WMI" | Select -Expandproperty Attributes | %{($_.PortWWN | % {"{0:x
    
    2}" -f $_}) -join ""} | ConvertTo-JSON} catch { "{}" | ConvertTo-JSON <<<< }
    
        + CategoryInfo          : ObjectNotFound: (ConvertTo-JSON:String) [], Comm 
    
       andNotFoundException
    
        + FullyQualifiedErrorId : CommandNotFoundException
    [ERROR   ] Error converting PowerShell JSON return
    Traceback (most recent call last):
      File "C:\salt\bin\lib\site-packages\salt\modules\cmdmod.py", line 3233, in powershell
        return salt.utils.json.loads(response)
      File "C:\salt\bin\lib\site-packages\salt\utils\json.py", line 78, in loads
        return json_module.loads(s, **kwargs)
      File "C:\salt\bin\lib\json\__init__.py", line 339, in loads
        return _default_decoder.decode(s)
      File "C:\salt\bin\lib\json\decoder.py", line 364, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "C:\salt\bin\lib\json\decoder.py", line 382, in raw_decode
        raise ValueError("No JSON object could be decoded")
    ValueError: No JSON object could be decoded
    [ERROR   ] Exception raised when processing __virtual__ function for salt.loaded.int.module.win_snmp. Module will not be loaded: expected str or bytearray
    [WARNING ] salt.loaded.int.module.win_snmp.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'win_snmp', please fix this.
    [WARNING ] C:\salt\bin\lib\site-packages\salt\modules\win_update.py:92: DeprecationWarning: The 'win_update' module is being deprecated and will be removed in Salt Fluorine (Unreleased). Please use the 'win_wua' module instead.
```

### Steps to Reproduce Issue
salt \* cmd.run "C://salt/salt-call --local sys.doc none"

```
[root@localhost ~]# salt \* cmd.run "C://salt/salt-call --local sys.doc none"
win2012:
    [ERROR   ] Exception raised when processing __virtual__ function for salt.loaded.int.module.win_snmp. Module will not be loaded: expected str or bytearray
    [WARNING ] salt.loaded.int.module.win_snmp.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'win_snmp', please fix this.
    [WARNING ] C:\salt\bin\lib\site-packages\salt\modules\win_update.py:92: DeprecationWarning: The 'win_update' module is being deprecated and will be removed in Salt Fluorine (Unreleased). Please use the 'win_wua' module instead.
    
    local:
        ----------
win2008:
    [ERROR   ] Command 'try {Get-WmiObject -ErrorAction Stop -class MSFC_FibrePortHBAAttributes -namespace "root\WMI" | Select -Expandproperty Attributes | %{($_.PortWWN | % {"{0:x2}" -f $_}) -join ""} | ConvertTo-JSON} catch { "{}" | ConvertTo-JSON}' failed with return code: 1
    [ERROR   ] output: The term 'ConvertTo-JSON' is not recognized as the name of a cmdlet, function, 
    
    script file, or operable program. Check the spelling of the name, or if a path 
    
    was included, verify that the path is correct and try again.
    
    At line:1 char:226
    
    + try {Get-WmiObject -ErrorAction Stop -class MSFC_FibrePortHBAAttributes -name
    
    space "root\WMI" | Select -Expandproperty Attributes | %{($_.PortWWN | % {"{0:x
    
    2}" -f $_}) -join ""} | ConvertTo-JSON} catch { "{}" | ConvertTo-JSON <<<< }
    
        + CategoryInfo          : ObjectNotFound: (ConvertTo-JSON:String) [], Comm 
    
       andNotFoundException
    
        + FullyQualifiedErrorId : CommandNotFoundException
    [ERROR   ] Error converting PowerShell JSON return
    Traceback (most recent call last):
      File "C:\salt\bin\lib\site-packages\salt\modules\cmdmod.py", line 3233, in powershell
        return salt.utils.json.loads(response)
      File "C:\salt\bin\lib\site-packages\salt\utils\json.py", line 78, in loads
        return json_module.loads(s, **kwargs)
      File "C:\salt\bin\lib\json\__init__.py", line 339, in loads
        return _default_decoder.decode(s)
      File "C:\salt\bin\lib\json\decoder.py", line 364, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "C:\salt\bin\lib\json\decoder.py", line 382, in raw_decode
        raise ValueError("No JSON object could be decoded")
    ValueError: No JSON object could be decoded
    [ERROR   ] Exception raised when processing __virtual__ function for salt.loaded.int.module.win_snmp. Module will not be loaded: expected str or bytearray
    [WARNING ] salt.loaded.int.module.win_snmp.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'win_snmp', please fix this.
    [WARNING ] C:\salt\bin\lib\site-packages\salt\modules\win_update.py:92: DeprecationWarning: The 'win_update' module is being deprecated and will be removed in Salt Fluorine (Unreleased). Please use the 'win_wua' module instead.
    
    local:
        ----------
win7:
    [ERROR   ] Command 'try {Get-WmiObject -ErrorAction Stop -class MSFC_FibrePortHBAAttributes -namespace "root\WMI" | Select -Expandproperty Attributes | %{($_.PortWWN | % {"{0:x2}" -f $_}) -join ""} | ConvertTo-JSON} catch { "{}" | ConvertTo-JSON}' failed with return code: 1
    [ERROR   ] output: The term 'ConvertTo-JSON' is not recognized as the name of a cmdlet, function, 
    
    script file, or operable program. Check the spelling of the name, or if a path 
    
    was included, verify that the path is correct and try again.
    
    At line:1 char:226
    
    + try {Get-WmiObject -ErrorAction Stop -class MSFC_FibrePortHBAAttributes -name
    
    space "root\WMI" | Select -Expandproperty Attributes | %{($_.PortWWN | % {"{0:x
    
    2}" -f $_}) -join ""} | ConvertTo-JSON} catch { "{}" | ConvertTo-JSON <<<< }
    
        + CategoryInfo          : ObjectNotFound: (ConvertTo-JSON:String) [], Comm 
    
       andNotFoundException
    
        + FullyQualifiedErrorId : CommandNotFoundException
    [ERROR   ] Error converting PowerShell JSON return
    Traceback (most recent call last):
      File "C:\salt\bin\lib\site-packages\salt\modules\cmdmod.py", line 3233, in powershell
        return salt.utils.json.loads(response)
      File "C:\salt\bin\lib\site-packages\salt\utils\json.py", line 78, in loads
        return json_module.loads(s, **kwargs)
      File "C:\salt\bin\lib\json\__init__.py", line 339, in loads
        return _default_decoder.decode(s)
      File "C:\salt\bin\lib\json\decoder.py", line 364, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "C:\salt\bin\lib\json\decoder.py", line 382, in raw_decode
        raise ValueError("No JSON object could be decoded")
    ValueError: No JSON object could be decoded
    [ERROR   ] Exception raised when processing __virtual__ function for salt.loaded.int.module.win_snmp. Module will not be loaded: expected str or bytearray
    [WARNING ] salt.loaded.int.module.win_snmp.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'win_snmp', please fix this.
    [WARNING ] C:\salt\bin\lib\site-packages\salt\modules\win_update.py:92: DeprecationWarning: The 'win_update' module is being deprecated and will be removed in Salt Fluorine (Unreleased). Please use the 'win_wua' module instead.
    
    local:
        ----------
win2016:
    [ERROR   ] Exception raised when processing __virtual__ function for salt.loaded.int.module.win_snmp. Module will not be loaded: expected str or bytearray
    [WARNING ] salt.loaded.int.module.win_snmp.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'win_snmp', please fix this.
    [WARNING ] C:\salt\bin\lib\site-packages\salt\modules\win_update.py:92: DeprecationWarning: The 'win_update' module is being deprecated and will be removed in Salt Fluorine (Unreleased). Please use the 'win_wua' module instead.
    
    local:
        ----------
win10:
    [ERROR   ] Exception raised when processing __virtual__ function for salt.loaded.int.module.win_snmp. Module will not be loaded: expected str or bytearray
    [WARNING ] salt.loaded.int.module.win_snmp.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'win_snmp', please fix this.
    [WARNING ] C:\salt\bin\lib\site-packages\salt\modules\win_update.py:92: DeprecationWarning: The 'win_update' module is being deprecated and will be removed in Salt Fluorine (Unreleased). Please use the 'win_wua' module instead.
    
    local:
        ----------
win81:
    [ERROR   ] Exception raised when processing __virtual__ function for salt.loaded.int.module.win_snmp. Module will not be loaded: expected str or bytearray
    [WARNING ] salt.loaded.int.module.win_snmp.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'win_snmp', please fix this.
    [WARNING ] C:\salt\bin\lib\site-packages\salt\modules\win_update.py:92: DeprecationWarning: The 'win_update' module is being deprecated and will be removed in Salt Fluorine (Unreleased). Please use the 'win_wua' module instead.
    
    local:
        ----------
[root@localhost ~]# 
```
### Versions Report
```
    Salt Version:
               Salt: 2018.3.0rc1
     
    Dependency Versions:
               cffi: 1.10.0
           cherrypy: Not Installed
           dateutil: 2.6.1
          docker-py: Not Installed
              gitdb: 2.0.3
          gitpython: 2.1.7
              ioflo: Not Installed
             Jinja2: 2.10
            libgit2: Not Installed
            libnacl: 1.6.1
           M2Crypto: Not Installed
               Mako: 1.0.7
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.18
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
       python-gnupg: 0.4.1
             PyYAML: 3.12
              PyZMQ: 16.0.3
               RAET: Not Installed
              smmap: 2.0.3
            timelib: 0.2.4
            Tornado: 4.5.2
                ZMQ: 4.1.6
     
    System Versions:
               dist:   
             locale: cp1252
            machine: AMD64
            release: 2016Server
             system: Windows
            version: 2016Server 10.0.14393  Multiprocessor Free
```

**Comment by garethgreenaway** [comment]
@twangboy @dwoz Thoughts on this one?

**Comment by rallytime** [comment]
There is a similar issue with mac. We need to fix this, but it shouldn't block the release as it only happens on `sys.doc`.

**Comment by twangboy** [comment]
@rallytime So, are you thinking 2018.3.1?

**Comment by rallytime** [comment]
If it's a simple fix to get in for the RC, that's fine. Otherwise, .1 is great.

**Comment by damon-atkins** [comment]
Consider "Get-WmiObject -ErrorAction Stop -class MSFC_FibrePortHBAAttributes" needing to be switch on in a minion configuration option as the original author of this code  seems to have gone. Like the ec2 grains need to be enabled.

**Comment by twangboy** [comment]
@rallytime Part of this is already fixed by https://github.com/saltstack/salt/pull/46429, but that's on the 2017.7 branch, so it will need to be merged forward. I'm looking at the other issue

**Comment by twangboy** [comment]
I just ran the function above on a Server 2016 box, so maybe that's already been merged forward.

**Comment by rallytime** [comment]
@twangboy I haven't done a merge forward since #46429 was merged in.
