### ISSUE TITLE
salt-proxy minion pillar config optional_args value needs type validation

### ISSUE THREAD

**Issue by raddessi** [saltstack/salt#46438]
### Description of Issue/Question
I misconfigured a proxy with the optional_args value set up as a list rather than a dict and the proxy error ended up being a little cryptic, and looped very quickly which isn't great for logs. If the value of optional_args is type checked this would be much clearer.

### Setup
proxy minion pillar:
```
proxy:
  proxytype: napalm
  driver: eos
  hostname: 192.168.1.2
  username: admin
  passwd: admin
  optional_args:
    - transport: https
```

### Steps to Reproduce Issue
[CRITICAL] Unexpected error while connecting to salt
Traceback (most recent call last):
  File "/opt/miniconda/envs/salt/lib/python2.7/site-packages/salt/minion.py", line 991, in _connect_minion
    yield minion.connect_master(failed=failed)
  File "/opt/miniconda/envs/salt/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/miniconda/envs/salt/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/opt/miniconda/envs/salt/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/miniconda/envs/salt/lib/python2.7/site-packages/salt/minion.py", line 1182, in connect_master
    yield self._post_master_init(master)
  File "/opt/miniconda/envs/salt/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/miniconda/envs/salt/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/opt/miniconda/envs/salt/lib/python2.7/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/opt/miniconda/envs/salt/lib/python2.7/site-packages/salt/minion.py", line 3581, in _post_master_init
    proxy_init_fn(self.opts)
  File "/opt/miniconda/envs/salt/lib/python2.7/site-packages/salt/proxy/napalm.py", line 183, in init
    NETWORK_DEVICE.update(salt.utils.napalm.get_device(opts))
  File "/opt/miniconda/envs/salt/lib/python2.7/site-packages/salt/utils/napalm.py", line 303, in get_device
    network_device = get_device_opts(opts, salt_obj=salt_obj)
  File "/opt/miniconda/envs/salt/lib/python2.7/site-packages/salt/utils/napalm.py", line 290, in get_device_opts
    network_device['OPTIONAL_ARGS']['config_lock'] = False
TypeError: list indices must be integers, not unicode
[ERROR   ] Cannot execute "get_facts" on [unspecified hostname] as . Reason: not connected!
[ERROR   ] Traceback (most recent call last):
  File "/opt/miniconda/envs/salt/lib/python2.7/site-packages/salt/utils/napalm.py", line 158, in call
    raise Exception('not connected')
Exception: not connected

### Versions Report
Salt Version:
           Salt: 2018.3.0-203-gba4266f
 
Dependency Versions:
           cffi: 1.11.4
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 |Anaconda, Inc.| (default, Nov  8 2017, 22:44:41)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.6
 
System Versions:
           dist: fedora 26 Twenty Six
         locale: UTF-8
        machine: x86_64
        release: 4.15.6-200.fc26.x86_64
         system: Linux
        version: Fedora 26 Twenty Six

**Comment by gtmanfred** [comment]
This seems reasonable.  Would love to see a PR around it.

I am marking this as a feature request.

Thanks,
Daniel

**Comment by raddessi** [comment]
What's a PR in this case?

**Comment by raddessi** [comment]
Ah, point release?

**Comment by gtmanfred** [comment]
Pull request.

https://docs.saltstack.com/en/latest/topics/development/contributing.html

**Comment by raddessi** [comment]
Right on. Is that meant to be from me or someone else?

**Comment by raddessi** [comment]
Ill check out the code and set one up this weekend

**Comment by raddessi** [comment]
bumping so this shows as active in my queue, I need to get back on it
