### ISSUE TITLE
pkg.installed and file.managed breaks with remote source on hosts booted with ipv6.disable=1

### ISSUE THREAD

**Issue by ixs** [saltstack/salt#46485]
### Description of Issue/Question
When testing some changes to the epel formula I noticed an interesting new behavior.

```
epel_release:
  pkg.installed:
    - sources:
      - epel-release: http://download.fedoraproject.org/pub/epel/7/x86_64/Packages/e/epel-release-7-11.noarch.rpm
    - require:
      - file: install_pubkey_epel
```

Will work fine on a host with ipv6 module loaded. On a host with ipv6.disabled=1 as a kernel parameter, the following error is thrown:
```
----------
          ID: epel_release
    Function: pkg.installed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1851, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1795, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/pkg.py", line 1478, in installed
                  **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/pkg.py", line 694, in _find_install_targets
                  cached_path = __salt__['cp.cache_file'](val, saltenv=kwargs['saltenv'])
                File "/usr/lib/python2.7/site-packages/salt/modules/cp.py", line 474, in cache_file
                  result = _client().cache_file(path, saltenv)
                File "/usr/lib/python2.7/site-packages/salt/fileclient.py", line 189, in cache_file
                  return self.get_url(path, '', True, saltenv, cachedir=cachedir)
                File "/usr/lib/python2.7/site-packages/salt/fileclient.py", line 698, in get_url
                  **get_kwargs
                File "/usr/lib/python2.7/site-packages/salt/utils/http.py", line 507, in query
                  **req_kwargs
                File "/usr/lib64/python2.7/site-packages/tornado/httpclient.py", line 102, in fetch
                  self._async_client.fetch, request, **kwargs))
                File "/usr/lib64/python2.7/site-packages/tornado/ioloop.py", line 444, in run_sync
                  return future_cell[0].result()
                File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result
                  raise_exc_info(self._exc_info)
                File "<string>", line 3, in raise_exc_info
              error: [Errno 97] Address family not supported by protocol
     Started: 23:46:09.122278
    Duration: 3364.506 ms
     Changes:
```
Rebooting the machine without ipv6.disable=1 gives the following output:

```
  Name: epel_release - Function: pkg.installed - Result: Clean Started: - 23:42:52.334206 Duration: 2923.25 ms
```

### Versions Report
```
salt-call --versions-report
Salt Version:
           Salt: 2017.7.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

**Comment by garethgreenaway** [comment]
@ixs Thanks for the report.  Unfortunately I am unable to duplicate the issue.   Are you able to install the packages manually using `yum` or `dnf`?

**Comment by ixs** [comment]
@garethgreenaway I am able to reproduce that on several hosts and yes, downloading via wget or curl works fine.
I could try yum but lemme try if I can come up with a simple testcase using the file.managed state. That should be possible as well as both are using the httpdownloader code which seems to trigger the problem.

**Comment by ixs** [comment]
@garethgreenaway when trying to reproduce, are you running with selinux enforcing? or disabled?

**Comment by dgengtek** [comment]
I get exactly the same exception as lxs. Selinux is disabled.
```
postgres
  pkg.installed:
    - sources:
      - postgresql10: https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7-x86_64/pgdg-centos10-10-2.noarch.rpm
```
```
Salt Version:                                                                                                                                                                                
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Apr 11 2018, 07:36:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.5.1804 Core
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.16.13-2-ARCH
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```

**Comment by donkopotamus** [comment]
I have also observed this when using `pkg.installed` with `sources` on RHEL7.5

    git2u-ius-repo:
      pkg.installed:
        - sources:
          - ius-release: https://rhel7.iuscommunity.org/ius-release.rpm

The rpm can be installed manually using `sudo -E yum install <the-url>`.  As a workaround I currently use `salt://` to provide the rpm

**Version Report**
```
$ salt-call --versions-report
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, May 31 2018, 09:41:32)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.5 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.11.6.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.5 Maipo
```

**Comment by nhavens** [comment]
We're seeing this issue intermittently as well on our CentOS 7.5 boxes with salt 2018.3.3. Strangely, the same sls file will work on the majority of our minions, but fail on a different 2 or 3 with each scheduled state.apply. Every failure is caused by a pkg.installed that specifies an https source URL. The stack trace always includes tornado. As best I can tell, the issue began for us after upgrading from salt 2018.3.2 to 2018.3.3. That upgrade didn't update Python or tornado.

**Comment by ixs** [comment]
Still valid with current salt.

**Comment by ixs** [comment]
Still valid with current salt.

**Comment by ixs** [comment]
Still valid with current salt.

**Comment by ixs** [comment]
could someone please reopen this...

this is getting kinda ridiculous... autoclosing issues because nobody is fixing them, really?
