### ISSUE TITLE
git.pull failing when run from the salt scheduler

### ISSUE THREAD

**Issue by blarghmatey** [saltstack/salt#46512]
### Description of Issue/Question
I have a scheduled job to run a `git.pull` on a host with the identity file specified in the job definition. When executing the job I am seeing a traceback in the logs because of the `ssh.key_is_encrypted` function not being present in the context.

### Setup
pillar.sls
```
schedule:
  pull_latest_code_every_five_minutes:
    function: git.pull
    minutes: 5
    args:
      - /path/to/git/repo
    kwargs:
      identity: /path/to/ssh.key
```

### Steps to Reproduce Issue
Set up the schedule on the minion and execute the job. Tailing the minion log should show a traceback similar to:
```
    2018-03-13 14:41:48,257 [salt.utils.schedule:923 ][ERROR   ][10105] Unhandled exception running git.pull
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/utils/schedule.py", line 890, in handle_func
        ret['return'] = self.functions[func](*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/git.py", line 3143, in pull
        saltenv=saltenv)['stdout']
      File "/usr/lib/python2.7/dist-packages/salt/modules/git.py", line 283, in _git_run
        and __utils__['ssh.key_is_encrypted'](id_file):
      File "/usr/lib/python2.7/dist-packages/salt/utils/context.py", line 227, in __getitem__
        return self._dict()[key]
    KeyError: 'ssh.key_is_encrypted'
```

### Versions Report
```
    Salt Version:
               Salt: 2017.7.4
     
    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 2.4.2
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.8
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: 1.0.3
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: 0.7.2.None
          pycparser: Not Installed
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 15.2.0
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.1.4
     
    System Versions:
               dist: Ubuntu 16.04 xenial
             locale: UTF-8
            machine: x86_64
            release: 4.4.0-1020-aws
             system: Linux
            version: Ubuntu 16.04 xenial
```

**Comment by gtmanfred** [comment]
can you test out this PR and see if it fixes your problem?

It should pass in utils from the Minion() so that self.utils can be reloaded in the minion_mods functions.

https://github.com/saltstack/salt/pull/46520
