### ISSUE TITLE
that syndic is not connected,the process will disappear !

### ISSUE THREAD

**Issue by zhulh200868** [saltstack/salt#46573]
### Description of Issue/Question
[salt.minion      ][ERROR   ][85567] Unable to call _return_pub_multi on 192.168.2.100, that syndic is not connected

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Salt Version:
           Salt: 2017.7.2

**Comment by gtmanfred** [comment]
Can you provide any more information?

Without knowing how to replicate this issue, there isn't anything that we can do.
Daniel

**Comment by zhulh200868** [comment]
What do you want to know ? Because my syndic's log is only this .

**Comment by WangWenchao** [comment]
Met this problem today, may I know any fix solution?

 salt --versions-report
Salt Version:
           Salt: 2017.7.8
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 12 2018, 14:36:49)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-62-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by lterlecki** [comment]
I have the same situation, logs after restart salt-syndic:
`2021-07-22 11:07:14,316 [salt.cli.daemons :85  ][INFO    ][24270] Starting up the Salt Syndic
2021-07-22 11:07:26,193 [salt.minion      :1143][INFO    ][24270] Creating minion process manager
2021-07-22 11:07:42,984 [tornado.application:611 ][ERROR   ][24270] Exception in callback <functools.partial object at 0x7f82947cd998>
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/tornado/ioloop.py", line 591, in _run_callback
    ret = callback()
  File "/usr/lib64/python2.7/site-packages/tornado/stack_context.py", line 274, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/tornado/ioloop.py", line 597, in <lambda>
    self.add_future(ret, lambda f: f.result())
  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 888, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 603, in _authenticate
    creds = yield self.sign_in(channel=channel)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 882, in run
    value = future.result()
  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 891, in run
    yielded = self.gen.send(value)
  File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 747, in sign_in
    auth['aes'] = self.verify_master(payload, master_pub='token' in sign_in_payload)
  File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 1114, in verify_master
    return self.extract_aes(payload, master_pub=False)
  File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 1035, in extract_aes
    aes, token = self.decrypt_aes(payload, master_pub)
  File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 879, in decrypt_aes
    m_digest = public_decrypt(mkey, payload['sig'])
  File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 311, in public_decrypt
    return pub.public_decrypt(message, salt.utils.rsax931.RSA_X931_PADDING)
  File "/usr/lib64/python2.7/site-packages/M2Crypto/RSA.py", line 72, in public_decrypt
    return m2.rsa_public_decrypt(self.rsa, data, padding)
RSAError: invalid header`


And system info:
`Salt Version:
           Salt: 2018.3.5
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.31.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 16 2020, 22:23:17)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.9.2009 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1127.18.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.9.2009 Core`
