### ISSUE TITLE
[modules] [nova] AttributeError: 'module' object has no attribute 'auth_plugin'

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#46623]
### Description of Issue/Question
Follow up of #46622 I tried setting keystoneauth to False 

### Setup
With the following pillars : 

```
keystone.user: admin
keystone.password: [snip]
keystone.tenant: admin
keystone.auth_url: 'http://127.0.0.1:5000/v3'
keystone.region_name: 'RegionOne'
keystone.use_keystoneauth: False
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

```
# salt-call nova.list
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 391, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 204, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/nova.py", line 612, in list_
    return server_list(profile=profile)
  File "/usr/lib/python2.7/dist-packages/salt/modules/nova.py", line 625, in server_list
    conn = _auth(profile)
  File "/usr/lib/python2.7/dist-packages/salt/modules/nova.py", line 145, in _auth
    return suon.SaltNova(**kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/utils/openstack/nova.py", line 257, in __init__
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/utils/openstack/nova.py", line 330, in _old_init
    novaclient.auth_plugin.discover_auth_systems()
AttributeError: 'module' object has no attribute 'auth_plugin'

```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
Salt Version:
           Salt: 2017.7.4
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: 1.9.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-92-generic
         system: Linux
        version: Ubuntu 16.04 xenial

```

**Comment by garethgreenaway** [comment]
@arthurlogilab Thanks for the report.  Looking at previous, similar issues I suspect this might be an issue in the upstream python-novaclient.  Can you provide the version of that library that you have installed?

**Comment by arthurlogilab** [comment]
```
dpkg -i python-novaclient 
ii  python-novaclient       2:7.1.0-0ubuntu1 all              client library for OpenStack Compute API - Python 2.
```
