### ISSUE TITLE
[modules] [nova] UnboundLocalError: local variable 'credentials' referenced before assignment

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#46622]
### Setup
With the following pillars : 

```
keystone.user: admin
keystone.password: [snip]
keystone.tenant: admin
keystone.auth_url: 'http://127.0.0.1:5000/v3'
keystone.region_name: 'RegionOne'
keystone.use_keystoneauth: True
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

```
# salt-call nova.list
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 391, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 204, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/nova.py", line 612, in list_
    return server_list(profile=profile)
  File "/usr/lib/python2.7/dist-packages/salt/modules/nova.py", line 625, in server_list
    conn = _auth(profile)
  File "/usr/lib/python2.7/dist-packages/salt/modules/nova.py", line 120, in _auth
    project_domain_name = credentials['keystone.project_domain_name']
UnboundLocalError: local variable 'credentials' referenced before assignment
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
Salt Version:
           Salt: 2017.7.4
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: 1.9.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-92-generic
         system: Linux
        version: Ubuntu 16.04 xenial

```

**Comment by garethgreenaway** [comment]
@arthurlogilab Thanks for the report.

**Comment by L4rS6** [comment]
The same problem still exists in the latest SaltStack version:
```
myserver:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/salt/minion.py", line 1664, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/python3/dist-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/modules/nova.py", line 442, in flavor_list
        conn = _auth(profile)
      File "/usr/lib/python3/dist-packages/salt/modules/nova.py", line 130, in _auth
        project_domain_name = credentials['keystone.project_domain_name']
    UnboundLocalError: local variable 'credentials' referenced before assignment
```


SaltStack Version:

```
Salt Version:
           Salt: 3000

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.9 (default, Nov  7 2019, 10:44:02)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-76-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```



Minion Config:
```
keystone.user: admin
keystone.password: mypassword
keystone.tenant: admin
keystone.auth_url: 'https://myserver:5000/v3/'
keystone.use_keystoneauth: true
keystone.verify: '/etc/ssl/certs/ca-certs.pem'
keystone.project_domain_name: default
```
