### ISSUE TITLE
[salt-cloud] [new oxygen openstack driver] Timeout waiting for the floating IP to be attached

### ISSUE THREAD

**Issue by stamak** [saltstack/salt#46663]
### Description of Issue
During provisioning of 4 VMs in **PARALLEL** it fails with an error:

```
[ERROR   ] Error creating server paraller-vm4: Timeout waiting for the floating IP to be attached.
[DEBUG   ] Manager defaults:RegionOne ran task compute.DELETE.servers in 0.288921117783s
[INFO    ] Destroyed VM: paraller-vm4
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
[ERROR   ] Failed to deploy 'paraller-vm4'. Error: Timeout waiting for the floating IP to be attached.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 2317, in create_multiprocessing
    local_master=parallel_data['local_master']
  File "/usr/local/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1284, in create
    output = self.clouds[func](vm_)
  File "/usr/local/lib/python2.7/dist-packages/salt/cloud/clouds/openstack.py", line 678, in create
    data = request_instance(conn=conn, call='action', vm_=vm_)
  File "/usr/local/lib/python2.7/dist-packages/salt/cloud/clouds/openstack.py", line 630, in request_instance
    raise SaltCloudSystemExit(six.text_type(exc))
SaltCloudSystemExit: Timeout waiting for the floating IP to be attached.
[DEBUG   ] LazyLoaded json.output
```

3 of 4 VMs have been successfully provisioned, one failed

When I provision the same map **without** -P (parallel) option - everything works as intended

### Steps to Reproduce Issue

Provider config:
```
openstack-provider:
  driver: openstack
  region_name: RegionOne
  auth:
    username: user
    password: pass
    project_name: project
    auth_url: 'https://*.net:5000/v2.0'
  verify: False
  compute_name: nova
  ssh_key_name: os-key
  ssh_key_file: /etc/salt/pki/os-ssh-key.pem
  ssh_connect_timeout: 120
  wait_for_passwd_timeout: 200
  wait_for_passwd_maxtries: 500
```
map file:
```
root@ubuntu1604:~# cat test.map
os-ubuntu1604-m1-medium:
  - paraller-vm1:
  - paraller-vm2:
  - paraller-vm3:
  - paraller-vm4:
```

Provision command:  `salt-cloud -m test.map -P -y -l debug --out=json --out-file=no_public_ips --no-deploy`

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
root@ubuntu1604:/etc/salt/cloud.profiles.d# salt-cloud --versions-report                                                    
Salt Version:
            Salt: 2018.3.0rc1

Dependency Versions:
 Apache Libcloud: 2.3.0
            cffi: 1.11.5
        cherrypy: Not Installed
        dateutil: Not Installed
       docker-py: Not Installed
           gitdb: Not Installed
       gitpython: Not Installed
           ioflo: Not Installed
          Jinja2: 2.10
         libgit2: Not Installed
         libnacl: Not Installed
        M2Crypto: Not Installed
            Mako: Not Installed
    msgpack-pure: Not Installed
  msgpack-python: 0.5.6
    mysql-python: Not Installed
       pycparser: 2.18
        pycrypto: 2.6.1
    pycryptodome: Not Installed
          pygit2: Not Installed
          Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
    python-gnupg: Not Installed
          PyYAML: 3.12
           PyZMQ: 17.0.0
            RAET: Not Installed
           smmap: Not Installed
         timelib: Not Installed
         Tornado: 4.5.3
             ZMQ: 4.1.6

System Versions:
            dist: Ubuntu 16.04 xenial
          locale: UTF-8
         machine: x86_64
         release: 4.4.0-116-generic
          system: Linux
         version: Ubuntu 16.04 xenial
```

**Comment by garethgreenaway** [comment]
@gtmanfred Thoughts on this one?

**Comment by stamak** [comment]
forgot to tell that in case of parallel:
3 of 4 VMs have been successfully deployed, one failed
Sometimes 2 of 4 are ok.

**Comment by gtmanfred** [comment]
You can pass timeout in your settings.

```
timeout: (optional) Seconds to wait, defaults to 60.
    See the wait parameter.
```

This is provided by the shade library that we are using.

**Comment by smakar-vs** [comment]
@gtmanfred  the problem is that destroyed VM gets floating IP( it's shown on OpenStack WebUI) but
**salt-cloud** does not see it and destroy

**Comment by stamak** [comment]
@gtmanfred the problem is that destroyed VM gets floating IP( it's shown on OpenStack WebUI) but
salt-cloud does not see it and destroy

**Comment by gtmanfred** [comment]
I will see if I can replicate this, but I was about to build 10 machines in parallel when writing the driver.

What version of openstack are you using?

**Comment by stamak** [comment]
@gtmanfred thx
We use Mitaka

**Comment by gtmanfred** [comment]
Can you test the fix from https://github.com/saltstack/salt/pull/46912 and also set a higher timeout?

By default the timeout for everything is 60 seconds, so if you are attaching multiple ip addresses, openstack does them one at a time, and queues up the rest, so if you have 4 ips to attach, and the first one takes 45 seconds to attach, the build will fail.

The change above PR change should help as well.

I was able to replicate the issue, but i increased my timeout, and was able to build 30 servers at once with no problem.

**Comment by rickh563** [comment]
ZD-2353

**Comment by stamak** [comment]
@gtmanfred thx
I have applied your patch and increased timeout to 120 but it does not help 
I have spent some time and and run 10 tests for each driver: openstack and nova

Statistic:
new openstack driver: 3 failed form 10 parallel provisioning
nova driver: 0 failed form 10 parallel provisioning

BTW: there is an environment I am using to do it, all details how to access it in ZD-2353

**Comment by stamak** [comment]
https://storyboard.openstack.org/#!/story/2001794

**Comment by gtmanfred** [comment]
Can you set `reuse_ips: False` in the cloud settings?  This should change back to the old behavior we had in our previous driver, which will allocate an ip address for each server.

I am going to change this to be the default.

After talking to the original creator of shade, this was what we discussed.

```
10:23:40         mordred » yah. multi-process re-use of pre-existing floating ips is basically unpossible - without some sort of shared locking/brokering system
10:24:32               ╰ » in nodepool (which does this process in many many parallel threads) - we make sure we delete floating ips when we delete servers - and also have a cleanup thread that deletes any unattached floating ips it finds
10:25:13               ╰ » since if the create-with-server-port method is being used, there is no such thing as a validly unattached floating ip
10:25:26       gtmanfred » ok, i think what I am just going to do is change the default `reuse_ips` to False, and allow them to set it if they really really really really really really really really want to use it
10:26:57         mordred » gtmanfred: yah
10:27:05         mordred » gtmanfred: so - that said - there is an option we can do
10:27:36               ╰ » (it's on my list already = it's just deep down there and there's a few big ticket items we need to likely get done first)
10:28:47               ╰ » task number 1 is to finish making the caching tier use dogpile.cache everywhere (servers, ports and floating ips are currently done manually if caching is enabled - and there are some tricky interactions as it relates to batched operations and thundering herd that we hvae to be careful about when fixing
                                  » that)
10:29:28               ╰ » but once we've got that, then we should be able to add in a locking/multi-process aware TaskManager (similar to the multithreaded TaskManager that's in nodepool right now)
10:29:43               ╰ » and leverge dogpile for the shared locking
```

He is going to make some storyboards to make this possible to use reuse_ips in a multiprocess aware way, but until that is implemented, we are going to have to stick to `reuse_ips: False` by default
