### ISSUE TITLE
pkg.mod_repo fails with a python error when removing a dictionary key

### ISSUE THREAD

**Issue by roskens** [saltstack/salt#46765]
### Description of Issue/Question
I am trying to configure the epel yum repository to use a local mirror after installing the epel-release package to set a baseurl and remove the metalink that is set. 

When trying to remove the metalink setting, I get an error.

### Setup
No special setup is required.

### Steps to Reproduce Issue
0. Start with a RedHat 7 or CentOS 7 system
1. yum install -y http://download.fedoraproject.org/pub/epel/7/x86_64/Packages/e/epel-release-7-11.noarch.rpm
2. salt-call --local pkg.mod_repo epel metalink= baseurl='http://download.fedoraproject.org/pub/epel/7/$basearch'

```
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
RuntimeError: dictionary changed size during iteration
Traceback (most recent call last):
  File "/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 391, in salt_call
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 204, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/yumpkg.py", line 2607, in mod_repo
    for key in repo_opts:
RuntimeError: dictionary changed size during iteration
Traceback (most recent call last):
  File "/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 391, in salt_call
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 204, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/yumpkg.py", line 2607, in mod_repo
    for key in repo_opts:
RuntimeError: dictionary changed size during iteration
```

### Versions Report
```
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.8.1
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, May  3 2017, 07:55:04)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.4 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.11.6.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.4 Maipo

```

A solution is to modify this section in `mod_repo` function as follows:
```
    # Build a list of keys to be deleted
    todelete = []
    for key in repo_opts:
        if repo_opts[key] != 0 and not repo_opts[key]:
            del repo_opts[key]
            todelete.append(key)
```

To:
```
    # Build a list of keys to be deleted
    todelete = []
    for key in repo_opts:
        if repo_opts[key] != 0 and not repo_opts[key]:
            todelete.append(key)
    for key in todelete:
        del repo_opts[key]
```

**Comment by gtmanfred** [comment]
I have fixed this here.

https://github.com/saltstack/salt/pull/46776

Thanks for reporting,
Daniel
