### ISSUE TITLE
salt-ssh 2018.3 states with "runas" fail with "Environment could not be retrieved for User"

### ISSUE THREAD

**Issue by anlutro** [saltstack/salt#46779]
My salt-ssh setup (using the latest version from git and a virtualenv) which works in 2017.7 breaks in 2018.3 for states that have a `runas` argument.

Example output:

```
          ID: /etc/letsencrypt/acme-tiny
    Function: git.latest
        Name: https://github.com/diafygi/acme-tiny
      Result: False
     Comment: Failed to check remote refs: Environment could not be retrieved for User 'letsencrypt'
     Started: 20:25:48.553908
    Duration: 55.377 ms
     Changes: 
```

Some state functions give a traceback:

```
An exception occurred in this state: Traceback (most recent call last):
  File "/var/tmp/.salt_08831c_salt/py3/salt/modules/cmdmod.py", line 446, in _run
    ).communicate(salt.utils.stringutils.to_bytes(py_code))[0]
ValueError: too many values to unpack (expected 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/tmp/.salt_08831c_salt/py3/salt/state.py", line 1895, in call
    **cdata['kwargs'])
  File "/var/tmp/.salt_08831c_salt/py3/salt/loader.py", line 1822, in wrapper
    return f(*args, **kwargs)
  File "/var/tmp/.salt_08831c_salt/py3/salt/states/postgres_database.py", line 98, in present
    dbs = __salt__['postgres.db_list'](**db_args)
  File "/var/tmp/.salt_08831c_salt/py3/salt/modules/postgres.py", line 480, in db_list
    password=password)
  File "/var/tmp/.salt_08831c_salt/py3/salt/modules/postgres.py", line 430, in psql_query
    password=password)
  File "/var/tmp/.salt_08831c_salt/py3/salt/modules/postgres.py", line 369, in _psql_prepare_and_run
    rcmd, runas=runas, password=password, host=host, port=port, user=user)
  File "/var/tmp/.salt_08831c_salt/py3/salt/modules/postgres.py", line 186, in _run_psql
    ret = __salt__['cmd.run_all'](cmd, python_shell=False, **kwargs)
  File "/var/tmp/.salt_08831c_salt/py3/salt/modules/cmdmod.py", line 1829, in run_all
    **kwargs)
  File "/var/tmp/.salt_08831c_salt/py3/salt/modules/cmdmod.py", line 488, in _run
    runas
salt.exceptions.CommandExecutionError: Environment could not be retrieved for User 'postgres'
```

```
$ salt-ssh --versions
Salt Version:
           Salt: 2018.3.0-272-g4609a7d
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (default, Jan 19 2017, 14:11:04)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.6
 
System Versions:
           dist: debian 9.4 
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-6-amd64
         system: Linux
        version: debian 9.4
```

**Comment by Ch3LL** [comment]
i'm able to replicate this with this state using both salt-ssh and salt-call:

```
echo test:
  cmd.run:
    - runas: ch3ll

foo_app:
  git.latest:
    - name: https://github.com/saltstack/salt.git
    - target: /tmp/foo
    - runas: ch3ll
```

Fortunately I tested this with our 2018.3.0 internal testing tag and it does not exhibit the same behavior.

**Comment by terminalmage** [comment]
This may be due to https://github.com/saltstack/salt/pull/46503

**Comment by terminalmage** [comment]
Fixed in https://github.com/saltstack/salt/pull/46796
