### ISSUE TITLE
network.managed with type: source throws KeyError if source parameter is not given

### ISSUE THREAD

**Issue by blbradley** [saltstack/salt#46827]
### Description of Issue/Question
```
          ID: source files from interfaces.d
    Function: network.managed
        Name: /etc/network/interfaces.d
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1851, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1795, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/network.py", line 315, in managed
                  new = __salt__['ip.build_interface'](name, type, enabled, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/debian_ip.py", line 1740, in build_interface
                  opts = _parse_settings_source(settings, iface_type, enabled, iface)
                File "/usr/lib/python2.7/dist-packages/salt/modules/debian_ip.py", line 1414, in _parse_settings_source
                  iface_data['sources'] = [opts['source']]
              KeyError: 'source'
     Started: 04:56:01.865532
    Duration: 8.212 ms
     Changes:
```
### Setup

SLS
```
source files from interfaces.d:
  network.managed:
    - name: /etc/network/interfaces.d
    - type: source
```

### Steps to Reproduce Issue
Run this state!

### Versions Report
```
Salt Version:                                           
           Salt: 2017.7.4                               
                                                        
Dependency Versions:                                    
           cffi: Not Installed                          
       cherrypy: Not Installed                          
       dateutil: 2.4.2                                  
      docker-py: Not Installed                          
          gitdb: Not Installed                          
      gitpython: Not Installed                          
          ioflo: Not Installed                          
         Jinja2: 2.8                                    
        libgit2: Not Installed                          
        libnacl: Not Installed                          
       M2Crypto: Not Installed                          
           Mako: 1.0.3                                  
   msgpack-pure: Not Installed                          
 msgpack-python: 0.4.6                                  
   mysql-python: Not Installed                          
      pycparser: Not Installed                          
       pycrypto: 2.6.1                                  
   pycryptodome: Not Installed                          
         pygit2: Not Installed                          
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed                          
         PyYAML: 3.11                                   
          PyZMQ: 15.2.0                                 
           RAET: Not Installed                          
          smmap: Not Installed                          
        timelib: Not Installed                          
        Tornado: 4.2.1                                  
            ZMQ: 4.1.4                                  
                                                        
System Versions:                                        
           dist: Ubuntu 16.04 xenial                    
         locale: UTF-8                                  
        machine: x86_64                                 
        release: 4.4.0-116-generic                      
         system: Linux                                  
        version: Ubuntu 16.04 xenial                    
```

**Comment by blbradley** [comment]
Fixed by using this state:

```
source files from interfaces.d:
  network.managed:
    - type: source
    - source: /etc/network/interfaces.d
```

This is completely undocumented and introduced in #20286. I like the features, just needs some work. In addition, how to manage interfaces files in the sourced directory is also undocumented.

**Comment by gtmanfred** [comment]
If you had time to submit a PR to improve the documentation, we would greatly appreciate it.

Thanks,
Daniel

**Comment by blbradley** [comment]
Agreed! I may have time soon.

Before that, I'd like to submit a PR to expose the error via a test and fix the `KeyError` with an error message to the user about a missing `source` parameter.

**Comment by gtmanfred** [comment]
That would be awesome!

Thanks,
Daniel
