### ISSUE TITLE
How to use custom util module in runner?

### ISSUE THREAD

**Issue by thuhak** [saltstack/salt#46828]
### Description of Issue/Question

There is a demo in document which describe how to use custom util module in execution module, and it's mentioned that the util module also works in runner.

I used
```
salt-run saltutil.sync_all
```
and the source code appeared in /var/cache/salt/master/extmods/utils

And then, what's the next?

**Comment by thuhak** [comment]
currently, i use 
```
import sys
sys.path.append('mypath')
```

that's a little bit ugly

**Comment by gtmanfred** [comment]
you can just use `__utils__['module.function']` and it will be automatically loaded and packed into all the runner modules.

This is how the loader works.

**Comment by thuhak** [comment]
I tried , but failed

The whole story is:

i wrote a decorator, when a runner result goes fail, i push the request back to queue.

/srv/salt/_util/mydecorators.py

```python
'''
decorators for salt runners
'''
from functools import wraps, partial
import salt.runner
import salt.config

opts = salt.config.master_config('/etc/salt/master')
queue = opts.get('runner_queue', {}).get('queue', None)


def pushback(func=None, queue=queue):
    '''
    push runner to queue if the result of runner function was false

    Usage:

    .. code-block:: python

        @pushback
        def somerunner():
            ret = {'result': True}
            return ret

        @pushback(queue='myqueue')
        def somerunner():
            ret = {'result': True}
            return ret
    '''
    if func is None:
        return partial(pushback, queue=queue)
    func_name = func.__name__
    queue=queue

    @wraps(func)
    def wrapper(*args, **kwargs):
        filterd_kw = {}
        for k in kwargs:
            if not k.startswith('__pub_'):
                filterd_kw[k] = kwargs[k]
        ret = func(*args, **filterd_kw)
        try:
            if not (ret['result'] and queue):
                runner = salt.runner.RunnerClient(opts)
                kw = {'fun': func_name, 'queue': queue, 'args':args, 'kwargs': filterd_kw}
                runner.cmd('queue.insert_runner', kwarg=kw)
        except KeyError:
            pass
        return ret
    return wrapper
```


I wanna reuse this module in other runner module.
Here is a test case.

/srv/_runner/testlib.py

```python
#  from mydecorators import pushback
pushback = __utils__['mydecorators.pushback']
#import sys
#sys.path.append('/srv/salt/_utils')
#from mydecorators import pushback

@pushback(queue="testq")
def test(arg1, arg2, arg3=None):
    ret = {'result': False}
    ret['message'] = 'arg1: {}, arg2: {}'.format(arg1, arg2)
    return ret
```

test it
```bash
sudo salt-run testlib.test a b arg3=c
```

and the result is:
```
[ERROR   ] Failed to import runners testlib, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1412, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/srv/_runners/testlib.py", line 2, in <module>
    pushback = __utils__['mydecorators.pushback']
NameError: name '__utils__' is not defined
```

Did i miss something?

**Comment by gtmanfred** [comment]
Ahh yes, you can't do that, because the __utils__ is not loaded in the top level of module.  It is only packed in once the whole module has been loaded.

What you would need to do is using `__init__` to create the decorated module.

```
def __init__():
    def test(arg1, arg2, arg3=None):
        ret = {'result': False}
        ret['message'] = 'arg1: {}, arg2: {}'.format(arg1, arg2)
        return ret
    global test = __utils__['mydecorators.pushback'](test)
```

All dunder functions are only available in the modules, not in the global namespace, because they are packed in after the module has been imported.

**Comment by thuhak** [comment]
Thx a lot

Now I think the previous version is not that bad
