### ISSUE TITLE
Attribute Error When Invoking Vault Module Method

### ISSUE THREAD

**Issue by femnad** [saltstack/salt#46864]
### Description of Issue/Question
Executing methods in vault modules fail with an attribute error:
```
<minion name>:
    ERROR: Exception occurred in runner vault.generate_token: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 387, in _low
        data['return'] = self.functions[fun](*args, **kwargs)
      File "/usr/lib/python2.7/site-packages/salt/runners/vault.py", line 43, in generate_token
        'Token generation request for %s (impersonated by master: %s)'.
    AttributeError: 'unicode' object has no attribute 'minion_id'
```
### Setup
Vault configuration:
```
vault:
  url: <url>
  auth:
    method: token
    token: <token>
  policies:
    - <policy>
```
### Steps to Reproduce Issue
Run the vault module by itself or via sdb:
```
salt <target> vault.list_secrets <secret>
```
```
salt <target> sdb.get <secret>
```
### Versions Report

```

Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, May  3 2017, 07:55:04)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: redhat 7.4 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.17.1.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.4 Maipo
```

**Comment by gtmanfred** [comment]
Thanks for the bug fix here!
Daniel
