### ISSUE TITLE
2018.3.0 reg.present catching wrong exception when vdata is a list.

### ISSUE THREAD

**Issue by whytewolf** [saltstack/salt#46932]
### Description of Issue/Question

with 2018.3.0 the `salt.utils.stringutils.to_unicode` function was changed to throw `TypeError` instead of `UnicodeEncodeError` the reg state is still looking for `UnicodeEncodeError` so when a list is added as as vdata. instead of running it's code to handle it. the `TypeError` trace gets output to the user. and the registery is never updated.

### Setup
Try this state in 2018.3.0 on windows
```
test_reg:
  reg.present:
    - name: HKEY_LOCAL_MACHINE\SOFTWARE\salttest\salty\salted
    - vname: Test
    - REG_MULTI_SZ
    - vdata: ['test'.'test2']
```

### Steps to Reproduce Issue
Run the above state in 2018.3.0

result:
```
local:
---------
              ID: test_reg 
   Function: reg.present 
        Name: HKEY_LOCAL_MACHINE\SOFTWARE\salttest\salty\salted 
       Result: False 
 Comment: An exception occurred in this state: Traceback (most recent call last): 
                     File "c:\salt\bin\lib\site-packages\salt\state.py", line 1878, in call 
                       **cdata['kwargs']) 
                     File "c:\salt\bin\lib\site-packages\salt\loader.py", line 1823, in wrapper 
                       return f(*args, **kwargs) 
                     File "c:\salt\bin\lib\site-packages\salt\states\reg.py", line 196, in present 
                       vdata_decoded = salt.utils.stringutils.to_unicode(vdata, 'utf-8') 
                     File "c:\salt\bin\lib\site-packages\salt\utils\stringutils.py", line 99, in to_unicode 
                       raise TypeError('expected str, bytes, or bytearray') 
                     TypeError: expected str, bytes, or bytearray 
```

Expected result: a new registry REG_MULTI_SZ registry item inserted. 

### Versions Report
```
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit(AMD64)]
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.2
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2016Server
         system: Windows
        version: 2016Server 10.0.14393 SPO Multiprocessor Free
```

**Comment by whytewolf** [comment]
ZD-2407

**Comment by Ch3LL** [comment]
ping @saltstack/team-windows any ideas here?

**Comment by skizunov** [comment]
I would say that at:
https://github.com/saltstack/salt/blob/2018.3/salt/states/reg.py#L197
```
except UnicodeDecodeError:
```
Could be changed to something like:
```
except (UnicodeDecodeError, TypeError):
```
However, searching the Salt codebase shows that `except UnicodeDecodeError:` appears in many places. So either all the places should be changed, or the implementation of `salt.utils.stringutils.to_unicode` needs to be changed to ensure that `TypeError` gets converted to `UnicodeDecodeError`.

@twangboy : Do you have a preference for which way to proceed?

**Comment by twangboy** [comment]
I pinged @terminalmage on this. If we're going to use `TypeError` in the `to_unicode` function, we need to fix all the `try/except` blocks to use `TypeError` as well.
