### ISSUE TITLE
[2018.3.0] Backwards compatibilty breaking change in 2018.3.0

### ISSUE THREAD

**Issue by gtmanfred** [saltstack/salt#46977]
### Description of Issue/Question

I know we reserve the right to do this, but there is a breaking change in `salt/state.py` that breaks using `state.highstate` on minions that have 2018.3.0 installed on them, if your master is 2017.7.

### Steps to Reproduce Issue
Salt master on 2017.7.5
Salt minion on 2018.3.0

```
==> /srv/salt/top.sls <==
base:
  '*':
    - test

==> /srv/salt/test.sls <==
test:
  test.succeed_without_changes
```

Run `salt-call state.apply` and it fails with 

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 212, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 749, in apply_
    return highstate(**kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 1055, in highstate
    orchestration_jid=orchestration_jid)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 3839, in call_highstate
    matches = self.top_matches(top)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 3333, in top_matches
    for saltenv in ext_matches:
TypeError: 'bool' object is not iterable
```

### Versions Report
```
[root@salt salt]# salt --versions-report
Salt Version:
           Salt: 2017.7.5

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.9.87-linuxkit-aufs
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

```
[root@minion1 /]# salt-call --versions-report
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.9.87-linuxkit-aufs
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

**Comment by thatch45** [comment]
While we reserve the right to break minion master compat in this case we do not do it unless it is a critical reason that cannot be worked around. This needs to be fixed for the .1 release

**Comment by rallytime** [comment]
@garethgreenaway Can you take a look at this for the 2018.3.1 release?
