### ISSUE TITLE
nfs3 module errors with in-line comments in the exports file

### ISSUE THREAD

**Issue by OrlandoArcapix** [saltstack/salt#46987]
### Description of Issue/Question

The `nfs3.list_exports` call throws an exception when there are in-line comments in an entry in the exports file.

### Setup

Create an exports file with a comment after a defined share:
```
/test/share	*(rw,async,fsid=12345) # some comment
```

### Steps to Reproduce Issue

```
# salt-call nfs3.list_exports
Traceback (most recent call last):
  File "/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 391, in salt_call
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 204, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/nfs3.py", line 50, in list_exports
    permcomps[1] = permcomps[1].replace(')', '')
IndexError: list index out of range
```

### Expected behaviour

Should return:
```
local:
    ----------
    /test/share:
        |_
          ----------
          hosts:
              - *
          options:
              - rw
              - async
              - fsid=12345
```

### Versions Report
```Salt Version:
           Salt: 2017.7.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.17.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

(I've also confirmed issue is present in 2018.3.0)

**Comment by garethgreenaway** [comment]
@OrlandoArcapix Thanks for the report.  Marking this as a feature request for include a comment field.
