### ISSUE TITLE
UnicodeDecodeError in mako

### ISSUE THREAD

**Issue by Mrten** [saltstack/salt#4699]
This is driving me *insane*:

```
ns2:
----------
    State: - file
    Name:      /etc/powerdns/zones
    Function:  recurse
        Result:    False
        Comment:   An exception occured in this state: Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/salt/state.py", line 1208, in call
    *cdata['args'], **cdata['kwargs'])
  File "/usr/lib/pymodules/python2.7/salt/states/file.py", line 1235, in recurse
    manage_file(dest, src)
  File "/usr/lib/pymodules/python2.7/salt/states/file.py", line 1174, in manage_file
    **pass_kwargs)
  File "/usr/lib/pymodules/python2.7/salt/states/file.py", line 762, in managed
    **kwargs
  File "/usr/lib/pymodules/python2.7/salt/modules/file.py", line 1131, in get_managed
    **kwargs
  File "/usr/lib/pymodules/python2.7/salt/utils/templates.py", line 50, in render_tmpl
    tmplstr = tmplsrc.read()
  File "/usr/lib/python2.7/codecs.py", line 671, in read
    return self.reader.read(size)
  File "/usr/lib/python2.7/codecs.py", line 477, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x81 in position 18: invalid start byte

        Changes:
```
The sls is:
```
/etc/powerdns/zones:
  file.recurse:
    - source: salt://machine/ns/master/zones
    - template: mako
```
Part of the file in question is:
```
<%!
import datetime

# dit doet eens per 4.4 minuten de serial ophogen, hopelijk is dat genoeg
def soaserial():

  today = datetime.datetime.now()

  serial = today.strftime('%Y%m')

  cnt =  (int(today.strftime("%d"))-1) * 24*60
  cnt += int(today.strftime("%H")) * 60
  cnt += int(today.strftime("%M"))

  serial += '{0:04d}'.format(int(cnt/44640.0*10000))

  return int(serial)

soa = soaserial()
%>
$TTL 900
@               IN      SOA     ns2.ii.nl. hostmaster.ii.nl. (
                ${ soa }              ;serial
                                4H      ;refresh after 4 hours
                                1H      ;retry after 1 hour
```

I've tried `soaserial.encode('utf-8')`, `soaserial.decode('utf-8')` (before I caved and converted the result to an int()), but nothing works. The hex-number in the errormessage changes, though ;)

(BTW, I'm assuming it is about that file, can't see that from the trace and there are more files in `/etc/powerdns/zones`). I've hexdumped all files and found no trace of the 0x81 anywhere.

**Comment by terminalmage** [comment]
Added a warning in #26218.
