### ISSUE TITLE
Setting Memory Reservation (Locked to Max) salt-cloud vmware pyvmomi

### ISSUE THREAD

**Issue by pinto430** [saltstack/salt#47003]
### Setup
Profile is first, provider is second
```

W9TVDS1039:
  provider: vcenter_server
  clonefrom: "Win 2K16 Datacenter 2018.01"
  num_cpus: 2
  memory: 4096
  devices:
  dns_servers:
    - 10.200.45.111
    - 10.200.45.112
  folder: Minions
  power_on: False
  deploy: False
  customization: True
  plain_text: True
  extra_config:
    memoryReservationLockedToMax: True

vcenter_server:
  driver: vmware
  user: 'nonya'
  password: 'business'
  url: 'servername'
  protocol: 'https'
  port: 443
```

### Steps to Reproduce Issue

I am trying to set the memory reservation checkbox on a newly created vm when it is built via Salt-Cloud. I have tried multiple different methods to setting this checkbox (it appears that its a field called memoryreservationLockedToMax) but all of them error out with the message that a specified parameter was not correct. The different values we have tried are (all under extra_config)
    memoryReservationLockedToMax: True
    vim.vm.ConfigInfo.memoryReservationLockedToMax: True
    vim.vm.ConfigSpec.memoryReservationLockedToMax: True
    VMware.vim.virtualmachineConfigSpec.memoryReservationLockedToMax: True

All of these different values returned the same error (listed above). I also tried moving the memoryReservationLockedToMax: True outside of the extra config (and into the same level as the other config items). This successfully created the VM, but it did not lock the memory on the created VM.

This is using the salt-cloud -p SERVERNAME servername methodology.

Currently when running the above profile into our vCenter

```
salt-cloud -l debug -p W9TVDS1039 W9TVDS1039
[DEBUG   ] Sending event: tag = salt/cloud/W9TVDS1039/creating; data = {'profile': 'W9TVDS1039', '_stamp': '2018-04-10T21:17:11.119958', 'name': 'W9TVDS1039', 'driver': 'vmware', 'provider': 'vcenter_X9NVTL1000:vmware', 'event': 'starting create'}
[DEBUG   ] Setting cpu to: 2
[DEBUG   ] Setting memory to: 4096 MB
[DEBUG   ] clone_spec set to:
(vim.vm.CloneSpec) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   location = (vim.vm.RelocateSpec) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      service = <unset>,
      folder = <unset>,
      datastore = 'vim.Datastore:datastore-3905',
      diskMoveType = <unset>,
      pool = 'vim.ResourcePool:resgroup-799',
      host = <unset>,
      disk = (vim.vm.RelocateSpec.DiskLocator) [],
      transform = <unset>,
      deviceChange = (vim.vm.device.VirtualDeviceSpec) [],
      profile = (vim.vm.ProfileSpec) []
   },
   template = false,
   config = (vim.vm.ConfigSpec) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      changeVersion = <unset>,
      name = <unset>,
      version = <unset>,
      uuid = <unset>,
      instanceUuid = <unset>,
      npivNodeWorldWideName = (long) [],
      npivPortWorldWideName = (long) [],
      npivWorldWideNameType = <unset>,
      npivDesiredNodeWwns = <unset>,
      npivDesiredPortWwns = <unset>,
      npivTemporaryDisabled = <unset>,
      npivOnNonRdmDisks = <unset>,
      npivWorldWideNameOp = <unset>,
      locationId = <unset>,
      guestId = <unset>,
      alternateGuestName = <unset>,
      annotation = <unset>,
      files = <unset>,
      tools = <unset>,
      flags = <unset>,
      consolePreferences = <unset>,
      powerOpInfo = <unset>,
      numCPUs = 2,
      numCoresPerSocket = <unset>,
      memoryMB = 4096,
      memoryHotAddEnabled = <unset>,
      cpuHotAddEnabled = <unset>,
      cpuHotRemoveEnabled = <unset>,
      virtualICH7MPresent = <unset>,
      virtualSMCPresent = <unset>,
      deviceChange = (vim.vm.device.VirtualDeviceSpec) [
         (vim.vm.device.VirtualDeviceSpec) {
            dynamicType = <unset>,
            dynamicProperty = (vmodl.DynamicProperty) [],
            operation = 'edit',
            fileOperation = <unset>,
            device = (vim.vm.device.VirtualVmxnet3) {
               dynamicType = <unset>,
               dynamicProperty = (vmodl.DynamicProperty) [],
               key = 4000,
               deviceInfo = (vim.Description) {
                  dynamicType = <unset>,
                  dynamicProperty = (vmodl.DynamicProperty) [],
                  label = 'Network adapter 1',
                  summary = 'LAB-SFA-D2-NR-V44'
               },
               backing = (vim.vm.device.VirtualEthernetCard.DistributedVirtualPortBackingInfo) {
                  dynamicType = <unset>,
                  dynamicProperty = (vmodl.DynamicProperty) [],
                  port = (vim.dvs.PortConnection) {
                     dynamicType = <unset>,
                     dynamicProperty = (vmodl.DynamicProperty) [],
                     switchUuid = '80 cf 15 50 24 8d 99 a3-f2 c6 09 bc 81 19 c7 0a',
                     portgroupKey = 'dvportgroup-12569',
                     portKey = <unset>,
                     connectionCookie = <unset>
                  }
               },
               connectable = (vim.vm.device.VirtualDevice.ConnectInfo) {
                  dynamicType = <unset>,
                  dynamicProperty = (vmodl.DynamicProperty) [],
                  startConnected = true,
                  allowGuestControl = true,
                  connected = false,
                  status = 'untried'
               },
               slotInfo = <unset>,
               controllerKey = 100,
               unitNumber = 7,
               addressType = 'assigned',
               macAddress = '00:50:56:af:3e:c8',
               wakeOnLanEnabled = true,
               resourceAllocation = (vim.vm.device.VirtualEthernetCard.ResourceAllocation) {
                  dynamicType = <unset>,
                  dynamicProperty = (vmodl.DynamicProperty) [],
                  reservation = 0L,
                  share = (vim.SharesInfo) {
                     dynamicType = <unset>,
                     dynamicProperty = (vmodl.DynamicProperty) [],
                     shares = 50,
                     level = 'normal'
                  },
                  limit = -1L
               },
               externalId = <unset>,
               uptCompatibilityEnabled = <unset>
            },
            profile = (vim.vm.ProfileSpec) [],
            backing = <unset>
         },
         (vim.vm.device.VirtualDeviceSpec) {
            dynamicType = <unset>,
            dynamicProperty = (vmodl.DynamicProperty) [],
            operation = 'edit',
            fileOperation = <unset>,
            device = (vim.vm.device.VirtualVmxnet3) {
               dynamicType = <unset>,
               dynamicProperty = (vmodl.DynamicProperty) [],
               key = 4001,
               deviceInfo = (vim.Description) {
                  dynamicType = <unset>,
                  dynamicProperty = (vmodl.DynamicProperty) [],
                  label = 'Network adapter 2',
                  summary = 'LAB-SFA-D2-NR-V2144-BK'
               },
               backing = (vim.vm.device.VirtualEthernetCard.DistributedVirtualPortBackingInfo) {
                  dynamicType = <unset>,
                  dynamicProperty = (vmodl.DynamicProperty) [],
                  port = (vim.dvs.PortConnection) {
                     dynamicType = <unset>,
                     dynamicProperty = (vmodl.DynamicProperty) [],
                     switchUuid = '80 cf 15 50 24 8d 99 a3-f2 c6 09 bc 81 19 c7 0a',
                     portgroupKey = 'dvportgroup-20630',
                     portKey = <unset>,
                     connectionCookie = <unset>
                  }
               },
               connectable = (vim.vm.device.VirtualDevice.ConnectInfo) {
                  dynamicType = <unset>,
                  dynamicProperty = (vmodl.DynamicProperty) [],
                  startConnected = true,
                  allowGuestControl = true,
                  connected = false,
                  status = 'untried'
               },
               slotInfo = <unset>,
               controllerKey = 100,
               unitNumber = 8,
               addressType = 'assigned',
               macAddress = '00:50:56:af:af:f3',
               wakeOnLanEnabled = true,
               resourceAllocation = (vim.vm.device.VirtualEthernetCard.ResourceAllocation) {
                  dynamicType = <unset>,
                  dynamicProperty = (vmodl.DynamicProperty) [],
                  reservation = 0L,
                  share = (vim.SharesInfo) {
                     dynamicType = <unset>,
                     dynamicProperty = (vmodl.DynamicProperty) [],
                     shares = 50,
                     level = 'normal'
                  },
                  limit = -1L
               },
               externalId = <unset>,
               uptCompatibilityEnabled = <unset>
            },
            profile = (vim.vm.ProfileSpec) [],
            backing = <unset>
         }
      ],
      cpuAllocation = <unset>,
      memoryAllocation = <unset>,
      latencySensitivity = <unset>,
      cpuAffinity = <unset>,
      memoryAffinity = <unset>,
      networkShaper = <unset>,
      cpuFeatureMask = (vim.vm.ConfigSpec.CpuIdInfoSpec) [],
      extraConfig = (vim.option.OptionValue) [
         (vim.option.OptionValue) {
            dynamicType = <unset>,
            dynamicProperty = (vmodl.DynamicProperty) [],
            key = 'memoryReservationLockedToMax',
            value = true
         }
      ],
      swapPlacement = <unset>,
      bootOptions = <unset>,
      vAppConfig = <unset>,
      ftInfo = <unset>,
      repConfig = <unset>,
      vAppConfigRemoved = <unset>,
      vAssertsEnabled = <unset>,
      changeTrackingEnabled = <unset>,
      firmware = <unset>,
      maxMksConnections = <unset>,
      guestAutoLockEnabled = <unset>,
      managedBy = <unset>,
      memoryReservationLockedToMax = <unset>,
      nestedHVEnabled = <unset>,
      vPMCEnabled = <unset>,
      scheduledHardwareUpgradeInfo = <unset>,
      vmProfile = (vim.vm.ProfileSpec) [],
      messageBusTunnelEnabled = <unset>,
      crypto = <unset>,
      migrateEncryption = <unset>
   },
   customization = (vim.vm.customization.Specification) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      options = <unset>,
      identity = (vim.vm.customization.Sysprep) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         guiUnattended = (vim.vm.customization.GuiUnattended) {
            dynamicType = <unset>,
            dynamicProperty = (vmodl.DynamicProperty) [],
            password = (vim.vm.customization.Password) {
               dynamicType = <unset>,
               dynamicProperty = (vmodl.DynamicProperty) [],
               value = '******',
               plainText = true
            },
            timeZone = 0,
            autoLogon = true,
            autoLogonCount = 1
         },
         userData = (vim.vm.customization.UserData) {
            dynamicType = <unset>,
            dynamicProperty = (vmodl.DynamicProperty) [],
            fullName = 'Windows User',
            orgName = 'Organization',
            computerName = (vim.vm.customization.FixedName) {
               dynamicType = <unset>,
               dynamicProperty = (vmodl.DynamicProperty) [],
               name = 'W9TVDS1039'
            },
            productId = ''
         },
         guiRunOnce = <unset>,
         identification = (vim.vm.customization.Identification) {
            dynamicType = <unset>,
            dynamicProperty = (vmodl.DynamicProperty) [],
            joinWorkgroup = <unset>,
            joinDomain = <unset>,
            domainAdmin = <unset>,
            domainAdminPassword = <unset>
         },
         licenseFilePrintData = <unset>
      },
      globalIPSettings = (vim.vm.customization.GlobalIPSettings) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         dnsSuffixList = (str) [],
         dnsServerList = (str) [
            '10.200.45.111',
            '10.200.45.112'
         ]
      },
      nicSettingMap = (vim.vm.customization.AdapterMapping) [
         (vim.vm.customization.AdapterMapping) {
            dynamicType = <unset>,
            dynamicProperty = (vmodl.DynamicProperty) [],
            macAddress = <unset>,
            adapter = (vim.vm.customization.IPSettings) {
               dynamicType = <unset>,
               dynamicProperty = (vmodl.DynamicProperty) [],
               ip = (vim.vm.customization.FixedIp) {
                  dynamicType = <unset>,
                  dynamicProperty = (vmodl.DynamicProperty) [],
                  ipAddress = '10.200.44.75'
               },
               subnetMask = '255.255.255.0',
               gateway = '10.200.44.1',
               ipV6Spec = <unset>,
               dnsServerList = (str) [],
               dnsDomain = 'giolab.local',
               primaryWINS = <unset>,
               secondaryWINS = <unset>,
               netBIOS = <unset>
            }
         },
         (vim.vm.customization.AdapterMapping) {
            dynamicType = <unset>,
            dynamicProperty = (vmodl.DynamicProperty) [],
            macAddress = <unset>,
            adapter = (vim.vm.customization.IPSettings) {
               dynamicType = <unset>,
               dynamicProperty = (vmodl.DynamicProperty) [],
               ip = (vim.vm.customization.FixedIp) {
                  dynamicType = <unset>,
                  dynamicProperty = (vmodl.DynamicProperty) [],
                  ipAddress = '10.200.144.75'
               },
               subnetMask = '255.255.255.0',
               gateway = (str) [],
               ipV6Spec = <unset>,
               dnsServerList = (str) [],
               dnsDomain = <unset>,
               primaryWINS = <unset>,
               secondaryWINS = <unset>,
               netBIOS = <unset>
            }
         }
      ],
      encryptionKey = (byte) []
   },
   powerOn = false,
   snapshot = <unset>,
   memory = <unset>
}
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event: tag = salt/cloud/W9TVDS1039/requesting; data = {'event': 'requesting instance', 'domain': 'giolab.local', 'priv_key': None, 'protocol': 'https', '_stamp': '2018-04-10T21:17:11.693879', 'cluster': 'E9TCIR8056', 'dns_servers': ['10.200.45.111', '10.200.45.112'], 'customization': True, 'datastore': 'E9TCIR8021_VPLEX0336_4', 'win_password': '*****', 'num_cpus': 2, 'port': 443, 'memory': 4096, 'folder': 'Minions', 'extra_config': {'memoryReservationLockedToMax': True}, 'profile': 'W9TVDS1039', 'deploy': False, 'driver': 'vmware', 'provider': 'vcenter_*****:vmware', 'plain_text': True, 'user': 'giolab\\aka1svc038', 'inline_script': None, 'power_on': False, 'name': '*****', 'clonefrom': 'Win 2K16 Datacenter 2018.01', 'url': '*******', 'devices': }, 'pub_key': None, 'os': 'bootstrap-salt'}
[INFO    ] Creating W9TVDS1039 from template(Win 2K16 Datacenter 2018.01)
[INFO    ] [ W9TVDS1039 ] Waiting for clone task to finish [0 s]
[INFO    ] [ W9TVDS1039 ] Waiting for clone task to finish [5 s]
[INFO    ] [ W9TVDS1039 ] Waiting for clone task to finish [10 s]
[INFO    ] [ W9TVDS1039 ] Waiting for clone task to finish [15 s]
[INFO    ] [ W9TVDS1039 ] Waiting for clone task to finish [20 s]
[INFO    ] [ W9TVDS1039 ] Waiting for clone task to finish [25 s]
[INFO    ] [ W9TVDS1039 ] Waiting for clone task to finish [30 s]
[INFO    ] [ W9TVDS1039 ] Waiting for clone task to finish [35 s]
[ERROR   ] Error creating W9TVDS1039: A specified parameter was not correct: config.extraConfig["memoryReservationLockedToMax"]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/vmware.py", line 2681, in create
    salt.utils.vmware.wait_for_task(task, vm_name, 'clone', 5, 'info')
  File "/usr/lib/python2.7/site-packages/salt/utils/vmware.py", line 1336, in wait_for_task
    raise salt.exceptions.VMwareApiError(exc_message)
VMwareApiError: A specified parameter was not correct: config.extraConfig["memoryReservationLockedToMax"]
[DEBUG   ] LazyLoaded nested.output
W9TVDS1039:
    ----------
    Error:
        Error creating W9TVDS1039: A specified parameter was not correct: config.extraConfig["memoryReservationLockedToMax"]`

```
### Versions Report

Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, May 29 2017, 20:42:36)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: oracle 7.4
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.5.2.el7.x86_64
         system: Linux
        version: Oracle Linux Server 7.4

**Comment by gtmanfred** [comment]
@nmadhok can you help here?

Thanks,
Daniel
