### ISSUE TITLE
Openstack keystone users can't be added to a project

### ISSUE THREAD

**Issue by L4rS6** [saltstack/salt#47013]
### Description of Issue/Question
Openstack keystone users can't be added to a project as mentioned in the documentation: https://docs.saltstack.com/en/latest/ref/states/all/salt.states.keystone.html

### Setup
Setup Openstack environment

### Steps to Reproduce Issue
Use the following state:

```
openstack_keystone_test_user:
  keystone_user.present:
    - name: test
    - password: testpassword
    - roles:
        myproject:
          - myrole
```

This will throw an exception:
```
----------
          ID: openstack_keystone_test_user
    Function: keystone_user.present
        Name: test
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1878, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1823, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/keystone_user.py", line 99, in present
                  user = __salt__['keystoneng.user_create'](**kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/keystoneng.py", line 542, in user_create
                  return cloud.create_user(**kwargs)
              TypeError: create_user() got an unexpected keyword argument 'roles'
     Started: 10:16:58.373630
    Duration: 585.116 ms
     Changes:
```

### Versions Report
Master:
```
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: 1.5.0
       cherrypy: 3.2.2
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Nov 23 2017, 15:49:48)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 3.13.0-142-generic
         system: Linux
        version: Ubuntu 14.04 trusty

```

Minion:
```
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.4.0-119-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by L4rS6** [comment]
It looks like that this is not just a documentation bug. I already have rewritten the state (have a look at my test state) to the new keystoneng module/state and it's still not working (it was neither for the old version).

In the new keystone_user state there is no possibility to add roles: https://github.com/saltstack/salt/blob/2018.3/salt/states/keystone_user.py#L59

**Comment by gtmanfred** [comment]
Right, you need to use the keystone_role_grant state module, to grant roles to users or groups

**Comment by L4rS6** [comment]
@gtmanfred Thank you. With the keystone_role_grant state module it works!

**Comment by gtmanfred** [comment]
The new state documents are up.
