### ISSUE TITLE
can not get the ip of new vms

### ISSUE THREAD

**Issue by antime** [saltstack/salt#47090]
### Description of Issue/Question
when i use 'salt-cloud -p aliyun_api ds_salt_test -P -l debug' to create a vm,i can not get the ip of it. And the error is like this:Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1284, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/aliyun.py", line 700, in create
    'wait_for_ip_interval', vm_, __opts__, default=10),
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 2389, in wait_for_ip
    data = update_callback(*update_args, **update_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/aliyun.py", line 686, in __query_node_data
    data = show_instance(vm_name, call='action')
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/aliyun.py", line 928, in show_instance
    return _get_node(name)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/aliyun.py", line 935, in _get_node
    return list_nodes_full()[name]
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/aliyun.py", line 329, in list_nodes_full
    result_instancestatus.update(result['InstanceStatuses']['InstanceStatus'])
AttributeError: 'list' object has no attribute 'update'
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
salt-cloud 2018.3.0 (Oxygen)

**Comment by gtmanfred** [comment]
@steinliber can you take a look at this?  This looks like something you changed in #39388

Thanks!
Daniel
