### ISSUE TITLE
Nfs3 execution modules unusable on AIX minion

### ISSUE THREAD

**Issue by jose1711** [saltstack/salt#47098]
### Description of Issue/Question
Nfs3 execution modules does not work properly on AIX system as AIX uses different format of ```/etc/exports```.

### Setup
Linux master
AIX 7.1 minion

### Steps to Reproduce Issue
```
# salt aix_minion nfs3.list_exports
aix_minion:
    The minion function caused an exception: Traceback (most recent call last):
      File "/opt/salt/lib/python2.7/site-packages/salt/minion.py", line 1445, in _thread_return
        return_data = executor.execute()
      File "/opt/salt/lib/python2.7/site-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/opt/salt/lib/python2.7/site-packages/salt/modules/nfs3.py", line 50, in list_exports
        permcomps[1] = permcomps[1].replace(')', '')
    IndexError: list index out of range
```

situation on minion
```
# cat /etc/exports
/exported_dir -public,sec=sys,rw
```

### Versions Report
```
Salt Version:
           Salt: 2016.11.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.3
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.5
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Apr 24 2017, 13:47:33)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.1.6

System Versions:
           dist:
        machine: 00CED4E74C00
        release: 1
         system: AIX
        version: Not Installed
```

**Comment by gtmanfred** [comment]
@dmurphy18 can you take a look at this when you get a minute?

Thanks,
Daniel

**Comment by dmurphy18** [comment]
This should be fixed in the upcoming Fluorine release.

**Comment by garethgreenaway** [comment]
Closing this out, if the problem persists please comment & we'll re-open the issue or feel free to open a new issue.
