### ISSUE TITLE
salt-cloud can't serialize azure.mgmt.compute.models.virtual_hard_disk.VirtualHardDisk object

### ISSUE THREAD

**Issue by cskowronnek** [saltstack/salt#47096]
### Description of Issue/Question
When I try to run salt-cloud -p to provision a VM using driver "azurearm", I run into the following error message:

TypeError: can't serialize <azure.mgmt.compute.models.virtual_hard_disk.VirtualHardDisk object at 0x7f7cf254b690>

Trace:
> [INFO    ] Rendering deploy script: /usr/lib/python2.7/dist-packages/salt/cloud/deploy/bootstrap-salt.sh
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
[ERROR   ] There was a profile error: can't serialize <azure.mgmt.compute.models.virtual_hard_disk.VirtualHardDisk object at 0x7f7cf254b690>
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 281, in run
    self.config.get('names')
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1454, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1284, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/azurearm.py", line 1305, in create
    ret = __utils__['cloud.bootstrap'](vm_, __opts__)
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 553, in bootstrap
    transport=opts.get('transport', 'zeromq')
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 1786, in fire_event
    event.fire_event(args, tag)
  File "/usr/lib/python2.7/dist-packages/salt/utils/event.py", line 718, in fire_event
    dump_data = self.serial.dumps(data)
  File "/usr/lib/python2.7/dist-packages/salt/payload.py", line 213, in dumps
    return msgpack.dumps(msg, default=ext_type_encoder, use_bin_type=use_bin_type)
  File "/usr/lib/python2.7/dist-packages/msgpack/__init__.py", line 47, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 223, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:223)
  File "msgpack/_packer.pyx", line 225, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:225)
  File "msgpack/_packer.pyx", line 184, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:184)
  File "msgpack/_packer.pyx", line 184, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:184)
  File "msgpack/_packer.pyx", line 184, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:184)
  File "msgpack/_packer.pyx", line 213, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:213)
  File "msgpack/_packer.pyx", line 184, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:184)
  File "msgpack/_packer.pyx", line 220, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:220)
TypeError: can't serialize <azure.mgmt.compute.models.virtual_hard_disk.VirtualHardDisk object at 0x7f7cf254b690>

### Setup
Salt-Cloud 2018.3.0 on Ubuntu 16.04

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: 1.11.2
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-119-generic
         system: Linux
        version: Ubuntu 16.04 xenial

-----------------------------
pip freeze

azure==2.0.0rc6
azure-batch==1.0.0
azure-batch-extensions==1.0.1
azure-cli==2.0.23
azure-cli-acr==2.0.17
azure-cli-acs==2.0.22
azure-cli-advisor==0.1.0
azure-cli-appservice==0.1.22
azure-cli-backup==1.0.3
azure-cli-batch==3.1.7
azure-cli-batchai==0.1.3
azure-cli-billing==0.1.6
azure-cli-cdn==0.0.10
azure-cli-cloud==2.0.10
azure-cli-cognitiveservices==0.1.9
azure-cli-command-modules-nspkg==2.0.1
azure-cli-configure==2.0.12
azure-cli-consumption==0.2.0
azure-cli-container==0.1.15
azure-cli-core==2.0.23
azure-cli-cosmosdb==0.1.15
azure-cli-dla==0.0.15
azure-cli-dls==0.0.18
azure-cli-eventgrid==0.1.5
azure-cli-extension==0.0.6
azure-cli-feedback==2.0.6
azure-cli-find==0.2.7
azure-cli-interactive==0.3.11
azure-cli-iot==0.1.15
azure-cli-keyvault==2.0.15
azure-cli-lab==0.0.13
azure-cli-monitor==0.0.13
azure-cli-network==2.0.19
azure-cli-nspkg==3.0.1
azure-cli-profile==2.0.16
azure-cli-rdbms==0.0.9
azure-cli-redis==0.2.10
azure-cli-reservations==0.1.0
azure-cli-resource==2.0.19
azure-cli-role==2.0.15
azure-cli-servicefabric==0.0.7
azure-cli-sql==2.0.17
azure-cli-storage==2.0.21
azure-cli-vm==2.0.20
azure-common==1.1.4
azure-datalake-store==0.0.17
azure-graphrbac==0.31.0
azure-keyvault==0.3.7
azure-mgmt==0.30.0rc6
azure-mgmt-advisor==0.1.0
azure-mgmt-authorization==0.30.0
azure-mgmt-batch==1.0.0
azure-mgmt-batchai==0.2.0
azure-mgmt-billing==0.1.0
azure-mgmt-cdn==0.30.2
azure-mgmt-cognitiveservices==1.0.0
azure-mgmt-compute==0.33.0
azure-mgmt-consumption==1.0.0
azure-mgmt-containerinstance==0.2.0
azure-mgmt-containerregistry==1.0.1
azure-mgmt-containerservice==3.0.0
azure-mgmt-cosmosdb==0.2.1
azure-mgmt-datalake-analytics==0.2.0
azure-mgmt-datalake-nspkg==2.0.0
azure-mgmt-datalake-store==0.2.0
azure-mgmt-devtestlabs==2.0.0
azure-mgmt-dns==1.2.0
azure-mgmt-documentdb==0.1.3
azure-mgmt-eventgrid==0.2.0
azure-mgmt-iothub==0.4.0
azure-mgmt-keyvault==0.30.0rc6
azure-mgmt-logic==1.0.0
azure-mgmt-monitor==0.4.0
azure-mgmt-msi==0.1.0
azure-mgmt-network==0.30.0rc6
azure-mgmt-nspkg==2.0.0
azure-mgmt-rdbms==0.1.0
azure-mgmt-recoveryservices==0.1.0
azure-mgmt-recoveryservicesbackup==0.1.1
azure-mgmt-redis==1.0.0
azure-mgmt-reservations==0.1.0
azure-mgmt-resource==0.30.0
azure-mgmt-scheduler==1.0.0
azure-mgmt-servicefabric==0.1.0
azure-mgmt-sql==0.8.4
azure-mgmt-storage==0.30.0rc6
azure-mgmt-trafficmanager==0.40.0
azure-mgmt-web==0.34.1
azure-multiapi-storage==0.1.7
azure-nspkg==2.0.0
azure-servicebus==0.20.3
azure-servicefabric==5.6.130
azure-servicemanagement-legacy==0.20.4
azure-storage==0.32.0
msrestazure==0.4.21

**Comment by Ch3LL** [comment]
Can you share a sanitized version of your cloud profile?

**Comment by cskowronnek** [comment]
@Ch3LL Megan, here it is:

azure-es-node:
  provider: azurearm
  master: host.domain.tld
  image: Canonical|UbuntuServer|16.04-LTS|latest
  size: Standard_B4ms
  location: westeurope
  network: VNET-xxx
  subnet: VNET-xxx-Subnet1
  storage_account: xxx742
  storage_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  ssh_username: xxxxxxxxxxxxxxx
  ssh_publickeyfile: /etc/salt/cloud.profiles.d/xxxxx
  ssh_password: xxxxxxxxxxxx
  public_ip: False
  volumes:
    - {disk_size_gb: 60, name: 'Node-4-datadisk1', caching: 'ReadWrite' }

  cleanup_disks: True
  cleanup_vhds: True
  cleanup_data_disks: True
  cleanup_interfaces: True

**Comment by Ch3LL** [comment]
thanks :)

i'm having a hard time replicating this. ping @saltstack/team-cloud any ideas here?

**Comment by cskowronnek** [comment]
I've updated my SaltStack to the latest develop version and now I'm getting the following error. It has probably to do with not having a public ip for my VM.

> [ERROR   ] There was a profile error: list index out of range
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 281, in run
    self.config.get('names')
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1454, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1284, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/azurearm.py", line 1417, in create
    'wait_for_ip_interval_multiplier', vm_, __opts__, default=1),
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 2389, in wait_for_ip
    data = update_callback(*update_args, **update_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/azurearm.py", line 1401, in _query_node_data
    ip_address = data['public_ips'][0]
IndexError: list index out of range

**Comment by gtmanfred** [comment]
@nicholasmhughes can you take a look here since you have more experience with the azurearm stuff?

Thanks,
Daniel

**Comment by nicholasmhughes** [comment]
@cskowronnek check out [this comment](https://github.com/saltstack/salt/issues/44886#issuecomment-374796819)... I think it also applies to the latest error you're seeing.

There is some logic in the cloud module that needs to be tweaked, and this issue is one of those that need to be addressed.

**Comment by gtmanfred** [comment]
@nicholasmhughes thank you for the help, we greatly appreciate it.

**Comment by cskowronnek** [comment]
@nicholasmhughes As I had no success with the latest dev version, I downgraded back to 2018.3.0

Same problem as before:

> [INFO    ] Rendering deploy script: /usr/lib/python2.7/dist-packages/salt/cloud/deploy/bootstrap-salt.sh
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
[ERROR   ] There was a profile error: can't serialize <azure.mgmt.compute.models.virtual_hard_disk.VirtualHardDisk object at 0x7f4f1d406310>
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 281, in run
    self.config.get('names')
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1454, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1284, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/azurearm.py", line 1308, in create
    ret = __utils__['cloud.bootstrap'](vm_, __opts__)
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 553, in bootstrap
    transport=opts.get('transport', 'zeromq')
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 1786, in fire_event
    event.fire_event(args, tag)
  File "/usr/lib/python2.7/dist-packages/salt/utils/event.py", line 725, in fire_event
    dump_data = self.serial.dumps(data)
  File "/usr/lib/python2.7/dist-packages/salt/payload.py", line 217, in dumps
    return msgpack.dumps(msg, default=ext_type_encoder, use_bin_type=use_bin_type)
  File "/usr/lib/python2.7/dist-packages/msgpack/__init__.py", line 47, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 223, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:223)
  File "msgpack/_packer.pyx", line 225, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:225)
  File "msgpack/_packer.pyx", line 184, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:184)
  File "msgpack/_packer.pyx", line 184, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:184)
  File "msgpack/_packer.pyx", line 184, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:184)
  File "msgpack/_packer.pyx", line 213, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:213)
  File "msgpack/_packer.pyx", line 184, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:184)
  File "msgpack/_packer.pyx", line 220, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:220)
TypeError: can't serialize <azure.mgmt.compute.models.virtual_hard_disk.VirtualHardDisk object at 0x7f4f1d406310>

**Comment by cskowronnek** [comment]
Could this be a problem with the Azure SDK? The error message references to azure.mgmt.compute.models.virtual_hard_disk.VirtualHardDisk object

**Comment by nicholasmhughes** [comment]
The version of the cloud module and the version of the Azure SDK are certainly important factors. Looking at your `pip freeze` output above, you shouldn't have any trouble with the `develop` code. What problems were you encountering with `develop`?

As far as the stack trace you're seeing on `2018.3`, it looks like it's creating your instance... but it's failing at the bootstrap. The whole VM object is passed to `__utils__['cloud.bootstrap']`, and that function is passing that object inside of `event_kwargs` to `fire_event`. It's probably expecting a dictionary of "normal" types, and instead gets weird Azure objects that it doesn't know about. Truthfully, I'd rather troubleshoot the `develop` code, because there are a lot of updates that will make your life in Azure easier (although there are still some things that need to be fixed there too).

**Comment by cskowronnek** [comment]
@nicholasmhughes

Thank you for your help. I tried again with develop and I'm encountering the following error when deploying.

> [ERROR   ] There was a profile error: can't serialize <DiskCreateOptionTypes.empty: 'empty'>
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 281, in run
    self.config.get('names')
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1454, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1284, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/azurearm.py", line 1437, in create
    ret = __utils__['cloud.bootstrap'](vm_, __opts__)
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 573, in bootstrap
    transport=opts.get('transport', 'zeromq')
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 1946, in fire_event
    event.fire_event(args, tag)
  File "/usr/lib/python2.7/dist-packages/salt/utils/event.py", line 722, in fire_event
    dump_data = self.serial.dumps(data)
  File "/usr/lib/python2.7/dist-packages/salt/payload.py", line 221, in dumps
    return msgpack.dumps(msg, default=ext_type_encoder, use_bin_type=use_bin_type)
  File "/usr/lib/python2.7/dist-packages/msgpack/__init__.py", line 47, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 223, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:223)
  File "msgpack/_packer.pyx", line 225, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:225)
  File "msgpack/_packer.pyx", line 184, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:184)
  File "msgpack/_packer.pyx", line 184, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:184)
  File "msgpack/_packer.pyx", line 184, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:184)
  File "msgpack/_packer.pyx", line 213, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:213)
  File "msgpack/_packer.pyx", line 184, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:184)
  File "msgpack/_packer.pyx", line 220, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:220)
TypeError: can't serialize <DiskCreateOptionTypes.empty: 'empty'>

**Comment by nicholasmhughes** [comment]
I'm not sure what's going on there... I just installed the code from `develop` and the pip modules you listed above. I didn't have any problems creating a `Standard_DS1` VM with that setup. However, the `Standard_B4ms` size from your profile isn't present in the SDK version you're running... so, you should end up with this error:
```
[ERROR   ] There was a profile error: standard_b4ms
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/cli.py", line 281, in run
    self.config.get('names')
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1454, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1284, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/azurearm.py", line 1385, in create
    vm_request = request_instance(vm_=vm_)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/azurearm.py", line 1297, in request_instance
    VirtualMachineSizeTypes, vm_['size'].lower()
  File "/usr/lib/python2.7/site-packages/enum/__init__.py", line 390, in __getattr__
    raise AttributeError(name)
AttributeError: standard_b4ms
```
Can you verify all of the information you posted above is accurate? If it is, I'm not sure why you're failing with a `can't serialize` error instead of the size error I'm seeing.

**Comment by cskowronnek** [comment]
It's working because I added 'Standard_B4ms" to the list in /azure/mgmt/compute/models/compute_management_client_enums.py

I also tried it with Standard_DS1, same errror 
`[ERROR   ] There was a profile error: can't serialize <DiskCreateOptionTypes.empty: 'empty'>`

**Comment by cskowronnek** [comment]
Any ideas?

**Comment by nicholasmhughes** [comment]
Not really... I apologize, but I just can't reproduce the error. The section of code that's throwing the exception is outside the cloud module in the message creation for (I believe) the event to be sent on the message bus. It's probably expecting "normal" types for Packer, and doesn't know how to handle the Azure types it's seeing... but that still doesn't explain why I'm not seeing the problem with any of my testing across multiple versions. You could try spinning up a test box to make sure you have fresh Salt and Azure SDK code.

**Comment by cskowronnek** [comment]
It has something to with the additional disks.
If I comment out

`#  volumes:
#    - {disk_size_gb: 60, name: 'Elastic-Node-4-datadisk-1'}
`
everything is running fine. With the additional volumes, the error occurs.
I'm deploying to a Premium storage, LRS, General purpose v1, Resource Manager.

**Comment by nicholasmhughes** [comment]
I tested additional volumes because you listed it in your profile above. It works fine on my test system, which I loaded fresh with the versions you posted.

**Comment by nicholasmhughes** [comment]
To be clear, this looks like a failure during the event firing during/after bootstrap. Your instance should be created at this point. Can you verify that your instance was created as expected, but Salt was not installed?

To answer your question about the change in disk creation, I updated the Azure cloud module to default to managed disks per Microsoft best practices, with the ability to create unmanaged disks by passing (I'm not looking at the code right now, so I think this option is correct) `vhd: unmanaged` in the profile for OS disk or in the volume dict for a data disk. Note that you can't mix managed and unmanaged disks on a single host. This change is only present in the `develop` code, so any stable releases will still only allow you to created unmanaged disks with a storage account.

**Comment by cskowronnek** [comment]
Yes, the VM is created as expected, but without the additional disk. Salt is not installed because of the exception.

Without an additional volume, the VM is created and bootstrapped but no state is applied. (worked in 2017.x). I'll open another for said problem.

I'm using the develop code, so a managed disk should be created?

**Comment by nicholasmhughes** [comment]
Correct, the develop code should create managed disks.

**Comment by nicholasmhughes** [comment]
I took another look. I'm still not sure what changed to make this start happening, but I was able to reproduce the problem. At first glance, I thought I could just pass a return dictionary from the VM creation to the bootstrap... but that might not work properly for bootstrapping even though it stops throwing the exception. I need to test some more. Feel free to grab the one line change from the commit above and test on your own.

**Comment by nicholasmhughes** [comment]
Nope... that doesn't work. I might have some time this week to take a harder look.

**Comment by nicholasmhughes** [comment]
So, it seems this could be easily solved two ways... although they both feel kinda hacky.

We could replace the volumes list with the return data from the instance creation (which has "normal" types) before firing the bootstrap event...
```
vm_['volumes'] = vm_request['storage_profile'].get('data_disks', [])
```

...or we could use strings for the volume disk creation options instead of the Azure objects.
```
        if 'image' in volume:
            volume['create_option'] = 'from_image' #DiskCreateOptionTypes.from_image
        elif 'attach' in volume:
            volume['create_option'] = 'attach' #DiskCreateOptionTypes.attach
        else:
            volume['create_option'] = 'empty' #DiskCreateOptionTypes.empty
```

I think using the Azure objects when you pass to the API is the "right" way to create instances (per MS), but it's messing up the bootstrap and it feels like more of a workaround than using the strings. Really, I could go either way here. @gtmanfred , any best practices for code here?

**Comment by cskowronnek** [comment]
Fix #47774 works on my side
