### ISSUE TITLE
CherrPy库报错：AttributeError: 'NoneType' object has no attribute 'recv'

### ISSUE THREAD

**Issue by xuming2860** [saltstack/salt#47112]
### Description of Issue/Questiont
the salt-api is running . I used it to test websocket.When i input the code,the log said:AttributeError: 'NoneType' object has no attribute 'recv'.That mean in the Cherrypy,the type of self_sock is none.So that it doesn't have the attribute 'recv'.
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
api.conf:

```
rest_cherrypy:
  port: 8000
  #ssl_crt: /etc/pki/tls/certs/server.crt     
  #ssl_key: /etc/pki/tls/certs/server.key
  disable_ssl: True
```

eauth.conf:

```
external_auth:
  pam:
    larry:
      - .*
      - '@runner'
      - '@wheel'
    darrel:
      - test.*
      - '@runner'
      - '@wheel'
    darry1:
      - test.*
      - network.*
      - '@runner'
      - '@wheel'
```

### Steps to Reproduce Issue
Get token:

```
curl -si localhost:8000/login \
        -H "Accept: application/json" \
        -d username='larry' \
        -d password='123pass' \
        -d eauth='pam'
X-Auth-Token: 6cb25f06ed1854033df003752d0caf15759da931
```

```
curl -NsS \
    -H 'X-Auth-Token: 6cb25f06ed1854033df003752d0caf15759da931' \
    -H 'Host: localhost:8000' \
    -H 'Connection: Upgrade' \
    -H 'Upgrade: websocket' \
    -H 'Origin: http://localhost:8000' \
    -H 'Sec-WebSocket-Version: 13' \
    -H 'Sec-WebSocket-Key: dGhlIHNhbXBsZSBub25jZQ==' \
    localhost:8000/ws
```

It return nothing .and we can see the error in log:

```
2018-04-17 11:14:56,116 [cherrypy.error   :201 ][ERROR   ][6260] [17/Apr/2018:11:14:56] ENGINE AttributeError("'NoneType' object has no attribute 'recv'",)
Traceback (most recent call last):
  File "/home/charles/anaconda2/envs/pysalt/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 1292, in communicate
    req.parse_request()
  File "/home/charles/anaconda2/envs/pysalt/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 580, in parse_request
    success = self.read_request_line()
  File "/home/charles/anaconda2/envs/pysalt/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 611, in read_request_line
    request_line = self.rfile.readline()
  File "/home/charles/anaconda2/envs/pysalt/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 274, in readline
    data = self.rfile.readline(256)
  File "/home/charles/anaconda2/envs/pysalt/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 1114, in readline
    data = self.recv(self._rbufsize)
  File "/home/charles/anaconda2/envs/pysalt/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 990, in recv
    data = self._sock.recv(size)
AttributeError: 'NoneType' object has no attribute 'recv'
```

### Versions Report
os: Ubuntu
the version of salt: salt 2018.3.0 (Oxygen)
the version of salt-api: salt-api 2018.3.0 (Oxygen)
the version of CherrPy: CherryPy (3.2.3)
the version of python : python2.7.14

**Comment by xuming2860** [comment]
ws4py(0.5.1)

**Comment by Ch3LL** [comment]
i'm still not able to replicate this. ping @saltstack/team-netapi any ideas here?
