### ISSUE TITLE
TypeError: unicode not allowed, use setsockopt_string

### ISSUE THREAD

**Issue by tjuup** [saltstack/salt#47144]
### Description of Issue/Question
After upgrading the salt-master to 2018.3.0 I see these errors in the master log:
Everything seems to work though.

<snip>

> 2018-04-18 08:56:11,164 [salt.utils.process:754 ][ERROR   ][13908] An un-handled exception from the multiprocessing process 'ConnectedCache-111' was caught:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/salt/utils/process.py", line 747, in _run
>     return self._original_run()
>   File "/usr/lib/python2.7/dist-packages/salt/utils/master.py", line 569, in run
>     cupd_in.setsockopt(zmq.SUBSCRIBE, '')
>   File "socket.pyx", line 310, in zmq.backend.cython.socket.Socket.set (zmq/backend/cython/socket.c:3219)
> TypeError: unicode not allowed, use setsockopt_string
> 2018-04-18 08:56:21,182 [salt.utils.process:754 ][ERROR   ][13941] An un-handled exception from the multiprocessing process 'ConnectedCache-112' was caught:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/salt/utils/process.py", line 747, in _run
>     return self._original_run()
>   File "/usr/lib/python2.7/dist-packages/salt/utils/master.py", line 569, in run
>     cupd_in.setsockopt(zmq.SUBSCRIBE, '')
>   File "socket.pyx", line 310, in zmq.backend.cython.socket.Socket.set (zmq/backend/cython/socket.c:3219)
> TypeError: unicode not allowed, use setsockopt_string
> 2018-04-18 08:56:31,202 [salt.utils.process:754 ][ERROR   ][13954] An un-handled exception from the multiprocessing process 'ConnectedCache-113' was caught:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/salt/utils/process.py", line 747, in _run
>     return self._original_run()
>   File "/usr/lib/python2.7/dist-packages/salt/utils/master.py", line 569, in run
>     cupd_in.setsockopt(zmq.SUBSCRIBE, '')
>   File "socket.pyx", line 310, in zmq.backend.cython.socket.Socket.set (zmq/backend/cython/socket.c:3219)
> TypeError: unicode not allowed, use setsockopt_string

<end snip>

### Versions Report
# salt --versions-report

> Salt Version:
>            Salt: 2018.3.0
>  
> Dependency Versions:
>            cffi: Not Installed
>        cherrypy: 3.2.2
>        dateutil: 1.5
>       docker-py: Not Installed
>           gitdb: 0.5.4
>       gitpython: 0.3.2 RC1
>           ioflo: Not Installed
>          Jinja2: 2.7.2
>         libgit2: Not Installed
>         libnacl: Not Installed
>        M2Crypto: Not Installed
>            Mako: Not Installed
>    msgpack-pure: Not Installed
>  msgpack-python: 0.4.6
>    mysql-python: 1.2.3
>       pycparser: Not Installed
>        pycrypto: 2.6.1
>    pycryptodome: Not Installed
>          pygit2: Not Installed
>          Python: 2.7.6 (default, Nov 23 2017, 15:49:48)
>    python-gnupg: Not Installed
>          PyYAML: 3.10
>           PyZMQ: 14.4.0
>            RAET: Not Installed
>           smmap: 0.8.2
>         timelib: Not Installed
>         Tornado: 4.2.1
>             ZMQ: 4.0.5
>  
> System Versions:
>            dist: Ubuntu 14.04 trusty
>          locale: ISO-8859-1
>         machine: x86_64
>         release: 3.13.0-144-generic
>          system: Linux
>         version: Ubuntu 14.04 trusty

**Comment by tjuup** [comment]
Fixed by applying this fix for python3 although we still use python2.7
https://github.com/saltstack/salt/pull/46878/files
