### ISSUE TITLE
salt2018.3 cpu problem.

### ISSUE THREAD

**Issue by Zambozo** [saltstack/salt#47171]
### Description of Issue/Question

The CPU load of the if the server is beyond normal.

I have noticed that salt master is taking for ever to respond to one test.ping 

load average: 3025.51, 3041.50, 3102.71

this is ec2 m3.medium 

the log is full of ::
```
2018-04-19 06:50:35,156 [salt.utils.process:754 ][ERROR   ][5860] An un-handled exception from the multiprocessing process 'ConnectedCache-4589' was caught:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/process.py", line 747, in _run
    return self._original_run()
  File "/usr/lib/python2.7/site-packages/salt/utils/master.py", line 569, in run
    cupd_in.setsockopt(zmq.SUBSCRIBE, '')
  File "socket.pyx", line 374, in zmq.backend.cython.socket.Socket.set (zmq/backend/cython/socket.c:3959)
TypeError: unicode not allowed, use setsockopt_string
2018-04-19 06:51:04,529 [salt.utils.process:754 ][ERROR   ][5921] An un-handled exception from the multiprocessing process 'ConnectedCache-4590' was caught:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/process.py", line 747, in _run
    return self._original_run()
  File "/usr/lib/python2.7/site-packages/salt/utils/master.py", line 569, in run
    cupd_in.setsockopt(zmq.SUBSCRIBE, '')
  File "socket.pyx", line 374, in zmq.backend.cython.socket.Socket.set (zmq/backend/cython/socket.c:3959)
TypeError: unicode not allowed, use setsockopt_string
2018-04-19 06:51:42,816 [salt.utils.process:754 ][ERROR   ][5949] An un-handled exception from the multiprocessing process 'ConnectedCache-4591' was caught:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/process.py", line 747, in _run
    return self._original_run()
  File "/usr/lib/python2.7/site-packages/salt/utils/master.py", line 569, in run
    cupd_in.setsockopt(zmq.SUBSCRIBE, '')
  File "socket.pyx", line 374, in zmq.backend.cython.socket.Socket.set (zmq/backend/cython/socket.c:3959)
TypeError: unicode not allowed, use setsockopt_string
```

### Versions Report
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.2 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.21.1.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.2 Maipo

P.S. First time ever reporting if i messed up please tell me how to fix it :)

**Comment by gtmanfred** [comment]
> P.S. First time ever reporting if i messed up please tell me how to fix it :)

You did great.  Can you also provide your master config file, so that I can use that to try and replicate this issue?

Thanks,
Daniel

**Comment by Zambozo** [comment]
Hello I have added the changed in ht master config file 

`[root]$ cat /etc/salt/master | egrep -v "(^#.*|^$)"
worker_threads: 20
extension_modules: /srv/pillar/ext_pillar
timeout: 15
minion_data_cache: True
external_auth:
  pam:
    veka:
        - .*
        - '@runner'
        - '@wheel'
verify_ssl: False
ext_pillar_first: True
rest_tornado:
  port: 5417
  host: 127.0.0.1
  disable_ssl: true
  websockets: True
  cors_origin: '*'
presence_events: True
`

**Comment by gtmanfred** [comment]
How many minions do you have?

**Comment by Zambozo** [comment]
Hello,

I am having 22 to 30 minions.

I am seeing this issue over 3 salt-master in 3 region in AWS with sameoutput in the logs

**Comment by gtmanfred** [comment]
Looks like your first issue has been fixed in this PR https://github.com/saltstack/salt/pull/46874 which has been backported for 2018.3.1.

As for the load, you shouldn't need 20 worker threads to handle only 20-30 minions, you should be fine with 5 worker threads.

Can you install [setproctitle](https://pypi.org/project/setproctitle/) , i am pretty sure it is called `python-setproctitle` in the redhat yum repositories, but it might be in epel.  And check the processes, and see which one is running at 100%? setproctitle, will give you the titles of the salt-master processes, like MWorker-1, etc.
