### ISSUE TITLE
ZeroMQ Version 3.2.4 not compatible with salt-call 2016.11.6

### ISSUE THREAD

**Issue by rehmanzile** [saltstack/salt#47205]
### Description of Issue/Question
ZeroMQ needs to be upgraded to `3.2.4` from the default `3.0.0` version. Upon doing so, `salt-call` command no longer works.

### Setup
`salt-master` and `salt-minion` and other other salt packages are using `2016.11.6` version.

### Steps to Reproduce Issue

1. Install `salt-minion` and `salt-common` version `2016.11.6` on Ubuntu 14.04. 
2. Install `zeromq` version `3.2.4`
```
cd ~
export z_ver=3.2.4
wget http://download.zeromq.org/zeromq-${z_ver}.tar.gz
tar xvzf zeromq-${z_ver}.tar.gz
sudo apt-get update && sudo apt-get install -y libtool pkg-config build-essential autoconf automake uuid-dev
cd zeromq-${z_ver}
./configure --prefix=/ur && sudo make install
sudo ldconfig
ldconfig -p | grep zmq
```

3. This command `sudo salt-call grains.items` throws the following failure
```
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
ImportError: No module named cffi
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 391, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 48, in run
    caller = salt.cli.caller.Caller.factory(self.config)
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 79, in factory
    return ZeroMQCaller(opts, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 283, in __init__
    super(ZeroMQCaller, self).__init__(opts)
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 102, in __init__
    self.minion = salt.minion.SMinion(opts)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 657, in __init__
    lambda: self.eval_master(self.opts, failed=True)
  File "/usr/lib/python2.7/dist-packages/tornado/ioloop.py", line 445, in run_sync
    return future_cell[0].result()
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 230, in wrapper
    yielded = next(result)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 625, in eval_master
    pub_channel = salt.transport.client.AsyncPubChannel.factory(self.opts, **factory_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/client.py", line 161, in factory
    import salt.transport.zeromq
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 33, in <module>
    import zmq
  File "/usr/lib/python2.7/dist-packages/zmq/__init__.py", line 62, in <module>
    from zmq.backend import *
  File "/usr/lib/python2.7/dist-packages/zmq/backend/__init__.py", line 22, in <module>
    _ns = select_backend('zmq.backend.cffi')
  File "/usr/lib/python2.7/dist-packages/zmq/backend/select.py", line 31, in select_backend
    mod = __import__(name, fromlist=public_api)
ImportError: No module named cffi
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 391, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 48, in run
    caller = salt.cli.caller.Caller.factory(self.config)
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 79, in factory
    return ZeroMQCaller(opts, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 283, in __init__
    super(ZeroMQCaller, self).__init__(opts)
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 102, in __init__
    self.minion = salt.minion.SMinion(opts)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 657, in __init__
    lambda: self.eval_master(self.opts, failed=True)
  File "/usr/lib/python2.7/dist-packages/tornado/ioloop.py", line 445, in run_sync
    return future_cell[0].result()
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 230, in wrapper
    yielded = next(result)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 625, in eval_master
    pub_channel = salt.transport.client.AsyncPubChannel.factory(self.opts, **factory_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/client.py", line 161, in factory
    import salt.transport.zeromq
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 33, in <module>
    import zmq
  File "/usr/lib/python2.7/dist-packages/zmq/__init__.py", line 62, in <module>
    from zmq.backend import *
  File "/usr/lib/python2.7/dist-packages/zmq/backend/__init__.py", line 22, in <module>
    _ns = select_backend('zmq.backend.cffi')
  File "/usr/lib/python2.7/dist-packages/zmq/backend/select.py", line 31, in select_backend
    mod = __import__(name, fromlist=public_api)
ImportError: No module named cffi
```

### Versions Report
```
$ sudo salt-call --versions-report
Salt Version:
           Salt: 2016.11.6
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.2.0-27-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by Ch3LL** [comment]
looks like the error here: `ImportError: No module named cffi` just requires that package. if you install the python cffi module do you still see this ?

**Comment by rehmanzile** [comment]
Yes. Which version of zmq do you support? `3.0.0`?
