### ISSUE TITLE
pillar.ls or pillar.item fails from client API

### ISSUE THREAD

**Issue by golmaal** [saltstack/salt#47209]
Install salt master and minion as following - 
```
curl -o bootstrap-salt.sh -L https://bootstrap.saltstack.com
sh ./bootstrap-salt.sh -M git v2017.7.5
```
Check that pillar.ls succeeds after modifying /etc/hosts for salt hostname and accepting the key
```
# salt-call pillar.ls
local:
```
Try to do the same thing from the python client APIs
```
# python
>>> import salt.config
>>> import salt.loader
>>>
>>> __opts__ = salt.config.minion_config('/etc/salt/minion')
>>> __grains__ = salt.loader.grains(__opts__)
>>> __opts__['grains'] = __grains__
>>> __utils__ = salt.loader.utils(__opts__)
>>> __salt__ = salt.loader.minion_mods(__opts__, utils=__utils__)
>>> __salt__['pillar.ls']()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/salt/modules/pillar.py", line 339, in ls
    return list(items(*args).keys())
  File "/usr/lib/python2.7/site-packages/salt/modules/pillar.py", line 268, in items
    pillarenv=pillarenv)
  File "/usr/lib/python2.7/site-packages/salt/pillar/__init__.py", line 57, in get_pillar
    pillar_override=pillar_override, pillarenv=pillarenv)
  File "/usr/lib/python2.7/site-packages/salt/pillar/__init__.py", line 139, in __init__
    self.channel = salt.transport.Channel.factory(opts)
  File "/usr/lib/python2.7/site-packages/salt/transport/__init__.py", line 53, in factory
    return ReqChannel.factory(opts, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/transport/client.py", line 25, in factory
    sync = SyncWrapper(AsyncReqChannel.factory, (opts,), kwargs)
  File "/usr/lib/python2.7/site-packages/salt/utils/async.py", line 60, in __init__
    self.async = method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/transport/client.py", line 108, in factory
    return salt.transport.zeromq.AsyncZeroMQReqChannel(opts, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/transport/zeromq.py", line 95, in __new__
    obj.__singleton_init__(opts, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/transport/zeromq.py", line 154, in __singleton_init__
    self.auth = salt.crypt.AsyncAuth(self.opts, io_loop=self._io_loop)
  File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 372, in __new__
    key = cls.__key(opts)
  File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 390, in __key
    opts['master_uri'],  # master ID
KeyError: 'master_uri'
```

Version Report
```
salt --versions-report
Salt Version:
           Salt: 2017.7.5

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.17.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

This issue is present in v2017.7.3 as well, so it's not a regression in v2017.7.5.

**Comment by Ch3LL** [comment]
from the docs here: https://docs.saltstack.com/en/latest/ref/clients/#salt-s-loader-interface 

>Most modules can be manually loaded. This is often useful in third-party Python apps or when writing tests. However some modules require and expect a full, running Salt system underneath. Notably modules that facilitate master-to-minion communication such as the mine, publish, and peer execution modules. The error KeyError: 'master_uri' is a likely indicator for this situation. In those instances use the Caller class to execute those modules instead.

If you use the caller class it should work for you

**Comment by golmaal** [comment]
@Ch3LL using Caller does work. 
Very strange, I had searched for master_uri earlier, but don't remember seeing the page you shared. Thanks!
