### ISSUE TITLE
Host Present State - Fails with Error "Unicode is not supported"

### ISSUE THREAD

**Issue by Silvenga** [saltstack/salt#47215]
### Description of Issue/Question

When using the host present state, the salt minion throws a `Unicode is not supported` error. This appears to only exist on Windows hosts using Python 2 (although, I haven't tested this).

### Setup
```yaml
Add host entry:
  host.present:
    - name: example.com
    - ip: 127.0.0.1
```

### Steps to Reproduce Issue

Apply the above state on a Windows host.

The following is returned:

```
          ID: Add host entry
    Function: host.present
        Name: example.com
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "C:\salt\bin\lib\site-packages\salt\state.py", line 1878, in call
                  **cdata['kwargs'])
                File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1823, in wrapper
                  return f(*args, **kwargs)
                File "C:\salt\bin\lib\site-packages\salt\states\host.py", line 97, in present
                  if salt.utils.validate.net.ipv4_addr(_ip) or salt.utils.validate.net.ipv6_addr(_ip):
                File "C:\salt\bin\lib\site-packages\salt\utils\validate\net.py", line 73, in ipv4_addr
                  return __ip_addr(addr, socket.AF_INET)
                File "C:\salt\bin\lib\site-packages\salt\utils\validate\net.py", line 52, in __ip_addr
                  socket.inet_pton(address_family, ip)
                File "C:\salt\bin\lib\site-packages\salt\ext\win_inet_pton.py", line 40, in inet_pton
                  ipaddress.ip_address(six.u(ip_string))
                File "C:\salt\bin\lib\site-packages\salt\ext\six.py", line 654, in u
                  return unicode(s.replace(r'\\', r'\\\\'), "unicode_escape")
              TypeError: decoding Unicode is not supported
     Started: 14:45:31.440000
    Duration: 0.0 ms
     Changes:
```

### Versions Report

```
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.2
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2016Server
         system: Windows
        version: 2016Server 10.0.14393  Multiprocessor Free
```

**Comment by garethgreenaway** [comment]
@dwoz @twangboy Thoughts on this one?

**Comment by Silvenga** [comment]
Did some more testing, considering the following command:

```
C:\salt\salt-call hosts.set_host "127.0.0.1" "example.com"
```

When the host file is encoded via ANSI, the modifications are correct.

```
127.0.0.1               example.com
```

When the host file is encoded via Unicode, junk is added to the hosts file:

![image](https://user-images.githubusercontent.com/2753330/39282920-1ef579b4-48d1-11e8-8462-f7bab72f4971.png)

**Comment by Silvenga** [comment]
It appears if Powershell creates or overwrites a file, these files will be encoded in Unicode. The default encoding for the host file is ANSI.

**Comment by twangboy** [comment]
There's a lengthy discussion about this in https://github.com/saltstack/salt/issues/47274
I wonder if the hosts file even works when encoded utf-16

**Comment by twangboy** [comment]
This issue is actually fixed by this PR: https://github.com/saltstack/salt/pull/46219

Should be in the next release (2018.3.1)
