### ISSUE TITLE
Installing SaltStack via RHEL Repo with Kickstart file sometimes fails

### ISSUE THREAD

**Issue by Fauxsys** [saltstack/salt#47229]
### Description of Issue/Question

When I build an ISO based from my anaconda kickstart file, the salt-master is sometimes not installed correctly (and reinstalling salt-master does not resolve the problem). The installation is performed with the commands:
```
yum install https://repo.saltstack.com/yum/redhat/salt-repo-latest-2.el7.noarch.rpm  -y
yum install salt-master -y
```

Stack Trace:
```
2018-04-22 03:07:13,118 [salt.cli.daemons :85  ][INFO    ][988] Setting up the Salt Master
2018-04-22 03:07:13,331 [salt.log.setup   :1165][ERROR   ][988] An un-handled exception was caught by salt's global exception handler:
IndexError: string index out of range
Traceback (most recent call last):
  File "/usr/bin/salt-master", line 22, in <module>
    salt_master()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 97, in salt_master
    master.start()
  File "/usr/lib/python2.7/site-packages/salt/cli/daemons.py", line 211, in start
    super(Master, self).start()
  File "/usr/lib/python2.7/site-packages/salt/utils/parsers.py", line 1036, in start
    self.prepare()
  File "/usr/lib/python2.7/site-packages/salt/cli/daemons.py", line 192, in prepare
    self.master = salt.master.Master(self.config)
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 496, in __init__
    SMaster.__init__(self, opts)
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 110, in __init__
    self.master_key = salt.crypt.MasterKeys(self.opts)
  File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 328, in __init__
    self.key = self.__get_keys(passphrase=key_pass)
  File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 398, in __get_keys
    key = get_rsa_key(path, passphrase)
  File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 201, in get_rsa_key
    return _get_key_with_evict(path, six.text_type(os.path.getmtime(path)), passphrase)
  File "/usr/lib/python2.7/site-packages/salt/utils/decorators/__init__.py", line 185, in _memoize
    cache[args_] = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 185, in _get_key_with_evict
    key = RSA.importKey(f.read(), passphrase)
  File "/usr/lib64/python2.7/site-packages/Crypto/PublicKey/RSA.py", line 678, in importKey
    if bord(externKey[0])==0x30:
IndexError: string index out of range
```

### Setup
The lines specific to Salt are in [anaconda-ks.cfg](https://github.com/Fauxsys/Erratum/blob/master/anaconda-ks.cfg#L63-L68). I have also attached [ks-post.log](https://github.com/saltstack/salt/files/1935301/ks-post.log) which shows the successful installation of salt-master despite the service failing to properly start.

### Steps to Reproduce Issue
The problem is not always 100% reproducible, but has occurred frequently while testing within VMware Workstation. Using the same .ISO file, the result will either be salt-master installed and running correctly, or salt-master installed but failing to start as a result of the above stack trace.

### Versions Report
```
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.21.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

**Comment by garethgreenaway** [comment]
@Fauxsys Thanks for the report.  In the event that an installation fails, can you verify if the Salt master has generated it's keys under /etc/salt/pki/master?

**Comment by Fauxsys** [comment]
I'm going to close this as I haven't had time to reproduce the issue. I also plan to migrate my testing platform from VMware to Docker, so chances are I will not re-encounter this issue.
