### ISSUE TITLE
Unable to load salt_proxy beacon on minion in 2018.3.0

### ISSUE THREAD

**Issue by bosatsu** [saltstack/salt#47239]
### Description of Issue/Question
After configuring salt_proxy beacons in either `/etc/salt/minion` or `/etc/salt/minion.d/beacons.conf` , following the format in the documentation:

https://docs.saltstack.com/en/latest/ref/beacons/all/salt.beacons.salt_proxy.html#module-salt.beacons.salt_proxy

then starting the salt minion, salt begins to loop through the following error:

```
[TRACE   ] Beacon processing: salt_proxy
[DEBUG   ] LazyLoaded salt_proxy.beacon
[CRITICAL] The beacon errored:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 2484, in handle_beacons
    beacons = self.process_beacons(self.functions)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 444, in process_beacons
    return self.beacons.process(b_conf, self.opts['grains'])  # pylint: disable=no-member
  File "/usr/lib/python2.7/site-packages/salt/beacons/__init__.py", line 104, in process
    valid, vcomment = self.beacons[validate_str](b_config[mod])
TypeError: 'NoneType' object is not iterable
[TRACE   ] ==== evaluating schedule now None =====
[DEBUG   ] LazyLoaded status.master
[TRACE   ] Beacon processing: salt_proxy
[CRITICAL] The beacon errored:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 2484, in handle_beacons
    beacons = self.process_beacons(self.functions)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 444, in process_beacons
    return self.beacons.process(b_conf, self.opts['grains'])  # pylint: disable=no-member
  File "/usr/lib/python2.7/site-packages/salt/beacons/__init__.py", line 104, in process
    valid, vcomment = self.beacons[validate_str](b_config[mod])
TypeError: 'NoneType' object is not iterable
```

### Setup
Beacon Config:
```
beacons:
  salt_proxy:
    - proxies:
        device1: {}
        device2: {}
        device3: {}
        device4: {}
```

Salt Master Pillar:
```
base:

  minion1:
    - minion_data

  device1:
    - lab-device1_pillar
  device2:
    - lab-device2_pillar
  device3:
    - lab-device3_pillar
  device4:
    - lab-device4_pillar
```

lab-device1_pillar
```
proxy:
  proxytype: napalm
  driver: nxos_ssh
  host: 1.1.1.1
  username: cisco
  password: cisco
```

### Steps to Reproduce Issue
Place above `Beacon Config` in either `/etc/salt/minion` or `/etc/salt/minion.d/beacons.conf` and then start the salt-minion:

`salt-minion -l trace`

 
### Versions Report

Salt Master
```
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.21.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

Salt Minion
```
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.28.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.21.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

**Comment by bosatsu** [comment]
Thank you for taking up this issue.  Not sure if this should be added, but I also think the documentation needs to be updated here:

https://docs.saltstack.com/en/latest/topics/proxyminion/beacon.html

to include `-proxies:` in the yaml code block under `Configure the salt_proxy beacon`

**Comment by garethgreenaway** [comment]
@bosatsu It is possible to use the updated version if you download the following and place it on your master master under /srv/salt/_beacons, then run `saltutil.sync_all` on all the Salt minions that you want to use the new version of the proxy beacon.  One caveat, this will override any future additions that are installed on the minions, so once 2018.3.1 is release it would be best to remove that file from /srv/salt/_beacons.

**Comment by bosatsu** [comment]
@garethgreenaway Okay understood. Thank you for the response and for the quick response on the bug fix!
