### ISSUE TITLE
Reopen Windows Minion That Has IAM Role Cannot Access to S3

### ISSUE THREAD

**Issue by isdig** [saltstack/salt#47269]
### Description of Issue/Question

I reopened this #47176 issue because the thing @gtmanfred mentioned actually works. In addition to following screenshots from earlier I can also access the file and download it by running Python Boto modules directly from the Windows machine. 

gtmanfred's SS: I don't know it was typo or intentional to show me 404 but your IAM role is "gttest". Instead "gtest" is written at the end of second request.

![](https://user-images.githubusercontent.com/732321/39003125-d1ba4f96-43bf-11e8-8dab-ac7e388b8df5.png)

**My SS:**

![](https://user-images.githubusercontent.com/37999536/39032803-cb153012-4477-11e8-956e-50175baeb2cb.JPG)

Trying to download a file from AWS S3 to my Windows minion (IAM role is attached) but it says 

> ERROR: Failed to get file. InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.

I can get the file by declaring s3.keyid and s3.key in minion config file but I need to do it via IAM Role. 

BTW I also can access to the file using the same IAM role on **Linux minions** (they are both ubuntu and one of them is my master/minion called "salt-master-minion") .  

[Related Doc](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.s3.html)

This page says you have to do _no additional configuration_ for IAM method to work. That's true for only Linux minions in my case.

### Setup
**Minion Config**

`master: master's-private-ip`

### Steps to Reproduce Issue
The command I'm trying to run:

`salt 'miniwin' s3.get mybucket index.html local_file="C:\index.html -l trace`

Tracelog
```
 root@ip-my-private-ip:/etc/salt# salt 'mini*' s3.get mybucket index.html local_file="C:\index.html" -l trace
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/roots.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/roots.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt-master-minion
[DEBUG   ] Missing configuration file: /root/.saltrc
[TRACE   ] The required configuration section, 'fluent_handler', was not found the in the configuration. Not loading the fluent logging handlers module.
[TRACE   ] None of the required configuration sections, 'logstash_udp_handler' and 'logstash_zmq_handler', were found in the configuration. Not loading the Logstash logging handlers module.
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/roots.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/roots.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt-master-minion
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/master', u'salt-master-minion_master', u'tcp://127.0.0.1:4506', u'clear')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://127.0.0.1:4506
[DEBUG   ] Trying to connect to: tcp://127.0.0.1:4506
[TRACE   ] Inserted key into loop_instance_map id 140155722460408 for key (u'/etc/salt/pki/master', u'salt-master-minion_master', u'tcp://127.0.0.1:4506', u'clear') and process 10612
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[TRACE   ] IPCClient: Connecting to socket: /var/run/salt/master/master_event_pub.ipc
[TRACE   ] func get_cli_event_returns()
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/ed/12954a04f58e539be6ea6df6c04eea5b8caaf8e511c436e9ecbb4ef8c10aef/.minions.p
[DEBUG   ] get_iter_returns for jid 20180419103735507121 sent to set(['miniwin']) will timeout at 10:37:40.514718
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] get_event() received = {u'tag': 'salt/job/20180419103735507121/new', u'data': {u'tgt_type': u'glob', u'jid': u'20180419103735507121', u'tgt': u'mini*', u'missing': [], u'_stamp': u'2018-04-19T10:37:35.507688', u'user': u'sudo_ubuntu', u'arg': [u'mybucket', u'index.html', {u'local_file': u'C:\\index.html', u'__kwarg__': True}], u'fun': u's3.get', u'minions': [u'miniwin']}}
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[DEBUG   ] Checking whether jid 20180419103735507121 is still running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/master', u'salt-master-minion_master', u'tcp://127.0.0.1:4506', u'clear')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://127.0.0.1:4506
[DEBUG   ] Trying to connect to: tcp://127.0.0.1:4506
[TRACE   ] Inserted key into loop_instance_map id 140155705480472 for key (u'/etc/salt/pki/master', u'salt-master-minion_master', u'tcp://127.0.0.1:4506', u'clear') and process 10612
[TRACE   ] get_event() caching unwanted event = {u'tag': '20180419103740603869', u'data': {u'_stamp': u'2018-04-19T10:37:40.604131', u'minions': [u'miniwin']}}
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] get_event() caching unwanted event = {u'tag': 'salt/job/20180419103740603869/new', u'data': {u'tgt_type': u'list', u'jid': u'20180419103740603869', u'tgt': [u'miniwin'], u'missing': [], u'_stamp': u'2018-04-19T10:37:40.604463', u'user': u'sudo_ubuntu', u'arg': [u'20180419103735507121'], u'fun': u'saltutil.find_job', u'minions': [u'miniwin']}}
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] get_event() returning cached event = {u'tag': 'salt/job/20180419103740603869/new', u'data': {u'tgt_type': u'list', u'jid': u'20180419103740603869', u'tgt': [u'miniwin'], u'missing': [], u'_stamp': u'2018-04-19T10:37:40.604463', u'user': u'sudo_ubuntu', u'arg': [u'20180419103735507121'], u'fun': u'saltutil.find_job', u'minions': [u'miniwin']}}
[DEBUG   ] Passing on saltutil error. Key 'u'retcode' missing from client return. This may be an error in the client.
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] get_event() caching unwanted event = {u'tag': 'salt/job/20180419103735507121/ret/miniwin', u'data': {u'fun_args': [u'mybucket', u'index.html', {u'local_file': u'C:\\index.html'}], u'jid': u'20180419103735507121', u'return': u'ERROR: Failed to get file. InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.', u'success': False, u'cmd': u'_return', u'_stamp': u'2018-04-19T10:37:42.051021', u'fun': u's3.get', u'id': u'miniwin', u'out': u'nested'}}
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] get_event() returning cached event = {u'tag': 'salt/job/20180419103735507121/ret/miniwin', u'data': {u'fun_args': [u'mybucket', u'index.html', {u'local_file': u'C:\\index.html'}], u'jid': u'20180419103735507121', u'return': u'ERROR: Failed to get file. InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.', u'success': False, u'cmd': u'_return', u'_stamp': u'2018-04-19T10:37:42.051021', u'fun': u's3.get', u'id': u'miniwin', u'out': u'nested'}}
[DEBUG   ] jid 20180419103735507121 return from miniwin
[DEBUG   ] return event: {u'miniwin': {u'jid': u'20180419103735507121', u'ret': u'ERROR: Failed to get file. InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.', u'out': u'nested'}}
[DEBUG   ] LazyLoaded nested.output
[TRACE   ] data = {u'miniwin': u'ERROR: Failed to get file. InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.'}
miniwin:
    ERROR: Failed to get file. InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.
[TRACE   ] _get_event() waited 0 seconds and received nothing
[DEBUG   ] jid 20180419103735507121 found all minions set([u'miniwin'])

```

### Versions
**Master**:
```
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-1054-aws
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Minion**

```
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.2
            ZMQ: 4.1.6
 
System Versions:
           dist:   
         locale: cp1252
        machine: AMD64
        release: 2016Server
         system: Windows
        version: 2016Server 10.0.14393 SP0 Multiprocessor Free

```

**Comment by gtmanfred** [comment]
Ahh yes, that was a typo, sorry, i meant to reopen the other issue.

**Comment by gtmanfred** [comment]
Hrm, I am still unable to replicate this issue.

![screen shot 2018-04-24 at 9 45 31 am](https://user-images.githubusercontent.com/732321/39194911-4c6f8df4-47a4-11e8-86e6-b7c366e23e8a.png)


I can get information about the s3 buckets without setting anything but the location to pull from.

Can you try just `s3.get` without any arguments and see if it can list buckets?

Thanks,
Daniel

**Comment by isdig** [comment]
![winsalt2](https://user-images.githubusercontent.com/37999536/39229874-165bb822-486d-11e8-9e44-ca26d8b7365c.JPG)

My instance and bucket are in Canada but as you stated I put this "s3.location: us-east-1" in minion conf file so it can get the list.

**Comment by gtmanfred** [comment]
Can you go into IAM, and just double check which permissions you have assigned to that iam role?

**Comment by isdig** [comment]
It has S3 Full, EC2 Full and IAM Full Access and again I can get the bucket list on my Ubuntu master-minion with the same command that I copied from here.

**Comment by dwoz** [comment]
I have tried to re-produce this, unsuccessfully. Providing "S3FullAccess" to an AIM role allows me to access an S3 bucket with this command
```
 C:\salt\salt-call.bat --local s3.get dwoz index.html local_file="C:\index.html" -l trace
```
The response is:
```
local:
    Saved to local file: C:\index.html
```

Something I've noticed which I can not explain is, when the AIM doesn't have permissions to S3 I receive an `Access Denied` response. The only way I am able to get the error reported is by removing the AIM role all together.

When the instance does *not* have an AIM role I get this response:

`ERROR: Failed to get file. InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.`

**Comment by dwoz** [comment]
@isdig 

Both @gtmanfred and myself have tried to reproduce this with no success. Can you please check your set up one more time by validating your minion does not have a key defined in it's config, and the instance has the proper IAM role? If the problem persists we need some more debug info..  Seeing your config files (with sensitive info redacted) and any other logs you can provide might help.

**Comment by isdig** [comment]
It's the same error for me every single time even if there is no S3FullAccess within role. I can get all the bucket list with 
`aws s3api list-buckets`
if AWS CLI's installed. 

I've just launched a new instance with regular base image and only installed Python 3.6.5 and Salt (Both are 32-bit). My Salt Minion config file just contains these.

```
master: salt //  or my master's ip. I don't think this matters.
s3.location: us-east-1 // for bucket list. I'll just delete this if I want to get item from my Canadian S3.
```

Here is the debug from new server. As you can see it gives 404 when my role is added. (Again, I can access to that url from browser in my instance)

```
C:\Users\Administrator>C:\salt\salt-call.bat --local s3.get oztest index.html local_file="C:\index.html" -l trace
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Using cached minion ID from c:\salt\conf\minion_id: EC2AMAZ-T7PBHCJ.ca-central-1.compute.internal
[TRACE   ] The required configuration section, 'fluent_handler', was not found the in the configuration. Not loading the fluent logging handlers module.
[TRACE   ] None of the required configuration sections, 'logstash_udp_handler' and 'logstash_zmq_handler', were found in the configuration. Not loading the Logstash logging handlers module.
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[TRACE   ] 'dig' could not be found in the following search path: '['C:\\Windows\\system32', 'C:\\Windows', 'C:\\Windows\\System32\\Wbem', 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\', 'C:\\Program Files\\Amazon\\cfn-bootstrap\\', 'C:\\salt', 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python36-32\\Scripts\\', 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python36-32\\', 'C:\\Users\\Administrator\\AppData\\Local\\Microsoft\\WindowsApps', '', 'C:\\salt\\bin\\lib\\site-packages\\pywin32_system32']'
[TRACE   ] 'drill' could not be found in the following search path: '['C:\\Windows\\system32', 'C:\\Windows', 'C:\\Windows\\System32\\Wbem', 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\', 'C:\\Program Files\\Amazon\\cfn-bootstrap\\', 'C:\\salt', 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python36-32\\Scripts\\', 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python36-32\\', 'C:\\Users\\Administrator\\AppData\\Local\\Microsoft\\WindowsApps', '', 'C:\\salt\\bin\\lib\\site-packages\\pywin32_system32']'
[TRACE   ] 'host' could not be found in the following search path: '['C:\\Windows\\system32', 'C:\\Windows', 'C:\\Windows\\System32\\Wbem', 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\', 'C:\\Program Files\\Amazon\\cfn-bootstrap\\', 'C:\\salt', 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python36-32\\Scripts\\', 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python36-32\\', 'C:\\Users\\Administrator\\AppData\\Local\\Microsoft\\WindowsApps', '', 'C:\\salt\\bin\\lib\\site-packages\\pywin32_system32']'
[TRACE   ] 'dmidecode' could not be found in the following search path: '['C:\\Windows\\system32', 'C:\\Windows', 'C:\\Windows\\System32\\Wbem', 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\', 'C:\\Program Files\\Amazon\\cfn-bootstrap\\', 'C:\\salt', 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python36-32\\Scripts\\', 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python36-32\\', 'C:\\Users\\Administrator\\AppData\\Local\\Microsoft\\WindowsApps', '', 'C:\\salt\\bin\\lib\\site-packages\\pywin32_system32']'
[TRACE   ] 'smbios' could not be found in the following search path: '['C:\\Windows\\system32', 'C:\\Windows', 'C:\\Windows\\System32\\Wbem', 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\', 'C:\\Program Files\\Amazon\\cfn-bootstrap\\', 'C:\\salt', 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python36-32\\Scripts\\', 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python36-32\\', 'C:\\Users\\Administrator\\AppData\\Local\\Microsoft\\WindowsApps', '', 'C:\\salt\\bin\\lib\\site-packages\\pywin32_system32']'
[TRACE   ] 'esxcli' could not be found in the following search path: '['C:\\Windows\\system32', 'C:\\Windows', 'C:\\Windows\\System32\\Wbem', 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\', 'C:\\Program Files\\Amazon\\cfn-bootstrap\\', 'C:\\salt', 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python36-32\\Scripts\\', 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python36-32\\', 'C:\\Users\\Administrator\\AppData\\Local\\Microsoft\\WindowsApps', '', 'C:\\salt\\bin\\lib\\site-packages\\pywin32_system32']'
[TRACE   ] Depends decorator instantiated with dep list of (False,)
[TRACE   ] Depends decorator instantiated with dep list of (False,)
LOTS OF DEPENDS DECORATOR I STANTIATED WITH DEP LIST OF (FALSE,)--------
LOTS OF DEPENDS DECORATOR I STANTIATED WITH DEP LIST OF (FALSE,)--------
LOTS OF DEPENDS DECORATOR I STANTIATED WITH DEP LIST OF (FALSE,)--------
[TRACE   ] Error loading grains.napalm: "napalm"" (C:\salt\bin\lib\site-packages\salt\grains\__pycache__\napalm.cpython-35.pyc) cannot be loaded: NAPALM is not installed or not running in a (proxy) minion
[TRACE   ] Loading core.append_domain grain
[TRACE   ] Loading core.default_gateway grain
[TRACE   ] 'ip' could not be found in the following search path: '['C:\\Windows\\system32', 'C:\\Windows', 'C:\\Windows\\System32\\Wbem', 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\', 'C:\\Program Files\\Amazon\\cfn-bootstrap\\', 'C:\\salt', 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python36-32\\Scripts\\', 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python36-32\\', 'C:\\Users\\Administrator\\AppData\\Local\\Microsoft\\WindowsApps', '', 'C:\\salt\\bin\\lib\\site-packages\\pywin32_system32']'
[TRACE   ] Loading core.dns grain
[TRACE   ] Loading core.get_machine_id grain
[TRACE   ] Loading core.get_master grain
[TRACE   ] Loading core.get_server_id grain
[TRACE   ] Loading core.hostname grain
[TRACE   ] Loading core.hwaddr_interfaces grain
[TRACE   ] Loading core.id_ grain
[TRACE   ] Loading core.ip4_interfaces grain
[TRACE   ] Loading core.ip6_interfaces grain
[TRACE   ] Loading core.ip_fqdn grain
[TRACE   ] Loading core.ip_interfaces grain
[TRACE   ] Loading core.linux_distribution grain
[TRACE   ] Loading core.locale_info grain
[TRACE   ] Loading core.os_data grain
[DEBUG   ] Motherboard info not available on this system
[TRACE   ] Loading core.path grain
[TRACE   ] Loading core.pythonexecutable grain
[TRACE   ] Loading core.pythonpath grain
[TRACE   ] Loading core.pythonversion grain
[TRACE   ] Loading core.saltpath grain
[TRACE   ] Loading core.saltversion grain
[TRACE   ] Loading core.saltversioninfo grain
[TRACE   ] Loading core.zmqversion grain
[TRACE   ] Loading disks.disks grain
[TRACE   ] Loading extra.config grain
[TRACE   ] Loading extra.shell grain
[TRACE   ] Loading mdadm.mdadm grain
[TRACE   ] Loading minion_process.grains grain
[TRACE   ] Loading opts.opts grain
[TRACE   ] Loading zfs.zfs grain
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded s3.get
[DEBUG   ] LazyLoaded config.option
[DEBUG   ] LazyLoaded s3.query
[DEBUG   ] Starting new HTTP connection (1): 169.254.169.254
[DEBUG   ] http://169.254.169.254:80 "GET /latest/dynamic/instance-identity/document HTTP/1.1" 200 486
[DEBUG   ] Starting new HTTP connection (1): 169.254.169.254
[DEBUG   ] http://169.254.169.254:80 "GET /latest/meta-data/iam/security-credentials/ HTTP/1.1" 200 10
[DEBUG   ] Starting new HTTP connection (1): 169.254.169.254
[DEBUG   ] http://169.254.169.254:80 "GET /latest/meta-data/iam/security-credentials/b'salts3test' HTTP/1.1" 404 345
[DEBUG   ] S3 Request: http://oztest.s3.amazonaws.com/index.html?
[DEBUG   ] S3 Headers::
[DEBUG   ]     Authorization: XXXX-XXXX-SHA256 Credential=use-instance-role-credentials/20180502/ca-central-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=XXXXXXXXXXXXXXXXXX361b8737876ae78013d080XXXXXXXXXXXXXXXXXX
[DEBUG   ] Starting new HTTP connection (1): oztest.s3.amazonaws.com
[DEBUG   ] http://oztest.s3.amazonaws.com:80 "GET /index.html HTTP/1.1" 403 None
[DEBUG   ]     Response content: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided does not exist in our records.</Message><AWSAccessKeyId>use-instance-role-credentials</AWSAccessKeyId><RequestId>EAAFE738E873FC9B</RequestId><HostId>XXXXXXXXXXXXXXXXXXXXXXXhF8N3EN+vz3nQswX+OXCdngwXXXXXXXXXXXXXX/W/Ranc=</HostId></Error>'
[DEBUG   ] S3 Response Status Code: 403
Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 212, in call
    ret['return'] = func(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\modules\s3.py", line 204, in get
    https_enable=https_enable)
  File "C:\salt\bin\lib\site-packages\salt\utils\s3.py", line 237, in query
    'Failed to get file. {0}: {1}'.format(err_code, err_msg))
salt.exceptions.CommandExecutionError: Failed to get file. InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.
Error running 's3.get': Failed to get file. InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.

```
