### ISSUE TITLE
salt fails to start on freebsd 11

### ISSUE THREAD

**Issue by dawidpogorzelski** [saltstack/salt#47301]
### Description of Issue/Question
Salt minion/master fails to start on freebsd 11.1-2 due to bad msgpack reference

### Steps to Reproduce Issue
```
cd /usr/ports/sysutils/py-salt/ && make install clean
service salt_minion start
Starting salt_minion.
Traceback (most recent call last):
  File "/usr/local/bin/salt-minion", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'msgpack-python!=0.5.5,>0.3' distribution was not found and is required by salt
/usr/local/etc/rc.d/salt_minion: WARNING: failed to start salt_minion
```
This workaround works: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=227754

### Versions Report
```
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: 1.11.2
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.5.0
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: 1.5.2
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Jan  2 2018, 01:25:01)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: 0.6.5
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.3
 
System Versions:
           dist:   
         locale: UTF-8
        machine: amd64
        release: 11.1-RELEASE-p8
         system: FreeBSD
        version: Not Installed
```

**Comment by Ch3LL** [comment]
ping @cedwards any ideas here?

**Comment by cedwards** [comment]
Yes. We submitted a patch for that to the FreeBSD ports tree earlier today. It should be available.

A change to the port name for py-msgpack came along with my 2018.3.0 salt update and caused this.

**Comment by dawidpogorzelski** [comment]
yep, 2018.3.0_1 fixes it, thx :)
