### ISSUE TITLE
lxc clone not working

### ISSUE THREAD

**Issue by masau** [saltstack/salt#47322]
I've been working on setting up some lxc containers in saltstack, but when attempting to clone an lxc container, I get the following error:
```
salt-call lxc.clone test_clone orig=base
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'unicode' object has no attribute 'version'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 400, in salt_call
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 212, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/lxc.py", line 2080, in clone
    if version() >= _LooseVersion('2.0'):
  File "/usr/lib/python2.7/distutils/version.py", line 295, in __cmp__
    return cmp(self.version, other.version)
AttributeError: 'unicode' object has no attribute 'version'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 400, in salt_call
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 212, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/lxc.py", line 2080, in clone
    if version() >= _LooseVersion('2.0'):
  File "/usr/lib/python2.7/distutils/version.py", line 295, in __cmp__
    return cmp(self.version, other.version)
AttributeError: 'unicode' object has no attribute 'version'
```

After some investigation, it appears the fix is changing line 2080 in the lxc module:
https://github.com/saltstack/salt/blob/e8d837357a07d61509550ff6864440f8eaff9913/salt/modules/lxc.py#L2080
to this (similar to line 870):
`if _LooseVersion(version()) >= _LooseVersion('2.0'):`

**Comment by garethgreenaway** [comment]
@masau Thanks for the report.  Would you be able to provide a PR with those changes?

**Comment by ejparker12** [comment]
PR submitted. Sorry for the delay - I submitted the issue under a username I largely stopped using a long time ago and I didn't get an email about your comment. Also sorry for the multiple references - was trying to get gpg working and didn't realize the references would stick around here even with the commits being redone.

**Comment by rallytime** [comment]
All good. :)

I'll go ahead and close this now since the fix has been merged. Thanks!
