### ISSUE TITLE
Saltstack 2018.3.0 fails to start on FreeBSD with py-msgpack

### ISSUE THREAD

**Issue by sylgeist** [saltstack/salt#47345]
### Description of Issue/Question
FreeBSD ports renamed Python 'msgpack' from:
msgpack-python -> pyXX-msgpack

This breaks salt-2018.3.0 with the following error:

`Starting salt_master.
Traceback (most recent call last):
  File "/usr/local/bin/salt-master", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'msgpack-python!=0.5.5,>0.3' distribution was not found and is required by salt
`

### Setup
FreeBSD 11.1 (in my case with Python-3.6)
Salt 2018.3.0 (current ports tree version)

### Steps to Reproduce Issue
Install py36-salt-2018.3.0 from packages/ports
Install py36-msgpack-0.5.6 from packages/ports (automatic as a dependency of Salt)

### Versions Report
The versions report doesn't run due to the error above

**Comment by sylgeist** [comment]
Tested fix by changing requirements.txt to:
msgpack>0.3,!=0.5.5

instead of:
msgpack-python>0.3,!=0.5.5

and it starts successfully.

**Comment by cedwards** [comment]
We addressed the update in `requirements.txt` in version 2018.3.0_1 of the port.

**Comment by gtmanfred** [comment]
Awesome, thanks!
