### ISSUE TITLE
Bug with two resource pools with same name in different clusters in salt-cloud

### ISSUE THREAD

**Issue by FixGN** [saltstack/salt#47350]
### Description of Issue/Question
I have 2 clusers (HA01 and HA02) in one datacenter. I have a resource pool with name "ID" in both datacenters. Additional, I have RO permission to ther resource pools in datacenter . When salt-cloud try create VM, it's select only HA02/ID resource pool, regardless on variable "cluster" value.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
/etc/salt/cloud.providers
```
cloud-example-com:
  driver: vmware
  user: 'user@example.com'
  password: 'verystrongpassword'
  url: 'cloud.example.com'
```
/etc/salt/cloud.profiles
```
COS74-DEV-1.2.24:
  provider: cloud-example-com
  clonefrom: TemplateCentOS74

  datacenter: EXAMPLE
  resourcepool: ID

  num_cpus: 1
  memory: 2GB
  
  devices:
    disk:
      Hard disk 1:
        size: 24
    network:
      Network adapter 1:
        name: example-network
        gateway: [172.28.16.1]
        subnet_mask: 255.255.255.0
        switch_type: standard

  domain: example.com
  dns_servers:
    - 172.28.16.2
    - 172.28.16.3
    - 8.8.8.8

  deploy: False
```
/etc/salt/cloud.maps.d/dev.map 
```
COS74-DEV-1.2.24:
  - test.example.com:
      cluster: HA01
      folder: ID/Test
      devices:
        network:
          Network adapter 1:
            ip: 172.28.16.200
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
salt-cloud -P -m /etc/salt/cloud.maps.d/dev.map -l debug
```
[DEBUG   ] Reading configuration from /etc/salt/cloud
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles
[DEBUG   ] Configuration file path: /etc/salt/cloud
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] salt-cloud starting
[DEBUG   ] Marking 'base64_encode' as a jinja filter
[DEBUG   ] Marking 'base64_decode' as a jinja filter
[DEBUG   ] Marking 'md5' as a jinja filter
[DEBUG   ] Marking 'sha256' as a jinja filter
[DEBUG   ] Marking 'sha512' as a jinja filter
[DEBUG   ] Marking 'hmac' as a jinja filter
[DEBUG   ] Marking 'random_hash' as a jinja filter
[DEBUG   ] Marking 'rand_str' as a jinja filter
[DEBUG   ] Marking 'file_hashsum' as a jinja filter
[DEBUG   ] Marking 'http_query' as a jinja filter
[DEBUG   ] Marking 'yaml_dquote' as a jinja filter
[DEBUG   ] Marking 'yaml_squote' as a jinja filter
[DEBUG   ] Marking 'yaml_encode' as a jinja filter
[DEBUG   ] Marking 'raise' as a jinja global
[DEBUG   ] Marking 'match' as a jinja test
[DEBUG   ] Marking 'equalto' as a jinja test
[DEBUG   ] Marking 'skip' as a jinja filter
[DEBUG   ] Marking 'sequence' as a jinja filter
[DEBUG   ] Marking 'to_bool' as a jinja filter
[DEBUG   ] Marking 'quote' as a jinja filter
[DEBUG   ] Marking 'regex_escape' as a jinja filter
[DEBUG   ] Marking 'regex_search' as a jinja filter
[DEBUG   ] Marking 'regex_match' as a jinja filter
[DEBUG   ] Marking 'regex_replace' as a jinja filter
[DEBUG   ] Marking 'uuid' as a jinja filter
[DEBUG   ] Marking 'unique' as a jinja filter
[DEBUG   ] Marking 'min' as a jinja filter
[DEBUG   ] Marking 'max' as a jinja filter
[DEBUG   ] Marking 'avg' as a jinja filter
[DEBUG   ] Marking 'union' as a jinja filter
[DEBUG   ] Marking 'intersect' as a jinja filter
[DEBUG   ] Marking 'difference' as a jinja filter
[DEBUG   ] Marking 'symmetric_difference' as a jinja filter
[DEBUG   ] Could not LazyLoad parallels.avail_sizes: 'parallels' __virtual__ returned False
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Reading configuration from /etc/salt/cloud
[DEBUG   ] Guessing ID. The id can be explicitly set in /etc/salt/minion
[DEBUG   ] Found minion id from generate_minion_id(): master.salt
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from /etc/salt/cloud
[DEBUG   ] pyVmomi not loaded: Incompatible versions of Python. See Issue #29537.
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] compile template: /etc/salt/cloud.maps.d/dev.map
[DEBUG   ] Jinja search path: [u'/var/cache/salt/cloud/files/base']
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[DEBUG   ] Updating roots fileserver cache
[PROFILE ] Time (in seconds) to render '/etc/salt/cloud.maps.d/dev.map' using 'jinja' renderer: 0.0300891399384
[DEBUG   ] Rendered data from file: /etc/salt/cloud.maps.d/dev.map:
COS74-DEV-1.2.24:
  - test.example.com:
      cluster: HA01
      folder: ID/Test
      devices:
        network:
          Network adapter 1:
            ip: 172.28.16.200

[DEBUG   ] Results of YAML rendering: 
OrderedDict([(u'COS74-HA01-243-1.2.24', [OrderedDict([(u'test.example.com', OrderedDict([(u'cluster', u'HA01'), (u'folder', u'ID/Test'), (u'devices', OrderedDict([(u'network', OrderedDict([(u'Network adapter 1', OrderedDict([(u'ip', u'')]))]))]))]))])])])
[PROFILE ] Time (in seconds) to render '/etc/salt/cloud.maps.d/dev.map' using 'yaml' renderer: 0.00667095184326
[INFO    ] Applying map from '/etc/salt/cloud.maps.d/dev.map'.
[DEBUG   ] Could not LazyLoad vmware.optimize_providers: 'vmware.optimize_providers' is not available.
[DEBUG   ] The 'vmware' cloud driver is unable to be optimized.
[DEBUG   ] Could not LazyLoad parallels.avail_sizes: 'parallels' __virtual__ returned False
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
The following virtual machines are set to be created:
  test.example.com

Proceed? [N/y] y
... proceeding
[INFO    ] Calculating dependencies for test.example.com
[DEBUG   ] Got execution order 0 for test.example.com
[DEBUG   ] No make_master found in map
[INFO    ] Since parallel deployment is in use, ssh console output is disabled. All ssh output will be logged though
[INFO    ] Cloud pool size: 1
[DEBUG   ] Could not LazyLoad parallels.avail_sizes: 'parallels' __virtual__ returned False
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] LazyLoaded cloud.fire_event
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] No datastore/datastore cluster specified
[DEBUG   ] Using datastore used by the template TemplateCentOS74
[DEBUG   ] Setting cpu to: 1
[DEBUG   ] Setting memory to: 2048 MB
[DEBUG   ] clone_spec set to:
(vim.vm.CloneSpec) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   location = (vim.vm.RelocateSpec) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      service = <unset>,
      folder = <unset>,
      datastore = <unset>,
      diskMoveType = <unset>,
      pool = 'vim.ResourcePool:resgroup-1021',
      host = <unset>,
      disk = (vim.vm.RelocateSpec.DiskLocator) [],
      transform = <unset>,
      deviceChange = (vim.vm.device.VirtualDeviceSpec) [],
      profile = (vim.vm.ProfileSpec) []
   },
   template = false,
   config = (vim.vm.ConfigSpec) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      changeVersion = <unset>,
      name = <unset>,
      version = <unset>,
      uuid = <unset>,
      instanceUuid = <unset>,
      npivNodeWorldWideName = (long) [],
      npivPortWorldWideName = (long) [],
      npivWorldWideNameType = <unset>,
      npivDesiredNodeWwns = <unset>,
      npivDesiredPortWwns = <unset>,
      npivTemporaryDisabled = <unset>,
      npivOnNonRdmDisks = <unset>,
      npivWorldWideNameOp = <unset>,
      locationId = <unset>,
      guestId = <unset>,
      alternateGuestName = <unset>,
      annotation = <unset>,
      files = <unset>,
      tools = <unset>,
      flags = <unset>,
      consolePreferences = <unset>,
      powerOpInfo = <unset>,
      numCPUs = 1,
      numCoresPerSocket = <unset>,
      memoryMB = 2048,
      memoryHotAddEnabled = <unset>,
      cpuHotAddEnabled = <unset>,
      cpuHotRemoveEnabled = <unset>,
      virtualICH7MPresent = <unset>,
      virtualSMCPresent = <unset>,
      deviceChange = (vim.vm.device.VirtualDeviceSpec) [
         (vim.vm.device.VirtualDeviceSpec) {
            dynamicType = <unset>,
            dynamicProperty = (vmodl.DynamicProperty) [],
            operation = 'edit',
            fileOperation = <unset>,
            device = (vim.vm.device.VirtualVmxnet3) {
               dynamicType = <unset>,
               dynamicProperty = (vmodl.DynamicProperty) [],
               key = 4000,
               deviceInfo = (vim.Description) {
                  dynamicType = <unset>,
                  dynamicProperty = (vmodl.DynamicProperty) [],
                  label = 'Network adapter 1',
                  summary = u'example-network'
               },
               backing = (vim.vm.device.VirtualEthernetCard.NetworkBackingInfo) {
                  dynamicType = <unset>,
                  dynamicProperty = (vmodl.DynamicProperty) [],
                  deviceName = u'example-network',
                  useAutoDetect = <unset>,
                  network = 'vim.dvs.DistributedVirtualPortgroup:dvportgroup-75',
                  inPassthroughMode = <unset>
               },
               connectable = (vim.vm.device.VirtualDevice.ConnectInfo) {
                  dynamicType = <unset>,
                  dynamicProperty = (vmodl.DynamicProperty) [],
                  startConnected = true,
                  allowGuestControl = true,
                  connected = false,
                  status = 'untried'
               },
               slotInfo = <unset>,
               controllerKey = 100,
               unitNumber = 7,
               addressType = 'assigned',
               macAddress = '00:50:56:8f:a6:9d',
               wakeOnLanEnabled = true,
               resourceAllocation = (vim.vm.device.VirtualEthernetCard.ResourceAllocation) {
                  dynamicType = <unset>,
                  dynamicProperty = (vmodl.DynamicProperty) [],
                  reservation = 0L,
                  share = (vim.SharesInfo) {
                     dynamicType = <unset>,
                     dynamicProperty = (vmodl.DynamicProperty) [],
                     shares = 50,
                     level = 'normal'
                  },
                  limit = -1L
               },
               externalId = <unset>,
               uptCompatibilityEnabled = true
            },
            profile = (vim.vm.ProfileSpec) [],
            backing = <unset>
         }
      ],
      cpuAllocation = <unset>,
      memoryAllocation = <unset>,
      latencySensitivity = <unset>,
      cpuAffinity = <unset>,
      memoryAffinity = <unset>,
      networkShaper = <unset>,
      cpuFeatureMask = (vim.vm.ConfigSpec.CpuIdInfoSpec) [],
      extraConfig = (vim.option.OptionValue) [],
      swapPlacement = <unset>,
      bootOptions = <unset>,
      vAppConfig = <unset>,
      ftInfo = <unset>,
      repConfig = <unset>,
      vAppConfigRemoved = <unset>,
      vAssertsEnabled = <unset>,
      changeTrackingEnabled = <unset>,
      firmware = <unset>,
      maxMksConnections = <unset>,
      guestAutoLockEnabled = <unset>,
      managedBy = <unset>,
      memoryReservationLockedToMax = <unset>,
      nestedHVEnabled = <unset>,
      vPMCEnabled = <unset>,
      scheduledHardwareUpgradeInfo = <unset>,
      vmProfile = (vim.vm.ProfileSpec) [],
      messageBusTunnelEnabled = <unset>,
      crypto = <unset>,
      migrateEncryption = <unset>
   },
   customization = (vim.vm.customization.Specification) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      options = <unset>,
      identity = (vim.vm.customization.LinuxPrep) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         hostName = (vim.vm.customization.FixedName) {
            dynamicType = <unset>,
            dynamicProperty = (vmodl.DynamicProperty) [],
            name = u'test'
         },
         domain = u'example.com',
         timeZone = <unset>,
         hwClockUTC = <unset>
      },
      globalIPSettings = (vim.vm.customization.GlobalIPSettings) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         dnsSuffixList = (str) [],
         dnsServerList = (str) [
            u'172.28.16.2',
            u'172.28.16.3',
            u'8.8.8.8'
         ]
      },
      nicSettingMap = (vim.vm.customization.AdapterMapping) [
         (vim.vm.customization.AdapterMapping) {
            dynamicType = <unset>,
            dynamicProperty = (vmodl.DynamicProperty) [],
            macAddress = <unset>,
            adapter = (vim.vm.customization.IPSettings) {
               dynamicType = <unset>,
               dynamicProperty = (vmodl.DynamicProperty) [],
               ip = (vim.vm.customization.FixedIp) {
                  dynamicType = <unset>,
                  dynamicProperty = (vmodl.DynamicProperty) [],
                  ipAddress = u'172.28.16.200'
               },
               subnetMask = u'255.255.255.0',
               gateway = (str) [
                  u'172.28.16.1'
               ],
               ipV6Spec = <unset>,
               dnsServerList = (str) [],
               dnsDomain = <unset>,
               primaryWINS = <unset>,
               secondaryWINS = <unset>,
               netBIOS = <unset>
            }
         }
      ],
      encryptionKey = (byte) []
   },
   powerOn = true,
   snapshot = <unset>,
   memory = <unset>
}
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
[INFO    ] Creating test.example.com from template(TemplateCentOS74)
[INFO    ] [ test.example.com ] Waiting for clone task to finish [0 s]
[INFO    ] [ test.example.com ] Waiting for clone task to finish [5 s]
[INFO    ] [ test.example.com ] Waiting for clone task to finish [10 s]
[ERROR   ] (vim.fault.CannotAccessVmConfig) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'Unable to access the virtual machine configuration: Unable to access file [example-datastore] TemplateCentOS74/TemplateCentOS74.vmtx',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   reason = (vim.fault.CannotAccessFile) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      msg = 'Unable to access file [example-datastore] TemplateCentOS74/TemplateCentOS74.vmtx',
      faultCause = <unset>,
      faultMessage = (vmodl.LocalizableMessage) [],
      file = '[example-datastore] TemplateCentOS74/TemplateCentOS74.vmtx'
   }
}
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/vmware.py", line 3151, in wait_for_task
    raise task_info.error
vim.fault.CannotAccessVmConfig: (vim.fault.CannotAccessVmConfig) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'Unable to access the virtual machine configuration: Unable to access file [example-datastore] TemplateCentOS74/TemplateCentOS74.vmtx',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   reason = (vim.fault.CannotAccessFile) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      msg = 'Unable to access file [example-datastore] TemplateCentOS74/TemplateCentOS74.vmtx',
      faultCause = <unset>,
      faultMessage = (vmodl.LocalizableMessage) [],
      file = '[example-datastore] TemplateCentOS74/TemplateCentOS74.vmtx'
   }
}
[ERROR   ] Error creating test.dev.itass.local: Unable to access the virtual machine configuration: Unable to access file [example-datastore] TemplateCentOS74/TemplateCentOS74.vmtx
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/vmware.py", line 2767, in create
    salt.utils.vmware.wait_for_task(task, vm_name, 'clone', 5, 'info')
  File "/usr/lib/python2.7/site-packages/salt/utils/vmware.py", line 3162, in wait_for_task
    raise salt.exceptions.VMwareApiError(exc.msg)
VMwareApiError: Unable to access the virtual machine configuration: Unable to access file [example-datastore] TemplateCentOS74/TemplateCentOS74.vmtx
[DEBUG   ] LazyLoaded nested.output
test.example.com:
    ----------
    Error:
        Error creating test.example.com: Unable to access the virtual machine configuration: Unable to access file [example-datastore] TemplateCentOS74/TemplateCentOS74.vmtx

```
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
[vagrant@master salt]$ salt --versions-report
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.11.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

**Comment by gtmanfred** [comment]
Unfortunately I only have one cluster to test on, so I will be unable to attempt to replicate this.

@nmadhok can you help here?

Thanks,
Daniel

**Comment by zbukhari-apex** [comment]
I think I found the issue, it's in the documentation in a weird way and I believe your comment helped me get to it. Basically unless you set up different resource pools the generic one is "Resources". I'm not 100% sure why you're running into it but basically on vm creation if you specify cluster and resourcepool, it will use resourcepool. That's not definitive in my environment. So I simply commented out resourcepool and only left in cluster. It worked.

https://docs.saltproject.io/en/latest/topics/cloud/vmware.html

More specifically as I'm using a template this applied to me:

`For a clone operation from a template to a virtual machine, specifying either this or resourcepool is required. If both are specified, the resourcepool value will be used.`

I had to look at the vcenters own logs, it helped because it showed it was trying to deploy on a server which does not have access to the datastore. Meaning that although we can see it, the destination host can not see the guest template/vm. This led me to investigate why and that's when I found out for me it was resourcepool. It seems in your case you only have one cluster so perhaps try defining your destination host in profiles/extends. Let me know if it works please!

My working config if it helps:

```
vcenter2-focal:
  provider: vcenter2
  clonefrom: focal-server-cloudimg-amd64
  datacenter: Smallville
  cluster: DR_Smallville
  template: False
  # We will deploy Salt manually
  deploy: False

# Fluffy stuff omitted ...

vcenter2-focal-generic:
  extends: vcenter2-focal
  cpu_hot_add: True
  mem_hot_add: True
  power_on: False

  ## Optional arguments
  num_cpus: 4
  memory: 4GB

  file_map:
    /tmp/testA.txt: /tmp/testA.txt
    /tmp/scriptA.bash: /tmp/scriptA.bash

  # You can't specify both of these as it will use resourcepool in that situation and that same resourcepool is everywhere.
  # resourcepool: Resources
  cluster: DR_Smallville
```
