### ISSUE TITLE
[Feature Request] Easier Debugging of states + modules

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#47357]
## Situation
Recently, there was an issue with an extension module we wrote for salt.

```
{% if 'modarch' in salt['tbz.process_systems'](pillar.systems)|map(attribute='project') %}
```

```python
salt:/srv # salt-ssh minion state.sls real_sls
[ERROR   ] Rendering exception occurred
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 169, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 390, in render_jinja_tmpl
    buf=tmplstr)
SaltRenderError: Jinja variable 'str object' has no attribute 'project'
[CRITICAL] Rendering SLS 'base:root' failed: Jinja variable 'str object' has no attribute 'project'
minion:
    - Rendering SLS 'base:root' failed: Jinja variable 'str object' has no attribute 'project'
```

We then extracted the relevant part into a tmp/xyz.sls as a simple {{ jinja }} variable.

```yaml
abc:
  test.nop:
    - name: {{ salt['tbz.process_systems'](pillar.systems) }}
```

```python
salt:/srv # salt-ssh minion state.sls tmp.xyz
[CRITICAL] Rendering SLS 'base:tmp.xyz' failed: while parsing a flow mapping
  in "<unicode string>", line 4, column 13:
        - name: {'retcode': 0, '_error': 'Failed ... 
                ^
expected ',' or '}', but got ':'
  in "<unicode string>", line 4, column 113:
     ... 'tbz' __virtual__ returned False: invalid syntax (tbz.py, line 6 ... 
                                         ^
minion:
    - Rendering SLS 'base:tmp.xyz' failed: while parsing a flow mapping
        in "<unicode string>", line 4, column 13:
              - name: {'retcode': 0, '_error': 'Failed ... 
                      ^
      expected ',' or '}', but got ':'
        in "<unicode string>", line 4, column 113:
           ... 'tbz' __virtual__ returned False: invalid syntax (tbz.py, line 6 ... 
                                               ^
```

So, we can chase down the real error by doing:

```python
salt:/srv # python salt/_modules/tbz.py
  File "salt/_modules/tbz.py", line 62
    return process_systems(systems)o
                                   ^
SyntaxError: invalid syntax
```
Using "--log-level debug/all" didn't help much because of missing output and because it's just too much.

It was very time consuming since causing tracebacks aren't visible at a first glance. Moreover, developing the workflow above, wasn't obvious at all.

## Question

Is there a way to stop execution completely and show the **first** traceback/error?

Like in regular Python.

**Comment by gtmanfred** [comment]
That is difficult, because the error happened in the jinja context, so it would show you the jinja error, instead of the python error.

@saltstack/team-core anyone have any comments on this?

Thanks,
Daniel

**Comment by srkunze** [comment]
What about #47352?

Is it possible to make __slots__ failing early?

**Comment by gtmanfred** [comment]
I am actually not sure what happens when something in slots stack traces.
