### ISSUE TITLE
salt-api and salt-ssh error in 2018.3.0 py3

### ISSUE THREAD

**Issue by xiaopanggege** [saltstack/salt#47383]
### Description of Issue/Question
when client system is CentOS-7.4 and python version is py2, not install py3 in envionment variables  
my master system CentOS-7.4 install salt-ssh and salt-api is version 2018.3.0 py3  
**execute salt-ssh salt-api not available**  
### Setup
```
[root@localhost ~]# cat /etc/salt/roster   
web1:
  host: 192.168.100.172
  user: root
  passwd: 123456
  port: 22
```
**salt-ssh**
```
[root@localhost ~]# salt-ssh \* test.pings
web1:
    ----------
    retcode:
        10
    stderr:
        ERROR: Unable to locate appropriate python command
    stdout:
        ERROR: salt requires python 2.6 or newer on target hosts, must have same major version as origin host
```

**salt-api**
```
[root@localhost ~]# curl -sS 192.168.68.50:8080/run -H 'Accept: application/x-yaml' -d client='ssh' -d tgt='*' -d fun='test.ping'               
return:
- web1:
    _stamp: '2018-04-28T08:22:20.875345'
    id: web1
    jid: '20180428162210081977'
    retcode: 10
    stderr: 'ERROR: Unable to locate appropriate python command

'
    stdout: 'ERROR: salt requires python 2.6 or newer on target hosts, must have same
      major version as origin host'
```
**when tgt='web1'**  
**salt-ssh** 
```
[root@localhost ~]# salt-ssh 'web1' test.ping
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: normcase() argument must be str or bytes, not 'NoneType'
Traceback (most recent call last):
  File "/usr/bin/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/usr/lib/python3.4/site-packages/salt/scripts.py", line 425, in salt_ssh
    client.run()
  File "/usr/lib/python3.4/site-packages/salt/cli/ssh.py", line 23, in run
    ssh = salt.client.ssh.SSH(self.config)
  File "/usr/lib/python3.4/site-packages/salt/client/ssh/__init__.py", line 235, in __init__
    self.tgt_type)
  File "/usr/lib/python3.4/site-packages/salt/roster/__init__.py", line 105, in targets
    targets.update(self.rosters[f_str](tgt, tgt_type))
  File "/usr/lib/python3.4/site-packages/salt/roster/flat.py", line 50, in targets
    return rmatcher.targets()
  File "/usr/lib/python3.4/site-packages/salt/roster/flat.py", line 68, in targets
    return getattr(self, 'ret_{0}_minions'.format(self.tgt_type))()
  File "/usr/lib/python3.4/site-packages/salt/roster/flat.py", line 78, in ret_glob_minions
    if fnmatch.fnmatch(minion, self.tgt):
  File "/usr/lib64/python3.4/fnmatch.py", line 35, in fnmatch
    pat = os.path.normcase(pat)
  File "/usr/lib64/python3.4/posixpath.py", line 53, in normcase
    "not '{}'".format(s.__class__.__name__))
TypeError: normcase() argument must be str or bytes, not 'NoneType'
Traceback (most recent call last):
  File "/usr/bin/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/usr/lib/python3.4/site-packages/salt/scripts.py", line 425, in salt_ssh
    client.run()
  File "/usr/lib/python3.4/site-packages/salt/cli/ssh.py", line 23, in run
    ssh = salt.client.ssh.SSH(self.config)
  File "/usr/lib/python3.4/site-packages/salt/client/ssh/__init__.py", line 235, in __init__
    self.tgt_type)
  File "/usr/lib/python3.4/site-packages/salt/roster/__init__.py", line 105, in targets
    targets.update(self.rosters[f_str](tgt, tgt_type))
  File "/usr/lib/python3.4/site-packages/salt/roster/flat.py", line 50, in targets
    return rmatcher.targets()
  File "/usr/lib/python3.4/site-packages/salt/roster/flat.py", line 68, in targets
    return getattr(self, 'ret_{0}_minions'.format(self.tgt_type))()
  File "/usr/lib/python3.4/site-packages/salt/roster/flat.py", line 78, in ret_glob_minions
    if fnmatch.fnmatch(minion, self.tgt):
  File "/usr/lib64/python3.4/fnmatch.py", line 35, in fnmatch
    pat = os.path.normcase(pat)
  File "/usr/lib64/python3.4/posixpath.py", line 53, in normcase
    "not '{}'".format(s.__class__.__name__))
TypeError: normcase() argument must be str or bytes, not 'NoneType'
```
**salt-api**
```
[root@localhost ~]# curl -sS 192.168.68.50:8080/run -H 'Accept: application/x-yaml' -d client='ssh' -d tgt='web1' -d fun='test.ping'
return: An unexpected error occurred
status: 500
```
/var/log/salt/api   is no error display  

if my master remove salt-ssh py3 and install salt-ssh in py2 2018.3.0
```
[root@localhost ~]# pip2 install salt-ssh==2018.3.0
Collecting salt-ssh==2018.3.0
  Using cached https://files.pythonhosted.org/packages/45/fd/ac5c4fa12f5a71f3169b48776fa04dbf05cdd1b8857a5ba8d45b9312f738/salt-ssh-2018.3.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): Jinja2 in /usr/lib/python2.7/site-packages (from salt-ssh==2018.3.0)
Requirement already satisfied (use --upgrade to upgrade): msgpack-python!=0.5.5,>0.3 in /usr/lib64/python2.7/site-packages (from salt-ssh==2018.3.0)
Requirement already satisfied (use --upgrade to upgrade): PyYAML in /usr/lib64/python2.7/site-packages (from salt-ssh==2018.3.0)
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in /usr/lib64/python2.7/site-packages (from salt-ssh==2018.3.0)
Requirement already satisfied (use --upgrade to upgrade): requests>=1.0.0 in /usr/lib/python2.7/site-packages (from salt-ssh==2018.3.0)
Requirement already satisfied (use --upgrade to upgrade): tornado<5.0,>=4.2.1 in /usr/lib64/python2.7/site-packages (from salt-ssh==2018.3.0)
Requirement already satisfied (use --upgrade to upgrade): futures>=2.0 in /usr/lib/python2.7/site-packages (from salt-ssh==2018.3.0)
Installing collected packages: salt-ssh
  Running setup.py install for salt-ssh ... done
Successfully installed salt-ssh-2018.3.0
```
now execute  **salt-ssh**  
```
[root@localhost ~]# salt-ssh \* test.ping               
web1:
    True
```
execute  **salt-ssh tgt='web1'**  
```
[root@localhost ~]# salt-ssh '192.168.100.172' test.ping
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/usr/bin/salt-ssh", line 9, in <module>
    load_entry_point('salt-ssh==2018.3.0', 'console_scripts', 'salt-ssh')()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 425, in salt_ssh
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/ssh.py", line 23, in run
    ssh = salt.client.ssh.SSH(self.config)
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 235, in __init__
    self.tgt_type)
  File "/usr/lib/python2.7/site-packages/salt/roster/__init__.py", line 105, in targets
    targets.update(self.rosters[f_str](tgt, tgt_type))
  File "/usr/lib/python2.7/site-packages/salt/roster/flat.py", line 50, in targets
    return rmatcher.targets()
  File "/usr/lib/python2.7/site-packages/salt/roster/flat.py", line 68, in targets
    return getattr(self, 'ret_{0}_minions'.format(self.tgt_type))()
  File "/usr/lib/python2.7/site-packages/salt/roster/flat.py", line 78, in ret_glob_minions
    if fnmatch.fnmatch(minion, self.tgt):
  File "/usr/lib64/python2.7/fnmatch.py", line 43, in fnmatch
    return fnmatchcase(name, pat)
  File "/usr/lib64/python2.7/fnmatch.py", line 75, in fnmatchcase
    res = translate(pat)
  File "/usr/lib64/python2.7/fnmatch.py", line 87, in translate
    i, n = 0, len(pat)
TypeError: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/usr/bin/salt-ssh", line 9, in <module>
    load_entry_point('salt-ssh==2018.3.0', 'console_scripts', 'salt-ssh')()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 425, in salt_ssh
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/ssh.py", line 23, in run
    ssh = salt.client.ssh.SSH(self.config)
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 235, in __init__
    self.tgt_type)
  File "/usr/lib/python2.7/site-packages/salt/roster/__init__.py", line 105, in targets
    targets.update(self.rosters[f_str](tgt, tgt_type))
  File "/usr/lib/python2.7/site-packages/salt/roster/flat.py", line 50, in targets
    return rmatcher.targets()
  File "/usr/lib/python2.7/site-packages/salt/roster/flat.py", line 68, in targets
    return getattr(self, 'ret_{0}_minions'.format(self.tgt_type))()
  File "/usr/lib/python2.7/site-packages/salt/roster/flat.py", line 78, in ret_glob_minions
    if fnmatch.fnmatch(minion, self.tgt):
  File "/usr/lib64/python2.7/fnmatch.py", line 43, in fnmatch
    return fnmatchcase(name, pat)
  File "/usr/lib64/python2.7/fnmatch.py", line 75, in fnmatchcase
    res = translate(pat)
  File "/usr/lib64/python2.7/fnmatch.py", line 87, in translate
    i, n = 0, len(pat)
TypeError: object of type 'NoneType' has no len()
```
salt-api not remove still py3 ,so when execute:
```
curl -sS 192.168.68.50:8080/run -H 'Accept: application/x-yaml' -d client='ssh' -d tgt='*' -d fun='test.ping'
```
result:  
```
[root@localhost ~]# curl -sS 192.168.68.50:8080/run -H 'Accept: application/x-yaml' -d client='ssh' -d tgt='*' -d fun='test.ping'               
return:
- web1:
    _stamp: '2018-04-28T09:06:02.170392'
    id: web1
    jid: '20180428170556322169'
    retcode: 10
    stderr: 'ERROR: Unable to locate appropriate python command

'
    stdout: 'ERROR: salt requires python 2.6 or newer on target hosts, must have same
      major version as origin host'
```
if **tgt='web1'**  
```
[root@localhost ~]# curl -sS 192.168.68.50:8080/run -H 'Accept: application/x-yaml' -d client='ssh' -d tgt='web1' -d fun='test.ping'   
return: An unexpected error occurred
status: 500
```
**if my remove salt-ssh and install salt-ssh versioin 2017.7.2 py2**  
```
[root@localhost ~]# pip2 install salt-ssh==2017.7.2
Collecting salt-ssh==2017.7.2
  Using cached https://files.pythonhosted.org/packages/6b/2d/7b2e87ba03a9069220815e3b8181944bed9637034a14d8b74f959ce78668/salt-ssh-2017.7.2.tar.gz
Requirement already satisfied (use --upgrade to upgrade): Jinja2 in /usr/lib/python2.7/site-packages (from salt-ssh==2017.7.2)
Requirement already satisfied (use --upgrade to upgrade): msgpack-python>0.3 in /usr/lib64/python2.7/site-packages (from salt-ssh==2017.7.2)
Requirement already satisfied (use --upgrade to upgrade): PyYAML in /usr/lib64/python2.7/site-packages (from salt-ssh==2017.7.2)
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in /usr/lib64/python2.7/site-packages (from salt-ssh==2017.7.2)
Requirement already satisfied (use --upgrade to upgrade): requests>=1.0.0 in /usr/lib/python2.7/site-packages (from salt-ssh==2017.7.2)
Requirement already satisfied (use --upgrade to upgrade): tornado>=4.2.1 in /usr/lib64/python2.7/site-packages (from salt-ssh==2017.7.2)
Requirement already satisfied (use --upgrade to upgrade): futures>=2.0 in /usr/lib/python2.7/site-packages (from salt-ssh==2017.7.2)
Installing collected packages: salt-ssh
  Running setup.py install for salt-ssh ... done
Successfully installed salt-ssh-2017.7.2
```
**now execute tgt='web1'**  
```
[root@localhost ~]# salt-ssh 'web1' test.ping
web1:
    True
```
**And if I'm salt-api install 2017.7.2 py2 ,execute tgt='web1'  also will be successful**

***
**Now if I want to use salt-api salt-ssh salt-master in 2018.3.0 py3 ,how solve this problem**

***

### Versions Report
2018.3.0

**Comment by gtmanfred** [comment]
Because you are using salt-ssh with the python 3 version, you also have to have python3 installed on the minion.  If you are not doing this as part of your provisioning process of the minion, then it would probably be best to stick to python 2 for salt-ssh, until https://github.com/saltstack/salt/pull/46684 is available in the next major version of salt.

**Comment by xiaopanggege** [comment]
@gtmanfred Thank you, looking forward to the next version to solve this problem.

**Comment by xiaopanggege** [comment]
@gtmanfred  #47150 Will this problem be solved in the new version?

**Comment by bouazizkhaled** [comment]
Hello i have the same issue, has the fix been released ?

**Comment by gtmanfred** [comment]
Which issue? 2018.3.2 is the latest release, so the ip_to_host/expand_host issue is fixed already.

the other "issue" is the expected behavior, and won't change until fluorine, when you can better specify which version of python to use on specific salt-ssh minions.

**Comment by bouazizkhaled** [comment]
I have python interpreter on minion which is not installed in the default PATH so is it possible to set it in the roster file ? 
Actually in master i have a python3 and in the minion the default one is python 2 so i whant to specify a diffrent one which is python3

  ERROR: Python version error. Recommendation(s) follow:
        - Install Python 2.6/2.7 Salt dependencies on the Salt SSH
          master to interact with Python 2.6/2.7 targets
        - Install Python 3 on the target machine(s)

**Comment by luobote** [comment]
Salt:2019.2.0  
windows cygwin  ssh
salt-ssh  "S1"  -r 'ls /'  --- is ok

salt-api   
curl 

{"return": [{"S1": {"_stamp": "2019-04-09T07:29:57.142639", "retcode": 10, "stdout": "ERROR: Python version error. Recommendation(s) follow:\nInstall Python 2.6 / Python 3 Salt dependencies on the Salt SSH master \nto interact with Python 2.6 / Python 3 targets", "jid": "20190409152956136352", "stderr": "ERROR: Unable to locate appropriate python command\n", "id": "S1"}}]}

**Comment by h0jeZvgoxFepBQ2C** [comment]
Still happening to me in 3000.3?
