### ISSUE TITLE
Vault - cannot generate token - 2018.3.0

### ISSUE THREAD

**Issue by 1ricardo** [saltstack/salt#47394]
### Description of Issue/Question
Hello,
After upgrade to version 2018.3.0, the Vault stooped working, according with error, there is problem with Token generation.

On version 2017.7.4 all working fine

### Setup

```sh
vault:
  url: https://vault.service.consul:8200
  auth:
    method: token
    token: {{ token here }}
  policies:
    - saltstack
```
```sh
peer_run:
  .*:
    - vault.generate_token
```
### Steps to Reproduce Issue
```sh
# salt-call vault.read_secret secret/saltstack/aws/cli/salt
[INFO    ] Publishing runner 'vault.generate_token' to tcp://10.200.12.78:4506
[ERROR   ] Failed to get token from master! Response is not a dict: Exception occurred in runner vault.generate_token: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 387, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/runners/vault.py", line 43, in generate_token
    'Token generation request for %s (impersonated by master: %s)'.
AttributeError: 'unicode' object has no attribute 'minion_id'

[ERROR   ] Failed to read secret! CommandExecutionError: Exception occurred in runner vault.generate_token: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 387, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/runners/vault.py", line 43, in generate_token
    'Token generation request for %s (impersonated by master: %s)'.
AttributeError: 'unicode' object has no attribute 'minion_id'

Error running 'vault.read_secret': Exception occurred in runner vault.generate_token: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 387, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/runners/vault.py", line 43, in generate_token
    'Token generation request for %s (impersonated by master: %s)'.
AttributeError: 'unicode' object has no attribute 'minion_id'
```

### Versions Report
```sh
# salt --versions-report
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: 2.7.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.21.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

**Comment by gtmanfred** [comment]
This is a duplicate, it is already fixed, and will be in 2018.3.1

**Comment by gtmanfred** [comment]
https://github.com/saltstack/salt/pull/46865

**Comment by 1ricardo** [comment]
Thank You for reply
