### ISSUE TITLE
slack engine running from salt-master tries to access /etc/salt/pki/minion/

### ISSUE THREAD

**Issue by viq** [saltstack/salt#47416]
### Description of Issue/Question
Slack engine, running from salt-master, tries to access `/etc/salt/pki/minion` and complains loudly when it cannot.

### Setup
`salt-master` running as a dedicated, non-root user, simple slack engine configured to run from salt-master.
https://raw.githubusercontent.com/saltstack/salt/bcdef641e8943f7a2aaeb88ad25cd3d23aac80f9/salt/engines/slack.py put in `/srv/salt/_engines/` and synced.

### Steps to Reproduce Issue
```
may 01 16:10:26 salt.master.example.com salt-master[22969]: Traceback (most recent call last):                                                                                                                               
may 01 16:10:26 salt.master.example.com salt-master[22969]:   File "/srv/deploy/salt/.venv/lib/python3.6/site-packages/salt/engines/__init__.py", line 128, in run
may 01 16:10:26 salt.master.example.com salt-master[22969]:     self.engine[self.fun](**kwargs)                                                                                                                              
may 01 16:10:26 salt.master.example.com salt-master[22969]:   File "/tmp/pip-build-1jhjfqa0/salt/salt/engines/slack.py", line 777, in start                                                                                  
may 01 16:10:26 salt.master.example.com salt-master[22969]: Exception: Traceback (most recent call last):                                                                                                                    
may 01 16:10:26 salt.master.example.com salt-master[22969]:   File "/tmp/pip-build-1jhjfqa0/salt/salt/engines/slack.py", line 775, in start
may 01 16:10:26 salt.master.example.com salt-master[22969]:   File "/tmp/pip-build-1jhjfqa0/salt/salt/engines/slack.py", line 652, in run_commands_from_slack_async                                                          
may 01 16:10:26 salt.master.example.com salt-master[22969]:   File "/tmp/pip-build-1jhjfqa0/salt/salt/engines/slack.py", line 464, in generate_triggered_messages                                                            
may 01 16:10:26 salt.master.example.com salt-master[22969]:   File "/tmp/pip-build-1jhjfqa0/salt/salt/engines/slack.py", line 205, in get_config_groups
may 01 16:10:26 salt.master.example.com salt-master[22969]:   File "/tmp/pip-build-1jhjfqa0/salt/salt/engines/slack.py", line 238, in _groups_from_pillar                                                                    
may 01 16:10:26 salt.master.example.com salt-master[22969]:   File "/srv/deploy/salt/.venv/lib/python3.6/site-packages/salt/client/__init__.py", line 2076, in __init__                                                      
may 01 16:10:26 salt.master.example.com salt-master[22969]:     self.sminion = salt.minion.SMinion(self.opts)
may 01 16:10:26 salt.master.example.com salt-master[22969]:   File "/srv/deploy/salt/.venv/lib/python3.6/site-packages/salt/minion.py", line 787, in __init__                                                                
may 01 16:10:26 salt.master.example.com salt-master[22969]:     lambda: self.eval_master(self.opts, failed=True)
may 01 16:10:26 salt.master.example.com salt-master[22969]:   File "/srv/deploy/salt/.venv/lib/python3.6/site-packages/tornado/ioloop.py", line 458, in run_sync                                                             
may 01 16:10:26 salt.master.example.com salt-master[22969]:     return future_cell[0].result()
may 01 16:10:26 salt.master.example.com salt-master[22969]:   File "/srv/deploy/salt/.venv/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result                                                           
may 01 16:10:26 salt.master.example.com salt-master[22969]:     raise_exc_info(self._exc_info)                                                                                                                                
may 01 16:10:26 salt.master.example.com salt-master[22969]:   File "<string>", line 4, in raise_exc_info                                                                                                                     
may 01 16:10:26 salt.master.example.com salt-master[22969]:   File "/srv/deploy/salt/.venv/lib/python3.6/site-packages/tornado/gen.py", line 307, in wrapper
may 01 16:10:26 salt.master.example.com salt-master[22969]:     yielded = next(result)        
may 01 16:10:26 salt.master.example.com salt-master[22969]:   File "/srv/deploy/salt/.venv/lib/python3.6/site-packages/salt/minion.py", line 700, in eval_master                                                             
may 01 16:10:26 salt.master.example.com salt-master[22969]:     raise exc                                                                                                                                                    
may 01 16:10:26 salt.master.example.com salt-master[22969]:   File "/srv/deploy/salt/.venv/lib/python3.6/site-packages/salt/minion.py", line 691, in eval_master                                                             
may 01 16:10:26 salt.master.example.com salt-master[22969]:     pub_channel = salt.transport.client.AsyncPubChannel.factory(self.opts, **factory_kwargs)
may 01 16:10:26 salt.master.example.com salt-master[22969]:   File "/srv/deploy/salt/.venv/lib/python3.6/site-packages/salt/transport/client.py", line 162, in factory                                                       
may 01 16:10:26 salt.master.example.com salt-master[22969]:     return salt.transport.zeromq.AsyncZeroMQPubChannel(opts, **kwargs)                                                                                           
may 01 16:10:26 salt.master.example.com salt-master[22969]:   File "/srv/deploy/salt/.venv/lib/python3.6/site-packages/salt/transport/zeromq.py", line 345, in __init__
may 01 16:10:26 salt.master.example.com salt-master[22969]:     self.auth = salt.crypt.AsyncAuth(self.opts, io_loop=self.io_loop)                                                                                            
may 01 16:10:26 salt.master.example.com salt-master[22969]:   File "/srv/deploy/salt/.venv/lib/python3.6/site-packages/salt/crypt.py", line 466, in __new__                                                                  
may 01 16:10:26 salt.master.example.com salt-master[22969]:     auth.__singleton_init__(opts, io_loop=io_loop)
may 01 16:10:26 salt.master.example.com salt-master[22969]:   File "/srv/deploy/salt/.venv/lib/python3.6/site-packages/salt/crypt.py", line 505, in __singleton_init__                                                       
may 01 16:10:26 salt.master.example.com salt-master[22969]:     self.get_keys()                                                                                                                                              
may 01 16:10:26 salt.master.example.com salt-master[22969]:   File "/srv/deploy/salt/.venv/lib/python3.6/site-packages/salt/crypt.py", line 765, in get_keys                                                                 
may 01 16:10:26 salt.master.example.com salt-master[22969]:     salt.utils.verify.check_path_traversal(self.opts['pki_dir'], user)                                                                                           
may 01 16:10:26 salt.master.example.com salt-master[22969]:   File "/srv/deploy/salt/.venv/lib/python3.6/site-packages/salt/utils/verify.py", line 413, in check_path_traversal                                              
may 01 16:10:26 salt.master.example.com salt-master[22969]:     raise SaltClientError(msg)                                                                                                                                   
may 01 16:10:26 salt.master.example.com salt-master[22969]: salt.exceptions.SaltClientError: Could not access /etc/salt/pki/minion. Try running as user root.
```

### Versions Report
```
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.27.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.27.0
         Python: 3.6.5 (default, Apr 12 2018, 22:45:43)
   python-gnupg: 0.4.2
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.6

System Versions:
           dist: arch
         locale: UTF-8
        machine: x86_64
        release: 4.15.18-1-hardened
         system: Linux
        version: arch
```

**Comment by rallytime** [comment]
Closed via #47417
