### ISSUE TITLE
salt-master is trying to read salt-minion config files

### ISSUE THREAD

**Issue by viq** [saltstack/salt#47418]
### Description of Issue/Question
When running `salt-master` as dedicated, non-root user, creation of file not readable by that user under `/etc/salt/minion.d/` generates a lot of logs about not being able to read that file.

### Setup
master config:
```
user: _salt
cli_summary: True
state_output: changes
engines:
  - logstash:
      host: 10.20.30.40
      port: 5959
  - webhook:
      port: 8000
      address: 127.0.0.1
state_events: True
external_auth:
  pam:
    viq:
      - .*
      - '@wheel'
      - '@runner'
      - '@jobs'
fileserver_backend:
  - git
  - roots
file_roots:
  base:
    - /srv/salt
    - /srv/salt-formulas/elasticsearch-logstash-kibana-formula
thorium_roots:
  base:
    - /srv/thorium
gitfs_remotes:
  - ssh://git@git.example.com/salt-roots.git
ext_pillar:
  - git:
    - master ssh://git@git.example.com/salt-pillars:
      - user: git
      - pubkey: /var/salt/.ssh/id_rsa.pub
      - privkey: /var/salt/.ssh/id_rsa
gitfs_provider: pygit2
gitfs_user: git
gitfs_pubkey: /var/salt/.ssh/id_rsa.pub
gitfs_privkey: /var/salt/.ssh/id_rsa
state_top_saltenv: base
peer:
  .*:
    - x509.sign_remote_certificate
  salt.master.example.com:
    - grains.get
presence_events: True
reactor:
  - 'salt/auth':
    - salt://reactor/ntpdsync.sls
    - salt://reactor/start-notify.sls
  - 'salt/presence/change':
    - salt://reactor/presence-changes.sls
  - 'salt/engines/hook/prometheus/alertmanager':
    - salt://reactor/prometheus.sls
```

### Steps to Reproduce Issue
```
May 01 20:12:14 salt.master.example.com salt-master[16188]: [CRITICAL] Engine 'reactor' could not be started!                                                                 
May 01 20:12:14 salt.master.example.com salt-master[16188]: Traceback (most recent call last):                                                                                                                               
May 01 20:12:14 salt.master.example.com salt-master[16188]:   File "/srv/deploy/salt/.venv/lib/python3.6/site-packages/salt/engines/__init__.py", line 128, in run          
May 01 20:12:14 salt.master.example.com salt-master[16188]:     self.engine[self.fun](**kwargs)                                                                                                                              
May 01 20:12:14 salt.master.example.com salt-master[16188]:   File "/tmp/pip-build-1jhjfqa0/salt/salt/engines/reactor.py", line 36, in start                                                                                 
May 01 20:12:14 salt.master.example.com salt-master[16188]:   File "/srv/deploy/salt/.venv/lib/python3.6/site-packages/salt/utils/reactor.py", line 57, in __init__                                                          
May 01 20:12:14 salt.master.example.com salt-master[16188]:     self.minion = salt.minion.MasterMinion(local_minion_opts)                                                     
May 01 20:12:14 salt.master.example.com salt-master[16188]:   File "/srv/deploy/salt/.venv/lib/python3.6/site-packages/salt/minion.py", line 864, in __init__
May 01 20:12:14 salt.master.example.com salt-master[16188]:     role='master'
May 01 20:12:14 salt.master.example.com salt-master[16188]:   File "/srv/deploy/salt/.venv/lib/python3.6/site-packages/salt/config/__init__.py", line 2373, in minion_config
May 01 20:12:14 salt.master.example.com salt-master[16188]:     exit_on_config_errors=not ignore_config_errors))
May 01 20:12:14 salt.master.example.com salt-master[16188]:   File "/srv/deploy/salt/.venv/lib/python3.6/site-packages/salt/config/__init__.py", line 2251, in include_config
May 01 20:12:14 salt.master.example.com salt-master[16188]:     opts = _read_conf_file(fn_)
May 01 20:12:14 salt.master.example.com salt-master[16188]:   File "/srv/deploy/salt/.venv/lib/python3.6/site-packages/salt/config/__init__.py", line 2107, in _read_conf_file
May 01 20:12:14 salt.master.example.com salt-master[16188]:     with salt.utils.files.fopen(path, 'r') as conf_file:
May 01 20:12:14 salt.master.example.com salt-master[16188]:   File "/srv/deploy/salt/.venv/lib/python3.6/site-packages/salt/utils/files.py", line 366, in fopen
May 01 20:12:14 salt.master.example.com salt-master[16188]:     f_handle = open(*args, **kwargs)  # pylint: disable=resource-leakage
May 01 20:12:14 salt.master.example.com salt-master[16188]: PermissionError: [Errno 13] Permission denied: '/etc/salt/minion.d/engines.conf'
```

### Versions Report
```
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.27.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.27.0
         Python: 3.6.5 (default, Apr 12 2018, 22:45:43)
   python-gnupg: 0.4.2
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.6

System Versions:
           dist: arch
         locale: UTF-8
        machine: x86_64
        release: 4.15.18-1-hardened
         system: Linux
        version: arch
```

**Comment by gtmanfred** [comment]
This is the expected behavior, the `MasterMinion` inside of the salt master does this.
