### ISSUE TITLE
salt-ssh doesn't work with lets than perfect dns servers

### ISSUE THREAD

**Issue by edgan** [saltstack/salt#47529]
### Description of Issue/Question
I am trying to setup some DNS servers with salt-ssh. Which are also configured as in my /etc/resolv.conf. dns-dns-01 is already configured, but dns-dns-03 is the not setup. The dns-dns-03 instance is first in the resolv.conf.

In ```salt/client/ssh/__init__.py``` on line 355 it tries to use the ip_to_host function to test if it can resolve the target name, not the host entry from the roster. When it fails the hostname is then set to None, and you get the traceback below.

In my opinion this line is useless, because I could set the target name in the roster to be whatever I want, and there shouldn't be an assumption that it will resolve via DNS. Also if I comment out that line, salt-ssh works without error.

Also the whole expand_target function is new, and I question if it does anything useful. It is new in 2018.3.0.

```
salt/client/ssh/__init__.py:
355: hostname = salt.utils.network.ip_to_host(hostname)
```
```
dns-dns-01 = 10.200.32.10
dns-dns-02 = 10.200.40.10
dns-dns-03 = 10.200.24.10
```

### Setup
roster:
```
dns-dns-01.inf.us-west-2.aws.acme.com:
  host: 10.200.32.10
  sudo: True
```
/etc/resolv.conf:
```
nameserver 10.200.24.10
nameserver 10.200.32.10
nameserver 100.200.40.10
```

### Steps to Reproduce Issue
```
salt-ssh -i dns-dns-01.inf.us-west-2.aws.acme.com
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/usr/bin/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 425, in salt_ssh
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/ssh.py", line 23, in run
    ssh = salt.client.ssh.SSH(self.config)
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 235, in __init__
    self.tgt_type)
  File "/usr/lib/python2.7/site-packages/salt/roster/__init__.py", line 105, in targets
    targets.update(self.rosters[f_str](tgt, tgt_type))
  File "/usr/lib/python2.7/site-packages/salt/roster/flat.py", line 50, in targets
    return rmatcher.targets()
  File "/usr/lib/python2.7/site-packages/salt/roster/flat.py", line 68, in targets
    return getattr(self, 'ret_{0}_minions'.format(self.tgt_type))()
  File "/usr/lib/python2.7/site-packages/salt/roster/flat.py", line 78, in ret_glob_minions
    if fnmatch.fnmatch(minion, self.tgt):
  File "/usr/lib64/python2.7/fnmatch.py", line 43, in fnmatch
    return fnmatchcase(name, pat)
  File "/usr/lib64/python2.7/fnmatch.py", line 79, in fnmatchcase
    res = translate(pat)
  File "/usr/lib64/python2.7/fnmatch.py", line 91, in translate
    i, n = 0, len(pat)
TypeError: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/usr/bin/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 425, in salt_ssh
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/ssh.py", line 23, in run
    ssh = salt.client.ssh.SSH(self.config)
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 235, in __init__
    self.tgt_type)
  File "/usr/lib/python2.7/site-packages/salt/roster/__init__.py", line 105, in targets
    targets.update(self.rosters[f_str](tgt, tgt_type))
  File "/usr/lib/python2.7/site-packages/salt/roster/flat.py", line 50, in targets
    return rmatcher.targets()
  File "/usr/lib/python2.7/site-packages/salt/roster/flat.py", line 68, in targets
    return getattr(self, 'ret_{0}_minions'.format(self.tgt_type))()
  File "/usr/lib/python2.7/site-packages/salt/roster/flat.py", line 78, in ret_glob_minions
    if fnmatch.fnmatch(minion, self.tgt):
  File "/usr/lib64/python2.7/fnmatch.py", line 43, in fnmatch
    return fnmatchcase(name, pat)
  File "/usr/lib64/python2.7/fnmatch.py", line 79, in fnmatchcase
    res = translate(pat)
  File "/usr/lib64/python2.7/fnmatch.py", line 91, in translate
    i, n = 0, len(pat)
TypeError: object of type 'NoneType' has no len()
```

### Versions Report
```
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: 1.11.2
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.5.5
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Mar 14 2018, 16:45:33)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.1.6
 
System Versions:
           dist: fedora 28 Twenty Eight
         locale: UTF-8
        machine: x86_64
        release: 4.16.6-302.fc28.x86_64
         system: Linux
        version: Fedora 28 Twenty Eight
```

**Comment by edgan** [comment]
I wouldn't say it is a pure duplicate. I question the whole existence of the expand_target function. Even if it is useful, it seems to be doing very questionable things.

**Comment by Ch3LL** [comment]
ping @isbm can you clarify that purpose behind the new function?

**Comment by edgan** [comment]
This has been addressed in other issues. Closing.
