### ISSUE TITLE
Errors in salt-master log after installing from head of 2018.3 branch

### ISSUE THREAD

**Issue by ssgward** [saltstack/salt#47522]
Errors in salt-master log after installing from head of 2018.3 branch

Steps:
1. Install clean OS (we’ve tried CentOS 7.3, 7.4, RH 7.4, Ubuntu 16.06 in C7/ONE and Vagrant)
2. Bootstrap head of 2018.3. Install master and minion
3. Restart salt-master service
4. check /var/log/salt/master

Here are the errors:
```
[root@SSE ~]# cat /var/log/salt/master
2018-05-07 19:35:39,374 [salt.utils.stringutils:337 ][ERROR   ][6885] Value 'bin' or expression set([u'root']) is not a string
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/stringutils.py", line 329, in expr_match
    if fnmatch.fnmatch(line, expr):
  File "/usr/lib64/python2.7/fnmatch.py", line 43, in fnmatch
    return fnmatchcase(name, pat)
  File "/usr/lib64/python2.7/fnmatch.py", line 74, in fnmatchcase
    if not pat in _cache:
TypeError: unhashable type: 'set'
2018-05-07 19:35:39,375 [salt.utils.stringutils:337 ][ERROR   ][6885] Value 'daemon' or expression set([u'root']) is not a string
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/stringutils.py", line 329, in expr_match
    if fnmatch.fnmatch(line, expr):
  File "/usr/lib64/python2.7/fnmatch.py", line 43, in fnmatch
    return fnmatchcase(name, pat)
  File "/usr/lib64/python2.7/fnmatch.py", line 74, in fnmatchcase
    if not pat in _cache:
TypeError: unhashable type: 'set'
2018-05-07 19:35:39,375 [salt.utils.stringutils:337 ][ERROR   ][6885] Value 'adm' or expression set([u'root']) is not a string
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/stringutils.py", line 329, in expr_match
    if fnmatch.fnmatch(line, expr):
  File "/usr/lib64/python2.7/fnmatch.py", line 43, in fnmatch
    return fnmatchcase(name, pat)
  File "/usr/lib64/python2.7/fnmatch.py", line 74, in fnmatchcase
    if not pat in _cache:
TypeError: unhashable type: 'set'
2018-05-07 19:35:39,375 [salt.utils.stringutils:337 ][ERROR   ][6885] Value 'lp' or expression set([u'root']) is not a string
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/stringutils.py", line 329, in expr_match
    if fnmatch.fnmatch(line, expr):
  File "/usr/lib64/python2.7/fnmatch.py", line 43, in fnmatch
    return fnmatchcase(name, pat)
  File "/usr/lib64/python2.7/fnmatch.py", line 74, in fnmatchcase
    if not pat in _cache:
TypeError: unhashable type: 'set'
2018-05-07 19:35:39,375 [salt.utils.stringutils:337 ][ERROR   ][6885] Value 'sync' or expression set([u'root']) is not a string
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/stringutils.py", line 329, in expr_match
    if fnmatch.fnmatch(line, expr):
  File "/usr/lib64/python2.7/fnmatch.py", line 43, in fnmatch
    return fnmatchcase(name, pat)
  File "/usr/lib64/python2.7/fnmatch.py", line 74, in fnmatchcase
    if not pat in _cache:
TypeError: unhashable type: 'set'
2018-05-07 19:35:39,376 [salt.utils.stringutils:337 ][ERROR   ][6885] Value 'shutdown' or expression set([u'root']) is not a string
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/stringutils.py", line 329, in expr_match
    if fnmatch.fnmatch(line, expr):
  File "/usr/lib64/python2.7/fnmatch.py", line 43, in fnmatch
    return fnmatchcase(name, pat)
  File "/usr/lib64/python2.7/fnmatch.py", line 74, in fnmatchcase
    if not pat in _cache:
TypeError: unhashable type: 'set'
2018-05-07 19:35:39,376 [salt.utils.stringutils:337 ][ERROR   ][6885] Value 'halt' or expression set([u'root']) is not a string
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/stringutils.py", line 329, in expr_match
    if fnmatch.fnmatch(line, expr):
  File "/usr/lib64/python2.7/fnmatch.py", line 43, in fnmatch
    return fnmatchcase(name, pat)
  File "/usr/lib64/python2.7/fnmatch.py", line 74, in fnmatchcase
    if not pat in _cache:
TypeError: unhashable type: 'set'
2018-05-07 19:35:39,376 [salt.utils.stringutils:337 ][ERROR   ][6885] Value 'mail' or expression set([u'root']) is not a string
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/stringutils.py", line 329, in expr_match
    if fnmatch.fnmatch(line, expr):
  File "/usr/lib64/python2.7/fnmatch.py", line 43, in fnmatch
    return fnmatchcase(name, pat)
  File "/usr/lib64/python2.7/fnmatch.py", line 74, in fnmatchcase
    if not pat in _cache:
TypeError: unhashable type: 'set'
2018-05-07 19:35:39,376 [salt.utils.stringutils:337 ][ERROR   ][6885] Value 'operator' or expression set([u'root']) is not a string
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/stringutils.py", line 329, in expr_match
    if fnmatch.fnmatch(line, expr):
  File "/usr/lib64/python2.7/fnmatch.py", line 43, in fnmatch
    return fnmatchcase(name, pat)
  File "/usr/lib64/python2.7/fnmatch.py", line 74, in fnmatchcase
    if not pat in _cache:
TypeError: unhashable type: 'set'
2018-05-07 19:35:39,376 [salt.utils.stringutils:337 ][ERROR   ][6885] Value 'games' or expression set([u'root']) is not a string
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/stringutils.py", line 329, in expr_match
    if fnmatch.fnmatch(line, expr):
  File "/usr/lib64/python2.7/fnmatch.py", line 43, in fnmatch
    return fnmatchcase(name, pat)
  File "/usr/lib64/python2.7/fnmatch.py", line 74, in fnmatchcase
    if not pat in _cache:
TypeError: unhashable type: 'set'
2018-05-07 19:35:39,376 [salt.utils.stringutils:337 ][ERROR   ][6885] Value 'ftp' or expression set([u'root']) is not a string
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/stringutils.py", line 329, in expr_match
    if fnmatch.fnmatch(line, expr):
  File "/usr/lib64/python2.7/fnmatch.py", line 43, in fnmatch
    return fnmatchcase(name, pat)
  File "/usr/lib64/python2.7/fnmatch.py", line 74, in fnmatchcase
    if not pat in _cache:
TypeError: unhashable type: 'set'
2018-05-07 19:35:39,377 [salt.utils.stringutils:337 ][ERROR   ][6885] Value 'nobody' or expression set([u'root']) is not a string
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/stringutils.py", line 329, in expr_match
    if fnmatch.fnmatch(line, expr):
  File "/usr/lib64/python2.7/fnmatch.py", line 43, in fnmatch
    return fnmatchcase(name, pat)
  File "/usr/lib64/python2.7/fnmatch.py", line 74, in fnmatchcase
    if not pat in _cache:
TypeError: unhashable type: 'set'
2018-05-07 19:35:39,377 [salt.utils.stringutils:337 ][ERROR   ][6885] Value 'systemd-bus-proxy' or expression set([u'root']) is not a string
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/stringutils.py", line 329, in expr_match
    if fnmatch.fnmatch(line, expr):
  File "/usr/lib64/python2.7/fnmatch.py", line 43, in fnmatch
    return fnmatchcase(name, pat)
  File "/usr/lib64/python2.7/fnmatch.py", line 74, in fnmatchcase
    if not pat in _cache:
TypeError: unhashable type: 'set'
2018-05-07 19:35:39,377 [salt.utils.stringutils:337 ][ERROR   ][6885] Value 'systemd-network' or expression set([u'root']) is not a string
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/stringutils.py", line 329, in expr_match
    if fnmatch.fnmatch(line, expr):
  File "/usr/lib64/python2.7/fnmatch.py", line 43, in fnmatch
    return fnmatchcase(name, pat)
  File "/usr/lib64/python2.7/fnmatch.py", line 74, in fnmatchcase
    if not pat in _cache:
TypeError: unhashable type: 'set'
2018-05-07 19:35:39,377 [salt.utils.stringutils:337 ][ERROR   ][6885] Value 'dbus' or expression set([u'root']) is not a string
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/stringutils.py", line 329, in expr_match
    if fnmatch.fnmatch(line, expr):
  File "/usr/lib64/python2.7/fnmatch.py", line 43, in fnmatch
    return fnmatchcase(name, pat)
  File "/usr/lib64/python2.7/fnmatch.py", line 74, in fnmatchcase
    if not pat in _cache:
TypeError: unhashable type: 'set'
2018-05-07 19:35:39,377 [salt.utils.stringutils:337 ][ERROR   ][6885] Value 'polkitd' or expression set([u'root']) is not a string
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/stringutils.py", line 329, in expr_match
    if fnmatch.fnmatch(line, expr):
  File "/usr/lib64/python2.7/fnmatch.py", line 43, in fnmatch
    return fnmatchcase(name, pat)
  File "/usr/lib64/python2.7/fnmatch.py", line 74, in fnmatchcase
    if not pat in _cache:
TypeError: unhashable type: 'set'
2018-05-07 19:35:39,377 [salt.utils.stringutils:337 ][ERROR   ][6885] Value 'rpc' or expression set([u'root']) is not a string
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/stringutils.py", line 329, in expr_match
    if fnmatch.fnmatch(line, expr):
  File "/usr/lib64/python2.7/fnmatch.py", line 43, in fnmatch
    return fnmatchcase(name, pat)
  File "/usr/lib64/python2.7/fnmatch.py", line 74, in fnmatchcase
    if not pat in _cache:
TypeError: unhashable type: 'set'
2018-05-07 19:35:39,377 [salt.utils.stringutils:337 ][ERROR   ][6885] Value 'tss' or expression set([u'root']) is not a string
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/stringutils.py", line 329, in expr_match
    if fnmatch.fnmatch(line, expr):
  File "/usr/lib64/python2.7/fnmatch.py", line 43, in fnmatch
    return fnmatchcase(name, pat)
  File "/usr/lib64/python2.7/fnmatch.py", line 74, in fnmatchcase
    if not pat in _cache:
TypeError: unhashable type: 'set'
2018-05-07 19:35:39,378 [salt.utils.stringutils:337 ][ERROR   ][6885] Value 'rpcuser' or expression set([u'root']) is not a string
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/stringutils.py", line 329, in expr_match
    if fnmatch.fnmatch(line, expr):
  File "/usr/lib64/python2.7/fnmatch.py", line 43, in fnmatch
    return fnmatchcase(name, pat)
  File "/usr/lib64/python2.7/fnmatch.py", line 74, in fnmatchcase
    if not pat in _cache:
TypeError: unhashable type: 'set'
2018-05-07 19:35:39,378 [salt.utils.stringutils:337 ][ERROR   ][6885] Value 'nfsnobody' or expression set([u'root']) is not a string
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/stringutils.py", line 329, in expr_match
    if fnmatch.fnmatch(line, expr):
  File "/usr/lib64/python2.7/fnmatch.py", line 43, in fnmatch
    return fnmatchcase(name, pat)
  File "/usr/lib64/python2.7/fnmatch.py", line 74, in fnmatchcase
    if not pat in _cache:
TypeError: unhashable type: 'set'
2018-05-07 19:35:39,378 [salt.utils.stringutils:337 ][ERROR   ][6885] Value 'postfix' or expression set([u'root']) is not a string
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/stringutils.py", line 329, in expr_match
    if fnmatch.fnmatch(line, expr):
  File "/usr/lib64/python2.7/fnmatch.py", line 43, in fnmatch
    return fnmatchcase(name, pat)
  File "/usr/lib64/python2.7/fnmatch.py", line 74, in fnmatchcase
    if not pat in _cache:
TypeError: unhashable type: 'set'
2018-05-07 19:35:39,378 [salt.utils.stringutils:337 ][ERROR   ][6885] Value 'sshd' or expression set([u'root']) is not a string
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/stringutils.py", line 329, in expr_match
    if fnmatch.fnmatch(line, expr):
  File "/usr/lib64/python2.7/fnmatch.py", line 43, in fnmatch
    return fnmatchcase(name, pat)
  File "/usr/lib64/python2.7/fnmatch.py", line 74, in fnmatchcase
    if not pat in _cache:
TypeError: unhashable type: 'set'
2018-05-07 19:35:39,378 [salt.utils.stringutils:337 ][ERROR   ][6885] Value 'chrony' or expression set([u'root']) is not a string
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/stringutils.py", line 329, in expr_match
    if fnmatch.fnmatch(line, expr):
  File "/usr/lib64/python2.7/fnmatch.py", line 43, in fnmatch
    return fnmatchcase(name, pat)
  File "/usr/lib64/python2.7/fnmatch.py", line 74, in fnmatchcase
    if not pat in _cache:
TypeError: unhashable type: 'set'
2018-05-07 19:35:39,378 [salt.utils.stringutils:337 ][ERROR   ][6885] Value 'vagrant' or expression set([u'root']) is not a string
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/stringutils.py", line 329, in expr_match
    if fnmatch.fnmatch(line, expr):
  File "/usr/lib64/python2.7/fnmatch.py", line 43, in fnmatch
    return fnmatchcase(name, pat)
  File "/usr/lib64/python2.7/fnmatch.py", line 74, in fnmatchcase
    if not pat in _cache:
TypeError: unhashable type: 'set'
2018-05-07 19:35:39,379 [salt.utils.stringutils:337 ][ERROR   ][6885] Value 'vboxadd' or expression set([u'root']) is not a string
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/stringutils.py", line 329, in expr_match
    if fnmatch.fnmatch(line, expr):
  File "/usr/lib64/python2.7/fnmatch.py", line 43, in fnmatch
    return fnmatchcase(name, pat)
  File "/usr/lib64/python2.7/fnmatch.py", line 74, in fnmatchcase
    if not pat in _cache:
TypeError: unhashable type: 'set'
```

### Versions Report
```
[root@SSE ~]# salt --versions-report
Salt Version:
           Salt: 2018.3.0-n/a-05fc52f

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

**Comment by rallytime** [comment]
@terminalmage Can you look at this really quickly and fix this up?

**Comment by terminalmage** [comment]
I opened https://github.com/saltstack/salt/pull/47159 last week to fix this, but there are unresolved test failures that I still need to take care of.

**Comment by terminalmage** [comment]
That PR should be fixed now, pending test results.
