### ISSUE TITLE
SPM multiple definitions for opts with post_local_state

### ISSUE THREAD

**Issue by daveneeley** [saltstack/salt#47530]
### Description of Issue/Question
I tried to create a top-formula spm package, containing a top/init.sls file that would be symlinked to /srv/salt/top.sls by the post_local_state block in the FORMULA file. The end goal is to completely set up a salt master using only spm packages.

### Setup
A salt formula with this in the FORMULA file
```
name: top
os: CentOS
os_family: RedHat
version: 201802
release: 7
summary: top level formula
description: top level formula
top_level_dir: top
post_local_state: >
  /srv/spm/salt/top.sls:
    file.symlink:
      - target: /srv/spm/salt/top/init.sls
      - makedirs: True
```

### Steps to Reproduce Issue
```
[... srv]$ sudo spm install top -l debug
[DEBUG   ] Missing configuration file: /etc/salt/spm
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt
[DEBUG   ] Missing configuration file: /etc/salt/spm
[DEBUG   ] Including configuration from '/etc/salt/master.d/file_roots.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/file_roots.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/logging.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/logging.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/pillar_roots.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/pillar_roots.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/reactor.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/reactor.conf
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/file_roots.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/file_roots.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/logging.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/logging.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/pillar_roots.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/pillar_roots.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/reactor.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/reactor.conf
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/file_roots.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/file_roots.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/logging.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/logging.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/pillar_roots.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/pillar_roots.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/reactor.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/reactor.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] LazyLoaded localfs.init_kwargs
Installing packages:
        top

Proceed? [N/y] y
[DEBUG   ] LazyLoaded localfs.init_kwargs
... installing top
[DEBUG   ] Installing package file top to /srv/spm/salt
[DEBUG   ] Installing package file top/init.sls to /srv/spm/salt
[DEBUG   ] FORMULA not in top level directory, not installing
[DEBUG   ] Executing post_local_state script
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] compile template: :string:
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: render_tmpl() got multiple values for keyword argument 'opts'
Traceback (most recent call last):
  File "/bin/spm", line 12, in <module>
    salt_spm()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 487, in salt_spm
    spm.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/spm.py", line 41, in run
    client.run(self.args)
  File "/usr/lib/python2.7/site-packages/salt/spm/__init__.py", line 116, in run
    self._install(args)
  File "/usr/lib/python2.7/site-packages/salt/spm/__init__.py", line 367, in _install
    self._install_indv_pkg(package, out_file)
  File "/usr/lib/python2.7/site-packages/salt/spm/__init__.py", line 543, in _install_indv_pkg
    high_data = self._render(formula_def['post_local_state'], formula_def)
  File "/usr/lib/python2.7/site-packages/salt/spm/__init__.py", line 1113, in _render
    **template_vars
  File "/usr/lib/python2.7/site-packages/salt/template.py", line 95, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/usr/lib/python2.7/site-packages/salt/renderers/jinja.py", line 70, in render
    **kws)
TypeError: render_tmpl() got multiple values for keyword argument 'opts'
Traceback (most recent call last):
  File "/bin/spm", line 12, in <module>
    salt_spm()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 487, in salt_spm
    spm.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/spm.py", line 41, in run
    client.run(self.args)
  File "/usr/lib/python2.7/site-packages/salt/spm/__init__.py", line 116, in run
    self._install(args)
  File "/usr/lib/python2.7/site-packages/salt/spm/__init__.py", line 367, in _install
    self._install_indv_pkg(package, out_file)
  File "/usr/lib/python2.7/site-packages/salt/spm/__init__.py", line 543, in _install_indv_pkg
    high_data = self._render(formula_def['post_local_state'], formula_def)
  File "/usr/lib/python2.7/site-packages/salt/spm/__init__.py", line 1113, in _render
    **template_vars
  File "/usr/lib/python2.7/site-packages/salt/template.py", line 95, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/usr/lib/python2.7/site-packages/salt/renderers/jinja.py", line 70, in render
    **kws)
TypeError: render_tmpl() got multiple values for keyword argument 'opts'
```

### Versions Report
```
Salt Version:
           Salt: 2017.7.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.16.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

**Comment by daveneeley** [comment]
@plastikos this is the bug I showed you at the meetup.

**Comment by Ch3LL** [comment]
can you paste a versions report: `salt --versions-report`

**Comment by daveneeley** [comment]
Here you go
```
Salt Version:
           Salt: 2017.7.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.16.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

**Comment by daveneeley** [comment]
@Ch3LL I added the versions report above. This should reproduce for all four state combinations that are allowed in the `FORMULA` file.

**Comment by daveneeley** [comment]
The trouble is that [spm/__init__.py](https://github.com/saltstack/salt/blob/2017.7/salt/spm/__init__.py#L1105) passes a new 'opts' dict, while the [Jinja renderer](https://github.com/saltstack/salt/blob/2017.7/salt/renderers/jinja.py#L63) tries to add the global __opts__ deeper in the same call stack.

**Comment by Ch3LL** [comment]
Thanks for providing the versions report :)

ping @team-spm any ideas here?
