### ISSUE TITLE
--out=table broken in  2018.3.0 'str' object but received a 'unicode'

### ISSUE THREAD

**Issue by FedericoOlivieri** [saltstack/salt#47587]
### Description of Issue/Question
`--out=table  ` doesn't work on salt-proxy. All other outputs work fine (json,raw,etc)

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
```
$ sudo salt ios.aut.lab net.arp --out=table
[ERROR   ] Nested output failed: 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 47, in try_printout
    printout = get_printout('nested', opts)(data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/output/table_out.py", line 370, in output
    labels_key=labels_key))
  File "/usr/lib/python2.7/dist-packages/salt/output/table_out.py", line 295, in display
    self.display(val, indent + 4, out, rows_key=rows_key, labels_key=labels_key)
  File "/usr/lib/python2.7/dist-packages/salt/output/table_out.py", line 293, in display
    out.extend(self.display_rows(rows, labels, indent))
  File "/usr/lib/python2.7/dist-packages/salt/output/table_out.py", line 250, in display_rows
    return self.prepare_rows(labels_and_rows, indent + 4, has_header)
  File "/usr/lib/python2.7/dist-packages/salt/output/table_out.py", line 187, in prepare_rows
    ]) + self.suffix
TypeError: descriptor 'center' requires a 'str' object but received a 'unicode'
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: descriptor 'center' requires a 'str' object but received a 'unicode'
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 485, in salt_main
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/salt.py", line 197, in run
    self._output_ret(ret_, out, retcode=retcode)
  File "/usr/lib/python2.7/dist-packages/salt/cli/salt.py", line 376, in _output_ret
    _retcode=retcode)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 94, in display_output
    display_data = try_printout(data, out, opts, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 52, in try_printout
    printout = get_printout('raw', opts)(data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/output/table_out.py", line 370, in output
    labels_key=labels_key))
  File "/usr/lib/python2.7/dist-packages/salt/output/table_out.py", line 295, in display
    self.display(val, indent + 4, out, rows_key=rows_key, labels_key=labels_key)
  File "/usr/lib/python2.7/dist-packages/salt/output/table_out.py", line 293, in display
    out.extend(self.display_rows(rows, labels, indent))
  File "/usr/lib/python2.7/dist-packages/salt/output/table_out.py", line 250, in display_rows
    return self.prepare_rows(labels_and_rows, indent + 4, has_header)
  File "/usr/lib/python2.7/dist-packages/salt/output/table_out.py", line 187, in prepare_rows
    ]) + self.suffix
TypeError: descriptor 'center' requires a 'str' object but received a 'unicode'
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 485, in salt_main
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/salt.py", line 197, in run
    self._output_ret(ret_, out, retcode=retcode)
  File "/usr/lib/python2.7/dist-packages/salt/cli/salt.py", line 376, in _output_ret
    _retcode=retcode)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 94, in display_output
    display_data = try_printout(data, out, opts, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 52, in try_printout
    printout = get_printout('raw', opts)(data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/output/table_out.py", line 370, in output
    labels_key=labels_key))
  File "/usr/lib/python2.7/dist-packages/salt/output/table_out.py", line 295, in display
    self.display(val, indent + 4, out, rows_key=rows_key, labels_key=labels_key)
  File "/usr/lib/python2.7/dist-packages/salt/output/table_out.py", line 293, in display
    out.extend(self.display_rows(rows, labels, indent))
  File "/usr/lib/python2.7/dist-packages/salt/output/table_out.py", line 250, in display_rows
    return self.prepare_rows(labels_and_rows, indent + 4, has_header)
  File "/usr/lib/python2.7/dist-packages/salt/output/table_out.py", line 187, in prepare_rows
    ]) + self.suffix
TypeError: descriptor 'center' requires a 'str' object but received a 'unicode'
```
```
federico@federico:~ $ sudo salt ios.aut.lab net.arp --out=raw
{u'ios.aut.lab': {u'comment': u'', u'result': True, u'out': [{u'interface': u'GigabitEthernet0/1', u'ip': u'4.4.4.8', u'mac': u'0C:E0:2E:A5:91:01', u'age': 0.0}, {u'interface': u'GigabitEthernet0/0', u'ip': u'10.255.255.1', u'mac': u'E6:49:C1:36:EE:74', u'age': 119.0}, {u'interface': u'GigabitEthernet0/0', u'ip': u'10.255.255.101', u'mac': u'0C:E0:2E:A5:91:00', u'age': 0.0}]}}
```

### Versions Report
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Nov 24 2017, 17:33:09)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.4 
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-6-amd64
         system: Linux
        version: debian 9.4

**Comment by Ch3LL** [comment]
looks like i can replicate this outside of proxy minion: `sudo salt-call --local network.routes --out=table `

ping @terminalmage any ideas here?
