### ISSUE TITLE
Broken Jinja in top file makes minions not to see it

### ISSUE THREAD

**Issue by bebosudo** [saltstack/salt#47612]
### Setup
Centos 7, add salt repo, `yum install salt-master salt-minion`.

### Steps to Reproduce Issue
```
base:
  '*':
    # Here I place a comment on the following state, with a broken jinja command {{broken}}
    - do_something
```

This results in:
```
# salt \* state.apply
frontend:
----------
          ID: states
    Function: no.None
      Result: False
     Comment: No Top file or master_tops data matches found.
     Changes:   

Summary for frontend
------------
Succeeded: 0
Failed:    1
```

```
2018-05-11 15:05:20,717 [salt.utils.templates:180 ][ERROR   ][2216] Rendering exception occurred
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 169, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 390, in render_jinja_tmpl
    buf=tmplstr)
SaltRenderError: Jinja variable 'broken' is undefined
2018-05-11 15:05:20,718 [salt.state       :3288][ERROR   ][2216] Unable to render top file: Jinja variable 'broken' is undefined
```

I've spent half an hour to solve this issue. Is this behaviour normal? Couldn't we add a more detailed error or add a reference to watch in the logs? I could create a PR if you agree

### Versions Report
Master and minions are two identical docker images just built.

```
# salt --versions-report
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.13.16-100.fc25.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

**Comment by Ch3LL** [comment]
yeah i think it could be useful to show there is a rendering error if thats the reason for not being able to find the file . PR would be greatly appreciated :)

**Comment by bebosudo** [comment]
PR submitted, closing the issue.
