### ISSUE TITLE
reg.present fails when integer value is used on DWORD type

### ISSUE THREAD

**Issue by breshead** [saltstack/salt#47653]
### Description of Issue/Question
Older version (2017.7.2) would allow you to use bare integers when defining the value on reg.present. When moving to 2018.3.0 this now fails. 

When value does not need changed the error does not show.

Quoting the integer value bypasses the error, but then it triggers the 'change' every time regardless if it is the same or not.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
~~~
set-login-reg:
     reg.present:
         - name: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System
         - vname: dontdisplaylastusername
         - vdata: 1
         - vtype: REG_DWORD
~~~

### Steps to Reproduce Issue

Simply run the above state on a windows minion.
Output as follows..
~~~
          ID: set-login-reg
    Function: reg.present
        Name: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "c:\salt\bin\lib\site-packages\salt\state.py", line 1878, in call
                  **cdata['kwargs'])
                File "c:\salt\bin\lib\site-packages\salt\loader.py", line 1823, in wrapper
                  return f(*args, **kwargs)
                File "c:\salt\bin\lib\site-packages\salt\states\reg.py", line 196, in present
                  vdata_decoded = salt.utils.stringutils.to_unicode(vdata, 'utf-8')
                File "c:\salt\bin\lib\site-packages\salt\utils\stringutils.py", line 115, in to_unicode
                  raise TypeError('expected str or bytearray')
              TypeError: expected str or bytearray
     Started: 17:50:35.943000
    Duration: 16.0 ms
     Changes:  
~~~

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Minion and Master running same version (2018.3.0)
~~~
BYDT01:
    Salt Version:
               Salt: 2018.3.0
     
    Dependency Versions:
               cffi: 1.10.0
           cherrypy: 10.2.1
           dateutil: 2.6.1
          docker-py: Not Installed
              gitdb: 2.0.3
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.10
            libgit2: Not Installed
            libnacl: 1.6.1
           M2Crypto: Not Installed
               Mako: 1.0.7
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.18
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
       python-gnupg: 0.4.1
             PyYAML: 3.12
              PyZMQ: 16.0.3
               RAET: Not Installed
              smmap: 2.0.3
            timelib: 0.2.4
            Tornado: 4.5.2
                ZMQ: 4.1.6
     
    System Versions:
               dist:   
             locale: cp1252
            machine: AMD64
            release: 7
             system: Windows
            version: 7 6.1.7601 SP1 Multiprocessor Free
~~~

**Comment by breshead** [comment]
When quoting, even though the error does not show, it triggers the 'change' every time regardless if it is the same or not.

**Comment by gtmanfred** [comment]
@saltstack/team-windows can yall take a look at this?

I think this probably should just need to be changed to only running to_unicode if isinstance(six.text_type)

Thanks,
Daniel

**Comment by twangboy** [comment]
This was fixed by https://github.com/saltstack/salt/pull/47107 and will be in the 2018.3.1 release of Salt
