### ISSUE TITLE
UnboundLocalError: local variable 'current_state' referenced before assignment

### ISSUE THREAD

**Issue by kunal-bajpai** [saltstack/salt#47654]
I encountered the following error in the logs of a Salt minion.
```
2018-04-26 22:05:07,015 [salt.utils.parsers][WARNING ][18889] Minion received a SIGTERM. Exiting.
2018-04-26 22:05:07,015 [salt.cli.daemons ][INFO    ][18889] Shutting down the Salt Minion
2018-04-26 22:05:07,517 [tornado.application][ERROR   ][18889] Exception in callback <functools.partial object at 0x7f094dbf8e10>
Traceback (most recent call last):
  File "/root/.pex/install/tornado-4.5.1-cp27-cp27mu-linux_x86_64.whl.fb67a9263e015c45296bb7103c9afdb612cd69fa/tornado-4.5.1-cp27-cp27mu-linux_x86_64.whl/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/root/.pex/install/tornado-4.5.1-cp27-cp27mu-linux_x86_64.whl.fb67a9263e015c45296bb7103c9afdb612cd69fa/tornado-4.5.1-cp27-cp27mu-linux_x86_64.whl/tornado/stack_context.py", line 279, in null_wrapper
    _state.contexts = current_state
UnboundLocalError: local variable 'current_state' referenced before assignment
2018-04-26 23:15:14,613 [tornado.application][ERROR   ][18889] Exception in callback <functools.partial object at 0x7f094eaf5890>
Traceback (most recent call last):
  File "/root/.pex/install/tornado-4.5.1-cp27-cp27mu-linux_x86_64.whl.fb67a9263e015c45296bb7103c9afdb612cd69fa/tornado-4.5.1-cp27-cp27mu-linux_x86_64.whl/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/root/.pex/install/tornado-4.5.1-cp27-cp27mu-linux_x86_64.whl.fb67a9263e015c45296bb7103c9afdb612cd69fa/tornado-4.5.1-cp27-cp27mu-linux_x86_64.whl/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/root/.pex/install/tornado-4.5.1-cp27-cp27mu-linux_x86_64.whl.fb67a9263e015c45296bb7103c9afdb612cd69fa/tornado-4.5.1-cp27-cp27mu-linux_x86_64.whl/tornado/ioloop.py", line 626, in _discard_future_result
    future.result()
  File "/root/.pex/install/tornado-4.5.1-cp27-cp27mu-linux_x86_64.whl.fb67a9263e015c45296bb7103c9afdb612cd69fa/tornado-4.5.1-cp27-cp27mu-linux_x86_64.whl/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/root/.pex/install/tornado-4.5.1-cp27-cp27mu-linux_x86_64.whl.fb67a9263e015c45296bb7103c9afdb612cd69fa/tornado-4.5.1-cp27-cp27mu-linux_x86_64.whl/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/root/.pex/install/salt-2016.11.7-py2-none-any.whl.249b465ff64d91b2728e6ba08207c57bb133c22f/salt-2016.11.7-py2-none-any.whl/salt/minion.py", line 829, in handle_event
    yield [minion.handle_event(package) for minion in self.minions]
  File "/root/.pex/install/tornado-4.5.1-cp27-cp27mu-linux_x86_64.whl.fb67a9263e015c45296bb7103c9afdb612cd69fa/tornado-4.5.1-cp27-cp27mu-linux_x86_64.whl/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/root/.pex/install/tornado-4.5.1-cp27-cp27mu-linux_x86_64.whl.fb67a9263e015c45296bb7103c9afdb612cd69fa/tornado-4.5.1-cp27-cp27mu-linux_x86_64.whl/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/root/.pex/install/tornado-4.5.1-cp27-cp27mu-linux_x86_64.whl.fb67a9263e015c45296bb7103c9afdb612cd69fa/tornado-4.5.1-cp27-cp27mu-linux_x86_64.whl/tornado/gen.py", line 828, in callback
    result_list.append(f.result())
  File "/root/.pex/install/tornado-4.5.1-cp27-cp27mu-linux_x86_64.whl.fb67a9263e015c45296bb7103c9afdb612cd69fa/tornado-4.5.1-cp27-cp27mu-linux_x86_64.whl/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/root/.pex/install/tornado-4.5.1-cp27-cp27mu-linux_x86_64.whl.fb67a9263e015c45296bb7103c9afdb612cd69fa/tornado-4.5.1-cp27-cp27mu-linux_x86_64.whl/tornado/gen.py", line 307, in wrapper
    yielded = next(result)
  File "/root/.pex/install/salt-2016.11.7-py2-none-any.whl.249b465ff64d91b2728e6ba08207c57bb133c22f/salt-2016.11.7-py2-none-any.whl/salt/minion.py", line 1979, in handle_event
    notify=data.get('notify', False)
  File "/root/.pex/install/salt-2016.11.7-py2-none-any.whl.249b465ff64d91b2728e6ba08207c57bb133c22f/salt-2016.11.7-py2-none-any.whl/salt/minion.py", line 1820, in module_refresh
    self.schedule.functions = self.functions
AttributeError: 'Minion' object has no attribute 'schedule'
```
The minion version is 2016.11.7

The attribute error then continues indefinitely. Seems like the minion fails to stop but disconnects from the master causing it to fail to run its schedule.

I've checked on possible issues with tornado in https://github.com/tornadoweb/tornado/issues/2381 but a tornado issue seems unlikely.

**Comment by gtmanfred** [comment]
Can you try upgrading to the latest version of 2016.11, and see if 2016.11.9 works for you?

Also, may be worth while upgrading to 2017.7

I have been unable to replicate this issue with a basic schedule setup, can you provide me the config files for your minion and master? and any schedules you may be setting in pillars and grains?

Thanks,
Daniel

**Comment by kunal-bajpai** [comment]
Upgrading the minion is not possible. I work for LinkedIn and we have a massive stack here.

We’ve seen this issue on a fraction of minions so it isn’t occuring every time a minion gets sigterm. Also, the schedule exception happens way after the UnboundLocalError so I don’t think it is related. I just posted it because it could give you some hint of the state that the minion is in (disconnected from the master). It seems like the UnboundLocalError prevents a clean shutdown because it happens exactly when a sigterm is received.

If you look at the tornado issue I’ve linked, the dev thinks it could be something to do with threading. Since salt has labyrynthine threading/processing, I was hoping you could help.

**Comment by gtmanfred** [comment]
Hrm, yes it seems like it would be unrelated to the schedule issue.

Do you have `multiprocessing: False` set in your minion config, because that would be the only time we use threading in 2016.11 from what I can remember.

Otherwise we always using the multiprocessing library.

https://github.com/saltstack/salt/blob/v2016.11.7/salt/minion.py#L1349

**Comment by gtmanfred** [comment]
I have never seen it @saltstack/team-core has anyone ever seen this error in salt before?

```
2018-04-26 22:05:07,015 [salt.utils.parsers][WARNING ][18889] Minion received a SIGTERM. Exiting.
2018-04-26 22:05:07,015 [salt.cli.daemons ][INFO    ][18889] Shutting down the Salt Minion
2018-04-26 22:05:07,517 [tornado.application][ERROR   ][18889] Exception in callback <functools.partial object at 0x7f094dbf8e10>
Traceback (most recent call last):
  File "/root/.pex/install/tornado-4.5.1-cp27-cp27mu-linux_x86_64.whl.fb67a9263e015c45296bb7103c9afdb612cd69fa/tornado-4.5.1-cp27-cp27mu-linux_x86_64.whl/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/root/.pex/install/tornado-4.5.1-cp27-cp27mu-linux_x86_64.whl.fb67a9263e015c45296bb7103c9afdb612cd69fa/tornado-4.5.1-cp27-cp27mu-linux_x86_64.whl/tornado/stack_context.py", line 279, in null_wrapper
    _state.contexts = current_state
```

Thanks,
Daniel
