### ISSUE TITLE
Unhelpful salt.exceptions.SaltInvocationError: A valid directory was not specified

### ISSUE THREAD

**Issue by bdrung** [saltstack/salt#47707]
### Description of Issue/Question

The example sls contains:
```
{% set DEVICE = "md302" %}
{% set SLAVE_DEVICES = salt['file.readdir']("/sys/block/" ~ DEVICE ~ "/slaves/") %}
```

When the md device is not assembled, the path `/sys/block/md302/slaves` does not exists and a salt highstate will fail with following totally unhelpful error message:

```
[CRITICAL] Rendering SLS 'example' failed: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 421, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 36, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 34, in <module>
  File "/usr/lib/python3/dist-packages/salt/modules/file.py", line 3317, in readdir
    raise SaltInvocationError('A valid directory was not specified.')
salt.exceptions.SaltInvocationError: A valid directory was not specified.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 167, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 442, in render_jinja_tmpl
    line, out = _get_jinja_error(trace, context=decoded_context)
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 249, in _get_jinja_error
    line = _get_jinja_error_line(trace)
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 232, in _get_jinja_error_line
    return _get_jinja_error_slug(tb_data)[1]
TypeError: 'NoneType' object is not subscriptable
```

This error message does not help to identify the issue. SaltInvocationError exception should at least contain the path that is not valid.

### Steps to Reproduce Issue

Create a example sls with the above snippet. Ensure that the referenced path is not present. Then run the state.

### Versions Report

```
Salt Version:
           Salt: 2017.7.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.4.2 (default, Oct  8 2014, 10:45:20)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.10
         locale: UTF-8
        machine: x86_64
        release: 4.4.62-1-storage
         system: Linux
        version: debian 8.10
```

**Comment by Ch3LL** [comment]
agreed this could use some improvement. Want to take a stab at a PR? Should just be in salt/modules/file.py to add more details to the error.

**Comment by bdrung** [comment]
Two fixes are needed:

1. salt/modules/file.py should add more details to the error
2. The second exception (TypeError: 'NoneType' object is not subscriptable) should be correctly handled

A PR for point one is simple.

**Comment by bdrung** [comment]
Issue is still present.
