### ISSUE TITLE
Looping through multiple pillar levels error

### ISSUE THREAD

**Issue by ndubc** [saltstack/salt#47756]
### Description of Issue/Question
I'm running my setup minion less to test.

I'm attempting to loop through a multi level dictionary and not exactly sure how to get the concepts down packed to drill down.

Every attempt has landed me with this error.
```
#salt-call state.show_sls directory
[ERROR   ] Rendering exception occurred
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 169, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 390, in render_jinja_tmpl
    buf=tmplstr)
SaltRenderError: Jinja variable 'unicode object' has no attribute 'items'
[CRITICAL] Rendering SLS 'base:directory' failed: Jinja variable 'unicode object' has no attribute 'items'
local:
    - Rendering SLS 'base:directory' failed: Jinja variable 'unicode object' has no attribute 'items'
```

Any and all help is appreciated.

### Setup

Pillar file
```
active:
  directory:
    id1:
      path: /abc-staging/interface
      owner: root
      group: root
      mode: 755
    id2:
      path: /defg-staging/analytical-storage
      owner: root
      group: root
      mode: 770
```
### Steps to Reproduce Issue

Sample directory/init.sls
```
{% for directory, ids in salt['pillar.get']('active', {}).iteritems() %}
  {% for id, args in ids.iteritems() %}

{{ id }}:
  file.directory:
    - user: root
    - name: {{ id }}:{{ args['path'] }} 
    - group: root
    - mode: 700

  {% endfor %}
{% endfor %}
```
### Versions Report
```
# salt-call --versions-report
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Feb 20 2018, 09:19:12)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: redhat 7.5 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.2.3.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.5 Maipo
```

**Comment by gtmanfred** [comment]
I am unable to replicate this.

```
[root@3bc37f834fd2 salt]# tail -c +0 /srv/*/*.sls
==> /srv/pillar/test.sls <==
active:
  directory:
    id1:
      path: /abc-staging/interface
      owner: root
      group: root
      mode: 755
    id2:
      path: /defg-staging/analytical-storage
      owner: root
      group: root
      mode: 770

==> /srv/pillar/top.sls <==
base:
  '*':
    - test

==> /srv/salt/directory.sls <==
{% for directory, ids in salt['pillar.get']('active', {}).iteritems() %}
  {% for id, args in ids.iteritems() %}

{{ id }}:
  file.directory:
    - user: root
    - name: {{ id }}:{{ args['path'] }}
    - group: root
    - mode: 700

  {% endfor %}
{% endfor %}
[root@3bc37f834fd2 salt]# salt-call --local slsutil.renderer salt://directory.sls default_renderer='jinja'
local:



    id1:
      file.directory:
        - user: root
        - name: id1:/abc-staging/interface
        - group: root
        - mode: 700



    id2:
      file.directory:
        - user: root
        - name: id2:/defg-staging/analytical-storage
        - group: root
        - mode: 700
```

This is rendering fine for me.

Also, it looks like your error is something else, because it says unicode does not have `.items` but you are only referencing `iteritems` in your example.

Can you provide some more information?

Thanks,
Daniel

**Comment by ndubc** [comment]
Thanks for looking into this. I get the same error whether I use 'items' or 'iteritems' . See below. I'll keep troubleshooting on my one. Much appreciated. 

`
local:
    - Rendering SLS 'base:directory' failed: Jinja variable 'unicode object' has no attribute 'items'
`

`local:
    - Rendering SLS 'base:directory' failed: Jinja variable 'unicode object' has no attribute 'iteritems'
`

**Comment by gtmanfred** [comment]
you could use the `log` module so that the minion prints out a log message with the data that is in the variable.

```
{%- do salt.log.critical('MyVar %s'|format(myvar))
```

And that might help track down what is actually happening in your environment.

Daniel

**Comment by noelmcloughlin** [comment]
I think I replicated in #48504
