### ISSUE TITLE
[ERROR ] There was a profile error: 'unicode' object has no attribute 'keys'

### ISSUE THREAD

**Issue by blefeuvr** [saltstack/salt#47767]
Hello, 
I am trying to build a vm with salt-cloud and vmware.

Here is my cloud.conf file :
```
first_one:
  provider: vmware_lab
  image: ubuntu64Guest  
  datastore: HDD
  resourcepool: Resources
  folder: vm
  minion: 
    master: saltmaster
  devices:
    ide:
      IDE 2
    cd:
      CD/DVD drive 1:
        device_type: client_device
        mode: atapi
        controller: IDE 2
```
Command is :
```
salt-cloud -p first_one VM-TON
```
Error is :
```
[ERROR   ] There was a profile error: 'unicode' object has no attribute 'keys'
```
I took a glance at the sources and devices['ide'] seems to be 'unicode' where it should have been 'dict'

See '-l debug' logs
```[DEBUG   ] Reading configuration from /etc/salt/cloud
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Changed git to gitfs in master opts' fileserver_backend list
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: ec-vm-cr-lab-salt
[DEBUG   ] Missing configuration file: /etc/salt/cloud.providers
[DEBUG   ] Including configuration from '/etc/salt/cloud.providers.d/vmware.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers.d/vmware.conf
[DEBUG   ] Missing configuration file: /etc/salt/cloud.profiles
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/cloud.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/cloud.conf
[DEBUG   ] Configuration file path: /etc/salt/cloud
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] salt-cloud starting
[DEBUG   ] Marking 'base64_encode' as a jinja filter
[DEBUG   ] Marking 'base64_decode' as a jinja filter
[DEBUG   ] Marking 'md5' as a jinja filter
[DEBUG   ] Marking 'sha256' as a jinja filter
[DEBUG   ] Marking 'sha512' as a jinja filter
[DEBUG   ] Marking 'hmac' as a jinja filter
[DEBUG   ] Marking 'random_hash' as a jinja filter
[DEBUG   ] Marking 'rand_str' as a jinja filter
[DEBUG   ] Marking 'file_hashsum' as a jinja filter
[DEBUG   ] Marking 'http_query' as a jinja filter
[DEBUG   ] Marking 'yaml_dquote' as a jinja filter
[DEBUG   ] Marking 'yaml_squote' as a jinja filter
[DEBUG   ] Marking 'yaml_encode' as a jinja filter
[DEBUG   ] Marking 'raise' as a jinja global
[DEBUG   ] Marking 'match' as a jinja test
[DEBUG   ] Marking 'equalto' as a jinja test
[DEBUG   ] Marking 'skip' as a jinja filter
[DEBUG   ] Marking 'sequence' as a jinja filter
[DEBUG   ] Marking 'to_bool' as a jinja filter
[DEBUG   ] Marking 'quote' as a jinja filter
[DEBUG   ] Marking 'regex_escape' as a jinja filter
[DEBUG   ] Marking 'regex_search' as a jinja filter
[DEBUG   ] Marking 'regex_match' as a jinja filter
[DEBUG   ] Marking 'regex_replace' as a jinja filter
[DEBUG   ] Marking 'uuid' as a jinja filter
[DEBUG   ] Marking 'unique' as a jinja filter
[DEBUG   ] Marking 'min' as a jinja filter
[DEBUG   ] Marking 'max' as a jinja filter
[DEBUG   ] Marking 'avg' as a jinja filter
[DEBUG   ] Marking 'union' as a jinja filter
[DEBUG   ] Marking 'intersect' as a jinja filter
[DEBUG   ] Marking 'difference' as a jinja filter
[DEBUG   ] Marking 'symmetric_difference' as a jinja filter
[DEBUG   ] Could not LazyLoad parallels.avail_sizes: 'parallels' __virtual__ returned False
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad vmware.optimize_providers: 'vmware.optimize_providers' is not available.
[DEBUG   ] The 'vmware' cloud driver is unable to be optimized.
[DEBUG   ] Could not LazyLoad parallels.avail_sizes: 'parallels' __virtual__ returned False
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Generating minion keys for 'VM-TON'
[DEBUG   ] LazyLoaded cloud.fire_event
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event: tag = salt/cloud/VM-TON/creating; data = {u'profile': u'first_one', u'_stamp': '2018-05-22T11:39:19.069910', u'name': u'VM-TON', u'driver': u'vmware', u'provider': u'vcenter_lab:vmware', u'event': u'starting create'}
[ERROR   ] There was a profile error: 'unicode' object has no attribute 'keys'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 281, in run
    self.config.get('names')
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1454, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1284, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/vmware.py", line 2651, in create
    specs = _manage_devices(devices, vm=object_ref, container_ref=container_ref, new_vm_name=vm_name)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/vmware.py", line 822, in _manage_devices
    ide_controllers_to_create = list(set(devices['ide'].keys()) - set(existing_ide_controllers_label))
AttributeError: 'unicode' object has no attribute 'keys'
```
### Versions
```
Salt Version:
           Salt: 2018.3.0
```

**Comment by gtmanfred** [comment]
Try setting your ide like this.

```
    ide:
      IDE 2:
```

or 

```
    ide:
      IDE 2: {}
```

It looks like you should be able to pass configuration stuff to the IDE, but the documentation does not list it, so yaml renders it as a string.

Daniel
