### ISSUE TITLE
mtime argument of file.touch does not work

### ISSUE THREAD

**Issue by gurubert** [saltstack/salt#47886]
### Description of Issue/Question

I am trying to use file.touch with the mtime option and it fails on Salt 2018.3.0

### Steps to Reproduce Issue
    # salt host file.touch '/tmp/testfile' mtime='1'
    host:
        The minion function caused an exception: Traceback (most recent call last):
          File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1600, in _thread_return
            return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
          File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 12, in execute
            return func(*args, **kwargs)
          File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 3083, in touch
            if mtime and mtime.isdigit():
        AttributeError: 'int' object has no attribute 'isdigit'
    # salt host file.touch '/tmp/testfile' mtime=1
    host:
        The minion function caused an exception: Traceback (most recent call last):
          File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1600, in _thread_return
            return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
          File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 12, in execute
            return func(*args, **kwargs)
          File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 3083, in touch
            if mtime and mtime.isdigit():
        AttributeError: 'int' object has no attribute 'isdigit'

### Versions Report
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.13.0-41-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by gurubert** [comment]
I just saw in the develop branch that the touch() method in the file module has already been rewritten and the code there now reads:

    try:
        atime = int(atime)
    except:
        atime = None
    try:
        mtime = int(mtime)
    except:
        mtime = None

It seems that I was the original author ;) of commit 9f016da563155d939d89607c5c01665d0931f001 but unfortunately it did not make it into Salt 2018.3
