### ISSUE TITLE
After upgrading to 2018.3 salt-master service causes excessive load to master servers

### ISSUE THREAD

**Issue by alogoc** [saltstack/salt#47948]
### Description of Issue/Question
Salt-master is often unresponsive and unable to contact minions after upgrading to version 2018.3

### Setup
2 identical salt-masters upgraded both to 2018.3, servers became almost unresponsive after excess load being generated by the salt-master service 
```
00:44:01 up  2:39,  3 users,  load average: 315.97, 294.88, 196.65
``` 
Salt-minions fail to connect to master 
```
2018-06-04 02:17:58,955 [salt.utils.parsers][WARNING ][24541] Syndic received a SIGTERM. Exiting.
2018-06-04 02:18:16,735 [salt.minion      :2942][CRITICAL][28081] Unexpected error while connecting to salt-master
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 2914, in _connect_syndic
    yield syndic.connect_master(failed=failed)
GeneratorExit
```

### Steps to Reproduce Issue
Seems that several modules are missing, can that be the cause even though those grains haven't been called?

Output of /var/log/master:
```
2018-06-04 02:25:12,682 [salt.loader      ][CRITICAL][5009] Failed to load grains defined in grain file mdadm.mdadm in function <function mdadm at 0x34975f0>, error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 726, in grains
    if force_refresh:  # if we refresh, lets reload grain modules
  File "/usr/lib/python2.7/site-packages/salt/grains/mdadm.py", line 22, in mdadm
    with salt.utils.files.fopen('/proc/mdstat', 'r') as mdstat:
AttributeError: 'module' object has no attribute 'fopen'
2018-06-04 02:25:12,717 [salt.loader      ][CRITICAL][5009] Failed to load grains defined in grain file disks.disks in function <function disks at 0x422b140>, error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 726, in grains
    if force_refresh:  # if we refresh, lets reload grain modules
  File "/usr/lib/python2.7/site-packages/salt/grains/disks.py", line 36, in disks
    return _linux_disks()
  File "/usr/lib/python2.7/site-packages/salt/grains/disks.py", line 136, in _linux_disks
    with salt.utils.files.fopen(entry) as entry_fp:
AttributeError: 'module' object has no attribute 'fopen'
2018-06-04 02:25:12,718 [salt.loader      ][CRITICAL][5009] Failed to load grains defined in grain file zfs.zfs in function <function zfs at 0x422bf50>, error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 726, in grains
    if force_refresh:  # if we refresh, lets reload grain modules
  File "/usr/lib/python2.7/site-packages/salt/grains/zfs.py", line 114, in zfs
    grains = salt.utils.dictupdate.update(grains, _zfs_support(), merge_lists=True)
  File "/usr/lib/python2.7/site-packages/salt/grains/zfs.py", line 73, in _zfs_support
    modinfo = salt.utils.path.which('modinfo')
  File "/usr/lib/python2.7/site-packages/salt/utils/path.py", line 240, in which
    full_path = join(path, exe)
  File "/usr/lib/python2.7/site-packages/salt/utils/path.py", line 293, in join
    kwargs = salt.utils.args.clean_kwargs(**kwargs)```
```

```
### Versions Report
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.28.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Apr 11 2018, 07:36:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```

Any help/hints would be much appreciated :)

**Comment by gtmanfred** [comment]
Can you make sure you don't have any left over .pyc files from an older release?

Because there was some moving of the salt/utils/__init__.py functions into other utils module files.

Thanks,
Daniel

**Comment by alogoc** [comment]
Indeed I read about this on the release notes, I checked all the files under salt/utils but there are no old utils modules files.

The load average is getting better but it's still complaining about the fopen module.

Regards,
Georgios

**Comment by alogoc** [comment]
There is no salt-minion process, this is just the salt-master running only the salt-master service :)

**Comment by gtmanfred** [comment]
Sorry, hrm, yeah it wouldn't be the minion.

No, just restart the salt-master process.  they are just the compiled bytecode that python creates at the start.
