### ISSUE TITLE
Zookeeper module raises NoNodeError when getting non-existent node

### ISSUE THREAD

**Issue by onlyanegg** [saltstack/salt#47979]
### Description of Issue/Question
The Zookeeper execution module raises a NoNodeError when doing a get for a node that doesn't exist. This causes states which use this module in Jinja to fail. I think it would be better to catch this exception and return something reasonable (`None` maybe). 

I wrote a custom SDB module on top of the Zookeeper execution module, so one solution for me is to catch it in the SDB module, but I think it might be better to catch it within the execution module.

### Setup
Install Zookeeper

### Steps to Reproduce Issue
```
[root@minion salt]# salt-call zookeeper.get hello
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
NoNodeError:
Traceback (most recent call last):
  File "/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 400, in salt_call
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 212, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/zookeeper.py", line 305, in get
    ret, _ = conn.get(path)
  File "/usr/lib/python2.7/site-packages/kazoo/client.py", line 1042, in get
    return self.get_async(path, watch=watch).get()
  File "/usr/lib/python2.7/site-packages/kazoo/handlers/utils.py", line 79, in get
    raise self._exception
NoNodeError
Traceback (most recent call last):
  File "/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 400, in salt_call
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 212, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/zookeeper.py", line 305, in get
    ret, _ = conn.get(path)
  File "/usr/lib/python2.7/site-packages/kazoo/client.py", line 1042, in get
    return self.get_async(path, watch=watch).get()
  File "/usr/lib/python2.7/site-packages/kazoo/handlers/utils.py", line 79, in get
    raise self._exception
kazoo.exceptions.NoNodeError
```

### Versions Report
```
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.9
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.21.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

**Comment by gtmanfred** [comment]
Yes, it would be better to return false instead of the stack trace (but also log the stacktrace in the debug log)

Would you mind submitting a PR to fix this?

Thanks,
Daniel

**Comment by onlyanegg** [comment]
Sure, @gtmanfred. I'd be happy to. Thanks!

**Comment by gtmanfred** [comment]
Awesome!

When i initially wrote this module, i wrote it with a very limited knowledge of how zookeeper actually works, and just to fit one customers usecase for what they were asking for.
