### ISSUE TITLE
2018.3.1 - Py3 - Salt upgrade using pip3 fails

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#47974]
### Description of Issue/Question
Trying to upgrade from 2017.7.5 to 2018.3.1 using pip3 fails. 
It seems to upgrade fine but when trying to run commands it doesn't work.

The upgrade is working fine from 2018.3.0 to 2018.3.1 but fails when trying from 2017.7.5 to 2018.3.1.

I see this in the master log:
```
2018-06-05 16:21:43,788 [salt.master                                           :2025][ERROR   ][3486] Failed to allocate a jid. The requested returner 'local_cache' could not be loaded.
2018-06-05 16:21:43,789 [salt.transport.zeromq                                 :632 ][ERROR   ][3486] Some exception handling a payload from minion
Traceback (most recent call last):
  File "/root/salt/salt/transport/zeromq.py", line 628, in handle_message
    salt.transport.mixins.auth.AESReqServerMixin.post_fork(self, payload_handler, io_loop)
  File "/usr/lib64/python3.5/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/lib64/python3.5/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/lib64/python3.5/site-packages/tornado/gen.py", line 292, in wrapper
    result = func(*args, **kwargs)
  File "/usr/lib64/python3.5/types.py", line 243, in wrapped
    coro = func(*args, **kwargs)
  File "/root/salt/salt/master.py", line 896, in _handle_payload
    def destroy(self, signum=signal.SIGTERM):
  File "/root/salt/salt/master.py", line 910, in _handle_clear
    '''
  File "/root/salt/salt/master.py", line 1991, in publish
    log.error(
  File "/root/salt/salt/master.py", line 2049, in _prep_pub
    username = auth_check.get('username')
  File "/root/salt/salt/utils/event.py", line 731, in fire_event
    dump_data = self.serial.dumps(data, use_bin_type=True)
  File "/root/salt/salt/utils/__init__.py", line 3219, in to_bytes
TypeError: expected bytes, bytearray, or str
2018-06-05 16:21:43,796 [tornado.general                                       :462 ][ERROR   ][3486] Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/zmq/sugar/socket.py", line 426, in send_multipart
    memoryview(msg)
TypeError: memoryview: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 454, in _handle_events
    self._handle_send()
  File "/usr/lib64/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 493, in _handle_send
    status = self.socket.send_multipart(msg, **kwargs)
  File "/usr/lib64/python3.5/site-packages/zmq/sugar/socket.py", line 433, in send_multipart
    i, rmsg,
TypeError: Frame 0 ('Some exception handling minion ...) does not support the buffer interface.
2018-06-05 16:21:43,797 [tornado.application                                   :638 ][ERROR   ][3486] Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7f10cfc99a60>)
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/zmq/sugar/socket.py", line 426, in send_multipart
    memoryview(msg)
TypeError: memoryview: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/usr/lib64/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib64/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 536, in <lambda>
    self.io_loop.add_callback(lambda : self._handle_events(self.socket, 0))
  File "/usr/lib64/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 454, in _handle_events
    self._handle_send()
  File "/usr/lib64/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 493, in _handle_send
    status = self.socket.send_multipart(msg, **kwargs)
  File "/usr/lib64/python3.5/site-packages/zmq/sugar/socket.py", line 433, in send_multipart
    i, rmsg,
TypeError: Frame 0 ('Some exception handling minion ...) does not support the buffer interface.
2018-06-05 16:22:03,813 [py.warnings      :160 ][WARNING ][5067] /root/salt/salt/output/__pycache__/nested.cpython-35.py:46: DeprecationWarning: Use of 'salt.utils.get_colors' detected. This function has been moved to 'salt.utils.color.get_colors' as of Salt 2018.3.0. This warning will be removed in Salt Neon.

2018-06-05 16:22:19,270 [salt.loader                                           :753 ][CRITICAL][3482] Failed to load grains defined in grain file zfs.zfs in function <function zfs at 0x7f10cfd4af28>, error:
Traceback (most recent call last):
  File "/root/salt/salt/loader.py", line 744, in grains
    if key.startswith('core.') or key == '_errors':
  File "/root/salt/salt/grains/zfs.py", line 78, in zfs
    grains['zfs_support'] = __utils__['zfs.is_supported']()
  File "/root/salt/salt/utils/zfs.py", line 296, in is_supported
    elif salt.utils.platform.is_linux() and salt.utils.path.which('zfs-fuse'):
AttributeError: module 'salt.utils.path' has no attribute 'which'
```

### Setup
Pip3 install 2017.7.5 then upgrade to 2018.3.1 using pip3.

### Versions Report
```
Salt Version:
           Salt: 2018.3.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (default, Jan 17 2017, 14:34:36)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.6
 
System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.21.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

**Comment by frogunder** [comment]
Closing this, its working correctly for me now, must have been something in my environment.
