### ISSUE TITLE
salt.states.mount & salt.modules.mount not working on FreeBSD minion

### ISSUE THREAD

**Issue by hackacad** [saltstack/salt#47994]
### Description of Issue/Question
Cannot mount shares on FreeBSD via module or state (/proc/self/mounts, /proc/self/mountinfo missing). Mounting manually works fine with the giving opts.

### Setup
mount.sls:

/mnt/dummy:
  mount.mounted:
    - device: nfserver:/mnt/share
    - fstype: nfs
    - mkmnt: True
    - persist: True
    - mount: True
    - opts: nsuid,noatime,tcp,rw

### Steps to Reproduce Issue

salt 'minion' state.sls mount 

host:
----------
          ID: /mnt/dummy
    Function: mount.mounted
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/local/lib/python3.6/site-packages/salt/modules/mount.py", line 242, in active
                  _active_mountinfo(ret)
                File "/usr/local/lib/python3.6/site-packages/salt/modules/mount.py", line 62, in _active_mountinfo
                  raise CommandExecutionError(msg.format(filename))
              salt.exceptions.CommandExecutionError: File not readable /proc/self/mountinfo

              During handling of the above exception, another exception occurred:

              Traceback (most recent call last):
                File "/usr/local/lib/python3.6/site-packages/salt/state.py", line 1878, in call
                  **cdata['kwargs'])
                File "/usr/local/lib/python3.6/site-packages/salt/loader.py", line 1823, in wrapper
                  return f(*args, **kwargs)
                File "/usr/local/lib/python3.6/site-packages/salt/states/mount.py", line 223, in mounted
                  active = __salt__['mount.active'](extended=True)
                File "/usr/local/lib/python3.6/site-packages/salt/modules/mount.py", line 244, in active
                  _active_mounts(ret)
                File "/usr/local/lib/python3.6/site-packages/salt/modules/mount.py", line 106, in _active_mounts
                  raise CommandExecutionError(msg.format(filename))
              salt.exceptions.CommandExecutionError: File not readable /proc/self/mounts

### Versions Report
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.27.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.27.0
         Python: 3.6.5 (default, May 10 2018, 01:16:34)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: UTF-8
        machine: amd64
        release: 11.1-RELEASE-p10
         system: FreeBSD
        version: Not Installed

###
Same problem with the mount module   
$ salt minion mount.active
ERROR: File not readable /proc/self/mounts

Does anyone have an idea how to get around this?

**Comment by garethgreenaway** [comment]
@hackacad Thanks for the report. Sounds like the OS detection in the mount module isn't working correctly, the `active` function should be running the `_active_mounts_freebsd` function.  Can you check what is being returned in the `os` grain on that system?

**Comment by hackacad** [comment]
Yes! OS detection seems to be broken. On FreeBSD 11 with salt 2018 os returns "none".
That helps me understand a couple of similar problems and side effects. 

minion log:
----------
 File "/usr/local/lib/python3.6/site-packages/salt/utils/versions.py", line 138, in warn_until
    salt_version=_version_.formatted_version
RuntimeError: The warning triggered on filename '/usr/local/lib/python3.6/site-packages/salt/loader.py', line number 1768, is supposed to be shown until version 2014.1.0 (Hydrogen) is released. Current version is now 2018.3.0 (Oxygen). Please remove the warning.
2018-06-06 13:07:49,608 [salt.loader                                                                                         :1729][ERROR   ][3980] Exception raised when processing __virtual__ function for salt.loader.ca.sven.bike.int.module.xbpspkg.opt-1. Module will not be loaded: 'in <string>' requires string as left operand, not NoneType
2018-06-06 13:07:49,608 [salt.loader                                                                                         :1745][WARNING ][3980] salt.loader.hostname.int.module.xbpspkg.opt-1.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'opt-1', please fix this.

**Comment by hackacad** [comment]
It's related to the existing FreeBSD bugfix as well.
Applying the patch:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=227836  worked. 
related to: #47006

Thanks @cedwards
