### ISSUE TITLE
Custom ext_pillar __opts__ is not defined

### ISSUE THREAD

**Issue by kiemlicz** [saltstack/salt#48010]
### Description of Issue/Question
I was trying to write very simple `ext_pillar` that pretty much just delegates the call to `git_pillar.ext_pillar` (dynamically creates the repository configuration that gets delegated)

I'm facing the issue that `git_pillar.ext_pillar` cannot find `__opts__`

Why is that and how to fix this?
Inside of the custom pillar I can access `__opts__` but not after calling
` git_pillar.ext_pillar(...)`

### Setup
Latest salt installation (2018.3)
Following custom ext_pillar configured.
`/srv/extensions/pillar/privgit.py`:
```
import collections
import copy
import logging
import os
import re

import salt.ext.six as six
import salt.pillar.git_pillar as git_pillar
import salt.utils
import salt.utils.dictupdate
import salt.utils.gitfs
from salt.exceptions import SaltConfigurationError
from salt.utils.gitfs import GitPillar

...

def ext_pillar(minion_id, pillar, *args, **kwargs):
          # pseudo code here
          repo = [{'branch git@bitbucket.org:user/cfg.git': [{'env': u'custom'}, {'root': u'pillar'}, {'privkey': u'/var/cache/salt/master/privgit/some.host/main/priv.key'}, {'pubkey': u'/var/cache/salt/master/privgit/some.host/main/pub.key'}]}]
          ret = git_pillar.ext_pillar(minion_id, {}, repo)
```

### Steps to Reproduce Issue
Running such pillar (e.g. via `pillar.items`) yields:
```
Traceback (most recent call last):
  File "/srv/salt_ext/pillar/privgit.py", line 130, in ext_pillar
    ret = git_pillar.ext_pillar(minion_id, {}, repo)
  File "/usr/lib/python2.7/dist-packages/salt/pillar/git_pillar.py", line 381, in ext_pillar
    opts = copy.deepcopy(__opts__)
NameError: global name '__opts__' is not defined
```

### Versions Report
```
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: 2.5.3
      docker-py: 1.10.6
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.27.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.27.1
         Python: 2.7.13 (default, Nov 24 2017, 17:33:09)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.4
         locale: UTF-8
        machine: x86_64
        release: 4.11.8-no5kill
         system: Linux
        version: debian 9.4
```

**Comment by gtmanfred** [comment]
You cannot import the files directly, you have to load them through the loader.

```
import salt.pillar.git_pillar as git_pillar
```

Instead of that, load them through the loader.

https://docs.saltstack.com/en/latest/ref/clients/#salt-s-loader-interface

use

```
import salt.loader
...
pillar = salt.loader.pillar(__opts__, __salt__)
ret = pillar['git_pillar.ext_pillar'](minion_id, {}, repo)
```

**Comment by kiemlicz** [comment]
Thank you!

**Comment by gtmanfred** [comment]
:+1: no problem!

**Comment by kiemlicz** [comment]
To be honest: it worked... at least I think it did... slightly differently written:
```
        repo = {'{} {}'.format(privgit_branch, privgit_url): [
            {"env": privgit_env},
            {"root": privgit_root},
            {"privkey": privgit_privkey},
            {"pubkey": privgit_pubkey}]}

        log.debug("generated private git configuration: {}".format(repo))

        try:
            loaded_pillar = salt.loader.pillars(__opts__, __salt__)
            ret = loaded_pillar['git'](minion_id, pillar, repo)
        except Exception as e:
            log.exception(
                "Fatal error in privgit, for: {} {}, repository will be omitted".format(privgit_branch, privgit_url))
```
But now (2018.3.1) it does not...
The same code causes to initialize git but doesn't initialize remotes. Thus in logs I see:
```
2018-06-16 12:32:53,505 [salt.utils.gitfs                                               :1573][ERROR   ][12287] Failed to checkout some_branch from git_pillar remote 'some_branch git@bitbucket.org:username_bb/cfg.git': remote ref does not exist
2018-06-16 12:32:53,505 [salt.utils.gitfs                                               :2664][DEBUG   ][12287] Created gitfs object with uninitialized remotes
2018-06-16 12:32:53,508 [salt.utils.lazy                                                :100 ][DEBUG   ][12287] LazyLoaded localfs.init_kwargs
```
In the `/var/cache/salt/master/git_pillar/...` I can find empty repostory without branch checkout
How do I fix this? How to pass the `init_remotes` ?
