### ISSUE TITLE
vault runner is broken in 2018.3.0

### ISSUE THREAD

**Issue by zerthimon** [saltstack/salt#48018]
### Description of Issue/Question
```
root@infra02:/etc/salt/master.d# salt-call vault.list_secrets saltstack/envs
[ERROR   ] Failed to get token from master! Response is not a dict: Exception occurred in runner vault.generate_token: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 387, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/runners/vault.py", line 43, in generate_token
    'Token generation request for %s (impersonated by master: %s)'.
AttributeError: 'unicode' object has no attribute 'minion_id'

[ERROR   ] Failed to list secrets! CommandExecutionError: Exception occurred in runner vault.generate_token: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 387, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/runners/vault.py", line 43, in generate_token
    'Token generation request for %s (impersonated by master: %s)'.
AttributeError: 'unicode' object has no attribute 'minion_id'

Error running 'vault.list_secrets': Exception occurred in runner vault.generate_token: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 387, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/runners/vault.py", line 43, in generate_token
    'Token generation request for %s (impersonated by master: %s)'.
AttributeError: 'unicode' object has no attribute 'minion_id'
```
Should be (example):
```
local:
    ----------
    keys:
        - prod/
        - stage/
        - test/
```
### Setup
vault.conf
```
vault:
  url: https://vault.xxx.xxx.com:8200
  auth:
    method: token
    token: xxx-xxx-xxx-xxx-xxx
  policies:
    - saltstack/envs/base
    - saltstack/envs/{grains[ec2_tags][Environment]}
    - saltstack/minions/{minion}
```

peer_run.conf
```
peer_run:
  .*:
    - vault.generate_token
```
### Steps to Reproduce Issue
`salt-call vault.list_secrets saltstack/envs`

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-1060-aws
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by zerthimon** [comment]
argh, sorry, duplicate https://github.com/saltstack/salt/issues/46864

closing
