### ISSUE TITLE
fresh install result on mac = ValueError: invalid literal for float(): 1024,00

### ISSUE THREAD

**Issue by sugizo** [saltstack/salt#48078]
### Setup
no config, just started from scratch new python environment in conda

### Steps to Reproduce Issue
```
$ uname
Darwin
$ launchctl limit maxfiles
	maxfiles    8192           10240
$ python -V
Python 2.7.15 :: Anaconda, Inc.
$ pip install salt
$ salt-master --log-level=all
Traceback (most recent call last):
  File "/Users/MacBookPro/miniconda3/envs/python2_test/bin/salt-master", line 11, in <module>
    sys.exit(salt_master())
  File "/Users/MacBookPro/miniconda3/envs/python2_test/lib/python2.7/site-packages/salt/scripts.py", line 95, in salt_master
    import salt.cli.daemons
  File "/Users/MacBookPro/miniconda3/envs/python2_test/lib/python2.7/site-packages/salt/cli/daemons.py", line 48, in <module>
    import salt.utils.parsers
  File "/Users/MacBookPro/miniconda3/envs/python2_test/lib/python2.7/site-packages/salt/utils/parsers.py", line 27, in <module>
    import salt.config as config
  File "/Users/MacBookPro/miniconda3/envs/python2_test/lib/python2.7/site-packages/salt/config/__init__.py", line 98, in <module>
    _DFLT_IPC_WBUFFER = _gather_buffer_space() * .5
  File "/Users/MacBookPro/miniconda3/envs/python2_test/lib/python2.7/site-packages/salt/config/__init__.py", line 91, in _gather_buffer_space
    grains = salt.grains.core._memdata(os_data)
  File "/Users/MacBookPro/miniconda3/envs/python2_test/lib/python2.7/site-packages/salt/grains/core.py", line 511, in _memdata
    grains.update(_osx_memdata())
  File "/Users/MacBookPro/miniconda3/envs/python2_test/lib/python2.7/site-packages/salt/grains/core.py", line 433, in _osx_memdata
    swap_total = float(swap_total[:-1]) * _power
ValueError: invalid literal for float(): 1024,00
```

trying salt --versions-report and salt --help also thrown the same error : 
ValueError: invalid literal for float(): 1024,00

### Versions Report
can not generate salt --version-report, but seen in pip install salt = salt-2018.3.0

any idea ? thx

**Comment by Ch3LL** [comment]
running the salt master on macosx is not supported as documented here: https://docs.saltstack.com/en/2017.7/topics/installation/osx.html#salt-master-customizations

but i bet you will run into this on minion as well. can you run the minion process and do you run into the same thing? And which macosx version are you using?

**Comment by sugizo** [comment]
macos siera version 10.12.6
started from fresh, no minions created yet

**Comment by Ch3LL** [comment]
can you just try starting hte minion process on the same minion with `salt-minion -ldebug` and see if it fails or not? 

As stated previously the master isn't supported on macosx

**Comment by sugizo** [comment]
```
$ salt --version-report
Traceback (most recent call last):
  File "/Users/sugizo/miniconda3/envs/python2_test/bin/salt", line 11, in <module>
    sys.exit(salt_main())
  File "/Users/sugizo/miniconda3/envs/python2_test/lib/python2.7/site-packages/salt/scripts.py", line 480, in salt_main
    import salt.cli.salt
  File "/Users/sugizo/miniconda3/envs/python2_test/lib/python2.7/site-packages/salt/cli/salt.py", line 10, in <module>
    import salt.utils.job
  File "/Users/sugizo/miniconda3/envs/python2_test/lib/python2.7/site-packages/salt/utils/job.py", line 11, in <module>
    import salt.minion
  File "/Users/sugizo/miniconda3/envs/python2_test/lib/python2.7/site-packages/salt/minion.py", line 75, in <module>
    import salt.client
  File "/Users/sugizo/miniconda3/envs/python2_test/lib/python2.7/site-packages/salt/client/__init__.py", line 30, in <module>
    import salt.config
  File "/Users/sugizo/miniconda3/envs/python2_test/lib/python2.7/site-packages/salt/config/__init__.py", line 98, in <module>
    _DFLT_IPC_WBUFFER = _gather_buffer_space() * .5
  File "/Users/sugizo/miniconda3/envs/python2_test/lib/python2.7/site-packages/salt/config/__init__.py", line 91, in _gather_buffer_space
    grains = salt.grains.core._memdata(os_data)
  File "/Users/sugizo/miniconda3/envs/python2_test/lib/python2.7/site-packages/salt/grains/core.py", line 510, in _memdata
    grains.update(_osx_memdata())
  File "/Users/sugizo/miniconda3/envs/python2_test/lib/python2.7/site-packages/salt/grains/core.py", line 432, in _osx_memdata
    swap_total = float(swap_total[:-1]) * _power
ValueError: invalid literal for float(): 1024,00
$ salt-minion -ldebug
Traceback (most recent call last):
  File "/Users/sugizo/miniconda3/envs/python2_test/bin/salt-minion", line 11, in <module>
    sys.exit(salt_minion())
  File "/Users/sugizo/miniconda3/envs/python2_test/lib/python2.7/site-packages/salt/scripts.py", line 168, in salt_minion
    import salt.cli.daemons
  File "/Users/sugizo/miniconda3/envs/python2_test/lib/python2.7/site-packages/salt/cli/daemons.py", line 48, in <module>
    import salt.utils.parsers
  File "/Users/sugizo/miniconda3/envs/python2_test/lib/python2.7/site-packages/salt/utils/parsers.py", line 27, in <module>
    import salt.config as config
  File "/Users/sugizo/miniconda3/envs/python2_test/lib/python2.7/site-packages/salt/config/__init__.py", line 98, in <module>
    _DFLT_IPC_WBUFFER = _gather_buffer_space() * .5
  File "/Users/sugizo/miniconda3/envs/python2_test/lib/python2.7/site-packages/salt/config/__init__.py", line 91, in _gather_buffer_space
    grains = salt.grains.core._memdata(os_data)
  File "/Users/sugizo/miniconda3/envs/python2_test/lib/python2.7/site-packages/salt/grains/core.py", line 510, in _memdata
    grains.update(_osx_memdata())
  File "/Users/sugizo/miniconda3/envs/python2_test/lib/python2.7/site-packages/salt/grains/core.py", line 432, in _osx_memdata
    swap_total = float(swap_total[:-1]) * _power
ValueError: invalid literal for float(): 1024,00
```

same error for both salt --version-report and salt-minion -ldebug, think the problem is not about the salt-master

**Comment by Ch3LL** [comment]
thanks for verifying. Im not able to replicate this because my swap_total is not 1024. Seems odd that your return is 1024,00

can you paste the contents of: `sysctl -n vm.swapusage`? That way I can see how we should properly be handling this type of return since I cannot replicate it. thanks

**Comment by sugizo** [comment]
```
$ sysctl -n vm.swapusage
total = 1024,00M  used = 160,75M  free = 863,25M  (encrypted)
```
seems problem with my os or what?

**Comment by Ch3LL** [comment]
can you try the fix in https://github.com/saltstack/salt/pull/48304

**Comment by Ch3LL** [comment]
actually looks like i might need to fix it, one sec. but once i refine the fix you would need to just edit the file with the patch. you can use `git apply <git-diff>` if you grab the diff from the PR. but let me dive into a better fix before that :)

**Comment by sugizo** [comment]
seen the comment in https://github.com/saltstack/salt/pull/48304
fyi
```
$ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```
no worries, pls let me know how to test it, btw never tried to install salt from github, might i know how to do it?
```
$ git clone https://github.com/saltstack/salt
$ cd salt
$ python setup.py
```
is it correct?

**Comment by Ch3LL** [comment]
that seems odd that your locale is using `en_US.UTF-8`  and you are still getting a comma decimal separator. `en_us` should be using a point decimal seperator.

Can you type the following commands in a python interpreter (make sure its the same python version used by salt):

```
>>> import locale
>>> locale.getlocale()
('en_US', 'UTF-8')
>>> locale.atof('127,00')
```

and paste the results here.

**Comment by sugizo** [comment]
```
$ python 
Python 3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> locale.getlocale()
('en_US', 'UTF-8')
>>> locale.atof('127,00')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/MacBookPro/miniconda3/lib/python3.6/locale.py", line 321, in atof
    return func(delocalize(string))
ValueError: could not convert string to float: '127,00'
```

```
$ source activate python2_prod
$ python
Python 2.7.15 |Anaconda, Inc.| (default, May  1 2018, 18:37:05) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> locale.getlocale()
(None, None)
>>> locale.atof('127,00')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/MacBookPro/miniconda3/envs/python2_prod/lib/python2.7/locale.py", line 318, in atof
    return func(string)
ValueError: invalid literal for float(): 127,00
```
tested with miniconda (python 2 and 3 env)

**Comment by DmitryKuzmenko** [comment]
@sugizo 
Just an assumption: couldn't it be a number separator customized in "language and region" -> "advanced" -> "general"? I just have no MAC to check this.

**Comment by DmitryKuzmenko** [comment]
@Ch3LL as python locale module documentation says the module is just an interface to the POSIX locale database. So to properly use it it has to be initialized after loading.
@sugizo could you try this?
```python
import locale
locale.setlocale(LC_ALL, '')
locale.atof('123,45')
```

**Comment by sugizo** [comment]
```
$ python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> locale.setlocale(LC_ALL, '')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'LC_ALL' is not defined
>>> locale.atof('123,45')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/MacBookPro/miniconda3/lib/python3.6/locale.py", line 321, in atof
    return func(delocalize(string))
ValueError: could not convert string to float: '123,45'
```

```
$ source activate python2_prod
$ python
Python 2.7.15 |Anaconda, Inc.| (default, May  1 2018, 18:37:05) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> locale.setlocale(LC_ALL, '')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'LC_ALL' is not defined
>>> locale.atof('123,45')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/MacBookPro/miniconda3/envs/python2_prod/lib/python2.7/locale.py", line 318, in atof
    return func(string)
ValueError: invalid literal for float(): 123,45
```

**Comment by DmitryKuzmenko** [comment]
@sugizo sure, thanks for fixing that. So `locale.atof` works good.
@Ch3LL what about using that way in your PR?

**Comment by Ch3LL** [comment]
I've done some more research on this locale module and I'm worried about using `setlocale` because it changes the program from using the C locale to the user default settings from the LANG environment variables and I'm not sure what problems this could cause if we mess with the locale. What about an approach where we just find out what the decimal point is here: https://docs.python.org/2/library/locale.html#locale.localeconv

then do a string replace from `,` to `.` if the decimal point is a comma. What do you think of that approach @DmitryKuzmenko

**Comment by DmitryKuzmenko** [comment]
If we have to avoid using the system locale I'm OK.
