### ISSUE TITLE
Stacktrace when fetching archive file types using s3 module

### ISSUE THREAD

**Issue by davidwright** [saltstack/salt#48111]
I am getting the following error when trying to do a salt-call s3.get for archive filetypes(tar, zip, gz). The error does not occur when getting text or image files.

[ERROR   ] An un-handled exception was caught by salt's global exception handler:
ParseError: not well-formed (invalid token): line 1, column 2
Traceback (most recent call last):
  File "/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 391, in salt_call
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 204, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/s3.py", line 204, in get
    https_enable=https_enable)
  File "/usr/lib/python2.7/site-packages/salt/utils/s3.py", line 250, in query
    items = ET.fromstring(result.content)
  File "<string>", line 124, in XML
ParseError: not well-formed (invalid token): line 1, column 2
Traceback (most recent call last):
  File "/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 391, in salt_call
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 204, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/s3.py", line 204, in get
    https_enable=https_enable)
  File "/usr/lib/python2.7/site-packages/salt/utils/s3.py", line 250, in query
    items = ET.fromstring(result.content)
  File "<string>", line 124, in XML
cElementTree.ParseError: not well-formed (invalid token): line 1, column 2

### Setup
Connecting to a S3 compatible HCP Object Storage.

#test S3 Settings
s3.verify_ssl: False
s3.https_enable: True
s3.location: US
s3.service_url: Some_valid_url
s3.keyid: Some_valid_key_id
s3.key: Some_valid_key

### Steps to Reproduce Issue
zip test.zip test.txt
salt-call s3.put sandbox "testserver1/test.zip" local_file="test.zip"
salt-call s3.get sandbox "testserver1/test.zip"

### Versions Report
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Apr 11 2018, 07:36:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.5.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core

**Comment by Ch3LL** [comment]
seems there was a similar issue here: https://github.com/saltstack/salt/issues/23007

can you try the recommendations in there around the `return_bin` kwarg.

**Comment by davidwright** [comment]
Sorry I should have included those details in the original post - I thought I had but didn't. Yes using return_bin will download the file, that is not what I am trying to do. I am trying to fetch the list of headers available for the file.  I found a workaround using s3.head to get a dictionary of headers and values but s3.get should return a list of the file headers available. It works correctly for non archive file types:

salt-call s3.get sandbox "testserver1/test.txt"
local:
    ----------
    headers:
        - content-length
        - x-xss-protection
        - x-content-type-options
        - x-download-options
        - content-type
        - accept-ranges
        - expires
        - last-modified
        - etag
        - x-hcp-contentlength
        - pragma
        - cache-control
        - date
        - x-frame-options
        - x-dns-prefetch-control
        - content-security-policy

**Comment by Ch3LL** [comment]
when trying to put hte archive file up in the bucket i am getting this error:

```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 12: invalid continuation byte
Traceback (most recent call last):
  File "/home/ch3ll/git/salt/scripts//salt-call", line 11, in <module>
    salt_call()
  File "/home/ch3ll/git/salt/salt/scripts.py", line 400, in salt_call
    client.run()
  File "/home/ch3ll/git/salt/salt/cli/call.py", line 57, in run
    caller.run()
  File "/home/ch3ll/git/salt/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/home/ch3ll/git/salt/salt/cli/caller.py", line 212, in call
    ret['return'] = func(*args, **kwargs)
  File "/home/ch3ll/git/salt/salt/modules/s3.py", line 292, in put
    https_enable=https_enable)
  File "/home/ch3ll/git/salt/salt/utils/s3.py", line 161, in query
    stream=True)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1055, in _send_output
    for chunk in chunks:
  File "/usr/lib/python3.6/http/client.py", line 1010, in _read_readable
    datablock = readable.read(blocksize)
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 12: invalid continuation byte
```

with this command: `sudo salt-call --local s3.put ch3lltest "test.zip" local_file="/home/ch3ll/test.zip" -ldebug`  I tested with a normal text file adn was able to push up fine.

I know you are showing the `s3.put` command but did you push your zip file up that way or manually upload it via aws console just to clarify?

**Comment by davidwright** [comment]
I used the put command. The commands I listed are the ones I used to
reproduce the issue after I had narrowed down the cause. Although I am not
connecting to Amazon s3 but an in house s3 compatible storage array.

**Comment by Ch3LL** [comment]
thanks for clarifying. I ended up uploading the file manually and getting it and can replicate your error. I'm also seeing this on 2017.7.4 so this is not a regression.

ping @gtmanfred any ideas here? Do we maybe need to add a header to specify the type of content we are querying?

**Comment by gtmanfred** [comment]
These look like two separate errors, one on python 2.7 and one on python 3.6.

It looks like the OP issue is failing on the result that is returned, not being valid xml.

And @Ch3LL your issue being with encoding of the data that is being uploaded.

Which one am I looking at?

**Comment by Ch3LL** [comment]
im refering to the initial issue.

**Comment by Ch3LL** [comment]
ahh gotchya. okay thanks wasn't sure if there was just something I was just missing. thanks :)
