### ISSUE TITLE
Exception thrown if you ctrl-c from a master -> minion command

### ISSUE THREAD

**Issue by jeffclay** [saltstack/salt#48142]
On a newly updated master from 2018.3.0 to 2018.3.1 running on CentOS-7 with everything up to date, if you run the command 'salt MINION-ID test.ping' then press ctrl-c you get the error below.

```
salt MINION-ID test.ping
^C[ERROR   ] An un-handled exception was caught by salt's global exception handler:
Exception: DummyFuture does not support blocking for results
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 485, in salt_main
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/salt.py", line 193, in run
    for full_ret in cmd_func(**kwargs):
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 842, in cmd_cli
    self.event.close_pub()
  File "/usr/lib/python2.7/site-packages/salt/utils/event.py", line 398, in close_pub
    self.subscriber.close()
  File "/usr/lib/python2.7/site-packages/salt/transport/ipc.py", line 755, in close
    self._read_sync_future.exception()
  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 230, in exception
    self._check_done()
  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 293, in _check_done
    raise Exception("DummyFuture does not support blocking for results")
Exception: DummyFuture does not support blocking for results
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 485, in salt_main
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/salt.py", line 193, in run
    for full_ret in cmd_func(**kwargs):
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 842, in cmd_cli
    self.event.close_pub()
  File "/usr/lib/python2.7/site-packages/salt/utils/event.py", line 398, in close_pub
    self.subscriber.close()
  File "/usr/lib/python2.7/site-packages/salt/transport/ipc.py", line 755, in close
    self._read_sync_future.exception()
  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 230, in exception
    self._check_done()
  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 293, in _check_done
    raise Exception("DummyFuture does not support blocking for results")
Exception: DummyFuture does not support blocking for results
```

### Versions Report
```
salt --versions-report
Salt Version:
           Salt: 2018.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Apr 11 2018, 07:36:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.3.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```

**Comment by gtmanfred** [comment]
Confirmed.

@DmitryKuzmenko would you be able to help with this when you get a second?  It popped up with the work for tornado 5.0, and I think something is just falling through getting caught and printing out the jid, so that it can be looked up after the job finishes.

Thanks,
Daniel

**Comment by gtmanfred** [comment]
Duplicate #47901
