### ISSUE TITLE
Exceptions in execution modules are considered a successful call

### ISSUE THREAD

**Issue by Heiko-san** [saltstack/salt#48303]
### Description of Issue/Question

I came accross this while trying to get a failed condition for a custom salt execution module. Of course I got aware that any return value may be valid and therefore understood, that there is no value that will lead to the function call being considered failed.

However I recognized that even an exception thrown while the function executes is considered a successful call. I'm not aware of any internals that might require such behavior, but I feel this should definitly be considered a failed execution.

``` bash
salt 'minion1' foo.bar ; echo $?
minion1:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1470, in _thread_return
        return_data = executor.execute()
      File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/var/cache/salt/minion/extmods/modules/foo.py", line 2, in bar
        raise Exception("foobar")
    Exception: foobar


-------------------------------------------
Summary
-------------------------------------------
# of minions targeted: 1
# of minions returned: 1
# of minions that did not return: 0
# of minions with errors: 0
-------------------------------------------
0
```

### Setup

* _modules/foo.py
``` python
def bar():                                                                      
    raise Exception("foobar")                                                   
    return "some_value"
```

### Steps to Reproduce Issue

``` bash
salt 'minion' saltutil.sync_all
salt 'minion' foo.bar ; echo $?
```

### Versions Report

```
Salt Version:
           Salt: 2018.3.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.28.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Apr 11 2018, 07:36:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.5.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```

**Comment by gtmanfred** [comment]
This is kind of a duplicate of https://github.com/saltstack/salt/issues/18510 but not quite.

Thanks for the request.
Daniel
