### ISSUE TITLE
salt-api return 500 when run couple of days, but become work after restart salt-api

### ISSUE THREAD

**Issue by jiansongjay** [saltstack/salt#48333]
### Setup
master.conf
```
default_include: master.d/*.conf
worker_threads: 100
auto_accept: True
syndic_master:
  - 10.21.23.31
  - 10.21.23.32
file_roots:
  base:
    - /srv/salt
  ops:
    - /srv/salt/ops
```

salt-api.conf
```
rest_cherrypy:
  port: 8000
  host: 0.0.0.0
  disable_ssl: True
  debug: True
external_auth:
  pam:
    saltapi:
      - .*
      - '@wheel'
      - '@runner'
      - '@jobs'
```

### Steps to Reproduce Issue
Request:
`curl -k http://10.10.100.1:8000 -H "Content-type: application/json" -H "X-Auth-Token: 8441d4b7c2eb83e748f541d68b6f1514a6d8a8fa" -d '{"client":"local","tgt":"test-10-30-54-33-vm","fun":"cmd.run","arg":"w","timeout":60}'`

Response:
```
{
    "status": 500,
    "return": "Traceback (most recent call last):\n  File \"/usr/lib/python2.7/site-packages/salt/netapi/rest_cherrypy/app.py\", line 858, in hypermedia_handler\n    ret = cherrypy.serving.request._hypermedia_inner_handler(*args, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py\", line 60, in __call__\n    return self.callable(*self.args, **self.kwargs)\n  File \"/usr/lib/python2.7/site-packages/salt/netapi/rest_cherrypy/app.py\", line 1286, in POST\n    token=cherrypy.session.get('token')))\n  File \"/usr/lib/python2.7/site-packages/salt/netapi/rest_cherrypy/app.py\", line 1178, in exec_lowstate\n    ret = self.api.run(chunk)\n  File \"/usr/lib/python2.7/site-packages/salt/netapi/__init__.py\", line 75, in run\n    return l_fun(*f_call.get('args', ()), **f_call.get('kwargs', {}))\n  File \"/usr/lib/python2.7/site-packages/salt/netapi/__init__.py\", line 103, in local\n    return local.cmd(*args, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/salt/client/__init__.py\", line 740, in cmd\n    **kwargs)\n  File \"/usr/lib/python2.7/site-packages/salt/client/__init__.py\", line 353, in run_job\n    raise SaltClientError(general_exception)\nSaltClientError: Authentication error occurred.\n"
}
```

### Versions Report
```
Salt Version:
           Salt: 2018.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Mar 30 2018, 15:31:59)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.8 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-642.el6.x86_64
         system: Linux
        version: CentOS 6.8 Final
```

**Comment by Ch3LL** [comment]
if you remove `  debug: True` from your cherrypy config do you still see this issue?

**Comment by Ch3LL** [comment]
This still could possibly be the reason because of this from the docs: (https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html)

>Starts the web server in development mode. It will reload itself when the underlying code is changed and will output more debugging info.

So if you upgraded a library that cherrypy on only one box that uses it, it will restart. and i've noticed on cent6 a defunct process is then created. When you see this issue can you paste the output of `ps uax | grep -i salt-api`

Just want to make sure you aren't running into this.

Also when this occurs do you see anything in the debug logs that you can paste here?

**Comment by alexbe** [comment]
After update to 
```
# salt-api --version
salt-api 2018.3.2 (Oxygen)

```
i'm getting same exception every day when i come to work, so i need to restart salt-api. 
In the time when exception occurs i have two salt-api process:

```
# ps uax | grep -i salt-api
root      4813  0.0  0.0 112700   928 pts/0    S+   13:40   0:00 grep --color=auto -i salt-api
root     13670  0.0  3.7 438560 38408 ?        Ss   сен06   0:04 /usr/bin/python /usr/bin/salt-api
root     13705  1.0  7.7 1870376 78376 ?       Sl   сен06  14:56 /usr/bin/python /usr/bin/salt-api

```

May be i need to increase a system limit or change something in conf?

**Comment by Ch3LL** [comment]
i noticed in the intial users report that `worker_threads: 100` is set. that seems very high unless you are handling A LOT of minions and you would need the appropriate cpu/memory resources to handle that. Are you doing something similar @alexbe

**Comment by alexbe** [comment]
No, my configs are mostly default centos7 configs:
`# grep worker_threads /etc/salt/master
#worker_threads: 5
# cores with appropriate worker_threads will not need these set as high.
`
Probably the only unusual thing i do is every 100 seconds i send to salt-api (cherrypy) GET request "/minions". And after about 12-15 hours of such a normal request process i'm getting 500 error on client side and the exception on server side.

**Comment by Ch3LL** [comment]
can you include your --versions-report output so i can see your package versions?

also is there anything relevant in the debug logs before this occurs?

**Comment by alexbe** [comment]
```
# salt-master --versions-report
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: 5.6.0
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.26.3
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: 3.6.1
         pygit2: 0.26.4
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```
I can't see any significant between normal operation and the exception. Following is the part of /var/log/salt/api logged after normal salt.client response:
`
2018-09-12 00:22:18,795 [cherrypy.access.140197369975504:299 ][INFO    ][26508] 127.0.0.1 - - [12/Sep/2018:00:22:18] "POST / HTTP/1.1" 200 45 "" ""
2018-09-12 00:22:20,728 [salt.client      :236 ][DEBUG   ][26508] Checking whether jid 20180912002215598466 is still running
2018-09-12 00:22:20,729 [salt.transport.zeromq:128 ][DEBUG   ][26508] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/master', u'ukm5-manager.servplus.ru_master', u'tcp://127.0.0
.1:4506', u'clear')
2018-09-12 00:22:20,730 [salt.transport.zeromq:194 ][DEBUG   ][26508] Connecting the Minion to the Master URI (for the return server): tcp://127.0.0.1:4506
2018-09-12 00:22:20,730 [salt.transport.zeromq:1029][DEBUG   ][26508] Trying to connect to: tcp://127.0.0.1:4506
2018-09-12 00:22:20,795 [salt.client      :1284][DEBUG   ][26508] Passing on saltutil error. Key 'u'retcode' missing from client return. This may be an error in the client.
2018-09-12 00:22:30,850 [cherrypy.access.140197369975504:299 ][INFO    ][26508] 127.0.0.1 - - [12/Sep/2018:00:22:30] "GET /minions HTTP/1.1" 200 8979 "" ""
2018-09-12 00:23:55,438 [salt.utils.event :321 ][DEBUG   ][26508] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
2018-09-12 00:23:55,438 [salt.utils.event :324 ][DEBUG   ][26508] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
2018-09-12 00:23:55,530 [salt.utils.lazy  :100 ][DEBUG   ][26508] LazyLoaded masterscript.get_ngroups
2018-09-12 00:23:55,532 [salt.utils.event :321 ][DEBUG   ][26508] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
2018-09-12 00:23:55,533 [salt.utils.event :324 ][DEBUG   ][26508] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
2018-09-12 00:23:55,533 [salt.transport.ipc:254 ][DEBUG   ][26508] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
2018-09-12 00:23:55,535 [salt.transport.zeromq:128 ][DEBUG   ][26508] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/master', u'ukm5-manager.servplus.ru_master', u'tcp://127.0.0.1:4506', u'clear')
2018-09-12 00:23:55,536 [salt.transport.zeromq:194 ][DEBUG   ][26508] Connecting the Minion to the Master URI (for the return server): tcp://127.0.0.1:4506
2018-09-12 00:23:55,540 [salt.transport.zeromq:1029][DEBUG   ][26508] Trying to connect to: tcp://127.0.0.1:4506
2018-09-12 00:23:55,627 [salt.transport.zeromq:128 ][DEBUG   ][26508] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/master', u'ukm5-manager.servplus.ru_master', u'tcp://127.0.0.1:4506', u'clear')
2018-09-12 00:23:55,628 [salt.transport.zeromq:194 ][DEBUG   ][26508] Connecting the Minion to the Master URI (for the return server): tcp://127.0.0.1:4506
2018-09-12 00:23:55,629 [salt.transport.zeromq:1029][DEBUG   ][26508] Trying to connect to: tcp://127.0.0.1:4506
2018-09-12 00:23:55,630 [salt.transport.ipc:254 ][DEBUG   ][26508] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
2018-09-12 00:23:55,670 [salt.loaded.int.netapi.rest_cherrypy.app:885 ][DEBUG   ][26508] Error while processing request for: /minions
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/netapi/rest_cherrypy/app.py", line 858, in hypermedia_handler
    ret = cherrypy.serving.request._hypermedia_inner_handler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/salt/netapi/rest_cherrypy/app.py", line 1342, in GET
    token=cherrypy.session.get('token'))),
  File "/usr/lib/python2.7/site-packages/salt/netapi/rest_cherrypy/app.py", line 1178, in exec_lowstate
    ret = self.api.run(chunk)
  File "/usr/lib/python2.7/site-packages/salt/netapi/__init__.py", line 75, in run
    return l_fun(*f_call.get('args', ()), **f_call.get('kwargs', {}))
  File "/usr/lib/python2.7/site-packages/salt/netapi/__init__.py", line 103, in local
    return local.cmd(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 741, in cmd
    **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 354, in run_job
    raise SaltClientError(general_exception)
SaltClientError: Authentication error occurred.

`

**Comment by Ch3LL** [comment]
thanks for the additional information. ping @saltstack/team-netapi any ideas here?

**Comment by hiscal2015** [comment]
I have the same issue. I'm using 2018.3.2.

**Comment by Ch3LL** [comment]
okay i stood up a box and i'll check it throughout the day and on monday and update here to see if i can replicate the error. One more question while i'm waiting, when you get the authentication error, if you run a salt command outside of salt-api does it work with that user? For example `salt -a pam '*' test.ping`

**Comment by alexbe** [comment]
Yes, sure, as i mentioned before it is working normally for a half day. Nonetheless i logged as root at the time when exception occurs, wrote
salt -a pam --username=pepper --password=something '*' test.ping
and got normal response

**Comment by Ch3LL** [comment]
thanks for verifying that for me. So we know its related to the api call somehow since the salt-cli tool authenticated. I unfortunately have not been able to replicate this. I have one theory. Are all of you authenticating with tokens? If so can you try the following when the issue shows up again:

1. Authenticate with username and password and see if that works
2. If that works re log in to get a new token and see if you can now use token again.

This will help narrow it down whether its an issue with the token authentication.

**Comment by alexbe** [comment]
Thanks, Megan, you are absolutely right, the exception is produced by old token. So it is not a bug, just a feature :) Probably i was confused by the exception itself
It disappeared after restart of my client app, and of cause new requests give me normal answer.
Excuse me for the vain concern

**Comment by Ch3LL** [comment]
and you are certain that when this occurs the token is indeed expired? I just want to make sure that is the case and this isn't a bug
