### ISSUE TITLE
Salt doesn't work if cffi 1.2.1 is installed

### ISSUE THREAD

**Issue by dosercz** [saltstack/salt#48341]
We have upgraded Debian to Stretch and after that salt stops working on one of our servers. Remote call via salt-ssh fails too with same error. I have tried salt-ssh from salt-master and it works only until salt-minion is installed. Problem is with probably broken cffi 1.2.1, which was installed on this server with salt-minion by default.
Solution: delete cffi packages manually from /usr/local/lib/python2.7/dist-packages/ (pip doesn't work, it has same error as salt)

Error:
```
Traceback (most recent call last):
          File "/var/tmp/.root_e14548_salt/salt-call", line 15, in <module>
            salt_call()
          File "/var/tmp/.root_e14548_salt/py2/salt/scripts.py", line 395, in salt_call
            import salt.cli.call
          File "/var/tmp/.root_e14548_salt/py2/salt/cli/call.py", line 8, in <module>
            import salt.cli.caller
          File "/var/tmp/.root_e14548_salt/py2/salt/cli/caller.py", line 19, in <module>
            import salt.minion
          File "/var/tmp/.root_e14548_salt/py2/salt/minion.py", line 81, in <module>
            import salt.pillar
          File "/var/tmp/.root_e14548_salt/py2/salt/pillar/__init__.py", line 20, in <module>
            import salt.fileclient
          File "/var/tmp/.root_e14548_salt/py2/salt/fileclient.py", line 31, in <module>
            import salt.utils.http
          File "/var/tmp/.root_e14548_salt/py2/salt/utils/http.py", line 80, in <module>
            import requests
          File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 52, in <module>
            from .packages.urllib3.contrib import pyopenssl
          File "/usr/lib/python2.7/dist-packages/requests/packages/__init__.py", line 59, in <module>
            vendored('urllib3.contrib.pyopenssl')
          File "/usr/lib/python2.7/dist-packages/requests/packages/__init__.py", line 32, in vendored
            __import__(vendored_name, globals(), locals(), level=0)
          File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 47, in <module>
            import OpenSSL.SSL
          File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
            from OpenSSL import rand, crypto, SSL
          File "/usr/lib/python2.7/dist-packages/OpenSSL/rand.py", line 12, in <module>
            from OpenSSL._util import (
          File "/usr/lib/python2.7/dist-packages/OpenSSL/_util.py", line 6, in <module>
            from cryptography.hazmat.bindings.openssl.binding import Binding
          File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 173, in <module>
            Binding.init_static_locks()
          File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 137, in init_static_locks
            cls._ensure_ffi_initialized()
          File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 124, in _ensure_ffi_initialized
            cls.lib = build_conditional_library(lib, CONDITIONAL_NAMES)
          File "/usr/lib/python2.7/dist-packages/cryptogr
```
### Versions Report
```
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: 1.2.1
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Nov 24 2017, 17:33:09)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.4
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-6-amd64
         system: Linux
        version: debian 9.4
```

**Comment by Ch3LL** [comment]
im having a hard time replicating this. Can you clarify what you are attempting to do when you see this error? running a certain command, etc

**Comment by Ch3LL** [comment]
is cffi installed on the minion you are salt-sshing into or on the master? Also in the original report i dont think you included the entire traceback, can you paste that here?

**Comment by dosercz** [comment]
Problem with cffi was on minion (local call fails same as salt-ssh from master), master has no problem.
Server is fixed now, so I'm not able get traceback again:(

**Comment by Ch3LL** [comment]
Weird okay you okay closing this issue for now and re-opening if it shows again?
