### ISSUE TITLE
salt-api return 500 when trying to run the job

### ISSUE THREAD

**Issue by jfoboss** [saltstack/salt#48355]
### Description of Issue/Question
We are unable to use CherryPy after updating to 2018.3.2 (`SaltClientError: Authentication error occurred.`).

### Setup
```
user: "root"
timeout: 30
cache: "consul"
auto_accept: true
external_auth:
  pam:
    saltuser:
      - '.*'
      - '@wheel'
      - '@runner'
      - '@jobs'
file_roots:
  base:
    - /srv/salt/formulas
pillar_roots:
  base:
    - /srv/salt/pillars
log_level: "error"
winrepo_dir_ng: "/srv/salt/formulas/win/repo-ng"
rest_cherrypy:
  response.timeout: 120
  webhook_disable_auth: True
  disable_ssl: True
  host: localhost
  webhook_url: /hook
  expire_responses: False
  port: 8000
consul.host: "127.0.0.1"
consul.token: "XXXX"
consul.port: 8500
consul.scheme: "http"
consul.consistency: "default"
consul.verify: true
consul.dc: "XXXX"

```

### Steps to Reproduce Issue
Try to run the job on 2018.3.2 which works perfect on older releases and get:
```
2018-06-28 12:34:44,444 [salt.loaded.int.netapi.rest_cherrypy.app:885 ][DEBUG   ][25045] Error while processing request for: /run
Traceback (most recent call last):
 File "/usr/lib/python2.7/site-packages/salt/netapi/rest_cherrypy/app.py", line 858, in hypermedia_handler
   ret = cherrypy.serving.request._hypermedia_inner_handler(*args, **kwargs)
 File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
   return self.callable(*self.args, **self.kwargs)
 File "/usr/lib/python2.7/site-packages/salt/netapi/rest_cherrypy/app.py", line 2128, in POST
   'return': list(self.exec_lowstate()),
 File "/usr/lib/python2.7/site-packages/salt/netapi/rest_cherrypy/app.py", line 1178, in exec_lowstate
   ret = self.api.run(chunk)
 File "/usr/lib/python2.7/site-packages/salt/netapi/__init__.py", line 75, in run
   return l_fun(*f_call.get('args', ()), **f_call.get('kwargs', {}))
 File "/usr/lib/python2.7/site-packages/salt/netapi/__init__.py", line 103, in local
   return local.cmd(*args, **kwargs)
 File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 741, in cmd
   **kwargs)
 File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 354, in run_job
   raise SaltClientError(general_exception)
SaltClientError: Authentication error occurred.
2018-06-28 12:34:44,445 [cherrypy.access.139985439236944:299 ][INFO    ][25045] ::1 - - [28/Jun/2018:12:34:44] "POST /run HTTP/1.1" 500 57 "" "Apache-HttpClient/4.5.2 (Java/
1.8.0_171)"
```

### Versions Report
```
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Apr 11 2018, 07:36:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.3.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```

**Comment by jfoboss** [comment]
Sorry, found misconfuguration - everything is working great! Sorry for inconvenience.
