### ISSUE TITLE
2017.7.6 breaks zeromq

### ISSUE THREAD

**Issue by jatorvi** [saltstack/salt#48370]
### Description of Issue/Question
update from 2017.7.5 to 2017.7.6 breaks zeromq on salt-master when trying to run caller.cmd.run from reactor on debian 9 py2. local.cmd.run silently fails.
`salt-call cmd.run cmd=` works as expected, as does `salt 'target' cmd.run cmd=`

### Setup
```
run_command:
  caller.cmd.run:
    - args:
      - cmd: 'touch /tmp/foo'
```
### Steps to Reproduce Issue
`salt-call event.send what/ever/triggers/reactor`

resulting error from journal:
```
[WARNING ] /usr/lib/python2.7/dist-packages/salt/minion.py:648: RuntimeWarning: IOLoop.current expected instance of <class 'zmq.eventloop.ioloop.ZMQIOLoop'>, got <tornado.platform.epoll.EPollIOLoop object at 0x7f97d3467a50>
  io_loop = ZMQDefaultLoop.current()
[WARNING ] /usr/lib/python2.7/dist-packages/salt/transport/zeromq.py:329: RuntimeWarning: IOLoop.current expected instance of <class 'zmq.eventloop.ioloop.ZMQIOLoop'>, got <tornado.platform.epoll.EPollIOLoop object at 0x7f97d3467a50>
  self.io_loop = ZMQDefaultLoop.current()
[ERROR   ] Exception in callback <functools.partial object at 0x7f97d0226100>
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/ioloop.py", line 604, in _run_callback
    ret = callback()
  File "/usr/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/tornado/ioloop.py", line 619, in <lambda>
    self.add_future(ret, lambda f: f.result())
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 285, in wrapper
    yielded = next(result)
  File "/usr/lib/python2.7/dist-packages/salt/crypt.py", line 510, in _authenticate
    io_loop=self.io_loop)
  File "/usr/lib/python2.7/dist-packages/salt/transport/client.py", line 108, in factory
    return salt.transport.zeromq.AsyncZeroMQReqChannel(opts, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 130, in __new__
    obj.__singleton_init__(opts, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 193, in __singleton_init__
    kwargs={'io_loop': self._io_loop})
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 907, in __init__
    super(AsyncReqMessageClientPool, self).__init__(AsyncReqMessageClient, opts, args=args, kwargs=kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/__init__.py", line 69, in __init__
    self.message_clients = [tgt(*args, **kwargs) for _ in range(sock_pool_size)]
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 954, in __init__
    self._init_socket()
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 1007, in _init_socket
    self.stream = zmq.eventloop.zmqstream.ZMQStream(self.socket, io_loop=self.io_loop)
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 114, in __init__
    self._init_io_state()
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 535, in _init_io_state
    self.io_loop.add_handler(self.socket, self._handle_events, self._state)
  File "/usr/lib/python2.7/dist-packages/tornado/ioloop.py", line 725, in add_handler
    self._impl.register(fd, events | self.ERROR)
TypeError: argument must be an int, or have a fileno() method.
```

### Versions Report
Salt Version:
           Salt: 2017.7.6

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Nov 24 2017, 17:33:09)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.4
         locale: UTF-8
        machine: x86_64
        release: 4.15.17-1-pve
         system: Linux
        version: debian 9.4

**Comment by DmitryKuzmenko** [comment]
@jatorvi is it possible for you to try to do a small manual change on the master and check will it fix the issue?

Here's the change I'm talking about:
```diff
diff --git a/salt/utils/event.py b/salt/utils/event.py
index a6daef0670..03c3cf27ae 100644
--- a/salt/utils/event.py
+++ b/salt/utils/event.py
@@ -82,6 +82,7 @@ import salt.utils.zeromq
 import salt.log.setup
 import salt.defaults.exitcodes
 import salt.transport.ipc
+from salt.utils.zeromq import zmq, ZMQDefaultLoop, install_zmq, ZMQ_VERSION_INFO
 
 log = logging.getLogger(__name__)
 
@@ -229,7 +230,8 @@ class SaltEvent(object):
             self.io_loop = io_loop
             self._run_io_loop_sync = False
         else:
-            self.io_loop = tornado.ioloop.IOLoop()
+            install_zmq()
+            io_loop = ZMQDefaultLoop.current()
             self._run_io_loop_sync = True
         self.cpub = False
         self.cpush = False
```

**Comment by jatorvi** [comment]
you mean self.io_loop right?
diff to /usr/lib/python2.7/dist-packages/salt/utils/event.py:
```
--- event.py.bak        2018-06-07 20:42:00.000000000 +0300
+++ event.py    2018-06-29 17:08:44.995434460 +0300
@@ -82,6 +82,7 @@
 import salt.log.setup
 import salt.defaults.exitcodes
 import salt.transport.ipc
+from salt.utils.zeromq import zmq, ZMQDefaultLoop, install_zmq, ZMQ_VERSION_INFO

 log = logging.getLogger(__name__)

@@ -229,7 +230,8 @@
             self.io_loop = io_loop
             self._run_io_loop_sync = False
         else:
-            self.io_loop = tornado.ioloop.IOLoop()
+            install_zmq()
+            self.io_loop = ZMQDefaultLoop.current()
             self._run_io_loop_sync = True
         self.cpub = False
         self.cpush = False

```
Seems to work! No errors/traces and the command gets executed, and consecutive events work so it does not hang after it or anything. Thanks!

with io_loop = ZMQDefaultLoop.current() gives lots of errors only by starting master :)

**Comment by DmitryKuzmenko** [comment]
@jatorvi thank you. It's not a solution, just wanted to ensure I'm thinking in the right direction.

**Comment by jatorvi** [comment]
Ok, I've quickly fixed reactors to use local.cmd.run and target minion running on master. That can be workaround until proper fix.

**Comment by cmcmarrow** [comment]
Just Ran this on master branch. on deb9 with python3.5 and I got no error. I ran salt-run event.send foo '{orchestrate: refresh}'

**Comment by cmcmarrow** [comment]
Feel free to reopen this issue if you still get this error on python3 on the master branch.
