### ISSUE TITLE
state pip.installed requires force_reinstall: True

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack/salt#48407]
### Description of Issue/Question

The state `pip.installed` does not work as documented on MacOS.

> [ERROR   ] Command '[u'/usr/local/bin/pip2.7', u'install']' failed with return code: 1
> [ERROR   ] stderr: ERROR: You must give at least one requirement to install (see "pip help install")
> [ERROR   ] retcode: 1
> [ERROR   ] Python package docker was already installed

Only works if `force_reinstall: True` is specified.

### Setup

MacOS

### Steps to Reproduce Issue

**Attempt 1**
```
etcd-pip-docker-package:
   pip.installed:
      name:
      - docker

$ sudo salt-call state.highstate --local
[ERROR   ] Command '[u'/usr/local/bin/pip2.7', u'install', u'--exists-action', u'i', u'etcd-pip-docker-package']' failed with return code: 1
```

**Attempt 2**
```
etcd-pip-docker-package:
   pip.installed:
      name: docker

sudo salt-call state.highstate --local
[ERROR   ] Command '[u'/usr/local/bin/pip2.7', u'install', u'--exists-action', u'i']' failed with return code: 1
```

**Attempt 3**
```
docker:
   pip.installed:

$ sudo salt-call state.highstate --local
[ERROR   ] Command '[u'/usr/local/bin/pip2.7', u'install', u'--exists-action', u'i']' failed with return code: 1
```

Using `exists_action: i' or `force: False` has no effect.

**Attempt 4 (`force_reinstall: True` and `runas: user`)**
```
[ERROR   ] Command '[u'/usr/local/bin/pip2.7', u'install', u'--force-reinstall', u'docker']' failed with return code: 1
[ERROR   ] stdout: Collecting docker
  Downloading https://files.pythonhosted.org/packages/a5/64/8c0a5d22e70257e6b7ef7f14b577f99f0b9b1560c604f87856d0db80d151/docker-3.4.1-py2.py3-none-any.whl (124kB)
```

**Attempt 5 (`force_reinstall: True`)**
```
ID: docker
    Function: pip.installed
      Result: True
     Comment: All packages were successfully installed
     Started: 16:31:34.755483
    Duration: 19221.273 ms
     Changes:   
              ----------
              docker==3.4.1:
                  Installed
```

### Versions Report
```
$ salt-call --versions-report
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.27.0
        libnacl: Not Installed
       M2Crypto: 0.29.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.27.0
         Python: 2.7.14 (default, Apr 25 2018, 15:22:05)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 17.5.0
         system: Darwin
        version: 10.13.4 x86_64
```

**Comment by noelmcloughlin** [comment]
Some issue with python library.
```
$ pip list | grep docker
docker                                 3.4.1    
docker-pycreds                         0.3.0    

$ python
Python 2.7.13 (default, Apr  4 2017, 08:46:44) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import docker
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named docker
>>>
```

**Comment by noelmcloughlin** [comment]
Changing from `pip.installed` to `cmd.run` produces cleaner non-Error output.  
```
 ID: etcd-pip-docker-package
    Function: cmd.run
        Name: pip install docker
      Result: True
     Comment: Command "pip install docker" run
     Started: 17:04:52.533197
    Duration: 705.557 ms
     Changes:   
              ----------
              pid:
                  25358
              retcode:
                  0
              stderr:
                  The directory '/Users/nmcloughlin/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
                  The directory '/Users/nmcloughlin/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
                  matplotlib 1.3.1 requires nose, which is not installed.
                  matplotlib 1.3.1 requires tornado, which is not installed.
              stdout:
                  Requirement already satisfied: docker in /Library/Python/2.7/site-packages (3.4.1)
                  Requirement already satisfied: backports.ssl-match-hostname>=3.5; python_version < "3.5" in /Library/Python/2.7/site-packages (from docker) (3.5.0.1)
                  Requirement already satisfied: ipaddress>=1.0.16; python_version < "3.3" in /Library/Python/2.7/site-packages (from docker) (1.0.22)
                  Requirement already satisfied: six>=1.4.0 in /Library/Python/2.7/site-packages (from docker) (1.11.0)
                  Requirement already satisfied: requests!=2.18.0,>=2.14.2 in /Library/Python/2.7/site-packages (from docker) (2.19.1)
                  Requirement already satisfied: docker-pycreds>=0.3.0 in /Library/Python/2.7/site-packages (from docker) (0.3.0)
                  Requirement already satisfied: websocket-client>=0.32.0 in /Library/Python/2.7/site-packages (from docker) (0.48.0)
                  Requirement already satisfied: certifi>=2017.4.17 in /Library/Python/2.7/site-packages (from requests!=2.18.0,>=2.14.2->docker) (2018.4.16)
                  Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Library/Python/2.7/site-packages (from requests!=2.18.0,>=2.14.2->docker) (3.0.4)
                  Requirement already satisfied: urllib3<1.24,>=1.21.1 in /Library/Python/2.7/site-packages (from requests!=2.18.0,>=2.14.2->docker) (1.23)
                  Requirement already satisfied: idna<2.8,>=2.5 in /Library/Python/2.7/site-packages (from requests!=2.18.0,>=2.14.2->docker) (2.7)
```
I uninstalled and resinstalled pip and tried again - this pattern seems to work better. 
```
docker:
  pip.installed:
    - exists_action: i
    - force_reinstall: True
    - require_in:
      - docker_container: run etcd dockerized service
```
But docker module is not installed by Salt.
```
find /usr/local/lib/python2.7/site-packages/docker*
/usr/local/lib/python2.7/site-packages/docker_pycreds-0.2.2.dist-info
/usr/local/lib/python2.7/site-packages/docker_pycreds-0.2.2.dist-info/RECORD
/usr/local/lib/python2.7/site-packages/docker_pycreds-0.2.2.dist-info/metadata.json
/usr/local/lib/python2.7/site-packages/docker_pycreds-0.2.2.dist-info/WHEEL
/usr/local/lib/python2.7/site-packages/docker_pycreds-0.2.2.dist-info/DESCRIPTION.rst
/usr/local/lib/python2.7/site-packages/docker_pycreds-0.2.2.dist-info/top_level.txt
/usr/local/lib/python2.7/site-packages/docker_pycreds-0.2.2.dist-info/INSTALLER
/usr/local/lib/python2.7/site-packages/docker_pycreds-0.2.2.dist-info/METADATA
/usr/local/lib/python2.7/site-packages/dockerpycreds
/usr/local/lib/python2.7/site-packages/dockerpycreds/store.pyc
/usr/local/lib/python2.7/site-packages/dockerpycreds/store.py
/usr/local/lib/python2.7/site-packages/dockerpycreds/version.py
/usr/local/lib/python2.7/site-packages/dockerpycreds/errors.pyc
/usr/local/lib/python2.7/site-packages/dockerpycreds/constants.py
/usr/local/lib/python2.7/site-packages/dockerpycreds/__init__.py
/usr/local/lib/python2.7/site-packages/dockerpycreds/version.pyc
/usr/local/lib/python2.7/site-packages/dockerpycreds/constants.pyc
/usr/local/lib/python2.7/site-packages/dockerpycreds/__init__.pyc
/usr/local/lib/python2.7/site-packages/dockerpycreds/errors.py
```
Uninstall of pip 
```
$ sudo pip uninstall pip
The directory '/Users/nmcloughlin/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Uninstalling pip-10.0.1:
  Would remove:
    /Library/Python/2.7/site-packages/pip-10.0.1-py2.7.egg
    /usr/local/bin/pip
    /usr/local/bin/pip3
    /usr/local/bin/pip3.6
```

Must be an issue with PYTHONPATH.

**Comment by noelmcloughlin** [comment]
Fixed python issue as follows
```
brew uninstall python
sudo easy_install pip

$ python
Python 2.7.10 (default, Oct  6 2017, 22:29:07) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import docker
>>>
```
Running state again, removed the `pip.installed` state, still having issue:
```
[ERROR   ] State 'docker_container.running' was not found in SLS 'etcd.docker.running'
Reason: 'docker_container' __virtual__ returned False: 'docker.version' is not available.
```
Maybe need to reinstall salt?

**Comment by noelmcloughlin** [comment]
Cannot find solution.
```
$ sudo find /Library/  -name docker
/Library//Python/2.7/site-packages/docker
```
Salt error
```
[ERROR   ] State 'docker_container.running' was not found in SLS 'etcd.docker.running'
Reason: 'docker_container' __virtual__ returned False: 'docker.version' is not available.


  ID: docker
    Function: pip.installed
      Result: True
     Comment: All packages were successfully installed
     Started: 18:29:33.997794
    Duration: 38354.26 ms
     Changes:   
              ----------
              docker==3.4.1:
                  Installed
----------
          ID: run etcd dockerized service
    Function: docker_container.running
        Name: coreos-etcd-latest
      Result: False
     Comment: State 'docker_container.running' was not found in SLS 'etcd.docker.running'
              Reason: 'docker_container' __virtual__ returned False: 'docker.version' is not available.
     Changes:   
````

**Comment by noelmcloughlin** [comment]
Also seen on Ubuntu 16.04, verified workaround is `force_reinstall: True` ....
```
etcd-docker-python-module:
  pip.installed:
    - name: 'docker'
    - reload_modules: True
    - exists_action: i
    - force_reinstall: True
```

**Comment by selfin** [comment]
@noelmcloughlin, please, try to upgrade salt at least to 2018.3.1, your first problem with `pip.installed` should be already resolved there with https://github.com/saltstack/salt/commit/34bf66c09f67382cb05b5be3b02ed5a932d62ebe

**Comment by noelmcloughlin** [comment]
Thanks @selfin I'll try that during the week and close the issue if it works.

**Comment by hemebond** [comment]
Having the same/similar issue on 2017.7.7. `force_reinstall: True` didn't help.

```
Salt Version:
           Salt: 2017.7.7
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.7 
         locale: UTF-8
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.7 
```

States:
```
docker-repo:
  pkgrepo.managed:
    - name: deb https://apt.dockerproject.org/repo {{ grains["os"]|lower }}-{{ grains["oscodename"] }} main
    - humanname: {{ grains["os"] }} {{ grains["oscodename"]|capitalize }} Docker Package Repository
    - keyid: 58118E89F3A912897C070ADBF76221572C52609D
    - keyserver: hkp://p80.pool.sks-keyservers.net:80
    - refresh_db: True

docker-engine:
  pkg.installed:
    - require:
      - pkgrepo: docker-repo

docker:
  pip.installed:
    - reload_modules: True
    - force_reinstall: True
    - upgrade: True
    - require:
      - pkg: docker-engine

nginx:
  docker_container.running:
    - image: nginx:latest
    - require:
      - pip: docker
```

Result:
```
# salt-call state.apply testminion
[ERROR   ] Failed to import module dockermod, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1438, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/usr/lib/python2.7/dist-packages/salt/modules/dockermod.py", line 219, in <module>
    import docker
  File "/usr/local/lib/python2.7/dist-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/usr/local/lib/python2.7/dist-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 10, in <module>
    from .build import BuildApiMixin
  File "/usr/local/lib/python2.7/dist-packages/docker/api/build.py", line 6, in <module>
    from .. import auth
  File "/usr/local/lib/python2.7/dist-packages/docker/auth.py", line 8, in <module>
    from . import errors
  File "/usr/local/lib/python2.7/dist-packages/docker/errors.py", line 34, in <module>
    class APIError(requests.exceptions.HTTPError, DockerException):
AttributeError: 'module' object has no attribute 'exceptions'
[ERROR   ] State 'docker_container.running' was not found in SLS 'testminion'
Reason: 'docker_container' __virtual__ returned False: 'docker.version' is not available.

local:
----------
          ID: docker-repo
    Function: pkgrepo.managed
        Name: deb https://apt.dockerproject.org/repo debian-jessie main
      Result: True
     Comment: Package repo 'deb https://apt.dockerproject.org/repo debian-jessie main' already configured
     Started: 21:41:48.441692
    Duration: 43.306 ms
     Changes:   
----------
          ID: docker-engine
    Function: pkg.installed
      Result: True
     Comment: The following packages were installed/updated: docker-engine
     Started: 21:41:48.864323
    Duration: 8002.486 ms
     Changes:   
              ----------
              docker-engine:
                  ----------
                  new:
                      17.05.0~ce-0~debian-jessie
                  old:
----------
          ID: docker
    Function: pip.installed
      Result: True
     Comment: All packages were successfully installed
     Started: 21:41:57.524563
    Duration: 2198.257 ms
     Changes:   
              ----------
              docker==3.5.0:
                  Installed
----------
          ID: nginx
    Function: docker_container.running
      Result: False
     Comment: State 'docker_container.running' was not found in SLS 'testminion'
              Reason: 'docker_container' __virtual__ returned False: 'docker.version' is not available.
     Changes:   
```

Reset with:
```
salt-call pip.uninstall certifi,docker && salt-call pkg.purge docker-engine && systemctl restart salt-minion
```

**Comment by twangboy** [comment]
Closing this issue due to age and lack of activity. Please test this on version 3006.2 and create a new issue if the problem persists. The new issue template has more information and will allow us to track and reproduce the issue more effectively. Thanks!
