### ISSUE TITLE
salt-minion start error, salt-master can't see

### ISSUE THREAD

**Issue by like-inspur** [saltstack/salt#48448]
I install salt-minion 2017.7.7 on ubuntu 16.04 with apt command, just configure master address in /etc/salt/minion, but I found error in service start log and salt-master can't see it
2018-07-05 19:48:17,589 [salt.utils.parsers:1051][WARNING ][3108] Minion received a SIGTERM. Exiting.
2018-07-05 19:48:29,589 [tornado.application:792 ][ERROR   ][30802] Exception in callback <functools.partial object at 0x7f060636e418>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 759, in _run_callback
    ret = callback()
  File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 780, in _discard_future_result
    future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 260, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 315, in wrapper
    yielded = next(result)
  File "/usr/lib/python2.7/dist-packages/salt/crypt.py", line 510, in _authenticate
    io_loop=self.io_loop)
  File "/usr/lib/python2.7/dist-packages/salt/transport/client.py", line 108, in factory
    return salt.transport.zeromq.AsyncZeroMQReqChannel(opts, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 130, in __new__
    obj.__singleton_init__(opts, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 193, in __singleton_init__
    kwargs={'io_loop': self._io_loop})
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 907, in __init__
    super(AsyncReqMessageClientPool, self).__init__(AsyncReqMessageClient, opts, args=args, kwargs=kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/__init__.py", line 69, in __init__
    self.message_clients = [tgt(*args, **kwargs) for _ in range(sock_pool_size)]
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 954, in __init__
    self._init_socket()
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 1007, in _init_socket
    self.stream = zmq.eventloop.zmqstream.ZMQStream(self.socket, io_loop=self.io_loop)
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 114, in __init__
    self._init_io_state()
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 535, in _init_io_state
    self.io_loop.add_handler(self.socket, self._handle_events, self._state)
  File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 901, in add_handler
    self._impl.register(fd, events | self.ERROR)
TypeError: argument must be an int, or have a fileno() method.
@uggedal @jfrost @timcharper @fivethreeo @auser

**Comment by importepeu** [comment]
Hi, I'm not a salt developper but will try to help.

Can you post your master and minion configs please ? Can you stop your minion, clear the log, and repost all logs from minion ? Are you able to reach port 4505 or 4506 of the master from your minion server ? To know that, what this commands return ?

# nc -zv <master_ip> 4505
# nc -zv <master_ip> 4506

**Comment by like-inspur** [comment]
@importepeu It works, the network of master and minion is not the problem.

**Comment by importepeu** [comment]
Ok. I just wanted to check connectivity due to the fact that your master doesn't seems to receive the minion key. It is almost the first thing minion does after generates them.

You don't seem to used the distrib version as I far I can see, cause [16.04 brings version 2015.8.8+ds-1](https://packages.ubuntu.com/xenial/allpackages). Why didin't you want to used the last salt version instead of 2017 one ?

Can you post your master/minion conf and requested logs ?

**Comment by like-inspur** [comment]
I have upgrade salt-master and salt-minion to salt 2018.3.2 (Oxygen), but error still exists.
master config: interface: 10.110.25.215
minion config: master: 10.110.25.215
minion error log:
2018-07-06 18:12:29,590 [tornado.application:792 ][ERROR   ][16704] Exception in callback <functools.partial object at 0x7f5d82e38628>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 759, in _run_callback
    ret = callback()
  File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 780, in _discard_future_result
    future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 260, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 315, in wrapper
    yielded = next(result)
  File "/usr/lib/python2.7/dist-packages/salt/crypt.py", line 598, in _authenticate
    io_loop=self.io_loop)
  File "/usr/lib/python2.7/dist-packages/salt/transport/client.py", line 108, in factory
    return salt.transport.zeromq.AsyncZeroMQReqChannel(opts, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 133, in __new__
    obj.__singleton_init__(opts, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 197, in __singleton_init__
    kwargs={'io_loop': self._io_loop})
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 930, in __init__
    super(AsyncReqMessageClientPool, self).__init__(AsyncReqMessageClient, opts, args=args, kwargs=kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/__init__.py", line 71, in __init__
    self.message_clients = [tgt(*args, **kwargs) for _ in range(sock_pool_size)]
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 977, in __init__
    self._init_socket()
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 1031, in _init_socket
    self.stream = zmq.eventloop.zmqstream.ZMQStream(self.socket, io_loop=self.io_loop)
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 114, in __init__
    self._init_io_state()
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 535, in _init_io_state
    self.io_loop.add_handler(self.socket, self._handle_events, self._state)
  File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 901, in add_handler
    self._impl.register(fd, events | self.ERROR)
TypeError: argument must be an int, or have a fileno() method.

**Comment by ancat** [comment]
Bumping this -- I am seeing the same exact issue as the previous comment.

**Comment by ancat** [comment]
The solution here is to update PyZMQ. Ubuntu 16.04's latest version of PyZMQ is 15.2.0 which is incompatible with salt-minion. However, python-zmq is a dependency for salt-minion and so removing it via apt will end up removing salt as well. The workaround I've found is to install the latest PyZMQ via pip:

```
sudo pip install --ignore-installed --upgrade pyzmq==17.1.2
```

The `--ignore-installed` is an unfortunately required hack that tells pip to ignore the version of PyZMQ installed on the system via apt.
