### ISSUE TITLE
salt-cloud create ec2 instance with slash "/" in the Name tag

### ISSUE THREAD

**Issue by ac-hibbert** [saltstack/salt#48469]
### Description of Issue/Question

We have the requirement to tag our instances with a Name that is "Project/Name" so we need to retag our instances

### Setup

Able to rename instances using the following

```
salt-cloud -a rename instance-name newname=project/instance-name
```

But having problems when running salt-cloud to spin up new instance, with cloud.profiles.d setup and cloud.maps.d file showing

```
instance-name:
  - project/instance-name
```

I get the following error

```
TRACE: [Errno 2] No such file or directory: '/etc/salt/pki/master/minions/project/instance-name'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 65, in _call
    ret = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 2311, in create_multiprocessing
    local_master=parallel_data['local_master']
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1253, in create
    self.opts['pki_dir'], vm_['pub_key'], key_id
  File "/usr/lib/python2.7/site-packages/salt/utils/cloud.py", line 185, in accept_key
    with salt.utils.fopen(key, 'w+') as fp_:
  File "/usr/lib/python2.7/site-packages/salt/utils/__init__.py", line 1357, in fopen
    fhandle = open(*args, **kwargs)  # pylint: disable=resource-leakage
IOError: [Errno 2] No such file or directory: '/etc/salt/pki/master/minions/project/instance-name'
```
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report

```
# salt --versions-report
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: 1.10.6
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

**Comment by twangboy** [comment]
Closing this issue due to age and lack of activity. Please test this on version 3006.2 and create a new issue if the problem persists. The new issue template has more information and will allow us to track and reproduce the issue more effectively. Thanks!
