### ISSUE TITLE
Wrong build causes UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4

### ISSUE THREAD

**Issue by markuskramerIgitt** [saltstack/salt#48467]
### Description of Issue/Question
Minion fails to start

c:\salt\var\log\salt\minion contains

```
2018-07-06 17:28:18,944 [salt.log.setup   :1196][ERROR   ][3488] An un-handled exception was caught by salt's global exception handler:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 11: ordinal not in range(128)
Traceback (most recent call last):
  File "c:\salt\bin\Scripts\salt-minion", line 26, in <module>
    salt_minion()
  File "c:\salt\bin\lib\site-packages\salt\scripts.py", line 175, in salt_minion
    minion.start()
  File "c:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 348, in start
    self.minion.tune_in()
  File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1029, in tune_in
    self._spawn_minions()
  File "c:\salt\bin\lib\site-packages\salt\minion.py", line 978, in _spawn_minions
    jid_queue=self.jid_queue,
  File "c:\salt\bin\lib\site-packages\salt\minion.py", line 959, in _create_minion_object
    jid_queue=jid_queue)
  File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1099, in __init__
    self.opts['grains'] = salt.loader.grains(opts)
  File "c:\salt\bin\lib\site-packages\salt\loader.py", line 735, in grains
    ret = funcs[key]()
  File "c:\salt\bin\lib\site-packages\salt\grains\core.py", line 2025, in locale_info
    grains['locale_info']['timezone'] = datetime.datetime.now(dateutil.tz.tzlocal()).tzname()
  File "c:\salt\bin\lib\site-packages\dateutil\tz\_common.py", line 22, in adjust_encoding
    name = name.encode()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 11: ordinal not in range(128)
```

### Setup
Build minion from develop.

### Steps to Reproduce Issue
Installed minion.
Started minion

### My guess 
Byte 0xe4 is at position 11 of "Mitteleuropäische Zeit" (Central European Time) represented as "Mitteleurop\xe4ische Zeit", which is my time zone.  [Guessed after](https://stackoverflow.com/questions/33295733/utf8-codec-cant-decode-byte-0xe4-invalid-continuation-byte-in-timezone)

How do I call `datetime.datetime.now(dateutil.tz.tzlocal()).tzname()`?

### Versions Report
Salt Version:
           Salt: 2018.3.0-616-g8731f42

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 7
         system: Windows
        version: 7 6.1.7601 SP1 Multiprocessor Free

**Comment by markuskramerIgitt** [comment]
I built minion 2018.3.0-618-gc0d4279 and got a different error, though also related to timezone:

```
2018-07-07 00:56:13,657 [salt.minion      :1014][CRITICAL][4000] Unexpected error while connecting to ************
Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt\minion.py", line 997, in _connect_minion
    yield minion.connect_master(failed=failed)
  File "c:\salt\bin\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "c:\salt\bin\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "c:\salt\bin\lib\site-packages\tornado\gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1189, in connect_master
    yield self._post_master_init(master)
  File "c:\salt\bin\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "c:\salt\bin\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "c:\salt\bin\lib\site-packages\tornado\gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1234, in _post_master_init
    cleanup=[master_event(type='alive')])
  File "c:\salt\bin\lib\site-packages\salt\utils\schedule.py", line 101, in __new__
    utils=utils)
  File "c:\salt\bin\lib\site-packages\salt\utils\schedule.py", line 147, in __singleton_init__
    self.time_offset = self.functions.get('timezone.get_offset', lambda: '0000')()
  File "c:\salt\bin\lib\site-packages\salt\modules\win_timezone.py", line 235, in get_offset
    tz_object = pytz.timezone(get_zone())
  File "c:\salt\bin\lib\site-packages\pytz\__init__.py", line 177, in timezone
    raise UnknownTimeZoneError(zone)
UnknownTimeZoneError: 'Unknown'

```


I built minion 2018.3.0-616-g8731f42 **with** build-caching.
I built minion 2018.3.0-618-gc0d4279  **without** build-caching.

I no longer consider build-caching (using variables SALTREPO_LOCAL_CACHE, SALT_REQ_LOCAL_CACHE, SALT_PIP_LOCAL_CACHE) safe, or useful. 
I introduced the concept but now I realize that it is flawed because manually curating a cache is unreliable. I will remove build-caching in a following pull request.

I close this issue because

  1) Minions 2018.3.0-618-gc0d4279 or 2018.3.0-618-gc0d4279 are from the **devellopment** branch, 
  2) I built minion 2018.3.2 (without build-caching) and it starts without error (especially no timezone error),
  3) Minion 2018.3.2 from the released installer starts without error.

**Comment by cruscio** [comment]
Hey @markuskramerIgitt - I just ran into this error with Salt-Minion-2018.3.3-Py2-AMD64-Setup.exe from repo.saltstack.com on Windows Server 2008 R2. Can we reopen this issue or should I log my own?

```
 Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.4
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: 2.0.4
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2008ServerR2
         system: Windows
        version: 2008ServerR2 6.1.7601 SP1 Multiprocessor Free
```

**Comment by markuskramerIgitt** [comment]
Hi @cruscio 
This issue is about my own errors in building a pip cache.
I am surprised the official installer has this problem

I have no time to install a new client: please attach your c:\salt\var\log\salt\minion

**Comment by cruscio** [comment]
Saved the error, but I didn't save the log. I'll see if I can reproduce it later and update this issue

```
[CRITICAL] Unexpected error while connecting to {{master}}
Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt\minion.py", line 997, in _connect_minion
    yield minion.connect_master(failed=failed)
  File "c:\salt\bin\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "c:\salt\bin\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "c:\salt\bin\lib\site-packages\tornado\gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1189, in connect_master
    yield self._post_master_init(master)
  File "c:\salt\bin\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "c:\salt\bin\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "c:\salt\bin\lib\site-packages\tornado\gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1234, in _post_master_init
    cleanup=[master_event(type='alive')])
  File "c:\salt\bin\lib\site-packages\salt\utils\schedule.py", line 88, in __new__
    cls.instance.__singleton_init__(opts, functions, returners, intervals, cleanup, proxy, utils, standalone)
  File "c:\salt\bin\lib\site-packages\salt\utils\schedule.py", line 115, in __singleton_init__
    self.time_offset = self.functions.get('timezone.get_offset', lambda: '0000')()
  File "c:\salt\bin\lib\site-packages\salt\modules\win_timezone.py", line 235, in get_offset
    tz_object = pytz.timezone(get_zone())
  File "c:\salt\bin\lib\site-packages\pytz\__init__.py", line 177, in timezone
    raise UnknownTimeZoneError(zone)
UnknownTimeZoneError: 'Unknown'
```

**Comment by zbarr** [comment]
Can this be reopened? I am seeing this also on 2018.3.3.

**Comment by markuskramerIgitt** [comment]
@zbarr, I just compiled Salt-Minion-v2018.3.3-Py2-AMD64-Setup.exe and run smoke tests -- I found no problems, and the log file is clean.

You could have a look at [these steps how to build the Salt-Minion exe installer](https://github.com/markuskramerIgitt/salt-windows-msi#build-the-exe-installer)

What do you see?

**Comment by markuskramerIgitt** [comment]
@cruscio, how is your situation?

**Comment by markuskramerIgitt** [comment]
@cruscio, please open a new issue, if needed.

This issue is tied to a wrong and outdated (and written-by-me) build method.
