### ISSUE TITLE
CloudError: Azure Error: LocationRequired

### ISSUE THREAD

**Issue by diepes** [saltstack/salt#48463]
### Description of Issue/Question
Azure config to create a server, working on salt-cloud 2018.3.2 , after commenting out 
`#availability_set: INF` 
Now trying same config on **developement** branch, and it fails with the error below, probably due to using new azure-api ?

_CloudError: Azure Error: LocationRequired_

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

```
$ cat /etc/salt/cloud.maps.d/AEA01/azure_pieter-INF.conf
#20180703 single server for testing.
azure_vm_pieter_UBUNTU14_CPU4_RAM8_HDD16:
  - ALL03INF01AEA01:
      minion:
        master: 10.10.2.4
        tcp_keepalive: True
        tcp_keepalive_idle: 180
        mysql.default_file: '/etc/mysql/debian.cnf'
      grains:
        environment: INF01AEA01
        role:
          - tomcat
          - mongodb
          - microservices
          - esb
          - mysql
          - microservices
        mysql_role: primary
        mongodb_role: primary

```

```
$ cat /etc/salt/cloud.profiles.d/azure_pieter-AEA01.conf 
azure_vm_pieter_UBUNTU14_CPU4_RAM8_HDD16:
  provider: azurearm_pieter-conf
  image: Canonical|UbuntuServer|14.04.5-LTS|14.04.201806270
  size: Standard_DS2_v2
  location: Australia East
  ssh_username: xxxxx
  ssh_password: xxxxx
  #storage_resource_group: INFRA-STORAGE
  storage_resource_group: INF
  storage_account: inf01nsp
  resource_group: INF
  # security_group: $nsgname
  network_resource_group: INFRA-VNET
  network: VNET-INFRASTRUCTURE
  subnet: INF
  public_ip: False

  #availability_set: INF

```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

salt-cloud -l debug -m /etc/salt/cloud.maps.d/AEA01/azure_pieter-INF.conf
```
...
...
[DEBUG   ] Configuring proxies: u''
[DEBUG   ] Evaluate proxies against ENV settings: True
[DEBUG   ] Configuring redirects: allow=True, max=30
[DEBUG   ] Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
[DEBUG   ] Starting new HTTPS connection (1): management.azure.com:443
[DEBUG   ] https://management.azure.com:443 "GET /subscriptions/44xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx9c/resourceGroups/INFRA-VNET/providers/Microsoft.Network/virtualNetworks/VNET-INFRASTRUCTURE/subnets/INF?api-version=2018-02-01 HTTP/1.1" 200 None
[DEBUG   ] Accept header absent and forced to application/json
[DEBUG   ] Configuring request: timeout=100, verify=True, cert=None
[DEBUG   ] Configuring proxies: u''
[DEBUG   ] Evaluate proxies against ENV settings: True
[DEBUG   ] Configuring redirects: allow=True, max=30
[DEBUG   ] Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
[DEBUG   ] Starting new HTTPS connection (1): management.azure.com:443
[DEBUG   ] https://management.azure.com:443 "PUT /subscriptions/44xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx9c/resourceGroups/INFRA-VNET/providers/Microsoft.Network/networkInterfaces/ALL03INF01AEA01-iface0?api-version=2018-02-01 HTTP/1.1" 400 104
[DEBUG   ] The location property is required for this definition.
[ERROR   ] There was a query error: Azure Error: LocationRequired
Message: The location property is required for this definition.
Traceback (most recent call last):
  File "/home/pieter/git/salt/salt/cloud/cli.py", line 343, in run
    ret = mapper.run_map(dmap)
  File "/home/pieter/git/salt/salt/cloud/__init__.py", line 2237, in run_map
    profile, local_master=local_master
  File "/home/pieter/git/salt/salt/cloud/__init__.py", line 1284, in create
    output = self.clouds[func](vm_)
  File "/home/pieter/git/salt/salt/cloud/clouds/azurearm.py", line 1385, in create
    vm_request = request_instance(vm_=vm_)
  File "/home/pieter/git/salt/salt/cloud/clouds/azurearm.py", line 986, in request_instance
    kwargs=vm_
  File "/home/pieter/git/salt/salt/cloud/clouds/azurearm.py", line 872, in create_network_interface
    kwargs['resource_group'], kwargs['iface_name'], iface_params
  File "/home/pieter/git/salt/local/lib/python2.7/site-packages/azure/mgmt/network/v2018_02_01/operations/network_interfaces_operations.py", line 275, in create_or_update
    **operation_config
  File "/home/pieter/git/salt/local/lib/python2.7/site-packages/azure/mgmt/network/v2018_02_01/operations/network_interfaces_operations.py", line 229, in _create_or_update_initial
    raise exp
CloudError: Azure Error: LocationRequired
Message: The location property is required for this definition.

```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
$ salt --versions-report
Salt Version:
           Salt: 2018.3.0-416-gc68f5b4
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15rc1 (default, Apr 15 2018, 21:51:34)
   python-gnupg: Not Installed
         PyYAML: 4.2
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.6
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.17.2-041702-lowlatency
         system: Linux
        version: Ubuntu 18.04 bionic
 
(salt) ✔ ~/git/salt [develop|…1] 

```

**Comment by diepes** [comment]
using pudb, and printing the request with 
`open('/tmp/pes-debug.txt','a').write('{}\n{}\n{}\n\n{}'.format('-----------START-----------',req.method + ' ' + req.url,'\n'.join('{}: {}'.format(k, v) for k, v in req.headers.items()),req.data,  ))`

I got the request that fail's, sanitized a bit.
```
-----------START-----------
PUT https://management.azure.com/subscriptions/44fd9d24-0993-420f-bb46-861fbd85bc9c/resourceGroups/INFRA-VNET/providers/Microsoft.Network/networkInterfaces/ALL03INF01AEA01-iface0?api-version=2018-02-01
Content-Type: application/json; charset=utf-8
Content-Length: 604
accept-language: en-US
x-ms-client-request-id: 1xxxxxxx-xxxx-xxxx-xxxx-00xxxx0xxxx0
Accept: application/json

{"properties": {"ipConfigurations": [{"name": "ALL03INF01AEA01-iface0-ip", "properties": {"subnet": {"id": "/subscriptions/44xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/INFRA-VNET/providers/Microsoft.Network/virtualNetworks/VNET-INFRASTRUCTURE/subnets/INF", "etag": "W/\"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx\"", "properties": {"addressPrefix": "10.10.3.0/24", "serviceEndpoints": [{"locations": ["australiaeast", "australiasoutheast"], "service": "Microsoft.Storage", "provisioningState": "Succeeded"}], "provisioningState": "Succeeded"}, "name": "INF"}, "privateIPAllocationMethod": "Dynamic"}}]}}
```

**Comment by diepes** [comment]
Updated to latest dev branch.  
(Big update https://github.com/saltstack/salt/pull/47566 )
time salt-cloud -l debug -m /etc/salt/cloud.maps.d/AEA01/azure_pieter-INF.conf
Got same error 
```
CloudError: Azure Error: LocationRequired
Message: The location property is required for this definition.
```

added a location to my  provider file.
```
$ cat /etc/salt/cloud.providers.d/azure-pieter.conf 
azurearm_pieter-conf:
  driver: azurearm
  subscription_id: xxxx
  client_id: xxxx
  secret: xxxx
  tenant: xxxx

  location: australiaeast
```

try again.
now i get a new error.  I suggest we close this ticket and i will log a new one for the new error.

```
[DEBUG   ] Invoking 0 token response hooks.
[DEBUG   ] Obtained token {u'resource': u'https://management.core.windows.net/', u'access_token': u'xxxxxxxxxxxx_1142char_xxxxxxxxxxxx', u'ext_expires_in': u'0', u'expires_in': u'3599', u'expires_at': 1531261481.003758, u'token_type': u'Bearer', u'not_before': u'1531257581', u'expires_on': u'1531261481'}.
[DEBUG   ] Accept header absent and forced to application/json
[DEBUG   ] Configuring request: timeout=100, verify=True, cert=None
[DEBUG   ] Configuring proxies: u''
[DEBUG   ] Evaluate proxies against ENV settings: True
[DEBUG   ] Configuring redirects: allow=True, max=30
[DEBUG   ] Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
[DEBUG   ] Starting new HTTPS connection (1): management.azure.com:443
[DEBUG   ] https://management.azure.com:443 "GET /subscriptions/44xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/INFRA-VNET/providers/Microsoft.Network/networkInterfaces/ALL03INF01AEA01-iface0?api-version=2018-02-01 HTTP/1.1" 200 None
[ERROR   ] There was a query error: __init__() takes exactly 1 argument (2 given)
Traceback (most recent call last):
  File "/home/pieter/git/salt/salt/cloud/cli.py", line 343, in run
    ret = mapper.run_map(dmap)
  File "/home/pieter/git/salt/salt/cloud/__init__.py", line 2237, in run_map
    profile, local_master=local_master
  File "/home/pieter/git/salt/salt/cloud/__init__.py", line 1284, in create
    output = self.clouds[func](vm_)
  File "/home/pieter/git/salt/salt/cloud/clouds/azurearm.py", line 1385, in create
    vm_request = request_instance(vm_=vm_)
  File "/home/pieter/git/salt/salt/cloud/clouds/azurearm.py", line 1312, in request_instance
    NetworkInterfaceReference(vm_['iface_id']),
TypeError: __init__() takes exactly 1 argument (2 given)

real	0m41.557s
user	0m8.827s
sys	0m1.323s
```
