### ISSUE TITLE
pkgrepo.manage is broken 2018.3.2

### ISSUE THREAD

**Issue by nhatfield** [saltstack/salt#48560]
### Description of Issue/Question
pkgrepo.manage is broken:

`'pkgrepo' __virtual__ returned False`

### Setup
```
sensu-repo:
  pkgrepo.managed:
    - name: sensu
    - humanname: sensu-main
    - baseurl: http://sensu.global.ssl.fastly.net/yum/6/$basearch/
    - gpgcheck: 0
    - disabled: false
    - require_in:
      - pkg: sensu
      - cmd: refresh-sensu-repo
    - require:
      - sls: common.hostname
```

### Steps to Reproduce Issue
`salt 'host01*' state.apply sensu -l debug`

```
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/99-master.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/99-master.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: master.company.com
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/99-master.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/99-master.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: master.company.com
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/master', u'master.company.com_master', u'tcp://127.0.0.1:4506', u'clear')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://127.0.0.1:4506
[DEBUG   ] Trying to connect to: tcp://127.0.0.1:4506
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/f4/6467bfcfe4641fede209b6ec39bed083572bb75cc7d5b2b828ec4becc4c3ff/.minions.p
[DEBUG   ] get_iter_returns for jid 20180712183443388291 sent to set(['host01.company.com']) will timeout at 18:36:13.406768
[DEBUG   ] jid 20180712183443388291 return from host01.company.com
[DEBUG   ] return event:
```
```
----------
          ID: sensu-repo
    Function: pkgrepo.managed
        Name: sensu
      Result: False
     Comment: State 'pkgrepo.managed' was not found in SLS 'sensu.client'
              Reason: 'pkgrepo' __virtual__ returned False
     Changes:
```

### Versions Report
`salt --versions-report`

```
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.7.0
       dateutil: 2.6.1
      docker-py: 1.10.6
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, May  2 2018, 18:31:34)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 4.14.51-60.38.amzn1.x86_64
         system: Linux
        version: Not Installed
```

**Comment by Ch3LL** [comment]
I can't replicate this on centos 7. can you run on your minion `salt-call --local pkg.list_pkgs -ldebug` and paste sanitized version here. It should print out the reason for not loading.

**Comment by nhatfield** [comment]
`salt-call --local pkg.list_pkgs -l debug`
```
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/99-master-address.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/99-master-address.conf
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: host01.company.com
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/99-master-address.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/99-master-address.conf
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Failed to import grains docker_info:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1461, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/var/cache/salt/minion/extmods/grains/docker_info.py", line 12, in <module>
    import docker
ImportError: No module named docker
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[DEBUG   ] Loading static grains from /etc/salt/grains
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[WARNING ] /usr/lib/python2.7/dist-packages/salt/modules/yumpkg.py:541: DeprecationWarning: Use of 'salt.utils.alias_function' detected. This function has been moved to 'salt.utils.functools.alias_function' as of Salt 2018.3.0. This warning will be removed in Salt Neon.

[ERROR   ] Failed to import module kernelpkg_linux_yum, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1461, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/usr/lib/python2.7/dist-packages/salt/modules/kernelpkg_linux_yum.py", line 17, in <module>
    import salt.modules.yumpkg
  File "/usr/lib/python2.7/dist-packages/salt/modules/yumpkg.py", line 2866, in <module>
    @decorators.which('yumdownloader')
AttributeError: 'module' object has no attribute 'which'
[WARNING ] /usr/lib/python2.7/dist-packages/salt/modules/yumpkg.py:541: DeprecationWarning: Use of 'salt.utils.alias_function' detected. This function has been moved to 'salt.utils.functools.alias_function' as of Salt 2018.3.0. This warning will be removed in Salt Neon.

[ERROR   ] Failed to import module yumpkg, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1461, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/usr/lib/python2.7/dist-packages/salt/modules/yumpkg.py", line 2866, in <module>
    @decorators.which('yumdownloader')
AttributeError: 'module' object has no attribute 'which'
[DEBUG   ] Failed to import module swarm:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1461, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/var/cache/salt/minion/extmods/modules/swarm.py", line 12, in <module>
    import docker
ImportError: No module named docker
[DEBUG   ] LazyLoaded boto3.assign_funcs
[DEBUG   ] LazyLoaded boto.assign_funcs
[DEBUG   ] LazyLoaded systemd.booted
[DEBUG   ] DSC: Only available on Windows systems
[DEBUG   ] Module PSGet: Only available on Windows systems
[DEBUG   ] Could not LazyLoad pkg.list_pkgs: 'pkg.list_pkgs' is not available.
'pkg.list_pkgs' is not available.
```

**Comment by nhatfield** [comment]
I got it figured out now, ty
