### ISSUE TITLE
restartcheck module failing if kernel-version scheme contains more than 3 dots 

### ISSUE THREAD

**Issue by maltris** [saltstack/salt#48569]
### Description of Issue/Question
Looks like the problem lays in 

https://github.com/saltstack/salt/blob/9fbe6d5d486886772d2c26b20c911d09eedcd950/salt/modules/restartcheck.py#L273

As with the longer version-string the rsplit splits the ".1" and not ".43~16.04.1" (check the examples below).

### Setup
Working:
```
# apt-cache policy linux-image-4.4.0-112-generic
linux-image-4.4.0-112-generic:
  Installed: 4.4.0-112.135
  Candidate: 4.4.0-112.135
  Version table:
 *** 4.4.0-112.135 500
```

Not working:
```
# apt-cache policy linux-image-4.13.0-38-generic
linux-image-4.13.0-38-generic:
  Installed: 4.13.0-38.43~16.04.1
  Candidate: 4.13.0-38.43~16.04.1
  Version table:
 *** 4.13.0-38.43~16.04.1 500
```

### Steps to Reproduce Issue
```
salt 'node' restartcheck.restartcheck

    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1476, in _thread_return
        return_data = executor.execute()
      File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/restartcheck.py", line 323, in restartcheck
        kernel_versions = _kernel_versions_debian()
      File "/usr/lib/python2.7/dist-packages/salt/modules/restartcheck.py", line 268, in _kernel_versions_debian
        kernel_ubuntu_generic = kernel_v[0] + '-generic #' + kernel_v[1]
    IndexError: list index out of range
```

### Versions Report
```
Salt Version:
           Salt: 2017.7.6
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.3.7
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: ISO-8859-1
        machine: x86_64
        release: 4.4.0-127-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by Ch3LL** [comment]
looks like you might have an idea of a fix. Want to take a stab at a PR?
