### ISSUE TITLE
Help : Custom SDB module and GITFS

### ISSUE THREAD

**Issue by Poil** [saltstack/salt#48603]
Hi,

I've wrote a custom SDB module to interact with PHPIPAM.
I've put it in a folder "_sdb" at the root path of my top-formula that is in a GITFS.

When running `salt '*' saltutil.sync_sdb` the SDB module is sync and present on the filesystem `/var/cache/salt/master/gitfs/refs/base/_sdb/rest_auth.py`

But when running `salt-run sdb.get "sdb://phpipam-api/post-free-ip?subnet_id=111"` the module does not seem to be found

```
Exception occurred in runner sdb.get: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 387, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/runners/sdb.py", line 27, in get
    return salt.utils.sdb.sdb_get(uri, __opts__, __utils__)
  File "/usr/lib/python2.7/site-packages/salt/utils/sdb.py", line 46, in sdb_get
    return loaded_db[fun](query, profile=profile)
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1143, in __getitem__
    func = super(LazyLoader, self).__getitem__(item)
  File "/usr/lib/python2.7/site-packages/salt/utils/lazy.py", line 104, in __getitem__
    raise KeyError(key)
KeyError: u'rest_auth.get'
```

I've tried to rename my module filename to rest-auth.py but no changes, also the old filename doesn't seem to be purged via the commands `fileserver.update` and `saltutil.sync_sdb`

I've also tried the example from the book "Extending Saltstack" but I've the same error.
Also, when I copy my `rest_auth.py` in `/usr/lib/python2.7/site-packages/salt/sdb` all is working fine

Am I missing a configuration on my master like ext_pillar or something like that ?

Best regards,

**Comment by garethgreenaway** [comment]
@Poil Thanks for the report.  Can you provide the code for your custom SDB module?

**Comment by Poil** [comment]
Here is the code

```python
# import python libs
from __future__ import absolute_import, print_function, unicode_literals
import logging

try:
    from urllib.parse import unquote
except:
    from urllib import unquote

import salt.loader
import salt.utils.http as http
from salt.template import compile_template

log = logging.getLogger(__name__)

__func_alias__ = {
    'set_': 'set'
}


def set_(key, value, service=None, profile=None):  # pylint: disable=W0613
    '''
    Set a key/value pair in the REST interface
    '''
    return query(key, value, service, profile)


def get(key, service=None, profile=None):  # pylint: disable=W0613
    '''
    Get a value from the REST interface
    '''
    return query(key, None, service, profile)


def query(key, value=None, service=None, profile=None):  # pylint: disable=W0613
    '''
    Get a value from the REST interface
    '''
    try:
        key, query_string = key.split('?')
        key_vars = {}
        if query_string:
            for pair in query_string.split('&'):
                pair_key, pair_val = pair.split('=')
                key_vars[pair_key] = unquote(pair_val)
    except:
        key_vars = {}

    renderer = __opts__.get('renderer', 'yaml_jinja')
    rend = salt.loader.render(__opts__, {})
    blacklist = __opts__.get('renderer_blacklist')
    whitelist = __opts__.get('renderer_whitelist')
    url = compile_template(
        ':string:',
        rend,
        renderer,
        blacklist,
        whitelist,
        input_data=profile[key]['url'],
        **key_vars
    )

    extras = {}
    for item in profile[key]:
        if item not in ('backend', 'url', 'auth_url', 'auth_username', 'auth_password', 'auth_token_header_name', 'auth_token_return_key'):
            extras[item] = profile[key][item]

    if 'auth_url' in profile[key]:
        result = http.query(
            profile[key]['auth_url'],
            profile[key].get('auth_method', 'GET'),
            username=profile[key]['auth_username'],
            password=profile[key]['auth_password'], decode=True)
        token = result['dict']['data'].get(profile[key]['auth_token_return_key'])
        if 'header_dict' in extras:
            extras['header_dict'][profile[key]['auth_token_header_name']] = token
        else:
            extras['header_dict'] = {profile[key]['auth_token_header_name']: token}

    result = http.query(
        url,
        decode=True,
        **extras
    )
    return result['dict']
```

**Comment by gcamblin** [comment]
I am getting the same error with a custom sdb module I've written for mysql. Has anyone been able to resolve this?
