### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0xfe in position 0: invalid start byte

### ISSUE THREAD

**Issue by diepes** [saltstack/salt#48642]
### Description of Issue/Question
salt-call thowing a error with no indication of where the problem is

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
vagrant vm

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
`
vagrant@localsandbox:~$ time sudo salt-call --state_verbose=False --log-level=info state.apply common.syslog
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
UnicodeDecodeError: 'utf8' codec can't decode byte 0xfe in position 0: invalid start byte
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 400, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 212, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 748, in apply_
    return sls(mods, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 1234, in sls
    initial_pillar=_get_initial_pillar(opts))
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 4037, in __init__
    BaseHighState.__init__(self, opts)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2902, in __init__
    self.opts = self.__gen_opts(opts)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2929, in __gen_opts
    mopts = self.client.master_opts()
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 1387, in master_opts
    return salt.utils.data.decode(self.channel.send(load)) if six.PY2 \
  File "/usr/lib/python2.7/dist-packages/salt/utils/data.py", line 105, in decode
    preserve_dict_class, preserve_tuples, to_str)
  File "/usr/lib/python2.7/dist-packages/salt/utils/data.py", line 171, in decode_dict
    preserve_dict_class, preserve_tuples, to_str)
  File "/usr/lib/python2.7/dist-packages/salt/utils/data.py", line 171, in decode_dict
    preserve_dict_class, preserve_tuples, to_str)
  File "/usr/lib/python2.7/dist-packages/salt/utils/data.py", line 171, in decode_dict
    preserve_dict_class, preserve_tuples, to_str)
  File "/usr/lib/python2.7/dist-packages/salt/utils/data.py", line 174, in decode_dict
    value = _decode_func(value, encoding, errors, normalize)
  File "/usr/lib/python2.7/dist-packages/salt/utils/stringutils.py", line 124, in to_unicode
    return _normalize(s.decode(__salt_system_encoding__, errors))
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xfe in position 0: invalid start byte
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 400, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 212, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 748, in apply_
    return sls(mods, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 1234, in sls
    initial_pillar=_get_initial_pillar(opts))
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 4037, in __init__
    BaseHighState.__init__(self, opts)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2902, in __init__
    self.opts = self.__gen_opts(opts)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2929, in __gen_opts
    mopts = self.client.master_opts()
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 1387, in master_opts
    return salt.utils.data.decode(self.channel.send(load)) if six.PY2 \
  File "/usr/lib/python2.7/dist-packages/salt/utils/data.py", line 105, in decode
    preserve_dict_class, preserve_tuples, to_str)
  File "/usr/lib/python2.7/dist-packages/salt/utils/data.py", line 171, in decode_dict
    preserve_dict_class, preserve_tuples, to_str)
  File "/usr/lib/python2.7/dist-packages/salt/utils/data.py", line 171, in decode_dict
    preserve_dict_class, preserve_tuples, to_str)
  File "/usr/lib/python2.7/dist-packages/salt/utils/data.py", line 171, in decode_dict
    preserve_dict_class, preserve_tuples, to_str)
  File "/usr/lib/python2.7/dist-packages/salt/utils/data.py", line 174, in decode_dict
    value = _decode_func(value, encoding, errors, normalize)
  File "/usr/lib/python2.7/dist-packages/salt/utils/stringutils.py", line 124, in to_unicode
    return _normalize(s.decode(__salt_system_encoding__, errors))
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xfe in position 0: invalid start byte

real	0m4.449s
user	0m3.790s
sys	0m0.776s
vagrant@localsandbox:~$

`
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
`
vagrant@localsandbox:/vagrant$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
vagrant@localsandbox:/vagrant$ 

`

`
vagrant@localsandbox:~$ salt-call --versions-report
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Nov 23 2017, 15:49:48)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
         locale: UTF-8
        machine: x86_64
        release: 3.13.0-139-generic
         system: Linux
        version: Ubuntu 14.04 trusty
 
vagrant@localsandbox:~$
`

**Comment by diepes** [comment]
I created an empty state  "salt/test/init.sls"  with just a comment "#" and got the same error.
Downgraded salt to 2017.7 latest version and no errors.
Upgrade back to 2018.3.2 and get the error.

Will try to see if I can pinpoint something in the pillar causing the issue, the error does not seem to assist in finding the cause.

**Comment by diepes** [comment]
I seem to be caused by a binary file (jks keystore) gpg encrypted in the pillar.

Is this related to https://github.com/saltstack/salt/issues/46934

**Comment by Ch3LL** [comment]
that was fixed in >=2018.3.1

if you remove that binary file from teh pillar it works?

**Comment by diepes** [comment]
Yes if i exclude that pillar for inclusion it works.
Plan to just remove the binary from the pillar, it was a bad idea.
