### ISSUE TITLE
archive module(s) fail when extracting unicode filenames

### ISSUE THREAD

**Issue by soostdijck** [saltstack/salt#48684]
### Description of Issue/Question

When I use `archive.extracted` to unzip files with unicode in their filenames (russian) things break.

**trace:**
```
          ID: statapp-static-zip
    Function: archive.extracted
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1905, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1830, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/archive.py", line 1003, in extracted
                  verbose=True)
                File "/usr/lib/python2.7/site-packages/salt/modules/archive.py", line 419, in list_
                  if x.count('/') == 0]
              UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 5: ordinal not in range(128)
     Started: 10:58:13.901653
    Duration: 1477.659 ms
```

### Setup
**state stanza example:**
```
statapp-static-zip:
  archive.extracted:
    - name: '{{statstatic.static_dir}}_tmp/'
    - source: salt://jenkins-builds/{{statstatic.jenkins_static_zip}}
    - overwrite: True
    - enforce_toplevel: False
```

### Steps to Reproduce Issue
Create a tar.gz with russian filenames in it, extract it with archive.extracted or the execution module...

### Versions Report
```
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.21.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

**Comment by gtmanfred** [comment]
@terminalmage can you take a look at this?

Thanks,
Daniel

**Comment by rallytime** [comment]
Hey @soostdijck - Can you test this on the 2018.3 branch? I think @garethgreenaway already fixeded this with #47572.

**Comment by soostdijck** [comment]
@rallytime I'm not sure what you mean, I ran into this on 2018.3.2 That other bug #47572 was fixed and merged before .2 came out from what I can tell?

**Comment by rallytime** [comment]
@soostdijck Ah, it's not in the 2018.3.2 release. We did a quick release with a limited number of fixes there, based on the 2018.3.1 release.

The fix in #47572 is in the 2018.3 branch, but won't be available until 2018.3.3.
