### ISSUE TITLE
Salt-API returns 500 instead of 401 for /minions

### ISSUE THREAD

**Issue by erwindon** [saltstack/salt#48703]
### Description of Issue/Question
I'm testing an application based on `salt-api/rest_cherrypy`. Part of the test is to revoke (not grant) access rights to specific api calls, and see how the application behaves. Most api calls return the expected http response code 401 (unauthorized). At least the `/minions` api call returns a http response code 500 (internal server error). This is never a valid outcome.

### Setup
Using a standard `rest_cherrypy` configuration, with the addition of `debug: true` so that a stacktrace becomes visible in `/var/log/salt/api` on internal errors. Using an `external_auth` that allows the application to use `pam`, but which contains no (relevant) access rights:
```
external_auth:
  pam:
    username:
      - dummy
```

### Steps to Reproduce Issue
Login using the salt-api/rest_cherrypy.
Perform api call "/minions" (see https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html#minions)
The rest call ends in response code 500.
Logfile `/var/log/salt/api` shows the following error:

```
2018-07-22 10:26:02,306 [cherrypy.error.139763866168848:216 ][ERROR   ][39603] [22/Jul/2018:10:26:02] HTTP 
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/salt/client/__init__.py", line 346, in run_job
    **kwargs)
  File "/usr/lib/python3.4/site-packages/salt/client/__init__.py", line 1857, in pub
    raise AuthorizationError(err_msg)
salt.exceptions.AuthorizationError: Authorization error occurred.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/salt/netapi/rest_cherrypy/app.py", line 858, in hypermedia_handler
    ret = cherrypy.serving.request._hypermedia_inner_handler(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python3.4/site-packages/salt/netapi/rest_cherrypy/app.py", line 1342, in GET
    token=cherrypy.session.get('token'))),
  File "/usr/lib/python3.4/site-packages/salt/netapi/rest_cherrypy/app.py", line 1178, in exec_lowstate
    ret = self.api.run(chunk)
  File "/usr/lib/python3.4/site-packages/salt/netapi/__init__.py", line 75, in run
    return l_fun(*f_call.get('args', ()), **f_call.get('kwargs', {}))
  File "/usr/lib/python3.4/site-packages/salt/netapi/__init__.py", line 103, in local
    return local.cmd(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/salt/client/__init__.py", line 741, in cmd
    **kwargs)
  File "/usr/lib/python3.4/site-packages/salt/client/__init__.py", line 354, in run_job
    raise SaltClientError(general_exception)
salt.exceptions.SaltClientError: Authorization error occurred.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/salt/netapi/rest_cherrypy/app.py", line 892, in hypermedia_handler
    if cherrypy.config['debug']
  File "/usr/lib64/python3.4/traceback.py", line 256, in format_exc
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
  File "/usr/lib64/python3.4/traceback.py", line 181, in format_exception
    return list(_format_exception_iter(etype, value, tb, limit, chain))
  File "/usr/lib64/python3.4/traceback.py", line 153, in _format_exception_iter
    yield from _format_list_iter(_extract_tb_iter(tb, limit=limit))
  File "/usr/lib64/python3.4/traceback.py", line 18, in _format_list_iter
    for filename, lineno, name, line in extracted_list:
  File "/usr/lib64/python3.4/traceback.py", line 58, in _extract_tb_or_stack_iter
    while curr is not None and (limit is None or n < limit):
TypeError: unorderable types: int() < SaltClientError()
```` 

### Versions Report
```
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.10
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: 1.3.12
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.4.8 (default, Mar 23 2018, 10:04:27)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.3.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```

**Comment by Ch3LL** [comment]
seems we need to clean this up to ensure we are returning the correct error code.

fyi @saltstack/team-netapi

**Comment by erwindon** [comment]
ping

**Comment by twangboy** [comment]
Closing this issue due to age and lack of activity. Please test this on version 3006.2 and create a new issue if the problem persists. The new issue template has more information and will allow us to track and reproduce the issue more effectively. Thanks!
