### ISSUE TITLE
saltutil.sync_modules cause AuthenticationError: message authentication failed

### ISSUE THREAD

**Issue by Hitamashi** [saltstack/salt#48764]
### Description of Issue/Question
The issue occur when I sync the modules from syndic to my minions:
```
salt minion-1 saltutil.sync_modules
```
The minion will return a tracestack with the error: `AuthenticationError`

But it not happens for all my minions (This is the weird part). Even though, I use the same os image and with the same setup process.  

Some other modules like `cmd.run` or `test.ping` , `test.version` work fine.

I have tried to match the module version between master and syndic but it doesn't work.  
And I tried remove M2Crypto on my minion but it is still the same.

Could you please check it out for me?

### Setup
Simplify topology:
* Root master: salt-master
* Syndic: salt-minion + salt-master + salt-syndic
* Minion (RHEL7 from EC2 region us-east-2): salt-minion

**Master config**
```
auto_accept: True
order_masters: True
publish_port: 4515
ret_port: 4516

fileserver_backend:
  - s3fs
  - roots
### s3 config ... ###
```

**Syndic config**
```
### Master
syndic_master_port: 4516
syndic_master: root-master
fileserver_backend:
  - s3fs
  - roots

### Minion
publish_port: 4515
master_port: 4516
master: root-master
```
On syndic I have a custom module placed in `/srv/salt/_modules/lbn.py`  
The module works fine
```
from __future__ import absolute_import
import logging
import os

LOG = logging.getLogger(__name__)

# Module name
__virtualname__ = 'lbn'

# Check condition to load module
def __virtual__():
    return __virtualname__

def getall(*args, **kwargs):
    ret = {"test": True}  
    return ret
```

**Minion config**
```
master: syndic
root_dir:  #custom path#
pidfile:   /var/salt-minion.pid
pki_dir:   /var/pki
cachedir:  /var/cache
sock_dir:  /var/sock
log_file:  /var/log
log_level: debug
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
Deploy master, syndic and minions  
Accept minion key. Then run:
```
salt minion saltutil.sync_modules
```
The command return:
```
The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1476, in _thread_return
        return_data = executor.execute()
      File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/usr/lib/python2.7/site-packages/salt/modules/saltutil.py", line 310, in sync_modules
        ret = _sync('modules', saltenv, extmod_whitelist, extmod_blacklist)
      File "/usr/lib/python2.7/site-packages/salt/modules/saltutil.py", line 99, in _sync
        saltenv = _get_top_file_envs()
      File "/usr/lib/python2.7/site-packages/salt/modules/saltutil.py", line 80, in _get_top_file_envs
        initial_pillar=__pillar__)
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 3860, in __init__
        BaseHighState.__init__(self, opts)
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 2732, in __init__
        self.opts = self.__gen_opts(opts)
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 2759, in __gen_opts
        mopts = self.client.master_opts()
      File "/usr/lib/python2.7/site-packages/salt/fileclient.py", line 1338, in master_opts
        return self.channel.send(load)
      File "/usr/lib/python2.7/site-packages/salt/utils/async.py", line 65, in wrap
        ret = self._block_future(ret)
      File "/usr/lib/python2.7/site-packages/salt/utils/async.py", line 75, in _block_future
        return future.result()
      File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result
        raise_exc_info(self._exc_info)
      File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 876, in run
        yielded = self.gen.throw(*exc_info)
      File "/usr/lib/python2.7/site-packages/salt/transport/zeromq.py", line 312, in send
        ret = yield self._crypted_transfer(load, tries=tries, timeout=timeout, raw=raw)
      File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result
        raise_exc_info(self._exc_info)
      File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 876, in run
        yielded = self.gen.throw(*exc_info)
      File "/usr/lib/python2.7/site-packages/salt/transport/zeromq.py", line 284, in _crypted_transfer
        ret = yield _do_transfer()
      File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result
        raise_exc_info(self._exc_info)
      File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 879, in run
        yielded = self.gen.send(value)
      File "/usr/lib/python2.7/site-packages/salt/transport/zeromq.py", line 271, in _do_transfer
        data = self.auth.crypticle.loads(data, raw)
      File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 1308, in loads
        data = self.decrypt(data)
      File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 1277, in decrypt
        raise AuthenticationError('message authentication failed')
    AuthenticationError: message authentication failed
```

No special log on master and syndic. Just normal log with executing jobs
Log on minions (this is the log from my actual platform): 
```
2018-07-25 10:09:19,976 [salt.minion      :1307][INFO    ][14107] User root Executing command saltutil.sync_modules with jid 20180725100919907370
2018-07-25 10:09:19,976 [salt.minion      :1313][DEBUG   ][14107] Command details {'tgt_type': 'glob', 'jid': '20180725100919907370', 'tgt': 'SID-9a19f710-ac5b-117e-b59b-cfe96549c63c', 'ret': '', 'user': 'root', 'arg': [], 'fun': 'saltutil.sync_modules', 'master_id': 'salt-master-1'}
2018-07-25 10:09:19,990 [salt.minion      :1431][INFO    ][14493] Starting a new job with PID 14493
2018-07-25 10:09:20,002 [salt.utils.lazy  :97  ][DEBUG   ][14493] LazyLoaded saltutil.sync_modules
2018-07-25 10:09:20,002 [salt.utils.lazy  :97  ][DEBUG   ][14493] LazyLoaded direct_call.get
2018-07-25 10:09:20,007 [salt.transport.zeromq:125 ][DEBUG   ][14493] Initializing new AsyncZeroMQReqChannel for ('/usr/local/linkbynet/script/lbn-smith-agent/var/pki', 'SID-9a19f710-ac5b-117e-b59b-cfe96549c63c', 'tcp://127.0.0.1:4506', 'aes')
2018-07-25 10:09:20,008 [salt.crypt       :375 ][DEBUG   ][14493] Initializing new AsyncAuth for ('/usr/local/linkbynet/script/lbn-smith-agent/var/pki', 'SID-9a19f710-ac5b-117e-b59b-cfe96549c63c', 'tcp://127.0.0.1:4506')
2018-07-25 10:09:20,049 [salt.crypt       :1276][DEBUG   ][14493] Failed to authenticate message
2018-07-25 10:09:20,049 [salt.transport.zeromq:125 ][DEBUG   ][14493] Initializing new AsyncZeroMQReqChannel for ('/usr/local/linkbynet/script/lbn-smith-agent/var/pki', 'SID-9a19f710-ac5b-117e-b59b-cfe96549c63c', 'tcp://127.0.0.1:4506', 'clear')
2018-07-25 10:09:20,088 [salt.crypt       :757 ][DEBUG   ][14493] Decrypting the current master AES key
2018-07-25 10:09:20,089 [salt.crypt       :681 ][DEBUG   ][14493] Loaded minion key: /usr/local/linkbynet/script/lbn-smith-agent/var/pki/minion.pem
2018-07-25 10:09:20,101 [salt.crypt       :1276][DEBUG   ][14493] Failed to authenticate message
2018-07-25 10:09:20,102 [salt.minion      :1536][WARNING ][14493] The minion function caused an exception
2018-07-25 10:09:20,102 [salt.utils.event :314 ][DEBUG   ][14493] SaltEvent PUB socket URI: /usr/local/linkbynet/script/lbn-smith-agent/var/sock/minion_event_2b14e7e5f2_pub.ipc
2018-07-25 10:09:20,102 [salt.utils.event :317 ][DEBUG   ][14493] SaltEvent PULL socket URI: /usr/local/linkbynet/script/lbn-smith-agent/var/sock/minion_event_2b14e7e5f2_pull.ipc
2018-07-25 10:09:20,102 [salt.transport.ipc:255 ][DEBUG   ][14493] Initializing new IPCClient for path: /usr/local/linkbynet/script/lbn-smith-agent/var/sock/minion_event_2b14e7e5f2_pull.ipc
2018-07-25 10:09:20,103 [salt.utils.event :729 ][DEBUG   ][14493] Sending event: tag = _salt_error; data = {'message': u'The minion function caused an exception', 'args': ('The minion function caused an exception',), '_stamp': '2018-07-25T10:09:20.103893'}
2018-07-25 10:09:20,106 [salt.minion      :1156][DEBUG   ][14493] Minion return retry timer set to 8 seconds (randomized)
2018-07-25 10:09:20,106 [salt.minion      :1708][INFO    ][14493] Returning information for job: 20180725100919907370
2018-07-25 10:09:20,106 [salt.transport.zeromq:125 ][DEBUG   ][14493] Initializing new AsyncZeroMQReqChannel for ('/usr/local/linkbynet/script/lbn-smith-agent/var/pki', 'SID-9a19f710-ac5b-117e-b59b-cfe96549c63c', 'tcp://127.0.0.1:4506', 'aes')
2018-07-25 10:09:20,107 [salt.crypt       :375 ][DEBUG   ][14493] Initializing new AsyncAuth for ('/usr/local/linkbynet/script/lbn-smith-agent/var/pki', 'SID-9a19f710-ac5b-117e-b59b-cfe96549c63c', 'tcp://127.0.0.1:4506')
2018-07-25 10:09:20,110 [salt.minion      :2000][DEBUG   ][14107] Minion of "127.0.0.1" is handling event tag '_salt_error'
2018-07-25 10:09:20,110 [salt.minion      :2163][DEBUG   ][14107] Forwarding salt error event tag=_salt_error
2018-07-25 10:09:20,110 [salt.transport.zeromq:125 ][DEBUG   ][14107] Initializing new AsyncZeroMQReqChannel for ('/usr/local/linkbynet/script/lbn-smith-agent/var/pki', 'SID-9a19f710-ac5b-117e-b59b-cfe96549c63c', 'tcp://127.0.0.1:4506', 'aes')
2018-07-25 10:09:20,111 [salt.crypt       :375 ][DEBUG   ][14107] Initializing new AsyncAuth for ('/usr/local/linkbynet/script/lbn-smith-agent/var/pki', 'SID-9a19f710-ac5b-117e-b59b-cfe96549c63c', 'tcp://127.0.0.1:4506')
2018-07-25 10:09:20,255 [salt.crypt       :1276][DEBUG   ][14493] Failed to authenticate message
2018-07-25 10:09:20,255 [salt.transport.zeromq:125 ][DEBUG   ][14493] Initializing new AsyncZeroMQReqChannel for ('/usr/local/linkbynet/script/lbn-smith-agent/var/pki', 'SID-9a19f710-ac5b-117e-b59b-cfe96549c63c', 'tcp://127.0.0.1:4506', 'clear')
2018-07-25 10:09:20,350 [salt.crypt       :757 ][DEBUG   ][14493] Decrypting the current master AES key
2018-07-25 10:09:20,352 [salt.crypt       :681 ][DEBUG   ][14493] Loaded minion key: /usr/local/linkbynet/script/lbn-smith-agent/var/pki/minion.pem
2018-07-25 10:09:20,367 [salt.minion      :1575][DEBUG   ][14493] minion return: {'fun_args': [], 'jid': '20180725100919907370', 'return': 'The minion function caused an exception: Traceback (most recent call last):\n  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1476, in _thread_return\n    return_data = executor.execute()\n  File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 28, in execute\n    return self.func(*self.args, **self.kwargs)\n  File "/usr/lib/python2.7/site-packages/salt/modules/saltutil.py", line 310, in sync_modules\n    ret = _sync(\'modules\', saltenv, extmod_whitelist, extmod_blacklist)\n  File "/usr/lib/python2.7/site-packages/salt/modules/saltutil.py", line 99, in _sync\n    saltenv = _get_top_file_envs()\n  File "/usr/lib/python2.7/site-packages/salt/modules/saltutil.py", line 80, in _get_top_file_envs\n    initial_pillar=__pillar__)\n  File "/usr/lib/python2.7/site-packages/salt/state.py", line 3860, in __init__\n    BaseHighState.__init__(self, opts)\n  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2732, in __init__\n    self.opts = self.__gen_opts(opts)\n  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2759, in __gen_opts\n    mopts = self.client.master_opts()\n  File "/usr/lib/python2.7/site-packages/salt/fileclient.py", line 1338, in master_opts\n    return self.channel.send(load)\n  File "/usr/lib/python2.7/site-packages/salt/utils/async.py", line 65, in wrap\n    ret = self._block_future(ret)\n  File "/usr/lib/python2.7/site-packages/salt/utils/async.py", line 75, in _block_future\n    return future.result()\n  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result\n    raise_exc_info(self._exc_info)\n  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 876, in run\n    yielded = self.gen.throw(*exc_info)\n  File "/usr/lib/python2.7/site-packages/salt/transport/zeromq.py", line 312, in send\n    ret = yield self._crypted_transfer(load, tries=tries, timeout=timeout, raw=raw)\n  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 870, in run\n    value = future.result()\n  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result\n    raise_exc_info(self._exc_info)\n  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 876, in run\n    yielded = self.gen.throw(*exc_info)\n  File "/usr/lib/python2.7/site-packages/salt/transport/zeromq.py", line 284, in _crypted_transfer\n    ret = yield _do_transfer()\n  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 870, in run\n    value = future.result()\n  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result\n    raise_exc_info(self._exc_info)\n  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 879, in run\n    yielded = self.gen.send(value)\n  File "/usr/lib/python2.7/site-packages/salt/transport/zeromq.py", line 271, in _do_transfer\n    data = self.auth.crypticle.loads(data, raw)\n  File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 1308, in loads\n    data = self.decrypt(data)\n  File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 1277, in decrypt\n    raise AuthenticationError(\'message authentication failed\')\nAuthenticationError: message authentication failed\n', 'success': False, 'fun': 'saltutil.sync_modules', 'master_id': 'salt-master-1', 'out': 'nested'}
```

### Versions Report
**Master**
```
Salt Version:
           Salt: 2017.7.7
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.4
      gitpython: 2.1.11
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: 0.24.5
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.3.7
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.2
         Python: 2.7.13 (default, Nov 24 2017, 17:33:09)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.4
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.5 
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.9.76-3.78.amzn1.x86_64
         system: Linux
        version: debian 9.5 
```

**Syndic**
```
Salt Version:
           Salt: 2017.7.7
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: 0.24.5
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.2
         Python: 2.7.13 (default, Nov 24 2017, 17:33:09)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.5 
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.9.77-31.58.amzn1.x86_64
         system: Linux
        version: debian 9.5 
```

**Minion**
```
Salt Version:
           Salt: 2017.7.7
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, May 31 2018, 09:41:32)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: redhat 7.5 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.5 Maipo
```

**Comment by gtmanfred** [comment]
I am unable to replicate this.

```
[root@saltmaster /]# salt-cp --chunked syndic* /srv/salt/_modules /srv/salt/
syndic1:
    ----------
    /srv/salt/_modules/lbn.py:
        True
syndic2:
    ----------
    /srv/salt/_modules/lbn.py:
        True
[root@saltmaster /]# salt syndic\* service.stop salt-minion
syndic1:
    True
syndic2:
    True
[root@saltmaster /]# salt \* saltutil.sync_modules
754a95a80cbe:
    - modules.lbn
9b97cce9c38c:
    - modules.lbn
```

Can you also provide your minion config?

Have you tried removing the port configurations and using the default salt ports?

Thanks,
Daniel

**Comment by Hitamashi** [comment]
@gtmanfred, I've already provided the minion config
```
master: syndic
root_dir:  #custom path#
pidfile:   /var/salt-minion.pid
pki_dir:   /var/pki
cachedir:  /var/cache
sock_dir:  /var/sock
log_file:  /var/log
log_level: debug
```
It is just some changes in the root directories.

For more info, the issues also occurred when I send `test.ping`. 
Here is the minion log when my `test.ping` failed: https://pastebin.com/aC3y2u1N

About the port configuration, I think it is not the problem because not all of my minions have this issues. 

Actually in my real platform, I have several syndics with exactly same config. But only unix minions under 1 syndic have this problem. The windows minion works well.

**Comment by Hitamashi** [comment]
Hello @gtmanfred ,
Any new progress?

On my part, I have to redeploy everything again. And the issue is gone. No modification is done.
Anyway, I will keep monitoring to check if it happens again.

Regards,

**Comment by gtmanfred** [comment]
Ok, thanks,

Yeah i was never able to reproduce this.  I wonder if it was an old pyc file left behind by something.

Let me know if you can reproduce it again, and I will reopen this issue.
