### ISSUE TITLE
Salt-ssh returns 

### ISSUE THREAD

**Issue by perfecto25** [saltstack/salt#48802]
### Description of Issue/Question

Running salt-ssh Target _test.ping_, results in an Import error (I think this may be related to Centos6, I ran the same test.ping command on Centos 7.5 and no issues.)

uname of box with issues: 
Linux atlas 2.6.32-642.4.2.el6.x86_64 #1 SMP Tue Aug 23 19:58:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

* btw, I can still run raw cmds on it

```
salt-ssh atlas -r "free -m"
atlas:
    ----------
    retcode:
        0
    stderr:
    stdout:
                     total       used       free     shared    buffers     cached
        Mem:        193696     172580      21116       2603       2467      60316
        -/+ buffers/cache:     109797      83899
        Swap:        19073       4867      14206
```

but modules dont work,

```
salt-ssh atlas test.ping
atlas:
    ----------
    retcode:
        0
    stderr:
        Traceback (most recent call last):
          File "/var/tmp/.root_356e09_salt/salt-call", line 15, in <module>
            salt_call()
          File "/var/tmp/.root_356e09_salt/py2/salt/scripts.py", line 395, in salt_call
            import salt.cli.call
          File "/var/tmp/.root_356e09_salt/py2/salt/cli/call.py", line 5, in <module>
            import salt.utils.parsers
          File "/var/tmp/.root_356e09_salt/py2/salt/utils/parsers.py", line 27, in <module>
            import salt.config as config
          File "/var/tmp/.root_356e09_salt/py2/salt/config/__init__.py", line 98, in <module>
            _DFLT_IPC_WBUFFER = _gather_buffer_space() * .5
          File "/var/tmp/.root_356e09_salt/py2/salt/config/__init__.py", line 88, in _gather_buffer_space
            import salt.grains.core
          File "/var/tmp/.root_356e09_salt/py2/salt/grains/core.py", line 44, in <module>
            import salt.utils.dns
          File "/var/tmp/.root_356e09_salt/py2/salt/utils/dns.py", line 32, in <module>
            import salt.modules.cmdmod
          File "/var/tmp/.root_356e09_salt/py2/salt/modules/cmdmod.py", line 34, in <module>
            import salt.utils.templates
          File "/var/tmp/.root_356e09_salt/py2/salt/utils/templates.py", line 32, in <module>
            import salt.utils.http
          File "/var/tmp/.root_356e09_salt/py2/salt/utils/http.py", line 41, in <module>
            import salt.loader
          File "/var/tmp/.root_356e09_salt/py2/salt/loader.py", line 28, in <module>
            import salt.utils.event
          File "/var/tmp/.root_356e09_salt/py2/salt/utils/event.py", line 70, in <module>
            import tornado.iostream
          File "/var/tmp/.root_356e09_salt/py2/tornado/iostream.py", line 40, in <module>
            from tornado.netutil import ssl_wrap_socket, ssl_match_hostname, SSLCertificateError, _client_ssl_defaults, _server_ssl_defaults
          File "/var/tmp/.root_356e09_salt/py2/tornado/netutil.py", line 56, in <module>
            import backports.ssl_match_hostname
        ImportError: No module named backports.ssl_match_hostname
    stdout:

```

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.27.2
        libnacl: Not Installed
       M2Crypto: 0.30.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.27.1
         Python: 2.7.15 (default, Jul 23 2018, 21:28:00)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 15.6.0
         system: Darwin
        version: 10.11.6 x86_64

**Comment by gtmanfred** [comment]
We should be handling this, if you install https://pypi.org/project/backports.ssl_match_hostname/ we should copy it over to the minion.

Daniel

**Comment by perfecto25** [comment]
my saltmaster already has this pkg installed, 


[root@saltmaster reactor]# pip freeze | grep ssl
You are using pip version 8.1.2, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
backports.ssl-match-hostname==3.5.0.1

**Comment by gtmanfred** [comment]
Hrm, it looks like it should always pack the ssl_match_hostname.

Can you try running this on your salt master and provide the output?

```
try:
    # Older python where the backport from pypi is installed
    from backports import ssl_match_hostname
    HAS_SSL_MATCH_HOSTNAME = True
    TYPE = 'PACKAGE'
except ImportError:
    # Other older python we use our bundled copy
    try:
        from salt.ext import ssl_match_hostname
        HAS_SSL_MATCH_HOSTNAME = True
        TYPE = 'SALT.EXT'
    except ImportError:
        HAS_SSL_MATCH_HOSTNAME = False
        TYPE = 'NONE'
print(HAS_SSL_MATCH_HOSTNAME, TYPE)
```

Also, are you running this on a mac?  can you pip install the package to the salt python directory? it should be in /opt/salt.

Thanks,
Daniel

**Comment by perfecto25** [comment]
master is centos 7.5

[root@saltmaster tmp]# cat test.py 
try:
    # Older python where the backport from pypi is installed
    from backports import ssl_match_hostname
    HAS_SSL_MATCH_HOSTNAME = True
    TYPE = 'PACKAGE'
except ImportError:
    # Other older python we use our bundled copy
    try:
        from salt.ext import ssl_match_hostname
        HAS_SSL_MATCH_HOSTNAME = True
        TYPE = 'SALT.EXT'
    except ImportError:
        HAS_SSL_MATCH_HOSTNAME = False
        TYPE = 'NONE'
print(HAS_SSL_MATCH_HOSTNAME, TYPE)

[root@saltmaster tmp]# python test.py 
(True, 'PACKAGE')

[root@saltmaster tmp]# cat /etc/redhat-release 
CentOS Linux release 7.5.1804 (Core)

**Comment by perfecto25** [comment]
I dont have anything in /opt

I have salt modules in /usr/lib,

```
[root@saltmaster tmp]# ls /usr/lib/python2.7/site-packages/salt/
acl          _compat.pyo    exceptions.pyc  __init__.py   log         output       roster       serializers    syspaths.pyc    textformat.pyo  version.pyc
auth         config         exceptions.pyo  __init__.pyc  master.py   payload.py   runner.py    spm            _syspaths.pyo   thorium         _version.pyo
beacons      crypt.py       executors       __init__.pyo  master.pyc  payload.pyc  runner.pyc   state.py       syspaths.pyo    tokens          version.pyo
cache        crypt.pyc      ext             key.py        master.pyo  payload.pyo  runner.pyo   state.pyc      template.py     tops            wheel
cli          crypt.pyo      fileclient.py   key.pyc       minion.py   pillar       runners      state.pyo      template.pyc    transport
client       daemons        fileclient.pyc  key.pyo       minion.pyc  proxy        scripts.py   states         template.pyo    utils
cloud        defaults       fileclient.pyo  loader.py     minion.pyo  queues       scripts.pyc  _syspaths.py   templates       _version.py
_compat.py   engines        fileserver      loader.pyc    modules     renderers    scripts.pyo  syspaths.py    textformat.py   version.py
_compat.pyc  exceptions.py  grains          loader.pyo    netapi      returners    sdb          _syspaths.pyc  textformat.pyc  _version.pyc
```

**Comment by gtmanfred** [comment]
Can you provide the version report from the machine you are on then?

Because the version report in the first comment of this issue is from a mac.

**Comment by perfecto25** [comment]
Oh sorry, I swtiched desktops since I opened this ticket,

The original error is gone now (running from Centos instead of Mac) when I run same command, but getting this

```
[root@saltmaster tmp]# salt-ssh atlas test.ping
atlas:
    ----------
    retcode:
        0
    stderr:
        Traceback (most recent call last):
          File "/var/tmp/.root_303cbc_salt/salt-call", line 15, in <module>
            salt_call()
          File "/var/tmp/.root_303cbc_salt/py2/salt/scripts.py", line 398, in salt_call
            client = salt.cli.call.SaltCall()
          File "/var/tmp/.root_303cbc_salt/py2/salt/utils/parsers.py", line 160, in __init__
            optparse.OptionParser.__init__(self, *args, **kwargs)
          File "/usr/local/lib/python2.7/optparse.py", line 1214, in __init__
            add_help=add_help_option)
          File "/var/tmp/.root_303cbc_salt/py2/salt/utils/parsers.py", line 241, in _populate_option_list
            self, option_list, add_help=add_help
          File "/usr/local/lib/python2.7/optparse.py", line 1258, in _populate_option_list
            self._add_version_option()
          File "/var/tmp/.root_303cbc_salt/py2/salt/utils/parsers.py", line 252, in _add_version_option
            help='Show program\'s dependencies version number and exit.'
          File "/usr/local/lib/python2.7/optparse.py", line 1018, in add_option
            raise TypeError, "invalid arguments"
        TypeError: invalid arguments
    stdout:

```

I opened up a separate Issue for this, 

https://github.com/saltstack/salt/issues/48820

You can close this one. 
Thanks.
