### ISSUE TITLE
Unicode error while deploying Ubuntu 18.04 template in VMware

### ISSUE THREAD

**Issue by 11chrisadams11** [saltstack/salt#48825]
### Description of Issue/Question
When deploying a new VMware server from a Ubuntu 18.04 template I get the following error: 
```UnicodeEncodeError: 'ascii' codec can't encode character u'\u2192' in position 274: ordinal not in range(128)```

The server is created, but Salt is not installed and the setup is not continued.

Here is the full trace:
```
The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1606, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/var/cache/salt/minion/extmods/modules/cloud_vmware.py", line 273, in create_instance
        create_success, create_error = _create_vm(hostname, profile, notes)
      File "/var/cache/salt/minion/extmods/modules/cloud_vmware.py", line 144, in _create_vm
        ret = CLOUD_CLIENT.profile(profile, names=[hostname], vm_overrides={'annotation': annotation})
      File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 354, in profile
        mapper.run_profile(profile, names, vm_overrides=vm_overrides)
      File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1454, in run_profile
        ret[name] = self.create(vm_)
      File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1284, in create
        output = self.clouds[func](vm_)
      File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/vmware.py", line 2808, in create
        out = __utils__['cloud.bootstrap'](vm_, __opts__)
      File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 566, in bootstrap
        deployed = deploy_script(**deploy_kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 1547, in deploy_script
        if root_cmd(deploy_command, tty, sudo, **ssh_kwargs) != 0:
      File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 2248, in root_cmd
        retcode = _exec_ssh_cmd(cmd, allow_failure=allow_failure, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 1809, in _exec_ssh_cmd
        stdout, stderr = proc.recv()
      File "/usr/lib/python2.7/dist-packages/salt/utils/vt.py", line 310, in recv
        return self._recv(maxsize)
      File "/usr/lib/python2.7/dist-packages/salt/utils/vt.py", line 688, in _recv
        self.stream_stdout.write(stdout)
    UnicodeEncodeError: 'ascii' codec can't encode character u'\u2192' in position 274: ordinal not in range(128)
```
### Setup
Create Ubuntu 18.04 template in VMware from Server ISO (only thing changed adding user)

### Steps to Reproduce Issue
Run the cloud.profile module with  a profile that uses the template. 

### Versions Report
```
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-128-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by Ch3LL** [comment]
can you share the command that you are running?

**Comment by 11chrisadams11** [comment]
salt '*salt*' cloud.profile web-18.04 webserver-name01

**Comment by Ch3LL** [comment]
thanks for the additional information. ping @saltstack/team-cloud any initial ideas here?

**Comment by gtmanfred** [comment]
probably just another unicode error in 2018.3

**Comment by 11chrisadams11** [comment]
Is there a workaround for this, or is it being worked on for a new version? Is there something that I could change to allow it to continue with the installation?

**Comment by Ch3LL** [comment]
i would have an easier time at a fix if i had a vmware instance to look at but we did a bunch of Unicode work in the 2018.3 releases. I want to guess we need to convert the stdout to unicode, something like `salt.utils.stringutils.to_unicode(stdout)` but i'm not sure without looking at it, and @gtmanfred might have a better idea too here whether we need to be handling it higher in the stack or not
