### ISSUE TITLE
Salt-SSH OptParse error on python 2.7 target

### ISSUE THREAD

**Issue by perfecto25** [saltstack/salt#48820]
### Description of Issue/Question
running Salt-SSH on Centos 6.9 (python 2.7) results in

          File "/usr/local/lib/python2.7/optparse.py", line 1018, in add_option
            raise TypeError, "invalid arguments"
        TypeError: invalid arguments

Testing against a Centos 6 host with Python 2.7. 

Running any module commands (cmd.run, test.ping, etc) results in this error. 
Running Raw commands shows no error and returns normal value,

Testbox sysinfo:
```
[09:34 root@atlas:~ ]# uname -a
Linux atlas 2.6.32-642.4.2.el6.x86_64 #1 SMP Tue Aug 23 19:58:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
[09:42 root@atlas:~ ]# cat /etc/redhat-release 
CentOS release 6.9 (Final)
[09:34 root@atlas:~ ]# python --version
Python 2.7
```

results in the following error (if running a Raw command, then it works)

```
[root@saltmaster srv]# salt-ssh atlas cmd.run 'uname' -l debug
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] compile template: /etc/salt/roster
[DEBUG   ] Jinja search path: [u'/var/cache/salt/master/files/base']
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[DEBUG   ] Updating roots fileserver cache
[PROFILE ] Time (in seconds) to render '/etc/salt/roster' using 'jinja' renderer: 0.0220921039581
[DEBUG   ] Rendered data from file: /etc/salt/roster:
atlas:
  host: 192.168.xxx
  user: root
  priv: /home/mreider/.ssh/id_rsa
  #sudo: True
  #tty: True

newatlas:
  host: 208.xxxxx
  user: root
  priv: /home/mreider/.ssh/id_rsa
  #sudo: True
  #tty: True

# AWS
ansibletest:
  host: 18.210.xxxxx
  user: centos
  priv: /home/mreider/.ssh/aws/amiprod.pem
  sudo: True 
  tty: True


[DEBUG   ] Results of YAML rendering: 
OrderedDict([(u'atlas', OrderedDict([(u'host', u'192.168.xxxxx'), (u'user', u'root'), (u'priv', u'/home/mreider/.ssh/id_rsa')])), (u'newatlas', OrderedDict([(u'host', u'208.224.xxxxx'), (u'user', u'root'), (u'priv', u'/home/mreider/.ssh/id_rsa')])), (u'ansibletest', OrderedDict([(u'host', u'18.210.xxxxx'), (u'user', u'centos'), (u'priv', u'/home/mreider/.ssh/aws/amiprod.pem'), (u'sudo', True), (u'tty', True)]))])
[PROFILE ] Time (in seconds) to render '/etc/salt/roster' using 'yaml' renderer: 0.00288701057434
[DEBUG   ] LazyLoaded flat.targets
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] compile template: /etc/salt/roster
[DEBUG   ] Jinja search path: [u'/var/cache/salt/master/files/base']
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[PROFILE ] Time (in seconds) to render '/etc/salt/roster' using 'jinja' renderer: 0.0160429477692
[DEBUG   ] Rendered data from file: /etc/salt/roster:
atlas:
  host: 192.168xxxxx
  user: root
  priv: /home/mreider/.ssh/id_rsa
  #sudo: True
  #tty: True

newatlas:
  host: 208.224.xxxxx
  user: root
  priv: /home/mreider/.ssh/id_rsa
  #sudo: True
  #tty: True

# AWS
ansibletest:
  host: 18.210.xxxxxx
  user: centos
  priv: /home/mreider/.ssh/aws/amiprod.pem
  sudo: True 
  tty: True
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[DEBUG   ] Updating roots fileserver cache
[DEBUG   ] LazyLoaded local_cache.prep_jid
[DEBUG   ] Adding minions for job 20180730094236946858: [u'atlas']
[DEBUG   ] Could not LazyLoad cmd.run: 'cmd.run' is not available.
[DEBUG   ] Performing shimmed, blocking command as follows:
cmd.run uname
[DEBUG   ] Executed SHIM command. Command logged to TRACE
[DEBUG   ] Child Forked! PID: 1810  STDOUT_FD: 10  STDERR_FD: 12
[DEBUG   ] VT: Salt-SSH SHIM Terminal Command executed. Logged to TRACE
[DEBUG   ] RETCODE 192.168.40.21: 0
[DEBUG   ] LazyLoaded nested.output
atlas:
    ----------
    retcode:
        0
    stderr:
        Traceback (most recent call last):
          File "/var/tmp/.root_303cbc_salt/salt-call", line 15, in <module>
            salt_call()
          File "/var/tmp/.root_303cbc_salt/py2/salt/scripts.py", line 398, in salt_call
            client = salt.cli.call.SaltCall()
          File "/var/tmp/.root_303cbc_salt/py2/salt/utils/parsers.py", line 160, in __init__
            optparse.OptionParser.__init__(self, *args, **kwargs)
          File "/usr/local/lib/python2.7/optparse.py", line 1214, in __init__
            add_help=add_help_option)
          File "/var/tmp/.root_303cbc_salt/py2/salt/utils/parsers.py", line 241, in _populate_option_list
            self, option_list, add_help=add_help
          File "/usr/local/lib/python2.7/optparse.py", line 1258, in _populate_option_list
            self._add_version_option()
          File "/var/tmp/.root_303cbc_salt/py2/salt/utils/parsers.py", line 252, in _add_version_option
            help='Show program\'s dependencies version number and exit.'
          File "/usr/local/lib/python2.7/optparse.py", line 1018, in add_option
            raise TypeError, "invalid arguments"
        TypeError: invalid arguments
    stdout:

```

Running the same command against another testbox (Centos7 with Python 2.7.5) shows no error,
sysinfo:

```
[root@qbtny3 ~]# python --version
Python 2.7.5
[root@qbtny3 ~]# uname -a
Linux qbtny3 3.10.0-862.9.1.el7.x86_64 #1 SMP Mon Jul 16 16:29:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
[root@qbtny3 ~]# cat /etc/redhat-release 
CentOS Linux release 7.5.1804 (Core)
```

No errors on this host,

```

[root@saltmaster srv]# salt-ssh newatlas cmd.run 'uname' -l debug
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] compile template: /etc/salt/roster
[DEBUG   ] Jinja search path: [u'/var/cache/salt/master/files/base']
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[DEBUG   ] Updating roots fileserver cache
[PROFILE ] Time (in seconds) to render '/etc/salt/roster' using 'jinja' renderer: 0.0216541290283
[DEBUG   ] Rendered data from file: /etc/salt/roster:
atlas:
  host: 192.168.xxxx
  user: root
  priv: /home/mreider/.ssh/id_rsa
  #sudo: True
  #tty: True

newatlas:
  host: 208.224xxxx
  user: root
  priv: /home/mreider/.ssh/id_rsa
  #sudo: True
  #tty: True

# AWS
ansibletest:
  host: 18.210.xxxx
  user: centos
  priv: /home/mreider/.ssh/aws/amiprod.pem
  sudo: True 
  tty: True

[PROFILE ] Time (in seconds) to render '/etc/salt/roster' using 'yaml' renderer: 0.00278091430664
[DEBUG   ] LazyLoaded flat.targets
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] compile template: /etc/salt/roster
[DEBUG   ] Jinja search path: [u'/var/cache/salt/master/files/base']
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[PROFILE ] Time (in seconds) to render '/etc/salt/roster' using 'jinja' renderer: 0.0158960819244
[DEBUG   ] Rendered data from file: /etc/salt/roster:
atlas:
  host: 192.168.xxxx
  user: root
  priv: /home/mreider/.ssh/id_rsa
  #sudo: True
  #tty: True

newatlas:
  host: 208.224.xxxxx
  user: root
  priv: /home/mreider/.ssh/id_rsa
  #sudo: True
  #tty: True

# AWS
ansibletest:
  host: 18.210.xxxx
  user: centos
  priv: /home/mreider/.ssh/aws/amiprod.pem
  sudo: True 
  tty: True


[DEBUG   ] Results of YAML rendering: 
OrderedDict([(u'atlas', OrderedDict([(u'host', u'192.168.xxxxx'), (u'user', u'root'), (u'priv', u'/home/mreider/.ssh/id_rsa')])), (u'newatlas', OrderedDict([(u'host', u'208.224.251.xxxxx), (u'user', u'root'), (u'priv', u'/home/mreider/.ssh/id_rsa')])), (u'ansibletest', OrderedDict([(u'host', u'18.210.4xxxxx9'), (u'user', u'centos'), (u'priv', u'/home/mreider/.ssh/aws/amiprod.pem'), (u'sudo', True), (u'tty', True)]))])
[PROFILE ] Time (in seconds) to render '/etc/salt/roster' using 'yaml' renderer: 0.00265002250671
[DEBUG   ] Matched minions: {u'newatlas': {u'host': u'208.22xxxxxxx3', u'user': u'root', u'priv': u'/home/mreider/.ssh/id_rsa'}}
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[DEBUG   ] Updating roots fileserver cache
[DEBUG   ] LazyLoaded local_cache.prep_jid
[DEBUG   ] Adding minions for job 20180730094628562527: [u'newatlas']
[DEBUG   ] Could not LazyLoad cmd.run: 'cmd.run' is not available.
[DEBUG   ] Performing shimmed, blocking command as follows:
cmd.run uname
[DEBUG   ] Executed SHIM command. Command logged to TRACE
[DEBUG   ] Child Forked! PID: 1828  STDOUT_FD: 10  STDERR_FD: 12
[DEBUG   ] VT: Salt-SSH SHIM Terminal Command executed. Logged to TRACE
[DEBUG   ] RETCODE 208.224.251.253: 0
[DEBUG   ] LazyLoaded nested.output
newatlas:
    Linux

```

### Versions Report
[root@saltmaster srv]# salt-ssh --versions-report
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.9.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core

**Comment by Ch3LL** [comment]
i'm having a hard time replicating this how did you install salt? and how did you install python2.7 on the cent6 host?

**Comment by perfecto25** [comment]
Salt was installed via regular RPM install (using bootstrap.sh)

root@saltmaster /h/centos# rpm -qa | grep salt
salt-2018.3.2-1.el7.noarch
salt-minion-2018.3.2-1.el7.noarch
salt-ssh-2018.3.2-1.el7.noarch
salt-master-2018.3.2-1.el7.noarch

python on host was I believe part of initial centos6 buiild, 

these are the current python RPMs we have on the box,

```
[10:49 root@atlas:~ ]# rpm -qa | grep python
python-webflash-0.1-0.2.a9.el6.noarch
spice-gtk-python-0.26-8.el6.x86_64
python-paste-1.7.4-2.el6.noarch
libproxy-python-0.3.0-10.el6.x86_64
python-sssdconfig-1.13.3-57.el6_9.noarch
abrt-addon-python-2.0.8-43.el6.centos.x86_64
python-webob-0.9.6.1-3.el6.noarch
gnome-python2-canvas-2.28.0-3.el6.x86_64
python-volume_key-0.3.1-5.el6.x86_64
python-lxml-2.2.3-1.1.el6.x86_64
python-six-1.9.0-2.el6.noarch
python-decoratortools-1.7-4.1.el6.noarch
gnome-python2-gnomekeyring-2.28.0-5.el6.x86_64
python-webtest-1.2-2.el6.noarch
python-mako-0.3.4-1.el6.noarch
python-repoze-what-plugins-sql-1.0-0.6.rc1.el6.noarch
python-pycurl-7.19.0-9.el6.x86_64
policycoreutils-python-2.0.83-30.1.el6_8.x86_64
python-cheetah-2.4.1-1.el6.x86_64
python-prioritized-methods-0.2.1-5.2.el6.noarch
abrt-python-2.0.8-43.el6.centos.x86_64
python-2.6.6-66.el6_8.x86_64
setools-libs-python-3.3.7-4.el6.x86_64
python-magic-5.04-30.el6.x86_64
python-zope-filesystem-1-5.el6.x86_64
python-sqlalchemy-0.5.5-3.el6_2.noarch
gnome-python2-extras-2.25.3-20.el6.x86_64
python-meh-0.12.1-3.el6.noarch
python-markupsafe-0.9.2-4.el6.x86_64
gnome-python2-2.28.0-3.el6.x86_64
notify-python-0.1.1-10.el6.x86_64
python-dateutil-1.4.1-7.el6.noarch
python-qpid-qmf-0.14-14.el6_3.x86_64
gtk-vnc-python-0.3.10-3.el6.x86_64
python-genshi-0.5.1-7.1.el6.x86_64
python-paste-script-1.7.3-5.el6_3.noarch
dbus-python-0.83.0-6.1.el6.x86_64
python-peak-util-symbols-1.0-4.1.el6.noarch
python-routes-1.10.3-2.el6.noarch
gnome-python2-applet-2.28.0-5.el6.x86_64
python-netaddr-0.7.5-4.el6.noarch
libselinux-python-2.0.94-7.el6.x86_64
python-memcached-1.43-6.el6.noarch
python-peak-util-addons-0.6-4.1.el6.noarch
python-peak-util-assembler-0.5.1-1.el6.noarch
python-repoze-what-pylons-1.0-4.el6.noarch
python-saslwrapper-0.14-1.el6.x86_64
python-keyczar-0.71c-1.el6.noarch
gnome-python2-gnome-2.28.0-3.el6.x86_64
gamin-python-0.1.10-9.el6.x86_64
python-repoze-what-1.0.8-6.el6.noarch
python-paste-deploy-1.3.3-2.1.el6.noarch
python-repoze-who-testutil-1.0-0.4.rc1.el6.noarch
python-matplotlib-0.99.1.2-1.el6.x86_64
python-peak-util-extremes-1.1-4.1.el6.noarch
python-httplib2-0.7.7-1.el6.noarch
python-repoze-who-plugins-sa-1.0-0.4.rc1.el6.noarch
python-psycopg2-2.0.14-2.el6.x86_64
python-slip-dbus-0.2.20-1.el6_2.noarch
python-paramiko-1.7.5-2.1.el6.noarch
gnome-python2-gnomevfs-2.28.0-3.el6.x86_64
gnome-python2-libegg-2.25.3-20.el6.x86_64
python-repoze-who-friendlyform-1.0.8-2.el6.noarch
python-slip-gtk-0.2.20-1.el6_2.noarch
python-crypto-2.0.1-22.el6.x86_64
python-nose-0.10.4-3.1.el6.noarch
python-argparse-1.2.1-2.1.el6.noarch
python-repoze-tm2-1.0-0.5.a4.el6.noarch
python-weberror-0.10.2-2.el6.noarch
newt-python-0.52.11-4.el6.x86_64
python-slip-0.2.20-1.el6_2.noarch
python-myghty-1.1-11.el6.noarch
libvirt-python-0.10.2-62.el6_9.1.x86_64
ipa-python-3.0.0-51.el6.centos.x86_64
python-ethtool-0.6-6.el6.x86_64
python-jinja2-26-2.6-3.el6.noarch
python-sss-murmur-1.13.3-57.el6_9.x86_64
gnome-python2-desktop-2.28.0-5.el6.x86_64
python-qpid-0.14-11.el6_3.noarch
python-devel-2.6.6-66.el6_8.x86_64
python-transaction-1.0.1-1.el6.noarch
python-peak-rules-0.5a1.dev-9.2582.1.el6.noarch
python-tempita-0.4-2.el6.noarch
python-babel-0.9.4-5.1.el6.noarch
boost-python-1.41.0-28.el6.x86_64
python-pyasn1-0.0.12a-1.el6.noarch
python-dmidecode-3.10.15-1.el6.x86_64
at-spi-python-1.28.1-2.el6.centos.x86_64
libuser-python-0.56.13-8.el6_7.x86_64
python-pygments-1.1.1-2.el6.noarch
libxml2-python-2.7.6-21.el6_8.1.x86_64
python-iniparse-0.3.1-2.1.el6.noarch
python-virtinst-0.600.0-31.el6.noarch
cracklib-python-2.8.16-4.el6.x86_64
python-suds-0.4.1-3.el6.noarch
python-decorator-3.0.1-3.1.el6.noarch
kross-python-4.3.4-5.el6.x86_64
python-iwlib-0.1-1.2.el6.x86_64
python-libipa_hbac-1.13.3-57.el6_9.x86_64
libreport-python-2.0.9-33.el6.centos.x86_64
python-formencode-1.2.2-2.1.el6.noarch
gnome-python2-libwnck-2.28.0-5.el6.x86_64
gnome-python2-bonobo-2.28.0-3.el6.x86_64
python-toscawidgets-0.9.8-1.el6.noarch
gstreamer-python-0.10.16-1.1.el6.x86_64
python-zope-interface-3.5.2-2.1.el6.x86_64
python-enchant-1.3.1-5.2.el6.x86_64
gnome-python2-gconf-2.28.0-3.el6.x86_64
python-webhelpers-0.6.4-4.el6.noarch
python-ldap-2.3.10-1.el6.x86_64
python-turbojson-1.2.1-8.1.el6.noarch
python-repoze-what-quickstart-1.0.1-1.el6.noarch
audit-libs-python-2.4.5-6.el6.x86_64
python-markdown-2.0.1-4.el6.noarch
python-kerberos-1.1-7.el6.x86_64
python-krbV-1.0.90-3.el6.x86_64
python-simplejson-2.0.9-3.1.el6.x86_64
python-repoze-who-1.0.18-1.el6.noarch
libsemanage-python-2.0.43-5.1.el6.x86_64
python-urlgrabber-3.9.1-11.el6.noarch
python-setuptools-0.6.10-4el6_9.noarch
rpm-python-4.8.0-55.el6.x86_64
python-deltarpm-3.5-0.5.20090913git.el6.x86_64
python-pylons-0.9.7-2.el6.noarch
python-beaker-1.3.1-7.el6.noarch
MySQL-python-1.2.3-0.3.c1.1.el6.x86_64
python-libs-2.6.6-66.el6_8.x86_64
python-zope-sqlalchemy-0.4-3.el6.noarch
python-nss-0.16.0-1.el6.x86_64
python-crypto2.6-2.6.1-2.el6.x86_64
```

and heres installed pip pkgs
```

[10:49 root@atlas:~ ]# pip freeze
asn1crypto==0.22.0
beautifulsoup4==4.3.2
certifi==2017.4.17
cffi==1.10.0
chardet==3.0.4
cryptography==2.0.2
cssselect==0.9.1
csvkit==0.5.0
Cython==0.20.1
dbf==0.94.5
Django==1.4.1
django-admin-tools==0.4.0
django-dajax==0.8.4
django-dajaxice==0.1.8.1
django-reversion==1.4
egenix-mx-base==3.2.3
enum34==1.1.6
howdoi==1.1.6
HTML.py==0.4
html5lib==0.9999.dev0
idna==2.5
ipaddress==1.0.18
lxml==3.3.5
Mako==1.0.7
MarkupSafe==1.0
matplotlib==1.4.1
mock==1.0.1
nose==1.3.4
numpy==1.8.1
openpyxl==1.6.1
pandas==0.13.1
pdfkit==0.5.0
pdfminer==20140328
prettytable==0.7.2
pycparser==2.18
Pygments==1.6
pyOpenSSL==17.2.0
pyparsing==2.0.3
pyquery==1.2.8
python-dateutil==2.1
pytz==2014.2
PyYAML==3.12
pyzmq==15.2.0
requests==2.18.2
requests-cache==0.4.4
scikits.statsmodels==0.3.1
six==1.8.0
South==0.7.3
SQLAlchemy==0.8.0b2
update==0.4.4
urllib3==1.22
wkhtmltopdf==0.2
xlrd==1.0.0
zmq==0.0.0
/usr/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
You are using pip version 9.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by perfecto25** [comment]
does having this pkg on the target interfere w how salt-ssh runs

zmq==0.0.0

salt-ssh doesnt use zmq, wondering if this in someway affects some other core modules.

**Comment by Ch3LL** [comment]
i still cannot replicate this. I installed all of the packages you have in your pip freeze output on teh cent6 host and still not seeing the issue. was this working previously?

when you state: "python on target host was I believe part of initial centos6 buiild," i'm not sure this is true because by default python 2.6 is installed with cent6. If you have salt installed on that box for >=2018.3.0 then we will install python2.7 for you. 

and just to verify you see this issue when running salt-ssh from cent7 against a cent6 box correct?
