### ISSUE TITLE
salt api 500: Could not serialize the return data from Salt

### ISSUE THREAD

**Issue by dragouf** [saltstack/salt#48839]
### Description of Issue/Question
when calling job details on api it return 500 error with :

```
<!DOCTYPE html PUBLIC
"-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
        <title>500 Internal Server Error</title>
        <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
    </head>
    <body>
        <h2>500 Internal Server Error</h2>
        <p>Could not serialize the return data from Salt.</p>
        <pre id="traceback"></pre>
        <div id="powered_by">
            <span>
        Powered by 
                <a href="http://www.cherrypy.org">CherryPy 5.6.0</a>
            </span>
        </div>
    </body>
</html>
```

### Setup
execute a big job with api endpoint 'local_async' and then call: 

```
curl -X GET \
  'https://apihost/jobs/20180730095827413902?timeout=600' \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/json' \
  -H 'X-Auth-Token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
```

When calling in command line instead of the api:
 `salt-run jobs.print_job 20180730095827413902`

it seems to work

### Api Log
```
2018-07-31 08:27:12,835 [salt.loaded.int.netapi.rest_cherrypy.app][DEBUG   ][30787] Could not serialize the return data from Salt.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/netapi/rest_cherrypy/app.py", line 779, in hypermedia_handler
    response = out(ret)
  File "/usr/lib64/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib64/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x85 in position 37927: invalid start byte
```

### Versions Report
```
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.24.6
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: 0.24.2
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.21.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

**Comment by Ch3LL** [comment]
can you clarify this statement: "execute a big job with api endpoint 'local_async' " 

Can you clarify what you mean by big job?

I can't seem to replicate this so would be useful if you can paste a sanitized version of the curl command you're making

**Comment by Ch3LL** [comment]
and does the behavior still exhibit itself in the latest 2018.3 release? we did a ton of unicode improvements in that release.
