### ISSUE TITLE
salt-minion self-restart doesn't work in daemon mode. Works when not a daemon

### ISSUE THREAD

**Issue by pengyao** [saltstack/salt#48860]
### Description of Issue/Question

salt-minion in daemon mode process dies instead of restarting itself

### Setup

Two salt master,  `master_type` use `failover`

Minion config:

```
master:
  - master-01
  - master-02
master_type: failover
master_alive_interval: 30
log_level_logfile: debug
```
### Steps to Reproduce Issue

1. Start salt-minion with daemon mode

```
/usr/bin/salt-minion -d
```

2. After minion started, Stop all masters

3. Tail minion's log, after 1 minute, you will look like this:

```
2018-08-01 13:18:04,652 [salt.minion                                                             :650 ][ERROR   ][4611] No master could be reached or all masters denied the minion's connection
2018-08-01 13:18:04,652 [salt.scripts                                                            :146 ][WARNING ][4611] Fatal functionality error caught by minion handler:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 144, in minion_process
    minion.start()
  File "/usr/lib/python2.7/site-packages/salt/cli/daemons.py", line 350, in start
    raise SaltClientError('Minion could not connect to Master')
SaltClientError: Minion could not connect to Master
2018-08-01 13:18:04,652 [salt.scripts                                                            :147 ][WARNING ][4611] ** Restarting minion **
2018-08-01 13:18:04,652 [salt.scripts                                                            :152 ][INFO    ][4611] waiting random_reauth_delay 8s
```

4. After random_reauth_delay, the salt-minion process die, not restart

5. Start salt-minion without daemon, and test again, the salt-minion will self-restart

### Versions Report

```
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Mar 30 2018, 15:31:59)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.9 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-696.6.3.el6.x86_64
         system: Linux
        version: CentOS 6.9 Final
```

**Comment by garethgreenaway** [comment]
@pengyao Thanks for the report.  Unfortunately I wasn't able to reproduce this issue, any additional information you can provide about your setup that might help would be appreciated.

**Comment by cachedout** [comment]
I think I am seeing this bug on-site in a large Salt installation.

**Comment by pengyao** [comment]
I think the reason is minion start keepalive process first. The keepalive process is the parent process, will be exited by daemon operation.  @cachedout
