### ISSUE TITLE
salt-cloud unable to create VM with external_ip: somename

### ISSUE THREAD

**Issue by dawidpogorzelski** [saltstack/salt#48947]
### Description of Issue/Question
salt-cloud is unable to create a VM on gce when `external_ip: somename` is provided regardless of whether that ip was pre-created or not.

```
ERROR   ] Caught Exception, terminating workers
TRACE: can't serialize <GCEAddress id="5717818400664030676" name="someipaddressname" address="someiphere" region="europe-west1">
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/salt/cloud/__init__.py", line 67, in _call
    ret = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/salt/cloud/__init__.py", line 2317, in create_multiprocessing
    local_master=parallel_data['local_master']
  File "/usr/local/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1284, in create
    output = self.clouds[func](vm_)
  File "/usr/local/lib/python2.7/site-packages/salt/cloud/clouds/gce.py", line 2581, in create
    ret = __utils__['cloud.bootstrap'](vm_, __opts__)
  File "/usr/local/lib/python2.7/site-packages/salt/utils/cloud.py", line 553, in bootstrap
    transport=opts.get('transport', 'zeromq')
  File "/usr/local/lib/python2.7/site-packages/salt/utils/cloud.py", line 1786, in fire_event
    event.fire_event(args, tag)
  File "/usr/local/lib/python2.7/site-packages/salt/utils/event.py", line 725, in fire_event
    dump_data = self.serial.dumps(data)
  File "/usr/local/lib/python2.7/site-packages/salt/payload.py", line 217, in dumps
    return msgpack.dumps(msg, default=ext_type_encoder, use_bin_type=use_bin_type)
  File "/usr/local/lib/python2.7/site-packages/msgpack/__init__.py", line 47, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 284, in msgpack._packer.Packer.pack
  File "msgpack/_packer.pyx", line 290, in msgpack._packer.Packer.pack
  File "msgpack/_packer.pyx", line 287, in msgpack._packer.Packer.pack
  File "msgpack/_packer.pyx", line 234, in msgpack._packer.Packer._pack
  File "msgpack/_packer.pyx", line 234, in msgpack._packer.Packer._pack
  File "msgpack/_packer.pyx", line 234, in msgpack._packer.Packer._pack
  File "msgpack/_packer.pyx", line 281, in msgpack._packer.Packer._pack
TypeError: can't serialize <GCEAddress id="5717818400664030676" name="someipaddressname" address="someiphere" region="europe-west1">
```

### Setup
profile:
```
proxy:
  provider: gce-config
  image: windows-server-2016
  network: somenet
  subnetwork: somesubnet
  tags: '["sometag"]'
  metadata: '{"windows-startup-script-url":"gs://windows-startup-script.ps1"}'
  deploy: true
  use_winrm: true
  winrm_verify_ssl: false
  winrm_use_ssl: false
  external_ip: ephemeral
  win_installer: /opt/Salt-Minion-2018.3.2-Py2-AMD64-Setup.exe
  minion:
    master: someip
    startup_states: highstate
  ex_disks_gce_struct:
    -
      autoDelete: true
      boot: true
      initializeParams:
        sourceImage: compute/v1/projects/windows-cloud/global/images/family/windows-2016
        diskType: projects/someproject/zones/europe-west1-d/diskTypes/pd-ssd
      type: PERSISTENT
    -
      autoDelete: true
      initializeParams:
        diskType: projects/someproject/zones/europe-west1-d/diskTypes/pd-ssd
        diskSizeGb: 100
```

map:
```
proxy:
  - myvmname:
      grains:
        some: val
      location: europe-west1-b
      size: n1-standard-4
      external_ip: someipname
```

### Steps to Reproduce Issue
`salt-cloud -l all -m master-config/cloud.maps.d/map.conf -Py`

### Versions Report
```
Salt Version:
           Salt: 2018.3.1

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15 (default, May 26 2018, 01:11:09)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.3

System Versions:
           dist:
         locale: UTF-8
        machine: amd64
        release: 11.2-RELEASE
         system: FreeBSD
        version: Not Installed
```

**Comment by garethgreenaway** [comment]
@dawidpogorzelski Similar to question on your other issue, was it this working in previous releases and broke in 2018.3.1?

**Comment by dawidpogorzelski** [comment]
Did a quick test with 2017.7.7, same problem.

**Comment by dawidpogorzelski** [comment]
Have a working fix:
https://github.com/dawidpogorzelski/salt/commit/6acfa841a306e69aff6c415562d56737653dc7c3
This seemed like the most logic place where to do this serialization work to me but there are most likely better places
