### ISSUE TITLE
can't serialize gce object

### ISSUE THREAD

**Issue by dawidpogorzelski** [saltstack/salt#48949]
### Description of Issue/Question
When using orchestrate to perform a cloud.action on GCE the action is performed correctly on GCE end but the gce object can't be serialized.

```
ID: create_disk
Function: salt.runner
Name: cloud.action
Result: False
Comment: An exception occurred in this state: Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/salt/state.py", line 1905, in call
        **cdata['kwargs'])
      File "/usr/local/lib/python2.7/site-packages/salt/loader.py", line 1830, in wrapper
        return f(*args, **kwargs)
      File "/usr/local/lib/python2.7/site-packages/salt/states/saltmod.py", line 759, in runner
        **kwargs)
      File "/usr/local/lib/python2.7/site-packages/salt/modules/saltutil.py", line 1522, in runner
        full_return=full_return)
      File "/usr/local/lib/python2.7/site-packages/salt/runner.py", line 156, in cmd
        full_return)
      File "/usr/local/lib/python2.7/site-packages/salt/client/mixins.py", line 238, in cmd
        return self.low(fun, low, print_event=print_event, full_return=full_return)
      File "/usr/local/lib/python2.7/site-packages/salt/client/mixins.py", line 261, in low
        return self._low(fun, low, print_event=print_event, full_return=full_return)
      File "/usr/local/lib/python2.7/site-packages/salt/client/mixins.py", line 418, in _low
        mminion=self.mminion,
      File "/usr/local/lib/python2.7/site-packages/salt/utils/job.py", line 107, in store_job
        mminion.returners[savefstr](load['jid'], load)
      File "/usr/local/lib/python2.7/site-packages/salt/returners/local_cache.py", line 215, in save_load
        serial.dump(clear_load, wfh)
      File "/usr/local/lib/python2.7/site-packages/salt/payload.py", line 251, in dump
        fn_.write(self.dumps(msg))
      File "/usr/local/lib/python2.7/site-packages/salt/payload.py", line 217, in dumps
        return msgpack.dumps(msg, default=ext_type_encoder, use_bin_type=use_bin_type)
      File "/usr/local/lib/python2.7/site-packages/msgpack/__init__.py", line 47, in packb
        return Packer(**kwargs).pack(o)
      File "msgpack/_packer.pyx", line 284, in msgpack._packer.Packer.pack
      File "msgpack/_packer.pyx", line 290, in msgpack._packer.Packer.pack
      File "msgpack/_packer.pyx", line 287, in msgpack._packer.Packer.pack
      File "msgpack/_packer.pyx", line 234, in msgpack._packer.Packer._pack
      File "msgpack/_packer.pyx", line 234, in msgpack._packer.Packer._pack
      File "msgpack/_packer.pyx", line 234, in msgpack._packer.Packer._pack
      File "msgpack/_packer.pyx", line 234, in msgpack._packer.Packer._pack
      File "msgpack/_packer.pyx", line 234, in msgpack._packer.Packer._pack
      File "msgpack/_packer.pyx", line 234, in msgpack._packer.Packer._pack
      File "msgpack/_packer.pyx", line 234, in msgpack._packer.Packer._pack
      File "msgpack/_packer.pyx", line 281, in msgpack._packer.Packer._pack
    TypeError: can't serialize <libcloud.compute.drivers.gce.GCENodeDriver object at 0x812319050>
Started: 13:49:05.858060
Duration: 6073.282 ms
Changes:
```
If i call the same function from salt-cloud the response is parsed correctly:
```salt-cloud -f create_disk gce-config disk_name=aaa location=europe-west1-b size=20
gce-config:
    ----------
    gce:
        ----------
        _uuid:
            None
        driver:
        extra:
            ----------
            creationTimestamp:
                2018-08-06T06:56:49.545-07:00
            description:
                None
            options:
                None
            selfLink:
                https://www.googleapis.com/compute/v1/projects/aproject/zones/europe-west1-b/disks/aaa
            sourceImage:
                None
            sourceImageId:
                None
            sourceSnapshot:
                None
            sourceSnapshotId:
                None
            status:
                READY
            type:
                pd-standard
            zone:
                ----------
                country:
                    europe
                deprecated:
                    None
                driver:
                extra:
                    ----------
                    creationTimestamp:
                        1969-12-31T16:00:00.000-08:00
                    description:
                        europe-west1-b
                    region:
                        https://www.googleapis.com/compute/v1/projects/aproject/regions/europe-west1
                    selfLink:
                        https://www.googleapis.com/compute/v1/projects/aproject/zones/europe-west1-b
                id:
                    2101
                maintenance_windows:
                    None
                name:
                    europe-west1-b
                status:
                    UP
        id:
            1873367996916165966
        name:
            aaa
        size:
            20
        state:
            None
```

### Setup
mystate.sls:
```
create_disk:
  salt.runner:
    - name: cloud.action
    - func: create_disk
    - provider: gce-config
    - kwargs:
        location: europe-west1-b
        disk_name: somename
        size: 20
```

### Steps to Reproduce Issue
salt-run state.orchestrate _orch.mystate test=false

```
### Versions Report
Salt Version:
           Salt: 2018.3.1

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15 (default, May 26 2018, 01:11:09)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.3

System Versions:
           dist:
         locale: UTF-8
        machine: amd64
        release: 11.2-RELEASE
         system: FreeBSD
        version: Not Installed
```

**Comment by garethgreenaway** [comment]
@dawidpogorzelski Thanks for the report.  Was this working in previous versions of Salt? I found this PR and it seems related, https://github.com/saltstack/salt/pull/40120 but I'm wondering if it affects Salt cloud call but not when using the Salt runner.

**Comment by dawidpogorzelski** [comment]
Did a quick test with 2017.7.7, same problem.
