### ISSUE TITLE
Proxy minion strange behavior

### ISSUE THREAD

**Issue by jpvis** [saltstack/salt#48963]
We are running proxy minions for 1600+ Cisco devices, some of these devices are unreachable. 
When I'm started proxy minion for these devices for the first time (if minion server rebooted or I'm killing all proxy processes) I found few odd things:

- CPU usage is about 95-100% - I though that maybe salt need some resources to get grains from all devices, but after 48 hours nothing changed.

- Salt started to create thousands of empty files in /tmp dir with names "__salt.tmp.XXX" - after 5 days  I had problem with lack of innodes in my VM.

-  In logs I saw that proxy constantly trying to reconnect : 
```2018-08-07 06:54:20,815 [/usr/lib/python2.7/site-packages/salt/utils/napalm.pyc:228 ][ERROR   ][15301] Cannot execute "get_facts" on [unspecified hostname] as . Reason: not connected!
2018-08-07 06:54:20,815 [/usr/lib/python2.7/site-packages/salt/utils/napalm.pyc:229 ][ERROR   ][15301] Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/napalm.py", line 158, in call
    raise Exception('not connected')
Exception: not connected
2018-08-07 07:03:44,829 [salt.minion      :1008][CRITICAL][33163] Unexpected error while connecting to **salt-master_IP**
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 991, in _connect_minion
    yield minion.connect_master(failed=failed)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1182, in connect_master
    yield self._post_master_init(master)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 879, in run
    yielded = self.gen.send(value)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 3578, in _post_master_init
    proxy_init_fn(self.opts)
  File "/usr/lib/python2.7/site-packages/salt/proxy/napalm.py", line 183, in init
    NETWORK_DEVICE.update(salt.utils.napalm.get_device(opts))
  File "/usr/lib/python2.7/site-packages/salt/utils/napalm.py", line 332, in get_device
    network_device.get('DRIVER').open()
  File "/usr/lib/python2.7/site-packages/napalm/ios/ios.py", line 125, in open
    **self.netmiko_optional_args)
  File "/usr/lib/python2.7/site-packages/netmiko/ssh_dispatcher.py", line 178, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 207, in __init__
    self.establish_connection()
  File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 693, in establish_connection
    raise NetMikoTimeoutException(msg)
NetMikoTimeoutException: Connection to device timed-out: cisco_ios **device_IP**:22
```
And I see this type of messages for every unreachable device.

When I killed all minion-proxy processes that can't connect to devices all these problems are gone.

I tried to tune configuration related to proxy connection : 
proxy_keep_alive: False
proxy_always_alive: False
 
But that didn't help 

I got suggestion to open feature request  -  **limit for connecting to devices**
I think it will be useful.

For now I'm thinking to write a script that will kill processes for all unreachable devices as a workaround. 

### Setup
Salt master and Salt minion - different VMs.

### Versions Report
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.28.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, May  3 2017, 07:55:04)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.4 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.3.3.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.4 Maipo

**Comment by gtmanfred** [comment]
Yes, this would be great.

@mirceaulinic you may be interested in this.

Thanks for the request!
Daniel
