### ISSUE TITLE
MySQL returner

### ISSUE THREAD

**Issue by Annnetta** [saltstack/salt#49028]
### Description of Issue/Question
I would like to add some additional columns to MySQL database with MySQL returner. 
For now I have a table `salt_returns` created as this:
```
CREATE TABLE `salt_returns` (
  `fun` varchar(50) NOT NULL,
  `jid` varchar(255) NOT NULL,
  `result` mediumtext NOT NULL,    //  I have  changed the column name from 'return' to 'result' as it creates the conflict in MySQL,
  `fun_args` varchar(50),      // I would like to have this column additionally
  `id` varchar(255) NOT NULL,
  `success` varchar(10) NOT NULL,
  `full_ret` mediumtext NOT NULL,
  `alter_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY `id` (`id`),
  KEY `jid` (`jid`),
  KEY `fun` (`fun`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

in /usr/lib/python2.7/dist-packages/salt/returners/mysql.py
for returner function I have:

```
def returner(ret):
    '''
    Return data to a mysql server
    '''
    # if a minion is returning a standalone job, get a jobid
    if ret['jid'] == 'req':
        ret['jid'] = prep_jid(nocache=ret.get('nocache', False))
        save_load(ret['jid'], ret)

    try:
        with _get_serv(ret, commit=True) as cur:
            sql = '''INSERT INTO `salt_returns`
                     (`fun`, `jid`, `result`, `id`, `fun_args`, `success`, `full_ret`)
                     VALUES (%s, %s, %s, %s, %s, %s, %s)'''

            cur.execute(sql, (ret['fun'], ret['jid'],
                              salt.utils.json.dumps(ret['return']),
                              ret['id'],
                              ret['fun_args'],
                              ret.get('success', False),
                              salt.utils.json.dumps(ret)))
    except salt.exceptions.SaltMasterError as exc:
        log.critical(exc)
        log.critical('Could not store return with MySQL returner. MySQL server unavailable.')
```

While executing  `sudo salt-run manage.status` I have this error:

```
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
KeyError: u'fun_args'
Traceback (most recent call last):
  File "/usr/bin/salt-run", line 10, in <module>
    salt_run()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 412, in salt_run
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/run.py", line 40, in run
    ret = runner.run()
  File "/usr/lib/python2.7/dist-packages/salt/runner.py", line 271, in run
    daemonize=False)
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 485, in _proc_function
    return self.low(fun, low, full_return=False)
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 261, in low
    return self._low(fun, low, print_event=print_event, full_return=full_return)
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 418, in _low
    mminion=self.mminion,
  File "/usr/lib/python2.7/dist-packages/salt/utils/job.py", line 110, in store_job
    mminion.returners[fstr](load)
  File "/usr/lib/python2.7/dist-packages/salt/returners/mysql.py", line 294, in returner
    ret['fun_args'],
KeyError: u'fun_args'
Traceback (most recent call last):
  File "/usr/bin/salt-run", line 10, in <module>
    salt_run()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 412, in salt_run
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/run.py", line 40, in run
    ret = runner.run()
  File "/usr/lib/python2.7/dist-packages/salt/runner.py", line 271, in run
    daemonize=False)
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 485, in _proc_function
    return self.low(fun, low, full_return=False)
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 261, in low
    return self._low(fun, low, print_event=print_event, full_return=full_return)
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 418, in _low
    mminion=self.mminion,
  File "/usr/lib/python2.7/dist-packages/salt/utils/job.py", line 110, in store_job
    mminion.returners[fstr](load)
  File "/usr/lib/python2.7/dist-packages/salt/returners/mysql.py", line 294, in returner
    ret['fun_args'],
KeyError: u'fun_args'
```

As I can see, the problem is in the name of the argument fun_args as **KeyError: u'fun_args'**. 

I am not sure from which output this python code takes the arguments. 
If I do 
`sudo salt-call --local --metadata test.ping --out=pprint`

I have:
```
{u'local': {u'fun': u'test.ping',
            u'fun_args': [],
            u'id': u'octopus-workstation01',
            u'jid': u'20180809145132049792',
            u'retcode': 0,
            u'return': True}}
```
and  here the field fun_args exists.
### Versions Report
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.3.7
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Nov 24 2017, 17:33:09)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.5 
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-6-amd64
         system: Linux
        version: debian 9.5 

-------------------------------------------------------------------
What should I do to add the column if it is possible?

Thanks in advance,
Hanna

**Comment by Annnetta** [comment]
Well, finally that works. 

I forgot to change the number of  `VALUES (%s, %s, %s, %s, %s, %s, %s) ` (before there were only 6) in mysql.py.

Now, in my database I have the field fun_args filled in.

**Comment by Annnetta** [comment]
The problem is that if I execute  `sudo salt-run manage.status`
I  have the same error as mentioned. 


And also `sudo salt-run jobs.print_job 20180809162256603883`
doesn't work:
```
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
KeyError: u'fun_args'
Traceback (most recent call last):
  File "/usr/bin/salt-run", line 10, in <module>
    salt_run()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 412, in salt_run
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/run.py", line 40, in run
    ret = runner.run()
  File "/usr/lib/python2.7/dist-packages/salt/runner.py", line 271, in run
    daemonize=False)
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 485, in _proc_function
    return self.low(fun, low, full_return=False)
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 261, in low
    return self._low(fun, low, print_event=print_event, full_return=full_return)
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 418, in _low
    mminion=self.mminion,
  File "/usr/lib/python2.7/dist-packages/salt/utils/job.py", line 110, in store_job
    mminion.returners[fstr](load)
  File "/usr/lib/python2.7/dist-packages/salt/returners/mysql.py", line 294, in returner
    ret['fun_args'],
KeyError: u'fun_args'
```

Do you have any ideas how to add some columns correctly?

Thanks,
Hanna

**Comment by garethgreenaway** [comment]
@Annnetta It seems like the `fun_args` item is not always in the `ret` that the returner is receiving.  A quick fix would be to check if it's available, in the event that it's not add an empty list.
Something like this:
```
def returner(ret):
    '''
    Return data to a mysql server
    '''
    # if a minion is returning a standalone job, get a jobid
    if ret['jid'] == 'req':
        ret['jid'] = prep_jid(nocache=ret.get('nocache', False))
        save_load(ret['jid'], ret)

    if 'fun_args' not in ret:
      ret['fun_args'] = []

    try:
        with _get_serv(ret, commit=True) as cur:
            sql = '''INSERT INTO `salt_returns`
                     (`fun`, `jid`, `result`, `id`, `fun_args`, `success`, `full_ret`)
                     VALUES (%s, %s, %s, %s, %s, %s, %s)'''

            cur.execute(sql, (ret['fun'], ret['jid'],
                              salt.utils.json.dumps(ret['return']),
                              ret['id'],
                              ret['fun_args'],
                              ret.get('success', False),
                              salt.utils.json.dumps(ret)))
    except salt.exceptions.SaltMasterError as exc:
        log.critical(exc)
        log.critical('Could not store return with MySQL returner. MySQL server unavailable.')
```

**Comment by Annnetta** [comment]
@garethgreenaway Thank you for your answer!

This exactly solution didn't work, but if we change `ret['fun_args'] = [] `to `ret['fun_args'] = ['NULL']` or another string that works!

So the full function here will be:

```
def returner(ret):
    '''
    Return data to a mysql server
    '''
    # if a minion is returning a standalone job, get a jobid
    if ret['jid'] == 'req':
        ret['jid'] = prep_jid(nocache=ret.get('nocache', False))
        save_load(ret['jid'], ret)

    if 'fun_args' not in ret:
      ret['fun_args'] = ['NULL']

    try:
        with _get_serv(ret, commit=True) as cur:
            sql = '''INSERT INTO `salt_returns`
                     (`fun`, `jid`, `result`, `id`, `fun_args`, `success`, `full_ret`)
                     VALUES (%s, %s, %s, %s, %s, %s, %s)'''

            cur.execute(sql, (ret['fun'], ret['jid'],
                              salt.utils.json.dumps(ret['return']),
                              ret['id'],
                              ret['fun_args'],
                              ret.get('success', False),
                              salt.utils.json.dumps(ret)))
    except salt.exceptions.SaltMasterError as exc:
        log.critical(exc)
        log.critical('Could not store return with MySQL returner. MySQL server unavailable.')
```

**Comment by Annnetta** [comment]
I have one more question. 
I would like to have one more column - "comment" that will show what  is in u'comment':

`sudo salt-call --local --metadata state.apply add_file --out=pprint`

```
{u'local': {u'fun': u'state.apply',
            u'fun_args': [u'add_file'],
            u'id': u'workstation01',
            u'jid': u'20180810105438323244',
            u'out': u'highstate',
            u'retcode': 2,
            u'return': {u'file_|-/tmp/hello.txt_|-/tmp/the newesthello.txt_|-managed': {u'__id__': u'/tmp/hello.txt',
                                                                                        u'__run_num__': 0,
                                                                                        u'__sls__': u'add_file',
                                                                                        u'changes': {},
                                                                                        u'comment': u'Source file salt://hellonotexistant.txt not found',
                                                                                        u'duration': 14.204,
                                                                                        u'name': u'/tmp/the newesthello.txt',
                                                                                        u'pchanges': {},
                                                                                        u'result': False,
                                                                                        u'start_time': '10:54:38.756662'}}}}
```


For this I modified mysql.py like this:
To access the information in 'comment' I have used: `salt.utils.json.dumps(ret['return'].values()[0]['comment'])`
```
def returner(ret):
    '''
    Return data to a mysql server
    '''
    # if a minion is returning a standalone job, get a jobid
    if ret['jid'] == 'req':
        ret['jid'] = prep_jid(nocache=ret.get('nocache', False))
        save_load(ret['jid'], ret)

    if 'fun_args' not in ret:
      ret['fun_args'] = ['NULL']

    if 'comment' not in ret:
      ret['comment'] = ['NULL']

    try:
        with _get_serv(ret, commit=True) as cur:
            sql = '''INSERT INTO `salt_returns`
                     (`fun`, `jid`, `result`, `id`, `fun_args`, `comment`, `success`,`full_ret`)
                     VALUES (%s, %s, %s, %s, %s, %s, %s, %s)'''

            cur.execute(sql, (ret['fun'], 
                              ret['jid'],
                              salt.utils.json.dumps(ret['return']),
                              ret['id'],
                              ret['fun_args'],
                              salt.utils.json.dumps(ret['return'].values()[0]['comment']),
                              ret.get('success', False),
                              salt.utils.json.dumps(ret)))
    except salt.exceptions.SaltMasterError as exc:
        log.critical(exc)
        log.critical('Could not store return with MySQL returner. MySQL server unavailable.')
```

This code works as I have the correct output in my database.

But if I would like to execute 
`sudo salt-run jobs.print_job 20180810113525790121`

I have another error:
```
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: list indices must be integers, not unicode
Traceback (most recent call last):
  File "/usr/bin/salt-run", line 10, in <module>
    salt_run()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 412, in salt_run
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/run.py", line 40, in run
    ret = runner.run()
  File "/usr/lib/python2.7/dist-packages/salt/runner.py", line 271, in run
    daemonize=False)
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 485, in _proc_function
    return self.low(fun, low, full_return=False)
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 261, in low
    return self._low(fun, low, print_event=print_event, full_return=full_return)
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 418, in _low
    mminion=self.mminion,
  File "/usr/lib/python2.7/dist-packages/salt/utils/job.py", line 110, in store_job
    mminion.returners[fstr](load)
  File "/usr/lib/python2.7/dist-packages/salt/returners/mysql.py", line 305, in returner
    salt.utils.json.dumps(ret['return'].values()[0]['result']),
TypeError: list indices must be integers, not unicode
```

------------------------
Do you see the problem?

Thanks,
Hanna

**Comment by garethgreenaway** [comment]
Looks like when you're running the Salt runner it's also attempting to add a job into MySQL and the contents of that job's return data is different.  I'd adding a couple logging statements to see what 
`ret['return'].values()[0]` looks like.

**Comment by Annnetta** [comment]
@garethgreenaway 
As far as I can see the outputs are a little bit different, maybe this creates a problem:

While doing `salt 'windows-minion' -l debug state.apply latest --return`

I have:
```
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/mysql.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/mysql.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: octopus-workstation01.cosmo
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/mysql.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/mysql.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: workstation01
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/master', u'workstation01', u'tcp://127.0.0.1:45060', u'clear')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://127.0.0.1:45060
[DEBUG   ] Trying to connect to: tcp://127.0.0.1:45060
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] SaltReqTimeoutError, retrying. (1/3)
[DEBUG   ] LazyLoaded mysql.get_load
[DEBUG   ] LazyLoaded config.option
[INFO    ] Using default for mysql ssl_key
[INFO    ] Using default for mysql ssl_cert
[INFO    ] Using default for mysql ssl_ca
[DEBUG   ] Generating new MySQL connection pool
[DEBUG   ] get_iter_returns for jid 20180813154611973683 sent to set(['windows-minion']) will timeout at 15:46:17.062875
[DEBUG   ] Checking whether jid 20180813154611973683 is still running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/master', u'workstation01', u'tcp://127.0.0.1:45060', u'clear')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://127.0.0.1:45060
[DEBUG   ] Trying to connect to: tcp://127.0.0.1:45060
[DEBUG   ] Passing on saltutil error. Key 'u'retcode' missing from client return. This may be an error in the client.
[DEBUG   ] Checking whether jid 20180813154611973683 is still running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/master', u'workstation01', u'tcp://127.0.0.1:45060', u'clear')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://127.0.0.1:45060
[DEBUG   ] Trying to connect to: tcp://127.0.0.1:45060
[DEBUG   ] Passing on saltutil error. Key 'u'retcode' missing from client return. This may be an error in the client.
[DEBUG   ] jid 20180813154611973683 return from windows-minion
[DEBUG   ] return event: {u'windows-minion': {u'jid': u'20180813154611973683', u'retcode': 0, u'ret': {u'pkg_|-zip_install_|-Zzip_|-installed': {u'comment': u'All specified packages are already installed', u'name': u'Zzip', u'start_time': u'15:46:16.693000', u'result': True, u'duration': 12078.0, u'__run_num__': 0, u'__sls__': u'latest', u'changes': {}, u'__id__': u'zip_install'}}, u'out': u'highstate'}}
[DEBUG   ] LazyLoaded highstate.output
```
--------------------------------------
If then I do `salt-run jobs.print_job 20180813154611973683`
where in the code (mysql.py) I have written an exception in order to see the output 
`raise Exception(repr(ret))`

I have:

```
Traceback (most recent call last):
  File "/usr/bin/salt-run", line 10, in <module>
    salt_run()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 412, in salt_run
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/run.py", line 40, in run
    ret = runner.run()
  File "/usr/lib/python2.7/dist-packages/salt/runner.py", line 271, in run
    daemonize=False)
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 485, in _proc_function
    return self.low(fun, low, full_return=False)
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 261, in low
    return self._low(fun, low, print_event=print_event, full_return=full_return)
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 418, in _low
    mminion=self.mminion,
  File "/usr/lib/python2.7/dist-packages/salt/utils/job.py", line 110, in store_job
    mminion.returners[fstr](load)
  File "/usr/lib/python2.7/dist-packages/salt/returners/mysql.py", line 299, in returner
    raise Exception(repr(ret))
Exception: {u'fun_args': [u'NULL'], u'jid': u'20180813154156907655', u'return': {u'fun_args': [u'20180813154119227559'], u'jid': u'20180813154156907655', u'return': {u'20180813154119227559': {u'Function': u'state.apply', u'Target': u'windows-minion', u'Result': {}, u'User': u'sudo_salt', u'StartTime': u'2018, Aug 13 15:41:19.227559', u'Target-type': u'glob', u'Arguments': [u'latest']}}, u'success': True, u'_stamp': '2018-08-13T13:41:57.287726', u'user': u'sudo_salt', u'fun': u'runner.jobs.print_job'}, u'user': u'sudo_salt', u'tgt': u'octopus-workstation01.cosmo_master', u'fun': u'runner.jobs.print_job', u'id': u'workstation01'}
```


If I do an exception with **ret['return'].values()[0]** , it gives only 
`[u'20180813154416558894']`

--------------------------------------
Meantime in my MySQL table in the column 'comment' I have the output as wanted : `All specified packages are already installed`
