### ISSUE TITLE
On Py3, redis job cache throws TypeError bytes / str  

### ISSUE THREAD

**Issue by The-Loeki** [saltstack/salt#49060]
### Description of Issue/Question
```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/site-packages/salt/utils/process.py", line 747, in _run
    return self._original_run()
  File "/usr/lib/python3.6/site-packages/salt/master.py", line 223, in run
    salt.daemons.masterapi.clean_old_jobs(self.opts)
  File "/usr/lib/python3.6/site-packages/salt/daemons/masterapi.py", line 174, in clean_old_jobs
    mminion.returners[fstr]()
  File "/usr/lib/python3.6/site-packages/salt/returners/redis_return.py", line 308, in clean_old_jobs
    load_key = ret_key.replace('ret:', 'load:', 1)
TypeError: a bytes-like object is required, not 'str'
```

There's already `unicode_literals` in there, so since `ret_key` is a bytes, the 'fix' seems 
```
load_key = ret_key.replace(b'ret:', b'load:', 1)
```
Which seems odd because the default encoding for redis is already utf8?
What's the canonical way to fix this? 

### Versions Report
```
Salt Version:
           Salt: 2018.3.0-616-ge995901
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: 3.5.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.26.0
        libnacl: 1.6.1
       M2Crypto: 0.28.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 3.6.6 (default, Jul 19 2018, 14:25:17)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.6
 
System Versions:
           dist: fedora 28 Twenty Eight
         locale: UTF-8
        machine: x86_64
        release: 4.17.12-200.fc28.x86_64
         system: Linux
        version: Fedora 28 Twenty Eight
```

**Comment by Ch3LL** [comment]
ping @saltstack/team-core any insight here on @The-Loeki 's suggested fix?

**Comment by rallytime** [comment]
@The-Loeki Does the `to_bytes` function work for you here in the `salt.utils.stringutils`?

**Comment by terminalmage** [comment]
I'm not sure what the reasons are either, I've never used py-redis. However, the docs don't really warn about performance (see [here](https://github.com/andymccurdy/redis-py#getting-started)), so perhaps the best solution is indeed to use `decode_responses=True`.

**Comment by The-Loeki** [comment]
#49190 closes the issue, thanks again for the swift & considerate input
