### ISSUE TITLE
lsattr for AIX is not compatiable with lsattr for linux.

### ISSUE THREAD

**Issue by whytewolf** [saltstack/salt#49089]
### Description of Issue/Question

When using a bunch of the file state functions, it detects the presence of lsattr on AIX even though the lsattr for AIX is a much different command for device management, not file attributes. So while trying to use lsattr to compare attributes on AIX it throughs an IndexError

### Setup
Have 2018.3.x and use `file.replace` state on AIX.

```
[DEBUG   ] output: lsattr: 0514-500 Usage error - /var/spool/cron/crontabs/root

Usage:
lsattr {-D[-O]| -E[-O] -P[-O]| -F Format [-Z Character]} -l Name
        [-a Attribute]...[-H] [-f File]
lsattr {-D[-O]| -F Format [-Z Character]}{[-c Class][-s Subclass][-t Type]}
        [-a Attribute]... [-H][-f File]
lsattr -R {-l Name | [-c Class][-s Subclass][-t Type]} -a Attribute [-H]
        [-f File]
lsattr {-l Name | [-c Class][-s Subclass][-t Type]} -o Operation [...]
        -F Format [-Z Character][-f File][-H]
lsattr -h
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/opt/salt/lib/python2.7/site-packages/salt/state.py", line 1905, in call
    **cdata['kwargs'])
  File "/opt/salt/lib/python2.7/site-packages/salt/loader.py", line 1830, in wrapper
    return f(*args, **kwargs)
  File "/opt/salt/lib/python2.7/site-packages/salt/states/file.py", line 4119, in replace
    backslash_literal=backslash_literal)
  File "/opt/salt/lib/python2.7/site-packages/salt/modules/file.py", line 2420, in replace
    check_perms(path, None, pre_user, pre_group, pre_mode)
  File "/opt/salt/lib/python2.7/site-packages/salt/modules/file.py", line 4460, in check_perms
    lattrs = lsattr(name)
  File "/opt/salt/lib/python2.7/site-packages/salt/modules/file.py", line 573, in lsattr
    results[vals[1]] = re.findall(r"[acdijstuADST]", vals[0])
IndexError: list index out of range
```

### Steps to Reproduce Issue
install 2018.3.x on AIX and use file.replace or file.lsattr 

### Versions Report
```
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.30.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Jul  9 2018, 14:45:55)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: ISO8859-1
        machine: 00CB2F274C00
        release: 1
         system: AIX
        version: Not Installed
```

**Comment by whytewolf** [comment]
ZD-2764

**Comment by rallytime** [comment]
@dmurphy18 Can you fix this for `2018.3.4` please?

**Comment by whytewolf** [comment]
ZD-3044

**Comment by whytewolf** [comment]
ZD-3135
