### ISSUE TITLE
Salt request timed out. The master is not responding.

### ISSUE THREAD

**Issue by slhu91** [saltstack/salt#49105]
### Description of Issue/Question
saltstack run exception error
sometimes success and sometimes failed
![image](https://user-images.githubusercontent.com/14175152/44078426-0255061c-9fd9-11e8-881b-2ae866e22638.png)

![image](https://user-images.githubusercontent.com/14175152/44078037-15988d58-9fd8-11e8-9930-4a2219cbc42a.png)
![image](https://user-images.githubusercontent.com/14175152/44078385-ec28d4f4-9fd8-11e8-816f-8e64eba0a13e.png)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
master version
![image](https://user-images.githubusercontent.com/14175152/44078470-259474f0-9fd9-11e8-8a88-878b5896807e.png)

minion version
![image](https://user-images.githubusercontent.com/14175152/44078511-3c01481c-9fd9-11e8-837a-7b2a73487ba9.png)

**Comment by slhu91** [comment]
debug in salt-minion, have follow info

minion return: {u'fun_args': [u'base.abc_test', {u'test': True}], u'jid': u'20180814145515520668', u'return': u'The minion function caused an exception: Traceback (most recent call last):
File "/data/saltstack/python/lib/python2.7/site-packages/salt/minion.py", line 1600, in _thread_return
return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
File "/data/saltstack/python/lib/python2.7/site-packages/salt/executors/direct_call.py", line 12, in execute
return func(*args, **kwargs)
File "/data/saltstack/python/lib/python2.7/site-packages/salt/modules/state.py", line 1236, in sls
initial_pillar=_get_initial_pillar(opts))
File "/data/saltstack/python/lib/python2.7/site-packages/salt/state.py", line 3987, in __init__
BaseHighState.__init__(self, opts)
File "/data/saltstack/python/lib/python2.7/site-packages/salt/state.py", line 2854, in __init__
self.avail = self.__gather_avail()
File "/data/saltstack/python/lib/python2.7/site-packages/salt/state.py", line 2864, in __gather_avail
avail[saltenv] = self.client.list_states(saltenv)
File "/data/saltstack/python/lib/python2.7/site-packages/salt/fileclient.py", line 392, in list_states
for path in self.file_list(saltenv):
File "/data/saltstack/python/lib/python2.7/site-packages/salt/fileclient.py", line 1276, in file_list
return salt.utils.data.decode(self.channel.send(load)) if six.PY2 
File "/data/saltstack/python/lib/python2.7/site-packages/salt/utils/async.py", line 64, in wrap
ret = self._block_future(ret)
File "/data/saltstack/python/lib/python2.7/site-packages/salt/utils/async.py", line 74, in _block_future
return future.result()
File "/data/saltstack/python/lib/python2.7/site-packages/tornado-4.5-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
raise_exc_info(self._exc_info)
File "/data/saltstack/python/lib/python2.7/site-packages/tornado-4.5-py2.7-linux-x86_64.egg/tornado/gen.py", line 1063, in run
yielded = self.gen.throw(*exc_info)
File "/data/saltstack/python/lib/python2.7/site-packages/salt/transport/zeromq.py", line 324, in send
ret = yield self._crypted_transfer(load, tries=tries, timeout=timeout, raw=raw)
File "/data/saltstack/python/lib/python2.7/site-packages/tornado-4.5-py2.7-linux-x86_64.egg/tornado/gen.py", line 1055, in run
value = future.result()
File "/data/saltstack/python/lib/python2.7/site-packages/tornado-4.5-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
raise_exc_info(self._exc_info)
File "/data/saltstack/python/lib/python2.7/site-packages/tornado-4.5-py2.7-linux-x86_64.egg/tornado/gen.py", line 1063, in run
yielded = self.gen.throw(*exc_info)
File "/data/saltstack/python/lib/python2.7/site-packages/salt/transport/zeromq.py", line 292, in _crypted_transfer
ret = yield _do_transfer()
File "/data/saltstack/python/lib/python2.7/site-packages/tornado-4.5-py2.7-linux-x86_64.egg/tornado/gen.py", line 1055, in run
value = future.result()
File "/data/saltstack/python/lib/python2.7/site-packages/tornado-4.5-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
raise_exc_info(self._exc_info)
File "/data/saltstack/python/lib/python2.7/site-packages/tornado-4.5-py2.7-linux-x86_64.egg/tornado/gen.py", line 1063, in run
yielded = self.gen.throw(*exc_info)
File "/data/saltstack/python/lib/python2.7/site-packages/salt/transport/zeromq.py", line 276, in _do_transfer
tries=tries,
File "/data/saltstack/python/lib/python2.7/site-packages/tornado-4.5-py2.7-linux-x86_64.egg/tornado/gen.py", line 1055, in run
value = future.result()
File "/data/saltstack/python/lib/python2.7/site-packages/tornado-4.5-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 238, in result
raise_exc_info(self._exc_info)
File "<string>", line 3, in raise_exc_infonSaltReqTimeoutError: Message timed out', u'success': False, u'fun': u'state.sls', u'out': u'nested'}

**Comment by garethgreenaway** [comment]
@slhu91 Thanks for the report.  It appears that at the start of the logs the minion had an exception.  can you provide information about what Salt function you were running that may have caused this?

**Comment by slhu91** [comment]
@garethgreenaway Is there an answer?
