### ISSUE TITLE
gitfs: git push --force doesn't invalidate caches

### ISSUE THREAD

**Issue by dhs-rec** [saltstack/salt#49155]
### Description of Issue/Question
After doing a `git push --force` on a repository that serves as a gitfs backend the Git caches on the Salt master are not invalidated. It must be done manually and the master must be restarted in order to function properly again. Only indication are messages like this in the log:

> Aug 16 15:13:22 ip-172-31-4-233 salt-master[14492]: [ERROR   ] Error in function _file_hash:
Aug 16 15:13:22 ip-172-31-4-233 salt-master[14492]: Traceback (most recent call last):
Aug 16 15:13:22 ip-172-31-4-233 salt-master[14492]:   File "/usr/lib/python2.7/dist-packages/salt/master.py", line 1776, in run
Aug 16 15:13:22 ip-172-31-4-233 salt-master[14492]:     ret = getattr(self, func)(load)
Aug 16 15:13:22 ip-172-31-4-233 salt-master[14492]:   File "/usr/lib/python2.7/dist-packages/salt/fileserver/__init__.py", line
Aug 16 15:13:22 ip-172-31-4-233 salt-master[14492]:     return self.__file_hash_and_stat(load)[0]
Aug 16 15:13:22 ip-172-31-4-233 salt-master[14492]:   File "/usr/lib/python2.7/dist-packages/salt/fileserver/__init__.py", line
Aug 16 15:13:22 ip-172-31-4-233 salt-master[14492]:     load['saltenv'])
Aug 16 15:13:22 ip-172-31-4-233 salt-master[14492]:   File "/usr/lib/python2.7/dist-packages/salt/fileserver/__init__.py", line
Aug 16 15:13:22 ip-172-31-4-233 salt-master[14492]:     fnd = self.servers[fstr](path, saltenv, **kwargs)
Aug 16 15:13:22 ip-172-31-4-233 salt-master[14492]:   File "/usr/lib/python2.7/dist-packages/salt/fileserver/gitfs.py", line 15
Aug 16 15:13:22 ip-172-31-4-233 salt-master[14492]:     return _gitfs().find_file(path, tgt_env=tgt_env, **kwargs)
Aug 16 15:13:22 ip-172-31-4-233 salt-master[14492]:   File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 2750, i
Aug 16 15:13:22 ip-172-31-4-233 salt-master[14492]:     blob, blob_hexsha, blob_mode = repo.find_file(repo_path, tgt_env)
Aug 16 15:13:22 ip-172-31-4-233 salt-master[14492]:   File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 1303, i
Aug 16 15:13:22 ip-172-31-4-233 salt-master[14492]:     tree = self.get_tree(tgt_env)
Aug 16 15:13:22 ip-172-31-4-233 salt-master[14492]:   File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 1012, i
Aug 16 15:13:22 ip-172-31-4-233 salt-master[14492]:     candidate = func(tgt_ref)
Aug 16 15:13:22 ip-172-31-4-233 salt-master[14492]:   File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 1350, i
Aug 16 15:13:22 ip-172-31-4-233 salt-master[14492]:     'refs/remotes/origin/{0}'.format(ref)).commit.tree
Aug 16 15:13:22 ip-172-31-4-233 salt-master[14492]:   File "/usr/lib/python2.7/dist-packages/git/refs/symbolic.py", line 183, i
Aug 16 15:13:22 ip-172-31-4-233 salt-master[14492]:     obj = self._get_object()
Aug 16 15:13:22 ip-172-31-4-233 salt-master[14492]:   File "/usr/lib/python2.7/dist-packages/git/refs/symbolic.py", line 176, i
Aug 16 15:13:22 ip-172-31-4-233 salt-master[14492]:     return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recur
Aug 16 15:13:22 ip-172-31-4-233 salt-master[14492]:   File "/usr/lib/python2.7/dist-packages/git/objects/base.py", line 65, in
Aug 16 15:13:22 ip-172-31-4-233 salt-master[14492]:     oinfo = repo.odb.info(sha1)
Aug 16 15:13:22 ip-172-31-4-233 salt-master[14492]:   File "/usr/lib/python2.7/dist-packages/gitdb/db/base.py", line 205, in in
Aug 16 15:13:22 ip-172-31-4-233 salt-master[14492]:     return self._db_query(sha).info(sha)
Aug 16 15:13:22 ip-172-31-4-233 salt-master[14492]:   File "/usr/lib/python2.7/dist-packages/gitdb/db/base.py", line 192, in _d
Aug 16 15:13:22 ip-172-31-4-233 salt-master[14492]:     raise BadObject(sha)
Aug 16 15:13:22 ip-172-31-4-233 salt-master[14492]: BadObject: BadObject: 058f057b139715adfa8b54b2f44a1f692c363625

### Setup
Salt master with a gitfs fileserver backend.

### Steps to Reproduce Issue
Push a change to the configured gitfs repo
Wait until the master has that change cached
Remove that change from the local clone (git reset --hard)
Do a `git push --force` to remove the change on the Git server
Watch the master falling apart (see above for logs)

### Versions Report
```
# salt --versions-report                                                            :(
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-1062-aws
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by Ch3LL** [comment]
ping @terminalmage any ideas here?

**Comment by terminalmage** [comment]
This honestly makes no sense, as the "cache" is _always_ replaced when a file is requested. The files in the "cache" are only there because we need the file to exist locally for it to be transferred to the minion, and we pull it out of the git objects to do so.

There is really nothing to invalidate.

**Comment by dhs-rec** [comment]
Hmm, the server is an Ubuntu 16.04. Will try to upgrade to 18.04 and see what happens.

**Comment by terminalmage** [comment]
OK, then this is probably a long-since-fixed upstream bug in GitPython.

**Comment by jacksontj** [comment]
I actually ran into this same issue as well. After upgrading GitPython and gitdb to 2.x+ (2.1.8 and 2.0.4 respectively) I am unable to reproduce the issue. I did a quick search and couldn't find the exact issue upstream, but there where a few ;)
