### ISSUE TITLE
Faulty reference to get_umask in file.managed

### ISSUE THREAD

**Issue by bittermandel** [saltstack/salt#49157]
### Description of Issue/Question
When using file.managed with mode not set and not on Windows, Salt crashes as it tries to import an attribute that does not exist in salt.utils.files:
```
[INFO    ] Executing state file.managed for [/etc/systemd/system/iptables-mangle-ttl.service]
[DEBUG   ] In saltenv 'base', looking at rel_path 'sys/iptables/files/iptables-mangle-ttl.service' to resolve 'salt://sys/iptables/files/iptables-mangle-ttl.service'
[DEBUG   ] In saltenv 'base', ** considering ** path '/var/cache/salt/minion/files/base/sys/iptables/files/iptables-mangle-ttl.service' to resolve 'salt://sys/iptables/files/iptables-mangle-ttl.service'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://sys/iptables/files/iptables-mangle-ttl.service'
[DEBUG   ] No dest file found
[INFO    ] Fetching file from saltenv 'base', ** done ** 'sys/iptables/files/iptables-mangle-ttl.service'
[DEBUG   ] Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 2575, in managed
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 5476, in manage_file
    mask = salt.utils.files.get_umask()
AttributeError: 'module' object has no attribute 'get_umask'

[ERROR   ] Unable to manage file: 'module' object has no attribute 'get_umask'
```

### Setup
Salt 2018.3.2
Debian 9.4

```yaml
  file.managed:
    - name: /etc/systemd/system/iptables-mangle-ttl.service
    - source: salt://sys/iptables/files/iptables-mangle-ttl.service
```

### Steps to Reproduce Issue
Use file.managed and do not set mode.
File's umask:
```➜  salt git:(master) ls -la states/sys/iptables/files/iptables-mangle-ttl.service
-rw-r--r--@ 1 jonathangrahl  staff  273 Jun 29 15:56 states/sys/iptables/files/iptables-mangle-ttl.service
```

### Versions Report
```jonathangra@server1:~$ sudo salt-call --versions-report
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Nov 24 2017, 17:33:09)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.4
         locale: ISO-8859-1
        machine: x86_64
        release: 4.9.0-6-amd64
         system: Linux
        version: debian 9.4```

**Comment by Ch3LL** [comment]
i cannot replicate this and `salt.utils.files.get_umask()` does exist in the code. how did you install salt? i'm wondering if you have some old pyc files that possibly need to be cleared out?
