### ISSUE TITLE
METADATA file is invalid due to tornado requirements

### ISSUE THREAD

**Issue by apt-itude** [saltstack/salt#49165]
### Description of Issue
Installing salt via pip in a Python 2.7 environment succeeds, but produces the following error output:
```
salt 2018.3.2 has requirement tornado<5.0,>=4.2.1, but you'll have tornado 5.1 which is incompatible.
```

salt has a conditional dependency on the tornado library, depending on the Python version:
```
tornado>=4.2.1,<6.0; python_version < '3'
tornado>=4.2.1,<5.0; python_version >= '3.4'
```

pip obeys the `python_version` environment markers and correctly installs tornado 5.1, but the resulting `METADATA` file it generates omits the environment markers:
```
Requires-Dist: tornado (<6.0,>=4.2.1)
Requires-Dist: tornado (<5.0,>=4.2.1)
```

Also, not that `pip show salt` shows tornado as a requirement twice:
```$ pip show salt
Name: salt
Version: 2018.3.2
Summary: Portable, distributed, remote execution and configuration management system
Home-page: http://saltstack.org
Author: Thomas S Hatch
Author-email: thatch45@gmail.com
License: Apache Software License 2.0
Location: /Users/athompson/.pyenv/versions/2.7.15/envs/salt-2.7/lib/python2.7/site-packages
Requires: PyYAML, tornado, tornado, requests, msgpack, futures, MarkupSafe, Jinja2, pyzmq, pycrypto
Required-by:
```

This doesn't cause a functional problem with salt; the real problem is that the invalid METADATA file causes issues in other tools. 

In particular the Bazel [rules_python](https://github.com/bazelbuild/rules_python) library fails because it appears that the package depends on tornado twice. 

In addition, `pip-autoremove` fails:
```
$ pip-autoremove salt
Traceback (most recent call last):
  File "/Users/athompson/.pyenv/versions/salt-2.7/bin/pip-autoremove", line 11, in <module>
    sys.exit(main())
  File "/Users/athompson/.pyenv/versions/2.7.15/envs/salt-2.7/lib/python2.7/site-packages/pip_autoremove.py", line 106, in main
    autoremove(args, yes=opts.yes)
  File "/Users/athompson/.pyenv/versions/2.7.15/envs/salt-2.7/lib/python2.7/site-packages/pip_autoremove.py", line 21, in autoremove
    dead = list_dead(names)
  File "/Users/athompson/.pyenv/versions/2.7.15/envs/salt-2.7/lib/python2.7/site-packages/pip_autoremove.py", line 29, in list_dead
    graph = get_graph()
  File "/Users/athompson/.pyenv/versions/2.7.15/envs/salt-2.7/lib/python2.7/site-packages/pip_autoremove.py", line 89, in get_graph
    for req in requires(dist):
  File "/Users/athompson/.pyenv/versions/2.7.15/envs/salt-2.7/lib/python2.7/site-packages/pip_autoremove.py", line 95, in requires
    return map(get_distribution, dist.requires())
  File "/Users/athompson/.pyenv/versions/2.7.15/envs/salt-2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 471, in get_distribution
    dist = get_provider(dist)
  File "/Users/athompson/.pyenv/versions/2.7.15/envs/salt-2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 347, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/Users/athompson/.pyenv/versions/2.7.15/envs/salt-2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 633, in find
    raise VersionConflict(dist, req)
pkg_resources.VersionConflict: (tornado 5.1 (/Users/athompson/.pyenv/versions/2.7.15/envs/salt-2.7/lib/python2.7/site-packages), Requirement.parse('tornado<5.0,>=4.2.1'))
```

### Versions Report
```
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15 (default, Jul 20 2018, 11:18:10)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 5.1
            ZMQ: 4.2.5

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 15.6.0
         system: Darwin
        version: 10.11.6 x86_64
```

**Comment by gtmanfred** [comment]
Is there a way that we can make these definitions so that metadata is correct?  because we are going to have to add another one, because we still support python 3.4 for centos, but tornado 6.0 is going to drop support for 3.4 and 2.7, so we will definitely need these marker requirements then, if we still support 2.7.
