### ISSUE TITLE
file.directory state fails if directory contains an invalid symlink

### ISSUE THREAD

**Issue by mchugh19** [saltstack/salt#49204]
### Description of Issue/Question
If a file.directory state is run on a directory which contains a broken symlink, the state crashes.

### Setup
test state:
```
/tmp/dirtest:
  file.directory:
    - user: root
    - group: root
    - mode: 755
    - recurse:
      - user
      - group
      - mode
```

### Steps to Reproduce Issue
Success
```
# salt-call state.sls dir
local:
----------
          ID: /tmp/dirtest
    Function: file.directory
      Result: True
     Comment: The directory /tmp/dirtest is in the correct state
     Started: 10:34:25.797989
    Duration: 11.287 ms
     Changes:

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:  11.287 ms
```
Create bad symlink
```
ln -s /tmp/dirtest/thing /tmp/dirtest/nope
```
State now crashes
```
# salt-call state.sls dir
/usr/local/lib/python2.7/dist-packages/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/salt/state.py", line 1905, in call
    **cdata['kwargs'])
  File "/usr/local/lib/python2.7/dist-packages/salt/loader.py", line 1830, in wrapper
    return f(*args, **kwargs)
  File "/var/cache/salt/minion/extmods/states/file.py", line 3421, in directory
    full, ret, user, group, file_mode, None, follow_symlinks)
  File "/usr/local/lib/python2.7/dist-packages/salt/modules/file.py", line 4460, in check_perms
    lattrs = lsattr(name)
  File "/usr/local/lib/python2.7/dist-packages/salt/modules/file.py", line 564, in lsattr
    raise SaltInvocationError("File or directory does not exist.")
SaltInvocationError: File or directory does not exist.

local:
----------
          ID: /tmp/dirtest
    Function: file.directory
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/local/lib/python2.7/dist-packages/salt/state.py", line 1905, in call
                  **cdata['kwargs'])
                File "/usr/local/lib/python2.7/dist-packages/salt/loader.py", line 1830, in wrapper
                  return f(*args, **kwargs)
                File "/var/cache/salt/minion/extmods/states/file.py", line 3421, in directory
                  full, ret, user, group, file_mode, None, follow_symlinks)
                File "/usr/local/lib/python2.7/dist-packages/salt/modules/file.py", line 4460, in check_perms
                  lattrs = lsattr(name)
                File "/usr/local/lib/python2.7/dist-packages/salt/modules/file.py", line 564, in lsattr
                  raise SaltInvocationError("File or directory does not exist.")
              SaltInvocationError: File or directory does not exist.
     Started: 10:34:39.631296
    Duration: 27.711 ms
     Changes:

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:  27.711 ms
```

### Versions Report
```
Salt Version:
           Salt: 2018.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 5.0.2
            ZMQ: 4.1.6

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-130-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by gtmanfred** [comment]
I hate that lsattr function.

Thanks for reporting this, if you had time to fix it, we would greatly appreciate it, probably could get away with just catching that exception in a try: except: block.

Otherwise we will get it fixed.

Thanks!
Daniel

**Comment by gtmanfred** [comment]
Actually, fixed here.

https://github.com/saltstack/salt/pull/49209

**Comment by gtmanfred** [comment]
The fix has been merged.

Thanks for reporting.
Daniel
