### ISSUE TITLE
saltcheck throwing IOLoop is already running errors

### ISSUE THREAD

**Issue by mchugh19** [saltstack/salt#49207]
### Description of Issue/Question
local runs with salt-call seem to work fine, but when run through the eventbus, saltcheck throws `IOLoop is already running` errors. 
```
# salt-call saltcheck.run_highstate_tests
local:
    |_
      ----------
      base.common:
          ----------
          boto3-installed:
              Pass
...
```

```
# salt MINIONID saltcheck.run_highstate_tests
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1600, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/var/cache/salt/minion/extmods/modules/saltcheck.py", line 177, in run_highstate_tests
        scheck = SaltCheck()
      File "/var/cache/salt/minion/extmods/modules/saltcheck.py", line 305, in __init__
        self.salt_lc = salt.client.Caller()
      File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 2076, in __init__
        self.sminion = salt.minion.SMinion(self.opts)
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 787, in __init__
        lambda: self.eval_master(self.opts, failed=True)
      File "/usr/lib64/python2.7/site-packages/tornado/ioloop.py", line 439, in run_sync
        self.start()
      File "/usr/lib64/python2.7/site-packages/tornado/ioloop.py", line 730, in start
        raise RuntimeError("IOLoop is already running")
    RuntimeError: IOLoop is already running
```

### Setup
Create ntp/init.sls to install ntp package
Create ntp/saltcheck-tests/ntp.tst with the following content
```
ntp-client-installed:
  module_and_function: pkg.version
  args:
    - ntp
  assertion: assertNotEmpty
```
Run ntp test by salt-call and salt
```
salt-call saltcheck.run_state_tests ntp
local:
    |_
      ----------
      ntp:
          ----------
          ntp-client-installed:
              Pass
...

salt MINIONID saltcheck.run_state_tests ntp
The minion function caused an exception
...
```

### Steps to Reproduce Issue
The fix committed in https://github.com/wcannon/salt-check/commit/d7056f824cd4218e74713049620846eb8aed2226 does a replace line 305
```
self.salt_lc = salt.client.Caller()
```

with 
```
__opts__ = salt.config.minion_config('/etc/salt/minion')
__opts__['file_client'] = 'local'
self.salt_lc = salt.client.Caller(mopts=__opts__)
```

This does seem to resolve the problem, but this likely isn't suitable for upsteaming as it the minion config file path can't be guantereed, and this path would not work on windows. What is the proper fix here?

### Versions Report
```
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: 1.11.5
       cherrypy: 5.6.0
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.26.3
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: 0.26.4
         Python: 2.7.5 (default, Apr 11 2018, 07:36:10)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.6

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.3.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```

**Comment by gtmanfred** [comment]
you should be able to get the conf_file from `__opts__['conf_file']` if you are just loading the same minion config file as what was loaded for the minion running the command.

You probably also don't want to overwrite `__opts__` in a function, because that is the injected variable, so you will be overwriting the __opts__ for that running minion process.

**Comment by mchugh19** [comment]
So would this be correct?
```
local_opts = salt.config.minion_config(__opts__['conf_file'])
local_opts['file_client'] = 'local'
self.salt_lc = salt.client.Caller(mopts=local_opts)
```
This seems to work for both the salt-call and salt use-cases.

**Comment by gtmanfred** [comment]
Yup, that should be correct.

**Comment by mchugh19** [comment]
Sweet! Thanks!
