### ISSUE TITLE
[Salt-Cloud] Cannot ascii encode character when spinning up EC2 instance

### ISSUE THREAD

**Issue by theonlyjohnny** [saltstack/salt#49304]
### Description of Issue/Question

I get this Exception: `UnicodeEncodeError: 'ascii' codec can't encode character u'→' in position 317: ordinal not in range(128)` any time I try to spin up a box on AWS EC2. The creation succeeds, but the salt-cloud command errors.

I found a similar issue, for VMWare @ https://github.com/saltstack/salt/issues/30277

Error:

```
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 281, in run
self.config.get('names')
File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1454, in run_profile
ret[name] = self.create(vm_)
File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1284, in create
output = self.clouds[func](vm_)
File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 2760, in create
for key, value in six.iteritems(__utils__['cloud.bootstrap'](vm_, __opts__)):
File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 566, in bootstrap
deployed = deploy_script(**deploy_kwargs)
File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 1547, in deploy_script
if root_cmd(deploy_command, tty, sudo, **ssh_kwargs) != 0:
File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 2248, in root_cmd
retcode = _exec_ssh_cmd(cmd, allow_failure=allow_failure, **kwargs)
File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 1809, in _exec_ssh_cmd
stdout, stderr = proc.recv()
File "/usr/lib/python2.7/dist-packages/salt/utils/vt.py", line 310, in recv
return self._recv(maxsize)
File "/usr/lib/python2.7/dist-packages/salt/utils/vt.py", line 688, in _recv
self.stream_stdout.write(stdout)
UnicodeEncodeError: 'ascii' codec can't encode character u'→' in position 317: ordinal not in range(128)
```

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

`/etc/salt/cloud`:

```
script_args: stable 2018.3.2
start_action: state.apply
```

Provider (personal info removed):
```
{provider}:                      
  driver: ec2                                          
  id: {id}
  key: {key}
  private_key: {ssh_key}
  keyname: {keypair_name}                         
  subnetid: {subnet}
  minion:                                              
    startup_states: highstate                          
    master: {master_ip}
  ssh_interface: private_ips                           
  location: us-west-1                                  
  availability_zone: us-west-1a                        
  ssh_username: admin                                  
```

Profile (personal info removed):

```
{profile}:
image: ami-c8a68ba8
provider: {provider}
size: c5.large
block_device_mappings:
- DeviceName: xvdb
Ebs.VolumeSize: 50
Ebs.VolumeType: gp2
tag: {'Role': ''}
sync_after_install: all
iam_profile: ''
securitygroupid:
- {sg0}
- {sg1}
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
`sudo salt-cloud -p {profile} {hostname} -l debug`

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
sudo salt-cloud --versions-report
Salt Version:
Salt: 2018.3.0

Dependency Versions:
Apache Libcloud: 1.5.0
cffi: Not Installed
cherrypy: Not Installed
dateutil: 2.5.3
docker-py: 1.10.6
gitdb: 2.0.0
gitpython: 2.1.1
ioflo: Not Installed
Jinja2: 2.9.4
libgit2: Not Installed
libnacl: Not Installed
M2Crypto: Not Installed
Mako: Not Installed
msgpack-pure: Not Installed
msgpack-python: 0.4.8
mysql-python: Not Installed
pycparser: Not Installed
pycrypto: 2.6.1
pycryptodome: Not Installed
pygit2: Not Installed
Python: 2.7.13 (default, Nov 24 2017, 17:33:09)
python-gnupg: Not Installed
PyYAML: 3.12
PyZMQ: 16.0.2
RAET: Not Installed
smmap: 2.0.1
timelib: Not Installed
Tornado: 4.4.3
ZMQ: 4.2.1

System Versions:
dist: debian 9.4
locale: UTF-8
machine: x86_64
release: 4.9.0-4-amd64
system: Linux
version: debian 9.4
```

**Comment by Ch3LL** [comment]
i am having a hard time replicating this and tried multiple times, ping @saltstack/team-cloud any ideas here?

**Comment by gtmanfred** [comment]
@Ch3LL can you put a unicode character in your PROMPT and run it again, and see if that causes an issue?

also, possibly put a unicode character in the prompt on the remote machine.

**Comment by gtmanfred** [comment]
So, i think it needs to be in the `PS1` which is what the vt.py terminal stuff looks for when trying to match when it can put in a new command, because bash has returned.

```
[root@23740b925608 /]# echo $PS1
[\u@\h \W]\$
```

Try setting it to something like

```
export PS1='[\u@\h \W]→ '
```

**Comment by gtmanfred** [comment]
You should also be able to use this reactor and be able to trigger bootstrapping an instance that is already online.

https://github.com/saltstack-formulas/ec2-autoscale-reactor/blob/master/ec2-autoscale/init.sls

**Comment by Ch3LL** [comment]
hmm i've been trying for the last 30 minutes on multiple versions and it just keeps holding here:

```
[DEBUG   ] Connection to <ip> closed.
[DEBUG   ] Removed /tmp/.saltcloud-75294ce4-e36a-4cfd-8cda-3819393819/minion

```

can you build a VM? i'm wondiner if there is an issue with aws, although i dont see anything in their status website, but i can't get past this point to test the issue
