### ISSUE TITLE
[Salt-Cloud] StopIteration on destruction of AWS EC2 Instance

### ISSUE THREAD

**Issue by theonlyjohnny** [saltstack/salt#49300]
### Description of Issue/Question

StopIteration error occurs on every termination of an EC2 instance. This issue occurs across AWS regions, with the same result every time.
This causes the process exit code to be non-0, and means we have to "ignore" errors, so we don't know if salt-cloud ever actually fails. This happens automatically routinely.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

Profile:
```
{profile}:
  image: {ami}
  provider: {provider}
  size: c5.large
  block_device_mappings:
    - DeviceName: xvda
      Ebs.VolumeSize: 16
      Ebs.VolumeType: gp2
  tag: {'Role': '{role}'}
  sync_after_install: all
  iam_profile: '{iam_profile}'
  securitygroupid:
    - {sg0}
    - {sg1}
```
Provider:
```
{provider}:                
  driver: ec2                                           
  id: 'use-instance-role-credentials'                   
  key: 'use-instance-role-credentials'                  
  private_key: {ssh key}
  keyname: {keypair name}                          
  subnetid: {subnet}
  securitygroupid:                                      
    - {sg0}
  minion:                                               
    startup_states: highstate                           
    master: {salt master}
  ssh_interface: private_ips                            
  location: us-west-1                                   
  availability_zone: us-west-1a                         
  ssh_username: admin
```

`/etc/salt/cloud`:
```
script_args: stable 2018.3.2
start_action: state.apply
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

Create EC2 Instance on AWS (`sudo salt-cloud -p {profile} {NODE_NAME}-l debug`)
Destroy that instance (`sudo salt-cloud -d  {NODE_NAME} -l debug`)

Debug Logs:
```[INFO    ] Destroying in non-parallel mode.
[DEBUG   ] Using AWS endpoint: ec2.us-west-1.amazonaws.com
[DEBUG   ] Starting new HTTP connection (1): 169.254.169.254:80
[DEBUG   ] http://169.254.169.254:80 "GET /latest/meta-data/iam/security-credentials/ HTTP/1.1" 200 10
[DEBUG   ] Starting new HTTP connection (1): 169.254.169.254:80
[DEBUG   ] http://169.254.169.254:80 "GET /latest/meta-data/iam/security-credentials/ROLE HTTP/1.1" 200 886
[DEBUG   ] AWS Request: https://ec2.us-west-1.amazonaws.com/?Action=DescribeInstances&Filter.1.Name=tag%3AName&Filter.1.Value.1=NODE_NAME&Version=2014-10-01
[DEBUG   ] Starting new HTTPS connection (1): ec2.us-west-1.amazonaws.com:443
[DEBUG   ] https://ec2.us-west-1.amazonaws.com:443 "GET /?Action=DescribeInstances&Filter.1.Name=tag%3AName&Filter.1.Value.1=NODE_NAME&Version=2014-10-01 HTTP/1.1" 200 None
[DEBUG   ] AWS Response Status Code: 200
[DEBUG   ] Using AWS endpoint: ec2.us-west-1.amazonaws.com
[DEBUG   ] AWS Request: https://ec2.us-west-1.amazonaws.com/?Action=DescribeInstanceAttribute&Attribute=disableApiTermination&InstanceId=INSTANCE_ID&Version=2014-10-01
[DEBUG   ] Starting new HTTPS connection (1): ec2.us-west-1.amazonaws.com:443
[DEBUG   ] https://ec2.us-west-1.amazonaws.com:443 "GET /?Action=DescribeInstanceAttribute&Attribute=disableApiTermination&InstanceId=INSTANCE_ID&Version=2014-10-01 HTTP/1.1" 200 None
[DEBUG   ] AWS Response Status Code: 200
[DEBUG   ] Termination Protection is disabled for NODE_NAME
[DEBUG   ] LazyLoaded cloud.fire_event
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event: tag = salt/cloud/NODE_NAME/destroying; data = {u'instance_id': 'INSTANCE_ID', u'_stamp': '2018-08-23T23:27:17.183092', u'name': 'NODE_NAME', u'event': u'destroying instance'}
[INFO    ] Renaming NODE_NAME to NODE_NAME-DEL3cdda5c007ba49a390a8a93a8d4b0019
[DEBUG   ] Using AWS endpoint: ec2.us-west-1.amazonaws.com
[DEBUG   ] AWS Request: https://ec2.us-west-1.amazonaws.com/?Action=DescribeInstances&Filter.1.Name=tag%3AName&Filter.1.Value.1=NODE_NAME&Version=2014-10-01
[DEBUG   ] Starting new HTTPS connection (1): ec2.us-west-1.amazonaws.com:443
[DEBUG   ] https://ec2.us-west-1.amazonaws.com:443 "GET /?Action=DescribeInstances&Filter.1.Name=tag%3AName&Filter.1.Value.1=NODE_NAME&Version=2014-10-01 HTTP/1.1" 200 None
[DEBUG   ] AWS Response Status Code: 200
[DEBUG   ] Tags to set for NODE_NAME: {u'Name': u'NODE_NAME-DEL3cdda5c007ba49a390a8a93a8d4b0019'}
[DEBUG   ] Using AWS endpoint: ec2.us-west-1.amazonaws.com
[DEBUG   ] AWS Request: https://ec2.us-west-1.amazonaws.com/?Action=CreateTags&ResourceId.1=INSTANCE_ID&Tag.0.Key=Name&Tag.0.Value=NODE_NAME-DEL3cdda5c007ba49a390a8a93a8d4b0019&Version=2014-10-01
[DEBUG   ] Starting new HTTPS connection (1): ec2.us-west-1.amazonaws.com:443
[DEBUG   ] https://ec2.us-west-1.amazonaws.com:443 "GET /?Action=CreateTags&ResourceId.1=INSTANCE_ID&Tag.0.Key=Name&Tag.0.Value=NODE_NAME-DEL3cdda5c007ba49a390a8a93a8d4b0019&Version=2014-10-01 HTTP/1.1" 200 None
[DEBUG   ] AWS Response Status Code: 200
[DEBUG   ] Using AWS endpoint: ec2.us-west-1.amazonaws.com
[DEBUG   ] AWS Request: https://ec2.us-west-1.amazonaws.com/?Action=DescribeTags&Filter.1.Name=resource-id&Filter.1.Value=INSTANCE_ID&Version=2014-10-01
[DEBUG   ] Starting new HTTPS connection (1): ec2.us-west-1.amazonaws.com:443
[DEBUG   ] https://ec2.us-west-1.amazonaws.com:443 "GET /?Action=DescribeTags&Filter.1.Name=resource-id&Filter.1.Value=INSTANCE_ID&Version=2014-10-01 HTTP/1.1" 200 None
[DEBUG   ] AWS Response Status Code: 200
[DEBUG   ] Setting the tags returned: [{u'resourceType': 'instance', u'resourceId': 'INSTANCE_ID', u'value': 'NODE_NAME-DEL3cdda5c007ba49a390a8a93a8d4b0019', u'key': 'Name'}, {u'resourceType': 'instance', u'resourceId': 'INSTANCE_ID', u'value': 'composer', u'key$: 'Role'}]
[INFO    ] Machine will be identified as NODE_NAME-DEL3cdda5c007ba49a390a8a93a8d4b0019 until it has been cleaned up.
[DEBUG   ] Using AWS endpoint: ec2.us-west-1.amazonaws.com
[DEBUG   ] AWS Request: https://ec2.us-west-1.amazonaws.com/?Action=TerminateInstances&InstanceId.1=INSTANCE_ID&Version=2014-10-01
[DEBUG   ] Starting new HTTPS connection (1): ec2.us-west-1.amazonaws.com:443
[DEBUG   ] https://ec2.us-west-1.amazonaws.com:443 "GET /?Action=TerminateInstances&InstanceId.1=INSTANCE_ID&Version=2014-10-01 HTTP/1.1" 200 None
[DEBUG   ] AWS Response Status Code: 200
[INFO    ] [{u'instanceId': 'INSTANCE_ID', u'currentState': {u'code': '32', u'name': 'shutting-down'}, u'previousState': {u'code': '16', u'name': 'running'}}]
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event: tag = salt/cloud/NODE_NAME/destroyed; data = {u'instance_id': 'INSTANCE_ID', u'_stamp': '2018-08-23T23:27:17.534290', u'name': 'NODE_NAME', u'event': u'destroyed instance'}
[DEBUG   ] Using AWS endpoint: ec2.us-west-1.amazonaws.com
[DEBUG   ] AWS Request: https://ec2.us-west-1.amazonaws.com/?Action=DescribeInstances&Filter.1.Name=tag%3AName&Filter.1.Value.1=NODE_NAME&Version=2014-10-01
[DEBUG   ] Starting new HTTPS connection (1): ec2.us-west-1.amazonaws.com:443
[DEBUG   ] https://ec2.us-west-1.amazonaws.com:443 "GET /?Action=DescribeInstances&Filter.1.Name=tag%3AName&Filter.1.Value.1=NODE_NAME&Version=2014-10-01 HTTP/1.1" 200 None
[DEBUG   ] AWS Response Status Code: 200
[ERROR   ] There was an error destroying machines:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 212, in run
    ret = mapper.destroy(names, cached=True)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1039, in destroy
    ret = self.clouds[fun](name)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 3191, in destroy
     node_metadata = _get_node(name)
   File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 3393, in _get_node
     return next(iter(instance_info))
 StopIteration
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
``` % salt --versions-report
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: 3.4.1
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Nov 24 2017, 17:33:09)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.4
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-4-amd64
         system: Linux
        version: debian 9.4```

**Comment by Ch3LL** [comment]
im having a hard time replicating this. ping @saltstack/team-cloud any ideas here?
