### ISSUE TITLE
2018.3.2 broke the servicenow module

### ISSUE THREAD

**Issue by claudekenni** [saltstack/salt#49403]
### Description of Issue/Question
Servicenow Module is not working anymore in 2018.3.2

### Steps to Reproduce Issue
```
root@:/srv# salt-call servicenow.non_structured_query table=cmdb_ci_linux_server name=fdsafsd
[INFO    ] Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
[INFO    ] Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
InvalidUsage: You must pass a query using either a dictionary or string (for advanced queries)
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 400, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 212, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/servicenow.py", line 144, in non_structured_query
    response = client.get(query)
  File "/usr/local/lib/python2.7/dist-packages/servicenow_rest/api.py", line 164, in get
    return self._request('GET', query, fields)
  File "/usr/local/lib/python2.7/dist-packages/servicenow_rest/api.py", line 143, in _request
    params=self._format_query(query, fields)
  File "/usr/local/lib/python2.7/dist-packages/servicenow_rest/api.py", line 111, in _format_query
    raise InvalidUsage("You must pass a query using either a dictionary or string (for advanced queries)")
InvalidUsage: You must pass a query using either a dictionary or string (for advanced queries)
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 400, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 212, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/servicenow.py", line 144, in non_structured_query
    response = client.get(query)
  File "/usr/local/lib/python2.7/dist-packages/servicenow_rest/api.py", line 164, in get
    return self._request('GET', query, fields)
  File "/usr/local/lib/python2.7/dist-packages/servicenow_rest/api.py", line 143, in _request
    params=self._format_query(query, fields)
  File "/usr/local/lib/python2.7/dist-packages/servicenow_rest/api.py", line 111, in _format_query
    raise InvalidUsage("You must pass a query using either a dictionary or string (for advanced queries)")
servicenow_rest.api.InvalidUsage: You must pass a query using either a dictionary or string (for advanced queries)
root@:/srv#
```
### Versions Report
```
root@:/srv# salt --versions-report
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.8.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.3.7
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-119-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by claudekenni** [comment]
It still works on our Production Salt Master with 2017.7

**Comment by claudekenni** [comment]
Differences between the Module:

```
root@lab08ld100:/srv# diff /usr/lib/python2.7/dist-packages/salt/modules/servicenow.py /root/servicenow.py
23c23
< from __future__ import absolute_import, unicode_literals, print_function
---
> from __future__ import absolute_import
27d26
< from salt.ext import six
135c134
<     # does isinstance(x, str)
---
>     # does isinstance(x,str)
143c142
<     query = six.text_type(query)
---
>     query = str(query)
```

**Comment by garethgreenaway** [comment]
@claudekenni Thanks for the report.  With 2018.3.x there was a big effort to make everything Unicode compliant, it appears that perhaps the ServiceNOW API does not like receiving Unicode strings.

**Comment by claudekenni** [comment]
With pysnow queries can be created as a dict.

I have written my own snow module and this function does the same as the non_structured_query function.

```python
def query(table, **kwargs):
    '''
    Run a query on a servicenow table and return all records
    
    :param table: The table name, e.g. sys_user
    :type  table: ``str``

    CLI Example:

    .. code-block:: bash

        salt myminion snow.query cmdb_ci 'role=web'
        salt myminion snow.query cmdb_ci role=web type=computer
    '''
    client = _get_client()
    resource = client.resource(api_path='/table/' + table)

    query={}
    for key, value in kwargs.items():
        if "__" not in key:
            query[key] = value

    response = resource.get(query=query).all()
    return response
```

**Comment by twangboy** [comment]
Closing this issue due to age and lack of activity. Please test this on version 3006.2 and create a new issue if the problem persists. The new issue template has more information and will allow us to track and reproduce the issue more effectively. Thanks!
