### ISSUE TITLE
Jobs.Last_Run Cache Failure

### ISSUE THREAD

**Issue by vangourd** [saltstack/salt#49450]
### Description of Issue/Question
These failures appear to be intermittent and occur after a job is more than a few minutes old. 
```
Exception occurred in runner jobs.last_run: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 387, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/runners/jobs.py", line 528, in last_run
    return print_job(last_job, ext_source)
  File "/usr/lib/python2.7/dist-packages/salt/runners/jobs.py", line 441, in print_job
    job = mminion.returners['{0}.get_load'.format(returner)](jid)
  File "/usr/lib/python2.7/dist-packages/salt/returners/local_cache.py", line 325, in get_load
    salt.utils.files.process_read_exception(exc, minions_path)
  File "/usr/lib/python2.7/dist-packages/salt/utils/files.py", line 212, in process_read_exception
    raise CommandExecutionError('{0} does not exist'.format(path))
CommandExecutionError: /var/cache/salt/master/jobs/b1/87f885f743eeef8fde1478137121114f6583ddf178a46359d0b6546dc93ab4/.minions.p does not exist
```
I noticed it occurring in my API calls

### Steps to Reproduce Issue
1. Run a **salt-run** `jobs.last_run` command on master for a specific function `grains.items` as an example
No corresponding output from `/var/log/salt/master` , `/var/log/salt/api` 

### Versions Report
```
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.3
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.5.5
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-134-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by Ch3LL** [comment]
my guess is you are running into this when your job cache is part of a scheduled clear before you run it?

**Comment by vangourd** [comment]
How do I found out where it might be configured to clear the job cache? Is this a default task based on thresholds to make sure the cache doesn't grow too unwieldy. 

I've tightened the amount of jobs executing at any given time to make sure it wasn't the API performing poorly at a high rate. So I'm only running a few jobs every hour or so.

**Comment by vangourd** [comment]
I'm so sorry I accidentally hit close and comment on mobile.

**Comment by Ch3LL** [comment]
and does this appear once a day possibly or more often?

**Comment by vangourd** [comment]
I just came back to the issue and now I can't seem to get it to act up again. I reduced the amount of queries I was making against the server by implementing some timer locking into some clients. The only other change I've made since then was removing the paramterer `"target-type": "list"`. Adding that now does not cause the issue to re-occur. 

I'll see if I can drum down if it happens only when under higher load.

**Comment by Ch3LL** [comment]
awesome just ping me when it happens again. any other data to help me try to replicate it will help

**Comment by tengkongyixu** [comment]
in the same version of satl, there are same problem!!

------------------------------
getJobResultFile : param is [ filePath=/var/log/salt/20181017164930705375.log]
Exception occurred in runner jobs.lookup_jid: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 387, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/runners/jobs.py", line 128, in lookup_jid
    display_progress=display_progress
  File "/usr/lib/python2.7/site-packages/salt/runners/jobs.py", line 198, in list_job
    job = mminion.returners['{0}.get_load'.format(returner)](jid)
  File "/usr/lib/python2.7/site-packages/salt/returners/local_cache.py", line 325, in get_load
    salt.utils.files.process_read_exception(exc, minions_path)
  File "/usr/lib/python2.7/site-packages/salt/utils/files.py", line 212, in process_read_exception
    raise CommandExecutionError('{0} does not exist'.format(path))
CommandExecutionError: /var/cache/salt/master/jobs/49/8a87ba24638b11b3397cfce087fb708ddab0dc0d75e802d6125cb7875fd70d/.minions.p does not exist
-------------------------------

four times happend in  a week.

please help me!!

**Comment by Ch3LL** [comment]
ping @saltstack/team-core any ideas on why this might be occuring?

**Comment by vangourd** [comment]
@Ch3LL 

I still seem to have an issue in querying the Salt-API. I consistently run out of memory and have to reset salt VM's in order to return responsiveness.

How could I help in debugging these issues as I think you're doing great work?

I was looking into starting Salt in a debugging mode or using some utility to profile the memory usage.

**Comment by Ch3LL** [comment]
can you upload a sanitized version of the master debug logs when this occurs for a given job. Please include from when the job was initiated to when you run `jobs.last_run`

**Comment by vangourd** [comment]
@Ch3LL 

Over the period this issue has been open I have begun describing what is a different issue than the one I opened this issue for in the last few comments.

I will open an issue for the new problem and I promise I will get a confirmation on whether or not *last_run* produces the same error for me. Today. 

----
My original issue was an error (500) when querying for the specific job. Ignore the comments on memory consumption as that is a different command and different problem.

**Comment by vangourd** [comment]
@Ch3LL 

The issue with last_run appears to be fixed with the newer version of Salt. I cannot get it to repeat the broken behavior.  Thanks for the help!!
