### ISSUE TITLE
signal handler for SIGUSR1 goes wrong

### ISSUE THREAD

**Issue by thuhak** [saltstack/salt#49463]
### Description of Issue/Question

There is a signal handler for SIGUSR1, which will print current stack frame traceback. 
in utils/debug.py

```python
def _makepretty(printout, stack):
    '''
    Pretty print the stack trace and environment information
    for debugging those hard to reproduce user problems.  :)
    '''
    printout.write('======== Salt Debug Stack Trace =========\n')
    traceback.print_stack(stack, file=printout)
    printout.write('=========================================\n')


def _handle_sigusr1(sig, stack):
    '''
    Signal handler for SIGUSR1, only available on Unix-like systems
    '''
    # When running in the foreground, do the right  thing
    # and spit out the debug info straight to the console
    if sys.stderr.isatty():
        output = sys.stderr
        _makepretty(output, stack)
    else:
        filename = 'salt-debug-{0}.log'.format(int(time.time()))
        destfile = os.path.join(tempfile.gettempdir(), filename)
        with salt.utils.files.fopen(destfile, 'w') as output:
            _makepretty(output, salt.utils.stringutils.to_str(stack))
```

The _makepretty should get a frame object parameter, not a str type.
Therefore,when i send SIGUSR1 to salt-master process, there will be a exception as below:

```
8月 31 11:13:25 t-shhq-infratest-01 salt-master[28444]: [ERROR   ] Future exception was never retrieved: Traceback (most recent call last):
8月 31 11:13:25 t-shhq-infratest-01 salt-master[28444]: File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 230, in wrapper
8月 31 11:13:25 t-shhq-infratest-01 salt-master[28444]: yielded = next(result)
8月 31 11:13:25 t-shhq-infratest-01 salt-master[28444]: File "/usr/lib/python2.7/site-packages/salt/utils/process.py", line 501, in run
8月 31 11:13:25 t-shhq-infratest-01 salt-master[28444]: time.sleep(10)
8月 31 11:13:25 t-shhq-infratest-01 salt-master[28444]: File "/usr/lib/python2.7/site-packages/salt/utils/debug.py", line 44, in _h...igusr1
8月 31 11:13:25 t-shhq-infratest-01 salt-master[28444]: _makepretty(output, salt.utils.stringutils.to_str(stack))
8月 31 11:13:25 t-shhq-infratest-01 salt-master[28444]: File "/usr/lib/python2.7/site-packages/salt/utils/stringutils.py", line 93,...to_str
8月 31 11:13:25 t-shhq-infratest-01 salt-master[28444]: raise TypeError('expected str, bytearray, or unicode')
8月 31 11:13:25 t-shhq-infratest-01 salt-master[28444]: TypeError: expected str, bytearray, or unicode
```

### Versions Report

Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Apr 11 2018, 07:36:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.6

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.2.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core

**Comment by Ch3LL** [comment]
looks like i'm able to replicate this. working on fix now
