### ISSUE TITLE
salt-ssh with ansible roster is broken?

### ISSUE THREAD

**Issue by Oloremo** [saltstack/salt#49665]
### Description of Issue/Question
Look like salt-ssh with ansible roaster is broken or maybe I'm doing something wrong?

### Steps to Reproduce Issue
```
# cat roster.ini
[cluster]
delme-salt-rm
delme-salt-[01:30]
```
```
[root@delme-salt-rm salt]# salt-ssh -c /opt/salt --roster ansible --roster-file roster.ini '*'  test.ping
[cluster]:
    ssh: Could not resolve hostname cluster: Name or service not known

[root@delme-salt-rm salt]# salt-ssh -c /opt/salt --roster ansible --roster-file roster.ini 'cluster'  test.ping
[cluster]:
    ssh: Could not resolve hostname cluster: Name or service not known

[root@delme-salt-rm salt]# salt-ssh -c /opt/salt --roster ansible --roster-file roster.ini 'delme-salt-rm'  test.ping
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
SaltRenderError: expected '<document start>', but found '<scalar>'
  in "<unicode string>", line 2, column 1:
    delme-salt-rm
    ^
Traceback (most recent call last):
  File "/bin/salt-ssh", line 11, in <module>
    load_entry_point('salt-ssh==2018.3.2', 'console_scripts', 'salt-ssh')()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 425, in salt_ssh
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/ssh.py", line 23, in run
    ssh = salt.client.ssh.SSH(self.config)
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 231, in __init__
    self._expand_target()
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 359, in _expand_target
    self._get_roster()
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 338, in _get_roster
    self.opts['renderer_whitelist'])
  File "/usr/lib/python2.7/site-packages/salt/template.py", line 93, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/usr/lib/python2.7/site-packages/salt/renderers/yaml.py", line 59, in render
    raise SaltRenderError(exc)
SaltRenderError: expected '<document start>', but found '<scalar>'
  in "<unicode string>", line 2, column 1:
    delme-salt-rm
    ^
Traceback (most recent call last):
  File "/bin/salt-ssh", line 11, in <module>
    load_entry_point('salt-ssh==2018.3.2', 'console_scripts', 'salt-ssh')()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 425, in salt_ssh
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/ssh.py", line 23, in run
    ssh = salt.client.ssh.SSH(self.config)
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 231, in __init__
    self._expand_target()
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 359, in _expand_target
    self._get_roster()
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 338, in _get_roster
    self.opts['renderer_whitelist'])
  File "/usr/lib/python2.7/site-packages/salt/template.py", line 93, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/usr/lib/python2.7/site-packages/salt/renderers/yaml.py", line 59, in render
    raise SaltRenderError(exc)
salt.exceptions.SaltRenderError: expected '<document start>', but found '<scalar>'
  in "<unicode string>", line 2, column 1:
    delme-salt-rm
    ^
```

### Versions Report
```
[root@delme-salt-rm salt]# salt --versions-report
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 5.1
            ZMQ: 4.2.5

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.3.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```

**Comment by garethgreenaway** [comment]
@gtmanfred When you're back from your PTO, perhaps you could weigh in on this one.

**Comment by gtmanfred** [comment]
Yes, i am not sure when the ansible roster got broken, but it was rewritten for the fluorine release to just use the new `ansible-inventory` binary.  so that is what i would recommend doing.

**Comment by Oloremo** [comment]
@gtmanfred I'm new to Salt, can you point me to the docs on how to use that? The only docs I found about ansible inventory as roster is not working for me.

**Comment by gtmanfred** [comment]
It won't be available until Fluorine is actually released, but here is the file.

https://github.com/saltstack/salt/blob/fluorine/salt/roster/ansible.py

and you can use it through the dynamic modules system.

https://docs.saltstack.com/en/latest/ref/file_server/dynamic-modules.html

put it in `salt://_roster/` on your salt master, and run `salt-run saltutil.sync_roster`

https://docs.saltstack.com/en/latest/ref/runners/all/salt.runners.saltutil.html#salt.runners.saltutil.sync_roster

So that it gets put in the extmods roster directory.

**Comment by Oloremo** [comment]
Oh, it's will in the new release, ok got it!
