### ISSUE TITLE
[gitfs] failed to run state.apply when saltenv refers to a tag formated as float

### ISSUE THREAD

**Issue by opopops** [saltstack/salt#49716]
### Description of Issue/Question

Is use gitfs remote repo and  when I try to use **state.apply** with saltenv refers to a tag typed as float (**1.0**), it fails

### Setup
My Master config:

```yaml
ext_pillar:
- git:
  - __env__ git@gitlab.klaxoon.com:devops/salt/salt-red.git
ext_pillar_first: true
file_roots:
  base:
  - /srv/salt
fileserver_backend:
- roots
- git
git_pillar_base: master
git_pillar_privkey: /root/.ssh/id_rsa
git_pillar_provider: pygit2
git_pillar_pubkey: /root/.ssh/id_rsa.pub
git_pillar_root: pillar
gitfs_base: master
gitfs_global_lock: false
gitfs_privkey: /root/.ssh/id_rsa
gitfs_provider: pygit2
gitfs_pubkey: /root/.ssh/id_rsa.pub
gitfs_remotes:
- git@gitlab.klaxoon.com:devops/salt/salt-red.git
- git@gitlab.klaxoon.com:devops/salt/salt-formula.git:
  - all_saltenvs: master
gitfs_saltenv:
- base:
  - ref: master
interface: 0.0.0.0
log_datefmt_logfile: '%d/%m/%Y %H:%M:%S'
log_fmt_logfile: '[%(asctime)s,%(msecs)03.0f][SALT][%(name)s][%(levelname)s]%(message)s'
log_granular_levels:
  salt.master: warning
  salt.transport.mixins.auth: warning
  salt.transport.zeromq: warning
log_level: info
log_level_logfile: info
pillar_roots:
  __env__:
  - /srv/salt/pillar
pillarenv_from_saltenv: true
timeout: 120
top_file_merging_strategy: same

```

### Steps to Reproduce Issue
```shell
salt-call state.apply saltenv=1.0 -l info test=True
```

ERROR:

```shell
[INFO    ] Loading fresh modules for state activity
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'float' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 400, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 212, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 748, in apply_
    return sls(mods, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 1261, in sls
    high_, errors = st_.render_highstate({opts['saltenv']: mods})
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 3770, in render_highstate
    sls, saltenv, mods, matches)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 3424, in render_state
    state_data = self.client.get_state(sls, saltenv)
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 411, in get_state
    dest = self.cache_file(path, saltenv, cachedir=cachedir)
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 193, in cache_file
    path, '', True, saltenv, cachedir=cachedir, source_hash=source_hash)
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 515, in get_url
    result = self.get_file(url, dest, makedirs, saltenv, cachedir=cachedir)
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 1127, in get_file
    rel_path, saltenv, cachedir=cachedir) as cache_dest:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 144, in _cache_loc
    path)
  File "/usr/lib/python2.7/dist-packages/salt/utils/path.py", line 301, in join
    parts = [pathlib.normpath(p) for p in parts]
  File "/usr/lib/python2.7/posixpath.py", line 335, in normpath
    initial_slashes = path.startswith('/')
AttributeError: 'float' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 400, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 212, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 748, in apply_
    return sls(mods, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 1261, in sls
    high_, errors = st_.render_highstate({opts['saltenv']: mods})
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 3770, in render_highstate
    sls, saltenv, mods, matches)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 3424, in render_state
    state_data = self.client.get_state(sls, saltenv)
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 411, in get_state
    dest = self.cache_file(path, saltenv, cachedir=cachedir)
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 193, in cache_file
    path, '', True, saltenv, cachedir=cachedir, source_hash=source_hash)
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 515, in get_url
    result = self.get_file(url, dest, makedirs, saltenv, cachedir=cachedir)
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 1127, in get_file
    rel_path, saltenv, cachedir=cachedir) as cache_dest:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 144, in _cache_loc
    path)
  File "/usr/lib/python2.7/dist-packages/salt/utils/path.py", line 301, in join
    parts = [pathlib.normpath(p) for p in parts]
  File "/usr/lib/python2.7/posixpath.py", line 335, in normpath
    initial_slashes = path.startswith('/')
AttributeError: 'float' object has no attribute 'startswith'
```
### Versions Report
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: 0.24.5
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.2
         Python: 2.7.13 (default, Nov 24 2017, 17:33:09)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.5 
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.15.17-3-pve
         system: Linux
        version: debian 9.5

**Comment by Ch3LL** [comment]
ping @terminalmage

**Comment by terminalmage** [comment]
Pretty sure this is already fixed.

**Comment by terminalmage** [comment]
@opopops How did you generate the versions report? There was a fix for this added in back in the summer of 2017 which I confirmed is in 2018.3.2. What is the value of the `saltversion` grain on that minion?
