### ISSUE TITLE
version 2018.3.2 salt api An unexpected error occurred 

### ISSUE THREAD

**Issue by hiscal2015** [saltstack/salt#49767]
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
# salt-api --version
salt-api 2018.3.2 (Oxygen)
```
```
# salt --versions-report
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: 1.11.4
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.4.0-101-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
master config:
```
rest_cherrypy:
  port: 8000
  disable_ssl: True

external_auth:
  pam:
    saltuser:
      - .*
      - '@wheel'
      - '@runner'
      - '@jobs'
```

I can get token successfully:
```
# curl -ki http://10.10.0.10:8000/login -H "Accept: application/json" \
>  -d username='saltapi' \
>  -d password='123456' \
>  -d eauth='pam'
HTTP/1.1 200 OK
Content-Length: 172
Access-Control-Expose-Headers: GET, POST
Vary: Accept-Encoding
Server: CherryPy/3.5.0
Allow: GET, HEAD, POST
Access-Control-Allow-Credentials: true
Date: Tue, 25 Sep 2018 07:25:05 GMT
Access-Control-Allow-Origin: *
X-Auth-Token: 1548270041caf44f7702b3a3e059bf90b4b44015
Content-Type: application/json
Set-Cookie: session_id=1548270041caf44f7702b3a3e059bf90b4b44015; expires=Tue, 25 Sep 2018 17:25:05 GMT; Path=/

{"return": [{"perms": {}, "start": 1537860305.256632, "token": "1548270041caf44f7702b3a3e059bf90b4b44015", "expire": 1537903505.256633, "user": "saltapi", "eauth": "pam"}]}
```

But I can't proceed with client=local:
```
# curl -sSk http://localhost:8000 \
>     -H 'Accept: application/x-yaml' \
>     -H 'X-Auth-Token: 1548270041caf44f7702b3a3e059bf90b4b44015'\
>     -d client=local \
>     -d tgt='*' \
>     -d fun=test.ping
return: An unexpected error occurred
status: 500
```

salt master log:
```
[salt.master      :2043][WARNING ][17028] Authentication failure of type "token" occurred.
```

No salt-api logs.

Please help, thanks.

**Comment by garethgreenaway** [comment]
@hiscal2015 with the same configuration that you have above I haven't been able to duplicate this issue.  The only way I was able to duplicate the issue was with an invalid external authentication configuration.

**Comment by hiscal2015** [comment]
@garethgreenaway 

From salt-master log, only one line showing up as bold text below:
```
#salt-master -l debug
...
[DEBUG   ] LazyLoaded local_cache.clean_old_jobs
[DEBUG   ] LazyLoaded localfs.list_tokens
[DEBUG   ] This salt-master instance has accepted 190 minion keys.
[DEBUG   ] LazyLoaded pam.auth
[DEBUG   ] LazyLoaded localfs.mk_token
[DEBUG   ] LazyLoaded localfs.get_token
**[WARNING ] Authentication failure of type "token" occurred.**
[DEBUG   ] Performing fileserver updates for items with an update interval of 60
[DEBUG   ] Updating roots fileserver cache
[DEBUG   ] Completed fileserver updates for items with an update interval of 60, waiting 60 seconds
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/minion.d/99-master-address.conf'
```

salt-api
```
#salt-api -l debug
...
[DEBUG   ] Error while processing request for: /
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/netapi/rest_cherrypy/app.py", line 858, in hypermedia_handler
    ret = cherrypy.serving.request._hypermedia_inner_handler(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/netapi/rest_cherrypy/app.py", line 1286, in POST
    token=cherrypy.session.get('token')))
  File "/usr/lib/python2.7/dist-packages/salt/netapi/rest_cherrypy/app.py", line 1178, in exec_lowstate
    ret = self.api.run(chunk)
  File "/usr/lib/python2.7/dist-packages/salt/netapi/__init__.py", line 75, in run
    return l_fun(*f_call.get('args', ()), **f_call.get('kwargs', {}))
  File "/usr/lib/python2.7/dist-packages/salt/netapi/__init__.py", line 103, in local
    return local.cmd(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 741, in cmd
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 354, in run_job
    raise SaltClientError(general_exception)
SaltClientError: Authorization error occurred.
127.0.0.1 - - [26/Sep/2018:10:05:10] "POST / HTTP/1.1" 500 1268 "" "curl/7.47.0"
[INFO    ] 127.0.0.1 - - [26/Sep/2018:10:05:10] "POST / HTTP/1.1" 500 1268 "" "curl/7.47.0"
```

From client:
```
dshsalt:~# curl -sSk http://localhost:8000 \
>     -H 'Accept: application/x-yaml' \
>     -H 'X-Auth-Token: 616fb52f3f30e6584a36a34c80b574716da0e17d'\
>     -d client=local \
>     -d tgt='*' \
>     -d fun=test.ping
return: "Traceback (most recent call last):\n  File \"/usr/lib/python2.7/dist-packages/salt/netapi/rest_cherrypy/app.py\",
  line 858, in hypermedia_handler\n    ret = cherrypy.serving.request._hypermedia_inner_handler(*args,
  **kwargs)\n  File \"/usr/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py\",
  line 61, in __call__\n    return self.callable(*self.args, **self.kwargs)\n  File
  \"/usr/lib/python2.7/dist-packages/salt/netapi/rest_cherrypy/app.py\", line 1286,
  in POST\n    token=cherrypy.session.get('token')))\n  File \"/usr/lib/python2.7/dist-packages/salt/netapi/rest_cherrypy/app.py\",
  line 1178, in exec_lowstate\n    ret = self.api.run(chunk)\n  File \"/usr/lib/python2.7/dist-packages/salt/netapi/__init__.py\",
  line 75, in run\n    return l_fun(*f_call.get('args', ()), **f_call.get('kwargs',
  {}))\n  File \"/usr/lib/python2.7/dist-packages/salt/netapi/__init__.py\", line
  103, in local\n    return local.cmd(*args, **kwargs)\n  File \"/usr/lib/python2.7/dist-packages/salt/client/__init__.py\",
  line 741, in cmd\n    **kwargs)\n  File \"/usr/lib/python2.7/dist-packages/salt/client/__init__.py\",
  line 354, in run_job\n    raise SaltClientError(general_exception)\nSaltClientError:
  Authorization error occurred.\n"
status: 500

```

**Comment by hiscal2015** [comment]
@garethgreenaway yes, I use below command to get the token then call the test.ping function.

```
curl -ki http://localhost:8000/login -H "Accept: application/json" \
 -d username='saltapi' \
 -d password='123456' \
 -d eauth='pam'
```

**Comment by hiscal2015** [comment]
@garethgreenaway Sorry, I made a mistake to the username
