### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'strip' when using salt-ssh

### ISSUE THREAD

**Issue by DrPyser** [saltstack/salt#49807]
### Description of Issue/Question

I'm learning and playing around with salt-ssh, so I'm probably not doing things correctly.

I ran the command `sudo salt-ssh my.host.domain test.ping`, with the below roster file, and got this stack trace:
<details><summary>stack trace</summary>
<p>

```
[ERROR   ] An un-handled exception from the multiprocessing process 'MultiprocessingProcess-1' was caught:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/process.py", line 747, in _run
    return self._original_run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 518, in handle_routine
    **target)
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 920, in __init__
    self.shell = salt.client.ssh.shell.gen_shell(opts, **args)
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/shell.py", line 63, in gen_shell
    shell = Shell(opts, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/shell.py", line 90, in __init__
    self.host = host.strip('[]')
AttributeError: 'NoneType' object has no attribute 'strip'
Process MultiprocessingProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/site-packages/salt/utils/process.py", line 747, in _run
    return self._original_run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 518, in handle_routine
    **target)
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 920, in __init__
    self.shell = salt.client.ssh.shell.gen_shell(opts, **args)
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/shell.py", line 63, in gen_shell
    shell = Shell(opts, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/shell.py", line 90, in __init__
    self.host = host.strip('[]')
AttributeError: 'NoneType' object has no attribute 'strip'
[ERROR   ] Target 'None' did not return any data, probably due to an error.
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/usr/bin/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 425, in salt_ssh
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/ssh.py", line 24, in run
    ssh.run()
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 771, in run
    self.cache_job(jid, host, ret[host], fun)
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 697, in cache_job
    'fun': fun})
  File "/usr/lib/python2.7/site-packages/salt/returners/local_cache.py", line 144, in returner
    hn_dir = os.path.join(jid_dir, load['id'])
  File "/usr/lib/python2.7/posixpath.py", line 68, in join
    if b.startswith('/'):
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/usr/bin/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 425, in salt_ssh
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/ssh.py", line 24, in run
    ssh.run()
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 771, in run
    self.cache_job(jid, host, ret[host], fun)
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 697, in cache_job
    'fun': fun})
  File "/usr/lib/python2.7/site-packages/salt/returners/local_cache.py", line 144, in returner
    hn_dir = os.path.join(jid_dir, load['id'])
  File "/usr/lib/python2.7/posixpath.py", line 68, in join
    if b.startswith('/'):
AttributeError: 'NoneType' object has no attribute 'startswith'
``` 

</p>
</details>

### Setup
Roster file(`/etc/salt/roster`):
```
dev-server:
  host: my.host.name
  user: myuser
  sudo: True
  tty: True
  priv: /home/myuser/.ssh/id_rsa
```

### Steps to Reproduce Issue

Run above command with above roster file.

### Versions Report

```
$  salt-ssh --versions-report
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.30.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 3.6.6
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15 (default, Jun 27 2018, 13:05:28)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 5.1.1
            ZMQ: 4.2.5
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 4.18.9-arch1-1-ARCH
         system: Linux
        version: Not Installed
 
```

**Comment by garethgreenaway** [comment]
@DrPyser Thanks for the report.  When using salt-ssh use the name of the name of the minion from the roster file, in this case that would be `dev-server`.  That being said, we should have better handling when things wrong.
