### ISSUE TITLE
boto_elbv2.create_target_group state does not perform int-to-string type conversion

### ISSUE THREAD

**Issue by xenophonf** [saltstack/salt#49909]
### Description of Issue/Question

Given the following:
  - YAML interprets unquoted digit sequences as integer values [(1)](http://yaml.org/spec/1.2/spec.html#id2803828).
  - The boto_elbv2.create_target_group state passes its arguments directly to the relevant boto/boto3 library functions/object methods without converting from integers to strings.
  - The relevant boto/boto3 library functions/object methods perform input validation at AWS API request serialization time via botocore.validate.
  - The boto/boto3 API requires that an ELBv2 target group's HealthCheckPort have type `basestring`.

The boto_elbv2.create_target_group state does not convert `health_check_port` integer values to strings, violating the principle of least astonishment and resulting in an error similar to the following:

```
ParamValidationError: Parameter validation failed:
Invalid type for parameter HealthCheckPort, value: 443, type: <type 'int'>, valid types: <type 'basestring'>
```

### Setup

1. Create an AWS account.
2. Create an IAM instance profile with sufficient rights to create ELBv2 target groups.
3. Launch an EC2 instance with the above instance profile assigned.
4. Install the salt-minion in masterless mode on the above EC2 instance.

### Steps to Reproduce Issue

1. Get the ID of the default VPC of us-east-1.
2. Create an ELBv2 target group using the following SLS:

```yaml
example-target-group:
  boto_elbv2.create_target_group:
    - protocol: HTTPS
    - port: 443
    - health_check_protocol: HTTPS
    - health_check_port: 443
    - health_check_path: /ping
    - vpc_id: "{{ default_vpc_id }}"
    - region: us-east-1
```

3. Alternatively, run the following command as root:

```sh
salt-call state.single boto_elbv2.create_target_group name=example-target-group protocol=HTTPS port=443 health_check_protocol=HTTPS health_check_port=443 health_check_path=/ vpc_id=$DEFAULT_VPC_ID region=us-east-1
```

Either the SLS or the command will return the following error:

```
          ID: example-target-group
    Function: boto_elbv2.create_target_group
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1905, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1830, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/boto_elbv2.py", line 141, in create_target_group
                  **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/modules/boto_elbv2.py", line 151, in create_target_group
                  UnhealthyThresholdCount=unhealthy_threshold_count)
                File "/usr/lib/python2.7/site-packages/botocore/client.py", line 312, in _api_call
                  return self._make_api_call(operation_name, kwargs)
                File "/usr/lib/python2.7/site-packages/botocore/client.py", line 575, in _make_api_call
                  api_params, operation_model, context=request_context)
                File "/usr/lib/python2.7/site-packages/botocore/client.py", line 630, in _convert_to_request_dict
                  api_params, operation_model)
                File "/usr/lib/python2.7/site-packages/botocore/validate.py", line 291, in serialize_to_request
                  raise ParamValidationError(report=report.generate_report())
              ParamValidationError: Parameter validation failed:
              Invalid type for parameter HealthCheckPort, value: 443, type: <type 'int'>, valid types: <type 'basestring'>
     Started: 13:21:53.295288
    Duration: 687.261 ms
     Changes:   
```

### Versions Report

```sh
# salt --versions-report                                                                                              
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.8.1
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0  
           RAET: Not Installed
          smmap: 0.9.0   
        timelib: Not Installed
        Tornado: 4.2.1   
            ZMQ: 4.1.4   

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8   
        machine: x86_64  
        release: 3.10.0-862.14.4.el7.x86_64
         system: Linux   
        version: CentOS Linux 7.5.1804 Core
```

**Comment by xenophonf** [comment]
Note that the `health_check_port` parameter is documented as taking a string value.

**Comment by garethgreenaway** [comment]
@xenophonf Thanks for the report.  Seems like this should be a pretty simple fix to check if that parameter is a string and if not, convert it to one.  Would you be able to put in a pull request with those changes?

**Comment by twangboy** [comment]
Closing this issue due to age and lack of activity. Please test this on version 3006.2 and create a new issue if the problem persists. The new issue template has more information and will allow us to track and reproduce the issue more effectively. Thanks!
