### ISSUE TITLE
Centos7 salt repository packages broke python

### ISSUE THREAD

**Issue by Poil** [saltstack/salt#49928]
Hi,

After installing salt-minion, Pulp is broken on my host with this error

```
Oct  8 08:24:26 repos celery: from . import utils
Oct  8 08:24:26 repos celery: File "/usr/lib/python2.7/site-packages/requests/utils.py", line 32, in <module>
Oct  8 08:24:26 repos celery: from .exceptions import InvalidURL
Oct  8 08:24:26 repos celery: File "/usr/lib/python2.7/site-packages/requests/exceptions.py", line 10, in <module>
Oct  8 08:24:26 repos celery: from .packages.urllib3.exceptions import HTTPError as BaseHTTPError
Oct  8 08:24:26 repos celery: File "/usr/lib/python2.7/site-packages/requests/packages/__init__.py", line 95, in load_module
Oct  8 08:24:26 repos celery: raise ImportError("No module named '%s'" % (name,))
Oct  8 08:24:26 repos celery: ImportError: No module named 'requests.packages.urllib3'
```

If I try to import manually

```
>>> import requests.packages.urllib3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/usr/lib/python2.7/site-packages/requests/utils.py", line 32, in <module>
    from .exceptions import InvalidURL
  File "/usr/lib/python2.7/site-packages/requests/exceptions.py", line 10, in <module>
    from .packages.urllib3.exceptions import HTTPError as BaseHTTPError
  File "/usr/lib/python2.7/site-packages/requests/packages/__init__.py", line 95, in load_module
    raise ImportError("No module named '%s'" % (name,))
ImportError: No module named 'requests.packages.urllib3'

>>> import requests
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/usr/lib/python2.7/site-packages/requests/utils.py", line 25, in <module>
    from . import certs
```

I've removed all packages coming from salt-repository and reinstall python2-requests-2.6.0-2.el7.noarch and m2crypto-0.21.1-17.el7.x86_64 from the base os repository, Pulp is working again.

**Comment by Poil** [comment]
If I upgrade the OS before installing salt it seems to be ok the package from salt-repository are not erasing the OS one

**Comment by garethgreenaway** [comment]
@dmurphy18 FYI.

**Comment by Poil** [comment]
In general never replace a distribution package.

**Comment by dmurphy18** [comment]
@Poil Sorry that the urllib3 package caused you such trouble.  Can you provide the version of Redhat that you are using, that is, the output of 'cat /etc/redhat-release' and output of salt-run --versions-report for the salt-minion.  There were some issues with the versions of M2Crypto and Openssl on RHEL 7, which are fixed in the upcoming Salt 2018.3.3 point release.

Also can you let me know if you are mainly using Python 3 or Python 2 versions of Salt since you appear to have both installed and wondering if that is causing issues.

Normally SaltStack tries not to replace a version of a distribution package, unless absolutely necessary, for example: SaltStack had a need for python-tornado v4.2.1 as a base version which was unavailable from other repositories for some time, similarly with some versions of python-jinja2.  There is an effort to have SaltStack named versions of packages such that they do not conflict with distribution packages, but all current attempts to do this successfully have been in vain to date.

You mention reinstalling python2-requests-2.6.0-2.el7.noarch, but the yum list installed |grep python | sort -k3 shows python-requests.noarch   2.6.0-1.el7_1   @base ?

Can you provide the output of 'yum list python*-requests*' also.

**Comment by Poil** [comment]
Hey,

Sorry, I forgot this thread.

We use Salt with Python 2
Yes I've reinstalled python-requests.noarch 2.6.0-1.el7_1, I'll try to upgrade it to -2

```
[root@repos ~]# yum list python*-requests*
Modules complémentaires chargés : fastestmirror, priorities
Loading mirror speeds from cached hostfile
64 packages excluded due to repository priority protections
Paquets installés
python-requests.noarch                                                                                                       2.6.0-1.el7_1                                                                                              @base
python-requests-toolbelt.noarch                                                                                              0.8.0-1.el7                                                                                                @epel
Paquets disponibles
python-requests-kerberos.noarch                                                                                              0.7.0-2.el7                                                                                                epel 
python-requests-oauthlib.noarch                                                                                              0.4.0-7.el7                                                                                                epel 
python2-requests.noarch                                                                                                      2.6.0-0.el7                                                                                                epel 
python2-requests-file.noarch                                                                                                 1.4.3-3.el7                                                                                                epel 
python2-requests-gssapi.noarch                                                                                               1.0.0-5.el7                                                                                                epel 
python2-requests-mock.noarch                                                                                                 1.5.2-1.el7                                                                                                epel 
python2-requests-oauthlib.noarch                                                                                             0.8.0-5.el7                                                                                                base 
python2-requests_ntlm.noarch                                                                                                 1.1.0-1.el7                                                                                                epel 
python34-requests.noarch                                                                                                     2.12.5-1.el7                                                                                               epel 
```

**Comment by dmurphy18** [comment]
@Poil FYI in the current point releases the SaltStack version of python-requests has been removed and in future SaltStack shall rely on the provided python-requests for RHEL 7.

With this fix, can you review this issue and if satisfied, close it.
Thanks

**Comment by dmurphy18** [comment]
@Poil Can you confirm that the latest point releases of Salt resolve this issue for you, and consider closing this issue

**Comment by Poil** [comment]
All is ok :)
Thanks
