### ISSUE TITLE
unhashable type: 'list'

### ISSUE THREAD

**Issue by martin684** [saltstack/salt#49924]
When running test.ping from the CLI to minion through syndic from multi-master, we receive the following error. Syndic's minion did not return response to multi-master. Could someone help me to get it fixed, please?

`salt "*" test.ping`
```
2018-10-07 21:18:47,918 [tornado.application:632 ][ERROR   ][1071] Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7fc197b66510>, b'salt/job/20181007211847681019/ret/prg-vl-gns3-2\n\n\x8a\xa3cmd\xa7_return\xa3fun\xb1saltutil.find_job\xa6return\x80\xa6_stamp\xba2018-10-07T19:18:47.910224\xa2id\xadprg-vl-gns3-2\xa3jid\xb420181007211847681019\xa8fun_args\x91\xb420181007211842614258\xa7success\xc3\xa7retcode\x00\xa9master_id\x92\xb0MasterOfMaster-1\xb0MasterOfMaster-2')
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/tornado/ioloop.py", line 603, in _run_callback
    ret = callback()
  File "/usr/lib64/python3.4/site-packages/tornado/stack_context.py", line 274, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/salt/minion.py", line 3118, in _process_event
    jdict = self.job_rets.setdefault(master, {}).setdefault(mtag, {})
TypeError: unhashable type: 'list'
```

```
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.4.9 (default, Aug 14 2018, 21:28:57)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core

 
System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.14.4.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```

### Setup MoM 1,2
cat /etc/salt/master.d/ext.conf
```
order_masters: True
master_id:
  - MasterOfMaster-1
  - MasterOfMaster-2
```

### Syndic 1,2,3
/etc/salt/master.d/ext.conf
```
syndic_master:
  - MasterOfMaster-1
  - MasterOfMaster-2
```
/etc/salt/minion.d/ext.conf
```
master:
  - MasterOfMaster-1
  - MasterOfMaster-2

```
### Minion
```
master:
  - syndic-1
  - syndic-2
  - syndic-3
```

**Comment by garethgreenaway** [comment]
@martin684 Thanks for the report.  I believe the issue is that you have your `master_id` set to a list instead of a string.

**Comment by martin684** [comment]
Yes, because I wanted to use HA in active-active topology, without losing
returning job if one master die. This is the reason why I used a list. Is
possible to add feature to get data to list of masters not only to the one
of them?

I think if I will start job on master 1 and master 1 die, master 2 won't
know about the returning  job from master 1.

On 8 Oct 2018 19:59, "Gareth J. Greenaway" <notifications@github.com> wrote:

@martin684 <https://github.com/martin684> Thanks for the report. I believe
the issue is that you have your master_id set to a list instead of a string.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/saltstack/salt/issues/49924#issuecomment-427925767>,
or mute
the thread
