### ISSUE TITLE
encoding/unicode issue in 2018.X

### ISSUE THREAD

**Issue by remyd1** [saltstack/salt#49932]
Hi,

I have the same kind of error of #37906 :

```
          ID: dell_omsa_repo
    Function: pkgrepo.managed
        Name: deb http://linux.dell.com/repo/community/ubuntu xenial openmanage
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1931, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1943, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/pkgrepo.py", line 398, in managed
                  ppa_auth=kwargs.get('ppa_auth', None)
                File "/usr/lib/python2.7/dist-packages/salt/modules/aptpkg.py", line 1651, in get_repo
                  repos = list_repos()
                File "/usr/lib/python2.7/dist-packages/salt/modules/aptpkg.py", line 1603, in list_repos
                  repo['line'] = salt.utils.pkg.deb.strip_uri(source.line.strip())
                File "/usr/lib/python2.7/dist-packages/salt/utils/pkg/deb.py", line 38, in strip_uri
                  for x in ('http://', 'https://', 'ftp://')):
                File "/usr/lib/python2.7/dist-packages/salt/utils/pkg/deb.py", line 38, in <genexpr>
                  for x in ('http://', 'https://', 'ftp://')):
              UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
     Started: 14:04:46.827710
    Duration: 80.0000000745 ms
     Changes:
```

I had this error on salt `2018.3.2` and tried to switch to develop branch and I get the same error.

```
Salt Version:
           Salt: 2018.11.0-206-gb125901

Dependency Versions:
           cffi: 1.7.0
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 2.0.6
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.27.0
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.3.10
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15rc1 (default, Apr 15 2018, 21:51:34)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-33-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```

My state is working on previous release, that is to say `2017.7.2` and `2017.7.3`.

My state is the following:

```
{% if grains['os_family'] == 'Debian' %}
 {% set os = grains['os']|lower %}
 {% set release = grains['oscodename'] %}
 {% set majorrelease = grains['osmajorrelease'] %}
 # no recent package for ubuntu > 16
 {% if majorrelease > 16 %}
  {% set release = "xenial" %}
 {% endif %}

dell_omsa_repo:
  pkgrepo.managed:
    - humanname: linux.dell.com
    - name: deb http://linux.dell.com/repo/community/{{ os }} {{ release }} openmanage
    - file: /etc/apt/sources.list.d/linux.dell.com.sources.list
    - keyserver: pool.sks-keyservers.net
    - keyid: 1285491434D8786F


{% elif grains['os_family'] == 'RedHat' %}

dell_script_repo:
  cmd.run:
    - name: "curl -s http://linux.dell.com/repo/hardware/dsu/bootstrap.cgi | bash"
    - cwd: /
    - unless: ls /opt/curldell


touch /opt/curldell:
  cmd.run:
    - creates: /opt/curldell

{% endif %}
```

Any help would be appreciated.

Kind regards,
Rémy

**Comment by garethgreenaway** [comment]
@remyd1 Thanks for the report.  Unfortunately I haven't been able to duplicate the issue using the above state file.  A couple questions, are all machines running 2018.3.2, both master and any minions where you're seeing this issue?

**Comment by remyd1** [comment]
Yes it didn't work for machines with salt > `2018.x`. All my master are with salt > `2018.x`. 
It worked on minion `2017.x` (2017.7.x) but not on minions > `2018.x`.
