### ISSUE TITLE
winrepo_pkg.install in testing

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#50031]
### Description of Issue/Question

From https://jenkinsci.saltstack.com/job/pr-kitchen-windows2016-py3/job/PR-50026/2/consoleFull against 2017.7 branch

winrepo_pkg was design to run on the master only and create a winrepo.p in salt://win/repo
This was the old way, has it been deprecated now?

Not even sure how someone is calling `winrepo_pkg.install`  it should not exist
```
00:17:46.722        [INFO    ] Running state [winrepo_pkg.install] at time 13:30:14.573000
00:17:46.722        
00:17:46.722        [INFO    ] Executing state module.run for [winrepo_pkg.install]
00:17:46.722        
00:17:46.722        [WARNING ] The function "module.run" is using its deprecated version and will expire in version "Sodium".
00:17:46.722        
00:17:48.077        [WARNING ] C:\salt\bin\lib\site-packages\salt\modules\win_update.py:91: DeprecationWarning: The 'win_update' module is being deprecated and will be removed in Salt Fluorine (Unreleased). Please use the 'win_wua' module instead.
00:17:48.077        
00:17:48.077        
00:17:48.077        [ERROR   ] Not able to read repo file
00:17:48.077        [ERROR   ] [Errno 2] No such file or directory: u'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\kitchen\\var\\cache\\salt\\minion\\files\\base\\win\\repo-ng\\winrepo.p'
00:17:48.077        Traceback (most recent call last):
00:17:48.077          File "C:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 1877, in get_repo_data
00:17:48.077            with salt.utils.fopen(repo_details.winrepo_file, 'rb') as repofile:
00:17:48.077          File "C:\salt\bin\lib\site-packages\salt\utils\__init__.py", line 1361, in fopen
00:17:48.077            fhandle = open(*args, **kwargs)  # pylint: disable=resource-leakage
00:17:48.077        IOError: [Errno 2] No such file or directory: u'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\kitchen\\var\\cache\\salt\\minion\\files\\base\\win\\repo-ng\\winrepo.p'
```

**Comment by Ch3LL** [comment]
looks like it was added here: https://github.com/saltstack/salt-jenkins/pull/923/files  . its a custom module.

**Comment by damon-atkins** [comment]
Looks like @dwoz needs to sort it out.   Seems to be allowing a package definition to be passed to pkg.install instead of using winrepo.p on disk.
