### ISSUE TITLE
stringutils.to_none AttributeError: 'module' object has no attribute 'tex_type'

### ISSUE THREAD

**Issue by m03** [saltstack/salt#50142]
### Description of Issue/Question

Using `salt.utils.stringutils.to_none` results in the following:

```
  File "/usr/lib/python2.7/dist-packages/salt/utils/stringutils.py", line 150, in to_none
    if six.tex_type(text).strip():
AttributeError: 'module' object has no attribute 'tex_type'.
```

### Setup

Tested on Masterless Minion.

### Steps to Reproduce Issue

Use `salt.utils.stringutils.to_none` anywhere. Example execution module:

```
from __future__ import absolute_import, print_function, unicode_literals

import salt.utils

__virtualname__ = 'fakemod'

def __virtual__():
    return __virtualname__

def is_broken():
    return None == salt.utils.stringutils.to_none('')

def is_not_broken():
    return 42 == salt.utils.stringutils.to_num('42')
```

Example output:

```
root@example# salt-call fakemod.is_not_broken
local:
    True
root@example# salt-call fakemod.is_broken
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'module' object has no attribute 'tex_type'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 400, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 212, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/fakemod.py", line 16, in is_broken
    return None == salt.utils.stringutils.to_none('')
  File "/usr/lib/python2.7/dist-packages/salt/utils/stringutils.py", line 150, in to_none
    if six.tex_type(text).strip():
AttributeError: 'module' object has no attribute 'tex_type'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 400, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 212, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/fakemod.py", line 16, in is_broken
    return None == salt.utils.stringutils.to_none('')
  File "/usr/lib/python2.7/dist-packages/salt/utils/stringutils.py", line 150, in to_none
    if six.tex_type(text).strip():
AttributeError: 'module' object has no attribute 'tex_type'
```

### Versions Report

```
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: ISO-8859-1
        machine: x86_64
        release: 4.4.0-87-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by gtmanfred** [comment]
Woop, looks like a typo.  Thanks for the pr to fix this, i have merged it and we will get it backported to the other releases.

For future reference, when submitting bug fixes, PRs should be submitted against the oldest support release that the bug is in.

Thanks!
Daniel
