### ISSUE TITLE
No way to debug templates over salt-ssh

### ISSUE THREAD

**Issue by max-arnold** [saltstack/salt#50196]
### Description of Issue/Question

The recommended ways to debug templates are (as seen in the Slack chat):

```
salt 'example.com' slsutil.renderer /path/to/file.jinja 'jinja'
salt 'example.com' cp.get_template salt://path/to/template /dev/stdout template=jinja
```

Unfortunately, I was unable to make it work over `salt-ssh`:

```
salt-ssh -l debug example.com slsutil.renderer path='salt://test.sls' default_renderer='jinja'
...
[DEBUG   ] Could not LazyLoad slsutil.renderer: 'slsutil.renderer' is not available.
...
```

```
salt-ssh example.com cp.get_template salt://test.sls /dev/stdout template=jinja

example.com:
    ----------
    retcode:
        0
    stderr:
        Traceback (most recent call last):
          File "/var/tmp/.root_7e26e1_salt/salt-call", line 15, in <module>
            salt_call()
          File "/var/tmp/.root_7e26e1_salt/py3/salt/scripts.py", line 400, in salt_call
            client.run()
          File "/var/tmp/.root_7e26e1_salt/py3/salt/cli/call.py", line 57, in run
            caller.run()
          File "/var/tmp/.root_7e26e1_salt/py3/salt/cli/caller.py", line 134, in run
            ret = self.call()
          File "/var/tmp/.root_7e26e1_salt/py3/salt/cli/caller.py", line 212, in call
            ret['return'] = func(*args, **kwargs)
          File "/var/tmp/.root_7e26e1_salt/py3/salt/modules/cp.py", line 335, in get_template
            **kwargs)
          File "/var/tmp/.root_7e26e1_salt/py3/salt/fileclient.py", line 782, in get_template
            **kwargs
          File "/var/tmp/.root_7e26e1_salt/py3/salt/utils/templates.py", line 167, in render_tmpl
            tmplstr = tmplsrc.read()
        AttributeError: 'bool' object has no attribute 'read'
    stdout:
```

Third way also doesn't work:

```
salt-ssh example.com cp.get_file salt://test.sls /dev/stdout template=jinja

example.com:
    False
```

Salt version `2018.3.2` on Py3.

The question is: what is the best (and documented) way to debug templates, which works consistently across `salt`, `salt-call` and `salt-ssh` (and maybe `salt-run`)?

**Comment by dwoz** [comment]
@max-arnold Thank you for reporting this.

**Comment by limakzi** [comment]
```
.venv ❯ salt --version
salt 2019.2.0 (Fluorine)
```

I faced this problem yesterday. It highly impacts local development process.

**Comment by max-arnold** [comment]
Still valid

**Comment by amendlik** [comment]
I can work on a fix if the @dwoz or someone at Salt can offer some guidance.

**Comment by sagetherage** [comment]
@amendlik looking to find someone who can give that guidance, thank you!

**Comment by andreasnuesslein** [comment]
@amendlik  so I looked into the code a bit as well, if you're still interested in takling this ( / but also writing this here as a note to myself a bit):

i found out that 
```
[DEBUG   ] Could not LazyLoad slsutil.renderer: 'slsutil.renderer' is not available.
[DEBUG   ] Performing shimmed, blocking command as follows:
slsutil.renderer /tmp/map.py
``` 

basically means: "i did not find a `ssh/wrapper` for slsutil, i will instead copy a kind of shim over to the node and try to execute everything there"

the shimmed version will actually work if that target file is on the host; so my test here with `/tmp/map.py` worked because i threw that file over onto that node. however `salt://` paths will obviously not work.

a starting point to implement that `slsutil` to make it LazyLoad-able  is the folder `salt/client/ssh/wrapper/`, create a file **`salt/client/ssh/wrapper/slsutil.py`**:

```
import logging

log = logging.getLogger(__name__)

def renderer(path=None, string=None, default_renderer="jinja|yaml", **kwargs):
    log.info("whoohoo, we found the starting point")
```

and then I suppose gather inspiration from the other salt/client/ssh/wrappers

**Comment by dwoz** [comment]
Fixed by #65517 (3007.x, 2024-01-02) and backported via #66661 (3006.x, 2024-06-25). `slsutil.renderer` is now a salt-ssh wrapper; covered by tests/pytests/integration/ssh/test_slsutil.py on 3006.x/3007.x/3008.x/master.
