### ISSUE TITLE
broken highstate going from 2017.7.7 to 2017.7.8: "KeyError: 'saltutil.is_running'"

### ISSUE THREAD

**Issue by Mrten** [saltstack/salt#50220]
I'm currently stuck on something that looks suspiciously like #28274, which I'll stop spamming now.

2017.7.8 minion:
```
secstore:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1477, in _thread_return
        return_data = executor.execute()
      File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 1071, in sls
        conflict = running(concurrent)
      File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 209, in running
        active = __salt__['saltutil.is_running']('state.*')
      File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1121, in __getitem__
        func = super(LazyLoader, self).__getitem__(item)
      File "/usr/lib/python2.7/dist-packages/salt/utils/lazy.py", line 101, in __getitem__
        raise KeyError(key)
    KeyError: 'saltutil.is_running'
```
If I downgrade to 2017.7.7, same state.sls:
```
secstore:
----------
          ID: upgrade-config
    Function: file.managed
        Name: /etc/apt/apt.conf.d/upgrade
      Result: True
     Comment: File /etc/apt/apt.conf.d/upgrade updated
     Started: 12:27:40.224133
    Duration: 32.174 ms
     Changes:
              ----------
              diff:
                  New file
              mode:
                  0644

```

**Comment by Mrten** [comment]
Related? /var/log/salt/minion from a failing run:
```
2018-10-25 12:15:47,225 [salt.minion      :1308][INFO    ][1253] User root Executing command state.sls with jid 20181025121547134387
2018-10-25 12:15:47,240 [salt.minion      :1432][INFO    ][2719] Starting a new job with PID 2719
2018-10-25 12:15:47,695 [salt.loader.salt.int.module.snapper:67  ][WARNING ][2719] org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
2018-10-25 12:15:47,913 [salt.minion      :1539][WARNING ][2719] The minion function caused an exception
```

**Comment by sblaisot** [comment]
same here with 2017.7.7 master and 2017.7.8 minion
If I downgrade the minion to 2017.7.7 no problem, but unfortunately older versions are not available anymore from saltstack's official debian repo.

I did not try to upgrade master to 2017.7.8 yet to have both master and minion in this version beacause I don't want to break all my servers.

**Comment by Mrten** [comment]
You can change your /etc/apt/sources.list.d/[salt-ppa] file to have, for example:
```
#deb http://repo.saltstack.com/apt/ubuntu/14.04/amd64/2017.7 trusty main
deb http://repo.saltstack.com/apt/ubuntu/14.04/amd64/archive/2017.7.7 trusty main
```
then 
```
apt-get update
apt-get install salt-common=2017.7.7+ds-1 salt-minion=2017.7.7+ds-1
```

**Comment by Mrten** [comment]
all old releases are [there](http://repo.saltstack.com/apt/ubuntu/14.04/amd64/archive).

**Comment by Mrten** [comment]
Btw, my master is 2017.7.8 and it's OK. But be careful to run a highstate if it upgrades the salt-minion package, I had to manually downgrade four servers.

**Comment by Mrten** [comment]
I'm in the process of upgrading 14.04 machines to 16.04. 

The problem manifested itself on 14.04 first. When the upgrade to 16.04 is done 2017.7.8 is still broken, but when I then dist-upgrade which upgrades (amongst others) `python-concurrent.futures` (to 3.0.5) and `python-tornado` (to 4.2.1-2~ds+1) things seem to work again.

Is there a minumum dependency on either of those two packages missing?

**Comment by lomeroe** [comment]
I am seeing the same on 2018.3.3 too (as well as 2017.7.8), even when just trying to run a state.single or state.apply, my nodes are masterless too...

```
# salt-call -V
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
   python-gnupg: 0.4.3
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.14.4.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```

```
# salt-call -V
Salt Version:
           Salt: 2017.7.8

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
   python-gnupg: 0.4.3
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.14.4.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```

**Comment by lomeroe** [comment]
Seems python's concurrent module is the cause in my case:

```
# salt-call --local saltutil -d -l debug
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: ip-10-80-18-48.ec2.internal
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded boto.assign_funcs
[DEBUG   ] Failed to import module dockermod:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1440, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/usr/lib/python2.7/site-packages/salt/modules/dockermod.py", line 209, in <module>
    import salt.utils.thin
  File "/usr/lib/python2.7/site-packages/salt/utils/thin.py", line 17, in <module>
    import concurrent
ImportError: No module named concurrent
[DEBUG   ] LazyLoaded systemd.booted
[DEBUG   ] Failed to import module saltutil:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1440, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/usr/lib/python2.7/site-packages/salt/modules/saltutil.py", line 42, in <module>
    import salt.client.ssh.client
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 44, in <module>
    import salt.utils.thin
  File "/usr/lib/python2.7/site-packages/salt/utils/thin.py", line 17, in <module>
    import concurrent
ImportError: No module named concurrent
[DEBUG   ] DSC: Only available on Windows systems
[DEBUG   ] Module PSGet: Only available on Windows systems
```

```
#yum install python2-futures
```

fixes it on Cent...looks like the package needs a dependency to make sure it gets installed

**Comment by folti** [comment]
> perhaps the dependency on -concurrent was 'soft' in 2017.7.7 and became 'hard' in 2017.7.8?

Not on trusty.
It looks like, the problem is the different dependency handling by APT, regarding the dependencies of the python-tornado package. On our trusty hosts which shows this bug, the version of the python-tornado package is 4.2.1-1 with no installation candidate:
```# apt-cache policy python-tornado
python-tornado:
  Installed: 4.2.1-1
  Candidate: 4.2.1-1
  Version table:
 *** 4.2.1-1 0
        100 /var/lib/dpkg/status
     4.2.1-1~ds+1 0
        500 http://repo.saltstack.com/apt/ubuntu/14.04/amd64/2017.7/ trusty/main amd64 Packages
     3.1.1-1ubuntu2 0
        500 http://mirror.devel.balabit/ubuntu/ trusty/main amd64 Packages
``` 
This usually happens when the source of that version disappears from APT sources (eg. probably provided in a previous Salt repository but no longer), and the currently provided version (4.2.1-1~ds+1) is considered a downgrade.

The problematic version of the `python-tornado` lacks the `python-futures` dependency, while the working 4.2.1-1~ds+1 have it.

4.2.1-1:
```Package: python-tornado
Status: install ok installed
Priority: optional
Section: web
Installed-Size: 1606
Maintainer: Debian Python Modules Team <python-modules-team@lists.alioth.debian.org>
Architecture: amd64
Version: 4.2.1-1
Depends: ca-certificates, python (>= 2.7), python-pycurl, python (<< 2.8), python:any (>= 2.7.1-0ubuntu2)
Recommends: python-mysqldb
Description-en: scalable, non-blocking web server and tools
 Tornado is an open source version of the scalable, non-blocking
 web server and tools that power FriendFeed. The FriendFeed application
 is written using a web framework that looks a bit like web.py or
 Google's webapp, but with additional tools and optimizations to take
 advantage of the underlying non-blocking infrastructure.
 .
 This is the Python 2 version of the package.
Description-md5: 334f29c239009363c41bf9736d065ebc
Homepage: http://www.tornadoweb.org/
```

4.2.1-1~ds+1:
```
Package: python-tornado
Version: 4.2.1-1~ds+1
Architecture: amd64
Maintainer: Debian Python Modules Team <python-modules-team@lists.alioth.debian.org>
Installed-Size: 1606
Depends: ca-certificates, python (>= 2.7), python-futures, python-pycurl, python (<< 2.8), python:any (>= 2.7.1-0ubuntu2)
Recommends: python-mysqldb
Homepage: http://www.tornadoweb.org/
Priority: optional
Section: web
Filename: pool/main/p/python-tornado/python-tornado_4.2.1-1~ds+1_amd64.deb
Size: 274048
SHA256: 2bfdcbae1ce7b1935ee780af59574c5fb1d2df0c2cdf05f84c7a63315e7f7848
SHA1: ba5e01182ef17f7d148e7b929dc0ec0d4282ac8a
MD5sum: e9efdc2c43e80eb5e23373b7ac4c73f7
Description-en: scalable, non-blocking web server and tools
 Tornado is an open source version of the scalable, non-blocking
 web server and tools that power FriendFeed. The FriendFeed application
 is written using a web framework that looks a bit like web.py or
 Google's webapp, but with additional tools and optimizations to take
 advantage of the underlying non-blocking infrastructure.
 .
 This is the Python 2 version of the package.
Description-md5: 334f29c239009363c41bf9736d065ebc
```

Force downgrading python-tornado to 4.2.1-1~ds+1 will install the `python-concurrent.futures` package, which provides the `python-futures` package, which will solve the problem:

```
apt-get install --reinstall python-tornado=4.2.1-1~ds+1
service salt-minion restart
```

**Comment by sblaisot** [comment]
On a debian stretch minion server, installing package `python-concurrent.futures` resolves the issue.
This package should definitely be made a dependance of the salt-minion package

**Comment by Ch3LL** [comment]
this is being tracked over here: https://github.com/saltstack/salt-pack/issues/593
