### ISSUE TITLE
numeric git branch name breaks saltenv=<mybranch>

### ISSUE THREAD

**Issue by soostdijck** [saltstack/salt#50222]
### Description of Issue/Question

When using gitfs and using  `saltenv=somebranch` where "somebranch" is a integer/number things fall over.

### Setup
`salt-call state.apply network saltenv=1297551 pillarenv=base --output-diff`

### Steps to Reproduce Issue
```
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'int' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 410, in salt_call
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 212, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 763, in apply_
    return sls(mods, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 1313, in sls
    high_, errors = st_.render_highstate({opts['saltenv']: mods})
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 3779, in render_highstate
    sls, saltenv, mods, matches)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 3431, in render_state
    state_data = self.client.get_state(sls, saltenv)
  File "/usr/lib/python2.7/site-packages/salt/fileclient.py", line 414, in get_state
    dest = self.cache_file(path, saltenv, cachedir=cachedir)
  File "/usr/lib/python2.7/site-packages/salt/fileclient.py", line 196, in cache_file
    path, '', True, saltenv, cachedir=cachedir, source_hash=source_hash)
  File "/usr/lib/python2.7/site-packages/salt/fileclient.py", line 518, in get_url
    result = self.get_file(url, dest, makedirs, saltenv, cachedir=cachedir)
  File "/usr/lib/python2.7/site-packages/salt/fileclient.py", line 1133, in get_file
    rel_path, saltenv, cachedir=cachedir) as cache_dest:
  File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/lib/python2.7/site-packages/salt/fileclient.py", line 147, in _cache_loc
    path)
  File "/usr/lib/python2.7/site-packages/salt/utils/path.py", line 301, in join
    parts = [pathlib.normpath(p) for p in parts]
  File "/usr/lib64/python2.7/posixpath.py", line 327, in normpath
    initial_slashes = path.startswith('/')
AttributeError: 'int' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 410, in salt_call
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 212, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 763, in apply_
    return sls(mods, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 1313, in sls
    high_, errors = st_.render_highstate({opts['saltenv']: mods})
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 3779, in render_highstate
    sls, saltenv, mods, matches)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 3431, in render_state
    state_data = self.client.get_state(sls, saltenv)
  File "/usr/lib/python2.7/site-packages/salt/fileclient.py", line 414, in get_state
    dest = self.cache_file(path, saltenv, cachedir=cachedir)
  File "/usr/lib/python2.7/site-packages/salt/fileclient.py", line 196, in cache_file
    path, '', True, saltenv, cachedir=cachedir, source_hash=source_hash)
  File "/usr/lib/python2.7/site-packages/salt/fileclient.py", line 518, in get_url
    result = self.get_file(url, dest, makedirs, saltenv, cachedir=cachedir)
  File "/usr/lib/python2.7/site-packages/salt/fileclient.py", line 1133, in get_file
    rel_path, saltenv, cachedir=cachedir) as cache_dest:
  File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/lib/python2.7/site-packages/salt/fileclient.py", line 147, in _cache_loc
    path)
  File "/usr/lib/python2.7/site-packages/salt/utils/path.py", line 301, in join
    parts = [pathlib.normpath(p) for p in parts]
  File "/usr/lib64/python2.7/posixpath.py", line 327, in normpath
    initial_slashes = path.startswith('/')
AttributeError: 'int' object has no attribute 'startswith'
```

### Versions Report
```
0:root@vmx-lab [/var/log> salt-call -V                                                                               [DEV]
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.3.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```

**Comment by gtmanfred** [comment]
That is caused by yaml,  you will need to quote those.

`salt-call state.apply network saltenv='"1297551"' pillarenv=base --output-diff`

https://docs.saltstack.com/en/latest/topics/troubleshooting/yaml_idiosyncrasies.html

all of the salt commandline inputs are passed through the yaml loader, which converts the string with only numbers in it to an integer.

**Comment by cstrahan** [comment]
@gtmanfred 

> all of the salt commandline inputs are passed through the yaml loader, which converts the string with only numbers in it to an integer.

I've tried searching through the Salt documentation, as well as asking Gemini, and I can't find anything stating that any of the CLI inputs are passed through the YAML loader, but empirically this does seem to be the case (at least for `saltenv`). Do you know if this is documented anywhere?
