### ISSUE TITLE
Nested grains.filter_by calls fail when using salt-ssh

### ISSUE THREAD

**Issue by ixs** [saltstack/salt#50247]
### Description of Issue
This occured using the epel formula from https://github.com/saltstack-formulas/epel-formula.

When running state.apply epel via salt-call, everything works.
Running the same via salt-ssh, an error is returned instead:

`    - Rendering SLS 'base:epel' failed: Jinja variable 'dict object' has no attribute 'key_name'
`
The problem seems to be, that the salt-ssh grains wrapper for filter_by() in clients/ssh/wrapper/grains.py does not support nested filter_by calls correctly.

It seems to get called twice, but the nested filter_by call seems to be merged as None.
I did not investigate further because I did not understand the wrapper concept.
This is most likely related to <https://github.com/saltstack/salt/issues/33966> where thatch says, the wrapper is needed.

Interestingly, during my testing I broke the wrapper at which point the grains.regular filter_by() function was used which worked correctly.

### Setup
Add default epel-formula used on a CentOS target.
Verify it works locally: salt-call --local state.apply epel
Watch it fail using salt-ssh: salt-ssh localhost state.apply epel

```
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] Could not find file 'salt://epel.sls' in saltenv 'base'
[DEBUG   ] In saltenv 'base', looking at rel_path 'epel/init.sls' to resolve 'salt://epel/init.sls'
[DEBUG   ] In saltenv 'base', ** considering ** path '/var/cache/salt/master/files/base/epel/init.sls' to resolve 'salt://epel/init.sls'
[DEBUG   ] compile template: /var/cache/salt/master/files/base/epel/init.sls
[DEBUG   ] Jinja search path: [u'/var/tmp/.root_1c8204_salt/running_data/var/cache/salt/minion/files/base']
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[DEBUG   ] In saltenv 'base', looking at rel_path 'epel/map.jinja' to resolve 'salt://epel/map.jinja'
[DEBUG   ] In saltenv 'base', ** considering ** path '/var/tmp/.root_1c8204_salt/running_data/var/cache/salt/minion/files/base/epel/map.jinja' to resolve 'salt://epel/map.jinja'
[DEBUG   ] LazyLoaded grains.filter_by
[DEBUG   ] LazyLoaded pillar.get
[ERROR   ] Rendering exception occurred
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 170, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 399, in render_jinja_tmpl
    buf=tmplstr)
SaltRenderError: Jinja variable 'dict object' has no attribute 'key_name'
[CRITICAL] Rendering SLS 'base:epel' failed: Jinja variable 'dict object' has no attribute 'key_name'
[DEBUG   ] LazyLoaded nested.output
[TRACE   ] data = {u'easydb.bawue.net': [u"Rendering SLS 'base:epel' failed: Jinja variable 'dict object' has no attribute 'key_name'"]}
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
[TRACE   ] IPCClient: Connecting to socket: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event: tag = salt/job/20181026133404044684/ret/test; data = {'jid': u'20181026133404044684', u'return': [u"Rendering SLS 'base:epel' failed: Jinja variable 'dict object' has no attribute 'key_name'"], 'id': u'test', u'_stamp': '2018-10-26T11:34:13.476301'}
test:
    - Rendering SLS 'base:epel' failed: Jinja variable 'dict object' has no attribute 'key_name'
```

### Versions Report
```
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.28.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.14.4.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```

**Comment by Ch3LL** [comment]
if the code for nested `filter_by` calls is in `salt/modules/grains.py` and not the wrapper then we will need to add it to the wrapper.

**Comment by ixs** [comment]
@Ch3LL nah, the original code in salt/modules/grains.py calls utils/data.py for it's filter_by function.
The ssh wrapper contains a filter_by function which is a close approximation of the utils code but not exactly.

I have to admit, I had a quick look at the wrapper but did not understand it's purpose. So please take my attempt at explaining things with a grain of salt.

**Comment by dwoz** [comment]
Fixed by #63041 (merged 2022-11-09). The salt-ssh `grains.filter_by` wrapper now delegates to `salt.utils.data.filter_by`, the same util used by the regular grains module. Verified across 3006.x, 3007.x, 3008.x, and master: nested `grains.filter_by` calls (e.g. the epel-formula `map.jinja` pattern in the original report) resolve correctly. Not reproducible.
