### ISSUE TITLE
salt-ssh throws exception when minionfs is enabled.

### ISSUE THREAD

**Issue by russellballestrini** [saltstack/salt#50351]
### Setup
salt-ssh throws the following exception when minionfs is enabled on salt master::

```
ERROR   ] An Exception occurred while executing state.highstate: [Errno 2] No such file or directory: '/var/tmp/.root_812c13_salt/running_data/var/cache/salt/minion/minions'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 1156, in run_wfunc
    result = self.wfuncs[self.fun](*self.args, **self.kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/wrapper/state.py", line 705, in highstate
    roster_grains)
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/state.py", line 229, in prep_trans_tar
    files = file_client.cache_dir(name, saltenv, cachedir=cachedir)
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 240, in cache_dir
    for fn_ in self.file_list(saltenv):
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 1283, in file_list
    return salt.utils.data.decode(self.channel.send(load)) if six.PY2 \
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/__init__.py", line 871, in send
    return getattr(self.fs, cmd)(load)
  File "/usr/lib/python2.7/dist-packages/salt/utils/decorators/__init__.py", line 594, in wrapped
    **salt.utils.data.decode_dict(kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/__init__.py", line 752, in file_list
    ret.update(self.servers[fstr](load))
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/minionfs.py", line 253, in file_list
    minion_dirs = os.listdir(minions_cache_dir)
OSError: [Errno 2] No such file or directory: '/var/tmp/.root_812c13_salt/running_data/var/cache/salt/minion/minions'
[DEBUG   ] LazyLoaded nested.output
[TRACE   ] data = {u'mx1.example.net': u"An Exception occurred while executing state.highstate: [Errno 2] No such file or directory: '/var/tmp/.root_812c13_salt/running_data/var/cache/salt/minion/minions'"}
```

### Steps to Reproduce Issue

enable `minionfs` on `salt-master` and try to run `state.highstate` using `salt-ssh`

### Versions Report
```
$ salt-ssh --version
salt-ssh 2018.3.3 (Oxygen)

$ salt --version
salt 2018.3.3 (Oxygen)
```

**Comment by russellballestrini** [comment]
Anyone have any hints on where to hunt for this defect / regression?

It's starting to block me.

**Comment by russellballestrini** [comment]
It's still broken.
