### ISSUE TITLE
`'user.info' is not available` with macOS minion through salt-ssh

### ISSUE THREAD

**Issue by SimonSapin** [saltstack/salt#50477]
### Description of Issue/Question

When configuring a macOS 10.13 minion, trying to use the `user.present` state causes exception `KeyError: u'user.info'`. Trying `user.info` on the command-line results on `'user.info' is not available.`

A search engine leads to https://docs.saltstack.com/en/latest/ref/modules/index.html#module-provider-override which suggests this could be a Salt bug.

### Setup

On my Linux laptop, I installed agentless Salt through `pip install salt-ssh`. Other states like `file.managed` or `cmd.run` are working well.

Relevant SLS fragment:

```
worker:
  user.present
```

### Steps to Reproduce Issue

```
$ salt-ssh '*' state.apply              
mac1:
----------
          ID: worker
    Function: user.present
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/var/tmp/.root_62cd23_salt/py2/salt/state.py", line 1913, in call
                  **cdata['kwargs'])
                File "/var/tmp/.root_62cd23_salt/py2/salt/loader.py", line 1898, in wrapper
                  return f(*args, **kwargs)
                File "/private/var/tmp/.root_62cd23_salt/py2/salt/states/user.py", line 563, in present
                  allow_gid_change)
                File "/private/var/tmp/.root_62cd23_salt/py2/salt/states/user.py", line 99, in _changes
                  lusr = __salt__['user.info'](name)
                File "/var/tmp/.root_62cd23_salt/py2/salt/loader.py", line 1155, in __getitem__
                  func = super(LazyLoader, self).__getitem__(item)
                File "/var/tmp/.root_62cd23_salt/py2/salt/utils/lazy.py", line 104, in __getitem__
                  raise KeyError(key)
              KeyError: u'user.info'
     Started: 09:21:04.773550
    Duration: 785.056 ms
     Changes:   

Summary for mac1
------------
Succeeded: 4
Failed:    1
------------
Total states run:     5
Total run time:   2.349 s
```

```
$ salt-ssh '*' user.info worker         
mac1:
    ----------
    retcode:
        0
    stderr:
        'user.info' is not available.
    stdout:
```

### Grains

Elided output:

```
$ salt-ssh '*' grains.items
mac1:
    ----------
    cpu_model:
        Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
    cpuarch:
        x86_64
    domain:
        local
    fqdn:
        administrators-Mac-mini.local
    gid:
        0
    gpus:
        |_
          ----------
          model:
              HD Graphics 4000
          vendor:
              intel
    groupname:
        wheel
    host:
        administrators-Mac-mini
    kernel:
        Darwin
    kernelrelease:
        17.7.0
    kernelversion:
        Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64
    locale_info:
        ----------
        defaultencoding:
            None
        defaultlanguage:
            None
        detectedencoding:
            ascii
    localhost:
        administrators-Mac-mini.local
    manufacturer:
        Apple Inc.
    master:
        salt
    mem_total:
        16384
    model_name:
        Mac mini
    nodename:
        administrators-Mac-mini.local
    num_cpus:
        8
    num_gpus:
        1
    os:
        MacOS
    os_family:
        MacOS
    osarch:
        x86_64
    osbuild:
        17G65
    osfinger:
        Mac OS X 10.13.6-10
    osfullname:
        Mac OS X 10.13.6
    osmajorrelease:
        10
    osrelease:
        10.13.6
    osrelease_info:
        - 10
        - 13
        - 6
    path:
        /usr/bin:/bin:/usr/sbin:/sbin
    pid:
        35300
    productname:
        Macmini6,2
    ps:
        ps auxwww
    pythonexecutable:
        /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
    pythonpath:
        - /var/tmp/.root_62cd23_salt/py2
        - /private/var/tmp/.root_62cd23_salt
        - /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip
        - /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7
        - /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin
        - /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
        - /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages
        - /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk
        - /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old
        - /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload
        - /Library/Python/2.7/site-packages
        - /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python
        - /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC
    pythonversion:
        - 2
        - 7
        - 10
        - final
        - 0
    saltpath:
        /private/var/tmp/.root_62cd23_salt/py2/salt
    saltversion:
        2018.3.3
    saltversioninfo:
        - 2018
        - 3
        - 3
        - 0
    server_id:
        1054159750
    shell:
        /bin/sh
    smc_version:
        2.8f1
    swap_total:
        0
    uid:
        0
    username:
        root
    virtual:
        physical
    zfs_feature_flags:
        False
    zfs_support:
        False
```

### Versions Report

```
$ ./salt-ssh '*' --versions-report
Salt Version:
           Salt: 2018.3.3
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15 (default, Jun 27 2018, 13:05:28)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: Not Installed
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 5.1.1
            ZMQ: Not Installed
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 4.18.16-arch1-1-ARCH
         system: Linux
        version: Not Installed
```

**Comment by SimonSapin** [comment]
This works around the issue:

```diff
--- a/config/roster
+++ b/config/roster
@@ -1,2 +1,5 @@
 mac1:
     host: mac1.example.net
+    minion_opts:
+        providers:
+            user: mac_user

**Comment by SimonSapin** [comment]
No (further) work-around was needed to use the `service.running` state.

**Comment by SimonSapin** [comment]
Later, I expect to deploy multiple macOS machines with identical configuration. Is there a way in the `roster` file to have a `minion_opts` section apply to multiple minions, rather than repeating it entirely for each minion?

**Comment by Ch3LL** [comment]
im having a hard time replicating this issue. When i run `user.info` against a 10.13 VM it runs just fine. Was this working previously?

Also i'm not seeing an options from the docs to apply the opts to multiple minions unless there is a different roster module that would allow that.

**Comment by SimonSapin** [comment]
(I’ve found https://docs.saltstack.com/en/latest/topics/ssh/roster.html#target-defaults where `roster_defaults` in the master config can apply `minion_opts` to all minions.)

> Was this working previously?

No, this setup and this minion are new.

**Comment by Ch3LL** [comment]
nice find on the roster_defaults.

So the way that the loader tries to decide to load a module is right here: https://github.com/saltstack/salt/blob/v2018.3.3/salt/modules/mac_user.py#L42-L47 for mac_user.

so im not sure why its not loading for you. If you run the salt-ssh command with `-ltrace` it will show you the exact salt-call command its attempting to run on the mac. Then you can try to run that command with `-ldebug` which might tell use more as to why its not loading the module.
