### ISSUE TITLE
yaml|jinja renderer crashes

### ISSUE THREAD

**Issue by paulcdejean** [saltstack/salt#50517]
The expected behavior is ansible like rendering, where the individual keys and values from yaml are passed through jinja2 processing.

What we get instead is a crash.

```
paul_pauldejean_com@instance-1:/srv/salt$ ls
top.sls  webserver.sls
paul_pauldejean_com@instance-1:/srv/salt$ cat top.sls 
base:
  '*':
    - webserver
paul_pauldejean_com@instance-1:/srv/salt$ cat webserver.sls 
#! yaml|jinja
apache2:                 # ID declaration
  pkg:                  # state declaration
    - installed         # function declaration
paul_pauldejean_com@instance-1:/srv/salt$ sudo salt-call --local state.apply
[CRITICAL] Rendering SLS webserver failed, render error: 'OrderedDict' object has no attribute 'read'
local:
    Data failed to compile:
----------
    Rendering SLS webserver failed, render error: 'OrderedDict' object has no attribute 'read'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 3456, in render_state
    rendered_sls=mods
  File "/usr/lib/python2.7/dist-packages/salt/template.py", line 93, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/renderers/jinja.py", line 70, in render
    **kws)
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 167, in render_tmpl
    tmplstr = tmplsrc.read()
AttributeError: 'OrderedDict' object has no attribute 'read'
paul_pauldejean_com@instance-1:/srv/salt$ salt-call --version
salt-call 2018.3.3 (Oxygen)
paul_pauldejean_com@instance-1:/srv/salt$
```

**Comment by dwoz** [comment]
@paulcdejean The render's will run in order. So using `yaml|jina` will render `yaml` first which returns a dictionary and they try to feed the dictionary to `jinja` which is expecting a string.

Try reversing the order in your shebang `#! jinja|yaml`
