### ISSUE TITLE
saltutil.is_running error in masterless mode with python 2

### ISSUE THREAD

**Issue by ldav1s** [saltstack/salt#50531]
### Description of Issue/Question

The `saltutil.is_running` backtrace appears when trying to run a salt state in masterless mode (e.g. `salt-call --local state.apply foo`).  The salt-minion is _not_ running, as described in the [masterless documentation](https://docs.saltstack.com/en/latest/topics/tutorials/standalone_minion.html).

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

```
$ dpkg -l salt-*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                              Version                       Architecture                  Description
+++-=================================================-=============================-=============================-=======================================================================================================
ii  salt-common                                       2018.3.3+ds-1                 all                           shared libraries that salt requires for all packages
ii  salt-minion                                       2018.3.3+ds-1                 all                           client package for salt, the distributed remote execution system
```

When I ran `salt-call -l DEBUG`, I noticed in the log that it asked for the `concurrent` library a few times, and never finding it.  It did process all my pillars and was about ready to process states before emitting the error in the bug report.  Installing the `python-concurrent.futures` package fixed the error.  I'm seeing this collection of dependencies for `salt-common`.

```
2018.3.3+ds-1 - python-apt (0 (null)) python-dateutil (0 (null)) python-jinja2 (0 (null)) python-msgpack (2 0.4) python-pkg-resources (0 (null)) python-requests (2 1.0.0) python-tornado (2 4.2.1) python-yaml (0 (null)) python-systemd (0 (null)) python-psutil (0 (null)) python-gnupg (0 (null)) python:any (3 2.8) python:any (2 2.7.5-5~) python-mako (3 0.7.0) python-mako:i386 (3 0.7.0) lsb-release (0 (null)) python-mako (0 (null)) 
```

`python-concurrent.futures` is notably absent from that list.  It shouldn't be.

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

`salt-call --local state.apply foo` and get:

```
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
KeyError: u'saltutil.is_running'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 410, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 212, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 763, in apply_
    return sls(mods, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 1207, in sls
    conflict = running(concurrent)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 377, in running
    active = __salt__['saltutil.is_running']('state.*')
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1155, in __getitem__
    func = super(LazyLoader, self).__getitem__(item)
  File "/usr/lib/python2.7/dist-packages/salt/utils/lazy.py", line 104, in __getitem__
    raise KeyError(key)
KeyError: u'saltutil.is_running'

```
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
$ salt-call -V
Salt Version:
           Salt: 2018.3.3
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 2.5.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-138-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by Ch3LL** [comment]
ping @dmurphy18 can you look here. I believe this is resolved but maybe this is related to just installing the salt-minion?

**Comment by ldav1s** [comment]
I'm wondering how my machine got into that state.  I tried to reproduce this by removing and reinstalling `salt-minion` and `python-concurrent.futures`.  The `python-tornado`(?) dependency seems to correctly pick up `python-concurrent.futures`.

**Comment by ldav1s** [comment]
I was not able to reproduce this with the direct install and the upgrade install.

**Comment by ldav1s** [comment]
Ran into it again on on another server.

**Comment by ldav1s** [comment]
I have a reliable way to reproduce it now, I think:

I installed [Ubuntu Server 16.04.5](http://releases.ubuntu.com/16.04/ubuntu-16.04.5-server-amd64.iso.torrent?_ga=2.268964085.545887992.1542415602-2131580808.1539279040) into a VirtualBox VM and went through the setup rigamrole.

On first login I sudoe'd to root and noted that `python-concurrent.futures` was not installed, which was expected.  I installed `openssh-server` so I could copy/paste into a reasonable terminal.

I then ran `apt-get install salt-minion; systemctl disable salt-minion; systemctl stop salt-minion;`
I then ran `echo 'file_client: local'> /etc/salt/minion`.
Then: `apt-get install gnupg-curl` to make `apt-key` in your instructions work.
Then steps you will be familiar with:

```
apt-key adv --fetch-keys https://repo.saltstack.com/apt/ubuntu/16.04/amd64/2018.3/SALTSTACK-GPG-KEY.pub
add-apt-repository "deb http://repo.saltstack.com/apt/ubuntu/16.04/amd64/2018.3 xenial main" -y
apt-get update
sudo apt-get install salt-minion
```
I didn't let it update `/etc/salt/minion`.

I then:

```
root@ubuntusrv:~# dpkg -l | grep concurrent
root@ubuntusrv:~# salt-call -V
Salt Version:
           Salt: 2018.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 12 2018, 14:36:49)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-131-generic
         system: Linux
        version: Ubuntu 16.04 xenial
 
root@ubuntusrv:/# mkdir -p /srv/salt
root@ubuntusrv:/# mkdir -p /srv/pillar
root@ubuntusrv:/# cd /srv/salt
root@ubuntusrv:/srv/salt# vim top.sls
root@ubuntusrv:/srv/salt# vim test.sls
root@ubuntusrv:/srv/salt# salt-call state.apply test
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
KeyError: u'saltutil.is_running'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 410, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 212, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 763, in apply_
    return sls(mods, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 1207, in sls
    conflict = running(concurrent)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 377, in running
    active = __salt__['saltutil.is_running']('state.*')
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1155, in __getitem__
    func = super(LazyLoader, self).__getitem__(item)
  File "/usr/lib/python2.7/dist-packages/salt/utils/lazy.py", line 104, in __getitem__
    raise KeyError(key)
KeyError: u'saltutil.is_running'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 410, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 212, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 763, in apply_
    return sls(mods, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 1207, in sls
    conflict = running(concurrent)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 377, in running
    active = __salt__['saltutil.is_running']('state.*')
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1155, in __getitem__
    func = super(LazyLoader, self).__getitem__(item)
  File "/usr/lib/python2.7/dist-packages/salt/utils/lazy.py", line 104, in __getitem__
    raise KeyError(key)
KeyError: u'saltutil.is_running'
```

**top.sls**
```
base:
  '*':
    - test

```

**test.sls**

```
test_install:
  test.nop

```

**Comment by ldav1s** [comment]
The `python-tornado` in the broken environment is:

```
# dpkg -l | grep tornado
ii  python-tornado                      4.2.1-1ubuntu3                             amd64        scalable, non-blocking web server and tools
```

in a working environment it is:

```
$ dpkg -l | grep tornado
ii  python-tornado                                       4.2.1-2~ds+1                                             amd64        scalable, non-blocking web server and tools
```

I can see your python-tornado package in the broken environment, it just didn't seem to get installed in this sequence of steps:

```
# apt-cache showpkg python-tornado
Package: python-tornado
Versions: 
4.2.1-2~ds+1 (/var/lib/apt/lists/repo.saltstack.com_apt_ubuntu_16.04_amd64_2018.3_dists_xenial_main_binary-amd64_Packages)
 Description Language: 
                 File: /var/lib/apt/lists/us.archive.ubuntu.com_ubuntu_dists_xenial_universe_binary-amd64_Packages
                  MD5: 334f29c239009363c41bf9736d065ebc
 Description Language: 
                 File: /var/lib/apt/lists/us.archive.ubuntu.com_ubuntu_dists_xenial_universe_binary-i386_Packages
                  MD5: 334f29c239009363c41bf9736d065ebc
 Description Language: en
                 File: /var/lib/apt/lists/us.archive.ubuntu.com_ubuntu_dists_xenial_universe_i18n_Translation-en
                  MD5: 334f29c239009363c41bf9736d065ebc
 Description Language: 
                 File: /var/lib/apt/lists/repo.saltstack.com_apt_ubuntu_16.04_amd64_2018.3_dists_xenial_main_binary-amd64_Packages
                  MD5: 334f29c239009363c41bf9736d065ebc

4.2.1-1ubuntu3 (/var/lib/apt/lists/us.archive.ubuntu.com_ubuntu_dists_xenial_universe_binary-amd64_Packages) (/var/lib/dpkg/status)
 Description Language: 
                 File: /var/lib/apt/lists/us.archive.ubuntu.com_ubuntu_dists_xenial_universe_binary-amd64_Packages
                  MD5: 334f29c239009363c41bf9736d065ebc
 Description Language: 
                 File: /var/lib/apt/lists/us.archive.ubuntu.com_ubuntu_dists_xenial_universe_binary-i386_Packages
                  MD5: 334f29c239009363c41bf9736d065ebc
 Description Language: en
                 File: /var/lib/apt/lists/us.archive.ubuntu.com_ubuntu_dists_xenial_universe_i18n_Translation-en
                  MD5: 334f29c239009363c41bf9736d065ebc
 Description Language: 
                 File: /var/lib/apt/lists/repo.saltstack.com_apt_ubuntu_16.04_amd64_2018.3_dists_xenial_main_binary-amd64_Packages
                  MD5: 334f29c239009363c41bf9736d065ebc


Reverse Depends: 
  ipython-notebook,python-tornado 3.1.0
  salt-common,python-tornado 4.2.1
  python-tornado:i386,python-tornado
  salt-common,python-tornado 4.2
  python-ws4py,python-tornado
  python-toro,python-tornado
  python-tornadorpc,python-tornado
  python-tornado-pyvows,python-tornado
  python-tornadio2,python-tornado
  python-sockjs-tornado,python-tornado
  python-restless,python-tornado
  python-pytest-tornado,python-tornado
  python-matplotlib,python-tornado
  python-livereload,python-tornado
  python-flower,python-tornado
  mopidy,python-tornado 2.3
  mitmproxy,python-tornado
  jsonbot,python-tornado 2.2
  bup,python-tornado
  gunicorn,python-tornado
  dicompyler,python-tornado
  circus,python-tornado
  chaussette,python-tornado
Dependencies: 
4.2.1-2~ds+1 - ca-certificates (0 (null)) python (2 2.7) python-pycurl (0 (null)) python-futures (0 (null)) python (3 2.8) python-pymysql (0 (null)) python-tornado:i386 (32 (null)) 
4.2.1-1ubuntu3 - ca-certificates (0 (null)) python (2 2.7) python-pycurl (0 (null)) python (3 2.8) python-pymysql (0 (null)) python-tornado:i386 (32 (null)) 
Provides: 
4.2.1-2~ds+1 - 
4.2.1-1ubuntu3 - 
Reverse Provides: 
```

**Comment by ldav1s** [comment]
The workaround:

```
apt-get install python-tornado=4.2.1-2~ds+1
```

does work to fix this condition once encountered.  The fix is make sure the install/upgrade installs this package.

**Comment by dmurphy18** [comment]
@ldav1s Sorry for the latest of this reply, mining GitHub issues for issues mentioning me.  This has been seen where person have installed versions of python-tornado from non-LTS or testing repositories.

Previously, SaltStack relied on python-tornado having a dependency on python-concurrent.futures but that dependency changed.  Hence a dependency on python-concurrent.futures was added to the salt-common package which salt-minion, salt-master,. etc. depend on, thus stopping this issue from occurring and the fix is in the current Salt 2018.3.4 and 2019.2.0 point releases, see: https://github.com/saltstack/salt-pack/issues/598

If this information is sufficient, please consider closing this issue, unless there is some other relevant point.

**Comment by ldav1s** [comment]
Salt 2018.3.4 does fix this issue for me.  I followed the steps outlined above and ended up with salt-minion 2018.3.4+ds-1 being installed.  Installing salt-common does also install python-concurrent.futures.  The python-tornado package remains as installed (4.2.1-1ubuntu3) which is fine.

[salt-2018.3.4.txt](https://github.com/saltstack/salt/files/3082504/salt-2018.3.4.txt) has the output of my test on this pass for those who care.

Thanks!

**Comment by ldav1s** [comment]
Salt 2019.2.0 doesn't have this issue either.  I followed the steps, substituting:

```
apt-key adv --fetch-keys https://repo.saltstack.com/apt/ubuntu/16.04/amd64/2019.2/SALTSTACK-GPG-KEY.pub
add-apt-repository "deb http://repo.saltstack.com/apt/ubuntu/16.04/amd64/2019.2 xenial main" -y
```
as the first two steps of the installation of 2019.2.0.

[salt-2019.2.0.txt](https://github.com/saltstack/salt/files/3082596/salt-2019.2.0.txt) is the output of my test for this version of salt.
