### ISSUE TITLE
salt.modules.pdbedit broken on Samba 4.9.x

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#50538]
### Description of Issue/Question
The pdbedit module is broken again after upgrading to Samba 4.9.2

Both pdbedit.list in verbose and non-verbose mode.

```
[atlas :: sjorge][~]
[.]$ salt-call pdbedit.list verbose=False
local:
    - Registered MSG_REQ_POOL_USAGE
    - Registered MSG_REQ_DMALLOC_MARK and LOG_CHANGED
    - lp_load_ex
    - Initialising global parameters
    - Processing section "[global]"
    - tmartine
    - sjorge
```

For non-verbose we should filter out all lines that do not follow the 'login:uid:full name' format,

```
[atlas :: sjorge][~]
[.]$ salt-call pdbedit.list
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
KeyError: u'unix username'
Traceback (most recent call last):
  File "/opt/local/bin/salt-call", line 11, in <module>
    salt_call()
  File "/opt/local/lib/python2.7/site-packages/salt/scripts.py", line 410, in salt_call
    client.run()
  File "/opt/local/lib/python2.7/site-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/opt/local/lib/python2.7/site-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/opt/local/lib/python2.7/site-packages/salt/cli/caller.py", line 212, in call
    ret['return'] = func(*args, **kwargs)
  File "/var/cache/salt/minion/extmods/modules/pdbedit.py", line 100, in list_users
    users[user_data['unix username']] = user_data
KeyError: u'unix username'
Traceback (most recent call last):
  File "/opt/local/bin/salt-call", line 11, in <module>
    salt_call()
  File "/opt/local/lib/python2.7/site-packages/salt/scripts.py", line 410, in salt_call
    client.run()
  File "/opt/local/lib/python2.7/site-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/opt/local/lib/python2.7/site-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/opt/local/lib/python2.7/site-packages/salt/cli/caller.py", line 212, in call
    ret['return'] = func(*args, **kwargs)
  File "/var/cache/salt/minion/extmods/modules/pdbedit.py", line 100, in list_users
    users[user_data['unix username']] = user_data
KeyError: u'unix username'
```

### Setup
N/a

### Steps to Reproduce Issue
Run develop of salt against a pdbedit from samba 4.9.x

I will look into this when I have some a bit of time.

**Comment by Ch3LL** [comment]
thanks for the PR!
