### ISSUE TITLE
salt errors with current azure-storage because of no version set

### ISSUE THREAD

**Issue by wyardley** [saltstack/salt#50535]
### Description of Issue/Question
We recently added some of the azure storage modules. Even though we aren't referencing them or using them in our salt setup (other than using Salt to install them), Salt is erring due to the the lack of a `__version__` in a recent version of these modules.

### Setup
n/a

### Steps to Reproduce Issue
Run a highstate with the azure-storage-* pip modules installed:
```bash
root@f4d88f7c7105:~# pip list | grep azure
azure-common (1.1.16)
azure-nspkg (3.0.2)
azure-storage-blob (1.4.0)
azure-storage-common (1.4.0)
azure-storage-nspkg (3.1.0)
```

```
       [ERROR   ] Failed to import fileserver azurefs, this is due most likely to a syntax error:
       Traceback (most recent call last):
         File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1514, in _load_module
           mod = imp.load_module(mod_namespace, fn_, fpath, desc)
         File "/usr/lib/python2.7/dist-packages/salt/fileserver/azurefs.py", line 68, in <module>
           if LooseVersion(azure.storage.__version__) < LooseVersion('0.20.0'):
       AttributeError: 'module' object has no attribute '__version__'
       [ERROR   ] Failed to import fileserver azurefs, this is due most likely to a syntax error:
       Traceback (most recent call last):
         File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1514, in _load_module
           mod = imp.load_module(mod_namespace, fn_, fpath, desc)
         File "/usr/lib/python2.7/dist-packages/salt/fileserver/azurefs.py", line 68, in <module>
           if LooseVersion(azure.storage.__version__) < LooseVersion('0.20.0'):
       AttributeError: 'module' object has no attribute '__version__'
```

### Versions Report
This is in our test kitchen setup on an Ubuntu 16 container, installed via .deb, version 2018.3.3+ds-1

```
Salt Version:
           Salt: 2018.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.3.7
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 12 2018, 14:36:49)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.9.87-linuxkit-aufs
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by Ch3LL** [comment]
looks like we need to handle this exception in the imports. thanks

ping @saltstack/team-cloud fyi

**Comment by gtmanfred** [comment]
@nicholasmhughes can you take a look at this?

**Comment by wyardley** [comment]
Just to be clear, in case it affects the severity, the run continues and Salt doesn’t fail outright. This error is repeated a number of times in the run output though.
