### ISSUE TITLE
Saltstack needs shared memory but fails without a clear error message 

### ISSUE THREAD

**Issue by morgana2313** [saltstack/salt#50595]
When you start salt-minion (and salt-master) without /dev/shm (as is default with Alpine Linux) salt gives a vague error message. Notifying the use about the lack of /dev/shm would be better. 

salt works just fine after `mkdir -p -m 1777 /dev/shm `

```
# salt-minion
[ERROR   ] [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/parsers.py", line 222, in parse_args
    mixin_after_parsed_func(self)
  File "/usr/lib/python3.6/site-packages/salt/utils/parsers.py", line 861, in _setup_mp_logging_listener
    self._get_mp_logging_listener_queue()
  File "/usr/lib/python3.6/site-packages/salt/utils/parsers.py", line 855, in _get_mp_logging_listener_queue
    return log.get_multiprocessing_logging_queue()
  File "/usr/lib/python3.6/site-packages/salt/log/setup.py", line 813, in get_multiprocessing_logging_queue
    __MP_LOGGING_QUEUE = multiprocessing.Queue()
  File "/usr/lib/python3.6/multiprocessing/context.py", line 102, in Queue
    return Queue(maxsize, ctx=self.get_context())
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 42, in __init__
    self._rlock = ctx.Lock()
  File "/usr/lib/python3.6/multiprocessing/context.py", line 67, in Lock
    return Lock(ctx=self.get_context())
  File "/usr/lib/python3.6/multiprocessing/synchronize.py", line 163, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/usr/lib/python3.6/multiprocessing/synchronize.py", line 60, in __init__
    unlink_now)
FileNotFoundError: [Errno 2] No such file or directory
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/parsers.py", line 222, in parse_args
    mixin_after_parsed_func(self)
  File "/usr/lib/python3.6/site-packages/salt/utils/parsers.py", line 861, in _setup_mp_logging_listener
    self._get_mp_logging_listener_queue()
  File "/usr/lib/python3.6/site-packages/salt/utils/parsers.py", line 855, in _get_mp_logging_listener_queue
    return log.get_multiprocessing_logging_queue()
  File "/usr/lib/python3.6/site-packages/salt/log/setup.py", line 813, in get_multiprocessing_logging_queue
    __MP_LOGGING_QUEUE = multiprocessing.Queue()
  File "/usr/lib/python3.6/multiprocessing/context.py", line 102, in Queue
    return Queue(maxsize, ctx=self.get_context())
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 42, in __init__
    self._rlock = ctx.Lock()
  File "/usr/lib/python3.6/multiprocessing/context.py", line 67, in Lock
    return Lock(ctx=self.get_context())
  File "/usr/lib/python3.6/multiprocessing/synchronize.py", line 163, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/usr/lib/python3.6/multiprocessing/synchronize.py", line 60, in __init__
    unlink_now)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/salt/scripts.py", line 144, in minion_process
    minion.start()
  File "/usr/lib/python3.6/site-packages/salt/cli/daemons.py", line 343, in start
    super(Minion, self).start()
  File "/usr/lib/python3.6/site-packages/salt/utils/parsers.py", line 1036, in start
    self.prepare()
  File "/usr/lib/python3.6/site-packages/salt/cli/daemons.py", line 250, in prepare
    super(Minion, self).prepare()
  File "/usr/lib/python3.6/site-packages/salt/utils/parsers.py", line 1033, in prepare
    self.parse_args()
  File "/usr/lib/python3.6/site-packages/salt/utils/parsers.py", line 227, in parse_args
    mixin_after_parsed_func, traceback.format_exc(err)
  File "/usr/lib/python3.6/traceback.py", line 163, in format_exc
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
  File "/usr/lib/python3.6/traceback.py", line 117, in format_exception
    type(value), value, tb, limit=limit).format(chain=chain))
  File "/usr/lib/python3.6/traceback.py", line 497, in __init__
    capture_locals=capture_locals)
  File "/usr/lib/python3.6/traceback.py", line 332, in extract
    if limit >= 0:
TypeError: '>=' not supported between instances of 'FileNotFoundError' and 'int'
```

See also: https://bugs.alpinelinux.org/issues/6407

**Comment by Ch3LL** [comment]
we could probably do a check for the file or simply catch this exception. thanks
