### ISSUE TITLE
Modified Minion installer for Windows is giving Timezone issue and not connecting with master.

### ISSUE THREAD

**Issue by nithinh123** [saltstack/salt#50667]
### Description of Issue/Question
Modified Minion installer for Windows is giving Timezone isseue and not connecting with master. Able to add minion key in Master, but not able to connect to minion after that. 
### Setup
Modified the Salt Minion installer for windows. Tried to debug the issue using the salt-minion-debug.bat
Getting the below error:

  File "C:\hivecenter\bin\lib\site-packages\salt\modules\win_timezone.py", line
235, in get_offset
    tz_object = pytz.timezone(get_zone())
  File "C:\hivecenter\bin\lib\site-packages\pytz\__init__.py", line 179, in time
zone
    raise UnknownTimeZoneError(zone)
UnknownTimeZoneError: 'Unknown'

### Steps to Reproduce Issue
Run the salt-minion-debug.bat in windows command line.

### Versions Report
Minion- 2017.7.2

**Comment by dwoz** [comment]
@nithinh123 I do not fully understand the problem you are having. When you call the installer 'modified', does it mean you changed it in some way? If so What modifications did you make to the installer? Otherwise, please explain this further.

**Comment by nithinh123** [comment]
@dwoz  I made changes to the service name, installer directory and installer UI and icons. It works well in Windows Server 2012. Facing issue in Windows Server 2008.

**Comment by Steltek** [comment]
Seeing the same issue on a Win2k8 R2 server. Doesn't connect to master and is continually outputting these errors into the log:

`2019-03-06 10:45:12,377 [salt.minion      :1041][CRITICAL][5852] Unexpected error while connecting to sivour.dyndns.org
Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1018, in _connect_minion
    yield minion.connect_master(failed=failed)
  File "c:\salt\bin\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "c:\salt\bin\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "c:\salt\bin\lib\site-packages\tornado\gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1216, in connect_master
    yield self._post_master_init(master)
  File "c:\salt\bin\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "c:\salt\bin\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "c:\salt\bin\lib\site-packages\tornado\gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1263, in _post_master_init
    cleanup=[master_event(type='alive')])
  File "c:\salt\bin\lib\site-packages\salt\utils\schedule.py", line 106, in __new__
    utils=utils)
  File "c:\salt\bin\lib\site-packages\salt\utils\schedule.py", line 152, in __singleton_init__
    self.time_offset = self.functions.get('timezone.get_offset', lambda: '0000')()
  File "c:\salt\bin\lib\site-packages\salt\modules\win_timezone.py", line 240, in get_offset
    tz_object = pytz.timezone(get_zone())
  File "c:\salt\bin\lib\site-packages\pytz\__init__.py", line 178, in timezone
    raise UnknownTimeZoneError(zone)
UnknownTimeZoneError: 'Unknown'`

Salt minion is 2019.2.0-Py2-AMD64 (no modifications).

**Comment by nithinh123** [comment]
I have a work around for the issue. Made some changes in pytz library. I have modified __init__.py file in this library.

In the function timezone() make this changes. I Have commented the exception thrown and returned utc instead of that.

```python
    if zone.upper() == 'UTC':
        return utc

    try:
        zone = ascii(zone)
    except UnicodeEncodeError:
        # All valid timezones are ASCII
        **#raise UnknownTimeZoneError(zone)
        return utc**

    zone = _unmunge_zone(zone)
    if zone not in _tzinfo_cache:
        if zone in all_timezones_set:
            fp = open_resource(zone)
            try:
                _tzinfo_cache[zone] = build_tzinfo(zone, fp)
            finally:
                fp.close()
        else:
            **#raise UnknownTimeZoneError(zone)
            return utc**

    return _tzinfo_cache[zone]
```

**Comment by twangboy** [comment]
It's possible that this is fixed with the following PR: https://github.com/saltstack/salt/pull/51095
Should be in 2018.3.4 and 2019.2.0

**Comment by twangboy** [comment]
Could you verify?

**Comment by Steltek** [comment]
In my case, I'm using Win2k8R2 with 2019.2.0 and getting the indicated error, unless I specifically enable "Automatically adjust clock for Daylight Saving Time".

**Comment by twangboy** [comment]
So, I think the issue here is that the code was changed to use the `tzutil` command to get the TimeZone info (https://github.com/saltstack/salt/pull/51095) due to an issue where there was some strange data in the registry key for the same information. However, `tzutil /g` appends `_dstoff` to the TimeZone name which causes the dictionary lookup to fail. I'd like to figure out the problem with the bad registry data and go back to using that rather than shell out. There's an overhead cost to shelling out. Since this is a grain, it's happening often.

Here's a reference to a similar stackoverflow issue
https://stackoverflow.com/questions/27716746/hklm-system-currentcontrolset-control-timezoneinformation-timezonekeyname-corrup

**Comment by twangboy** [comment]
FYI: Speed comparison cmd vs reg
```
timeit: cmd - 1000 runs
9.4037297
timeit: reg - 1000 runs
0.0563001
```

**Comment by twangboy** [comment]
@nithinh123 @Steltek Could you verify the above PR fixes the issue?

**Comment by vrvaderom** [comment]
Still happens with salt minion 2019.2.0 Py2 and Py3
Windows server 2012

```
2019-08-27 09:26:12,654 [salt.minion      :1041][CRITICAL][20004] Unexpected error while connecting to tstworkstation01
Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1018, in _connect_minion
    yield minion.connect_master(failed=failed)
  File "c:\salt\bin\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "c:\salt\bin\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "c:\salt\bin\lib\site-packages\tornado\gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1216, in connect_master
    yield self._post_master_init(master)
  File "c:\salt\bin\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "c:\salt\bin\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "c:\salt\bin\lib\site-packages\tornado\gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1263, in _post_master_init
    cleanup=[master_event(type='alive')])
  File "c:\salt\bin\lib\site-packages\salt\utils\schedule.py", line 106, in __new__
    utils=utils)
  File "c:\salt\bin\lib\site-packages\salt\utils\schedule.py", line 152, in __singleton_init__
    self.time_offset = self.functions.get('timezone.get_offset', lambda: '0000')()
  File "c:\salt\bin\lib\site-packages\salt\modules\win_timezone.py", line 240, in get_offset
    tz_object = pytz.timezone(get_zone())
  File "c:\salt\bin\lib\site-packages\pytz\__init__.py", line 178, in timezone
    raise UnknownTimeZoneError(zone)
pytz.exceptions.UnknownTimeZoneError: 'Unknown'
```
