### ISSUE TITLE
Help explaining AuthenticationError seen after upgrade to CentOS 7.6

### ISSUE THREAD

**Issue by icycle77** [saltstack/salt#50673]
### Description of Issue/Question

I am testing an updated base image which incorporates a boatload of recent CentOS changes including moving salt one patch version forward to `2017.7.8`. In testing this I'm getting a consistent stack trace in salt when running a `cmd.script` invocation of a separate Python script. It's happened 2/2 times I've tested it so far, but it works when manually retried afterwards.

It's interesting that the state that runs successfully just before this problem state is restarting the `chronyd` NTP daemon on the minion. In the first repro the daemon logged that it adjusted the clock after the problem state started and before it failed, but in today's repro the clock adjust happened before the problem state started (logs below from today's repro). NTP may be related if message authentication could be impacted by clock changes? However, this state order has been running in our environment for many months as-is, so that is an unlikely hunch in my opinion.

In a nutshell, this feels like a bug in salt perhaps but I could use some guidance on how to narrow it down.

### Setup

The state triggering the problem, which is called from highstate:
```
setup-secondary-ips:
  cmd.script:
    - stateful: True
    - source: salt://base/networking/setup-secondary-ips.py
```
I'm not yet convinced that I need to provide the contents of `setup-secondary-ips.py` but I can look into any intellectual property considerations if needed.

### Steps to Reproduce Issue

Below are the relevant logs from the time window of the issue, including the state run just before the problem state and the running of the problem state with the full stack trace. The one before was included due to the possible clock sync theory discussed earlier.

```
2018-11-28T16:35:13.280645+00:00 ip-10-128-152-49 cloud-init: [INFO    ] Running state [chronyd.service] at time 16:35:13.194690
2018-11-28T16:35:13.282653+00:00 ip-10-128-152-49 cloud-init: [INFO    ] Executing state service.mod_watch for [chronyd.service]
2018-11-28T16:35:13.284171+00:00 ip-10-128-152-49 cloud-init: [INFO    ] Executing command ['systemctl', 'is-active', 'chronyd.service'] in directory '/'
2018-11-28T16:35:13.287003+00:00 ip-10-128-152-49 cloud-init: [INFO    ] Executing command ['systemd-run', '--scope', 'systemctl', 'restart', 'chronyd.service'] in directory '/'
2018-11-28T16:35:13.287750+00:00 ip-10-128-152-49 chronyd[7528]: chronyd version 3.2 starting (+CMDMON +NTP +REFCLOCK +RTC +PRIVDROP +SCFILTER +SECHASH +SIGND +ASYNCDNS +IPV6 +DEBUG)
2018-11-28T16:35:13.287987+00:00 ip-10-128-152-49 systemd: Stopping NTP client/server...
2018-11-28T16:35:13.288245+00:00 ip-10-128-152-49 chronyd[7528]: Frequency 32.745 +/- 0.130 ppm read from /var/lib/chrony/drift
2018-11-28T16:35:13.288546+00:00 ip-10-128-152-49 systemd: Stopped NTP client/server.
2018-11-28T16:35:13.288876+00:00 ip-10-128-152-49 systemd: Starting NTP client/server...
2018-11-28T16:35:13.292544+00:00 ip-10-128-152-49 systemd: Started NTP client/server.
2018-11-28T16:35:13.295982+00:00 ip-10-128-152-49 cloud-init: [INFO    ] {'chronyd.service': True}
2018-11-28T16:35:13.298411+00:00 ip-10-128-152-49 cloud-init: [INFO    ] Completed state [chronyd.service] at time 16:35:13.294010 duration_in_ms=99.319
2018-11-28T16:35:13.300931+00:00 ip-10-128-152-49 cloud-init: [INFO    ] Running state [setup-secondary-ips] at time 16:35:13.294461
2018-11-28T16:35:13.302740+00:00 ip-10-128-152-49 cloud-init: [INFO    ] Executing state cmd.script for [setup-secondary-ips]
2018-11-28T16:35:13.494523+00:00 ip-10-128-152-49 cloud-init: [ERROR   ] An exception occurred in this state: Traceback (most recent call last):
2018-11-28T16:35:13.497189+00:00 ip-10-128-152-49 cloud-init: File "/usr/lib/python2.7/site-packages/salt/state.py", line 1889, in call
2018-11-28T16:35:13.500053+00:00 ip-10-128-152-49 cloud-init: **cdata['kwargs'])
2018-11-28T16:35:13.502780+00:00 ip-10-128-152-49 cloud-init: File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1839, in wrapper
2018-11-28T16:35:13.505822+00:00 ip-10-128-152-49 cloud-init: return f(*args, **kwargs)
2018-11-28T16:35:13.508537+00:00 ip-10-128-152-49 cloud-init: File "/usr/lib/python2.7/site-packages/salt/states/cmd.py", line 1118, in script
2018-11-28T16:35:13.511297+00:00 ip-10-128-152-49 cloud-init: cmd_all = __salt__['cmd.script'](source, python_shell=True, **cmd_kwargs)
2018-11-28T16:35:13.514308+00:00 ip-10-128-152-49 cloud-init: File "/usr/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 2114, in script
2018-11-28T16:35:13.517107+00:00 ip-10-128-152-49 cloud-init: fn_ = __salt__['cp.cache_file'](source, saltenv)
2018-11-28T16:35:13.520171+00:00 ip-10-128-152-49 cloud-init: File "/usr/lib/python2.7/site-packages/salt/modules/cp.py", line 474, in cache_file
2018-11-28T16:35:13.523112+00:00 ip-10-128-152-49 cloud-init: result = _client().cache_file(path, saltenv)
2018-11-28T16:35:13.526199+00:00 ip-10-128-152-49 cloud-init: File "/usr/lib/python2.7/site-packages/salt/fileclient.py", line 188, in cache_file
2018-11-28T16:35:13.529055+00:00 ip-10-128-152-49 cloud-init: return self.get_url(path, '', True, saltenv, cachedir=cachedir)
2018-11-28T16:35:13.532046+00:00 ip-10-128-152-49 cloud-init: File "/usr/lib/python2.7/site-packages/salt/fileclient.py", line 494, in get_url
2018-11-28T16:35:13.535280+00:00 ip-10-128-152-49 cloud-init: result = self.get_file(url, dest, makedirs, saltenv, cachedir=cachedir)
2018-11-28T16:35:13.538335+00:00 ip-10-128-152-49 cloud-init: File "/usr/lib/python2.7/site-packages/salt/fileclient.py", line 1145, in get_file
2018-11-28T16:35:13.541621+00:00 ip-10-128-152-49 cloud-init: data = self.channel.send(load, raw=True)
2018-11-28T16:35:13.544750+00:00 ip-10-128-152-49 cloud-init: File "/usr/lib/python2.7/site-packages/salt/utils/async.py", line 65, in wrap
2018-11-28T16:35:13.548071+00:00 ip-10-128-152-49 cloud-init: ret = self._block_future(ret)
2018-11-28T16:35:13.551304+00:00 ip-10-128-152-49 cloud-init: File "/usr/lib/python2.7/site-packages/salt/utils/async.py", line 75, in _block_future
2018-11-28T16:35:13.554546+00:00 ip-10-128-152-49 cloud-init: return future.result()
2018-11-28T16:35:13.557950+00:00 ip-10-128-152-49 cloud-init: File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result
2018-11-28T16:35:13.561205+00:00 ip-10-128-152-49 cloud-init: raise_exc_info(self._exc_info)
2018-11-28T16:35:13.564478+00:00 ip-10-128-152-49 cloud-init: File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 876, in run
2018-11-28T16:35:13.568139+00:00 ip-10-128-152-49 cloud-init: yielded = self.gen.throw(*exc_info)
2018-11-28T16:35:13.571683+00:00 ip-10-128-152-49 cloud-init: File "/usr/lib/python2.7/site-packages/salt/transport/zeromq.py", line 312, in send
2018-11-28T16:35:13.575103+00:00 ip-10-128-152-49 cloud-init: ret = yield self._crypted_transfer(load, tries=tries, timeout=timeout, raw=raw)
2018-11-28T16:35:13.578736+00:00 ip-10-128-152-49 cloud-init: File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 870, in run
2018-11-28T16:35:13.582255+00:00 ip-10-128-152-49 cloud-init: value = future.result()
2018-11-28T16:35:13.585869+00:00 ip-10-128-152-49 cloud-init: File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result
2018-11-28T16:35:13.589636+00:00 ip-10-128-152-49 cloud-init: raise_exc_info(self._exc_info)
2018-11-28T16:35:13.593537+00:00 ip-10-128-152-49 cloud-init: File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 876, in run
2018-11-28T16:35:13.597250+00:00 ip-10-128-152-49 cloud-init: yielded = self.gen.throw(*exc_info)
2018-11-28T16:35:13.604695+00:00 ip-10-128-152-49 cloud-init: File "/usr/lib/python2.7/site-packages/salt/transport/zeromq.py", line 284, in _crypted_transfer
2018-11-28T16:35:13.608535+00:00 ip-10-128-152-49 cloud-init: ret = yield _do_transfer()
2018-11-28T16:35:13.612022+00:00 ip-10-128-152-49 cloud-init: File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 870, in run
2018-11-28T16:35:13.615530+00:00 ip-10-128-152-49 cloud-init: value = future.result()
2018-11-28T16:35:13.619175+00:00 ip-10-128-152-49 cloud-init: File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result
2018-11-28T16:35:13.622702+00:00 ip-10-128-152-49 cloud-init: raise_exc_info(self._exc_info)
2018-11-28T16:35:13.626336+00:00 ip-10-128-152-49 cloud-init: File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 879, in run
2018-11-28T16:35:13.629839+00:00 ip-10-128-152-49 cloud-init: yielded = self.gen.send(value)
2018-11-28T16:35:13.633372+00:00 ip-10-128-152-49 cloud-init: File "/usr/lib/python2.7/site-packages/salt/transport/zeromq.py", line 271, in _do_transfer
2018-11-28T16:35:13.636931+00:00 ip-10-128-152-49 cloud-init: data = self.auth.crypticle.loads(data, raw)
2018-11-28T16:35:13.640794+00:00 ip-10-128-152-49 cloud-init: File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 1316, in loads
2018-11-28T16:35:13.644318+00:00 ip-10-128-152-49 cloud-init: data = self.decrypt(data)
2018-11-28T16:35:13.647997+00:00 ip-10-128-152-49 cloud-init: File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 1296, in decrypt
2018-11-28T16:35:13.651578+00:00 ip-10-128-152-49 cloud-init: raise AuthenticationError('message authentication failed')
2018-11-28T16:35:13.655231+00:00 ip-10-128-152-49 cloud-init: AuthenticationError: message authentication failed
2018-11-28T16:35:13.658805+00:00 ip-10-128-152-49 cloud-init: [INFO    ] Completed state [setup-secondary-ips] at time 16:35:13.491356 duration_in_ms=196.894
```

### Versions Report
```
# salt --versions-report
Salt Version:
           Salt: 2017.7.8

Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Oct 30 2018, 23:45:53)
   python-gnupg: 0.4.2
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```
Master and minion are on the same version, in this setup the master is `ip-10-128-152-17.ec2.internal` and the problem state is hit on the minion `ip-10-128-152-49.ec2.internal` running highstate.
```
# salt '*' test.ping
ip-10-128-152-17.ec2.internal:
    True
ip-10-128-152-49.ec2.internal:
    True
```

**Comment by dwoz** [comment]
@icycle77 Thank you for reporting this issues. I have a couple comments and questions.

It doesn't look like the script itself has anything to do with the traceback. The traceback is indicating the authentication failure happens while trying to download the script from the master. Also, I don't think time has anything to do with authentication and it does not look like the time change based on what is in the logs.

It seems like something is happening to cause the key of the minion or master to change.

Did the state in question with your custom script work before the upgrade?
Are you running salt directly or using some other tool? (I ask because of the 'cloud-init' prefix in the logs)

**Comment by icycle77** [comment]
@dwoz thanks for taking a look. 

Glad to hear it initially doesn't appear to be related to the contents of the Py script nor the clock.

Yes, everything worked well as-is before the upgrade but like I said, the Linux distribution package update did touch a lot of packages. I made no changes to anything else, especially the salt tree, here.

We are using `cloud-init` to bootstrap our AWS EC2 instances, which effectively ends up calling a highstate. No change here from before.

**Comment by icycle77** [comment]
I downgraded just `salt` to `2017.7.7` and reproduced the problem. So, this has nothing to do with salt changes from .7 to .8, it's some other change that's affecting salt.

**Comment by icycle77** [comment]
I filed this as the next logical place for tracking this issue:
https://bugs.python.org/issue35737

**Comment by icycle77** [comment]
It looks like the Python folks are leaning towards labeling this issue as a Salt custom validation error on stale Python: https://bugs.python.org/issue35737#msg334038. We are using latest RHEL 7.6 in this case, so I would have thought it'd be current enough.

Where does the SaltStack community stand on this issue?

**Comment by icycle77** [comment]
@dwoz or anyone at SaltStack--could I get a second look at this issue? I'm happy to try reducing this to a simple reproducer but I'm so far at a loss for what's actually happening here.
