### ISSUE TITLE
Salt error not helpful when using bad syntax in listen_in

### ISSUE THREAD

**Issue by Poil** [saltstack/salt#50681]
### Description of Issue/Question

When doing this error in a formula, it's very difficult to understand the error

```
m2crypto:
  pkg.installed
    - listen_in: salt-minion
```

```
[root@tlsslt-p01-mst minion.d]# salt --state-output=changes 'flxcdb-d01-stb*' state.apply
flxcdb-d01-stb.team2:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1606, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 749, in apply_
        return highstate(**kwargs)
      File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 1053, in highstate
        orchestration_jid=orchestration_jid)
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 3931, in call_highstate
        return self.state.call_high(high, orchestration_jid)
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 2757, in call_high
        ret = self.call_listen(chunks, ret)
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 2671, in call_listen
        for key, val in six.iteritems(l_in):
      File "/usr/lib/python2.7/site-packages/salt/ext/six.py", line 606, in iteritems
        return d.iteritems(**kw)
    AttributeError: 'unicode' object has no attribute 'iteritems'
```

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by Poil** [comment]
It seems I'm in this situation : #37034
