### ISSUE TITLE
ImportError: No module named singledispatch

### ISSUE THREAD

**Issue by andyyumiao** [saltstack/salt#50807]
### Description of Issue/Question
I got this error when I run "salt-ssh -L 'xxx.xxx.xxx.xxx' test.ping"

### Steps to Reproduce Issue
xxx.xxx.xxx.xxx:
    ----------
    retcode:
        0
    stderr:
        Traceback (most recent call last):
          File "/var/tmp/.root_4032f8_salt/salt-call", line 15, in <module>
            salt_call()
          File "/var/tmp/.root_4032f8_salt/py2/salt/scripts.py", line 428, in salt_call
            import salt.cli.call
          File "/var/tmp/.root_4032f8_salt/py2/salt/cli/call.py", line 6, in <module>
            from salt.utils import parsers
          File "/var/tmp/.root_4032f8_salt/py2/salt/utils/parsers.py", line 28, in <module>
            import salt.config as config
          File "/var/tmp/.root_4032f8_salt/py2/salt/config/__init__.py", line 100, in <module>
            _DFLT_IPC_WBUFFER = _gather_buffer_space() * .5
          File "/var/tmp/.root_4032f8_salt/py2/salt/config/__init__.py", line 90, in _gather_buffer_space
            import salt.grains.core
          File "/var/tmp/.root_4032f8_salt/py2/salt/grains/core.py", line 47, in <module>
            import salt.utils.dns
          File "/var/tmp/.root_4032f8_salt/py2/salt/utils/dns.py", line 28, in <module>
            import salt.modules.cmdmod
          File "/var/tmp/.root_4032f8_salt/py2/salt/modules/cmdmod.py", line 35, in <module>
            import salt.utils.templates
          File "/var/tmp/.root_4032f8_salt/py2/salt/utils/templates.py", line 31, in <module>
            import salt.utils.http
          File "/var/tmp/.root_4032f8_salt/py2/salt/utils/http.py", line 41, in <module>
            import salt.loader
          File "/var/tmp/.root_4032f8_salt/py2/salt/loader.py", line 30, in <module>
            import salt.utils.event
          File "/var/tmp/.root_4032f8_salt/py2/salt/utils/event.py", line 74, in <module>
            import salt.payload
          File "/var/tmp/.root_4032f8_salt/py2/salt/payload.py", line 17, in <module>
            import salt.crypt
          File "/var/tmp/.root_4032f8_salt/py2/salt/crypt.py", line 62, in <module>
            import tornado.gen
          File "/var/tmp/.root_4032f8_salt/py2/tornado/gen.py", line 97, in <module>
            from singledispatch import singledispatch  # backport
        ImportError: No module named singledispatch

### Versions Report
Salt Version:
           Salt: 2017.7.8
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.2.5
 
System Versions:
           dist: centos 7.2.1511 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-327.28.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

**Comment by andyyumiao** [comment]
I have try to install singledispatch separately and degrade tornado version, but it also not work

**Comment by dwoz** [comment]
@andyyumiao Thank you for reporting this. Can you provide us with the output of `pip freeze` on the box where you are running the `salt-ssh` command?

**Comment by PeterS242** [comment]
I'm getting the same error on a **McAfee Web Gateway v7.8** system (they seemingly recently rebased their OS off **CentOS 7**--it used to be **CentOS 6**.)  Should I create a new Issue or just append here?  The **McAfee** **CentOS 7**-based system has a newer variant of tornado which I suspect is causing it: ```python2-tornado-4.4.2-2.mlos3.x86_64```.
