### ISSUE TITLE
solarisips fails on multiple package installs

### ISSUE THREAD

**Issue by clallen** [saltstack/salt#50874]
### Description of Issue/Question
When using the "pkgs" option of the solarisips module, this exception is thrown:
```
AttributeError: 'unicode' object has no attribute 'items'
Traceback (most recent call last):
  File "/sbin/salt-call", line 11, in <module>
    salt_call()
  File "/opt/apps/unix/salt/lib/python2.7/site-packages/salt/scripts.py", line 410, in salt_call
    client.run()
  File "/opt/apps/unix/salt/lib/python2.7/site-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/opt/apps/unix/salt/lib/python2.7/site-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/opt/apps/unix/salt/lib/python2.7/site-packages/salt/cli/caller.py", line 212, in call
    ret['return'] = func(*args, **kwargs)
  File "/opt/apps/unix/salt-2018.3.3/lib/python2.7/site-packages/salt/modules/solarisips.py", line 477, in install
    if list(pkg.items())[0][1]:   # version specified
AttributeError: 'unicode' object has no attribute 'items'
```
This appears to be caused by the "pkg" str being treated as a dict (```pkg.items()```).

I thought about writing a fix for it but I'm unsure what the reasoning behind the dict assumption was.

Single package installs work fine.
### Steps to Reproduce Issue
On Solaris, run the pkg.install function with the pkgs arg as documented:
```
salt-call pkg.install pkgs='["pkg:/library/motif", "pkg:/compatibility/packages/SUNWxwplr"]'
```
### Versions Report
```
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.11
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.0
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15 (default, Dec  9 2018, 16:53:27)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 5.1.1
            ZMQ: 4.3.0

System Versions:
           dist:
         locale: 646
        machine: sun4v
        release: 5.11
         system: SunOS
        version: Not Installed
```

**Comment by Ch3LL** [comment]
yeah it looks like it specifically states that it should be a list: https://github.com/saltstack/salt/blob/v2018.3.3/salt/modules/solarisips.py#L455

Seems it needs to be handled that way instead of using `.items()`. If we are worried about keeping the ability to specify a dictionary, we could just add a check right before there to see if its a list type and handle it there.
