### ISSUE TITLE
Unable to start salt minion in RHEL 6, but no error in salt-minion -l debug

### ISSUE THREAD

**Issue by sandilyasd** [saltstack/salt#50957]
###Description
Getting an error "unable to load the config values from /etc/salt while starting the salt-minion service.
[root@xxxxxxxxx bin]# service salt-minion start
ERROR: Unable to look-up config values for /etc/salt

I have tried to run the salt-minion -l debug but the minion is successfully able to connect to minion and able to receive the requests and data from master.

However i am getting the below error when i am running the "salt-call -c /etc/salt/minion --local config.get sock_dir"

[root@xxxxxxxxx bin]# salt-call -c /etc/salt/minion --local config.get sock_dir
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 405, in salt_call
   import salt.cli.call
  File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 8, in <module>
    import salt.cli.caller
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 37, in <module>
    from raet import raeting, nacling
  File "/usr/lib/python2.7/site-packages/raet/__init__.py", line 12, in <module>
    importlib.import_module(".{0}".format(m), package='raet')
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/site-packages/raet/nacling.py", line 11, in <module>
    import libnacl
  File "/usr/lib/python2.7/site-packages/libnacl/__init__.py", line 119, in <module>
    crypto_box_SEEDBYTES = nacl.crypto_box_seedbytes()
  File "/usr/lib64/python2.7/ctypes/__init__.py", line 370, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib64/python2.7/ctypes/__init__.py", line 375, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib64/libsodium.so: undefined symbol: crypto_box_seedbytes

### Steps to Reproduce Issue
1. Download all the rpm packages from the salt repo and install them manually in RHEL 6 Operating system.
2. Update the salt master and master_finger in the minion configuration.
3. start the salt-minion service using service salt-minon start 

### Versions Report
Getting the below error
[root@xxxxxxxx bin]# salt-call --versions-report
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 405, in salt_call
    import salt.cli.call
  File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 8, in <module>
    import salt.cli.caller
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 37, in <module>
    from raet import raeting, nacling
  File "/usr/lib/python2.7/site-packages/raet/__init__.py", line 12, in <module>
    importlib.import_module(".{0}".format(m), package='raet')
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/site-packages/raet/nacling.py", line 11, in <module>
    import libnacl
  File "/usr/lib/python2.7/site-packages/libnacl/__init__.py", line 119, in <module>
    crypto_box_SEEDBYTES = nacl.crypto_box_seedbytes()
  File "/usr/lib64/python2.7/ctypes/__init__.py", line 370, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib64/python2.7/ctypes/__init__.py", line 375, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib64/libsodium.so: undefined symbol: crypto_box_seedbytes

**Comment by garethgreenaway** [comment]
@sandilyasd Thanks for the report.  Can you provide your minion configuration? 
@dwoz This looks like it might be something related to crypto libraries installed, any thoughts?

**Comment by dwoz** [comment]
I've tested this with the 2018.3 with and without python-libnacl installed but was not able to reproduce the issue.

**Comment by sandilyasd** [comment]
@dwoz salt-minion version installed is 2018.3.2
