### ISSUE TITLE
ZMQError: Operation not supported by device

### ISSUE THREAD

**Issue by wzlee** [saltstack/salt#50986]
### Error Log
```
[INFO    ] Starting the Salt Publisher on tcp://salt:4505
Process salt.transport.zeromq.<type 'instancemethod'>.zmq_device:
Traceback (most recent call last):
Process salt.transport.zeromq.<type 'instancemethod'>._publish_daemon:
  File "/usr/local/opt/python@2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
Traceback (most recent call last):
  File "/usr/local/opt/python@2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/local/opt/python@2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/salt/2018.3.2/libexec/lib/python2.7/site-packages/salt/transport/zeromq.py", line 535, in zmq_device
    self.run()
  File "/usr/local/opt/python@2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/salt/2018.3.2/libexec/lib/python2.7/site-packages/salt/transport/zeromq.py", line 809, in _publish_daemon
    self.clients.bind(self.uri)
  File "zmq/backend/cython/socket.pyx", line 547, in zmq.backend.cython.socket.Socket.bind
    pub_sock.bind(pub_uri)
  File "zmq/backend/cython/socket.pyx", line 547, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
    raise ZMQError(errno)
ZMQError: Operation not supported by device
    raise ZMQError(errno)
ZMQError: Operation not supported by device
```
### Versions Report
```
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.27.5
        libnacl: Not Installed
       M2Crypto: 0.30.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.27.1
         Python: 2.7.15 (default, Jun 17 2018, 12:46:58)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 18.2.0
         system: Darwin
        version: 10.14.2 x86_64
```

**Comment by garethgreenaway** [comment]
@wzlee Thanks for the report.  What does `salt` resolve to?  Is it localhost?  The loopback interface?  Thanks!

**Comment by wzlee** [comment]
> @wzlee Thanks for the report. What does `salt` resolve to? Is it localhost? The loopback interface? Thanks!
> @saltstack/team-core fyi.

Yes, I configured the interface is: 127.0.0.1
