### ISSUE TITLE
stacktrace on compound command execution

### ISSUE THREAD

**Issue by hwoarang** [saltstack/salt#51054]
### Description of Issue/Question
Compound command execution as described on https://docs.saltstack.com/en/latest/topics/execution/remote_execution.html#compound-command-execution leads to python stacktrace

```
master:/home/vagrant # salt '*' cmd.run,test.ping,test.echo 'cat /proc/cpuinfo',,foo
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: '>' not supported between instances of 'dict' and 'int'
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python3.6/site-packages/salt/scripts.py", line 485, in salt_main
    client.run()
  File "/usr/lib/python3.6/site-packages/salt/cli/salt.py", line 195, in run
    ret_, out, retcode = self._format_ret(full_ret)
  File "/usr/lib/python3.6/site-packages/salt/cli/salt.py", line 393, in _format_ret
    if ret_retcode > retcode:
TypeError: '>' not supported between instances of 'dict' and 'int'
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python3.6/site-packages/salt/scripts.py", line 485, in salt_main
    client.run()
  File "/usr/lib/python3.6/site-packages/salt/cli/salt.py", line 195, in run
    ret_, out, retcode = self._format_ret(full_ret)
  File "/usr/lib/python3.6/site-packages/salt/cli/salt.py", line 393, in _format_ret
    if ret_retcode > retcode:
TypeError: '>' not supported between instances of 'dict' and 'int'
```

### Setup
openSUSE Leap 15.0
salt-2018.3.0-lp150.3.14.1

### Steps to Reproduce Issue
salt '*' cmd.run,test.ping,test.echo 'cat /proc/cpuinfo',,foo

### Versions Report
```
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.4
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.5 (default, Mar 31 2018, 19:45:04) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.3
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 4.12.14-lp150.12.25-default
         system: Linux
        version: Not Installed
```

**Comment by garethgreenaway** [comment]
@hwoarang Thanks for the report.  I'm not seeing this issue in later versions of 2018.3.x.  Are you able to upgrade to a later version such as 2018.3.3 where the issue appears to be fixed.  Thanks!

**Comment by hwoarang** [comment]
@garethgreenaway Unfortunately openSUSE does not provide 2018.3.3 but they provide 2019.2rc1 and this problem seems to have been fixed there. So I am closing this bug.
