### ISSUE TITLE
Critical error with custom grain after upgrading to 2018

### ISSUE THREAD

**Issue by stjack99** [saltstack/salt#51064]
### Description of Issue/Question
I have a few custom grains for Windows minions that get content from the registry. They've worked in 2017 and 2016 versions of salt, but do not work if I upgrade to 2018.x versions of salt.

### Setup
----- Custom Grain -----
```
import logging
import os
import subprocess

import salt.log
import salt.utils
import salt.utils.network

import salt.modules.cmdmod
import salt.modules.smbios

__salt__ = {
    'cmd.run': salt.modules.cmdmod._run_quiet,
    'cmd.retcode': salt.modules.cmdmod._retcode_quiet,
    'cmd.run_all': salt.modules.cmdmod._run_all_quiet,
    'smbios.records': salt.modules.smbios.records,
    'smbios.get': salt.modules.smbios.get,
}
log = logging.getLogger(__name__)

HAS_WMI = False
if salt.utils.is_windows():
    # attempt to import the python wmi module
    # the Windows minion uses WMI for some of its grains
    try:
        import wmi  # pylint: disable=import-error
        import salt.utils.winapi
        import win32api
        import salt.modules.reg
        HAS_WMI = True
        __salt__['reg.read_value'] = salt.modules.reg.read_value
        __salt__['reg.list_keys'] = salt.modules.reg.list_keys
    except ImportError:
        log.exception(
            'Unable to import Python wmi module, some core grains '
            'will be missing'
        )

def obscureSoftware_installed():
    '''
    Detect if obscureSoftware is installed
    '''
    # Provides:
    #   obscureSoftware_installed

    grains = {}
    if salt.utils.is_windows():
        # Cast to int so that the logic isn't broken when used as a
        # conditional in templating. Also follows _linux_cpudata()
        try:
            keys = __salt__['reg.list_keys'](
             "HKEY_LOCAL_MACHINE",
             "SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall"
             )

            for key in keys:
                prog_name = __salt__['reg.read_value'](
                                   "HKEY_LOCAL_MACHINE",
                                   "SOFTWARE\\WOW6432Node\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\" + key,
                                   "DisplayName").get('vdata')

                if 'Obscure Software' in str(prog_name).lower():
                    obscureSoftware_version = __salt__['reg.read_value'](
                        "HKEY_LOCAL_MACHINE",
                        "SOFTWARE\\WOW6432Node\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\" + key,
                        "DisplayVersion").get('vdata')

                    grains['obscureSoftware_installed'] = True
                    grains['obscureSoftware_version'] = obscureSoftware_version
                    break
                else:
                     grains['obscureSoftware_installed'] = False

        except KeyError:
             grains['obscureSoftware_installed'] = False
    else:
         grains['obscureSoftware_installed'] = False

    return grains
```

----- Output from salt-call saltutil.sync_all -----
```
[CRITICAL] Failed to load grains defined in grain file obscureSoftware_installed.obscureSoftware_installed in function <function obscureSoftware_installed at 0x00000000064F3C88>, error:
Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\loader.py", line 760, in grains
    ret = funcs[key]()
  File "c:\salt\var\cache\salt\minion\extmods\grains\obscureSoftware_installed.py", line 53, in obscureSoftware_installed
    "SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall"
  File "C:\salt\bin\lib\site-packages\salt\modules\reg.py", line 178, in list_keys
    return __utils__['reg.list_keys'](hive=hive,
NameError: global name '__utils__' is not defined
```

### Steps to Reproduce Issue
I get the critical error every time salt runs after the grains are sync'd over.

### Versions Report
This grain works on 2016 and 2017 versions (specifically 2017.7.4). It does not work on 2018.3.2 or 2018.3.3. Master is 2018.3.2 on FreeBSD.

**Comment by garethgreenaway** [comment]
@stjack99 Thanks for the report.  Because of the way the Salt loader work, you need to add `__utils__` to your custom grain similar to how it's done in the zfs grain:
https://github.com/saltstack/salt/blob/develop/salt/grains/zfs.py#L32

Your `__utils__` would look something like this:
```
__utils__ = {
    'reg.list_keys': salt.modules.list_keys,
}
```
