### ISSUE TITLE
salt.http.query() causes jinja template render failure, despite "raise_error = false" if server does not respond or response has zero length

### ISSUE THREAD

**Issue by TheCatFelix** [saltstack/salt#51180]
### Description of Issue/Question

salt.http.query() causes jinja template render failure, despite "raise_error = false" if server does not respond or response has zero length.

Relevant error message:

local:
    Data failed to compile:
----------
    Rendering SLS 'base:test' failed: Jinja error: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 393, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 2, in top-level template code
  File "/usr/lib/python3/dist-packages/salt/modules/http.py", line 38, in query
    return salt.utils.http.query(url=url, opts=opts, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/utils/http.py", line 613, in query
    result_text = __decompressContent(coding, result_text)
  File "/usr/lib/python3/dist-packages/salt/utils/http.py", line 113, in __decompressContent
    log.trace("Decompressing %s byte content with compression type: %s", len(pgctnt), coding)
TypeError: object of type 'NoneType' has no len()

; line 2

---

{% set test = salt.http.query('https://not.a.resolvable.server', raise_error = False) %}    <======================

/home/test/salt/query.txt:
 file.managed:
 - contents: {{ test }}

[...]

Note that when I comment out the following two lines in /usr/lib/python3/dist-packages/salt/utils/http.py, the state runs just fine:

   113	    #log.trace("Decompressing %s byte content with compression type: %s", len(pgctnt), coding)
   133	    #log.trace("Content size after decompression: %s", len(pgctnt))

It appears that the root of the exception is calling len() on an empty object.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

root@debian:/home/test/salt# cat test.sls

{% set test = salt.http.query('https://not.a.resolvable.server', raise_error = False) %}

/home/test/salt/query.txt:
 file.managed:
 - contents: {{ test }}
root@debian:/home/test/salt#

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

root@debian:/home/test/salt# salt-call --local --file-root=/home/test/salt state.apply test

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

(Note: only using masterless salt in this case)

root@debian:/home/test/salt# salt-call --versions-report
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.2 (default, Jan  3 2019, 02:55:40)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: Not Installed
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 5.1.1
            ZMQ: Not Installed

System Versions:
           dist: debian buster/sid
         locale: UTF-8
        machine: x86_64
        release: 4.19.0-1-amd64
         system: Linux
        version: debian buster/sid

root@debian:/home/test/salt#

**Comment by garethgreenaway** [comment]
@TheCatFelix Thanks for the report.  This looks like it should be a fairly easy fix, we just need to test that `pgctnt` is valid, eg. not `None` before attempting to log.

**Comment by dwoz** [comment]
Fixed by #53394 (merged 2019-06-10, commit b6d64f504a6). Present on 3006.x, 3007.x, 3008.x, master via the `if not pgctnt: return pgctnt` guard in `__decompressContent` (salt/utils/http.py). Regression test: `tests/pytests/unit/utils/test_http.py::test_query_null_response`. PR didn't link the issue so it never auto-closed.
