### ISSUE TITLE
file_roots envs with slash leads to "No such file or directory: '/var/cache/salt/master/file_lists/roots/.foo/bar.w'

### ISSUE THREAD

**Issue by sathieu** [saltstack/salt#51211]
### Description of Issue/Question
Using this master config (to workaround #48132):
```yaml
file_roots:
  base:
    - /srv/salt
  feature/2:
    - /srv/salt
```
Salt works incorrectly and logs:
```log
2019-01-08 09:57:23,653 [salt.master      :1795][ERROR   ][28091] Error in function _file_list:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 1788, in run_func
    ret = getattr(self, func)(load)
  File "/usr/lib/python2.7/dist-packages/salt/utils/decorators/__init__.py", line 594, in wrapped
    **salt.utils.data.decode_dict(kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/__init__.py", line 752, in file_list
    ret.update(self.servers[fstr](load))
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/roots.py", line 422, in file_list
    return _file_lists(load, 'files')
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/roots.py", line 310, in _file_lists
    __opts__, form, list_cache, w_lock
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/__init__.py", line 116, in check_file_list_cache
    if not os.path.isfile(list_cache) and _lock_cache(w_lock):
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/__init__.py", line 50, in _lock_cache
    os.mkdir(w_lock)
OSError: [Errno 2] No such file or directory: '/var/cache/salt/master/file_lists/roots/.feature/2.w'
```

### Setup
See above.

### Steps to Reproduce Issue
See above

### Versions Report
2018.3.3 with additionnal patches (#50417, #49987, #50626, #50768, #50783, but those are not related).

**Comment by dwoz** [comment]
@sathieu Thanks for reporting this and working on the fix!
