### ISSUE TITLE
salt-api rest_cherrypy sslobj.do_handshake

### ISSUE THREAD

**Issue by metabsd** [saltstack/salt#51219]
### Description of Issue/Question
I can not start the service properly. There seems to be a problem with the certificate.

### Setup
`/etc/salt/master.d/salt_api.conf`

```
external_auth:
  pam:
    saltapiuser:
      - .*
      - '@runner'

rest_cherrypy:
  port: 8000
#  disable_ssl: true
  ssl_crt: /etc/salt/pki/salt-api/salt-api.crt
  ssl_key: /etc/salt/pki/salt-api/salt-api.key
  ssl_chain: /etc/salt/pki/salt-api/fullchain.pem
```
I try with fullchain and without it. I also try a self-signed and a LetsEncrypt cert.

### Steps to Reproduce Issue
`salt-api -l debug`

```
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/salt_api.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/salt_api.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: hostname.domain
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] Setting up the Salt API
[DEBUG   ] Created pidfile: /var/run/salt-api.pid
[INFO    ] The salt-api is starting up
[INFO    ] Starting rest_cherrypy.start netapi module
[DEBUG   ] Started 'salt.loaded.int.netapi.rest_cherrypy.start' with pid 16705
[DEBUG   ] Process Manager starting!
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[INFO    ] [17/Jan/2019:14:38:48] ENGINE Listening for SIGHUP.
[INFO    ] [17/Jan/2019:14:38:48] ENGINE Listening for SIGTERM.
[INFO    ] [17/Jan/2019:14:38:48] ENGINE Listening for SIGUSR1.
[INFO    ] [17/Jan/2019:14:38:48] ENGINE Bus STARTING
[INFO    ] [17/Jan/2019:14:38:48] ENGINE Started monitor thread '_TimeoutMonitor'.
[INFO    ] [17/Jan/2019:14:38:48] ENGINE Serving on https://0.0.0.0:8000
[INFO    ] [17/Jan/2019:14:38:48] ENGINE Bus STARTED
[ERROR   ] [17/Jan/2019:14:38:48] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cherrypy/wsgiserver/__init__.py", line 2021, in start
    self.tick()
  File "/usr/lib/python2.7/dist-packages/cherrypy/wsgiserver/__init__.py", line 2090, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/usr/lib/python2.7/dist-packages/cherrypy/wsgiserver/ssl_builtin.py", line 67, in wrap
    server_side=True)
  File "/usr/lib/python2.7/ssl.py", line 369, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 617, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 846, in do_handshake
    self._sslobj.do_handshake()
error: [Errno 0] Error

^C[INFO    ] [17/Jan/2019:14:41:27] ENGINE Keyboard Interrupt: shutting down bus
[INFO    ] [17/Jan/2019:14:41:27] ENGINE Bus STOPPING
[INFO    ] [17/Jan/2019:14:41:27] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8000)) shut down
[INFO    ] [17/Jan/2019:14:41:27] ENGINE Stopped thread '_TimeoutMonitor'.
[INFO    ] [17/Jan/2019:14:41:27] ENGINE Bus STOPPED
[INFO    ] [17/Jan/2019:14:41:27] ENGINE Bus EXITING
[INFO    ] [17/Jan/2019:14:41:27] ENGINE Bus EXITED
[INFO    ] [17/Jan/2019:14:41:27] ENGINE Waiting for child threads to terminate...
[WARNING ] SaltAPI received a SIGINT. Exiting.
[INFO    ] The salt-api is shutting down..
The salt-api is shutdown. SaltAPI received a SIGINT. Exited.
```

### Versions Report

```
Salt Version:
           Salt: 2017.7.8

Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: 2.5.1
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-43-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```

**Comment by dwoz** [comment]
@metabsd Thanks for reporting this. I've tested salt-api (2017.7.8) using a self signed certificate. I am able to connect via ssl without a problem.

Here is the script I used to generate the certificate:
```
#!/bin/sh
# generate-ssl.sh - Simple self signed SSL certigicate creation script.
#
# This script will create a self signed certificate for a subdomain of
# 'localhost'. By default the hostname dev.localhost is used. The hostname can
# be overridden by specifying an SSL_HOSTNAME environment variable. For
# example, to create a cert for foo.localhost:
#
# $ SSL_HOSTNAME="foo" generate-ssl.sh
#


unset _HOSTNAME;
_HOSTNAME="${SSL_HOSTNAME}"
if [ -z "${_HOSTNAME}" ]; then
  _HOSTNAME="dev"
fi
echo "Generating self-signed SSL certificate for ${_HOSTNAME}.localhost"
openssl req -subj "/C=US/ST=Arizona/L=Scottsdale/O=Trax Technologies Developer/OU=DevOps/CN=${_HOSTNAME}.localhost" -new  -newkey rsa:2049 -days 365 -nodes -x509 -keyout server.key -out server.crt
```

**Comment by metabsd** [comment]
I got that error. I try with a self signed cert and I got error too.

```
2019-01-23 03:32:42,356 [cherrypy.error   :219 ][ERROR   ][2037] [23/Jan/2019:03:32:42] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cherrypy/wsgiserver/__init__.py", line 2021, in start
    self.tick()
  File "/usr/lib/python2.7/dist-packages/cherrypy/wsgiserver/__init__.py", line 2090, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/usr/lib/python2.7/dist-packages/cherrypy/wsgiserver/ssl_builtin.py", line 67, in wrap
    server_side=True)
  File "/usr/lib/python2.7/ssl.py", line 369, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 617, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 846, in do_handshake
    self._sslobj.do_handshake()
SSLError: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:726)
```

**Comment by metabsd** [comment]
I just tested the salt-api endpoint and it works well ... although I have this error.

```
2019-01-24 17:51:22,980 [cherrypy.error   :219 ][ERROR   ][74041] [24/Jan/2019:17:51:22] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cherrypy/wsgiserver/__init__.py", line 2021, in start
    self.tick()
  File "/usr/lib/python2.7/dist-packages/cherrypy/wsgiserver/__init__.py", line 2090, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/usr/lib/python2.7/dist-packages/cherrypy/wsgiserver/ssl_builtin.py", line 67, in wrap
    server_side=True)
  File "/usr/lib/python2.7/ssl.py", line 369, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 617, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 846, in do_handshake
    self._sslobj.do_handshake()
error: [Errno 0] Error
```

**Comment by bbrendon** [comment]
Anyone figure this out? Looks like I have the same issue.

```
2020-02-14 15:51:46,404 [cherrypy.error   :219 ][ERROR   ][28210] [14/Feb/2020:15:51:46] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cherrypy/wsgiserver/__init__.py", line 2021, in start
    self.tick()
  File "/usr/lib/python3/dist-packages/cherrypy/wsgiserver/__init__.py", line 2090, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/usr/lib/python3/dist-packages/cherrypy/wsgiserver/ssl_builtin.py", line 67, in wrap
    server_side=True)
  File "/usr/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/usr/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

```

**Comment by golmaal** [comment]
I'm having this issue as well... 

`[root@salt ~]# salt --versions-report
Salt Version:
           Salt: 3000

Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: 0.33.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Nov 21 2019, 19:31:34)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist: centos 8.1.1911 Core
         locale: UTF-8
        machine: x86_64
        release: 4.18.0-147.5.1.el8_1.x86_64
         system: Linux
        version: CentOS Linux 8.1.1911 Core
`

`[root@salt dnf]# salt-api -l debug
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/cherrypy.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/cherrypy.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] Setting up the Salt API
[DEBUG   ] Created pidfile: /var/run/salt-api.pid
[INFO    ] The salt-api is starting up
[DEBUG   ] Marking 'base64_encode' as a jinja filter
[DEBUG   ] Marking 'base64_decode' as a jinja filter
[DEBUG   ] Marking 'md5' as a jinja filter
[DEBUG   ] Marking 'sha1' as a jinja filter
[DEBUG   ] Marking 'sha256' as a jinja filter
[DEBUG   ] Marking 'sha512' as a jinja filter
[DEBUG   ] Marking 'hmac' as a jinja filter
[DEBUG   ] Marking 'hmac_compute' as a jinja filter
[DEBUG   ] Marking 'random_hash' as a jinja filter
[DEBUG   ] Marking 'rand_str' as a jinja filter
[DEBUG   ] Marking 'file_hashsum' as a jinja filter
[DEBUG   ] Marking 'http_query' as a jinja filter
[DEBUG   ] Marking 'strftime' as a jinja filter
[DEBUG   ] Marking 'date_format' as a jinja filter
[DEBUG   ] Marking 'yaml_dquote' as a jinja filter
[DEBUG   ] Marking 'yaml_squote' as a jinja filter
[DEBUG   ] Marking 'yaml_encode' as a jinja filter
[DEBUG   ] Marking 'raise' as a jinja global
[DEBUG   ] Marking 'match' as a jinja test
[DEBUG   ] Marking 'equalto' as a jinja test
[DEBUG   ] Marking 'skip' as a jinja filter
[DEBUG   ] Marking 'sequence' as a jinja filter
[DEBUG   ] Marking 'to_bool' as a jinja filter
[DEBUG   ] Marking 'tojson' as a jinja filter
[DEBUG   ] Marking 'quote' as a jinja filter
[DEBUG   ] Marking 'regex_escape' as a jinja filter
[DEBUG   ] Marking 'regex_search' as a jinja filter
[DEBUG   ] Marking 'regex_match' as a jinja filter
[DEBUG   ] Marking 'regex_replace' as a jinja filter
[DEBUG   ] Marking 'uuid' as a jinja filter
[DEBUG   ] Marking 'unique' as a jinja filter
[DEBUG   ] Marking 'min' as a jinja filter
[DEBUG   ] Marking 'max' as a jinja filter
[DEBUG   ] Marking 'avg' as a jinja filter
[DEBUG   ] Marking 'union' as a jinja filter
[DEBUG   ] Marking 'intersect' as a jinja filter
[DEBUG   ] Marking 'difference' as a jinja filter
[DEBUG   ] Marking 'symmetric_difference' as a jinja filter
[INFO    ] Starting rest_cherrypy.start netapi module
[DEBUG   ] Started 'RunNetapi' with pid 18134
[DEBUG   ] Process Manager starting!
[DEBUG   ] LazyLoaded rest_cherrypy.start
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[INFO    ] [17/Feb/2020:16:53:03] ENGINE Listening for SIGTERM.
[INFO    ] [17/Feb/2020:16:53:03] ENGINE Listening for SIGHUP.
[INFO    ] [17/Feb/2020:16:53:03] ENGINE Listening for SIGUSR1.
[INFO    ] [17/Feb/2020:16:53:03] ENGINE Bus STARTING
[INFO    ] [17/Feb/2020:16:53:03] ENGINE Serving on https://127.0.0.1:8000
[INFO    ] [17/Feb/2020:16:53:03] ENGINE Bus STARTED
[ERROR   ] [17/Feb/2020:16:53:03] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/cherrypy/wsgiserver/wsgiserver3.py", line 1684, in start
    self.tick()
  File "/usr/lib/python3.6/site-packages/cherrypy/wsgiserver/wsgiserver3.py", line 1750, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/usr/lib/python3.6/site-packages/cherrypy/wsgiserver/ssl_builtin.py", line 67, in wrap
    server_side=True)
  File "/usr/lib64/python3.6/ssl.py", line 365, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib64/python3.6/ssl.py", line 773, in __init__
    self.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 1033, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 645, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
`

**Comment by jhammons** [comment]
I believe this is a problem with cherrypy? https://github.com/cherrypy/cherrypy/issues/1618

**Comment by hatifnatt** [comment]
Why this is closed? Problem is still present. May be some bugs in CherryPy is the root case of this error but probably Salt team can make some workaround or update documentation to better reflect what can be done to mitigate the problem. Current docs states:

> Note: there is a known SSL traceback for CherryPy versions 3.2.5 through 3.7.x. Please use version 3.2.3 or the latest 10.x version instead.

That's not fully correct, yes CherrPy 3.5 does not work at all, but 8.9.1-2 seems working although it print error in the log during startup.
Why this is important? Because latest Debian (10) and Ubuntu (19.10) only have 8.9.1-2 version of CherryPy. And if you believe the documentation, it is looks like it is impossible to run `salt-api` with SSL without building custom CherryPy package or using external WSGI server but actually it's possibe despite error in the log file. See details below.

Master configuration

```
rest_cherrypy:
  port: 8000
  ssl_crt: '/etc/pki/api/salt.crt'
  ssl_key: '/etc/pki/api/salt.key'
```

**Salt 2019.2.3, Deb 9, CherryPy 3.5.0-2**
`salt-api` doesn't not work at all, I get error in log during startup and although `salt-api` process is running I can't connect to API via HTTPS, browsers thorw SSL related errors:

Firefox - `SSL_ERROR_RX_RECORD_TOO_LONG`
Chromium - `ERR_SSL_PROTOCOL_ERROR`

The error from the log is the same as for the people above.

```
2020-04-21 18:42:34,098 [salt.utils.parsers:1071][WARNING ][2777] SaltAPI received a SIGTERM. Exiting.
2020-04-21 18:42:34,750 [cherrypy.error   :214 ][ERROR   ][4351] [21/Apr/2020:18:42:34] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cherrypy/wsgiserver/wsgiserver2.py", line 1968, in start
    self.tick()
  File "/usr/lib/python2.7/dist-packages/cherrypy/wsgiserver/wsgiserver2.py", line 2035, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/usr/lib/python2.7/dist-packages/cherrypy/wsgiserver/ssl_builtin.py", line 54, in wrap
    ssl_version=ssl.PROTOCOL_SSLv23)
  File "/usr/lib/python2.7/ssl.py", line 943, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 611, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 840, in do_handshake
    self._sslobj.do_handshake()
error: [Errno 0] Error
```


**Salt 2019.2.3, Deb 10, CherryPy 8.9.1-2**
I still get almost exactly same error during startup but actually **I can connect to API via HTTPS.**

```
2020-04-21 18:28:14,606 [salt.utils.parsers:1071][WARNING ][12379] SaltAPI received a SIGTERM. Exiting.
2020-04-21 18:47:16,286 [cherrypy.error   :219 ][ERROR   ][779] [21/Apr/2020:18:47:16] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cherrypy/wsgiserver/__init__.py", line 2021, in start
    self.tick()
  File "/usr/lib/python3/dist-packages/cherrypy/wsgiserver/__init__.py", line 2090, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/usr/lib/python3/dist-packages/cherrypy/wsgiserver/ssl_builtin.py", line 67, in wrap
    server_side=True)
  File "/usr/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/usr/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
```
