### ISSUE TITLE
Unicode exception in saltmaster maintenance thread in 2019.2 RC1

### ISSUE THREAD

**Issue by thusoy** [saltstack/salt#51258]
### Description of Issue/Question

On the current RC I get the follow in the saltmaster log:

```
2019-01-21 08:13:03,063 [salt.utils.process:772 ][ERROR   ][9447] An un-handled exception from the multiprocessing process 'Maintenance-4' was caught:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/process.py", line 765, in _run
    return self._original_run()
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 234, in run
    salt.daemons.masterapi.clean_old_jobs(self.opts)
  File "/usr/lib/python2.7/dist-packages/salt/daemons/masterapi.py", line 169, in clean_old_jobs
    rend=False,
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 883, in __init__
    role='master'
  File "/usr/lib/python2.7/dist-packages/salt/config/__init__.py", line 2434, in minion_config
    minion_id=minion_id)
  File "/usr/lib/python2.7/dist-packages/salt/config/__init__.py", line 3772, in apply_minion_config
    cache_minion_id=cache_minion_id)
  File "/usr/lib/python2.7/dist-packages/salt/config/__init__.py", line 3669, in get_id
    is_ipv4 = salt.utils.network.is_ipv4(newid)
  File "/usr/lib/python2.7/dist-packages/salt/utils/network.py", line 260, in is_ipv4
    return ipaddress.ip_address(ip).version == 4
  File "/usr/lib/python2.7/dist-packages/salt/ext/ipaddress.py", line 115, in ip_address
    return IPv6Address(address)
  File "/usr/lib/python2.7/dist-packages/salt/_compat.py", line 175, in __init__
    elif self._is_packed_binary(address):
  File "/usr/lib/python2.7/dist-packages/salt/_compat.py", line 194, in _is_packed_binary
    packed = bool(int(str(bytearray(data)).encode('hex'), 16))
TypeError: unicode argument without an encoding
```
This is a fresh saltmaster install with no other minions than the saltmaster itself added yet.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
I think you only need to watch saltmaster logs after having run highstate.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
           Salt: 2019.2.0rc1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Sep 26 2018, 18:42:22)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.6 
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-8-amd64
         system: Linux
        version: debian 9.6 
```

**Comment by terminalmage** [comment]
Do you have an `id_function` set up in /etc/salt/minion on the master?

**Comment by terminalmage** [comment]
Note, /etc/salt/minion, not /etc/salt/master

**Comment by thusoy** [comment]
Nope, not in either.

**Comment by terminalmage** [comment]
OK. Can you run:

```
python -c 'import salt.utils.network; print(repr(salt.utils.network.generate_minion_id()))'
```

I'm trying to narrow down what input is being sent to that IP address-checking code, since I'm not able to reproduce it myself.

**Comment by thusoy** [comment]
Sure. Adding some more context too.
```
tarjei@saltmaster:~$ python -c 'import salt.utils.network; print(repr(salt.utils.network.generate_minion_id()))'
u'saltmaster'
tarjei@saltmaster:~$ python -V
Python 2.7.13
```

```
# /etc/salt/minion
id: saltmaster
master: localhost
grains:
    roles:
        - saltmaster
    environment: prod
```

```
# /etc/salt/master
# Drop privileges
user: saltmaster

hash_type: sha256

fileserver_backend:
    - git

# libssh2 used by pygit2 doesn't support ed25519 keys yet
# Ref. https://github.com/libssh2/libssh2/issues/39
gitfs_privkey: /etc/salt/.ssh/id_rsa
gitfs_pubkey: /etc/salt/.ssh/id_rsa.pub

# Note that pygit2 as packaged on debian doesn't support cloning over https
gitfs_remotes:
    - ssh://git@github.com/<repo1>
    - ssh://git@github.com/<repo2>

gitfs_env_whitelist:
    - base

gitfs_root: salt

nodegroups:
    all: '*'

extension_modules: <extensions-path>

ext_pillar:
    - file_tree:
        root_dir: <file-root-path>
        keep_newline: True
    - git:
        - master ssh://git@github.com/<repo1>:
          - root: pillar
          - privkey: /etc/salt/.ssh/id_rsa
          - pubkey: /etc/salt/.ssh/id_rsa.pub
    - <extension-1>: []
    - <extension-2>: []

# Only show output from changed or failing states
# # (can be overridden on the cli by --state-verbose True)
state_verbose: False

yaml_utf8: True
```

**Comment by thusoy** [comment]
```
# /etc/hosts
127.0.0.1		localhost saltmaster
```

**Comment by terminalmage** [comment]
OK, still can't reproduce. Can you try temporarily adding some logging before the call to `is_ipv4` on line 3669 of `/usr/lib/python2.7/dist-packages/salt/config/__init__.py`?

```python
log.error('newid = %r', newid)
```

You should then see error logging with the value being sent to the that function right before the traceback occurs. Hopefully this will give me something I can use to further troubleshoot.

**Comment by thusoy** [comment]
Sure. Is there a way to force the maintenance thread to run or does it happen regularly?

**Comment by terminalmage** [comment]
OK I think I have found the issue. That block with the error is only triggered when the ID is a string of length 16. I can trigger the traceback by feeding it a 16-character-long string:

```pytb
>>> from salt._compat import ipaddress
>>> ipaddress.ip_address(u'saltmaster123456')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/testing/salt/ext/ipaddress.py", line 115, in ip_address
    return IPv6Address(address)
  File "/testing/salt/_compat.py", line 175, in __init__
    elif self._is_packed_binary(address):
  File "/testing/salt/_compat.py", line 194, in _is_packed_binary
    packed = bool(int(str(bytearray(data)).encode('hex'), 16))
TypeError: unicode argument without an encoding
```

Did you earlier have a different ID configured? If not, whatever was generated at the time was likely exactly 16 characters long, which would explain why `saltmaster` is not triggering the traceback.

Ultimately, this check is meant to see if the detected minion ID itself is an IPv4 address. A non-IP address string should never cause an error, it should always return False, and we can do that by simply ignoring the TypeError here.

**Comment by terminalmage** [comment]
Actually, instead of doing that, we may want to ensure that `data` is not a unicode type on PY2... if we're feeding it a unicode type at all, it will cause this TypeError.

**Comment by thusoy** [comment]
Ah, yes, it was 16 characters long actually. Glad you figured out the cause!

**Comment by terminalmage** [comment]
Yeah, I should have a fix ready shortly. Thanks for reporting this. Since this function is designed to check bytes types only, we can just assume false if the string is not a bytestring.
