### ISSUE TITLE
AmazonLinux GitFS PyGit2 AttributeError: '_pygit2.Reference' object has no attribute 'get_object'

### ISSUE THREAD

**Issue by iwillflytothemoon** [saltstack/salt#51270]
### Description of Issue/Question
I am using amazonlinux:2018.03 docker image and trying to setup salt-master with gitfs. I already installed all necessary libraries and no error found after restart salt-master service. But when I run salt-run fileserver.file_list I encountered this error:
```
Exception occurred in runner fileserver.file_list: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 387, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/runners/fileserver.py", line 193, in file_list
    return fileserver.file_list(load=load)
  File "/usr/lib/python2.7/dist-packages/salt/utils/decorators/__init__.py", line 594, in wrapped
    **salt.utils.data.decode_dict(kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/__init__.py", line 752, in file_list
    ret.update(self.servers[fstr](load))
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/gitfs.py", line 185, in file_list
    return _gitfs().file_list(load)
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 2934, in file_list
    return self._file_lists(load, 'files')
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 2911, in _file_lists
    repo_files, repo_symlinks = repo.file_list(load['saltenv'])
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 1777, in file_list
    tree = self.get_tree(tgt_env)
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 1016, in get_tree
    candidate = func(tgt_ref)
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 1852, in get_tree_from_branch
    'refs/remotes/origin/{0}'.format(ref)).get_object().tree
AttributeError: '_pygit2.Reference' object has no attribute 'get_object'
```
### Setup
/etc/salt/master
```
interface: 0.0.0.0

ipv6: False

user: root

file_ignore_glob : ''

auto_accept: True

default_include: master.d/*.conf

file_roots:
  base:
    - /saltstack/salt/base

pillar_roots:
  base:
    - /saltstack/pillar/base
```
/etc/salt/master.d/gitfs.conf
```
fileserver_backend:
  - roots
  - git

gitfs_remotes:
  - https://github.com/saltstack-formulas/users-formula.git
```

### Steps to Reproduce Issue
1. Install required libraries and follow this instruction: https://www.pygit2.org/install.html
2. Setup salt configuration same as above
3. Run `salt-run fileserver.file_list`

### Versions Report
```
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: 1.11.5
       cherrypy: 3.2.2
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.27.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.27.4
         Python: 2.7.15 (default, Nov 28 2018, 22:38:08)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist:
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.15.0-43-generic
         system: Linux
        version: Not Installed
```

**Comment by Ch3LL** [comment]
looks like in pygit version `0.27.4 (2019-01-19)` they removed get_object. From the changelog:

https://github.com/libgit2/pygit2/blob/master/CHANGELOG.rst

```
Breaking changes:

Remove deprecated Reference.get_object(), use Reference.peel() instead
```

ping @terminalmage

**Comment by terminalmage** [comment]
Fixed in https://github.com/saltstack/salt/pull/51304

**Comment by iwillflytothemoon** [comment]
@terminalmage will try it now. I will give an update later. Thanks.

**Comment by iwillflytothemoon** [comment]
Downgrading pygit2 version fixed the issue. I updated my formula and it worked. 
```
linux_salt_master_gitfs_pip_packages:
  module.run:
    - name: pip.install
    - pkgs:
        - pygit2==0.27.3
```
thanks @terminalmage @Ch3LL

**Comment by FinalProjectGit** [comment]
> looks like in pygit version `0.27.4 (2019-01-19)` they removed get_object. From the changelog:
> 
> https://github.com/libgit2/pygit2/blob/master/CHANGELOG.rst
> 
> ```
> Breaking changes:
> 
> Remove deprecated Reference.get_object(), use Reference.peel() instead
> ```
> ping @terminalmage

Thanks a lottt!!

**Comment by terminalmage** [comment]
The fix for this was merged almost a year ago. This issue should be closed immediately and not because of a bot.
