### ISSUE TITLE
errors while doing salt-ssh on Windows target

### ISSUE THREAD

**Issue by rv93** [saltstack/salt#51302]
### Description of Issue/Question
Getting errors while doing salt-ssh on windows target
Source machine : Ubuntu 16.04 Salt-2018.3.3
Target Machine : Windows Server 2016 Salt-2017.7.8

### Setup
Using roster file as following : 
```
server1:
  host: server1
  user: myuser
  password: xxxxx
  sudo: True
```

### Steps to Reproduce Issue
`salt-ssh -i 'server1' test.ping `

```
[DEBUG   ] Executed SHIM command. Command logged to TRACE
[DEBUG   ] Child Forked! PID: 4773  STDOUT_FD: 13  STDERR_FD: 15
[DEBUG   ] VT: Salt-SSH SHIM Terminal Command executed. Logged to TRACE
[DEBUG   ] RETCODE server1: 1
[ERROR   ] An un-handled exception from the multiprocessing process 'MultiprocessingProcess-1' was caught:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/salt/utils/process.py", line 747, in _run
    return self._original_run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 522, in handle_routine
    stdout, stderr, retcode = single.run()
  File "/usr/local/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 998, in run
    stdout, stderr, retcode = self.cmd_block()
  File "/usr/local/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 1307, in cmd_block
    saltwinshell.deploy_python(self)
NameError: global name 'saltwinshell' is not defined
Process MultiprocessingProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/salt/utils/process.py", line 747, in _run
    return self._original_run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 522, in handle_routine
    stdout, stderr, retcode = single.run()
  File "/usr/local/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 998, in run
    stdout, stderr, retcode = self.cmd_block()
  File "/usr/local/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 1307, in cmd_block
    saltwinshell.deploy_python(self)
NameError: global name 'saltwinshell' is not defined
[ERROR   ] Target 'DEV-WE-VM-EVA09.afftech.info' did not return any data, probably due to an error.
[DEBUG   ] Child Forked! PID: 4777  STDOUT_FD: 12  STDERR_FD: 14
[DEBUG   ] Terminal Command: /bin/sh -c ssh-copy-id -i /etc/salt/pki/master/ssh/salt-ssh.rsa.pub '-o ControlMaster=auto -o StrictHostKeyChecking=no -o GSSAPIAuthentication=no -o ConnectTimeout=120 -o StrictHostKeyChecking=no -o PasswordAuthentication=yes -o PubkeyAuthentication=yes -o Port=22 -o User=myuser  -p 22  myuser@server1'
[DEBUG   ] Child Forked! PID: 4799  STDOUT_FD: 12  STDERR_FD: 14
[DEBUG   ] Terminal Command: /bin/sh -c ssh-copy-id -i /etc/salt/pki/master/ssh/salt-ssh.rsa.pub -o ControlMaster=auto -o StrictHostKeyChecking=no -o GSSAPIAuthentication=no -o ConnectTimeout=120 -o StrictHostKeyChecking=no -o PasswordAuthentication=yes -o PubkeyAuthentication=yes -o Port=22 -o User=myuser  -p 22  myuser@server1'
[DEBUG   ] LazyLoaded nested.output
server1:
    Target 'server1' did not return any data, probably due to an error.
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: 'str' object does not support item assignment
Traceback (most recent call last):
  File "/usr/local/bin/salt-ssh", line 11, in <module>
    sys.exit(salt_ssh())
  File "/usr/local/lib/python2.7/dist-packages/salt/scripts.py", line 435, in salt_ssh
    client.run()
  File "/usr/local/lib/python2.7/dist-packages/salt/cli/ssh.py", line 24, in run
    ssh.run()
  File "/usr/local/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 799, in run
    data['jid'] = jid  # make the jid in the payload the same as the jid in the tag
TypeError: 'str' object does not support item assignment

```
### Versions Report
Master : 
```
Salt Version:
           Salt: 2018.3.3
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.7.5
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 2.0.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.0
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 12 2018, 14:36:49)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 5.1.1
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.15.0-43-generic
         system: Linux
        version: Ubuntu 16.04 xenial
 
```

I read an answer posted in Feb 2017 that salt-ssh is not supported for windows. I however couldn't confirm this anywhere in the doc if it's available now.  Please let me know what's the current status.
Thanks

**Comment by garethgreenaway** [comment]
@rv93 Thanks for the report.  Support for salt-ssh on Windows is only available using Salt Enterprise.

**Comment by rv93** [comment]
Okay, thanks for the confirmation. 
Would appreciate if we can have this info added in the docs as well, just so others find it easy too. 
Thanks
