### ISSUE TITLE
execute cp.get_dir

### ISSUE THREAD

**Issue by linuxyn** [saltstack/salt#51316]
Hello, when I installed the salt 2018.3.0 version, I can't execute cp.get_dir, cp.get_file can be used normally.
Error is as follows：
[root@master_1 qfpay]# salt 'minion_1' cp.get_dir salt://f5 /tmp/

minion_1:
The minion function caused an exception: Traceback (most recent call last):
File "/home/qfpay/python/lib/python2.7/site-packages/salt/minion.py", line 1600, in _thread_return
return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
File "/home/qfpay/python/lib/python2.7/site-packages/salt/executors/direct_call.py", line 12, in execute
return func(*args, **kwargs)
File "/home/qfpay/python/lib/python2.7/site-packages/salt/modules/cp.py", line 352, in get_dir
return client().get_dir(path, dest, saltenv, gzip)
File "/home/qfpay/python/lib/python2.7/site-packages/salt/fileclient.py", line 437, in get_dir
for fn in self.file_list(saltenv, prefix=path):
File "/home/qfpay/python/lib/python2.7/site-packages/salt/fileclient.py", line 1276, in file_list
return salt.utils.data.decode(self.channel.send(load)) if six.PY2 
File "/home/qfpay/python/lib/python2.7/site-packages/salt/utils/async.py", line 64, in wrap
ret = self._block_future(ret)
File "/home/qfpay/python/lib/python2.7/site-packages/salt/utils/async.py", line 74, in _block_future
return future.result()
File "/home/qfpay/python/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
raise_exc_info(self._exc_info)
File "/home/qfpay/python/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run
yielded = self.gen.throw(*exc_info)
File "/home/qfpay/python/lib/python2.7/site-packages/salt/transport/zeromq.py", line 324, in send
ret = yield self._crypted_transfer(load, tries=tries, timeout=timeout, raw=raw)
File "/home/qfpay/python/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
value = future.result()
File "/home/qfpay/python/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
raise_exc_info(self._exc_info)
File "/home/qfpay/python/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run
yielded = self.gen.throw(*exc_info)
File "/home/qfpay/python/lib/python2.7/site-packages/salt/transport/zeromq.py", line 292, in _crypted_transfer
ret = yield _do_transfer()
File "/home/qfpay/python/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
value = future.result()
File "/home/qfpay/python/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
raise_exc_info(self._exc_info)
File "/home/qfpay/python/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run
yielded = self.gen.throw(*exc_info)
File "/home/qfpay/python/lib/python2.7/site-packages/salt/transport/zeromq.py", line 276, in _do_transfer
tries=tries,
File "/home/qfpay/python/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
value = future.result()
File "/home/qfpay/python/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
raise_exc_info(self._exc_info)
File "", line 3, in raise_exc_info
SaltReqTimeoutError: Message timed out

[root@master_1 qfpay]# salt -V
Salt Version:
Salt: 2018.3.0

Dependency Versions:
cffi: 1.11.2
cherrypy: 3.2.3
dateutil: 2.6.1
docker-py: Not Installed
gitdb: Not Installed
gitpython: Not Installed
ioflo: Not Installed
Jinja2: 2.10
libgit2: Not Installed
libnacl: Not Installed
M2Crypto: Not Installed
Mako: 1.0.7
msgpack-pure: Not Installed
msgpack-python: 0.5.6
mysql-python: 1.3.12
pycparser: 2.18
pycrypto: 3.7.2
pycryptodome: Not Installed
pygit2: Not Installed
Python: 2.7.9 (default, Sep 30 2017, 07:50:44)
python-gnupg: Not Installed
PyYAML: 3.12
PyZMQ: 16.0.3
RAET: Not Installed
smmap: Not Installed
timelib: Not Installed
Tornado: 4.5.3
ZMQ: 4.1.6

System Versions:
dist: centos 6.9 Final
locale: UTF-8
machine: x86_64
release: 2.6.32-696.el6.x86_64
system: Linux
version: CentOS 6.9 Final
#-------------------------------------------------------------
[root@minion_1 ~]# /home/qfpay/python/bin/salt-minion -V
Salt Version:
Salt: 2018.3.0

Dependency Versions:
cffi: Not Installed
cherrypy: Not Installed
dateutil: 2.7.3
docker-py: Not Installed
gitdb: Not Installed
gitpython: Not Installed
ioflo: Not Installed
Jinja2: 2.10
libgit2: Not Installed
libnacl: Not Installed
M2Crypto: Not Installed
Mako: Not Installed
msgpack-pure: Not Installed
msgpack-python: 0.5.6
mysql-python: Not Installed
pycparser: Not Installed
pycrypto: 2.6.1
pycryptodome: Not Installed
pygit2: Not Installed
Python: 2.7.14 (default, Apr 16 2018, 15:25:21)
python-gnupg: Not Installed
PyYAML: 3.12
PyZMQ: 17.0.0
RAET: Not Installed
smmap: Not Installed
timelib: Not Installed
Tornado: 4.5.3
ZMQ: 4.1.6

System Versions:
dist: centos 6.9 Final
locale: UTF-8
machine: x86_64
release: 2.6.32-696.el6.x86_64
system: Linux
version: CentOS 6.9 Final

Error log of minion is as follows:
2019-01-10 10:25:19,185 [salt.minion :1658][WARNING ][10099] The minion function caused an exception

**Comment by garethgreenaway** [comment]
@linuxyn Thanks for the report.  2018.3.0 is a few months old at this point, are you able to upgrade to the latest 2018.3 release which is 2018.3.3? Thanks!

**Comment by linuxyn** [comment]
When I installed the 2018.3.3 version, I still can't execute the cp.get_dir module, and other modules can be used normally. I don't know how to solve it

(salt_env) [root@master_1 ~]# salt-master -V
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Jan 10 2019, 19:00:36)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.6

System Versions:
           dist: centos 6.9 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-696.el6.x86_64
         system: Linux
        version: CentOS 6.9 Final


(salt_env) [root@master_1 ~]# salt 'minion_1' cp.get_file salt://hosts /tmp
minion_1:
    /tmp/hosts
(salt_env) [root@master_1 ~]#
(salt_env) [root@master_1 ~]# salt 'minion_1' cp.get_dir salt://d1 /tmp -l debug
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/api.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/api.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/eauth.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/eauth.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/reactor.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/reactor.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: master_1
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/api.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/api.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/eauth.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/eauth.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/reactor.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/reactor.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: master_1
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/master', u'master_1_master', u'tcp://xxx.xx.xxx.xx:4506', u'clear')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://xxx.xx.xxx.xx:4506
[DEBUG   ] Trying to connect to: tcp://xxx.xx.xxx.xx:4506
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/7b/629b2a9eed8852eaddeca750bf05a74d77f4e357c82764600db6cbf025d18a/.minions.p
[DEBUG   ] get_iter_returns for jid 20190128113011780024 sent to set(['minion_1']) will timeout at 11:30:16.813951
[DEBUG   ] Checking whether jid 20190128113011780024 is still running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/master', u'master_1_master', u'tcp://xxx.xx.xxx.xx:4506', u'clear')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://xxx.xx.xxx.xx:4506
[DEBUG   ] Trying to connect to: tcp://xxx.xx.xxx.xx:4506
[DEBUG   ] Passing on saltutil error. Key 'u'retcode' missing from client return. This may be an error in the client.
[DEBUG   ] Checking whether jid 20190128113011780024 is still running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/master', u'master_1_master', u'tcp://xxx.xx.xxx.xx:4506', u'clear')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://xxx.xx.xxx.xx:4506
[DEBUG   ] Trying to connect to: tcp://xxx.xx.xxx.xx:4506
[DEBUG   ] SaltReqTimeoutError, retrying. (1/3)
[DEBUG   ] SaltReqTimeoutError, retrying. (2/3)
[DEBUG   ] SaltReqTimeoutError, retrying. (3/3)
[DEBUG   ] Re-init ZMQ socket: Message timed out
[DEBUG   ] Trying to connect to: tcp://xxx.xx.xxx.xx:4506
[DEBUG   ] LazyLoaded nested.output
Salt request timed out. The master is not responding. You may need to run your command with `--async` in order to bypass the congested event bus. With `--async`, the CLI tool will print the job id (jid) and exit immediately without listening for responses. You can then use `salt-run jobs.lookup_jid` to look up the results of the job in the job cache later.


The error on the minion side is as follows：
(salt_env) [root@minion_1 ~]# tail -f /var/log/salt/minion
2019-01-28 11:30:11,799 [salt.minion                                                        :1429][INFO    ][12344] User root Executing command cp.get_dir with jid 20190128113011780024
2019-01-28 11:30:11,811 [salt.minion                                                        :1436][DEBUG   ][12344] Command details {u'tgt_type': u'glob', u'jid': u'20190128113011780024', u'tgt': u'minion_1', u'ret': u'', u'user': u'root', u'arg': [u'salt://d1', u'/tmp'], u'fun': u'cp.get_dir'}
2019-01-28 11:30:11,853 [salt.minion                                                        :1564][INFO    ][1888] Starting a new job with PID 1888
2019-01-28 11:30:11,857 [salt.utils.lazy                                                    :100 ][DEBUG   ][1888] LazyLoaded cp.get_dir
2019-01-28 11:30:11,859 [salt.utils.lazy                                                    :100 ][DEBUG   ][1888] LazyLoaded direct_call.execute
2019-01-28 11:30:11,869 [salt.transport.zeromq                                              :128 ][DEBUG   ][1888] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/minion', u'minion_1', u'tcp://xxx.xx.xxx.xx:4506', u'aes')
2019-01-28 11:30:11,869 [salt.crypt                                                         :463 ][DEBUG   ][1888] Initializing new AsyncAuth for (u'/etc/salt/pki/minion', u'minion_1', u'tcp://xxx.xx.xxx.xx4506')
2019-01-28 11:30:11,871 [salt.transport.zeromq                                              :194 ][DEBUG   ][1888] Connecting the Minion to the Master URI (for the return server): tcp://xxx.xx.xxx.xx:4506
2019-01-28 11:30:11,871 [salt.transport.zeromq                                              :1029][DEBUG   ][1888] Trying to connect to: tcp://xxx.xx.xxx.xx:4506
2019-01-28 11:30:16,911 [salt.minion                                                        :1429][INFO    ][12344] User root Executing command saltutil.find_job with jid 20190128113016876181
2019-01-28 11:30:16,911 [salt.minion                                                        :1436][DEBUG   ][12344] Command details {u'tgt_type': u'list', u'jid': u'20190128113016876181', u'tgt': [u'minion_1'], u'ret': u'', u'user': u'root', u'arg': [u'20190128113011780024'], u'fun': u'saltutil.find_job'}
2019-01-28 11:30:16,975 [salt.minion                                                        :1564][INFO    ][2182] Starting a new job with PID 2182
2019-01-28 11:30:17,020 [salt.utils.lazy                                                    :100 ][DEBUG   ][2182] LazyLoaded saltutil.find_job
2019-01-28 11:30:17,023 [salt.utils.lazy                                                    :100 ][DEBUG   ][2182] LazyLoaded direct_call.execute
2019-01-28 11:30:17,040 [salt.minion                                                        :755 ][DEBUG   ][2182] Minion return retry timer set to 9 seconds (randomized)
2019-01-28 11:30:17,040 [salt.minion                                                        :1863][INFO    ][2182] Returning information for job: 20190128113016876181
2019-01-28 11:30:17,041 [salt.transport.zeromq                                              :128 ][DEBUG   ][2182] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/minion', u'minion_1', u'tcp://xxx.xx.xxx.xx:4506', u'aes')
2019-01-28 11:30:17,042 [salt.crypt                                                         :463 ][DEBUG   ][2182] Initializing new AsyncAuth for (u'/etc/salt/pki/minion', u'minion_1', u'tcp://xxx.xx.xxx.xx:4506')
2019-01-28 11:30:17,044 [salt.transport.zeromq                                              :194 ][DEBUG   ][2182] Connecting the Minion to the Master URI (for the return server): tcp://xxx.xx.xxx.xx:4506
2019-01-28 11:30:17,057 [salt.transport.zeromq                                              :1029][DEBUG   ][2182] Trying to connect to: tcp://xxx.xx.xxx.xx:4506
2019-01-28 11:30:17,095 [salt.minion                                                        :1711][DEBUG   ][2182] minion return: {u'fun_args': [u'20190128113011780024'], u'jid': u'20190128113016876181', u'return': {'tgt_type': 'glob', 'jid': '20190128113011780024', 'tgt': 'minion_1', 'pid': 1888, 'ret': '', 'user': 'root', 'arg': ['salt://d1', '/tmp'], 'fun': 'cp.get_dir'}, u'retcode': 0, u'success': True, u'fun': u'saltutil.find_job'}
2019-01-28 11:31:11,932 [salt.transport.zeromq                                              :1084][DEBUG   ][1888] SaltReqTimeoutError, retrying. (1/3)
2019-01-28 11:32:11,991 [salt.transport.zeromq                                              :1084][DEBUG   ][1888] SaltReqTimeoutError, retrying. (2/3)
2019-01-28 11:33:12,050 [salt.transport.zeromq                                              :1084][DEBUG   ][1888] SaltReqTimeoutError, retrying. (3/3)
2019-01-28 11:34:12,111 [salt.transport.zeromq                                              :1054][DEBUG   ][1888] Re-init ZMQ socket: Message timed out
2019-01-28 11:34:12,115 [salt.transport.zeromq                                              :1029][DEBUG   ][1888] Trying to connect to: tcp://xxx.xx.xxx.xx:4506
2019-01-28 11:34:12,131 [salt.minion                                                        :1667][WARNING ][1888] The minion function caused an exception
2019-01-28 11:34:12,135 [salt.utils.event                                                   :321 ][DEBUG   ][1888] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_6a2cb5e835_pub.ipc
2019-01-28 11:34:12,143 [salt.utils.event                                                   :324 ][DEBUG   ][1888] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_6a2cb5e835_pull.ipc
2019-01-28 11:34:12,144 [salt.transport.ipc                                                 :254 ][DEBUG   ][1888] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_6a2cb5e835_pull.ipc
2019-01-28 11:34:12,154 [salt.utils.event                                                   :739 ][DEBUG   ][1888] Sending event: tag = _salt_error; data = {'message': u'The minion function caused an exception', 'args': ('The minion function caused an exception',), u'_stamp': '2019-01-28T03:34:12.153541'}
2019-01-28 11:34:12,161 [salt.minion                                                        :2261][DEBUG   ][12344] Minion of 'xxx.xx.xxx.xx' is handling event tag '_salt_error'
2019-01-28 11:34:12,165 [salt.minion                                                        :2432][DEBUG   ][12344] Forwarding salt error event tag=_salt_error
2019-01-28 11:34:12,177 [salt.transport.zeromq                                              :128 ][DEBUG   ][12344] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/minion', u'minion_1', u'tcp://xxx.xx.xxx.xx:4506', u'aes')
2019-01-28 11:34:12,178 [salt.crypt                                                         :463 ][DEBUG   ][12344] Initializing new AsyncAuth for (u'/etc/salt/pki/minion', u'minion_1', u'tcp://xxx.xx.xxx.xx:4506')
2019-01-28 11:34:12,186 [salt.minion                                                        :755 ][DEBUG   ][1888] Minion return retry timer set to 9 seconds (randomized)
2019-01-28 11:34:12,193 [salt.minion                                                        :1863][INFO    ][1888] Returning information for job: 20190128113011780024
2019-01-28 11:34:12,202 [salt.transport.zeromq                                              :194 ][DEBUG   ][12344] Connecting the Minion to the Master URI (for the return server): tcp://xxx.xx.xxx.xx:4506
2019-01-28 11:34:12,203 [salt.transport.zeromq                                              :128 ][DEBUG   ][1888] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/minion', u'minion_1', u'tcp://xxx.xx.xxx.xx:4506', u'aes')
2019-01-28 11:34:12,205 [salt.transport.zeromq                                              :1029][DEBUG   ][12344] Trying to connect to: tcp://xxx.xx.xxx.xx:4506
2019-01-28 11:34:12,207 [salt.crypt                                                         :463 ][DEBUG   ][1888] Initializing new AsyncAuth for (u'/etc/salt/pki/minion', u'minion_1', u'tcp://xxx.xx.xxx.xx:4506')
2019-01-28 11:34:12,220 [salt.transport.zeromq                                              :194 ][DEBUG   ][1888] Connecting the Minion to the Master URI (for the return server): tcp://xxx.xx.xxx.xx:4506
2019-01-28 11:34:12,228 [salt.transport.zeromq                                              :1029][DEBUG   ][1888] Trying to connect to: tcp://xxx.xx.xxx.xx:4506
2019-01-28 11:34:12,354 [salt.minion                                                        :1711][DEBUG   ][1888] minion return: {u'fun_args': [u'salt://d1', u'/tmp'], u'jid': u'20190128113011780024', u'return': u'The minion function caused an exception: Traceback (most recent call last):\n  File "/home/op/salt_env/lib/python2.7/site-packages/salt/minion.py", line 1607, in _thread_return\n    return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)\n  File "/home/op/salt_env/lib/python2.7/site-packages/salt/executors/direct_call.py", line 12, in execute\n    return func(*args, **kwargs)\n  File "/home/op/salt_env/lib/python2.7/site-packages/salt/modules/cp.py", line 352, in get_dir\n    return _client().get_dir(path, dest, saltenv, gzip)\n  File "/home/op/salt_env/lib/python2.7/site-packages/salt/fileclient.py", line 437, in get_dir\n    for fn_ in self.file_list(saltenv, prefix=path):\n  File "/home/op/salt_env/lib/python2.7/site-packages/salt/fileclient.py", line 1283, in file_list\n    return salt.utils.data.decode(self.channel.send(load)) if six.PY2 \\\n  File "/home/op/salt_env/lib/python2.7/site-packages/salt/utils/asynchronous.py", line 64, in wrap\n    ret = self._block_future(ret)\n  File "/home/op/salt_env/lib/python2.7/site-packages/salt/utils/asynchronous.py", line 74, in _block_future\n    return future.result()\n  File "/home/op/salt_env/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result\n    raise_exc_info(self._exc_info)\n  File "/home/op/salt_env/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run\n    yielded = self.gen.throw(*exc_info)\n  File "/home/op/salt_env/lib/python2.7/site-packages/salt/transport/zeromq.py", line 325, in send\n    ret = yield self._crypted_transfer(load, tries=tries, timeout=timeout, raw=raw)\n  File "/home/op/salt_env/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run\n    value = future.result()\n  File "/home/op/salt_env/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result\n    raise_exc_info(self._exc_info)\n  File "/home/op/salt_env/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run\n    yielded = self.gen.throw(*exc_info)\n  File "/home/op/salt_env/lib/python2.7/site-packages/salt/transport/zeromq.py", line 293, in _crypted_transfer\n    ret = yield _do_transfer()\n  File "/home/op/salt_env/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run\n    value = future.result()\n  File "/home/op/salt_env/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result\n    raise_exc_info(self._exc_info)\n  File "/home/op/salt_env/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run\n    yielded = self.gen.throw(*exc_info)\n  File "/home/op/salt_env/lib/python2.7/site-packages/salt/transport/zeromq.py", line 277, in _do_transfer\n    tries=tries,\n  File "/home/op/salt_env/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run\n    value = future.result()\n  File "/home/op/salt_env/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result\n    raise_exc_info(self._exc_info)\n  File "<string>", line 3, in raise_exc_info\nSaltReqTimeoutError: Message timed out\n', u'success': False, u'fun': u'cp.get_dir', u'out': u'nested'}
2019-01-28 11:35:12,277 [salt.transport.zeromq                                              :1084][DEBUG   ][12344] SaltReqTimeoutError, retrying. (1/3)
2019-01-28 11:36:12,336 [salt.transport.zeromq                                              :1084][DEBUG   ][12344] SaltReqTimeoutError, retrying. (2/3)
2019-01-28 11:37:12,395 [salt.transport.zeromq                                              :1084][DEBUG   ][12344] SaltReqTimeoutError, retrying. (3/3)
2019-01-28 11:38:12,455 [salt.transport.zeromq                                              :1054][DEBUG   ][12344] Re-init ZMQ socket: Message timed out
2019-01-28 11:38:12,456 [salt.transport.zeromq                                              :1029][DEBUG   ][12344] Trying to connect to: tcp://xxx.xx.xxx.xx:4506
2019-01-28 11:38:12,457 [salt.minion                                                        :1401][INFO    ][12344] fire_master failed: master could not be contacted. Request timed out.

(salt_env) [root@minion_1 ~]# salt-minion -V
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.0
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Jan 11 2019, 13:45:53)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.6

System Versions:
           dist: centos 6.9 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-696.el6.x86_64
         system: Linux
        version: CentOS 6.9 Final

**Comment by linuxyn** [comment]
At first, I saw the error of Minion. I also thought that Minion couldn't connect to the master, but I measured it many times. At the same time that Minion gave an error, I manually connected the master and found that there was no problem. Also, it is normal for me to execute other modules, but this module has problems. I have built a total of 4 saltstack environments, and all three can not work properly. They use the same python, dependency packages, and versions of the saltstack. Those who are not working properly report the same error. I remember that the 2017 version of saltstatck I used was still good. Next, I don't know what to do.
The result is that I tested the state of the minion connection master

(salt_env) [root@minion_1 ~]# salt-call test.ping
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Master URI: tcp://xxx.xx.xxx.xx:4506
[DEBUG   ] Connecting to master. Attempt 1 of 1
[DEBUG   ] Master URI: tcp://xxx.xx.xxx.xx:4506
[DEBUG   ] Initializing new AsyncAuth for (u'/etc/salt/pki/minion', u'minion_1', u'tcp://xxx.xx.xxx.xx:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (10153)
[DEBUG   ] Setting zmq_reconnect_ivl to '10153ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/minion', u'minion_1', u'tcp://xxx.xx.xxx.xx:4506', 'clear')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://xxx.xx.xxx.xx:4506
[DEBUG   ] Trying to connect to: tcp://xxx.xx.xxx.xx:4506
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] salt.crypt._get_key_with_evict: Loading private key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
[DEBUG   ] Connecting the Minion to the Master publish port, using the URI: tcp://xxx.xx.xxx.xx:4505
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Determining pillar cache
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/minion', u'minion_1', u'tcp://xxx.xx.xxx.xx:4506', u'aes')
[DEBUG   ] Initializing new AsyncAuth for (u'/etc/salt/pki/minion', u'minion_1', u'tcp://xxx.xx.xxx.xx:4506')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://xxx.xx.xxx.xx:4506
[DEBUG   ] Trying to connect to: tcp://xxx.xx.xxx.xx:4506
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded test.ping
[DEBUG   ] test.ping received for minion 'minion_1'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/minion', u'minion_1', u'tcp://xxx.xx.xxx.xx:4506', u'aes')
[DEBUG   ] Initializing new AsyncAuth for (u'/etc/salt/pki/minion', u'minion_1', u'tcp://xxx.xx.xxx.xx:4506')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://xxx.xx.xxx.xx:4506
[DEBUG   ] Trying to connect to: tcp://xxx.xx.xxx.xx:4506
[DEBUG   ] LazyLoaded nested.output
local:
    True
