### ISSUE TITLE
Exception in minion when using master_type: func

### ISSUE THREAD

**Issue by sidh** [saltstack/salt#51326]
### Description of Issue/Question
When using master_type: func, salt minion spams its log with the following expception:
```
2019-01-25 06:46:46,024 [salt.minion      :2258][DEBUG   ][295912] Minion of '<master_fqdn_omitted>' is handling event tag '__master_failback'
2019-01-25 06:46:46,029 [tornado.application:629 ][ERROR   ][295912] Exception in callback <functools.partial object at 0x7f3e7c33f158>
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/ioloop.py", line 600, in _run_callback
    ret = callback()
  File "/usr/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/tornado/ioloop.py", line 615, in <lambda>
    self.add_future(ret, lambda f: f.result())
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 946, in handle_event
    yield [minion.handle_event(package) for minion in self.minions]
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 789, in callback
    result_list.append(f.result())
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 282, in wrapper
    yielded = next(result)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 2295, in handle_event
    if data['master'] != self.opts['master_list'][0]:
KeyError: u'master_list'
```

### Setup
cat /etc/salt/minion
```
master: get_master.master
master_type: func
```

### Steps to Reproduce Issue
Happens every minute.

### Versions Report
Note: it was tested with 2018.3.3 - same error.
```
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Nov 13 2018, 12:45:42)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.0.4
 
System Versions:
           dist: Ubuntu 14.04 trusty
         locale: UTF-8
        machine: x86_64
        release: 4.9.101-26
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by dwoz** [comment]
@sidh Thanks for reporting the problem. Can you send me an example of your master config? Scrubbed of any sensitive data of course. :)

**Comment by sidh** [comment]
```
timeout: 40
worker_threads: 5
output: nested
log_file: /var/log/salt/master
log_level: debug
jinja_trim_blocks: True
ipv6: True
interface: '::'
failhard: False

master_sign_pubkey: True
master_sign_key_name: master_sign_key

job_cache: False
keep_jobs: 1
ext_job_cache: myreturner

module_dirs:
    - /srv/conf

pillar_roots:
    base:
        - /srv/pillar

include:
    - /srv/pillar/private/ext_pillars

fileserver_backend:
    - roots
    - git_version

file_roots:
    base:
        - /srv/salt
    dev:
        - /srv/salt

gitfs_provider: GitPython
gitfs_env_whitelist:
    - base
    - dev
    - qa
    - load
    - prod
gitfs_remotes:
...
publisher_acl:
...
```

**Comment by sidh** [comment]
The error is likely triggered by python code that we call periodically on minion machine (not inside salt, rough approximation):
```
import salt.client
...
caller = salt.client.Caller()
res = caller.cmd('status.ping_master', caller.opts['master'])
...
```

We use it to verify that minion itself can 'see' current master.

**Comment by morph027** [comment]
Coming here for the same, same reason, we're pinging master from time to time.
