### ISSUE TITLE
The nested outputter fails with a UnicodeDecodeError when changes dare have non ascii characters.

### ISSUE THREAD

**Issue by mat813** [saltstack/salt#51330]
### Setup
Some managed files has a character outside of [\x00-\x7f], and needs to be updated, the diff from the changes contains said character, and the nested outputter fails.

### Steps to Reproduce Issue
```
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 639: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/bin/salt-run", line 11, in <module>
    load_entry_point('salt==2018.3.3', 'console_scripts', 'salt-run')()
  File "/usr/local/lib/python2.7/site-packages/salt/scripts.py", line 422, in salt_run
    client.run()
  File "/usr/local/lib/python2.7/site-packages/salt/cli/run.py", line 40, in run
    ret = runner.run()
  File "/usr/local/lib/python2.7/site-packages/salt/runner.py", line 271, in run
    daemonize=False)
  File "/usr/local/lib/python2.7/site-packages/salt/client/mixins.py", line 485, in _proc_function
    return self.low(fun, low, full_return=False)
  File "/usr/local/lib/python2.7/site-packages/salt/client/mixins.py", line 261, in low
    return self._low(fun, low, print_event=print_event, full_return=full_return)
  File "/usr/local/lib/python2.7/site-packages/salt/client/mixins.py", line 425, in _low
    namespaced_event.fire_event(data, 'ret')
  File "/usr/local/lib/python2.7/site-packages/salt/utils/event.py", line 928, in fire_event
    self.print_func(tag, data)
  File "/usr/local/lib/python2.7/site-packages/salt/client/mixins.py", line 563, in print_async_event
    salt.output.display_output(event_data, outputter, self.opts)
  File "/usr/local/lib/python2.7/site-packages/salt/output/__init__.py", line 96, in display_output
    display_data = try_printout(data, out, opts, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/salt/output/__init__.py", line 43, in try_printout
    printout = get_printout(out, opts)(data, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/salt/output/highstate.py", line 157, in output
    for host, hostdata in six.iteritems(data)
  File "/usr/local/lib/python2.7/site-packages/salt/output/highstate.py", line 236, in _format_host
    schanged, ctext = _format_changes(ret['changes'], orchestration)
  File "/usr/local/lib/python2.7/site-packages/salt/output/highstate.py", line 527, in _format_changes
    ctext = _nested_changes(changes)
  File "/usr/local/lib/python2.7/site-packages/salt/output/highstate.py", line 500, in _nested_changes
    nested_indent=14)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 639: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/bin/salt-run", line 11, in <module>
    load_entry_point('salt==2018.3.3', 'console_scripts', 'salt-run')()
  File "/usr/local/lib/python2.7/site-packages/salt/scripts.py", line 422, in salt_run
    client.run()
  File "/usr/local/lib/python2.7/site-packages/salt/cli/run.py", line 40, in run
    ret = runner.run()
  File "/usr/local/lib/python2.7/site-packages/salt/runner.py", line 271, in run
    daemonize=False)
  File "/usr/local/lib/python2.7/site-packages/salt/client/mixins.py", line 485, in _proc_function
    return self.low(fun, low, full_return=False)
  File "/usr/local/lib/python2.7/site-packages/salt/client/mixins.py", line 261, in low
    return self._low(fun, low, print_event=print_event, full_return=full_return)
  File "/usr/local/lib/python2.7/site-packages/salt/client/mixins.py", line 425, in _low
    namespaced_event.fire_event(data, 'ret')
  File "/usr/local/lib/python2.7/site-packages/salt/utils/event.py", line 928, in fire_event
    self.print_func(tag, data)
  File "/usr/local/lib/python2.7/site-packages/salt/client/mixins.py", line 563, in print_async_event
    salt.output.display_output(event_data, outputter, self.opts)
  File "/usr/local/lib/python2.7/site-packages/salt/output/__init__.py", line 96, in display_output
    display_data = try_printout(data, out, opts, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/salt/output/__init__.py", line 43, in try_printout
    printout = get_printout(out, opts)(data, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/salt/output/highstate.py", line 157, in output
    for host, hostdata in six.iteritems(data)
  File "/usr/local/lib/python2.7/site-packages/salt/output/highstate.py", line 236, in _format_host
    schanged, ctext = _format_changes(ret['changes'], orchestration)
  File "/usr/local/lib/python2.7/site-packages/salt/output/highstate.py", line 527, in _format_changes
    ctext = _nested_changes(changes)
  File "/usr/local/lib/python2.7/site-packages/salt/output/highstate.py", line 500, in _nested_changes
    nested_indent=14)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 639: ordinal not in range(128)
```

### Versions Report
```
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.27.4
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.27.2
         Python: 2.7.15 (default, May 11 2018, 15:23:13)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.3

System Versions:
           dist:
         locale: UTF-8
        machine: amd64
        release: 11.2-RELEASE-p5
         system: FreeBSD
        version: Not Installed
```

**Comment by mat813** [comment]
I can provide a yaml output of what salt was failing to output with the default nested output. (but privately, it contains sensitive information.)

**Comment by dwoz** [comment]
@mat813 Are you able to scrub the file of the sensitive info and post it here? If not, you can send it to me dwozniak `@` saltstack.com.

**Comment by mat813** [comment]
I sent it to you via email.
