### ISSUE TITLE
Salt Napalm junos.ping errors

### ISSUE THREAD

**Issue by juthewiz** [saltstack/salt#51357]
I am able to run certain modules. but for some reason junos.ping and state.apply (#51355 ) are giving me issues. please see the debug below. i really dont see anything bad besides the bottom half of this. does anyone have any insight?

```
sudo salt sj1e2 junos.ping "10.255.255.6" count=2 -l debug

[DEBUG ] Reading configuration from /etc/salt/master

[DEBUG ] Using cached minion ID from /etc/salt/minion_id: **************

[DEBUG ] Missing configuration file: /home/julius/.saltrc

[DEBUG ] Configuration file path: /etc/salt/master

[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.

[DEBUG ] Reading configuration from /etc/salt/master

[DEBUG ] Using cached minion ID from /etc/salt/minion_id: ***************

[DEBUG ] Missing configuration file: /home/julius/.saltrc

[DEBUG ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc

[DEBUG ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc

[DEBUG ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/master', u'*****************************master', u'tcp://127.0.0.1:4506', u'clear')

[DEBUG ] Connecting the Minion to the Master URI (for the return server): tcp://127.0.0.1:4506

[DEBUG ] Trying to connect to: tcp://127.0.0.1:4506

[DEBUG ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc

[DEBUG ] LazyLoaded local_cache.get_load

[DEBUG ] Reading minion list from /var/cache/salt/master/jobs/b6/1e423215539192fc2cbb2a5c71b2befe94131def163c1d409863c65ff2ce2e/.minions.p

[DEBUG ] get_iter_returns for jid 20190126195925478362 sent to set(['sj1e2']) will timeout at 19:59:30.487877

[DEBUG ] jid 20190126195925478362 return from sj1e2

[DEBUG ] return event: {u'sj1e2': {u'jid': u'20190126195925478362', u'ret': u'The minion function caused an exception: Traceback (most recent call last):\n File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1607, in _thread_return\n return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)\n File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 12, in execute\n return func(*args, **kwargs)\n File "/usr/lib/python2.7/dist-packages/salt/modules/junos.py", line 560, in ping\n conn = __proxy__[\'junos.conn\']()\n File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1155, in __getitem__\n func = super(LazyLoader, self).__getitem__(item)\n File "/usr/lib/python2.7/dist-packages/salt/utils/lazy.py", line 106, in __getitem__\n return self._dict[key]\nKeyError: u\'junos.conn\'\n', u'out': u'nested'}}

[DEBUG ] LazyLoaded nested.output

sj1e2:

The minion function caused an exception: Traceback (most recent call last):

File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1607, in _thread_return

return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)

File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 12, in execute

return func(*args, **kwargs)

File "/usr/lib/python2.7/dist-packages/salt/modules/junos.py", line 560, in ping

conn = __proxy__['junos.conn']()

File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1155, in __getitem__

func = super(LazyLoader, self).__getitem__(item)

File "/usr/lib/python2.7/dist-packages/salt/utils/lazy.py", line 106, in __getitem__

return self._dict[key]

KeyError: u'junos.conn'

[DEBUG ] jid 20190126195925478362 found all minions set([u'sj1e2'])
```

 master
```
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: 0.3.8
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: ISO-8859-1
        machine: x86_64
        release: 4.4.0-124-generic
         system: Linux
        version: Ubuntu 16.04 xenial```

**Comment by Ch3LL** [comment]
ping @saltstack/team-network any ideas here?

**Comment by waynew** [comment]
Anyone know where I can get access to one of these devices so I can try and repro? 😝

**Comment by juthewiz** [comment]
@wasabi222 i am using the napalm proxy with the junos driver 
```

proxy:
 proxytype: napalm
 driver: junos
 host: *.*.*.*
 username: SALT
 password: ************
 port: 830


```

**Comment by juthewiz** [comment]
this can be closed
