### ISSUE TITLE
Problem starting salt with extension_modules

### ISSUE THREAD

**Issue by misch42** [saltstack/salt#51395]
### Problem starting salt with extension_modules

I have problems starting the salt-master with extension_modules set. I have ubuntu bionic and installed python3 with pip3.

### Setup
enable additional modules that were installed by pip3 in /etc/salt/master
extension_modules: /usr/lib/python3/dist-packages/salt

### Steps to Reproduce Issue
Installation of salt according to the docs. Install additional modules with pip3.
starting salt-master with systemctl start salt-master fails:

2019-01-29 21:03:29,864 [salt.log.setup   :1165][ERROR   ][1105] An un-handled exception was caught by salt's global exception handler:
ModuleNotFoundError: No module named 'http.client'; 'http' is not a package
Traceback (most recent call last):
  File "/usr/bin/salt-master", line 22, in <module>
    salt_master()
  File "/usr/lib/python3/dist-packages/salt/scripts.py", line 97, in salt_master
    master.start()
  File "/usr/lib/python3/dist-packages/salt/cli/daemons.py", line 211, in start
    super(Master, self).start()
  File "/usr/lib/python3/dist-packages/salt/utils/parsers.py", line 1044, in start
    self.prepare()
  File "/usr/lib/python3/dist-packages/salt/cli/daemons.py", line 191, in prepare
    import salt.master
  File "/usr/lib/python3/dist-packages/salt/master.py", line 35, in <module>
    import salt.client.ssh.client
  File "/usr/lib/python3/dist-packages/salt/client/ssh/__init__.py", line 34, in <module>
    import salt.minion
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 81, in <module>
    import salt.pillar
  File "/usr/lib/python3/dist-packages/salt/pillar/__init__.py", line 20, in <module>
    import salt.fileclient
  File "/usr/lib/python3/dist-packages/salt/fileclient.py", line 15, in <module>
    from tornado.httputil import parse_response_start_line, HTTPHeaders, HTTPInputError
  File "/usr/lib/python3/dist-packages/tornado/httputil.py", line 39, in <module>
    import http.cookies as Cookie
  File "/usr/lib/python3/dist-packages/salt/utils/http.py", line 60, in <module>
    import salt.ext.six.moves.http_client
  File "/usr/lib/python3/dist-packages/salt/ext/six.py", line 210, in load_module
    mod = mod._resolve()
  File "/usr/lib/python3/dist-packages/salt/ext/six.py", line 122, in _resolve
    return _import_module(self.mod)
  File "/usr/lib/python3/dist-packages/salt/ext/six.py", line 89, in _import_module
    __import__(name)
ModuleNotFoundError: No module named 'http.client'; 'http' is not a package

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
# salt --versions-report
Salt Version:
           Salt: 2018.3.3
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.26.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 3.7.2
   pycryptodome: Not Installed
         pygit2: 0.26.2
         Python: 3.6.7 (default, Oct 22 2018, 11:32:17)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-43-generic
         system: Linux
        version: Ubuntu 18.04 bionic

**Comment by dwoz** [comment]
@misch42 The issue is caused by pointing `extension_modules` at your system's `salt` location. If you have a custom module it usually goes somewhere under `file_roots` like `/srv/salt/ext_mods`.

**Comment by misch42** [comment]
it seems to be a problem with python3. With python2 everything works as documented.
