### ISSUE TITLE
 sysbench -- AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by brianthelion** [saltstack/salt#51396]
### Description of Issue/Question
Identical to https://github.com/saltstack/salt/issues/6175

### Setup
Vanilla master/minion installs from `bootstrap-salt.sh` followed by `salt "*" pkg.install sysbench`.

### Steps to Reproduce Issue
```
$ sudo salt "*" sysbench.cpu
tx2:
   <SUCCESS>
lore:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1607, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/sysbench.py", line 83, in cpu
        ret_val[key] = _parser(result)
      File "/usr/lib/python2.7/dist-packages/salt/modules/sysbench.py", line 40, in _parser
        total_execution = re.search(_total_execution, result).group(1)
    AttributeError: 'NoneType' object has no attribute 'group'
skull-canyon:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1607, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/sysbench.py", line 83, in cpu
        ret_val[key] = _parser(result)
      File "/usr/lib/python2.7/dist-packages/salt/modules/sysbench.py", line 40, in _parser
        total_execution = re.search(_total_execution, result).group(1)
    AttributeError: 'NoneType' object has no attribute 'group'
mulder:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1607, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/sysbench.py", line 83, in cpu
        ret_val[key] = _parser(result)
      File "/usr/lib/python2.7/dist-packages/salt/modules/sysbench.py", line 40, in _parser
        total_execution = re.search(_total_execution, result).group(1)
    AttributeError: 'NoneType' object has no attribute 'group'
upsquared:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1607, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/sysbench.py", line 83, in cpu
        ret_val[key] = _parser(result)
      File "/usr/lib/python2.7/dist-packages/salt/modules/sysbench.py", line 40, in _parser
        total_execution = re.search(_total_execution, result).group(1)
    AttributeError: 'NoneType' object has no attribute 'group'
hadron1:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1607, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/sysbench.py", line 83, in cpu
        ret_val[key] = _parser(result)
      File "/usr/lib/python2.7/dist-packages/salt/modules/sysbench.py", line 40, in _parser
        total_execution = re.search(_total_execution, result).group(1)
    AttributeError: 'NoneType' object has no attribute 'group'
raspberrypi:
    <SUCCESS>

$ sudo salt "*" cmd.run "sysbench --version"
lore:
    sysbench 1.0.11
skull-canyon:
    sysbench 1.0.11
mulder:
    sysbench 1.0.11
upsquared:
    sysbench 1.0.11
hadron1:
    sysbench 1.0.11
tx2:
    sysbench 0.4.12
raspberrypi:
    sysbench 0.4.12
```

### Versions Report
Vanilla Oxygen across the board. Only difference is the sysbench version, which is distro dependent.

```
$ sudo salt "*" cmd.run "lsb_release -d"
mulder:
    Description:	Ubuntu 18.04.1 LTS
lore:
    Description:	Ubuntu 18.04.1 LTS
skull-canyon:
    Description:	Ubuntu 18.04.1 LTS
upsquared:
    Description:	Ubuntu 18.04.1 LTS
hadron1:
    Description:	Ubuntu 18.04.1 LTS
tx2:
    Description:	Ubuntu 16.04.5 LTS
raspberrypi:
    Description:	Raspbian GNU/Linux 9.6 (stretch)
```

**Comment by Arabus** [comment]
It appears the output of the sysbench tool changed in the "newer" versions of sysbench and thus the regex here: https://github.com/saltstack/salt/blob/develop/salt/modules/sysbench.py#L32 fails to parse anything, which will results in an invalid parameter access here: https://github.com/saltstack/salt/blob/develop/salt/modules/sysbench.py#L40

**Comment by myrahaubrich** [comment]
I know this is closed. Only FYI for someone want to quickly fix it yourself, run sysbench in the command line on your OS then fix the regex to match it. Eg with sysbench version 1.0.17,
``` 
    _total_execution = re.compile(r"total number of events:\s*(\d*.\d*s?)")
    _min_response_time = re.compile(r"min:\s*(\d*.\d*)")
    _max_response_time = re.compile(r"max:\s*(\d*.\d*)")
    _avg_response_time = re.compile(r"avg:\s*(\d*.\d*)")
    _per_response_time = re.compile(r"95 percentile:\s*(\d*.\d*)")
```
