### ISSUE TITLE
Fix this error please.

### ISSUE THREAD

**Issue by zhaiweiwei** [saltstack/salt#51446]
Python Version: 3.6.6
Salt Version: 2018.3.3
```
>>> import salt.client
>>> local = salt.client.LocalClient()
>>> local.cmd('*', 'test.fib', [10])
/usr/local/python3/lib/python3.6/site-packages/salt/transport/ipc.py:280: DeprecationWarning: encoding is deprecated, Use raw=False instead.
  self.unpacker = msgpack.Unpacker(encoding=encoding)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/python3/lib/python3.6/site-packages/salt/client/__init__.py", line 766, in cmd
    **kwargs):
  File "/usr/local/python3/lib/python3.6/site-packages/salt/client/__init__.py", line 1641, in get_cli_event_returns
    **kwargs
  File "/usr/local/python3/lib/python3.6/site-packages/salt/client/__init__.py", line 1209, in get_iter_returns
    for raw in ret_iter:
  File "/usr/local/python3/lib/python3.6/site-packages/salt/client/__init__.py", line 1134, in get_returns_no_block
    no_block=True, auto_reconnect=self.auto_reconnect)
  File "/usr/local/python3/lib/python3.6/site-packages/salt/utils/event.py", line 654, in get_event
    ret = self._get_event(wait, tag, match_func, no_block)
  File "/usr/local/python3/lib/python3.6/site-packages/salt/utils/event.py", line 553, in _get_event
    raw = self.subscriber.read_sync(timeout=wait)
  File "/usr/local/python3/lib/python3.6/site-packages/salt/transport/ipc.py", line 706, in read_sync
    return ret_future.result()
  File "/usr/local/python3/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/python3/lib/python3.6/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/usr/local/python3/lib/python3.6/site-packages/salt/transport/ipc.py", line 682, in _read_sync
    raise exc_to_raise  # pylint: disable=E0702
  File "/usr/local/python3/lib/python3.6/site-packages/salt/transport/ipc.py", line 656, in _read_sync
    ret = framed_msg['body']
TypeError: 'int' object is not subscriptable
```

**Comment by garethgreenaway** [comment]
@zhaiweiwei Thanks for the report.  Unfortunately I haven't been able to reproduce this issue.  Are you able to provide some more information, particularly information from `salt --versions-report`.  Thanks!

**Comment by JackTheMico** [comment]
meeting the same error right now, here is my detail salt informations:
           Salt: 2015.5.10
         Python: 2.6.6 (r266:84292, Jun 20 2019, 14:14:55)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: 0.3.4
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: Not Installed

I'm using python client library running something like this:
```python
mycli.cmd("10.25.193.7", "file.file_exists", [/wmcapp/salt-test/tset_minion.py",])
```
and met the same error:
ret = framed_msg['body']
TypeError: 'int' object is not subscriptable
