### ISSUE TITLE
tomcat.ls fails with UnicodeDecodeError: 'ascii' codec can't decode byte

### ISSUE THREAD

**Issue by cavepopo** [saltstack/salt#51448]
### Description of Issue/Question
When using the tomcat.ls function it cannot list tomcat context.
It only happens on some tomcat not all, and I could not spot the difference causing the crash. 

### Versions Report

**Master**:
```
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: 0.27.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.27.3
         Python: 2.7.13 (default, Sep 26 2018, 18:42:22)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.6 
         locale: UTF-8
        machine: x86_64
        release: 4.15.18-9-pve
         system: Linux
        version: debian 9.6 
```
**And minion :** 
```
 Version:
               Salt: 2018.3.2
     
    Dependency Versions:
               cffi: 0.8.6
           cherrypy: Not Installed
           dateutil: 2.2
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.9.4
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.2
       mysql-python: 1.2.3
          pycparser: 2.10
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.9 (default, Sep 25 2018, 20:42:16)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.4.0
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5
     
    System Versions:
               dist: debian 8.11 
             locale: ascii
            machine: x86_64
            release: 3.16.0-7-amd64
             system: Linux
            version: debian 8.11
```

Complete trace : 
```
root@salt [~]: salt "client-vm" tomcat.ls
client-vm:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1606, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/tomcat.py", line 338, in ls
        data = _wget('list', '', url, timeout=timeout)
      File "/usr/lib/python2.7/dist-packages/salt/modules/tomcat.py", line 258, in _wget
        if not ret['msg'][0].startswith('OK'):
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 22: ordinal not in range(128)
```

**Comment by cavepopo** [comment]
I worked around this issue by setting `LANGUAGE=en_US:en` in `/etc/profile` but I guess it'd be better for the future if the strings were encoded in unicode or something like that.
