### ISSUE TITLE
LocalClient in reactor runner sometimes throws DummyFuture does not support blocking for results

### ISSUE THREAD

**Issue by markuskramerIgitt** [saltstack/salt#51457]
### Description of Issue/Question

I use a runner to react to an event. 
From the event data, I extract the minion that send the event and use a local client to issue a command on that minion.

This sometimes work, and sometimes throws the exception: `DummyFuture does not support blocking for results`.

The [local client documentation](https://docs.saltstack.com/en/latest/ref/clients/#salt-s-client-interfaces) notes that an IOLoop can create issues. 

Is it allowed to use a local client in a runner that reacts to an event?

Would cmd_async(minion, 'saltutil.sync_modules') resolve the issue?

in minion_start_reactor.sls: 
```
minion_start_reaction:
  runner.minion_start_runner.main:
    - arg:
      - {{ data }}
```

In minion_start_runner.py: 
``` 
import salt.client
minion = event_data[0]['id']
local = salt.client.LocalClient()
localreturn = local.cmd(minion, 'saltutil.sync_modules')
```

Is  https://github.com/saltstack/salt/issues/29616 related?

**Comment by markuskramerIgitt** [comment]
The Traceback

```
Traceback (most recent call last):
  File \"/srv/salt/modules/runners/minion_start_runner.py\", line 61, in main
    function_sync_modules(minion)
  File \"/srv/salt/modules/runners/minion_start_runner.py\", line 15, in function_sync_modules
    salt_return = salt_handle.cmd(minion, 'saltutil.sync_modules')
  File \"/usr/lib/python2.7/dist-packages/salt/client/__init__.py\", line 766, in cmd
    **kwargs):
  File \"/usr/lib/python2.7/dist-packages/salt/client/__init__.py\", line 1634, in get_cli_event_returns
    **kwargs
  File \"/usr/lib/python2.7/dist-packages/salt/client/__init__.py\", line 1209, in get_iter_returns
    for raw in ret_iter:
  File \"/usr/lib/python2.7/dist-packages/salt/client/__init__.py\", line 1134, in get_returns_no_block
    no_block=True, auto_reconnect=self.auto_reconnect)
  File \"/usr/lib/python2.7/dist-packages/salt/utils/event.py\", line 649, in get_event
    ret = self._get_event(wait, tag, match_func, no_block)
  File \"/usr/lib/python2.7/dist-packages/salt/utils/event.py\", line 548, in _get_event
    raw = self.subscriber.read_sync(timeout=wait)
  File \"/usr/lib/python2.7/dist-packages/salt/transport/ipc.py\", line 706, in read_sync
    return ret_future.result()
  File \"/usr/lib/python2.7/dist-packages/tornado/concurrent.py\", line 216, in result
    self._check_done()
  File \"/usr/lib/python2.7/dist-packages/tornado/concurrent.py\", line 294, in _check_done
    raise Exception(\"DummyFuture does not support blocking for results\")
Exception: DummyFuture does not support blocking for results

```
Salt Version

```
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Sep 25 2018, 20:42:16)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.11
         locale: UTF-8
        machine: x86_64
        release: 3.16.0-6-amd64
         system: Linux
        version: debian 8.11

```

**Comment by dwoz** [comment]
@saltstack/team-core Does anyone have a good answer for this?

**Comment by markuskramerIgitt** [comment]
At the same time file `/var/log/salt/master` contains

```
2019-02-04 07:27:50,085 [tornado.application:124 ][ERROR   ][3206] Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.7/dist-packages/salt/transport/ipc.py", line 682, in _read_sync
    raise exc_to_raise  # pylint: disable=E0702
StreamClosedError

```

**Comment by markuskramerIgitt** [comment]
cmd_async(minion, 'saltutil.sync_modules') resolved the issue.

I also guess that the server was overloaded at the time.
