### ISSUE TITLE
grains.filter_by list broken?

### ISSUE THREAD

**Issue by johnnybubonic** [saltstack/salt#51478]
### Description of Issue/Question
Per [the docs](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.grains.html#salt.modules.grains.filter_by), `grains.filter_by`'s `grain` parameter supposedly accepts a list:

> Changed in version 2016.11.0: The grain value could be a list. The function will return the lookup_dict value for a first found item in the list matching one of the lookup_dict keys.

However, this:

```
{% set os_family_map = salt['grains.filter_by'](
{
    'CentOS Linux-7': {
        'pkg': 'nmap-ncat',
    },
    'CentOS-6': {
        'pkg': 'nc',
    },
    'Red Hat Enterprise Linux Server-7': {
        'pkg': 'nmap-ncat',
    },
    'Arch Linux': {
        'pkg': 'gnu-netcat',
    },
    'default': {}
},
grain="osfinger,os",
merge=salt['pillar.get']('netcat:lookup')) %}
```
does not work, as it returns blank and defaults to the (incorrect, for those keys) default values. This can be shown at the commandline:

```Bash
salt -L 'arch,centos6_32' grains.filter_by '{ CentOS Linux-7: { pkg: nmap-ncat }, CentOS-6: { pkg: nc }, Red Hat Enterprise Linux Server-7: {pkg: nmap-ncat }, Arch Linux: { pkg: gnu-netcat }, default: {} }' grain=osfinger,os
jid: 20190202122041160200
centos6_32:
    ----------
arch:
    ----------
```
Yet:
**salt -L 'arch,centos6_32' grains.get osfinger:**
```YAML
(...)
arch:
centos6_32:
    CentOS-6
```
**salt -L 'arch,centos6_32' grains.get os:**
```YAML
centos6_32:
    CentOS
arch:
    Arch
```

I've tried multiple variations on the list syntax.

- `grain1,grain2`: Nothing returns.
- `[grain1,grain2]`: The following error is returned:
```Python
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1607, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/lib/python2.7/site-packages/salt/modules/grains.py", line 600, in filter_by
        base=base)
      File "/usr/lib/python2.7/site-packages/salt/utils/data.py", line 403, in filter_by
        val = traverse_dict_and_list(traverse, lookup, [])
      File "/usr/lib/python2.7/site-packages/salt/utils/data.py", line 475, in traverse_dict_and_list
        for each in key.split(delimiter):
    AttributeError: 'list' object has no attribute 'split'
```
- `["grain1","grain2"]`: Same as `[grain1,grain2]`.
- `["grain1,grain2"]`: Same as `[grain1,grain2]`.
- `grain1:grain2`: (As expected, as this is reserverd for dicts, but worth a shot because of the referenced error line) Nothing returns.
- `[grain1:grain2]`: Nothing returns.

etc.

It happens on python 3.4 as well:
```Python
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python3.4/site-packages/salt/minion.py", line 1607, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/python3.4/site-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/lib/python3.4/site-packages/salt/modules/grains.py", line 600, in filter_by
        base=base)
      File "/usr/lib/python3.4/site-packages/salt/utils/data.py", line 403, in filter_by
        val = traverse_dict_and_list(traverse, lookup, [])
      File "/usr/lib/python3.4/site-packages/salt/utils/data.py", line 475, in traverse_dict_and_list
        for each in key.split(delimiter):
    AttributeError: 'list' object has no attribute 'split'
```

### Versions Report
Happening on all my minions. Master and all minions are on 2018.3.3, mix of python 3.4 and 2.7.

**Comment by Ch3LL** [comment]
looks like i'm able to replicate this. glancing at the code it seems we might need to loop through the list before making the call to `traverse_dict_and_list`.

**Comment by johnnybubonic** [comment]
keep open

**Comment by Ch3LL** [comment]
nope, we changed our settings with stalebot to not close issues with bug/feature labels so this should not go stale again.

**Comment by nf-brentsaner** [comment]
This still happens on 3007.2.
