### ISSUE TITLE
UnicodeEncodeError when apply states from master but not minion

### ISSUE THREAD

**Issue by barkingfoodog** [saltstack/salt#51496]
### Description of Issue/Question

When running state.apply from the master, I get this:
```
          ID: Suran VCS_localizable_CORE_RES_1
    Function: file.replace
        Name: /Users/Shared/Jenkins/Applications/Omnis/master/Suran VCS.app/Contents/Resources/English.lproj/Localizable.strings
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/opt/salt/lib/python3.5/site-packages/salt/state.py", line 1913, in call
                  **cdata['kwargs'])
                File "/opt/salt/lib/python3.5/site-packages/salt/loader.py", line 1898, in wrapper
                  return f(*args, **kwargs)
                File "/opt/salt/lib/python3.5/site-packages/salt/states/file.py", line 4301, in replace
                  backslash_literal=backslash_literal)
                File "/opt/salt/lib/python3.5/site-packages/salt/modules/file.py", line 2341, in replace
                  w_file.write(salt.utils.stringutils.to_str(result))
              UnicodeEncodeError: 'ascii' codec can't encode character '\xa9' in position 14052: ordinal not in range(128)
     Started: 15:34:39.314528
    Duration: 1120.305 ms
     Changes:
```
But, when I run `salt-call state.apply` from the minion, the state applies properly:
```
          ID: Suran VCS_localizable_CORE_RES_1
    Function: file.replace
        Name: /Users/Shared/Jenkins/Applications/Omnis/master/Suran VCS.app/Contents/Resources/English.lproj/Localizable.strings
      Result: True
     Comment: Changes were made
     Started: 15:38:21.728764
    Duration: 253.199 ms
     Changes:
              ----------
              diff:
                  ---
                  +++
                  @@ -1,5 +1,5 @@
                   {
                  -"CORE_RES_1" = "Omnis Studio";
                  +"CORE_RES_1" = "Suran VCS";
                   "CORE_RES_2" = "Version 8.1.6";
                   "CORE_RES_3" = "Omnis Studio $ $";
                   "CORE_RES_4" = "";
```

### Setup
```
Suran VCS_localizable_CORE_RES_1:
  file.replace:
    - name: /Users/Shared/Jenkins/Applications/Omnis/master/Suran VCS.app/Contents/Resources/English.lproj/Localizable.strings
    - pattern: |
        "CORE_RES_1" = ".*";
    - repl: |
        "CORE_RES_1" = "Suran VCS";
    - require:
      - file: /Users/Shared/Jenkins/Applications/Omnis/master/Suran VCS.app
```

[Sample Localizable.string file](
https://developer.suran.com/Localizable.strings.tgz)

### Versions Report
Minion:
```
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: 1.11.2
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.7
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (default, Nov  8 2018, 15:57:22)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.2
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 15.6.0
         system: Darwin
        version: 10.11.6 x86_64
```

Master:
```
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 3.5.2 (default, Nov 12 2018, 13:43:14)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 3.13.0-57-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

I'm at a loss to explain why salt behaves differently based on who initiates the state apply.

**Comment by Ch3LL** [comment]
i have not been able to replicate this.

i've tried on 3 hosts. One on python2 centos7, python3.7 arch, python3.5 ubuntu16 and all of them run the state from either salt-call or salt. If you change that file path to not include a space do you still see the same stack trace?

**Comment by barkingfoodog** [comment]
@Ch3LL thank you for digging into this. The problem persists if you use a path without a space.

I set this up from an Ubuntu 16 host with an Ubuntu 16 minion and it works. The problem seems to be with a macOS minion. I tried both macOS 10.11 and 10.14 and get the error.

FWIW I also tried Windows 10 and that works properly when run from master or minion.

**Comment by barkingfoodog** [comment]
@Ch3LL were you able to reproduce this with a macOS minion? Is there anything else I can provide to help track this down?

**Comment by Ch3LL** [comment]
i'm still not able to replicate on mac. ping @weswhet any chance you can see if you can replicate this?

**Comment by barkingfoodog** [comment]
Just in case anyone else is running into this, I was able to workaround it by replacing `file.replace` with `sed` in a `cmd.run`:
```yaml
Suran VCS_localizable_CORE_RES_1
  cmd.run:
    - name: sed -i '' 's/"CORE_RES_1" = ".*";/"CORE_RES_1" = "Suran VCS";/' "/Users/Shared/Jenkins/Applications/Omnis/master/Suran VCS.app/Contents/Resources/English.lproj/Localizable.strings"
    - require:
      - file: {{ application_root }}
    - unless: grep '"CORE_RES_1" = "Suran VCS";' "/Users/Shared/Jenkins/Applications/Omnis/master/Suran VCS.app/Contents/Resources/English.lproj/Localizable.strings"
```

But, I would much rather use `file.replace` for its clarity and cross-platform support.

**Comment by weswhet** [comment]
Hmm, I only have a masterless setup so I can't reproduce this.

**Comment by boltronics** [comment]
I just hit what looks like this issue on a Debian Stretch box when I upgraded to the Python 3 `2019.2.2+ds-1` packages from http://repo.saltstack.com/py3/debian/9/amd64/2019.2 - except I'm getting it from the minion as well.

```Salt Version:
           Salt: 2019.2.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (default, Sep 27 2018, 17:25:39)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.11 
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.9.0-11-amd64
         system: Linux
        version: debian 9.11 
 
```

```
$ cat /etc/apticron/apticron.conf  | grep -v '#' | cat -s
EMAIL="serveradmin@olddomain.com"

SYSTEM="mysaltmaster.com"

CUSTOM_FROM="serveradmin@olddomain.com"
$ 
```

Here's the relevant snippet from my `apticron.sls` state file:
```
{%-
  for file_name, config in salt['pillar.get']('apticron:config',
                                              {}).items()
%}
{%- for setting, value in config.items() %}

Uncomment {{ setting }} in {{ file_name }}:
  file.uncomment:
    - name: {{ file_name }}
    - regex: '{{ setting }}='
    - char: '# '
    - backup: ''
    - require:
      - pkg: apticron

Set {{ setting }} in {{ file_name }}:
  file.replace:
    - name: {{ file_name }}
    - pattern: '^{{ setting }}=".*"$'
    - repl: '{{ setting }}="{{ value }}"'
    - backup: False
    - require:
      - file: Uncomment {{ setting }} in {{ file_name }}

{%- endfor %}
{%- endfor %}
```

Here's my `apticron.sls` pillar data:
```
{%- set id = grains['id'] %}

apt-listchanges:
  config:
    /etc/apt/listchanges.conf:
      email_address: serveradmin@somedomain.com

apticron:
  config:
    /etc/apticron/apticron.conf:
      EMAIL: serveradmin@somedomain.com
      SYSTEM: {{ id }}
      CUSTOM_FROM: serveradmin@somedomain.com
```

The result:
```
$ sudo salt-call state.sls apticron
...
----------
          ID: Uncomment EMAIL in /etc/apticron/apticron.conf
    Function: file.uncomment
        Name: /etc/apticron/apticron.conf
      Result: True
     Comment: Pattern already uncommented
     Started: 12:50:36.237316
    Duration: 6.947 ms
     Changes:   
----------
          ID: Set EMAIL in /etc/apticron/apticron.conf
    Function: file.replace
        Name: /etc/apticron/apticron.conf
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 1933, in call
                  **cdata['kwargs'])
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 1951, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/file.py", line 4535, in replace
                  backslash_literal=backslash_literal)
                File "/usr/lib/python3/dist-packages/salt/modules/file.py", line 2402, in replace
                  w_file.write(salt.utils.stringutils.to_str(result))
              UnicodeEncodeError: 'ascii' codec can't encode character '\u2010' in position 824: ordinal not in range(128)
     Started: 12:50:36.244814
    Duration: 9.006 ms
     Changes:   
----------
          ID: Uncomment CUSTOM_FROM in /etc/apticron/apticron.conf
    Function: file.uncomment
        Name: /etc/apticron/apticron.conf
      Result: False
     Comment: CUSTOM_FROM=: Pattern not found
     Started: 12:50:36.254162
    Duration: 2.592 ms
     Changes:   
----------
          ID: Set CUSTOM_FROM in /etc/apticron/apticron.conf
    Function: file.replace
        Name: /etc/apticron/apticron.conf
      Result: False
     Comment: One or more requisite failed: apticron.Uncomment CUSTOM_FROM in /etc/apticron/apticron.conf
     Started: 12:50:36.257398
    Duration: 0.021 ms
     Changes:   
----------
          ID: Uncomment SYSTEM in /etc/apticron/apticron.conf
    Function: file.uncomment
        Name: /etc/apticron/apticron.conf
      Result: False
     Comment: SYSTEM=: Pattern not found
     Started: 12:50:36.257628
    Duration: 2.455 ms
     Changes:   
----------
          ID: Set SYSTEM in /etc/apticron/apticron.conf
    Function: file.replace
        Name: /etc/apticron/apticron.conf
      Result: False
     Comment: One or more requisite failed: apticron.Uncomment SYSTEM in /etc/apticron/apticron.conf
     Started: 12:50:36.260686
    Duration: 0.021 ms
     Changes:   

Summary for local
-------------
Succeeded: 14
Failed:     5
-------------
Total states run:     19
Total run time:  430.909 ms
```

Why the "Pattern not found" errors in the blocks that follow the initial stack trace?
```
$ cat /etc/apticron/apticron.conf
$
```
Yep - it completely deleted the file! I had to restore from backups.

**Comment by boltronics** [comment]
Unless this was fixed in the last couple of weeks with the release of 2019.2.3 (and I'm assuming not since this wasn't updated), this is still an issue.

**Comment by Ch3LL** [comment]
thanks for the example @boltronics i was able to replicate this on debian 9 with that package. I was not able to replicate it on my laptop though which runs manjaro.

I created a docker container to make it easy to replicate: `docker run -it ch3ll/issues:51496 salt-call --local state.sls test -ldebug` will need to get this fixed up

**Comment by boltronics** [comment]
This still seems to happen using the official 3001 packages and package repositories (`3001+ds-1` running on a Debian Stretch master, `3001+ds-2` on an Ubuntu 16.04.6 minion). 
```
----------
          ID: Uncomment NOTIFY_HOLDS in /etc/apticron/apticron.conf
    Function: file.replace
        Name: /etc/apticron/apticron.conf
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 2154, in call
                  *cdata["args"], **cdata["kwargs"]
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2087, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/file.py", line 5179, in replace
                  backslash_literal=backslash_literal,
                File "/usr/lib/python3/dist-packages/salt/modules/file.py", line 2632, in replace
                  w_file.write(salt.utils.stringutils.to_str(result))
              UnicodeEncodeError: 'ascii' codec can't encode character '\u2010' in position 803: ordinal not in range(128)
     Started: 17:57:02.691087
    Duration: 16.848 ms
     Changes:   
```

As before, this continues to delete the entire contents of anything it tries to modify:
```
$ ls -l /etc/apticron/apticron.conf 
-rw-r--r-- 1 root root 0 Jul 30 17:57 /etc/apticron/apticron.conf
$ 
```

However everything works if executed on the minion. So when bringing up a new host, I've needed to manually SSH into it and run `highstate` locally to get it initially working. I was hoping upgrading to `3001` on `py3` would solve this, but it has not.

Debian master:
```
Salt Version:
           Salt: 3001
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
         Jinja2: 2.9.4
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.6.1
         pygit2: Not Installed
         Python: 3.5.3 (default, Jul  9 2020, 13:00:10)
   python-gnupg: 0.3.9
         PyYAML: 3.12
          PyZMQ: 17.1.2
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9 stretch
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-13-amd64
         system: Linux
        version: Debian GNU/Linux 9 stretch
 
```

Ubuntu minion:
```
Salt Version:
           Salt: 3001
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: 3.4.7
         pygit2: Not Installed
         Python: 3.5.2 (default, Jul 17 2020, 14:04:10)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 17.1.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4
 
System Versions:
           dist: ubuntu 16.04 Xenial Xerus
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-1109-aws
         system: Linux
        version: Ubuntu 16.04 Xenial Xerus
 
```

**Comment by boltronics** [comment]
I needed a better fix for this today, as I was hitting what looked like this issue in other states as well, which didn't even use `file.uncomment`! So looked into it this morning to find the exact conditions that are triggering this issue.

Firstly, the above `file.uncomment` rule appears to be failing because the file contents it is editing are "UTF-8 Unicode text", not "ASCII text".

```
$ file /etc/apticron/apticron.conf
/etc/apticron/apticron.conf: UTF-8 Unicode text
$ 
```

Why is the file UTF-8? It's because of this comment (which I unfortunately stripped out of the above example):
```
#
# From hostname manpage: "Displays  all FQDNs of the machine. This option
# enumerates all configured network addresses on all configured network inter‐
# faces, and translates them to DNS domain names. Addresses that cannot be
# translated (i.e. because they do not have an appro‐ priate  reverse DNS
# entry) are skipped. Note that different addresses may resolve to the same
# name, therefore the output may contain duplicate entries. Do not make any
# assumptions about the order of the output."
#
# ALL_FQDNS="1"
```

That the default text provided by the Debian Stretch `apticron` package. Note the hyphens are `‐` and not `-` (and the second one shouldn't even be there - and was fixed in Buster)! Hence this is a UTF-8 Unicode text file.

When I remove these two characters, the state runs correctly from the salt-master. So amazingly Salt on Python 3 cannot handle UTF-8 text files edits.

The second time I saw this, it was triggered on any Ubuntu host when I would run a specific state that only contained iptables rules in it. I eventually narrowed it down to this section:
```
# Block all packets that are not a SYN packet and don’t belong to an
# established TCP connection.
Block invalid packets:
  iptables.append:
    - table: mangle
    - chain: PREROUTING
    - match: conntrack
    - ctstate: INVALID
    - jump: DROP
    - save: True
```

This comment was copied from a [website](https://javapipe.com/blog/iptables-ddos-protection/), hence it contains a `’` instead of a `'` in "don't", which would trigger the `UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 558: ordinal not in range(128)` error.

Interestingly, only one host was affected by this, and it is the only host that was launched from scratch recently (using Ubuntu's official AWS AMI) and launched with Salt 3001, as opposed to the other hosts on my network that were upgraded from 2019.2.5 on Python 2.7.

This gave me a hint to look at what difference there could be that would cause this, and I realised that `language-pack-en` was installed by Salt itself using `pkg.installed` in other state sls file. I restarted the salt-minion daemon, re-ran the state from the master, and now the minion is able to run the state correctly.

I don't yet know if this was related specifically to `language-pack-en` or some other package, but it seems that Salt installs a package that fixes the issue but requires a restart (or perhaps just the modules be reloaded?) to work properly.

I also don't know if this is related to using Python 3 packages, or a regression in the newer version, as I've never encountered this problem before and I've been using the above state in question since March 2018. The AMI I was testing with has not changed. Fortunately most of my comments are in English so for now I'm just going through all my sls files and making sure the `file` command reports "ASCII text" for everything. Obviously this is a problem for teams that don't just use English.

I don't see any reason why this should be a problem for Salt. If an unsupported character is in a comment, Salt should not care. If an unsupported character is used in a text replacement string or some such, probably Salt should just insert the characters "as is" without trying to decode them - although I suspect that that kind of use case is much less of an issue. In any case, it appears to be a regression.
