### ISSUE TITLE
Issues configuring event_return: smtp on salt-master

### ISSUE THREAD

**Issue by tuxthepenguin84** [saltstack/salt#51585]
### Description of Issue/Question
I want to configure my Salt Master to send jobs to Splunk, however right now before I get access to our internal Splunk server I'm testing by sending emails (to myself). I just want to validate I have the correct config for event returns.

On my salt master I have this config:
event_return: smtp
smtp.from: user@company.com
smtp.to: user@company.com
smtp.host: exch-server
smtp.port: 25

When I restart my salt-master I get this error in the logs:
```
2019-02-11 15:28:44,760 [salt.utils.templates:181 ][ERROR   ][3663] Rendering exception occurred
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 170, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 403, in render_jinja_tmpl
    buf=tmplstr)
SaltRenderError: Jinja variable 'id' is undefined
2019-02-11 15:28:44,761 [salt.utils.event :1232][ERROR   ][3663] Could not store events - returner 'smtp.event_return' raised exception: Jinja variable 'id' is undefined
```

Salt commands and jobs still run correctly and I get the emails, but it generates this on all salt commands I run.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 12 2018, 14:36:49)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-141-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by tuxthepenguin84** [comment]
I was able to duplicate this issue on a clean install of Ubuntu 18.04
```
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-45-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```
As soon as I copied over my file_roots directory structure, replicated my salt-master configuration, and restarted the salt-master, the issue returned.

**Comment by dwoz** [comment]
@techhat Is this a config issue or does it look like a bug?

**Comment by tuxthepenguin84** [comment]
I'll post my full master config tomorrow if that would help, it's very short with only a few changes.

Also one thing to note is the following will change depending on what is being done:
```SaltRenderError: Jinja variable 'id' is undefined```
This will sometimes say:
```SaltRenderError: Jinja variable 'fun' is undefined```

**Comment by tuxthepenguin84** [comment]
My /etc/salt/master file excluding commented sections:
```
keep_jobs: 168
event_return: smtp
smtp.from: user@company.com
smtp.to: user@company.com
smtp.host: server01
smtp.port: 25
file_roots:
  base:
    - /srv/salt
```
