### ISSUE TITLE
Errors using consul sdb

### ISSUE THREAD

**Issue by crux-capacitor** [saltstack/salt#51668]
### Description of Issue/Question

After configuring the consul sdb, I receive the following errors when trying to access values:

```
salt-call sdb.get sdb://consul/key/value
  The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1606, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/lib/python2.7/site-packages/salt/modules/sdb.py", line 28, in get
        return salt.utils.sdb.sdb_get(uri, __opts__, __utils__)
      File "/usr/lib/python2.7/site-packages/salt/utils/sdb.py", line 46, in sdb_get
        return loaded_db[fun](query, profile=profile)
      File "/usr/lib/python2.7/site-packages/salt/sdb/consul.py", line 59, in get
        conn = get_conn(profile)
      File "/usr/lib/python2.7/site-packages/salt/sdb/consul.py", line 76, in get_conn
        return consul.Consul(**params)
    AttributeError: 'module' object has no attribute 'Consul'
```

```
salt-call consul.get key='key/value'
[ERROR   ] No Consul URL found.
local:
    ----------
    message:
        No Consul URL found.
    res:
        False
```

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

Configuration in the minion config file:

```
consul:
  driver: consul
  host: 127.0.0.7
  port: 8500
  scheme: http
  consistency: default
  dc: dc1
```

I have consul installed as an agent and can use it to pull values from consul.

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

1. Set up a consul cluster with some key/value pairs.
2. Set up a salt minion with that above config and install consul as an agent, and verify connection.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Jul 26 2018, 19:59:38)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 4.14.88-88.76.amzn2.x86_64
         system: Linux
        version: Not Installed

**Comment by garethgreenaway** [comment]
@crux-capacitor Thanks for the report.  Do you have the consul python, `python-consul`, library installed on the Salt minion?

**Comment by crux-capacitor** [comment]
@garethgreenaway Hi Gareth. No I don't. I installed it using pip but still am getting the same errors. Here is some output:

Just to prove that consul is returning something:
```
[root@salt-minion ~]# consul kv get test
thisisatest
```

python-consul is installed:
```
[root@salt-minion ~]# pip install python-consul
Requirement already satisfied: python-consul in /usr/lib/python2.7/site-packages
Requirement already satisfied: six>=1.4 in /usr/lib/python2.7/site-packages (from python-consul)
Requirement already satisfied: requests>=2.0 in /usr/lib/python2.7/site-packages (from python-consul)
```

using consul.get:
```
[root@salt-minion ~]# salt-call consul.get key='test'
[ERROR   ] No Consul URL found.
local:
    ----------
    message:
        No Consul URL found.
    res:
        False
```

using sdb.get:
```
[root@salt-minion ~]# salt-call sdb.get sdb://consul/test
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 410, in salt_call
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 212, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/sdb.py", line 28, in get
    return salt.utils.sdb.sdb_get(uri, __opts__, __utils__)
  File "/usr/lib/python2.7/site-packages/salt/utils/sdb.py", line 46, in sdb_get
    return loaded_db[fun](query, profile=profile)
  File "/usr/lib/python2.7/site-packages/salt/sdb/consul.py", line 61, in get
    _, result = conn.kv.get(key)
  File "/usr/lib/python2.7/site-packages/consul/base.py", line 554, in get
    params=params)
  File "/usr/lib/python2.7/site-packages/consul/std.py", line 22, in get
    self.session.get(uri, verify=self.verify, cert=self.cert)))
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 476, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 410, in salt_call
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 212, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/sdb.py", line 28, in get
    return salt.utils.sdb.sdb_get(uri, __opts__, __utils__)
  File "/usr/lib/python2.7/site-packages/salt/utils/sdb.py", line 46, in sdb_get
    return loaded_db[fun](query, profile=profile)
  File "/usr/lib/python2.7/site-packages/salt/sdb/consul.py", line 61, in get
    _, result = conn.kv.get(key)
  File "/usr/lib/python2.7/site-packages/consul/base.py", line 554, in get
    params=params)
  File "/usr/lib/python2.7/site-packages/consul/std.py", line 22, in get
    self.session.get(uri, verify=self.verify, cert=self.cert)))
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 476, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))
```

netstat output showing that the consul port is open:
```
[root@salt-minion ~]# netstat -pant
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 10.120.3.133:8301       0.0.0.0:*               LISTEN      23872/consul
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      2047/rpcbind
tcp        0      0 127.0.0.1:8500          0.0.0.0:*               LISTEN      23872/consul
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      4929/sshd
tcp        0      0 127.0.0.1:8600          0.0.0.0:*               LISTEN      23872/consul
tcp        0      0 0.0.0.0:4505            0.0.0.0:*               LISTEN      9057/python
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      2569/master
tcp        0      0 0.0.0.0:4506            0.0.0.0:*               LISTEN      9064/python
tcp        0      1 10.120.3.133:4505       10.120.3.210:39697      LAST_ACK    -
tcp        0      0 10.120.3.133:8301       10.120.1.86:33806       TIME_WAIT   -
tcp        0      0 10.120.3.133:48275      10.120.2.184:8300       ESTABLISHED 23872/consul
tcp        0      0 10.120.3.133:37481      10.120.3.54:8300        ESTABLISHED 23872/consul
tcp        0      0 10.120.3.133:41808      10.120.1.39:8301        TIME_WAIT   -
tcp        0      0 10.120.3.133:990        10.120.2.131:2049       ESTABLISHED -
tcp        0      0 10.120.3.133:41384      10.120.2.120:3268       ESTABLISHED 6807/sssd_be
tcp        0    232 10.120.3.133:22         10.120.0.77:55365       ESTABLISHED 23371/sshd: ec2-use
tcp        0      0 10.120.3.133:49040      10.120.2.120:389        ESTABLISHED 6807/sssd_be
tcp        0      0 10.120.3.133:39232      10.120.1.192:8301       TIME_WAIT   -
tcp        0      0 10.120.3.133:35710      10.120.1.192:4505       ESTABLISHED 4930/python
tcp6       0      0 :::111                  :::*                    LISTEN      2047/rpcbind
tcp6       0      0 :::22                   :::*                    LISTEN      4929/sshd
```

**Comment by garethgreenaway** [comment]
@crux-capacitor The `consul` execution module is looking for a different configuration option, `url` inside the consul section:
```
consul:
  driver: consul
  host: 127.0.0.7
  port: 8500
  scheme: http
  consistency: default
  dc: dc1
  url: http://127.0.0.1:8500
```

It also looks like you're original configuration might have a typo for the host, should that be 127.0.0.1?  To match the local IP that consul is listening on.

**Comment by crux-capacitor** [comment]
@garethgreenaway You were correct! Fixing the typo and adding the URL option fixed it. With the URL option, I was able to get rid of host, port and scheme.

Thanks very much!
