### ISSUE TITLE
sdb.delete fails with sqlite3.delete KeyError

### ISSUE THREAD

**Issue by hemebond** [saltstack/salt#51722]
Configured an SQLite database to use with SDB. Can `sdb.get` and `sdb.set` entries without issue, but trying to `sdb.delete` entries just throws an error.

### Setup
```
# /etc/salt/master.d/sdb.conf
db9:
  create_table: true
  database: /var/lib/salt/sdb.db
  driver: sqlite3
  table: db9
```

### Steps to Reproduce Issue
```
# salt-run sdb.set 'sdb://db9/test' 'foobar'
True
# salt-run sdb.get 'sdb://db9/test'
foobar
# salt-run sdb.delete 'sdb://db9/test'
Exception occurred in runner sdb.delete: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 387, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/runners/sdb.py", line 57, in delete
    return salt.utils.sdb.sdb_delete(uri, __opts__, __utils__)
  File "/usr/lib/python2.7/dist-packages/salt/utils/sdb.py", line 108, in sdb_delete
    return loaded_db[fun](query, profile=profile)
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1155, in __getitem__
    func = super(LazyLoader, self).__getitem__(item)
  File "/usr/lib/python2.7/dist-packages/salt/utils/lazy.py", line 104, in __getitem__
    raise KeyError(key)
KeyError: u'sqlite3.delete'
```

### Versions Report
```
Salt Version:
           Salt: 2018.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.11
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.3.10
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15+ (default, Feb  3 2019, 13:13:16)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 5.1.1
            ZMQ: 4.3.1
 
System Versions:
           dist: debian buster/sid 
         locale: UTF-8
        machine: x86_64
        release: 4.19.0-2-amd64
         system: Linux
        version: debian buster/sid 
```

**Comment by hemebond** [comment]
Sorry, this is invalid. I was accidentally reading the `develop` version of the documentation. `sqlite3.delete` is not implemented in 2018.3.
