### ISSUE TITLE
salt.states.file.copy force=true on Windows does not clear the Read-Only attribute during removal

### ISSUE THREAD

**Issue by arizvisa** [saltstack/salt#51739]
### Description of Issue/Question
On the windows platform, when using file.copy where the source has a file with a read-only attribute (`attrib +r`), the call to `file.remove` fails with an exception and so the whole state fails.

### Setup
Setup a Windows box, drop a directory with some files that have the readonly attribute set. You can enable the +r attribute via `attrib +r $filename` at the command prompt.

### Steps to Reproduce Issue
Once you have a source directory with the prior mentioned constraints, just use a state with `file.copy` and the `force` parameter set to `true`. After the copy happens, the second time you apply the state you'll get the following exception:

```----------
          ID: Copy harness stage into target path
    Function: file.copy
        Name: R:\harness
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "c:\salt\bin\lib\site-packages\salt\state.py", line 1913, in call
                  **cdata['kwargs'])
                File "c:\salt\bin\lib\site-packages\salt\loader.py", line 1898, in wrapper
                  return f(*args, **kwargs)
                File "c:\salt\bin\lib\site-packages\salt\states\file.py", line 5757, in copy
                  __salt__['file.remove'](name)
                File "c:\salt\bin\lib\site-packages\salt\modules\win_file.py", line 1093, in remove
                  remove(item, force)
                File "c:\salt\bin\lib\site-packages\salt\modules\win_file.py", line 1093, in remove
                  remove(item, force)
                File "c:\salt\bin\lib\site-packages\salt\modules\win_file.py", line 1093, in remove
                  remove(item, force)
                File "c:\salt\bin\lib\site-packages\salt\modules\win_file.py", line 1093, in remove
                  remove(item, force)
                File "c:\salt\bin\lib\site-packages\salt\modules\win_file.py", line 1093, in remove
                  remove(item, force)
                File "c:\salt\bin\lib\site-packages\salt\modules\win_file.py", line 1093, in remove
                  remove(item, force)
                File "c:\salt\bin\lib\site-packages\salt\modules\win_file.py", line 1093, in remove
                  remove(item, force)
                File "c:\salt\bin\lib\site-packages\salt\modules\win_file.py", line 1093, in remove
                  remove(item, force)
                File "c:\salt\bin\lib\site-packages\salt\modules\win_file.py", line 1093, in remove
                  remove(item, force)
                File "c:\salt\bin\lib\site-packages\salt\modules\win_file.py", line 1093, in remove
                  remove(item, force)
                File "c:\salt\bin\lib\site-packages\salt\modules\win_file.py", line 1093, in remove
                  remove(item, force)
                File "c:\salt\bin\lib\site-packages\salt\modules\win_file.py", line 1093, in remove
                  remove(item, force)
                File "c:\salt\bin\lib\site-packages\salt\modules\win_file.py", line 1093, in remove
                  remove(item, force)
                File "c:\salt\bin\lib\site-packages\salt\modules\win_file.py", line 1093, in remove
                  remove(item, force)
                File "c:\salt\bin\lib\site-packages\salt\modules\win_file.py", line 1102, in remove
                  'Could not remove \'{0}\': {1}'.format(path, exc)
              CommandExecutionError: Could not remove 'R:\harness\BugId\.git\modules\modules\cBugId\modules\modules\mFileSystem\modules\modules\mWindowsAPI\objects\pack\pack-f43ecb13511b485fc9417c2aeb795ac9bc24a914.idx': [Error 5] Access is denied: u'R:\\harness\\BugId\\.git\\modules\\modules\\cBugId\\modules\\modules\\mFileSystem\\modules\\modules\\mWindowsAPI\\objects\\pack\\pack-f43ecb13511b485fc9417c2aeb795ac9bc24a914.idx'
```

### Versions Report
```
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)]
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 8
         system: Windows
        version: 8 6.2.9200 SP0 Multiprocessor Free
```

**Comment by arizvisa** [comment]
The issue is that the call to `file.remove` in the `file.copy` state is also not setting the `force` parameter to `true`. It looks like:

```        elif not __opts__['test'] and changed:
            # Remove the destination to prevent problems later
            try:
                __salt__['file.remove'](name)
            except (IOError, OSError):
                return _error(
                    ret,
                    'Failed to delete "{0}" in preparation for '
                    'forced move'.format(name)
                )
```

I'll submit a PR for this one too.

**Comment by Ch3LL** [comment]
thanks for the pr!

**Comment by arizvisa** [comment]
Closing this issue as it appears the PR was merged.
