### ISSUE TITLE
Cannot list installed patches

### ISSUE THREAD

**Issue by amannch** [saltstack/salt#51763]
### Description of Issue/Question

When trying to list installed patches I get the following result:

          ID: test_case
    Function: pkg.patch_installed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1939, in call
                  ret = self.states[cdata['full']](*cdata['args'], **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1941, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/pkg.py", line 2160, in patch_installed
                  targets = _find_advisory_targets(name, advisory_ids, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/pkg.py", line 386, in _find_advisory_targets
                  cur_patches = __salt__['pkg.list_installed_patches'](**kwargs)
              TypeError: list_installed_patches() got an unexpected keyword argument 'refresh'
     Started: 15:39:51.125880
    Duration: 1.699 ms
     Changes:   

Should be:

          ID: test_case
    Function: pkg.patch_installed
      Result: True
     Comment: Advisory patch is not needed or related packages are already installed
     Started: 15:40:22.546790
    Duration: 2434.074 ms
     Changes: 

### Setup

salt-call --local state.apply test_case

/srv/salt/test_case.sls:

test_case:
  pkg.patch_installed:
    - refresh: true
    - advisory_ids:
      - [PLACEHOLDER]

### Possible Cause
pkg.py unpacks all sorts of unwanted  kwargs into the underlying `pkg.list_installed_patches` method (line 386):

`cur_patches = __salt__['pkg.list_installed_patches'](**kwargs)`

in 2018.3 this was:

`cur_patches = __salt__['pkg.list_installed_patches']()`

### Versions Report
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: 1.7.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 11 2017, 10:56:06) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
 
System Versions:
           dist: SuSE 12 x86_64
         locale: UTF-8
        machine: x86_64
        release: 4.12.14-95.6-default
         system: Linux
        version: SUSE Linux Enterprise Server  12 x86_64

**Comment by garethgreenaway** [comment]
@amannch Thanks for the report.  To confirm, are you seeing this on the `develop` branch?  Just making sure as I don't see this on the `2019.2` branch, but I do see it in `develop`.

**Comment by amannch** [comment]
yes, this is the `develop` branch

**Comment by dwoz** [comment]
Fixed by #54954 (merged 2020-05-19) which added `**kwargs` to `pkg.list_installed_patches` in yumpkg and zypperpkg via commit 6b89c648ff7 ("pkg: partially unify public functions signature"). Verified on 3006.x, 3007.x, 3008.x, and master — `def list_installed_patches(**kwargs)` in yumpkg and `def list_installed_patches(root=None, **kwargs)` in zypperpkg, so the `TypeError: unexpected keyword argument 'refresh'` no longer triggers.
