### ISSUE TITLE
Fluorine jinja relative import not working with slsutil.renderer

### ISSUE THREAD

**Issue by Oloremo** [saltstack/salt#51835]
### Description of Issue/Question
New feature of the Fluorine is the relative import paths: https://docs.saltstack.com/en/develop/topics/releases/2019.2.0.html#jinja-include-relative-paths

And looks like they're not working with slsutil.renderer

### Steps to Reproduce Issue
```
$ ls -1 states/tests/map.sls states/tests/import_test.yaml
states/tests/import_test.yaml
states/tests/map.sls
```
cat states/tests/map.sls
```
{% from './import_test.yaml' import test with context %}

{{ test }}

```

cat states/tests/import_test.yaml
```
test:
  key: value
```

salt-call slsutil.renderer salt://tests/map.sls
```
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    load_entry_point('salt-ssh==2019.2.0', 'console_scripts', 'salt-call')()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 431, in salt_call
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 138, in run
    ret = self.call()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 237, in call
    ret['return'] = self.minion.executors[fname](self.opts, data, func, args, kwargs)
  File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/slsutil.py", line 182, in renderer
    **kwargs
  File "/usr/lib/python2.7/site-packages/salt/template.py", line 101, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/usr/lib/python2.7/site-packages/salt/renderers/jinja.py", line 70, in render
    **kws)
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 169, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 441, in render_jinja_tmpl
    trace=tracestr)
salt.exceptions.SaltRenderError: Jinja error: ./import_test.yaml
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 392, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 1, in top-level template code
  File "/usr/lib/python2.7/site-packages/salt/utils/jinja.py", line 171, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: ./import_test.yaml
```

### Versions Report
```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: 1.10.6
          gitdb: 2.0.5
      gitpython: 2.1.11
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
   python-gnupg: 0.4.4
         PyYAML: 3.11
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.2.5

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

**Comment by Oloremo** [comment]
Additionally, I wonder if this feature should work with the constructions like:
1) `{% import './defaults.yaml' as defaults %}`
2) `{% import_yaml './defaults.yaml' as defaults %}`
?

Because documentation gives only a single and very specific example.

**Comment by Ch3LL** [comment]
ping @plastikos looks like you added this feature here  https://github.com/saltstack/salt/pull/47490/files

do you mind commenting here ?

**Comment by tacerus** [comment]
This still seems to be an issue. With slsutil.renderer, the includes only work if they are absolute, which in return won't work in the real environment. It would be great being able to debug render templates whilst keeping their relative includes as is.
