### ISSUE TITLE
ansiblegate.py Module will not be loaded: 'module' object has no attribute 'IGNORE_FILES'

### ISSUE THREAD

**Issue by maltris** [saltstack/salt#51834]
```
[DEBUG   ] Resolving Ansible modules
[ERROR   ] Exception raised when processing __virtual__ function for salt.loaded.int.module.ansiblegate. Module will not be loaded: 'module' object has no attribute 'IGNORE_FILES'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1790, in _process_virtual
    virtual = getattr(mod, virtual_func)()
  File "/usr/lib/python2.7/dist-packages/salt/modules/ansiblegate.py", line 227, in __virtual__
    _resolver = AnsibleModuleResolver(__opts__).resolve().install()
  File "/usr/lib/python2.7/dist-packages/salt/modules/ansiblegate.py", line 123, in resolve
    self._modules_map = self._get_modules_map()
  File "/usr/lib/python2.7/dist-packages/salt/modules/ansiblegate.py", line 79, in _get_modules_map
    paths.update(self._get_modules_map(p_el_path))
  File "/usr/lib/python2.7/dist-packages/salt/modules/ansiblegate.py", line 79, in _get_modules_map
    paths.update(self._get_modules_map(p_el_path))
  File "/usr/lib/python2.7/dist-packages/salt/modules/ansiblegate.py", line 83, in _get_modules_map
    p_el in ansible.constants.IGNORE_FILES):
AttributeError: 'module' object has no attribute 'IGNORE_FILES'
[WARNING ] salt.loaded.int.module.ansiblegate.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'ansiblegate', please fix this.
```

```
# salt-call -V
Salt Version:
           Salt: 2018.3.3
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-116-generic
         system: Linux
        version: Ubuntu 16.04 xenial

```

https://github.com/saltstack/salt/blob/4b37292ffb1a0ba7cee402071bf8e851fd7c90dc/salt/modules/ansiblegate.py#L86

**Comment by Ch3LL** [comment]
what ansible module version do you have installed? Looks liked IGNORED_FILES was added int `v2.1.0.0-1` and above.

**Comment by maltris** [comment]
2.0.0.2-2ubuntu1.1 as provided by xenial-updates: https://packages.ubuntu.com/xenial-updates/ansible

The problem seems to be gone with 2.1.1.0-1~ubuntu16.04.1 as provided by xenial-backports: https://packages.ubuntu.com/xenial-backports/ansible
