### ISSUE TITLE
mysql module version comparison doesn't work in python3 

### ISSUE THREAD

**Issue by Oloremo** [saltstack/salt#51866]
### Description of Issue/Question
Fluorine release **doesn't** have a MariaDB fixes in mysql.py module.
So I'm tried to apply mysql module version compassion fix(https://github.com/saltstack/salt/pull/51530) for MariaDB from 2018.3 branch to 2019.2 one with Salt running with python3 and runs on a problem with the following error:

```
Function: mysql_user.present
Name: root
Result: False
Comment: An exception occurred in this state: Traceback (most recent call last):
                   File "/usr/local/lib/python3.6/site-packages/salt/state.py", line 1933, in call
                   **cdata['kwargs'])
                   File "/usr/local/lib/python3.6/site-packages/salt/loader.py", line 1939, in wrapper                    
                   return f(*args, **kwargs)
                   File "/usr/local/lib/python3.6/site-packages/salt/states/mysql_user.py", line 142, in present
                    **connection_args):
                    File "/opt/behavox/salt/library/extmods/modules/mysql.py", line 1206, in user_exists
                    compare_version = '10.2.0' if 'MariaDB' in server_version else '8.0.11'
                    TypeError: a bytes-like object is required, not 'str'
```

### Steps to Reproduce Issue
Apply fixes from the to the  2019.2 branch
Start Salt from python 3
Try to execute a `mysql_user.present` state

### Versions Report
```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.6 (default, Aug 13 2018, 18:24:23)
   python-gnupg: 0.4.4
         PyYAML: 3.13
          PyZMQ: 18.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

**Comment by Oloremo** [comment]
Kinda related: https://github.com/saltstack/salt/issues/45026

**Comment by Oloremo** [comment]
So fix is merged yet no ported. Should I close an issue?..

**Comment by Oloremo** [comment]
Backported to the  v2019.2.1, so closing it. Thanks!
