### ISSUE TITLE
[Py3][Tornado 5.0] IOLoop tests failing with asyncio

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#51883]
@gtmanfred commented on [Thu May 24 2018](https://github.com/saltstack/salt-jenkins/issues/995)

When running 

```
PYTHONASYNCIODEBUG=1 python3 -m tests.runtests --output-columns=80 -vv --run-destructive --ssh -n integration.modules.test_aliases -n integration.modules.test_saltutil
```

The integration.modules.test_saltutil.SaltUtilSyncModuleTest.test_sync_all hangs and eventually errors with the following.

```
test_sync_all (integration.modules.test_saltutil.SaltUtilSyncModuleTest)
[CPU:35.6%|MEM:53.5%]  ... 15:22:22,347 [asyncio                            :1131][ERROR   ] Exception in callback future_with_timeout_callback(<Future finis...stream.py:812>) at /root/salt/salt/transport/ipc.py:36
handle: <Handle future_with_timeout_callback(<Future finis...stream.py:812>) at /root/salt/salt/transport/ipc.py:36 created at /usr/lib64/python3.4/asyncio/futures.py:242>
source_traceback: Object created at (most recent call last):
  File "/usr/lib64/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/salt/tests/runtests.py", line 789, in <module>
    main()
  File "/root/salt/tests/runtests.py", line 774, in main
    status = parser.run_integration_tests()
  File "/root/salt/tests/runtests.py", line 714, in run_integration_tests
    results = self.run_suite('', name, suffix='test_*.py', load_from_name=True)
  File "/root/salt/tests/support/parser/__init__.py", line 515, in run_suite
    verbosity=self.options.verbosity).run(tests)
  File "/usr/lib64/python3.4/unittest/runner.py", line 168, in run
    test(result)
  File "/usr/lib64/python3.4/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib64/python3.4/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib64/python3.4/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib64/python3.4/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib64/python3.4/unittest/case.py", line 666, in __call__
    return self.run(*args, **kwds)
  File "/root/salt/tests/support/unit.py", line 181, in run
    outcome = super(TestCase, self).run(result=result)
  File "/usr/lib64/python3.4/unittest/case.py", line 614, in run
    self.setUp()
  File "/root/salt/tests/integration/modules/test_saltutil.py", line 72, in setUp
    self.run_function('saltutil.sync_all', extmod_whitelist=whitelist)
  File "/root/salt/tests/support/case.py", line 727, in run_function
    kwarg=kwargs)
  File "/root/salt/salt/client/__init__.py", line 741, in cmd
    **kwargs):
  File "/root/salt/salt/client/__init__.py", line 1595, in get_cli_event_returns
    **kwargs
  File "/root/salt/salt/client/__init__.py", line 1180, in get_iter_returns
    for raw in ret_iter:
  File "/root/salt/salt/client/__init__.py", line 1105, in get_returns_no_block
    no_block=True, auto_reconnect=self.auto_reconnect)
  File "/root/salt/salt/utils/event.py", line 641, in get_event
    ret = self._get_event(wait, tag, match_func, no_block)
  File "/root/salt/salt/utils/event.py", line 541, in _get_event
    raw = self.subscriber.read_sync(timeout=wait)
  File "/root/salt/salt/transport/ipc.py", line 702, in read_sync
    self.io_loop.start()
  File "/usr/lib64/python3.4/site-packages/tornado/platform/asyncio.py", line 127, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib64/python3.4/asyncio/base_events.py", line 331, in run_forever
    self._run_once()
  File "/usr/lib64/python3.4/asyncio/base_events.py", line 1287, in _run_once
    handle._run()
  File "/usr/lib64/python3.4/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/lib64/python3.4/site-packages/tornado/platform/asyncio.py", line 117, in _handle_events
    handler_func(fileobj, events)
  File "/usr/lib64/python3.4/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib64/python3.4/site-packages/tornado/iostream.py", line 657, in _handle_events
    self._handle_read()
  File "/usr/lib64/python3.4/site-packages/tornado/iostream.py", line 801, in _handle_read
    self._read_from_buffer(pos)
  File "/usr/lib64/python3.4/site-packages/tornado/iostream.py", line 939, in _read_from_buffer
    self._run_read_callback(pos, False)
  File "/usr/lib64/python3.4/site-packages/tornado/iostream.py", line 835, in _run_read_callback
    future.set_result(result)
  File "/usr/lib64/python3.4/asyncio/futures.py", line 332, in set_result
    self._schedule_callbacks()
  File "/usr/lib64/python3.4/asyncio/futures.py", line 242, in _schedule_callbacks
    self._loop.call_soon(callback, self)
Traceback (most recent call last):
  File "/root/salt/salt/transport/ipc.py", line 80, in _done_callback
    self.set_result(future.result())
  File "/usr/lib64/python3.4/asyncio/futures.py", line 329, in set_result
    raise InvalidStateError('{}: {!r}'.format(self._state, self))
asyncio.futures.InvalidStateError: FINISHED: <FutureWithTimeout finished result=b'\x82\xa4bod...r\xa4head\x80' created at /root/salt/salt/transport/ipc.py:43>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.4/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/root/salt/salt/transport/ipc.py", line 38, in future_with_timeout_callback
    future._future_with_timeout._done_callback(future)
  File "/root/salt/salt/transport/ipc.py", line 82, in _done_callback
    self.set_exception(exc)
  File "/usr/lib64/python3.4/asyncio/futures.py", line 341, in set_exception
    raise InvalidStateError('{}: {!r}'.format(self._state, self))
asyncio.futures.InvalidStateError: FINISHED: <FutureWithTimeout finished result=b'\x82\xa4bod...r\xa4head\x80' created at /root/salt/salt/transport/ipc.py:43>
15:22:28,404 [asyncio                            :1131][ERROR   ] Exception in callback future_with_timeout_callback(<Future finis...stream.py:812>) at /root/salt/salt/transport/ipc.py:36
handle: <Handle future_with_timeout_callback(<Future finis...stream.py:812>) at /root/salt/salt/transport/ipc.py:36 created at /usr/lib64/python3.4/asyncio/futures.py:242>
source_traceback: Object created at (most recent call last):
  File "/usr/lib64/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/salt/tests/runtests.py", line 789, in <module>
    main()
  File "/root/salt/tests/runtests.py", line 774, in main
    status = parser.run_integration_tests()
  File "/root/salt/tests/runtests.py", line 714, in run_integration_tests
    results = self.run_suite('', name, suffix='test_*.py', load_from_name=True)
  File "/root/salt/tests/support/parser/__init__.py", line 515, in run_suite
    verbosity=self.options.verbosity).run(tests)
  File "/usr/lib64/python3.4/unittest/runner.py", line 168, in run
    test(result)
  File "/usr/lib64/python3.4/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib64/python3.4/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib64/python3.4/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib64/python3.4/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib64/python3.4/unittest/case.py", line 666, in __call__
    return self.run(*args, **kwds)
  File "/root/salt/tests/support/unit.py", line 181, in run
    outcome = super(TestCase, self).run(result=result)
  File "/usr/lib64/python3.4/unittest/case.py", line 614, in run
    self.setUp()
  File "/root/salt/tests/integration/modules/test_saltutil.py", line 72, in setUp
    self.run_function('saltutil.sync_all', extmod_whitelist=whitelist)
  File "/root/salt/tests/support/case.py", line 727, in run_function
    kwarg=kwargs)
  File "/root/salt/salt/client/__init__.py", line 741, in cmd
    **kwargs):
  File "/root/salt/salt/client/__init__.py", line 1595, in get_cli_event_returns
    **kwargs
  File "/root/salt/salt/client/__init__.py", line 1180, in get_iter_returns
    for raw in ret_iter:
  File "/root/salt/salt/client/__init__.py", line 1105, in get_returns_no_block
    no_block=True, auto_reconnect=self.auto_reconnect)
  File "/root/salt/salt/utils/event.py", line 641, in get_event
    ret = self._get_event(wait, tag, match_func, no_block)
  File "/root/salt/salt/utils/event.py", line 541, in _get_event
    raw = self.subscriber.read_sync(timeout=wait)
  File "/root/salt/salt/transport/ipc.py", line 702, in read_sync
    self.io_loop.start()
  File "/usr/lib64/python3.4/site-packages/tornado/platform/asyncio.py", line 127, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib64/python3.4/asyncio/base_events.py", line 331, in run_forever
    self._run_once()
  File "/usr/lib64/python3.4/asyncio/base_events.py", line 1287, in _run_once
    handle._run()
  File "/usr/lib64/python3.4/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/lib64/python3.4/site-packages/tornado/platform/asyncio.py", line 117, in _handle_events
    handler_func(fileobj, events)
  File "/usr/lib64/python3.4/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib64/python3.4/site-packages/tornado/iostream.py", line 657, in _handle_events
    self._handle_read()
  File "/usr/lib64/python3.4/site-packages/tornado/iostream.py", line 801, in _handle_read
    self._read_from_buffer(pos)
  File "/usr/lib64/python3.4/site-packages/tornado/iostream.py", line 939, in _read_from_buffer
    self._run_read_callback(pos, False)
  File "/usr/lib64/python3.4/site-packages/tornado/iostream.py", line 835, in _run_read_callback
    future.set_result(result)
  File "/usr/lib64/python3.4/asyncio/futures.py", line 332, in set_result
    self._schedule_callbacks()
  File "/usr/lib64/python3.4/asyncio/futures.py", line 242, in _schedule_callbacks
    self._loop.call_soon(callback, self)
Traceback (most recent call last):
  File "/root/salt/salt/transport/ipc.py", line 80, in _done_callback
    self.set_result(future.result())
  File "/usr/lib64/python3.4/asyncio/futures.py", line 329, in set_result
    raise InvalidStateError('{}: {!r}'.format(self._state, self))
asyncio.futures.InvalidStateError: FINISHED: <FutureWithTimeout finished result=b'\x82\xa4bod...r\xa4head\x80' created at /root/salt/salt/transport/ipc.py:43>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.4/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/root/salt/salt/transport/ipc.py", line 38, in future_with_timeout_callback
    future._future_with_timeout._done_callback(future)
  File "/root/salt/salt/transport/ipc.py", line 82, in _done_callback
    self.set_exception(exc)
  File "/usr/lib64/python3.4/asyncio/futures.py", line 341, in set_exception
    raise InvalidStateError('{}: {!r}'.format(self._state, self))
asyncio.futures.InvalidStateError: FINISHED: <FutureWithTimeout finished result=b'\x82\xa4bod...r\xa4head\x80' created at /root/salt/salt/transport/ipc.py:43>
```

---

@DmitryKuzmenko commented on [Fri May 25 2018](https://github.com/saltstack/salt-jenkins/issues/995#issuecomment-392065160)

Using Python 3.6 after start master trying to start minion I'm getting the following error in the minion log:
```
[INFO    ] fire_master failed: Traceback (most recent call last):
  File "/home/dimm/projects/salt/git/salt/salt/minion.py", line 1281, in _fire_master
    self._send_req_sync(load, timeout)
  File "/home/dimm/projects/salt/git/salt/salt/minion.py", line 1245, in _send_req_sync
    return channel.send(load, timeout=timeout)
  File "/home/dimm/projects/salt/git/salt/salt/utils/async.py", line 70, in wrap
    ret = self._block_future(ret, oloop)
  File "/home/dimm/projects/salt/git/salt/salt/utils/async.py", line 81, in _block_future
    self.io_loop.start()
  File "/home/dimm/projects/salt/python-venv/venv-3.6/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 127, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 412, in run_forever
    'Cannot run the event loop while another loop is running')
RuntimeError: Cannot run the event loop while another loop is running
```
I have to fix this issue first before I can to continue to work on the original report.
@rallytime is it OK?

---

@rallytime commented on [Fri May 25 2018](https://github.com/saltstack/salt-jenkins/issues/995#issuecomment-392073736)

@DmitryKuzmenko Yes, that error will need to be fixed first. Good find!

---

@nbraud commented on [Tue Aug 28 2018](https://github.com/saltstack/salt-jenkins/issues/995#issuecomment-416552025)

What's the status of this, and will a fix be included in 2018.3.3?

I'm asking because this results in Salt being completely broken in Debian `sid` and `testing`.  :(

---

@gtmanfred commented on [Tue Aug 28 2018](https://github.com/saltstack/salt-jenkins/issues/995#issuecomment-416570266)

This is not going to be fixed in 2018.3.3, you will have to stick with salt with python2 for versions where python-tornado is already upgraded.

This is will be fixed in Fluorine for python3 and if it is not too complicated it may be backported to 2018.3 once it has finished, but it is not holding up the 2018.3.3 release.

---

@nbraud commented on [Wed Aug 29 2018](https://github.com/saltstack/salt-jenkins/issues/995#issuecomment-416887567)

@gtmanfred OK, that's good to know (and I will forward that info to the corresponding Debian bug).
Is there an ETA on Fluorine?  I see 2018.11 has been [tagged](https://github.com/saltstack/salt/releases), but the [documentation](https://docs.saltstack.com/en/latest/topics/releases/version_numbers.html) states that Fluorine's version number is still TBD; does it mean it won't happen this year?

---

@gtmanfred commented on [Wed Aug 29 2018](https://github.com/saltstack/salt-jenkins/issues/995#issuecomment-416947473)

2018.11 is our target, but we still need to get a release candidate out.

---

@DmitryKuzmenko commented on [Mon Sep 24 2018](https://github.com/saltstack/salt-jenkins/issues/995#issuecomment-424168351)

I've done a big code review around the stuff is still needed to be modified to work properly under Tornado up to 5.x
Next step is to estimate this list and go forward step-by-step.

Sync/Async issues
==========

- salt
    - auth
        - class Resolver
            - def _send_token_request
                Uses sync wrapper for AsyncReqChannel. This method is used from `token_cli`,
                `mk_token` and `get_token` methods.  Switch to async and analyze those methods usage
                in the code.
    - cli
        - caller
            - class BaseCaller
                - def call
                    Will not work with `coroutines` execution module functions. Make it run through
                    eventloop with waiting for returned coroutine is done.
            - class ZeroMQCaller (BaseCaller)
                - def return_pub
                    Uses sync wrapper for AsyncReqChannel. Check is it okay if not change to async.
    - client
        - class LocalClient
            - def pub
                Coroutine, reworked to async, revert back to sync.
            - def pub_async
                Equal to the current pub implementation, use everywhere instead of pub.
        - mixins
            - SyncClientMixin
                - def low
                    Uses sync client. Check usage Runs runner and wheel modules directly. Check for
                    async calls.
    - crypt
        - Remove io_loop argument from all classes. Use current ioloop.
        - class AsyncAuth
            - def gen_token
                In much cases SAuth is instantiated just to call this method once. Check for a way
                to either rewrite it to a single function or use AsyncAuth instead of SAuth.
    - fileclient
        - def get_file_client
            Returns an instance of unified interface that could be remote or local client. Remote is
            needed to be rewritten in async paradigm when local is not. Think about a common
            interface for both. Don't forget about sync/async caller.
        - class RemoteClient(Client)
            - self.channel is sync wrapped AsyncReqChannel. Switch to async.
            - `class FSClient(RemoteClient)` uses sync `FSChan`
            - def get_file
            - def file_list
            - def file_list_empty_dirs
            - def dir_list
            - def symlink_list
            - def __hash_and_stat_file
            - def hash_and_stat_file
            - def list_env
            - def envs
            - def master_opts
            - def master_tops
                Uses sync channel send. Adopt to async.
    - fileserver
        - roots
            - def update
                Uses sync event. Change to async.
        - svnfs
            - def update
                Uses sync event. Change ot async.
        - hgfs
            - def update
                Uses sync event. Change ot async.
    - minion
        - class Minion
            - def _send_req_sync
                Used by:
                    - def _fire_master with sync=True
                        Not used anymore, remove sync functionality.
                    - def _return_pub with sync=True
                        Not used anymore, remove sync functionality.
                    - def _return_pub_multi with sync=True
                        Not used anymore, remove sync functionality.
            - def _mine_send
                Uses sync wrapper for channel. Rewrite to use AsyncReqChannel.
    - modules
        - cp
            - def _auth
                Uses SAuth. Change to AsyncAuth.
            - def push
                Uses sync wrapper for channel. Rewrite to use AsyncReqChannel.
        - event
            - def fire_master
                Uses sync wrapper for channel. Rewrite to use AsyncReqChannel.
                This returns bool so no need to make it coroutine.
                Uses SAuth. Change to AsyncAuth.
                Uses MinionEvent with `sync=True`. Rewrite to `sync=False`.
            - def fire
                Uses SaltEvent with `sync=True`. Rewrite to `sync=False`.
                This returns bool so no need to make it coroutine.
        - mine
            - def _auth
                Uses SAuth. Change to AsyncAuth.
            - def _mine_get
                Uses sync wrapper for channel. Rewrite to use AsyncReqChannel.
            - def _mine_send
                Uses MinionEvent with `sync=True`. Rewrite to `sync=False`.
            - def get
                uses _mine_get
            - def update
                Calls module functions that can be coroutines now. Check the result and wait for
                coroutine result with `yield` like it's done in `minion.Minion._thread_return`.
        - publish
            - def _publish
            - def runner
                Uses sync wrapper for channel. Rewrite to use AsyncReqChannel.
                Uses SAuth. Change to AsyncAuth.
        - saltutil
            - def revoke_auth
                Uses sync wrapper for channel. Rewrite to use AsyncReqChannel
            - def regen_keys
                Creates sync wrapped channel just because it regenerates keys. Check how to rewrite
                this.
        - status
            - def ping_master
                Uses sync wrapper for channel. Rewrite to use AsyncReqChannel.
                Uses sync SaltEvent. Switch to async.
    - pillar
        - def get_pillar
            Shall be changed to get_async_pillar almost everywhere. Exception could be the only
            single call cli wrappers.
        - class RemotePillar(RemotePillarMixin)
            Avoid of using this class. Replace with AsyncRemotePillar.
    - returners
        - highstate_return
            - def _generate_report
                Calls custom configured execution function that now could be a coroutine.
    - state
        - class RemoteHighState
            - def compile_master
                Uses sync wrapper for channel. Rewrite to use AsyncReqChannel.
                This class isn't used anywhere in salt code. Remove?
    - transport
        - client
            - class ReqChannel
                Is a SyncWrapper for AsyncReqChannel. It's used by Channel class and all usage is
                covered by this document so it could be just removed if there still no usages after
                refactoring.
            - class PushChannel
                Is a SyncWrapper for AsyncPushChannel. Not used anywhere.
            - class PullChannel
                Is a SyncWrapper for AsyncPullChannel. Not used anywhere.
        - tcp
            - class AsyncTCPPubChannel(salt.transport.mixins.auth.AESPubClientMixin,
                                       salt.transport.client.AsyncPubChannel)
                - def connect_callback @coroutine
                    Remove using of SyncWrapper inside.
            - class AsyncTCPReqChannel (salt.transport.client.ReqChannel)
                - def crypted_transfer_decode_dictentry
                    Coroutine. Ensure it's used correctly in the code.
        - zeromq
            - class AsyncZeroMQReqChannel (salt.transport.client.ReqChannel)
                - def crypted_transfer_decode_dictentry
                    Coroutine. Ensure it's used correctly in the code.
    - utils
        - event
            - class StateFire
                - this class is not used in salt code. Deprecate it?
                - def __init__
                    Uses SAuth. Lookup for rework to AsyncAuth.
                - def fire_master
                - def fire_running
                    Both use sync `Channel` that would fail if ioloop already running.
            - class EventReturn
                Optional! It's a master subprocess. Now it runs/stops ioloop to iterate events.
                Rewrite to work inside one continuously running ioloop.
            - def get_event
                Review sync/async usages.
            - def get_master_event
                Review sync/async usages.
            - def fire_args
                Uses sync master event. Switch to async.
        - reactor
            - class ReactWrap
                Uses sync paradigm. Review for possibility to migrate to tornado asyncio.
            - class Reactor
                Uses sync paradigm: in run method it iterates through sync event that runs/stops
                ioloop.
    - wheel
        - class WheelClient (salt.client.mixins.SyncClientMixin,
                             salt.client.mixins.AsyncClientMixin)
                - def master_call
                    Uses Sync wrapped channel that is okay for all except
                    `salt.modules.saltutil.wheel` in current implementation.

Other problems found
====================

- Proxy minion support
- Proxy minion starts engines after event loop start
- `salt.modules.saltutil.wheel` uses WheelClient that is synchronous
- SaltEvent: check almost everywhere it should be created with `sync=False`
- salt.utils.event.get_event ^^^
- Check where `__salt__` is used in modules. Check it for compatibility with
  coroutines.
    - Found over 7400 usages of `\<__salt__\[`. （╯°□°）╯︵ ┻━┻
- Check get_local_client(sync=True(Default))
    - Found 61 usage
- Check `sync=` kwarg in other classes and functions

**Comment by taigrr** [comment]
As a note, I'd like to bump the priority on this if possible. The archlinux official release is still stuck at the python 2 release until full Tornado 5 support is patched.

**Comment by sagetherage** [comment]
Not stale
