### ISSUE TITLE
Salt don't stop on Jinja errors

### ISSUE THREAD

**Issue by Oloremo** [saltstack/salt#51906]
### Description of Issue/Question
I have this construction in my orchestration:

```
{% set nodes_to_migrate = [] %}
{% for id, misstake in salt['mine.get']('roles:mysql', 'mysql', tgt_type='grain').items() %}
{%  if 'galera_migration' in mysql and mysql.galera_migration == 'needed' %}
{%    do nodes_to_migrate.append(id) %}
{%  endif %}
{% endfor %}
```

As you may see I run mine.get and set it's output to two variables `id` and `misstake`. Mistake name indicates a typo that I made. :-) On the next string I'm trying to search a key `galera_migration` in `mysql` variable yet this variable is undefined. 

If I run orchestration runner against this state - it works without any errors:
```
$ salt-run state.orchestrate orch.galera_bootstrap -l critical
test-run-kproskurin-rm.aws.internal_master:
  Name: install.mysql.base - Function: salt.state - Result: Clean Started: - 14:34:34.628640 Duration: 1297.399 ms

Summary for test-run-kproskurin-rm.aws.internal_master
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:   1.297 s
[behavox@test-run-kproskurin-rm salt]$ echo $?
0
```

But if I run `slsutil.renderer` against this file it actually shows an error!

salt-call slsutil.renderer salt://orch/galera_bootstrap.sls
```
---
{% set galera = pillar.get('galera') %}

{% set nodes_to_migrate = [] %}
{% for id, misstake in salt['mine.get']('roles:mysql', 'mysql', tgt_type='grain').items() %}
{%  if 'galera_migration' in mysql and mysql.galera_migration == 'needed' %}    <======================
{%    do nodes_to_migrate.append(id) %}
{%  endif %}
{% endfor %}


[...]
---
# [ERROR   ] An un-handled exception was caught by salt's global exception handler:
SaltRenderError: Jinja error: argument of type 'StrictUndefined' is not iterable
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/salt/utils/templates.py", line 392, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/local/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 6, in top-level template code
TypeError: argument of type 'StrictUndefined' is not iterable

; line 6
```

Other funny example looks like this:
```
{% set var1 = nonexistent | to_bool %}
```

`var1` will be set to `False` and I'm not sure if this behavior is correct in terms of being error-prone.

This makes using Jinja even more complicated than it's already is. 

### Versions Report
```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.6 (default, Aug 13 2018, 18:24:23)
   python-gnupg: 0.4.4
         PyYAML: 3.13
          PyZMQ: 18.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

**Comment by Oloremo** [comment]
To make it even more confusing I just checked that this code:
```
{% set nodes_to_migrate = [] %}
{%  if 'galera_migration' in mysql and mysql.galera_migration == 'needed' %}
{%    do nodes_to_migrate.append(1) %}
{%  endif %}
```
Actually produces the error. So it maybe a `mine` related?..

**Comment by Oloremo** [comment]
Please disregard, the problem was in the fact that `slsutil.renderer` used the different data than a orch for some reason, so in orch loop was done against an empty iterator for it didn't actually execute line with syntax error.
