### ISSUE TITLE
Slack returner not found and not loaded

### ISSUE THREAD

**Issue by echoes86** [saltstack/salt#51901]
### Description of Issue/Question
Hello ... I'm trying to use the Slack returner provided with Salt. I want to filter only some of the messages, but for the moment is ok to let it load and run (in future I will add an `event_return`).

The scenario is simple:
 - [`master_job_cache` NOT SET] when I run `salt 'minion' --return slack test.ping` everything is ok and the `slack` returner is used
 - when I try to set `master_job_cache: slack` the master got crazy and I see in the logs some lines of debug declaring _Failed to allocate a jid. The requested returner 'slack' could not be loaded._

### Setup
**/etc/salt/master**
```
slack.channel: admin
slack.api_key: <key>
slack.username: Saltstack
slack.as_user: true

master_job_cache: slack
```

### Steps to Reproduce Issue
I include the debug log when I try to execute a `test.ping` to a minion.
```
2019-02-28 14:08:52,412 [salt.utils.verify:535 ][WARNING ][16056] Insecure logging configuration detected! Sensitive data may be logged.
2019-02-28 14:08:52,484 [salt.master      :2191][ERROR   ][15514] **Failed to allocate a jid. The requested returner 'slack' could not be loaded.**
2019-02-28 14:08:52,486 [salt.transport.zeromq:754 ][ERROR   ][15514] Some exception handling a payload from minion
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 750, in handle_message
    ret, req_opts = yield self.payload_handler(payload)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 215, in wrapper
    result = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 1064, in _handle_payload
    'clear': self._handle_clear}[key](load)
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 1095, in _handle_clear
    ret = getattr(self.clear_funcs, cmd)(load), {'fun': 'send_clear'}
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 2137, in publish
    payload = self._prep_pub(minions, jid, clear_load, extra, missing)
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 2229, in _prep_pub
    self.event.fire_event({'minions': minions}, clear_load['jid'])
  File "/usr/lib/python2.7/dist-packages/salt/utils/event.py", line 744, in fire_event
    salt.utils.stringutils.to_bytes(tag),
  File "/usr/lib/python2.7/dist-packages/salt/utils/stringutils.py", line 63, in to_bytes
    return to_str(s, encoding, errors)
  File "/usr/lib/python2.7/dist-packages/salt/utils/stringutils.py", line 118, in to_str
    raise TypeError('expected str, bytearray, or unicode')
TypeError: expected str, bytearray, or unicode
2019-02-28 14:08:52,487 [tornado.general  :452 ][ERROR   ][15514] Uncaught exception, closing connection.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 444, in _handle_events
    self._handle_send()
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 487, in _handle_send
    status = self.socket.send_multipart(msg, **kwargs)
  File "/usr/lib/python2.7/dist-packages/zmq/sugar/socket.py", line 326, in send_multipart
    i, rmsg,
TypeError: Frame 0 (u'Some exception handling minion...) does not support the buffer interface.
2019-02-28 14:08:52,488 [tornado.application:612 ][ERROR   ][15514] Exception in callback None
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/ioloop.py", line 866, in start
    handler_func(fd_obj, events)
  File "/usr/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 444, in _handle_events
    self._handle_send()
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 487, in _handle_send
    status = self.socket.send_multipart(msg, **kwargs)
  File "/usr/lib/python2.7/dist-packages/zmq/sugar/socket.py", line 326, in send_multipart
    i, rmsg,
TypeError: Frame 0 (u'Some exception handling minion...) does not support the buffer interface.
```

### Versions Report
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 12 2018, 14:36:49)
   python-gnupg: 0.3.8
         PyYAML: 3.12
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-1052-aws
         system: Linux
        version: Ubuntu 16.04 xenial

Same version on minion targeted.

**Comment by dwoz** [comment]
@echoes86 Thanks for reporting this. I tested this on 2018.3.4 and got the same result
