### ISSUE TITLE
salt-windows-2012r2-py2 tests fail for 2017.7

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#51928]
I'm not entirely sure what's going wrong: https://jenkinsci.saltstack.com/job/2017.7/job/salt-windows-2012r2-py2/13/consoleFull

The first error in the log is:

```
03:50:59        c:\salt\salt-call.bat : [ERROR   ] Could not cache minion ID: [Errno 2] No such file or directory: 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\kitchen\\conf\\minion_id'
03:50:59        At line:1 char:131
```

Then things  run okay until

```
03:53:28        [WARNING ] The function "module.run" is using its deprecated version and will expire in version "Sodium".
03:53:28        
03:53:30        [WARNING ] C:\salt\bin\lib\site-packages\salt\modules\win_update.py:93: DeprecationWarning: The 'win_update' module is being deprecated and will be removed in Salt Fluorine (Unreleased). Please use the 'win_wua' module instead.
03:53:30        
03:53:30        
03:53:30        [ERROR   ] Not able to read repo file
03:53:30        
03:53:30        [ERROR   ] [Errno 2] No such file or directory: u'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\kitchen\\var\\cache\\salt\\minion\\files\\base\\win\\repo-ng\\winrepo.p'
03:53:30        Traceback (most recent call last):
03:53:30          File "C:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 1872, in get_repo_data
03:53:30            with salt.utils.fopen(repo_details.winrepo_file, 'rb') as repofile:
03:53:30          File "C:\salt\bin\lib\site-packages\salt\utils\__init__.py", line 1361, in fopen
03:53:30            fhandle = open(*args, **kwargs)  # pylint: disable=resource-leakage
03:53:30        IOError: [Errno 2] No such file or directory: u'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\kitchen\\var\\cache\\salt\\minion\\files\\base\\win\\repo-ng\\winrepo.p'
```

Not sure if those are in any way related to the failure, but it's clearly failing.

**Comment by dwoz** [comment]
These builds are broken across the board:

```
Suite salt-windows-2012r2-py3 failed on 2017.7, 2017.7.9, 2018.3, 2019.2, develop
Suite salt-windows-2012r2-py2 failed on 2017.7, 2017.7.9, 2018.3, 2019.2, develop
```

**Comment by twangboy** [comment]
I'm going to close this until we get tests running properly on 2012r2.
