### ISSUE TITLE
AttributeError in spm/pkgfiles/local.py

### ISSUE THREAD

**Issue by recursiveMake** [saltstack/salt#51957]
### Description of Issue/Question

An `AttributeError` is raised accessing the `name` attribute of the unicode string `new_name`

It seems like the code in `salt/spm/pkgfiles/local.py` mistakenly tries to get this attribute twice in the `install_file` function (mirroring the pattern used to get `name` from the `member` object).

### Setup

Install from a configured SPM

### Steps to Reproduce Issue

```
    test: [ERROR   ] An un-handled exception was caught by salt's global exception handler:
    test: AttributeError: 'unicode' object has no attribute 'name'
    test: Traceback (most recent call last):
    test:   File "/bin/spm", line 12, in <module>
    test:     salt_spm()
    test:   File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 527, in salt_spm
    test:     spm.run()
    test:   File "/usr/lib/python2.7/site-packages/salt/cli/spm.py", line 41, in run
    test:     client.run(self.args)
    test:   File "/usr/lib/python2.7/site-packages/salt/spm/__init__.py", line 125, in run
    test:     self._install(args)
    test:   File "/usr/lib/python2.7/site-packages/salt/spm/__init__.py", line 379, in _install
    test:     self._install_indv_pkg(package, out_file)
    test:   File "/usr/lib/python2.7/site-packages/salt/spm/__init__.py", line 532, in _install_indv_pkg
    test:     self.files_conn)
    test:   File "/usr/lib/python2.7/site-packages/salt/spm/__init__.py", line 161, in _pkgfiles_fun
    test:     return self.pkgfiles['{0}.{1}'.format(self.files_prov, func)](*args, **kwargs)
    test:   File "/usr/lib/python2.7/site-packages/salt/spm/pkgfiles/local.py", line 147, in install_file
    test:     member.name = new_name.name.replace('{0}/'.format(package), '')
    test: AttributeError: 'unicode' object has no attribute 'name'
    test: Traceback (most recent call last):
    test:   File "/bin/spm", line 12, in <module>
    test:     salt_spm()
    test:   File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 527, in salt_spm
    test:     spm.run()
    test:   File "/usr/lib/python2.7/site-packages/salt/cli/spm.py", line 41, in run
    test:     client.run(self.args)
    test:   File "/usr/lib/python2.7/site-packages/salt/spm/__init__.py", line 125, in run
    test:     self._install(args)
    test:   File "/usr/lib/python2.7/site-packages/salt/spm/__init__.py", line 379, in _install
    test:     self._install_indv_pkg(package, out_file)
    test:   File "/usr/lib/python2.7/site-packages/salt/spm/__init__.py", line 532, in _install_indv_pkg
    test:     self.files_conn)
    test:   File "/usr/lib/python2.7/site-packages/salt/spm/__init__.py", line 161, in _pkgfiles_fun
    test:     return self.pkgfiles['{0}.{1}'.format(self.files_prov, func)](*args, **kwargs)
    test:   File "/usr/lib/python2.7/site-packages/salt/spm/pkgfiles/local.py", line 147, in install_file
    test:     member.name = new_name.name.replace('{0}/'.format(package), '')
    test: AttributeError: 'unicode' object has no attribute 'name'
```

### Versions Report

```
$ salt --versions-report
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Oct 30 2018, 23:45:53)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.1.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core
```

**Comment by garethgreenaway** [comment]
@recursiveMake Thanks for the report.  It appears that the issue is that new_name is being set to the result of running the replace on the name attribute of member.  This looks like it should be a fairly simple fix if you're able to provide a PR with the change.

**Comment by daveneeley** [comment]
#51965 needs to be merged into a few branches. It was introduced in Feb 2018 in https://github.com/saltstack/salt/commit/fefaff4f1ccd89e6a6e894dc93df9b0baf710455
which has these tags: v2019.8  v2019.2.0 v2019.2.0rc2 v2019.2.0rc1 v2019.2 v2018.11

**Comment by recursiveMake** [comment]
I believe this commit wasn't applied to all the branches. It's still a problem in master.
