### ISSUE TITLE
Sentry Logger throws error on Non-string types

### ISSUE THREAD

**Issue by weswhet** [saltstack/salt#51987]
### Description of Issue/Question

If you try and use a non-string type grain in the context list for the sentry logger it will throw an exception like below on 2019.2

```
salt-call: error: Error while processing <bound method SaltCall.__setup_extended_logging of <salt.cli.call.SaltCall object at 0x10ef34e90>>: Traceback (most recent call last):
  File "/opt/salt/lib/python2.7/site-packages/salt/utils/parsers.py", line 222, in parse_args
    mixin_after_parsed_func(self)
  File "/opt/salt/lib/python2.7/site-packages/salt/utils/parsers.py", line 861, in __setup_extended_logging
    log.setup_extended_logging(self.config)
  File "/opt/salt/lib/python2.7/site-packages/salt/log/setup.py", line 769, in setup_extended_logging
    handlers = get_handlers_func()
  File "/opt/salt/lib/python2.7/site-packages/salt/log/handlers/sentry_mod.py", line 215, in setup_handlers
    if len(tag_value) > 0:
TypeError: object of type 'bool' has no len()
```

This issue is resolved on develop already by https://github.com/saltstack/salt/pull/51201, can we get that back-ported to a 2019.2 bug fix release?

**Comment by Ch3LL** [comment]
i've added the backport label so it will get backported soon :) thanks for the heads up!

**Comment by Ch3LL** [comment]
Backported here: https://github.com/saltstack/salt/pull/52037
