### ISSUE TITLE
Module file.remove cannot handle symlinks on Windows

### ISSUE THREAD

**Issue by afischer-opentext-com** [saltstack/salt#52002]
### Description of Issue/Question

Using a minion running on Windows and when using the `file.remove` execution module this fails in case 
* the to be removed filesystem entry directory is containing a symlink
* the to be removed filesystem entry is a symlink

Th observed exception is

```
2019-03-06 05:02:47,659 [salt.minion      :1674][ERROR   ][2332] A command in 'file.remove' had a problem: Path not found: C:/Temp/tmp/vagrant/base\child_2\link
Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1637, in _thread_return
    return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
  File "c:\salt\bin\lib\site-packages\salt\executors\direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt\modules\win_file.py", line 1094, in remove
    remove(item, force)
  File "c:\salt\bin\lib\site-packages\salt\modules\win_file.py", line 1094, in remove
    remove(item, force)
  File "c:\salt\bin\lib\site-packages\salt\modules\win_file.py", line 1075, in remove
    raise CommandExecutionError('Path not found: {0}'.format(path))
salt.exceptions.CommandExecutionError: Path not found: C:/Temp/tmp/vagrant/base\child_2\link
```

### Setup

Vanilla Windows with vanilla salt 2018.3.4 py3 AMD 64

### Steps to Reproduce Issue

```
salt 'windowsminion' file.makedirs "C:/Temp/tmp/vagrant/base/child 1/target/"
salt 'windowsminion' file.makedirs "C:/Temp/tmp/vagrant/base/child 2/"
salt 'windowsminion' file.symlink "C:/Temp/tmp/vagrant/base/child 1/target/" "C:/Temp/tmp/vagrant/base/child 2/link"
salt 'windowsminion' file.remove "C:/Temp/tmp/vagrant/base"
```

### Versions Report

```
Salt Version:
           Salt: 2018.3.4
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6
 
System Versions:
           dist:   
         locale: cp1252
        machine: AMD64
        release: 2008ServerR2
         system: Windows
        version: 2008ServerR2 6.1.7601 SP1 Multiprocessor Free
```

**Comment by twangboy** [comment]
Thanks for the PR!
