### ISSUE TITLE
Inconsistent error handling in different output modules

### ISSUE THREAD

**Issue by Oloremo** [saltstack/salt#52007]
### Description of Issue/Question

I noticed some inconsistency with the 'profile' output as an example. So if you try to run a state.apply against a **non-existent state** with default output you will see something like this:

```
salt-call state.apply formula.consul2
[INFO    ] Although 'virt-what' was found in path, the current user cannot execute it. Grains output might not be accurate.
[INFO    ] Loading fresh modules for state activity
local:
    Data failed to compile:
----------
    No matching sls found for 'formula.consul2' in env 'base'
```

Yet if you do same thing with --out=profile you will see something like this:
```
salt-call state.apply formula.consul2 --out=profile
[INFO    ] Although 'virt-what' was found in path, the current user cannot execute it. Grains output might not be accurate.
[INFO    ] Loading fresh modules for state activity
[ERROR   ] Nested output failed:
Traceback (most recent call last):
  File "/opt/behavox/.local/lib/python3.6/site-packages/salt/output/__init__.py", line 43, in try_printout
    printout = get_printout(out, opts)(data, **kwargs)
  File "/opt/behavox/.local/lib/python3.6/site-packages/salt/output/profile.py", line 66, in output
    rows = _find_durations(data)
  File "/opt/behavox/.local/lib/python3.6/site-packages/salt/output/profile.py", line 17, in _find_durations
    dat = data[host][sid]
TypeError: list indices must be integers or slices, not str

During handling of the above exception, another exception occurred:
```

The reason is it receives a list with an error as a data yet it expects a dict with highstate output.
As far as I understand the **non-existent state** state should be caught way before and print an error.

### Versions Report
```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.6 (default, Aug 13 2018, 18:24:23)
   python-gnupg: 0.4.4
         PyYAML: 3.13
          PyZMQ: 18.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

**Comment by Oloremo** [comment]
not stale

**Comment by dwoz** [comment]
Fixed in #66770 (commit 53ddf5a, merged 2024-08-08, base 3006.x, merged-forward to 3007.x and 3008.x). The same patch was tracked as duplicate issue #65104. `_find_durations` now guards the dict indexing with try/TypeError and coerces non-dict values, so `--out=profile` no longer crashes on the list-of-error compile-failure payload. The outputter was purged into a community extension on 3008.x+ (no longer in core).
