### ISSUE TITLE
2019.2.0 TypeError chugid_and_umask() takes exactly 2 arguments (3 given)

### ISSUE THREAD

**Issue by do3meli** [saltstack/salt#52017]
### Description of Issue/Question
Running a highstate from a salt-master against a salt-minion on Debian 9 with 2019.2.0 resulting in an error. The minion log contains the following traceback:

```
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1913, in call
    if '__env__' not in inject_globals:
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1898, in wrapper
    )
  File "/usr/lib/python2.7/dist-packages/salt/states/cron.py", line 359, in present
    identifier=identifier)
  File "/usr/lib/python2.7/dist-packages/salt/modules/cron.py", line 553, in set_job
    lst = list_tab(user)
  File "/usr/lib/python2.7/dist-packages/salt/modules/cron.py", line 322, in list_tab
    data = raw_cron(user)
  File "/usr/lib/python2.7/dist-packages/salt/modules/cron.py", line 295, in raw_cron
    python_shell=False)
  File "/usr/lib/python2.7/dist-packages/salt/modules/cmdmod.py", line 1626, in run_stdout
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/cmdmod.py", line 650, in _run
    proc = salt.utils.timed_subprocess.TimedProc(cmd, **new_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/utils/timed_subprocess.py", line 77, in __init__
    kwargs['env'] = salt.utils.data.encode_dict(kwargs['env'])
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
TypeError: chugid_and_umask() takes exactly 2 arguments (3 given)
```

### Versions Report
Salt Minion Version Report:
```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Sep 26 2018, 18:42:22)
   python-gnupg: 0.3.9
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.8 
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-8-amd64
         system: Linux
        version: debian 9.8 
```

**Comment by garethgreenaway** [comment]
@do3meli Looks like an issue running the cron state and execution module.  Can you provide the state file that you're attempting to run in a highstate?  Thanks!

**Comment by do3meli** [comment]
@garethgreenaway it seems to be any cron.present state that is not working.
```
test_update_cronjob:
  cron.present:
    - name:  echo "gugugs" > /dev/null
    - identifier: test_cron_123
    - hour: 1
    - minute: random
```
an additional error i got on the master:
```
The minion function caused an exception: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1607, in _thread_return
    fp_.write(minion_instance.serial.dumps(sdata))
  File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 1330, in sls
    __context__['retcode'] = salt.defaults.exitcodes.EX_STATE_COMPILER_ERROR
AttributeError: 'module' object has no attribute 'EX_STATE_COMPILER_ERROR'
```

**Comment by snlnspc** [comment]
@garethgreenaway I'm running into the same type error in git.latest (and presumably cmd.run) on centos and arch systems as well.

git.latest on centos 7.6 failed on this state for two users, but the rest of the job was successful, including other git.latest states. the only difference being the successes were not rendered from jinja/pillar values, and are gitlab links with deploy tokens in them.

```yaml
user_salt-vim:
  git.latest:
    - name: https://github.com/saltstack/salt-vim.git
    - target: /home/user/.vim/bundle/salt-vim
    - user: user
    - branch: master
    - require:
        - user_pathogen
```

git.py trace:
```
Comment: An exception occurred in this state: Traceback (most recent call last):
            File "/usr/lib/python2.7/site-packages/salt/state.py", line 1913, in call
              if '__env__' not in inject_globals:
            File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1898, in wrapper
              )
            File "/usr/lib/python2.7/site-packages/salt/states/git.py", line 765, in latest
              output_encoding=output_encoding)
            File "/usr/lib/python2.7/site-packages/salt/modules/git.py", line 3932, in remote_refs
              output_encoding=output_encoding)['stdout']
            File "/usr/lib/python2.7/site-packages/salt/modules/git.py", line 386, in _git_run
              **kwargs)
            File "/usr/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 2069, in run_all
              **kwargs)
            File "/usr/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 650, in _run
              proc = salt.utils.timed_subprocess.TimedProc(cmd, **new_kwargs)
            File "/usr/lib/python2.7/site-packages/salt/utils/timed_subprocess.py", line 77, in __init__
              kwargs['env'] = salt.utils.data.encode_dict(kwargs['env'])
            File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
              errread, errwrite)
            File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
              raise child_exception
          TypeError: chugid_and_umask() takes exactly 2 arguments (3 given)
```

Version Report:
```yaml
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.26.3
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 2.7.5 (default, Oct 30 2018, 23:45:53)
   python-gnupg: 0.4.3
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.5.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core
```

on an unrelated Arch system (masterless minion, different states etc), I ran into the same TypeError error several times in rapid succession with two different traces. I'm not sure which states caused the issue, as the job died shortly after with no output, and the issue hasn't repeated after only one more run.

The first trace is identical to the git.py trace above.
cmd.py trace:
```
2019-03-18 08:40:52,677 [salt.state       :320 ][ERROR   ][1040] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 1913, in call
    if '__env__' not in inject_globals:
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1898, in wrapper
    )
  File "/usr/lib/python2.7/site-packages/salt/states/cmd.py", line 916, in run
    name, timeout=timeout, python_shell=True, **cmd_kwargs
  File "/usr/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 2069, in run_all
    **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 650, in _run
    proc = salt.utils.timed_subprocess.TimedProc(cmd, **new_kwargs)
  File "/usr/lib/python2.7/site-packages/salt/utils/timed_subprocess.py", line 77, in __init__
    kwargs['env'] = salt.utils.data.encode_dict(kwargs['env'])
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
TypeError: chugid_and_umask() takes exactly 2 arguments (3 given)
```

finally, this exception occurred and I was dumped back to the command line:

```
2019-03-18 08:41:07,771 [salt.log.setup   :1165][ERROR   ][1040] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'module' object has no attribute 'EX_STATE_FAILURE'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 410, in salt_call
    def salt_cp():
  File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 134, in run
    profiling_enabled = self.opts.get('profiling_enabled', False)
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 212, in call
    sys.stderr.write(
  File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 764, in apply_
  File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 1076, in highstate
    try:
  File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 108, in _set_retcode
    __context__['retcode'] = salt.defaults.exitcodes.EX_STATE_FAILURE
AttributeError: 'module' object has no attribute 'EX_STATE_FAILURE'
```
```yaml
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.12.2
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.27.7
        libnacl: Not Installed
       M2Crypto: 0.30.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 3.7.3
   pycryptodome: Not Installed
         pygit2: 0.27.3
         Python: 2.7.16 (default, Mar 11 2019, 18:59:25)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 18.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 5.1.1
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 5.0.2-arch1-1-ARCH
         system: Linux
        version: Not Installed
```

**Comment by EHJ-52n** [comment]
Hi,
I have the same error message with a `cmd.run` state.

Output:
```
----------
          ID: system-update_dist-upgrade
    Function: cmd.run
        Name: apt-get dist-upgrade --assume-yes
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1913, in call
                  if '__env__' not in inject_globals:
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1898, in wrapper
                  )
                File "/usr/lib/python2.7/dist-packages/salt/states/cmd.py", line 916, in run
                  name, timeout=timeout, python_shell=True, **cmd_kwargs
                File "/usr/lib/python2.7/dist-packages/salt/modules/cmdmod.py", line 2069, in run_all
                  **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/cmdmod.py", line 650, in _run
                  proc = salt.utils.timed_subprocess.TimedProc(cmd, **new_kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/utils/timed_subprocess.py", line 77, in __init__
                  kwargs['env'] = salt.utils.data.encode_dict(kwargs['env'])
                File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
                  errread, errwrite)
                File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
                  raise child_exception
              TypeError: chugid_and_umask() takes exactly 2 arguments (3 given)
     Started: 10:42:36.914918
    Duration: 57.191 ms
     Changes:   
----------
```

According state:
```
system-update_dist-upgrade:
  cmd.run:
    - name: apt-get dist-upgrade --assume-yes
    - runas: root
    - require:
      - system-update_package-updates
```

Version report minion:
```yaml
salt-minion --versions-report
/usr/lib/python2.7/dist-packages/salt/scripts.py:198: DeprecationWarning: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date.  Salt will drop support for Python 2.7 in the Sodium release or later.
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Sep 26 2018, 18:42:22)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.8 
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-8-amd64
         system: Linux
        version: debian 9.8
```

Version report master:
```yml
salt --versions-report
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 12 2018, 14:36:49)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-31-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

Just before the failing state, salt was updated on the minion:
```
              salt-common:
                  ----------
                  new:
                      2019.2.0+ds-1
                  old:
                      2018.3.3+ds-2
              salt-minion:
                  ----------
                  new:
                      2019.2.0+ds-1
                  old:
                      2018.3.3+ds-2
```

Hence, I think this is a problem with the `cmdmod.py`.
