### ISSUE TITLE
The salt.utils.vt.Terminal._recv (reached via the use_vt option of cmd.run) seems to attempt treat utf8 terminal output as well-formed ascii

### ISSUE THREAD

**Issue by arizvisa** [saltstack/salt#52011]
### Description of Issue/Question
This isn't a personal need for me or anything, but seems to be an oversight of some bugfix related to a unicode issue in the `salt.utils.vt` module. The issue is that the `_recv` function in the `salt.utils.vt.Terminal` class assumes that output from a process will be unicode that can be converted back to 7-bit ascii. This is not the case as the output from a process will be a byte-stream that can include non-printable terminal escape sequences which will either need to be stripped (via 'replace' or 'ignore' set for the `error` parameter to `.encode`) or to encode it back into its original utf-8 form.

Here's an exception from applying a state.
```
    cmd_|-Build the application image_|-/usr/bin/ssh -i "/media/root/home/core/.ssh/id_rsa" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -- 'core@localhost' sudo "IMAGEDIR=/var/lib/container" "TOOLSDIR=/opt/bin" -- "/opt/libexec/container/build.sh" "/srv/container/app-adobe-flash:0.1.acb"_|-run:
        ----------
        __id__:
            Build the application image
        __run_num__:
            1
        __sls__:
            application
        changes:
            ----------
        comment:
            An exception occurred in this state: Traceback (most recent call last):
              File "/usr/lib/python2.7/site-packages/salt/state.py", line 1926, in call
                **cdata['kwargs'])
              File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1844, in wrapper
                return f(*args, **kwargs)
              File "/usr/lib/python2.7/site-packages/salt/states/cmd.py", line 916, in run
                name, timeout=timeout, python_shell=True, **cmd_kwargs
              File "/usr/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 2010, in run_all
                **kwargs)
              File "/usr/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 767, in _run
                cstdout, cstderr = proc.recv()
              File "/usr/lib/python2.7/site-packages/salt/utils/vt.py", line 310, in recv
                return self._recv(maxsize)
              File "/usr/lib/python2.7/site-packages/salt/utils/vt.py", line 688, in _recv
                self.stream_stdout.write(stdout)
            UnicodeEncodeError: 'ascii' codec can't encode character u'\u2192' in position 79: ordinal not in range(128)
        duration:
            190607.364
        name:
            /usr/bin/ssh -i "/media/root/home/core/.ssh/id_rsa" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -- 'core@localhost' sudo "IMAGEDIR=/var/lib/container" "TOOLSDIR=/opt/bin" -- "/opt/libexec/container/build.sh" "/srv/container/app-adobe-flash:0.1.acb"
        result:
            False
        start_time:
            11:32:29.865443
```

### Setup
Simply prepare yourself to execute a program, you might be able to do this by using `cmd.run` to execute `printf $'\u2192\n'` via your bourne shell. This particular example should output a unicode arrow. The issue is in the `salt.utils.vt` module and so you'll need to set `use_vt` to `True` when doing this.

### Steps to Reproduce Issue
When executing the program, the `UnicodeEncodeError` exception will be raised due to the `Terminal._recv` function trying to call the `salt.utils.stringutils.to_str` function to convert the unicode to 7-bit ascii when it should be converting it to utf-8.

### Versions Report
2019.2.0

**Comment by arizvisa** [comment]
Workaround: Don't use `use_vt` when executing commands that don't emit 7-bit ascii.. Should be obvious, but in case it wasn't.

**Comment by arizvisa** [comment]
This issue has not been discussed, or even confirmed by a maintainer. Therefore it shouldn't be marked as stale...yet.

**Comment by dwoz** [comment]
Fix merged and shipped in a supported release. Closing per bulk triage. Reopen if this reproduces on a currently supported release (3006.x, 3007.x, 3008.x, master).
