### ISSUE TITLE
integration.modules.test_shadow.ShadowModuleTest.test_set_date

### ISSUE THREAD

**Issue by dwoz** [saltstack/salt#52048]
### Description of Issue/Question

Looks like this test is flaky but I see it failing in multiple places

```
integration.modules.test_shadow.ShadowModuleTest.test_set_date
--------------------------------------------------------------------------------
develop failed salt-fedora-28-py2, salt-fedora-28-py3
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
2017.7 failed salt-fedora-28-py3
--------------------------------------------------------------------------------

False is not true
................................................................................

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/support/helpers.py", line 123, in wrap
    return caller(cls)
  File "/tmp/kitchen/testing/tests/integration/modules/test_shadow.py", line 195, in test_set_date
    self.assertTrue(self.run_function('shadow.set_date', [self._test_user, '2016-08-19']))
AssertionError: False is not true
```

**Comment by dwoz** [comment]
Duplicate of #51926
