### ISSUE TITLE
unit.modules.test_vsphere

### ISSUE THREAD

**Issue by dwoz** [saltstack/salt#52047]
### Description of Issue/Question

```
unit.modules.test_vsphere.RemoveDatastoreTestCase.test_remove_datastore_call
--------------------------------------------------------------------------------
2018.3 failed salt-fedora-28-py3, salt-fedora-29-py3
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
develop failed salt-fedora-28-py3, salt-fedora-29-py3
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
2019.2 failed salt-fedora-28-py3
--------------------------------------------------------------------------------

name 'vim' is not defined
................................................................................

Traceback (most recent call last):
  File "/tmp/kitchen/testing/salt/utils/vmware.py", line 484, in disconnect
    Disconnect(service_instance)
NameError: name 'Disconnect' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/kitchen/testing/salt/modules/vsphere.py", line 384, in _gets_service_instance_via_proxy
    salt.utils.vmware.disconnect(local_service_instance)
  File "/tmp/kitchen/testing/salt/utils/vmware.py", line 485, in disconnect
    except vim.fault.NoPermission as exc:
NameError: name 'vim' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/kitchen/testing/salt/utils/vmware.py", line 484, in disconnect
    Disconnect(service_instance)
NameError: name 'Disconnect' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/unit/modules/test_vsphere.py", line 1376, in test_remove_datastore_call
    vsphere.remove_datastore(datastore='fake_ds')
  File "/tmp/kitchen/testing/salt/modules/vsphere.py", line 295, in __supports_proxies
    return fn(*args, **salt.utils.args.clean_kwargs(**kwargs))
  File "/tmp/kitchen/testing/salt/modules/vsphere.py", line 389, in _gets_service_instance_via_proxy
    salt.utils.vmware.disconnect(local_service_instance)
  File "/tmp/kitchen/testing/salt/utils/vmware.py", line 485, in disconnect
    except vim.fault.NoPermission as exc:
NameError: name 'vim' is not defined
```

**Comment by KChandrashekhar** [comment]
Decided to work on the fix in 2019.2.2

**Comment by KChandrashekhar** [comment]
> Decided to work on the fix in 2019.2.2. Deemed not a blocker as its failing only on Fedora

Adding this back as a blocker.

**Comment by Ch3LL** [comment]
re-adding as 2019.2.1 blocker

**Comment by Ch3LL** [comment]
this is now passing here:

https://jenkinsci.saltstack.com/job/2019.2.1/view/Python3/job/salt-fedora-29-py3/38/

There was an issue with fedora conflicting between the urlib3 system and pip packages. When attempting to import urllib3 there was an importerror and said the module did not exist. When i uninstalled the system urllib3 package the test would pass. The test is passing now because of the transition to using nox which installs the dependencies with pip.
