### ISSUE TITLE
unit.fileserver.test_gitfs.GitPythonTest

### ISSUE THREAD

**Issue by dwoz** [saltstack/salt#52055]
```
setUpClass (unit.fileserver.test_gitfs.GitPythonTest)
--------------------------------------------------------------------------------
develop failed salt-windows-2019-py2
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
environment can only contain strings
................................................................................

Traceback (most recent call last):
  File "c:\users\admini~1\appdata\local\temp\kitchen\testing\tests\unit\fileserver\test_gitfs.py", line 424, in setUpClass
    repo.index.commit('Test')
  File "C:\Python27\lib\site-packages\git\index\base.py", line 950, in commit
    author_date=author_date, commit_date=commit_date)
  File "C:\Python27\lib\site-packages\git\objects\commit.py", line 397, in create_from_tree
    master = git.refs.Head.create(repo, repo.head.ref, new_commit, logmsg="commit (initial): %s" % message)
  File "C:\Python27\lib\site-packages\git\refs\symbolic.py", line 546, in create
    return cls._create(repo, path, cls._resolve_ref_on_create, reference, force, logmsg)
  File "C:\Python27\lib\site-packages\git\refs\symbolic.py", line 497, in _create
    target = repo.rev_parse(str(reference))
  File "C:\Python27\lib\site-packages\git\repo\fun.py", line 334, in rev_parse
    obj = name_to_object(repo, rev)
  File "C:\Python27\lib\site-packages\git\repo\fun.py", line 150, in name_to_object
    return Object.new_from_sha(repo, hex_to_bin(hexsha))
  File "C:\Python27\lib\site-packages\git\objects\base.py", line 64, in new_from_sha
    oinfo = repo.odb.info(sha1)
  File "C:\Python27\lib\site-packages\git\db.py", line 37, in info
    hexsha, typename, size = self._git.get_object_header(bin_to_hex(sha))
  File "C:\Python27\lib\site-packages\git\cmd.py", line 1076, in get_object_header
    cmd = self._get_persistent_cmd("cat_file_header", "cat_file", batch_check=True)
  File "C:\Python27\lib\site-packages\git\cmd.py", line 1059, in _get_persistent_cmd
    cmd = self._call_process(cmd_name, *args, **options)
  File "C:\Python27\lib\site-packages\git\cmd.py", line 1014, in _call_process
    return self.execute(call, **exec_kwargs)
  File "C:\Python27\lib\site-packages\git\cmd.py", line 735, in execute
    **subprocess_kwargs
  File "C:\Python27\lib\subprocess.py", line 394, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 644, in _execute_child
    startupinfo)
TypeError: environment can only contain strings
```

**Comment by twangboy** [comment]
No longer failing
