### ISSUE TITLE
integration.states.test_user.UserTest.test_user_present_gid_from_name_default

### ISSUE THREAD

**Issue by dwoz** [saltstack/salt#52058]
```
integration.states.test_user.UserTest.test_user_present_gid_from_name_default
--------------------------------------------------------------------------------
2017.7.9 failed salt-mac-sierra-py2
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Failed to get result. Salt Returned: ['The function "state.single" is running as PID 15027 and was started at 2019, Mar 07 05:49:28.309172 with jid 20190307054928309172',  "[TEST SUITE ENFORCED]A running state.single was found causing a state lock. Job details: '{}'  Killing Job Returned: ''[/TEST SUITE ENFORCED]",  "[TEST SUITE ENFORCED]A running state.single was found causing a state lock. Job details: '{}'  Killing Job Returned: ''[/TEST SUITE ENFORCED]"]
................................................................................

Traceback (most recent call last):
  File "/testing/tests/support/helpers.py", line 1048, in decorator
    return func(cls, grains=cls.run_function('grains.items'))
  File "/testing/tests/integration/states/test_user.py", line 151, in test_user_present_gid_from_name_default
    self.assertSaltTrueReturn(ret_user_present)
  File "/testing/tests/support/mixins.py", line 559, in assertSaltTrueReturn
    pprint.pformat(ret)
AssertionError: Failed to get result. Salt Returned:
['The function "state.single" is running as PID 15027 and was started at 2019, Mar 07 05:49:28.309172 with jid 20190307054928309172',
 "[TEST SUITE ENFORCED]A running state.single was found causing a state lock. Job details: '{}'  Killing Job Returned: ''[/TEST SUITE ENFORCED]",
 "[TEST SUITE ENFORCED]A running state.single was found causing a state lock. Job details: '{}'  Killing Job Returned: ''[/TEST SUITE ENFORCED]"]
```

**Comment by KChandrashekhar** [comment]
It's been decided not to fix this.
