### ISSUE TITLE
unit.modules.test_btrfs.BtrfsTestCase.test_subvolume_create

### ISSUE THREAD

**Issue by dwoz** [saltstack/salt#52062]
```
unit.modules.test_btrfs.BtrfsTestCase.test_subvolume_create
--------------------------------------------------------------------------------
develop failed salt-windows-2019-py2
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Expected call: mock([u'btrfs', u'subvolume', u'create', u'/mnt/var']) Actual call: mock([u'btrfs', u'subvolume', u'create', u'/mnt\\var'])
................................................................................

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\mock\mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "c:\users\admini~1\appdata\local\temp\kitchen\testing\tests\unit\modules\test_btrfs.py", line 418, in test_subvolume_create
    ['btrfs', 'subvolume', 'create', '/mnt/var'])
  File "C:\Python27\lib\site-packages\mock\mock.py", line 937, in assert_called_with
    six.raise_from(AssertionError(_error_message(cause)), cause)
  File "C:\Python27\lib\site-packages\six.py", line 737, in raise_from
    raise value
AssertionError: Expected call: mock([u'btrfs', u'subvolume', u'create', u'/mnt/var'])
Actual call: mock([u'btrfs', u'subvolume', u'create', u'/mnt\\var'])
```

**Comment by waynew** [comment]
develop failed [salt-windows-2016-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2016-py2/19/testReport/junit/unit.modules.test_btrfs/BtrfsTestCase/test_subvolume_create), [salt-windows-2016-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2016-py3/19/testReport/junit/unit.modules.test_btrfs/BtrfsTestCase/test_subvolume_create), [salt-windows-2019-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2019-py2/66/testReport/junit/unit.modules.test_btrfs/BtrfsTestCase/test_subvolume_create), [salt-windows-2019-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2019-py3/60/testReport/junit/unit.modules.test_btrfs/BtrfsTestCase/test_subvolume_create)
---

expected call not found. Expected: mock(['btrfs', 'subvolume', 'create', '/mnt/var']) Actual: mock(['btrfs', 'subvolume', 'create', '/mnt\\var'])

```

Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\mock\mock.py", line 1329, in patched
    return func(*args, **keywargs)
  File "c:\users\admini~1\appdata\local\temp\kitchen\testing\tests\unit\modules\test_btrfs.py", line 418, in test_subvolume_create
    ['btrfs', 'subvolume', 'create', '/mnt/var'])
  File "C:\Python35\lib\site-packages\mock\mock.py", line 943, in assert_called_with
    six.raise_from(AssertionError(_error_message(cause)), cause)
  File "<string>", line 3, in raise_from
AssertionError: expected call not found.
Expected: mock(['btrfs', 'subvolume', 'create', '/mnt/var'])
Actual: mock(['btrfs', 'subvolume', 'create', '/mnt\\var'])
		
```

Looks like this is still failing 🤷‍♂

**Comment by twangboy** [comment]
Waiting for the above PR to be merged.... should fix this
