### ISSUE TITLE
integration.modules.test_pip.PipModuleTest.test_pip_install_multiple_editables_and_pkgs

### ISSUE THREAD

**Issue by dwoz** [saltstack/salt#52061]
```
integration.modules.test_pip.PipModuleTest.test_pip_install_multiple_editables_and_pkgs
--------------------------------------------------------------------------------
develop failed salt-centos-7-py3, salt-centos-7-py3-m2crypto, salt-centos-7-py3-transport, salt-fedora-28-py3
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
string indices must be integers
................................................................................

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/modules/test_pip.py", line 437, in test_pip_install_multiple_editables_and_pkgs
    if self._check_download_error(ret['stdout']):
TypeError: string indices must be integers
```

**Comment by Akm0d** [comment]
I'm also seeing an error in this module:
``` 
bashTraceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/modules/test_pip.py", line 440, in test_pip_install_multiple_editables_and_pkgs
    self.assertEqual(ret['retcode'], 0)
AssertionError: 1 != 0
```
