### ISSUE TITLE
unittest.loader._FailedTest.unit.runners.test_vault

### ISSUE THREAD

**Issue by dwoz** [saltstack/salt#52066]
```
unittest.loader._FailedTest.unit.runners.test_vault
--------------------------------------------------------------------------------
develop failed salt-fedora-28-py3, salt-fedora-29-py3
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Failed to import test module: unit.runners.test_vault Traceback (most recent call last):   File "/usr/lib64/python3.6/unittest/loader.py", line 428, in _find_test_path     module = self._get_module_from_name(name)   File "/usr/lib64/python3.6/unittest/loader.py", line 369, in _get_module_from_name     __import__(name)   File "/tmp/kitchen/testing/tests/unit/runners/test_vault.py", line 25, in <module>     import salt.runners.vault as vault   File "/tmp/kitchen/testing/salt/runners/vault.py", line 16, in <module>     import requests   File "/usr/lib/python3.6/site-packages/requests/__init__.py", line 43, in <module>     import urllib3   File "/usr/lib/python3.6/site-packages/urllib3/__init__.py", line 8, in <module>     from .connectionpool import (   File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 11, in <module>     from .exceptions import (   File "/usr/lib/python3.6/site-packages/urllib3/exceptions.py", line 2, in <module>     from .packages.six.moves.http_client import ( ModuleNotFoundError: No module named 'urllib3.packages.six'
................................................................................

ImportError: Failed to import test module: unit.runners.test_vault
Traceback (most recent call last):
  File "/usr/lib64/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib64/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/tmp/kitchen/testing/tests/unit/runners/test_vault.py", line 25, in <module>
    import salt.runners.vault as vault
  File "/tmp/kitchen/testing/salt/runners/vault.py", line 16, in <module>
    import requests
  File "/usr/lib/python3.6/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/lib/python3.6/site-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/usr/lib/python3.6/site-packages/urllib3/exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import (
ModuleNotFoundError: No module named 'urllib3.packages.six'

```

**Comment by garethgreenaway** [comment]
Fixed with https://github.com/saltstack/salt-jenkins/pull/1351
