### ISSUE TITLE
integration.states.test_pip_state.PipStateTest.test_pip_installed_specific_env

### ISSUE THREAD

**Issue by dwoz** [saltstack/salt#52063]
```
integration.states.test_pip_state.PipStateTest.test_pip_installed_specific_env
--------------------------------------------------------------------------------
develop failed salt-fedora-28-py3
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
"'salt://prod-env-requirements.txt' not found" not found in "Error installing '': Could not find a `pip` binary"
................................................................................

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/states/test_pip_state.py", line 444, in test_pip_installed_specific_env
    "'salt://prod-env-requirements.txt' not found", ret
  File "/tmp/kitchen/testing/tests/support/mixins.py", line 617, in assertInSaltComment
    self.assertIn(in_comment, saltret)
AssertionError: "'salt://prod-env-requirements.txt' not found" not found in "Error installing '': Could not find a `pip` binary"
```

**Comment by waynew** [comment]
Also failing on Ubuntu 18.04

develop failed [salt-ubuntu-1804-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1804-py3/203/testReport/junit/integration.states.test_pip_state/PipStateTest/test_pip_installed_specific_env)
---

"'salt://prod-env-requirements.txt' not found" not found in "Error installing '': Could not find a `pip` binary"

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/states/test_pip_state.py", line 440, in test_pip_installed_specific_env
    "'salt://prod-env-requirements.txt' not found", ret
  File "/tmp/kitchen/testing/tests/support/mixins.py", line 615, in assertInSaltComment
    self.assertIn(in_comment, saltret)
AssertionError: "'salt://prod-env-requirements.txt' not found" not found in "Error installing '': Could not find a `pip` binary"
		
```
