### ISSUE TITLE
unit.modules.test_ssh.SSHAuthKeyTestCase.test_recv_known_hosts_hashed_shoud_be_findable_by_ssh_keygen

### ISSUE THREAD

**Issue by dwoz** [saltstack/salt#52075]
```
unit.modules.test_ssh.SSHAuthKeyTestCase.test_recv_known_hosts_hashed_shoud_be_findable_by_ssh_keygen
--------------------------------------------------------------------------------
develop failed salt-windows-2019-py2
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Command '[u'ssh-keygen', u'-f', 'c:\\users\\admini~1\\appdata\\local\\temp\\tmp1dtlqx', u'-F', u'[example.com]:12345']' returned non-zero exit status 255
................................................................................

Traceback (most recent call last):
  File "c:\users\admini~1\appdata\local\temp\kitchen\testing\tests\unit\modules\test_ssh.py", line 193, in test_recv_known_hosts_hashed_shoud_be_findable_by_ssh_keygen
    '[{hostname}]:{port}'.format(hostname=hostname, port=port),
  File "C:\Python27\lib\subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '[u'ssh-keygen', u'-f', 'c:\\users\\admini~1\\appdata\\local\\temp\\tmp1dtlqx', u'-F', u'[example.com]:12345']' returned non-zero exit status 255
```

**Comment by twangboy** [comment]
No longer failing

**Comment by twangboy** [comment]
Failing on develop:
May 21, 2019 5:42:00 PM - https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2019-py2/95/
