### ISSUE TITLE
unittest.loader._FailedTest.unit.modules.test_libcloud_storage

### ISSUE THREAD

**Issue by dwoz** [saltstack/salt#52082]
```
unittest.loader._FailedTest.unit.modules.test_libcloud_storage
--------------------------------------------------------------------------------
develop failed salt-fedora-28-py3, salt-fedora-29-py3
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Failed to import test module: unit.modules.test_libcloud_storage Traceback (most recent call last):   File "/usr/lib64/python3.6/unittest/loader.py", line 428, in _find_test_path     module = self._get_module_from_name(name)   File "/usr/lib64/python3.6/unittest/loader.py", line 369, in _get_module_from_name     __import__(name)   File "/tmp/kitchen/testing/tests/unit/modules/test_libcloud_storage.py", line 20, in <module>     from libcloud.storage.base import Container, BaseDriver, Object   File "/usr/local/lib/python3.6/site-packages/libcloud/storage/base.py", line 32, in <module>     from libcloud.common.base import ConnectionUserAndKey, BaseDriver   File "/usr/local/lib/python3.6/site-packages/libcloud/common/base.py", line 27, in <module>     import requests   File "/usr/lib/python3.6/site-packages/requests/__init__.py", line 43, in <module>     import urllib3   File "/usr/lib/python3.6/site-packages/urllib3/__init__.py", line 8, in <module>     from .connectionpool import (   File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 11, in <module>     from .exceptions import (   File "/usr/lib/python3.6/site-packages/urllib3/exceptions.py", line 2, in <module>     from .packages.six.moves.http_client import ( ModuleNotFoundError: No module named 'urllib3.packages.six'
................................................................................

ImportError: Failed to import test module: unit.modules.test_libcloud_storage
Traceback (most recent call last):
  File "/usr/lib64/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib64/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/tmp/kitchen/testing/tests/unit/modules/test_libcloud_storage.py", line 20, in <module>
    from libcloud.storage.base import Container, BaseDriver, Object
  File "/usr/local/lib/python3.6/site-packages/libcloud/storage/base.py", line 32, in <module>
    from libcloud.common.base import ConnectionUserAndKey, BaseDriver
  File "/usr/local/lib/python3.6/site-packages/libcloud/common/base.py", line 27, in <module>
    import requests
  File "/usr/lib/python3.6/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/lib/python3.6/site-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/usr/lib/python3.6/site-packages/urllib3/exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import (
ModuleNotFoundError: No module named 'urllib3.packages.six'
```

**Comment by garethgreenaway** [comment]
Fixed with saltstack/salt-jenkins#1351

**Comment by waynew** [comment]
Has this been merged forward yet? It's also causing these failures on 2019.2.1:

- unittest.loader._FailedTest.unit.modules.test_libcloud_storage
- unittest.loader._FailedTest.unit.modules.test_libcloud_compute
- unittest.loader._FailedTest.unit.states.test_grafana_datasource
- unittest.loader._FailedTest.unit.modules.test_libcloud_loadbalancer
- unit.cloud.clouds.test_dimensiondata.DimensionDataTestCase.test_avail_sizes
- unittest.loader._FailedTest.unit.runners.test_vault

**Comment by waynew** [comment]
Same tests are also still failing on develop
