### ISSUE TITLE
integration.pillar.test_git_pillar.TestGitPythonAuthenticatedHTTP.test_includes_enabled_solves___env___with_mountpoint

### ISSUE THREAD

**Issue by dwoz** [saltstack/salt#52083]
```
integration.pillar.test_git_pillar.TestGitPythonAuthenticatedHTTP.test_includes_enabled_solves___env___with_mountpoint
--------------------------------------------------------------------------------
develop failed salt-fedora-28-py3
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Cmd('git') failed due to: exit code(128)   cmdline: git fetch -v origin   stderr: 'fatal: unable to access 'http://gitpillaruser:saltrules@127.0.0.1:50241/extra_repo.git/': The requested URL returned error: 502'
................................................................................

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/pillar/test_git_pillar.py", line 382, in test_includes_enabled_solves___env___with_mountpoint
    ''')
  File "/tmp/kitchen/testing/tests/support/gitfs.py", line 353, in get_pillar
    *ext_pillar_opts['ext_pillar'][0]['git']
  File "/tmp/kitchen/testing/salt/pillar/git_pillar.py", line 413, in ext_pillar
    global_only=GLOBAL_ONLY)
  File "/tmp/kitchen/testing/salt/utils/gitfs.py", line 2135, in __init__
    global_only)
  File "/tmp/kitchen/testing/salt/utils/gitfs.py", line 2201, in init_remotes
    repo_obj.fetch()
  File "/tmp/kitchen/testing/salt/utils/gitfs.py", line 767, in fetch
    return self._fetch()
  File "/tmp/kitchen/testing/salt/utils/gitfs.py", line 1253, in _fetch
    fetch_results = origin.fetch()
  File "/usr/local/lib/python3.6/site-packages/git/remote.py", line 789, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress)
  File "/usr/local/lib/python3.6/site-packages/git/remote.py", line 675, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "/usr/local/lib/python3.6/site-packages/git/cmd.py", line 415, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v origin
  stderr: 'fatal: unable to access 'http://gitpillaruser:saltrules@127.0.0.1:50241/extra_repo.git/': The requested URL returned error: 502'
```

**Comment by garethgreenaway** [comment]
https://github.com/saltstack/salt-jenkins/pull/1352
