### ISSUE TITLE
integration.modules.test_grains.GrainsAppendTestCase.test_grains_append_val_is_list

### ISSUE THREAD

**Issue by dwoz** [saltstack/salt#52089]
```
integration.modules.test_grains.GrainsAppendTestCase.test_grains_append_val_is_list
--------------------------------------------------------------------------------
2017.7.9 failed salt-mac-highsierra-py3
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Lists differ: ['my-[20 chars]n-val', 'my-grain-val-2', 'my-grain-val', 'my-[76 chars]l-2'] != ['my-[20 chars]n-val-2']  First differing element 1: 'my-grain-val' 'my-grain-val-2'  First list contains 7 additional elements. First extra element 2: 'my-grain-val-2'  + ['my-grain-val', 'my-grain-val-2'] - ['my-grain-val', -  'my-grain-val', -  'my-grain-val-2', -  'my-grain-val', -  'my-grain-val-2', -  'my-grain-val', -  'my-grain-val-2', -  'my-grain-val', -  'my-grain-val-2']
................................................................................

Traceback (most recent call last):
  File "/testing/tests/support/helpers.py", line 206, in wrap
    raise exc
  File "/testing/tests/support/helpers.py", line 203, in wrap
    return caller(cls)
  File "/testing/tests/integration/modules/test_grains.py", line 191, in test_grains_append_val_is_list
    self.assertEqual(ret[self.GRAIN_KEY], [self.GRAIN_VAL, second_grain])
AssertionError: Lists differ: ['my-[20 chars]n-val', 'my-grain-val-2', 'my-grain-val', 'my-[76 chars]l-2'] != ['my-[20 chars]n-val-2']

First differing element 1:
'my-grain-val'
'my-grain-val-2'

First list contains 7 additional elements.
First extra element 2:
'my-grain-val-2'

+ ['my-grain-val', 'my-grain-val-2']
- ['my-grain-val',
-  'my-grain-val',
-  'my-grain-val-2',
-  'my-grain-val',
-  'my-grain-val-2',
-  'my-grain-val',
-  'my-grain-val-2',
-  'my-grain-val',
-  'my-grain-val-2']
```

**Comment by KChandrashekhar** [comment]
It's been decide not to fix this as this seems like a flaky test
