### ISSUE TITLE
integration.modules.test_mac_power.MacPowerModuleTest.test_computer_sleep

### ISSUE THREAD

**Issue by dwoz** [saltstack/salt#52097]
This one may be flaky

```
integration.modules.test_mac_power.MacPowerModuleTest.test_computer_sleep
--------------------------------------------------------------------------------
2017.7 failed salt-mac-highsierra-py3
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
False is not true
................................................................................

Traceback (most recent call last):
  File "/testing/tests/support/helpers.py", line 206, in wrap
    raise exc
  File "/testing/tests/support/helpers.py", line 203, in wrap
    return caller(cls)
  File "/testing/tests/support/helpers.py", line 123, in wrap
    return caller(cls)
  File "/testing/tests/integration/modules/test_mac_power.py", line 51, in test_computer_sleep
    self.assertTrue(self.run_function('power.set_computer_sleep', [90]))
AssertionError: False is not true
```

**Comment by KChandrashekhar** [comment]
It's been decided not to fix this.
