### ISSUE TITLE
unittest.loader._FailedTest.unit.modules.test_libcloud_loadbalancer

### ISSUE THREAD

**Issue by dwoz** [saltstack/salt#52090]
```
unittest.loader._FailedTest.unit.modules.test_libcloud_loadbalancer
--------------------------------------------------------------------------------
develop failed salt-fedora-28-py3, salt-fedora-29-py3
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Failed to import test module: unit.modules.test_libcloud_loadbalancer Traceback (most recent call last):   File "/usr/lib64/python3.6/unittest/loader.py", line 428, in _find_test_path     module = self._get_module_from_name(name)   File "/usr/lib64/python3.6/unittest/loader.py", line 369, in _get_module_from_name     __import__(name)   File "/tmp/kitchen/testing/tests/unit/modules/test_libcloud_loadbalancer.py", line 20, in <module>     from libcloud.loadbalancer.base import BaseDriver, LoadBalancer, Algorithm, Member   File "/usr/local/lib/python3.6/site-packages/libcloud/loadbalancer/base.py", line 16, in <module>     from libcloud.common.base import ConnectionKey, BaseDriver   File "/usr/local/lib/python3.6/site-packages/libcloud/common/base.py", line 27, in <module>     import requests   File "/usr/lib/python3.6/site-packages/requests/__init__.py", line 43, in <module>     import urllib3   File "/usr/lib/python3.6/site-packages/urllib3/__init__.py", line 8, in <module>     from .connectionpool import (   File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 11, in <module>     from .exceptions import (   File "/usr/lib/python3.6/site-packages/urllib3/exceptions.py", line 2, in <module>     from .packages.six.moves.http_client import ( ModuleNotFoundError: No module named 'urllib3.packages.six'
................................................................................

ImportError: Failed to import test module: unit.modules.test_libcloud_loadbalancer
Traceback (most recent call last):
  File "/usr/lib64/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib64/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/tmp/kitchen/testing/tests/unit/modules/test_libcloud_loadbalancer.py", line 20, in <module>
    from libcloud.loadbalancer.base import BaseDriver, LoadBalancer, Algorithm, Member
  File "/usr/local/lib/python3.6/site-packages/libcloud/loadbalancer/base.py", line 16, in <module>
    from libcloud.common.base import ConnectionKey, BaseDriver
  File "/usr/local/lib/python3.6/site-packages/libcloud/common/base.py", line 27, in <module>
    import requests
  File "/usr/lib/python3.6/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/lib/python3.6/site-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/usr/lib/python3.6/site-packages/urllib3/exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import (
ModuleNotFoundError: No module named 'urllib3.packages.six'
```

**Comment by garethgreenaway** [comment]
Fixed with saltstack/salt-jenkins#1351
