### ISSUE TITLE
integration.states.test_pip_state.PipStateTest.test_pip_installed_removed_venv

### ISSUE THREAD

**Issue by dwoz** [saltstack/salt#52095]
```
integration.states.test_pip_state.PipStateTest.test_pip_installed_removed_venv
--------------------------------------------------------------------------------
develop failed salt-fedora-28-py3
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 != 0
................................................................................

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/states/test_pip_state.py", line 87, in test_pip_installed_removed_venv
    with VirtualEnv(self, venv_dir):
  File "/tmp/kitchen/testing/tests/integration/states/test_pip_state.py", line 60, in __enter__
    self.test.assertEqual(ret['retcode'], 0)
AssertionError: 1 != 0
```

**Comment by waynew** [comment]
Also failing on Ubuntu 18.04

develop failed [salt-ubuntu-1804-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1804-py3/203/testReport/junit/integration.states.test_pip_state/PipStateTest/test_pip_installed_removed_venv)
---

1 != 0

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/states/test_pip_state.py", line 87, in test_pip_installed_removed_venv
    with VirtualEnv(self, venv_dir):
  File "/tmp/kitchen/testing/tests/integration/states/test_pip_state.py", line 60, in __enter__
    self.test.assertEqual(ret['retcode'], 0)
AssertionError: 1 != 0
		
```

**Comment by waynew** [comment]
Looks like the same failure might be here:

develop failed [salt-ubuntu-1804-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1804-py3/203/testReport/junit/integration.states.test_pip_state/PipStateTest/test_pip_installed_errors)
---

1 != 0

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/states/test_pip_state.py", line 115, in test_pip_installed_errors
    self.assertEqual(ret['retcode'], 0)
AssertionError: 1 != 0
		
```

**Comment by waynew** [comment]
Failure is the same in:

- integration.states.test_pip_state.PipStateTest.test_issue_2087_missing_pip
- integration.states.test_pip_state.PipStateTest.test_issue_6833_pip_upgrade_pip

so those are probably related

**Comment by twangboy** [comment]
Neon failed on `salt-amazon-1-py2, salt-debian-9-py2, salt-debian-9-py3, salt-windows-2016-py2, salt-windows-2019-py2`
