### ISSUE TITLE
unit.utils.test_ssdp.SSDPFactoryTestCase.test_datagram_signature_correct_timestamp_reply

### ISSUE THREAD

**Issue by dwoz** [saltstack/salt#52104]
```
unit.utils.test_ssdp.SSDPFactoryTestCase.test_datagram_signature_correct_timestamp_reply
--------------------------------------------------------------------------------
2019.2 failed salt-mac-sierra-py3
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[Errno 8] nodename nor servname provided, or not known
................................................................................

Traceback (most recent call last):
  File "/testing/tests/unit/utils/test_ssdp.py", line 290, in test_datagram_signature_correct_timestamp_reply
    factory = ssdp.SSDPFactory()
  File "/testing/salt/utils/ssdp.py", line 121, in __init__
    self.my_ip = socket.gethostbyname(socket.gethostname())
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```

**Comment by garethgreenaway** [comment]
Forcing the tests to run on a different Mac OS and they no longer failed consistently.  Marking this one as Fixed.
