### ISSUE TITLE
unit.templates.test_jinja.TestCustomExtensions.test_http_query

### ISSUE THREAD

**Issue by dwoz** [saltstack/salt#52107]
```
unit.templates.test_jinja.TestCustomExtensions.test_http_query
--------------------------------------------------------------------------------
2017.7 failed salt-fedora-28-py3
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'body'
................................................................................

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/support/helpers.py", line 206, in wrap
    raise exc
  File "/tmp/kitchen/testing/tests/support/helpers.py", line 203, in wrap
    return caller(cls)
  File "/tmp/kitchen/testing/tests/unit/templates/test_jinja.py", line 949, in test_http_query
    self.assertIsInstance(dict_reply['body'], six.string_types, 'Failed with backend: {}'.format(backend))
KeyError: 'body'

```

**Comment by KChandrashekhar** [comment]
Won't be fixed as this is failing on EOL Fedora
