### ISSUE TITLE
[states/jinja] mine.get in jinja in states fails on expr_form targetting 

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#52110]
### Description of Issue/Question

targetting with expr_form (for pillar targeting in salt calls in states)

### Setup

In states file basepkgs/bashrc.sls : 

```
{% set redis_master = salt['mine.get']('role:redis', fun='network.interface_ip', expr_form='pillar').values() %}    
```

### Steps to Reproduce Issue

```
    Rendering SLS 'base:basepkgs.bashrc' failed: Jinja error: get() got an unexpected keyword argument 'expr_form'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 392, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 1, in top-level template code
TypeError: get() got an unexpected keyword argument 'expr_form'

; line 1

---
{% set redis_master = salt['mine.get']('role:redis', fun='network.interface_ip', expr_form='pillar').values() %}    <======================
```

### Versions Report

This used to work on version 2018.x (and previous if I recall correctly)

```
$ sudo salt-call --versions-report
sudo: unable to resolve host integration-nemo-web1
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: 1.9.0
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Sep 26 2018, 18:42:22)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.8 
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-8-amd64
         system: Linux
        version: debian 9.8 
```

**Comment by Ch3LL** [comment]
https://docs.saltstack.com/en/develop/topics/releases/2019.2.0.html#api-removed-arguments

`expr_form` has been deprecated in favor for `tgt_type`

**Comment by arthurlogilab** [comment]
@Ch3LL thanks for pointing that out. I'll go and change my code.
