### ISSUE TITLE
type hints not supported

### ISSUE THREAD

**Issue by kiemlicz** [saltstack/salt#52140]
### Description of Issue/Question
It is impossible to run Execution Module which contains type hints from CLI  
Is there any workaround available now?

### Setup
Create any custom Execution Module with type hints, e.g. `_modules/my.py`:  
```
def info(ip: str, port: int):
    return {}
```

### Steps to Reproduce Issue
Run from CLI (sync_all first):
`salt '*' my.info 127.0.0.1 11111`
It will fail with:
```
salt-minion-mnwlq:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/salt/minion.py", line 1641, in _thread_return
        data)
      File "/usr/lib/python3/dist-packages/salt/minion.py", line 321, in load_args_and_kwargs
        argspec = salt.utils.args.get_function_argspec(func)
      File "/usr/lib/python3/dist-packages/salt/utils/args.py", line 271, in get_function_argspec
        aspec = _getargspec(func)  # pylint: disable=redefined-variable-type
      File "/usr/lib/python3/dist-packages/salt/utils/args.py", line 231, in _getargspec
        raise ValueError('Function has keyword-only arguments or annotations'
    ValueError: Function has keyword-only arguments or annotations, use getfullargspec() API which can support them
ERROR: Minions returned with non-zero exit code
```

### Versions Report
```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.12.2
       cherrypy: unknown
       dateutil: 2.8.0
      docker-py: 1.10.6
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.27.4
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.27.4
         Python: 3.5.3 (default, Sep 27 2018, 17:25:39)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.8
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.9.0-7-amd64
         system: Linux
        version: debian 9.8
```

**Comment by garethgreenaway** [comment]
@kiemlicz Thanks for the report.  I'm marking this as a feature request as it would be a new addition.

**Comment by kiemlicz** [comment]
Could you please add some labels that prevent this bot from closing tickets, it is a bit annoying.

**Comment by nschoonm** [comment]
+1

**Comment by frebib** [comment]
This was fixed in 3005rc1 https://github.com/saltstack/salt/commit/21f0644fa25768891b0d1a88be964d37d3dda06e
