### ISSUE TITLE
[Py3] gitfs throws "There is no current event loop in thread 'Thread-1'"

### ISSUE THREAD

**Issue by kyrias** [saltstack/salt#52188]
### Description of Issue/Question

I just tried migrating the Arch Linux package to Python 3, but when updating the gitfs fileserver cache, it throws the following exception:

```
Mar 14 18:59:12 theos.kyriasis.com salt-master[1307]: [ERROR   ] Uncaught exception while updating gitfs fileserver cache
Mar 14 18:59:12 theos.kyriasis.com salt-master[1307]: Traceback (most recent call last):
Mar 14 18:59:12 theos.kyriasis.com salt-master[1307]:   File "/usr/lib/python3.7/site-packages/salt/master.py", line 459, in _do_update
Mar 14 18:59:12 theos.kyriasis.com salt-master[1307]:     update_func(*args)
Mar 14 18:59:12 theos.kyriasis.com salt-master[1307]:   File "/usr/lib/python3.7/site-packages/salt/fileserver/gitfs.py", line 133, in update
Mar 14 18:59:12 theos.kyriasis.com salt-master[1307]:     _gitfs().update(remotes)
Mar 14 18:59:12 theos.kyriasis.com salt-master[1307]:   File "/usr/lib/python3.7/site-packages/salt/fileserver/gitfs.py", line 84, in _gitfs
Mar 14 18:59:12 theos.kyriasis.com salt-master[1307]:     init_remotes=init_remotes)
Mar 14 18:59:12 theos.kyriasis.com salt-master[1307]:   File "/usr/lib/python3.7/site-packages/salt/utils/gitfs.py", line 2662, in __new__
Mar 14 18:59:12 theos.kyriasis.com salt-master[1307]:     io_loop = tornado.ioloop.IOLoop.current() if init_remotes else None
Mar 14 18:59:12 theos.kyriasis.com salt-master[1307]:   File "/usr/lib/python3.7/site-packages/tornado/ioloop.py", line 282, in current
Mar 14 18:59:12 theos.kyriasis.com salt-master[1307]:     loop = asyncio.get_event_loop()
Mar 14 18:59:12 theos.kyriasis.com salt-master[1307]:   File "/usr/lib/python3.7/asyncio/events.py", line 644, in get_event_loop
Mar 14 18:59:12 theos.kyriasis.com salt-master[1307]:     % threading.current_thread().name)
Mar 14 18:59:12 theos.kyriasis.com salt-master[1307]: RuntimeError: There is no current event loop in thread 'Thread-1'.
```

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

Only relevant part of the config is that there are gitfs remotes specified:

```
gitfs_remotes:                                                                                      
   - git://github.com/yabok/nginx-formula.git                                                       
   - git://github.com/kyrias/opensmtpd-formula.git:                                                 
     - base: wip
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

1. Build Arch salt package using Python 3
2. Start salt master

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.12.2
       cherrypy: Not Installed
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.27.7
        libnacl: Not Installed
       M2Crypto: 0.30.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 3.7.3
   pycryptodome: 3.7.3
         pygit2: 0.27.3
         Python: 3.7.2 (default, Jan 10 2019, 23:51:51)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 18.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 5.1.1
            ZMQ: 4.3.1
 
System Versions:
           dist: arch  
         locale: UTF-8
        machine: x86_64
        release: 4.20.8-arch1-1-ARCH
         system: Linux
        version: arch 
```

**Comment by kyrias** [comment]
This appears to be due to a combination of the changes in 958c99b87cf0c3af34e9f8353fc75ba08d1fcd63 making the updates multithreaded, and tornado migrating to being based on the asyncio module.

Previously `IOLoop.current` would fall back to calling `.instance` which gets the main thread's `IOLoop` instance if the current thread didn't have one.  This isn't how asyncio does it, so the changed `.instance` to be an alias to `.current`, and now `.current` tries to create a new `IOLoop` instead of getting the main threads loop, which I guess fails since no event loop was created for the new thread.

I guess the simplest fix would be to just have salt pass in the main thread's `IOLoop` when creating the new thread, and mark it as the current one there.

**Comment by kyrias** [comment]
Ah, d'oh, for some reason I thought that salt now supported tornado 5 on py3, silly me.
