### ISSUE TITLE
salt-cloud startup_action failure when states fail

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#52184]
when using `start_action: state.apply` with salt-cloud and building a VM from a map file. If the states fail we see this exception:

```
Traceback (most recent call last):
 File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 2237, in run_map
   profile, local_master=local_master
 File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1284, in create
   output = self.clouds[func](vm_)
 File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/ec2.py", line 2760, in create
   for key, value in six.iteritems(__utils__['cloud.bootstrap'](vm_, __opts__)):
 File "/usr/lib/python2.7/site-packages/salt/utils/cloud.py", line 566, in bootstrap
   deployed = deploy_script(**deploy_kwargs)
 File "/usr/lib/python2.7/site-packages/salt/utils/cloud.py", line 1629, in deploy_script
   tty, sudo, **ssh_kwargs
 File "/usr/lib/python2.7/site-packages/salt/utils/cloud.py", line 2248, in root_cmd
   retcode = _exec_ssh_cmd(cmd, allow_failure=allow_failure, **kwargs)
 File "/usr/lib/python2.7/site-packages/salt/utils/cloud.py", line 1835, in _exec_ssh_cmd
   cmd, proc.exitstatus

[INFO    ] Complete
[DEBUG   ] LazyLoaded nested.output
```

And it does not continue to send the `create` even tags or continue the rest of the salt-cloud creation run. Heres the command I'm running: 

`salt-cloud -m /etc/salt/cloud.maps.d/test.map`

The reason this occurs now is because in 2019.2.0 the exit code returns a non zero if there is a failure in a state run whereas previously it did not in earlier versions

i'm working on a pr for this.

**Comment by Ch3LL** [comment]
after further discussion with @gtmanfred (thanks!) we determined this is expected behavior, and that we want salt-cloud to fail when the `start_action` fails.

As a side note this feature request https://github.com/saltstack/salt/issues/16291 would make things easier if you are running a state.apply and are okay with a state failure.
