### ISSUE TITLE
unit.utils.test_event.TestSaltEvent.test_event_nested_sub_all

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#52253]
```
unit.utils.test_event.TestSaltEvent.test_event_nested_sub_all
--------------------------------------------------------------------------------
2017.7.9 failed on salt-debian-9-py2, salt-fedora-28-py2, salt-fedora-29-py2, salt-opensuse-42-py2
salt-ubuntu-1804-py2, salt-debian-9-py3, salt-ubuntu-1804-py3
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
EXPECTED FAILURE: None: Key data value mismatch, foo2 != foo1
................................................................................
Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/unit/utils/test_event.py", line 304, in test_event_nested_sub_all
    self.assertGotEvent(evt2, {'data': 'foo2'})
  File "/tmp/kitchen/testing/tests/unit/utils/test_event.py", line 98, in assertGotEvent
    self.assertEqual(data[key], evt[key], assertMsg)
AssertionError: None: Key data value mismatch, foo2 != foo1
```

**Comment by twangboy** [comment]
These are no longer failing
