### ISSUE TITLE
integration.modules.test_shadow.ShadowModuleTest.test_set_expire

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#52255]
```
integration.modules.test_shadow.ShadowModuleTest.test_set_expire
--------------------------------------------------------------------------------
2017.7.9 failed on salt-fedora-28-py2
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
False is not true
................................................................................
Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/support/helpers.py", line 123, in wrap
    return caller(cls)
  File "/tmp/kitchen/testing/tests/integration/modules/test_shadow.py", line 211, in test_set_expire
    self.assertTrue(self.run_function('shadow.set_expire', [self._test_user, '2016-08-25']))
AssertionError: False is not true
```

**Comment by KChandrashekhar** [comment]
It was decided not to fix this as it's only failing on a older Fedora version
