### ISSUE TITLE
integration.modules.test_shadow.ShadowModuleTest.test_set_date

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#52254]
```
integration.modules.test_shadow.ShadowModuleTest.test_set_date
--------------------------------------------------------------------------------
2017.7.9 failed on salt-fedora-28-py2
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
False is not true
................................................................................
Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/support/helpers.py", line 123, in wrap
    return caller(cls)
  File "/tmp/kitchen/testing/tests/integration/modules/test_shadow.py", line 197, in test_set_date
    self.assertTrue(self.run_function('shadow.set_date', [self._test_user, '2016-08-19']))
AssertionError: False is not true
```

**Comment by KChandrashekhar** [comment]
It was decided not to fix this as this is failing on older platform.
