### ISSUE TITLE
GlusterFS 6 module error parsing xml due to welcome banner

### ISSUE THREAD

**Issue by dbellavista** [saltstack/salt#52318]
### Description of Issue/Question

The `glusterfs` module is not working on gluster 6.0.

https://github.com/saltstack/salt/blob/develop/salt/modules/glusterfs.py#L58

### Setup
```
install_gluster_repo:
  pkgrepo.managed:
    - ppa: gluster/glusterfs-6
glusterfs-server:
  pkg.latest:
    - require:
      - pkgrepo: install_gluster_repo
glusterd:
  service.running:
    - require:
      - pkgrepo: install_gluster_repo
share:
  glusterfs.volume_present:
    - bricks: ["gluster01:/data/brick1", "gluster02:/data/brick1", "gluster03:/data/brick1"]
    - replica: 3
    - arbiter: True
    - start: True
```

### Steps to Reproduce Issue
`salt-call state.apply`

```
[INFO    ] Running state [backups] at time 12:26:20.235866
[INFO    ] Executing state glusterfs.volume_present for [backups]
[DEBUG   ] LazyLoaded cmd.run
[INFO    ] Executing command 'gluster --version' in directory '/root'
[DEBUG   ] stdout: glusterfs 6.0
Repository revision: git://git.gluster.org/glusterfs.git
Copyright (c) 2006-2016 Red Hat, Inc. <https://www.gluster.org/>
GlusterFS comes with ABSOLUTELY NO WARRANTY.
It is licensed to you under your choice of the GNU Lesser
General Public License, version 3 or any later version (LGPLv3
or later), or the GNU General Public License, version 2 (GPLv2),
in all cases as published by the Free Software Foundation.
[DEBUG   ] output: glusterfs 6.0
Repository revision: git://git.gluster.org/glusterfs.git
Copyright (c) 2006-2016 Red Hat, Inc. <https://www.gluster.org/>
GlusterFS comes with ABSOLUTELY NO WARRANTY.
It is licensed to you under your choice of the GNU Lesser
General Public License, version 3 or any later version (LGPLv3
or later), or the GNU General Public License, version 2 (GPLv2),
in all cases as published by the Free Software Foundation.
[INFO    ] Executing command 'gluster --xml --mode=script' in directory '/root'
[DEBUG   ] stdout: Welcome to gluster prompt, type 'help' to see the available commands.
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<cliOutput>
  <opRet>0</opRet>
  <opErrno>0</opErrno>
  <opErrstr/>
  <volList>
    <count>1</count>
    <volume>backups</volume>
  </volList>
</cliOutput>
[DEBUG   ] output: Welcome to gluster prompt, type 'help' to see the available commands.
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<cliOutput>
  <opRet>0</opRet>
  <opErrno>0</opErrno>
  <opErrstr/>
  <volList>
    <count>1</count>
    <volume>backups</volume>
  </volList>
</cliOutput>
[DEBUG   ] An exception occurred in this state: syntax error: line 1, column 0
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1933, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1939, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/states/glusterfs.py", line 171, in volume_present
    volumes = __salt__['glusterfs.list_volumes']()
  File "/usr/lib/python2.7/dist-packages/salt/modules/glusterfs.py", line 333, in list_volumes
    root = _gluster_xml('volume list')
  File "/usr/lib/python2.7/dist-packages/salt/modules/glusterfs.py", line 86, in _gluster_xml
    raise e
ParseError: syntax error: line 1, column 0
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1933, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1939, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/states/glusterfs.py", line 171, in volume_present
    volumes = __salt__['glusterfs.list_volumes']()
  File "/usr/lib/python2.7/dist-packages/salt/modules/glusterfs.py", line 333, in list_volumes
    root = _gluster_xml('volume list')
  File "/usr/lib/python2.7/dist-packages/salt/modules/glusterfs.py", line 86, in _gluster_xml
    raise e
ParseError: syntax error: line 1, column 0

[INFO    ] Completed state [backups] at time 12:26:20.337134 (duration_in_ms=101.268)
```

### Versions Report
```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-46-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```

**Comment by dbellavista** [comment]
By changing `https://github.com/saltstack/salt/blob/develop/salt/modules/glusterfs.py#L59` into 
```
    for line in result.splitlines():
        if line.startswith('gluster>'):
            ret += line[9:].strip()
        elif line.startswith('Welcome'):
            pass
        else:
            ret += line.strip()
```
it works. I couldn't find a way to make gluster not promt the banner.

**Comment by dmurphy18** [comment]
@dbellavista Given you have identified the fix, could you submit a PR containing it ?

**Comment by dbellavista** [comment]
Yeah I was hesitant, since it's kind of a workaround. But no problem
