### ISSUE TITLE
Error when doing `saltutil.sync_all` on 2019.2.0

### ISSUE THREAD

**Issue by CGenie** [saltstack/salt#52346]
With the `2019.2.0` version on my `salt-master` and `salt-minion` I do the simple:

```bash
salt -c _all '<minion>' saltutil.sync_all
```

and the response is:

```
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/salt/minion.py", line 1660, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "/usr/local/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/salt/modules/state.py", line 2028, in show_top
        matches = st_.top_matches(top_)
      File "/usr/local/lib/python2.7/dist-packages/salt/state.py", line 3414, in top_matches
        _filter_matches(match, data, self.opts['nodegroups'])
      File "/usr/local/lib/python2.7/dist-packages/salt/state.py", line 3396, in _filter_matches
        _opts
      File "/usr/local/lib/python2.7/dist-packages/salt/matchers/confirm_top.py", line 35, in confirm_top
        m = matchers[funcname]
      File "/usr/local/lib/python2.7/dist-packages/salt/loader.py", line 1196, in __getitem__
        func = super(LazyLoader, self).__getitem__(item)
      File "/usr/local/lib/python2.7/dist-packages/salt/utils/lazy.py", line 108, in __getitem__
        raise KeyError(key)
    KeyError: u'componund_match.match'
```

This used to work previously with the `2018.xx` versions. I can see the `compund_match.py` file under `/usr/local/lib/python2.7/dist-packages/salt/matchers/` so have no clue why it's not loading.

**Comment by dmurphy18** [comment]
@CGenie  Could you provide a copy of the output of salt-run --versions-report on the master and salt-call --local test.versions on the minion.

However I suspect you are using Debian 9 or Ubuntu 18.04 or 16.04 and are not using Salt provided by SaltStack, since you indicate /usr/**local**/lib/python2.7, which would imply using the native version of Salt supplied by the OS.

Salt packages install into /usr/**lib**/python2.7 unless special steps are taken to redirect.

The command ran successfully in my environment (without -c _all) using default /etc/salt.

Could you retry the command with the SaltStack provided packages.

**Comment by CGenie** [comment]
I install salt via

```bash
pip install -U salt
```

Results of `salt-run --versions-report` on the master:

```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.8.0
      docker-py: 3.5.1
          gitdb: 2.0.3
      gitpython: 2.1.9
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.5 (default, Apr  1 2018, 05:46:30)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 18.0.1
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.9.93-mainline-rev1
         system: Linux
        version: Ubuntu 18.04 bionic
```

Results of `salt-call --local test.versions` on the minion:

```
local:
    Salt Version:
               Salt: 2019.2.0
     
    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: Not Installed
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.10
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.6.1
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
       python-gnupg: Not Installed
             PyYAML: 5.1
              PyZMQ: 18.0.1
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 5.1.1
                ZMQ: 4.3.1
     
    System Versions:
               dist: Ubuntu 18.04 bionic
             locale: UTF-8
            machine: x86_64
            release: 4.15.0-46-generic
             system: Linux
            version: Ubuntu 18.04 bionic
```

**Comment by slakyari** [comment]
I am new to salt and installed Salt: 2019.2.0 , I am getting the same error in proxy logs and log is generated every second.

2019-04-12 09:57:46,752 [salt.minion      :1041][CRITICAL][34576] Unexpected error while connecting to x.x.x.x
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1018, in _connect_minion
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1216, in connect_master
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 879, in run
    yielded = self.gen.send(value)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 3382, in _post_master_init
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1196, in __getitem__
  File "/usr/lib/python2.7/site-packages/salt/utils/lazy.py", line 108, in __getitem__
KeyError: u'saltutil.sync_all'

**Comment by tyhunt99** [comment]
@CGenie not sure if you are still having issue with this but I had the same issue and it turned out I had a typo in "compnud" which gave me this error. It looks like the error message you have also has a typo in compound: "componund_match.match"

**Comment by CGenie** [comment]
Ah indeed thank you!
