### ISSUE TITLE
trackback instead of clean fail in lvm.pv_present when disk doesn't exist

### ISSUE THREAD

**Issue by whytewolf** [saltstack/salt#52363]
### Description of Issue/Question

Simple state 

```
test pv:
  lvm.pv_present:
    - name: /dev/vdc
```

No vdc exists

```
[root@salt00 testings]# salt-call grains.get disks
local:
    - sda
    - sdb
    - dm-0
    - dm-1
```

```
[root@salt00 testings]# salt-call state.apply testings.test
[ERROR   ] Command '[u'pvdisplay', u'-c', u'/dev/vdc']' failed with return code: 5
[ERROR   ] stderr:   Failed to find device for physical volume "/dev/vdc".
[ERROR   ] retcode: 5
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 1933, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1939, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/states/lvm.py", line 66, in pv_present
    changes = __salt__['lvm.pvcreate'](name, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/linux_lvm.py", line 232, in pvcreate
    raise CommandExecutionError('{0} does not exist'.format(device))
CommandExecutionError: /dev/vdc does not exist

local:
----------
          ID: test pv
    Function: lvm.pv_present
        Name: /dev/vdc
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1933, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1939, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/lvm.py", line 66, in pv_present
                  changes = __salt__['lvm.pvcreate'](name, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/modules/linux_lvm.py", line 232, in pvcreate
                  raise CommandExecutionError('{0} does not exist'.format(device))
              CommandExecutionError: /dev/vdc does not exist
     Started: 10:27:47.280357
    Duration: 234.837 ms
     Changes:

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time: 234.837 ms
```

Instead of a traceback should just get a disk doesn't exist fail. 

### Setup

run `lvm.pv_present` on a disk that doesn't exist.

### Versions Report
Pretty sure this has been around awhile. but does show up in recent versions.
```
salt-call --versions
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Oct 30 2018, 23:45:53)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.1.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core
```

**Comment by whytewolf** [comment]
After a little insight, it looks like the exception is raised by the code in `modules/linux_lvm.py` which doesn't seem right. either we should be catching the exception in the state module. or we should be returning false not raising exceptions. This isn't like an unexpected failure. It is failing with cause.

**Comment by whytewolf** [comment]
not stale
