### ISSUE TITLE
Boto_route53.present errors out, error: Useage of _record before assignment of _record

### ISSUE THREAD

**Issue by Church-** [saltstack/salt#52375]
### Description of Issue/Question
When trying to assign a dns entry in route53 to my box via boto_route53.present I've run into an issue where it fails out.
### Setup
SLS File:
```
setup.internal.domain:
  boto_route53.present:
    - name: {{ grains['internal_domain'] }}
    - value: {{ grains.get('ipv4')[0] }}
    - zone: DOMAIN.TLD
    - ttl: 60
    - record_type: A
    - region: us-east-1
    - profile: 
        keyid: {{ salt['pillar.get']('awskeyid','failure') }}
        key: {{ salt['pillar.get']('awskey','failure') }}
```

### Steps to Reproduce Issue
Error is:
```
    Apr 01 15:27:16 nhendrickson-test-box.linode-nj1.backtrace.io salt-minion[3891]:   File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1933, in call
    Apr 01 15:27:16 nhendrickson-test-box.linode-nj1.backtrace.io salt-minion[3891]:     **cdata['kwargs'])
    Apr 01 15:27:16 nhendrickson-test-box.linode-nj1.backtrace.io salt-minion[3891]:   File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1939, in wrapper
    Apr 01 15:27:16 nhendrickson-test-box.linode-nj1.backtrace.io salt-minion[3891]:     return f(*args, **kwargs)
    Apr 01 15:27:16 nhendrickson-test-box.linode-nj1.backtrace.io salt-minion[3891]:   File "/usr/lib/python2.7/dist-packages/salt/states/boto_route53.py", line 185, in present
    Apr 01 15:27:16 nhendrickson-test-box.linode-nj1.backtrace.io salt-minion[3891]:     private_zone, identifier)
    Apr 01 15:27:16 nhendrickson-test-box.linode-nj1.backtrace.io salt-minion[3891]:   File "/usr/lib/python2.7/dist-packages/salt/modules/boto_route53.py", line 533, in get_record
    Apr 01 15:27:16 nhendrickson-test-box.linode-nj1.backtrace.io salt-minion[3891]:     if _record:
    Apr 01 15:27:16 nhendrickson-test-box.linode-nj1.backtrace.io salt-minion[3891]: UnboundLocalError: local variable '_record' referenced before assignment
```
Reproduce:
```
sudo salt 'target_name' state.apply states.network.internal-dns
or
sudo salt 'target_name' state.highstate
```

### Versions Report
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.12.1
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.26.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.2
         Python: 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-43-generic
         system: Linux
        version: Ubuntu 18.04 bionic

**Comment by frogunder** [comment]
I am able to replicate this issue. Thanks for the report.

**Comment by tkent** [comment]
Just ran into this one myself

**Comment by Reiner030** [comment]
I have a different error message since saltstack version `2018.3.4` but this may be caused because the A record is already setup. This state was working vor several years fine for public DNS zone (and NEVER for a private zone even after deleting 2nd internal zone in other region; therefore commented out):

Origin state(s):
```
{%- if grains.ec2 is defined %}

salt-production-regional-dns-public:
  boto_route53.present:
    - name: salt-production-regional.my.domain.
    - value: {{ salt['grains.get']('ec2:public_ipv4') }}
    - zone: my.domain.
    - ttl: 60
    - record_type: A
    - region: eu-central-1
    - wait_for_sync: False
    - split_dns: True
    - private_zone: False
    # this state requirement sadly finds already preinstalled old version of the package
    #- require:
    #    - pkg: python-boto


# actual buggy in 2015.8.1 with multiple private Route53 zones - always ap-southeast-1 zone is updated :(
# still  buggy in 2016.3.2
# still  buggy in 2017.7.2
# we need vpc_id instead of region
{#-   for aws_region in pillar.regions %}
salt-production-regional-dns-{{ aws_region }}:
  boto_route53.present:
    - name: salt-production-regional.my.domain.
{%-     if aws_region in grains['location'] %}
    - value: {{ salt['grains.get']('ec2:private_ip') }}
{%-     else %}
    - value: {{ salt['grains.get']('ec2:public_ipv4') }}
{%-     endif %}
    - zone: my.domain.
    - ttl: 60
    - record_type: A
    - region: {{ aws_region }}
    - wait_for_sync: False
    - split_dns: True
    - private_zone: True
{%-   endfor #}
{%- endif %}
```

It is rendered to:
```
salt-production-regional-dns-public:
  boto_route53.present:
    - name: salt-production-regional.my.domain.
    - value: 52.29.x.x								# correct IPv4, here masked
    - zone: my.domain.								# zone exists
    - ttl: 60
    - record_type: A
    - region: eu-central-1
    - wait_for_sync: False
    - split_dns: True
    - private_zone: False
```

And I got since Update to `2018.3.4` this error (in test and productive runs):
```
[INFO    ] Running state [salt-production-regional.my.domain.] at time 09:42:05.735448
[INFO    ] Executing state boto_route53.present for [salt-production-regional.my.domain.]
[DEBUG   ] An exception occurred in this state: list index out of range
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1919, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1918, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/states/boto_route53.py", line 185, in present
    private_zone, identifier)
  File "/usr/lib/python2.7/dist-packages/salt/modules/boto_route53.py", line 535, in get_record
    ret['value'] = _record.resource_records[0]
IndexError: list index out of range
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1919, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1918, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/states/boto_route53.py", line 185, in present
    private_zone, identifier)
  File "/usr/lib/python2.7/dist-packages/salt/modules/boto_route53.py", line 535, in get_record
    ret['value'] = _record.resource_records[0]
IndexError: list index out of range

[INFO    ] Completed state [salt-production-regional.my.domain.] at time 09:42:06.395252 (duration_in_ms=659.803)
```

**Comment by frogunder** [comment]
@saltstack/team-boto Can you guys take a look here when you have time?

**Comment by Reiner030** [comment]
Hi, "blaming" helps again and shows that there was a version switch initial prepared:

```
$ git blame salt/modules/boto_route53.py | grep -v 201[0-7] | head -n 7
4ca79316557 (Erik Johnson        2018-01-17 17:05:08 -0600  48) from __future__ import absolute_import, print_function, unicode_literals
838f41dd714 (rallytime           2018-01-29 18:22:09 -0500  58) import salt.utils.versions
838f41dd714 (rallytime           2018-01-29 18:22:09 -0500  81)     # create_zone params were changed in boto 2.35+
838f41dd714 (rallytime           2018-01-29 18:22:09 -0500  82)     return salt.utils.versions.check_boto_reqs(
838f41dd714 (rallytime           2018-01-29 18:22:09 -0500  83)         boto_ver='2.35.0',
838f41dd714 (rallytime           2018-01-29 18:22:09 -0500  84)         check_boto3=False
838f41dd714 (rallytime           2018-01-29 18:22:09 -0500  85)     )
```

but this is the only appearance of boto_ver in this module ?!?

Compared to secgroup (and other) module where the version is used in a condition:
```
tests/unit/modules/test_boto_secgroup.py:required_boto_version = '2.4.0'
tests/unit/modules/test_boto_secgroup.py:    elif LooseVersion(boto.__version__) < LooseVersion(required_boto_version):
tests/unit/modules/test_boto_secgroup.py:                                       .format(required_boto_version))
```

Btw Debian Stretch is using:

```
# apt-cache policy python-boto
python-boto:
  Installed: 2.44.0-1
  Candidate: 2.44.0-1
  Version table:
 *** 2.44.0-1 500
        500 http://cdn-aws.deb.debian.org/debian stretch/main amd64 Packages
        100 /var/lib/dpkg/status
```
which I setup/used since February 2018 with Saltstack 2017.7.2/2017.7.8 without problems.

**Comment by Reiner030** [comment]
This seems to be a problem caused by the length of the hostname:

My Alias entry has a problem even on CLI request:
```
root@salt-euc1-01:~ # salt-call boto_route53.get_record salt-production-regional.example.com example.com A
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 410, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 212, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/boto_route53.py", line 535, in get_record
    ret['value'] = _record.resource_records[0]
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 410, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 212, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/boto_route53.py", line 535, in get_record
    ret['value'] = _record.resource_records[0]
IndexError: list index out of range
```
The normal instance name/minion_id is working:
```
root@salt-euc1-01:~ # salt-call boto_route53.get_record salt-euc1-01.example.com example.com A
local:
    ----------
    name:
        salt-euc1-01.example.com.
    value:
        1.2.3.4
    record_type:
        A
    ttl:
        60
```

**Comment by waynew** [comment]
Thanks for the information @Church- !

This is pretty weird! I looked at the code in `salt/modules/boto_route53.py` and I couldn't see any obvious reason for the failure. Would it be possible to modify the code and add some debugging code? I believe that since you're running `salt-call` you should be able to edit that file locally and add `import pdb; pdb.set_trace()` above line 535.

If that's something that you're comfortable doing, I'm thinking that it should be able to provide some more information. Otherwise I can see if I have access to poke around at this sort of thing myself. It's definitely a weird one.

Another thing that I would suggest looking at, again if you're comfortable, is if boto on its own will actually return the correct information. I can't see any reason why the Salt code would be making problems here, and I suspect there's something going sideways with boto... then again I could be wrong!

**Comment by Church-** [comment]
@waynew So oddly enough forgot to update this. My issue was from my pillar being down and my state not getting access to AWS creds. If others are having it that's odd.

**Comment by Reiner030** [comment]
Hell @waynew ,
I added the lines as intended for church and there is as expected no result given back (test state contains only above mentioned state) - here with the origin length of my FQDN entry for better replaying:

```
salt-production-regional-dns-public:
  boto_route53.present:
    - name: salt-production-regional.xxx.xx.
    - value: 52.29.x.x
    - zone: xxx.xx.
    - ttl: 60
    - record_type: A
    - region: eu-central-1
    #- wait_for_sync: False
    #- split_dns: True
    #- private_zone: False

```

```
# salt-call state.apply saltmaster.test
> /usr/lib/python2.7/dist-packages/salt/modules/boto_route53.py(536)get_record()
-> ret['name'] = _decode_name(_record.name)
(Pdb) pp _record.name
u'salt-production-regional.xxx.xx.'
(Pdb) pp ret['name']
*** KeyError: KeyError('name',)
(Pdb) pp ret
OrderedDict()
(Pdb) n
> /usr/lib/python2.7/dist-packages/salt/modules/boto_route53.py(537)get_record()
-> ret['value'] = _record.resource_records[0]
(Pdb) pp _record.resource_records
[]
(Pdb)

```

Same behavior/values when I call it as module:
```
# salt-call boto_route53.get_record salt-production-regional.xxx.xx. xxx.xx. A
```

but not if the length is shorter (/ different?) as the minion_id is:

```
# salt-call boto_route53.get_record salt-euc1-01.xxx.xx. xxx.xx. A
> /usr/lib/python2.7/dist-packages/salt/modules/boto_route53.py(536)get_record()
-> ret['name'] = _decode_name(_record.name)
(Pdb) pp _record.name
u'salt-euc1-01.xxx.xx.'
(Pdb) pp ret['name']
*** KeyError: KeyError('name',)
(Pdb) pp ret
OrderedDict()
(Pdb) n
> /usr/lib/python2.7/dist-packages/salt/modules/boto_route53.py(537)get_record()
-> ret['value'] = _record.resource_records[0]
(Pdb) pp _record.resource_records
[u'52.29.x.x']
```

**Comment by Reiner030** [comment]
Hello @waynew , perhaps you also need information about installed packages/versions which I forgot to write because it's normally self-explained by Distro:

```
root@salt-euc1-01:~# salt-call --versions-report
Salt Version:
           Salt: 2018.3.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.3.7
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Sep 26 2018, 18:42:22)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.9
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-9-amd64
         system: Linux
        version: debian 9.9

root@salt-euc1-01:~# aptitude search boto | grep ^i | sed "s/ - .*//" | xargs apt-cache policy {} | grep -B 1 Installed
python-boto:
  Installed: 2.44.0-1
--
python-boto3:
  Installed: 1.4.2-1
--
python-botocore:
  Installed: 1.4.70-1
--
python3-boto:
  Installed: 2.44.0-1
--
python3-boto3:
  Installed: 1.4.2-1
--
python3-botocore:
  Installed: 1.4.70-1

```

**Comment by rsuarezsoto** [comment]
I'm affected by this as well. Has there been any improvement?

**Comment by choopooly** [comment]
Just to add some context on this, using salt `3000.2`, I was also facing the same issue with the following stacktrace

```
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 1981, in call
                  **cdata['kwargs'])
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 1977, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/boto_route53.py", line 185, in present
                  private_zone, identifier)
                File "/usr/lib/python3/dist-packages/salt/modules/boto_route53.py", line 551, in get_record
                  if _record:
              UnboundLocalError: local variable '_record' referenced before assignment
```

However after investigating for a while I found that the error was misleading and the actual issue was simply a lack of permission in my instance IAM role. Once added the module was working as expected.

Here is my salt-minion report
```
Salt Version:
           Salt: 3000.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.2 (default, Apr 16 2020, 17:47:17)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-1105-aws
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by BruXy** [comment]
I am using 3000.2 and I have exact same issue as @choopooly. I have double-checked that my user has proper IAM permissions with awscli.

**Comment by BruXy** [comment]
> I am using 3000.2 and I have exact same issue as @choopooly. I have double-checked that my user has proper IAM permissions with awscli.

```
add_hostname_dns:
  boto_route53.present:
    - name: {{ minion_hostname|lower }}.mydomain.net
    - value: {{ external_ip }}
    - zone: mydoiman.net.
    - record_type: A
    - require:
      - pip: boto_dependency
    **- profile: ec2 <<<-- did not have profile name here**
```
In the previous version 2019.2.2, I have ec2 profile specified in pillars, but it was not necessary to put it directly  in the state. After adding a profile it works again, so looks like that state is not using the "default" AWS profile.

**Comment by dwoz** [comment]
UnboundLocalError on `_record` was fixed in ec83ce2b90f (Apr 2020, "Fix bugs found while writing tests") by initializing `_record = None` above the while loop. Present on 3006.x and 3007.x. The module was purged from 3008.x/master in dc526dc2b17 as part of the community-extension purge. Reporter and later commenters (#52375 (comment), #52375 (comment)) confirmed the underlying cause was IAM permissions, not a Salt bug. Required perms documented at #52375 (comment).
