### ISSUE TITLE
Mac tests are not running

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#52409]
I see this on the mac tests, both on py2 and py3. They are failing to run.

https://jenkinsci.saltstack.com/job/2019.2/view/Python3/job/salt-mac-highsierra-py3/34/console

```
02:53:49 FATAL: command execution failed
02:53:49 java.io.EOFException
02:53:49 	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2680)
02:53:49 	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3155)
02:53:49 	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:861)
02:53:49 	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:357)
02:53:49 	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:48)
02:53:49 	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:36)
02:53:49 	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)
02:53:49 Caused: java.io.IOException: Unexpected termination of the channel
02:53:49 	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:77)
02:53:49 Caused: java.io.IOException: Backing channel 'mac-bld-pro' is disconnected.
02:53:49 	at hudson.remoting.RemoteInvocationHandler.channelOrFail(RemoteInvocationHandler.java:214)
02:53:49 	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:283)
02:53:49 	at com.sun.proxy.$Proxy95.isAlive(Unknown Source)
02:53:49 	at hudson.Launcher$RemoteLauncher$ProcImpl.isAlive(Launcher.java:1137)
02:53:49 	at hudson.Launcher$RemoteLauncher$ProcImpl.join(Launcher.java:1129)
02:53:49 	at hudson.tasks.CommandInterpreter.join(CommandInterpreter.java:155)
02:53:49 	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:109)
02:53:49 	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:66)
02:53:49 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
02:53:49 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
02:53:49 	at hudson.model.Build$BuildExecution.build(Build.java:206)
02:53:49 	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
02:53:49 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
02:53:49 	at hudson.model.Run.execute(Run.java:1798)
02:53:49 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
02:53:49 	at hudson.model.ResourceController.execute(ResourceController.java:97)
02:53:49 	at hudson.model.Executor.run(Executor.java:429)
02:53:49 FATAL: Unable to delete script file /var/folders/fs/s5f4dbwn5rnctq9vwnfb_j900000gp/T/jenkins674765709671427543.sh
02:53:49 java.io.EOFException
02:53:49 	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2680)
02:53:49 	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3155)
02:53:49 	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:861)
02:53:49 	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:357)
02:53:49 	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:48)
02:53:49 	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:36)
02:53:49 	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)
02:53:49 Caused: java.io.IOException: Unexpected termination of the channel
02:53:49 	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:77)
02:53:49 Caused: hudson.remoting.ChannelClosedException: Channel "unknown": Remote call on mac-bld-pro failed. The channel is closing down or has closed down
02:53:49 	at hudson.remoting.Channel.call(Channel.java:948)
02:53:49 	at hudson.FilePath.act(FilePath.java:1036)
02:53:49 	at hudson.FilePath.act(FilePath.java:1025)
02:53:49 	at hudson.FilePath.delete(FilePath.java:1511)
02:53:49 	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:123)
02:53:49 	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:66)
02:53:49 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
02:53:49 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
02:53:49 	at hudson.model.Build$BuildExecution.build(Build.java:206)
02:53:49 	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
02:53:49 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
02:53:49 	at hudson.model.Run.execute(Run.java:1798)
02:53:49 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
02:53:49 	at hudson.model.ResourceController.execute(ResourceController.java:97)
02:53:49 	at hudson.model.Executor.run(Executor.java:429)
02:53:49 Build step 'Execute shell' marked build as failure
02:53:49 Performing Post build task...
02:53:49 Match found for :. : True
02:53:49 Logical operation result is TRUE
02:53:49 Running script  : salt-jenkins-build \
02:53:49   --output-columns 160 \
02:53:49   --download-artifact '/tmp/xml-unittests-output/*.xml' artifacts/unittests \
02:53:49   --download-artifact '/tmp/coverage.xml' artifacts/coverage \
02:53:49   --download-artifact /var/log/salt/minion artifacts/logs \
02:53:49   --download-artifact /tmp/salt-runtests.log artifacts/logs \
02:53:49   $JENKINS_VM_NAME
02:53:49 
02:53:49 find artifacts/logs -type f -not -name '*.log' -exec mv {} {}.log \;
02:53:49 Exception when executing the batch command : no workspace from node hudson.slaves.DumbSlave[mac-bld-pro] which is computer hudson.slaves.SlaveComputer@524cfe76 and has channel null
02:53:49 Build step 'Post build task' marked build as failure
02:53:49 ERROR: Step ‘Archive the artifacts’ failed: no workspace for 2019.2/salt-mac-highsierra-py3 #34
02:53:49 ERROR: Step ‘Publish Cobertura Coverage Report’ failed: no workspace for 2019.2/salt-mac-highsierra-py3 #34
02:53:49 [xUnit] [INFO] - Starting to record.
02:53:49 [xUnit] [INFO] - Processing JUnit
02:53:49 ERROR: Build step failed with exception
02:53:49 java.lang.NullPointerException
02:53:49 Build step 'Publish xUnit test result report' marked build as failure
02:53:49 ERROR: Step ‘Delete workspace when build is done’ failed: no workspace for 2019.2/salt-mac-highsierra-py3 #34
02:53:49 Finished: FAILURE
```

**Comment by garethgreenaway** [comment]
Seems like the previous failures were related to the jobs running on mac-bld-pro, I started one up and it's running on mac-bld04 and it's running tests.

**Comment by Ch3LL** [comment]
do we need to remove mac-bld-pro as a jenkins node until it is able to run tests properly?

**Comment by garethgreenaway** [comment]
@Ch3LL mac-bld-pro was pulled out of rotation and I believe @bryceml had found the issue with it.

**Comment by Ch3LL** [comment]
cool. i'm still seeing mac tests failing here though: https://jenkinsci.saltstack.com/job/2019.2/job/salt-mac-highsierra-py2/27/console

here https://jenkinsci.saltstack.com/job/2019.2/job/salt-mac-mojave-py2/11/console

here: https://jenkinsci.saltstack.com/job/2019.2/job/salt-mac-sierra-py2/31/console

**Comment by Ch3LL** [comment]
although those were started about 12 days ago i'll restart them

**Comment by KChandrashekhar** [comment]
Looks like High-Sierra  Py2 isn't completing 
https://jenkinsci.saltstack.com/job/2019.2/job/salt-mac-highsierra-py2/31/#showFailuresLink

mojave is still failing here: https://jenkinsci.saltstack.com/job/2019.2/job/salt-mac-mojave-py2/12/console

**Comment by bryceml** [comment]
They are timing out with an hour of no output and then jenkins aborts the job.  Why it stops I'm not sure yet.  Looks like quite a few stack traces are in there.

**Comment by bryceml** [comment]
Is this still happening?

**Comment by garethgreenaway** [comment]
Closing this out since Mac tests are running again since we've moved to using kitchen-salt.
