### ISSUE TITLE
Stack trace managing files with international characters

### ISSUE THREAD

**Issue by amendlik** [saltstack/salt#52406]
### Description of Issue/Question
I ran the `file.directory` state to manage the permissions of a bunch of files and directories with international characters in the file names and got this stack trace:

```
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/salt/payload.py", line 221, in dumps
        return msgpack.dumps(msg, default=ext_type_encoder, use_bin_type=use_bin_type)
      File "/usr/local/lib/python3.6/site-packages/msgpack/__init__.py", line 46, in packb
        return Packer(**kwargs).pack(o)
      File "msgpack/_packer.pyx", line 282, in msgpack._cmsgpack.Packer.pack
      File "msgpack/_packer.pyx", line 288, in msgpack._cmsgpack.Packer.pack
      File "msgpack/_packer.pyx", line 285, in msgpack._cmsgpack.Packer.pack
      File "msgpack/_packer.pyx", line 232, in msgpack._cmsgpack.Packer._pack
      File "msgpack/_packer.pyx", line 232, in msgpack._cmsgpack.Packer._pack
      File "msgpack/_packer.pyx", line 230, in msgpack._cmsgpack.Packer._pack
    UnicodeEncodeError: 'utf-8' codec can't encode characters in position 35-50: surrogates not allowed
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/salt/minion.py", line 1660, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "/usr/local/lib/python3.6/site-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/local/lib/python3.6/site-packages/salt/modules/state.py", line 778, in apply_
        return sls(mods, **kwargs)
      File "/usr/local/lib/python3.6/site-packages/salt/modules/state.py", line 1352, in sls
        serial.dump(ret, fp_)
      File "/usr/local/lib/python3.6/site-packages/salt/payload.py", line 260, in dump
        fn_.write(self.dumps(msg, use_bin_type=True))
      File "/usr/local/lib/python3.6/site-packages/salt/payload.py", line 246, in dumps
        return msgpack.dumps(msg, default=ext_type_encoder, use_bin_type=use_bin_type)
      File "/usr/local/lib/python3.6/site-packages/msgpack/__init__.py", line 46, in packb
        return Packer(**kwargs).pack(o)
      File "msgpack/_packer.pyx", line 282, in msgpack._cmsgpack.Packer.pack
      File "msgpack/_packer.pyx", line 288, in msgpack._cmsgpack.Packer.pack
      File "msgpack/_packer.pyx", line 285, in msgpack._cmsgpack.Packer.pack
      File "msgpack/_packer.pyx", line 232, in msgpack._cmsgpack.Packer._pack
      File "msgpack/_packer.pyx", line 232, in msgpack._cmsgpack.Packer._pack
      File "msgpack/_packer.pyx", line 230, in msgpack._cmsgpack.Packer._pack
    UnicodeEncodeError: 'utf-8' codec can't encode characters in position 35-50: surrogates not allowed
```

### Versions Report
```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.27.8
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.27.4
         Python: 3.6.8 (default, Feb  8 2019, 21:14:59)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 18.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist:   
         locale: UTF-8
        machine: amd64
        release: 11.2-STABLE
         system: FreeBSD
        version: Not Installed
```

**Comment by frogunder** [comment]
@amendlik Thanks for the report. I have not been able to replicate it.
Do you have a sanitized version of the state file you run and some examples of those international characters, so I can try an replicate this?

Thanks.
