### ISSUE TITLE
Lots of test suite tests fails after IPC changes

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#52408]
I see this traceback on lots of tests

```
Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/modules/test_pkg.py", line 32, in setUp
    os_release = self.run_function('grains.get', ['osrelease'])
  File "/tmp/kitchen/testing/tests/support/case.py", line 814, in run_function
    kwarg=kwargs)
  File "/tmp/kitchen/testing/salt/client/__init__.py", line 715, in cmd
    **kwargs):
  File "/tmp/kitchen/testing/salt/client/__init__.py", line 1527, in get_cli_event_returns
    **kwargs
  File "/tmp/kitchen/testing/salt/client/__init__.py", line 1104, in get_iter_returns
    for raw in ret_iter:
  File "/tmp/kitchen/testing/salt/client/__init__.py", line 1038, in get_returns_no_block
    no_block=True, auto_reconnect=self.auto_reconnect)
  File "/tmp/kitchen/testing/salt/utils/event.py", line 652, in get_event
    ret = self._get_event(wait, tag, match_func, no_block)
  File "/tmp/kitchen/testing/salt/utils/event.py", line 551, in _get_event
    raw = self.subscriber.read_sync(timeout=wait)
  File "/tmp/kitchen/testing/salt/transport/ipc.py", line 820, in read_sync
    return self.service.io_loop.run_sync(lambda: self.read_async(None, timeout))
  File "/usr/lib64/python2.7/site-packages/tornado/ioloop.py", line 444, in run_sync
    return future_cell[0].result()
  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 879, in run
    yielded = self.gen.send(value)
  File "/tmp/kitchen/testing/salt/transport/ipc.py", line 805, in read_async
    raise data
TypeError: list indices must be integers, not unicode```

**Comment by Ch3LL** [comment]
should be fixed by https://github.com/saltstack/salt/pull/52445
