### ISSUE TITLE
boto_asg.present fails with dictionary comparison when used with python3

### ISSUE THREAD

**Issue by sial-ari** [saltstack/salt#52404]
### Description of Issue/Question
The salt boto_asg module for amazon auto-scaling groups is trying to compare
dictionaries when there is existing auto-scaling group when using python3.

### Setup
Create aws auto-scaling group with boto module
```
Ensure example_security_group security group exists:
    boto_secgroup.present:
        - name: example_security_group
        - description: Templateservice ELB Security Group
        - vpc_id: vpc-5b7e4d3c
        - region: 'us-east-1'
        - rules:
            - ip_protocol: tcp
              from_port: 80
              to_port: 80
              cidr_ip:
                - 172.16.0.0/12
        - rules_egress:
            - ip_protocol: all
              from_port: -1
              to_port: -1
              cidr_ip:
                - 0.0.0.0/0


Ensure example_load_balancer elb exists:
  boto_elb.present:
    - name: example_load_balances
    - subnets: subnet-2d2c4b33
    - scheme: internal
    - security_groups:
      - example_security_group
    - listeners:
      - elb_port: 80
        elb_protocol: http
        instance_port: 80
        instance_protocol: http
    - health_check:
        target: 'HTTP:80/healthcheck'
    - attributes:
        access_log:
          enabled: true
          s3_bucket_name: example_log_bucket
          s3_bucket_prefix: example_asg_logs
          emit_interval: '5'
        connecting_settings:
          idle_timeout: 600
    - cnames:
      - name: example_service.example.com.
        zone: cognet.tv.
    - tags:
        Name: 'example_tag'
        Type: 'loadbalancer'
        Monitoring: 'development'
    - profile: infra_profile

Ensure example_asg exists:
  boto_asg.present:
    - name: example_asg
    - load_balancers:
      - example_load_balancer
    - launch_config_name: example_asg_launch_config
    - launch_config:
      - image_id: ami-0ac019f4fcb7cb7e6
      - key_name: example_key
      - security_groups:
        - example_security_group
      - instance_profile_name: example_instance_profile_name
      - instance_type: t3.medium
      - block_device_mappings:
        - "/dev/sda1":
            size: 20
            volume_type: gp2
            delete_on_termination: true
      - associate_public_ip_address: true
      - instance_monitoring: true
      - cloud_init:
          scripts:
            salt: |
              #!/bin/bash
              echo "Hello."
    - vpc_zone_identifier: vpc-5b7e4d3c
    - availability_zones: 'us-east-1'
    - min_size: 1
    - desired_capacity: 1
    - max_size: 1
    - tags:
      - key: 'Name'
        value: '{{ grains.cluster_name }}'
        propagate_at_launch: true
      - key: 'Type'
        value: '{{ grains.service_name }}'
        propagate_at_launch: true
      - key: 'Zoo'
        value: '{{grains.zoo}}'
        propagate_at_launch: true
      - key: 'Monitoring'
        value: '{{pillar.aws.tags.monitoring}}'
        propagate_at_launch: true
    - profile: infra_profile
```

### Steps to Reproduce Issue
Rerun boto_asg.present state 
``` ID: Ensure templateservice-sofiazoo-iad asg exists
    Function: boto_asg.present
        Name: templateservice-sofiazoo-iad
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/tmp/infra_venv/venv/lib/python3.6/site-packages/salt/state.py", line 1919, in call
                  **cdata['kwargs'])
                File "/tmp/infra_venv/venv/lib/python3.6/site-packages/salt/loader.py", line 1918, in wrapper
                  return f(*args, **kwargs)
                File "/tmp/infra_venv/venv/lib/python3.6/site-packages/salt/states/boto_asg.py", line 628, in present
                  value = __utils__['boto3.ordered'](value)
                File "/tmp/infra_venv/venv/lib/python3.6/site-packages/salt/utils/boto3mod.py", line 322, in ordered
                  return sorted(ordered(x) for x in obj)
              TypeError: '<' not supported between instances of 'dict' and 'dict'
     Started: 18:10:07.630392
    Duration: 175545.241 ms
     Changes:
```

The problematic object is:
```> /tmp/infra_venv/venv/lib/python3.6/site-packages/salt/utils/boto3mod.py(322)ordered()
-> return sorted(ordered(x) for x in obj)
(Pdb) obj
[OrderedDict([('key', 'Name'), ('value', 'templateservice-sofiazoo-iad'), ('propagate_at_launch', True)]), OrderedDict([('key', 'Type'), ('value', 'templateservice'), ('propagate_at_launch', True)]), OrderedDict([('key', 'Zoo'), ('value', 'sofiazoo'), ('propagate_at_launch', True)]), OrderedDict([('key', 'Monitoring'), ('value', 'development'), ('propagate_at_launch', True)])]
```
### Versions Report
```Salt Version:
           Salt: 2018.3.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.7 (default, Oct 22 2018, 11:32:17)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 18.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-46-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```

**Comment by frogunder** [comment]
Thank you for your report.
I have not been able to replicate this issue.

@saltstack/team-core Do any of you have time to take a look at this issue?

Thanks.

**Comment by waynew** [comment]
Hi @sial-ari 

What version of boto3 do you have installed?

**Comment by melbaa** [comment]
Here's more detail on the issue. 

As far as I understand, the problem is the function salt/utils/boto3mod.py::ordered can't really deal with a list of dictionaries. An isolated example reproducing the bug is:
```
from collections import OrderedDict
import six

def ordered(obj):
    if isinstance(obj, (list, tuple)):
        return sorted(ordered(x) for x in obj)
    elif isinstance(obj, dict):
        return dict((six.text_type(k) if isinstance(k, six.string_types) else k, ordered(v)) for k, v in obj.items())
    elif isinstance(obj, six.string_types):
        return six.text_type(obj)
    return obj

obj = [OrderedDict([('key', 'Name'), ('value', 'templateservice-sofiazoo-iad'), ('propagate_at_launch', True)]), OrderedDict([('key', 'Type'), ('value', 'templateservice'), ('propagate_at_launch', True)]), OrderedDict([('key', 'Zoo'), ('value', 'sofiazoo'), ('propagate_at_launch', True)]), OrderedDict([('key', 'Monitoring'), ('value', 'development'), ('propagate_at_launch', True)])]

print(ordered(obj))
```

python package versions
```
atomicwrites==1.3.0
attrs==19.1.0
boto==2.49.0
boto3==1.9.185
botocore==1.12.185
certifi==2019.6.16
chardet==3.0.4
coverage==4.5.3
docutils==0.14
idna==2.8
importlib-metadata==0.18
Jinja2==2.10.1
jmespath==0.9.4
MarkupSafe==1.1.1
more-itertools==7.1.0
msgpack==0.6.1
msgpack-python==0.5.6
packaging==19.0
pathlib2==2.3.4
pkg-resources==0.0.0
pluggy==0.12.0
py==1.8.0
pycrypto==2.6.1
pyparsing==2.4.0
pypd==1.1.0
pytest==5.0.1
pytest-cov==2.7.1
pytest-mock==1.10.4
python-dateutil==2.8.0
PyYAML==5.1.1
pyzmq==18.0.2
requests==2.22.0
s3transfer==0.2.1
salt==2018.3.4
six==1.12.0
tornado==4.5.3
urllib3==1.25.3
wcwidth==0.1.7
zipp==0.5.2
```

**Comment by melbaa** [comment]
The way boto_asg.present used salt/utils/boto3mod.py::ordered to sort ASG tags worked on python 2, because dictionaries had an ordering defined. No longer true in python 3. https://stackoverflow.com/a/22334235

**Comment by buroa** [comment]
> Thank you for your report.
> I have not been able to replicate this issue.
> 
> @saltstack/team-core Do any of you have time to take a look at this issue?
> 
> Thanks.

You did not test this thoroughly. It works on the first try **only**. If you try to run the state again, it will fail cause it tries to compare both of the dictionaries (what is created, and what to create).

**Comment by rodawg** [comment]
I'm able to replicate this as well on various versions of Saltstack (3000, 3001, 3002, 3003).

The initial creation succeeds but any further attempts against the existing autoscaling groups fails with the same error:
```
TypeError: '<' not supported between instances of 'dict' and 'dict'
```

I can provide more information if necessary.

**Comment by rodawg** [comment]
Here's version info for the last attempt:

```
Salt Version:                 
          Salt: 3003.1     
                                 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: Not Installed                
         gitdb: 2.0.3                                                                                                                                                                                              
     gitpython: 2.1.8                                                                                    
        Jinja2: 2.10
       libgit2: 0.26.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.4.7
        pygit2: 0.26.2
        Python: 3.6.9 (default, Jan 26 2021, 15:33:00)
  python-gnupg: 0.4.1
        PyYAML: 3.12
         PyZMQ: 17.1.2
         smmap: 2.0.3
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.5
  
System Versions:
          dist: ubuntu 18.04 Bionic Beaver
        locale: UTF-8
       machine: x86_64
       release: 5.4.0-1051-aws
        system: Linux
       version: Ubuntu 18.04 Bionic Beaver
```
