### ISSUE TITLE
Windows tests are not running in ci (2012R2)

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#52416]
The windows 2012 tests in ci gives traceback.

https://jenkinsci.saltstack.com/job/2019.2/job/salt-windows-2012r2-py2/29/

See this on py2:
```
20:34:58        Traceback (most recent call last):
20:34:58          File "c:\\users\\admini~1\\appdata\\local\\temp\\kitchen\\testing\salt\log\setup.py", line 1217, in __global_logging_exception_handler
20:34:58            exc_type, exc_value, exc_traceback
20:34:58        MemoryError
20:34:58        
20:34:58        Original exception was:
20:34:58        Traceback (most recent call last):
20:34:58          File "c:\users\admini~1\appdata\local\temp\salt-tests-tmpdir\scripts\cli_master.py", line 10, in <module>
20:34:58            import salt.utils.platform
20:34:58          File "c:\\users\\admini~1\\appdata\\local\\temp\\kitchen\\testing\salt\utils\platform.py", line 12, in <module>
20:34:58            from salt.utils.decorators import memoize as real_memoize
20:34:58          File "c:\\users\\admini~1\\appdata\\local\\temp\\kitchen\\testing\salt\utils\decorators\__init__.py", line 18, in <module>
20:34:58            import salt.utils.args
20:34:58          File "c:\\users\\admini~1\\appdata\\local\\temp\\kitchen\\testing\salt\utils\args.py", line 18, in <module>
20:34:58            import salt.utils.data
20:34:58          File "c:\\users\\admini~1\\appdata\\local\\temp\\kitchen\\testing\salt\utils\data.py", line 23, in <module>
20:34:58            import salt.utils.yaml
20:34:58          File "c:\\users\\admini~1\\appdata\\local\\temp\\kitchen\\testing\salt\utils\yaml.py", line 9, in <module>
20:34:58            from salt.utils.yamldumper import *
20:34:58          File "c:\\users\\admini~1\\appdata\\local\\temp\\kitchen\\testing\salt\utils\yamldumper.py", line 24, in <module>
20:34:58            from ioflo.aid.odicting import odict  # pylint: disable=E0611
20:34:58          File "C:\Python27\lib\site-packages\ioflo\__init__.py", line 11, in <module>
20:34:58            importlib.import_module(".{0}".format(m), package='ioflo')
20:34:58          File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
20:34:58            __import__(name)
20:34:58          File "C:\Python27\lib\site-packages\ioflo\base\__init__.py", line 17, in <module>
20:34:58            importlib.import_module(".{0}".format(m), package='ioflo.base')
20:34:58          File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
20:34:58            __import__(name)
20:34:58          File "C:\Python27\lib\site-packages\ioflo\base\skedding.py", line 26, in <module>
20:34:58            from . import building
20:34:58          File "C:\Python27\lib\site-packages\ioflo\base\building.py", line 27, in <module>
20:34:58            from . import housing
20:34:58          File "C:\Python27\lib\site-packages\ioflo\base\housing.py", line 21, in <module>
20:34:58            from . import acting  #needed for Registries
20:34:58          File "C:\Python27\lib\site-packages\ioflo\base\acting.py", line 26, in <module>
20:34:58            from . import framing
20:34:58          File "C:\Python27\lib\site-packages\ioflo\base\framing.py", line 10, in <module>
20:34:58            import uuid
20:34:58        MemoryError
```

See this on py3:
```
:16        Current thread 0x000006c8 (most recent call first):
11:28:25        Traceback (most recent call last):
11:28:25          File "C:\Python35\lib\site-packages\win32com\client\dynamic.py", line 327, in _make_method_
11:28:25        MemoryError
11:28:25        Traceback (most recent call last):
11:28:25          File "C:\Users\ADMINI~1\AppData\Local\Temp\salt-tests-tmpdir\scripts\cli_minion.py", line 27, in <module>
11:28:25            salt_minion()
11:28:25          File "c:\\users\\admini~1\\appdata\\local\\temp\\kitchen\\testing\salt\scripts.py", line 191, in salt_minion
11:28:25            minion.start()
11:28:25          File "c:\\users\\admini~1\\appdata\\local\\temp\\kitchen\\testing\salt\cli\daemons.py", line 346, in start
11:28:25            self._real_start()
11:28:25          File "c:\\users\\admini~1\\appdata\\local\\temp\\kitchen\\testing\salt\cli\daemons.py", line 358, in _real_start
11:28:25            self.minion.tune_in()
11:28:25          File "c:\\users\\admini~1\\appdata\\local\\temp\\kitchen\\testing\salt\minion.py", line 1059, in tune_in
11:28:25            self._spawn_minions()
11:28:25          File "c:\\users\\admini~1\\appdata\\local\\temp\\kitchen\\testing\salt\minion.py", line 1003, in _spawn_minions
11:28:25            jid_queue=self.jid_queue)
11:28:25          File "c:\\users\\admini~1\\appdata\\local\\temp\\kitchen\\testing\salt\minion.py", line 975, in _create_minion_object
11:28:25            jid_queue=jid_queue)
11:28:25          File "c:\\users\\admini~1\\appdata\\local\\temp\\kitchen\\testing\salt\minion.py", line 1129, in __init__
11:28:25            self.opts['grains'] = salt.loader.grains(opts)
11:28:25          File "c:\\users\\admini~1\\appdata\\local\\temp\\kitchen\\testing\salt\loader.py", line 772, in grains
11:28:25            ret = funcs[key]()
11:28:25          File "c:\users\admini~1\appdata\local\temp\kitchen\testing\salt\grains\core.py", line 2313, in hwaddr_interfaces
11:28:25            ifaces = _get_interfaces()
11:28:25          File "c:\users\admini~1\appdata\local\temp\kitchen\testing\salt\grains\core.py", line 1506, in _get_interfaces
11:28:25            _INTERFACES = salt.utils.network.interfaces()
11:28:25          File "c:\\users\\admini~1\\appdata\\local\\temp\\kitchen\\testing\salt\utils\network.py", line 1052, in interfaces
11:28:25            return win_interfaces()
11:28:25          File "c:\\users\\admini~1\\appdata\\local\\temp\\kitchen\\testing\salt\utils\network.py", line 1008, in win_interfaces
11:28:25            for iface in c.Win32_NetworkAdapterConfiguration(IPEnabled=1):
11:28:25          File "C:\Python35\lib\site-packages\wmi.py", line 1145, in __getattr__
11:28:25            return self._cached_classes (attribute)
11:28:25          File "C:\Python35\lib\site-packages\wmi.py", line 1156, in _cached_classes
11:28:25            self._classes_map[class_name] = _wmi_class (self, self._namespace.Get (class_name))
11:28:25        TypeError: 'NoneType' object is not callable
```

**Comment by Ch3LL** [comment]
there was a successful run with test failure results here on 2019.2.1: https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-windows-2012r2-py2/7/

**Comment by Ch3LL** [comment]
looks like its failing again on 2019.2.1. Any progress on this @twangboy ?

**Comment by twangboy** [comment]
I'm going to close this until we get tests running properly on 2012r2.
