### ISSUE TITLE
integration.shell.test_call.CallTest.test_issue_2731_masterless test failing

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#52466]
### Description of Issue/Question
The test `integration.shell.test_call.CallTest.test_issue_2731_masterless` is failing on teh following:

salt-debian-8-py3, salt-debian-9-py2, salt-fedora-29-py3, salt-ubuntu-1604-py3, salt-ubuntu-1604-py3-transport, salt-ubuntu-1804-py2

https://jenkinsci.saltstack.com/job/develop/job/salt-debian-9-py2/163/testReport/junit/integration.shell.test_call/CallTest/test_issue_2731_masterless/

with error:

```
Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/support/helpers.py", line 214, in wrap
    raise exc
AssertionError: 'local:' not found in []
```

**Comment by twangboy** [comment]
Failing on develop:
May 21, 2019 4:11:00 PM - https://jenkinsci.saltstack.com/job/develop/job/salt-amazon-1-py2/1/

**Comment by DmitryKuzmenko** [comment]
Failing on 2018.3:
https://jenkinsci.saltstack.com/job/2018.3/job/salt-fedora-30-py2/108/testReport/junit/integration.shell.test_call/CallTest/test_issue_2731_masterless/

```
Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/support/helpers.py", line 212, in wrap
    six.reraise(*sys.exc_info())
  File "/tmp/kitchen/testing/tests/support/helpers.py", line 209, in wrap
    return caller(cls)
  File "/tmp/kitchen/testing/tests/integration/shell/test_call.py", line 213, in test_issue_2731_masterless
    self.assertIn('local:', ret)
AssertionError: 'local:' not found in []
```
