### ISSUE TITLE
integration.cloud.clouds.test_vmware test failures

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#52511]
The tests:

```
integration.cloud.clouds.test_vmware.VMWareTest.test_instance
integration.cloud.clouds.test_vmware.VMWareTest.test_snapshot
```

are failing on salt-centos-7-py2-cloud, salt-centos-7-py3-cloud

with error:

```
Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/cloud/clouds/test_vmware.py", line 97, in test_instance
    self.assertIn(ret_str, instance)
AssertionError: u'CLOUD-TEST-QK7GNI:' not found in []
```

**Comment by KChandrashekhar** [comment]
Need to fix this but not for 2019.2.1 release

**Comment by waynew** [comment]
This looks very much like the flaky test problem found in https://github.com/saltstack/salt/pull/52551

**Comment by Ch3LL** [comment]
im seeing this error:

```
16:42:47        20:42:44,219 [tornado.general                           :1259][WARNING ] SSL Error on 17 ('184.72.47.146', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618)
16:42:56        [ERROR   ] There was a profile error: Cannot complete login due to an incorrect user name or password.
```

This has happened in the past when the account has been locked out or a password reset is required. i believe @pksalty manages the vmware server. Any chance you can check if the password has expired or the account is locked out?

**Comment by Ch3LL** [comment]
actually @bryceml or @jshatch ^

**Comment by Ch3LL** [comment]
this is passing on the 2019.2.1 branch now :) but not 2019.2 so keeping open for 2019.2 branch but passing for 2019.2.1 release

**Comment by DmitryKuzmenko** [comment]
Now the error message is changed to this:

https://jenkinsci.saltstack.com/job/2019.2/view/Cloud/job/salt-centos-7-py2-cloud/142/testReport/junit/integration.cloud.clouds.test_vmware/VMWareTest/test_instance/
```
Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/cloud/clouds/test_vmware.py", line 92, in test_instance
    assert value, "Instance config incomplete; missing '{}'".format(key)
AssertionError: Instance config incomplete; missing 'host'
```

https://jenkinsci.saltstack.com/job/2019.2/view/Cloud/job/salt-centos-7-py2-cloud/142/testReport/junit/integration.cloud.clouds.test_vmware/VMWareTest/test_snapshot/
```
Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/cloud/clouds/test_vmware.py", line 122, in test_snapshot
    assert instance, "Instance not found, are the '{}' provider credentials active?".format(PROVIDER_NAME)
AssertionError: Instance not found, are the 'vmware' provider credentials active?
```
