### ISSUE TITLE
Exception occurs when looking up jobs via the Jobs Runner

### ISSUE THREAD

**Issue by faelin** [saltstack/salt#52616]
# Description of Issue
As described in issue #41100 (**"Exception occurred in runner jobs.list_jobs"**), I am seeing the following errors when I attempt to query the Jobs Runner without a specific JID
```
[root@salt-master-01-dfw ~]# salt-run jobs.list_jobs
Exception occurred in runner jobs.list_jobs: Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/salt/client/mixins.py", line 387, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/salt/runners/jobs.py", line 308, in list_jobs
    ret = mminion.returners['{0}.get_jids'.format(returner)]()
  File "/usr/lib/python3.4/site-packages/salt/returners/local_cache.py", line 376, in get_jids
    for jid, job, _, _ in _walk_through(_job_dir()):
  File "/usr/lib/python3.4/site-packages/salt/returners/local_cache.py", line 80, in _walk_through
    jid = job['jid']
KeyError: 'jid'


[root@salt-master-01-dfw ~]# salt-run jobs.last_run
Exception occurred in runner jobs.last_run: Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/salt/client/mixins.py", line 387, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/salt/runners/jobs.py", line 525, in last_run
    function, target, display_progress)
  File "/usr/lib/python3.4/site-packages/salt/runners/jobs.py", line 308, in list_jobs
    ret = mminion.returners['{0}.get_jids'.format(returner)]()
  File "/usr/lib/python3.4/site-packages/salt/returners/local_cache.py", line 376, in get_jids
    for jid, job, _, _ in _walk_through(_job_dir()):
  File "/usr/lib/python3.4/site-packages/salt/returners/local_cache.py", line 80, in _walk_through
    jid = job['jid']
KeyError: 'jid'
```

Based on the error message, it seems clear that both the `jobs.list_jobs` and `jobs.last_run` are for some reason once again expecting a `jid` argument to be provided.

---

# Versions Report
```
[root@salt-master-01-dfw ~]# salt --versions
Salt Version:
           Salt: 2018.3.4

Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.27.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.27.0
         Python: 3.4.8 (default, Mar 23 2018, 10:04:27)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 4.4.135-1.el7.elrepo.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```

**Comment by Ch3LL** [comment]
i'm having a hard time replicating this:

```
(salt-py3) ➜  salt git:(d0cad3e5a3) sudo salt-run jobs.list_jobs
20190426132136063151:
    ----------
    Arguments:
    Function:
        test.ping
    StartTime:
        2019, Apr 26 13:21:36.063151
    Target:
        *
    Target-type:
        glob
    User:
        sudo_ch3ll
```

```
(salt-py3) ➜  salt git:(d0cad3e5a3) salt --versions-report
Salt Version:
           Salt: 2018.3.4
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: 3.6.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.27.7
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.27.4
         Python: 3.7.2 (default, Jan 10 2019, 23:51:51)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 18.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: arch Manjaro Linux
         locale: UTF-8
        machine: x86_64
        release: 4.19.28-1-MANJARO
         system: Linux
        version: arch Manjaro Linux
```

did you just recently upgrade when you started seeing this? i'm wondering if there is possibly something corrupt in the cache that is causing this?
