### ISSUE TITLE
salt-call schedule.modify throws unhandled error

### ISSUE THREAD

**Issue by HighWatersDev** [saltstack/salt#52644]
After running schedule.present in state file, trying to change scheduled job by running salt-call schedule.modify throws unhandled error when not all arguments for the existing job are provided.

### Configuration file
_schedule.conf:

```
schedule:
  __mine_interval: {enabled: true, function: mine.update, jid_include: true, maxrunning: 2,
    minutes: 60, return_job: false, run_on_start: true}
  __update_grains:
    args:
    - {}
    - grains_refresh
    function: event.fire
    jid_include: true
    maxrunning: 1
    minutes: 120
    name: __update_grains
    run: true
  update_job: {enabled: true, function: update_group_patch.sls, jid_include: true,
    maxrunning: 1, name: update_job, once: '2019-04-18T20:00:00', once_fmt: '%Y-%m-%dT%H:%M:%S'}
```

### Steps to reproduce the issue

```
-bash-4.2$ sudo salt-call schedule.modify update_job once=2018
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
KeyError: u'function'
Traceback (most recent call last):
  File "/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 410, in salt_call
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 212, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/schedule.py", line 486, in modify
    _new = build_schedule_item(name, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/schedule.py", line 296, in build_schedule_item
    schedule[name]['function'] = kwargs['function']
KeyError: u'function'
```

### Version report

```
-bash-4.2$ sudo salt-call --versions-report
Salt Version:
           Salt: 2018.3.4

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.31.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Sep 12 2018, 05:31:16)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: redhat 7.6 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.5.1.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.6 Maipo
```

**Comment by Ch3LL** [comment]
can you paste your `schedule.present` state file?

Also was this working previously?

**Comment by HighWatersDev** [comment]
What you see about under configuration file is what I have in the schedule file. To clarify myself, the issue is not that command didn't work. The expected behavior is to provide all of the fields found in schedule.present and only modify what needs to be. What I tried to do was to only include fields I want to modify.
For example, if I run schedule.present name=job1 function=test.ping once=2019-04-18T20:00:00 once_fmt=%Y-%m-%dT%H:%M:%S. If I want to modify "once" field I have to include all fields and modify only what I need as such: schedule.modify name=job1 function=test.ping once=2019-05-10T22:00:00 once_fmt=%Y-%m-%dT%H:%M:%S. If I only do schedule.modify name=job1 once=2020-01-01T22:00:00 it fails with the above unhandled exception.

**Comment by Ch3LL** [comment]
thanks for the follow up information. Looks like @garethgreenaway assigned this to himself to dive into. thanks :)
