### ISSUE TITLE
Debian 9 python 2 tests are failed 

### ISSUE THREAD

**Issue by DmitryKuzmenko** [saltstack/salt#52664]
### Description of Issue/Question
Debian 9 py2 build is failing. After bootstrap the test suite reports an inability to access the syndic:
```
08:12:52,992 [salt.minion                              :3096][ERROR   ] Unable to call _fire_master on localhost, that syndic is not connected
       08:12:52,993 [salt.minion                              :3110][CRITICAL] Unable to call _fire_master on any masters!
       08:12:52,993 [salt.minion                              :3121][ERROR   ] Unable to call _return_pub_multi on localhost, that syndic is not connected
       OK (0.814s)
```
Further errors could be related.

https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-debian-9-py2/7/consoleText

**Comment by DmitryKuzmenko** [comment]
Similar is for fedora 9 py2. Common errors are:
1. Syndic is not connected as pasted above.
2. Next to it is an `UnsupportedOperation` error:
```
      11:06:06,591 [salt.utils.process                       :772 ][ERROR   ] An un-handled exception from the multiprocessing process 'SignalHandlingMultiprocessingProcess-2' was caught:
       Traceback (most recent call last):
         File "/tmp/kitchen/testing/salt/utils/process.py", line 765, in _run
           return self._original_run()
         File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
           self._target(*self._args, **self._kwargs)
         File "/tmp/kitchen/testing/salt/client/mixins.py", line 467, in _proc_function
           salt.utils.process.daemonize()
         File "/tmp/kitchen/testing/salt/utils/process.py", line 106, in daemonize
           os.dup2(dev_null.fileno(), sys.stdout.fileno())
       UnsupportedOperation: fileno
```

**Comment by KChandrashekhar** [comment]
Will work on the fix in 2019.2.2

**Comment by Ch3LL** [comment]
re-adding as 2019.2.1 blocker but i think its passing now had to restart the tests here: https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-debian-9-py2/ build #33

**Comment by garethgreenaway** [comment]
Looking at recent tests it seems to still be passing as expected.  Fedora 28 have other failures but that release is being "end of lifed".
