### ISSUE TITLE
Salt-Cloud:  conflicting option string

### ISSUE THREAD

**Issue by batgranny** [saltstack/salt#52683]
Hi, I'm trying to get salt-cloud up and running and I have recently run into an error when running any salt-cloud commands:

```
# salt-cloud --config-dir
Traceback (most recent call last):
  File "/usr/local/bin/salt-cloud", line 14, in <module>
    main()
  File "/usr/local/bin/salt-cloud", line 9, in main
    cloud = saltcloud.cli.SaltCloud()
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 160, in __init__
    optparse.OptionParser.__init__(self, *args, **kwargs)
  File "/usr/lib/python2.7/optparse.py", line 1220, in __init__
    add_help=add_help_option)
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 244, in _populate_option_list
    mixin_setup_func(self)
  File "/usr/local/lib/python2.7/dist-packages/saltcloud/utils/parsers.py", line 56, in _mixin_setup
    help='The location of the saltcloud VM config file. '
  File "/usr/lib/python2.7/optparse.py", line 1021, in add_option
    self._check_conflict(option)
  File "/usr/lib/python2.7/optparse.py", line 996, in _check_conflict
    option)
optparse.OptionConflictError: option -V/--profiles/--vm_config: conflicting option string(s): -V
```

I think it may have something to so with the salt-cloud python module that is installed.  Would anyone know how I would check which version of the salt cloud module should be installed and how would I install the correct version if it's wrong?

```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.12.2
       cherrypy: 2.3.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 12 2018, 14:36:49)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-142-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by DmitryKuzmenko** [comment]
Hello @batgranny. Mentioned options `-V/--profiles/--vm_config` was removed in Salt 2014.7.0 release. It looks you use old `salt-cloud` package together with new `salt` package.
Here you can find instructions how to install Salt to Ubuntu: https://repo.saltstack.com/#ubuntu
Click `Ubuntu 16 (xenial) PY2` button and follow the instructions.
Also I recommend to remove your Salt installation first to avoid conflicts.

For further questions welcome to Salt Users Google group: https://groups.google.com/forum/#!forum/salt-users
