### ISSUE TITLE
"AsyncZeroMQReqChannel object has no attribute close"

### ISSUE THREAD

**Issue by satshabad-cr** [saltstack/salt#52716]
### Description of Issue/Question
I'm getting AsyncZeroMQReqChannel object has no attribute close when I run the highstate from the salt-master on the minion. Blowing away the salt master (it runs in docker with auto-accept keys) resolves the error, but it pops up again later.

full error message

```
[DEBUG   ] Sending event: tag = salt/job/20190425181128214477/ret/raspberrypi; data = {'fun_args': ['pillar={"bay-name":"bay29"}'], 'jid': '20190425181128214477', 'return': 'The minion function caused an exception: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1607, in _thread_return
    fp_.write(minion_instance.serial.dumps(sdata))
  File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 1068, in highstate
    errors = _get_pillar_errors(kwargs, st_.opts[\'pillar\'])
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 3940, in call_highstate
    if \'__exclude__\' in high:
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2764, in call_high
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2129, in call_chunks
    pat,
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2664, in call_chunk
    \'result\': True,
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2436, in event
    chunk is evaluated an event will be set up to the master with the
  File "/usr/lib/python2.7/dist-packages/salt/modules/event.py", line 97, in fire_master
    channel.close()
  File "/usr/lib/python2.7/dist-packages/salt/utils/asynchronous.py", line 57, in __getattribute__
    attr = getattr(self.asynchronous, key)
AttributeError: \'AsyncZeroMQReqChannel\' object has no attribute \'close\'
', 'success': False, 'cmd': '_return', u'_stamp': '2019-04-25T18:15:34.350925', 'fun': 'state.highstate', 'id': 'raspberrypi', 'out': 'nested'}
```

### Setup
We have a bunch of different sls files that install various things. I haven't tracked down after which step this happens. 
### Steps to Reproduce Issue
debug logs above

### Versions Report
salt minion version-report
```
% salt-minion --versions-report                                                                                                                                         :( 127 19-04-26 - 12:49:26
/usr/lib/python2.7/dist-packages/salt/scripts.py:198: DeprecationWarning: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date.  Salt will drop support for Python 2.7 in the Sodium release or later.
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.12.3
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: 3.7.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Sep 26 2018, 18:42:22)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.8 
         locale: UTF-8
        machine: armv7l
        release: 4.14.98-v7+
         system: Linux
        version: debian 9.8 
 

```
salt-master version-report

```
Salt Version:
           Salt: 2018.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: ascii
        machine: x86_64
        release: 4.15.0-1033-aws
         system: Linux
        version: Ubuntu 18.04 bionic
 
```

**Comment by waynew** [comment]
This is super weird because https://github.com/saltstack/salt/blob/522c7a12541bb6917f2f4e1da0b5a86d6f59a547/salt/transport/zeromq.py#L215 is definitely the attribute `close`...

**Comment by satshabad-cr** [comment]
What more info do you need? I upgraded the master and minions to the same version

**Comment by satshabad-cr** [comment]
So I discovered that this happens after the `pkg.uptodate` state is applied, which upgrades salt-minion from the 2018.3.3 to 2019.2.

Any advice on how to pin the salt-minion version?

**Comment by waynew** [comment]
Which `pkg.uptodate`? If you salt-minion isn't in your list of `pkgs`, then it shouldn't be upgraded.

**Comment by doesitblend** [comment]
ZD-4249
