### ISSUE TITLE
integration.modules.test_cp.CPModuleTest.test_get_url_https_no_dest

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52808]
2019.2.1 failed [salt-ubuntu-1404-py2](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-ubuntu-1404-py2/10/testReport/junit/integration.modules.test_cp/CPModuleTest/test_get_url_https)
---

u'Bootstrap' not found in u''

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/support/helpers.py", line 1016, in <lambda>
    lambda testcase, *args, **kwargs: self.wrap(testcase, *args, **kwargs)  # pylint: disable=W0108
  File "/tmp/kitchen/testing/tests/support/helpers.py", line 1024, in wrap
    return self.func(testcase, name, *args, **kwargs)
  File "/tmp/kitchen/testing/tests/integration/modules/test_cp.py", line 298, in test_get_url_https
    self.assertIn('Bootstrap', data)
AssertionError: u'Bootstrap' not found in u''
		
```

**Comment by dmurphy18** [comment]
@KChandrashekhar THis should not be a Blocker since no more Ubuntu 14.04 support

**Comment by dmurphy18** [comment]
Closing since Ubuntu 14.04 is EOL and we are not supporting now
