### ISSUE TITLE
Arch python3 tests are not starting

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#52834]
### Description of Issue/Question

```
04:46:13        [Runtests] Verify on instance py3-arch with state={:server_id=>"i-0ecfb61222ea9da81", :hostname=>"10.200.51.81", :last_action=>"setup", :last_error=>nil}
04:46:13        Running Command: python3 /tmp/kitchen/testing/tests/runtests.py --sysinfo --output-columns=80  --transport=zeromq -v --run-destructive --coverage-xml=/tmp/coverage.xml --xml=/tmp/xml-unittests-output/ --ssh -n integration.modules.test_pkg  2>&1
04:46:14        Traceback (most recent call last):
04:46:14          File "/tmp/kitchen/testing/tests/runtests.py", line 61, in <module>
04:46:14            from tests.integration import TestDaemon  # pylint: disable=W0403
04:46:14          File "/tmp/kitchen/testing/tests/integration/__init__.py", line 47, in <module>
04:46:14            import salt.minion
04:46:14          File "/tmp/kitchen/testing/salt/minion.py", line 70, in <module>
04:46:14            import salt.crypt
04:46:14          File "/tmp/kitchen/testing/salt/crypt.py", line 69, in <module>
04:46:14            import salt.utils.rsax931
04:46:14          File "/tmp/kitchen/testing/salt/utils/rsax931.py", line 93, in <module>
04:46:14            libcrypto = _init_libcrypto()
04:46:14          File "/tmp/kitchen/testing/salt/utils/rsax931.py", line 69, in _init_libcrypto
04:46:14            if libcrypto.OpenSSL_version_num < 0x10100000:
04:46:14        TypeError: '<' not supported between instances of '_FuncPtr' and 'int'
04:46:14        chmod: cannot access '/tmp/xml-unittests-output': No such file or directory
04:46:14 >>>>>> ------Exception-------
```

https://jenkinsci.saltstack.com/job/2019.2.1/view/Python3/job/salt-arch-py3/14/console

**Comment by KChandrashekhar** [comment]
Decided to work on fix for 2019.2.2

**Comment by dmurphy18** [comment]
unsigned long OpenSSL_version_num();

Looks like missing a set of parenthesis, will test fix

**Comment by dmurphy18** [comment]
Fix merged in by https://github.com/saltstack/salt/pull/52842
