### ISSUE TITLE
unit.utils.test_files.FilesTestCase.test_safe_walk_symlink_recursion

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52857]
develop failed [salt-windows-2016-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2016-py3/19/testReport/junit/unit.utils.test_files/FilesTestCase/test_safe_walk_symlink_recursion), [salt-windows-2019-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2019-py3/60/testReport/junit/unit.utils.test_files/FilesTestCase/test_safe_walk_symlink_recursion)
---

```
got:  expected: ('C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\salt-tests-tmpdir\\tmpzoa4amvf\\root', ['bar'], []) ('C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\salt-tests-tmpdir\\tmpzoa4amvf\\root\\bar', ['baz'], []) ('C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\salt-tests-tmpdir\\tmpzoa4amvf\\root\\bar\\baz', ['fax', 'foo', 'root'], []) ('C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\salt-tests-tmpdir\\tmpzoa4amvf\\root\\bar\\baz\\fax', [], [])
```

```

Traceback (most recent call last):
  File "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\kitchen\\testing\tests\support\helpers.py", line 1004, in <lambda>
    lambda testcase, *args, **kwargs: self.wrap(testcase, *args, **kwargs)  # pylint: disable=W0108
  File "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\kitchen\\testing\tests\support\helpers.py", line 1012, in wrap
    return self.func(testcase, tempdir, *args, **kwargs)
  File "c:\users\admini~1\appdata\local\temp\kitchen\testing\tests\unit\utils\test_files.py", line 66, in test_safe_walk_symlink_recursion
    ['', 'expected:'] + [repr(p) for p in expected]
AssertionError: got:

expected:
('C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\salt-tests-tmpdir\\tmpzoa4amvf\\root', ['bar'], [])
('C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\salt-tests-tmpdir\\tmpzoa4amvf\\root\\bar', ['baz'], [])
('C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\salt-tests-tmpdir\\tmpzoa4amvf\\root\\bar\\baz', ['fax', 'foo', 'root'], [])
('C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\salt-tests-tmpdir\\tmpzoa4amvf\\root\\bar\\baz\\fax', [], [])
		
```

**Comment by twangboy** [comment]
https://jenkinsci.saltstack.com/job/2019.2.1/view/Python3/job/salt-windows-2019-py3/48/testReport/junit/unit.utils.test_files/FilesTestCase/test_safe_walk_symlink_recursion/

**Comment by twangboy** [comment]
Failing on 2019.2.1:
May 20, 2019 8:00:00 PM - https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-windows-2019-py3/48/
