### ISSUE TITLE
unit.modules.test_ssh.SSHAuthKeyTestCase.test_recv_known_hosts_hashed_should_return_hashed_hostnames

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52865]
develop failed [salt-windows-2016-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2016-py2/19/testReport/junit/unit.modules.test_ssh/SSHAuthKeyTestCase/test_recv_known_hosts_hashed_should_return_hashed_hostnames), [salt-windows-2016-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2016-py3/19/testReport/junit/unit.modules.test_ssh/SSHAuthKeyTestCase/test_recv_known_hosts_hashed_should_return_hashed_hostnames)
---

The 'ssh-keyscan' binary was not found in $PATH.

```

Traceback (most recent call last):
  File "c:\users\admini~1\appdata\local\temp\kitchen\testing\tests\unit\modules\test_ssh.py", line 204, in test_recv_known_hosts_hashed_should_return_hashed_hostnames
    hash_known_hosts=True,
  File "<string>", line 2, in recv_known_host_entries
  File "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\kitchen\\testing\salt\utils\decorators\path.py", line 21, in wrapped
    'The \'{0}\' binary was not found in $PATH.'.format(exe)
salt.exceptions.CommandNotFoundError: The 'ssh-keyscan' binary was not found in $PATH.
		
```

Might just need to be wrapped in a skip on windows decorator?

**Comment by twangboy** [comment]
Failed on develop:
May 21, 2019 9:43:00 PM - https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2016-py2/49/
