### ISSUE TITLE
unit.modules.test_win_service.WinServiceTestCase.test_stop_not_running

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52862]
develop failed [salt-windows-2016-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2016-py2/19/testReport/junit/unit.modules.test_win_service/WinServiceTestCase/test_stop_not_running), [salt-windows-2016-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2016-py3/19/testReport/junit/unit.modules.test_win_service/WinServiceTestCase/test_stop_not_running), [salt-windows-2019-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2019-py2/66/testReport/junit/unit.modules.test_win_service/WinServiceTestCase/test_stop_not_running), [salt-windows-2019-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2019-py3/60/testReport/junit/unit.modules.test_win_service/WinServiceTestCase/test_stop_not_running)
---

The provided name 'spongebob' does not exist

```

Traceback (most recent call last):
  File "c:\users\admini~1\appdata\local\temp\kitchen\testing\tests\unit\modules\test_win_service.py", line 190, in test_stop_not_running
    self.assertTrue(win_service.stop('spongebob'))
  File "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\kitchen\\testing\salt\modules\win_service.py", line 692, in stop
    services = ServiceDependencies(name, get_all, info)
  File "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\kitchen\\testing\salt\modules\win_service.py", line 127, in __init__
    self._name = self._normalize_name(self._all_services, name)
  File "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\kitchen\\testing\salt\modules\win_service.py", line 168, in _normalize_name
    raise ValueError("The provided name '{}' does not exist".format(difference))
ValueError: The provided name 'spongebob' does not exist
		
```

**Comment by waynew** [comment]
Other two were closed as dupes, see also:

develop failed [salt-windows-2016-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2016-py2/19/testReport/junit/unit.modules.test_win_service/WinServiceTestCase/test_start), [salt-windows-2016-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2016-py3/19/testReport/junit/unit.modules.test_win_service/WinServiceTestCase/test_start), [salt-windows-2019-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2019-py2/66/testReport/junit/unit.modules.test_win_service/WinServiceTestCase/test_start), [salt-windows-2019-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2019-py3/60/testReport/junit/unit.modules.test_win_service/WinServiceTestCase/test_start)
---

The provided name 'spongebob' does not exist

```

Traceback (most recent call last):
  File "c:\users\admini~1\appdata\local\temp\kitchen\testing\tests\unit\modules\test_win_service.py", line 128, in test_start
    self.assertTrue(win_service.start('spongebob'))
  File "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\kitchen\\testing\salt\modules\win_service.py", line 637, in start
    services = ServiceDependencies(name, get_all, info)
  File "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\kitchen\\testing\salt\modules\win_service.py", line 127, in __init__
    self._name = self._normalize_name(self._all_services, name)
  File "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\kitchen\\testing\salt\modules\win_service.py", line 168, in _normalize_name
    raise ValueError("The provided name '{}' does not exist".format(difference))
ValueError: The provided name 'spongebob' does not exist
		
```

**Comment by twangboy** [comment]
Failing on develop:
May 21, 2019 5:42:00 PM - https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2019-py2/95/
May 21, 2019 9:43:00 PM - https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2016-py2/49/
