### ISSUE TITLE
unit.modules.test_virtualenv_mod.VirtualenvTestCase.test_python_argument

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52877]
develop failed [salt-fedora-29-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-fedora-29-py3/122/testReport/junit/unit.modules.test_virtualenv_mod/VirtualenvTestCase/test_python_argument), [salt-ubuntu-1804-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1804-py3/203/testReport/junit/unit.modules.test_virtualenv_mod/VirtualenvTestCase/test_python_argument)
---

expected call not found. Expected: mock(['virtualenv', '--python=/usr/bin/python3', '/tmp/foo'], python_shell=False, runas=None) Actual: mock(['python3', '-m', 'venv', '--python=/usr/bin/python3', '/tmp/foo'], python_shell=False, runas=None)

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/unit/modules/test_virtualenv_mod.py", line 289, in test_python_argument
    python_shell=False
  File "/usr/local/lib/python3.6/dist-packages/mock/mock.py", line 956, in assert_called_once_with
    return self.assert_called_with(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mock/mock.py", line 943, in assert_called_with
    six.raise_from(AssertionError(_error_message(cause)), cause)
  File "<string>", line 3, in raise_from
AssertionError: expected call not found.
Expected: mock(['virtualenv', '--python=/usr/bin/python3', '/tmp/foo'], python_shell=False, runas=None)
Actual: mock(['python3', '-m', 'venv', '--python=/usr/bin/python3', '/tmp/foo'], python_shell=False, runas=None)
		
```

**Comment by waynew** [comment]
Also failing in at least - unit.modules.test_virtualenv_mod.VirtualenvTestCase.test_issue_6029_deprecated_distribute
- unit.modules.test_virtualenv_mod.VirtualenvTestCase.test_clear_argument
- unit.modules.test_virtualenv_mod.VirtualenvTestCase.test_get_virtualenv_version_from_shell
