### ISSUE TITLE
integration.modules.test_virtualenv_mod.VirtualenvModuleTest.test_site_packages

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52871]
develop failed [salt-ubuntu-1804-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1804-py3/203/testReport/junit/integration.modules.test_virtualenv_mod/VirtualenvModuleTest/test_site_packages)
---

True is not false

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/modules/test_virtualenv_mod.py", line 45, in test_site_packages
    self.assertFalse(with_site == without_site)
AssertionError: True is not false
		
```

Probably related, might be dupe of #52049

**Comment by waynew** [comment]
Also failing in integration.modules.test_virtualenv_mod.VirtualenvModuleTest.test_create_defaults I think:


integration.modules.test_virtualenv_mod.VirtualenvModuleTest.test_create_defaults
=======

develop failed [salt-ubuntu-1804-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1804-py3/203/testReport/junit/integration.modules.test_virtualenv_mod/VirtualenvModuleTest/test_create_defaults)
---

False is not true

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/modules/test_virtualenv_mod.py", line 34, in test_create_defaults
    self.assertTrue(os.path.exists(pip_file))
AssertionError: False is not true
		
```
