### ISSUE TITLE
unit.fileserver.test_gitfs.GitfsConfigTestCase.test_per_saltenv_config

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52895]
develop failed [salt-debian-8-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-debian-8-py2/184/testReport/junit/unit.fileserver.test_gitfs/GitfsConfigTestCase/test_per_saltenv_config)
---

Failed to load gitfs

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/unit/fileserver/test_gitfs.py", line 181, in test_per_saltenv_config
    per_remote_only=gitfs.PER_REMOTE_ONLY)
  File "/tmp/kitchen/testing/salt/utils/gitfs.py", line 2712, in __new__
    init_remotes=init_remotes)
  File "/tmp/kitchen/testing/salt/utils/gitfs.py", line 2144, in __init__
    global_only)
  File "/tmp/kitchen/testing/salt/utils/gitfs.py", line 2202, in init_remotes
    self.role
  File "/tmp/kitchen/testing/salt/utils/gitfs.py", line 1128, in __init__
    override_params, cache_root, role
  File "/tmp/kitchen/testing/salt/utils/gitfs.py", line 465, in __init__
    failhard(self.role)
  File "/tmp/kitchen/testing/salt/utils/gitfs.py", line 211, in failhard
    raise FileserverConfigError('Failed to load {0}'.format(role))
FileserverConfigError: Failed to load gitfs
		
```

**Comment by frogunder** [comment]
We do not do py2 testing on develop branch anymore. I am closing this issue.
