### ISSUE TITLE
unit.daemons.test_masterapi.RemoteFuncsTestCase.test_mine_get_dict_str - cannot allocate memory

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52891]
develop failed [salt-debian-8-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-debian-8-py2/184/testReport/junit/unit.daemons.test_masterapi/RemoteFuncsTestCase/test_mine_get_dict_str), [salt-ubuntu-1604-py2-pycryptodomex](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py2-pycryptodomex/133/testReport/junit/unit.daemons.test_masterapi/RemoteFuncsTestCase/test_mine_get_dict_str)
---

[Errno 12] Cannot allocate memory

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/unit/daemons/test_masterapi.py", line 574, in setUp
    self.funcs = masterapi.RemoteFuncs(opts)
  File "/tmp/kitchen/testing/salt/daemons/masterapi.py", line 465, in __init__
    rend=False)
  File "/tmp/kitchen/testing/salt/minion.py", line 905, in __init__
    self.opts['grains'] = salt.loader.grains(opts)
  File "/tmp/kitchen/testing/salt/loader.py", line 801, in grains
    ret = funcs[key]()
  File "/tmp/kitchen/testing/salt/grains/core.py", line 2175, in fqdns
    addresses = salt.utils.network.ip_addrs(include_loopback=False, interface_data=_get_interfaces())
  File "/tmp/kitchen/testing/salt/grains/core.py", line 1510, in _get_interfaces
    _INTERFACES = salt.utils.network.interfaces()
  File "/tmp/kitchen/testing/salt/utils/network.py", line 1060, in interfaces
    return linux_interfaces()
  File "/tmp/kitchen/testing/salt/utils/network.py", line 857, in linux_interfaces
    stderr=subprocess.STDOUT).communicate()[0]
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1235, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
		
```

**Comment by waynew** [comment]
also fails on unit.daemons.test_masterapi.RemoteFuncsTestCase.test_mine_get_dict_list

**Comment by waynew** [comment]
And unit.renderers.test_stateconf.StateConfigRendererTestCase.test_states_declared_with_shorthand_no_args

**Comment by waynew** [comment]
Also fails in:

- unit.daemons.test_masterapi.AutoKeyTest.test_check_permissions_windows
- unit.grains.test_core.CoreGrainsTestCase.test_suse_os_grains_sles12sp1
- unit.renderers.test_stateconf.StateConfigRendererTestCase.test_goal_state_generation
- unit.daemons.test_masterapi.LocalFuncsTestCase.test_wheel_token_not_authenticated
- unit.utils.test_pyobjects.RendererTests.test_requisite_implicit_list
- unit.returners.test_local_cache.Local_CacheTest.test_not_clean_new_jobs
- setUpClass (unit.test_loader.LazyLoaderWhitelistTest)
- unit.modules.test_saltcheck.LinuxSysctlTestCase.test__assert_less1
- unit.daemons.test_masterapi.LocalFuncsTestCase.test_runner_eauth_authorization_error
- setUpClass (unit.states.test_boto_cloudtrail.BotoCloudTrailTestCase)
- unit.test_config.ConfigTestCase.test_conf_file_strings_are_unicode_for_master
- unit.daemons.test_masterapi.LocalFuncsTestCase.test_runner_eauth_salt_invocation_error
- unit.daemons.test_masterapi.LocalFuncsTestCase.test_runner_token_not_authenticated
- unit.test_master.ClearFuncsTestCase.test_publish_user_is_blacklisted
- unit.test_config.ConfigTestCase.test_load_master_config_from_environ_var
- unit.utils.test_pydsl.PyDSLRendererTestCase.test_include_extend
- unit.daemons.test_masterapi.AutoKeyTest.test_check_permissions_only_owner_can_write_root
- unit.test_master.ClearFuncsTestCase.test_publish_user_authenticated_missing_auth_list
- unit.daemons.test_masterapi.LocalFuncsTestCase.test_wheel_eauth_not_authenticated
- unit.modules.test_saltcheck.LinuxSysctlTestCase.test__assert_greater_equal1
- unit.cloud.clouds.test_saltify.SaltifyTestCase.test_saltify_reboot
- unit.modules.test_saltcheck.LinuxSysctlTestCase.test__assert_not_equal2
- unit.daemons.test_masterapi.LocalFuncsTestCase.test_wheel_eauth_salt_invocation_error
- unit.daemons.test_masterapi.AutoKeyTest.test_check_autosign_grains_no_grains
- unit.daemons.test_masterapi.LocalFuncsTestCase.test_runner_token_authorization_error
- unit.test_config.ConfigTestCase.test_cloud_config_providers_in_opts_path
- unit.transport.test_zeromq.PubServerChannel.test_issue_36469_udp
- unit.daemons.test_masterapi.AutoKeyTest.test_check_permissions_group_can_write_permissive_root_in_group
- unit.renderers.test_yamlex.RendererTests.test_complex
- unit.daemons.test_masterapi.AutoKeyTest.test_check_autosign_grains_invalid_file_permissions
- unit.test_master.ClearFuncsTestCase.test_publish_token_not_authenticated
- unit.transport.test_ipc.IPCMessageClient.test_singleton
- unit.renderers.test_stateconf.StateConfigRendererTestCase.test_multilevel_relative_include_beyond_top_level
- unit.modules.test_saltcheck.LinuxSysctlTestCase.test_call_salt_command
- unit.test_master.ClearFuncsTestCase.test_runner_token_not_authenticated
- unit.utils.test_pyobjects.RendererTests.test_random_password
- unit.test_master.ClearFuncsTestCase.test_publish_eauth_not_authenticated
- setUpClass (unit.states.test_boto_lambda.BotoLambdaAliasTestCase)
- integration.wheel.test_key.KeyWheelModuleTest.test_gen
- setUpClass (unit.states.test_boto_vpc.BotoVpcTestCase)
- unit.utils.test_timed_subprocess.TestTimedSubprocess.test_timedproc_with_shell_true_and_list_args
- unit.modules.test_saltcheck.LinuxSysctlTestCase.test__assert_less_equal1
- unit.modules.test_saltcheck.LinuxSysctlTestCase.test__assert_in1
- setUpClass (unit.states.test_boto_iot.BotoIoTThingTypeTestCase)
- unit.transport.test_ipc.IPCMessageClient.test_last_singleton_instance_closes
- setUpClass (unit.test_loader.LazyLoaderModulePackageTest)
- unit.renderers.test_stateconf.StateConfigRendererTestCase.test_adding_state_name_arg_for_dot_state_id
- setUpClass (unit.utils.test_reactor.TestReactor)
- unit.utils.test_pyobjects.RendererTests.test_import_scope
- unit.utils.test_pydsl.PyDSLRendererTestCase.test_requisite_declarations
- unit.test_master.ClearFuncsTestCase.test_wheel_eauth_not_authenticated
- unit.grains.test_core.CoreGrainsTestCase.test_suse_os_from_cpe_data
- unit.renderers.test_stateconf.StateConfigRendererTestCase.test_relative_include_and_extend
- unit.utils.test_pyobjects.RendererTests.test_include
- unit.client.test_ssh.SSHRosterDefaults.test_roster_defaults_flat
- unit.test_config.ConfigTestCase.test_cloud_config_double_profiles_path
- integration.states.test_supervisord.SupervisordTest.test_dead_notexists
- unit.modules.test_saltcheck.LinuxSysctlTestCase.test__assert_less_equal3
- setUpClass (unit.test_loader.LazyLoaderVirtualDisabledTest)
- unit.test_config.ConfigTestCase.test_minion_file_roots_glob
- unit.transport.test_zeromq.PubServerChannel.test_issue_36469_tcp
- unit.daemons.test_masterapi.LocalFuncsTestCase.test_publish_user_authorization_error
- unit.transport.test_ipc.IPCMessageClient.test_very_big_message
- unit.test_config.ConfigTestCase.test_cloud_config_deploy_scripts_search_path
- unit.transport.test_ipc.IPCMessageClient.test_multistream_sends
- unit.modules.test_saltcheck.LinuxSysctlTestCase.test_run_test_1
- setUpClass (unit.test_loader.LazyLoaderSingleItem)
- unit.modules.test_saltcheck.LinuxSysctlTestCase.test__assert_not_equal1
- unit.test_config.ConfigTestCase.test_master_pillar_roots_glob
- unit.renderers.test_stateconf.StateConfigRendererTestCase.test_implicit_require_with_goal_state
- unit.renderers.test_stateconf.StateConfigRendererTestCase.test_state_config
- unit.test_master.ClearFuncsTestCase.test_publish_cmd_blacklisted
- unit.modules.test_zypperpkg.ZypperTestCase.test_remove_purge
- unit.test_master.ClearFuncsTestCase.test_publish_user_authorization_error
- unit.test_minion.MinionTestCase.test_process_count_max
- unit.modules.test_saltcheck.LinuxSysctlTestCase.test__assert_false1
- unit.test_master.ClearFuncsTestCase.test_runner_token_salt_invocation_error
- unit.grains.test_core.CoreGrainsTestCase.test_suse_os_grains_sles11sp4
- unit.utils.test_network.NetworkTestCase.test__generate_minion_id_with_unicode_in_etc_hosts
- unit.modules.test_saltcheck.LinuxSysctlTestCase.test_call_salt_command2
- unit.test_master.ClearFuncsTestCase.test_runner_token_authorization_error
- unit.renderers.test_stateconf.StateConfigRendererTestCase.test_relative_include_with_requisites
- unit.test_master.ClearFuncsTestCase.test_runner_eauth_not_authenticated
- integration.states.test_supervisord.SupervisordTest.test_dead_stopped
- unit.test_config.ConfigTestCase.test_cloud_config_double_providers_path
- unit.utils.test_pyobjects.RendererTests.test_import_random_password
- unit.daemons.test_masterapi.AutoKeyTest.test_check_autosign_grains_accept_not
- unit.modules.test_saltcheck.LinuxSysctlTestCase.test__assert_equal1
- unit.modules.test_saltcheck.LinuxSysctlTestCase.test__assert_false2
- unit.modules.test_saltcheck.LinuxSysctlTestCase.test__assert_greater_equal2
- unit.utils.test_pydsl.PyDSLRendererTestCase.test_ordered_states
- unit.modules.test_saltcheck.LinuxSysctlTestCase.test__assert_less3
- setUpClass (unit.states.test_boto_cloudwatch_event.BotoCloudWatchEventTestCase)
- unit.test_master.ClearFuncsTestCase.test_wheel_eauth_salt_invocation_error
- unit.test_master.ClearFuncsTestCase.test_wheel_token_not_authenticated
- unit.test_config.ConfigTestCase.test_cloud_config_providers_in_opts
- unit.test_minion.MinionTestCase.test_beacons_before_connect
- unit.test_config.ConfigTestCase.test_sha256_is_default_for_master
- unit.daemons.test_masterapi.RemoteFuncsTestCase.test_mine_get_pre_nitrogen_compat
- setUpClass (unit.states.test_boto_s3_bucket.BotoS3BucketTestCase)
- unit.grains.test_core.CoreGrainsTestCase.test_suse_os_grains_opensuse_leap_42_1
- unit.modules.test_aptpkg.AptPkgTestCase.test_upgrade
- unit.modules.test_saltcheck.LinuxSysctlTestCase.test__assert_true2
- unit.test_config.ConfigTestCase.test_minion_id_lowercase
- unit.renderers.test_yamlex.RendererTests.test_basic
- unit.daemons.test_masterapi.AutoKeyTest.test_check_autosign_grains_accept
- unit.test_config.ConfigTestCase.test_deploy_search_path_as_string
- unit.renderers.test_stateconf.StateConfigRendererTestCase.test_dot_state_id_in_requisites
- unit.test_config.ConfigTestCase.test_proper_path_joining
- unit.test_config.ConfigTestCase.test_master_file_roots_glob
- unit.daemons.test_masterapi.AutoKeyTest.test_check_permissions_others_can_write
- integration.wheel.test_client.WheelModuleTest.test_cmd_async
- unit.utils.test_pydsl.PyDSLRendererTestCase.test_repeat_includes
- unit.states.test_winrepo.WinrepoTestCase.test_genrepo
- unit.utils.test_pydsl.PyDSLRendererTestCase.test_cmd_call
- unit.test_config.ConfigTestCase.test_load_minion_config_from_environ_var
- setUpClass (unit.states.test_boto_vpc.BotoVpcSubnetsTestCase)
- unit.modules.test_saltcheck.LinuxSysctlTestCase.test__assert_greater1
- integration.states.test_supervisord.SupervisordTest.test_running_stopped
- unit.utils.test_pyobjects.RendererTests.test_context_manager
- unit.test_config.ConfigTestCase.test_minion_pillar_roots_glob
- unit.utils.test_pydsl.PyDSLRendererTestCase.test_pipe_through_stateconf
- unit.utils.test_network.NetworkTestCase.test_generate_minion_id
- setUpClass (unit.states.test_boto_cognitoidentity.BotoCognitoIdentityTestCase)
- setUpClass (unit.states.test_boto_lambda.BotoLambdaFunctionTestCase)
- setUpClass (unit.test_loader.LazyLoaderReloadingTest)
- unit.renderers.test_stateconf.StateConfigRendererTestCase.test_slsdir
- unit.utils.test_pydsl.PyDSLRendererTestCase.test_load_highstate
- unit.modules.test_linux_sysctl.LinuxSysctlTestCase.test_persist_no_conf_failure
- setUpClass (unit.states.test_boto_elasticsearch_domain.BotoElasticsearchDomainTestCase)
- unit.modules.test_saltcheck.LinuxSysctlTestCase.test__assert_in2
- integration.states.test_supervisord.SupervisordTest.test_dead_removed
- unit.daemons.test_masterapi.AutoKeyTest.test_check_permissions_group_can_write_permissive_root_not_in_group
- unit.test_minion.MinionTestCase.test_handle_decoded_payload_jid_match_in_jid_queue
- unit.test_config.ConfigTestCase.test_load_cloud_config_from_environ_var
- unit.cloud.clouds.test_saltify.SaltifyTestCase.test_create_wake_on_lan
- unit.transport.test_ipc.IPCMessageClient.test_many_send
- unit.daemons.test_masterapi.AutoKeyTest.test_check_permissions_group_can_write_permissive
- unit.daemons.test_masterapi.LocalFuncsTestCase.test_publish_user_authenticated_missing_auth_list
- setUpClass (unit.test_loader.LazyLoaderTest)
- unit.utils.test_pyobjects.MapTests.test_map_with_priority
- unit.modules.test_saltcheck.LinuxSysctlTestCase.test__assert_not_in1
- unit.daemons.test_masterapi.LocalFuncsTestCase.test_publish_token_authorization_error
- unit.test_config.ConfigTestCase.test_load_client_config_from_environ_var
- unit.modules.test_saltcheck.LinuxSysctlTestCase.test__assert_greater2
- unit.grains.test_core.CoreGrainsTestCase.test_suse_os_grains_tumbleweed
- integration.states.test_supervisord.SupervisordTest.test_running_needsupdate
- setUpClass (unit.states.test_boto_iot.BotoIoTTopicRuleTestCase)
- setUpClass (unit.states.test_boto_vpc.BotoVpcRouteTableTestCase)
- unit.modules.test_saltcheck.LinuxSysctlTestCase.test__assert_less_equal2
- unit.utils.test_pydsl.PyDSLRendererTestCase.test_state_declarations
- unit.cloud.clouds.test_saltify.SaltifyTestCase.test_saltify_destroy
- unit.utils.test_parsers.SaltKeyOptionParserTestCase.test_get_log_level_cli
- unit.utils.test_pydsl.PyDSLRendererTestCase.test_multiple_state_func_in_state_mod
- unit.daemons.test_masterapi.LocalFuncsTestCase.test_publish_cmd_blacklisted
- unit.renderers.test_stateconf.StateConfigRendererTestCase.test_multilevel_relative_include_with_requisites
- unit.utils.test_pydsl.PyDSLRendererTestCase.test_nested_high_state_execution
- unit.daemons.test_masterapi.AutoKeyTest.test_check_permissions_only_owner_can_write
- unit.test_master.ClearFuncsTestCase.test_publish_user_not_authenticated
- unit.modules.test_aptpkg.AptPkgTestCase.test_autoremove
- unit.modules.test_saltcheck.LinuxSysctlTestCase.test__assert_greater3
- unit.renderers.test_stateconf.StateConfigRendererTestCase.test_sls_dir
- unit.test_config.ConfigTestCase.test_conf_file_strings_are_unicode_for_minion
- integration.states.test_supervisord.SupervisordTest.test_dead_started
- unit.daemons.test_masterapi.AutoKeyTest.test_check_autosign_grains_no_autosign_grains_dir
- unit.utils.test_pyobjects.RendererTests.test_basic
- unit.tops.test_ext_nodes.ExtNodesTestCase.test_ext_nodes
- unit.test_master.ClearFuncsTestCase.test_runner_user_not_authenticated
- unit.modules.test_kernelpkg_linux_yum.YumKernelPkgTestCase.test_remove_error
- unit.grains.test_core.CoreGrainsTestCase.test_suse_os_grains_sles11sp3
- unit.test_master.ClearFuncsTestCase.test_wheel_token_authorization_error
- integration.states.test_supervisord.SupervisordTest.test_restart_stopped
- unit.daemons.test_masterapi.LocalFuncsTestCase.test_publish_eauth_authorization_error
- unit.test_config.ConfigTestCase.test_common_prefix_stripping
- unit.modules.test_saltcheck.LinuxSysctlTestCase.test__assert_equal2
- unit.modules.test_saltcheck.LinuxSysctlTestCase.test__assert_true1
- unit.utils.test_pyobjects.RendererTests.test_serialization
- unit.grains.test_core.CoreGrainsTestCase.test_suse_os_grains_sles12
- unit.daemons.test_masterapi.LocalFuncsTestCase.test_wheel_user_not_authenticated
- unit.renderers.test_stateconf.StateConfigRendererTestCase.test_state_prefix
- unit.modules.test_saltcheck.LinuxSysctlTestCase.test__assert_not_in2
- integration.states.test_supervisord.SupervisordTest.test_restart_needsupdate
- unit.modules.test_kernelpkg_linux_yum.YumKernelPkgTestCase.test_remove_success
- integration.states.test_supervisord.SupervisordTest.test_running_started
- unit.test_master.ClearFuncsTestCase.test_wheel_user_not_authenticated
- unit.daemons.test_masterapi.LocalFuncsTestCase.test_wheel_token_authorization_error
- unit.renderers.test_stateconf.StateConfigRendererTestCase.test_start_state_generation
- unit.test_config.ConfigTestCase.test_master_confd_inclusion
- unit.modules.test_dockermod.DockerTestCase.test_call_success
- unit.test_master.ClearFuncsTestCase.test_runner_eauth_authorization_error
- unit.test_config.ConfigTestCase.test_master_id_function
- unit.utils.test_pyobjects.RendererTests.test_invalid_function
- unit.test_config.ConfigTestCase.test_sha256_is_default_for_minion
- unit.daemons.test_masterapi.RemoteFuncsTestCase.test_mine_get
- unit.test_loader.RawModTest.test_bad_name
- unit.test_master.ClearFuncsTestCase.test_runner_eauth_salt_invocation_error
- unit.test_minion.MinionTestCase.test_handle_decoded_payload_jid_queue_addition
- unit.daemons.test_masterapi.LocalFuncsTestCase.test_runner_token_salt_invocation_error
- unit.test_config.ConfigTestCase.test_minion_id_function
- setUpClass (unit.test_loader.LazyLoaderDeepSubmodReloadingTest)
- unit.daemons.test_masterapi.AutoKeyTest.test_check_permissions_group_can_write_not_permissive
- unit.transport.test_zeromq.PubServerChannel.test_publish_to_pubserv_ipc
- unit.transport.test_ipc.IPCMessageClient.test_multistream_errors
- setUpClass (unit.test_loader.LazyLoaderOptimizationOrderTest)
- unit.daemons.test_masterapi.LocalFuncsTestCase.test_publish_eauth_not_authenticated
- unit.utils.test_pydsl.PyDSLRendererTestCase.test_no_state_func_in_state_mod
- integration.wheel.test_key.KeyWheelModuleTest.test_list_all
- unit.daemons.test_masterapi.LocalFuncsTestCase.test_publish_token_not_authenticated
- unit.test_minion.MinionTestCase.test_scheduler_before_connect
- setUpClass (unit.states.test_boto_iot.BotoIoTPolicyTestCase)
- unit.utils.test_pyobjects.MapTests.test_map
- setUpClass (unit.states.test_boto_apigateway.BotoApiGatewayTestCase)
- unit.test_master.ClearFuncsTestCase.test_publish_eauth_authorization_error
- setUpClass (unit.states.test_boto_apigateway.BotoApiGatewayUsagePlanTestCase)
- unit.modules.test_saltcheck.LinuxSysctlTestCase.test__assert_greater_equal3
- unit.test_config.ConfigTestCase.test_issue_5970_minion_confd_inclusion
- unit.test_minion.MinionTestCase.test_handle_decoded_payload_jid_queue_reduced_minion_jid_queue_hwm
- unit.utils.test_pyobjects.RendererTests.test_sls_imports
- unit.returners.test_local_cache.Local_CacheTest.test_clean_old_jobs
- unit.transport.test_ipc.IPCMessageClient.test_basic_send
- setUpClass (unit.test_loader.LazyLoaderSubmodReloadingTest)
- unit.test_master.ClearFuncsTestCase.test_wheel_token_salt_invocation_error
- unit.transport.test_zeromq.PubServerChannel.test_publish_to_pubserv_tcp
- unit.cloud.clouds.test_saltify.SaltifyTestCase.test_list_nodes
- unit.test_loader.RawModTest.test_basic
- unit.daemons.test_masterapi.LocalFuncsTestCase.test_publish_user_is_blacklisted
- setUpClass (unit.test_loader.LazyLoaderVirtualEnabledTest)
- unit.utils.test_pyobjects.RendererTests.test_duplicates
- unit.daemons.test_masterapi.LocalFuncsTestCase.test_wheel_eauth_authorization_error
- unit.tops.test_ext_nodes.ExtNodesTestCase.test_ext_nodes_with_environment
- unit.test_master.ClearFuncsTestCase.test_wheel_eauth_authorization_error
- integration.states.test_supervisord.SupervisordTest.test_restart_started
- unit.utils.test_pydsl.PyDSLRendererTestCase.test_compile_time_state_execution
- unit.test_config.ConfigTestCase.test_default_root_dir_included_in_config_root_dir
- setUpClass (unit.states.test_boto_apigateway.BotoApiGatewayUsagePlanAssociationTestCase)
- setUpClass (unit.test_loader.LazyLoaderVirtualAliasTest)
- setUpClass (unit.states.test_boto_vpc.BotoVpcInternetGatewayTestCase)
- unit.test_config.ConfigTestCase.test_backend_rename
- unit.utils.test_pyobjects.RendererTests.test_salt_data
- unit.daemons.test_masterapi.LocalFuncsTestCase.test_runner_eauth_not_authenticated
- unit.utils.test_pyobjects.RendererTests.test_factory_serialization
- unit.utils.test_pyobjects.RendererTests.test_extend
- unit.client.test_ssh.SSHPasswordTests.test_password_failure
- unit.test_master.ClearFuncsTestCase.test_publish_token_authorization_error
- setUpClass (unit.states.test_boto_lambda.BotoLambdaEventSourceMappingTestCase)
- unit.daemons.test_masterapi.LocalFuncsTestCase.test_wheel_token_salt_invocation_error
- unit.daemons.test_masterapi.LocalFuncsTestCase.test_publish_user_not_authenticated
- unit.modules.test_saltcheck.LinuxSysctlTestCase.test__assert_less2
- unit.utils.test_network.NetworkTestCase.test_generate_minion_id_with_long_hostname
