### ISSUE TITLE
unittest.loader._FailedTest.integration.netapi.rest_tornado.test_app - no module named zmq

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52904]
2018.3 failed [salt-centos-7-py3-tcp](https://jenkinsci.saltstack.com/job/2018.3/job/salt-centos-7-py3-tcp/17/testReport/junit/unittest.loader._FailedTest.integration.netapi/rest_tornado/test_app)
---

Failed to import test module: integration.netapi.rest_tornado.test_app Traceback (most recent call last):   File "/usr/lib64/python3.4/unittest/loader.py", line 323, in _find_tests     module = self._get_module_from_name(name)   File "/usr/lib64/python3.4/unittest/loader.py", line 301, in _get_module_from_name     __import__(name)   File "/tmp/kitchen/testing/tests/integration/netapi/rest_tornado/test_app.py", line 15, in <module>     from tests.unit.netapi.test_rest_tornado import SaltnadoTestCase   File "/tmp/kitchen/testing/tests/unit/netapi/test_rest_tornado.py", line 19, in <module>     from tests.unit.utils.test_event import eventpublisher_process, SOCK_DIR  # pylint: disable=import-error   File "/tmp/kitchen/testing/tests/unit/utils/test_event.py", line 16, in <module>     import zmq ImportError: No module named 'zmq' 

```

Traceback (most recent call last):
  File "/usr/lib64/python3.4/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib64/python3.4/unittest/case.py", line 618, in run
    testMethod()
  File "/usr/lib64/python3.4/unittest/loader.py", line 33, in testFailure
    raise self._exception
ImportError: Failed to import test module: integration.netapi.rest_tornado.test_app
Traceback (most recent call last):
  File "/usr/lib64/python3.4/unittest/loader.py", line 323, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib64/python3.4/unittest/loader.py", line 301, in _get_module_from_name
    __import__(name)
  File "/tmp/kitchen/testing/tests/integration/netapi/rest_tornado/test_app.py", line 15, in <module>
    from tests.unit.netapi.test_rest_tornado import SaltnadoTestCase
  File "/tmp/kitchen/testing/tests/unit/netapi/test_rest_tornado.py", line 19, in <module>
    from tests.unit.utils.test_event import eventpublisher_process, SOCK_DIR  # pylint: disable=import-error
  File "/tmp/kitchen/testing/tests/unit/utils/test_event.py", line 16, in <module>
    import zmq
ImportError: No module named 'zmq'

		
```

**Comment by waynew** [comment]
Failure also appears in:

- unittest.loader._FailedTest.unit.test_payload
- unittest.loader._FailedTest.unit.netapi.test_rest_tornado
- unittest.loader._FailedTest.unit.transport.test_zeromq
- unittest.loader._FailedTest.unit.utils.test_event

**Comment by waynew** [comment]
Also:

- unittest.loader.ModuleImportFailure.unit.test_payload

**Comment by waynew** [comment]
And:

- unit.test_auth.MasterACLTestCase.test_master_not_user_glob_all
- unit.test_auth.MasterACLTestCase.test_args_kwargs_match
- unit.test_auth.MasterACLTestCase.test_master_function_glob
- unit.test_auth.MasterACLTestCase.test_args_empty_spec
- unit.test_auth.MasterACLTestCase.test_args_mixed_match
- unit.test_auth.MasterACLTestCase.test_args_kwargs_mismatch
- unittest.loader.ModuleImportFailure.unit.utils.test_zeromq
- unit.test_auth.MasterACLTestCase.test_args_simple_match
- unit.utils.test_verify.TestVerify.test_zmq_verify_insufficient
- unittest.loader.ModuleImportFailure.unit.transport.test_zeromq
- unittest.loader.ModuleImportFailure.integration.netapi.rest_tornado.test_app
- unit.test_auth.MasterACLTestCase.test_args_mixed_mismatch
- unit.test_auth.MasterACLTestCase.test_master_minion_glob
- unit.test_auth.MasterACLTestCase.test_master_publish_name
- unit.test_auth.MasterACLTestCase.test_args_simple_forbidden
- unit.test_auth.MasterACLTestCase.test_args_more_args
- unit.test_auth.MasterACLTestCase.test_master_publish_group
- unittest.loader.ModuleImportFailure.unit.netapi.test_rest_tornado
- unittest.loader.ModuleImportFailure.unit.utils.test_event
- unit.test_auth.MasterACLTestCase.test_master_publish_some_minions

**Comment by waynew** [comment]
Closing this as we're migrating to a single release branch (`master`)
