### ISSUE TITLE
integration.states.test_supervisord.SupervisordTest.test_restart_notexists - Starting: does not exist

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52909]
2018.3 failed [salt-centos-7-py2-tcp](https://jenkinsci.saltstack.com/job/2018.3/job/salt-centos-7-py2-tcp/22/testReport/junit/integration.states.test_supervisord/SupervisordTest/test_restart_notexists), [salt-ubuntu-1604-py2-tcp](https://jenkinsci.saltstack.com/job/2018.3/job/salt-ubuntu-1604-py2-tcp/17/testReport/junit/integration.states.test_supervisord/SupervisordTest/test_restart_notexists)
develop failed [salt-debian-8-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-debian-8-py2/184/testReport/junit/integration.states.test_supervisord/SupervisordTest/test_restart_notexists), [salt-debian-9-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-debian-9-py2/185/testReport/junit/integration.states.test_supervisord/SupervisordTest/test_restart_notexists), [salt-ubuntu-1404-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1404-py2/200/testReport/junit/integration.states.test_supervisord/SupervisordTest/test_restart_notexists), [salt-ubuntu-1604-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py2/192/testReport/junit/integration.states.test_supervisord/SupervisordTest/test_restart_notexists), [salt-ubuntu-1604-py2-m2crypto](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py2-m2crypto/141/testReport/junit/integration.states.test_supervisord/SupervisordTest/test_restart_notexists), [salt-ubuntu-1604-py2-pycryptodomex](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py2-pycryptodomex/133/testReport/junit/integration.states.test_supervisord/SupervisordTest/test_restart_notexists), [salt-ubuntu-1604-py2-transport](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py2-transport/155/testReport/junit/integration.states.test_supervisord/SupervisordTest/test_restart_notexists), [salt-ubuntu-1804-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1804-py2/202/testReport/junit/integration.states.test_supervisord/SupervisordTest/test_restart_notexists)
---

True is not False. Salt Comment: Starting: does_not_exist

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/states/test_supervisord.py", line 211, in test_restart_notexists
    self.assertSaltFalseReturn(ret)
  File "/tmp/kitchen/testing/tests/support/mixins.py", line 588, in assertSaltFalseReturn
    **(next(six.itervalues(ret)))
AssertionError: True is not False. Salt Comment:
Starting: does_not_exist
		
```

**Comment by waynew** [comment]
Duplicate of #52908
