### ISSUE TITLE
integration.states.test_alternatives.AlterantivesStateTest.test_install_set_and_remove - alternative for alt-test not installed

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52902]
2018.3 failed [salt-opensuse-15-py2](https://jenkinsci.saltstack.com/job/2018.3/job/salt-opensuse-15-py2/75/testReport/junit/integration.states.test_alternatives/AlterantivesStateTest/test_install_set_and_remove), [salt-opensuse-15-py3](https://jenkinsci.saltstack.com/job/2018.3/job/salt-opensuse-15-py3/68/testReport/junit/integration.states.test_alternatives/AlterantivesStateTest/test_install_set_and_remove)
---

False is not True. Salt Comment: Alternative for alt-test not installed: update-alternatives: using /bin/true to provide /usr/local/bin/alt-test (alt-test) in auto mode

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/support/mixins.py", line 551, in assertSaltTrueReturn
    self.assertTrue(saltret)
  File "/usr/lib64/python3.6/unittest/case.py", line 682, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/support/helpers.py", line 129, in wrap
    return caller(cls)
  File "/tmp/kitchen/testing/tests/integration/states/test_alternatives.py", line 30, in test_install_set_and_remove
    self.assertSaltTrueReturn(ret)
  File "/tmp/kitchen/testing/tests/support/mixins.py", line 557, in assertSaltTrueReturn
    **(next(six.itervalues(ret)))
AssertionError: False is not True. Salt Comment:
Alternative for alt-test not installed: update-alternatives: using /bin/true to provide /usr/local/bin/alt-test (alt-test) in auto mode
		
```

**Comment by DmitryKuzmenko** [comment]
https://jenkinsci.saltstack.com/job/2017.7/job/salt-opensuse-15-py2/105/testReport/junit/integration.states.test_alternatives/AlterantivesStateTest/test_install_set_and_remove/
