### ISSUE TITLE
unittest.loader._FailedTest.unit.utils.test_zeromq - no module named zmq

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52905]
2018.3 failed [salt-centos-7-py3-tcp](https://jenkinsci.saltstack.com/job/2018.3/job/salt-centos-7-py3-tcp/17/testReport/junit/unittest.loader._FailedTest.unit/utils/test_zeromq)
---

Failed to import test module: unit.utils.test_zeromq Traceback (most recent call last):   File "/usr/lib64/python3.4/unittest/loader.py", line 323, in _find_tests     module = self._get_module_from_name(name)   File "/usr/lib64/python3.4/unittest/loader.py", line 301, in _get_module_from_name     __import__(name)   File "/tmp/kitchen/testing/tests/unit/utils/test_zeromq.py", line 8, in <module>     import zmq ImportError: No module named 'zmq' 

```

Traceback (most recent call last):
  File "/usr/lib64/python3.4/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib64/python3.4/unittest/case.py", line 618, in run
    testMethod()
  File "/usr/lib64/python3.4/unittest/loader.py", line 33, in testFailure
    raise self._exception
ImportError: Failed to import test module: unit.utils.test_zeromq
Traceback (most recent call last):
  File "/usr/lib64/python3.4/unittest/loader.py", line 323, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib64/python3.4/unittest/loader.py", line 301, in _get_module_from_name
    __import__(name)
  File "/tmp/kitchen/testing/tests/unit/utils/test_zeromq.py", line 8, in <module>
    import zmq
ImportError: No module named 'zmq'

		
```

**Comment by waynew** [comment]
Probably a duplicate of #52904
