### ISSUE TITLE
integration.states.test_pkg.PkgTest.test_pkg_004_installed_multipkg_with_version - Zypper command, Package 'rpm-python' not found

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52917]
2019.2.1 failed [salt-opensuse-15-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-opensuse-15-py3/23/testReport/junit/integration.states.test_pkg/PkgTest/test_pkg_004_installed_multipkg_with_version)
2018.3 failed [salt-opensuse-15-py2](https://jenkinsci.saltstack.com/job/2018.3/job/salt-opensuse-15-py2/75/testReport/junit/integration.states.test_pkg/PkgTest/test_pkg_004_installed_multipkg_with_version), [salt-opensuse-15-py3](https://jenkinsci.saltstack.com/job/2018.3/job/salt-opensuse-15-py3/68/testReport/junit/integration.states.test_pkg/PkgTest/test_pkg_004_installed_multipkg_with_version)
---

False is not True. Salt Comment: An error was encountered while installing package(s): Zypper command failure: Running scope as unit: run-r7eb8531a26b2427f9f64db0391f32fc5.scope Package 'rpm-python' not found.

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/support/mixins.py", line 551, in assertSaltTrueReturn
    self.assertTrue(saltret)
  File "/usr/lib64/python3.6/unittest/case.py", line 682, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/support/helpers.py", line 212, in wrap
    raise exc
  File "/tmp/kitchen/testing/tests/support/helpers.py", line 209, in wrap
    return caller(cls)
  File "/tmp/kitchen/testing/tests/support/helpers.py", line 1075, in decorator
    return func(cls, grains=cls.run_function('grains.items'))
  File "/tmp/kitchen/testing/tests/integration/states/test_pkg.py", line 328, in test_pkg_004_installed_multipkg_with_version
    self.assertSaltTrueReturn(ret)
  File "/tmp/kitchen/testing/tests/support/mixins.py", line 557, in assertSaltTrueReturn
    **(next(six.itervalues(ret)))
AssertionError: False is not True. Salt Comment:
An error was encountered while installing package(s): Zypper command failure: Running scope as unit: run-r7eb8531a26b2427f9f64db0391f32fc5.scope
Package 'rpm-python' not found.
		
```

**Comment by waynew** [comment]
Also fails on integration.states.test_pkg.PkgTest.test_pkg_003_installed_multipkg
