### ISSUE TITLE
integration.states.test_docker_network.DockerNetworkTestCase.test_present_with_custom_ipv6 - connection aborted no such file or directory

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52920]
2019.2.1 failed [salt-opensuse-15-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-opensuse-15-py3/23/testReport/junit/integration.states.test_docker_network/DockerNetworkTestCase/test_present_with_custom_ipv6)
---

False is not True. Salt Comment: An exception occurred in this state: Traceback (most recent call last):   File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen     chunked=chunked)   File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request     conn.request(method, url, **httplib_request_kw)   File "/usr/lib64/python3.6/http/client.py", line 1239, in request     self._send_request(method, url, body, headers, encode_chunked)   File "/usr/lib64/python3.6/http/client.py", line 1285, in _send_request     self.endheaders(body, encode_chunked=encode_chunked)   File "/usr/lib64/python3.6/http/client.py", line 1234, in endheaders     self._send_output(message_body, encode_chunked=encode_chunked)   File "/usr/lib64/python3.6/http/client.py", line 1026, in _send_output     self.send(msg)   File "/usr/lib64/python3.6/http/client.py", line 964, in send     self.connect()   File "/usr/lib/python3.6/site-packages/docker/transport/unixconn.py", line 43, in connect     sock.connect(self.unix_socket) FileNotFoundError: [Errno 2] No such file or directory  During handling of the above exception, another exception occurred:  Traceback (most recent call last):   File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 449, in send     timeout=timeout   File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen     _stacktrace=sys.exc_info()[2])   File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment     raise six.reraise(type(error), error, _stacktrace)   File "/usr/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise     raise value.with_traceback(tb)   File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen     chunked=chunked)   File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request     conn.request(method, url, **httplib_request_kw)   File "/usr/lib64/python3.6/http/client.py", line 1239, in request     self._send_request(method, url, body, headers, encode_chunked)   File "/usr/lib64/python3.6/http/client.py", line 1285, in _send_request     self.endheaders(body, encode_chunked=encode_chunked)   File "/usr/lib64/python3.6/http/client.py", line 1234, in endheaders     self._send_output(message_body, encode_chunked=encode_chunked)   File "/usr/lib64/python3.6/http/client.py", line 1026, in _send_output     self.send(msg)   File "/usr/lib64/python3.6/http/client.py", line 964, in send     self.connect()   File "/usr/lib/python3.6/site-packages/docker/transport/unixconn.py", line 43, in connect     sock.connect(self.unix_socket) urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))  During handling of the above exception, another exception occurred:  Traceback (most recent call last):   File "/usr/lib/python3.6/site-packages/docker/api/client.py", line 207, in _retrieve_server_version     return self.version(api_version=False)["ApiVersion"]   File "/usr/lib/python3.6/site-packages/docker/api/daemon.py", line 181, in version     return self._result(self._get(url), json=True)   File "/usr/lib/python3.6/site-packages/docker/utils/decorators.py", line 46, in inner     return f(self, *args, **kwargs)   File "/usr/lib/python3.6/site-packages/docker/api/client.py", line 230, in _get     return self.get(url, **self._set_request_timeout(kwargs))   File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 546, in get     return self.request('GET', url, **kwargs)   File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 533, in request     resp = self.send(prep, **send_kwargs)   File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 646, in send     r = adapter.send(request, **kwargs)   File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 498, in send     raise ConnectionError(err, request=request) requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))  During handling of the above exception, another exception occurred:  Traceback (most recent call last):   File "/tmp/kitchen/testing/salt/state.py", line 1933, in call     **cdata['kwargs'])   File "/tmp/kitchen/testing/salt/loader.py", line 1939, in wrapper     return f(*args, **kwargs)   File "/tmp/kitchen/testing/salt/states/docker_network.py", line 533, in present     network = __salt__['docker.inspect_network'](name)   File "/tmp/kitchen/testing/salt/modules/dockermod.py", line 5382, in inspect_network     response = _client_wrapper('inspect_network', network_id)   File "/tmp/kitchen/testing/salt/modules/dockermod.py", line 423, in wrapper     __context__['docker.client'] = _get_client(timeout=timeout, **kwargs)   File "/tmp/kitchen/testing/salt/modules/dockermod.py", line 387, in _get_client     ret = docker.APIClient(**client_kwargs)   File "/usr/lib/python3.6/site-packages/docker/api/client.py", line 190, in __init__     self._version = self._retrieve_server_version()   File "/usr/lib/python3.6/site-packages/docker/api/client.py", line 215, in _retrieve_server_version     'Error while fetching server API version: {0}'.format(e) docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory')) 

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/support/mixins.py", line 555, in assertSaltTrueReturn
    self.assertTrue(saltret)
  File "/usr/lib64/python3.6/unittest/case.py", line 682, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/support/docker.py", line 87, in <lambda>
    lambda testcase, *args, **kwargs: self.wrap(testcase, *args, **kwargs)  # pylint: disable=W0108
  File "/tmp/kitchen/testing/tests/support/docker.py", line 97, in wrap
    return self.func(testcase, self.network, *args, **kwargs)
  File "/tmp/kitchen/testing/tests/support/docker.py", line 87, in <lambda>
    lambda testcase, *args, **kwargs: self.wrap(testcase, *args, **kwargs)  # pylint: disable=W0108
  File "/tmp/kitchen/testing/tests/support/docker.py", line 97, in wrap
    return self.func(testcase, self.network, *args, **kwargs)
  File "/tmp/kitchen/testing/tests/support/docker.py", line 87, in <lambda>
    lambda testcase, *args, **kwargs: self.wrap(testcase, *args, **kwargs)  # pylint: disable=W0108
  File "/tmp/kitchen/testing/tests/support/docker.py", line 97, in wrap
    return self.func(testcase, self.network, *args, **kwargs)
  File "/tmp/kitchen/testing/tests/integration/states/test_docker_network.py", line 456, in test_present_with_custom_ipv6
    'gateway': ipv6_net1.gateway}
  File "/tmp/kitchen/testing/tests/support/mixins.py", line 561, in assertSaltTrueReturn
    **(next(six.itervalues(ret)))
AssertionError: False is not True. Salt Comment:
An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/lib/python3.6/site-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/lib/python3.6/site-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/docker/api/client.py", line 207, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/usr/lib/python3.6/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/usr/lib/python3.6/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/docker/api/client.py", line 230, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/kitchen/testing/salt/state.py", line 1933, in call
    **cdata['kwargs'])
  File "/tmp/kitchen/testing/salt/loader.py", line 1939, in wrapper
    return f(*args, **kwargs)
  File "/tmp/kitchen/testing/salt/states/docker_network.py", line 533, in present
    network = __salt__['docker.inspect_network'](name)
  File "/tmp/kitchen/testing/salt/modules/dockermod.py", line 5382, in inspect_network
    response = _client_wrapper('inspect_network', network_id)
  File "/tmp/kitchen/testing/salt/modules/dockermod.py", line 423, in wrapper
    __context__['docker.client'] = _get_client(timeout=timeout, **kwargs)
  File "/tmp/kitchen/testing/salt/modules/dockermod.py", line 387, in _get_client
    ret = docker.APIClient(**client_kwargs)
  File "/usr/lib/python3.6/site-packages/docker/api/client.py", line 190, in __init__
    self._version = self._retrieve_server_version()
  File "/usr/lib/python3.6/site-packages/docker/api/client.py", line 215, in _retrieve_server_version
    'Error while fetching server API version: {0}'.format(e)
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

		
```

**Comment by waynew** [comment]
Also fails in:

- integration.states.test_docker_network.DockerNetworkTestCase.test_present_with_custom_ipv4
- integration.states.test_docker_network.DockerNetworkTestCase.test_present
- integration.states.test_docker_network.DockerNetworkTestCase.test_absent
- integration.states.test_docker_network.DockerNetworkTestCase.test_present_attachable
- integration.modules.test_dockermod.DockerCallTestCase.test_docker_sls
- integration.modules.test_dockermod.DockerCallTestCase.test_docker_highstate
- integration.states.test_docker_network.DockerNetworkTestCase.test_present_with_custom_ipv6
- integration.states.test_docker_network.DockerNetworkTestCase.test_present_internal
- integration.states.test_docker_network.DockerNetworkTestCase.test_present_labels
- integration.states.test_docker_network.DockerNetworkTestCase.test_present_enable_ipv6
- integration.states.test_docker_network.DockerNetworkTestCase.test_absent_when_not_present

**Comment by Ch3LL** [comment]
no longer failing https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-opensuse-15-py3/31/
