### ISSUE TITLE
[2019.2.0] Unhandled exception: salt-call retcode KeyError

### ISSUE THREAD

**Issue by vosscodes** [saltstack/salt#52955]
### Description of Issue/Question
When using `salt-call` (--local or not), Salt reports when a function `key.blah` is not available. Running only `key` to print all available options succeeds with the correct output, but an unhandled exception occurs when exiting.

### Setup
Multiple different setups, masterless minions, large syndicated groups, etc. Same results and traceback on CentOS 7.6, Manjaro, Arch, and Debian 9.5. I did not see anything useful in trace logs.

### Steps to Reproduce Issue
Masterless minion with nothing running and no state files in place.

```
# /etc/salt/minion
id: test
````

```
$ sudo salt-call key.blah
'key.blah' is not available.

$ sudo salt-call key
local:
    ----------
    key:
        'key' is not available.
    key.finger:
    keyboard.set_x:
        ...

[ERROR   ] An un-handled exception was caught by salt's global exception handler:
KeyError: u'retcode'
Traceback (most recent call last):
  File "/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 431, in salt_call
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 158, in run
    elif ret['retcode'] != salt.defaults.exitcodes.EX_OK:
KeyError: u'retcode'
Traceback (most recent call last):
  File "/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 431, in salt_call
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 158, in run
    elif ret['retcode'] != salt.defaults.exitcodes.EX_OK:
KeyError: u'retcode'
```

`salt-run` only returns 'not available' for both with no traceback.

```
$ sudo salt-run key.blah
'key.blah' is not available.

$ sudo salt-run key
'key' is not available.
```

### Versions Report
```yaml
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.26.3
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 2.7.5 (default, Apr  9 2019, 14:30:50)
   python-gnupg: 0.4.3
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.12.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core

Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.12.3
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.30.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 3.8.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.16 (default, Mar 11 2019, 18:59:25)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 18.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 5.1.1
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 4.19.36-1-MANJARO
         system: Linux
        version: Not Installed
```

**Comment by garethgreenaway** [comment]
@vosscodes Thanks for the report.  Looks to be a mostly cosmetic bug and a relatively simple fix.  We'll get this taken care of.
