### ISSUE TITLE
Call of unexisting function is_text_file in salt.utils

### ISSUE THREAD

**Issue by SuperPommeDeTerre** [saltstack/salt#52963]
### Description of Issue/Question
Call of unexisting function in `salt.utils`.

### Setup
Create a custom module making use of `salt.utils.istextfile` and run this module.
For example :
```python
# -*-coding:utf-8 -*
import salt.utils

def test_is_text_file_error(file_path):
  return salt.utils.istextfile(file_path)
```

### Steps to Reproduce Issue
Call the created module :
```shell
salt-call mymodule.test_is_text_file_error file_path="/etc/passwd"
```

An error is then raised (the warning is ok, though) :
```shell
[WARNING ] /var/cache/salt/minion/extmods/modules/mymodule.py:5: DeprecationWarning: Use of 'salt.utils.istextfile' detected. This function has been moved to 'salt.utils.files.is_text_file' as of Salt 2018.3.0. This warning will be removed in Salt Neon.

[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'module' object has no attribute 'is_text_file'
Traceback (most recent call last):
  File "/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 431, in salt_call
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 138, in run
    ret = self.call()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 237, in call
    ret['return'] = self.minion.executors[fname](self.opts, data, func, args, kwargs)
  File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/var/cache/salt/minion/extmods/modules/mymodule.py", line 5, in test_is_text_file_error
    return salt.utils.istextfile(file_path)
  File "/usr/lib/python2.7/site-packages/salt/utils/__init__.py", line 925, in istextfile
    return salt.utils.files.is_text_file(fp_, blocksize=blocksize)
AttributeError: 'module' object has no attribute 'is_text_file'
Traceback (most recent call last):
  File "/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 431, in salt_call
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 138, in run
    ret = self.call()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 237, in call
    ret['return'] = self.minion.executors[fname](self.opts, data, func, args, kwargs)
  File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/var/cache/salt/minion/extmods/modules/mymodule.py", line 5, in test_is_text_file_error
    return salt.utils.istextfile(file_path)
  File "/usr/lib/python2.7/site-packages/salt/utils/__init__.py", line 925, in istextfile
    return salt.utils.files.is_text_file(fp_, blocksize=blocksize)
AttributeError: 'module' object has no attribute 'is_text_file'
```

The problem is inside [`salt.utils.__init.py`](https://github.com/saltstack/salt/blob/20cccd85f15ebb715177a2a3e123b75d2621751b/salt/utils/__init__.py#L913) as it calls `salt.utils.files.is_text_file` that doesn't exists (as viewed from python), but it should call instead [`salt.utils.files.is_text`](https://github.com/saltstack/salt/blob/20cccd85f15ebb715177a2a3e123b75d2621751b/salt/utils/files.py#L643)

### Versions Report
```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.31.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Oct 30 2018, 23:45:53)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.5.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core
```

**Comment by garethgreenaway** [comment]
@SuperPommeDeTerre Thanks for the report.  Definitely a bug and we'll get this fixed, that particular function has been deprecated and will be removed in the Neon release.  If you're using it or planning to use it, please update your code to use `salt.utils.files.is_text` instead.

**Comment by SuperPommeDeTerre** [comment]
> 
> 
> @SuperPommeDeTerre Thanks for the report. Definitely a bug and we'll get this fixed, that particular function has been deprecated and will be removed in the Neon release. If you're using it or planning to use it, please update your code to use `salt.utils.files.is_text` instead.

@garethgreenaway  Yes, that's we have done. Thanks !
