### ISSUE TITLE
integration.modules.test_dockermod.DockerCallTestCase.test_docker_highstate test failures

### ISSUE THREAD

**Issue by garethgreenaway** [saltstack/salt#52994]
2019.2 failed [salt-opensuse-15-py2](https://jenkinsci.saltstack.com/job/2019.2/job/salt-opensuse-15-py2/67/testReport/junit/integration.modules.test_dockermod/DockerCallTestCase/test_docker_highstate), [salt-opensuse-15-py3](https://jenkinsci.saltstack.com/job/2019.2/job/salt-opensuse-15-py3/64/testReport/junit/integration.modules.test_dockermod/DockerCallTestCase/test_docker_highstate)

```
Failed to get result. Salt Returned: ('The minion function caused an exception: Traceback (most recent call last):\n'  '  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line '  '601, in urlopen\n'  '    chunked=chunked)\n'  '  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line '  '357, in _make_request\n'  '    conn.request(method, url, **httplib_request_kw)\n'  '  File "/usr/lib64/python3.6/http/client.py", line 1239, in request\n'  '    self._send_request(method, url, body, headers, encode_chunked)\n'  '  File "/usr/lib64/python3.6/http/client.py", line 1285, in _send_request\n'  '    self.endheaders(body, encode_chunked=encode_chunked)\n'  '  File "/usr/lib64/python3.6/http/client.py", line 1234, in endheaders\n'  '    self._send_output(message_body, encode_chunked=encode_chunked)\n'  '  File "/usr/lib64/python3.6/http/client.py", line 1026, in _send_output\n'  '    self.send(msg)\n'  '  File "/usr/lib64/python3.6/http/client.py", line 964, in send\n'  '    self.connect()\n'  '  File "/usr/lib/python3.6/site-packages/docker/transport/unixconn.py", line '  '43, in connect\n'  '    sock.connect(self.unix_socket)\n'  'FileNotFoundError: [Errno 2] No such file or directory\n'  '\n'  'During handling of the above exception, another exception occurred:\n'  '\n'  'Traceback (most recent call last):\n'  '  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 449, in '  'send\n'  '    timeout=timeout\n'  '  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line '  '639, in urlopen\n'  '    _stacktrace=sys.exc_info()[2])\n'  '  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, '  'in increment\n'  '    raise six.reraise(type(error), error, _stacktrace)\n'  '  File "/usr/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, '  'in reraise\n'  '    raise value.with_traceback(tb)\n'  '  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line '  '601, in urlopen\n'  '    chunked=chunked)\n'  '  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line '  '357, in _make_request\n'  '    conn.request(method, url, **httplib_request_kw)\n'  '  File "/usr/lib64/python3.6/http/client.py", line 1239, in request\n'  '    self._send_request(method, url, body, headers, encode_chunked)\n'  '  File "/usr/lib64/python3.6/http/client.py", line 1285, in _send_request\n'  '    self.endheaders(body, encode_chunked=encode_chunked)\n'  '  File "/usr/lib64/python3.6/http/client.py", line 1234, in endheaders\n'  '    self._send_output(message_body, encode_chunked=encode_chunked)\n'  '  File "/usr/lib64/python3.6/http/client.py", line 1026, in _send_output\n'  '    self.send(msg)\n'  '  File "/usr/lib64/python3.6/http/client.py", line 964, in send\n'  '    self.connect()\n'  '  File "/usr/lib/python3.6/site-packages/docker/transport/unixconn.py", line '  '43, in connect\n'  '    sock.connect(self.unix_socket)\n'  "urllib3.exceptions.ProtocolError: ('Connection aborted.', "  "FileNotFoundError(2, 'No such file or directory'))\n"  '\n'  'During handling of the above exception, another exception occurred:\n'  '\n'  'Traceback (most recent call last):\n'  '  File "/usr/lib/python3.6/site-packages/docker/api/client.py", line 207, in '  '_retrieve_server_version\n'  '    return self.version(api_version=False)["ApiVersion"]\n'  '  File "/usr/lib/python3.6/site-packages/docker/api/daemon.py", line 181, in '  'version\n'  '    return self._result(self._get(url), json=True)\n'  '  File "/usr/lib/python3.6/site-packages/docker/utils/decorators.py", line '  '46, in inner\n'  '    return f(self, *args, **kwargs)\n'  '  File "/usr/lib/python3.6/site-packages/docker/api/client.py", line 230, in '  '_get\n'  '    return self.get(url, **self._set_request_timeout(kwargs))\n'  '  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 546, in '  'get\n'  "    return self.request('GET', url, **kwargs)\n"  '  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 533, in '  'request\n'  '    resp = self.send(prep, **send_kwargs)\n'  '  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 646, in '  'send\n'  '    r = adapter.send(request, **kwargs)\n'  '  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 498, in '  'send\n'  '    raise ConnectionError(err, request=request)\n'  "requests.exceptions.ConnectionError: ('Connection aborted.', "  "FileNotFoundError(2, 'No such file or directory'))\n"  '\n'  'During handling of the above exception, another exception occurred:\n'  '\n'  'Traceback (most recent call last):\n'  '  File "/tmp/kitchen/testing/salt/minion.py", line 1663, in _thread_return\n'  '    return_data = minion_instance.executors[fname](opts, data, func, args, '  'kwargs)\n'  '  File "/tmp/kitchen/testing/salt/executors/direct_call.py", line 12, in '  'execute\n'  '    return func(*args, **kwargs)\n'  '  File "/tmp/kitchen/testing/salt/modules/dockermod.py", line 6758, in '  'apply_\n'  '    return highstate(name, **kwargs)\n'  '  File "/tmp/kitchen/testing/salt/modules/dockermod.py", line 6900, in '  'highstate\n'  "    return sls(name, saltenv='base', **kwargs)\n"  '  File "/tmp/kitchen/testing/salt/modules/dockermod.py", line 6815, in sls\n'  "    grains = call(name, 'grains.items')\n"  '  File "/tmp/kitchen/testing/salt/modules/dockermod.py", line 6680, in call\n'  '    ret = run_all(name, subprocess.list2cmdline(mkdirp_thin_argv))\n'  '  File "/tmp/kitchen/testing/salt/modules/dockermod.py", line 6325, in '  'run_all\n'  '    keep_env=keep_env)\n'  '  File "/tmp/kitchen/testing/salt/modules/dockermod.py", line 447, in '  'wrapper\n'  "    returned = wrapped(*args, **__utils__['args.clean_kwargs'](**kwargs))\n"  '  File "/tmp/kitchen/testing/salt/modules/dockermod.py", line 6059, in _run\n'  '    exec_driver = _get_exec_driver()\n'  '  File "/tmp/kitchen/testing/salt/modules/dockermod.py", line 533, in '  '_get_exec_driver\n'  "    driver = info().get('ExecutionDriver', 'docker-exec')\n"  '  File "/tmp/kitchen/testing/salt/modules/dockermod.py", line 1740, in info\n'  "    return _client_wrapper('info')\n"  '  File "/tmp/kitchen/testing/salt/modules/dockermod.py", line 423, in '  'wrapper\n'  "    __context__['docker.client'] = _get_client(timeout=timeout, **kwargs)\n"  '  File "/tmp/kitchen/testing/salt/modules/dockermod.py", line 387, in '  '_get_client\n'  '    ret = docker.APIClient(**client_kwargs)\n'  '  File "/usr/lib/python3.6/site-packages/docker/api/client.py", line 190, in '  '__init__\n'  '    self._version = self._retrieve_server_version()\n'  '  File "/usr/lib/python3.6/site-packages/docker/api/client.py", line 215, in '  '_retrieve_server_version\n'  "    'Error while fetching server API version: {0}'.format(e)\n"  'docker.errors.DockerException: Error while fetching server API version: '  "('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))\n")
```

```
Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/support/mixins.py", line 497, in assertReturnSaltType
    self.assertTrue(isinstance(ret, dict))
  File "/usr/lib64/python3.6/unittest/case.py", line 682, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/support/mixins.py", line 554, in assertSaltTrueReturn
    for saltret in self.__getWithinSaltReturn(ret, 'result'):
  File "/tmp/kitchen/testing/tests/support/mixins.py", line 527, in __getWithinSaltReturn
    self.assertReturnNonEmptySaltType(ret)
AssertionError: str is not dict. Salt returned: The minion function caused an exception: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/lib/python3.6/site-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/lib/python3.6/site-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/docker/api/client.py", line 207, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/usr/lib/python3.6/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/usr/lib/python3.6/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/docker/api/client.py", line 230, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/kitchen/testing/salt/minion.py", line 1663, in _thread_return
    return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
  File "/tmp/kitchen/testing/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/tmp/kitchen/testing/salt/modules/dockermod.py", line 6758, in apply_
    return highstate(name, **kwargs)
  File "/tmp/kitchen/testing/salt/modules/dockermod.py", line 6900, in highstate
    return sls(name, saltenv='base', **kwargs)
  File "/tmp/kitchen/testing/salt/modules/dockermod.py", line 6815, in sls
    grains = call(name, 'grains.items')
  File "/tmp/kitchen/testing/salt/modules/dockermod.py", line 6680, in call
    ret = run_all(name, subprocess.list2cmdline(mkdirp_thin_argv))
  File "/tmp/kitchen/testing/salt/modules/dockermod.py", line 6325, in run_all
    keep_env=keep_env)
  File "/tmp/kitchen/testing/salt/modules/dockermod.py", line 447, in wrapper
    returned = wrapped(*args, **__utils__['args.clean_kwargs'](**kwargs))
  File "/tmp/kitchen/testing/salt/modules/dockermod.py", line 6059, in _run
    exec_driver = _get_exec_driver()
  File "/tmp/kitchen/testing/salt/modules/dockermod.py", line 533, in _get_exec_driver
    driver = info().get('ExecutionDriver', 'docker-exec')
  File "/tmp/kitchen/testing/salt/modules/dockermod.py", line 1740, in info
    return _client_wrapper('info')
  File "/tmp/kitchen/testing/salt/modules/dockermod.py", line 423, in wrapper
    __context__['docker.client'] = _get_client(timeout=timeout, **kwargs)
  File "/tmp/kitchen/testing/salt/modules/dockermod.py", line 387, in _get_client
    ret = docker.APIClient(**client_kwargs)
  File "/usr/lib/python3.6/site-packages/docker/api/client.py", line 190, in __init__
    self._version = self._retrieve_server_version()
  File "/usr/lib/python3.6/site-packages/docker/api/client.py", line 215, in _retrieve_server_version
    'Error while fetching server API version: {0}'.format(e)
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/support/mixins.py", line 561, in assertSaltTrueReturn
    **(next(six.itervalues(ret)))
  File "/tmp/kitchen/testing/salt/ext/six.py", line 585, in itervalues
    return iter(d.values(**kw))
AttributeError: 'str' object has no attribute 'values'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/modules/test_dockermod.py", line 99, in test_docker_highstate
    self.assertSaltTrueReturn(ret)
  File "/tmp/kitchen/testing/tests/support/mixins.py", line 567, in assertSaltTrueReturn
    pprint.pformat(ret)
AssertionError: Failed to get result. Salt Returned:
('The minion function caused an exception: Traceback (most recent call last):\n'
 '  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line '
 '601, in urlopen\n'
 '    chunked=chunked)\n'
 '  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line '
 '357, in _make_request\n'
 '    conn.request(method, url, **httplib_request_kw)\n'
 '  File "/usr/lib64/python3.6/http/client.py", line 1239, in request\n'
 '    self._send_request(method, url, body, headers, encode_chunked)\n'
 '  File "/usr/lib64/python3.6/http/client.py", line 1285, in _send_request\n'
 '    self.endheaders(body, encode_chunked=encode_chunked)\n'
 '  File "/usr/lib64/python3.6/http/client.py", line 1234, in endheaders\n'
 '    self._send_output(message_body, encode_chunked=encode_chunked)\n'
 '  File "/usr/lib64/python3.6/http/client.py", line 1026, in _send_output\n'
 '    self.send(msg)\n'
 '  File "/usr/lib64/python3.6/http/client.py", line 964, in send\n'
 '    self.connect()\n'
 '  File "/usr/lib/python3.6/site-packages/docker/transport/unixconn.py", line '
 '43, in connect\n'
 '    sock.connect(self.unix_socket)\n'
 'FileNotFoundError: [Errno 2] No such file or directory\n'
 '\n'
 'During handling of the above exception, another exception occurred:\n'
 '\n'
 'Traceback (most recent call last):\n'
 '  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 449, in '
 'send\n'
 '    timeout=timeout\n'
 '  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line '
 '639, in urlopen\n'
 '    _stacktrace=sys.exc_info()[2])\n'
 '  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, '
 'in increment\n'
 '    raise six.reraise(type(error), error, _stacktrace)\n'
 '  File "/usr/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, '
 'in reraise\n'
 '    raise value.with_traceback(tb)\n'
 '  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line '
 '601, in urlopen\n'
 '    chunked=chunked)\n'
 '  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line '
 '357, in _make_request\n'
 '    conn.request(method, url, **httplib_request_kw)\n'
 '  File "/usr/lib64/python3.6/http/client.py", line 1239, in request\n'
 '    self._send_request(method, url, body, headers, encode_chunked)\n'
 '  File "/usr/lib64/python3.6/http/client.py", line 1285, in _send_request\n'
 '    self.endheaders(body, encode_chunked=encode_chunked)\n'
 '  File "/usr/lib64/python3.6/http/client.py", line 1234, in endheaders\n'
 '    self._send_output(message_body, encode_chunked=encode_chunked)\n'
 '  File "/usr/lib64/python3.6/http/client.py", line 1026, in _send_output\n'
 '    self.send(msg)\n'
 '  File "/usr/lib64/python3.6/http/client.py", line 964, in send\n'
 '    self.connect()\n'
 '  File "/usr/lib/python3.6/site-packages/docker/transport/unixconn.py", line '
 '43, in connect\n'
 '    sock.connect(self.unix_socket)\n'
 "urllib3.exceptions.ProtocolError: ('Connection aborted.', "
 "FileNotFoundError(2, 'No such file or directory'))\n"
 '\n'
 'During handling of the above exception, another exception occurred:\n'
 '\n'
 'Traceback (most recent call last):\n'
 '  File "/usr/lib/python3.6/site-packages/docker/api/client.py", line 207, in '
 '_retrieve_server_version\n'
 '    return self.version(api_version=False)["ApiVersion"]\n'
 '  File "/usr/lib/python3.6/site-packages/docker/api/daemon.py", line 181, in '
 'version\n'
 '    return self._result(self._get(url), json=True)\n'
 '  File "/usr/lib/python3.6/site-packages/docker/utils/decorators.py", line '
 '46, in inner\n'
 '    return f(self, *args, **kwargs)\n'
 '  File "/usr/lib/python3.6/site-packages/docker/api/client.py", line 230, in '
 '_get\n'
 '    return self.get(url, **self._set_request_timeout(kwargs))\n'
 '  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 546, in '
 'get\n'
 "    return self.request('GET', url, **kwargs)\n"
 '  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 533, in '
 'request\n'
 '    resp = self.send(prep, **send_kwargs)\n'
 '  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 646, in '
 'send\n'
 '    r = adapter.send(request, **kwargs)\n'
 '  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 498, in '
 'send\n'
 '    raise ConnectionError(err, request=request)\n'
 "requests.exceptions.ConnectionError: ('Connection aborted.', "
 "FileNotFoundError(2, 'No such file or directory'))\n"
 '\n'
 'During handling of the above exception, another exception occurred:\n'
 '\n'
 'Traceback (most recent call last):\n'
 '  File "/tmp/kitchen/testing/salt/minion.py", line 1663, in _thread_return\n'
 '    return_data = minion_instance.executors[fname](opts, data, func, args, '
 'kwargs)\n'
 '  File "/tmp/kitchen/testing/salt/executors/direct_call.py", line 12, in '
 'execute\n'
 '    return func(*args, **kwargs)\n'
 '  File "/tmp/kitchen/testing/salt/modules/dockermod.py", line 6758, in '
 'apply_\n'
 '    return highstate(name, **kwargs)\n'
 '  File "/tmp/kitchen/testing/salt/modules/dockermod.py", line 6900, in '
 'highstate\n'
 "    return sls(name, saltenv='base', **kwargs)\n"
 '  File "/tmp/kitchen/testing/salt/modules/dockermod.py", line 6815, in sls\n'
 "    grains = call(name, 'grains.items')\n"
 '  File "/tmp/kitchen/testing/salt/modules/dockermod.py", line 6680, in call\n'
 '    ret = run_all(name, subprocess.list2cmdline(mkdirp_thin_argv))\n'
 '  File "/tmp/kitchen/testing/salt/modules/dockermod.py", line 6325, in '
 'run_all\n'
 '    keep_env=keep_env)\n'
 '  File "/tmp/kitchen/testing/salt/modules/dockermod.py", line 447, in '
 'wrapper\n'
 "    returned = wrapped(*args, **__utils__['args.clean_kwargs'](**kwargs))\n"
 '  File "/tmp/kitchen/testing/salt/modules/dockermod.py", line 6059, in _run\n'
 '    exec_driver = _get_exec_driver()\n'
 '  File "/tmp/kitchen/testing/salt/modules/dockermod.py", line 533, in '
 '_get_exec_driver\n'
 "    driver = info().get('ExecutionDriver', 'docker-exec')\n"
 '  File "/tmp/kitchen/testing/salt/modules/dockermod.py", line 1740, in info\n'
 "    return _client_wrapper('info')\n"
 '  File "/tmp/kitchen/testing/salt/modules/dockermod.py", line 423, in '
 'wrapper\n'
 "    __context__['docker.client'] = _get_client(timeout=timeout, **kwargs)\n"
 '  File "/tmp/kitchen/testing/salt/modules/dockermod.py", line 387, in '
 '_get_client\n'
 '    ret = docker.APIClient(**client_kwargs)\n'
 '  File "/usr/lib/python3.6/site-packages/docker/api/client.py", line 190, in '
 '__init__\n'
 '    self._version = self._retrieve_server_version()\n'
 '  File "/usr/lib/python3.6/site-packages/docker/api/client.py", line 215, in '
 '_retrieve_server_version\n'
 "    'Error while fetching server API version: {0}'.format(e)\n"
 'docker.errors.DockerException: Error while fetching server API version: '
 "('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))\n")
		
```

**Comment by KChandrashekhar** [comment]
Test is failing on 2019.2 branch and not on 2019.2.1 so it will be fixed in 2019.2.2 release
