### ISSUE TITLE
KeyError: 'lowpkg.version_cmp' on CentOS 7.6.1810

### ISSUE THREAD

**Issue by Rabattkarte** [saltstack/salt#53017]
### Description of Issue/Question

I ran into a similar issue over here: https://github.com/HubbleStack/Nova/issues/279
@basepi was involved back then. I have the same/similar issue today and can reproduce.

### Setup
```
$ cat defaults/settings.sls
some:
  key:
    option: some_string
    {% if salt['pkg.version_cmp'](salt['grains'].get('kernelrelease'),'4.19.36') != -1 %}
    another_option: 5
    {% endif %}
```

### Steps to Reproduce Issue
```
[root@salt-minion ~]# uname -r
3.10.0-957.12.1.el7.x86_64
```

When I issue an `highstate` on `salt-minion`, I receive this error log in the master log:
```
2019-05-14 15:25:56,110 [salt.pillar      :644 ][CRITICAL][2107] Rendering SLS 'defaults.settings' failed, render error:
Jinja error: 'lowpkg.version_cmp'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 418, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 154, in top-level template code
  File "/usr/lib/python2.7/dist-packages/salt/modules/yumpkg.py", line 593, in version_cmp
    return __salt__['lowpkg.version_cmp'](pkg1, pkg2, ignore_epoch=ignore_epoch)
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1114, in __getitem__
    func = super(LazyLoader, self).__getitem__(item)
  File "/usr/lib/python2.7/dist-packages/salt/utils/lazy.py", line 101, in __getitem__
    raise KeyError(key)
KeyError: 'lowpkg.version_cmp'

; line 154

---
[...]
some:
  key:
    option: some_string
    {% if salt['pkg.version_cmp'](salt['grains'].get('kernelrelease'),'4.19.36') != -1 %}    <======================
    another_option: 5
    {% endif %}

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 418, in render_jinja_tmpl
[...]
---
2019-05-14 15:25:56,658 [salt.pillar      :892 ][CRITICAL][2107] Pillar render error: Rendering SLS 'defaults.settings' failed. Please see master log for details.
```

#### salt-master
```
[salt-master ~]# salt-call --versions-report
Salt Version:
           Salt: 2017.7.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Sep 26 2018, 18:42:22)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.4 
         locale: UTF-8
        machine: x86_64
        release: 4.19.36
         system: Linux
        version: debian 9.4 
```

#### salt-minion
```
[salt-minion ~]# salt-call --versions-report
Salt Version:
           Salt: 2017.7.8
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Apr  9 2019, 14:30:50)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.12.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core
```

**Comment by garethgreenaway** [comment]
@Rabattkarte Thanks for the report.  Can you confirm that the following file exists:
`/usr/lib/python2.7/dist-packages/salt/modules/rpm.py` and that the python libraries for `rpm` and `rpmUtils` are both installed?

**Comment by Rabattkarte** [comment]
@garethgreenaway The only thing existent is `rpm-python-4.11.3-35.el7.x86_64`:

```
[salt-minion ~]# rpm -qa | grep -i ".*rpm.*py.*"
rpm-python-4.11.3-35.el7.x86_64
[salt-minion ~]# ls /usr/lib/python2.7/dist-packages/salt/modules/rpm.py
ls: cannot access '/usr/lib/python2.7/dist-packages/salt/modules/rpm.py': No such file or directory
```

We installed salt as described here: https://repo.saltstack.com/#rhel

**Comment by Rabattkarte** [comment]
@garethgreenaway any update on what I might be missing?

* I believe `/usr/lib/python2.7/dist-packages/salt/modules/rpm.py` is part of salt? So this file missing should be a bug if I'm not mistaken?
* Also there seems to be missing dependencies in the rpm-Files, if `libs` for `rpmUtils` and rpm are missing?

**Comment by disaster123** [comment]
this is still "unfixed"

**Comment by sagetherage** [comment]
@garethgreenaway can you please follow up, here?

**Comment by disaster123** [comment]
this is still "unfixed"

**Comment by disaster123** [comment]
@sagetherage any news? This sitll happens on CentOS while pkg.version_cmp works fine on shell

**Comment by sagetherage** [comment]
@Rabattkarte @disaster123 can either of you confirm this is still and issue on a currently supported version of Salt and python 3?

**Comment by disaster123** [comment]
@sagetherage i'm sorry i'm no longer involved in salt stuff

**Comment by sagetherage** [comment]
> @sagetherage i'm sorry i'm no longer involved in salt stuff

@disaster123 thank you for the prompt reply and noted.

**Comment by Rabattkarte** [comment]
@sagetherage unfortunately not. Currently I'm not using salt anymore and lost access to this issue's originating setup. On a second thought, CentOS is dead anyway.
