### ISSUE TITLE
integration.runners.test_jobs.ManageTest.test_lookup_jid_invalid test failures

### ISSUE THREAD

**Issue by garethgreenaway** [saltstack/salt#53034]
2019.2 failed [salt-centos-7-py2-m2crypto](https://jenkinsci.saltstack.com/job/2019.2/job/salt-centos-7-py2-m2crypto/81/testReport/junit/integration.runners.test_jobs/ManageTest/test_lookup_jid_invalid), [salt-centos-7-py2-pycryptodomex](https://jenkinsci.saltstack.com/job/2019.2/job/salt-centos-7-py2-pycryptodomex/83/testReport/junit/integration.runners.test_jobs/ManageTest/test_lookup_jid_invalid), [salt-centos-7-py2-tornado](https://jenkinsci.saltstack.com/job/2019.2/job/salt-centos-7-py2-tornado/71/testReport/junit/integration.runners.test_jobs/ManageTest/test_lookup_jid_invalid), [salt-centos-7-py3](https://jenkinsci.saltstack.com/job/2019.2/job/salt-centos-7-py3/76/testReport/junit/integration.runners.test_jobs/ManageTest/test_lookup_jid_invalid), [salt-centos-7-py3-m2crypto](https://jenkinsci.saltstack.com/job/2019.2/job/salt-centos-7-py3-m2crypto/83/testReport/junit/integration.runners.test_jobs/ManageTest/test_lookup_jid_invalid), [salt-centos-7-py3-pycryptodomex](https://jenkinsci.saltstack.com/job/2019.2/job/salt-centos-7-py3-pycryptodomex/82/testReport/junit/integration.runners.test_jobs/ManageTest/test_lookup_jid_invalid), [salt-centos-7-py3-transport](https://jenkinsci.saltstack.com/job/2019.2/job/salt-centos-7-py3-transport/74/testReport/junit/integration.runners.test_jobs/ManageTest/test_lookup_jid_invalid), [salt-fedora-28-py3](https://jenkinsci.saltstack.com/job/2019.2/job/salt-fedora-28-py3/80/testReport/junit/integration.runners.test_jobs/ManageTest/test_lookup_jid_invalid), [salt-fedora-29-py3](https://jenkinsci.saltstack.com/job/2019.2/job/salt-fedora-29-py3/80/testReport/junit/integration.runners.test_jobs/ManageTest/test_lookup_jid_invalid), [salt-opensuse-15-py3](https://jenkinsci.saltstack.com/job/2019.2/job/salt-opensuse-15-py3/65/testReport/junit/integration.runners.test_jobs/ManageTest/test_lookup_jid_invalid), [salt-ubuntu-1604-py2](https://jenkinsci.saltstack.com/job/2019.2/job/salt-ubuntu-1604-py2/79/testReport/junit/integration.runners.test_jobs/ManageTest/test_lookup_jid_invalid), [salt-ubuntu-1604-py2-m2crypto](https://jenkinsci.saltstack.com/job/2019.2/job/salt-ubuntu-1604-py2-m2crypto/79/testReport/junit/integration.runners.test_jobs/ManageTest/test_lookup_jid_invalid), [salt-ubuntu-1604-py2-pycryptodomex](https://jenkinsci.saltstack.com/job/2019.2/job/salt-ubuntu-1604-py2-pycryptodomex/80/testReport/junit/integration.runners.test_jobs/ManageTest/test_lookup_jid_invalid), [salt-ubuntu-1604-py2-transport](https://jenkinsci.saltstack.com/job/2019.2/job/salt-ubuntu-1604-py2-transport/75/testReport/junit/integration.runners.test_jobs/ManageTest/test_lookup_jid_invalid), [salt-ubuntu-1604-py3](https://jenkinsci.saltstack.com/job/2019.2/job/salt-ubuntu-1604-py3/78/testReport/junit/integration.runners.test_jobs/ManageTest/test_lookup_jid_invalid), [salt-ubuntu-1604-py3-m2crypto](https://jenkinsci.saltstack.com/job/2019.2/job/salt-ubuntu-1604-py3-m2crypto/79/testReport/junit/integration.runners.test_jobs/ManageTest/test_lookup_jid_invalid), [salt-ubuntu-1604-py3-pycryptodomex](https://jenkinsci.saltstack.com/job/2019.2/job/salt-ubuntu-1604-py3-pycryptodomex/83/testReport/junit/integration.runners.test_jobs/ManageTest/test_lookup_jid_invalid), [salt-ubuntu-1604-py3-transport](https://jenkinsci.saltstack.com/job/2019.2/job/salt-ubuntu-1604-py3-transport/74/testReport/junit/integration.runners.test_jobs/ManageTest/test_lookup_jid_invalid), [salt-ubuntu-1804-py2](https://jenkinsci.saltstack.com/job/2019.2/job/salt-ubuntu-1804-py2/80/testReport/junit/integration.runners.test_jobs/ManageTest/test_lookup_jid_invalid), [salt-ubuntu-1804-py3](https://jenkinsci.saltstack.com/job/2019.2/job/salt-ubuntu-1804-py3/82/testReport/junit/integration.runners.test_jobs/ManageTest/test_lookup_jid_invalid), [salt-windows-2019-py2](https://jenkinsci.saltstack.com/job/2019.2/job/salt-windows-2019-py2/64/testReport/junit/integration.runners.test_jobs/ManageTest/test_lookup_jid_invalid)
---

u'Passed invalid arguments:' not found in u'Exception occurred in runner jobs.lookup_jid: Traceback (most recent call last):\n  File "C:\\\\Users\\\\ADMINI~1\\\\AppData\\\\Local\\\\Temp\\\\kitchen\\\\testing\\salt\\client\\mixins.py", line 374, in low\n    data[\'return\'] = self.functions[fun](*args, **kwargs)\nTypeError: lookup_jid() takes at least 1 argument (0 given)\n'

```

Traceback (most recent call last):
  File "c:\users\admini~1\appdata\local\temp\kitchen\testing\tests\integration\runners\test_jobs.py", line 39, in test_lookup_jid_invalid
    self.assertIn(expected, ret['return'])
AssertionError: u'Passed invalid arguments:' not found in u'Exception occurred in runner jobs.lookup_jid: Traceback (most recent call last):\n  File "C:\\\\Users\\\\ADMINI~1\\\\AppData\\\\Local\\\\Temp\\\\kitchen\\\\testing\\salt\\client\\mixins.py", line 374, in low\n    data[\'return\'] = self.functions[fun](*args, **kwargs)\nTypeError: lookup_jid() takes at least 1 argument (0 given)\n'
		
```

**Comment by garethgreenaway** [comment]
Fixed with https://github.com/saltstack/salt/pull/53021
