### ISSUE TITLE
integration.output.test_output.OutputReturnTest.test_static_simple test failures

### ISSUE THREAD

**Issue by garethgreenaway** [saltstack/salt#53057]
2018.3 failed [salt-ubuntu-1604-py2-tcp](https://jenkinsci.saltstack.com/job/2018.3/job/salt-ubuntu-1604-py2-tcp/39/testReport/junit/integration.output.test_output/OutputReturnTest/test_static_simple)
---

[Errno 12] Cannot allocate memory

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/output/test_output.py", line 182, in test_static_simple
    ret = self.run_salt('"minion" test.ping --static')
  File "/tmp/kitchen/testing/tests/support/case.py", line 513, in run_salt
    popen_kwargs=popen_kwargs)
  File "/tmp/kitchen/testing/tests/support/case.py", line 360, in run_script
    process = subprocess.Popen(cmd, **popen_kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1235, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
		
```

**Comment by twangboy** [comment]
Failed on develop:
May 21, 2019 10:44:00 PM - https://jenkinsci.saltstack.com/job/develop/job/salt-centos-6-py2/235/
