### ISSUE TITLE
unit.test_state.StateCompilerTestCase.test_verify_unless_parse test failures

### ISSUE THREAD

**Issue by garethgreenaway** [saltstack/salt#53101]
develop failed [salt-windows-2019-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2019-py2/87/testReport/junit/unit.test_state/StateCompilerTestCase/test_verify_unless_parse)
---

File not found: c:\etc\crontab

```

Traceback (most recent call last):
  File "c:\users\admini~1\appdata\local\temp\kitchen\testing\tests\unit\test_state.py", line 195, in test_verify_unless_parse
    return_result = state_obj._run_check_unless(low_data, '')
  File "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\kitchen\\testing\salt\state.py", line 958, in _run_check_unless
    result = self.functions[entry.pop('fun')](*entry.pop('args'), **entry)
  File "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\kitchen\\testing\salt\modules\file.py", line 2859, in search
    ignore_if_missing=ignore_if_missing)
  File "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\kitchen\\testing\salt\modules\file.py", line 2262, in replace
    raise SaltInvocationError('File not found: {0}'.format(path))
SaltInvocationError: File not found: c:\etc\crontab
		
```

**Comment by twangboy** [comment]
Failing on develop:
May 21, 2019 5:42:00 PM - https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2019-py2/95/
May 21, 2019 9:43:00 PM - https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2016-py2/49/
