### ISSUE TITLE
ps.top yields error in Window masterless minion

### ISSUE THREAD

**Issue by iacopo-papalini** [saltstack/salt#53110]
### Setup
Install salt minon and configure it as masterless

### Steps to Reproduce Issue
```
C:\salt>salt-call.bat ps.top 3 10 -l debug
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Including configuration from 'c:\salt\conf\minion.d\_schedule.conf'
[DEBUG   ] Reading configuration from c:\salt\conf\minion.d\_schedule.conf
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Including configuration from 'c:\salt\conf\minion.d\_schedule.conf'
[DEBUG   ] Reading configuration from c:\salt\conf\minion.d\_schedule.conf
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded ps.top
[DEBUG   ] LazyLoaded direct_call.execute

Passed invalid arguments: unorderable types: Process() < Process().

Usage:

    Return a list of top CPU consuming processes during the interval.
    num_processes = return the top N CPU consuming processes
    interval = the number of seconds to sample CPU usage over

    CLI Examples:

    .. code-block:: bash

        salt '*' ps.top

        salt '*' ps.top 5 10

Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 237, in call
    ret['return'] = self.minion.executors[fname](self.opts, data, func, args, kwargs)
  File "C:\salt\bin\lib\site-packages\salt\executors\direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\modules\ps.py", line 157, in top
    for idx, (diff, process) in enumerate(reversed(sorted(usage))):
TypeError: unorderable types: Process() < Process()

```
### Versions Report
salt-minion 2019.2.0 (Fluorine)

**Comment by iacopo-papalini** [comment]
It seems a Python error: the Process() class isn't sortable

**Comment by garethgreenaway** [comment]
@saltstack/team-windows FYI.

**Comment by iacopo-papalini** [comment]
Actually I should rename the title - I can reproduce it in a minion connected to a master
