### ISSUE TITLE
yaml_encode and cmd.run

### ISSUE THREAD

**Issue by scubahub** [saltstack/salt#53163]
### Description of Issue/Question
Trying to invoke cmd.run using yaml_encode to handle escaping, but I get 
```
          ID: add x.y.z.com to replica set
    Function: cmd.run
        Name: mongo --quiet --eval 'printjson(rs.add({host: "x.y.z.com"}))'
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1919, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1918, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/cmd.py", line 892, in run
                  name, timeout=timeout, python_shell=True, **cmd_kwargs
              TypeError: run_all() got multiple values for keyword argument 'cmd'
     Started: 01:06:27.821132
    Duration: 1.142 ms
     Changes:
```

### Setup
I have a command string with '{', '}', and ':' in it.  I tried various ways to escape then I discovered the yaml_encode filter, so the state snippet is:
```
 initialize replica set:
  cmd.run:
    - name: |
        mongo --quiet --eval "printjson(rs.initiate())"
        sleep 60
    - unless: test $(mongo --quiet --eval "s=rs.status(); print( 'set' in s );") == "true"

 {%- for secondary in secondaries %}
    {%- set cmd = "mongo --quiet --eval 'printjson(rs.add({host: \"" + secondary + "\"}))'" %}
add {{ secondary }} to replica set:
  cmd.run:
    - name: {{ cmd | yaml_encode }}
    - requires:
      cmd: initialize replica set
  {%- endfor %}

{%- endif %}
```
Where secondaries is a list of fully qualified host names.

### Steps to Reproduce Issue
When I run the state it fails.

Debug logs
```
[INFO    ] Running state [mongo --quiet --eval "printjson(rs.initiate())"
sleep 60] at time 01:21:22.425286
[INFO    ] Executing state cmd.run for [mongo --quiet --eval "printjson(rs.initiate())"
sleep 60]
[DEBUG   ] LazyLoaded cmd.retcode
[INFO    ] Executing command 'test $(mongo --quiet --eval "s=rs.status(); print( 'set' in s );") == "true"' in directory '/root'
[DEBUG   ] Last command return code: 0
[INFO    ] unless condition is true
[INFO    ] Completed state [mongo --quiet --eval "printjson(rs.initiate())"
sleep 60] at time 01:21:22.485453 (duration_in_ms=60.167)
[INFO    ] Running state [mongo --quiet --eval 'printjson(rs.add({host: "x.y.z.com"}))'] at time 01:21:22.485946
[INFO    ] Executing state cmd.run for [mongo --quiet --eval 'printjson(rs.add({host: "x.y.z.com"}))']
[DEBUG   ] An exception occurred in this state: run_all() got multiple values for keyword argument 'cmd'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 1919, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1918, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/states/cmd.py", line 892, in run
    name, timeout=timeout, python_shell=True, **cmd_kwargs
TypeError: run_all() got multiple values for keyword argument 'cmd'
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 1919, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1918, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/states/cmd.py", line 892, in run
    name, timeout=timeout, python_shell=True, **cmd_kwargs
TypeError: run_all() got multiple values for keyword argument 'cmd'

[INFO    ] Completed state [mongo --quiet --eval 'printjson(rs.add({host: "x.y.z.com"}))'] at time 01:21:22.488596 (duration_in_ms=2.651)
```
Note if I copy/paste the Name from the error into the shell it works fine.

### Versions Report
```
Salt Version:
           Salt: 2018.3.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Oct 30 2018, 23:45:53)
   python-gnupg: 0.4.4
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.10.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core
```

**Comment by scubahub** [comment]
issue is the indention under the -requires.. sigh
