### ISSUE TITLE
integration.states.test_ansiblegate.AnsiblePlaybooksTestCase.test_ansible_playbook

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#53187]
```
Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/support/helpers.py", line 214, in wrap
    raise exc
AssertionError: False is not True. Salt Comment:
An exception occurred in this state: Traceback (most recent call last):
  File "/tmp/kitchen/testing/salt/state.py", line 1998, in call
    ret = self.states[cdata['full']](*cdata['args'], **cdata['kwargs'])
  File "/tmp/kitchen/testing/salt/loader.py", line 2056, in wrapper
    return f(*args, **kwargs)
  File "<string>", line 2, in playbooks
  File "/tmp/kitchen/testing/salt/utils/decorators/path.py", line 23, in wrapped
    return function(*args, **kwargs)
  File "/tmp/kitchen/testing/salt/states/ansiblegate.py", line 180, in playbooks
    checks = __salt__['ansible.playbooks'](name, rundir=rundir, check=True, diff=True, **ansible_kwargs)
  File "<string>", line 2, in playbooks
  File "/tmp/kitchen/testing/salt/utils/decorators/path.py", line 23, in wrapped
    return function(*args, **kwargs)
  File "/tmp/kitchen/testing/salt/modules/ansiblegate.py", line 376, in playbooks
    ret = __salt__['cmd.run_all'](**cmd_kwargs)
  File "/tmp/kitchen/testing/salt/modules/cmdmod.py", line 2195, in run_all
    **kwargs)
  File "/tmp/kitchen/testing/salt/modules/cmdmod.py", line 693, in _run
    raise CommandExecutionError(msg)
CommandExecutionError: Unable to run command '[u'ansible-playbook', u'remove.yml', u'--check', u'--diff', u'--inventory=/tmp/tmpN1tMgKinventory', u'--forks=5']' with the context '{u'timeout': None, u'with_communicate': True, u'shell': False, u'bg': False, u'stderr': -1, u'env': {'LC_NUMERIC': 'C', 'ANSIBLE_RETRY_FILES_ENABLED': '0', 'TESTS_XML_OUTPUT_DIR': '/tmp/xml-unittests-output/', 'TESTS_LOG_LEVEL': '2', 'LC_CTYPE': 'C', 'LESSOPEN': '||/usr/bin/lesspipe.sh %s', 'SSH_CLIENT': '10.200.26.197 35420 22', 'LOGNAME': 'root', 'USER': 'root', 'HOME': '/root', 'LC_PAPER': 'C', 'PATH': '/tmp/kitchen/testing/tests/integration/mockbin:/sbin:/bin:/usr/sbin:/usr/bin', 'COVERAGE_PROCESS_START': '', 'LANG': 'en_US.UTF-8', 'TERM': 'xterm', 'SHELL': '/bin/bash', 'LANGUAGE': 'C', 'LC_MEASUREMENT': 'C', 'LESS_TERMCAP_me': '\x1b[0m', 'LESS_TERMCAP_md': '\x1b[01;38;5;208m', 'LESS_TERMCAP_mb': '\x1b[01;31m', 'PYTHONPATH': '/usr/local/lib/python2.7/site-packages/pytestsalt/salt/coverage', 'AWS_ELB_HOME': '/opt/aws/apitools/elb', 'SUDO_USER': 'ec2-user', 'JAVA_HOME': '/usr/lib/jvm/jre', 'EC2_HOME': '/opt/aws/apitools/ec2', 'LC_MONETARY': 'C', 'USERNAME': 'root', 'ANSIBLE_STDOUT_CALLBACK': 'json', 'LC_ADDRESS': 'C', 'COVERAGE_OPTIONS': '{"source": ["/tmp/kitchen/testing/salt"], "branch": true, "data_suffix": true}', 'SHLVL': '1', 'SUDO_UID': '500', 'SUDO_GID': '500', 'AWS_AUTO_SCALING_HOME': '/opt/aws/apitools/as', '_': '/usr/bin/sudo', 'DESTRUCTIVE_TESTS': 'True', 'LC_IDENTIFICATION': 'C', 'LESS_TERMCAP_ue': '\x1b[0m', 'SUDO_COMMAND': '/usr/bin/python2.7 /tmp/kitchen/testing/tests/runtests.py --sysinfo --output-columns=80 --transport=zeromq -v --run-destructive --coverage-xml=/tmp/coverage.xml --xml=/tmp/xml-unittests-output/ --ssh', 'LC_MESSAGES': 'C', 'AWS_PATH': '/opt/aws', 'SSH_TTY': '/dev/pts/0', 'LC_COLLATE': 'C', 'AWS_CLOUDWATCH_HOME': '/opt/aws/apitools/mon', 'LC_TELEPHONE': 'C', 'LESS_TERMCAP_se': '\x1b[0m', 'EC2_AMITOOL_HOME': '/opt/aws/amitools/ec2', 'PWD': '/home/ec2-user', 'LESS_TERMCAP_us': '\x1b[04;38;5;111m', 'LC_NAME': 'C', 'MAIL': '/var/mail/ec2-user', 'LC_TIME': 'C', 'SSH_CONNECTION': '10.200.26.197 35420 10.200.50.29 22'}, u'stdout': -1, u'close_fds': True, u'stdin': None, u'cwd': u'/tmp/salt-tests-tmpdir/rootdir/cache/extrn_files/base/github.com/gtmanfred/playbooks.git'}', reason: [Errno 2] No such file or directory
```

**Comment by twangboy** [comment]
Failing on develop:
May 21, 2019 4:11:00 PM - https://jenkinsci.saltstack.com/job/develop/job/salt-amazon-1-py2/1/

**Comment by DmitryKuzmenko** [comment]
The same is happening on 2019.2:
https://jenkinsci.saltstack.com/job/2019.2/job/salt-amazon-1-py2/57/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_ini/
https://jenkinsci.saltstack.com/job/2019.2/job/salt-amazon-1-py2/57/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_script/
https://jenkinsci.saltstack.com/job/2019.2/job/salt-amazon-1-py2/57/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_yml/

**Comment by DmitryKuzmenko** [comment]
Duplicates #53084
