### ISSUE TITLE
Issue with zabbix_user.present on Zabbix 4.0+

### ISSUE THREAD

**Issue by alcane** [saltstack/salt#53203]
### Description of Issue/Question

Salt is returning errors when calling the `zabbix_user.present` state on a Zabbix server >= 4.0

The zabbix api changed between zabbix 3.4 and zabbix 4.0, the "usermedia" object is not handled by the same methods now....

### Setup
- Require a Zabbix server/api >= 4.0
- Create a Zabbix Super Admin user which will be used to connect salt to zabbix.

### Steps to Reproduce Issue

Setup a state like:

```
zabbix_server_users_{{username}}:
    zabbix_user.present:
        - alias: {{username}}
        - passwd: 'none'
        - password_reset: False
        - usrgrps:
            - 4
        - _connection_user: {{pillar.zabbix.api.user}}
        - _connection_password: {{pillar.zabbix.api.password}}
        - _connection_url: {{pillar.zabbix.api.url}}
```

This returns:

```
----------
          ID: zabbix_server_users_xxxxxxx
    Function: zabbix_user.present
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1933, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1939, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/zabbix_user.py", line 256, in prese
                  user_medias = __salt__['zabbix.user_getmedia'](userid, **connection_args)
                File "/usr/lib/python2.7/site-packages/salt/modules/zabbix.py", line 694, in user_getm
                  ret = _query(method, params, conn_args['url'], conn_args['auth'])
                File "/usr/lib/python2.7/site-packages/salt/modules/zabbix.py", line 172, in _query
                  raise SaltException('Zabbix API: {} ({})'.format(ret['error']['message'], ret['error
              SaltException: Zabbix API: Invalid params. (Incorrect API "usermedia".)
     Started: 11:59:27.877958
    Duration: 375.257 ms
     Changes:
```

### Versions Report

```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.8.0
      docker-py: 1.10.6-a1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.31.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.2.5
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Apr  9 2019, 14:30:50)
   python-gnupg: 0.4.4
         PyYAML: 3.13
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.5.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core
```

**Comment by devney** [comment]
I am also having this issue.  I have a state file

devney_user:
  zabbix_user.present:
    - _connection_user: {{ pillar['_connection_user'] }}
    - _connection_password: {{ pillar['_connection_password'] }}
    - _connection_url: {{ pillar['zabbix_url'] }}
    - alias: devney
    - passwd: abcd1234
    - password_reset: False
    - usrgrps:
      - 7
    - medias:
      - devney@dummydomain
        - mediatype: mail
        - period: '1-7,00:00-24:00'
        - severity: NIWAHD


And this is the error:
----------
          ID: devney_user
    Function: zabbix_user.present
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 2153, in call
                  ret = self.states[cdata["full"]](
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2106, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/zabbix_user.py", line 282, in present
                  user_medias = __salt__["zabbix.user_getmedia"](userid, **connection_args)
                File "/usr/lib/python3/dist-packages/salt/modules/zabbix.py", line 738, in user_getmedia
                  ret = _query(method, params, conn_args["url"], conn_args["auth"])
                File "/usr/lib/python3/dist-packages/salt/modules/zabbix.py", line 190, in _query
                  raise SaltException(
              salt.exceptions.SaltException: Zabbix API: Invalid params. (Incorrect API "usermedia".)
     Started: 02:18:08.333171
    Duration: 447.871 ms
     Changes:
----------

**Comment by ShaneHutter** [comment]
In the zabbix module, usermedia needs to be replaced with mediatype, so that mediatype.get is called.

After this the sendto field needs to pass a list instead of a string.
```
  - medias:
      - email_notifications:
        - sendto:
          - user@hostname.tld
        - mediatype: mail
        - period: '1-7,00:00-24:00'
        - severity: HD
```
From this point I'm getting a new error:
```
              salt.exceptions.SaltException: Zabbix API: Invalid params. (Incorrect method "user.addmedia".)
```

This section is critical to my organisation, so I'll let you know if I get any further.

**Comment by ShaneHutter** [comment]
It looks like the user.addmedia method is no longer in Zabbix >= 4.0

3.0 documentation for the API:
https://www.zabbix.com/documentation/3.0/manual/api/reference/user

And you can see it's not listed in the 5.2 documentation:
https://www.zabbix.com/documentation/current/manual/api/reference/user

**Comment by rsolano-isb** [comment]
This bug report is over 2.5 years old, and was automatically marked closed by a robot. Will any Salt developer see this, or does a new bug report need to be opened?
I can confirm that this issue is still present. I'm on Zabbix 5.4. My salt version:
```
$ salt-minion --version
salt-minion 3004
```
My Salt state:
```
{% for user, data in pillar['zabbix_users'].items() %}  
zabbix_user_{{ user }}:                                 
  zabbix_user.present:                                  
    - firstname: {{ user }}                             
    - alias: {{ user }}                                 
    {% for k, v in data.items()  %}                     
    - {{ k }}: {{ v }}                                  
    {% endfor %}                                        
{% endfor %}         
```
And my error message from the salt run:
```
 ID: zabbix_user_[redacted]
Function: zabbix_user.present
  Result: False
 Comment: An exception occurred in this state: Traceback (most recent call last):
            File "/usr/lib/python3/dist-packages/salt/state.py", line 2179, in call
              ret = self.states[cdata["full"]](
            File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 149, in __call__
              return self.loader.run(run_func, *args, **kwargs)
            File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1201, in run
              return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
            File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1216, in _run_as
              return _func_or_method(*args, **kwargs)
            File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1249, in wrapper
              return f(*args, **kwargs)
            File "/usr/lib/python3/dist-packages/salt/states/zabbix_user.py", line 269, in present
              user_medias = __salt__["zabbix.user_getmedia"](userid, **connection_args)
            File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 149, in __call__
              return self.loader.run(run_func, *args, **kwargs)
            File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1201, in run
              return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
            File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1216, in _run_as
              return _func_or_method(*args, **kwargs)
            File "/usr/lib/python3/dist-packages/salt/modules/zabbix.py", line 745, in user_getmedia
              ret = _query(method, params, conn_args["url"], conn_args["auth"])
            File "/usr/lib/python3/dist-packages/salt/modules/zabbix.py", line 185, in _query
              raise SaltException(
          salt.exceptions.SaltException: Zabbix API: Method not found. (Incorrect API "usermedia".)
 Started: 10:00:57.020506
Duration: 564.395 ms
 Changes:   
```

**Comment by devopssankar** [comment]
The issue still persists
