### ISSUE TITLE
Win Master fails test integration.proxy.test_shell

### ISSUE THREAD

**Issue by cmcmarrow** [saltstack/salt#53214]
### Setup
Be on windows with salt 2019

### Steps to Reproduce Issue
`python runtests.py --run-destructive -n integration.proxy.test_shell`

### Error
```
===================  Overall Tests Report  =======================
*** integration.proxy.test_shell Tests  ******************************
 --------  Tests with Errors  ----------------------------------------
   -> integration.proxy.test_shell.ProxyCallerSimpleTestCase.test_can_it_ping
       Traceback (most recent call last):
         File "c:\users\administrator\downloads\salt-develop\tests\integration\proxy\test_shell.py", line 31, in test_can_it_ping
           ret = self._load_return(self.run_call('--proxyid proxytest --out=json test.ping'))
         File "c:\users\administrator\downloads\salt-develop\tests\integration\proxy\test_shell.py", line 25, in _load_return
           return json.loads('\n'.join(ret))
         File "C:\\Users\\Administrator\\Downloads\\salt-develop\salt\utils\json.py", line 93, in loads
           return json_module.loads(s, **kwargs)
         File "C:\Python35\lib\json\__init__.py", line 319, in loads
           return _default_decoder.decode(s)
         File "C:\Python35\lib\json\decoder.py", line 339, in decode
           obj, end = self.raw_decode(s, idx=_w(s, 0).end())
         File "C:\Python35\lib\json\decoder.py", line 357, in raw_decode
           raise JSONDecodeError("Expecting value", s, err.value) from None
       json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
   ...................................................................
   -> integration.proxy.test_shell.ProxyCallerSimpleTestCase.test_grains_items
       Traceback (most recent call last):
         File "c:\users\administrator\downloads\salt-develop\tests\integration\proxy\test_shell.py", line 63, in test_grains_items
           ret = self._load_return(self.run_call('--proxyid proxytest --out=json grains.items'))
         File "c:\users\administrator\downloads\salt-develop\tests\integration\proxy\test_shell.py", line 25, in _load_return
           return json.loads('\n'.join(ret))
         File "C:\\Users\\Administrator\\Downloads\\salt-develop\salt\utils\json.py", line 93, in loads
           return json_module.loads(s, **kwargs)
         File "C:\Python35\lib\json\__init__.py", line 319, in loads
           return _default_decoder.decode(s)
         File "C:\Python35\lib\json\decoder.py", line 339, in decode
           obj, end = self.raw_decode(s, idx=_w(s, 0).end())
         File "C:\Python35\lib\json\decoder.py", line 357, in raw_decode
           raise JSONDecodeError("Expecting value", s, err.value) from None
       json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
   ...................................................................
   -> integration.proxy.test_shell.ProxyCallerSimpleTestCase.test_list_pkgs
       Traceback (most recent call last):
         File "c:\users\administrator\downloads\salt-develop\tests\integration\proxy\test_shell.py", line 39, in test_list_pkgs
           ret = self._load_return(self.run_call('--proxyid proxytest --out=json pkg.list_pkgs'))
         File "c:\users\administrator\downloads\salt-develop\tests\integration\proxy\test_shell.py", line 25, in _load_return
           return json.loads('\n'.join(ret))
         File "C:\\Users\\Administrator\\Downloads\\salt-develop\salt\utils\json.py", line 93, in loads
           return json_module.loads(s, **kwargs)
         File "C:\Python35\lib\json\__init__.py", line 319, in loads
           return _default_decoder.decode(s)
         File "C:\Python35\lib\json\decoder.py", line 339, in decode
           obj, end = self.raw_decode(s, idx=_w(s, 0).end())
         File "C:\Python35\lib\json\decoder.py", line 357, in raw_decode
           raise JSONDecodeError("Expecting value", s, err.value) from None
       json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
   ...................................................................
   -> integration.proxy.test_shell.ProxyCallerSimpleTestCase.test_service_get_all
       Traceback (most recent call last):
         File "c:\users\administrator\downloads\salt-develop\tests\integration\proxy\test_shell.py", line 59, in test_service_get_all
           ret = self._load_return(self.run_call('--proxyid proxytest --out=json service.get_all'))
         File "c:\users\administrator\downloads\salt-develop\tests\integration\proxy\test_shell.py", line 25, in _load_return
           return json.loads('\n'.join(ret))
         File "C:\\Users\\Administrator\\Downloads\\salt-develop\salt\utils\json.py", line 93, in loads
           return json_module.loads(s, **kwargs)
         File "C:\Python35\lib\json\__init__.py", line 319, in loads
           return _default_decoder.decode(s)
         File "C:\Python35\lib\json\decoder.py", line 339, in decode
           obj, end = self.raw_decode(s, idx=_w(s, 0).end())
         File "C:\Python35\lib\json\decoder.py", line 357, in raw_decode
           raise JSONDecodeError("Expecting value", s, err.value) from None
       json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
   ...................................................................
   -> integration.proxy.test_shell.ProxyCallerSimpleTestCase.test_service_list
       Traceback (most recent call last):
         File "c:\users\administrator\downloads\salt-develop\tests\integration\proxy\test_shell.py", line 50, in test_service_list
           ret = self._load_return(self.run_call('--proxyid proxytest --out=json service.list'))
         File "c:\users\administrator\downloads\salt-develop\tests\integration\proxy\test_shell.py", line 25, in _load_return
           return json.loads('\n'.join(ret))
         File "C:\\Users\\Administrator\\Downloads\\salt-develop\salt\utils\json.py", line 93, in loads
           return json_module.loads(s, **kwargs)
         File "C:\Python35\lib\json\__init__.py", line 319, in loads
           return _default_decoder.decode(s)
         File "C:\Python35\lib\json\decoder.py", line 339, in decode
           obj, end = self.raw_decode(s, idx=_w(s, 0).end())
         File "C:\Python35\lib\json\decoder.py", line 357, in raw_decode
           raise JSONDecodeError("Expecting value", s, err.value) from None
       json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
   ...................................................................
   -> integration.proxy.test_shell.ProxyCallerSimpleTestCase.test_service_start
       Traceback (most recent call last):
         File "c:\users\administrator\downloads\salt-develop\tests\integration\proxy\test_shell.py", line 54, in test_service_start
           ret = self._load_return(self.run_call('--proxyid proxytest --out=json service.start samba'))
         File "c:\users\administrator\downloads\salt-develop\tests\integration\proxy\test_shell.py", line 25, in _load_return
           return json.loads('\n'.join(ret))
         File "C:\\Users\\Administrator\\Downloads\\salt-develop\salt\utils\json.py", line 93, in loads
           return json_module.loads(s, **kwargs)
         File "C:\Python35\lib\json\__init__.py", line 319, in loads
           return _default_decoder.decode(s)
         File "C:\Python35\lib\json\decoder.py", line 339, in decode
           obj, end = self.raw_decode(s, idx=_w(s, 0).end())
         File "C:\Python35\lib\json\decoder.py", line 357, in raw_decode
           raise JSONDecodeError("Expecting value", s, err.value) from None
       json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
   ...................................................................
   -> integration.proxy.test_shell.ProxyCallerSimpleTestCase.test_upgrade
       Traceback (most recent call last):
         File "c:\users\administrator\downloads\salt-develop\tests\integration\proxy\test_shell.py", line 45, in test_upgrade
           ret = self._load_return(self.run_call('--proxyid proxytest --out=json pkg.upgrade'))
         File "c:\users\administrator\downloads\salt-develop\tests\integration\proxy\test_shell.py", line 25, in _load_return
           return json.loads('\n'.join(ret))
         File "C:\\Users\\Administrator\\Downloads\\salt-develop\salt\utils\json.py", line 93, in loads
           return json_module.loads(s, **kwargs)
         File "C:\Python35\lib\json\__init__.py", line 319, in loads
           return _default_decoder.decode(s)
         File "C:\Python35\lib\json\decoder.py", line 339, in decode
           obj, end = self.raw_decode(s, idx=_w(s, 0).end())
         File "C:\Python35\lib\json\decoder.py", line 357, in raw_decode
           raise JSONDecodeError("Expecting value", s, err.value) from None
       json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
   ...................................................................
 ---------------------------------------------------------------------
======================================================================
FAILED (total=7, skipped=0, passed=0, failures=0, errors=7)
=======================  Overall Tests Report  =======================
```
### Versions Report
Salt Version:
Salt: 2019.2.0

Dependency Versions:
cffi: 1.11.5
cherrypy: unknown
dateutil: 2.7.5
docker-py: 2.7.0
gitdb: 2.0.5
gitpython: 2.1.10
Jinja2: 2.10
libgit2: Not Installed
M2Crypto: Not Installed
Mako: 1.0.7
msgpack-pure: Not Installed
msgpack-python: 0.6.1
mysql-python: Not Installed
pycparser: 2.19
pycrypto: 2.6.1
pycryptodome: 3.8.1
pygit2: Not Installed
Python: 3.5.4 (v3.5.4:3f56838, Aug 8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]
python-gnupg: 0.4.3
PyYAML: 3.13
PyZMQ: 17.1.2
smmap: 2.0.5
timelib: 0.2.4
Tornado: 4.5.3
ZMQ: 4.2.5

System Versions:
dist:
locale: cp1252
machine: AMD64
release: 2016Server
system: Windows
version: 2016Server 10.0.14393 SP0 Multiprocessor Free

**Comment by cmcmarrow** [comment]
This could be a power-shell to Json problem. If so I would do a XML work around. I suggest this because Power-shell some times does not format Json correctly.
