### ISSUE TITLE
unit.utils.test_parsers failing amazon python3 

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#53277]
The tests:

```
unit.utils.test_parsers.SaltCloudParserTestCase.test_get_console_log_level_with_file_log_level
unit.utils.test_parsers.SaltCloudParserTestCase.test_get_log_file_cli
unit.utils.test_parsers.SaltCloudParserTestCase.test_get_log_file_config
unit.utils.test_parsers.SaltCloudParserTestCase.test_get_log_file_default
unit.utils.test_parsers.SaltCloudParserTestCase.test_get_log_file_level_cli
unit.utils.test_parsers.SaltCloudParserTestCase.test_get_log_file_level_config
unit.utils.test_parsers.SaltCloudParserTestCase.test_get_log_file_level_default
unit.utils.test_parsers.SaltCloudParserTestCase.test_get_log_level_cli
unit.utils.test_parsers.SaltCloudParserTestCase.test_get_log_level_config
unit.utils.test_parsers.SaltCloudParserTestCase.test_get_log_level_default
unit.utils.test_parsers.SaltCloudParserTestCase.test_log_created
```

fail on amazon python3:

https://jenkinsci.saltstack.com/job/2019.2.1/view/Python3/job/salt-amazon-2-py3/17/#showFailuresLink

```
Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/unit/utils/test_parsers.py", line 475, in test_get_console_log_level_with_file_log_level
    parser.parse_args(args)
  File "/tmp/kitchen/testing/salt/utils/parsers.py", line 3230, in parse_args
    from salt.cloud import libcloudfuncs
  File "/tmp/kitchen/testing/salt/cloud/libcloudfuncs.py", line 18, in <module>
    import libcloud
  File "/tmp/kitchen/testing/.nox/runtests-parametrized-3-coverage-true-crypto-none-transport-zeromq/lib/python3.7/site-packages/libcloud/__init__.py", line 30, in <module>
    import paramiko
  File "/tmp/kitchen/testing/.nox/runtests-parametrized-3-coverage-true-crypto-none-transport-zeromq/lib/python3.7/site-packages/paramiko/__init__.py", line 30, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/tmp/kitchen/testing/.nox/runtests-parametrized-3-coverage-true-crypto-none-transport-zeromq/lib/python3.7/site-packages/paramiko/transport.py", line 66, in <module>
    from paramiko.sftp_client import SFTPClient
  File "/tmp/kitchen/testing/.nox/runtests-parametrized-3-coverage-true-crypto-none-transport-zeromq/lib/python3.7/site-packages/paramiko/sftp_client.py", line 41, in <module>
    from paramiko.sftp_file import SFTPFile
  File "/tmp/kitchen/testing/.nox/runtests-parametrized-3-coverage-true-crypto-none-transport-zeromq/lib/python3.7/site-packages/paramiko/sftp_file.py", line 66
    self._close(async=True)
                    ^
SyntaxError: invalid syntax
```

**Comment by Ch3LL** [comment]
these tests are also failing for the same reason:

```
unittest.loader._FailedTest.integration.shell.test_cloud
unittest.loader._FailedTest.unit.cloud.clouds.test_dimensiondata
unittest.loader._FailedTest.unit.cloud.clouds.test_gce
unittest.loader._FailedTest.unit.cloud.clouds.test_joyent
unittest.loader._FailedTest.unit.cloud.clouds.test_nova
unittest.loader._FailedTest.unit.cloud.test_libcloudfuncs
unittest.loader._FailedTest.unit.modules.test_boto_elb
unittest.loader._FailedTest.unit.modules.test_boto_route53
unittest.loader._FailedTest.unit.modules.test_boto_secgroup
unittest.loader._FailedTest.unit.modules.test_boto_vpc
unittest.loader._FailedTest.unit.modules.test_dockermod
unittest.loader._FailedTest.unit.modules.test_junos
unittest.loader._FailedTest.unit.modules.test_libcloud_compute
unittest.loader._FailedTest.unit.modules.test_libcloud_dns
unittest.loader._FailedTest.unit.modules.test_libcloud_loadbalancer
unittest.loader._FailedTest.unit.modules.test_libcloud_storage
unittest.loader._FailedTest.unit.states.test_boto_vpc
unittest.loader._FailedTest.unit.states.test_docker_image
unittest.loader._FailedTest.unit.states.test_docker_volume
unittest.loader._FailedTest.unit.states.test_libcloud_dns
unittest.loader._FailedTest.unit.utils.test_botomod
unittest.loader._FailedTest.unit.utils.test_docker
```

**Comment by Akm0d** [comment]
Before digging in my guess is that this is because "async" is a keyword in python3 and we just need to change that variable name for all those test cases.

**Comment by Akm0d** [comment]
Ok... so digging deeper it seems we just need to update the version of paramiko for the amazon py3 instance.  I'm not seeing the naming problem in paramiko==2.4.2 but I'll see what the earliest version of paramiko with that change is

**Comment by Akm0d** [comment]
The earliest version of paramiko with this change is 2.2.3.  Now I just need to find out where it's being declared in a yaml file somewhere and update it and we can have a PR to fix this.
