### ISSUE TITLE
system.set_computer_desc does not work in 2019.2.0 on windows 

### ISSUE THREAD

**Issue by mbochenk** [saltstack/salt#53378]
### Description of Issue
`system.set_computer_desc` returns error `Passed invalid arguments to system.set_computer_desc: unsupported operand type(s) for +=: 'int' and 'NoneType'`
This works on 2018.3.3 but fails on 2019.2.0

### Setup
Minion freshly deployed via salt-cloud and salt-minion is running on minion. 
both module and state fail:
```
set-computer-desc:
  system.computer_desc:
    - name: {{ computer_id }}
```
```
salt test-minion system.set_computer_desc 'test'
```
### Steps to Reproduce Issue
Run `salt test-minion system.set_computer_desc 'test'` or `salt-call system.set_computer_desc 'test'` for a new minion (win 2016/2019, potentially all other versions of windows), either from master or on minion.
Result:
```
Passed invalid arguments: unsupported operand type(s) for +=: 'int' and 'NoneType'.

Usage:

    Set the Windows computer description

    Args:

        desc (str):
            The computer description

    Returns:
        str: Description if successful, otherwise ``False``

    CLI Example:

    .. code-block:: bash

        salt 'minion-id' system.set_computer_desc 'This computer belongs to Dave!'

Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 237, in call
    ret['return'] = self.minion.executors[fname](self.opts, data, func, args, kwargs)
  File "C:\salt\bin\lib\site-packages\salt\executors\direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\modules\win_system.py", line 497, in set_computer_desc
    return {'Computer Description': get_computer_desc()}
  File "C:\salt\bin\lib\site-packages\salt\modules\win_system.py", line 649, in get_computer_desc
    desc = get_system_info()['description']
  File "C:\salt\bin\lib\site-packages\salt\modules\win_system.py", line 621, in get_system_info
    ret['processor_cores_enabled'] += system.NumberOfEnabledCore
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'
```

### Versions Report
Master:
```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.12.3
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: 1.3.8
         Jinja2: 2.7.2
        libgit2: 0.26.3
        libnacl: 1.6.1
       M2Crypto: 0.31.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: 3.7.3
         pygit2: 0.26.4
         Python: 2.7.5 (default, Apr  9 2019, 14:30:50)
   python-gnupg: 0.4.3
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 4.4.164-1.el7.elrepo.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core
```
Minion:
```

PS C:\salt> salt-call --versions-report
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.11.5
       cherrypy: 17.4.1
       dateutil: 2.7.5
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.10
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.4.3
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2016Server
         system: Windows
        version: 2016Server 10.0.14393  Multiprocessor Free
```

**Comment by skjaro** [comment]
I have similar problem with `system.get_system_info` module function. When I call it it returns this error:

```
    The minion function caused an exception: Traceback (most recent call last):
      File "C:\salt\bin\lib\site-packages\salt\minion.py", line 1660, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "C:\salt\bin\lib\site-packages\salt\executors\direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "C:\salt\bin\lib\site-packages\salt\modules\win_system.py", line 592, in get_system_info
        'chassis_sku_number': system.ChassisSKUNumber,
      File "C:\salt\bin\lib\site-packages\wmi.py", line 561, in __getattr__
        return getattr (self.ole_object, attribute)
      File "C:\salt\bin\lib\site-packages\win32com\client\dynamic.py", line 527, in __getattr__
        raise AttributeError("%s.%s" % (self._username_, attr))
    AttributeError: <unknown>.ChassisSKUNumber
```

It look like WMI subsystem returns fever data  in new version in salt

**Comment by cmcmarrow** [comment]
`salt-call --local system.set_computer_desc 'test'`
 works

**Comment by cmcmarrow** [comment]
`salt '*' system.set_computer_desc 'test'`
also works
I ran this on windows 2016 sever on 2019.2.0

**Comment by twangboy** [comment]
This is a problem with some grains that were added that are not supported on some versions of Windows. `NumberOfEnabledCore` and `ChassisSKUNumber`. The following PR addresses this issue:
https://github.com/saltstack/salt/pull/53287
