### ISSUE TITLE
Pillar failed to render: while parsing a block mapping

### ISSUE THREAD

**Issue by abezard** [saltstack/salt#53402]
Hi everyone!.

### Description of Issue
I keep hitting the following error while trying to execute a salt state against a specific saltenv/pillarenv:
```
local:
    Data failed to compile:
----------
    Pillar failed to render with the following messages:
----------
    Rendering SLS 'teststate' failed. Please see master log for details.
```

Here's what I have in the master logs:
```
[salt.pillar      :741 ][CRITICAL][34134] Rendering SLS 'teststate' failed, render error:
while parsing a block mapping
  in "<unicode string>", line 8, column 3
did not find expected key
  in "<unicode string>", line 17, column 3
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 736, in render_pstate
    **defaults)
  File "/usr/lib/python2.7/dist-packages/salt/template.py", line 93, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/var/cache/salt/master/extmods/renderers/yaml.py", line 217, in render
    raise SaltRenderError(exc)
SaltRenderError: while parsing a block mapping
  in "<unicode string>", line 8, column 3
did not find expected key
  in "<unicode string>", line 17, column 3
```

I have been trying so many things to fix this issue, I'm now running out of ideas. I used yaml linter / salt linter / search for non-ascii chars / completely emptied my salt pillars / salt states / clear the cache / spawn a brand new system / point to a different master (we have multiple masters)...etc. I keep getting the same result.

The weirdest thing is that I can do a `salt-call pillar.items pillarenv=my-testing-env` and it will load the pillar file just fine (and any change I make to my environment will be replicated in there).

Other states in that environment work as expected.

### Steps to Reproduce Issue
- Create a new salt state in a new environment
- run salt-call my_state against that environment

### Versions Report
Master:
```
salt --versions-report
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 2.0.4
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 12 2018, 14:36:49)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 2.0.4
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-1069-aws
         system: Linux
        version: Ubuntu 16.04 xenial
```

Thanks in advance for your help, I'm truly running out of ideas right now...

**Comment by abezard** [comment]
this was fixed by upgrading to 2019.2
