### ISSUE TITLE
gitfs(pygit2): gitea deploy keys fail

### ISSUE THREAD

**Issue by 5paceToast** [saltstack/salt#53414]
### Description of Issue
If salt's credentials have no global permissions on the server, but do have permissions to clone a specific directory, it will fail to authenticate.
An equivalent setup using GitPython has no such issues.

### Setup
`/etc/salt/master.d/fileserver.conf`:
```yaml
file_roots:
  base:
    - /srv/salt

gitfs_remotes:
  - git@server:namespace/repository.git

gitfs_privkey: /etc/salt/ssh
gitfs_pubkey: /etc/salt/ssh.pub
```
The above setup causes the following failure:
```
DATE [salt.utils.gitfs :1734][ERROR   ][PID] Error occurred fetching gitfs remote 'git@server:namespace/repository.git': Failed to authenticate SSH session: Callback returned error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 1712, in _fetch
    fetch_results = origin.fetch(**fetch_kwargs)
  File "/usr/lib/python2.7/dist-packages/pygit2/remote.py", line 405, in fetch
    check_error(err)
  File "/usr/lib/python2.7/dist-packages/pygit2/errors.py", line 64, in check_error
    raise GitError(message)
GitError: Failed to authenticate SSH session: Callback returned error
```
The following steps resolve the problem:
- uninstall pygit2 (making sure GitPython is installed)
- copy `/etc/salt/ssh` to `~/.ssh/id_rsa` and `/etc/salt/ssh.pub` to `~/.ssh/id_rsa.pub`
- comment `gitfs_privkey` and `gitfs_pubkey` keys in `fileserver.conf`

Note that the keys, repository, etc remain unchanged.
Similarly, loading the key into an ssh-agent and using the command line `git` clones successfully as well.

With that setup, gitfs is added (and is usable) successfully.

### Steps to Reproduce Issue
Gitea:
1. Install gitea
2. Create a private repository
3. Add salt's public key as a "Deploy Key" (giving it read-only access to that repository only)

Salt:
1. Set up salt as per above.
2. Launch `salt-master`.
3. Observe the error.
4. Perform the modifications mentioned above (minimal changes to switch to GitPython).
5. Launch `salt-master`
6. Observe the lack of an error

### Versions Report
```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.26.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.2
         Python: 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-50-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```

**Comment by lae** [comment]
This happens with GitHub read-only deploy keys as well. (the workaround using gitpython works)

**Comment by lae** [comment]
not stale

**Comment by Darkentik** [comment]
> This happens with GitHub read-only deploy keys as well. (the workaround using gitpython works)

Hey, we have same error 
"File "/usr/lib/python3/dist-packages/salt/utils/gitfs.py", line 1745, in _fetch | fetch_results = origin.fetch(**fetch_kwargs)".

Can you tell what workaround with gitpython should work?
We are using debian buster with saltstack 2019.2.3+ds-1 and python 3.7.3-1.

Thanks a lot!

**Comment by lae** [comment]
@Darkentik the workaround referenced there is the one documented in the first post.

**Comment by 5paceToast** [comment]
Still not stale.

**Comment by 5paceToast** [comment]
This issue is not stale. Why did the bot mark it as such again after another hour?

**Comment by windowsrefund** [comment]
Still seeing this on 3000-1. The GitPython work-around is less than ideal though since attributes like privkey and pubkey are not supported. This makes interacting with multiple repos a PITA since hackery would be needed to assign keys to fake URLs by way of ~/.ssh/config

Surprised this issue isn't getting any love

**Comment by windowsrefund** [comment]
After testing the posted work-around (along with micro-managing my ~/.ssh/config in order to work with multiple repos), I'm not sure this is going to work with git_pillar. In fact, I'm seeing no evidence that it will

Why isn't pygit2 using the correct privkey when auth is attempted?

**Comment by 5paceToast** [comment]
still not stale

**Comment by oogali** [comment]
Still not stale...

**Comment by oogali** [comment]
My issue turned out to be I was running Salt as non-root, but the `salt` user did not have access to the SSH private key (which owned by root, mode `0400`).

The error thrown by `pygit2` is a generic exception for all sorts of authentication problems.

**Comment by uwerler** [comment]
I have the same issue:

Salt Version:
          Salt: 3004
 
Dependency Versions:
          cffi: 1.15.0
      cherrypy: 8.9.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.5
     gitpython: 3.1.14
        Jinja2: 2.11.3
       libgit2: 1.3.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.0
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.7
        pygit2: 1.7.2
        Python: 3.9.2 (default, Feb 28 2021, 17:03:44)
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 20.0.0
         smmap: 4.0.0
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 11 bullseye
        locale: utf-8
       machine: x86_64
       release: 5.10.0-8-amd64
        system: Linux
       version: Debian GNU/Linux 11 bullseye

and

Gitea version 1.15.7 built with GNU Make 4.1, go1.16.10 : bindata, sqlite, sqlite_unlock_notify

under Debian 11.
