### ISSUE TITLE
can i upgrade tornado version to 5.x on python>=3.4 ?

### ISSUE THREAD

**Issue by GwiYeong** [saltstack/salt#53424]
### Description of Issue
now i use salt-api with salt-master. i just install dependency with `pip install -r requirements/base.txt` and it had installed `tornado==4.5.3` (this is latest version of 4.x in tornado and i use python 3.6)
but tornado 4.x has bug for handling they callback in this [line](https://github.com/tornadoweb/tornado/blob/branch4.5/tornado/concurrent.py#L323)
```python
def _set_done(self):
    self._done = True
    for cb in self._callbacks:  ## self._callbacks can be None
        try:
            cb(self)
        except Exception:
            app_log.exception('Exception in callback %r for %r',
                              cb, self)
```
so below exception will occured in salt-api
```
Uncaught exception POST /run (127.0.0.1)
HTTPServerRequest(protocol='http', host='10.162.3.204', method='POST', uri='/run', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Host': '10.162.3.204', 'Content-Type': 'application/json', 'Cache-Control': 'no-cache', 'Postman-Token': 'df32cdd8-119f-46a3-944a-7e17c45c4941', 'User-Agent': 'PostmanRuntime/7.1.1', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'X-Forwarded-For': '10.78.10.40', 'X-Forwarded-Host': '10.162.3.204', 'X-Forwarded-Server': 'salt-master.toastoven.net', 'Connection': 'Keep-Alive', 'Content-Length': '173'})
Traceback (most recent call last):
  File "/home1/irteamsu/.pyenv/versions/3.6.8/lib/python3.6/site-packages/tornado/web.py", line 1468, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File "<string>", line 4, in raise_exc_info
  File "/home1/irteamsu/.pyenv/versions/3.6.8/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
    ret = fn(*args, **kwargs)
  File "/home1/irteamsu/.pyenv/versions/3.6.8/lib/python3.6/site-packages/tornado/gen.py", line 951, in <lambda>
    IOLoop.current().call_later(duration, lambda: f.set_result(None))
  File "/home1/irteamsu/.pyenv/versions/3.6.8/lib/python3.6/site-packages/tornado/concurrent.py", line 279, in set_result
    self._set_done()
  File "/home1/irteamsu/.pyenv/versions/3.6.8/lib/python3.6/site-packages/tornado/concurrent.py", line 323, in _set_done
    for cb in self._callbacks:
TypeError: 'NoneType' object is not iterable
```

but this bug was fixed in `tornado>5`.(this [line](https://github.com/tornadoweb/tornado/blob/branch5.0/tornado/concurrent.py#L346))

so can i upgrade tornado version to 5.x?
and i just wondering why saltstack should use tornado<5 on python >= 3.4 as wiritten in [requirements/base.txt](https://github.com/saltstack/salt/blob/2019.2/requirements/base.txt) 

### Setup
pip install -r requirements/base.txt

### Steps to Reproduce Issue
i don't know.. but after several request to salt-api `http://localhost:32001/run [POST]`, above error occured.

### Versions Report
```
# python --version
Python 3.6.8

# salt --versions-report
Salt Version:
           Salt: 2019.2.0-9-g57e3663

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.11
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Jun  4 2019, 17:53:35)
   python-gnupg: Not Installed
         PyYAML: 5.1
          PyZMQ: 18.0.1
           RAET: Not Installed
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist: centos 6.8 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-642.15.1.el6.x86_64
         system: Linux
        version: CentOS 6.8 Final
```

**Comment by Akm0d** [comment]
Tornado 5 is not supported yet in salt with python>=3.4.   You can follow [this issue](https://github.com/saltstack/salt/issues/51883) for progress implementing it.

**Comment by GwiYeong** [comment]
@Akm0d  ok. thanks for giving information. i will follow it up
