### ISSUE TITLE
Windows: reg.present failing with "NotImplementedError: Ace type 9 is not supported yet"

### ISSUE THREAD

**Issue by ctr49** [saltstack/salt#53457]
### Description of Issue
When setting an (existing) registry value (possibly having permissions containing an unknown user), salt fails to apply.

### Setup
example sls:
```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PolicyManager\current\device\System\AllowExperimentation:
  reg.present:
    - name: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PolicyManager\current\device\System
    - vname: AllowExperimentation
    - vdata: 0
    - vtype: REG_DWORD
```
### Steps to Reproduce Issue
Apply above state
```
----------
          ID: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PolicyManager\current\device\System\AllowExperimentation
    Function: reg.present
        Name: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PolicyManager\current\device\System
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "c:\salt\bin\lib\site-packages\salt\state.py", line 1933, in call
                  **cdata['kwargs'])
                File "c:\salt\bin\lib\site-packages\salt\loader.py", line 1939, in wrapper
                  return f(*args, **kwargs)
                File "c:\salt\bin\lib\site-packages\salt\states\reg.py", line 414, in present
                  reset=win_perms_reset)
                File "c:\salt\bin\lib\site-packages\salt\utils\win_dacl.py", line 2343, in check_perms
                  cur_perms = get_permissions(obj_name=obj_name, obj_type=obj_type)
                File "c:\salt\bin\lib\site-packages\salt\utils\win_dacl.py", line 1680, in get_permissions
                  return obj_dacl.list_aces()
                File "c:\salt\bin\lib\site-packages\salt\utils\win_dacl.py", line 862, in list_aces
                  ace = self.dacl.GetAce(i)
              NotImplementedError: Ace type 9 is not supported yet
     Started: 00:33:36.070295
    Duration: 51.255 ms
     Changes:   
----------
```
### Versions Report
```
    Salt Version:
               Salt: 2019.2.0
     
    Dependency Versions:
               cffi: 1.11.5
           cherrypy: 17.4.1
           dateutil: 2.7.5
          docker-py: Not Installed
              gitdb: 2.0.5
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.10
            libgit2: Not Installed
            libnacl: 1.6.1
           M2Crypto: Not Installed
               Mako: 1.0.7
       msgpack-pure: Not Installed
     msgpack-python: 0.5.6
       mysql-python: Not Installed
          pycparser: 2.19
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]
       python-gnupg: 0.4.3
             PyYAML: 3.13
              PyZMQ: 17.1.2
               RAET: Not Installed
              smmap: 2.0.5
            timelib: 0.2.4
            Tornado: 4.5.3
                ZMQ: 4.2.5
     
    System Versions:
               dist:   
             locale: cp1252
            machine: AMD64
            release: 10
             system: Windows
            version: 10 10.0.17763 SP0 Multiprocessor Free
```

I assume the problem and hopefully the solution is similar to #45126 with symptoms (unknown account causing weird behavior) mentioned in #51868 too.
This is a brand new Win10 machine (so no accounts have been created or removed).

**Comment by Ch3LL** [comment]
ping @saltstack/team-windows any ideas here?

**Comment by cmcmarrow** [comment]
Do you believe the error message is not correct? If so can you please share why. I don't believe that this has to do anything whit unknown account.

**Comment by cmcmarrow** [comment]
Its a "AccessAllowedCallback". Just need to implement it does not look to hard. I will also check to see if types 10, 15... are supported as well.

**Comment by twangboy** [comment]
Looks like the 'AccessAllowedCalleback` Ace:

https://docs.microsoft.com/en-us/dotnet/api/system.security.accesscontrol.acetype?view=netframework-4.8

Is not currently supported by the PyWin32 `win32security.ACL` object

http://timgolden.me.uk/pywin32-docs/PyACL__GetAce_meth.html

**Comment by cmcmarrow** [comment]
I pushed a fix to 2018.3. We don't need to read or change any data from ace 9. So we can just ignore ace 9.

**Comment by cmcmarrow** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.security.accesscontrol.acetype?view=netframework-4.8

**Comment by mcuca1** [comment]
was this bug somehow reintroduced? I'm on 3001.1 and getting this error with a registry key that has an unknown user/group object within permissions
