### ISSUE TITLE
unit.modules.test_win_file.WinFileCheckPermsTestCase.test_issue_52002_check_file_remove_symlink failure

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#53458]
The tests `unit.modules.test_win_file.WinFileCheckPermsTestCase.test_issue_52002_check_file_remove_symlink` is failing on windows 2016:

https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-windows-2016-py2/101/testReport/junit/unit.modules.test_win_file/WinFileCheckPermsTestCase/test_issue_52002_check_file_remove_symlink/

```
Traceback (most recent call last):
  File "c:\users\admini~1\appdata\local\temp\kitchen\testing\tests\unit\modules\test_win_file.py", line 338, in test_issue_52002_check_file_remove_symlink
    self.assertTrue(win_file.makedirs_(target))
  File "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\kitchen\\testing\salt\modules\win_file.py", line 1470, in makedirs_
    reset=reset)
  File "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\kitchen\\testing\salt\modules\win_file.py", line 1336, in mkdir
    reset=reset)
  File "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\kitchen\\testing\salt\modules\win_file.py", line 1739, in set_perms
    return __utils__['dacl.set_perms'](obj_name=path,
KeyError: u'dacl.set_perms'
```

**Comment by waynew** [comment]
@twangboy Does that fix of yours also apply to this?

**Comment by twangboy** [comment]
oui

**Comment by twangboy** [comment]
Fixed by https://github.com/saltstack/salt/pull/53437
