### ISSUE TITLE
NameError: name '__salt_system_encoding__' is not defined while applying the states

### ISSUE THREAD

**Issue by kk21986** [saltstack/salt#53523]
### Description of Issue
When I run state.apply <state_name> or state.highstate on minion then getting the below error SOMETIMES. Interestingly the below error appeared after completing the state apply only. If I run the state for 10 times then I get this error on around 3-4 times.

```
Exception ignored in: <function RemoteClient.__del__ at 0x7fb27e9f30d0>
Traceback (most recent call last):
  File "/usr/local/python371/lib/python3.7/site-packages/salt/fileclient.py", line 1026, in __del__
  File "/usr/local/python371/lib/python3.7/site-packages/salt/fileclient.py", line 1033, in destroy
  File "/usr/local/python371/lib/python3.7/site-packages/salt/utils/asynchronous.py", line 62, in wrap
  File "/usr/local/python371/lib/python3.7/site-packages/salt/transport/zeromq.py", line 227, in close
  File "/usr/local/python371/lib/python3.7/logging/__init__.py", line 1371, in debug
  File "/usr/local/python371/lib/python3.7/site-packages/salt/log/setup.py", line 343, in _log
  File "/usr/local/python371/lib/python3.7/logging/__init__.py", line 1518, in _log
  File "/usr/local/python371/lib/python3.7/site-packages/salt/log/setup.py", line 363, in makeRecord
NameError: name '__salt_system_encoding__' is not defined
Exception ignored in: <function SyncWrapper.__del__ at 0x7fb27fa60048>
Traceback (most recent call last):
  File "/usr/local/python371/lib/python3.7/site-packages/salt/utils/asynchronous.py", line 85, in __del__
  File "/usr/local/python371/lib/python3.7/site-packages/salt/transport/zeromq.py", line 227, in close
  File "/usr/local/python371/lib/python3.7/logging/__init__.py", line 1371, in debug
  File "/usr/local/python371/lib/python3.7/site-packages/salt/log/setup.py", line 343, in _log
  File "/usr/local/python371/lib/python3.7/logging/__init__.py", line 1518, in _log
  File "/usr/local/python371/lib/python3.7/site-packages/salt/log/setup.py", line 363, in makeRecord
NameError: name '__salt_system_encoding__' is not defined
Exception ignored in: <function AsyncZeroMQReqChannel.__del__ at 0x7fb27e527598>
Traceback (most recent call last):
  File "/usr/local/python371/lib/python3.7/site-packages/salt/transport/zeromq.py", line 251, in __del__
  File "/usr/local/python371/lib/python3.7/site-packages/salt/transport/zeromq.py", line 227, in close
  File "/usr/local/python371/lib/python3.7/logging/__init__.py", line 1371, in debug
  File "/usr/local/python371/lib/python3.7/site-packages/salt/log/setup.py", line 343, in _log
  File "/usr/local/python371/lib/python3.7/logging/__init__.py", line 1518, in _log
  File "/usr/local/python371/lib/python3.7/site-packages/salt/log/setup.py", line 363, in makeRecord
NameError: name '__salt_system_encoding__' is not defined
```

### Setup
The state which I have tried to apply has dependent with JINJA template as while applying it will pull pillar, template and perform the changes. 

### Steps to Reproduce Issue
salt-call state.apply <state_name>

### Versions Report
Minion version report 
```
# salt-call --versions-report
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: 3.7.3
         pygit2: Not Installed
         Python: 3.7.1 (default, Nov 23 2018, 02:59:05)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: redhat 6.9 Santiago
         locale: utf-8
        machine: x86_64
        release: 4.1.12-123.16.7.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.9 Santiago
```

Master version report:

```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: 3.7.3
         pygit2: Not Installed
         Python: 3.7.1 (default, Nov 23 2018, 02:59:05)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: redhat 7.6 Maipo
         locale: UTF-8
        machine: x86_64
        release: 4.14.1456.1.3.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.6 Maipo
```

**Comment by xeacott** [comment]
Wondering how we can make this occur more often than just a few times to see exactly whats going on.

**Comment by kk21986** [comment]
You can try to run salt-call state.highstate on the minion multiple times without giving gap and you will notice this issue. If you give gap more than 5 mins then you will get this issue.

**Comment by lchausmann** [comment]
We're seeing the same issue - so far it's pretty hard to pinpoint what excactly is causing the error: 
`Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.2 (default, Nov 12 2018, 13:43:14)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-154-generic
         system: Linux
        version: Ubuntu 16.04 xenial`

**Comment by kk21986** [comment]
Interestingly I got the same issue while copying the file as well.

```
# /usr/local/python371/bin/salt-call cp.get_file salt://files/test.sh /tmp/test.sh
local:
    /tmp/test.sh
Exception ignored in: <function RemoteClient.__del__ at 0x7f2b2a7f5598>
Traceback (most recent call last):
  File "/usr/local/python371/lib/python3.7/site-packages/salt/fileclient.py", line 1026, in __del__
  File "/usr/local/python371/lib/python3.7/site-packages/salt/fileclient.py", line 1033, in destroy
  File "/usr/local/python371/lib/python3.7/site-packages/salt/utils/asynchronous.py", line 62, in wrap
  File "/usr/local/python371/lib/python3.7/site-packages/salt/transport/zeromq.py", line 227, in close
  File "/usr/local/python371/lib/python3.7/logging/__init__.py", line 1371, in debug
  File "/usr/local/python371/lib/python3.7/site-packages/salt/log/setup.py", line 343, in _log
  File "/usr/local/python371/lib/python3.7/logging/__init__.py", line 1518, in _log
  File "/usr/local/python371/lib/python3.7/site-packages/salt/log/setup.py", line 363, in makeRecord
NameError: name '__salt_system_encoding__' is not defined
Exception ignored in: <function SyncWrapper.__del__ at 0x7f2b2b8c2510>
Traceback (most recent call last):
  File "/usr/local/python371/lib/python3.7/site-packages/salt/utils/asynchronous.py", line 85, in __del__
  File "/usr/local/python371/lib/python3.7/site-packages/salt/transport/zeromq.py", line 227, in close
  File "/usr/local/python371/lib/python3.7/logging/__init__.py", line 1371, in debug
  File "/usr/local/python371/lib/python3.7/site-packages/salt/log/setup.py", line 343, in _log
  File "/usr/local/python371/lib/python3.7/logging/__init__.py", line 1518, in _log
  File "/usr/local/python371/lib/python3.7/site-packages/salt/log/setup.py", line 363, in makeRecord
NameError: name '__salt_system_encoding__' is not defined
Exception ignored in: <function AsyncZeroMQReqChannel.__del__ at 0x7f2b29fb1bf8>
Traceback (most recent call last):
  File "/usr/local/python371/lib/python3.7/site-packages/salt/transport/zeromq.py", line 251, in __del__
  File "/usr/local/python371/lib/python3.7/site-packages/salt/transport/zeromq.py", line 227, in close
  File "/usr/local/python371/lib/python3.7/logging/__init__.py", line 1371, in debug
  File "/usr/local/python371/lib/python3.7/site-packages/salt/log/setup.py", line 343, in _log
  File "/usr/local/python371/lib/python3.7/logging/__init__.py", line 1518, in _log
  File "/usr/local/python371/lib/python3.7/site-packages/salt/log/setup.py", line 363, in makeRecord
NameError: name '__salt_system_encoding__' is not defined
```

I suspect the encoding value variable `__salt_system_encoding__` is not set properly when the minion service gets started.

**Comment by Oloremo** [comment]
Probably a fix: https://github.com/saltstack/salt/pull/52012

**Comment by kk21986** [comment]
@Oloremo Unfortunately the fix provided on [#52012](https://github.com/saltstack/salt/pull/52012) is not worked. I tried to apply this patch on salt 2019.2.0 but still getting the same errors

**Comment by kk21986** [comment]
I still see the below exceptions printed on the console,

```
# salt-call state.apply configmanagement
local:
----------
          ID: copyautorestart
    Function: file.recurse
        Name: /tmp/test
      Result: True
     Comment: The directory /tmp/test is in the correct state
     Started: 07:53:53.720693
    Duration: 800.344 ms
     Changes:

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time: 800.344 ms
Exception ignored in: <function RemoteClient.__del__ at 0x7f1d2eb34ea0>
Traceback (most recent call last):
  File "/usr/local/python371/lib/python3.7/site-packages/salt/fileclient.py", line 1026, in __del__
  File "/usr/local/python371/lib/python3.7/site-packages/salt/fileclient.py", line 1033, in destroy
  File "/usr/local/python371/lib/python3.7/site-packages/salt/utils/asynchronous.py", line 62, in wrap
  File "/usr/local/python371/lib/python3.7/site-packages/salt/transport/zeromq.py", line 227, in close
  File "/usr/local/python371/lib/python3.7/logging/__init__.py", line 1371, in debug
  File "/usr/local/python371/lib/python3.7/site-packages/salt/log/setup.py", line 343, in _log
  File "/usr/local/python371/lib/python3.7/logging/__init__.py", line 1518, in _log
  File "/usr/local/python371/lib/python3.7/site-packages/salt/log/setup.py", line 363, in makeRecord
NameError: name '__salt_system_encoding__' is not defined
Exception ignored in: <function SyncWrapper.__del__ at 0x7f1d304ecf28>
Traceback (most recent call last):
  File "/usr/local/python371/lib/python3.7/site-packages/salt/utils/asynchronous.py", line 85, in __del__
  File "/usr/local/python371/lib/python3.7/site-packages/salt/transport/zeromq.py", line 227, in close
  File "/usr/local/python371/lib/python3.7/logging/__init__.py", line 1371, in debug
  File "/usr/local/python371/lib/python3.7/site-packages/salt/log/setup.py", line 343, in _log
  File "/usr/local/python371/lib/python3.7/logging/__init__.py", line 1518, in _log
  File "/usr/local/python371/lib/python3.7/site-packages/salt/log/setup.py", line 363, in makeRecord
NameError: name '__salt_system_encoding__' is not defined
Exception ignored in: <function AsyncZeroMQReqChannel.__del__ at 0x7f1d2e6756a8>
Traceback (most recent call last):
  File "/usr/local/python371/lib/python3.7/site-packages/salt/transport/zeromq.py", line 249, in __del__
  File "/usr/local/python371/lib/python3.7/site-packages/salt/transport/zeromq.py", line 227, in close
  File "/usr/local/python371/lib/python3.7/logging/__init__.py", line 1371, in debug
  File "/usr/local/python371/lib/python3.7/site-packages/salt/log/setup.py", line 343, in _log
  File "/usr/local/python371/lib/python3.7/logging/__init__.py", line 1518, in _log
  File "/usr/local/python371/lib/python3.7/site-packages/salt/log/setup.py", line 363, in makeRecord
NameError: name '__salt_system_encoding__' is not defined
```

**Comment by jpmckinney** [comment]
Same issue reported at #23520

FWIW I encountered this error when importing salt sub-packages within Python. I had to add this before the imports:

```
import builtins
setattr(builtins, "__salt_system_encoding__", "utf-8")
```

This implements the same logic as at:

https://github.com/saltstack/salt/blob/master/salt/__init__.py#L130

Just doing `import salt` (instead of the above) didn't work.
