### ISSUE TITLE
salt-ssh errors on parallel=True

### ISSUE THREAD

**Issue by EliAndrewC** [saltstack/salt#53538]
### Description of Issue
I've run into an issue where it looks like specifying ``parallel: True`` in a state raises an exception anytime we're using ``salt-ssh``.

### Setup
Here's the sls file I used:

```
test parallel file management:
  file.managed:
  - name: /tmp/paralleltest.txt
  - contents: "Hello World"
  - parallel: True
```

### Steps to Reproduce Issue

The above state works without the ``parallel: True`` but fails when that's included.  The specific error is:

```
$ salt-ssh gold state.apply test=True
[ERROR   ] JSON Render failed for: 
Process MultiprocessingProcess-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/var/tmp/.centos_b181cd_salt/pyall/salt/utils/process.py", line 765, in _run
    return self._original_run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/var/tmp/.centos_b181cd_salt/pyall/salt/state.py", line 1771, in _call_parallel_target
    troot = os.path.join(self.opts['cachedir'], self.jid)
  File "/usr/lib64/python2.7/posixpath.py", line 75, in join
    if b.startswith('/'):
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/var/tmp/.centos_b181cd_salt/salt-call", line 27, in <module>
    salt_call()
  File "/var/tmp/.centos_b181cd_salt/pyall/salt/scripts.py", line 431, in salt_call
    client.run()
  File "/var/tmp/.centos_b181cd_salt/pyall/salt/cli/call.py", line 57, in run
    caller.run()
  File "/var/tmp/.centos_b181cd_salt/pyall/salt/cli/caller.py", line 138, in run
    ret = self.call()
  File "/var/tmp/.centos_b181cd_salt/pyall/salt/cli/caller.py", line 237, in call
    ret['return'] = self.minion.executors[fname](self.opts, data, func, args, kwargs)
  File "/var/tmp/.centos_b181cd_salt/pyall/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/var/tmp/.centos_b181cd_salt/pyall/salt/modules/state.py", line 2192, in pkg
    ret = st_.call_chunks(lowstate)
  File "/var/tmp/.centos_b181cd_salt/pyall/salt/state.py", line 2157, in call_chunks
    if self.reconcile_procs(running):
  File "/var/tmp/.centos_b181cd_salt/pyall/salt/state.py", line 2233, in reconcile_procs
    salt.utils.hashutils.sha1_digest(tag))
  File "/usr/lib64/python2.7/posixpath.py", line 75, in join
    if b.startswith('/'):
AttributeError: 'NoneType' object has no attribute 'startswith'
[ERROR   ] No JSON object could be decoded
gold:
```

I did some digging and from looking at the ``salt/state.py`` file, it looks like the ``State`` class expects to have a ``jid`` of ``None`` for ``salt-ssh`` calls, but the ``State._call_parallel_target`` method tries to use ``self.jid`` to construct a filesystem path via ``os.path.join``.

### Versions Report

I'm on Salt 2019.2, but I also tested on the older version 2015.8 where it *did* work, albeit on a different system.

Here's the info from my master and minion:

```
$ salt-ssh --versions-report
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.31.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Oct 30 2018, 23:45:53)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 4.4.74-1.el7.centos.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core
 
$ salt-ssh gold test.versions_report
gold:
    Salt Version:
               Salt: 2019.2.0
     
    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: Not Installed
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.7.2
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.5.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: Not Installed
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.5 (default, Oct 30 2018, 23:45:53)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: Not Installed
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: Not Installed
     
    System Versions:
               dist: centos 7.6.1810 Core
             locale: UTF-8
            machine: x86_64
            release: 3.10.0-957.1.3.el7.x86_64
             system: Linux
            version: CentOS Linux 7.6.1810 Core

```

**Comment by dseomn** [comment]
I just came across the same issue, but with a slightly different stack trace.

```
[ERROR   ] JSON Render failed for: Execute a packaged state run, the packaged state run will exist in a
    tarball available locally. This packaged state
    can be generated using salt-ssh.

    CLI Example:

    .. code-block:: bash

        salt '*' state.pkg /tmp/salt_state.tgz 760a9353810e36f6d81416366fc426dc md5
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/var/tmp/.dseomn_a639a4_salt/pyall/salt/utils/process.py", line 895, in wrapped_run_func
    return run_func()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/var/tmp/.dseomn_a639a4_salt/pyall/salt/state.py", line 2006, in _call_parallel_target
    troot = os.path.join(self.opts["cachedir"], self.jid)
  File "/usr/lib/python3.9/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.9/genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'

Passed invalid arguments: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'.

Usage:
[ERROR   ] Expecting value: line 1 column 1 (char 0)
```

```
$ salt-ssh --versions-report
Salt Version:
          Salt: 3002.7
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.0.1
       libgit2: 1.1.0
      M2Crypto: Not Installed
          Mako: 1.1.3
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.9.7
        pygit2: 1.4.0
        Python: 3.9.7 (default, Sep 24 2021, 09:43:00)
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 22.3.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian testing bookworm
        locale: utf-8
       machine: x86_64
       release: 5.14.0-2-amd64
        system: Linux
       version: Debian GNU/Linux testing bookworm
```

**Comment by Rudd-O** [comment]
I have the exact same issue as above commenter.  It's broken again.

**Comment by vladaurosh** [comment]
Please reopen this issue.

**Comment by dseomn** [comment]
I asked on Discord about re-opening this, and was told to file a new issue: #66514

**Comment by lkubb** [comment]
This should be fixed (again?) by https://github.com/saltstack/salt/pull/66517, which also adds a test to ensure it stays that way.
