### ISSUE TITLE
mac python3 tests sometimes timeout

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#53535]
The mac python3 tests are sometimes timing out on this test `integration.shell.test_minion.MinionTest.test_issue_7754`

Here is the error:

```
06:21:49        [CPU:0.0%|MEM:70.1%]  ... OK (10.811s)
06:21:49          test_issue_7754 (integration.shell.test_minion.MinionTest)
13:17:52 FATAL: command execution failed
13:17:52 java.io.IOException
13:17:52 	at hudson.remoting.Channel.close(Channel.java:1447)
13:17:52 	at hudson.remoting.Channel.close(Channel.java:1403)
13:17:52 	at hudson.slaves.SlaveComputer.closeChannel(SlaveComputer.java:799)
13:17:52 	at hudson.slaves.SlaveComputer.kill(SlaveComputer.java:766)
13:17:52 	at hudson.model.AbstractCIBase.killComputer(AbstractCIBase.java:88)
13:17:52 	at jenkins.model.Jenkins.access$2100(Jenkins.java:304)
13:17:52 	at jenkins.model.Jenkins$20.run(Jenkins.java:3391)
13:17:52 	at hudson.model.Queue._withLock(Queue.java:1380)
13:17:52 	at hudson.model.Queue.withLock(Queue.java:1257)
13:17:52 	at jenkins.model.Jenkins._cleanUpDisconnectComputers(Jenkins.java:3385)
13:17:52 	at jenkins.model.Jenkins.cleanUp(Jenkins.java:3260)
13:17:52 	at hudson.WebAppMain.contextDestroyed(WebAppMain.java:379)
13:17:52 	at org.eclipse.jetty.server.handler.ContextHandler.callContextDestroyed(ContextHandler.java:898)
13:17:52 	at org.eclipse.jetty.servlet.ServletContextHandler.callContextDestroyed(ServletContextHandler.java:545)
13:17:52 	at org.eclipse.jetty.server.handler.ContextHandler.stopContext(ContextHandler.java:873)
13:17:52 	at org.eclipse.jetty.servlet.ServletContextHandler.stopContext(ServletContextHandler.java:355)
13:17:52 	at org.eclipse.jetty.webapp.WebAppContext.stopWebapp(WebAppContext.java:1521)
13:17:52 	at org.eclipse.jetty.webapp.WebAppContext.stopContext(WebAppContext.java:1485)
13:17:52 	at org.eclipse.jetty.server.handler.ContextHandler.doStop(ContextHandler.java:927)
13:17:52 	at org.eclipse.jetty.servlet.ServletContextHandler.doStop(ServletContextHandler.java:271)
13:17:52 	at org.eclipse.jetty.webapp.WebAppContext.doStop(WebAppContext.java:569)
13:17:52 	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
13:17:52 	at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:144)
13:17:52 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:162)
13:17:52 	at org.eclipse.jetty.server.handler.AbstractHandler.doStop(AbstractHandler.java:124)
13:17:52 	at org.eclipse.jetty.server.Server.doStop(Server.java:489)
13:17:52 	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
13:17:52 	at winstone.Launcher.shutdown(Launcher.java:307)
13:17:52 	at winstone.ShutdownHook.run(ShutdownHook.java:25)
13:17:52 Caused: hudson.remoting.ChannelClosedException: Channel "unknown": Remote call on mac-bld03 failed. The channel is closing down or has closed down
```

**Comment by Ch3LL** [comment]
realized it will will be fixed here: https://github.com/saltstack/salt/pull/53210
