### ISSUE TITLE
maintenance process restarted

### ISSUE THREAD

**Issue by tsaridas** [saltstack/salt#53548]
### Description of Issue
```
2019-06-18 08:30:32,832 [salt.utils.process:754 ][ERROR   ][116567] An un-handled exception from the multiprocessing process 'Maintenance-9' was caught:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/process.py", line 747, in _run
    return self._original_run()
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 223, in run
    salt.daemons.masterapi.clean_old_jobs(self.opts)
  File "/usr/lib/python2.7/site-packages/salt/daemons/masterapi.py", line 174, in clean_old_jobs
    mminion.returners[fstr]()
  File "/usr/lib/python2.7/site-packages/salt/returners/local_cache.py", line 441, in clean_old_jobs
    shutil.rmtree(t_path)
  File "/usr/lib64/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib64/python2.7/shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib64/python2.7/shutil.py", line 254, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/var/cache/salt/master/jobs/94/81c947980cd522d331b9bd44d1f2a165599d1363953bc6e80ad80f0d20bb4a'
2019-06-18 08:30:37,003 [salt.utils.process:435 ][INFO    ][122058] Process <class 'salt.master.Maintenance'> (116567) died with exit status 1, restarting...

```

### Versions Report
should affect all versions.

**Comment by Akm0d** [comment]
Thanks for the issue!  Can you give us the output of `salt-call --local test.versions` from the master and describe the module/state/command that was being invoked when this error was encountered?

**Comment by tsaridas** [comment]
I wrote that all versions should be affected. The maintenance process doesn't have anything to do with commands being invoked afaik.

**Comment by rmatte** [comment]
We're seeing this on 3002.6 (likely not fixed in 3003 as well).

This is a traceback often seen in the log on one of our syndicates.  This seems to possibly coincide with the job cache starting to "leak" or growing uncontrollably until we take manual action to correct it.

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/process.py", line 895, in wrapped_run_func
    return run_func()
  File "/usr/lib/python3/dist-packages/salt/master.py", line 249, in run
    salt.daemons.masterapi.clean_old_jobs(self.opts)
  File "/usr/lib/python3/dist-packages/salt/daemons/masterapi.py", line 165, in clean_old_jobs
    mminion.returners[fstr]()
  File "/usr/lib/python3/dist-packages/salt/returners/local_cache.py", line 445, in clean_old_jobs
    shutil.rmtree(f_path)
  File "/usr/lib/python3.8/shutil.py", line 722, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib/python3.8/shutil.py", line 720, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/var/cache/salt/master/jobs/6b/8bf745498c8a3ec534403e52c07d35059d4aeb3238386446f2ed746691e73b'
```

**Comment by tsaridas** [comment]
I patched the master myself to avoid this error, should be easy just by adding an ingore errors option in rmtree.

**Comment by dwoz** [comment]
Fixed in #61356 (merged Oct 2022) — `clean_old_jobs` now routes all `shutil.rmtree` calls through `_remove_job_dir`, which catches `OSError` (including errno 39 "Directory not empty") and logs instead of bubbling up to kill the Maintenance process. Present on 3006.x, 3007.x, 3008.x, master.
