### ISSUE TITLE
ssh.set_known_host breaks when updating key because of ssh-keygen output

### ISSUE THREAD

**Issue by HansAdema** [saltstack/salt#53551]
### Description of Issue

The `ssh.set_known_host` module function should be capable of updating the known hosts entry of a system if it has changed. However, this doesn't work on Debian Jessie. Instead, the following exception is returned:

```
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 410, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 212, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/ssh.py", line 1255, in set_known_host
    _get_matched_host_line_numbers(lines, enc)
  File "/usr/lib/python2.7/dist-packages/salt/modules/ssh.py", line 807, in _get_matched_host_line_numbers
    line_no = int(line.strip().split()[-1])
ValueError: invalid literal for int() with base 10: 'ECDSA'
```

This is caused by an incorrect assumption regarding the output of `ssh-keygen` (which is used to check the existing keys). The output of this function on Debian Jessie looks like:

```
~# ssh-keygen -F test.rebex.net
# Host test.rebex.net found: line 1 type ECDSA
|1|Yd+J7smphGDBh+1XGN/4cXnTNDY=|EFQ+scViqfmIWOmR7nhzA/h9U6g= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBIKmUgPsZGs4TZUO///u60XYezOy28hTQyHWaVAU0al0odcfuf84icYICEFQAUGw+jSwcF+Zjb18bSb4iLw06B4=
```

However, the breaking line assumes that the `type ECDSA` segment in this output is not present and (naively) assumes that the last word on the first line is always the line number.

### Setup
A clean installation of Salt on Debian Jessie. No further relevant config was identified.

### Steps to Reproduce Issue
1. Import an SSH host key of an example host, e.g. by running `ssh test.rebex.net`.
2. Update the `~/.ssh/known_hosts` file and replace the accepted host key for the domain and IP (the last word on the last two lines) by another value (e.g. `AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBIKmUgPsZGs4TZUO///u60XYezOy28hTQyHWaVAU0al0odcfuf84icYICEFQAUGw+jSwcF+Zjb18bSb4iLw06B4=`).
3. Run `salt-call ssh.set_known_host {USER} test.rebex.net`.

### Versions Report

```
Salt Version:
           Salt: 2018.3.4
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Sep 25 2018, 20:42:16)
   python-gnupg: 0.3.6
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.11 
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-52-generic
         system: Linux
        version: debian 8.11
```

**Comment by HansAdema** [comment]
This issue still happens.
