### ISSUE TITLE
ssh.set_known_host doesn't return updated fingerprint, and ssh_known_hosts.present assumes it does

### ISSUE THREAD

**Issue by HansAdema** [saltstack/salt#53552]
### Description of Issue

The `ssh_known_hosts.present` state function should be capable of updating the known hosts entry of a system if it has changed. On Debian Stretch, the update itself works, but the state file is unable to parse the output of the module function. When the SSH key has been updated, the state returns the following error:

```
          ID: test.rebex.net
    Function: ssh_known_hosts.present
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1933, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1939, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/ssh_known_hosts.py", line 187, in present
                  fingerprint = result['new'][0]['fingerprint']
              KeyError: u'fingerprint'
     Started: 15:53:15.580113
    Duration: 476.861 ms
     Changes:   
```

Subsequent runs of the same state do not return the same error (because the key was successfully updated).

This appears to be caused by state module assuming that the `fingerprint` key is always present, but this this not the case. Running the module directly returns output like this:

```
local:
    ----------
    new:
        |_
          ----------
          enc:
              ecdsa-sha2-nistp256
          hostname:
              test.rebex.net
          key:
              AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLZcZopPvkxYERubWeSrWOSHpxJdR14WFVES/Q3hFguTn6L+0EANqYcbRXhGBUV6SjR7SaxZACXSxOzgCtG4kwc=
    old:
        |_
          ----------
          enc:
              ecdsa-sha2-nistp256
          fingerprint:
              69:b1:72:32:f7:37:e5:ef:70:91:d3:fc:82:c5:de:88:99:8a:5d:5a:55:39:2d:7b:44:45:1f:59:bc:93:c4:a7
          hostname:
              |1|vg8WpzwRgalorXSq2IZCIh0ix30=|dqZc/C+djaYLbevzCF1LNniB2HU=
          key:
              AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBIKmUgPsZGs4TZUO///u60XYezOy28hTQyHWaVAU0al0odcfuf84icYICEFQAUGw+jSwcF+Zjb18bSb4iLw06B4=
    status:
        updated
```

As you can see: no fingerprint is present for the `new` entry.

### Setup

A minimal `ssh_key.sls`:

```
test.rebex.net:
  ssh_known_hosts.present:
    - user: root
    - enc: ecdsa-sha2-nistp256
```

This issue presented itself on Debian Stretch. Debian Jessie suffers from [another issue](https://github.com/saltstack/salt/issues/53551) preventing this stage from being reached. I don't know if other operating systems are affected.

### Steps to Reproduce Issue
1. Apply the state file above: `salt-call state.apply ssh_key`
2. Update the `~/.ssh/known_hosts` file and replace the accepted host key for the domain  (the last word on the last line) by another value (e.g. `AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBIKmUgPsZGs4TZUO///u60XYezOy28hTQyHWaVAU0al0odcfuf84icYICEFQAUGw+jSwcF+Zjb18bSb4iLw06B4=`).
3. Run the state file above again: `salt-call state.apply ssh_key`

### Versions Report
```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Sep 26 2018, 18:42:22)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.9 
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-52-generic
         system: Linux
        version: debian 9.9 
```

**Comment by HansAdema** [comment]
This issue still happens.
