### ISSUE TITLE
Issue with simple install and using the docker API

### ISSUE THREAD

**Issue by kmkramer** [saltstack/salt#53582]
I'm seeing this issue when trying to create docker volumes, image pull or other API calls. I've tried 2019.2.0 and 2018.3.3 as well as docker pip module 2.6.1 - 4.2.0

Adding a service.running  before the state shows that docker service is up and running.

Vagrantfile
```
Vagrant.configure("2") do |config|
    ## Choose your base box
    config.vm.box = "ubuntu/bionic64"

    ## For masterless, mount your salt file root
    config.vm.synced_folder "srv/salt", "/srv/salt/"
    config.vm.synced_folder "etc/salt/minion.d/", "/etc/salt/minion.d/"

    ## Use all the defaults:
    config.vm.provision :salt do |salt|
      salt.masterless = true
    end
  end
```
test.sls

```
requirements:
  pkg.installed:
    - pkgs:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - nfs-common

docker-repo:
  pkgrepo.managed:
    - name: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ salt['grains.get']('oscodename') }} stable
    - keyserver: https://download.docker.com/linux/ubuntu/gpg
    - keyid: 0EBFCD88
    - refresh: True

docker-host-pkgs:
  pkg.installed:
    - pkgs:
      - python-pip
      - docker-ce=18.06*
    - requires:
      - pkgrepo: docker-repo

docker-host-pip:
  pip.installed:
    - pkgs:
      - setuptools
      - docker==3.7.2
    - reload_modules: true

test-volume:
  docker_volume.present
```

failure snip..
```----------
          ID: test-volume
    Function: docker_volume.present
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1933, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1939, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/docker_volume.py", line 139, in present
                  volume = _find_volume(name)
                File "/usr/lib/python2.7/dist-packages/salt/states/docker_volume.py", line 60, in _find_volume
                  docker_volumes = __salt__['docker.volumes']()['Volumes']
                File "/usr/lib/python2.7/dist-packages/salt/modules/dockermod.py", line 5517, in volumes
                  response = _client_wrapper('volumes', filters=filters)
                File "/usr/lib/python2.7/dist-packages/salt/modules/dockermod.py", line 423, in wrapper
                  __context__['docker.client'] = _get_client(timeout=timeout, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/dockermod.py", line 387, in _get_client
                  ret = docker.APIClient(**client_kwargs)
                File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 190, in __init__
                  self._version = self._retrieve_server_version()
                File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 215, in _retrieve_server_version
                  'Error while fetching server API version: {0}'.format(e)
              DockerException: Error while fetching server API version: Timeout value connect was Timeout(connect=60, read=60, total=None), but it must be an int, float or None.
     Started: 14:51:49.741210
    Duration: 6.733 ms
     Changes:

Summary for local
------------
Succeeded: 4 (changed=4)
Failed:    1
```

**Comment by gecube** [comment]
Hello!

It is very interesting case as I think. Just right now I don't have capacity to test it. But I have 3 ideas

1. Did you try to check that docker daemon is *really* started ? Vagrant VMs sometimes are so slooooow.
2. Did you try to change timeout to higher values?
3. Is it correct to say that all states are applied in order as you defined them? Or is out-of-order execution possible? If yes, I believe you shall use watch_in/require_in keywords to make chain from states. Or it is enough to manually [set order numbe](https://docs.saltstack.com/en/latest/ref/states/ordering.html)r.
