### ISSUE TITLE
A number of integration.states.test_pkg.PkgTest tests fail with assertion error

### ISSUE THREAD

**Issue by DmitryKuzmenko** [saltstack/salt#53597]
Tests fail on debian8 py2 2019.2.1 branch build.

https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-debian-8-py2/140/testReport/junit/integration.states.test_pkg/PkgTest/test_pkg_001_installed/
https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-debian-8-py2/140/testReport/junit/integration.states.test_pkg/PkgTest/test_pkg_013_installed_with_wildcard_version/
https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-debian-8-py2/140/testReport/junit/integration.states.test_pkg/PkgTest/test_pkg_014_installed_with_comparison_operator/

```
Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/support/helpers.py", line 212, in wrap
    raise exc
AssertionError: u'1.11-3' is not false
```

Possibly the related to #53595 #53596

**Comment by garethgreenaway** [comment]
I ran these manually and they passed.  Looking back at the log from the last test run there was an issue with the version of python3.4 being installed which caused problems installing other packages that depended on that one.
```
02:05:56        Preparing to unpack .../python-plist_1.11-3_amd64.deb ...
02:05:56        Unpacking python-plist (1.11-3) ...
02:05:56        Setting up python3.4 (3.4.2-1+deb8u3) ...
02:05:56          File "/usr/lib/python3.4/http/client.py", line 1014
02:05:56            raise InvalidURL(f"URL can't contain control characters. {url!r} "
02:05:56                                                                      ^
02:05:56        SyntaxError: invalid syntax
02:05:56        dpkg: error processing package python3.4 (--configure):
02:05:56         subprocess installed post-installation script returned error exit status 1
02:05:56        dpkg: dependency problems prevent configuration of python3.4-dev:
02:05:56         python3.4-dev depends on python3.4 (= 3.4.2-1+deb8u3); however:
02:05:56          Package python3.4 is not configured yet.
02:05:56        
02:05:56        dpkg: error processing package python3.4-dev (--configure):
02:05:56         dependency problems - leaving unconfigured
02:05:56        Setting up python-plist (1.11-3) ...
02:05:56        Errors were encountered while processing:
02:05:56         python3.4
02:05:56         python3.4-dev
02:05:56        09:05:56,643 [salt.loaded.int.module.cmdmod                             :834 ][ERROR   ] stderr: Running as unit run-8945.scope.
02:05:56        E: Sub-process /usr/bin/dpkg returned an error code (1)
02:05:56        09:05:56,643 [salt.loaded.int.module.cmdmod                             :836 ][ERROR   ] retcode: 100
02:05:56        09:05:56,675 [salt.state                                                :322 ][ERROR   ] An error was encountered while installing package(s): Problem 
```

Started another test run for debian 8 to confirm.
