### ISSUE TITLE
file.shortcut injecting c:\windows\system32 into target and working dir fields

### ISSUE THREAD

**Issue by trudesea** [saltstack/salt#53706]
Hi,  I'm trying to create a shortcut on Windows and using the following state:

    application/shortcut:
      file.shortcut:
        - name: 'C:\Users\Public\Desktop\application.lnk'
        - target: iexplore.exe
        - arguments: http://{{ erpfqdn }}:22178
        - working_dir: '"C:\Program Files (x86)\Internet Explorer"'
        - icon_location: c:\graphics\logo.ico
        - force: True

When applying this state, the target and start in field have "C:\Windows\system32\" injected into the text, ie:

Target: C:\Windows\system32\iexplore.exe http://mywebsite:22178
Start in: "C:\Windows\system32\"C:\Program Files (x86)\Internet Explorer""

Don't think I have anything wrong there as it is pretty straightforward.
If this is a known issue, what could be a workaround?

### Versions Report
    Salt Version:
           Salt: 2019.2.0

    Dependency Versions:
           cffi: 1.11.5
       cherrypy: 17.4.1
       dateutil: 2.7.5
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.7
     msgpack-pure: Not Installed
     msgpack-python: 0.5.6
     mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
       pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:22:17) [MSC v.1500 32 bit (Intel)]
         python-gnupg: 0.4.3
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.2.5

    System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2016Server
         system: Windows
        version: 2016Server 10.0.14393  Multiprocessor Free

**Comment by trudesea** [comment]
An update: It seems to be injecting whatever directory you are running the salt-call from.

So for example if I run the salt-call state.apply from the C:\  dir, it will put that in front of the values in the target and Start in fields.  

Target:  C:\iexplore.exe http://mywebsite:22178
Start In: "C:\"C:\Program Files (x86)\Internet Explorer""

**Comment by sagetherage** [comment]
@twangboy @xeacott let's re-triage this issue please

**Comment by xeacott** [comment]
Hi @trudesea could you try this again on the latest release of salt? Unless I'm not fully understanding the issue... it does appear to be working. I created a file called testfile.txt in my path C:\dev\salt\testfile.txt and applied the following state:
```
application.shortcut:
  file.shortcut:
    - name: 'C:\Users\Public\Desktop\application.lnk'
    - target: testfile.txt
    - arguments: http://test:22178
    - working_dir: '"C:\Program Files (x86)\Internet Explorer"'
    - icon_location: c:\graphics\logo.ico
    - force: True
```

and it created a file in path C:\Users\Public\Desktop\application.lnk and when I open that file, it opens my testfile.txt and the properties of the testfile.txt include the arguments as such:
<img width="274" alt="Capture" src="https://user-images.githubusercontent.com/31625359/121617626-9d330f00-ca22-11eb-99b4-97ad5807c1ed.PNG">

**Comment by darkpixel** [comment]
I'm definitely seeing some weirdness in 3003.1 related to creating shortcuts on Windows Server 2019.

```
url_shortcut_test:
  file.shortcut:
    - name: 'C:\\Users\\Public\\Desktop\\test.url'
    - target: 'https://google.com/'
    - icon_location: '\\customer.local\netlogon\logo.ico'
```

```
          ID: url_shortcut_test
    Function: file.shortcut
        Name: C:\\Users\\Public\\Desktop\\test.url
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "c:\salt\bin\lib\site-packages\salt-3003.1-py3.7.egg\salt\state.py", line 2172, in call
                  *cdata["args"], **cdata["kwargs"]
                File "c:\salt\bin\lib\site-packages\salt-3003.1-py3.7.egg\salt\loader.py", line 1241, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "c:\salt\bin\lib\site-packages\salt-3003.1-py3.7.egg\salt\loader.py", line 2274, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "c:\salt\bin\lib\site-packages\salt-3003.1-py3.7.egg\salt\loader.py", line 2289, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "c:\salt\bin\lib\site-packages\salt-3003.1-py3.7.egg\salt\loader.py", line 2322, in wrapper
                  return f(*args, **kwargs)
                File "c:\salt\bin\lib\site-packages\salt-3003.1-py3.7.egg\salt\states\file.py", line 8341, in shortcut
                  state_checks.append(scut.IconLocation.lower() == icon_location.lower())
                File "c:\salt\bin\lib\site-packages\win32com\client\dynamic.py", line 511, in __getattr__
                  raise AttributeError("%s.%s" % (self._username_, attr))
              AttributeError: <unknown>.IconLocation
     Started: 22:41:14.430321
    Duration: 156.005 ms
     Changes:   
```

If I remove the ```icon_location``` line, it creates the shortcut.  I just have to manually go into the file properties and assign the icon myself.

**Comment by digitalsleuth** [comment]
@xeacott @sagetherage This issue is still occurring in Salt 3004.2 for Windows.
Error:
```
----------
          ID: winfor-standalones-cyberchef-shortcut
    Function: file.shortcut
        Name: C:\\Users\\forensics\\Desktop\\CyberChef.lnk
      Result: False
     Comment: Unable to create new shortcut C:\Users\forensics\Desktop\CyberChef.lnk -> C:\Windows\System32\"C:\Program Files\Mozilla Firefox\firefox.exe": (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147024809), None)
     Started: 13:37:31.437075
    Duration: 15.545 ms
     Changes:
 ```

Actual state:
```
{% set version='9.32.3' %}
{% set hash='465cf64bdd80cf99be72bedc9dccf7fcebaeace58d77ec62d71733c3e2ba404f' %}

include:
  - winfor.packages.firefox

winfor-standalones-cyberchef:
  archive.extracted:
    - name: "C:\\standalone\\cyberchef"
    - enforce_toplevel: False
    - source: https://github.com/gchq/CyberChef/releases/download/v{{ version}}/CyberChef_v{{ version }}.zip
    - source_hash: sha256={{ hash }}
    - overwrite: True
    - require:
      - sls: winfor.packages.firefox

winfor-standalones-cyberchef-shortcut:
  file.shortcut:
    - name: 'C:\\Users\\forensics\\Desktop\\CyberChef.lnk'
    - target: '"C:\\Program Files\\Mozilla Firefox\\firefox.exe"'
    - argument: 'C:\\standalone\\cyberchef\\CyberChef_v{{ version }}.html'
    - user: forensics
    - force: True
    - working_dir: 'C:\\standalone\\cyberchef'
    - makedirs: True
    - watch:
      - archive: winfor-standalones-cyberchef
    - require:
      - sls: winfor.packages.firefox
      - archive: winfor-standalones-cyberchef
```
Please note the `Comment:` line in the error, it has **C:\Windows\System32** prepended to the actual shortcut target. This happens to be the directory I ran the command in. When I change directory, it gives me the same error, but prepends THAT directory to the target.

```
----------
          ID: winfor-standalones-cyberchef-shortcut
    Function: file.shortcut
        Name: C:\\Users\\forensics\\Desktop\\CyberChef.lnk
      Result: False
     Comment: Unable to create new shortcut C:\Users\forensics\Desktop\CyberChef.lnk -> C:\run_state_from_here\"C:\Program Files\Mozilla Firefox\firefox.exe": (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147024809), None)
     Started: 13:43:47.722019
    Duration: 31.165 ms
     Changes:
```

@xeacott Your previous post you'll notice that your path of C:\dev\salt was NOT listed in your state, but it showed up in the shortcut properties, both in the Target and Start In. This is not desired behavior.

**Comment by digitalsleuth** [comment]
Additionally, tried the method from #61170 and this did not work either.

**Comment by digitalsleuth** [comment]
And still fails with 3003.3.

**Comment by digitalsleuth** [comment]
After a bit of playing around, I realize that this appears to have been a typo. I used `argument` instead of `arguments`. Perhaps this typo may require a bit of error handling to identify the source of this particular error. I would have expected an error indicating that was the wrong value.

@xeacott Not sure if you're still tracking this, but if you modify your state to look like this it should work (note the changes in type and quantity of quotes):
```
application.shortcut:
  file.shortcut:
    - name: 'C:\Users\Public\Desktop\application.lnk'
    - target: 'C:\Program Files (x86)\Internet Explorer\iexplore.exe'
    - arguments: "http://test:22178"
    - working_dir: 'C:\Program Files (x86)\Internet Explorer'
    - icon_location: 'C:\graphics\logo.ico'
    - force: True
```
Hope this helps someone.

**Comment by darkpixel** [comment]
It doesn't work on my end.

This works:
```
my_shortcut:
  file.shortcut:
    - name: 'C:\Users\Public\Desktop\my site.url'
    - target: 'https://google.com/'
```

This throws an error:
```
my_shortcut:
  file.shortcut:
    - name: 'C:\Users\Public\Desktop\my site.url'
    - target: 'https://google.com/'
    - icon_location: 'c:\temp\myicon.ico'
```

```
PS C:\Program Files\Salt Project\Salt> .\salt-call.bat -l info state.sls mysite
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** done ** 'mysite.sls'
[INFO    ] Running state [C:\Users\Public\Desktop\my site.url] at time 08:24:32.214440
[INFO    ] Executing state file.shortcut for [C:\Users\Public\Desktop\my site.url]
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "C:\Program Files\Salt Project\Salt\bin\lib\site-packages\salt-3004-py3.8.egg\salt\state.py", line 2179, in call
    ret = self.states[cdata["full"]](
  File "C:\Program Files\Salt Project\Salt\bin\lib\site-packages\salt-3004-py3.8.egg\salt\loader\lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "C:\Program Files\Salt Project\Salt\bin\lib\site-packages\salt-3004-py3.8.egg\salt\loader\lazy.py", line 1201, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "C:\Program Files\Salt Project\Salt\bin\lib\site-packages\salt-3004-py3.8.egg\salt\loader\lazy.py", line 1216, in _run_as
    return _func_or_method(*args, **kwargs)
  File "C:\Program Files\Salt Project\Salt\bin\lib\site-packages\salt-3004-py3.8.egg\salt\loader\lazy.py", line 1249, in wrapper
    return f(*args, **kwargs)
  File "C:\Program Files\Salt Project\Salt\bin\Lib\site-packages\salt-3004-py3.8.egg\salt\states\file.py", line 8289, in shortcut
    tresult, tcomment, tchanges = _shortcut_check(
  File "C:\Program Files\Salt Project\Salt\bin\Lib\site-packages\salt-3004-py3.8.egg\salt\states\file.py", line 1235, in _shortcut_check
    state_checks.append(scut.IconLocation.lower() == icon_location.lower())
  File "C:\Program Files\Salt Project\Salt\bin\lib\site-packages\win32com\client\dynamic.py", line 554, in __getattr__
    raise AttributeError("%s.%s" % (self._username_, attr))
AttributeError: <unknown>.IconLocation

[INFO    ] Completed state [C:\Users\Public\Desktop\my site.url] at time 08:24:32.355057 (duration_in_ms=140.617)
[INFO    ] Executing command attrib in directory 'C:\Users\adebruyn'
local:
----------
          ID: my_site
    Function: file.shortcut
        Name: C:\Users\Public\Desktop\my site.url
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "C:\Program Files\Salt Project\Salt\bin\lib\site-packages\salt-3004-py3.8.egg\salt\state.py", line 2179, in call
                  ret = self.states[cdata["full"]](
                File "C:\Program Files\Salt Project\Salt\bin\lib\site-packages\salt-3004-py3.8.egg\salt\loader\lazy.py", line 149, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "C:\Program Files\Salt Project\Salt\bin\lib\site-packages\salt-3004-py3.8.egg\salt\loader\lazy.py", line 1201, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "C:\Program Files\Salt Project\Salt\bin\lib\site-packages\salt-3004-py3.8.egg\salt\loader\lazy.py", line 1216, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "C:\Program Files\Salt Project\Salt\bin\lib\site-packages\salt-3004-py3.8.egg\salt\loader\lazy.py", line 1249, in wrapper
                  return f(*args, **kwargs)
                File "C:\Program Files\Salt Project\Salt\bin\Lib\site-packages\salt-3004-py3.8.egg\salt\states\file.py", line 8289, in shortcut
                  tresult, tcomment, tchanges = _shortcut_check(
                File "C:\Program Files\Salt Project\Salt\bin\Lib\site-packages\salt-3004-py3.8.egg\salt\states\file.py", line 1235, in _shortcut_check
                  state_checks.append(scut.IconLocation.lower() == icon_location.lower())
                File "C:\Program Files\Salt Project\Salt\bin\lib\site-packages\win32com\client\dynamic.py", line 554, in __getattr__
                  raise AttributeError("%s.%s" % (self._username_, attr))
              AttributeError: <unknown>.IconLocation
     Started: 08:24:32.214440
    Duration: 140.617 ms
     Changes:

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time: 140.617 ms
PS C:\Program Files\Salt Project\Salt>
```

Setting the icon location causes it to fail.
