### ISSUE TITLE
The combination of loop.until and http.wait_for_successful_query is broken

### ISSUE THREAD

**Issue by Oloremo** [saltstack/salt#53729]
### Description of Issue
Looks like a combination of `loop.until` and `http.wait_for_successful_query` is broken.

when you try to use them together you'll have this exception. 
```
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/opt/behavox/.local/lib/python3.6/site-packages/salt/state.py", line 1933, in call
                  **cdata['kwargs'])
                File "/opt/behavox/.local/lib/python3.6/site-packages/salt/loader.py", line 1939, in wrapper
                  return f(*args, **kwargs)
                File "/opt/behavox/.local/lib/python3.6/site-packages/salt/states/loop.py", line 106, in until
                  m_ret = __salt__[name](*m_args, **m_kwargs)
                File "/opt/behavox/.local/lib/python3.6/site-packages/salt/modules/http.py", line 67, in wait_for_successful_query
                  if time.time() > starttime + wait_for:
              TypeError: unsupported operand type(s) for +: 'float' and 'OrderedDict'
```

### Setup
I use this state with local Elasticsearch:

```
formula.elasticsearch.supervisord.service.wait:
  loop.until:
    - name: http.wait_for_successful_query
    - condition: 'm_ret["dict"]["_nodes"].get("successful", 0) == 1'
    - period: 1
    - timeout: 10
    - m_args:
        - http://127.0.0.1:9200/_nodes/_local/{{ grains.fqdn }}
        - wait_for: 10
    - m_kwargs:
        decode: True
```

### Steps to Reproduce Issue
Run a state like the above. Url probably won't matter.
It will work if you remove the `wait_for` argument.

Looks like `wait_for` has to be converted to int() in that case.

### Versions Report
```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.6 (default, Aug 13 2018, 18:24:23)
   python-gnupg: 0.4.4
         PyYAML: 5.1.1
          PyZMQ: 18.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.3.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```

**Comment by Oloremo** [comment]
Oh, looks like I need to move wait_for to m_kwargs. Not sure why tho'... But anyway. sorry for the noise.
