### ISSUE TITLE
Python 2 encoding problem

### ISSUE THREAD

**Issue by cmcmarrow** [saltstack/salt#53856]
### Description of Issue
Python 2 encoding problem

### Setup
Have German as only installed language.

### Steps to Reproduce Issue
`PS C:\salt> salt-minion -l debug` 
### Error
```[DEBUG ] Reading configuration from c:\salt\conf\minion 
[DEBUG ] Including configuration from 'c:\salt\conf\minion.d\_schedule.conf' 
[DEBUG ] Reading configuration from c:\salt\conf\minion.d\_schedule.conf 
[DEBUG ] Multiprocessing queue logging configured for the process running under PID: XXXX at log level 10 
[DEBUG ] Marking 'is_ip' as a jinja filter 
[DEBUG ] Marking 'is_ipv4' as a jinja filter 
[DEBUG ] Marking 'is_ipv6' as a jinja filter 
[DEBUG ] Marking 'ipv4' as a jinja filter 
[DEBUG ] Marking 'ipv6' as a jinja filter 
[DEBUG ] Marking 'ipaddr' as a jinja filter 
[DEBUG ] Marking 'ip_host' as a jinja filter 
[DEBUG ] Marking 'network_hosts' as a jinja filter 
[DEBUG ] Marking 'network_size' as a jinja filter 
[DEBUG ] Marking 'gen_mac' as a jinja filter 
[DEBUG ] Marking 'mac_str_to_bytes' as a jinja filter 
[DEBUG ] Marking 'dns_check' as a jinja filter 
[DEBUG ] Multiprocessing queue logging configured for the process running under PID: XXXX at log level 10 
[DEBUG ] Configuration file path: c:\salt\conf\minion 
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged. 
[INFO ] Setting up the Salt Minion "mgtsrv01.mainz2063" 
[DEBUG ] Marking 'base64_encode' as a jinja filter 
[DEBUG ] Marking 'base64_decode' as a jinja filter 
[DEBUG ] Marking 'md5' as a jinja filter 
[DEBUG ] Marking 'sha256' as a jinja filter 
[DEBUG ] Marking 'sha512' as a jinja filter 
[DEBUG ] Marking 'hmac' as a jinja filter 
[DEBUG ] Marking 'random_hash' as a jinja filter 
[DEBUG ] Marking 'rand_str' as a jinja filter 
[DEBUG ] Marking 'file_hashsum' as a jinja filter 
[DEBUG ] Marking 'http_query' as a jinja filter 
[DEBUG ] Marking 'strftime' as a jinja filter 
[DEBUG ] Marking 'date_format' as a jinja filter 
[DEBUG ] Marking 'yaml_dquote' as a jinja filter 
[DEBUG ] Marking 'yaml_squote' as a jinja filter 
[DEBUG ] Marking 'yaml_encode' as a jinja filter 
[DEBUG ] Marking 'raise' as a jinja global 
[DEBUG ] Marking 'match' as a jinja test 
[DEBUG ] Marking 'equalto' as a jinja test 
[DEBUG ] Marking 'skip' as a jinja filter 
[DEBUG ] Marking 'sequence' as a jinja filter 
[DEBUG ] Marking 'to_bool' as a jinja filter 
[DEBUG ] Marking 'tojson' as a jinja filter 
[DEBUG ] Marking 'quote' as a jinja filter 
[DEBUG ] Marking 'regex_escape' as a jinja filter 
[DEBUG ] Marking 'regex_search' as a jinja filter 
[DEBUG ] Marking 'regex_match' as a jinja filter 
[DEBUG ] Marking 'regex_replace' as a jinja filter 
[DEBUG ] Marking 'uuid' as a jinja filter 
[DEBUG ] Marking 'unique' as a jinja filter 
[DEBUG ] Marking 'min' as a jinja filter 
[DEBUG ] Marking 'max' as a jinja filter 
[DEBUG ] Marking 'avg' as a jinja filter 
[DEBUG ] Marking 'union' as a jinja filter 
[DEBUG ] Marking 'intersect' as a jinja filter 
[DEBUG ] Marking 'difference' as a jinja filter 
[DEBUG ] Marking 'symmetric_difference' as a jinja filter 
[DEBUG ] Created pidfile: c:\salt\var\run\salt-minion.pid 
[INFO ] Starting up the Salt Minion 
[DEBUG ] AsyncEventPublisher PUB socket URI: XXXX
[DEBUG ] AsyncEventPublisher PULL socket URI: XXXX 
[INFO ] Starting pull socket on XXXX
[DEBUG ] SaltEvent PUB socket URI: XXXX
[DEBUG ] SaltEvent PULL socket URI: XXXX 
[DEBUG ] Initializing new IPCClient for path: XXXX 
[DEBUG ] Grains refresh requested. Refreshing grains. 
[DEBUG ] Reading configuration from c:\salt\conf\minion 
[DEBUG ] Including configuration from 'c:\salt\conf\minion.d\_schedule.conf' 
[DEBUG ] Reading configuration from c:\salt\conf\minion.d\_schedule.conf 
Traceback (most recent call last): 
[ File "C:\salt\bin\Scripts\salt-minion", line 26, in <module> 
ERROR ] An un-handled exception was caught by salt's global exception handler: 
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 11: ordinal not in range(128) 
Traceback (most recent call last): 
File "C:\salt\bin\Scripts\salt-minion", line 26, in <module> 
salt_minion() 
File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 191, in salt_minion 
minion.start() 
File "C:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 348, in start 
self.minion.tune_in() 
File "C:\salt\bin\lib\site-packages\salt\minion.py", line 1056, in tune_in 
self._spawn_minions() 
File "C:\salt\bin\lib\site-packages\salt\minion.py", line 1000, in _spawn_minions 
jid_queue=self.jid_queue) 
File "C:\salt\bin\lib\site-packages\salt\minion.py", line 972, in _create_minion_object 
jid_queue=jid_queue) 
File "C:\salt\bin\lib\site-packages\salt\minion.py", line 1126, in __init__ 
self.opts['grains'] = salt.loader.grains(opts) 
File "C:\salt\bin\lib\site-packages\salt\loader.py", line 772, in grains 
ret = funcs[key]() 
File "C:\salt\bin\lib\site-packages\salt\grains\core.py", line 2091, in locale_info 
grains['locale_info']['timezone'] = datetime.datetime.now(dateutil.tz.tzlocal()).tzname() 
File "C:\salt\bin\lib\site-packages\dateutil\tz\_common.py", line 22, in adjust_encoding 
name = name.encode() 
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 11: ordinal not in range(128) 
salt_minion() 
File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 191, in salt_minion 
minion.start() 
File "C:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 348, in start 
self.minion.tune_in() 
File "C:\salt\bin\lib\site-packages\salt\minion.py", line 1056, in tune_in 
self._spawn_minions() 
File "C:\salt\bin\lib\site-packages\salt\minion.py", line 1000, in _spawn_minions 
jid_queue=self.jid_queue) 
File "C:\salt\bin\lib\site-packages\salt\minion.py", line 972, in _create_minion_object 
jid_queue=jid_queue) 
File "C:\salt\bin\lib\site-packages\salt\minion.py", line 1126, in __init__ 
self.opts['grains'] = salt.loader.grains(opts) 
File "C:\salt\bin\lib\site-packages\salt\loader.py", line 772, in grains 
ret = funcs[key]() 
File "C:\salt\bin\lib\site-packages\salt\grains\core.py", line 2091, in locale_info 
grains['locale_info']['timezone'] = datetime.datetime.now(dateutil.tz.tzlocal()).tzname() 
File "C:\salt\bin\lib\site-packages\dateutil\tz\_common.py", line 22, in adjust_encoding 
name = name.encode() 
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 11: ordinal not in range(128)
```

### Versions Report
Salt-Minion-2019.2.0-Py2-AMD64-Setup.exe
Target system: Windows Server 2012 RR

**Comment by doesitblend** [comment]
ZD-3834

**Comment by cmcmarrow** [comment]
I have been able to replicate the error. For this error to happen the set time zone most have a non ASCII char and salt most be running with python 2. Will see if I get the same error for 2019.2.1. A fast fix for this is to simply change the time zone of the computer.

**Comment by cmcmarrow** [comment]
I can confirm this to be a bug in 2019.2.1

**Comment by cmcmarrow** [comment]
I can confirm that this bug is not in 2018.3
