### ISSUE TITLE
Convert the CLI: "salt-run salt.cmd file.readdir /srv/pillar" to Jinja

### ISSUE THREAD

**Issue by HenrikHL** [saltstack/salt#53883]
I have problems converting the following CLI:
`salt-run salt.cmd file.readdir /srv/pillar`
which produces the following output:
```
- .
- ..
- default.sls
- instances
- top.sls
```
to Jinja. I have tried a lot of combinations like:
```
{% set files = salt['saltutil.runner'](name='salt.cmd', arg=['file.readdir','/srv/pillar']) %}
files:
{% for file in files %}
  {{ file }}
{% endfor %}
```
I have also tried: changing the arguments to:
`{% set files = salt['saltutil.runner'](name='salt.cmd', arg=['file.readdir /srv/pillar']) %}`
But I keep on getting errors like:
```
2019-07-17 07:31:19,779 [salt.pillar      :741 ][CRITICAL][7382] Rendering SLS 'instances' failed, render error:
while parsing a block mapping
  in "<unicode string>", line 32, column 1
did not find expected key
  in "<unicode string>", line 212, column 3
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 736, in render_pstate
    **defaults)
  File "/usr/lib/python2.7/dist-packages/salt/template.py", line 101, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/renderers/yaml.py", line 59, in render
    raise SaltRenderError(exc)
SaltRenderError: while parsing a block mapping
  in "<unicode string>", line 32, column 1
did not find expected key
  in "<unicode string>", line 212, column 3
2019-07-17 07:31:19,780 [salt.pillar      :1036][CRITICAL][7382] Pillar render error: Rendering SLS 'instances' failed. Please see master log for details.
```
I need to be able to read the pillar folder - I cannot see any other way to do this...

### Versions Report
```
root@saltmaster:/var/log/salt# salt --versions-report
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15+ (default, Nov 27 2018, 23:36:35)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-51-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```

**Comment by HenrikHL** [comment]
I found the answer:
`{% set test = salt.saltutil.runner('salt.cmd', fun='file.readdir', path='/srv/pillar') %}`
I really think the error messages could be vastly improved in salt! The above error message says:

> did not find the expected key

I had no clue as this was referring to the argument name "path". Why does it not write:

>did not find expected parameter 'path'

This would have saved me a lot of time...
