### ISSUE TITLE
pkg.latest traces back when package does not exist (FreeBSD)

### ISSUE THREAD

**Issue by amontalban** [saltstack/salt#53886]
### Description of Issue
When you use `pkg.latest` in FreeBSD and the package does not exist (In our case package name changed in the repository) it just traces back.

### Setup
```
perceptyx-app-prince:
  pkg.latest:
    - require:
      - pkg: java
```

**Output:**

```  
[INFO    ] Running state [perceptyx-app-prince] at time 05:52:26.569484
[INFO    ] Executing state pkg.latest for [perceptyx-app-prince]
[INFO    ] Executing command [u'pkg', u'--version'] in directory '/home/ec2-user'
[INFO    ] Executing command [u'pkg', u'search', u'-S', u'name', u'-Q', u'version', u'-e', u'-q', u'perceptyx-app-prince'] in directory '/home/ec2-user'
[ERROR   ] Command '[u'pkg', u'search', u'-S', u'name', u'-Q', u'version', u'-e', u'-q', u'perceptyx-app-prince']' failed with return code: 70
[ERROR   ] retcode: 70
[ERROR   ] Command '[u'pkg', u'search', u'-S', u'name', u'-Q', u'version', u'-e', u'-q', u'perceptyx-app-prince']' failed with return code: 70
[ERROR   ] output: 
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
 File "/usr/local/lib/python2.7/site-packages/salt/state.py", line 1933, in call
   **cdata['kwargs'])
 File "/usr/local/lib/python2.7/site-packages/salt/loader.py", line 1939, in wrapper
   return f(*args, **kwargs)
 File "/usr/local/lib/python2.7/site-packages/salt/states/pkg.py", line 2413, in latest
   **kwargs)
 File "/usr/local/lib/python2.7/site-packages/salt/modules/pkgng.py", line 328, in latest_version
   ).pop(0)
IndexError: pop from empty list

[INFO    ] Completed state [perceptyx-app-prince] at time 05:52:28.584410 (duration_in_ms=2014.925)
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.12.2
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.32.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.16 (default, May 16 2019, 01:14:27)
   python-gnupg: Not Installed
         PyYAML: 5.1
          PyZMQ: 18.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist:   
         locale: UTF-8
        machine: amd64
        release: 11.2-RELEASE-p9
         system: FreeBSD
        version: Not Installed
```

**Comment by fzipi** [comment]
Any news on this one? Is it just confirmed?

**Comment by noelmcloughlin** [comment]
Same with pkg.install on freebsd
```
          ID: docker-package
    Function: pkg.installed
        Name: docker-ce
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/local/lib/python2.7/site-packages/salt/state.py", line 1933, in call
                  **cdata['kwargs'])
                File "/usr/local/lib/python2.7/site-packages/salt/loader.py", line 1951, in wrapper
                  return f(*args, **kwargs)
                File "/usr/local/lib/python2.7/site-packages/salt/states/pkg.py", line 1563, in installed
                  **kwargs)
                File "/usr/local/lib/python2.7/site-packages/salt/states/pkg.py", line 692, in _find_install_targets
                  **kwargs)
                File "/usr/local/lib/python2.7/site-packages/salt/modules/pkgng.py", line 328, in latest_version
                  ).pop(0)
              IndexError: pop from empty list
```

**Comment by krionbsd** [comment]
It's fixed in the latest salt version, try it instead of 2019.x.x
