### ISSUE TITLE
win_dns_client.dns_exists fails

### ISSUE THREAD

**Issue by Mapel88** [saltstack/salt#53938]
### Description of Issue
running state win_dns_client.dns_exists fails.

### Setup
```
{% set dnsList  = salt['pillar.get']('resolver:nameservers') %}

config_dns_servers:
  win_dns_client.dns_exists:
    - replace: True #remove any servers not in the "servers" list, default is False
    - servers:
      {% for dns_server in dnsList %}
      - {{ dns_server }}
      {% endfor %}
```

### Steps to Reproduce Issue
```
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Including configuration from 'c:\salt\conf\minion.d\_schedule.conf'
[DEBUG   ] Reading configuration from c:\salt\conf\minion.d\_schedule.conf
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Including configuration from 'c:\salt\conf\minion.d\_schedule.conf'
[DEBUG   ] Reading configuration from c:\salt\conf\minion.d\_schedule.conf
[DEBUG   ] Motherboard info not available on this system
[DEBUG   ] Loading static grains from c:\salt\conf\grains
[DEBUG   ] Connecting to master. Attempt 1 (infinite attempts)
[DEBUG   ] Master URI: tcp://1.1.1.1:4506
[DEBUG   ] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'nl1-stg03', 'tcp://1.1.1.1:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (8493)
[DEBUG   ] Setting zmq_reconnect_ivl to '8493ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'nl1-stg03', 'tcp://1.1.1.1:4506', 'clear')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://1.1.1.1:4506
[DEBUG   ] Trying to connect to: tcp://1.1.1.1:4506
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] salt.crypt._get_key_with_evict: Loading private key
[DEBUG   ] Loaded minion key: c:\minion.pem
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
[DEBUG   ] Connecting the Minion to the Master publish port, using the URI: tcp://1.1.1.1:4505
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] Loaded minion key: c:\minion.pem
[DEBUG   ] Determining pillar cache
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'nl1-stg03', 'tcp://1.1.1.1:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'nl1-stg03', 'tcp://1.1.1.1:4506')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://1.1.1.1:4506
[DEBUG   ] Trying to connect to: tcp://1.1.1.1:4506
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] Loaded minion key: c:\minion.pem
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded state.apply
[DEBUG   ] LazyLoaded saltutil.is_running
[DEBUG   ] LazyLoaded grains.get
[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'nl1-stg03', 'tcp://1.1.1.1:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'nl1-stg03', 'tcp://1.1.1.1:4506')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://1.1.1.1:4506
[DEBUG   ] Trying to connect to: tcp://1.1.1.1:4506
[DEBUG   ] Gathering pillar data for state run
[DEBUG   ] Finished gathering pillar data for state run
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] Could not find file 'salt://windows/dns.sls' in saltenv 'base'
[DEBUG   ] In saltenv 'base', looking at rel_path 'windows/dns/init.sls' to resolve 'salt://windows/dns/init.sls'
[DEBUG   ] In saltenv 'base', ** considering ** path 'c:\salt\var\cache\salt\minion\files\base\windows\dns\init.sls' to resolve 'salt://windows/dns/init.sls'
[DEBUG   ] compile template: c:\salt\var\cache\salt\minion\files\base\windows\dns\init.sls
[DEBUG   ] Jinja search path: ['c:\\salt\\var\\cache\\salt\\minion\\files\\base']
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'nl1-stg03', 'tcp://1.1.1.1:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'nl1-stg03', 'tcp://1.1.1.1:4506')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://1.1.1.1:4506
[DEBUG   ] Trying to connect to: tcp://1.1.1.1:4506
[DEBUG   ] LazyLoaded pillar.get
[PROFILE ] Time (in seconds) to render 'c:\salt\var\cache\salt\minion\files\base\windows\dns\init.sls' using 'jinja' renderer: 0.04700803756713867
[DEBUG   ] Rendered data from file: c:\salt\var\cache\salt\minion\files\base\windows\dns\init.sls:


config_dns_servers:
  win_dns_client.dns_exists:
    - replace: True #remove any servers not in the "servers" list, default is False
    - servers:

      - 1.1.1.2

      - 1.1.1.3

      - 1.1.1.4

      - 1.1.1.5

      - 1.1.1.6

[DEBUG   ] Results of YAML rendering:
OrderedDict([('config_dns_servers', OrderedDict([('win_dns_client.dns_exists', [OrderedDict([('replace', True)]), OrderedDict([('servers', ['1.1.1.2', '1.1.1.3', '1.1.1.4', '1.1.1.5', '1.1.1.6'])])])]))])
[PROFILE ] Time (in seconds) to render 'c:\salt\var\cache\salt\minion\files\base\windows\dns\init.sls' using 'yaml' renderer: 0.008006811141967773
[DEBUG   ] LazyLoaded config.option
[DEBUG   ] LazyLoaded win_dns_client.add_dns
[DEBUG   ] LazyLoaded win_dns_client.dns_exists
[INFO    ] Running state [config_dns_servers] at time 10:19:31.079390
[INFO    ] Executing state win_dns_client.dns_exists for [config_dns_servers]
[DEBUG   ] Interface "Local Area Connection" not found
[DEBUG   ] Interface "Local Area Connection" not found
[ERROR   ] Failed to add 1.1.1.2 as DNS server number 1
[INFO    ] Completed state [config_dns_servers] at time 10:19:31.246410 (duration_in_ms=167.02)
[DEBUG   ] LazyLoaded event.fire_master
[DEBUG   ] Initializing new SAuth for ('c:\\salt\\conf\\pki\\minion', 'nl1-stg03', 'tcp://1.1.1.1:4506')
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] Loaded minion key: c:\minion.pem
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'nl1-stg03', 'tcp://1.1.1.1:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'nl1-stg03', 'tcp://1.1.1.1:4506')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://1.1.1.1:4506
[DEBUG   ] Trying to connect to: tcp://1.1.1.1:4506
[DEBUG   ] File c:\salt\var\cache\salt\minion\accumulator\2117470431832 does not exist, no need to cleanup
[DEBUG   ] LazyLoaded cmd.run
[INFO    ] Executing command ['attrib', '-R', 'c:\\salt\\var\\cache\\salt\\minion\\sls.p'] in directory 'C:\Users\maayana'
[DEBUG   ] output:
[DEBUG   ] LazyLoaded state.check_result
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'nl1-stg03', 'tcp://1.1.1.1:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'nl1-stg03', 'tcp://1.1.1.1:4506')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://1.1.1.1:4506
[DEBUG   ] Trying to connect to: tcp://1.1.1.1:4506
[DEBUG   ] LazyLoaded highstate.output
local:
----------
          ID: config_dns_servers
    Function: win_dns_client.dns_exists
      Result: False
     Comment: Failed to add 1.1.1.2 as DNS server number 1
     Started: 10:19:31.079390
    Duration: 167.02 ms
     Changes:

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time: 167.020 ms
```

### Versions Report
Salt Version:
           Salt: 2018.3.4

Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.24.6
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: 3.6.1
         pygit2: 0.24.2
         Python: 2.7.5 (default, Oct 30 2018, 23:45:53)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.14.4.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core

**Comment by dwoz** [comment]
@Mapel88 Does this work if you remove the extra spaces from your rendered state by using the `{%-` jinja syntax as show below? 

```
{% set dnsList  = salt['pillar.get']('resolver:nameservers') %}

config_dns_servers:
  win_dns_client.dns_exists:
    - replace: True #remove any servers not in the "servers" list, default is False
    - servers:
      {%- for dns_server in dnsList %}
      - {{ dns_server }}
      {%- endfor %}
```

**Comment by Mapel88** [comment]
@dwoz nope. Same error.

**Comment by AgentGen** [comment]
The actual issue is hiding here in salt\bin\lib\site-packages\salt\states\win_dns_client.py line 48:


> [DEBUG   ] Results of YAML rendering:
OrderedDict([('config_dns_servers', OrderedDict([('win_dns_client.dns_exists', [OrderedDict([('replace', True)]), Ordere
dDict([('servers', ['172.16.32.101', '172.16.32.102', '172.16.32.1', '172.16.32.2', '172.16.32.3'])])])]))])
[PROFILE ] Time (in seconds) to render 'c:\salt\var\cache\salt\minion\files\base\windows\dns\init.sls' using 'yaml' rend
erer: 0.0
[DEBUG   ] LazyLoaded config.option
[DEBUG   ] LazyLoaded win_dns_client.add_dns
[DEBUG   ] LazyLoaded win_dns_client.dns_exists
[INFO    ] Running state [config_dns_servers] at time 11:50:16.732869
[INFO    ] Executing state win_dns_client.dns_exists for [config_dns_servers]
[DEBUG   ] Interface "Local Area Connection" not found
[DEBUG   ] An exception occurred in this state: argument of type 'bool' is not iterable
Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\state.py", line 1919, in call
    **cdata['kwargs'])
  File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1918, in wrapper
    return f(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\states\win_dns_client.py", line 58, in dns_exists
    if server in configured_list:
TypeError: argument of type 'bool' is not iterable
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\state.py", line 1919, in call
    **cdata['kwargs'])
  File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1918, in wrapper
    return f(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\states\win_dns_client.py", line 58, in dns_exists
    if server in configured_list:
TypeError: argument of type 'bool' is not iterable

configured_list is a bool that cannot be iterated over, so far traced it back to get_dns_servers function in salt\bin\Lib\site-packages\salt\modules\win_dns_client.py.

For now I bypassed it by declaring configured_list = [''] on line 49.

**Comment by AgentGen** [comment]
The actual issue is hiding here in salt\bin\lib\site-packages\salt\states\win_dns_client.py line 48:

> [DEBUG ] Results of YAML rendering:
OrderedDict([('config_dns_servers', OrderedDict([('win_dns_client.dns_exists', [OrderedDict([('replace', True)]), Ordere
dDict([('servers', ['IP1', 'IP2', 'IP3', 'IP4', 'IP5'])])])]))])
[PROFILE ] Time (in seconds) to render 'c:\salt\var\cache\salt\minion\files\base\windows\dns\init.sls' using 'yaml' rend
erer: 0.0
[DEBUG ] LazyLoaded config.option
[DEBUG ] LazyLoaded win_dns_client.add_dns
[DEBUG ] LazyLoaded win_dns_client.dns_exists
[INFO ] Running state [config_dns_servers] at time 11:50:16.732869
[INFO ] Executing state win_dns_client.dns_exists for [config_dns_servers]
[DEBUG ] Interface "Local Area Connection" not found
[DEBUG ] An exception occurred in this state: argument of type 'bool' is not iterable
Traceback (most recent call last):
File "C:\salt\bin\lib\site-packages\salt\state.py", line 1919, in call
**cdata['kwargs'])
File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1918, in wrapper
return f(*args, **kwargs)
File "C:\salt\bin\lib\site-packages\salt\states\win_dns_client.py", line 58, in dns_exists
if server in configured_list:
TypeError: argument of type 'bool' is not iterable
[ERROR ] An exception occurred in this state: Traceback (most recent call last):
File "C:\salt\bin\lib\site-packages\salt\state.py", line 1919, in call
**cdata['kwargs'])
File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1918, in wrapper
return f(*args, **kwargs)
File "C:\salt\bin\lib\site-packages\salt\states\win_dns_client.py", line 58, in dns_exists
if server in configured_list:
TypeError: argument of type 'bool' is not iterable


configured_list is a bool that cannot be iterated over, so far traced it back to get_dns_servers function in salt\bin\Lib\site-packages\salt\modules\win_dns_client.py.

For now I bypassed it by declaring configured_list = [''] on line 49 in salt\bin\lib\site-packages\salt\states\win_dns_client.py

**Comment by Mapel88** [comment]
Agreed. The problem is with `win_dns_client.get_dns_servers` function.
When running with default params it returns False:
```
C:\Users\maayana>salt-call win_dns_client.get_dns_servers -l debug
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Including configuration from 'c:\salt\conf\minion.d\_schedule.conf'
[DEBUG   ] Reading configuration from c:\salt\conf\minion.d\_schedule.conf
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Including configuration from 'c:\salt\conf\minion.d\_schedule.conf'
[DEBUG   ] Reading configuration from c:\salt\conf\minion.d\_schedule.conf
[DEBUG   ] Motherboard info not available on this system
[DEBUG   ] Loading static grains from c:\salt\conf\grains
[DEBUG   ] "il-octopus.corp.projecteam.com" Not an IP address? Assuming it is a hostname.
[DEBUG   ] Master URI: tcp://1.1.1.1:4506
[DEBUG   ] "il-octopus02.corp.projecteam.com" Not an IP address? Assuming it is a hostname.
[DEBUG   ] Master URI: tcp://1.1.1.2:4506
[DEBUG   ] Connecting to master. Attempt 1 (infinite attempts)
[DEBUG   ] "il-octopus.corp.projecteam.com" Not an IP address? Assuming it is a hostname.
[DEBUG   ] Master URI: tcp://1.1.1.1:4506
[DEBUG   ] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'iis03', 'tcp://1.1.1.1:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (4474)
[DEBUG   ] Setting zmq_reconnect_ivl to '4474ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'iis03', 'tcp://1.1.1.1:4506', 'clear')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://1.1.1.1:4506
[DEBUG   ] Trying to connect to: tcp://1.1.1.1:4506
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] salt.crypt._get_key_with_evict: Loading private key
[DEBUG   ] Loaded minion key: c:\minion.pem
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
[DEBUG   ] Connecting the Minion to the Master publish port, using the URI: tcp://1.1.1.1:4505
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] Loaded minion key: c:\minion.pem
[DEBUG   ] Determining pillar cache
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'iis03', 'tcp://1.1.1.1:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'iis03', 'tcp://1.1.1.1:4506')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://1.1.1.1:4506
[DEBUG   ] Trying to connect to: tcp://1.1.1.1:4506
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] Loaded minion key: c:\minion.pem
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded win_dns_client.get_dns_servers
[DEBUG   ] Interface "Local Area Connection" not found
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'iis03', 'tcp://1.1.1.1:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'iis03', 'tcp://1.1.1.1:4506')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://1.1.1.1:4506
[DEBUG   ] Trying to connect to: tcp://1.1.1.1:4506
[DEBUG   ] LazyLoaded nested.output
local:
    False
```


When passing argument getting syntax error:
```
C:\Users\maayana>salt-call win_dns_client.get_dns_servers 'Ethernet 5' -l debug
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Including configuration from 'c:\salt\conf\minion.d\_schedule.conf'
[DEBUG   ] Reading configuration from c:\salt\conf\minion.d\_schedule.conf
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Including configuration from 'c:\salt\conf\minion.d\_schedule.conf'
[DEBUG   ] Reading configuration from c:\salt\conf\minion.d\_schedule.conf
[DEBUG   ] Motherboard info not available on this system
[DEBUG   ] Loading static grains from c:\salt\conf\grains
[DEBUG   ] "il-octopus.corp.projecteam.com" Not an IP address? Assuming it is a hostname.
[DEBUG   ] Master URI: tcp://1.1.1.1:4506
[DEBUG   ] "il-octopus02.corp.projecteam.com" Not an IP address? Assuming it is a hostname.
[DEBUG   ] Master URI: tcp://1.1.1.2:4506
[DEBUG   ] Connecting to master. Attempt 1 (infinite attempts)
[DEBUG   ] "il-octopus.corp.projecteam.com" Not an IP address? Assuming it is a hostname.
[DEBUG   ] Master URI: tcp://1.1.1.1:4506
[DEBUG   ] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'iis03', 'tcp://1.1.1.1:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (3663)
[DEBUG   ] Setting zmq_reconnect_ivl to '3663ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'iis03', 'tcp://1.1.1.1:4506', 'clear')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://1.1.1.1:4506
[DEBUG   ] Trying to connect to: tcp://1.1.1.1:4506
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] salt.crypt._get_key_with_evict: Loading private key
[DEBUG   ] Loaded minion key: c:\minion.pem
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
[DEBUG   ] Connecting the Minion to the Master publish port, using the URI: tcp://1.1.1.1:4505
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] Loaded minion key: c:\minion.pem
[DEBUG   ] Determining pillar cache
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'iis03', 'tcp://1.1.1.1:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'iis03', 'tcp://1.1.1.1:4506')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://1.1.1.1:4506
[DEBUG   ] Trying to connect to: tcp://1.1.1.1:4506
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] Loaded minion key: c:\minion.pem
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded win_dns_client.get_dns_servers

Passed invalid arguments: get_dns_servers() takes from 0 to 1 positional arguments but 2 were given.

Usage:

    Return a list of the configured DNS servers of the specified interface

    CLI Example:

    .. code-block:: bash

        salt '*' win_dns_client.get_dns_servers 'Local Area Connection'

Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 212, in call
    ret['return'] = func(*args, **kwargs)
TypeError: get_dns_servers() takes from 0 to 1 positional arguments but 2 were given
```


Getting the same error when running the example:
`salt '*' win_dns_client.get_dns_servers 'Local Area Connection'`

**Comment by Mapel88** [comment]
any update on this?

**Comment by Mapel88** [comment]
Hi, @dwoz 
Can you please update on this?
Do you need additional info?

**Comment by Mapel88** [comment]
Not stale.
Bug marked with "additional info required" but not sure what other info you need.
Can anyone update on this?

@dwoz ?

**Comment by Mapel88** [comment]
Not stale!!!! 
Why is no one checking this bug????
You got all the information you need!

**Comment by utonium** [comment]
I'm running into this issue on Windows with the current version of the Salt master and minion (3000.1).

**Comment by utonium** [comment]
The fix, at least in my case, was to list the interfaces with 'network.interfaces_names' and determine I was not using the default interface name. I added that interface to my call for 'win_dns_client.dns_exists' and it addressed the error message that brought me to this thread.

**Comment by jfoboss** [comment]
Why is it closed? No one is using win_dns_client.dns_exists? It's not working :(

**Comment by Grayfoox** [comment]
+1 

same problem, documentation don't reflect this issue
