### ISSUE TITLE
Salt cloud azure: changed behavior of network security_group

### ISSUE THREAD

**Issue by cskowronnek** [saltstack/salt#53995]
### Description of Issue
The deployment of a new VM fails with an error
Command:
`salt-cloud -p azure-es-node-warm Elastic-Node-7 -l debug `

Output:
```
[DEBUG   ] https://management.azure.com:443 "GET /subscriptions/abc/resourceGroups/ELK/providers/Microsoft.Network/networkSecurityGroups/ELK?api-version=2017-03-01 HTTP/1.1" 200 None
[DEBUG   ] Parameter 'SecurityRule.destination_address_prefix' can not be None.
[DEBUG   ] Parameter 'SecurityRule.destination_address_prefix' can not be None.
[DEBUG   ] Parameter 'SecurityRule.source_address_prefix' can not be None.
[DEBUG   ] Parameter 'SecurityRule.source_address_prefix' can not be None.
[ERROR   ] There was a profile error: Parameter 'SecurityRule.destination_address_prefix' can not be None.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 281, in run
    self.config.get('names')
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1458, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1288, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/azurearm.py", line 1403, in create
    vm_request = request_instance(vm_=vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/azurearm.py", line 998, in request_instance
    kwargs=vm_
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/azurearm.py", line 884, in create_network_interface
    kwargs['resource_group'], kwargs['iface_name'], iface_params
  File "/usr/local/lib/python2.7/dist-packages/azure/mgmt/network/v2017_03_01/operations/network_interfaces_operations.py", line 233, in create_or_update
    body_content = self._serialize.body(parameters, 'NetworkInterface')
  File "/usr/local/lib/python2.7/dist-packages/msrest/serialization.py", line 579, in body
    raise errors[0]
ValidationError: Parameter 'SecurityRule.destination_address_prefix' can not be None.

```

### Setup
salt cloud profile:

```
azure-es-node-warm:
  provider: azurearm
  image: Canonical|UbuntuServer|18.04-LTS|latest
  size: Standard_B2ms
  location: westeurope
  resource_group: ELK
  network_resource_group: RG-INFRA
  security_group: ELK
  network: VNET-1
  subnet: VNET-1-Subnet1
  ssh_username: user
  ssh_keyfile: /etc/salt/cloud.profiles.d/key
  ssh_publickeyfile: /etc/salt/cloud.profiles.d/pub
  ssh_password: abc
  public_ip: False
  bootstrap_interface: private
  volumes:
    - disk_size_gb: 338
      caching: ReadWrite
      managed_disk:
        storage_account_type: Standard_LRS
    - disk_size_gb: 338
      caching: ReadWrite
      managed_disk:
        storage_account_type: Standard_LRS
    - disk_size_gb: 338
      caching: ReadWrite
      managed_disk:
        storage_account_type: Standard_LRS
  script: bootstrap-salt
  cleanup_disks: True
  cleanup_vhds: True
  cleanup_data_disks: True
  cleanup_interfaces: True

```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.12.3
       cherrypy: Not Installed
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 12 2018, 14:36:49)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-151-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by dwoz** [comment]
@cskowronnek Thanks for reporting this.

**Comment by nicholasmhughes** [comment]
@cskowronnek I'm guessing you might need to bump your Azure SDK versions to work w/ `2019.2`

What are you running now? (`pip freeze | egrep 'azure|msrest'`)

**Comment by nicholasmhughes** [comment]
The Azure functionality in Salt is moving to https://github.com/salt-extensions/saltext-azurerm

Please try out the extension and open an issue there if you are still encountering problems.
