### ISSUE TITLE
Salt 2019.2.1 and Debian 9 test failure

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt#54015]
https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-debian-9-py2/90/testReport/junit/unit.transport.test_zeromq/PubServerChannel/test_publish_to_pubserv_tcp/

**Comment by dmurphy18** [comment]
Believe that the ThreadPoolExecutor threads are receiving the signal SIGTERM and attempting to process after the main thread has already terminated the process

[2019-07-25T06:34:48.972Z]          test_issue_36469_tcp (unit.transport.test_zeromq.PubServerChannel) ... Process salt.transport.zeromq.<type 'instancemethod'>._publish_daemon:
[2019-07-25T06:34:48.972Z]        Traceback (most recent call last):
[2019-07-25T06:34:48.972Z]          File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
[2019-07-25T06:34:48.972Z]            self.run()
[2019-07-25T06:34:48.972Z]          File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
[2019-07-25T06:34:48.972Z]            self._target(*self._args, **self._kwargs)
[2019-07-25T06:34:48.972Z]          File "/tmp/kitchen/testing/salt/transport/zeromq.py", line 905, in _publish_daemon
[2019-07-25T06:34:48.972Z]            package = pull_sock.recv()
[2019-07-25T06:34:48.972Z]          File "zmq/backend/cython/socket.pyx", line 788, in zmq.backend.cython.socket.Socket.recv
[2019-07-25T06:34:48.972Z]          File "zmq/backend/cython/socket.pyx", line 824, in zmq.backend.cython.socket.Socket.recv
[2019-07-25T06:34:48.972Z]          File "zmq/backend/cython/socket.pyx", line 191, in zmq.backend.cython.socket._recv_copy
[2019-07-25T06:34:48.972Z]          File "zmq/backend/cython/socket.pyx", line 186, in zmq.backend.cython.socket._recv_copy
[2019-07-25T06:34:48.972Z]          File "zmq/backend/cython/checkrc.pxd", line 12, in zmq.backend.cython.checkrc._check_rc
[2019-07-25T06:34:48.972Z]            PyErr_CheckSignals()
[2019-07-25T06:34:48.972Z]          File "/tmp/kitchen/testing/salt/utils/event.py", line 1154, in _handle_signals
[2019-07-25T06:34:48.972Z]            super(EventPublisher, self)._handle_signals(signum, sigframe)
[2019-07-25T06:34:48.972Z]          File "/tmp/kitchen/testing/salt/utils/process.py", line 810, in _handle_signals
[2019-07-25T06:34:48.972Z]            process = psutil.Process(self.pid)
[2019-07-25T06:34:48.972Z]          File "/tmp/kitchen/testing/.nox/runtests-parametrized-2-7-coverage-true-crypto-none-transport-zeromq/local/lib/python2.7/site-packages/psutil/__init__.py", line 442, in __init__
[2019-07-25T06:34:48.972Z]            self._init(pid)
[2019-07-25T06:34:48.972Z]          File "/tmp/kitchen/testing/.nox/runtests-parametrized-2-7-coverage-true-crypto-none-transport-zeromq/local/lib/python2.7/site-packages/psutil/__init__.py", line 482, in _init
[2019-07-25T06:34:48.972Z]            raise NoSuchProcess(pid, None, msg)
[2019-07-25T06:34:48.972Z]        NoSuchProcess: psutil.NoSuchProcess no process found with pid 24394
[2019-07-25T06:34:49.276Z]        OK (2.310s)

Note there are 4 pid 24394 attempts in the log conforming to the 4 executor.submit in unit/transport/test_zeromq.py line 646

**Comment by dmurphy18** [comment]
PR for fix https://github.com/saltstack/salt/pull/54017

**Comment by KChandrashekhar** [comment]
The PR https://github.com/saltstack/salt/pull/54017 will also fix the issue in https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-29-py2/89/

**Comment by dmurphy18** [comment]
PR merged
