### ISSUE TITLE
salt-api does not return generated keypair

### ISSUE THREAD

**Issue by johnnybubonic** [saltstack/salt#54041]
### Description of Issue
When following [the example](https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html#post--keys) (with proper credentials substituted in), a 500 is returned (with no tarball returned, obviously) with the following error content:

```HTML
<!DOCTYPE html PUBLIC
"-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>500 Internal Server Error</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>500 Internal Server Error</h2>
        <p>The server encountered an unexpected condition which prevented it from fulfilling the request.</p>
        <pre id="traceback"></pre>
    <div id="powered_by">
      <span>
        Powered by <a href="http://www.cherrypy.org">CherryPy 5.6.0</a>
      </span>
    </div>
    </body>
</html>
```

And the following stack trace in /var/log/salt/api:

```Python
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python3.6/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/salt/netapi/rest_cherrypy/app.py", line 1727, in POST
    tarball.addfile(pub_key_file, six.StringIO(pub_key))
  File "/usr/lib64/python3.6/tarfile.py", line 1975, in addfile
    self.fileobj.write(buf)
TypeError: string argument expected, got 'bytes'
```
The key DOES seem to get generated, both based on the stacktrace and that there is a corresponding minion *pubkey* in /etc/salt/pki/master/minions/. It just isn't returned.

### Setup
N/A

### Steps to Reproduce Issue
Follow example in docs as linked in description.

### Versions Report
```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 2.1.12
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Apr 25 2019, 21:02:35)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.21.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core
```
NOTE: This is from the "salt-py3-latest" repo for CentOS 7.

**Comment by johnnybubonic** [comment]
This is because of a combination of:

(tarfile.py)
```Python
   1964     def addfile(self, tarinfo, fileobj=None):
   1965         """Add the TarInfo object `tarinfo' to the archive. If `fileobj' is
   1966            given, it should be a binary file, and tarinfo.size bytes are read
   1967            from it and added to the archive. You can create TarInfo objects
   1968            directly, or by using gettarinfo().
   1969         """
```

Up to python 2.7, io.StringIO could handle bytes as well as unicode. However, in python 3.x, it was changed to only handle unicode strings.

Lines 1725-1729 in salt/netapi/rest_cherrypy/app.py:

```Python
        fileobj = six.StringIO()
        tarball = tarfile.open(fileobj=fileobj, mode='w')
        tarball.addfile(pub_key_file, six.StringIO(pub_key))
        tarball.addfile(priv_key_file, six.StringIO(priv_key))
        tarball.close()
```
Per [six's docs](https://six.readthedocs.io/#six.BytesIO), this should be `six.BytesIO` rather than `six.StringIO` (as tarfile.add expects a bytes buffer, NOT a string buffer).

I'll see if I can get a pull request in.

**Comment by johnnybubonic** [comment]
Actually, I'm gonna hold off on that pull request, because this *might* be a packaging issue as well. I'm noticing some weird inconsistencies.

```Bash
[root@salttest-server salt]# rpm -qf /usr/lib/python3.6/site-packages/salt/netapi/rest_cherrypy/app.py 
salt-2019.2.0-2.el7.noarch
```

```Bash
[root@salttest-server salt]# yum info salt
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.cs.pitt.edu
 * epel: epel.mirror.constant.com
 * extras: mirror.cs.pitt.edu
 * updates: centos.mirror.constant.com
Installed Packages
Name        : salt
Arch        : noarch
Version     : 2019.2.0
Release     : 2.el7
Size        : 58 M
Repo        : installed
From repo   : salt-py3-latest
Summary     : A parallel remote execution system
URL         : http://saltstack.org/
License     : ASL 2.0
Description : Salt is a distributed remote execution system used to execute commands and
            : query data. It was developed in order to bring the best solutions found in
            : the world of remote execution together and make them better, faster and more
            : malleable. Salt accomplishes this via its ability to handle larger loads of
            : information, and not just dozens, but hundreds or even thousands of individual
            : servers, handle them quickly and through a simple and manageable interface.
```

```Bash
[root@salttest-server salt]# cat /etc/yum.repos.d/salt-py3-latest.repo 
[salt-py3-latest]
name=SaltStack Latest Release Channel Python 3 for RHEL/Centos $releasever
baseurl=https://repo.saltstack.com/py3/redhat/7/$basearch/latest
failovermethod=priority
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/saltstack-signing-key
```
`sed -n '1725,1729p' /usr/lib/python3.6/site-packages/salt/netapi/rest_cherrypy/app.py`:

```Python
        fileobj = six.StringIO()
        tarball = tarfile.open(fileobj=fileobj, mode='w')
        tarball.addfile(pub_key_file, six.StringIO(pub_key))
        tarball.addfile(priv_key_file, six.StringIO(priv_key))
        tarball.close()
```

BUT when I check out 2019.2 branch:

```Bash
[bts@cylon salt]$ git fetch
[bts@cylon salt]$ git branch -l
* 2019.2
  develop
  issue_54041_fix
```

`sed -n '1725,1729p' salt/netapi/rest_cherrypy/app.py` on this repo gives:
```Python
        fileobj = BytesIO()
        tarball = tarfile.open(fileobj=fileobj, mode='w')

        if six.PY3:
            pub_key = pub_key.encode(__salt_system_encoding__)
```

Something totally different. Am I missing something? Or are the CentOS/RHEL 7.x PY3 packages futzed?

**Comment by johnnybubonic** [comment]
Whoops, sorry- figured that out. The RPM for salt-2019.2.0-2 is built against *tag* v2019.2.0 (or v2019.2.0rc2?), it seems.

Which is fine and dandy. But that doesn't fix the problem of the RPM having this bug, because it seems the 2019.2 *branch* contains the fix, but v2019.2.0(rc2)? tag does NOT have it.

So I guess what I'm asking is can you please build and release a new RPM containing this fix? Because I can't preseed keys via the API without it.

**Comment by dwoz** [comment]
@dmurphy18 Thoughts?

**Comment by dmurphy18** [comment]
@johnnybubonic @dwoz the current potential point release Salt 2019.2.1 contains the fix.  Hopefully we are close to releasing this soon since we are near to fixing any final issues found in QA.

Further note, the Python 3 packaging on Redhat (Centos) 7 is about to get altered with the dropping of Python 3.6 support from EPEL as it is moved into Redhat 7.7 which is currently in Beta.

**Comment by johnnybubonic** [comment]
@dmurphy18 thanks! i hope the release occurs soon.

was aware of the python3.6 move though; saw it in one of your other replies (#53559). for those hunting down the post in question in epel-devel list, [this](https://lists.fedoraproject.org/archives/list/epel-devel@lists.fedoraproject.org/thread/GUSLTD5AJWFEGBFK5EYFVH3LHQVHUBAP/) is it.

**Comment by johnnybubonic** [comment]
closing as it *should*? be in 2019.2.2 (haven't confirmed)
