### ISSUE TITLE
salt 2019: regression for file state on fuse

### ISSUE THREAD

**Issue by disaster123** [saltstack/salt#54075]
### Description of Issue
the replace function in file.py has the following code:
```
2279                 r_data = mmap.mmap(r_file.fileno(),
2280                                    0,
2281                                    access=mmap.ACCESS_READ)
```

this one uses mmap.MAP_SHARED by default which does not work on fuse filesystems. Instead you need to use mmap.MAP_PRIVATE

the fix is simple:
```
2279                 r_data = mmap.mmap(r_file.fileno(),
2280                                    0,
2281                                    access=mmap.ACCESS_READ|mmap.MAP_PRIVATE)
```

would be great to get this fixed in 2019.2.1

**Comment by disaster123** [comment]
There are some other places as well like:
2346                         r_data = mmap.mmap(r_file.fileno(),
2347                                            0,
2348                                            access=mmap.ACCESS_READ)

Error on fuse is:
```
    Function: file.replace
        Name: /etc/fuse/user.cfg
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/modules/file.py", line 2281, in replace
                  access=mmap.ACCESS_READ)
              OSError: [Errno 19] No such device
              
              During handling of the above exception, another exception occurred:
              
              Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 1933, in call
                  **cdata['kwargs'])
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 1939, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/file.py", line 4495, in replace
                  backslash_literal=backslash_literal)
                File "/usr/lib/python3/dist-packages/salt/modules/file.py", line 2284, in replace
                  r_data = salt.utils.stringutils.to_bytes("".join(r_file))
              TypeError: sequence item 0: expected str instance, bytes found
```

**Comment by garethgreenaway** [comment]
@disaster123 Thanks for the report.  We'll get this one fixed.

**Comment by disaster123** [comment]
thanks - no chance for 2019.2.1 ?

**Comment by disaster123** [comment]
Why is this still unfixed in 2019.2.2?

**Comment by disaster123** [comment]
Still valid

**Comment by sagetherage** [comment]
@disaster123 not sure why and how we missed this one in 2019.2.2 and I apologize for that mis-step. Likely we need to look at our processes (something I will do in the near future), but for now, we are going to look to get it fixed sooner rather than later. I will be following up the next couple of day as will the core-team.

**Comment by disaster123** [comment]
@sagetherage thanks a lot - sadly there are a lot more regressions in 2019.2 i found and reported - but none of them has ever been fixed

**Comment by sagetherage** [comment]
@disaster123 I will take a look at the tickets you mention above and attempt to get them address in the master branch release, are you author of these regressions? If you are on the community slack, you can reach me there at the same handle and send me links to tickets, but I will also do a search in the main salt repo. If there are other repos, please let me know so I can explore further.

**Comment by dwoz** [comment]
@disaster123 what fuse filesystem are you using?

**Comment by disaster123** [comment]
@dwoz pve fuse but i don't think this is relevant there are a LOT of fuse filesystems out there which do not support this.

Just google for "fuse mmap access_read no such device"

**Comment by sagetherage** [comment]
@disaster123 we were wondering about your use-case so we could also develop a test against it.

**Comment by disaster123** [comment]
Use case:
Proxmox (www.proxmox.com) uses a fuse filesystem for /etc/pve/ to store cluster wide config files which i manage via salt.

**Comment by vmichel-ephe** [comment]
Still can't append to files on the PVE fuse filesystem

**Comment by Pier-areas** [comment]
I do encounter the samle on PVE filesystem (proxmox related fs)
