### ISSUE TITLE
[salt-ssh] AttributeError raised when targeting an IP address

### ISSUE THREAD

**Issue by rossengeorgiev** [saltstack/salt#54076]
### Description of Issue
Looks like `salt-ssh` is trying to resolve the hostname when targeting an IP directly. Failing to resolve the hostname causes it to fail completely. 

I would expect the command just run without issue. I don't see why reverse DNS is required for this at all. 

### Steps to Reproduce Issue
```yaml
# salt-ssh --user=vagrant --passwd=vagrant --sudo 192.168.22.131 test.ping
[ERROR   ] An un-handled exception from the multiprocessing process 'MultiprocessingProcess-1' was caught:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/process.py", line 765, in _run
    return self._original_run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 521, in handle_routine
    **target)
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 925, in __init__
    self.shell = salt.client.ssh.shell.gen_shell(opts, **args)
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/shell.py", line 64, in gen_shell
    shell = Shell(opts, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/shell.py", line 92, in __init__
    self.host = host.strip('[]')
AttributeError: 'NoneType' object has no attribute 'strip'
Process MultiprocessingProcess-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/site-packages/salt/utils/process.py", line 765, in _run
    return self._original_run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 521, in handle_routine
    **target)
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 925, in __init__
    self.shell = salt.client.ssh.shell.gen_shell(opts, **args)
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/shell.py", line 64, in gen_shell
    shell = Shell(opts, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/shell.py", line 92, in __init__
    self.host = host.strip('[]')
AttributeError: 'NoneType' object has no attribute 'strip'
[ERROR   ] Target 'None' did not return any data, probably due to an error.
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/bin/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 456, in salt_ssh
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/ssh.py", line 24, in run
    ssh.run()
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 774, in run
    self.cache_job(jid, host, ret[host], fun)
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 700, in cache_job
    'fun': fun})
  File "/usr/lib/python2.7/site-packages/salt/returners/local_cache.py", line 144, in returner
    hn_dir = os.path.join(jid_dir, load['id'])
  File "/usr/lib64/python2.7/posixpath.py", line 75, in join
    if b.startswith('/'):
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/bin/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 456, in salt_ssh
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/ssh.py", line 24, in run
    ssh.run()
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 774, in run
    self.cache_job(jid, host, ret[host], fun)
  File "/usr/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 700, in cache_job
    'fun': fun})
  File "/usr/lib/python2.7/site-packages/salt/returners/local_cache.py", line 144, in returner
    hn_dir = os.path.join(jid_dir, load['id'])
  File "/usr/lib64/python2.7/posixpath.py", line 75, in join
    if b.startswith('/'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```
Adding the host to `/etc/hosts` or DNS resolves the issue:
```yaml
# echo "192.168.22.131 myhost.home" >> /etc/hosts
# salt-ssh -i --user=vagrant --passwd=vagrant --sudo 192.168.22.131 test.ping
myhost.home:
    True
```

### Versions Report
I've encountered this issue before on other versions. I have not verified, but `2017` and `2018` are probably also affected.

```yaml
# salt-ssh --versions-report
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```

**Comment by garethgreenaway** [comment]
@rossengeorgiev Thanks for the report.  When you're adding the entry into /etc/hosts is that on the target machine or the machine you're running salt-ssh from?

**Comment by rossengeorgiev** [comment]
@garethgreenaway, its all on the same host. I think the following is the offending code:

https://github.com/saltstack/salt/blob/cb6cfcc5945cc66c9e675b2777dde8591eedd20d/salt/client/ssh/__init__.py#L408-L410

I'm guessing, if I target an IP address and PTR points to hostname that points to a different IP, I would connect to that second IP. That is frankly a terrible behavior.

**Comment by garethgreenaway** [comment]
@rossengeorgiev That code appears to be attempting to figure out what the name of the minion is based on the hostname, which would update the target to be used for things like grains, pillars, etc.  It does not appear that it is forcing a reconnecting to another IP address.  A couple follow up questions.  Are you using a roster with salt-ssh?  Is `myhost.home` the hostname of the machine that you're using salt-ssh against?  Thanks!

**Comment by rossengeorgiev** [comment]
I'm fairly certain it will do that. I've seen badly maintained DNS servers with records like that.
```
input IP -> rDNS -> somehostname
somehostname ->fDNS -> another IP
```
The reproduction steps are all I did after installing `salt-ssh` package. There are not rosters, Saltfiles, pillar or states.

Looks like I've actually reported this issue before last year in #49968, which was closed a duplicate of #49840.

**Comment by max-arnold** [comment]
Couldn't agree more! Reverse DNS zones could contain any garbage. Salt shouldn't trust that data.

**Comment by max-arnold** [comment]
This is also a potential security problem

**Comment by max-arnold** [comment]
Bump

**Comment by Ch3LL** [comment]
going to close as a duplicate in favor of https://github.com/saltstack/salt/issues/49840

please monitor that issue for any updates
