### ISSUE TITLE
Exception thrown when trying to deploy state.sls from master (2019.2)

### ISSUE THREAD

**Issue by ksalman** [saltstack/salt#54092]
### Description of Issue
I am trying to deploy a state on the minion. I can deploy the state if I run `salt-call state.sls test` on the minion but I cannot deploy the state if I run `salt minionid state.sls test` on the master. 

I see this exception when I try from the master
```
saltminiondev-0:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1660, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 1297, in sls
        initial_pillar=_get_initial_pillar(opts))
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 4081, in __init__
        initial_pillar=initial_pillar)
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 741, in __init__
        self.opts['pillar'] = self._gather_pillar()
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 803, in _gather_pillar
        return pillar.compile_pillar()
      File "/usr/lib/python2.7/site-packages/salt/pillar/__init__.py", line 248, in compile_pillar
        dictkey='pillar',
      File "/usr/lib/python2.7/site-packages/salt/utils/asynchronous.py", line 64, in wrap
        ret = self._block_future(ret)
      File "/usr/lib/python2.7/site-packages/salt/utils/asynchronous.py", line 74, in _block_future
        return future.result()
      File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result
        raise_exc_info(self._exc_info)
      File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 879, in run
        yielded = self.gen.send(value)
      File "/usr/lib/python2.7/site-packages/salt/transport/zeromq.py", line 297, in crypted_transfer_decode_dictentry
        aes = cipher.decrypt(ret['key'])
      File "/usr/lib64/python2.7/site-packages/Crypto/Cipher/PKCS1_OAEP.py", line 227, in decrypt
        raise ValueError("Incorrect decryption.")
    ValueError: Incorrect decryption.

```

### Setup

/srv/salt/test.sls:
```
/tmp/foobar:
  file.touch
```

### Versions Report
I am using 2019.2.0 in both master and minion
```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.3
         locale: UTF-8
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.3
```

/etc/salt/master:
```
timeout: 60
open_mode: True
auto_accept: True
state_output: mixed
file_roots:
  base:
    - /srv/salt
pillar_roots:
  base:
    - /srv/salt/pillar
```
/etc/salt/minion:
```
master: 192.168.1.3
```

**Comment by garethgreenaway** [comment]
@ksalman Thanks for the report.  It appears there might be an issue with either tornado or pycrypto.  @saltstack/team-core Any thoughts?

**Comment by waynew** [comment]
Seems like we should be able to reproduce this with a docker image without too much effort, unless the issue is just with the keys somehow.

**Comment by ksalman** [comment]
For what it's worth, I tried salt master (Python 3) on Ubuntu 16, and I am getting the same error. 
```
saltminiondev-0:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1660, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 1297, in sls
        initial_pillar=_get_initial_pillar(opts))
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 4081, in __init__
        initial_pillar=initial_pillar)
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 741, in __init__
        self.opts['pillar'] = self._gather_pillar()
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 803, in _gather_pillar
        return pillar.compile_pillar()
      File "/usr/lib/python2.7/site-packages/salt/pillar/__init__.py", line 248, in compile_pillar
        dictkey='pillar',
      File "/usr/lib/python2.7/site-packages/salt/utils/asynchronous.py", line 64, in wrap
        ret = self._block_future(ret)
      File "/usr/lib/python2.7/site-packages/salt/utils/asynchronous.py", line 74, in _block_future
        return future.result()
      File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result
        raise_exc_info(self._exc_info)
      File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 879, in run
        yielded = self.gen.send(value)
      File "/usr/lib/python2.7/site-packages/salt/transport/zeromq.py", line 297, in crypted_transfer_decode_dictentry
        aes = cipher.decrypt(ret['key'])
      File "/usr/lib64/python2.7/site-packages/Crypto/Cipher/PKCS1_OAEP.py", line 227, in decrypt
        raise ValueError("Incorrect decryption.")
    ValueError: Incorrect decryption.
```
```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.2 (default, Nov 17 2016, 17:05:23)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-83-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
I am not sure why the traceback shows that path and why it's using python2.7. That path doesn't even exist on either master or minion. Here is the path for PKCS1_OAEP.py on both.
```
find / -name PKCS1_OAEP.py
/usr/lib/python3/dist-packages/Crypto/Cipher/PKCS1_OAEP.py
```

**Comment by ksalman** [comment]
> 
> 
> Seems like we should be able to reproduce this with a docker image without too much effort, unless the issue is just with the keys somehow.

I tried deleting the keys at /etc/salt/pki on the master and the minion, and restarted the services. That did not appear to change anything.

**Comment by ksalman** [comment]
Any idea what could be wrong? It's pretty unusable as it is :S

**Comment by ksalman** [comment]
Weirdly it appears to be working after re-installing.

**Comment by waynew** [comment]
I suspect either one of your dependencies got pooched or you had a weird caching issue. Thanks for updating!

**Comment by Deshke** [comment]
i have same issue with some instances, e.g we have a standard image that is copied to all aws regions, 5 out of 99 instances report this issue
