### ISSUE TITLE
salt.states.logrotate doesn't create conf_file

### ISSUE THREAD

**Issue by nergdron** [saltstack/salt#54142]
### Description of Issue
When setting a logrotate configuration using the logrotate state, and a config file other than the default is specified, the logrotate state doesn't create it if it's not already present. This means on a fresh system, all logrotate configuration has to be a two-part operation, where the empty file is created first and then config is added to it after. It'd be better behaviour create the file if it doesn't exist, as part of this state.

### Setup
```yaml
logrotate_config:
  logrotate.set:
    - key: rotate
    - value: 5
    - conf_file: /etc/logrotate.d/defaults
```

### Steps to Reproduce Issue
output:
```
salt-apply:341]           ID: logrotate_config
[salt-apply:342]     Function: logrotate.set
[salt-apply:343]       Result: False
[salt-apply:344]      Comment: An exception occurred in this state: Traceback (most recent call last):
[salt-apply:345]                 File "/root/.local/lib/python3.6/site-packages/salt/state.py", line 1933, in call
[salt-apply:346]                   **cdata['kwargs'])
[salt-apply:347]                 File "/root/.local/lib/python3.6/site-packages/salt/loader.py", line 1939, in wrapper
[salt-apply:348]                   return f(*args, **kwargs)
[salt-apply:349]                 File "/root/.local/lib/python3.6/site-packages/salt/states/logrotate.py", line 87, in set_
[salt-apply:350]                   current_value = __salt__['logrotate.get'](key=key, conf_file=conf_file)
[salt-apply:351]                 File "/root/.local/lib/python3.6/site-packages/salt/modules/logrotate.py", line 163, in get
[salt-apply:352]                   current_conf = _parse_conf(conf_file)
[salt-apply:353]                 File "/root/.local/lib/python3.6/site-packages/salt/modules/logrotate.py", line 72, in _parse_conf
[salt-apply:354]                   with salt.utils.files.fopen(conf_file, 'r') as ifile:
[salt-apply:355]                 File "/root/.local/lib/python3.6/site-packages/salt/utils/files.py", line 399, in fopen
[salt-apply:356]                   f_handle = open(*args, **kwargs)  # pylint: disable=resource-leakage
[salt-apply:357]               FileNotFoundError: [Errno 2] No such file or directory: '/etc/logrotate.d/defaults'
[salt-apply:358]      Started: 19:26:45.652859
[salt-apply:359]     Duration: 0.858 ms
```

### Versions Report
```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.12.3
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.3 (default, Apr  3 2019, 05:39:12)
   python-gnupg: Not Installed
         PyYAML: 5.1
          PyZMQ: 18.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: Ubuntu 19.04 disco
         locale: UTF-8
        machine: x86_64
        release: 5.0.0-21-generic
         system: Linux
        version: Ubuntu 19.04 disco
```

**Comment by cmcmarrow** [comment]
For example pylint does not like 'ok' just changine 'ok' to 'okay' will fix that pylint warning.
