### ISSUE TITLE
integration.shell.test_syndic.SyndicTest.test_exit_status_correct_usage

### ISSUE THREAD

**Issue by KChandrashekhar** [saltstack/salt#54184]
### Description of Issue
https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-mac-mojave-py2/97/testReport/junit/integration.shell.test_syndic/SyndicTest/test_exit_status_correct_usage/

AccessDenied: psutil.AccessDenied (pid=81236)

**Comment by KChandrashekhar** [comment]
Non-blocker for the release but need to address after

**Comment by dwoz** [comment]
We've also seen this fail with a traceback
```
Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/shell/test_syndic.py", line 126, in test_exit_status_correct_usage
    syndic.shutdown(wait_for_orphans=3)
  File "/tmp/kitchen/testing/tests/integration/utils/testprogram.py", line 854, in shutdown
    terminate_process(pid=pid, kill_children=True)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pytestsalt/utils/__init__.py", line 188, in terminate_process
    terminate_process_list(process_list, kill=slow_stop is False, slow_stop=slow_stop)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pytestsalt/utils/__init__.py", line 126, in terminate_process_list
    cmdline = proc.cmdline()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/psutil/__init__.py", line 790, in cmdline
    return self._proc.cmdline()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/psutil/_psosx.py", line 339, in wrapper
    return fun(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/psutil/_psosx.py", line 425, in cmdline
    return cext.proc_cmdline(self.pid)
OSError: [Errno 5] Input/output error
```

**Comment by sagetherage** [comment]
@dwoz I am unsure that this still needs your attention or not, so I am closing it for now.
