### ISSUE TITLE
Salt pip.installed with upgrade=True not working for all modules

### ISSUE THREAD

**Issue by gigi206** [saltstack/salt#54253]
### Description of Issue
State **pip.installed** with option **upgrade=True** failed on somes python modules

### Steps to Reproduce Issue
```
$ C:\salt\bin\python.exe C:\salt\bin\Scripts\salt-call state.single pip.installed black bin_env="C:\Program Files\Python3\Scripts\pip.exe"
local:
          ID: black
    Function: pip.installed
      Result: True
     Comment: All packages were successfully installed
     Started: 19:28:33.034069
    Duration: 3042.087 ms
     Changes:
              ----------
              black==19.3b0:
                  Installed

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   3.042 s
```
Module **black** is installed. Try now to upgrade :
```
$ C:\salt\bin\python.exe C:\salt\bin\Scripts\salt-call state.single pip.installed black upgrade=True bin_env="C:\Program Files\Python3\Scripts\pip.exe"
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\state.py", line 1933, in call
    **cdata['kwargs'])
  File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1939, in wrapper
    return f(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\states\pip_state.py", line 765, in installed
    **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\states\pip_state.py", line 274, in _check_if_installed
    desired_version = available_versions[-1]
TypeError: 'NoneType' object is not subscriptable

local:
----------
          ID: black
    Function: pip.installed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "C:\salt\bin\lib\site-packages\salt\state.py", line 1933, in call
                  **cdata['kwargs'])
                File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1939, in wrapper
                  return f(*args, **kwargs)
                File "C:\salt\bin\lib\site-packages\salt\states\pip_state.py", line 765, in installed
                  **kwargs)
                File "C:\salt\bin\lib\site-packages\salt\states\pip_state.py", line 274, in _check_if_installed
                  desired_version = available_versions[-1]
              TypeError: 'NoneType' object is not subscriptable
     Started: 19:29:01.860493
    Duration: 1671.956 ms
     Changes:

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   1.672 s
```

With the module instead of the state it works:
```
$ C:\salt\bin\python.exe C:\salt\bin\Scripts\salt-call pip.install black upgrade=True bin_env="C:\Program Files\Python3\Scripts\pip.exe"
local:
    ----------
    pid:
        6928
    retcode:
        0
    stderr:
    stdout:
        Requirement already up-to-date: black in c:\program files\python3\lib\site-packages (19.3b0)
        Requirement already satisfied, skipping upgrade: toml>=0.9.4 in c:\program files\python3\lib\site-packages (from black) (0.10.0)
        Requirement already satisfied, skipping upgrade: attrs>=18.1.0 in c:\program files\python3\lib\site-packages (from black) (19.1.0)
        Requirement already satisfied, skipping upgrade: appdirs in c:\program files\python3\lib\site-packages (from black) (1.4.3)
        Requirement already satisfied, skipping upgrade: click>=6.5 in c:\program files\python3\lib\site-packages (from black) (7.0)
```

### Versions Report
```
$ C:\salt\bin\python.exe C:\salt\bin\Scripts\salt-call --versions-report
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.11.5
       cherrypy: 17.4.1
       dateutil: 2.7.5
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.10
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.28.2
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.28.2
         Python: 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.3
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 10
         system: Windows
        version: 10 10.0.18362 SP0 Multiprocessor Free
```

**Comment by frogunder** [comment]
@gigi206 Thank you for reporting this issue.

@saltstack/team-windows Do you have any input on this issue?

Thanks.

**Comment by gigi206** [comment]
I just install black with the salt state pip.installed and it seems to works:

![image](https://user-images.githubusercontent.com/13576579/63747145-b1863600-c8a6-11e9-8ee1-a2f9cbe55485.png)

**Comment by gigi206** [comment]
I analyse the issue.

The issue occurs only with black module because you filter alpha, beta and rc release.

And black has only alpha and beta release.

The workaround I found is to provide the version to ``pip.installed`` directly on the name:
```yaml
name: 'black >= 19.10b0'
```

In this case it works !
