### ISSUE TITLE
integration.modules.test_state.StateModuleTest.test_state_sls_unicode_characters

### ISSUE THREAD

**Issue by KChandrashekhar** [saltstack/salt#54365]
### Description of Issue
https://jenkinsci.saltstack.com/job/2019.2.1/view/Python3/job/salt-windows-2016-py3/194/

Error Message

argument of type 'bool' is not iterable
Stacktrace

Traceback (most recent call last):
  File "c:\users\admini~1\appdata\local\temp\kitchen\testing\tests\integration\modules\test_state.py", line 2047, in test_state_sls_unicode_characters
    self.assertIn(_expected, ret)
  File "C:\Python35\Lib\unittest\case.py", line 1085, in assertIn
    if member not in container:
TypeError: argument of type 'bool' is not iterable

**Comment by s0undt3ch** [comment]
Couldn't get this issue to trigger running the offending tests several times, not even on several full test suite runs.
We won't be able to know what happens until we turn on multiprocessng logging under Py3.
