### ISSUE TITLE
gitfs works but print traceback (Windows only)

### ISSUE THREAD

**Issue by gigi206** [saltstack/salt#54398]
### Setup
You must configure gitfs on Windows. Note that on Linux systems works without error

### Steps to Reproduce Issue
All commands procuce this error once gitfs is configured:
```
PS C:\WINDOWS\system32> C:\Python35\python.exe C:\Python35\Scripts\salt-call state.sls_exists salt/modules
[ERROR   ] Exception caught while fetching gitfs remote 'https://github.com/gigi206/VSCode-Anywhere.git': environment can only contain strings
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\salt\utils\gitfs.py", line 2372, in fetch_remotes
    if repo.fetch():
  File "C:\Python35\lib\site-packages\salt\utils\gitfs.py", line 777, in fetch
    return self._fetch()
  File "C:\Python35\lib\site-packages\salt\utils\gitfs.py", line 1291, in _fetch
    cleaned = self.clean_stale_refs()
  File "C:\Python35\lib\site-packages\salt\utils\gitfs.py", line 612, in clean_stale_refs
    stderr=subprocess.STDOUT)
  File "C:\Python35\lib\subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "C:\Python35\lib\subprocess.py", line 957, in _execute_child
    startupinfo)
TypeError: environment can only contain strings
local:
    True
```

### Versions Report
```
C:\Python35\python.exe C:\Python35\Scripts\salt-call --versions-report
Salt Version:
           Salt: 2019.2.0-n/a-37ceccb

Dependency Versions:
           cffi: 1.12.2
       cherrypy: 17.4.1
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.10
         Jinja2: 2.10.1
        libgit2: 0.28.2
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 3.8.1
   pycryptodome: Not Installed
         pygit2: 0.28.2
         Python: 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.4
         PyYAML: 3.13
          PyZMQ: 18.0.1
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 10
         system: Windows
        version: 10 10.0.18362 SP0 Multiprocessor Free
```

**Comment by xeacott** [comment]
Hi @gigi206 are you meaning that configuring gitfs on windows produces these errors with salt, whereas on a linux system counterpart, doing the same will not produce these errors?

**Comment by xeacott** [comment]
We also have someone here who may be able to provide more helpful information, ping @cmcmarrow

**Comment by gigi206** [comment]
Yes same config produce only this traceback on Windows.

Note that on Windows I use Python3 and on Linux I use Python2.

**Comment by DmitryKuzmenko** [comment]
This bug is introduced by PR #50917.
That code shall not hardcode binaries, but always use native strings for environment across py2/py3 versions.

**Comment by DmitryKuzmenko** [comment]
@gigi206 simplest fix for you is to revert this change (remove the `b`'s before strings):
```
diff --git a/salt/utils/gitfs.py b/salt/utils/gitfs.py
index c3127ff462..1cc06fcb09 100644
--- a/salt/utils/gitfs.py
+++ b/salt/utils/gitfs.py
@@ -590,8 +590,8 @@ class GitProvider(object):
         # According to stackoverflow (http://goo.gl/l74GC8), we are setting LANGUAGE as well
         # just to be sure.
         env = os.environ.copy()
-        env["LANGUAGE"] = "C"
-        env["LC_ALL"] = "C"
+        env[b"LANGUAGE"] = b"C"
+        env[b"LC_ALL"] = b"C"
 
         cmd = subprocess.Popen(
             shlex.split(cmd_str),
```

**Comment by DmitryKuzmenko** [comment]
BTW, it's not Windows related. It would fail on Linux Py3 too.

**Comment by gigi206** [comment]
Yes it fix the issue 👍

**Comment by gigi206** [comment]
When this fix will be published?

**Comment by cmcmarrow** [comment]
@gigi206 can I get a .sls that causes the 'error'. I have not been able to reproduce.

**Comment by cmcmarrow** [comment]
@gigi206 I was able to reproduce the error

**Comment by gigi206** [comment]
Nice, I use a fork of salt with my custom patches but it would be better if it was officially patched :)

I just revert the patch (thanks to @DmitryKuzmenko) to test on a dev branch (3000.1) and I the code crash on Windows => https://ci.appveyor.com/project/gigi206/vscode-anywhere/builds/32727312#L399

But it seems strange I test on Linux, with python3 and I haven't the issue (test with https://travis-ci.org)...

**Comment by dwoz** [comment]
Fixed by #56955 (twangboy, merged 2020-05-07, commit dfdcf95d935), which gates the bytes-keyed `env[b"LANGUAGE"]/env[b"LC_ALL"]` mutation in `salt/utils/gitfs.py:clean_stale_refs` behind `if not salt.utils.platform.is_windows():`. Present on 3006.x, 3007.x, 3008.x, master. The PR was titled "Fix stacktrace in return from win_pkg" and only referenced #56952, so this issue never auto-closed.
