### ISSUE TITLE
unit.utils.test_win_dacl.WinDaclFileTestCase.test_check_perms

### ISSUE THREAD

**Issue by KChandrashekhar** [saltstack/salt#54391]
### Description of Issue
https://jenkinsci.saltstack.com/job/2019.2.1/view/Python3/job/salt-windows-2019-py3/195

Error Message

{'Not[93 chars]': ['Create files / write data', 'Delete', 'Wr[37 chars]]}}}} != {'Not[93 chars]': ['Delete', 'Create files / write data', 'Wr[37 chars]]}}}}   {'Not Inherited': {'NETWORK SERVICE': {'deny': {'applies to': 'Not Inherited '                                                                 '(file)', -                                                 'permissions': ['Create files ' ?                                                                  ^^ ^  -------  +                                                 'permissions': ['Delete', ?                                                                  ^ ^^   +  +                                                                 'Create files '                                                                   '/ write data', -                                                                 'Delete',                                                                   'Write '                                                                   'attributes',                                                                   'Change '                                                                   'permissions']}}}}
Stacktrace

Traceback (most recent call last):
  File "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\kitchen\\testing\tests\support\helpers.py", line 129, in wrap
    return caller(cls)
  File "c:\users\admini~1\appdata\local\temp\kitchen\testing\tests\unit\utils\test_win_dacl.py", line 607, in test_check_perms
    expected)
AssertionError: {'Not[93 chars]': ['Create files / write data', 'Delete', 'Wr[37 chars]]}}}} != {'Not[93 chars]': ['Delete', 'Create files / write data', 'Wr[37 chars]]}}}}
  {'Not Inherited': {'NETWORK SERVICE': {'deny': {'applies to': 'Not Inherited '
                                                                '(file)',
-                                                 'permissions': ['Create files '
?                                                                  ^^ ^  -------

+                                                 'permissions': ['Delete',
?                                                                  ^ ^^   +

+                                                                 'Create files '
                                                                  '/ write data',
-                                                                 'Delete',
                                                                  'Write '
                                                                  'attributes',
                                                                  'Change '
                                                                  'permissions']}}}}

**Comment by KChandrashekhar** [comment]
Fixed in https://github.com/saltstack/salt/pull/54386
