### ISSUE TITLE
http.query fails when using headers

### ISSUE THREAD

**Issue by nigelsim** [saltstack/salt#54410]
### Description of Issue
When using `http.query` with the `header_list` option the minion will crash when trying to send a response via *ZeroMQ*. Note, when running in a masterless setup this works.

This is somewhat related to #45590

### Setup
```
purge_cloudflare:
  http.query:
    - name:  https://api.cloudflare.com/client/v4/zones/CODE/purge_cache
    - method: POST
    - headers: True
    - header_list:
      - 'X-Auth-Key: KEY'
      - 'X-Auth-Email: EMAIL'
      - 'Content-Type: application/json'
    - data: '{"purge_everything":true}'
    - status: 200
```

### Steps to Reproduce Issue

1. In a master/minion setup add the above state
2. Call that state

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1582, in _target
    run_func(minion_instance, opts, data)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1577, in run_func
    return Minion._thread_return(minion_instance, opts, data)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1772, in _thread_return
    timeout=minion_instance._return_retry_timer()
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 2002, in _return_pub
    ret_val = self._send_req_sync(load, timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1394, in _send_req_sync
    return channel.send(load, timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/salt/utils/asynchronous.py", line 64, in wrap
    ret = self._block_future(ret)
  File "/usr/lib/python2.7/dist-packages/salt/utils/asynchronous.py", line 74, in _block_future
    return future.result()
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 373, in send
    ret = yield self._crypted_transfer(load, tries=tries, timeout=timeout, raw=raw)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 341, in _crypted_transfer
    ret = yield _do_transfer()
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 307, in wrapper
    yielded = next(result)
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 323, in _do_transfer
    self._package_load(self.auth.crypticle.dumps(load)),
  File "/usr/lib/python2.7/dist-packages/salt/crypt.py", line 1465, in dumps
    return self.encrypt(self.PICKLE_PAD + self.serial.dumps(obj))
  File "/usr/lib/python2.7/dist-packages/salt/payload.py", line 221, in dumps
    return msgpack.dumps(msg, default=ext_type_encoder, use_bin_type=use_bin_type)
  File "/usr/lib/python2.7/dist-packages/msgpack/__init__.py", line 47, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 284, in msgpack._packer.Packer.pack
  File "msgpack/_packer.pyx", line 290, in msgpack._packer.Packer.pack
  File "msgpack/_packer.pyx", line 287, in msgpack._packer.Packer.pack
  File "msgpack/_packer.pyx", line 234, in msgpack._packer.Packer._pack
message repeated 3 times: [   File "msgpack/_packer.pyx", line 234, in msgpack._packer.Packer._pack]
  File "msgpack/_packer.pyx", line 281, in msgpack._packer.Packer._pack
TypeError: can't serialize <tornado.httputil.HTTPHeaders object at 0x7f5b50b8ec50>
```

### Versions Report
All a fresh install of the following

Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15+ (default, Nov 27 2018, 23:36:35)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 5.0.0-1018-azure
         system: Linux
        version: Ubuntu 18.04 bionic

**Comment by xeacott** [comment]
Thanks for submitting and bringing up a previous issue for reference! Anything quick come to mind @saltstack/team-core ?

**Comment by waynew** [comment]
Nothing I'm *aware* of, but from the stack trace it's clearly trying to serialize Tornado headers instead of some kind of dictionary type object. Naturally, that can't be done. It may be pretty obvious when and why this is happening, if one takes a quick step through the code around the stack trace

**Comment by Ch3LL** [comment]
Closing this due to age, the old version of Salt and Python 2.
Can you retest this with the latest release of Salt 3006.3 and if there is still an issue, please open a new issue, which will have metrics in tracking issues.
