### ISSUE TITLE
Critical Windows cache issue

### ISSUE THREAD

**Issue by gigi206** [saltstack/salt#54436]
### Description of Issue
Cache not working without admin rights

### Setup
Windows without admin rights
Gitfs configured

### Steps to Reproduce Issue
First run works

No **cache** direcitory exists :
```
dir C:\VSCode-Anywhere\Third-Party\Saltstack\var


    Répertoire : C:\VSCode-Anywhere\Third-Party\Saltstack\var


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       08/09/2019     19:27                log
```

```
salt-call --config-dir=C:\VSCode-Anywhere\Third-Party\Saltstack\conf --pillar-root=C:\VSCode-Anywhere\Third-Party\Saltstack\srv\pillar --cachedir=C:\VSCode-Anywhere\Third-Party\Saltstack\var\cache\salt\minion state.apply salt/conf
local:
----------
          ID: C:\VSCode-Anywhere\Third-Party\Saltstack\conf\minion.d\VSCode-Anywhere.conf
    Function: file.managed
      Result: True
     Comment: File C:\VSCode-Anywhere\Third-Party\Saltstack\conf\minion.d\VSCode-Anywhere.conf is in the correct state
     Started: 20:26:17.637926
    Duration: 108.115 ms
     Changes:
----------
          ID: C:\VSCode-Anywhere\Third-Party\Saltstack\conf\minion.d\VSCode-Anywhere-path.conf
    Function: file.managed
      Result: True
     Comment: File C:\VSCode-Anywhere\Third-Party\Saltstack\conf\minion.d\VSCode-Anywhere-path.conf is in the correct state
     Started: 20:26:17.746041
    Duration: 67.557 ms
     Changes:
----------
          ID: C:\VSCode-Anywhere\Third-Party\Saltstack\srv\pillar\top.sls
    Function: file.managed
      Result: True
     Comment: File C:\VSCode-Anywhere\Third-Party\Saltstack\srv\pillar\top.sls is in the correct state
     Started: 20:26:17.813598
    Duration: 35.543 ms
     Changes:
----------
          ID: C:\VSCode-Anywhere\Third-Party\Saltstack\srv\pillar\vscode-anywhere.sls
    Function: file.managed
      Result: True
     Comment: File C:\VSCode-Anywhere\Third-Party\Saltstack\srv\pillar\vscode-anywhere.sls is in the correct state
     Started: 20:26:17.849141
    Duration: 30.355 ms
     Changes:

Summary for local
------------
Succeeded: 4
Failed:    0
------------
Total states run:     4
Total run time: 241.570 ms
```

It works the 1st time.

Now if I run again it fails :

```
salt-call --config-dir=C:\VSCode-Anywhere\Third-Party\Saltstack\conf --pillar-root=C:\VSCode-Anywhere\Third-Party\Saltstack\srv\pillar --cachedir=C:\VSCode-Anywhere\Third-Party\Saltstack\var\cache\salt\minion state.apply salt/conf
[CRITICAL] Failed to load grains defined in grain file disks.disks in function <function disks at 0x0000025A70D3B840>, error:
Traceback (most recent call last):
  File "C:\VSCode-Anywhere\Third-Party\Saltstack\bin\lib\site-packages\salt\modules\cmdmod.py", line 650, in _run
    proc = salt.utils.timed_subprocess.TimedProc(cmd, **new_kwargs)
  File "C:\VSCode-Anywhere\Third-Party\Saltstack\bin\lib\site-packages\salt\utils\timed_subprocess.py", line 49, in __init__
    self.process = subprocess.Popen(args, **kwargs)
  File "C:\VSCode-Anywhere\Third-Party\Saltstack\bin\lib\subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "C:\VSCode-Anywhere\Third-Party\Saltstack\bin\lib\subprocess.py", line 957, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\VSCode-Anywhere\Third-Party\Saltstack\bin\lib\site-packages\salt\loader.py", line 798, in grains
    ret = funcs[key](**kwargs)
  File "C:\VSCode-Anywhere\Third-Party\Saltstack\bin\lib\site-packages\salt\grains\disks.py", line 38, in disks
    return _windows_disks()
  File "C:\VSCode-Anywhere\Third-Party\Saltstack\bin\lib\site-packages\salt\grains\disks.py", line 167, in _windows_disks
    wmic, namespace, path, where, get))
  File "C:\VSCode-Anywhere\Third-Party\Saltstack\bin\lib\site-packages\salt\modules\cmdmod.py", line 920, in _run_all_quiet
    success_retcodes=success_retcodes)
  File "C:\VSCode-Anywhere\Third-Party\Saltstack\bin\lib\site-packages\salt\modules\cmdmod.py", line 669, in _run
    raise CommandExecutionError(msg)
salt.exceptions.CommandExecutionError: Unable to run command 'REDACTED' with the context '{'shell': False, 'env': {'PATH': 'C:\\VSCode-Anywhere\\Third-Party\\Saltstack;C:\\VSCode-Anywhere\\Third-Party\\Saltstack;C:\\VSCode-Anywhere\\Third-Party\\Saltstack;C:\\VSCode-Anywhere\\Third-Party\\Saltstack;C:\\VSCode-Anywhere\\Third-Party\\Saltstack;C:\\VSCode-Anywhere\\Third-Party\\Saltstack;C:\\VSCode-Anywhere\\Third-Party\\Saltstack;C:\\Users\\gigi\\AppData\\Local\\Microsoft\\WindowsApps;C:\\tools\\git\\bin;C:\\VSCode-Anywhere\\Third-Party\\Chocolatey\\bin;C:\\VSCode-Anywhere\\Third-Party\\saltstack;C:\\VSCode-Anywhere\\Third-Party\\git\\bin;;C:\\VSCode-Anywhere\\Third-Party\\Saltstack\\bin\\lib\\site-packages\\pywin32_system32', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'SYSTEMDRIVE': 'C:', 'CHOCOLATEYINSTALL': 'C:\\VSCode-Anywhere\\Third-Party\\Chocolatey', 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files', 'PROGRAMW6432': 'C:\\Program Files', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'SCRIPT': 'C:\\VSCode-Anywhere\\Third-Party\\Saltstack\\bin\\Scripts\\salt-call', 'SALTDIR': 'C:\\VSCode-Anywhere\\Third-Party\\Saltstack', 'PROCESSOR_LEVEL': '6', 'PROGRAMDATA': 'C:\\ProgramData', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 'ONEDRIVE': 'C:\\Users\\gigi\\OneDrive', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'LOCALAPPDATA': 'C:\\Users\\gigi\\AppData\\Local', 'CHOCOLATEYEXITCODE': '0', 'USERDOMAIN_ROAMINGPROFILE': 'PORTABLE', 'VS140COMNTOOLS': 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\Tools\\', 'OS': 'Windows_NT', 'PROMPT': '$P$G', 'CHOCOLATEYLASTPATHUPDATE': '132124284765399963', 'PSEXECUTIONPOLICYPREFERENCE': 'Bypass', 'TEMP': 'C:\\Users\\gigi\\AppData\\Local\\Temp', 'WINDIR': 'C:\\WINDOWS', 'APPDATA': 'C:\\Users\\gigi\\AppData\\Roaming', 'PSMODULEPATH': 'C:\\Users\\gigi\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules', 'USERPROFILE': 'C:\\Users\\gigi', 'LANG': 'fr-FR', 'PROCESSOR_REVISION': '8e09', 'HOMEDRIVE': 'C:', 'PYTHON': 'C:\\VSCode-Anywhere\\Third-Party\\Saltstack\\bin\\python.exe', 'SYSTEMROOT': 'C:\\WINDOWS', 'TMP': 'C:\\Users\\gigi\\AppData\\Local\\Temp', 'HOMEPATH': '\\Users\\gigi', 'COMPUTERNAME': 'PORTABLE', 'SESSIONNAME': 'Console', 'LOGONSERVER': '\\\\PORTABLE', 'DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData', 'ONEDRIVECONSUMER': 'C:\\Users\\gigi\\OneDrive', 'USERDOMAIN': 'PORTABLE', 'PUBLIC': 'C:\\Users\\Public', 'ALLUSERSPROFILE': 'C:\\ProgramData', 'NUMBER_OF_PROCESSORS': '4', 'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe', 'CHOCOLATEYTOOLSLOCATION': 'C:\\VSCode-Anywhere\\Third-Party', 'USERNAME': 'gigi', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC', 'PROGRAMFILES': 'C:\\Program Files', 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 142 Stepping 9, GenuineIntel'}, 'with_communicate': True, 'bg': False, 'timeout': None, 'cwd': 'C:\\Users\\gigi', 'stdin': None, 'stderr': -1, 'stdout': -1}', reason: command not found
[ERROR   ] Exception caught while fetching gitfs remote 'https://github.com/gigi206/VSCode-Anywhere.git': environment can only contain strings
Traceback (most recent call last):
  File "C:\VSCode-Anywhere\Third-Party\Saltstack\bin\lib\site-packages\salt\utils\gitfs.py", line 2333, in fetch_remotes
    if repo.fetch():
  File "C:\VSCode-Anywhere\Third-Party\Saltstack\bin\lib\site-packages\salt\utils\gitfs.py", line 767, in fetch
    return self._fetch()
  File "C:\VSCode-Anywhere\Third-Party\Saltstack\bin\lib\site-packages\salt\utils\gitfs.py", line 1281, in _fetch
    cleaned = self.clean_stale_refs()
  File "C:\VSCode-Anywhere\Third-Party\Saltstack\bin\lib\site-packages\salt\utils\gitfs.py", line 602, in clean_stale_refs
    stderr=subprocess.STDOUT)
  File "C:\VSCode-Anywhere\Third-Party\Saltstack\bin\lib\subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "C:\VSCode-Anywhere\Third-Party\Saltstack\bin\lib\subprocess.py", line 957, in _execute_child
    startupinfo)
TypeError: environment can only contain strings
[ERROR   ] Failed to cache salt://salt/conf/conf/minion.d/VSCode-Anywhere.conf: (1314, 'GetNamedSecurityInfo', 'Le client ne dispose pas d\u2019un privilège nécessaire.')
[ERROR   ] Failed to cache salt://salt/conf/conf/minion.d/VSCode-Anywhere-path.conf: (1314, 'GetNamedSecurityInfo', 'Le client ne dispose pas d\u2019un privilège nécessaire.')
[ERROR   ] Unable to manage file: (1314, 'GetNamedSecurityInfo', 'Le client ne dispose pas d\u2019un privilège nécessaire.')
[ERROR   ] Unable to manage file: (1314, 'GetNamedSecurityInfo', 'Le client ne dispose pas d\u2019un privilège nécessaire.')
b"local:\n----------\n          ID: C:\\VSCode-Anywhere\\Third-Party\\Saltstack\\conf\\minion.d\\VSCode-Anywhere.conf\n    Function: file.managed\n      Result: False\n     Comment: Failed to cache salt://salt/conf/conf/minion.d/VSCode-Anywhere.conf: (1314, 'GetNamedSecurityInfo', 'Le client ne dispose pas d\xe2\x80\x99un privil\xc3\xa8ge n\xc3\xa9cessaire.')\n     Started: 20:32:38.170824\n    Duration: 70.689 ms\n     Changes:   \n----------\n          ID: C:\\VSCode-Anywhere\\Third-Party\\Saltstack\\conf\\minion.d\\VSCode-Anywhere-path.conf\n    Function: file.managed\n      Result: False\n     Comment: Failed to cache salt://salt/conf/conf/minion.d/VSCode-Anywhere-path.conf: (1314, 'GetNamedSecurityInfo', 'Le client ne dispose pas d\xe2\x80\x99un privil\xc3\xa8ge n\xc3\xa9cessaire.')\n     Started: 20:32:38.241513\n    Duration: 27.536 ms\n     Changes:   \n----------\n          ID: C:\\VSCode-Anywhere\\Third-Party\\Saltstack\\srv\\pillar\\top.sls\n    Function: file.managed\n      Result: False\n     Comment: Unable to manage file: (1314, 'GetNamedSecurityInfo', 'Le client ne dispose pas d\xe2\x80\x99un privil\xc3\xa8ge n\xc3\xa9cessaire.')\n     Started: 20:32:38.269049\n    Duration: 33.387 ms\n     Changes:   \n----------\n          ID: C:\\VSCode-Anywhere\\Third-Party\\Saltstack\\srv\\pillar\\vscode-anywhere.sls\n    Function: file.managed\n      Result: False\n     Comment: Unable to manage file: (1314, 'GetNamedSecurityInfo', 'Le client ne dispose pas d\xe2\x80\x99un privil\xc3\xa8ge n\xc3\xa9cessaire.')\n     Started: 20:32:38.302436\n    Duration: 30.695 ms\n     Changes:   \n\nSummary for local\n------------\nSucceeded: 0\nFailed:    4\n------------\nTotal states run:     4\nTotal run time: 162.307 ms"
```

It works if I delete the cache manually. Note that **saltutil.clear_cache** fails :

```
salt-call --config-dir=C:\VSCode-Anywhere\Third-Party\Saltstack\conf --pillar-root=C:\VSCode-Anywhere\Third-Party\Saltstack\srv\pillar --cachedir=C:\VSCode-Anywhere\Third-Party\Saltstack\var\cache\salt\minion saltutil.clear_cache
[CRITICAL] Failed to load grains defined in grain file disks.disks in function <function disks at 0x0000016B22429BF8>, error:
Traceback (most recent call last):
  File "C:\VSCode-Anywhere\Third-Party\Saltstack\bin\lib\site-packages\salt\modules\cmdmod.py", line 650, in _run
    proc = salt.utils.timed_subprocess.TimedProc(cmd, **new_kwargs)
  File "C:\VSCode-Anywhere\Third-Party\Saltstack\bin\lib\site-packages\salt\utils\timed_subprocess.py", line 49, in __init__
    self.process = subprocess.Popen(args, **kwargs)
  File "C:\VSCode-Anywhere\Third-Party\Saltstack\bin\lib\subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "C:\VSCode-Anywhere\Third-Party\Saltstack\bin\lib\subprocess.py", line 957, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\VSCode-Anywhere\Third-Party\Saltstack\bin\lib\site-packages\salt\loader.py", line 798, in grains
    ret = funcs[key](**kwargs)
  File "C:\VSCode-Anywhere\Third-Party\Saltstack\bin\lib\site-packages\salt\grains\disks.py", line 38, in disks
    return _windows_disks()
  File "C:\VSCode-Anywhere\Third-Party\Saltstack\bin\lib\site-packages\salt\grains\disks.py", line 167, in _windows_disks
    wmic, namespace, path, where, get))
  File "C:\VSCode-Anywhere\Third-Party\Saltstack\bin\lib\site-packages\salt\modules\cmdmod.py", line 920, in _run_all_quiet
    success_retcodes=success_retcodes)
  File "C:\VSCode-Anywhere\Third-Party\Saltstack\bin\lib\site-packages\salt\modules\cmdmod.py", line 669, in _run
    raise CommandExecutionError(msg)
salt.exceptions.CommandExecutionError: Unable to run command 'REDACTED' with the context '{'env': {'LANG': 'fr-FR', 'SCRIPT': 'C:\\VSCode-Anywhere\\Third-Party\\Saltstack\\bin\\Scripts\\salt-call', 'APPDATA': 'C:\\Users\\gigi\\AppData\\Roaming', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 'PATH': 'C:\\VSCode-Anywhere\\Third-Party\\Saltstack;C:\\VSCode-Anywhere\\Third-Party\\Saltstack;C:\\VSCode-Anywhere\\Third-Party\\Saltstack;C:\\VSCode-Anywhere\\Third-Party\\Saltstack;C:\\VSCode-Anywhere\\Third-Party\\Saltstack;C:\\VSCode-Anywhere\\Third-Party\\Saltstack;C:\\VSCode-Anywhere\\Third-Party\\Saltstack;C:\\Users\\gigi\\AppData\\Local\\Microsoft\\WindowsApps;C:\\tools\\git\\bin;C:\\VSCode-Anywhere\\Third-Party\\Chocolatey\\bin;C:\\VSCode-Anywhere\\Third-Party\\saltstack;C:\\VSCode-Anywhere\\Third-Party\\git\\bin;;C:\\VSCode-Anywhere\\Third-Party\\Saltstack\\bin\\lib\\site-packages\\pywin32_system32', 'PROCESSOR_LEVEL': '6', 'SESSIONNAME': 'Console', 'LOCALAPPDATA': 'C:\\Users\\gigi\\AppData\\Local', 'PROGRAMW6432': 'C:\\Program Files', 'WINDIR': 'C:\\WINDOWS', 'PROGRAMDATA': 'C:\\ProgramData', 'NUMBER_OF_PROCESSORS': '4', 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 142 Stepping 9, GenuineIntel', 'PROCESSOR_REVISION': '8e09', 'COMPUTERNAME': 'PORTABLE', 'SALTDIR': 'C:\\VSCode-Anywhere\\Third-Party\\Saltstack', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'PROMPT': '$P$G', 'CHOCOLATEYLASTPATHUPDATE': '132124284765399963', 'PSMODULEPATH': 'C:\\Users\\gigi\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules', 'VS140COMNTOOLS': 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\Tools\\', 'USERDOMAIN': 'PORTABLE', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'CHOCOLATEYTOOLSLOCATION': 'C:\\VSCode-Anywhere\\Third-Party', 'PUBLIC': 'C:\\Users\\Public', 'HOMEPATH': '\\Users\\gigi', 'TEMP': 'C:\\Users\\gigi\\AppData\\Local\\Temp', 'USERNAME': 'gigi', 'ONEDRIVECONSUMER': 'C:\\Users\\gigi\\OneDrive', 'CHOCOLATEYEXITCODE': '0', 'SYSTEMROOT': 'C:\\WINDOWS', 'DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData', 'SYSTEMDRIVE': 'C:', 'LOGONSERVER': '\\\\PORTABLE', 'CHOCOLATEYINSTALL': 'C:\\VSCode-Anywhere\\Third-Party\\Chocolatey', 'OS': 'Windows_NT', 'HOMEDRIVE': 'C:', 'USERDOMAIN_ROAMINGPROFILE': 'PORTABLE', 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files', 'ONEDRIVE': 'C:\\Users\\gigi\\OneDrive', 'PYTHON': 'C:\\VSCode-Anywhere\\Third-Party\\Saltstack\\bin\\python.exe', 'PROGRAMFILES': 'C:\\Program Files', 'PSEXECUTIONPOLICYPREFERENCE': 'Bypass', 'TMP': 'C:\\Users\\gigi\\AppData\\Local\\Temp', 'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'ALLUSERSPROFILE': 'C:\\ProgramData', 'USERPROFILE': 'C:\\Users\\gigi'}, 'bg': False, 'with_communicate': True, 'stdin': None, 'cwd': 'C:\\Users\\gigi', 'stdout': -1, 'shell': False, 'stderr': -1, 'timeout': None}', reason: command not found
[ERROR   ] Attempt to clear cache with saltutil.clear_cache FAILED with: [WinError 5] Accès refusé: 'C:\\VSCode-Anywhere\\Third-Party\\Saltstack\\var\\cache\\salt\\minion\\gitfs\\d189884602febd6b283b53aeac85ef83062e4ed2836b6c13ea88bfc036b18633\\.git\\objects\\pack\\pack-77c6194b8ef97e828e6b906b5b185e59c7845a1d.idx'
local:
    False
```

Each time I delete manually the directory **C:\VSCode-Anywhere\Third-Party\Saltstack\var\cache\salt\minion\files** it works again (1 time).

### Versions Report
```
salt-call --config-dir=C:\VSCode-Anywhere\Third-Party\Saltstack\conf --pillar-root=C:\VSCode-Anywhere\Third-Party\Saltstack\srv\pillar --cachedir=C:\VSCode-Anywhere\Third-Party\Saltstack\var\cache\salt\minion --versions-report
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.11.5
       cherrypy: 17.4.1
       dateutil: 2.7.5
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.10
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.3
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 10
         system: Windows
        version: 10 10.0.18362 SP0 Multiprocessor Free
```

**Comment by DmitryKuzmenko** [comment]
@saltstack/team-windows thoughts?

**Comment by waynew** [comment]
@gigi206 are you deleting the cache manually via the box, or are you using Salt to manually remove it (e.g. `salt 'your-minion' file.remove C:\VSCode-Anywhere\Third-Party\Saltstack\var\cache\salt\minion`)?

**Comment by gigi206** [comment]
I delete from the Windows file manager (**_explorer.exe_**) and I try also with **_saltutil.clear_cache_**.

**Comment by waynew** [comment]
@gigi206 it fails with `clear_cache`? Does it also fail when doing `file.remove`?

**Comment by gigi206** [comment]
Fix with the last version of saltstack
