### ISSUE TITLE
[virt.running] configure graphics - TypeError: list indices must be integers, not unicode

### ISSUE THREAD

**Issue by kartnico** [saltstack/salt#54435]
### Description of Issue
When I try to use virt.running state in order to configure graphics configuration of a virtual machine, I get an error : **TypeError: list indices must be integers, not unicode**

I tried the same configuration written in documentation: [here](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.virt.html#salt.states.virt.running)

And I also tried with only :
```
    - graphics:
      - type: vnc
```

### Setup
kvm.sls
```
create_virtual_machine_srv-01:
  virt.running:
    - name: srv-01
    - cpu: 2
    - mem: 2048
    - disk_profile: None
    - disks:
      - name: system
        format: qcow2
        size: 8192
        model: virtio
        pool: default
        image: https://cdimage.debian.org/cdimage/openstack/current-10/debian-10-openstack-amd64.qcow2
    - seed: False
    - nic_profile: None
    - interfaces:
      - name: eth0
        source: br0
        model: virtio
        type: bridge
    - graphics:
      - type: vnc
        listen:
          - type: address
            address: 0.0.0.0
```

### Steps to Reproduce Issue
```
          ID: create_virtual_machine_srv-01
    Function: virt.running
        Name: srv-01
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1933, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1939, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/virt.py", line 460, in running
                  password=password)
                File "/usr/lib/python2.7/site-packages/salt/modules/virt.py", line 1516, in init
                  vm_xml = _gen_xml(name, cpu, mem, diskp, nicp, hypervisor, os_type, arch, graphics, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/modules/virt.py", line 555, in _gen_xml
                  graphics['listen'] = {'type': 'address', 'address': '0.0.0.0'}
              TypeError: list indices must be integers, not unicode
     Started: 21:52:13.569578
    Duration: 33.727 ms
     Changes:
```

### Versions Report
```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.16 (default, Apr 30 2019, 15:54:43)
   python-gnupg: Not Installed
         PyYAML: 5.1
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 5.0.2
            ZMQ: 4.3.1
 
System Versions:
           dist: fedora 30 Thirty
         locale: UTF-8
        machine: x86_64
        release: 5.0.9-301.fc30.x86_64
         system: Linux
        version: Fedora 30 Thirty
```

**Comment by DmitryKuzmenko** [comment]
@kartnico could you please try to change the value to the dict, but not a list of one dict item. It's not your fault, it's not your fault, it's an issue int the module documentation.
```
    - graphics:
        type: vnc
        listen:
            type: address
            address: 0.0.0.0
```

Please let us know has this helped or not.

**Comment by kartnico** [comment]
Thanks, it works!

**Comment by kartnico** [comment]
#54483
