### ISSUE TITLE
Salt master error log

### ISSUE THREAD

**Issue by firelizzard18** [saltstack/salt#54477]
### Description of Issue
I tried to run `salt-call state.apply my-custom-state` from the minion and the master threw an exception. From the minion's perspective, the master timed out.

### Setup
The only interesting detail that I can really share is that the master is itself a minion of another master.

### Steps to Reproduce Issue
Unknown. Sometimes, things get weird and break, and I have to restart the master.

```
Sep 13 00:42:21 MY-MASTER salt-master[30043]: [ERROR   ] Some exception handling a payload from minion
Sep 13 00:42:21 MY-MASTER salt-master[30043]: Traceback (most recent call last):
Sep 13 00:42:21 MY-MASTER salt-master[30043]: File "/usr/lib/python2.7/site-packages/salt/transport/zeromq.py", line 687, in handle_message
Sep 13 00:42:21 MY-MASTER salt-master[30043]: ret, req_opts = yield self.payload_handler(payload)
Sep 13 00:42:21 MY-MASTER salt-master[30043]: File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 870, in run
Sep 13 00:42:21 MY-MASTER salt-master[30043]: value = future.result()
Sep 13 00:42:21 MY-MASTER salt-master[30043]: File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result
Sep 13 00:42:21 MY-MASTER salt-master[30043]: raise_exc_info(self._exc_info)
Sep 13 00:42:21 MY-MASTER salt-master[30043]: File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 215, in wrapper
Sep 13 00:42:21 MY-MASTER salt-master[30043]: result = func(*args, **kwargs)
Sep 13 00:42:21 MY-MASTER salt-master[30043]: File "/usr/lib/python2.7/site-packages/salt/master.py", line 1022, in _handle_payload
Sep 13 00:42:21 MY-MASTER salt-master[30043]: 'clear': self._handle_clear}[key](load)
Sep 13 00:42:21 MY-MASTER salt-master[30043]: File "/usr/lib/python2.7/site-packages/salt/master.py", line 1053, in _handle_clear
Sep 13 00:42:21 MY-MASTER salt-master[30043]: ret = getattr(self.clear_funcs, cmd)(load), {'fun': 'send_clear'}
Sep 13 00:42:21 MY-MASTER salt-master[30043]: File "/usr/lib/python2.7/site-packages/salt/master.py", line 2087, in publish
Sep 13 00:42:21 MY-MASTER salt-master[30043]: payload = self._prep_pub(minions, jid, clear_load, extra, missing)
Sep 13 00:42:21 MY-MASTER salt-master[30043]: File "/usr/lib/python2.7/site-packages/salt/master.py", line 2179, in _prep_pub
Sep 13 00:42:21 MY-MASTER salt-master[30043]: self.event.fire_event({'minions': minions}, clear_load['jid'])
Sep 13 00:42:21 MY-MASTER salt-master[30043]: File "/usr/lib/python2.7/site-packages/salt/utils/event.py", line 748, in fire_event
Sep 13 00:42:21 MY-MASTER salt-master[30043]: self.io_loop.run_sync(lambda: self.pusher.send(msg))
Sep 13 00:42:21 MY-MASTER salt-master[30043]: File "/usr/lib64/python2.7/site-packages/tornado/ioloop.py", line 444, in run_sync
Sep 13 00:42:21 MY-MASTER salt-master[30043]: return future_cell[0].result()
Sep 13 00:42:21 MY-MASTER salt-master[30043]: File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result
Sep 13 00:42:21 MY-MASTER salt-master[30043]: raise_exc_info(self._exc_info)
Sep 13 00:42:21 MY-MASTER salt-master[30043]: File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 876, in run
Sep 13 00:42:21 MY-MASTER salt-master[30043]: yielded = self.gen.throw(*exc_info)
Sep 13 00:42:21 MY-MASTER salt-master[30043]: File "/usr/lib/python2.7/site-packages/salt/transport/ipc.py", line 426, in send
Sep 13 00:42:21 MY-MASTER salt-master[30043]: yield self.stream.write(pack)
Sep 13 00:42:21 MY-MASTER salt-master[30043]: File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 870, in run
Sep 13 00:42:21 MY-MASTER salt-master[30043]: value = future.result()
Sep 13 00:42:21 MY-MASTER salt-master[30043]: File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result
Sep 13 00:42:21 MY-MASTER salt-master[30043]: raise_exc_info(self._exc_info)
Sep 13 00:42:21 MY-MASTER salt-master[30043]: File "<string>", line 3, in raise_exc_info
Sep 13 00:42:21 MY-MASTER salt-master[30043]: StreamClosedError
Sep 13 00:42:21 MY-MASTER salt-master[30043]: [ERROR   ] Uncaught exception, closing connection.
Sep 13 00:42:21 MY-MASTER salt-master[30043]: Traceback (most recent call last):
Sep 13 00:42:21 MY-MASTER salt-master[30043]: File "/usr/lib64/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 444, in _handle_events
Sep 13 00:42:21 MY-MASTER salt-master[30043]: self._handle_send()
Sep 13 00:42:21 MY-MASTER salt-master[30043]: File "/usr/lib64/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 487, in _handle_send
Sep 13 00:42:21 MY-MASTER salt-master[30043]: status = self.socket.send_multipart(msg, **kwargs)
Sep 13 00:42:21 MY-MASTER salt-master[30043]: File "/usr/lib64/python2.7/site-packages/zmq/sugar/socket.py", line 363, in send_multipart
Sep 13 00:42:21 MY-MASTER salt-master[30043]: i, rmsg,
Sep 13 00:42:21 MY-MASTER salt-master[30043]: TypeError: Frame 0 (u'Some exception handling minion...) does not support the buffer interface.
Sep 13 00:42:21 MY-MASTER salt-master[30043]: [ERROR   ] Exception in callback None
Sep 13 00:42:21 MY-MASTER salt-master[30043]: Traceback (most recent call last):
Sep 13 00:42:21 MY-MASTER salt-master[30043]: File "/usr/lib64/python2.7/site-packages/tornado/ioloop.py", line 865, in start
Sep 13 00:42:21 MY-MASTER salt-master[30043]: handler_func(fd_obj, events)
Sep 13 00:42:21 MY-MASTER salt-master[30043]: File "/usr/lib64/python2.7/site-packages/tornado/stack_context.py", line 274, in null_wrapper
Sep 13 00:42:21 MY-MASTER salt-master[30043]: return fn(*args, **kwargs)
Sep 13 00:42:21 MY-MASTER salt-master[30043]: File "/usr/lib64/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 444, in _handle_events
Sep 13 00:42:21 MY-MASTER salt-master[30043]: self._handle_send()
Sep 13 00:42:21 MY-MASTER salt-master[30043]: File "/usr/lib64/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 487, in _handle_send
Sep 13 00:42:21 MY-MASTER salt-master[30043]: status = self.socket.send_multipart(msg, **kwargs)
Sep 13 00:42:21 MY-MASTER salt-master[30043]: File "/usr/lib64/python2.7/site-packages/zmq/sugar/socket.py", line 363, in send_multipart
Sep 13 00:42:21 MY-MASTER salt-master[30043]: i, rmsg,
Sep 13 00:42:21 MY-MASTER salt-master[30043]: TypeError: Frame 0 (u'Some exception handling minion...) does not support the buffer interface.
```

### Versions Report
```
> salt --versions-report
Salt Version:
           Salt: 2018.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.11
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Oct 30 2018, 23:45:53)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.1.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core
```

```
> salt-minion --versions-report
Salt Version:
           Salt: 2018.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: 2.6.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Oct 30 2018, 23:45:53)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.1.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core
```

**Comment by DmitryKuzmenko** [comment]
Can't reproduce the issue. Could you please provide more details about your salt layout, configuration and the state code?

**Comment by ironman627** [comment]
Just updated pyOpenSSL to take care of different issue, restarted my master and received the above error. Here is my versions-report. I have not applied any states.
###############################
Salt Version:
           Salt: 2019.2.5

Dependency Versions:
           cffi: 1.14.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  7 2019, 00:51:29)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.7.1908 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1062.12.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.7.1908 Core
######################################
