### ISSUE TITLE
Salt SSH debugging 

### ISSUE THREAD

**Issue by kiemlicz** [saltstack/salt#54485]
### Question
I would like to see the logs from all calls on the remote host when using Salt SSH

In the doc https://docs.saltstack.com/en/latest/topics/ssh/ I found:  
`It is recommended that one modify this command a bit by removing the -l quiet, --metadata and --output json to get a better idea of what's going on the target system.`

How/where should I do this? (I've tried modifying the SALT_ARGV in `pyall/salt/client/ssh/ssh_py_shim.py` in thin_dir on the remote but it does nothing...)

Digging further:
I thought that setting (in `/etc/salt/roster`):
```
minion:
  host: minion.local
  user: dev
  sudo: True
  tty: True
  passwd: <redacted>
  minion_opts:
    log_level: info
    log_level_logfile: info
    log_file: /tmp/logfile
```
helps, but there is absolutely no `/tmp/logfile` on the remote host?!

Am I too stupid for this or this is broken?

Additionally (Salt 2019.2.0): is the Salt SSH really production ready?

**Comment by max-arnold** [comment]
The recommended approach involves ssh-ing into a remote host and invoking the `salt-call` command from a thin tarball (see https://docs.saltstack.com/en/latest/topics/ssh/#debugging-salt-ssh and https://www.eisscholle.net/spickzettel/saltstack/debug_salt-ssh)

However, there is a more straightforward method, and your example is almost right. You need to set `log_file` to something like `../../salt-ssh.log` so it would be kept intact after the `salt-ssh` command finishes.

See the animated gif for a complete example: https://twitter.com/SaltTips/status/1146306964026253312

Also see this email thread on how to solve a tangential problem with `salt-ssh` stdout/stderr logging https://groups.google.com/forum/#!topic/salt-users/1ZbMmAH4S6U

**Comment by kiemlicz** [comment]
Thank you!
So it turns out that the absolute path as `log_file` is not supported.
Many of the tweets from https://twitter.com/SaltTips are pure gold! Thank you for that awesome work!

**Comment by kiemlicz** [comment]
On the other hand:
Did you have any success with ssh login using keys (instead of `passwd`)
No matter what I do:
 - setting `priv` option
 - using default `priv` option (`/etc/salt/pki/master/ssh/salt-ssh.rsa`)

Every time `salt-ssh minion ...` commands are rejected with
```
Permission denied for host minion, do you want to deploy the salt-ssh key? (password required):
[Y/n] 
```

```
minion:
    Permission denied, no authentication information
```

Using `salt-ssh -i` doesn't help at all

I can find the `authorized_keys` for configured user but it still is rejected...

**Comment by max-arnold** [comment]
I tend to use ssh-agent with salt-ssh.

**Comment by kiemlicz** [comment]
I'm also using ssh-agent

When I configure the roster:
```
minion:
  host: minion.local
  user: dev
  sudo: true
  passwd: redacted
  tty: true
  minion_opts:
    log_level: debug
    log_level_logfile: debug
    log_file: ../../salt-ssh.log
```
It works. However when I try to use keys (`roster`):
```
minion:
  host: minion.mgl
  user: dev
  sudo: true
  tty: true
  minion_opts:
    log_level: debug
    log_level_logfile: debug
    log_file: ../../salt-ssh.log
```
I **always** end up with:
```
Permission denied for host minion, do you want to deploy the salt-ssh key? (password required):
[Y/n]
```
However adding `sudo_user` 'kind of solves the problem':
```
minion:
  host: minion.mgl
  user: dev
  sudo: true
  sudo_user: dev
  tty: true
  minion_opts:
    log_level: debug
    log_level_logfile: debug
    log_file: ../../salt-ssh.log
```
the `test.version` works but any state that requires sudo fails with permission denied (like pkg.installed), state log:
```
          ID: required_pkgs           
    Function: pkg.latest     
      Result: False   
     Comment: An error was encountered while checking the newest available version of package(s): W: chmod 0700 of directory /var/lib/apt/lists/partial failed - SetupAPTPartialDirectory (1: Operation not permitted)
              E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
              E: Unable to lock directory /var/lib/apt/lists/
              W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
              W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)
     Started: 17:42:46.161816
    Duration: 44.493 ms          
```
SSH minion log:
```
2019-09-15 17:42:45,786 [salt.utils.lazy  :104 ][DEBUG   ][5118] LazyLoaded pkg.latest
2019-09-15 17:42:45,845 [salt.loader      :1565][DEBUG   ][5118] Failed to import module datadog_api:
Traceback (most recent call last):
  File "/var/tmp/.dev_b45596_salt/pyall/salt/loader.py", line 1555, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/var/tmp/.dev_b45596_salt/pyall/salt/modules/datadog_api.py", line 22, in <module>
    import requests
ImportError: No module named requests
2019-09-15 17:42:45,891 [salt.loaded.int.module.config:398 ][DEBUG   ][5118] key: ifttt.secret_key, ret: _|-
2019-09-15 17:42:45,891 [salt.loaded.int.module.config:398 ][DEBUG   ][5118] key: ifttt:secret_key, ret: _|-
2019-09-15 17:42:45,957 [salt.loader      :1565][DEBUG   ][5118] Failed to import module opsgenie:
Traceback (most recent call last):
  File "/var/tmp/.dev_b45596_salt/pyall/salt/loader.py", line 1555, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/var/tmp/.dev_b45596_salt/pyall/salt/modules/opsgenie.py", line 26, in <module>
    import requests
ImportError: No module named requests
2019-09-15 17:42:45,965 [salt.loader      :1565][DEBUG   ][5118] Failed to import module pagerduty_util:
Traceback (most recent call last):
  File "/var/tmp/.dev_b45596_salt/pyall/salt/loader.py", line 1555, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/var/tmp/.dev_b45596_salt/pyall/salt/modules/pagerduty_util.py", line 23, in <module>
    import requests
ImportError: No module named requests
2019-09-15 17:42:45,971 [salt.loader      :1565][DEBUG   ][5118] Failed to import module pip:
Traceback (most recent call last):
  File "/var/tmp/.dev_b45596_salt/pyall/salt/loader.py", line 1555, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/var/tmp/.dev_b45596_salt/pyall/salt/modules/pip.py", line 82, in <module>
    import pkg_resources
ImportError: No module named pkg_resources
2019-09-15 17:42:45,977 [salt.loaded.int.module.config:398 ][DEBUG   ][5118] key: pushbullet.api_key, ret: _|-
2019-09-15 17:42:45,977 [salt.loaded.int.module.config:398 ][DEBUG   ][5118] key: pushbullet:api_key, ret: _|-
2019-09-15 17:42:45,990 [salt.utils.lazy  :104 ][DEBUG   ][5118] LazyLoaded systemd.booted
2019-09-15 17:42:46,050 [salt.loaded.int.module.config:398 ][DEBUG   ][5118] key: victorops.api_key, ret: _|-
2019-09-15 17:42:46,050 [salt.loaded.int.module.config:398 ][DEBUG   ][5118] key: victorops:api_key, ret: _|-
2019-09-15 17:42:46,130 [salt.loaded.int.module.win_dsc:43  ][DEBUG   ][5118] DSC: Only available on Windows systems
2019-09-15 17:42:46,136 [salt.loaded.int.module.win_psget:36  ][DEBUG   ][5118] Module PSGet: Only available on Windows systems
2019-09-15 17:42:46,141 [salt.utils.lazy  :104 ][DEBUG   ][5118] LazyLoaded platform.is_windows
2019-09-15 17:42:46,161 [salt.utils.lazy  :107 ][DEBUG   ][5118] Could not LazyLoad pkg.ex_mod_init: 'pkg.ex_mod_init' is not available.
2019-09-15 17:42:46,161 [salt.state       :1819][INFO    ][5118] Running state [required_pkgs] at time 17:42:46.161816
2019-09-15 17:42:46,161 [salt.state       :1852][INFO    ][5118] Executing state pkg.latest for [required_pkgs]
2019-09-15 17:42:46,166 [salt.utils.lazy  :107 ][DEBUG   ][5118] Could not LazyLoad pkg.normalize_name: 'pkg.normalize_name' is not available.
2019-09-15 17:42:46,171 [salt.utils.lazy  :107 ][DEBUG   ][5118] Could not LazyLoad pkg.resolve_capabilities: 'pkg.resolve_capabilities' is not available.
2019-09-15 17:42:46,172 [salt.loaded.int.module.cmdmod:397 ][INFO    ][5118] Executing command [u'dpkg-query', u'--showformat', u'${Status} ${Package} ${Version} ${Architecture}', u'-W'] in directory '/home/dev'
2019-09-15 17:42:46,180 [salt.loaded.int.module.cmdmod:397 ][INFO    ][5118] Executing command [u'apt-get', u'-q', u'update'] in directory '/home/dev'
2019-09-15 17:42:46,205 [salt.loaded.int.module.cmdmod:826 ][ERROR   ][5118] Command '[u'apt-get', u'-q', u'update']' failed with return code: 100
2019-09-15 17:42:46,205 [salt.loaded.int.module.cmdmod:828 ][ERROR   ][5118] stdout: Reading package lists...
2019-09-15 17:42:46,205 [salt.loaded.int.module.cmdmod:830 ][ERROR   ][5118] stderr: W: chmod 0700 of directory /var/lib/apt/lists/partial failed - SetupAPTPartialDirectory (1: Operation not permitted)
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)
2019-09-15 17:42:46,205 [salt.loaded.int.module.cmdmod:832 ][ERROR   ][5118] retcode: 100
2019-09-15 17:42:46,206 [salt.state       :322 ][ERROR   ][5118] An error was encountered while checking the newest available version of package(s): W: chmod 0700 of directory /var/lib/apt/lists/partial failed - SetupAPTPartialDirectory (1: Operation not permitted)
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)
2019-09-15 17:42:46,206 [salt.state       :1997][INFO    ][5118] Completed state [required_pkgs] at time 17:42:46.206309 (duration_in_ms=44.493)
2019-09-15 17:42:46,206 [salt.utils.lazy  :104 ][DEBUG   ][5118] LazyLoaded locale.present
2019-09-15 17:42:46,207 [salt.state       :1819][INFO    ][5118] Running state [OS basic setup completed] at time 17:42:46.207543
2019-09-15 17:42:46,207 [salt.state       :1852][INFO    ][5118] Executing state test.show_notification for [OS basic setup completed]
2019-09-15 17:42:46,207 [salt.state       :320 ][INFO    ][5118] OS basic setup completed
2019-09-15 17:42:46,207 [salt.state       :1997][INFO    ][5118] Completed state [OS basic setup completed] at time 17:42:46.207950 (duration_in_ms=0.407)
2019-09-15 17:42:46,208 [salt.state       :1819][INFO    ][5118] Running state [openjdk-11-jdk] at time 17:42:46.208147
2019-09-15 17:42:46,208 [salt.state       :1852][INFO    ][5118] Executing state pkg.latest for [openjdk-11-jdk]
2019-09-15 17:42:46,213 [salt.utils.lazy  :107 ][DEBUG   ][5118] Could not LazyLoad pkg.normalize_name: 'pkg.normalize_name' is not available.
2019-09-15 17:42:46,218 [salt.utils.lazy  :107 ][DEBUG   ][5118] Could not LazyLoad pkg.resolve_capabilities: 'pkg.resolve_capabilities' is not available.
2019-09-15 17:42:46,219 [salt.loaded.int.module.cmdmod:397 ][INFO    ][5118] Executing command [u'apt-get', u'-q', u'update'] in directory '/home/dev'
2019-09-15 17:42:46,243 [salt.loaded.int.module.cmdmod:826 ][ERROR   ][5118] Command '[u'apt-get', u'-q', u'update']' failed with return code: 100
2019-09-15 17:42:46,243 [salt.loaded.int.module.cmdmod:828 ][ERROR   ][5118] stdout: Reading package lists...
2019-09-15 17:42:46,243 [salt.loaded.int.module.cmdmod:830 ][ERROR   ][5118] stderr: W: chmod 0700 of directory /var/lib/apt/lists/partial failed - SetupAPTPartialDirectory (1: Operation not permitted)
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)

```

I kind of feel that there is some bug

**Comment by max-arnold** [comment]
On a first glance, it looks like `minion.local` does allow passwordless `sudo` (or the `sudo` credentials are cached), and `minion.mgl` doesn't. `salt-ssh` does two things here:

1. It connects to a minion as `user: dev` via ssh (this is where ssh `passwd` OR key is used)
2. Then it wants a remote privileged account to run the states. It can achieve that by either connecting as `root` in the first step, or by using `sudo: true` (via `sudo_user: root` by default). I think it expects a NOPASSWD sudo access #8882 (the `passwd` option is only used in step (1)). With `sudo_user: dev` it doesn't need a password, but can't get enough privileges to run.

Also there is a `priv_passwd` option in Salt 2019.2.0, but it is only intended to specify a password for an ssh key.

To verify my guess, try the following commands:

```
ssh dev@minion.mgl
sudo
```

If the `sudo` command asks for a password, then you might want to add `NOPASSWD` for the `dev` user.

Also, I've seen a couple of problems with `salt-ssh` command itself, when it doesn't have sufficient permissions on a master machine (i.e. not run as root). That is fixable, although I do not remember what exact permission it needs.

**Comment by kiemlicz** [comment]
Thank you for awesome answer and sorry for late reply.
Yes, it was missing `NOPASSWD` setting, adding it resolves my issue  
Moreover it is stated in doc: https://docs.saltstack.com/en/latest/topics/ssh/#salt-ssh-roster

However, will salt-ssh always require `NOPASSWD`?

**Comment by max-arnold** [comment]
> However, will salt-ssh always require NOPASSWD?

I do not know. Maybe someone will improve salt-ssh and add this feature.
