### ISSUE TITLE
Proxy only working from command line, not deamon or service

### ISSUE THREAD

**Issue by adrianchi** [saltstack/salt#54691]
### Description of Issue
I've just installed salt and napalm, following the guidelines at:
[https://github.com/napalm-automation/napalm-salt](url)
[https://docs.saltstack.com/en/latest/topics/network_automation/index.html](url)
[https://mirceaulinic.net/2016-11-17-network-orchestration-with-salt-and-napalm/](url)

If i start the proxy process with the command line `"sudo salt-proxy --proxyid=r1 -l debug"` everything works just fine.
But, if i try to run it as a deamon with "`-d`" or `as a service` or `as beacon`, i go into a loop with this errors in the logs:

```
2019-09-19 14:28:18,659 [salt.minion:1041][CRITICAL][6789] Unexpected error while connecting to localhost
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1018, in _connect_minion
    yield minion.connect_master(failed=failed)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1216, in connect_master
    yield self._post_master_init(master)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 3420, in _post_master_init
    proxy_init_fn(self.opts)
  File "/usr/lib/python2.7/dist-packages/salt/proxy/napalm.py", line 206, in init
    NETWORK_DEVICE.update(salt.utils.napalm.get_device(opts))
  File "/usr/lib/python2.7/dist-packages/salt/utils/napalm.py", line 331, in get_device
    _driver_ = provider_lib.get_network_driver(network_device.get('DRIVER_NAME'))
  File "/usr/local/lib/python2.7/dist-packages/napalm_base/__init__.py", line 118, in get_network_driver
    install_name=module_install_name
ModuleImportError: Cannot import "napalm_ios". Is the library installed?
2019-09-19 14:28:18,888 [/usr/lib/python2.7/dist-packages/salt/utils/napalm.pyc     :239 ][ERROR   ][6789] Cannot execute "get_facts" on [unspecified hostname] as . Reason: not connected!
2019-09-19 14:28:18,889 [/usr/lib/python2.7/dist-packages/salt/utils/napalm.pyc     :240 ][ERROR   ][6789] Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/napalm.py", line 169, in call
    raise Exception('not connected')
Exception: not connected 
```

Napalm seems to work fine:

```
>>> from napalm_base import get_network_driver
>>> d = get_network_driver('ios')
>>> e = d('r1', 'cisco', 'cisco', optional_args={'config_lock': False})
>>> e.open()
>>> e.get_facts()
{u'os_version': u'3700 Software (C3725-ADVENTERPRISEK9-M), Version 12.4(15)T13, RELEASE SOFTWARE (fc3)', u'uptime': 5400, u'interface_list': [u'FastEthernet0/0', u'FastEthernet0/1', u'FastEthernet1/0', u'FastEthernet2/0'], u'vendor': u'Cisco', u'serial_number': u'FTX0945W0MY', u'model': u'3725', u'hostname': u'r1', u'fqdn': u'r1.quadrant.edu'}
>>> e.close()
```

### Setup

**top.sls**
```
base:
  'r1':
    - r1
```

**r1.sls**
```
proxy:
  proxytype: napalm
  driver: ios
  host: r1
  username: 'cisco'
  password: 'cisco'
  optional_args:
    use_keys: True
    auto_rollback_on_error: True
```

**/etc/systemd/system/salt-proxy@.service** 
```
[Unit]
Description=Salt proxy minion
After=network.target

[Service]
Type=simple
ExecStart=/usr/bin/salt-proxy --proxyid=%i -l debug
User=root
Group=root
Restart=always
RestartPreventExitStatus=SIGHUP
RestartSec=5

[Install]
WantedBy=default.target
adrian@adrian-VirtualBox:/srv/pillar$ 
```

**cat /etc/salt/proxy**
```
master: localhost
multiprocessing: false
mine_enabled: true # not required, but nice to have
pki_dir: /etc/salt/pki/proxy # not required - this separates the proxy keys into a different directory
```

**cat /etc/salt/minion**
`master: localhost`

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
**salt-proxy --version**
`salt-proxy 2019.2.0 (Fluorine)`

**salt --versions-report**
```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.12.3
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: 3.8.2
         pygit2: Not Installed
         Python: 2.7.15+ (default, Jul  9 2019, 16:51:35)
   python-gnupg: 0.4.1
         PyYAML: 5.1.2
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: LinuxMint 19.1 tessa
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-20-generic
         system: Linux
        version: LinuxMint 19.1 tessa
```
 
**salt-minion --version**
```
/usr/lib/python2.7/dist-packages/salt/scripts.py:198: DeprecationWarning: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date.  Salt will drop support for Python 2.7 in the Sodium release or later.
salt-minion 2019.2.0 (Fluorine)
```

**Comment by adrianchi** [comment]
After reinstalling napalm, i have a new error
salt.minion [CRITICAL][29957] Unexpected error while connecting to localhost, TypeError: connect() got an unexpected keyword argument 'passphrase'

Running on Ubuntu LinuxMint

Still not a clue why running the proxy command line it works, but not as a service or beacon

**Comment by adrianchi** [comment]
installing napalm 2.4 solved the issue.
thanks @mirceaulinic !
