### ISSUE TITLE
Regression in file.managed - Non-Ascii Files Not Found

### ISSUE THREAD

**Issue by Silvenga** [saltstack/salt#54719]
### Description of Issue

This system uses gitfs as the backend. These states that contained non-ascii characters worked on 18.X versions of Salt.

`file.managed` fails to find files with high UTF-8 characters (with a data transport is broken warning on the minion). The master logs the following:

```                                                  │
│   [ERROR   ] Error in function _serve_file:                                                                                                                      │
│   Traceback (most recent call last):                                                                                                                             │
│     File "/usr/lib/python3/dist-packages/salt/master.py", line 1838, in run_func                                                                                 │
│       ret = getattr(self, func)(load)                                                                                                                            │
│     File "/usr/lib/python3/dist-packages/salt/fileserver/__init__.py", line 650, in serve_file                                                                   │
│       return self.servers[fstr](load, fnd)                                                                                                                       │
│     File "/usr/lib/python3/dist-packages/salt/fileserver/gitfs.py", line 170, in serve_file                                                                      │
│       return _gitfs().serve_file(load, fnd)                                                                                                                      │
│     File "/usr/lib/python3/dist-packages/salt/utils/gitfs.py", line 2844, in serve_file                                                                          │
│       data = data.decode(__salt_system_encoding__)                                                                                                               │
│   UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 31459: ordinal not in range(128)
```

### Setup

files/telegraf-linux.conf
```
  # Precision of writes, valid values are "ns", "us" (or "µs"), "ms", "s", "m", "h".
```

linux.sls
```
Ensure the Telegraf configuration file exists:
  file.managed:
    - name: /etc/telegraf/telegraf.conf
    - source: salt://{{ tpldir }}/files/telegraf-linux.conf
    - template: jinja
```

```
salt-call apply linux
```

### Steps to Reproduce Issue

In this example, changing `µ` to `u` allows the minion to "locate" the file.

### Versions Report

Using the python 3 version.

```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.26.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.2
         Python: 3.6.8 (default, Jan 14 2019, 11:02:34)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.15.0-54-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```

**Comment by cmcmarrow** [comment]
It works in 2019.2.1 for me

**Comment by cmcmarrow** [comment]
I can not reproduce in 2019.2 I put 'µ' in every file path I could think and in the file I moved.

**Comment by cmcmarrow** [comment]
Can you share your config files?

**Comment by Silvenga** [comment]
My config as follows:

```
# master.config

fileserver_backend:
    - git
gitfs_remotes:
  - git@salt.git:
    - name: states
    - root: salt
    - pubkey: /etc/salt/id_rsa.pub
    - privkey: /etc/salt/id_rsa
ext_pillar:
  - git:
    - master git@salt.git:
        - root: pillar
        - pubkey: /etc/salt/id_rsa.pub
        - privkey: /etc/salt/id_rsa
```

```
# init.sh

#!/bin/bash

echo "Starting salt-api, if there are no configurations, salt-api will exit."
salt-api -d
echo "Starting salt-master."
salt-master --log-level=info
```

```
# Dockerfile
FROM ubuntu:18.04

RUN set -xe \
  && DEBIAN_FRONTEND=noninteractive apt-get update -q \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y wget gnupg \
  && wget -O - https://repo.saltstack.com/py3/ubuntu/18.04/amd64/2019.2/SALTSTACK-GPG-KEY.pub | apt-key add - \
  && echo "deb http://repo.saltstack.com/py3/ubuntu/18.04/amd64/2019.2 bionic main" > /etc/apt/sources.list.d/saltstack.list \
  && DEBIAN_FRONTEND=noninteractive apt-get update -q \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y \
  salt-master=2019.2.0+ds-1 \
  salt-api=2019.2.0+ds-1 \
  python3-pygit2 \
  virt-what \
  python3-psycopg2 \
  gnupg2 \
  && rm -r /var/lib/apt/lists/*

COPY rootfs/ /

EXPOSE 4505
EXPOSE 4506

VOLUME [ "/etc/salt/pki", "/var/cache/salt", "/var/log/salt", "/var/run/salt" ]

CMD [ "/bin/bash", "/init.sh" ]
```

The config file, before and after the changes.
https://gist.github.com/Silvenga/650012ce00d6cfe56f2a9b9261d2ba5c

I'll definitely try upgrading to 2019.2.1.

**Comment by Silvenga** [comment]
The issue is not present in 2019.2.1.
