### ISSUE TITLE
Unable to use pkg.install with 'sources' parameter in Ubuntu on some deb files

### ISSUE THREAD

**Issue by lomeroe** [saltstack/salt#54739]
### Description of Issue
Unable to install some deb packages through pkg.install using the 'sources' parameter.

the dpkg_lowpkg module attempts to use 'startswith' to find the information from the output of `dpkg -I ...`

dpkg -I <path/to/deb> returns info with spaces on some packages (McAfee Agent Packages in my case):

```
package.deb
 new Debian package, version 2.0.
 size 1333890 bytes: control archive=1142 bytes.
     260 bytes,     9 lines      control
    1788 bytes,    61 lines   *  postinst             #!/bin/sh
     342 bytes,    18 lines   *  postrm               #!/bin/sh
     401 bytes,    20 lines   *  preinst              #!/bin/sh
     588 bytes,    28 lines   *  prerm                #!/bin/sh
 Package        : <package_name>
 Version        : <version_number>
 Maintainer     : <maintainer>
 Description    : <description>
 Release        : <release_number>
 Architecture   : <arch>
 Section        : <section info>
 Summary        : <summary>
 Pre-Depends    : <depends>
```

The spaces mess up the 'startswith' which uses the 'Architecture:', 'Package:', etc..

### Setup
salt-call pkg.install sources="[{'pkgname':'/path/to/install.deb'}]"

### Steps to Reproduce Issue
salt-call pkg.install sources="[{'pkgname':'/path/to/install.deb'}]"
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 237, in call
    ret['return'] = self.minion.executors[fname](self.opts, data, func, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/aptpkg.py", line 618, in install
    deb_info = __salt__['lowpkg.bin_pkg_info'](pkg_source)
  File "/usr/lib/python2.7/dist-packages/salt/modules/dpkg.py", line 106, in bin_pkg_info
    'Unable to get {0} for {1}'.format(', '.join(missing), path)
CommandExecutionError: Unable to get arch for /var/cache/salt/minion/files/base/install.deb
Error running 'pkg.install': Unable to get arch for /var/cache/salt/minion/files/base/install.deb
```

### Versions Report
```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15+ (default, Jul  9 2019, 16:51:35)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-1044-aws
         system: Linux
        version: Ubuntu 18.04 bionic
```

**Comment by xeacott** [comment]
Thanks for reporting and addressing the issue!

**Comment by lomeroe** [comment]
awaiting PR commit
