### ISSUE TITLE
2019.2.1: Breaks salt-cloud openstack --query

### ISSUE THREAD

**Issue by vdloo** [saltstack/salt#54760]
previous behavior:
```
$ salt --version
saltsalt 2019.2.0 (Fluorine)

$ salt-cloud -Q
aws:
    ----------
    ec2:
        ----------
        testing-...-DEL...:
            ----------
            id:
                i-...
            image:
                ami-...
            name:
                testing-...
            private_ips:
            public_ips:
            size:
                t2.medium
            state:
                terminated
cos:
    ----------
    openstack:
        ----------
        some-node:
            ----------
            fixed_ips:
                - ...
            floating_ips:
            id:
                ...
            image:
                debian-buster-amd64
            name:
                some-node
            private_ips:
            public_ips:
                - ...
            size:
                m1.medium
            state:
                ACTIVE
```

behavior after upgrading to 2019.2.1:
```
$ salt --version
salt 2019.2.1 (Fluorine)

$ salt-cloud -Q
[ERROR   ] Exception raised when processing __virtual__ function for salt.loaded.int.clouds.openstack. Module will not be loaded: 'module' object is not subscriptable
[WARNING ] salt.loaded.int.clouds.openstack.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'openstack', please fix this.
[WARNING ] The cloud driver, 'openstack', configured under the 'cos' cloud provider alias, could not be loaded. Please check your provider configuration files and ensure all required dependencies are installed for the 'openstack' driver.
In rare cases, this could indicate the 'openstack.get_configured_provider()' function could not be found.
Removing 'openstack' from the available providers list
aws:
    ----------
    ec2:
        ----------
        testing-...-DEL...:
            ----------
            id:
                i-...
            image:
                ami-...
            name:
                testing-...
            private_ips:
            public_ips:
            size:
                t2.medium
            state:
                terminated
```

Running on:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

$ python --version
Python 3.5.2
```

with debug:
```
[INFO    ] salt-cloud starting
[ERROR   ] Exception raised when processing __virtual__ function for salt.loaded.int.clouds.openstack. Module will not be loaded: 'module' object is not subscriptable
Traceback (most recent call last):
  File "/usr/local/venv/saltyparrot1/lib/python3.5/site-packages/salt/loader.py", line 1843, in _process_virtual
    virtual = getattr(mod, virtual_func)()
  File "/usr/local/venv/saltyparrot1/lib/python3.5/site-packages/salt/cloud/clouds/openstack.py", line 254, in __virtual__
    if get_dependencies() is False:
  File "/usr/local/venv/saltyparrot1/lib/python3.5/site-packages/salt/cloud/clouds/openstack.py", line 283, in get_dependencies
    'shade': shade[0],
TypeError: 'module' object is not subscriptable
[WARNING ] salt.loaded.int.clouds.openstack.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'openstack', please fix this.
```
tested with both shade==1.31.0 and the currently latest shade==1.32.0

sounds related to https://github.com/saltstack/salt/pull/53734 and https://github.com/saltstack/salt/issues/53012

**Comment by cmcmarrow** [comment]
thanks for telling us

**Comment by sagetherage** [comment]
closing as fixed
