### ISSUE TITLE
2019.2.1: Can't load modules: Module sys has no attribute 'modules' (os.path)

### ISSUE THREAD

**Issue by kyentei** [saltstack/salt#54766]
### Description of Issue
On a `state.highstate`, the `salt-minion` can't seem to load any of the sys modules, throwing an `AttributeError: module 'sys' has no attribute 'modules'` error. They all seem to break on `os.path`.

```
AttributeError: module 'sys' has no attribute 'modules'
2019-09-26 13:30:24,975 [salt.loader      :1584][ERROR   ][16616] Failed to import utils win_lgpo_auditpol, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1560, in _load_module
    mod = spec.loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/salt/utils/win_lgpo_auditpol.py", line 64, in <module>
    import logging
  File "/usr/lib/python3.6/logging/__init__.py", line 26, in <module>
    import sys, os, time, io, traceback, warnings, weakref, collections
  File "/usr/lib/python3.6/os.py", line 91, in <module>
    sys.modules['os.path'] = path
AttributeError: module 'sys' has no attribute 'modules'
2019-09-26 13:30:24,978 [salt.loader      :1584][ERROR   ][16616] Failed to import utils win_lgpo_netsh, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1560, in _load_module
    mod = spec.loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/salt/utils/win_lgpo_netsh.py", line 72, in <module>
    import logging
  File "/usr/lib/python3.6/logging/__init__.py", line 26, in <module>
    import sys, os, time, io, traceback, warnings, weakref, collections
  File "/usr/lib/python3.6/os.py", line 91, in <module>
    sys.modules['os.path'] = path
```

```
AttributeError: module 'sys' has no attribute 'stdin'                                       
[ERROR   ] Failed to import states win_system, this is due most likely to a syntax error:  
Traceback (most recent call last):                                                                         
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1560, in _load_module                              
    mod = spec.loader.load_module()                                                                             
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper             
  File "<frozen importlib._bootstrap_external>", line 823, in load_module                      
  File "<frozen importlib._bootstrap_external>", line 682, in load_module                                       
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim                                          
  File "<frozen importlib._bootstrap>", line 684, in _load                                                      
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked                     
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module                         
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                             
  File "/usr/lib/python3/dist-packages/salt/states/win_system.py", line 22, in <module>                         
    import logging                                                                    
  File "/usr/lib/python3.6/logging/__init__.py", line 26, in <module>                      
    import sys, os, time, io, traceback, warnings, weakref, collections              
  File "/usr/lib/python3.6/os.py", line 91, in <module>                                                         
    sys.modules['os.path'] = path
```

### Setup
No specific configuration

### Steps to Reproduce Issue
Have a salt minion and salt master on 2019.2.1, using Ubuntu 18.04

### Versions Report
```
Salt Version:
           Salt: 2019.2.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.26.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.2
         Python: 3.6.8 (default, Aug 20 2019, 17:12:48)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 5.0.0-29-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```

**Comment by kyentei** [comment]
Apparently, since 2019.2.1, there's a hard dependency on having `python3-pip` installed on Ubuntu.
