### ISSUE TITLE
2019.2.1: errors in jinja|yaml renderer on Ubuntu 18.04

### ISSUE THREAD

**Issue by kyentei** [saltstack/salt#54764]
### Description of Issue
Since the upgrade to `2019.2.1`, all Ubuntu 18.04 minions are reporting the following:

```
2019-09-26 10:20:02,078 [salt.template    :236 ][ERROR   ][9167] The renderer "jinja|yaml" is not available
2019-09-26 10:20:02,079 [salt.loader      :650 ][CRITICAL][9167] The renderer jinja|yaml is unavailable, this error is often because the needed software is unavailable
2019-09-26 10:20:02,079 [salt.utils.schedule:791 ][ERROR   ][9167] Unhandled exception running state.highstate
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/schedule.py", line 759, in handle_func
  File "/usr/lib/python3/dist-packages/salt/modules/state.py", line 1083, in highstate
  File "/usr/lib/python3/dist-packages/salt/state.py", line 3968, in call_highstate
  File "/usr/lib/python3/dist-packages/salt/state.py", line 2789, in call_high
  File "/usr/lib/python3/dist-packages/salt/state.py", line 2151, in call_chunks
  File "/usr/lib/python3/dist-packages/salt/state.py", line 2596, in call_chunk
  File "/usr/lib/python3/dist-packages/salt/utils/decorators/state.py", line 30, in _func
  File "/usr/lib/python3/dist-packages/salt/state.py", line 1981, in call
  File "/usr/lib/python3/dist-packages/salt/state.py", line 1055, in check_refresh
  File "/usr/lib/python3/dist-packages/salt/state.py", line 1011, in module_refresh
  File "/usr/lib/python3/dist-packages/salt/state.py", line 994, in load_modules
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 651, in render
salt.exceptions.LoaderError: The renderer jinja|yaml is unavailable, this error is often because the needed software is unavailable
```

### Setup
No special configuration entries have been configured.

### Steps to Reproduce Issue
1) Have Ubuntu 18.04
2) Upgrade minions and master to `2019.2.1`

### Versions Report
Minion:

```
Salt Version:
           Salt: 2019.2.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Aug 20 2019, 17:12:48)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 5.0.0-27-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```

Master: 

```
Salt Version:
           Salt: 2019.2.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 8.9.1
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.26.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.2
         Python: 3.6.8 (default, Aug 20 2019, 17:12:48)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 5.0.0-29-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```

**Comment by kyentei** [comment]
This was most likely caused by `salt-minion` and `salt-common` having a new dependency on `ifupdown` and `resolvconf`, which were removed in a salt-state. Therefore, the `salt-minion` and `salt-common` packages were removed mid-run. Not removing `ifupdown` and `resolvconf` seems to have resolved this issue.
