### ISSUE TITLE
postgres_local_cache causing 'IntegrityError: duplicate key value violates unique constraint "jids_pkey"'

### ISSUE THREAD

**Issue by breshead** [saltstack/salt#54787]
### Description of Issue
When using postgres master_job_cache, running any state fails with the following message.
~~~
2019-09-26 18:06:05,733 [salt.master      :1845][ERROR   ][19716] Error in function _return:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 1838, in run_func
    ret = getattr(self, func)(load)
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 1637, in _return
    self.opts, load, event=self.event, mminion=self.mminion)
  File "/usr/lib/python2.7/dist-packages/salt/utils/job.py", line 109, in store_job
    mminion.returners[savefstr](load['jid'], load)
  File "/usr/lib/python2.7/dist-packages/salt/returners/postgres_local_cache.py", line 303, in save_load
    six.text_type(clear_load.get("fun")),
IntegrityError: duplicate key value violates unique constraint "jids_pkey"
DETAIL:  Key (jid)=(20190926180501069881) already exists.
~~~

### Setup
https://docs.saltstack.com/en/latest/ref/returners/all/salt.returners.postgres_local_cache.html

### Steps to Reproduce Issue
Just run any state

### Versions Report
~~~
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Nov 13 2018, 12:45:42)
   python-gnupg: 0.3.6
         PyYAML: 3.10
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
         locale: UTF-8
        machine: x86_64
        release: 3.13.0-74-generic
         system: Linux
        version: Ubuntu 14.04 trusty
~~~

### Possible Source
In utils/job.py, I changed the `if job_cache != 'local_cache'` to also check for `postgres_local_cache` and the errors went away and I was getting the return data I was looking for. However that feels like the wrong thing to do but maybe it gets us closer the the real source.
~~~
106     if job_cache != 'local_cache' and job_cache != 'postgres_local_cache':
107         try:
108             log.error("job_cache != 'local_cache' (%s)", job_cache)
109             mminion.returners[savefstr](load['jid'], load)
110         except KeyError as e:
111             log.error("Load does not contain 'jid': %s", e)
~~~

**Comment by dwoz** [comment]
Duplicate of #69214, fixed by #69322 (merged into 3006.x and propagated to 3007.x/3008.x/master). `save_load` now uses `INSERT ... ON CONFLICT (jid) DO NOTHING` so concurrent masters (or any retried write) no longer trip `jids_pkey`.
