### ISSUE TITLE
DummyFuture does not support blocking for results - cherryPy - local.cmd

### ISSUE THREAD

**Issue by saltpicker** [saltstack/salt#54788]
Basicaly i'm using cherryPy to execute simple commands for my needs, example:

`uptimeOut = local.cmd(hostMinion, 'cmd.run', ['uptime | xargs'])`

Nothing special at all.
Now when i call it on minion which is offline and one which is online at the same time i'm getting this:
```
Sep 27 09:37:45 saltmaster nice[9540]: 127.0.0.1 - - [27/Sep/2019:09:37:45] "GET /gets/uptime/lx00031.pl.ing-ad HTTP/1.1" 500 823 "" "curl/7.29.0"
Sep 27 09:37:45 saltmaster nice[9540]: [27/Sep/2019:09:37:45] HTTP
Sep 27 09:37:45 saltmaster nice[9540]: Traceback (most recent call last):
Sep 27 09:37:45 saltmaster nice[9540]: File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 670, in respond
Sep 27 09:37:45 saltmaster nice[9540]: response.body = self.handler()
Sep 27 09:37:45 saltmaster nice[9540]: File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
Sep 27 09:37:45 saltmaster nice[9540]: self.body = self.oldhandler(*args, **kwargs)
Sep 27 09:37:45 saltmaster nice[9540]: File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
Sep 27 09:37:45 saltmaster nice[9540]: return self.callable(*self.args, **self.kwargs)
Sep 27 09:37:45 saltmaster nice[9540]: File "/opt/pepper/engine/microapi/microapi.py", line 177, in GET
Sep 27 09:37:45 saltmaster nice[9540]: uptimeOut = local.cmd(hostMinion, 'cmd.run', ['uptime | xargs'])
Sep 27 09:37:45 saltmaster nice[9540]: File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 715, in cmd
Sep 27 09:37:45 saltmaster nice[9540]: **kwargs):
Sep 27 09:37:45 saltmaster nice[9540]: File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 1527, in get_cli_event_returns
Sep 27 09:37:45 saltmaster nice[9540]: **kwargs
Sep 27 09:37:45 saltmaster nice[9540]: File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 1104, in get_iter_returns
Sep 27 09:37:45 saltmaster nice[9540]: for raw in ret_iter:
Sep 27 09:37:45 saltmaster nice[9540]: File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 1038, in get_returns_no_block
Sep 27 09:37:45 saltmaster nice[9540]: no_block=True, auto_reconnect=self.auto_reconnect)
Sep 27 09:37:45 saltmaster nice[9540]: File "/usr/lib/python2.7/site-packages/salt/utils/event.py", line 652, in get_event
Sep 27 09:37:45 saltmaster nice[9540]: ret = self._get_event(wait, tag, match_func, no_block)
Sep 27 09:37:45 saltmaster nice[9540]: File "/usr/lib/python2.7/site-packages/salt/utils/event.py", line 551, in _get_event
Sep 27 09:37:45 saltmaster nice[9540]: raw = self.subscriber.read_sync(timeout=wait)
Sep 27 09:37:45 saltmaster nice[9540]: File "/usr/lib/python2.7/site-packages/salt/transport/ipc.py", line 752, in read_sync
Sep 27 09:37:45 saltmaster nice[9540]: return ret_future.result()
Sep 27 09:37:45 saltmaster nice[9540]: File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 215, in result
Sep 27 09:37:45 saltmaster nice[9540]: self._check_done()
Sep 27 09:37:45 saltmaster nice[9540]: File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 293, in _check_done
Sep 27 09:37:45 saltmaster nice[9540]: raise Exception("DummyFuture does not support blocking for results")
Sep 27 09:37:45 saltmaster nice[9540]: Exception: DummyFuture does not support blocking for results
```

When i'm calling it on online minions,  all works OK.

Second problematic issue is here, please look at it: https://github.com/saltstack/salt/issues/54021

Current RHEL7
salt-minion-2019.2.0-1.el7.noarch
salt-2019.2.0-1.el7.noarch
salt-master-2019.2.0-1.el7.noarch
python-cherrypy-5.6.0-2.el7.noarch

Thanks

**Comment by cmcmarrow** [comment]
https://github.com/saltstack/salt/issues/26884
