### ISSUE TITLE
No beacon data

### ISSUE THREAD

**Issue by nkrishnakishor** [saltstack/salt#54816]
### Description of Issue

No beacon data is being displayed from minions

### Setup
```cat /srv/pillar/beacon.sls``` as below
```
monitor-disk:
  beacons:
    diskusage:
      - interval: 1
#     - 'c:\\': 5%
      - /: 9%
      - disable_during_state_run: True
```

```cat /srv/pillar/top.sls``` as below
```
base:
  '*':
    - pass
  'test1*':
  'test2*':
    - disk.beacon
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
Updated pillar data across the minions but it beacons data is not reflecting from minions.
```
salt '*' saltutil.refresh_pillar
system1
		True
system2
		True

 salt 'system1*' beacons.list
system1
    ----------
    beacons:
        ----------
```

### Versions Report
`salt --versions-report`
```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Feb 20 2019, 09:59:36)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.10 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-754.18.2.el6.x86_64
         system: Linux
        version: CentOS 6.10 Final
```

**Comment by garethgreenaway** [comment]
@nkrishnakishor If you update your beacon data stored in pillar to the following you'll get the beacon events:
```

**Comment by nkrishnakishor** [comment]
@garethgreenaway thanks for the reply. I have updated beacon file accordingly but didn't payoff.

```
beacons:
  diskusage:
    - interval: 1
#     - 'c:\\':  5%
    - /:  9%
    - disable_during_state_run: True
```

After making changes on beacons file, i have refreshed pillar data but no use. Even i have restarted salt master service also but no use.

**Do we really need to restart salt master service post any beacon file changes or any pillar data changes ?**

**Comment by lukasraska** [comment]
@nkrishnakishor You don't need to restart salt-master when any pillar files change. Beacons are executed on minions, so you only need to trigger pillar refresh.

The beacons pillar look okay now, but checking provided top.sls, you're referencing wrong file there. Try this top.sls (if your beacon pillar file is /srv/pillar/beacon.sls -> you're referencing sls file in top.sls, not the actual key present in those files). 

```
base:
  '*':
    - pass
  'test1*':
  'test2*':
    - beacon
```

Once you change this, `saltutil.refresh_pillar` should refresh it (and it should work).

**Comment by nkrishnakishor** [comment]
Thanks @lukasraska for the reply. I was able to get desired results after changing as per your suggestion.

But i'm unable to see beacons data for windows minons with beacon file as below.

```
beacons:
  diskusage:
    - interval: 1
#     - 'c:\\':  5%
    - /:  9%
    - disable_during_state_run: True
```

Can you please help me in this regard ?

**Comment by lukasraska** [comment]
Looking at the source code (https://github.com/saltstack/salt/blob/develop/salt/beacons/diskusage.py#L108) , you will probably need to uncomment the `c:\\` option -> you need to specify all partitions to be "monitored", otherwise the beacon won't return any data.

So try this:
```
beacons:
  diskusage:
    - interval: 1
    - 'c:\\':  5%
    - /:  9%
    - disable_during_state_run: True
```

**Comment by nkrishnakishor** [comment]
@lukasraska by mistake i have left the copied code from above as it is but on master i have commented out the line containing ```C:\``` but it did not return anything.

Tried both the notations mentioned in the source code as below beacon file.

```
beacons:
  diskusage:
    - interval: 1
    - 'C:\\': 5%
    - 'D:\\$': 57%
#   - /: 9%
    - disable_during_state_run: True
```
Refreshed pillar data of the minion ```# salt *windows* saltutil.refresh_pillar```

```
windows-minion:
    True
```
Tried to list out beacon data ```# salt *windows* beacons.list```

```
windows-minion:
    ----------
    beacons:
        ----------
```

**Comment by lukasraska** [comment]
Did you include this windows minion in pillar top.sls? You need to explicitly state which miniona should have access to which states

**Comment by nkrishnakishor** [comment]
Thanks @lukasraska you're right i have missed it in pillar top file. I have modified the content and now able to see beacon data for windows and Linux minions.

But there are no events triggered from Windows minion even after ```C drive``` is meeting the criteria but from Linux minions i'm able to receive events on master after running ```salt-run state.event pretty=true```

```
windows-minion:
    beacons:
      diskusage:
      - interval: 1
      - C:\\: 5%
      - D:\\$: 57%
      - /: 50%
      - disable_during_state_run: true
```

Can you guide me on this ?

**Comment by lukasraska** [comment]
Hi,
it works for me.

This is my pillar top.sls.
```
base:
  '*':
    - beacon
```

This is the beacon.sls file:
```
beacons:
  diskusage:
    - interval: 1
    - C:\\: 5%
    - D:\\$: 57%
    - /: 50%
    - disable_during_state_run: true
```

This is the `pillar.get beacons` output:
```
# salt 'my-win-minion' pillar.get beacons
my-win-minion:
    ----------
    diskusage:
        |_
          ----------
          interval:
              1
        |_
          ----------
          C:\\:
              5%
        |_
          ----------
          D:\\$:
              57%
        |_
          ----------
          /:
              50%
        |_
          ----------
          disable_during_state_run:
```

This is the `salt-run state.event pretty=true` output:
```
salt/beacon/my-win-minion/diskusage/	{
    "_stamp": "2019-10-04T17:08:24.515607",
    "diskusage": 16.6,
    "id": "my-win-minion",
    "mount": "C:\\\\"
}
```


Don't always forget to run `saltutil.refresh_pillar` after the change of any pillar data.

**Comment by nkrishnakishor** [comment]
@lukasraska thanks for the reply. I'm able to see everything pillar data, beacons information on the minion but there are no events on the master bus for the criteria defined.

Can you help me in this regard and resolve ?

**Comment by nkrishnakishor** [comment]
Do we need to have any package installed on master for beacon to work on Windows ?

**Comment by lukasraska** [comment]
@nkrishnakishor You don't usually need any specific package for beacons to work on Windows. That said, you can create custom beacons that require those packages, but the diskusage beacon worked for me without any modifications.

Can you show your pillar top.sls file, beacon.sls file and output from `salt *windows* beacons.list` and `salt *windows* pillar.items`?

Other debugging options is to run salt-minion with detailed logging (which then shows how the beacons are processed there).

**Comment by nkrishnakishor** [comment]
Thank you @lukasraska for the reply, below are the details of the files ```pillar top.sls file, beacon.sls``` and output of ```salt *windows* beacons.list``` and ```salt *windows* pillar.items```

```
cat /srv/pillar/top.sls | grep -v "#" | grep -v '^$'
base:
  '*':
    - pass
    - secret
    - beacon

 cat /srv/pillar/beacon.sls | grep -v "#" | grep -v '^$'
beacons:
  diskusage:
    - 'c:\\': 5%
    - interval: 1
    - /: 50%
    - disable_during_state_run: True
```

```
salt *windows* beacons.list
windows-minion:
    beacons:
      diskusage:
      - c:\\: 5%
      - interval: 1
      - /: 50%
      - disable_during_state_run: true
```

```
salt *windows* pillar.items
windows-minion:
    ----------
    a-secret:
        secret
    beacons:
        ----------
        diskusage:
            |_
              ----------
              c:\\:
                  5%
            |_
              ----------
              interval:
                  1
            |_
              ----------
              /:
                  50%
            |_
              ----------
              disable_during_state_run:
                  True
    testpass:
        dummy
```

I have tried to run ```salt-minion-debug``` on the windows minion and able to capture below log, please check if this can be any helpful.

```
[CRITICAL] The beacon errored:
Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 2592, in handle_beac
ons
    beacons = self.process_beacons(self.functions)
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 449, in process_beac
ons
    return self.beacons.process(b_conf, self.opts['grains'])  # pylint: disable=
no-member
  File "C:\salt\bin\lib\site-packages\salt\beacons\__init__.py", line 112, in pr
ocess
    raw = self.beacons[fun_str](b_config[mod])
  File "C:\salt\bin\lib\site-packages\salt\beacons\diskusage.py", line 103, in b
eacon
    if re.match(mount_re, part.mountpoint):
  File "C:\salt\bin\lib\re.py", line 141, in match
    return _compile(pattern, flags).match(string)
  File "C:\salt\bin\lib\re.py", line 251, in _compile
    raise error, v # invalid expression
error: bogus escape (end of line)
[CRITICAL] The beacon errored:
Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 2592, in handle_beac
ons
    beacons = self.process_beacons(self.functions)
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 449, in process_beac
ons
    return self.beacons.process(b_conf, self.opts['grains'])  # pylint: disable=
no-member
  File "C:\salt\bin\lib\site-packages\salt\beacons\__init__.py", line 112, in pr
ocess
    raw = self.beacons[fun_str](b_config[mod])
  File "C:\salt\bin\lib\site-packages\salt\beacons\diskusage.py", line 103, in b
eacon
    if re.match(mount_re, part.mountpoint):
  File "C:\salt\bin\lib\re.py", line 141, in match
    return _compile(pattern, flags).match(string)
  File "C:\salt\bin\lib\re.py", line 251, in _compile
    raise error, v # invalid expression
error: bogus escape (end of line)
[CRITICAL] The beacon errored:
Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 2592, in handle_beac
ons
    beacons = self.process_beacons(self.functions)
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 449, in process_beac
ons
    return self.beacons.process(b_conf, self.opts['grains'])  # pylint: disable=
no-member
  File "C:\salt\bin\lib\site-packages\salt\beacons\__init__.py", line 112, in pr
ocess
    raw = self.beacons[fun_str](b_config[mod])
  File "C:\salt\bin\lib\site-packages\salt\beacons\diskusage.py", line 103, in b
eacon
    if re.match(mount_re, part.mountpoint):
  File "C:\salt\bin\lib\re.py", line 141, in match
    return _compile(pattern, flags).match(string)
  File "C:\salt\bin\lib\re.py", line 251, in _compile
    raise error, v # invalid expression
error: bogus escape (end of line)
[CRITICAL] The beacon errored:
Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 2592, in handle_beac
ons
    beacons = self.process_beacons(self.functions)
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 449, in process_beac
ons
    return self.beacons.process(b_conf, self.opts['grains'])  # pylint: disable=
no-member
  File "C:\salt\bin\lib\site-packages\salt\beacons\__init__.py", line 112, in pr
ocess
    raw = self.beacons[fun_str](b_config[mod])
  File "C:\salt\bin\lib\site-packages\salt\beacons\diskusage.py", line 103, in b
eacon
    if re.match(mount_re, part.mountpoint):
  File "C:\salt\bin\lib\re.py", line 141, in match
    return _compile(pattern, flags).match(string)
  File "C:\salt\bin\lib\re.py", line 251, in _compile
    raise error, v # invalid expression
error: bogus escape (end of line)
```
