### ISSUE TITLE
[centos] FileNotFoundError: [Errno 2] No such file or directory: 'userdel': 'userdel'

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#54850]
### Description of Issue

Failing to do a `user.absent`

### Setup

Using https://github.com/saltstack-formulas/users-formula (which uses `user.absent`) I get : 

### Steps to Reproduce Issue

```
                 ID: users_absent_user_admin
           Function: user.absent
               Name: admin
             Result: False
            Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3.6/site-packages/salt/modules/cmdmod.py", line 650, in _run
                  proc = salt.utils.timed_subprocess.TimedProc(cmd, **new_kwargs)
                File "/usr/lib/python3.6/site-packages/salt/utils/timed_subprocess.py", line 49, in __init__
                  self.process = subprocess.Popen(args, **kwargs)
                File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
                  restore_signals, start_new_session)
                File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
                  raise child_exception_type(errno_num, err_msg, err_filename)
              FileNotFoundError: [Errno 2] No such file or directory: 'userdel': 'userdel'
              
              During handling of the above exception, another exception occurred:
              
              Traceback (most recent call last):
                File "/usr/lib/python3.6/site-packages/salt/state.py", line 1933, in call
                  **cdata['kwargs'])
                File "/usr/lib/python3.6/site-packages/salt/loader.py", line 1939, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/states/user.py", line 896, in absent
                  ret['result'] = __salt__['user.delete'](name, purge, force)
                File "/usr/lib/python3.6/site-packages/salt/modules/useradd.py", line 271, in delete
                  ret = __salt__['cmd.run_all'](cmd, python_shell=False)
                File "/usr/lib/python3.6/site-packages/salt/modules/cmdmod.py", line 2069, in run_all
                  **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/modules/cmdmod.py", line 669, in _run
                  raise CommandExecutionError(msg)
              salt.exceptions.CommandExecutionError: Unable to run command '['userdel', '-r', '-f', 'admin']' with the context '{'cwd': '/home/vagrant', 'shell': False, 'env': 'with_communicate': True, 'timeout': None, 'bg': False, 'close_fds': True}', reason: [Errno 2] No such file or directory: 'userdel': 'userdel': userdel
```

### Versions Report
Versions 

```
[vagrant@default-centos-7 ~]$ sudo salt-call test.versions_report
local:
    Salt Version:
               Salt: 2019.2.0
     
    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: Not Installed
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.8.1
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: 0.33.0
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.5.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 3.6.8 (default, Aug  7 2019, 17:28:10)
       python-gnupg: Not Installed
             PyYAML: 3.12
              PyZMQ: 15.3.0
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.4.2
                ZMQ: 4.1.4
     
    System Versions:
               dist: centos 7.4.1708 Core
             locale: UTF-8
            machine: x86_64
            release: 3.10.0-693.21.1.el7.x86_64
             system: Linux
            version: CentOS Linux 7.4.1708 Core
```

**Comment by lukasraska** [comment]
@arthurlogilab Seems like you don't have command `userdel` available on your system. Can you check if you have package `shadow-utils` installed? If not, can you install it and try again?

**Comment by arthurlogilab** [comment]
I do have `userdel` installed. For some obscure reason it might be a shell/path problem ?

**Comment by lukasraska** [comment]
Yes, might be. What does `salt-call environ.get PATH` return for you? 

Mine shows this
```
# salt-call environ.get PATH
local:
    /usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
```

The userdel command is usually stored in /usr/sbin, which is only available to root user. Is there any chance your minion process is running under different user?
