### ISSUE TITLE
salt-cloud raises `ResourceNotFoundError: Node '{node_name}' not found in any zone.`

### ISSUE THREAD

**Issue by zentrung** [saltstack/salt#54865]
### Description of Issue
We're using Google Cloud. When we have ~700 compute instances, our salt-cloud - which used to work fine - don't want to launch new instance anymore.
### Setup
I don't think the setup or states are relevant here.

### Steps to Reproduce Issue
Please find the debug log below

```
root@salt-1:/opt/salt-repo# salt-cloud -p {node_profile} {node_name} -l debug
[DEBUG   ] Reading configuration from /etc/salt/cloud
[DEBUG   ] Reading configuration from /etc/salt/master
...
[DEBUG   ] Starting new HTTPS connection (1): www.googleapis.com
[DEBUG   ] https://www.googleapis.com:443 "GET /compute/v1/projects/{project_id}/zones HTTP/1.1" 200 None
[DEBUG   ] https://www.googleapis.com:443 "GET /compute/v1/projects/{project_id}/regions HTTP/1.1" 200 None
[DEBUG   ] https://www.googleapis.com:443 "GET /compute/v1/projects/{project_id}/aggregated/instances HTTP/1.1" 200 None
[ERROR   ] There was a profile error: u"Node '{node_name}' not found in any zone."
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 279, in run
    self.config.get('names')
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1432, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1253, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/gce.py", line 2579, in create
    node_info = request_instance(vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/gce.py", line 2565, in request_instance
    node_dict = show_instance(node_data.name, 'action')
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/gce.py", line 307, in show_instance
    node = _expand_node(conn.ex_get_node(vm_name))
  File "/usr/lib/python2.7/dist-packages/libcloud/compute/drivers/gce.py", line 7030, in ex_get_node
    name, 'instances', res_name='Node')
  File "/usr/lib/python2.7/dist-packages/libcloud/compute/drivers/gce.py", line 7561, in _find_zone_or_region
    (res_name, name, rz), None, None)
ResourceNotFoundError: u"Node '{node_name}'' not found in any zone."
```

According to the documentation of [Google Compute API](https://cloud.google.com/compute/docs/reference/rest/v1/instances/aggregatedList) the end-point `/compute/v1/projects/{project_id}/aggregated/instances` returns up to 500 results by default. So, the more existing servers we have, the more likely that the new-launched instance doesn't show up in the list of results.

### Versions Report
```
# salt --versions-report
Salt Version:
           Salt: 2019.2.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15+ (default, Jul  9 2019, 16:51:35)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-1044-gcp
         system: Linux
        version: Ubuntu 18.04 bionic
 ```

**Comment by zentrung** [comment]
After digging the stacktrace and the code, this is actually an issue of `libcloud` rather than `saltstack`. This issue was fixed in https://github.com/apache/libcloud/commit/e15d3a18bd73cd9e7149cdcc82370b78648c75dc.
So, upgrading `libcloud` to version `2.4.0` or higher fixes it for me.
