### ISSUE TITLE
x509.crl_managed not working - error on digest

### ISSUE THREAD

**Issue by joni1993** [saltstack/salt#54867]
### Description of Issue
x509.crl_managed fails because of digest.

### Setup
```
create_ca_crl:
  x509.crl_managed:
    - name: {{ ca.pki_directory }}/{{ ca.server.crl_file }}
    - signing_private_key: {{ ca.pki_directory }}/private/{{ ca.server.certificate.file_key }}
    - signing_cert: {{ ca.pki_directory }}/{{ ca.server.certificate.file }}
    - user: root
    - group: ssl-cert
    - mode: 644
    - digest: sha256
    - days_remaining: 30
    - backup: True
    - require:
      - file: create_pki_directory
      - x509: create_ca_key
      - x509: create_ca_certificate
```
### Steps to Reproduce Issue
With digest specified: 
```
File "/usr/lib/python3/dist-packages/salt/state.py", line 1933, in call
                  **cdata['kwargs'])
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 1951, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/x509.py", line 677, in crl_managed
                  new = __salt__['x509.read_crl'](crl=new_crl)
                File "/usr/lib/python3/dist-packages/salt/modules/x509.py", line 674, in read_crl
                  crltempfile.write(salt.utils.stringutils.to_str(text))
                File "/usr/lib/python3.5/tempfile.py", line 622, in func_wrapper
                  return func(*args, **kwargs)
              TypeError: a bytes-like object is required, not 'str
```
Without digest specified:
```
An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/modules/x509.py", line 1014, in create_crl
                  crltext = crl.export(**export_kwargs)
                File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 2230, in export
                  raise TypeError("digest must be provided")
              TypeError: digest must be provided
              
              During handling of the above exception, another exception occurred:
              
              Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 1933, in call
                  **cdata['kwargs'])
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 1951, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/x509.py", line 675, in crl_managed
                  signing_cert=signing_cert, revoked=revoked, days_valid=days_valid, digest=digest, include_expired=include_expired)
                File "/usr/lib/python3/dist-packages/salt/modules/x509.py", line 1019, in create_crl
                  crltext = crl.export(**export_kwargs)
                File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 2230, in export
                  raise TypeError("digest must be provided")
              TypeError: digest must be provided
```

### Versions Report
```
Salt Version:
           Salt: 2019.2.1
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 3.5.2 (default, Jul 10 2019, 11:58:48)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-165-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by iavael** [comment]
It actually works, if there’s no digest parameter at all, but it uses... ugh... md5 then. So it should be fixed.

**Comment by cheald** [comment]
This isn't failing because of digest, it's failing because: 

    crltempfile.write(salt.utils.stringutils.to_str(text))

tempfile.write() expects a bytes object, but `salt.utils.stringutils.to_str` takes a byte string and converts it to a unicode string. This is fixed by just changing this line to:

    crltempfile.write(text)
