### ISSUE TITLE
KeyError: u'Firewall Policy'

### ISSUE THREAD

**Issue by colttt** [saltstack/salt#55026]
### Description of Issue
just run a command from the documentation https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.win_lgpo.html at it doesn't work

### Setup
```
salt -l debug win7test lgpo.get machine --state-output=full --state-verbose=True
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/gitfs.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/gitfs.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/output.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/output.conf
[DEBUG   ] Changed git to gitfs in master opts' fileserver_backend list
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt.xxx.de
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/gitfs.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/gitfs.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/output.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/output.conf
[DEBUG   ] Changed git to gitfs in master opts' fileserver_backend list
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt.xxx.de
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/master', u'salt.xxx.de_master', u'tcp://127.0.0.1:4506', u'clear')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://127.0.0.1:4506
[DEBUG   ] Trying to connect to: tcp://127.0.0.1:4506
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/21/bb5b7473da55791b422dd19b298dd6442fad9994bc567b1fef6b81a5c57a87/.minions.p
[DEBUG   ] get_iter_returns for jid 20191016153726063881 sent to set(['win7test']) will timeout at 15:37:31.076096
[DEBUG   ] jid 20191016153726063881 return from win7test
[DEBUG   ] return event: {u'win7test': {u'jid': u'20191016153726063881', u'retcode': 1, u'ret': u'The minion function caused an exception: Traceback (most recent call last):\n  File "c:\\salt\\bin\\lib\\site-packages\\salt\\minion.py", line 1663, in _thread_return\n    return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)\n  File "c:\\salt\\bin\\lib\\site-packages\\salt\\executors\\direct_call.py", line 12, in execute\n    return func(*args, **kwargs)\n  File "c:\\salt\\bin\\lib\\site-packages\\salt\\modules\\win_lgpo.py", line 7735, in get\n    option=_pol[\'NetSH\'][\'Option\'])\n  File "c:\\salt\\bin\\lib\\site-packages\\salt\\modules\\win_lgpo.py", line 5276, in _findOptionValueNetSH\n    store=\'lgpo\')\n  File "c:\\salt\\bin\\lib\\site-packages\\salt\\utils\\win_lgpo_netsh.py", line 254, in get_all_settings\n    ret.update(get_settings(profile=profile, section=\'firewallpolicy\', store=store))\n  File "c:\\salt\\bin\\lib\\site-packages\\salt\\utils\\win_lgpo_netsh.py", line 221, in get_settings\n    inbound, outbound = ret[\'Firewall Policy\'].split(\',\')\nKeyError: u\'Firewall Policy\'\n', u'out': u'nested'}}
[DEBUG   ] LazyLoaded nested.output
win7test:
    The minion function caused an exception: Traceback (most recent call last):
      File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1663, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "c:\salt\bin\lib\site-packages\salt\executors\direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "c:\salt\bin\lib\site-packages\salt\modules\win_lgpo.py", line 7735, in get
        option=_pol['NetSH']['Option'])
      File "c:\salt\bin\lib\site-packages\salt\modules\win_lgpo.py", line 5276, in _findOptionValueNetSH
        store='lgpo')
      File "c:\salt\bin\lib\site-packages\salt\utils\win_lgpo_netsh.py", line 254, in get_all_settings
        ret.update(get_settings(profile=profile, section='firewallpolicy', store=store))
      File "c:\salt\bin\lib\site-packages\salt\utils\win_lgpo_netsh.py", line 221, in get_settings
        inbound, outbound = ret['Firewall Policy'].split(',')
    KeyError: u'Firewall Policy'
[DEBUG   ] jid 20191016153726063881 found all minions set([u'win7test'])
[DEBUG   ] Closing IPCMessageSubscriber instance
ERROR: Minions returned with non-zero exit code

```
### Steps to Reproduce Issue
I've a german Windows 7 notebook and play a little bit with it, just try it ;-)

### Versions Report
```
salt --versions-report
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Sep 25 2018, 20:42:16)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.11 
         locale: UTF-8
        machine: x86_64
        release: 3.16.0-7-amd64
         system: Linux
        version: debian 8.11 
 


salt win7test cmd.run 'C:\salt\salt-minion --versions-report'
win7test:
    Salt Version:
               Salt: 2019.2.1
     
    Dependency Versions:
               cffi: 1.12.2
           cherrypy: 17.4.1
           dateutil: 2.8.0
          docker-py: Not Installed
              gitdb: 2.0.5
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.10.1
            libgit2: Not Installed
            libnacl: 1.6.1
           M2Crypto: Not Installed
               Mako: 1.0.7
       msgpack-pure: Not Installed
     msgpack-python: 0.5.6
       mysql-python: Not Installed
          pycparser: 2.19
           pycrypto: Not Installed
       pycryptodome: 3.8.1
             pygit2: Not Installed
             Python: 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]
       python-gnupg: 0.4.4
             PyYAML: 3.13
              PyZMQ: 18.0.1
               RAET: Not Installed
              smmap: 2.0.5
            timelib: 0.2.4
            Tornado: 4.5.3
                ZMQ: 4.3.1
     
    System Versions:
               dist:   
             locale: cp1252
            machine: AMD64
            release: 7
             system: Windows
            version: 7 6.1.7601 SP1 Multiprocessor Free```

**Comment by garethgreenaway** [comment]
@xeacott @twangboy FYI

**Comment by twangboy** [comment]
@colttt Are you saying you're running German Windows?

**Comment by colttt** [comment]
@twangboy Yes that is correct, its the german version

**Comment by colttt** [comment]
@twangboy any ideas how to fix that?
