### ISSUE TITLE
smtp.send_msg: in Reactor Fails

### ISSUE THREAD

**Issue by swtharp** [saltstack/salt#55111]
### Description of Issue
beacons:
  diskusage:
    - /: 10%
Event Normal
salt/beacon/rhsttp3/diskusage/salt/beacon/rhsttp3/diskusage/  {
    "_stamp": "2019-10-24T03:10:37.457558",
    "diskusage": 60.8,
    "id": "rhsttp3",
    "mount": "/"
}
Reactors
reactor:
- salt/beacon/*/diskusage/:
    - /srv/reactor/diskusage.sls
diskusage:
  smtp.send_msg:
    - recipient: steven@steventharp.com
    - message: "Disk usage on {{ data['id'] }} (mount: {{ data['mount'] }}) is at {{ data['diskusage'] }}%."
    - subject: "High disk usage on {{ data['id'] }}"
    - profile: "my_smtp_profile"
    - use_ssl: "False"
diskusage:
  smtp.send_msg:
    - recipient: steven@steventharp.com
    - message: "Disk usage on {{ data['id'] }} (mount: {{ data['mount'] }}) is at {{ data['diskusage'] }}%."
    - subject: "High disk usage on {{ data['id'] }}"
    - profile: "my_smtp_profile"
    - use_ssl: "False"
Profile
my_smtp_profile:
    smtp.sender: salt@thettp.org
    smtp.server: smg.thettp.org
    smtp.tls: False
Master LOG
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/engines/__init__.py", line 132, in run
    self.engine[self.fun](**kwargs)
  File "/usr/lib/python3.6/site-packages/salt/engines/reactor.py", line 36, in start
    salt.utils.reactor.Reactor(__opts__).run()
  File "/usr/lib/python3.6/site-packages/salt/utils/process.py", line 765, in _run
    return self._original_run()
  File "/usr/lib/python3.6/site-packages/salt/utils/reactor.py", line 271, in run
    self.call_reactions(chunks)
  File "/usr/lib/python3.6/site-packages/salt/utils/reactor.py", line 228, in call_reactions
    self.wrap.run(chunk)
  File "/usr/lib/python3.6/site-packages/salt/utils/reactor.py", line 330, in run
    self.populate_client_cache(low)
  File "/usr/lib/python3.6/site-packages/salt/utils/reactor.py", line 324, in populate_client_cache
    self.reaction_class[reaction_type](self.opts['conf_file'])
KeyError: 'smtp'
2019-10-24 03:34:54,860 [salt.utils.process:772 ][ERROR   ][60622] An un-handled exception from the multiprocessing process 'Reactor-18:1' was caught:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/process.py", line 765, in _run
    return self._original_run()
  File "/usr/lib/python3.6/site-packages/salt/utils/reactor.py", line 271, in run
    self.call_reactions(chunks)
  File "/usr/lib/python3.6/site-packages/salt/utils/reactor.py", line 228, in call_reactions
    self.wrap.run(chunk)
  File "/usr/lib/python3.6/site-packages/salt/utils/reactor.py", line 330, in run
    self.populate_client_cache(low)
  File "/usr/lib/python3.6/site-packages/salt/utils/reactor.py", line 324, in populate_client_cache
    self.reaction_class[reaction_type](self.opts['conf_file'])
KeyError: 'smtp'
2019-10-24 03:34:54,861 [salt.engines     :136 ][CRITICAL][60622] Engine 'reactor' could not be started!
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/engines/__init__.py", line 132, in run
    self.engine[self.fun](**kwargs)
  File "/usr/lib/python3.6/site-packages/salt/engines/reactor.py", line 36, in start
    salt.utils.reactor.Reactor(__opts__).run()
  File "/usr/lib/python3.6/site-packages/salt/utils/process.py", line 765, in _run
    return self._original_run()
  File "/usr/lib/python3.6/site-packages/salt/utils/reactor.py", line 271, in run
    self.call_reactions(chunks)
  File "/usr/lib/python3.6/site-packages/salt/utils/reactor.py", line 228, in call_reactions
    self.wrap.run(chunk)
  File "/usr/lib/python3.6/site-packages/salt/utils/reactor.py", line 330, in run
    self.populate_client_cache(low)
  File "/usr/lib/python3.6/site-packages/salt/utils/reactor.py", line 324, in populate_client_cache
    self.reaction_class[reaction_type](self.opts['conf_file'])
KeyError: 'smtp'
2019-10-24 03:35:04,806 [salt.utils.process:772 ][ERROR   ][60663] An un-handled exception from the multiprocessing process 'Reactor-19:1' was caught:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/process.py", line 765, in _run
    return self._original_run()
  File "/usr/lib/python3.6/site-packages/salt/utils/reactor.py", line 271, in run
    self.call_reactions(chunks)
  File "/usr/lib/python3.6/site-packages/salt/utils/reactor.py", line 228, in call_reactions
    self.wrap.run(chunk)
  File "/usr/lib/python3.6/site-packages/salt/utils/reactor.py", line 330, in run
    self.populate_client_cache(low)
  File "/usr/lib/python3.6/site-packages/salt/utils/reactor.py", line 324, in populate_client_cache
    self.reaction_class[reaction_type](self.opts['conf_file'])
KeyError: 'smtp'	
	
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.11.2
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: 0.26.3
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.4
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.0
         Python: 3.6.8 (default, Apr 30 2019, 13:27:23) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.3
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 4.12.14-150.35-default
         system: Linux
        version: Not Installed

**Comment by swtharp** [comment]
I cure this by changing the diskusage reactor to read: 
diskusage:
    local.smtp.send_msg:
        - tgt: 'rhsttp3'
        - arg:
            - 'steven@steventharp.com'
            - "Disk usage on {{ data['id'] }} (mount: {{ data['mount'] }}) is at {{ data['diskusage'] }}%."
            - subject="High disk usage on {{ data['id'] }}"
            - profile='my_smtp_profile'
