### ISSUE TITLE
Jinja renderer resolves wrong relative paths when importing subdirectories

### ISSUE THREAD

**Issue by dgengtek** [saltstack/salt#55159]
### Description of Issue
Importing variables from a subdirectory fails when using the relative path syntax with an error of `salt.exceptions.SaltRenderError: Jinja variable the template './map.jinja' (imported on line 3) does not export the requested name '<variable>'`. 

Using the full relative path does not fail with a rendering error but resolves to the wrong path for defaults.yaml because of `{% import_yaml "./defaults.yaml" as defaults %}` in subdir/map.jinja. Result is that the wrong variable is rendered in the output. Using the full path for defaults.yaml in subdir/map.jinja renders without errors.

Is this intended behaviour that the relative path syntax only works for the root directory?
### Setup
```
$ tree
.
├── defaults.yaml
├── map.jinja
└── subdir
    ├── defaults.yaml
    ├── map.jinja
    └── test.sls
```
```
# defaults.yaml
rootdir: "ok"
```
```
# map.jinja
{% import_yaml "./defaults.yaml" as defaults %}

{% set simpletest = salt['pillar.get'](
        'simpletest',
        default=defaults,
        merge=True
    )
%}
```
```
# subdir/defaults.yaml
subdir: "good"
```
```
# subdir/map.jinja
{% import_yaml "./defaults.yaml" as defaults %}

{% set subdir = salt['pillar.get'](
        'subdir',
        default=defaults,
        merge=True
    )
%}
```
```
# subdir/test_path.sls
{% from "simpletest/map.jinja" import simpletest with context %}
{% from "simpletest/subdir/map.jinja" import subdir with context %}

{{ simpletest }}

{{ subdir }}
```
```
# subdir/test_syntax.sls
{% from "simpletest/map.jinja" import simpletest with context %}
{% from "./map.jinja" import subdir with context %}

{{ simpletest }}

{{ subdir }}
```

### Steps to Reproduce Issue
```
Converging <simpletest-formula-kitchen-debian-9>...
Preparing files for transfer
Preparing salt-minion
Preparing pillars into /srv/pillar
Preparing grains into /etc/salt/grains
Preparing formula: simpletest from /mnt/hdd/bigX/salt/formulas/simpletest-formula
Preparing state_top
Preparing scripts into /etc/salt/scripts
Generating locales (this might take a while)...
 en_US.UTF-8... done
Generation complete.
You asked for latest and you have 2019.2.0 installed, sweet!
Transferring files to <simpletest-formula-kitchen-debian-9>
Install External Dependencies
Content of /tmp/kitchen//srv/salt :
total 28
drwxr-xr-x 6 root    kitchen 4096 Oct 29 17:15 .
drwxr-xr-x 4 kitchen kitchen 4096 Oct 29 17:15 ..
drwxr-xr-x 3 root    kitchen 4096 Oct 29 17:15 _grains
drwxr-xr-x 3 root    kitchen 4096 Oct 29 17:15 _modules
drwxr-xr-x 3 root    kitchen 4096 Oct 29 17:15 simpletest
drwxr-xr-x 3 root    kitchen 4096 Oct 29 17:15 _states
-rw-r--r-- 1 root    kitchen   83 Oct 29 17:17 top.sls
[DEBUG   ] Reading configuration from /tmp/kitchen/etc/salt/minion
[DEBUG   ] Including configuration from '/tmp/kitchen/etc/salt/minion.d/99-minion.conf'
[DEBUG   ] Reading configuration from /tmp/kitchen/etc/salt/minion.d/99-minion.conf
[DEBUG   ] Using cached minion ID from /tmp/kitchen/etc/salt/minion_id: simpletest-formula-kitchen-debian-9-d243dbcedaed4e63
[DEBUG   ] Configuration file path: /tmp/kitchen/etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from /tmp/kitchen/etc/salt/minion
[DEBUG   ] Including configuration from '/tmp/kitchen/etc/salt/minion.d/99-minion.conf'
[DEBUG   ] Reading configuration from /tmp/kitchen/etc/salt/minion.d/99-minion.conf
[DEBUG   ] /etc/resolv.conf: The domain and search keywords are mutually exclusive.
[DEBUG   ] Loading static grains from /tmp/kitchen/etc/salt/grains
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] compile template: /tmp/kitchen/srv/pillar/top.sls
[DEBUG   ] Jinja search path: ['/tmp/kitchen/srv/pillar', '/tmp/kitchen/srv/spm/pillar']
[PROFILE ] Time (in seconds) to render '/tmp/kitchen/srv/pillar/top.sls' using 'jinja' renderer: 0.011122703552246094
[DEBUG   ] Rendered data from file: /tmp/kitchen/srv/pillar/top.sls:
---
base:
 "*": []

[DEBUG   ] Results of YAML rendering:
OrderedDict([('base', OrderedDict([('*', [])]))])
[PROFILE ] Time (in seconds) to render '/tmp/kitchen/srv/pillar/top.sls' using 'yaml' renderer: 0.00039768218994140625
[DEBUG   ] LazyLoaded confirm_top.confirm_top
[ERROR   ] Received bad data when setting the match from the top file
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded state.highstate
[DEBUG   ] LazyLoaded direct_call.execute
[DEBUG   ] LazyLoaded grains.get
[DEBUG   ] LazyLoaded saltutil.is_running
[DEBUG   ] LazyLoaded config.get
[DEBUG   ] key: test, ret: _|-
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[DEBUG   ] Updating roots fileserver cache
[DEBUG   ] Gathering pillar data for state run
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] compile template: /tmp/kitchen/srv/pillar/top.sls
[DEBUG   ] Jinja search path: ['/tmp/kitchen/srv/pillar', '/tmp/kitchen/srv/spm/pillar']
[PROFILE ] Time (in seconds) to render '/tmp/kitchen/srv/pillar/top.sls' using 'jinja' renderer: 0.009231090545654297
[DEBUG   ] Rendered data from file: /tmp/kitchen/srv/pillar/top.sls:
---
base:
 "*": []

[DEBUG   ] Results of YAML rendering:
OrderedDict([('base', OrderedDict([('*', [])]))])
[PROFILE ] Time (in seconds) to render '/tmp/kitchen/srv/pillar/top.sls' using 'yaml' renderer: 0.00030350685119628906
[DEBUG   ] LazyLoaded confirm_top.confirm_top
[ERROR   ] Received bad data when setting the match from the top file
[DEBUG   ] Finished gathering pillar data for state run
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] In saltenv 'base', looking at rel_path 'top.sls' to resolve 'salt://top.sls'
[DEBUG   ] In saltenv 'base', ** considering ** path '/tmp/kitchen/var/cache/salt/minion/files/base/top.sls' to resolve 'salt://top.sls'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://top.sls'
[DEBUG   ] No dest file found
[INFO    ] Fetching file from saltenv 'base', ** done ** 'top.sls'
[DEBUG   ] compile template: /tmp/kitchen/var/cache/salt/minion/files/base/top.sls
[DEBUG   ] Jinja search path: ['/tmp/kitchen/var/cache/salt/minion/files/base']
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[PROFILE ] Time (in seconds) to render '/tmp/kitchen/var/cache/salt/minion/files/base/top.sls' using 'jinja' renderer: 0.021074295043945312
[DEBUG   ] Rendered data from file: /tmp/kitchen/var/cache/salt/minion/files/base/top.sls:
---
base:
 "*":
 - simpletest.subdir.test_syntax
 - simpletest.subdir.test_path

[DEBUG   ] Results of YAML rendering:
OrderedDict([('base', OrderedDict([('*', ['simpletest.subdir.test_syntax', 'simpletest.subdir.test_path'])]))])
[PROFILE ] Time (in seconds) to render '/tmp/kitchen/var/cache/salt/minion/files/base/top.sls' using 'yaml' renderer: 0.00029754638671875
[DEBUG   ] LazyLoaded confirm_top.confirm_top
[DEBUG   ] LazyLoaded compound_match.match
[DEBUG   ] compound_match: simpletest-formula-kitchen-debian-9-d243dbcedaed4e63 ? *
[DEBUG   ] LazyLoaded glob_match.match
[DEBUG   ] compound_match simpletest-formula-kitchen-debian-9-d243dbcedaed4e63 ? "*" => "True"
[DEBUG   ] The _ext_nodes master function has been renamed to _master_tops. To ensure compatibility when using older Salt masters we will continue to invoke the function as _ext_nodes until the Magnesium release.
[DEBUG   ] LazyLoaded saltutil.sync_all
[DEBUG   ] Syncing all
[INFO    ] Creating module dir '/tmp/kitchen/var/cache/salt/minion/extmods/clouds'
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[INFO    ] Syncing clouds for environment 'base'
[INFO    ] Loading cache from salt://_clouds, for base)
[INFO    ] Caching directory '_clouds/' for environment 'base'
[DEBUG   ] Returning file list from cache: age=0 cache_time=20 /tmp/kitchen/var/cache/salt/minion/file_lists/roots/base.p
[DEBUG   ] Local cache dir: '/tmp/kitchen/var/cache/salt/minion/files/base/_clouds'
[INFO    ] Creating module dir '/tmp/kitchen/var/cache/salt/minion/extmods/beacons'
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[INFO    ] Syncing beacons for environment 'base'
[INFO    ] Loading cache from salt://_beacons, for base)
[INFO    ] Caching directory '_beacons/' for environment 'base'
[DEBUG   ] Returning file list from cache: age=0 cache_time=20 /tmp/kitchen/var/cache/salt/minion/file_lists/roots/base.p
[DEBUG   ] Local cache dir: '/tmp/kitchen/var/cache/salt/minion/files/base/_beacons'
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[INFO    ] Syncing modules for environment 'base'
[INFO    ] Loading cache from salt://_modules, for base)
[INFO    ] Caching directory '_modules/' for environment 'base'
[DEBUG   ] Returning file list from cache: age=0 cache_time=20 /tmp/kitchen/var/cache/salt/minion/file_lists/roots/base.p
[DEBUG   ] In saltenv 'base', looking at rel_path '_modules/dgops_simpletest.py' to resolve 'salt://_modules/dgops_simpletest.py'
[DEBUG   ] In saltenv 'base', ** considering ** path '/tmp/kitchen/var/cache/salt/minion/files/base/_modules/dgops_simpletest.py' to resolve 'salt://_modules/dgops_simpletest.py'
[DEBUG   ] In saltenv 'base', looking at rel_path '_modules/tests/conftest.py' to resolve 'salt://_modules/tests/conftest.py'
[DEBUG   ] In saltenv 'base', ** considering ** path '/tmp/kitchen/var/cache/salt/minion/files/base/_modules/tests/conftest.py' to resolve 'salt://_modules/tests/conftest.py'
[DEBUG   ] In saltenv 'base', looking at rel_path '_modules/tests/test_custom_simpletest.py' to resolve 'salt://_modules/tests/test_custom_simpletest.py'
[DEBUG   ] In saltenv 'base', ** considering ** path '/tmp/kitchen/var/cache/salt/minion/files/base/_modules/tests/test_custom_simpletest.py' to resolve 'salt://_modules/tests/test_custom_simpletest.py'
[DEBUG   ] Local cache dir: '/tmp/kitchen/var/cache/salt/minion/files/base/_modules'
[INFO    ] Copying '/tmp/kitchen/var/cache/salt/minion/files/base/_modules/dgops_simpletest.py' to '/tmp/kitchen/var/cache/salt/minion/extmods/modules/dgops_simpletest.py'
[INFO    ] Copying '/tmp/kitchen/var/cache/salt/minion/files/base/_modules/tests/conftest.py' to '/tmp/kitchen/var/cache/salt/minion/extmods/modules/tests/conftest.py'
[INFO    ] Copying '/tmp/kitchen/var/cache/salt/minion/files/base/_modules/tests/test_custom_simpletest.py' to '/tmp/kitchen/var/cache/salt/minion/extmods/modules/tests/test_custom_simpletest.py'
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[INFO    ] Syncing states for environment 'base'
[INFO    ] Loading cache from salt://_states, for base)
[INFO    ] Caching directory '_states/' for environment 'base'
[DEBUG   ] Returning file list from cache: age=0 cache_time=20 /tmp/kitchen/var/cache/salt/minion/file_lists/roots/base.p
[DEBUG   ] In saltenv 'base', looking at rel_path '_states/dgops_simpletest.py' to resolve 'salt://_states/dgops_simpletest.py'
[DEBUG   ] In saltenv 'base', ** considering ** path '/tmp/kitchen/var/cache/salt/minion/files/base/_states/dgops_simpletest.py' to resolve 'salt://_states/dgops_simpletest.py'
[DEBUG   ] In saltenv 'base', looking at rel_path '_states/tests/conftest.py' to resolve 'salt://_states/tests/conftest.py'
[DEBUG   ] In saltenv 'base', ** considering ** path '/tmp/kitchen/var/cache/salt/minion/files/base/_states/tests/conftest.py' to resolve 'salt://_states/tests/conftest.py'
[DEBUG   ] In saltenv 'base', looking at rel_path '_states/tests/test_custom_simpletest.py' to resolve 'salt://_states/tests/test_custom_simpletest.py'
[DEBUG   ] In saltenv 'base', ** considering ** path '/tmp/kitchen/var/cache/salt/minion/files/base/_states/tests/test_custom_simpletest.py' to resolve 'salt://_states/tests/test_custom_simpletest.py'
[DEBUG   ] Local cache dir: '/tmp/kitchen/var/cache/salt/minion/files/base/_states'
[INFO    ] Copying '/tmp/kitchen/var/cache/salt/minion/files/base/_states/dgops_simpletest.py' to '/tmp/kitchen/var/cache/salt/minion/extmods/states/dgops_simpletest.py'
[INFO    ] Copying '/tmp/kitchen/var/cache/salt/minion/files/base/_states/tests/conftest.py' to '/tmp/kitchen/var/cache/salt/minion/extmods/states/tests/conftest.py'
[INFO    ] Copying '/tmp/kitchen/var/cache/salt/minion/files/base/_states/tests/test_custom_simpletest.py' to '/tmp/kitchen/var/cache/salt/minion/extmods/states/tests/test_custom_simpletest.py'
[INFO    ] Creating module dir '/tmp/kitchen/var/cache/salt/minion/extmods/sdb'
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[INFO    ] Syncing sdb for environment 'base'
[INFO    ] Loading cache from salt://_sdb, for base)
[INFO    ] Caching directory '_sdb/' for environment 'base'
[DEBUG   ] Returning file list from cache: age=0 cache_time=20 /tmp/kitchen/var/cache/salt/minion/file_lists/roots/base.p
[DEBUG   ] Local cache dir: '/tmp/kitchen/var/cache/salt/minion/files/base/_sdb'
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[INFO    ] Syncing grains for environment 'base'
[INFO    ] Loading cache from salt://_grains, for base)
[INFO    ] Caching directory '_grains/' for environment 'base'
[DEBUG   ] Returning file list from cache: age=0 cache_time=20 /tmp/kitchen/var/cache/salt/minion/file_lists/roots/base.p
[DEBUG   ] In saltenv 'base', looking at rel_path '_grains/tests/conftest.py' to resolve 'salt://_grains/tests/conftest.py'
[DEBUG   ] In saltenv 'base', ** considering ** path '/tmp/kitchen/var/cache/salt/minion/files/base/_grains/tests/conftest.py' to resolve 'salt://_grains/tests/conftest.py'
[DEBUG   ] In saltenv 'base', looking at rel_path '_grains/tests/test_simpletest.py' to resolve 'salt://_grains/tests/test_simpletest.py'
[DEBUG   ] In saltenv 'base', ** considering ** path '/tmp/kitchen/var/cache/salt/minion/files/base/_grains/tests/test_simpletest.py' to resolve 'salt://_grains/tests/test_simpletest.py'
[DEBUG   ] Local cache dir: '/tmp/kitchen/var/cache/salt/minion/files/base/_grains'
[INFO    ] Copying '/tmp/kitchen/var/cache/salt/minion/files/base/_grains/tests/conftest.py' to '/tmp/kitchen/var/cache/salt/minion/extmods/grains/tests/conftest.py'
[INFO    ] Copying '/tmp/kitchen/var/cache/salt/minion/files/base/_grains/tests/test_simpletest.py' to '/tmp/kitchen/var/cache/salt/minion/extmods/grains/tests/test_simpletest.py'
[INFO    ] Creating module dir '/tmp/kitchen/var/cache/salt/minion/extmods/renderers'
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[INFO    ] Syncing renderers for environment 'base'
[INFO    ] Loading cache from salt://_renderers, for base)
[INFO    ] Caching directory '_renderers/' for environment 'base'
[DEBUG   ] Returning file list from cache: age=0 cache_time=20 /tmp/kitchen/var/cache/salt/minion/file_lists/roots/base.p
[DEBUG   ] Local cache dir: '/tmp/kitchen/var/cache/salt/minion/files/base/_renderers'
[INFO    ] Creating module dir '/tmp/kitchen/var/cache/salt/minion/extmods/returners'
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[INFO    ] Syncing returners for environment 'base'
[INFO    ] Loading cache from salt://_returners, for base)
[INFO    ] Caching directory '_returners/' for environment 'base'
[DEBUG   ] Returning file list from cache: age=0 cache_time=20 /tmp/kitchen/var/cache/salt/minion/file_lists/roots/base.p
[DEBUG   ] Local cache dir: '/tmp/kitchen/var/cache/salt/minion/files/base/_returners'
[INFO    ] Creating module dir '/tmp/kitchen/var/cache/salt/minion/extmods/output'
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[INFO    ] Syncing output for environment 'base'
[INFO    ] Loading cache from salt://_output, for base)
[INFO    ] Caching directory '_output/' for environment 'base'
[DEBUG   ] Returning file list from cache: age=0 cache_time=20 /tmp/kitchen/var/cache/salt/minion/file_lists/roots/base.p
[DEBUG   ] Local cache dir: '/tmp/kitchen/var/cache/salt/minion/files/base/_output'
[INFO    ] Creating module dir '/tmp/kitchen/var/cache/salt/minion/extmods/utils'
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[INFO    ] Syncing utils for environment 'base'
[INFO    ] Loading cache from salt://_utils, for base)
[INFO    ] Caching directory '_utils/' for environment 'base'
[DEBUG   ] Returning file list from cache: age=0 cache_time=20 /tmp/kitchen/var/cache/salt/minion/file_lists/roots/base.p
[DEBUG   ] Local cache dir: '/tmp/kitchen/var/cache/salt/minion/files/base/_utils'
[INFO    ] Creating module dir '/tmp/kitchen/var/cache/salt/minion/extmods/log_handlers'
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[INFO    ] Syncing log_handlers for environment 'base'
[INFO    ] Loading cache from salt://_log_handlers, for base)
[INFO    ] Caching directory '_log_handlers/' for environment 'base'
[DEBUG   ] Returning file list from cache: age=1 cache_time=20 /tmp/kitchen/var/cache/salt/minion/file_lists/roots/base.p
[DEBUG   ] Local cache dir: '/tmp/kitchen/var/cache/salt/minion/files/base/_log_handlers'
[INFO    ] Creating module dir '/tmp/kitchen/var/cache/salt/minion/extmods/proxy'
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[INFO    ] Syncing proxy for environment 'base'
[INFO    ] Loading cache from salt://_proxy, for base)
[INFO    ] Caching directory '_proxy/' for environment 'base'
[DEBUG   ] Returning file list from cache: age=1 cache_time=20 /tmp/kitchen/var/cache/salt/minion/file_lists/roots/base.p
[DEBUG   ] Local cache dir: '/tmp/kitchen/var/cache/salt/minion/files/base/_proxy'
[INFO    ] Creating module dir '/tmp/kitchen/var/cache/salt/minion/extmods/engines'
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[INFO    ] Syncing engines for environment 'base'
[INFO    ] Loading cache from salt://_engines, for base)
[INFO    ] Caching directory '_engines/' for environment 'base'
[DEBUG   ] Returning file list from cache: age=1 cache_time=20 /tmp/kitchen/var/cache/salt/minion/file_lists/roots/base.p
[DEBUG   ] Local cache dir: '/tmp/kitchen/var/cache/salt/minion/files/base/_engines'
[INFO    ] Creating module dir '/tmp/kitchen/var/cache/salt/minion/extmods/thorium'
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[INFO    ] Syncing thorium for environment 'base'
[INFO    ] Loading cache from salt://_thorium, for base)
[INFO    ] Caching directory '_thorium/' for environment 'base'
[DEBUG   ] Returning file list from cache: age=1 cache_time=20 /tmp/kitchen/var/cache/salt/minion/file_lists/roots/base.p
[DEBUG   ] Local cache dir: '/tmp/kitchen/var/cache/salt/minion/files/base/_thorium'
[INFO    ] Creating module dir '/tmp/kitchen/var/cache/salt/minion/extmods/serializers'
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[INFO    ] Syncing serializers for environment 'base'
[INFO    ] Loading cache from salt://_serializers, for base)
[INFO    ] Caching directory '_serializers/' for environment 'base'
[DEBUG   ] Returning file list from cache: age=1 cache_time=20 /tmp/kitchen/var/cache/salt/minion/file_lists/roots/base.p
[DEBUG   ] Local cache dir: '/tmp/kitchen/var/cache/salt/minion/files/base/_serializers'
[INFO    ] Creating module dir '/tmp/kitchen/var/cache/salt/minion/extmods/matchers'
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[INFO    ] Syncing matchers for environment 'base'
[INFO    ] Loading cache from salt://_matchers, for base)
[INFO    ] Caching directory '_matchers/' for environment 'base'
[DEBUG   ] Returning file list from cache: age=1 cache_time=20 /tmp/kitchen/var/cache/salt/minion/file_lists/roots/base.p
[DEBUG   ] Local cache dir: '/tmp/kitchen/var/cache/salt/minion/files/base/_matchers'
[INFO    ] Creating module dir '/tmp/kitchen/var/cache/salt/minion/extmods/pillar'
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[INFO    ] Syncing pillar for environment 'base'
[INFO    ] Loading cache from salt://_pillar, for base)
[INFO    ] Caching directory '_pillar/' for environment 'base'
[DEBUG   ] Returning file list from cache: age=1 cache_time=20 /tmp/kitchen/var/cache/salt/minion/file_lists/roots/base.p
[DEBUG   ] Local cache dir: '/tmp/kitchen/var/cache/salt/minion/files/base/_pillar'
[DEBUG   ] Refreshing modules...
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] In saltenv 'base', looking at rel_path 'simpletest/subdir/test_syntax.sls' to resolve 'salt://simpletest/subdir/test_syntax.sls'
[DEBUG   ] In saltenv 'base', ** considering ** path '/tmp/kitchen/var/cache/salt/minion/files/base/simpletest/subdir/test_syntax.sls' to resolve 'salt://simpletest/subdir/test_syntax.sls'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://simpletest/subdir/test_syntax.sls'
[DEBUG   ] No dest file found
[INFO    ] Fetching file from saltenv 'base', ** done ** 'simpletest/subdir/test_syntax.sls'
[DEBUG   ] compile template: /tmp/kitchen/var/cache/salt/minion/files/base/simpletest/subdir/test_syntax.sls
[DEBUG   ] Jinja search path: ['/tmp/kitchen/var/cache/salt/minion/files/base']
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[DEBUG   ] In saltenv 'base', looking at rel_path 'simpletest/map.jinja' to resolve 'salt://simpletest/map.jinja'
[DEBUG   ] In saltenv 'base', ** considering ** path '/tmp/kitchen/var/cache/salt/minion/files/base/simpletest/map.jinja' to resolve 'salt://simpletest/map.jinja'
[DEBUG   ] In saltenv 'base', looking at rel_path 'simpletest/defaults.yaml' to resolve 'salt://simpletest/defaults.yaml'
[DEBUG   ] In saltenv 'base', ** considering ** path '/tmp/kitchen/var/cache/salt/minion/files/base/simpletest/defaults.yaml' to resolve 'salt://simpletest/defaults.yaml'
[DEBUG   ] LazyLoaded pillar.get
[ERROR   ] Rendering exception occurred
Traceback (most recent call last):
 File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 392, in render_jinja_tmpl
   output = template.render(**decoded_context)
 File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
   return self.environment.handle_exception(exc_info, True)
 File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
   reraise(exc_type, exc_value, tb)
 File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
   raise value.with_traceback(tb)
 File "<template>", line 7, in top-level template code
jinja2.exceptions.UndefinedError: the template './map.jinja' (imported on line 3) does not export the requested name 'subdir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 169, in render_tmpl
   output = render_str(tmplstr, context, tmplpath)
 File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 402, in render_jinja_tmpl
   buf=tmplstr)
salt.exceptions.SaltRenderError: Jinja variable the template './map.jinja' (imported on line 3) does not export the requested name 'subdir'
[CRITICAL] Rendering SLS 'base:simpletest.subdir.test_syntax' failed: Jinja variable the template './map.jinja' (imported on line 3) does not export the requested name 'subdir'
[DEBUG   ] In saltenv 'base', looking at rel_path 'simpletest/subdir/test_path.sls' to resolve 'salt://simpletest/subdir/test_path.sls'
[DEBUG   ] In saltenv 'base', ** considering ** path '/tmp/kitchen/var/cache/salt/minion/files/base/simpletest/subdir/test_path.sls' to resolve 'salt://simpletest/subdir/test_path.sls'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://simpletest/subdir/test_path.sls'
[DEBUG   ] No dest file found
[INFO    ] Fetching file from saltenv 'base', ** done ** 'simpletest/subdir/test_path.sls'
[DEBUG   ] compile template: /tmp/kitchen/var/cache/salt/minion/files/base/simpletest/subdir/test_path.sls
[DEBUG   ] Jinja search path: ['/tmp/kitchen/var/cache/salt/minion/files/base']
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[DEBUG   ] In saltenv 'base', looking at rel_path 'simpletest/map.jinja' to resolve 'salt://simpletest/map.jinja'
[DEBUG   ] In saltenv 'base', ** considering ** path '/tmp/kitchen/var/cache/salt/minion/files/base/simpletest/map.jinja' to resolve 'salt://simpletest/map.jinja'
[DEBUG   ] In saltenv 'base', looking at rel_path 'simpletest/defaults.yaml' to resolve 'salt://simpletest/defaults.yaml'
[DEBUG   ] In saltenv 'base', ** considering ** path '/tmp/kitchen/var/cache/salt/minion/files/base/simpletest/defaults.yaml' to resolve 'salt://simpletest/defaults.yaml'
[DEBUG   ] In saltenv 'base', looking at rel_path 'simpletest/subdir/map.jinja' to resolve 'salt://simpletest/subdir/map.jinja'
[DEBUG   ] In saltenv 'base', ** considering ** path '/tmp/kitchen/var/cache/salt/minion/files/base/simpletest/subdir/map.jinja' to resolve 'salt://simpletest/subdir/map.jinja'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://simpletest/subdir/map.jinja'
[DEBUG   ] No dest file found
[INFO    ] Fetching file from saltenv 'base', ** done ** 'simpletest/subdir/map.jinja'
[PROFILE ] Time (in seconds) to render '/tmp/kitchen/var/cache/salt/minion/files/base/simpletest/subdir/test_path.sls' using 'jinja' renderer: 0.03363323211669922
[DEBUG   ] Rendered data from file: /tmp/kitchen/var/cache/salt/minion/files/base/simpletest/subdir/test_path.sls:
# vim: ft=sls



{'rootdir': 'ok'}

{'rootdir': 'ok'}

[CRITICAL] Rendering SLS 'base:simpletest.subdir.test_path' failed: did not find expected <document start>
 in "<unicode string>", line 7, column 1
local:
   Data failed to compile:
----------
   Rendering SLS 'base:simpletest.subdir.test_syntax' failed: Jinja variable the template './map.jinja' (imported on line 3) does not export the requested name 'subdir'
----------
   Rendering SLS 'base:simpletest.subdir.test_path' failed: did not find expected <document start>
 in "<unicode string>", line 7, column 1

```

### Versions Report
```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (default, Sep 27 2018, 17:25:39)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.5
         locale: UTF-8
        machine: x86_64
        release: 5.3.7-arch1-1-ARCH
         system: Linux
        version: debian 9.5
```

**Comment by frogunder** [comment]
https://github.com/saltstack/salt/issues/55158
