### ISSUE TITLE
XTablesError: can't find directory with extensions; please set XTABLES_LIBDIR

### ISSUE THREAD

**Issue by Linuturk** [saltstack/salt#55160]
### Description of Issue

I'm not running any specific states. Nothing related to iptables.

Seeing the following traceback in my salt-minion logs:

```
Oct 29 18:17:01 r3000113 salt-minion[14825]: [ERROR   ] Failed to import module apf, this is due most likely to a syntax error:
Oct 29 18:17:01 r3000113 salt-minion[14825]: Traceback (most recent call last):
Oct 29 18:17:01 r3000113 salt-minion[14825]:   File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1555, in _load_module
Oct 29 18:17:01 r3000113 salt-minion[14825]:     mod = imp.load_module(mod_namespace, fn_, fpath, desc)
Oct 29 18:17:01 r3000113 salt-minion[14825]:   File "/usr/lib/python2.7/dist-packages/salt/modules/apf.py", line 14, in <module>
Oct 29 18:17:01 r3000113 salt-minion[14825]:     import iptc
Oct 29 18:17:01 r3000113 salt-minion[14825]:   File "/usr/local/lib/python2.7/dist-packages/iptc/__init__.py", line 10, in <module>
Oct 29 18:17:01 r3000113 salt-minion[14825]:     from iptc.ip4tc import (is_table_available, Table, Chain, Rule, Match, Target,
Oct 29 18:17:01 r3000113 salt-minion[14825]:   File "/usr/local/lib/python2.7/dist-packages/iptc/ip4tc.py", line 13, in <module>
Oct 29 18:17:01 r3000113 salt-minion[14825]:     from .xtables import (XT_INV_PROTO, NFPROTO_IPV4, XTablesError, xtables,
Oct 29 18:17:01 r3000113 salt-minion[14825]:   File "/usr/local/lib/python2.7/dist-packages/iptc/xtables.py", line 691, in <module>
Oct 29 18:17:01 r3000113 salt-minion[14825]:     raise XTablesError("can't find directory with extensions; "
Oct 29 18:17:01 r3000113 salt-minion[14825]: XTablesError: can't find directory with extensions; please set XTABLES_LIBDIR
```

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

Setup a salt-minion and connect to the master. Execute `salt 'myminion' test.version` and see the output of the Traceback in your minion side logs.

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Minion:
```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Sep 26 2018, 18:42:22)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.4 
         locale: UTF-8
        machine: x86_64
        release: 4.14.97
         system: Linux
        version: debian 9.4
```

Master
```
Salt Version:
           Salt: 2019.2.2
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.12 (default, Oct  8 2019, 14:14:10)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-1050-aws
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by frogunder** [comment]
@Linuturk Thank you for reporting this issue.

I am not able to replicate this and do not see what you are seeing.
Do you have any additional information to help me replicate it? Thanks.

**Comment by Linuturk** [comment]
Sure, happy to provide any additional information. What additional information would be helpful?

**Comment by Linuturk** [comment]
It seems like this might be related to https://github.com/ldx/python-iptables/issues/37 

I've modified `/usr/local/lib/python2.7/dist-packages/iptc/xtables.py` on a minion exhibiting this behavior. On line 691 I've changed it from:

```python
if _xtables_libdir is None:
    import os.path
    for xtdir in ["/lib/xtables", "/lib64/xtables", "/usr/lib/xtables",
                  "/usr/lib/iptables", "/usr/lib64/xtables",
                  "/usr/lib64/iptables", "/usr/local/lib/xtables"]:
        if os.path.isdir(xtdir):
            _xtables_libdir = xtdir
            break
if _xtables_libdir is None:
    raise XTablesError("can't find directory with extensions; "
                       "please set XTABLES_LIBDIR")
```

to

```python
if _xtables_libdir is None:
    import os.path
    for xtdir in ["/lib/xtables", "/lib64/xtables", "/usr/lib/xtables",
                  "/usr/lib/iptables", "/usr/lib64/xtables",
                  "/usr/lib64/iptables", "/usr/local/lib/xtables", "/usr/lib/x86_64-linux-gnu/xtables"]:
        if os.path.isdir(xtdir):
            _xtables_libdir = xtdir
            break
if _xtables_libdir is None:
    raise XTablesError("can't find directory with extensions; "
                       "please set XTABLES_LIBDIR")
```

I've restarted the minion and I'm currently watching the logs to see if this resolves the issue.

**Comment by Linuturk** [comment]
So, the issue hasn't presented itself after modifying that file. What are our next steps? Is this core to Salt, or is there an upstream where I should be reporting this? Perhaps salt should be overriding the environment variable?

**Comment by frogunder** [comment]
@saltstack/team-core can you give some feedback when you have time, thanks.
