### ISSUE TITLE
Document self-contained Windows salt-minion

### ISSUE THREAD

**Issue by marbx** [saltstack/salt#55179]
This issue is intended to discuss the Windows instructions of
https://docs.saltstack.com/en/latest/topics/development/hacking.html#running-a-self-contained-development-version 

# Instructions 

Install python-2.7.15.amd64.msi to c:\Python27

Git checkout master

Install virtualenv

    \Python27\Scripts\pip.exe install virtualenv

Create a new virtualenv
    
    \Python27\Scripts\virtualenv \saltve27

Activate the virtualenv 

    \saltve27\Scripts\activate

Install Microsoft Visual C++ Compiler for Python 2.7

    https://www.microsoft.com/en-us/download/details.aspx?id=44266

Install libraries (ignore setproctitle)

    pip install -r \git\salt\pkg\windows\req.txt

Install Salt 

    pip install -e \git\salt

Create pki dir

    mkdir \saltve27\etc\salt\pki\minion

Add two settings to the `\saltve27\etc\salt\minion` file (you must add the drive letter)

    root_dir: C:\saltve27
    pki_dir: C:\saltve27\etc\salt\pki\minion

Make local call (observe double quotes)

    salt-call --local cmd.run "dir"
    salt-call --local cmd.run "ver"
    salt-call --local cmd.run "echo hello world"
    salt-call --local cmd.run "echo %temp%"
    salt-call --local cmd.run "dir \"c:\Program Files\""

**Comment by markuskramerIgitt** [comment]
# Errors

Above instructions result in 2 ERRORS

```
[ERROR   ] Unable to import Python wmi module, some core grains will be missing
Traceback (most recent call last):
  File "c:\git\salt\salt\grains\core.py", line 90, in <module>
    import wmi  # pylint: disable=import-error
ImportError: No module named wmi
Traceback (most recent call last):
[  File "C:\saltve27\Scripts\salt-minion-script.py", line 11, in <module>
ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'module' object has no attribute 'winapi'
Traceback (most recent call last):
  File "C:\saltve27\Scripts\salt-minion-script.py", line 11, in <module>
    load_entry_point('salt', 'console_scripts', 'salt-minion')()
  File "c:\git\salt\salt\scripts.py", line 191, in salt_minion
    minion.start()
  File "c:\git\salt\salt\cli\daemons.py", line 326, in start
    self._real_start()
  File "c:\git\salt\salt\cli\daemons.py", line 338, in _real_start
    self.minion.tune_in()
  File "c:\git\salt\salt\minion.py", line 1065, in tune_in
    self._spawn_minions()
  File "c:\git\salt\salt\minion.py", line 1009, in _spawn_minions
    jid_queue=self.jid_queue)
  File "c:\git\salt\salt\minion.py", line 977, in _create_minion_object
    jid_queue=jid_queue)
  File "c:\git\salt\salt\minion.py", line 1136, in __init__
    self.opts['grains'] = salt.loader.grains(opts)
  File "c:\git\salt\salt\loader.py", line 786, in grains
    ret = funcs[key]()
  File "c:\git\salt\salt\grains\core.py", line 2361, in hwaddr_interfaces
    ifaces = _get_interfaces()
  File "c:\git\salt\salt\grains\core.py", line 1539, in _get_interfaces
    _INTERFACES = salt.utils.network.interfaces()
  File "c:\git\salt\salt\utils\network.py", line 1052, in interfaces
    return win_interfaces()
  File "c:\git\salt\salt\utils\network.py", line 1005, in win_interfaces
    with salt.utils.winapi.Com():
AttributeError: 'module' object has no attribute 'winapi'
    load_entry_point('salt', 'console_scripts', 'salt-minion')()
  File "c:\git\salt\salt\scripts.py", line 191, in salt_minion
    minion.start()
  File "c:\git\salt\salt\cli\daemons.py", line 326, in start
    self._real_start()
  File "c:\git\salt\salt\cli\daemons.py", line 338, in _real_start
    self.minion.tune_in()
  File "c:\git\salt\salt\minion.py", line 1065, in tune_in
    self._spawn_minions()
  File "c:\git\salt\salt\minion.py", line 1009, in _spawn_minions
    jid_queue=self.jid_queue)
  File "c:\git\salt\salt\minion.py", line 977, in _create_minion_object
    jid_queue=jid_queue)
  File "c:\git\salt\salt\minion.py", line 1136, in __init__
    self.opts['grains'] = salt.loader.grains(opts)
  File "c:\git\salt\salt\loader.py", line 786, in grains
    ret = funcs[key]()
  File "c:\git\salt\salt\grains\core.py", line 2361, in hwaddr_interfaces
    ifaces = _get_interfaces()
  File "c:\git\salt\salt\grains\core.py", line 1539, in _get_interfaces
    _INTERFACES = salt.utils.network.interfaces()
  File "c:\git\salt\salt\utils\network.py", line 1052, in interfaces
    return win_interfaces()
  File "c:\git\salt\salt\utils\network.py", line 1005, in win_interfaces
    with salt.utils.winapi.Com():
AttributeError: 'module' object has no attribute 'winapi'

```

**Comment by frogunder** [comment]
@markuskramerIgitt Thank you for reporting this issue.

@saltstack/team-windows Any thoughts on this one?

**Comment by markuskramerIgitt** [comment]
@frogunder The instructions seems to be complete, by adding `pip install -r \git\salt\pkg\windows\req.txt`

**Comment by markuskramerIgitt** [comment]
A configuration problems remains: I cannot contact the master


# Error

    [ERROR   ] Minion unable to successfully connect to a Salt Master.

**Comment by markuskramerIgitt** [comment]
I noted these files in c:\saltve27\saltve27\etc\salt\pki\minion
 - minion.pem
 - minion.pub


I would have expected them at c:\saltve27\etc\salt\pki\minion which remains empty

**Comment by markuskramerIgitt** [comment]
# Error when trying Python3

```
  Building wheel for setproctitle (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\saltve36\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Markus\\AppData\\Local\\Temp\\pip-install-l39q64__\\setproctitle\\setup.py'"'"'; __file__='"'"'C:\\Users\\Markus\\AppData\\Local\\Temp\\pip-install-l39q64__\\setproctitle\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Markus\AppData\Local\Temp\pip-wheel-ks4289df' --python-tag cp36
       cwd: C:\Users\Markus\AppData\Local\Temp\pip-install-l39q64__\setproctitle\
  Complete output (5 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'setproctitle' extension
  error: [WinError 3] The system cannot find the path specified: 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\PlatformSDK\\lib'
  ----------------------------------------
  ERROR: Failed building wheel for setproctitle
  Running setup.py clean for setproctitle
  Building wheel for timelib (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\saltve36\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Markus\\AppData\\Local\\Temp\\pip-install-l39q64__\\timelib\\setup.py'"'"'; __file__='"'"'C:\\Users\\Markus\\AppData\\Local\\Temp\\pip-install-l39q64__\\timelib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Markus\AppData\Local\Temp\pip-wheel-zwtur6zk' --python-tag cp36
       cwd: C:\Users\Markus\AppData\Local\Temp\pip-install-l39q64__\timelib\
  Complete output (5 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'timelib' extension
  error: [WinError 3] The system cannot find the path specified: 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\PlatformSDK\\lib'
  ----------------------------------------
  ERROR: Failed building wheel for timelib

```

Maybe ....

https://stackoverflow.com/questions/51476784/how-to-install-visual-studio-2015-platformsdk-now

**Comment by markuskramerIgitt** [comment]
Not stale

**Comment by markuskramerIgitt** [comment]
Not stale

**Comment by waynew** [comment]
@markuskramerIgitt is this a documentation issue?

**Comment by markuskramerIgitt** [comment]
> @markuskramerIgitt is this a documentation issue?

Yes

**Comment by marbx** [comment]
This is no longer an issue for me
