### ISSUE TITLE
Can't configure twilio profile via master config as per docs 

### ISSUE THREAD

**Issue by jtraub91** [saltstack/salt#55198]
### Description of Issue
The [docs](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.twilio_notify.html) indicate that we can define the twilio profile via the master config. This is not the case. Furthermore, a typo seems to be present in the doc as the profile is defined as 'my-twilio-account' but the cli usage example uses 'twilio-account'

### Setup
Normal salt installation. Place the following in the master config:
```
# /etc/salt/master
twilio_profile:
  twilio.account_sid: <removed-for-privacy>
  twilio.auth_token: <removed-for-privacy>
```
Restart the salt-master process

### Steps to Reproduce Issue
```
# salt \* twilio.send_sms twilio_profile "Test message" '<to-phone-number>' '<from-phone-number>'
ubuntu-salt-test:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1664, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/twilio_notify.py", line 81, in send_sms
        client = _get_twilio(profile)
      File "/usr/lib/python2.7/dist-packages/salt/modules/twilio_notify.py", line 63, in _get_twilio
        creds.get('twilio.account_sid'),
    AttributeError: 'unicode' object has no attribute 'get'
```

Put the twilio_profile above in the minion config instead (/etc/salt/minion)

```
# salt \* twilio.send_sms twilio_profile "Test message" '<to-phone-number>' '<from-phone-number>'
ubuntu-salt-test:
    ----------
    message:
        ----------
        body:
            Sent from your Twilio trial account - Test message
        date_created:
            2019-11-04 22:05:39+00:00
        date_sent:
            None
        num_segments:
            1
        price:
            None
        price_unit:
            USD
        sid:
            xxxxxxxxxxxxxxxxxx
        status:
            queued
```

### Versions Report
```
# salt --versions-report
Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15+ (default, Oct  7 2019, 17:39:04)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 5.0.0-32-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```

**Comment by Ch3LL** [comment]
If this is set in the master config and `pillar_opts` is set to True then it will work. Probably would help to clarify that. I would not recommend to set `pillar_opts` to true as it can be considered insecure as it copies over all of master opts into pillar. Did you want to push a PR to make these doc changes you mentioned or i can?

**Comment by jtraub91** [comment]
https://github.com/saltstack/salt/pull/55215

I haven't done much with docs before, but I assume they will build automatically from the new docstrings? Let me know if this will suffice and if the clarification is good. Thanks :)

**Comment by Ch3LL** [comment]
thanks! i just left a couple suggestions. yes once that is merged the docs should build from that PR. i'll go ahead and close this issue and we can keep the conversation in the PR if any more discussion is needed. Thanks once again :)
