### ISSUE TITLE
Compund matches trigger an exception in 2018.3.4-py2 master

### ISSUE THREAD

**Issue by lubyou** [saltstack/salt#55204]
Hi,

I have a 2018.3.4 master and 2018.3.4 and 2017.7.8 minions, python2 for both the master and the minions.

Almost all of the minions are running on various versions of Windows (7, 10, 2008R2-2016), the majority of them on non English systems.

Whenever I try to use compound matches, the minions do not return ("Minion did not return. [No response]"), and the master throws an exception:

`sudo salt -C "G@saltversion:2017.7.8" test.ping -t30`

```
[DEBUG   ] Attempting to match '2017.7.8' in 'saltversion' using delimiter ':'
[DEBUG   ] Evaluating final compound matching expr: set([u'p-018-659e2fa1-3d7f-40df-ada1-99844794eb98.domain.tld', u'gfr-app.domain.tld', u'p-358-5925b577-c7e0-4ebd-af8a-60acc978e2c5.domain.tld', u'p-070-9885637e-cf28-466b-abdd-9acc0e3b1477.domain.tld', u'desktop-2lpf4io-cef1543f-602e-4afe-99a8-56b083d9f1c3.domain.tld', u'xxx-pc-a432be00-2f3f-47d0-bbe4-a8321a632e08.salt.sub.domain.tld', u'p-059-b9767038-acb2-4b1c-b894-2328d216c524.domain.tld', u'windows-vm-1bfdf941-8fe5-4e36-a87c-0ea33a536d5a.domain.tld', u'p-356.domain.tld', u'p-025-a09236be-03dc-459e-881f-7f7ccfaa6abe.domain.tld', u'p-030-2fea342a-7072-4735-b3a8-734727dd058a.domain.tld', u'p-042-33e3a145-1109-4108-96da-6d0141aed5c1.domain.tld', u'pguettrot-pc-f7894508-2e90-491b-b289-e734ae83caca.salt.sub.domain.tld', u'p-095-5743f77c-4855-4195-99ff-81786ce69eae.salt.sub.domain.tld', u'p-016-c828bf6b-3c02-4451-93e5-baf5b788aab7.domain.tld'])
[DEBUG   ] Sending event: tag = 20191105134203815485; data = {u'_stamp': '2019-11-05T12:42:03.816118', u'minions': [u'p-018-659e2fa1-3d7f-40df-ada1-99844794eb98.domain.tld', u'gfr-app.domain.tld', u'p-358-5925b577-c7e0-4ebd-af8a-60acc978e2c5.domain.tld', u'p-070-9885637e-cf28-466b-abdd-9acc0e3b1477.domain.tld', u'desktop-2lpf4io-cef1543f-602e-4afe-99a8-56b083d9f1c3.domain.tld', u'xxx-pc-a432be00-2f3f-47d0-bbe4-a8321a632e08.salt.sub.domain.tld', u'p-059-b9767038-acb2-4b1c-b894-2328d216c524.domain.tld', u'windows-vm-1bfdf941-8fe5-4e36-a87c-0ea33a536d5a.domain.tld', u'p-356.domain.tld', u'p-025-a09236be-03dc-459e-881f-7f7ccfaa6abe.domain.tld', u'p-030-2fea342a-7072-4735-b3a8-734727dd058a.domain.tld', u'p-042-33e3a145-1109-4108-96da-6d0141aed5c1.domain.tld', u'pguettrot-pc-f7894508-2e90-491b-b289-e734ae83caca.salt.sub.domain.tld', u'p-095-5743f77c-4855-4195-99ff-81786ce69eae.salt.sub.domain.tld', u'p-016-c828bf6b-3c02-4451-93e5-baf5b788aab7.domain.tld']}
[DEBUG   ] Gathering reactors for tag 20191105134203815485
[DEBUG   ] Sending event: tag = salt/job/20191105134203815485/new; data = {u'tgt_type': 'compound', u'jid': u'20191105134203815485', u'user': 'sudo_myuser', u'tgt': 'G@saltversion:2017.7.8', u'arg': [], u'fun': 'test.ping', u'missing': [], u'_stamp': '2019-11-05T12:42:03.819640', u'minions': [u'p-018-659e2fa1-3d7f-40df-ada1-99844794eb98.domain.tld', u'gfr-app.domain.tld', u'p-358-5925b577-c7e0-4ebd-af8a-60acc978e2c5.domain.tld', u'p-070-9885637e-cf28-466b-abdd-9acc0e3b1477.domain.tld', u'desktop-2lpf4io-cef1543f-602e-4afe-99a8-56b083d9f1c3.domain.tld', u'xxx-pc-a432be00-2f3f-47d0-bbe4-a8321a632e08.salt.sub.domain.tld', u'p-059-b9767038-acb2-4b1c-b894-2328d216c524.domain.tld', u'windows-vm-1bfdf941-8fe5-4e36-a87c-0ea33a536d5a.domain.tld', u'p-356.domain.tld', u'p-025-a09236be-03dc-459e-881f-7f7ccfaa6abe.domain.tld', u'p-030-2fea342a-7072-4735-b3a8-734727dd058a.domain.tld', u'p-042-33e3a145-1109-4108-96da-6d0141aed5c1.domain.tld', u'pguettrot-pc-f7894508-2e90-491b-b289-e734ae83caca.salt.sub.domain.tld', u'p-095-5743f77c-4855-4195-99ff-81786ce69eae.salt.sub.domain.tld', u'p-016-c828bf6b-3c02-4451-93e5-baf5b788aab7.domain.tld']}
[DEBUG   ] Gathering reactors for tag salt/job/20191105134203815485/new
[DEBUG   ] Adding minions for job 20191105134203815485: [u'p-018-659e2fa1-3d7f-40df-ada1-99844794eb98.domain.tld', u'gfr-app.domain.tld', u'p-358-5925b577-c7e0-4ebd-af8a-60acc978e2c5.domain.tld', u'p-070-9885637e-cf28-466b-abdd-9acc0e3b1477.domain.tld', u'desktop-2lpf4io-cef1543f-602e-4afe-99a8-56b083d9f1c3.domain.tld', u'xxx-pc-a432be00-2f3f-47d0-bbe4-a8321a632e08.salt.sub.domain.tld', u'p-059-b9767038-acb2-4b1c-b894-2328d216c524.domain.tld', u'windows-vm-1bfdf941-8fe5-4e36-a87c-0ea33a536d5a.domain.tld', u'p-356.domain.tld', u'p-025-a09236be-03dc-459e-881f-7f7ccfaa6abe.domain.tld', u'p-030-2fea342a-7072-4735-b3a8-734727dd058a.domain.tld', u'p-042-33e3a145-1109-4108-96da-6d0141aed5c1.domain.tld', u'pguettrot-pc-f7894508-2e90-491b-b289-e734ae83caca.salt.sub.domain.tld', u'p-095-5743f77c-4855-4195-99ff-81786ce69eae.salt.sub.domain.tld', u'p-016-c828bf6b-3c02-4451-93e5-baf5b788aab7.domain.tld']
[INFO    ] User sudo_myuser Published command test.ping with jid 20191105134203815485
[DEBUG   ] Published command details {u'tgt_type': 'compound', u'jid': u'20191105134203815485', u'tgt': 'G@saltversion:2017.7.8', u'ret': '', u'user': 'sudo_myuser', u'arg': [], u'fun': 'test.ping'}
[DEBUG   ] Signing data packet
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] salt.crypt.sign_message: Signing message.
[DEBUG   ] Sending payload to publish daemon. jid=20191105134203815485 size=468
[DEBUG   ] Publish daemon received payload. size=468
Process salt.transport.zeromq.<type 'instancemethod'>._publish_daemon:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 862, in _publish_daemon
    pub_sock.send('broadcast', flags=zmq.SNDMORE)
[DEBUG   ] Sent payload to publish daemon.
  File "zmq/backend/cython/socket.pyx", line 617, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:6625)
  File "zmq/backend/cython/socket.pyx", line 657, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:6300)
TypeError: unicode not allowed, use send_string
[INFO    ] Process <bound method ZeroMQPubServerChannel._publish_daemon of <salt.transport.zeromq.ZeroMQPubServerChannel object at 0x7f7f1893f0d0>> (29432) died with exit status 1, restarting...
```

salt -G 'saltversion:2017.7.8' test.ping -t30 fails as well, while using glob matches works.

The salt minions do have grains that contain diacritics, for example:

```
    timezone:
        (UTC-06:00) América Central
```

Anybody else encountered this particular issue? It was not present in the 2017.7.8 version of the master.

Thank you very much

### Versions Report
```
Salt Version:
           Salt: 2018.3.4

Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.12 (default, Oct  8 2019, 14:14:10)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.4.0-141-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by Ch3LL** [comment]
im having a hard time replicate this. If you target your 2018.3.4 with the compound targeting do you see the same thing?

Also can you try clearing your cache and seeing if that helps?

**Comment by lubyou** [comment]
Hi,

I just tried this:

`sudo salt-run cache.clear_all tgt=\*`
`sudo salt \* saltutil.refresh_grains`
`sudo salt -C "G@saltversion:2017.7.8" test.ping`

The result was unfortunately the same as in the original post, the mast threw the same exception.

**Comment by lubyou** [comment]
Hi again,

If I set zmq_filtering to false on the master, things work as expected.

**Comment by Ch3LL** [comment]
ahh nice find. yeah that was changed in this PR https://github.com/saltstack/salt/pull/48881

any chance you can verify that does indeed fix it for you?

**Comment by lubyou** [comment]
Hi,

It does fix the issue for me.

Thanks for your help!
