### ISSUE TITLE
Microsoft Hyper-V Server 2019 1809 - Minion fails to start

### ISSUE THREAD

**Issue by hbonath** [saltstack/salt#55212]
### Description of Issue

Fresh installation of Hyper-V Server 2019
 *(The Free Hyper-V Server, **not** Windows Server 2019 with Hyper-V Role, which can be downloaded here: https://www.microsoft.com/en-us/evalcenter/evaluate-hyper-v-server-2019)*

Salt Minion 2019.2.2  Py3 Fresh Installed using https://winbootstrap.saltstack.com with the following command:

`powershell.exe -file .\bootstrap-salt.ps1 -pythonVersion 3 -minion MY-MINION-NAME -master MY-MASTER-IP`

The minion fails to start, and of course never shows up in the master.

### Setup
Stock, vanilla configuration.

### Steps to Reproduce Issue
Here is the output from starting up the minion in debug mode:
```
PS C:\salt> .\salt-minion-debug.bat
The salt-minion service is not started.

More help is available by typing NET HELPMSG 3521.

[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Multiprocessing queue logging configured for the process running under PID: 2360 at log level 10
[DEBUG   ] Marking 'is_ip' as a jinja filter
[DEBUG   ] Marking 'is_ipv4' as a jinja filter
[DEBUG   ] Marking 'is_ipv6' as a jinja filter
[DEBUG   ] Marking 'ipv4' as a jinja filter
[DEBUG   ] Marking 'ipv6' as a jinja filter
[DEBUG   ] Marking 'ipaddr' as a jinja filter
[DEBUG   ] Marking 'ip_host' as a jinja filter
[DEBUG   ] Marking 'network_hosts' as a jinja filter
[DEBUG   ] Marking 'network_size' as a jinja filter
[DEBUG   ] Marking 'gen_mac' as a jinja filter
[DEBUG   ] Marking 'mac_str_to_bytes' as a jinja filter
[DEBUG   ] Marking 'dns_check' as a jinja filter
[DEBUG   ] Multiprocessing queue logging configured for the process running under PID: 2360 at log level 10
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] Setting up the Salt Minion "MY-MINION-NAME"
[DEBUG   ] Marking 'base64_encode' as a jinja filter
[DEBUG   ] Marking 'base64_decode' as a jinja filter
[DEBUG   ] Marking 'md5' as a jinja filter
[DEBUG   ] Marking 'sha256' as a jinja filter
[DEBUG   ] Marking 'sha512' as a jinja filter
[DEBUG   ] Marking 'hmac' as a jinja filter
[DEBUG   ] Marking 'random_hash' as a jinja filter
[DEBUG   ] Marking 'rand_str' as a jinja filter
[DEBUG   ] Marking 'file_hashsum' as a jinja filter
[DEBUG   ] Marking 'http_query' as a jinja filter
[DEBUG   ] Marking 'strftime' as a jinja filter
[DEBUG   ] Marking 'date_format' as a jinja filter
[DEBUG   ] Marking 'yaml_dquote' as a jinja filter
[DEBUG   ] Marking 'yaml_squote' as a jinja filter
[DEBUG   ] Marking 'yaml_encode' as a jinja filter
[DEBUG   ] Marking 'raise' as a jinja global
[DEBUG   ] Marking 'match' as a jinja test
[DEBUG   ] Marking 'equalto' as a jinja test
[DEBUG   ] Marking 'skip' as a jinja filter
[DEBUG   ] Marking 'sequence' as a jinja filter
[DEBUG   ] Marking 'to_bool' as a jinja filter
[DEBUG   ] Marking 'tojson' as a jinja filter
[DEBUG   ] Marking 'quote' as a jinja filter
[DEBUG   ] Marking 'regex_escape' as a jinja filter
[DEBUG   ] Marking 'regex_search' as a jinja filter
[DEBUG   ] Marking 'regex_match' as a jinja filter
[DEBUG   ] Marking 'regex_replace' as a jinja filter
[DEBUG   ] Marking 'uuid' as a jinja filter
[DEBUG   ] Marking 'unique' as a jinja filter
[DEBUG   ] Marking 'min' as a jinja filter
[DEBUG   ] Marking 'max' as a jinja filter
[DEBUG   ] Marking 'avg' as a jinja filter
[DEBUG   ] Marking 'union' as a jinja filter
[DEBUG   ] Marking 'intersect' as a jinja filter
[DEBUG   ] Marking 'difference' as a jinja filter
[DEBUG   ] Marking 'symmetric_difference' as a jinja filter
[DEBUG   ] Created pidfile: c:\salt\var\run\salt-minion.pid
[INFO    ] Starting up the Salt Minion
[DEBUG   ] AsyncEventPublisher PUB socket URI: 4510
[DEBUG   ] AsyncEventPublisher PULL socket URI: 4511
[INFO    ] Starting pull socket on 4511
[DEBUG   ] SaltEvent PUB socket URI: 4510
[DEBUG   ] SaltEvent PULL socket URI: 4511
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Motherboard info not available on this system
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-minion", line 26, in <module>
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-minion", line 26, in <module>
    salt_minion()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 191, in salt_minion
    minion.start()
  File "C:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 346, in start
    self._real_start()
  File "C:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 358, in _real_start
    self.minion.tune_in()
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 1065, in tune_in
    self._spawn_minions()
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 1009, in _spawn_minions
    jid_queue=self.jid_queue)
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 977, in _create_minion_object
    jid_queue=jid_queue)
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 1136, in __init__
    self.opts['grains'] = salt.loader.grains(opts)
  File "C:\salt\bin\lib\site-packages\salt\loader.py", line 784, in grains
    ret = funcs[key]()
  File "C:\salt\bin\lib\site-packages\salt\grains\core.py", line 1662, in os_data
    if 'Server' in grains['osrelease']:
TypeError: argument of type 'NoneType' is not iterable    salt_minion()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 191, in salt_minion

    minion.start()
  File "C:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 346, in start
    self._real_start()
  File "C:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 358, in _real_start
    self.minion.tune_in()
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 1065, in tune_in
    self._spawn_minions()
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 1009, in _spawn_minions
    jid_queue=self.jid_queue)
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 977, in _create_minion_object
    jid_queue=jid_queue)
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 1136, in __init__
    self.opts['grains'] = salt.loader.grains(opts)
  File "C:\salt\bin\lib\site-packages\salt\loader.py", line 784, in grains
    ret = funcs[key]()
  File "C:\salt\bin\lib\site-packages\salt\grains\core.py", line 1662, in os_data
    if 'Server' in grains['osrelease']:
TypeError: argument of type 'NoneType' is not iterable

```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
#### Minion:
```
Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: 1.12.2
       cherrypy: 17.4.1
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.6
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: Not Installed
   pycryptodome: 3.8.1
         pygit2: Not Installed
         Python: 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.4
         PyYAML: 3.13
          PyZMQ: 18.0.1
           RAET: Not Installed
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2019Server
         system: Windows
        version: 2019Server 10.0.17763 SP0 Multiprocessor Free
```

**Comment by Ch3LL** [comment]
what if you install with the windows packages? Do you still see the same behavior. Trying to narrow it down to the windows bootstrap script or windows running on that particular os.

**Comment by hbonath** [comment]
Thanks for your response.

I believe that I've narrowed it down to the behavior in [grains.py](https://github.com/saltstack/salt/blob/master/salt/grains/core.py) as I had the same behavior with a standard Windows Packaged installation of the salt minion.

Someone was helping me in #salt on Freenode and gave me some [code to test with](https://paste.fedoraproject.org/paste/hMUs5gV~gdTqKTmD0B7c7g) as I am not much of a dev. 

I did some experimenting on my own and I believe that the issue is caused due to the fact that the value returned by `osinfo.Caption` in the WMI Request made in function **_windows_platform_data:**  `osinfo = wmi_c.Win32_OperatingSystem()[0]` outputs simply `'Microsoft Hyper-V Server'` on this version of Windows.

If I execute the same command of `osinfo.Caption` on a Hyper-V 2016 machine, the output I get is `'Microsoft Hyper-V Server 2016'` and from a normal Windows Server 2019 I get `'Microsoft Windows Server 2019 Datacenter'` 

What I'm thinking is that something in here is looking for the "Year" nomenclature that Microsoft has been using for Server editions, and they of course broke the assumption used around [here](https://github.com/saltstack/salt/blob/master/salt/grains/core.py#L1203) is where we need to be looking.

Hopefully this is something that someone more familiar with Python can quickly identify and solve, I am happy to provide as much information as possible to help get this working.

**Comment by hbonath** [comment]
Ok to update, I was able to do some hacking and I got this to work, the issue is exactly because the `osinfo.Caption` for this edition of Windows is "Microsoft Hyper-V Server" and does not contain the Year nomenclature used by seemingly all Windows Server editions up to this point.

Here's is a diff of what I added to grains\core.py:

```
--- core.py	2019-07-26 14:20:44.000000000 -0400
+++ core.py	2019-11-07 20:51:28.610299000 -0500
@@ -1205,14 +1205,19 @@
     version = 'Unknown'
     release = ''
     if 'Server' in caption:
-        for item in caption.split(' '):
-            # If it's all digits, then it's version
-            if re.match(r'\d+', item):
-                version = item
-            # If it starts with R and then numbers, it's the release
-            # ie: R2
-            if re.match(r'^R\d+$', item):
-                release = item
+        # Check if it is specifically "Microsoft Hyper-V Server"
+        # as Hyper-V 2019 does not contain the Year
+        if re.match(r'^Microsoft Hyper-V Server$', caption):
+            version = '2019'
+        else:
+            for item in caption.split(' '):
+                # If it's all digits, then it's version
+                if re.match(r'\d+', item):
+                    version = item
+                # If it starts with R and then numbers, it's the release
+                # ie: R2
+                if re.match(r'^R\d+$', item):
+                    release = item
         os_release = '{0}Server{1}'.format(version, release)
     else:
         for item in caption.split(' '):
```

I'm not sure if this "fix" is kosher, but I did test it against several other Windows OSs in my lab and they all continued to report their versions correctly.

**Comment by Ch3LL** [comment]
ping @twangboy you okay with the fix above?

**Comment by sagetherage** [comment]
@xeacott can you review this?

**Comment by hbonath** [comment]
@xeacott That sounds good, so long as that's included in the logic that creates the 'osrelease' grain then that should help solve this at least until Microsoft changes it again!

**Comment by xeacott** [comment]
I should have a PR up in a second and we'll continue the conversation there. @hbonath
