### ISSUE TITLE
cmd.run_all not working as expected with shell=powershell

### ISSUE THREAD

**Issue by gigi206** [saltstack/salt#55213]
### Description of Issue
Module **cmd.run_all** seems not working as expected with the shell powershell

### Steps to Reproduce Issue
No problem with the **cmd** shell:
```
$ salt-call cmd.run_all "['echo', 'salt']" python_shell=False shell='cmd'
local:
    ----------
    pid:
        14916
    retcode:
        0
    stderr:
    stdout:
        salt
```

But it seems there is a problem with powershell:
```
$ salt-call cmd.run_all "['echo', 'salt']" python_shell=False shell='powershell'
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'list' object has no attribute 'replace'
Traceback (most recent call last):
  File "C:\VSCode-Anywherex\apps\saltstack\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "C:\VSCode-Anywherex\apps\saltstack\bin\lib\site-packages\salt\scripts.py", line 431, in salt_call
    client.run()
  File "C:\VSCode-Anywherex\apps\saltstack\bin\lib\site-packages\salt\cli\call.py", line 57, in run
    caller.run()
  File "C:\VSCode-Anywherex\apps\saltstack\bin\lib\site-packages\salt\cli\caller.py", line 138, in run
    ret = self.call()
  File "C:\VSCode-Anywherex\apps\saltstack\bin\lib\site-packages\salt\cli\caller.py", line 237, in call
    ret['return'] = self.minion.executors[fname](self.opts, data, func, args, kwargs)
  File "C:\VSCode-Anywherex\apps\saltstack\bin\lib\site-packages\salt\executors\direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "C:\VSCode-Anywherex\apps\saltstack\bin\lib\site-packages\salt\modules\cmdmod.py", line 2084, in run_all
    **kwargs)
  File "C:\VSCode-Anywherex\apps\saltstack\bin\lib\site-packages\salt\modules\cmdmod.py", line 351, in _run
    cmd = 'Powershell -NonInteractive -NoProfile "{0}"'.format(cmd.replace('"', '\\"'))
AttributeError: 'list' object has no attribute 'replace'
Traceback (most recent call last):
  File "C:\VSCode-Anywherex\apps\saltstack\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "C:\VSCode-Anywherex\apps\saltstack\bin\lib\site-packages\salt\scripts.py", line 431, in salt_call
    client.run()
  File "C:\VSCode-Anywherex\apps\saltstack\bin\lib\site-packages\salt\cli\call.py", line 57, in run
    caller.run()
  File "C:\VSCode-Anywherex\apps\saltstack\bin\lib\site-packages\salt\cli\caller.py", line 138, in run
    ret = self.call()
  File "C:\VSCode-Anywherex\apps\saltstack\bin\lib\site-packages\salt\cli\caller.py", line 237, in call
    ret['return'] = self.minion.executors[fname](self.opts, data, func, args, kwargs)
  File "C:\VSCode-Anywherex\apps\saltstack\bin\lib\site-packages\salt\executors\direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "C:\VSCode-Anywherex\apps\saltstack\bin\lib\site-packages\salt\modules\cmdmod.py", line 2084, in run_all
    **kwargs)
  File "C:\VSCode-Anywherex\apps\saltstack\bin\lib\site-packages\salt\modules\cmdmod.py", line 351, in _run
    cmd = 'Powershell -NonInteractive -NoProfile "{0}"'.format(cmd.replace('"', '\\"'))
AttributeError: 'list' object has no attribute 'replace'
```

### Versions Report
```
$ salt-call --versions-report
Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: 1.12.2
       cherrypy: 17.4.1
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.6
      gitpython: 2.1.10
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: Not Installed
   pycryptodome: 3.8.1
         pygit2: Not Installed
         Python: 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.4
         PyYAML: 3.13
          PyZMQ: 18.0.1
           RAET: Not Installed
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 10
         system: Windows
        version: 10 10.0.18362 SP0 Multiprocessor Free
```

**Comment by Ch3LL** [comment]
looks like its trying to run a replcae on your cmd which is a list, which is why its not working. Was this working previously? I'm actually  not able to get the cmd shell to work either although im on windows server 2016.

**Comment by gigi206** [comment]
I know that in the documentation a string is printed as expected but in a lot your source code I show that a list is used.
On example here : https://github.com/saltstack/salt/blob/01b9405b61cd416d4c852c87bd484759f5ec9c96/salt/modules/xfs.py#L205

That's why I open the bug and I have also used a list in y custom  modules but a change the shell tp powershell and now I have this traceback

**Comment by Ch3LL** [comment]
looks like i can run it just fine on linux terminal as well. looks like we need to get this fixed up.

ping @saltstack/team-windows anyone want to take a stab at a fix here?
