### ISSUE TITLE
salt-cloud -Q crashes if an OpenStack instance has no image

### ISSUE THREAD

**Issue by vdloo** [saltstack/salt#55229]
It is possible for an OpenStack instance to have no image
![image_000](https://user-images.githubusercontent.com/1437341/68400887-0f71ac80-0179-11ea-8bf0-7deacbfcb682.png)

When you run `salt-cloud -Q` in this scenario the OpenStack driver crashes like this:
```
salt-cloud -Q -l debug
...
[DEBUG   ] LazyLoaded cloud.is_public_ip
[DEBUG   ] Failed to execute 'openstack.list_nodes()' while querying for running nodes: 'dict' object has no attribute 'name'
Traceback (most recent call last):
  File "/srv/releases/1/venv/lib/python3.7/site-packages/salt/cloud/__init__.py", line 2414, in run_parallel_map_providers_query
    cloud.clouds[data['fun']]()
  File "/srv/releases/1/venv/lib/python3.7/site-packages/salt/cloud/clouds/openstack.py", line 342, in list_nodes
    for node, info in list_nodes_full(conn=conn).items():
  File "/srv/releases/1/venv/lib/python3.7/site-packages/salt/cloud/clouds/openstack.py", line 413, in list_nodes_full
    ret[node.name]['image'] = node.image.name
AttributeError: 'dict' object has no attribute 'name'
```

Without `-l debug` it will just show you the query result of other connected clouds, it doesn't warn you it crashed.
```
(venv) root@staging-00f91e48-2019-11-07-10-47-13-saltmaster1 /srv/saltyparrot # salt-cloud -Q
[WARNING ] /srv/releases/1/venv/lib/python3.7/site-packages/salt/utils/xmlutil.py:30: DeprecationWarning: This method will be removed in future versions.  Use 'list(elem)' or iteration over elem instead.
  if len(xmltree.getchildren()) < 1:

aws:
    ----------
    ec2:
        ----------
        staging-00f91e48-2019-11-07-10-47-13-hes:
            ----------
            id:
                i-abcde
            image:
                ami-abcde
            name:
                staging-00f91e48-2019-11-07-10-47-13-hes
            private_ips:
                1.2.3.4
            public_ips:
                2.3.4.5
            size:
                t2.medium
            state:
                running
```

**Comment by vdloo** [comment]
Ah looks like this was already fixed in a later version, in master this is already taken care of https://github.com/saltstack/salt/blob/aee25f641377e6c911a7e3c83ca25c5b988d9431/salt/cloud/clouds/openstack.py#L427

closing
