### ISSUE TITLE
Salt not listening on port 4506

### ISSUE THREAD

**Issue by sadeghsolati** [saltstack/salt#55224]
### Description of Issue
My salt master is not listening on port 4506

### Steps to Reproduce Issue
Setting max_threads: 15 caused the issue.  removing it solved it.

```
salt-master[65037]: TypeError: an integer is required
salt-master[65037]: Process salt.transport.zeromq.<type 'instancemethod'>.zmq_device:
salt-master[65037]: Traceback (most recent call last):
salt-master[65037]: File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
salt-master[65037]: self.run()
salt-master[65037]: File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
salt-master[65037]: self._target(*self._args, **self._kwargs)
salt-master[65037]: File "/usr/lib/python2.7/site-packages/salt/transport/zeromq.py", line 588, in zmq_device
salt-master[65037]: self.context = zmq.Context(self.opts['worker_threads'])
salt-master[65037]: File "context.pyx", line 35, in zmq.backend.cython.context.Context.__cinit__ (zmq/backend/cython/context.c:1023)
salt-master[65037]: TypeError: an integer is required
```

```
### Versions Report
Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.26.3
        libnacl: Not Installed
       M2Crypto: 0.31.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: 3.7.3
         pygit2: 0.26.4
         Python: 2.7.5 (default, Jun 11 2019, 14:33:56)
   python-gnupg: 0.4.3
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.7 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1062.1.2.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.7 Maipo
```

**Comment by Ch3LL** [comment]
can you clarify when you see this traceback?

I simple set `max_threads: 15` in my master config and started up the master `salt-master -ldebug` and everything works fine.

**Comment by sadeghsolati** [comment]
It kept printing every few seconds.  I had a backup of my old config and and diff showed only one difference which was max_threads. commenting it out and restart fixed it. the only special point in my config is external pillars.

**Comment by Ch3LL** [comment]
im still having a hard time replicating this. if you setup the salt-master on a new clean VM do you still see the same error?
