### ISSUE TITLE
iptables-legacy warning message causes an KeyError exception in modules.iptables

### ISSUE THREAD

**Issue by jdelic** [saltstack/salt#55262]
Debian Buster has switched to `iptables-nft` as default. However if anything on the system adds iptables rules (in my case it's the Concourse build server, but simply installing docker.io on Debian Buster will probably suffice to see the problem in action), iptables-nft will output the following message:

```
$ iptables -L -v -n
[...]
Chain DOCKER-USER (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere
# Warning: iptables-legacy tables present, use iptables-legacy to see them
```

This leads to the following exception:

```
          ID: opensmtpd-relay-out465-send
    Function: iptables.append
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 1933, in call
                  **cdata['kwargs'])
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 1951, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/iptables.py", line 442, in append
                  _rules = __salt__['iptables.get_rules'](family=family)
                File "/usr/lib/python3/dist-packages/salt/modules/iptables.py line 578, in get_rules
                  return _parse_conf(in_mem=True, family=family)
                File "/usr/lib/python3/dist-packages/salt/modules/iptables.py", line 1048, in _parse_conf
                  ret[table][chain[0]]['rules'].append(ret_args)
              KeyError: 'OUTP# Warning: iptables-legacy tables present, use iptables-legacy-save to see them'
```

### Steps to Reproduce Issue
1. Use any distro that has switched to iptables-nft
2. Add an iptables rule using the `iptables-legacy` command
3. observe the state fail

### Versions Report
```
Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.11
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.3 (default, Apr  3 2019, 05:39:12)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist: debian 10.1
         locale: UTF-8
        machine: x86_64
        release: 4.19.0-6-amd64
         system: Linux
        version: debian 10.1
```

**Comment by xeacott** [comment]
Thanks for submitting! Although I'm not an expert on this, maybe someone else on @saltstack/team-core can address the issue because although I can address the KeyError, there may be some deeper understanding about the issue itself and why we're seeing it!

**Comment by jdelic** [comment]
### Impact
This bug means that the installation of random packages which use iptables-legacy can break Salt on some platforms as soon as the package is installed. This halted my rollout of Debian Buster.

### Fix
The pragmatic fix would be to first just filter "comments" (starting with `#`) from the output (or perhaps just ignore `iptables` output on `stderr` altogether?).

The better long term fix would probably be to change the `*tables` modules so they understand this output and provide a unified view to Salt so the legacy rules can be managed from Salt.

In any case, from my point of view this is a platform-breaking bug that deserves a quick fix in the 2019.2 series.

**Comment by jdelic** [comment]
I would implore @saltstack/team-core to take a look at this.

**Comment by jdelic** [comment]
@xeacott is there any way to proceed with this ticket?

**Comment by waynew** [comment]
Filtering the comments from iptables output seems like the correct thing to do. I'm fairly certain that there are other states/modules out there that do the same thing.

**Comment by jdelic** [comment]
this is still an issue and should be fixed.

**Comment by jdelic** [comment]
@DmitryKuzmenko 
I have found the actual root cause of this!

Looking into `/etc/iptables/rules.v4` created by setting `save: True` on my `iptables.append` states:
```
-A FORWARD -s 10.254.0.0/22 -p tcp -m state --state NEW -m tcp --dport 443 -j ACCEPT
-A FORWARD -s 10.254.0.0/22 -p tcp -m state --state NEW -m tcp --d# Warning: iptables-legacy tables present, use iptables-legacy-save to see them
port 8100 -j ACCEPT
-A FORWARD -s 10.254.0.0/22 -p udp -m state --state NEW -m udp --dport 53 -j ACCEPT
```

This is stderr output from `iptables-save` mixed into this. The reason for that is the strange decision [to redirect stderr into stdout in `cmd.run`](https://github.com/saltstack/salt/blob/5ad847d619c5c80873d0b67f2ffdeff00323968c/salt/modules/cmdmod.py#L1185). When this output lands in the wrong place (for example inside the chain name) then the initially reported exception happens.

The path to fixing this is to revert the decision in cmd.run to redirect stderr. It should probably learn a new argument to allow the caller to specify what they'd like to happen. I could imagine
```python
def run(..., output_capture='mixed'):
    """
    :param output_capture: One of "mixed", "stdout", "stderr" or "dict". 
                           "mixed" is backwards-compatible where all output 
                           ends up in one ``str`` returned. "stdout" returns only 
                           ``stdout``, "stderr" returns only ``stderr`` and "dict" 
                           returns a dictionary with two keys 
                           ``{"stdout": "...", "stderr": "..."}``.
    """
```

I can't imagine this behavior doesn't lead to other problems.

**Comment by DmitryKuzmenko** [comment]
@jdelic thank you for update. I put this to the pipeline.
