### ISSUE TITLE
Creation of Kubernetes Service Fails With Invalid Port

### ISSUE THREAD

**Issue by morinap** [saltstack/salt#55287]
### Description of Issue
Calling `kubernetes.service_present` with any port configuration fails with an error in creating a kubernetes client library object:
```
local:
----------
          ID: web-service
    Function: kubernetes.service_present
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/Users/<redacted>/tools/saltstack/salt/state.py", line 1933, in call
                  **cdata['kwargs'])
                File "/Users/<redacted>/tools/saltstack/salt/loader.py", line 1939, in wrapper
                  return f(*args, **kwargs)
                File "/Users/<redacted>/tools/saltstack/salt/states/kubernetes.py", line 312, in service_present
                  **kwargs)
                File "/Users/<redacted>/tools/saltstack/salt/modules/kubernetesmod.py", line 1070, in create_service
                  saltenv=saltenv)
                File "/Users/<redacted>/tools/saltstack/salt/modules/kubernetesmod.py", line 1464, in __create_object_body
                  spec=spec_creator(spec))
                File "/Users/<redacted>/tools/saltstack/salt/modules/kubernetesmod.py", line 1572, in __dict_to_service_spec
                  kube_port = kubernetes.client.V1ServicePort()
                File "/Users/<redacted>/tools/python/lib/python3.7/site-packages/kubernetes/client/models/v1_service_port.py", line 65, in __init__
                  self.port = port
                File "/Users/<redacted>/tools/python/lib/python3.7/site-packages/kubernetes/client/models/v1_service_port.py", line 138, in port
                  raise ValueError("Invalid value for `port`, must not be `None`")
              ValueError: Invalid value for `port`, must not be `None`
     Started: 09:33:32.025176
    Duration: 24.63 ms
     Changes:
```

### Setup
Example sls:
```
web-service:
  kubernetes.service_present:
    - namespace: default
      metadata:
        name: web-service
      spec:
        selector:
          app: web
        type: NodePort
        ports:
        - port: 3001
          target_port: 80
          protocol: TCP
```

### Steps to Reproduce Issue
Execute the above sls using `state.sls` and receive the error

### Versions Report
This has been reproduced against current develop and 2019.2. It works against 2018.3 because it uses an older version of the Kubernetes python client (3.0.0) for which this call does not fail. For any Kubernetes python client >= 4.0.0, it does fail.

```
Salt Version:
           Salt: 2019.2.0-339-g779bc17

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.8.0
      docker-py: 4.0.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.4 (default, Sep 23 2019, 10:32:33)
   python-gnupg: Not Installed
         PyYAML: 5.1.2
          PyZMQ: 18.1.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 18.7.0
         system: Darwin
        version: 10.14.6 x86_64
```

**Comment by Ch3LL** [comment]
thanks for the PR! i'll go ahead and close the issue here since there is a fix and we will move the conversation over the pr ! thanks once again :)
