### ISSUE TITLE
elasticsearch returner: Cannot load module elasticsearch

### ISSUE THREAD

**Issue by schka17** [saltstack/salt#55283]
### Description of Issue
try to write returns to elasticsearch, but this process fails with 
`2019-11-13 13:01:34,222 [salt.minion      :1749][DEBUG   ][18570] minion return: {'success': True, 'return': '40%', 'retcode': 0, 'jid': '20191113130134110550', 'fun': 'disk.percent', 'fun_args': ['/']}
2019-11-13 13:01:34,224 [salt.utils.lazy  :104 ][DEBUG   ][18570] LazyLoaded elasticsearch.returner
2019-11-13 13:01:34,225 [salt.returners   :188 ][INFO    ][18570] Using default for elasticsearch doc_type
2019-11-13 13:01:34,225 [salt.returners   :188 ][INFO    ][18570] Using default for elasticsearch master_event_index
2019-11-13 13:01:34,225 [salt.returners   :188 ][INFO    ][18570] Using default for elasticsearch master_event_doc_type
2019-11-13 13:01:34,225 [salt.returners   :188 ][INFO    ][18570] Using default for elasticsearch master_job_cache_index
2019-11-13 13:01:34,225 [salt.returners   :188 ][INFO    ][18570] Using default for elasticsearch master_job_cache_doc_type
2019-11-13 13:01:34,229 [py.warnings      :110 ][WARNING ][18570] /usr/lib/python3/dist-packages/salt/utils/path.py:265: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  if not isinstance(exes, collections.Iterable):

2019-11-13 13:01:34,390 [py.warnings      :110 ][WARNING ][18570] /usr/lib/python3/dist-packages/salt/utils/decorators/signature.py:31: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
  *salt.utils.args.get_function_argspec(original_function)

2019-11-13 13:01:34,591 [py.warnings      :110 ][WARNING ][18570] /usr/lib/python3/dist-packages/salt/utils/decorators/signature.py:31: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
  *salt.utils.args.get_function_argspec(original_function)

2019-11-13 13:01:34,655 [py.warnings      :110 ][WARNING ][18570] /usr/lib/python3/dist-packages/salt/utils/decorators/signature.py:31: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
  *salt.utils.args.get_function_argspec(original_function)

2019-11-13 13:01:34,874 [salt.utils.lazy  :104 ][DEBUG   ][18570] LazyLoaded systemd.booted
2019-11-13 13:01:36,925 [salt.loader.salt.int.module.win_dsc:43  ][DEBUG   ][18570] DSC: Only available on Windows systems
2019-11-13 13:01:36,933 [salt.loader.salt.int.module.win_psget:36  ][DEBUG   ][18570] Module PSGet: Only available on Windows systems
2019-11-13 13:01:36,978 [salt.utils.lazy  :104 ][DEBUG   ][18570] LazyLoaded platform.is_windows
2019-11-13 13:01:37,000 [salt.utils.lazy  :107 ][DEBUG   ][18570] Could not LazyLoad elasticsearch.index_exists: 'elasticsearch' __virtual__ returned False: Cannot load module elasticsearch: elasticsearch libraries not found
2019-11-13 13:01:37,000 [salt.minion      :1770][ERROR   ][18570] The return failed for job 20191113130134110550: 'elasticsearch.index_exists'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 1761, in _thread_return
    minion_instance.returners[returner_str](ret)
  File "/usr/lib/python3/dist-packages/salt/returners/elasticsearch_return.py", line 301, in returner
    _ensure_index(index)
  File "/usr/lib/python3/dist-packages/salt/returners/elasticsearch_return.py", line 175, in _ensure_index
    index_exists = __salt__['elasticsearch.index_exists'](index)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1175, in __getitem__
    func = super(LazyLoader, self).__getitem__(item)
  File "/usr/lib/python3/dist-packages/salt/utils/lazy.py", line 108, in __getitem__
    raise KeyError(key)
KeyError: 'elasticsearch.index_exists'
`
using other return options like rawfile.jso are working fine.
Testscript using elasticsearch.py is working as well

### Setup
Master default
minion default with this config in /etc/salt/minion.d/test.conf
`#master: test
log_file: /var/log/salt/minion
log_level_logfile: debug

elasticsearch:
    hosts:
      - "192.168.12.6:9200"
    index_date: True
    number_of_shards: 1
    number_of_replicas: 1
    debug_returner_payload: True
    states_count: True
    states_order_output: True
    states_single_index: True
    functions_blacklist:
      - test.ping
      - saltutil.find_job`
### Steps to Reproduce Issue
run command `salt '*' disk.percent / --return elasticsearch` on master
logoutput:
`2019-11-13 13:01:34,222 [salt.minion      :1749][DEBUG   ][18570] minion return: {'success': True, 'return': '40%', 'retcode': 0, 'jid': '20191113130134110550', 'fun': 'disk.percent', 'fun_args': ['/']}
2019-11-13 13:01:34,224 [salt.utils.lazy  :104 ][DEBUG   ][18570] LazyLoaded elasticsearch.returner
2019-11-13 13:01:34,225 [salt.returners   :188 ][INFO    ][18570] Using default for elasticsearch doc_type
2019-11-13 13:01:34,225 [salt.returners   :188 ][INFO    ][18570] Using default for elasticsearch master_event_index
2019-11-13 13:01:34,225 [salt.returners   :188 ][INFO    ][18570] Using default for elasticsearch master_event_doc_type
2019-11-13 13:01:34,225 [salt.returners   :188 ][INFO    ][18570] Using default for elasticsearch master_job_cache_index
2019-11-13 13:01:34,225 [salt.returners   :188 ][INFO    ][18570] Using default for elasticsearch master_job_cache_doc_type
2019-11-13 13:01:34,229 [py.warnings      :110 ][WARNING ][18570] /usr/lib/python3/dist-packages/salt/utils/path.py:265: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  if not isinstance(exes, collections.Iterable):

2019-11-13 13:01:34,390 [py.warnings      :110 ][WARNING ][18570] /usr/lib/python3/dist-packages/salt/utils/decorators/signature.py:31: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
  *salt.utils.args.get_function_argspec(original_function)

2019-11-13 13:01:34,591 [py.warnings      :110 ][WARNING ][18570] /usr/lib/python3/dist-packages/salt/utils/decorators/signature.py:31: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
  *salt.utils.args.get_function_argspec(original_function)

2019-11-13 13:01:34,655 [py.warnings      :110 ][WARNING ][18570] /usr/lib/python3/dist-packages/salt/utils/decorators/signature.py:31: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
  *salt.utils.args.get_function_argspec(original_function)

2019-11-13 13:01:34,874 [salt.utils.lazy  :104 ][DEBUG   ][18570] LazyLoaded systemd.booted
2019-11-13 13:01:36,925 [salt.loader.salt.int.module.win_dsc:43  ][DEBUG   ][18570] DSC: Only available on Windows systems
2019-11-13 13:01:36,933 [salt.loader.salt.int.module.win_psget:36  ][DEBUG   ][18570] Module PSGet: Only available on Windows systems
2019-11-13 13:01:36,978 [salt.utils.lazy  :104 ][DEBUG   ][18570] LazyLoaded platform.is_windows
2019-11-13 13:01:37,000 [salt.utils.lazy  :107 ][DEBUG   ][18570] Could not LazyLoad elasticsearch.index_exists: 'elasticsearch' __virtual__ returned False: Cannot load module elasticsearch: elasticsearch libraries not found
2019-11-13 13:01:37,000 [salt.minion      :1770][ERROR   ][18570] The return failed for job 20191113130134110550: 'elasticsearch.index_exists'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 1761, in _thread_return
    minion_instance.returners[returner_str](ret)
  File "/usr/lib/python3/dist-packages/salt/returners/elasticsearch_return.py", line 301, in returner
    _ensure_index(index)
  File "/usr/lib/python3/dist-packages/salt/returners/elasticsearch_return.py", line 175, in _ensure_index
    index_exists = __salt__['elasticsearch.index_exists'](index)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1175, in __getitem__
    func = super(LazyLoader, self).__getitem__(item)
  File "/usr/lib/python3/dist-packages/salt/utils/lazy.py", line 108, in __getitem__
    raise KeyError(key)
KeyError: 'elasticsearch.index_exists'
`

### Versions Report
`Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.11
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.16 (default, Apr  6 2019, 01:42:57)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 5.1.1
            ZMQ: 4.3.1

System Versions:
           dist: debian 10.1
         locale: UTF-8
        machine: x86_64
        release: 4.19.0-6-amd64
         system: Linux
        version: debian 10.1`
salt-minion --version
`salt-minion` 2018.3.4 (Oxygen)`

**Comment by schka17** [comment]
solved after upgrading to python3
