### ISSUE TITLE
Kubernetes Secrets Fail To Base64 Encode Under Python 3

### ISSUE THREAD

**Issue by morinap** [saltstack/salt#55292]
### Description of Issue
Kubernetes secrets are not correctly base64 encoded under Python 3. An error is generated:
```
local:
----------
          ID: test-secret
    Function: kubernetes.secret_present
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/Users/<redacted>g/tools/saltstack/salt/state.py", line 1933, in call
                  **cdata['kwargs'])
                File "/Users/<redacted>g/tools/saltstack/salt/loader.py", line 1939, in wrapper
                  return f(*args, **kwargs)
                File "/Users/<redacted>g/tools/saltstack/salt/states/kubernetes.py", line 583, in secret_present
                  **kwargs)
                File "/Users/<redacted>g/tools/saltstack/salt/modules/kubernetesmod.py", line 1358, in replace_secret
                  data[key] = base64.b64encode(data[key])
                File "/Users/<redacted>g/tools/python/lib/python3.7/base64.py", line 58, in b64encode
                  encoded = binascii.b2a_base64(s, newline=False)
              TypeError: a bytes-like object is required, not 'str'
     Started: 13:32:56.827595
    Duration: 22.805 ms
     Changes:
```

### Setup
Example sls:
```
test-secret:
  kubernetes.secret_present:
    - namespace: default
      metadata:
        name: test-secret
      data:
        tls.crt: test cert data
        tls.key: test key data
```

### Steps to Reproduce Issue
Execute the above sls using state.sls and receive the error

### Versions Report
This bug has been reproduced against `develop`, `2018.3`, and `2019.2` branches:
```
Salt Version:
           Salt: 2019.2.0-339-g779bc17

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.8.0
      docker-py: 4.0.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.4 (default, Sep 23 2019, 10:32:33)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 18.1.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 18.7.0
         system: Darwin
        version: 10.14.6 x86_64
```

**Comment by Ch3LL** [comment]
thanks for the PR! since this has a PR i will close this issue here and we can keep the discussion in the PR

**Comment by kau8hik** [comment]
@morinap any update on your PR?
