### ISSUE TITLE
AWS EC2 Metadata grain module issue with user-data

### ISSUE THREAD

**Issue by stelah1423** [saltstack/salt#55298]
### Description of Issue
Recently, I have discovered that `user-data` from the EC2 metadata endpoint is no longer being loaded/parsed correctly. I believe this is because previously this module was expecting that the `Content-Type` being returned from the user-data endpoint, returns `application/octet-stream`, but actually returns `text/plain`. This appears to be related to how the module is calling the endpoint. When calling `user-data`, the type is correct, however, when calling `user-data/`, the content type is just `text/plain`.

```
root@ip-10-251-2-252:/usr/lib/python2.7/dist-packages/salt/grains# curl -I http://169.254.169.254/latest/user-data/
HTTP/1.0 200 OK
Accept-Ranges: bytes
Content-Length: 75
Content-Type: text/plain
Date: Wed, 13 Nov 2019 21:58:32 GMT
Last-Modified: Wed, 13 Nov 2019 21:49:17 GMT
Connection: close
Server: EC2ws

root@ip-10-251-2-252:/usr/lib/python2.7/dist-packages/salt/grains# curl -I http://169.254.169.254/latest/user-data
HTTP/1.0 200 OK
Accept-Ranges: bytes
Content-Length: 75
Content-Type: application/octet-stream
Date: Wed, 13 Nov 2019 21:58:48 GMT
Last-Modified: Wed, 13 Nov 2019 21:49:17 GMT
Connection: close
Server: EC2ws
```

This _was_ working just a week or so ago.. I wonder if something changed on the AWS metadata endpoint. I do have a case open with them to understand if this is intended, or was changed in error.

I do have a simple fix, and plan to open a PR to link to this issue momentarily. We first discovered this error using the latest "2017.7" version of Salt. In efforts to troubleshoot, I deployed a minion with the latest version, and while I no longer get an error trying to load the grains, the user-data is parsed incorrectly.

In earlier versions of salt (2017.7), one will get this error trying to load grains (this error doesn't happen with 2019.2 -- its just loaded incorrectly):
```
salt-call grains.get bootstrap
[CRITICAL] Failed to load grains defined in grain file metadata.metadata in function <function metadata at 0x7f67c96326e0>, error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 747, in grains
    ret = funcs[key]()
  File "/usr/lib/python2.7/dist-packages/salt/grains/metadata.py", line 79, in metadata
    return _search()
  File "/usr/lib/python2.7/dist-packages/salt/grains/metadata.py", line 63, in _search
    ret[line] = _search(prefix=os.path.join(prefix, line + '/'))
  File "/usr/lib/python2.7/dist-packages/salt/grains/metadata.py", line 72, in _search
    ret[line] = json.loads(retdata)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
local:
    True
```
Debugging the minion, I found this error was being raised when trying to parse user-data content, which is what led me to this discovery.

Example:
user_data defined for ec2 instance at launch:
```
#!/bin/bash
touch /tmp/hello_test.txt
# another comment here
# just to test
```

When looking up with grains.get:
```
salt-call --local grains.get user-data
local:
    ----------
    # another comment here:
        #!/bin/bash
        touch /tmp/hello_test.txt
        # another comment here
        # just to test
    # just to test:
        #!/bin/bash
        touch /tmp/hello_test.txt
        # another comment here
        # just to test
    #!/bin/bash:
        #!/bin/bash
        touch /tmp/hello_test.txt
        # another comment here
        # just to test
    touch /tmp/hello_test.txt:
        None
```

### Setup
Minion config:
`metadata_server_grains: True`

### Steps to Reproduce Issue

1. Deploy an ec2 instance with any arbitrary user-data, preferably multiple lines
2. Ensure `metadata_server_grains: True` is set on the minion.
3. Use `grains.get user-data` to retrieve the content
4. The output will likely be a line by line nested output, as opposed to the user-data data that you entered. It looks like each line is added as a key, and the value of each line is the body of the user-data body.

### Versions Report
```
Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Oct  8 2019, 14:14:10)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-1098-aws
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by xeacott** [comment]
Thanks for submitting this ticket and creating a PR. We'll get this reviewed so we'll keep the comments in the PR!

**Comment by stelah1423** [comment]
I'm going to close this issue.. AWS has finally gotten back to me, and it was an unintended change on their end.. This is their response:

```
Service team responded saying that there have been a number of internal updates on an internal project. One of the changes resulted in this behaviour that you are facing. This has been fixed and an update is rolling out world-wide. It is largely complete, with the exception of a small number of zones.
I went on and looked at the internal ticket where this issue is being tracked, and I can see that the status is currently "In Progress". In my test environment, I am able to confirm that the fix has propagated successfully:
[ec2-user@ip-172-31-54-32:~]$ curl -I http://169.254.169.254/latest/user-data 
HTTP/1.0 200 OK
Accept-Ranges: bytes
Content-Length: 515
Content-Type: application/octet-stream
Date: Tue, 19 Nov 2019 07:26:33 GMT
Last-Modified: Tue, 19 Nov 2019 07:15:20 GMT
Connection: close
Server: EC2ws
[ec2-user@ip-172-31-54-32:~]$  curl -I http://169.254.169.254/latest/user-data/ 
HTTP/1.0 200 OK
Accept-Ranges: bytes
Content-Length: 515
Content-Type: application/octet-stream
Date: Tue, 19 Nov 2019 07:26:47 GMT
Last-Modified: Tue, 19 Nov 2019 07:15:20 GMT
Connection: close
Server: EC2ws
Can you please confirm if the fix has propagated on your end?
I am looking forward to your response. Have a pleasant day!
```
It looks like they have fixed this issue, and it wasn't intended. That said, this issue, and its PR is no longer needed.
