### ISSUE TITLE
jinja strftime filter

### ISSUE THREAD

**Issue by xpicio** [saltstack/salt#55303]
Hello i am trying to use jinja strftime and i already installed on master the pip package timelib (with the following command `salt-run salt.cmd pip.install timelib`) but is not working. Here the error:
```
----------
          ID: deploy config
    Function: file.managed
        Name: /opt/smartplugs/user/smartplug.conf
      Result: False
     Comment: Unable to manage file: Jinja error: Unable to parse now. Consider installing timelib
              Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/utils/dateutils.py", line 52, in date_cast
                  date = float(date)
              ValueError: could not convert string to float: 'now'

              During handling of the above exception, another exception occurred:

              Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 394, in render_jinja_tmpl
                  output = template.render(**decoded_context)
                File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
                  return original_render(self, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
                  return self.environment.handle_exception(exc_info, True)
                File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
                  reraise(exc_type, exc_value, tb)
                File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
                  raise value.with_traceback(tb)
                File "<template>", line 3, in top-level template code
                File "/usr/lib/python3/dist-packages/salt/utils/dateutils.py", line 89, in strftime
                  return date_cast(date).strftime(format)
                File "/usr/lib/python3/dist-packages/salt/utils/dateutils.py", line 60, in date_cast
                  'Unable to parse {0}. Consider installing timelib'.format(date))
              RuntimeError: Unable to parse now. Consider installing timelib

              ; line 3

              ---
              #
              # DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
              # generate by SaltStack at {{ "now" | strftime }}    <======================
              #

              enroll_target = thing
              enroll_model = {{ model }}
              enroll_thing = {{ thing_id  }}
              [...]
              ---
     Started: 03:46:48.352275
    Duration: 179.279 ms
     Changes:
```

The state file:
```
deploy SmartPlug's config:
  file.managed:
    - name: /opt/smartplugs/user/smartplug.conf
    - source: salt://temapltes/gtw/smartplug.conf
    - template: jinja
    - context:
        thing_id: {{ grains['id'] }}
        model: {{ pillar['cloudplugs_smartplug']['model_template'][pillar['type']]  }}
        enroll_password: {{ pillar['cloudplugs_smartplug']['enroll_password'] }}
```

The template file:
```
#
# DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
# generate by SaltStack at {{ "now" | strftime }}
#

enroll_target = thing
enroll_model = {{ model }}
enroll_thing = {{ thing_id  }}
enroll_password = {{ enroll_password }}
app_e1 = true
```

```
/srv/salt # salt --versions-report
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: 0.27.4
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: 3.8.2
         pygit2: 0.27.2
         Python: 3.6.8 (default, Apr  8 2019, 18:17:52)
   python-gnupg: Not Installed
         PyYAML: 5.1.1
          PyZMQ: 18.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 4.14.138+
         system: Linux
        version: Not Installed

```

Any idea about to fix it ?

**Comment by Ch3LL** [comment]
can you verify its installed correctly (`python -c "import timelib"`) - `python3 -c "import timelib"` if your python client is pytho3n.

**Comment by xpicio** [comment]
Hello, i'm using python 3, so i tried the command on both the master and the minion and in both cases the module was successfully imported.
Today i did a new test with a new minion and this simple state file:

```
timelib setup:
  pip.installed:
    - name: timelib
    - reload_modules: True

deploy SmartPlug's config:
  file.managed:
    - name: /opt/smartplug/usr/smartplug.conf
    - source: salt://templates/gtw/smartplug.j2
    - template: jinja
    - makedirs: True
    - context:
        model: {{ pillar['cloudplugs']['model_template'][pillar['type']] }}    
        thing_id: {{ pillar['serial'] }}
        enroll_password: {{ pillar['cloudplugs']['enroll_password'] }}
```

applying many times the state file to the minion i got the same error reported on my previous post. I restarted the salt-minion service and applying again the state file everything is working fine.
