### ISSUE TITLE
Unable to list minions from etcd minion data cache

### ISSUE THREAD

**Issue by malletp** [saltstack/salt#55305]
### Description of Issue
When using etcd minion data cache in master/syndics infra, I'm unable to retrieve the list of the minions attached to syndics minions from a master's minion, for example with a mine.get function.

### Setup
One master of master with minions.
Several syndics with minions.
Etcd minion data cache enabled in master of master and syndics.

### Steps to Reproduce Issue
From a minion attached to the MOM, I want to retrieve a mine from minions attached to syndics.
```
salt-call mine.get 'my_grain:my_value' my_mine grain
```

I only get response from minions attached to the MOM and I got this message in master log.
```
2019-11-13 10:24:44,560 [salt.utils.minions:728 ][ERROR   ][14338] Failed matching available minions with grain pattern: my_grain:my_value
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/minions.py", line 715, in check_minions
    _res = check_func(expr, delimiter, greedy)
  File "/usr/lib/python2.7/site-packages/salt/utils/minions.py", line 326, in _check_grain_minions
    return self._check_cache_minions(expr, delimiter, greedy, 'grains')
  File "/usr/lib/python2.7/site-packages/salt/utils/minions.py", line 306, in _check_cache_minions
    mdata = self.cache.fetch('minions/{0}'.format(id_), 'data')
  File "/usr/lib/python2.7/site-packages/salt/cache/__init__.py", line 180, in fetch
    return self.modules[fun](bank, key, **self._kwargs)
  File "/usr/lib/python2.7/site-packages/salt/cache/etcd_cache.py", line 151, in fetch
    etcd_key, exc
SaltCacheError: There was an error reading the key, /salt_cache/minions/minion_id/mine/data: Not a directory : /salt_cache/minions/minion_id/mine
```

### Analysis and quick fix

* In salt/utils/minions.py, _check_cache_minions is used to retrieve the list of minions from cache. _check_cache_minions use cache.list('minions') function from the cache factory.
* In salt/cache/etcd_cache.py, the list function is an alias of the ls function that list recursively all objects under minions bank, not only the list if the minions.

To fix the issue, I have modified in salt/cache/etcd_cache.py the ls function to only return the list of the minions and not all objects stored for each minions.
```pyhton
def ls(bank):
    '''
    Return an iterable object containing all entries stored in the specified
    bank.
    '''
    _init_client()
    path = '{0}/{1}'.format(path_prefix, bank)
    try:
        ret = []
        for child in client.read(path).children:
            ret.append(child.key.split('/', 3)[3])
        return ret
    except Exception as exc:
        raise SaltCacheError(
            'There was an error getting the key "{0}": {1}'.format(
                bank, exc
            )
        )

```

I think we can also remove the _walk function.

### Versions Report

* Master versions report
```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.26.3
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: 3.9.1
         pygit2: 0.26.4
         Python: 2.7.5 (default, Jun 11 2019, 14:33:56)
   python-gnupg: 0.4.4
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.5 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1062.1.2.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.5 Maipo
```
* Minion versions report
```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.31.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: 3.9.0
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  7 2019, 00:51:29)
   python-gnupg: 0.4.4
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1062.1.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core
```

**Comment by Ch3LL** [comment]
does this work correctly when not using etcd but the default cache system?

**Comment by malletp** [comment]
With the default cache system, we can only retrieve mine data for minions attached to the same master.
My need is to retrieve mine data attached to other syndics, that why I use a minion data cache.

Nevertheless, I can reproduce the issue with etcd cache on a single master deployment, and only with etcd cache. I have no issue with default cache system.
