### ISSUE TITLE
Bug (?) in LocalClient.get_cli_returns "ValueError: list.remove(x): x not in list"

### ISSUE THREAD

**Issue by Heiko-san** [saltstack/salt#55301]
### Description of Issue

We have a script using the saltstack python API which worked perfectly under python2 and Salt 2017.7. 
After upgrading the Salt master to 2019.2.2 and python3 it now crashes with the following error:

```
Traceback (most recent call last):
  File "/home/bm-admin/bin/reparierenscript.sh", line 118, in <module>
    default_handler)(target, action, service)
  File "/home/bm-admin/bin/reparierenscript.sh", line 94, in netmodo
    run_salt(target, "netmodo." + action, outputter=None, timeout=120)
  File "/home/bm-admin/bin/reparierenscript.sh", line 42, in run_salt
    timeout=timeout):
  File "/usr/lib/python3/dist-packages/salt/client/__init__.py", line 1018, in get_cli_returns
    self._clean_up_subscriptions(jid)
  File "/usr/lib/python3/dist-packages/salt/client/__init__.py", line 1896, in _clean_up_subscriptions
    self.event.unsubscribe('salt/job/{0}'.format(job_id))
  File "/usr/lib/python3/dist-packages/salt/utils/event.py", line 349, in unsubscribe
    self.pending_tags.remove([tag, match_func])
ValueError: list.remove(x): x not in list
```

It uses some code like:

```
#!/usr/bin/env python3
import salt.client
...

local = salt.client.LocalClient(c_path="/etc/salt/master")
job = local.run_job("myweb*", "test.ping", args=(), tgt_type='compound', timeout=120)
for data in local.get_cli_returns(job["jid"], job["minions"], timeout=120):
    pass
...
```

* The command is actually something else then test.ping but it doesn't seem to matter which command is used.
* Also targets can differ but even such a simple form produces the error.

Actually the script works , that means it does what ever is inside the for-loop.
However this for-loop line is where it crashes when the last element was returned.
If I comment line 1018 in /usr/lib/python3/dist-packages/salt/client/\_\_init\_\_.py, this is "self._clean_up_subscriptions(jid)" inside "get_cli_returns", everything works well. 
However I don't think this can really be the solution. 

A workaround for us is  something like:

```
#!/usr/bin/env python3
import salt.client
...

local = salt.client.LocalClient(c_path="/etc/salt/master")
job = local.run_job("myweb*", "test.ping", args=(), tgt_type='compound', timeout=120)
try:
    for data in local.get_cli_returns(job["jid"], job["minions"], timeout=120):
        pass
except:
    pass
finally:
    ...
```
* Of course there could be cases where this is not an acceptable solution.

I have no idea what the actual problem is, maybe it's a bug, maybe the CLI API just changed and I need to change my call? Can you help to investigate the issue?

### Versions Report

```
Salt Version:
           Salt: 2019.2.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Oct  7 2019, 12:59:55)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-134-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```
The Minions are also 2019.2.2 and it doesn't seem to matter if they are python2 or 3 or Windows or Linux.

**Comment by Ch3LL** [comment]
looks like a duplicate of https://github.com/saltstack/salt/issues/54175

okay to close in favor of https://github.com/saltstack/salt/issues/54175?
