### ISSUE TITLE
SPM install broken with py3

### ISSUE THREAD

**Issue by dahrens** [saltstack/salt#55330]
### Setup

Try installing any spm package using `spm install [yourpackage]`

### Steps to Reproduce Issue
```
$ spm install users
Installing packages:
	users

Proceed? [N/y] y
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 12: invalid continuation byte
Traceback (most recent call last):
  File "/usr/bin/spm", line 12, in <module>
    salt_spm()
  File "/usr/lib/python3/dist-packages/salt/scripts.py", line 527, in salt_spm
    spm.run()
  File "/usr/lib/python3/dist-packages/salt/cli/spm.py", line 41, in run
    client.run(self.args)
  File "/usr/lib/python3/dist-packages/salt/spm/__init__.py", line 125, in run
    self._install(args)
  File "/usr/lib/python3/dist-packages/salt/spm/__init__.py", line 373, in _install
    outf.write(self._query_http(dl_url, repo_info['info']))
  File "/usr/lib/python3/dist-packages/salt/spm/__init__.py", line 668, in _query_http
    query = http.query(dl_path, text=True, backend='requests')
  File "/usr/lib/python3/dist-packages/salt/utils/http.py", line 385, in query
    body = body.decode(result.encoding or 'utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 12: invalid continuation byte
Traceback (most recent call last):
  File "/usr/bin/spm", line 12, in <module>
    salt_spm()
  File "/usr/lib/python3/dist-packages/salt/scripts.py", line 527, in salt_spm
    spm.run()
  File "/usr/lib/python3/dist-packages/salt/cli/spm.py", line 41, in run
    client.run(self.args)
  File "/usr/lib/python3/dist-packages/salt/spm/__init__.py", line 125, in run
    self._install(args)
  File "/usr/lib/python3/dist-packages/salt/spm/__init__.py", line 373, in _install
    outf.write(self._query_http(dl_url, repo_info['info']))
  File "/usr/lib/python3/dist-packages/salt/spm/__init__.py", line 668, in _query_http
    query = http.query(dl_path, text=True, backend='requests')
  File "/usr/lib/python3/dist-packages/salt/utils/http.py", line 385, in query
    body = body.decode(result.encoding or 'utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 12: invalid continuation byte
```

For me the problem seems to be located in `salt.util.http.query()`, which (with [requests](https://github.com/saltstack/salt/blob/develop/salt/utils/http.py#L379), [tornado](https://github.com/saltstack/salt/blob/develop/salt/utils/http.py#L596) and [urllib2](https://github.com/saltstack/salt/blob/develop/salt/utils/http.py#L470)) tries to decode bytes to utf-8 in case you sit on py3. But `spm` wants to download an spm file, and...

> Packages are built using BZ2-compressed tarballs.

### Versions Report

```
Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.11
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.3 (default, Apr  3 2019, 05:39:12)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist: debian 10.1
         locale: UTF-8
        machine: x86_64
        release: 4.19.0-6-amd64
         system: Linux
        version: debian 10.1
```

**Comment by Ch3LL** [comment]
im able to replicate this for http spm content. we will need to get this fixed. thanks

**Comment by Ch3LL** [comment]
@dahrens can you try the fix in https://github.com/saltstack/salt/pull/56129
