### ISSUE TITLE
States should use full path instead of search in PATH

### ISSUE THREAD

**Issue by mjtrangoni** [saltstack/salt#55344]
### Description of Issue
Running state.apply on **crond** (as root user) is crashing because some modules does not use the full path, trusting that some commands are always on path.

### Setup
1. Configure any minion to use [kmod.absent](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.kmod.html#salt.states.kmod.absent), [sysctl.present](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.sysctl.html#salt.states.sysctl.present), or [selinux.module](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.selinux.html#salt.states.selinux.module)

### Steps to Reproduce Issue
1. On one salt-minion, use the cronjob environment. In my case was,
```bash
XDG_SESSION_ID=3822
SHELL=/bin/sh
USER=root
PATH=/usr/bin:/bin
PWD=/root
LANG=en_US.UTF-8
SHLVL=1
HOME=/root
LOGNAME=root
XDG_RUNTIME_DIR=/run/user/0
_=/usr/bin/env
```
or you can get it configuring a root cronjob like this  `*/5 * * * *env > ~/cronenv`

2. Run
```bash
# env - `cat ~/cronenv` /usr/bin/salt-call state.apply test=True > /dev/null
```
3. Resulting on these errors,
```bash
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 1933, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1951, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/states/kmod.py", line 189, in absent
    loaded_mods = __salt__['kmod.mod_list']()
  File "/usr/lib/python2.7/site-packages/salt/modules/kmod.py", line 223, in mod_list
    for mod in lsmod():
  File "/usr/lib/python2.7/site-packages/salt/modules/kmod.py", line 177, in lsmod
    for line in __salt__['cmd.run']('lsmod').splitlines():
  File "/usr/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 1182, in run
    **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 684, in _run
    raise CommandExecutionError(msg)
CommandExecutionError: Unable to run command '[u'lsmod']' with the context '{u'timeout': None, u'with_communicate': True, u'shell': False, u'bg': False, u'stderr': -2, u'env': {'LC_NUMERIC': 'C', 'LC_MEASUREMENT': 'C', 'LC_CTYPE': 'C', 'LOGNAME': 'root', 'USER': 'root', 'HOME': '/root', 'LC_PAPER': 'C', 'PATH': '/usr/bin:/bin', 'LANG': 'en_US.UTF-8', 'SHELL': '/bin/sh', 'LANGUAGE': 'C', 'SHLVL': '1', 'XDG_RUNTIME_DIR': '/run/user/0', 'LC_ADDRESS': 'C', 'XDG_SESSION_ID': '3822', '_': '/usr/bin/env', 'LC_IDENTIFICATION': 'C', 'LC_MESSAGES': 'C', 'LC_COLLATE': 'C', 'LC_TELEPHONE': 'C', 'LC_MONETARY': 'C', 'PWD': '/root', 'LC_NAME': 'C', 'LC_TIME': 'C'}, u'stdout': -1, u'close_fds': True, u'stdin': None, u'cwd': u'/root'}', reason: command not found
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 1933, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1951, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/states/sysctl.py", line 63, in present
    current = __salt__['sysctl.show']()
  File "/usr/lib/python2.7/site-packages/salt/modules/linux_sysctl.py", line 96, in show
    out = __salt__['cmd.run_stdout'](cmd, output_loglevel='trace')
  File "/usr/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 1641, in run_stdout
    **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 684, in _run
    raise CommandExecutionError(msg)
CommandExecutionError: Unable to run command '[u'sysctl', u'-a']' with the context '{u'timeout': None, u'with_communicate': True, u'shell': False, u'bg': False, u'stderr': -1, u'env': {'LC_NUMERIC': 'C', 'LC_MEASUREMENT': 'C', 'LC_CTYPE': 'C', 'LOGNAME': 'root', 'USER': 'root', 'HOME': '/root', 'LC_PAPER': 'C', 'PATH': '/usr/bin:/bin', 'LANG': 'en_US.UTF-8', 'SHELL': '/bin/sh', 'LANGUAGE': 'C', 'SHLVL': '1', 'XDG_RUNTIME_DIR': '/run/user/0', 'LC_ADDRESS': 'C', 'XDG_SESSION_ID': '3822', '_': '/usr/bin/env', 'LC_IDENTIFICATION': 'C', 'LC_MESSAGES': 'C', 'LC_COLLATE': 'C', 'LC_TELEPHONE': 'C', 'LC_MONETARY': 'C', 'PWD': '/root', 'LC_NAME': 'C', 'LC_TIME': 'C'}, u'stdout': -1, u'close_fds': True, u'stdin': None, u'cwd': u'/root'}', reason: command not found
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 1933, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1951, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/states/selinux.py", line 229, in module
    ret = module_install(module_path)
  File "/usr/lib/python2.7/site-packages/salt/states/selinux.py", line 284, in module_install
    if __salt__['selinux.install_semod'](name):
  File "/usr/lib/python2.7/site-packages/salt/modules/selinux.py", line 312, in install_semod
    return not __salt__['cmd.retcode'](cmd)
  File "/usr/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 2280, in retcode
    **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 684, in _run
    raise CommandExecutionError(msg)
CommandExecutionError: Unable to run command '[u'semodule', u'-i', u'/var/cache/salt/minion/files/base/REDACTED/FILE.pp']' with the context '{u'timeout': None, u'with_communicate': True, u'shell': False, u'bg': False, u'stderr': -2, u'env': {'LC_NUMERIC': 'C', 'LC_MEASUREMENT': 'C', 'LC_CTYPE': 'C', 'LOGNAME': 'root', 'USER': 'root', 'HOME': '/root', 'LC_PAPER': 'C', 'PATH': '/usr/bin:/bin', 'LANG': 'en_US.UTF-8', 'SHELL': '/bin/sh', 'LANGUAGE': 'C', 'SHLVL': '1', 'XDG_RUNTIME_DIR': '/run/user/0', 'LC_ADDRESS': 'C', 'XDG_SESSION_ID': '3822', '_': '/usr/bin/env', 'LC_IDENTIFICATION': 'C', 'LC_MESSAGES': 'C', 'LC_COLLATE': 'C', 'LC_TELEPHONE': 'C', 'LC_MONETARY': 'C', 'PWD': '/root', 'LC_NAME': 'C', 'LC_TIME': 'C'}, u'stdout': -1, u'close_fds': True, u'stdin': None, u'cwd': u'/root'}', reason: command not found
```
One workaround would be adding the /usr/sbin to the cronjob command, like this
```bash
env - `cat ~/cronenv` PATH="/usr/sbin:$PATH" /usr/bin/salt-call state.apply test=True
```

### Versions Report
Master:
```
# salt --versions-report
Salt Version:
           Salt: 2019.2.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  7 2019, 00:51:29)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.7.1908 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1062.4.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.7.1908 Core
```

Minion:
```
# salt-call --versions-report
Salt Version:
           Salt: 2019.2.2
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Oct  7 2019, 17:58:22)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.3.2
 
System Versions:
           dist: centos 8.0.1905 Core
         locale: UTF-8
        machine: x86_64
        release: 4.18.0-80.11.2.el8_0.x86_64
         system: Linux
        version: CentOS Linux 8.0.1905 Core
```

**Comment by waynew** [comment]
I'm not sure that this really is desired. `$PATH` is there for a reason - you may have installed different dependencies in different locations for other reasons.

Why doesn't your cronenv just contain

```
PATH=/usr/bin:/bin:/usr/sbin
```
?

Especially for the root user, it's surprising that `sbin` isn't on your PATH.

**Comment by ZsBT** [comment]
I've just met another example. Salt master and minion version is 3000.1.
No customization, a plain sysctl state :
```
kernel.sysrq:
  sysctl.present:
    - value: 1
    - config: /etc/sysctl.conf
```

...runs to error:
```
          ID: kernel.sysrq
    Function: sysctl.present
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1981, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1977, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/sysctl.py", line 63, in present
                  current = __salt__['sysctl.show']()
                File "/usr/lib/python2.7/site-packages/salt/modules/linux_sysctl.py", line 96, in show
                  out = __salt__['cmd.run_stdout'](cmd, output_loglevel='trace')
                File "/usr/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 1638, in run_stdout
                  **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 681, in _run
                  raise CommandExecutionError(msg)
              CommandExecutionError: Unable to run command '[u'sysctl', u'-a']' with the context '{u'timeout': None, u'with_communicate':
 True, u'shell': False, u'bg': False, u'stderr': -1, u'env': {'LC_NUMERIC': 'C', 'LC_CTYPE': 'C', 'LOGNAME': 'root', 'USER': 'root', 'HOME': '/home/XXXXXX', 'LC_PAPER': 'C', 'PATH': '/usr/local/bin:/bin:/usr/bin'   (...and so on...)
```

The PATH environment variable, obviously,  is not set locally.
