### ISSUE TITLE
Custom Salt Grain Throws Type Errors

### ISSUE THREAD

**Issue by LinuxLeafFan** [saltstack/salt#55347]
### Description of Issue
A custom salt grain I've written is tossing type errors when it's synced and executed by salt; however, if I execute the grain manually, it doesn't throw any errors.

#### Grains source code: gets gcp metadata
```
import json
try:
    # python3 compat
    from urllib.request import Request, urlopen
    from urllib.parse import urlencode
except ImportError:
    from urllib2 import Request, urlopen  # Python 2
    from urllib import urlencode

def get_gcp_grains():
    """
    Retrieves useful metadata and returns it

    Returns:
        dict: dict containing useful metadata

    """
    urls = [
        { 'url': 'http://metadata.google.internal/computeMetadata/v1/project/',
          'keys': ['projectId'],
          'type': 'project'},


        { 'url': 'http://metadata.google.internal/computeMetadata/v1/instance/',
          'keys': ['cpuPlatform',
                   'disks',
                   'image',
                   'labels',
                   'licenses',
                   'machineType',
                   'maintenanceEvent',
                   'networkInterfaces',
                   'preempted',
                   'scheduling',
                   'serviceAccounts',
                   'tags',
                   'zone'],
          'type': 'instance'}
    ]
    params = urlencode(
        {'recursive':'true',
         'alt':'json' }
    )

    d = {'gcp':{}}
    for obj in urls:
        r = Request("{0}?{1}".format(obj['url'],params))
        r.add_header('Metadata-Flavor','Google')
        d['gcp'][obj['type']] = dict()
        try:
            d['gcp'][obj['type']].update(json.loads(
                urlopen(r).read()
            ))
        except:
            # Assume not a gcp server
            return({})

        for k in d['gcp'][obj['type']].keys():
            if k not in obj['keys']:
                del(d['gcp'][obj['type']][k])

    return(d)

if __name__ == '__main__':
    print(json.dumps(get_gcp_grains(),
                     indent=4,
                     sort_keys=True))
```
#### Syncing grains on minion
```
# salt-call saltutil.sync_grains
[ERROR   ] Exception during resolving address: [Errno 1] Unknown host
[WARNING ] /usr/lib/python3.6/site-packages/salt/grains/core.py:2827: DeprecationWarning: This server_id is computed nor by Adler32 neither by CRC32. Please use "server_id_use_crc" option and define algorithm youprefer (default "Adler32"). The server_id will be computed withAdler32 by default.

[WARNING ] /var/cache/salt/minion/extmods/grains/cpuinfo.py:22: DeprecationWarning: Use of 'salt.utils.which_bin' detected. This function has been moved to 'salt.utils.path.which_bin' as of Salt 2018.3.0. This warning will be removed in Salt Neon.

[CRITICAL] Failed to load grains defined in grain file gcp.urlencode in function <function urlencode at 0x7fff9a23a488>, error:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 798, in grains
    ret = funcs[key](**kwargs)
TypeError: urlencode() missing 1 required positional argument: 'query'
[CRITICAL] Failed to load grains defined in grain file gcp.urlopen in function <function urlopen at 0x7fff981f60d0>, error:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 792, in grains
    parameters = salt.utils.args.get_function_argspec(funcs[key]).args
  File "/usr/lib/python3.6/site-packages/salt/utils/args.py", line 271, in get_function_argspec
    aspec = _getargspec(func)  # pylint: disable=redefined-variable-type
  File "/usr/lib/python3.6/site-packages/salt/utils/args.py", line 231, in _getargspec
    raise ValueError('Function has keyword-only arguments or annotations'
ValueError: Function has keyword-only arguments or annotations, use getfullargspec() API which can support them
local:
    - grains.gcp
```

#### Executing grain source code on minion
```
# ./gcp.py
{}
```

#### Minion

```
# rpm -qi salt-minion
Name        : salt-minion
Version     : 2019.2.0
Release     : 4.4
Architecture: ppc64le
Install Date: Thu Nov 14 20:52:15 2019
Group       : System/Management
Size        : 41019
License     : Apache-2.0
Signature   : RSA/SHA256, Mon May 13 06:54:28 2019, Key ID 70af9e8139db7c82
Source RPM  : salt-2019.2.0-4.4.src.rpm
Build Date  : Mon May 13 06:50:23 2019
Build Host  : mourvedre
Relocations : (not relocatable)
Packager    : https://www.suse.com/
Vendor      : SUSE LLC <https://www.suse.com/>
URL         : http://saltstack.org/
Summary     : The client component for Saltstack
Description :
Salt minion is queried and controlled from the master.
Listens to the salt master and execute the commands.
Distribution: SUSE Linux Enterprise 15
```

#### Master
```
# salt --versions-report
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.6.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.29.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 11 2017, 10:56:06) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: SuSE 12 x86_64
         locale: UTF-8
        machine: x86_64
        release: 4.4.180-94.100-default
         system: Linux
        version: SUSE Linux Enterprise Server  12 x86_64
```

**Comment by lukasraska** [comment]
In the stacktrace, you can see it's trying to load grains from `Failed to load grains defined in grain file gcp.urlencode`, so essentially it thinks the imported function is part of the beacons (because that's how Python exposes that and Salt loader tries to process every function found)

The solution is quite simple, just import every `function` as `_function`, such as 
```
import json
try:
    # python3 compat
    from urllib.request import Request, urlopen as _urlopen
    from urllib.parse import urlencode as _urlencode
except ImportError:
    from urllib2 import Request, urlopen as _urlopen # Python 2
    from urllib import urlencode as _urlencode
```

Then use `_urlencode` and `_urlopen` instead of those. This needs to be done for every imported functions

**Comment by LinuxLeafFan** [comment]
I see, so pre-pending with _ (underscore) will actually treat them as private and the loader will ignore them. Good to know.

Interestingly, this problem is only happening (currently) on my python3 systems. Anyways, thanks for the help, hopefully this helps someone else.
