### ISSUE TITLE
Output to stdout in bash configuration causes pkg.install to fail on macOS

### ISSUE THREAD

**Issue by taranlu-houzz** [saltstack/salt#55405]
### Description of Issue
Any output printed to stdout in bash configuration appears to get added to the json string obtained with `/usr/local/bin/brew info --json=v1 --installed` which causes the json to be invalid and breaks the `pkg` module and state.

### Steps to Reproduce Issue
- `brew` installed normally
- `python@2` installed via `brew`
- `salt` installed via pip
- `salt-minion` running via LaunchDaemon

~/.bash_profile
```
echo 'TEST'
echo 'OH NO!'
```

On macOS minion run:
`sudo salt-call --local -l debug pkg.install tree`

Debug output:
```
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: [---]
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded pkg.install
[DEBUG   ] LazyLoaded direct_call.execute
[DEBUG   ] LazyLoaded pkg_resource.parse_targets
[DEBUG   ] key: ifttt.secret_key, ret: _|-
[DEBUG   ] key: ifttt:secret_key, ret: _|-
[DEBUG   ] LazyLoaded mac_utils.available_services
[DEBUG   ] Loading available services
[DEBUG   ] Service /System/Library/LaunchDaemons/com.apple.jetsamproperties.Mac.plist does not contain a Label key. Skipping.
[DEBUG   ] Loading available services
[DEBUG   ] Found context for available services.
[DEBUG   ] key: pushbullet.api_key, ret: _|-
[DEBUG   ] key: pushbullet:api_key, ret: _|-
[DEBUG   ] LazyLoaded systemd.booted
[DEBUG   ] key: victorops.api_key, ret: _|-
[DEBUG   ] key: victorops:api_key, ret: _|-
[DEBUG   ] DSC: Only available on Windows systems
[DEBUG   ] Module PSGet: Only available on Windows systems
[DEBUG   ] LazyLoaded platform.is_windows
[DEBUG   ] Could not LazyLoad pkg.normalize_name: 'pkg.normalize_name' is not available.
[INFO    ] Executing command 'brew --prefix' in directory '/Users/[----]'
[INFO    ] Executing command '/usr/local/bin/brew info --json=v1 --installed' as user '[----]' in directory '/Users/[----]'
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "/usr/local/bin/salt-call", line 8, in <module>
    sys.exit(salt_call())
  File "/usr/local/lib/python2.7/site-packages/salt/scripts.py", line 431, in salt_call
    client.run()
  File "/usr/local/lib/python2.7/site-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/local/lib/python2.7/site-packages/salt/cli/caller.py", line 138, in run
    ret = self.call()
  File "/usr/local/lib/python2.7/site-packages/salt/cli/caller.py", line 237, in call
    ret['return'] = self.minion.executors[fname](self.opts, data, func, args, kwargs)
  File "/usr/local/lib/python2.7/site-packages/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/salt/modules/mac_brew_pkg.py", line 397, in install
    old = list_pkgs()
  File "/usr/local/lib/python2.7/site-packages/salt/modules/mac_brew_pkg.py", line 127, in list_pkgs
    package_info = salt.utils.json.loads(_call_brew(cmd)['stdout'])
  File "/usr/local/lib/python2.7/site-packages/salt/utils/json.py", line 92, in loads
    return json_module.loads(s, **kwargs)
  File "/usr/local/Cellar/python@2/2.7.17/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@2/2.7.17/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@2/2.7.17/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
```

### Versions Report
```
Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.17 (default, Oct 24 2019, 12:57:50)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 18.1.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 5.1.1
            ZMQ: 4.3.2

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 17.7.0
         system: Darwin
        version: 10.13.6 x86_64
```

**Comment by s0undt3ch** [comment]
Hello @taranlu-houzz! Sorry for the time taken to triage the issue.
I didn't need to setup a test environment to see why this fails, although I did, and of course, it fails.

I actually added the won't fix label because Salt does not control the user's shell configuration, and Salt relies on "clean" output to do it's work.
So, right now, I see no way around this issue.
If you have any ideas, please let us know.
