### ISSUE TITLE
DSC cannot compile config with .psd1 file

### ISSUE THREAD

**Issue by haodeon** [saltstack/salt#55425]
### Description of Issue
The win_dsc module fails to compile DSC configuration when supplied with a .psd1 file as configuration data. The issue appears to be how the module calls the DSC compilation, it simply appends the path to the .psd1 file.

This results in no .mof file being compiled, no error returned and no response, which salt cannot handle.

As a workaround, explicitly passing the -ConfigurationData switch into the config_data parameter allows win_dsc to compile the configuration successfully.

`C:\salt\salt-call.bat -l debug dsc.compile_config D:\HelloWorld.ps1 config_name='HelloWorld' config_data='-ConfigurationData D:\HelloWorld.psd1`

### Setup
HelloWorld.ps1 example

```
Configuration HelloWorld {

    # Import the module that contains the File resource.
    Import-DscResource -ModuleName PsDesiredStateConfiguration

    # The Node statement specifies which targets to compile MOF files for, when this configuration is executed.
    Node $AllNodes.NodeName {

        # The File resource can ensure the state of files, or copy them from a source to a destination with persistent updates.
        File HelloWorld {
            DestinationPath = "C:\Temp\HelloWorld.txt"
            Ensure = "Present"
            Contents   = "Hello World from DSC!"
        }
    }
}
```
HelloWorld.psd1 example

```
@{
    AllNodes = @(
        @{
            NodeName = 'localhost'
            PSDscAllowPlainTextPassword = $true
            PSDscAllowDomainUser = $true
        }
    )
}
```

### Steps to Reproduce Issue

Run `C:\salt\salt-call.bat -l debug dsc.compile_config D:\HelloWorld.ps1 config_name='HelloWorld' config_data=D:\HelloWorld.psd1`

```
[DEBUG   ] DSC: D:\HelloWorld.ps1 | Select-Object -Property FullName, Extension, Exists, @{Name="LastWriteTime";Expression={Get-Date ($_.LastWriteTime) -Format g}} | ConvertTo-Json -Depth 2
[INFO    ] Executing command 'Powershell -NonInteractive -NoProfile "D:\HelloWorld.ps1 | Select-Object -Property FullName, Extension, Exists, @{Name=\"LastWriteTime\";Expression={Get-Date ($_.LastWriteTime) -Format g}} | ConvertTo-Json -Depth 2"' in directory 'D:\'
[INFO    ] DSC: Returning "{}"
[DEBUG   ] DSC: . D:\HelloWorld.ps1 ; HelloWorld D:\hos.psd1 | Select-Object -Property FullName, Extension, Exists, @{Name="LastWriteTime";Expression={Get-Date ($_.LastWriteTime) -Format g}} | ConvertTo-Json -Depth 2
[INFO    ] Executing command 'Powershell -NonInteractive -NoProfile ". D:\HelloWorld.ps1 ; HelloWorld D:\hos.psd1 | Select-Object -Property FullName, Extension, Exists, @{Name=\"LastWriteTime\";Expression={Get-Date ($_.LastWriteTime) -Format g}} | ConvertTo-Json -Depth 2"' in directory 'D:\'
[INFO    ] DSC: Returning "{}"
[ERROR   ] DSC: Failed to compile config: D:\HelloWorld.ps1
Returned: {}
Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 237, in call
    ret['return'] = self.minion.executors[fname](self.opts, data, func, args, kwargs)
  File "C:\salt\bin\lib\site-packages\salt\executors\direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\modules\win_dsc.py", line 329, in compile_config
    raise CommandExecutionError(error)
salt.exceptions.CommandExecutionError: Failed to compile config: D:\HelloWorld.ps1
Returned: {}
Error running 'dsc.compile_config': Failed to compile config: D:\HelloWorld.ps1
Returned: {}
PS D:\>
```

### Versions Report
```
Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: 1.12.2
       cherrypy: 17.4.1
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.6
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: Not Installed
   pycryptodome: 3.8.1
         pygit2: Not Installed
         Python: 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.4
         PyYAML: 3.13
          PyZMQ: 18.0.1
           RAET: Not Installed
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2019Server
         system: Windows
        version: 2019Server 10.0.17763 SP0 Multiprocessor Free
```

**Comment by garethgreenaway** [comment]
@twangboy @xeacott FYI.

**Comment by haodeon** [comment]
There is a fix in a pull request for this issue but it is blocked due to tests needing to be written.

**Comment by haodeon** [comment]
Still working on it

**Comment by haodeon** [comment]
My PR is awaiting feedback. Can someone from Saltstack please take a moment to have a look?
