### ISSUE TITLE
"OSError [Errno 17] File exists" while running cmd.script

### ISSUE THREAD

**Issue by Hitamashi** [saltstack/salt#55439]
### Description of Issue
When I run `cmd.script` on 1 minion with same `source`, I have face this issue:
```
The minion function caused an exception: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1660, in _thread_return
    return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
  File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 2527, in script
    fn_ = __salt__['cp.cache_file'](source, saltenv)
  File "/usr/lib/python2.7/site-packages/salt/modules/cp.py", line 515, in cache_file
    result = _client().cache_file(path, saltenv, source_hash=source_hash)
  File "/usr/lib/python2.7/site-packages/salt/fileclient.py", line 194, in cache_file
    path, '', True, saltenv, cachedir=cachedir, source_hash=source_hash)
  File "/usr/lib/python2.7/site-packages/salt/fileclient.py", line 505, in get_url
    os.makedirs(destdir)
  File "/usr/lib64/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/mycustomsaltdir/var/cache/extrn_files/base/example.com/c6864aa90b9e579b628f38f83ce6e76f0235a4d64df1beb09bfbb2d4882d8152/common'
```

The `source` is an https url. I ran it twice with different `args`. One is success but one throws the error above. FYI, the `cmd.script` is ran almost at the same time.

### Steps to Reproduce Issue
Just run `cmd.script` with same `source` which is https url.
Actually, I cannot reproduce it. But it somehow happened in my system (~ 4000 minions). 

Maybe it is caused by race condition in https://github.com/saltstack/salt/blob/2019.2/salt/fileclient.py#L503-L504

### Versions Report
Master version: 2019.2.0

```
# salt-call --versions-report
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Sep 12 2018, 05:31:16)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: redhat 7.6 Maipo
         locale: ascii
        machine: x86_64
        release: 3.10.0-957.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.6 Maipo
```

**Comment by sagetherage** [comment]
@Hitamashi is this still an issue with a supported version of Python 3.6+ and a supported version of Salt >3000.9?

**Comment by sagetherage** [comment]
Reviewed in Grooming 2021-JUL-19 considering closing

**Comment by sagetherage** [comment]
@Hitamashi following up here have you been able to upgrade to a supported version of Salt?

**Comment by Ch3LL** [comment]
Closing due to inactivity. Please feel free to open a new issue if its still valid for 3006.2
