### ISSUE TITLE
http.query raises: 'Function has keyword-only arguments or annotations'

### ISSUE THREAD

**Issue by skrobul** [saltstack/salt#55499]
### Description of Issue
The `http.query` state stopped working somewhere between 2018.3 and 2019.2.1. It fails with following traceback:

```
----------
          ID: example ILM policy
    Function: http.query
        Name: http://localhost:9200/_ilm/policy/tacacs-production
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/var/tmp/.root_5c401f_salt/pyall/salt/state.py", line 1933, in call
                  **cdata['kwargs'])
                File "/var/tmp/.root_5c401f_salt/pyall/salt/loader.py", line 1951, in wrapper
                  return f(*args, **kwargs)
                File "/var/tmp/.root_5c401f_salt/pyall/salt/states/http.py", line 93, in query
                  data = __salt__['http.query'](name, **kwargs)
                File "/var/tmp/.root_5c401f_salt/pyall/salt/modules/http.py", line 41, in query
                  return salt.utils.http.query(url=url, opts=opts, **kwargs)
                File "/var/tmp/.root_5c401f_salt/pyall/salt/utils/http.py", line 534, in query
                  tornado.simple_httpclient.SimpleAsyncHTTPClient.initialize)
                File "/var/tmp/.root_5c401f_salt/pyall/salt/utils/args.py", line 277, in get_function_argspec
                  aspec = _getargspec(func)  # pylint: disable=redefined-variable-type
                File "/var/tmp/.root_5c401f_salt/pyall/salt/utils/args.py", line 237, in _getargspec
                  raise ValueError('Function has keyword-only arguments or annotations'
              ValueError: Function has keyword-only arguments or annotations, use getfullargspec() API which can support them
     Started: 11:04:53.712922
    Duration: 3.624 ms
     Changes:   



Summary for REDACTED
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   3.624 ms
```

### Setup
Minion is still running 2018.3, but I guess it does not matter when `salt-ssh` is used.
The very same formula works on a different computer (Debian) with `2018.3` version of `salt-ssh`.

### Steps to Reproduce Issue
Failing state:

```
example ILM policy:
  http.query:
    - name: "http://localhost:9200/_ilm/policy/example-policy"
    - method: PUT
    - username: elastic
    - password: {{ elastic_pw }}
    - header_dict:
        Content-Type: application/json
    - status: 200
    - data: |
       {
          "policy" : {
            "phases" : {
              "hot" : {
                "min_age" : "0ms",
                "actions" : {
                  "rollover" : {
                    "max_size" : "30gb",
                    "max_age" : "7d"
                  }
                }
              },
              "delete" : {
                "min_age" : "365d",
                "actions" : {
                  "delete" : { }
                }
              }
            }
          }
        }

```

### Versions Report
```
❯ salt-ssh --versions-report
Salt Version:
           Salt: 2019.2.1rc0
 
Dependency Versions:
           cffi: 1.12.3
       cherrypy: Not Installed
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.35.2
           Mako: 1.1.0
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.5 (default, Oct 17 2019, 12:16:48)
   python-gnupg: Not Installed
         PyYAML: 5.1.2
          PyZMQ: 18.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 6.0.2
            ZMQ: 4.3.2
 
System Versions:
           dist: fedora 31 Thirty One
         locale: UTF-8
        machine: x86_64
        release: 5.3.11-300.fc31.x86_64
         system: Linux
        version: Fedora 31 Thirty One
 
```

**Comment by DmitryKuzmenko** [comment]
Tornado added annotations to methods in the 6.0 release. We're working on Tornado 6.x support and plan to release it in neon.

**Comment by DmitryKuzmenko** [comment]
`salt.utils.args.py._getargspec` gets argspec for `tornado.simple_httpclient.SimpleAsyncHTTPClient.initialize` and then checks for kwonly args and annotations and refuses to handle it. This is the problem.

**Comment by DmitryKuzmenko** [comment]
@dwoz pinging you since you're working on Tornado 6.x support.

**Comment by skrobul** [comment]
bad bot

**Comment by dwoz** [comment]
Fixed by #61080 (commit 21f0644fa25, merged 2022-02-24). `salt.utils.args.get_function_argspec` now uses `inspect.signature` and handles annotations cleanly. Verified the original repro path (`get_function_argspec(tornado.simple_httpclient.SimpleAsyncHTTPClient.initialize)`) returns a valid ArgSpec on 3006.x/3007.x/3008.x/master.
