### ISSUE TITLE
`salt.function` state do not fail if module raise

### ISSUE THREAD

**Issue by TeddyAndrieux** [saltstack/salt#55503]
### Description of Issue

If we have a state running a `salt.function` if the module called by it raise the resulting state result is `True`.

In the code in `salt/states/saltmod.py` there is a check about `failed` field,

```
        m_ret = False
        if mdata.get('retcode'):
            func_ret['result'] = False
            fail.add(minion)
        if mdata.get('failed', False):
            m_func = False
        else:
            if 'return' in mdata and 'ret' not in mdata:
                mdata['ret'] = mdata.pop('return')
            m_ret = mdata['ret']
            m_func = (not fail_function and True) or __salt__[fail_function](m_ret)

            if m_ret is False:
                m_func = False
```

In my test I just saw that `mdata` object contains a `success` key which is `False`, may be this key should be checked also. (I can do the PR if this fix looks good)

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

A state `test.sls`
```
Test failed salt function:
  salt.function:
    - name: foo.test
    - tgt: bootstrap
```

A module `foo.py`
```
def test():
  raise ValueError("bar")
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

Just call the state with `salt-run`
```
[root@bootstrap /]# salt-run state.sls test saltenv=metalk8s-2.5.0-dev
/run/dbus/system_bus_socket: No such file or directory
bootstrap_master:
----------
          ID: Test failed salt function
    Function: salt.function
        Name: foo.test
      Result: True
     Comment: Function ran successfully. Function foo.test ran on bootstrap.
     Started: 15:46:02.694388
    Duration: 2004.447 ms
     Changes:   
              bootstrap:
                  The minion function caused an exception: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1637, in _thread_return
                  return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
                File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 12, in execute
                  return func(*args, **kwargs)
                File "/var/cache/salt/minion/extmods/modules/foo.py", line 2, in test
                  raise ValueError("bar")
              ValueError: bar
              

Summary for bootstrap_master
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   2.004 s
```

The only option to have a `Failed` state without specifying a `fail_function` is that the module return `False`

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
[root@bootstrap /]# salt --versions-report
Salt Version:
           Salt: 2018.3.4
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Oct 30 2018, 23:45:53)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.6.1810 Core
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 3.10.0-957.1.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core
```

**Comment by dwoz** [comment]
Cannot reproduce on 3006.x/3007.x/3008.x/master.

When the targeted function raises, the minion sets retcode=EX_GENERIC and success=False on the return; saltmod.function() catches the non-zero retcode at https://github.com/saltstack/salt/blob/master/salt/states/saltmod.py#L658-L661 and marks the state result False. The fallback path (function returns literal False, retcode 0) is also handled via the 'm_ret is False -> m_func = False' branch.

Reproducer (unit-level, mirrors salt/minion.py exception path):
```
mdata = {'success': False, 'return': 'Traceback ... ValueError: bar', 'retcode': EX_GENERIC, 'out': 'nested'}
```
returns result=False on all four supported branches. Closing; please reopen with a current-version reproducer if still seen.
