### ISSUE TITLE
NameError: global name 'requests' is not defined

### ISSUE THREAD

**Issue by dbuehler77** [saltstack/salt#55604]
### Description of Issue
Requests is installed on the minion; however, when modules requiring the requests package, such as 's3.head' are run, the minion returns saying that "global name 'requests' is not defined".

I have two other minions running the same version of salt with the same version of requests and they do not have this issue.

Why is one of my minions saying requests is not defined when it is clearly installed?

### Setup
I have a salt master and minion each running 2019.2.0 and I cannot execute any s3.* modules on the minion because it says requests is not defined.

### Steps to Reproduce Issue
When running the s3.head module, the following is returned to the salt master:

```
root:/srv/salt# salt minion s3.head my-bucket
minion:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1660, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/s3.py", line 244, in head
        https_enable=https_enable)
      File "/usr/lib/python2.7/dist-packages/salt/utils/s3.py", line 176, in query
        result = requests.request(method,
    NameError: global name 'requests' is not defined
ERROR: Minions returned with non-zero exit code
```

The minion debug logs show:

```
2019-12-11 15:25:08,033 [salt.utils.lazy  :104 ][DEBUG   ][8340] LazyLoaded compound_match.match
2019-12-11 15:25:08,040 [salt.loaded.int.matchers.compound_match:32  ][DEBUG   ][8340] compound_match: rb-qio-bro-2 ? ['L@gf312-qio-bro-2,gf205-qio-bro-2,rb-qio-bro-2,oq-qio-bro-2']
2019-12-11 15:25:08,043 [salt.utils.lazy  :104 ][DEBUG   ][8340] LazyLoaded list_match.match
2019-12-11 15:25:08,044 [salt.loaded.int.matchers.compound_match:105 ][DEBUG   ][8340] compound_match rb-qio-bro-2 ? "['L@gf312-qio-bro-2,gf205-qio-bro-2,rb-qio-bro-2,oq-qio-bro-2']" => "True"
2019-12-11 15:25:08,046 [salt.minion      :1465][INFO    ][8340] User sudo_dylan Executing command s3.head with jid 20191211102507992557
2019-12-11 15:25:08,047 [salt.minion      :1472][DEBUG   ][8340] Command details {u'tgt_type': u'compound', u'jid': u'20191211102507992557', u'tgt': [u'L@gf312-qio-bro-2,gf205-qio-bro-2,rb-qio-bro-2,oq-qio-bro-2'], u'ret': u'', u'user': u'sudo_dylan', u'arg': [u'my-bucket'], u'fun': u's3.head'}
2019-12-11 15:25:08,084 [salt.minion      :1605][INFO    ][8440] Starting a new job 20191211102507992557 with PID 8440
2019-12-11 15:25:08,100 [salt.utils.lazy  :107 ][DEBUG   ][8440] Could not LazyLoad {0}.allow_missing_func: '{0}.allow_missing_func' is not available.
2019-12-11 15:25:08,104 [salt.utils.lazy  :104 ][DEBUG   ][8440] LazyLoaded s3.head
2019-12-11 15:25:08,122 [salt.utils.lazy  :104 ][DEBUG   ][8440] LazyLoaded s3.query
2019-12-11 15:25:08,125 [salt.loaded.int.utils.s3:87  ][ERROR   ][8440] There was an error: requests is required for s3 access
2019-12-11 15:25:08,128 [salt.loaded.int.utils.s3:148 ][DEBUG   ][8440] S3 Request: http://my-bucket.s3.amazonaws.com/?
2019-12-11 15:25:08,131 [salt.loaded.int.utils.s3:149 ][DEBUG   ][8440] S3 Headers::
2019-12-11 15:25:08,133 [salt.loaded.int.utils.s3:150 ][DEBUG   ][8440]     Authorization: AWS4-HMAC-SHA256 Credential=key/20191211/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=1b149de708f8f14606f76c74837cc55dc5954a90fc86fa8c642390fcda91e4e8
2019-12-11 15:25:08,136 [salt.minion      :1738][WARNING ][8440] The minion function caused an exception
2019-12-11 15:25:08,139 [salt.utils.event :324 ][DEBUG   ][8440] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_e903c27ad7_pub.ipc
2019-12-11 15:25:08,142 [salt.utils.event :327 ][DEBUG   ][8440] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_e903c27ad7_pull.ipc
2019-12-11 15:25:08,144 [salt.transport.ipc:261 ][DEBUG   ][8440] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_e903c27ad7_pull.ipc
2019-12-11 15:25:08,149 [salt.utils.event :742 ][DEBUG   ][8440] Sending event: tag = _salt_error; data = {'message': u'The minion function caused an exception', 'args': ('The minion function caused an exception',), u'_stamp': '2019-12-11T15:25:08.149162'}
2019-12-11 15:25:08,153 [salt.transport.ipc:405 ][DEBUG   ][8440] Closing IPCMessageClient instance
2019-12-11 15:25:08,156 [salt.minion      :767 ][DEBUG   ][8440] Minion return retry timer set to 7 seconds (randomized)
2019-12-11 15:25:08,157 [salt.minion      :1941][INFO    ][8440] Returning information for job: 20191211102507992557
2019-12-11 15:25:08,158 [salt.minion      :2355][DEBUG   ][8340] Minion of 'master' is handling event tag '_salt_error'
2019-12-11 15:25:08,160 [salt.minion      :2528][DEBUG   ][8340] Forwarding salt error event tag=_salt_error
2019-12-11 15:25:08,160 [salt.transport.zeromq:132 ][DEBUG   ][8440] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/minion', u'rb-qio-bro-2', u'tcp://52.2.182.237:80', u'aes')
2019-12-11 15:25:08,162 [salt.crypt       :463 ][DEBUG   ][8440] Initializing new AsyncAuth for (u'/etc/salt/pki/minion', u'rb-qio-bro-2', u'tcp://52.2.182.237:80')
2019-12-11 15:25:08,166 [salt.transport.zeromq:203 ][DEBUG   ][8440] Connecting the Minion to the Master URI (for the return server): tcp://52.2.182.237:80
2019-12-11 15:25:08,169 [salt.transport.zeromq:1178][DEBUG   ][8440] Trying to connect to: tcp://52.2.182.237:80
2019-12-11 15:25:08,170 [salt.transport.zeromq:132 ][DEBUG   ][8340] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/minion', u'rb-qio-bro-2', u'tcp://52.2.182.237:80', u'aes')
2019-12-11 15:25:08,175 [salt.crypt       :463 ][DEBUG   ][8340] Initializing new AsyncAuth for (u'/etc/salt/pki/minion', u'rb-qio-bro-2', u'tcp://52.2.182.237:80')
2019-12-11 15:25:08,180 [salt.transport.zeromq:203 ][DEBUG   ][8340] Connecting the Minion to the Master URI (for the return server): tcp://52.2.182.237:80
2019-12-11 15:25:08,182 [salt.transport.zeromq:1178][DEBUG   ][8340] Trying to connect to: tcp://52.2.182.237:80
2019-12-11 15:25:08,435 [salt.transport.zeromq:227 ][DEBUG   ][8340] Closing AsyncZeroMQReqChannel instance
2019-12-11 15:25:08,440 [salt.transport.zeromq:227 ][DEBUG   ][8440] Closing AsyncZeroMQReqChannel instance
2019-12-11 15:25:08,446 [salt.minion      :1783][DEBUG   ][8440] minion return: {u'fun_args': [u'my-bucket'], u'jid': u'20191211102507992557', u'return': u'The minion function caused an exception: Traceback (most recent call last):\n  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1660, in _thread_return\n    return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)\n  File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 12, in execute\n    return func(*args, **kwargs)\n  File "/usr/lib/python2.7/dist-packages/salt/modules/s3.py", line 244, in head\n    https_enable=https_enable)\n  File "/usr/lib/python2.7/dist-packages/salt/utils/s3.py", line 176, in query\n    result = requests.request(method,\nNameError: global name \'requests\' is not defined\n', u'retcode': 1, u'success': False, u'fun': u's3.head', u'out': u'nested'}
```

### Versions Report

```
Master:
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Oct  8 2019, 14:14:10)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-1022-aws
         system: Linux
        version: Ubuntu 16.04 xenial

Minion:
Salt Version:
               Salt: 2019.2.0

    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 2.5.3
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.9.4
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.13 (default, Sep 26 2018, 18:42:22)
       python-gnupg: Not Installed
             PyYAML: 3.12
              PyZMQ: 16.0.2
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.4.3
                ZMQ: 4.2.1

    System Versions:
               dist: debian 9.9
             locale: UTF-8
            machine: armv7l
            release: 4.19.57-v7+
             system: Linux
            version: debian 9.9

```

Running 'pip freeze' on the minion shows the version of requests:

```
backports-abc==0.5
    certifi==2019.11.28
    chardet==2.3.0
    croniter==0.3.12
    cryptography==1.7.1
    enum34==1.1.6
    futures==3.0.5
    idna==2.2
    ipaddress==1.0.17
    Jinja2==2.9.4
    keyring==10.1
    keyrings.alt==1.3
    MarkupSafe==0.23
    msgpack-python==0.4.8
    psutil==5.0.1
    pyasn1==0.1.9
    pycrypto==2.6.1
    pygobject==3.22.0
    pyinotify==0.9.6
    pyOpenSSL==16.2.0
    python-apt==1.1.0b5
    python-dateutil==2.5.3
    pytz==2016.7
    pyxdg==0.25
    PyYAML==3.12
    pyzmq==16.0.2
    **requests==2.12.4**
    RPi.GPIO==0.6.5
    salt==2019.2.0
    SecretStorage==2.3.1
    sentry-sdk==0.13.5
    singledispatch==3.4.0.3
    six==1.12.0
    systemd-python==233
    tornado==4.4.3
    urllib3==1.25.7
 ```

Any ideas?

**Comment by dbuehler77** [comment]
WORKAROUND:

In my case, I was able to fix the issue with requests by upgrading the version of requests and restarting the salt minion.

`pip install requests --upgrade`
`service salt-minion restart`

pip freeze now shows the versions as 2.22.0, which is working.
`- backports-abc==0.5
    - certifi==2019.11.28
    - chardet==3.0.4
    - croniter==0.3.12
    - cryptography==1.7.1
    - enum34==1.1.6
    - futures==3.0.5
    - idna==2.8
    - ipaddress==1.0.17
    - Jinja2==2.9.4
    - keyring==10.1
    - keyrings.alt==1.3
    - MarkupSafe==0.23
    - msgpack-python==0.4.8
    - pip==9.0.1
    - psutil==5.0.1
    - pyasn1==0.1.9
    - pycrypto==2.6.1
    - pygobject==3.22.0
    - pyinotify==0.9.6
    - pyOpenSSL==16.2.0
    - python-apt==1.1.0b5
    - python-dateutil==2.5.3
    - pytz==2016.7
    - pyxdg==0.25
    - PyYAML==3.12
    - pyzmq==16.0.2
    - requests==2.22.0
    - RPi.GPIO==0.6.5
    - salt==2019.2.0
    - SecretStorage==2.3.1
    - sentry-sdk==0.13.5
    - setuptools==33.1.1
    - singledispatch==3.4.0.3
    - six==1.12.0
    - systemd-python==233
    - tornado==4.4.3
    - urllib3==1.25.7
    - wheel==0.29.0`

This ultimately doesn't explain or identify the underlying issue, but it is at least a workaround.

**Comment by waynew** [comment]
Hey @dbuehler77 thanks for the report!

That's uh... super weird. I was going to suggest that you double check that you've got the right Python - `salt your-minion grains.get pythonexecutable` is one way to see which Python you're using, and then `/path/to/that/python -m pip freeze`.

I expect that what happened here is an issue with your PATH, but it also appears to be resolved, so I'm not sure what else can be done. I'm going to go ahead and close this issue, but if anyone encounters this again, please let us know!

**Comment by dbuehler77** [comment]
@waynew thanks for looking into this. Given I already upgraded pip on the affected host and resolved the issue for operational purposes, I'll have to wait for another opportunity where this comes up (hopefully it doesn't!), but in our organization this has actually been one of our biggest issues with Salt. We absolutely love Salt, but requests has given us the runaround more than once.
