### ISSUE TITLE
exceptions with cpan module with salt '*' but not salt-call

### ISSUE THREAD

**Issue by fabrice1972** [saltstack/salt#55633]
### Description of Issue
when I use cpan module with salt-call from the minion, it works fine. But with salt '*' it fails.
 

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
the master and the minion is the same host : lnxtst01-foncier

For exemple, if I call cpan.list :
**[root@lnxtst01-foncier ~]# salt 'lnxtst01*' cpan.list
lnxtst01-foncier.appli.dgfip:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1200, in _thread_return
        return_data = func(*args, **kwargs)
      File "/usr/lib/python2.7/site-packages/salt/modules/cpan.py", line 149, in list_
        ret[comps[0]] = comps[1]
    IndexError: list index out of range**

I modified the cpan.py to find an explanation, returning the 15 fists lines of output :
```
   for x in range(15):
      ret[x] = out[x]
#    for line in out:
#        comps = line.split()
#        log.info ("comps[0] :" + comps[0] + "  comps[1] :"+comps[1])
#        ret[comps[0]] = comps[1]
    return ret

```
The fact is that there is a blank line in the output, split the empty line  cause the crash when executing _ret[comps[0]] = comps[1]_

the output is then (notice line 1 and 5 are empty): 

> [root@lnxtst01-foncier /var/cache/salt/minion/proc]# salt 'lnxtst01*'  cpan.list
> lnxtst01-foncier.appli.dgfip:
>     ----------
>     0:
>         Loading internal null logger. Install Log::Log4perl for logging messages
>     1:
>     2:
>         CPAN.pm requires configuration, but most of it can be done automatically.
>     3:
>         If you answer 'no' below, you will enter an interactive dialog for each
>     4:
>         configuration option instead.
>     5:
>     6:
>         Would you like to configure as much as possible automatically? [yes] yes
>     7:
>         version 0.9918
>     8:
>         MIME::Base64    3.15
> 
> (...)

il y run with salt-call, the output is different (notice that there is no message from cpan asking something about the configuration)
```
[root@lnxtst01-foncier /var/cache/salt/minion/proc]# salt-call  cpan.list
[INFO    ] Executing command 'cpan -l' in directory '/root'
local:
    ----------
    0:
        Loading internal null logger. Install Log::Log4perl for logging messages
    1:
        version 0.9918
    2:
        MIME::Base64    3.15

```

when i run directly the cpan command 'cpan -l' being root on the host, i have no message neither (excepted the one about log4perl).

I am new to salt, and i cannot figure why the environment seems different where i execute from 'salt '*' or from salt-call

cpan is version 1.64.

/root/.cpan/CPAN/MyConfig.pm exists

### Versions Report
[root@lnxtst01-foncier /var/log/salt]# salt --versions-report
           Salt: 2015.5.10
         Python: 2.7.5 (default, Jun 25 2019, 07:10:03)
         Jinja2: 2.9.6
       M2Crypto: 0.21.1
 msgpack-python: 0.5.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.7.0
           RAET: Not Installed
            ZMQ: 4.1.4
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: Not Installed

**Comment by fabrice1972** [comment]
I finally found the cause of the difference.

It is a matter of environment. With salt-call, the module is executed locally with all the environement, and when using salt, this is the environment of the minion process.

you can see the différence with the 2 commands :
 `salt 'lnxtst01*' cmd.run 'env'`
and
` salt-call cmd.run 'env'`

In the second case, there is 2 needed environement variables for cpan : 
```
HOME=/root
PERL_MM_USE_DEFAULT=1

```
It is not mentionned in the documentation of salt cpan module, but this environement variables must be positionned, with state.environment . In particular the HOME directory, because cpan looks for $HOME/.cpan/CPAN/MyConfig.pm and if it cannot find it, it asks for the config. 
```
[root@lnxtst01-foncier /srv/salt/perl]# cat environment.sls
HOME:
  environ.setenv:
    - value: /root
    - update_minion: True

PERL_MM_USE_DEFAULT:
  environ.setenv:
    - value: '1'
    - update_minion: True

```
