### ISSUE TITLE
Unicode decoding error in user.present state when /etc/login.defs is read

### ISSUE THREAD

**Issue by reversefold** [saltstack/salt#55695]
### Description of Issue
I'm getting a unicode decode error every time the user.present state runs on Ubuntu 16.04 with Python 3 and salt 2019.2.2. The error is happening in the code that reads the /etc/login.defs file.
```
2019-12-19 01:04:32,499 [salt.state       :322 ][ERROR   ][19335] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/state.py", line 1933, in call
    **cdata['kwargs'])
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1951, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/states/user.py", line 756, in present
    if __salt__['user.add'](**params):
  File "/usr/lib/python3/dist-packages/salt/modules/useradd.py", line 155, in add
    for line in fp_:
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 6962: ordinal not in range(128)
```
I'm not having this problem on Ubuntu 18.04.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
```
# salt-minion --versions-report
Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: 1.13.2
       cherrypy: Not Installed
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.2 (default, Oct  8 2019, 13:06:37)
   python-gnupg: 0.3.8
         PyYAML: 5.1.2
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-1087-aws
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by justinIntergas** [comment]
Hi we have the same issue only with a .p12 file when test=true is applied

```
Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3.6/site-packages/salt/state.py", line 1933, in call
                  **cdata['kwargs'])
                File "/usr/lib/python3.6/site-packages/salt/loader.py", line 1951, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/states/file.py", line 2769, in managed
                  **kwargs
                File "/usr/lib/python3.6/site-packages/salt/modules/file.py", line 4841, in check_managed_changes
                  group, mode, attrs, saltenv, contents)
                File "/usr/lib/python3.6/site-packages/salt/modules/file.py", line 4945, in check_file_meta
                  tmp_.write(salt.utils.stringutils.to_str(contents))
                File "/usr/lib/python3.6/site-packages/salt/utils/stringutils.py", line 102, in to_str
                  raise exc  # pylint: disable=raising-bad-type
                File "/usr/lib/python3.6/site-packages/salt/utils/stringutils.py", line 95, in to_str
                  return _normalize(s.decode(enc, errors))
              UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 1: invalid start byte
```

```
Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: 1.12.3
       cherrypy: 18.2.0
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 3.0.2
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Apr 25 2019, 21:02:35)
   python-gnupg: 0.4.5
         PyYAML: 3.13
          PyZMQ: 18.1.0
           RAET: Not Installed
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.3.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```

**Comment by reversefold** [comment]
Some more information: This happened on AWS with AMI ami-0b37e9efc396e4c38 (ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20190628) in the us-west-2 region. After some digging I found utf-8 code c2b4 (´ | 0xc2 0xb4 | ACUTE ACCENT) in /etc/login.defs. There are clearly regular quotes in the file but somehow this one made its way in. The file has no UTF8 BOM.

Perhaps the code should be logging a warning when this kind of thing happens but then falling back to decoding with errors='backslashreplace'?

**Comment by Ch3LL** [comment]
ping @justinIntergas is that when you are using `user.present` state as well? If its another use case please open another issue with the details on how to replicate. 

@reversefold it seems odd, because we are trying to handle unicode here https://github.com/saltstack/salt/blob/v2019.2.2/salt/modules/useradd.py#L156 on the line just under that. any chance you can share a sanitized version of your file so i can replicate this issue?

**Comment by reversefold** [comment]
We're using `user.present` state in our users state. I can't provide the code directly.  I see the `to_unicode` call on line 156, but the error happens on line 155. This is due to the file being opened in text mode with an encoding that doesn't decode the data properly.

You may need to either open the file in binary mode, try to convert permissively, then split to lines, or to add an `errors` option to the open call so that the errors are handled.

**Comment by Ch3LL** [comment]
looks like i'm able to replicate with this state: 

```
root@7cdc9a11f285:/# cat /srv/salt/test.sls
fred:
  user.present:
    - fullname: Fred Jones
    - shell: /bin/zsh
    - home: /home/fred
    - groups:
      - wheel
      - fred
```

I believe we just need to open that file in binary mode (`rb`)  `with salt.utils.files.fopen(defs_file, 'rb') as fp_:`  can you test that out as well? if it works i'll get some tests written to ensure it works on both python2/python3

**Comment by reversefold** [comment]
That looks like it should work, yes.

**Comment by greut** [comment]
@Ch3LL can we get an option to activate _binary_ (`rb`) mode for pillars as well? The same encoding error on `test=True` occurs when using the following example.

https://docs.saltstack.com/en/latest/topics/pillar/#binary-data-in-the-pillar

Cheers,

**Comment by Ch3LL** [comment]
can you open a separate issue with a detailed use case? the fix might be different then here.

**Comment by pnickerson-cashstar** [comment]
I submitted a bug report to Ubuntu, asking them to remove the non-ASCII character from /etc/login.defs: https://bugs.launchpad.net/ubuntu/+source/shadow/+bug/1869267

I think opening the file in binary mode would be a good idea, but I also would generally expect this file to contain only ASCII characters.
