### ISSUE TITLE
CentOS 8 regression user.present state broken ?

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt#55701]
### Description of Issue
when trying to push a user.present state out on a newly upgraded to CentOO 8 server from master to itself,  it now fails whereas it worked for years. It fails in same way when pushing to CentOS 7 as well.

### Setup
Salt minion version 2019.2.2 on latest and fully patched CentOS 8

### Steps to Reproduce Issue
```salt 'salt master.fqdn' state.apply user1```

fails with:
```
[WARNING ] /usr/lib/python3.6/site-packages/salt/transport/zeromq.py:42: VisibleDeprecationWarning: zmq.eventloop.minitornado is deprecated in pyzmq 14.0 and will be removed.
    Install tornado itself to use zmq with the tornado IOLoop.
    
  import zmq.eventloop.ioloop

saltmaster.fqdn:
----------
          ID: /etc/sudoers.d/user1
    Function: file.managed
      Result: True
     Comment: File /etc/sudoers.d/ursr is in the correct state
     Started: 16:38:18.943877
    Duration: 41.028 ms
     Changes:   
----------
          ID: user1
    Function: user.present
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3.6/site-packages/salt/state.py", line 1933, in call
                  **cdata['kwargs'])
                File "/usr/lib/python3.6/site-packages/salt/loader.py", line 1951, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/states/user.py", line 509, in present
                  present_optgroups = [x for x in optional_groups
                File "/usr/lib/python3.6/site-packages/salt/states/user.py", line 510, in <listcomp>
                  if __salt__['group.info'](x)]
                File "/usr/lib/python3.6/site-packages/salt/modules/groupadd.py", line 95, in info
                  grinfo = grp.getgrnam(name)
              TypeError: getgrnam() argument 1 must be str, not OrderedDict
     Started: 16:38:18.985961
    Duration: 8.426 ms
     Changes:   

Summary for git.ict.om.org
------------
Succeeded: 1
Failed:    1
------------
Total states run:     2
Total run time:  49.454 ms
```

### Versions Report
Salt Version:
           Salt: 2019.2.2
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Oct  7 2019, 17:58:22)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.3.2
 
System Versions:
           dist: centos 8.0.1905 Core
         locale: UTF-8
        machine: x86_64
        release: 4.18.0-80.11.2.el8_0.x86_64
         system: Linux
        version: CentOS Linux 8.0.1905 Core

The sos file ```user1.sls``` looks as follows:
```
cat user1.sls 
/etc/sudoers.d/user1:
  file.managed:
    - source: salt://centos/users/user1
    - mode: 440
user1:
  user.present:
    - fullname: User 1
    - name: user1
    - optional_groups:
      - ssh_access
      - system
      - password: <hash-removed-manually>

**Comment by TheBigBear** [comment]
We have also recently switched from py2.x to py3.x and it ***might*** be related to that change and not  to the change to CentOS 8 as suspected in subject, sorry, if that turns out to be the reason.

**Comment by TheBigBear** [comment]
False alarm, sorry. The sls file had two extraneous spaces which broke the yaml syntax. Simple. All good.
