### ISSUE TITLE
lgpo will not work in Windows version 10.0.18363 due to an (possibly invalid) administrative template

### ISSUE THREAD

**Issue by H20-17** [saltstack/salt#55709]
### Description of Issue

After upgrading windows 10 to version 1909 (build 8363), There were two problems with the file _C:\Windows\PolicyDefinitions\en-US\WindowsDefender.adml_ .

If I run a command like.

```
C:\salt\salt-call.bat lgpo.get machine
```

I see the following errors in the output (not necessarily in the order they appear)

#### First error

```
lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1
[ERROR   ] An error was found while processing adml file c:\Windows\PolicyDefinitions\en-US\WindowsDefender.adml, all policy language data from this file will be unavailable via this module
```

#### Second error

```
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
KeyError: 'Microsoft.Policies.WindowsDefender'
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 431, in salt_call
    client.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\call.py", line 57, in run
    caller.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 138, in run
    ret = self.call()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 237, in call
    ret['return'] = self.minion.executors[fname](self.opts, data, func, args, kwargs)
  File "C:\salt\bin\lib\site-packages\salt\executors\direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\modules\win_lgpo.py", line 7784, in get
    return_not_configured=return_not_configured))
  File "C:\salt\bin\lib\site-packages\salt\modules\win_lgpo.py", line 6519, in _checkAllAdmxPolicies
    for path_needed in unpathed_dict[policy_namespace]:
KeyError: 'Microsoft.Policies.WindowsDefender'
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 431, in salt_call
    client.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\call.py", line 57, in run
    caller.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 138, in run
    ret = self.call()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 237, in call
    ret['return'] = self.minion.executors[fname](self.opts, data, func, args, kwargs)
  File "C:\salt\bin\lib\site-packages\salt\executors\direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\modules\win_lgpo.py", line 7784, in get
    return_not_configured=return_not_configured))
  File "C:\salt\bin\lib\site-packages\salt\modules\win_lgpo.py", line 6519, in _checkAllAdmxPolicies
    for path_needed in unpathed_dict[policy_namespace]:
KeyError: 'Microsoft.Policies.WindowsDefender'
```
### Setup
The setup is to have windows 10 1909 installed.

### Steps to Reproduce Issue

Call the following comand

```
C:\salt\salt-call.bat lgpo.get machine
```

### Versions Report
```
Salt Version:
           Salt: 2019.2.2
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.11
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.5 (default, Oct 17 2019, 12:09:47)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: fedora 30 Thirty
         locale: UTF-8
        machine: x86_64
        release: 5.3.13-200.fc30.x86_64
         system: Linux
        version: Fedora 30 Thirty
```

**Comment by H20-17** [comment]
The workaround I came up with for this issue is as follows:

I made sure that start  of _C:\Windows\PolicyDefinitions\en-US\WindowsDefender.adml _ is as follows:

```
<?xml version="1.0" encoding="utf-8"?>

<policyDefinitionResources xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" revision="1.0" schemaVersion="1.0" xmlns="http://schemas.microsoft.com/GroupPolicy/2006/07/PolicyDefinitions">
```

Note that I'm pointing to the schema _http://schemas.microsoft.com/GroupPolicy/2006/07/PolicyDefinitions_ instead of _http://schemas.microsoft.com/GroupPolicy/2006/07/Policysecurity intelligence_ which the xml parsing library does not recognize.

In terms of state formulas I acomplished the above by doing:

```
{% if grains['osversion'] in ['10.0.18363'] %}


Take ownership of WindowsDefender.adml:
    cmd.run:
       - name: "takeown /F C:\\Windows\\PolicyDefinitions\\en-US\\WindowsDefender.adml"


Assign Permissions to WindowsDefender.adml:
     win_dacl.present:
       - name: "C:\\Windows\\PolicyDefinitions\\en-US\\WindowsDefender.adml"
       - objectType: File
       - user: Administrators
       - acetype: ALLOW
       - permission: FullControl
       - propagation: FILES


Overwrite Windows Defender Admin Template:
   file.managed:
      - name: "C:\\Windows\\PolicyDefinitions\\en-US\\WindowsDefender.adml"
      - source: salt://win/admin_templates/WindowsDefender.adml 
      - user: Administrator
      - require:
           - Assign Permissions to WindowsDefender.adml

{% endif %}
```

**Comment by garethgreenaway** [comment]
@twangboy @xeacott FYI.

**Comment by sagetherage** [comment]
not stale

**Comment by xeacott** [comment]
Thanks for the report on this! In the last month or so the LGPO module has had some extremely intense and long-winded work done to it. @twangboy has been responsible for the awesome work done to that module, however when it comes to the .admx/.adml files, Microsoft can and will update these files pretty regularly. 

A lot of the issues with the LGPO stem from these changes that Microsoft makes to them and how the eTree ends up parsing it.

Anyways, I'll let @twangboy see this because it actually could have been fixed in `2019.2.3` as I noticed your version of salt is `2019.2.2`.

**Comment by xeacott** [comment]
Update on this - this is _potentially_ fixed already with Neon.

**Comment by twangboy** [comment]
I think all the updates to LGPO went into the 3000 (Neon) release. We addressed some issues with mal-formatted xml in the MS supplied ADMX/ADML files. So, yeah, I think this has been addressed.

**Comment by H20-17** [comment]
I'll close this then. Thanks for the work.
