### ISSUE TITLE
salt-call --local state.orch un-handled exception

### ISSUE THREAD

**Issue by Fauxsys** [saltstack/salt#55735]
### Description of Issue
- `salt-run state.orch bugreport` will work
- `salt-run state.orchestrate bugreport` will work
- `salt-call --local state.orch bugreport` will NOT work
- `salt-call --local state.orchestrate bugreport` will NOT work

### Setup
- File Structure:
    ```
    root@bug_report:/srv/states# tree
    .
    ├── bugreport.sls
    ├── bug.sls
    ```
- `/etc/salt/minion`:
    ```
    master: 127.0.0.1
    log_file: /var/log/salt/minion
    log_level: info
    file_mode: local
    ```
- `/etc/salt/master`:
    ```
    file_roots:
      base:
        - /srv/states

    pillar_roots:
      base:
        - /srv/pillar

    log_level: info
    ```
- `bug.sls`:
    ```
    Echo Hello:
      cmd.run:
        - name: echo Hello
    ```
- `bugreport.sls`
    ```
    bug:
      salt.state:
        - tgt: '*'
        - sls:
          - bug
    ```
### Steps to Reproduce Issue
- `salt-call --local state.orch bugreport`
    ```
    [WARNING ] /usr/lib/python3/dist-packages/salt/utils/path.py:265: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
      if not isinstance(exes, collections.Iterable):

    [WARNING ] /usr/lib/python3/dist-packages/salt/utils/decorators/signature.py:31: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
      *salt.utils.args.get_function_argspec(original_function)

    [WARNING ] /usr/lib/python3/dist-packages/salt/utils/decorators/signature.py:31: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
      *salt.utils.args.get_function_argspec(original_function)

    [WARNING ] /usr/lib/python3/dist-packages/salt/utils/decorators/signature.py:31: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
      *salt.utils.args.get_function_argspec(original_function)

    [WARNING ] /usr/lib/python3/dist-packages/salt/utils/decorators/signature.py:31: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
      *salt.utils.args.get_function_argspec(original_function)

    [WARNING ] /usr/lib/python3/dist-packages/salt/utils/decorators/signature.py:31: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
      *salt.utils.args.get_function_argspec(original_function)

    local:
        ----------
        state.orch:
            'state.orch' is not available.
        state.orchestrate:

                New in version 2016.11.0

                Execute the orchestrate runner from a masterless minion.

                .. seealso:: More Orchestrate documentation

                    * :ref:`Full Orchestrate Tutorial <orchestrate-runner>`
                    * :py:mod:`Docs for the ``salt`` state module <salt.states.saltmod>`

                CLI Examples:

                    salt-call --local state.orchestrate webserver
                    salt-call --local state.orchestrate webserver saltenv=dev test=True
                    salt-call --local state.orchestrate webserver saltenv=dev pillarenv=aws

    [ERROR   ] An un-handled exception was caught by salt's global exception handler:
    KeyError: 'retcode'
    Traceback (most recent call last):
      File "/usr/bin/salt-call", line 11, in <module>
        salt_call()
      File "/usr/lib/python3/dist-packages/salt/scripts.py", line 431, in salt_call
        client.run()
      File "/usr/lib/python3/dist-packages/salt/cli/call.py", line 57, in run
        caller.run()
      File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 158, in run
        elif ret['retcode'] != salt.defaults.exitcodes.EX_OK:
    KeyError: 'retcode'
    Traceback (most recent call last):
      File "/usr/bin/salt-call", line 11, in <module>
        salt_call()
      File "/usr/lib/python3/dist-packages/salt/scripts.py", line 431, in salt_call
        client.run()
      File "/usr/lib/python3/dist-packages/salt/cli/call.py", line 57, in run
        caller.run()
      File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 158, in run
        elif ret['retcode'] != salt.defaults.exitcodes.EX_OK:
    KeyError: 'retcode'
    ```
- `salt-call --local state.orchestrate bugreport`
    ```
    [INFO    ] Loading fresh modules for state activity
    local:
        ----------
        data:
            ----------
            bug_report.host:
                - No matching sls found for 'bugreport' in env 'base'
        outputter:
            highstate
        retcode:
            1
    ```

### Versions Report
```
Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: 1.13.1
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: 4.1.0
          gitdb: 2.0.6
      gitpython: 3.0.5
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.4.4
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: 3.6.1
         pygit2: Not Installed
         Python: 3.7.5 (default, Oct 27 2019, 15:43:29)
   python-gnupg: Not Installed
         PyYAML: 5.1.2
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2

System Versions:
           dist: debian kali-rolling
         locale: UTF-8
        machine: x86_64
        release: 5.3.0-kali2-amd64
         system: Linux
        version: debian kali-rolling
```

**Comment by peterhirn** [comment]
`salt-call --local state.orch` is not aliased to `state.orchestrate` like in the runner, see https://github.com/saltstack/salt/blob/master/salt/runners/state.py#L139

`salt-call --local state.orchestrate bugreport` is not working because `salt-call --local` is only considering the minion config. Just add `file_roots` and `pillar_roots` to your minion config and you should be good.

**Comment by garethgreenaway** [comment]
@peterhirn Thanks for the responses.  @Fauxsys Please let us know if the above suggestions fix the issues you're seeing.
