### ISSUE TITLE
"TypeError: can not serialize 'lxml.etree._Element' object" when using junos proxy minion

### ISSUE THREAD

**Issue by tim-fiola** [saltstack/salt#55746]
### Description of Issue
Hello.  I'm using a Junos proxy minion and am creating an execution module called 'hello.get_uptime'.

My module appears to be executing properly until I hit an error.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Here is my execution module 
```
from jnpr.junos import Device

import logging
log = logging.getLogger(__name__)

### This works ###
def hello():
    return 'world'

def get_proxytype():
    # below is same as running 'salt ppr4b pillar.get proxy:proxytype' from cli
    proxytype = __pillar__.get("proxy", {}).get('proxytype')

    return proxytype

def proxy_dir():

    return dir(__proxy__)
### This works end ###


def get_uptime():

    conn = __proxy__['junos.conn']()
    uptime = conn.rpc.get_system_uptime_information()

    return uptime
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

Here is the output from the proxy minion debug.
2 things to note:
1.  I do indeed get the uptime information from the managed device back
2.  Later on, this error shows: **TypeError: can not serialize 'lxml.etree._Element' object**

```
[DEBUG   ] LazyLoaded proxy.handle_payload
[DEBUG   ] LazyLoaded proxy.target_load
[DEBUG   ] LazyLoaded proxy.handle_decoded_payload
[INFO    ] User sudo_tim Executing command hello.get_uptime with jid 20191227181230978659
[DEBUG   ] Command details {u'tgt_type': u'glob', u'jid': u'20191227181230978659', u'tgt': u'ppr4b', u'ret': u'', u'user': u'sudo_tim', u'arg': [], u'fun': u'hello.get_uptime'}
[DEBUG   ] Subprocess 20191227181230978659-Job-20191227181230978659 added
[DEBUG   ] LazyLoaded proxy.target
[DEBUG   ] LazyLoaded proxy.thread_return
[INFO    ] Starting a new job with PID 214870
[DEBUG   ] Could not LazyLoad {0}.allow_missing_func: '{0}.allow_missing_func' is not available.
[INFO    ] [host 10.13.138.65 session-id 24229] Requesting u'ExecuteRpc'
[DEBUG   ] [host 10.13.138.65 session-id 24229] queueing <?xml version="1.0" encoding="UTF-8"?><nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:52e75951-c7c8-49df-a863-3577be7fd1f1"><get-system-uptime-information/></nc:rpc>
[DEBUG   ] [host 10.13.138.65 session-id 24229] Sync request, will wait for timeout=30
[DEBUG   ] [host 10.13.138.65 session-id 24229] Sending message
[INFO    ] [host 10.13.138.65 session-id 24229] Sending:
<?xml version="1.0" encoding="UTF-8"?><nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:52e75951-c7c8-49df-a863-3577be7fd1f1"><get-system-uptime-information/></nc:rpc>]]>]]>
[DEBUG   ] [host 10.13.138.65 session-id 24229] parsing netconf v1.0
[DEBUG   ] [host 10.13.138.65 session-id 24229] parsing netconf v1.0
[DEBUG   ] [host 10.13.138.65 session-id 24229] parsing netconf v1.0
[DEBUG   ] [host 10.13.138.65 session-id 24229] parsing netconf v1.0
[DEBUG   ] [host 10.13.138.65 session-id 24229] parsing netconf v1.0
[DEBUG   ] [host 10.13.138.65 session-id 24229] parsing netconf v1.0
[DEBUG   ] [host 10.13.138.65 session-id 24229] parsing netconf v1.0
[DEBUG   ] [host 10.13.138.65 session-id 24229] parsing netconf v1.0
[DEBUG   ] [host 10.13.138.65 session-id 24229] parsing netconf v1.0
[DEBUG   ] [host 10.13.138.65 session-id 24229] parsing netconf v1.0
[DEBUG   ] [host 10.13.138.65 session-id 24229] parsing netconf v1.0
[DEBUG   ] [host 10.13.138.65 session-id 24229] parsing netconf v1.0
[DEBUG   ] [host 10.13.138.65 session-id 24229] parsing netconf v1.0
[DEBUG   ] [host 10.13.138.65 session-id 24229] parsing netconf v1.0
[DEBUG   ] [host 10.13.138.65 session-id 24229] parsing netconf v1.0
[DEBUG   ] [host 10.13.138.65 session-id 24229] parsing netconf v1.0
[DEBUG   ] [host 10.13.138.65 session-id 24229] parsing netconf v1.0
[DEBUG   ] [host 10.13.138.65 session-id 24229] parsing netconf v1.0
[DEBUG   ] [host 10.13.138.65 session-id 24229] parsing netconf v1.0
[DEBUG   ] [host 10.13.138.65 session-id 24229] parsing netconf v1.0
[DEBUG   ] [host 10.13.138.65 session-id 24229] parsing netconf v1.0
[DEBUG   ] [host 10.13.138.65 session-id 24229] parsing netconf v1.0
[DEBUG   ] [host 10.13.138.65 session-id 24229] parsing netconf v1.0
[DEBUG   ] [host 10.13.138.65 session-id 24229] parsing netconf v1.0
[DEBUG   ] [host 10.13.138.65 session-id 24229] parsing netconf v1.0
[DEBUG   ] [host 10.13.138.65 session-id 24229] parsing netconf v1.0
[DEBUG   ] [host 10.13.138.65 session-id 24229] parsing netconf v1.0
[DEBUG   ] [host 10.13.138.65 session-id 24229] parsing netconf v1.0
[DEBUG   ] [host 10.13.138.65 session-id 24229] parsing netconf v1.0
[INFO    ] [host 10.13.138.65 session-id 24229] Received message from host
[DEBUG   ] [host 10.13.138.65 session-id 24229] Received:
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:junos="http://xml.juniper.net/junos/17.3R3/junos" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:52e75951-c7c8-49df-a863-3577be7fd1f1">
<system-uptime-information xmlns="http://xml.juniper.net/junos/17.3R3/junos">
<current-time>
<date-time junos:seconds="1577488347">2019-12-27 18:12:27 EST</date-time>
</current-time>
<time-source>
 NTP CLOCK 
</time-source>
<system-booted-time>
<date-time junos:seconds="1571850157">2019-10-23 13:02:37 EDT</date-time>
<time-length junos:seconds="5638190">9w2d 06:09</time-length>
</system-booted-time>
<protocols-started-time>
<date-time junos:seconds="1571850195">2019-10-23 13:03:15 EDT</date-time>
<time-length junos:seconds="5638152">9w2d 06:09</time-length>
</protocols-started-time>
<last-configured-time>
<date-time junos:seconds="1577483717">2019-12-27 16:55:17 EST</date-time>
<time-length junos:seconds="4630">01:17:10</time-length>
<user>tim</user>
</last-configured-time>
<uptime-information>
<date-time junos:seconds="1577488347">
6:12PM
</date-time>
<up-time junos:seconds="5638200">
65 days,  6:10
</up-time>
<active-user-count junos:format="1 users">
1
</active-user-count>
<load-average-1>
0.09
</load-average-1>
<load-average-5>
0.17
</load-average-5>
<load-average-15>
0.16
</load-average-15>
<user-table>
</user-table>
</uptime-information>
</system-uptime-information>
</rpc-reply>
[DEBUG   ] [host 10.13.138.65 session-id 24229] dispatching message to <ncclient.transport.session.NotificationHandler object at 0x7f8e1f516110>: <rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:junos="http://xml.juniper.net/junos/17.3R3/junos" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:52e75951-c7c8-49df-a863-3577be7fd1f1">
<system-uptime-information xmlns="http://xml.juniper.net/junos/17.3R3/junos">
<current-time>
<date-time junos:seconds="1577488347">2019-12-27 18:12:27 EST</date-time>
</current-time>
<time-source>
 NTP CLOCK 
</time-source>
<system-booted-time>
<date-time junos:seconds="1571850157">2019-10-23 13:02:37 EDT</date-time>
<time-length junos:seconds="5638190">9w2d 06:09</time-length>
</system-booted-time>
<protocols-started-time>
<date-time junos:seconds="1571850195">2019-10-23 13:03:15 EDT</date-time>
<time-length junos:seconds="5638152">9w2d 06:09</time-length>
</protocols-started-time>
<last-configured-time>
<date-time junos:seconds="1577483717">2019-12-27 16:55:17 EST</date-time>
<time-length junos:seconds="4630">01:17:10</time-length>
<user>tim</user>
</last-configured-time>
<uptime-information>
<date-time junos:seconds="1577488347">
6:12PM
</date-time>
<up-time junos:seconds="5638200">
65 days,  6:10
</up-time>
<active-user-count junos:format="1 users">
1
</active-user-count>
<load-average-1>
0.09
</load-average-1>
<load-average-5>
0.17
</load-average-5>
<load-average-15>
0.16
</load-average-15>
<user-table>
</user-table>
</uptime-information>
</system-uptime-information>
</rpc-reply>
[DEBUG   ] [host 10.13.138.65 session-id 24229] dispatching message to <jnpr.junos.device.DeviceSessionListener object at 0x7f8e1f51e8d0>: <rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:junos="http://xml.juniper.net/junos/17.3R3/junos" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:52e75951-c7c8-49df-a863-3577be7fd1f1">
<system-uptime-information xmlns="http://xml.juniper.net/junos/17.3R3/junos">
<current-time>
<date-time junos:seconds="1577488347">2019-12-27 18:12:27 EST</date-time>
</current-time>
<time-source>
 NTP CLOCK 
</time-source>
<system-booted-time>
<date-time junos:seconds="1571850157">2019-10-23 13:02:37 EDT</date-time>
<time-length junos:seconds="5638190">9w2d 06:09</time-length>
</system-booted-time>
<protocols-started-time>
<date-time junos:seconds="1571850195">2019-10-23 13:03:15 EDT</date-time>
<time-length junos:seconds="5638152">9w2d 06:09</time-length>
</protocols-started-time>
<last-configured-time>
<date-time junos:seconds="1577483717">2019-12-27 16:55:17 EST</date-time>
<time-length junos:seconds="4630">01:17:10</time-length>
<user>tim</user>
</last-configured-time>
<uptime-information>
<date-time junos:seconds="1577488347">
6:12PM
</date-time>
<up-time junos:seconds="5638200">
65 days,  6:10
</up-time>
<active-user-count junos:format="1 users">
1
</active-user-count>
<load-average-1>
0.09
</load-average-1>
<load-average-5>
0.17
</load-average-5>
<load-average-15>
0.16
</load-average-15>
<user-table>
</user-table>
</uptime-information>
</system-uptime-information>
</rpc-reply>
[DEBUG   ] [host 10.13.138.65 session-id 24229] dispatching message to <ncclient.operations.rpc.RPCReplyListener object at 0x7f8e1f49d150>: <rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:junos="http://xml.juniper.net/junos/17.3R3/junos" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:52e75951-c7c8-49df-a863-3577be7fd1f1">
<system-uptime-information xmlns="http://xml.juniper.net/junos/17.3R3/junos">
<current-time>
<date-time junos:seconds="1577488347">2019-12-27 18:12:27 EST</date-time>
</current-time>
<time-source>
 NTP CLOCK 
</time-source>
<system-booted-time>
<date-time junos:seconds="1571850157">2019-10-23 13:02:37 EDT</date-time>
<time-length junos:seconds="5638190">9w2d 06:09</time-length>
</system-booted-time>
<protocols-started-time>
<date-time junos:seconds="1571850195">2019-10-23 13:03:15 EDT</date-time>
<time-length junos:seconds="5638152">9w2d 06:09</time-length>
</protocols-started-time>
<last-configured-time>
<date-time junos:seconds="1577483717">2019-12-27 16:55:17 EST</date-time>
<time-length junos:seconds="4630">01:17:10</time-length>
<user>tim</user>
</last-configured-time>
<uptime-information>
<date-time junos:seconds="1577488347">
6:12PM
</date-time>
<up-time junos:seconds="5638200">
65 days,  6:10
</up-time>
<active-user-count junos:format="1 users">
1
</active-user-count>
<load-average-1>
0.09
</load-average-1>
<load-average-5>
0.17
</load-average-5>
<load-average-15>
0.16
</load-average-15>
<user-table>
</user-table>
</uptime-information>
</system-uptime-information>
</rpc-reply>
[DEBUG   ] [host 10.13.138.65 session-id 24229] Delivering to <ncclient.operations.third_party.juniper.rpc.ExecuteRpc object at 0x7f8e2d203050>
[DEBUG   ] Minion return retry timer set to 6 seconds (randomized)
[INFO    ] Returning information for job: 20191227181230978659
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/proxy', 'ppr4b', u'tcp://127.0.0.1:4506', u'aes')
[DEBUG   ] Initializing new AsyncAuth for (u'/etc/salt/pki/proxy', 'ppr4b', u'tcp://127.0.0.1:4506')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://127.0.0.1:4506
[DEBUG   ] Trying to connect to: tcp://127.0.0.1:4506
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
Exception in thread 20191227181230978659-Job-20191227181230978659:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/salt/minion.py", line 3369, in _target
    return mp_call(cls, minion_instance, opts, data, connected)
  File "/usr/local/lib/python2.7/dist-packages/salt/metaproxy/proxy.py", line 328, in target
    ProxyMinion._thread_return(minion_instance, opts, data)
  File "/usr/local/lib/python2.7/dist-packages/salt/minion.py", line 3374, in _thread_return
    return mp_call(cls, minion_instance, opts, data)
  File "/usr/local/lib/python2.7/dist-packages/salt/metaproxy/proxy.py", line 509, in thread_return
    timeout=minion_instance._return_retry_timer()
  File "/usr/local/lib/python2.7/dist-packages/salt/minion.py", line 1997, in _return_pub
    ret_val = self._send_req_sync(load, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/salt/minion.py", line 1411, in _send_req_sync
    return channel.send(load, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/salt/utils/asynchronous.py", line 64, in wrap
    ret = self._block_future(ret)
  File "/usr/local/lib/python2.7/dist-packages/salt/utils/asynchronous.py", line 74, in _block_future
    return future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 383, in send
    ret = yield self._crypted_transfer(load, tries=tries, timeout=timeout, raw=raw)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 351, in _crypted_transfer
    ret = yield _do_transfer()
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/usr/local/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 333, in _do_transfer
    self._package_load(self.auth.crypticle.dumps(load)),
  File "/usr/local/lib/python2.7/dist-packages/salt/crypt.py", line 1470, in dumps
    return self.encrypt(self.PICKLE_PAD + self.serial.dumps(obj))
  File "/usr/local/lib/python2.7/dist-packages/salt/payload.py", line 240, in dumps
    return msgpack.dumps(msg, default=ext_type_encoder, use_bin_type=use_bin_type)
  File "/usr/local/lib/python2.7/dist-packages/msgpack/__init__.py", line 46, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 284, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 290, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 287, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 234, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 281, in msgpack._cmsgpack.Packer._pack
TypeError: can not serialize 'lxml.etree._Element' object

[DEBUG   ] Subprocess 20191227181230978659-Job-20191227181230978659 cleaned up
```

Pillar files

```
root@softlayer:/srv/salt/_modules# cat /srv/pillar/ppr4b_details.sls 
proxy:
  proxytype: junos
  host: 10.13.138.65
  username: tim
  port: 830
  password: tim123

root@softlayer:/srv/salt/_modules# cat /srv/pillar/top.sls 
base:
  'ppr4b':
    - ppr4b_details

root@softlayer:/srv/salt/_modules# 
```
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
root@softlayer:/srv/salt/_modules# salt --versions-report
Salt Version:
           Salt: 2019.2.2
 
Dependency Versions:
           cffi: 1.13.2
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Oct  8 2019, 14:14:10)
   python-gnupg: Not Installed
         PyYAML: 5.2
          PyZMQ: 18.1.1
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 5.1.1
            ZMQ: 4.3.2
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-142-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by tim-fiola** [comment]
ah, nevermind.  I figured the problem: parsing the xml to text fixes this

def get_uptime():
    
    conn = __proxy__['junos.conn']()
    rpc1 = conn.rpc.get_system_uptime_information()


    uptime = rpc1.find('.//system-booted-time/time-length').attrib['seconds']    
    return uptime
