### ISSUE TITLE
NameError: name 'RSA' is not defined

### ISSUE THREAD

**Issue by babvin** [saltstack/salt#55782]
### Description of Issue
NameError: name 'RSA' is not defined
2020-01-03 01:25:10,047 [salt.minion :994 ][ERROR   ][3517] Minion unable to successfully connect to a Salt Master.

### Setup
(salt-minion) SALT-SLES11:~ # salt-minion --version
salt-minion 2019.2.1-2812-g4dd05be (Fluorine)
Running salt minion in Python venv (development) on  Suse 11 SP4

### Steps to Reproduce Issue
salt-minion -c /salt-minion/etc/salt -d

### Versions Report
(salt-minion) SALT-SLES11:~ # salt --versions-report
Salt Version:
           Salt: 2019.2.1-2812-g4dd05be

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10.3
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.10 (default, Jan  3 2020, 00:04:23)
   python-gnupg: Not Installed
         PyYAML: 5.2
          PyZMQ: 18.1.1
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2

System Versions:
           dist: SuSE 11 x86_64
         locale: UTF-8
        machine: x86_64
        release: 3.0.101-108.108-default
         system: Linux
        version: SUSE Linux Enterprise Server  11 x86_64

(salt-minion) SALT-SLES11:~ #

Traceback (most recent call last):
  File "/salt-minion/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/salt-minion/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/salt-minion/lib/python3.6/site-packages/tornado/ioloop.py", line 626, in _discard_future_result
    future.result()
  File "/salt-minion/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/salt-minion/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/salt/salt/crypt.py", line 604, in _authenticate
    creds = yield self.sign_in(channel=channel)
  File "/salt-minion/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/salt-minion/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/salt-minion/lib/python3.6/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/salt/salt/crypt.py", line 754, in sign_in
    auth['aes'] = self.verify_master(payload, master_pub='token' in sign_in_payload)
  File "/salt/salt/crypt.py", line 1121, in verify_master
    return self.extract_aes(payload, master_pub=False)
  File "/salt/salt/crypt.py", line 1042, in extract_aes
    aes, token = self.decrypt_aes(payload, master_pub)
  File "/salt/salt/crypt.py", line 868, in decrypt_aes
    key = self.get_keys()
  File "/salt/salt/crypt.py", line 795, in get_keys
    key = get_rsa_key(self.rsa_path, None)
  File "/salt/salt/crypt.py", line 201, in get_rsa_key
    return _get_key_with_evict(path, six.text_type(os.path.getmtime(path)), passphrase)
  File "/salt/salt/utils/decorators/__init__.py", line 284, in _memoize
    cache[args_] = func(*args, **kwargs)
  File "/salt/salt/crypt.py", line 185, in _get_key_with_evict
    key = RSA.importKey(f.read(), passphrase)
NameError: name 'RSA' is not defined
2020-01-03 01:25:10,047 [salt.minion                              :994 ][ERROR   ][3517] Minion unable to successfully connect to a Salt Master.

**Comment by frogunder** [comment]
@babvin thank you for reporting this issue.

@saltstack/team-suse any thoughts on this?

Thanks.

**Comment by sagetherage** [comment]
@frogunder I am not sure the @saltstack/team-suse is reaching the team or might be noisy GitHub emails, do you have a contact or @Akm0d maybe you have a contact with SUSE that might help here?

**Comment by brejoc** [comment]
@babvin I think for SLES11 you can't use 2019.2.x and you need to stick to 2016.11.x or of course upgrade your SLES installation. But if you are still in support, you can also open an issue with the SUSE support engineers.

**Comment by brejoc** [comment]
PS: This should be close from my point of view.
