### ISSUE TITLE
Need help unpacking salt pillar data

### ISSUE THREAD

**Issue by trc-af** [saltstack/salt#55803]
### Description of Issue

Recently upgraded to salt 2019 (py3), and am in the process of updating all out older salt scripts to python 3. One process reads pillar data for each host, unpacks it, and send it to a host for processing. msgpack for python3 has issues with unpacking this data. I'm hoping someone has experienced this issue already and has a fix or workaround.

### Setup

$ sudo cat /etc/redhat-release 
CentOS Linux release 7.5.1804 (Core)
$ sudo yum install python36-msgpack
```
#!/bin/env python3
import msgpack
datafile = '/var/cache/salt/master/minions/example.domain.com/data.p'
data = open(datafile, 'r')
x = msgpack.unpack(data, raw=True)
print( x )
```

### Steps to Reproduce Issue

To view expected output, replace the shebang with "/bin/env python" (to invoke python2). Python 3's msgpack returns the following error:

```
$ ./test.py 
Traceback (most recent call last):
  File "./test.py", line 82, in <module>
    test()
  File "./test.py", line 13, in test
    x = msgpack.unpack(data, raw=True)
  File "/usr/local/lib64/python3.6/site-packages/msgpack/__init__.py", line 56, in unpack
    data = stream.read()
  File "/usr/lib64/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 0: invalid start byte
```

### Versions Report

```
Salt Version:
           Salt: 2019.2.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.33.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Apr 25 2019, 21:02:35)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```

**Comment by trc-af** [comment]
To avoid any confusion, the script above is run on a salt master, and you must replace example.domain.com with an actual minion ID.

**Comment by oeuftete** [comment]
@trc-af You may want to try the various [Saltstack community resources](https://www.saltstack.com/resources/community/) for a question like this.  Lots of helpful folks on Slack/IRC.

That being said, I think opening your file in binary mode would address your problem:

```py
data = open(datafile, 'rb')
```
