### ISSUE TITLE
TypeError: 'int' object is not subscriptable

### ISSUE THREAD

**Issue by zhaodaiyang0574** [saltstack/salt#55883]
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by zhaodaiyang0574** [comment]
Salt Version:
           Salt: 2019.2.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.6 (default, Jan 16 2020, 13:47:09)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 18.1.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core

**Comment by zhaodaiyang0574** [comment]
[root@localhost pip-19.3.1]# salt '*' test.ping
[WARNING ] jid does not exist
[WARNING ] Returner unavailable: 
[ERROR   ] Exception occurred in Subscriber while handling stream: 'int' object is not subscriptable
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: 'int' object is not subscriptable
Traceback (most recent call last):
  File "/usr/local/python37/bin/salt", line 11, in <module>
    load_entry_point('salt==2019.2.3', 'console_scripts', 'salt')()
  File "/usr/local/python37/lib/python3.7/site-packages/salt/scripts.py", line 516, in salt_main
    client.run()
  File "/usr/local/python37/lib/python3.7/site-packages/salt/cli/salt.py", line 194, in run
    for full_ret in cmd_func(**kwargs):
  File "/usr/local/python37/lib/python3.7/site-packages/salt/client/__init__.py", line 777, in cmd_cli
    **kwargs):
  File "/usr/local/python37/lib/python3.7/site-packages/salt/client/__init__.py", line 1527, in get_cli_event_returns
    **kwargs
  File "/usr/local/python37/lib/python3.7/site-packages/salt/client/__init__.py", line 1104, in get_iter_returns
    for raw in ret_iter:
  File "/usr/local/python37/lib/python3.7/site-packages/salt/client/__init__.py", line 1038, in get_returns_no_block
    no_block=True, auto_reconnect=self.auto_reconnect)
  File "/usr/local/python37/lib/python3.7/site-packages/salt/utils/event.py", line 639, in get_event
    ret = self._get_event(wait, tag, match_func, no_block)
  File "/usr/local/python37/lib/python3.7/site-packages/salt/utils/event.py", line 545, in _get_event
    raw = self.subscriber.read_sync(timeout=wait)
  File "/usr/local/python37/lib/python3.7/site-packages/salt/transport/ipc.py", line 690, in read_sync
    return self.io_loop.run_sync(lambda: self._read(timeout))
  File "/usr/local/python37/lib/python3.7/site-packages/tornado/ioloop.py", line 458, in run_sync
    return future_cell[0].result()
  File "/usr/local/python37/lib/python3.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/python37/lib/python3.7/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/usr/local/python37/lib/python3.7/site-packages/salt/transport/ipc.py", line 675, in _read
    raise exc_to_raise  # pylint: disable=E0702
  File "/usr/local/python37/lib/python3.7/site-packages/salt/transport/ipc.py", line 652, in _read
    ret = framed_msg['body']
TypeError: 'int' object is not subscriptable
Traceback (most recent call last):
  File "/usr/local/python37/bin/salt", line 11, in <module>
    load_entry_point('salt==2019.2.3', 'console_scripts', 'salt')()
  File "/usr/local/python37/lib/python3.7/site-packages/salt/scripts.py", line 516, in salt_main
    client.run()
  File "/usr/local/python37/lib/python3.7/site-packages/salt/cli/salt.py", line 194, in run
    for full_ret in cmd_func(**kwargs):
  File "/usr/local/python37/lib/python3.7/site-packages/salt/client/__init__.py", line 777, in cmd_cli
    **kwargs):
  File "/usr/local/python37/lib/python3.7/site-packages/salt/client/__init__.py", line 1527, in get_cli_event_returns
    **kwargs
  File "/usr/local/python37/lib/python3.7/site-packages/salt/client/__init__.py", line 1104, in get_iter_returns
    for raw in ret_iter:
  File "/usr/local/python37/lib/python3.7/site-packages/salt/client/__init__.py", line 1038, in get_returns_no_block
    no_block=True, auto_reconnect=self.auto_reconnect)
  File "/usr/local/python37/lib/python3.7/site-packages/salt/utils/event.py", line 639, in get_event
    ret = self._get_event(wait, tag, match_func, no_block)
  File "/usr/local/python37/lib/python3.7/site-packages/salt/utils/event.py", line 545, in _get_event
    raw = self.subscriber.read_sync(timeout=wait)
  File "/usr/local/python37/lib/python3.7/site-packages/salt/transport/ipc.py", line 690, in read_sync
    return self.io_loop.run_sync(lambda: self._read(timeout))
  File "/usr/local/python37/lib/python3.7/site-packages/tornado/ioloop.py", line 458, in run_sync
    return future_cell[0].result()
  File "/usr/local/python37/lib/python3.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/python37/lib/python3.7/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/usr/local/python37/lib/python3.7/site-packages/salt/transport/ipc.py", line 675, in _read
    raise exc_to_raise  # pylint: disable=E0702
  File "/usr/local/python37/lib/python3.7/site-packages/salt/transport/ipc.py", line 652, in _read
    ret = framed_msg['body']
TypeError: 'int' object is not subscriptable

**Comment by Ch3LL** [comment]
im not able to replicate this. does this occur for any salt command your running?

also can you share a sanitized version of your configs to help replicate?
