### ISSUE TITLE
Need to update version.py to work with new release version (3000)

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#55896]
### Description of Issue
When changing in salt/version.py Neon to version 3000, the doc tests fail.

Change in version.py:
```
        'Oxygen'        : (2018, 3),
        'Fluorine'      : (2019, 2),
        'Neon'          : (3000),
        'Sodium'        : (MAX_SIZE - 98, 0),
```

Get this error in the doc build:
```
15:27:37  Configuration error:
15:27:37  There is a programmable error in your configuration file:
15:27:37  
15:27:37  Traceback (most recent call last):
15:27:37    File "/var/jenkins/workspace/pr-docs_PR-55875/.nox/docs-html-compress-true/lib/python3.6/site-packages/sphinx/config.py", line 361, in eval_config_file
15:27:37      execfile_(filename, namespace)
15:27:37    File "/var/jenkins/workspace/pr-docs_PR-55875/.nox/docs-html-compress-true/lib/python3.6/site-packages/sphinx/util/pycompat.py", line 86, in execfile_
15:27:37      exec(code, _globals)
15:27:37    File "/var/jenkins/workspace/pr-docs_PR-55875/doc/conf.py", line 239, in <module>
15:27:37      import salt.version
15:27:37    File "/var/jenkins/workspace/pr-docs_PR-55875/salt/version.py", line 60, in <module>
15:27:37      class SaltStackVersion(object):
15:27:37    File "/var/jenkins/workspace/pr-docs_PR-55875/salt/version.py", line 215, in SaltStackVersion
15:27:37      RMATCH = dict((v[:2], k) for (k, v) in iter(NAMES.items()))
15:27:37    File "/var/jenkins/workspace/pr-docs_PR-55875/salt/version.py", line 215, in <genexpr>
15:27:37      RMATCH = dict((v[:2], k) for (k, v) in iter(
```

**Comment by frogunder** [comment]
Its related to this https://github.com/saltstack/salt/pull/55875

**Comment by dmurphy18** [comment]
it is also related to https://github.com/saltstack/salt/issues/55892

**Comment by waynew** [comment]
Should it not be `(3000,0)`?
