### ISSUE TITLE
HgPillarTestCase.test_base fails

### ISSUE THREAD

**Issue by bdrung** [saltstack/salt#55935]
The `HgPillarTestCase.test_base` test case fail:

```
$ LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 python3 ./tests/runtests.py -v --no-report -n unit.pillar.test_hg_pillar.HgPillarTestCase
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Python Version: 3.7.5 (default, Nov 20 2019, 09:21:52) [GCC 9.2.1 20191008]
 * Transplanting configuration files to '/tmp/salt-tests-tmpdir/config'
 * Transplanting multimaster configuration files to '/tmp/salt-tests-tmpdir/config'
 * Current Directory: /home/bdrung/projects/salt/upstream
 * Test suite is running under PID 9381
 * Logging tests on /tmp/salt-runtests.log
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Starting unit.pillar.test_hg_pillar.HgPillarTestCase Tests
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
test_base (unit.pillar.test_hg_pillar.HgPillarTestCase)
[CPU:9.5%|MEM:51.7%] check hg repo is imported correctly ... Füge top.sls hinzu
Füge user.sls hinzu
18:08:29,187 [salt.template              :236 ][ERROR   ] The renderer "yaml_jinja" is not available
18:08:29,187 [salt.loader                :650 ][CRITICAL] The renderer yaml_jinja is unavailable, this error is often because the needed software is unavailable
ERROR
Exception ignored in: <function Pillar.__del__ at 0x7f35cf6e5710>
Traceback (most recent call last):
  File "salt/pillar/__init__.py", line 1126, in __del__
    self.destroy()
  File "salt/pillar/__init__.py", line 1121, in destroy
    if self._closing:
AttributeError: 'Pillar' object has no attribute '_closing'

======================================================================
ERROR: test_base (unit.pillar.test_hg_pillar.HgPillarTestCase)
[CPU:13.2%|MEM:51.7%] check hg repo is imported correctly
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/unit/pillar/test_hg_pillar.py", line 78, in test_base
    mypillar = hg_pillar.ext_pillar('*', None, 'file://{0}'.format(self.hg_repo_path))
  File "salt/pillar/hg_pillar.py", line 83, in ext_pillar
    pil = salt.pillar.Pillar(opts, __grains__, minion_id, envname)
  File "salt/pillar/__init__.py", line 390, in __init__
    self.rend = salt.loader.render(self.opts, self.functions)
  File "salt/loader.py", line 651, in render
    raise LoaderError(err)
salt.exceptions.LoaderError: The renderer yaml_jinja is unavailable, this error is often because the needed software is unavailable

----------------------------------------------------------------------
Ran 1 test in 0.439s

FAILED (errors=1)
```

This test case is consistently failing on Debian stable, testing, and unstable as well on Ubuntu. I am using salt 2019.2.3.

**Comment by xeacott** [comment]
Thanks for the report. Although I did leave a comment in the other reported failure, this kind of seems to be slightly related? 

I also checked this test and this is a test we skip in our system, unsure why though.

**Comment by bdrung** [comment]
I don't see a connection here. These are two different tests. `HgPillarTestCase.test_base` fails on all Debian and Ubuntu versions that I tried.

**Comment by xeacott** [comment]
I should have changed my comment, as I initially thought this test was passing in our CI system. :) So not related at all. I can investigate why this test is being skipped on our end.

**Comment by bdrung** [comment]
This issue is still open.

**Comment by bdrung** [comment]
still open

**Comment by bdrung** [comment]
Commit 399835f672771db8a25ebc6efd71709984a9a11f removed this failing test case. So this bug is solved.
