### ISSUE TITLE
netmiko proxy with always_alive does not work properly

### ISSUE THREAD

**Issue by sindhukothe** [saltstack/salt#55945]
### Description of Issue
Using netmiko proxy with always_alive flag set to true has the following issue:
Once the proxy connects to the device, and device closes the connection for whatever reason (idle timeout on the device or device rebooted etc), netmiko proxy does not check if the connection is active for further communications. It assumes the connection is always alive and sends the commands to the device, which causes exception. Only workaround is to restart the proxy.
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
1. Use netmiko proxy (with always_alive set to true) and execute a command on the device.
2. Go to the device and kill the user session (clear vty line in case of cisco)
3. try to execute a command on device through netmiko proxy.
### Versions Report
bash-4.4$ salt --versions-report
Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: 1.12.3
       cherrypy: unknown
       dateutil: 2.7.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: 0.27.7
        libnacl: Not Installed
       M2Crypto: 0.33.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.27.4
         Python: 2.7.16 (default, May  6 2019, 19:35:26)
   python-gnupg: 0.4.2
         PyYAML: 5.1.1
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.5.1.el7.x86_64
         system: Linux
        version: Not Installed

**Comment by xeacott** [comment]
Thanks for the report. I asked a core member about this who has more experience than I and unfortunately there are known issues with the netmiko proxy around loosing connections. But I'll try to follow up with a bit more information when I learn more.

**Comment by garethgreenaway** [comment]
@sindhukothe Thanks for the report.   The `always_alive` parameter when True (the default) indicates that the connection that this proxy minion is using should always be considered as alive or connected to the host, when it's False then the proxy minion will connect only when it needs to run a command then disconnect immediately afterwards.  Some basic testing of having the `netmiko` proxy minion connect to a Linux, when the SSH session is killed on the server then `netmiko` appears to reconnect, it's possible that this functionality doesn't exist in the code that is handling other devices.  Can you provide the exception that you're seeing?

**Comment by sindhukothe** [comment]
I am able to reproduce this with cisco nx-os devices consistently using netmiko proxy with always_alive = true.
1. Start the proxy
```
bash-4.4$ python2 /usr/bin/salt-proxy --proxyid=<proxy_id> -d -l debug --log-file=/tmp/t
[DEBUG   ] Reading configuration from /etc/salt/proxy
[DEBUG   ] Configuration file path: /etc/salt/proxy
```
2. Execute show version
```
bash-4.4$ salt '<proxy_id>' common.cli 'show version'
... show version output comes here...
```
3. Login into device and kill the line (to simulate idle timeout or restart)
```
# clear line pts/27
```
4.  Try the show version again:
```
bash-4.4$ salt '<proxy_id>' common.cli 'show version'
<proxy_id>:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/metaproxy/proxy.py", line 397, in thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/var/cache/salt/proxy/extmods/bcr02b.sng01/modules/common.py", line 32, in cli
        return __salt__['netmiko.send_command'](command)
      File "/var/cache/salt/proxy/extmods/bcr02b.sng01/modules/netmiko_mod.py", line 395, in send_command
        return call('send_command', command_string, **kwargs)
      File "/var/cache/salt/proxy/extmods/bcr02b.sng01/modules/netmiko_mod.py", line 313, in call
        return __proxy__['netmiko.call'](method, *args, **kwargs)
      File "/usr/lib/python2.7/site-packages/salt/proxy/netmiko_px.py", line 322, in call
        return getattr(netmiko_device['connection'], method)(*args, **kwargs)
      File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 1244, in send_command
        prompt = self.find_prompt(delay_factor=delay_factor)
      File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 1055, in find_prompt
        self.write_channel(self.RETURN)
      File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 407, in write_channel
        self._write_channel(out_data)
      File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 374, in _write_channel
        self.remote_conn.sendall(write_bytes(out_data, encoding=self.encoding))
      File "/usr/lib/python2.7/site-packages/paramiko/channel.py", line 846, in sendall
        sent = self.send(s)
      File "/usr/lib/python2.7/site-packages/paramiko/channel.py", line 801, in send
        return self._send(s, m)
      File "/usr/lib/python2.7/site-packages/paramiko/channel.py", line 1180, in _send
        raise socket.error("Socket is closed")
    error: Socket is closed
ERROR: Minions returned with non-zero exit code
bash-4.4$
```

**Comment by alan-cugler** [comment]
https://docs.saltstack.com/en/latest/ref/proxy/all/salt.proxy.netmiko_px.html has the option listed with a less than clear explanation that @garethgreenaway left commented here. 

@saltstack/docs-working-group will take @garethgreenaway clarification comment and add that clarification to the docs?
