### ISSUE TITLE
salt incompatible with msgpack >= 1.0.0rc1

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#56007]
### Description of Issue
When using msgpack 1.0.0rc1 I see this error:

```
Process salt.transport.zeromq.<class 'method'>._publish_daemon:
Traceback (most recent call last):
  File "/home/ch3ll/.pyenv/versions/3.6.9/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/ch3ll/.pyenv/versions/3.6.9/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ch3ll/git/salt/salt/transport/zeromq.py", line 920, in _publish_daemon
    unpacked_package = salt.payload.unpackage(package)
  File "/home/ch3ll/git/salt/salt/payload.py", line 47, in unpackage
    return salt.utils.msgpack.loads(package_, use_list=True)
  File "/home/ch3ll/git/salt/salt/utils/msgpack.py", line 128, in unpackb
    return msgpack.unpackb(packed, **_sanitize_msgpack_kwargs(kwargs))
  File "msgpack/_unpacker.pyx", line 195, in msgpack._cmsgpack.unpackb
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 0: invalid start byte
```

when trying to run any commands against a minion.

### Setup
`pip install --pre --upgrade msgpack` or `python setup.py install` in salt repo.

### Steps to Reproduce Issue
1. install msgpack 1.0.0rc1
2. `salt '*' test.ping`

### Versions Report

```
Salt Version:
           Salt: 3000rc2-29-g796265c5be

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: 4.1.0
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10.3
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.9.4
         pygit2: Not Installed
         Python: 2.7.16 (default, Nov 21 2019, 13:15:23)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 18.1.1
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 5.1.1
            ZMQ: 4.3.2

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 5.4.14-2-MANJARO
         system: Linux
        version: Not Installed
```

**Comment by prometheanfire** [comment]
This is now blocking msgpack in openstack.  See commit message here.  https://github.com/openstack/requirements/commit/825c615e5ae2d71f0bf0fbeaf9a5de377c09adf6

When can the cap be removed?

**Comment by Ch3LL** [comment]
this is tagged to be fixed for the sodium release. looking to work on it this week, when other 3000.1 release priorities do not come up.

**Comment by prometheanfire** [comment]
so, how's it going?

**Comment by Ch3LL** [comment]
this is still slated for sodium. Had to migrate to other tasks before this one, but this is still committed to for sodium.

**Comment by mirceaulinic** [comment]
Was there a plan to address this issue for past releases as well?

**Comment by prometheanfire** [comment]
The fix looks like is in sodium (3001_rc1).  The requirements/base.txt needs to remove the cap now

**Comment by ihakh** [comment]
this works for me:
```
async def get_event(filter_tag=''):
        stream_reader, _ = await asyncio.open_unix_connection('/var/run/salt/master/master_event_pub.ipc')
        unpacker_raw = Unpacker(raw=True)
        unpacker = Unpacker(raw=False)
        while True:
            b= await stream_reader.read(1024)
            # print(b)
            unpacker_raw.feed(b)
            for b1 in unpacker_raw:
                b1=b1[b'body']
                # print(b1)
                tag, data = b1.split(b'\n\n')
                tag = tag.decode()
                if filter_tag in tag:
                    unpacker.feed(data)
                    d=unpacker.unpack()
                    yield (tag, d)
```

**Comment by ihakh** [comment]
just explicitly set the `raw` option

**Comment by sagetherage** [comment]
closing as we upgraded to mspack 1.0, and please reference this issue if more issues arise.
