### ISSUE TITLE
seeing ZMQ errors on 2019.2.2 minion 

### ISSUE THREAD

**Issue by bilalbaqar** [saltstack/salt#56049]
### Description of Issue

Seeing the following error message in minion logs when any long running (~15sec+) job is submitted to the minion. 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py", line 456, in _handle_events
    self._handle_recv()
  File "/usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py", line 476, in _handle_recv
    msg = self.socket.recv_multipart(zmq.NOBLOCK, copy=self._recv_copy)
  File "/usr/local/lib/python3.6/dist-packages/zmq/sugar/socket.py", line 475, in recv_multipart
    parts = [self.recv(flags, copy=copy, track=track)]
  File "zmq/backend/cython/socket.pyx", line 791, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 827, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 195, in zmq.backend.cython.socket._recv_copy
  File "zmq/backend/cython/message.pxd", line 61, in zmq.backend.cython.message.copy_zmq_msg_bytes
SystemError: Negative size passed to PyBytes_FromStringAndSize
2020-02-01 00:00:18,198 [tornado.application:638 ][ERROR   ][1809] Exception in callback (<zmq.sugar.socket.Socket object at 0x7f39051f5048>, <function wrap.<locals>.wrapped at 0x7f3902
69cb70>)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/usr/lib/python3/dist-packages/tornado/stack_context.py", line 345, in wrapped
    raise_exc_info(exc)
  File "<string>", line 4, in raise_exc_info
  File "/usr/lib/python3/dist-packages/tornado/stack_context.py", line 316, in wrapped
    ret = fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py", line 456, in _handle_events
    self._handle_recv()
  File "/usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py", line 476, in _handle_recv
    msg = self.socket.recv_multipart(zmq.NOBLOCK, copy=self._recv_copy)
  File "/usr/local/lib/python3.6/dist-packages/zmq/sugar/socket.py", line 475, in recv_multipart
    parts = [self.recv(flags, copy=copy, track=track)]
  File "zmq/backend/cython/socket.pyx", line 791, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 827, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 195, in zmq.backend.cython.socket._recv_copy
  File "zmq/backend/cython/message.pxd", line 61, in zmq.backend.cython.message.copy_zmq_msg_bytes
SystemError: Negative size passed to PyBytes_FromStringAndSize
```
Sometimes see `MemoryError` instread of `SystemError: Negative size passed to PyBytes_FromStringAndSize`

### Setup
master installed via pip3 on ubuntu 16.04 under python3 virtualenv. Minion setup via salt bootstrap with following extra params `-H http://cloud-proxy:port -x python3 stable 2019.2.2`

minion config:
```
backend: requests
hash_type: sha256
id: dev-machine-1
log_level: info
master: 172.21.X.X
mine_functions:
  grains.items: []
  network.ip_addrs: []
```

### Steps to Reproduce Issue

Minions gets added to salt master successfully. Most short-run modules like `test.ping` run fine but anything that takes longer like `state.highstate` returns with `Minion did not return. [No response]`
the minion log shows the error message shown at the top. 

`state.highstate` works fine if the states being applied do not take that long. 

### Versions Report
Salt master:
```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.13.2
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.5
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.2 (default, Oct  8 2019, 13:06:37)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 2.2.0
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-166-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

Salt minion:
```
salt-minion ion --versions-report
Salt Version:
           Salt: 2019.2.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.9 (default, Nov  7 2019, 10:44:02)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 18.1.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-76-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```

**Comment by Ch3LL** [comment]
your zmq verison is very old: `            ZMQ: 2.2.0`, does upgrading help resolve the issue?

**Comment by sagetherage** [comment]
@bilalbaqar are you still seeing this issue on a current supported version of Salt and/or another ZMQ version?

**Comment by sagetherage** [comment]
@bilalbaqar are you still seeing this issue on a current, supported version of Salt/ZMQ?

Reviewed in Grooming 2021-JUL-19 considering closing

**Comment by bilalbaqar** [comment]
> @bilalbaqar are you still seeing this issue on a current, supported version of Salt/ZMQ?
> 
> Reviewed in Grooming 2021-JUL-19 considering closing

I am no longer seeing this issue. We can close it.
