### ISSUE TITLE
Salt-call Traceback on Amazon Linux 2

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#56059]
### Description of Issue
When running salt-call commands on an Python 2, Amazon Linux 2 machine on 3000, it gives this traceback.
Command runs fine and returns, it just also gives this traceback:
```
                                [ERROR   ] Failed to import grains esxi, this is due most likely to a syntax error:
                                Traceback (most recent call last):
                                  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1607, in _load_module
                                    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
                                  File "/usr/lib/python2.7/site-packages/salt/grains/esxi.py", line 16, in <module>
                                    import salt.modules.vsphere
                                  File "/usr/lib/python2.7/site-packages/salt/modules/vsphere.py", line 222, in <module>
                                    import jsonschema
                                  File "/usr/lib/python2.7/site-packages/jsonschema/__init__.py", line 18, in <module>
                                    from jsonschema.validators import (
                                  File "/usr/lib/python2.7/site-packages/jsonschema/validators.py", line 163, in <module>
                                    meta_schema=_utils.load_schema("draft3"),
                                  File "/usr/lib/python2.7/site-packages/jsonschema/_utils.py", line 57, in load_schema
                                    data = pkgutil.get_data('jsonschema', "schemas/{0}.json".format(name))
                                  File "/usr/lib64/python2.7/pkgutil.py", line 576, in get_data
                                    loader = get_loader(package)
                                  File "/usr/lib64/python2.7/pkgutil.py", line 462, in get_loader
                                    return find_loader(fullname)
                                  File "/usr/lib64/python2.7/pkgutil.py", line 473, in find_loader
                                    loader = importer.find_module(fullname)
                                TypeError: find_module() takes exactly 3 arguments (2 given)
```

### Versions Report
```
                                Salt Version:
                                           Salt: 3000
                                 
                                Dependency Versions:
                                           cffi: 1.6.0
                                       cherrypy: unknown
                                       dateutil: 2.6.0
                                      docker-py: Not Installed
                                          gitdb: Not Installed
                                      gitpython: Not Installed
                                         Jinja2: 2.7.2
                                        libgit2: Not Installed
                                       M2Crypto: Not Installed
                                           Mako: Not Installed
                                   msgpack-pure: Not Installed
                                 msgpack-python: 0.6.2
                                   mysql-python: Not Installed
                                      pycparser: 2.14
                                       pycrypto: 2.6.1
                                   pycryptodome: Not Installed
                                         pygit2: Not Installed
                                         Python: 2.7.16 (default, Dec 12 2019, 23:58:22)
                                   python-gnupg: Not Installed
                                         PyYAML: 3.10
                                          PyZMQ: 15.3.0
                                          smmap: Not Installed
                                        timelib: Not Installed
                                        Tornado: 4.5.3
                                            ZMQ: 4.1.4
                                 
                                System Versions:
                                           dist:   
                                         locale: ascii
                                        machine: x86_64
                                        release: 4.14.70-72.55.amzn2.x86_64
                                         system: Linux
                                        version: Not Installed
```

**Comment by dhiltonp** [comment]
Closing this in favor of #56063, thanks Frode :)
