### ISSUE TITLE
salt-ssh fails with FreeBSD target and 'unless' requisite

### ISSUE THREAD

**Issue by amendlik** [saltstack/salt#56078]
### Description of Issue
When using salt-ssh, with the target system running FreeBSD, state execution fails if the SLS contains an `unless` requisite.

### Setup
Here is the SLS I'm using to reproduce this issue:
```
demo:
  test.nop:
    - unless: true
```

### Steps to Reproduce Issue
```
# salt-ssh <node> state.apply demo
[ERROR   ] JSON Render failed for: 
Traceback (most recent call last):
  File "/var/tmp/.amendlik_e98484_salt/salt-call", line 27, in <module>
    salt_call()
  File "/var/tmp/.amendlik_e98484_salt/pyall/salt/scripts.py", line 431, in salt_call
    client.run()
  File "/var/tmp/.amendlik_e98484_salt/pyall/salt/cli/call.py", line 57, in run
    caller.run()
  File "/var/tmp/.amendlik_e98484_salt/pyall/salt/cli/caller.py", line 138, in run
    ret = self.call()
  File "/var/tmp/.amendlik_e98484_salt/pyall/salt/cli/caller.py", line 237, in call
    ret['return'] = self.minion.executors[fname](self.opts, data, func, args, kwargs)
  File "/var/tmp/.amendlik_e98484_salt/pyall/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/var/tmp/.amendlik_e98484_salt/pyall/salt/modules/state.py", line 2198, in pkg
    _set_retcode(ret)
  File "/var/tmp/.amendlik_e98484_salt/pyall/salt/modules/state.py", line 107, in _set_retcode
    if not __utils__['state.check_result'](ret, highstate=highstate):
  File "/var/tmp/.amendlik_e98484_salt/pyall/salt/loader.py", line 1208, in __getitem__
    func = super(LazyLoader, self).__getitem__(item)
  File "/var/tmp/.amendlik_e98484_salt/pyall/salt/utils/lazy.py", line 108, in __getitem__
    raise KeyError(key)
KeyError: 'state.check_result'
[ERROR   ] Expecting value: line 1 column 1 (char 0)
demo:
```

### Versions Report
**Source:**
```
Salt Version:
           Salt: 2019.2.1rc0
 
Dependency Versions:
           cffi: 1.12.3
       cherrypy: Not Installed
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 3.0.2
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.35.2
           Mako: 1.1.0
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.6 (default, Dec 19 2019, 22:52:49)
   python-gnupg: Not Installed
         PyYAML: 5.1.2
          PyZMQ: 18.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 6.0.2
            ZMQ: 4.3.2
 
System Versions:
           dist: fedora 31 Thirty One
         locale: UTF-8
        machine: x86_64
        release: 5.4.13-201.fc31.x86_64
         system: Linux
        version: Fedora 31 Thirty One
```
**Target:**
```
    Salt Version:
               Salt: 2019.2.1rc0
     
    Dependency Versions:
               cffi: 1.13.2
           cherrypy: Not Installed
           dateutil: 2.8.0
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.10.1
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.6.1
       mysql-python: Not Installed
          pycparser: 2.19
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 3.7.6 (default, Jan  4 2020, 02:40:34)
       python-gnupg: Not Installed
             PyYAML: 5.1.2
              PyZMQ: 18.1.1
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 6.0.2
                ZMQ: 4.3.1
     
    System Versions:
               dist:   
             locale: UTF-8
            machine: amd64
            release: 11.2-STABLE
             system: FreeBSD
            version: Not Installed
```

**Comment by max-arnold** [comment]
2019.2.1 is exceptionally buggy (example: https://github.com/saltstack/salt/issues/54804). 

Can you try 2019.2.3?

**Comment by amendlik** [comment]
I can't reproduce this with 2019.2.3.

How can I obtain a 2019.2.3 build for Fedora?

**Comment by sagetherage** [comment]
@dmurphy18 can you help here?

**Comment by amendlik** [comment]
@dmurphy18 Any update?

**Comment by amendlik** [comment]
I need to rescind my earlier comment. I **am** able to consistently reproduce this error using v3000.
```
Salt Version:
           Salt: 3000
 
Dependency Versions:
           cffi: 1.14.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10.1
        libgit2: 0.99.0
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 1.1.1
         Python: 3.7.6 (default, Dec 19 2019, 22:52:49)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 18.0.1
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: fedora 31 Thirty One
         locale: UTF-8
        machine: x86_64
        release: 5.4.13-201.fc31.x86_64
         system: Linux
        version: Fedora 31 Thirty One
```

**Comment by max-arnold** [comment]
That is because the bug reappeared again in 3000: https://github.com/saltstack/salt/issues/56131

**Comment by sagetherage** [comment]
I will wait to close this, looks like it is fixed in the dot release.
