### ISSUE TITLE
mine.get: KeyError ('master')

### ISSUE THREAD

**Issue by Mrten** [saltstack/salt#5608]
I get various errors when trying to use the mine in a pillar:

```
#!mako|yaml
<%!
  import re
  import yaml
%><%
  ping = {}
  ping['virt'] = salt['mine.get']('virtual:kvm', 'test.ping', 'grain')
```

gives me

```
_errors:
        - Rendering SLS list-all-minions failed, render error:
        -
        -
        - Traceback (most recent call last):
        -   File "/usr/lib/pymodules/python2.7/salt/utils/templates.py", line 143, in render_mako_tmpl
        -     ).render(**context)
        -   File "/usr/lib/python2.7/dist-packages/mako/template.py", line 302, in render
        -     return runtime._render(self, self.callable_, args, data)
        -   File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 660, in _render
        -     **_kwargs_for_callable(callable_, data))
        -   File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 692, in _render_context
        -     _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
        -   File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 718, in _exec_template
        -     callable_(context, *args, **kwargs)
        -   File "list_all_minions", line 5, in render_body
        -     %><%
        -   File "/usr/lib/pymodules/python2.7/salt/modules/mine.py", line 90, in get
        -     auth = _auth()
        -   File "/usr/lib/pymodules/python2.7/salt/modules/mine.py", line 21, in _auth
        -     __context__['auth'] = salt.crypt.SAuth(__opts__)
        -   File "/usr/lib/pymodules/python2.7/salt/crypt.py", line 403, in __init__
        -     self.crypticle = self.__authenticate()
        -   File "/usr/lib/pymodules/python2.7/salt/crypt.py", line 413, in __authenticate
        -     creds = self.sign_in()
        -   File "/usr/lib/pymodules/python2.7/salt/crypt.py", line 251, in sign_in
        -     self.opts['master'],
        - KeyError: 'master'
```

**Comment by Mrten** [comment]
so, can we mine a pillar yet?

**Comment by Mrten** [comment]
i really dont know

**Comment by waynew** [comment]
> so, can we mine a pillar yet?

@Mrten as far as I can tell, yes! I have the following pillar:

```
ping:
  - virt: {{ salt['mine.get']('*', 'test.ping') }}
```

In my minion file I have:

```
mine_functions:
  test.ping: []
```

Then on the minion I ran:

```
salt-call --local mine.update
salt-call --local pillar.items
```

That produced this output:

```
local:
    ----------
    ping:
        |_
          ----------
          virt:
              ----------
              90826cc4be93:
                  True
```

Give it a try and see if that works for you!

**Comment by Mrten** [comment]
I get 
```
    mine-in-pillar-test:
        |_
          ----------
          virt:
              ----------
```
if I run it like you, with salt-call --local I get empty output:
```
local:
    ----------
```

**Comment by whytewolf** [comment]
wow, surprised this is still open. so the real answer is yes it is possible and is documented. and has been available since at least 2014.x

See the `see also` in the mine.get documentation https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.mine.html#salt.modules.mine.get

but for clarity here. 

`{% set minion_ips = salt.saltutil.runner('mine.get', tgt='*', fun='network.ip_addrs', tgt_type='glob') %}`

I'm going to go ahead and close this now.
