### ISSUE TITLE
Got Authentication Error while patching and reboot list of server

### ISSUE THREAD

**Issue by khaiduong** [saltstack/salt#56138]
### We have a script to do patching for our MySQL servers, during the patching, the reboot is required. We encountered the error with salt-minion service on the target server:

```2019-11-21 00:53:48,433 Thread-4 [INFO ] Processing server003
2019-11-21 00:53:48,433 Thread-4 [INFO ] Disable Nagios notifications for server003
2019-11-21 00:53:53,077 Thread-4 [INFO ] Running pkg.upgrade against server003
2019-11-21 00:55:49,324 Thread-4 [INFO ] Waiting for nagios to get a fresh check for patches on server003
2019-11-21 00:56:10,012 Thread-4 [INFO ] Stop group greplication on server003 before rebooting
2019-11-21 00:56:22,961 Thread-4 [INFO ] Rebooting server003
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/local/bin/patching.py", line 837, in run
    self._process_single_host(host_name)
  File "/usr/local/bin/patching.py", line 745, in _process_single_host
    reboot_verified = self._reboot(host_name)
  File "/usr/local/bin/patching.py", line 133, in _reboot
    uptime_after_reboot = self.salt_client.cmd(host, 'status.uptime', timeout=5)
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 703, in cmd
    **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 344, in run_job
    raise AuthenticationError(err)
AuthenticationError: Authentication error occurred.```


### Versions Report
2019.2.3

**Comment by DmitryKuzmenko** [comment]
@khaiduong could you please provide a description of your configuration, your state sequence before the reboot and the full output of `salt --versions`?

**Comment by khaiduong** [comment]
actually, the script run `yum update -y` for all the `CentOS` instances and then do reboot and waiting them up and running again. This is the full output of the command: 
`sudo salt --version
salt 2019.2.3 (Fluorine)`

**Comment by Akm0d** [comment]
@khaiduong can you give me the output of `salt ---versions-report`?

It looks to me like the authentication error is because of the minion rebooting and salt hasn't started yet.  I suppose the minion should be returning properly after rebooting :thinking:

**Comment by Ch3LL** [comment]
Closing due to inactivity. If this is still occurring on the latest version of Salt please open a new issue with the requested information and details.
