### ISSUE TITLE
UnboundLocalError: local variable 'current_state' referenced before assignment

### ISSUE THREAD

**Issue by jouve** [saltstack/salt#56141]
### Description of Issue
2020-02-12 15:07:01,775 [tornado.application:611 ][ERROR   ][13986] Exception in callback (<socket._socketobject object at 0x7f6106f657c0>, <function null_wrapper at 0x7f6105f26758>)
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/tornado/ioloop.py", line 865, in start
    handler_func(fd_obj, events)
  File "/usr/lib64/python2.7/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    _state.contexts = current_state
UnboundLocalError: local variable 'current_state' referenced before assignment

### Setup
default config + gitfs

### Steps to Reproduce Issue
state.apply xxx

### Versions Report
Salt Version:
           Salt: 2018.3.3

same as #47654

**Comment by DmitryKuzmenko** [comment]
@jouve Could you please provide salt log of the error and `salt --versions` output?

**Comment by DmitryKuzmenko** [comment]
@jouve 2018.3 is EOL so please consider upgrading your Salt installation to 2019.2 or later.
