### ISSUE TITLE
Lack of FQDN on host blocks salt-master startup

### ISSUE THREAD

**Issue by landergate** [saltstack/salt#56179]
### Description of Issue
Some VPS providers do not provision hostname at /etc/hosts at Ubuntu 18.04 image.
Right now it leads to salt-master failure to start.

From UX point of view, it looks like this:
1. User gets a new VPS with Ubuntu 18.04
2. Installs salt-master from SaltStack's py3 repo
3. salt-master never starts

Current workaround: add hostname lines to `/etc/hosts` manually, e.g.:

```diff
  127.0.0.1       localhost.localdomain   localhost
  ::1             localhost6.localdomain6 localhost6
+ 127.0.1.1       cloud208317.someprovider.io cloud208317
```

### Setup
Ubuntu 18.04, SaltStack py3 repo

```sh
~# cat /etc/hostname
cloud208317.someprovider.io

~# hostname --all-fqdns
cloud123-123-123-123.someprovider.io .

~# cat /etc/hosts
127.0.0.1       localhost.localdomain   localhost
::1             localhost6.localdomain6 localhost6

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
```

### Steps to Reproduce Issue
1. Spin a node with Ubuntu 18.04
2. Make sure `/etc/hosts` lacks node's hostname
3. Install salt-master from SaltStack py3 repo
4. Start salt-master
5. Wait ~30 sec

```
~# salt-master -l debug

....

[ERROR   ] An un-handled exception from the multiprocessing process 'MWorker-1' was caught:
Traceback (most recent call last):
  File "/usr/lib/python3.6/encodings/idna.py", line 165, in encode
    raise UnicodeError("label empty or too long")
UnicodeError: label empty or too long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/process.py", line 760, in wrapped_run_func
    return run_func()
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1139, in run
    self.key,
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1891, in __init__
    ignore_config_errors=True
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 898, in __init__
    self.opts['grains'] = salt.loader.grains(opts)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 808, in grains
    ret = funcs[key]()
  File "/usr/lib/python3/dist-packages/salt/grains/core.py", line 2279, in ip_fqdn
    info = socket.getaddrinfo(_fqdn, None, socket_type)
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)
Process MWorker-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/encodings/idna.py", line 165, in encode
    raise UnicodeError("label empty or too long")
UnicodeError: label empty or too long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3/dist-packages/salt/utils/process.py", line 771, in wrapped_run_func
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3/dist-packages/salt/ext/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/salt/utils/process.py", line 760, in wrapped_run_func
    return run_func()
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1139, in run
    self.key,
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1891, in __init__
    ignore_config_errors=True
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 898, in __init__
    self.opts['grains'] = salt.loader.grains(opts)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 808, in grains
    ret = funcs[key]()
  File "/usr/lib/python3/dist-packages/salt/grains/core.py", line 2279, in ip_fqdn
    info = socket.getaddrinfo(_fqdn, None, socket_type)
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)
[ERROR   ] An un-handled exception from the multiprocessing process 'MWorker-0' was caught:
Traceback (most recent call last):
  File "/usr/lib/python3.6/encodings/idna.py", line 165, in encode
    raise UnicodeError("label empty or too long")
UnicodeError: label empty or too long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/process.py", line 760, in wrapped_run_func
    return run_func()
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1139, in run
    self.key,
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1891, in __init__
    ignore_config_errors=True
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 898, in __init__
    self.opts['grains'] = salt.loader.grains(opts)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 808, in grains
    ret = funcs[key]()
  File "/usr/lib/python3/dist-packages/salt/grains/core.py", line 2279, in ip_fqdn
    info = socket.getaddrinfo(_fqdn, None, socket_type)
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)
Process MWorker-0:
Traceback (most recent call last):
  File "/usr/lib/python3.6/encodings/idna.py", line 165, in encode
    raise UnicodeError("label empty or too long")
UnicodeError: label empty or too long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3/dist-packages/salt/utils/process.py", line 771, in wrapped_run_func
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3/dist-packages/salt/ext/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/salt/utils/process.py", line 760, in wrapped_run_func
    return run_func()
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1139, in run
    self.key,
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1891, in __init__
    ignore_config_errors=True
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 898, in __init__
    self.opts['grains'] = salt.loader.grains(opts)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 808, in grains
    ret = funcs[key]()
  File "/usr/lib/python3/dist-packages/salt/grains/core.py", line 2279, in ip_fqdn
    info = socket.getaddrinfo(_fqdn, None, socket_type)
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)
[ERROR   ] An un-handled exception from the multiprocessing process 'MWorker-3' was caught:
Traceback (most recent call last):
  File "/usr/lib/python3.6/encodings/idna.py", line 165, in encode
    raise UnicodeError("label empty or too long")
UnicodeError: label empty or too long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/process.py", line 760, in wrapped_run_func
    return run_func()
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1139, in run
    self.key,
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1891, in __init__
    ignore_config_errors=True
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 898, in __init__
    self.opts['grains'] = salt.loader.grains(opts)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 808, in grains
    ret = funcs[key]()
  File "/usr/lib/python3/dist-packages/salt/grains/core.py", line 2279, in ip_fqdn
    info = socket.getaddrinfo(_fqdn, None, socket_type)
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)
Process MWorker-3:
Traceback (most recent call last):
  File "/usr/lib/python3.6/encodings/idna.py", line 165, in encode
    raise UnicodeError("label empty or too long")
UnicodeError: label empty or too long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3/dist-packages/salt/utils/process.py", line 771, in wrapped_run_func
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3/dist-packages/salt/ext/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/salt/utils/process.py", line 760, in wrapped_run_func
    return run_func()
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1139, in run
    self.key,
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1891, in __init__
    ignore_config_errors=True
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 898, in __init__
    self.opts['grains'] = salt.loader.grains(opts)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 808, in grains
    ret = funcs[key]()
  File "/usr/lib/python3/dist-packages/salt/grains/core.py", line 2279, in ip_fqdn
    info = socket.getaddrinfo(_fqdn, None, socket_type)
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)
[ERROR   ] An un-handled exception from the multiprocessing process 'MWorker-2' was caught:
Traceback (most recent call last):
  File "/usr/lib/python3.6/encodings/idna.py", line 165, in encode
    raise UnicodeError("label empty or too long")
UnicodeError: label empty or too long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/process.py", line 760, in wrapped_run_func
    return run_func()
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1139, in run
    self.key,
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1891, in __init__
    ignore_config_errors=True
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 898, in __init__
    self.opts['grains'] = salt.loader.grains(opts)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 808, in grains
    ret = funcs[key]()
  File "/usr/lib/python3/dist-packages/salt/grains/core.py", line 2279, in ip_fqdn
    info = socket.getaddrinfo(_fqdn, None, socket_type)
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)
Process MWorker-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/encodings/idna.py", line 165, in encode
    raise UnicodeError("label empty or too long")
UnicodeError: label empty or too long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3/dist-packages/salt/utils/process.py", line 771, in wrapped_run_func
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3/dist-packages/salt/ext/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/salt/utils/process.py", line 760, in wrapped_run_func
    return run_func()
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1139, in run
    self.key,
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1891, in __init__
    ignore_config_errors=True
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 898, in __init__
    self.opts['grains'] = salt.loader.grains(opts)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 808, in grains
    ret = funcs[key]()
  File "/usr/lib/python3/dist-packages/salt/grains/core.py", line 2279, in ip_fqdn
    info = socket.getaddrinfo(_fqdn, None, socket_type)
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)
[ERROR   ] An un-handled exception from the multiprocessing process 'MWorker-4' was caught:
Traceback (most recent call last):
  File "/usr/lib/python3.6/encodings/idna.py", line 165, in encode
    raise UnicodeError("label empty or too long")
UnicodeError: label empty or too long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/process.py", line 760, in wrapped_run_func
    return run_func()
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1139, in run
    self.key,
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1891, in __init__
    ignore_config_errors=True
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 898, in __init__
    self.opts['grains'] = salt.loader.grains(opts)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 808, in grains
    ret = funcs[key]()
  File "/usr/lib/python3/dist-packages/salt/grains/core.py", line 2279, in ip_fqdn
    info = socket.getaddrinfo(_fqdn, None, socket_type)
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)
Process MWorker-4:
Traceback (most recent call last):
  File "/usr/lib/python3.6/encodings/idna.py", line 165, in encode
    raise UnicodeError("label empty or too long")
UnicodeError: label empty or too long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3/dist-packages/salt/utils/process.py", line 771, in wrapped_run_func
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3/dist-packages/salt/ext/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/salt/utils/process.py", line 760, in wrapped_run_func
    return run_func()
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1139, in run
    self.key,
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1891, in __init__
    ignore_config_errors=True
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 898, in __init__
    self.opts['grains'] = salt.loader.grains(opts)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 808, in grains
    ret = funcs[key]()
  File "/usr/lib/python3/dist-packages/salt/grains/core.py", line 2279, in ip_fqdn
    info = socket.getaddrinfo(_fqdn, None, socket_type)
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)
[INFO    ] Process <class 'salt.master.MWorker'> (9022) died with exit status 1, restarting...
[DEBUG   ] Started 'salt.master.<class 'type'>.MWorker' with pid 9106
[INFO    ] Process <class 'salt.master.MWorker'> (9023) died with exit status 1, restarting...
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Started 'salt.master.<class 'type'>.MWorker' with pid 9107
[INFO    ] Process <class 'salt.master.MWorker'> (9024) died with exit status 1, restarting...


~# salt '*' test.ping
[ERROR   ] Message timed out
Salt request timed out. The master is not responding. You may need to run your command with `--async` in order to bypass the congested event bus. With `--async`, the CLI tool will print the job id (jid) and exit immediately without listening for responses. You can then use `salt-run jobs.lookup_jid` to look up the results of the job in the job cache later.
```

### Versions Report
```
~# salt --versions-report
Salt Version:
           Salt: 3000

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
         Jinja2: 2.10
        libgit2: 0.26.0
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.2
         Python: 3.6.9 (default, Nov  7 2019, 10:44:02)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-76-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```

**Comment by waynew** [comment]
Thanks for the report! Working to reproduce this now.

**Comment by waynew** [comment]
@landergate I cannot for the life of me reproduce this. Following your steps I still get success. I'm quite certain that the error is due to something wonky getting returned from the host lookup. As a matter of fact, it's possible that your DNS is broken because this does not look right:

```
~# hostname --all-fqdns
cloud123-123-123-123.someprovider.io .
```

If you're really getting `.`. That's not valid:

```
>>> '.'.encode('idna')
Traceback (most recent call last):
  File "/usr/lib/python3.6/encodings/idna.py", line 165, in encode
    raise UnicodeError("label empty or too long")
UnicodeError: label empty or too long
```

You can double check to see what it's actually looking for here:

```
  File "/usr/lib/python3/dist-packages/salt/grains/core.py", line 2279, in ip_fqdn
    info = socket.getaddrinfo(_fqdn, None, socket_type)
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
```

Can you add `import pdb; pdb.set_trace()` above each of those lines, i.e. before 2279 in `/usr/lib/python3/dist-packages/salt/grains/core.py` and before line 745 in `/usr/lib/python3.6/socket.py`? If you do that before you run the salt-master command it should drop you into a pdb shell. Type `_fqdn` on the first one and I suspect it will show `'.'`, and then press 'c' to continue. Then type `host` and my guess is that it should show `'.'` there as well.

Can you give that a shot and let me know? Thanks!

**Comment by dwoz** [comment]
I've seen this before and was able to work around it by setting an `id` in the master config.

**Comment by landergate** [comment]
@dwoz
Thanks for advice.
Tried both `master_id:` and `id:` at master config, but exception still happens.

@waynew
Thanks for your patience.
I agree that this issue depends on environment.

Checking variable values:

Without `127.0.1.1 hostname` line in /etc/hosts:
```
host: '0.0.0.0'
_fqdn: '.'

~# hostname --all-fqdns
cloud123-123-123-123.someprovider.io .
```

With `127.0.1.1 hostname` line in /etc/hosts:
```sh
host: '0.0.0.0'
_fqdn: 'cloud208317.someprovider.io'

~# hostname --all-fqdns
cloud123-123-123-123.someprovider.io .
```

Despite `hostname --all-fqdns` shows a single dot for a second fqdn in both cases, having `127.0.1.1 hostname` line lets salt-master to resolve `_fqdn` correctly and thus start as expected.

`strace -s 1024 domainname --all-fqdns` mentions ip6.arpa on requesting 127.0.0.53 dns resolver.

That gave me an idea to do an ipv6 reverse lookup.

```
~# host <ipv6 address here>
x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.a.2.ip6.arpa domain name pointer .
```

So the reason why --all-fqdns returns a single dot is **lack of ivp6 reverse DNS**.

And hostname line at /etc/hosts forced ipv4-only reverse lookup instead of ipv6.

------

I guess we can conclude that salt-master currently fails to boot if it gets invalid response on hostname reverse DNS lookup.

Must salt-master rely on it? Could it use some fallback value in case for '.' or even any invalid reverse DNS response? Not trying to pin responsibility, I agree that this is an environment issue and empty reverse DNS is not a common case. Just wondering if its possible to workaround such situation to avoid startup block.

**Comment by waynew** [comment]
I'm not intimately familiar with how linux resolves it's hostnames - but looking at the stack trace, in particular this line:

```
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
```

getaddrinfo is probably just exposing [getaddrinfo](http://man7.org/linux/man-pages/man3/getaddrinfo.3.html), so it's largely based on the underlying system.

> Must salt-master rely on it? Could it use some fallback value in case for '.' or even any invalid reverse DNS response? Not trying to pin responsibility, I agree that this is an environment issue and empty reverse DNS is not a common case. Just wondering if its possible to workaround such situation to avoid startup block.

I guess that's the philosophical question - and looking back at this it does appear to be happening within grains. Should salt halt starting up if it can't load all the grains? Is there a *minimum* set of grains that Salt needs to be able to load before being useful?

I don't have any strong feelings about it one way or another - @thatch45 may be able to weigh in here, but I'm not aware of any established guidelines.

---

If failure is the route we want to take, I think it *does* make sense to update this flow to fail with a friendly message, like `CRITICAL: Failed to resolve required valid FQDN, salt is shutting down. See <some URL> for more info.`

**Comment by kd8drx** [comment]
Tagging onto this issue, as I'm seeing this _exact_ same problem - but on a Windows 10 minion. This particular minion had IPv6 enabled (Windows does this by default), but was not on a IPv6 network, and so the IPv6 hostname in Windows 10 was blank.

As a result, any time you attempted to run `salt-call` or apply a state – anything that requires calculating the grains – salt would crash when trying to determine `ip_fqdn`:
```
File "c:\salt\bin\lib\site-packages\salt\grains\core.py", line 2259, in ip_fqdn
    info = socket.getaddrinfo(_fqdn, None, socket_type)
  File "c:\salt\bin\lib\socket.py", line 733, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)
Traceback (most recent call last):
  File "c:\salt\bin\lib\encodings\idna.py", line 165, in encode
    raise UnicodeError("label empty or too long")
UnicodeError: label empty or too long
```

In my case, I was able to work around the issue by disabling IPv6 on all the minion's network interfaces.

### Full Stack Trace
```c:\salt>salt-call --local -g
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)
Traceback (most recent call last):
  File "c:\salt\bin\lib\encodings\idna.py", line 165, in encode
    raise UnicodeError("label empty or too long")
UnicodeError: label empty or too long
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "c:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "c:\salt\bin\lib\site-packages\salt\scripts.py", line 431, in salt_call
    client.run()
  File "c:\salt\bin\lib\site-packages\salt\cli\call.py", line 47, in run
    caller = salt.cli.caller.Caller.factory(self.config)
  File "c:\salt\bin\lib\site-packages\salt\cli\caller.py", line 80, in factory
    return ZeroMQCaller(opts, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt\cli\caller.py", line 332, in __init__
    super(ZeroMQCaller, self).__init__(opts)
  File "c:\salt\bin\lib\site-packages\salt\cli\caller.py", line 106, in __init__
    self.minion = salt.minion.SMinion(opts)
  File "c:\salt\bin\lib\site-packages\salt\minion.py", line 835, in __init__
    opts['grains'] = salt.loader.grains(opts)
  File "c:\salt\bin\lib\site-packages\salt\loader.py", line 784, in grains
    ret = funcs[key]()
  File "c:\salt\bin\lib\site-packages\salt\grains\core.py", line 2259, in ip_fqdn
    info = socket.getaddrinfo(_fqdn, None, socket_type)
  File "c:\salt\bin\lib\socket.py", line 733, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)
Traceback (most recent call last):
  File "c:\salt\bin\lib\encodings\idna.py", line 165, in encode
    raise UnicodeError("label empty or too long")
UnicodeError: label empty or too long
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "c:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "c:\salt\bin\lib\site-packages\salt\scripts.py", line 431, in salt_call
    client.run()
  File "c:\salt\bin\lib\site-packages\salt\cli\call.py", line 47, in run
    caller = salt.cli.caller.Caller.factory(self.config)
  File "c:\salt\bin\lib\site-packages\salt\cli\caller.py", line 80, in factory
    return ZeroMQCaller(opts, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt\cli\caller.py", line 332, in __init__
    super(ZeroMQCaller, self).__init__(opts)
  File "c:\salt\bin\lib\site-packages\salt\cli\caller.py", line 106, in __init__
    self.minion = salt.minion.SMinion(opts)
  File "c:\salt\bin\lib\site-packages\salt\minion.py", line 835, in __init__
    opts['grains'] = salt.loader.grains(opts)
  File "c:\salt\bin\lib\site-packages\salt\loader.py", line 784, in grains
    ret = funcs[key]()
  File "c:\salt\bin\lib\site-packages\salt\grains\core.py", line 2259, in ip_fqdn
    info = socket.getaddrinfo(_fqdn, None, socket_type)
  File "c:\salt\bin\lib\socket.py", line 733, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)
```

### Versions Information
```Salt Version:
           Salt: 2019.2.2
Dependency Versions:
           cffi: 1.12.2
       cherrypy: 17.4.1
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.6
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: Not Installed
   pycryptodome: 3.8.1
         pygit2: Not Installed
         Python: 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.4
```

I hope this helps in finding a solution!
