### ISSUE TITLE
Salt 3000 minion won't start after upgrade to 3000

### ISSUE THREAD

**Issue by githubcdr** [saltstack/salt#56196]
### Description of Issue

Salt is making me salty, first Linux minions fail to start, now Windows;

PS C:\salt> .\salt-minion-debug.bat
The salt-minion service is not started.

More help is available by typing NET HELPMSG 3521.

[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Using cached minion ID from c:\salt\conf\minion_id: win10.eigenhuis.lan
[DEBUG   ] Multiprocessing queue logging configured for the process running under PID: 5144 at log level 10
[DEBUG   ] Marking 'is_ip' as a jinja filter
[DEBUG   ] Marking 'is_ipv4' as a jinja filter
[DEBUG   ] Marking 'is_ipv6' as a jinja filter
[DEBUG   ] Marking 'ipv4' as a jinja filter
[DEBUG   ] Marking 'ipv6' as a jinja filter
[DEBUG   ] Marking 'ipaddr' as a jinja filter
[DEBUG   ] Marking 'ip_host' as a jinja filter
[DEBUG   ] Marking 'network_hosts' as a jinja filter
[DEBUG   ] Marking 'network_size' as a jinja filter
[DEBUG   ] Marking 'gen_mac' as a jinja filter
[DEBUG   ] Marking 'mac_str_to_bytes' as a jinja filter
[DEBUG   ] Marking 'dns_check' as a jinja filter
[DEBUG   ] Multiprocessing queue logging configured for the process running under PID: 5144 at log level 10
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] Setting up the Salt Minion "win10.salty.lan"
[DEBUG   ] Marking 'base64_encode' as a jinja filter
[DEBUG   ] Marking 'base64_decode' as a jinja filter
[DEBUG   ] Marking 'md5' as a jinja filter
[DEBUG   ] Marking 'sha1' as a jinja filter
[DEBUG   ] Marking 'sha256' as a jinja filter
[DEBUG   ] Marking 'sha512' as a jinja filter
[DEBUG   ] Marking 'hmac' as a jinja filter
[DEBUG   ] Marking 'hmac_compute' as a jinja filter
[DEBUG   ] Marking 'random_hash' as a jinja filter
[DEBUG   ] Marking 'rand_str' as a jinja filter
[DEBUG   ] Marking 'file_hashsum' as a jinja filter
[DEBUG   ] Marking 'http_query' as a jinja filter
[DEBUG   ] Marking 'strftime' as a jinja filter
[DEBUG   ] Marking 'date_format' as a jinja filter
[DEBUG   ] Marking 'yaml_dquote' as a jinja filter
[DEBUG   ] Marking 'yaml_squote' as a jinja filter
[DEBUG   ] Marking 'yaml_encode' as a jinja filter
[DEBUG   ] Marking 'raise' as a jinja global
[DEBUG   ] Marking 'match' as a jinja test
[DEBUG   ] Marking 'equalto' as a jinja test
[DEBUG   ] Marking 'skip' as a jinja filter
[DEBUG   ] Marking 'sequence' as a jinja filter
[DEBUG   ] Marking 'to_bool' as a jinja filter
[DEBUG   ] Marking 'tojson' as a jinja filter
[DEBUG   ] Marking 'quote' as a jinja filter
[DEBUG   ] Marking 'regex_escape' as a jinja filter
[DEBUG   ] Marking 'regex_search' as a jinja filter
[DEBUG   ] Marking 'regex_match' as a jinja filter
[DEBUG   ] Marking 'regex_replace' as a jinja filter
[DEBUG   ] Marking 'uuid' as a jinja filter
[DEBUG   ] Marking 'unique' as a jinja filter
[DEBUG   ] Marking 'min' as a jinja filter
[DEBUG   ] Marking 'max' as a jinja filter
[DEBUG   ] Marking 'avg' as a jinja filter
[DEBUG   ] Marking 'union' as a jinja filter
[DEBUG   ] Marking 'intersect' as a jinja filter
[DEBUG   ] Marking 'difference' as a jinja filter
[DEBUG   ] Marking 'symmetric_difference' as a jinja filter
[DEBUG   ] Created pidfile: c:\salt\var\run\salt-minion.pid
[INFO    ] Starting up the Salt Minion
[DEBUG   ] AsyncEventPublisher PUB socket URI: 4510
[DEBUG   ] AsyncEventPublisher PULL socket URI: 4511
[INFO    ] Starting pull socket on 4511
[DEBUG   ] SaltEvent PUB socket URI: 4510
[DEBUG   ] SaltEvent PULL socket URI: 4511
[DEBUG   ] Grains cache file does not exist.
[DEBUG   ] Reading configuration from c:\salt\conf\minion
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-minion", line 4, in <module>
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
KeyError: 53
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-minion", line 4, in <module>
    __import__('pkg_resources').run_script('salt==3000', 'salt-minion')
  File "C:\salt\bin\lib\site-packages\pkg_resources\__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "C:\salt\bin\lib\site-packages\pkg_resources\__init__.py", line 1527, in run_script
    exec(code, namespace, namespace)
  File "c:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\EGG-INFO\scripts\salt-minion", line 26, in <module>
    salt_minion()
  File "C:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\scripts.py", line 205, in salt_minion
    minion.start()
  File "C:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\cli\daemons.py", line 326, in start
    self._real_start()
  File "C:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\cli\daemons.py", line 338, in _real_start
    self.minion.tune_in()
  File "C:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\minion.py", line 1074, in tune_in
    self._spawn_minions()
  File "C:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\minion.py", line 1018, in _spawn_minions
    jid_queue=self.jid_queue)
  File "C:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\minion.py", line 986, in _create_minion_object
    jid_queue=jid_queue)
  File "C:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\minion.py", line 1145, in __init__
    self.opts['grains'] = salt.loader.grains(opts)
  File "C:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\loader.py", line 808, in grains
    ret = funcs[key]()
  File "C:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\grains\core.py", line 2381, in hwaddr_interfaces
    ifaces = _get_interfaces()
  File "C:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\grains\core.py", line 1558, in _get_interfaces
    _INTERFACES = salt.utils.network.interfaces()
  File "C:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\utils\network.py", line 1004, in interfaces
    return win_interfaces()
  File "C:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\utils\network.py", line 996, in win_interfaces
    return salt.utils.win_network.get_interface_info()
  File "C:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\utils\win_network.py", line 348, in get_interface_info
    return get_interface_info_dot_net_formatted()
  File "C:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\utils\win_network.py", line 237, in get_interface_info_dot_net_formatted
    interfaces = get_interface_info_dot_net()
  File "C:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\utils\win_network.py", line 272, in get_interface_info_dot_net
    temp_dict = _get_base_properties(i_face)
  File "C:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\utils\win_network.py", line 116, in _get_base_properties
    'type': enum_adapter_types[i_face.NetworkInterfaceType],
KeyError: 53    __import__('pkg_resources').run_script('salt==3000', 'salt-minion')

  File "C:\salt\bin\lib\site-packages\pkg_resources\__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "C:\salt\bin\lib\site-packages\pkg_resources\__init__.py", line 1527, in run_script
    exec(code, namespace, namespace)
  File "c:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\EGG-INFO\scripts\salt-minion", line 26, in <module>
    salt_minion()
  File "C:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\scripts.py", line 205, in salt_minion
    minion.start()
  File "C:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\cli\daemons.py", line 326, in start
    self._real_start()
  File "C:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\cli\daemons.py", line 338, in _real_start
    self.minion.tune_in()
  File "C:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\minion.py", line 1074, in tune_in
    self._spawn_minions()
  File "C:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\minion.py", line 1018, in _spawn_minions
    jid_queue=self.jid_queue)
  File "C:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\minion.py", line 986, in _create_minion_object
    jid_queue=jid_queue)
  File "C:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\minion.py", line 1145, in __init__
    self.opts['grains'] = salt.loader.grains(opts)
  File "C:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\loader.py", line 808, in grains
    ret = funcs[key]()
  File "C:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\grains\core.py", line 2381, in hwaddr_interfaces
    ifaces = _get_interfaces()
  File "C:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\grains\core.py", line 1558, in _get_interfaces
    _INTERFACES = salt.utils.network.interfaces()
  File "C:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\utils\network.py", line 1004, in interfaces
    return win_interfaces()
  File "C:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\utils\network.py", line 996, in win_interfaces
    return salt.utils.win_network.get_interface_info()
  File "C:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\utils\win_network.py", line 348, in get_interface_info
    return get_interface_info_dot_net_formatted()
  File "C:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\utils\win_network.py", line 237, in get_interface_info_dot_net_formatted
    interfaces = get_interface_info_dot_net()
  File "C:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\utils\win_network.py", line 272, in get_interface_info_dot_net
    temp_dict = _get_base_properties(i_face)
  File "C:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\utils\win_network.py", line 116, in _get_base_properties
    'type': enum_adapter_types[i_face.NetworkInterfaceType],
KeyError: 53
PS C:\salt>

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report

Salt Version:
           Salt: 3000

Dependency Versions:
           cffi: 1.12.2
       cherrypy: 17.4.1
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.6
      gitpython: 2.1.10
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: Not Installed
   pycryptodome: 3.8.1
         pygit2: Not Installed
         Python: 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.4
         PyYAML: 5.1.2
          PyZMQ: 18.0.1
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 10
         system: Windows
        version: 10 10.0.17763 SP0 Multiprocessor Free

**Comment by githubcdr** [comment]
This error is gone when I disable my OpenVPN tap device.

**Comment by waynew** [comment]
Hi @githubcdr we'll take a look at this and try to reproduce!

**Comment by waynew** [comment]
Interesting! We'll give it a try and see if we can reproduce!

**Comment by wh1te909** [comment]
> This error is gone when I disable my OpenVPN tap device.

getting same error on all my windows computers that have openvpn after updating to v3000, same for me disabling tap fixes it

**Comment by dwoz** [comment]
@twangboy Please take a look and see if this is an easy fix.

**Comment by sagetherage** [comment]
closing as merged for 3000.1 release
