### ISSUE TITLE
salt-minion in restart loop

### ISSUE THREAD

**Issue by shortstack** [saltstack/salt#56216]
### Description of Issue
Minion checks in with key, master accepts key

Can't test.ping or run any commands from master to minion

This minion was checking in until about a month ago and then stopped 

Windows event logs show a constant restart loop with `"c:\salt\bin\python.exe" -E -s c:\salt\bin\Scripts\salt-minion -c c:\salt\conf -l quiet`

Tried Salt-Minion-2019.2.2-Py3-AMD64-Setup.exe and Salt-Minion-2019.2.0-Py2-AMD64-Setup.exe

Same issue / error / service restart loop regardless of version

Last logs available on minion in C:\salt\var\log\minion
```
IOError: [Errno 22] Invalid argument
2020-02-20 12:43:52,686 [tornado.application:129 ][ERROR   ][27516] Future exception was never retrieved: Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\tornado\gen.py", line 307, in wrapper
    yielded = next(result)
  File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1524, in _handle_decoded_payload
    process.start()
  File "c:\salt\bin\lib\site-packages\salt\utils\process.py", line 819, in start
    super(SignalHandlingMultiprocessingProcess, self).start()
  File "c:\salt\bin\lib\multiprocessing\process.py", line 130, in start
    self._popen = Popen(self)
  File "c:\salt\bin\lib\multiprocessing\forking.py", line 280, in __init__
    to_child.close()
IOError: [Errno 22] Invalid argument
2020-02-20 12:44:07,783 [tornado.application:129 ][ERROR   ][27516] Future exception was never retrieved: Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\tornado\gen.py", line 307, in wrapper
    yielded = next(result)
  File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1524, in _handle_decoded_payload
    process.start()
  File "c:\salt\bin\lib\site-packages\salt\utils\process.py", line 819, in start
    super(SignalHandlingMultiprocessingProcess, self).start()
  File "c:\salt\bin\lib\multiprocessing\process.py", line 130, in start
    self._popen = Popen(self)
  File "c:\salt\bin\lib\multiprocessing\forking.py", line 280, in __init__
    to_child.close()
IOError: [Errno 22] Invalid argument
2020-02-20 12:47:38,605 [tornado.application:129 ][ERROR   ][27516] Future exception was never retrieved: Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\tornado\gen.py", line 307, in wrapper
    yielded = next(result)
  File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1524, in _handle_decoded_payload
    process.start()
  File "c:\salt\bin\lib\site-packages\salt\utils\process.py", line 819, in start
    super(SignalHandlingMultiprocessingProcess, self).start()
  File "c:\salt\bin\lib\multiprocessing\process.py", line 130, in start
    self._popen = Popen(self)
  File "c:\salt\bin\lib\multiprocessing\forking.py", line 280, in __init__
    to_child.close()
IOError: [Errno 22] Invalid argument
2020-02-20 12:48:11,700 [tornado.application:129 ][ERROR   ][27516] Future exception was never retrieved: Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\tornado\gen.py", line 307, in wrapper
    yielded = next(result)
  File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1524, in _handle_decoded_payload
    process.start()
  File "c:\salt\bin\lib\site-packages\salt\utils\process.py", line 819, in start
    super(SignalHandlingMultiprocessingProcess, self).start()
  File "c:\salt\bin\lib\multiprocessing\process.py", line 130, in start
    self._popen = Popen(self)
  File "c:\salt\bin\lib\multiprocessing\forking.py", line 280, in __init__
    to_child.close()
IOError: [Errno 22] Invalid argument
2020-02-20 12:48:26,940 [tornado.application:129 ][ERROR   ][27516] Future exception was never retrieved: Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\tornado\gen.py", line 307, in wrapper
    yielded = next(result)
  File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1524, in _handle_decoded_payload
    process.start()
  File "c:\salt\bin\lib\site-packages\salt\utils\process.py", line 819, in start
    super(SignalHandlingMultiprocessingProcess, self).start()
  File "c:\salt\bin\lib\multiprocessing\process.py", line 130, in start
    self._popen = Popen(self)
  File "c:\salt\bin\lib\multiprocessing\forking.py", line 280, in __init__
    to_child.close()
IOError: [Errno 22] Invalid argument
```

### Setup
Pretty straight forward deployment, minions are distributed

### Steps to Reproduce Issue
Install Salt minion on endpoint
Accept key on master
Run `salt 'minion-name' test.ping` (or any other command) and get minion did not return error every time

### Versions Report

**Master:** 
```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.12.3
       cherrypy: 3.2.3
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Oct  8 2019, 14:14:10)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-1099-aws
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Minion:** 
Microsoft Windows Server 2019 Datacenter

```
    Salt Version:
               Salt: 2019.2.0
     
    Dependency Versions:
               cffi: 1.11.5
           cherrypy: 17.4.1
           dateutil: 2.7.5
          docker-py: Not Installed
              gitdb: 2.0.5
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.10
            libgit2: Not Installed
            libnacl: 1.6.1
           M2Crypto: Not Installed
               Mako: 1.0.7
       msgpack-pure: Not Installed
     msgpack-python: 0.5.6
       mysql-python: Not Installed
          pycparser: 2.19
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]
       python-gnupg: 0.4.3
             PyYAML: 3.13
              PyZMQ: 17.1.2
               RAET: Not Installed
              smmap: 2.0.5
            timelib: 0.2.4
            Tornado: 4.5.3
                ZMQ: 4.2.5
     
    System Versions:
               dist:   
             locale: cp1252
            machine: AMD64
            release: 2019Server
             system: Windows
            version: 2019Server 10.0.17763  Multiprocessor Free
```

**Comment by shortstack** [comment]
bump :(

**Comment by waynew** [comment]
Do you have anything special in your minion config?

```
salt dev-salt cmd.run 'salt-call --versions-report'
dev-salt:
    Salt Version:
               Salt: 2019.2.3
     
    Dependency Versions:
               cffi: 1.12.2
           cherrypy: 17.4.1
           dateutil: 2.8.0
          docker-py: Not Installed
              gitdb: 2.0.6
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.10.1
            libgit2: Not Installed
            libnacl: 1.6.1
           M2Crypto: Not Installed
               Mako: 1.0.7
       msgpack-pure: Not Installed
     msgpack-python: 0.5.6
       mysql-python: Not Installed
          pycparser: 2.19
           pycrypto: Not Installed
       pycryptodome: 3.8.1
             pygit2: Not Installed
             Python: 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]
       python-gnupg: 0.4.4
             PyYAML: 3.13
              PyZMQ: 18.0.1
               RAET: Not Installed
              smmap: 2.0.5
            timelib: 0.2.4
            Tornado: 4.5.3
                ZMQ: 4.3.1
     
    System Versions:
               dist:   
             locale: cp1252
            machine: AMD64
            release: 2019Server
             system: Windows
            version: 2019Server 10.0.17763  Multiprocessor Free
```

I'm able to actually run the command on my minion from my master. As well as run `test.ping`, `test.version`, and more.

This is on a fresh EC2 instance with a brand new install of Salt.

**Comment by shortstack** [comment]
hi @waynew,

no, there is nothing "special" in the config aside from using non-standard ports (have hundreds of other minions configured in the same way with the same ports without issue)

```
master_port: 80
publish_port: 443
hash_type: sha256
master: REDACTED
```

**Comment by sagetherage** [comment]
@xeacott can you help with follow up on this tomorrow during regular triage of new issue, please?

**Comment by xeacott** [comment]
Yes @shortstack ill add this to my list of stuff for the day and i'll see what I can come up with, but ill follow up in an hour so once i've read this a few times 😄

**Comment by xeacott** [comment]
Okay so, @shortstack off the bat this seems to be highly specific and incorrect behavior:

```
Minion checks in with key, master accepts key
Can't test.ping or run any commands from master to minion
```

Are there any logs at this point in time you'd be able to share some output from? Or have you considered upgrading the master/minion?

My usual setup is a master running on Ubuntu (WSL) and then a native Windows minion, so I'm hoping to find a way to repro this.

**Comment by shortstack** [comment]
We've had numerous issues with the salt minions causing exceptions and no longer checking into the master (dozens more than just this instance and various other exceptions). In a distributed environment where we don't always have access to these systems by any means *other* than salt, we've had to abandon salt and find another solution since it has become unreliable. 

I do not have the logs from this anymore, unfortunately :( The above is what it continues to output across the systems with this same issue. Multiple versions of Windows in a dozen different environments.

Thank you for your time.

**Comment by sagetherage** [comment]
@shortstack We certainly don't like hearing this, and we will need more information in order to move forward, here. Are you able to get with a colleague or peer that can get logs? 

We can schedule a time with you and an Open Core team member, maybe include someone from support for 30 minutes to run through more specifics. Let us know if there is more we can do or if you want to move forward with either of these options.

**Comment by markuskramerIgitt** [comment]
@shortstack can you verify the content of the _schedule.conf file?

**Comment by markuskramerIgitt** [comment]
I installed Salt-Minion-2019.2.2-Py3-AMD64-Setup.exe and copied a [_schedule.conf containing only NUL charecters]() to `C:\salt\conf\minion.d` 

The minion can no longer start:

```
sc query salt-minion

SERVICE_NAME: salt-minion
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 2  START_PENDING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x3
        WAIT_HINT          : 0x1964

```
The minion creates an error that is not logged, only visible on the console

```
\salt\salt-call --local  test.versiony
[ERROR   ] Error parsing configuration file: c:\salt\conf\minion.d\_schedule.conf - unacceptable character #x0000: control characters are not allowed
  in "c:\salt\conf\minion.d\_schedule.conf", position 0


```

That minions of @shortstack could have auto-destroyed himself by writing NUL into _schedule.conf ("This minion was checking in until about a month ago and then stopped")

I do not know which component fails and writes NUL.

This PR https://github.com/saltstack/salt/pull/58179 is a remedy.

**Comment by markuskramerIgitt** [comment]
@shortstack describes a loop of the exact event log entries the invalid `_schedule.conf` file causes. 

I found 8 minions that invalidated their `_schedule.conf` files "spontaneously".

This supports the assumption.
