### ISSUE TITLE
regex in kernelpkg latest_available() fails on Debian Buster kernel

### ISSUE THREAD

**Issue by thehunmonkgroup** [saltstack/salt#56219]
### Description of Issue

```latest_available()``` has the following regex to match the kernel version:

```python
version = re.match(r'^(\d+\.\d+\.\d+)\.(\d+)', result)
```

However, latest Debian Buster returns a kernel version that is not compatible with this regex:

```
# aptitude show linux-image-amd64
Package: linux-image-amd64        
Version: 4.19+105+deb10u3
State: installed (4.19+105+deb10u1), upgrade available (4.19+105+deb10u3)
Automatically installed: no
Priority: optional
Section: kernel
Maintainer: Debian Kernel Team <debian-kernel@lists.debian.org>
Architecture: amd64
Uncompressed Size: 17.4 k
Depends: linux-image-4.19.0-8-amd64
Provides: linux-latest-modules-4.19.0-8-amd64
Description: Linux for 64-bit PCs (meta-package)
 This package depends on the latest Linux kernel and modules for use on PCs with AMD64, Intel 64 or VIA Nano processors.
```

Which results in the following error:

```
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python3/dist-packages/salt/scripts.py", line 431, in salt_call
    client.run()
  File "/usr/lib/python3/dist-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 138, in run
    ret = self.call()
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 237, in call
    ret['return'] = self.minion.executors[fname](self.opts, data, func, args, kwargs)
  File "/usr/lib/python3/dist-packages/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/modules/kernelpkg_linux_apt.py", line 104, in latest_available
    version.group(1), version.group(2), _kernel_type())
AttributeError: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python3/dist-packages/salt/scripts.py", line 431, in salt_call
    client.run()
  File "/usr/lib/python3/dist-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 138, in run
    ret = self.call()
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 237, in call
    ret['return'] = self.minion.executors[fname](self.opts, data, func, args, kwargs)
  File "/usr/lib/python3/dist-packages/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/modules/kernelpkg_linux_apt.py", line 104, in latest_available
    version.group(1), version.group(2), _kernel_type())
AttributeError: 'NoneType' object has no attribute 'group'
```

### Setup
```yaml
install-latest-kernel:
  kernelpkg.latest_installed
```

### Steps to Reproduce Issue
From CLI:

```
salt-call kernelpkg.latest_available
```

### Versions Report
Running a *slightly* older version, but I verified that the code in ```latest_available()``` hasn't changed.

```
Salt Version:
           Salt: 2019.2.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.3 (default, Dec 20 2019, 18:57:59)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: debian 10.3 
         locale: UTF-8
        machine: x86_64
        release: 4.19.0-6-amd64
         system: Linux
        version: debian 10.3 
```

**Comment by waynew** [comment]
@sagetherage I'm assuming this should go into Sodium. It appears to have been broken for quite a while - I went back to debian 8 and this fails with current pkg version names.

**Comment by palfrey** [comment]
I'm seeing it working somehow?
```
> salt-ssh '*' kernelpkg.latest_available
server-0:
    4.19.0-14-amd64
```

This is on a Debian Buster machine, and I'm running Salt 3002.5

**Comment by grrodre** [comment]
It seems not to work with debian bullseye.

I was trying to debug a little bit and I found that this re expresion https://github.com/saltstack/salt/blob/master/salt/modules/kernelpkg_linux_apt.py#L105 does not match with the result variable _5.10.24-1_. Maybe it would work with a a dash instead?

`re.match(r"^(\d+\.\d+\.\d+)\-(\d+)", result)`


Regards

**Comment by sagetherage** [comment]
yes, we don't support Debian Bullseye, just yet. :)

**Comment by chstaudte** [comment]
It seems that this issue still persists after one year, so kernel upgrades can't be done on the current stable Debian release. Can maybe someone else confirm that?
