### ISSUE TITLE
amazon linux 1 test failures (Cannot allocate memory)

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#56235]
### Description of Issue

These tests:

```
    unit.test_proxy_minion.ProxyMinionTestCase.test_handle_decoded_payload_metaproxy_called
    unit.test_proxy_minion.ProxyMinionTestCase.test_handle_payload_metaproxy_called
    unit.test_proxy_minion.ProxyMinionTestCase.test_post_master_init_metaproxy_called
    setUpClass (unit.states.test_boto_apigateway.BotoApiGatewayUsagePlanTestCase)
```

are failing sometimes with error:

```
Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/unit/test_proxy_minion.py", line 34, in test_post_master_init_metaproxy_called
    proxy_minion = salt.minion.ProxyMinion(mock_opts, jid_queue=copy.copy(mock_jid_queue), io_loop=salt.ext.tornado.ioloop.IOLoop())
  File "/tmp/kitchen/testing/salt/minion.py", line 1145, in __init__
    self.opts['grains'] = salt.loader.grains(opts)
  File "/tmp/kitchen/testing/salt/loader.py", line 808, in grains
    ret = funcs[key]()
  File "/tmp/kitchen/testing/salt/grains/core.py", line 2381, in hwaddr_interfaces
    ifaces = _get_interfaces()
  File "/tmp/kitchen/testing/salt/grains/core.py", line 1558, in _get_interfaces
    _INTERFACES = salt.utils.network.interfaces()
  File "/tmp/kitchen/testing/salt/utils/network.py", line 1008, in interfaces
    return linux_interfaces()
  File "/tmp/kitchen/testing/salt/utils/network.py", line 843, in linux_interfaces
    stderr=subprocess.STDOUT).communicate()[0]
  File "/usr/lib64/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 938, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```

https://jenkinsci.saltstack.com/job/pr-amazon1-py2/job/master/627/

maybe similar to https://github.com/saltstack/salt/issues/56109 ?? but they are getting memory errors on different tests so might be different issue

**Comment by s0undt3ch** [comment]
Hotfix in https://github.com/saltstack/sre-jenkins/pull/261

**Comment by dmurphy18** [comment]
@Ch3LL @sagetherage You removed 3000.1 label and added Sodium, but we will not be supporting RHEL 6 or Amazon Linux 1 in Sodium.

Perhaps this should be closed, please do so if you agree.
