### ISSUE TITLE
windows ec2 cloud tests failing

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#56233]
### Description of Issue

https://jenkinsci.saltstack.com/job/pr-centos7-py3-cloud/job/master/

The following cloud tests are failing:

```
    integration.cloud.clouds.test_ec2.EC2Test.test_win2016_psexec
    integration.cloud.clouds.test_ec2.EC2Test.test_win2016_winrm
```

```
Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/cloud/clouds/test_ec2.py", line 187, in test_win2016_psexec
    self._test_instance('ec2-win2016-test', debug=True)
  File "/tmp/kitchen/testing/tests/integration/cloud/clouds/test_ec2.py", line 108, in _test_instance
    self.assertInstanceExists(ret_val)
  File "/tmp/kitchen/testing/tests/integration/cloud/helpers/cloud_test_base.py", line 97, in assertInstanceExists
    ', '.join(query)))
AssertionError: False is not true : Instance "cloud-test-ec2-5ojgew" was not created successfully
```

**Comment by Akm0d** [comment]
I'm pretty sure this is fixed with https://github.com/saltstack/salt/pull/55435, verifying now

**Comment by Akm0d** [comment]
No... Those tests fail instantly, even on the refactor, looking deeper

**Comment by Akm0d** [comment]
```
Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/cloud/helpers/cloud_test_base.py", line 54, in wrapper
    return caller(cls)
  File "/tmp/kitchen/testing/tests/integration/cloud/clouds/test_ec2.py", line 150, in test_win2016_psexec
    self._test_instance(self.WIN2016_PROFILE, debug=True)
  File "/tmp/kitchen/testing/tests/integration/cloud/clouds/test_ec2.py", line 83, in _test_instance
    self.assertCreateInstance(profile_config_name, args=['-l', 'debug'] if debug else [])
  File "/tmp/kitchen/testing/tests/integration/cloud/helpers/cloud_test_base.py", line 221, in assertCreateInstance
    self.assertInstanceExists(creation_ret=stdout, instance_name=instance_name, stderr=stderr)
  File "/tmp/kitchen/testing/tests/integration/cloud/helpers/cloud_test_base.py", line 234, in assertInstanceExists
    self.assertFalse([line for line in stderr if line.lstrip().startswith('[ERROR   ]')], stderr)
AssertionError: 
["[ERROR   ] AWS Response Status Code and Error: [401 401 Client Error: Unauthorized for url: https://ec2.us-west-2.amazonaws.com/?Action=RunInstances&***************&
```

**Comment by Ch3LL** [comment]
@Akm0d is there a workaround for these failures? looks like more are failing now:

    integration.cloud.clouds.test_ec2.EC2Test.test_win2012r2_psexec
    integration.cloud.clouds.test_ec2.EC2Test.test_win2012r2_winrm
    integration.cloud.clouds.test_ec2.EC2Test.test_win2016_psexec
    integration.cloud.clouds.test_ec2.EC2Test.test_win2016_winrm

from here: https://jenkinsci.saltstack.com/job/pr-centos7-py2-cloud/job/master/558/

**Comment by Ch3LL** [comment]
udpate: @Akm0d is still working on a fix here, but will not block this failure on 3000.1 release as verified to be working and the failures are test issues that need to be fixed due to some changes in how we parse repo.saltstack.com to verify the latest version.

**Comment by Ch3LL** [comment]
https://github.com/saltstack/salt/pull/57012
