### ISSUE TITLE
Unhelpful error message - sls include

### ISSUE THREAD

**Issue by peter-scott** [saltstack/salt#56253]
When running a highstate, I was getting the following error and traceback:
```
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    load_entry_point('salt==3000', 'console_scripts', 'salt-call')()
  File "/usr/lib/python3/dist-packages/salt/scripts.py", line 445, in salt_call
    client.run()
  File "/usr/lib/python3/dist-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 119, in run
    ret = self.call()
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 218, in call
    ret['return'] = self.minion.executors[fname](self.opts, data, func, args, kwargs)
  File "/usr/lib/python3/dist-packages/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/modules/state.py", line 783, in apply_
    return highstate(**kwargs)
  File "/usr/lib/python3/dist-packages/salt/modules/state.py", line 1087, in highstate
    orchestration_jid=orchestration_jid)
  File "/usr/lib/python3/dist-packages/salt/state.py", line 4058, in call_highstate
    high, errors = self.render_highstate(matches)
  File "/usr/lib/python3/dist-packages/salt/state.py", line 3926, in render_highstate
    sls, saltenv, mods, matches)
  File "/usr/lib/python3/dist-packages/salt/state.py", line 3663, in render_state
    if inc_sls.startswith('.'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

In the end, there was a simple typo that introduced a `None` item into the include list:
```
include:
  # essential invariable state
  - .source.core

  # get network utilities
  - .source.network
  -
  # configure preferences (language, time, keyboard layout, mappings, mime types)
  - .source.preferences
```

To trace this, I had to add the following temporary logging message because the traceback does not identify which state file was being inspected when the error occurred.

```
if not hasattr(inc_sls, 'startswith'):
  msg = "include error in SLS '{0}'".format(sls)
  log.error(msg)    
  errors.append(msg)
  continue
```

It would be helpful if there was some form of reporting for type errors in include lists.

### Versions Report
```
Salt Version:
           Salt: 3000
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.11
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.3 (default, Dec 20 2019, 18:57:59)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: debian 10.3 
         locale: UTF-8
        machine: x86_64
        release: 4.19.0-8-amd64
         system: Linux
        version: debian 10.3 
```

**Comment by mjbotes** [comment]
Can i please be assigned to this issue
