### ISSUE TITLE
tomcat module fails on python3

### ISSUE THREAD

**Issue by sabtom** [saltstack/salt#56269]
### Description of Issue
When using the tomcat module of salt, it does a call to the localhost tomcat manager via urlopen.
This call gives back byte encoded strings, on a few places in this module this is not accounted for and since python3 does a bit more stricter version checking it fails.

### Setup
Relevant part of sls:
``` yaml
Converter wait for Tomcat:
  tomcat.wait:
    - timeout: 300
```

### Steps to Reproduce Issue
We used this repo to install the salt minion:
deb http://repo.saltstack.com/py3/ubuntu/18.04/amd64/latest bionic main
Run state which uses the tomcat module.

Result:
``` bash
----------                                                                                                                                                                                     
          ID: Converter wait for Tomcat                                                                                                                                                        
    Function: tomcat.wait                                                                                                                                                                      
      Result: False                                                                                                                                                                            
     Comment: An exception occurred in this state: Traceback (most recent call last):                                                                                                          
                File "/usr/lib/python3/dist-packages/salt/state.py", line 1981, in call                                                                                                        
                  **cdata['kwargs'])                                                                                                                                                           
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 1977, in wrapper                                                                                                    
                  return f(*args, **kwargs)                                                                                                                                                    
                File "/usr/lib/python3/dist-packages/salt/states/tomcat.py", line 262, in wait                                                                                                 
                  result = __salt__['tomcat.status'](url, timeout)                                                                                                                             
                File "/usr/lib/python3/dist-packages/salt/modules/tomcat.py", line 324, in status                                                                                              
                  return _wget('list', {}, url, timeout=timeout)['res']                                                                                                                        
                File "/usr/lib/python3/dist-packages/salt/modules/tomcat.py", line 265, in _wget                                                                                               
                  if not ret['msg'][0].startswith('OK'):                                                                                                                       
              TypeError: startswith first arg must be bytes or a tuple of bytes, not str                                                                                                       
     Started: 10:10:08.888146                                                                                                                                                                  
    Duration: 31.016 ms                                                                                                                                                                        
     Changes:                                                                                                                                                                                  
----------    
```

### Versions Report
``` bash
Salt Version:
           Salt: 3000

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.3.10
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.9 (default, Nov  7 2019, 10:44:02)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: ISO-8859-1
        machine: x86_64
        release: 4.15.0-45-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```

**Comment by sagetherage** [comment]
closing as corrected by above PR and will be released in Sodium
