### ISSUE TITLE
International symbols in computer name on windows cause minion to fail on start 

### ISSUE THREAD

**Issue by enwony** [saltstack/salt#56279]
### Description of Issue
Minons fail to start if computer name set to non-english characters.
Old version  2015.8.3 is working with that, 2018.3.4 and 3000 is not.
No matter python 2.7/3.0

### Setup
tried windows 7 x64, windows 10 x64
tried saltstack minion 2018.3.4, 3000
tried both versions python2.7 and python3

### Steps to Reproduce Issue
* Set computer name on windows as "Компьютер" or any non-english title (Control panel - System - Computer)
* Try to setup/run saltstack minion version 3000
Got cyclic error in log (as for version "3000"):
```
2020-03-02` 16:29:02,839 [salt.log.setup   :880 ][ERROR   ][6868] An un-handled exception was caught by salt's global exception handler:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "c:\salt\bin\Scripts\salt-minion", line 4, in <module>
    __import__('pkg_resources').run_script('salt==3000', 'salt-minion')
  File "c:\salt\bin\lib\site-packages\pkg_resources\__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "c:\salt\bin\lib\site-packages\pkg_resources\__init__.py", line 1527, in run_script
    exec(code, namespace, namespace)
  File "c:\salt\bin\lib\site-packages\salt-3000-py2.7.egg\EGG-INFO\scripts\salt-minion", line 26, in <module>
    salt_minion()
  File "c:\salt\bin\lib\site-packages\salt-3000-py2.7.egg\salt\scripts.py", line 205, in salt_minion
    minion.start()
  File "c:\salt\bin\lib\site-packages\salt-3000-py2.7.egg\salt\cli\daemons.py", line 326, in start
    self._real_start()
  File "c:\salt\bin\lib\site-packages\salt-3000-py2.7.egg\salt\cli\daemons.py", line 338, in _real_start
    self.minion.tune_in()
  File "c:\salt\bin\lib\site-packages\salt-3000-py2.7.egg\salt\minion.py", line 1074, in tune_in
    self._spawn_minions()
  File "c:\salt\bin\lib\site-packages\salt-3000-py2.7.egg\salt\minion.py", line 1018, in _spawn_minions
    jid_queue=self.jid_queue)
  File "c:\salt\bin\lib\site-packages\salt-3000-py2.7.egg\salt\minion.py", line 986, in _create_minion_object
    jid_queue=jid_queue)
  File "c:\salt\bin\lib\site-packages\salt-3000-py2.7.egg\salt\minion.py", line 1145, in __init__
    self.opts['grains'] = salt.loader.grains(opts)
  File "c:\salt\bin\lib\site-packages\salt-3000-py2.7.egg\salt\loader.py", line 808, in grains
    ret = funcs[key]()
  File "c:\salt\bin\lib\site-packages\salt-3000-py2.7.egg\salt\grains\core.py", line 2209, in hostname
    (grains['host'], grains['domain']) = grains['fqdn'].partition('.')[::2]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 0: ordinal not in range(128)
```

### Versions Report
```
Salt Version:
           Salt: 3000

Dependency Versions:
           cffi: 1.12.2
       cherrypy: 17.4.1
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.6
      gitpython: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: Not Installed
   pycryptodome: 3.8.1
         pygit2: Not Installed
         Python: 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.4.4
         PyYAML: 5.1.2
          PyZMQ: 18.0.1
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: cp1251
        machine: AMD64
        release: 7
         system: Windows
        version: 7 6.1.7601 SP1 Multiprocessor Free
```

**Comment by garethgreenaway** [comment]
@twangboy FYI.

**Comment by githubcdr** [comment]
Ran into similar issue with pygit2 when I tried to copy a file with unicode from file_root;

```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 6841: ordinal not in range(128)
[ERROR   ] Error in function _serve_file:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1839, in run_func
    ret = getattr(self, func)(load)
  File "/usr/lib/python3/dist-packages/salt/fileserver/__init__.py", line 650, in serve_file
    return self.servers[fstr](load, fnd)
  File "/usr/lib/python3/dist-packages/salt/fileserver/gitfs.py", line 170, in serve_file
    return _gitfs().serve_file(load, fnd)
  File "/usr/lib/python3/dist-packages/salt/utils/gitfs.py", line 2861, in serve_file
    data = data.decode(__salt_system_encoding__)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 6841: ordinal not in range(128)
```

file snippet

```
  # Example:
  #
  #   typeset -g POWERLEVEL9K_DIR_CLASSES=(
  #       '~/work(|/*)'  WORK     '(╯°□°）╯︵ ┻━┻'
  #       '~(|/*)'       HOME     '⌂'
  #       '*'            DEFAULT  '')
  #
  # With these settings, the current directory in the prompt may look like this:
  #
  #   (╯°□°）╯︵ ┻━┻ ~/work/projects/important/urgent
  #
```

**Comment by sagetherage** [comment]
not stale

**Comment by twangboy** [comment]
Salt recently adopted Python 3.7 as the default python for Windows. Python 3.7 is now bundled in the Salt Windows Installer starting with 3001. Python 3.7 has many improvements for handling Unicode on Windows.

Could you please try with the 3001.1 build? I am unable to replicate.

**Comment by enwony** [comment]
Repeated with win 7 x64 with salt win x64 3001.1 build - not reproduced anymore.
Could somebody link pull request to understand what caused it to change behavior?
I can retest it if requested.

Version report for analysis
```
Salt Version:
           Salt: 3001.1

Dependency Versions:
           cffi: 1.12.2
       cherrypy: 17.4.1
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 1.0.0
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: Not Installed
   pycryptodome: 3.9.7
         pygit2: Not Installed
         Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
   python-gnupg: 0.4.4
         PyYAML: 5.3.1
          PyZMQ: 18.0.1
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: cp1251
        machine: AMD64
        release: 7
         system: Windows
        version: 7 6.1.7601 SP1

```

**Comment by twangboy** [comment]
It was the transition to Python 3.7.

**Comment by sagetherage** [comment]
@enwony we don't necessarily have a specific PR, but the upgrade to Python 3 that handle unicode better. That isn't super helpful, I realize.

**Comment by sagetherage** [comment]
if you have this working, I will close this, please mention me if need anything or want this reopened.

**Comment by enwony** [comment]
Any reference is better than nothing, python 3.7 is ok.
