### ISSUE TITLE
salt.exceptions.SaltClientError in pipenv virtual env

### ISSUE THREAD

**Issue by vikramhansawat** [saltstack/salt#56292]
### Description of Issue
Gets the following error while try to create salt.client.Caller object inside pipenv. The same object creation works pretty well outside of pipenv venv.

### Steps to Reproduce Issue
vikky@vikky:~/blueprints$ pip install pipenv==2018.11.26
vikky@vikky:~/blueprints$ pipenv shell
Launching subshell in virtual environment...
 . /home/vikky/.local/share/virtualenvs/blueprints-qKQexZsE/bin/activate
vikky@vikky:~/blueprints$  . /home/vikky/.local/share/virtualenvs/blueprints-qKQexZsE/bin/activate
(blueprints) vikky@vikky:~/FARFETCH/git-repos/blueprints$ python
Python 2.7.15+ (default, Oct  7 2019, 17:39:04) 
[GCC 7.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import salt.client
>>> _salt = salt.client.Caller()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vikky/.local/share/virtualenvs/blueprints-qKQexZsE/local/lib/python2.7/site-packages/salt/client/__init__.py", line 2107, in __init__
    self.sminion = salt.minion.SMinion(self.opts)
  File "/home/vikky/.local/share/virtualenvs/blueprints-qKQexZsE/local/lib/python2.7/site-packages/salt/minion.py", line 793, in __init__
    lambda: self.eval_master(self.opts, failed=True)
  File "/home/vikky/.local/share/virtualenvs/blueprints-qKQexZsE/local/lib/python2.7/site-packages/tornado/ioloop.py", line 458, in run_sync
    return future_cell[0].result()
  File "/home/vikky/.local/share/virtualenvs/blueprints-qKQexZsE/local/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/home/vikky/.local/share/virtualenvs/blueprints-qKQexZsE/local/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/vikky/.local/share/virtualenvs/blueprints-qKQexZsE/local/lib/python2.7/site-packages/salt/minion.py", line 706, in eval_master
    raise exc
salt.exceptions.SaltClientError: Attempt to authenticate with the salt master failed with timeout error
>>> 

$ python
Python 2.7.15+ (default, Oct  7 2019, 17:39:04) 
[GCC 7.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import salt.client
>>> _salt = salt.client.Caller()
>>> 

### Versions Report
vikky@vikky:~/blueprints$ grep salt Pipfile
salt = "==2018.3.3"
vikky@vikky:~/blueprints$ salt-minion --versions
Salt Version:
           Salt: 2018.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: 4.0.2
          gitdb: 2.0.6
      gitpython: 2.1.11
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15+ (default, Oct  7 2019, 17:39:04)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 18.0.1
           RAET: Not Installed
          smmap: 3.0.1
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-65-generic
         system: Linux
        version: Ubuntu 18.04 bionic

vikky@vikky:~/blueprints$ pipenv --version
pipenv, version 2018.11.26

**Comment by garethgreenaway** [comment]
@saltstack/team-core Any thoughts on this one?

**Comment by DmitryKuzmenko** [comment]
Reproduced on Arch. Works with system python 2.7 interpreter. Fails with the same stack trace in any of `pipenv` and `pyenv` 2.7 environments.

**Comment by DmitryKuzmenko** [comment]
Interesting that there's a difference between `pipenv` and `pyenv` on master with python 3.7.7.

pyenv:
```
$ python
Python 3.7.7 (default, Mar 31 2020, 15:13:24) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import salt.client
>>> _salt = salt.client.Caller()
>>> 
```

pipenv:
```
$ python
Python 3.7.7 (default, Mar 31 2020, 15:13:24) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import salt.client
>>> _salt = salt.client.Caller()
Traceback (most recent call last):
  File "/home/dimm/projects/salt/git/salt/salt/crypt.py", line 702, in sign_in
    timeout=timeout
  File "/home/dimm/projects/salt/git/salt/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/home/dimm/projects/salt/git/salt/salt/ext/tornado/concurrent.py", line 239, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/dimm/projects/salt/git/salt/salt/ext/tornado/gen.py", line 1064, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/dimm/projects/salt/git/salt/salt/transport/zeromq.py", line 384, in send
    ret = yield self._uncrypted_transfer(load, tries=tries, timeout=timeout)
  File "/home/dimm/projects/salt/git/salt/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/home/dimm/projects/salt/git/salt/salt/ext/tornado/concurrent.py", line 239, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/dimm/projects/salt/git/salt/salt/ext/tornado/gen.py", line 1064, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/dimm/projects/salt/git/salt/salt/transport/zeromq.py", line 373, in _uncrypted_transfer
    tries=tries,
  File "/home/dimm/projects/salt/git/salt/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/home/dimm/projects/salt/git/salt/salt/ext/tornado/concurrent.py", line 239, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
salt.exceptions.SaltReqTimeoutError: Message timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dimm/projects/salt/git/salt/salt/client/__init__.py", line 1993, in __init__
    self.sminion = salt.minion.SMinion(self.opts)
  File "/home/dimm/projects/salt/git/salt/salt/minion.py", line 852, in __init__
    lambda: self.eval_master(self.opts, failed=True)
  File "/home/dimm/projects/salt/git/salt/salt/ext/tornado/ioloop.py", line 459, in run_sync
    return future_cell[0].result()
  File "/home/dimm/projects/salt/git/salt/salt/ext/tornado/concurrent.py", line 239, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/dimm/projects/salt/git/salt/salt/ext/tornado/gen.py", line 1064, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/dimm/projects/salt/git/salt/salt/minion.py", line 712, in eval_master
    raise last_exc  # pylint: disable=E0702
  File "/home/dimm/projects/salt/git/salt/salt/minion.py", line 680, in eval_master
    yield pub_channel.connect()
  File "/home/dimm/projects/salt/git/salt/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/home/dimm/projects/salt/git/salt/salt/ext/tornado/concurrent.py", line 239, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/dimm/projects/salt/git/salt/salt/ext/tornado/gen.py", line 1064, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/dimm/projects/salt/git/salt/salt/transport/zeromq.py", line 512, in connect
    yield self.auth.authenticate()
  File "/home/dimm/projects/salt/git/salt/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/home/dimm/projects/salt/git/salt/salt/ext/tornado/concurrent.py", line 239, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/dimm/projects/salt/git/salt/salt/crypt.py", line 604, in _authenticate
    creds = yield self.sign_in(channel=channel)
  File "/home/dimm/projects/salt/git/salt/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/home/dimm/projects/salt/git/salt/salt/ext/tornado/concurrent.py", line 239, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/dimm/projects/salt/git/salt/salt/ext/tornado/gen.py", line 1064, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/dimm/projects/salt/git/salt/salt/crypt.py", line 711, in sign_in
    raise SaltClientError('Attempt to authenticate with the salt master failed with timeout error')
salt.exceptions.SaltClientError: Attempt to authenticate with the salt master failed with timeout error
>>>
```
