### ISSUE TITLE
[BUG] salt-api causing errors in master when calling state.sls with pillar kwargs

### ISSUE THREAD

**Issue by SammyTbeile** [saltstack/salt#56371]
### Description of Issue
I'm trying to run `salt 'sammy*' state.sls 'state' pillar='{"foo":"bar"}'` via the salt-api. I tried using pepper and ran into errors that I thought were due to pepper (https://github.com/saltstack/pepper/issues/204) however, upon converting this to use curl, I'm running into the same issues

### Setup
The relevant section in my eauth:
```
external_auth:
  ldap:
    minion_ldap_group%:
       - '*.dev.okcupid.com':
          - 'state.sls':
              args:
                - 'docker.swarm.okapi.service_update'
              kwargs:
                - 'pillar': '*'
          - test.*
```
The json I'm sending:
```
[{
        "client":"local",
        "tgt":"sammy*",
        "fun":"state.sls",
        "arg":"state",
        "kwarg": {
                "pillar":{"foo":"bar"}
        }
}]
```
### Steps to Reproduce Issue
Login to salt-api, then issue the following command:
```
curl  https://master:XXXX -H "Content-Type: application/json" -H 'X-Auth-Token: token' -d @payload.json
```

Results in the following error on the master:
```
Some exception handling a payload from minion
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 773, in handle_message
    ret, req_opts = yield self.payload_handler(payload)
  File "/usr/lib/python2.7/dist-packages/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/usr/lib/python2.7/dist-packages/salt/ext/tornado/concurrent.py", line 239, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/dist-packages/salt/ext/tornado/gen.py", line 294, in wrapper
    result = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 1065, in _handle_payload
    'clear': self._handle_clear}[key](load)
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 1096, in _handle_clear
    ret = getattr(self.clear_funcs, cmd)(load), {'fun': 'send_clear'}
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 2101, in publish
    whitelist=['saltutil.find_job'],
  File "/usr/lib/python2.7/dist-packages/salt/utils/minions.py", line 962, in auth_check
    if self.__fun_check(ind[valid], fun, fun_args, fun_kwargs):
  File "/usr/lib/python2.7/dist-packages/salt/utils/minions.py", line 1073, in __fun_check
    if self.__args_check(cond[fname_cond], args, kwargs):
  File "/usr/lib/python2.7/dist-packages/salt/utils/minions.py", line 1103, in __args_check
    for k, v in six.iteritems(cond_kwargs):
  File "/usr/lib/python2.7/dist-packages/salt/ext/six.py", line 606, in iteritems
    return d.iteritems(**kw)
AttributeError: 'list' object has no attribute 'iteritems'
[ERROR   ] Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 454, in _handle_events
    self._handle_send()
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 493, in _handle_send
    status = self.socket.send_multipart(msg, **kwargs)
  File "/usr/lib/python2.7/dist-packages/zmq/sugar/socket.py", line 434, in send_multipart
    i, rmsg,
TypeError: Frame 0 (u'Some exception handling minion...) does not support the buffer interface.
[ERROR   ] Exception in callback <functools.partial object at 0x7f0306a90260>
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/ext/tornado/ioloop.py", line 606, in _run_callback
    ret = callback()
  File "/usr/lib/python2.7/dist-packages/salt/ext/tornado/stack_context.py", line 278, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 536, in <lambda>
    self.io_loop.add_callback(lambda : self._handle_events(self.socket, 0))
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 454, in _handle_events
    self._handle_send()
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 493, in _handle_send
    status = self.socket.send_multipart(msg, **kwargs)
  File "/usr/lib/python2.7/dist-packages/zmq/sugar/socket.py", line 434, in send_multipart
    i, rmsg,
TypeError: Frame 0 (u'Some exception handling minion...) does not support the buffer interface.
```

### Versions Report
salt master:
```
Salt Version:
           Salt: 3000

Dependency Versions:
           cffi: 1.12.3
       cherrypy: unknown
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.11
         Jinja2: 2.9.4
        libgit2: 0.26.8
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 2.7.16 (default, Apr  6 2019, 01:42:57)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist: debian 10.0
         locale: UTF-8
        machine: x86_64
        release: 4.19.0-5-amd64
         system: Linux
        version: debian 10.0
```
salt-minion if relevant:
```
Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.3.7
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Sep 26 2018, 18:42:22)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.9
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-9-amd64
         system: Linux
        version: debian 9.9
```

**Comment by SammyTbeile** [comment]
This was due to me not setting kwargs as a dict in eauth
