### ISSUE TITLE
integration.shell.test_saltcli tests failing sometimes on mac

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#56399]
### Description of Issue
The `integration.shell.test_saltcli` tests are failing sometimes on macosx.

https://jenkinsci.saltstack.com/job/pr-macosxmojave-py2/job/PR-56380/1/

```
integration.shell.test_saltcli.RetcodeTestCase.test_salt_error
Traceback (most recent call last):
  File "/private/tmp/kitchen/testing/tests/integration/shell/test_saltcli.py", line 182, in test_salt_error
    self._test_error()
  File "/private/tmp/kitchen/testing/tests/integration/shell/test_saltcli.py", line 122, in _test_error
    assert retcode == self.error_status, retcode
AssertionError: 64
```

```
integration.shell.test_saltcli.RetcodeTestCase.test_missing_minion
Traceback (most recent call last):
  File "/private/tmp/kitchen/testing/tests/integration/shell/test_saltcli.py", line 201, in test_missing_minion
    assert retcode == salt.defaults.exitcodes.EX_GENERIC, retcode
AssertionError: None
```

https://jenkinsci.saltstack.com/job/pr-macosxmojave-py2/job/master/661/testReport/junit/integration.shell.test_saltcli/RetcodeTestCase/test_missing_minion/

**Comment by DmitryKuzmenko** [comment]
@Ch3LL am I right this was failing only with Python2? Can we close this now?

**Comment by Ch3LL** [comment]
yes should be fine for now. i'll re-open if i see it on python3
