### ISSUE TITLE
3000.1 Mac Packages Minion won't start

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#56416]
There is an error with the  3000.1 Mac packages.

It seems to install fine but give this traceback:
```
Traceback (most recent call last):
  File "/opt/salt/bin/salt", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/opt/salt/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3017, in <module>
    @_call_aside
  File "/opt/salt/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/opt/salt/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3030, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/opt/salt/lib/python3.5/site-packages/pkg_resources/__init__.py", line 659, in _build_master
    ws.require(__requires__)
  File "/opt/salt/lib/python3.5/site-packages/pkg_resources/__init__.py", line 967, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/salt/lib/python3.5/site-packages/pkg_resources/__init__.py", line 853, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pyobjc-framework-AdSupport==5.1.2; platform_release >= "18.0"' distribution was not found and is required by pyobjc
```

**Comment by frogunder** [comment]
https://github.com/saltstack/salt/pull/56417
