### ISSUE TITLE
Get UnicodeDecoderError after salt compiled

### ISSUE THREAD

**Issue by ryanking8215** [saltstack/salt#56413]
### Description of Issue

Normal salt-minion is working OK. 
Salt-minion is running on a MIPS board, so I have to decrease its size, then I compile salt to pyc files and delete all the py files.

But with this compiled version of salt, salt-minion will get such error when connecting to the salt-master which runs on a x64 ubuntu system.

```
[CRITICAL] Unexpected error while connecting to 192.168.1.2
Traceback (most recent call last):
  File "pyvenv/lib/python3.7/site-packages/salt/minion.py", line 1036, in _connect_minion
  File "pyvenv/lib/python3.7/site-packages/salt/ext/tornado/gen.py", line 1056, in run
  File "pyvenv/lib/python3.7/site-packages/salt/ext/tornado/concurrent.py", line 239, in result
  File "<string>", line 4, in raise_exc_info
  File "pyvenv/lib/python3.7/site-packages/salt/ext/tornado/gen.py", line 1064, in run
  File "pyvenv/lib/python3.7/site-packages/salt/minion.py", line 1234, in connect_master
  File "pyvenv/lib/python3.7/site-packages/salt/ext/tornado/gen.py", line 1056, in run
  File "pyvenv/lib/python3.7/site-packages/salt/ext/tornado/concurrent.py", line 239, in result
  File "<string>", line 4, in raise_exc_info
  File "pyvenv/lib/python3.7/site-packages/salt/ext/tornado/gen.py", line 309, in wrapper
  File "pyvenv/lib/python3.7/site-packages/salt/minion.py", line 754, in eval_master
  File "pyvenv/lib/python3.7/site-packages/salt/transport/client.py", line 185, in factory
  File "pyvenv/lib/python3.7/site-packages/salt/transport/zeromq.py", line 35, in <module>
  File "pyvenv/lib/python3.7/site-packages/salt/transport/mixins/auth.py", line 16, in <module>
  File "pyvenv/lib/python3.7/site-packages/salt/master.py", line 35, in <module>
  File "pyvenv/lib/python3.7/site-packages/salt/client/ssh/__init__.py", line 195, in <module>
  File "/codecs.py", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 12: invalid continuation byte
```

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
compiling  running on MIPS board
```
python3 -m compileall -b salt
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Salt Version:
           Salt: 3000
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10.3
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.6 (default, Jan 06 2020, 16:47:09)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 18.1.1
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist:   
         locale: UTF-8
        machine: mips
        release: 4.14.162
         system: Linux
        version: Not Installed

I wonder why salt of py files is ok and of pyc files gets error.

**Comment by ryanking8215** [comment]
I have solved the problem. 

in file client/ssh/__init__.py:195
```python
if not is_windows():
    shim_file = os.path.join(os.path.dirname(__file__), 'ssh_py_shim.py')
    if not os.path.exists(shim_file):
        # On esky builds we only have the .pyc file
        shim_file += 'c'
    with salt.utils.files.fopen(shim_file) as ssh_py_shim:
        SSH_PY_SHIM = ssh_py_shim.read()

```

Because I compiled 'ssh_py_shim.py' to 'ssh_py_shim.pyc'. It seems has bug with reading pyc file.
 I just use ssh_py_shim.py instead of pyc file.

**Comment by waynew** [comment]
So that's actually really cool! I've not seen Salt run on a MIPS board. Also neat that you're able to run just the .pyc files.

Looking a little closer at this, it probably only works on Python 2 because bytes and text are conflated, when they've been separated under Python3. Looks like this will probably fail under Python3 any time there's no `.py` file.

**Comment by ryanking8215** [comment]
Salt supports pyc files in __pycache__ only if working on Python3, which I learned from "loader.py". So after compiling salt by legacy way, salt failed to run because LazyLoader can't load pyc files.

So I stop working on compiling stuff currently. 
I think It is worth to decrease size by deleting files not used rather than compiling to *.pyc.
