### ISSUE TITLE
salt-api returns internal server error with TypeError: unhashable type: 'dict'

### ISSUE THREAD

**Issue by pprkut** [saltstack/salt#56495]
### Description of Issue
We have a working setup of saltstack 2018.3. Trying to update to 2019.2 we noticed that salt-api stopped working as users couldn't login anymore. Looking at the logs revealed this error:

```
2020-04-01 19:14:24,446 [tornado.application:1547][ERROR   ][5131] Uncaught exception POST /login (127.0.0.1)
HTTPServerRequest(protocol='https', host='localhost:8008', method='POST', uri='/login', version='HTTP/1.0', remote_ip='127.0.0.1', headers={'Host': 'localhost:8008', 'Connection': 'close', 'Content-Length': '63', 'User-Agent': 'check_http/v2.3.1 (nagios-plugins 2.3.1)', 'Accept': '*/*', 'Content-Type': 'application/x-www-form-urlencoded'})
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/tornado/web.py", line 1466, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/usr/lib/python3.6/site-packages/salt/netapi/rest_tornado/saltnado.py", line 758, in post
    perms = sorted(list(set(perms)))
TypeError: unhashable type: 'dict'
2020-04-01 19:14:24,449 [tornado.access   :1970][ERROR   ][5131] 500 POST /login (127.0.0.1) 88.48ms
```

### Setup

```
external_auth:
  pam:
    jenkinsbot:
      - 'G@ec2_tags:role:jenkins':
        - 'event.send'

rest_tornado:
  port: 8008
  address: 0.0.0.0
  debug: True
  ssl_crt: /etc/letsencrypt/live/salt.example.com/fullchain.pem
  ssl_key: /etc/letsencrypt/live/salt.example.com/privkey.pem
  websockets: False
  cors_origin: '*'
```

### Steps to Reproduce Issue
Try to login as the jenkinsbot user

### Versions Report
```
Salt Version:
           Salt: 2018.3.5

Dependency Versions:
           cffi: 1.9.1
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: 0.26.6
        libnacl: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 3.6.8 (default, Aug  7 2019, 17:28:10)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.7.1908 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1062.4.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.7.1908 Core
```

This is the report of the working 2018.3 system. The only thing we changed was update salt, salt-minion, salt-master, salt-api and salt-cloud to 2019.2.3 on that server (it's the salt master server).

**Comment by xeacott** [comment]
Thanks for reporting! We'll have to take a look at the diffs from those files between those releases to see exactly which code changes that would cause that :) it may be the upgrade in tornado

**Comment by SMillerDev** [comment]
Anything that can be done to help debug this @xeacott ?

**Comment by oeuftete** [comment]
I can reproduce this in 3001 as well.  A little more detail which might help focus in on where the problem lies.

This configuration seems to work:

```yaml
rest_tornado:
  port: 8000
  address: 0.0.0.0
  debug: True
  websockets: False
  cors_origin: '*'
  ssl_crt: /etc/pki/tls/certs/localhost.crt
  ssl_key: /etc/pki/tls/certs/localhost.key

external_auth:
  pam:
    salt-api:
      - .*
```

```text
$ curl -sSk -H 'Accept: application/x-yaml' https://localhost:8000/login -d username=salt-api -d password=redacted -d eauth=pam
return:
- eauth: pam
  expire: 1592620331.737281
  perms: [.*]
  start: 1592577131.7372808
  token: f1c34ae54053cb99d46a543b8fae1bf1ecc56ab77cf9d830c404e8929637f997
  user: salt-api
```

However, if I use the ["by minion, by user" `external_auth` configuration](https://docs.saltstack.com/en/latest/topics/eauth/index.html#matching-syntax):

```yaml
external_auth: 
  pam: 
    salt-api: 
      - 'G@id:master1': 
        - .* 
```

```text
$ curl -sSk -H 'Accept: application/x-yaml' https://localhost:8000/login -d username=salt-api -d password=redacted -d eauth=pam
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/web.py", line 1511, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/usr/lib/python3.6/site-packages/salt/netapi/rest_tornado/saltnado.py", line 781, in post
    perms = sorted(list(set(perms)))
TypeError: unhashable type: 'dict'
```

**Comment by oeuftete** [comment]
Here's the diff between 2018.3.5 and 2019.2.5:

```diff
diff --git a/salt/netapi/rest_tornado/saltnado.py b/salt/netapi/rest_tornado/saltnado.py
index 53c2b197ab..d6b3674665 100644
--- a/salt/netapi/rest_tornado/saltnado.py
+++ b/salt/netapi/rest_tornado/saltnado.py
@@ -208,8 +208,8 @@ import salt.ext.six as six
 import salt.netapi
 import salt.utils.args
 import salt.utils.event
-import salt.utils.jid
 import salt.utils.json
+import salt.utils.minions
 import salt.utils.yaml
 import salt.utils.zeromq
 from salt.utils.event import tagify
@@ -743,8 +743,19 @@ class SaltAuthHandler(BaseSaltAPIHandler):  # pylint: disable=W0223
 
         # Grab eauth config for the current backend for the current user
         try:
-            perms = self.application.opts['external_auth'][token['eauth']][token['name']]
+            eauth = self.application.opts['external_auth'][token['eauth']]
+            # Get sum of '*' perms, user-specific perms, and group-specific perms
+            perms = eauth.get(token['name'], [])
+            perms.extend(eauth.get('*', []))
 
+            if 'groups' in token and token['groups']:
+                user_groups = set(token['groups'])
+                eauth_groups = set([i.rstrip('%') for i in eauth.keys() if i.endswith('%')])
+
+                for group in user_groups & eauth_groups:
+                    perms.extend(eauth['{0}%'.format(group)])
+
+            perms = sorted(list(set(perms)))
         # If we can't find the creds, then they aren't authorized
         except KeyError:
             self.send_error(401)
```
