### ISSUE TITLE
Broken pyproject.toml

### ISSUE THREAD

**Issue by mchugh19** [saltstack/salt#56579]
### Description of Issue
When following the instructions on https://docs.saltstack.com/en/master/topics/development/hacking.html and trying to run `pip -e ./salt`, the pip command fails with:
```
$ pip install -e ./
Obtaining file:///home/xian/tech/gits/salt
ERROR: Exception:
Traceback (most recent call last):
  File "/home/xian/.local/share/virtualenvs/salt-csy8NuFj/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/home/xian/.local/share/virtualenvs/salt-csy8NuFj/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 331, in run
    resolver.resolve(requirement_set)
  File "/home/xian/.local/share/virtualenvs/salt-csy8NuFj/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/home/xian/.local/share/virtualenvs/salt-csy8NuFj/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/xian/.local/share/virtualenvs/salt-csy8NuFj/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 265, in _get_abstract_dist_for
    return self.preparer.prepare_editable_requirement(req)
  File "/home/xian/.local/share/virtualenvs/salt-csy8NuFj/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 555, in prepare_editable_requirement
    req, self.req_tracker, self.finder, self.build_isolation,
  File "/home/xian/.local/share/virtualenvs/salt-csy8NuFj/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 95, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/home/xian/.local/share/virtualenvs/salt-csy8NuFj/lib/python3.7/site-packages/pip/_internal/distributions/sdist.py", line 33, in prepare_distribution_metadata
    self.req.load_pyproject_toml()
  File "/home/xian/.local/share/virtualenvs/salt-csy8NuFj/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 516, in load_pyproject_toml
    str(self)
  File "/home/xian/.local/share/virtualenvs/salt-csy8NuFj/lib/python3.7/site-packages/pip/_internal/pyproject.py", line 75, in load_pyproject_toml
    pp_toml = pytoml.load(f)
  File "/home/xian/.local/share/virtualenvs/salt-csy8NuFj/lib/python3.7/site-packages/pip/_vendor/pytoml/parser.py", line 11, in load
    return loads(fin.read(), translate=translate, object_pairs_hook=object_pairs_hook, filename=getattr(fin, 'name', repr(fin)))
  File "/home/xian/.local/share/virtualenvs/salt-csy8NuFj/lib/python3.7/site-packages/pip/_vendor/pytoml/parser.py", line 24, in loads
    ast = _p_toml(src, object_pairs_hook=object_pairs_hook)
  File "/home/xian/.local/share/virtualenvs/salt-csy8NuFj/lib/python3.7/site-packages/pip/_vendor/pytoml/parser.py", line 341, in _p_toml
    s.expect_eof()
  File "/home/xian/.local/share/virtualenvs/salt-csy8NuFj/lib/python3.7/site-packages/pip/_vendor/pytoml/parser.py", line 123, in expect_eof
    return self._expect(self.consume_eof())
  File "/home/xian/.local/share/virtualenvs/salt-csy8NuFj/lib/python3.7/site-packages/pip/_vendor/pytoml/parser.py", line 163, in _expect
    raise TomlError('msg', self._pos[0], self._pos[1], self._filename)
pip._vendor.pytoml.core.TomlError: /home/xian/tech/gits/salt/pyproject.toml(2, 1): msg
```
moving pyproject.toml out of the way allows `pip -e .` to continue

### Versions Report
git checkout

**Comment by sagetherage** [comment]
@s0undt3ch I think this is fixed but we need a documentation review to update the docs in the all the places, yes?

**Comment by s0undt3ch** [comment]
@mchugh19 and if you try from https://github.com/saltstack/salt/pull/56904 ?
It's now obolete and needs to be updated to master, but still?

**Comment by s0undt3ch** [comment]
No @sagetherage this is not fixed.

**Comment by garethgreenaway** [comment]
I wasn't able to reproduce this one so I believe it's fixed.  If the issue persists, please open a new issue.  Thanks!
