### ISSUE TITLE
PyMySQL Error Handling broken - workaround required

### ISSUE THREAD

**Issue by awerner** [saltstack/salt#56570]
### Description of Issue
PyMySQL raises InternalError Exception ins specific cases. The _connect method in the mysql module only checks for OperationalError. PyMySQL raising InternalError is clearly an upstream bug, and was already fixed with https://github.com/PyMySQL/PyMySQL/pull/823. But as there has been no stable release of PyMySQL since 2018, this fix is not widely available. So it would be very handy if the mysql module could also check for InternalError with code > 1000 and handle it the same way.

### Setup

```
set root password for home:
  mysql_user:
    - present
    - name: root
    - host: 127.0.0.1
    - password: somepass
    - onlyif: mysql -e quit
    - connection_user: root
    - connection_pass: ''
```

Here the resulting Exception, not only version is affected, also other methods such as verify_login.

```
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/local/lib/python3.7/site-packages/salt/state.py", line 1933, in call
                  **cdata['kwargs'])
                File "/usr/local/lib/python3.7/site-packages/salt/loader.py", line 1951, in wrapper
                  return f(*args, **kwargs)
                File "/usr/local/lib/python3.7/site-packages/salt/states/mysql_user.py", line 142, in present
                  **connection_args):
                File "/usr/local/lib/python3.7/site-packages/salt/modules/mysql.py", line 1266, in user_exists
                  server_version = salt.utils.data.decode(version(**connection_args))
                File "/usr/local/lib/python3.7/site-packages/salt/modules/mysql.py", line 858, in version
                  dbc = _connect(**connection_args)
                File "/usr/local/lib/python3.7/site-packages/salt/modules/mysql.py", line 392, in _connect
                  dbc = MySQLdb.connect(**connargs)
                File "/usr/local/lib/python3.7/site-packages/pymysql/__init__.py", line 94, in Connect
                  return Connection(*args, **kwargs)
                File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 325, in __init__
                  self.connect()
                File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 599, in connect
                  self._request_authentication()
                File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 861, in _request_authentication
                  auth_packet = self._read_packet()
                File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 684, in _read_packet
                  packet.check_error()
                File "/usr/local/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
                  err.raise_mysql_exception(self._data)
                File "/usr/local/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
                  raise errorclass(errno, errval)
              pymysql.err.InternalError: (1698, "Access denied for user 'root'@'localhost'")
     Started: 19:25:23.322454
    Duration: 57.027 ms
     Changes:
```

### Versions Report

```
Salt Version:
           Salt: 2019.2.3
 
Dependency Versions:
           cffi: 1.14.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.6 (default, Jan 30 2020, 01:17:24)
   python-gnupg: Not Installed
         PyYAML: 5.2
          PyZMQ: 18.1.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist:   
         locale: UTF-8
        machine: amd64
        release: 12.1-RELEASE-p2
         system: FreeBSD
        version: Not Installed
```
Here the relevant system packages:
```
py37-pymysql-0.9.3             Pure Python MySQL Driver
mariadb104-client-10.4.12      Multithreaded SQL database (client)
mariadb104-server-10.4.12      Multithreaded SQL database (server)
```

**Comment by frogunder** [comment]
@awerner Thank you for reporting this issue.

**Comment by sagetherage** [comment]
PR is merged and will be released in Sodium
