### ISSUE TITLE
win_pkg: python3_x64 failed but is installed successfully

### ISSUE THREAD

**Issue by var314** [saltstack/salt#56587]
### Description of Issue
python3_x64 install status is success but the overall result is False. The python is actually installed.

```bash
          ID: python3_x64
    Function: pkg.installed
      Result: False
     Comment: The following packages failed to install/update: python3_x64=3.4.3150
     Started: 20:39:00.515928
    Duration: 14407.358 ms
     Changes:
              ----------
              Python 3.4.3 (64-bit):
                  ----------
                  new:
                      3.4.3150
                  old:
              python3_x64:
                  ----------
                  install status:
                      success
```

Seeing some similar issues I looked in `/srv/salt/win/repo-ng/salt-winrepo-ng/python3_x64.sls`. There is:
```
full_name: 'Python {{ VER }} Core Interpreter (64-bit)'
```
After changing to `full_name: 'Python {{ VER }} (64-bit)'` the issue is gone.

### Setup

python.sls

```
python3_x64:
  pkg.installed:
    - version: 3.4.3150
```

Logs from minion:

```
2020-04-08 20:38:50,205 [salt.pillar      :255 ][ERROR   ][5768] Got a bad pillar from master, type str, expecting dict: 
2020-04-08 20:39:14,829 [salt.state       :322 ][ERROR   ][5768] {'Python 3.4.3 (64-bit)': {'old': '', 'new': '3.4.3150'}, 'python3_x64': {'install status': 'success'}}
```

Logs from master (although I do not think they are relevant):

```
2020-04-08 20:38:50,184 [salt.master      :1846][ERROR   ][9557] Error in function _pillar:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1839, in run_func
    ret = getattr(self, func)(load)
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1545, in _pillar
    self.fs_.update_opts()
  File "/usr/lib/python3/dist-packages/salt/fileserver/__init__.py", line 411, in update_opts
    for name, func in self.servers.items():
  File "/usr/lib/python3.8/_collections_abc.py", line 743, in __iter__
    for key in self._mapping:
  File "/usr/lib/python3/dist-packages/salt/utils/lazy.py", line 120, in __iter__
    self._load_all()
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1833, in _load_all
    self._load_module(name)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1600, in _load_module
    mod = spec.loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 462, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 962, in load_module
  File "<frozen importlib._bootstrap_external>", line 787, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1057, in get_code
  File "<frozen importlib._bootstrap_external>", line 975, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3/dist-packages/salt/fileserver/__pycache__/azur
efs.cpython-37.pyc'
```

### Steps to Reproduce Issue
```bash
sudo salt '*' state.apply python
```

### Versions Report

master

```
Salt Version:
           Salt: 3000

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10.1
        libgit2: 0.28.3
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.6.1
         pygit2: 1.0.3
         Python: 3.8.2 (default, Apr  1 2020, 15:52:55)
   python-gnupg: Not Installed
         PyYAML: 5.3.1
          PyZMQ: 18.1.1
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2

System Versions:
           dist: debian testing bullseye
         locale: utf-8
        machine: x86_64
        release: 4.4.0-17763-Microsoft
         system: Linux
        version: Debian GNU/Linux testing bullseye
```
Note: this is actually Windows Subsystem for Linux.

minion installed from `Salt-Minion-3000.1-Py3-AMD64-Setup.exe`

**Comment by twangboy** [comment]
Should be fixed by https://github.com/saltstack/salt-winrepo-ng/pull/1933
