### ISSUE TITLE
salt minion won't start on Windows: cffi.FFIError: multiple declarations of anonymous MPZ

### ISSUE THREAD

**Issue by oeuftete** [saltstack/salt#56597]
### Description of Issue

```text
PS C:\Users\vagrant> salt-minion-debug.bat
The salt-minion service is stopping.
The salt-minion service was stopped successfully.

[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Including configuration from 'c:\salt\conf\minion.d\_schedule.conf'
[DEBUG   ] Reading configuration from c:\salt\conf\minion.d\_schedule.conf
[DEBUG   ] Multiprocessing queue logging configured for the process running under PID: 2780 at log level 10
[DEBUG   ] Marking 'is_ip' as a jinja filter
[DEBUG   ] Marking 'is_ipv4' as a jinja filter
[DEBUG   ] Marking 'is_ipv6' as a jinja filter
[DEBUG   ] Marking 'ipv4' as a jinja filter
[DEBUG   ] Marking 'ipv6' as a jinja filter
[DEBUG   ] Marking 'ipaddr' as a jinja filter
[DEBUG   ] Marking 'ip_host' as a jinja filter
[DEBUG   ] Marking 'network_hosts' as a jinja filter
[DEBUG   ] Marking 'network_size' as a jinja filter
[DEBUG   ] Marking 'gen_mac' as a jinja filter
[DEBUG   ] Marking 'mac_str_to_bytes' as a jinja filter
[DEBUG   ] Marking 'dns_check' as a jinja filter
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-minion", line 6, in <module>
    __import__('pkg_resources').run_script('salt==3000', 'salt-minion')
  File "C:\salt\bin\lib\site-packages\pkg_resources\__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "C:\salt\bin\lib\site-packages\pkg_resources\__init__.py", line 1527, in run_script
    exec(code, namespace, namespace)
  File "c:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\EGG-INFO\scripts\salt-minion", line 26, in <module>
    salt_minion()
  File "C:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\scripts.py", line 205, in salt_minion
    minion.start()
  File "C:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\cli\daemons.py", line 323, in start
    super(Minion, self).start()
  File "C:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\utils\parsers.py", line 1073, in start
    self.prepare()
  File "C:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\cli\daemons.py", line 296, in prepare
    import salt.minion
  File "C:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\minion.py", line 64, in <module>
    import salt.crypt
  File "C:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\crypt.py", line 41, in <module>
    from Cryptodome.PublicKey import RSA
  File "C:\salt\bin\lib\site-packages\Cryptodome\PublicKey\RSA.py", line 42, in <module>
    from Cryptodome.Math.Numbers import Integer
  File "C:\salt\bin\lib\site-packages\Cryptodome\Math\Numbers.py", line 34, in <module>
    from Cryptodome.Math._IntegerGMP import IntegerGMP as Integer
  File "C:\salt\bin\lib\site-packages\Cryptodome\Math\_IntegerGMP.py", line 95, in <module>
    lib = load_lib("gmp", gmp_defs)
  File "C:\salt\bin\lib\site-packages\Cryptodome\Util\_raw_api.py", line 103, in load_lib
    ffi.cdef(cdecl)
  File "C:\salt\bin\lib\site-packages\cffi\api.py", line 112, in cdef
    self._cdef(csource, override=override, packed=packed, pack=pack)
  File "C:\salt\bin\lib\site-packages\cffi\api.py", line 126, in _cdef
    self._parser.parse(csource, override=override, **options)
  File "C:\salt\bin\lib\site-packages\cffi\cparser.py", line 347, in parse
    self._internal_parse(csource)
  File "C:\salt\bin\lib\site-packages\cffi\cparser.py", line 387, in _internal_parse
    decl.type, name=decl.name, partial_length_ok=True)
  File "C:\salt\bin\lib\site-packages\cffi\cparser.py", line 619, in _get_type_and_quals
    tp = self._get_struct_union_enum_type('struct', type, name)
  File "C:\salt\bin\lib\site-packages\cffi\cparser.py", line 751, in _get_struct_union_enum_type
    self._declare('anonymous %s' % tp.forcename, tp)
  File "C:\salt\bin\lib\site-packages\cffi\cparser.py", line 526, in _declare
    "try cdef(xx, override=True))" % (name,))
cffi.FFIError: multiple declarations of anonymous MPZ (for interactive usage, try cdef(xx, override=True))
```

### Setup

Put `gmp.dll` from this archive somewhere in the Windows `PATH`: [gmp.zip](https://github.com/saltstack/salt/files/4457558/gmp.zip)  This came from a third-party application installed on the problem system; it looks to me like maybe it's from an old distribution of curl maybe??

```
$ winedump -x -C gmp.dll | grep -i ssl
    00000130: 46 3a 5c 73 70 61 63 65-5c 4f 70 65 6e 53 53 4c  F:\space\OpenSSL
    00000140: 26 43 75 72 6c 5c 6f 70-65 6e 73 73 6c 31 30 31  &Curl\openssl101
      Filename:          F:\space\OpenSSL&Curl\openssl101p_curl7430\openssl-1.0.1p\out32dll\gmp.pdb
```

### Steps to Reproduce Issue

Install salt 3000.  Run `salt-minion-debug`.

### Versions Report

```
PS C:\Users\vagrant> salt-minion.bat --versions-report
Salt Version:
           Salt: 3000

Dependency Versions:
           cffi: 1.12.2
       cherrypy: 17.4.1
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.6
      gitpython: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: Not Installed
   pycryptodome: 3.8.1
         pygit2: Not Installed
         Python: 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.4
         PyYAML: 5.1.2
          PyZMQ: 18.0.1
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2012ServerR2
         system: Windows
        version: 2012ServerR2 6.3.9600 SP0 Multiprocessor Free
```

**Comment by oeuftete** [comment]
I don't think this is Salt's problem, really, but maybe there are some things that could make it a better user experience, like catching the `cffi.FFIError` and logging the suspected cause (an incompatible (?) `gmp` library from a third-party application in `PATH`).

Applying the suggestion from the traceback...

```
cffi.FFIError: multiple declarations of anonymous MPZ (for interactive usage, try cdef(xx, override=True))
```

to the call here:

```
  File "C:\salt\bin\lib\site-packages\Cryptodome\Util\_raw_api.py", line 103, in load_lib
    ffi.cdef(cdecl)
```

... also made the issue go away, but there may be very good reasons why it's not called like that in Cryptodome.

**Comment by oeuftete** [comment]
ZD-5188

**Comment by oeuftete** [comment]
The [pycryptodome 3.9.8 release](https://github.com/Legrandin/pycryptodome/blob/master/Changelog.rst#398-23-june-2020) provides [a fix](https://github.com/Legrandin/pycryptodome/commit/f499fd3756f9f0a215bf4131992cfd03fb8b0a10), so resolving this is hopefully a matter of bumping the requirements.

**Comment by cmcmarrow** [comment]
https://github.com/Legrandin/pycryptodome/commit/f499fd3756f9f0a215bf4131992cfd03fb8b0a10

**Comment by l3ra** [comment]
> I don't think this is Salt's problem, really, but maybe there are some things that could make it a better user experience, like catching the `cffi.FFIError` and logging the suspected cause (an incompatible (?) `gmp` library from a third-party application in `PATH`).
> 
> Applying the suggestion from the traceback...
> 
> ```
> cffi.FFIError: multiple declarations of anonymous MPZ (for interactive usage, try cdef(xx, override=True))
> ```
> 
> to the call here:
> 
> ```
>   File "C:\salt\bin\lib\site-packages\Cryptodome\Util\_raw_api.py", line 103, in load_lib
>     ffi.cdef(cdecl)
> ```
> 
> ... also made the issue go away, but there may be very good reasons why it's not called like that in Cryptodome.

@oeuftete I'm having a similar issue to yours but unsure as to how you fixed yours exactly. 

cffi.FFIError: multiple declarations of function MD5_init (for interactive usage, try cdef(xx, override=True))

I'm using a cryptodome module: "/usr/lib/python2.7/Cryptodome/Hash/MD5.py", line 47, in <module>

Should I be changing the MD5.py function at line 47?

from Crypto.Util._raw_api import (load_pycryptodome_raw_lib,
                                  VoidPointer, SmartPointer,
                                  create_string_buffer,
                                  get_raw_buffer, c_size_t,
                                  c_uint8_ptr)
