### ISSUE TITLE
[BUG] gpg.encrypt example in the docs requires recipient (or: symmetric encryption should be supported)

### ISSUE THREAD

**Issue by oeuftete** [saltstack/salt#56646]
**Description**

The [documented `gpg.encrypt` examples](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.gpg.html#salt.modules.gpg.encrypt) don't work.

```
salt '*' gpg.encrypt text='Hello there.  How are you?'
salt '*' gpg.encrypt filename='/path/to/important.file'
```

**Setup**

Create/import GPG key.

**Steps to Reproduce the behavior**

Run either example above.

```
[root@master1 salt]# salt-call gpg.encrypt text='Hello there.  How are you?'
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
ValueError: No recipients specified with asymmetric encryption
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    load_entry_point('salt==3000.1', 'console_scripts', 'salt-call')()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 445, in salt_call
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 119, in run
    ret = self.call()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 218, in call
    ret['return'] = self.minion.executors[fname](self.opts, data, func, args, kwargs)
  File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/gpg.py", line 1191, in encrypt
    result = gpg.encrypt(text, recipients, passphrase=gpg_passphrase)
  File "/usr/lib/python2.7/site-packages/gnupg.py", line 1506, in encrypt
    result = self.encrypt_file(data, recipients, **kwargs)
  File "/usr/lib/python2.7/site-packages/gnupg.py", line 1440, in encrypt_file
    raise ValueError('No recipients specified with asymmetric '
ValueError: No recipients specified with asymmetric encryption
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    load_entry_point('salt==3000.1', 'console_scripts', 'salt-call')()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 445, in salt_call
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 119, in run
    ret = self.call()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 218, in call
    ret['return'] = self.minion.executors[fname](self.opts, data, func, args, kwargs)
  File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/gpg.py", line 1191, in encrypt
    result = gpg.encrypt(text, recipients, passphrase=gpg_passphrase)
  File "/usr/lib/python2.7/site-packages/gnupg.py", line 1506, in encrypt
    result = self.encrypt_file(data, recipients, **kwargs)
  File "/usr/lib/python2.7/site-packages/gnupg.py", line 1440, in encrypt_file
    raise ValueError('No recipients specified with asymmetric '
ValueError: No recipients specified with asymmetric encryption
```

**Expected behavior**

The documented examples should work, or; working examples should be documented.

**Versions Report**

<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
# salt-call test.versions_report
local:
    Salt Version:
               Salt: 3000.1
     
    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: Not Installed
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
             Jinja2: 2.7.2
            libgit2: Not Installed
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.6.2
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.5 (default, Aug  7 2019, 00:51:29)
       python-gnupg: 0.4.3
             PyYAML: 3.11
              PyZMQ: 15.3.0
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.5.3
                ZMQ: 4.1.4
     
    System Versions:
               dist: centos 7.6.1810 Core
             locale: UTF-8
            machine: x86_64
            release: 5.3.0-46-generic
             system: Linux
            version: CentOS Linux 7.6.1810 Core
```
</details>

**Comment by sagetherage** [comment]
@oeuftete there seems to have been some confusion on labels - the release label is where it will be fixed not what version it was found. I will have triage review for the Core Open severity/priority and then come back to this ticket later this week. Thanks for the report!

**Comment by oeuftete** [comment]
> The documented examples should work

If this is the choice, then if `recipients` is none, we should just do symmetric encryption: https://docs.red-dove.com/python-gnupg/#encryption

> or; working examples should be documented.

If this is the choice, we should add `recipients` to the example and handle `recipients` not being set gracefully.

**Comment by sagetherage** [comment]
@saltstack/docs-working-group
