### ISSUE TITLE
[BUG] much of the gnupg module does not work on Windows

### ISSUE THREAD

**Issue by oeuftete** [saltstack/salt#56644]
**Description**

The [`gnupg` module](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.gpg.html) does not generally work on Windows.

**Setup**

(Please provide relevant configs and/or SLS files (be sure to remove sensitive info).

**Steps to Reproduce the behavior**

Drop a gpg public key in `c:\tmp', then...

* Try to import a key

```
[root@master1 salt]# salt win2012 gpg.import_key filename='c:\tmp\pubkey.gpg' user=salt
win2012:
    ERROR executing 'gpg.import_key': User SYSTEM does not exist
ERROR: Minions returned with non-zero exit code

[root@master1 salt]# salt win2012 gpg.import_key filename='c:\tmp\pubkey.gpg'
win2012:
    ERROR executing 'gpg.import_key': User SYSTEM does not exist
ERROR: Minions returned with non-zero exit code
```

* After manually importing the key, try to trust it:

```
[root@master1 salt]# salt win2012 gpg.trust_key keyid=A4E89A0D3328D483 trust_level=ultimately user=salt
win2012:
    ERROR: No mapping between account names and security IDs was done.
ERROR: Minions returned with non-zero exit code

[root@master1 salt]# salt win2012 gpg.trust_key keyid=A4E89A0D3328D483 trust_level=ultimately
win2012:
    ERROR executing 'gpg.trust_key': User SYSTEM does not exist
ERROR: Minions returned with non-zero exit code
```

**Expected behavior**

There is no documentation suggesting Windows is not supported, so these should work.

**Versions Report**

```
# salt win2012 test.versions_report
win2012:
    Salt Version:
               Salt: 3000.1
     
    Dependency Versions:
               cffi: 1.12.2
           cherrypy: 17.4.1
           dateutil: 2.8.0
          docker-py: Not Installed
              gitdb: 2.0.5
          gitpython: Not Installed
             Jinja2: 2.10.1
            libgit2: Not Installed
           M2Crypto: Not Installed
               Mako: 1.0.7
       msgpack-pure: Not Installed
     msgpack-python: 0.5.6
       mysql-python: Not Installed
          pycparser: 2.19
           pycrypto: Not Installed
       pycryptodome: 3.8.1
             pygit2: Not Installed
             Python: 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]
       python-gnupg: 0.4.4
             PyYAML: 5.1.2
              PyZMQ: 18.0.1
              smmap: 2.0.5
            timelib: 0.2.4
            Tornado: 4.5.3
                ZMQ: 4.3.1
     
    System Versions:
               dist:   
             locale: cp1252
            machine: AMD64
            release: 2012ServerR2
             system: Windows
            version: 2012ServerR2 6.3.9600 SP0 Multiprocessor Free
```

**Comment by oeuftete** [comment]
The `SYSTEM` errors I think ultimately go back to the `_restore_ownership` decorator:

https://github.com/saltstack/salt/blob/ee1ebeb92f1aeaaac860eba4d0027cf12016411b/salt/modules/gpg.py#L158-L159

```
Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt-3000.1-py3.5.egg\salt\minion.py", line 1676, in _thread_return
    return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
  File "c:\salt\bin\lib\site-packages\salt-3000.1-py3.5.egg\salt\executors\direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt-3000.1-py3.5.egg\salt\modules\gpg.py", line 333, in list_secret_keys
    for _key in _list_keys(user, gnupghome, secret=True):
  File "c:\salt\bin\lib\site-packages\salt-3000.1-py3.5.egg\salt\modules\gpg.py", line 196, in _list_keys
    gpg = _create_gpg(user, gnupghome)
  File "c:\salt\bin\lib\site-packages\salt-3000.1-py3.5.egg\salt\modules\gpg.py", line 182, in _create_gpg
    gnupghome = _get_user_gnupghome(user)
  File "c:\salt\bin\lib\site-packages\salt-3000.1-py3.5.egg\salt\modules\gpg.py", line 133, in _get_user_gnupghome
    gnupghome = os.path.join(_get_user_info(user)['home'], '.gnupg')
  File "c:\salt\bin\lib\site-packages\salt-3000.1-py3.5.egg\salt\modules\gpg.py", line 121, in _get_user_info
    raise SaltInvocationError('User {0} does not exist'.format(user))
salt.exceptions.SaltInvocationError: User SYSTEM does not exist
```

**Comment by oeuftete** [comment]
The "No mapping between account names and security IDs was done" error goes back to an assumption of a `root` user:

https://github.com/saltstack/salt/blob/5c450f3bce57ed9798c7c5ff06ffa391343c5b82/salt/modules/gpg.py#L925-L932

```text
Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt-3000.1-py3.5.egg\salt\minion.py", line 1676, in _thread_return
    return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
  File "c:\salt\bin\lib\site-packages\salt-3000.1-py3.5.egg\salt\executors\direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt-3000.1-py3.5.egg\salt\modules\gpg.py", line 932, in trust_key
    python_shell=False)
  File "c:\salt\bin\lib\site-packages\salt-3000.1-py3.5.egg\salt\modules\cmdmod.py", line 2081, in run_all
    **kwargs)
  File "c:\salt\bin\lib\site-packages\salt-3000.1-py3.5.egg\salt\modules\cmdmod.py", line 407, in _run
    return win_runas(cmd, runas, password, cwd)
  File "c:\salt\bin\lib\site-packages\salt-3000.1-py3.5.egg\salt\utils\win_runas.py", line 76, in runas
    raise CommandExecutionError(message)
salt.exceptions.CommandExecutionError: No mapping between account names and security IDs was done.
```
