### ISSUE TITLE
Canot created windows schedule task

### ISSUE THREAD

**Issue by H20-17** [saltstack/salt#56716]
**Description**
Either, because I don't know what I am doing, or because of a bug, I am unable to create a Windows (TM) scheduled task with an event trigger

**Setup**
From the Windows (TM) Task Scheduler I exported a task definition as XML. The XML thereby obtained is as follows:

```
<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Date>2020-04-19T14:10:42.75551</Date>
    <Author>AD\waltonm</Author>
    <Description>Restart the salt minion after sleep</Description>
    <URI>\Event Viewer Tasks\salt-minion-restart</URI>
  </RegistrationInfo>
  <Triggers>
    <EventTrigger>
      <Enabled>true</Enabled>
      <Subscription>&lt;QueryList&gt;&lt;Query Id="0" Path="System"&gt;&lt;Select Path="System"&gt;*[System[Provider[@Name='Microsoft-Windows-Power-Troubleshooter'] and EventID=1]]&lt;/Select&gt;&lt;/Query&gt;&lt;/QueryList&gt;</Subscription>
    </EventTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <UserId>S-1-5-18</UserId>
      <RunLevel>LeastPrivilege</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>true</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>true</StopIfGoingOnBatteries>
    <AllowHardTerminate>true</AllowHardTerminate>
    <StartWhenAvailable>false</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <IdleSettings>
      <StopOnIdleEnd>true</StopOnIdleEnd>
      <RestartOnIdle>false</RestartOnIdle>
    </IdleSettings>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>false</Hidden>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
    <WakeToRun>false</WakeToRun>
    <ExecutionTimeLimit>PT72H</ExecutionTimeLimit>
    <Priority>7</Priority>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>powershell.exe</Command>
      <Arguments>restart-service salt-minion</Arguments>
      <WorkingDirectory>C:\Windows\System32\WindowsPowerShell\v1.0</WorkingDirectory>
    </Exec>
  </Actions>
</Task>
```

From the above XML I extracted the following section:

```
 <Subscription>&lt;QueryList&gt;&lt;Query Id="0" Path="System"&gt;&lt;Select Path="System"&gt;*[System[Provider[@Name='Microsoft-Windows-Power-Troubleshooter'] and EventID=1]]&lt;/Select&gt;&lt;/Query&gt;&lt;/QueryList&gt;</Subscription>
```
I also created a task as follows:

```
salt my_minion task.create_task salt-minion-restart action_type=Execute cmd='powershell restart-service salt-minion'
```

**Steps to Reproduce the behavior**
I tried to add an event trigger. First I tried this:

```
ask.add_trigger salt-minion-restart trigger_type=Event subscription="<subscription>&lt;QueryList&gt;&lt;Query Id=\"0\" Path=\"System\"&gt;&lt;Select Path=\"System\"&gt;*[System[Provider[@Name='Microsoft-Windows-Power-Troubleshooter'] and EventID=1]]&lt;/Select&gt;&lt;/Query&gt;&lt;/QueryList&gt;</subscription>" user_name=System
```
It didn't work. I just got the following error message which meant nothing at all to me.
```
    Failed to modify task: Unknown Failure: (-2147352567, 'Exception occurred.', (0, None, '(10,279):Subscription:&lt;QueryList&gt;&lt;Query Id="0" Path="System"&gt;&lt;Select Path="System"&gt;*[System[Provider[@Name=\'Microsoft-Windows-Power-Troubleshooter\'] and EventID=1]]&lt;/Select&gt;&lt;/Query&gt;&lt;/QueryList&gt;', None, 0, -2147009896), None)
```

Then I tried removing the _<subscription>_ xml tags because I'm not sure if they're supposed to be included or not. The command then looked like this:

```
  /usr/local/bin/salt -v -t 500 'O18112810' task.add_trigger salt-minion-restart trigger_type=Event subscription="&lt;QueryList&gt;&lt;Query Id=\"0\" Path=\"System\"&gt;&lt;Select Path=\"System\"&gt;*[System[Provider[@Name='Microsoft-Windows-Power-Troubleshooter'] and EventID=1]]&lt;/Select&gt;&lt;/Query&gt;&lt;/QueryList&gt;" user_name=System
```
I got an error message equivalent to the previous one.

**Expected behavior**
Ideally the command would return true and the event trigger would be added.

**Versions Report**
<details><summary>salt --versions-report</summary>

```
alt Version:
           Salt: 3000.1
 
Dependency Versions:
           cffi: 1.12.3
       cherrypy: Not Installed
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 3.0.2
         Jinja2: 2.10.1
        libgit2: 0.28.2
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.28.2
         Python: 3.7.6 (default, Jan 30 2020, 09:44:41)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 18.0.2
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: fedora 31 Thirty One
         locale: UTF-8
        machine: x86_64
        release: 5.5.13-200.fc31.x86_64
         system: Linux
        version: Fedora 31 Thirty One

```
</details>

Note that the minion is version 3000

**Additional comments**

I tried my hand with using _task.create_task_from_xml_ using the original xml file as the source. I had no luck with that either.

**Comment by alexey-zhukovin** [comment]
@H20-17 
Thank you for the issue: 

Could you try it with unescaped `subscription` string: 
```
<QueryList><Query Id="0" Path="System"><Select Path="System">*[System[Provider[@Name='Microsoft-Windows-Power-Troubleshooter'] and EventID=1]]</Select></Query></QueryList>
```

**Comment by H20-17** [comment]
Hi @alexey-zhukovin I'm not sure how to use that string in the command line without quoting something and escaping some other things. Could you provide me with an example of what you want me to do? Thanks.

**Comment by H20-17** [comment]
@alexey-zhukovin  What I have done so far is this

First of all I did this:
```
subscription="<QueryList><Query Id=\"0\" Path=\"System\"><Select Path=\"System\">*[System[Provider[@Name='Microsoft-Windows-Power-Troubleshooter'] and EventID=1]]</Select></Query></QueryList>"
```
Then I tried the execution module as follows:

```
/usr/local/bin/salt -v -t 500 my_win_minion task.add_trigger salt-minion-restart trigger_type=Event subscription=$subscription user_name=System
```

This time I got almost the same error message, but there's a stack trace this time

```
my_win_minion:
    The minion function caused an exception: Traceback (most recent call last):
      File "c:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\minion.py", line 1675, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "c:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\executors\direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "c:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\modules\win_task.py", line 2204, in add_trigger
        if name in list_tasks(location):
      File "c:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\modules\win_task.py", line 352, in list_tasks
        task_folder = task_service.GetFolder(location)
      File "<COMObject Schedule.Service>", line 2, in GetFolder
    pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147024894), None)
```

**Comment by dwoz** [comment]
Fix merged and shipped in a supported release. Closing per bulk triage. Reopen if this reproduces on a currently supported release (3006.x, 3007.x, 3008.x, master).
