### ISSUE TITLE
salt-cloud fails during provisioning GCE instances with pre-created fixed IPs

### ISSUE THREAD

**Issue by alrf** [saltstack/salt#56824]
**Description**
salt-cloud 2019.2.3, gce provider.
salt-cloud fails during provisioning GCE instances with pre-created fixed IPs.

**Setup**
Create manually the fixed IPs:
```
salt-cloud -f create_address gce name=vpn1 region=europe-west4
salt-cloud -f create_address gce name=vpn2 region=europe-west4
salt-cloud -f create_address gce name=vpn3 region=europe-west4
```
IPs will be created, everything fine here.

Configs:
```
/etc/salt/cloud.profiles.d/gce.conf:
vpn-profile:
  image: debian-9
  ssh_username: gceuser
  ssh_keyfile: /root/.ssh/id_rsa_gce
  size: f1-micro
  network: default
  subnetwork: default
  tags: '["allow-all"]'
  metadata: '{"sshKeys": "MYKEY"}'
  use_persistent_disk: True
  delete_boot_pd: True
  ssh_interface: public_ips
  ip_forwarding: False
  deploy: True
  make_master: False
  provider: MYPROVIDER
```

```
/etc/salt/cloud.maps.d/vpn.conf:
vpn-profile:
  - vpn1:
      location: europe-west4-a
      external_ip: "vpn1"
  - vpn2:
      location: europe-west4-b
      external_ip: "vpn2"
  - vpn3:
      location: europe-west4-c
      external_ip: "vpn3"
```

**Steps to Reproduce the behavior**
Run setup:
```
/etc/salt/cloud.providers.d# salt-cloud -m /etc/salt/cloud.maps.d/vpn.conf -P
The following virtual machines are set to be created:
  vpn2
  vpn1
  vpn3

Proceed? [N/y] y
... proceeding
Error: There was a query error: Exception caught
Caught Exception, terminating workers
TRACE: Cannot serialize socket object
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/cloud/__init__.py", line 67, in _call
    ret = func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/cloud/__init__.py", line 2294, in create_multiprocessing
    local_master=parallel_data['local_master']
  File "/usr/lib/python3/dist-packages/salt/cloud/__init__.py", line 1253, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python3/dist-packages/salt/cloud/clouds/gce.py", line 2591, in create
    ret = __utils__['cloud.bootstrap'](vm_, __opts__)
  File "/usr/lib/python3/dist-packages/salt/utils/cloud.py", line 614, in bootstrap
    event_kwargs = copy.deepcopy(deploy_kwargs)
  File "/usr/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python3.5/copy.py", line 297, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python3.5/copy.py", line 297, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python3.5/copy.py", line 297, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python3.5/copy.py", line 297, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.5/copy.py", line 174, in deepcopy
    rv = reductor(4)
  File "/usr/lib/python3.5/socket.py", line 175, in __getstate__
    raise TypeError("Cannot serialize socket object")
```

GCE instances will be created, IPs assigned to instances, but salt-minion will not be installed and any instance configuration will be skipped.

**Expected behavior**
GCE instances should be created, IPs assigned to instances, salt-minion and configuration are applied.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 2019.2.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (default, Sep 27 2018, 17:25:39)
   python-gnupg: 0.3.9
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.12 
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-12-amd64
         system: Linux
        version: debian 9.12 
```
</details>

**Comment by twangboy** [comment]
Are you defining location in the provider file?

**Comment by alrf** [comment]
There is no location parameter in the provider file: https://docs.saltstack.com/en/latest/topics/cloud/gce.html#provider-configuration

I'm defining location in the map file (`/etc/salt/cloud.maps.d/vpn.conf`), content is above.
Also, I tried to define location in `/etc/salt/cloud.profiles.d/gce.conf` and got the same error.

**Comment by sagetherage** [comment]
The Core Team will not be able to get this in this release cycle and moving this back into planning.

**Comment by dwoz** [comment]
Fix merged and shipped in a supported release. Closing per bulk triage. Reopen if this reproduces on a currently supported release (3006.x, 3007.x, 3008.x, master).
