### ISSUE TITLE
[BUG] `salt-cloud` Failed to get the output of 'gce.avail_images()'

### ISSUE THREAD

**Issue by yencarnacion** [saltstack/salt#56862]
**Description**
``` salt-cloud -l debug --list-images my-google``` returns:

```
[ERROR   ] Failed to get the output of 'gce.avail_images()': {u'reason': u'notFound', u'message': u"The resource 'projects/c' was not found. A missing project error may be an authentication issue. Please  ensure your auth credentials match your project. ", u'domain': u'global'}
```

**Setup**
```
python -c "import libcloud ; print libcloud.__version__"
2.2.1
```
`/etc/salt/cloud.providers.d/google.conf`
```
my-google:
  project: 'my-project'
  service_account_email_address: ''
  service_account_private_key: ''
  minion:
    master: tmp-salt-master-03.example.com
  driver: gce
```

**Steps to Reproduce the behavior**

On a Ubuntu 18.04 minimal with full API access on us-east4-a

```
sudo apt-get update
sudo apt-get install tmux git emacs-nox vim -y

curl -o bootstrap-salt.sh -L https://bootstrap.saltstack.com
tmux
sudo sh bootstrap-salt.sh git develop

sudo su

mkdir -p /etc/salt/cloud.providers.d

cat <<EOT >>  /etc/salt/cloud.providers.d/google.conf
my-google:
  project: 'my-project'
  service_account_email_address: ''
  service_account_private_key: ''
  minion:
    master: tmp-salt-master-03.example.com
  driver: gce
EOT

sudo apt-get install python-libcloud -y
```

`salt-cloud -l debug --list-images my-google`
```
WARNING: CONFIG '/etc/salt/cloud' file does not exist. Falling back to default '/etc/salt/cloud'.
[DEBUG   ] Missing configuration file: /etc/salt/cloud
[DEBUG   ] Missing configuration file: /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: tmp-salt-master-02.c.covidpr-271900.internal
[DEBUG   ] Missing configuration file: /etc/salt/cloud.providers
[DEBUG   ] Including configuration from '/etc/salt/cloud.providers.d/google.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers.d/google.conf
[DEBUG   ] Missing configuration file: /etc/salt/cloud.profiles
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] salt-cloud starting
[DEBUG   ] Could not LazyLoad parallels.avail_sizes: 'parallels' __virtual__ returned False
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Starting new HTTP connection (1): metadata
[DEBUG   ] http://metadata:80 "GET /computeMetadata/v1/ HTTP/1.1" 200 28
[DEBUG   ] Starting new HTTPS connection (1): www.googleapis.com
[DEBUG   ] https://www.googleapis.com:443 "GET /compute/v1/projects/covidpr-271900/zones HTTP/1.1" 200 None
[DEBUG   ] https://www.googleapis.com:443 "GET /compute/v1/projects/covidpr-271900/regions HTTP/1.1" 200 None
[DEBUG   ] https://www.googleapis.com:443 "GET /compute/v1/projects/c/global/images HTTP/1.1" 404 None
[ERROR   ] Failed to get the output of 'gce.avail_images()': {u'reason': u'notFound', u'message': u"The resource
 'projects/c' was not found. A missing project error may be an authentication issue. Please  ensure your auth cr
edentials match your project. ", u'domain': u'global'}
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 866, in image_list
    data[alias][driver] = self.clouds[fun]()
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/gce.py", line 363, in avail_images
    all_images.extend(conn.list_images(project))
  File "/usr/lib/python2.7/dist-packages/libcloud/compute/drivers/gce.py", line 2217, in list_images
    ex_include_deprecated=dep)
  File "/usr/lib/python2.7/dist-packages/libcloud/compute/drivers/gce.py", line 2269, in ex_list_project_images
    method='GET').object
  File "/usr/lib/python2.7/dist-packages/libcloud/compute/drivers/gce.py", line 121, in request
    response = super(GCEConnection, self).request(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/libcloud/common/google.py", line 808, in request
    *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/libcloud/common/base.py", line 637, in request
    response = responseCls(**kwargs)
  File "/usr/lib/python2.7/dist-packages/libcloud/common/base.py", line 159, in __init__
    self.object = self.parse_body()
  File "/usr/lib/python2.7/dist-packages/libcloud/common/google.py", line 280, in parse_body
    raise ResourceNotFoundError(message, self.status, code)
ResourceNotFoundError: {u'reason': u'notFound', u'message': u"The resource 'projects/c' was not found. A missing
 project error may be an authentication issue. Please  ensure your auth credentials match your project. ", u'dom
ain': u'global'}
[DEBUG   ] LazyLoaded nested.output
```

**Expected behavior**
A List of available images instead of an error

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
alt Version:
           Salt: 2019.8.0-69-g637fe0b
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: 0.27.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.17 (default, Apr 15 2020, 17:20:14)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 5.0.0-1034-gcp
         system: Linux
        version: Ubuntu 18.04 bionic
 
```
</details>

**Comment by twangboy** [comment]
Are these two lines really empty?
```
  service_account_email_address: ''
  service_account_private_key: ''
```
I'm assuming you removed sensitive data, but just to be sure...

**Comment by yencarnacion** [comment]
@twangboy 

I left `service_account_email_address` and `service_account_private_key` empty on purpose.  I did this because on https://docs.saltstack.com/en/latest/topics/cloud/gce.html it says:

```
Empty strings as values for service_account_private_key and service_account_email_address 
can be used on GCE instances. This will result in the service account assigned to the GCE 
instance being used.
```

The GCE instance on which the commands are executed have full API access.

Thank you for asking for the clarification.

**Comment by s0undt3ch** [comment]
Can you please try `apache-libcloud>=2.5.0`? I recently encountered an issue with our own GCE cloud tests which would fail unless we had at least that version of libcloud.
