### ISSUE TITLE
ps.top fails on newer psutil in Python 2 and 3, and 100% of time on Python 3

### ISSUE THREAD

**Issue by terminalmage** [saltstack/salt#56942]
Traceback on newer psutil:

```
Traceback (most recent call last):
  File "/testing/scripts/salt-call", line 10, in <module>
    salt_call()
  File "/testing/salt/scripts.py", line 472, in salt_call
    client.run()
  File "/testing/salt/cli/call.py", line 58, in run
    caller.run()
  File "/testing/salt/cli/caller.py", line 121, in run
    ret = self.call()
  File "/testing/salt/cli/caller.py", line 229, in call
    self.opts, data, func, args, kwargs
  File "/testing/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/testing/salt/modules/ps.py", line 152, in top
    user, system, _, _ = process.cpu_times()
ValueError: too many values to unpack (expected 4)
```

Error on Python 3 (with older psutil):

```
# python3 /usr/bin/salt-call --local ps.top

Passed invalid arguments: '<' not supported between instances of 'Process' and 'Process'.

Usage:

    Return a list of top CPU consuming processes during the interval.
    num_processes = return the top N CPU consuming processes
    interval = the number of seconds to sample CPU usage over

    CLI Examples:

    .. code-block:: bash

        salt '*' ps.top

        salt '*' ps.top 5 10
```

**Comment by terminalmage** [comment]
https://github.com/saltstack/salt/pull/56943 opened to fix this
