### ISSUE TITLE
[BUG] RuntimeError: maximum recursion with pkg.installed and prereq

### ISSUE THREAD

**Issue by rossengeorgiev** [saltstack/salt#56957]
**Description**
Getting maximum recursion error when trying to use `pkg.installed` with prereq

Affected versions: `2019` and `3000`

**Steps to Reproduce the behavior**
```yaml
root@host ~ # cat /srv/salt/testcase.sls

echo 1:
  cmd.run:
    - prereq:
      - pkg: name2

name2:
  pkg.installed:
    - name: nc
    - require:
      - name: non-existant

echo 2:
  cmd.run:
    - require:
       - pkg: name2
```
```python	   
root@host ~ # salt-call --local state.apply testcase
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
RuntimeError: maximum recursion depth exceeded in cmp
Traceback (most recent call last):
  File "/bin/salt-call", line 11, in <module>
    load_entry_point('salt==3000.1', 'console_scripts', 'salt-call')()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 445, in salt_call
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 119, in run
    ret = self.call()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 218, in call
    ret['return'] = self.minion.executors[fname](self.opts, data, func, args, kwargs)
  File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 782, in apply_
    return sls(mods, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 1351, in sls
    ret = st_.state.call_high(high_, orchestration_jid)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2909, in call_high
    ret = self.call_chunks(chunks)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2271, in call_chunks
    running = self.call_chunk(low, running, chunks)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2708, in call_chunk
    running = self.call_chunk(low, running, chunks)	   
<------snip------->
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2708, in call_chunk
    running = self.call_chunk(low, running, chunks)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2697, in call_chunk
    running = self.call_chunk(chunk, running, chunks)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2588, in call_chunk
    low = self._mod_aggregate(low, running, chunks)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 827, in _mod_aggregate
    agg_opt = self.functions['config.option']('state_aggregate')
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1248, in __getitem__
    func = super(LazyLoader, self).__getitem__(item)
  File "/usr/lib/python2.7/site-packages/salt/utils/lazy.py", line 101, in __getitem__
    if key not in self._dict and not self.loaded:
RuntimeError: maximum recursion depth exceeded in cmp
Traceback (most recent call last):
  File "/bin/salt-call", line 11, in <module>
    load_entry_point('salt==3000.1', 'console_scripts', 'salt-call')()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 445, in salt_call
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 119, in run
    ret = self.call()
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 218, in call
    ret['return'] = self.minion.executors[fname](self.opts, data, func, args, kwargs)
  File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 782, in apply_
    return sls(mods, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 1351, in sls
    ret = st_.state.call_high(high_, orchestration_jid)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2909, in call_high
    ret = self.call_chunks(chunks)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2271, in call_chunks
    running = self.call_chunk(low, running, chunks)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2708, in call_chunk
    running = self.call_chunk(low, running, chunks)
<------snip------->
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2708, in call_chunk
    running = self.call_chunk(low, running, chunks)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2697, in call_chunk
    running = self.call_chunk(chunk, running, chunks)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2588, in call_chunk
    low = self._mod_aggregate(low, running, chunks)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 827, in _mod_aggregate
    agg_opt = self.functions['config.option']('state_aggregate')
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1248, in __getitem__
    func = super(LazyLoader, self).__getitem__(item)
  File "/usr/lib/python2.7/site-packages/salt/utils/lazy.py", line 101, in __getitem__
    if key not in self._dict and not self.loaded:
RuntimeError: maximum recursion depth exceeded in cmp
root@host ~ #
```

If we remove `echo 2`, then we get highstate output where the result of `name2` is missing.

```yaml
root@host ~ # cat /srv/salt/testcase2.sls
echo 1:
  cmd.run:
    - prereq:
      - pkg: name2

name2:
  pkg.installed:
    - name: nc
    - require:
      - name: non-existant
```
```python
root@host ~ # salt-call --local state.apply testcase2
local:
----------
          ID: echo 1
    Function: cmd.run
      Result: False
     Comment: One or more requisite failed: testcase2.name2
     Started: 23:44:44.400684
    Duration: 0.025 ms
     Changes:

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   0.025 ms
```

**Expected behavior**
To get an error about missing state called `non-existant`

**Versions Report**

<details><summary>salt --versions-report</summary>

```yaml
Salt Version:
           Salt: 3000.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Oct 30 2018, 23:45:53)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.1.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core

```
</details>

**Comment by waynew** [comment]
@rossengeorgiev thanks for the report! This is definitely a problem.

**Comment by rossengeorgiev** [comment]
@waynew yes, I think the issue exist even when `name2` requires an existing id.

**Comment by rossengeorgiev** [comment]
@garethgreenaway hey, sorry to ping you, but is that something that can be looked at for upcoming release. It really hurts not being able to use `prereq`. I think this issue goes as far back as v2017.

**Comment by garethgreenaway** [comment]
@rossengeorgiev No worries.  This might be fixed with some recent changes to the requisites that we're looking at including for Sodium that @cmcmarrow worked on.  @cmcmarrow can you take a look and see if your recent PR fixes this situation?  Thanks!
