### ISSUE TITLE
[BUG] Windows minion returning stack trace when state.apply is called

### ISSUE THREAD

**Issue by H20-17** [saltstack/salt#56997]
**Description**
A minion is returning a stack trace instead of running returning the usual state run output dictionary after running _state.apply_

At present the output looks like this:

```
 The minion function caused an exception: Traceback (most recent call last):
      File "c:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\minion.py", line 1675, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "c:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\executors\direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "c:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\modules\state.py", line 783, in apply_
        return highstate(**kwargs)
      File "c:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\modules\state.py", line 1063, in highstate
        initial_pillar=_get_initial_pillar(opts))
      File "c:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\state.py", line 4203, in __init__
        initial_pillar=initial_pillar)
      File "c:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\state.py", line 740, in __init__
        self.opts['pillar'] = self._gather_pillar()
      File "c:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\state.py", line 802, in _gather_pillar
        return pillar.compile_pillar()
      File "c:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\pillar\__init__.py", line 249, in compile_pillar
        dictkey='pillar',
      File "c:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\utils\asynchronous.py", line 67, in wrap
        ret = self._block_future(ret)
      File "c:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\utils\asynchronous.py", line 75, in _block_future
        return future.result()
      File "c:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\ext\tornado\concurrent.py", line 239, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
      File "c:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\ext\tornado\gen.py", line 1064, in run
        yielded = self.gen.throw(*exc_info)
      File "c:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\transport\zeromq.py", line 294, in crypted_transfer_decode_dictentry
        tries=tries,
      File "c:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\ext\tornado\gen.py", line 1056, in run
        value = future.result()
      File "c:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\ext\tornado\concurrent.py", line 239, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
    salt.exceptions.SaltReqTimeoutError: Message timed out

```

**Steps to Reproduce the behavior**

I don't know how to reproduce this. It could be some kind of unusual networking problem due to the minion being in an unusual location. I am willing to accept that this may be the case. I may try to exclude that possibility.

**Expected behavior**

I would like to see the usual return dictionary.

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3000.1
 
Dependency Versions:
           cffi: 1.12.3
       cherrypy: Not Installed
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 3.0.2
         Jinja2: 2.10.1
        libgit2: 0.28.2
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.28.2
         Python: 3.7.7 (default, Mar 13 2020, 10:23:39)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 18.0.2
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: fedora 31 Thirty One
         locale: UTF-8
        machine: x86_64
        release: 5.6.6-200.fc31.x86_64
         system: Linux
        version: Fedora 31 Thirty One
```
</details>

**Additional context**
The mininion is running v. 3000 x64 (py3)

**Comment by H20-17** [comment]
It worked after restarting WireGuard on the minion. I don't know what would be to blame.

**Comment by H20-17** [comment]
I believe it's a WireGuard issue. I'm having the identical issue with another minion. Wireguard doesn't behave perfectly in every situation. It's impossible to know why. Sorry for this bug report.
