### ISSUE TITLE
salt-api calls fail due to wsgiref string assertion

### ISSUE THREAD

**Issue by codecritic** [saltstack/salt#57050]
**Description**
salt-api calls fail on salt-master 2018.3.5 (also observed on 2019.2.4 and 3000.2) packages for centos6 (python 2.7).  With these versions, unicode_literals is being imported, which results in unicode status codes being passed to wsgiref's start_response().  This fails string assertion and a 500 is returned to the caller.

**Setup**
Install versions noted above of salt, salt-master and salt-api on centos 6 and start the salt-api service (in the foreground if possible).

**Steps to Reproduce the behavior**

- Curl the service after startup (e.g., http://127.0.0.1:8011)
- An internal error 500 is return along with the following stream (if the service has been foregrounded):

Starting salt-api daemon: Traceback (most recent call last):
  File “/usr/lib64/python2.7/wsgiref/handlers.py”, line 85, in run
    self.result = application(self.environ, self.start_response)
  File “/usr/lib/python2.7/site-packages/salt/netapi/rest_wsgi.py”, line 293, in application
    ‘Content-Type’: ‘application/json’,
  File “/usr/lib64/python2.7/wsgiref/handlers.py”, line 173, in start_response
    assert type(status) is StringType,“Status must be a string”
AssertionError: Status must be a string

Curl the service after startup.  

**Expected behavior**
200 Response with json.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 2018.3.5

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 1.0.0
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Jan 31 2018, 02:12:13)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.10 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-754.28.1.el6.x86_64
         system: Linux
        version: CentOS 6.10 Final
```
</details>

**Comment by waynew** [comment]
Thanks for the report, @codecritic!

While this *does* appear to be valid, if it's only happening on Python2.7 then this will probably get a  wontfix, since we're dropping Python 2.7 support in Sodium.

Can you check to see if this works under Python3?

**Comment by codecritic** [comment]
> Thanks for the report, @codecritic!
> 
> While this _does_ appear to be valid, if it's only happening on Python2.7 then this will probably get a wontfix, since we're dropping Python 2.7 support in Sodium.
> 
> Can you check to see if this works under Python3?

Confirmed with 3.6.8/cent7, although the error is slightly different now with python3's use of Bytes().  I would almost say that support for rest_wsgi should be dropped since cherrypy and tornado are probably better choices.  Anyways, here is an example error:

`May 07 23:57:13 salt-master salt-api[6685]: Exception happened during processing of request from ('127.0.0.1', 35286)
May 07 23:57:13 salt-master salt-api[6685]: Traceback (most recent call last):
May 07 23:57:13 salt-master salt-api[6685]: File "/usr/lib64/python3.6/wsgiref/handlers.py", line 138, in run
May 07 23:57:13 salt-master salt-api[6685]: self.finish_response()
May 07 23:57:13 salt-master salt-api[6685]: File "/usr/lib64/python3.6/wsgiref/handlers.py", line 180, in finish_response
May 07 23:57:13 salt-master salt-api[6685]: self.write(data)
May 07 23:57:13 salt-master salt-api[6685]: File "/usr/lib64/python3.6/wsgiref/handlers.py", line 266, in write
May 07 23:57:13 salt-master salt-api[6685]: "write() argument must be a bytes instance"
May 07 23:57:13 salt-master salt-api[6685]: AssertionError: write() argument must be a bytes instance
May 07 23:57:13 salt-master salt-api[6685]: During handling of the above exception, another exception occurred:
May 07 23:57:13 salt-master salt-api[6685]: Traceback (most recent call last):
May 07 23:57:13 salt-master salt-api[6685]: File "/usr/lib64/python3.6/wsgiref/handlers.py", line 141, in run
May 07 23:57:13 salt-master salt-api[6685]: self.handle_error()`

And here is the salt-master -V output:

`Salt Version:
           Salt: 3000.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: 5.6.0
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.1
        libgit2: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Apr  2 2020, 13:34:55)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.3.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.8.2003 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1127.el7.x86_64
         system: Linux
        version: CentOS Linux 7.8.2003 Core`

**Comment by dwoz** [comment]
Fix merged and shipped in a supported release. Closing per bulk triage. Reopen if this reproduces on a currently supported release (3006.x, 3007.x, 3008.x, master).
