### ISSUE TITLE
[BUG] Pillar-scheduled jobs do not have properly populated __salt__ and __util__ dictionaries

### ISSUE THREAD

**Issue by H20-17** [saltstack/salt#57115]
**Description**
I created an ext

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info).

**Steps to Reproduce the behavior**

```
2020-05-06 15:30:05,796 [salt.loader      :1897][ERROR   ][13208] Exception raised when processing __virtual__ function for salt.loaded.int.module.chroot. Module will not be loaded: 'path.which'
Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\loader.py", line 1883, in _process_virtual
    virtual = getattr(mod, virtual_func)()
  File "c:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\modules\chroot.py", line 37, in __virtual__
    if __utils__['path.which']('chroot') is not None:
KeyError: 'path.which'
2020-05-06 15:30:05,798 [salt.loader      :1913][WARNING ][13208] salt.loaded.int.module.chroot.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'chroot', please fix this.
2020-05-06 15:30:09,625 [salt.loader      :1897][ERROR   ][13208] Exception raised when processing __virtual__ function for salt.loaded.int.module.rh_service. Module will not be loaded: 'systemd.booted'
Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\loader.py", line 1883, in _process_virtual
    virtual = getattr(mod, virtual_func)()
  File "c:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\modules\rh_service.py", line 54, in __virtual__
    if __utils__['systemd.booted'](__context__):
KeyError: 'systemd.booted'
2020-05-06 15:30:09,626 [salt.loader      :1913][WARNING ][13208] salt.loaded.int.module.rh_service.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'rh_service', please fix this.
2020-05-06 15:30:20,838 [salt.loader      :1897][ERROR   ][13208] Exception raised when processing __virtual__ function for salt.loaded.int.module.win_snmp. Module will not be loaded: 'reg.key_exists'
Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\loader.py", line 1883, in _process_virtual
    virtual = getattr(mod, virtual_func)()
  File "c:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\modules\win_snmp.py", line 51, in __virtual__
    if not __salt__['reg.key_exists'](_HKEY, _SNMP_KEY):
  File "c:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\loader.py", line 1248, in __getitem__
    func = super(LazyLoader, self).__getitem__(item)
  File "c:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\utils\lazy.py", line 105, in __getitem__
    return self._dict[key]
KeyError: 'reg.key_exists'
2020-05-06 15:30:20,839 [salt.loader      :1913][WARNING ][13208] salt.loaded.int.module.win_snmp.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'win_snmp', please fix this.
2020-05-06 15:30:20,868 [salt.loader      :1897][ERROR   ][13208] Exception raised when processing __virtual__ function for salt.loaded.int.module.win_timezone. Module will not be loaded: 'platform.is_windows'
Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\loader.py", line 1883, in _process_virtual
    virtual = getattr(mod, virtual_func)()
  File "c:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\modules\win_timezone.py", line 192, in __virtual__
    if not __utils__['platform.is_windows']():
KeyError: 'platform.is_windows'
2020-05-06 15:30:20,869 [salt.loader      :1913][WARNING ][13208] salt.loaded.int.module.win_timezone.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'win_timezone', please fix this.
2020-05-06 15:30:21,026 [salt.utils.schedule:801 ][ERROR   ][13208] Unhandled exception running pillar_test.run
Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\utils\schedule.py", line 769, in handle_func
    ret['return'] = self.functions[func](*args, **kwargs)
  File "c:\salt\var\cache\salt\minion\extmods\modules\pillar_test.py", line 10, in run
    __salt__['reg.set_value']("HKLM",'SOFTWARE\\Salt\\test_key','test_property',vtype="REG_SZ",vdata='test_data_value')
  File "c:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\loader.py", line 1248, in __getitem__
    func = super(LazyLoader, self).__getitem__(item)
  File "c:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\utils\lazy.py", line 108, in __getitem__
    raise KeyError(key)
KeyError: 'reg.set_value'
```

**Expected behavior**

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
PASTE HERE
```
</details>

**Additional context**

**Comment by waynew** [comment]
@H20-17 thanks for the report! I tried this with a linux minion, obviously doing a different function, but everything seems to have worked just fine.

**Comment by xeacott** [comment]
So my setup is a master on 3000.2 on ubuntu and my minion is running natively on my machine on version 3000.2 and im not seeing these same errors, but it could be my setup.

What happens if you run...
`salt windows_minion pillar.items` and 
`salt windows_minion 'reg.set_value' ("HKLM",'SOFTWARE\\Salt\\test_key','test_property',vtype="REG_SZ",vdata='test_data_value')`

Also what version of Windows are you running? (Not that it matters a ton)

**Comment by xeacott** [comment]
I am able to set the key using _just_ the command and then lookup with a reg.read_value

```
me@DESKTOP-SQIU2I1:/srv/salt/_modules# salt windows reg.read_value HKEY_LOCAL_MACHINE "SOFTWARE\\Salt\\test_key"
windows:
    ----------
    hive:
        HKEY_LOCAL_MACHINE
    key:
        SOFTWARE\Salt\test_key
    success:
        True
    vdata:
        (value not set)
    vname:
        (Default)
    vtype:
        REG_SZ
```

**Comment by H20-17** [comment]
@xeacott, I upgraded my test minion to 3000.2 and I'm still experiencing the issue. My windows version is 10.0.18363.

The command:
```
salt windows_minion pillar.items
```
runs without issue. And so does
```
salt windows_minion reg.set_value HKEY_LOCAL_MACHINE 'SOFTWARE\\Salt\\test_key' 'test_property' vtype="REG_SZ" vdata='test_data_value'
```
You said

> I am able to set the key using just the command and then lookup with a reg.read_value

Right. I understand. That all works. It's only failing when I'm trying to read dunder dictionaries inside an external module when the module is executed by a pillar scheduled event (i don't know about other scheduled events). I don't think it's got much (or anything) to to with the _win_reg_ execution module or the _reg_ util module. They're simply not loaded into either the _\_\_salt\_\__ or _\_\_util\_\__ dictionaries. I just chose the _reg_ module as an example.

**Comment by xeacott** [comment]
Yes you are correct sir @H20-17 I just wanted to make sure the basics worked as I do not have much experience with the module itself, as well as asking about your version of Windows; sometimes we run into issues that are present on certain versions of windows vs. others. 😄

**Comment by H20-17** [comment]
@waynew, I notice that you added the _Info Needed_ tag. I need to know what info you would like to have.

**Comment by dwoz** [comment]
Fixed in cabc7e3fbaa ("Make sure we repopulate __utils__ on Windows when a job is run from the scheduler", Sep 2020) — `handle_func` now re-runs `salt.loader.utils(self.opts)` on spawning platforms, so scheduled jobs get a populated `__utils__` (and therefore `__salt__` funcs that depend on it). Regression covered by `tests/pytests/unit/utils/scheduler/test_schedule.py::test_handle_func_check_dicts`, present and passing on 3006.x, 3007.x, 3008.x, and master.
