### ISSUE TITLE
win_system.join_domain fails in version 3000.2

### ISSUE THREAD

**Issue by Mapel88** [saltstack/salt#57202]
**Description**
Add server to domain fails in version 3000.2.
Issue started in version 2019.2.1 and never fixed ( bug #54869  )
Different errors though.

**Setup**
```
{% set domain_info = salt['pillar.get']('domain', {}) %}
{% if domain_info.add_to_domain %}
  join_to_{domain_info.domain_name}:
    system.join_domain:
      - name: {{ domain_info.get('domain_name') }}
      - username: {{ domain_info.get('user', 'Administrator')}}
      - password: {{ domain_info.get('password') }}
      - account_exists: {{ domain_info.get('account_exists', 'False') }}
      - restart: {{ domain_info.get('restart', 'False') }}
      {% if 'account_ou' in domain_info -%}
      - account_ou: {{ domain_info.get('account_ou') }}
      {% endif -%}
{% endif %}

```

**Steps to Reproduce the behavior**
**_state test:_**
salt 'nl1-iistest01' state.apply add2domain -l debug

```
----------
          ID: add2domain
    Function: salt.state
      Result: False
     Comment: Attempt 1: Returned a result of "False", with the following comment: "Run failed on minions: nl1-iistest01"
              Attempt 2: Returned a result of "False", with the following comment: "Run failed on minions: nl1-iistest01"
              Run failed on minions: nl1-iistest01
     Started: 14:18:33.411283
    Duration: 195979.12 ms
     Changes:   
              nl1-iistest01:
              ----------
                        ID: join_to_{domain_info.domain_name}
                  Function: system.join_domain
                      Name: nl.eu.com
                    Result: False
                   Comment: An exception occurred in this state: Traceback (most recent call last):
                              File "c:\salt\bin\lib\site-packages\wmi.py", line 1145, in __getattr__
                                return self._cached_classes (attribute)
                              File "c:\salt\bin\lib\site-packages\wmi.py", line 1156, in _cached_classes
                                self._classes_map[class_name] = _wmi_class (self, self._namespace.Get (class_name))
                              File "<COMObject winmgmts:>", line 3, in Get
                              File "c:\salt\bin\lib\site-packages\win32com\client\dynamic.py", line 287, in _ApplyTypes_
                                result = self._oleobj_.InvokeTypes(*(dispid, LCID, wFlags, retType, argTypes) + args)
                            pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, 'SWbemServicesEx', 'The object invoked has disconnected from its clients. ', None, 0, -2147417848), None)
                            
                            During handling of the above exception, another exception occurred:
                            
                            Traceback (most recent call last):
                              File "c:\salt\bin\lib\site-packages\salt-3000.2-py3.5.egg\salt\state.py", line 1981, in call
                                **cdata['kwargs'])
                              File "c:\salt\bin\lib\site-packages\salt-3000.2-py3.5.egg\salt\loader.py", line 1977, in wrapper
                                return f(*args, **kwargs)
                              File "c:\salt\bin\lib\site-packages\salt-3000.2-py3.5.egg\salt\states\win_system.py", line 223, in join_domain
                                current_domain_dic = __salt__['system.get_domain_workgroup']()
                              File "c:\salt\bin\lib\site-packages\salt-3000.2-py3.5.egg\salt\modules\win_system.py", line 986, in get_domain_workgroup
                                for computer in conn.Win32_ComputerSystem():
                              File "c:\salt\bin\lib\site-packages\wmi.py", line 1147, in __getattr__
                                return getattr (self._namespace, attribute)
                              File "c:\salt\bin\lib\site-packages\win32com\client\dynamic.py", line 527, in __getattr__
                                raise AttributeError("%s.%s" % (self._username_, attr))
                            AttributeError: winmgmts:.Win32_ComputerSystem
                   Started: 13:21:45.625530
                  Duration: 15.68 ms
                   Changes:   
              
              Summary for nl1-iistest01
              ------------
              Succeeded: 0
              Failed:    1
              ------------
              Total states run:     1
              Total run time:  15.680 ms

```

**_module test_**
salt 'nl1-iistes01' system.join_domain domain='my.domain.com' username='adminUser' password='xxxxxxx' account_exists=False, restart=false

```
nl1-iistest01:
    The minion function caused an exception: Traceback (most recent call last):
      File "c:\salt\bin\lib\site-packages\wmi.py", line 1145, in __getattr__
        return self._cached_classes (attribute)
      File "c:\salt\bin\lib\site-packages\wmi.py", line 1156, in _cached_classes
        self._classes_map[class_name] = _wmi_class (self, self._namespace.Get (class_name))
      File "<COMObject winmgmts:>", line 3, in Get
      File "c:\salt\bin\lib\site-packages\win32com\client\dynamic.py", line 287, in _ApplyTypes_
        result = self._oleobj_.InvokeTypes(*(dispid, LCID, wFlags, retType, argTypes) + args)
    pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, 'SWbemServicesEx', 'The object invoked has disconnected from its clients. ', None, 0, -2147417848), None)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "c:\salt\bin\lib\site-packages\salt-3000.2-py3.5.egg\salt\minion.py", line 1676, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "c:\salt\bin\lib\site-packages\salt-3000.2-py3.5.egg\salt\executors\direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "c:\salt\bin\lib\site-packages\salt-3000.2-py3.5.egg\salt\modules\win_system.py", line 770, in join_domain
        status = get_domain_workgroup()
      File "c:\salt\bin\lib\site-packages\salt-3000.2-py3.5.egg\salt\modules\win_system.py", line 986, in get_domain_workgroup
        for computer in conn.Win32_ComputerSystem():
      File "c:\salt\bin\lib\site-packages\wmi.py", line 1147, in __getattr__
        return getattr (self._namespace, attribute)
      File "c:\salt\bin\lib\site-packages\win32com\client\dynamic.py", line 527, in __getattr__
        raise AttributeError("%s.%s" % (self._username_, attr))
    AttributeError: winmgmts:.Win32_ComputerSystem
```

**_salt-call test_**

salt-call system.join_domain system.join_domain domain='my.domain.com' username='adminUser' 
```
password='xxxxxxx' account_exists=False, restart=false
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Including configuration from 'c:\salt\conf\minion.d\_schedule.conf'
[DEBUG   ] Reading configuration from c:\salt\conf\minion.d\_schedule.conf
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Including configuration from 'c:\salt\conf\minion.d\_schedule.conf'
[DEBUG   ] Reading configuration from c:\salt\conf\minion.d\_schedule.conf
[DEBUG   ] Motherboard info not available on this system
[DEBUG   ] Loading static grains from c:\salt\conf\grains
[DEBUG   ] "myMaster" Not an IP address? Assuming it is a hostname.
[DEBUG   ] Master URI: tcp://1.1.1.1:4506
[DEBUG   ] Connecting to master. Attempt 1 (infinite attempts)
[DEBUG   ] "myMaster" Not an IP address? Assuming it is a hostname.
[DEBUG   ] Master URI: tcp://1.1.1.1:4506
[DEBUG   ] Popen(['git', 'version'], cwd=C:\Users\Administrator, universal_newlines=False, shell=None)
[DEBUG   ] Popen(['git', 'version'], cwd=C:\Users\Administrator, universal_newlines=False, shell=None)
[DEBUG   ] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'nl1-iistest01', 'tcp://1.1.1.1:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (9531)
[DEBUG   ] Setting zmq_reconnect_ivl to '9531ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'nl1-iistest01', 'tcp://1.1.1.1:4506', 'clear')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://1.1.1.1:4506
[DEBUG   ] Trying to connect to: tcp://1.1.1.1:4506
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] salt.crypt._get_key_with_evict: Loading private key
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[DEBUG   ] Connecting the Minion to the Master publish port, using the URI: tcp://1.1.1.1:4505
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
[DEBUG   ] Determining pillar cache
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'nl1-iistest01', 'tcp://1.1.1.1:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'nl1-iistest01', 'tcp://1.1.1.1:4506')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://1.1.1.1:4506
[DEBUG   ] Trying to connect to: tcp://1.1.1.1:4506
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded system.join_domain
[DEBUG   ] LazyLoaded direct_call.execute
Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt-3000.2-py3.5.egg\salt\cli\caller.py", line 218, in call
    ret['return'] = self.minion.executors[fname](self.opts, data, func, args, kwargs)
  File "C:\salt\bin\lib\site-packages\salt-3000.2-py3.5.egg\salt\executors\direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt-3000.2-py3.5.egg\salt\modules\win_system.py", line 796, in join_domain
    raise CommandExecutionError(win32api.FormatMessage(err).rstrip())
salt.exceptions.CommandExecutionError: No mapping between account names and security IDs was done.
Error running 'system.join_domain': No mapping between account names and security IDs was done.

```

**Expected behavior**
server added to domain.

**Versions Report**

```
Salt Version:
           Salt: 3000.2
 
Dependency Versions:
           cffi: 1.13.2
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
         Jinja2: 2.7.2
        libgit2: 0.24.6
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: 3.6.1
         pygit2: 0.24.2
         Python: 2.7.5 (default, Aug  7 2019, 00:51:29)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.1.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core
 

```
</details>

**Additional context**

**Comment by arizvisa** [comment]
@Mapel88, can you try executing `system.get_domain_workgroup` on the minion? It should return the same error.

Once that's been confirmed, can you verify that wmi queries work on the box? You can probably do that like `wmic computersystem` at a console. Essentially we need to troubleshoot why WMI/COM is returning error 0x80020009.

**Comment by baby-gnu** [comment]
I have the same issue with `2019.2.5-py2`, `3000.3-py2` and `3000.3-py3`:

```
salt 'PC-*' system.get_domain_workgroup
PC-420266.example.net:
    The minion function caused an exception: Traceback (most recent call last):
      File "c:\salt\bin\lib\site-packages\salt-3000.3-py2.7.egg\salt\minion.py", line 1676, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "c:\salt\bin\lib\site-packages\salt-3000.3-py2.7.egg\salt\executors\direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "c:\salt\bin\lib\site-packages\salt-3000.3-py2.7.egg\salt\modules\win_system.py", line 986, in get_domain_workgroup
        for computer in conn.Win32_ComputerSystem():
      File "c:\salt\bin\lib\site-packages\wmi.py", line 1147, in __getattr__
        return getattr (self._namespace, attribute)
      File "c:\salt\bin\lib\site-packages\win32com\client\dynamic.py", line 527, in __getattr__
        raise AttributeError("%s.%s" % (self._username_, attr))
    AttributeError: winmgmts:.Win32_ComputerSystem
```

I'm running `wmic` without issue:

```
salt 'PC-*' cmd.run 'wmic ComputerSystem get PartOfDomain'
PC-420266.example.net:
    PartOfDomain

    FALSE
```

It's working fine with `3001.1-py3`:

```
salt 'PC-*' system.get_domain_workgroup
PC-420266.example.net:
    ----------
    Workgroup:
        WORKGROUP
```

**Comment by dwoz** [comment]
Fixed by #57360 (merged 2020-05-18, shipped in 3001). Reporter <code>baby-gnu</code> confirmed the fix in-thread. Current 3006.x/3007.x/3008.x/master all carry the fixed indentation of `conn.Win32_ComputerSystem()` calls inside the `with salt.utils.winapi.Com():` block in `salt/modules/win_system.py`.
