### ISSUE TITLE
[BUG]AttributeError: 'module' object has no attribute 'nested'

### ISSUE THREAD

**Issue by felixglow** [saltstack/salt#57403]
**Description**
Salt master send commond to minion, this error occurs in the minion log

**Setup**
salt "minion" test.ping

**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

**Expected behavior**
return True

**Screenshots**
![image](https://user-images.githubusercontent.com/8147810/82521543-8ee52d00-9b59-11ea-8af9-4daa34b116e7.png)

**Versions Report**
<details>
<summary>
Master: centos7, saltstack 3000.3, python2   |
Minion:  ubuntu14.04, saltstack 2019.2.0, python2

</summary> 

```
#### Master
Salt Version:
           Salt: 3000.3

Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  7 2019, 00:51:29)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

#### Minion
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Nov 13 2018, 12:45:42)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 TrustyTahr
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-22-generic
         system: Linux
        version: Ubuntu 14.04 TrustyTahr
```
</details>

**Additional context**
```
2020-05-17 06:30:37,314 [salt.utils.process                                    :772 ][ERROR   ][40435] An un-handled exception from the multiprocessing process 'SignalHandlingMultiprocessingProcess-1:9515' was caught:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/process.py", line 765, in _run
    return self._original_run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1581, in _target
    with tornado.stack_context.StackContext(minion_instance.ctx):
  File "/usr/lib/python2.7/dist-packages/tornado/stack_context.py", line 135, in __enter__
    self.enter()
  File "/usr/lib/python2.7/dist-packages/tornado/stack_context.py", line 118, in enter
    context = self.context_factory()
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1540, in ctx
    return contextlib.nested(
AttributeError: 'module' object has no attribute 'nested'
```

**Comment by garethgreenaway** [comment]
@felixglow Thanks for the report.  I haven't been able to reproduce this issue.  Are you installing Salt via the provided packages?

**Comment by felixglow** [comment]
@garethgreenaway  yes, install salt from official website
**here is my install steps:**

```
root@WCHJELK005:~# wget -O - https://repo.saltstack.com/apt/ubuntu/14.04/amd64/2019.2/SALTSTACK-GPG-KEY.pub | sudo apt-key add -
--2020-05-22 00:07:14--  https://repo.saltstack.com/apt/ubuntu/14.04/amd64/2019.2/SALTSTACK-GPG-KEY.pub
Resolving repo.saltstack.com (repo.saltstack.com)... 99.84.230.59, 99.84.230.3, 99.84.230.76, ...
Connecting to repo.saltstack.com (repo.saltstack.com)|99.84.230.59|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1727 (1.7K) [application/octet-stream]
Saving to: ‘STDOUT’

-                                 100%[============================================================>]   1.69K  --.-KB/s    in 0s

2020-05-22 00:07:15 (365 MB/s) - written to stdout [1727/1727]

OK


root@WCHJELK005:~# echo "deb https://repo.saltstack.com/apt/ubuntu/14.04/amd64/2019.2 trusty main" | tee /etc/apt/sources.list.d/saltstack.list
deb https://repo.saltstack.com/apt/ubuntu/14.04/amd64/2019.2 trusty main
root@WCHJELK005:~# apt-get update
Ign:1 http://172.28.184.28/ubuntu trusty InRelease
Hit:2 http://172.28.184.28/ubuntu trusty-updates InRelease
Hit:3 http://172.28.184.28/ubuntu trusty-backports InRelease
Hit:4 http://172.28.184.28/ubuntu trusty-security InRelease
Hit:5 http://172.28.184.28/ubuntu trusty Release
Get:9 https://repo.saltstack.com/apt/ubuntu/14.04/amd64/2019.2 trusty/main i386 Packages [5,575 B]
Reading package lists... Done
W: https://repo.saltstack.com/apt/ubuntu/14.04/amd64/2019.2/dists/trusty/InRelease: Signature by key 754A1A7AE731F165D5E6D4BD0E08A149DE57BFBE uses weak digest algorithm (SHA1)
root@WCHJELK005:~# apt-get install salt-minion -y
Reading package lists... Done
Building dependency tree
Reading state information... Done

root@WCHJELK005:~# service salt-minion restart
root@WCHJELK005:~# systemctl status salt-minion
● salt-minion.service - LSB: salt minion control daemon
   Loaded: loaded (/etc/init.d/salt-minion; bad; vendor preset: enabled)
   Active: active (running) since Fri 2020-05-22 00:12:02 EDT; 10min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 99511 ExecStart=/etc/init.d/salt-minion start (code=exited, status=0/SUCCESS)
    Tasks: 3 (limit: 512)
   Memory: 42.1M
      CPU: 2.103s
   CGroup: /system.slice/salt-minion.service
           └─99535 /usr/bin/python /usr/bin/salt-minion -d

May 22 00:12:02 WCHJELK005 systemd[1]: Starting LSB: salt minion control daemon...
May 22 00:12:02 WCHJELK005 salt-minion[99511]:  * Starting salt minion control daemon salt-minion
May 22 00:12:02 WCHJELK005 salt-minion[99511]:    ...done.
May 22 00:12:02 WCHJELK005 systemd[1]: Started LSB: salt minion control daemon.
```

**everything is ok, but when i send commond from the master, this error occurs in the minion log**

```
2020-05-22 00:24:33,559 [salt.utils.process                                    :772 ][ERROR   ][99882] An un-handled exception from the multiprocessing process 'SignalHandlingMultiprocessingProcess-1:21' was caught:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/process.py", line 765, in _run
    return self._original_run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1581, in _target
    with tornado.stack_context.StackContext(minion_instance.ctx):
  File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 135, in __enter__
    self.enter()
  File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 118, in enter
    context = self.context_factory()
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1540, in ctx
    return contextlib.nested(
AttributeError: 'module' object has no attribute 'nested'
2020-05-22 00:24:38,596 [salt.utils.process                                    :772 ][ERROR   ][99885] An un-handled exception from the multiprocessing process 'SignalHandlingMultiprocessingProcess-1:22' was caught:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/process.py", line 765, in _run
    return self._original_run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1581, in _target
    with tornado.stack_context.StackContext(minion_instance.ctx):
  File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 135, in __enter__
    self.enter()
  File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 118, in enter
    context = self.context_factory()
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1540, in ctx
    return contextlib.nested(
AttributeError: 'module' object has no attribute 'nested'
```

**Comment by garethgreenaway** [comment]
@felixglow Thanks!

**Comment by garethgreenaway** [comment]
@felixglow I attempted to replicate this with a CentOS 7 master running 3000.3 and a Ubuntu 14.04 minion running 2019.2.0, but unfortunately I wasn't able to.  Commands ran as expected.  Ubuntu 14.04 is no longer supported by us so it won't be receiving new packages.  Are you able to upgrade to a newer version of Ubuntu?

**Comment by felixglow** [comment]
@garethgreenaway There are some difficulties，this is an ancient project。Thank you brother！
