### ISSUE TITLE
collections deprecation warning deque

### ISSUE THREAD

**Issue by alan-cugler** [saltstack/salt#57429]
**Description**
Hello, working off the latest 3000.3 salt, and I have a deprecation warning for collections. I see [here](https://github.com/saltstack/salt/pull/57240/files) we had a merged PR for this in the sodium release but not for this particular file.

Relevant Warning
```
Traceback (most recent call last):
  File "/usr/bin/salt", line 8, in <module>
    sys.exit(salt_main())
  File "/usr/lib/python3.7/site-packages/salt/scripts.py", line 525, in salt_main
    import salt.cli.salt
  File "/usr/lib/python3.7/site-packages/salt/cli/salt.py", line 11, in <module>
    import salt.utils.job
  File "/usr/lib/python3.7/site-packages/salt/utils/job.py", line 11, in <module>
    import salt.minion
  File "/usr/lib/python3.7/site-packages/salt/minion.py", line 34, in <module>
    import salt.utils.crypt
  File "/usr/lib/python3.7/site-packages/salt/utils/crypt.py", line 16, in <module>
    import salt.loader
  File "/usr/lib/python3.7/site-packages/salt/loader.py", line 24, in <module>
    import salt.config
  File "/usr/lib/python3.7/site-packages/salt/config/__init__.py", line 100, in <module>
    _DFLT_IPC_WBUFFER = _gather_buffer_space() * .5
  File "/usr/lib/python3.7/site-packages/salt/config/__init__.py", line 89, in _gather_buffer_space
    import salt.grains.core
  File "/usr/lib/python3.7/site-packages/salt/grains/core.py", line 58, in <module>
    import salt.utils.dns
  File "/usr/lib/python3.7/site-packages/salt/utils/dns.py", line 34, in <module>
    import salt.modules.cmdmod
  File "/usr/lib/python3.7/site-packages/salt/modules/cmdmod.py", line 34, in <module>
    import salt.utils.templates
  File "/usr/lib/python3.7/site-packages/salt/utils/templates.py", line 32, in <module>
    import salt.utils.http
  File "/usr/lib/python3.7/site-packages/salt/utils/http.py", line 73, in <module>
    import salt.ext.tornado.httputil
  File "/usr/lib/python3.7/site-packages/salt/ext/tornado/httputil.py", line 104, in <module>
    _normalized_headers = _NormalizedHeaderCache(1000)
  File "/usr/lib/python3.7/site-packages/salt/ext/tornado/httputil.py", line 89, in __init__
    self.queue = collections.deque()
AttributeError: module 'collections.abc' has no attribute 'deque'
```
The main problem is I dont see a natural upgrade for `collections.deque` in collections.abc. Would someone know the whats the correct transition?

The Relevant [code](https://github.com/saltstack/salt/blob/9b74e9bb167d65d693521f28b033e04ec4752ce9/salt/ext/tornado/httputil.py#L75-L101)

**Comment by krionbsd** [comment]
It seems it's fixed in master branch, could you check it:
https://github.com/saltstack/salt/blob/master/salt/ext/tornado/httputil.py

**Comment by dmurphy18** [comment]
@alan-cugler Can you check per @krionbsd request that this is resolved

**Comment by Ch3LL** [comment]
Closing due to inactivity. If this is still an issue please feel free to open a new issue
