### ISSUE TITLE
Git broken in Python3 Minion when not using UTF-8 as system locale

### ISSUE THREAD

**Issue by crimv42** [saltstack/salt#57432]
**Description**
When trying to use the state `git.latest` on a system that uses both Python3 and a locale that is _not_ UTF-8, the state fails with a `UnicodeEncodeError`:
```
          ID: salt_git_repo
    Function: git.latest
        Name: git@github.com:remote/repo.git
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 1933, in call
                  **cdata['kwargs'])
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 1951, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/git.py", line 774, in latest
                  output_encoding=output_encoding)
                File "/usr/lib/python3/dist-packages/salt/modules/git.py", line 3951, in remote_refs
                  output_encoding=output_encoding)['stdout']
                File "/usr/lib/python3/dist-packages/salt/modules/git.py", line 319, in _git_run
                  **kwargs)
                File "/usr/lib/python3/dist-packages/salt/modules/cmdmod.py", line 2084, in run_all
                  **kwargs)
                File "/usr/lib/python3/dist-packages/salt/modules/cmdmod.py", line 665, in _run
                  proc = salt.utils.timed_subprocess.TimedProc(cmd, **new_kwargs)
                File "/usr/lib/python3/dist-packages/salt/utils/timed_subprocess.py", line 49, in __init__
                  self.process = subprocess.Popen(args, **kwargs)
                File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
                  restore_signals, start_new_session)
                File "/usr/lib/python3.5/subprocess.py", line 1471, in _execute_child
                  for k, v in env.items()]
                File "/usr/lib/python3.5/subprocess.py", line 1471, in <listcomp>
                  for k, v in env.items()]
                File "/usr/lib/python3.5/os.py", line 860, in fsencode
                  return filename.encode(encoding, errors)
              UnicodeEncodeError: 'latin-1' codec can't encode character '\u2192' in position 15: ordinal not in range(256)
```

**Setup**
State:
```
salt_git_repo:
  git.latest:
    - user:  root
    - name:  {{ master.source }}
    - output_encoding: ISO-8859-1
    - target: {{ master.target }}
    - identity: {{ master.key }}
    - branch: {{ master.branch }}
    - rev: {{ master.rev }}
    - force_clone: {{ master.f_clone }}
    - force_checkout: {{ master.f_checkout }}
    - force_reset: {{ master.f_reset }}
    - force_fetch: {{ master.f_fetch }}
```

Also tried `output_encoding: latin-1`, and same results.

**Steps to Reproduce the behavior**
Try the git.latest state while using a system locale that is not UTF-8.

**Expected behavior**
Git clone into the output directory no matter the locale, or at least the specified locale.

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

Master and Minion
```
(dev)$ sudo salt-call --versions-report
Salt Version:
           Salt: 2019.2.5
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.2 (default, Apr 16 2020, 17:47:17)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: ISO-8859-1
        machine: x86_64
        release: 4.4.0-142-generic
         system: Linux
        version: Ubuntu 16.04 xenial

```
</details>

**Additional context**

**Comment by dmurphy18** [comment]
@crimv42 I believe that this is to be expected since Python 3 will typically assume UTF-8 is available.
For example: PEP 538 and PEP 540 cover this in detail and a working solution, see https://www.python.org/dev/peps/pep-0538 and https://www.python.org/dev/peps/pep-0540

This does work in environments where only 'C' and POSIX locales are available.using Python 3.7, Cython and POSIX locale, such as on switches/routers or some containers as stated in the PEP.

Noting that you are making use of Python 3.5 (probably Debian 9 or Ubuntu 16.04). 

SaltStack is addressing these issues with a self-contained Python 3.7 based binary with all dependencies internal  called **_salt-bin_** in the upcoming Salt 3001 point release (mid-end June) to overcome these issues, alongside the normal packages.

**Comment by Ch3LL** [comment]
Closing due to inactivity. If this is still a valid issue on the latest version of Salt please open a new issue with the details.
