### ISSUE TITLE
[BUG] network.wolmatch failed on Windows because of Loopback interface not ignored

### ISSUE THREAD

**Issue by davidme4** [saltstack/salt#57476]
**Description**
`network.wolmatch` failed on Windows

**Setup**
Salt 3000.3 (On CentOS 7)

**Steps to Reproduce the behavior**
With correction indicated on the bottom of in https://github.com/saltstack/salt/issues/57473 to make `network.wolmatch`  working.
Just (after having Windows Minion associate, with Grains Cache) test wolmatch function as defined [here](https://docs.saltstack.com/en/latest/ref/runners/all/salt.runners.network.html#salt.runners.network.wolmatch).
salt-run network.wolmatch my_windows_minion_id
Error :
```Exception occurred in runner network2.wolmatch: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 374, in low
    data['return'] = func(*args, **kwargs)
  File "/var/lib/salt/runners/network2.py", line 80, in wolmatch
    wol(mac, bcast, destport)
  File "/var/lib/salt/runners/network2.py", line 55, in wol
    dest = salt.utils.network.mac_str_to_bytes(mac)
  File "/usr/lib/python2.7/site-packages/salt/utils/network.py", line 1834, in mac_str_to_bytes
    raise ValueError('Invalid MAC address')
ValueError: Invalid MAC address
```
**Expected behavior**
No error, success of `wolmatch` function on Windows minion.

**Versions Report**
<details><summary>salt --versions-report</summary>
Salt Version:
           Salt: 3000.3

Dependency Versions:
           cffi: 1.14.0
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Apr  9 2019, 14:30:50)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.7.1908 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.12.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.7.1908 Core
</details>

**Additional context**
On windows minion Grains there is a Loopback interface to be ignored : 
```
hwaddr_interfaces:
        ----------
        Intel(R) PRO/1000 MT Desktop Adapter #2:
            08:00:XX:XX:XX:XX
        Software Loopback Interface 1:
            :::::
```
That interface is not ignored in  [network.py](https://github.com/saltstack/salt/blob/master/salt/runners/network.py), but is ignored for linux with 
```
if iface == "lo":
                continue
```
_**Tested solution with succes with a specific runner clone from network.py :**_
Will be to add something like (on line 77) : 
```
if "Loopback" in iface :
                # continue
```
Or can be to ignored `00:00:00:00:00:00` and `:::::` MAC adress.

**Comment by dmurphy18** [comment]
PR submitted, but it needs testcases

**Comment by dwoz** [comment]
Fix merged and shipped in a supported release. Closing per bulk triage. Reopen if this reproduces on a currently supported release (3006.x, 3007.x, 3008.x, master).
