### ISSUE TITLE
SDB.GET Module Traceback Error with SALT-RUN

### ISSUE THREAD

**Issue by ironman627** [saltstack/salt#57472]
**Description**
When executing the command: "salt-run sdb.get sdb://mysqlite/app_licence_key" it generates the following error: (issuing the salt-call version of this command works fine)
#############
salt-run sdb.get sdb://mysqlite/app_license_key
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: Object of type 'bytes' is not JSON serializable
Traceback (most recent call last):
  File "/usr/bin/salt-run", line 11, in <module>
    load_entry_point('salt==3000.3', 'console_scripts', 'salt-run')()
  File "/usr/lib/python3.6/site-packages/salt/scripts.py", line 457, in salt_run
    client.run()
  File "/usr/lib/python3.6/site-packages/salt/cli/run.py", line 40, in run
    ret = runner.run()
  File "/usr/lib/python3.6/site-packages/salt/runner.py", line 273, in run
    daemonize=False)
  File "/usr/lib/python3.6/site-packages/salt/client/mixins.py", line 472, in _proc_function
    return self.low(fun, low, full_return=False)
  File "/usr/lib/python3.6/site-packages/salt/client/mixins.py", line 407, in low
    mminion=self.mminion,
  File "/usr/lib/python3.6/site-packages/salt/utils/job.py", line 108, in store_job
    mminion.returners[savefstr](load['jid'], load)
  File "/usr/lib/python3.6/site-packages//sseape/returners/sseapi_return.py", line 133, in save_load
    get_client().api.ret.save_load(__opts__['id'], jid, load=load)
  File "/usr/lib/python3.6/site-packages/sseapiclient/apiloader.py", line 40, in __call__
    return self._client.call(self._resource_name, self._method_name, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/sseapiclient/apiclient.py", line 187, in call
    result = self.httpclient.fetch(url='/rpc', method='POST', body=payload, timeout=timeout)
  File "/usr/lib/python3.6/site-packages/sseapiclient/httpclient.py", line 414, in fetch
    request = self._build_request(url, method, body)
  File "/usr/lib/python3.6/site-packages/sseapiclient/httpclient.py", line 164, in _build_request
    body = self.json_dumps(body).encode()
  File "/usr/lib/python3.6/site-packages/sseapiclient/httpclient.py", line 197, in json_dumps
    return sseapiclient.serialize.json_dumps(data, cls=self.json_encoder)
  File "/usr/lib/python3.6/site-packages/sseapiclient/serialize.py", line 36, in json_dumps
    return json.dumps(obj, cls=cls)
  File "/usr/lib64/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib64/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/site-packages/sseapiclient/serialize.py", line 55, in default
    return super(JSONEncoder, self).default(obj)
  File "/usr/lib64/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable
Traceback (most recent call last):
  File "/usr/bin/salt-run", line 11, in <module>
    load_entry_point('salt==3000.3', 'console_scripts', 'salt-run')()
  File "/usr/lib/python3.6/site-packages/salt/scripts.py", line 457, in salt_run
    client.run()
  File "/usr/lib/python3.6/site-packages/salt/cli/run.py", line 40, in run
    ret = runner.run()
  File "/usr/lib/python3.6/site-packages/salt/runner.py", line 273, in run
    daemonize=False)
  File "/usr/lib/python3.6/site-packages/salt/client/mixins.py", line 472, in _proc_function
    return self.low(fun, low, full_return=False)
  File "/usr/lib/python3.6/site-packages/salt/client/mixins.py", line 407, in low
    mminion=self.mminion,
  File "/usr/lib/python3.6/site-packages/salt/utils/job.py", line 108, in store_job
    mminion.returners[savefstr](load['jid'], load)
  File "/usr/lib/python3.6/site-packages//sseape/returners/sseapi_return.py", line 133, in save_load
    get_client().api.ret.save_load(__opts__['id'], jid, load=load)
  File "/usr/lib/python3.6/site-packages/sseapiclient/apiloader.py", line 40, in __call__
    return self._client.call(self._resource_name, self._method_name, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/sseapiclient/apiclient.py", line 187, in call
    result = self.httpclient.fetch(url='/rpc', method='POST', body=payload, timeout=timeout)
  File "/usr/lib/python3.6/site-packages/sseapiclient/httpclient.py", line 414, in fetch
    request = self._build_request(url, method, body)
  File "/usr/lib/python3.6/site-packages/sseapiclient/httpclient.py", line 164, in _build_request
    body = self.json_dumps(body).encode()
  File "/usr/lib/python3.6/site-packages/sseapiclient/httpclient.py", line 197, in json_dumps
    return sseapiclient.serialize.json_dumps(data, cls=self.json_encoder)
  File "/usr/lib/python3.6/site-packages/sseapiclient/serialize.py", line 36, in json_dumps
    return json.dumps(obj, cls=cls)
  File "/usr/lib64/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib64/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/site-packages/sseapiclient/serialize.py", line 55, in default
    return super(JSONEncoder, self).default(obj)
  File "/usr/lib64/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable
####################################################

**Setup**
1. Yum install sqlite
2. create /etc/salt/master.d/sdb_sqlite.conf
################
# Place in both master.d and minion.d directories
mysqlite:
  driver: sqlite3
  database: /opt/salt/sdb.db
  table: sdb
  create_table: True
###############

**Steps to Reproduce the behavior**
1. After setup is done, then execute "salt-run sdb.set sdb://mysqlite/app_license_key "111-222-333"
2. Then execute salt-run sdb.get sdb://mysqlite/app_license_key
3. Error appears
4. Execute salt-call sdb.get sdb://mysqlite/app_license_key to see that this command functions properly.

**Expected behavior**
The following similar output should appear as the results of the above command:
#########
[root@demo-master-tmpl ~]# salt-call sdb.get sdb://mysqlite/app_license_key
local:
    111-222-333
###############

**Screenshots**
![image](https://user-images.githubusercontent.com/12309269/83027603-2678ce80-9fe5-11ea-98da-094063e7909b.png)

[root@demo-master-tmpl ~]# salt-run sdb.set sdb://mysqlite/app_license_key "111-222-333"
True
[root@demo-master-tmpl ~]#

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
[root@demo-master-tmpl ~]# salt --versions-report
Salt Version:
           Salt: 3000.3

Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.1
        libgit2: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Apr  2 2020, 13:34:55)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 15.3.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.8.2003 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.el7.x86_64
         system: Linux
        version: CentOS Linux 7.8.2003 Core

```
</details>

**Comment by oeuftete** [comment]
This is summarized maybe a little more tidily in #58533; I'd prefer that one over this if we want to close a duplicate.

As well, when this or the other is addressed, please also consider internal issue raas_master 692 for the full picture.

**Comment by sagetherage** [comment]
duplicate
