### ISSUE TITLE
[BUG] Saltcheck raises UnboundLocalError exception

### ISSUE THREAD

**Issue by onionka** [saltstack/salt#57485]
**Description**
Since I started trying out the saltcheck, I have gotten multiple exceptions like this. I don't know what exactly causes them, because the message is not really helpful. I was trying to implement simple tests for already working apache, just to learn how to implement tests. It should test if the directory exists and if `index.html` is present, just to try out `assertions` option. I can put there basically anything valid and it just raises this error when I use this option.

**Setup**
```
test_public_html_present:
  module_and_function: cmd.run
  args:
    - ls /var/www/html/{{ salt['pillar'].get('domain') }}/public_html
  assertions:
    - assertion: assertNotEmpty
    - assertion: assertContains
      expected_return: index.html
  print_result: True
  output_details: True
```

**Steps to Reproduce the behavior**
 - Implement `saltcheck-tests/apache.tst`
 - Run `sudo salt 'minion2' saltcheck.run_highstate_tests` on master

**Expected behavior**
I expected that test will pass or fail with a proper error message.

**Output**
```
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1676, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/saltcheck.py", line 464, in run_highstate_tests
        return run_state_tests(all_states, saltenv=saltenv)
      File "/usr/lib/python2.7/dist-packages/salt/modules/saltcheck.py", line 434, in run_state_tests
        result = scheck.run_test(value)
      File "/usr/lib/python2.7/dist-packages/salt/modules/saltcheck.py", line 749, in run_test
        if assertion_section:
    UnboundLocalError: local variable 'assertion_section' referenced before assignment
```

**Versions Report**

<details><summary>Master: $ salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3000.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.17 (default, Apr 15 2020, 17:20:14)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-99-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```
</details>

<details><summary>Minion: $ salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
/usr/lib/python2.7/dist-packages/salt/scripts.py:212: DeprecationWarning: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date.  Salt will drop support for Python 2.7 in the Sodium release or later.
Salt Version:
           Salt: 3000.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.17 (default, Apr 15 2020, 17:20:14)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-99-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```
</details>

<details><summary>$ diff master.version minion.version</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
+/usr/lib/python2.7/dist-packages/salt/scripts.py:212: DeprecationWarning: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date.  Salt will drop support for Python 2.7 in the Sodium release or later.
 Salt Version:
            Salt: 3000.3
  
 Dependency Versions:
            cffi: Not Installed
        cherrypy: Not Installed
        dateutil: 2.6.1
       docker-py: Not Installed
-          gitdb: 2.0.3
-      gitpython: 2.1.8
+          gitdb: Not Installed
+      gitpython: Not Installed
          Jinja2: 2.10
         libgit2: Not Installed
        M2Crypto: Not Installed
            Mako: 1.0.7
    msgpack-pure: Not Installed
  msgpack-python: 0.5.6
    mysql-python: Not Installed
       pycparser: Not Installed
        pycrypto: 2.6.1
    pycryptodome: Not Installed
          pygit2: Not Installed
          Python: 2.7.17 (default, Apr 15 2020, 17:20:14)
    python-gnupg: 0.4.1
          PyYAML: 3.12
           PyZMQ: 16.0.2
-          smmap: 2.0.3
+          smmap: Not Installed
         timelib: Not Installed
         Tornado: 4.5.3
             ZMQ: 4.2.5
  
 System Versions:
            dist: Ubuntu 18.04 bionic
          locale: UTF-8
         machine: x86_64
         release: 4.15.0-99-generic
          system: Linux
         version: Ubuntu 18.04 bionic
```
</details>

**Comment by mchugh19** [comment]
@onionka Unfortunately, this appears to be a bug that is present in the v3000 release but it has been corrected in the master branch, and will be in future salt releases. 

You can backport the fixed version from 
https://raw.githubusercontent.com/saltstack/salt/master/salt/modules/saltcheck.py
and override the version shipped in v3000 by copying it into your `states/_modules` as described in https://docs.saltstack.com/en/latest/ref/states/writing.html#using-custom-state-modules

Additionally, the line `assertion: assertContains` should probably read `assertion: assertIn`
