### ISSUE TITLE
Saltstack's service will produce a file with jobID as the file name in the proc directory of the minion terminal after each issue of the task. This file will be deleted after a period of time. I want to know what is the mechanism of file deletion

### ISSUE THREAD

**Issue by hongwuyuan** [saltstack/salt#57486]
Saltstack's service will produce a file with jobID as the file name in the proc directory of the minion terminal after each issue of the task. This file will be deleted after a period of time. I want to know what is the mechanism of file deletion

**Comment by DmitryKuzmenko** [comment]
This file is being created right before the job is starting it's execution.
Minion removes the file in the very beginning of the returning the job results to master when the job is done.
I can provide more details if needed. Feel free to ask.

**Comment by hongwuyuan** [comment]
If I send a command like 'ping 127.0.0.1' on the proxy side, which can never be executed, will the files under the proc on the minion side disappear? Currently, I test that if I kill the process executing the task minion, I will delete all the files under the proc within 1 hour, during which I do no other tasks. Is there a mechanism similar to the timing task to periodically delete proc files below

**Comment by hongwuyuan** [comment]
The files under cache / salt / minion / proc / of minion will be deleted automatically every hour, even if the minion task is still in progress. I want to know if this is the definition, or can I delete files of non running tasks?

**Comment by hongwuyuan** [comment]
Now I have a problem. I will execute the command like "Ping 127.0.0.1, tail - f file" on the master side to the minion side. This command will be executed forever. I need to kill these processes. I will kill them through kill_ The job method can't kill all the processes and their subprocesses executing the task. I wrote a script to kill the process tree, but the first step of my script is to read the file corresponding to the jobid under proc. If the file disappears, my function can't be realized

**Comment by DmitryKuzmenko** [comment]
Yes, this is a bug. Minion removes the proc file  only if the job is done. If you kill it the proc file is still there forever.

**Comment by DmitryKuzmenko** [comment]
The temporary workaround could be running `saltutil.find_job` for each file in the `prooc` dir to determine is it alive.
```bash
$ for f in /var/cache/salt/minion/proc/*; do f=$(basename $f); salt * saltutil.find_job $f; done
```

**Comment by hongwuyuan** [comment]
I found a bug. In line 108 of salt/utils/minion.py, there is no return value when calling the _check_cmdline method, causing the following judgment error
![log](https://user-images.githubusercontent.com/39953293/83422548-47657780-a45c-11ea-9abf-d77b02b4ab0a.png)

**Comment by hongwuyuan** [comment]
#This is my code for printing the log
def _read_proc_file(path, opts):
    '''
    Return a dict of JID metadata, or None
    '''
    serial = salt.payload.Serial(opts)
    current_thread = threading.currentThread().name
    pid = os.getpid()
    with salt.utils.files.fopen(path, 'rb') as fp_:
        buf = fp_.read()
        fp_.close()
        if buf:
            data = serial.loads(buf)
        else:
            # Proc file is empty, remove
            try:
                os.remove(path)
            except IOError:
                log.debug('Unable to remove proc file %s.', path)
            return None
    if not isinstance(data, dict):
        # Invalid serial object
        return None
    if not salt.utils.process.os_is_running(data['pid']):
        # The process is no longer running, clear out the file and
        # continue
        try:
            os.remove(path)
        except IOError:
            log.debug('Unable to remove proc file %s.', path)
        return None
    if opts.get('multiprocessing'):
        if data.get('pid') == pid:
            return None
    else:
        if data.get('pid') != pid:
            try:
                os.remove(path)
            except IOError:
                log.debug('Unable to remove proc file %s.', path)
            return None
        if data.get('jid') == current_thread:
            return None
        if not data.get('jid') in [x.name for x in threading.enumerate()]:
            try:
                os.remove(path)
            except IOError:
                log.debug('Unable to remove proc file %s.', path)
            return None

    tmp =  _check_cmdline(data)
    log.warning('fan hui jie guo is %s',str(tmp))
    if not _check_cmdline(data):
        pid = data.get('pid')
        if pid:
            log.warning(
                'PID %s exists but does not appear to be a salt process.', pid
            )
        try:
            os.remove(path)
            log.warning("remove %s",path)
        except IOError:
            log.debug('Unable to remove proc file %s.', path)
        return None
    return data


def _check_cmdline(data):
    '''
    In some cases where there are an insane number of processes being created
    on a system a PID can get recycled or assigned to a non-Salt process.
    On Linux this fn checks to make sure the PID we are checking on is actually
    a Salt process.

    For non-Linux systems we punt and just return True
    '''
    if not salt.utils.platform.is_linux():
        return True
    pid = data.get('pid')
    log.warning(
                '_check_cmdline PID is %s ', pid
            )
    if not pid:
        log.warning('not pid')
        return False
    if not os.path.isdir('/proc'):
        log.warning('os.path.isdir proc is False')
        return True
    path = os.path.join('/proc/{0}/cmdline'.format(pid))
    if not os.path.isfile(path):
        log.warning('os.path.isfile proc.pid.cmdline is False')
        return False
    try:
        with salt.utils.files.fopen(path, 'rb') as fp_:
            log.warning('fopen path is {0} '.format(path))
            if b'salt' in fp_.read():
                log.waring('salt in fp_read')
                return True
    except (OSError, IOError):
        log.warning('fopen error False')
        return False

**Comment by hongwuyuan** [comment]
This is my print log，_check_cmdline() method return None,It should be True or False

2020-06-01 22:35:54,736 [salt.utils.minion                                                            :141 ][WARNING ][11312] _check_cmdline PID is 21629 
2020-06-01 22:35:54,737 [salt.utils.minion                                                            :155 ][WARNING ][11312] fopen path is /proc/21629/cmdline 
2020-06-01 22:35:54,737 [salt.utils.minion                                                            :112 ][WARNING ][11312] fan hui jie guo is None
2020-06-01 22:35:54,738 [salt.utils.minion                                                            :141 ][WARNING ][11312] _check_cmdline PID is 21629 
2020-06-01 22:35:54,738 [salt.utils.minion                                                            :155 ][WARNING ][11312] fopen path is /proc/21629/cmdline 
2020-06-01 22:35:54,738 [salt.utils.minion                                                            :117 ][WARNING ][11312] PID 21629 exists but does not appear to be a salt process.
2020-06-01 22:35:54,739 [salt.utils.minion                                                            :121 ][WARNING ][11312] remove /data/app/cje/config/cache/salt/minion/proc/241590a34bd04c8d8a8f58907072dfb3

**Comment by hongwuyuan** [comment]
Hello, I still have a question. The method _read_proc_file() will be executed once an hour, and more files below the proc will be detected. Could you please tell me where the specified code of this place is

**Comment by hongwuyuan** [comment]
When I opened the /proc/process/cmdline file, I was surprised to find it, but I executed vim normally on the terminal

with salt.utils.files.fopen('/proc/18761/cmdline', 'rb') as fp_:
...     print(fp_.read())
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/app/cje/cje-automation/lib/python3.7/site-packages/salt/utils/files.py", line 399, in fopen
    f_handle = open(*args, **kwargs)  # pylint: disable=resource-leakage
FileNotFoundError: [Errno 2] No such file or directory: '/proc/18761/cmdline'

**Comment by hongwuyuan** [comment]
I finally found out the reason, because we changed the name of salt by secondary development, which resulted in the failure of judgment in "if b'salt' in data:" judgment, so I suggest adding "if b'salt' in data or b'minion' in data:" on this judgment.


>>> with salt.utils.files.fopen('/proc/31345/cmdline', 'rb') as fp_:
...     data = fp_.read()
... 
>>> data
b'/data/app/cje/cje-automation/bin/python3\x00/data/app/cje/cje-automation/bin/cje-minion\x00-c\x00/data/app/cje/config\x00-d\x00'
>>> if b'salt' in data:
...     print('salt')
... 
>>> if b'minion' in data:
...     print('minion')
... 
minion

**Comment by DmitryKuzmenko** [comment]
@hongwuyuan good catch! Thank you for analyzing this. The proposed change sounds good to me. Will you create a PR with the fix?
