### ISSUE TITLE
[BUG] salt.util not finding rabbitmq module user_exists

### ISSUE THREAD

**Issue by mforde84** [saltstack/salt#57495]
**Description**
I'm experiencing an issue with salt utils being unable to find the rabbitmq.user_exists module

**Setup**

part of the state init
```
{% set admin_user = salt['pillar.get']('rabbitmq:server:admin:name') %}   
     renders to some admin username
{% if salt['rabbitmq.user_exists'](admin_user) != True %}     <======================
     this is where the render fails on the "rabbitmq.user_exists" call
```

Stating the rabbitmq role generates following:
```
salt-call state.apply states.rabbitmq
[ERROR   ] Rendering exception occurred
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 169, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 404, in render_jinja_tmpl
    buf=tmplstr)
SaltRenderError: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'rabbitmq.user_exists'
[CRITICAL] Rendering SLS 'base:rabbitmq.RedHat.server.vhost' failed: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'rabbitmq.user_exists'
[ERROR   ] Rendering exception occurred
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 169, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 404, in render_jinja_tmpl
    buf=tmplstr)
SaltRenderError: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'rabbitmq.user_exists'
[CRITICAL] Rendering SLS 'base:rabbitmq.RedHat.server.user' failed: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'rabbitmq.user_exists'
local:
    Data failed to compile:
----------
    Rendering SLS 'base:rabbitmq.RedHat.server.vhost' failed: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'rabbitmq.user_exists'
----------
    Rendering SLS 'base:rabbitmq.RedHat.server.user' failed: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'rabbitmq.user_exists'

```
**Steps to Reproduce the behavior**
Can only reproduce with jinja render. With CLI, the module works fine:
```
root -> salt-call rabbitmq.user_exists

Passed invalid arguments: user_exists() takes at least 1 argument (0 given).

Usage:

    Return whether the user exists based on rabbitmqctl list_users.

    CLI Example:

    .. code-block:: bash

        salt '*' rabbitmq.user_exists rabbit_user
```
**Expected behavior**
Jinja should make a module call to rabbitmq.user_exists and check if user exists

**Versions Report**
MINION:
root -> salt-call --versions-report
Salt Version:
           Salt: 2019.2.2
 
Dependency Versions:
           cffi: 1.14.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: 2.6.1
   pycryptodome: 3.9.7
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  7 2019, 00:51:29)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.7.1908 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1062.18.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.7.1908 Core
```
MASTER:
```Salt Version:
           Salt: 3000.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: 0.31.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  7 2019, 00:51:29)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.6
 
System Versions:
           dist: centos 7.7.1908 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1062.12.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.7.1908 Core
```

**Comment by sagetherage** [comment]
@mforde84 Python 2 is no longer supported -- have you been able to upgrade to a supported version of Python 3.6+ and still seeing this issue? Also, you have upgraded to Salt version 3000.9? previous point versions are vulnerable.

**Comment by sagetherage** [comment]
@mforde84 Python 2 is no longer supported -- have you been able to upgrade to a supported version of Python 3.6+ and still seeing this issue? Also, you have upgraded to a supported Salt version?

Reviewed in Grooming 2021-JUL-19 considering closing

**Comment by Ch3LL** [comment]
Closing due to inactivity. If this is still an issue on the latest version of Salt please open a new issue with the details and the requested information.
