### ISSUE TITLE
haproxyconn Module : typeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by Nerigal** [saltstack/salt#57522]
**Setup**
haproxyctl-0.3.1 from `pip3 install haproxyctl`

```
Salt Version:
           Salt: 3000.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.1
        libgit2: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Apr  2 2020, 13:34:55)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 15.3.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.8.2003 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1127.8.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.8.2003 Core
```

**Steps to Reproduce the behavior**

`salt-call --local haproxy.show_backends -l debug`

```
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[WARNING ] The 'environment' minion config option has been renamed to 'saltenv'. Using dev as the 'saltenv' config value.
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Loading static grains from /etc/salt/grains
[DEBUG   ] LazyLoaded zfs.is_supported
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] pillarenv 'dev' not found in the configured pillar environments (base)
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded haproxy.show_backends
[DEBUG   ] LazyLoaded direct_call.execute

Passed invalid arguments: a bytes-like object is required, not 'str'.

Usage:

    Show HaProxy Backends

    socket
        haproxy stats socket, default ``/var/run/haproxy.sock``

    CLI Example:

    .. code-block:: bash

        salt '*' haproxy.show_backends
    
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/cli/caller.py", line 218, in call
    ret['return'] = self.minion.executors[fname](self.opts, data, func, args, kwargs)
  File "/usr/lib/python3.6/site-packages/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/modules/haproxyconn.py", line 373, in show_backends
    return ha_conn.sendCmd(ha_cmd)
  File "/usr/local/lib/python3.6/site-packages/haproxy/conn.py", line 33, in sendCmd
    self.sock.send(cmd.getCmd())
TypeError: a bytes-like object is required, not 'str'
```

**Comment by dmurphy18** [comment]
@Nerigal The last commit on the haproxyctl was 'Latest commit 8a10db7 on Aug 24, 2015'
Are you sure that this module is compatible with Python 3.6 which you are using on Redhat 7, since this appears to be a bytes vs str usage issue, typically not an issue in Py 2.7 but not in Python 3.

Noting that support for Python 3 was released in May 2015, but still quite some time ago, Py 3.4 and Py 3.5 where active then, but Py 3.4 is EOL'd 

Noting that the error is occurring in haproxy code

**Comment by Nerigal** [comment]
it is the version installed from `pip3 install haproxyctl`
haproxyctl-0.3.1 

and yes i figured that the version on the repo work fine but the pip version is still broken with the  encoding of `cmd.getCmd()`

**Comment by Nerigal** [comment]
Also, i say here because i dont know where but in the official documentation 
there is no mention on what are and how to install the requirements to make `salt.modules.haproxyconn` work properly 

https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.haproxyconn.html#module-salt.modules.haproxyconn

**Comment by dmurphy18** [comment]
@Nerigal You state it is pip3 installed, then it is not from CentOS 7 haproxyctl-0.3.1 since it will have been installed from PyPI, and you then state that the pip version is broken.

SaltStack is not in control of haproxyctl especially the version installed from PyPi. You can log the error with upstream for haproxyctl.

As for haproxyctl-0.3.1, I fail to find that package on either Centos 7 or Redhat / Fedora sites when searching for it, http://rpms.remirepo.net/rpmphp/zoom.php?rpm=haproxy and http://rpms.remirepo.net/rpmphp/zoom.php?rpm=haproxyctl

Lastly SaltStack only packages a limit amount of modules when creating a package for a platform, additionally functionality can be pip installed from PyPi. This is done in interest to reduce the size of packages delivered to users with the packages containing the functionality that most users typically use.

**Comment by dmurphy18** [comment]
I expect Ubuntu 20.04 version is more up to date and functions correctly with Python 3 since they are shipping https://packages.ubuntu.com/focal/haproxyctl v1.4.3-1 (Debian versioning)

it’s not spelled out that you have to install it yourself, but on the top of any module documentation that has 3rd party deps it says something to that effect.

**Comment by Nerigal** [comment]
i don't see anything about that here 

https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.haproxyconn.html#module-salt.modules.haproxyconn

**Comment by dmurphy18** [comment]
```
it’s not spelled out that you have to install it yourself,
```
Usually it says it for 3rd party deps, but not in current documentation.  SaltStack has recently hired new documentation writers and they going through the documentation for correction, errors and Python 2 specific items. I shall add this to their list of fixes

@saltstack/docs-working-group  Missing 3rd party deps requiring pip install for the haproxy module.
@Nerigal You need to file an upstream issue with haproxyctl to have it fix it's utf-8 handling

**Comment by Nerigal** [comment]
@dmurphy18 ok thank you

**Comment by OrangeDog** [comment]
https://packages.ubuntu.com/focal/haproxyctl is a CLI tool written in Ruby, not a Python package.

As @gtmanfred appears to be the author of `haproxyconn`, can they confirm what the dependency was supposed to be?

If it was https://pypi.org/project/haproxyctl/ then there's probably no chance of any maintenance, and the salt module is going to need re-writing or removing.

**Comment by dmurphy18** [comment]
This might be a good candidate for salt extensions
