### ISSUE TITLE
[BUG] Empty `master:` minion setting floods logs with stack traces

### ISSUE THREAD

**Issue by boltronics** [saltstack/salt#57526]
**Description**
I deployed a Salt minion configuration update to a subnet of minions. Unfortunately the value of `master:` was missing from pillar for some of the minions, so the Jinja template left the `master:` field empty.

This caused the following trace to be continuously spammed to the logs:
```
020-06-02 18:58:48,128 [salt.minion      :1050][CRITICAL][2702] Unexpected error while connecting to None
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1027, in _connect_minion
    yield minion.connect_master(failed=failed)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1225, in connect_master
    master, self.pub_channel = yield self.eval_master(self.opts, self.timeout, self.safe, failed)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, 2020-06-02 18:58:48,142 [salt.minion      :1050][CRITICAL][2702] Unexpected error while connecting to None
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1027, in _connect_minion
    yield minion.connect_master(failed=failed)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1225, in connect_master
    master, self.pub_channel = yield self.eval_master(self.opts, self.timeout, self.safe, failed)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 230, in wrapper
    yielded = next(result)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 733, in eval_master
    opts.update(prep_ip_port(opts))
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 260, in prep_ip_port
    host, port = parse_host_port(opts['master'])
  File "/usr/lib/python2.7/dist-packages/salt/utils/network.py", line 1979, in parse_host_port
    _s_ = host_port[:]
TypeError: 'NoneType' object has no attribute '__getitem__'
2020-06-02 18:58:48,144 [salt.minion      :1050][CRITICAL][2702] Unexpected error while connecting to None
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1027, in _connect_minion
    yield minion.connect_master(failed=failed)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1225, in connect_master
    master, self.pub_channel = yield self.eval_master(self.opts, self.timeout, self.safe, failed)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 230, in wrapper
    yielded = next(result)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 733, in eval_master
    opts.update(prep_ip_port(opts))
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 260, in prep_ip_port
    host, port = parse_host_port(opts['master'])
  File "/usr/lib/python2.7/dist-packages/salt/utils/network.py", line 1979, in parse_host_port
    _s_ = host_port[:]
TypeError: 'NoneType' object has no attribute '__getitem__'
```
It was spammed so frequently that all hosts affected by this ran out of disk space before I got around to correcting the problem, as the logs quickly grew to gigabytes in size.

**Setup**
The complete minion configuration ended up looking like this:
```
# grep -v '^#' /etc/salt/minion
grains:
  account: company-account
  management: salt
  provider: ec2
hash_type: sha256
id: some-minion-id.internal
log_level: info
master: 

# grep -vh '^#' /etc/salt/minion.d/*
schedule:
  __mine_interval: {enabled: true, function: mine.update, jid_include: true, maxrunning: 2,
    minutes: 60, return_job: false, run_on_start: true}

startup_states: sls

sls_list:
  - mine-update.ssh_fingerprint

use_superseded:
  - module.run
# 
```

**Steps to Reproduce the behavior**
Remove the value from `master:` on the minion and restart.

**Expected behavior**
A warning in the log (just once after launching, with no stack trace), with Salt falling back to the default hostname of `salt` and otherwise behaving as per usual.

**Versions Report**
```
salt --versions-report
Salt Version:
           Salt: 2019.2.5
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.24.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Sep 26 2018, 18:42:22)
   python-gnupg: 0.3.9
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.12 
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-11-amd64
         system: Linux
        version: debian 9.12 
 
```

**Comment by boltronics** [comment]
To highlight the severity, here is an example from one of the affected hosts that was out of space:
```
root@ip-172-29-83-58:/var/log# ls -lh daemon*
-rw-r----- 1 root adm 3.9G Jun  2 20:30 daemon.log
-rw-r----- 1 root adm 713K Jun  1 16:14 daemon.log.1
-rw-r----- 1 root adm 100K May 24 16:15 daemon.log.2.gz
-rw-r----- 1 root adm 137K May 18 16:22 daemon.log.3.gz
-rw-r----- 1 root adm 121K May 10 16:22 daemon.log.4.gz
root@ip-172-29-83-58:/var/log# 
```
However I think the fix will be easy.

**Comment by dmurphy18** [comment]
@boltronics The minion configuration is being written from pillar information in your application, and some of the minion's are failing to read the pillar information correctly and thus their configuration lacks the master: term.  Am I understanding the issue correctly ?

If so can you perhaps include an example of the configuration, pillars, top file, etc to allow understanding of the problem.  For example: does the top file have some globbing to remove some of the minions from the pillar information.  And yes pulling master from a minion configuration file will produce errors. If you can also explain how mine is being used to create the pillar information, it would be helpful.

**Comment by boltronics** [comment]
@dmurphy18 To put it simply, there was a pillar mis-configuration resulting in a number of our hosts ending up with a minion config that had `master:` in their config, without a value that would normally follow when that setting is used. If you need more config info than that, you're probably misunderstanding the issue.

Normally I believe the minion would default to "salt" as a master hostname if that key is not set, but in this case it treated the default as None - which is correct from the eyes a pure YAML parser, but doesn't make sense in the context of what Salt uses this key for.

Salt's config parser should have detected this as an obvious error when parsing (either failing to start or reload the salt-minion daemon with a clear error message in the log, or setting "salt" as the default when a value of None is found), but instead Salt mishandled this situation in the worst possible way, resulting in downtime for a bunch of hosts.

Normally Salt is not a critical component of our infrastructure, so even if the minions all died, that would have been an acceptable outcome - a minor inconvenience. Thankfully, this all happened in our staging environment.

Adding sanity checking to the config parser is all that needs to be done to prevent anyone else having hosts completely taken out by such a simple and obvious mistake. It would also be worth adding similar checks to other config options as well, as if the main config option doesn't even have validation checking to check for a string value, I would imagine most don't have input checks.

**Comment by waynew** [comment]
I would consider this a feature request. It's expected that you either provide a valid master, or don't and we set a default.

Defining your master as undefined is an undefined behavior, and clearly in nearly a decade it's never been something that's come up, and definitely not a common occurence.

**Comment by boltronics** [comment]
Not reported at least. I wouldn't consider the lack of input validation a feature request, especially when consequences are so dire... but we can agree to disagree. It's your project.

**Comment by dmurphy18** [comment]
Closing this as operating as expected, however a PR (Feature Request) adding input validation for a master which is undefined, would definitely be considered.

Please feel free to reopen this issue if unsatisfied with this answer
