### ISSUE TITLE
Flaky test - integration.pillar.test_git_pillar.TestGitPythonHTTP setUpClass

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#57552]
```
Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/support/gitfs.py", line 408, in setUpClass
    check_port=cls.nginx_port,
  File "/tmp/kitchen/testing/.nox/runtests-parametrized-3-coverage-true-crypto-pycryptodome-transport-zeromq/lib/python3.6/site-packages/saltfactories/utils/processes/helpers.py", line 314, in start_daemon
    exitcode=result.exitcode,
saltfactories.exceptions.ProcessNotStarted: [Nginx] The <NginxDaemon display_name='nginx'> has failed to confirm running status after 3 attempts, which took 5.30 seconds
 Exitcode: 1
 Process Output:
   >>>>> STDERR >>>>>
nginx: [emerg] bind() to 0.0.0.0:49342 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:49342 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:49342 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:49342 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:49342 failed (98: Address already in use)
nginx: [emerg] still could not bind()

   <<<<< STDERR <<<<<
```

**Comment by Ch3LL** [comment]
Have not seen this fail in a while.
