### ISSUE TITLE
[BUG] Acme state fails on first run, succeeds on every other

### ISSUE THREAD

**Issue by schorsch3000** [saltstack/salt#57562]
**Description**
The Acme-state fails with an exception on the first run anfter cerbot runs successfully

**Setup**
```'{{grains["acme"]["fqdn"]}}':
  acme.cert:
    - name: '{{grains["acme"]["fqdn"]}}'
    - certname: '{{grains["acme"]["fqdn"]}}'
    - email: <email>
    - webroot: /var/www/acme/
    - renew: 14
    - test_cert: {{grains['acme']['test_cert']}}
    - fire_event: acme/'{{grains["acme"]["fqdn"]}}'
    - onchanges_in:
      - cmd: reload-nginx
```
Note: nginx is configured to server `/var/www/acme/` if the path starts with -well-known.
Cerbot runs successfully and is able to obtain a certificate

**Steps to Reproduce the behavior**
logs from `salt-call`
```
[INFO    ] Executing command '/usr/bin/certbot certonly --non-interactive --agree-tos --cert-name <domain> --test-cert --authenticator webroot --webroot-path /var/www/acme/ --email <email> --domains <domain>' in directory '/root'
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/state.py", line 1981, in call
    **cdata['kwargs'])
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1977, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/states/acme.py", line 141, in cert
    ret['changes'] = salt.utils.dictdiffer.deep_diff(current_certificate, new_certificate)
  File "/usr/lib/python3/dist-packages/salt/utils/dictdiffer.py", line 54, in deep_diff
    new = copy.deepcopy(new)
  File "/usr/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.7/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle dict_keys objects
```

**Expected behavior**
I expected the acme state to work on the first run.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3000.3-1-gba9f944d36
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.8.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.3 (default, Dec 20 2019, 18:57:59)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: debian 10.4 
         locale: UTF-8
        machine: x86_64
        release: 4.19.0-9-amd64
         system: Linux
        version: debian 10.4 
```
</details>

**Additional context**
To reset the starte clearing /etc/letsencrypt is needed.
It seems that the check that tests if the certificate is renewed fails if there is no certificate to check against.

**Comment by dmurphy18** [comment]
@schorsch3000 Can you re-run the issue against a released version of Salt.  Running issues on non-released versions of Salt is problematic since those versions are in flux and unreliable as a solid basis for investigation.

**Comment by dmurphy18** [comment]
Closing this since duplicate, thanks for catching that @OrangeDog
