### ISSUE TITLE
[BUG] "ValueError: insecure string pickle" in s3fs cache read should be handled

### ISSUE THREAD

**Issue by oeuftete** [saltstack/salt#57565]
**Description**

Occasional errors have been observed loading the s3fs cache.  I've investigated a handful of theories on what might be happening in the particular customer environment, but can not reproduce.  However, it seems appropriate in this case to return no data from the cache lookup and continue, as is done with several other exceptions: https://github.com/saltstack/salt/blob/9e1caa2d4b6fd49411a18eb0a33568017b72dad6/salt/fileserver/s3fs.py#L596-L607

```
Exception occurred in runner state.orchestrate: Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 382, in _low
data['return'] = self.functions[fun](*args, **kwargs)
File "/usr/lib/python2.7/site-packages/salt/runners/state.py", line 88, in orchestrate
orchestration_jid=orchestration_jid)
File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 1098, in sls
initial_pillar=_get_initial_pillar(opts))
File "/usr/lib/python2.7/site-packages/salt/state.py", line 3846, in __init__
BaseHighState.__init__(self, opts)
File "/usr/lib/python2.7/site-packages/salt/state.py", line 2721, in __init__
self.avail = self.__gather_avail()
File "/usr/lib/python2.7/site-packages/salt/state.py", line 2730, in __gather_avail
for saltenv in self._get_envs():
File "/usr/lib/python2.7/site-packages/salt/state.py", line 2791, in _get_envs
client_envs = self.client.envs()
File "/usr/lib/python2.7/site-packages/salt/fileclient.py", line 1331, in envs
return self.channel.send(load)
File "/usr/lib/python2.7/site-packages/salt/fileserver/__init__.py", line 892, in send
return self.fs.envs()
File "/usr/lib/python2.7/site-packages/salt/fileserver/__init__.py", line 488, in envs
ret.update(self.servers[fstr](**kwargs))
File "/usr/lib/python2.7/site-packages/salt/fileserver/s3fs.py", line 93, in envs
metadata = _init()
File "/usr/lib/python2.7/site-packages/salt/fileserver/s3fs.py", line 354, in _init
metadata = _read_buckets_cache_file(cache_file)
File "/usr/lib/python2.7/site-packages/salt/fileserver/s3fs.py", line 553, in _read_buckets_cache_file
data = pickle.load(fp_)
File "/usr/lib64/python2.7/pickle.py", line 1378, in load
return Unpickler(file).load()
File "/usr/lib64/python2.7/pickle.py", line 858, in load
dispatch[key](self)
File "/usr/lib64/python2.7/pickle.py", line 966, in load_string
raise ValueError, "insecure string pickle"
ValueError: insecure string pickle
```

**Setup**

Use s3fs.

**Steps to Reproduce the behavior**

Not easily reproducible.

**Expected behavior**

Whatever operation that was going on continues.

**Comment by oeuftete** [comment]
ZD-5095

**Comment by sagetherage** [comment]
Likely we shouldn't write this file as a pickled object, we are accepting an import error is a security issue.
