### ISSUE TITLE
[BUG] [documentation] salt.virt module dependencies are not complete

### ISSUE THREAD

**Issue by q1x** [saltstack/salt#57641]
**Description**
Today I found out that the virt module is dependent on `qemu-img` (it calls it through `subprocess.Popen()`. It is however not mentioned in the 'depends' section in the documentation. https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.virt.html

Furthermore, the command run uses the `-U` flag, which is not available in older versions of `qemu-img`. Debian 9 (still LTS) ships an unsupported version, so I think the minimal version should be explicitly be mentioned. 

**Steps to Reproduce the behavior**
Run salt `virt.get_disk`, `virt.vm_info`, etc. against a Debian9 host.

**Expected behavior**
Minimal `qemu-img` version should be documented and possibly checked for during module load.

**Screenshots**
```
root@iso-host01:/srv/salt-images# salt-call virt.get_disks test42
info: invalid option -- 'U'
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    load_entry_point('salt==3000.3', 'console_scripts', 'salt-call')()
  File "/usr/lib/python3/dist-packages/salt/scripts.py", line 445, in salt_call
    client.run()
  File "/usr/lib/python3/dist-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 119, in run
    ret = self.call()
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 218, in call
    ret['return'] = self.minion.executors[fname](self.opts, data, func, args, kwargs)
  File "/usr/lib/python3/dist-packages/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/modules/virt.py", line 2371, in get_disks
    disks = _get_disks(_get_domain(conn, vm_))
  File "/usr/lib/python3/dist-packages/salt/modules/virt.py", line 476, in _get_disks
    output = _parse_qemu_img_info(qemu_output)
  File "/usr/lib/python3/dist-packages/salt/modules/virt.py", line 298, in _parse_qemu_img_info
    raw_infos = salt.utils.json.loads(info)
  File "/usr/lib/python3/dist-packages/salt/utils/json.py", line 97, in loads
    return json_module.loads(s, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    load_entry_point('salt==3000.3', 'console_scripts', 'salt-call')()
  File "/usr/lib/python3/dist-packages/salt/scripts.py", line 445, in salt_call
    client.run()
  File "/usr/lib/python3/dist-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 119, in run
    ret = self.call()
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 218, in call
    ret['return'] = self.minion.executors[fname](self.opts, data, func, args, kwargs)
  File "/usr/lib/python3/dist-packages/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/modules/virt.py", line 2371, in get_disks
    disks = _get_disks(_get_domain(conn, vm_))
  File "/usr/lib/python3/dist-packages/salt/modules/virt.py", line 476, in _get_disks
    output = _parse_qemu_img_info(qemu_output)
  File "/usr/lib/python3/dist-packages/salt/modules/virt.py", line 298, in _parse_qemu_img_info
    raw_infos = salt.utils.json.loads(info)
  File "/usr/lib/python3/dist-packages/salt/utils/json.py", line 97, in loads
    return json_module.loads(s, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3000.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (default, Sep 27 2018, 17:25:39)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.12
         locale: UTF-8
        machine: x86_64
        release: 4.14.0-3-amd64
         system: Linux
        version: debian 9.12
```
</details>

**Additional context**
n/a

**Comment by frogunder** [comment]
@q1x Thank you for reporting this issue.
