### ISSUE TITLE
[BUG] [RC1 Sodium] Duplicate zipped custom module and custom module file throws uncaught exception

### ISSUE THREAD

**Issue by oeuftete** [saltstack/salt#57674]
**Description**

If a custom module is provided in the file roots as a zipped version and as a simple module file, `salt` will not run.

**Setup**

Add the same simple custom module as a zip file and a regular module file:

`/srv/salt/_modules/zd5292.py`:

```python
def ok():
    return 'ok'
```

`/srv/salt/_modules/zd5292.zip` (same content as above in `__init__.py`):

```text
# unzip -l /srv/salt/_modules/zd5292.zip 
Archive:  /srv/salt/_modules/zd5292.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  06-15-2020 16:23   zd5292/
       26  06-15-2020 16:23   zd5292/__init__.py
---------                     -------
       26                     2 files
```

Put these two files in a custom modules path, e.g. `/srv/salt/_modules`.

**Steps to Reproduce the behavior**

```
[root@master1 ~]# salt-run saltutil.sync_modules
- modules.zd5292
- modules.zd5292

[root@master1 ~]# salt '*' test.ping
Traceback (most recent call last):
  File "/usr/bin/salt", line 11, in <module>
    sys.exit(salt_main())
  File "/usr/lib/python3.6/site-packages/salt/scripts.py", line 559, in salt_main
    client.run()
  File "/usr/lib/python3.6/site-packages/salt/cli/salt.py", line 59, in run
    auto_reconnect=True,
  File "/usr/lib/python3.6/site-packages/salt/client/__init__.py", line 116, in get_local_client
    auto_reconnect=auto_reconnect,
  File "/usr/lib/python3.6/site-packages/salt/client/__init__.py", line 191, in __init__
    self.functions = salt.loader.minion_mods(self.opts, utils=self.utils)
  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 263, in minion_mods
    extra_module_dirs=utils.module_dirs if utils else None,
  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 1264, in __init__
    self._refresh_file_mapping()
  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 1470, in _refresh_file_mapping
    ext
ValueError: '.zip' is not in list
```
(Include debug logs if possible and relevant)

**Expected behavior**

An error should be raised about the collision; or maybe one should be preferred over the other (with a warning and backing documentation).

**Versions Report**
<details><summary>salt --versions-report</summary>

Originally seen in 2019.2.2, but reproduced in 3001rc1.

```
Salt Version:
           Salt: 3001rc1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.2
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: 3.9.7
         pygit2: Not Installed
         Python: 3.6.8 (default, Apr  2 2020, 13:34:55)
   python-gnupg: Not Installed
         PyYAML: 5.3.1
          PyZMQ: 19.0.1
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: centos 7 Core
         locale: UTF-8
        machine: x86_64
        release: 5.3.0-59-generic
         system: Linux
        version: CentOS Linux 7 Core
```
</details>

**Comment by oeuftete** [comment]
ZD-5292

**Comment by oeuftete** [comment]
I think the same thing would happen with `.pyx` if enabled?

https://github.com/saltstack/salt/blob/b95213ec903402f25c1e0aeb3990fe8452ab63ce/salt/loader.py#L1338-L1352

Either both of these need to also be appended to `self.suffix_order`, or maybe checked along with directories (the `""` extension) at:

https://github.com/saltstack/salt/blob/b95213ec903402f25c1e0aeb3990fe8452ab63ce/salt/loader.py#L1456

The latter sounds more correct to me.

**Comment by sagetherage** [comment]
For some reason this didn't get it's PR merged so it will be in the Magnesium release, moving and relabeling.
