### ISSUE TITLE
[BUG] Installation failed on Ubuntu 20.04 LTS arm64 (Raspberry Pi)

### ISSUE THREAD

**Issue by sjkummer** [saltstack/salt#57694]
**Description**
Salt minion installation fails on Ubuntu 20.04 (arm64 Raspberry Pi). But worked on earlier versions (Ubuntu 19.10).

**Setup**
`sudo sh bootstrap-salt.sh -D -x python3 git v3000.3`
Same behavior when using v3000

**Install Log**

```
ubuntu@ubuntu:~$ sudo sh bootstrap-salt.sh -D -x python3 git v3000.3

Installed Salt Version: 3000.3
Installed Salt Package Path: /usr/local/lib/python3.8/dist-packages/salt

 *  INFO: Running install_ubuntu_git_post()
 * DEBUG: Not overwriting /lib/systemd/system/salt-minion.service with /tmp/git/salt/pkg/salt-minion.service
enabled
 *  INFO: Running install_ubuntu_check_services()
 * DEBUG: Checking if service salt-minion is enabled
 * DEBUG: Service salt-minion is enabled
 *  INFO: Running install_ubuntu_restart_daemons()
 * DEBUG: Waiting 3 seconds for processes to settle before checking for them
 * DEBUG: There's systemd support while checking salt-minion
 *  INFO: Running daemons_running()
 * DEBUG: Waiting 3 seconds for processes to settle before checking for them
 * ERROR: salt-minion was not found running
 * ERROR: Failed to run daemons_running()!!!
nohup: ignoring input
Traceback (most recent call last):
  File "/usr/local/bin/salt-minion", line 8, in <module>
    sys.exit(salt_minion())
  File "/usr/local/lib/python3.8/dist-packages/salt/scripts.py", line 191, in salt_minion
    import salt.cli.daemons
  File "/usr/local/lib/python3.8/dist-packages/salt/cli/daemons.py", line 48, in <module>
    import salt.utils.parsers
  File "/usr/local/lib/python3.8/dist-packages/salt/utils/parsers.py", line 28, in <module>
    import salt.config as config
  File "/usr/local/lib/python3.8/dist-packages/salt/config/__init__.py", line 100, in <module>
    _DFLT_IPC_WBUFFER = _gather_buffer_space() * .5
  File "/usr/local/lib/python3.8/dist-packages/salt/config/__init__.py", line 89, in _gather_buffer_space
    import salt.grains.core
  File "/usr/local/lib/python3.8/dist-packages/salt/grains/core.py", line 40, in <module>
    from platform import _supported_dists
ImportError: cannot import name '_supported_dists' from 'platform' (/usr/lib/python3.8/platform.py)
 * DEBUG: Running salt-minion by hand outputs: 
 * DEBUG: /var/log/salt/minion does not exist. Can't cat its contents!
 * DEBUG: Running Processes:
 * DEBUG: USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  1.1  1.2 170812 11920 ?        Ss   07:13   2:09 /lib/systemd/systemd --system --deserialize 27
root           2  0.0  0.0      0     0 ?        S    07:13   0:00 [kthreadd]
root           3  0.0  0.0      0     0 ?        I<   07:13   0:00 [rcu_gp]
root           4  0.0  0.0      0     0 ?        I<   07:13   0:00 [rcu_par_gp]
root           8  0.0  0.0      0     0 ?        I<   07:13   0:00 [mm_percpu_wq]
root           9  0.0  0.0      0     0 ?        S    07:13   0:05 [ksoftirqd/0]
root          10  0.1  0.0      0     0 ?        I    07:13   0:18 [rcu_sched]
root          11  0.0  0.0      0     0 ?        S    07:13   0:00 [migration/0]
root          12  0.0  0.0      0     0 ?        S    07:13   0:00 [idle_inject/0]
root          14  0.0  0.0      0     0 ?        S    07:13   0:00 [cpuhp/0]
root          15  0.0  0.0      0     0 ?        S    07:13   0:00 [cpuhp/1]
root          16  0.0  0.0      0     0 ?        S    07:13   0:00 [idle_inject/1]
root          17  0.0  0.0      0     0 ?        S    07:13   0:00 [migration/1]
root          18  0.0  0.0      0     0 ?        S    07:13   0:05 [ksoftirqd/1]
root          21  0.0  0.0      0     0 ?        S    07:13   0:00 [cpuhp/2]
root          22  0.0  0.0      0     0 ?        S    07:13   0:00 [idle_inject/2]
root          23  0.0  0.0      0     0 ?        S    07:13   0:00 [migration/2]
root          24  0.0  0.0      0     0 ?        S    07:13   0:05 [ksoftirqd/2]
root          27  0.0  0.0      0     0 ?        S    07:13   0:00 [cpuhp/3]
root          28  0.0  0.0      0     0 ?        S    07:13   0:00 [idle_inject/3]
root          29  0.0  0.0      0     0 ?        S    07:13   0:00 [migration/3]
root          30  0.0  0.0      0     0 ?        S    07:13   0:05 [ksoftirqd/3]
root          33  0.0  0.0      0     0 ?        S    07:13   0:00 [kdevtmpfs]
root          34  0.0  0.0      0     0 ?        I<   07:13   0:00 [netns]
root          35  0.0  0.0      0     0 ?        S    07:13   0:00 [rcu_tasks_kthre]
root          39  0.0  0.0      0     0 ?        S    07:13   0:00 [kauditd]
root          40  0.0  0.0      0     0 ?        S    07:13   0:00 [khungtaskd]
root          41  0.0  0.0      0     0 ?        S    07:13   0:00 [oom_reaper]
root          42  0.0  0.0      0     0 ?        I<   07:13   0:00 [writeback]
root          43  0.0  0.0      0     0 ?        S    07:13   0:00 [kcompactd0]
root          44  0.0  0.0      0     0 ?        SN   07:13   0:00 [ksmd]
root         138  0.0  0.0      0     0 ?        I<   07:13   0:00 [kintegrityd]
root         139  0.0  0.0      0     0 ?        I<   07:13   0:00 [kblockd]
root         140  0.0  0.0      0     0 ?        I<   07:13   0:00 [blkcg_punt_bio]
root         141  0.0  0.0      0     0 ?        I<   07:13   0:00 [tpm_dev_wq]
root         142  0.0  0.0      0     0 ?        I<   07:13   0:00 [ata_sff]
root         143  0.0  0.0      0     0 ?        I<   07:13   0:00 [md]
root         144  0.0  0.0      0     0 ?        I<   07:13   0:00 [edac-poller]
root         145  0.0  0.0      0     0 ?        I<   07:13   0:00 [devfreq_wq]
root         146  0.0  0.0      0     0 ?        S    07:13   0:00 [watchdogd]
root         147  0.0  0.0      0     0 ?        S    07:13   0:08 [kswapd0]
root         148  0.0  0.0      0     0 ?        S    07:13   0:00 [ecryptfs-kthrea]
root         151  0.0  0.0      0     0 ?        I<   07:13   0:00 [kthrotld]
root         152  0.0  0.0      0     0 ?        I<   07:13   0:00 [dwc_otg]
root         153  0.0  0.0      0     0 ?        I<   07:13   0:00 [DWC Notificatio]
root         156  0.0  0.0      0     0 ?        S<   07:13   0:00 [vchiq-slot/0]
root         157  0.0  0.0      0     0 ?        S<   07:13   0:00 [vchiq-recy/0]
root         158  0.0  0.0      0     0 ?        S<   07:13   0:00 [vchiq-sync/0]
root         159  0.0  0.0      0     0 ?        I<   07:13   0:00 [ipv6_addrconf]
root         170  0.0  0.0      0     0 ?        I<   07:13   0:00 [kstrp]
root         174  0.0  0.0      0     0 ?        I<   07:13   0:00 [kworker/u9:0]
root         179  0.0  0.0      0     0 ?        I<   07:13   0:00 [cryptd]
root         243  0.0  0.0      0     0 ?        S    07:13   0:00 [spi0]
root         245  0.0  0.0      0     0 ?        I<   07:13   0:00 [charger_manager]
root         262  0.0  0.0      0     0 ?        I<   07:13   0:00 [mmc_complete]
root         569  0.0  0.0      0     0 ?        I<   07:13   0:00 [raid5wq]
root         623  0.0  0.0      0     0 ?        S    07:13   0:06 [jbd2/mmcblk0p2-]
root         624  0.0  0.0      0     0 ?        I<   07:13   0:00 [ext4-rsv-conver]
root         738  0.0  0.0      0     0 ?        S    07:13   0:00 [vchiq-keep/0]
root         740  0.0  0.0      0     0 ?        S<   07:13   0:00 [SMIO]
root         796  0.0  0.0      0     0 ?        I<   07:13   0:00 [cfg80211]
root         848  0.0  0.0      0     0 ?        I<   07:13   0:00 [brcmf_wq/mmc1:0]
root         849  0.0  0.0      0     0 ?        S    07:13   0:00 [brcmf_wdog/mmc1]
root        1058  0.0  0.0      0     0 ?        I<   07:13   0:00 [kaluad]
root        1059  0.0  0.0      0     0 ?        I<   07:13   0:00 [kmpath_rdacd]
root        1060  0.0  0.0      0     0 ?        I<   07:13   0:00 [kmpathd]
root        1061  0.0  0.0      0     0 ?        I<   07:13   0:00 [kmpath_handlerd]
root        1062  0.0  1.9 280212 17908 ?        SLsl 07:13   0:02 /sbin/multipathd -d -s
message+    1215  0.1  0.4   8476  3968 ?        Ss   07:14   0:18 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
root        1218  0.0  0.2  80776  2708 ?        Ssl  07:14   0:02 /usr/sbin/irqbalance --foreground
root        1219  0.0  0.8  29068  7940 ?        Ss   07:14   0:00 /usr/bin/python3 /usr/bin/networkd-dispatcher --run-startup-triggers
syslog      1221  0.0  0.3 221160  3232 ?        Ssl  07:14   0:00 /usr/sbin/rsyslogd -n -iNONE
root        1224  0.0  0.5  16516  5052 ?        Ss   07:14   0:07 /lib/systemd/systemd-logind
root        1225  0.0  0.3  12352  3424 ?        Ss   07:14   0:00 /sbin/wpa_supplicant -u -s -O /run/wpa_supplicant
root        1235  0.0  0.2   8328  2536 ?        Ss   07:14   0:00 /usr/sbin/cron -f
daemon      1243  0.0  0.2   3584  1936 ?        Ss   07:14   0:00 /usr/sbin/atd -f
root        1256  0.0  1.4 107780 13776 ?        Ssl  07:14   0:00 /usr/bin/python3 /usr/share/unattended-upgrades/unattended-upgrade-shutdown --wait-for-signal
root        1262  0.0  0.1   6828  1788 ttyS0    Ss+  07:14   0:00 /sbin/agetty -o -p -- \u --keep-baud 115200,38400,9600 ttyS0 vt220
root        1270  0.0  0.1   5304  1336 tty1     Ss+  07:14   0:00 /sbin/agetty -o -p -- \u --noclear tty1 linux
root        1295  0.0  0.6 232916  6228 ?        Ssl  07:14   0:00 /usr/lib/policykit-1/polkitd --no-debug
root        1530  0.0  0.0      0     0 ?        S<   07:14   0:00 [loop0]
root        2003  0.0  0.0      0     0 ?        S<   07:14   0:00 [loop1]
root        2085  0.0  0.0      0     0 ?        S<   07:14   0:00 [loop2]
root        2581  0.0  0.6  12180  5856 ?        Ss   07:15   0:00 sshd: /usr/sbin/sshd -D [listener] 0 of 10-100 startups
root        2715  0.0  0.0      0     0 ?        S<   07:15   0:00 [loop3]
root        3063  0.0  0.0      0     0 ?        S<   07:16   0:00 [loop4]
root        3091  0.5  1.8 1223004 17320 ?       Ssl  07:16   0:56 /usr/lib/snapd/snapd
root        3402  0.0  0.0      0     0 ?        S<   07:17   0:00 [loop5]
root        3718  0.0  0.0      0     0 ?        I<   07:19   0:04 [kworker/0:0H-kblockd]
root       24455  0.0  0.3  19688  3556 ?        Ss   07:36   0:00 /lib/systemd/systemd-udevd
root       24551  0.0  0.8 240572  7888 ?        Ssl  07:36   0:00 /usr/lib/accountsservice/accounts-daemon
systemd+   24854  0.0  0.5  26452  5124 ?        Ss   07:36   0:01 /lib/systemd/systemd-networkd
systemd+   24861  0.0  1.0  24068  9488 ?        Ss   07:36   0:01 /lib/systemd/systemd-resolved
root       24865  0.0  0.8  51128  7960 ?        S<s  07:36   0:01 /lib/systemd/systemd-journald
systemd+   24970  0.0  0.6  89744  5628 ?        Ssl  07:36   0:00 /lib/systemd/systemd-timesyncd
root       35607  0.0  0.1  50464  1408 ?        Ss   07:40   0:00 nginx: master process /usr/sbin/nginx -g daemon on; master_process on;
www-data   35608  0.0  0.4  51088  4192 ?        S    07:40   0:00 nginx: worker process
www-data   35609  0.0  0.4  51088  4320 ?        S    07:40   0:00 nginx: worker process
www-data   35610  0.0  0.4  51088  4320 ?        S    07:40   0:00 nginx: worker process
www-data   35611  0.0  0.4  51088  4320 ?        S    07:40   0:00 nginx: worker process
root       35748  0.0  0.7  15296  6548 ?        Ss   08:35   0:00 sshd: ubuntu [priv]
ubuntu     35752  0.0  0.9  19568  8812 ?        Ss   08:35   0:01 /lib/systemd/systemd --user
ubuntu     35753  0.0  0.7 172740  7368 ?        S    08:35   0:00 (sd-pam)
ubuntu     35854  0.1  0.4  15592  4140 ?        S    08:35   0:06 sshd: ubuntu@pts/0
ubuntu     35855  0.0  0.4   9656  4596 pts/0    Ss   08:35   0:00 -bash
root       36471  0.0  0.0      0     0 ?        I    08:37   0:05 [kworker/u8:3-events_power_efficient]
mongodb    36537  1.5  5.4 973344 50296 ?        Ssl  08:37   1:32 /usr/bin/mongod --unixSocketPrefix=/run/mongodb --config /etc/mongodb.conf
avahi      38876  0.0  0.3   7132  3368 ?        Ss   08:40   0:03 avahi-daemon: running [yourvcam.local]
avahi      38877  0.0  0.0   6868   332 ?        S    08:40   0:00 avahi-daemon: chroot helper
root       38935  0.0  0.0   1912   516 ?        S    08:40   0:00 bpfilter_umh
root       39698  0.0  0.0      0     0 ?        I<   08:41   0:01 [kworker/2:2H-kblockd]
root       46594  0.0  0.0      0     0 ?        I    09:35   0:00 [kworker/3:1-events_freezable]
root       48920  0.0  0.0      0     0 ?        I    09:45   0:01 [kworker/0:2-events]
root       49153  0.0  0.0      0     0 ?        I    09:50   0:00 [kworker/2:2-events]
root       49254  0.1  0.0      0     0 ?        I    09:54   0:02 [kworker/1:1-events]
root       49276  0.0  0.0      0     0 ?        I<   09:56   0:00 [kworker/3:1H-mmc_complete]
root       49393  0.0  0.4  12616  3936 pts/0    S+   09:59   0:00 sudo sh bootstrap-salt.sh -D -x python3 git v3000.3
root       49394  0.0  0.2   2840  2180 pts/0    S+   09:59   0:00 sh bootstrap-salt.sh -D -x python3 git v3000.3
root       49406  0.0  0.0   6660   452 pts/0    S+   09:59   0:00 tee /tmp/bootstrap-salt.log
root       50001  0.0  0.0      0     0 ?        I<   10:00   0:00 [kworker/1:2H-mmc_complete]
root       50043  0.0  0.0      0     0 ?        I    10:01   0:00 [kworker/u8:0-events_power_efficient]
root       51082  0.0  0.0      0     0 ?        I    10:05   0:00 [kworker/1:2-events]
root       51148  0.0  0.0      0     0 ?        I    10:07   0:00 [kworker/3:0-events]
root       51168  0.0  0.0      0     0 ?        I<   10:07   0:00 [kworker/3:2H]
root       51214  0.1  0.0      0     0 ?        I    10:08   0:00 [kworker/2:1-events]
root       51300  0.0  0.0      0     0 ?        I<   10:10   0:00 [kworker/2:1H-kblockd]
root       51328  0.0  0.0      0     0 ?        I<   10:10   0:00 [kworker/0:2H-kblockd]
root       51359  0.0  0.0      0     0 ?        I<   10:11   0:00 [kworker/1:1H]
root       51390  0.0  0.0      0     0 ?        I    10:12   0:00 [kworker/3:2-events]
root       51397  0.0  0.0      0     0 ?        I    10:12   0:00 [kworker/0:1-mm_percpu_wq]
root       51405  0.0  0.0      0     0 ?        I<   10:12   0:00 [kworker/3:0H]
root       51441  0.4  0.0      0     0 ?        I    10:14   0:00 [kworker/u8:1-events_power_efficient]
root       51458  0.0  0.0      0     0 ?        I    10:15   0:00 [kworker/2:0-events]
root       51460  0.2  0.0      0     0 ?        I    10:15   0:00 [kworker/u8:2-events_unbound]
root       51465  0.1  0.0      0     0 ?        I    10:15   0:00 [kworker/1:0-events]
root       51466  0.0  0.0      0     0 ?        I    10:15   0:00 [kworker/3:3-events]
root       51467  0.1  0.0      0     0 ?        I<   10:15   0:00 [kworker/2:0H-kblockd]
root       51468  0.0  0.0      0     0 ?        I<   10:16   0:00 [kworker/0:1H]
root       51480  0.0  0.0      0     0 ?        I<   10:16   0:00 [kworker/1:0H]
root       51552  0.0  0.0      0     0 ?        I    10:17   0:00 [kworker/0:0-events]
root       51560  0.0  0.2  10172  2772 pts/0    R+   10:17   0:00 ps auxwww
 * DEBUG: Cleaning up the Salt Temporary Git Repository
 * DEBUG: Removing the logging pipe /tmp/bootstrap-salt.logpipe
 * DEBUG: Removing the temporary apt error file /tmp/apt_error.aE2sB6
 * DEBUG: Killing logging pipe tee's with pid(s): 49406
```

```
ubuntu@ubuntu:~$ salt-minion
Traceback (most recent call last):
  File "/usr/local/bin/salt-minion", line 8, in <module>
    sys.exit(salt_minion())
  File "/usr/local/lib/python3.8/dist-packages/salt/scripts.py", line 191, in salt_minion
    import salt.cli.daemons
  File "/usr/local/lib/python3.8/dist-packages/salt/cli/daemons.py", line 48, in <module>
    import salt.utils.parsers
  File "/usr/local/lib/python3.8/dist-packages/salt/utils/parsers.py", line 28, in <module>
    import salt.config as config
  File "/usr/local/lib/python3.8/dist-packages/salt/config/__init__.py", line 100, in <module>
    _DFLT_IPC_WBUFFER = _gather_buffer_space() * .5
  File "/usr/local/lib/python3.8/dist-packages/salt/config/__init__.py", line 89, in _gather_buffer_space
    import salt.grains.core
  File "/usr/local/lib/python3.8/dist-packages/salt/grains/core.py", line 40, in <module>
    from platform import _supported_dists
ImportError: cannot import name '_supported_dists' from 'platform' (/usr/lib/python3.8/platform.py)
```

**Comment by xeacott** [comment]
Hi @sjkummer thanks for reporting. I'll ask if @dmurphy18 if he could look at this since probably has the most experience when it comes to building on a pi.

**Comment by dmurphy18** [comment]
Python 3.8 is supported with the about to be released Salt 3001. You could try the Release Candidate Salt 3001rc1 or wait a few hours and 3001 should be available later today.

**Comment by dmurphy18** [comment]
Actually the Raspbian 10 version of Salt 3001 is just pure Salt, hence noarch, you could probably take that and run it on Ubuntu 20.04 arm.  It is built on a Pi 3, for armhl but should work.

**Comment by sjkummer** [comment]
I can confirm that installing v3001 on Ubuntu 20.04 LTS arm64 was successful!

Thanks for your fast response.

**Comment by mrueg** [comment]
@sjkummer fyi I've filed https://github.com/saltstack/salt-pack-py3/issues/235 

@dmurphy18 do you know how I can get it to install through the repository? Or will only an install via dpkg work?

**Comment by sjkummer** [comment]
@mrueg I installed it using the bootstrap script:
```
curl -o bootstrap-salt.sh -L https://bootstrap.saltstack.com
sudo sh bootstrap-salt.sh -x python3 git v3001
```

**Comment by morph027** [comment]
I've added a comment to https://github.com/saltstack/salt-pack-py3/issues/235
