### ISSUE TITLE
[BUG] Trouble importing macro with gitfs and using saltenv

### ISSUE THREAD

**Issue by kkallday** [saltstack/salt#57709]
**Description**
I have a master config with two git remotes. My Salt state fails to render, when specifying `saltenv` because it can't find the sls file that contains the macro definition. The saltenv/branch exists in git remote 1, but not in git remote 2. The macro definition is in git remote 2. I can't find a configuration option in the doc that resolves this issue. Thanks in advance!

**Setup**
formulas/my-state/init.sls (in branch "my-branch"):
```
{% import 'my-macro.sls' as something %}

echo_hello:
  cmd.run:
    - name: "echo hello"
{{ something.my_test('sup') }}
```

src/formulas/my-macro.sls (in branch "master"):
```
{% macro my_test(msg) %}
my_test_echo_message:
  cmd.run:
    - name: "echo macro here"
{% endmacro %}
```

master config:
```
...
fileserver_backend:
    - gitfs

gitfs_provider: gitpython

gitfs_base: master

gitfs_remotes:
    - ssh://git@git.example.com/si/repo-1.git:
        - root: formulas
    - ssh://git@git.example.com/si/repo-2.git:
        - root: src/formulas
...
```

**Steps to Reproduce the behavior**
1. `salt "hostname of minion" state.apply my-state saltenv=my-branch`
1. Fails with:
```
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Popen(['git', 'version'], cwd=/root, universal_newlines=False, shell=None, istream=None)
[DEBUG   ] Popen(['git', 'version'], cwd=/root, universal_newlines=False, shell=None, istream=None)
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/master', u'2061ee26-c122-4eed-896c-2db2783e7f1a_master', u'tcp://127.0.0.1:4506', u'clear')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://127.0.0.1:4506
[DEBUG   ] Trying to connect to: tcp://127.0.0.1:4506
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/7a/7bf33707eb382634fff09b1a45307bb4d3ea15d35d42ef0096c605cb110798/.minions.p
[DEBUG   ] get_iter_returns for jid 20200618011624637423 sent to set(['ip-192-168-212-175.us-west-2.compute.internal']) will timeout at 01:16:29.646181
[DEBUG   ] jid 20200618011624637423 return from ip-192-168-212-175.us-west-2.compute.internal
[DEBUG   ] return event: {u'ip-192-168-212-175.us-west-2.compute.internal': {u'jid': u'20200618011624637423', u'retcode': 1, u'ret': [u'Rendering SLS \'my-branch:my-state/init.sls\' failed: Jinja error:my-macro.sls\nTraceback (most recent call last):\n  File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 394, in render_jinja_tmpl\n    output = template.render(**decoded_context)\n  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render\n    self.environment.handle_exception()\n  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception\n    reraise(*rewrite_traceback_stack(source=source))\n  File "/usr/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise\n    raise value.with_traceback(tb)\n  File "<template>", line 1, in top-level template code\n  File "/usr/lib/python3.6/site-packages/salt/utils/jinja.py", line 193, in get_source\n    raise TemplateNotFound(template)\njinja2.exceptions.TemplateNotFound: my-macro.sls\n\n; line 1\n\n---\n{% import \'my-macro.sls\' as something %}    <======================\n\nkk_test:\n  cmd.run:\n    - name: "echo hello"\n\n[...]\n---'], u'out': u'highstate'}}
[DEBUG   ] LazyLoaded highstate.output
ip-192-168-212-175.us-west-2.compute.internal:
    Data failed to compile:
----------
    Rendering SLS 'my-branch:my-state/init.sls' failed: Jinja error: my-macro.sls
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 394, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
  File "/usr/lib/python3.6/site-packages/salt/utils/jinja.py", line 193, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: my-macro.sls

; line 1

---
{% import 'my-macro.sls' as something %}    <======================

echo_hello:
  cmd.run:
    - name: "echo hello"
{{ something.my_test('sup') }}

[...]
---
[DEBUG   ] jid 20200618011624637423 found all minions set([u'ip-192-168-212-175.us-west-2.compute.internal'])
[DEBUG   ] Closing IPCMessageSubscriber instance
ERROR: Minions returned with non-zero exit code
```

**Expected behavior**
Although `my-branch` is not a branch on remote 2, I expected it to use the `master` branch and find the macro.

**Screenshots**
n/a

**Versions Report**

```
Salt Version:
           Salt: 3000.3

Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.6
      gitpython: 2.1.15
         Jinja2: 2.10
        libgit2: 0.26.0
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.2
         Python: 2.7.17 (default, Apr 15 2020, 17:20:14)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
          smmap: 3.0.4
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.19.105
         system: Linux
        version: Ubuntu 18.04 bionic
```
</details>

**Additional context**

**Comment by xeacott** [comment]
Thanks for the report @kkallday has your state files worked in the past at all, and now with an upgrade they're no longer working? 

All i can find is this doc: https://docs.saltstack.com/en/master/topics/tutorials/gitfs.html#tutorial-gitfs
and this doc: https://docs.saltstack.com/en/master/ref/pillar/all/salt.pillar.git_pillar.html#git-pillar-configuration

**Comment by whytewolf** [comment]
This is working as expected. 

saltenv locks an environment to ONLY that environment. and master is the base environment in your config. 

The branches are not what is important here but the mapping of environments. If you use saltenv you are locking those environments to only that environment.

**Comment by kkallday** [comment]
Got it. To summarize:
- I have a master config with repo-1 and repo-2
- The "my-branch" is only in repo-1
- `something.sls` in repo-1 imports a file that resides in repo-2
- If I `state.apply something saltenv=my-branch`, the failure is expected because "my-branch" does not exist in repo-2.

Is my understanding correct?

An additional question: I see the `fallback` feature [here](https://docs.saltstack.com/en/latest/topics/tutorials/gitfs.html#global-remotes). If I specify `fallback: master` for repo-2, would the import succeed? I haven't had any success using `fallback` because the master fails stating that there is no such option.

**Comment by kkallday** [comment]
@xeacott @whytewolf here is the output when I try to use `fallback: master`:

```
2020-06-23 05:27:48,189 [salt.utils.gitfs :317 ][CRITICAL][3282] Invalid gitfs configuration parameter 'fallback' in remote 'ssh://git@git.example.com/repo-1.git'. Valid parameters are: base, mountpoint, root, ssl_ver
ify, saltenv_whitelist, saltenv_blacklist, refspecs, disable_saltenv_mapping, ref_types, update_interval, all_saltenvs, name, saltenv. See the GitFS Walkthrough in the Salt documentation for further information.
2020-06-23 05:27:48,191 [salt.utils.lazy  :104 ][DEBUG   ][3282] LazyLoaded local_cache.prep_jid
2020-06-23 05:27:48,192 [salt.utils.event :736 ][DEBUG   ][3282] Sending event: tag = salt/run/20200623052746901351/ret; data = {u'fun_args': [], u'jid': u'20200623052746901351', u'return': u'Exception occurred in runner fileserver.file
_list: Traceback (most recent call last):\n  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 374, in low\n    data[\'return\'] = func(*args, **kwargs)\n  File "/usr/lib/python2.7/dist-packages/salt/runners/fileserver
.py", line 193, in file_list\n    return fileserver.file_list(load=load)\n  File "/usr/lib/python2.7/dist-packages/salt/utils/decorators/__init__.py", line 688, in wrapped\n    **salt.utils.data.decode_dict(kwargs)\n  File "/usr/lib/pyt
hon2.7/dist-packages/salt/fileserver/__init__.py", line 789, in file_list\n    ret.update(self.servers[fstr](load))\n  File "/usr/lib/python2.7/dist-packages/salt/fileserver/gitfs.py", line 185, in file_list\n    return _gitfs().file_li
st(load)\n  File "/usr/lib/python2.7/dist-packages/salt/fileserver/gitfs.py", line 84, in _gitfs\n    init_remotes=init_remotes)\n  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 2693, in __new__\n    init_remotes=ini
t_remotes)\n  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 2125, in __init__\n    global_only)\n  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 2183, in init_remotes\n    self.role\n  File "/usr/
lib/python2.7/dist-packages/salt/utils/gitfs.py", line 1106, in __init__\n    override_params, cache_root, role\n  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 320, in __init__\n    failhard(self.role)\n  File "/usr
/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 210, in failhard\n    raise FileserverConfigError(\'Failed to load {0}\'.format(role))\nFileserverConfigError: Failed to load gitfs\n', u'success': False, u'_stamp': '2020-06-23T05
:27:48.192367', u'user': u'root', u'fun': u'runner.fileserver.file_list'}
2020-06-23 05:27:48,193 [salt.utils.reactor:113 ][DEBUG   ][486] Gathering reactors for tag salt/run/20200623052746901351/ret
2020-06-23 05:27:48,193 [salt.utils.lazy  :104 ][DEBUG   ][3282] LazyLoaded nested.output
2020-06-23 05:27:48,194 [salt.client.mixins:418 ][INFO    ][3282] Runner completed: 20200623052746901351
2020-06-23 05:27:48,194 [salt.transport.ipc:363 ][DEBUG   ][3282] Closing IPCMessageClient instance
2020-06-23 05:27:48,194 [salt.runner      :296 ][DEBUG   ][3282] Runner return: Exception occurred in runner fileserver.file_list: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 374, in low
    data['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/runners/fileserver.py", line 193, in file_list
    return fileserver.file_list(load=load)
  File "/usr/lib/python2.7/dist-packages/salt/utils/decorators/__init__.py", line 688, in wrapped
    **salt.utils.data.decode_dict(kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/__init__.py", line 789, in file_list
    ret.update(self.servers[fstr](load))
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/gitfs.py", line 185, in file_list
    return _gitfs().file_list(load)
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/gitfs.py", line 84, in _gitfs
    init_remotes=init_remotes)
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 2693, in __new__
    init_remotes=init_remotes)
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 2125, in __init__
    global_only)
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 2183, in init_remotes
    self.role
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 1106, in __init__
    override_params, cache_root, role
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 320, in __init__
    failhard(self.role)
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 210, in failhard
    raise FileserverConfigError('Failed to load {0}'.format(role))
FileserverConfigError: Failed to load gitfs
```

Here is the relevant part of my master config:
```
fileserver_backend:
    - gitfs

gitfs_provider: gitpython
git_pillar_provider: gitpython

gitfs_base: master
git_pillar_base: master
git_pillar_branch: master

gitfs_remotes:
    - ssh://git@git.example.com/repo-1.git:
        - root: formulas
        - fallback: master
    - ssh://git@git.example.com/repo-2.git:
        - root: src/formulas
```

**Comment by whytewolf** [comment]
`fallback` was introduced in 3001. So isn't in 3000.3, this is what the line `New in version 2018.3.0: for all_saltenvs, 3001 for fallback` means. 

It didn't exist in salt before that. so it will cause that error. 

In the version you are in you would want `all_saltenvs` which can be used to have the single branch appear in all environments. 


The difference between the two is this. 

* `all_saltenvs`, a single branch covers all environments, regardless of other branches in git. introduced in 2018.2.0
* `fallback` System will try doing branch to env mapping but if it can't find the branch will fallback to the listed branch. Introduced in 3001.


If you need other branches in that repo, then yes you need `fallback` and have to update the master to 3001 to get it. Otherwise `all_saltenv` should be fine.

**Comment by kkallday** [comment]
Got it - thanks for the follow up @whytewolf.

I was able to get the behavior I want with this config:
```
gitfs_remotes:
    - ssh://git@git.example.com/repo-1.git:
        - root: formulas
    - ssh://git@git.example.com/repo-2.git:
        - root: src/formulas
    - ssh://git@git.example.com/repo-1.git:
        - name: repo-1-fallback
        - root: formulas
        - all_saltenvs: master
        - refspecs:
            - "+refs/heads/*:refs/remotes/origin/master"
    - ssh://git@git.example.com/repo-2.git:
        - name: repo-2-fallback
        - root: src/formulas
        - all_saltenvs: master
        - refspecs:
            - "+refs/heads/*:refs/remotes/origin/master"
```
