### ISSUE TITLE
Installation failed on RHEL 7.4

### ISSUE THREAD

**Issue by Morozzko** [saltstack/salt#57717]
I tried to solve the problem from different sentences, it did not help.
Can any one help me?

```

[root@161 /]# pip install salt
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already satisfied: salt in /usr/lib/python2.7/site-packages (3001)
Requirement already satisfied: pyzmq>=17.0.0 in /usr/lib64/python2.7/site-packages (from salt) (19.0.1)
Requirement already satisfied: distro in /usr/lib/python2.7/site-packages (from salt) (1.5.0)
Requirement already satisfied: Jinja2 in /usr/lib/python2.7/site-packages (from salt) (2.11.2)
Requirement already satisfied: PyYAML in /usr/lib64/python2.7/site-packages (from salt) (5.3.1)
Requirement already satisfied: MarkupSafe in /usr/lib64/python2.7/site-packages (from salt) (1.1.1)
Requirement already satisfied: pycryptodomex>=3.9.7 in /usr/lib64/python2.7/site-packages (from salt) (3.9.7)
Requirement already satisfied: msgpack!=0.5.5,<1.0.0,>=0.5 in /usr/lib64/python2.7/site-packages (from salt) (0.6.2)
Requirement already satisfied: requests>=1.0.0 in /usr/lib/python2.7/site-packages (from salt) (2.24.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python2.7/site-packages (from requests>=1.0.0->salt) (2020.4.5.2)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python2.7/site-packages (from requests>=1.0.0->salt) (1.25.9)
Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python2.7/site-packages (from requests>=1.0.0->salt) (2.9)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/lib/python2.7/site-packages (from requests>=1.0.0->salt) (3.0.4)
[root@161 /]# salt --version
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    sys.exit(salt_main())
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 553, in salt_main
    import salt.cli.salt
  File "/usr/lib/python2.7/site-packages/salt/cli/salt.py", line 12, in <module>
    import salt.utils.job
  File "/usr/lib/python2.7/site-packages/salt/utils/job.py", line 12, in <module>
    import salt.minion
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 27, in <module>
    import salt.beacons
  File "/usr/lib/python2.7/site-packages/salt/beacons/__init__.py", line 13, in <module>
    import salt.loader
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 22, in <module>
    from collections.abc import MutableMapping
ImportError: No module named abc
[root@161 /]#

```

**Comment by xeacott** [comment]
Hi @Morozzko so it looks like you've installed using Python 2.7, which we no longer officially support, to which the ImportError is because Python 2.7 does not have abc importing. You will have to use Python3.6+

**Comment by Morozzko** [comment]
thx gonna try
