### ISSUE TITLE
[BUG] unnecessary line. broken ansible roster.

### ISSUE THREAD

**Issue by Zortran** [saltstack/salt#57715]
https://github.com/saltstack/salt/blob/b95213ec903402f25c1e0aeb3990fe8452ab63ce/salt/roster/ansible.py#L146
Line was pushed in **if** but have double. Comment line 146 fix ansible roster.
```
username@do-ansible:~$ salt-mk \* test.ping
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
KeyError: 'ungrouped'
Traceback (most recent call last):
  File "/usr/bin/salt-ssh", line 11, in <module>
    load_entry_point('salt==3001', 'console_scripts', 'salt-ssh')()
  File "/usr/lib/python3/dist-packages/salt/scripts.py", line 499, in salt_ssh
    client.run()
  File "/usr/lib/python3/dist-packages/salt/cli/ssh.py", line 25, in run
    ssh = salt.client.ssh.SSH(self.config)
  File "/usr/lib/python3/dist-packages/salt/client/ssh/__init__.py", line 243, in __init__
    self.targets = self.roster.targets(self.opts["tgt"], self.tgt_type)
  File "/usr/lib/python3/dist-packages/salt/roster/__init__.py", line 105, in targets
    targets.update(self.rosters[f_str](tgt, tgt_type))
  File "/usr/lib/python3/dist-packages/salt/roster/ansible.py", line 133, in targets
    host for host in _get_hosts_from_group("all") if fnmatch.fnmatch(host, tgt)
  File "/usr/lib/python3/dist-packages/salt/roster/ansible.py", line 146, in _get_hosts_from_group
    hosts.extend(_get_hosts_from_group(child))
  File "/usr/lib/python3/dist-packages/salt/roster/ansible.py", line 142, in _get_hosts_from_group
    hosts = [host for host in inventory[group].get("hosts", [])]
KeyError: 'ungrouped'
Traceback (most recent call last):
  File "/usr/bin/salt-ssh", line 11, in <module>
    load_entry_point('salt==3001', 'console_scripts', 'salt-ssh')()
  File "/usr/lib/python3/dist-packages/salt/scripts.py", line 499, in salt_ssh
    client.run()
  File "/usr/lib/python3/dist-packages/salt/cli/ssh.py", line 25, in run
    ssh = salt.client.ssh.SSH(self.config)
  File "/usr/lib/python3/dist-packages/salt/client/ssh/__init__.py", line 243, in __init__
    self.targets = self.roster.targets(self.opts["tgt"], self.tgt_type)
  File "/usr/lib/python3/dist-packages/salt/roster/__init__.py", line 105, in targets
    targets.update(self.rosters[f_str](tgt, tgt_type))
  File "/usr/lib/python3/dist-packages/salt/roster/ansible.py", line 133, in targets
    host for host in _get_hosts_from_group("all") if fnmatch.fnmatch(host, tgt)
  File "/usr/lib/python3/dist-packages/salt/roster/ansible.py", line 146, in _get_hosts_from_group
    hosts.extend(_get_hosts_from_group(child))
  File "/usr/lib/python3/dist-packages/salt/roster/ansible.py", line 142, in _get_hosts_from_group
    hosts = [host for host in inventory[group].get("hosts", [])]
KeyError: 'ungrouped'
username@do-ansible:~$ sudo sed -i '146 s/^\([ ]*\)/\1#/g' /usr/lib/python3/dist-packages/salt/roster/ansible.py
username@do-ansible:~$ salt-mk \* test.ping
do-ansible:
    True
do-test:
    True
username@do-ansible:~$ dpkg -l|grep salt
ii  salt-common                          3001+ds-1                         all          shared libraries that salt requires for all packages
ii  salt-ssh                             3001+ds-1                         all          remote manager to administer servers via Salt SSH
username@do-ansible:~$ grep -i pret /etc/os-release
PRETTY_NAME="Ubuntu 20.04 LTS"
```

**Comment by xeacott** [comment]
@Zortran Thanks for the report. Just to clarify, the line ...

num 146 `hosts.extend(_get_hosts_from_group(child)) ` 
should be commented out as its causing issues, yes?

If this is the case, would you like to get a PR in for this and we can continue discussion there?

**Comment by Zortran** [comment]
@xeacott I'm newbie in Python. But receive error I found broken logic in function. I think line 146 must be deleted. For me it fix the roster module.
```
def _get_hosts_from_group(group):
    inventory = __context__["inventory"]
    hosts = [host for host in inventory[group].get("hosts", [])]
    for child in inventory[group].get("children", []):
        if child != "ungrouped":
            hosts.extend(_get_hosts_from_group(child))
        hosts.extend(_get_hosts_from_group(child))  ##line 146. run always. for [some_group:children][item]!="ungrouped" - twice
    return hosts
```

**Comment by xeacott** [comment]
I'll make a PR in a second here, let the tests run on it, and see if something breaks. 😄
