### ISSUE TITLE
[BUG] test_thin_dir fails with python3-virtualenv 20.0.23+ds-1

### ISSUE THREAD

**Issue by bdrung** [saltstack/salt#57734]
I wanted to prepare salt 3001 for Debian and one test case failed:

```
======================================================================
ERROR: test_thin_dir (unit.utils.test_thin.SSHThinTestCase)
[CPU:0.0%|MEM:69.8%] Test the thin dir to make sure salt-call can run
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/tests/unit/utils/test_thin.py", line 1312, in test_thin_dir
    with VirtualEnv() as venv:
  File "/<<PKGBUILDDIR>>/tests/support/helpers.py", line 1659, in __enter__
    self._create_virtualenv()            
  File "/<<PKGBUILDDIR>>/tests/support/helpers.py", line 1718, in _create_virtualenv
    sminion.functions.virtualenv.create(         
  File "/<<PKGBUILDDIR>>/salt/modules/virtualenv_mod.py", line 204, in create
    virtualenv_version_info = virtualenv_ver(venv_bin, user=user, **kwargs)
  File "/<<PKGBUILDDIR>>/salt/modules/virtualenv_mod.py", line 60, in virtualenv_ver
    [int(i) for i in version.split("rc")[0].split(".")]
  File "/<<PKGBUILDDIR>>/salt/modules/virtualenv_mod.py", line 60, in <listcomp>
    [int(i) for i in version.split("rc")[0].split(".")]
ValueError: invalid literal for int() with base 10: '23+ds'

----------------------------------------------------------------------
```

The test case obviously choke the version number of the installed python3-virtualenv package: `20.0.23+ds-1`.

**Comment by xeacott** [comment]
I believe this test is passing in our environment but let me check @bdrung
