### ISSUE TITLE
[BUG] Problem with file.replace with python 3.8

### ISSUE THREAD

**Issue by fgionghi** [saltstack/salt#57744]
**Description**
I have 1 master (ubuntu 18.04) and 2 clients (one ubuntu 18.04 and one ubuntu 20.04) with salt 3001.

I have this state:
```
history-search-backward:
  file.replace:
    - name: /etc/inputrc
    - pattern: {{ '# "\e[5~": history-search-backward' | regex_escape }}
    - repl: '"\e[5~": history-search-backward'

history-search-forward:
  file.replace:
    - name: /etc/inputrc
    - pattern: {{ '# "\e[6~": history-search-forward' | regex_escape }}
    - repl: '"\e[6~": history-search-forward'
```
and on ubuntu 18.04 everything is working fine:
```
ariel:
----------
          ID: history-search-backward
    Function: file.replace
        Name: /etc/inputrc
      Result: True
     Comment: No changes needed to be made
     Started: 10:05:43.693257
    Duration: 12.352 ms
     Changes:  
----------
          ID: history-search-forward
    Function: file.replace
        Name: /etc/inputrc
      Result: True
     Comment: No changes needed to be made
     Started: 10:05:43.705747
    Duration: 2.844 ms
     Changes:

Summary for ariel
------------
Succeeded: 2
Failed:    0
------------
Total states run:     2
Total run time:  15.196 ms
```
But I have problems with ubuntu 20.04:
```
imsai:
----------
          ID: history-search-backward
    Function: file.replace
        Name: /etc/inputrc
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3.8/sre_parse.py", line 1039, in parse_template
                  this = chr(ESCAPES[this][1])
              KeyError: '\\e'

              During handling of the above exception, another exception occurred:

              Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 2153, in call
                  ret = self.states[cdata["full"]](
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2087, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/file.py", line 5165, in replace
                  changes = __salt__["file.replace"](
                File "/usr/lib/python3/dist-packages/salt/modules/file.py", line 2566, in replace
                  result, nrepl = re.subn(
                File "/usr/lib/python3.8/re.py", line 219, in subn
                  return _compile(pattern, flags).subn(repl, string, count)
                File "/usr/lib/python3.8/re.py", line 325, in _subx
                  template = _compile_repl(template, pattern)
                File "/usr/lib/python3.8/re.py", line 316, in _compile_repl
                  return sre_parse.parse_template(repl, pattern)
                File "/usr/lib/python3.8/sre_parse.py", line 1042, in parse_template
                  raise s.error('bad escape %s' % this, len(this))
              re.error: bad escape \e at position 1
     Started: 10:01:51.684033
    Duration: 12.025 ms
     Changes:
----------
          ID: history-search-forward
    Function: file.replace
        Name: /etc/inputrc
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3.8/sre_parse.py", line 1039, in parse_template
                  this = chr(ESCAPES[this][1])
              KeyError: '\\e'

              During handling of the above exception, another exception occurred:

              Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 2153, in call
                  ret = self.states[cdata["full"]](
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2087, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/file.py", line 5165, in replace
                  changes = __salt__["file.replace"](
                File "/usr/lib/python3/dist-packages/salt/modules/file.py", line 2566, in replace
                  result, nrepl = re.subn(
                File "/usr/lib/python3.8/re.py", line 219, in subn
                  return _compile(pattern, flags).subn(repl, string, count)
                File "/usr/lib/python3.8/re.py", line 325, in _subx
                  template = _compile_repl(template, pattern)
                File "/usr/lib/python3.8/re.py", line 316, in _compile_repl
                  return sre_parse.parse_template(repl, pattern)
                File "/usr/lib/python3.8/sre_parse.py", line 1042, in parse_template
                  raise s.error('bad escape %s' % this, len(this))
              re.error: bad escape \e at position 1
     Started: 10:01:51.696315
    Duration: 2.001 ms
     Changes:

Summary for imsai
------------
Succeeded: 0
Failed:    2
------------
Total states run:     2
Total run time:  14.026 ms
ERROR: Minions returned with non-zero exit code
```

**Versions Report**
minion `ariel` ubuntu 18.04:
```
Salt Version:
           Salt: 3001
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.7
         pygit2: Not Installed
         Python: 3.6.9 (default, Apr 18 2020, 01:56:04)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 17.1.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: ubuntu 18.04 Bionic Beaver
         locale: UTF-8
        machine: x86_64
        release: 5.3.0-59-generic
         system: Linux
        version: Ubuntu 18.04 Bionic Beaver
```
minion `imsai` ubuntu 20.04:
```
Salt Version:
           Salt: 3001
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 2.0.6
      gitpython: 3.0.7
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: 1.1.0
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: 3.6.1
         pygit2: Not Installed
         Python: 3.8.2 (default, Apr 27 2020, 15:53:34)
   python-gnupg: 0.4.5
         PyYAML: 5.3.1
          PyZMQ: 18.1.1
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: ubuntu 20.04 focal
         locale: utf-8
        machine: x86_64
        release: 5.4.0-37-generic
         system: Linux
        version: Ubuntu 20.04 focal
```
master with ubuntu 18.04:
```
Salt Version:
           Salt: 3001
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
         Jinja2: 2.10
        libgit2: 0.26.0
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.7
         pygit2: 0.26.2
         Python: 3.6.9 (default, Apr 18 2020, 01:56:04)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 17.1.2
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: ubuntu 18.04 Bionic Beaver
         locale: UTF-8
        machine: x86_64
        release: 5.0.0-25-generic
         system: Linux
        version: Ubuntu 18.04 Bionic Beaver
```

**Comment by krionbsd** [comment]
It seems backslash handling changed in Python3.8:
https://docs.python.org/3.8/library/re.html

Could you please use smth like:
```
- repl: '"\\e[5~": history-search-backward'
```

**Comment by fgionghi** [comment]
Thanks, it works on the client with python 3.8 (ubuntu 20.04) and it also works on python 3.6 (ubuntu 18.04). 
I think we can close the issue.
