### ISSUE TITLE
[BUG] Broken Tiamat-based Salt builds (undefined symbol: EVP_idea_cbc)

### ISSUE THREAD

**Issue by max-arnold** [saltstack/salt#57809]
**Description**

A couple of Tiamat-based daily builds are currently broken: https://gitlab.com/myii/salt-image-builder/-/pipelines/158890125

* Debian 9
* Debian 10
* Ubuntu 18.04
* Ubuntu 20.04

A package fails to start with `undefined symbol: EVP_idea_cbc, version OPENSSL_1_1_0`

**Steps to Reproduce the behavior**

```
cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04 LTS"

wget -qO - https://artifactory.saltstack.net/artifactory/api/gpg/key/public | sudo apt-key add -
echo 'deb https://artifactory.saltstack.net/artifactory/open-debian-staging focal main' | sudo tee /etc/apt/sources.list.d/saltstack.list
sudo apt-get update
sudo apt-get install salt-minion

Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  dctrl-tools debconf-utils net-tools salt-common
Suggested packages:
  debtags
The following NEW packages will be installed:
  dctrl-tools debconf-utils net-tools salt-common salt-minion
0 upgraded, 5 newly installed, 0 to remove and 55 not upgraded.
Need to get 40.7 MB of archives.
After this operation, 144 MB of additional disk space will be used.
Do you want to continue? [Y/n]
Get:1 http://archive.ubuntu.com/ubuntu focal/main amd64 dctrl-tools amd64 2.24-3 [61.5 kB]
Get:2 http://archive.ubuntu.com/ubuntu focal/universe amd64 debconf-utils all 1.5.73 [57.2 kB]
Get:3 http://archive.ubuntu.com/ubuntu focal/main amd64 net-tools amd64 1.60+git20180626.aebd88e-1ubuntu1 [196 kB]
Get:4 https://artifactory.saltstack.net/artifactory/open-debian-staging focal/main amd64 salt-common amd64 3001~rc1-70-gb95213ec90+ds-1 [40.3 MB]
Get:5 https://artifactory.saltstack.net/artifactory/open-debian-staging focal/main amd64 salt-minion all 3001~rc1-70-gb95213ec90+ds-1 [27.8 kB]
Fetched 40.7 MB in 1min 7s (610 kB/s)
Selecting previously unselected package dctrl-tools.
(Reading database ... 47128 files and directories currently installed.)
Preparing to unpack .../dctrl-tools_2.24-3_amd64.deb ...
Unpacking dctrl-tools (2.24-3) ...
Selecting previously unselected package debconf-utils.
Preparing to unpack .../debconf-utils_1.5.73_all.deb ...
Unpacking debconf-utils (1.5.73) ...
Selecting previously unselected package net-tools.
Preparing to unpack .../net-tools_1.60+git20180626.aebd88e-1ubuntu1_amd64.deb ...
Unpacking net-tools (1.60+git20180626.aebd88e-1ubuntu1) ...
Selecting previously unselected package salt-common.
Preparing to unpack .../salt-common_3001~rc1-70-gb95213ec90+ds-1_amd64.deb ...
Unpacking salt-common (3001~rc1-70-gb95213ec90+ds-1) ...
Selecting previously unselected package salt-minion.
Preparing to unpack .../salt-minion_3001~rc1-70-gb95213ec90+ds-1_all.deb ...
Unpacking salt-minion (3001~rc1-70-gb95213ec90+ds-1) ...
Setting up net-tools (1.60+git20180626.aebd88e-1ubuntu1) ...
Setting up salt-common (3001~rc1-70-gb95213ec90+ds-1) ...
Setting up debconf-utils (1.5.73) ...
Setting up dctrl-tools (2.24-3) ...
Setting up salt-minion (3001~rc1-70-gb95213ec90+ds-1) ...
Created symlink /etc/systemd/system/multi-user.target.wants/salt-minion.service → /lib/systemd/system/salt-minion.service.
Job for salt-minion.service failed because the control process exited with error code.
See "systemctl status salt-minion.service" and "journalctl -xe" for details.
invoke-rc.d: initscript salt-minion, action "start" failed.
● salt-minion.service - The Salt Minion
     Loaded: loaded (/lib/systemd/system/salt-minion.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2020-06-26 05:56:53 PDT; 11ms ago
       Docs: man:salt-minion(1)
             file:///usr/share/doc/salt/html/contents.html
             https://docs.saltstack.com/en/latest/contents.html
    Process: 22829 ExecStart=/usr/bin/salt-minion (code=exited, status=255/EXCEPTION)
   Main PID: 22829 (code=exited, status=255/EXCEPTION)
Jun 26 05:56:53 minion1 systemd[1]: Starting The Salt Minion...
Jun 26 05:56:53 minion1 salt-minion[22836]: [22836] Failed to execute script pyi_rth_certifi
Jun 26 05:56:53 minion1 salt-minion[22836]: Traceback (most recent call last):
Jun 26 05:56:53 minion1 salt-minion[22836]:   File "PyInstaller/loader/rthooks/pyi_rth_certifi.py", line 13, in <module>
Jun 26 05:56:53 minion1 salt-minion[22836]:   File "/tmp/tmp34rxjeot/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
Jun 26 05:56:53 minion1 salt-minion[22836]:   File "ssl.py", line 98, in <module>
Jun 26 05:56:53 minion1 salt-minion[22836]: ImportError: /opt/saltstack/salt/run/libssl.so.1.1: undefined symbol: EVP_idea_cbc, version OPENSSL_1_1_0
Jun 26 05:56:53 minion1 systemd[1]: salt-minion.service: Main process exited, code=exited, status=255/EXCEPTION
Jun 26 05:56:53 minion1 systemd[1]: salt-minion.service: Failed with result 'exit-code'.
Jun 26 05:56:53 minion1 systemd[1]: Failed to start The Salt Minion.
dpkg: error processing package salt-minion (--configure):
 installed salt-minion package post-installation script subprocess returned error exit status 1
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for systemd (245.4-4ubuntu3) ...
Errors were encountered while processing:
 salt-minion
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

CC: @bryceml

**Comment by krionbsd** [comment]
@myii could you look into this?

**Comment by myii** [comment]
@krionbsd Actually @bryceml is well-aware of the issues and mentioned the general problem in yesterday's Open Hour.  He explained it will be fixed in the next couple of weeks.

**Comment by krionbsd** [comment]
@myii ok great, thank you

**Comment by s0undt3ch** [comment]
How is this tiamat related if it's installing the `salt-minion` package?

**Comment by s0undt3ch** [comment]
Nevermind the above comment.
_Look at the "trace" Luke_

**Comment by bryceml** [comment]
this fixed, but the pipeline that creates the packages broke at the same time.  We're blocked by https://gitlab.com/saltstack/pop/tiamat/-/issues/5

**Comment by bryceml** [comment]
looks like we're unblocked, I just merged https://gitlab.com/saltstack/open/salt-pkg/-/merge_requests/30

**Comment by bryceml** [comment]
@max-arnold do you want to test this again and make sure it's fixed?

**Comment by myii** [comment]
@bryceml All good at our end:

* https://gitlab.com/myii/salt-image-builder/-/pipelines/158890125

**Comment by myii** [comment]
Latest pre-salted Tiamat images being pushed here:

* https://hub.docker.com/r/myii/salt-tiamat-py3/tags

**Comment by max-arnold** [comment]
@bryceml I can confirm that the package installs fine now. Thanks!
