### ISSUE TITLE
[BUG] Traceback on any Proxy Minion startup due to ESXI Grain module missing __opts__

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#57811]
**Description**

Start any Proxy Minion with 3001, and see the following error multiple times:

```
[ERROR   ] Failed to import grains esxi, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/salt/loader.py", line 1685, in _load_module
    mod = spec.loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/site-packages/salt/grains/esxi.py", line 18, in <module>
    if salt.utils.platform.is_proxy() and __opts__["proxy"]["proxytype"] == "esxi":
NameError: name '__opts__' is not defined
```

**Setup**

Proxy config:

```yaml
open_mode: true
master: localhost
```

Master config:

```yaml
open_mode: true

pillar_roots:
  base:
    - /tmp/pillar
```

Pillar top ``/tmp/pillar/top.sls``

```yaml
base: 
  b0rk:
    - dummy
```

``/tmp/pillar/dummy.sls``

```yaml
proxy:
  proxytype: dummy
```

**Steps to Reproduce the behavior**

Using the files above, start the Proxy Minion and should see the error:

```bash
root@b6c49910bacb:/# salt-proxy -c /tmp --proxyid b0rk
[ERROR   ] Failed to import grains esxi, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/salt/loader.py", line 1685, in _load_module
    mod = spec.loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/site-packages/salt/grains/esxi.py", line 18, in <module>
    if salt.utils.platform.is_proxy() and __opts__["proxy"]["proxytype"] == "esxi":
NameError: name '__opts__' is not defined
[ERROR   ] Failed to import grains esxi, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/salt/loader.py", line 1685, in _load_module
    mod = spec.loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/site-packages/salt/grains/esxi.py", line 18, in <module>
    if salt.utils.platform.is_proxy() and __opts__["proxy"]["proxytype"] == "esxi":
NameError: name '__opts__' is not defined
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
root@b6c49910bacb:/# salt -V
Salt Version:
           Salt: 3001
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.9.8
         pygit2: Not Installed
         Python: 3.6.10 (default, Feb 26 2020, 16:40:36)
   python-gnupg: Not Installed
         PyYAML: 5.3.1
          PyZMQ: 19.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: debian 9 stretch
         locale: UTF-8
        machine: x86_64
        release: 5.3.0-59-generic
         system: Linux
        version: Debian GNU/Linux 9 stretch
```
</details>

**Comment by mirceaulinic** [comment]
Seems like this was introduced by 92a33352f82f657b3a9e91162290da3d7a99da62. I'm surprised this code went in like this, it's a well known fact that ``__opts__`` isn't available outside a function.

**Comment by hupebln** [comment]
I’ve experienced the same.
I had to downgrade to the latest 3000 version. And I hope it will be fixed in the next Minor version of 3001, otherwise we cannot use newer versions.

**Comment by markuskramerIgitt** [comment]
My bad. Thank you for letting me know. I was not aware that dunder opts exist only in functions and will surely remember.

**Comment by markuskramerIgitt** [comment]
Please note the above pull request to remove `__opts__` to fix behaviour for proxy clients.

**Comment by markuskramerIgitt** [comment]
I now face the same problem in `file.line`, in the out-of-date version of the minion I use:

```
----------
          ID: write_autologon_bat
    Function: file.line
        Name: /apps/dhlcopy/autologon.bat
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "C:\salt\bin\lib\site-packages\salt\state.py", line 1746, in call
                  **cdata['kwargs'])
                File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1703, in wrapper
                  return f(*args, **kwargs)
                File "C:\salt\bin\lib\site-packages\salt\states\file.py", line 3191, in line
                  backup=backup, quiet=quiet, indent=indent)
                File "C:\salt\bin\lib\site-packages\salt\modules\file.py", line 1819, in line
                  if __opts__['test'] is False:
              NameError: global name '__opts__' is not defined
     Started: 20:54:47.917000
    Duration: 16.0 ms
     Changes:
    
 ```

**Comment by mirceaulinic** [comment]
FYI, if you're not using the ESXI proxy, you can get rid of that noisy error by disabling the ESXI Grain, i.e.,

```yaml
disable_grains:
  - esxi
```

(add that to your minion / proxy config file)
