### ISSUE TITLE
[BUG] lxd container_file_put failed with lxd  4.x

### ISSUE THREAD

**Issue by Insolita** [saltstack/salt#57822]
**Description**
lxd.container_file_put doesn't work with lxd 4.x (with 3.x its ok)
There no any restriction about supported lxd versions in salt documentation
**Setup**
salt 3000.3, 3001 (master and minion used same salt version )
pylxd 2.2.11
python 3.7.3

**Steps to Reproduce the behavior**
try to call `salt myminion lxd.container_file_put lxd1 /pat/to/dest /path/to/src`
With lxd 3.0 its ok, but with 4.0 and later it rase error:

```
 The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/salt/minion.py", line 1870, in _thread_return
        opts, data, func, args, kwargs
      File "/usr/lib/python3/dist-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/modules/lxd.py", line 1646, in container_file_put
        container.files.put(dst, src_fp.read(), mode=mode, uid=uid, gid=gid)
      File "/usr/lib/python3/dist-packages/salt/modules/lxd.py", line 3659, in put
        response = self._client.api.containers[self._container.name].files.post(
    AttributeError: 'FilesManager' object has no attribute '_client'
```

**Expected behavior**
file should be copied to the container

**Screenshots**
-
**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3001
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.11
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.6.1
         pygit2: Not Installed
         Python: 3.7.3 (default, Dec 20 2019, 18:57:59)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: debian 10 buster
         locale: UTF-8
        machine: x86_64
        release: 4.19.0-9-amd64
         system: Linux
        version: Debian GNU/Linux 10 buster

```
</details>

**Comment by Insolita** [comment]
Seems, reason in pylxd library, 2.2.11 version has breaking changes, with 2.2.10 all right

**Comment by goapunk** [comment]
This should be reopened since we want compatibility with 2.2.11, once it becomes the default version on most distros other users will run into this issue as well. 
The following test should make it work on 2.2.11  but I didn't really test it:
```
diff --git a/salt/modules/lxd.py b/salt/modules/lxd.py                          
index 7c8f9fb..d3528ae 100644                                                   
--- a/salt/modules/lxd.py                                                       
+++ b/salt/modules/lxd.py                                                       
@@ -3656,9 +3656,8 @@ if HAS_PYLXD:                                             
                 headers["X-LXD-uid"] = six.text_type(uid)                      
             if gid is not None:                                                
                 headers["X-LXD-gid"] = six.text_type(gid)                      
-            response = self._client.api.containers[self._container.name].files.post(
-                params={"path": filepath}, data=data, headers=headers          
-            )                                                                  
+            response = self._instance.client.api.containers[self._instance.name]
+                .files.post(params={'path': filepath}, data=data, headers=headers)
             return response.status_code == 200                                 
                                                                               
     Container.FilesManager = FilesManager
```
cc @pcdummy
