### ISSUE TITLE
[BUG] After upgrading to salt 3001 Hashicorp Vault integration breaks.

### ISSUE THREAD

**Issue by Arderos** [saltstack/salt#57838]
**Description**
After upgrading to salt 3001 Hashicorp Vault integration breaks. Verified on clean install with Ubuntu 18.04.

**Setup**
```
/etc/salt/master.d/vault.conf:
myvault:
  driver: vault

vault:
  url: https://astr-vault-01.fallensky.intra:8200
  verify: /etc/ssl/certs/ca-certificates.crt
  auth:
    method: approle
    role_id: removed
    secret_id: removed
  policies:
    - saltmaster

```
All other config files are not changed.

**Steps to Reproduce the behavior**

1. Install Salt master & minion:
`sh bootstrap-salt.sh -x python3 -M -A astr-salt-01`
3. Create some secrets
4. Configure vault integration with approle method
5. Try to query a secret:
`sudo salt-run sdb.get 'sdb://myvault/salt/unifi/chain' -l debug`

debug log:
```
[DEBUG   ] Sending event: tag = salt/run/20200629190646917754/new; data = {'fun': 'runner.sdb.get', 'jid': '20200629190646917754', 'user': 'sudo_root', 'fun_args': ['sdb://myvault/salt/unifi/chain'], '_stamp': '2020-06-29T19:06:47.262409'}
[DEBUG   ] LazyLoaded vault.get
[DEBUG   ] LazyLoaded vault.is_v2
[DEBUG   ] Found cached metadata for salt/unifi
[DEBUG   ] LazyLoaded local_cache.prep_jid
[DEBUG   ] Sending event: tag = salt/run/20200629190646917754/ret; data = {'fun': 'runner.sdb.get', 'jid': '20200629190646917754', 'user': 'sudo_root', 'fun_args': ['sdb://myvault/salt/unifi/chain'], '_stamp': '2020-06-29T19:06:47.289161', 'return': 'Exception occurred in runner sdb.get: Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/salt/client/mixins.py", line 397, in low\n    data["return"] = func(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/salt/runners/sdb.py", line 26, in get\n    return salt.utils.sdb.sdb_get(uri, __opts__, __utils__)\n  File "/usr/lib/python3/dist-packages/salt/utils/sdb.py", line 46, in sdb_get\n    return loaded_db[fun](query, profile=profile)\n  File "/usr/lib/python3/dist-packages/salt/sdb/vault.py", line 91, in get\n    version2 = __utils__["vault.is_v2"](path)\n  File "/usr/lib/python3/dist-packages/salt/utils/vault.py", line 413, in is_v2\n    if ret["type"] == "kv" and path_metadata.get("options", {}).get("version", "1") in [\nAttributeError: \'NoneType\' object has no attribute \'get\'\n', 'success': False}
[DEBUG   ] LazyLoaded nested.output
[INFO    ] Runner completed: 20200629190646917754
[DEBUG   ] Closing IPCMessageClient instance
[DEBUG   ] Runner return: Exception occurred in runner sdb.get: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/client/mixins.py", line 397, in low
    data["return"] = func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/runners/sdb.py", line 26, in get
    return salt.utils.sdb.sdb_get(uri, __opts__, __utils__)
  File "/usr/lib/python3/dist-packages/salt/utils/sdb.py", line 46, in sdb_get
    return loaded_db[fun](query, profile=profile)
  File "/usr/lib/python3/dist-packages/salt/sdb/vault.py", line 91, in get
    version2 = __utils__["vault.is_v2"](path)
  File "/usr/lib/python3/dist-packages/salt/utils/vault.py", line 413, in is_v2
    if ret["type"] == "kv" and path_metadata.get("options", {}).get("version", "1") in [
AttributeError: 'NoneType' object has no attribute 'get'

```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3001
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: 3.4.7
         pygit2: Not Installed
         Python: 3.6.9 (default, Apr 18 2020, 01:56:04)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 17.1.2
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: ubuntu 18.04 Bionic Beaver
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-76-generic
         system: Linux
        version: Ubuntu 18.04 Bionic Beaver

```
</details>

**Additional context**

**Comment by cmcmarrow** [comment]
@Arederos thanks for the bug report! This break is probably related to this PR #57066. It looks like _get_secret_path_metadata is returning None.

**Comment by mchugh19** [comment]
This should also be fixed in #57739, which I suggest targeting for 3001.1

**Comment by oeuftete** [comment]
ZD-5700

**Comment by sagetherage** [comment]
PR is merged closing as fixed in Magnesium will be released Oct 21, 2020
