### ISSUE TITLE
[BUG] Minion does not run startup_states in local mode until it connects to master

### ISSUE THREAD

**Issue by litnimax** [saltstack/salt#57865]
I have the following config (Salt 3001):
```
file_client: local
startup_states: sls
sls_list:
  - start
```
When I shutdown salt master start.sls is not executed until the minion is connected to the master.

I think it should execute local startup states regardless of master connection.

**Comment by s0undt3ch** [comment]
With the following config:
```yaml
/testing # cat /etc/salt/minion.d/c.conf 
file_client: local
master: 1.2.3.4
use_master_when_local: false
master_type: disable
startup_states: sls
sls_list:
  - start
```
It works correctly:
```
/testing # rm -f /tmp/foo.txt; salt-minion; ls -lah /tmp/foo.txt
[WARNING ] Error loading grains, unexpected linux_gpu_data output, check that you have a valid shell configured and permissions to run lspci command
[WARNING ] Master is set to disable, skipping connection
[WARNING ] Error loading grains, unexpected linux_gpu_data output, check that you have a valid shell configured and permissions to run lspci command
[WARNING ] PID 996 exists but does not appear to be a salt process.
^C[WARNING ] Minion received a SIGINT. Exiting.
The Salt Minion is shutdown. Minion received a SIGINT. Exited.
-rw-r--r--    1 root     root           4 Jul  7 15:01 /tmp/foo.txt
/testing # salt --version
salt 3001
```

What version of salt are you running?

**Comment by s0undt3ch** [comment]
Sorry, you mentioned it in the issue, 3001.

So, I can't reproduce it.

**Comment by s0undt3ch** [comment]
With only the config you provided, I can confirm the issue.

The piece of config that makes it work is `master_type: disable`

**Comment by litnimax** [comment]
Hi!
Let me tell more about the case.
I would like to have a fully masterless setup. 
I have it with:
```
file_client: local
master_type: disable
```
This is what all users of my product have. 
Now for my commercial customers (paid updates subscription) I want to have the same configuration but with the ability for remote support to connect to this minion and execute commands.
But in my case it cannot depend on master. The minion must be self-sufficient and run all states from local. And also it must run ``startup_states`` without any dependence on master connection.
So I don't get the idea of such a limitation not to run ``startup_states`` without master connection as the states are available locally. 
Please advise.
Thanks!

**Comment by amalaguti** [comment]
I can confirm this issue in Windows minion 3004.2
AFAIK, it's no sense to require master_type: disable in order to run startup_states

In fact, in Linux minion it's not required and works as expected running the startup states with the given config using file_client: local and a custom file_root

In addition some exceptions and warnings are seen in the Windows minion log, that may be annoying given the configuration is set to not use a master but seems like the minion is kinda ignoring it for certain functions
`
[WARNING ] The minion failed to return the job information for job req. This is often due to the master being shut down or overloaded. If the master is running, consider increasing the worker_threads value.
[WARNING ] The minion failed to return the job information for job req. This is often due to the master being shut down or overloaded. If the master is running, consider increasing the worker_threads value.
[DEBUG   ] Subprocess SignalHandlingProcess-4-Schedule-run_on_start_once cleaned up
[DEBUG   ] Subprocess ProcessPayload-Job-req cleaned up
Exception ignored in: <function AsyncZeroMQReqChannel.__del__ at 0x000002586A92FF70>
Traceback (most recent call last):
  File "c:\program files\salt project\salt\bin\lib\site-packages\salt-3004.2-py3.8.egg\salt\transport\zeromq.py", line 188, in __del__
    self.close()
  File "c:\program files\salt project\salt\bin\lib\site-packages\salt-3004.2-py3.8.egg\salt\transport\zeromq.py", line 178, in close
    if self._closing:
AttributeError: 'AsyncZeroMQReqChannel' object has no attribute '_closing'
`
