### ISSUE TITLE
[BUG] salt-ssh does not work on mac osx

### ISSUE THREAD

**Issue by jagguli** [saltstack/salt#57915]
**Description**
Tryiiing to run modules usng salt-ssh on a mac machine does not work

**Setup**
/etc/salt/roster
```
iosbuild:
  host: iosbuild
  user: build
  password: pass
```
**Steps to Reproduce the behavior**
`salt-ssh iosbuild cmd.run ls`

```
iosbuild:
    ----------
    retcode:
        1
    stderr:
        Traceback (most recent call last):
          File "/var/tmp/.hawk_9d45b7_salt/salt-call", line 27, in <module>
            salt_call()
          File "/var/tmp/.hawk_9d45b7_salt/pyall/salt/scripts.py", line 466, in salt_call
            import salt.cli.call
          File "/var/tmp/.hawk_9d45b7_salt/pyall/salt/cli/call.py", line 6, in <module>
            import salt.cli.caller
          File "/var/tmp/.hawk_9d45b7_salt/pyall/salt/cli/caller.py", line 18, in <module>
            import salt.loader
          File "/var/tmp/.hawk_9d45b7_salt/pyall/salt/loader.py", line 26, in <module>
            import salt.config
          File "/var/tmp/.hawk_9d45b7_salt/pyall/salt/config/__init__.py", line 26, in <module>
            import salt.utils.files
          File "/var/tmp/.hawk_9d45b7_salt/pyall/salt/utils/files.py", line 21, in <module>
            import salt.modules.selinux
          File "/var/tmp/.hawk_9d45b7_salt/pyall/salt/modules/selinux.py", line 24, in <module>
            import salt.utils.path
          File "/var/tmp/.hawk_9d45b7_salt/pyall/salt/utils/path.py", line 21, in <module>
            import salt.utils.platform
          File "/var/tmp/.hawk_9d45b7_salt/pyall/salt/utils/platform.py", line 11, in <module>
            from distro import linux_distribution
          File "/var/tmp/.hawk_9d45b7_salt/py3/distro.py", line 42, in <module>
            raise ImportError('Unsupported platform: {0}'.format(sys.platform))
        ImportError: Unsupported platform: darwin
    stdout:
```
**Expected behavior**

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
PASTE HERE
```
</details>

**Additional context**

**Comment by alexey-zhukovin** [comment]
@jagguli Thank you for your comment. 
Could you provide information from MacOs. `salt --versions-report`

**Comment by jagguli** [comment]
salt version on mac
```
/usr/local/Cellar/salt/3000/libexec/lib/python3.7/site-packages/salt/ext/tornado/httputil.py:107: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  class HTTPHeaders(collections.MutableMapping):
Salt Version:
           Salt: 3000

Dependency Versions:
           cffi: 1.13.2
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10.3
        libgit2: 0.28.4
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.28.2
         Python: 3.7.7 (default, Mar 10 2020, 15:43:03)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 18.1.1
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 19.5.0
         system: Darwin
        version: 10.15.5 x86_64
```

**Comment by Ch3LL** [comment]
im not able to replicate this on version 3001.

Looks like distro removed that importerror  here https://github.com/nir0s/distro/pull/202/files which was added in version v1.2.0.

What version of distro do you have?

**Comment by Ch3LL** [comment]
Closing due to inactivity. Please feel free to open a new issue with details if you are still running into this issue.
