### ISSUE TITLE
[BUG] no hard stop when there is a pillar rendering error

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#57923]
## The error in a pillar file
```
system_configs:
  test_vums_p:
  test_vums_p:
  check_vums_q:
  check_vums_q:
```

## The issue
salt keeps going and executes without a hard stop running states without any pillar data which is quite disturbing.

Why? Because there might be essential data in the pillar file which could easily lead to a reconfiguration of the **whole** host.

## The Output
```
[CRITICAL] Rendering SLS 'vums-work' failed, render error:
while constructing a mapping
  in "<unicode string>", line 2, column 3
found conflicting ID 'test_vums_p'
  in "<unicode string>", line 3, column 3
Traceback (most recent call last):
  File "/root/src/salt/salt/pillar/__init__.py", line 741, in render_pstate
    **defaults)
  File "/root/src/salt/salt/template.py", line 101, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/root/src/salt/salt/renderers/yaml.py", line 71, in render
    raise SaltRenderError(exc)
SaltRenderError: while constructing a mapping
  in "<unicode string>", line 2, column 3
found conflicting ID 'test_vums_p'
  in "<unicode string>", line 3, column 3
[CRITICAL] Pillar render error: Rendering SLS 'vums-work' failed. Please see master log for details.
[CRITICAL] Rendering SLS 'vums-work' failed, render error:
while constructing a mapping
  in "<unicode string>", line 2, column 3
found conflicting ID 'test_vums_p'
  in "<unicode string>", line 3, column 3
Traceback (most recent call last):
  File "/root/src/salt/salt/pillar/__init__.py", line 741, in render_pstate
    **defaults)
  File "/root/src/salt/salt/template.py", line 101, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/root/src/salt/salt/renderers/yaml.py", line 71, in render
    raise SaltRenderError(exc)
SaltRenderError: while constructing a mapping
  in "<unicode string>", line 2, column 3
found conflicting ID 'test_vums_p'
  in "<unicode string>", line 3, column 3
[CRITICAL] Pillar render error: Rendering SLS 'vums-work' failed. Please see master log for details.

###################################################
THE REGULAR SALT OUTPUT
###################################################

Summary for vums-work
-------------
Succeeded: 68 (changed=3)
Failed:     2
-------------
Total states run:     70
Total run time:   20.662 s

```

**Comment by alexey-zhukovin** [comment]
@team-core ^
