### ISSUE TITLE
[BUG] Salt fails to start on Windows if the hostname contains diacritics

### ISSUE THREAD

**Issue by lubyou** [saltstack/salt#57958]
**Description**
Hi,

I have a salt minion that contains diacritics in its hostname.
Salt crashes on startup.
Tested on 2019.2.5 and 3001.

**Setup**
Assign a hostname that contains diacritics, install salt, try to launch it.

**Steps to Reproduce the behavior**
```
C:\salt>hostname
Laptop-Auréal

C:\salt>salt-minion.bat -ltrace
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Multiprocessing queue logging configured for the process running unde
r PID: 63924 at log level 5
[DEBUG   ] Marking 'is_ip' as a jinja filter
[DEBUG   ] Marking 'is_ipv4' as a jinja filter
[DEBUG   ] Marking 'is_ipv6' as a jinja filter
[DEBUG   ] Marking 'ipv4' as a jinja filter
[DEBUG   ] Marking 'ipv6' as a jinja filter
[DEBUG   ] Marking 'ipaddr' as a jinja filter
[DEBUG   ] Marking 'ip_host' as a jinja filter
[DEBUG   ] Marking 'network_hosts' as a jinja filter
[DEBUG   ] Marking 'network_size' as a jinja filter
[DEBUG   ] Marking 'gen_mac' as a jinja filter
[DEBUG   ] Marking 'mac_str_to_bytes' as a jinja filter
[DEBUG   ] Marking 'dns_check' as a jinja filter
[DEBUG   ] Marking 'filter_by_networks' as a jinja filter
[TRACE   ] The required configuration section, 'fluent_handler', was not found t
he in the configuration. Not loading the fluent logging handlers module.
[TRACE   ] None of the required configuration sections, 'logstash_udp_handler' a
nd 'logstash_zmq_handler', were found in the configuration. Not loading the Logs
tash logging handlers module.
[DEBUG   ] Multiprocessing queue logging configured for the process running unde
r PID: 63924 at log level 5
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged
.
[INFO    ] Setting up the Salt Minion "laptop-aur-al-81b22c48-0ce5-4e34-b5bc-572
d379a5f6e.salt.domain.tld"
[DEBUG   ] Marking 'base64_encode' as a jinja filter
[DEBUG   ] Marking 'base64_decode' as a jinja filter
[DEBUG   ] Marking 'md5' as a jinja filter
[DEBUG   ] Marking 'sha1' as a jinja filter
[DEBUG   ] Marking 'sha256' as a jinja filter
[DEBUG   ] Marking 'sha512' as a jinja filter
[DEBUG   ] Marking 'hmac' as a jinja filter
[DEBUG   ] Marking 'hmac_compute' as a jinja filter
[DEBUG   ] Marking 'random_hash' as a jinja filter
[DEBUG   ] Marking 'rand_str' as a jinja filter
[DEBUG   ] Marking 'file_hashsum' as a jinja filter
[DEBUG   ] Marking 'http_query' as a jinja filter
[DEBUG   ] Marking 'strftime' as a jinja filter
[DEBUG   ] Marking 'date_format' as a jinja filter
[DEBUG   ] Marking 'raise' as a jinja global
[DEBUG   ] Marking 'match' as a jinja test
[DEBUG   ] Marking 'equalto' as a jinja test
[DEBUG   ] Marking 'skip' as a jinja filter
[DEBUG   ] Marking 'sequence' as a jinja filter
[DEBUG   ] Marking 'to_bool' as a jinja filter
[DEBUG   ] Marking 'indent' as a jinja filter
[DEBUG   ] Marking 'tojson' as a jinja filter
[DEBUG   ] Marking 'quote' as a jinja filter
[DEBUG   ] Marking 'regex_escape' as a jinja filter
[DEBUG   ] Marking 'regex_search' as a jinja filter
[DEBUG   ] Marking 'regex_match' as a jinja filter
[DEBUG   ] Marking 'regex_replace' as a jinja filter
[DEBUG   ] Marking 'uuid' as a jinja filter
[DEBUG   ] Marking 'unique' as a jinja filter
[DEBUG   ] Marking 'min' as a jinja filter
[DEBUG   ] Marking 'max' as a jinja filter
[DEBUG   ] Marking 'avg' as a jinja filter
[DEBUG   ] Marking 'union' as a jinja filter
[DEBUG   ] Marking 'intersect' as a jinja filter
[DEBUG   ] Marking 'difference' as a jinja filter
[DEBUG   ] Marking 'symmetric_difference' as a jinja filter
[DEBUG   ] Marking 'method_call' as a jinja filter
[DEBUG   ] Marking 'yaml_dquote' as a jinja filter
[DEBUG   ] Marking 'yaml_squote' as a jinja filter
[DEBUG   ] Marking 'yaml_encode' as a jinja filter
[TRACE   ] loaded json json lib
[DEBUG   ] Created pidfile: c:\salt\var\run\salt-minion.pid
[INFO    ] Starting up the Salt Minion
[DEBUG   ] AsyncEventPublisher PUB socket URI: 4510
[DEBUG   ] AsyncEventPublisher PULL socket URI: 4511
[INFO    ] Starting pull socket on 4511
[TRACE   ] IPCMessagePublisher: binding to socket: 4510
[TRACE   ] IPCServer: binding to socket: 4511
[DEBUG   ] SaltEvent PUB socket URI: 4510
[DEBUG   ] SaltEvent PULL socket URI: 4511
[TRACE   ] IPCClient: Connecting to socket: 4510
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[TRACE   ] 'dig' could not be found in the following search path: '['C:\\Program
 Files (x86)\\AdoptOpenJDK\\jre-8.0.232.09-hotspot\\bin', 'C:\\Windows\\system32
', 'C:\\Windows', 'C:\\Windows\\System32\\Wbem', 'C:\\Windows\\System32\\Windows
PowerShell\\v1.0\\', 'C:\\Windows\\System32\\OpenSSH\\', 'C:\\Program Files (x86
)\\Intel\\Intel(R) Management Engine Components\\DAL', 'C:\\Program Files\\Intel
\\Intel(R) Management Engine Components\\DAL', 'C:\\Program Files\\Intel\\WiFi\\
bin\\', 'C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\', 'C:\\salt',
'C:\\Users\\Administrateur\\AppData\\Local\\Microsoft\\WindowsApps']'
[TRACE   ] 'drill' could not be found in the following search path: '['C:\\Progr
am Files (x86)\\AdoptOpenJDK\\jre-8.0.232.09-hotspot\\bin', 'C:\\Windows\\system
32', 'C:\\Windows', 'C:\\Windows\\System32\\Wbem', 'C:\\Windows\\System32\\Windo
wsPowerShell\\v1.0\\', 'C:\\Windows\\System32\\OpenSSH\\', 'C:\\Program Files (x
86)\\Intel\\Intel(R) Management Engine Components\\DAL', 'C:\\Program Files\\Int
el\\Intel(R) Management Engine Components\\DAL', 'C:\\Program Files\\Intel\\WiFi
\\bin\\', 'C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\', 'C:\\salt'
, 'C:\\Users\\Administrateur\\AppData\\Local\\Microsoft\\WindowsApps']'
[TRACE   ] 'host' could not be found in the following search path: '['C:\\Progra
m Files (x86)\\AdoptOpenJDK\\jre-8.0.232.09-hotspot\\bin', 'C:\\Windows\\system3
2', 'C:\\Windows', 'C:\\Windows\\System32\\Wbem', 'C:\\Windows\\System32\\Window
sPowerShell\\v1.0\\', 'C:\\Windows\\System32\\OpenSSH\\', 'C:\\Program Files (x8
6)\\Intel\\Intel(R) Management Engine Components\\DAL', 'C:\\Program Files\\Inte
l\\Intel(R) Management Engine Components\\DAL', 'C:\\Program Files\\Intel\\WiFi\
\bin\\', 'C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\', 'C:\\salt',
 'C:\\Users\\Administrateur\\AppData\\Local\\Microsoft\\WindowsApps']'
[TRACE   ] 'dig' could not be found in the following search path: '['C:\\Program
 Files (x86)\\AdoptOpenJDK\\jre-8.0.232.09-hotspot\\bin', 'C:\\Windows\\system32
', 'C:\\Windows', 'C:\\Windows\\System32\\Wbem', 'C:\\Windows\\System32\\Windows
PowerShell\\v1.0\\', 'C:\\Windows\\System32\\OpenSSH\\', 'C:\\Program Files (x86
)\\Intel\\Intel(R) Management Engine Components\\DAL', 'C:\\Program Files\\Intel
\\Intel(R) Management Engine Components\\DAL', 'C:\\Program Files\\Intel\\WiFi\\
bin\\', 'C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\', 'C:\\salt',
'C:\\Users\\Administrateur\\AppData\\Local\\Microsoft\\WindowsApps']'
[TRACE   ] 'drill' could not be found in the following search path: '['C:\\Progr
am Files (x86)\\AdoptOpenJDK\\jre-8.0.232.09-hotspot\\bin', 'C:\\Windows\\system
32', 'C:\\Windows', 'C:\\Windows\\System32\\Wbem', 'C:\\Windows\\System32\\Windo
wsPowerShell\\v1.0\\', 'C:\\Windows\\System32\\OpenSSH\\', 'C:\\Program Files (x
86)\\Intel\\Intel(R) Management Engine Components\\DAL', 'C:\\Program Files\\Int
el\\Intel(R) Management Engine Components\\DAL', 'C:\\Program Files\\Intel\\WiFi
\\bin\\', 'C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\', 'C:\\salt'
, 'C:\\Users\\Administrateur\\AppData\\Local\\Microsoft\\WindowsApps']'
[TRACE   ] 'host' could not be found in the following search path: '['C:\\Progra
m Files (x86)\\AdoptOpenJDK\\jre-8.0.232.09-hotspot\\bin', 'C:\\Windows\\system3
2', 'C:\\Windows', 'C:\\Windows\\System32\\Wbem', 'C:\\Windows\\System32\\Window
sPowerShell\\v1.0\\', 'C:\\Windows\\System32\\OpenSSH\\', 'C:\\Program Files (x8
6)\\Intel\\Intel(R) Management Engine Components\\DAL', 'C:\\Program Files\\Inte
l\\Intel(R) Management Engine Components\\DAL', 'C:\\Program Files\\Intel\\WiFi\
\bin\\', 'C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\', 'C:\\salt',
 'C:\\Users\\Administrateur\\AppData\\Local\\Microsoft\\WindowsApps']'
[TRACE   ] Error loading grains.napalm: "napalm"" (C:\salt\bin\lib\site-packages
\salt-3001-py3.7.egg\salt\grains\napalm.py) cannot be loaded: NAPALM is not inst
alled: ``pip install napalm``
[TRACE   ] Error loading grains.nxos: No host specified and no UDS found at /tmp
/nginx_local/nginx_1_be_nxapi.sock

[TRACE   ] Error loading grains.zfs: ZFS: Not available on Windows
[TRACE   ] Loading core.append_domain grain
[TRACE   ] Loading core.cwd grain
[TRACE   ] Loading core.default_gateway grain
[TRACE   ] 'ip' could not be found in the following search path: '['C:\\Program
Files (x86)\\AdoptOpenJDK\\jre-8.0.232.09-hotspot\\bin', 'C:\\Windows\\system32'
, 'C:\\Windows', 'C:\\Windows\\System32\\Wbem', 'C:\\Windows\\System32\\WindowsP
owerShell\\v1.0\\', 'C:\\Windows\\System32\\OpenSSH\\', 'C:\\Program Files (x86)
\\Intel\\Intel(R) Management Engine Components\\DAL', 'C:\\Program Files\\Intel\
\Intel(R) Management Engine Components\\DAL', 'C:\\Program Files\\Intel\\WiFi\\b
in\\', 'C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\', 'C:\\salt', '
C:\\Users\\Administrateur\\AppData\\Local\\Microsoft\\WindowsApps']'
[TRACE   ] Loading core.dns grain
[TRACE   ] Loading core.fqdns grain
[TRACE   ] Loading core.get_machine_id grain
[TRACE   ] Loading core.get_master grain
[TRACE   ] Loading core.get_server_id grain
[TRACE   ] Loading core.hostname grain
[ERROR   ] An un-handled exception was caught by salt's global exception handler
:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 10: invalid
 continuation byte
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-minion", line 4, in <module>
    __import__('pkg_resources').run_script('salt==3001', 'salt-minion')
  File "C:\salt\bin\lib\site-packages\pkg_resources\__init__.py", line 750, in r
un_script
    self.require(requires)[0].run_script(script_name, ns)
  File "C:\salt\bin\lib\site-packages\pkg_resources\__init__.py", line 1527, in
run_script
    exec(code, namespace, namespace)
  File "c:\salt\bin\lib\site-packages\salt-3001-py3.7.egg\EGG-INFO\scripts\salt-
minion", line 27, in <module>
    salt_minion()
  File "C:\salt\bin\lib\site-packages\salt-3001-py3.7.egg\salt\scripts.py", line
 213, in salt_minion
    minion.start()
  File "C:\salt\bin\lib\site-packages\salt-3001-py3.7.egg\salt\cli\daemons.py",
line 337, in start
    self._real_start()
  File "C:\salt\bin\lib\site-packages\salt-3001-py3.7.egg\salt\cli\daemons.py",
line 349, in _real_start
    self.minion.tune_in()
  File "C:\salt\bin\lib\site-packages\salt-3001-py3.7.egg\salt\minion.py", line
1162, in tune_in
    self._spawn_minions()
  File "C:\salt\bin\lib\site-packages\salt-3001-py3.7.egg\salt\minion.py", line
1101, in _spawn_minions
    jid_queue=self.jid_queue,
  File "C:\salt\bin\lib\site-packages\salt-3001-py3.7.egg\salt\minion.py", line
1066, in _create_minion_object
    jid_queue=jid_queue,
  File "C:\salt\bin\lib\site-packages\salt-3001-py3.7.egg\salt\minion.py", line
1242, in __init__
    self.opts["grains"] = salt.loader.grains(opts)
  File "C:\salt\bin\lib\site-packages\salt-3001-py3.7.egg\salt\loader.py", line
825, in grains
    ret = funcs[key]()
  File "C:\salt\bin\lib\site-packages\salt-3001-py3.7.egg\salt\grains\core.py",
line 2313, in hostname
    __FQDN__ = salt.utils.network.get_fqhostname()
  File "C:\salt\bin\lib\site-packages\salt-3001-py3.7.egg\salt\utils\network.py"
, line 244, in get_fqhostname
    l = [socket.getfqdn()]
  File "C:\salt\bin\lib\socket.py", line 676, in getfqdn
    hostname, aliases, ipaddrs = gethostbyaddr(name)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 10: invalid
 continuation byte
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-minion", line 4, in <module>
    __import__('pkg_resources').run_script('salt==3001', 'salt-minion')
  File "C:\salt\bin\lib\site-packages\pkg_resources\__init__.py", line 750, in r
un_script
    self.require(requires)[0].run_script(script_name, ns)
  File "C:\salt\bin\lib\site-packages\pkg_resources\__init__.py", line 1527, in
run_script
    exec(code, namespace, namespace)
  File "c:\salt\bin\lib\site-packages\salt-3001-py3.7.egg\EGG-INFO\scripts\salt-
minion", line 27, in <module>
    salt_minion()
  File "C:\salt\bin\lib\site-packages\salt-3001-py3.7.egg\salt\scripts.py", line
 213, in salt_minion
    minion.start()
  File "C:\salt\bin\lib\site-packages\salt-3001-py3.7.egg\salt\cli\daemons.py",
line 337, in start
    self._real_start()
  File "C:\salt\bin\lib\site-packages\salt-3001-py3.7.egg\salt\cli\daemons.py",
line 349, in _real_start
    self.minion.tune_in()
  File "C:\salt\bin\lib\site-packages\salt-3001-py3.7.egg\salt\minion.py", line
1162, in tune_in
    self._spawn_minions()
  File "C:\salt\bin\lib\site-packages\salt-3001-py3.7.egg\salt\minion.py", line
1101, in _spawn_minions
    jid_queue=self.jid_queue,
  File "C:\salt\bin\lib\site-packages\salt-3001-py3.7.egg\salt\minion.py", line
1066, in _create_minion_object
    jid_queue=jid_queue,
  File "C:\salt\bin\lib\site-packages\salt-3001-py3.7.egg\salt\minion.py", line
1242, in __init__
    self.opts["grains"] = salt.loader.grains(opts)
  File "C:\salt\bin\lib\site-packages\salt-3001-py3.7.egg\salt\loader.py", line
825, in grains
    ret = funcs[key]()
  File "C:\salt\bin\lib\site-packages\salt-3001-py3.7.egg\salt\grains\core.py",
line 2313, in hostname
    __FQDN__ = salt.utils.network.get_fqhostname()
  File "C:\salt\bin\lib\site-packages\salt-3001-py3.7.egg\salt\utils\network.py"
, line 244, in get_fqhostname
    l = [socket.getfqdn()]
  File "C:\salt\bin\lib\socket.py", line 676, in getfqdn
    hostname, aliases, ipaddrs = gethostbyaddr(name)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 10: invalid
 continuation byte
```

**Expected behavior**
The salt minion should not crash.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3001

Dependency Versions:
           cffi: 1.12.2
       cherrypy: 17.4.1
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: Not Installed
   pycryptodome: 3.9.7
         pygit2: Not Installed
         Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.19
16 64 bit (AMD64)]
   python-gnupg: 0.4.4
         PyYAML: 5.1.2
          PyZMQ: 18.0.1
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 10
         system: Windows
        version: 10 10.0.18362 SP0
```
</details>

**Comment by lubyou** [comment]
Looks like this might be an upstream issue https://bugs.python.org/issue26227

**Comment by alexey-zhukovin** [comment]
@lubyou 
Thank you for your comment.

**Comment by sagetherage** [comment]
The upstream bug has been resolved in python @lubyou can you confirm this is no longer an issue?

**Comment by lubyou** [comment]
@sagetherage seems to be working with one of the recent releases.

Before:
```python
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> socket.getnameinfo(('127.0.0.1', 20), 0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 0: invalid continuation byte
```

After:
```python
Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> import socket
>>> socket.getnameinfo(('127.0.0.1', 20), 0)
('éééé.domain.tld', 'ftp-data')
>>> 
```
