### ISSUE TITLE
[BUG][Failing Test] EC2 Cloud tests are failing

### ISSUE THREAD

**Issue by s0undt3ch** [saltstack/salt#57965]
**Description**
After https://github.com/saltstack/salt/pull/57913 got merged, cloud tests started running again(they were previously being skipped) and we now have a few failures
* integration.cloud.clouds.test_ec2.EC2Test.test_instance
* integration.cloud.clouds.test_ec2.EC2Test.test_instance_rename
* integration.cloud.clouds.test_ec2.EC2Test.test_win2012r2_psexec
* integration.cloud.clouds.test_ec2.EC2Test.test_win2012r2_winrm
* integration.cloud.clouds.test_ec2.EC2Test.test_win2016_psexec
* integration.cloud.clouds.test_ec2.EC2Test.test_win2016_winrm

https://jenkinsci.saltstack.com/job/pr-centos7-py3-cloud/job/master/

**Comment by Ch3LL** [comment]
```
02:44:58         [ERROR   ] There was a profile error: unpackb() got an unexpected keyword argument 'encoding'
02:44:58         Traceback (most recent call last):
02:44:58           File "/tmp/kitchen/testing/salt/cloud/cli.py", line 290, in run
02:44:58             ret = mapper.run_profile(self.options.profile, self.config.get("names"))
02:44:58           File "/tmp/kitchen/testing/salt/cloud/__init__.py", line 1423, in run_profile
02:44:58             ret[name] = self.create(vm_)
02:44:58           File "/tmp/kitchen/testing/salt/cloud/__init__.py", line 1242, in create
02:44:58             output = self.clouds[func](vm_)
02:44:58           File "/tmp/kitchen/testing/salt/cloud/clouds/ec2.py", line 2654, in create
02:44:58             vm_["name"], vm_["profile"], "ec2", vm_["driver"]
02:44:58           File "/tmp/kitchen/testing/salt/utils/cloud.py", line 2729, in cachedir_index_add
02:44:58             salt.utils.msgpack.msgpack.load(fh_, encoding=MSGPACK_ENCODING)
02:44:58           File "/tmp/kitchen/testing/.nox/runtests-cloud-3-coverage-true/lib/python3.6/site-packages/msgpack/__init__.py", line 46, in unpack
02:44:58             return unpackb(data, **kwargs)
02:44:58           File "msgpack/_unpacker.pyx", line 144, in msgpack._cmsgpack.unpackb
02:44:58         TypeError: unpackb() got an unexpected keyword argument 'encoding'
```
