### ISSUE TITLE
[BUG] KeyError: 'uses' when using salt.sdb.vault module

### ISSUE THREAD

**Issue by ggiesen** [saltstack/salt#57989]
**Description**
I set up the Vault module following this guide:

https://help.saltstack.com/hc/en-us/articles/360041140451-Quick-Guide-to-Vault-Integration

and am receiving multiple errors:

```
[ERROR   ] Error from vault: {"request_id":"c0ae101a-7429-d5bd-1dc5-64bc686bdaeb","lease_id":"","renewable":false,"lease_duration":0,"data":null,"wrap_info":null,"warnings":["Non-listing operations on the root of a K/V v2 mount are not supported."],"auth":null}
[ERROR   ] Failed to read secret! KeyError: 'uses'
```

**Setup**
```
# export VAULT_TOKEN=<removed>
# vault secrets enable -version=2 -path=salt/ kv
# vault secrets list -detailed

Path          Plugin       Accessor              Default TTL    Max TTL    Force No Cache    Replication    Seal Wrap    External Entropy Access    Options           Description                                                UUID
----          ------       --------              -----------    -------    --------------    -----------    ---------    -----------------------    -------           -----------                                                ----
cubbyhole/    cubbyhole    cubbyhole_0ed4e009    n/a            n/a        false             local          false        false                      map[]             per-token private secret storage                           <removed>       
identity/     identity     identity_5c67da23     system         system     false             replicated     false        false                      map[]             identity store                                             <removed>       
salt/         kv           kv_388973e6           system         system     false             replicated     false        false                      map[version:2]    n/a                                                        <removed>       
sys/          system       system_06f235c2       n/a            n/a        false             replicated     false        false                      map[]             system endpoints used for control, policy and debugging    <removed>
```

/etc/vault.d/saltmaster.hcl:
```
# This section grants all access on "salt/*". 
# Further restrictions can be applied to this broad policy, as shown below.

# Minimum required access for KV secrets engine V1 and V2

# V1
path "salt/*" {
  capabilities = ["create", "read", "update", "delete", "list"]
}

path "salt/" {
  capabilities = ["list"]
}

# V2
path "salt/data/*" {
  capabilities = ["create", "read", "update", "delete", "list"]
}

path "salt/data/" {
  capabilities = ["list"]
}

# THIS ENTRY ALLOW SALTUTIL.PILLAR_REFRESH TO WORK PROPERLY
path "auth/token/create" {
 capabilities = ["create", "read", "update"]
}
```

```
# vault policy write saltmaster /etc/vault.d/saltmaster.hcl
# vault kv put salt/user1 password=p4ssw0rd desc="test user"
```
```
# vault kv get salt/user1 
====== Metadata ======
Key              Value
---              -----
created_time     2020-07-20T23:01:36.654071035Z
deletion_time    n/a
destroyed        false
version          1

====== Data ======
Key         Value
---         -----
desc        test user
password    p4ssw0rd
```
```
# vault auth enable approle
# vault write auth/approle/role/saltmaster policies="saltmaster" token_num_uses=0 secret_id_num_uses=0 token_ttl=3600 secret_id_ttl=31536000 token_type=service role_name=saltmaster
```
```
# vault read auth/approle/role/saltmaster
Key                        Value
---                        -----
bind_secret_id             true
local_secret_ids           false
policies                   [saltmaster]
secret_id_bound_cidrs      <nil>
secret_id_num_uses         0
secret_id_ttl              8760h
token_bound_cidrs          []
token_explicit_max_ttl     0s
token_max_ttl              0s
token_no_default_policy    false
token_num_uses             0
token_period               0s
token_policies             [saltmaster]
token_ttl                  1h
token_type                 service
```
```
# vault read auth/approle/role/saltmaster/role-id
Key        Value
---        -----
role_id    <removed>
```
```
# vault write -f auth/approle/role/saltmaster/secret-id
Key                   Value
---                   -----
secret_id             <removed>
secret_id_accessor    <removed>
```
```
# vault write auth/approle/login role_id=<removed> secret_id=<removed>
Key                     Value
---                     -----
token                   <removed>
token_accessor          <removed>
token_duration          1h
token_renewable         true
token_policies          ["default" "saltmaster"]
identity_policies       []
policies                ["default" "saltmaster"]
token_meta_role_name    saltmaster
```
```
# export VAULT_TOKEN=<removed>
```
```
# vault kv get salt/user1
====== Metadata ======
Key              Value
---              -----
created_time     2020-07-20T23:01:36.654071035Z
deletion_time    n/a
destroyed        false
version          1

====== Data ======
Key         Value
---         -----
desc        test user
password    p4ssw0rd
```

/etc/salt/master.d/vault.conf:
```
# SDB CONFIG
myvault:
  driver: vault

# VAULT CONFIG FOR TOKEN OR APPROLE AUTH MODE
vault:
  url: http://127.0.0.1:8200
  auth:
    method: approle
    role_id: <removed>
    secret_id: <removed>
  policies:
    - saltmaster
```

**Steps to Reproduce the behavior**
```
# salt-run sdb.get 'sdb://myvault/salt/data/user1' --out=json -l debug
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/git_pillar.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/git_pillar.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/gitfs.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/gitfs.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/netbox.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/netbox.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/saltgui.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/saltgui.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/slack.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/slack.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/vault.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/vault.conf
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] LazyLoaded sdb.get
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/git_pillar.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/git_pillar.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/gitfs.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/gitfs.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/netbox.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/netbox.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/saltgui.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/saltgui.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/slack.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/slack.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/vault.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/vault.conf
[DEBUG   ] Guessing ID. The id can be explicitly set in /etc/salt/minion
[DEBUG   ] Found minion id from generate_minion_id(): host.example.com
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/git_pillar.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/git_pillar.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/gitfs.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/gitfs.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/netbox.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/netbox.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/saltgui.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/saltgui.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/slack.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/slack.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/vault.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/vault.conf
[DEBUG   ] Elapsed time getting FQDNs: 0.11360836029052734 seconds
[DEBUG   ] LazyLoaded zfs.is_supported
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event: tag = salt/run/20200720234111374246/new; data = {'fun': 'runner.sdb.get', 'jid': '20200720234111374246', 'user': 'sudo_user', 'fun_args': ['sdb://myvault/salt/data/user1'], '_stamp': '2020-07-20T23:41:12.216083'}
[DEBUG   ] LazyLoaded vault.get
[DEBUG   ] LazyLoaded vault.is_v2
[DEBUG   ] Fetching metadata for salt/data
[DEBUG   ] Token has not expired 1595290789 > 1595288472
[DEBUG   ] Starting new HTTP connection (1): 127.0.0.1:8200
[DEBUG   ] http://127.0.0.1:8200 "GET /v1/sys/internal/ui/mounts/salt/data HTTP/1.1" 200 438
[DEBUG   ] Got metadata for salt/data
[DEBUG   ] Writing vault cache file
[DEBUG   ] Path salt/data already contains data in the right place - saltstack duct tape?
[DEBUG   ] Path is a "data" type but "metadata" type requested - Flipping: salt/metadata
[DEBUG   ] Path is a "data" type but "destroy" type requested - Flipping: salt/destroy
[DEBUG   ] Token has not expired 1595290789 > 1595288472
[DEBUG   ] Starting new HTTP connection (1): 127.0.0.1:8200
[DEBUG   ] http://127.0.0.1:8200 "GET /v1/salt/data HTTP/1.1" 403 33
[INFO    ] Permission denied from vault
[DEBUG   ] Deleting cache file
[DEBUG   ] Retrying with new credentials
[DEBUG   ] Refreshing token
[DEBUG   ] Using Vault connection details from local config
[DEBUG   ] Vault token expired. Recreating one
[DEBUG   ] Starting new HTTP connection (1): 127.0.0.1:8200
[DEBUG   ] http://127.0.0.1:8200 "POST /v1/auth/approle/login HTTP/1.1" 200 484
[DEBUG   ] Writing vault cache file
[DEBUG   ] Starting new HTTP connection (1): 127.0.0.1:8200
[DEBUG   ] http://127.0.0.1:8200 "GET /v1/salt/data HTTP/1.1" 404 232
[ERROR   ] Error from vault: {"request_id":"<removed>","lease_id":"","renewable":false,"lease_duration":0,"data":null,"wrap_info":null,"warnings":["Non-listing operations on the root of a K/V v2 mount are not supported."],"auth":null}       
[DEBUG   ] Decrementing Vault uses on limited token for url: v1/salt/data
[ERROR   ] Failed to read secret! KeyError: 'uses'
[DEBUG   ] LazyLoaded local_cache.prep_jid
[DEBUG   ] Sending event: tag = salt/run/20200720234111374246/ret; data = {'fun': 'runner.sdb.get', 'jid': '20200720234111374246', 'user': 'sudo_user', 'fun_args': ['sdb://myvault/salt/data/user1'], '_stamp': '2020-07-20T23:41:12.312651', 'return': 'Exception occur
red in runner sdb.get: Traceback (most recent call last):\n  File "/usr/lib/python3.6/site-packages/salt/sdb/vault.py", line 97, in get\n    response = __utils__["vault.make_request"]("GET", url, profile)\n  File "/usr/lib/python3.6/site-packages/salt/utils/vault.py",
 line 342, in make_request\n    connection["uses"] -= 1\nKeyError: \'uses\'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/lib/python3.6/site-packages/salt/client/mixins.py", line 397, in low\
n    data["return"] = func(*args, **kwargs)\n  File "/usr/lib/python3.6/site-packages/salt/runners/sdb.py", line 26, in get\n    return salt.utils.sdb.sdb_get(uri, __opts__, __utils__)\n  File "/usr/lib/python3.6/site-packages/salt/utils/sdb.py", line 46, in sdb_get\n
    return loaded_db[fun](query, profile=profile)\n  File "/usr/lib/python3.6/site-packages/salt/sdb/vault.py", line 113, in get\n    raise salt.exceptions.CommandExecutionError(e)\nsalt.exceptions.CommandExecutionError: \'uses\'\n', 'success': False}
[DEBUG   ] LazyLoaded json.output
"Exception occurred in runner sdb.get: Traceback (most recent call last):\n  File \"/usr/lib/python3.6/site-packages/salt/sdb/vault.py\", line 97, in get\n    response = __utils__[\"vault.make_request\"](\"GET\", url, profile)\n  File \"/usr/lib/python3.6/site-package
s/salt/utils/vault.py\", line 342, in make_request\n    connection[\"uses\"] -= 1\nKeyError: 'uses'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/lib/python3.6/site-packages/salt/client/mixi
ns.py\", line 397, in low\n    data[\"return\"] = func(*args, **kwargs)\n  File \"/usr/lib/python3.6/site-packages/salt/runners/sdb.py\", line 26, in get\n    return salt.utils.sdb.sdb_get(uri, __opts__, __utils__)\n  File \"/usr/lib/python3.6/site-packages/salt/utils
/sdb.py\", line 46, in sdb_get\n    return loaded_db[fun](query, profile=profile)\n  File \"/usr/lib/python3.6/site-packages/salt/sdb/vault.py\", line 113, in get\n    raise salt.exceptions.CommandExecutionError(e)\nsalt.exceptions.CommandExecutionError: 'uses'\n"    
[INFO    ] Runner completed: 20200720234111374246
[DEBUG   ] Closing IPCMessageClient instance
[DEBUG   ] Runner return: Exception occurred in runner sdb.get: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/sdb/vault.py", line 97, in get
    response = __utils__["vault.make_request"]("GET", url, profile)
  File "/usr/lib/python3.6/site-packages/salt/utils/vault.py", line 342, in make_request
    connection["uses"] -= 1
KeyError: 'uses'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/client/mixins.py", line 397, in low
    data["return"] = func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/runners/sdb.py", line 26, in get
    return salt.utils.sdb.sdb_get(uri, __opts__, __utils__)
  File "/usr/lib/python3.6/site-packages/salt/utils/sdb.py", line 46, in sdb_get
    return loaded_db[fun](query, profile=profile)
  File "/usr/lib/python3.6/site-packages/salt/sdb/vault.py", line 113, in get
    raise salt.exceptions.CommandExecutionError(e)
salt.exceptions.CommandExecutionError: 'uses'
```

**Expected behavior**
```
{ "data": { "password": "p4ssw0rd", "desc": "test user" }, "metadata": { "created_time": "2020-07-20T23:01:36.654071035Z", "destroyed": false, "version": 1, "deletion_time": "" } }
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3001

Dependency Versions:
           cffi: 1.14.0
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.2
        libgit2: 0.26.8
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 3.6.8 (default, Apr 16 2020, 01:36:27)
   python-gnupg: Not Installed
         PyYAML: 5.3.1
          PyZMQ: 19.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2

System Versions:
           dist: centos 8 Core
         locale: UTF-8
        machine: x86_64
        release: 4.18.0-193.6.3.el8_2.x86_64
         system: Linux
        version: CentOS Linux 8 Core
```
</details>

**Additional context**
Changing the secret to salt/user/user1 eliminates this error:

`[ERROR   ] Error from vault: {"request_id":"c0ae101a-7429-d5bd-1dc5-64bc686bdaeb","lease_id":"","renewable":false,"lease_duration":0,"data":null,"wrap_info":null,"warnings":["Non-listing operations on the root of a K/V v2 mount are not supported."],"auth":null}`

but not the other.

```
# vault status
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    5
Threshold       3
Version         1.4.3
Cluster Name    vault-cluster-415da5fb
Cluster ID      <removed>
HA Enabled      false
```

**Comment by ggiesen** [comment]
Duplicate of #57705

**Comment by richardh538** [comment]
Why has this issue been closed? The Additional context above is not solved.
`[DEBUG   ] Starting new HTTP connection (1): 127.0.0.1:8200
[DEBUG   ] http://127.0.0.1:8200 "GET /v1/salt/data HTTP/1.1" 404 232
[ERROR   ] Error from vault: {"request_id":"af546575-64bf-8254-ace3-b102df2c5efe","lease_id":"","renewable":false,"lease_duration":0,"data":null,"wrap_info":null,"warnings":["Non-listing operations on the root of a K/V v2 mount are not supported."],"auth":null}
[DEBUG   ] LazyLoaded local_cache.prep_jid
[DEBUG   ] Sending event: tag = salt/run/20201112084715709358/ret; data = {'fun': 'runner.sdb.get', 'jid': '20201112084715709358', 'user': 'salt', 'fun_args': ['sdb://myvault/salt/data/user1'], '_stamp': '2020-11-12T08:47:15.928509', 'return': None, 'success': True}
[DEBUG   ] LazyLoaded json.output
null
[INFO    ] Runner completed: 20201112084715709358
[DEBUG   ] Closing IPCMessageClient instance
[DEBUG   ] Runner return: None
`

**Comment by lfanew** [comment]
> Why has this issue been closed? The Additional context above is not solved. I have applied the patches done for "uses".
> 
> [DEBUG ] Starting new HTTP connection (1): 127.0.0.1:8200
> [DEBUG ] http://127.0.0.1:8200 "GET /v1/salt/data HTTP/1.1" 404 232
> [ERROR ] Error from vault: {"request_id":"af546575-64bf-8254-ace3-b102df2c5efe","lease_id":"","renewable":false,"lease_duration":0,"data":null,"wrap_info":null,"warnings":["**Non-listing operations on the root of a K/V v2 mount are not supported**."],"auth":null}
> [DEBUG ] LazyLoaded local_cache.prep_jid
> [DEBUG ] Sending event: tag = salt/run/20201112084715709358/ret; data = {'fun': 'runner.sdb.get', 'jid': '20201112084715709358', 'user': 'salt', 'fun_args': ['sdb://myvault/salt/data/user1'], '_stamp': '2020-11-12T08:47:15.928509', 'return': None, 'success': True}
> [DEBUG ] LazyLoaded json.output
> null
> [INFO ] Runner completed: 20201112084715709358
> [DEBUG ] Closing IPCMessageClient instance
> [DEBUG ] Runner return: None
> `

**Cross-posting [my comment](https://github.com/saltstack/salt/pull/57739#issuecomment-753373436) from issue #57739 for visibility.**

I also ran into this while following SaltStack's [Quick Guide for Vault Integration](https://help.saltstack.com/hc/en-us/articles/360041140451-Quick-Guide-to-Vault-Integration). I believe the problem lies within the guide.

* It instructs you to retrieve an entire secret (user1) with sdb.vault.get
    * `salt-run sdb.get 'sdb://myvault/salt/data/user1'`
    * Running this will give you the error stated above - **Non-listing operations on the root of a K/V v2 mount are not supported**.
* Looking at the guide, `salt/data/user1` was a secret defined with two KV fields
    * `vault kv put salt/user1 password=p4ssw0rd desc="test user"` - so this secrets contains two KV pairs.
*  Now, looking at the documentation for sdb.vault.get we see the function documented as:
    * `salt.sdb.vault.get(key, profile=None)` - **Get a value from the vault service**
* Notice how sdb.vault.get takes a _key_ as an argument, not a secret. With that in mind let's run something that works.
    * `salt-run sdb.get 'sdb://myvault/salt/data/user1/password`
        * [OUT] **p4ssw0rd**
    * `salt-run sdb.get 'sdb://myvault/salt/data/user1/desc`
        * [OUT] **test user**

Hopefully I save a headache or two of anyone googling while losing their patience at this point in the guide.
