### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by tnelson-doghouse** [saltstack/salt#58009]
**Problem:** 
Ex. I'm always frustrated when I get a useless error like this one:
```
2020-07-23 05:21:10,679 [salt.utils.templates:179 ][ERROR   ][20272] Rendering exception occurred
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 400, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 21, in top-level template code
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'backup-01.stack.host'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 166, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 407, in render_jinja_tmpl
    raise SaltRenderError("Jinja variable {0}{1}".format(exc, out), buf=tmplstr)
salt.exceptions.SaltRenderError: Jinja variable 'dict object' has no attribute 'backup-01.stack.host'
```
**Describe the solution you'd like**
First, I'd like to see an error message that **doesn't** contain a python stack trace.  This might be useful to those actually working on Salt, but it's not useful to me as someone trying to debug my own Salt configuration.  I mean, sure, if you want to put the python stuff *after* a useful error message, fine, but as just about the only thing?  No.  

Second, I'd like to see an error message that **does** contain:

- The name of the file that the problem occurred in.  Preferably the full path name.  Even if it begins with salt:// or something, I'd like to have some indication of where it's coming from
- The line number that the error occurred on.  That'd be handy.  
- The name of the actual variable involved.  I'm sure I don't have a variable called 'dict object' (and I think if I did I'd be twice as confused).  But what's the variable that doesn't have the attribute?  
- For bonus points, an excerpt from the file containing the line with the problem, and a big arrow pointing at it like you have in some of your other messages

Some of the info may be buried in the error that Salt gives, but I'm not familiar enough with Salt internals to locate it.  

**Describe alternatives you've considered**
I considered continuing to put up with it

**Additional context**
Sorry if I sound frustrated (I am), and thanks for all the work you guys do on Salt.

**Comment by sagetherage** [comment]
We should have a better error message so changing this to a Bug instead of a Feature request and looking to get this done in the next release cycle.

**Comment by dwoz** [comment]
Fixed in v3005 by d4731a548d6 ('Print jinja error context on UndefinedError'). `SaltRenderError` now reports `; line N` and a source excerpt with a marker at the offending line for `UndefinedError`. Regression test: `tests/pytests/unit/utils/templates/test_jinja.py::test_undefined_error_context`. Closing.
