### ISSUE TITLE
  ssh_auth.manage: does not get in ssh keys defined from source:

### ISSUE THREAD

**Issue by jamesbernardi** [saltstack/salt#58021]
version salt 3001

```
sshkeys:
  ssh_auth.manage:
    - user: root
    - source:
      - salt://user/key/user
```

errors with:

```
----------
          ID: sshkeys
    Function: ssh_auth.manage
      Result: False
     Comment: Missing parameter ssh_keys for state ssh_auth.manage
     Changes:   
----------
```

Adding ssh_keys and source gives this error:

```
sshkeys:
  ssh_auth.manage:
    - user: root
    - source:
      - salt://users/keys/user
    - ssh_keys:
      - ***************************************************


----------
          ID: sshkeys
    Function: ssh_auth.manage
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3.7/site-packages/salt/state.py", line 2154, in call
                  *cdata["args"], **cdata["kwargs"]
                File "/usr/lib/python3.7/site-packages/salt/loader.py", line 2087, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3.7/site-packages/salt/states/ssh_auth.py", line 610, in manage
                  **kwargs
                File "/usr/lib/python3.7/site-packages/salt/states/ssh_auth.py", line 313, in present
                  source_path = __salt__["cp.get_url"](source, None, saltenv=__env__)
                File "/usr/lib/python3.7/site-packages/salt/modules/cp.py", line 401, in get_url
                  path, None, makedirs, saltenv, no_cache=True, source_hash=source_hash
                File "/usr/lib/python3.7/site-packages/salt/fileclient.py", line 474, in get_url
                  url_data = urlparse(url)
                File "/usr/lib64/python3.7/urllib/parse.py", line 367, in urlparse
                  url, scheme, _coerce_result = _coerce_args(url, scheme)
                File "/usr/lib64/python3.7/urllib/parse.py", line 123, in _coerce_args
                  return _decode_args(args) + (_encode_result,)
                File "/usr/lib64/python3.7/urllib/parse.py", line 107, in _decode_args
                  return tuple(x.decode(encoding, errors) if x else '' for x in args)
                File "/usr/lib64/python3.7/urllib/parse.py", line 107, in <genexpr>
                  return tuple(x.decode(encoding, errors) if x else '' for x in args)
              AttributeError: 'list' object has no attribute 'decode'
     Started: 21:06:56.948868
    Duration: 4.652 ms
     Changes:
```

looking at: https://github.com/saltstack/salt/blob/2ea43cc291f228553cfd609199b0233803af6b31/salt/states/ssh_auth.py#L523 
I don't see any instructions for the source like I do the others.

**Comment by Ch3LL** [comment]
Looks like source should not be a list. Try this:

```
sshkeys:
  ssh_auth.manage:
    - user: root
    - ssh_keys:
      - AAAAB3NzaC1kc3MAAACBAL0sQ9fJ5bYTEyY==
    - source: salt://user/key/user
```

We should still clean this up so we do not stack trace though and include a useful error for the user, so i will label as a bug to get that fixed up.

**Comment by jamesbernardi** [comment]
Thanks I did end up realizing that it can only take 1 source.

I was trying to add multiple keys from different source files

which would be a nice to have
