### ISSUE TITLE
[BUG] Creating a salt-master vm on azurearm fails

### ISSUE THREAD

**Issue by markododa** [saltstack/salt#58096]
following the cloud map guide, specifically the part on setting up new salt master https://docs.saltstack.com/en/latest/topics/cloud/map.html#setting-up-new-salt-masters, i have the map file:

`azure_ubuntu:
  - smvm:
      make_master: True
`
backed up by the following profile:

`azure_ubuntu:
  provider: my-azurearm-config
  image: Canonical|UbuntuServer|18.04-LTS|latest
  size: Basic_A0
  #location: westus
  #network: my_network
  #subnet: subnet
  #resource_group: my_rg
  allocate_public_ip: True
  ssh_username: azureuser
  ssh_publickeyfile: /root/.ssh/id_rsa.pub
  ssh_keyfile: /root/.ssh/id_rsa
  disable_password_authentication: True`

Launching a regular instance works just fine however when make_master is True, salt-cloud trows the following error

`[ERROR   ] There was a query error: dictionary update sequence element #0 has length 1; 2 is required
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/cloud/cli.py", line 352, in run
    ret = mapper.run_map(dmap)
  File "/usr/lib/python3/dist-packages/salt/cloud/__init__.py", line 2126, in run_map
    out = self.create(master_profile, local_master=local_master)
  File "/usr/lib/python3/dist-packages/salt/cloud/__init__.py", line 1242, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python3/dist-packages/salt/cloud/clouds/azurearm.py", line 1362, in create
    ret = __utils__["cloud.bootstrap"](vm_, __opts__)
  File "/usr/lib/python3/dist-packages/salt/utils/cloud.py", line 547, in bootstrap
    master_conf = master_config(opts, vm_)
  File "/usr/lib/python3/dist-packages/salt/utils/cloud.py", line 361, in master_config
    "master", vm_, opts, default={}, search_global=True
ValueError: dictionary update sequence element #0 has length 1; 2 is required
`

**Comment by markododa** [comment]
However it seems like just adding a simple master section fixes it

```
azure_ubuntu:
  - master:
      make_master: True
      master:
        user: root
        interface: 0.0.0.0
```

**Comment by cmcmarrow** [comment]
@markododa looks like salt expects the master section and does not add defaults if missing. Is the documentations not clear about this? Do you think the documentations needs to make this  more clear?

**Comment by markododa** [comment]
I followed this doc https://docs.saltstack.com/en/latest/topics/cloud/map.html#setting-up-new-salt-masters.
There is no mention about master configuration.
