### ISSUE TITLE
[BUG] Unable to use salt-minion on Windows Server 2004

### ISSUE THREAD

**Issue by bociankruk** [saltstack/salt#58122]
**Description**
When I'm trying to call state.apply on Windows Server 2004 build (https://docs.microsoft.com/en-us/windows-server/get-started/whats-new-in-windows-server-2004), command fails. After quick troubleshooting looks like variable `grains["osrelease"]` equals None.

Here is a full log message:
```
PS C:\Users\Administrator> salt-call state.apply -l debug
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Using cached minion ID from c:\salt\conf\minion_id: ...
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Failed to read /proc/cmdline: [Errno 2] No such file or directory: '/proc/cmdline'
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-call", line 4, in <module>
    __import__('pkg_resources').run_script('salt==3001', 'salt-call')
  File "C:\salt\bin\lib\site-packages\pkg_resources\__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "C:\salt\bin\lib\site-packages\pkg_resources\__init__.py", line 1527, in run_script
    exec(code, namespace, namespace)
  File "c:\salt\bin\lib\site-packages\salt-3001-py3.7.egg\EGG-INFO\scripts\salt-call", line 10, in <module>
    salt_call()
  File "C:\salt\bin\lib\site-packages\salt-3001-py3.7.egg\salt\scripts.py", line 472, in salt_call
    client.run()
  File "C:\salt\bin\lib\site-packages\salt-3001-py3.7.egg\salt\cli\call.py", line 48, in run
    caller = salt.cli.caller.Caller.factory(self.config)
  File "C:\salt\bin\lib\site-packages\salt-3001-py3.7.egg\salt\cli\caller.py", line 64, in factory
    return ZeroMQCaller(opts, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt-3001-py3.7.egg\salt\cli\caller.py", line 329, in __init__
    super(ZeroMQCaller, self).__init__(opts)
  File "C:\salt\bin\lib\site-packages\salt-3001-py3.7.egg\salt\cli\caller.py", line 89, in __init__
    self.minion = salt.minion.SMinion(opts)
  File "C:\salt\bin\lib\site-packages\salt-3001-py3.7.egg\salt\minion.py", line 912, in __init__
    opts["grains"] = salt.loader.grains(opts)
  File "C:\salt\bin\lib\site-packages\salt-3001-py3.7.egg\salt\loader.py", line 825, in grains
    ret = funcs[key]()
  File "C:\salt\bin\lib\site-packages\salt-3001-py3.7.egg\salt\grains\core.py", line 1771, in os_data
    if "Server" in grains["osrelease"]:
TypeError: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-call", line 4, in <module>
    __import__('pkg_resources').run_script('salt==3001', 'salt-call')
  File "C:\salt\bin\lib\site-packages\pkg_resources\__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "C:\salt\bin\lib\site-packages\pkg_resources\__init__.py", line 1527, in run_script
    exec(code, namespace, namespace)
  File "c:\salt\bin\lib\site-packages\salt-3001-py3.7.egg\EGG-INFO\scripts\salt-call", line 10, in <module>
    salt_call()
  File "C:\salt\bin\lib\site-packages\salt-3001-py3.7.egg\salt\scripts.py", line 472, in salt_call
    client.run()
  File "C:\salt\bin\lib\site-packages\salt-3001-py3.7.egg\salt\cli\call.py", line 48, in run
    caller = salt.cli.caller.Caller.factory(self.config)
  File "C:\salt\bin\lib\site-packages\salt-3001-py3.7.egg\salt\cli\caller.py", line 64, in factory
    return ZeroMQCaller(opts, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt-3001-py3.7.egg\salt\cli\caller.py", line 329, in __init__
    super(ZeroMQCaller, self).__init__(opts)
  File "C:\salt\bin\lib\site-packages\salt-3001-py3.7.egg\salt\cli\caller.py", line 89, in __init__
    self.minion = salt.minion.SMinion(opts)
  File "C:\salt\bin\lib\site-packages\salt-3001-py3.7.egg\salt\minion.py", line 912, in __init__
    opts["grains"] = salt.loader.grains(opts)
  File "C:\salt\bin\lib\site-packages\salt-3001-py3.7.egg\salt\loader.py", line 825, in grains
    ret = funcs[key]()
  File "C:\salt\bin\lib\site-packages\salt-3001-py3.7.egg\salt\grains\core.py", line 1771, in os_data
    if "Server" in grains["osrelease"]:
TypeError: argument of type 'NoneType' is not iterable
```

**Setup**
None

**Steps to Reproduce the behavior**
1. Install salt-minion. Connection to salt-master is not needed.
2. Run ```salt-call state.apply```

**Expected behavior**
Run ```salt-call state.apply``` with success.

**Screenshots**
None

**Versions Report**
```
PS C:\Users\Administrator> salt-minion --versions-report
Salt Version:
           Salt: 3001

Dependency Versions:
           cffi: 1.12.2
       cherrypy: 17.4.1
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.10
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: Not Installed
   pycryptodome: 3.9.7
         pygit2: Not Installed
         Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
   python-gnupg: 0.4.4
         PyYAML: 5.1.2
          PyZMQ: 18.0.1
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: UnknownServer
         system: Windows
        version: UnknownServer 10.0.19041 SP0
```
</details>

**Additional context**

**Comment by garethgreenaway** [comment]
@bociankruk Thanks for the report.  We do not support that version of Windows Server, we support 2008, 2012, 2016, and 2019
per our supported operating system document, https://get.saltstack.com/rs/304-PHQ-615/images/SaltStack-Supported-Operating-Systems.pdf

**Comment by bociankruk** [comment]
Thanks for quick reply. Just to clarify, are there any plans to add support for other builds of Windows Server (like 2004)?

**Comment by morsik** [comment]
Hmm… I just looked into MS docs, and looks like MS did some inconsistency in naming. At first I thought it's Windows Server released in 2004 year which makes sense not to support by SaltStack as they mention they support 2008, 2012, 2016 and 2019.

But looking further into https://support.microsoft.com/en-us/lifecycle/search/19616 looks like MS changes naming convention and 2004 is not year, but YYMM format like they did in desktop Windows version. If so - then this should be changed to some sort of feature request.
