### ISSUE TITLE
[BUG] win_network.managed

### ISSUE THREAD

**Issue by rosscdh** [saltstack/salt#58138]
**Description**
Network Adapter not able to be referenced by name

**Setup**
setup a network.managed state for a windows minion

hwa exists

```
salt lab.ws02 network.hw_addr 'Realtek PCIe GBE Family Controller'
lab.ws02:
    00:19:99:F1:7B:9A
```

**Steps to Reproduce the behavior**
```
          ID: install_net_adapter_'434355045'
    Function: network.managed
        Name: Realtek PCIe GBE Family Controller
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "c:\salt\bin\lib\site-packages\salt-3001-py3.7.egg\salt\state.py", line 2154, in call
                  *cdata["args"], **cdata["kwargs"]
                File "c:\salt\bin\lib\site-packages\salt-3001-py3.7.egg\salt\loader.py", line 2087, in wrapper
                  return f(*args, **kwargs)
                File "c:\salt\bin\lib\site-packages\salt-3001-py3.7.egg\salt\states\win_network.py", line 321, in managed
                  if not __salt__["ip.enable"](name):
                File "c:\salt\bin\lib\site-packages\salt-3001-py3.7.egg\salt\modules\win_ip.py", line 174, in enable
                  if is_enabled(iface):
                File "c:\salt\bin\lib\site-packages\salt-3001-py3.7.egg\salt\modules\win_ip.py", line 147, in is_enabled
                  raise CommandExecutionError("Interface '{0}' not found".format(iface))
              salt.exceptions.CommandExecutionError: Interface 'Realtek PCIe GBE Family Controller' not found
     Started: 16:05:17.473680
    Duration: 197.266 ms

```

**Expected behavior**
network adapter is configured as desired

**Screenshots**

**Versions Report**

```
/ # salt --versions-report
Salt Version:
           Salt: 3001

Dependency Versions:
           cffi: 1.14.0
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 4.0.5
      gitpython: 3.1.7
         Jinja2: 2.11.2
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: Not Installed
   pycryptodome: 3.9.8
         pygit2: Not Installed
         Python: 3.7.8 (default, Jun 30 2020, 19:02:38)
   python-gnupg: Not Installed
         PyYAML: 5.3.1
          PyZMQ: 19.0.1
          smmap: 3.0.4
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2

System Versions:
           dist: alpine 3.12.0
         locale: UTF-8
        machine: x86_64
        release: 4.19.0-9-amd64
         system: Linux
        version: Alpine Linux 3.12.0
```

```
PASTE HERE
```
</details>

**Additional context**

**Comment by garethgreenaway** [comment]
@cmcmarrow FYI.

**Comment by rosscdh** [comment]
Or does it rather expect the "other" windows name "Ethernet" ?

**Comment by rosscdh** [comment]
This looks to be related to the bug i filed today about language
https://github.com/saltstack/salt/issues/58361

**Comment by twangboy** [comment]
@cmcmarrow Looks like we may need to look at rewriting the `win_network` module to use pywin32 or dotNET to avoid the localization issues.

**Comment by Timmeeh** [comment]
Also ran into this. Don't think [60522](https://github.com/saltstack/salt/pull/60522) would have fixed; rather looks like a quoting issue.

```
PS C:\Windows\system32> netsh interface show interface

Admin State    State          Type             Interface Name
-------------------------------------------------------------------------
Enabled        Connected      Dedicated        Ethernet 5
Enabled        Disconnected   Dedicated        Ethernet 6

PS C:\Windows\system32> netsh interface show interface "name=Ethernet 5"

Ethernet 5
   Type:                 Dedicated
   Administrative state: Enabled
   Connect state:        Connected

PS C:\Windows\system32> netsh interface show interface 'name=Ethernet 5'

Ethernet 5
   Type:                 Dedicated
   Administrative state: Enabled
   Connect state:        Connected

PS C:\Windows\system32> salt-call cmd.run "netsh interface show interface 'name=Ethernet 5'"
local:
    ''name' is not a valid argument for this command.
    The syntax supplied for this command is not valid. Check help for the correct syntax.

    Usage: show interface [[name=]string]

    Parameters:

          Tag              Value
          name           - Name of a specific interface to show current
                           parameter settings.

    Remarks: Shows interface parameters.

    Examples:

           show interface name="Wired Ethernet Connection"

PS C:\Windows\system32> salt-call cmd.run 'netsh interface show interface \"name=Ethernet 5\"'
local:

    Ethernet 5
       Type:                 Dedicated
       Administrative state: Enabled
       Connect state:        Connected
```

Changing https://github.com/saltstack/salt/blob/5c86f6d0d45fc22bf3900fba854ede5816879538/salt/modules/win_ip.py#L135
to below appears to fix it (on a salt minion 3006.11)

```cmd = ["netsh", "interface", "show", "interface", f'"name={iface}"']```


Before

```
PS C:\Windows\system32> salt-call ip.is_enabled 'Ethernet 5'
Error running 'ip.is_enabled': Interface 'Ethernet 5' not found
```

After
```
PS C:\Windows\system32> salt-call ip.is_enabled 'Ethernet 5'
local:
    True
```

However, to make the whole  `win_ip` module work all other instances of `f"name={iface}"` would also need to be replaced.

**Comment by twangboy** [comment]
https://github.com/saltstack/salt/pull/68314 uses the name instead of the description. This makes the state work.
