### ISSUE TITLE
I'm getting an error when trying to run a Thorium reactor

### ISSUE THREAD

**Issue by fabricioasap** [saltstack/salt#58316]
I understand this is probably not a bug, but I'm not sure what I'm doing wrong

**Description**
I'm getting an error when trying to run a Thorium reactor

**Setup**
```yaml
memusage_checker:
  reg.list:
    - name: minion1
    - add: memusage
    - match: salt/beacon/*/memusage/
    - stamp: True
    - prune: 50
  check.gt:
    - value: 80

shell_test:
  runner.cmd:
    - func: http.query
    - arg:
      - http://192.168.0.103:8000/api/v2/test_reactor/
    - kwargs:
      method: POST
    - require:
      - check: memusage_checker
```

**Steps to Reproduce the behavior**
```
[DEBUG   ] Reactor is populating check client cache
[DEBUG   ] Closing IPCMessageSubscriber instance
[ERROR   ] An un-handled exception from the multiprocessing process 'Reactor-4:1' was caught:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/process.py", line 897, in wrapped_run_func
    return run_func()
  File "/usr/lib/python3/dist-packages/salt/utils/reactor.py", line 309, in run
    self.call_reactions(chunks)
  File "/usr/lib/python3/dist-packages/salt/utils/reactor.py", line 232, in call_reactions
    self.wrap.run(chunk)
  File "/usr/lib/python3/dist-packages/salt/utils/reactor.py", line 373, in run
    self.populate_client_cache(low)
  File "/usr/lib/python3/dist-packages/salt/utils/reactor.py", line 365, in populate_client_cache
    self.client_cache[reaction_type] = self.reaction_class[reaction_type](
KeyError: 'check'
[CRITICAL] Engine 'reactor' could not be started!
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/engines/__init__.py", line 135, in run
    self.engine[self.fun](**kwargs)
  File "/usr/lib/python3/dist-packages/salt/engines/reactor.py", line 35, in start
    salt.utils.reactor.Reactor(__opts__).run()
  File "/usr/lib/python3/dist-packages/salt/utils/process.py", line 911, in wrapped_run_func
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3/dist-packages/salt/ext/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/salt/utils/process.py", line 897, in wrapped_run_func
    return run_func()
  File "/usr/lib/python3/dist-packages/salt/utils/reactor.py", line 309, in run
    self.call_reactions(chunks)
  File "/usr/lib/python3/dist-packages/salt/utils/reactor.py", line 232, in call_reactions
    self.wrap.run(chunk)
  File "/usr/lib/python3/dist-packages/salt/utils/reactor.py", line 373, in run
    self.populate_client_cache(low)
  File "/usr/lib/python3/dist-packages/salt/utils/reactor.py", line 365, in populate_client_cache
    self.client_cache[reaction_type] = self.reaction_class[reaction_type](
KeyError: 'check'
```

**Versions Report**
<details><summary>
```
Salt Version:
           Salt: 3001.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 2.0.6
      gitpython: 3.0.7
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: 3.6.1
         pygit2: Not Installed
         Python: 3.8.2 (default, Jul 16 2020, 14:00:26)
   python-gnupg: 0.4.5
         PyYAML: 5.3.1
          PyZMQ: 18.1.1
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2

System Versions:
           dist: ubuntu 20.04 focal
         locale: utf-8
        machine: x86_64
        release: 5.4.0-42-generic
         system: Linux
        version: Ubuntu 20.04 focal</summary> 

```
</summary>
</details>

Thanks

**Comment by dwoz** [comment]
I belive this:

```
    - require:
      - check: memusage_checker
```

Should be 
```
    - require:
      - memusage_checker
```

**Comment by Ch3LL** [comment]
Closing due to inactivity. If the suggestion from @dwoz is still not working and this is a bug on the latest version of Salt please open a new issue the the details.
