### ISSUE TITLE
Debian 9 tests not starting

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#58335]
**Description**
The debian 9 tests are not starting
https://jenkinsci.saltstack.com/job/pr-debian9-py3-slow/job/master/449

```
23:44:51         Traceback (most recent call last):
23:44:51           File "<string>", line 1, in <module>
23:44:51           File "<frozen importlib._bootstrap>", line 969, in _find_and_load
23:44:51           File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
23:44:51           File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
23:44:51           File "<frozen importlib._bootstrap>", line 577, in module_from_spec
23:44:51           File "/tmp/kitchen/testing/.nox/runtests-parametrized-3-coverage-true-crypto-none-transport-zeromq/lib/python3.5/site-packages/_distutils_hack/__init__.py", line 82, in create_module
23:44:51             return importlib.import_module('._distutils', 'setuptools')
23:44:51           File "/tmp/kitchen/testing/.nox/runtests-parametrized-3-coverage-true-crypto-none-transport-zeromq/lib/python3.5/importlib/__init__.py", line 126, in import_module
23:44:51             return _bootstrap._gcd_import(name[level:], package, level)
23:44:51           File "<frozen importlib._bootstrap>", line 981, in _gcd_import
23:44:51           File "<frozen importlib._bootstrap>", line 931, in _sanity_check
23:44:51         SystemError: Parent module 'setuptools' not loaded, cannot perform relative import
```

**Comment by Ch3LL** [comment]
also failing here:

https://jenkinsci.saltstack.com/job/pr-ubuntu1604-py3-m2crypto-slow/job/master/451/console

https://jenkinsci.saltstack.com/job/pr-ubuntu1604-py3-proxy-slow/job/master/449/console

https://jenkinsci.saltstack.com/job/pr-ubuntu1604-py3-pycryptodome-slow/job/master/451/console

https://jenkinsci.saltstack.com/job/pr-ubuntu1604-py3-slow/job/master/452/console

https://jenkinsci.saltstack.com/job/pr-ubuntu1604-py3-tcp-slow/job/master/451/console

**Comment by Ch3LL** [comment]
should be fixed by https://github.com/saltstack/salt/pull/58337

**Comment by Ch3LL** [comment]
tests are running now
