### ISSUE TITLE
[BUG] module.run return error UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 113: ordinal not in range(128)

### ISSUE THREAD

**Issue by pankajghadge** [saltstack/salt#58365]
**Description**

There is some UTF8 character in module.run which might causing this issue. I have seen this kind of error in salt issues but it was for other modules.
I think we need the same bug fix for module.run 

```
  Function: module.run
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1933, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1951, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/utils/decorators/__init__.py", line 631, in _decorate
                  return self._call_function(kwargs)
                File "/usr/lib/python2.7/site-packages/salt/utils/decorators/__init__.py", line 334, in _call_function
                  raise error
              UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 113: ordinal not in range(128)
     Started: 14:30:45.508369
    Duration: 4186489.657 ms
     Changes:   
```

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info).

**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

**Expected behavior**
it should return proper output with UTF8 character support 

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 2019.2.4

Dependency Versions:
           cffi: 1.14.2
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: 3.8.2
         pygit2: Not Installed
         Python: 2.7.5 (default, Jun 11 2019, 12:19:05)
   python-gnupg: 0.4.4
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.5 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1127.18.2.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.5 Maipo

```
</details>

**Additional context**

**Comment by garethgreenaway** [comment]
@pankajghadge Thanks for the report.  Can you provide an example state where you're calling `module.run` and receiving this error?  Thanks!

**Comment by garethgreenaway** [comment]
Closing this issue due to age and lack of activity. Please test this on version 3006.2 and create a new issue if the problem persists. The new issue template has more information and will allow us to track and reproduce the issue more effectively. Thanks!
