### ISSUE TITLE
[BUG] Minion fails to start on Windows if timezone cannot be determined

### ISSUE THREAD

**Issue by lukasraska** [saltstack/salt#58379]
**Description**
When Windows timezone cannot be determined for any reason, if defaults to `Unknown`, which is invalid timezone for pytz and exception is raised. Due to scheduler relying on `timezone.get_offset` not raising exception, it then fails in initialization, hence whole minion fails to start.

**Setup**
Windows system where timezone is unknown (the exact reason is not clear).

**Steps to Reproduce the behavior**
Possibly empty values in following registry keys:
```
HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Time Zones 
HKLM\System\CurrentControlSet\Control\TimeZoneInformation
```

Then start minion and encounter:
```
2020-09-02 11:10:37,702 [salt.minion      :1050][CRITICAL][972] Unexpected error while connecting to <master>
Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1027, in _connect_minion
    yield minion.connect_master(failed=failed)
  File "c:\salt\bin\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "c:\salt\bin\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "c:\salt\bin\lib\site-packages\tornado\gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1226, in connect_master
    yield self._post_master_init(master)
  File "c:\salt\bin\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "c:\salt\bin\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "c:\salt\bin\lib\site-packages\tornado\gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1273, in _post_master_init
    cleanup=[master_event(type='alive')])
  File "c:\salt\bin\lib\site-packages\salt\utils\schedule.py", line 105, in __new__
    utils=utils)
  File "c:\salt\bin\lib\site-packages\salt\utils\schedule.py", line 152, in __singleton_init__
    self.time_offset = self.functions.get('timezone.get_offset', lambda: '0000')()
  File "c:\salt\bin\lib\site-packages\salt\modules\win_timezone.py", line 241, in get_offset
    tz_object = pytz.timezone(get_zone())
  File "c:\salt\bin\lib\site-packages\pytz\__init__.py", line 181, in timezone
    raise UnknownTimeZoneError(zone)
pytz.exceptions.UnknownTimeZoneError: 'Unknown'
```

**Expected behavior**
Minion starts and connects to master, even with default timezone.

**Versions Report**
At least 2019.2 through 3001 minions on Windows (found on Windows 2008 R2)

**Additional context**
Related to https://support.microsoft.com/en-us/help/2562433/the-timezonekeyname-registry-entry-value-changes-to-a-null-value-in-wi and https://github.com/saltstack/salt/issues/50667

**Comment by cmcmarrow** [comment]
Hello, @lukasraska what time zone is your computer in and what language is windows set to?

**Comment by lukasraska** [comment]
Hi @cmcmarrow, well basically it can be any kind of timezone and language. The problem is that Salt (not Windows) is returning "Unknown" as timezone, when no timezone is found (https://github.com/saltstack/salt/blob/master/salt/modules/win_timezone.py#L227) and that's actually invalid name for pytz (which raises this exception, my exception was from 2019.2, the new exception will most likely be `CommandExecutionError` because of https://github.com/saltstack/salt/commit/32aeff6b6e33130f6670265361cedbe1b4d21926).

The issue can be easily reproduced just by mangling with registries (which in some cases can happen by manual error, or in this case where I've discovered - by bad Windows update). For example this clean AWS Win 2019 VM, English locale, UTC timezone:
```
PS C:\salt> .\salt-minion.bat --versions-report
Salt Version:
           Salt: 3001.1

Dependency Versions:
           cffi: 1.12.2
       cherrypy: 17.4.1
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 1.0.0
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: Not Installed
   pycryptodome: 3.9.7
         pygit2: Not Installed
         Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
   python-gnupg: 0.4.4
         PyYAML: 5.3.1
          PyZMQ: 18.0.1
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2019Server
         system: Windows
        version: 2019Server 10.0.17763 SP0
``` 


If you mess with registry `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\TimeZoneInformation` (for example rename it), you get following error:
```
PS C:\salt> .\salt-call.bat --local timezone.get_zone
[ERROR   ] Command '['tzutil', '/g']' failed with return code: 515
[ERROR   ] stdout: TZUTIL: Failed to get the system time zone id.
[ERROR   ] retcode: 515
Error running 'timezone.get_zone': tzutil encountered an error getting timezone. Additional info follows:

pid:
    1532
retcode:
    515
stderr:
stdout:
    TZUTIL: Failed to get the system time zone id.
```


And when you actually run the minion and it connects to the master, it results with:
```
[CRITICAL] Unexpected error while connecting to <master>
Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt-3001.1-py3.7.egg\salt\minion.py", line 1120, in _connect_minion
    yield minion.connect_master(failed=failed)
  File "C:\salt\bin\lib\site-packages\salt-3001.1-py3.7.egg\salt\ext\tornado\gen.py", line 1056, in run
    value = future.result()
  File "C:\salt\bin\lib\site-packages\salt-3001.1-py3.7.egg\salt\ext\tornado\concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "C:\salt\bin\lib\site-packages\salt-3001.1-py3.7.egg\salt\ext\tornado\gen.py", line 1064, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\salt\bin\lib\site-packages\salt-3001.1-py3.7.egg\salt\minion.py", line 1336, in connect_master
    yield self._post_master_init(master)
  File "C:\salt\bin\lib\site-packages\salt-3001.1-py3.7.egg\salt\ext\tornado\gen.py", line 1056, in run
    value = future.result()
  File "C:\salt\bin\lib\site-packages\salt-3001.1-py3.7.egg\salt\ext\tornado\concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "C:\salt\bin\lib\site-packages\salt-3001.1-py3.7.egg\salt\ext\tornado\gen.py", line 1070, in run
    yielded = self.gen.send(value)
  File "C:\salt\bin\lib\site-packages\salt-3001.1-py3.7.egg\salt\minion.py", line 1388, in _post_master_init
    cleanup=[master_event(type="alive")],
  File "C:\salt\bin\lib\site-packages\salt-3001.1-py3.7.egg\salt\utils\schedule.py", line 112, in __new__
    utils=utils,
  File "C:\salt\bin\lib\site-packages\salt-3001.1-py3.7.egg\salt\utils\schedule.py", line 167, in __singleton_init__
    self.time_offset = self.functions.get("timezone.get_offset", lambda: "0000")()
  File "C:\salt\bin\lib\site-packages\salt-3001.1-py3.7.egg\salt\modules\win_timezone.py", line 244, in get_offset
    tz_object = pytz.timezone(get_zone())
  File "C:\salt\bin\lib\site-packages\salt-3001.1-py3.7.egg\salt\modules\win_timezone.py", line 225, in get_zone
    "tzutil encountered an error getting timezone", info=res
salt.exceptions.CommandExecutionError: tzutil encountered an error getting timezone. Additional info follows:

pid:
    2556
retcode:
    515
stderr:
stdout:
    TZUTIL: Failed to get the system time zone id.
```

And it's then stuck in a loop, taking ~30% of CPU. Which in my opinion shouldn't do, although the error is obviously outside Salt. In case I apply the PR #58380 , the error is following:
```
PS C:\salt> .\salt-minion.bat
[ERROR   ] Command '['tzutil', '/g']' failed with return code: 515
[ERROR   ] stdout: TZUTIL: Failed to get the system time zone id.
[ERROR   ] retcode: 515
[WARNING ] Unable to obtain correct timezone offset, defaulting to 0000
Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt-3001.1-py3.7.egg\salt\utils\schedule.py", line 168, in __singleton_init__
    self.time_offset = self.functions.get("timezone.get_offset", lambda: "0000")()
  File "C:\salt\bin\lib\site-packages\salt-3001.1-py3.7.egg\salt\modules\win_timezone.py", line 244, in get_offset
    tz_object = pytz.timezone(get_zone())
  File "C:\salt\bin\lib\site-packages\salt-3001.1-py3.7.egg\salt\modules\win_timezone.py", line 225, in get_zone
    "tzutil encountered an error getting timezone", info=res
salt.exceptions.CommandExecutionError: tzutil encountered an error getting timezone. Additional info follows:

pid:
    5804
retcode:
    515
stderr:
stdout:
    TZUTIL: Failed to get the system time zone id.
```

But minion is working and CPU utilisation is normal.

**Comment by cmcmarrow** [comment]
@lukasraska thanks for extra information. The reason why I asked for the language and time zone is because I have had time zone errors due to those variables and I want to make sure I can reproduce it.

**Comment by jbfriedrich** [comment]
I just ran into the same issue on Windows Server 2012 R2 machines that are set to the timezone "(UTC-03:00) Brasilia". It is currently no clear to me why tzutil is not able to identify the time zone. The language is set to English (US), Minion version is 3002.2.

**Comment by oeuftete** [comment]
ZD-6230.

**Comment by oeuftete** [comment]
While investigating the issue with @jbfriedrich as [reported above](https://github.com/saltstack/salt/issues/58379#issuecomment-762711344), we found that time zones that can be set to toggled to adjust for DST, and that have toggled this off, will cause this problem.   Timezones like this are returned from `tzutil /g` with a `_dstoff` suffix, e.g.:

```
PS C:\Users\vagrant> tzutil /g
Pacific Standard Time_dstoff
```

As these suffixed zones are not in the hard-coded map, the conversion to a unix zone comes back as `Unknown`.

Would the proper solution be to update `salt.modules.win_timezone.TzMapper` to discard the `_dstoff` suffix if present?

**Comment by lukasraska** [comment]
@Ch3LL can you please reopen this? #59341 doesn't solve this issue, #58380 does
