### ISSUE TITLE
[BUG] slack returner fail when `changes: True`

### ISSUE THREAD

**Issue by skob** [saltstack/salt#58375]
**Description**
slack returner don't work with
slack.changes or slack.only_show_failed

**Setup**
salt 3001.1 on master/minion on ubuntu16.04

**Expected behavior**
receive report on changes or failed states

**Additional context**
```
2020-09-04 08:52:09,266 [salt.minion      :1820][ERROR   ][2638] The return failed for job 20200904085127809008: unhashable type: 'dict'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 1811, in _thread_return
    minion_instance.returners[returner_str](ret)
  File "/usr/lib/python3/dist-packages/salt/returners/slack_returner.py", line 218, in returner
    returns = {(key, value) for key, value in returns.items() if value['result'] is not True or value['changes']}
  File "/usr/lib/python3/dist-packages/salt/returners/slack_returner.py", line 218, in <setcomp>
    returns = {(key, value) for key, value in returns.items() if value['result'] is not True or value['changes']}
TypeError: unhashable type: 'dict'
```

**Comment by Ch3LL** [comment]
can you also include how you are running the returner command to help replicate the issue?

**Comment by skob** [comment]
```
salt minion --return slack state.apply 11
```
```
cat 11.sls
always-fails:
  test.fail_without_changes:
    - name: foo
```
```
cat /etc/salt/minion.d/slack.conf
slack:
  channel: '@skob'
  api_key: '<skipped>'
  username: salt
  as_user: true
  changes: true
  yaml_format: true
```
```
cat /var/log/salt/minion
2020-09-08 19:23:49,812 [salt.state       :328 ][ERROR   ][49959] Failure!
2020-09-08 19:23:49,912 [salt.minion      :2022][ERROR   ][49959] The return failed for job 20200908192349072798: unhashable type: 'dict'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 2011, in _thread_return
    minion_instance.returners[returner_str](ret)
  File "/usr/lib/python3/dist-packages/salt/returners/slack_returner.py", line 227, in returner
    for key, value in returns.items()
  File "/usr/lib/python3/dist-packages/salt/returners/slack_returner.py", line 228, in <setcomp>
    if value["result"] is not True or value["changes"]
TypeError: unhashable type: 'dict'
```

**Comment by Ch3LL** [comment]
thanks. looks like we need to get this cleaned up.

**Comment by garethgreenaway** [comment]
Does this returner still work since Slack changed their connection requirements? I wonder if we should deprecate it in favor of the `slack_webook_return` returner?
