### ISSUE TITLE
[BUG] Salt highstate sometimes "missing" a few minions

### ISSUE THREAD

**Issue by paladin8** [saltstack/salt#58387]
**Description**
This is admittedly going to be quite vague, so any pointers toward debugging steps would be valuable. We use salt quite intensively to deploy new code to our systems. It pretty much looks like highstate on a specific cluster (matching based on EC2 tags that are stored as grains) that causes new code to be downloaded.

What we observe a small fraction of the time (1-5%) is that not all of the minions actually respond to the highstate despite the fact that they appear to be connected fine. This happens most with our large clusters (100-200 nodes), and it's usually just handful (<5, often just 1) that are missing. A subsequent highstate will have all the nodes respond, so it's not like the minion died or anything, it just didn't respond to that one command.

Is there any logging or debugging info that can be found/enabled on the master/minion to identify transient disconnects? We've been running into this for months if not years, so happy to configure anything that gives us long-term potential to debug.

**Setup**
Nothing I can think of that would be helpful, but please let me know what I can provide.

**Steps to Reproduce the behavior**
Run highstate, e.g. `sudo salt -C 'G@ec2_tags:cluster:...' state.highstate`, and occasionally a small number of minions will not be affected.

**Expected behavior**
All salt minions matching the search should run the highstate.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 2019.2.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.0
      docker-py: 1.10.6
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: 0.3.8
         PyYAML: 3.12
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-1022-aws
         system: Linux
        version: Ubuntu 16.04 xenial
 
```
</details>

I'll node that this was happening on the previous version we were running, `2018.3.5`, as well.

**Comment by Ch3LL** [comment]
Can we get some more information when this does occur.

1. Does the job actually run on the minion. 
2. Do you see it when you run `jobs.lookup_jid <jid>` on the master?
3. Is there any relative information when you enable debug logs on the minion or any errors?
4. If you increase the timeout when running the job `-t <seconds>` do you still see this behavior?

**Comment by paladin8** [comment]
@Ch3LL Thanks for the response.

1. No, the job doesn't appear to run at all.
2. Unsure, it's quite hard to figure this out since it's too nondeterministic to reproduce.
3. Will look into enabling debug logging.
4. Will try this as well.

One other data point is that I tried running a separate command (`cmd.run hostname`) instead of a highstate and did it across entire clusters in a tight loop. Over the course of hundreds of runs, there wasn't a single instance of a missing minion. So it's possible there's something subtle about the highstate which is much slower and does a lot more stuff that triggers this behavior.

**Comment by paladin8** [comment]
We were able to find evidence of this logging correlating with a minion not responding:
```
2020-09-18 19:26:02,316 [tornado.application:124 ][ERROR   ][18942] Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 569, in wrap_callback
    payload = yield self._decode_messages(messages)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 546, in _decode_messages
    ret = yield self._decode_payload(payload)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.7/dist-packages/salt/transport/mixins/auth.py", line 63, in _decode_payload
    yield self.auth.authenticate()
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
SaltClientError: Attempt to authenticate with the salt master failed with timeout error
```
This happened before we enabled the debug logging, next time we'll have more information.

**Comment by paladin8** [comment]
With the debug logging on, we're noticing a pretty high number of minion re-authentications on the master, e.g.
```
2020-09-18 23:39:18,271 [salt.transport.mixins.auth:184 ][INFO    ][14027] Authentication request from <REDACTED>
2020-09-18 23:39:18,271 [salt.transport.mixins.auth:407 ][INFO    ][14027] Authentication accepted from <REDACTED>
2020-09-18 23:39:18,272 [salt.crypt       :208 ][DEBUG   ][14027] salt.crypt.get_rsa_pub_key: Loading public key
2020-09-18 23:39:18,272 [salt.transport.mixins.auth:463 ][DEBUG   ][14027] Signing master public key before sending
2020-09-18 23:39:18,272 [salt.crypt       :200 ][DEBUG   ][14027] salt.crypt.get_rsa_key: Loading private key
2020-09-18 23:39:18,272 [salt.crypt       :225 ][DEBUG   ][14027] salt.crypt.sign_message: Signing message.
2020-09-18 23:39:18,274 [salt.utils.event :737 ][DEBUG   ][14018] Sending event: tag = salt/auth; data = {u'id': '<REDACTED>', u'_stamp': '2020-09-18T23:39:18.274465', u'result': True, u'pub': '<REDACTED>', u'act': u'accept'}
2020-09-18 23:39:18,275 [salt.utils.event :737 ][DEBUG   ][14013] Sending event: tag = salt/auth; data = {u'id': '<REDACTED>', u'_stamp': '2020-09-18T23:39:18.275055', u'result': True, u'pub': '<REDACTED>', u'act': u'accept'}
2020-09-18 23:39:18,275 [salt.transport.mixins.auth:184 ][INFO    ][14013] Authentication request from <REDACTED>
2020-09-18 23:39:18,275 [salt.transport.mixins.auth:407 ][INFO    ][14013] Authentication accepted from <REDACTED>
2020-09-18 23:39:18,276 [salt.crypt       :208 ][DEBUG   ][14013] salt.crypt.get_rsa_pub_key: Loading public key
2020-09-18 23:39:18,276 [salt.transport.mixins.auth:463 ][DEBUG   ][14013] Signing master public key before sending
2020-09-18 23:39:18,276 [salt.crypt       :200 ][DEBUG   ][14013] salt.crypt.get_rsa_key: Loading private key
2020-09-18 23:39:18,276 [salt.crypt       :225 ][DEBUG   ][14013] salt.crypt.sign_message: Signing message.
2020-09-18 23:39:18,281 [salt.utils.event :737 ][DEBUG   ][14027] Sending event: tag = salt/auth; data = {u'id': '<REDACTED>', u'_stamp': '2020-09-18T23:39:18.281065', u'result': True, u'pub': '<REDACTED>', u'act': u'accept'}
```
It's happening multiple times each second, even though these minions have been persistently around for a long time. Is this normal? We have 2-3k minions connected to a single master. On the minion side we see:
```
2020-09-18 23:38:01,981 [salt.crypt       :1450][DEBUG   ][2166] Failed to authenticate message
2020-09-18 23:38:01,982 [salt.transport.zeromq:138 ][DEBUG   ][2166] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/minion', u'<REDACTED>', u'<REDACTED>', 'clear')
2020-09-18 23:38:01,982 [salt.transport.zeromq:209 ][DEBUG   ][2166] Connecting the Minion to the Master URI (for the return server): <REDACTED>
2020-09-18 23:38:01,982 [salt.transport.zeromq:1189][DEBUG   ][2166] Trying to connect to: <REDACTED>
2020-09-18 23:38:01,983 [salt.crypt       :208 ][DEBUG   ][2166] salt.crypt.get_rsa_pub_key: Loading public key
2020-09-18 23:38:04,606 [salt.crypt       :873 ][DEBUG   ][2166] Decrypting the current master AES key
2020-09-18 23:38:04,606 [salt.crypt       :200 ][DEBUG   ][2166] salt.crypt.get_rsa_key: Loading private key
2020-09-18 23:38:04,606 [salt.crypt       :802 ][DEBUG   ][2166] Loaded minion key: /etc/salt/pki/minion/minion.pem
2020-09-18 23:38:04,609 [salt.crypt       :208 ][DEBUG   ][2166] salt.crypt.get_rsa_pub_key: Loading public key
2020-09-18 23:38:04,612 [salt.transport.zeromq:233 ][DEBUG   ][2166] Closing AsyncZeroMQReqChannel instance
2020-09-18 23:39:14,978 [salt.crypt       :1450][DEBUG   ][2166] Failed to authenticate message
2020-09-18 23:39:14,978 [salt.transport.zeromq:138 ][DEBUG   ][2166] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/minion', u'<REDACTED>', u'<REDACTED>', 'clear')
2020-09-18 23:39:14,978 [salt.transport.zeromq:209 ][DEBUG   ][2166] Connecting the Minion to the Master URI (for the return server): <REDACTED>
2020-09-18 23:39:14,978 [salt.transport.zeromq:1189][DEBUG   ][2166] Trying to connect to: <REDACTED>
2020-09-18 23:39:14,979 [salt.crypt       :208 ][DEBUG   ][2166] salt.crypt.get_rsa_pub_key: Loading public key
2020-09-18 23:39:18,271 [salt.crypt       :873 ][DEBUG   ][2166] Decrypting the current master AES key
2020-09-18 23:39:18,272 [salt.crypt       :200 ][DEBUG   ][2166] salt.crypt.get_rsa_key: Loading private key
2020-09-18 23:39:18,272 [salt.crypt       :802 ][DEBUG   ][2166] Loaded minion key: /etc/salt/pki/minion/minion.pem
2020-09-18 23:39:18,275 [salt.crypt       :208 ][DEBUG   ][2166] salt.crypt.get_rsa_pub_key: Loading public key
2020-09-18 23:39:18,278 [salt.transport.zeromq:233 ][DEBUG   ][2166] Closing AsyncZeroMQReqChannel instance
```
It seems like most of the time it does not escalate into the above timeout error, but maybe if it fails enough times it will.

**Comment by paladin8** [comment]
@Ch3LL I was wondering if any of these errors give you any insight into what might be happening here, thanks!

**Comment by Ch3LL** [comment]
tuning these settings might help out: https://docs.saltstack.com/en/master/topics/troubleshooting/master.html#salt-master-auth-flooding
