### ISSUE TITLE
user defined pillars unusable for other targets than dom0 in qubes

### ISSUE THREAD

**Issue by 100111001** [saltstack/salt#58386]
Using user defined pillars leads to an exception if tageting any other vm than dom0 in qubes.

To Reproduce
My pillars are located in
/srv/salt/user_pillar/

To enable them during a qubesctl execution, I'm running:
sudo qubesctl --show-output state.highstate --pillar-root=/srv/salt/user_pillar/

This works quite well when running this for dom0, but when I'm running it towards a target:
sudo qubesctl --show-output --target myTarget state.highstate --pillar-root=/srv/salt/user_pillar/

I receive this error after the disp-mgmt-vm starts:
ERROR (exception list index out of range)

Expected behavior
Pillars are applied same way like it's done for dom0 with:
sudo qubesctl --show-output state.highstate --pillar-root=/srv/salt/user_pillar/

Actual behavior
I receive this error after the disp-mgmt-vm starts:
ERROR (exception list index out of range)

Solutions you've tried

    Instead of using user defined pillars, it's possible to use jinja variables which does work.
    Passing pillars as command line params also doesn't work:
    sudo qubesctl --show-output --target myVM state.apply pillar=true pillar='{"myPillar":"value"}'
    this leads to this error:
    myVM:
    TypeError encountered executing state.apply: apply_() takes from 0 to 1 positional arguments but 7 were given
    Also the following fails:
    sudo qubesctl top.enable user_salt.myPersonalTopFile pillar=true

With the stack trace:
SaltRenderError: Could not find relpath for user_salt.myPersonalTopFile.top
Traceback (most recent call last):
File "/bin/qubesctl", line 110, in
salt_call()
File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 391, in salt_call
client.run()
File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 58, in run
caller.run()
File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 134, in run
ret = self.call()
File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 204, in call
ret['return'] = func(*args, **kwargs)
File "/var/cache/salt/minion/extmods/modules/topd.py", line 74, in enable
return TopUtils(opts, **kwargs).enable(paths, saltenv)
File "/var/cache/salt/minion/extmods/utils/toputils.py", line 600, in enable
toppaths, unseen = self.prepare_paths(paths)
File "/var/cache/salt/minion/extmods/utils/toputils.py", line 453, in prepare_paths
toppath = self.toppath(path)
File "/var/cache/salt/minion/extmods/utils/toputils.py", line 332, in toppath
saltenv = saltenv or self.saltenv(path, saltenv)
File "/var/cache/salt/minion/extmods/utils/pathutils.py", line 128, in saltenv
relpath = self.relpath(path)
File "/var/cache/salt/minion/extmods/utils/pathutils.py", line 486, in relpath
return self.path(path, saltenv)
File "/var/cache/salt/minion/extmods/utils/toputils.py", line 269, in path
return super(TopUtils, self).path(path, saltenv, path_type=path_type)
File "/var/cache/salt/minion/extmods/utils/pathutils.py", line 445, in path
raise SaltRenderError('Could not find relpath for {0}'.format(path))
salt.exceptions.SaltRenderError: Could not find relpath for user_salt.myPersonalTopFile.top
DOM0 configuration failed, not continuing

Relevant documentation you've consulted
https://www.qubes-os.org/doc/salt/
https://github.com/QubesOS/qubes-mgmt-salt
https://docs.saltstack.com/en/getstarted/config/pillar.html

**Versions Report**
Salt: 2017.7.1
Jinja2: 2.8.1

**Comment by 100111001** [comment]
This issue can be closed. I was pointed to the right direction in the qubes mailling list. In the upper solution I'm trying to use:
/srv/salt/user_salt
instead of the correct directory:
/srv/user_salt
