### ISSUE TITLE
[BUG] Nacl-encrypted values fail to render

### ISSUE THREAD

**Issue by centromere** [saltstack/salt#58436]
**Description**
When using nacl-encrypted Pillar values via git to serve the [consul-formula](https://github.com/saltstack-formulas/consul-formula) formula, the following error occurs upon running `state.apply`:

```
    Data failed to compile:
----------
    Pillar failed to render with the following messages:
----------
    Failed to decrypt pillar key 'consul': cannot use a string pattern on a bytes-like object
```

Interestingly, when running `pillar.items`, the value *is* decrypted properly:

```
    ----------
    _errors:
        - Failed to decrypt pillar key 'consul': cannot use a string pattern on a bytes-like object
    consul:
        ----------
...
           encrypt:
             foo
...
```

Debug log:
```
[ERROR   ] Failed to decrypt pillar key 'consul': cannot use a string pattern on a bytes-like object
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/pillar/__init__.py", line 1255, in decrypt_pillar
    ret = salt.utils.crypt.decrypt(
  File "/usr/lib/python3/dist-packages/salt/utils/crypt.py", line 99, in decrypt
    return rend_func(data, translate_newlines=translate_newlines)
  File "/usr/lib/python3/dist-packages/salt/renderers/nacl.py", line 102, in render
    return _decrypt_object(nacl_data, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/renderers/nacl.py", line 87, in _decrypt_object
    obj[key] = _decrypt_object(value, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/renderers/nacl.py", line 87, in _decrypt_object
    obj[key] = _decrypt_object(value, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/renderers/nacl.py", line 81, in _decrypt_object
    if re.search(NACL_REGEX, obj) is not None:
  File "/usr/lib/python3.8/re.py", line 199, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
```

If I modify [this line](https://github.com/saltstack/salt/blob/2df0b55d677db3d3526073e7c0d9a4d9002961cc/salt/renderers/nacl.py#L82), it works properly:

Old:
```
return __salt__["nacl.dec"](re.search(NACL_REGEX, obj).group(1), **kwargs)
```

New:
```
return __salt__["nacl.dec"](re.search(NACL_REGEX, obj).group(1), **kwargs).decode('utf-8')
```

**Setup**

1. Set up a Pillar served via git:
```
---
consul:
  config:
...
    encrypt: "NACL[Z6cIxxdhWF...]"
```

salt-master config:
```
decrypt_pillar:
  - "consul"
decrypt_pillar_default: nacl
decrypt_pillar_renderers:
  - nacl
```

**Steps to Reproduce the behavior**
Follow the setup steps above and run `state.apply`.

**Expected behavior**
`state.apply` succeeds.

**Versions Report**
<details><summary>salt --versions-report</summary>
```
Salt Version:
           Salt: 3001.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10.1
        libgit2: 0.28.3
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: 3.6.1
         pygit2: 1.0.3
         Python: 3.8.2 (default, Jul 16 2020, 14:00:26)
   python-gnupg: 0.4.5
         PyYAML: 5.3.1
          PyZMQ: 18.1.1
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2

System Versions:
           dist: ubuntu 20.04 focal
         locale: utf-8
        machine: x86_64
        release: 5.4.0-42-generic
         system: Linux
        version: Ubuntu 20.04 focal
```
</details>

**Comment by DmitryKuzmenko** [comment]
Fixed by https://github.com/saltstack/salt/pull/57563 will be released with Magnesium release.
@centromere you personally could either wait for release or hotfix your installation with this patch:
```diff
diff --git a/salt/renderers/nacl.py b/salt/renderers/nacl.py
index 114594785c..b16163a0d1 100644
--- a/salt/renderers/nacl.py
+++ b/salt/renderers/nacl.py
@@ -77,7 +77,7 @@ def _decrypt_object(obj, **kwargs):
     """
     if salt.utils.stringio.is_readable(obj):
         return _decrypt_object(obj.getvalue(), **kwargs)
-    if isinstance(obj, six.string_types):
+    if isinstance(obj, str):
         if re.search(NACL_REGEX, obj) is not None:
             return __salt__["nacl.dec"](re.search(NACL_REGEX, obj).group(1), **kwargs)
         else:
```
