### ISSUE TITLE
integration.pillar.test_git_pillar.TestGitPythonHTTP failing on new freebsd AMI 

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#58431]
This PR is adding a new AMI https://github.com/saltstack/salt/pull/58429  

This issue is created to track the work to fix this failing test.

https://jenkinsci.saltstack.com/job/pr-centos7-py3-m2crypto/job/PR-58429/1/

```
Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/support/gitfs.py", line 407, in setUpClass
    check_port=cls.nginx_port,
  File "/tmp/kitchen/testing/.nox/runtests-parametrized-3-coverage-true-crypto-m2crypto-transport-zeromq/lib/python3.6/site-packages/saltfactories/utils/processes/helpers.py", line 340, in start_daemon
    exitcode=result.exitcode,
saltfactories.exceptions.ProcessNotStarted: [Nginx] The <NginxDaemon display_name='nginx'> has failed to confirm running status after 3 attempts, which took 5.29 seconds(10.00 seconds each)
 Exitcode: 1
 Process Output:
   >>>>> STDERR >>>>>
nginx: [emerg] bind() to 0.0.0.0:46904 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:46904 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:46904 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:46904 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:46904 failed (98: Address already in use)
nginx: [emerg] still could not bind()

   <<<<< STDERR <<<<<
```

**Comment by sagetherage** [comment]
These are passing now
