### ISSUE TITLE
[BUG] salt proxy vcenter modue conflict with salt proxy esxi module

### ISSUE THREAD

**Issue by arnebjarne** [saltstack/salt#58517]
**Description**
I am using the salt proxy esxi module but code thinks its vcenter module

**Setup**
/srv/esxi_proxy/pillar/myesxihost.sls
```
proxy:
  proxytype: esxi
  host: myesxihost
  username: 'myproxyusername'
  passwords:
    - HIDDEN
```

**Steps to Reproduce the behavior**
salt myesxihost test.ping

myesxihost:
```
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python3.6/site-packages/salt/metaproxy/proxy.py", line 480, in thread_return
        opts, data, func, args, kwargs
      File "/usr/lib/python3.6/site-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/lib/python3.6/site-packages/salt/modules/test.py", line 132, in ping
        return __proxy__[ping_cmd]()
      File "/usr/lib/python3.6/site-packages/salt/proxy/esxi.py", line 458, in ping
        if DETAILS["mechanism"] == "userpass":
    KeyError: 'mechanism'
```

**Expected behavior**
```
salt myesxihost  test.ping
myesxihost :
    True


-------------------------------------------
Summary
-------------------------------------------
# of minions targeted: 1
# of minions returned: 1
# of minions that did not return: 0
# of minions with errors: 0
-------------------------------------------
```

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3001.1

Dependency Versions:
           cffi: 1.14.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.1
        libgit2: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Apr  2 2020, 13:34:55)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4

System Versions:
           dist: centos 7 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1127.19.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7 Core

```
</details>

**Additional context**
Problem is in
/usr/lib/python3.6/site-packages/salt/proxy/esxi.py

    if DETAILS.get("esxi_host"):
        return True

DETAILS["esxi_host"] is not set in "    if "host" in proxy_conf:" section. Its only set in "    if "vcenter" in proxy_conf:" section.

i guess the 
 if DETAILS.get("esxi_host"):
should be replaced with something like
checking     if "vcenter" in proxy_conf /     if "host" in proxy_conf:

**Comment by waynew** [comment]
Closing this, since we're moving VMware support to https://github.com/saltstack/salt-ext-modules-vmware (which should not have this issue once the functionality is implemented)
