### ISSUE TITLE
[BUG] NameError: name 'six' is not defined when running winrepo.genrepo on a masterless minion

### ISSUE THREAD

**Issue by eemperor** [saltstack/salt#58596]
**Description**
Executing `salt-call --local winrepo.genrepo` generates an un-handled exception error.

**Setup**
Initialize the default Windows Package Manager as described here:  [Windows Package Manager initialization](https://docs.saltstack.com/en/latest/topics/windows/windows-package-manager.html#initialization)

**Steps to Reproduce the behavior**
1.  Install Git on a Windows system
2.  Install Salt 3001.1 64-bit for Windows
3.  Initialize the local repository with the Windows package definitions provided by Salt
```
salt-call --local winrepo.update_git_repos
```
4.  Generate the metadata file (legacy)
```
salt-call --local winrepo.genrepo
```
Error output:
```
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
NameError: name 'six' is not defined
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-call", line 4, in <module>
    __import__('pkg_resources').run_script('salt==3001.1', 'salt-call')
  File "C:\salt\bin\lib\site-packages\pkg_resources\__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "C:\salt\bin\lib\site-packages\pkg_resources\__init__.py", line 1527, in run_script
    exec(code, namespace, namespace)
  File "c:\salt\bin\lib\site-packages\salt-3001.1-py3.7.egg\EGG-INFO\scripts\salt-call", line 10, in <module>
    salt_call()
  File "C:\salt\bin\lib\site-packages\salt-3001.1-py3.7.egg\salt\scripts.py", line 445, in salt_call
    client.run()
  File "C:\salt\bin\lib\site-packages\salt-3001.1-py3.7.egg\salt\cli\call.py", line 58, in run
    caller.run()
  File "C:\salt\bin\lib\site-packages\salt-3001.1-py3.7.egg\salt\cli\caller.py", line 121, in run
    ret = self.call()
  File "C:\salt\bin\lib\site-packages\salt-3001.1-py3.7.egg\salt\cli\caller.py", line 229, in call
    self.opts, data, func, args, kwargs
  File "C:\salt\bin\lib\site-packages\salt-3001.1-py3.7.egg\salt\executors\direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt-3001.1-py3.7.egg\salt\modules\winrepo.py", line 76, in genrepo
    return _genrepo(opts=__opts__, fire_event=False)
  File "C:\salt\bin\lib\site-packages\salt-3001.1-py3.7.egg\salt\runners\winrepo.py", line 86, in genrepo
    for pkgname, versions in six.iteritems(config):
NameError: name 'six' is not defined
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-call", line 4, in <module>
    __import__('pkg_resources').run_script('salt==3001.1', 'salt-call')
  File "C:\salt\bin\lib\site-packages\pkg_resources\__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "C:\salt\bin\lib\site-packages\pkg_resources\__init__.py", line 1527, in run_script
    exec(code, namespace, namespace)
  File "c:\salt\bin\lib\site-packages\salt-3001.1-py3.7.egg\EGG-INFO\scripts\salt-call", line 10, in <module>
    salt_call()
  File "C:\salt\bin\lib\site-packages\salt-3001.1-py3.7.egg\salt\scripts.py", line 445, in salt_call
    client.run()
  File "C:\salt\bin\lib\site-packages\salt-3001.1-py3.7.egg\salt\cli\call.py", line 58, in run
    caller.run()
  File "C:\salt\bin\lib\site-packages\salt-3001.1-py3.7.egg\salt\cli\caller.py", line 121, in run
    ret = self.call()
  File "C:\salt\bin\lib\site-packages\salt-3001.1-py3.7.egg\salt\cli\caller.py", line 229, in call
    self.opts, data, func, args, kwargs
  File "C:\salt\bin\lib\site-packages\salt-3001.1-py3.7.egg\salt\executors\direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt-3001.1-py3.7.egg\salt\modules\winrepo.py", line 76, in genrepo
    return _genrepo(opts=__opts__, fire_event=False)
  File "C:\salt\bin\lib\site-packages\salt-3001.1-py3.7.egg\salt\runners\winrepo.py", line 86, in genrepo
    for pkgname, versions in six.iteritems(config):
NameError: name 'six' is not defined
```

**Expected behavior**
An output of the available Windows packages is produced and the metadata file is created.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3001.1

Dependency Versions:
           cffi: 1.12.2
       cherrypy: 17.4.1
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.10
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 1.0.0
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: Not Installed
   pycryptodome: 3.9.7
         pygit2: Not Installed
         Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
   python-gnupg: 0.4.4
         PyYAML: 5.3.1
          PyZMQ: 18.0.1
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist: mingw64_nt-10.0-14393 3.1.6
         locale: cp1252
        machine: AMD64
        release: 2016Server
         system: Windows
        version: 2016Server 10.0.14393 SP0
```
</details>

**Comment by xeacott** [comment]
Yep can confirm this is a bug. Looks like there a PR that didn't get ported over to master... specifically [this](https://github.com/saltstack/salt/pull/26822/files) one and i tested it locally and problem solved. 

Let me gen a PR and you can give it a go!

**Comment by eemperor** [comment]
Excellent!  Thank you.

**Comment by xeacott** [comment]
Okay, same PR # new code. Give it a whirl. :)
