### ISSUE TITLE
[BUG] gitfs using pygit2 git://  failed on CentOS 8

### ISSUE THREAD

**Issue by tjyang** [saltstack/salt#58623]
**Description**

In my test lab,  centos8t01.test.lan gitfs  configured with pygit2. 
https:// syntax works  but not ssh:// or git@ remote GitHub repository. 

<details><summary>  Following is the git@syntax error message on centos8t01:/var/log/salt/master </summary>

```
2020-10-03 15:04:36,319 [salt.utils.gitfs :1871][ERROR   ][1938017] Unable to fetch SSH-based gitfs remote 'git@github.com:tjyang/test.lan.git'. You may need to add ssh:// to the repo string or libgit2 must be compiled with libssh2 to support SSH authentication.
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/gitfs.py", line 1858, in _fetch
    fetch_results = origin.fetch(**fetch_kwargs)
  File "/usr/lib64/python3.6/site-packages/pygit2/remote.py", line 405, in fetch
    check_error(err)
  File "/usr/lib64/python3.6/site-packages/pygit2/errors.py", line 64, in check_error
    raise GitError(message)
_pygit2.GitError: unsupported URL protocol
```

</details>

**Setup**
-  RTFM
    - [Read and follow CentOS 8 install guide.](https://repo.saltstack.com/#rhel)
    - [gifts walkthrough](https://docs.saltstack.com/en/latest/topics/tutorials/gitfs.html)

<details><summary> CentOS 8: cat /etc/redhat-release ;rpm -qa |egrep 'python3-pygit2|salt' </summary>

```
root@centos8t01 salt]# cat /etc/redhat-release ;rpm -qa |egrep 'python3-pygit2|salt'
CentOS Linux release 8.2.2004 (Core)
salt-master-3001.1-1.el8.noarch
python3-pygit2-0.26.4-1.el8.x86_64
salt-py3-repo-latest-4.el8.noarch
salt-3001.1-1.el8.noarch
salt-minion-3001.1-1.el8.noarch
salt-api-3001.1-1.el8.noarch
[root@centos8t01 salt]#
```
</details>

<details><summary> gifts config in /etc/salt/master </summary>

```
<snipped> git@ syntax commented out below,uncomment when reproducing the error is needed.
gitfs_provider: pygit2
fileserver_backend:
  - git
  - roots
gitfs_remotes:
  - git://github.com/saltstack-formulas/salt-formula.git:
     - mountpoint: salt://formula01-git
  - https://github.com/tjyang/salt-formula.git:
     - user:  tjyang
     - password: xxxxxxx
     - mountpoint: salt://private01-https
#  - git@github.com:tjyang/salt-formula.git:
#     - pubkey:  /home/tjyang/.ssh/id_dsa.pub
#     - privkey: /home/tjyang/.ssh/id_dsa
#     - mountpoint: salt://test01-git

<snipped>
```
</details>

**Steps to Reproduce the behavior**

<details><summary>Make sure command line git checkout works on centos8t01</summary>

```
[tjyang@centos8t01 tmp]$ git clone git@github.com:tjyang/salt-formula.git
Cloning into 'salt-formula'...
remote: Enumerating objects: 31, done.
remote: Counting objects: 100% (31/31), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 3818 (delta 10), reused 20 (delta 7), pack-reused 3787
Receiving objects: 100% (3818/3818), 1.07 MiB | 7.48 MiB/s, done.
Resolving deltas: 100% (2223/2223), done.
[tjyang@centos8t01 tmp]$

```
</details>

<details><summary>Failed on  CentOS 8: sudo salt-run -l debug fileserver.update  </summary>

```
[tjyang@centos8t01 tmp]$ sudo salt-run -l debug fileserver.update
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Changed git to gitfs in master opts' fileserver_backend list
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: centos8t01
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] LazyLoaded fileserver.update
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Changed git to gitfs in minion opts' fileserver_backend list
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: centos8t01
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Elapsed time getting FQDNs: 0.11284971237182617 seconds
[DEBUG   ] LazyLoaded zfs.is_supported
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event: tag = salt/run/20201004203746683033/new; data = {'fun': 'runner.fileserver.update', 'jid': '20201004203746683033', 'user': 'sudo_tjyang', 'fun_args': [], '_stamp': '2020-10-04T20:37:47.105097'}
[DEBUG   ] pygit2 gitfs_provider enabled
[DEBUG   ] Created gitfs object with uninitialized remotes
[DEBUG   ] LazyLoaded gitfs.envs
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Updating gitfs fileserver cache
[DEBUG   ] Current fetch URL for gitfs remote 'git://github.com/saltstack-formulas/salt-formula.git': git://github.com/saltstack-formulas/salt-formula.git (desired: git://github.com/saltstack-formulas/salt-formula.git)
[DEBUG   ] Current refspecs for gitfs remote 'git://github.com/saltstack-formulas/salt-formula.git': ['+refs/heads/*:refs/remotes/origin/*', '+refs/tags/*:refs/tags/*'] (desired: ['+refs/heads/*:refs/remotes/origin/*', '+refs/tags/*:refs/tags/*'])
[DEBUG   ] Current http.sslVerify for gitfs remote 'git://github.com/saltstack-formulas/salt-formula.git': true (desired: true)
[DEBUG   ] Current fetch URL for gitfs remote 'https://github.com/tjyang/salt-formula.git': https://github.com/tjyang/salt-formula.git (desired: https://github.com/tjyang/salt-formula.git)
[DEBUG   ] Current refspecs for gitfs remote 'https://github.com/tjyang/salt-formula.git': ['+refs/heads/*:refs/remotes/origin/*', '+refs/tags/*:refs/tags/*'] (desired: ['+refs/heads/*:refs/remotes/origin/*', '+refs/tags/*:refs/tags/*'])
[DEBUG   ] Current http.sslVerify for gitfs remote 'https://github.com/tjyang/salt-formula.git': true (desired: true)
[DEBUG   ] Current fetch URL for gitfs remote 'git@github.com:tjyang/salt-formula.git': git@github.com:tjyang/salt-formula.git (desired: git@github.com:tjyang/salt-formula.git)
[DEBUG   ] Current refspecs for gitfs remote 'git@github.com:tjyang/salt-formula.git': ['+refs/heads/*:refs/remotes/origin/*', '+refs/tags/*:refs/tags/*'] (desired: ['+refs/heads/*:refs/remotes/origin/*', '+refs/tags/*:refs/tags/*'])
[DEBUG   ] Current http.sslVerify for gitfs remote 'git@github.com:tjyang/salt-formula.git': true (desired: true)
[DEBUG   ] Created gitfs object for process 2658190
[DEBUG   ] Set update lock for gitfs remote 'git://github.com/saltstack-formulas/salt-formula.git'
[DEBUG   ] Fetching gitfs remote 'git://github.com/saltstack-formulas/salt-formula.git'
[DEBUG   ] gitfs remote 'git://github.com/saltstack-formulas/salt-formula.git' is up-to-date
[DEBUG   ] Removed update lock for gitfs remote 'git://github.com/saltstack-formulas/salt-formula.git'
[DEBUG   ] Set update lock for gitfs remote 'https://github.com/tjyang/salt-formula.git'
[DEBUG   ] Fetching gitfs remote 'https://github.com/tjyang/salt-formula.git'
[DEBUG   ] gitfs remote 'https://github.com/tjyang/salt-formula.git' is up-to-date
[DEBUG   ] Removed update lock for gitfs remote 'https://github.com/tjyang/salt-formula.git'
[DEBUG   ] Set update lock for gitfs remote 'git@github.com:tjyang/salt-formula.git'
[DEBUG   ] Fetching gitfs remote 'git@github.com:tjyang/salt-formula.git'
[ERROR   ] Unable to fetch SSH-based gitfs remote 'git@github.com:tjyang/salt-formula.git'. You may need to add ssh:// to the repo string or libgit2 must be compiled with libssh2 to support SSH authentication.
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/gitfs.py", line 1858, in _fetch
    fetch_results = origin.fetch(**fetch_kwargs)
  File "/usr/lib64/python3.6/site-packages/pygit2/remote.py", line 405, in fetch
    check_error(err)
  File "/usr/lib64/python3.6/site-packages/pygit2/errors.py", line 64, in check_error
    raise GitError(message)
_pygit2.GitError: unsupported URL protocol
[DEBUG   ] Removed update lock for gitfs remote 'git@github.com:tjyang/salt-formula.git'
[DEBUG   ] Updating roots fileserver cache
[DEBUG   ] LazyLoaded local_cache.prep_jid
[DEBUG   ] Sending event: tag = salt/run/20201004203746683033/ret; data = {'fun': 'runner.fileserver.update', 'jid': '20201004203746683033', 'user': 'sudo_tjyang', 'fun_args': [], '_stamp': '2020-10-04T20:37:47.460986', 'return': True, 'success': True}
[DEBUG   ] LazyLoaded nested.output
True
[INFO    ] Runner completed: 20201004203746683033
[DEBUG   ] Closing IPCMessageClient instance
[DEBUG   ] Runner return: True
[tjyang@centos8t01 tmp]$
```
</details>

**Expected behavior**
- showing  test01-git  got mount  from "salt-run fileserver.dir_list" on centos8t01. 

**Screenshots**

NA

**Versions Report**
<details><summary>salt --versions-report</summary>
 
```
[root@centos8t01 salt]# salt --versions-report
Salt Version:
           Salt: 3001.1

Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10.1
        libgit2: 0.26.8
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 3.6.8 (default, Apr 16 2020, 01:36:27)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 19.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2

System Versions:
           dist: centos 8 Core
         locale: UTF-8
        machine: x86_64
        release: 4.18.0-193.14.2.el8_2.x86_64
         system: Linux
        version: CentOS Linux 8 Core

[root@centos8t01 salt]#
```
</details>

**Additional context**

- References:
   - https://github.com/saltstack/salt/issues/40335
   - https://github.com/saltstack/salt/issues/58029
   - [Open/Closed Issues regarding gitfs](https://github.com/saltstack/salt/issues?q=is%3Aissue+gitfs)

**Comment by DmitryKuzmenko** [comment]
@tjyang this is a known documentation issue. Please see https://github.com/saltstack/salt/issues/56127

**Comment by tjyang** [comment]
@DmitryKuzmenko 
Thanks for the  #56127 pointer.
```
# Wrong syntax
# - git@github.com:tjyang/salt-formula.git:
# Correct syntax below.
  - git://github.com/tjyang/salt-formula.git:
     - pubkey:  /home/tjyang/.ssh/id_dsa.pub
     - privkey: /home/tjyang/.ssh/id_dsa
     - mountpoint: salt://test01-git
```
