### ISSUE TITLE
[BUG] gitlab repo:  _pygit2.GitError: Error receiving socket data: Connection reset by peer

### ISSUE THREAD

**Issue by tjyang** [saltstack/salt#58654]
**Description**
Not able to mount repo on gitab.com
```
2020-10-06 16:37:20,473 [salt.utils.gitfs :1887][ERROR   ][3914026] Error occurred fetching gitfs remote 'git://gitlab.com/tjyang/mysalt.git': Error receiving socket data: C\
onnection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/gitfs.py", line 1858, in _fetch
    fetch_results = origin.fetch(**fetch_kwargs)
  File "/usr/lib64/python3.6/site-packages/pygit2/remote.py", line 405, in fetch
    check_error(err)
  File "/usr/lib64/python3.6/site-packages/pygit2/errors.py", line 64, in check_error
    raise GitError(message)
_pygit2.GitError: Error receiving socket data: Connection reset by peer
```
**Setup**

```
  - git://github.com/tjyang/salt-formula.git:
     - pubkey:  /home/tjyang/.ssh/id_dsa.pub
     - privkey: /home/tjyang/.ssh/id_dsa
     - mountpoint: salt://test01-git

  - git://gitlab.com/tjyang/mysalt.git:
     - pubkey:  /home/tjyang/.ssh/id_dsa.pub
     - privkey: /home/tjyang/.ssh/id_dsa
     - mountpoint: salt://test01-gitlab

```

**Steps to Reproduce the behavior**
- with above "git://gitlab.com/tjyang/mysalt.git:" config in /etc/salt/master.
- sudo salt-run -l debug fileserver.update # to trigger repo mount manually
- Or "sudo systemctl restart salt-master" to see the error in /var/log/salt/master.

**Expected behavior**
To see test01-gitlab successfully mounted like test01-github  on centos8t01.

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>

```
[tjyang@centos8t01 ~]$ salt --versions-report
Salt Version:
           Salt: 3001.1

Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10.1
        libgit2: 0.26.8
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 3.6.8 (default, Apr 16 2020, 01:36:27)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 19.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2

System Versions:
           dist: centos 8 Core
         locale: UTF-8
        machine: x86_64
        release: 4.18.0-193.14.2.el8_2.x86_64
         system: Linux
        version: CentOS Linux 8 Core

[tjyang@centos8t01 ~]$

```
</details>

**Additional context**
See the other ticket that centos8t01 was able mount repo from GitHub.

**Comment by tjyang** [comment]
sorry , duplicated with  #58653
