### ISSUE TITLE
[BUG] `aptpkg.del_repo` can't delete repository without components

### ISSUE THREAD

**Issue by kwargs** [saltstack/salt#58667]
**Description**
`aptpkg.del_repo` ignores the case when the repository has no 'components'.
https://github.com/saltstack/salt/blob/3f6b5d42753105ea7b5ecd42c1abaa8f8e5227d1/salt/modules/aptpkg.py#L1848

**Setup**
Add sample source.list
```bash
$ cat /etc/apt/sources.list.d/del-repo.list
deb http://dist.list stable/all/
```

**Steps to Reproduce the behavior**
```bash
$ salt-call pkg.get_repo 'deb http://dist.list stable/all/'
local:
    ----------
    architectures:
    comps:
    disabled:
        False
    dist:
        stable/all/
    file:
        /etc/apt/sources.list.d/del-repo.list
    line:
        deb http://dist.list stable/all/
    type:
        deb
    uri:
        http://dist.list
$ salt-call pkg.del_repo 'deb http://dist.list stable/all/'
Error running 'pkg.del_repo': Repo deb http://dist.list stable/all/ doesn't exist in the sources.list(s)
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
salt-call --versions-report
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.17 (default, Jul 20 2020, 15:37:01)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.19.114-29
         system: Linux
        version: Ubuntu 18.04 bionic
```
</details>

**Comment by votdev** [comment]
This bug still exists in `3005.1`.

remove_apt_sources_list_security_0:
  module.run:
    - pkg.del_repo:
      - repo: "deb-src [signed-by=/etc/apt/trusted.gpg.d/debian-archive-bullseye-security-automatic.gpg] http://security.debian.org/debian-security bullseye-security main contrib non-free"

```
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/state.py", line 2276, in call
    ret = self.states[cdata["full"]](
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1228, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1243, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1276, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/states/module.py", line 394, in run
    return _run(**kwargs)
  File "/usr/lib/python3/dist-packages/salt/states/module.py", line 449, in _run
    func_ret = _call_function(
  File "/usr/lib/python3/dist-packages/salt/states/module.py", line 495, in _call_function
    mret = salt.utils.functools.call_function(__salt__[name], *func_args, **func_kwargs)
  File "/usr/lib/python3/dist-packages/salt/utils/functools.py", line 174, in call_function
    return salt_function(*function_args, **function_kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1228, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1243, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/modules/aptpkg.py", line 2138, in del_repo
    raise CommandExecutionError(
salt.exceptions.CommandExecutionError: Repo deb-src [signed-by=/etc/apt/trusted.gpg.d/debian-archive-bullseye-security-automatic.gpg] http://security.debian.org/debian-security bullseye-security main contrib non-free doesn't exist in the sources.list(s)
```

**Comment by votdev** [comment]
This bug still exists in `3005.1`.

```
remove_apt_sources_list_security_0:
  module.run:
    - pkg.del_repo:
      - repo: "deb-src [signed-by=/etc/apt/trusted.gpg.d/debian-archive-bullseye-security-automatic.gpg] http://security.debian.org/debian-security bullseye-security main contrib non-free"
```

```
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/state.py", line 2276, in call
    ret = self.states[cdata["full"]](
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1228, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1243, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1276, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/states/module.py", line 394, in run
    return _run(**kwargs)
  File "/usr/lib/python3/dist-packages/salt/states/module.py", line 449, in _run
    func_ret = _call_function(
  File "/usr/lib/python3/dist-packages/salt/states/module.py", line 495, in _call_function
    mret = salt.utils.functools.call_function(__salt__[name], *func_args, **func_kwargs)
  File "/usr/lib/python3/dist-packages/salt/utils/functools.py", line 174, in call_function
    return salt_function(*function_args, **function_kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1228, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1243, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/modules/aptpkg.py", line 2138, in del_repo
    raise CommandExecutionError(
salt.exceptions.CommandExecutionError: Repo deb-src [signed-by=/etc/apt/trusted.gpg.d/debian-archive-bullseye-security-automatic.gpg] http://security.debian.org/debian-security bullseye-security main contrib non-free doesn't exist in the sources.list(s)
```
