### ISSUE TITLE
salt-api rest_cherrypy sslobj.do_handshake

### ISSUE THREAD

**Issue by TobiaszG24** [saltstack/salt#58711]
**Description**
I can not start the service properly. There seems to be a problem with the certificate.
I've generated cert using: salt-call --local tls.create_self_signed_cert

**Setup**
```
rest_cherrypy:
  port: 8000
  ssl_crt: /etc/pki/tls/certs/localhost.crt
  ssl_key: /etc/pki/tls/certs/localhost.key
```

**Traceback**

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cherrypy/wsgiserver/__init__.py", line 2021, in start
    self.tick()
  File "/usr/lib/python3/dist-packages/cherrypy/wsgiserver/__init__.py", line 2090, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/usr/lib/python3/dist-packages/cherrypy/wsgiserver/ssl_builtin.py", line 66, in wrap
    s = self.context.wrap_socket(sock,do_handshake_on_connect=True,
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
```

**Versions Report**
```
Salt Version:
           Salt: 3001.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 2.0.6
      gitpython: 3.0.7
         Jinja2: 2.10.1
        libgit2: 0.28.3
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.6.1
         pygit2: 1.0.3
         Python: 3.8.5 (default, Jul 28 2020, 12:59:40)
   python-gnupg: 0.4.5
         PyYAML: 5.3.1
          PyZMQ: 18.1.1
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: ubuntu 20.04 focal
         locale: utf-8
        machine: x86_64
        release: 5.4.0-1026-azure
         system: Linux
        version: Ubuntu 20.04 focal

```

**Comment by frogunder** [comment]
@TobiaszG24 Thank you for reporting this issue.

I have not been able to replicate it, salt-api starts just fine for me. I just tried on a Ubuntu 20 machine with salt 3001.1 installed.

Did you follow the instructions here?:
https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html

Does your log files show any other errors?

Also what is the output of salt-api --version? Just want to make sure it is the same as salt --version.

Thanks.

**Comment by TobiaszG24** [comment]
salt-api 3001.1
salt 3001.1

Over all API is working correctly, but i have above traceback in logs.

**Comment by frogunder** [comment]
Thanks, I also see the traceback in the log.

**Comment by TobiaszG24** [comment]
@frogunder Is it possible that these issue is related to: [https://github.com/saltstack/salt/issues/58775](issue)

**Comment by RallyHereMattSmith** [comment]
Addendum to my previous post, looks like the OneDrive installation configures a salt user and group for the master to run as, which breaks Salt-API pam eauth validation per [this](https://docs.saltproject.io/en/latest/ref/configuration/nonroot.html) doc.
I changed the systemd file to run as root, then modified the salt master config to set user to root as well (since the systemd unit file update didn't work) and now, with SSL disabled in the API I can successfully auth at least with my user.
However with the self-signed or CA certs I still get the above stack trace.
