### ISSUE TITLE
Salt orchestration command is not working

### ISSUE THREAD

**Issue by sooraj2589** [saltstack/salt#58766]
I need to run multiple state files in an ordered way on different targets with different pillar values from a single trigger. I could see salt orchestration is the best way to achieve my task

I have setup the orch folder and writen below file for testing

#/srv/salt/orch/test.sls
remove_vip:
  salt.state:
    - tgt: 'G@host_set:Set B and G@mode:et'
    - tgt_type: compund
    - sls: test1
 test_deploy:
    salt.state:
    - tgt: 'host_set:Set A'
    - tgt_type: grain
    - sls: test2
    - require:
       -  remove_vip

When I trigger the command  **salt-run state.orchestrate orch.test** getting below exceptions

Exception occurred in runner state.orchestrate: Traceback (most recent call last):
  File "/ngs/app/sdopilotd/salt/usr/lib/python3.7/site-packages/salt/client/mixins.py", line 374, in low
    data['return'] = func(*args, **kwargs)
  File "/ngs/app/sdopilotd/salt/usr/lib/python3.7/site-packages/salt/runners/state.py", line 128, in orchestrate
    orchestration_jid=orchestration_jid)
  File "/ngs/app/sdopilotd/salt/usr/lib/python3.7/site-packages/salt/modules/state.py", line 1308, in sls
    initial_pillar=_get_initial_pillar(opts))
  File "/ngs/app/sdopilotd/salt/usr/lib/python3.7/site-packages/salt/state.py", line 4194, in __init__
    BaseHighState.__init__(self, opts)
  File "/ngs/app/sdopilotd/salt/usr/lib/python3.7/site-packages/salt/state.py", line 3057, in __init__
    self.avail = self.__gather_avail()
  File "/ngs/app/sdopilotd/salt/usr/lib/python3.7/site-packages/salt/state.py", line 3067, in __gather_avail
    avail[saltenv] = self.client.list_states(saltenv)
  File "/ngs/app/sdopilotd/salt/usr/lib/python3.7/site-packages/salt/fileclient.py", line 349, in list_states
    for path in self.file_list(saltenv):
  File "/ngs/app/sdopilotd/salt/usr/lib/python3.7/site-packages/salt/fileclient.py", line 1256, in file_list
    else self.channel.send(load)
  File "/ngs/app/sdopilotd/salt/usr/lib/python3.7/site-packages/salt/fileserver/__init__.py", line 906, in send
    return getattr(self.fs, cmd)(load)
  File "/ngs/app/sdopilotd/salt/usr/lib/python3.7/site-packages/salt/utils/decorators/__init__.py", line 691, in wrapped
    return function(*args, **kwargs)
  File "/ngs/app/sdopilotd/salt/usr/lib/python3.7/site-packages/salt/fileserver/__init__.py", line 789, in file_list
    ret.update(self.servers[fstr](load))
  File "/ngs/app/sdopilotd/salt/usr/lib/python3.7/site-packages/sseape/fileserver/sseapi_fs.py", line 305, in file_list
    return _file_lists(load['saltenv'], 'files')
  File "/ngs/app/sdopilotd/salt/usr/lib/python3.7/site-packages/sseape/fileserver/sseapi_fs.py", line 273, in _file_lists
    cache_match, _, save_cache = salt.fileserver.check_file_list_cache(__opts__, form, list_cache, w_lock)
  File "/ngs/app/sdopilotd/salt/usr/lib/python3.7/site-packages/salt/fileserver/__init__.py", line 122, in check_file_list_cache
    if not os.path.isfile(list_cache) and _lock_cache(w_lock):
  File "/ngs/app/sdopilotd/salt/usr/lib/python3.7/site-packages/salt/fileserver/__init__.py", line 56, in _lock_cache
    os.mkdir(w_lock)
FileNotFoundError: [Errno 2] No such file or directory: '/ngs/app/sdopilotd/salt/var/cache/salt/master/file_lists/sseapi/.feature/pricing-changes-ui.w'

could any one advice please??

**Comment by sagetherage** [comment]
@sooraj2589 can you give run a salt versions report please?

**Comment by sooraj2589** [comment]
@sagetherage **salt 3000.3**

**Comment by sooraj2589** [comment]
can anyone please advise on the issue??

**Comment by oeuftete** [comment]
@sooraj2589 It looks like you are using SaltStack Enterprise.  Could you please open an issue with us through enterprisesupport@saltstack.com?

**Comment by oeuftete** [comment]
Closing this up as its an Enterprise-related issue.  @sooraj2589 Please contact Enterprise Support if you have further concerns with this issue.
