### ISSUE TITLE
[BUG] API CherryPy Salt request timed out. The master is not responding. You may need to run your command with `--async`

### ISSUE THREAD

**Issue by tobiasz-gleba** [saltstack/salt#58775]
**Description**
When I'm hitting via cherrypy "/minions" I receive 500, but when I'm using CLI, everything works correctly.

**Setup**
```
Salt Version:
           Salt: 3001.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 2.0.6
      gitpython: 3.0.7
         Jinja2: 2.10.1
        libgit2: 0.28.3
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.6.1
         pygit2: 1.0.3
         Python: 3.8.5 (default, Jul 28 2020, 12:59:40)
   python-gnupg: 0.4.5
         PyYAML: 5.3.1
          PyZMQ: 18.1.1
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2

System Versions:
           dist: ubuntu 20.04 focal
         locale: utf-8
        machine: x86_64
        release: 5.4.0-1031-azure
         system: Linux
        version: Ubuntu 20.04 focal
```

**Api config**
```
rest_cherrypy:
  port: 8000
  ssl_crt: /etc/pki/tls/certs/localhost.crt
  ssl_key: /etc/pki/tls/certs/localhost.key
  debug : True

external_auth:
  pam:
 ......................................................

```
**Response**
```
<!DOCTYPE html
	PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	</meta>
	<title>500 Internal Server Error</title>
	<style type="text/css">
		#powered_by {
			margin-top: 20px;
			border-top: 2px solid black;
			font-style: italic;
		}

		#traceback {
			color: red;
		}
	</style>
</head>

<body>
	<h2>500 Internal Server Error</h2>
	<p>The server encountered an unexpected condition which prevented it from fulfilling the request.</p>
	<pre id="traceback">Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/client/__init__.py", line 1857, in pub
    payload = channel.send(payload_kwargs, timeout=timeout)
  File "/usr/lib/python3/dist-packages/salt/utils/asynchronous.py", line 126, in wrap
    six.reraise(*results[1])
  File "/usr/lib/python3/dist-packages/salt/ext/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/salt/utils/asynchronous.py", line 132, in _target
    result = io_loop.run_sync(lambda: getattr(self.obj, key)(*args, **kwargs))
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/ioloop.py", line 459, in run_sync
    return future_cell[0].result()
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "&lt;string&gt;", line 4, in raise_exc_info
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/gen.py", line 1064, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python3/dist-packages/salt/transport/zeromq.py", line 439, in send
    ret = yield self._uncrypted_transfer(load, tries=tries, timeout=timeout)
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "&lt;string&gt;", line 4, in raise_exc_info
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/gen.py", line 1064, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python3/dist-packages/salt/transport/zeromq.py", line 427, in _uncrypted_transfer
    ret = yield self.message_client.send(
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "&lt;string&gt;", line 4, in raise_exc_info
salt.exceptions.SaltReqTimeoutError: Message timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/client/__init__.py", line 346, in run_job
    pub_data = self.pub(
  File "/usr/lib/python3/dist-packages/salt/client/__init__.py", line 1860, in pub
    raise SaltReqTimeoutError(
salt.exceptions.SaltReqTimeoutError: Salt request timed out. The master is not responding. You may need to run your command with `--async` in order to bypass the congested event bus. With `--async`, the CLI tool will print the job id (jid) and exit immediately without listening for responses. You can then use `salt-run jobs.lookup_jid` to look up the results of the job in the job cache later.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/netapi/rest_cherrypy/app.py", line 851, in hypermedia_handler
    ret = cherrypy.serving.request._hypermedia_inner_handler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/salt/netapi/rest_cherrypy/app.py", line 1345, in GET
    "return": list(self.exec_lowstate(token=cherrypy.session.get("token"))),
  File "/usr/lib/python3/dist-packages/salt/netapi/rest_cherrypy/app.py", line 1188, in exec_lowstate
    ret = self.api.run(chunk)
  File "/usr/lib/python3/dist-packages/salt/netapi/__init__.py", line 86, in run
    return l_fun(*f_call.get("args", ()), **f_call.get("kwargs", {}))
  File "/usr/lib/python3/dist-packages/salt/netapi/__init__.py", line 114, in local
    return local.cmd(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/client/__init__.py", line 708, in cmd
    pub_data = self.run_job(
  File "/usr/lib/python3/dist-packages/salt/client/__init__.py", line 368, in run_job
    raise SaltClientError(general_exception)
salt.exceptions.SaltClientError: Salt request timed out. The master is not responding. You may need to run your command with `--async` in order to bypass the congested event bus. With `--async`, the CLI tool will print the job id (jid) and exit immediately without listening for responses. You can then use `salt-run jobs.lookup_jid` to look up the results of the job in the job cache later.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python3/dist-packages/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/netapi/rest_cherrypy/app.py", line 890, in hypermedia_handler
    "return": "{0}".format(traceback.format_exc(exc))
  File "/usr/lib/python3.8/traceback.py", line 167, in format_exc
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
  File "/usr/lib/python3.8/traceback.py", line 120, in format_exception
    return list(TracebackException(
  File "/usr/lib/python3.8/traceback.py", line 493, in __init__
    context = TracebackException(
  File "/usr/lib/python3.8/traceback.py", line 493, in __init__
    context = TracebackException(
  File "/usr/lib/python3.8/traceback.py", line 509, in __init__
    self.stack = StackSummary.extract(
  File "/usr/lib/python3.8/traceback.py", line 340, in extract
    if limit &gt;= 0:
TypeError: '&gt;=' not supported between instances of 'SaltClientError' and 'int'
</pre>
	<div id="powered_by">
		<span>
        Powered by <a href="http://www.cherrypy.org">CherryPy 8.9.1</a>
      </span>
	</div>
</body>

</html>
```

**Comment by garethgreenaway** [comment]
@TobiaszG24 Thanks for the report.  You indicated that you see the expected results when running Salt commands via the CLI, can you give some information about how many minions you have connected to your Salt master?

**Comment by TobiaszG24** [comment]
I have connected only one minion.

**Comment by garethgreenaway** [comment]
Closing this due to age and the old version of Salt.
Can you retest this with the latest release of Salt 3006.2 and if this is still an issue, please open a new issue.

**Comment by corentin-dev** [comment]
I am having a similar issue with 3006.3, and I only have one minion.
My setup is not with cherrypy. I have a reactor that have the same behavior. I'll maybe post a different issue...

**Comment by corentin-dev** [comment]
#65438 is open now, I think it may be related.
