### ISSUE TITLE
[BUG] 3001.1 on ubuntu 20.04 salt-call never returns

### ISSUE THREAD

**Issue by zerthimon** [saltstack/salt#58770]
**Description**
`salt-call state.sls` command never returns to the command prompt, hangs on `[DEBUG   ] Closing AsyncZeroMQReqChannel instance`

**Setup**
```
test:
  pkg.installed:
    - name: cowsay
```

**Steps to Reproduce the behavior**
`salt-call state.sls test -l debug`

**Expected behavior**
state runs and exits

**Screenshots**
```
root@infra01:/srv/salt/base/states# salt-call state.sls test -l debug
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: infra01.mcs-int.obf.ru
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Elapsed time getting FQDNs: 0.057227134704589844 seconds
[DEBUG   ] LazyLoaded zfs.is_supported
[DEBUG   ] Connecting to master. Attempt 1 of 1
[DEBUG   ] "salt" Not an IP address? Assuming it is a hostname.
[DEBUG   ] Master URI: tcp://10.110.10.8:4506
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'infra01.mcs-int.obf.ru', 'tcp://10.110.10.8:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (3937)
[DEBUG   ] Setting zmq_reconnect_ivl to '3937ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'infra01.mcs-int.obf.ru', 'tcp://10.110.10.8:4506', 'clear')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://10.110.10.8:4506
[DEBUG   ] Trying to connect to: tcp://10.110.10.8:4506
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] salt.crypt._get_key_with_evict: Loading private key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[DEBUG   ] Connecting the Minion to the Master publish port, using the URI: tcp://10.110.10.8:4505
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Determining pillar cache
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'infra01.mcs-int.obf.ru', 'tcp://10.110.10.8:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'infra01.mcs-int.obf.ru', 'tcp://10.110.10.8:4506')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://10.110.10.8:4506
[DEBUG   ] Trying to connect to: tcp://10.110.10.8:4506
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded state.sls
[DEBUG   ] LazyLoaded direct_call.execute
[DEBUG   ] LazyLoaded saltutil.is_running
[DEBUG   ] LazyLoaded grains.get
[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'infra01.mcs-int.obf.ru', 'tcp://10.110.10.8:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'infra01.mcs-int.obf.ru', 'tcp://10.110.10.8:4506')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://10.110.10.8:4506
[DEBUG   ] Trying to connect to: tcp://10.110.10.8:4506
[DEBUG   ] Gathering pillar data for state run
[DEBUG   ] Finished gathering pillar data for state run
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] Could not find file 'salt://test.sls' in saltenv 'base'
[DEBUG   ] In saltenv 'base', looking at rel_path 'test/init.sls' to resolve 'salt://test/init.sls'
[DEBUG   ] In saltenv 'base', ** considering ** path '/var/cache/salt/minion/files/base/test/init.sls' to resolve 'salt://test/init.sls'
[DEBUG   ] compile template: /var/cache/salt/minion/files/base/test/init.sls
[DEBUG   ] Jinja search path: ['/var/cache/salt/minion/files/base']
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'infra01.mcs-int.obf.ru', 'tcp://10.110.10.8:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'infra01.mcs-int.obf.ru', 'tcp://10.110.10.8:4506')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://10.110.10.8:4506
[DEBUG   ] Trying to connect to: tcp://10.110.10.8:4506
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/test/init.sls' using 'jinja' renderer: 0.011323213577270508
[DEBUG   ] Rendered data from file: /var/cache/salt/minion/files/base/test/init.sls:
test:
  pkg.installed:
    - name: cowsay

[DEBUG   ] Results of YAML rendering: 
OrderedDict([('test', OrderedDict([('pkg.installed', [OrderedDict([('name', 'cowsay')])])]))])
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/test/init.sls' using 'yaml' renderer: 0.0003974437713623047
[DEBUG   ] LazyLoaded config.option
[DEBUG   ] LazyLoaded pkg.install
[DEBUG   ] LazyLoaded pkg.installed
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: infra01.mcs-int.obf.ru
[DEBUG   ] Could not LazyLoad boto3.assign_funcs: 'boto3.assign_funcs' is not available.
[DEBUG   ] Error loading module.boto3_elasticsearch: __init__ failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1754, in _load_module
    module_init(self.opts)
  File "/usr/lib/python3/dist-packages/salt/modules/boto3_elasticsearch.py", line 96, in __init__
    __utils__["boto3.assign_funcs"](__name__, "es")
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1278, in __getitem__
    func = super(LazyLoader, self).__getitem__(item)
  File "/usr/lib/python3/dist-packages/salt/utils/lazy.py", line 108, in __getitem__
    raise KeyError(key)
KeyError: 'boto3.assign_funcs'
[DEBUG   ] Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
[DEBUG   ] No config file found
[DEBUG   ] Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
[DEBUG   ] No config file found
[DEBUG   ] http://localhost:None "GET /version HTTP/1.1" 200 859
[DEBUG   ] docker-py API version: 1.40
[DEBUG   ] Attempting to run docker-py's "version" function with args=() and kwargs={}
[DEBUG   ] http://localhost:None "GET /v1.40/version HTTP/1.1" 200 859
[DEBUG   ] Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
[DEBUG   ] No config file found
[DEBUG   ] Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
[DEBUG   ] No config file found
[DEBUG   ] http://localhost:None "GET /version HTTP/1.1" 200 859
[DEBUG   ] DSC: Only available on Windows systems
[DEBUG   ] Module PSGet: Only available on Windows systems
[DEBUG   ] Could not LazyLoad pkg.ex_mod_init: 'pkg.ex_mod_init' is not available.
[INFO    ] Running state [cowsay] at time 20:19:28.142413
[INFO    ] Executing state pkg.installed for [cowsay]
[DEBUG   ] Could not LazyLoad pkg.resolve_capabilities: 'pkg.resolve_capabilities' is not available.
[INFO    ] Executing command ['dpkg-query', '--showformat', '${Status} ${Package} ${Version} ${Architecture}', '-W'] in directory '/root'
[INFO    ] All specified packages are already installed
[INFO    ] Completed state [cowsay] at time 20:19:28.185266 (duration_in_ms=42.854)
[DEBUG   ] File /var/cache/salt/minion/accumulator/139812808430592 does not exist, no need to cleanup
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'infra01.mcs-int.obf.ru', 'tcp://10.110.10.8:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'infra01.mcs-int.obf.ru', 'tcp://10.110.10.8:4506')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://10.110.10.8:4506
[DEBUG   ] Trying to connect to: tcp://10.110.10.8:4506
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[DEBUG   ] LazyLoaded highstate.output
local:
----------
          ID: test
    Function: pkg.installed
        Name: cowsay
      Result: True
     Comment: All specified packages are already installed
     Started: 20:19:28.142412
    Duration: 42.854 ms
     Changes:   

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:  42.854 ms
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
^C
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3001.1
 
Dependency Versions:
           cffi: 1.14.3
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: 4.3.1
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: Not Installed
   pycryptodome: 3.6.1
         pygit2: Not Installed
         Python: 3.8.5 (default, Jul 28 2020, 12:59:40)
   python-gnupg: 0.4.5
         PyYAML: 5.3.1
          PyZMQ: 18.1.1
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: ubuntu 20.04 focal
         locale: utf-8
        machine: x86_64
        release: 5.4.0-52-generic
         system: Linux
        version: Ubuntu 20.04 focal
```
</details>

**Additional context**

**Comment by sagetherage** [comment]
This has been corrected in the Magnesium release with the PR https://github.com/saltstack/salt/pull/58364 please try to upgrade to the latest version of Salt.

**Comment by zerthimon** [comment]
@sagetherage isn't 3001.1 the lastest version of Salt ?
This is what https://repo.saltstack.com/#ubuntu suggest installing.

**Comment by zerthimon** [comment]
@sagetherage Is there a deb-repo to install Magnesium from ?
