### ISSUE TITLE
Test failure (flaky?) - integration.states.test_pkg.PkgTest.test_pkg_004_installed_multipkg_with_version

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#58792]
https://jenkinsci.saltstack.com/job/pr-windows2019-py3/job/PR-58438/8/testReport/junit/integration.states.test_pkg/PkgTest/test_pkg_004_installed_multipkg_with_version/

# Error Message
```
False is not True. Salt Comment: The following packages failed to install/update: putty Failed to cache https://the.earth.li/~sgtatham/putty/0.69/w64/putty-64bit-0.69-installer.msi Error: [Errno 11002] getaddrinfo failed reading https://the.earth.li/~sgtatham/putty/0.69/w64/putty-64bit-0.69-installer.msi The following packages were installed/updated: vlc=3.0.10
```

# Stacktrace
```
Traceback (most recent call last):
  File "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\kitchen\\testing\tests\support\mixins.py", line 569, in assertSaltTrueReturn
    self.assertTrue(saltret)
  File "c:\python37\lib\unittest\case.py", line 705, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\admini~1\appdata\local\temp\kitchen\testing\tests\integration\states\test_pkg.py", line 208, in test_pkg_004_installed_multipkg_with_version
    self.assertSaltTrueReturn(ret)
  File "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\kitchen\\testing\tests\support\mixins.py", line 575, in assertSaltTrueReturn
    **(next(iter(ret.values())))
AssertionError: False is not True. Salt Comment:
The following packages failed to install/update: putty
Failed to cache https://the.earth.li/~sgtatham/putty/0.69/w64/putty-64bit-0.69-installer.msi
Error: [Errno 11002] getaddrinfo failed reading https://the.earth.li/~sgtatham/putty/0.69/w64/putty-64bit-0.69-installer.msi
The following packages were installed/updated: vlc=3.0.10
```

**Comment by Ch3LL** [comment]
Have not seen this fail in a while
