### ISSUE TITLE
[BUG] NX-OS native GuestShell minion does not respond to NX-OS modules

### ISSUE THREAD

**Issue by ChristopherJHart** [saltstack/salt#58797]
**Description**
A Cisco Nexus switch with the native GuestShell Salt minion [installed according to documentation](https://docs.saltstack.com/en/develop/topics/installation/nxos.html#guestshell-salt-minion-installation) does not respond to calls made with NX-OS modules. The following error message is reported by the Salt master:

```
[chart2@chart2-playground ~]$ sudo salt SJC-HOM-VTEP-1 nxos.ping
SJC-HOM-VTEP-1:
    'nxos' __virtual__ returned False: The nxos execution module failed to load: only available on proxy minions.
ERROR: Minions returned with non-zero exit code
```

**Setup**
This can be reproduced with a very vanilla setup. No specific SLS files or configuration is needed.

**Steps to Reproduce the behavior**
1. Install a native NX-OS GuestShell Salt minion in the GuestShell of a supported Cisco Nexus switch using the [documented installation procedure](https://docs.saltstack.com/en/develop/topics/installation/nxos.html#guestshell-salt-minion-installation). In this scenario, this minion has been installed on a Nexus 9348GC-FXP switch running NX-OS software release 9.3(5) named "SJC-HOM-VTEP-1".
2. Attempt to execute any NX-OS module against the native NX-OS GuestShell Salt minion on the Salt master:
```
[chart2@chart2-playground ~]$ sudo salt SJC-HOM-VTEP-1 nxos.ping
SJC-HOM-VTEP-1:
    'nxos' __virtual__ returned False: The nxos execution module failed to load: only available on proxy minions.
ERROR: Minions returned with non-zero exit code
```
3. The following debugs can be observed on the native NX-OS GuestShell Salt minion:
```
[INFO    ] User sudo_chart2 Executing command nxos.ping with jid 20201023170911092351
[DEBUG   ] Command details {u'tgt_type': u'glob', u'jid': u'20201023170911092351', u'tgt': u'SJC-HOM-VTEP-1', u'ret': u'', u'user': u'sudo_chart2', u'arg': [], u'fun': u'nxos.ping'}
[DEBUG   ] Subprocess ProcessPayload-Job-20201023170911092351 added
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[INFO    ] Starting a new job 20201023170911092351 with PID 1970
[DEBUG   ] Could not LazyLoad direct_call.allow_missing_func: 'direct_call.allow_missing_func' is not available.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Could not LazyLoad boto3.assign_funcs: 'boto3.assign_funcs' is not available.
[DEBUG   ] Error loading module.boto3_elasticsearch: __init__ failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1664, in _load_module
    module_init(self.opts)
  File "/usr/lib/python2.7/site-packages/salt/modules/boto3_elasticsearch.py", line 92, in __init__
    __utils__['boto3.assign_funcs'](__name__, 'es')
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1248, in __getitem__
    func = super(LazyLoader, self).__getitem__(item)
  File "/usr/lib/python2.7/site-packages/salt/utils/lazy.py", line 108, in __getitem__
    raise KeyError(key)
KeyError: u'boto3.assign_funcs'
[DEBUG   ] key: ifttt.secret_key, ret: _|-
[DEBUG   ] key: ifttt:secret_key, ret: _|-
[DEBUG   ] key: pushbullet.api_key, ret: _|-
[DEBUG   ] key: pushbullet:api_key, ret: _|-
[DEBUG   ] Error loading module.swarm: __init__ failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1664, in _load_module
    module_init(self.opts)
  File "/usr/lib/python2.7/site-packages/salt/modules/swarm.py", line 53, in __init__
    __context__['client'] = docker.from_env()
AttributeError: 'module' object has no attribute 'from_env'
[DEBUG   ] key: victorops.api_key, ret: _|-
[DEBUG   ] key: victorops:api_key, ret: _|-
[DEBUG   ] LazyLoaded list_match.match
[INFO    ] User sudo_chart2 Executing command saltutil.find_job with jid 20201023170916146642
[DEBUG   ] Command details {u'tgt_type': u'list', u'jid': u'20201023170916146642', u'tgt': [u'SJC-HOM-VTEP-1'], u'ret': u'', u'user': u'sudo_chart2', u'arg': [u'20201023170911092351'], u'fun': u'saltutil.find_job'}
[DEBUG   ] Subprocess ProcessPayload-Job-20201023170916146642 added
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[INFO    ] Starting a new job 20201023170916146642 with PID 1976
[DEBUG   ] Could not LazyLoad direct_call.allow_missing_func: 'direct_call.allow_missing_func' is not available.
[DEBUG   ] LazyLoaded saltutil.find_job
[DEBUG   ] Minion return retry timer set to 7 seconds (randomized)
[INFO    ] Returning information for job: 20201023170916146642
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/minion', u'SJC-HOM-VTEP-1', u'tcp://{REDACTED}:4506', u'aes')
[DEBUG   ] Initializing new AsyncAuth for (u'/etc/salt/pki/minion', u'SJC-HOM-VTEP-1', u'tcp://{REDACTED}:4506')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://{REDACTED}:4506
[DEBUG   ] Trying to connect to: tcp://{REDACTED}:4506
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[DEBUG   ] minion return: {u'fun_args': [u'20201023170911092351'], u'jid': u'20201023170916146642', u'return': {'tgt_type': 'glob', 'jid': '20201023170911092351', 'tgt': 'SJC-HOM-VTEP-1', 'pid': 1970, 'ret': '', 'user': 'sudo_chart2', 'arg': [], 'fun': 'nxos.ping'}, u'retcode': 0, u'success': True, u'fun': u'saltutil.find_job'}
[DEBUG   ] Subprocess ProcessPayload-Job-20201023170916146642 cleaned up
[DEBUG   ] DSC: Only available on Windows systems
[DEBUG   ] Module PSGet: Only available on Windows systems
[DEBUG   ] Could not LazyLoad nxos.ping: 'nxos' __virtual__ returned False: The nxos execution module failed to load: only available on proxy minions.
[DEBUG   ] Minion return retry timer set to 5 seconds (randomized)
[INFO    ] Returning information for job: 20201023170911092351
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/minion', u'SJC-HOM-VTEP-1', u'tcp://{REDACTED}:4506', u'aes')
[DEBUG   ] Initializing new AsyncAuth for (u'/etc/salt/pki/minion', u'SJC-HOM-VTEP-1', u'tcp://{REDACTED}:4506')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://{REDACTED}:4506
[DEBUG   ] Trying to connect to: tcp://{REDACTED}:4506
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[DEBUG   ] minion return: {u'fun_args': [], u'jid': u'20201023170911092351', u'return': u"'nxos' __virtual__ returned False: The nxos execution module failed to load: only available on proxy minions.", u'retcode': 1, u'success': False, u'fun': u'nxos.ping', u'out': u'nested'}
[DEBUG   ] Subprocess ProcessPayload-Job-20201023170911092351 cleaned up
```

**Expected behavior**
An NX-OS native GuestShell Salt minion installed on a Cisco Nexus switch should respond to NX-OS modules as expected.

**Screenshots**
N/A

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

Salt master version information:
```
[chart2@chart2-playground ~]$ salt --versions-report
Salt Version:
           Salt: 3000.3

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Apr  2 2020, 13:16:51)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.8.2003 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1062.18.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.8.2003 Core
```

NX-OS native GuestShell Salt minion version information:
```
[root@guestshell ~]# /bin/nsenter --net=/var/run/netns/management -- salt-minion -l debug -V
/usr/lib/python2.7/site-packages/salt/scripts.py:212: DeprecationWarning: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date.  Salt will drop support for Python 2.7 in the Sodium release or later.
Salt Version:
           Salt: 3000.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Apr  2 2020, 13:16:51)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.1.1503 Core
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.1.21-WR8.0.0.28-standard
         system: Linux
        version: CentOS Linux 7.1.1503 Core
```
</details>

**Additional context**
This issue will be fixed by #58291.

**Comment by ChristopherJHart** [comment]
I opened this issue to track the symptoms of the issue resolved by #58291 so that if anybody runs into this issue in the future, a quick Google search can guide them on how to resolve this issue.

**Simply put, if one upgrades their Salt master and minion to a version wherein #58291 is integrated, this issue will be resolved.**

Since this issue will already be resolved through an open PR, I am closing this issue out.
