### ISSUE TITLE
TypeError: Frame 0 (u'Some exception handling minion...) does not support the buffer interface.

### ISSUE THREAD

**Issue by ironman627** [saltstack/salt#58886]
### Description of Issue
Issued a salt command (see below) and the master does not respond, event bus does not record the command event, and throws the TypeError from above.

### Setup
/var/log/salt/master latest relevant entry:
###################################################
2020-11-04 23:28:22,388 [tornado.application:611 ][ERROR   ][27706] Exception in callback None
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/tornado/ioloop.py", line 865, in start
    handler_func(fd_obj, events)
  File "/usr/lib64/python2.7/site-packages/tornado/stack_context.py", line 274, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 444, in _handle_events
    self._handle_send()
  File "/usr/lib64/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 487, in _handle_send
    status = self.socket.send_multipart(msg, **kwargs)
  File "/usr/lib64/python2.7/site-packages/zmq/sugar/socket.py", line 363, in send_multipart
    i, rmsg,
TypeError: Frame 0 (u'Some exception handling minion...) does not support the buffer interface.
##########################################################################

### Steps to Reproduce Issue
Issue the following command:
salt -G ‘os:Windows’ service.status W3SVC

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
################################################
[root@ip-172-31-22-154 salt]# salt --versions-report
Salt Version:
           Salt: 2019.2.5

Dependency Versions:
           cffi: 1.14.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  7 2019, 00:51:29)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.7.1908 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1062.12.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.7.1908 Core
#######################################

**Comment by ironman627** [comment]
Here is the salt-master's debug relating to the above command:
########################################
[DEBUG   ] LazyLoaded localfs.init_kwargs
[WARNING ] /usr/lib/python2.7/site-packages/salt/utils/data.py:688: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if key == '*':

[DEBUG   ] Attempting to match 'Windows’' in '‘os' using delimiter ':'
[DEBUG   ] Attempting to match 'Windows’' in '‘os' using delimiter ':'
[DEBUG   ] Attempting to match 'Windows’' in '‘os' using delimiter ':'
[DEBUG   ] Attempting to match 'Windows’' in '‘os' using delimiter ':'
[DEBUG   ] Attempting to match 'Windows’' in '‘os' using delimiter ':'
[ERROR   ] Some exception handling a payload from minion
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/transport/zeromq.py", line 761, in handle_message
    ret, req_opts = yield self.payload_handler(payload)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 882, in run
    value = future.result()
  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 217, in wrapper
    result = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 1065, in _handle_payload
    'clear': self._handle_clear}[key](load)
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 1097, in _handle_clear
    ret = method(load), {'fun': 'send_clear'}
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 2171, in publish
    'error': 'Master could not resolve minions for target {0}'.format(clear_load['tgt'])
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)
[ERROR   ] Uncaught exception, closing connection.
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 444, in _handle_events
    self._handle_send()
  File "/usr/lib64/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 487, in _handle_send
    status = self.socket.send_multipart(msg, **kwargs)
  File "/usr/lib64/python2.7/site-packages/zmq/sugar/socket.py", line 363, in send_multipart
    i, rmsg,
TypeError: Frame 0 (u'Some exception handling minion...) does not support the buffer interface.
[ERROR   ] Exception in callback None
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/tornado/ioloop.py", line 865, in start
    handler_func(fd_obj, events)
  File "/usr/lib64/python2.7/site-packages/tornado/stack_context.py", line 274, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 444, in _handle_events
    self._handle_send()
  File "/usr/lib64/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 487, in _handle_send
    status = self.socket.send_multipart(msg, **kwargs)
  File "/usr/lib64/python2.7/site-packages/zmq/sugar/socket.py", line 363, in send_multipart
    i, rmsg,
TypeError: Frame 0 (u'Some exception handling minion...) does not support the buffer interface.
###############################################################

**Comment by ironman627** [comment]
If I execute the following: salt \*win service.status W3SVC it works fine.
Possibly something to do with the targeting of the grains.

**Comment by cmcmarrow** [comment]
I ran this on master and got no return as well. The minion or master did not crash and I cant find a stack trace in the logs.

**Comment by thinkst-marco** [comment]
Super late to the party, but the issue is that command includes smart quotes:
```
salt -G [‘]os:Windows[’] service.status W3SVC
         ^------------^--- these characters
```
Their UTF-8 values are \xe2\x80\x98 and \xe2\x80\x99... which is why the Unicode error triggers. The error `'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)` indicates that position 0 in the targeting string is `\xe2`, which confirms the hypothesis.
