### ISSUE TITLE
[BUG] 3002.1 lvm.lv_present TypeError: '<' not supported

### ISSUE THREAD

**Issue by daro1337** [saltstack/salt#58882]
**Description**
State lvm.lv_present gives error o nsalt-minion 3002.1:
```
          ID: cassandra-data
    Function: lvm.lv_present
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 2154, in call
                  *cdata["args"], **cdata["kwargs"]
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2188, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/lvm.py", line 334, in lv_present
                  if force is False and (size_mb < old_size_mb or extents < old_extents):
              TypeError: '<' not supported between instances of 'str' and 'int'
     Started: 13:26:57.917702
    Duration: 20.27 ms
     Changes: 
```
On salt-minion 3001.3 error does not exist.

**Setup**
```
cassandra-data:
  lvm.lv_present:
    - vgname: cassandra_vg
    - extents: '+100%FREE'
```

**Steps to Reproduce the behavior**
salt-call state.apply

**Expected behavior**
Resize LVM partition without error

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
salt-call --versions
Salt Version:
           Salt: 3002.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.3.10
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: 3.4.7
         pygit2: Not Installed
         Python: 3.6.9 (default, Oct  8 2020, 12:12:24)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 17.1.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: ubuntu 18.04 Bionic Beaver
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-122-generic
         system: Linux
        version: Ubuntu 18.04 Bionic Beaver
```
</details>

**Additional context**

**Comment by piterpunk** [comment]
Duplicated of #58759

**Comment by Ch3LL** [comment]
closing as duplicate
