### ISSUE TITLE
Salt-Master Slow Memory Increase and CPU Pegged

### ISSUE THREAD

**Issue by cmietzner** [saltstack/salt#58890]
### Description of Issue
After the upgrade to 3002, we began having issues with the salt-minions failing to connect to the salt master. Upon further inspection we noticed the salt-master had crashed. After a restart we noticed memory would increase by about 1gb every 12/hours. The CPU usage is also pegged at 100% for a single thread. The logs show the below error but not everytime the master crashes. 

2020-11-01 17:29:36,762 [tornado.general  :435 ][ERROR   ][1566] Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/stack_context.py", line 278, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/zmq/eventloop/zmqstream.py", line 196, in <lambda>
    self.on_recv(lambda msg: callback(self, msg), copy=copy)
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/gen.py", line 309, in wrapper
    yielded = next(result)
  File "/usr/lib/python3/dist-packages/salt/transport/zeromq.py", line 872, in handle_message
    ret, req_opts = yield self.payload_handler(payload)
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/gen.py", line 294, in wrapper
    result = func(*args, **kwargs)
  File "/usr/lib/python3.5/types.py", line 243, in wrapped
    coro = func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1131, in _handle_payload
    ret = {"aes": self._handle_aes, "clear": self._handle_clear}[key](load)
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1203, in _handle_aes
    ret = run_func(data)
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1198, in run_func
    return self.aes_funcs.run_func(data["cmd"], data)
  File "/usr/lib/python3/dist-packages/salt/master.py", line 2010, in run_func
    ret = getattr(self, func)(load)
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1707, in _pillar
    data = pillar.compile_pillar()
  File "/usr/lib/python3/dist-packages/salt/pillar/__init__.py", line 1185, in compile_pillar
    matches = self.top_matches(top)
  File "/usr/lib/python3/dist-packages/salt/pillar/__init__.py", line 814, in top_matches
    match, data, self.opts.get("nodegroups", {}),
  File "/usr/lib/python3/dist-packages/salt/matchers/confirm_top.py", line 24, in confirm_top
    matchers = salt.loader.matchers(__opts__)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 332, in matchers
    return LazyLoader(_module_dirs(opts, "matchers"), opts, tag="matchers")
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1274, in __init__
    self.clean_modules()
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1347, in clean_modules
    _cleanup_module_namespace(self.loaded_base_name, delete_from_sys_modules=True)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1169, in _cleanup_module_namespace
    if name.startswith(loaded_base_name):
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1086, in _handle_signals
    channel.close()
  File "/usr/lib/python3/dist-packages/salt/transport/zeromq.py", line 748, in close
    self.context.term()
  File "zmq/backend/cython/context.pyx", line 136, in zmq.backend.cython.context.Context.term (zmq/backend/cython/context.c:2010)
  File "zmq/backend/cython/checkrc.pxd", line 12, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/context.c:2899)
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1087, in _handle_signals
    super()._handle_signals(signum, sigframe)
  File "/usr/lib/python3/dist-packages/salt/utils/process.py", line 981, in _handle_signals
    sys.exit(salt.defaults.exitcodes.EX_OK)
SystemExit: 0

In the graphs below you can see I upgraded salt on the 28th and immediately the CPU was pegged and memory started increasing. And then we increased total memory 2 days ago. The sudden decreases in memory are reboots or service restarts.
![Salt](https://user-images.githubusercontent.com/5660111/98268998-6e176500-1f4a-11eb-87f2-da73c487060b.png)

### Versions Report
root@salt:/var/log/salt# salt --versions-report
Salt Version:
           Salt: 3002

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
         Jinja2: 2.9.6
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: Not Installed
   pycryptodome: 3.4.7
         pygit2: Not Installed
         Python: 3.5.2 (default, Oct  7 2020, 17:19:02)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 17.1.2
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4

System Versions:
           dist: ubuntu 16.04 Xenial Xerus
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-193-generic
         system: Linux
        version: Ubuntu 16.04 Xenial Xerus

**Comment by jwolfe-ns** [comment]
I'm seeing this also on our masters with only a couple thousand minions on `3002.1`. Our larger masters have been left on 3001 and haven't experienced any issues. There are a handful for different Maintenance procs. My trace is different, but they seem like they might both be related to ZMQ issues as a session is in an unexpected state.

```
2020-11-09 04:29:24,751 [salt.utils.process:900 ][ERROR   ][2077345] An un-handled exception from the multiprocessing process 'Maintenance-5' was caught:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/client/__init__.py", line 1857, in pub
    payload = channel.send(payload_kwargs, timeout=timeout)
  File "/usr/lib/python3/dist-packages/salt/utils/asynchronous.py", line 126, in wrap
    six.reraise(*results[1])
  File "/usr/lib/python3/dist-packages/salt/ext/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/salt/utils/asynchronous.py", line 132, in _target
    result = io_loop.run_sync(lambda: getattr(self.obj, key)(*args, **kwargs))
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/ioloop.py", line 459, in run_sync
    return future_cell[0].result()
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/gen.py", line 1064, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python3/dist-packages/salt/transport/zeromq.py", line 444, in send
    ret = yield self._uncrypted_transfer(load, tries=tries, timeout=timeout)
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/gen.py", line 1064, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python3/dist-packages/salt/transport/zeromq.py", line 432, in _uncrypted_transfer
    ret = yield self.message_client.send(
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
salt.exceptions.SaltReqTimeoutError: Message timed out

**Comment by jwolfe-ns** [comment]
Actually missed this prior. The exceptions are going to be random as it's actually OOM killing procs. Not sure if this is the case for you @cmietzner 
```
[Fri Nov  6 09:49:41 2020] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/system.slice/salt-master.service,task=/usr/bin/python,pid=2077755,uid=0
[Fri Nov  6 12:14:35 2020] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/system.slice/salt-master.service,task=/usr/bin/python,pid=2077764,uid=0
[Fri Nov  6 15:05:40 2020] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/system.slice/salt-master.service,task=/usr/bin/python,pid=2077763,uid=0
[Fri Nov  6 17:43:21 2020] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/system.slice/salt-master.service,task=/usr/bin/python,pid=2077772,uid=0
[Fri Nov  6 20:34:42 2020] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/system.slice/salt-master.service,task=/usr/bin/python,pid=2077757,uid=0
[Fri Nov  6 23:47:19 2020] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/system.slice/salt-master.service,task=/usr/bin/python,pid=2077770,uid=0
[Sat Nov  7 03:19:34 2020] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/system.slice/salt-master.service,task=/usr/bin/python,pid=2077761,uid=0
[Sat Nov  7 06:59:49 2020] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/system.slice/salt-master.service,task=/usr/bin/python,pid=2077771,uid=0
[Sat Nov  7 10:58:12 2020] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/system.slice/salt-master.service,task=/usr/bin/python,pid=2077775,uid=0
[Sat Nov  7 16:16:03 2020] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/system.slice/salt-master.service,task=/usr/bin/python,pid=2077766,uid=0
[Sat Nov  7 23:16:49 2020] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/system.slice/salt-master.service,task=/usr/bin/python,pid=2077758,uid=0
[Sun Nov  8 09:28:34 2020] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/system.slice/salt-master.service,task=/usr/bin/python,pid=2077756,uid=0
[Mon Nov  9 00:37:26 2020] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/system.slice/salt-master.service,task=/usr/bin/python,pid=2077776,uid=0
```

**Comment by cmietzner** [comment]
@jwolfe-ns , what log are you seeing that in? I'm not seeing it in the master or syslogs.

**Comment by jwolfe-ns** [comment]
@cmietzner `dmesg`, which may not be in syslog. If you are seeing mem cap out, it's likely you're having OOM kills also.

**Comment by venugopalnaidu** [comment]
Hi All, 

**we are facing salt cpu pegged to peak and huge memory usage after upgrading to latest 3002.2.**

Salt Version:
           Salt: 3002.1
 
Dependency Versions:
           cffi: 1.12.3
       cherrypy: Not Installed
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: 3.4.7
         pygit2: Not Installed
         Python: 3.6.9 (default, Apr 18 2020, 01:56:04)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 17.1.2
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: ubuntu 18.04 Bionic Beaver
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-88-generic
         system: Linux
        version: Ubuntu 18.04 Bionic Beaver

**We are getting the below error in salt-master log file**

[CRITICAL] The specified 'local_cache' returner threw a stack trace:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/job.py", line 75, in store_job
    mminion.returners[jidstore_fstr](False, passed_jid=load["jid"])
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1354, in __getitem__
    func = super().__getitem__(item)
  File "/usr/lib/python3/dist-packages/salt/utils/lazy.py", line 101, in __getitem__
    if self._load(key):
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2012, in _load
    ret = _inner_load(mod_name)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2001, in _inner_load
    if self._load_module(name) and key in self._dict:
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1838, in _load_module
    self.__clean_sys_path()
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1657, in __clean_sys_path
    importlib.invalidate_caches()
  File "/usr/lib/python3.6/importlib/__init__.py", line 71, in invalidate_caches
    finder.invalidate_caches()
  File "<frozen importlib._bootstrap_external>", line 1063, in invalidate_caches
RuntimeError: dictionary changed size during iteration

**The below error in syslog**

 Out of memory: Kill process 17091 (salt-master) score 756 or sacrifice child
Killed process 17091 (salt-master) total-vm:21735540kB, anon-rss:4821856kB, file-rss:0kB, shmem-rss:0kB

**Comment by viktordaniel** [comment]
Hi! After upgrade to salt 3002, we are experiencing the excessive CPU usage as well: 
![image](https://user-images.githubusercontent.com/32159337/99055682-eeb51180-2599-11eb-91c2-be95dbcc80cc.png)

**Comment by jwolfe-ns** [comment]
This one is pretty bad.. it basically makes 3002 unusable as a master. If it is ZMQ related, it appears to affect ZMQ `4.1.4`, `4.2.5`, and `4.3.2`

**Comment by cmietzner** [comment]
I did an upgrade last night to 3002.2 and so far I am seeing big improvements. Memory and CPU usage is way down. There hasnt been much load and I did double my CPUs from 2 to 4. 

Salt Version:
          Salt: 3002.2

Dependency Versions:
          cffi: 1.11.5
      cherrypy: Not Installed
      dateutil: 2.4.2
     docker-py: Not Installed
         gitdb: 0.6.4
     gitpython: 1.0.1
        Jinja2: 2.9.6
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.19
      pycrypto: Not Installed
  pycryptodome: 3.4.7
        pygit2: Not Installed
        Python: 3.5.2 (default, Oct  7 2020, 17:19:02)
  python-gnupg: 0.3.8
        PyYAML: 3.11
         PyZMQ: 17.1.2
         smmap: 0.9.0
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4

System Versions:
          dist: ubuntu 16.04 Xenial Xerus
        locale: UTF-8
       machine: x86_64
       release: 4.4.0-194-generic
        system: Linux
       version: Ubuntu 16.04 Xenial Xerus

**Comment by jwolfe-ns** [comment]
I believe this was the fix, which isn't mentioned in the changelog

https://github.com/saltstack/salt/pull/58862

There are 2 other reports for this same issue, so this one can likely be marked a dupe. cc @garethgreenaway 

https://github.com/saltstack/salt/issues/58791
https://github.com/saltstack/salt/issues/58785

**Comment by garethgreenaway** [comment]
3002 had a really bad memory leak and the recommendation is to upgrade to 3002.2.  We've had a few different similar reports so I'll close this out as a duplicate.
