### ISSUE TITLE
salt-minion issue with python3.8 decorators

### ISSUE THREAD

**Issue by EthanB11** [saltstack/salt#58895]
Description of problem:
Salt-minion not able to take process commands from salt-master.

Version-Release number of selected component (if applicable):
salt-minion-3001rc1-2.fc32.noarch and salt-minion-3001.1-1.fc32.noarch
python3-decorator-4.4.0-6.fc32.noarch

How reproducible:
All machines upgraded from Fedora 31 to Fedora 32 exhibit this issue.

Steps to Reproduce:
1. Upgraded Fedora 31 to Fedora 32.
2. Removed python2 packages so only python3 remained.
3. Start salt-minion on client.

Actual results:
```
2020-08-12 11:57:28,945 [salt.utils.decorators:722 ][WARNING ][4130] The function "module.run" is using its deprecated version and will expire in version "Phosphorus".
2020-08-12 11:57:28,948 [salt.state       :328 ][ERROR   ][4130] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/salt/utils/decorators/__init__.py", line 360, in _call_function
    return self._function(*args, **kwargs)
TypeError: _run() missing 1 required positional argument: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/salt/state.py", line 2153, in call
    ret = self.states[cdata["full"]](
  File "/usr/lib/python3.8/site-packages/salt/loader.py", line 2087, in wrapper
    return f(*args, **kwargs)
  File "/var/cache/salt/minion/extmods/states/mgrcompat.py", line 85, in module_run
    ret = module.run(**new_kwargs)
  File "/usr/lib/python3.8/site-packages/salt/utils/decorators/__init__.py", line 746, in _decorate
    return self._call_function(kwargs)
  File "/usr/lib/python3.8/site-packages/salt/utils/decorators/__init__.py", line 362, in _call_function
    error = six.text_type(error).replace(
TypeError: replace() argument 1 must be str, not function

2020-08-12 11:57:28,949 [salt.utils.decorators:722 ][WARNING ][4130] The function "module.run" is using its deprecated version and will expire in version "Phosphorus".
2020-08-12 11:57:28,949 [salt.state       :328 ][ERROR   ][4130] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/salt/utils/decorators/__init__.py", line 360, in _call_function
    return self._function(*args, **kwargs)
TypeError: _run() missing 1 required positional argument: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/salt/state.py", line 2153, in call
    ret = self.states[cdata["full"]](
  File "/usr/lib/python3.8/site-packages/salt/loader.py", line 2087, in wrapper
    return f(*args, **kwargs)
  File "/var/cache/salt/minion/extmods/states/mgrcompat.py", line 85, in module_run
    ret = module.run(**new_kwargs)
  File "/usr/lib/python3.8/site-packages/salt/utils/decorators/__init__.py", line 746, in _decorate
    return self._call_function(kwargs)
  File "/usr/lib/python3.8/site-packages/salt/utils/decorators/__init__.py", line 362, in _call_function
    error = six.text_type(error).replace(
TypeError: replace() argument 1 must be str, not function

2020-08-12 11:57:28,951 [salt.utils.decorators:722 ][WARNING ][4130] The function "module.run" is using its deprecated version and will expire in version "Phosphorus".
2020-08-12 11:57:28,951 [salt.state       :328 ][ERROR   ][4130] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/salt/utils/decorators/__init__.py", line 360, in _call_function
    return self._function(*args, **kwargs)
TypeError: _run() missing 1 required positional argument: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/salt/state.py", line 2153, in call
    ret = self.states[cdata["full"]](
  File "/usr/lib/python3.8/site-packages/salt/loader.py", line 2087, in wrapper
    return f(*args, **kwargs)
  File "/var/cache/salt/minion/extmods/states/mgrcompat.py", line 85, in module_run
    ret = module.run(**new_kwargs)
  File "/usr/lib/python3.8/site-packages/salt/utils/decorators/__init__.py", line 746, in _decorate
    return self._call_function(kwargs)
  File "/usr/lib/python3.8/site-packages/salt/utils/decorators/__init__.py", line 362, in _call_function
    error = six.text_type(error).replace(
TypeError: replace() argument 1 must be str, not function

2020-08-12 11:57:29,273 [salt.utils.decorators:722 ][WARNING ][4130] The function "module.run" is using its deprecated version and will expire in version "Phosphorus".
2020-08-12 11:57:29,274 [salt.state       :328 ][ERROR   ][4130] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/salt/utils/decorators/__init__.py", line 360, in _call_function
    return self._function(*args, **kwargs)
TypeError: _run() missing 1 required positional argument: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/salt/state.py", line 2153, in call
    ret = self.states[cdata["full"]](
  File "/usr/lib/python3.8/site-packages/salt/loader.py", line 2087, in wrapper
    return f(*args, **kwargs)
  File "/var/cache/salt/minion/extmods/states/mgrcompat.py", line 85, in module_run
    ret = module.run(**new_kwargs)
  File "/usr/lib/python3.8/site-packages/salt/utils/decorators/__init__.py", line 746, in _decorate
    return self._call_function(kwargs)
  File "/usr/lib/python3.8/site-packages/salt/utils/decorators/__init__.py", line 362, in _call_function
    error = six.text_type(error).replace(
TypeError: replace() argument 1 must be str, not function

2020-08-12 11:57:29,275 [salt.utils.decorators:722 ][WARNING ][4130] The function "module.run" is using its deprecated version and will expire in version "Phosphorus".
2020-08-12 11:57:29,276 [salt.state       :328 ][ERROR   ][4130] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/salt/utils/decorators/__init__.py", line 360, in _call_function
    return self._function(*args, **kwargs)
TypeError: _run() missing 1 required positional argument: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/salt/state.py", line 2153, in call
    ret = self.states[cdata["full"]](
  File "/usr/lib/python3.8/site-packages/salt/loader.py", line 2087, in wrapper
    return f(*args, **kwargs)
  File "/var/cache/salt/minion/extmods/states/mgrcompat.py", line 85, in module_run
    ret = module.run(**new_kwargs)
  File "/usr/lib/python3.8/site-packages/salt/utils/decorators/__init__.py", line 746, in _decorate
    return self._call_function(kwargs)
  File "/usr/lib/python3.8/site-packages/salt/utils/decorators/__init__.py", line 362, in _call_function
    error = six.text_type(error).replace(
TypeError: replace() argument 1 must be str, not function

2020-08-12 11:57:29,277 [salt.utils.decorators:722 ][WARNING ][4130] The function "module.run" is using its deprecated version and will expire in version "Phosphorus".
2020-08-12 11:57:29,278 [salt.state       :328 ][ERROR   ][4130] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/salt/utils/decorators/__init__.py", line 360, in _call_function
    return self._function(*args, **kwargs)
TypeError: _run() missing 1 required positional argument: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/salt/state.py", line 2153, in call
    ret = self.states[cdata["full"]](
  File "/usr/lib/python3.8/site-packages/salt/loader.py", line 2087, in wrapper
    return f(*args, **kwargs)
  File "/var/cache/salt/minion/extmods/states/mgrcompat.py", line 85, in module_run
    ret = module.run(**new_kwargs)
  File "/usr/lib/python3.8/site-packages/salt/utils/decorators/__init__.py", line 746, in _decorate
    return self._call_function(kwargs)
  File "/usr/lib/python3.8/site-packages/salt/utils/decorators/__init__.py", line 362, in _call_function
    error = six.text_type(error).replace(
TypeError: replace() argument 1 must be str, not function
```

Expected results:
No errors and salt commands complete sucessfully.

Additional info:
Salt-master through Uyuni 2020.07 is running on OpenSUSE Leap 15.2, package salt-master-3000-lp152.3.6.1.x86_64 and salt-master-3000-lp152.3.12.1.x86_64.

RedHat bug https://bugzilla.redhat.com/show_bug.cgi?id=1868454

**Comment by s0undt3ch** [comment]
Looks like this code path just needs to drop Py2 and six support.

**Comment by s0undt3ch** [comment]
What is `mgrcompat`? Because the traceback is going through that code path, which does not exist in salt.

**Comment by sagetherage** [comment]
@EthanB11 are you able to answer Pedro's question, above? ^^

**Comment by EthanB11** [comment]
I do not know, I cant check the contents of the file tomorrow, but I might hazard a guess it's from Uyuni. https://github.com/uyuni-project/uyuni/blob/master/susemanager-utils/susemanager-sls/src/states/mgrcompat.py

**Comment by EthanB11** [comment]
The file is from Uyuni.

```
# -*- coding: utf-8 -*-
'''
SUSE Manager custom wrapper for Salt "module.run" state module.

This wrapper determines the syntax to use for calling the Salt "module.run" state
that has changed between different Salt version.

Using this wrapper we ensure all SUSE Manager SLS files are using the same syntax
regardless the actual Salt version installed on the minion.

'''
from __future__ import absolute_import

# Import salt libs
from salt.utils.odict import OrderedDict
from salt.states import module

import logging

log = logging.getLogger(__name__)

__virtualname__ = 'mgrcompat'


def __virtual__():
    '''
    This module is always enabled while 'module.run' is available.
    '''
    module.__salt__ = __salt__
    module.__opts__ = __opts__
    module.__pillar__ = __pillar__
    module.__grains__ = __grains__
    module.__context__ = __context__
    module.__utils__ = __utils__
    return __virtualname__

def _tailor_kwargs_to_new_syntax(name, **kwargs):
    nkwargs = {}
    _opt_kwargs = None
    for k, v in kwargs.items():
        if k.startswith("m_"):
            nkwargs[k[2:]] = v
        elif k == 'kwargs':
            _opt_kwargs = kwargs[k]
        else:
            nkwargs[k] = v
    ret = {name: [OrderedDict(nkwargs)]}
    if _opt_kwargs:
        ret[name].append(OrderedDict(_opt_kwargs))
    return ret

def module_run(**kwargs):
    '''
    This function execute the Salt "module.run" state passing the arguments
    in the right way according to the supported syntax depending on the Salt
    minion version and configuration

    '''

    # The new syntax will be used as the default
    use_new_syntax = True

    if __grains__['saltversioninfo'][0] > 3002:
        # Only new syntax - default behavior for Phosphorus and future releases
        pass
    elif __grains__['saltversioninfo'][0] > 2016 and 'module.run' in __opts__.get('use_superseded', []):
        # New syntax - explicitely enabled via 'use_superseded' configuration on 2018.3, 2019.2, 3000.x and 3002.x
        pass
    elif __grains__['saltversioninfo'][0] > 2016 and not 'module.run' in __opts__.get('use_superseded', []):
        # Old syntax - default behavior for 2018.3, 2019.2, 3000.x and 3002.x
        use_new_syntax = False
    elif __grains__['saltversioninfo'][0] <= 2016:
        # Only old syntax - the new syntax is not available for 2016.11 and 2015.8
        use_new_syntax = False

    if use_new_syntax:
        log.debug("Minion is using the new syntax for 'module.run' state. Tailoring parameters.")
        log.debug("Old parameters: {}".format(kwargs))
        old_name = kwargs.pop('name')
        new_kwargs = _tailor_kwargs_to_new_syntax(old_name, **kwargs)
        log.debug("New parameters for 'module.run' state: {}".format(new_kwargs))
    else:
        new_kwargs = kwargs

    ret = module.run(**new_kwargs)
    if use_new_syntax:
        if ret['changes']:
            changes = ret['changes'].pop(old_name)
            ret['changes']['ret'] = changessalt-minion-3001.6-1.fc32.noarch
        ret['name'] = old_name
    return ret
```


 Using the latest packages from Fedora 32 and Uyuni 2021.02 the salt stack is working correctly. I don't know where the issue came from, but it has been resolved.

salt-minion-3001.6-1.fc32.noarch and python3-decorator-4.4.0-6.fc32.noarch are the version on the Fedora 32 clients now.

**Comment by EthanB11** [comment]
It's back with the latest Uyuni 05-2021 and Fedora 33.

Fedora 33 packages - salt-minion-3003-1.fc33.noarch python3-decorator-4.4.2-3.fc33.noarch
Uyuni server packages - salt-master-3000-lp152.3.33.1.x86_64 uyuni-base-server-4.2.3-2.2.uyuni.x86_64

```----------
          ID: sync_states
    Function: mgrcompat.run
        Name: saltutil.sync_states
      Result: false
     Comment: An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/salt/utils/decorators/__init__.py", line 360, in _call_function
    return self._function(*args, **kwargs)
TypeError: _run() missing 1 required positional argument: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/salt/state.py", line 2171, in call
    ret = self.states[cdata["full"]](
  File "/usr/lib/python3.9/site-packages/salt/loader.py", line 1235, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/salt/loader.py", line 2268, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/salt/loader.py", line 2283, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/salt/loader.py", line 2316, in wrapper
    return f(*args, **kwargs)
  File "/var/cache/salt/minion/extmods/states/mgrcompat.py", line 85, in module_run
    ret = module.run(**new_kwargs)
  File "/usr/lib/python3.9/site-packages/salt/utils/decorators/__init__.py", line 746, in _decorate
    return self._call_function(kwargs)
  File "/usr/lib/python3.9/site-packages/salt/utils/decorators/__init__.py", line 362, in _call_function
    error = six.text_type(error).replace(
TypeError: replace() argument 1 must be str, not function

     Started: 15:48:14.091541
    Duration: 7.195
         SLS: util.syncstates
     Changed: {}```

**Comment by whytewolf** [comment]
this looks to be third party related. and that their package is not compatible with adding ours. this is not a salt issue.
