### ISSUE TITLE
[BUG] Since the last security update os salt eauth authentication doesn't work

### ISSUE THREAD

**Issue by StefanSa** [saltstack/salt#58909]
**Description**
After the last  security updates on our uyuni server (latest version), salt eauth authentication doesn't work

**Setup**
/etc/salt/master.d/susemanager.conf (api auth)
```
external_auth:
  file:
    ^filename: /etc/salt/master.d/susemanager-users.txt
    ^hashtype: sha512
    admin:
      - .*
      - '@wheel'
      - '@runner'
      - '@jobs'
```

**Steps to Reproduce the behavior**
/var/log/salt/api:
```
2020-11-09 10:28:48,210 [salt.auth        :310 ][WARNING ][1990] Authentication failure of type "eauth" occurred.
2020-11-09 10:33:08,758 [salt.auth        :310 ][WARNING ][1990] Authentication failure of type "eauth" occurred.
2020-11-09 10:50:35,516 [salt.auth        :310 ][WARNING ][1990] Authentication failure of type "eauth" occurred.
```
/var/log/salt/master:
```
2020-11-08 15:01:46,365 [salt.loader      :860 ][CRITICAL][11774] Failed to load grains defined in grain file extra.uefi in function <function uefi at
0x7fea07060c80>, error:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 853, in grains
    ret = funcs[key](**kwargs)
  File "/usr/lib/python3.6/site-packages/salt/grains/extra.py", line 106, in uefi
    "efi-secure-boot": __secure_boot(),
  File "/usr/lib/python3.6/site-packages/salt/grains/extra.py", line 97, in __secure_boot
    with salt.utils.files.fopen(sboot[0], "rb") as fd:
  File "/usr/lib/python3.6/site-packages/salt/utils/files.py", line 399, in fopen
    f_handle = open(*args, **kwargs)  # pylint: disable=resource-leakage
PermissionError: [Errno 13] Permission denied: '/sys/firmware/efi/vars/SecureBoot-8be4df61-93ca-11d2-aa0d-00e098032b8c/data'
```

**Versions Report**
salt --versions-report
```
Salt Version:
           Salt: 3000

Dependency Versions:
           cffi: 1.13.2
       cherrypy: unknown
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10.1
        libgit2: 0.28.4
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 3.9.0
   pycryptodome: Not Installed
         pygit2: 0.28.2
         Python: 3.6.10 (default, Jan 16 2020, 09:12:04) [GCC]
   python-gnupg: Not Installed
         PyYAML: 5.1.2
          PyZMQ: 17.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.3

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 5.3.18-lp152.47-default
         system: Linux
        version: Not Installed
```
Any help here ?

**Comment by aplanas** [comment]
@StefanSa The grains error comes from the openSUSE version of the package, and the fix is already available here https://github.com/openSUSE/salt/pull/287

The upstream patch is also living here https://github.com/saltstack/salt/pull/58520, but not merged.

If this is the only error, IMO we should close it from here.

**Comment by StefanSa** [comment]
@aplanas 
yes, currently this is the only but serious mistake.
Bootstrapping is currently not possible with this bug.

**Comment by aplanas** [comment]
> yes, currently this is the only but serious mistake.

The fix in openSUSE just gets merged, and a new release will happen soon.

@StefanSa because the bug is not present in the SaltStack version, can you close the issue?

**Comment by StefanSa** [comment]
Hi there @aplanas @Ch3LL @psagers 
Since these are apparently not a bug in the SaltStack version, i close this ticket.
