### ISSUE TITLE
[BUG] win_perms_reset together with win_inheritance do not work together correctly

### ISSUE THREAD

**Issue by Varbin** [saltstack/salt#58924]
**Description**
When using `win_perms_reset` and `win_inheritance` together salt does not work correctly. Such combination is required for securely creating a new folder on the C: drive root, as by default any users could create new files all newly created folders.

If the folder does not exist, it is created, but with a completely empty set of permissions. If the folder exists, it fails with a similar error as in #58541. 

**Setup**

A minimal state to reproduce the above problem is:

```
C:/brokendir:
    file.directory:
        - win_owner: Administrator
        - win_perms:
          SYSTEM:
            perms: full_control
          Administrator:
            perms: full_control
        - win_deny_perms: []
        - win_perms_reset: yes
        - win_inheritance: no

C:/brokendir/test.txt:
    file.touch:
        - require:
          - file: C:/brokendir
```

**Steps to Reproduce the behavior**

Apply above state. The below `salt-call` is executed from the built-in "Administrator" account, but the same problem arises if applied from the salt master.

*Result if directory does not exist*:

<details><summary>salt-call -l debug state.apply brokendir</summary>

```
C:\Windows\system32>salt-call -l debug state.apply brokendir
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Including configuration from 'c:\salt\conf\minion.d\_schedule.conf'
[DEBUG   ] Reading configuration from c:\salt\conf\minion.d\_schedule.conf
[DEBUG   ] Using cached minion ID from c:\salt\conf\minion_id: WIN-LCADMNSTK2H.user.boreus.de
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Including configuration from 'c:\salt\conf\minion.d\_schedule.conf'
[DEBUG   ] Reading configuration from c:\salt\conf\minion.d\_schedule.conf
[DEBUG   ] Connecting to master. Attempt 1 (infinite attempts)
[DEBUG   ] Master URI: tcp://10.114.100.250:4506
[DEBUG   ] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'WIN-LCADMNSTK2H.user.boreus.de', 'tcp://10.114.100.250:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (1466)
[DEBUG   ] Setting zmq_reconnect_ivl to '1466ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'WIN-LCADMNSTK2H.user.boreus.de', 'tcp://10.114.100.250:4506', 'clear')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://10.114.100.250:4506
[DEBUG   ] Trying to connect to: tcp://10.114.100.250:4506
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] salt.crypt._get_key_with_evict: Loading private key
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[DEBUG   ] Connecting the Minion to the Master publish port, using the URI: tcp://10.114.100.250:4505
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
[DEBUG   ] Determining pillar cache
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'WIN-LCADMNSTK2H.user.boreus.de', 'tcp://10.114.100.250:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'WIN-LCADMNSTK2H.user.boreus.de', 'tcp://10.114.100.250:4506')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://10.114.100.250:4506
[DEBUG   ] Trying to connect to: tcp://10.114.100.250:4506
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded state.apply
[DEBUG   ] LazyLoaded direct_call.execute
[DEBUG   ] LazyLoaded saltutil.is_running
[DEBUG   ] LazyLoaded grains.get
[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'WIN-LCADMNSTK2H.user.boreus.de', 'tcp://10.114.100.250:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'WIN-LCADMNSTK2H.user.boreus.de', 'tcp://10.114.100.250:4506')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://10.114.100.250:4506
[DEBUG   ] Trying to connect to: tcp://10.114.100.250:4506
[DEBUG   ] Gathering pillar data for state run
[DEBUG   ] Finished gathering pillar data for state run
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] In saltenv 'base', looking at rel_path 'brokendir.sls' to resolve 'salt://brokendir.sls'
[DEBUG   ] In saltenv 'base', ** considering ** path 'c:\salt\var\cache\salt\minion\files\base\brokendir.sls' to resolve 'salt://brokendir.sls'
[DEBUG   ] compile template: c:\salt\var\cache\salt\minion\files\base\brokendir.sls
[DEBUG   ] Jinja search path: ['c:\\salt\\var\\cache\\salt\\minion\\files\\base']
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'WIN-LCADMNSTK2H.user.boreus.de', 'tcp://10.114.100.250:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'WIN-LCADMNSTK2H.user.boreus.de', 'tcp://10.114.100.250:4506')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://10.114.100.250:4506
[DEBUG   ] Trying to connect to: tcp://10.114.100.250:4506
[PROFILE ] Time (in seconds) to render 'c:\salt\var\cache\salt\minion\files\base\brokendir.sls' using 'jinja' renderer: 0.07812094688415527
[DEBUG   ] Rendered data from file: c:\salt\var\cache\salt\minion\files\base\brokendir.sls:
C:/brokendir:
    file.directory:
        - win_owner: Administrator
        - win_perms:
          SYSTEM:
            perms: full_control
          Administrator:
            perms: full_control
        - win_deny_perms: []
        - win_perms_reset: yes
        - win_inheritance: no

C:/brokendir/test.txt:
    file.touch:
        - require:
          - file: C:/brokendir

[DEBUG   ] Results of YAML rendering:
OrderedDict([('C:/brokendir', OrderedDict([('file.directory', [OrderedDict([('win_owner', 'Administrator')]), OrderedDict([('win_perms', None), ('SYSTEM', OrderedDict([('perms', 'full_control')])), ('Administrator', OrderedDict([('perms', 'full_control')]))]), OrderedDict([('win_deny_perms', [])]), OrderedDict([('win_perms_reset', True)]), OrderedDict([('win_inheritance', False)])])])), ('C:/brokendir/test.txt', OrderedDict([('file.touch', [OrderedDict([('require', [OrderedDict([('file', 'C:/brokendir')])])])])]))])
[PROFILE ] Time (in seconds) to render 'c:\salt\var\cache\salt\minion\files\base\brokendir.sls' using 'yaml' renderer: 0.0
[DEBUG   ] LazyLoaded config.option
[DEBUG   ] LazyLoaded file.directory
[INFO    ] Running state [C:/brokendir] at time 16:41:25.953100
[INFO    ] Executing state file.directory for [C:/brokendir]
[DEBUG   ] LazyLoaded file.mkdir
[DEBUG   ] LazyLoaded dacl.set_perms
[DEBUG   ] Getting current permissions for C:/brokendir
[DEBUG   ] Resetting permissions for C:/brokendir
[INFO    ] {'C:/brokendir': 'New Dir'}
[INFO    ] Completed state [C:/brokendir] at time 16:41:26.078114 (duration_in_ms=125.014)
[INFO    ] Running state [C:/brokendir/test.txt] at time 16:41:26.078114
[INFO    ] Executing state file.touch for [C:/brokendir/test.txt]
[DEBUG   ] An exception occurred in this state: Permission denied
Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt-3002.1-py3.7.egg\salt\modules\file.py", line 3547, in touch
    with salt.utils.files.fopen(name, "a"):
  File "c:\salt\bin\lib\site-packages\salt-3002.1-py3.7.egg\salt\utils\files.py", line 396, in fopen
    f_handle = open(*args, **kwargs)  # pylint: disable=resource-leakage
PermissionError: [Errno 13] Permission denied: 'C:/brokendir/test.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt-3002.1-py3.7.egg\salt\state.py", line 2154, in call
    *cdata["args"], **cdata["kwargs"]
  File "c:\salt\bin\lib\site-packages\salt-3002.1-py3.7.egg\salt\loader.py", line 2188, in wrapper
    return f(*args, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt-3002.1-py3.7.egg\salt\states\file.py", line 7127, in touch
    ret["result"] = __salt__["file.touch"](name, atime, mtime)
  File "c:\salt\bin\lib\site-packages\salt-3002.1-py3.7.egg\salt\modules\file.py", line 3563, in touch
    raise CommandExecutionError(exc.strerror)
salt.exceptions.CommandExecutionError: Permission denied
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt-3002.1-py3.7.egg\salt\modules\file.py", line 3547, in touch
    with salt.utils.files.fopen(name, "a"):
  File "c:\salt\bin\lib\site-packages\salt-3002.1-py3.7.egg\salt\utils\files.py", line 396, in fopen
    f_handle = open(*args, **kwargs)  # pylint: disable=resource-leakage
PermissionError: [Errno 13] Permission denied: 'C:/brokendir/test.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt-3002.1-py3.7.egg\salt\state.py", line 2154, in call
    *cdata["args"], **cdata["kwargs"]
  File "c:\salt\bin\lib\site-packages\salt-3002.1-py3.7.egg\salt\loader.py", line 2188, in wrapper
    return f(*args, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt-3002.1-py3.7.egg\salt\states\file.py", line 7127, in touch
    ret["result"] = __salt__["file.touch"](name, atime, mtime)
  File "c:\salt\bin\lib\site-packages\salt-3002.1-py3.7.egg\salt\modules\file.py", line 3563, in touch
    raise CommandExecutionError(exc.strerror)
salt.exceptions.CommandExecutionError: Permission denied

[INFO    ] Completed state [C:/brokendir/test.txt] at time 16:41:26.124974 (duration_in_ms=46.86)
[DEBUG   ] File c:\salt\var\cache\salt\minion\accumulator\1980412398344 does not exist, no need to cleanup
[DEBUG   ] LazyLoaded cmd.run
[INFO    ] Executing command ['attrib', '-R', 'c:\\salt\\var\\cache\\salt\\minion\\sls.p'] in directory 'C:\Users\Administrator'
[DEBUG   ] output:
[DEBUG   ] LazyLoaded state.check_result
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'WIN-LCADMNSTK2H.user.boreus.de', 'tcp://10.114.100.250:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'WIN-LCADMNSTK2H.user.boreus.de', 'tcp://10.114.100.250:4506')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://10.114.100.250:4506
[DEBUG   ] Trying to connect to: tcp://10.114.100.250:4506
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[DEBUG   ] LazyLoaded highstate.output
[DEBUG   ] LazyLoaded nested.output
local:
----------
          ID: C:/brokendir
    Function: file.directory
      Result: True
     Comment: Directory C:/brokendir updated
     Started: 16:41:25.953100
    Duration: 125.014 ms
     Changes:
              ----------
              C:/brokendir:
                  New Dir
----------
          ID: C:/brokendir/test.txt
    Function: file.touch
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "c:\salt\bin\lib\site-packages\salt-3002.1-py3.7.egg\salt\modules\file.py", line 3547, in touch
                  with salt.utils.files.fopen(name, "a"):
                File "c:\salt\bin\lib\site-packages\salt-3002.1-py3.7.egg\salt\utils\files.py", line 396, in fopen
                  f_handle = open(*args, **kwargs)  # pylint: disable=resource-leakage
              PermissionError: [Errno 13] Permission denied: 'C:/brokendir/test.txt'

              During handling of the above exception, another exception occurred:

              Traceback (most recent call last):
                File "c:\salt\bin\lib\site-packages\salt-3002.1-py3.7.egg\salt\state.py", line 2154, in call
                  *cdata["args"], **cdata["kwargs"]
                File "c:\salt\bin\lib\site-packages\salt-3002.1-py3.7.egg\salt\loader.py", line 2188, in wrapper
                  return f(*args, **kwargs)
                File "c:\salt\bin\lib\site-packages\salt-3002.1-py3.7.egg\salt\states\file.py", line 7127, in touch
                  ret["result"] = __salt__["file.touch"](name, atime, mtime)
                File "c:\salt\bin\lib\site-packages\salt-3002.1-py3.7.egg\salt\modules\file.py", line 3563, in touch
                  raise CommandExecutionError(exc.strerror)
              salt.exceptions.CommandExecutionError: Permission denied
     Started: 16:41:26.078114
    Duration: 46.86 ms
     Changes:

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    1
------------
Total states run:     2
Total run time: 171.874 ms
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[DEBUG   ] Closing AsyncZeroMQReqChannel instance

C:\Windows\system32>
```

</details>

*Output if folder already exists*:
<details><summary>salt-call -l debug state.apply brokendir</summary>

```
C:\Windows\system32>salt-call -l debug state.apply brokendir
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Including configuration from 'c:\salt\conf\minion.d\_schedule.conf'
[DEBUG   ] Reading configuration from c:\salt\conf\minion.d\_schedule.conf
[DEBUG   ] Using cached minion ID from c:\salt\conf\minion_id: WIN-LCADMNSTK2H.user.boreus.de
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Including configuration from 'c:\salt\conf\minion.d\_schedule.conf'
[DEBUG   ] Reading configuration from c:\salt\conf\minion.d\_schedule.conf
[ERROR   ] Failed to decode stderr from command C:\Windows\System32\Wbem\wmic.EXE /namespace:\\root\microsoft\windows\storage path MSFT_PhysicalDisk get DeviceID,MediaType /format:table, non-decodable characters have been replaced
[DEBUG   ] Connecting to master. Attempt 1 (infinite attempts)
[DEBUG   ] Master URI: tcp://10.114.100.250:4506
[DEBUG   ] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'WIN-LCADMNSTK2H.user.boreus.de', 'tcp://10.114.100.250:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (2458)
[DEBUG   ] Setting zmq_reconnect_ivl to '2458ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'WIN-LCADMNSTK2H.user.boreus.de', 'tcp://10.114.100.250:4506', 'clear')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://10.114.100.250:4506
[DEBUG   ] Trying to connect to: tcp://10.114.100.250:4506
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] salt.crypt._get_key_with_evict: Loading private key
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[DEBUG   ] Connecting the Minion to the Master publish port, using the URI: tcp://10.114.100.250:4505
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
[DEBUG   ] Determining pillar cache
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'WIN-LCADMNSTK2H.user.boreus.de', 'tcp://10.114.100.250:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'WIN-LCADMNSTK2H.user.boreus.de', 'tcp://10.114.100.250:4506')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://10.114.100.250:4506
[DEBUG   ] Trying to connect to: tcp://10.114.100.250:4506
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded state.apply
[DEBUG   ] LazyLoaded direct_call.execute
[DEBUG   ] LazyLoaded saltutil.is_running
[DEBUG   ] LazyLoaded grains.get
[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'WIN-LCADMNSTK2H.user.boreus.de', 'tcp://10.114.100.250:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'WIN-LCADMNSTK2H.user.boreus.de', 'tcp://10.114.100.250:4506')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://10.114.100.250:4506
[DEBUG   ] Trying to connect to: tcp://10.114.100.250:4506
[DEBUG   ] Gathering pillar data for state run
[DEBUG   ] Finished gathering pillar data for state run
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] In saltenv 'base', looking at rel_path 'brokendir.sls' to resolve 'salt://brokendir.sls'
[DEBUG   ] In saltenv 'base', ** considering ** path 'c:\salt\var\cache\salt\minion\files\base\brokendir.sls' to resolve 'salt://brokendir.sls'
[DEBUG   ] compile template: c:\salt\var\cache\salt\minion\files\base\brokendir.sls
[DEBUG   ] Jinja search path: ['c:\\salt\\var\\cache\\salt\\minion\\files\\base']
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'WIN-LCADMNSTK2H.user.boreus.de', 'tcp://10.114.100.250:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'WIN-LCADMNSTK2H.user.boreus.de', 'tcp://10.114.100.250:4506')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://10.114.100.250:4506
[DEBUG   ] Trying to connect to: tcp://10.114.100.250:4506
[PROFILE ] Time (in seconds) to render 'c:\salt\var\cache\salt\minion\files\base\brokendir.sls' using 'jinja' renderer: 1.093756914138794
[DEBUG   ] Rendered data from file: c:\salt\var\cache\salt\minion\files\base\brokendir.sls:
C:/brokendir:
    file.directory:
        - win_owner: Administrator
        - win_perms:
          SYSTEM:
            perms: full_control
          Administrator:
            perms: full_control
        - win_deny_perms: []
        - win_perms_reset: yes
        - win_inheritance: no

C:/brokendir/test.txt:
    file.touch:
        - require:
          - file: C:/brokendir

[DEBUG   ] Results of YAML rendering:
OrderedDict([('C:/brokendir', OrderedDict([('file.directory', [OrderedDict([('win_owner', 'Administrator')]), OrderedDict([('win_perms', None), ('SYSTEM', OrderedDict([('perms', 'full_control')])), ('Administrator', OrderedDict([('perms', 'full_control')]))]), OrderedDict([('win_deny_perms', [])]), OrderedDict([('win_perms_reset', True)]), OrderedDict([('win_inheritance', False)])])])), ('C:/brokendir/test.txt', OrderedDict([('file.touch', [OrderedDict([('require', [OrderedDict([('file', 'C:/brokendir')])])])])]))])
[PROFILE ] Time (in seconds) to render 'c:\salt\var\cache\salt\minion\files\base\brokendir.sls' using 'yaml' renderer: 0.21875405311584473
[DEBUG   ] LazyLoaded config.option
[DEBUG   ] LazyLoaded file.directory
[INFO    ] Running state [C:/brokendir] at time 16:58:05.205313
[INFO    ] Executing state file.directory for [C:/brokendir]
[DEBUG   ] An exception occurred in this state: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt-3002.1-py3.7.egg\salt\state.py", line 2154, in call
    *cdata["args"], **cdata["kwargs"]
  File "c:\salt\bin\lib\site-packages\salt-3002.1-py3.7.egg\salt\loader.py", line 2188, in wrapper
    return f(*args, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt-3002.1-py3.7.egg\salt\states\file.py", line 3739, in directory
    win_perms_reset=win_perms_reset,
  File "c:\salt\bin\lib\site-packages\salt-3002.1-py3.7.egg\salt\states\file.py", line 951, in _check_directory_win
    if user_name not in win_perms:
TypeError: argument of type 'NoneType' is not iterable
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt-3002.1-py3.7.egg\salt\state.py", line 2154, in call
    *cdata["args"], **cdata["kwargs"]
  File "c:\salt\bin\lib\site-packages\salt-3002.1-py3.7.egg\salt\loader.py", line 2188, in wrapper
    return f(*args, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt-3002.1-py3.7.egg\salt\states\file.py", line 3739, in directory
    win_perms_reset=win_perms_reset,
  File "c:\salt\bin\lib\site-packages\salt-3002.1-py3.7.egg\salt\states\file.py", line 951, in _check_directory_win
    if user_name not in win_perms:
TypeError: argument of type 'NoneType' is not iterable

[INFO    ] Completed state [C:/brokendir] at time 16:58:06.080329 (duration_in_ms=875.016)
[DEBUG   ] File c:\salt\var\cache\salt\minion\accumulator\1679094220104 does not exist, no need to cleanup
[DEBUG   ] LazyLoaded cmd.run
[INFO    ] Executing command ['attrib', '-R', 'c:\\salt\\var\\cache\\salt\\minion\\sls.p'] in directory 'C:\Users\Administrator'
[DEBUG   ] output:
[DEBUG   ] LazyLoaded state.check_result
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('c:\\salt\\conf\\pki\\minion', 'WIN-LCADMNSTK2H.user.boreus.de', 'tcp://10.114.100.250:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('c:\\salt\\conf\\pki\\minion', 'WIN-LCADMNSTK2H.user.boreus.de', 'tcp://10.114.100.250:4506')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://10.114.100.250:4506
[DEBUG   ] Trying to connect to: tcp://10.114.100.250:4506
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[DEBUG   ] LazyLoaded highstate.output
local:
----------
          ID: C:/brokendir
    Function: file.directory
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "c:\salt\bin\lib\site-packages\salt-3002.1-py3.7.egg\salt\state.py", line 2154, in call
                  *cdata["args"], **cdata["kwargs"]
                File "c:\salt\bin\lib\site-packages\salt-3002.1-py3.7.egg\salt\loader.py", line 2188, in wrapper
                  return f(*args, **kwargs)
                File "c:\salt\bin\lib\site-packages\salt-3002.1-py3.7.egg\salt\states\file.py", line 3739, in directory
                  win_perms_reset=win_perms_reset,
                File "c:\salt\bin\lib\site-packages\salt-3002.1-py3.7.egg\salt\states\file.py", line 951, in _check_directory_win
                  if user_name not in win_perms:
              TypeError: argument of type 'NoneType' is not iterable
     Started: 16:58:05.205313
    Duration: 875.016 ms
     Changes:
----------
          ID: C:/brokendir/test.txt
    Function: file.touch
      Result: False
     Comment: One or more requisite failed: brokendir.C:/brokendir
     Started: 16:58:06.283442
    Duration: 0.0 ms
     Changes:

Summary for local
------------
Succeeded: 0
Failed:    2
------------
Total states run:     2
Total run time: 875.016 ms
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
```

</details>

**Expected behavior**
Inheritance is removed and the above mentioned permissions are applied so only those permissions apply (in this order).

**Screenshots**

The below screenshot is after applying the above state, if the folder did not exist before.

![Screenshot of the security details of C:\brokendir. No user or group as any permissions.](https://user-images.githubusercontent.com/5983372/98832894-4d14af80-2435-11eb-84e3-8b6a05ef00d6.png)

The screenshot is in German, the text in the field below "Gruppen- oder Benutzernamen" (Group or usernames) can be translated to "For this object neither groups nor users have the required access rights. The owner can assign permissions".

Listing the permissions with `icacls.exe` gives an empty result, too:

```
C:\Windows\system32>icacls.exe C:\brokendir
C:\brokendir
1 Dateien erfolgreich verarbeitet, bei 0 Dateien ist ein Verarbeitungsfehler aufgetreten.
```

**Versions Report**
<details><summary>salt-minion --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
C:\Windows\system32>salt-minion --versions-report
Salt Version:
           Salt: 3002.1

Dependency Versions:
           cffi: 1.12.2
       cherrypy: 17.4.1
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.10
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 1.0.0
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: Not Installed
   pycryptodome: 3.9.8
         pygit2: Not Installed
         Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
   python-gnupg: 0.4.4
         PyYAML: 5.3.1
          PyZMQ: 18.0.1
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2016Server
         system: Windows
        version: 2016Server 10.0.14393 SP0
```
</details>

**Additional context**

**Comment by twangboy** [comment]
I think the problem here is the indentation on the `win_perms`. Should be this instead:
```
C:/brokendir:
    file.directory:
        - win_owner: Administrator
        - win_perms:
          SYSTEM:
            perms: full_control
          Administrator:
            perms: full_control
        - win_deny_perms: []
        - win_perms_reset: yes
        - win_inheritance: no
```

**Comment by Varbin** [comment]
@twangboy ... Yes. :rage: (I am an idiot, sorry for wasting your time).


In my quick test on a masterless minion, I had to apply it twice before the permissions got applied, but it worked.

```
C:\Users\Administrator.DC1>salt-call state.apply blub
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\state.py", line 2154, in call
    *cdata["args"], **cdata["kwargs"]
  File "c:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\loader.py", line 2106, in wrapper
    return f(*args, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\states\file.py", line 3795, in directory
    reset=win_perms_reset,
  File "c:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\modules\win_file.py", line 1431, in mkdir
    reset=reset,
  File "c:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\modules\win_file.py", line 1836, in set_perms
    reset=reset,
  File "c:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\utils\win_dacl.py", line 2685, in set_perms
    access_mode="grant",
  File "c:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\utils\win_dacl.py", line 2518, in _set_perms
    user_name in cur_perms["Not Inherited"]
KeyError: 'Not Inherited'

local:
----------
          ID: C:/brokendir
    Function: file.directory
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "c:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\state.py", line 2154, in call
                  *cdata["args"], **cdata["kwargs"]
                File "c:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\loader.py", line 2106, in wrapper
                  return f(*args, **kwargs)
                File "c:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\states\file.py", line 3795, in directory
                  reset=win_perms_reset,
                File "c:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\modules\win_file.py", line 1431, in mkdir
                  reset=reset,
                File "c:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\modules\win_file.py", line 1836, in set_perms
                  reset=reset,
                File "c:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\utils\win_dacl.py", line 2685, in set_perms
                  access_mode="grant",
                File "c:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\utils\win_dacl.py", line 2518, in _set_perms
                  user_name in cur_perms["Not Inherited"]
              KeyError: 'Not Inherited'
     Started: 00:01:21.881287
    Duration: 85.029 ms
     Changes:

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:  85.029 ms

C:\Users\Administrator.DC1>salt-call state.apply blub
[WARNING ] Skipped invalid cache mtime entry in c:\salt\var\cache\salt\minion\roots\mtime_map: c:\salt\srv\salt\blub.sls:1612393091.473904

local:
----------
          ID: C:/brokendir
    Function: file.directory
      Result: True
     Comment: Directory C:/brokendir updated
     Started: 00:01:59.142290
    Duration: 49.021 ms
     Changes:
              ----------
              grant_perms:
                  ----------
                  Administrator:
                      ----------
                      perms:
                          full_control
              inheritance:
                  False
              perms:
                  ----------
                  Administrator:
                      ----------
                      grant:
                          full_control
              remove_perms:
                  ----------
                  Administrators:
                      ----------
                      grant:
                          ----------
                          applies to:
                              This folder, subfolders and files
                          permissions:
                              Full control
                  CREATOR OWNER:
                      ----------
                      grant:
                          ----------
                          applies to:
                              Subfolders and files only
                          permissions:
                              - Undefined Permission: 268435456
                  Users:
                      ----------
                      grant:
                          ----------
                          applies to:
                              This folder and subfolders
                          permissions:
                              - Create files / write data

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  49.021 ms

C:\Users\Administrator.DC1>salt-call state.apply blub
[WARNING ] Skipped invalid cache mtime entry in c:\salt\var\cache\salt\minion\roots\mtime_map: c:\salt\srv\salt\blub.sls:1612393091.473904

local:
----------
          ID: C:/brokendir
    Function: file.directory
      Result: True
     Comment: The directory C:/brokendir is in the correct state
     Started: 00:02:13.935289
    Duration: 6.0 ms
     Changes:

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:   6.000 ms
```

**Comment by Rockin2** [comment]
I have to apply my file.directory states two times me too for having working permissions.

**Comment by twangboy** [comment]
@Rockin2 @Varbin I think I have addressed these stracktraces in https://github.com/saltstack/salt/pull/59442
