### ISSUE TITLE
[BUG] Event bus UnicodeDecodeError for salt/minion/*/start event

### ISSUE THREAD

**Issue by ni3mm4nd** [saltstack/salt#58998]
**Description**
Getting error while watching salt event bus and new salt/minion/*/start event is fired

**Setup**

```
SERVER-A# salt-run state.event pretty=True
```
```
SERVER-B# systemctl restart salt-minion
```

**Steps to Reproduce the behavior**
```
SERVER-A# salt-run state.event pretty=True
```
```
SERVER-B# systemctl restart salt-minion
```
```
SERVER-A# salt-run state.event pretty=True
[ERROR   ] Exception occurred in Subscriber while handling stream: 'utf-8' codec can't decode byte 0x85 in position 11: invalid start byte
Exception occurred in runner state.event: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/salt/client/mixins.py", line 397, in low
    data["return"] = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/salt/runners/state.py", line 305, in event
    node=node,
  File "/usr/local/lib/python3.6/site-packages/salt/modules/state.py", line 2477, in event
    ret = sevent.get_event(full=True, auto_reconnect=True)
  File "/usr/local/lib/python3.6/site-packages/salt/utils/event.py", line 660, in get_event
    ret = self._get_event(wait, tag, match_func, no_block)
  File "/usr/local/lib/python3.6/site-packages/salt/utils/event.py", line 561, in _get_event
    raw = self.subscriber.read_sync(timeout=wait)
  File "/usr/local/lib/python3.6/site-packages/salt/transport/ipc.py", line 726, in read_sync
    return self.io_loop.run_sync(lambda: self._read(timeout))
  File "/usr/local/lib/python3.6/site-packages/salt/ext/tornado/ioloop.py", line 459, in run_sync
    return future_cell[0].result()
  File "/usr/local/lib/python3.6/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/lib/python3.6/site-packages/salt/ext/tornado/gen.py", line 1070, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python3.6/site-packages/salt/transport/ipc.py", line 711, in _read
    raise exc_to_raise  # pylint: disable=E0702
  File "/usr/local/lib/python3.6/site-packages/salt/transport/ipc.py", line 684, in _read
    for framed_msg in self.unpacker:
  File "msgpack/_unpacker.pyx", line 528, in msgpack._cmsgpack.Unpacker.__next__
  File "msgpack/_unpacker.pyx", line 459, in msgpack._cmsgpack.Unpacker._unpack
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x85 in position 11: invalid start byte
```

**Expected behavior**
I should obtain normal salt/minion/*/start event

**Versions Report**
Both servers are on 3000.3 versions
```
SERVER-A# salt --versions-report
Salt Version:
           Salt: 3000.3
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: 2.8.1
      docker-py: Not Installed
          gitdb: 4.0.5
      gitpython: 3.1.3
         Jinja2: 2.7.2
        libgit2: 0.26.3
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 2.7.5 (default, Apr  2 2020, 13:16:51)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
          smmap: 3.0.4
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.8.2003 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1127.10.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.8.2003 Core
 
```

**Comment by sagetherage** [comment]
@ni3mm4nd apologies for not getting to this sooner, can you also try this in the latest version of salt or at least 3000.5 and can you try this on python 3 as we are no longer supporting python 2? it does look like we may have fixed this here and will be released in soon https://github.com/saltstack/salt/pull/59260 with Aluminium

**Comment by ni3mm4nd** [comment]
@sagetherage I can confirm that it works! Thank you
