### ISSUE TITLE
[BUG] win_task.create_task_from_xml doesn't open file

### ISSUE THREAD

**Issue by aarnaud** [saltstack/salt#59035]
**Description**
xml_path in function win_task.create_task_from_xml doesn't read file
https://github.com/saltstack/salt/blob/master/salt/modules/win_task.py#L649

**Setup**
'Create Tasks':
  module.run:
  - task.create_task_from_xml:
    - name: "\\MyTestTask"
    - xml_path: "{{ salt['environ.get']('SystemDrive') }}\\MyTestTask.xml"

**Steps to Reproduce the behavior**
```
salt -G 'os:windows' task.create_task_from_xml name=MyTestTask xml_path="C:\\MyTestTask.xml"
MyWindowsMinion:
    ERROR: Unknown Failure: 0x8004131a
```

**Expected behavior**
```
MyWindowsMinion:
    True
```

Also the error code is display because, in code is wrote upercase so that doesn't match. https://github.com/saltstack/salt/blob/master/salt/modules/win_task.py#L704

**Versions Report**

```
MASTER
Salt Version:
          Salt: 3002.2
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.8.5 (default, Jul 28 2020, 12:59:40)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2
 
System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-54-generic
        system: Linux
       version: Ubuntu 20.04 focal

MINION
Salt Version:
          Salt: 3002.2

Dependency Versions:
          cffi: 1.12.2
      cherrypy: 17.4.1
      dateutil: 2.8.0
     docker-py: Not Installed
         gitdb: 2.0.5
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: 1.0.7
       msgpack: 1.0.0
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.19
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
  python-gnupg: 0.4.4
        PyYAML: 5.3.1
         PyZMQ: 18.0.1
         smmap: 2.0.5
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.1

System Versions:
          dist:
        locale: cp1252
       machine: AMD64
       release: 2019Server
        system: Windows
       version: 2019Server 10.0.17763 SP0
```
</details>

**Additional context**
```
2020-11-27 09:16:20,891 [salt.minion      :1940][ERROR   ][8968] A command in 'task.create_task_from_xml' had a problem: Unknown Failure: 0x8004131a
Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\modules\win_task.py", line 674, in create_task_from_xml
    name, xml_text, TASK_CREATE, user_name, password, logon_type
  File "<COMObject GetFolder>", line 5, in RegisterTask
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, None, '(1,2)::ERROR: incorrect document syntax', None, 0, -2147216614), None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\minion.py", line 1890, in _thread_return
    function_name, function_args, executors, opts, data
  File "c:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\minion.py", line 1846, in _execute_job_function
    return_data = self.executors[fname](opts, data, func, args, kwargs)
  File "c:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\executors\direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\modules\win_task.py", line 715, in create_task_from_xml
    raise CommandExecutionError(failure_code)
salt.exceptions.CommandExecutionError: Unknown Failure: 0x8004131a

```

**Comment by garethgreenaway** [comment]
@aarnaud Thanks for the report and the PR, would you be able to add a test to that PR?

**Comment by aarnaud** [comment]
Hi @garethgreenaway sorry but there is no test at all on this module, I can write a test just for this function. But I Don't have work time to write a full test on this module

**Comment by garethgreenaway** [comment]
@aarnaud A test for the function that needs the change would be great.

**Comment by kibi** [comment]
Hi, I've fixed this issue by implementing the previously absent functionality of reading from an XML file and fixing several other bugs in that function.
Could you please advise how to contribute it properly?

**Comment by ligzer** [comment]
@kibi It is not contributed yet?

**Comment by kibi** [comment]
No, it's not. I sent the merge request, but then no move happened.
You can find my changes here:
https://github.com/kibi/salt/commit/602753111111847a5663d1cb96869c81477e6469

**Comment by amalaguti** [comment]
@garethgreenaway Hi, can this be merged ? This function is broken and @kibi contribution seems to fix it.
