### ISSUE TITLE
[BUG] beacon error after minion restart

### ISSUE THREAD

**Issue by xpicio** [saltstack/salt#59075]
**Description**
After a minion restart (does not matter from the minion host or from master) the beacon stop working.

**Setup**
test.sls:
```
# monitor pc health
status:
  beacon.present:
   - save: True
   - interval: 30
```

**Steps to Reproduce the behavior**
Apply a simple state file:
`salt DEMO-GTW state.apply test`

The master start receiving data every 30 seconds:
```
2020-12-03 11:02:58,535 [salt.utils.event :752 ][DEBUG   ][67] Sending event: tag = salt/beacon/DEMO-GTW/status/2020-12-03T10:02:58.528428, data = ....
2020-12-03 11:03:28,525 [salt.utils.event :752 ][DEBUG   ][60] Sending event: tag = salt/beacon/DEMO-GTW/status/2020-12-03T10:03:28.529701; data = ...
2020-12-03 11:03:58,539 [salt.utils.event :752 ][DEBUG   ][62] Sending event: tag = salt/beacon/DEMO-GTW/status/2020-12-03T10:03:58.527995; data = ...
```

Connect to the DEMO-GTW minion and restart the service:
`systemctl restart salt-minion`

The master will not receive any more beacon data, and the minion start lo this error every second:
```
2020-12-03 04:06:39,541 [salt.minion      :2879][CRITICAL][27549] The beacon errored: 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 2877, in handle_beacons
    beacons = self.process_beacons(self.functions)
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 516, in process_beacons
    b_conf, self.opts["grains"]
  File "/usr/lib/python3/dist-packages/salt/beacons/__init__.py", line 75, in process
    b_config[mod].append({"_beacon_name": mod})
AttributeError: 'dict' object has no attribute 'append'
```

**Expected behavior**
The beacon should working even after the minion restart.

**Versions Report Master**
<details><summary>salt --versions-report</summary>

```
Salt Version:
          Salt: 3002.2

Dependency Versions:
          cffi: 1.14.3
      cherrypy: unknown
      dateutil: 2.2
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: 1.1.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.0
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.17
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: 1.4.0
        Python: 3.7.9 (default, Oct 22 2020, 05:22:26)
  python-gnupg: 0.4.4
        PyYAML: 5.3.1
         PyZMQ: 18.0.1
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.1

System Versions:
          dist: alpine 3.12.1
        locale: UTF-8
       machine: x86_64
       release: 4.19.114
        system: Linux
       version: Alpine Linux 3.12.1
```
</details>

**Versions Report Minion**
<details><summary>salt-minion --versions-report</summary>

```
Salt Version:
          Salt: 3002.2
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.4.7
        pygit2: Not Installed
        Python: 3.6.9 (default, Oct  8 2020, 12:12:24)
  python-gnupg: 0.4.1
        PyYAML: 3.12
         PyZMQ: 17.1.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.5
 
System Versions:
          dist: ubuntu 18.04 Bionic Beaver
        locale: UTF-8
       machine: x86_64
       release: 4.15.0-121-generic
        system: Linux
       version: Ubuntu 18.04 Bionic Beaver
```

</details>

**Comment by garethgreenaway** [comment]
@xpicio thanks for the report.  This is likely because of the issue found with the save function in the beacon module which has been fixed here, https://github.com/saltstack/salt/pull/58854
