### ISSUE TITLE
[BUG] sensehat module does not work

### ISSUE THREAD

**Issue by bensteinberg** [saltstack/salt#59125]
**Description**
The `sensehat` module always causes an exception when run on a minion with a sensehat correctly installed.

**Setup**
Attach a sensehat to a Raspberry Pi minion, then run `salt pi pkg.install sense-hat` on the master.

**Steps to Reproduce the behavior**
Run e.g. `salt pi sensehat.get_humidity`; the response is
```
pi:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/salt/minion.py", line 1890, in _thread_return
        function_name, function_args, executors, opts, data
      File "/usr/lib/python3/dist-packages/salt/minion.py", line 1846, in _execute_job_function
        return_data = self.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/python3/dist-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/modules/sensehat.py", line 264, in get_humidity
        return _sensehat.get_humidity()
    NameError: name '_sensehat' is not defined
ERROR: Minions returned with non-zero exit code
```

**Expected behavior**
The response should have been, for example:
```
pi:
    35.67671203613281
```
**Versions Report**
<details><summary>salt --versions-report</summary>

```
Salt Version:
          Salt: 3002.2
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.5
     gitpython: 2.1.11
        Jinja2: 2.10
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.7.3 (default, Jul 25 2020, 13:03:44)
  python-gnupg: 0.4.4
        PyYAML: 3.13
         PyZMQ: 17.1.2
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.1
 
System Versions:
          dist: debian 10 buster
        locale: UTF-8
       machine: x86_64
       release: 4.19.0-13-amd64
        system: Linux
       version: Debian GNU/Linux 10 buster
```
</details>

**Additional context**
The variable `_sensehat` is only getting set in `__virtual__` since https://github.com/saltstack/salt/commit/dafa820f932965c2ed3b0497b43d6a36f96fc79a -- I believe it needs to be set outside any function in the module for this to work. I have a one-line fix to do so, but I want to make sure it's sensible when the `sense-hat` package isn't installed and/or the hardware isn't present.

**Comment by dwoz** [comment]
No repro. `salt/modules/sensehat.py` was fixed on 3006.x by [b9be2dec1b3](https://github.com/saltstack/salt/commit/b9be2dec1b33a654da7cb73e39a5b35ff78fef57) (`global _sensehat` added in `__virtual__`); loading the module and calling `get_humidity()` no longer raises `NameError`. The module was removed from 3007.x+ in [dc526dc2b17](https://github.com/saltstack/salt/commit/dc526dc2b17660059ca19f2d486cabeba54d021a) (community-extension purge). Closing.
