### ISSUE TITLE
[BUG] The setting of auth_tries is lost and set to 3 when going offline

### ISSUE THREAD

**Issue by markuskramerIgitt** [saltstack/salt#59174]
**Description**

The setting of `auth_tries` is lost and set to 3 when going offline

**Setup**
Write into your minion config
```
auth_timeout: 60
auth_tries: 60
ping_interval: 10
```

**Steps to Reproduce the behavior**

Stop the minion

Go Offline

Start the minion

Find in the log:
- auth_timeout: 60
- auth_tries: 60

```
2020-12-19 13:44:49,574 [salt.minion      :1089][ERROR   ][12596] Minion unable to successfully connect to a Salt Master.
2020-12-19 13:44:53,224 [salt.transport.zeromq:1363][DEBUG   ][12596] SaltReqTimeoutError, retrying. (1/60)
2020-12-19 13:45:53,226 [salt.transport.zeromq:1363][DEBUG   ][12596] SaltReqTimeoutError, retrying. (2/60)
2020-12-19 13:46:53,240 [salt.transport.zeromq:1363][DEBUG   ][12596] SaltReqTimeoutError, retrying. (3/60)
```

Go Online

Perform  test.version from the master

Find in the log:

```
2020-12-19 16:24:59,471 [salt.minion      :1671][INFO    ][14724] User root Executing command test.version with jid 20201219172043985731
```

Go Offline again

Wait up to 10 minutes

Find in the log:
- auth_timeout: 60
- auth_tries: 3 **wrong should be 60**

```
2020-12-19 15:18:31,059 [salt.transport.zeromq:1363][DEBUG   ][12596] SaltReqTimeoutError, retrying. (1/3)
2020-12-19 15:19:31,063 [salt.transport.zeromq:1363][DEBUG   ][12596] SaltReqTimeoutError, retrying. (2/3)
2020-12-19 15:20:31,075 [salt.transport.zeromq:1363][DEBUG   ][12596] SaltReqTimeoutError, retrying. (3/3)
```

**Expected behavior**

``` 
2020-12-19 15:18:31,059 [salt.transport.zeromq:1363][DEBUG   ][12596] SaltReqTimeoutError, retrying. (1/60)
```

**Versions Report**
<details><summary>salt --versions-report</summary> 

```
Salt Version:
          Salt: 3002.2

Dependency Versions:
          cffi: 1.12.2
      cherrypy: 17.4.1
      dateutil: 2.8.0
     docker-py: Not Installed
         gitdb: 2.0.5
     gitpython: 2.1.10
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: 1.0.7
       msgpack: 1.0.0
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.19
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
  python-gnupg: 0.4.4
        PyYAML: 5.3.1
         PyZMQ: 18.0.1
         smmap: 2.0.5
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.1

System Versions:
          dist:
        locale: cp1252
       machine: AMD64
       release: 10
        system: Windows
       version: 10 10.0.18362 SP0

```
</details>

**Additional context**

The consecutive of the log is related to issue https://github.com/saltstack/salt/issues/59064

```
2020-12-19 15:21:31,085 [salt.transport.zeromq:1330][DEBUG   ][12596] Re-init ZMQ socket: Message timed out
2020-12-19 15:21:31,085 [salt.transport.zeromq:1302][DEBUG   ][12596] Trying to connect to: tcp://2.148.96.188:4506
2020-12-19 15:21:31,085 [salt.transport.zeromq:291 ][DEBUG   ][12596] Closing AsyncZeroMQReqChannel instance
2020-12-19 15:21:31,085 [tornado.application:640 ][ERROR   ][12596] Exception in callback functools.partial(<function wrap.<locals>.wrapped at 0x0000011D54AA7B88>, <salt.ext.tornado.concurrent.Future object at 0x0000011D376F2848>)
Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\ext\tornado\ioloop.py", line 606, in _run_callback
    ret = callback()
  File "c:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\ext\tornado\stack_context.py", line 346, in wrapped
    raise_exc_info(exc)
  File "<string>", line 4, in raise_exc_info
  File "c:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\ext\tornado\stack_context.py", line 317, in wrapped
    ret = fn(*args, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\ext\tornado\gen.py", line 291, in <lambda>
    future, lambda future: callback(future.result()))
  File "c:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\ext\tornado\concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "c:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\ext\tornado\gen.py", line 1064, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\minion.py", line 1587, in _send_req_async
    ret = yield channel.send(load, timeout=timeout)
  File "c:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\ext\tornado\gen.py", line 1056, in run
    value = future.result()
  File "c:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\ext\tornado\concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "c:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\ext\tornado\gen.py", line 1064, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\transport\zeromq.py", line 447, in send
    load, tries=tries, timeout=timeout, raw=raw
  File "c:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\ext\tornado\gen.py", line 1056, in run
    value = future.result()
  File "c:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\ext\tornado\concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "c:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\ext\tornado\gen.py", line 1064, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\transport\zeromq.py", line 416, in _crypted_transfer
    ret = yield _do_transfer()
  File "c:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\ext\tornado\gen.py", line 1056, in run
    value = future.result()
  File "c:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\ext\tornado\concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "c:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\ext\tornado\gen.py", line 1064, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\transport\zeromq.py", line 399, in _do_transfer
    tries=tries,
  File "c:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\ext\tornado\gen.py", line 1056, in run
    value = future.result()
  File "c:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\ext\tornado\concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
salt.exceptions.SaltReqTimeoutError: Message timed out
```

**Comment by markuskramerIgitt** [comment]
@sagetherage  you could link PR  https://github.com/saltstack/salt/pull/59178 to this issue

**Comment by sagetherage** [comment]
> @sagetherage you could link PR #59178 to this issue

once it is out of WIP status I can :)
