### ISSUE TITLE
[BUG] shadow.set_password "a bytes-like object is required, not 'str'."

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#59180]
**Description**
Looks like there is some str vs bytes issues with the shadow.set_password module, which is used by user.present.

**Setup**
I already tracked it down to the module, so I can trigger is without a state.

```
[root@illumos]# salt-call shadow.set_password sjorge $5$unAsNuUI$3VOtsbWOobzp9Bia//PzFXWC3pb09t6IiQszQqF9YO3

Passed invalid arguments: a bytes-like object is required, not 'str'.

Usage:

    Set the password for a named user. The password must be a properly defined
    hash, the password hash can be generated with this command:
    ``openssl passwd -1 <plaintext password>``

    CLI Example:

    .. code-block:: bash

        salt '*' shadow.set_password root $1$UYCIxa628.9qXjpQCjM4a..

```

**Steps to Reproduce the behavior**
Do a call to shadow.set_password, seems to work fine when using python 2 but broken on python 3.7

**Expected behavior**
Update to /etc/shadows to happen.

**Screenshots**
n/a

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3002.2

Dependency Versions:
          cffi: 1.14.4
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.2
       libgit2: 1.1.0
      M2Crypto: 0.36.0
          Mako: 1.1.3
       msgpack: 1.0.0
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: 3.9.9
  pycryptodome: 3.9.9
        pygit2: 1.4.0
        Python: 3.7.9 (default, Dec 12 2020, 18:03:07)
  python-gnupg: 0.4.6
        PyYAML: 5.3.1
         PyZMQ: 19.0.2
         smmap: 3.0.4
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist: pkgsrc 5.11
        locale: utf-8
       machine: i86pc
       release: 5.11
        system: SunOS
       version: release: trunk 5.11
```
</details>

**Additional context**

**Comment by sjorge** [comment]
```
             An exception occurred in this state: Traceback (most recent call last):
                File "/opt/salt/lib/python3.7/site-packages/salt/state.py", line 2154, in call
                  *cdata["args"], **cdata["kwargs"]
                File "/opt/salt/lib/python3.7/site-packages/salt/loader.py", line 2106, in wrapper
                  return f(*args, **kwargs)
                File "/opt/salt/lib/python3.7/site-packages/salt/states/user.py", line 660, in present
                  __salt__["shadow.set_password"](name, password)
                File "/opt/salt/lib/python3.7/site-packages/salt/modules/solaris_shadow.py", line 296, in set_password
                  comps = line.strip().split(":")
              TypeError: a bytes-like object is required, not 'str'
```

**Comment by dmurphy18** [comment]
@sjorge Curious was this Solaris 11.3 or 11.4 that you are running on, trying to gauge support for 11.3

**Comment by sjorge** [comment]
Seen it on both:

OmniOS r151036-a13510b579
SmartOS joyent_20210119T081805Z (base-64-lts image)

Both are using python 3.7 now.

**Comment by dmurphy18** [comment]
@sjorge Have a salt solution in development for Solaris 11.4 but fails on 11.3 and 11.3 drops out of Premium support at the end of January, working on 11.3 solution since bet there is still quite a lot of it still around. no timeline for release since 11.3 is being very difficult.  Thanks for the info.
