### ISSUE TITLE
[BUG] Cannot Render configuration file

### ISSUE THREAD

**Issue by macejko8** [saltstack/salt#59224]
**Description**
I have an issue with rendering the configuration template via salt

**Setup**
I have been following salt documentation https://docs.saltstack.com/en/master/topics/network_automation/index.html#cross-platform-configuration-management-example-ntp

So I created the same SLS files and Jinja template

**Steps to Reproduce the behavior**
After running the command sudo salt router2 state.sls router.ntp ..... I see the following output
```
router2:
    Data failed to compile:
----------
    Pillar failed to render with the following messages:
----------
    Rendering SLS 'ntp' failed. Please see master log for details.
ERROR: Minions returned with non-zero exit code
```

and this is from master log file:
```
2021-01-05 07:16:50,087 [salt.utils.process:670 ][ERROR   ][16720] An un-handled exception from the multiprocessing process 'Maintenance-10' was caught:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/process.py", line 663, in _run
    return self._original_run()
  File "/usr/lib/python3/dist-packages/salt/master.py", line 238, in run
    salt.daemons.masterapi.clean_old_jobs(self.opts)
  File "/usr/lib/python3/dist-packages/salt/daemons/masterapi.py", line 203, in clean_old_jobs
    mminion.returners[fstr]()
  File "/usr/lib/python3/dist-packages/salt/returners/local_cache.py", line 426, in clean_old_jobs
    shutil.rmtree(t_path)
  File "/usr/lib/python3.6/shutil.py", line 486, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.6/shutil.py", line 424, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.6/shutil.py", line 444, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.6/shutil.py", line 442, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: '.load.p'
```

**Comment by sagetherage** [comment]
@cmcmarrow let me know if you are not able to triage this issue this week and I will get it reassigned for triage, thank you!

**Comment by sagetherage** [comment]
@macejko8 can you send your sanitized state file, please? thank you!

**Comment by garethgreenaway** [comment]
@macejko8 Following up on this one, can you provide the sanitized contents of your state file so we can see what is potentially causing the issue?  Thanks!

**Comment by garethgreenaway** [comment]
Closing this one out due to lack of activity.  If the problem persists please feel free to reopen this issue or open a new one.
