### ISSUE TITLE
[BUG]Salt-api usgi | rest_cherry

### ISSUE THREAD

**Issue by zloyded** [saltstack/salt#59272]
**Description**
``` 
127.0.0.1 - - [12/Jan/2021 03:11:57] "POST / HTTP/1.1" 500 0
Traceback (most recent call last):
  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 266, in write
    "write() argument must be a bytes instance"
AssertionError: write() argument must be a bytes instance
127.0.0.1 - - [12/Jan/2021 03:11:57] "POST / HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 33872)
Traceback (most recent call last):
  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 266, in write
    "write() argument must be a bytes instance"
AssertionError: write() argument must be a bytes instance

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 141, in run
    self.handle_error()
  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 368, in handle_error
    self.finish_response()
  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/socketserver.py", line 320, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib64/python3.6/socketserver.py", line 351, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/usr/lib64/python3.6/wsgiref/simple_server.py", line 133, in handle
    handler.run(self.server.get_app())
  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 144, in run
    self.close()
  File "/usr/lib64/python3.6/wsgiref/simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
```

**Setup**
```
rest_wsgi:
  debug: True
  port: 8001

rest_cherrypy:
  debug: True
  disable_ssl: True
  port: 8002
```

**Steps to Reproduce the behavior**
enable salt-api or cherry with epam: pam and try do login to cherrypy or test.ping to wsgi

**Expected behavior**

**Versions Report**
```
Salt Version:
          Salt: 3002.2

Dependency Versions:
          cffi: 1.11.5
      cherrypy: 18.4.0
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: 0.26.8
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.14
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: 0.26.4
        Python: 3.6.8 (default, Aug 24 2020, 17:57:11)
  python-gnupg: Not Installed
        PyYAML: 3.12
         PyZMQ: 19.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.3

System Versions:
          dist: centos 8
        locale: UTF-8
       machine: x86_64
       release: 4.18.0-240.1.1.el8_3.x86_64
        system: Linux
       version: CentOS Linux 
```

**Comment by zloyded** [comment]
> @zloyded Thanks for the report. Can you provide the versions wsgi and cherrypy that you have installed?
```python3-cherrypy.noarch             18.4.0-1.el8 ```
sure, in version report =)

**Comment by zloyded** [comment]
Good! I found a solution! I manage user passwords for API encrypted with gpg key.
In / etc / shadow, the password hash was incorrect because the hash_password parameter was set to False.
it is very difficult to debug and look for a problem with one short message when the TRACE logging mode is enabled. Add a little more verbose output.

This does not override wsgi api issues


``` 
[TRACE   ] Inserted key into loop_instance_map id 139695603149792 for key ('/etc/salt/pki/master', 'salt1_master', 'tcp://IP:4506', 'clear') and process 1078800
[TRACE   ] IPCClient: Connecting to socket: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[TRACE   ] func get_cli_event_returns()
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/6a/7c23220251cbf0466ada9c42820f1f2feb46e2fbe4afeba24afa25b1ad9f46/.minions.p
[DEBUG   ] get_iter_returns for jid 20210112210125795034 sent to {'salt1'} will timeout at 00:01:35.815344
[TRACE   ] Get event. tag: salt/job/20210112210125795034
[TRACE   ] _get_event() waited 0 seconds and received nothing
[TRACE   ] Get event. tag: salt/job/20210112210125795034
[TRACE   ] get_event() received = {'data': {'jid': '20210112210125795034', 'tgt_type': 'glob', 'tgt': 'salt1', 'user': 'saltmaster', 'fun': 'test.ping', 'arg': [], 'minions': ['salt1'], 'missing': [], '_stamp': '2021-01-12T21:01:25.796103'}, 'tag': 'salt/job/20210112210125795034/new'}
[TRACE   ] Get event. tag: salt/job/20210112210125795034
[TRACE   ] get_event() received = {'data': {'cmd': '_return', 'id': 'salt1', 'success': True, 'return': True, 'retcode': 0, 'jid': '20210112210125795034', 'fun': 'test.ping', 'fun_args': [], '_stamp': '2021-01-12T21:01:25.901249'}, 'tag': 'salt/job/20210112210125795034/ret/salt1'}
[DEBUG   ] jid 20210112210125795034 return from salt1
[DEBUG   ] return event: {'salt1': {'ret': True, 'retcode': 0, 'jid': '20210112210125795034'}}
[TRACE   ] Get event. tag: salt/job/20210112210125795034
[TRACE   ] _get_event() waited 0 seconds and received nothing
[DEBUG   ] jid 20210112210125795034 found all minions {'salt1'}
[DEBUG   ] Closing IPCMessageSubscriber instance
127.0.0.1 - - [13/Jan/2021 00:01:26] "POST / HTTP/1.1" 200 0
Traceback (most recent call last):
  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 266, in write
    "write() argument must be a bytes instance"
AssertionError: write() argument must be a bytes instance
127.0.0.1 - - [13/Jan/2021 00:01:26] "POST / HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 39456)
Traceback (most recent call last):
  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 266, in write
    "write() argument must be a bytes instance"
AssertionError: write() argument must be a bytes instance

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 141, in run
    self.handle_error()
  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 368, in handle_error
    self.finish_response()
  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/socketserver.py", line 320, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib64/python3.6/socketserver.py", line 351, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/usr/lib64/python3.6/wsgiref/simple_server.py", line 133, in handle
    handler.run(self.server.get_app())
  File "/usr/lib64/python3.6/wsgiref/handlers.py", line 144, in run
    self.close()
  File "/usr/lib64/python3.6/wsgiref/simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
```
that all for one event:
```curl http://127.0.01:8001 \
  -H 'Content-Type: application/json'\
  -d '[{"username":"saltapiuser","password":"PSSWD","eauth":"pam", "client":"local","tgt":"salt1","fun":"test.ping"}]'
  ```
I have no idea why.
### My acl config:
```
external_auth:
  pam:
    saltmaster:
      - '*':
        - test.*
    saltapi:
      - '*':
        - .*

publisher_acl:
  saltapi:
    - .*
  saltmaster:
    - .*
```

**Comment by zloyded** [comment]
hello?
