### ISSUE TITLE
[BUG] in 3002.2 minions that have autosign enabled fail to render templates

### ISSUE THREAD

**Issue by bgdnlp** [saltstack/salt#59294]
**Description**
I'm using autosign grains to allow new minions to register themselves on the master, as described here: https://docs.saltstack.com/en/latest/topics/tutorials/autoaccept_grains.html#tutorial-autoaccept-grains

On the minion I have the grain set up in minion config (/usr/local/etc/salt/minion.d/autosign.conf) like this:

```
autosign_grains:
  - autosign_key
grains:
  autosign_key: ===secret-key-here===
```

This works up to Salt version 3002. However, in 3002.2 when the minion STARTS I get errors like these in the master log file:
```
2021-01-14 09:45:31,109 [salt.transport.mixins.auth                                         :197 ][INFO    ][7982] Authentication request from mymnion-id-here
2021-01-14 09:45:31,111 [salt.transport.mixins.auth                                         :434 ][INFO    ][7982] Authentication accepted from mymnion-id-here
2021-01-14 09:45:31,491 [salt.utils.templates                                               :273 ][ERROR   ][7981] Rendering exception occurred
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/salt/utils/templates.py", line 498, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'os_family'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/salt/utils/templates.py", line 260, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/local/lib/python3.7/site-packages/salt/utils/templates.py", line 505, in render_jinja_tmpl
    raise SaltRenderError("Jinja variable {}{}".format(exc, out), buf=tmplstr)
salt.exceptions.SaltRenderError: Jinja variable 'dict object' has no attribute 'os_family'
2021-01-14 09:45:31,491 [salt.pillar                                                        :888 ][CRITICAL][7981] Rendering SLS 'common' failed, render error:                                                                                                      [1049/9172]
Jinja variable 'dict object' has no attribute 'os_family'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/salt/utils/templates.py", line 498, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'os_family'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/salt/pillar/__init__.py", line 884, in render_pstate
    **defaults
  File "/usr/local/lib/python3.7/site-packages/salt/template.py", line 101, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/usr/local/lib/python3.7/site-packages/salt/renderers/jinja.py", line 79, in render
    **kws
  File "/usr/local/lib/python3.7/site-packages/salt/utils/templates.py", line 260, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/local/lib/python3.7/site-packages/salt/utils/templates.py", line 505, in render_jinja_tmpl
    raise SaltRenderError("Jinja variable {}{}".format(exc, out), buf=tmplstr)
salt.exceptions.SaltRenderError: Jinja variable 'dict object' has no attribute 'os_family'
```
and so on.

The stdout on the master when running state.apply prints:
```
etc/salt » sudo salt mymnion-id-here state.apply
mymnion-id-here:
    Data failed to compile:
----------
    Pillar failed to render with the following messages:
----------
    Rendering SLS 'common' failed. Please see master log for details.
(... and so on for other SLS files)
```

I'm on FreeBSD. Tried both FreeBSD 12.2 and FreeBSD 12.1, same thing.

Running `sudo salt mymnion-id-here grains.items` on master reports the os_family properly:
```
os:
    FreeBSD
os_family:
    FreeBSD
osarch:
    amd64
osfinger:
    FreeBSD-12
osfullname:
    FreeBSD
osmajorrelease:
    12
osrelease:
    12.1
osrelease_info:
    - 12
    - 1
```

**Setup**
in description

**Steps to Reproduce the behavior**
in description

**Expected behavior**
Used to work up to 3002. Upgraded to 3002.2 and now it fails.

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3002.2

Dependency Versions:
          cffi: 1.14.4
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.2
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: 2.6.1
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.7.9 (default, Oct 17 2020, 01:23:59)
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 19.0.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.1

System Versions:
          dist: freebsd 12.1
        locale: UTF-8
       machine: amd64
       release: 12.1-RELEASE-p10
        system: FreeBSD
       version: FreeBSD 12.1
```
</details>

**Comment by bgdnlp** [comment]
To clarify, simply removing the autosign.conf from minion makes the state apply properly, so it looks like sending the autosign grain when the minion starts is messing something up.

**Comment by dwoz** [comment]
@bgdnlp I am not able to re-produce this issue thus far. Can you give me an example state that is trying to run?

**Comment by bgdnlp** [comment]
It's been too long. Basically my states and pillars have this kind of thing in them:

```
{% if grains['os_family'] == 'Debian' %}
local_etc_path: /etc/
{% elif grains['os_family'] == 'FreeBSD' %}
local_etc_path: /usr/local/etc/
{% endif %}
```

The above is from `./pillar/common.sls`. `local_etc_path` (and others) is then used in state files. I'm guessing that's where it failed, but I don't know for sure, it's been too long.

I'll try to upgrade and put it back the way it was, see if it still happens, but it probably won't be soon, this is prod. If you do manage to reproduce please let me know.

**Comment by Ch3LL** [comment]
I'm also not able to replicate this.

I setup the autosign grain feature. When I start the minion everything works, the Master auto accepts the key and when I run `state.apply` with states calling the pillar files you shared it parses the jinja correctly.

Any other details on how to replicate this?

**Comment by Ch3LL** [comment]
bump ^

**Comment by bgdnlp** [comment]
As far as I'm concerned this can be closed as "cannot reproduce". Our infrastructure and configuration has drifted too far for me to easily go back and check if it's still there.
