### ISSUE TITLE
[BUG] Unable to parse ansible roster

### ISSUE THREAD

**Issue by imcitius** [saltstack/salt#59293]
**Description**
I'm trying to use salt-ssh with ansible roster file, as mentioned in docs [here](https://docs.saltstack.com/en/latest/ref/roster/all/salt.roster.ansible.html#module-salt.roster.ansible).
I've tried to use any type of ansible inventory file: yaml, json, ini.

salt-ssh is unable to parse inventory with following error raised:
```
(3002) [root@salt-master-ams test]# salt-ssh --roster ansible --roster-file /root/test/test2.sh -H
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
UnboundLocalError: local variable 'hosts' referenced before assignment
Traceback (most recent call last):
  File "/root/3002/bin/salt-ssh", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/root/3002/salt/scripts/salt-ssh", line 9, in <module>
    salt_ssh()
  File "/root/3002/salt/salt/scripts.py", line 479, in salt_ssh
    client.run()
  File "/root/3002/salt/salt/cli/ssh.py", line 25, in run
    ssh = salt.client.ssh.SSH(self.config)
  File "/root/3002/salt/salt/client/ssh/__init__.py", line 236, in __init__
    self.targets = self.roster.targets(self.opts["tgt"], self.tgt_type)
  File "/root/3002/salt/salt/roster/__init__.py", line 102, in targets
    targets.update(self.rosters[f_str](tgt, tgt_type))
  File "/var/cache/salt/master/extmods/roster/ansible.py", line 137, in targets
    return {host: _get_hostvars(host) for host in hosts}
UnboundLocalError: local variable 'hosts' referenced before assignment
Traceback (most recent call last):
  File "/root/3002/bin/salt-ssh", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/root/3002/salt/scripts/salt-ssh", line 9, in <module>
    salt_ssh()
  File "/root/3002/salt/salt/scripts.py", line 479, in salt_ssh
    client.run()
  File "/root/3002/salt/salt/cli/ssh.py", line 25, in run
    ssh = salt.client.ssh.SSH(self.config)
  File "/root/3002/salt/salt/client/ssh/__init__.py", line 236, in __init__
    self.targets = self.roster.targets(self.opts["tgt"], self.tgt_type)
  File "/root/3002/salt/salt/roster/__init__.py", line 102, in targets
    targets.update(self.rosters[f_str](tgt, tgt_type))
  File "/var/cache/salt/master/extmods/roster/ansible.py", line 137, in targets
    return {host: _get_hostvars(host) for host in hosts}
UnboundLocalError: local variable 'hosts' referenced before assignment
```

**Setup**
Saltfile contents:
```
salt-ssh:
  config_dir: /root/test
```

roster script file contents:
```
#!/bin/bash
echo '{
  "servers": [
    "testhost"
  ],
  "_meta": {
    "hostvars": {
      "testhost": {
        "ansible_ssh_user": "citius",
        "ansible_ssh_host": "192.168.122.190",
        "ansible_ssh_port": 22
      }
    }
  }
}'
```

<details><summary>Full execution debug log</summary>

```
(3002) [root@salt-master-ams test]# salt-ssh --roster ansible --roster-file /root/test/test2.sh -H -l all
[INFO    ] Loading Saltfile from '/root/test/Saltfile'
[DEBUG   ] Reading configuration from /root/test/Saltfile
[DEBUG   ] Missing configuration file: /root/test/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt-master-ams
[TRACE   ] The required configuration section, 'fluent_handler', was not found the in the configuration. Not loading the fluent logging handlers module.
[TRACE   ] None of the required configuration sections, 'logstash_udp_handler' and 'logstash_zmq_handler', were found in the configuration. Not loading the Logstash logging handlers module.
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] LazyLoaded ansible.targets
[DEBUG   ] LazyLoaded salt.cmd
[DEBUG   ] Called salt.cmd runner with minion function cmd.run
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/vault.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/vault.conf
[TRACE   ] 'dig' could not be found in the following search path: '['/root/3002/bin', '/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/root/bin', '/sbin', '/bin']'
[TRACE   ] 'drill' could not be found in the following search path: '['/root/3002/bin', '/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/root/bin', '/sbin', '/bin']'
[TRACE   ] 'host' could not be found in the following search path: '['/root/3002/bin', '/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/root/bin', '/sbin', '/bin']'
[TRACE   ] 'nslookup' could not be found in the following search path: '['/root/3002/bin', '/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/root/bin', '/sbin', '/bin']'
[TRACE   ] 'dig' could not be found in the following search path: '['/root/3002/bin', '/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/root/bin', '/sbin', '/bin']'
[TRACE   ] 'drill' could not be found in the following search path: '['/root/3002/bin', '/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/root/bin', '/sbin', '/bin']'
[TRACE   ] 'host' could not be found in the following search path: '['/root/3002/bin', '/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/root/bin', '/sbin', '/bin']'
[TRACE   ] 'nslookup' could not be found in the following search path: '['/root/3002/bin', '/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/root/bin', '/sbin', '/bin']'
[TRACE   ] Error loading grains.napalm: "napalm"" (/root/3002/salt/salt/grains/napalm.py) cannot be loaded: NAPALM is not installed: ``pip install napalm``
[TRACE   ] Error loading grains.nxos: No host specified and no UDS found at /tmp/nginx_local/nginx_1_be_nxapi.sock

[TRACE   ] Error loading grains.pending_reboot: 'pending_reboot' grain only available on Windows
[TRACE   ] Loading core.append_domain grain
[TRACE   ] Loading core.cwd grain
[TRACE   ] Loading core.default_gateway grain
[TRACE   ] Loading core.dns grain
[TRACE   ] Loading core.fqdns grain
[DEBUG   ] Elapsed time getting FQDNs: 0.11398649215698242 seconds
[TRACE   ] Loading core.get_machine_id grain
[TRACE   ] Loading core.get_master grain
[TRACE   ] Loading core.get_server_id grain
[TRACE   ] Loading core.hostname grain
[TRACE   ] Loading core.hwaddr_interfaces grain
[TRACE   ] Loading core.id_ grain
[TRACE   ] Loading core.ip4_interfaces grain
[TRACE   ] Loading core.ip6_interfaces grain
[TRACE   ] Loading core.ip_fqdn grain
[TRACE   ] Loading core.ip_interfaces grain
[TRACE   ] Loading core.kernelparams grain
[TRACE   ] Loading core.locale_info grain
[TRACE   ] Loading core.os_data grain
[TRACE   ] Adding selinux grains
[TRACE   ] Adding systemd grains
[TRACE   ] Adding init grain
[TRACE   ] Getting lsb_release distro information
[TRACE   ] lsb_release python bindings not available
[TRACE   ] Attempting to parse /etc/lsb-release
[TRACE   ] Failed to parse /etc/lsb-release: [Errno 2] No such file or directory: '/etc/lsb-release'
[TRACE   ] Failed to get lsb_distrib_id, trying to parse os-release
[TRACE   ] Getting OS name, release, and codename from distro id, version, codename
[TRACE   ] Loading core.path grain
[TRACE   ] Loading core.pythonexecutable grain
[TRACE   ] Loading core.pythonpath grain
[TRACE   ] Loading core.pythonversion grain
[TRACE   ] Loading core.saltpath grain
[TRACE   ] Loading core.saltversion grain
[TRACE   ] Loading core.saltversioninfo grain
[TRACE   ] Loading core.zmqversion grain
[TRACE   ] Loading disks.disks grain
[TRACE   ] Device sr0 reports itself as an HDD
[TRACE   ] Device sda reports itself as an HDD
[TRACE   ] Loading extra.config grain
[TRACE   ] Loading extra.shell grain
[TRACE   ] Loading lvm.lvm grain
[TRACE   ] Loading mdadm.mdadm grain
[TRACE   ] Loading minion_process.grains grain
[TRACE   ] Loading opts.opts grain
[TRACE   ] Loading zfs.zfs grain
[DEBUG   ] LazyLoaded zfs.is_supported
[TRACE   ] 'zfs-fuse' could not be found in the following search path: '['/root/3002/bin', '/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/root/bin', '/sbin', '/bin']'
[TRACE   ] 'zpool' could not be found in the following search path: '['/root/3002/bin', '/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/root/bin', '/sbin', '/bin']'
[TRACE   ] Loaded cmdmod as virtual cmd
[DEBUG   ] LazyLoaded cmd.run
[INFO    ] Executing command 'ansible-inventory -i /root/test/test2.sh --list' in directory '/root'
[DEBUG   ] stdout: {
    "_meta": {
        "hostvars": {
            "testhost": {
                "ansible_ssh_host": "192.168.122.190",
                "ansible_ssh_port": 22,
                "ansible_ssh_user": "citius"
            }
        }
    },
    "all": {
        "children": [
            "servers",
            "ungrouped"
        ]
    },
    "servers": {
        "hosts": [
            "testhost"
        ]
    }
}
[DEBUG   ] output: {
    "_meta": {
        "hostvars": {
            "testhost": {
                "ansible_ssh_host": "192.168.122.190",
                "ansible_ssh_port": 22,
                "ansible_ssh_user": "citius"
            }
        }
    },
    "all": {
        "children": [
            "servers",
            "ungrouped"
        ]
    },
    "servers": {
        "hosts": [
            "testhost"
        ]
    }
}
[DEBUG   ] LazyLoaded json.loads
[DEBUG   ] LazyLoaded stringutils.to_str
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
UnboundLocalError: local variable 'hosts' referenced before assignment
Traceback (most recent call last):
  File "/root/3002/bin/salt-ssh", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/root/3002/salt/scripts/salt-ssh", line 9, in <module>
    salt_ssh()
  File "/root/3002/salt/salt/scripts.py", line 479, in salt_ssh
    client.run()
  File "/root/3002/salt/salt/cli/ssh.py", line 25, in run
    ssh = salt.client.ssh.SSH(self.config)
  File "/root/3002/salt/salt/client/ssh/__init__.py", line 236, in __init__
    self.targets = self.roster.targets(self.opts["tgt"], self.tgt_type)
  File "/root/3002/salt/salt/roster/__init__.py", line 102, in targets
    targets.update(self.rosters[f_str](tgt, tgt_type))
  File "/var/cache/salt/master/extmods/roster/ansible.py", line 137, in targets
    return {host: _get_hostvars(host) for host in hosts}
UnboundLocalError: local variable 'hosts' referenced before assignment
Traceback (most recent call last):
  File "/root/3002/bin/salt-ssh", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/root/3002/salt/scripts/salt-ssh", line 9, in <module>
    salt_ssh()
  File "/root/3002/salt/salt/scripts.py", line 479, in salt_ssh
    client.run()
  File "/root/3002/salt/salt/cli/ssh.py", line 25, in run
    ssh = salt.client.ssh.SSH(self.config)
  File "/root/3002/salt/salt/client/ssh/__init__.py", line 236, in __init__
    self.targets = self.roster.targets(self.opts["tgt"], self.tgt_type)
  File "/root/3002/salt/salt/roster/__init__.py", line 102, in targets
    targets.update(self.rosters[f_str](tgt, tgt_type))
  File "/var/cache/salt/master/extmods/roster/ansible.py", line 137, in targets
    return {host: _get_hostvars(host) for host in hosts}
UnboundLocalError: local variable 'hosts' referenced before assignment
```
</details>

**Versions Report**
<details><summary>salt --versions-report</summary>

```
(3002) [root@salt-master-ams test]# salt --versions-report
Salt Version:
          Salt: 3002.2

Dependency Versions:
          cffi: 1.14.4
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.2
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: 2.6.1
  pycryptodome: 3.9.9
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 20.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.3

System Versions:
          dist: centos 7 Core
        locale: ANSI_X3.4-1968
       machine: x86_64
       release: 5.1.5-1.el7.elrepo.x86_64
        system: Linux
       version: CentOS Linux 7 Core
```
</details>

**Comment by joshiegy** [comment]
I have the same issue, more or less. Have tried both ini-format (even copied the documentations example) and yaml, neither worked.

**Comment by MKLeb** [comment]
Fixed by https://github.com/saltstack/salt/pull/64422
