### ISSUE TITLE
[BUG] salt-call --local service ends with un-handled exception on macOS Mojave

### ISSUE THREAD

**Issue by AldarisPale** [saltstack/salt#59331]
**Description**
Trying to get help locally ends with unhandled exception
```
salt-call --local service
[...]
    service.stop:
        
            Stop a launchd service.  Raises an error if the service fails to stop
[...]
                salt '*' service.stop org.cups.cupsd
            
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
KeyError: 'retcode'
Traceback (most recent call last):
  File "/opt/salt/bin/salt-call", line 11, in <module>
    load_entry_point('salt==3002.1', 'console_scripts', 'salt-call')()
  File "/opt/salt/lib/python3.7/site-packages/salt-3002.1-py3.7.egg/salt/scripts.py", line 449, in salt_call
    client.run()
  File "/opt/salt/lib/python3.7/site-packages/salt-3002.1-py3.7.egg/salt/cli/call.py", line 58, in run
    caller.run()
  File "/opt/salt/lib/python3.7/site-packages/salt-3002.1-py3.7.egg/salt/cli/caller.py", line 134, in run
    elif ret["retcode"] != salt.defaults.exitcodes.EX_OK:
KeyError: 'retcode'
Traceback (most recent call last):
  File "/opt/salt/bin/salt-call", line 11, in <module>
    load_entry_point('salt==3002.1', 'console_scripts', 'salt-call')()
  File "/opt/salt/lib/python3.7/site-packages/salt-3002.1-py3.7.egg/salt/scripts.py", line 449, in salt_call
    client.run()
  File "/opt/salt/lib/python3.7/site-packages/salt-3002.1-py3.7.egg/salt/cli/call.py", line 58, in run
    caller.run()
  File "/opt/salt/lib/python3.7/site-packages/salt-3002.1-py3.7.egg/salt/cli/caller.py", line 134, in run
    elif ret["retcode"] != salt.defaults.exitcodes.EX_OK:
KeyError: 'retcode'
```

**Setup**
Macos Mojave

**Steps to Reproduce the behavior**
See above

**Expected behavior**
There should be no exception thrown.

**Screenshots**
None

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3002.1
 
Dependency Versions:
           cffi: 1.12.2
       cherrypy: unknown
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.6
      gitpython: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 1.0.0
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: Not Installed
   pycryptodome: 3.9.8
         pygit2: Not Installed
         Python: 3.7.4 (default, Oct 26 2020, 15:51:24)
   python-gnupg: 0.4.4
         PyYAML: 5.3.1
          PyZMQ: 18.0.1
          smmap: 3.0.2
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: darwin 18.7.0 
         locale: UTF-8
        machine: x86_64
        release: 18.7.0
         system: Darwin
        version: 10.14.6 x86_64
```
</details>

**Additional context**

**Comment by garethgreenaway** [comment]
@saltstack/team-macos Any thoughts on this one?

**Comment by tuxthepenguin84** [comment]
I'm having this issue as well however I'm on Ubuntu 18.04 and 20.04 running 3003.3.
You can also reproduce the issue by running salt-call schedule
