### ISSUE TITLE
[BUG] Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'boto_ssm'

### ISSUE THREAD

**Issue by DenisBY** [saltstack/salt#59370]
**Description**
I would like to get params from AWS ssm instead of pillar. During `state.highstate` I'm getting the following error:
```
salt.exceptions.SaltRenderError: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'boto_ssm'
c:\salt\var\cache\salt\minion\files\base\tag-dm-worker-common-win-py3/files/worker.conf(1):
---
{%- set rmq_hosts = salt['boto_ssm'].get_parameter('/tag/rabbitmq/'+ grains['env_name'] +'/amqp_url_list').split('\n') -%}    <======================
```

**Setup**
WIndows 2012 R2 Standard. 
Jinja template looks like this:
```
{%- set rmq_hosts = salt['boto_ssm'].get_parameter('/tag/rabbitmq/'+ grains['env_name'] +'/amqp_url_list').split('\n') -%}
```

**Steps to Reproduce the behavior**
Install salt-minion on Windows, execute `state.highstate` for this salt-minion.

**Expected behavior**
Jinja template rendered without errors

**Versions Report**
<details><summary>salt --versions-report</summary>

```
Salt Version:
          Salt: 3002.2

Dependency Versions:
          cffi: 1.12.2
      cherrypy: 17.4.1
      dateutil: 2.8.0
     docker-py: Not Installed
         gitdb: 2.0.5
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: 1.0.7
       msgpack: 1.0.0
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.19
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
  python-gnupg: 0.4.4
        PyYAML: 5.3.1
         PyZMQ: 18.0.1
         smmap: 2.0.5
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.1

System Versions:
          dist: cygwin_nt-6.3 3.1.7
        locale: cp1252
       machine: AMD64
       release: 2012ServerR2
        system: Windows
       version: 2012ServerR2 6.3.9600 SP0
```
</details>

**Additional context**
On Linux I was able to solve it with installing both `boto3` and `boto`, but on Windows installing `boto3` breaks salt-minion as it replaces `urllib3` with version 1.26.x, however salt-minion wants `urllib3==1.24.3` and refuses to start.

**Comment by DenisBY** [comment]
Workaround is to forcefully install `urllib3==1.24.3` and ignore warnings like:
```
botocore 1.19.62 requires urllib3<1.27,>=1.25.4; python_version != "3.4", but you'll have urllib3 1.24.3 which is incompatible.
```
It seems it works.

**Comment by twangboy** [comment]
We probably need to update as many libraries as we can for Windows. I don't think that has been done for a while.

**Comment by OrangeDog** [comment]
It should also be `salt["boto_ssm.get_parameter"]`

**Comment by mbrrg** [comment]
Can confirm this works as intended on a Windows minion with version 3005.1 after installation of the boto library (```salt pip install boto```).

**Comment by lylejohnson** [comment]
I'm seeing this on Ubuntu 22.04 LTS, with Salt 3006.1. I've tried installing both the `boto3` and `boto` packages, restarting the Salt Master, etc.
```
Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/templates.py", line 476, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/opt/saltstack/salt/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 3, in top-level template code
  File "/opt/saltstack/salt/lib/python3.10/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'salt.utils.templates.AliasedLoader object' has no attribute 'boto_ssm'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/pillar/__init__.py", line 919, in render_pstate
    state = compile_template(
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/template.py", line 99, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1232, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1247, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/renderers/jinja.py", line 62, in render
    tmp_data = salt.utils.templates.JINJA(
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/templates.py", line 218, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/templates.py", line 482, in render_jinja_tmpl
    raise SaltRenderError("Jinja variable {}{}".format(exc, out), line, tmplstr)
salt.exceptions.SaltRenderError: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'boto_ssm'; line 3
```

**Comment by OrangeDog** [comment]
> I've tried installing

How did you install them? With `salt-pip`?

**Comment by lylejohnson** [comment]
> > I've tried installing
> 
> How did you install them? With `salt-pip`?

@OrangeDog Sorry, no, I've never even heard of `salt-pip`. That's a new one for me. Sounds like I need to do some Googling.

**Comment by OrangeDog** [comment]
Tagging #64291
