### ISSUE TITLE
[BUG] Salt jinja renderer ignores escape characters (')

### ISSUE THREAD

**Issue by ggiesen** [saltstack/salt#59379]
**Description**
The Salt jinja renderer seems to ignore the Jinja2 escape character ('), per https://docs.saltproject.io/en/3001/topics/jinja/index.html#escaping-jinja

**Setup**
On the salt master (with minion running):
```
cat > /tmp/test.sls<<EOF
hello: '{#'}
EOF
```

**Steps to Reproduce the behavior**
```
$ salt master slsutil.renderer /tmp/test.sls
master:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 398, in render_jinja_tmpl
        template = jinja_env.from_string(tmplstr)
      File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 941, in from_string
        return cls.from_code(self, self.compile(source), globals, None)
      File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 638, in compile
        self.handle_exception(source=source_hint)
      File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
        reraise(*rewrite_traceback_stack(source=source))
      File "/usr/local/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
        raise value.with_traceback(tb)
      File "<unknown>", line 1, in template
    jinja2.exceptions.TemplateSyntaxError: Missing end of comment tag

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/lib/python3.6/site-packages/salt/minion.py", line 1870, in _thread_return
        opts, data, func, args, kwargs
      File "/usr/lib/python3.6/site-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/lib/python3.6/site-packages/salt/modules/slsutil.py", line 182, in renderer
        **kwargs
      File "/usr/lib/python3.6/site-packages/salt/template.py", line 106, in compile_template
        ret = render(input_data, saltenv, sls, **render_kwargs)
      File "/usr/lib/python3.6/site-packages/salt/renderers/jinja.py", line 79, in render
        **kws
      File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 166, in render_tmpl
        output = render_str(tmplstr, context, tmplpath)
      File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 417, in render_jinja_tmpl
        "Jinja syntax error: {0}{1}".format(exc, out), line, tmplstr
    salt.exceptions.SaltRenderError: Jinja syntax error: Missing end of comment tag; line 1

    ---
    hello: '{#'}    <======================
    ---

```

**Expected behavior**
```
# salt master slsutil.renderer /tmp/test.sls
master: 
    ----------
    hello:
        {#}

```
**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
# salt --versions-report
Salt Version:
           Salt: 3001.4

Dependency Versions:
           cffi: 1.14.0
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.2
        libgit2: 1.0.1
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: 1.3.0
         Python: 3.6.8 (default, Aug 24 2020, 17:57:11)
   python-gnupg: 0.4.6
         PyYAML: 5.3.1
          PyZMQ: 19.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.3

System Versions:
           dist: centos 8
         locale: UTF-8
        machine: x86_64
        release: 4.18.0-193.19.1.el8_2.x86_64
         system: Linux
        version: CentOS Linux 8
```
</details>

**Comment by hemebond** [comment]
@ggiesen You have to put `'{#'` actually inside Jinja for it to be escaped by Jinja, i.e.,
```
hello: {{ '{#}' }}
```

**Comment by teizz** [comment]
@ggiesen: The `'` is not an escape character in and by itself. Rather, a literal string can be given within a Jinja statement to have whatever is inside it not be interpreted as such. Using `'` or `"` won't matter in such a case.

What you're really running into is that the default renderer is `jinja|yaml`, meaning it will first do any Jinja parsing (and falling over the fact that there is a `{#` without an accompanying `#}` regardless of what preceded it).

The proper way to do this within a `jinja|yaml` renderer would be like @hemebond states (note the quotes around the entire YAML value to prevent YAML from trying to parse it as a dictionary):
```
bash-5.1# cat << EOF > /tmp/tst.sls
hello: '{{ "{#}" }}'
EOF
bash-5.1# salt demosalt slsutil.renderer /tmp/tst.sls 
demosalt:
    ----------
    hello:
        {#}
```

The other solution would be to switch the renderer to pure YAML, forgoing the Jinja parser all together (note that the quotes are still required, without them the YAML parser will fail):
```
bash-5.1# cat << EOF > /tmp/tst.sls
#!yaml
hello: '{#}'
EOF
bash-5.1# salt demosalt slsutil.renderer /tmp/tst.sls 
demosalt:
    ----------
    hello:
        {#}
```

So, indeed not a bug and this issue should be closed.

**Comment by ggiesen** [comment]
Confirmed. It's definitely not intuitive that I have to enable jinja to escape it, but it is what it is.
