### ISSUE TITLE
[BUG] win_servermanager: KeyError: 'system.restart'

### ISSUE THREAD

**Issue by major0** [saltstack/salt#59424]
**Description**
`salt/modules/win_servermanager.py` calls `__salt__["system.restart"]` which is invalid.  The correct method appears to be `system.reboot`.

```
    Function: win_servermanager.installed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "c:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\state.py", line 2154, in call
                  *cdata["args"], **cdata["kwargs"]
                File "c:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\loader.py", line 2106, in wrapper
                  return f(*args, **kwargs)
                File "c:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\states\win_servermanager.py", line 161, in installed
                  features, recurse=recurse, restart=restart, source=source, exclude=exclude
                File "c:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\modules\win_servermanager.py", line 300, in install
                  if __salt__["system.restart"](in_seconds=True):
                File "c:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\loader.py", line 1283, in __getitem__
                  func = super().__getitem__(item)
                File "c:\salt\bin\lib\site-packages\salt-3002.2-py3.7.egg\salt\utils\lazy.py", line 108, in __getitem__
                  raise KeyError(key)
              KeyError: 'system.restart'
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3002.2
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.10.1
       libgit2: 0.28.3
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.6.1
        pygit2: 1.0.3
        Python: 3.8.5 (default, Jul 28 2020, 12:59:40)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2
 
System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: aarch64
       release: 5.4.0-1029-aws
        system: Linux
       version: Ubuntu 20.04 focal
```
</details>

**Comment by iHarshalAgarwal** [comment]
I face the same issue. Do we have a workaround for this?
