### ISSUE TITLE
New problem with pygit2 1.5.0 KeyError object not found <commit_id>

### ISSUE THREAD

**Issue by remyd1** [saltstack/salt#59489]
### Description of Issue
I have synchronization issues between a salt master server and gitfs through `pygit2` module version `1.5.0` and with saltstack `3002.2`.

Here is what I am seeing in my salt-master logs (after anonymization) :

```bash
journalctl -xn150 -f -u salt-master.service
```

```
 [ERROR   ] Exception caught while fetching gitfs remote 'ssh://git@host.domain.tld/repos/un-peu-de-sel.git': 'object not found - no match for id (3bc3ba574>
 Traceback (most recent call last):
   File "/usr/lib/python3/dist-packages/salt/utils/gitfs.py", line 2531, in fetch_remotes
     if repo.fetch():
   File "/usr/lib/python3/dist-packages/salt/utils/gitfs.py", line 820, in fetch
     return self._fetch()
   File "/usr/lib/python3/dist-packages/salt/utils/gitfs.py", line 1864, in _fetch
     fetch_results = origin.fetch(**fetch_kwargs)
   File "/usr/local/lib/python3.8/dist-packages/pygit2/remote.py", line 128, in fetch
     payload.check_error(err)
   File "/usr/local/lib/python3.8/dist-packages/pygit2/callbacks.py", line 93, in check_error
     check_error(error_code)
   File "/usr/local/lib/python3.8/dist-packages/pygit2/errors.py", line 56, in check_error
     raise KeyError(message)
 KeyError: 'object not found - no match for id (3bc3ba574e1992af38727fa67c3d6a541a2d1146)'
 [ERROR   ] Exception caught while fetching gitfs remote 'ssh://git@host.domain.tld/repos/modulefiles.git': 'object not found - no match for id (84fe4348c08ebd198>
 Traceback (most recent call last):
   File "/usr/lib/python3/dist-packages/salt/utils/gitfs.py", line 2531, in fetch_remotes
     if repo.fetch():
   File "/usr/lib/python3/dist-packages/salt/utils/gitfs.py", line 820, in fetch
     return self._fetch()
   File "/usr/lib/python3/dist-packages/salt/utils/gitfs.py", line 1864, in _fetch
     fetch_results = origin.fetch(**fetch_kwargs)
   File "/usr/local/lib/python3.8/dist-packages/pygit2/remote.py", line 128, in fetch
     payload.check_error(err)
   File "/usr/local/lib/python3.8/dist-packages/pygit2/callbacks.py", line 93, in check_error
     check_error(error_code)
   File "/usr/local/lib/python3.8/dist-packages/pygit2/errors.py", line 56, in check_error
     raise KeyError(message)
 KeyError: 'object not found - no match for id (84fe4348c08ebd198f85856077541bb5b4c97ebc)'
 [ERROR   ] Exception caught while fetching gitfs remote 'ssh://git@host.domain.tld/repos/un-peu-de-sel.git': 'object not found - no match for id (3bc3ba574>
 Traceback (most recent call last):
   File "/usr/lib/python3/dist-packages/salt/utils/gitfs.py", line 2531, in fetch_remotes
     if repo.fetch():
   File "/usr/lib/python3/dist-packages/salt/utils/gitfs.py", line 820, in fetch
     return self._fetch()
   File "/usr/lib/python3/dist-packages/salt/utils/gitfs.py", line 1864, in _fetch
     fetch_results = origin.fetch(**fetch_kwargs)
   File "/usr/local/lib/python3.8/dist-packages/pygit2/remote.py", line 128, in fetch
     payload.check_error(err)
   File "/usr/local/lib/python3.8/dist-packages/pygit2/callbacks.py", line 93, in check_error
     check_error(error_code)
   File "/usr/local/lib/python3.8/dist-packages/pygit2/errors.py", line 56, in check_error
     raise KeyError(message)
 KeyError: 'object not found - no match for id (3bc3ba574e1992af38727fa67c3d6a541a2d1146)'
 [ERROR   ] Exception caught while fetching gitfs remote 'ssh://git@host.domain.tld/repos/modulefiles.git': 'object not found - no match for id (84fe4348c08ebd198>
 Traceback (most recent call last):
   File "/usr/lib/python3/dist-packages/salt/utils/gitfs.py", line 2531, in fetch_remotes
     if repo.fetch():
   File "/usr/lib/python3/dist-packages/salt/utils/gitfs.py", line 820, in fetch
     return self._fetch()
   File "/usr/lib/python3/dist-packages/salt/utils/gitfs.py", line 1864, in _fetch
     fetch_results = origin.fetch(**fetch_kwargs)
   File "/usr/local/lib/python3.8/dist-packages/pygit2/remote.py", line 128, in fetch
     payload.check_error(err)
   File "/usr/local/lib/python3.8/dist-packages/pygit2/callbacks.py", line 93, in check_error
     check_error(error_code)
   File "/usr/local/lib/python3.8/dist-packages/pygit2/errors.py", line 56, in check_error
     raise KeyError(message)
 KeyError: 'object not found - no match for id (84fe4348c08ebd198f85856077541bb5b4c97ebc)'
```

> Switching to a recent version of gitpython solved this issue.

### Setup

My `/etc/salt/master` master configuration:
```
fileserver_backend:
  - git
gitfs_provider: gitpython
gitfs_base: master
gitfs_remotes:
  - ssh://git@host.domain.tld/repos/salt.git:
    - name: states
    - root: 'salt_states'
    - pubkey: /root/.ssh/id_rsa.pub
    - privkey: /root/.ssh/id_rsa
  - ssh://git@host.domain.tld/repos/salt.git:
    - name: reactor
    - root: 'salt_reactor'
    - pubkey: /root/.ssh/id_rsa.pub
    - privkey: /root/.ssh/id_rsa
  - ssh://git@host.domain.tld/repos/modulefiles.git:
    - name: modulefiles
    - pubkey: /root/.ssh/id_rsa.pub
    - privkey: /root/.ssh/id_rsa

ext_pillar:
  - git: 
    - master ssh://git@host.domain.tld/repos/salt.git:
      - env: base
      - name: pillar
      - root: salt_pillar
      - pubkey: /root/.ssh/id_rsa.pub
      - privkey: /root/.ssh/id_rsa
```

### Steps to Reproduce Issue

Install saltstack 3002.2 for python3, then install pygit2 1.5.0, and configure it to use a local git repository (I am using a local gitlab server with an autosign certificate. I tried to switch to a public server but I get the same error).

### Versions Report

```
Salt Version:
          Salt: 3002.2
 
Dependency Versions:
          cffi: 1.14.3
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.10.1
       libgit2: 1.1.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: 2.6.1
  pycryptodome: 3.6.1
        pygit2: 1.5.0
        Python: 3.8.5 (default, Jul 28 2020, 12:59:40)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2
 
System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-54-generic
        system: Linux
       version: Ubuntu 20.04 focal

```

**Comment by remyd1** [comment]
In fact, it seems that the result of switching to `gitpython` is working but, nevertheless, I have to restart the master, because of [this issue](https://github.com/saltstack/salt/issues/57716)...

**Comment by other-ryan** [comment]
We're seeing a similar issue but with pygit2 0.26.2. Also a little strange but it seems like not all our branches are being pulled down. We are usually able to specify `saltenv={branchname}` on the command line and test states from there but that is intermittently not working. Still investigating that issue.

```
[ERROR   ] Exception caught while fetching gitfs remote 'https://git.domain.com/scm/salt/salt.git': 'object not found - no match for id (25eb23a9fc1ec3511d8ae4d4560184c492e210e3)'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/gitfs.py", line 2531, in fetch_remotes
    if repo.fetch():
  File "/usr/lib/python3/dist-packages/salt/utils/gitfs.py", line 820, in fetch
    return self._fetch()
  File "/usr/lib/python3/dist-packages/salt/utils/gitfs.py", line 1864, in _fetch
    fetch_results = origin.fetch(**fetch_kwargs)
  File "/usr/lib/python3/dist-packages/pygit2/remote.py", line 405, in fetch
    check_error(err)
  File "/usr/lib/python3/dist-packages/pygit2/errors.py", line 55, in check_error
    raise KeyError(message)
KeyError: 'object not found - no match for id (25eb23a9fc1ec3511d8ae4d4560184c492e210e3)'
[DEBUG   ] Set update lock for gitfs remote 'https://git.domain.com/scm/salt/salt.git'
[DEBUG   ] Fetching gitfs remote 'https://git.domain.com/scm/salt/salt.git'
[ERROR   ] Error occurred fetching gitfs remote 'https://git.domain.com/scm/salt/salt.git': curl error:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/gitfs.py", line 1864, in _fetch
    fetch_results = origin.fetch(**fetch_kwargs)
  File "/usr/lib/python3/dist-packages/pygit2/remote.py", line 405, in fetch
    check_error(err)
  File "/usr/lib/python3/dist-packages/pygit2/errors.py", line 64, in check_error
    raise GitError(message)
_pygit2.GitError: curl error:

[DEBUG   ] Removed update lock for gitfs remote 'https://git.domain.com/scm/salt/salt.git'
[DEBUG   ] Set update lock for gitfs remote 'https://github.com/saltstack-formulas/salt-formula.git'
[DEBUG   ] Fetching gitfs remote 'https://github.com/saltstack-formulas/salt-formula.git'
[ERROR   ] Error occurred fetching gitfs remote 'https://github.com/saltstack-formulas/salt-formula.git': curl error:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/gitfs.py", line 1864, in _fetch
    fetch_results = origin.fetch(**fetch_kwargs)
  File "/usr/lib/python3/dist-packages/pygit2/remote.py", line 405, in fetch
    check_error(err)
  File "/usr/lib/python3/dist-packages/pygit2/errors.py", line 64, in check_error
    raise GitError(message)
_pygit2.GitError: curl error:
```
In addition to the above, we also see this in the logs at the same time:

```
DEBUG   ] Removed update lock for gitfs remote 'https://github.com/saltstack-formulas/openssh-formula.git'
[DEBUG   ] Set update lock for gitfs remote 'https://github.com/saltstack-formulas/vault-formula.git'
[DEBUG   ] Fetching gitfs remote 'https://github.com/saltstack-formulas/vault-formula.git'
[ERROR   ] Error occurred fetching gitfs remote 'https://github.com/saltstack-formulas/vault-formula.git': curl error:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/gitfs.py", line 1864, in _fetch
    fetch_results = origin.fetch(**fetch_kwargs)
  File "/usr/lib/python3/dist-packages/pygit2/remote.py", line 405, in fetch
    check_error(err)
  File "/usr/lib/python3/dist-packages/pygit2/errors.py", line 64, in check_error
    raise GitError(message)
_pygit2.GitError: curl error:

[DEBUG   ] Removed update lock for gitfs remote 'https://github.com/saltstack-formulas/vault-formula.git'
[DEBUG   ] Could not LazyLoad local_cache.prep_jid: 'local_cache.prep_jid' is not available.
[ERROR   ] Returner 'local_cache' does not support function prep_jid
[DEBUG   ] Closing IPCMessageClient instance
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
KeyError: "Returner 'local_cache' does not support function prep_jid"
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/job.py", line 75, in store_job
    mminion.returners[jidstore_fstr](False, passed_jid=load["jid"])
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1283, in __getitem__
    func = super().__getitem__(item)
  File "/usr/lib/python3/dist-packages/salt/utils/lazy.py", line 108, in __getitem__
    raise KeyError(key)
KeyError: 'local_cache.prep_jid'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/salt-run", line 11, in <module>
    load_entry_point('salt==3002.2', 'console_scripts', 'salt-run')()
  File "/usr/lib/python3/dist-packages/salt/scripts.py", line 465, in salt_run
    client.run()
  File "/usr/lib/python3/dist-packages/salt/cli/run.py", line 41, in run
    ret = runner.run()
  File "/usr/lib/python3/dist-packages/salt/runner.py", line 296, in run
    daemonize=False,
  File "/usr/lib/python3/dist-packages/salt/client/mixins.py", line 507, in _proc_function
    return self.low(fun, low, full_return=False)
  File "/usr/lib/python3/dist-packages/salt/client/mixins.py", line 434, in low
    mminion=self.mminion,
  File "/usr/lib/python3/dist-packages/salt/utils/job.py", line 79, in store_job
    raise KeyError(emsg)
KeyError: "Returner 'local_cache' does not support function prep_jid"
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/job.py", line 75, in store_job
    mminion.returners[jidstore_fstr](False, passed_jid=load["jid"])
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1283, in __getitem__
    func = super().__getitem__(item)
  File "/usr/lib/python3/dist-packages/salt/utils/lazy.py", line 108, in __getitem__
    raise KeyError(key)
KeyError: 'local_cache.prep_jid'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/salt-run", line 11, in <module>
    load_entry_point('salt==3002.2', 'console_scripts', 'salt-run')()
  File "/usr/lib/python3/dist-packages/salt/scripts.py", line 465, in salt_run
    client.run()
  File "/usr/lib/python3/dist-packages/salt/cli/run.py", line 41, in run
    ret = runner.run()
  File "/usr/lib/python3/dist-packages/salt/runner.py", line 296, in run
    daemonize=False,
  File "/usr/lib/python3/dist-packages/salt/client/mixins.py", line 507, in _proc_function
    return self.low(fun, low, full_return=False)
  File "/usr/lib/python3/dist-packages/salt/client/mixins.py", line 434, in low
    mminion=self.mminion,
  File "/usr/lib/python3/dist-packages/salt/utils/job.py", line 79, in store_job
    raise KeyError(emsg)
KeyError: "Returner 'local_cache' does not support function prep_jid"
```
## Versions Report
```
Salt Version:
          Salt: 3002.2

Dependency Versions:
          cffi: 1.14.0
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: 4.2.1
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10
       libgit2: 0.26.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: 2.6.1
  pycryptodome: 3.4.7
        pygit2: 0.26.2
        Python: 3.6.9 (default, Oct  8 2020, 12:12:24)
  python-gnupg: 0.4.1
        PyYAML: 3.12
         PyZMQ: 17.1.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.5

System Versions:
          dist: ubuntu 18.04 bionic
        locale: UTF-8
       machine: x86_64
       release: 5.4.0-1037-aws
        system: Linux
       version: Ubuntu 18.04 bionic
```

## Setup
```
top_file_merging_strategy: "same"
fileserver_backend:
  - git
gitfs_provider: "pygit2"
gitfs_remotes:
    - https://git.domain.com/scm/salt/salt.git:
      - name: salt-backend
      - root: salt
      - base: master
    - https://git.domain.com/scm/salt/salt.git:
      - name: reactor-backend
      - root: reactor
      - base: master
      - mountpoint: salt://reactor
    - https://github.com/saltstack-formulas/salt-formula.git:
      - name: salt-formula
      - base: v1.7.0
      - all_saltenvs: v1.7.0
    - https://github.com/saltstack-formulas/chrony-formula.git:
      - name: chrony-formula
      - base: v1.2.1
      - all_saltenvs: v1.2.1
    - https://github.com/saltstack-formulas/logrotate-formula.git:
      - name: logrotate-formula
      - base: v0.11.5
      - all_saltenvs: v0.11.5
    - https://github.com/saltstack-formulas/sudoers-formula.git:
      - name: sudoers-formula
      - base: v0.22.2
      - all_saltenvs: v0.22.2
    - https://github.com/saltstack-formulas/sysctl-formula.git:
      - name: sysctl-formula
      - base: v0.6.2
      - all_saltenvs: v0.6.2
    - https://github.com/saltstack-formulas/timezone-formula.git:
      - name: timezone-formula
      - base: v0.4.4
      - all_saltenvs: v0.4.4
    - https://github.com/saltstack-formulas/openssh-formula.git:
      - name: openssh-formula
      - base: v2.0.4
      - all_saltenvs: v2.0.4
    - https://github.com/saltstack-formulas/vault-formula.git:
      - name: vault-formula
      - base: v1.2.3
      - all_saltenvs: v1.2.3
ext_pillar:
  - git:
    - __env__ https://git.domain.com/scm/salt/salt.git:
      - root: pillars
git_pillar_base: "master"
git_pillar_global_lock: false
gitfs_global_lock:
  false
gitfs_saltenv_blacklist:
  - registry-sync/*
```

We install pygit2 using the apt `python3-pygit2` package which installs pygit2=0.26.2 and libgit2=0.26.0. We'll test gitpython to see if it's any better for us.

**Comment by mdschmitt** [comment]
I can report the same with python 3.7.10 and pygit2 1.6.1 (installed via pip as root) on an Amazon Linux 2 box with salt v 3003.1.  Took me forever to track down the problem and then find this bug report.  Does anyone know what's going on?
```
Jul 09 01:52:34 saltmaster salt-master[4218]: [ERROR   ] Exception caught while fetching gitfs remote 'https://github.com/saltstack-formulas/logrotate-formula.git': 'object not found - no match for id (5bd6c259e6fe53628193ae4346e6c4114338576f)'
Jul 09 01:52:34 saltmaster salt-master[4218]: Traceback (most recent call last):
Jul 09 01:52:34 saltmaster salt-master[4218]: File "/usr/lib/python3.7/site-packages/salt/utils/gitfs.py", line 2531, in fetch_remotes
Jul 09 01:52:34 saltmaster salt-master[4218]: if repo.fetch():
Jul 09 01:52:34 saltmaster salt-master[4218]: File "/usr/lib/python3.7/site-packages/salt/utils/gitfs.py", line 820, in fetch
Jul 09 01:52:34 saltmaster salt-master[4218]: return self._fetch()
Jul 09 01:52:34 saltmaster salt-master[4218]: File "/usr/lib/python3.7/site-packages/salt/utils/gitfs.py", line 1864, in _fetch
Jul 09 01:52:34 saltmaster salt-master[4218]: fetch_results = origin.fetch(**fetch_kwargs)
Jul 09 01:52:34 saltmaster salt-master[4218]: File "/usr/local/lib64/python3.7/site-packages/pygit2/remote.py", line 147, in fetch
Jul 09 01:52:34 saltmaster salt-master[4218]: payload.check_error(err)
Jul 09 01:52:34 saltmaster salt-master[4218]: File "/usr/local/lib64/python3.7/site-packages/pygit2/callbacks.py", line 93, in check_error
Jul 09 01:52:34 saltmaster salt-master[4218]: check_error(error_code)
Jul 09 01:52:34 saltmaster salt-master[4218]: File "/usr/local/lib64/python3.7/site-packages/pygit2/errors.py", line 56, in check_error
Jul 09 01:52:34 saltmaster salt-master[4218]: raise KeyError(message)
Jul 09 01:52:34 saltmaster salt-master[4218]: KeyError: 'object not found - no match for id (5bd6c259e6fe53628193ae4346e6c4114338576f)'
```
config file section (and I get the same sort of error when doing it with the users-formula, presumably with everything):
```
gitfs_remotes:
  - https://github.com/saltstack-formulas/logrotate-formula.git:
    - root: logrotate
    - mountpoint: salt://logrotate
    - base: v0.12.0
```

**Comment by qt-crajapakshe** [comment]
I have same issue in seeing git backend and its complaining about match id. Installed and configured GitPython instead and its working as expected. https://docs.saltproject.io/en/latest/topics/tutorials/gitfs.html#id2

**Comment by bearrito** [comment]
Any update on this? Or other workarounds? I'm seeing this issue as well.

**Comment by remyd1** [comment]
Hi,

I switched to `gitpython` on my salt masters (`3.1.13` with `Python 3.8.10`, and `3.1.14` with `Python 3.9.2` on another master).

**Comment by jzandbergen** [comment]
I just resolved this exact problem on my end as follows. 

Let's say the error is:
```
[ERROR   ] Exception caught while fetching gitfs remote 'git@github.com:xxxxx/yyyyy-formula.git': 'object not found - no match for id (22655d3d7e7194ca39de109cccd1f9d4fc3e4f2e)'
```

Then we can make a strace of the causing command like:
```bash
mkdir /tmp/w00t
cd /tmp/w00t
strace -ff -o saltrun -yY --trace=%file salt-run fileserver.update backend=gitfs
```

As soon  as you see the error, break the strace with `ctrl-c`

Check which cache directory is missing the file:
```bash
# note: omit the first two characters from the error message because those are used as the directory name!
grep 655d3d7e7194ca39de109cccd1f9d4fc3e4f2e *
saltrun.2929371:access("/var/cache/salt/master/gitfs/By27xe5qrllYTVYjZywQQ10Rf5+i_dAHpvggrUqcJIc=/_/.git/objects/22/655d3d7e7194ca39de109cccd1f9d4fc3e4f2e", F_OK) = -1 ENOENT (No such file or directory)
saltrun.2929371:access("/var/cache/salt/master/gitfs/By27xe5qrllYTVYjZywQQ10Rf5+i_dAHpvggrUqcJIc=/_/.git/objects/22/655d3d7e7194ca39de109cccd1f9d4fc3e4f2e", F_OK) = -1 ENOENT (No such file or directory)
```

Stop the salt-master,delete the offending cache directory:
```bash
rm -Rf /var/cache/salt/master/gitfs/By27xe5qrllYTVYjZywQQ10Rf5+i_dAHpvggrUqcJIc\=/
```

Start the salt-master and try again.
