### ISSUE TITLE
[BUG] file.replace cannot accept empty list of flags

### ISSUE THREAD

**Issue by OrangeDog** [saltstack/salt#59554]
**Description**
Despite the documentation saying you can use either a list of a number, if you want to compile the pattern with no flags then an empty list does not work.

```
An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/state.py", line 2153, in call
    ret = self.states[cdata["full"]](
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2106, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/states/file.py", line 5176, in replace
    changes = __salt__["file.replace"](
  File "/usr/lib/python3/dist-packages/salt/modules/file.py", line 2530, in replace
    flags_num = _get_flags(flags)
  File "/usr/lib/python3/dist-packages/salt/modules/file.py", line 1660, in _get_flags
    return reduce(operator.__or__, _flags_acc)
TypeError: reduce() of empty sequence with no initial value
```

**Setup**
```sls
/data/foo:
  file.replace:
    - pattern: abc
    - repl: def
    - flags: []
```

**Expected behavior**
Should be the same as `-flags: 0`

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3002.2

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.10.1
       libgit2: 0.28.3
      M2Crypto: 0.31.0
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: 1.0.3
        Python: 3.8.5 (default, Jul 28 2020, 12:59:40)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-65-generic
        system: Linux
       version: Ubuntu 20.04 focal
```
</details>

**Additional context**
Should be a very simple fix:
```python
return reduce(operator.__or__, _flags_acc, 0)
```

**Comment by jennshan** [comment]
Hi,

I would like to work on this, is it up for grabs?
