### ISSUE TITLE
[BUG] Salt-minion not connecting after key accepted

### ISSUE THREAD

**Issue by DixanR** [saltstack/salt#59562]
**Description**
Salt-minion not connecting to master after key is accepted.

minion makes multiple connection attempts with no success.

```
[DEBUG   ] Connecting to master. Attempt 1 of 1
[DEBUG   ] Master URI: tcp://10.100.100.162:4506
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'O1X13A01', 'tcp://10.100.100.162:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (10309)
[DEBUG   ] Setting zmq_reconnect_ivl to '10309ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'O1X13A01', 'tcp://10.100.100.162:4506', 'clear')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://10.100.100.162:4506
[DEBUG   ] Trying to connect to: tcp://10.100.100.162:4506
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] salt.crypt._get_key_with_evict: Loading private key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[DEBUG   ] Connecting the Minion to the Master publish port, using the URI: tcp://10.100.100.162:4505
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'O1X13A01', 'tcp://10.100.100.162:4506', 'aes')
[DEBUG   ] Re-using AsyncAuth for ('/etc/salt/pki/minion', 'O1X13A01', 'tcp://10.100.100.162:4506')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://10.100.100.162:4506
[DEBUG   ] Trying to connect to: tcp://10.100.100.162:4506
[ERROR   ] Minion unable to successfully connect to a Salt Master.
[DEBUG   ] SaltReqTimeoutError, retrying. (1/3)
[DEBUG   ] SaltReqTimeoutError, retrying. (2/3)
[DEBUG   ] SaltReqTimeoutError, retrying. (3/3)
[DEBUG   ] Re-init ZMQ socket: Message timed out
[DEBUG   ] Trying to connect to: tcp://10.100.100.162:4506
[ERROR   ] Exception getting pillar:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/pillar/__init__.py", line 243, in compile_pillar
    load, dictkey="pillar",
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/gen.py", line 1064, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python3/dist-packages/salt/transport/zeromq.py", line 356, in crypted_transfer_decode_dictentry
    tries=tries,
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
salt.exceptions.SaltReqTimeoutError: Message timed out
```
on the master side, it responds with public key and then nothing else happens.

```
[INFO    ] Authentication request from O1X13A01
[INFO    ] Authentication accepted from O1X13A01
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
[DEBUG   ] Sending event: tag = salt/auth; data = {'result': True, 'act': 'accept', 'id': 'O1X13A01', 'pub': '-----BEGIN PUBLIC \\\REMOVED\\\-----END PUBLIC KEY-----', '_stamp': '2021-02-19T21:23:12.020827'}
``` 

In the firewall log i can see the masters response.

```
10.110.16.2.42604 -> 10.100.100.162.4506: syn 3985408552
10.100.100.162.4506 -> 10.110.16.2.42604: syn 351929124 ack 3985408553
10.110.16.2.42604 -> 10.100.100.162.4506: ack 351929125
10.110.16.2.42604 -> 10.100.100.162.4506: psh 3985408553 ack 351929125
10.100.100.162.4506 -> 10.110.16.2.42604: ack 3985408563
10.100.100.162.4506 -> 10.110.16.2.42604: psh 351929125 ack 3985408563
10.110.16.2.42604 -> 10.100.100.162.4506: ack 351929136
10.110.16.2.42604 -> 10.100.100.162.4506: psh 3985408563 ack 351929136
10.100.100.162.4506 -> 10.110.16.2.42604: psh 351929136 ack 3985408617
10.100.100.162.4506 -> 10.110.16.2.42604: psh 351929189 ack 3985408617
10.110.16.2.42604 -> 10.100.100.162.4506: ack 351929189
10.110.16.2.42604 -> 10.100.100.162.4506: ack 351929232
10.110.16.2.42604 -> 10.100.100.162.4506: psh 3985412775 ack 351929232
10.100.100.162.4506 -> 10.110.16.2.42604: ack 3985408617
10.100.100.162.4505 -> 10.110.16.2.42776: ack 2392000099
``` 

both ports are reachable from the minion. 

```
root@minion:/etc# nc -nvz -w2 10.100.100.162 4506
(UNKNOWN) [10.100.100.162] 4506 (?) open
root@minion:/etc# nc -nvz -w2 10.100.100.162 4505
(UNKNOWN) [10.100.100.162] 4505 (?) open

```

I was having the same issue with master on v3000 and the minion on v2018, i upgraded with hopes it would be solved but the issue persists.

There are other minions connecting to this master and working correctly.

<details>
<summary>
Master versions report
</summary>

```
Salt Version:
          Salt: 3002.2

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4

System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-1127.19.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core
```
</details>

<details>
<summary>
Minion versions report
</summary>

```
salt-minion --versions-report
Salt Version:
          Salt: 3002.2

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.7.3 (default, Jul 25 2020, 13:03:44)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.1.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.1

System Versions:
          dist: debian 10 buster
        locale: UTF-8
       machine: x86_64
       release: 5.4.65-1-pve
        system: Linux
       version: Debian GNU/Linux 10 buster
```
</details>

**Comment by DixanR** [comment]
IPSec TCP issue.
![image](https://user-images.githubusercontent.com/41627169/108732934-4fa39c80-752e-11eb-9f99-8a0b8cce6fe1.png)

**Comment by DixanR** [comment]
* Reduce the MTU on the salt-minion network card not on the IPSec vti since that will just make it worse.
