### ISSUE TITLE
[BUG]Salt Napalm proxy issue

### ISSUE THREAD

**Issue by macejko8** [saltstack/salt#59575]
**Description**

Hello, I have an issue w/ Salt napalm proxy issue. Connection to local minion which is on the same machine is working fine, proxy is running also on the same machine.

I am getting the following error when running this test command sudo salt '*' test.version
ubuntu:
    2017.7.4
swsmaller:
    Minion did not return. [Not connected]
sw1:
    Minion did not return. [Not connected]

swsmaller and sw1 are the napalm proxies

I am also getting this error in /var/log/salt/proxy:
2021-02-22 03:21:57,723 [salt.cli.daemons                                        :532 ][ERROR   ][5691] Proxymodule napalm is missing an init() or a shutdown() or both. Check your proxymodule.  Salt-proxy aborted.

And this one when trying to test connection to the device via napalm .......napalm --vendor ios --user matej --password klklkl 192.168.1.92

Traceback (most recent call last):
  File "/home/matej/.local/bin/napalm", line 7, in <module>
    from napalm.base.clitools.cl_napalm import main
  File "/home/matej/.local/lib/python2.7/site-packages/napalm/__init__.py", line 5, in <module>
    from napalm.base import get_network_driver
  File "/home/matej/.local/lib/python2.7/site-packages/napalm/base/__init__.py", line 22, in <module>
    from napalm.base.base import NetworkDriver
  File "/home/matej/.local/lib/python2.7/site-packages/napalm/base/base.py", line 17, in <module>
    from netmiko import ConnectHandler, NetMikoTimeoutException
  File "/home/matej/.local/lib/python2.7/site-packages/netmiko/__init__.py", line 7, in <module>
    from netmiko.ssh_dispatcher import ConnectHandler
  File "/home/matej/.local/lib/python2.7/site-packages/netmiko/ssh_dispatcher.py", line 2, in <module>
    from netmiko.a10 import A10SSH
  File "/home/matej/.local/lib/python2.7/site-packages/netmiko/a10/__init__.py", line 1, in <module>
    from netmiko.a10.a10_ssh import A10SSH
  File "/home/matej/.local/lib/python2.7/site-packages/netmiko/a10/a10_ssh.py", line 3, in <module>
    from netmiko.cisco_base_connection import CiscoSSHConnection
  File "/home/matej/.local/lib/python2.7/site-packages/netmiko/cisco_base_connection.py", line 165
    msg = f"Login failed: {self.host}"
                                     ^
SyntaxError: invalid syntax

I suppose more likely issue w/ napalm than w/ Salt itself.
Any ides what could be wrong? I have installed napalm according to this link https://napalm.readthedocs.io/en/latest/installation/index.html also with the dependecies for ios.

Thanks
**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info).

**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

**Expected behavior**

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
PASTE HERE
```
</details>

**Additional context**

**Comment by sagetherage** [comment]
@macejko8 you are running Salt version 2017.7.4? please upgrade to a supported version of Salt >v3000.x, you can find these here: http://repo.saltproject.io/3000.html, the latest version is 3002.2 http://repo.saltproject.io/index.html and we have a CVE release announced weeks ago that will be available Thursday US hours. If the issue persists, please open another ticket and let us know if the template is difficult to use.
