### ISSUE TITLE
[BUG] salt-run state.event pretty=True hangs and ends with exception upon exit

### ISSUE THREAD

**Issue by TathanT** [saltstack/salt#59618]
**Description**
Running the command `salt-run state.event pretty=True` hangs for an endless time period. Use Ctrl+C to exit and it returns an exception.

```bash
salt-run state.event pretty=True
^C
Exception occurred in runner state.event: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/client/mixins.py", line 397, in low
    data["return"] = func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/runners/state.py", line 305, in event
    node=node,
  File "/usr/lib/python3.6/site-packages/salt/modules/state.py", line 2477, in event
    ret = sevent.get_event(full=True, auto_reconnect=True)
  File "/usr/lib/python3.6/site-packages/salt/utils/event.py", line 655, in get_event
    ret = self._get_event(wait, tag, match_func, no_block)
  File "/usr/lib/python3.6/site-packages/salt/utils/event.py", line 556, in _get_event
    raw = self.subscriber.read_sync(timeout=wait)
  File "/usr/lib/python3.6/site-packages/salt/transport/ipc.py", line 726, in read_sync
    return self.io_loop.run_sync(lambda: self._read(timeout))
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/ioloop.py", line 454, in run_sync
    self.start()
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/ioloop.py", line 865, in start
    event_pairs = self._impl.poll(poll_timeout)
  File "/usr/lib/python3.6/site-packages/salt/scripts.py", line 76, in _handle_signals
    trace=trace,
  File "/usr/lib/python3.6/site-packages/salt/scripts.py", line 40, in _handle_interrupt
    raise exc
SystemExit: 
Exiting gracefully on Ctrl-c

```

**Versions Report**
```bash
Salt Version:
          Salt: 3002.2
 
Dependency Versions:
          cffi: 1.14.0
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: 4.0.5
     gitpython: 3.1.12
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.0.0
         smmap: 3.0.4
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4
 
System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-1160.11.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core
```

**Comment by sagetherage** [comment]
@TathanT 
The Salt version is vulnerable. We recommend upgrading as soon as possible to at least latest point release or to latest. You can find those here https://github.com/saltstack/salt/releases or the packages repo here: https://repo.saltproject.io/

I do wonder if this is still an issue if you were to upgrade to [Salt v3002.6](https://github.com/saltstack/salt/tree/v3002.6), can you upgrade and confirm?

**Comment by TathanT** [comment]
Unfortunately I no longer have access to the same system where the issue existed so I won't be able to test the resolution

**Comment by baby-gnu** [comment]
It's still present on 3004.1.

Using kill signals `HUP` or `ABRT` avoid the traceback:

- `kill -HUP`
  ```
  # salt-run state.event pretty=True 
  Hangup
  ```
- `kill -ABRT`
  ```
  # salt-run state.event pretty=True 
  Aborted
  ```
