### ISSUE TITLE
[BUG] CherryPy Could not serialize the return data from Salt

### ISSUE THREAD

**Issue by Linuturk** [saltstack/salt#59620]
**Description**
When attempting to access the `/stats` endpoint via the salt-api, I receive the following response:

```html
<!DOCTYPE html PUBLIC
"-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>500 Internal Server Error</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>500 Internal Server Error</h2>
        <p>Could not serialize the return data from Salt.</p>
        <pre id="traceback"></pre>
    <div id="powered_by">
      <span>
        Powered by <a href="http://www.cherrypy.org">CherryPy 8.9.1</a>
      </span>
    </div>
    </body>
</html>
```

**Setup**
```yaml
rest_cherrypy:
  collect_stats: True
  port: 7101
  disable_ssl: True
  static: /var/www/salt-api
  static_path: /healthcheck
```

**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

1. Follow the instructions here: https://docs.saltproject.io/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html#authentication to get an authentication token for the api.
```bash
curl -sS http://localhost:7101/login -H 'Accept: application/json' -d username=saltdev -d password=saltdev -d eauth=pam
{"return": [{"token": "xxx", "expire": 1614346756.7356985, "start": 1614303556.7356982, "user": "saltdev", "eauth": "pam", "perms": [".*", "@jobs", "@runner"]}]}
```
2. Use the token to access the `stats` endpoint.
```bash
# curl -sS http://localhost:7101/stats -H 'Accept: application/json' -H 'X-Auth-Token: xxx'
<!DOCTYPE html PUBLIC
"-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>405 Method Not Allowed</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>405 Method Not Allowed</h2>
        <p>Specified method is invalid for this resource</p>
        <pre id="traceback"></pre>
    <div id="powered_by">
      <span>
        Powered by <a href="http://www.cherrypy.org">CherryPy 8.9.1</a>
      </span>
    </div>
    </body>
</html>
```
3. Make the same request, but for the yaml output, and you receive the stats.
```bash
curl -sS http://localhost:7101/stats -H 'Accept: application/x-yaml' -H 'X-Auth-Token: xxx'
CherryPy Applications:
  Bytes Read/Request: 2.028225806451613
  Bytes Read/Second: 0.21173904402536514
  Bytes Written/Request: 8986.592741935483
  Bytes Written/Second: 938.1660302839282
  Current Requests: 1
  Current Time: 1614303967.352832
  Enabled: true
  Requests: .... << truncated as it's really large
```

`/var/log/salt/api` has no information on the error.

**Expected behavior**
I expect the same data returned when requesting YAML to be returned when requesting JSON.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
# salt -V
Salt Version:
          Salt: 3002.5
 
Dependency Versions:
          cffi: 1.11.5
      cherrypy: unknown  << Shows as Unknown but the version from the installed package is 8.9.1-2
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: 2.0.3
     gitpython: 2.1.8
        Jinja2: 2.10
       libgit2: 0.26.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.18
      pycrypto: 2.6.1
  pycryptodome: 3.4.7
        pygit2: 0.26.2
        Python: 3.6.9 (default, Jan 26 2021, 15:33:00)
  python-gnupg: 0.4.1
        PyYAML: 3.12
         PyZMQ: 17.1.2
         smmap: 2.0.3
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.5
 
System Versions:
          dist: ubuntu 18.04 Bionic Beaver
        locale: UTF-8
       machine: x86_64
       release: 5.4.0-1037-aws
        system: Linux
       version: Ubuntu 18.04 Bionic Beaver
```
</details>

**Additional context**
Happy to produce any additional information that might help debug this issue.

**Comment by Linuturk** [comment]
I was able to get debug logs from the salt-api service:

```
[INFO    ] 127.0.0.1 - - [01/Mar/2021:23:21:23] "GET /stats HTTP/1.1" 500 775 "" "curl/7.58.0"
[DEBUG   ] Could not serialize the return data from Salt.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/netapi/rest_cherrypy/app.py", line 909, in hypermedia_handler
    response = out(ret)
  File "/usr/lib/python3/dist-packages/salt/utils/json.py", line 149, in dumps
    return json_module.dumps(obj, **kwargs)  # future lint: blacklisted-function
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable
[INFO    ] 127.0.0.1 - - [01/Mar/2021:23:21:36] "GET /stats HTTP/1.1" 500 453 "" "Go-http-client/1.1"
```

**Comment by Linuturk** [comment]
I added a debug log line to the output:

```python
    # Transform the output from the handler into the requested output format
    cherrypy.response.headers["Content-Type"] = best
    out = cherrypy.response.processors[best]
    try:
        logger.debug(ret, exc_info=True) <<<<
        response = out(ret)
        return salt.utils.stringutils.to_bytes(response)
    except Exception:  # pylint: disable=broad-except
        msg = "Could not serialize the return data from Salt."
        logger.debug(msg, exc_info=True)
        raise cherrypy.HTTPError(500, msg)
```

and I get the value of the ret added to the output

```
[DEBUG   ] {'CherryPy Applications': {'Enabled': True, 'Bytes Read/Request': 7.166666666666667, 'Bytes Read/Second': 2.146173957221429, 'Bytes Written/Request': 269.8333333333333, 'Bytes Written/Second': 80.80593157855405, 'Current Time': 1614641449.128699, 'Current Requests': 1, 'Requests/Second': 0.2994660088411752, 'Server Version': '8.9.1', 'Start Time': 1614641429.0930395, 'Total Bytes Read': 43, 'Total Bytes Written': 1619, 'Total Requests': 6, 'Total Time': 0.03468632698059082, 'Uptime': 20.03566884994507, 'Requests': {140273967429376: {'Bytes Read': 43, 'Bytes Written': 198, 'Client': '127.0.0.1:47208', 'End Time': 1614641432.810507, 'Processing Time': 0.031494140625, 'Request-Line': 'POST /login HTTP/1.1', 'Response Status': b'200 OK', 'Start Time': 1614641432.779013}, 140273959036672: {'Bytes Read': 0, 'Bytes Written': 441, 'Client': '127.0.0.1:47230', 'End Time': 1614641436.1050928, 'Processing Time': 0.0006456375122070312, 'Request-Line': 'GET /jobs HTTP/1.1', 'Response Status': b'401 Unauthorized', 'Start Time': 1614641436.1044471}, 140273950643968: {'Bytes Read': 0, 'Bytes Written': 98, 'Client': '127.0.0.1:47276', 'End Time': 1614641446.1943545, 'Processing Time': 0.0007359981536865234, 'Request-Line': 'GET /healthcheck/static HTTP/1.1', 'Response Status': b'200 OK', 'Start Time': 1614641446.1936185}, 140273942251264: {'Bytes Read': None, 'Bytes Written': None, 'Client': '127.0.0.1:47288', 'End Time': None, 'Processing Time': 0.0002589225769042969, 'Request-Line': 'GET /stats HTTP/1.1', 'Response Status': None, 'Start Time': 1614641449.1284766}}}, 'CherryPy HTTPServer 140274374866592': {'Enabled': False, 'Bind Address': "('0.0.0.0', 7101)", 'Run time': -1, 'Accepts': 0, 'Accepts/sec': 0.0, 'Queue': 0, 'Threads': 100, 'Threads Idle': 98, 'Socket Errors': 0, 'Requests': -1, 'Bytes Read': -1, 'Bytes Written': -1, 'Work Time': -1, 'Read Throughput': -1, 'Write Throughput': -1, 'Worker Threads': {'CP Server Thread-3': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-4': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-5': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-6': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-7': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-8': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-9': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-10': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-11': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-12': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-13': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-14': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-15': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-16': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-17': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-18': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-19': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-20': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-21': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-22': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-23': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-24': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-25': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-26': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-27': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-28': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-29': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-30': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-31': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-32': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-33': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-34': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-35': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-36': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-37': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-38': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-39': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-40': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-41': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-42': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-43': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-44': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-45': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-46': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-47': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-48': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-49': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-50': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-51': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-52': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-53': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-54': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-55': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-56': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-57': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-58': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-59': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-60': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-61': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-62': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-63': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-64': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-65': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-66': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-67': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-68': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-69': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-70': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-71': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-72': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-73': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-74': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-75': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-76': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-77': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-78': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-79': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-80': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-81': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-82': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-83': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-84': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-85': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-86': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-87': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-88': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-89': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-90': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-91': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-92': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-93': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-94': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-95': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-96': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-97': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-98': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-99': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-100': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-101': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}, 'CP Server Thread-102': {'Requests': 0, 'Bytes Read': 0, 'Bytes Written': 0, 'Work Time': 0, 'Read Throughput': 0.0, 'Write Throughput': 0.0}}}}
NoneType: None
[DEBUG   ] Could not serialize the return data from Salt.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/netapi/rest_cherrypy/app.py", line 910, in hypermedia_handler
    response = out(ret)
  File "/usr/lib/python3/dist-packages/salt/utils/json.py", line 149, in dumps
    return json_module.dumps(obj, **kwargs)  # future lint: blacklisted-function
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable
```

I popped the bytes into a text editor and did some manual transformation from Python to JSON by replacing single quotes with double quotes and a few other manual find/replace actions, and it does seem to translate to JSON properly.

**Comment by Linuturk** [comment]
I think I've narrowed it down a bit. It seems that the `Response Status` key in some of the data contains a byte string instead of a normal utf-8 string. That could be what's causing the error.

**Comment by sagetherage** [comment]
Yes, we have a few issues in the backlog referring to this:
https://github.com/saltstack/salt/issues/57433
https://github.com/saltstack/salt/issues/56895
and maybe others

**Comment by erwindon** [comment]
I found the same error and analysed it to the same cause (i.e. bytes string in the `Response Status` field).
This makes it impossible to retrieve salt-api statistics by using `[rest_cherrypy.]collect_stats: true`.

Solved locally by updating `/usr/lib/python3/dist-packages/cherrypy/lib/cpstats.py` around line 363:
```
        w['Response Status'] = getattr(
            resp, 'output_status', None) or resp.status
```
to
```
        w['Response Status'] = str(getattr(
            resp, 'output_status', None), 'utf-8') or resp.status
```

**Comment by garethgreenaway** [comment]
Spent some time looking into this one and wasn't able to reproduce it with the latest Salt code.  I noticed in the original report the version being used was 3002.5.  Are you able to upgrade to see if the issue persists?  Thanks!

**Comment by erwindon** [comment]
@garethgreenaway 
The problem still occurs in 3004.
The location is still `/usr/lib/python3/dist-packages/cherrypy/lib/cpstats.py`, line 363+364.
Debugging show that `resp.output_status` = `b'200'` (a byte-array) on entry of those lines.

**Comment by garethgreenaway** [comment]
@erwindon thanks for the response. Seems like this could be a bug in CherryPy and not Salt?  Can you share your API config and I can try to reproduce.

**Comment by erwindon** [comment]
This snippet is from a local (non-secure) installation on one of my development VMs.
It is almost the default (see also https://docs.saltproject.io/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html).
```
          rest_cherrypy:
            port: 8000
            host: 0.0.0.0
            disable_ssl: true
            app: /home/erwindon/SaltGUI/saltgui/index.html
            static: /home/erwindon/SaltGUI/saltgui/static
            static_path: /static
            log.access_file: /tmp/log_access_file
            log.error_file: /tmp/log_error_file
            collect_stats: true
```
I'm using salt-api to facilitate the SaltGUI web application (for which I'm the maintainer).
But the error also occurs during a simple `curl http://localhost:8000/stats -H 'X-Auth-Token: 697adbdc8fe971d09ae4c2a3add7248859c87079'` (grab your own token from the response of a curl+login)

**Comment by erwindon** [comment]
> Seems like this could be a bug in CherryPy and not Salt

no, I don't think so.

The indicated line is not the line where the actual error occurs.
It is 'only' the line where the data is produced that cannot be handled later.

In the stack-trace provided above by @Linuturk it is shown that the python object which is returned by cherrypy is converted to JSON by a piece of code from Salt.
That is in `/usr/lib/python3/dist-packages/salt/netapi/rest_cherrypy/app.py`, line 909, ultimately calling the `dumps` function in `salt/utils/json.py`.

This is a tricky situation because the object that is converted has a byte-array in one-or-more of its object properties, and not even on the top-level.
The most straightforward solution is to assume it is only the "Response Status" fields, and convert each of these from bytes-array to string.

BTW: the conversion depends on the requested content type.
When content type `application/x-yaml` is requested, the problem field is represented as the somewhat useless text `Response Status: !!binary` and the api is fine.
But when content type `application/json` is requested (the default), then the json-converter causes the exception.

**Comment by garethgreenaway** [comment]
Thanks.  I wasn't including `collect_stats` I'll include that and test again.

**Comment by erwindon** [comment]
@garethgreenaway 
I had good results with the following addition to `netapi/rest_cherrypy/app.py` at line 908, between `try:` and `response = out(ret)`:
```
        # /stats with collect_stats:true returns a byte-array in
        # field "Response Status" in 2 different blocks of its answer
        # this prevents the conversion to json
        # compensate by first translating those fields to strings
        if cherrypy.request.path_info == "/stats" and "CherryPy Applications" in ret:
            CherryPyApplications = ret["CherryPy Applications"]
            if "Requests" in CherryPyApplications:
                requests = CherryPyApplications["Requests"]
                for key,request in requests.items():
                    if "Response Status" in request:
                        rs = request["Response Status"]
                        if type(rs) == type(b""):
                            request["Response Status"] = rs.decode('ascii', 'replace')
            if "Slow Queries" in CherryPyApplications:
                slowqueries = CherryPyApplications["Slow Queries"]
                for slowquery in slowqueries:
                    if "Response Status" in slowquery:
                        rs = slowquery["Response Status"]
                        if type(rs) == type(b""):
                            slowquery["Response Status"] = rs.decode('ascii', 'replace')
```

This could have been a generic function that searches the response for byte-arrays and turns them into strings. but without context, the character-set of such byte-arrays is unclear. It is even unclear whether the bytes-arrays actually are encoded strings. Therefore I chose the approach to only try to translate the known occurrences for a known request url.

**Comment by erwindon** [comment]
Just ran into the same problem again.
And having the memory of a goldfish.
Searched for a solution and found my own answers here... :-(
