### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by oeuftete** [saltstack/salt#59712]
**Description**

Installation of the `systemd` package from PyPI, https://pypi.org/project/systemd/, can prevent salt minion startup.

**Setup/Steps to Reproduce the behavior**

```bash
yum install -y systemd-devel
salt-call pip.install systemd
systemctl stop salt-minion
salt-minion -l debug
```

```text
[root@master1-one ~]# salt-minion -l debug
Traceback (most recent call last):
  File "/usr/bin/salt-minion", line 11, in <module>
    load_entry_point('salt==3002.5', 'console_scripts', 'salt-minion')()
  File "/usr/lib/python3.6/site-packages/salt/scripts.py", line 181, in salt_minion
    salt.utils.process.notify_systemd()
  File "/usr/lib/python3.6/site-packages/salt/utils/process.py", line 184, in notify_systemd
    if systemd.daemon.booted():
AttributeError: module 'systemd.daemon' has no attribute 'booted'
```

**Expected behavior**

The minion should start.

**Versions Report**
<details><summary>salt --versions-report</summary>

```
Salt Version:
          Salt: 3002.5
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.10.1
        pygit2: Not Installed
        Python: 3.6.8 (default, Aug 24 2020, 17:57:11)
  python-gnupg: Not Installed
        PyYAML: 3.12
         PyZMQ: 19.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: centos 8 Core
        locale: UTF-8
       machine: x86_64
       release: 5.4.0-66-generic
        system: Linux
       version: CentOS Linux 8 Core
```
</details>

**Additional context**

There's a conflict with the system-supplied `python3-systemd`.  Maybe catch a bit more in https://github.com/saltstack/salt/blob/c7ec8b9124b9efd29b127ffe7274a6a856557934/salt/utils/process.py#L164-L189 to catch this edge case?

ZD-6424.

**Comment by capsunica** [comment]
You may use this project https://github.com/systemd/python-systemd instead.
I just checked using salt 3004 and it works.

**Comment by MKLeb** [comment]
Hi @oeuftete, I'm looking into this and just attempted to reproduce it on salt 3006.2.  It seems to be working there, are you able to to test against a newer version of salt (ideally 3006.2) to verify this on your end?

**Comment by oeuftete** [comment]
Hi @MKLeb, I haven't been involved with the project for some time now, perhaps someone else here can help verify.
