### ISSUE TITLE
[BUG] kubernetes.service_present fails on Kubernetes python client version 11.0 

### ISSUE THREAD

**Issue by felixmarch** [saltstack/salt#59758]
## Description
Every time I run state.apply with `kubernetes.service_present` it gives me error: 
_ValueError: Invalid value for \`port\`, must not be \`None\`_

### Setup

**tomcat-test.sls**
```
Create tomcat internal service for namespace tomcat:
  kubernetes.service_present:
    - name: tai-tomcat-service-internal
    - kubeconfig: /root/kubeconfig_salt
    - context: default
    - namespace: tomcat
      metadata:
        name: tai-tomcat-service-internal
        labels:
          run: tai-app-service
      spec:
        selector:
          run: tai-app-service
        type: ClusterIP
        ports:
        - name: tai-tomcat-service
          protocol: TCP
          port: 8080
          targetPort: 8080
```

## Steps to Reproduce the behavior
```
root@dev:/srv/salt/kubernetes# salt mytest state.apply kubernetes.tomcat-test
mytest:
----------
          ID: Create tai-tomcat internal service tai for namespace tomcat
    Function: kubernetes.service_present
        Name: tai-tomcat-service-internal
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3.6/site-packages/salt/state.py", line 1981, in call
                  **cdata['kwargs'])
                File "/usr/lib/python3.6/site-packages/salt/loader.py", line 1977, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/states/kubernetes.py", line 312, in service_present
                  **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/modules/kubernetesmod.py", line 1072, in create_service
                  saltenv=saltenv)
                File "/usr/lib/python3.6/site-packages/salt/modules/kubernetesmod.py", line 1466, in __create_object_body
                  spec=spec_creator(spec))
                File "/usr/lib/python3.6/site-packages/salt/modules/kubernetesmod.py", line 1574, in __dict_to_service_spec
                  kube_port = kubernetes.client.V1ServicePort()
                File "/usr/local/lib/python3.6/site-packages/kubernetes/client/models/v1_service_port.py", line 63, in __init__
                  self.port = port
                File "/usr/local/lib/python3.6/site-packages/kubernetes/client/models/v1_service_port.py", line 136, in port
                  raise ValueError("Invalid value for `port`, must not be `None`")  # noqa: E501
              ValueError: Invalid value for `port`, must not be `None`
     Started: 16:53:16.407060
    Duration: 23.525 ms
     Changes:
----------
```

I suspect the method  `__dict_to_service_spec(spec)` on **kubernetesmod.py** would need to pass the port into the constructor `kube_port = kubernetes.client.V1ServicePort()`

[https://github.com/kubernetes-client/python/blame/master/kubernetes/client/models/v1_service_port.py](https://github.com/kubernetes-client/python/blame/master/kubernetes/client/models/v1_service_port.py)

## Expected behavior
From the issue seen on [https://github.com/kubernetes-client/python/issues/1199](https://github.com/kubernetes-client/python/issues/1199) the codes might need to be refactored as `kube_port = kubernetes.client.V1ServicePort(port=port)`

## Versions Report
```
Salt Version:
           Salt: 3000.2

Dependency Versions:
           cffi: 1.14.0
       cherrypy: Not Installed
       dateutil: 2.8.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
       M2Crypto: 0.33.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Aug  7 2019, 17:28:10)
   python-gnupg: Not Installed
         PyYAML: 5.3.1
          PyZMQ: 15.3.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1062.18.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

**Comment by sagetherage** [comment]
@felixmarch Salt v3000.2 is known to be vulnerable, are you able to upgrade to 3000.8? Then are you still seeing this issue?

**Comment by felixmarch** [comment]
Hello @sagetherage 

I upgraded to salt 3001.6 also seeing same errors.

This is the error output from version 3001.6

```
----------
          ID: Create tai-tomcat internal service tai for namespace tomcat
    Function: kubernetes.service_present
        Name: tai-tomcat-service-internal
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3.6/site-packages/salt/state.py", line 2154, in call
                  *cdata["args"], **cdata["kwargs"]
                File "/usr/lib/python3.6/site-packages/salt/loader.py", line 2087, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/states/kubernetes.py", line 320, in service_present
                  **kwargs
                File "/usr/lib/python3.6/site-packages/salt/modules/kubernetesmod.py", line 1252, in replace_service
                  saltenv=saltenv,
                File "/usr/lib/python3.6/site-packages/salt/modules/kubernetesmod.py", line 1416, in __create_object_body
                  spec=spec_creator(spec),
                File "/usr/lib/python3.6/site-packages/salt/modules/kubernetesmod.py", line 1524, in __dict_to_service_spec
                  kube_port = kubernetes.client.V1ServicePort()
                File "/usr/local/lib/python3.6/site-packages/kubernetes/client/models/v1_service_port.py", line 63, in __init__
                  self.port = port
                File "/usr/local/lib/python3.6/site-packages/kubernetes/client/models/v1_service_port.py", line 136, in port
                  raise ValueError("Invalid value for `port`, must not be `None`")  # noqa: E501
              ValueError: Invalid value for `port`, must not be `None`
     Started: 05:47:16.398062
    Duration: 28.728 ms
     Changes:
----------
```

```
Salt Version:
           Salt: 3001.6

Dependency Versions:
           cffi: 1.14.0
       cherrypy: Not Installed
       dateutil: 2.8.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
       M2Crypto: 0.33.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Aug  7 2019, 17:28:10)
   python-gnupg: Not Installed
         PyYAML: 5.3.1
          PyZMQ: 17.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4

System Versions:
           dist: centos 7 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1062.18.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7 Core
```

I believe this issue should be still seen even in the latest version 3002, because in master branch, I saw it was still calling constructor `kube_port = kubernetes.client.V1ServicePort()` without passing the port number into it

[https://github.com/saltstack/salt/blob/master/salt/modules/kubernetesmod.py](https://github.com/saltstack/salt/blob/master/salt/modules/kubernetesmod.py)

```
def __dict_to_service_spec(spec):
    """
    Converts a dictionary into kubernetes V1ServiceSpec instance.
    """
    spec_obj = kubernetes.client.V1ServiceSpec()
    for key, value in spec.items():  # pylint: disable=too-many-nested-blocks
        if key == "ports":
            spec_obj.ports = []
            for port in value:
                kube_port = kubernetes.client.V1ServicePort()  # <--------------------
                if isinstance(port, dict):
                    for port_key, port_value in port.items():
                        if hasattr(kube_port, port_key):
                            setattr(kube_port, port_key, port_value)
                else:
                    kube_port.port = port
                spec_obj.ports.append(kube_port)
        elif hasattr(spec_obj, key):
            setattr(spec_obj, key, value)

    return spec_obj
```

**Comment by sagetherage** [comment]
@felixmarch are you able to open a PR for this?

**Comment by felixmarch** [comment]
Hi @sagetherage 

Would like to raise PR but am not familiar with salt test process.

In PR template, it mentions about test requirement, I tried to follow the doc on https://docs.saltstack.com/en/latest/topics/tutorials/writing_tests.html and ran the nox, but getting no luck with error "No such file or directory: '/root/noxfile.py'"

I guess I would need some time to get familiar with it (I am new to salt dev and integration process here). Would you mind to help me to perform test and raise PR from your side for better process and coverage?

I forked and made my modification here: [fix_59758](https://github.com/felixmarch/salt/commit/10c0a09cdb60764fa4a4717a2d7c090858bab8da)

Before that I also actually tested my changes on version 3001.7, it works fine in my local environment. 

These are my changes that I had tested in my local machine with 3001.7 version: [3001.7-fix-kubernetesmod](https://github.com/felixmarch/salt/commit/2b344dcc70c081e661e17464e7e6215a0b98800a)

Thanks.

**Comment by sagetherage** [comment]
@waynew This is likely a great candidate for the Test Clinic tomorrow Noon to 2 PM MDT and 8-10 PM UTC via [Twitch](https://www.twitch.tv/saltprojectoss) or Thursday's Test Clinic from 8-10 AM MDT and 3-5 PM UTC also on [Twitch](https://www.twitch.tv/saltprojectoss

**Comment by waynew** [comment]
@felixmarch Indeed - I can walk through starting some tests. FWIW that error looks like you're in the wrong directory -- you'll want to be in the root of your clone of the Salt repository

**Comment by sagetherage** [comment]
Thank you, @waynew!  @felixmarch hope this helpful and maybe we can get some of the things in this temporary recording into our docs, or perhaps expound on any thing you see particularly useful :)

**Comment by felixmarch** [comment]
Hey @waynew, @sagetherage. Happy Easter, thanks for the walk thru at Twitch! 

Finally I am able to run nox with some tests you showed in the test clinic there ([commit 1](https://github.com/felixmarch/salt/commit/293e27d0590918d5e1aa488127a039a43d15ca6d)) ([commit 2](https://github.com/felixmarch/salt/commit/7158e73e05936b450c472839618938c3f918817f))

In your last video, you showed some code refactor with a new function named `_port_from_spec(data)`

Would you perform the refactor at your side or you would expect me to do it?

**Comment by sagetherage** [comment]
> Hey @waynew, @sagetherage. Happy Easter, thanks for the walk thru at Twitch!
> 
> Finally I am able to run nox with some tests you showed in the test clinic there ([commit 1](https://github.com/felixmarch/salt/commit/293e27d0590918d5e1aa488127a039a43d15ca6d)) ([commit 2](https://github.com/felixmarch/salt/commit/7158e73e05936b450c472839618938c3f918817f))
> 
> At the end of your video, you showed some code refactor with a new function named `_port_from_spec(data)`
> 
> Would you perform the refactor at your side or you would expect me to do it?

@felixmarch If you are willing to refactor yes please do!

**Comment by felixmarch** [comment]
Hi @sagetherage I refactored the codes ([commit 3](https://github.com/felixmarch/salt/commit/ea9456d912c0cb5f70952762edbecb7dccbfcf85)) ([commit 4](https://github.com/felixmarch/salt/commit/2d682e92c1b38c3ab07fc17329bc26d3db482901)). 
And thanks @waynew, he also gave some input on the ([commit 3](https://github.com/felixmarch/salt/commit/ea9456d912c0cb5f70952762edbecb7dccbfcf85)) there. 
Can you please let me know if these are good on your side now? :smile:

**Comment by waynew** [comment]
@felixmarch can you go ahead and open a PR? Then we can review it there :+1:

**Comment by felixmarch** [comment]
> 
> 
> @felixmarch can you go ahead and open a PR? Then we can review it there 👍

Yep, PR #60218 created. Thanks :handshake::smile:

**Comment by felixmarch** [comment]
@sagetherage Wonder if this is getting merged? 
I saw the [salt-k8s-working-grp](https://github.com/orgs/saltstack/projects/34#card-60415050) project was closed since Aug 4 and no longer active?

**Comment by felixmarch** [comment]
@sagetherage @waynew @garethgreenaway How? It's been more than 6 months, lol 😄
