### ISSUE TITLE
3001 salt-call hangs on ubuntu 20

### ISSUE THREAD

**Issue by keithpjolley** [saltstack/salt#59764]
hi - not sure what's going on here. i've noticed that salt hangs on some of my machines but not all. i have two sls files - cluster/admin.sls and minion/admin01.sls.  the admin.sls will cause salt-call on ubuntu 20 machine to hang, but not on ubuntu 18. admin01.sls won't hang on either machine. i noticed it in particular with the `pkg.installed` command but haven't done enough troubleshooting to figure out if that's the only command causing this.

```
admin01% cat cluster/admin.sls
admin_pkgs:
  pkg.installed:
    - pkgs:
      - gcc

admin01% cat minion/admin01.sls 
always-passes:
  test.succeed_without_changes:
    - name: foo

admin01% admin01:~ $ salt-call -V
Salt Version:
           Salt: 3001
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.6.1
         pygit2: Not Installed
         Python: 3.8.5 (default, Jul 28 2020, 12:59:40)
   python-gnupg: 0.4.5
         PyYAML: 5.3.1
          PyZMQ: 18.1.1
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: ubuntu 20.04 focal
         locale: utf-8
        machine: x86_64
        release: 5.4.0-47-generic
         system: Linux
        version: Ubuntu 20.04 focal
 
admin01% sudo salt-call state.apply minion.admin01 # works as expected
local:

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:   1.436 ms

admin01% sudo salt-call state.apply cluster.admin -l debug # hangs at return
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Including configuration from '/etc/salt/minion.d/mysql.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/mysql.conf
[DEBUG   ] Including configuration from '/etc/salt/minion.d/verbosity.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/verbosity.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: admin01.corp.light.co
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Including configuration from '/etc/salt/minion.d/mysql.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/mysql.conf
[DEBUG   ] Including configuration from '/etc/salt/minion.d/verbosity.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/verbosity.conf
[DEBUG   ] Unable to resolve address fe80::b0f9:e0ff:fe1e:341: [Errno 1] Unknown host
[DEBUG   ] Elapsed time getting FQDNs: 0.014191150665283203 seconds
[DEBUG   ] Loading static grains from /etc/salt/grains
[DEBUG   ] LazyLoaded zfs.is_supported
[DEBUG   ] Connecting to master. Attempt 1 of 1
[DEBUG   ] "salt" Not an IP address? Assuming it is a hostname.
[DEBUG   ] Master URI: tcp://10.0.110.12:4506
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'admin01.corp.light.co', 'tcp://10.0.110.12:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (6463)
[DEBUG   ] Setting zmq_reconnect_ivl to '6463ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'admin01.corp.light.co', 'tcp://10.0.110.12:4506', 'clear')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://10.0.110.12:4506
[DEBUG   ] Trying to connect to: tcp://10.0.110.12:4506
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] salt.crypt._get_key_with_evict: Loading private key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[DEBUG   ] Connecting the Minion to the Master publish port, using the URI: tcp://10.0.110.12:4505
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Determining pillar cache
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'admin01.corp.light.co', 'tcp://10.0.110.12:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'admin01.corp.light.co', 'tcp://10.0.110.12:4506')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://10.0.110.12:4506
[DEBUG   ] Trying to connect to: tcp://10.0.110.12:4506
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded state.apply
[DEBUG   ] LazyLoaded direct_call.execute
[DEBUG   ] LazyLoaded saltutil.is_running
[DEBUG   ] LazyLoaded grains.get
[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'admin01.corp.light.co', 'tcp://10.0.110.12:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'admin01.corp.light.co', 'tcp://10.0.110.12:4506')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://10.0.110.12:4506
[DEBUG   ] Trying to connect to: tcp://10.0.110.12:4506
[DEBUG   ] Gathering pillar data for state run
[DEBUG   ] Finished gathering pillar data for state run
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] In saltenv 'base', looking at rel_path 'cluster/admin.sls' to resolve 'salt://cluster/admin.sls'
[DEBUG   ] In saltenv 'base', ** considering ** path '/var/cache/salt/minion/files/base/cluster/admin.sls' to resolve 'salt://cluster/admin.sls'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://cluster/admin.sls'
[DEBUG   ] No dest file found
[INFO    ] Fetching file from saltenv 'base', ** done ** 'cluster/admin.sls'
[DEBUG   ] compile template: /var/cache/salt/minion/files/base/cluster/admin.sls
[DEBUG   ] Jinja search path: ['/var/cache/salt/minion/files/base']
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'admin01.corp.light.co', 'tcp://10.0.110.12:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'admin01.corp.light.co', 'tcp://10.0.110.12:4506')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://10.0.110.12:4506
[DEBUG   ] Trying to connect to: tcp://10.0.110.12:4506
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/cluster/admin.sls' using 'jinja' renderer: 0.024571657180786133
[DEBUG   ] Rendered data from file: /var/cache/salt/minion/files/base/cluster/admin.sls:
admin_pkgs:
  pkg.installed:
    - pkgs:
      - gcc

[DEBUG   ] Results of YAML rendering: 
OrderedDict([('admin_pkgs', OrderedDict([('pkg.installed', [OrderedDict([('pkgs', ['gcc'])])])]))])
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/cluster/admin.sls' using 'yaml' renderer: 0.0007677078247070312
[DEBUG   ] LazyLoaded config.option
[DEBUG   ] LazyLoaded pkg.install
[DEBUG   ] LazyLoaded pkg.installed
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Including configuration from '/etc/salt/minion.d/mysql.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/mysql.conf
[DEBUG   ] Including configuration from '/etc/salt/minion.d/verbosity.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/verbosity.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: admin01.corp.light.co
[DEBUG   ] Could not LazyLoad boto3.assign_funcs: 'boto3.assign_funcs' is not available.
[DEBUG   ] Error loading module.boto3_elasticsearch: __init__ failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1754, in _load_module
    module_init(self.opts)
  File "/usr/lib/python3/dist-packages/salt/modules/boto3_elasticsearch.py", line 96, in __init__
    __utils__["boto3.assign_funcs"](__name__, "es")
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1278, in __getitem__
    func = super(LazyLoader, self).__getitem__(item)
  File "/usr/lib/python3/dist-packages/salt/utils/lazy.py", line 108, in __getitem__
    raise KeyError(key)
KeyError: 'boto3.assign_funcs'
[INFO    ] Executing command 'pdbedit -V' in directory '/root'
[DEBUG   ] stdout: Version 4.11.6-Ubuntu
[DEBUG   ] output: Version 4.11.6-Ubuntu
[DEBUG   ] DSC: Only available on Windows systems
[DEBUG   ] Module PSGet: Only available on Windows systems
[DEBUG   ] Could not LazyLoad pkg.ex_mod_init: 'pkg.ex_mod_init' is not available.
[INFO    ] Running state [admin_pkgs] at time 12:26:15.337557
[INFO    ] Executing state pkg.installed for [admin_pkgs]
[DEBUG   ] Could not LazyLoad pkg.resolve_capabilities: 'pkg.resolve_capabilities' is not available.
[INFO    ] Executing command ['dpkg-query', '--showformat', '${Status} ${Package} ${Version} ${Architecture}', '-W'] in directory '/root'
[INFO    ] All specified packages are already installed
[INFO    ] Completed state [admin_pkgs] at time 12:26:15.364061 (duration_in_ms=26.502)
[DEBUG   ] File /var/cache/salt/minion/accumulator/140379665902608 does not exist, no need to cleanup
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'admin01.corp.light.co', 'tcp://10.0.110.12:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'admin01.corp.light.co', 'tcp://10.0.110.12:4506')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://10.0.110.12:4506
[DEBUG   ] Trying to connect to: tcp://10.0.110.12:4506
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[DEBUG   ] LazyLoaded highstate.output
local:

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:  26.502 ms
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
<hangs here>^C
admin01%

```

The same commands run on a similar host running ubuntu 18 (with or without the "-l debug" args):

```
admin02% salt-call -V
Salt Version:
           Salt: 3001
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.8.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 3.1.7
         Jinja2: 2.11.2
        libgit2: 1.0.0
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: Not Installed
   pycryptodome: 3.9.8
         pygit2: 1.2.1
         Python: 3.6.9 (default, Oct  8 2020, 12:12:24)
   python-gnupg: 0.4.1
         PyYAML: 5.3.1
          PyZMQ: 19.0.1
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 5.3.0-59-generic
         system: Linux
        version: Ubuntu 18.04 bionic
 

admin02% sudo salt-call state.apply cluster.admin
local:

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:  57.772 ms

admin02% sudo salt-call state.apply minion.admin01
local:

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:   0.993 ms

```

**Comment by importepeu** [comment]
Hi,

Got the same hanging thing here. Needs to Ctrl-C to get back shell after Summary was displayed.

Regards,
Guillaume C.

**Comment by krionbsd** [comment]
@keithpjolley could you upgrade to the latest version - 3002.6 and re-check?

**Comment by sagetherage** [comment]
@keithpjolley are you able to upgrade to v3002.6 and verify this is still an issue?

**Comment by garethgreenaway** [comment]
@keithpjolley Following up again, were you able to upgrade to the latest version which is now 3003.1 and see if the problem still persists?
