### ISSUE TITLE
[BUG] 3002.5 lgpo.set failing on base Windows 2019 image in GCP

### ISSUE THREAD

**Issue by BrettPowell** [saltstack/salt#59769]
**Description**
Salt fails to apply some settings when using lgpo.set to set options on Windows 2019 image in GCP.

**Setup**
Salt version: salt-3002.5-py3.7

Salt state
```
test:
  lgpo.set:
    - name: Network\Windows Connection Manager\Minimize the number of simultaneous connections to the Internet or a Windows Domain
    - policy_class: Machine
    - setting:
        WCM_MinimizeConnections_Options: Enabled
        Minimize Policy Options:
           3 = Prevent Wi-Fi when on Ethernet
```

**Steps to Reproduce the behavior**
1. Download salt-3002.5-py3.7
2. `salt-call  --local --log-level debug --file-root=C:\Users\user\Desktop state.apply state`

```
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Using cached minion ID from c:\salt\conf\minion_id: window-cis-testing.c.cleardata-lab-bretttest.internal
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded state.apply
[DEBUG   ] LazyLoaded direct_call.execute
[DEBUG   ] LazyLoaded saltutil.is_running
[DEBUG   ] LazyLoaded grains.get
[DEBUG   ] LazyLoaded config.get
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[DEBUG   ] Updating roots fileserver cache
[WARNING ] Skipped invalid cache mtime entry in c:\salt\var\cache\salt\minion\roots\mtime_map: C:\Users\brett\Desktop\desktop.ini:1615355351.12268

[WARNING ] Skipped invalid cache mtime entry in c:\salt\var\cache\salt\minion\roots\mtime_map: C:\Users\brett\Desktop\salt.ps1:1615315600.0980518

[WARNING ] Skipped invalid cache mtime entry in c:\salt\var\cache\salt\minion\roots\mtime_map: C:\Users\brett\Desktop\state\init.sls:1615317270.3450286

[WARNING ] Skipped invalid cache mtime entry in c:\salt\var\cache\salt\minion\roots\mtime_map: C:\Users\brett\Desktop\state\yes\init.sls:1615401290.0225139

[DEBUG   ] Gathering pillar data for state run
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] Finished gathering pillar data for state run
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] Could not find file 'salt://state.sls' in saltenv 'base'
[DEBUG   ] In saltenv 'base', looking at rel_path 'state/init.sls' to resolve 'salt://state/init.sls'
[DEBUG   ] In saltenv 'base', ** considering ** path 'c:\salt\var\cache\salt\minion\files\base\state\init.sls' to resolve 'salt://state/init.sls'
[DEBUG   ] compile template: c:\salt\var\cache\salt\minion\files\base\state\init.sls
[DEBUG   ] Jinja search path: ['c:\\salt\\var\\cache\\salt\\minion\\files\\base']
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[PROFILE ] Time (in seconds) to render 'c:\salt\var\cache\salt\minion\files\base\state\init.sls' using 'jinja' renderer: 0.07815718650817871
[DEBUG   ] Rendered data from file: c:\salt\var\cache\salt\minion\files\base\state\init.sls:
include:
    - '.yes'
[DEBUG   ] Results of YAML rendering:
OrderedDict([('include', ['.yes'])])
[PROFILE ] Time (in seconds) to render 'c:\salt\var\cache\salt\minion\files\base\state\init.sls' using 'yaml' renderer: 0.0
[DEBUG   ] Could not find file 'salt://state/yes.sls' in saltenv 'base'
[DEBUG   ] In saltenv 'base', looking at rel_path 'state/yes/init.sls' to resolve 'salt://state/yes/init.sls'
[DEBUG   ] In saltenv 'base', ** considering ** path 'c:\salt\var\cache\salt\minion\files\base\state\yes\init.sls' to resolve 'salt://state/yes/init.sls'
[DEBUG   ] compile template: c:\salt\var\cache\salt\minion\files\base\state\yes\init.sls
[DEBUG   ] Jinja search path: ['c:\\salt\\var\\cache\\salt\\minion\\files\\base']
[PROFILE ] Time (in seconds) to render 'c:\salt\var\cache\salt\minion\files\base\state\yes\init.sls' using 'jinja' renderer: 0.0
[DEBUG   ] Rendered data from file: c:\salt\var\cache\salt\minion\files\base\state\yes\init.sls:
test:
  lgpo.set:
    - name: Network\Windows Connection Manager\Minimize the number of simultaneous connections to the Internet or a Windows Domain
    - policy_class: Machine
    - setting:
        WCM_MinimizeConnections_Options: Enabled
        Minimize Policy Options:
           3 = Prevent Wi-Fi when on Ethernet
[DEBUG   ] Results of YAML rendering:
OrderedDict([('test', OrderedDict([('lgpo.set', [OrderedDict([('name', 'Network\\Windows Connection Manager\\Minimize the number of simultaneous connections to the Internet or a Windows Domain')]), OrderedDict([('policy_class', 'Machine')]), OrderedDict([('setting', OrderedDict([('WCM_MinimizeConnections_Options', 'Enabled'), ('Minimize Policy Options', '3 = Prevent Wi-Fi when on Ethernet')]))])])]))])
[PROFILE ] Time (in seconds) to render 'c:\salt\var\cache\salt\minion\files\base\state\yes\init.sls' using 'yaml' renderer: 0.0
[DEBUG   ] LazyLoaded config.option
[DEBUG   ] LazyLoaded lgpo.set
[DEBUG   ] LazyLoaded lgpo.set
[INFO    ] Running state [Network\Windows Connection Manager\Minimize the number of simultaneous connections to the Internet or a Windows Domain] at time 18:52:45.792879
[INFO    ] Executing state lgpo.set for [Network\Windows Connection Manager\Minimize the number of simultaneous connections to the Internet or a Windows Domain]
[DEBUG   ] LGPO: Loading policy definitions
[DEBUG   ] LazyLoaded file.file_exists
[WARNING ] Trying another: Network\Windows Connection Manager\Minimize the number of simultaneous connections to the Internet or a Windows Domain
[WARNING ] Trying another: Network\Windows Connection Manager\Minimize the number of simultaneous connections to the Internet or a Windows Domain
[DEBUG   ] Compiling non hierarchical return...
[DEBUG   ] pol_data == {'user': {'requested_policy': {}, 'policy_lookup': {}}, 'machine': {'requested_policy': {'Network\\Windows Connection Manager\\Minimize the number of simultaneous connections to the Internet or a Windows Domain': OrderedDict([('WCM_MinimizeConnections_Options', 'Enabled'), ('Minimize Policy Options', '3 = Prevent Wi-Fi when on Ethernet')])}, 'policy_lookup': {'Network\\Windows Connection Manager\\Minimize the number of simultaneous connections to the Internet or a Windows Domain': {'policy_name': 'Network\\Windows Connection Manager\\Minimize the number of simultaneous connections to the Internet or a Windows Domain', 'policy_class': 'machine', 'policy_aliases': ['Minimize the number of simultaneous connections to the Internet or a Windows Domain', 'WCM_MinimizeConnections', 'Network\\Windows Connection Manager\\Minimize the number of simultaneous connections to the Internet or a Windows Domain'], 'policy_found': True, 'rights_assignment': False, 'policy_elements': [{'element_id': 'WCM_MinimizeConnections_Options', 'element_aliases': ['WCM_MinimizeConnections_Options', 'Minimize Policy Options']}], 'message': ''}}}}
[DEBUG   ] current policy == {'Computer Configuration': {'Network\\Windows Connection Manager\\Minimize the number of simultaneous connections to the Internet or a Windows Domain': {'Minimize Policy Options': '3 = Prevent Wi-Fi when on Ethernet'}}}
[DEBUG   ] need to compare Network\Windows Connection Manager\Minimize the number of simultaneous connections to the Internet or a Windows Domain from current/requested policy
[DEBUG   ] Network\Windows Connection Manager\Minimize the number of simultaneous connections to the Internet or a Windows Domain current policy != requested policy
[DEBUG   ] We compared {"minimize policy options": "3 = prevent wi-fi when on ethernet", "wcm_minimizeconnections_options": "enabled"} to {"minimize policy options": "3 = prevent wi-fi when on ethernet"}
[WARNING ] Trying another: Network\Windows Connection Manager\Minimize the number of simultaneous connections to the Internet or a Windows Domain
[WARNING ] C:\salt\bin\lib\site-packages\salt-3002.5-py3.7.egg\salt\modules\win_lgpo.py:6540: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
  if child_item:

[DEBUG   ] An exception occurred in this state: 'NoneType' object has no attribute 'start'
Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt-3002.5-py3.7.egg\salt\state.py", line 2154, in call
    *cdata["args"], **cdata["kwargs"]
  File "C:\salt\bin\lib\site-packages\salt-3002.5-py3.7.egg\salt\loader.py", line 2106, in wrapper
    return f(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt-3002.5-py3.7.egg\salt\states\win_lgpo.py", line 538, in set_
    adml_language=adml_language,
  File "C:\salt\bin\lib\site-packages\salt-3002.5-py3.7.egg\salt\modules\win_lgpo.py", line 10172, in set_
    registry_class=p_class,
  File "C:\salt\bin\lib\site-packages\salt-3002.5-py3.7.egg\salt\modules\win_lgpo.py", line 7868, in _writeAdminTemplateRegPolFile
    policy_data.admx_registry_classes[registry_class]["gpt_extension_guid"],
  File "C:\salt\bin\lib\site-packages\salt-3002.5-py3.7.egg\salt\modules\win_lgpo.py", line 7235, in _write_regpol_data
    gpt_ext_str = gpt_ini_data[gpt_ext_loc.start() : gpt_ext_loc.end()]
AttributeError: 'NoneType' object has no attribute 'start'
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt-3002.5-py3.7.egg\salt\state.py", line 2154, in call
    *cdata["args"], **cdata["kwargs"]
  File "C:\salt\bin\lib\site-packages\salt-3002.5-py3.7.egg\salt\loader.py", line 2106, in wrapper
    return f(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt-3002.5-py3.7.egg\salt\states\win_lgpo.py", line 538, in set_
    adml_language=adml_language,
  File "C:\salt\bin\lib\site-packages\salt-3002.5-py3.7.egg\salt\modules\win_lgpo.py", line 10172, in set_
    registry_class=p_class,
  File "C:\salt\bin\lib\site-packages\salt-3002.5-py3.7.egg\salt\modules\win_lgpo.py", line 7868, in _writeAdminTemplateRegPolFile
    policy_data.admx_registry_classes[registry_class]["gpt_extension_guid"],
  File "C:\salt\bin\lib\site-packages\salt-3002.5-py3.7.egg\salt\modules\win_lgpo.py", line 7235, in _write_regpol_data
    gpt_ext_str = gpt_ini_data[gpt_ext_loc.start() : gpt_ext_loc.end()]
AttributeError: 'NoneType' object has no attribute 'start'

[INFO    ] Completed state [Network\Windows Connection Manager\Minimize the number of simultaneous connections to the Internet or a Windows Domain] at time 18:52:49.829373 (duration_in_ms=4036.494)
[DEBUG   ] File c:\salt\var\cache\salt\minion\accumulator\1784340593096 does not exist, no need to cleanup
[DEBUG   ] LazyLoaded cmd.run
[INFO    ] Executing command attrib in directory 'C:\Users\brett'
[DEBUG   ] output:
[DEBUG   ] LazyLoaded state.check_result
[DEBUG   ] LazyLoaded highstate.output
local:
----------
          ID: test
    Function: lgpo.set
        Name: Network\Windows Connection Manager\Minimize the number of simultaneous connections to the Internet or a Windows Domain
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "C:\salt\bin\lib\site-packages\salt-3002.5-py3.7.egg\salt\state.py", line 2154, in call
                  *cdata["args"], **cdata["kwargs"]
                File "C:\salt\bin\lib\site-packages\salt-3002.5-py3.7.egg\salt\loader.py", line 2106, in wrapper
                  return f(*args, **kwargs)
                File "C:\salt\bin\lib\site-packages\salt-3002.5-py3.7.egg\salt\states\win_lgpo.py", line 538, in set_
                  adml_language=adml_language,
                File "C:\salt\bin\lib\site-packages\salt-3002.5-py3.7.egg\salt\modules\win_lgpo.py", line 10172, in set_
                  registry_class=p_class,
                File "C:\salt\bin\lib\site-packages\salt-3002.5-py3.7.egg\salt\modules\win_lgpo.py", line 7868, in _writeAdminTemplateRegPolFile
                  policy_data.admx_registry_classes[registry_class]["gpt_extension_guid"],
                File "C:\salt\bin\lib\site-packages\salt-3002.5-py3.7.egg\salt\modules\win_lgpo.py", line 7235, in _write_regpol_data
                  gpt_ext_str = gpt_ini_data[gpt_ext_loc.start() : gpt_ext_loc.end()]
              AttributeError: 'NoneType' object has no attribute 'start'
     Started: 18:52:45.792879
    Duration: 4036.494 ms
     Changes:

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   4.036 s
```

**Expected behavior**
The state should alter the computer configuration for `Minimize the number of simultaneous connections to the Internet or a Windows Domain` setting the `Minimize Policy Options` to `3 = Prevent Wi-Fi when on Ethernet`

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3002.5

Dependency Versions:
          cffi: 1.12.2
      cherrypy: 17.4.1
      dateutil: 2.8.0
     docker-py: Not Installed
         gitdb: 2.0.5
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: 1.0.7
       msgpack: 1.0.0
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.19
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
  python-gnupg: 0.4.4
        PyYAML: 5.3.1
         PyZMQ: 18.0.1
         smmap: 2.0.5
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.1

System Versions:
          dist:
        locale: cp1252
       machine: AMD64
       release: 2019Server
        system: Windows
       version: 2019Server 10.0.17763 SP0
```
</details>

**Additional context**
While this does seem to only effect some settings. This salt state works perfectly fine on a AWS Windows 2019 image using the same setup.

```
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Using cached minion ID from c:\salt\conf\minion_id: EC2AMAZ-5UASJIB.ec2.internal
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Motherboard info not available on this system
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded state.apply
[DEBUG   ] LazyLoaded direct_call.execute
[DEBUG   ] LazyLoaded saltutil.is_running
[DEBUG   ] LazyLoaded grains.get
[DEBUG   ] LazyLoaded config.get
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[DEBUG   ] Updating roots fileserver cache
[WARNING ] Skipped invalid cache mtime entry in c:\salt\var\cache\salt\minion\roots\mtime_map: C:\Users\Administrator\Desktop\desktop.ini:1615400694.62151

[WARNING ] Skipped invalid cache mtime entry in c:\salt\var\cache\salt\minion\roots\mtime_map: C:\Users\Administrator\Desktop\EC2 Feedback.website:1466523377.7148287

[WARNING ] Skipped invalid cache mtime entry in c:\salt\var\cache\salt\minion\roots\mtime_map: C:\Users\Administrator\Desktop\EC2 Microsoft Windows Guide.website:1466523383.7926435

[WARNING ] Skipped invalid cache mtime entry in c:\salt\var\cache\salt\minion\roots\mtime_map: C:\Users\Administrator\Desktop\salt-download.ps1:1615400798.829083

[WARNING ] Skipped invalid cache mtime entry in c:\salt\var\cache\salt\minion\roots\mtime_map: C:\Users\Administrator\Desktop\salt-states\init.sls:1615405426.6398113

[DEBUG   ] Gathering pillar data for state run
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] Finished gathering pillar data for state run
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] Could not find file 'salt://salt-states.sls' in saltenv 'base'
[DEBUG   ] In saltenv 'base', looking at rel_path 'salt-states/init.sls' to resolve 'salt://salt-states/init.sls'
[DEBUG   ] In saltenv 'base', ** considering ** path 'c:\salt\var\cache\salt\minion\files\base\salt-states\init.sls' to resolve 'salt://salt-states/init.sls'
[DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://salt-states/init.sls'
[DEBUG   ] No dest file found
[INFO    ] Fetching file from saltenv 'base', ** done ** 'salt-states/init.sls'
[DEBUG   ] compile template: c:\salt\var\cache\salt\minion\files\base\salt-states\init.sls
[DEBUG   ] Jinja search path: ['c:\\salt\\var\\cache\\salt\\minion\\files\\base']
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[PROFILE ] Time (in seconds) to render 'c:\salt\var\cache\salt\minion\files\base\salt-states\init.sls' using 'jinja' renderer: 0.04693126678466797
[DEBUG   ] Rendered data from file: c:\salt\var\cache\salt\minion\files\base\salt-states\init.sls:
test:
   lgpo.set:
    - name: Network\Windows Connection Manager\Minimize the number of simultaneous connections to the Internet or a Windows Domain
    - policy_class: Machine
    - setting:
        WCM_MinimizeConnections_Options: Enabled
        Minimize Policy Options:
           3 = Prevent Wi-Fi when on Ethernet
[DEBUG   ] Results of YAML rendering:
OrderedDict([('test', OrderedDict([('lgpo.set', [OrderedDict([('name', 'Network\\Windows Connection Manager\\Minimize the number of simultaneous connections to the Internet or a Windows Domain')]), OrderedDict([('policy_class', 'Machine')]), OrderedDict([('setting', OrderedDict([('WCM_MinimizeConnections_Options', 'Enabled'), ('Minimize Policy Options', '3 = Prevent Wi-Fi when on Ethernet')]))])])]))])
[PROFILE ] Time (in seconds) to render 'c:\salt\var\cache\salt\minion\files\base\salt-states\init.sls' using 'yaml' renderer: 0.0
[DEBUG   ] LazyLoaded config.option
[DEBUG   ] LazyLoaded lgpo.set
[DEBUG   ] LazyLoaded lgpo.set
[INFO    ] Running state [Network\Windows Connection Manager\Minimize the number of simultaneous connections to the Internet or a Windows Domain] at time 19:49:47.204234
[INFO    ] Executing state lgpo.set for [Network\Windows Connection Manager\Minimize the number of simultaneous connections to the Internet or a Windows Domain]
[DEBUG   ] LGPO: Loading policy definitions
[DEBUG   ] LazyLoaded file.file_exists
[WARNING ] Trying another: Network\Windows Connection Manager\Minimize the number of simultaneous connections to the Internet or a Windows Domain
[WARNING ] Trying another: Network\Windows Connection Manager\Minimize the number of simultaneous connections to the Internet or a Windows Domain
[DEBUG   ] Compiling non hierarchical return...
[DEBUG   ] pol_data == {'user': {'requested_policy': {}, 'policy_lookup': {}}, 'machine': {'requested_policy': {'Network\\Windows Connection Manager\\Minimize the number of simultaneous connections to the Internet or a Windows Domain': OrderedDict([('WCM_MinimizeConnections_Options', 'Enabled'), ('Minimize Policy Options', '3 = Prevent Wi-Fi when on Ethernet')])}, 'policy_lookup': {'Network\\Windows Connection Manager\\Minimize the number of simultaneous connections to the Internet or a Windows Domain': {'policy_name': 'Network\\Windows Connection Manager\\Minimize the number of simultaneous connections to the Internet or a Windows Domain', 'policy_class': 'machine', 'policy_aliases': ['Minimize the number of simultaneous connections to the Internet or a Windows Domain', 'WCM_MinimizeConnections', 'Network\\Windows Connection Manager\\Minimize the number of simultaneous connections to the Internet or a Windows Domain'], 'policy_found': True, 'rights_assignment': False, 'policy_elements': [{'element_id': 'WCM_MinimizeConnections_Options', 'element_aliases': ['WCM_MinimizeConnections_Options', 'Minimize Policy Options']}], 'message': ''}}}}
[DEBUG   ] current policy == {'Computer Configuration': {'Network\\Windows Connection Manager\\Minimize the number of simultaneous connections to the Internet or a Windows Domain': 'Not Configured'}}
[DEBUG   ] need to compare Network\Windows Connection Manager\Minimize the number of simultaneous connections to the Internet or a Windows Domain from current/requested policy
[DEBUG   ] Network\Windows Connection Manager\Minimize the number of simultaneous connections to the Internet or a Windows Domain current policy != requested policy
[DEBUG   ] We compared {"minimize policy options": "3 = prevent wi-fi when on ethernet", "wcm_minimizeconnections_options": "enabled"} to "not configured"
[WARNING ] Trying another: Network\Windows Connection Manager\Minimize the number of simultaneous connections to the Internet or a Windows Domain
[WARNING ] Trying another: Network\Windows Connection Manager\Minimize the number of simultaneous connections to the Internet or a Windows Domain
[DEBUG   ] Compiling non hierarchical return...
[INFO    ] {'old': {'Computer Configuration': {'Network\\Windows Connection Manager\\Minimize the number of simultaneous connections to the Internet or a Windows Domain': 'Not Configured'}}, 'new': {'Computer Configuration': {'Network\\Windows Connection Manager\\Minimize the number of simultaneous connections to the Internet or a Windows Domain': {'Minimize Policy Options': '3 = Prevent Wi-Fi when on Ethernet'}}}}
[INFO    ] Completed state [Network\Windows Connection Manager\Minimize the number of simultaneous connections to the Internet or a Windows Domain] at time 19:49:49.127651 (duration_in_ms=1923.417)
[DEBUG   ] File c:\salt\var\cache\salt\minion\accumulator\3137015144264 does not exist, no need to cleanup
[DEBUG   ] LazyLoaded cmd.run
[INFO    ] Executing command attrib in directory 'C:\Users\Administrator'
[DEBUG   ] output:
[DEBUG   ] LazyLoaded state.check_result
[DEBUG   ] LazyLoaded highstate.output
[DEBUG   ] LazyLoaded nested.output
local:
----------
          ID: test
    Function: lgpo.set
        Name: Network\Windows Connection Manager\Minimize the number of simultaneous connections to the Internet or a Windows Domain
      Result: True
     Comment: The following policies changed:
              Network\Windows Connection Manager\Minimize the number of simultaneous connections to the Internet or a Windows Domain
     Started: 19:49:47.204234
    Duration: 1923.417 ms
     Changes:
              ----------
              new:
                  ----------
                  Computer Configuration:
                      ----------
                      Network\Windows Connection Manager\Minimize the number of simultaneous connections to the Internet or a Windows Domain:
                          ----------
                          Minimize Policy Options:
                              3 = Prevent Wi-Fi when on Ethernet
              old:
                  ----------
                  Computer Configuration:
                      ----------
                      Network\Windows Connection Manager\Minimize the number of simultaneous connections to the Internet or a Windows Domain:
                          Not Configured

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   1.923 s
```

**Comment by twangboy** [comment]
This is caused by a gpt.ini file in the `C:\Windows\System32\GroupPolicy` directory that had Unix-style line endings (`\n`). This seems to unique to GCP. I haven't seen it elsewhere. To work around this issue you could do one of the following:

1. If there are already policies applied, fix the line endings in the gpt.ini file so that they are Windows-style line endings (`\r\n`). That's basically what the PR above does.
2. Delete everything in the `C:\Windows\System32\GroupPolicy` directory and let Windows recreate it. Windows will recreate it when you open `gpedit.msc`.
3. Wait for the next Salt release that contains the above fix.

**Comment by BrettPowell** [comment]
The first work around worked for me. Thanks for getting to this so quickly!
