### ISSUE TITLE
[BUG] napalm proxy saltcheck.run_state_tests 

### ISSUE THREAD

**Issue by network-shark** [saltstack/salt#59838]
Hello Saltteam ,

I’m running a napalm proxy minion , I tried to use  saltcheck.run_state_tests
The ‘hello_test’ from the documentation is working, but I tried to created my own test, but it fails with a traceback. Not sure if I pass the wrong args or if it is a bug. Can anyone have a look at ?

```
╰─ salt -V
Salt Version:
           Salt: 3001.3

Dependency Versions:
           cffi: 1.12.2
       cherrypy: unknown
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.6
      gitpython: 2.1.15
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 1.0.0
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 3.8.1
   pycryptodome: 3.9.7
         pygit2: Not Installed
         Python: 3.6.8 (default, Nov  8 2019, 21:16:45)
   python-gnupg: 0.4.4
         PyYAML: 5.3.1
          PyZMQ: 18.0.1
          smmap: 3.0.4
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist: darwin 20.2.0
         locale: UTF-8
        machine: x86_64
        release: 20.2.0
         system: Darwin
        version: 10.16 x86_64
```

Command 
```
salt 'c1000v' saltcheck.run_state_tests cisco.deployment_validation
```

```
net_cli_show_version:
  module_and_function: net.cli
  args:
    - "show version"
  assertion: assertEqual
  expected_return:  'idontknowyetnbutshouldnottheproblem'
```

```
[DEBUG   ] return event: {'c1000v': {'ret': 'The minion function caused an exception: Traceback (most recent call last):\n  File "/Users/sharky/.pyenv/versions/3.6.8/envs/salt-sproxy/lib/python3.6/site-packages/salt/metaproxy/proxy.py", line 480, in thread_return\n    opts, data, func, args, kwargs\n  File "/Users/sharky/.pyenv/versions/3.6.8/envs/salt-sproxy/lib/python3.6/site-packages/salt/executors/direct_call.py", line 12, in execute\n    return func(*args, **kwargs)\n  File "/Users/sharky/.pyenv/versions/3.6.8/envs/salt-sproxy/lib/python3.6/site-packages/salt/modules/saltcheck.py", line 509, in run_state_tests\n    result = global_scheck.run_test(value)\n  File "/Users/sharky/.pyenv/versions/3.6.8/envs/salt-sproxy/lib/python3.6/site-packages/salt/modules/saltcheck.py", line 893, in run_test\n    actual_return = self._call_salt_command(mod_and_func, args, kwargs)\n  File "/Users/sharky/.pyenv/versions/3.6.8/envs/salt-sproxy/lib/python3.6/site-packages/salt/modules/saltcheck.py", line 739, in _call_salt_command\n    value = salt.client.Caller(mopts=mlocal_opts).cmd(fun, *args)\n  File "/Users/sharky/.pyenv/versions/3.6.8/envs/salt-sproxy/lib/python3.6/site-packages/salt/client/__init__.py", line 2135, in cmd\n    return self.sminion.functions[fun](*args, **kwargs)\n  File "/Users/sharky/.pyenv/versions/3.6.8/envs/salt-sproxy/lib/python3.6/site-packages/salt/loader.py", line 1278, in __getitem__\n    func = super(LazyLoader, self).__getitem__(item)\n  File "/Users/sharky/.pyenv/versions/3.6.8/envs/salt-sproxy/lib/python3.6/site-packages/salt/utils/lazy.py", line 108, in __getitem__\n    raise KeyError(key)\nKeyError: \'net.cli\'\n', 'out': 'nested', 'retcode': 1, 'jid': '20210318103422339628'}}
[DEBUG   ] LazyLoaded nested.output
c1000v:
    The minion function caused an exception: Traceback (most recent call last):
      File "/Users/sharky/.pyenv/versions/3.6.8/envs/salt-sproxy/lib/python3.6/site-packages/salt/metaproxy/proxy.py", line 480, in thread_return
        opts, data, func, args, kwargs
      File "/Users/sharky/.pyenv/versions/3.6.8/envs/salt-sproxy/lib/python3.6/site-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/Users/sharky/.pyenv/versions/3.6.8/envs/salt-sproxy/lib/python3.6/site-packages/salt/modules/saltcheck.py", line 509, in run_state_tests
        result = global_scheck.run_test(value)
      File "/Users/sharky/.pyenv/versions/3.6.8/envs/salt-sproxy/lib/python3.6/site-packages/salt/modules/saltcheck.py", line 893, in run_test
        actual_return = self._call_salt_command(mod_and_func, args, kwargs)
      File "/Users/sharky/.pyenv/versions/3.6.8/envs/salt-sproxy/lib/python3.6/site-packages/salt/modules/saltcheck.py", line 739, in _call_salt_command
        value = salt.client.Caller(mopts=mlocal_opts).cmd(fun, *args)
      File "/Users/sharky/.pyenv/versions/3.6.8/envs/salt-sproxy/lib/python3.6/site-packages/salt/client/__init__.py", line 2135, in cmd
        return self.sminion.functions[fun](*args, **kwargs)
      File "/Users/sharky/.pyenv/versions/3.6.8/envs/salt-sproxy/lib/python3.6/site-packages/salt/loader.py", line 1278, in __getitem__
        func = super(LazyLoader, self).__getitem__(item)
      File "/Users/sharky/.pyenv/versions/3.6.8/envs/salt-sproxy/lib/python3.6/site-packages/salt/utils/lazy.py", line 108, in __getitem__
        raise KeyError(key)
    KeyError: 'net.cli'
```

**Comment by network-shark** [comment]
Failure on 3003RC1

```
c1000v:
    The minion function caused an exception: Traceback (most recent call last):
      File "/Users/sharky/.pyenv/versions/3.6.8/envs/salt3003rc/lib/python3.6/site-packages/salt/metaproxy/proxy.py", line 475, in thread_return
        opts, data, func, args, kwargs
      File "/Users/sharky/.pyenv/versions/3.6.8/envs/salt3003rc/lib/python3.6/site-packages/salt/loader.py", line 1235, in __call__
        return self.loader.run(run_func, *args, **kwargs)
      File "/Users/sharky/.pyenv/versions/3.6.8/envs/salt3003rc/lib/python3.6/site-packages/salt/loader.py", line 2262, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "/Users/sharky/.pyenv/versions/3.6.8/envs/salt3003rc/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
        return callable(*args, **kwargs)
      File "/Users/sharky/.pyenv/versions/3.6.8/envs/salt3003rc/lib/python3.6/site-packages/salt/loader.py", line 2277, in _run_as
        return _func_or_method(*args, **kwargs)
      File "/Users/sharky/.pyenv/versions/3.6.8/envs/salt3003rc/lib/python3.6/site-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/Users/sharky/.pyenv/versions/3.6.8/envs/salt3003rc/lib/python3.6/site-packages/salt/loader.py", line 1235, in __call__
        return self.loader.run(run_func, *args, **kwargs)
      File "/Users/sharky/.pyenv/versions/3.6.8/envs/salt3003rc/lib/python3.6/site-packages/salt/loader.py", line 2262, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "/Users/sharky/.pyenv/versions/3.6.8/envs/salt3003rc/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
        return callable(*args, **kwargs)
      File "/Users/sharky/.pyenv/versions/3.6.8/envs/salt3003rc/lib/python3.6/site-packages/salt/loader.py", line 2277, in _run_as
        return _func_or_method(*args, **kwargs)
      File "/Users/sharky/.pyenv/versions/3.6.8/envs/salt3003rc/lib/python3.6/site-packages/salt/modules/saltcheck.py", line 507, in run_state_tests
        result = global_scheck.run_test(value)
      File "/Users/sharky/.pyenv/versions/3.6.8/envs/salt3003rc/lib/python3.6/site-packages/salt/modules/saltcheck.py", line 910, in run_test
        actual_return = self._call_salt_command(mod_and_func, args, kwargs)
      File "/Users/sharky/.pyenv/versions/3.6.8/envs/salt3003rc/lib/python3.6/site-packages/salt/modules/saltcheck.py", line 756, in _call_salt_command
        value = salt.client.Caller(mopts=mlocal_opts).cmd(fun, *args)
      File "/Users/sharky/.pyenv/versions/3.6.8/envs/salt3003rc/lib/python3.6/site-packages/salt/client/__init__.py", line 2122, in cmd
        return self.sminion.functions[fun](*args, **kwargs)
      File "/Users/sharky/.pyenv/versions/3.6.8/envs/salt3003rc/lib/python3.6/site-packages/salt/loader.py", line 1397, in __getitem__
        func = super().__getitem__(item)
      File "/Users/sharky/.pyenv/versions/3.6.8/envs/salt3003rc/lib/python3.6/site-packages/salt/utils/lazy.py", line 108, in __getitem__
        raise KeyError(key)
    KeyError: 'net.cli'
```

**Comment by dmurphy18** [comment]
@sagetherage Are you sure I am the correct person for this since macOS, and I have never worked on Mac's, perhaps @twangboy might be a better person for an initial look. If not, I can dig in tomorrow.

**Comment by sagetherage** [comment]
my mistake I guess it read it incorrectly!

**Comment by network-shark** [comment]
Do you really think this bug is specific to mac os ?

**Comment by dmurphy18** [comment]
@network-shark Standard practice would be to try to reproduce the issue on the platform exhibiting it initially.  The packages for the macOS are produced separately from those done for Linux based packages, and something might have been missed in the packaging efforts.  Use of 'net.cli' has worked with other platforms, hence some dependency might be missing on macOS, hence makes sense to start there.

**Comment by network-shark** [comment]
I never had any problems with net.cli and mac os and proxy minions. I will try to recreated this issue on linux....

**Comment by network-shark** [comment]
@dmurphy18  Update on a debian 10 host

```



root@debian10:/srv/states/cisco# salt-run fileserver.file_list
- cisco/saltcheck-tests/deployment_validation.tst
- top.sls



 salt r1 saltcheck.run_state_tests cisco.deployment_validation
 
r1:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/salt/metaproxy/proxy.py", line 475, in thread_return
        opts, data, func, args, kwargs
      File "/usr/lib/python3/dist-packages/salt/loader.py", line 1235, in __call__
        return self.loader.run(run_func, *args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/loader.py", line 2268, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/loader.py", line 2283, in _run_as
        return _func_or_method(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/loader.py", line 1235, in __call__
        return self.loader.run(run_func, *args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/loader.py", line 2268, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/loader.py", line 2283, in _run_as
        return _func_or_method(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/modules/saltcheck.py", line 507, in run_state_tests
        result = global_scheck.run_test(value)
      File "/usr/lib/python3/dist-packages/salt/modules/saltcheck.py", line 910, in run_test
        actual_return = self._call_salt_command(mod_and_func, args, kwargs)
      File "/usr/lib/python3/dist-packages/salt/modules/saltcheck.py", line 756, in _call_salt_command
        value = salt.client.Caller(mopts=mlocal_opts).cmd(fun, *args)
      File "/usr/lib/python3/dist-packages/salt/client/__init__.py", line 2122, in cmd
        return self.sminion.functions[fun](*args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/loader.py", line 1403, in __getitem__
        func = super().__getitem__(item)
      File "/usr/lib/python3/dist-packages/salt/utils/lazy.py", line 108, in __getitem__
        raise KeyError(key)
    KeyError: 'net.cli'
```

**Comment by dmurphy18** [comment]
Is it possible to give a sample version of **_deployment_validation.tst_** such that I can retry your test.
I don't have a Cisco system available to me, but I do have various versions of Arista to test against with napalm.

Want to run as close to what you are using to reproduce the issue.

**Comment by network-shark** [comment]
It is still the same file. I just read the documentation again. 
```
root@debian10:/srv/states/cisco# cat saltcheck-tests/deployment_validation.tst
net_cli_show_version:
  module_and_function: net.cli
  args:
    - "show version"
  assertion: assertEqual
  expected_return:  'idontknowyetnbutshouldnottheproblem'

```

**Comment by dmurphy18** [comment]
@network-shark FYI able to duplicate given similar test above using Arista

```
root@Unknown:/srv/salt# cat saltcheck/saltcheck-tests/t8.tst 
net_cli_show_version:
  module_and_function: net.cli
  args:
    - "show version"
  assertion: assertEqual
  expected_return:  'idontknowyetnbutshouldnottheproblem'
root@Unknown:/srv/salt# 
```
with errors from 
```
root@Unknown:/srv/salt/saltcheck/saltcheck-tests# salt p7000 saltcheck.run_state_tests saltcheck.t8
p7000:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python3.6/site-packages/salt/metaproxy/proxy.py", line 477, in thread_return
        opts, data, func, args, kwargs
      File "/usr/lib/python3.6/site-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/lib/python3.6/site-packages/salt/modules/saltcheck.py", line 507, in run_state_tests
        result = global_scheck.run_test(value)
      File "/usr/lib/python3.6/site-packages/salt/modules/saltcheck.py", line 910, in run_test
        actual_return = self._call_salt_command(mod_and_func, args, kwargs)
      File "/usr/lib/python3.6/site-packages/salt/modules/saltcheck.py", line 756, in _call_salt_command
        value = salt.client.Caller(mopts=mlocal_opts).cmd(fun, *args)
      File "/usr/lib/python3.6/site-packages/salt/client/__init__.py", line 2122, in cmd
        return self.sminion.functions[fun](*args, **kwargs)
      File "/usr/lib/python3.6/site-packages/salt/loader.py", line 1283, in __getitem__
        func = super().__getitem__(item)
      File "/usr/lib/python3.6/site-packages/salt/utils/lazy.py", line 108, in __getitem__
        raise KeyError(key)
    KeyError: 'net.cli'
ERROR: Minions returned with non-zero exit code
```

However the net.cli is working through napalm with the Arista router (vEOS 64-bit v4.25)
```
root@Unknown:/etc/salt# salt p7000 net.cli 'show version'
p7000:
    ----------
    comment:
    out:
        ----------
        show version:
             vEOS
            Hardware version: 
            Serial number: 
            Hardware MAC address: 0800.27c4.9d95
            System MAC address: 0800.27c4.9d95
            
            Software image version: 4.25.0F
            Architecture: x86_64
            Internal build version: 4.25.0F-19436514.4250F
            Internal build ID: 9271a36c-cfb6-4c58-971e-7e30a4eaf173
            
            Uptime: 0 weeks, 0 days, 0 hours and 18 minutes
            Total memory: 2014556 kB
            Free memory: 939452 kB
            
    result:
        True
```

Digging into the issue and will let you know what I find.

**Comment by dmurphy18** [comment]
Failure is occurring due to the following:
```
1721 [TRACE   ] Error loading module.napalm_network: "net"" (/usr/lib/python3.6/site-packages/salt/modules/napalm_network.py) cannot be loaded: NAPALM is not installed: ``pip install napalm``
```
this is even with init.sls containing:
```
root@Unknown:/srv/salt/saltcheck# cat init.sls 
ensure_capirca:
  cmd.run:
    - name: |
        /usr/bin/pip3 install capirca

ensure_napalm:
  cmd.run:
    - name: |
        /usr/bin/pip3 install napalm

pip3_list:
  cmd.run:
    - name: |
        echo "DGM was here"
        /usr/bin/pip3 list
```

Digging further as to why napalm is not found when using saltcheck module_and_run

**Comment by dmurphy18** [comment]
So communicated with the code author for Saltcheck, William Cannon <william.cannon@gmail.com> and

```
Saltcheck was written to run as a module on a minion not with the proxy.
```

The correct solution will be to add a check to see if this is being run on a proxy and return 'Not supported'

**Comment by danielrobbins** [comment]
@dmurphy18 Are there any quick documentation updates that could be made along with your PR to clarify the situation for end-users of salt?

**Comment by dmurphy18** [comment]
@danielrobbins The documentation already states **minion**, that was what made me think about whether it could also be used with a proxy.  But good suggestion, changed the initial doc string from 

```
A module for testing the logic of states and highstates
```
to 
```
A module for testing the logic of states and highstates on salt minions
```

Thanks for the suggestion
