### ISSUE TITLE
[BUG] Automated salt-minion runs fails intermittently with AuthenticationError

### ISSUE THREAD

**Issue by rravi-sift** [saltstack/salt#59858]
**Description**
After upgrading salt from `2019.2.7` to `3002.2` we started seeing intermittent failures in salt-minion runs

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info).

**Steps to Reproduce the behavior**
Run `salt-call state.apply`
```
2021-03-22 03:40:13,301 [tornado.application:353 ][ERROR   ][3206] Future <salt.ext.tornado.concurrent.Future object at 0x7f5e9ca93940> exception was never retrieved: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/gen.py", line 309, in wrapper
    yielded = next(result)
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 2617, in handle_event
    self._mine_send(tag, data)
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 2570, in _mine_send
    ret = channel.send(data)
  File "/usr/lib/python3/dist-packages/salt/utils/asynchronous.py", line 126, in wrap
    six.reraise(*results[1])
  File "/usr/lib/python3/dist-packages/salt/ext/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/salt/utils/asynchronous.py", line 132, in _target
    result = io_loop.run_sync(lambda: getattr(self.obj, key)(*args, **kwargs))
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/ioloop.py", line 459, in run_sync
    return future_cell[0].result()
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/gen.py", line 1064, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python3/dist-packages/salt/transport/zeromq.py", line 446, in send
    ret = yield self._crypted_transfer(
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/gen.py", line 1064, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python3/dist-packages/salt/transport/zeromq.py", line 420, in _crypted_transfer
    ret = yield _do_transfer()
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/gen.py", line 1070, in run
    yielded = self.gen.send(value)
  File "/usr/lib/python3/dist-packages/salt/transport/zeromq.py", line 406, in _do_transfer
    data = self.auth.crypticle.loads(data, raw)
  File "/usr/lib/python3/dist-packages/salt/crypt.py", line 1541, in loads
    data = self.decrypt(data)
  File "/usr/lib/python3/dist-packages/salt/crypt.py", line 1510, in decrypt
    raise AuthenticationError("message authentication failed")
salt.exceptions.AuthenticationError: message authentication failed
```

**Expected behavior**
salt-call should complete without error

**Versions Report**
`minion`
```
Salt Version:
          Salt: 3002.2

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.8.5 (default, Jul 28 2020, 12:59:40)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-1036-gcp
        system: Linux
       version: Ubuntu 20.04 focal
```

`master`
```
Salt Version:
          Salt: 3002.5

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.8.5 (default, Jul 28 2020, 12:59:40)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-1036-gcp
        system: Linux
       version: Ubuntu 20.04 focal
```

**Comment by sagetherage** [comment]
@rravi-sift Salt v3002.2 is vulnerable are you able to upgrade your minion Salt version to 3002.5?

**Comment by rravi-sift** [comment]
> @rravi-sift Salt v3002.2 is vulnerable are you able to upgrade your minion Salt version to 3002.5?

@sagetherage we can do that, but do you think that's the reason for the error?

**Comment by sagetherage** [comment]
@rravi-sift Not necessarily, but I don't want you on a version that is vulnerable, if that isn't known - can you also verify once upgraded that this issue persists?

**Comment by sagetherage** [comment]
Are you able to upgrade @rravi-sift?

**Comment by rravi-sift** [comment]
No not, yet, I will close this case and reopen it if the upgrade does not fix the issue.

**Comment by marty-macfly** [comment]
Hello,

We are using 3002.6 and we can see the same issue:

```
2021-08-26 11:03:20,978 [tornado.application:356 ][ERROR   ][6596] Future <salt.ext.tornado.concurrent.Future object at 0x000002B1A512C188> exception was never retrieved: Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt-3002.6-py3.7.egg\salt\transport\mixins\auth.py", line 70, in _decode_payload
    payload["load"] = self.auth.crypticle.loads(payload["load"])
  File "C:\salt\bin\lib\site-packages\salt-3002.6-py3.7.egg\salt\crypt.py", line 1541, in loads
    data = self.decrypt(data)
  File "C:\salt\bin\lib\site-packages\salt-3002.6-py3.7.egg\salt\crypt.py", line 1517, in decrypt
    raise AuthenticationError("message authentication failed")
salt.exceptions.AuthenticationError: message authentication failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt-3002.6-py3.7.egg\salt\ext\tornado\gen.py", line 1064, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\salt\bin\lib\site-packages\salt-3002.6-py3.7.egg\salt\transport\zeromq.py", line 661, in wrap_callback
    payload = yield self._decode_messages(messages)
  File "C:\salt\bin\lib\site-packages\salt-3002.6-py3.7.egg\salt\ext\tornado\gen.py", line 1056, in run
    value = future.result()
  File "C:\salt\bin\lib\site-packages\salt-3002.6-py3.7.egg\salt\ext\tornado\concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "C:\salt\bin\lib\site-packages\salt-3002.6-py3.7.egg\salt\ext\tornado\gen.py", line 1064, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\salt\bin\lib\site-packages\salt-3002.6-py3.7.egg\salt\transport\zeromq.py", line 636, in _decode_messages
    ret = yield self._decode_payload(payload)
  File "C:\salt\bin\lib\site-packages\salt-3002.6-py3.7.egg\salt\ext\tornado\gen.py", line 1056, in run
    value = future.result()
  File "C:\salt\bin\lib\site-packages\salt-3002.6-py3.7.egg\salt\ext\tornado\concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "C:\salt\bin\lib\site-packages\salt-3002.6-py3.7.egg\salt\ext\tornado\gen.py", line 1070, in run
    yielded = self.gen.send(value)
  File "C:\salt\bin\lib\site-packages\salt-3002.6-py3.7.egg\salt\transport\mixins\auth.py", line 73, in _decode_payload
    payload["load"] = self.auth.crypticle.loads(payload["load"])
  File "C:\salt\bin\lib\site-packages\salt-3002.6-py3.7.egg\salt\crypt.py", line 1541, in loads
    data = self.decrypt(data)
  File "C:\salt\bin\lib\site-packages\salt-3002.6-py3.7.egg\salt\crypt.py", line 1517, in decrypt
    raise AuthenticationError("message authentication failed")
salt.exceptions.AuthenticationError: message authentication failed
```
