### ISSUE TITLE
[BUG] WinError 126 when salt is installed silently

### ISSUE THREAD

**Issue by robin-thoni** [saltstack/salt#59923]
**Description**
Salt fails to start (service and salt-call).

**Setup**
Windows 10 Pro 20H2

**Steps to Reproduce the behavior**
Install from exe setup with `/S`. This will skip vc redist installation.

**Expected behavior**
Setup provides a command line switch to install vc redist.

**Screenshots**
```
C:\Windows\system32>salt-call
Traceback (most recent call last):
  File "c:\salt\bin\Scripts\salt-call", line 4, in <module>
    __import__('pkg_resources').run_script('salt==3002.6', 'salt-call')
  File "c:\salt\bin\lib\site-packages\pkg_resources\__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "c:\salt\bin\lib\site-packages\pkg_resources\__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "c:\salt\bin\lib\site-packages\salt-3002.6-py3.7.egg\EGG-INFO\scripts\salt-call", line 10, in <module>
    salt_call()
  File "c:\salt\bin\lib\site-packages\salt-3002.6-py3.7.egg\salt\scripts.py", line 437, in salt_call
    import salt.cli.call
  File "c:\salt\bin\lib\site-packages\salt-3002.6-py3.7.egg\salt\cli\call.py", line 6, in <module>
    import salt.cli.caller
  File "c:\salt\bin\lib\site-packages\salt-3002.6-py3.7.egg\salt\cli\caller.py", line 15, in <module>
    import salt.minion
  File "c:\salt\bin\lib\site-packages\salt-3002.6-py3.7.egg\salt\minion.py", line 26, in <module>
    import salt.crypt
  File "c:\salt\bin\lib\site-packages\salt-3002.6-py3.7.egg\salt\crypt.py", line 31, in <module>
    import salt.utils.rsax931
  File "c:\salt\bin\lib\site-packages\salt-3002.6-py3.7.egg\salt\utils\rsax931.py", line 138, in <module>
    libcrypto = _init_libcrypto()
  File "c:\salt\bin\lib\site-packages\salt-3002.6-py3.7.egg\salt\utils\rsax931.py", line 91, in _init_libcrypto
    libcrypto = _load_libcrypto()
  File "c:\salt\bin\lib\site-packages\salt-3002.6-py3.7.egg\salt\utils\rsax931.py", line 84, in _load_libcrypto
    return cdll.LoadLibrary(_find_libcrypto())
  File "c:\salt\bin\lib\ctypes\__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "c:\salt\bin\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```

**Versions Report**
- 3001.x
- 3002.x

**Comment by twangboy** [comment]
VCRedist 2013 is installed by default when the installer is run silently. Are you running with Administrator privileges?

**Comment by xeacott** [comment]
@robin-thoni we've since reproduced this issue and will be looking to fix the installer. for some reason, the .exe and the .msi have recently been failing to install the VCRedist, and that's causing this issue
