### ISSUE TITLE
[BUG] running netmiko function on napalm proxy fails

### ISSUE THREAD

**Issue by network-shark** [saltstack/salt#60061]
Hello Saltdevs, 

**Description**
running  salt '*' napalm.netmiko_commands 'show version' against a cisco csr1000v results in traceback .

According to the docs it is possible to call netmiko via napalm proxy. None of the functions are working for me.

salt 'r1' napalm.netmiko_commands 'show version'
salt 'r1' napalm.netmiko_config 'hostname r1'
salt 'r1' napalm.netmiko_fun send_command 'show version'

It seems all functions above using napalm_mod.netmiko_conn to get connection to the device. Could that function be broken ?

***Whats the issue ?
Netmiko does not work on napalm proxy anymore . It worked on 2019.2.0.

thanks for any feedback

**Setup**
```
Salt Version:
          Salt: 3003

Dependency Versions:
          cffi: 1.14.5
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.5
     gitpython: 2.1.11
        Jinja2: 2.10
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: 2.6.1
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.7.3 (default, Jan 22 2021, 20:04:44)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.1.2
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.1

System Versions:
          dist: debian 10 buster
        locale: UTF-8
       machine: x86_64
       release: 4.19.0-13-amd64
        system: Linux
       version: Debian GNU/Linux 10 buster
```

**Steps to Reproduce the behavior**
Setup a napalm proxy 

Important: add netmiko key in pillar with username and password and device_type .

Setup can be verified with 
```
root@debian10:~# salt '*' napalm.netmiko_args
r1:
    ----------
    device_type:
        cisco_ios
    host:
        172.28.128.8
    keepalive:
        5
    password:
        vagrant
    timeout:
        60
    username:
        vagrant
```

Just to show napalm works and is installed
```
root@debian10:~# salt r1 napalm.call get_facts
r1:
    ----------
    comment:
    out:
        ----------
        fqdn:
            csr1000v-lab.example.com
        hostname:
            csr1000v-lab
        interface_list:
            - GigabitEthernet1
            - GigabitEthernet2
            - GigabitEthernet3
            - GigabitEthernet4
        model:
            CSR1000V
        os_version:
            Virtual XE Software (X86_64_LINUX_IOSD-UNIVERSALK9-M), Version 16.9.6, RELEASE SOFTWARE (fc2)
        serial_number:
            9PCEK87G3D6
        uptime:
            780
        vendor:
            Cisco
    result:
        True
```

Errors:
```
salt '*' napalm.netmiko_commands 'show version' 
r1:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/salt/metaproxy/proxy.py", line 475, in thread_return
        opts, data, func, args, kwargs
      File "/usr/lib/python3/dist-packages/salt/loader.py", line 1235, in __call__
        return self.loader.run(run_func, *args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/loader.py", line 2268, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/loader.py", line 2283, in _run_as
        return _func_or_method(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/loader.py", line 1235, in __call__
        return self.loader.run(run_func, *args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/loader.py", line 2268, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/loader.py", line 2283, in _run_as
        return _func_or_method(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/utils/napalm.py", line 508, in func_wrapper
        ret = func(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/modules/napalm_mod.py", line 614, in netmiko_commands
        conn = netmiko_conn(**kwargs)
      File "/usr/lib/python3/dist-packages/salt/utils/napalm.py", line 508, in func_wrapper
        ret = func(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/modules/napalm_mod.py", line 714, in netmiko_conn
        return __salt__["netmiko.get_connection"](**kwargs)
      File "/usr/lib/python3/dist-packages/salt/loader_context.py", line 72, in __getitem__
        return self.value()[item]
      File "/usr/lib/python3/dist-packages/salt/loader.py", line 1403, in __getitem__
        func = super().__getitem__(item)
      File "/usr/lib/python3/dist-packages/salt/utils/lazy.py", line 108, in __getitem__
        raise KeyError(key)
    KeyError: 'netmiko.get_connection'
ERROR: Minions returned with non-zero exit code
```

```
oot@debian10:~# salt 'r1' napalm.netmiko_fun send_command 'show version'
r1:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/salt/metaproxy/proxy.py", line 475, in thread_return
        opts, data, func, args, kwargs
      File "/usr/lib/python3/dist-packages/salt/loader.py", line 1235, in __call__
        return self.loader.run(run_func, *args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/loader.py", line 2268, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/loader.py", line 2283, in _run_as
        return _func_or_method(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/loader.py", line 1235, in __call__
        return self.loader.run(run_func, *args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/loader.py", line 2268, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/loader.py", line 2283, in _run_as
        return _func_or_method(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/utils/napalm.py", line 508, in func_wrapper
        ret = func(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/modules/napalm_mod.py", line 513, in netmiko_fun
        return __salt__[fun](*args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/loader_context.py", line 72, in __getitem__
        return self.value()[item]
      File "/usr/lib/python3/dist-packages/salt/loader.py", line 1403, in __getitem__
        func = super().__getitem__(item)
      File "/usr/lib/python3/dist-packages/salt/utils/lazy.py", line 108, in __getitem__
        raise KeyError(key)
    KeyError: 'netmiko.send_command'
```
```
root@debian10:~# salt 'r1' napalm.netmiko_config 'hostname r1'
r1:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/salt/metaproxy/proxy.py", line 475, in thread_return
        opts, data, func, args, kwargs
      File "/usr/lib/python3/dist-packages/salt/loader.py", line 1235, in __call__
        return self.loader.run(run_func, *args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/loader.py", line 2268, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/loader.py", line 2283, in _run_as
        return _func_or_method(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/loader.py", line 1235, in __call__
        return self.loader.run(run_func, *args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/loader.py", line 2268, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/loader.py", line 2283, in _run_as
        return _func_or_method(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/utils/napalm.py", line 508, in func_wrapper
        ret = func(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/modules/napalm_mod.py", line 688, in netmiko_config
        return __salt__["netmiko.send_config"](config_commands=config_commands, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/loader_context.py", line 72, in __getitem__
        return self.value()[item]
      File "/usr/lib/python3/dist-packages/salt/loader.py", line 1403, in __getitem__
        func = super().__getitem__(item)
      File "/usr/lib/python3/dist-packages/salt/utils/lazy.py", line 108, in __getitem__
        raise KeyError(key)
    KeyError: 'netmiko.send_config'
```

**Comment by dmurphy18** [comment]
@network-shark Fortunately, I have access to Arista (close enough CLI to Cisco) and can duplicate the issue
```
root@Unknown:/srv/salt# salt p7000 test.versions
p7000:
    Salt Version:
              Salt: 3002.2
     
    Dependency Versions:
              cffi: 1.14.4
          cherrypy: Not Installed
          dateutil: Not Installed
         docker-py: Not Installed
             gitdb: Not Installed
         gitpython: Not Installed
            Jinja2: 2.8.1
           libgit2: Not Installed
          M2Crypto: 0.33.0
              Mako: Not Installed
           msgpack: 0.6.2
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         pycparser: 2.20
          pycrypto: Not Installed
      pycryptodome: Not Installed
            pygit2: Not Installed
            Python: 3.6.8 (default, Apr  2 2020, 13:34:55)
      python-gnupg: Not Installed
            PyYAML: 5.4.1
             PyZMQ: 17.0.0
             smmap: Not Installed
           timelib: Not Installed
           Tornado: 4.5.3
               ZMQ: 4.1.4
     
    System Versions:
              dist: centos 7 Core
            locale: UTF-8
           machine: x86_64
           release: 3.10.0-1127.18.2.el7.x86_64
            system: Linux
           version: CentOS Linux 7 Core
     
root@Unknown:/srv/salt# salt p7000 napalm.alive
p7000:
    ----------
    comment:
    out:
        ----------
        is_alive:
            True
    result:
        True
root@Unknown:/srv/salt# salt p7000 napalm.netmiko_args
p7000:
    ----------
    device_type:
        arista_eos
    host:
        192.168.0.125
    keepalive:
        5
    password:
        dogkat2015
    timeout:
        60
    username:
        admin
root@Unknown:/srv/salt# salt p7000 napalm.netmiko_commands 'show version'
p7000:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python3.6/site-packages/salt/metaproxy/proxy.py", line 477, in thread_return
        opts, data, func, args, kwargs
      File "/usr/lib/python3.6/site-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/lib/python3.6/site-packages/salt/utils/napalm.py", line 508, in func_wrapper
        ret = func(*args, **kwargs)
      File "/usr/lib/python3.6/site-packages/salt/modules/napalm_mod.py", line 622, in netmiko_commands
        conn = netmiko_conn(**kwargs)
      File "/usr/lib/python3.6/site-packages/salt/utils/napalm.py", line 508, in func_wrapper
        ret = func(*args, **kwargs)
      File "/usr/lib/python3.6/site-packages/salt/modules/napalm_mod.py", line 722, in netmiko_conn
        return __salt__["netmiko.get_connection"](**kwargs)
      File "/usr/lib/python3.6/site-packages/salt/loader.py", line 1283, in __getitem__
        func = super().__getitem__(item)
      File "/usr/lib/python3.6/site-packages/salt/utils/lazy.py", line 110, in __getitem__
        return self._dict[key]
    KeyError: 'netmiko.get_connection'
ERROR: Minions returned with non-zero exit code
root@Unknown:/srv/salt# 
```
 Using Salt 3002.2 so whatever the problem is, it has been around for a while.  Will dig into this and let you know what I find.

**Comment by network-shark** [comment]
@dmurphy18  Good to know you can reproduce the iusse.

**Comment by network-shark** [comment]
@dmurphy18  On slack someone mentioded the bug is maybe related to this one ?  https://github.com/saltstack/salt/issues/59690 ?

**Comment by dmurphy18** [comment]
@network-shark Thanks for finding that, it looks likely from a quick read. I shall dig further

**Comment by network-shark** [comment]
@dmurphy18 @sagetherage Any news on this ? Thank you !

**Comment by dmurphy18** [comment]
@network-shark It looks to be related to #59690 and that is a loader issue, so have to fix that first and then re-check that it resolves this issue.  Fixing loader issues takes time due to not wanting to break that, testing etc., still under investigation as to the most appropriate solution.

**Comment by dmurphy18** [comment]
@network-shark Can you provide a sanitized version of your pillar file for the proxy using napalm and netmiko

**Comment by network-shark** [comment]
@dmurphy18 

Sure no problem..

root@debian10:/srv/pillar/base# cat top.sls
base:
  '*':
    - proxy_napalm
    - netmiko

root@debian10:/srv/pillar/base# cat r1.sls
proxy:
  r1:
    proxytype: napalm
    host:  172.28.128.8
root@debian10:/srv/pillar/base# cat proxy_napalm.sls

proxy:
  proxytype: napalm
  user: vagrant
  driver: ios
  password: vagrant
  host: 172.28.128.8
  optional_args:
    enable_password: vagrant
    secret: vagrant

root@debian10:/srv/pillar/base# cat netmiko.sls
netmiko:
  username: vagrant
  password: vagrant

**Comment by dmurphy18** [comment]
Found code responsible for the issue, and have dev. tested fix.   Need to write some tests for the issue.

**Comment by network-shark** [comment]
@dmurphy18 That means the fix will be in 3004 ?

**Comment by dmurphy18** [comment]
Cannot say what fix will appear in what release, but probably will appear in Silicon given current timeframes.
Also working on #60327 while I have the files open and a Cisco Router available to me, so no PR submit for it just yet.
