### ISSUE TITLE
UnicodeEncodeError in v3003

### ISSUE THREAD

**Issue by sagetherage** [saltstack/salt#60102]
Seeing a similar error in master logs, once this happens the master becomes unresponsive until restarted. I've not been able to reproduce it in this way but can achieve the interactive failure detailed in the original post.
```
2021-04-23 17:06:24,391 [salt.transport.zeromq                    :879 ][ERROR  ][4498] Some exception handling a payload from minion
Traceback (most recent call last):
 File "/usr/lib/python3.6/site-packages/salt/payload.py", line 196, in dumps
  msg, default=ext_type_encoder, use_bin_type=use_bin_type
 File "/usr/lib/python3.6/site-packages/salt/utils/msgpack.py", line 133, in packb
  return msgpack.packb(o, **_sanitize_msgpack_kwargs(kwargs))
 File "/usr/lib64/python3.6/site-packages/msgpack/__init__.py", line 46, in packb
  return Packer(**kwargs).pack(o)
 File "msgpack/_packer.pyx", line 284, in msgpack._cmsgpack.Packer.pack
 File "msgpack/_packer.pyx", line 290, in msgpack._cmsgpack.Packer.pack
 File "msgpack/_packer.pyx", line 287, in msgpack._cmsgpack.Packer.pack
 File "msgpack/_packer.pyx", line 234, in msgpack._cmsgpack.Packer._pack
 File "msgpack/_packer.pyx", line 263, in msgpack._cmsgpack.Packer._pack
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 17-18: surrogates not allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "/usr/lib/python3.6/site-packages/salt/transport/zeromq.py", line 875, in handle_message
  ret, req_opts = yield self.payload_handler(payload)
 File "/usr/lib/python3.6/site-packages/salt/ext/tornado/gen.py", line 1056, in run
  value = future.result()
 File "/usr/lib/python3.6/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
  raise_exc_info(self._exc_info)
 File "<string>", line 4, in raise_exc_info
 File "/usr/lib/python3.6/site-packages/salt/ext/tornado/gen.py", line 294, in wrapper
  result = func(*args, **kwargs)
 File "/usr/lib64/python3.6/types.py", line 248, in wrapped
  coro = func(*args, **kwargs)
 File "/usr/lib/python3.6/site-packages/salt/master.py", line 1060, in _handle_payload
  ret = {"aes": self._handle_aes, "clear": self._handle_clear}[key](load)
 File "/usr/lib/python3.6/site-packages/salt/master.py", line 1101, in _handle_clear
  ret = method(load), {"fun": "send_clear"}
 File "/usr/lib/python3.6/site-packages/salt/master.py", line 2286, in publish
  payload = self._prep_pub(minions, jid, clear_load, extra, missing)
 File "/usr/lib/python3.6/site-packages/salt/master.py", line 2373, in _prep_pub
  self.event.fire_event({"minions": minions}, clear_load["jid"])
 File "/usr/lib/python3.6/site-packages/salt/utils/event.py", line 797, in fire_event
  dump_data = self.serial.dumps(data, use_bin_type=True)
 File "/usr/lib/python3.6/site-packages/salt/payload.py", line 233, in dumps
  msg, default=ext_type_encoder, use_bin_type=use_bin_type
 File "/usr/lib/python3.6/site-packages/salt/utils/msgpack.py", line 133, in packb
  return msgpack.packb(o, **_sanitize_msgpack_kwargs(kwargs))
 File "/usr/lib64/python3.6/site-packages/msgpack/__init__.py", line 46, in packb
  return Packer(**kwargs).pack(o)
 File "msgpack/_packer.pyx", line 284, in msgpack._cmsgpack.Packer.pack
 File "msgpack/_packer.pyx", line 290, in msgpack._cmsgpack.Packer.pack
 File "msgpack/_packer.pyx", line 287, in msgpack._cmsgpack.Packer.pack
```
versions
```
# salt-call --versions
Salt Version:
          Salt: 3003

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.8.5 (default, Jan 27 2021, 15:41:15)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.72-microsoft-standard-WSL2
        system: Linux
       version: Ubuntu 20.04 focal
```

_Originally posted by @seandjones92 in https://github.com/saltstack/salt/issues/55162#issuecomment-825943260_

**Comment by dwoz** [comment]
@seandjones92 are you able to upgrade python's msgpack library to 1.0?

**Comment by seandjones92** [comment]
I'll check to see if that's possible

**Comment by dwoz** [comment]
@seandjones92 Have you been able to test with msgpack 1.0?

**Comment by seandjones92** [comment]
with msgpack 1.0 I no longer see the unicode error. Thanks!

**Comment by dwoz** [comment]
Looks like the same issue has been reported before #52406

**Comment by dwoz** [comment]
@seandjones92 I have not been able to re-produce this error. Do you happen to know what states or jobs you were running when it happened?

**Comment by sagetherage** [comment]
I synced up with @seandjones92 and the original issue isn't coming through reliably enough to reproduce and asked me to close this issue.
