### ISSUE TITLE
[BUG] in Master AttributeError in spm/pkgfiles/local.py

### ISSUE THREAD

**Issue by recursiveMake** [saltstack/salt#60106]
**Description**
This reopens issue #51957 as the fix did not appear in later versions.

An AttributeError is raised accessing the name attribute of the unicode string new_name

It seems like the code in salt/spm/pkgfiles/local.py mistakenly tries to get this attribute twice in the install_file function (mirroring the pattern used to get name from the member object).

**Setup**
Install from a configured SPM

**Steps to Reproduce the behavior**

```
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'unicode' object has no attribute 'name'
Traceback (most recent call last):
  File "/usr/bin/spm", line 11, in <module>
    load_entry_point('salt==3000.9', 'console_scripts', 'spm')()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 541, in salt_spm
    spm.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/spm.py", line 41, in run
    client.run(self.args)
  File "/usr/lib/python2.7/site-packages/salt/spm/__init__.py", line 125, in run
    self._install(args)
  File "/usr/lib/python2.7/site-packages/salt/spm/__init__.py", line 379, in _install
    self._install_indv_pkg(package, out_file)
  File "/usr/lib/python2.7/site-packages/salt/spm/__init__.py", line 532, in _install_indv_pkg
    self.files_conn)
  File "/usr/lib/python2.7/site-packages/salt/spm/__init__.py", line 161, in _pkgfiles_fun
    return self.pkgfiles['{0}.{1}'.format(self.files_prov, func)](*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/spm/pkgfiles/local.py", line 147, in install_file
    member.name = new_name.name.replace('{0}/'.format(package), '')
AttributeError: 'unicode' object has no attribute 'name'
```

**Expected behavior**
This should not raise an attribute error

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 
</details>

```
Salt Version:
           Salt: 3000.9
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
       M2Crypto: 0.31.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: 3.9.7
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug 13 2020, 02:51:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4
 
System Versions:
           dist: redhat 7.9 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1127.13.1.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.9 Maipo
```

**Additional context**
This can be fixed with something like

```
sed -i 's/new_name\.name/new_name/g' spm/pkgfiles/local.py
```

Also, it should be applied to all branches.

**Comment by sagetherage** [comment]
@recursiveMake oh I see what happened - we merged that PR into `develop` and did not port it to master or other branches, we should do that!

**Comment by sagetherage** [comment]
Also @recursiveMake we are no longer supporting python 2.
