### ISSUE TITLE
[BUG] core grains (e.g. oscodename) unknown when rendering pillars

### ISSUE THREAD

**Issue by rasstef** [saltstack/salt#60123]
**Description**
```
2021-05-03 13:42:43,966 [salt.utils.templates:274 ][ERROR   ][27782] Rendering exception occurred
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 501, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 46, in <module>
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'oscodename'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 261, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 508, in render_jinja_tmpl
    raise SaltRenderError("Jinja variable {}{}".format(exc, out), buf=tmplstr)
salt.exceptions.SaltRenderError: Jinja variable 'dict object' has no attribute 'oscodename'
2021-05-03 13:42:43,967 [salt.pillar      :888 ][CRITICAL][27782] Rendering SLS 'base.sensu.client' failed, render error:
Jinja variable 'dict object' has no attribute 'oscodename'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 501, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 46, in <module>
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'oscodename'
```

**Setup**
```
# cat /etc/salt/master
auto_accept: True
state_output: changes
state_verbose: True
state_top_saltenv: base
con_cache: True

fileserver_backend:
  - roots

file_roots:
  base:
    - /srv/salt
    - /srv/mo-salt/formulas/*/

pillar_source_merging_strategy: none

pillar_roots:
  base:
    - /srv/pillar

runner_dirs:
  - /srv/salt/_runners
worker_threads: 10
cli_summary: True
hash_type: sha256
log_level_logfile: info
keep_jobs: 1

reactor:
  - 'salt/auth':
    - /srv/reactor/auth.sls
  - 'salt/minion/*/start':
    - '/srv/reactor/initial_state_apply.sls'
```

```
# cat /etc/salt/minion
master: saltmaster001
log_level_logfile: info
hash_type: sha256
saltenv: base
pillarenv_from_saltenv: True
pillarenv: base
state_output_diff: True
state_output: changes
saltrun_json.filename: /tmp/salt_run.json
random_reauth_delay: 60
recon_default: 1000
recon_max: 59000
recon_randomize: True

grains:
  saltenv: base
  shell: /bin/bash

start_event_grains:
  - salt_initialized
  - salt_complete
  - salt_debug

mine_interval: 2
mine_functions:
  network.ip_addrs:
    - interface: ens3
  network.get_hostname: []
  openstack.server_list: []

use_superseded:
  - module.run

schedule:
  state_apply:
    function: state.apply
    returner: saltrun_json
    hours: 1
    splay: 1800
```

```
# cat /srv/reactor/initial_state_apply.sls

sync_grains:
  local.saltutil.sync_all:
    - tgt: {{ data['id'] }}

state_apply_1:
  local.state.apply:
    - tgt: {{ data['id'] }}
    - kwarg:
        queue: True
```

```
cat /srv/pillar/base/sensu/client/init.sls 

sensu:
  lookup:
    repos:
      name: deb http://repositories.es.ecg.tools/sensu {{ salt.grains.get('oscodename') }} main
      ...
```
      
**Steps to Reproduce the behavior**
In my setup it happens every time a minion is restarted. It does not happen with version 3002.1. I tried both ways to access grains:
- `salt.grains.get('oscodename')`
- `grains['oscodename']`

**Expected behavior**
pillars render grains without any problems. 

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
# salt --versions-report
Salt Version:
          Salt: 3002.6

Dependency Versions:
          cffi: Not Installed
      cherrypy: unknown
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: 0.28.3
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.6.1
        pygit2: 1.0.3
        Python: 3.8.5 (default, Jan 27 2021, 15:41:15)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-70-generic
        system: Linux
       version: Ubuntu 20.04 focal
  ```
</details>

**Additional context**
I would really appreciate if I could install 3002.6 as it provides essential security patches, so I really hope you'll find a solution for this problem. 3002.1 doesn't have this issue (I haven't tried 3002.5).

**Comment by rasstef** [comment]
**Hi, when can we expect this bug to be fixed? It prevents us installing the critical security patches provided by 3002.6.**

**Comment by rasstef** [comment]
To reproduce the bug just use the following simple configuration:

```# cat /etc/salt/master
fileserver_backend:
  - roots
file_roots:
  base:
    - /srv/salt
reactor:
  - 'salt/minion/*/start':
    - '/srv/reactor/initial_state_apply.sls'



# cat /etc/salt/minion
master: saltmaster001
saltenv: base
pillarenv_from_saltenv: True
pillarenv: base
start_event_grains:
  - salt_initialized
  - salt_complete
mine_interval: 2
mine_functions:
  network.ip_addrs:
    - interface: ens3
  network.get_hostname: []
grains:
  saltenv: base
  shell: /bin/bash
  salt_initialized: True
  salt_complete: True
  domain: mo-staging00-nonprod.ams1.cloud
  environment: staging
  region: ams1



# cat /srv/salt/top.sls
base:
  '*':
    - consul



# cat /srv/salt/consul/init.sls
{% from "consul/settings.jinja" import consul with context %}
/etc/consul/config.json:
  file.serialize:
    - user: consul
    - group: consul
    - mode: '0600'
    - dataset: {{ consul.config }}
    - formatter: json
    - makedirs: True
    - watch_in:
      - service: consul
    - require:
        - user: consul



# cat /srv/salt/consul/settings.jinja
{% set consul = salt['pillar.get']('consul', None) %}
{% if not consul %}
  {{ salt.test.exception("consul pillar data missing!") }}
{% endif %}
{% set pillar_cluster_name = consul['cluster']['name'] %}
{% set master_dict = salt['mine.get']('G@role:consul and G@cluster:{name}'.format(name=pillar_cluster_name), 'network.ip_addrs', 'compound') %}
{% set master_nodes = master_dict.keys() %}
{% if consul.auto_bootstrap -%}
    {% do consul.config.update({'retry_join': master_nodes}) %}
{% else %}
    {% do consul.config.update({'retry_join': consul.config.retry_join}) %}
{% endif %}
{% do consul.config.update({'retry_join_wan': consul.config.get('retry_join_wan', [])}) %}



# cat srv/salt/consul/files/config.json.sls
{% from "consul/settings.jinja" import consul with context %}
{{ consul.config | json(indent=4) }}



# cat /srv/pillar/top.sls
base:
  '*':
    - base.consul



# cat /srv/pillar/base/consul.sls
{%- set datacenter = [ grains['region'], grains['environment'] ] %}
{%- set domain = grains['domain'] %}
{%- set interface_address = grains['fqdn_ip4'] %}

consul:
  cluster:
    name: consul

  auto_bootstrap: false

  config:
    advertise_addr: "{{ interface_address }}"
    bind_addr: "0.0.0.0"
    client_addr: "0.0.0.0"
    datacenter: {{ datacenter|join("-") }}
    encrypt: XXXXXXXXXXXXX
    data_dir: /var/lib/consul
    domain: {{ domain }}
    retry_join_wan: []
    retry_join:
      - consul001.{{ domain }}
    enable_debug: false
    enable_syslog: true
    log_level: info
    server: false
    ui: false
``` 

Then install the packages and the error pops up immediately:

```
# apt install salt-common=3002.6+ds-1 salt-master=3002.6+ds-1 salt-minion=3002.6+ds-1
# salt-key -Ay
# cat /var/log/salt/master
2021-05-18 17:15:16,855 [salt.utils.parsers:1104][WARNING ][191500] Master received a SIGTERM. Exiting.
2021-05-18 17:15:30,052 [salt.utils.templates:274 ][ERROR   ][193494] Rendering exception occurred
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 501, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 3, in <module>
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'fqdn_ip4'
``` 

No such error with Saltstack `3002.1`.

This zip contains the config files list above:
[salt-bug.zip](https://github.com/saltstack/salt/files/6502498/salt-bug.zip)

**Comment by agraul** [comment]
This could be the same as https://github.com/saltstack/salt/issues/59545

**Comment by dwoz** [comment]
Not reproducible on 3006.x, 3007.x, 3008.x, or master.

Verified by constructing `salt.minion.Minion` on each branch with the reporter's static-grain config (`grains:` block plus `start_event_grains`) and inspecting `self.opts["grains"]` after `__init__`. On every branch, core grains (`oscodename`, `osrelease`, `fqdn_ip4`) are loaded and merged with static grains — 85–86 grains total — so the payload the minion would send to the master for pillar rendering contains the core grains. The reported `'dict object' has no attribute 'oscodename'` failure mode requires the opposite (static-only grains in the request).

Closing.
