### ISSUE TITLE
[BUG] module not loading redis cache

### ISSUE THREAD

**Issue by sagetherage** [saltstack/salt#60189]
**Description**
Hi..
I am trying to use redis cache as external minion data cache.. I have given the configuration in master as per the below format:

cache.redis.host: localhost
cache.redis.port: 6379
cache.redis.db: '0'
cache.redis.password: my pass
cache.redis.bank_prefix: #BANK
cache.redis.bank_keys_prefix: #BANKEYS
cache.redis.key_prefix: #KEY
cache.redis.separator: '@'

However, If i try to ping minion or try to access the grains info.. i get the following error:

```
$ sudo salt ‘*’ test.ping
[ERROR   ] An un-handled exception was caught by salt’s global exception handler:
KeyError: ‘redis.list’
Traceback (most recent call last):
  File “/usr/bin/salt”, line 11, in <module>
    load_entry_point(‘salt==3003’, ‘console_scripts’, ‘salt’)()
  File “/usr/lib/python3/dist-packages/salt/scripts.py”, line 539, in salt_main
    client.run()
  File “/usr/lib/python3/dist-packages/salt/cli/salt.py”, line 200, in run
    for full_ret in cmd_func(**kwargs):
  File “/usr/lib/python3/dist-packages/salt/client/__init__.py”, line 779, in cmd_cli
    **kwargs
  File “/usr/lib/python3/dist-packages/salt/client/__init__.py”, line 1610, in get_cli_event_returns
    self.opts
  File “/usr/lib/python3/dist-packages/salt/utils/minions.py”, line 634, in connected_ids
    search = self.cache.list(“minions”)
  File “/usr/lib/python3/dist-packages/salt/cache/__init__.py”, line 246, in list
    return self.modules[fun](bank, **self._kwargs)
  File “/usr/lib/python3/dist-packages/salt/loader.py”, line 1403, in __getitem__
    func = super().__getitem__(item)
  File “/usr/lib/python3/dist-packages/salt/utils/lazy.py”, line 108, in __getitem__
    raise KeyError(key)
KeyError: ‘redis.list’
Traceback (most recent call last):
  File “/usr/bin/salt”, line 11, in <module>
    load_entry_point(‘salt==3003’, ‘console_scripts’, ‘salt’)()
  File “/usr/lib/python3/dist-packages/salt/scripts.py”, line 539, in salt_main
    client.run()
  File “/usr/lib/python3/dist-packages/salt/cli/salt.py”, line 200, in run
    for full_ret in cmd_func(**kwargs):
  File “/usr/lib/python3/dist-packages/salt/client/__init__.py”, line 779, in cmd_cli
    **kwargs
  File “/usr/lib/python3/dist-packages/salt/client/__init__.py”, line 1610, in get_cli_event_returns
    self.opts
  File “/usr/lib/python3/dist-packages/salt/utils/minions.py”, line 634, in connected_ids
    search = self.cache.list(“minions”)
  File “/usr/lib/python3/dist-packages/salt/cache/__init__.py”, line 246, in list
    return self.modules[fun](bank, **self._kwargs)
  File “/usr/lib/python3/dist-packages/salt/loader.py”, line 1403, in __getitem__
    func = super().__getitem__(item)
  File “/usr/lib/python3/dist-packages/salt/utils/lazy.py”, line 108, in __getitem__
    raise KeyError(key)
KeyError: ‘redis.list’
```

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info).

**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

**Expected behavior**

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
PASTE HERE
```
</details>

**Additional context**
This means the module did not load. Pass `-l debug` when starting the minion. You should see information about the modules that did not load.
There might be some info there.
It could also be that the module does not work with the version of redis that you're currently using.

**Comment by s0undt3ch** [comment]
Issue submitted in https://saltstackcommunity.slack.com/archives/C7K04SEJC/p1620733260393800

Without actually setting up a redis server, I'm able to have salt load the module properly
<details>
<summary><tt>/etc/salt/master.d/redis.conf</tt></summary>
<pre>
cache: redis
cache.redis.host: localhost
cache.redis.port: 6379
cache.redis.db: '0'
cache.redis.password: my pass
cache.redis.bank_prefix: #BANK
cache.redis.bank_keys_prefix: #BANKEYS
cache.redis.key_prefix: #KEY
cache.redis.separator: '@'
</pre>
</details>

```
[DEBUG   ] LazyLoaded redis.init_kwargs
[ERROR   ] Cannot fetch the Redis cache key None@minions/9f7f6bc9fb90/data: Error 99 connecting to localhost:6379. Cannot assign requested address.
[DEBUG   ] LazyLoaded local_cache.prep_jid
[DEBUG   ] Using importlib_metadata to load entry points
[DEBUG   ] LazyLoaded nested.output
Exception occurred in runner cache.grains: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/cache/redis_cache.py", line 381, in fetch
    redis_value = redis_server.get(redis_key)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 1606, in get
    return self.execute_command('GET', name)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 99 connecting to localhost:6379. Cannot assign requested address.
```
So, on the salt side, it **does** look like it works.
Need more information from the original issue submitter.

**Comment by sagetherage** [comment]
User stated on 2021-MAY-18: Hi.. I was able to resolve it actually. There was a problem with redis python version. And there was a change in the way lists are read in redis ..
I updated it to the latest version and it worked..

Closing
