### ISSUE TITLE
[BUG] Ansiblegate is not usable after Salt 3001 release

### ISSUE THREAD

**Issue by s0undt3ch** [saltstack/salt#60207]
**Description**
Prior to the 3001 release of salt, the ansiblegate module worked by adding the ansible functions into the loaded salt module as a wrapper.

```
[root@b9dbd4ce1076 testing]# salt-call -l debug --local ansible.system.ping
[DEBUG   ] Missing configuration file: /etc/salt/minion
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: b9dbd4ce1076
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Missing configuration file: /etc/salt/minion
[DEBUG   ] Could not determine init system from command line: (bash)
[DEBUG   ] The `lspci` binary is not available on the system. GPU grains will not be available.
[DEBUG   ] LazyLoaded zfs.is_supported
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] Resolving Ansible modules
[DEBUG   ] Installing Ansible modules
[DEBUG   ] LazyLoaded ansible.system.ping
[DEBUG   ] LazyLoaded direct_call.execute

Passed invalid arguments: a bytes-like object is required, not 'str'.

Usage:
Available
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/salt/cli/caller.py", line 218, in call
    ret['return'] = self.minion.executors[fname](self.opts, data, func, args, kwargs)
  File "/usr/local/lib/python3.6/site-packages/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/salt/modules/ansiblegate.py", line 210, in _cmd
    return _caller.call(cmd_name, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/salt/modules/ansiblegate.py", line 167, in call
    stdin=proc_out.stdout, stdout=subprocess.PIPE, timeout=self.timeout)
  File "/usr/local/lib/python3.6/site-packages/salt/utils/timed_subprocess.py", line 36, in __init__
    self.stdin = salt.utils.stringutils.to_bytes(self.stdin.replace('\\n', '\n'))
TypeError: a bytes-like object is required, not 'str'
```
Although there's a traceback, the ansible modules were properly injected into Salt's `ansible` module.

Now, for Salt 3001+
```
[root@b9dbd4ce1076 testing]# salt-call -l debug --local ansible.system.ping
[DEBUG   ] Missing configuration file: /etc/salt/minion
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: b9dbd4ce1076
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Missing configuration file: /etc/salt/minion
[DEBUG   ] Elapsed time getting FQDNs: 0.11789274215698242 seconds
[DEBUG   ] Could not determine init system from command line: (bash)
[DEBUG   ] The `lspci` binary is not available on the system. GPU grains will not be available.
[DEBUG   ] LazyLoaded zfs.is_supported
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] Resolving Ansible modules
[DEBUG   ] Installing Ansible modules
[DEBUG   ] Missing configuration file: /etc/salt/minion
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: b9dbd4ce1076
[DEBUG   ] Could not LazyLoad boto3.assign_funcs: 'boto3.assign_funcs' is not available.
[DEBUG   ] Error loading module.boto3_elasticsearch: __init__ failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/salt/loader.py", line 1754, in _load_module
    module_init(self.opts)
  File "/usr/local/lib/python3.6/site-packages/salt/modules/boto3_elasticsearch.py", line 96, in __init__
    __utils__["boto3.assign_funcs"](__name__, "es")
  File "/usr/local/lib/python3.6/site-packages/salt/loader.py", line 1278, in __getitem__
    func = super(LazyLoader, self).__getitem__(item)
  File "/usr/local/lib/python3.6/site-packages/salt/utils/lazy.py", line 108, in __getitem__
    raise KeyError(key)
KeyError: 'boto3.assign_funcs'
[DEBUG   ] DSC: Only available on Windows systems
[DEBUG   ] Module PSGet: Only available on Windows systems
[DEBUG   ] Could not LazyLoad ansible.system.ping: 'ansible.system.ping' is not available.
'ansible.system.ping' is not available.
```

**Comment by s0undt3ch** [comment]
Broken in https://github.com/saltstack/salt/commit/92438882a94cbd4b1f1ec94eeda0bf1a35b98d27#diff-519146c38c0ed7bc961ffc5f408d3dd380abb8760d48e839743dbd38dc28ba15R323

Fixed locally. Will either submit a separate PR or will join it with the fix for https://github.com/saltstack/salt/issues/59792
