### ISSUE TITLE
[BUG] Unable to create aws ec2 instance salt cloud

### ISSUE THREAD

**Issue by nkrishnakishor** [saltstack/salt#60205]
**Description**
Unable to create aws ec2 instance with required details provided

**Setup**
Below are the require files under ```/etc/salt/cloud.providers.d/``` and ```/etc/salt/cloud.profiles.d/```

```
# /etc/salt/cloud.providers.d/aws.conf

ec2-us-west-2-private:
  minion:
    master: master-IP-Address
  id: HJGRYCILJLKJYG
  key: 'kdjgfsgm;woormgl/aserigjksjdhasdfgn'
  role_arn: arn:aws:iam::012345678910:role/SomeRoleName
  private_key: /etc/salt/test.pem
  keyname: test
  ssh_interface: private_ips
  location: us-east-1
  driver: ec2
  del_root_vol_on_destroy: True
  del_all_vol_on_destroy: True
  rename_on_destroy: True
```

```
#/etc/salt/cloud.profiles.d/aws.conf
  base_ec2:
    driver: ec2-us-east-1-private
    image: ami-5189a661
    size: t2.micro
    ssh_username: ubuntu
    tag: {"Environment": "Dev"}
    grains:
      environment: Dev
    sync_afte_install: grains
```

**Steps to Reproduce the behavior**
Below is the error while trying to spin the instance

```
[krishna@server ~]$ sudo salt-cloud -p base_ec2 ubuntu -l debug
[DEBUG   ] Reading configuration from /etc/salt/cloud
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: server.localhost.com
[DEBUG   ] Missing configuration file: /etc/salt/cloud.providers
[DEBUG   ] Including configuration from '/etc/salt/cloud.providers.d/aws.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers.d/aws.conf
[DEBUG   ] Missing configuration file: /etc/salt/cloud.profiles
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/aws.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/aws.conf
[ERROR   ] 'provider'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/parsers.py", line 196, in parse_args
    process_option_func()
  File "/usr/lib/python3.6/site-packages/salt/utils/parsers.py", line 553, in process_config_dir
    self.config.update(self.setup_config())
  File "/usr/lib/python3.6/site-packages/salt/utils/parsers.py", line 3500, in setup_config
    opts = config.cloud_config(self.get_config_file_path())
  File "/usr/lib/python3.6/site-packages/salt/config/__init__.py", line 2621, in cloud_config
    profiles_config = vm_profiles_config(profiles_config_path, providers_config)
  File "/usr/lib/python3.6/site-packages/salt/config/__init__.py", line 2752, in vm_profiles_config
    return apply_vm_profiles_config(providers, overrides, defaults)
  File "/usr/lib/python3.6/site-packages/salt/config/__init__.py", line 2779, in apply_vm_profiles_config
    if ":" in details["provider"]:
KeyError: 'provider'
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: '>=' not supported between instances of 'KeyError' and 'int'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/parsers.py", line 196, in parse_args
    process_option_func()
  File "/usr/lib/python3.6/site-packages/salt/utils/parsers.py", line 553, in process_config_dir
    self.config.update(self.setup_config())
  File "/usr/lib/python3.6/site-packages/salt/utils/parsers.py", line 3500, in setup_config
    opts = config.cloud_config(self.get_config_file_path())
  File "/usr/lib/python3.6/site-packages/salt/config/__init__.py", line 2621, in cloud_config
    profiles_config = vm_profiles_config(profiles_config_path, providers_config)
  File "/usr/lib/python3.6/site-packages/salt/config/__init__.py", line 2752, in vm_profiles_config
    return apply_vm_profiles_config(providers, overrides, defaults)
  File "/usr/lib/python3.6/site-packages/salt/config/__init__.py", line 2779, in apply_vm_profiles_config
    if ":" in details["provider"]:
KeyError: 'provider'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bin/salt-cloud", line 11, in <module>
    load_entry_point('salt==3003', 'console_scripts', 'salt-cloud')()
  File "/usr/lib/python3.6/site-packages/salt/scripts.py", line 511, in salt_cloud
    client.run()
  File "/usr/lib/python3.6/site-packages/salt/cloud/cli.py", line 48, in run
    self.parse_args()
  File "/usr/lib/python3.6/site-packages/salt/utils/parsers.py", line 3485, in parse_args
    return super().parse_args(args, values)
  File "/usr/lib/python3.6/site-packages/salt/utils/parsers.py", line 201, in parse_args
    process_option_func, traceback.format_exc(err)
  File "/usr/lib64/python3.6/traceback.py", line 167, in format_exc
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
  File "/usr/lib64/python3.6/traceback.py", line 121, in format_exception
    type(value), value, tb, limit=limit).format(chain=chain))
  File "/usr/lib64/python3.6/traceback.py", line 509, in __init__
    capture_locals=capture_locals)
  File "/usr/lib64/python3.6/traceback.py", line 338, in extract
    if limit >= 0:
TypeError: '>=' not supported between instances of 'KeyError' and 'int'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/parsers.py", line 196, in parse_args
    process_option_func()
  File "/usr/lib/python3.6/site-packages/salt/utils/parsers.py", line 553, in process_config_dir
    self.config.update(self.setup_config())
  File "/usr/lib/python3.6/site-packages/salt/utils/parsers.py", line 3500, in setup_config
    opts = config.cloud_config(self.get_config_file_path())
  File "/usr/lib/python3.6/site-packages/salt/config/__init__.py", line 2621, in cloud_config
    profiles_config = vm_profiles_config(profiles_config_path, providers_config)
  File "/usr/lib/python3.6/site-packages/salt/config/__init__.py", line 2752, in vm_profiles_config
    return apply_vm_profiles_config(providers, overrides, defaults)
  File "/usr/lib/python3.6/site-packages/salt/config/__init__.py", line 2779, in apply_vm_profiles_config
    if ":" in details["provider"]:
KeyError: 'provider'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bin/salt-cloud", line 11, in <module>
    load_entry_point('salt==3003', 'console_scripts', 'salt-cloud')()
  File "/usr/lib/python3.6/site-packages/salt/scripts.py", line 511, in salt_cloud
    client.run()
  File "/usr/lib/python3.6/site-packages/salt/cloud/cli.py", line 48, in run
    self.parse_args()
  File "/usr/lib/python3.6/site-packages/salt/utils/parsers.py", line 3485, in parse_args
    return super().parse_args(args, values)
  File "/usr/lib/python3.6/site-packages/salt/utils/parsers.py", line 201, in parse_args
    process_option_func, traceback.format_exc(err)
  File "/usr/lib64/python3.6/traceback.py", line 167, in format_exc
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
  File "/usr/lib64/python3.6/traceback.py", line 121, in format_exception
    type(value), value, tb, limit=limit).format(chain=chain))
  File "/usr/lib64/python3.6/traceback.py", line 509, in __init__
    capture_locals=capture_locals)
  File "/usr/lib64/python3.6/traceback.py", line 338, in extract
    if limit >= 0:
TypeError: '>=' not supported between instances of 'KeyError' and 'int'
```

**Expected behavior**
VM sould have been created in the AWS once the command ```sudo salt-cloud -p base_ec2 ubuntu -l debug``` was run

**Versions Report**
<details><summary>salt --versions-report</summary>

```
[krishna@server ~]$ salt --versions-report
Salt Version:
          Salt: 3003

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Mar 19 2021, 05:13:41)
  python-gnupg: Not Installed
        PyYAML: 3.12
         PyZMQ: 19.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: centos 8
        locale: UTF-8
       machine: x86_64
       release: 4.18.0-301.1.el8.x86_64
        system: Linux
       version: CentOS Stream 8

And **winrm version** winrm (0.4.1)

```
</details>

**Comment by OrangeDog** [comment]
The profile definition is supposed to contain a `provider` key. I think you've called it `driver` instead of some reason.

**Comment by nkrishnakishor** [comment]
@OrangeDog I have updated file under `profiles` as below 

```
#/etc/salt/cloud.profiles.d/aws.conf
  base_ec2:
    provider: ec2-us-east-1-private
    image: ami-5189a661
    size: t2.micro
    ssh_username: ubuntu
    tag: {"Environment": "Dev"}
    grains:
      environment: Dev
    sync_afte_install: grains
```
It is throwing error as below.
```
[krishna@server ~]$ sudo salt-cloud -p base_ec2 ubuntu
[ERROR   ] Profile base_ec2 is not defined
Error:
    Profile base_ec2 is not defined
```

**Comment by OrangeDog** [comment]
I'm guessing because you told it to use `ec2-us-east-1-private` but only defined `ec2-us-west-2-private`.

**Comment by nkrishnakishor** [comment]
Thanks @OrangeDog. It helped to rectify the issue..... able to spin the VM but its unable to establish the connection. Below is the error log, can you help on this or point to any reference doc about the issue. Moreover Salt is trying to SSH over instance private IP rather than public IP.

```
[DEBUG   ] Retrying connection to host 172.31.30.78 on port 22 (try 108)
[DEBUG   ] Caught exception in wait_for_port: timed out
[DEBUG   ] Retrying connection to host 172.31.30.78 on port 22 (try 109)
[DEBUG   ] Caught exception in wait_for_port: timed out
[DEBUG   ] Retrying connection to host 172.31.30.78 on port 22 (try 110)
[DEBUG   ] Caught exception in wait_for_port: timed out
[DEBUG   ] Retrying connection to host 172.31.30.78 on port 22 (try 111)
[DEBUG   ] Caught exception in wait_for_port: timed out
[DEBUG   ] Retrying connection to host 172.31.30.78 on port 22 (try 112)
[DEBUG   ] Caught exception in wait_for_port: timed out
[DEBUG   ] Retrying connection to host 172.31.30.78 on port 22 (try 113)
[DEBUG   ] Caught exception in wait_for_port: timed out
[DEBUG   ] Retrying connection to host 172.31.30.78 on port 22 (try 114)
[DEBUG   ] Caught exception in wait_for_port: timed out
[DEBUG   ] Retrying connection to host 172.31.30.78 on port 22 (try 115)
[DEBUG   ] Caught exception in wait_for_port: timed out
[DEBUG   ] Retrying connection to host 172.31.30.78 on port 22 (try 116)
[DEBUG   ] Caught exception in wait_for_port: timed out
[DEBUG   ] Retrying connection to host 172.31.30.78 on port 22 (try 117)
[DEBUG   ] Caught exception in wait_for_port: timed out
[DEBUG   ] Retrying connection to host 172.31.30.78 on port 22 (try 118)
[DEBUG   ] Caught exception in wait_for_port: timed out
[DEBUG   ] Retrying connection to host 172.31.30.78 on port 22 (try 119)
````
so on... I have checked the security group where all ports are allowed from default security group which was created along with the instance.

**Comment by garethgreenaway** [comment]
@nkrishnakishor It appears that salt-cloud is attempting to connect to the private IP address of the AWS instance and doesn't have the ability to connect.  You'll need to have AWS provide a public IP address for your instances and tell salt-cloud to use the public IP or use a VPN so that salt-cloud has access to the private IP.

**Comment by nkrishnakishor** [comment]
can u help me how to setup the requirements....any doc link towards that ?

**Comment by sagetherage** [comment]
[salt cloud ec2 docs](https://docs.saltproject.io/en/latest/ref/clouds/all/salt.cloud.clouds.ec2.html)

**Comment by sagetherage** [comment]
AWS has great documentation if that is what you mean, DuckDuckGo gave me this: https://docs.megaport.com/cloud/megaport/aws/aws-public-ip/ as one example

**Comment by sagetherage** [comment]
let myself or Gareth know if this doesn't help you by mention is in the comments, I am closing this issue for now.
