### ISSUE TITLE
[BUG] network.default_route: 'anycast' does not appear to be an IPv4 or IPv6 network

### ISSUE THREAD

**Issue by dbellavista** [saltstack/salt#60232]
**Description**
I have got an error (**ValueError: 'anycast' does not appear to be an IPv4 or IPv6 network**) when executing network.default_route:

<details><summary><code>salt minid network.default_route</code></summary>

```
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/salt/minion.py", line 1905, in _thread_return
        function_name, function_args, executors, opts, data
      File "/usr/lib/python3/dist-packages/salt/minion.py", line 1861, in _execute_job_function
        return_data = self.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/python3/dist-packages/salt/loader.py", line 1235, in __call__
        return self.loader.run(run_func, *args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/loader.py", line 2268, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "/usr/lib/python3/dist-packages/contextvars/__init__.py", line 38, in run
        return callable(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/loader.py", line 2283, in _run_as
        return _func_or_method(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/loader.py", line 1235, in __call__
        return self.loader.run(run_func, *args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/loader.py", line 2268, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "/usr/lib/python3/dist-packages/contextvars/__init__.py", line 38, in run
        return callable(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/loader.py", line 2283, in _run_as
        return _func_or_method(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/modules/network.py", line 1807, in default_route
        _routes = routes()
      File "/usr/lib/python3/dist-packages/salt/modules/network.py", line 1764, in routes
        routes_ = _ip_route_linux()
      File "/usr/lib/python3/dist-packages/salt/modules/network.py", line 609, in _ip_route_linux
        address_mask = convert_cidr(comps[0])
      File "/usr/lib/python3/dist-packages/salt/modules/network.py", line 1232, in convert_cidr
        cidr = calc_net(cidr)
      File "/usr/lib/python3/dist-packages/salt/modules/network.py", line 1255, in calc_net
        return __utils__["network.calc_net"](ip_addr, netmask)
      File "/usr/lib/python3/dist-packages/salt/loader.py", line 1235, in __call__
        return self.loader.run(run_func, *args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/loader.py", line 2268, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "/usr/lib/python3/dist-packages/contextvars/__init__.py", line 38, in run
        return callable(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/loader.py", line 2283, in _run_as
        return _func_or_method(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/utils/network.py", line 1185, in calc_net
        return str(ipaddress.ip_network(ipaddr, strict=False))
      File "/usr/lib/python3/dist-packages/salt/ext/ipaddress.py", line 108, in ip_network
        address)
    ValueError: 'anycast' does not appear to be an IPv4 or IPv6 network
```

</details>

**Setup**

**Steps to Reproduce the behavior**

**Expected behavior**
Should not throw

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3003
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: 4.4.1
         gitdb: 4.0.5
     gitpython: 3.1.13
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.8.5 (default, Jan 27 2021, 15:41:15)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: 3.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2
 
System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-73-generic
        system: Linux
       version: Ubuntu 20.04 focal

```
</details>

**Additional context**

**Comment by dmurphy18** [comment]
@dbellavista On a clean install running salt-call --local network.default_route encountered no problem on Ubuntu 20.04.2 (currently up to date).  Also had no issues on a Centos 7 machine running Salt 3003 too.

However on my own machine (Ubuntu 20.04.2 current) I did experience problems
```
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2268, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2283, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/utils/network.py", line 1185, in calc_net
    return str(ipaddress.ip_network(ipaddr, strict=False))
  File "/usr/lib/python3/dist-packages/salt/ext/ipaddress.py", line 107, in ip_network
    raise ValueError('%r does not appear to be an IPv4 or IPv6 network' %
ValueError: 'multicast' does not appear to be an IPv4 or IPv6 network
```

Given how much dev / testing I do, I removed Salt and reinstalled it to ensure I was really using Salt 3003, and encountered no problem with the command.
```
  696  apt-cache policy salt-minion
  698  apt-cache policy salt-common
  699  vim /etc/apt/sources.list
  700  apt remove salt-common salt-minion
  701  apt autoremove
  702  apt autoclean
  703  apt purge
  705  apt-get install salt-minion
```

Can you provide more context, ensure that the version of Salt running is from Salt Project (dpkg -S /usr/bin/salt-call), since I know that the Debian project's fork of Salt is sometimes confused as coming from the Salt Project (don't believe they are at 3003 yet, but best to check).
apt-cache policy salt* should provide that information.

I have played around with stopping, starting, running from a master
```
root@Unknown:/srv/salt# salt tu20 network.default_route
tu20:
    |_
      ----------
      addr_family:
          inet
      destination:
          0.0.0.0
      flags:
          UG
      gateway:
          192.168.0.1
      interface:
          enp0s3
      netmask:
          0.0.0.0
    |_
      ----------
      addr_family:
          inet6
      destination:
          ::/0
      flags:
          !n
      gateway:
          ::
      interface:
          lo
      netmask:
    |_
      ----------
      addr_family:
          inet6
      destination:
          ::/0
      flags:
          !n
      gateway:
          ::
      interface:
          lo
      netmask:
```
But have been unable to reproduce

From looking at the source code, use of 'multicast' and 'anycast' have to be coming from an underlying OS layer, as an unexpected value returned in response to a function call.  Wondering how current your Ubuntu 20.04 machine is ?, if there is some update which highlights the issue, since I updated both the test machine and mine before re-installing / ensuring Salt 3003 and if there was some underlying OS updates which affected this (I did have quite some updates).

Lastly could always re-install to ensure the code is accurate, similar to what I did: however would be interesting to see why the problem is occurring (if due to underlying package having issues, as outlined above). In my case, was unsure of salt-call version due to dev / test cycle hence re-installed to ensure I had what was shipping.

**Comment by dbellavista** [comment]
We were experiencing this problem recently on some minions (and now they are working only because we are patching di salt minion, we found the fix of `multicast` and added another `if` with `anycast`).

So, I'll try to reproduce it, but it may take a while. If it is of any help, recently an update of docker forced us to enable ipv6 on network interfaces (previously we kept it disabled). I don't know if it's the ipv6 or the docker installation itself that triggers the error.

Again, when I'll be able to make some tests I'll update the issue

**Comment by dmurphy18** [comment]
@dbellavista Would be interested in where you applied the fixes for mulitcast and anycast.  And interesting that you were using Docker and not a real machine or VM.  I used a real Ubuntu 20.04 on a laptop and a VirtualBox VM for Ubuntu 20.04, same for the Centos 7 machine (VM).

Interesting this was using a Docker container, can you supply any further details on the Docker containers used, versions etc., since while I could blame Docker configuration and claim real machine and VMs don't experience the problem, but too many people use containers today, hence would like to get to the bottom of the issue.

**Comment by dbellavista** [comment]
@dmurphy18 sorry I misspoke. The salt was running on a VM, but we are using salt also to install and run docker containers.

Here the state for patching (it was a very quick and dirty intervention I know :D )

<details><summary><code>init.sls</code></summary>

```
/root/network.patch:
  file.managed:
    - source: salt://patch/network.patch

Apply patchs:
  cmd.run:
    - name: |
        patch -t -u /usr/lib/python3/dist-packages/salt/modules/network.py -i /root/network.patch
    - require:
      - file: /root/network.patch
```

</details></summary>

<details><summary><code>network.patch</code></summary>

```
--- /usr/lib/python3/dist-packages/salt/modules/network.py      2021-03-24 22:53:25.000000000 +0100
+++ network.py  2021-05-21 20:02:54.813945202 +0200
@@ -529,6 +529,8 @@
         # to maintain output format
         if comps[0] == "unreachable":
             continue
+        if comps[0] == "anycast":
+            continue
 
         if comps[0] == "default":
             ip_interface = ""
@@ -572,6 +574,8 @@
         # to maintain output format
         if comps[0] == "unreachable":
             continue
+        if comps[0] == "anycast":
+            continue
 
         if comps[0] == "default":
             ip_interface = ""

```

</details></summary>

**Comment by dmurphy18** [comment]
Thanks for that info.  But your comment made me think, and we will be updating our standard bug report template to include info for real machine, VM, Docker, containerd, K8s, etc. esp. since containers are only going to get more popular with K8s.

Will dig further.

**Comment by dbellavista** [comment]
@dmurphy18 uh I haven't tried with table `all`. So the ipv4 routes are:

```
default via 192.168.3.251 dev eth0 proto static
192.168.3.0/24 dev eth0 proto kernel scope link src 192.168.3.235
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown
broadcast 127.0.0.0 dev lo table local proto kernel scope link src 127.0.0.1
local 127.0.0.0/8 dev lo table local proto kernel scope host src 127.0.0.1
local 127.0.0.1 dev lo table local proto kernel scope host src 127.0.0.1
broadcast 127.255.255.255 dev lo table local proto kernel scope link src 127.0.0.1
broadcast 192.168.3.0 dev eth0 table local proto kernel scope link src 192.168.3.235
local 192.168.3.235 dev eth0 table local proto kernel scope host src 192.168.3.235
broadcast 192.168.3.255 dev eth0 table local proto kernel scope link src 192.168.3.235
broadcast 172.17.0.0 dev docker0 table local proto kernel scope link src 172.17.0.1 linkdown
local 172.17.0.1 dev docker0 table local proto kernel scope host src 172.17.0.1
broadcast 172.17.255.255 dev docker0 table local proto kernel scope link src 172.17.0.1 linkdown
```

But the ipv6 table contains:

```
fe80::/64 dev ens192 proto kernel metric 256 pref medium
fe80::/64 dev ens160 proto kernel metric 256 pref medium
anycast fe80:: dev ens160 table local proto kernel metric 0 pref medium
anycast fe80:: dev ens192 table local proto kernel metric 0 pref medium
local fe80::250:56ff:fe9b:6ebf dev ens160 table local proto kernel metric 0 pref medium
local fe80::250:56ff:fe9b:e27f dev ens192 table local proto kernel metric 0 pref medium
ff00::/8 dev ens192 table local proto kernel metric 256 pref medium
ff00::/8 dev ens160 table local proto kernel metric 256 pref medium
```

So I guess it may have happened when we enabled ipv6.

**Comment by dmurphy18** [comment]
@dbellavista I believe that is where the issue is, esp. since **_anycast_** came in with IPv6, I also see **_multicast_** too
```
david@david-laptop2:~$ sudo ip -6 route show table all
[sudo] password for david: 
Sorry, try again.
[sudo] password for david: 
::1 dev lo proto kernel metric 256 pref medium
fe80::/64 dev enx3c18a040229d proto kernel metric 100 pref medium
fe80::/64 dev tun0 proto kernel metric 256 pref medium
fe80::/64 dev vboxnet0 proto kernel metric 256 pref medium
fe80::/64 dev docker0 proto kernel metric 256 linkdown pref medium
fe80::/64 dev wlp59s0 proto kernel metric 600 pref medium
local ::1 dev lo table local proto kernel metric 0 pref medium
local fe80::42:e5ff:fef3:ea4e dev docker0 table local proto kernel metric 0 pref medium
local fe80::800:27ff:fe00:0 dev vboxnet0 table local proto kernel metric 0 pref medium
local fe80::6c8d:66f8:230f:a81f dev enx3c18a040229d table local proto kernel metric 0 pref medium
local fe80::dd8e:db7f:b999:fc82 dev wlp59s0 table local proto kernel metric 0 pref medium
local fe80::f68b:1571:b435:88de dev tun0 table local proto kernel metric 0 pref medium
multicast ff00::/8 dev enx3c18a040229d table local proto kernel metric 256 pref medium
multicast ff00::/8 dev tun0 table local proto kernel metric 256 pref medium
multicast ff00::/8 dev vboxnet0 table local proto kernel metric 256 pref medium
multicast ff00::/8 dev wlp59s0 table local proto kernel metric 256 pref medium
multicast ff00::/8 dev docker0 table local proto kernel metric 256 linkdown pref medium
```
Will be able to fix this and add additional tests, and some other research to check if there is anything else missed with IPv6.

**Comment by dmurphy18** [comment]
Need to adjust the following code to allow for mutilcast, anycast, etc.
https://github.com/saltstack/salt/blob/5457218d86ebed772111954d061e332d7c30c0d7/salt/modules/network.py#L571-L575
