### ISSUE TITLE
[BUG] inotify beacon fails with AttributeError: 'list' object has no attribute 'get'

### ISSUE THREAD

**Issue by provonet** [saltstack/salt#60241]
**Description**
The inotify beacon fails after sending an event and spams the logfile with python stack traces.

**Setup**
```
beacons:
  enabled: true
  watch_important_files:
  - beacon_module: inotify
  - disable_during_state_run: true
  - files:
      /opt/newdir/do-not-touch:
        mask:
        - modify
```

**Steps to Reproduce the behavior**
1) salt minion1 beacons.add watch_important_files "[{'beacon_module': 'inotify'}, {'disable_during_state_run': true}, {'files': {'/opt/newdir/do-not-touch': {'mask': ['modify']}}}]"
2) modify /opt/newdir/do-not-touch

**Expected behavior**
the minion should not raise an error

**Screenshots**
```
2021-05-24 14:29:43,083 [salt.minion      :2947][CRITICAL][32837] The beacon errored: 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 2945, in handle_beacons
    beacons = self.process_beacons(self.functions)
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 512, in process_beacons
    return self.beacons.process(
  File "/usr/lib/python3/dist-packages/salt/beacons/__init__.py", line 107, in process
    self.beacons[close_str](b_config[mod])
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1235, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2268, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2283, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/beacons/inotify.py", line 370, in close
    beacon_name = config.get("_beacon_name", "inotify")
AttributeError: 'list' object has no attribute 'get'
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3003
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.8.5 (default, Jan 27 2021, 15:41:15)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2
 
System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-73-generic
        system: Linux
       version: Ubuntu 20.04 focal
```
</details>

**Additional context**

**Comment by provonet** [comment]
the following patch solves the reported bug:

```
--- inotify.py	2021-03-24 21:53:25.000000000 +0000
+++ /tmp/inotify.py	2021-05-24 15:26:24.761516777 +0000
@@ -366,9 +366,17 @@
     return ret
 
 
-def close(config):
+def _close(config):
     beacon_name = config.get("_beacon_name", "inotify")
     notifier = "{}.notifier".format(beacon_name)
     if notifier in __context__:
         __context__[notifier].stop()
         del __context__[notifier]
+
+def close(config):
+    if isinstance(config, list):
+        for _config in config:
+            _close(_config)
+    else:
+        _close(config)
+
```
but maybe config should always by treated as a list instead of a dict

**Comment by garethgreenaway** [comment]
@provonet Thanks for the report.  Unfortunately with the above steps I am unable to reproduce this, do you have more than one beacon configured or something else not specified above?

**Comment by garethgreenaway** [comment]
@provonet Never mind.  It was further back in the logs.

**Comment by garethgreenaway** [comment]
@provonet So this is definitely a bug, The configuration for the itnotify (and all beacons) should be a list, filled with dictionaries in most cases so we don't need to handle a situation where it isn't a list.
