### ISSUE TITLE
[BUG] salt-minion.service: main process exited, code=exited, status=1/FAILURE      TypeError: '>=' not supported between instances of 'OSError' and 'int'

### ISSUE THREAD

**Issue by dwicahyohph** [saltstack/salt#60330]
**Description**
I can't use salt-call command in one of minion in my dev, checked its status,  got this error:
```
[root@olndsaltminion02 ~]# systemctl status salt-minion
● salt-minion.service - The Salt Minion
   Loaded: loaded (/usr/lib/systemd/system/salt-minion.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2021-06-08 14:52:20 EST; 6min ago
     Docs: man:salt-minion(1)
           file:///usr/share/doc/salt/html/contents.html
           https://docs.saltstack.com/en/latest/contents.html
  Process: 23397 ExecStart=/usr/bin/salt-minion (code=exited, status=1/FAILURE)
 Main PID: 23397 (code=exited, status=1/FAILURE)

Jun 08 14:52:20 olndsaltminion02 salt-minion[23397]: File "/usr/lib64/python3.6/traceback.py", line 121, in format_exception
Jun 08 14:52:20 olndsaltminion02 salt-minion[23397]: type(value), value, tb, limit=limit).format(chain=chain))
Jun 08 14:52:20 olndsaltminion02 salt-minion[23397]: File "/usr/lib64/python3.6/traceback.py", line 509, in __init__
Jun 08 14:52:20 olndsaltminion02 salt-minion[23397]: capture_locals=capture_locals)
Jun 08 14:52:20 olndsaltminion02 salt-minion[23397]: File "/usr/lib64/python3.6/traceback.py", line 338, in extract
Jun 08 14:52:20 olndsaltminion02 salt-minion[23397]: if limit >= 0:
Jun 08 14:52:20 olndsaltminion02 salt-minion[23397]: TypeError: '>=' not supported between instances of 'OSError' and 'int'
Jun 08 14:52:20 olndsaltminion02 systemd[1]: salt-minion.service: main process exited, code=exited, status=1/FAILURE
Jun 08 14:52:20 olndsaltminion02 systemd[1]: Unit salt-minion.service entered failed state.
Jun 08 14:52:20 olndsaltminion02 systemd[1]: salt-minion.service failed.
[root@olndsaltminion02 ~]# 
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
[root@olndsaltminion02 ~]# yum info salt-minion
Loaded plugins: ulninfo
Installed Packages
Name        : salt-minion
Arch        : noarch
Version     : 3003
Release     : 1.el7
Size        : 72 k
Repo        : installed
From repo   : saltstack-repo
Summary     : Client component for Salt, a parallel remote execution system
URL         : http://saltstack.org/
License     : ASL 2.0
Description : The Salt minion is the agent component of Salt. It listens for instructions
            : from the master, runs jobs, and returns results back to the master.
            : Supports Python 3.

You have mail in /var/spool/mail/root
[root@olndsaltminion02 ~]#

```
</details>

**Comment by dwicahyohph** [comment]
I didnt do anything, first I just want to check the version using salt-call on cli. And then that kind of error happen..
[root@olndsaltmimion02 ~]# salt-call --local test.version

**Comment by dwicahyohph** [comment]
it is the same as above
```
[root@olndsaltminion02 ~]# salt-call --local test.version
[ERROR   ] [Errno 28] No space left on device: '/var/log/salt/minion'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/parsers.py", line 210, in parse_args
    mixin_after_parsed_func(self)
  File "/usr/lib/python3.6/site-packages/salt/utils/parsers.py", line 751, in __setup_logfile_logger_config
    verify_log_files([logfile], self.config["user"])
  File "/usr/lib/python3.6/site-packages/salt/utils/verify.py", line 166, in verify_log_files
    return verify_files(verify_logs_filter(files), user)
  File "/usr/lib/python3.6/site-packages/salt/utils/verify.py", line 211, in verify_files
    with salt.utils.files.fopen(fn_, "w"):
  File "/usr/lib/python3.6/site-packages/salt/utils/files.py", line 396, in fopen
    f_handle = open(*args, **kwargs)  # pylint: disable=resource-leakage
OSError: [Errno 28] No space left on device: '/var/log/salt/minion'
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: '>=' not supported between instances of 'OSError' and 'int'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/parsers.py", line 210, in parse_args
    mixin_after_parsed_func(self)
  File "/usr/lib/python3.6/site-packages/salt/utils/parsers.py", line 751, in __setup_logfile_logger_config
    verify_log_files([logfile], self.config["user"])
  File "/usr/lib/python3.6/site-packages/salt/utils/verify.py", line 166, in verify_log_files
    return verify_files(verify_logs_filter(files), user)
  File "/usr/lib/python3.6/site-packages/salt/utils/verify.py", line 211, in verify_files
    with salt.utils.files.fopen(fn_, "w"):
  File "/usr/lib/python3.6/site-packages/salt/utils/files.py", line 396, in fopen
    f_handle = open(*args, **kwargs)  # pylint: disable=resource-leakage
OSError: [Errno 28] No space left on device: '/var/log/salt/minion'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bin/salt-call", line 11, in <module>
    load_entry_point('salt==3003', 'console_scripts', 'salt-call')()
  File "/usr/lib/python3.6/site-packages/salt/scripts.py", line 449, in salt_call
    client.run()
  File "/usr/lib/python3.6/site-packages/salt/cli/call.py", line 22, in run
    self.parse_args()
  File "/usr/lib/python3.6/site-packages/salt/utils/parsers.py", line 215, in parse_args
    mixin_after_parsed_func, traceback.format_exc(err)
  File "/usr/lib64/python3.6/traceback.py", line 167, in format_exc
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
  File "/usr/lib64/python3.6/traceback.py", line 121, in format_exception
    type(value), value, tb, limit=limit).format(chain=chain))
  File "/usr/lib64/python3.6/traceback.py", line 509, in __init__
    capture_locals=capture_locals)
  File "/usr/lib64/python3.6/traceback.py", line 338, in extract
    if limit >= 0:
TypeError: '>=' not supported between instances of 'OSError' and 'int'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/parsers.py", line 210, in parse_args
    mixin_after_parsed_func(self)
  File "/usr/lib/python3.6/site-packages/salt/utils/parsers.py", line 751, in __setup_logfile_logger_config
    verify_log_files([logfile], self.config["user"])
  File "/usr/lib/python3.6/site-packages/salt/utils/verify.py", line 166, in verify_log_files
    return verify_files(verify_logs_filter(files), user)
  File "/usr/lib/python3.6/site-packages/salt/utils/verify.py", line 211, in verify_files
    with salt.utils.files.fopen(fn_, "w"):
  File "/usr/lib/python3.6/site-packages/salt/utils/files.py", line 396, in fopen
    f_handle = open(*args, **kwargs)  # pylint: disable=resource-leakage
OSError: [Errno 28] No space left on device: '/var/log/salt/minion'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bin/salt-call", line 11, in <module>
    load_entry_point('salt==3003', 'console_scripts', 'salt-call')()
  File "/usr/lib/python3.6/site-packages/salt/scripts.py", line 449, in salt_call
    client.run()
  File "/usr/lib/python3.6/site-packages/salt/cli/call.py", line 22, in run
    self.parse_args()
  File "/usr/lib/python3.6/site-packages/salt/utils/parsers.py", line 215, in parse_args
    mixin_after_parsed_func, traceback.format_exc(err)
  File "/usr/lib64/python3.6/traceback.py", line 167, in format_exc
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
  File "/usr/lib64/python3.6/traceback.py", line 121, in format_exception
    type(value), value, tb, limit=limit).format(chain=chain))
  File "/usr/lib64/python3.6/traceback.py", line 509, in __init__
    capture_locals=capture_locals)
  File "/usr/lib64/python3.6/traceback.py", line 338, in extract
    if limit >= 0:
TypeError: '>=' not supported between instances of 'OSError' and 'int'
[root@olndsaltminion02 ~]#
```

**Comment by dwicahyohph** [comment]
I found out the space of /var/log is full...
~~~
[root@olndsaltminion02 ~]# df -h
Filesystem                          Size  Used Avail Use% Mounted on
/dev/mapper/var_log        6.0G  6.0G   20K 100% /var/log
[root@olndsaltminion02 ~]# 
~~~
deleted some files, the issue solved.

closed this ticket.

**Comment by OrangeDog** [comment]
Reopening because there's still a bug here.

`traceback.format_exc` does not take an exception as its first argument.

**Comment by dwicahyohph** [comment]
I found another error, but this time, no mounted directories are full, I dont exactly why this generate error...
~~~
[root@oln3eairest03 etc]# salt-minion --version
salt-minion 3003
[root@oln3eairest03 etc]# salt-call --local test.version
[ERROR   ] 'ascii' codec can't decode byte 0xc2 in position 538: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/parsers.py", line 196, in parse_args
    process_option_func()
  File "/usr/lib/python3.6/site-packages/salt/utils/parsers.py", line 553, in process_config_dir
    self.config.update(self.setup_config())
  File "/usr/lib/python3.6/site-packages/salt/utils/parsers.py", line 3011, in setup_config
    self.get_config_file_path(), cache_minion_id=True
  File "/usr/lib/python3.6/site-packages/salt/config/__init__.py", line 2213, in minion_config
    overrides, defaults, cache_minion_id=cache_minion_id, minion_id=minion_id
  File "/usr/lib/python3.6/site-packages/salt/config/__init__.py", line 3641, in apply_minion_config
    opts["id"], using_ip_for_id = get_id(opts, cache_minion_id=cache_minion_id)
  File "/usr/lib/python3.6/site-packages/salt/config/__init__.py", line 3517, in get_id
    newid = salt.utils.network.generate_minion_id()
  File "/usr/lib/python3.6/site-packages/salt/utils/network.py", line 217, in generate_minion_id
    ret = salt.utils.stringutils.to_unicode(_generate_minion_id().first())
  File "/usr/lib/python3.6/site-packages/salt/utils/network.py", line 195, in _generate_minion_id
    for line in f_hdl:
  File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 538: ordinal not in range(128)
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: '>=' not supported between instances of 'UnicodeDecodeError' and 'int'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/parsers.py", line 196, in parse_args
    process_option_func()
  File "/usr/lib/python3.6/site-packages/salt/utils/parsers.py", line 553, in process_config_dir
    self.config.update(self.setup_config())
  File "/usr/lib/python3.6/site-packages/salt/utils/parsers.py", line 3011, in setup_config
    self.get_config_file_path(), cache_minion_id=True
  File "/usr/lib/python3.6/site-packages/salt/config/__init__.py", line 2213, in minion_config
    overrides, defaults, cache_minion_id=cache_minion_id, minion_id=minion_id
  File "/usr/lib/python3.6/site-packages/salt/config/__init__.py", line 3641, in apply_minion_config
    opts["id"], using_ip_for_id = get_id(opts, cache_minion_id=cache_minion_id)
  File "/usr/lib/python3.6/site-packages/salt/config/__init__.py", line 3517, in get_id
    newid = salt.utils.network.generate_minion_id()
  File "/usr/lib/python3.6/site-packages/salt/utils/network.py", line 217, in generate_minion_id
    ret = salt.utils.stringutils.to_unicode(_generate_minion_id().first())
  File "/usr/lib/python3.6/site-packages/salt/utils/network.py", line 195, in _generate_minion_id
    for line in f_hdl:
  File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 538: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bin/salt-call", line 11, in <module>
    load_entry_point('salt==3003', 'console_scripts', 'salt-call')()
  File "/usr/lib/python3.6/site-packages/salt/scripts.py", line 449, in salt_call
    client.run()
  File "/usr/lib/python3.6/site-packages/salt/cli/call.py", line 22, in run
    self.parse_args()
  File "/usr/lib/python3.6/site-packages/salt/utils/parsers.py", line 201, in parse_args
    process_option_func, traceback.format_exc(err)
  File "/usr/lib64/python3.6/traceback.py", line 167, in format_exc
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
  File "/usr/lib64/python3.6/traceback.py", line 121, in format_exception
    type(value), value, tb, limit=limit).format(chain=chain))
  File "/usr/lib64/python3.6/traceback.py", line 509, in __init__
    capture_locals=capture_locals)
  File "/usr/lib64/python3.6/traceback.py", line 338, in extract
    if limit >= 0:
TypeError: '>=' not supported between instances of 'UnicodeDecodeError' and 'int'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/parsers.py", line 196, in parse_args
    process_option_func()
  File "/usr/lib/python3.6/site-packages/salt/utils/parsers.py", line 553, in process_config_dir
    self.config.update(self.setup_config())
  File "/usr/lib/python3.6/site-packages/salt/utils/parsers.py", line 3011, in setup_config
    self.get_config_file_path(), cache_minion_id=True
  File "/usr/lib/python3.6/site-packages/salt/config/__init__.py", line 2213, in minion_config
    overrides, defaults, cache_minion_id=cache_minion_id, minion_id=minion_id
  File "/usr/lib/python3.6/site-packages/salt/config/__init__.py", line 3641, in apply_minion_config
    opts["id"], using_ip_for_id = get_id(opts, cache_minion_id=cache_minion_id)
  File "/usr/lib/python3.6/site-packages/salt/config/__init__.py", line 3517, in get_id
    newid = salt.utils.network.generate_minion_id()
  File "/usr/lib/python3.6/site-packages/salt/utils/network.py", line 217, in generate_minion_id
    ret = salt.utils.stringutils.to_unicode(_generate_minion_id().first())
  File "/usr/lib/python3.6/site-packages/salt/utils/network.py", line 195, in _generate_minion_id
    for line in f_hdl:
  File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 538: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bin/salt-call", line 11, in <module>
    load_entry_point('salt==3003', 'console_scripts', 'salt-call')()
  File "/usr/lib/python3.6/site-packages/salt/scripts.py", line 449, in salt_call
    client.run()
  File "/usr/lib/python3.6/site-packages/salt/cli/call.py", line 22, in run
    self.parse_args()
  File "/usr/lib/python3.6/site-packages/salt/utils/parsers.py", line 201, in parse_args
    process_option_func, traceback.format_exc(err)
  File "/usr/lib64/python3.6/traceback.py", line 167, in format_exc
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
  File "/usr/lib64/python3.6/traceback.py", line 121, in format_exception
    type(value), value, tb, limit=limit).format(chain=chain))
  File "/usr/lib64/python3.6/traceback.py", line 509, in __init__
    capture_locals=capture_locals)
  File "/usr/lib64/python3.6/traceback.py", line 338, in extract
    if limit >= 0:
TypeError: '>=' not supported between instances of 'UnicodeDecodeError' and 'int'
~~~

**Comment by OrangeDog** [comment]
@dwicahyohph that's an entirely separate issue.

> 'ascii' codec can't decode byte 0xc2 in position 538

You have non-ascii characters in one of these files:
-  /etc/hostname
-  /etc/nodename
-  /etc/hosts
- %WINDIR%\system32\drivers\etc\hosts
