### ISSUE TITLE
[BUG] salt-ssh python 3.7 contextvars issue

### ISSUE THREAD

**Issue by gray380** [saltstack/salt#60331]
**Description**
Hello,

The following error has appeared when I try to run the test.ping:

```
salt-ssh 'ops*' test.ping
ops-c-admin:
    ----------
    retcode:
        1
    stderr:
        Traceback (most recent call last):
          File "/var/tmp/.sadm_4f1a73_salt/salt-call", line 27, in <module>
            salt_call()
          File "/var/tmp/.sadm_4f1a73_salt/pyall/salt/scripts.py", line 437, in salt_call
            import salt.cli.call
          File "/var/tmp/.sadm_4f1a73_salt/pyall/salt/cli/call.py", line 6, in <module>
            import salt.cli.caller
          File "/var/tmp/.sadm_4f1a73_salt/pyall/salt/cli/caller.py", line 14, in <module>
            import salt.loader
          File "/var/tmp/.sadm_4f1a73_salt/pyall/salt/loader.py", line 7, in <module>
            import contextvars
          File "/var/tmp/.sadm_4f1a73_salt/py3/contextvars.py", line 1, in <module>
            from _contextvars import Context, ContextVar, Token, copy_context
```

Seems that I have to apply the following [fix](https://docs.saltproject.io/en/master/topics/releases/3003.1.html) but I didn't find how to apply it.

**Setup**
Initial salt-ssh setup :

```
virtualenv venv
source venv/bin/activate
pip install salt-ssh
```

**Versions Report**
<details><summary>salt --versions-report</summary>

```
 Salt Version:
          Salt: 3003
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.0.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.10.1
        pygit2: Not Installed
        Python: 3.7.10 (default, Jun  3 2021, 07:40:26)
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 22.1.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: solus 4.2 fortitude
        locale: UTF-8
       machine: x86_64
       release: 5.11.22-180.current
        system: Linux
       version: Solus 4.2 fortitude
```
</details>

**Additional context**
```
venv  ~  salt-ssh  pip list
Package       Version
------------- ---------
certifi       2021.5.30
chardet       4.0.0
contextvars   2.4
distro        1.5.0
idna          2.10
immutables    0.15
Jinja2        3.0.1
MarkupSafe    2.0.1
msgpack       1.0.2
pip           21.1.2
pycryptodomex 3.10.1
PyYAML        5.4.1
pyzmq         22.1.0
requests      2.25.1
salt-ssh      3003
setuptools    57.0.0
urllib3       1.26.5
wheel         0.36.2

```

**Comment by sagetherage** [comment]
@gray380 we can't really help with applying a fixing to your environment since we have no context for your setup and it puts us in an odd situation to assume liability, but the fix will be released soon in v3003.1 - the release date was set today 2021-JUN-23, thank you!
