### ISSUE TITLE
[BUG] MySQL Minion Cache isn't loaded

### ISSUE THREAD

**Issue by Linuturk** [saltstack/salt#60375]
**Description**
I've configured the external minion cache for my salt master and it isn't being loaded on startup of the service. No minion data is being sent to the database.

**Setup**

Minion cache config:

```
cache: mysql
mysql.database: 'salt'
mysql.table_name: 'minion_cache'
mysql.host: 'myhost'
mysql.user: 'myuser'
mysql.port: 3306
mysql.ssl_ca: None
mysql.ssl_cert: None
mysql.ssl_key: None
mysql.password: 'changeme'
```

**Steps to Reproduce the behavior**
Configure the MySQL minion cache according to the docs: https://docs.saltproject.io/en/latest/ref/cache/all/salt.cache.mysql_cache.html#module-salt.cache.mysql_cache 

Restart salt-master and check debug logs. No indication anywhere the cache system is loading.

**Expected behavior**
I'd expect the cache to load and attempt to send data to the database.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3003
Dependency Versions:
          cffi: 1.11.5
      cherrypy: unknown
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: 2.0.3
     gitpython: 2.1.8
        Jinja2: 2.10
       libgit2: 0.26.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: 1.3.10
     pycparser: 2.18
      pycrypto: 2.6.1
  pycryptodome: 3.4.7
        pygit2: 0.26.2
        Python: 3.6.9 (default, Jan 26 2021, 15:33:00)
  python-gnupg: 0.4.1
        PyYAML: 3.12
         PyZMQ: 17.1.2
         smmap: 2.0.3
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.5
```
</details>

**Comment by garethgreenaway** [comment]
@Linuturk Thanks for the report.  I was able to reproduce this and then noticed that restarting the Salt minion as well caused the Salt master to attempt to send information along to the MySQL cache.  I did run into a different issue that appears to be a more serious bug:
```python
[ERROR   ] Error in function _pillar:
Traceback (most recent call last):
  File "/home/gareth/code/salt/salt/master.py", line 1935, in run_func
    ret = getattr(self, func)(load)
  File "/home/gareth/code/salt/salt/master.py", line 1635, in _pillar
    self.masterapi.cache.store(
  File "/home/gareth/code/salt/salt/cache/__init__.py", line 158, in store
    return self.modules[fun](bank, key, data, **self._kwargs)
  File "/home/gareth/code/salt/salt/loader.py", line 1241, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/home/gareth/code/salt/salt/loader.py", line 2274, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/home/gareth/code/salt/salt/loader.py", line 2289, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/home/gareth/code/salt/salt/cache/mysql_cache.py", line 185, in store
    _init_client()
  File "/home/gareth/code/salt/salt/cache/mysql_cache.py", line 171, in _init_client
    for k, v in _mysql_kwargs.items():
RuntimeError: dictionary changed size during iteration
```

**Comment by dwoz** [comment]
The mysql_cache RuntimeError ("dictionary changed size during iteration") from @garethgreenaway's comment was fixed in #60447 (merged 2021-08-17, commit 5e6f2d69600), and that fix is present on 3006.x, 3007.x, 3008.x, and master.

The original "cache isn't loading on master startup" symptom is expected behavior: the cache loader is lazy — mysql_cache only initializes (and logs `mysql_cache: Setting up client with params`) on the first `store`/`fetch` call, which happens when a minion actually reports pillar/grain data, not at master start.

Closing as fixed. Reopen if the RuntimeError still reproduces on a supported version.
