### ISSUE TITLE
[BUG] Python client API salt.cloud.CloudClient fails with FileNotFoundError when run from reactor

### ISSUE THREAD

**Issue by ggiesen** [saltstack/salt#60377]
**Description**
A python reactor script for `salt/cloud/*/created` no longer workers on 3003. It fails with a `FileNotFoundError`:

```
Process SyncManager-4:496:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.6/multiprocessing/managers.py", line 539, in _run_server
    server = cls._Server(registry, address, authkey, serializer)
  File "/usr/lib64/python3.6/multiprocessing/managers.py", line 139, in __init__
    self.listener = Listener(address=address, backlog=16)
  File "/usr/lib64/python3.6/multiprocessing/connection.py", line 442, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/usr/lib64/python3.6/multiprocessing/connection.py", line 580, in __init__
    self._socket.bind(address)
FileNotFoundError: [Errno 2] No such file or directory
[ERROR   ] Failed to render "/var/cache/salt/master/files/base/reactor/cloud_created.sls": 
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/reactor.py", line 90, in render_reaction
    res = self.render_template(fn_, tag=tag, data=data)
  File "/usr/lib/python3.6/site-packages/salt/state.py", line 387, in render_template
    **kwargs
  File "/usr/lib/python3.6/site-packages/salt/template.py", line 99, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 1241, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 2276, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
    return callable(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 2291, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/renderers/py.py", line 153, in render
    tmp_data.get("data", "Unknown render error in py renderer")
salt.exceptions.SaltRenderError: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 697, in py
    data = mod.run()
  File "/var/cache/salt/master/files/base/reactor/cloud_created.sls", line 13, in run
    vmware_data = cclient.action(fun="show_instance", names=[data["name"]])
  File "/usr/lib/python3.6/site-packages/salt/cloud/__init__.py", line 486, in action
    return mapper.do_action(names, kwargs)
  File "/usr/lib/python3.6/site-packages/salt/cloud/__init__.py", line 1430, in do_action
    for alias, drivers in self.map_providers_parallel().items():
  File "/usr/lib/python3.6/site-packages/salt/cloud/__init__.py", line 690, in map_providers_parallel
    _run_parallel_map_providers_query, multiprocessing_data, pool=pool
  File "/usr/lib/python3.6/site-packages/salt/cloud/__init__.py", line 142, in enter_mainloop
    manager = multiprocessing.Manager()
  File "/usr/lib64/python3.6/multiprocessing/context.py", line 56, in Manager
    m.start()
  File "/usr/lib64/python3.6/multiprocessing/managers.py", line 517, in start
    self._address = reader.recv()
  File "/usr/lib64/python3.6/multiprocessing/connection.py", line 254, in recv
    buf = self._recv_bytes()
  File "/usr/lib64/python3.6/multiprocessing/connection.py", line 411, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib64/python3.6/multiprocessing/connection.py", line 387, in _recv
    raise EOFError
EOFError
```

**Setup**
/etc/salt/master.d/reactor.conf:
```
  - 'salt/cloud/*/created':
    - 'salt://reactor/cloud_created.sls'

```
salt://reactor/cloud_created.sls:

```
#!py

import pprint

from salt.cloud import CloudClient

def run():
    """
    Run the reactor
    """

    cclient = CloudClient(path="/etc/salt/cloud")
    vmware_data = cclient.action(fun="show_instance", names=[data["name"]])
    pprint.pprint(vmware_data)
```

**Steps to Reproduce the behavior**
`# salt-run event.send salt/cloud/testvm/created '{"name": "testvm"}'`

**Expected behavior**
Print VM data

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3003

Dependency Versions:
          cffi: 1.14.0
      cherrypy: unknown
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.2
       libgit2: 1.0.1
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: 1.3.0
        Python: 3.6.8 (default, Aug 24 2020, 17:57:11)
  python-gnupg: 0.4.6
        PyYAML: 5.3.1
         PyZMQ: 19.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: centos 8
        locale: UTF-8
       machine: x86_64
       release: 4.18.0-240.22.1.el8_3.x86_64
        system: Linux
       version: CentOS Linux 8
```
</details>

**Additional context**
Previously worked on 3001.7

**Comment by ggiesen** [comment]
Note the same script run locally (not from reactor) runs without issue.

**Comment by Ch3LL** [comment]
I have not been able to replicate this on the head of master or version 3003. It prints the vm data for me. 

Are you still running into this issue on the latest release of Salt?

**Comment by Ch3LL** [comment]
bump ^

**Comment by ggiesen** [comment]
This was at $dayjob-1 and I no longer have access to the python script that was the issue (and try to avoid writing reactor scripts in python since I don't want to be the only person supporting them) so I'm going to close this issue.
