### ISSUE TITLE
[BUG] TornadoTimeoutError cannot be caught

### ISSUE THREAD

**Issue by OrangeDog** [saltstack/salt#60391]
**Description**

> Exception ignored in: <generator object IPCMessageSubscriber._read at 0x7fa20dfa1040>
> Traceback (most recent call last):
>    File "/usr/lib/python3/dist-packages/salt/transport/ipc.py", line 695, in _read
> TypeError: catching classes that do not inherit from BaseException is not allowed

https://github.com/saltstack/salt/blob/v3003/salt/transport/ipc.py#L695:
```py
except TornadoTimeoutError:
    # In the timeout case, just return None.
    # Keep 'self._read_stream_future' alive.
    ret = None
```

**Steps to Reproduce the behavior**
Unsure. Happened once when I Ctrl-c a `salt` job.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3003

Dependency Versions:
          cffi: 1.14.5
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.10.1
       libgit2: 1.1.0
      M2Crypto: 0.31.0
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: 1.5.0
        Python: 3.8.5 (default, May 27 2021, 13:30:53)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-74-generic
        system: Linux
       version: Ubuntu 20.04 focal
```
</details>

**Comment by OrangeDog** [comment]
Reopening as this error still exists. The catch blocks in `ipc.py` do not work.

Salt 3004 after Ctrl+C a `salt-run state.event`:
```
Exception ignored in: <generator object IPCMessageSubscriber._read at 0x7fb677c94eb0>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/transport/ipc.py", line 702, in _read
TypeError: catching classes that do not inherit from BaseException is not allowed
```
