### ISSUE TITLE
salt-ssh in state.orch

### ISSUE THREAD

**Issue by alan-cugler** [saltstack/salt#60395]
**Description**
I can not find any clear examples of salt-ssh being enacted from state.orch states. There is code in place that is suppose to expose salt-ssh to salt-api and salt-runners with these two pieces with one wrapping another:
- [salt-ssh runner docs](https://docs.saltproject.io/en/latest/ref/runners/all/salt.runners.ssh.html)
- [salt-ssh runner code](https://github.com/saltstack/salt/blob/master/salt/runners/ssh.py)
- [ssh client docs](https://docs.saltproject.io/en/latest/ref/clients/index.html#salt.client.ssh.client.SSHClient.cmd)
- [ssh client code](https://github.com/saltstack/salt/blob/c59a559b03734fba58d046b2d7577b9d87f3fd57/salt/client/ssh/client.py#L42)

**Tests and Attempts**
```yaml
# This one is using the ssh.cmd runner but it isn't working with kwarg(I attempted multiple variations),
# and if I remove kwarg the tgt field says I have inputted multiple values.
system_update:
  salt.runner:
    - name: ssh.cmd
    - tgt: saltmaster01
    - fun: test.version
    - arg:
      - i
    - kwarg: {'priv':'/root/.ssh/id_rsa'}
 
# This is the orchestration equivalent to cmd.run for when you can't get the built in salt way to work.
system_test:
  salt.runner:
    - name: salt.cmd
    - arg:
      - cmd.run
      - salt-ssh -i --priv=/root/.ssh/id_rsa 'saltmaster01' test.version
```

** salt.cmd runner**
I stumbled across the salt.cmd syntax from a comment under this [issue](https://github.com/saltstack/salt/issues/38977).

** Request **
- So I am having trouble with the `tgt` field and passing `arg` and `kwarg` successfully. Keep in mind I have tested all of the roster file and salt-ssh command in terminal before trying to graph it to state.orch.
```bash
$ salt-ssh -i --priv=/root/.ssh/id_rsa saltmaster01 test.version
```

**Comment by alan-cugler** [comment]
Oh man, if I got wayne assigned then I'm in good hands!

**Comment by waynew** [comment]
Thanks for the vote of confidence :slightly_smiling_face: Just started looking into this to figure things out, got a master/minion/ssh server running, and I can run a `salt-ssh sshd-box test.version` and get my result. So that's very good. Tomorrow morning I *should* be able to figure out how to use orch & what-not :upside_down_face:

**Comment by waynew** [comment]
@alan-cugler looks like the (not very amazingly documented) `ssh: True` option in orchestration should do what we're after:

```
[root@33a4d91aab03 testing]# cat /srv/salt/orch/blerp.sls 
test.version:
  salt.function:
    - tgt: '*'


other thing:
  salt.function:
    - tgt: sshd
    - ssh: True
    - name: test.version


another thing:
  salt.function:
    - tgt: sshd
    - ssh: True
    - name: cmd.run
    - arg:
       - whoami
```

Does that sort of thing work for what you were trying to do?

**Comment by alan-cugler** [comment]
So I tried out your code and wasn't able to get the syntax to work when `ssh: True` was part of the orchestration state.
Variations I've tried:
```YAML
# Adding the needed salt-ssh flags
testing_ssh_orch:
  salt.function:
    - tgt: saltmaster01
    - ssh: True
    - name: test.version
    - arg:
      - i
    - kwarg: {'--priv':'/root/.ssh/id_rsa'}

# Attempting with as close to your code as possible
testing_ssh_orch2:
  salt.function:
    - tgt: saltmaster01
    - ssh: True
    - name: test.version
```
The persisting error:
```BASH
[root@supermaster01 orch]# salt-run state.orch orch.super
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/state.py", line 2172, in call
    *cdata["args"], **cdata["kwargs"]
  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 1235, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 2268, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
    return callable(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 2283, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 2316, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/states/saltmod.py", line 563, in function
    m_ret = mdata["ret"]
KeyError: 'ret'

supermaster01_master:
----------
          ID: testing_ssh_orch
    Function: salt.function
        Name: test.version
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3.6/site-packages/salt/state.py", line 2172, in call
                  *cdata["args"], **cdata["kwargs"]
                File "/usr/lib/python3.6/site-packages/salt/loader.py", line 1235, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/loader.py", line 2268, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/usr/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
                  return callable(*args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/loader.py", line 2283, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/loader.py", line 2316, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/states/saltmod.py", line 563, in function
                  m_ret = mdata["ret"]
              KeyError: 'ret'
     Started: 15:50:03.299466
    Duration: 514.5 ms
     Changes:   

Summary for supermaster01_master
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time: 514.500 ms
```

**Comment by alan-cugler** [comment]
More context (though not sure it will help), I am using salt-ssh to provision salt-minions to new VMs in the cloud. A ssh key is being provided to salt-ssh for accessing. I am using orchestration to layer a full provisioning with first salt, then applications, then integration across architecture.

Could you provided a link for the ssh:True docs you looked at, its such a common word combo in the docs I could guess which one you are looking at.

**Comment by waynew** [comment]
It's almost a footnote in https://docs.saltproject.io/en/latest/ref/states/all/salt.states.saltmod.html#salt.states.saltmod.function :thinking:

**Comment by waynew** [comment]
Looks like that error is showing up here:
```
    for minion, mdata in cmd_ret.items():
        m_ret = False
        if mdata.get("retcode"):
            func_ret["result"] = False
            fail.add(minion)
        if mdata.get("failed", False):
            m_func = False
        else:
            if "return" in mdata and "ret" not in mdata:
                mdata["ret"] = mdata.pop("return")
            m_ret = mdata["ret"]
```

Kinda looks like mdata has no `['ret']` or `'return'`. I'm actually not a fan of that line, seems like it would be better served as something like

```
m_ret = mdata.get('ret') or mdata.get('return')
```
(Could be `m_ret = mdata.get('ret', mdata.get('return'))` - not a huge difference, the former just skips the 2nd get while the latter always does 2x .get calls)

Not sure if that would fix the problem here, though :thinking:

**Comment by dwoz** [comment]
The reported `KeyError: 'ret'` in `saltmod.function` at `m_ret = mdata['ret']` was fixed by de052e71353 (2015-06-10), which added the `return` -> `ret` conversion mirroring the existing fix in `saltmod.state` (1c0ff6cff8). All currently-supported branches (3006.x/3007.x/3008.x/master) contain both conversions; a mocked `saltutil.cmd` return in the SSHClient shape (`{minion: {'return': ..., 'retcode': 0, ...}}`) runs through `saltmod.function(ssh=True)` without raising. The reporter's traceback was from a pre-2015 Salt in `/usr/lib/python3.6/site-packages/salt`. Closing as fixed.
