### ISSUE TITLE
[BUG] mysql cache module traceback error

### ISSUE THREAD

**Issue by sagetherage** [saltstack/salt#60398]
@Linuturk Thanks for the report.  I was able to reproduce this and then noticed that restarting the Salt minion as well caused the Salt master to attempt to send information along to the MySQL cache.  I did run into a different issue that appears to be a more serious bug:
```python
[ERROR   ] Error in function _pillar:
Traceback (most recent call last):
  File "/home/gareth/code/salt/salt/master.py", line 1935, in run_func
    ret = getattr(self, func)(load)
  File "/home/gareth/code/salt/salt/master.py", line 1635, in _pillar
    self.masterapi.cache.store(
  File "/home/gareth/code/salt/salt/cache/__init__.py", line 158, in store
    return self.modules[fun](bank, key, data, **self._kwargs)
  File "/home/gareth/code/salt/salt/loader.py", line 1241, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/home/gareth/code/salt/salt/loader.py", line 2274, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/home/gareth/code/salt/salt/loader.py", line 2289, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/home/gareth/code/salt/salt/cache/mysql_cache.py", line 185, in store
    _init_client()
  File "/home/gareth/code/salt/salt/cache/mysql_cache.py", line 171, in _init_client
    for k, v in _mysql_kwargs.items():
RuntimeError: dictionary changed size during iteration
```

_Originally posted by @garethgreenaway in https://github.com/saltstack/salt/issues/60375#issuecomment-863497993_

**Comment by garethgreenaway** [comment]
This particular traceback pops up when not all expected configuration items are included for the MySQL cache module.  Not all are needed and the code is trying to figure out which ones it has.  It is looping through the dictionary and removing items that are set to None, this causes the dictionary to be changed during the loop which is bad.

**Comment by Linuturk** [comment]
One thing to consider here is the Master Job Cache returner setup requires some of these `mysql.*` options as well, so if they share the dict between the two systems, removing unused options on the cache side might impact the returner configuration.

**Comment by garethgreenaway** [comment]
The following changes fix both this traceback as well as as another one when actually writing the data into the database:
```python
diff --git a/salt/cache/mysql_cache.py b/salt/cache/mysql_cache.py
index 1c183d16c0..d4287d1578 100644
--- a/salt/cache/mysql_cache.py
+++ b/salt/cache/mysql_cache.py
@@ -43,6 +43,7 @@ value to ``mysql``:
 
 """
 
+import copy
 import logging
 import time
 
@@ -90,7 +91,7 @@ def __virtual__():
     return bool(MySQLdb), "No python mysql client installed." if MySQLdb is None else ""
 
 
-def run_query(conn, query, retries=3):
+def run_query(conn, query, args=None, retries=3):
     """
     Get a cursor and run a query. Reconnect up to `retries` times if
     needed.
@@ -99,7 +100,14 @@ def run_query(conn, query, retries=3):
     """
     try:
         cur = conn.cursor()
-        out = cur.execute(query)
+
+        if args is None or args == {}:
+            log.debug("Doing query: %s", query)
+            out = cur.execute(query)
+        else:
+            log.debug("Doing query: %s args: %s ", query, repr(args))
+            out = cur.execute(query, args)
+
         return cur, out
     except (AttributeError, OperationalError) as e:
         if retries == 0:
@@ -112,7 +120,7 @@ def run_query(conn, query, retries=3):
             log.info("mysql_cache: recreating db connection due to: %r", e)
         global client
         client = MySQLdb.connect(**_mysql_kwargs)
-        return run_query(client, query, retries - 1)
+        return run_query(client, query, args, retries - 1)
     except Exception as e:  # pylint: disable=broad-except
         if len(query) > 150:
             query = query[:150] + "<...>"
@@ -168,7 +176,7 @@ def _init_client():
     _table_name = __opts__.get("mysql.table_name", _table_name)
     # TODO: handle SSL connection parameters
 
-    for k, v in _mysql_kwargs.items():
+    for k, v in copy.deepcopy(_mysql_kwargs).items():
         if v is None:
             _mysql_kwargs.pop(k)
     kwargs_copy = _mysql_kwargs.copy()
@@ -185,11 +193,11 @@ def store(bank, key, data):
     _init_client()
     data = __context__["serial"].dumps(data)
     query = (
-        b"REPLACE INTO {} (bank, etcd_key, data) values('{}', '{}', "
-        b"'{}')".format(_table_name, bank, key, data)
+        "REPLACE INTO {} (bank, etcd_key, data) values(%s,%s,%s)".format(_table_name)
     )
+    args = (bank, key, data)
 
-    cur, cnt = run_query(client, query)
+    cur, cnt = run_query(client, query, args)
     cur.close()
     if cnt not in (1, 2):
         raise SaltCacheError("Error storing {} {} returned {}".format(bank, key, cnt))
```
