### ISSUE TITLE
file.accumulated breaks on requisites referenced by state id without module "file"

### ISSUE THREAD

**Issue by aphor** [saltstack/salt#60426]
https://github.com/saltstack/salt/blob/4f3cb36955d84c6793efcbeabf53963067922d90/salt/states/file.py#L7395

Usage like this should work, however we generate an "Orphaned accumulator" error in the file.accumulated state when the requisite does not use the "function: state_id" reference style.
```
configuration file:
  file.managed:
    - name: /etc/foo/bar
    - source: salt://files/foo_bar.jinja
    - template: jinja

accumulated configstuff:
  file.accumulated:
    - filename: /etc/foo/bar
    - text:
      - some
      - good
      - stuff
    - watch_in:
      - configuration file
```

Also this error check does not appear to protect against cases where there are multiple requisites of the watch_in or require_in flavors and the file state which utilizes the accumulator does not use the old {'function': 'state_id'} requisite reference style.

Why is this fatal? This error prevents writing and testing file.accumulate states prior to the states which utilize the accumulator. Can we be more lenient here?

I think this error check should be removed if we can't really check and validate the requisite properly. Can it be demoted to a warning by diverting the error message to comments, but not fail the file.accumulated state?

**Comment by garethgreenaway** [comment]
@aphor thanks for the report.  I was able to reproduce it and to confirm this is the traceback I see:
```
local:
----------
          ID: accumulated configstuff
    Function: file.accumulated
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/home/gareth/code/salt/salt/state.py", line 2163, in call
                  ret = self.states[cdata["full"]](
                File "/home/gareth/code/salt/salt/loader.py", line 1241, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "/home/gareth/code/salt/salt/loader.py", line 2274, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/home/gareth/code/salt/salt/loader.py", line 2289, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/home/gareth/code/salt/salt/loader.py", line 2322, in wrapper
                  return f(*args, **kwargs)
                File "/home/gareth/code/salt/salt/states/file.py", line 7421, in accumulated
                  accum_deps[filename][name].extend(accumulator.values())
              AttributeError: 'str' object has no attribute 'values'
     Started: 10:54:41.039419
    Duration: 3.407 ms
     Changes:   
----------
          ID: configuration file
    Function: file.managed
        Name: /tmp/etc/foo/bar
      Result: False
     Comment: One or more requisite failed: test.60426.accumulated configstuff
     Started: 10:54:41.043009
    Duration: 0.003 ms
     Changes:   

Summary for local
------------
Succeeded: 0
Failed:    2
------------
Total states run:     2
Total run time:   3.410 ms
```
