### ISSUE TITLE
Error while bring up minion for multi-master and the list of masters decreased

### ISSUE THREAD

**Issue by zzxjoshua** [saltstack/salt#60440]
**Description**
While testing the failover feature with multi-master, we found that some master IPs disappeared in the list of masters decreased in minion log, and minon cannot switch over to other normal master for more than 3 hours.

**Setup**
Regular salt master - minion setup

Minion configuration
master:
- 71.15.94.58
- 71.15.94.152
- 71.15.94.153
master_type: failover
master_failback: False
master_alive_interval: 60
random_master: True
retry_dns: 0
loop_interval: 1
ping_interval: 5

**Steps to Reproduce the behavior**
1. shutdown master1(71.15.94.58) VM forever
2. restart master2(71.15.94.152) and hold on 5mins and restart master3(71.15.94.153)
3. wait master2/3 back to normal and check the list of masters in minon log
4. check minon switch over to  master2/3 or not

**Expected behavior**
Minon should switch over to master2/3 in minutes.

**Screenshots**

2021-06-22 14:26:10.234(30709|139648189548352)[minion:770]-ERROR:No master could be reached or all masters denied the minion's connection attempt.
2021-06-22 14:26:10.235(30709|139648189548352)[minion:1140]-ERROR:Error while bringing up minion for multi-master. Is master at ['71.15.94.58', '71.15.94.153', '71.15.94.152'] responding?
2021-06-22 14:26:43.267(30709|139648189548352)[minion:770]-ERROR:No master could be reached or all masters denied the minion's connection attempt.
2021-06-22 14:26:43.268(30709|139648189548352)[minion:1140]-ERROR:Error while bringing up minion for multi-master. Is master at ['71.15.94.152', '71.15.94.153', '71.15.94.58'] responding?
2021-06-22 14:27:16.301(30709|139648189548352)[minion:770]-ERROR:No master could be reached or all masters denied the minion's connection attempt.
2021-06-22 14:27:16.301(30709|139648189548352)[minion:1140]-ERROR:Error while bringing up minion for multi-master. Is master at ['71.15.94.153', '71.15.94.58', '71.15.94.152'] responding?
2021-06-22 14:27:49.335(30709|139648189548352)[minion:770]-ERROR:No master could be reached or all masters denied the minion's connection attempt.
2021-06-22 14:27:49.335(30709|139648189548352)[minion:1140]-ERROR:Error while bringing up minion for multi-master. Is master at ['71.15.94.58', '71.15.94.152', '71.15.94.153'] responding?
2021-06-22 14:28:22.367(30709|139648189548352)[minion:770]-ERROR:No master could be reached or all masters denied the minion's connection attempt.
2021-06-22 14:28:22.368(30709|139648189548352)[minion:1140]-ERROR:Error while bringing up minion for multi-master. Is master at ['71.15.94.152', '71.15.94.153', '71.15.94.58'] responding?
2021-06-22 14:28:55.400(30709|139648189548352)[minion:770]-ERROR:No master could be reached or all masters denied the minion's connection attempt.
2021-06-22 14:28:55.401(30709|139648189548352)[minion:1140]-ERROR:Error while bringing up minion for multi-master. Is master at ['71.15.94.58', '71.15.94.152', '71.15.94.153'] responding?
2021-06-22 14:29:28.435(30709|139648189548352)[minion:770]-ERROR:No master could be reached or all masters denied the minion's connection attempt.
2021-06-22 14:29:28.435(30709|139648189548352)[minion:1140]-ERROR:Error while bringing up minion for multi-master. Is master at ['71.15.94.58', '71.15.94.152', '71.15.94.153'] responding?
2021-06-22 14:30:01.468(30709|139648189548352)[minion:770]-ERROR:No master could be reached or all masters denied the minion's connection attempt.
2021-06-22 14:30:01.469(30709|139648189548352)[minion:1140]-ERROR:Error while bringing up minion for multi-master. Is master at ['71.15.94.152', '71.15.94.58', '71.15.94.153'] responding?
2021-06-22 14:30:34.504(30709|139648189548352)[minion:770]-ERROR:No master could be reached or all masters denied the minion's connection attempt.
2021-06-22 14:30:34.504(30709|139648189548352)[minion:1140]-ERROR:Error while bringing up minion for multi-master. Is **master at ['71.15.94.153', '71.15.94.58', '71.15.94.152']** responding?
2021-06-22 14:34:33.013(30709|139648189548352)[ioloop:640]-ERROR:Exception in callback functools.partial(<function wrap.<locals>.wrapped at 0x7f0242bd3ca0>, <salt.ext.tornado.concurrent.Future object at 0x7f0242b97ee0>)
Traceback (most recent call last):
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/ioloop.py", line 606, in _run_callback
    ret = callback()
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/stack_context.py", line 346, in wrapped
    raise_exc_info(exc)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/stack_context.py", line 317, in wrapped
    ret = fn(*args, **kwargs)
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/gen.py", line 291, in <lambda>
    future, lambda future: callback(future.result()))
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/gen.py", line 1064, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/minion.py", line 1587, in _send_req_async
    ret = yield channel.send(load, timeout=timeout)
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/gen.py", line 1064, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/transport/zeromq.py", line 446, in send
    ret = yield self._crypted_transfer(
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/gen.py", line 1064, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/transport/zeromq.py", line 416, in _crypted_transfer
    ret = yield _do_transfer()
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/gen.py", line 1064, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/transport/zeromq.py", line 396, in _do_transfer
    data = yield self.message_client.send(
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
salt.exceptions.SaltReqTimeoutError: Message timed out
2021-06-22 14:34:57.538(30709|139648189548352)[__init__:246]-ERROR:Exception getting pillar:
Traceback (most recent call last):
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/pillar/__init__.py", line 242, in compile_pillar
    ret_pillar = yield self.channel.crypted_transfer_decode_dictentry(
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/gen.py", line 1064, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/transport/zeromq.py", line 353, in crypted_transfer_decode_dictentry
    ret = yield self.message_client.send(
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
salt.exceptions.SaltReqTimeoutError: Message timed out
2021-06-22 14:34:57.539(30709|139648189548352)[minion:1140]-ERROR:Error while bringing up minion for multi-master. Is master at 71.15.94.58 responding?
2021-06-22 14:39:20.573(30709|139648189548352)[__init__:246]-ERROR:Exception getting pillar:
Traceback (most recent call last):
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/pillar/__init__.py", line 242, in compile_pillar
    ret_pillar = yield self.channel.crypted_transfer_decode_dictentry(
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/gen.py", line 1064, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/transport/zeromq.py", line 353, in crypted_transfer_decode_dictentry
    ret = yield self.message_client.send(
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
salt.exceptions.SaltReqTimeoutError: Message timed out
2021-06-22 14:39:20.574(30709|139648189548352)[minion:1140]-ERROR:Error while bringing up minion for multi-master. Is **master at 71.15.94.58** responding?
2021-06-22 14:39:34.590(30709|139648189548352)[ioloop:640]-ERROR:Exception in callback functools.partial(<function wrap.<locals>.wrapped at 0x7f0242bb9e50>, <salt.ext.tornado.concurrent.Future object at 0x7f0242b1f8e0>)
Traceback (most recent call last):
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/ioloop.py", line 606, in _run_callback
    ret = callback()
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/stack_context.py", line 346, in wrapped
    raise_exc_info(exc)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/stack_context.py", line 317, in wrapped
    ret = fn(*args, **kwargs)
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/gen.py", line 291, in <lambda>
    future, lambda future: callback(future.result()))
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/gen.py", line 1064, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/minion.py", line 1587, in _send_req_async
    ret = yield channel.send(load, timeout=timeout)
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/gen.py", line 1064, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/transport/zeromq.py", line 446, in send
    ret = yield self._crypted_transfer(
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/gen.py", line 1064, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/transport/zeromq.py", line 416, in _crypted_transfer
    ret = yield _do_transfer()
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/gen.py", line 1064, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/transport/zeromq.py", line 396, in _do_transfer
    data = yield self.message_client.send(
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
salt.exceptions.SaltReqTimeoutError: Message timed out
2021-06-22 14:43:48.617(30709|139648189548352)[__init__:246]-ERROR:Exception getting pillar:
Traceback (most recent call last):
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/pillar/__init__.py", line 242, in compile_pillar
    ret_pillar = yield self.channel.crypted_transfer_decode_dictentry(
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/gen.py", line 1064, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/transport/zeromq.py", line 353, in crypted_transfer_decode_dictentry
    ret = yield self.message_client.send(
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
salt.exceptions.SaltReqTimeoutError: Message timed out
2021-06-22 14:43:48.618(30709|139648189548352)[minion:1140]-ERROR:Error while bringing up minion for multi-master. Is master at 71.15.94.58 responding?
2021-06-22 14:44:32.665(30709|139648189548352)[ioloop:640]-ERROR:Exception in callback functools.partial(<function wrap.<locals>.wrapped at 0x7f0244119af0>, <salt.ext.tornado.concurrent.Future object at 0x7f0242b1fdc0>)
Traceback (most recent call last):
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/ioloop.py", line 606, in _run_callback
    ret = callback()
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/stack_context.py", line 346, in wrapped
    raise_exc_info(exc)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/stack_context.py", line 317, in wrapped
    ret = fn(*args, **kwargs)
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/gen.py", line 291, in <lambda>
    future, lambda future: callback(future.result()))
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/gen.py", line 1064, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/minion.py", line 1587, in _send_req_async
    ret = yield channel.send(load, timeout=timeout)
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/gen.py", line 1064, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/transport/zeromq.py", line 446, in send
    ret = yield self._crypted_transfer(
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/gen.py", line 1064, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/transport/zeromq.py", line 416, in _crypted_transfer
    ret = yield _do_transfer()
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/gen.py", line 1064, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/transport/zeromq.py", line 396, in _do_transfer
    data = yield self.message_client.send(
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
salt.exceptions.SaltReqTimeoutError: Message timed out
2021-06-22 14:48:11.654(30709|139648189548352)[__init__:246]-ERROR:Exception getting pillar:
Traceback (most recent call last):
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/pillar/__init__.py", line 242, in compile_pillar
    ret_pillar = yield self.channel.crypted_transfer_decode_dictentry(
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/gen.py", line 1064, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/transport/zeromq.py", line 353, in crypted_transfer_decode_dictentry
    ret = yield self.message_client.send(
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/usr/local/CloudAgent/plugins/MOOpsAgent/python-1.6.13/lib/python3.8/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
salt.exceptions.SaltReqTimeoutError: Message timed out
2021-06-22 14:48:11.655(30709|139648189548352)[minion:1140]-ERROR:Error while bringing up minion for multi-master. Is master at 71.15.94.58 responding?

**Versions Report**
Salt Version:
          Salt: 3002.5rc0+h0.cbu.mo.r2
 
Dependency Versions:
          cffi: 1.14.5
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.0.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.10.1
        pygit2: Not Installed
        Python: 3.7.4 (default, Jan 30 2021, 09:00:44)
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: Not Installed
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: Not Installed
 
System Versions:
          dist: euleros 2.0 SP9x86_64
        locale: UTF-8
       machine: x86_64
       release: 4.18.0-147.5.1.2.h340.eulerosv2r9.x86_64
        system: Linux
       version: EulerOS 2.0 SP9x86_64

**Comment by garethgreenaway** [comment]
@zzxjoshua Thanks for the report.  Are you using a shared master signing key between your masters?  Some documentation on how to set that up can be found here.  https://docs.saltproject.io/en/latest/topics/tutorials/multimaster_pki.html
