### ISSUE TITLE
[BUG] win_wua module got unknown failure.

### ISSUE THREAD

**Issue by vankhoa011** [saltstack/salt#60599]
**Description**
We are facing a weird issue when we tried to patch Windows server 2012 R2.

When we run `salt` from bastion server:

```
root@bastion:khnguyen#  salt host01  win_wua.list install=True -l debug
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/operators.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/operators.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/reactor.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/reactor.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: sus2uw1lnoc001
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/operators.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/operators.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/reactor.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/reactor.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: sus2uw1lnoc001
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/master', u'sus2uw1lnoc001_master', u'tcp://127.0.0.1:4506', u'clear')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://127.0.0.1:4506
[DEBUG   ] Trying to connect to: tcp://127.0.0.1:4506
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/bb/bbadba6d35f21daa875573bfb397657471d1153da918ababc29ef551a0419e/.minions.p
[DEBUG   ] get_iter_returns for jid 20210722013220938706 sent to set(['host01']) will timeout at 01:32:25.957887
[DEBUG   ] jid 20210722013220938706 return from host01
[DEBUG   ] return event: {u'host01': {u'jid': u'20210722013220938706', u'retcode': 1, u'ret': u"ERROR: Unknown Failure: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147221008), None)", u'out': u'nested'}}
[DEBUG   ] LazyLoaded nested.output
host01:
    ERROR: Unknown Failure: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147221008), None)
[DEBUG   ] jid 20210722013220938706 found all minions set([u'host01'])
[DEBUG   ] Closing IPCMessageSubscriber instance
ERROR: Minions returned with non-zero exit code
```
However when I ran `salt-call` , it's working

```
root@bastion:khnguyen# salt host01  cmd.run 'salt-call -l debug win_wua.list install=True'
host01:
    [DEBUG   ] Reading configuration from c:\salt\conf\minion
    [DEBUG   ] Including configuration from 'c:\salt\conf\minion.d\_schedule.conf'
    [DEBUG   ] Reading configuration from c:\salt\conf\minion.d\_schedule.conf
    [DEBUG   ] Using cached minion ID from c:\salt\conf\minion_id: host01
    [DEBUG   ] Configuration file path: c:\salt\conf\minion
    [WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
    [DEBUG   ] Grains refresh requested. Refreshing grains.
    [DEBUG   ] Reading configuration from c:\salt\conf\minion
    [DEBUG   ] Including configuration from 'c:\salt\conf\minion.d\_schedule.conf'
    [DEBUG   ] Reading configuration from c:\salt\conf\minion.d\_schedule.conf
    [DEBUG   ] Loading static grains from c:\salt\conf\grains
    [DEBUG   ] Connecting to master. Attempt 1 (infinite attempts)
    [DEBUG   ] "salt" Not an IP address? Assuming it is a hostname.
    [DEBUG   ] Master URI: tcp://10.7.4.8:4506
    [DEBUG   ] Popen(['git', 'version'], cwd=C:\Windows\system32\config\systemprofile, universal_newlines=False, shell=None)
    [DEBUG   ] Initializing new AsyncAuth for (u'c:\\salt\\conf\\pki\\minion', u'host01', u'tcp://10.7.4.8:4506')
    [DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (5621)
    [DEBUG   ] Setting zmq_reconnect_ivl to '5621ms'
    [DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
    [DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'c:\\salt\\conf\\pki\\minion', u'host01', u'tcp://10.7.4.8:4506', 'clear')
    [DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://10.7.4.8:4506
    [DEBUG   ] Trying to connect to: tcp://10.7.4.8:4506
    [DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
    [DEBUG   ] Decrypting the current master AES key
    [DEBUG   ] salt.crypt.get_rsa_key: Loading private key
    [DEBUG   ] salt.crypt._get_key_with_evict: Loading private key
    [DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
    [DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
    [DEBUG   ] Closing AsyncZeroMQReqChannel instance
    [DEBUG   ] Connecting the Minion to the Master publish port, using the URI: tcp://10.7.4.8:4505
    [DEBUG   ] salt.crypt.get_rsa_key: Loading private key
    [DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
    [DEBUG   ] Determining pillar cache
    [DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'c:\\salt\\conf\\pki\\minion', u'host01', u'tcp://10.7.4.8:4506', u'aes')
    [DEBUG   ] Initializing new AsyncAuth for (u'c:\\salt\\conf\\pki\\minion', u'host01', u'tcp://10.7.4.8:4506')
    [DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://10.7.4.8:4506
    [DEBUG   ] Trying to connect to: tcp://10.7.4.8:4506
    [DEBUG   ] salt.crypt.get_rsa_key: Loading private key
    [DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
    [DEBUG   ] Closing AsyncZeroMQReqChannel instance
    [DEBUG   ] LazyLoaded jinja.render
    [DEBUG   ] LazyLoaded yaml.render
    [DEBUG   ] LazyLoaded win_wua.list
    [DEBUG   ] LazyLoaded direct_call.execute
    [DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'c:\\salt\\conf\\pki\\minion', u'host01', u'tcp://10.7.4.8:4506', u'aes')
    [DEBUG   ] Initializing new AsyncAuth for (u'c:\\salt\\conf\\pki\\minion', u'host01', u'tcp://10.7.4.8:4506')
    [DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://10.7.4.8:4506
    [DEBUG   ] Trying to connect to: tcp://10.7.4.8:4506
    [DEBUG   ] Closing AsyncZeroMQReqChannel instance
    [DEBUG   ] LazyLoaded nested.output
    local:
        ----------
        Download:
            ----------
            Success:
                False
            Updates:
                Nothing to download
        Install:
            ----------
            Success:
                False
            Updates:
                Nothing to install
```

I tried to restart the window update agent follow this ticket https://github.com/saltstack/salt/issues/51874 but it's no luck. 
Do you have any idea how to debug this issue ? 
Thank you in advance.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 2019.2.8

Dependency Versions:
           cffi: 1.12.3
       cherrypy: unknown
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.26.3
        libnacl: Not Installed
       M2Crypto: 0.31.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: 3.9.7
         pygit2: 0.26.4
         Python: 2.7.5 (default, Nov 16 2020, 22:23:17)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.9.2009 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1160.31.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.9.2009 Core
```
</details>

**Additional context**

**Comment by vankhoa011** [comment]
I tried other options of win_wua module.  It seems this function `_get_msupdate_status` got the issue.

```
root@bastion:khnguyen#   salt host01  win_wua.get_needs_reboot
host01:
    False
```
```
root@bastion:khnguyen:#   salt host01  win_wua.get_wu_settings
host01:
    The minion function caused an exception: Traceback (most recent call last):
      File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1664, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "c:\salt\bin\lib\site-packages\salt\executors\direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "c:\salt\bin\lib\site-packages\salt\modules\win_wua.py", line 937, in get_wu_settings
        ret['Microsoft Update'] = _get_msupdate_status()
      File "c:\salt\bin\lib\site-packages\salt\modules\win_wua.py", line 969, in _get_msupdate_status
        col_services = obj_sm.Services
      File "c:\salt\bin\lib\site-packages\win32com\client\dynamic.py", line 516, in __getattr__
        ret = self._oleobj_.Invoke(retEntry.dispid,0,invoke_type,1)
    com_error: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147221008), None)
```

**Comment by vankhoa011** [comment]
I fixed the issue by reinstalling salt-minion. It seems there is something wrong with `win32com` lib when we use `salt` to run command from salt master. However,  the salt-call is using the same lib and it's working... 🤔

**Comment by sagetherage** [comment]
@vankhoa011 Salt v2019.2.8 is no longer supported. You may want to pose your question in the [mailing list forum for salt-users](https://groups.google.com/forum/#!forum/salt-users), ask on [IRC](https://web.libera.chat/#salt), or in our [community slack workspace](https://join.slack.com/t/saltstackcommunity/shared_invite/zt-3av8jjyf-oBQ2M0vhXOhJpNpRkPWBvg) for a better conversation platform.
