### ISSUE TITLE
[BUG] Pillar Git does not work properly

### ISSUE THREAD

**Issue by 53845714nF** [saltstack/salt#60613]
**Description**
I can't get my pillars from a git repo.

**Setup**
I have a local Git Server (gitea), with a Repo with my states and pillars.
I hav a git config in:  `/etc/salt/master.d/git.conf`:
```
fileserver_backend:
  - gitfs

gitfs_provider: gitpython
gitfs_base: master
gitfs_remotes:
  - ssh://gitea@git.local:/root/salt.git

gitfs_root: states

ext_pillar:
  - git:
    - master gitea@git.local:root/salt.git:
      - root: pillars

```

**Steps to Reproduce the behavior**
I get the following error message:
```
FileNotFoundError: [Errno 2] No such file or directory: '/var/cache/salt/master/git_pillar/85a9e5fcbbe9fdbde6ee82798ce1fa046173416125ca919e63d8154d199ee0c4/.git/update.lk'
2021-07-23 22:11:05,361 [salt.utils.gitfs :913 ][ERROR   ][29638] Unable to set update lock for master https://git.local/root/salt.git (/var/cache/salt/master/git_pillar/85a9e5fcbbe9fdbde6ee82798ce1fa046173416125ca919e63d8154d199ee0c4/.git/update.lk): [Errno 2] No such file or directory: '/var/cache/salt/master/git_pillar/85a9e5fcbbe9fdbde6ee82798ce1fa046173416125ca919e63d8154d199ee0c4/.git/update.lk'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/gitfs.py", line 843, in _lock
    self._get_lock_file(lock_type), os.O_CREAT | os.O_EXCL | os.O_WRONLY
FileNotFoundError: [Errno 2] No such file or directory: '/var/cache/salt/master/git_pillar/85a9e5fcbbe9fdbde6ee82798ce1fa046173416125ca919e63d8154d199ee0c4/.git/update.lk'
2021-07-23 22:12:05,872 [salt.utils.gitfs :913 ][ERROR   ][29638] Unable to set update lock for master https://git.local/root/salt.git (/var/cache/salt/master/git_pillar/85a9e5fcbbe9fdbde6ee82798ce1fa046173416125ca919e63d8154d199ee0c4/.git/update.lk): [Errno 2] No such file or directory: '/var/cache/salt/master/git_pillar/85a9e5fcbbe9fdbde6ee82798ce1fa046173416125ca919e63d8154d199ee0c4/.git/update.lk'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/gitfs.py", line 843, in _lock
    self._get_lock_file(lock_type), os.O_CREAT | os.O_EXCL | os.O_WRONLY
FileNotFoundError: [Errno 2] No such file or directory: '/var/cache/salt/master/git_pillar/85a9e5fcbbe9fdbde6ee82798ce1fa046173416125ca919e63d8154d199ee0c4/.git/update.lk'
2021-07-23 22:13:06,396 [salt.utils.gitfs :913 ][ERROR   ][29638] Unable to set update lock for master https://git.local/root/salt.git (/var/cache/salt/master/git_pillar/85a9e5fcbbe9fdbde6ee82798ce1fa046173416125ca919e63d8154d199ee0c4/.git/update.lk): [Errno 2] No such file or directory: '/var/cache/salt/master/git_pillar/85a9e5fcbbe9fdbde6ee82798ce1fa046173416125ca919e63d8154d199ee0c4/.git/update.lk'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/gitfs.py", line 843, in _lock
    self._get_lock_file(lock_type), os.O_CREAT | os.O_EXCL | os.O_WRONLY
FileNotFoundError: [Errno 2] No such file or directory: '/var/cache/salt/master/git_pillar/85a9e5fcbbe9fdbde6ee82798ce1fa046173416125ca919e63d8154d199ee0c4/.git/update.lk'
2021-07-23 22:14:06,976 [salt.utils.gitfs :913 ][ERROR   ][29638] Unable to set update lock for master https://git.local/root/salt.git (/var/cache/salt/master/git_pillar/85a9e5fcbbe9fdbde6ee82798ce1fa046173416125ca919e63d8154d199ee0c4/.git/update.lk): [Errno 2] No such file or directory: '/var/cache/salt/master/git_pillar/85a9e5fcbbe9fdbde6ee82798ce1fa046173416125ca919e63d8154d199ee0c4/.git/update.lk'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/gitfs.py", line 843, in _lock
    self._get_lock_file(lock_type), os.O_CREAT | os.O_EXCL | os.O_WRONLY
FileNotFoundError: [Errno 2] No such file or directory: '/var/cache/salt/master/git_pillar/85a9e5fcbbe9fdbde6ee82798ce1fa046173416125ca919e63d8154d199ee0c4/.git/update.lk'
2021-07-23 22:15:08,523 [salt.utils.gitfs :913 ][ERROR   ][29638] Unable to set update lock for master https://git.local/root/salt.git (/var/cache/salt/master/git_pillar/85a9e5fcbbe9fdbde6ee82798ce1fa046173416125ca919e63d8154d199ee0c4/.git/update.lk): [Errno 2] No such file or directory: '/var/cache/salt/master/git_pillar/85a9e5fcbbe9fdbde6ee82798ce1fa046173416125ca919e63d8154d199ee0c4/.git/update.lk'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/gitfs.py", line 843, in _lock
    self._get_lock_file(lock_type), os.O_CREAT | os.O_EXCL | os.O_WRONLY
FileNotFoundError: [Errno 2] No such file or directory: '/var/cache/salt/master/git_pillar/85a9e5fcbbe9fdbde6ee82798ce1fa046173416125ca919e63d8154d199ee0c4/.git/update.lk'
2021-07-23 22:15:34,848 [salt.utils.parsers:1104][WARNING ][29604] Master received a SIGTERM. Exiting.
2021-07-23 22:16:10,460 [salt.utils.gitfs :888 ][WARNING ][535] Process 529 has a git_pillar checkout lock (/var/cache/salt/master/git_pillar/8e3c76866879bd1faf93ddccb11984c2b7718fbc6b2e3f3c5cbc8ba4e0b4c2ab/.git/checkout.lk)
2021-07-23 22:16:10,464 [salt.utils.gitfs :888 ][WARNING ][527] Process 529 has a git_pillar checkout lock (/var/cache/salt/master/git_pillar/8e3c76866879bd1faf93ddccb11984c2b7718fbc6b2e3f3c5cbc8ba4e0b4c2ab/.git/checkout.lk)
2021-07-23 22:16:10,468 [salt.utils.gitfs :888 ][WARNING ][520] Process 529 has a git_pillar checkout lock (/var/cache/salt/master/git_pillar/8e3c76866879bd1faf93ddccb11984c2b7718fbc6b2e3f3c5cbc8ba4e0b4c2ab/.git/checkout.lk)
2021-07-23 22:16:10,562 [salt.utils.gitfs :888 ][WARNING ][535] Process 529 has a git_pillar checkout lock (/var/cache/salt/master/git_pillar/8e3c76866879bd1faf93ddccb11984c2b7718fbc6b2e3f3c5cbc8ba4e0b4c2ab/.git/checkout.lk)
2021-07-23 22:16:10,566 [salt.utils.gitfs :888 ][WARNING ][527] Process 529 has a git_pillar checkout lock (/var/cache/salt/master/git_pillar/8e3c76866879bd1faf93ddccb11984c2b7718fbc6b2e3f3c5cbc8ba4e0b4c2ab/.git/checkout.lk)
2021-07-23 22:16:10,571 [salt.utils.gitfs :888 ][WARNING ][520] Process 529 has a git_pillar checkout lock (/var/cache/salt/master/git_pillar/8e3c76866879bd1faf93ddccb11984c2b7718fbc6b2e3f3c5cbc8ba4e0b4c2ab/.git/checkout.lk)
2021-07-23 22:16:10,737 [salt.utils.gitfs :888 ][WARNING ][535] Process 531 has a git_pillar checkout lock (/var/cache/salt/master/git_pillar/8e3c76866879bd1faf93ddccb11984c2b7718fbc6b2e3f3c5cbc8ba4e0b4c2ab/.git/checkout.lk)
2021-07-23 22:16:10,738 [salt.utils.gitfs :888 ][WARNING ][527] Process 531 has a git_pillar checkout lock (/var/cache/salt/master/git_pillar/8e3c76866879bd1faf93ddccb11984c2b7718fbc6b2e3f3c5cbc8ba4e0b4c2ab/.git/checkout.lk)
2021-07-23 22:16:10,739 [salt.utils.gitfs :888 ][WARNING ][520] Process 531 has a git_pillar checkout lock (/var/cache/salt/master/git_pillar/8e3c76866879bd1faf93ddccb11984c2b7718fbc6b2e3f3c5cbc8ba4e0b4c2ab/.git/checkout.lk)
2021-07-23 22:21:42,222 [salt.utils.parsers:1104][WARNING ][483] Master received a SIGTERM. Exiting.
(END)
```

**Expected behavior**
I want to access my Pillars that are in a Git repo.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3003.1

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.5
     gitpython: 2.1.11
        Jinja2: 2.10
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.7.3 (default, Jan 22 2021, 20:04:44)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.1.2
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.1

System Versions:
          dist: debian 10 buster
        locale: utf-8
       machine: x86_64
       release: 5.4.119-1-pve
        system: Linux
       version: Debian GNU/Linux 10 buster

```
</details>

**Comment by 53845714nF** [comment]
My fault. 

Changed my config to this:
```
fileserver_backend:
  - gitfs

gitfs_provider: gitpython
gitfs_base: master
gitfs_remotes:
  - ssh://gitea@git.local:/root/salt.git

gitfs_root: states

ext_pillar:
  - git:
    - master gitea@git.local:root/salt.git:
      - root: pillars
      - env: base
      - name: base

```
