### ISSUE TITLE
[BUG] ProxyCaller() not working against napalm proxy 

### ISSUE THREAD

**Issue by network-shark** [saltstack/salt#60698]
**Description**

Hello Salties , 
because I can't use saltcheck on proxy minions I spend some time on how I could possible fix it. @dmurphy18 Mentioned maybe it's just replacing Caller() with ProxyCaller() . I thought , must be a low  hanging fruit , go for it :) 

So I just copied this from the documentation and waited for a result. 
```
import logging
logging.basicConfig(
    format='%(asctime)s %(levelname)s:%(message)s',
    datefmt='%m/%d/%Y %I:%M:%S %p',
    level=logging.DEBUG)

import salt.client
import salt.config

__opts__ = salt.config.proxy_config('/etc/salt/proxy',
        minion_id='c1000v')
caller = salt.client.ProxyCaller(mopts=__opts__)
caller.cmd('net.cli', 'show ip arp')
```

With logging enabled I could catch the error.

```
Proxymodule napalm is missing an init() or a shutdown() or both.

```

From the debugs I have collected it seems that the napalm functions are not loaded via the loader. It fails , but I don't see why . Due to lack of knowledge of loader system.

Good Example ( via salt-call ) 
salt-call
```
[DEBUG   ] ['__virtual__']
> /Users/sharky/.pyenv/versions/3.6.8/envs/salt3003/lib/python3.6/site-packages/salt/loader.py(2197)_process_virtual()
-> virtual_aliases = getattr(mod, "__virtual_aliases__", tuple())
(Pdb) n
> /Users/sharky/.pyenv/versions/3.6.8/envs/salt3003/lib/python3.6/site-packages/salt/loader.py(2198)_process_virtual()
-> try:
(Pdb) n
> /Users/sharky/.pyenv/versions/3.6.8/envs/salt3003/lib/python3.6/site-packages/salt/loader.py(2199)_process_virtual()
-> error_reason = None
(Pdb) n
> /Users/sharky/.pyenv/versions/3.6.8/envs/salt3003/lib/python3.6/site-packages/salt/loader.py(2200)_process_virtual()
-> if hasattr(mod, "__virtual__") and inspect.isfunction(mod.__virtual__):
(Pdb) n
> /Users/sharky/.pyenv/versions/3.6.8/envs/salt3003/lib/python3.6/site-packages/salt/loader.py(2201)_process_virtual()
-> try:
(Pdb) n
> /Users/sharky/.pyenv/versions/3.6.8/envs/salt3003/lib/python3.6/site-packages/salt/loader.py(2202)_process_virtual()
-> start = time.time()
(Pdb) n
> /Users/sharky/.pyenv/versions/3.6.8/envs/salt3003/lib/python3.6/site-packages/salt/loader.py(2203)_process_virtual()
-> virtual_attr = getattr(mod, virtual_func)
(Pdb) n
> /Users/sharky/.pyenv/versions/3.6.8/envs/salt3003/lib/python3.6/site-packages/salt/loader.py(2204)_process_virtual()
-> virtual = self.run(virtual_attr)
(Pdb) virutal_attr
*** NameError: name 'virutal_attr' is not defined
(Pdb) virtual_attr
<function __virtual__ at 0x107f60488>
(Pdb) n
> /Users/sharky/.pyenv/versions/3.6.8/envs/salt3003/lib/python3.6/site-packages/salt/loader.py(2205)_process_virtual()
-> if isinstance(virtual, tuple):
(Pdb) virtual
'napalm'
(Pdb) virtual_attr
<function __virtual__ at 0x107f60488>
(Pdb) virtual_attr
<function __virtual__ at 0x107f60488>
(Pdb) virtual_func
'__virtual__'
(Pdb) mod
<module 'salt.loaded.int.proxy.napalm' from '/Users/sharky/.pyenv/versions/3.6.8/envs/salt3003/lib/python3.6/site-packages/salt/proxy/napalm.py'>
(Pdb) c


> /Users/sharky/.pyenv/versions/3.6.8/envs/salt3003/lib/python3.6/site-packages/salt/loader.py(2298)run()
-> self._last_context = contextvars.copy_context()
(Pdb) contextvars.copy_context()
<contextvars.Context object at 0x1070af588>
(Pdb) print(contextvars.copy_context())
<contextvars.Context object at 0x1070af518>
(Pdb) vars(contextvars.copy_context()
*** SyntaxError: unexpected EOF while parsing
(Pdb) vars(contextvars.copy_context())
{'_data': <immutables.Map({}) at 0x105b61990>, '_prev_context': None}


> /Users/sharky/.pyenv/versions/3.6.8/envs/salt3003/lib/python3.6/site-packages/salt/loader.py(2299)run()->'napalm'
-> return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
```
Bad Example: ( via ProxyCaller() )
```
-Call--
> /Users/sharky/.pyenv/versions/salt3003/lib/python3.6/site-packages/contextvars/__init__.py(188)_get_context()
-> def _get_context():
(Pdb) n
> /Users/sharky/.pyenv/versions/salt3003/lib/python3.6/site-packages/contextvars/__init__.py(189)_get_context()
-> ctx = getattr(_state, 'context', None)
(Pdb) _state
<_thread._local object at 0x107a48db0>
(Pdb) n
> /Users/sharky/.pyenv/versions/salt3003/lib/python3.6/site-packages/contextvars/__init__.py(190)_get_context()
-> if ctx is None:
(Pdb) ctx
<contextvars.Context object at 0x109025780>
(Pdb) n
> /Users/sharky/.pyenv/versions/salt3003/lib/python3.6/site-packages/contextvars/__init__.py(193)_get_context()
-> return ctx
(Pdb) n
--Return--
> /Users/sharky/.pyenv/versions/salt3003/lib/python3.6/site-packages/contextvars/__init__.py(193)_get_context()-><contextvars....t 0x109025780>
-> return ctx
(Pdb) n
> /Users/sharky/.pyenv/versions/salt3003/lib/python3.6/site-packages/contextvars/__init__.py(36)run()
-> try:
(Pdb) n
> /Users/sharky/.pyenv/versions/salt3003/lib/python3.6/site-packages/contextvars/__init__.py(37)run()
-> _set_context(self)
(Pdb) n
> /Users/sharky/.pyenv/versions/salt3003/lib/python3.6/site-packages/contextvars/__init__.py(38)run()
-> return callable(*args, **kwargs)
(Pdb) args
self = <contextvars.Context object at 0x10a8f5eb8>
callable = <bound method LazyLoader._run_as of <salt.loader.LazyLoader object at 0x10a7fe5f8>>
args = (<function __virtual__ at 0x10a8d4e18>,)
kwargs = {}
(Pdb) n
> /Users/sharky/.pyenv/versions/salt3003/lib/python3.6/site-packages/contextvars/__init__.py(40)run()
-> _set_context(self._prev_context)
(Pdb) n
> /Users/sharky/.pyenv/versions/salt3003/lib/python3.6/site-packages/contextvars/__init__.py(41)run()
-> self._prev_context = None
(Pdb) n
--Return--
> /Users/sharky/.pyenv/versions/salt3003/lib/python3.6/site-packages/contextvars/__init__.py(41)run()->(False, '"napalm"" (/...tall napalm``')
-> self._prev_context = None
(Pdb) n
--Return--
> /Users/sharky/.pyenv/versions/salt3003/lib/python3.6/site-packages/salt/loader.py(2299)run()->(False, '"napalm"" (/...tall napalm``')
-> return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
(Pdb) n
> /Users/sharky/.pyenv/versions/salt3003/lib/python3.6/site-packages/salt/loader.py(2205)_process_virtual()
-> if isinstance(virtual, tuple):
(Pdb) n
> /Users/sharky/.pyenv/versions/salt3003/lib/python3.6/site-packages/salt/loader.py(2206)_process_virtual()
-> error_reason = virtual[1]
(Pdb) n
> /Users/sharky/.pyenv/versions/salt3003/lib/python3.6/site-packages/salt/loader.py(2207)_process_virtual()
-> virtual = virtual[0]
(Pdb) n
> /Users/sharky/.pyenv/versions/salt3003/lib/python3.6/site-packages/salt/loader.py(2208)_process_virtual()
-> if self.opts.get("virtual_timer", False):
(Pdb) n
> /Users/sharky/.pyenv/versions/salt3003/lib/python3.6/site-packages/salt/loader.py(2224)_process_virtual()
-> virtualname = getattr(mod, "__virtualname__", virtual)
(Pdb) virtual

```

Summary 
good example 
```

contextvars returns napalm 
```
in the bad example
```
contextvars returns a tuple(napalm , .....)
````
seems to be bad :/

With salt-call the napalm proxy is responding .

Command:
```
salt-call --proxyid c1000v net.cli 'show arp'
```

To be super safe that there is no issue with my config , I did the same setup with a netmiko proxy instead of a napalm proxy. 

Calling a netmiko proxy via ProxyCaller()  and salt-call are working fine ... . 

Commands
```
salt-call --proxyid c1000v netmiko.send_command 'show version'
```

Salt Version 3003.1

**Comment by network-shark** [comment]
Trying to work on this and document my progress

Via Proxy Call . 



```
14:33:08.63 LOG:
14:33:08.76 .... self.proxy._dict = OrderedDict()
14:33:08.76 >>> Enter with block in SProxyMinion.gen_modules in File "/Users/sharky/.pyenv/versions/salt3003rc/lib/python3.6/site-packages/salt/minion.py", line 3898
14:33:08.76 .................. self = <salt.minion.SProxyMinion object at 0x111842320>
14:33:08.76 .................. initial_load = True
14:33:08.76 .................. context = None
14:33:08.76 .................. fq_proxyname = 'napalm'
14:33:08.76 3899 |                 self.proxy.reload_modules()
    14:33:10.41 >>> Call to LazyLoader.reload_modules in File "/Users/sharky/.pyenv/versions/salt3003rc/lib/python3.6/site-packages/salt/loader.py", line 2154
    14:33:10.41 .......... self = LazyLoader({})
    14:33:10.41 2154 |     def reload_modules(self):
    14:33:10.41 .......... self = LazyLoader()
    14:33:10.41 2155 |         with self._lock:
    14:33:10.41 2156 |             self.loaded_files = set()
    14:33:10.42 2157 |             self._load_all()
        14:33:10.42 >>> Call to LazyLoader._load_all in File "/Users/sharky/.pyenv/versions/salt3003rc/lib/python3.6/site-packages/salt/loader.py", line 2142
        14:33:10.42 .......... self = LazyLoader()
        14:33:10.42 2142 |     def _load_all(self):
        14:33:10.42 2146 |         with self._lock:
        14:33:10.42 2147 |             for name in self.file_mapping:
        14:33:10.42 .................. name = 'ssh'
        14:33:10.42 2148 |                 if name in self.loaded_files or name in self.missing_modules:
        14:33:10.42 2149 |                     continue
        14:33:10.42 2147 |             for name in self.file_mapping:
        14:33:10.42 .................. name = 'arista_pyeapi'
        14:33:10.42 2148 |                 if name in self.loaded_files or name in self.missing_modules:
        14:33:10.42 2149 |                     continue
        14:33:10.42 2147 |             for name in self.file_mapping:
        14:33:10.42 .................. name = 'chronos'
        14:33:10.42 2148 |                 if name in self.loaded_files or name in self.missing_modules:
        14:33:10.42 2149 |                     continue
        14:33:10.42 2147 |             for name in self.file_mapping:
        14:33:10.42 .................. name = 'cimc'
        14:33:10.42 2148 |                 if name in self.loaded_files or name in self.missing_modules:
        14:33:10.42 2149 |                     continue
        14:33:10.42 2147 |             for name in self.file_mapping:
        14:33:10.42 .................. name = 'cisconso'
        14:33:10.42 2148 |                 if name in self.loaded_files or name in self.missing_modules:
        14:33:10.42 2149 |                     continue
        14:33:10.42 2147 |             for name in self.file_mapping:
        14:33:10.42 .................. name = 'docker'
        14:33:10.42 2148 |                 if name in self.loaded_files or name in self.missing_modules:
        14:33:10.42 2149 |                     continue
        14:33:10.42 2147 |             for name in self.file_mapping:
        14:33:10.43 .................. name = 'dummy'
        14:33:10.43 2148 |                 if name in self.loaded_files or name in self.missing_modules:
        14:33:10.43 2149 |                     continue
        14:33:10.43 2147 |             for name in self.file_mapping:
        14:33:10.43 .................. name = 'esxcluster'
        14:33:10.43 2148 |                 if name in self.loaded_files or name in self.missing_modules:
        14:33:10.43 2149 |                     continue
        14:33:10.43 2147 |             for name in self.file_mapping:
        14:33:10.43 .................. name = 'esxdatacenter'
        14:33:10.43 2148 |                 if name in self.loaded_files or name in self.missing_modules:
        14:33:10.43 2149 |                     continue
        14:33:10.43 2147 |             for name in self.file_mapping:
        14:33:10.43 .................. name = 'esxi'
        14:33:10.43 2148 |                 if name in self.loaded_files or name in self.missing_modules:
        14:33:10.43 2149 |                     continue
        14:33:10.43 2147 |             for name in self.file_mapping:
        14:33:10.43 .................. name = 'esxvm'
        14:33:10.43 2148 |                 if name in self.loaded_files or name in self.missing_modules:
        14:33:10.43 2149 |                     continue
        14:33:10.43 2147 |             for name in self.file_mapping:
        14:33:10.43 .................. name = 'fx2'
        14:33:10.43 2148 |                 if name in self.loaded_files or name in self.missing_modules:
        14:33:10.43 2149 |                     continue
        14:33:10.43 2147 |             for name in self.file_mapping:
        14:33:10.44 .................. name = 'junos'
        14:33:10.44 2148 |                 if name in self.loaded_files or name in self.missing_modules:
        14:33:10.44 2149 |                     continue
        14:33:10.44 2147 |             for name in self.file_mapping:
        14:33:10.44 .................. name = 'marathon'
        14:33:10.44 2148 |                 if name in self.loaded_files or name in self.missing_modules:
        14:33:10.44 2149 |                     continue
        14:33:10.44 2147 |             for name in self.file_mapping:
        14:33:10.44 .................. name = 'napalm'
        14:33:10.44 2148 |                 if name in self.loaded_files or name in self.missing_modules:
        14:33:10.44 2149 |                     continue
        14:33:10.44 2147 |             for name in self.file_mapping:
        14:33:10.44 .................. name = 'netmiko_px'
        14:33:10.44 2148 |                 if name in self.loaded_files or name in self.missing_modules:
        14:33:10.44 2149 |                     continue
        14:33:10.44 2147 |             for name in self.file_mapping:
        14:33:10.44 .................. name = 'nxos'
        14:33:10.44 2148 |                 if name in self.loaded_files or name in self.missing_modules:
        14:33:10.44 2149 |                     continue
        14:33:10.44 2147 |             for name in self.file_mapping:
        14:33:10.44 .................. name = 'nxos_api'
        14:33:10.44 2148 |                 if name in self.loaded_files or name in self.missing_modules:
        14:33:10.45 2149 |                     continue
        14:33:10.45 2147 |             for name in self.file_mapping:
        14:33:10.45 .................. name = 'panos'
        14:33:10.45 2148 |                 if name in self.loaded_files or name in self.missing_modules:
        14:33:10.45 2149 |                     continue
        14:33:10.45 2147 |             for name in self.file_mapping:
        14:33:10.45 .................. name = 'philips_hue'
        14:33:10.45 2148 |                 if name in self.loaded_files or name in self.missing_modules:
        14:33:10.45 2149 |                     continue
        14:33:10.45 2147 |             for name in self.file_mapping:
        14:33:10.46 .................. name = 'rest_sample'
        14:33:10.46 2148 |                 if name in self.loaded_files or name in self.missing_modules:
        14:33:10.46 2149 |                     continue
        14:33:10.47 2147 |             for name in self.file_mapping:
        14:33:10.47 .................. name = 'ssh_sample'
        14:33:10.47 2148 |                 if name in self.loaded_files or name in self.missing_modules:
        14:33:10.47 2149 |                     continue
        14:33:10.47 2147 |             for name in self.file_mapping:
        14:33:10.48 .................. name = 'vcenter'
        14:33:10.48 2148 |                 if name in self.loaded_files or name in self.missing_modules:
        14:33:10.48 2149 |                     continue
        14:33:10.48 2147 |             for name in self.file_mapping:
        14:33:10.48 2152 |             self.loaded = True
        14:33:10.48 <<< Return value from LazyLoader._load_all: None
    14:33:10.48 2157 |             self._load_all()
    14:33:10.49 <<< Return value from LazyLoader.reload_modules: None
14:33:10.49 3899 |                 self.proxy.reload_modules()

```
Returns none , because reloading of the modules can not work if there are any modules on the LazyLoader.

Question:  Why the hack are the modules not initiated on the lazy loader and why are they intialized via salt-call

**Comment by network-shark** [comment]
Problem found 

salt/grains/napalm.py

def virtual(opts, virtualname, filename):

```
run via proxycaller 
23:43:17.59   91 |     pp(HAS_NAPALM)
23:43:17.59 LOG:
23:43:17.59 .... HAS_NAPALM = True
23:43:17.59   92 |     pp(NAPALM_MAJOR)
23:43:17.59 LOG:
23:43:17.59 .... NAPALM_MAJOR = 3
23:43:17.59   93 |     pp(is_proxy(opts))
23:43:17.59 LOG:
23:43:17.59 .... is_proxy(opts) = False
23:43:17.59   94 |     pp(is_minion(opts))
23:43:17.59 LOG:

run via salt-call 
23:45:12.35 LOG:
23:45:12.36 .... HAS_NAPALM = True
23:45:12.36 LOG:
23:45:12.36 .... NAPALM_MAJOR = 3
23:45:12.36 LOG:
23:45:12.36 .... is_proxy(opts) = True
23:45:12.36 LOG:
23:45:12.36 .... is_minion(opts) = False

```

**Comment by network-shark** [comment]
is_proxy checks if there is an sys.argv argument '--proxyid' . 

./ProxyCaller.py '--proxyid'

```
18:15:54.11 <<< Return value from is_proxy: True
Traceback (most recent call last):
  File "./ProxyCaller.py", line 40, in <module>
    caller.cmd('netmiko.send_command', 'show ip arp',)
  File "/Users/sharky/.pyenv/versions/3.6.8/envs/salt3003rc/lib/python3.6/site-packages/salt/client/__init__.py", line 2192, in cmd
    func = self.sminion.functions[fun]
  File "/Users/sharky/.pyenv/versions/3.6.8/envs/salt3003rc/lib/python3.6/site-packages/salt/loader.py", line 1396, in __getitem__
    func = super().__getitem__(item)
  File "/Users/sharky/.pyenv/versions/3.6.8/envs/salt3003rc/lib/python3.6/site-packages/salt/utils/lazy.py", line 108, in __getitem__
    raise KeyError(key)
KeyError: 'netmiko.send_command'
```
