### ISSUE TITLE
[BUG] key error in python leading to "An un-handled exception was caught by salt's global exception handler"

### ISSUE THREAD

**Issue by ecstuchi** [saltstack/salt#60724]
**Description**
When running desired state often I am getting the a python traceback when accessing a key in python's structure.
This is happening for refreshing the pillar as well.

**Setup**
~2000 minions running 3001.7
~10 minions running 3003.1
salt-master running 3003.2

**Steps to Reproduce the behavior**
When running:
[root@3ca4653827b2 /]# salt --async -t 30 -b 30 '*' saltutil.refresh_pillar

I'm getting often this output:
```
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
KeyError: 'ret'
Traceback (most recent call last):
  File "/usr/bin/salt", line 11, in <module>
    load_entry_point('salt==3003.2', 'console_scripts', 'salt')()
  File "/usr/lib/python3.6/site-packages/salt/scripts.py", line 539, in salt_main
    client.run()
  File "/usr/lib/python3.6/site-packages/salt/cli/salt.py", line 61, in run
    self._run_batch()
  File "/usr/lib/python3.6/site-packages/salt/cli/salt.py", line 299, in _run_batch
    for res in batch.run():
  File "/usr/lib/python3.6/site-packages/salt/cli/batch.py", line 298, in run
    ret[minion] = data["ret"]
KeyError: 'ret'
Traceback (most recent call last):
  File "/usr/bin/salt", line 11, in <module>
    load_entry_point('salt==3003.2', 'console_scripts', 'salt')()
  File "/usr/lib/python3.6/site-packages/salt/scripts.py", line 539, in salt_main
    client.run()
  File "/usr/lib/python3.6/site-packages/salt/cli/salt.py", line 61, in run
    self._run_batch()
  File "/usr/lib/python3.6/site-packages/salt/cli/salt.py", line 299, in _run_batch
    for res in batch.run():
  File "/usr/lib/python3.6/site-packages/salt/cli/batch.py", line 298, in run
    ret[minion] = data["ret"]
KeyError: 'ret'
```
**Expected behavior**
I would expect that the salt command could finish successfully and without python's traceback (error).

**Screenshots**
Pasted log should be enough.

**Versions Report**
<details><summary>
[root@12e4b55eb1b7 /]# salt --versions-report
Salt Version:
          Salt: 3003.2
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, May 21 2019, 23:51:36)
  python-gnupg: Not Installed
        PyYAML: 3.12
         PyZMQ: 19.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: centos 8 Core
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-957.el7.x86_64
        system: Linux
       version: CentOS Linux 8 Core
</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
PASTE HERE
```
</details>

**Additional context**

**Comment by dmurphy18** [comment]
@ecstuchi Would it be possible to see an example of the pillar data for which the error occurs, an example which does not contain confidential information

**Comment by ecstuchi** [comment]
@dmurphy18, I had to trim the confidential information, but the logic is there. And it's a simple chain/flow.
[pillar.zip](https://github.com/saltstack/salt/files/6981295/pillar.zip)

Please let me know if you need any further information.
This is happening very often, but not 100% of the times. I'm not certain if it has a relation to behavior of some specific minions not responding or what.

**Comment by ecstuchi** [comment]
@dmurphy18, I had to trim the confidential information, but the logic is there. And it's a simple chain/flow.
[pillar.zip](https://github.com/saltstack/salt/files/6981349/pillar.zip)

Please let me know if you need any further information.
This is happening very often, but not 100% of the times. I'm not certain if it has a relation with the behavior of some specific minions not responding or what.

**Comment by dmurphy18** [comment]
@ecstuchi Sorry for the delay in looking at this, but examining rhel7/packages.sls file I notice a number of .i686 packages and with RedHat 7 being x86_64 wondering why ?, even though x86_64 is available.  Just curious in case there is some 32-bit / 64-bit interaction possibly occurring.

**Comment by ecstuchi** [comment]
@dmurphy18, That's due software requirements we have, so supporting native i686 libraries on a x86_64 system.
Usually that's not a problem. And I don't know why that would correlate with accessing the key in the data structure.
All our systems are mostly equal and it's strange that the error is coming from the salt client while processing the minions.

I'm not certain, but it seems that I only get this problem when using the '-b' for batch mode. I will try to run more tests without batch to check if it pops up or not.

**Comment by dmurphy18** [comment]
@ecstuchi I was just curious, given Salt does not support 32-bit since RHEL 6, (please ignore the 32-bit Arista built from AltArch Centos 7 running on Fedora Core 18 and up :) )

thanks for the info on batch mode

**Comment by ecstuchi** [comment]
@dmurphy18 I was evaluating it further and if I run:

`salt -t20 -b80 -L '<list with ~400 minions>' cmd.run 'uname -a'`

I get:

`[ERROR   ] An un-handled exception was caught by salt's global exception handler:
KeyError: 'ret'
Traceback (most recent call last):
  File "/usr/bin/salt", line 11, in <module>
    load_entry_point('salt==3003.3', 'console_scripts', 'salt')()
  File "/usr/lib/python3.6/site-packages/salt/scripts.py", line 539, in salt_main
    client.run()
  File "/usr/lib/python3.6/site-packages/salt/cli/salt.py", line 108, in run
    self._run_batch()
  File "/usr/lib/python3.6/site-packages/salt/cli/salt.py", line 299, in _run_batch
    for res in batch.run():
  File "/usr/lib/python3.6/site-packages/salt/cli/batch.py", line 298, in run
    ret[minion] = data["ret"]
KeyError: 'ret'
Traceback (most recent call last):
  File "/usr/bin/salt", line 11, in <module>
    load_entry_point('salt==3003.3', 'console_scripts', 'salt')()
  File "/usr/lib/python3.6/site-packages/salt/scripts.py", line 539, in salt_main
    client.run()
  File "/usr/lib/python3.6/site-packages/salt/cli/salt.py", line 108, in run
    self._run_batch()
  File "/usr/lib/python3.6/site-packages/salt/cli/salt.py", line 299, in _run_batch
    for res in batch.run():
  File "/usr/lib/python3.6/site-packages/salt/cli/batch.py", line 298, in run
    ret[minion] = data["ret"]
KeyError: 'ret'`

This error also happens when there's no state being applied.

**Comment by dmurphy18** [comment]
That's for that info

**Comment by dmurphy18** [comment]
@idontwanttosignin @ecstuchi Have you tried Salt 3004 to see if the changes in that release have resolved your issues.

**Comment by ecstuchi** [comment]
@dmurphy18, I upgraded the master to 3004 and I'm not able to reproduce the problem anymore.
It seems that it fixes the case for good.

I'll keep testing it over the week and we close the case if it's all good.

Thanks!

**Comment by ecstuchi** [comment]
Too early to celebrate:

`[ERROR   ] An un-handled exception was caught by salt's global exception handler:
KeyError: 'ret'
Traceback (most recent call last):
  File "/usr/bin/salt", line 11, in <module>
    load_entry_point('salt==3004', 'console_scripts', 'salt')()
  File "/usr/lib/python3.6/site-packages/salt/scripts.py", line 521, in salt_main
    client.run()
  File "/usr/lib/python3.6/site-packages/salt/cli/salt.py", line 108, in run
    self._run_batch()
  File "/usr/lib/python3.6/site-packages/salt/cli/salt.py", line 299, in _run_batch
    for res in batch.run():
  File "/usr/lib/python3.6/site-packages/salt/cli/batch.py", line 296, in run
    ret[minion] = data["ret"]
KeyError: 'ret'
Traceback (most recent call last):
  File "/usr/bin/salt", line 11, in <module>
    load_entry_point('salt==3004', 'console_scripts', 'salt')()
  File "/usr/lib/python3.6/site-packages/salt/scripts.py", line 521, in salt_main
    client.run()
  File "/usr/lib/python3.6/site-packages/salt/cli/salt.py", line 108, in run
    self._run_batch()
  File "/usr/lib/python3.6/site-packages/salt/cli/salt.py", line 299, in _run_batch
    for res in batch.run():
  File "/usr/lib/python3.6/site-packages/salt/cli/batch.py", line 296, in run
    ret[minion] = data["ret"]
KeyError: 'ret'`

It's still there.

**Comment by dmurphy18** [comment]
@ecstuchi Believe I have found the cause of the issue where there is no key 'ret' present in the data being processed for responses to jobs sent.

See https://github.com/saltstack/salt/blob/f65f953aba6166359b59d55c1a9a7e338b244259/salt/client/__init__.py#L1362-L1374

If the Minion which is expected to provide a response times out, the dictionary { minion_id: {"failed": True}} is returned.  No 'ret' key present, have a PR which allows for this situation and handles accordingly.

**Comment by ecstuchi** [comment]
I just upgraded my infrastructure to version 3004.2 and there is still an issue:

`
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
KeyError: 'ret'
Traceback (most recent call last):
  File "/usr/bin/salt", line 11, in <module>
    load_entry_point('salt==3004.2', 'console_scripts', 'salt')()
  File "/usr/lib/python3.6/site-packages/salt/scripts.py", line 521, in salt_main
    client.run()
  File "/usr/lib/python3.6/site-packages/salt/cli/salt.py", line 108, in run
    self._run_batch()
  File "/usr/lib/python3.6/site-packages/salt/cli/salt.py", line 299, in _run_batch
    for res in batch.run():
  File "/usr/lib/python3.6/site-packages/salt/cli/batch.py", line 296, in run
    ret[minion] = data["ret"]
KeyError: 'ret'
Traceback (most recent call last):
  File "/usr/bin/salt", line 11, in <module>
    load_entry_point('salt==3004.2', 'console_scripts', 'salt')()
  File "/usr/lib/python3.6/site-packages/salt/scripts.py", line 521, in salt_main
    client.run()
  File "/usr/lib/python3.6/site-packages/salt/cli/salt.py", line 108, in run
    self._run_batch()
  File "/usr/lib/python3.6/site-packages/salt/cli/salt.py", line 299, in _run_batch
    for res in batch.run():
  File "/usr/lib/python3.6/site-packages/salt/cli/batch.py", line 296, in run
    ret[minion] = data["ret"]
KeyError: 'ret'
[root@0cdf514bcd29 tmp]# salt --version
salt 3004.2
[root@0cdf514bcd29 tmp]# 
`
Should I file a new issue for it?
