### ISSUE TITLE
[BUG] Solaris 10 Intel get error if trying to add user if user already present on system.

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#60728]
**Description**
In Solaris 10 Intel get error if trying to add a user if the user already present on the system.
```
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "salt/state.py", line 2172, in call
                File "salt/loader.py", line 1241, in __call__
                File "salt/loader.py", line 2274, in run
                File "salt/loader.py", line 2289, in _run_as
                File "salt/loader.py", line 2322, in wrapper
                File "/opt/saltstack/salt/run/salt/states/user.py", line 689, in present
                  __salt__["file.mkdir"](val, pre["uid"], pre["gid"], 0o755)
                File "salt/loader.py", line 1241, in __call__
                File "salt/loader.py", line 2274, in run
                File "salt/loader.py", line 2289, in _run_as
                File "/opt/saltstack/salt/run/salt/modules/file.py", line 6321, in mkdir
                  makedirs_perms(directory, user, group, mode)
                File "/opt/saltstack/salt/run/salt/modules/file.py", line 6413, in makedirs_perms
                  os.mkdir(name)
              OSError: [Errno 89] Operation not applicable: '/home/dude'
```

**Setup**
```
cat /srv/salt/states.sls 
salt_dude:
  user.present:
    - name: dude
```

**Steps to Reproduce the behavior**
Run the state file twice

**Expected behavior**
I am expecting this result on the second run.
```
User dude is present and up to date
```

**Screenshots**
```
[root@li1167-223 ~]# cat /srv/salt/states.sls 
salt_dude:
  user.present:
    - name: dude

[root@li1167-223 ~]# salt \* state.sls states
solaris_10_intel:
----------
          ID: salt_dude
    Function: user.present
        Name: dude
      Result: True
     Comment: New user dude created
     Started: 14:44:23.406656
    Duration: 2063.048 ms
     Changes:   
              ----------
              fullname:
              gid:
                  1
              groups:
                  - other
              home:
                  /home/dude
              homephone:
              name:
                  dude
              passwd:
                  x
              roomnumber:
              shell:
                  /bin/sh
              uid:
                  100
              workphone:

Summary for solaris_10_intel
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   2.063 s
[root@li1167-223 ~]# salt \* state.sls states
solaris_10_intel:
----------
          ID: salt_dude
    Function: user.present
        Name: dude
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "salt/state.py", line 2172, in call
                File "salt/loader.py", line 1241, in __call__
                File "salt/loader.py", line 2274, in run
                File "salt/loader.py", line 2289, in _run_as
                File "salt/loader.py", line 2322, in wrapper
                File "/opt/saltstack/salt/run/salt/states/user.py", line 689, in present
                  __salt__["file.mkdir"](val, pre["uid"], pre["gid"], 0o755)
                File "salt/loader.py", line 1241, in __call__
                File "salt/loader.py", line 2274, in run
                File "salt/loader.py", line 2289, in _run_as
                File "/opt/saltstack/salt/run/salt/modules/file.py", line 6321, in mkdir
                  makedirs_perms(directory, user, group, mode)
                File "/opt/saltstack/salt/run/salt/modules/file.py", line 6413, in makedirs_perms
                  os.mkdir(name)
              OSError: [Errno 89] Operation not applicable: '/home/dude'
     Started: 14:44:30.263333
    Duration: 2350.626 ms
     Changes:   

Summary for solaris_10_intel
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   2.351 s
ERROR: Minions returned with non-zero exit code
[root@li1167-223 ~]# 

```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
    Salt Version:
              Salt: 3003.1
     
    Dependency Versions:
              cffi: 1.14.4
          cherrypy: 17.4.1
          dateutil: 2.8.1
         docker-py: Not Installed
             gitdb: Not Installed
         gitpython: Not Installed
            Jinja2: 2.11.3
           libgit2: Not Installed
          M2Crypto: 0.38.0
              Mako: Not Installed
           msgpack: 1.0.2
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         pycparser: 2.17
          pycrypto: Not Installed
      pycryptodome: 3.9.8
            pygit2: Not Installed
            Python: 3.7.10 (default, Aug 12 2021, 12:04:27)
      python-gnupg: 0.4.4
            PyYAML: 5.4.1
             PyZMQ: 18.0.1
             smmap: Not Installed
           timelib: 0.2.4
           Tornado: 4.5.3
               ZMQ: 4.3.3
     
    System Versions:
              dist: sunos 5.10 
            locale: utf-8
           machine: i86pc
           release: 5.10
            system: SunOS
           version: SunOS 5.10 
```
</details>

**Additional context**

**Comment by dmurphy18** [comment]
That looks like a Salt error not handling case of Solaris where the would expect to typically be /export/home/dude  for a user named dude

**Comment by dmurphy18** [comment]
On a clean Solaris 10 Intel machine, the provided example fails, **the first time**

```
root@c7mstr:/srv/salt# salt tsol10 test.versions
tsol10:
    Salt Version:
              Salt: 3004
     
    Dependency Versions:
              cffi: 1.14.3
          cherrypy: Not Installed
          dateutil: Not Installed
         docker-py: Not Installed
             gitdb: Not Installed
         gitpython: Not Installed
            Jinja2: 3.0.2
           libgit2: Not Installed
          M2Crypto: 0.38.0
              Mako: Not Installed
           msgpack: 1.0.2
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         pycparser: 2.17
          pycrypto: Not Installed
      pycryptodome: 3.11.0
            pygit2: Not Installed
            Python: 3.7.10 (default, Oct 20 2021, 17:42:44)
      python-gnupg: Not Installed
            PyYAML: 6.0
             PyZMQ: 21.0.2
             smmap: Not Installed
           timelib: 0.2.4
           Tornado: 4.5.3
               ZMQ: 4.3.3
     
    System Versions:
              dist: sunos 5.10 
            locale: UTF-8
           machine: i86pc
           release: 5.10
            system: SunOS
           version: SunOS 5.10 
     
root@c7mstr:/srv/salt# salt tsol10 state.sls file_sol10
tsol10:
----------
          ID: salt_david
    Function: user.present
        Name: david
      Result: False
     Comment: Failed to create new user david
     Started: 17:13:58.582448
    Duration: 77.57 ms
     Changes:   

Summary for tsol10
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:  77.570 ms
ERROR: Minions returned with non-zero exit code
root@c7mstr:/srv/salt# 
root@c7mstr:/srv/salt# l file_sol10.sls
-rw-r--r--. 1 root root 46 Feb  3 16:18 file_sol10.sls
root@c7mstr:/srv/salt# cat file_sol10.sls
salt_david:
  user.present:
    - name: david
root@c7mstr:/srv/salt# 
```

**Comment by dmurphy18** [comment]
Log file for the minion
```
   411  2022-02-03 17:13:58,567 [salt.transport.zeromq:1180][DEBUG   ][1219] Trying to connect to: tcp://192.168.0.105:4506
   412  2022-02-03 17:13:58,573 [salt.template    :28  ][PROFILE ][1219] Time (in seconds) to render '/var/cache/salt/minion/files/base/file_sol10.sls' using 'jinja' renderer: 0.012995243072509766
   413  2022-02-03 17:13:58,573 [salt.template    :120 ][DEBUG   ][1219] Rendered data from file: /var/cache/salt/minion/files/base/file_sol10.sls:
   414  salt_david:
   415    user.present:
   416      - name: david
   417
   418  2022-02-03 17:13:58,573 [salt.loaded.int.render.yaml:79  ][DEBUG   ][1219] Results of YAML rendering:
   419  OrderedDict([('salt_david', OrderedDict([('user.present', [OrderedDict([('name', 'david')])])]))])
   420  2022-02-03 17:13:58,574 [salt.template    :28  ][PROFILE ][1219] Time (in seconds) to render '/var/cache/salt/minion/files/base/file_sol10.sls' using 'yaml' renderer: 0.0005054473876953125
   421  2022-02-03 17:13:58,577 [salt.utils.lazy  :99  ][DEBUG   ][1219] LazyLoaded config.option
   422  2022-02-03 17:13:58,582 [salt.utils.lazy  :99  ][DEBUG   ][1219] LazyLoaded user.present
   423  2022-02-03 17:13:58,582 [salt.state       :2065][INFO    ][1219] Running state [david] at time 17:13:58.582448
   424  2022-02-03 17:13:58,582 [salt.state       :2097][INFO    ][1219] Executing state user.present for [david]
   425  2022-02-03 17:13:58,584 [salt.loader.lazy :37  ][TRACE   ][1219] Error loading module.aix_shadow: The aix_shadow execution module failed to load: only available on AIX systems.
   426  2022-02-03 17:13:58,610 [salt.loader.lazy :37  ][TRACE   ][1219] Error loading module.bsd_shadow: The bsd_shadow execution module cannot be loaded: only available on BSD family systems.
   427  2022-02-03 17:13:58,615 [salt.loader.lazy :37  ][TRACE   ][1219] Error loading module.mac_shadow: Not macOS
   428  2022-02-03 17:13:58,616 [salt.loader.lazy :37  ][TRACE   ][1219] Loaded solaris_shadow as virtual shadow
   429  2022-02-03 17:13:58,616 [salt.utils.lazy  :99  ][DEBUG   ][1219] LazyLoaded shadow.info
   430  2022-02-03 17:13:58,619 [salt.loader.lazy :37  ][TRACE   ][1219] Error loading module.mac_user: Only available on Mac OS 10.7+ systems
   431  2022-02-03 17:13:58,620 [salt.loader.lazy :37  ][TRACE   ][1219] Error loading module.napalm_users: "users"" (/opt/saltstack/salt/run/salt/modules/napalm_users.py) cannot be loaded: NAPALM is not i
nstalled: ``pip install napalm``
   432  2022-02-03 17:13:58,622 [salt.loader.lazy :37  ][TRACE   ][1219] Error loading module.pw_user: The pw_user execution module cannot be loaded: the pwd python module is not available or the system is
 not FreeBSD.
   433  2022-02-03 17:13:58,624 [salt.loader.lazy :37  ][TRACE   ][1219] Loaded solaris_user as virtual user
   434  2022-02-03 17:13:58,624 [salt.utils.lazy  :99  ][DEBUG   ][1219] LazyLoaded user.info
   435  2022-02-03 17:13:58,625 [salt.loaded.int.module.solaris_user:126 ][WARNING ][1219] Invalid kwargs passed to user.add
   436  2022-02-03 17:13:58,637 [salt.loader.lazy :37  ][TRACE   ][1219] Loaded cmdmod as virtual cmd
   437  2022-02-03 17:13:58,637 [salt.utils.lazy  :99  ][DEBUG   ][1219] LazyLoaded cmd.retcode
   438  2022-02-03 17:13:58,637 [salt.loaded.int.module.cmdmod:417 ][INFO    ][1219] Executing command useradd in directory '/'
   439  2022-02-03 17:13:58,658 [salt.loaded.int.module.cmdmod:877 ][ERROR   ][1219] Command 'useradd' failed with return code: 12
   440  2022-02-03 17:13:58,658 [salt.loaded.int.module.cmdmod:879 ][ERROR   ][1219] stdout: UX: useradd: ERROR: Unable to create the home directory: Operation not applicable.
   441  2022-02-03 17:13:58,659 [salt.loaded.int.module.cmdmod:883 ][ERROR   ][1219] retcode: 12
   442  2022-02-03 17:13:58,659 [salt.state       :317 ][ERROR   ][1219] Failed to create new user david
   443  2022-02-03 17:13:58,660 [salt.state       :2252][INFO    ][1219] Completed state [david] at time 17:13:58.660018 (duration_in_ms=77.57)
   444  2022-02-03 17:13:58,660 [salt.state       :3291][DEBUG   ][1219] File /var/cache/salt/minion/accumulator/3402890252 does not exist, no need to cleanup
   445  2022-02-03 17:13:58,661 [salt.transport.zeromq:177 ][DEBUG   ][1219] Closing AsyncZeroMQReqChannel instance
   446  2022-0
2-03 17:13:58,665 [salt.utils.lazy  :99  ][DEBUG   ][1219] LazyLoaded state.check_result
```
This is probably due to home directories on Solaris are **_/export/home_** and not **_/home_** as on Linux.

**Comment by dmurphy18** [comment]
Correct operation is show below:

```
root@c7mstr:/srv/salt# salt tsol10 state.sls file_sol10
tsol10:
----------
          ID: salt_david
    Function: user.present
        Name: david
      Result: True
     Comment: New user david created
     Started: 17:31:29.595341
    Duration: 2110.383 ms
     Changes:   
              ----------
              fullname:
              gid:
                  1
              groups:
                  - other
              home:
                  /export/home/david
              homephone:
              name:
                  david
              passwd:
                  x
              roomnumber:
              shell:
                  /usr/bin/bash
              uid:
                  100
              workphone:

Summary for tsol10
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   2.110 s
root@c7mstr:/srv/salt# cat file_sol10.sls 
salt_david:
  user.present:
    - name: david
    - home: /export/home/david
    - shell: /usr/bin/bash
root@c7mstr:/srv/salt# salt tsol10 state.sls file_sol10
tsol10:
----------
          ID: salt_david
    Function: user.present
        Name: david
      Result: True
     Comment: User david is present and up to date
     Started: 17:31:58.051425
    Duration: 2434.963 ms
     Changes:   

Summary for tsol10
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:   2.435 s
root@c7mstr:/srv/salt# 
```
Repeated execution of the state file succeeds, with the home directory specified.
The original state file which did not specify a home directory failed since no directory for home specified, that is, lack of -d option for useradd
```
  1383  2022-02-03 17:28:19,253 [salt.utils.lazy  :99  ][DEBUG   ][1250] LazyLoaded user.info
  1384  2022-02-03 17:28:19,253 [salt.loaded.int.module.solaris_user:123 ][DEBUG   ][1250] DGM solaris user add kwargs '{'system': False, 'other': None, 'nologinit': False, 'loginclass': None, 'usergroup':
 None}'
  1385  2022-02-03 17:28:19,254 [salt.loaded.int.module.solaris_user:128 ][WARNING ][1250] Invalid kwargs passed to user.add
  1386  2022-02-03 17:28:19,254 [salt.loaded.int.module.solaris_user:148 ][DEBUG   ][1250] DGM solaris user add cmd '['useradd', '-m', 'david']'
  1387  2022-02-03 17:28:19,267 [salt.loader.lazy :37  ][TRACE   ][1250] Loaded cmdmod as virtual cmd
  1388  2022-02-03 17:28:19,268 [salt.utils.lazy  :99  ][DEBUG   ][1250] LazyLoaded cmd.retcode
  1389  2022-02-03 17:28:19,268 [salt.loaded.int.module.cmdmod:417 ][INFO    ][1250] Executing command useradd in directory '/'
  1390  2022-02-03 17:28:19,291 [salt.loaded.int.module.cmdmod:877 ][ERROR   ][1250] Command 'useradd' failed with return code: 12
  1391  2022-02-03 17:28:19,292 [salt.loaded.int.module.cmdmod:879 ][ERROR   ][1250] stdout: UX: useradd: ERROR: Unable to create the home directory: Operation not applicable.
  1392  2022-02-03 17:28:19,292 [salt.loaded.int.module.cmdmod:883 ][ERROR   ][1250] retcode: 12
  1393  2022-02-03 17:28:19,293 [salt.state       :317 ][ERROR   ][1250] Failed to create new user david
```
as seen in the successful state file
```
  1668  2022-02-03 17:31:29,626 [salt.utils.lazy  :99  ][DEBUG   ][1265] LazyLoaded user.info
  1669  2022-02-03 17:31:29,626 [salt.loaded.int.module.solaris_user:123 ][DEBUG   ][1265] DGM solaris user add kwargs '{'system': False, 'other': None, 'nologinit': False, 'loginclass': None, 'usergroup':
 None}'
  1670  2022-02-03 17:31:29,627 [salt.loaded.int.module.solaris_user:128 ][WARNING ][1265] Invalid kwargs passed to user.add
  1671  2022-02-03 17:31:29,627 [salt.loaded.int.module.solaris_user:148 ][DEBUG   ][1265] DGM solaris user add cmd '['useradd', '-s', '/usr/bin/bash', '-m', '-d', '/export/home/david', 'david']'
  1672  2022-02-03 17:31:29,641 [salt.loader.lazy :37  ][TRACE   ][1265] Loaded cmdmod as virtual cmd
  1673  2022-02-03 17:31:29,641 [salt.utils.lazy  :99  ][DEBUG   ][1265] LazyLoaded cmd.retcode
  1674  2022-02-03 17:31:29,641 [salt.loaded.int.module.cmdmod:417 ][INFO    ][1265] Executing command useradd in directory '/'
  1675  2022-02-03 17:31:29,692 [salt.loaded.int.module.cmdmod:879 ][DEBUG   ][1265] stdout: 64 blocks
  1676  2022-02-03 17:31:30,096 [salt.utils.schedule:37  ][TRACE   ][1160] ==== evaluating schedule now None =====
  1677  2022-02-03 17:31:31,099 [salt.utils.schedule:37  ][TRACE   ][1160] ==== evaluating schedule now None =====
  1678  2022-02-03 17:31:31,697 [salt.utils.user  :37  ][TRACE   ][1265] Trying generic group list for 'david'
  1679  2022-02-03 17:31:31,702 [salt.utils.user  :37  ][TRACE   ][1265] Group list for user 'david': ['other']
  1680  2022-02-03 17:31:31,704 [salt.state       :315 ][INFO    ][1265] {'gid': 1, 'groups': ['other'], 'home': '/export/home/david', 'name': 'david', 'passwd': 'x', 'shell': '/usr/bin/bash', 'uid': 100,
'fullname': '', 'roomnumber': '', 'workphone': '', 'homephone': ''}
  1681  2022-02-03 17:31:31,706 [salt.state       :2252][INFO    ][1265] Completed state [david] at time 17:31:31.705724 (duration_in_ms=2110.383)
```

This was using Salt 3004 for Solaris 10
```
root@c7mstr:/srv/salt# salt tsol10 test.versions
tsol10:
    Salt Version:
              Salt: 3004
     
    Dependency Versions:
              cffi: 1.14.3
          cherrypy: Not Installed
          dateutil: Not Installed
         docker-py: Not Installed
             gitdb: Not Installed
         gitpython: Not Installed
            Jinja2: 3.0.2
           libgit2: Not Installed
          M2Crypto: 0.38.0
              Mako: Not Installed
           msgpack: 1.0.2
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         pycparser: 2.17
          pycrypto: Not Installed
      pycryptodome: 3.11.0
            pygit2: Not Installed
            Python: 3.7.10 (default, Oct 20 2021, 17:42:44)
      python-gnupg: Not Installed
            PyYAML: 6.0
             PyZMQ: 21.0.2
             smmap: Not Installed
           timelib: 0.2.4
           Tornado: 4.5.3
               ZMQ: 4.3.3
     
    System Versions:
              dist: sunos 5.10 
            locale: UTF-8
           machine: i86pc
           release: 5.10
            system: SunOS
           version: SunOS 5.10 
     
root@c7mstr:/srv/salt# 
```

**Comment by dmurphy18** [comment]
@frogunder What do you want to do with this, close it ?, since not even the initial provided state file works correctly, hence failed to reproduce

**Comment by dmurphy18** [comment]
the https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.solaris_user.html#salt.modules.solaris_user.add

is really at fault, home=None, is a bad default there, but wonder if worth fixing given this Solaris 10 is EOL 2023.

**Comment by dmurphy18** [comment]
Closing as not reproducible.
