### ISSUE TITLE
[BUG] Zombie process in salt-master 3003.2

### ISSUE THREAD

**Issue by OrangeDog** [saltstack/salt#60749]
**Description**
```
    PID F STAT NLWP     TIME COMMAND
 103743 4 Ss      1        1 /usr/bin/python3 /usr/bin/salt-master
 103761 1 Z       1        0  \_ [salt-master] <defunct>
 103774 1 Sl      3        0  \_ /usr/bin/python3 /usr/bin/salt-master
 103775 1 S       1        1  \_ /usr/bin/python3 /usr/bin/salt-master
 103778 1 S       1       15  \_ /usr/bin/python3 /usr/bin/salt-master
 103779 1 S       1        0  \_ /usr/bin/python3 /usr/bin/salt-master
 103780 1 Sl      7       12      \_ /usr/bin/python3 /usr/bin/salt-master
 103788 1 Sl      5       68      \_ /usr/bin/python3 /usr/bin/salt-master
 103790 1 Sl      5       75      \_ /usr/bin/python3 /usr/bin/salt-master
 103791 1 Sl      5       64      \_ /usr/bin/python3 /usr/bin/salt-master
 103792 1 Sl      5       64      \_ /usr/bin/python3 /usr/bin/salt-master
 103793 1 Sl      5       73      \_ /usr/bin/python3 /usr/bin/salt-master
```

**Steps to Reproduce the behavior**
Unsure. Has happened twice but not yet found the cause.
This exception looks to be related (has also happened twice)
```
2021-08-17 11:40:08,105 [tornado.application][ERROR   ] Future <salt.ext.tornado.concurrent.Future object at 0x7f80e093c7c0> exception was never retrieved: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/gen.py", line 309, in wrapper
    yielded = next(result)
  File "/usr/lib/python3/dist-packages/salt/utils/process.py", line 664, in run
    self.check_children()
  File "/usr/lib/python3/dist-packages/salt/utils/process.py", line 689, in check_children
    for pid, mapping in self._process_map.items():
RuntimeError: dictionary keys changed during iteration
```

**Expected behavior**
Child processes should be awaited correctly.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3003.2

Dependency Versions:
          cffi: 1.14.5
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.10.1
       libgit2: 1.1.0
      M2Crypto: 0.31.0
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: 1.6.1
        Python: 3.8.10 (default, Jun  2 2021, 10:49:15)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-81-generic
        system: Linux
       version: Ubuntu 20.04 focal
```
</details>

**Comment by OrangeDog** [comment]
It just happened again, with another instance of that exception appearing.

It's not (consistently) caused by sending minion commands, `cmd.run`, `state.apply`, nor `fileserver.update`.

**Comment by goapunk** [comment]
Same for me. happens on both our servers, here are some logs. I'm pretty sure I didn't run any command, it just happens randomly/event-based. 
<details><summary>Log Server 1</summary><p>

```
[salt.utils.process:909 ][ERROR   ][42833] An un-handled exception from the multiprocessing process 'MWorker-1' was caught:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/ioloop.py", line 865, in start
    event_pairs = self._impl.poll(poll_timeout)
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1019, in _handle_signals
    self.clear_funcs.destroy()
  File "/usr/lib/python3/dist-packages/salt/master.py", line 2514, in destroy
    self.masterapi.destroy()
  File "/usr/lib/python3/dist-packages/salt/daemons/masterapi.py", line 1430, in destroy
    self.local.destroy()
  File "/usr/lib/python3/dist-packages/salt/client/__init__.py", line 2055, in destroy
    self.event.destroy()
  File "/usr/lib/python3/dist-packages/salt/utils/event.py", line 841, in destroy
    self.io_loop.close()
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/ioloop.py", line 722, in close
    self._waker.close()
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/platform/posix.py", line 71, in close
    common.try_close(self.writer)
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/platform/common.py", line 18, in try_close
    f.close()
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1019, in _handle_signals
    self.clear_funcs.destroy()
  File "/usr/lib/python3/dist-packages/salt/master.py", line 2514, in destroy
    self.masterapi.destroy()
  File "/usr/lib/python3/dist-packages/salt/daemons/masterapi.py", line 1430, in destroy
    self.local.destroy()
  File "/usr/lib/python3/dist-packages/salt/client/__init__.py", line 2055, in destroy
    self.event.destroy()
  File "/usr/lib/python3/dist-packages/salt/utils/event.py", line 841, in destroy
    self.io_loop.close()
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/ioloop.py", line 718, in close
    self.remove_handler(self._waker.fileno())
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/platform/posix.py", line 49, in fileno
    return self.reader.fileno()
ValueError: I/O operation on closed file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/process.py", line 904, in wrapped_run_func
    return run_func()
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1177, in run
    self.__bind()
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1035, in __bind
    self.io_loop.start()
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/ioloop.py", line 872, in start
    if errno_from_exception(e) == errno.EINTR:
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/util.py", line 221, in errno_from_exception
    if hasattr(e, 'errno'):
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1019, in _handle_signals
    self.clear_funcs.destroy()
  File "/usr/lib/python3/dist-packages/salt/master.py", line 2514, in destroy
    self.masterapi.destroy()
  File "/usr/lib/python3/dist-packages/salt/daemons/masterapi.py", line 1430, in destroy
    self.local.destroy()
  File "/usr/lib/python3/dist-packages/salt/client/__init__.py", line 2055, in destroy
    self.event.destroy()
  File "/usr/lib/python3/dist-packages/salt/utils/event.py", line 841, in destroy
    self.io_loop.close()
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/ioloop.py", line 718, in close
    self.remove_handler(self._waker.fileno())
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/platform/posix.py", line 49, in fileno
    return self.reader.fileno()
ValueError: I/O operation on closed file

```

</p></details>

<details><summary>Log Server 2</summary><p>

```
[salt.utils.process:909 ][ERROR   ][1743] An un-handled exception from the multiprocessing process 'MWorker-1' was caught:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/process.py", line 904, in wrapped_run_func
    return run_func()
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1177, in run
    self.__bind()
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1035, in __bind
    self.io_loop.start()
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/ioloop.py", line 865, in start
    event_pairs = self._impl.poll(poll_timeout)
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1018, in _handle_signals
    channel.close()
  File "/usr/lib/python3/dist-packages/salt/transport/zeromq.py", line 752, in close
    self.context.term()
  File "zmq/backend/cython/context.pyx", line 91, in zmq.backend.cython.context.Context.term
  File "zmq/backend/cython/checkrc.pxd", line 12, in zmq.backend.cython.checkrc._check_rc
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1019, in _handle_signals
    self.clear_funcs.destroy()
  File "/usr/lib/python3/dist-packages/salt/master.py", line 2514, in destroy
    self.masterapi.destroy()
  File "/usr/lib/python3/dist-packages/salt/daemons/masterapi.py", line 1430, in destroy
    self.local.destroy()
  File "/usr/lib/python3/dist-packages/salt/client/__init__.py", line 2055, in destroy
    self.event.destroy()
  File "/usr/lib/python3/dist-packages/salt/utils/event.py", line 841, in destroy
    self.io_loop.close()
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/ioloop.py", line 722, in close
    self._waker.close()
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/platform/posix.py", line 71, in close
    common.try_close(self.writer)
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/platform/common.py", line 18, in try_close
    f.close()
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1019, in _handle_signals
    self.clear_funcs.destroy()
  File "/usr/lib/python3/dist-packages/salt/master.py", line 2514, in destroy
    self.masterapi.destroy()
  File "/usr/lib/python3/dist-packages/salt/daemons/masterapi.py", line 1430, in destroy
    self.local.destroy()
  File "/usr/lib/python3/dist-packages/salt/client/__init__.py", line 2055, in destroy
    self.event.destroy()
  File "/usr/lib/python3/dist-packages/salt/utils/event.py", line 841, in destroy
    self.io_loop.close()
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/ioloop.py", line 718, in close
    self.remove_handler(self._waker.fileno())
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/platform/posix.py", line 49, in fileno
    return self.reader.fileno()
ValueError: I/O operation on closed file
2021-08-18 03:45:01,912 [salt.utils.parsers:1104][WARNING ][1545] Master received a SIGTERM. Exiting.
2021-08-18 03:52:18,595 [tornado.application:353 ][ERROR   ][1573] Future <salt.ext.tornado.concurrent.Future object at 0x7f3334aaee20> exception was never retrieved: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/gen.py", line 309, in wrapper
    yielded = next(result)
  File "/usr/lib/python3/dist-packages/salt/utils/process.py", line 664, in run
    self.check_children()
  File "/usr/lib/python3/dist-packages/salt/utils/process.py", line 689, in check_children
    for pid, mapping in self._process_map.items():
RuntimeError: dictionary keys changed during iteration


```

</p></details>

**Comment by goapunk** [comment]
Probably related/caused by https://github.com/saltstack/salt/pull/60386 ?

**Comment by OrangeDog** [comment]
A day later there's still only one zombie process. One one hand that's not going to break the server, but on the other hand that probably means whatever it was supposed to be doing is stuck forever.

**Comment by OrangeDog** [comment]
> whatever it was supposed to be doing is stuck forever

I can confirm that the gitfs backend doesn't update by itself any more.
