### ISSUE TITLE
Regression in state.ldap module

### ISSUE THREAD

**Issue by matwey** [saltstack/salt#60760]
**Description**
```
----------
          ID: ldapi:///
    Function: ldap.managed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 2171, in call
                  ret = self.states[cdata["full"]](
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 1241, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2274, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2289, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2322, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/ldap.py", line 257, in managed
                  old, new = _process_entries(l, entries)
                File "/usr/lib/python3/dist-packages/salt/states/ldap.py", line 450, in _process_entries
                  _update_entry(newe, entry_status, directives)
                File "/usr/lib/python3/dist-packages/salt/states/ldap.py", line 483, in _update_entry
                  vals.update(entry.get(attr, ()))
              AttributeError: 'list' object has no attribute 'update'
```

**Setup**
```
      - cn=Administrator:
        - default:
            cn:
              - Administrator
            objectClass:
              - organizationalRole
        - add:
            roleOccupant:
              - somecn
```
  
**Steps to Reproduce the behavior**
Use sls above and run `salt-call`

**Expected behavior**
salt not crashing

**Versions Report**
```
Salt Version:
          Salt: 3003.2

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.8.10 (default, Jun  2 2021, 10:49:15)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-81-generic
        system: Linux
       version: Ubuntu 20.04 focal

```
</details>

**Additional context**
I suppose that the issue is produced by ea30f817942c9c5ee59bbd19b1c0fbcee8102844

**Comment by OrangeDog** [comment]
Yep. Should have been a set comprehension, not a list comprehension.

**Comment by OrangeDog** [comment]
The fix is not as obvious as you might think. It's all set up with `_toset()` to compare everything as `str`, yet this tries to combine it with `to_bytes`. It probably needs to convert the bytes elsewhere to str instead of having this one `OrderedSet` contain bytes.

**Comment by s0undt3ch** [comment]
A possible fix can be:
`vals = {to_bytes(val) for val in _toset(vals)}` based on the suggested https://github.com/saltstack/salt/commit/ea30f817942c9c5ee59bbd19b1c0fbcee8102844 change

**Comment by OrangeDog** [comment]
@s0undt3ch that won't give you an `OrderedDict`, and it won't be comparable to other `_toset()` returns.

**Comment by garethgreenaway** [comment]
@matwey Can you provide an example of the state you're trying to use with the `ldap.managed` state function?

**Comment by garethgreenaway** [comment]
Never mind, I was able to reproduce this one.

**Comment by garethgreenaway** [comment]
Since `vals` is now a list using `extend` instead of update.  And since we want everything to be an `OrderedSet` popping that in too:
```python
diff --git a/salt/states/ldap.py b/salt/states/ldap.py
index ebfcd7db97..3cfdd9a7a9 100644
--- a/salt/states/ldap.py
+++ b/salt/states/ldap.py
@@ -343,7 +343,7 @@ def managed(name, entries, connect_spec=None):
                 ret["result"] = False
                 ret["comment"] = "failed to " + ", ".join(
                     (
-                        op + " entry " + dn + "(" + err.items() + ")"
+                        op + " entry " + dn + "(" + str(err) + ")"
                         for op, dn, err in errs
                     )
                 )
@@ -478,17 +478,17 @@ def _update_entry(entry, status, directives):
             vals = [to_bytes(val) for val in _toset(vals)]
             if directive == "default":
                 if vals and (attr not in entry or not entry[attr]):
-                    entry[attr] = vals
+                    entry[attr] = OrderedSet(vals)
             elif directive == "add":
-                vals.update(entry.get(attr, ()))
+                vals.extend(entry.get(attr, []))
                 if vals:
-                    entry[attr] = vals
+                    entry[attr] = OrderedSet(vals)
             elif directive == "delete":
                 existing_vals = entry.pop(attr, OrderedSet())
                 if vals:
                     existing_vals -= vals
                     if existing_vals:
-                        entry[attr] = existing_vals
+                        entry[attr] = OrderedSet(existing_vals)
             elif directive == "replace":
                 entry.pop(attr, None)
                 if vals:
```

**Comment by garethgreenaway** [comment]
@matwey If you're able to test these changes that would be great, @OrangeDog any feedback is of course welcome.  Thanks!
