### ISSUE TITLE
[DOCS]  Adding gitlab config info in GIT FILESERVER BACKEND WALKTHROUGH

### ISSUE THREAD

**Issue by tjyang** [saltstack/salt#60809]
**Description**
After following through R1 doc and a few issues here in the past,  I am still not able to have a good gitfs from gitlab server. 

**Suggested Fix**
Can I trouble dev or doc team to add info specifically for gitlab backend server ? 

**Type of documentation**
how to enable gitfs on  SaltStack server (version above 3003) to gitlab repository ?

**Location or format of documentation**
R1: https://docs.saltproject.io/en/latest/topics/tutorials/gitfs.html

**Additional context**

**Comment by OrangeDog** [comment]
There's nothing special about GitLab. The only difference would be the URL says "gitlab" instead of "github".

**Comment by tjyang** [comment]
@OrangeDog, 

Can you please try to  provide a simple and working example like following ones ? 

- The error lines below are the one I see from /var/log/salt/master

```
# gitlab example
## ERROR: _pygit2.GitError: Error receiving socket data: Connection reset by peer
#  - git://gitlab.com/tjyang/mysalt.git:
#     - pubkey:  /home/tjyang/.ssh/id_dsa.pub
#     - privkey: /home/tjyang/.ssh/id_dsa
#     - mountpoint: salt://test01-gitlab

# Error: _pygit2.GitError: unsupported URL protocol
#  - git@gitlab.com:tjyang/mysalt.git:
#     - pubkey:  /home/tjyang/.ssh/id_rsa.pub
#     - privkey: /home/tjyang/.ssh/id_rsa
#     - mountpoint: salt://test01-gitlab
```

- Let me know if you need further details from my test box.

**Comment by OrangeDog** [comment]
What versions of pygit2 and libgit2 to do you have and how were they installed?
The second version should work, but only if libgit2 has ssh support.

**Comment by tjyang** [comment]
-  I followed the doc at https://repo.saltproject.io/#rhel using latest version.
- Using git:// protocol is currently working on CentOS 7 instance but not newer version of salt and CentOS 8.
- Please see details below from "/usr/bin/salt-master -V", I can test this on CentOS 8 or RHEL 8 if you like.
<details>
Salt Version:
          Salt: 3003.2

Dependency Versions:
          cffi: 1.11.5
      cherrypy: 18.4.0
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: 4.0.1
     gitpython: 3.0.9
        Jinja2: 2.10.1
       libgit2: 0.26.8
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.14
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: 0.26.4
        Python: 3.6.8 (default, May 19 2021, 03:00:47)
  python-gnupg: Not Installed
        PyYAML: 3.12
         PyZMQ: 19.0.0
         smmap: 3.0.1
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: rocky 8.4 Green Obsidian
        locale: UTF-8
       machine: x86_64
       release: 4.18.0-305.12.1.el8_4.x86_64
        system: Linux
       version: Rocky Linux 8.4 Green Obsidian
</details>

**Comment by bryceml** [comment]
gitlab.com does not support the git protocol, only ssh and https.

**Comment by tjyang** [comment]
@bryceml , Thanks for the update only ssh and https protocols are supported on gitlab.com. I am using gitlab.com as example , my target is private gitlab-ce in intranet. 

In the R1 doc, Can a section with  working example of using ssh or https protocol with gitlab  be added ?

**Comment by OrangeDog** [comment]
> example of using ssh or https protocol with gitlab

It already has `https://` and `git@` examples. That's why I said that one should work, not the `git://` one.

> python3-GitPython.noarch for libgit2

That's not libgit2, that's GitPython. Have you actually got libgit2 installed, and if so what version? Have you got libssh2 as well?

The documentation has all the details you need:

> If you are receiving the error "Unsupported URL Protocol" in the Salt Master log when making a connection using SSH, review the libssh2 details listed above.

**Comment by tjyang** [comment]
@OrangeDog 

>python3-GitPython.noarch for libgit2
>>That's not libgit2, that's GitPython. Have you actually got libgit2 installed, and if so what version? Have you got libssh2 as well?
I am testing both pygit2 and gitpython backend thus the python3-GitPython rpm install, thanks for correction about libgit2. 
libssh2 rpm was missed and now just installed, let my try "git@" protocol again.

**Comment by tjyang** [comment]
-  Using git@ protocol with gitlab.com

```
- ssh://git@gitlab.com/tjyang/mysalt.git:
   - pubkey:  /home/tjyang/.ssh/id_rsa.pub
   - privkey: /home/tjyang/.ssh/id_rsa
   - mountpoint: salt://test01-gitlab-com-ssh
```
- errors
<details>

2021-08-30 14:33:33,378 [salt.utils.gitfs :1877][ERROR   ][882815] Unable to fetch SSH-based gitfs remote 'ssh://git@gitlab.com/tjyang/mysalt.git'. You may need to add ssh:// to the repo string or libgit2 must be compiled with libssh2 to support SSH authentication.
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/gitfs.py", line 1864, in _fetch
    fetch_results = origin.fetch(**fetch_kwargs)
  File "/usr/lib64/python3.6/site-packages/pygit2/remote.py", line 405, in fetch
    check_error(err)
  File "/usr/lib64/python3.6/site-packages/pygit2/errors.py", line 64, in check_error
    raise GitError(message)
_pygit2.GitError: unsupported URL protocol

</details>

-  On RHEL/CentOS/RockyLinux 8, How can I confirm libgit2 rpm is compiled  with libssh2 to support SSH authentication

**Comment by tjyang** [comment]
- This is what I found out, libgit2 rpm in  RHEL/CentOS/OL 8 not compiled with libssh2 support.
```
[tjyang@rocky8t01 SOURCES]$ more README.rhel8
This version of libgit2 is built without ssh support.  libssh2 is not shipped
with RHEL 8 so the USE_SSH flag has been set to OFF in the build.
[tjyang@rocky8t01 SOURCES]$ pwd
/home/tjyang/rpmbuild/SOURCES
[tjyang@rocky8t01 SOURCES]$ dnf download --source libgit2

```

**Comment by tjyang** [comment]
- RL8: Re-enable libgit2 to use libssh2
```
- prepare your rpmbuild environment.
- dnf download --source libgit2
- recompile libgit2 rpm
    - add this line "BuildRequires:  libssh2-devel"
   - change " %cmake -DTHREADSAFE=ON -DUSE_SSH=OFF.." to " %cmake -DTHREADSAFE=ON -DUSE_SSH=ON .." in libgit2.spec
- rpmbuild -ba libgit2.spec
- sudo rpm --force -ivh /home/tjyang/rpmbuild/RPMS/x86_64/libgit2-0.26.8-2.el8.x86_64.rpm
```
- with ssh:// protcol in master file.

```
- ssh://git@gitlab.com/tjyang/mysalt.git:
   - pubkey:  /home/tjyang/.ssh/id_rsa.pub
   - privkey: /home/tjyang/.ssh/id_rsa
   - mountpoint: salt://test01-gitlab-com-ssh
```
- verification

```
[root@rocky8t01 salt]# salt-run  fileserver.file_list|grep ssh
- test01-gitlab-com-ssh/README.txt
[root@rocky8t01 salt]#
```
- In summary for running python3 salt-master on RHEL/CentOS/RL8 
- ssh:// protocol works  if libgit2 rpm got recompiled to build with libssh2. 
- https:// protocol works without recompiling libgit2 rpm work but account password is explicitly declared.

**Comment by whytewolf** [comment]
so, i know you found your answer but I just wanted to say. there is an easier way to install pygit2 instead of messing with the odds and ends of dependencies that libgit2 libssh and all that has. `python3 -m pip install --upgrade pip && python3 -m pip install pygit2` This will install the wheel version of pygit2 which includes the libraries already compiled. you have to upgrade pip3 first to get the wheel otherwise pip will try the egg that has the old issues with dependency hell that you ran into.

**Comment by tjyang** [comment]
@whytewolf 
- Thanks for the easier way via pip3 without libgit2 rpm remake . following is the confirmation on my RL8 test box.
```
sudo dnf remove  python3-pygit2
sudo python3 -m pip install --upgrade pip && sudo python3 -m pip install pygit2
#  pygit2-1.6.1 got installed vs older pygit2-0.26.4 rpm.
```
- Now, can  salt doc team add this info in a more clearer  way into [gitfs walkthrough doc]( https://docs.saltproject.io/en/latest/topics/tutorials/gitfs.html) ?

**Comment by tjyang** [comment]
The [reason why libgit2 missing libssh2 support in EL8](https://bugzilla.redhat.com/show_bug.cgi?id=1830319).
so the question is  the working pygit2-1.6.1  switched over to use libssh ?

**Comment by tjyang** [comment]
- Notes:
    - A: " recompile libgit2 rpm with "-DUSE_SSH=ON" in spec file
    - B:  "sudo python3 -m pip install --upgrade pip && sudo python3 -m pip install pygit2"
         - Feel like 2x slower when doing  "time sudo salt-run fileserver.file_list", compared with option A.

**Comment by OrangeDog** [comment]
> is the working pygit2-1.6.1 switched over to use libssh 

It's not a question of version number. Pip installs a pre-built binary that includes a libgit2 with SSH support.

> Feel like 2x slower

That's interesting. Is it actually 2x slower, or does it depend on caching and the like? Perhaps the .whl build has fewer optimisations enabled in order to be more compatible.

**Comment by tjyang** [comment]
@OrangeDog , Thanks for the reply. I will make  a comparison with real number.

**Comment by tjyang** [comment]
- A simple comparison of "time sudo salt-run fileserver.file_list" using same remote gitlab server.
``` 
0m34.385s :  Rocky Linux 8.4 with salt-master 3003.3 using option B, libgit2-0.26.8-2 removed.
1m8.114s    :  centos 7.9 with salt-master 3003.3 using option B.
```

**Comment by user-name-is-taken** [comment]
I had to add the following line because gitlab uses `main` instead of `master`

```yaml
gitfs_base: main
```

**Comment by tjyang** [comment]
Hi @barbaricyawps , hope you have time to work on git fs examples for gitlab users on RHEL8(and downstreams.  ex: rockylinux).

**Comment by dwoz** [comment]
Fix merged into the source tree, pending release. Closing per bulk triage; will ship in the next release cycle. Reopen if this reproduces on a currently supported release once the fix is out.
