### ISSUE TITLE
[BUG] TCP transport can leave msgpack.Unpacker in broken state

### ISSUE THREAD

**Issue by lukasraska** [saltstack/salt#60831]
**Description**
Recently I came across few Windows minions that ended up in state where no job could be executed on them, while beacons any any returning data worked. The log details were following (two different types):

```
[salt.transport.tcp:1294][ERROR   ][5056] Exception parsing response
Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt-3003-py3.7.egg\salt\transport\tcp.py", line 1248, in _stream_return
    for framed_msg in unpacker:
  File "msgpack\_unpacker.pyx", line 518, in msgpack._cmsgpack.Unpacker.__next__
  File "msgpack\_unpacker.pyx", line 443, in msgpack._cmsgpack.Unpacker._unpack
ValueError: 3960479480 exceeds max_array_len(104857600)
```
```
[tornado.application:356 ][ERROR   ][1600] Future <salt.ext.tornado.concurrent.Future object at 0x000000F943285FC8> exception was never retrieved: Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt-3003-py3.7.egg\salt\ext\tornado\gen.py", line 309, in wrapper
    yielded = next(result)
  File "c:\salt\bin\lib\site-packages\salt-3003-py3.7.egg\salt\transport\tcp.py", line 637, in wrap_callback
    body = salt.utils.msgpack.loads(body)
  File "c:\salt\bin\lib\site-packages\salt-3003-py3.7.egg\salt\utils\msgpack.py", line 157, in unpackb
    return msgpack.unpackb(packed, **_sanitize_msgpack_unpack_kwargs(kwargs))
  File "msgpack\_unpacker.pyx", line 202, in msgpack._cmsgpack.unpackb
msgpack.exceptions.ExtraData: unpack(b) received extra data.
```

The issue could only be solved by restarting minion, reconnection to master (e.g. by restarting master) would not help.

While investigating this, I believe this might be caused by following logic:
1. Instance of `msgpack.Unpacker` is being created (https://github.com/saltstack/salt/blob/v3003/salt/transport/tcp.py#L1240)
2. While minion should stay connected, read incoming data, feed them into the Unpacker (https://github.com/saltstack/salt/blob/v3003/salt/transport/tcp.py#L1247 ) and process the message
3. If any exception happens - minion get's disconnected (https://github.com/saltstack/salt/blob/v3003/salt/transport/tcp.py#L1283) or just any exception like those above (https://github.com/saltstack/salt/blob/v3003/salt/transport/tcp.py#L1305) would just force reconnection and yield

That way the unpacker object would be still left with data and not cleared up. Maybe the Unpacker object should be recreated every time reconnection is forced?

**Setup**

- [x] on-prem machine
- [x] VM (Virtualbox, KVM, etc. please specify)
- [x] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
Any minion with TCP transport in kind of broken state

**Expected behavior**
On any kind of unhandled exception, minion should recover. Also reconnection should force the minion to clear up any previous state

**Versions Report**
<details><summary>salt --versions-report</summary>

```
Salt Version:
          Salt: 3003
 
Dependency Versions:
          cffi: 1.14.5
      cherrypy: 18.6.0
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.5
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: 1.1.4
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
  python-gnupg: 0.4.6
        PyYAML: 5.3.1
         PyZMQ: 18.0.1
         smmap: 3.0.4
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.1
 
System Versions:
          dist:   
        locale: cp1252
       machine: AMD64
       release: 2016Server
        system: Windows
       version: 2016Server 10.0.14393 SP0
```
</details>

**Additional context**
If my suspicion is correct, I'm willing to prepare PR with appropriate test cases for solving this. It seems ZeroMQ transport should not be affected as it's reconstructing the message through msgpack at once.

**Comment by recmanj** [comment]
Bumping this issue with more logs

```
2022-05-10 09:59:26,168 [salt.transport.tcp:1294][ERROR   ][2620] Exception parsing response
Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt-3003-py3.7.egg\salt\transport\tcp.py", line 1247, in _stream_return
    unpacker.feed(wire_bytes)
  File "msgpack\_unpacker.pyx", line 373, in msgpack._cmsgpack.Unpacker.feed
  File "msgpack\_unpacker.pyx", line 396, in msgpack._cmsgpack.Unpacker.append_buffer
msgpack.exceptions.BufferFull
```
```
2022-05-10 14:52:32,992 [salt.transport.tcp:1335][ERROR   ][10702] Exception parsing response
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/transport/tcp.py", line 1289, in _stream_return
    for framed_msg in unpacker:
  File "msgpack/_unpacker.pyx", line 562, in msgpack._cmsgpack.Unpacker.__next__
  File "msgpack/_unpacker.pyx", line 493, in msgpack._cmsgpack.Unpacker._unpack
ValueError: 254502514 exceeds max_map_len(52428800)
```
```
[ERROR   ] Exception parsing response
Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/salt/transport/tcp.py", line 1289, in _stream_return
for framed_msg in unpacker:
File "msgpack/_unpacker.pyx", line 562, in msgpack._cmsgpack.Unpacker.__next__
File "msgpack/_unpacker.pyx", line 509, in msgpack._cmsgpack.Unpacker._unpack
msgpack.exceptions.FormatError
```

@dwoz as TCP transport has been refactored recently, it might be worth it to look into this issue (this part is unchanged).

Resetting the unpacker seems to be working but I am not entirely sure what's the best way to approach this.

**Comment by twangboy** [comment]
Assigning to @dwoz
