### ISSUE TITLE
[DOCS] absent info about install python package python3-redis for redis_cache

### ISSUE THREAD

**Issue by unix196** [saltstack/salt#60899]
**Description**
In documentation about _salt.cache.redis_cache_  absent info about installing important package:
`pip python3-redis`
Otherwise in salt master log:
```
2021-09-20 03:42:04,327 [salt.master      :1879][ERROR   ][39] Error in function _mine:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1872, in run_func
    ret = getattr(self, func)(load)
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1441, in _mine
    return self.masterapi._mine(load, skip_verify=True)
  File "/usr/lib/python3/dist-packages/salt/daemons/masterapi.py", line 608, in _mine
    data = self.cache.fetch(cbank, ckey)
  File "/usr/lib/python3/dist-packages/salt/cache/__init__.py", line 180, in fetch
    return self.modules[fun](bank, key, **self._kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1208, in __getitem__
    func = super(LazyLoader, self).__getitem__(item)
  File "/usr/lib/python3/dist-packages/salt/utils/lazy.py", line 108, in __getitem__
    raise KeyError(key)
KeyError: 'redis.fetch'
```
https://github.com/saltstack/salt/issues/57069 - issue with the same problem.

**Suggested Fix**
For example in doc about [etcd_cache](https://docs.saltproject.io/en/latest/ref/cache/all/salt.cache.etcd_cache.html#module-salt.cache.etcd_cache):
>To enable this cache plugin, the master will need the python client for Etcd installed. This can be easily installed with pip:
pip install python-etcd

**Type of documentation**
[https://docs.saltproject.io/en/latest/ref/cache/all/index.html#all-salt-cache](url)

**Location or format of documentation**
https://docs.saltproject.io/en/latest/ref/cache/all/salt.cache.redis_cache.html#module-salt.cache.redis_cache

**Comment by waynew** [comment]
Yeah - looks like the documentation should mention that the redis package is needed.

**Comment by unix196** [comment]
https://github.com/saltstack/salt/blob/master/doc/ref/cache/all/salt.cache.redis_cache.rst - I found this file, but I don't undestand how edit it.

**Comment by barbaricyawps** [comment]
Hi, @unix196 . If you're still interested in working on this issue, we would love your help.

To make an edit to the Salt module docs, you first need to set up your environment to contribute in the same way you would set up your environment to contribute to Salt in general. For that reason, it's best to follow the instructions in the Salt Contributing guide: https://github.com/saltstack/salt/blob/master/CONTRIBUTING.rst

Once your environment is good, navigate to the file **salt > cache > rediscache.py** and edit the docstrings for that module. Hope that helps!

**Comment by Sxderp** [comment]
This can be closed with https://github.com/saltstack/salt/pull/68819.

**Comment by dwoz** [comment]
Already documented via ecb5eefe867 (your own PR, Sep 2021). The pip install line is in the module docstring on 3006.x, 3007.x, 3008.x, and master. Closing.
