### ISSUE TITLE
[BUG] Encoding issue in powershell output

### ISSUE THREAD

**Issue by achimmihca** [saltstack/salt#60937]
**Description**
I am using cmd.run to execute powershell scripts.

When there are non-ascii characters then the call throws an exception in SaltStack instead of showing the error message.

The reason seems to be a mismatch of powershell encoding on Windows and the encoding of SaltStack running on Ubuntu.
The current encoding of the powershell console can be viewed via `[Console]::Out` and set via `[Console]::OutputEncoding = [System.Text.Encoding]::UTF8`.

Example: encoding-test.sls
```
encoding test:
  cmd.run:
    - name: |
        [Console]::Out
        [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
        [Console]::Out
        echo "äüß"
    - shell: powershell
```

Before settings the OutputEncoding, I get 
```
                  Encoding                         FormatProvider NewLine
                  --------                         -------------- -------
                  System.Text.SBCSCodePageEncoding de-DE          ...
```

Afterwards, I get 
```
                   Encoding                 FormatProvider NewLine
                  --------                 -------------- -------
                  System.Text.UTF8Encoding de-DE          ...
```

*On the salt-master running in Ubuntu 20.04*
Without setting the encoding, SaltStack cannot parse the output and throws an error: `'charmap' codec can't decode byte 0x81 in position 1: character maps to <undefined>`

When settings the encoding, the letters are still messed up, but at least SaltStack shows the output instead of throwing an exception: ` Ã¤Ã¼ÃŸ`

*On the salt-minion running in Windows (salt-call)*
Without setting the encoding, I get
```
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
error: (1314, 'GetNamedSecurityInfo', 'Dem Client fehlt ein erforderliches Recht.')
Traceback (most recent call last):
  File "c:\salt\bin\Scripts\salt-call", line 4, in <module>
    __import__('pkg_resources').run_script('salt==3003.3', 'salt-call')

... (I skip middle part of the stack trace for brevity)

File "c:\salt\bin\lib\site-packages\salt-3003.3-py3.7.egg\salt\utils\atomicfile.py", line 130, in close
    source=self._filename, target=self._tmp_filename
  File "c:\salt\bin\lib\site-packages\salt-3003.3-py3.7.egg\salt\utils\win_dacl.py", line 2180, in copy_security
    sec = win32security.GetNamedSecurityInfo(source, obj_type_flag, security_flags)
pywintypes.error: (1314, 'GetNamedSecurityInfo', 'Dem Client fehlt ein erforderliches Recht.')
```

When setting the encoding to UTF8, the characters are messed up the same way like when running it from the salt-master in Ubuntu:
`Ã¤Ã¼ÃŸ`

(What I really don't understand is the exception with `pywintypes.error: (1314, 'GetNamedSecurityInfo'` because of an encoding issue. This was difficult to find cause.)

**Setup**
So far, I am only evaluating SaltStack.
I have installed the salt-master on Ubuntu 20.04 (WSL running in Windows) and the salt-minion on the same Windows PC.

**Steps to Reproduce the behavior**
- Install and connect recent salt-master and salt-minion
- create sls file as in the example above
- run `salt '*' state.apply encoding-test`

**Expected behavior**
- The output of `salt-call` on the minion and `salt` on the master should produce the same output.
    - ATM, without setting an encoding, they fail with different exceptions
- The output should be parsed instead of throwing an exception.
    - Messed up characters are better than no proper message at all.
    - Maybe it would be better to set an encoding for powershell implicitly or add a parameter to cmd.run to do so?
    - Curse you Windows for not using UTF-8 as default!
- This issue should be documented. But I am unsure where, some ideas:
    - Unicode: https://docs.saltproject.io/en/latest/ref/internals/unicode.html
    - Windows: https://docs.saltproject.io/en/latest/topics/installation/windows.html
    - cmd.run: https://docs.saltproject.io/en/latest/ref/states/all/salt.states.cmd.html

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3003.3

Dependency Versions:
          cffi: Not Installed
      cherrypy: unknown
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.8.10 (default, Jun  2 2021, 10:49:15)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 4.4.0-19041-Microsoft
        system: Linux
       version: Ubuntu 20.04 focal
```

```
salt-minion 3003.3

Microsoft Windows 10 Pro
Version	10.0.19043 Build 19043
```
</details>

**Comment by marbx** [comment]
@achimmihca , could you please paste the full stacktrace?

Characters above 7-bit ASCII are an old issue for Salt on Windows, see e.g. https://github.com/saltstack/salt/pull/58478

**Comment by achimmihca** [comment]
I think I got it all wrong!

The exception on the minion occurs when it tries to fetch the changed sls file from the master. I always get an exception when using salt-call after I change the sls file, no matter the code in the sls file.
But it works when I run salt on the master and afterwards salt-call on the minion.

Thus, it might not be an encoding issue after all.

Anyway, the stack-trace I get when changing the sls file and afterwards running salt-call on the minion is:

<details>
<summary>stack-trace</summary>

> salt-call state.apply encoding-test
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
error: (1314, 'GetNamedSecurityInfo', 'Dem Client fehlt ein erforderliches Recht.')
Traceback (most recent call last):
  File "c:\salt\bin\Scripts\salt-call", line 4, in <module>
    __import__('pkg_resources').run_script('salt==3003.3', 'salt-call')
  File "c:\salt\bin\lib\site-packages\pkg_resources\__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "c:\salt\bin\lib\site-packages\pkg_resources\__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "c:\salt\bin\lib\site-packages\salt-3003.3-py3.7.egg\EGG-INFO\scripts\salt-call", line 10, in <module>
    salt_call()
  File "c:\salt\bin\lib\site-packages\salt-3003.3-py3.7.egg\salt\scripts.py", line 449, in salt_call
    client.run()
  File "c:\salt\bin\lib\site-packages\salt-3003.3-py3.7.egg\salt\cli\call.py", line 58, in run
    caller.run()
  File "c:\salt\bin\lib\site-packages\salt-3003.3-py3.7.egg\salt\cli\caller.py", line 112, in run
    ret = self.call()
  File "c:\salt\bin\lib\site-packages\salt-3003.3-py3.7.egg\salt\cli\caller.py", line 220, in call
    self.opts, data, func, args, kwargs
  File "c:\salt\bin\lib\site-packages\salt-3003.3-py3.7.egg\salt\loader.py", line 1241, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt-3003.3-py3.7.egg\salt\loader.py", line 2274, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt-3003.3-py3.7.egg\salt\loader.py", line 2289, in _run_as
    return _func_or_method(*args, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt-3003.3-py3.7.egg\salt\executors\direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt-3003.3-py3.7.egg\salt\loader.py", line 1241, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt-3003.3-py3.7.egg\salt\loader.py", line 2274, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt-3003.3-py3.7.egg\salt\loader.py", line 2289, in _run_as
    return _func_or_method(*args, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt-3003.3-py3.7.egg\salt\modules\state.py", line 792, in apply_
    return sls(mods, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt-3003.3-py3.7.egg\salt\modules\state.py", line 1378, in sls
    high_, errors = st_.render_highstate({opts["saltenv"]: mods})
  File "c:\salt\bin\lib\site-packages\salt-3003.3-py3.7.egg\salt\state.py", line 4356, in render_highstate
    sls, saltenv, mods, matches, context=context
  File "c:\salt\bin\lib\site-packages\salt-3003.3-py3.7.egg\salt\state.py", line 3997, in render_state
    state_data = self.client.get_state(sls, saltenv)
  File "c:\salt\bin\lib\site-packages\salt-3003.3-py3.7.egg\salt\fileclient.py", line 394, in get_state
    dest = self.cache_file(path, saltenv, cachedir=cachedir)
  File "c:\salt\bin\lib\site-packages\salt-3003.3-py3.7.egg\salt\fileclient.py", line 188, in cache_file
    verify_ssl=verify_ssl,
  File "c:\salt\bin\lib\site-packages\salt-3003.3-py3.7.egg\salt\fileclient.py", line 510, in get_url
    result = self.get_file(url, dest, makedirs, saltenv, cachedir=cachedir)
  File "c:\salt\bin\lib\site-packages\salt-3003.3-py3.7.egg\salt\fileclient.py", line 1299, in get_file
    fn_.close()
  File "c:\salt\bin\lib\site-packages\salt-3003.3-py3.7.egg\salt\utils\atomicfile.py", line 130, in close
    source=self._filename, target=self._tmp_filename
  File "c:\salt\bin\lib\site-packages\salt-3003.3-py3.7.egg\salt\utils\win_dacl.py", line 2180, in copy_security
    sec = win32security.GetNamedSecurityInfo(source, obj_type_flag, security_flags)
pywintypes.error: (1314, 'GetNamedSecurityInfo', 'Dem Client fehlt ein erforderliches Recht.')
Traceback (most recent call last):
  File "c:\salt\bin\Scripts\salt-call", line 4, in <module>
    __import__('pkg_resources').run_script('salt==3003.3', 'salt-call')
  File "c:\salt\bin\lib\site-packages\pkg_resources\__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "c:\salt\bin\lib\site-packages\pkg_resources\__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "c:\salt\bin\lib\site-packages\salt-3003.3-py3.7.egg\EGG-INFO\scripts\salt-call", line 10, in <module>
    salt_call()
  File "c:\salt\bin\lib\site-packages\salt-3003.3-py3.7.egg\salt\scripts.py", line 449, in salt_call
    client.run()
  File "c:\salt\bin\lib\site-packages\salt-3003.3-py3.7.egg\salt\cli\call.py", line 58, in run
    caller.run()
  File "c:\salt\bin\lib\site-packages\salt-3003.3-py3.7.egg\salt\cli\caller.py", line 112, in run
    ret = self.call()
  File "c:\salt\bin\lib\site-packages\salt-3003.3-py3.7.egg\salt\cli\caller.py", line 220, in call
    self.opts, data, func, args, kwargs
  File "c:\salt\bin\lib\site-packages\salt-3003.3-py3.7.egg\salt\loader.py", line 1241, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt-3003.3-py3.7.egg\salt\loader.py", line 2274, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt-3003.3-py3.7.egg\salt\loader.py", line 2289, in _run_as
    return _func_or_method(*args, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt-3003.3-py3.7.egg\salt\executors\direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt-3003.3-py3.7.egg\salt\loader.py", line 1241, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt-3003.3-py3.7.egg\salt\loader.py", line 2274, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt-3003.3-py3.7.egg\salt\loader.py", line 2289, in _run_as
    return _func_or_method(*args, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt-3003.3-py3.7.egg\salt\modules\state.py", line 792, in apply_
    return sls(mods, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt-3003.3-py3.7.egg\salt\modules\state.py", line 1378, in sls
    high_, errors = st_.render_highstate({opts["saltenv"]: mods})
  File "c:\salt\bin\lib\site-packages\salt-3003.3-py3.7.egg\salt\state.py", line 4356, in render_highstate
    sls, saltenv, mods, matches, context=context
  File "c:\salt\bin\lib\site-packages\salt-3003.3-py3.7.egg\salt\state.py", line 3997, in render_state
    state_data = self.client.get_state(sls, saltenv)
  File "c:\salt\bin\lib\site-packages\salt-3003.3-py3.7.egg\salt\fileclient.py", line 394, in get_state
    dest = self.cache_file(path, saltenv, cachedir=cachedir)
  File "c:\salt\bin\lib\site-packages\salt-3003.3-py3.7.egg\salt\fileclient.py", line 188, in cache_file
    verify_ssl=verify_ssl,
  File "c:\salt\bin\lib\site-packages\salt-3003.3-py3.7.egg\salt\fileclient.py", line 510, in get_url
    result = self.get_file(url, dest, makedirs, saltenv, cachedir=cachedir)
  File "c:\salt\bin\lib\site-packages\salt-3003.3-py3.7.egg\salt\fileclient.py", line 1299, in get_file
    fn_.close()
  File "c:\salt\bin\lib\site-packages\salt-3003.3-py3.7.egg\salt\utils\atomicfile.py", line 130, in close
    source=self._filename, target=self._tmp_filename
  File "c:\salt\bin\lib\site-packages\salt-3003.3-py3.7.egg\salt\utils\win_dacl.py", line 2180, in copy_security
    sec = win32security.GetNamedSecurityInfo(source, obj_type_flag, security_flags)
pywintypes.error: (1314, 'GetNamedSecurityInfo', 'Dem Client fehlt ein erforderliches Recht.')

</details>

**Comment by OrangeDog** [comment]
What is the output of `--versions-report` on the minion, specifically the locale?

**Comment by achimmihca** [comment]
The locale is `cp1252`.

Full command output:
```
> salt-call --versions-report
Salt Version:
          Salt: 3004

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.7
     gitpython: 3.1.18
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: 1.1.4
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.10.1
        pygit2: Not Installed
        Python: 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)]
  python-gnupg: 0.4.7
        PyYAML: 5.4.1
         PyZMQ: 19.0.0
         smmap: 4.0.0
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist:
        locale: cp1252
       machine: AMD64
       release: 10
        system: Windows
       version: 10 10.0.19041 SP0 Multiprocessor Free
```
