### ISSUE TITLE
[BUG] pip.installed doesn't work with upgrade=True due to inability of getting available version numbers

### ISSUE THREAD

**Issue by pckroon** [saltstack/salt#61004]
**Description**
Using pip.installed with upgrade: True results in the following traceback, which is due to how the `salt.modules.pip.list_all_versions` tries to get the available versions from pypi.
```
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/state.py", line 2171, in call
    ret = self.states[cdata["full"]](
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2105, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/states/pip_state.py", line 852, in installed
    out = _check_if_installed(
  File "/usr/lib/python3/dist-packages/salt/states/pip_state.py", line 329, in _check_if_installed
    desired_version = available_versions[-1]
TypeError: 'NoneType' object is not subscriptable
```

**Setup**

`my_state.sls`:
```
python3-pip:
  pkg.installed


pip-packages:
  pip.installed:
    - upgrade: True
    - names:
      - matplotlib
    - require:
        - pkg: python3-pip
```

`salt-call state.apply my_state` on the minion
<details>

```
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/state.py", line 2171, in call
    ret = self.states[cdata["full"]](
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2105, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/states/pip_state.py", line 852, in installed
    out = _check_if_installed(
  File "/usr/lib/python3/dist-packages/salt/states/pip_state.py", line 329, in _check_if_installed
    desired_version = available_versions[-1]
TypeError: 'NoneType' object is not subscriptable

local:
----------
          ID: python3-pip
    Function: pkg.installed
      Result: True
     Comment: All specified packages are already installed
     Started: 15:19:29.965834
    Duration: 60.832 ms
     Changes:   
----------
          ID: pip-packages
    Function: pip.installed
        Name: matplotlib
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 2171, in call
                  ret = self.states[cdata["full"]](
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2105, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/pip_state.py", line 852, in installed
                  out = _check_if_installed(
                File "/usr/lib/python3/dist-packages/salt/states/pip_state.py", line 329, in _check_if_installed
                  desired_version = available_versions[-1]
              TypeError: 'NoneType' object is not subscriptable
     Started: 15:19:30.175097
    Duration: 3189.604 ms
     Changes:   

Summary for local
------------
Succeeded: 1
Failed:    1
------------
Total states run:     2
Total run time:   3.250 s

```
</details>

**Versions Report**
`salt --versions-report`

On master:
<details>

```
Salt Version:
          Salt: 3003.3
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.5
     gitpython: 3.1.14
        Jinja2: 2.11.3
       libgit2: 1.1.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.0
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.9.7
        pygit2: 1.4.0
        Python: 3.9.2 (default, Feb 28 2021, 17:03:44)
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 20.0.0
         smmap: 4.0.0
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 11 bullseye
        locale: utf-8
       machine: x86_64
       release: 5.10.0-8-amd64
        system: Linux
       version: Debian GNU/Linux 11 bullseye
```
</details>

On minion:
<details>

```
Salt Version:
          Salt: 3002.6
 
Dependency Versions:
          cffi: 1.14.5
      cherrypy: 8.9.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.0
  msgpack-pure: Not Installed
  mysql-python: 1.4.4
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.9.7
        pygit2: Not Installed
        Python: 3.9.2 (default, Feb 28 2021, 17:03:44)
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 20.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 11 bullseye
        locale: utf-8
       machine: x86_64
       release: 5.10.0-8-amd64
        system: Linux
       version: Debian GNU/Linux 11 bullseye
```
</details>

Pip version on minion:
<details>

```
pip 20.3.4 from /usr/lib/python3/dist-packages/pip (python 3.9)
```
</details>

**Additional context**
My diagnosis is the following: `salt.states.pip_state.installed` tries to get the last available version via `salt.modules.pip.list_all_versions`, which tries to get all available version from pypi by calling `pip install matplotlib==versions`. This returns: 
```
ERROR: Could not find a version that satisfies the requirement matplotlib==versions
ERROR: No matching distribution found for matplotlib==versions
```

However, `salt.modules.pip.list_all_versions` tries to regex match this to `r"\s*Could not find a version.* \(from versions: (.*)\)"`; which doesn't work so well. The root cause is (of course) that `pip` doesn't (didn't?) have an api to request versions for (a) package(s). See also: https://stackoverflow.com/questions/4888027/python-and-pip-list-all-versions-of-a-package-thats-available?rq=1 

I attempted a workaround, where I made the following module:
`salt://_modules/pip.py`:
<details>

```python3
import json
from urllib.request import urlopen, Request
import pkg_resources

from salt.modules.pip import *


def _query_url(pkg_name, base_url=None):
    if base_url and not '://' in base_url:
        base_url = 'https://{}'.format(base_url)
    url = "{}/pypi/{}/json".format(base_url, pkg_name)
    data = json.load(urlopen(Request(url)))
    versions = data["releases"].keys()
    return versions

def list_all_versions(
    pkg,
    bin_env=None,
    include_alpha=False,
    include_beta=False,
    include_rc=False,
    user=None,
    cwd=None,
    index_url=None,
    extra_index_url=None,
):

    if index_url and not salt.utils.url.validate(index_url, VALID_PROTOS):
        raise CommandExecutionError("'{}' is not a valid URL".format(index_url))

    filtered = []
    if not include_alpha:
        filtered.append("a")
    if not include_beta:
        filtered.append("b")
    if not include_rc:
        filtered.append("rc")
    if filtered:
        excludes = re.compile(r"^((?!{}).)*$".format("|".join(filtered)))
    else:
        excludes = re.compile(r"")

    versions = _query_url(pkg, index_url)

    versions = sorted((v for v in versions if excludes.match(v)), key=pkg_resources.parse_version)

    if not versions:
        return None

    return versions
```
</details>

Where my idea is that since `salt.states.pip_state.installed` "does the right thing" by calling `__salt__["pip.list_all_versions"]` my new module would neatly take precedence. Doesn't work, unfortunately:
<details>

```
[ERROR   ] State 'pip.installed' was not found in SLS 'packages.pip_packages'
Reason: 'pip.installed' is not available.

local:
----------
          ID: python3-pip
    Function: pkg.installed
      Result: True
     Comment: All specified packages are already installed
     Started: 15:36:02.353821
    Duration: 61.283 ms
     Changes:   
----------
          ID: pip-packages
    Function: pip.installed
        Name: matplotlib
      Result: False
     Comment: State 'pip.installed' was not found in SLS 'packages.pip_packages'
              Reason: 'pip.installed' is not available.
     Changes:   

Summary for local
------------
Succeeded: 1
Failed:    1
------------
Total states run:     2
Total run time:  61.283 ms
```
</details>

Any advice is welcome :)

**Comment by dmurphy18** [comment]
@pckroon Can you check this with the latest Salt minion v3003.3 to see if the problem occurs with it.  Also can you ensure that you are using the salt-minion supplied by the SaltProject and not using the salt-minion that is supplied by Debian's fork of Salt which is also v3002.6, that is 3002.6+dfsg1-4.  The following commands should show which version is installed and being used:
```
apt-get update
apt-cache policy salt-minion
```

From my Bullseye system:
```
root@deb11:/home/david# apt-get update
Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Hit:2 http://deb.debian.org/debian bullseye InRelease
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
Hit:4 http://deb.debian.org/debian bullseye-backports InRelease
Reading package lists... Done
root@deb11:/home/david# apt-cache policy salt-minion
salt-minion:
  Installed: 3002.6+dfsg1-4
  Candidate: 3002.6+dfsg1-4
  Version table:
 *** 3002.6+dfsg1-4 500
        500 http://deb.debian.org/debian bullseye/main amd64 Packages
        100 /var/lib/dpkg/status
root@deb11:/home/david# 
```

**Comment by pckroon** [comment]
Of course. I've updated my minion to the one from the SaltProject repo (I indeed had the one from debian. By the way, is there a bullseye version available yet?)
`apt-cache policy salt-minion`:
<details>

```
salt-minion:
  Installed: 3003.3+ds-1
  Candidate: 3003.3+ds-1
  Version table:
 *** 3003.3+ds-1 500
        500 https://repo.saltproject.io/py3/debian/10/amd64/latest buster/main amd64 Packages
        100 /var/lib/dpkg/status
     3002.6+dfsg1-4 500
        500 http://apt:3142/debian bullseye/main amd64 Packages
        500 http://apt:3142/debian bullseye/main i386 Packages
```
</details>

`salt-call --versions-report`
<details>

```
Salt Version:
          Salt: 3003.3
 
Dependency Versions:
          cffi: 1.14.5
      cherrypy: 8.9.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.0
  msgpack-pure: Not Installed
  mysql-python: 1.4.4
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.9.7
        pygit2: Not Installed
        Python: 3.9.2 (default, Feb 28 2021, 17:03:44)
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 20.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 11 bullseye
        locale: utf-8
       machine: x86_64
       release: 5.10.0-8-amd64
        system: Linux
       version: Debian GNU/Linux 11 bullseye
```
</details>

The problem persists as in the original post.

Note however, that if I update my pip (`pip install -U pip`) to `21.2.4` everything works again, since `pip install <pkg>==versions` returns a list of available versions again.

**Comment by dmurphy18** [comment]
@pckroon Thanks for using the SaltProject version, makes it easier to debug when coming from our code base. As to a Bullseye version available, there shall be with 3004rc1, in QA.

**Comment by pckroon** [comment]
Hi David,

I think there's a small miscommunication/confusion. What I was trying to say with my previous post:
On first run, when matplotlib is *not* installed, applying the pip state works without issues.
On second run, when matplotlib *is* installed, applying the pip state results in the original traceback.

It seems you always run when matplotlib is *not* installed, and indeed you see no issues.

**Comment by dmurphy18** [comment]
problem is ignoring returned 'None' from pip.list_all_versions which is using the following trick to obtain all versions of matplotlib
```
python3 -m pip install matplotlib==versions
```
which in all other versions of pip returns
```
[root@Unknown david]# pip3 install matplotlib==versions
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting matplotlib==versions
  Could not find a version that satisfies the requirement matplotlib==versions (from versions: 0.86, 0.86.1, 0.86.2, 0.91.0, 0.91.1, 1.0.1, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1rc1, 1.4.1, 1.4.2, 1.4.3, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 2.0.0b1, 2.0.0b2, 2.0.0b3, 2.0.0b4, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.0.1, 2.0.2, 2.1.0rc1, 2.1.0, 2.1.1, 2.1.2, 2.2.0rc1, 2.2.0, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 3.0.0rc2, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.1.0rc1, 3.1.0rc2, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.2.0rc1, 3.2.0rc3, 3.2.0, 3.2.1, 3.2.2, 3.3.0rc1, 3.3.0, 3.3.1, 3.3.2, 3.3.3, 3.3.4)
No matching distribution found for matplotlib==versions
[root@Unknown david]#
[root@Unknown david]# pip3 install matplotlib==versions
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting matplotlib==versions
  Could not find a version that satisfies the requirement matplotlib==versions (from versions: 0.86, 0.86.1, 0.86.2, 0.91.0, 0.91.1, 1.0.1, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1rc1, 1.4.1, 1.4.2, 1.4.3, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 2.0.0b1, 2.0.0b2, 2.0.0b3, 2.0.0b4, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.0.1, 2.0.2, 2.1.0rc1, 2.1.0, 2.1.1, 2.1.2, 2.2.0rc1, 2.2.0, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 3.0.0rc2, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.1.0rc1, 3.1.0rc2, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.2.0rc1, 3.2.0rc3, 3.2.0, 3.2.1, 3.2.2, 3.3.0rc1, 3.3.0, 3.3.1, 3.3.2, 3.3.3, 3.3.4)
No matching distribution found for matplotlib==versions
[root@Unknown david]#```

and on Debian 10
```
root@tdeb10:/srv/salt# pip3 install matplotlib==versions
Collecting matplotlib==versions
  Could not find a version that satisfies the requirement matplotlib==versions (from versions: 0.86, 0.86.1, 0.86.2, 0.91.0, 0.91.1, 1.0.1, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1rc1, 1.4.1, 1.4.2, 1.4.3, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 2.0.0b1, 2.0.0b2, 2.0.0b3, 2.0.0b4, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.0.1, 2.0.2, 2.1.0rc1, 2.1.0, 2.1.1, 2.1.2, 2.2.0rc1, 2.2.0, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 3.0.0rc2, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.1.0rc1, 3.1.0rc2, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.2.0rc1, 3.2.0rc3, 3.2.0, 3.2.1, 3.2.2, 3.3.0rc1, 3.3.0, 3.3.1, 3.3.2, 3.3.3, 3.3.4, 3.4.0rc1, 3.4.0rc2, 3.4.0rc3, 3.4.0, 3.4.1, 3.4.2, 3.4.3, 3.5.0b1, 3.5.0rc1)
No matching distribution found for matplotlib==versions
root@tdeb10:/srv/salt# 
root@tdeb10:/srv/salt# pip3 --version
pip 18.1 from /usr/lib/python3/dist-packages/pip (python 3.7)
root@tdeb10:/srv/salt# 
```

but with pip 20.3.4 in Bullseye
```root@tdeb11:/usr/bin# pip3 install matplotlib==versions
ERROR: Could not find a version that satisfies the requirement matplotlib==versions
ERROR: No matching distribution found for matplotlib==versions
root@tdeb11:/usr/bin# pip3 --version
pip 20.3.4 from /usr/lib/python3/dist-packages/pip (python 3.9)
root@tdeb11:/usr/bin# 
```

but with upgrade to 21.1
```
root@tdeb11:/usr/bin# pip3 --version
pip 21.1 from /usr/local/lib/python3.9/dist-packages/pip (python 3.9)
root@tdeb11:/usr/bin# pip3 install matplotlib==versions
WARNING: Value for scheme.platlib does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /usr/local/lib/python3.9/dist-packages
sysconfig: /usr/lib/python3.9/site-packages
WARNING: Value for scheme.purelib does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /usr/local/lib/python3.9/dist-packages
sysconfig: /usr/lib/python3.9/site-packages
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /usr/local/include/python3.9/UNKNOWN
sysconfig: /usr/include/python3.9
WARNING: Value for scheme.scripts does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /usr/local/bin
sysconfig: /usr/bin
WARNING: Value for scheme.data does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /usr/local
sysconfig: /usr
WARNING: Additional context:
user = False
home = None
root = None
prefix = None
ERROR: Could not find a version that satisfies the requirement matplotlib==versions (from versions: 0.86, 0.86.1, 0.86.2, 0.91.0, 0.91.1, 1.0.1, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1rc1, 1.4.1, 1.4.2, 1.4.3, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 2.0.0b1, 2.0.0b2, 2.0.0b3, 2.0.0b4, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.0.1, 2.0.2, 2.1.0rc1, 2.1.0, 2.1.1, 2.1.2, 2.2.0rc1, 2.2.0, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 3.0.0rc2, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.1.0rc1, 3.1.0rc2, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.2.0rc1, 3.2.0rc3, 3.2.0, 3.2.1, 3.2.2, 3.3.0rc1, 3.3.0, 3.3.1, 3.3.2, 3.3.3, 3.3.4, 3.4.0rc1, 3.4.0rc2, 3.4.0rc3, 3.4.0, 3.4.1, 3.4.2, 3.4.3, 3.5.0b1, 3.5.0rc1)
ERROR: No matching distribution found for matplotlib==versions
root@tdeb11:/usr/bin#
```

So normal error output from pip restored

**Comment by dmurphy18** [comment]
@pckroon Sorry for taking so long to get back on this, had other fires to put out.
Given this is an issue with the underlying pip and some certain versions of pip (v20.x) and there is a work-around.
Please let me know if you have any objections to closing this issue.

**Comment by pckroon** [comment]
Sorry for the slow reply, holidays.

I have no issues with closing this issue. It's up to you what the criteria are for marking something as wont-fix.

**Comment by dmurphy18** [comment]
Closing this since an under-lying issue with only some versions of pip which pip has now corrected.
