### ISSUE TITLE
[BUG]salt master log: [salt.master  :1945][ERROR   ][387441] Error in function _file_list:

### ISSUE THREAD

**Issue by lianyutianshi77** [saltstack/salt#61022]
**Description**
Master version
Salt Version:
          Salt: 3003.2
 
Dependency Versions:
          cffi: 1.11.5
      cherrypy: 18.4.0
      dateutil: 2.8.2
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 1.0.0
  msgpack-pure: Not Installed
  mysql-python: 1.2.5
     pycparser: 2.14
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Dec 14 2020, 17:55:20)
  python-gnupg: Not Installed
        PyYAML: 3.12
         PyZMQ: 19.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: tencentos 3.2 Final
        locale: UTF-8
       machine: x86_64
        system: Linux
       version:  CentOS Linux release 8.2.2.2004

Master config:
file_roots:
  base:
    - /data/srv/salt
  prod:
    - /data/srv/salt/prod

Master log details:
[salt.master      :1945][ERROR   ][387441] Error in function _file_list:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/payload.py", line 196, in dumps
    msg, default=ext_type_encoder, use_bin_type=use_bin_type
  File "/usr/lib/python3.6/site-packages/salt/utils/msgpack.py", line 133, in packb
    return msgpack.packb(o, **_sanitize_msgpack_kwargs(kwargs))
  File "/usr/local/lib64/python3.6/site-packages/msgpack/__init__.py", line 35, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 286, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 292, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 289, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 225, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 258, in msgpack._cmsgpack.Packer._pack
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 44-52: surrogates not allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/master.py", line 1939, in run_func
    ret = getattr(self, func)(load)
  File "/usr/lib/python3.6/site-packages/salt/utils/decorators/__init__.py", line 791, in wrapped
    return function(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/fileserver/__init__.py", line 775, in file_list
    ret.update(self.servers[fstr](load))
  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 1241, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 2274, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
    return callable(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 2289, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/fileserver/roots.py", line 434, in file_list
    return _file_lists(load, "files")
  File "/usr/lib/python3.6/site-packages/salt/fileserver/roots.py", line 420, in _file_lists
    salt.fileserver.write_file_list_cache(__opts__, ret, list_cache, w_lock)
  File "/usr/lib/python3.6/site-packages/salt/fileserver/__init__.py", line 180, in write_file_list_cache
    fp_.write(serial.dumps(data))
  File "/usr/lib/python3.6/site-packages/salt/payload.py", line 233, in dumps
    msg, default=ext_type_encoder, use_bin_type=use_bin_type
  File "/usr/lib/python3.6/site-packages/salt/utils/msgpack.py", line 133, in packb
    return msgpack.packb(o, **_sanitize_msgpack_kwargs(kwargs))
  File "/usr/local/lib64/python3.6/site-packages/msgpack/__init__.py", line 35, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 286, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 292, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 289, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 225, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 258, in msgpack._cmsgpack.Packer._pack
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 44-52: surrogates not allowed

**Comment by OrangeDog** [comment]
msgpack 1.0.0 may be the culprit if that's a breaking change. Try downgrading it.

**Comment by garethgreenaway** [comment]
This is believed to be fixed in PR https://github.com/saltstack/salt/pull/61926 which will be available in the Phosphorus release.
