### ISSUE TITLE
[BUG] states virt.running throwing error when defining console

### ISSUE THREAD

**Issue by q1x** [saltstack/salt#61054]
**Description**
when adding the following to a virt.running state:

```
    - consoles:
      - type: pty
```

The minion throws the following exception:

```
    Function: virt.running
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 2172, in call
                  *cdata["args"], **cdata["kwargs"]
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 1241, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2274, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2289, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2322, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/virt.py", line 1024, in running
                  host_devices=host_devices,
                File "/usr/lib/python3/dist-packages/salt/states/virt.py", line 669, in defined
                  host_devices=host_devices,
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 1241, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2274, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2289, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/modules/virt.py", line 4232, in update
                  domain, new_desc, mem, cpu, old_mem, old_cpu, to_skip, test
                File "/usr/lib/python3/dist-packages/salt/modules/virt.py", line 3424, in _update_live
                  changes = _compute_device_changes(old_desc, new_desc, to_skip)
                File "/usr/lib/python3/dist-packages/salt/modules/virt.py", line 3338, in _compute_device_changes
                  changes[dev_type] = globals()["_diff_{}_lists".format(dev_type)](old, new)
                File "/usr/lib/python3/dist-packages/salt/modules/virt.py", line 3306, in _diff_console_lists
                  return _diff_lists(old, new, _serial_or_concole_equal)
                File "/usr/lib/python3/dist-packages/salt/modules/virt.py", line 3132, in _diff_lists
                  for item in old_devices
                File "/usr/lib/python3/dist-packages/salt/modules/virt.py", line 3133, in <listcomp>
                  if comparator(_remove_indent(item), _remove_indent(new_item))
                File "/usr/lib/python3/dist-packages/salt/modules/virt.py", line 3286, in _serial_or_concole_equal
                  return _filter_serial_or_concole(old) == _filter_serial_or_concole(new)
                File "/usr/lib/python3/dist-packages/salt/modules/virt.py", line 3279, in _filter_serial_or_concole
                  if item.find("source") is not None
              KeyError: 'service'
```

**Setup**
- [X ] on-prem machine
- [X ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
Add statements above to `virt.running` state and apply the state.

**Expected behavior**
Running vm with serial console.

**Screenshots**
N/A

**Versions Report**

```
Salt Version:
          Salt: 3003.3

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.7.3 (default, Jan 22 2021, 20:04:44)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.1.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.1

System Versions:
          dist: debian 10 buster
        locale: UTF-8
       machine: x86_64
       release: 4.19.0-14-amd64
        system: Linux
       version: Debian GNU/Linux 10 buster
```
</details>

**Additional context**
N/A

**Comment by q1x** [comment]
Did some troubleshooting with @cbosdo on slack, he suggested to make the following changes to `modules.virt`:

```
- item.find("source").attrib["service"]
+ item.find("source").get("service")
```

```
- "protocol": item.find("protocol").attrib["type"]
+ "protocol": item.find("protocol").get("type")
```

this indeed solved the problem for now.
