### ISSUE TITLE
[BUG] M2Crypto RSA Error - Salt request timed out. The master is not responding

### ISSUE THREAD

**Issue by rgarcia89** [saltstack/salt#61131]
**Description**
The Salt Master service is failing from time to time ending up with the following log entries:

```
Oct 26 18:20:46 5-7-6-33-1-c44601d5 salt-master[2758921]: [ERROR   ] Future <salt.ext.tornado.concurrent.Future object at 0x7fae7ded25c0> exception was never retrieved: Traceback (most recent call last):
Oct 26 18:20:46 5-7-6-33-1-c44601d5 salt-master[2758921]:   File "/usr/lib/python3.6/site-packages/salt/ext/tornado/gen.py", line 1070, in run
Oct 26 18:20:46 5-7-6-33-1-c44601d5 salt-master[2758921]:     yielded = self.gen.send(value)
Oct 26 18:20:46 5-7-6-33-1-c44601d5 salt-master[2758921]:   File "/usr/lib/python3.6/site-packages/salt/transport/zeromq.py", line 890, in handle_message
Oct 26 18:20:46 5-7-6-33-1-c44601d5 salt-master[2758921]:     self._encrypt_private(ret, req_opts["key"], req_opts["tgt"],)
Oct 26 18:20:46 5-7-6-33-1-c44601d5 salt-master[2758921]:   File "/usr/lib/python3.6/site-packages/salt/transport/mixins/auth.py", line 125, in _encrypt_private
Oct 26 18:20:46 5-7-6-33-1-c44601d5 salt-master[2758921]:     pub = salt.crypt.get_rsa_pub_key(pubfn)
Oct 26 18:20:46 5-7-6-33-1-c44601d5 salt-master[2758921]:   File "/usr/lib/python3.6/site-packages/salt/crypt.py", line 223, in get_rsa_pub_key
Oct 26 18:20:46 5-7-6-33-1-c44601d5 salt-master[2758921]:     key = RSA.load_pub_key_bio(bio)
Oct 26 18:20:46 5-7-6-33-1-c44601d5 salt-master[2758921]:   File "/usr/lib64/python3.6/site-packages/M2Crypto/RSA.py", line 444, in load_pub_key_bio
Oct 26 18:20:46 5-7-6-33-1-c44601d5 salt-master[2758921]:     rsa_error()
Oct 26 18:20:46 5-7-6-33-1-c44601d5 salt-master[2758921]:   File "/usr/lib64/python3.6/site-packages/M2Crypto/RSA.py", line 333, in rsa_error
Oct 26 18:20:46 5-7-6-33-1-c44601d5 salt-master[2758921]:     raise RSAError(Err.get_error_message())
Oct 26 18:20:46 5-7-6-33-1-c44601d5 salt-master[2758921]: M2Crypto.RSA.RSAError: no start line
Oct 26 18:20:49 5-7-6-33-1-c44601d5 salt-master[2758921]: [ERROR   ] Future <salt.ext.tornado.concurrent.Future object at 0x7fae7c8c8e10> exception was never retrieved: Traceback (most recent call last):
Oct 26 18:20:49 5-7-6-33-1-c44601d5 salt-master[2758921]:   File "/usr/lib/python3.6/site-packages/salt/ext/tornado/gen.py", line 1070, in run
Oct 26 18:20:49 5-7-6-33-1-c44601d5 salt-master[2758921]:     yielded = self.gen.send(value)
Oct 26 18:20:49 5-7-6-33-1-c44601d5 salt-master[2758921]:   File "/usr/lib/python3.6/site-packages/salt/transport/zeromq.py", line 890, in handle_message
Oct 26 18:20:49 5-7-6-33-1-c44601d5 salt-master[2758921]:     self._encrypt_private(ret, req_opts["key"], req_opts["tgt"],)
Oct 26 18:20:49 5-7-6-33-1-c44601d5 salt-master[2758921]:   File "/usr/lib/python3.6/site-packages/salt/transport/mixins/auth.py", line 125, in _encrypt_private
Oct 26 18:20:49 5-7-6-33-1-c44601d5 salt-master[2758921]:     pub = salt.crypt.get_rsa_pub_key(pubfn)
Oct 26 18:20:49 5-7-6-33-1-c44601d5 salt-master[2758921]:   File "/usr/lib/python3.6/site-packages/salt/crypt.py", line 223, in get_rsa_pub_key
Oct 26 18:20:49 5-7-6-33-1-c44601d5 salt-master[2758921]:     key = RSA.load_pub_key_bio(bio)
Oct 26 18:20:49 5-7-6-33-1-c44601d5 salt-master[2758921]:   File "/usr/lib64/python3.6/site-packages/M2Crypto/RSA.py", line 444, in load_pub_key_bio
Oct 26 18:20:49 5-7-6-33-1-c44601d5 salt-master[2758921]:     rsa_error()
Oct 26 18:20:49 5-7-6-33-1-c44601d5 salt-master[2758921]:   File "/usr/lib64/python3.6/site-packages/M2Crypto/RSA.py", line 333, in rsa_error
Oct 26 18:20:49 5-7-6-33-1-c44601d5 salt-master[2758921]:     raise RSAError(Err.get_error_message())
Oct 26 18:20:49 5-7-6-33-1-c44601d5 salt-master[2758921]: M2Crypto.RSA.RSAError: no start line
Oct 26 18:25:53 5-7-6-33-1-c44601d5 salt-master[2758921]: [ERROR   ] AES key not found
Oct 26 18:26:21 5-7-6-33-1-c44601d5 salt-master[2758921]: [ERROR   ] Future <salt.ext.tornado.concurrent.Future object at 0x7fae7daf3208> exception was never retrieved: Traceback (most recent call last):
Oct 26 18:26:21 5-7-6-33-1-c44601d5 salt-master[2758921]:   File "/usr/lib/python3.6/site-packages/salt/ext/tornado/gen.py", line 1070, in run
Oct 26 18:26:21 5-7-6-33-1-c44601d5 salt-master[2758921]:     yielded = self.gen.send(value)
Oct 26 18:26:21 5-7-6-33-1-c44601d5 salt-master[2758921]:   File "/usr/lib/python3.6/site-packages/salt/transport/zeromq.py", line 890, in handle_message
Oct 26 18:26:21 5-7-6-33-1-c44601d5 salt-master[2758921]:     self._encrypt_private(ret, req_opts["key"], req_opts["tgt"],)
Oct 26 18:26:21 5-7-6-33-1-c44601d5 salt-master[2758921]:   File "/usr/lib/python3.6/site-packages/salt/transport/mixins/auth.py", line 125, in _encrypt_private
Oct 26 18:26:21 5-7-6-33-1-c44601d5 salt-master[2758921]:     pub = salt.crypt.get_rsa_pub_key(pubfn)
Oct 26 18:26:21 5-7-6-33-1-c44601d5 salt-master[2758921]:   File "/usr/lib/python3.6/site-packages/salt/crypt.py", line 223, in get_rsa_pub_key
Oct 26 18:26:21 5-7-6-33-1-c44601d5 salt-master[2758921]:     key = RSA.load_pub_key_bio(bio)
Oct 26 18:26:21 5-7-6-33-1-c44601d5 salt-master[2758921]:   File "/usr/lib64/python3.6/site-packages/M2Crypto/RSA.py", line 444, in load_pub_key_bio
Oct 26 18:26:21 5-7-6-33-1-c44601d5 salt-master[2758921]:     rsa_error()
Oct 26 18:26:21 5-7-6-33-1-c44601d5 salt-master[2758921]:   File "/usr/lib64/python3.6/site-packages/M2Crypto/RSA.py", line 333, in rsa_error
Oct 26 18:26:21 5-7-6-33-1-c44601d5 salt-master[2758921]:     raise RSAError(Err.get_error_message())
Oct 26 18:26:21 5-7-6-33-1-c44601d5 salt-master[2758921]: M2Crypto.RSA.RSAError: no start line
```

On the minions we see the following logs for the period of time:
```
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]: Traceback (most recent call last):
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:   File "/usr/lib/python3.6/site-packages/salt/utils/schedule.py", line 843, in handle_func
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:     ret["return"] = self.functions[func](*args, **kwargs)
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:   File "/usr/lib/python3.6/site-packages/salt/loader.py", line 1241, in __call__
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:     return self.loader.run(run_func, *args, **kwargs)
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:   File "/usr/lib/python3.6/site-packages/salt/loader.py", line 2274, in run
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:     return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:   File "/usr/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:     return callable(*args, **kwargs)
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:   File "/usr/lib/python3.6/site-packages/salt/loader.py", line 2289, in _run_as
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:     return _func_or_method(*args, **kwargs)
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:   File "/usr/lib/python3.6/site-packages/salt/modules/state.py", line 1094, in highstate
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:     initial_pillar=_get_initial_pillar(opts),
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:   File "/usr/lib/python3.6/site-packages/salt/state.py", line 4635, in __init__
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:     BaseHighState.__init__(self, opts)
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:   File "/usr/lib/python3.6/site-packages/salt/state.py", line 3463, in __init__
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:     self.opts = self.__gen_opts(opts)
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:   File "/usr/lib/python3.6/site-packages/salt/state.py", line 3487, in __gen_opts
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:     mopts = self.client.master_opts()
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:   File "/usr/lib/python3.6/site-packages/salt/fileclient.py", line 1408, in master_opts
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:     return self.channel.send(load)
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:   File "/usr/lib/python3.6/site-packages/salt/utils/asynchronous.py", line 126, in wrap
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:     six.reraise(*results[1])
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:   File "/usr/lib/python3.6/site-packages/salt/ext/six.py", line 693, in reraise
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:     raise value
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:   File "/usr/lib/python3.6/site-packages/salt/utils/asynchronous.py", line 132, in _target
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:     result = io_loop.run_sync(lambda: getattr(self.obj, key)(*args, **kwargs))
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:   File "/usr/lib/python3.6/site-packages/salt/ext/tornado/ioloop.py", line 459, in run_sync
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:     return future_cell[0].result()
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:   File "/usr/lib/python3.6/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:     raise_exc_info(self._exc_info)
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:   File "<string>", line 4, in raise_exc_info
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:   File "/usr/lib/python3.6/site-packages/salt/ext/tornado/gen.py", line 1064, in run
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:     yielded = self.gen.throw(*exc_info)
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:   File "/usr/lib/python3.6/site-packages/salt/transport/zeromq.py", line 444, in send
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:     load, tries=tries, timeout=timeout, raw=raw
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:   File "/usr/lib/python3.6/site-packages/salt/ext/tornado/gen.py", line 1056, in run
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:     value = future.result()
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:   File "/usr/lib/python3.6/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:     raise_exc_info(self._exc_info)
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:   File "<string>", line 4, in raise_exc_info
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:   File "/usr/lib/python3.6/site-packages/salt/ext/tornado/gen.py", line 1064, in run
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:     yielded = self.gen.throw(*exc_info)
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:   File "/usr/lib/python3.6/site-packages/salt/transport/zeromq.py", line 413, in _crypted_transfer
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:     ret = yield _do_transfer()
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:   File "/usr/lib/python3.6/site-packages/salt/ext/tornado/gen.py", line 1056, in run
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:     value = future.result()
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:   File "/usr/lib/python3.6/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:     raise_exc_info(self._exc_info)
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:   File "<string>", line 4, in raise_exc_info
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:   File "/usr/lib/python3.6/site-packages/salt/ext/tornado/gen.py", line 1064, in run
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:     yielded = self.gen.throw(*exc_info)
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:   File "/usr/lib/python3.6/site-packages/salt/transport/zeromq.py", line 396, in _do_transfer
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:     tries=tries,
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:   File "/usr/lib/python3.6/site-packages/salt/ext/tornado/gen.py", line 1056, in run
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:     value = future.result()
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:   File "/usr/lib/python3.6/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:     raise_exc_info(self._exc_info)
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]:   File "<string>", line 4, in raise_exc_info
Oct 26 18:34:07 5-7-6-33-1-c44601d5 salt-minion[2757488]: salt.exceptions.SaltReqTimeoutError: Message timed out
Oct 26 18:38:07 5-7-6-33-1-c44601d5 salt-minion[2757488]: [WARNING ] The minion failed to return the job information for job 20211026183007146025. This is often due to the master being shut down or overloaded. If the master is running, consider increasing the worker_threads value.
Oct 26 18:39:18 5-7-6-33-1-c44601d5 salt-minion[2757488]: [ERROR   ] Unhandled exception running state.highstate
```
In order to fix that issue we have to restart the service of the Salt Master.

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [x] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3003.3

Dependency Versions:
          cffi: 1.11.5
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: 0.26.8
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.14
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: 0.26.4
        Python: 3.6.8 (default, Oct 19 2021, 05:14:06)
  python-gnupg: Not Installed
        PyYAML: 3.12
         PyZMQ: 19.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: centos 8
        locale: UTF-8
       machine: x86_64
       release: 4.18.0-338.el8.x86_64
        system: Linux
       version: CentOS Stream 8

```
</details>

**Comment by garethgreenaway** [comment]
@rgarcia89 Thanks for the report.  We had previously seen this following a change from having pycryptodome as the default to using M2Crypto.  Did you recently upgrade your Salt installations to this version and was that when the issue started?

**Comment by marbx** [comment]
Salt-master repors this error within 60 seconds after restart 

2022-05-27 11:18:36,277 [tornado.application:356 ][ERROR   ][974958] Future <salt.ext.tornado.concurrent.Future object at 0x7fd51d4ace48> exception was never retrieved: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/gen.py", line 309, in wrapper
    yielded = next(result)
  File "/usr/lib/python3.6/site-packages/salt/transport/zeromq.py", line 904, in handle_message
    stream.send(self.serial.dumps(self._auth(payload["load"], sign_messages)))
  File "/usr/lib/python3.6/site-packages/salt/transport/mixins/auth.py", line 520, in _auth
    pub = salt.crypt.get_rsa_pub_key(pubfn)
  File "/usr/lib/python3.6/site-packages/salt/crypt.py", line 224, in get_rsa_pub_key
    key = RSA.load_pub_key_bio(bio)
  File "/usr/lib64/python3.6/site-packages/M2Crypto/RSA.py", line 441, in load_pub_key_bio
    rsa_error()
  File "/usr/lib64/python3.6/site-packages/M2Crypto/RSA.py", line 330, in rsa_error
    raise RSAError(Err.get_error_message())
M2Crypto.RSA.RSAError: no start line


Salt Version:
          Salt: 3002.8

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: 0.33.0
          Mako: Not Installed
       msgpack: 0.6.1
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Sep  9 2021, 07:49:02)
  python-gnupg: Not Installed
        PyYAML: 3.12
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.1

System Versions:
          dist: rhel 8.3 Ootpa
        locale: UTF-8
       machine: x86_64
       release: 4.18.0-348.12.2.el8_5.x86_64
        system: Linux
       version: Red Hat Enterprise Linux 8.3 Ootpa

**Comment by garethgreenaway** [comment]
Closing due to lack of activity.
