### ISSUE TITLE
[BUG] Minion cannot execute state because of missing schedule

### ISSUE THREAD

**Issue by ari** [saltstack/salt#61155]
**Description**

* Upgrade to 3004
* Try to run state on minion

```
2021-10-31 16:21:51,612 [salt.minion                                                :1166][CRITICAL][93523] Unexpected error while connecting to salt.ish.com.au
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/salt/minion.py", line 1140, in _connect_minion
    yield minion.connect_master(failed=failed)
  File "/usr/local/lib/python3.8/site-packages/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/usr/local/lib/python3.8/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/lib/python3.8/site-packages/salt/ext/tornado/gen.py", line 1064, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.8/site-packages/salt/minion.py", line 1369, in connect_master
    yield self._post_master_init(master)
  File "/usr/local/lib/python3.8/site-packages/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/usr/local/lib/python3.8/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/lib/python3.8/site-packages/salt/ext/tornado/gen.py", line 1070, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python3.8/site-packages/salt/minion.py", line 1417, in _post_master_init
    self.schedule = salt.utils.schedule.Schedule(
  File "/usr/local/lib/python3.8/site-packages/salt/utils/schedule.py", line 97, in __new__
    instance.__singleton_init__(
  File "/usr/local/lib/python3.8/site-packages/salt/utils/schedule.py", line 181, in __singleton_init__
    self.delete_job_prefix(prefix)
  File "/usr/local/lib/python3.8/site-packages/salt/utils/schedule.py", line 354, in delete_job_prefix
    for job in list(self.opts["schedule"].keys()):
AttributeError: 'NoneType' object has no attribute 'keys'
```

Also note:

```
# salt-call schedule.list show_all=True
local:
    ----------
    schedule:
        ----------
```

Is this the same schedule this code is assuming exists without any null safe protection around trying to get a list of keys?

**Versions Report**

```
Salt Version:
          Salt: 3004

Dependency Versions:
          cffi: 1.14.6
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.0.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.10.1
        pygit2: Not Installed
        Python: 3.8.12 (default, Oct 22 2021, 11:57:12)
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 22.3.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: freebsd 13.0
        locale: utf-8
       machine: amd64
       release: 13.0-RELEASE-p3
        system: FreeBSD
       version: FreeBSD 13.0
```

**Comment by ari** [comment]
I removed the 3004 from the title, since I can make this happen in 3003.1 too.

**Comment by ari** [comment]
A bare "schedule:" in a minion config file caused this.
