### ISSUE TITLE
[BUG] salt-ssh pkgrepo.managed failed with error TypeError: invalid file: PosixPath('/etc/apt/sources.list')

### ISSUE THREAD

**Issue by dosercz** [saltstack/salt#61175]
**Description**
Pkgrepo.managed failed with error TypeError: invalid file: PosixPath('/etc/apt/sources.list') if called via salt-ssh. It works fine while running the same via salt-minion, so problem is probably in salt-ssh. OS Debian 9, salt v3004.

```
ID: salt-repo
    Function: pkgrepo.managed
        Name: deb [arch=amd64] https://repo.saltproject.io/py3/debian/9/amd64/3004 stretch main
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/var/tmp/.root_29fa9c_salt/pyall/salt/state.py", line 2180, in call
                  *cdata["args"], **cdata["kwargs"]
                File "/var/tmp/.root_29fa9c_salt/pyall/salt/loader/lazy.py", line 149, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "/var/tmp/.root_29fa9c_salt/pyall/salt/loader/lazy.py", line 1201, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/var/tmp/.root_29fa9c_salt/py3/contextvars/__init__.py", line 38, in run
                  return callable(*args, **kwargs)
                File "/var/tmp/.root_29fa9c_salt/pyall/salt/loader/lazy.py", line 1216, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/var/tmp/.root_29fa9c_salt/pyall/salt/loader/lazy.py", line 1249, in wrapper
                  return f(*args, **kwargs)
                File "/var/tmp/.root_29fa9c_salt/pyall/salt/states/pkgrepo.py", line 400, in managed
                  pre = __salt__["pkg.get_repo"](repo=repo, **kwargs)
                File "/var/tmp/.root_29fa9c_salt/pyall/salt/loader/lazy.py", line 149, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "/var/tmp/.root_29fa9c_salt/pyall/salt/loader/lazy.py", line 1201, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/var/tmp/.root_29fa9c_salt/py3/contextvars/__init__.py", line 38, in run
                  return callable(*args, **kwargs)
                File "/var/tmp/.root_29fa9c_salt/pyall/salt/loader/lazy.py", line 1216, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/var/tmp/.root_29fa9c_salt/pyall/salt/modules/aptpkg.py", line 1862, in get_repo
                  repos = list_repos()
                File "/var/tmp/.root_29fa9c_salt/pyall/salt/modules/aptpkg.py", line 1806, in list_repos
                  sources = SourcesList()
                File "/var/tmp/.root_29fa9c_salt/pyall/salt/modules/aptpkg.py", line 205, in __init__
                  self.add_file(file)
                File "/var/tmp/.root_29fa9c_salt/pyall/salt/modules/aptpkg.py", line 215, in add_file
                  with salt.utils.files.fopen(file) as source:
                File "/var/tmp/.root_29fa9c_salt/pyall/salt/utils/files.py", line 385, in fopen
                  f_handle = open(*args, **kwargs)  # pylint: disable=resource-leakage
              TypeError: invalid file: PosixPath('/etc/apt/sources.list')
```

**Setup**
Install salt-master + salt-ssh and setup roster file. The problem occurs at Debian 9 VM with salt v3004. Tested with salt v 2019.2.8 without any problem. No minion installed at target machine, target machine is clean Debian installation.
  
**Steps to Reproduce the behavior**
Call this state via salt-ssh e.g. like: `salt-ssh \* state.sls test`:

```
python-apt:
  pkg.installed

salt-repo:
  pkgrepo.managed:
    - file: /etc/apt/sources.list.d/saltstack.list
    - name: deb [arch=amd64] https://repo.saltproject.io/py3/debian/9/amd64/3004 stretch main
    - clean_file: True
    - key_url: https://repo.saltproject.io/py3/debian/9/amd64/3004/salt-archive-keyring.gpg
    - require:
      - pkg: python-apt
```

**Expected behavior**
Added APT repo in file /etc/apt/sources.list.d/saltstack.list

**Versions Report**
<details><summary>salt --versions-report</summary>

```
Salt Version: Salt: 3004

Dependency Versions:
cffi: Not Installed
cherrypy: Not Installed
dateutil: 2.5.3
docker-py: Not Installed
gitdb: 2.0.0
gitpython: 2.1.1
Jinja2: 2.9.4
libgit2: Not Installed
M2Crypto: Not Installed
Mako: Not Installed
msgpack: 0.6.2
msgpack-pure: Not Installed
mysql-python: Not Installed
pycparser: Not Installed
pycrypto: Not Installed
pycryptodome: 3.6.1
pygit2: Not Installed
Python: 3.5.3 (default, Apr 5 2021, 09:00:41)
python-gnupg: Not Installed
PyYAML: 3.12
PyZMQ: 17.1.2
smmap: 2.0.1
timelib: Not Installed
Tornado: 4.5.3
ZMQ: 4.2.1

System Versions:
dist: debian 9 stretch
locale: UTF-8
machine: x86_64
release: 4.9.0-16-amd64
system: Linux
version: Debian GNU/Linux 9 stretch
```
</details>

**Comment by rnick** [comment]
Same problem here. Runs fine with minion but have the same problem with Debian 9 as Target and salt-ssh v3004.

**Comment by Ch3LL** [comment]
This should be resolved by this: https://github.com/saltstack/salt/pull/61936/files#diff-4942e96e878c10bcad53f5ade902cb904c79835fc642e8a476876afeff18009fR215

Can you test the head of master and see if the  issue still persists?

**Comment by garethgreenaway** [comment]
Closed by the above mentioned PR, if the issue persists please let us know.
