### ISSUE TITLE
[BUG] KeyError: 'proxytype' when using Deltaproxy with more than one device

### ISSUE THREAD

**Issue by ggiesen** [saltstack/salt#61172]
**Description**
When more than one proxy is configured for Deltaproxy, SSH sessions recycle over and over and initialization never completes. Receive the following error over and over:

```
[DEBUG   ] Process Manager starting!
[CRITICAL] Unexpected error while connecting to salt
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/minion.py", line 1140, in _connect_minion
    yield minion.connect_master(failed=failed)
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/gen.py", line 1064, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python3.6/site-packages/salt/minion.py", line 1369, in connect_master
    yield self._post_master_init(master)
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/gen.py", line 1070, in run
    yielded = self.gen.send(value)
  File "/usr/lib64/python3.6/types.py", line 182, in send
    return self.__wrapped.send(val)
  File "/usr/lib/python3.6/site-packages/salt/metaproxy/deltaproxy.py", line 409, in post_master_init
    _proxy_minion.proxy.reload_modules()
  File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1062, in reload_modules
    self._load_all()
  File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1055, in _load_all
    self._load_module(name)
  File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 933, in _load_module
    self.opts["proxy"]["proxytype"] not in mod.__proxyenabled__
KeyError: 'proxytype'
```

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

/srv/pillar/top.sls:
```
base:
  deltaproxy:
    - deltaproxy
{% for sw in range(1,2) %}
  sw{{ sw }}:
    - sw{{ sw }}
{% endfor %}
```
/srv/pillar/sw1.sls
```
proxy:
  driver: ios
  host: 192.168.232.142
  proxytype: napalm
  username: cisco
  passwd: Cisco
  multiprocessing: False
```
/srv/pillar/sw2.sls
```
proxy:
  driver: ios
  host: 192.168.232.143
  proxytype: napalm
  username: cisco
  passwd: Cisco
  multiprocessing: False
```
```
proxy:
  proxytype: deltaproxy
  ids:
    - sw1
    - sw2
```
/etc/salt/proxy.d/metaproxy.conf:
```
metaproxy: deltaproxy
```
Please be as specific as possible and give set-up details.

- [x ] VM (Virtualbox, KVM, etc. please specify)

These are 3 VMs (one AlmaLinux 8 - fully updated, two Cisco CSR1000V routers running IOS-XE 16.12.05) running on VMware Workstation 16.
  
**Steps to Reproduce the behavior**
# salt-proxy --proxyid=deltaproxy

**Expected behavior**
Proxies to come up and be ready to accept commands from Salt.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3004

Dependency Versions:
          cffi: 1.15.0
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.0.2
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Sep 23 2021, 07:23:00)
  python-gnupg: Not Installed
        PyYAML: 6.0
         PyZMQ: 19.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: almalinux 8.4 Electric Cheetah
        locale: UTF-8
       machine: x86_64
       release: 4.18.0-305.el8.x86_64
        system: Linux
       version: AlmaLinux 8.4 Electric Cheetah
```
</details>

**Additional context**
pip list:
```
Package               Version
--------------------- ---------
absl-py               0.15.0
aiocontextvars        0.2.2
Babel                 2.5.1
bcrypt                3.2.0
capirca               2.0.3
certifi               2021.10.8
cffi                  1.15.0
chardet               3.0.4
charset-normalizer    2.0.7
ciscoconfparse        1.5.51
colorama              0.4.4
configobj             5.0.6
contextvars           2.4
cryptography          35.0.0
dbus-python           1.2.4
decorator             4.2.1
distro                1.4.0
dnspython             2.1.0
future                0.18.2
gpg                   1.13.1
idna                  3.3
immutables            0.16
importlib-resources   5.4.0
ipaddress             1.0.23
Jinja2                3.0.2
junos-eznc            2.6.3
loguru                0.5.3
lxml                  4.6.4
M2Crypto              0.35.2
MarkupSafe            2.0.1
mock                  4.0.3
msgpack               0.6.2
napalm                3.3.1
ncclient              0.6.9
netaddr               0.8.0
netmiko               3.4.0
nftables              0.1
ntc-templates         2.3.2
paramiko              2.8.0
passlib               1.7.4
perf                  0.1
pip                   21.3.1
ply                   3.11
psutil                5.4.3
pycparser             2.20
pycurl                7.43.0.2
pyeapi                0.8.4
PyGObject             3.28.3
PyNaCl                1.4.0
pyparsing             3.0.4
pyserial              3.5
PySocks               1.6.8
python-dateutil       2.6.1
python-linux-procfs   0.6.3
pytz                  2017.2
pyudev                0.21.0
PyYAML                6.0
pyzmq                 19.0.0
requests              2.26.0
rpm                   4.14.3
salt                  3004
schedutils            0.6
scp                   0.14.1
selinux               2.9
setuptools            39.2.0
six                   1.11.0
slip                  0.6.4
slip.dbus             0.6.4
syspurpose            1.28.13
systemd-python        234
tenacity              8.0.1
textfsm               1.1.2
transitions           0.8.10
typing-extensions     3.10.0.2
urllib3               1.26.7
wheel                 0.37.0
yamlordereddictloader 0.4.0
zipp                  3.6.0
```

Also tested with NX-OS and Juniper vMX VMs and encountered the same problem.

Edit note: I have corrected the pillar top, which was the source of the problem.

**Comment by ggiesen** [comment]
Also happens if I use the straight junos proxy (no NAPALM).

**Comment by ggiesen** [comment]
Per @garethgreenaway 's PR, the issue here was the jinja range function, or more accurately my lack of paying attention to the parameters. `range(1,2)` only produces 1 number, not 2 as might be intuitively expected, as the high value is omitted (see https://jinja.palletsprojects.com/en/2.10.x/templates/#list-of-global-functions). Thanks Gareth for tracking this down, and producing a fix so hopefully someone else doesn't have to suffer through this again ;)

**Comment by ggiesen** [comment]
I can confirm @garethgreenaway's PR #61251 fixes the original issue, and makes the deltaproxy usable for the hosts that are not missing pillar data.

A stretch goal might be to also fix this:

```
[ERROR   ] Future <salt.ext.tornado.concurrent.Future object at 0x7f91005339e8> exception was never retrieved: Traceback (most recent call last):        
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/gen.py", line 1070, in run
    yielded = self.gen.send(value)
  File "/usr/lib/python3.6/site-packages/salt/transport/zeromq.py", line 539, in wrap_callback
    callback(payload)
  File "/usr/lib/python3.6/site-packages/salt/minion.py", line 3781, in _handle_payload
    return mp_call(self, payload)
  File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1201, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
    return callable(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1216, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/metaproxy/deltaproxy.py", line 877, in handle_payload
    instance = self.deltaproxy_objs[_id]
KeyError: 'sw2'
```

This was me calling a `salt sw2 test.ping` while sw2 had the missing pillar data. I hate seeing tracebacks as it's a bad user experience, so something more friendly like your patch does for initialization would be great. I realize this may get more complicated as you may have to track which proxies are initialized properly but would make for a better user experience if this was relatively easy.
