### ISSUE TITLE
[BUG] cmd.run error: Data failed to compile

### ISSUE THREAD

**Issue by cmonty14** [saltstack/salt#61241]
**Description**
I have created a state that defines a variable.
However, when I execute the state I get this error:
''
    Rendering SLS 'base:manager_org_1.stc-lve-lvm-lv_root' failed: Jinja syntax error: expected token ',', got '{'; line 1

---
{% set vg = salt['cmd.run']('lvs --noheadings | grep root | awk '{ print \$2 }'') %}    <======================
''

**Debug output**
```
[ERROR   ] Rendering exception occurred
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 170, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 416, in render_jinja_tmpl
    tmplstr)
SaltRenderError: Jinja syntax error: expected token ',', got '{'; line 1

---
{% set vg = salt['cmd.run']('lvs --noheadings | grep root | awk '{ print \$2 }'') %}    <======================

root:
  salt.states.lvm.lv_present:
    - vgname: {{ vg }}
    - size: 20G
[...]
---
[CRITICAL] Rendering SLS 'base:manager_org_1.stc-lve-lvm-lv_root' failed: Jinja syntax error: expected token ',', got '{'; line 1

---
{% set vg = salt['cmd.run']('lvs --noheadings | grep root | awk '{ print \$2 }'') %}    <======================

root:
  salt.states.lvm.lv_present:
    - vgname: {{ vg }}
    - size: 20G
[...]
---
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/minion', u'ld3272.wdf.sap.corp', u'tcp://10.237.81.20:4506', u'aes')
[DEBUG   ] Initializing new AsyncAuth for (u'/etc/salt/pki/minion', u'ld3272.wdf.sap.corp', u'tcp://10.237.81.20:4506')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://10.237.81.20:4506
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[DEBUG   ] Trying to connect to: tcp://10.237.81.20:4506
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[DEBUG   ] LazyLoaded highstate.output
local:
    Data failed to compile:
----------
    Rendering SLS 'base:manager_org_1.stc-lve-lvm-lv_root' failed: Jinja syntax error: expected token ',', got '{'; line 1

---
{% set vg = salt['cmd.run']('lvs --noheadings | grep root | awk '{ print \$2 }'') %}    <======================

root:
  salt.states.lvm.lv_present:
    - vgname: {{ vg }}
    - size: 20G
[...]
---
[DEBUG   ] Closing AsyncZeroMQReqChannel instance

```

**Setup**
- [ ] on-prem machine
- [x] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
Execute state with the following content:
```
{% set vg = salt['cmd.run']('lvs --noheadings | grep root | awk '{ print \$2 }'') %}

root:
  salt.states.lvm.lv_present:
    - vgname: {{ vg }}
    - size: 20G
    - resizefs: True
```

**Expected behavior**
The same result as if executing
```
# salt-call --local cmd.run "lvs --noheadings | grep root | awk '{ print \$2 }'"
local:
    vg_sys_r1

```

**Versions Report**
<details><summary>salt-call --versions-report</summary>
```
Salt Version:
           Salt: 3000

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.18 (default, Mar 04 2021, 23:12:42) [GCC]
   python-gnupg: Not Installed
         PyYAML: 5.3.1
          PyZMQ: 14.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.0.4

System Versions:
           dist: SuSE 12 x86_64
         locale: ISO-8859-1
        machine: x86_64
        release: 4.4.180-94.100-default
         system: Linux
        version: SUSE Linux Enterprise Server  12 x86_64

```
</details>

**Additional context**

**Comment by network-shark** [comment]
What happens if you run 

```
{% set vg = salt['cmd.run']("lvs --noheadings | grep root | awk '{ print \$2 }'") %}
```

**Comment by cmonty14** [comment]
The error message is different, but I think the lvs command is now completely messed up:
```
[ERROR   ] Command 'lvs' failed with return code: 5
[ERROR   ] stdout:   Volume group name "|" has invalid characters.
  Cannot process volume group |
  Volume group "grep" not found
  Cannot process volume group grep
  Volume group "root" not found
  Cannot process volume group root
  Volume group "awk" not found
  Cannot process volume group awk
  Volume group name "{ print \$2 }" has invalid characters.
  Cannot process volume group { print \$2 }
[ERROR   ] retcode: 5
[ERROR   ] Command 'lvs' failed with return code: 5
[ERROR   ] output:   Volume group name "|" has invalid characters.
  Cannot process volume group |
  Volume group "grep" not found
  Cannot process volume group grep
  Volume group "root" not found
  Cannot process volume group root
  Volume group "awk" not found
  Cannot process volume group awk
  Volume group name "{ print \$2 }" has invalid characters.
  Cannot process volume group { print \$2 }
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/base/manager_org_1/stc-lve-lvm-lv_root/init.sls' using 'jinja' renderer: 0.0668570995331
[DEBUG   ] Rendered data from file: /var/cache/salt/minion/files/base/manager_org_1/stc-lve-lvm-lv_root/init.sls:


root:
  salt.states.lvm.lv_present:
    - vgname:   Volume group name "|" has invalid characters.
  Cannot process volume group |
  Volume group "grep" not found
  Cannot process volume group grep
  Volume group "root" not found
  Cannot process volume group root
  Volume group "awk" not found
  Cannot process volume group awk
  Volume group name "{ print \$2 }" has invalid characters.
  Cannot process volume group { print \$2 }
    - size: 20G
    - resizefs: True
[CRITICAL] Rendering SLS 'base:manager_org_1.stc-lve-lvm-lv_root' failed: could not find expected ':'
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/minion', u'ld3272.wdf.sap.corp', u'tcp://10.237.81.20:4506', u'aes')
[DEBUG   ] Initializing new AsyncAuth for (u'/etc/salt/pki/minion', u'ld3272.wdf.sap.corp', u'tcp://10.237.81.20:4506')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://10.237.81.20:4506
[DEBUG   ] Trying to connect to: tcp://10.237.81.20:4506
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[DEBUG   ] LazyLoaded highstate.output
local:
    Data failed to compile:
----------
    Rendering SLS 'base:manager_org_1.stc-lve-lvm-lv_root' failed: could not find expected ':'
[DEBUG   ] Closing AsyncZeroMQReqChannel instance

```

**Comment by network-shark** [comment]
You can run the minion with -ltrace then you should see if the command is correct .

**Comment by cmonty14** [comment]
I ran command
`salt-call -l trace state.apply manager_org_1.stc-lve-lvm-lv_root`
but the output is the same in regards to the errors.

This means the `lvs `command is interpreted with everything after `--noheadings`, but there's a pipe `|`.

**Comment by cmonty14** [comment]
Issue solved using `cmd.shell`:
```
{% set vg_root = salt['cmd.shell']("lvs --noheadings | grep root | awk {'print $2'}") %}

stc-lve-lvm_create_logical_volume_root:
  lvm.lv_present:
    - name: root
    - vgname: {{ vg_root }}
    - size: 20G
    - resizefs: True
```
