### ISSUE TITLE
[BUG] cmd.shell - Jinja syntax error: expected token ',', got '=';

### ISSUE THREAD

**Issue by cmonty14** [saltstack/salt#61292]
**Description**
The exeuction of a command that consists of grep and pipe is not working as expected.
The following error is reported when running the state:
```
 Rendering SLS 'base:manager_org_1.stc-lve-migration-saptune2' failed: Jinja syntax error: expected token ',', got '='; line 1

---
{% set saptune_solution = salt['cmd.shell']('grep TUNE_FOR_SOLUTIONS /etc/sysconfig/saptune | cut -d '=' -f 2 | sed s/\"//g') %}    <======================

```
<details><summary>Debugging output salt-call</summary>

```
[ERROR   ] Rendering exception occurred
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 497, in render_jinja_tmpl
    template = jinja_env.from_string(tmplstr)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 880, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)                                                                                                                                                                  File "<unknown>", line 1, in template                                                                                                                                                             File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/usr/lib/python3.6/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/usr/lib/python3.6/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/usr/lib/python3.6/site-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/usr/lib/python3.6/site-packages/jinja2/parser.py", line 181, in parse_set
    expr = self.parse_tuple()
  File "/usr/lib/python3.6/site-packages/jinja2/parser.py", line 620, in parse_tuple
    args.append(parse())
  File "/usr/lib/python3.6/site-packages/jinja2/parser.py", line 432, in parse_expression
    return self.parse_condexpr()
  File "/usr/lib/python3.6/site-packages/jinja2/parser.py", line 437, in parse_condexpr
    expr1 = self.parse_or()
  File "/usr/lib/python3.6/site-packages/jinja2/parser.py", line 450, in parse_or
    left = self.parse_and()
  File "/usr/lib/python3.6/site-packages/jinja2/parser.py", line 459, in parse_and
    left = self.parse_not()
  File "/usr/lib/python3.6/site-packages/jinja2/parser.py", line 470, in parse_not
    return self.parse_compare()
  File "/usr/lib/python3.6/site-packages/jinja2/parser.py", line 474, in parse_compare
    expr = self.parse_math1()
  File "/usr/lib/python3.6/site-packages/jinja2/parser.py", line 496, in parse_math1
    left = self.parse_concat()
  File "/usr/lib/python3.6/site-packages/jinja2/parser.py", line 507, in parse_concat
    args = [self.parse_math2()]
  File "/usr/lib/python3.6/site-packages/jinja2/parser.py", line 517, in parse_math2
    left = self.parse_pow()
  File "/usr/lib/python3.6/site-packages/jinja2/parser.py", line 528, in parse_pow
    left = self.parse_unary()
  File "/usr/lib/python3.6/site-packages/jinja2/parser.py", line 547, in parse_unary
    node = self.parse_postfix(node)
  File "/usr/lib/python3.6/site-packages/jinja2/parser.py", line 676, in parse_postfix
    node = self.parse_call(node)
  File "/usr/lib/python3.6/site-packages/jinja2/parser.py", line 767, in parse_call
    self.stream.expect('comma')
  File "/usr/lib/python3.6/site-packages/jinja2/lexer.py", line 384, in expect
    self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: expected token ',', got '='

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 260, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 515, in render_jinja_tmpl
    "Jinja syntax error: {}{}".format(exc, out), line, tmplstr
salt.exceptions.SaltRenderError: Jinja syntax error: expected token ',', got '='; line 1

---
{% set saptune_solution = salt['cmd.shell']('grep TUNE_FOR_SOLUTIONS /etc/sysconfig/saptune | cut -d '=' -f 2 | sed s/\"//g') %}    <======================
{% set time_date = salt['cmd.run']('date +%d%m%Y-%H%M') %}

{% if not salt['file.search']('/etc/sysconfig/saptune','SAPTUNE_VERSION="2"') %}

stc-lve-migration-saptune2_revert_solution:
[...]
---
[CRITICAL] Rendering SLS 'base:manager_org_1.stc-lve-migration-saptune2' failed: Jinja syntax error: expected token ',', got '='; line 1

---
{% set saptune_solution = salt['cmd.shell']('grep TUNE_FOR_SOLUTIONS /etc/sysconfig/saptune | cut -d '=' -f 2 | sed s/\"//g') %}    <======================
{% set time_date = salt['cmd.run']('date +%d%m%Y-%H%M') %}

{% if not salt['file.search']('/etc/sysconfig/saptune','SAPTUNE_VERSION="2"') %}

stc-lve-migration-saptune2_revert_solution:
[...]
---
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'ld3232.wdf.sap.corp', 'tcp://10.237.81.20:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'ld3232.wdf.sap.corp', 'tcp://10.237.81.20:4506')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://10.237.81.20:4506
[DEBUG   ] Trying to connect to: tcp://10.237.81.20:4506
[TRACE   ] Inserted key into loop_instance_map id 140598188310032 for key ('/etc/salt/pki/minion', 'ld3232.wdf.sap.corp', 'tcp://10.237.81.20:4506', 'aes') and process 17698
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[DEBUG   ] LazyLoaded highstate.output
[TRACE   ] data = {'local': ['Rendering SLS \'base:manager_org_1.stc-lve-migration-saptune2\' failed: Jinja syntax error: expected token \',\', got \'=\'; line 1\n\n---\n{% set saptune_solution
= salt[\'cmd.shell\'](\'grep TUNE_FOR_SOLUTIONS /etc/sysconfig/saptune | cut -d \'=\' -f 2 | sed s/\\"//g\') %}    <======================\n{% set time_date = salt[\'cmd.run\'](\'date +%d%m%Y-%H
%M\') %}\n\n{% if not salt[\'file.search\'](\'/etc/sysconfig/saptune\',\'SAPTUNE_VERSION="2"\') %}\n\nstc-lve-migration-saptune2_revert_solution:\n[...]\n---']}
local:
    Data failed to compile:
----------
    Rendering SLS 'base:manager_org_1.stc-lve-migration-saptune2' failed: Jinja syntax error: expected token ',', got '='; line 1

---
{% set saptune_solution = salt['cmd.shell']('grep TUNE_FOR_SOLUTIONS /etc/sysconfig/saptune | cut -d '=' -f 2 | sed s/\"//g') %}    <======================
{% set time_date = salt['cmd.run']('date +%d%m%Y-%H%M') %}

{% if not salt['file.search']('/etc/sysconfig/saptune','SAPTUNE_VERSION="2"') %}

stc-lve-migration-saptune2_revert_solution:
[...]
---
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
```
</details>

**Setup**
SLS file:
```
{% set saptune_solution = salt['cmd.shell']('grep TUNE_FOR_SOLUTIONS /etc/sysconfig/saptune | cut -d '=' -f 2 | sed s/\"//g') %}
{% set time_date = salt['cmd.run']('date +%d%m%Y-%H%M') %}

{% if not salt['file.search']('/etc/sysconfig/saptune','SAPTUNE_VERSION="2"') %}

stc-lve-migration-saptune2_revert_solution:
  cmd.run:
    - name: saptune solution revert {{ saptune_solution}}
{% endif %}
```

Please be as specific as possible and give set-up details.

- [x] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
Executing salt-call command: `salt-call state.apply manager_org_1.stc-lve-migration-saptune2`

**Expected behavior**
Running `salt-call --local` returns the expected result.
```
salt-call --local cmd.shell 'grep TUNE_FOR_SOLUTIONS /etc/sysconfig/saptune | cut -d '=' -f 2 | sed s/\"//g'
local:
    S4HANA-APPSERVER

```

**Versions Report**
<details><summary>salt-call --versions</summary>
(Provided by running salt-call --versions. No differences in master/minion versions.) 

```
Salt Version:
          Salt: 3002.2

Dependency Versions:
          cffi: 1.13.2
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.17
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.13 (default, Mar 10 2021, 18:30:35) [GCC]
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 17.1.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.3

System Versions:
          dist: sles 15.2
        locale: UTF-8
       machine: x86_64
       release: 5.3.18-24.86-default
        system: Linux
       version: SLES 15.2
```
</details>

**Comment by OrangeDog** [comment]
This is the string you've define: `'grep TUNE_FOR_SOLUTIONS /etc/sysconfig/saptune | cut -d '`

You need to nest quotes correctly. Use `cut -d "="` or escape the single quotes.

**Comment by cmonty14** [comment]
Hello,

unfortunately none of the provided solutions work.

The new error message is:
```
[ERROR   ] Command 'grep' failed with return code: 1
[ERROR   ] stdout: /bin/bash: -c: line 0: unexpected EOF while looking for matching `"'                                                                                                           /bin/bash: -c: line 1: syntax error: unexpected end of file                                                                                                                                       [ERROR   ] retcode: 1
[ERROR   ] Command 'grep' failed with return code: 1
[ERROR   ] output: /bin/bash: -c: line 0: unexpected EOF while looking for matching `"'
/bin/bash: -c: line 1: syntax error: unexpected end of file

```

**Comment by OrangeDog** [comment]
That will be the `"` in your `sed` command. The string is processed by both jinja and by bash. You need the correct escaping.

**Comment by cmonty14** [comment]
> Then you still aren't balancing or escaping quotes correctly. The string is processed by both jinja and by bash. You need to account for both.

Could you please share the syntax that should work in salt state?

**Comment by OrangeDog** [comment]
(not tested)

```sls
{% set saptune_solution = salt['cmd.shell']('grep TUNE_FOR_SOLUTIONS /etc/sysconfig/saptune | cut -d "=" -f 2 | sed s/\\"//g') %}
```

**Comment by cmonty14** [comment]
> (not tested)
> 
> ```yaml-salt
> {% set saptune_solution = salt['cmd.shell']('grep TUNE_FOR_SOLUTIONS /etc/sysconfig/saptune | cut -d "=" -f 2 | sed s/\\"//g') %}
> ```

I have tried this syntax already. the output is posted [here](https://github.com/saltstack/salt/issues/61292#issuecomment-979864731).

Can you please re-open this issue as there's no solution, yet.

**Comment by OrangeDog** [comment]
Then it probably needs backslashes.

There's no bug in Salt here. If you need more help getting the escapes correct, then Slack is probably a better place to ask.
https://join.slack.com/t/saltstackcommunity/shared_invite/zt-3av8jjyf-oBQ2M0vhXOhJpNpRkPWBvg

**Comment by cmonty14** [comment]
Thanks for your advise... I'll continue in Slack.
