### ISSUE TITLE
[BUG] Deltaproxy key-value arguements with napalm_net module to multiple minions.

### ISSUE THREAD

**Issue by n-holmstedt** [saltstack/salt#61315]
**Description**
Getting various error when sending napalm_net function calls, with key-value arguments, to multiple proxy-minions controlled by the same delta-proxy.

Sending the same command, targetting a single minion, works well for all commands.

tested:
net.lldp interface=<interface>  -Yields a TypeError
net.cli '<command>' textfsm_parse=true textfsm_template='<template>'  -Yields a Attribute error

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [x] or a combination, please be explicit
- [ ] jails if it is FreeBSD

Single salt master hosted in a docker container (Docker CE 19.03.8) on CentOS8.1 VM.
Single deltaproxy hosted in a docker container on the same machine.
Six IOX-XR 7.3.2 routers controlled by the delta proxy

The issue occurs both when running the delta-proxy in Kubernetes. 
  
**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)
```
/ # salt router1 net.lldp interface=TenGigE0/0/0/1
router1:
    ----------
    comment:
    out:
        ----------
        TenGigE0/0/0/1:
            None
    result:
        True

/ # salt router\* net.lldp interface=TenGigE0/0/0/1
router1:
    ----------
    comment:
    out:
        ----------
        TenGigE0/0/0/1:
            None
    result:
        True

router2:
    Passed invalid arguments to net.lldp: unhashable type: 'dict'
    ....
router3: 
    Passed invalid arguments to net.lldp: unhashable type: 'dict'
    .... And so on
```

Traceback from deltaproxy for net.lldp:
```
delta_proxy         | Traceback (most recent call last):
delta_proxy         |   File "/usr/local/lib/python3.7/site-packages/salt/metaproxy/deltaproxy.py", line 594, in thread_return
delta_proxy         |     opts, data, func, args, kwargs
delta_proxy         |   File "/usr/local/lib/python3.7/site-packages/salt/loader/lazy.py", line 149, in __call__
delta_proxy         |     return self.loader.run(run_func, *args, **kwargs)
delta_proxy         |   File "/usr/local/lib/python3.7/site-packages/salt/loader/lazy.py", line 1201, in run
delta_proxy         |     return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
delta_proxy         |   File "/usr/local/lib/python3.7/site-packages/salt/loader/lazy.py", line 1216, in _run_as
delta_proxy         |     return _func_or_method(*args, **kwargs)
delta_proxy         |   File "/usr/local/lib/python3.7/site-packages/salt/executors/direct_call.py", line 10, in execute
delta_proxy         |     return func(*args, **kwargs)
delta_proxy         |   File "/usr/local/lib/python3.7/site-packages/salt/loader/lazy.py", line 149, in __call__
delta_proxy         |     return self.loader.run(run_func, *args, **kwargs)
delta_proxy         |   File "/usr/local/lib/python3.7/site-packages/salt/loader/lazy.py", line 1201, in run
delta_proxy         |     return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
delta_proxy         |   File "/usr/local/lib/python3.7/site-packages/salt/loader/lazy.py", line 1216, in _run_as
delta_proxy         |     return _func_or_method(*args, **kwargs)
delta_proxy         |   File "/usr/local/lib/python3.7/site-packages/salt/utils/napalm.py", line 512, in func_wrapper
delta_proxy         |     ret = func(*args, **kwargs)
delta_proxy         |   File "/usr/local/lib/python3.7/site-packages/salt/modules/napalm_network.py", line 1163, in lldp
delta_proxy         |     lldp_neighbors = {interface: lldp_neighbors.get(interface)}
delta_proxy         | TypeError: unhashable type: 'dict'
```

Traceback from deltaproxy for net.cli
```
delta_proxy         | [ERROR   ] Traceback (most recent call last):
delta_proxy         |   File "/usr/local/lib/python3.7/site-packages/salt/utils/napalm.py", line 169, in call
delta_proxy         |     out = getattr(napalm_device.get("DRIVER"), method)(*args, **kwargs)
delta_proxy         |   File "/usr/local/lib/python3.7/site-packages/napalm/iosxr/iosxr.py", line 877, in cli
delta_proxy         |     cli_output[str(command)] = str(self.device._execute_show(command))
delta_proxy         |   File "/usr/local/lib/python3.7/site-packages/napalm/pyIOSXR/iosxr.py", line 505, in _execute_show
delta_proxy         |     show_command=escape_xml(show_command)
delta_proxy         |   File "/usr/local/lib/python3.7/xml/sax/saxutils.py", line 27, in escape
delta_proxy         |     data = data.replace("&", "&amp;")
delta_proxy         | AttributeError: 'dict' object has no attribute 'replace'

```
**Expected behavior**
I expected the proxy-minions to return the same output as when targeted as a single minion.

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3004rc1

Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.3
       libgit2: 1.1.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.17
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: 1.6.1
        Python: 3.7.12 (default, Sep  8 2021, 01:55:52)
  python-gnupg: 0.4.4
        PyYAML: 5.4.1
         PyZMQ: 18.0.1
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.1

System Versions:
          dist: alpine 3.14.2
        locale: UTF-8
       machine: x86_64
       release: 4.18.0-147.5.1.el8_1.x86_64
        system: Linux
       version: Alpine Linux 3.14.2

```
</details>

**Additional context**
Not sure if this is applicable for napalm_net only

**Comment by garethgreenaway** [comment]
@n-holmstedt Thanks for the report.  I was able to reproduce this and I suspect there is a global variable somewhere that is causing this to happen.  As a work around, if you specify the interface name as a non-keyword argument, eg. `salt router\* net.lldp TenGigE0/0/0/1` it should work as expected.

**Comment by dwoz** [comment]
Fixed by #65180 (merged 2023-09-14 into 3006.x, present on 3006.x/3007.x/3008.x/master). Root cause: `load_args_and_kwargs` in salt/minion.py was mutating the `__kwarg__` marker via `pop`, causing the second and subsequent sub-proxies in a deltaproxy loop to receive the kwargs dict positionally (`interface={...}`), which surfaced as `unhashable type: 'dict'` in napalm_network.lldp and `'dict' object has no attribute 'replace'` in net.cli. Closing.
