### ISSUE TITLE
[BUG] boto_secgroup.get_all_security_groups does not work with proivder/profile

### ISSUE THREAD

**Issue by AGirin** [saltstack/salt#61325]
**Description**
Running this command:

salt '<minion>' boto_secgroup.get_all_security_groups profile='base_ec2_private' gives this error:

```
The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python3.6/site-packages/salt/minion.py", line 1912, in _thread_return
        function_name, function_args, executors, opts, data
      File "/usr/lib/python3.6/site-packages/salt/minion.py", line 1868, in _execute_job_function
        return_data = self.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 149, in __call__
        return self.loader.run(run_func, *args, **kwargs)
      File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1201, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "/usr/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
        return callable(*args, **kwargs)
      File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1216, in _run_as
        return _func_or_method(*args, **kwargs)
      File "/usr/lib/python3.6/site-packages/salt/executors/direct_call.py", line 10, in execute
        return func(*args, **kwargs)
      File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 149, in __call__
        return self.loader.run(run_func, *args, **kwargs)
      File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1201, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "/usr/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
        return callable(*args, **kwargs)
      File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1216, in _run_as
        return _func_or_method(*args, **kwargs)
      File "/usr/lib/python3.6/site-packages/salt/modules/boto_secgroup.py", line 303, in get_all_security_groups
        conn = _get_conn(region=region, key=key, keyid=keyid, profile=profile)
      File "/usr/lib/python3.6/site-packages/salt/utils/botomod.py", line 179, in get_connection
        cxkey, region, key, keyid = _get_profile(service, region, key, keyid, profile)
      File "/usr/lib/python3.6/site-packages/salt/utils/botomod.py", line 81, in _get_profile
        key = _profile.get("key", None)
    AttributeError: 'str' object has no attribute 'get'
```

Running the same command while directly providing id, key and region works as expected.

/etc/salt/cloud.provders.d/aws.conf:

```
my-aws-default:
  id: '<key>'
  key: '<private key>'
  keyname: <key name>
  securitygroup: '<security group name>'
  private_key: /root/test
  location: <aws region>
  driver: ec2
```

/etc/cloud.profiles.d/test.conf:

```
base_ec2_private:
  provider: my-aws-default
```

Everything is running 3004.

**Comment by AGirin** [comment]
Salt Version:
          Salt: 3004
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: Not Installed
      dateutil: 2.8.2
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: 0.28.2
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: 0.28.2
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4
 
System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-1160.36.2.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core

**Comment by AGirin** [comment]
Answered my own question. I needed to provide those credentials in salt minion config, not in cloud.profiles.d or cloud.providers.d... I guess those are only for salt-cloud.
