### ISSUE TITLE
[BUG] Running state.apply on salt-master via salt-call throws ERROR from salt.utils.asynchronous after upgrade to 3004

### ISSUE THREAD

**Issue by anitakrueger** [saltstack/salt#61347]
**Description**

After upgrading to 3004, running a state on the salt master to update its github repos and corresponding github key file, throws the following error after a successful state run:

```
-bash-4.2$ sudo salt-call state.apply salt.master.x test=True
17:30:11 17:30:11,740 [salt.state                                           ][INFO    ] Loading fresh modules for state activity
17:30:12 17:30:12,724 [salt.loaded.int.utils.vault                          ][INFO    ] Permission denied from vault
17:30:12 17:30:12,728 [salt.loaded.int.module.publish                       ][INFO    ] Publishing runner 'vault.generate_token' to tcp://10.3.2.225:4506
17:30:13 17:30:13,658 [salt.loaded.int.utils.vault                          ][INFO    ] Permission denied from vault
17:30:13 17:30:13,660 [salt.loaded.int.module.publish                       ][INFO    ] Publishing runner 'vault.generate_token' to tcp://10.3.2.225:4506
17:30:14 17:30:14,637 [salt.state                                           ][INFO    ] Running state [/root/.ssh/github-salt] at time 17:30:14.637437
17:30:14 17:30:14,639 [salt.state                                           ][INFO    ] Executing state file.managed for [/root/.ssh/github-salt]
17:30:14 17:30:14,729 [salt.state                                           ][INFO    ] The file /root/.ssh/github-salt is in the correct state
17:30:14 17:30:14,729 [salt.state                                           ][INFO    ] Completed state [/root/.ssh/github-salt] at time 17:30:14.728720 (duration_in_ms=91.283)
local:
----------
          ID: github-token-salt
    Function: file.managed
        Name: /root/.ssh/github-salt
      Result: True
     Comment: The file /root/.ssh/github-salt is in the correct state
     Started: 17:30:14.637437
    Duration: 91.283 ms
     Changes:

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:  91.283 ms
17:30:14 17:30:14,875 [salt.utils.asynchronous                              ][ERROR   ] Exception encountered while running stop method
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/asynchronous.py", line 98, in close
    method()
  File "/usr/lib/python3.6/site-packages/salt/transport/zeromq.py", line 177, in close
    log.debug("Closing %s instance", self.__class__.__name__)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1296, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/_logging/impl.py", line 298, in _log
    stack_info=stack_info,
  File "/usr/lib64/python3.6/logging/__init__.py", line 1444, in _log
    self.handle(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1454, in handle
    self.callHandlers(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1516, in callHandlers
    hdlr.handle(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 865, in handle
    self.emit(record)
  File "/usr/lib64/python3.6/logging/handlers.py", line 482, in emit
    logging.FileHandler.emit(self, record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1071, in emit
    self.stream = self._open()
  File "/usr/lib64/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
NameError: name 'open' is not defined
Exception ignored in: <bound method RemoteClient.__del__ of <salt.fileclient.RemoteClient object at 0x7f26d7b64710>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/fileclient.py", line 1093, in __del__
  File "/usr/lib/python3.6/site-packages/salt/fileclient.py", line 1108, in destroy
  File "/usr/lib/python3.6/site-packages/salt/utils/asynchronous.py", line 102, in close
  File "/usr/lib64/python3.6/logging/__init__.py", line 1343, in exception
  File "/usr/lib64/python3.6/logging/__init__.py", line 1337, in error
  File "/usr/lib/python3.6/site-packages/salt/_logging/impl.py", line 298, in _log
  File "/usr/lib64/python3.6/logging/__init__.py", line 1444, in _log
  File "/usr/lib64/python3.6/logging/__init__.py", line 1454, in handle
  File "/usr/lib64/python3.6/logging/__init__.py", line 1516, in callHandlers
  File "/usr/lib64/python3.6/logging/__init__.py", line 865, in handle
  File "/usr/lib64/python3.6/logging/handlers.py", line 482, in emit
  File "/usr/lib64/python3.6/logging/__init__.py", line 1071, in emit
  File "/usr/lib64/python3.6/logging/__init__.py", line 1061, in _open
NameError: name 'open' is not defined
Exception ignored in: <bound method AsyncZeroMQReqChannel.__del__ of <salt.transport.zeromq.AsyncZeroMQReqChannel object at 0x7f26dcfe5b70>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/transport/zeromq.py", line 185, in __del__
  File "/usr/lib/python3.6/site-packages/salt/transport/zeromq.py", line 177, in close
  File "/usr/lib64/python3.6/logging/__init__.py", line 1296, in debug
  File "/usr/lib/python3.6/site-packages/salt/_logging/impl.py", line 298, in _log
  File "/usr/lib64/python3.6/logging/__init__.py", line 1444, in _log
  File "/usr/lib64/python3.6/logging/__init__.py", line 1454, in handle
  File "/usr/lib64/python3.6/logging/__init__.py", line 1516, in callHandlers
  File "/usr/lib64/python3.6/logging/__init__.py", line 865, in handle
  File "/usr/lib64/python3.6/logging/handlers.py", line 482, in emit
  File "/usr/lib64/python3.6/logging/__init__.py", line 1071, in emit
  File "/usr/lib64/python3.6/logging/__init__.py", line 1061, in _open
NameError: name 'open' is not defined
/usr/lib/python3.6/site-packages/salt/transport/zeromq.py:1147: UserWarning: Unregistering FD 35 after closing socket. This could result in unregistering handlers for the wrong socket. Please use stream.close() instead of closing the socket directly.
```

**Setup**

This error is thrown on the console after a successful state run. It only happens in this one state. The state originally had some other states in it, but I've narrowed it down to the file.managed state that manages a keyfile. We store the key in vault and get it from there using vault.read_secret.

```
{%- set github = salt.vault.read_secret("secret/github/tokens/salt") %}
github-token-salt:
  file.managed:
    - name: /root/.ssh/github-salt
    - contents: |-
        {{ github.private | indent(8) }}
    - user: root
    - group: root
    - mode: 400
```

Here are the conditions I found through trial and error as to when the ERROR appears after the successful state run:
* it does NOT happen when the file does not exist
* it does NOT happen when I put a sleep for 1 second into the same state
* it happens when the file is already in the correct state
* it happens when the file is there but not in the correct state (i.e. has been changed)
  
This is the sleep state I added to make the error go away:

```
sleep:
  module.run:
    - test.sleep:
      - 1
```

**Steps to Reproduce the behavior**

Run the state above and get the error at the end of the successful salt-call.

**Expected behavior**

No error should be thrown.

**Versions Report**

```
Salt Version:
          Salt: 3004

Dependency Versions:
          cffi: 1.14.5
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: 1.4.6
     pycparser: 2.20
      pycrypto: 3.10.1
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Aug  7 2019, 17:28:10)
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4

System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-1062.4.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core
```

**Additional context**

As far as I can see this is the only state were the error happens and it only happens when running salt-call on the salt master. It only happens after upgrading to 3004 (we were running 3002.5 before).
When running salt from the salt master and targeting the salt master another way (by grains or minion ID), the error does not appear. So it seems it is related to `salt-call`.
I have also tried different log levels for `salt-call` via the `-l` option including `debug`, `quiet`, `warning` and `all` and in any case, the error appears.

**Comment by OrangeDog** [comment]
Well that's very odd. The stacktrace suggests your python installation has become corrupted somehow.
A reinstall of python3.6 may fix it.

If that doesn't work, does the error go away if you downgrade Salt back to 3002?

**Comment by anitakrueger** [comment]
@OrangeDog I have tried to reinstall python3 and python36 from the redhat saltstack repo. No avail.
I've downgraded salt to 3002.5 and the error is immediately gone. Back up to 3004, it is back.

Also to note, when running the state and the file is new, the error is gone. It only appears when the file is already there.
And it only happens when running salt-call, not when targeting through the master.

I am not sure how else to troubleshoot? Thank you for your help!

**Comment by max-arnold** [comment]
Same here. Salt 3004 on Ubuntu 18 or 20, the command is run on a master:

```
# salt-call cp.list_master
local:
[ERROR   ] Exception encountered while running stop method
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/asynchronous.py", line 101, in close
    method()
  File "/usr/lib/python3/dist-packages/salt/transport/tcp.py", line 326, in close
    log.debug("Closing %s instance", self.__class__.__name__)
  File "/usr/lib/python3.6/logging/__init__.py", line 1296, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/_logging/impl.py", line 310, in _log
    stack_info=stack_info,
  File "/usr/lib/python3.6/logging/__init__.py", line 1444, in _log
    self.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1454, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1516, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 865, in handle
    self.emit(record)
  File "/usr/lib/python3.6/logging/handlers.py", line 482, in emit
    logging.FileHandler.emit(self, record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1071, in emit
    self.stream = self._open()
  File "/usr/lib/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
NameError: name 'open' is not defined
Exception ignored in: <bound method RemoteClient.__del__ of <salt.fileclient.RemoteClient object at 0x7f3660c1bfd0>>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/fileclient.py", line 1098, in __del__
  File "/usr/lib/python3/dist-packages/salt/fileclient.py", line 1113, in destroy
  File "/usr/lib/python3/dist-packages/salt/utils/asynchronous.py", line 105, in close
  File "/usr/lib/python3.6/logging/__init__.py", line 1343, in exception
  File "/usr/lib/python3.6/logging/__init__.py", line 1337, in error
  File "/usr/lib/python3/dist-packages/salt/_logging/impl.py", line 310, in _log
  File "/usr/lib/python3.6/logging/__init__.py", line 1444, in _log
  File "/usr/lib/python3.6/logging/__init__.py", line 1454, in handle
  File "/usr/lib/python3.6/logging/__init__.py", line 1516, in callHandlers
  File "/usr/lib/python3.6/logging/__init__.py", line 865, in handle
  File "/usr/lib/python3.6/logging/handlers.py", line 482, in emit
  File "/usr/lib/python3.6/logging/__init__.py", line 1071, in emit
  File "/usr/lib/python3.6/logging/__init__.py", line 1061, in _open
NameError: name 'open' is not defined
Exception ignored in: <bound method AsyncTCPReqChannel.__del__ of <salt.transport.tcp.AsyncTCPReqChannel object at 0x7f3660c2ed68>>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/transport/tcp.py", line 348, in __del__
  File "/usr/lib/python3/dist-packages/salt/transport/tcp.py", line 326, in close
  File "/usr/lib/python3.6/logging/__init__.py", line 1296, in debug
  File "/usr/lib/python3/dist-packages/salt/_logging/impl.py", line 310, in _log
  File "/usr/lib/python3.6/logging/__init__.py", line 1444, in _log
  File "/usr/lib/python3.6/logging/__init__.py", line 1454, in handle
  File "/usr/lib/python3.6/logging/__init__.py", line 1516, in callHandlers
  File "/usr/lib/python3.6/logging/__init__.py", line 865, in handle
  File "/usr/lib/python3.6/logging/handlers.py", line 482, in emit
  File "/usr/lib/python3.6/logging/__init__.py", line 1071, in emit
  File "/usr/lib/python3.6/logging/__init__.py", line 1061, in _open
NameError: name 'open' is not defined
[ERROR   ] Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7f3660c3af28>, <salt.ext.tornado.concurrent.Future object at 0x7f3660bc4dd8>)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/transport/tcp.py", line 1183, in _stream_return
    wire_bytes = yield self._read_until_future
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
salt.ext.tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/ioloop.py", line 606, in _run_callback
    ret = callback()
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/stack_context.py", line 278, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/ioloop.py", line 628, in _discard_future_result
    future.result()
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/gen.py", line 1064, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python3/dist-packages/salt/transport/tcp.py", line 1208, in _stream_return
    self.port,
  File "/usr/lib/python3.6/logging/__init__.py", line 1296, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/_logging/impl.py", line 310, in _log
    stack_info=stack_info,
  File "/usr/lib/python3.6/logging/__init__.py", line 1444, in _log
    self.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1454, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1516, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 865, in handle
    self.emit(record)
  File "/usr/lib/python3.6/logging/handlers.py", line 482, in emit
    logging.FileHandler.emit(self, record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1071, in emit
    self.stream = self._open()
  File "/usr/lib/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
NameError: name 'open' is not defined
Exception ignored in: <bound method SaltMessageClientPool.__del__ of <salt.transport.tcp.SaltMessageClientPool object at 0x7f3660c2efd0>>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/transport/tcp.py", line 978, in __del__
  File "/usr/lib/python3/dist-packages/salt/transport/tcp.py", line 984, in close
  File "/usr/lib/python3/dist-packages/salt/transport/tcp.py", line 1095, in close
  File "/usr/lib/python3.6/logging/__init__.py", line 1308, in info
  File "/usr/lib/python3/dist-packages/salt/_logging/impl.py", line 310, in _log
  File "/usr/lib/python3.6/logging/__init__.py", line 1444, in _log
  File "/usr/lib/python3.6/logging/__init__.py", line 1454, in handle
  File "/usr/lib/python3.6/logging/__init__.py", line 1516, in callHandlers
  File "/usr/lib/python3.6/logging/__init__.py", line 865, in handle
  File "/usr/lib/python3.6/logging/handlers.py", line 482, in emit
  File "/usr/lib/python3.6/logging/__init__.py", line 1071, in emit
  File "/usr/lib/python3.6/logging/__init__.py", line 1061, in _open
NameError: name 'open' is not defined
```

**Comment by OrangeDog** [comment]
This is caused by trying to log during asynchronous shutdown in Python <3.10
https://stackoverflow.com/a/64690062/476716

**Comment by dwoz** [comment]
This may be fixed by #63984

**Comment by dwoz** [comment]
Fixed. The `__del__`-during-shutdown code paths in `salt/fileclient.py` and the shutdown-time `log.debug("Closing %s instance", ...)` calls in `salt/transport/zeromq.py` have been removed on 3006.x, 3007.x, 3008.x, and master (via #63984 and follow-ups). 3004 and Python 3.6 are both EOL. Closing.
