### ISSUE TITLE
[TECH DEBT] unknown flags  experimental_control_plane and experimental_upload_certs  in kubeadm v1.23.0

### ISSUE THREAD

**Issue by daro1337** [saltstack/salt#61369]
### Description of the tech debt to be addressed, include links and screenshots
I've tried to use kubeadm module to bootstrap k8s cluster (1.23.0)
https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.kubeadm.html#salt.modules.kubeadm.init

`experimental_upload_certs` and `experimental_control_plane` are invalid for newer versions of kubeadm 
e.g 1.23.0 like in my case.
https://github.com/kubernetes/kubeadm/issues/2366

https://github.com/saltstack/salt/blob/master/salt/modules/kubeadm.py#L1093-L1094
https://github.com/saltstack/salt/blob/master/salt/modules/kubeadm.py#L1261-L1262

Stack trace:
```
          ID: k8s_kubeadm_init
    Function: module.run
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 2179, in call
                  ret = self.states[cdata["full"]](
                File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 149, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1201, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1216, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1249, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/utils/decorators/__init__.py", line 742, in _decorate
                  return self._call_function(kwargs)
                File "/usr/lib/python3/dist-packages/salt/utils/decorators/__init__.py", line 355, in _call_function
                  return self._function(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/module.py", line 424, in run
                  func_ret = _call_function(
                File "/usr/lib/python3/dist-packages/salt/states/module.py", line 470, in _call_function
                  mret = salt.utils.functools.call_function(__salt__[name], *func_args, **func_kwargs)
                File "/usr/lib/python3/dist-packages/salt/utils/functools.py", line 150, in call_function
                  return salt_function(*function_args, **function_kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 149, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1201, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1216, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/modules/kubeadm.py", line 1125, in init
                  return _cmd(cmd)
                File "/usr/lib/python3/dist-packages/salt/modules/kubeadm.py", line 152, in _cmd
                  raise CommandExecutionError(result["stderr"])
              salt.exceptions.CommandExecutionError: unknown flag: --experimental-upload-certs
              To see the stack trace of this error execute with --v=5 or higher
     Started: 07:52:46.549030
    Duration: 261.487 ms
     Changes:   
----------

```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
Salt Version:
          Salt: 3004
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: 4.1.0
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: 0.31.0
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.8.10 (default, Sep 28 2021, 16:10:42)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2
 
System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-91-generic
        system: Linux
       version: Ubuntu 20.04 focal
```

**Comment by daro1337** [comment]
After analyzing the [source code of the module](https://github.com/saltstack/salt/blob/master/salt/modules/kubeadm.py#L1121-L1125), I found a hacky workaround - you can inject your own parameters:

Example:
```
  - ignore_preflight_errors: "True --upload_certs=True --control-plane-endpoint {{ control_plane_endpoint }} --v=5"
```

```
{% set control_plane_endpoint = salt['pillar.get']('k8s-kube-vip:fqdn') %}

k8s_kubeadm_init:
  module.run:
    - kubeadm.init:
      - ignore_preflight_errors: "True --upload_certs=True --control-plane-endpoint {{ control_plane_endpoint }} --v=5"
      - token: {{ salt['pillar.get']('k8s:token') }}
      - token_ttl: {{ salt['pillar.get']('k8s:token_ttl') }}
    - onlyif:
      - test ! -f /etc/kubernetes/kubelet.conf

k8s_kubeadm_join_master:
  module.run:
    - kubeadm.join:
      - api_server_endpoint: {{ salt['pillar.get']('k8s-kube-vip:fqdn') }}
      - apiserver_bind_port: {{ salt['pillar.get']('k8s-kube-vip:port', '6443') }}
      - discovery_token_unsafe_skip_ca_verification: True
      - ignore_preflight_errors: 'True --control_plane=True'
      - token: {{ salt['pillar.get']('k8s:token') }}
    - onlyif:
      - test ! -f /etc/kubernetes/kubelet.conf
```

**Comment by garethgreenaway** [comment]
@daro1337 Thanks for the report.  Would you be willing to submit your fix above as a PR?

**Comment by daro1337** [comment]
@garethgreenaway  sure, done :)
