### ISSUE TITLE
[BUG] Cannot call transactional-update from within transactional-update environment!

### ISSUE THREAD

**Issue by user-name-is-taken** [saltstack/salt#61379]
**Description**
I get `salt.exceptions.CommandExecutionError: Cannot call transactional-update from within transactional-update environment!` whenever running the transactional-update module from within a state [as described in the salt docs](https://docs.saltproject.io/en/latest/ref/states/all/salt.states.module.html).

**Setup**

sls file 

```yaml
env: 
  module.run:
    - transactional_update.patch:
      - snapshot: continue

anotherEnv:
  module.run:
    - transactional_update.call: 
      - test.ping

yetAnotherEnv:
  module.run:
    - transactional_update.pkg_install: 
      - cockpit
```

output

```
----------
          ID: env
    Function: module.run
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/var/cache/salt/minion/tmpdxmiica8/pyall/salt/state.py", line 2186, in call
                  ret = self.states[cdata["full"]](
                File "/var/cache/salt/minion/tmpdxmiica8/pyall/salt/loader.py", line 2113, in wrapper
                  return f(*args, **kwargs)
                File "/var/cache/salt/minion/tmpdxmiica8/pyall/salt/utils/decorators/__init__.py", line 738, in _decorate
                  return self._call_function(kwargs)
                File "/var/cache/salt/minion/tmpdxmiica8/pyall/salt/utils/decorators/__init__.py", line 352, in _call_function
                  return self._function(*args, **kwargs)
                File "/var/cache/salt/minion/tmpdxmiica8/pyall/salt/states/module.py", line 421, in run
                  func_ret = _call_function(
                File "/var/cache/salt/minion/tmpdxmiica8/pyall/salt/states/module.py", line 467, in _call_function
                  mret = salt.utils.functools.call_function(__salt__[name], *func_args, **func_kwargs)
                File "/var/cache/salt/minion/tmpdxmiica8/pyall/salt/utils/functools.py", line 159, in call_function
                  return salt_function(*function_args, **function_kwargs)
                File "/var/cache/salt/minion/tmpdxmiica8/pyall/salt/modules/transactional_update.py", line 717, in patch
                  return _cmd(cmd)
                File "/var/cache/salt/minion/tmpdxmiica8/pyall/salt/modules/transactional_update.py", line 364, in _cmd
                  raise salt.exceptions.CommandExecutionError(result["stderr"])
              salt.exceptions.CommandExecutionError: Cannot call transactional-update from within transactional-update environment!
     Started: 07:27:58.192040
    Duration: 31.373 ms
     Changes:
----------
          ID: anotherEnv
    Function: module.run
      Result: False
     Comment: 'transactional_update.call' failed: Cannot call transactional-update from within transactional-update environment!
     Started: 07:27:58.223671
    Duration: 4375.585 ms
     Changes:
----------
          ID: yetAnotherEnv
    Function: module.run
      Result: False
     Comment: 'transactional_update.pkg_install' failed: pkg_install() got multiple values for argument 'pkg'
     Started: 07:28:02.599452
    Duration: 2.797 ms
     Changes:
```

- For details on how I'm pulling this SLS file into my cluster, see [this README.md](https://gitlab.com/infrastructure24/salt-iac/-/blob/main/README.md) and [this README.md](https://gitlab.com/infrastructure24/salt-iac/-/blob/main/states/README.md)
- [x] on-prem machine (kubic)
  
**Steps to Reproduce the behavior**

```
# salt-run fileserver.update
# salt '*' state.apply
```

**Expected behavior**
I expect the module to run from the state and produce results similar to calling the module from the command line like below.

```
# salt '*' transactional_update.call test.ping
hpe.verizon.net:
    True
thor.verizon.net:
    True
```

**Versions Report**
<details><summary>
</summary>

```
salt --versions-report
Salt Version:
          Salt: 3003.3

Dependency Versions:
          cffi: 1.15.0
      cherrypy: unknown
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.3
       libgit2: 1.3.0
      M2Crypto: 0.37.1
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: 3.11.0
  pycryptodome: Not Installed
        pygit2: 1.7.0
        Python: 3.8.10 (default, May 05 2021, 15:36:36) [GCC]
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 22.0.3
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: opensuse-microos 20210524
        locale: utf-8
       machine: x86_64
       release: 5.12.4-1-default
        system: Linux
       version: openSUSE MicroOS 20210524
```

- I also had to install the transactional update module on the minions with `transactional-update pkg install salt-transactional-update`
- I also added the following file to switch to the new module format on my minions

```
name:/etc/salt/minion.d # cat module.conf
use_superseded:
  - module.run
```

</details>

**Additional context**

- [SUSE code with error](https://github.com/openSUSE/transactional-update/blob/master/sbin/transactional-update.in)
- [My full repo](https://gitlab.com/infrastructure24/salt-iac)

**Comment by waynew** [comment]
This might be an error with how the commands are being sent. It looks like https://github.com/openSUSE/transactional-update/blob/master/sbin/transactional-update.in#L1044 is what's emitting that error message.

I don't think I have access to a transactional-update system (today is the first time I've even heard of it!)

**Comment by waynew** [comment]
@user-name-is-taken I still haven't been able to reproduce this or verify that this is a bug in Salt. If you still have access to a system, I'd be happy to hop on a tmate, jitsi, zoom, or whatever session to try and verify this.

**Comment by SchoolGuy** [comment]
@meaksh @agraul @vzhestkov maybe you can help out here. Just stumbled across this. Do we have a patch for this already in openSUSE with a PR here maybe? The usecase seems to be common or (if this is not a bug but a user error) this is not documented well enough mabye?

**Comment by agraul** [comment]
We don't have a patch, and I don't think we can easily patch this. My understanding of `transactional-update` is that you can't call it inside "of itself" because that wouldn't make sense.

In general, we expect that `state.apply` wants to be applied inside the "next" transaction because that's how transactional systems work. By default, we therefore configure salt to use the `transactional_update` executor and have a list of salt modules and a list of module.functions that use this executor. 

Looking at https://gitlab.com/infrastructure24/salt-iac/-/blob/main/states/transactional-update.sls, I don't understand the need for these `module.run` states. A `pkg.installed` or `pkg.patch_installed` should be enough. @user-name-is-taken can you share more about your use case that requires calling `module.run` in your sls file?

@waynew if you still want to play with transactional OSes, you could try https://get.opensuse.org/microos/

**Comment by tjyang** [comment]
I have this error message on a RL8.9 running salt-master 3007 onedir also, discovered this error when I enable to TRACE level of logging

**Comment by m-czernek** [comment]
Just to add to this issue, if you're facing this issue, you're likely using the `transactional_update` [execution module](https://github.com/saltstack/salt/blob/master/salt/modules/transactional_update.py) when the [transactional_update executor](https://github.com/saltstack/salt/blob/master/salt/modules/transactional_update.py) already opens a transaction for you.

On MicroOS, you can check if you're in an open transaction by, for example, checking the `TRANSACTIONAL_UPDATE` variable:

```
salt:~ # salt '*' cmd.run 'echo $TRANSACTIONAL_UPDATE'
slem-minion:
    true
```

In that case, use do not use the `transactional_update` module; use standard modules in commands (e.g. `salt '*' state.sls example`) as well as in sls and they'll execute within an open transaction.

**Comment by vzhestkov** [comment]
Looks like the issue can be closed, as @m-czernek mentioned it looks like the state was applied inside the transaction when transactional_update module was already used, so no need to try to use it explicitly with the state internally. It should be performend fully inside the transaction with transactional_update execution module replacing the call for `state.apply` with `transactional_update` alternative to perform it fully inside the transaction (in this case no need to use `transactional_update.*` inside the state) or use `state.apply` with `direct_call` outside of the transaction.
