### ISSUE TITLE
[BUG] Unable to install any new yum pkgs on Centos7 with salt 3004

### ISSUE THREAD

**Issue by username-is-already-taken2** [saltstack/salt#61387]
**Description**
A bit of weird one, I noticed that I can't seem to install any new packages on my centos (7.9.2009) box with salt 3004, if I ask it to make sure a package that I know is already installed then that works fine, so its 

```
install_yum-cron:
  pkg.installed:
    - pkgs:
      - yum-cron
```

Error
```
# salt-call --local state.sls os.yum_cron_pkg
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/state.py", line 2180, in call
    *cdata["args"], **cdata["kwargs"]
  File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1201, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
    return callable(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1216, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1249, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/states/pkg.py", line 1904, in installed
    **kwargs
  File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1201, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
    return callable(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1216, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/modules/yumpkg.py", line 1700, in install
    holds = list_holds(full=False)
  File "/usr/lib/python3.6/site-packages/salt/modules/yumpkg.py", line 2423, in list_holds
    _check_versionlock()
  File "/usr/lib/python3.6/site-packages/salt/modules/yumpkg.py", line 273, in _check_versionlock
    vl_plugin = _versionlock_pkg()
  File "/usr/lib/python3.6/site-packages/salt/modules/yumpkg.py", line 264, in _versionlock_pkg
    if int(grains.get("osmajorrelease")) == 5
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```
versions....
```
# salt-call --versions-report
Salt Version:
          Salt: 3004

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4

System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-1160.49.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core
```
I'll try it with a docker container

**Comment by lukasraska** [comment]
@username-is-already-taken2 that looks like your grains values (in particular the `osmajorrelease`) is `None`, rather than number. That grain should be set from `osrelease`, (https://github.com/saltstack/salt/blob/v3004/salt/grains/core.py#L2303), and if that fails for some reason, it won't be set (which could cause this behaviour).

The `osrelease` seems to be derived from the `distro` python module (https://github.com/saltstack/salt/blob/v3004/salt/grains/core.py#L2106, https://github.com/saltstack/salt/blob/v3004/salt/grains/core.py#L2132). Can you whare output from `salt-call --local grains.items` and check whether you don't have any specific value for `osrelease` set in `/etc/salt/minion` or any of `/etc/salt/minion.d/*` files?

**Comment by garethgreenaway** [comment]
@username-is-already-taken2 Just wanted to check that you saw the message from @lukasraska and if you can provide that information.  Thanks!

**Comment by garethgreenaway** [comment]
@username-is-already-taken2 Since 3004 has a known vulnerability so please upgrade to 3004.2, if the issue persists please open a new issue.
