### ISSUE TITLE
[BUG] SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats (python 3.10)

### ISSUE THREAD

**Issue by th0ma7** [saltstack/salt#61384]
**Description**
Hitting the following error message at startup:
```
Mon Dec 20 21:55:00 EST 2021
Starting salt-minion command /volume1/@appstore/salt-minion/env/bin/salt-minion -c /volume1/@appstore/salt-minion/env/etc/salt -d 
Process Process-1:
Traceback (most recent call last):
  File "/var/packages/python310/target/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/var/packages/python310/target/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/volume1/@appstore/salt-minion/env/lib/python3.10/site-packages/salt/scripts.py", line 101, in minion_process
    salt.utils.process.appendproctitle("KeepAlive")
  File "/volume1/@appstore/salt-minion/env/lib/python3.10/site-packages/salt/utils/process.py", line 54, in appendproctitle
    setproctitle.setproctitle(setproctitle.getproctitle() + " " + name)
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
salt-minion is not running
```

**Setup**
Package built using SynoCommunity framework for multi-arch linux platforms.
  
**Steps to Reproduce the behavior**
Porting existing package to python 3.10 resulted in this error.

**Expected behavior**
N/A

**Screenshots**
N/A

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
$ ./salt-minion --version
Process Process-1:
Traceback (most recent call last):
  File "/var/packages/python310/target/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/var/packages/python310/target/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/volume1/@appstore/salt-minion/env/lib/python3.10/site-packages/salt/scripts.py", line 101, in minion_process
    salt.utils.process.appendproctitle("KeepAlive")
  File "/volume1/@appstore/salt-minion/env/lib/python3.10/site-packages/salt/utils/process.py", line 54, in appendproctitle
    setproctitle.setproctitle(setproctitle.getproctitle() + " " + name)
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
```
</details>

**Additional context**
Issue not encountered using python 3.8

**Comment by lukasraska** [comment]
@th0ma7 This is issue in `setproctitle` library, not in Salt itself. Depending on how you want to handle this, you can either update `setproctitle` to version 1.2 or newer, or uninstall `setproctitle`, in which case Salt will not use it

**Comment by OrangeDog** [comment]
https://github.com/dvarrazzo/py-setproctitle/issues/83

**Comment by lukasraska** [comment]
The requirements should probably be bumped, so it doesn't list the not-working version in https://github.com/saltstack/salt/blob/master/requirements/static/pkg/py3.10/linux.txt#L76

**Comment by th0ma7** [comment]
Thnx, got it to almost work with no errors with the changes (daemon eventually stop after 10-30ish seconds, still investigating that):
```
./salt-minion --versions
Salt Version:
          Salt: 3004
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.17
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.10.0 (default, Dec  6 2021, 01:47:34) [GCC 7.5.0]
  python-gnupg: 0.4.4
        PyYAML: 5.4.1
         PyZMQ: 20.0.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.3
 
System Versions:
          dist:   
        locale: utf-8
       machine: x86_64
       release: 4.4.180+
        system: Linux
       version: Not Installed
```

**Comment by th0ma7** [comment]
@lukasraska and @OrangeDog It turns out I found where the issue was at startup, it needed the `--pid-file ${PID_FILE}` argument so the init script is able to locate the process when checking its status afterwards.

Still one last bit remains, I was able to redirect the sock_dir such as:
```
sock_dir: /volume1/@appdata/salt-minion/run/minion
```
But I'm unable to redirect the "jq" type `process_responsibility_salt-minion.pid` file?  What ever configuration I try using `pidfile:` option ends-up generating the file in the wrong location.  For instance, I want the "jq" pid to be located under the run directory such as:
```
pidfile: /volume1/@appdata/salt-minion/run/process_responsibility_salt-minion.pid
```
But it keeps going elsewhere such as:
```
Starting salt-minion command salt-minion --pid-file /volume1/@appdata/salt-minion/salt-minion.pid -c /volume1/@appstore/salt-minion/etc -d 
2021-12-22 20:57:17,262 [salt.cli.daemons :291 ][INFO    ][8451] Setting up the Salt Minion "DSM7"
2021-12-22 20:57:17,264 [salt.utils.process:244 ][INFO    ][8451] pidfile: /volume1/@appdata/salt-minion/process_responsibility_salt-minion.pid not found
2021-12-22 20:57:18,508 [salt.cli.daemons                         :89  ][INFO    ][8461] Starting up the Salt Minion
2021-12-22 20:57:18,513 [salt.utils.event                         :1125][INFO    ][8461] Starting pull socket on /volume1/@appdata/salt-minion/run/minion/minion_event_b12386228b_pull.ipc
2021-12-22 20:57:19,185 [salt.loaded.int.grains.core                                                         :1176][INFO    ][8461] Although 'dmidecode' was found in path, the current user cannot execute it. Grains output might not be accurate.
2021-12-22 20:57:19,247 [salt.minion                                                                         :1292][INFO    ][8461] Creating minion process manager
```
Am I using the right configuration parameter or is `pidfile` equivalent to `--pid-file` and totally unrelated to the "jq" pid file?  Or is it even possible to move its location?

Thnx in advance!

**Comment by th0ma7** [comment]
Modifying my `requirements.txt` file as a workaround solves the issue until a new version gets released.
```
# webrtcvad==2.0.10           # requires unreleased version at specific commit
git+https://github.com/wiseman/py-webrtcvad@3bd761332a9404f5c9276105070ee814c4428342#egg=webrtcvad
```

**Comment by Ch3LL** [comment]
Fixed by: https://github.com/saltstack/salt/pull/62576
