### ISSUE TITLE
[FEATURE REQUEST] ansiblegate support  playbook on gitfs

### ISSUE THREAD

**Issue by tjyang** [saltstack/salt#61396]
**ansiblegate does not support playbook reside on  gitfs **
- playbook on local /srv file system works.

```
sudo salt 'minion01' ansible.playbooks  playbook=/srv/playbooks/helloworld.yml
```
- From "sudo salt 'minion01' ansible.playbooks  playbook=mygit.playbooks.helloworld.yml"
```
minion01:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python3.6/site-packages/salt/minion.py", line 1912, in _thread_return
        function_name, function_args, executors, opts, data
      File "/usr/lib/python3.6/site-packages/salt/minion.py", line 1868, in _execute_job_function
        return_data = self.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 149, in __call__
        return self.loader.run(run_func, *args, **kwargs)
      File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1201, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "/usr/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
        return callable(*args, **kwargs)
      File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1216, in _run_as
        return _func_or_method(*args, **kwargs)
      File "/usr/lib/python3.6/site-packages/salt/executors/direct_call.py", line 10, in execute
        return func(*args, **kwargs)
      File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 149, in __call__
        return self.loader.run(run_func, *args, **kwargs)
      File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1201, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "/usr/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
        return callable(*args, **kwargs)
      File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1216, in _run_as
        return _func_or_method(*args, **kwargs)
      File "/usr/lib/python3.6/site-packages/salt/utils/decorators/path.py", line 23, in wrapped
        return function(*args, **kwargs)
      File "/usr/lib/python3.6/site-packages/salt/modules/ansiblegate.py", line 368, in playbooks
        retdata = json.loads(ret["stdout"])
      File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
        return _default_decoder.decode(s)
      File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Describe the solution you'd like**
- following command should works.
```
sudo salt 'minion01' ansible.playbooks  playbook=mygit.playbooks.helloworld.yml
```
**Describe alternatives you've considered**

N/A

**Additional context**

This is on latest salt-stack 3004.1 minion and master.

**Please Note**
If this feature request would be considered a substantial change or addition, this should go through a SEP process here https://github.com/saltstack/salt-enhancement-proposals, instead of a feature request.

**Comment by OrangeDog** [comment]
To reference things in the fileserver the syntax would be `salt://playbooks/helloworld.yml`.

You cannot reference individual roots separately. It's just a coincidence if `/srv/` happens to be available as both a fileserver root and a local directory.

**Comment by tjyang** [comment]
>To reference things in the fileserver the syntax would be salt://playbooks/helloworld.yml.

```
[me@salt01 ~]$ sudo salt-run  fileserver.file_list |grep hellow
- mygit/playbooks/helloworld.yml
[me@salt01 ~]$ sudo salt salt01 ansible.playbooks  playbook=salt://playbooks/helloworld.yml
```

- Same json decode error using salt:// syntax

```
salt01:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python3.6/site-packages/salt/minion.py", line 1912, in _thread_return
        function_name, function_args, executors, opts, data
<snipped>
        return _default_decoder.decode(s)
      File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

-  Hopefully SUSE authors can see this RFE and support gitfs syntax. saltstack need strong ansiblegate to resist 
encroachment from ansible camp.
-  Thanks for file.recurse/git.latest work around solution, I will look into this for now  if there is real solution.

**Comment by OrangeDog** [comment]
If `mygit` is in the path then include that too: `salt://mygit/playbooks/helloworld.yml`.

I don't know what SUSE has to do with it, but there is no such thing as "gitfs syntax".

**Comment by tjyang** [comment]
> If `mygit` is in the path then include that too: `salt://mygit/playbooks/helloworld.yml`.

```
# following text masked out private info
# I moved  playbooks dir under ansible dir.
[me@salt01 ~]$ sudo salt-run  fileserver.file_list |grep hellow
- mygit/ansible/playbooks/helloworld.yml
[me@salt01 ~]$ sudo salt salt01 ansible.playbooks  playbook=salt://mygit/ansible/playbooks/helloworld.yml
# output is same JSONDecodeError  error.
```

>I don't know what SUSE has to do with it, but there is no such thing as "gitfs syntax".

```
I watch an youtube video and learnt ansiblegate was created by SUSE's developer.
what I meant about "gitfs syntax" is the reference to file need to use gitfs syntax, not like local file syntax under /srv.
gitfs syntax example in formula .sls file: 
source: salt://mygit/sshd/files/issue.txt

```

**Comment by garethgreenaway** [comment]
Approved for a future feature addition but currently not a priority for the Salt core team.
