### ISSUE TITLE
[BUG] Pillar failed to render in the image with the master version

### ISSUE THREAD

**Issue by denis-khalturin-incountry** [saltstack/salt#61496]
**Description**
I just take a template-formula and run test-kitchen.
Test-kitchen fails with an error:
```
[CRITICAL] Pillar render error: Rendering Primary Top file failed, render error:
       The warning triggered on filename '/usr/local/lib/python3.6/dist-packages/salt/utils/templates.py', line number 103, is supposed to be shown until version 3005 is released. Current version is now 3005. Please remove the warning.
```

**Setup**
All files are available in the template-formula repository
  
**Steps to Reproduce the behavior**
```
git clone https://github.com/saltstack-formulas/template-formula.git
cd template-formula
kitchen test default-ubuntu-1804-master-py3
```

**Expected behavior**
Generated top.sls file for pillars

**Versions Report**
<details><summary>salt --versions-report</summary>

```
docker run saltimages/salt-master-py3:ubuntu-18.04 salt --versions-report
Salt Version:
          Salt: 3005+0na.eb8bd12

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.0.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.3
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.12.0
        pygit2: Not Installed
        Python: 3.6.9 (default, Dec  8 2021, 21:08:43)
  python-gnupg: Not Installed
        PyYAML: 6.0
         PyZMQ: 22.3.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: ubuntu 18.04 Bionic Beaver
        locale: ANSI_X3.4-1968
       machine: x86_64
       release: 5.10.76-linuxkit
        system: Linux
       version: Ubuntu 18.04 Bionic Beaver
```
</details>

**Additional context**
Also I don't see the released version 3005, but the docker image is already built with this version of salt.

**Comment by denis-khalturin-incountry** [comment]
<details><summary>More info</summary>
```
kitchen test default-ubuntu-1804-master-py3
-----> Starting Test Kitchen (v3.2.2)
-----> Cleaning up any prior instances of <default-ubuntu-1804-master-py3>
...
       [DEBUG   ] compile template: /tmp/kitchen/srv/pillar/top.sls
       [ERROR   ] Pillar rendering failed for minion f57e670ad000
       Traceback (most recent call last):
         File "/usr/local/lib/python3.6/dist-packages/salt/pillar/__init__.py", line 710, in get_tops
           _pillar_rend=True,
         File "/usr/local/lib/python3.6/dist-packages/salt/template.py", line 99, in compile_template
           ret = render(input_data, saltenv, sls, **render_kwargs)
         File "/usr/local/lib/python3.6/dist-packages/salt/loader/lazy.py", line 149, in __call__
           return self.loader.run(run_func, *args, **kwargs)
         File "/usr/local/lib/python3.6/dist-packages/salt/loader/lazy.py", line 1201, in run
           return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
         File "/usr/local/lib/python3.6/dist-packages/contextvars/__init__.py", line 38, in run
           return callable(*args, **kwargs)
         File "/usr/local/lib/python3.6/dist-packages/salt/loader/lazy.py", line 1216, in _run_as
           return _func_or_method(*args, **kwargs)
         File "/usr/local/lib/python3.6/dist-packages/salt/renderers/jinja.py", line 75, in render
           **kws
         File "/usr/local/lib/python3.6/dist-packages/salt/utils/templates.py", line 234, in render_tmpl
           sls_context = generate_sls_context(tmplpath, context["sls"])
         File "/usr/local/lib/python3.6/dist-packages/salt/utils/templates.py", line 210, in generate_sls_context
           return _generate_sls_context_legacy(tmplpath, sls)
         File "/usr/local/lib/python3.6/dist-packages/salt/utils/templates.py", line 103, in _generate_sls_context_legacy
           "There have been significant improvement to template variables. "
         File "/usr/local/lib/python3.6/dist-packages/salt/utils/versions.py", line 152, in warn_until
           salt_version=_version_.formatted_version,
       RuntimeError: The warning triggered on filename '/usr/local/lib/python3.6/dist-packages/salt/utils/templates.py', line number 103, is supposed to be shown until version 3005 is released. Current version is now 3005. Please remove the warning.
       [CRITICAL] Pillar render error: Rendering Primary Top file failed, render error:
       The warning triggered on filename '/usr/local/lib/python3.6/dist-packages/salt/utils/templates.py', line number 103, is supposed to be shown until version 3005 is released. Current version is now 3005. Please remove the warning.
...
       [DEBUG   ] LazyLoaded highstate.output
       local:
           Data failed to compile:
       ----------
           Pillar failed to render with the following messages:
       ----------
           Rendering Primary Top file failed, render error:
       The warning triggered on filename '/usr/local/lib/python3.6/dist-packages/salt/utils/templates.py', line number 103, is supposed to be shown until version 3005 is released. Current version is now 3005. Please remove the warning.
```
</details>

**Comment by garethgreenaway** [comment]
@denis-khalturin-incountry Thanks for the report.  Looking at the errors above it appears that the top.sls file for pillar is missing, I suspect this might be because the `template-formula` is an empty, boilerplate formula meant as a starting point and doesn't include everything needed to run the tests.  Have you filed an issue in the `template-formula` repo?

**Comment by garethgreenaway** [comment]
Closing this one out due to lack of activity. If this issue is not resolved please feel free to open a new issue or request that this issue be reopened.
