### ISSUE TITLE
[BUG] AIX mount.set_filesystems is erroring with too many values to unpack

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt#61509]
**Description**
mounting a file system with mount.set_filesystems as laid out in documentation https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.mount.html#salt.modules.mount.set_filesystems is failing.

**Setup**
Salt 30004 installed on AIX v7.1 TL5

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
Run the command 
```
salt-call --local -l trace mount.set_filesystems /dgm_test /dev/hd3 jsf2
```
results in 
```
[10682522] Failed to execute script salt-aix
Traceback (most recent call last):
  File "salt-aix", line 70, in <module>
  File "salt-aix", line 55, in redirect
  File "salt/scripts.py", line 432, in salt_call
  File "salt/cli/call.py", line 55, in run
  File "salt/cli/caller.py", line 111, in run
  File "salt/cli/caller.py", line 219, in call
  File "salt/loader/lazy.py", line 149, in __call__
  File "salt/loader/lazy.py", line 1201, in run
  File "salt/loader/lazy.py", line 1216, in _run_as
  File "/opt/saltstack/salt/run/salt/executors/direct_call.py", line 10, in execute
    return func(*args, **kwargs)
  File "salt/loader/lazy.py", line 149, in __call__
  File "salt/loader/lazy.py", line 1201, in run
  File "salt/loader/lazy.py", line 1216, in _run_as
  File "/opt/saltstack/salt/run/salt/modules/mount.py", line 1848, in set_filesystems
    entry_ip = _FileSystemsEntry.from_line(entry_args, kwargs)
  File "/opt/saltstack/salt/run/salt/modules/mount.py", line 560, in from_line
    return cls(**cls.dict_from_cmd_line(*args, **kwargs))
  File "/opt/saltstack/salt/run/salt/modules/mount.py", line 549, in dict_from_cmd_line
    for key, value in keys:
ValueError: too many values to unpack (expected 2)
```

**Expected behavior**
Should mount the file system

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
local:
    Salt Version:
              Salt: 3004
     
    Dependency Versions:
              cffi: 1.15.0
          cherrypy: Not Installed
          dateutil: Not Installed
         docker-py: Not Installed
             gitdb: Not Installed
         gitpython: Not Installed
            Jinja2: 3.0.2
           libgit2: Not Installed
          M2Crypto: Not Installed
              Mako: Not Installed
           msgpack: 1.0.2
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         pycparser: 2.20
          pycrypto: 3.11.0
      pycryptodome: 3.11.0
            pygit2: Not Installed
            Python: 3.7.11 (default, Sep  6 2021, 10:46:05)
      python-gnupg: Not Installed
            PyYAML: 6.0
             PyZMQ: 18.1.1
             smmap: Not Installed
           timelib: Not Installed
           Tornado: 4.5.3
               ZMQ: 4.3.3
     
    System Versions:
              dist: aix 1 
            locale: ISO8859-1
           machine: 00F9059E4C00
           release: 1
            system: AIX
           version: AIX 1 
```
</details>

**Additional context**

**Comment by dmurphy18** [comment]
This is another issue of Python 2'ism not caught with Python 3 update.

Python 2 line of code
```
for key, value in keys:
```
needs to be
```
for key, value in keys.items():
```

Need to check all AIX specific code paths for missed Py 2 -> Py 3 functionality
