### ISSUE TITLE
[BUG] pkgrepo.managed fails to configure ppa on Ubuntu 21.10

### ISSUE THREAD

**Issue by raczkow** [saltstack/salt#61600]
**Description**
On Ubuntu 20.10, 21.04 and 21.10, I can't setup my ppa repositories. Running high.state fails with error:
```
          ID: ppa keepassxc
    Function: pkgrepo.managed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 2171, in call
                  ret = self.states[cdata["full"]](
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2105, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/pkgrepo.py", line 412, in managed
                  pre = __salt__["pkg.get_repo"](repo=repo, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/modules/aptpkg.py", line 1721, in get_repo
                  repo = softwareproperties.ppa.PPAShortcutHandler(repo).expand(
              AttributeError: 'PPAShortcutHandler' object has no attribute 'expand'
     Started: 14:31:32.132847
    Duration: 982.162 ms
```
Looks, like changes in `python3-software-properties` break salt.

**Setup**
I'm using masterless salt configuration. Tested with Ubuntu's build of salt (3002.6) and latest official build for Ubuntu 20.04 (3004)

sls that fails to run:

```
ppa keepassxc:
  pkgrepo.managed:
    - ppa: phoerious/keepassxc
```
  
**Steps to Reproduce the behavior**
1. set sls to configure ppa with `pkgrepo.managed`
2. run high.state

**Expected behavior**
ppa is properly configured.

**Versions Report**
<details><summary>salt --versions-report</summary>

```
Salt Version:
          Salt: 3002.6
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: 4.4.4
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.0
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.9.7
        pygit2: Not Installed
        Python: 3.9.7 (default, Sep 10 2021, 14:59:43)
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 20.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: ubuntu 21.10 impish
        locale: utf-8
       machine: x86_64
       release: 5.13.0-21-lowlatency
        system: Linux
       version: Ubuntu 21.10 impish
```
```
Salt Version:
          Salt: 3004
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.0
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.9.7
        pygit2: Not Installed
        Python: 3.9.7 (default, Sep 10 2021, 14:59:43)
  python-gnupg: 0.4.6
        PyYAML: 5.3.1
         PyZMQ: 20.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: ubuntu 21.10 impish
        locale: utf-8
       machine: x86_64
       release: 5.13.0-28-generic
        system: Linux
       version: Ubuntu 21.10 impish

```
</details>

**Additional context**
Salt installed from official Ubuntu 21.10 packages. Problem also exists on latest 3004 provided from saltstack repositories.

**Comment by OrangeDog** [comment]
Duplicates #59065

**Comment by Ch3LL** [comment]
Closing as duplicate
