### ISSUE TITLE
cmd.script and cmd.run runas doesn't work

### ISSUE THREAD

**Issue by speedytom** [saltstack/salt#61644]
**Description**
<pre>
C:\salt>salt-call cmd.script runas=node salt://win/settings/mount-nfsserv2.bat > C:\out.txt

Exception ignored in: <function HANDLE.Close at 0x00000227DDE87B88>
Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt-3003.1-py3.7.egg\salt\platform\win.py", line 188, in Close
    CloseHandle(self.Detach())
  File "C:\salt\bin\lib\site-packages\salt-3003.1-py3.7.egg\salt\platform\win.py", line 633, in errcheck_bool
    raise ctypes.WinError(ctypes.get_last_error())
OSError: [WinError 6] The handle is invalid.
local:
    ----------
    pid:
        22516
    retcode:
        0
    stderr:
    stdout:
        
        c:\salt\var\cache\salt\minion\tmpcukxwpch>mount -o nolock \\nfsserv2.tok.ipp.cas.cz\cdb-2021\CDB_dataTest G: 
        G: is now successfully connected to \\nfsserv2.tok.ipp.cas.cz\cdb-2021\CDB_dataTest
        
        The command completed successfully.

C:\salt>net use
New connections will be remembered.

Status       Local     Remote                    Network

-------------------------------------------------------------------------------
                       \\TSCLIENT\media          Microsoft Terminal Services
The command completed successfully.

</pre>

**Setup**
<pre>
  C:\salt>salt-call.bat -V
Salt Version:
          Salt: 3003.1

Dependency Versions:
          cffi: 1.14.5
      cherrypy: 18.6.0
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.5
     gitpython: Not Installed
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: 1.1.4
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
  python-gnupg: 0.4.6
        PyYAML: 5.4.1
         PyZMQ: 18.0.1
         smmap: 3.0.4
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.1

System Versions:
          dist:
        locale: cp1252
       machine: AMD64
       release: 10
        system: Windows
       version: 10 10.0.17763 SP0
</pre>
**Additional context**
I tried these commands as workaround:
<pre>
C:\salt>salt-call cmd.run "cmd.exe /c mount -o nolock \\nfsserv2.tok.ipp.cas.cz\cdb-2021\CDB_dataTest F:\" runas=node password=linux stateful=True cwd=c:\Users\test
[ERROR   ] Command 'cmd.exe' failed with return code: 16
[ERROR   ] stdout: ERROR - Invalid command line argument
mount -o nolock \\nfsserv2.tok.ipp.cas.cz\cdb-2021\CDB_dataTest F: runas=node password=linux stateful=True cwd=c:\Users\test
[ERROR   ] retcode: 16
[ERROR   ] Command 'cmd.exe' failed with return code: 16
[ERROR   ] output: ERROR - Invalid command line argument
mount -o nolock \\nfsserv2.tok.ipp.cas.cz\cdb-2021\CDB_dataTest F: runas=node password=linux stateful=True cwd=c:\Users\test
local:
    ERROR - Invalid command line argument
    mount -o nolock \\nfsserv2.tok.ipp.cas.cz\cdb-2021\CDB_dataTest F: runas=node password=linux stateful=True cwd=c:\Users\test

C:\salt>salt-call cmd.run "mount -o nolock \\nfsserv2.tok.ipp.cas.cz\cdb-2021\CDB_dataTest F:\" runas=node cwd=c:\Users\test
[ERROR   ] Command 'mount' failed with return code: 16
[ERROR   ] stdout: ERROR - Invalid command line argument
mount -o nolock \\nfsserv2.tok.ipp.cas.cz\cdb-2021\CDB_dataTest F: runas=node cwd=c:\Users\test
[ERROR   ] retcode: 16
[ERROR   ] Command 'mount' failed with return code: 16
[ERROR   ] output: ERROR - Invalid command line argument
mount -o nolock \\nfsserv2.tok.ipp.cas.cz\cdb-2021\CDB_dataTest F: runas=node cwd=c:\Users\test
local:
    ERROR - Invalid command line argument
    mount -o nolock \\nfsserv2.tok.ipp.cas.cz\cdb-2021\CDB_dataTest F: runas=node cwd=c:\Users\test

</pre>

**Comment by speedytom** [comment]
Mount command provide NFS mount. 
There is manual run from cmd:
<pre>
C:\Users\test>mount \\nfsserv2.tok.ipp.cas.cz\cdb-2021\CDB_dataTest G:
G: is now successfully connected to \\nfsserv2.tok.ipp.cas.cz\cdb-2021\CDB_dataTest

The command completed successfully.

C:\Users\test>net use
New connections will be remembered.


Status       Local     Remote                    Network

-------------------------------------------------------------------------------
             G:        \\nfsserv2.tok.ipp.cas.cz\cdb-2021\CDB_dataTest
                                                NFS Network
                       \\TSCLIENT\media          Microsoft Terminal Services
The command completed successfully.
</pre>

**Comment by OrangeDog** [comment]
> **password** (_str_) --  
> Windows only. Required when specifying runas.

**Comment by speedytom** [comment]
It(node) isn't domain user. It is local user.

**Comment by speedytom** [comment]
I upgraded to the latest salt-minion.

<pre>
C:\Windows\system32>salt-call cmd.run "mount -o nolock \\nfsserv2.tok.ipp.cas.cz\cdb-2021\CDB_dataTest F:" runas=node password=linux stateful=True cwd=c:\Users\test
local:
    F: is now successfully connected to \\nfsserv2.tok.ipp.cas.cz\cdb-2021\CDB_dataTest

    The command completed successfully.

C:\Windows\system32>salt-call cmd.run "mount -o nolock \\nfsserv2.tok.ipp.cas.cz\cdb-2021\CDB_dataTest F:" runas=node cwd=c:\Users\test
Exception ignored in: <function HANDLE.Close at 0x000001DFD99C74C0>
Traceback (most recent call last):
  File "C:\Program Files\Salt Project\Salt\bin\lib\site-packages\salt-3004-py3.8.egg\salt\platform\win.py", line 185, in Close
    CloseHandle(self.Detach())
  File "C:\Program Files\Salt Project\Salt\bin\lib\site-packages\salt-3004-py3.8.egg\salt\platform\win.py", line 630, in errcheck_bool
    raise ctypes.WinError(ctypes.get_last_error())
OSError: [WinError 6] The handle is invalid.
local:
    F: is now successfully connected to \\nfsserv2.tok.ipp.cas.cz\cdb-2021\CDB_dataTest

    The command completed successfully.

testcase with PC name:
C:\Windows\system32>salt-call cmd.run "mount -o nolock \\nfsserv2.tok.ipp.cas.cz\cdb-2021\CDB_dataTest F:" runas=ww-smb-test\node password=linux stateful=True cwd=c:\Users\test
local:
    F: is now successfully connected to \\nfsserv2.tok.ipp.cas.cz\cdb-2021\CDB_dataTest

    The command completed successfully.

</pre>
I don't see NFS disk under user node. It was originally user test. I renamed to node by the way.

**Comment by speedytom** [comment]
I tried this workaround without success:
<pre>
C:\Windows\system32>salt-call cmd.run "New-PSDrive -name F -PSProvider FileSystem -Root \\nfsserv2.tok.ipp.cas.cz\cdb-2021\CDB_dataTest -Persist -scope Global" runas=node shell=powershell
Exception ignored in: <function HANDLE.Close at 0x0000016C528964C0>
Traceback (most recent call last):
  File "C:\Program Files\Salt Project\Salt\bin\lib\site-packages\salt-3004-py3.8.egg\salt\platform\win.py", line 185, in Close
    CloseHandle(self.Detach())
  File "C:\Program Files\Salt Project\Salt\bin\lib\site-packages\salt-3004-py3.8.egg\salt\platform\win.py", line 630, in errcheck_bool
    raise ctypes.WinError(ctypes.get_last_error())
OSError: [WinError 6] The handle is invalid.
local:

    Name           Used (GB)     Free (GB) Provider      Root                                               CurrentLocation
    ----           ---------     --------- --------      ----                                               ---------------
    F                  63.56       4264.54 FileSystem    \\nfsserv2.tok.ipp.cas.cz\cdb-20...
</pre>

I don't see NFS disk under user node.

**Comment by speedytom** [comment]
> You're also not calling `net use` as the `node` user, which may make a difference to what it returns.

Yes I do. I tested every time. I run salt-call as Administrator and `net use` as node user.

**Comment by speedytom** [comment]
![share-nfs-02](https://user-images.githubusercontent.com/43999405/154682163-81398f96-262e-4958-a9d2-5c9603be7b8c.jpg)

**Comment by speedytom** [comment]
![share-nfs-01](https://user-images.githubusercontent.com/43999405/154682211-12a5ed75-cd5f-452b-8229-0e8ca2d792f0.jpg)

**Comment by OrangeDog** [comment]
> I see NFS disk under user Administrator not user node.

Your screenshots show the opposite.

**Comment by speedytom** [comment]
> Your screenshots show the opposite.

You probably mean powershell test case. F Disk is still unavailable.

**Comment by twangboy** [comment]
Looks like the command works when you provide a password, but displays a stacktrace and fails without it. @dwoz ^^^

**Comment by twangboy** [comment]
This also may have something to do with the context of mounts in Windows. You're mounting as one user context with "runas" and then checking the mount in a different user context.
