### ISSUE TITLE
[BUG] svnfs fileserver backend do not work on salt 3004

### ISSUE THREAD

**Issue by y496237839** [saltstack/salt#61731]
**Description**
When the Salt master process starts and the svnfs backend is configured, it will crash trying to compute the hash of the repository url.

**Setup**
Configure the salt master to use the svnfs backend

```
fileserver_backend:
  - svnfs
#  - git
#  - roots
#
svnfs_remotes:
  - svn://192.168.214.152/svntest/
```

**Steps to Reproduce the behavior**
Start the salt master. It should crash right away.

```
● salt-master.service - The Salt Master Server
   Loaded: loaded (/usr/lib/systemd/system/salt-master.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since 日 2022-02-27 15:43:02 CST; 8s ago
     Docs: man:salt-master(1)
           file:///usr/share/doc/salt/html/contents.html
           https://docs.saltproject.io/en/latest/contents.html
  Process: 21874 ExecStart=/usr/bin/salt-master (code=exited, status=1/FAILURE)
 Main PID: 21874 (code=exited, status=1/FAILURE)

2月 27 15:43:02 k8smaster1 salt-master[21874]: File "/usr/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
2月 27 15:43:02 k8smaster1 salt-master[21874]: return callable(*args, **kwargs)
2月 27 15:43:02 k8smaster1 salt-master[21874]: File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1216, in _run_as
2月 27 15:43:02 k8smaster1 salt-master[21874]: return _func_or_method(*args, **kwargs)
2月 27 15:43:02 k8smaster1 salt-master[21874]: File "/usr/lib/python3.6/site-packages/salt/fileserver/svnfs.py", line 196, in init
2月 27 15:43:02 k8smaster1 salt-master[21874]: repo_hash = hash_type(repo_url).hexdigest()
2月 27 15:43:02 k8smaster1 salt-master[21874]: TypeError: Unicode-objects must be encoded before hashing
2月 27 15:43:02 k8smaster1 systemd[1]: salt-master.service: main process exited, code=exited, status=1/FAILURE
2月 27 15:43:02 k8smaster1 systemd[1]: Unit salt-master.service entered failed state.
2月 27 15:43:02 k8smaster1 systemd[1]: salt-master.service failed.
```

I tried to modify /usr/lib/python3.6/site-packages/salt/fileserver/svnfs.py
```
        hash_type = getattr(hashlib, __opts__.get("hash_type", "md6"))
        repo_hash = hash_type(repo_url.encode(encoding='utf-8')).hexdigest()
```
But a new error occurred
During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "/usr/bin/salt-master", line 11, in <module>
    load_entry_point('salt==3004', 'console_scripts', 'salt-master')()
  File "/usr/lib/python3.6/site-packages/salt/scripts.py", line 88, in salt_master
    master.start()
  File "/usr/lib/python3.6/site-packages/salt/cli/daemons.py", line 212, in start
    self.master.start()
  File "/usr/lib/python3.6/site-packages/salt/master.py", line 651, in start
    self._pre_flight()
  File "/usr/lib/python3.6/site-packages/salt/master.py", line 588, in _pre_flight
    fileserver.init()
  File "/usr/lib/python3.6/site-packages/salt/fileserver/__init__.py", line 540, in init
    self.servers[fstr]()
  File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1201, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
    return callable(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1216, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/fileserver/svnfs.py", line 207, in init
    except pysvn._pysvn.ClientError as exc:
AttributeError: module 'pysvn' has no attribute '_pysvn'
```

**Expected behavior**
It should not crash, and Successfully pulled svn repository

**Screenshots**

**Versions Report**

<details><summary>salt --versions-report</summary>

```
salt --versions-report
Salt Version:
          Salt: 3004
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4
 
System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 5.11.16-1.el7.elrepo.x86_64
        system: Linux
       version: CentOS Linux 7 Core
```

```
pip3 list |grep pysvn
pysvn (0.0.2) and 
pysvn(0.1.0)
```

</details>
**Additional context**

**Comment by y496237839** [comment]
I have installed 0.0.2 and 0.1.0, both of which have such problems.
@OrangeDog

**Comment by OrangeDog** [comment]
It seems that https://pysvn.sourceforge.io/ and https://pypi.org/project/pysvn/ are different projects.
I am guessing that the former is what you need.

**Comment by OrangeDog** [comment]
https://github.com/leafvmaple/pysvn/issues/1

**Comment by y496237839** [comment]
Thanks for your help.
I took your advice and reinstalled 1.9.5 via https://pysvn.sourceforge.io, however svnfs encountered a new problem. 
Execute  salt-run fileserver.file_list  backend=svn ，but no output anything. I found them in the cache

```
[root@aaa ~]# salt-run fileserver.file_list
[root@aaa ~]# salt-run fileserver.dir_list  backend=svnfs
[root@aaa ~]# salt-run fileserver.update backend=svnfs
True
[root@aaa ~]# salt-run fileserver.dir_list  backend=svnfs
[root@aaa ~]# salt-run fileserver.file_list backend=svnfs

[root@aaa ~]# ls /var/cache/salt/master/svnfs/
6e5db0d9974dc7d2fc6db8288ba131bb62661aa1ad19ededd978d50e77da2712  envs.p  remote_map.txt
[root@aaa ~]# ls /var/cache/salt/master/svnfs/6e5db0d9974dc7d2fc6db8288ba131bb62661aa1ad19ededd978d50e77da2712/
a.txt  ttt

```

Another problem is that I also encountered the same problem that SVN cannot specify the authentication password, and I didn't see any relevant content in the document.   #43948

**Comment by OrangeDog** [comment]
Have you tried all the stuff in this comment? https://github.com/saltstack/salt/issues/43948#issuecomment-336066116

**Comment by y496237839** [comment]
yes.
Use an auth by IP.  It cannot be verified. he does not provide a modified svnfs.py file
