### ISSUE TITLE
salt command data.items crashes

### ISSUE THREAD

**Issue by erwindon** [saltstack/salt#61812]
**Description**
Many operations in the `data` module crash with a stack trace.
Let's concentrate on `data.items` in this report.

**Setup**
Default setup of at least a master and a minion.
- [ ] on-prem machine
- [X] VM (Virtualbox)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
  
**Steps to Reproduce the behavior**
run command `salt '*' data.items`

See stack trace in `/var/log/salt/minion`:
```
2022-03-06 11:08:08,707 [salt.utils.process:1039][ERROR   ][71739] An un-handled exception from the multiprocessing process 'ProcessPayload' was caught: 
Traceback (most recent call last): 
  File "/usr/lib/python3/dist-packages/salt/utils/process.py", line 1034, in wrapped_run_func 
    return run_func() 
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run 
    self._target(*self._args, **self._kwargs) 
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 1810, in _target 
    run_func(minion_instance, opts, data) 
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 1804, in run_func 
    return Minion._thread_return(minion_instance, opts, data) 
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 2027, in _thread_return 
    minion_instance._return_pub( 
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 2231, in _return_pub 
    ret_val = self._send_req_sync(load, timeout=timeout) 
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 1595, in _send_req_sync 
    return channel.send( 
  File "/usr/lib/python3/dist-packages/salt/utils/asynchronous.py", line 125, in wrap 
    raise exc_info[1].with_traceback(exc_info[2]) 
  File "/usr/lib/python3/dist-packages/salt/utils/asynchronous.py", line 131, in _target 
    result = io_loop.run_sync(lambda: getattr(self.obj, key)(*args, **kwargs)) 
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/ioloop.py", line 459, in run_sync 
    return future_cell[0].result() 
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/concurrent.py", line 249, in result 
    raise_exc_info(self._exc_info) 
  File "<string>", line 4, in raise_exc_info 
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/gen.py", line 1064, in run 
    yielded = self.gen.throw(*exc_info) 
  File "/usr/lib/python3/dist-packages/salt/transport/zeromq.py", line 319, in send 
    ret = yield self._crypted_transfer( 
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/gen.py", line 1056, in run 
    value = future.result() 
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/concurrent.py", line 249, in result 
    raise_exc_info(self._exc_info) 
  File "<string>", line 4, in raise_exc_info 
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/gen.py", line 1064, in run 
    yielded = self.gen.throw(*exc_info) 
  File "/usr/lib/python3/dist-packages/salt/transport/zeromq.py", line 287, in _crypted_transfer 
    ret = yield _do_transfer() 
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/gen.py", line 1056, in run 
    value = future.result() 
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/concurrent.py", line 249, in result 
    raise_exc_info(self._exc_info) 
  File "<string>", line 4, in raise_exc_info 
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/gen.py", line 309, in wrapper 
    yielded = next(result) 
  File "/usr/lib/python3/dist-packages/salt/transport/zeromq.py", line 268, in _do_transfer 
    self._package_load(self.auth.crypticle.dumps(load)), 
  File "/usr/lib/python3/dist-packages/salt/crypt.py", line 1543, in dumps 
    return self.encrypt(self.PICKLE_PAD + salt.payload.dumps(obj)) 
  File "/usr/lib/python3/dist-packages/salt/payload.py", line 167, in dumps 
    return salt.utils.msgpack.packb( 
  File "/usr/lib/python3/dist-packages/salt/utils/msgpack.py", line 133, in packb 
    return msgpack.packb(o, **_sanitize_msgpack_kwargs(kwargs)) 
  File "/usr/lib/python3/dist-packages/msgpack/__init__.py", line 35, in packb 
    return Packer(**kwargs).pack(o) 
  File "msgpack/_packer.pyx", line 286, in msgpack._cmsgpack.Packer.pack 
  File "msgpack/_packer.pyx", line 292, in msgpack._cmsgpack.Packer.pack 
  File "msgpack/_packer.pyx", line 289, in msgpack._cmsgpack.Packer.pack 
  File "msgpack/_packer.pyx", line 225, in msgpack._cmsgpack.Packer._pack 
  File "msgpack/_packer.pyx", line 283, in msgpack._cmsgpack.Packer._pack
TypeError: can not serialize 'dict_items' object
```

**Expected behavior**
no error.
some output describing the data items.

**Versions Report**
Originally observed when using 3002.6.
Verified in 3004 that the problem still exists.

<details><summary>salt --versions-report</summary>

```yaml
Salt Version:
          Salt: 3004
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.0
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.9.7
        pygit2: Not Installed
        Python: 3.9.2 (default, Feb 28 2021, 17:03:44)
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 20.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 11 bullseye
        locale: utf-8
       machine: x86_64
       release: 5.10.0-11-amd64
        system: Linux
       version: Debian GNU/Linux 11 bullseye
```
</details>

**Comment by OrangeDog** [comment]
Are you sure that's the full reproduction? You haven't added something to the data store first?

**Comment by erwindon** [comment]
I never used the data-store before, and I'm fairly sure that the above happened (also) with this command as the first command.
It's easy to replay for me since the vm+saltmaster+saltminion have a scripted installation.
I'll replay this and let you know...

**Comment by OrangeDog** [comment]
I tried to reproduce and got #61818 instead. That's with an older version of msgpack though.

**Comment by erwindon** [comment]
I repeated this with a fresh vm+saltmaster+saltminion installation, and had exactly the same stack trace in the logfile as in the original ticket description.

But I did forgot to mention that the `salt` command itself ended with:
```
minionname:
    Minion did not return. [No response]
    The minions may not have all finished running and any remaining minions will return upon completion. To look up the return data for this job later, run the following command: 
    salt-run jobs.lookup_jid 20220321223516559837
```

**Comment by OrangeDog** [comment]
I see that now. It's the same thing causing two different problems depending on how you call it.
