### ISSUE TITLE
[DOCS] document Module.run usage with pyobjects renderer

### ISSUE THREAD

**Issue by nicholasmhughes** [saltstack/salt#61828]
**Description**
The new `module.run` format which will be enforced on the release of 3005 throws a little bit of a monkey wrench in the pyobjects renderer. The new format expects the name of the module to run as one of the keyword arguments, but it can't be listed explicitly in the pyobjects format because of the dot (`.`) in the name.

Attempting to run something like this:

```
#!pyobjects

user = {"name": "susan"}
Module.run("pyobject_shadow", shadow.lock_password=user)
```

will fail with an error like this:

```
local:
    Data failed to compile:
----------
    Rendering SLS py_shadow failed, render error: keyword can't be an expression (<string>, line 4)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/state.py", line 4034, in render_state
    context=context,
  File "/usr/lib/python3/dist-packages/salt/template.py", line 99, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1201, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1216, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/renderers/pyobjects.py", line 495, in render
    exec(final_template, _globals)
  File "<string>", line 4
SyntaxError: keyword can't be an expression
```

However, creating a kwargs dictionary seems to work just fine:

```
#!pyobjects

lock_kwargs = {"shadow.lock_password": {"name": "susan"}}
Module.run("pyobject_shadow", **lock_kwargs)
```

**Suggested Fix**
A brief section with code examples such as above should point folks in the right direction.

**Location or format of documentation**
Might be a good fit in either or both of the [pyobjects docs](https://docs.saltproject.io/en/latest/ref/renderers/all/salt.renderers.pyobjects.html) and [module.run docs](https://docs.saltproject.io/en/latest/ref/states/all/salt.states.module.html).

**Additional context**
This probably won't affect many people as I suspect the intersection of people using both pyobjects and `module.run` is small.

**Comment by whytewolf** [comment]
for clarification. per https://github.com/saltstack/salt/issues/58763 neither syntax of `module.run` is going away. we are instead going to do a detect and run style and make use_superseded a noop

**Comment by nicholasmhughes** [comment]
Oh nice! Thanks for letting me know @whytewolf
