### ISSUE TITLE
[BUG] UnicodeDecodeError when running under LANG=C and config file contains UTF-8 characters

### ISSUE THREAD

**Issue by ixs** [saltstack/salt#61947]
**Description**
When `salt-call` is executed through a script, I see the following error:

```python traceback
[ERROR   ] 'ascii' codec can't decode byte 0xe2 in position 8516: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/parsers.py", line 196, in parse_args
    process_option_func()
  File "/usr/lib/python3.6/site-packages/salt/utils/parsers.py", line 560, in process_config_dir
    self.config.update(self.setup_config())
  File "/usr/lib/python3.6/site-packages/salt/utils/parsers.py", line 3040, in setup_config
    self.get_config_file_path(), cache_minion_id=True
  File "/usr/lib/python3.6/site-packages/salt/config/__init__.py", line 2207, in minion_config
    exit_on_config_errors=not ignore_config_errors,
  File "/usr/lib/python3.6/site-packages/salt/config/__init__.py", line 2082, in include_config
    opts = _read_conf_file(fn_)
  File "/usr/lib/python3.6/site-packages/salt/config/__init__.py", line 1921, in _read_conf_file
    conf_opts = salt.utils.yaml.safe_load(conf_file) or {}
  File "/usr/lib/python3.6/site-packages/salt/utils/yamlloader.py", line 178, in safe_load
    return yaml.load(stream, Loader=Loader)
  File "/usr/lib64/python3.6/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/usr/lib64/python3.6/site-packages/yaml/constructor.py", line 35, in get_single_data
    node = self.get_single_node()
  File "_yaml.pyx", line 707, in _yaml.CParser.get_single_node (ext/_yaml.c:8040)
  File "_yaml.pyx", line 725, in _yaml.CParser._compose_document (ext/_yaml.c:8295)
  File "_yaml.pyx", line 776, in _yaml.CParser._compose_node (ext/_yaml.c:8983)
  File "_yaml.pyx", line 892, in _yaml.CParser._compose_mapping_node (ext/_yaml.c:10544)
  File "_yaml.pyx", line 903, in _yaml.CParser._parse_next_event (ext/_yaml.c:10698)
  File "_yaml.pyx", line 912, in _yaml.input_handler (ext/_yaml.c:10810)
  File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 8516: ordinal not in range(128
```

The same command works fine when run from the command line.

After a bit debugging, the culprit is an UTF-8 character in the config file and the fact that `salt-call` is being executed with the environment set to `LANG=C` under the script while it is being executed with `LANG=en_US.UTF-8` when run from the command-line.

**Setup**
`/etc/salt/minion` contains the following configuration for the highstate returner:
```yaml
highstate:
  report_changes: true
  report_delivery: smtp
  report_everything: true
  report_failures: true
  report_format: html
  smtp_failure_subject: Saltstack ❌ failure minion {id} on host {host}
  smtp_recipients: server@example.net
  smtp_sender: salt-minon <root@example.net>
  smtp_server: smtp.example.net
  smtp_success_subject: Saltstack ✅ success minion {id} on host {host}
```

The ❌ and ✅ emojiis are `<U+274C>` and `<U+2705>` respectively and trigger the problem.

  
**Steps to Reproduce the behavior**
Drop the config snippet from above into /etc/salt/minion and execute `LANG=C salt-call`.

**Versions Report**
```yaml
Salt Version:
          Salt: 3004.1

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4

System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-1160.59.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core
```
</details>

**Additional context**
The issue salt is experiencing here is described at https://github.com/yaml/pyyaml/issues/123 and suggests that the file needs to be opened with a clear encoding set for yaml to correctly decode things.

And indeed, a quick one-liner here fixes the problem:
```diff
--- /usr/lib/python3.6/site-packages/salt/config/__init__.py.orig	2022-04-13 13:00:36.913978197 +0200
+++ /usr/lib/python3.6/site-packages/salt/config/__init__.py	2022-04-13 13:03:17.091310353 +0200
@@ -1916,7 +1916,7 @@
     """
     log.debug("Reading configuration from %s", path)
     append_file_suffix_YAMLError = False
-    with salt.utils.files.fopen(path, "r") as conf_file:
+    with salt.utils.files.fopen(path, "r", encoding='utf8') as conf_file:
         try:
             conf_opts = salt.utils.yaml.safe_load(conf_file) or {}
         except salt.utils.yaml.YAMLError as err:
```

**Comment by OrangeDog** [comment]
That doesn't sound like a bug. Unless the YAML standard specifies that it must only use UTF-8?

**Comment by ixs** [comment]
So what is the right solution then?

Because right now what we have is the following:

Whether salt will work or not depends on how it's being called. And that's kinda surprising, especially as salt supports UTF-8 (mostly) everywhere else.

**Comment by OrangeDog** [comment]
https://yaml.org/spec/1.2-old/spec.html#id2771184

Yes, YAML must use a Unicode encoding, but not necessarily UTF-8. The reader should detect the encoding via BOM.

Opening using the current locale is therefore incorrect. As a workaround, ensure you only call Salt in a Unicode locale.

**Comment by dwoz** [comment]
Not reproducible on 3006.x / 3007.x / 3008.x / master.

Verified with the config from the report under `PYTHONUTF8=0 LC_ALL=C LANG=C salt-call --local test.ping` — parses fine.

Root cause was that in 3004 `__salt_system_encoding__` was derived from `sys.stdin.encoding` / `locale.getdefaultlocale()`, which resolved to `ascii` under `LANG=C` on Python 3.6. That value flowed into `salt.utils.files.fopen`'s implicit encoding, and libyaml's CParser then hit ASCII on the U+274C / U+2705 bytes.

Since c3fbc96 `__salt_system_encoding__` is unconditionally `sys.getdefaultencoding()` (always `utf-8` on Python 3), and `_read_conf_file` still opens via `salt.utils.files.fopen`, so the config file is decoded as UTF-8 regardless of locale.

Closing.
