### ISSUE TITLE
[BUG] test_deferred_stream_handler: test_sync_with_handlers and test_deferred_write_on_flush fail

### ISSUE THREAD

**Issue by bdrung** [saltstack/salt#61957]
**Description**

```python
$ python3 -m pytest -ra tests/pytests/unit/_logging/handlers/test_deferred_stream_handler.py
=================================== FAILURES ===================================
___________________________ test_sync_with_handlers ____________________________

    def test_sync_with_handlers():
        proc = multiprocessing.Process(target=_sync_with_handlers_proc_target)
        proc.start()
        proc.join()
>       assert proc.exitcode == 0
E       AssertionError: assert 1 == 0
E        +  where 1 = <Process name='Process-1' pid=274388 parent=274375 stopped exitcode=1>.exitcode

tests/pytests/unit/_logging/handlers/test_deferred_stream_handler.py:69: AssertionError
----------------------------- Captured stderr call -----------------------------
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "tests/pytests/unit/_logging/handlers/test_deferred_stream_handler.py", line 40, in _sync_with_handlers_proc_target
    assert stds.stderr == "Foo\nBar\n"
AssertionError: assert '' == 'Foo\nBar\n'
  - Foo
  - Bar
_________________________ test_deferred_write_on_flush _________________________

    def test_deferred_write_on_flush():
        proc = multiprocessing.Process(target=_deferred_write_on_flush_proc_target)
        proc.start()
        proc.join()
>       assert proc.exitcode == 0
E       AssertionError: assert 1 == 0
E        +  where 1 = <Process name='Process-2' pid=274389 parent=274375 stopped exitcode=1>.exitcode

tests/pytests/unit/_logging/handlers/test_deferred_stream_handler.py:76: AssertionError
----------------------------- Captured stderr call -----------------------------
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "tests/pytests/unit/_logging/handlers/test_deferred_stream_handler.py", line 62, in _deferred_write_on_flush_proc_target
    assert stds.stderr == "Foo\nBar\n"
AssertionError: assert '' == 'Foo\nBar\n'
  - Foo
  - Bar
=========================== short test summary info ============================
FAILED tests/pytests/unit/_logging/handlers/test_deferred_stream_handler.py::test_sync_with_handlers
FAILED tests/pytests/unit/_logging/handlers/test_deferred_stream_handler.py::test_deferred_write_on_flush
========================= 2 failed, 2 passed in 1.03s ==========================
```

**Setup**

git master branch on Ubuntu 22.04 (jammy) desktop installation.

**Comment by MKLeb** [comment]
Hey @bdrung, I've been working with Ubuntu 22.04 recently and haven't been able to replicate this failure. Are there any more details of your setup that may help us replicate this a little better?

**Comment by frebib** [comment]
I'm also hitting this test failure on Debian Bullseye with these dependencies installed
<details>
<summary>Expand me..</summary>
python3,
python3-apt,
python3-attr (>= 19.1),
python3-augeas,
python3-boto,
python3-boto3,
python3-cheetah,
python3-cherrypy3,
python3-consul,
python3-croniter,
python3-dateutil,
python3-distro,
python3-dnspython,
python3-docker,
python3-elasticsearch,
python3-etcd,
python3-genshi,
python3-git,
python3-hglib,
python3-isodate,
python3-jinja2,
python3-jsonschema,
python3-junos-eznc,
python3-keyring,
python3-kubernetes,
python3-ldap,
python3-libcloud (>= 0.14.1),
python3-mako,
python3-mock,
python3-msgpack,
python3-mysqldb,
python3-openssl,
python3-passlib,
python3-pip,
python3-psutil,
python3-pycryptodome,
python3-pygit2,
python3-pyinotify,
python3-pyroute2,
python3-pytest (>= 7.0.1),
python3-pytest-helpers-namespace (>= 2019.1.8),
python3-pytest-httpserver,
python3-pytest-skip-markers (>= 1.1.0-3~),
python3-pytest-subtests,
python3-pytest-tempdir (>= 2019.10.12),
python3-pyvmomi,
python3-requests (>= 1.0.0),
python3-saltfactories (>= 1.0.0rc17),
python3-setuptools,
python3-toml,
python3-twilio,
python3-yaml,
python3-zmq (>= 13.1.0),
sphinx-common,
</details>

Additionally the `test_sync_with_handlers` test is also failing
```
tests/pytests/unit/_logging/handlers/test_deferred_stream_handler.py:64 (test_sync_with_handlers)
1 != 0
def test_sync_with_handlers():
        proc = multiprocessing.Process(target=_sync_with_handlers_proc_target)
        proc.start()
        proc.join()
>       assert proc.exitcode == 0
E       AssertionError: assert 1 == 0
E        +  where 1 = <Process name='Process-44' pid=20805 parent=13 stopped exitcode=1>.exitcode
/cfsetup_build/salt/tests/pytests/unit/_logging/handlers/test_deferred_stream_handler.py:69: AssertionError
------- Stderr: -------
Process Process-44:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/cfsetup_build/salt/tests/pytests/unit/_logging/handlers/test_deferred_stream_handler.py", line 40, in _sync_with_handlers_proc_target
    assert stds.stderr == "Foo\nBar\n"
AssertionError: assert '' == 'Foo\nBar\n'
  - Foo
  - Bar
```

**Comment by frebib** [comment]
Judging by the fact that `Foo` and `Bar` are showing up in the output below the `AssertionError` I'd guess that `CaptureOutput()` isn't working as it should

**Comment by tj90241** [comment]
For some reason, the root logger does not have a log level of `DEBUG` set, so it filters out the messages that the handler produces.

Simply changing:
```
--- a/tests/pytests/unit/_logging/handlers/test_deferred_stream_handler.py
+++ b/tests/pytests/unit/_logging/handlers/test_deferred_stream_handler.py
@@ -14,6 +14,7 @@ from tests.support.helpers import CaptureOutput, dedent
 from tests.support.runtests import RUNTIME_VARS
 
 log = logging.getLogger(__name__)
+log.setLevel(logging.DEBUG)
 
 
 def _sync_with_handlers_proc_target():
```

Allows the test to pass. Though, I'm not sure how this was working before in this case, as AFAIK this is not a new behavior change in Python.

**Comment by tj90241** [comment]
This seems more like something the Debian packaging needs to account for than anything else.

I was able to get the tests to pass by adding `--log-level=DEBUG` to the pytest line in `debian/rules`.

**Comment by tj90241** [comment]
(the other option being adding a `log_level = DEBUG` to `pytest.ini` (though it makes me wonder how the onedir/upstream Salt tests as passing without this?)

**Comment by dwoz** [comment]
Fixed by 9cc0635ed38 (Feb 2024). Present on 3006.x, 3007.x, 3008.x, master; all 4 tests in `tests/pytests/unit/_logging/handlers/test_deferred_stream_handler.py` pass locally on each branch. Closing.
