### ISSUE TITLE
[BUG] State.single now reports '__pub_serial is invalid keyword for grains.present

### ISSUE THREAD

**Issue by doesitblend** [saltstack/salt#61976]
**Description**
I have an orchestration that I've been running to configure some grains on my minions. This orchestration was working in 3004. I upgraded my Salt master to 3004.1 ahead of my minions and started getting the error below:

<details><summary>Traceback message from minion</summary>

```
2022-04-22 10:50:17,649 [salt.minion      :1972][ERROR   ][7284] Problem executing 'state.single': '__pub_serial' is an invalid keyword argument for 'grains.present'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/minion.py", line 1912, in _thread_return
    function_name, function_args, executors, opts, data
  File "/usr/lib/python3.6/site-packages/salt/minion.py", line 1868, in _execute_job_function
    return_data = self.executors[fname](opts, data, func, args, kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1201, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
    return callable(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1216, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/executors/direct_call.py", line 10, in execute
    return func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1201, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
    return callable(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1216, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/modules/state.py", line 2185, in single
    kwargs
  File "/usr/lib/python3.6/site-packages/salt/utils/decorators/state.py", line 45, in _func
    result = func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/state.py", line 2108, in call
    expected_extra_kws=STATE_INTERNAL_KEYWORDS,
  File "/usr/lib/python3.6/site-packages/salt/utils/args.py", line 522, in format_call
    raise SaltInvocationError(msg)
salt.exceptions.SaltInvocationError: '__pub_serial' is an invalid keyword argument for 'grains.present'

```

</details>

I have confirmed the following about this issue:
* This issue does not happen in 3004 master using the same orchestration state
* Occurs when 3004.1 master is talking to 3004 minion and 3004.1 minion
* Running the state.single directly from the minion works fine on both 3004 and 3004.1
  - Confirmed that the grains file was updated and reports grains as expected

**Setup**
Add the following to your file roots:

```
set_grain:
  salt.function:
    - name: state.single
    - tgt:
        - c1-minion1
        - c1-minion2
    - tgt_type: list
    - kwarg:
        fun: grains.present
        name: last_snapshot
        value: today
        force: True
```

 
**Steps to Reproduce the behavior**
Enabled trace logging on your Salt minion and run the orchestration above

**Expected behavior**
The state.single function should execute successfully. 

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3004.1

Dependency Versions:
          cffi: 1.15.0
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.14.1
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4

Salt Extensions:
        SSEAPE: 8.6.1.4

System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-1160.49.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core
```
</details>

**Additional context**

**Comment by doesitblend** [comment]
Confirmed that `salt.state` works fine.

**Comment by OrangeDog** [comment]
3004.1 has a breaking change in the master-minion communications. You'll have to have everything on the same version.

**Comment by garethgreenaway** [comment]
@doesitblend I'm not seeing this with Salt Master 3005.1 and Salt Minions 3004.2.  Is this still an issue?

**Comment by OrangeDog** [comment]
@frogunder yes, that's exactly the problem. 3004.1 had a breaking change when it wasn't supposed to.

> a 3004 minion to a 3004.1 master is supported this is a valid issue and we need to address it.

**Comment by whytewolf** [comment]
as we are no longer supporting 3004. which had several CVE issues at this point. and all newer versions of even the 3004.x line worked. lets go ahead and close this issue. if a user does come up with this issue. upgrade the minion is an acceptable answer at this time.
