### ISSUE TITLE
Salt-Minion Exception Getting Pillar After Key is Accepted [BUG]

### ISSUE THREAD

**Issue by Scottsie** [saltstack/salt#61977]
**Description**
While testing a deployment scenario I run into an error with the minion after the key is accepted where it reports being unable to successfully connect to the salt master followed closely by an exception getting pillar data. 
Any troubleshooting or assistance on narrowing it down would be appreciated. But based on the errors I am wondering if this is a bug but I didn't find a specific matching report or article.

**Setup**
Device is deployed with an ISO build (kickstarted) which includes a salt-minion pre-configured to report to a standalone salt-master. 
The minion is required to use tcp transport and the vendor is only allowing minion version 3002.5 currently.
The device boots up after initial installation and waits for an LTE connection (SIM provider). Once online the salt-minion checks in triggering an auth event.
A reactor scripts accepts the key based on a lookup of 'known devices' in a list (yaml now but mysql later).
The goal is for additional reactor states to trigger at this point.

Please be as specific as possible and give set-up details.
- [X] on-prem machine (device is physical 'whitelabel' box with LTE connection by SIM)
- [X] VM (VMWare based salt-master)

**Steps to Reproduce the behavior**
1. Salt key deleted from master
2. Clean install from ISO with minion config populated with salt-master IP

**Expected behavior**
1. Minion should initiate communication to the master once online.
2. Minion sends a salt/auth and reactor script on looks up minion_id and accepts 'known' key.
3. Minion salt/minion/*/start triggers additional steps.

**Versions Report**
<details><summary>salt-master versions report</summary>
<p>

```
Salt Version:
          Salt: 3004.1

Dependency Versions:
          cffi: 1.11.5
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.14
      pycrypto: Not Installed
  pycryptodome: 3.10.1
        pygit2: Not Installed
        Python: 3.6.8 (default, Mar 25 2022, 11:15:52)
  python-gnupg: Not Installed
        PyYAML: 3.12
         PyZMQ: 19.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: centos 8 n/a
        locale: UTF-8
       machine: x86_64
       release: 4.18.0-373.el8.x86_64
        system: Linux
       version: CentOS Stream 8 n/a
```

</p>
</details>

<details><summary>salt-master config</summary>
<p>

`transport: tcp`

</p>
</details>

<details><summary>salt-minion versions report</summary>
<p>

```
Salt Version:
          Salt: 3002.5

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Jan 22 2021, 10:31:57)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4

System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 4.18.0-305.19.1.el8_4.x86_64
        system: Linux
       version: CentOS Linux 7 Core
```

</p>
</details>

<details><summary>salt-minion config</summary>
<p>

```
auth_safemode: true
autoload_dynamic_modules: false
enable_legacy_startup_events: false
include: /vendorpathto/_beacons/*.conf
master: <salt master ip>
master_alive_interval: 30
master_tries: -1
ping_interval: 0
random_reauth_delay: 120
recon_default: 5000
recon_max: 30000
recon_randomize: true
tcp_authentication_retries: -1
tcp_keepalive_cnt: 3
tcp_keepalive_idle: 5
tcp_keepalive_intvl: 10
transport: tcp
```

</p>
</details>

<details><summary>master debug log</summary>
<p>

```
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/reactor.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/reactor.conf
[DEBUG   ] Using importlib_metadata to load entry points
[DEBUG   ] Override  __utils__: <module 'salt.loaded.int.grains.zfs' from '/usr/lib/python3.6/site-packages/salt/grains/zfs.py'>
[DEBUG   ] /etc/resolv.conf: The domain and search keywords are mutually exclusive.
[DEBUG   ] Elapsed time getting FQDNs: 0.11922264099121094 seconds
[DEBUG   ] LazyLoaded zfs.is_supported
[DEBUG   ] Using importlib_metadata to load entry points
[DEBUG   ] LazyLoaded local_cache.clean_old_jobs
[DEBUG   ] LazyLoaded localfs.list_tokens
[DEBUG   ] This salt-master instance has accepted 0 minion keys.
[INFO    ] Authentication request from 9133210011
[INFO    ] New public key for 9133210011 placed in pending
[DEBUG   ] Sending event: tag = salt/auth; data = {'result': True, 'act': 'pend', 'id': '9133210011', 'pub': '-----BEGIN PUBLIC KEY-----\n<snipped for brevity>\n-----END PUBLIC KEY-----\n', '_stamp': '2022-04-22T22:56:57.361929'}
[DEBUG   ] Gathering reactors for tag salt/auth
[DEBUG   ] Compiling reactions for tag salt/auth
[DEBUG   ] compile template: /srv/reactor/redirector_auth.py
[DEBUG   ] LazyLoaded py.render
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/reactor.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/reactor.conf
[DEBUG   ] Using importlib_metadata to load entry points
[DEBUG   ] LazyLoaded key.list
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Guessing ID. The id can be explicitly set in /etc/salt/minion
[DEBUG   ] Found minion id from generate_minion_id(): <saltmasterID>
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/reactor.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/reactor.conf
[DEBUG   ] Override  __utils__: <module 'salt.loaded.int.grains.zfs' from '/usr/lib/python3.6/site-packages/salt/grains/zfs.py'>
[DEBUG   ] /etc/resolv.conf: The domain and search keywords are mutually exclusive.
[DEBUG   ] Elapsed time getting FQDNs: 0.11848282814025879 seconds
[DEBUG   ] LazyLoaded zfs.is_supported
[DEBUG   ] Using importlib_metadata to load entry points
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event: tag = salt/wheel/20220422225658137332/new; data = {'fun': 'wheel.key.list', 'jid': '20220422225658137332', 'user': 'UNKNOWN', 'fun_args': ['accepted'], '_stamp': '2022-04-22T22:56:58.143501'}
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] LazyLoaded local_cache.prep_jid
[DEBUG   ] Sending event: tag = salt/wheel/20220422225658137332/ret; data = {'fun': 'wheel.key.list', 'jid': '20220422225658137332', 'user': 'UNKNOWN', 'fun_args': ['accepted'], '_stamp': '2022-04-22T22:56:58.148313', 'return': {'minions': []}, 'success': True}
[DEBUG   ] LazyLoaded nested.output
minions:
[INFO    ] Runner completed: 20220422225658137332
[DEBUG   ] Closing IPCMessageClient instance
[WARNING ] found minion 9133210011 in the maps. Accepting minion key.
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event: tag = salt/wheel/20220422225658153907/new; data = {'fun': 'wheel.key.accept_dict', 'jid': '20220422225658153907', 'user': 'UNKNOWN', 'fun_args': [{'minions_pre': ['9133210011']}], '_stamp': '2022-04-22T22:56:58.156634'}
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
[DEBUG   ] Sending event: tag = salt/key; data = {'result': True, 'act': 'accept', 'id': '9133210011', '_stamp': '2022-04-22T22:56:58.160426'}
[DEBUG   ] Closing IPCMessageClient instance
[DEBUG   ] Sending event: tag = salt/wheel/20220422225658153907/ret; data = {'fun': 'wheel.key.accept_dict', 'jid': '20220422225658153907', 'user': 'UNKNOWN', 'fun_args': [{'minions_pre': ['9133210011']}], '_stamp': '2022-04-22T22:56:58.162942', 'return': {'minions': ['9133210011']}, 'success': True}
[DEBUG   ] LazyLoaded nested.output
minions:
    - 9133210011
[INFO    ] Runner completed: 20220422225658153907
[DEBUG   ] Closing IPCMessageClient instance
[PROFILE ] Time (in seconds) to render '/srv/reactor/redirector_auth.py' using 'py' renderer: 0.7997550964355469
[DEBUG   ] Gathering reactors for tag salt/wheel/20220422225658137332/new
[DEBUG   ] Gathering reactors for tag salt/wheel/20220422225658137332/ret
[DEBUG   ] Gathering reactors for tag salt/wheel/20220422225658153907/new
[DEBUG   ] Gathering reactors for tag salt/key
[DEBUG   ] Gathering reactors for tag salt/wheel/20220422225658153907/ret
[INFO    ] Authentication request from 9133210011
[INFO    ] Authentication accepted from 9133210011
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
[DEBUG   ] Sending event: tag = salt/auth; data = {'result': True, 'act': 'accept', 'id': '9133210011', 'pub': '-----BEGIN PUBLIC KEY-----\n<snipped for brevity>\n-----END PUBLIC KEY-----\n', '_stamp': '2022-04-22T22:57:07.501464'}
[DEBUG   ] Gathering reactors for tag salt/auth
[DEBUG   ] Compiling reactions for tag salt/auth
[DEBUG   ] compile template: /srv/reactor/redirector_auth.py
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/reactor.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/reactor.conf
[DEBUG   ] Using importlib_metadata to load entry points
[DEBUG   ] LazyLoaded key.list
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Guessing ID. The id can be explicitly set in /etc/salt/minion
[DEBUG   ] Found minion id from generate_minion_id(): <saltmasterid>
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/reactor.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/reactor.conf
[DEBUG   ] Override  __utils__: <module 'salt.loaded.int.grains.zfs' from '/usr/lib/python3.6/site-packages/salt/grains/zfs.py'>
[DEBUG   ] /etc/resolv.conf: The domain and search keywords are mutually exclusive.
[DEBUG   ] Elapsed time getting FQDNs: 0.11870932579040527 seconds
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
[DEBUG   ] LazyLoaded zfs.is_supported
[DEBUG   ] Using importlib_metadata to load entry points
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event: tag = salt/wheel/20220422225708344820/new; data = {'fun': 'wheel.key.list', 'jid': '20220422225708344820', 'user': 'UNKNOWN', 'fun_args': ['accepted'], '_stamp': '2022-04-22T22:57:08.350381'}
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] LazyLoaded local_cache.prep_jid
[DEBUG   ] Sending event: tag = salt/wheel/20220422225708344820/ret; data = {'fun': 'wheel.key.list', 'jid': '20220422225708344820', 'user': 'UNKNOWN', 'fun_args': ['accepted'], '_stamp': '2022-04-22T22:57:08.354715', 'return': {'minions': ['9133210011']}, 'success': True}
[DEBUG   ] LazyLoaded nested.output
minions:
    - 9133210011
[INFO    ] Runner completed: 20220422225708344820
[DEBUG   ] Closing IPCMessageClient instance
[WARNING ] minion 9133210011 key is already accepted.
[ERROR   ][37658] Future <salt.ext.tornado.concurrent.Future object at 0x7f7fb29eea58> exception was never retrieved: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/process.py", line 667, in run
    time.sleep(10)
  File "/usr/lib/python3.6/site-packages/salt/master.py", line 849, in _handle_signals
    self.destroy(signum)
  File "/usr/lib/python3.6/site-packages/salt/master.py", line 924, in destroy
    self.process_manager.kill_children()
  File "/usr/lib/python3.6/site-packages/salt/utils/process.py", line 738, in kill_children
    log.trace("Joining pid %s: %s", pid, p_map["Process"])
  File "/usr/lib/python3.6/site-packages/salt/_logging/mixins.py", line 37, in trace
    self.log(getattr(logging, "TRACE", 5), msg, *args, **kwargs)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1374, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/_logging/impl.py", line 298, in _log
    stack_info=stack_info,
  File "/usr/lib64/python3.6/logging/__init__.py", line 1443, in _log
    exc_info, func, extra, sinfo)
  File "/usr/lib/python3.6/site-packages/salt/_logging/impl.py", line 368, in makeRecord
    self, name, level, fn, lno, _msg, _args, exc_info, func, sinfo
  File "/usr/lib64/python3.6/logging/__init__.py", line 1413, in makeRecord
    sinfo)
  File "/usr/lib/python3.6/site-packages/salt/_logging/impl.py", line 129, in __init__
    SaltLogRecord.__init__(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/_logging/impl.py", line 121, in __init__
    logging.LogRecord.__init__(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/master.py", line 850, in _handle_signals
    super()._handle_signals(signum, sigframe)
  File "/usr/lib/python3.6/site-packages/salt/utils/process.py", line 1154, in _handle_signals
    sys.exit(salt.defaults.exitcodes.EX_OK)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/gen.py", line 309, in wrapper
    yielded = next(result)
  File "/usr/lib/python3.6/site-packages/salt/utils/process.py", line 667, in run
    time.sleep(10)
TypeError: 'int' object is not callable
```

</p>
</details>

</p>
</details>

<details><summary>minion debug log</summary>
<p>

```
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/usr/lib/<vendor>/python/salt/file_roots/_beacons/beacons.conf'
[DEBUG   ] Reading configuration from /usr/lib/<vendor>/python/salt/file_roots/_beacons/beacons.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: 9133210011
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] Setting up the Salt Minion "9133210011"
[DEBUG   ] Marking 'base64_encode' as a jinja filter
[DEBUG   ] Marking 'base64_decode' as a jinja filter
[DEBUG   ] Marking 'md5' as a jinja filter
[DEBUG   ] Marking 'sha1' as a jinja filter
[DEBUG   ] Marking 'sha256' as a jinja filter
[DEBUG   ] Marking 'sha512' as a jinja filter
[DEBUG   ] Marking 'hmac' as a jinja filter
[DEBUG   ] Marking 'hmac_compute' as a jinja filter
[DEBUG   ] Marking 'random_hash' as a jinja filter
[DEBUG   ] Marking 'rand_str' as a jinja filter
[DEBUG   ] Marking 'file_hashsum' as a jinja filter
[DEBUG   ] Marking 'http_query' as a jinja filter
[DEBUG   ] Marking 'strftime' as a jinja filter
[DEBUG   ] Marking 'date_format' as a jinja filter
[DEBUG   ] Marking 'raise' as a jinja global
[DEBUG   ] Marking 'match' as a jinja test
[DEBUG   ] Marking 'equalto' as a jinja test
[DEBUG   ] Marking 'skip' as a jinja filter
[DEBUG   ] Marking 'sequence' as a jinja filter
[DEBUG   ] Marking 'to_bool' as a jinja filter
[DEBUG   ] Marking 'indent' as a jinja filter
[DEBUG   ] Marking 'tojson' as a jinja filter
[DEBUG   ] Marking 'quote' as a jinja filter
[DEBUG   ] Marking 'regex_escape' as a jinja filter
[DEBUG   ] Marking 'regex_search' as a jinja filter
[DEBUG   ] Marking 'regex_match' as a jinja filter
[DEBUG   ] Marking 'regex_replace' as a jinja filter
[DEBUG   ] Marking 'uuid' as a jinja filter
[DEBUG   ] Marking 'unique' as a jinja filter
[DEBUG   ] Marking 'min' as a jinja filter
[DEBUG   ] Marking 'max' as a jinja filter
[DEBUG   ] Marking 'avg' as a jinja filter
[DEBUG   ] Marking 'union' as a jinja filter
[DEBUG   ] Marking 'intersect' as a jinja filter
[DEBUG   ] Marking 'difference' as a jinja filter
[DEBUG   ] Marking 'symmetric_difference' as a jinja filter
[DEBUG   ] Marking 'method_call' as a jinja filter
[DEBUG   ] Marking 'yaml_dquote' as a jinja filter
[DEBUG   ] Marking 'yaml_squote' as a jinja filter
[DEBUG   ] Marking 'yaml_encode' as a jinja filter
[DEBUG   ] Created pidfile: /var/run/salt-minion.pid
[INFO    ] Starting up the Salt Minion
[DEBUG   ] AsyncEventPublisher PUB socket URI: /var/run/salt/minion/minion_event_133e88feab_pub.ipc
[DEBUG   ] AsyncEventPublisher PULL socket URI: /var/run/salt/minion/minion_event_133e88feab_pull.ipc
[INFO    ] Starting pull socket on /var/run/salt/minion/minion_event_133e88feab_pull.ipc
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_133e88feab_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_133e88feab_pull.ipc
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/usr/lib/<vendor>/python/salt/file_roots/_beacons/beacons.conf'
[DEBUG   ] Reading configuration from /usr/lib/<vendor>/python/salt/file_roots/_beacons/beacons.conf
[DEBUG   ] Elapsed time getting FQDNs: 0.12727904319763184 seconds
[DEBUG   ] LazyLoaded zfs.is_supported
[INFO    ] Creating minion process manager
[DEBUG   ] Process Manager starting!
[DEBUG   ] Process Manager starting!
[DEBUG   ] Connecting to master. Attempt 1 (infinite attempts)
[DEBUG   ] Master URI: tcp://<SaltMasterIP>:4506
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_133e88feab_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_133e88feab_pull.ipc
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', '9133210011', 'tcp://<SaltMasterIP>:4506')
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] salt.crypt._get_key_with_evict: Loading private key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Initializing new AsyncTCPReqChannel for ('/etc/salt/pki/minion', '9133210011', 'tcp://<SaltMasterIP>:4506', 'clear')
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
[ERROR   ] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
[INFO    ] Waiting 10 seconds before retry.
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
[DEBUG   ] Closing AsyncTCPReqChannel instance
[INFO    ] Exception caught in SaltMessageClient.close: IOLoop is already running
[DEBUG   ] tcp stream to <SaltMasterIP>:4506 closed, unable to recv
[DEBUG   ] Sending event: tag = __master_connected; data = {'master': '<SaltMasterIP>', '_stamp': '2022-04-22T22:56:50.774979'}
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Initializing new AsyncTCPReqChannel for ('/etc/salt/pki/minion', '9133210011', 'tcp://<SaltMasterIP>:4506', 'aes')
[DEBUG   ] Re-using AsyncAuth for ('/etc/salt/pki/minion', '9133210011', 'tcp://<SaltMasterIP>:4506')
[ERROR   ] Minion unable to successfully connect to a Salt Master.
[ERROR   ] Exception getting pillar:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/pillar/__init__.py", line 243, in compile_pillar
    load, dictkey="pillar",
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/gen.py", line 1064, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python3.6/site-packages/salt/transport/tcp.py", line 385, in crypted_transfer_decode_dictentry
    self._package_load(self.auth.crypticle.dumps(load)), timeout=timeout
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
salt.exceptions.SaltReqTimeoutError: Message timed out
[ERROR   ] Error while bringing up minion for multi-master. Is master at <SaltMasterIP> responding?
[WARNING ][22035] TCP Message Client encountered an exception StreamClosedError('Stream is closed',)
```

</p>
</details>

**Additional context**
I don't believe the reactor process is related to the issue but for completeness here's a copy of relative files.
Can't take credit for the auth.py script. An ex-coworker wrote it.
<details><summary>/etc/salt/master.d/reactor.conf</summary>
<p>

```
reactor:
  - 'salt/auth':                    # Match tag "salt/auth"
    - /srv/reactor/auth.py       # Things to do when a minion registers

  - 'salt/minion/*/start':          # Match tag "salt/minion/*/start"
    - /srv/reactor/reconfig.py    # Things to do when a minion starts
```

</p>
</details>

<details><summary>/srv/reactor/auth.py</summary>
<p>

```python
#!py

"""
Reactor:auth
@version: 2020-08-24
"""
import logging
import yaml
import salt.wheel

log = logging.getLogger(__name__)

localLogfile = '/tmp/test_saltreactor.txt'
mappingsYaml = '/srv/reactor/auth_db.yaml'

opts = salt.config.master_config('/etc/salt/master')
wheel = salt.wheel.WheelClient(opts)

def run():
    """
    Basic Reactor should start with run()
    """
    # data structure is passed from Reactor with the id of the minion that sent the signal
    minion_id = data['id']

    log_to_file("received Auth request from minion {}".format(minion_id))

    redirectorMapKeys = list(load_mappings().keys())
    # mod integer S/Ns for some minion implementation that prefix S/N with 'sn'
    redirectorMapKeysExt = redirectorMapKeys + ['sn'+key for key in redirectorMapKeys]

    keysAccepted = wheel.cmd('key.list', ['accepted'])['minions']
    # mod integer S/Ns for some Roter minion implementation that prefix S/N with 'sn'
    keysAcceptedExt = keysAccepted + ['sn'+key for key in keysAccepted]


    if minion_id in keysAcceptedExt:
        log.warning("minion {} key is already accepted.".format(minion_id))
    else:
        if minion_id in redirectorMapKeysExt:
            log.warning("found minion {} in the maps. Accepting minion key.".format(minion_id))
            # fix all digits minion_id. Salt does not like it.
            res = wheel.cmd('key.accept_dict', [{'minions_pre': [minion_id]}])
            log_to_file(str(res))
        else:
            log.warning("No mappings for minion {} found: ignoring key auth request".format(minion_id))

    ret = {}
    return ret


def log_to_file(message):
    '''
    logging to file for quick debug
    '''
    with open(localLogfile, 'a+') as reactor_log_fd:
        reactor_log_fd.write(message + '\n')


def load_mappings():
    """
    Load device serial number to its mappings
    """

    with open(mappingsYaml) as mappings_fd:
        mappings = yaml.load(mappings_fd)

    return mappings
```

</p>
</details>

**Comment by OrangeDog** [comment]
3002.5 is not supported and contains multiple security issues.
3002.8 is the latest of that line, and won't be supported for much longer either.

**Comment by Scottsie** [comment]
> 3002.5 is not supported and contains multiple security issues. 3002.8 is the latest of that line, and won't be supported for much longer either.

I understand but am constrained on the client side. I did try downgrading the salt-master to release 3002.8 to see if it was a compatibility issue but saw the same results. 

My hope is that I can validate if this is a bug, configuration or something to do with tcp transport or versioning to bring to the vendor.

**Comment by OrangeDog** [comment]
Sorry, I didn't see the Master version. There is a breaking change in 3002.8, 3003.4. and 3004.1.
Communication with minions not of those versions is not possible.
A downgrade to 3004.0 should work, but then you will have these: https://saltproject.io/security_announcements/salt-security-advisory-release/

#61874
