### ISSUE TITLE
[BUG] 3004.1-1 - x509.create_certificate does not generate a valid certificate (invalid X509v3 Authority Key Identifier)

### ISSUE THREAD

**Issue by synedraIT** [saltstack/salt#61993]
**Description**
Hello!

After updating salt (minion, it works with an old minion) to v3004.1, I am unable to create certificates in states.
Using the module `x509.create_certificate` "works", but I get a certificate with a broken `X509v3 Authority Key Identifier` Extension.
The state presumably tries to read back a generated certificate to compare to the current one and terminates with a stacktrace, since the new certificate generated is invalid.

Stacktrace:
```
----------
          ID: sign zabbix certificate
    Function: x509.certificate_managed
        Name: /etc/pki/saltstack/zabbix.cert
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3.6/site-packages/salt/state.py", line 2180, in call
                  *cdata["args"], **cdata["kwargs"]
                File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 149, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1201, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/usr/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
                  return callable(*args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1216, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1249, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/states/x509.py", line 690, in certificate_managed
                  __salt__["x509.read_certificate"](contents)
                File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 149, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1201, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/usr/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
                  return callable(*args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1216, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/modules/x509.py", line 589, in read_certificate
                  val = ext.get_value()
                File "/usr/lib64/python3.6/site-packages/M2Crypto/X509.py", line 117, in get_value
                  return six.ensure_text(buf.read_all())
                File "/usr/lib64/python3.6/site-packages/M2Crypto/six.py", line 906, in ensure_text
                  raise TypeError("not expecting type '%s'" % type(s))
              TypeError: not expecting type '<class 'NoneType'>'
     Started: 09:50:44.897570
    Duration: 357.203 ms
     Changes:
```
I added some print statements to verify the faulty extension (adding `print(name)` to `/usr/lib/python3.6/site-packages/salt/modules/x509.py` in Line `589`) and it seems to be `authorityKeyIdentifier`, which is consistent with my findings.

**Setup**
Confirmed to be an issue:
- [x] on-prem machine
- [X] VM (Virtualbox, KVM, etc. please specify) - VMWare ESX
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
  
**Steps to Reproduce the behavior**
Run `x509.create_certificate`: 
```
salt "<REDACTED>" \
        x509.create_certificate \
        path="/etc/pki/saltstack/zabbix.cert" \
        ca_server="<REDACTED>" \
        signing_policy="zabbix" \
        public_key="/etc/pki/saltstack/private/zabbix.private.key" \
        CN="<REDACTED>" \
        days_valid=<REDACTED> \
        days_remaining=<REDACTED> \
        subjectAltName="DNS:<REDACTED>"
```
...with this signing policy:
```
x509_signing_policies:
  zabbix:
    - minions: '*'
    - signing_private_key: /etc/pki/CA/saltstack/zabbix/private/ca.private
    - signing_private_key_passphrase: <redacted>
    - signing_cert: /etc/pki/CA/saltstack/zabbix/cacert.pem
    - basicConstraints: "critical CA:false"
    - authorityKeyIdentifier: keyid,issuer:always
    - C:  "<REDACTED>"
    - ST: "<REDACTED>"
    - L:  "<REDACTED>"
    - O:  "<REDACTED>"
    - copypath: /etc/pki/CA/saltstack/zabbix/cert.db/
```

If you do the same in a state, that will fail with a stacktrace (had to heavily simplify our state here, so this might fail, hopefully you get the idea):
```
zabbix key:
  x509.private_key_managed:
    - name: "/etc/pki/saltstack/private/zabbix.private.key"
    - bits: <REDACTED>

sign zabbix certificate:
  x509.certificate_managed:
    - name: "/etc/pki/saltstack/zabbix.cert"
    - ca_server: "<REDACTED>"
    - signing_policy: zabbix

    - public_key: "/etc/pki/saltstack/private/zabbix.private.key"
    - CN: "<REDACTED>"
    - days_valid:  <REDACTED>
    - days_remaining: <REDACTED>
    - failhard: True
    - subjectAltName: "DNS:<REDACTED>"
    - require:
      - x509: zabbix key
```
**Expected behavior**
Salt generates a valid certificate.
Example of valid certificate extension generated by salt (using `openssl x509 -in /etc/pki/saltstack/zabbix.cert -text -noout`):
```
X509v3 Authority Key Identifier:
                DirName:/C=<REDACTED>/CN=<REDACTED>/L=<REDACTED>/O=<REDACTED>/OU=<REDACTED>/ST=<REDACTED>/emailAddress=<REDACTED>
                serial:XX:XX:XX:XX:XX:XX:XX:XX

```
Now, it generates:
```
X509v3 Authority Key Identifier:
                0.
```

**Versions Report**
<details><summary>salt --versions-report</summary>
Master running 3004.1.

Broken minion:

```yaml
Salt Version:
          Salt: 3004.1

Dependency Versions:
          cffi: 1.11.5
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.14
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 17 2021, 16:10:06)
  python-gnupg: Not Installed
        PyYAML: 3.12
         PyZMQ: 19.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: almalinux 8.5 Arctic Sphynx
        locale: UTF-8
       machine: x86_64
       release: 4.18.0-348.20.1.el8_5.x86_64
        system: Linux
       version: AlmaLinux 8.5 Arctic Sphynx

```

Working minion:

```yaml
Salt Version:
          Salt: 3004

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 17 2021, 16:10:06)
  python-gnupg: Not Installed
        PyYAML: 3.12
         PyZMQ: 19.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: almalinux 8.5 Arctic Sphynx
        locale: UTF-8
       machine: x86_64
       release: 4.18.0-348.12.2.el8_5.x86_64
        system: Linux
       version: AlmaLinux 8.5 Arctic Sphynx
```
</details>

**Additional context**
This happens with all policies we have and with all CA-Certificates we use.
I will happily provide further information on request.

Thank you!

**Comment by synedraIT** [comment]
On AlmaLinux 8.6 (4.18.0-348.7.1.el8_5.x86_64), the issue is not present anymore.
The only difference seems to be the python version, so this seems like an issue somewhere else.
