### ISSUE TITLE
New salt-minion versions are causing tornado exceptions in log files - connection fails to master

### ISSUE THREAD

**Issue by infantvin** [saltstack/salt#62034]
### Description of Issue
Installing the latest available version of salt-minion to a VM/physical system with a fresh install of RHEL8.0
After filling in master details and starting the minion - the minion does not connect to the master.

Error message is similar to the one below
2022-05-06 20:55:49,341 [tornado.application:640 ][ERROR   ][8635] Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7f866f6e0950>, <salt.ext.tornado.concurrent.Future object at 0x7f867558ba58>)
Traceback (most recent call last):
.....
2022-05-06 21:07:32,115 [salt.minion      :1143][ERROR   ][8824] Error while bringing up minion for multi-master. Is master at xxx  responding?
2022-05-06 21:07:42,141 [salt.crypt       :781 ][ERROR   ][8824] Sign-in attempt failed: {'enc': 'pub', 'pub_key': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
xdfqU\xb1\xb1\xeb\xd9\xa9\xe1\x8b)\xafP\xee`\xe5\x182k\x15\x88\xae'}
2022-05-06 21:07:42,142 [salt.minion      :1143][ERROR   ][8824] Error while bringing up minion for multi-master. Is master at xxx responding?

NOTE: - This happens with any latest version of salt-minion - v3003.x/v3002.x 
So this is specific to whatever binary package is available.

I tried to use an old version of salt-minion from a site which stores archived binaries (3001 in my case). It worked properly.

### Setup

Fresh install of RHEL8
Setup salt for v3003.x as per instructions here - https://repo.saltproject.io/3003.html#rhel

Currently whole salt minion work on RHEL8 is stopped because of this.

### Steps to Reproduce Issue

1) Install fresh RHEL8.0 VM and disable firewall to prevent any issues from it.
2) Install salt-minion as per https://repo.saltproject.io/3003.html#rhel
3) Fill in salt master details
4) Restart the minion service via systemctl.

### Versions Report
Salt master is on 3003.3

From the minion
[salt-minion-error.txt](https://github.com/saltstack/salt/files/8643141/salt-minion-error.txt)
salt-minion --versions-report
Salt Version:
          Salt: 3003.4

Dependency Versions:
          cffi: 1.11.5
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.14
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Jan 11 2019, 02:17:16)
  python-gnupg: Not Installed
        PyYAML: 3.12
         PyZMQ: 19.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: rhel 8.0 Ootpa
        locale: UTF-8
       machine: x86_64
       release: 4.18.0-80.el8.x86_64
        system: Linux
       version: Red Hat Enterprise Linux 8.0 Ootpa

**Comment by OrangeDog** [comment]
Same as #61874

3003.4 minions cannot communicate with a 3003.3 master.
The master must be upgraded first.

**Comment by infantvin** [comment]
Thanks for the update.
But how come even a 3002.x version of the minion is not allowing communicating with the 3003.3 master?

I will test this with a 3002.x latest minion version and get back. The last time I did this I think it failed with this same error.

**Comment by infantvin** [comment]
Hi,
I just installed the 3002.8 version of the minion on the RHEL8 VM and see the same error now.

2022-05-09 11:42:00,393 [tornado.application:640 ][ERROR   ][2486] Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7fa9e129f488>, <salt.ext.tornado.concurrent.Future object at 0x7fa9e1305908>)
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/ioloop.py", line 606, in _run_callback
    ret = callback()
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/stack_context.py", line 278, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/ioloop.py", line 628, in _discard_future_result
    future.result()
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/gen.py", line 1064, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python3.6/site-packages/salt/crypt.py", line 648, in _authenticate
    creds = yield self.sign_in(channel=channel)
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/gen.py", line 1070, in run
    yielded = self.gen.send(value)
  File "/usr/lib/python3.6/site-packages/salt/crypt.py", line 773, in sign_in
    ret = self.handle_signin_response(sign_in_payload, payload)
  File "/usr/lib/python3.6/site-packages/salt/crypt.py", line 785, in handle_signin_response
    clear_signature = payload["sig"]
KeyError: 'sig'
2022-05-09 11:43:00,365 [salt.minion      :1089][ERROR   ][2486] Minion unable to successfully connect to a Salt Master.

**Comment by infantvin** [comment]
# salt-minion --versions-report
Salt Version:
          Salt: 3002.8

Please let me know if you need any further info.

I cannot find the old version of 3003.3 or older anymore in the repositories and the salt-cloud is unable to fetch v 3003.3 when mentioned in the profile file.

**Comment by OrangeDog** [comment]
All vulnerable versions have been moved to [archive.repo.saltproject.io](https://archive.repo.saltproject.io/).
The latest fixes, which included a breaking change, was released as [3002.8, 3003.4, and 3004.1](https://saltproject.io/security_announcements/salt-security-advisory-release/).
No older masters will work with any of those minions.
You must upgrade the master first.

**Comment by infantvin** [comment]
Thanks for pointing to the older repo.

I saw the note on the upgrade of the salt master in the links you have given. I will do this at the earliest opportunity we get.. Right now we are in between a migration and it will have to wait until this migration is done.
