### ISSUE TITLE
[BUG] ssh_known_hosts.present excpetion when specified user not present

### ISSUE THREAD

**Issue by boltronics** [saltstack/salt#62049]
**Description**
Using the `ssh_known_hosts.present` state module with the `- user: ` argument blows up with an unhelpful `TypeError: string indices must be integers` exception when the supplied user does not actually exist.

**Setup**
No special setup required. Just specify a user that doesn't actually exist, and you'll get the following:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/state.py", line 2154, in call
    *cdata["args"], **cdata["kwargs"]
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2106, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/states/ssh_known_hosts.py", line 177, in present
    fingerprint_hash_type=fingerprint_hash_type,
  File "/usr/lib/python3/dist-packages/salt/modules/ssh.py", line 1114, in set_known_host
    stored_keys = [h["key"] for h in stored_host_entries] if stored_host_entries else []
  File "/usr/lib/python3/dist-packages/salt/modules/ssh.py", line 1114, in <listcomp>
    stored_keys = [h["key"] for h in stored_host_entries] if stored_host_entries else []
TypeError: string indices must be integers
```
  
**Steps to Reproduce the behavior**
```
Add {{ host }} ({{ host_fqdn }}) SSH host-key to baduser known_hosts:
  ssh_known_hosts.present:
    - name: {{ host_fqdn }}
    - user: baduser
    - enc: ecdsa
    - fingerprint: '{{ fingerprint }}'
    - port: 22
    - fingerprint_hash_type: sha256
```

Everything works as expected if I replace "baduser" with the valid user "root", for example.

**Expected behavior**
An error that the user does not exist.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
Salt Version:
          Salt: 3002.8
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.5
     gitpython: 2.1.11
        Jinja2: 2.10
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.7.3 (default, Jan 22 2021, 20:04:44)
  python-gnupg: 0.4.4
        PyYAML: 3.13
         PyZMQ: 17.1.2
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.1
 
System Versions:
          dist: debian 10 buster
        locale: UTF-8
       machine: x86_64
       release: 4.19.0-17-cloud-amd64
        system: Linux
       version: Debian GNU/Linux 10 buster
```
</details>

**Additional context**
I could not tell what the issue was when I ran into this exception without some investigation, which are additional steps that should not be necessary.

Thanks.

**Comment by Ch3LL** [comment]
I'm able to confirm this behavior on the head of master.

**Comment by boltronics** [comment]
Still an issue in 3006.17.

```
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/state.py", line 2465, in call
                  ret = self.states[cdata["full"]](
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 161, in __call__
                  ret = self.loader.run(run_func, *args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1247, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1262, in _run_as
                  ret = _func_or_method(*args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1298, in wrapper
                  return f(*args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/states/ssh_known_hosts.py", line 140, in present
                  result = __salt__["ssh.check_known_host"](
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 161, in __call__
                  ret = self.loader.run(run_func, *args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1247, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1262, in _run_as
                  ret = _func_or_method(*args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/modules/ssh.py", line 973, in check_known_host
                  known_keys = [h["key"] for h in known_host_entries] if known_host_entries else []
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/modules/ssh.py", line 973, in <listcomp>
                  known_keys = [h["key"] for h in known_host_entries] if known_host_entries else []
              TypeError: string indices must be integers
```

where 973 of ssh.py (the `check_known_host` function) has:
```
    known_host_entries = get_known_host_entries(
        user,
        hostname,
        config=config,
        port=port,
        fingerprint_hash_type=fingerprint_hash_type,
    )
    known_keys = [h["key"] for h in known_host_entries] if known_host_entries else []
```

So:
```
$ sudo salt salt-master ssh.get_known_host_entries baduser github.com
salt-master:
    ----------
    error:
        User baduser does not exist
    status:
        error
$
```
indicates the `get_known_host_entries` function is doing the right thing, but `check_known_host` is not.

Suggested fix:
```
    known_host_entries = get_known_host_entries(
        user,
        hostname,
        config=config,
        port=port,
        fingerprint_hash_type=fingerprint_hash_type,
    )
    if "error" in known_host_entries:
        return known_host_entries
    known_keys = [h["key"] for h in known_host_entries] if known_host_entries else []
```

Before the fix:
```
$ sudo salt salt-master ssh.check_known_host baduser github.com
salt-master:
    Passed invalid arguments to ssh.check_known_host: string indices must be integers
    
        Check the record in known_hosts file, either by its value or by fingerprint
        (it's enough to set up either key or fingerprint, you don't need to set up
        both).
    
        If provided key or fingerprint doesn't match with stored value, return
        "update", if no value is found for a given host, return "add", otherwise
        return "exists".
    
        If neither key, nor fingerprint is defined, then additional validation is
        not performed.
    
        CLI Example:
    
        .. code-block:: bash
    
            salt '*' ssh.check_known_host <user> <hostname> key='AAAA...FAaQ=='
$
```

After the fix:
```
$ sudo salt 'salt-master*' ssh.check_known_host baduser github.com
salt-master:
    ----------
    error:
        User baduser does not exist
    status:
        error
$ 
```

**Comment by dwoz** [comment]
Fixed by #68537 (commit 92b178d), merged to 3006.x on 2025-12-18 and merge-forwarded to 3007.x/3008.x/master. Closing.
