### ISSUE TITLE
[BUG] Unable to run Salt SSH on machines, getting error in python2.7 subprocess.py 

### ISSUE THREAD

**Issue by GudaboinaSuhas** [saltstack/salt#62051]
**Description**
I'm trying to run some adhoc commands on machines using salt ssh and getting this error. Couldn't find much help on internet.

Error:
```
----------
    retcode:
        1
    stderr:
        Traceback (most recent call last):
          File "<string>", line 245, in <module>
          File "<string>", line 420, in <module>
          File "<string>", line 363, in main
          File "<string>", line 266, in get_executable
          File "/usr/lib64/python2.7/subprocess.py", line 394, in __init__
            errread, errwrite)
          File "/usr/lib64/python2.7/subprocess.py", line 1047, in _execute_child
            raise child_exception
        OSError: [Errno 2] No such file or directory
    stdout:
        /bin/scp
```

**Setup**

- [ ] VM running on a cloud service
 Details:
 - OS: Ubuntu 18.04(salt master), Amazon Linux2(target instances)
 - Salt version: 3001.8

**Versions Report**
<details><summary>salt --versions-report</summary>

```yaml
Salt Version:
           Salt: 3001.8
 
Dependency Versions:
           cffi: 1.14.1
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: 2.6.1
   pycryptodome: 3.4.7
         pygit2: Not Installed
         Python: 3.6.9 (default, Mar 15 2022, 13:55:28)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 17.1.2
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: ubuntu 18.04 Bionic Beaver
         locale: UTF-8
        machine: x86_64
        release: 5.4.0-1056-aws
         system: Linux
        version: Ubuntu 18.04 Bionic Beaver
```
</details>

**Comment by OrangeDog** [comment]
Python 2 is not supported. You have to install Python 3.6 or higher on the target first.

**Comment by fs30000** [comment]
Just got the same error after installing just salt-ssh on a Centos 7 machine, version 3005.1:

`salt-ssh -v  -i '*' test.ping
Executing job with jid 20221216200416587914
-------------------------------------------


vm34:
    ----------
    retcode:
        1
    stderr:
        Traceback (most recent call last):
          File "<string>", line 246, in <module>
          File "<string>", line 427, in <module>
          File "<string>", line 370, in main
          File "<string>", line 272, in get_executable
          File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
            errread, errwrite)
          File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
            raise child_exception
        OSError: [Errno 2] No such file or directory
    stdout:
        /usr/bin/scp
`

Can't salt throw a warning?
