### ISSUE TITLE
[BUG] Salt incompatible with pyzmq 23.0.0

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#62092]
**Description**

pyzmq 23.0.0 has been just released a few days ago, which causes issues for the `salt` command: `Unable to connect to the salt master publisher at /var/run/salt/master`.

**Setup**

Install any Salt version & pyzmq 23.0.0.

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [x] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**

Install Salt 3002.8 & pyzmq 23.0.0 results in the following error:

```
Process salt.transport.zeromq.<class 'method'>._publish_daemon:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/salt/transport/zeromq.py", line 1020, in _publish_daemon
    pub_sock.setsockopt(zmq.HWM, self.opts.get("pub_hwm", 1000))
  File "zmq/backend/cython/socket.pyx", line 447, in zmq.backend.cython.socket.Socket.set
  File "zmq/backend/cython/socket.pyx", line 279, in zmq.backend.cython.socket._setsockopt
  File "zmq/backend/cython/checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Invalid argument
[ERROR   ] Future <salt.ext.tornado.concurrent.Future object at 0x7ffbe015be50> exception was never retrieved: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/salt/ext/tornado/gen.py", line 309, in wrapper
    yielded = next(result)
  File "/usr/local/lib/python3.9/site-packages/salt/utils/process.py", line 655, in run
    self.check_children()
  File "/usr/local/lib/python3.9/site-packages/salt/utils/process.py", line 680, in check_children
    for pid, mapping in self._process_map.items():
RuntimeError: dictionary keys changed during iteration
Process salt.transport.zeromq.<class 'method'>._publish_daemon:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/salt/transport/zeromq.py", line 1020, in _publish_daemon
    pub_sock.setsockopt(zmq.HWM, self.opts.get("pub_hwm", 1000))
  File "zmq/backend/cython/socket.pyx", line 447, in zmq.backend.cython.socket.Socket.set
  File "zmq/backend/cython/socket.pyx", line 279, in zmq.backend.cython.socket._setsockopt
  File "zmq/backend/cython/checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Invalid argument
```

(Salt 3002.8 with pyzmq 22.3.0 runs without issues)

Exact same incompatibility story with Salt 3003.4 & pyzmq 23.0.0, however 22.3.0 gives Salt what it needs.

I couldn't install pyzmq 23.0.0 with Salt 3004.1, thanks to the following req `pyzmq>19.0.2,<22.0.0 ; python_version >= "3.9"`:

```
The conflict is caused by:
    The user requested pyzmq==23.0.0
    salt 3004.1 depends on pyzmq<22.0.0 and >19.0.2
```

However I can see this has been dropped recently in https://github.com/saltstack/salt/commit/be9879c5d5b30ea0997b1cfca9ad830a54a900b0, although the commit message seems unrelated, so I wouldn't be surprised if the next Salt release would run into the same issue with pyzmq 23.0.0.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
root@master:/# salt -V
Salt Version:
          Salt: 3003.4
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.0.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.3
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.14.1
        pygit2: Not Installed
        Python: 3.9.12 (main, Apr 20 2022, 05:58:36)
  python-gnupg: Not Installed
        PyYAML: 6.0
         PyZMQ: 23.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 10 buster
        locale: utf-8
       machine: x86_64
       release: 5.4.0-107-generic
        system: Linux
       version: Debian GNU/Linux 10 buster
```
</details>

**Additional context**

I've added some files to https://github.com/mirceaulinic/salt-pyzmq. If you clone the repo and execute `make run` should see the issue (can use the `SALT` and `ZMQ` arguments to model various versions, e.g., `make run SALT=3003.4 ZMQ=22.3.0`.

**Comment by nicholasmhughes** [comment]
I just installed Salt from the master branch and ran into this. It will affect 3005 and needs to be resolved before release.

Tested on a fresh Debian 10 machine using the bootstrap script:

```bash
curl -L https://bootstrap.saltproject.io | sudo sh -s -- -M git master
```

Versions Report:

```yaml
Salt Version:
          Salt: 3005+0na.b18281e
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.3
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.14.1
        pygit2: Not Installed
        Python: 3.7.3 (default, Jan 22 2021, 20:04:44)
  python-gnupg: Not Installed
        PyYAML: 6.0
         PyZMQ: 23.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 10 buster
        locale: UTF-8
       machine: x86_64
       release: 4.19.0-18-amd64
        system: Linux
       version: Debian GNU/Linux 10 buster
```

Error in master logs:

```
2022-05-27 20:27:47,491 [salt.utils.process:1002][ERROR   ][11398] An un-handled exception from the multiprocessing process 'PubServerChannel._publish_daemon' was caught:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/salt/utils/process.py", line 993, in wrapped_run_func
    return run_func()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/salt/channel/server.py", line 777, in _publish_daemon
    self.transport.publish_daemon(self.publish_payload, self.presence_callback)
  File "/usr/local/lib/python3.7/dist-packages/salt/transport/zeromq.py", line 724, in publish_daemon
    pub_sock.setsockopt(zmq.HWM, self.opts.get("pub_hwm", 1000))
  File "zmq/backend/cython/socket.pyx", line 447, in zmq.backend.cython.socket.Socket.set
  File "zmq/backend/cython/socket.pyx", line 279, in zmq.backend.cython.socket._setsockopt
  File "zmq/backend/cython/checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Invalid argument
```

Unable to run commands as a result:

```bash
root@d10-saltgit-01:~# salt \* test.ping
[ERROR   ] Unable to connect to the salt master publisher at /var/run/salt/master
The salt master could not be contacted. Is master running?
```

**Comment by mirceaulinic** [comment]
Opened #62119 - I think that should fix it.
