### ISSUE TITLE
'azurearm_compute' __virtual__ returned False: The following dependencies are required to use the AzureARM modules: Microsoft Azure SDK for Python >= 2.0rc6, MS REST Azure (msrestazure) >= 0.4

### ISSUE THREAD

**Issue by rutvik-98** [saltstack/salt#62140]
Hello Team,

I was trying to run the azure-arm module in salt from salt-master but I am getting below error when I run this.

```
root@salt-master-b5f7f5964-whgwn:/opt/salt# salt-call azurearm_compute.virtual_machines_list_all
'azurearm_compute' __virtual__ returned False: The following dependencies are required to use the AzureARM modules: Microsoft Azure SDK for Python >= 2.0rc6, MS REST Azure (msrestazure) >= 0.4
root@salt-master-b5f7f5964-whgwn:/opt/salt# 
root@salt-master-b5f7f5964-whgwn:/opt/salt# pip list | grep msrestazure
msrestazure                             0.6.4
root@salt-master-b5f7f5964-whgwn:/opt/salt# 
```
I checked for `msrestazure` and it is above from minimum required version but when I tried to update `Microsoft Azure SDK for Python` I got errors.
```
root@salt-master-b5f7f5964-whgwn:/opt/salt# pip install azure
Collecting azure
  Downloading azure-5.0.0.zip (4.6 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-qpuf9sct/azure_d34cb58f834b4bfaae8d2c3389d2a22c/setup.py", line 60, in <module>
          raise RuntimeError(message)
      RuntimeError:
      
      Starting with v5.0.0, the 'azure' meta-package is deprecated and cannot be installed anymore.
      Please install the service specific packages prefixed by `azure` needed for your application.
      
      The complete list of available packages can be found at:
      https://aka.ms/azsdk/python/all
      
      Here's a non-exhaustive list of common packages:
      
      -  azure-mgmt-compute (https://pypi.python.org/pypi/azure-mgmt-compute) : Management of Virtual Machines, etc.
      -  azure-mgmt-storage (https://pypi.python.org/pypi/azure-mgmt-storage) : Management of storage accounts.
      -  azure-mgmt-resource (https://pypi.python.org/pypi/azure-mgmt-resource) : Generic package about Azure Resource Management (ARM)
      -  azure-keyvault-secrets (https://pypi.python.org/pypi/azure-keyvault-secrets) : Access to secrets in Key Vault
      -  azure-storage-blob (https://pypi.python.org/pypi/azure-storage-blob) : Access to blobs in storage accounts
      
      A more comprehensive discussion of the rationale for this decision can be found in the following issue:
      https://github.com/Azure/azure-sdk-for-python/issues/10646
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
root@salt-master-b5f7f5964-whgwn:/opt/salt# 
```

I have tried to add all the dependencies but dependencies are not updating in msater. Please help with this.

**Comment by rutvik-98** [comment]
```
root@salt-master-b5f7f5964-whgwn:/opt/salt# pip list | grep msrestazure
msrestazure                             0.6.4
root@salt-master-b5f7f5964-whgwn:/opt/salt# 
```
I checked for msrestazure and it is above from minimum required version but when I tried to update `Microsoft Azure SDK for Python` I got errors.
```
root@salt-master-b5f7f5964-whgwn:/opt/salt# pip install azure
Collecting azure
  Downloading azure-5.0.0.zip (4.6 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-qpuf9sct/azure_d34cb58f834b4bfaae8d2c3389d2a22c/setup.py", line 60, in <module>
          raise RuntimeError(message)
      RuntimeError:
      
      Starting with v5.0.0, the 'azure' meta-package is deprecated and cannot be installed anymore.
      Please install the service specific packages prefixed by `azure` needed for your application.
      
      The complete list of available packages can be found at:
      https://aka.ms/azsdk/python/all
      
      Here's a non-exhaustive list of common packages:
      
      -  azure-mgmt-compute (https://pypi.python.org/pypi/azure-mgmt-compute) : Management of Virtual Machines, etc.
      -  azure-mgmt-storage (https://pypi.python.org/pypi/azure-mgmt-storage) : Management of storage accounts.
      -  azure-mgmt-resource (https://pypi.python.org/pypi/azure-mgmt-resource) : Generic package about Azure Resource Management (ARM)
      -  azure-keyvault-secrets (https://pypi.python.org/pypi/azure-keyvault-secrets) : Access to secrets in Key Vault
      -  azure-storage-blob (https://pypi.python.org/pypi/azure-storage-blob) : Access to blobs in storage accounts
      
      A more comprehensive discussion of the rationale for this decision can be found in the following issue:
      https://github.com/Azure/azure-sdk-for-python/issues/10646
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
root@salt-master-b5f7f5964-whgwn:/opt/salt# 
```

**Comment by nicholasmhughes** [comment]
The Azure functionality in Salt is moving to https://github.com/salt-extensions/saltext-azurerm

Please try out the extension and open an issue there if you are still encountering problems.
