### ISSUE TITLE
[BUG] AttributeError: 'TimedProc' object has no attribute 'stdout'

### ISSUE THREAD

**Issue by marty-macfly** [saltstack/salt#62142]
**Description**

I'm trying to run a test python script with the [`cmd.run_all`](https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.cmdmod.html#salt.modules.cmdmod.run_all) command with the following arguments

```json
  {
    "cmd": "{{grains.pythonexecutable}} -",
    "stdin": "#!/usr/bin/env python3\n\nimport sys,os\nsys.path.append(os.getcwd())\n\nimport logging\n\ndef create_logger():\n    logger = logging.getLogger()\n    \n    c_handler = logging.StreamHandler()\n\n    # Set logging level\n    logger.setLevel(logging.DEBUG)\n    c_handler.setLevel(logging.INFO)\n\n    # Add handlers to the logger\n    logger.addHandler(c_handler)\n\n    return logger\n\n\nif __name__ == '__main__':\n\n    logger = create_logger()\n\n    logger.info(\"Test1\")    \n    logger.info(\"Test2\\n\")    \n    logger.info(\"\\nTest3\")  ",
    "timeout": 60,
    "template": "jinja",
    "stdin_raw_newlines": true
  }
```

 from the [CheryPy API](https://docs.saltproject.io/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html#salt.netapi.rest_cherrypy.app.Run) and when command is running on minion I've got the following error:

```
The minion function caused an exception: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/minion.py", line 1906, in _thread_return
    function_name, function_args, executors, opts, data
  File "/usr/lib/python3.6/site-packages/salt/minion.py", line 1862, in _execute_job_function
    return_data = self.executors[fname](opts, data, func, args, kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 1241, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 2274, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
    return callable(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 2289, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 1241, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 2274, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
    return callable(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 2289, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/modules/cmdmod.py", line 2188, in run_all
    **kwargs
  File "/usr/lib/python3.6/site-packages/salt/modules/cmdmod.py", line 719, in _run
    proc.stdout, encoding=output_encoding
AttributeError: 'TimedProc' object has no attribute 'stdout'
```

**Versions Report**

<details><summary>salt --versions-report</summary>

```yaml
Salt Version:
          Salt: 3004.1
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4
 
System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-1160.59.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core
```
</details>

  
**Steps to Reproduce the behavior**

Here is my test python script:

```python
#!/usr/bin/env python3

import sys,os
sys.path.append(os.getcwd())

import logging

def create_logger():
    logger = logging.getLogger()

    c_handler = logging.StreamHandler()

    # Set logging level
    logger.setLevel(logging.DEBUG)
    c_handler.setLevel(logging.INFO)

    # Add handlers to the logger
    logger.addHandler(c_handler)

    return logger


if __name__ == '__main__':

    logger = create_logger()

    logger.info("Test1")    
    logger.info("Test2\n")    
    logger.info("\nTest3")  
```

If I run the `cmd.run_all` command with the following arguments:

```json
  {
    "cmd": "{{grains.pythonexecutable}} -",
    "stdin": "#!/usr/bin/env python3\n\nimport sys,os\nsys.path.append(os.getcwd())\n\nimport logging\n\ndef create_logger():\n    logger = logging.getLogger()\n    \n    c_handler = logging.StreamHandler()\n\n    # Set logging level\n    logger.setLevel(logging.DEBUG)\n    c_handler.setLevel(logging.INFO)\n\n    # Add handlers to the logger\n    logger.addHandler(c_handler)\n\n    return logger\n\n\nif __name__ == '__main__':\n\n    logger = create_logger()\n\n    logger.info(\"Test1\")    \n    logger.info(\"Test2\\n\")    \n    logger.info(\"\\nTest3\")  ",
    "timeout": 60,
    "template": "jinja",
  }
```

I've got a return from the minion but the script is not properly execute due to the `/n` in the code.

```2022-06-07 05:31:10,322 [salt.loaded.int.module.cmdmod:415 ][INFO    ][90905] Executing command '/usr/bin/python3' in directory '/root'
2022-06-07 05:31:10,353 [salt.loaded.int.module.cmdmod:853 ][ERROR   ][90905] Command '/usr/bin/python3' failed with return code: 1
2022-06-07 05:31:10,353 [salt.loaded.int.module.cmdmod:857 ][ERROR   ][90905] stderr:   File "<stdin>", line 28
    logger.info("Test2
                     ^
SyntaxError: EOL while scanning string literal
2022-06-07 05:31:10,354 [salt.loaded.int.module.cmdmod:859 ][ERROR   ][90905] retcode: 1
```
To avoid the conversion of the `/n` from the STDIN into a line break I tried to add the following option:

```
stdin_raw_newlines (bool) --

False

    If True, Salt will not automatically convert the characters \n present in the stdin value to newlines.

New in version 2019.2.0.
```
new arguments to  `cmd.run_all` command are the following

```json
  {
    "cmd": "{{grains.pythonexecutable}} -",
    "stdin": "#!/usr/bin/env python3\n\nimport sys,os\nsys.path.append(os.getcwd())\n\nimport logging\n\ndef create_logger():\n    logger = logging.getLogger()\n    \n    c_handler = logging.StreamHandler()\n\n    # Set logging level\n    logger.setLevel(logging.DEBUG)\n    c_handler.setLevel(logging.INFO)\n\n    # Add handlers to the logger\n    logger.addHandler(c_handler)\n\n    return logger\n\n\nif __name__ == '__main__':\n\n    logger = create_logger()\n\n    logger.info(\"Test1\")    \n    logger.info(\"Test2\\n\")    \n    logger.info(\"\\nTest3\")  ",
    "timeout": 60,
    "template": "jinja",
    "__kwarg__": true,
    "stdin_raw_newlines": true
  }
```
And the return of the minion is:

```
2022-06-08 11:17:03,806 [salt.loaded.int.module.cmdmod:417 ][INFO    ][29409] Executing command '/usr/bin/python3' in directory '/root'
2022-06-08 11:17:03,813 [salt.minion      :1990][WARNING ][29409] The minion function caused an exception
2022-06-08 11:17:03,818 [salt.utils.event :817 ][DEBUG   ][29409] Sending event: tag = _salt_error; data = {'message': 'The minion function caused an exception', 'args': ('The minion function caused an exception',), '_stamp': '2022-06-08T09:17:03.818072'}
2022-06-08 11:17:03,818 [salt.transport.ipc:370 ][DEBUG   ][29409] Closing IPCMessageClient instance
2022-06-08 11:17:03,821 [salt.minion      :2669][DEBUG   ][27089] Minion of '127.0.0.1' is handling event tag '_salt_error'
2022-06-08 11:17:03,821 [salt.minion      :2887][DEBUG   ][27089] Forwarding salt error event tag=_salt_error
2022-06-08 11:17:03,822 [salt.transport.zeromq:160 ][DEBUG   ][27089] Connecting the Minion to the Master URI (for the return server): tcp://127.0.0.1:4506
2022-06-08 11:17:03,822 [salt.minion      :896 ][DEBUG   ][29409] Minion return retry timer set to 16 seconds (randomized)
2022-06-08 11:17:03,822 [salt.minion      :2173][INFO    ][29409] Returning information for job: 20220608091703422445
2022-06-08 11:17:03,823 [salt.transport.zeromq:1233][DEBUG   ][27089] Trying to connect to: tcp://127.0.0.1:4506
2022-06-08 11:17:03,823 [salt.transport.zeromq:160 ][DEBUG   ][29409] Connecting the Minion to the Master URI (for the return server): tcp://127.0.0.1:4506
2022-06-08 11:17:03,824 [salt.transport.zeromq:1233][DEBUG   ][29409] Trying to connect to: tcp://127.0.0.1:4506
2022-06-08 11:17:03,855 [salt.transport.zeromq:179 ][DEBUG   ][29409] Closing AsyncZeroMQReqChannel instance
2022-06-08 11:17:03,857 [salt.minion      :2040][DEBUG   ][29409] minion return: {'success': False, 'return': 'The minion function caused an exception: Traceback (most recent call last):\n  File "/usr/lib/python3.6/site-packages/salt/minion.py", line 1913, in _thread_return\n    function_name, function_args, executors, opts, data\n  File "/usr/lib/python3.6/site-packages/salt/minion.py", line 1869, in _execute_job_function\n    return_data = self.executors[fname](opts, data, func, args, kwargs)\n  File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 149, in __call__\n    return self.loader.run(run_func, *args, **kwargs)\n  File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1201, in run\n    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)\n  File "/usr/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run\n    return callable(*args, **kwargs)\n  File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1216, in _run_as\n    return _func_or_method(*args, **kwargs)\n  File "/usr/lib/python3.6/site-packages/salt/executors/direct_call.py", line 10, in execute\n    return func(*args, **kwargs)\n  File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 149, in __call__\n    return self.loader.run(run_func, *args, **kwargs)\n  File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1201, in run\n    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)\n  File "/usr/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run\n    return callable(*args, **kwargs)\n  File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1216, in _run_as\n    return _func_or_method(*args, **kwargs)\n  File "/usr/lib/python3.6/site-packages/salt/modules/cmdmod.py", line 2310, in run_all\n    **kwargs\n  File "/usr/lib/python3.6/site-packages/salt/modules/cmdmod.py", line 733, in _run\n    proc.stdout, encoding=output_encoding\nAttributeError: \'TimedProc\' object has no attribute \'stdout\'\n', 'out': 'nested', 'retcode': 1, 'jid': '20220608091703422445', 'fun': 'cmd.run_all', 'fun_args': [{'stdin': '#!/usr/bin/env python3\n\nimport sys,os\nsys.path.append(os.getcwd())\n\nimport logging\n\ndef create_logger():\n    logger = logging.getLogger()\n    \n    c_handler = logging.StreamHandler()\n\n    # Set logging level\n    logger.setLevel(logging.DEBUG)\n    c_handler.setLevel(logging.INFO)\n\n    # Add handlers to the logger\n    logger.addHandler(c_handler)\n\n    return logger\n\n\nif __name__ == \'__main__\':\n\n    logger = create_logger()\n\n    logger.info("Test1")    \n    logger.info("Test2\\n")    \n    logger.info("\\nTest3")  ', 'template': 'jinja', 'cmd': '{{grains.pythonexecutable}} -', 'timeout': 60}], 'master_id': 'salt-master'}
2022-06-08 11:17:03,866 [salt.transport.zeromq:179 ][DEBUG   ][27089] Closing AsyncZeroMQReqChannel instance
2022-06-08 11:17:04,614 [salt.utils.process:1230][DEBUG   ][27089] Subprocess ProcessPayload-Job-20220608091703422445 cleaned up
```

**Expected behavior**

To get the output of the script instead of an exception

**Comment by dwoz** [comment]
Fixed on all supported branches (3006.x/3007.x/3008.x/master) by 9da6764eb86 (`Convert stdin string to bytes regardless of stdin_raw_newlines`, Aug 2024, released in 3006.10). Root cause: on 3004.1 with `stdin_raw_newlines=True`, `TimedProc` skipped the `to_bytes()` conversion, so `process.communicate(input=<str>)` raised TypeError inside the receive thread — never set `self.stdout` — and `cmdmod._run` then blew up on `proc.stdout`. Closing.
