### ISSUE TITLE
[BUG] Issue with pip install of conflicting resources for Py 3.10 and Py 3.11

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt#62162]
**Description**
On platforms with Python 3.10 and 3.11.0b, pip resource management is showing conflicts between Salt and pyzmq.  This problem does not occur with Py 3.9 and lower.  The issue arose when testing Ubuntu 22.04 in salt-pkg due to requirements/py3.10/test.txt, but can be show simply as below:

Error:
```
ERROR: Cannot install -r ./test_req.txt (line 1) and pyzmq==21.0.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested pyzmq==21.0.2
    salt 3004 depends on pyzmq<=20.0.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

**Setup**
See below:

- [ ] on-prem machine
- [X] VM (**Virtualbox**, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
The issue in requirements/py3.10/test.txt can be pared down to the following:
```david@david-XPS-15-9570:~/test_req$ cat test_req.txt 
salt==3004
pyzmq==21.0.2
```
And run with the command:
```
pip3 install -v -r ./test_req.txt
```
The contents of requirements/py3.10/test.txt is essentially the same as requirements/py3.9/test.txt, for example:
```
pyzmq==21.0.2
    # via
    #   pytest-salt-factories
    #   salt
.
.
.
salt==3004
    # via -r requirements/tests.in
```
This is an issue with Ubuntu 22.04, Fedora 35 & 36 where Python 3.10 is the default.

From pip3 Error log:
```
Requirement already satisfied: Jinja2 in /home/david/.local/lib/python3.10/site-packages (from salt==3004->-r ./test_req.txt (line 1)) (3.1.2)
Given no hashes to check 1 links for project 'pyzmq': discarding no candidates
Given no hashes to check 0 links for project 'pyzmq': discarding no candidates
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pyzmq to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r ./test_req.txt (line 1) and pyzmq==21.0.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested pyzmq==21.0.2
    salt 3004 depends on pyzmq<=20.0.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
Exception information:
Traceback (most recent call last):
  File "/home/david/.local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 121, in resolve
    self._result = resolver.resolve(
  File "/home/david/.local/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 453, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/david/.local/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 357, in resolve
    raise ResolutionImpossible(causes)
pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=SpecifierRequirement('pyzmq==21.0.2'), parent=None), RequirementInformation(requirement=SpecifierRequirement('pyzmq<=20.0.0'), parent=LinkCandidate('file:///home/david/.cache/pip/wheels/99/9c/2c/64441892f02dfe925780a5bfce93e528be51c9bb6f5e064491/salt-3004-py3-none-any.whl'))]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/david/.local/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 223, in _main
    status = self.run(options, args)
  File "/home/david/.local/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "/home/david/.local/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 320, in run
    requirement_set = resolver.resolve(
  File "/home/david/.local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 127, in resolve
    six.raise_from(error, e)
  File "<string>", line 3, in raise_from
pip._internal.exceptions.DistributionNotFound: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
WARNING: You are using pip version 20.3.4; however, version 22.1.2 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
Removed build tracker: '/tmp/pip-req-tracker-t_ba4zze'
```

**Expected behavior**
Should not produce an error

**Versions Report**
<details><summary>pip 20.3.4 from /home/david/.local/lib/python3.10/site-packages/pip (python 3.10)
</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

</details>

**Additional context**

**Comment by dmurphy18** [comment]
Resolved by forcing the Salt desired version of pyzmq in the salt-pkg requirements/tests.in
```
pyzmq==20.0.0 ; python_version >= "3.10"
```
