### ISSUE TITLE
[BUG] yaml.lint fails with yamllint.config.YamlLintConfigError

### ISSUE THREAD

**Issue by max-arnold** [saltstack/salt#62238]
**Description**

The new (unreleased) `yaml.lint` execution function does not work on Ubuntu 20.04

**Setup**
  
* Ubuntu 20.04
* Latest Salt installed from git
* The yamllint version is the default one on Ubuntu 20.04: `1.20.0-1` (was installed via `apt install yamllint`)

**Steps to Reproduce the behavior**

```yaml
# phosphorus/foo.sls

foo:
  test.configurable_test_state:
    - changes: True
    - comment: A comment
```

```
salt-call yaml.lint salt://phosphorus/foo.sls

[ERROR   ] An un-handled exception was caught by Salt's global exception handler:
YamlLintConfigError: invalid config: unknown option "check-keys" for rule "truthy"
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    load_entry_point('salt==3003rc1+2349.g87f6189e58', 'console_scripts', 'salt-call')()
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/scripts.py", line 441, in salt_call
    client.run()
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/cli/call.py", line 50, in run
    caller.run()
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/cli/caller.py", line 95, in run
    ret = self.call()
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/cli/caller.py", line 202, in call
    ret["return"] = self.minion.executors[fname](
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/loader/lazy.py", line 1201, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/loader/lazy.py", line 1216, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/executors/direct_call.py", line 10, in execute
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/loader/lazy.py", line 1201, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/loader/lazy.py", line 1216, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/modules/yaml.py", line 56, in lint
    return __utils__["yamllint.lint"](yaml_out)
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/loader/lazy.py", line 1201, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/loader/lazy.py", line 1216, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/utils/yamllint.py", line 49, in lint
    conf = YamlLintConfig(yamlconf)
  File "/usr/lib/python3/dist-packages/yamllint/config.py", line 43, in __init__
    self.validate()
  File "/usr/lib/python3/dist-packages/yamllint/config.py", line 121, in validate
    self.rules[id] = validate_rule_conf(rule, self.rules[id])
  File "/usr/lib/python3/dist-packages/yamllint/config.py", line 149, in validate_rule_conf
    raise YamlLintConfigError(
yamllint.config.YamlLintConfigError: invalid config: unknown option "check-keys" for rule "truthy"
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    load_entry_point('salt==3003rc1+2349.g87f6189e58', 'console_scripts', 'salt-call')()
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/scripts.py", line 441, in salt_call
    client.run()
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/cli/call.py", line 50, in run
    caller.run()
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/cli/caller.py", line 95, in run
    ret = self.call()
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/cli/caller.py", line 202, in call
    ret["return"] = self.minion.executors[fname](
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/loader/lazy.py", line 1201, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/loader/lazy.py", line 1216, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/executors/direct_call.py", line 10, in execute
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/loader/lazy.py", line 1201, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/loader/lazy.py", line 1216, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/modules/yaml.py", line 56, in lint
    return __utils__["yamllint.lint"](yaml_out)
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/loader/lazy.py", line 1201, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/loader/lazy.py", line 1216, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt-3003rc1+2349.g87f6189e58-py3.8.egg/salt/utils/yamllint.py", line 49, in lint
    conf = YamlLintConfig(yamlconf)
  File "/usr/lib/python3/dist-packages/yamllint/config.py", line 43, in __init__
    self.validate()
  File "/usr/lib/python3/dist-packages/yamllint/config.py", line 121, in validate
    self.rules[id] = validate_rule_conf(rule, self.rules[id])
  File "/usr/lib/python3/dist-packages/yamllint/config.py", line 149, in validate_rule_conf
    raise YamlLintConfigError(
yamllint.config.YamlLintConfigError: invalid config: unknown option "check-keys" for rule "truthy"
```

Maybe a version-dependent config should be implemented? Or if that is too much hassle, then a minimal version check at the module's __init__()?

Based on https://github.com/saltstack/salt/pull/61183

Cc: @whytewolf

**Comment by whytewolf** [comment]
@max-arnold if you want to test the patch that pr should handle it. let me know if it works. I lowered the required version to 1.20.0 by removing the config that needed the updated version. I also added version checking. for anything older than 1.20.0

**Comment by max-arnold** [comment]
@whytewolf Thanks, it works as expected now!

Does the `yamlconf=None` argument exist to be able to provide a custom yamllint configuration file? I do not see any keyword arguments passed to the utils function besides the yaml file content.

**Comment by whytewolf** [comment]
So, that is for that functionality. it is for future use. I didn't get it into the module yet. it just exists within the utils function.
