### ISSUE TITLE
[BUG] taimat build 3005 - missing (built-in) python lib telnetlib - required for napalm/netmiko library

### ISSUE THREAD

**Issue by ITJamie** [saltstack/salt#62393]
**Description**
The built in python in salt tiamat rc3005 builds is missing telnetlib. 
this is required for some of the execution modules (netmiko, napalm)

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [x] VM (XEN)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
https://github.com/napalm-automation/napalm-salt/tree/master/saltstack - a quick example of a salt setup with napalm
install napalm with salt pip (salt-pip install napalm)
Attempt to start a salt proxy using the napalm driver (eg service saltproxy@veos using the above example salt code)

You will get errors about not being able to import napalm. 
to get to the root of the error. edit /opt/saltstack/salt/run/salt/proxy/napalm.py and add `import napalm` before  `import salt.utils.napalm`

This will give you the following output (truncated)
```
2022-07-28 17:10:14,527 [salt.loader.lazy :785 ][DEBUG   ][682339] Failed to import proxy napalm:
Traceback (most recent call last):
  File "salt/loader/lazy.py", line 768, in _load_module
    mod = self.run(spec.loader.load_module)
  File "salt/loader/lazy.py", line 1228, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "salt/loader/lazy.py", line 1243, in _run_as
    return _func_or_method(*args, **kwargs)
  File "<frozen importlib._bootstrap_external>", line 529, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1029, in load_module
  File "<frozen importlib._bootstrap_external>", line 854, in load_module
  File "<frozen importlib._bootstrap>", line 274, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/saltstack/salt/run/salt/proxy/napalm.py", line 162, in <module>
    import napalm
  File "/opt/saltstack/salt/pypath/lib/python3.9/site-packages/napalm/__init__.py", line 5, in <module>
    from napalm.base import get_network_driver
  File "/opt/saltstack/salt/pypath/lib/python3.9/site-packages/napalm/base/__init__.py", line 22, in <module>
    from napalm.base.base import NetworkDriver
  File "/opt/saltstack/salt/pypath/lib/python3.9/site-packages/napalm/base/base.py", line 17, in <module>
    from netmiko import ConnectHandler, NetMikoTimeoutException
  File "/opt/saltstack/salt/pypath/lib/python3.9/site-packages/netmiko/__init__.py", line 7, in <module>
    from netmiko.ssh_dispatcher import ConnectHandler
  File "/opt/saltstack/salt/pypath/lib/python3.9/site-packages/netmiko/ssh_dispatcher.py", line 2, in <module>
    from netmiko.a10 import A10SSH
  File "/opt/saltstack/salt/pypath/lib/python3.9/site-packages/netmiko/a10/__init__.py", line 1, in <module>
    from netmiko.a10.a10_ssh import A10SSH
  File "/opt/saltstack/salt/pypath/lib/python3.9/site-packages/netmiko/a10/a10_ssh.py", line 3, in <module>
    from netmiko.cisco_base_connection import CiscoSSHConnection
  File "/opt/saltstack/salt/pypath/lib/python3.9/site-packages/netmiko/cisco_base_connection.py", line 2, in <module>
    from netmiko.base_connection import BaseConnection
  File "/opt/saltstack/salt/pypath/lib/python3.9/site-packages/netmiko/base_connection.py", line 12, in <module>
    import telnetlib
ModuleNotFoundError: No module named 'telnetlib'
```

https://docs.python.org/3/library/telnetlib.html  - telnetlib is a built in library to python that appears to be missing in salt's python

**Expected behavior**
Able to start salt-proxy with napalm driver

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
Salt Version:
          Salt: 3005rc1

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.17
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.9.12 (main, Jul 20 2022, 19:54:18)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: debian 11 bullseye
        locale: utf-8
       machine: x86_64
       release: 5.10.0-12-amd64
        system: Linux
       version: Debian GNU/Linux 11 bullseye

```
</details>

**Additional context**

**Comment by ITJamie** [comment]
Nevermind. found this issue has been dealt with: https://github.com/saltstack/salt/issues/62362
