### ISSUE TITLE
[BUG] 3005rc2 - napalm not loading proxymodule (ValueError: invalid literal for int() with base 10: 'Not installed')

### ISSUE THREAD

**Issue by ITJamie** [saltstack/salt#62407]
**Description**
salt-proxy unable to load napalm

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [x] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
- Install 3005rc2
- salt-pip install napalm==4.0.0
- setup a proxy minion in salt pillar using napalm as the driver (eg https://github.com/napalm-automation/napalm-salt/blob/master/saltstack/pillar/veos.sls)
- start saltproxy and view logs (see below for error output)

**Expected behavior**
Napalm to load and salt-proxy to stay running

**Logs**
```
root@saltproxy:~# service salt-proxy@test-sw01-napalm start
root@saltproxy:~# service salt-proxy@test-sw01-napalm status
● salt-proxy@test-sw01-napalm.service - salt-proxy service for test-sw01-napalm
     Loaded: loaded (/lib/systemd/system/salt-proxy@.service; disabled; vendor preset: enabled)
     Active: active (running) since Tue 2022-08-02 10:42:35 UTC; 1s ago
       Docs: man:salt-proxy(1)
             file:///usr/share/doc/salt/html/contents.html
             https://docs.saltproject.io/en/latest/contents.html
   Main PID: 4177436 (/opt/saltstack/)
      Tasks: 3 (limit: 1036)
     Memory: 68.8M
        CPU: 1.315s
     CGroup: /system.slice/system-salt\x2dproxy.slice/salt-proxy@test-sw01-napalm.service
             ├─4177436 /opt/saltstack/salt/run/run proxy --proxyid=test-sw01-napalm
             └─4177440 /opt/saltstack/salt/run/run proxy --proxyid=test-sw01-napalm MultiMinionProcessManager MinionProcessManager

Aug 02 10:42:35 saltproxy.dev.39122.as systemd[1]: Started salt-proxy service for test-sw01-napalm.
root@saltproxy:~# tail -f /var/log/salt/proxy
    import salt.utils.napalm
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "salt/utils/napalm.py", line 38, in <module>
    NAPALM_MAJOR = int(napalm.__version__.split(".")[0])
ValueError: invalid literal for int() with base 10: 'Not installed'
2022-08-02 10:42:41,979 [test-sw01-napalm.salt.loaded.int.metaproxy.proxy:174 ][ERROR   ][4177440] Proxymodule napalm is missing an init() or a shutdown() or both. Check your proxymodule.  Salt-proxy aborted.
2022-08-02 10:42:41,980 [salt.cli.daemons :519 ][ERROR   ][4177440] Proxymodule napalm is missing an init() or a shutdown() or both. Check your proxymodule.  Salt-proxy aborted.
2022-08-02 10:42:55,777 [salt.loader.lazy :789 ][ERROR   ][4177552] Failed to import grains napalm, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "salt/loader/lazy.py", line 768, in _load_module
    mod = self.run(spec.loader.load_module)
  File "salt/loader/lazy.py", line 1228, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "salt/loader/lazy.py", line 1243, in _run_as
    return _func_or_method(*args, **kwargs)
  File "<frozen importlib._bootstrap_external>", line 529, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1029, in load_module
  File "<frozen importlib._bootstrap_external>", line 854, in load_module
  File "<frozen importlib._bootstrap>", line 274, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/saltstack/salt/run/salt/grains/napalm.py", line 22, in <module>
    import salt.utils.napalm
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "salt/utils/napalm.py", line 38, in <module>
    NAPALM_MAJOR = int(napalm.__version__.split(".")[0])
ValueError: invalid literal for int() with base 10: 'Not installed'
2022-08-02 10:42:58,196 [salt.loader.lazy :789 ][ERROR   ][4177552] Failed to import grains napalm, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "salt/loader/lazy.py", line 768, in _load_module
    mod = self.run(spec.loader.load_module)
  File "salt/loader/lazy.py", line 1228, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "salt/loader/lazy.py", line 1243, in _run_as
    return _func_or_method(*args, **kwargs)
  File "<frozen importlib._bootstrap_external>", line 529, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1029, in load_module
  File "<frozen importlib._bootstrap_external>", line 854, in load_module
  File "<frozen importlib._bootstrap>", line 274, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/saltstack/salt/run/salt/grains/napalm.py", line 22, in <module>
    import salt.utils.napalm
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "salt/utils/napalm.py", line 38, in <module>
    NAPALM_MAJOR = int(napalm.__version__.split(".")[0])
ValueError: invalid literal for int() with base 10: 'Not installed'
2022-08-02 10:42:58,304 [salt.loader.lazy :789 ][ERROR   ][4177552] Failed to import proxy napalm, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "salt/loader/lazy.py", line 768, in _load_module
    mod = self.run(spec.loader.load_module)
  File "salt/loader/lazy.py", line 1228, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "salt/loader/lazy.py", line 1243, in _run_as
    return _func_or_method(*args, **kwargs)
  File "<frozen importlib._bootstrap_external>", line 529, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1029, in load_module
  File "<frozen importlib._bootstrap_external>", line 854, in load_module
  File "<frozen importlib._bootstrap>", line 274, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/saltstack/salt/run/salt/proxy/napalm.py", line 162, in <module>
    import salt.utils.napalm
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "salt/utils/napalm.py", line 38, in <module>
    NAPALM_MAJOR = int(napalm.__version__.split(".")[0])
ValueError: invalid literal for int() with base 10: 'Not installed'
2022-08-02 10:42:58,578 [test-sw01-napalm.salt.loaded.int.metaproxy.proxy:174 ][ERROR   ][4177552] Proxymodule napalm is missing an init() or a shutdown() or both. Check your proxymodule.  Salt-proxy aborted.
2022-08-02 10:42:58,579 [salt.cli.daemons :519 ][ERROR   ][4177552] Proxymodule napalm is missing an init() or a shutdown() or both. Check your proxymodule.  Salt-proxy aborted.

```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
Salt Version:
          Salt: 3005rc2

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.17
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.9.13 (main, Jul 28 2022, 20:51:09)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: debian 11 bullseye
        locale: utf-8
       machine: x86_64
       release: 5.10.0-12-amd64
        system: Linux
       version: Debian GNU/Linux 11 bullseye
```
</details>

**Comment by s0undt3ch** [comment]
Next release of Salt, 3005rc3 or 3005 final, will have this issue fixed.
For more info, https://gitlab.com/saltstack/pop/tiamat-pip/-/blob/master/CHANGELOG.md#170-202285
