### ISSUE TITLE
[BUG] SALT-SSH: contextvars (Python 3.6.8 <--> Python: 3.10.4)

### ISSUE THREAD

**Issue by gray380** [saltstack/salt#62430]
**Description**
Salt host: Python: 3.10.4
Remote host: Python 3.6.8

test.ping faced the following issue:
```
ModuleNotFoundError: No module named '_contextvars'
ModuleNotFoundError: No module named 'typing_extensions'
```

**Setup**
Remote host:

- [ ] VM (VMware)
- [ ] OS: Oracle Linux Server release 8.6
  
**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

<details><summary>salt-ssh  'host*' test.ping</summary>

```bash
host:
    ----------
    retcode:
        1
    stderr:
        Traceback (most recent call last):
          File "/var/tmp/.as-s.somebody_4f1a73_salt/pyall/salt/loader/context.py", line 10, in <module>
            import _contextvars as contextvars
        ModuleNotFoundError: No module named '_contextvars'
        
        During handling of the above exception, another exception occurred:
        
        Traceback (most recent call last):
          File "/var/tmp/.as-s.somebody_4f1a73_salt/salt-call", line 27, in <module>
            salt_call()
          File "/var/tmp/.as-s.somebody_4f1a73_salt/pyall/salt/scripts.py", line 426, in salt_call
            import salt.cli.call
          File "/var/tmp/.as-s.somebody_4f1a73_salt/pyall/salt/cli/call.py", line 3, in <module>
            import salt.cli.caller
          File "/var/tmp/.as-s.somebody_4f1a73_salt/pyall/salt/cli/caller.py", line 14, in <module>
            import salt.loader
          File "/var/tmp/.as-s.somebody_4f1a73_salt/pyall/salt/loader/__init__.py", line 14, in <module>
            import salt.config
          File "/var/tmp/.as-s.somebody_4f1a73_salt/pyall/salt/config/__init__.py", line 101, in <module>
            _DFLT_IPC_WBUFFER = _gather_buffer_space() * 0.5
          File "/var/tmp/.as-s.somebody_4f1a73_salt/pyall/salt/config/__init__.py", line 89, in _gather_buffer_space
            import salt.grains.core
          File "/var/tmp/.as-s.somebody_4f1a73_salt/pyall/salt/grains/core.py", line 32, in <module>
            import salt.modules.cmdmod
          File "/var/tmp/.as-s.somebody_4f1a73_salt/pyall/salt/modules/cmdmod.py", line 31, in <module>
            import salt.utils.templates
          File "/var/tmp/.as-s.somebody_4f1a73_salt/pyall/salt/utils/templates.py", line 20, in <module>
            import salt.utils.jinja
          File "/var/tmp/.as-s.somebody_4f1a73_salt/pyall/salt/utils/jinja.py", line 21, in <module>
            import salt.fileclient
          File "/var/tmp/.as-s.somebody_4f1a73_salt/pyall/salt/fileclient.py", line 15, in <module>
            import salt.client
          File "/var/tmp/.as-s.somebody_4f1a73_salt/pyall/salt/client/__init__.py", line 33, in <module>
            import salt.payload
          File "/var/tmp/.as-s.somebody_4f1a73_salt/pyall/salt/payload.py", line 15, in <module>
            import salt.loader.context
          File "/var/tmp/.as-s.somebody_4f1a73_salt/pyall/salt/loader/context.py", line 13, in <module>
            import contextvars
          File "/var/tmp/.as-s.somebody_4f1a73_salt/py3/contextvars/__init__.py", line 4, in <module>
            import immutables
          File "/var/tmp/.as-s.somebody_4f1a73_salt/py3/immutables/__init__.py", line 18, in <module>
            from ._protocols import MapKeys as MapKeys
          File "/var/tmp/.as-s.somebody_4f1a73_salt/py3/immutables/_protocols.py", line 17, in <module>
            from typing_extensions import Protocol
        ModuleNotFoundError: No module named 'typing_extensions'
    stdout:
```
</details>

BTW, remote runs work as designed: `salt-ssh '*' -r 'pwd'` for instance.

Just for curiosity I've commented the following calls on the remote host:
/var/tmp/.as-s.somebody_4f1a73_salt/pyall/salt/loader/context.py
```
try:
    # Try the stdlib C extension first
    #import _contextvars as contextvars <-- commented
#except ImportError: <-- commented
    # Py<3.7
    import contextvars
```
The message `No module named '_contextvars'` has gone, but the following has appeared:
<details><summary>salt-ssh  'host*' test.ping</summary>

```bash
host:
    ----------
    retcode:
        1
    stderr:
        Traceback (most recent call last):
          File "/var/tmp/.as-s.somebody_4f1a73_salt/salt-call", line 27, in <module>
            salt_call()
          File "/var/tmp/.as-s.somebody_4f1a73_salt/pyall/salt/scripts.py", line 426, in salt_call
            import salt.cli.call
          File "/var/tmp/.as-s.somebody_4f1a73_salt/pyall/salt/cli/call.py", line 3, in <module>
            import salt.cli.caller
          File "/var/tmp/.as-s.somebody_4f1a73_salt/pyall/salt/cli/caller.py", line 14, in <module>
            import salt.loader
          File "/var/tmp/.as-s.somebody_4f1a73_salt/pyall/salt/loader/__init__.py", line 14, in <module>
            import salt.config
          File "/var/tmp/.as-s.somebody_4f1a73_salt/pyall/salt/config/__init__.py", line 101, in <module>
            _DFLT_IPC_WBUFFER = _gather_buffer_space() * 0.5
          File "/var/tmp/.as-s.somebody_4f1a73_salt/pyall/salt/config/__init__.py", line 89, in _gather_buffer_space
            import salt.grains.core
          File "/var/tmp/.as-s.somebody_4f1a73_salt/pyall/salt/grains/core.py", line 32, in <module>
            import salt.modules.cmdmod
          File "/var/tmp/.as-s.somebody_4f1a73_salt/pyall/salt/modules/cmdmod.py", line 31, in <module>
            import salt.utils.templates
          File "/var/tmp/.as-s.somebody_4f1a73_salt/pyall/salt/utils/templates.py", line 20, in <module>
            import salt.utils.jinja
          File "/var/tmp/.as-s.somebody_4f1a73_salt/pyall/salt/utils/jinja.py", line 21, in <module>
            import salt.fileclient
          File "/var/tmp/.as-s.somebody_4f1a73_salt/pyall/salt/fileclient.py", line 15, in <module>
            import salt.client
          File "/var/tmp/.as-s.somebody_4f1a73_salt/pyall/salt/client/__init__.py", line 33, in <module>
            import salt.payload
          File "/var/tmp/.as-s.somebody_4f1a73_salt/pyall/salt/payload.py", line 15, in <module>
            import salt.loader.context
          File "/var/tmp/.as-s.somebody_4f1a73_salt/pyall/salt/loader/context.py", line 15
            DEFAULT_CTX_VAR = "loader_ctxvar"
                          ^
        SyntaxError: invalid syntax
```
</details>
**Expected behavior**
`test.ping` and rest of the modules should work as deigned.

**Screenshots**

**Versions Report**
<details><summary>salt-ssh -V</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
Salt Version:
          Salt: 3004.2
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.4
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.15.0
        pygit2: Not Installed
        Python: 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0]
  python-gnupg: Not Installed
        PyYAML: 6.0
         PyZMQ: 20.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.3
 
System Versions:
          dist: pop 22.04 jammy
        locale: utf-8
       machine: x86_64
       release: 5.18.10-76051810-generic
        system: Linux
       version: Pop!_OS 22.04 jammy
```
</details>

**Additional context**

**Comment by OrangeDog** [comment]
Duplicate: #59942
