### ISSUE TITLE
[BUG] Windows 3005rc1 Traceback in kernelpkg_linux_yum.py

### ISSUE THREAD

**Issue by dafyddj** [saltstack/salt#62479]
**Description**

Traceback in kernelpkg_linux_yum.py
Output:
```
[ERROR   ] Failed to import module kernelpkg_linux_yum, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "C:\Program Files\Salt Project\Salt\bin\lib\site-packages\salt\loader\lazy.py", line 768, in _load_module
    mod = self.run(spec.loader.load_module)
  File "C:\Program Files\Salt Project\Salt\bin\lib\site-packages\salt\loader\lazy.py", line 1228, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "C:\Program Files\Salt Project\Salt\bin\lib\site-packages\salt\loader\lazy.py", line 1243, in _run_as
    return _func_or_method(*args, **kwargs)
  File "<frozen importlib._bootstrap_external>", line 522, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1022, in load_module
  File "<frozen importlib._bootstrap_external>", line 847, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Program Files\Salt Project\Salt\bin\Lib\site-packages\salt\modules\kernelpkg_linux_yum.py", line 26, in <modu
le>
    _yum = salt.utils.functools.namespaced_function(salt.modules.yumpkg._yum, globals())
AttributeError: module 'salt.modules' has no attribute 'yumpkg'
```

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Masterless install on **Windows** of `v3005rc1`

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

Call a function from the `pkg` module e.g.
`salt-call pkg.list_pkgs`

**Expected behavior**

No traceback

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
Salt Version:
          Salt: 3005rc1

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.7
     gitpython: 3.1.18
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: 1.1.4
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.10.1
        pygit2: Not Installed
        Python: 3.8.13 (tags/v3.8.13:ea67321, Jul  9 2022, 10:30:17) [MSC v.1929 64 bit (AMD64)]
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 19.0.0
         smmap: 4.0.0
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist:
        locale: cp1252
       machine: AMD64
       release: 8.1
        system: Windows
       version: 8.1 6.3.9600 SP0 Multiprocessor Free
```
</details>

**Additional context**
@twangboy

**Comment by MKLeb** [comment]
Hi @dafyddj, tried to reproduce this with your suggestion but was unable to.

**Comment by dafyddj** [comment]
@MKLeb I have tried this on several machines, fresh install and upgrade from `v3004.1` and the result is the same.
Could you post the exact steps you took to reproduce so that we can tease out any differences?

**Comment by Ch3LL** [comment]
closed by https://github.com/saltstack/salt/pull/62481
