### ISSUE TITLE
[BUG] Masterless setup suddently stopped working with 3005

### ISSUE THREAD

**Issue by Obbi89** [saltstack/salt#62553]
**Description**
Masterless setup causes endless logging and eventually fills up disk space.

I followed the guide on how to use a salt minion without a master.
This was working for a while now. I guess last update caused issues.

**Setup**
minion.d/masterless.conf
```yaml
file_client: local

file_roots:
  base:
    - /srv/salt

master_type: disable
pub_ret: False
```
Please be as specific as possible and give set-up details.

- [x] on-prem (my home (: ) machine
  
**Steps to Reproduce the behavior**

1. use config as printed above (otherwise clean install of salt-minion using debian repo)
2. start service through systemd
3. watch your hard drive going nuts

Follwing log excerpt is repeated as fast as the machine can produce and persist it to log files:

<details>

```log
Aug 27 16:16:45  salt-minion[14176]: Traceback (most recent call last):
Aug 27 16:16:45  salt-minion[14176]:   File "/usr/lib/python3/dist-packages/salt/minion.py", line 1134, in _connect_minion
Aug 27 16:16:45  salt-minion[14176]:     yield minion.connect_master(failed=failed)
Aug 27 16:16:45  salt-minion[14176]:   File "/usr/lib/python3/dist-packages/salt/ext/tornado/gen.py", line 1056, in run
Aug 27 16:16:45  salt-minion[14176]:     value = future.result()
Aug 27 16:16:45  salt-minion[14176]:   File "/usr/lib/python3/dist-packages/salt/ext/tornado/concurrent.py", line 249, in result
Aug 27 16:16:45  salt-minion[14176]:     raise_exc_info(self._exc_info)
Aug 27 16:16:45  salt-minion[14176]:   File "<string>", line 4, in raise_exc_info
Aug 27 16:16:45  salt-minion[14176]:   File "/usr/lib/python3/dist-packages/salt/ext/tornado/gen.py", line 1070, in run
Aug 27 16:16:45  salt-minion[14176]:     yielded = self.gen.send(value)
Aug 27 16:16:45  salt-minion[14176]:   File "/usr/lib/python3/dist-packages/salt/minion.py", line 1365, in connect_master
Aug 27 16:16:45  salt-minion[14176]:     self.req_channel = salt.transport.client.AsyncReqChannel.factory(
Aug 27 16:16:45  salt-minion[14176]:   File "/usr/lib/python3/dist-packages/salt/transport/client.py", line 83, in factory
Aug 27 16:16:45  salt-minion[14176]:     return salt.channel.client.AsyncReqChannel.factory(opts, **kwargs)
Aug 27 16:16:45  salt-minion[14176]:   File "/usr/lib/python3/dist-packages/salt/channel/client.py", line 127, in factory
Aug 27 16:16:45  salt-minion[14176]:     auth = salt.crypt.AsyncAuth(opts, io_loop=io_loop)
Aug 27 16:16:45  salt-minion[14176]:   File "/usr/lib/python3/dist-packages/salt/crypt.py", line 506, in __new__
Aug 27 16:16:45  salt-minion[14176]:     key = cls.__key(opts)
Aug 27 16:16:45  salt-minion[14176]:   File "/usr/lib/python3/dist-packages/salt/crypt.py", line 525, in __key
Aug 27 16:16:45  salt-minion[14176]:     opts["master_uri"],  # master ID
Aug 27 16:16:45  salt-minion[14176]: KeyError: 'master_uri'
Aug 27 16:16:45  salt-minion[14176]: [WARNING ] Master is set to disable, skipping connection
Aug 27 16:16:45  salt-minion[14176]: [CRITICAL] Unexpected error while connecting to salt
```

</details>

**Expected behavior**
The minion starts and serves it's configured states from local directory without filling up disk space.

**Versions Report**

<details>

```yaml
Salt Version:
          Salt: 3005
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.0.3
       libgit2: 1.3.0
      M2Crypto: Not Installed
          Mako: 1.1.3
       msgpack: 1.0.3
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.11.0
        pygit2: 1.8.0
        Python: 3.10.6 (main, Aug 10 2022, 11:19:32) [GCC 12.1.0]
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 22.3.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian testing bookworm
        locale: utf-8
       machine: x86_64
       release: 5.18.0-3-amd64
        system: Linux
       version: Debian GNU/Linux testing bookworm
```

</details>

**Additional context**
N/A

**Comment by twangboy** [comment]
Do you need to start a minion when running masterless? I assumed everything was done via `salt-call` when running masterless.

**Comment by whytewolf** [comment]
looks like the culprit is `master_type: disable`. which is running into the problem described in https://docs.saltproject.io/en/latest/ref/clients/index.html#salt-s-loader-interface 

i can't seem to find where the code changed that caused this though

**Comment by whytewolf** [comment]
@twangboy if you want engines or schedulers you do have to start a minion. that is what the `master_type: disable` option is for if you need to start the daemon. `salt-call` will work fine with just `file_client: local`. if you are not going to be using the persistent stuff such as engines or schedulers i would remove the `master_type: disable` and not start the daemon. but we also need to fix this for hose that do need to use those features in masterless.

**Comment by Ch3LL** [comment]
Fixed by https://github.com/saltstack/salt/pull/62582
