### ISSUE TITLE
[BUG] Salt-3004.2 failed to start

### ISSUE THREAD

**Issue by sastorsl** [saltstack/salt#62625]
**Description**
After patching of a RHEL7 server the salt-minion failed to start.
Repeated attempts to uninstall `salt` / `salt-minion` failed.

**Setup**
N/A

Please be as specific as possible and give set-up details.

- [X] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
`yum install salt-minion  # salt-3004.2`

**Expected behavior**
Salt to start and connect to the master.

**Screenshots**
```
Sep 06 13:45:59 my-server systemd[1]: Starting The Salt Minion...
Sep 06 13:45:59 my-server salt-minion[4042]: Traceback (most recent call last):
Sep 06 13:45:59 my-server salt-minion[4042]: File "/usr/bin/salt-minion", line 6, in <module>
Sep 06 13:45:59 my-server salt-minion[4042]: from pkg_resources import load_entry_point
Sep 06 13:45:59 my-server salt-minion[4042]: File "/opt/rh/rh-python38/root/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3252, in <module>
Sep 06 13:45:59 my-server salt-minion[4042]: def _initialize_master_working_set():
Sep 06 13:45:59 my-server salt-minion[4042]: File "/opt/rh/rh-python38/root/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
Sep 06 13:45:59 my-server salt-minion[4042]: f(*args, **kwargs)
Sep 06 13:45:59 my-server salt-minion[4042]: File "/opt/rh/rh-python38/root/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_m
Sep 06 13:45:59 my-server salt-minion[4042]: working_set = WorkingSet._build_master()
Sep 06 13:45:59 my-server salt-minion[4042]: File "/opt/rh/rh-python38/root/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
Sep 06 13:45:59 my-server salt-minion[4042]: ws.require(__requires__)
Sep 06 13:45:59 my-server salt-minion[4042]: File "/opt/rh/rh-python38/root/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
Sep 06 13:45:59 my-server salt-minion[4042]: needed = self.resolve(parse_requirements(requirements))
Sep 06 13:45:59 my-server salt-minion[4042]: File "/opt/rh/rh-python38/root/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
Sep 06 13:45:59 my-server salt-minion[4042]: raise DistributionNotFound(req, requirers)
Sep 06 13:45:59 my-server salt-minion[4042]: pkg_resources.DistributionNotFound: The 'salt==3004.2' distribution was not found and is required by the application
Sep 06 13:45:59 my-server systemd[1]: salt-minion.service: main process exited, code=exited, status=1/FAILURE
Sep 06 13:45:59 my-server systemd[1]: Failed to start The Salt Minion.

```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
Salt Version:
          Salt: 3004.2
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Aug 13 2020, 07:46:32)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4
 
System Versions:
          dist: rhel 7.9 Maipo
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-1160.76.1.el7.x86_64
        system: Linux
       version: Red Hat Enterprise Linux Server 7.9 Maipo
```
</details>

**Additional context**
The problem was local and is fixed.
Adding this bug report to help others down the line.

**Comment by sastorsl** [comment]
The solution was found after some time.
`salt` relies on `python3`, which on RHEL7 defaults to `python36`.

One of our engineers had installed `rh-python38.x86_64` and had replaced the `/bin/python3` symlink so it pointed to `/opt/rh/rh-python38/root/usr/bin/python3.8` instead of `/bin/python3.6`.

Updating the symlink - or in our case reinstalling `python36` resolved the issue.

`yum reinstall python36`
