### ISSUE TITLE
[BUG] import_json with absolute filepath broken in 3005

### ISSUE THREAD

**Issue by supfors** [saltstack/salt#62632]
**Description**
We use an orchestrate state that imports json files from a set location. This no longer works in salt 3005 whereas in previous salt versions it works as expected.

**Setup**
Salt-master/salt-minion 3005-1, tested on ubuntu20 and 22.

**Steps to Reproduce the behavior**
```
root@ubuntu22:~# cat /tmp/test.json
{"key": "value"}
```

**testorch.sls**
```
{% import_json "/tmp/test.json" as data %}

/tmp/data.txt:
  file.managed:
    - contents: >-
                {{ data }}
```

```
root@ubuntu22:~# salt-run state.orch testorch -ldebug
[DEBUG   ] Could not find file 'salt://tmp/test.json' in saltenv 'base'
[DEBUG   ] Jinja Error
[DEBUG   ] Exception:
Traceback (most recent call last):
  File "salt/utils/templates.py", line 469, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "jinja2/environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "salt/utils/jinja.py", line 221, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /tmp/test.json

---
localhost_master:
    Data failed to compile:
----------
    Rendering SLS 'base:testorch' failed: Jinja error: /tmp/test.json
Traceback (most recent call last):
  File "salt/utils/templates.py", line 469, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "jinja2/environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "salt/utils/jinja.py", line 221, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /tmp/test.json
```

**Expected behavior**
I expect salt to import the content of my file.

**Versions Report**

```yaml
Salt Version:
          Salt: 3005
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.2
     docker-py: 5.0.3
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: 1.5.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: 1.10.1
        Python: 3.9.13 (main, Aug 23 2022, 18:31:15)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: ubuntu 22.04 jammy
        locale: utf-8
       machine: x86_64
       release: 5.15.0-47-generic
        system: Linux
       version: Ubuntu 22.04 jammy
```
</details>

**Additional context**
* When using salt 3004 or previous versions this is working as I expect:

```
[DEBUG   ] Could not find file 'salt://tmp/test.json' in saltenv 'base'
[PROFILE ] Time (in seconds) to render import_json '/tmp/test.json': 0.0028154850006103516
[PROFILE ] Time (in seconds) to render '/var/cache/salt/master/files/base/testorch.sls' using 'jinja' renderer: 0.02628469467163086
[DEBUG   ] Rendered data from file: /var/cache/salt/master/files/base/testorch.sls:


localhost_master:
  Name: /tmp/data.txt - Function: file.managed - Result: Clean Started: - 09:49:18.532801 Duration: 18.633 ms

Summary for localhost_master
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:  18.633 ms
```
* `import_yaml` renders a similar error.

**Comment by iaingeorgeson** [comment]
We're seeing a similar issue with import_text. This started on upgrading to 3005.

```
          ID: bareos-etc-bareos-pki-combo-file
    Function: file.managed
        Name: /etc/bareos/pki/combo.pem
      Result: False
     Comment: Unable to manage file: Jinja error: /etc/bareos/pki/key.pem
              Traceback (most recent call last):
                File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 469, in render_jinja_tmpl
                  output = template.render(**decoded_context)
                File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
                  self.environment.handle_exception()
                File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
                  reraise(*rewrite_traceback_stack(source=source))
                File "/usr/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
                  raise value.with_traceback(tb)
                File "<template>", line 1, in top-level template code
                File "/usr/lib/python3.6/site-packages/salt/utils/jinja.py", line 221, in get_source
                  raise TemplateNotFound(template)
              jinja2.exceptions.TemplateNotFound: /etc/bareos/pki/key.pem
              
              ; line 1
              
              ---
              {% import_text key as key %}{% import_text cert as cert %}{{key}}    <======================
              {{cert}}
              
              Traceback (most recent call last):
                File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 469, in render_jinja_tmpl
                  output = template.render(**decoded_context)
              [...]
```

**Comment by nicholasmhughes** [comment]
closing in favor of #62611 . please add any additional comments there.
