### ISSUE TITLE
[BUG] v3005 on rhel7 cannot import shadow module when fips=1

### ISSUE THREAD

**Issue by neutronscott** [saltstack/salt#62643]
**Description**
When in FIPS mode Red Hat Enterprise Linux 7 cannot load shadow module. This makes user.present unable to check many attributes for changes.

**Setup**
rhel7 with fips=1
  
**Steps to Reproduce the behavior**
```
[root@rhel7 ~]# salt-call shadow.default_hash
'shadow.default_hash' is not available.
```

**Expected behavior**
```
[root@rhel8 ~]# salt-call shadow.default_hash
local:
    !
```

**Versions Report**
<details><summary>salt --versions-report</summary>

```yaml
Salt Version:
          Salt: 3005

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.9.13 (main, Aug 23 2022, 18:33:07)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: rhel 7.9 Maipo
        locale: utf-8
       machine: x86_64
       release: 3.10.0-1160.76.1.el7.x86_64
        system: Linux
       version: Red Hat Enterprise Linux Server 7.9 Maipo
```
</details>

**Additional context**

Unsure why but this does not effect rhel8 systems with fips=1 because glibc still sets errno EPERM. CPython must have been patched?

```
2022-09-08 14:43:09,806 [salt.state       :4148][CRITICAL][28263] Rendering SLS 'base:apps.saltstack.minion' failed: Jinja error: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "salt/utils/templates.py", line 469, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "jinja2/environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 16, in top-level template code
  File "jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
  File "salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "salt/loader/lazy.py", line 1228, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "salt/loader/lazy.py", line 1243, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/opt/saltstack/salt/run/salt/modules/test.py", line 427, in provider
    for key in __salt__:
  File "salt/loader/context.py", line 97, in __iter__
    return self.value().__iter__()
  File "salt/utils/lazy.py", line 117, in __iter__
    self._load_all()
  File "salt/loader/lazy.py", line 1082, in _load_all
    self._load_module(name)
  File "salt/loader/lazy.py", line 768, in _load_module
    mod = self.run(spec.loader.load_module)
  File "salt/loader/lazy.py", line 1228, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "salt/loader/lazy.py", line 1243, in _run_as
    return _func_or_method(*args, **kwargs)
  File "<frozen importlib._bootstrap_external>", line 529, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1029, in load_module
  File "<frozen importlib._bootstrap_external>", line 854, in load_module
  File "<frozen importlib._bootstrap>", line 274, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/saltstack/salt/run/salt/modules/bsd_shadow.py", line 22, in <module>
    import salt.utils.pycrypto
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "salt/utils/pycrypto.py", line 26, in <module>
    import crypt
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "crypt.py", line 117, in <module>
  File "crypt.py", line 94, in _add_method
  File "crypt.py", line 82, in crypt
PermissionError: [Errno 1] Operation not permitted

```

**Comment by neutronscott** [comment]
This affects all modules that import pycrypto, which imports crypt. Couldn't cleanly workaround this one. Modifications to salt.utils.pycrypto to catch PermissionError didn't seem to stick. I guess it's frozen?

**Comment by dwoz** [comment]
Fixed by 1c1dd0062a3 ("Handle PermissionError when importing crypt when FIPS is enabled.", Aug 2022) — present on 3006.x, 3007.x, 3008.x, master. 3005 is EOL. Closing.
