### ISSUE TITLE
[BUG] file.py _get_flags issue 

### ISSUE THREAD

**Issue by leifliddy** [saltstack/salt#62676]
**Description**
Running a simple salt file state results in failure. 
given /srv/salt/dnf-test.sls 

dnf_default_yes:
  file.append:
    - name: /etc/dnf/dnf.conf
    - text: 
      - defaultyes=True

**Setup**
Tested on a physical machine running Fedora 37, python 3.11, and salt v3005 (installed via the Fedora repo)

**Steps to Reproduce the behavior**
Create the following file:
```
/srv/salt/dnf-test.sls 

dnf_default_yes:
  file.append:
    - name: /etc/dnf/dnf.conf
    - text: 
      - defaultyes=True
```
Then run ```salt-call state.sls dnf-test```

This will result in the following error:
```
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/salt/state.py", line 2276, in call
    ret = self.states[cdata["full"]](
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/salt/loader/lazy.py", line 1228, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/salt/loader/lazy.py", line 1243, in _run_as
    return _func_or_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/salt/loader/lazy.py", line 1276, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/salt/states/file.py", line 6431, in append
    if __salt__["file.search"](
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/salt/loader/lazy.py", line 1228, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/salt/loader/lazy.py", line 1243, in _run_as
    return _func_or_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/salt/modules/file.py", line 3141, in search
    return replace(
           ^^^^^^^^
  File "/usr/lib/python3.11/site-packages/salt/modules/file.py", line 2516, in replace
    flags_num = _get_flags(flags)
                ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/salt/modules/file.py", line 1643, in _get_flags
    _flag = getattr(re, str(flag).upper())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 're' has no attribute 'RE.MULTILINE'
```

**Expected behavior**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
Salt Version:
          Salt: 3005
 
Dependency Versions:
          cffi: 1.15.1
      cherrypy: Not Installed
      dateutil: 2.8.2
     docker-py: Not Installed
         gitdb: 4.0.9
     gitpython: 3.1.27
        Jinja2: 3.0.3
       libgit2: 1.3.1
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.4
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.15.0
        pygit2: 1.7.1
        Python: 3.11.0rc1 (main, Aug  9 2022, 00:00:00) [GCC 12.1.1 20220628 (Red Hat 12.1.1-3)]
  python-gnupg: Not Installed
        PyYAML: 6.0
         PyZMQ: 23.2.0
         smmap: 5.0.0
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: fedora 37 Thirty Seven Prerelease
        locale: utf-8
       machine: x86_64
       release: 5.19.8-300.fc37.x86_64
        system: Linux
       version: Fedora Linux 37 Thirty Seven Prerelease

```
</details>

**Comment by leifliddy** [comment]
Will submit a PR shortly to resolve this.

**Comment by OrangeDog** [comment]
The cause is [this change in Python 3.11](https://docs.python.org/3.11/whatsnew/3.11.html#enum):

> `global_enum added – enum decorator to adjust __repr__ and __str__ to show members in the global context – see re.RegexFlag for an example.`

which means that `str(re.MULTILINE)` changes from `"MULTILINE"` to `"re.MULTILINE"`.

**Comment by hartwork** [comment]
@OrangeDog were you able to reproduce the difference in practice? Any ideas why I get identical results for 3.10 and 3.11?:
```console
# python3.10 --version
Python 3.10.8

# python3.10 -c 'import re; print(re.MULTILINE)'
re.MULTILINE

# python3.11 --version
Python 3.11.0

# python3.11 -c 'import re; print(re.MULTILINE)'
re.MULTILINE
```

**Comment by marmarek** [comment]
When is planned next release (3005.2?) with this bug fixed? It makes salt pretty much unusable on systems with Python 3.11 (at least Fedora 37 and Debian bookworm) and new release would help solving this situation.

**Comment by hartwork** [comment]
@marmarek I agree on unusable and 3005.1 is near four months old now. Probably asking for 3005.2 needs a dedicated issue to be visible.

**Comment by nkuttler** [comment]
Fwiw

`sed -i 's#str(flag).upper#str(flag).replace("re.", "").upper#' /path/to/dist-packages/salt/modules/file.py`
