### ISSUE TITLE
[BUG] Engine 'reactor' could not be started! for masterless minion

### ISSUE THREAD

**Issue by Anthonyhawkins** [saltstack/salt#62695]
**Description**
When running a masterless salt-minion in daemon mode and configuring it with a reactor engine, the salt-minion will fail to execute the reactor engine due to a `[CRITICAL] Engine 'reactor' could not be started!
` caused by a `RuntimeError("IOLoop is already running")` exception. 

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [X] VM (vSphere VM )
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [X] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**

masterless config
```yaml
master_type: disable
file_client: local
file_roots:
  base:
    - /srv/salt
```
reactor config
```yaml
######        Reactor Settings        #####
###########################################
# Define a salt reactor. See https://docs.saltproject.io/en/latest/topics/reactor/
engines:
  - reactor:
      refresh_interval: 60
      worker_threads: 10
      worker_hwm: 10000
reactor:
  - foobar:
    - /srv/reactor/ping.sls

#Set the TTL for the cache of the reactor configuration.
#reactor_refresh_interval: 60

#Configure the number of workers for the runner/wheel in the reactor.
#reactor_worker_threads: 10

#Define the queue size for workers in the reactor.
#reactor_worker_hwm: 10000
```
reactor sls
```yaml
#/srv/reactor/ping.sls
try-this:
  caller.test.ping:
    - tgt: {{ data['id'] }}
```

1. Setup config for masterless salt-minion, and start the salt-minion in debug mode with `salt-minion -l debug`
2. fire an event `salt-call --local event.fire '{"data":"my event data", "id": "ech-10-157-152-34"}' 'foobar'`

**Expected behavior**
Upon firing an event to the salt-minion, I expect the reactor to pick up on tag `foobar` and execute the reactor `ping.sls` state using the `caller` reactor type.

**Additional context**
Seems to be related to https://github.com/saltstack/salt/issues/57702
I looked for any hanging processes but multiple restarts/kills did not resolve the issue.  

**Logs**
```
[DEBUG   ] Minion of 'salt' is handling event tag 'foobar'
[DEBUG   ] Gathering reactors for tag foobar
[DEBUG   ] Compiling reactions for tag foobar
[DEBUG   ] compile template: /srv/reactor/ping.sls
[DEBUG   ] Jinja search path: ['/var/cache/salt/minion/files/base']
[DEBUG   ] Using importlib_metadata to load entry points
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[DEBUG   ] Updating roots fileserver cache
[PROFILE ] Time (in seconds) to render '/srv/reactor/ping.sls' using 'jinja' renderer: 0.06196117401123047
[DEBUG   ] Rendered data from file: /srv/reactor/ping.sls:
try-this:
  caller.test.ping:
    - tgt: ech-10-157-152-34

[DEBUG   ] Results of YAML rendering:
OrderedDict([('try-this', OrderedDict([('caller.test.ping', [OrderedDict([('tgt', 'ech-10-157-152-34')])])]))])
[PROFILE ] Time (in seconds) to render '/srv/reactor/ping.sls' using 'yaml' renderer: 0.0011010169982910156
[DEBUG   ] Reactor is populating caller client cache
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Including configuration from '/etc/salt/minion.d/local.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/local.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: ech-10-157-152-34
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Including configuration from '/etc/salt/minion.d/local.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/local.conf
[DEBUG   ] Override  __utils__: <module 'salt.loaded.int.grains.zfs' from '/usr/lib/python3.6/site-packages/salt/grains/zfs.py'>
[DEBUG   ] Elapsed time getting FQDNs: 0.11955451965332031 seconds
[DEBUG   ] LazyLoaded zfs.is_supported
[DEBUG   ] Closing IPCMessageSubscriber instance
[ERROR   ] An un-handled exception from the multiprocessing process 'Reactor-1:2:1' was caught:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/process.py", line 1034, in wrapped_run_func
    return run_func()
  File "/usr/lib/python3.6/site-packages/salt/utils/reactor.py", line 280, in run
    self.call_reactions(chunks)
  File "/usr/lib/python3.6/site-packages/salt/utils/reactor.py", line 202, in call_reactions
    self.wrap.run(chunk)
  File "/usr/lib/python3.6/site-packages/salt/utils/reactor.py", line 344, in run
    self.populate_client_cache(low)
  File "/usr/lib/python3.6/site-packages/salt/utils/reactor.py", line 337, in populate_client_cache
    self.opts["conf_file"]
  File "/usr/lib/python3.6/site-packages/salt/client/__init__.py", line 2171, in __init__
    self.sminion = salt.minion.SMinion(self.opts)
  File "/usr/lib/python3.6/site-packages/salt/minion.py", line 934, in __init__
    io_loop.run_sync(lambda: self.eval_master(self.opts, failed=True))
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/ioloop.py", line 454, in run_sync
    self.start()
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/ioloop.py", line 757, in start
    raise RuntimeError("IOLoop is already running")
RuntimeError: IOLoop is already running
[CRITICAL] Engine 'reactor' could not be started!
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/engines/__init__.py", line 106, in run
    self.engine[self.fun](**kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1201, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
    return callable(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1216, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/engines/reactor.py", line 31, in start
    salt.utils.reactor.Reactor(__opts__).run()
  File "/usr/lib/python3.6/site-packages/salt/utils/process.py", line 1034, in wrapped_run_func
    return run_func()
  File "/usr/lib/python3.6/site-packages/salt/utils/reactor.py", line 280, in run
    self.call_reactions(chunks)
  File "/usr/lib/python3.6/site-packages/salt/utils/reactor.py", line 202, in call_reactions
    self.wrap.run(chunk)
  File "/usr/lib/python3.6/site-packages/salt/utils/reactor.py", line 344, in run
    self.populate_client_cache(low)
  File "/usr/lib/python3.6/site-packages/salt/utils/reactor.py", line 337, in populate_client_cache
    self.opts["conf_file"]
  File "/usr/lib/python3.6/site-packages/salt/client/__init__.py", line 2171, in __init__
    self.sminion = salt.minion.SMinion(self.opts)
  File "/usr/lib/python3.6/site-packages/salt/minion.py", line 934, in __init__
    io_loop.run_sync(lambda: self.eval_master(self.opts, failed=True))
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/ioloop.py", line 454, in run_sync
    self.start()
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/ioloop.py", line 757, in start
    raise RuntimeError("IOLoop is already running")
RuntimeError: IOLoop is already running
[DEBUG   ] Process <class 'salt.engines.Engine'> (123298) died with exit status 0, restarting...
[DEBUG   ] Started 'salt.engines.<class 'type'>.Engine' with pid 123677
[DEBUG   ] Using importlib_metadata to load entry points
[DEBUG   ] LazyLoaded reactor.start
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Including configuration from '/etc/salt/minion.d/local.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/local.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: ech-10-157-152-34
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Including configuration from '/etc/salt/minion.d/local.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/local.conf
[DEBUG   ] Override  __utils__: <module 'salt.loaded.int.grains.zfs' from '/usr/lib/python3.6/site-packages/salt/grains/zfs.py'>
[DEBUG   ] Elapsed time getting FQDNs: 0.11946821212768555 seconds
[DEBUG   ] LazyLoaded zfs.is_supported
[DEBUG   ] Using importlib_metadata to load entry points
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_fa1ee940dd_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_fa1ee940dd_pull.ipc
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3004.2

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Mar  9 2021, 15:08:44)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4

System Versions:
          dist: ol 7.8 n/a
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-1127.el7.x86_64
        system: Linux
       version: Oracle Linux Server 7.8 n/a```
</details>

**Comment by Anthonyhawkins** [comment]
For additional context, I do not have this issue when using salt 3005.v (classic packaging) once this patch is applied: https://github.com/saltstack/salt/pull/62582/commits/450eeaf7a5555a5d4e4260365af9ad2e840ca5de

**Comment by dwoz** [comment]
Cannot reproduce on any currently-supported branch (3006.x / 3007.x / 3008.x / master).

The reported traceback in 3004.2 was `SMinion.__init__` unconditionally calling `eval_master()` inside a running IOLoop (Reactor -> `populate_client_cache` -> `salt.client.Caller` -> `SMinion`). Since c8dae4b (`use_master_when_local`), `SMinion.__init__` skips `eval_master()` when `file_client == 'local'` and `use_master_when_local` is False — the exact masterless config in the report. Verified with a pytest reproduction of the configured masterless minion + caller reactor: `populate_client_cache({'state': 'caller'})` returns cleanly, no `RuntimeError: IOLoop is already running`.

Closing. Please reopen with a fresh repro against a supported release if it recurs.
