### ISSUE TITLE
[BUG] Onedir minion grain cannot find ethtool binary at /usr/sbin/ethtool

### ISSUE THREAD

**Issue by frebib** [saltstack/salt#62789]
**Description**
We have a custom grain that invokes `ethtool` to collect network interface data. With a standard minion installation this works fine, but for some reason fails with a onedir minion:
```
[TRACE   ] Loading interfaces.interfaces grain
[DEBUG   ] Setting environment variable 'LD_LIBRARY_PATH' to an empty string
[DEBUG   ] Setting environment variable 'LD_LIBRARY_PATH' to an empty string
[DEBUG   ] Setting environment variable 'LD_LIBRARY_PATH' to an empty string
[DEBUG   ] Setting environment variable 'LD_LIBRARY_PATH' to an empty string
[DEBUG   ] Setting environment variable 'LD_LIBRARY_PATH' to an empty string
[DEBUG   ] Setting environment variable 'LD_LIBRARY_PATH' to an empty string
[DEBUG   ] Setting environment variable 'LD_LIBRARY_PATH' to an empty string
[CRITICAL] Failed to load grains defined in grain file interfaces.interfaces in function <LoadedFunc name='interfaces.interfaces'>, error:
Traceback (most recent call last):
  File "salt/loader/__init__.py", line 1150, in grains
    ret = funcs[key](**kwargs)
  File "salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "salt/loader/lazy.py", line 1228, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "salt/loader/lazy.py", line 1243, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/var/cache/salt/minion/extmods/grains/interfaces.py", line 77, in interfaces
    subprocess.check_output(["ethtool", "--driver", iface_name])
  File "subprocess.py", line 424, in check_output
  File "subprocess.py", line 505, in run
  File "salt/utils/pyinstaller/rthooks/_overrides.py", line 65, in __init__
    super().__init__(*args, **kwargs)
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1821, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'ethtool'
```
Logs captured from the output of `sudo salt-call --local grains.items -l all`

`ethtool` is present:
```
jgroocock@133m11:~$ sudo which ethtool
/usr/sbin/ethtool
```
And running the integrated Python shell works just fine, but not when using `subprocess`
```
jgroocock@133m11:~$ sudo /opt/saltstack/salt/run shell
oPython 3.9.14 (main, Sep 30 2022, 15:34:23)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> import salt.modules.cmdmod
>>> salt.modules.cmdmod.run(['ethtool'])
'ethtool: bad command line argument(s)\nFor more information run ethtool -h'
>>> os.environ["PATH"]
'/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
>>>
>>> import subprocess
>>> subprocess.check_output(["ethtool", "--driver", "eth0"])
Traceback (most recent call last):
  File "code.py", line 90, in runcode
  File "<console>", line 1, in <module>
  File "subprocess.py", line 424, in check_output
  File "subprocess.py", line 505, in run
  File "salt/utils/pyinstaller/rthooks/_overrides.py", line 65, in __init__
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1821, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'ethtool'
>>>
```

**Setup**
With this being a Debian system, `/usr/sbin` is only in the `$PATH` of root, if that matters.

- [x] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [x] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
The grain `interfaces.py`: https://gist.githubusercontent.com/frebib/73639ea1acdbac34542cc4279cab7330/raw
See logs above

**Expected behavior**
The grain is able to find ethtool.

**Versions Report**
```
Salt Version:
          Salt: 3005-cf32.gb5d459a15c

Dependency Versions:
          cffi: 1.15.1
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
      M2Crypto: 0.38.0
          Mako: Not Installed
       msgpack: 1.0.4
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.15.0
        pygit2: Not Installed
        Python: 3.9.14 (main, Sep 30 2022, 15:34:23)
  python-gnupg: Not Installed
        PyYAML: 6.0
         PyZMQ: 20.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.3

System Versions:
          dist: debian 11 bullseye
        locale: utf-8
       machine: x86_64
       release: 5.15.59-cloudflare-2022.8.0
        system: Linux
       version: Debian GNU/Linux 11 bullseye

```
</details>

**Additional context**
N/A

**Comment by frebib** [comment]
Looks like `/usr/sbin` is not in the `$PATH` according to
```
jgroocock@133m11:~$ /opt/saltstack/salt/run shell
Python 3.9.14 (main, Sep 30 2022, 15:34:23)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> import salt.modules.cmdmod
>>> salt.modules.cmdmod.run(['ethtool'])
Traceback (most recent call last):
  File "salt/modules/cmdmod.py", line 708, in _run
  File "salt/utils/timed_subprocess.py", line 53, in __init__
  File "salt/utils/pyinstaller/rthooks/_overrides.py", line 65, in __init__
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1821, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'ethtool'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "code.py", line 90, in runcode
  File "<console>", line 1, in <module>
  File "salt/modules/cmdmod.py", line 1265, in run
  File "salt/modules/cmdmod.py", line 715, in _run
salt.exceptions.CommandExecutionError: Unable to run command '['ethtool']' with the context {<snip>..., 'LC_TIME': 'C', 'PATH': '/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games', <snip>, 'LD_LIBRARY_PATH': ''}, 'stdin': None, 'stdout': -1, 'stderr': -2, 'with_communicate': True, 'timeout': None, 'bg': False, 'close_fds': True}', reason: [Errno 2] No such file or directory: 'ethtool'
```

**Comment by frebib** [comment]
Indeed it is, thanks! Backported 🔁
