### ISSUE TITLE
[BUG] Vault Integration is broken with saltstack version 3004.2

### ISSUE THREAD

**Issue by devopssankar** [saltstack/salt#62894]
**Description**
python2 based salt-minions are able to read vault secrets successfully and below exceptions occurs only for python3 salt-minions

    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python3.7/site-packages/salt/minion.py", line 1913, in _thread_return
        function_name, function_args, executors, opts, data
      File "/usr/lib/python3.7/site-packages/salt/minion.py", line 1869, in _execute_job_function
        return_data = self.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/python3.7/site-packages/salt/loader/lazy.py", line 149, in __call__
        return self.loader.run(run_func, *args, **kwargs)
      File "/usr/lib/python3.7/site-packages/salt/loader/lazy.py", line 1201, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "/usr/lib/python3.7/site-packages/salt/loader/lazy.py", line 1216, in _run_as
        return _func_or_method(*args, **kwargs)
      File "/usr/lib/python3.7/site-packages/salt/executors/direct_call.py", line 10, in execute
        return func(*args, **kwargs)
      File "/usr/lib/python3.7/site-packages/salt/loader/lazy.py", line 149, in __call__
        return self.loader.run(run_func, *args, **kwargs)
      File "/usr/lib/python3.7/site-packages/salt/loader/lazy.py", line 1201, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "/usr/lib/python3.7/site-packages/salt/loader/lazy.py", line 1216, in _run_as
        return _func_or_method(*args, **kwargs)
      File "/usr/lib/python3.7/site-packages/salt/modules/vault.py", line 214, in read_secret
        version2 = __utils__["vault.is_v2"](path)
      File "/usr/lib/python3.7/site-packages/salt/loader/context.py", line 78, in __getitem__
        return self.value()[item]
      File "/usr/lib/python3.7/site-packages/salt/loader/lazy.py", line 334, in __getitem__
        super().__getitem__(item)  # try to get the item from the dictionary
      File "/usr/lib/python3.7/site-packages/salt/utils/lazy.py", line 105, in __getitem__
        raise KeyError(key)
    KeyError: 'vault.is_v2'

**Setup**

Salt Version:
          Salt: 3004.2

Dependency Versions:
          cffi: 1.15.1
      cherrypy: unknown
      dateutil: 2.8.2
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.7.2
       libgit2: 1.5.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: 1.10.1
        Python: 3.7.10 (default, Jun  3 2021, 00:02:01)
  python-gnupg: Not Installed
        PyYAML: 4.2
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.3

System Versions:
          dist: amzn 2
        locale: UTF-8
       machine: x86_64
       release: 4.14.287-215.504.amzn2.x86_64
        system: Linux
       version: Amazon Linux 2

**Comment by OrangeDog** [comment]
What causes this exception? What command are you running on the minion?

Are there any previous errors in the log(s)?

**Comment by garethgreenaway** [comment]
@devopssankar Can you test this on the latest version of Salt?  If the issue still exists please open a new issue.  Thanks!
