### ISSUE TITLE
Py renderer is broken

### ISSUE THREAD

**Issue by djal** [saltstack/salt#62918]
### Setup
state.sls:
```
py-renderer:
  file.managed:
    - name: /tmp/py-renderer
    - source: salt://{{ slspath }}/py-file
    - template: py
    - encoding: utf_8
```
py-file:
```
#!py

def run():
    print("Ooops")
```

And after `state.apply` I get on master:
```
The State execution failed to record the order in which all states were executed. The state return missing data is:
{'changes': {},
 'comment': "An exception occurred in this state: 'Changes' should be a "
            'dictionary.',
 'name': 'later',
 'result': False}
----------
          ID: py-renderer
    Function: file.managed
        Name: /tmp/py-renderer
      Result: False
     Comment: An exception occurred in this state: 'Changes' should be a dictionary.
     Changes:   
```
And in minion log:
```
[salt.state       :321 ][ERROR   ][367648] (False, 'Traceback (most recent call last):\n  File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 693, in py\n    target.write(salt.utils.stringutils.to_str(data))\n  File "/usr/lib/python3.6/site-packages/salt/utils/stringutils.py", line 91, in to_str\n    raise TypeError("expected str, bytes, or bytearray not {}".format(type(s)))\nTypeError: expected str, bytes, or bytearray not <class \'NoneType\'>\n')
```
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
          Salt: 3005.1
 
Dependency Versions:
          cffi: 1.11.5
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: 4.0.1
     gitpython: 3.0.9
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.14
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Apr 12 2022, 06:55:39)
  python-gnupg: Not Installed
        PyYAML: 3.12
         PyZMQ: 20.0.0
         smmap: 3.0.1
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: rocky 8.6 Green Obsidian
        locale: UTF-8
       machine: x86_64
       release: 4.18.0-372.9.1.el8.x86_64
        system: Linux
       version: Rocky Linux 8.6 Green Obsidian
```

**Comment by djal** [comment]
I should use `return` in py-file not `print()`
Close it please.
