### ISSUE TITLE
Syndication broken in 3005

### ISSUE THREAD

**Issue by viktordaniel** [saltstack/salt#62933]
### Description of Issue
Salt syndication is broken after update to 3005
### Setup
master of masters -> syndic -> minions

### Steps to Reproduce Issue
salt minion_behind_syndic test.ping lead to timeout. 

Testet using vagrant demo environment: 
https://docs.saltproject.io/en/getstarted/fundamentals/index.html 
changed minion1 to act as syndic and minion2 to connect to minion1 as a master. deleted all keys, accepted new. The minion2 is able to receive command from master, sends a return, but syndic is unable to push back to master: 

```
[DEBUG   ] PubChannel received: {'enc': 'aes', 'load': {'fun': 'test.ping', 'arg': [], 'tgt': '*', 'jid': '20221021074351768582', 'ret': '', 'tgt_type': 'glob', 'user': 'sudo_vagrant'}, 'sig': b"T\x19\x14\xd0Z\x99\xc7\xba\x03\xf3B\xee\xe7\xfd\xcc\xcb\x94\x04<Hw\xf2\x1c'\x02\x8ew\xcb\xcc\x8b\xe6\xfb^\t\xa7\x03\x8a\xe7b\x01\xa9\x9c\xb9\x99\x10Z\rx\xe6o\xee\xd2V-\x0fYwY\x96Uuv\xe9C\x8b\xee\x1b\x9a\xe3N\xd7\xd1\x00\xc7\xcc6Y\x82<\xd7c\x0eR`^\x85\xa0\x05\x95\xb6\xa3,\x9d0X\xe6\xb9\xa6\xab@\xe8\x98\xa3Cv\x8a\x04X\xf4\xf42\xc1\xd7O\xacsQ\xe9\xf0U\xdbSc\xb4Y<[\xea\x07 \xcf\xf5\x97\xd0\xdb\xf0\xc5\x14\x85h@\xd3Gx\x89Jh\xc9'a\x00!$\xfd$\xff\x0ckp/5C0\x963\xd5\xa19\xb0F\xf2D\xa1\xa6zr.\x1a\\tG{\xe6\xe3\xc0\x8d#\x06>\x1b\x8b\xcd\x975U\xff\xce\x88\xdd\xa0m\xec\x8d\xa8\x15'\xe54\xcf\x0f}\xe0\xfa\xfc\xae\x16D\xc6\x01\xcaA\xbf-\xf3\xe6\xeb\xa2\x18\x11\x99\x96 \x805\x9cU\xedb\xa5P\xbd\xce\x90\xc3\x14\x87R8Drbp\xbb\xb1\x1a\x13"}
[DEBUG   ] Closing AsyncReqChannel instance
[DEBUG   ] Minion return retry timer set to 10 seconds (randomized)
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_1e9498c860_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_1e9498c860_pull.ipc
[ERROR   ] Unable to connect pusher: Stream is closed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/event.py", line 427, in connect_pull
    self.pusher.connect(timeout=timeout)
  File "/usr/lib/python3/dist-packages/salt/utils/asynchronous.py", line 125, in wrap
    raise exc_info[1].with_traceback(exc_info[2])
  File "/usr/lib/python3/dist-packages/salt/utils/asynchronous.py", line 131, in _target
    result = io_loop.run_sync(lambda: getattr(self.obj, key)(*args, **kwargs))
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/ioloop.py", line 459, in run_sync
    return future_cell[0].result()
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/lib/python3/dist-packages/salt/transport/ipc.py", line 345, in _connect
    yield self.stream.connect(sock_addr)
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
salt.ext.tornado.iostream.StreamClosedError: Stream is closed
[DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/ad/02be55f1dfd3dd798489265719c71c7e57e5a81eda7ae8c51c9d81331dfad3/.minions.p
[DEBUG   ] Minion return retry timer set to 9 seconds (randomized)
[INFO    ] Returning information for job: 20221021074351768582
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_1e9498c860_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_1e9498c860_pull.ipc
[ERROR   ] Unable to connect pusher: Stream is closed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/event.py", line 427, in connect_pull
    self.pusher.connect(timeout=timeout)
  File "/usr/lib/python3/dist-packages/salt/utils/asynchronous.py", line 125, in wrap
    raise exc_info[1].with_traceback(exc_info[2])
  File "/usr/lib/python3/dist-packages/salt/utils/asynchronous.py", line 131, in _target
    result = io_loop.run_sync(lambda: getattr(self.obj, key)(*args, **kwargs))
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/ioloop.py", line 459, in run_sync
    return future_cell[0].result()
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/lib/python3/dist-packages/salt/transport/ipc.py", line 345, in _connect
    yield self.stream.connect(sock_addr)
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
salt.ext.tornado.iostream.StreamClosedError: Stream is closed
```

Downgrade master and minion1 (acting as syndic) to 3004 helps and it works again.

### Versions Report
Salt Version:
          Salt: 3005.1
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.8.10 (default, Jun 22 2022, 20:18:18)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 20.0.0
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2
 
System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-126-generic
        system: Linux
       version: Ubuntu 20.04 focal

**Comment by viktordaniel** [comment]
# my fault, duplicate of https://github.com/saltstack/salt/issues/62577
