### ISSUE TITLE
[BUG] [ERROR   ] Missing python-croniter. Ignoring job Ubuntu 20.04

### ISSUE THREAD

**Issue by haykhovsepyan** [saltstack/salt#62998]
**Description**
I have schedule setup running with cron to upgrade servers Redhat/Debian. python3-croniter installed on machines and Redhat based servers works perfect. But on Ubuntu although python3-croniter I`m still getting below ERROR and schedule not executing. 

`salt-minion[9800]: [ERROR   ] Missing python-croniter. Ignoring job os_update.`

**Setup**
schedule.sls

```
schedule:
  os_update:
    function: state.sls
    cron: '06 9 1-8 * 3'
    args:
      - os.updates.linuxupdate
```
```
#dpkg -l | grep croniter
ii  python3-croniter                      0.3.29-2ubuntu1      
```

**Versions Report Minion/Master**
<details><summary>salt-minion --versions-report</summary>

```
Salt Version:
          Salt: 3005.1
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.9.14 (main, Oct  3 2022, 21:19:16)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-131-generic
        system: Linux
       version: Ubuntu 20.04 focal
```
       
<details><summary>salt --versions-report</summary>

```
Salt Version:
          Salt: 3005
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.9.13 (main, Aug 23 2022, 18:33:26)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: rocky 8.6 Green Obsidian
        locale: utf-8
       machine: x86_64
       release: 4.18.0-372.26.1.el8_6.x86_64
        system: Linux
       version: Rocky Linux 8.6 Green Obsidian
```

**Comment by OrangeDog** [comment]
If you are using the onedir packaging, you must install croniter with `salt-pip` or a `pip.installed` state.
The system Python is not used.

**Comment by haykhovsepyan** [comment]
with salt-pip installed it works thankss!!, one thing during updates with salt schedule I`m getting minion errors:

```
[salt.utils.schedule:875 ][ERROR   ][2385491] Unhandled exception running state.sls
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/schedule.py", line 842, in handle_func
  File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1201, in run
    module_name = virtualname
  File "/usr/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
    return callable(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1216, in _run_as
    module_name,
  File "/usr/lib/python3.6/site-packages/salt/modules/state.py", line 1392, in sls
    st_.push_active()
  File "/usr/lib/python3.6/site-packages/salt/state.py", line 3279, in call_high
    )
  File "/usr/lib/python3.6/site-packages/salt/state.py", line 2497, in call_chunks
    if isinstance(listvalue, str):
  File "/usr/lib/python3.6/site-packages/salt/state.py", line 2860, in call_chunk
    else:
  File "/usr/lib/python3.6/site-packages/salt/state.py", line 868, in _mod_aggregate
    for req in frozenset.union(
  File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1201, in run
    module_name = virtualname
  File "/usr/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
    return callable(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1216, in _run_as
    module_name,
  File "/usr/lib/python3.6/site-packages/salt/modules/config.py", line 211, in option
    if value in __opts__:
  File "/usr/lib/python3.6/site-packages/salt/loader/context.py", line 81, in __contains__
    return item in self.value()
  File "/usr/lib/python3.6/site-packages/salt/loader/context.py", line 72, in value
    return loader.pack[self.name]
KeyError: '__opts__'
```
it doesn't interfere with updates , but I have event checks in reactors and very often events failed due to mentioned ERROR.
Thanks.

**Comment by OrangeDog** [comment]
That would be a separate issue to be investigated.

**Comment by haykhovsepyan** [comment]
Ok thanks you can close the ticket.

**Comment by PlusOne** [comment]
Same issue on, on Ubuntu 20 and Debian 10 - same problem: 

```
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy
```

Syslog get flooded : 

```
Mar 28 07:20:07 icinga salt-minion[1187]: [ERROR   ] Missing python-croniter. Ignoring job schedule_update_upgrade.
Mar 28 07:20:08 icinga salt-minion[1187]: [ERROR   ] Missing python-croniter. Ignoring job schedule_update_upgrade.
Mar 28 07:20:09 icinga salt-minion[1187]: [ERROR   ] Missing python-croniter. Ignoring job schedule_update_upgrade.
Mar 28 07:20:10 icinga salt-minion[1187]: [ERROR   ] Missing python-croniter. Ignoring job schedule_update_upgrade.
```

**salt-pip install croniter** - does not solve the problem, either apt instalkl python3-croniter.
