### ISSUE TITLE
 [salt.utils.schedule:875 ][ERROR   ] Unhandled exception running state.sls

### ISSUE THREAD

**Issue by haykhovsepyan** [saltstack/salt#62999]
**Description**
I have schedule setup that upgrading servers based on Redhat/Debian. During the updates getting below  Error on minion  side

```
[salt.utils.schedule:875 ][ERROR   ][2385491] Unhandled exception running state.sls
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/schedule.py", line 842, in handle_func
  File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1201, in run
    module_name = virtualname
  File "/usr/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
    return callable(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1216, in _run_as
    module_name,
  File "/usr/lib/python3.6/site-packages/salt/modules/state.py", line 1392, in sls
    st_.push_active()
  File "/usr/lib/python3.6/site-packages/salt/state.py", line 3279, in call_high
    )
  File "/usr/lib/python3.6/site-packages/salt/state.py", line 2497, in call_chunks
    if isinstance(listvalue, str):
  File "/usr/lib/python3.6/site-packages/salt/state.py", line 2860, in call_chunk
    else:
  File "/usr/lib/python3.6/site-packages/salt/state.py", line 868, in _mod_aggregate
    for req in frozenset.union(
  File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1201, in run
    module_name = virtualname
  File "/usr/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
    return callable(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1216, in _run_as
    module_name,
  File "/usr/lib/python3.6/site-packages/salt/modules/config.py", line 211, in option
    if value in __opts__:
  File "/usr/lib/python3.6/site-packages/salt/loader/context.py", line 81, in __contains__
    return item in self.value()
  File "/usr/lib/python3.6/site-packages/salt/loader/context.py", line 72, in value
    return loader.pack[self.name]
KeyError: '__opts__'
```
it doesn't interfere with updates , but I have event checks in reactors and very often events failed due to mentioned ERROR.

**Setup**
schedule.sls

```
schedule:
  os_update:
    function: state.sls
    cron: '06 9 1-8 * 3'
    args:
      - os.updates.linuxupdate
```
linuxupdate.sls

```
uptodate:
{% if salt['grains.get']('os_family') == 'RedHat' %}
  pkg.uptodate:
    - refresh: True
{%- elif salt['grains.get']('os_family') == 'Debian' %}
  pkg.uptodate:
    - refresh: True
    - dist_upgrade: True
{% endif %}

event-completed:
   event.send:
     - name: 'salt/minion-update/success'
     - require:
       - pkg: uptodate


event-failed:
   event.send:
     - name: 'salt/minion-update/failed'
     - onfail:
       - pkg: uptodate
```

**Versions Report Master/Minion**
<details><summary>salt --versions-report</summary>

```
Salt Version:
          Salt: 3005
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.9.13 (main, Aug 23 2022, 18:33:26)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: rocky 8.6 Green Obsidian
        locale: utf-8
       machine: x86_64
       release: 4.18.0-372.26.1.el8_6.x86_64
        system: Linux
       version: Rocky Linux 8.6 Green Obsidian
```

<details><summary>salt-minion --versions-report</summary>

```
Salt Version:
          Salt: 3005.1
 
Dependency Versions:
          cffi: 1.11.5
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.14
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Sep 13 2022, 09:02:49)
  python-gnupg: Not Installed
        PyYAML: 3.12
         PyZMQ: 20.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: rocky 8.6 Green Obsidian
        locale: UTF-8
       machine: x86_64
       release: 4.18.0-372.32.1.el8_6.x86_64
        system: Linux
       version: Rocky Linux 8.6 Green Obsidian
```

**Comment by garethgreenaway** [comment]
@haykhovsepyan Can you test with the latest 3006 release and see if the issue still persists?  Thanks!

**Comment by haykhovsepyan** [comment]
hi @garethgreenaway 

I can confirm that on 3006 release I haven`t face the issue anymore.

**Comment by garethgreenaway** [comment]
@haykhovsepyan Thanks for the confirmation. I'll go ahead and close those issue.
