### ISSUE TITLE
[BUG] netbox.get utilizing the wrong API URL via pynetbox 

### ISSUE THREAD

**Issue by theonlykl** [saltstack/salt#63055]
**Description**
External pillar is defined to point to my netbox instance via the following: 

```
ext_pillar:
  - netbox:
      api_url: https://netbox.internal/api/
      api_token: XXXXXXXXXXXX
      proxy_return: False
      virtual_machines: True

```

Utilizing the above I can query the pillar data without issues; however, utilizing the netbox modules (specifically netbox.get) appears to query the wrong API URL.  

Returns: 
```
    pynetbox.core.query.RequestError: The requested url: https://netbox.internal/api/virtualization/virtual-machines/3/api/virtualization/virtual-machine/?name=samplevm.internal&limit=0 could not be found.
```

**Setup**

/etc/salt/master.d/netbox.conf: 

```
ext_pillar:
  - netbox:
      api_url: https://netbox.internal/api/
      api_token: XXXXXXXXXXXX
      proxy_return: False
      virtual_machines: True
```

Please be as specific as possible and give set-up details.

- Minion is a virtual device with a virtual-machine defined in Netbox. 
- Can manually query the API utilitizing URL: https://netbox.internal/api/virtualization/virtual-machines/?name=samplevm.internal
- Netbox Version: v3.3-2.2.0
- pynetbox Version: 6.6.2

**Steps to Reproduce the behavior**

> Hostnames were masked 

Running: 
```salt samplevm.internal netbox.get virtualization virtual-machine name=samplevm.internal````

Full Error Returned: 

```
samplevm.internal:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/minion.py", line 1916, in _thread_return
        return_data = minion_instance._execute_job_function(
      File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/minion.py", line 1873, in _execute_job_function
        return_data = self.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/loader/lazy.py", line 149, in __call__
        return self.loader.run(run_func, *args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/loader/lazy.py", line 1203, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/loader/lazy.py", line 1218, in _run_as
        return _func_or_method(*args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/executors/venv.py", line 24, in execute
        return __executors__["direct_call.execute"](opts, data, func, args, kwargs)
      File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/loader/lazy.py", line 149, in __call__
        return self.loader.run(run_func, *args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/loader/lazy.py", line 1203, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/loader/lazy.py", line 1218, in _run_as
        return _func_or_method(*args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/executors/direct_call.py", line 10, in execute
        return func(*args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/loader/lazy.py", line 149, in __call__
        return self.loader.run(run_func, *args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/loader/lazy.py", line 1203, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/loader/lazy.py", line 1218, in _run_as
        return _func_or_method(*args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/modules/netbox.py", line 188, in get_
        _get(
      File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/modules/netbox.py", line 122, in _get
        item = getattr(getattr(nb, app), endpoint).get(**kwargs)
      File "/var/lib/venv-salt-minion/local/pynetbox/core/endpoint.py", line 148, in get
        ret = next(resp, None)
      File "/var/lib/venv-salt-minion/local/pynetbox/core/response.py", line 117, in __next__
        next(self.response), self.endpoint.api, self.endpoint
      File "/var/lib/venv-salt-minion/local/pynetbox/core/query.py", line 320, in get
        req = self._make_call(add_params=add_params)
      File "/var/lib/venv-salt-minion/local/pynetbox/core/query.py", line 287, in _make_call
        raise RequestError(req)
    pynetbox.core.query.RequestError: The requested url: https://acdc.vigilant.dna/api/virtualization/virtual-machines/3/api/virtualization/virtual-machine/?name=s1acdc01.vigilant.dna&limit=0 could not be found.
```

If I run the salt-call directly from the minion the error does change a bit.   

```
user@samplevm:~$ sudo venv-salt-call netbox.get virtualization virtual-machines name=samplevm.internal
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
SSLError: HTTPSConnectionPool(host='netbox.internal', port=443): Max retries exceeded with url: /api/virtualization/virtual-machines/3/api/virtualization/virtual-machines/?name=samplevm.internal&limit=0 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))
Traceback (most recent call last):
  File "/var/lib/venv-salt-minion/local/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/var/lib/venv-salt-minion/local/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/var/lib/venv-salt-minion/local/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/var/lib/venv-salt-minion/local/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/var/lib/venv-salt-minion/local/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/var/lib/venv-salt-minion/local/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/venv-salt-minion/lib/python3.10/ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/venv-salt-minion/lib/python3.10/ssl.py", line 1070, in _create
    self.do_handshake()
  File "/usr/lib/venv-salt-minion/lib/python3.10/ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/venv-salt-minion/local/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/var/lib/venv-salt-minion/local/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/var/lib/venv-salt-minion/local/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='netbox.internal', port=443): Max retries exceeded with url: /api/virtualization/virtual-machines/3/api/virtualization/virtual-machines/?name=samplevm.internal&limit=0 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/venv-salt-call", line 10, in <module>
    salt_call()
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/scripts.py", line 432, in salt_call
    client.run()
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/cli/call.py", line 55, in run
    caller.run()
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/cli/caller.py", line 111, in run
    ret = self.call()
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/cli/caller.py", line 218, in call
    ret["return"] = self.minion.executors[fname](
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/loader/lazy.py", line 1203, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/loader/lazy.py", line 1218, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/executors/venv.py", line 24, in execute
    return __executors__["direct_call.execute"](opts, data, func, args, kwargs)
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/loader/lazy.py", line 1203, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/loader/lazy.py", line 1218, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/executors/direct_call.py", line 10, in execute
    return func(*args, **kwargs)
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/loader/lazy.py", line 1203, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/loader/lazy.py", line 1218, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/modules/netbox.py", line 188, in get_
    _get(
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/modules/netbox.py", line 122, in _get
    item = getattr(getattr(nb, app), endpoint).get(**kwargs)
  File "/var/lib/venv-salt-minion/local/pynetbox/core/endpoint.py", line 148, in get
    ret = next(resp, None)
  File "/var/lib/venv-salt-minion/local/pynetbox/core/response.py", line 117, in __next__
    next(self.response), self.endpoint.api, self.endpoint
  File "/var/lib/venv-salt-minion/local/pynetbox/core/query.py", line 320, in get
    req = self._make_call(add_params=add_params)
  File "/var/lib/venv-salt-minion/local/pynetbox/core/query.py", line 270, in _make_call
    req = getattr(self.http_session, verb)(
  File "/var/lib/venv-salt-minion/local/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/var/lib/venv-salt-minion/local/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/lib/venv-salt-minion/local/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/var/lib/venv-salt-minion/local/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='netbox.internal', port=443): Max retries exceeded with url: /api/virtualization/virtual-machines/3/api/virtualization/virtual-machines/?name=samplevm.internal&limit=0 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))
Traceback (most recent call last):
  File "/var/lib/venv-salt-minion/local/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/var/lib/venv-salt-minion/local/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/var/lib/venv-salt-minion/local/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/var/lib/venv-salt-minion/local/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/var/lib/venv-salt-minion/local/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/var/lib/venv-salt-minion/local/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/venv-salt-minion/lib/python3.10/ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/venv-salt-minion/lib/python3.10/ssl.py", line 1070, in _create
    self.do_handshake()
  File "/usr/lib/venv-salt-minion/lib/python3.10/ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/venv-salt-minion/local/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/var/lib/venv-salt-minion/local/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/var/lib/venv-salt-minion/local/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='netbox.internal', port=443): Max retries exceeded with url: /api/virtualization/virtual-machines/3/api/virtualization/virtual-machines/?name=samplevm.internal&limit=0 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/venv-salt-call", line 10, in <module>
    salt_call()
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/scripts.py", line 432, in salt_call
    client.run()
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/cli/call.py", line 55, in run
    caller.run()
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/cli/caller.py", line 111, in run
    ret = self.call()
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/cli/caller.py", line 218, in call
    ret["return"] = self.minion.executors[fname](
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/loader/lazy.py", line 1203, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/loader/lazy.py", line 1218, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/executors/venv.py", line 24, in execute
    return __executors__["direct_call.execute"](opts, data, func, args, kwargs)
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/loader/lazy.py", line 1203, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/loader/lazy.py", line 1218, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/executors/direct_call.py", line 10, in execute
    return func(*args, **kwargs)
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/loader/lazy.py", line 1203, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/loader/lazy.py", line 1218, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/modules/netbox.py", line 188, in get_
    _get(
  File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/modules/netbox.py", line 122, in _get
    item = getattr(getattr(nb, app), endpoint).get(**kwargs)
  File "/var/lib/venv-salt-minion/local/pynetbox/core/endpoint.py", line 148, in get
    ret = next(resp, None)
  File "/var/lib/venv-salt-minion/local/pynetbox/core/response.py", line 117, in __next__
    next(self.response), self.endpoint.api, self.endpoint
  File "/var/lib/venv-salt-minion/local/pynetbox/core/query.py", line 320, in get
    req = self._make_call(add_params=add_params)
  File "/var/lib/venv-salt-minion/local/pynetbox/core/query.py", line 270, in _make_call
    req = getattr(self.http_session, verb)(
  File "/var/lib/venv-salt-minion/local/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/var/lib/venv-salt-minion/local/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/lib/venv-salt-minion/local/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/var/lib/venv-salt-minion/local/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='netbox.internal', port=443): Max retries exceeded with url: /api/virtualization/virtual-machines/3/api/virtualization/virtual-machines/?name=samplevm.internal&limit=0 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))

```

Whats weird about the above error is the SSL certificate is pushed down to all the minions and netbox is secured with the same root_ca certificate.  The request URL is still incorrect in this output.  Is there anyway to bypass the SSL check? 

**Expected behavior**

Expectation would be to return a query of the virtual-machine as it exists in netbox.  

**Versions Report**

```
Salt Version:
          Salt: 3004

Dependency Versions:
          cffi: 1.13.2
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: 1.3.0
      M2Crypto: 0.38.0
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.17
      pycrypto: 3.9.0
  pycryptodome: Not Installed
        pygit2: 1.7.0
        Python: 3.6.15 (default, Sep 23 2021, 15:41:43) [GCC]
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 17.1.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.3

System Versions:
          dist: opensuse-leap 15.4
        locale: UTF-8
       machine: x86_64
       release: 5.14.21-150400.24.21-default
        system: Linux
       version: openSUSE Leap 15.4
```

**Comment by OrangeDog** [comment]
The pillar and the execution module do not share config.

To use the execution module you need to configure it [as the documentation says](https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.netbox.html):

```
netbox:
  url: https://netbox.internal/api/
  token: XXXXXXXXXXXX
```

You can probably use YAML references to reduce the duplication if you want.

**Comment by theonlykl** [comment]
> 

Thank you @OrangeDog, I missed that blurb in the documentation!   Ill get that setup and open up a new issue if there are more problems (which i dont think there will be).
