### ISSUE TITLE
[BUG] gitfs using pygit2 encounters connection time out

### ISSUE THREAD

**Issue by freemanjohn** [saltstack/salt#63072]
# Description
Unable to utilize gitfs via pygit2 and libgit2 using ed25519 ssh key. Please note I did change the repository visibility to public, and changed to HTTPS for gitfs, and it worked as expected. It appears I'm either missing something for SSH or it doesn't work :(

Please note that I can validate SSH connectivity to github.com via the below
```
[root@saltmaster1dc1 salt]# ssh -T git@github.com
Hi freemanjohn/devops-saltstack-salt_states! You've successfully authenticated, but GitHub does not provide shell access.
```

# Setup
Bootstrap installation, fresh

Please be as specific as possible and give set-up details.
- [x] on-prem machine
- [x] VM (Virtualbox, KVM, etc. please specify) KVM
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [x] used bootstrap to install

**Steps to Reproduce the behavior**
- Installed salt master and minion
- Configured sshkey
- Added ssh key as 'deploy' key to github repository
- run to clear locks `salt-run cache.clear_git_lock gitfs type=update`
- ran to update states `salt-run fileserver.update -l debug`

#Expected Behavior
Should pull latest changes from github for state data

# Versions Report
```
Salt Version:
          Salt: 3005.1

Dependency Versions:
          cffi: 1.15.1
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.3
       libgit2: 1.5.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.3
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.14.0
        pygit2: 1.11.1
        Python: 3.9.10 (main, Sep 23 2022, 00:00:00)
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 22.3.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: rocky 9.0 Blue Onyx
        locale: utf-8
       machine: x86_64
       release: 5.14.0-70.30.1.el9_0.x86_64
        system: Linux
       version: Rocky Linux 9.0 Blue Onyx
```

# Additional context
## Python and PIP configuration
```
[root@saltmaster1dc1 salt]# python --version
Python 3.9.10
[root@saltmaster1dc1 salt]# pip --version
pip 22.3.1 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)
```
## Master Configuration
```
gitfs_provider: pygit2
gitfs_remotes:
  - git://github.com/freemanjohn/devops-saltstack-salt_states.git:
    - privkey: '/root/.ssh/id_ed25519'
    - pubkey: '/root/.ssh/id_ed25519.pub'
```
## Error
```
[root@saltmaster1dc1 salt]# salt-run cache.clear_git_lock gitfs type=update
No locks were removed
[root@saltmaster1dc1 salt]# salt-run fileserver.update -l debug
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Changed git to gitfs in master opts' fileserver_backend list
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: saltmaster1dc1.domain.local
[DEBUG   ] Missing configuration file: /root/.saltrc
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Configuration file path: /etc/salt/master
[DEBUG   ] The functions from module 'fileserver' are being loaded by dir() on the loaded module
[DEBUG   ] LazyLoaded fileserver.update
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Changed git to gitfs in minion opts' fileserver_backend list
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: saltmaster1dc1.domain.local
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] The functions from module 'core' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'disks' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'extra' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'lvm' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'mdadm' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'minion_process' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'opts' are being loaded by dir() on the loaded module
[DEBUG   ] Override  __utils__: <module 'salt.loaded.int.grains.zfs' from '/usr/lib/python3.9/site-packages/salt/grains/zfs.py'>
[DEBUG   ] The functions from module 'zfs' are being loaded by dir() on the loaded module
[DEBUG   ] Elapsed time getting FQDNs: 0.022911787033081055 seconds
[DEBUG   ] The functions from module 'zfs' are being loaded by dir() on the loaded module
[DEBUG   ] LazyLoaded zfs.is_supported
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] The functions from module 'auth' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'cache' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'cloud' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'config' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'doc' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'error' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'event' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'git_pillar' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'http' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'jobs' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'launchd' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'lxc' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'manage' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'mattermost' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'mine' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'network' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'pagerduty' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'pillar' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'pkg' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'queue' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'reactor' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'salt' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'saltutil' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'sdb' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'vmadm' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'ssh' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'state' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'survey' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'test' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'thin' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'vault' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'virt' are being loaded by dir() on the loaded module
[DEBUG   ] The functions from module 'winrepo' are being loaded by dir() on the loaded module
[DEBUG   ] Sending event: tag = salt/run/20221116222400722331/new; data = {'fun': 'runner.fileserver.update', 'jid': '20221116222400722331', 'user': 'root', 'fun_args': [], '_stamp': '2022-11-16T22:24:01.033793'}
[DEBUG   ] pygit2 gitfs_provider enabled
[DEBUG   ] Created gitfs object with uninitialized remotes
[DEBUG   ] The functions from module 'gitfs' are being loaded by dir() on the loaded module
[DEBUG   ] LazyLoaded gitfs.envs
[DEBUG   ] Updating gitfs fileserver cache
[DEBUG   ] Current fetch URL for gitfs remote 'git://github.com/freemanjohn/devops-saltstack-salt_states.git': git://github.com/freemanjohn/devops-saltstack-salt_states.git (desired: git://github.com/freemanjohn/devops-saltstack-salt_states.git)
[DEBUG   ] Current refspecs for gitfs remote 'git://github.com/freemanjohn/devops-saltstack-salt_states.git': ['+refs/heads/*:refs/remotes/origin/*', '+refs/tags/*:refs/tags/*'] (desired: ['+refs/heads/*:refs/remotes/origin/*', '+refs/tags/*:refs/tags/*'])
[DEBUG   ] Current http.sslVerify for gitfs remote 'git://github.com/freemanjohn/devops-saltstack-salt_states.git': true (desired: true)
[DEBUG   ] Created gitfs object for process 110756
[DEBUG   ] Set update lock for gitfs remote 'git://github.com/freemanjohn/devops-saltstack-salt_states.git'
[DEBUG   ] Fetching gitfs remote 'git://github.com/freemanjohn/devops-saltstack-salt_states.git'
[ERROR   ] Error occurred fetching gitfs remote 'git://github.com/freemanjohn/devops-saltstack-salt_states.git': failed to connect to github.com: Connection timed out
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/salt/utils/gitfs.py", line 1870, in _fetch
    fetch_results = origin.fetch(**fetch_kwargs)
  File "/usr/local/lib64/python3.9/site-packages/pygit2/remote.py", line 146, in fetch
    payload.check_error(err)
  File "/usr/local/lib64/python3.9/site-packages/pygit2/callbacks.py", line 98, in check_error
    check_error(error_code)
  File "/usr/local/lib64/python3.9/site-packages/pygit2/errors.py", line 65, in check_error
    raise GitError(message)
_pygit2.GitError: failed to connect to github.com: Connection timed out
[DEBUG   ] Removed update lock for gitfs remote 'git://github.com/freemanjohn/devops-saltstack-salt_states.git'
[DEBUG   ] The functions from module 'local_cache' are being loaded by dir() on the loaded module
[DEBUG   ] LazyLoaded local_cache.prep_jid
[DEBUG   ] Sending event: tag = salt/run/20221116222400722331/ret; data = {'fun': 'runner.fileserver.update', 'jid': '20221116222400722331', 'user': 'root', 'fun_args': [], '_stamp': '2022-11-16T22:26:12.083379', 'return': True, 'success': True}
[DEBUG   ] The functions from module 'nested' are being loaded by dir() on the loaded module
[DEBUG   ] LazyLoaded nested.output
True
[INFO    ] Runner completed: 20221116222400722331
[DEBUG   ] Closing IPCMessageClient instance
[DEBUG   ] Runner return: True
```

**Comment by OrangeDog** [comment]
How exactly did you install pygit2? Specifically you need a libssh build that supports ed25519.

**Comment by freemanjohn** [comment]
@OrangeDog 
`pip install pygit2`

**Comment by OrangeDog** [comment]
Did that install a wheel or did it build it locally?

Have you checked again recently? I was also getting GitHub time-outs yesterday, because their servers were having some trouble.

**Comment by freemanjohn** [comment]
@OrangeDog I installed pygit2 with python version listed above and pip as root. I reran the commands below to see if theres a new version.

```
[root@saltmaster1dc1 ~]# cat /etc/group | grep wheel
wheel:x:10:
[root@saltmaster1dc1 ~]# pip install --upgrade pygit2
Requirement already satisfied: pygit2 in /usr/local/lib64/python3.9/site-packages (1.11.1)
Requirement already satisfied: cffi>=1.9.1 in /usr/local/lib64/python3.9/site-packages (from pygit2) (1.15.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.9/site-packages (from cffi>=1.9.1->pygit2) (2.21)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[root@saltmaster1dc1 ~]#
```

**Comment by OrangeDog** [comment]
Python wheels have nothing to do with the user group of the same name.
Attempting to install again doesn't tell you anything either.

Did you see if it was working today, and was just an issue with GitHub?

**Comment by freemanjohn** [comment]
@OrangeDog sorry I'm not super familiar with pip, and no the issue persists

**Comment by freemanjohn** [comment]
Gave up on pygit2 and used GitPython
