### ISSUE TITLE
[BUG] salt-call service.status <service> fails on MacOS with __salt__ is not defined [3004.1]

### ISSUE THREAD

**Issue by Sxderp** [saltstack/salt#63124]
**Description**

salt-call service.status <service> fails on MacOS with __salt__ is not defined

**Setup**
Just install Salt..

- [x] on-prem machine

**Steps to Reproduce the behavior**
On MacOS:
salt-call service.status com.apple.usernoted

**Expected behavior**
Not to crash?

I think the issue is:
 -> `modules.mac_service` uses `utils.mac_utils.launchctl`
 -> `utils.mac_utils` does a direct import of `modules.cmdmod._run_all_quiet` (no `__salt__` injection!)
 -> `utils.mac_utils.launchctl` calls the `_run_all_quiet` (under the fake `__salt__['cmd.run_all']`
 -> `modules.cmdmod._run_all_quiet` eventually calls `modules.cmdmod._run`
 -> `modules.cmdmod._run` requires `__salt__` but it hasn't been injected.
 
 Anyway, chicken / egg problem I suppose. Honestly, utils should be decoupled from
modules. In no way does it make sense to have "utils" call into "modules".
 

**Screenshots**
```
Traceback (most recent call last):
  File "/opt/salt/bin/salt-call", line 33, in <module>
    sys.exit(load_entry_point('salt==3004.1', 'console_scripts', 'salt-call')())
  File "/opt/salt/lib/python3.7/site-packages/salt-3004.1-py3.7.egg/salt/scripts.py", line 432, in salt_call
    client.run()
  File "/opt/salt/lib/python3.7/site-packages/salt-3004.1-py3.7.egg/salt/cli/call.py", line 55, in run
    caller.run()
  File "/opt/salt/lib/python3.7/site-packages/salt-3004.1-py3.7.egg/salt/cli/caller.py", line 111, in run
    ret = self.call()
  File "/opt/salt/lib/python3.7/site-packages/salt-3004.1-py3.7.egg/salt/cli/caller.py", line 219, in call
    self.opts, data, func, args, kwargs
  File "/opt/salt/lib/python3.7/site-packages/salt-3004.1-py3.7.egg/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/opt/salt/lib/python3.7/site-packages/salt-3004.1-py3.7.egg/salt/loader/lazy.py", line 1201, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/opt/salt/lib/python3.7/site-packages/salt-3004.1-py3.7.egg/salt/loader/lazy.py", line 1216, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/opt/salt/.pyenv/versions/3.7.12/lib/python3.7/site-packages/salt-3004.1-py3.7.egg/salt/executors/direct_call.py", line 10, in execute
    return func(*args, **kwargs)
  File "/opt/salt/lib/python3.7/site-packages/salt-3004.1-py3.7.egg/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/opt/salt/lib/python3.7/site-packages/salt-3004.1-py3.7.egg/salt/loader/lazy.py", line 1201, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/opt/salt/lib/python3.7/site-packages/salt-3004.1-py3.7.egg/salt/loader/lazy.py", line 1216, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/opt/salt/.pyenv/versions/3.7.12/lib/python3.7/site-packages/salt-3004.1-py3.7.egg/salt/modules/mac_service.py", line 528, in status
    output = __salt__["service.list"](name, runas=runas)
  File "/opt/salt/lib/python3.7/site-packages/salt-3004.1-py3.7.egg/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/opt/salt/lib/python3.7/site-packages/salt-3004.1-py3.7.egg/salt/loader/lazy.py", line 1201, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/opt/salt/lib/python3.7/site-packages/salt-3004.1-py3.7.egg/salt/loader/lazy.py", line 1216, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/opt/salt/.pyenv/versions/3.7.12/lib/python3.7/site-packages/salt-3004.1-py3.7.egg/salt/modules/mac_service.py", line 351, in list_
    return launchctl("list", label, return_stdout=True, runas=runas)
  File "/opt/salt/.pyenv/versions/3.7.12/lib/python3.7/site-packages/salt-3004.1-py3.7.egg/salt/modules/mac_service.py", line 318, in launchctl
    return __utils__["mac_utils.launchctl"](sub_cmd, *args, **kwargs)
  File "/opt/salt/lib/python3.7/site-packages/salt-3004.1-py3.7.egg/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/opt/salt/lib/python3.7/site-packages/salt-3004.1-py3.7.egg/salt/loader/lazy.py", line 1201, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/opt/salt/lib/python3.7/site-packages/salt-3004.1-py3.7.egg/salt/loader/lazy.py", line 1216, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/opt/salt/.pyenv/versions/3.7.12/lib/python3.7/site-packages/salt-3004.1-py3.7.egg/salt/utils/mac_utils.py", line 311, in launchctl
    ret = __salt__["cmd.run_all"](cmd, **kwargs)
  File "/opt/salt/lib/python3.7/site-packages/salt-3004.1-py3.7.egg/salt/modules/cmdmod.py", line 986, in _run_all_quiet
    success_stderr=success_stderr,
  File "/opt/salt/lib/python3.7/site-packages/salt-3004.1-py3.7.egg/salt/modules/cmdmod.py", line 442, in _run
    user_shell = __salt__["user.info"](runas)["shell"]
NameError: name '__salt__' is not defined
```

**Versions Report**

```
cos-2a09141:~ root# salt-call --versionsreport
Salt Version:
          Salt: 3004.1
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.0
     docker-py: Not Installed
         gitdb: 4.0.5
     gitpython: 3.1.12
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: 1.1.4
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.19
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.7.12 (default, Mar 11 2022, 20:48:53)
  python-gnupg: 0.4.4
        PyYAML: 5.4.1
         PyZMQ: 18.0.1
         smmap: 3.0.2
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.1
 
System Versions:
          dist: darwin 21.4.0 
        locale: utf-8
       machine: x86_64
       release: 21.4.0
        system: Darwin
       version: 12.3 x86_64
 ```

**Comment by lkubb** [comment]
This has been fixed in master already https://github.com/saltstack/salt/issues/61816 / https://github.com/saltstack/salt/pull/61826
