### ISSUE TITLE
[BUG] FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/m_/f91_g65n0p3dpzc3nnltrwkc0000gn/T/pip-install-n8yvvi_r/salt_4ea9b5927a9946f58817134b7fe54d06/requirements/static/pkg/py3.8/darwin.txt'

### ISSUE THREAD

**Issue by qiaouchicago** [saltstack/salt#63267]
**Description**
Can not install on M2 mac. Error message:
FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/m_/f91_g65n0p3dpzc3nnltrwkc0000gn/T/pip-install-n8yvvi_r/salt_4ea9b5927a9946f58817134b7fe54d06/requirements/static/pkg/py3.8/darwin.txt'

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [x] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)
 venv/bin/pip install salt
Collecting salt
  Using cached salt-3005.1.tar.gz (17.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [53 lines of output]
      3005.1
      Traceback (most recent call last):
        File "/Users/qiaoqiao/gdc/tungsten/venv38/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/Users/qiaoqiao/gdc/tungsten/venv38/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/qiaoqiao/gdc/tungsten/venv38/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/m_/f91_g65n0p3dpzc3nnltrwkc0000gn/T/pip-build-env-iuii0xh8/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/m_/f91_g65n0p3dpzc3nnltrwkc0000gn/T/pip-build-env-iuii0xh8/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/m_/f91_g65n0p3dpzc3nnltrwkc0000gn/T/pip-build-env-iuii0xh8/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 484, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/private/var/folders/m_/f91_g65n0p3dpzc3nnltrwkc0000gn/T/pip-build-env-iuii0xh8/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 1370, in <module>
        File "/private/var/folders/m_/f91_g65n0p3dpzc3nnltrwkc0000gn/T/pip-build-env-iuii0xh8/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/m_/f91_g65n0p3dpzc3nnltrwkc0000gn/T/pip-build-env-iuii0xh8/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "<string>", line 987, in __init__
        File "<string>", line 993, in update_metadata
        File "<string>", line 1124, in _property_install_requires
        File "<string>", line 179, in _parse_requirements_file
      FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/m_/f91_g65n0p3dpzc3nnltrwkc0000gn/T/pip-install-kdgsb2oe/salt_f137afe3dd2e4dafb1e1ba6e1983c5e8/requirements/static/pkg/py3.8/darwin.txt'
      [ERROR   ] An un-handled exception was caught by Salt's global exception handler:
      FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/m_/f91_g65n0p3dpzc3nnltrwkc0000gn/T/pip-install-kdgsb2oe/salt_f137afe3dd2e4dafb1e1ba6e1983c5e8/requirements/static/pkg/py3.8/darwin.txt'
      Traceback (most recent call last):
        File "/Users/qiaoqiao/gdc/tungsten/venv38/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/Users/qiaoqiao/gdc/tungsten/venv38/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/qiaoqiao/gdc/tungsten/venv38/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/m_/f91_g65n0p3dpzc3nnltrwkc0000gn/T/pip-build-env-iuii0xh8/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/m_/f91_g65n0p3dpzc3nnltrwkc0000gn/T/pip-build-env-iuii0xh8/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/m_/f91_g65n0p3dpzc3nnltrwkc0000gn/T/pip-build-env-iuii0xh8/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 484, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/private/var/folders/m_/f91_g65n0p3dpzc3nnltrwkc0000gn/T/pip-build-env-iuii0xh8/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 1370, in <module>
        File "/private/var/folders/m_/f91_g65n0p3dpzc3nnltrwkc0000gn/T/pip-build-env-iuii0xh8/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/m_/f91_g65n0p3dpzc3nnltrwkc0000gn/T/pip-build-env-iuii0xh8/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "<string>", line 987, in __init__
        File "<string>", line 993, in update_metadata
        File "<string>", line 1124, in _property_install_requires
        File "<string>", line 179, in _parse_requirements_file
      FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/m_/f91_g65n0p3dpzc3nnltrwkc0000gn/T/pip-install-kdgsb2oe/salt_f137afe3dd2e4dafb1e1ba6e1983c5e8/requirements/static/pkg/py3.8/darwin.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Expected behavior**
Salt should be installed successfully. 

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
PASTE HERE
```
</details>
3005.1

**Additional context**

**Comment by alphabet5** [comment]
I see the same issue. 

```
~ % python3.11 -m pip install --upgrade salt
Collecting salt
  Downloading salt-3005.1.tar.gz (17.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.9/17.9 MB 7.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [65 lines of output]
      3005.1
      Traceback (most recent call last):
        File "/opt/homebrew/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/homebrew/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/build_meta.py", line 485, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 1370, in <module>
        File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
                                       ^^^^^^^^^^^^
        File "<string>", line 987, in __init__
        File "<string>", line 993, in update_metadata
        File "<string>", line 1124, in _property_install_requires
        File "<string>", line 179, in _parse_requirements_file
      FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/kj/_rslddz103g5d3m98kr0qhy40000gn/T/pip-install-ueqroipo/salt_ef8afc9e9e6d4a9298ca08448933ba66/requirements/static/pkg/py3.11/darwin.txt'
      [ERROR   ] An un-handled exception was caught by Salt's global exception handler:
      FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/kj/_rslddz103g5d3m98kr0qhy40000gn/T/pip-install-ueqroipo/salt_ef8afc9e9e6d4a9298ca08448933ba66/requirements/static/pkg/py3.11/darwin.txt'
      Traceback (most recent call last):
        File "/opt/homebrew/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/homebrew/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/build_meta.py", line 485, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 1370, in <module>
        File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
                                       ^^^^^^^^^^^^
        File "<string>", line 987, in __init__
        File "<string>", line 993, in update_metadata
        File "<string>", line 1124, in _property_install_requires
        File "<string>", line 179, in _parse_requirements_file
      FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/kj/_rslddz103g5d3m98kr0qhy40000gn/T/pip-install-ueqroipo/salt_ef8afc9e9e6d4a9298ca08448933ba66/requirements/static/pkg/py3.11/darwin.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by ellisonmarks** [comment]
This indicates an unsupported version of python. See https://github.com/saltstack/salt/tree/master/requirements/static/pkg and the files under each version dir for the actual platform support at a given tag.

**Comment by qiaouchicago** [comment]
I was using python3.8

**Comment by MikeO-8thLight** [comment]
You need to set the includes for OpenSSL. I used the following on Mac:

```
env LDFLAGS="-L$(brew --prefix openssl@1.1)/lib" \
CFLAGS="-I$(brew --prefix openssl@1.1)/include" \
pip3.10 install salt
```

You may need swig in there too `SWIG_FEATURES="-cpperraswarn -includeall -I$(brew --prefix openssl@1.1)/include" \`

**Comment by dwoz** [comment]
Reporter used Python 3.8, which is EOL and unsupported (dropped in 9746aa75e61). Current branches (3006.x, 3007.x, 3008.x, master) ship darwin lock files for Python 3.9-3.14 only. Closing.
