### ISSUE TITLE
[BUG] Salt (3005.1) fails to build with Tiamat on Python 3.11

### ISSUE THREAD

**Issue by frebib** [saltstack/salt#63327]
**Description**
The error is `ERROR: No matching distribution found for PyInstaller==5.3`.
I cannot for the life of me work out where that is defined. `grep` doesn't find it. Is tiamat naughtily hiding/hardcoding things?
`omni/requirements.txt` only contains `tiamat-pip` and `setuptools<60.7.0`

Full log:
```
+ tiamat build --onedir --name=salt --system-site --system-copy-in=distutils --locale-utf8 --timeout=500 --log-level=info -r omni/requirements.txt
[INFO    ] Running ['/tmp/tmpzoyj77jg/bin/python3', '-m', 'pip', '--version'] in /cfsetup_build ...
[INFO    ] Running /tmp/tmpzoyj77jg/bin/python3 -c 'import sys;print(tuple(sys.version_info))' in /cfsetup_build ...
[INFO    ] Running ['/tmp/tmpzoyj77jg/bin/python3', '-m', 'pip', 'install', '--upgrade', 'pip', 'pyinstaller-hooks-contrib', 'setuptools>=50.3.0', 'wheel', 'pycparser', 'distro'] in /cfsetup_build ...
[INFO    ] Running ['/tmp/tmpzoyj77jg/bin/python3', '-m', 'pip', 'install', '-r', '/cfsetup_build/__build_requirements.txt', '/cfsetup_build', 'PyInstaller==5.3'] in /cfsetup_build ...
[ERROR   ] Command ['/tmp/tmpzoyj77jg/bin/python3', '-m', 'pip', 'install', '-r', '/cfsetup_build/__build_requirements.txt', '/cfsetup_build', 'PyInstaller==5.3'] running in /cfsetup_build completed.
 Dry-Run: False
 Exitcode: 1
 Process Output:
   >>>>> STDOUT >>>>>
Processing /cfsetup_build
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'

   <<<<< STDOUT <<<<<
   >>>>> STDERR >>>>>
ERROR: Ignored the following versions that require a different python version: 4.10 Requires-Python <3.11,>=3.6; 4.6 Requires-Python <3.11,>=3.6; 4.7 Requires-Python <3.11,>=3.6; 4.8 Requires-Python <3.11,>=3.6; 4.9 Requires-Python <3.11,>=3.6; 5.0 Requires-Python <3.11,>=3.7; 5.0.1 Requires-Python <3.11,>=3.7; 5.1 Requires-Python <3.11,>=3.7; 5.2 Requires-Python <3.11,>=3.7; 5.3 Requires-Python <3.11,>=3.7; 5.4 Requires-Python <3.11,>=3.7; 5.4.1 Requires-Python <3.11,>=3.7
ERROR: Could not find a version that satisfies the requirement PyInstaller==5.3 (from versions: 2.0, 2.1, 3.0, 3.1, 3.1.1, 3.2, 3.2.1, 3.3, 3.3.1, 3.4, 3.5, 3.6, 4.0, 4.1, 4.2, 4.3, 4.4, 4.5, 4.5.1, 5.5, 5.6, 5.6.1, 5.6.2, 5.7.0)
ERROR: No matching distribution found for PyInstaller==5.3

   <<<<< STDERR <<<<<

Traceback (most recent call last):
  File "/usr/bin/tiamat", line 8, in <module>
    sys.exit(start())
             ^^^^^^^
  File "/usr/lib/python3.11/site-packages/tiamat/scripts.py", line 8, in start
    hub.tiamat.init.cli()
  File "/usr/lib/python3.11/site-packages/pop/contract.py", line 211, in __call__
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tiamat/tiamat/init.py", line 54, in cli
    hub.builder.init.run_all(**hub.OPT.tiamat)
  File "/usr/lib/python3.11/site-packages/pop/contract.py", line 211, in __call__
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tiamat/builder/init.py", line 43, in run_all
    hub.builder.init.run(
  File "/usr/lib/python3.11/site-packages/pop/contract.py", line 211, in __call__
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tiamat/builder/init.py", line 59, in run
    hub.builder[builder_plugin].run(build_name)
  File "/usr/lib/python3.11/site-packages/pop/contract.py", line 211, in __call__
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tiamat/builder/pyinstaller.py", line 230, in run
    hub.virtualenv.init.create(build_name)
  File "/usr/lib/python3.11/site-packages/pop/contract.py", line 211, in __call__
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tiamat/virtualenv/init.py", line 69, in create
    return hub.virtualenv.init.setup_pip(bname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pop/contract.py", line 211, in __call__
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tiamat/virtualenv/init.py", line 227, in setup_pip
    hub.tiamat.cmd.run(
  File "/usr/lib/python3.11/site-packages/pop/contract.py", line 211, in __call__
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tiamat/tiamat/cmdmod.py", line 93, in run
    raise ChildProcessError(proc.stderr)
ChildProcessError: ERROR: Ignored the following versions that require a different python version: 4.10 Requires-Python <3.11,>=3.6; 4.6 Requires-Python <3.11,>=3.6; 4.7 Requires-Python <3.11,>=3.6; 4.8 Requires-Python <3.11,>=3.6; 4.9 Requires-Python <3.11,>=3.6; 5.0 Requires-Python <3.11,>=3.7; 5.0.1 Requires-Python <3.11,>=3.7; 5.1 Requires-Python <3.11,>=3.7; 5.2 Requires-Python <3.11,>=3.7; 5.3 Requires-Python <3.11,>=3.7; 5.4 Requires-Python <3.11,>=3.7; 5.4.1 Requires-Python <3.11,>=3.7
ERROR: Could not find a version that satisfies the requirement PyInstaller==5.3 (from versions: 2.0, 2.1, 3.0, 3.1, 3.1.1, 3.2, 3.2.1, 3.3, 3.3.1, 3.4, 3.5, 3.6, 4.0, 4.1, 4.2, 4.3, 4.4, 4.5, 4.5.1, 5.5, 5.6, 5.6.1, 5.6.2, 5.7.0)
ERROR: No matching distribution found for PyInstaller==5.3
```

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [x] onedir packaging
- [ ] used bootstrap to install

**Comment by OrangeDog** [comment]
Issues using tiamat should go elsewhere. Possibly https://gitlab.com/saltstack/pop/tiamat.

**Comment by frebib** [comment]
I got it to build finally. zmq needs updating because of https://github.com/zeromq/pyzmq/issues/1697
```
diff --git requirements/zeromq.txt requirements/zeromq.txt
index eb4d796418f1..b2e96f19761c 100644
--- requirements/zeromq.txt
+++ requirements/zeromq.txt
@@ -1,6 +1,5 @@
 -r base.txt
 -r crypto.txt

-pyzmq<=20.0.0 ; python_version < "3.6"
-pyzmq>=17.0.0 ; python_version < "3.9"
-pyzmq>19.0.2 ; python_version >= "3.9"
+pyzmq>19.0.2 ; python_version == "3.9"
+pyzmq>23.0.0 ; python_version >= "3.10"
```

The magic sauce was to add `--pyinstaller-version=5.7` to the `tiamat build ..` command
