### ISSUE TITLE
[BUG] Unable to forward pub data (running salt-syndic on a container)

### ISSUE THREAD

**Issue by neilspage2** [saltstack/salt#63338]
```
[WARNING ] Unable to forward pub data: Salt request timed out. The master is not responding. You may need to run your command with `--async` in order to bypass the congested event bus. With `--async`, the CLI tool will print the job id (jid) and exit immediately without listening for responses. You can then use `salt-run jobs.lookup_jid` to look up the results of the job in the job cache later.
```

This is what I get from the podman container. 

However, from the container I am able to hit the master AND the syndic:
```
# syndic node: master daemon
[root@f175df9f60a8 data]# nc -zv <omitted> 4505
Connection to  <omitted> ( <omitted>) 4505 port [tcp/*] succeeded!
[root@f175df9f60a8 data]#
```

```
# master of masters
**[root@f175df9f60a8 data]# nc -zv <omitted> 4505
Connection to <omitted> (<omitted>) 4505 port [tcp/*] succeeded!**
```

Salt-master on the syndic node shows it's able to process jobs:
```
[ERROR   ] ReqServer workers ipc:///var/run/salt/master/workers.ipc
[INFO    ] Worker binding to socket ipc:///var/run/salt/master/workers.ipc
[INFO    ] Worker binding to socket ipc:///var/run/salt/master/workers.ipc
[INFO    ] Authentication request from minion-host.somefqdn.com
[INFO    ] Authentication accepted from minion-host.somefqdn.com
[INFO    ] Got return from minion-host.somefqdn.com for job 20221219103820346896
[INFO    ] Authentication request from minion-host.somefqdn.com
[INFO    ] Authentication accepted from minion-host.somefqdn.com
[INFO    ] Got return from minion-host.somefqdn.com for job 20221219103835854268
```

The syndic component of the syndic node does not return back to the minions however, here are some errors from it:
```
[ERROR   ] Future <salt.ext.tornado.concurrent.Future object at 0x7fffded03f40> exception was never retrieved: Traceback (most recent call last):
  File "salt/ext/tornado/gen.py", line 1064, in run                                                                                                                             yielded = self.gen.throw(*exc_info)                                                                                                                                       File "salt/channel/client.py", line 426, in wrap_callback
    decoded = yield self._decode_payload(payload)                                                                                                                             File "salt/ext/tornado/gen.py", line 1056, in run                                                                                                                             value = future.result()
  File "salt/ext/tornado/concurrent.py", line 249, in result                                                                                                                    raise_exc_info(self._exc_info)                                                                                                                                            File "<string>", line 4, in raise_exc_info
  File "salt/ext/tornado/gen.py", line 309, in wrapper                                                                                                                          yielded = next(result)                                                                                                                                                    File "salt/channel/client.py", line 554, in _decode_payload
    if payload["enc"] == "aes":                                                                                                                                             TypeError: 'NoneType' object is not su
```

And
```
[WARNING ] Unable to forward pub data: Salt request timed out. The master is not responding. You may need to run your command with `--async` in order to bypass t[702/94993]
d event bus. With `--async`, the CLI tool will print the job id (jid) and exit immediately without listening for responses. You can then use `salt-run jobs.lookup_jid` to look up the results of the job in the job cache later.
```

**Comment by OrangeDog** [comment]
Possible duplicate: #62577

**Comment by dwoz** [comment]
Cannot reproduce on current 3006.x/3007.x/3008.x/master. Salt 3005 is EOL. The transport calling paths now guard `if msg:` before invoking `_decode_payload` (tcp `on_recv_handler` and zeromq `on_recv.consume`), so `None` no longer flows into `payload["enc"]`. Related fix `122fc230903` ("Let AsyncPubChannel._decode_payload bail out gracefully") shipped in 3007.9/3008.0, and #67936 (`a82f66413b2`) addressed syndic event forwarding. Reopen if this reproduces on a currently supported release.
