### ISSUE TITLE
[BUG] Salt's Wheelclient throws RuntimeError after upgrading to 3005 from 3004

### ISSUE THREAD

**Issue by anandcrusher** [saltstack/salt#63388]
**Description**
cmd_async method of salt.wheel.WheelClient throws "RuntimeError: The logging options have not been set yet" after upgrading the salt master version to 3005.1 from 3004.2. The complete error message below.

`Failed to configure logging on <SignalHandlingProcess(ProcessFunc(AsyncClientMixin._proc_function_remote, fun=key.accept jid=20221226101546297135), started)>: The logging options have not been set yet.
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/process.py", line 970, in wrapped_run_func
    salt._logging.setup_logging()
  File "/usr/lib/python3.6/site-packages/salt/_logging/impl.py", line 942, in setup_logging
    raise RuntimeError("The logging options have not been set yet.")
RuntimeError: The logging options have not been set yet.
{'tag': 'salt/wheel/20221226101546297135', 'jid': '20221226101546297135'}`

**Setup**
Salt-master and salt-api service running on an Centos Servers hosted in Azure.
Using an Python salt Engine to automatically accept salt keys using salt's WheelClient. Pasting the WheelClient's code snippet below

`wclient = salt.wheel.WheelClient(master_opts)
 return_data = wclient.cmd_async({'fun': 'key.accept', 'match': call_data['deviceId'],'eauth': 'pam','include_denied': True, 'username': pam_username,'password': pam_password })`

NOTE: call_data comes from an api which has to the minion key which is referred as deviceid here. 

**Steps to Reproduce the behavior**
Configure the config file of an Minion to point to master running with version 3005.1. Start the minion service and then accept the key in master using the cmd_async module of salt.wheel.WheelClient. They minion key wont get accepeted and throw the below error.

`>>> wclient.cmd_async({'fun': 'key.accept','match': 'TESTING_KEY_ACCEPTANCE_POST_SALT_UPGRADE_30051_TESTING2','eauth': 'pam','include_denied': True,'username': pam_username,'password': pam_password})
Failed to configure logging on <SignalHandlingProcess(ProcessFunc(AsyncClientMixin._proc_function_remote, fun=key.accept jid=20221228122753942755), started)>: The logging options have not been set yet.
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/process.py", line 970, in wrapped_run_func
    salt._logging.setup_logging()
  File "/usr/lib/python3.6/site-packages/salt/_logging/impl.py", line 942, in setup_logging
    raise RuntimeError("The logging options have not been set yet.")
RuntimeError: The logging options have not been set yet.
{'tag': 'salt/wheel/20221228122753942755', 'jid': '20221228122753942755'}`

**Expected behavior**
They key must get accepted wihtout any errors. The same is working fine with cmd_sync.

**Screenshots**

**Versions Report**
Salt master: (version 3005.1)
`Salt Version:
          Salt: 3005.1

Dependency Versions:
          cffi: Not Installed
      cherrypy: unknown
      dateutil: 2.4.2
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 18.0.1
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4

System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-1160.76.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core`

Salt-minion:  (version 2016.11.10)
`Salt Version:
           Salt: 2016.11.10

Dependency Versions:
           cffi: 1.12.2
       cherrypy: Not Installed
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Oct 30 2018, 23:45:53)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.6.1810 Core
        machine: x86_64
        release: 3.10.0-957.5.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core`

**Comment by anandcrusher** [comment]
Any update on this ?

**Comment by arch4ngel** [comment]
Experiencing the same with salt-ssh. I tend to monitor log outputs for failures and these dumping to stdout make it difficult to track during execution.

Know of any workaround to suppress this @anandcrusher?

**Comment by anandcrusher** [comment]
> Experiencing the same with salt-ssh. I tend to monitor log outputs for failures and these dumping to stdout make it difficult to track during execution.
> 
> Know of any workaround to suppress this @anandcrusher?

@arch4ngel Only workaround is to use the respective synchronous module. For example, cmd_sync instead of cmd_async. I think the same is applicable for salt-ssh too since both use the same modules. There is some changes done at https://github.com/saltstack/salt/blob/master/salt/client/mixins.py#L155 as part of the version 3005 which has messed up the sync calls.
If you absolutely need the async calls, then downgrade the salt-ssh version to 3004.2 or lesser. Did not experience this problem in 3004.2 or lesser.

**Comment by ptitdoc** [comment]
Similar error when using salt.client (and salt.client.ssh) in python scripts.

You can copy and run the function _disable_salt_logging in the beginning of your script (from there: https://github.com/saltstack/salt/blob/c5cfe214cdd3d2d46842075947394fa78ce60c53/tests/conftest.py#L1751C1-L1762C59)

This will hide the error message (and logging seems to be properly working afterward for me, probably it is properly initialized later).

**Comment by dwoz** [comment]
Fixed by 356218b564d ("fix(logging): tolerate unset options dict in worker bootstrap"), landed in 3006.x, 3007.x, 3008.x. Merge-forward to master in flight via #69631.
