### ISSUE TITLE
[BUG] ValueError: filedescriptor out of range in select()

### ISSUE THREAD

**Issue by golimix** [saltstack/salt#63404]
**Description**
[BUG] ValueError: filedescriptor out of range in select()

**Setup**

```
when the git http://172.31.96.54:3030/limix/salt-default.git
```

when the http://172.31.96.54:3030/limix/salt-default.git git repository is over 3000 count objects, 
268 directories, 3289 files

the error is happen

```
[root@172 ~]# cat /usr/lib/systemd/system/salt-master.service
[Unit]
Description=The Salt Master Server
Documentation=man:salt-master(1) file:///usr/share/doc/salt/html/contents.html https://docs.saltproject.io/en/latest/contents.html
After=network.target

[Service]
LimitNOFILE=100000
Type=notify
NotifyAccess=all
ExecStart=/usr/bin/salt-master
LimitCORE=infinity
LimitNOFILE=100000
LimitNPROC=100000


[Install]
WantedBy=multi-user.target
```

```
gitfs_remotes:
   - http://172.31.96.54:3030/limix/salt-default.git
```

### the /var/log/salt/master

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/process.py", line 993, in wrapped_run_func
    return run_func()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/salt/client/ssh/__init__.py", line 549, in handle_routine
    stdout, stderr, retcode = single.run()
  File "/usr/lib/python3.6/site-packages/salt/client/ssh/__init__.py", line 1092, in run
    stdout, stderr, retcode = self.cmd_block()
  File "/usr/lib/python3.6/site-packages/salt/client/ssh/__init__.py", line 1428, in cmd_block
    stdout, stderr, retcode = self.shim_cmd(cmd_str)
  File "/usr/lib/python3.6/site-packages/salt/client/ssh/__init__.py", line 1382, in shim_cmd
    return self.shell.exec_cmd(cmd_str)
  File "/usr/lib/python3.6/site-packages/salt/client/ssh/shell.py", line 334, in exec_cmd
    ret = self._run_cmd(cmd)
  File "/usr/lib/python3.6/site-packages/salt/client/ssh/shell.py", line 399, in _run_cmd
    stdout, stderr = term.recv()
  File "/usr/lib/python3.6/site-packages/salt/utils/vt.py", line 298, in recv
    return self._recv(maxsize)
  File "/usr/lib/python3.6/site-packages/salt/utils/vt.py", line 521, in _recv
    rlist, _, _ = select.select(rfds, [], [], 0)
ValueError: filedescriptor out of range in select()
```

```
/usr/local/lib/python3.6/site-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
  from cryptography.hazmat.backends import default_backend
Salt Version:
          Salt: 3005

Dependency Versions:
          cffi: 1.15.1
      cherrypy: unknown
      dateutil: Not Installed
     docker-py: 5.0.3
         gitdb: 0.6.4
     gitpython: 1.0.2
        Jinja2: 2.11.1
       libgit2: 0.28.4
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: 2.6.1
  pycryptodome: Not Installed
        pygit2: 1.0.3
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 18.0.1
         smmap: 0.9.0
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4

System Versions:
          dist: centos 7 Core
        locale: ANSI_X3.4-1968
       machine: x86_64
       release: 3.10.0-1127.19.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core
```

after clean the git repository, everything is ok

**Comment by OrangeDog** [comment]
What do you do to trigger the error? It looks like you're using `salt-ssh`?

**Comment by Ch3LL** [comment]
Closing due to inactivity. If this is still occurring on the latest version of Salt please open a new issue with the details and the information requested.
