### ISSUE TITLE
[BUG] onedir: thin generated by salt-ssh is missing packages

### ISSUE THREAD

**Issue by transistortim** [saltstack/salt#63446]
**Description**
With onedir, the thin generated by salt-ssh does not include the necessary python packages `distro` and `contextvars`. Thus, salt-ssh fails on the target minion.
If the classical salt-ssh is used instead, the packages are included correctly and everything works fine.
The cause of the issue seems to be some magic python path manipulation leading to inexistent pathes being reported by the `__file__`-attribute of `distro` and `contextvars` (see additional context below).

**Setup**
Debian bookworm, salt-ssh installed with apt from `deb https://repo.saltproject.io/salt/py3/debian/11/amd64/latest bullseye main`
- [x] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [x] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
```
% salt-ssh -l debug -w -t minion test.ping
```
<details><summary>Debug output from running salt-ssh</summary>

Shortened to the relevant parts
```
<...>
[DEBUG   ] Removing /home/user/.salt/var/cache/salt/master/thin/thin.tgz archive file
[DEBUG   ] No site package directories found
[DEBUG   ] Using contextvars <module 'contextvars' from '/opt/saltstack/salt/run/contextvars.pyc'>
[DEBUG   ] Adding module to the tops: "salt"
[DEBUG   ] Adding module to the tops: "distro"
[DEBUG   ] Adding module to the tops: "jinja2"
[DEBUG   ] Adding module to the tops: "yaml"
[DEBUG   ] Adding module to the tops: "salt.ext.tornado"
[DEBUG   ] Adding module to the tops: "msgpack"
[DEBUG   ] Adding module to the tops: "certifi"
[DEBUG   ] Adding module to the tops: "salt.ext.ssl_match_hostname"
[DEBUG   ] Adding module to the tops: "markupsafe"
[DEBUG   ] Adding module to the tops: "salt.ext.backports_abc"
[DEBUG   ] Adding module to the tops: "contextvars"
[DEBUG   ] Adding module to the tops: "immutables"
[DEBUG   ] Packing default libraries based on current Salt version
[DEBUG   ] Packing "salt" to "pyall" destination
[DEBUG   ] Packing "distro.py" to "py3" destination
[DEBUG   ] Packing "jinja2" to "pyall" destination
[DEBUG   ] Packing "yaml" to "py3" destination
[DEBUG   ] Packing "tornado" to "py3" destination
[DEBUG   ] Packing "msgpack" to "pyall" destination
[DEBUG   ] Packing "certifi" to "pyall" destination
[DEBUG   ] Packing "ssl_match_hostname.py" to "py3" destination
[DEBUG   ] Packing "markupsafe" to "py3" destination
[DEBUG   ] Packing "backports_abc.py" to "py3" destination
[DEBUG   ] Packing "contextvars.py" to "py3" destination
[DEBUG   ] Packing "immutables" to "py3" destination
<...>
minion:
    ----------
    retcode:
        1
    stderr:
        Traceback (most recent call last):
          File "/var/tmp/.minion_XXXXXX_salt/salt-call", line 27, in <module>
            salt_call()
          File "/var/tmp/.minion_XXXXXX_salt/pyall/salt/scripts.py", line 435, in salt_call
            import salt.cli.call
          File "/var/tmp/.minion_XXXXXX_salt/pyall/salt/cli/call.py", line 3, in <module>
            import salt.cli.caller
          File "/var/tmp/.minion_XXXXXX_salt/pyall/salt/cli/caller.py", line 12, in <module>
            import salt.channel.client
          File "/var/tmp/.minion_XXXXXX_salt/pyall/salt/channel/client.py", line 13, in <module>
            import salt.crypt
          File "/var/tmp/.minion_XXXXXX_salt/pyall/salt/crypt.py", line 26, in <module>
            import salt.payload
          File "/var/tmp/.minion_XXXXXX_salt/pyall/salt/payload.py", line 12, in <module>
            import salt.loader.context
          File "/var/tmp/.minion_XXXXXX_salt/pyall/salt/loader/__init__.py", line 15, in <module>
            import salt.config
          File "/var/tmp/.minion_XXXXXX_salt/pyall/salt/config/__init__.py", line 17, in <module>
            import salt.syspaths
          File "/var/tmp/.minion_XXXXXX_salt/pyall/salt/syspaths.py", line 22, in <module>
            import salt.utils.platform
          File "/var/tmp/.minion_XXXXXX_salt/pyall/salt/utils/platform.py", line 11, in <module>
            from distro import linux_distribution
        ModuleNotFoundError: No module named 'distro'
        [ERROR   ] An un-handled exception was caught by Salt's global exception handler:
        ModuleNotFoundError: No module named 'distro'
        Traceback (most recent call last):
          File "/var/tmp/.minion_XXXXXX_salt/salt-call", line 27, in <module>
            salt_call()
          File "/var/tmp/.minion_XXXXXX_salt/pyall/salt/scripts.py", line 435, in salt_call
            import salt.cli.call
          File "/var/tmp/.minion_XXXXXX_salt/pyall/salt/cli/call.py", line 3, in <module>
            import salt.cli.caller
          File "/var/tmp/.minion_XXXXXX_salt/pyall/salt/cli/caller.py", line 12, in <module>
            import salt.channel.client
          File "/var/tmp/.minion_XXXXXX_salt/pyall/salt/channel/client.py", line 13, in <module>
            import salt.crypt
          File "/var/tmp/.minion_XXXXXX_salt/pyall/salt/crypt.py", line 26, in <module>
            import salt.payload
          File "/var/tmp/.minion_XXXXXX_salt/pyall/salt/payload.py", line 12, in <module>
            import salt.loader.context
          File "/var/tmp/.minion_XXXXXX_salt/pyall/salt/loader/__init__.py", line 15, in <module>
            import salt.config
          File "/var/tmp/.minion_XXXXXX_salt/pyall/salt/config/__init__.py", line 17, in <module>
            import salt.syspaths
          File "/var/tmp/.minion_XXXXXX_salt/pyall/salt/syspaths.py", line 22, in <module>
            import salt.utils.platform
          File "/var/tmp/.minion_XXXXXX_salt/pyall/salt/utils/platform.py", line 11, in <module>
            from distro import linux_distribution
        ModuleNotFoundError: No module named 'distro'
    stdout:
```
</details>

Manually unpacking the thin shows that despite salt-ssh logs packing them, `distro.py` and `contextvars.py` are missing in the thin.
```
% ls thin/py3  
backports_abc.py
immutables
markupsafe
ssl_match_hostname.py
tornado
yaml
```

**Expected behavior**
Thin should include `distro` and `contextvars` as it does with classical salt (installed with apt from `deb https://repo.saltproject.io/py3/debian/11/amd64/latest bullseye main`).

**Versions Report**
<details><summary>salt-ssh --versions-report</summary>

```yaml
Salt Version:
          Salt: 3005.1
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.9.16 (main, Dec 14 2022, 15:47:34)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian n/a bookworm
        locale: utf-8
       machine: x86_64
       release: 6.0.0-6-amd64
        system: Linux
       version: Debian GNU/Linux n/a bookworm
```
</details>

**Additional context**
Looking at how the thin is generated, `<module>.__file__` is used and ".pyc" replaced with ".py", see https://github.com/saltstack/salt/blob/a7e492778a08f5471bbdf4b075742db4bba052f4/salt/utils/thin.py#L236
Check of `__file__` with small script & salt's python:
```
% cat ~/test.py
import distro
print(distro.__file__)
import contextvars
print(contextvars.__file__)
print(distro.name(pretty=True))
% /opt/saltstack/salt/run/run python ~/test.py         
/opt/saltstack/salt/run/distro.pyc
/opt/saltstack/salt/run/contextvars.pyc
Debian GNU/Linux bookworm/sid
```
So both modules are importable, distro.name also works correctly. But the reported pathes do not exist in /opt/saltstack/salt/run:
```
% ls /opt/saltstack/salt/run
<...>
CherryPy-18.6.1.dist-info
contextvars
contextvars-2.4.dist-info
Cryptodome
<...>
dateutil
distro-1.5.0.dist-info
distutils
<...>
```
If the reported path is used on thin generation, the packaging step uses the "top is a single file module" branch. There is a conditional file existence check, which is missing an else branch, see https://github.com/saltstack/salt/blob/a7e492778a08f5471bbdf4b075742db4bba052f4/salt/utils/thin.py#L704-L709
This is were I'm stuck, trying to implement an else branch for confirmation in /opt/saltstack/salt/run/salt/utils/thin.py didn't change anything. Is there an easy way to modify the onedir installation in place?

**Comment by garethgreenaway** [comment]
@s0undt3ch note to make sure `packaging` and `looseversion` are also included.

**Comment by transistortim** [comment]
Yes, I can confirm that with 3006.0RC2 the thin now contains all necessary packages. Thanks for asking!

**Comment by Ch3LL** [comment]
Are you okay closing this issue now?

**Comment by transistortim** [comment]
Yep, closing it now.
