### ISSUE TITLE
[BUG] ansiblegate stacktrace if ansible encounters any kind of error

### ISSUE THREAD

**Issue by dfidler** [saltstack/salt#63443]
**Description**

If your salt.states.ansible.playbooks passes in params that might cause empty output from ansible, you get a JSONDecodeError stack trace, which is undebuggable without going into the module code.

_Note:  Yes, I know you can't specify the runbook name with salt://  (was just testing to see if it would work when I hit this; this is a red herring)_

```
# salt-call state.apply ansible.helloworld
local:
----------
          ID: helloworld playbook
    Function: ansible.playbooks
        Name: salt://ansible/files/HelloWorld.yaml
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3.6/site-packages/salt/state.py", line 2180, in call
                  *cdata["args"], **cdata["kwargs"]
                File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 149, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1201, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/usr/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
                  return callable(*args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1216, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1249, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/utils/decorators/path.py", line 23, in wrapped
                  return function(*args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/states/ansiblegate.py", line 214, in playbooks
                  name, rundir=rundir, diff=True, **ansible_kwargs
                File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 149, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1201, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/usr/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
                  return callable(*args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1216, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/utils/decorators/path.py", line 23, in wrapped
                  return function(*args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/modules/ansiblegate.py", line 368, in playbooks
                  retdata = json.loads(ret["stdout"])
                File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
                  return _default_decoder.decode(s)
                File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
                  obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
                  raise JSONDecodeError("Expecting value", s, err.value) from None
              json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
     Started: 11:56:31.006839
    Duration: 1107.85 ms
     Changes:

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   1.108 s
```

**Setup**
Single salt-master running with ansible installed on it (test environment only).

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [x] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [x] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**

<details><summary>Run this script on your (RHEL-based) salt-master</summary>

```

DST=/root/ansiblegate-setup.sh
cat <<SCRIPT > ${DST}

mkdir -p /srv/salt/ansible /etc/ansible

echo Creating /srv/salt/ansible/setup-ansible-hosts.sls...
cat <<EOF1 > /srv/salt/ansible/setup-ansible-hosts.sls
#!py
import os
import yaml

MINION_SEARCH = "'G@kernel:Linux'"

ansible_etc = '/etc/ansible'
ansible_hosts_file = os.path.join(ansible_etc, 'hosts')

def success(minions):
  contents = "[all:vars]\nansible_connection=ssh\nansible_user=ansible\nansible_ssh_private_key_file=/etc/ansible/ansible_key\n\n[ansible_demo_servers]\n" + '\n'.join(sorted(minions))
  return {
    ansible_hosts_file: {
      'file.managed': [
        { 'user': 'root' },
        { 'group': 'root' },
        { 'mode':  '0750' },
        { 'contents': contents },
      ]
    }
  }
def failure(msg):
  return {
    ansible_hosts_file: {
      'test.fail_without_changes': [
        { 'name': msg },
      ]
    }
  }
def get_minions():
  x = salt['cmd.run']("salt -C '%s' grains.get fqdn_ip4 --out yaml" % MINION_SEARCH, python_shel=True, ignore_retcode=True)
  minions = yaml.safe_load(x)
  return minions
def run():
  try:
    minions = get_minions()
  except yaml.YAMLError as e:
    return failure('''Unable to get minion ips using "salt -C 'G@kernel:Linuxs' grains.get fqdn_ip4"; cannot generate /etc/ansible/hosts file''')

  minion_ips = []
  for id, ips in minions.items():
    minion_ips.append(ips[0])
  return success(minion_ips)

EOF1

echo Creating /srv/salt/ansible/setup-master.sls...
cat <<EOF2 > /srv/salt/ansible/setup-master.sls

{% set ansible_key = "/etc/ansible/ansible_key" %}

include:
  - .setup-ansible-hosts

# location of config files
/etc/ansible:
  file.directory:
    - create: True
    - user: root
    - group: root
    - mode: 0700
    - require_in:
      - /etc/ansible/hosts

install ansible:
  pkg.installed:
    - name: ansible 
    - require:
      - /etc/ansible

# generate an ssh key to deploy to all minions
generate_ssh_key_ansible:
  cmd.run:
    - name: ssh-keygen -q -N '' -C 'ansible_demo' -f {{ ansible_key }}
    - unless: test -f {{ ansible_key }}
    - require:
      - /etc/ansible

# copy the newly generated key to the salt fileserver so
# we can deploy it to minions
copy_ssh_key_to_file_roots:
  file.managed:
    - name: /srv/salt/ansible/files/ansible_key.pub
    - source: /etc/ansible/ansible_key.pub
    - makedirs: True
    - require:
      - generate_ssh_key_ansible
    - require_in:
      - /etc/ansible/hosts

/srv/playbooks:
  file.directory:
    - user: root
    - group: root
    - mode: 0700

/srv/playbooks/HelloWorld.yaml:
  file.managed:
    - user: root
    - group: root
    - mode: 0644
    - contents: |
        ---
        - name: This is a hello-world example
          hosts: ansible_demo_servers
          tasks:
            - name: Create a file called '/tmp/testfile.txt' with the content 'hello world'.
              copy:
                content: hello world
                dest: /tmp/testfile.txt 
    - require:
      - /srv/playbooks
EOF2

echo Creating /srv/salt/ansible/setup-minion.sls...
cat <<EOF3 > /srv/salt/ansible/setup-minion.sls
{% load_yaml as groups %}
RedHat: wheel
Debian: sudo
{% endload %}

{% set group = salt['grains.filter_by'](groups, 'os_family') %}

add ansible service account:
  user.present:
    - fullname: "Ansible Service Account"
    - name: ansible
    - password: '{{ salt['random.get_str'] (punctuation=False,whitespace=False) }}'
    - shell: /bin/bash
    - home: /home/ansible
    - groups:
        - {{ group }}
    - unless:
        - getent passwd ansible

install ssh key:
  ssh_auth.present:
    - user: "ansible"
    - source: "salt://ansible/files/ansible_key.pub"
    - enc: "ssh-rsa"
    - require:
      - add ansible service account
EOF3

SCRIPT

chmod u+x ${DST}
${DST}


echo Configuring the saltmaster...
salt-call state.apply ansible.setup-master

echo Configuring the minions....
salt -C 'G@kernel:Linux' state.apply ansible.setup-minion


```

/!\ Warning:  The script, above, creates /root/ansiblegate-setup.sh, which:
1. Creates state files to:
   a. Configure you salt-master to install ansible and setup ssh keys
   a. Configure you minions with an "ansible" user and the authroized public key
1. Builds the ansible /etc/ansible/hosts file with the Linux minions that are connected to the salt-master

Assumptions:
- You copy/paste the script (in the terminal if you like), above, onto your salt-master server, as root
- Your salt-master has the word "master" somewhere in the ID
- There is [optionally] at least one Linux host without the word "master" in the ID

Once the files are setup, you can always re-run the state files per...
```
# salt \*master* ansible.setup-master
# salt -C 'G@kernel:Linux and not *master*' ansible.setup-minion

```

</details>
As you can see, in the following output, the stdout from ansible is the empty string, which is not json decodable.  The code isn't pre-checking the retcode, or catching any exceptions, or checking stderr.... :/

<details><summary>Detailed output from exection</summary>

```
# cat /srv/salt/ansible/helloworld.sls
helloworld playbook:
  ansible.playbooks:
    - name: "salt://ansible/files/HelloWorld.yaml"

# salt-call state.apply ansible.helloworld
local:
----------
          ID: helloworld playbook
    Function: ansible.playbooks
        Name: salt://ansible/files/HelloWorld.yaml
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3.6/site-packages/salt/state.py", line 2180, in call
                  *cdata["args"], **cdata["kwargs"]
                File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 149, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1201, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/usr/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
                  return callable(*args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1216, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1249, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/utils/decorators/path.py", line 23, in wrapped
                  return function(*args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/states/ansiblegate.py", line 214, in playbooks
                  name, rundir=rundir, diff=True, **ansible_kwargs
                File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 149, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1201, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/usr/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
                  return callable(*args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1216, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/utils/decorators/path.py", line 23, in wrapped
                  return function(*args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/modules/ansiblegate.py", line 368, in playbooks
                  retdata = json.loads(ret["stdout"])
                File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
                  return _default_decoder.decode(s)
                File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
                  obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
                  raise JSONDecodeError("Expecting value", s, err.value) from None
              json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
     Started: 11:56:31.006839
    Duration: 1107.85 ms
     Changes:

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   1.108 s

#
# After adding a pdb.set_trace() into the ansiblegate module...
#

# salt-call state.apply ansible.helloworld
[ERROR   ] Command 'ansible-playbook' failed with return code: 1
[ERROR   ] stderr: ERROR! the playbook: salt://ansible/files/HelloWorld.yaml could not be found
[ERROR   ] retcode: 1
> /usr/lib/python3.6/site-packages/salt/modules/ansiblegate.py(370)playbooks()
-> retdata = json.loads(ret["stdout"])
(Pdb) ret
{'pid': 3756, 'retcode': 1, 'stdout': '', 'stderr': 'ERROR! the playbook: salt://ansible/files/HelloWorld.yaml could not be found'}
(Pdb) ret['stdout']
```
</details>

**Expected behavior**

Should gracefully catch the error, return "failure" for the state job, add stdout/stderr in the state's comments.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```
# salt-call --versions
Salt Version:
          Salt: 3004.2

Dependency Versions:
          cffi: 1.9.1
      cherrypy: 5.6.0
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: 0.6.4
     gitpython: 1.0.2
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.14
      pycrypto: Not Installed
  pycryptodome: 3.16.0
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.0.0
         smmap: 0.9.0
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4

Salt Extensions:
        SSEAPE: 8.10.2.4

System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-957.1.3.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core

```

</details>

**Comment by dwoz** [comment]
Not reproducible on 3006.x/3007.x/3008.x/master. Fixed by #60056 (commit d6740631ae0) which wraps `json.loads(ret["stdout"])` in `try/except ValueError:` in `salt/modules/ansiblegate.py` — `json.JSONDecodeError` is a `ValueError` subclass, so an empty ansible stdout now falls through to `retdata = ret` and the state module handles the missing `stats` key gracefully. Reporter was on 3004.2; the fix shipped in 3005.
