### ISSUE TITLE
[BUG] Mongo returner uri option does not parse hostname

### ISSUE THREAD

**Issue by abezyanka** [saltstack/salt#63476]
**Description**
When using mongo.uri option with the mongo returner, the returner fails because of a failure to connect to the mongodb host, which is left as default of "salt" - not what the Mongo URI is designating

mote.
2022-11-14 09:29:59,917 [salt.utils.job   :138 ][CRITICAL][60483] The specified 'mongo' returner threw a stack trace: 
Traceback (most recent call last): 
  File "/usr/lib/python3.6/site-packages/salt/utils/job.py", line 132, in store_job
    mminion.returners[savefstr](load["jid"], load)
  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 1241, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 2274, in run 
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run 
    return callable(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 2289, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/returners/mongo_future_return.py", line 299, in save_load
    conn, mdb = _get_conn(ret=None)
  File "/usr/lib/python3.6/site-packages/salt/returners/mongo_future_return.py", line 197, in _get_conn
    mdb.authenticate(user, password)
  File "/usr/lib64/python3.6/site-packages/pymongo/database.py", line 1495, in authenticate
    connect=True)
  File "/usr/lib64/python3.6/site-packages/pymongo/mongo_client.py", line 776, in _cache_credentials
    writable_preferred_server_selector)
  File "/usr/lib64/python3.6/site-packages/pymongo/topology.py", line 243, in select_server
    address))
  File "/usr/lib64/python3.6/site-packages/pymongo/topology.py", line 200, in select_servers
    selector, server_timeout, address)
  File "/usr/lib64/python3.6/site-packages/pymongo/topology.py", line 217, in _select_servers_loop
    (self._error_message(selector), timeout, self.description))
pymongo.errors.ServerSelectionTimeoutError: salt.db.genevatrading.com:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 63720a792a9de3279c36384b, topology_type: Single, servers: [<ServerDescription ('salt.db.genevatrading.com', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('salt.db.genevatrading.com:27017: timed out',)>]>

**Setup**
[(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)]

Configuration:
mongo.uri: mongodb://mongo_user:mongo_password@mongodb.company.com/salt

**Steps to Reproduce the behavior**
configure mongo returner with mongo.uri option and run state.apply

**Expected behavior**
The returner parses the hostname out of the mongo uri and uses that as the target host for the mongo connection

** Versions Report **
Salt Version:
          Salt: 3005.1
 
Dependency Versions:
          cffi: 1.15.1
      cherrypy: unknown
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: 1.5.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.4
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.16.0
        pygit2: 1.11.1
        Python: 3.9.16 (main, Jan 12 2023, 17:00:40)
  python-gnupg: Not Installed
        PyYAML: 6.0
         PyZMQ: 20.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.3
 
System Versions:
          dist: centos 7 Core
        locale: utf-8
       machine: x86_64
       release: 3.10.0-957.12.2.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core

**Comment by dwoz** [comment]
Cannot reproduce on current 3006.x/3007.x/3008.x/master. The `mdb.authenticate()` crash was fixed in 3006.0 by `db50e0c3b9f` ("Remove depr. pymongo function from mongo returner") — auth now goes through the `MongoClient(host, port, username=, password=)` constructor, and the mixed `mongo.host` + `mongo.uri` config now raises a clear `SaltConfigurationError` up front. The returner was purged on 3007.x+ (`dc526dc2b17`) and has no saltext replacement. Reopen if this reproduces on a currently supported release.
