### ISSUE TITLE
Mongo returner fails if pymongo is 4.0>

### ISSUE THREAD

**Issue by abezyanka** [saltstack/salt#63475]
### Description of Issue
Mongo returner has some bad authentication logic. When providing username password with a newer pymongo version, pymongo throws the following exception:
TypeError: 'Collection' object is not callable. If you meant to call the 'authenticate' method on a 'Database' object it is failing because no such method exists.
2023-01-12 20:47:57,571 [salt.client      :1161][WARNING ][15398] Returner unavailable: 'Collection' object is not callable. If you meant to call the 'authenticate' method on a 'Database' object it is failing because no such method exists.
2023-01-12 20:47:58,627 [salt.pillar      :1196][ERROR   ][7139] Exception caught loading ext_pillar 'mongo':
  File "/usr/local/lib/python3.9/site-packages/salt/pillar/__init__.py", line 1188, in ext_pillar
    ext = self._external_pillar_data(pillar, val, key)
  File "/usr/local/lib/python3.9/site-packages/salt/pillar/__init__.py", line 1108, in _external_pillar_data
    ext = self.ext_pillars[key](self.minion_id, pillar, **val)
  File "/usr/local/lib/python3.9/site-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/salt/loader/lazy.py", line 1228, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/salt/loader/lazy.py", line 1243, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/salt/pillar/mongo.py", line 132, in ext_pillar
    mdb.authenticate(user, password)
  File "/usr/local/lib/python3.9/site-packages/pymongo/collection.py", line 3207, in __call__
    raise TypeError(

2023-01-12 20:47:58,690 [salt.pillar      :1254][CRITICAL][7139] Pillar render error: Failed to load ext_pillar mongo: 'Collection' object is not callable. If you meant to call the 'authenticate' method on a 'Database' object it is failing because no such method exists.
2023-01-12 20:47:58,956 [salt.utils.job   :133 ][CRITICAL][7135] The specified 'mongo' returner threw a stack trace
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/salt/utils/job.py", line 129, in store_job
    mminion.returners[savefstr](load["jid"], load)
  File "/usr/local/lib/python3.9/site-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/salt/loader/lazy.py", line 1228, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/salt/loader/lazy.py", line 1243, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/salt/returners/mongo_future_return.py", line 293, in save_load
    conn, mdb = _get_conn(ret=None)
  File "/usr/local/lib/python3.9/site-packages/salt/returners/mongo_future_return.py", line 191, in _get_conn
    mdb.authenticate(user, password)
  File "/usr/local/lib/python3.9/site-packages/pymongo/collection.py", line 3207, in __call__
    raise TypeError(
TypeError: 'Collection' object is not callable. If you meant to call the 'authenticate' method on a 'Database' object it is failing because no such method exists.
2023-01-12 20:47:58,963 [salt.utils.job   :142 ][CRITICAL][7135] The specified 'mongo' returner threw a stack trace

/usr/local/lib/python3.9/site-packages/salt/returners/mongo_future_return.py", line 191, in _get_conn
/usr/local/lib/python3.9/site-packages/salt/pillar/mongo.py", line 132, in ext_pillar

My fix was to initialize MongoClient with username, password, authSource options passed in. As Database.authenticate has been removed in pymongo 4.0 (https://pymongo.readthedocs.io/en/stable/migrate-to-pymongo4.html#database-authenticate-and-database-logout-are-removed)

### Setup
salt==3005.1
pymongo==4.3.3

### Steps to Reproduce Issue
install pymongo=4.3.3 (though in theory, any 4.0> version will do) and configure mongo returner with username and password

### Versions Report
Salt Version:
          Salt: 3005.1
 
Dependency Versions:
          cffi: 1.15.1
      cherrypy: unknown
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: 1.5.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.4
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.16.0
        pygit2: 1.11.1
        Python: 3.9.16 (main, Jan 12 2023, 17:00:40)
  python-gnupg: Not Installed
        PyYAML: 6.0
         PyZMQ: 20.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.3
 
System Versions:
          dist: centos 7 Core
        locale: utf-8
       machine: x86_64
       release: 3.10.0-957.12.2.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core

**Comment by OrangeDog** [comment]
This should be fixed by #62832
