### ISSUE TITLE
[BUG] Slots/salt.utils.args.parse_function choke on an empty string

### ISSUE THREAD

**Issue by frebib** [saltstack/salt#63500]
**Description**
```python
>>> import salt.utils.args
>>> salt.utils.args.parse_function("foo.bar('')")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/frebib/stash/ops/saltstack/salt/utils/args.py", line 532, in parse_function
    if not brackets or token != {"[": "]", "{": "}", "(": ")"}[brackets.pop()]:
KeyError: ''
```

We hit this trying to pass an empty string into a slot call.

Apparently it works when you escape the quotes with backslashes.. because of course it does
```python
>>> salt.utils.args.parse_function("foo.bar(\\\"\\\")")
('foo.bar', ['""'], {})
>>> salt.utils.args.parse_function("foo.bar(\\'\\')")
('foo.bar', ["''"], {})
```

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

**Expected behavior**

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
PASTE HERE
```
</details>

**Additional context**

**Comment by OrangeDog** [comment]
Slots arguments (for some reason) are always strings and don't use quotes.`

It's probably impossible to pass an empty string, because that would be `foo.bar()`, and is identical to passing no arguments.

Your workaround does not work, as those are not empty strings being passed, but the two-character strings `""` and `''`.

**Comment by OrangeDog** [comment]
Related: #63287

**Comment by frebib** [comment]
Thanks @OrangeDog. I figured the answer would be as much.
I guess this ticket is more to track how flawed the slot syntax/parsing is.

> It's probably impossible to pass an empty string
So the issue is with the design. That'll need changing then
