### ISSUE TITLE
[BUG] PagerDuty errors out when using pillar for pagerduty profile

### ISSUE THREAD

**Issue by AGirin** [saltstack/salt#63533]
**Description**
Using pagerduty.create_event in s state produces error.

**Setup**
```
test_pd:
  pagerduty.create_event:
    - name: 'Test'
    - details: 'Test'
    - service_key: {{ salt['pillar.get']('test_pagerduty:key') }}
    - profile: {{ salt['pillar.get']('test_pagerduty') }}
```
We get this error: 
```
----------
          ID: test_pd
    Function: pagerduty.create_event
        Name: Test
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "salt\state.py", line 2276, in call
                  ret = self.states[cdata["full"]](
                File "salt\loader\lazy.py", line 149, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "salt\loader\lazy.py", line 1228, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "salt\loader\lazy.py", line 1243, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "salt\loader\lazy.py", line 1276, in wrapper
                  return f(*args, **kwargs)
                File "C:\Program Files\Salt Project\Salt\bin\salt\states\pagerduty.py", line 62, in create_event
                  __salt__["pagerduty.create_event"](
                File "salt\loader\lazy.py", line 149, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "salt\loader\lazy.py", line 1228, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "salt\loader\lazy.py", line 1243, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "C:\Program Files\Salt Project\Salt\bin\salt\modules\pagerduty.py", line 179, in create_event
                  salt.utils.pagerduty.query(
                File "salt\utils\pagerduty.py", line 67, in query
                  client_url = "https://{}.pagerduty.com".format(creds["pagerduty.subdomain"])
              KeyError: 'pagerduty.subdomain'
     Started: 18:56:10.841244
    Duration: 5.0 ms
     Changes:   
```

These commands work with the profile we have:

```
sudo salt '<salt minion>' pagerduty.list_services test_pagerduty
sudo salt '<salt minion>' pagerduty.list_incidents test_pagerduty
```
Any help is appreciated.

Thanks,

Andrew

**Comment by AGirin** [comment]
Pillar looks like this:

```
test_pagerduty:
  pagerduty.subdomain: <subdomain>
  pagerduty.api_key: <api_key>
  key: <key>
```

**Comment by AGirin** [comment]
Same config works just fine with paerduty config bengin in file...

**Comment by OrangeDog** [comment]
`profile` is the name of the profile, not the contents

```yaml
test_pd:
  pagerduty.create_event:
    - name: Test
    - details: Test
    - service_key: '{{ salt["pillar.get"]("test_pagerduty:key") }}'
    - profile: test_pagerduty
```

**Comment by AGirin** [comment]
Thanks :-). That was easy.
