### ISSUE TITLE
[BUG] modules.s3 tries to query location data from AWS metadata service when used with non-AWS S3 endpoint

### ISSUE THREAD

**Issue by ggiesen** [saltstack/salt#63569]
**Description**
The [s3 execution module](https://docs.saltproject.io/en/master/ref/modules/all/salt.modules.s3.html#module-salt.modules.s3) tries to query the AWS metadata service for location data even when service_url is specified, generating a Python traceback.

**Setup**
_/etc/salt/minion.d/s3.conf:_
```
s3.keyid: KAHRAAR8TAI3DOHZOO7O
s3.key: aepheena7Cae_shei+Biej+ei+XieJaeTu+xaeFu
s3.service_url: minio.example.com
s3.path_style: True
s3.https_enable: True
s3.verify_ssl: True
```
Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [x] VM (Virtualbox, KVM, etc. please specify): vSphere
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [x] onedir packaging
- [x] used bootstrap to install

**Steps to Reproduce the behavior**
```
salt-call s3.get mybucket bork local_file=/tmp/bork
[WARNING ] Failed to get AWS region from instance metadata.
Traceback (most recent call last):
  File "urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "http/client.py", line 1285, in request
  File "http/client.py", line 1331, in _send_request
  File "http/client.py", line 1280, in endheaders
  File "http/client.py", line 1040, in _send_output
  File "http/client.py", line 980, in send
  File "urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "urllib3/connection.py", line 174, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7f0ee4c9f400>, 'Connection to 169.254.169.254 timed out. (connect timeout=3.05)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /latest/dynamic/instance-identity/document (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f0ee4c9f400>, 'Connection to 169.254.169.254 timed out. (connect timeout=3.05)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "salt/utils/aws.py", line 582, in get_region_from_metadata
    result = requests.get(
  File "requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /latest/dynamic/instance-identity/document (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f0ee4c9f400>, 'Connection to 169.254.169.254 timed out. (connect timeout=3.05)'))
local:
    Saved to local file: /tmp/bork
```

It looks like the offending code is here:
https://github.com/saltstack/salt/blob/c45f22596c3a2b77f81c4499be7e2057f69ebba0/salt/utils/s3.py#L130-L131

If I specify the location (even though it's meaningless):
```
salt-call s3.get router-configs bork local_file=/tmp/bork location=bork
local:
    Saved to local file: /tmp/bork
```

**Expected behavior**
Add an option to disable metadata service, or don't attempt to fetch location from metadata if the credentials/service_url are specified in the minion config/pillar (I'm not sure how AWS builds its S3 endpoints and I haven't completely dug into the code yet)

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3005.1

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.9.16 (main, Dec 14 2022, 15:51:50)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: almalinux 8.7 Stone Smilodon
        locale: utf-8
       machine: x86_64
       release: 4.18.0-348.12.2.el8_5.x86_64
        system: Linux
       version: AlmaLinux 8.7 Stone Smilodon
```
</details>

**Additional context**
Using a local [minio](https://min.io/) instance as the endpoint

**Comment by ggiesen** [comment]
Two things resolve this.

**1. The `s3` execution module is no longer in Salt core.** It was moved out in the community-extensions purge and currently lives in the `salt-extensions/community-extensions-holding` repo (pending packaging as a standalone extension; only `saltext.s3fs` is published so far). So `salt-call s3.get` can't be run from core, and the metadata probe can't be triggered there. Core still ships `salt/utils/s3.py` (the module loads it via `__utils__["s3.query"]` and salt-ssh's thin tarball packs it), so the util itself remains.

**2. The behavior you asked for already has a config option: `s3.location`.** In `query()` the metadata lookup only runs when `location` is unset:

```python
if not location:
    location = salt.utils.aws.get_location()   # -> get_region_from_metadata() -> 169.254.169.254
```

and the module sources `location` from the `s3.location` config option (`_get_key`: `if location is None and __salt__["config.option"]("s3.location") ...`). So your `location=bork` workaround can be made permanent in the minion config:

```yaml
s3.location: us-east-1
```

With that set, `query()` never probes the metadata service. Unset, it keeps the old behavior (probe, then fall back to `us-east-1`). That is effectively the "configurable option, default = old behavior" approach, without hard-coding any endpoint domains.

Root cause for the record: with no `s3.location` and a non-AWS `service_url`, `get_location()` falls through to `get_region_from_metadata()`, which times out against `169.254.169.254` and logs the traceback before falling back to `us-east-1` (the request still succeeds). Setting `s3.location` avoids the probe entirely.

Closing this out: set `s3.location` to skip the probe, and use the `s3` modules from the extension going forward (https://github.com/salt-extensions/community-extensions-holding).
