### ISSUE TITLE
[BUG] salt.states.lxc.running throws uncaught exception

### ISSUE THREAD

**Issue by spinitron** [saltstack/salt#63705]
**Description**

An SLS that includes a perfectly simple example of `lxc.running` throws an exception on first application. On subsequent applications of the same SLS there is no error.

**Setup**
- [X] on-prem machine. actually OVH bare metal dedicated server

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
fsb@bhs7 [~] :)
$ uname -a
Linux bhs7 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux
```
**Steps to Reproduce the behavior**

My SLS is quite long and I doubt it is relevant. This is the state involved `name` is `"epf2"` in the example the follows.

```yaml
{{ name }} running:
  lxc.running:
    - name: {{ name }}
    - require:
      - service: lxc-net running
```

**Expected behavior**

No uncaught exceptions.

**Screenshots**

```
----------
          ID: epf2 running
    Function: lxc.running
        Name: epf2
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 2171, in call
                  ret = self.states[cdata["full"]](
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2105, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/lxc.py", line 452, in running
                  result = __salt__["lxc.start"](name, path=path)
                File "/usr/lib/python3/dist-packages/salt/modules/lxc.py", line 2478, in start
                  return _change_state(
                File "/usr/lib/python3/dist-packages/salt/modules/lxc.py", line 2348, in _change_state
                  __salt__["cmd.run"](rcmd, python_shell=False, timeout=30)
                File "/usr/lib/python3/dist-packages/salt/modules/cmdmod.py", line 1176, in run
                  ret = _run(
                File "/usr/lib/python3/dist-packages/salt/modules/cmdmod.py", line 688, in _run
                  proc.run()
                File "/usr/lib/python3/dist-packages/salt/utils/timed_subprocess.py", line 106, in run
                  if rt.isAlive():
              AttributeError: 'Thread' object has no attribute 'isAlive'
     Started: 19:04:47.930804
    Duration: 238.51 ms
     Changes:   
----------
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

On the master

```
Salt Version:
          Salt: 3002.6
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.3
       libgit2: 1.1.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.0
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.9.7
        pygit2: 1.4.0
        Python: 3.9.2 (default, Feb 28 2021, 17:03:44)
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 20.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 11 bullseye
        locale: utf-8
       machine: x86_64
       release: 5.10.0-18-amd64
        system: Linux
       version: Debian GNU/Linux 11 bullseye
```

On the target machine

```
$ salt-minion --version
salt-minion 3002.6
```

```yaml
PASTE HERE < --- what yaml do you want here?
```
</details>

**Additional context**

**Comment by dwoz** [comment]
Fixed in v3003 by b1dc0cee03896c8abad55a609805b0be6c7aaefa (`thread.isAlive()` → `thread.is_alive()` in `salt/utils/timed_subprocess.py`). Reporter was on 3002.6, which predates the fix. All supported branches (3006.x, 3007.x, 3008.x, master) already carry it.
