### ISSUE TITLE
[TECH DEBT] onedir installation to possibly read-only/networked /opt

### ISSUE THREAD

**Issue by carsten-AEI** [saltstack/salt#63709]
### Description of the tech debt

We are currently running a mix of 3003 and 3004 and I just started to look into 3005 changes. When looking I only learned about onedir installation just now.

We use saltstack to configure a mostly homogeneous large cluster with 3000+ hosts but use /opt as an networked autofs location which is read-only by the minions. IOW, installing the salt-common packages on Debian 10/11 would not work out of the box for us.

I've tried to gather information, if we could rebuild the Debian packages with a different path but `/opt` seems to be hardcoded in quite a number of places, thus I'm not sure if setting `TIAMAT_PIP_PYPATH` would help much.

Do you have any pointers which may help rebuilding the Debian packages with a different path, e.g. `/usr/local/` or even `/saltstack` would be preferable for us.

(thanks a bunch in advance for any help and feel free to re-label this issue)

### Versions Report

sample Debian buster node:
```
Salt Version:
Salt: 3004

Dependency Versions:
cffi: Not Installed
cherrypy: Not Installed
dateutil: 2.7.3
docker-py: Not Installed
gitdb: Not Installed
gitpython: Not Installed
Jinja2: 2.10
libgit2: Not Installed
M2Crypto: Not Installed
Mako: 1.0.7
msgpack: 0.5.6
msgpack-pure: Not Installed
mysql-python: Not Installed
pycparser: Not Installed
pycrypto: 2.6.1
pycryptodome: 3.6.1
pygit2: Not Installed
Python: 3.7.3 (default, Oct 31 2022, 14:04:00)
python-gnupg: Not Installed
PyYAML: 3.13
PyZMQ: 17.1.2
smmap: Not Installed
timelib: Not Installed
Tornado: 4.5.3
ZMQ: 4.3.1

System Versions:
dist: debian 10 buster
locale: UTF-8
machine: x86_64
release: 4.19.0-22-amd64
system: Linux
version: Debian GNU/Linux 10 buster
```

**Comment by carsten-AEI** [comment]
Just a side note, as I have tried a direct approach to change the hard coded paths:

After struggling a bit to create a reproducible build environment, I finally managed to build a set of packages with the direct approach of changing all `/opt/saltstack` to `/saltstack` via `sed` (as a test target):

[Dockerfile.txt](https://github.com/saltstack/salt/files/10744285/Dockerfile.txt)

(loosely based on your gitlab CI pipeline)

Running the official packages from https://repo.saltproject.io/salt/py3/debian/11/amd64/3005/pool/ versus these self created ones show a couple of differences/problems:

* **both** are still trying to initially find `libutil.so.1` under `/root/.pyenv/3.9.16` which seems to leak from the build container into the package. I'm not sure if this is a potential problem, just wanted to highlight this
* *my* build still creates `/opt/saltstack/salt/pypath/lib/python3.9/site-packages` but does not seem to do much with it before crashing (see below)
* when stracing *my* build, I see a couple of unsuccessful relative paths ending with `ENOENT` which I don't see when stracing your published packages, initially mostly like
```
openat(AT_FDCWD, "pyzmq.libs/tls/x86_64/x86_64/libsodium-bcf9f097.so.23.3.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "pyzmq.libs/tls/x86_64/libsodium-bcf9f097.so.23.3.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "pyzmq.libs/tls/x86_64/libsodium-bcf9f097.so.23.3.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
```
* *my* build is terminating like
```
/saltstack/salt/run/run master
[ERROR   ] 'EntryPoints' object has no attribute 'items'
Traceback (most recent call last):
File "salt/utils/parsers.py", line 212, in parse_args
mixin_after_parsed_func(self)
File "salt/utils/parsers.py", line 905, in __setup_logging
salt._logging.setup_logging()
File "salt/_logging/impl.py", line 971, in setup_logging
setup_extended_logging(opts)
File "salt/_logging/impl.py", line 878, in setup_extended_logging
providers = salt.loader.log_handlers(opts)
File "salt/loader/__init__.py", line 857, in log_handlers
_module_dirs(
File "salt/loader/__init__.py", line 153, in _module_dirs
for entry_point in entrypoints.iter_entry_points("salt.loader"):
File "salt/utils/entrypoints.py", line 29, in _wrapped
return f(*args, **kwargs)
File "salt/utils/entrypoints.py", line 41, in iter_entry_points
for entry_point_group, entry_points_list in entry_points.items():
AttributeError: 'EntryPoints' object has no attribute 'items'
Usage: salt-master [options]

[ERROR   ] 'EntryPoints' object has no attribute 'items'
Traceback (most recent call last):
File "salt/utils/parsers.py", line 212, in parse_args
mixin_after_parsed_func(self)
File "salt/utils/parsers.py", line 905, in __setup_logging
salt._logging.setup_logging()
File "salt/_logging/impl.py", line 971, in setup_logging
setup_extended_logging(opts)
File "salt/_logging/impl.py", line 878, in setup_extended_logging
providers = salt.loader.log_handlers(opts)
File "salt/loader/__init__.py", line 857, in log_handlers
_module_dirs(
File "salt/loader/__init__.py", line 153, in _module_dirs
for entry_point in entrypoints.iter_entry_points("salt.loader"):
File "salt/utils/entrypoints.py", line 29, in _wrapped
return f(*args, **kwargs)
File "salt/utils/entrypoints.py", line 41, in iter_entry_points
for entry_point_group, entry_points_list in entry_points.items():
AttributeError: 'EntryPoints' object has no attribute 'items'
salt-master: error: Error while processing <function LogLevelMixIn.__setup_logging at 0x7fc30f283f70>: Traceback (most recent call last):
File "salt/utils/parsers.py", line 212, in parse_args
mixin_after_parsed_func(self)
File "salt/utils/parsers.py", line 905, in __setup_logging
salt._logging.setup_logging()
File "salt/_logging/impl.py", line 971, in setup_logging
setup_extended_logging(opts)
File "salt/_logging/impl.py", line 878, in setup_extended_logging
providers = salt.loader.log_handlers(opts)
File "salt/loader/__init__.py", line 857, in log_handlers
_module_dirs(
File "salt/loader/__init__.py", line 153, in _module_dirs
for entry_point in entrypoints.iter_entry_points("salt.loader"):
File "salt/utils/entrypoints.py", line 29, in _wrapped
return f(*args, **kwargs)
File "salt/utils/entrypoints.py", line 41, in iter_entry_points
for entry_point_group, entry_points_list in entry_points.items():
AttributeError: 'EntryPoints' object has no attribute 'items'
```
but I have currently no clue why it errors out.

**Comment by Ch3LL** [comment]
For the 3006.0 release the package builds have moved to the Salt repo and the steps are different. But the big benefit is with these new builds you should be able to move the onedir anywhere on your system and it will work. 

I am working on adding documentation here: https://github.com/saltstack/salt/pull/63832
If you are only building just the onedir you don't need to update any paths, you simply just land it wherever you want to.

If you are building a Debian package you will have to replace the paths in the files in this directory: `pkg/debian`

Can you verify this works for you using the documentation I wrote?

**Comment by carsten-AEI** [comment]
With the Debian package (again pbuilder chroot for now), I'm currently stuck with 
```bash
[...]
Collecting urllib3==1.26.12
  Using cached urllib3-1.26.12-py2.py3-none-any.whl (140 kB)
Installing collected packages: commonmark, charset-normalizer, urllib3, typing-extensions, six, pyyaml, pygments, packaging, markupsafe, jmespath, idna, certifi, attrs, rich, requests, python-dateutil, jinja2, python-tools-scripts, botocore, s3transfer, boto3
Successfully installed attrs-22.1.0 boto3-1.21.46 botocore-1.24.46 certifi-2022.12.7 charset-normalizer-3.0.1 commonmark-0.9.1 idna-3.4 jinja2-3.1.2 jmespath-1.0.1 markupsafe-2.1.2 packaging-23.0 pygments-2.13.0 python-dateutil-2.8.2 python-tools-scripts-0.11.1 pyyaml-6.0 requests-2.28.2 rich-12.5.1 s3transfer-0.5.2 six-1.16.0 typing-extensions-4.4.0 urllib3-1.26.12

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: /tmp/salt-3006.0rc1/build/onedir/tools/bin/python3 -m pip install --upgrade pip
build/onedir/tools/bin/tools pkg pre-archive-cleanup --pkg build/onedir/salt
usage: tools [-h] [--version] [--timestamps | --no-timestamps]
             [--quiet | --debug] [--timeout SECONDS]
             [--no-output-timeout-secs SECONDS]
             {} ...
tools: error: argument command: invalid choice: 'pkg' (choose from )
make[1]: *** [debian/rules:31: override_dh_auto_build] Error 2
make[1]: Leaving directory '/tmp/salt-3006.0rc1'
make: *** [debian/rules:5: build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui failed
```

I'll try the docker image next, but given that the [Dockerfile](https://github.com/saltstack/salt-ci-containers/blob/main/custom/packaging/debian-11.Dockerfile) does not look too different, I guess it may fail the same way.

**Comment by carsten-AEI** [comment]
Unfortunately, the same:
```bash
mkdir salttest
 curl -s https://raw.githubusercontent.com/saltstack/salt-ci-containers/main/custom/packaging/debian-11.Dockerfile > salttest/Dockerfile
curl -s https://raw.githubusercontent.com/saltstack/salt-ci-containers/main/custom/packaging/01_nodoc > salttest/01_nodoc
docker build salttest --tag salttest
Sending build context to Docker daemon  3.072kB
Step 1/3 : FROM debian:11
11: Pulling from library/debian
32fb02163b6b: Already exists
Digest: sha256:f81bf5a8b57d6aa1824e4edb9aea6bd5ef6240bcc7d86f303f197a2eb77c430f
Status: Downloaded newer image for debian:11
 ---> 72b624312240
Step 2/3 : COPY 01_nodoc /etc/dpkg/dpkg.cfg.d/01_nodoc
 ---> 7371351c56bc
[...]
Running hooks in /etc/ca-certificates/update.d...
done.
Removing intermediate container 6c1f43170fbf
 ---> c471c2aa50aa
Successfully built c471c2aa50aa
Successfully tagged salttest:latest

docker run -i -t salttest /bin/bash
```
Now following the steps from [here](https://github.com/saltstack/salt/blob/3006.x/doc/topics/packaging/index.rst#how-to-build-deb-packages) in the docker container:

```bash
root@d9aa81cc5130:/# cd tmp; curl -sL https://github.com/saltstack/salt/releases/download/v3006.0rc1/salt-3006.0rc1.tar.gz | tar xz && cd salt-3006.0rc1
root@d9aa81cc5130:/tmp/salt-3006.0rc1# apt install -y python3 python3-venv python3-pip build-essential devscripts debhelper bash-completion git
[...]
root@d9aa81cc5130:/tmp/salt-3006.0rc1# ln -sf pkg/debian/ .
root@d9aa81cc5130:/tmp/salt-3006.0rc1# debuild -uc -us
[...]
Installing collected packages: commonmark, charset-normalizer, urllib3, typing-extensions, six, pyyaml, pygments, packaging, markupsafe, jmespath, idna, certifi, attrs, rich, requests, python-dateutil, jinja2, python-tools-scripts, botocore, s3transfer, boto3
Successfully installed attrs-22.1.0 boto3-1.21.46 botocore-1.24.46 certifi-2022.12.7 charset-normalizer-3.0.1 commonmark-0.9.1 idna-3.4 jinja2-3.1.2 jmespath-1.0.1 markupsafe-2.1.2 packaging-23.0 pygments-2.13.0 python-dateutil-2.8.2 python-tools-scripts-0.11.1 pyyaml-6.0 requests-2.28.2 rich-12.5.1 s3transfer-0.5.2 six-1.16.0 typing-extensions-4.4.0 urllib3-1.26.12

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: /tmp/salt-3006.0rc1/build/onedir/tools/bin/python3 -m pip install --upgrade pip
build/onedir/tools/bin/tools pkg pre-archive-cleanup --pkg build/onedir/salt
usage: tools [-h] [--version] [--timestamps | --no-timestamps]
             [--quiet | --debug] [--timeout SECONDS]
             [--no-output-timeout-secs SECONDS]
             {} ...
tools: error: argument command: invalid choice: 'pkg' (choose from )
make[1]: *** [debian/rules:31: override_dh_auto_build] Error 2
make[1]: Leaving directory '/tmp/salt-3006.0rc1'
make: *** [debian/rules:5: build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui failed
```

Thus, obviously, something with `tools` within onedir seems to be at odds, but I have no idea how to fix that.

Apart from this, the documentation looks good enough for me :)

**Comment by Ch3LL** [comment]
1. Are you on the most recent changes of the `3006.x` branch?
2. Can you ensure tools is installed at the most recent version.
3. If it still isn't working can you do a `pip list |grep -i tools` and paste here

**Comment by carsten-AEI** [comment]
ah, sorry, I misunderstood your initial comment that the fixes were already in the published rc1 and "just" the documentation was updated.

Anyway, when trying to go the docker route, starting again from salt's Debian 11 Dockerfile, I am now doing the following within the docker container:
```bash
# NOTE: patchelf seems to be required but is NOT yet part of the documentation
apt install -y python3 python3-venv python3-pip build-essential devscripts debhelper bash-completion git patchelf
git clone https://github.com/saltstack/salt.git
cd salt
git checkout 3006.x
ln -sf pkg/debian/ .
debuild -uc -us
```
and this then ends with
```
dh_strip: warning: Could not find the BuildID in debian/salt-common/opt/saltstack/salt/bin/python3.10
   dh_makeshlibs
   dh_shlibdeps
dpkg-shlibdeps: error: cannot find library libsodium-a0cd10d3.so.23.3.0 needed by debian/salt-common/opt/saltstack/salt/lib/python3.10/site-packages/pyzmq.libs/libzmq-fc4fcd2d.so.5.2.4 (ELF format: 'elf64-x86-64' abi: '0201003e00000000'; RPATH: '')
dpkg-shlibdeps: warning: debian/salt-common/opt/saltstack/salt/lib/libreadline.so.8.2 contains an unresolvable reference to symbol tgoto: it's probably a plugin
dpkg-shlibdeps: warning: 8 other similar warnings have been skipped (use -v to see them all)
dpkg-shlibdeps: error: cannot continue due to the error above
Note: libraries are not searched in other binary packages that do not have any shlibs or symbols file.
To help dpkg-shlibdeps find private libraries, you might need to use -l.
dh_shlibdeps: error: dpkg-shlibdeps -Tdebian/salt-common.substvars debian/salt-common/opt/saltstack/salt/bin/python3.10 debian/salt-common/opt/saltstack/salt/lib/libz.so.1.2.13 
[...]
stack/salt/lib/engines-1.1/afalg.so debian/salt-common/opt/saltstack/salt/lib/engines-1.1/capi.so returned exit code 2
dh_shlibdeps: error: Aborting due to earlier error
make: *** [debian/rules:5: binary] Error 25
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui failed
```

I'll try find out what is broken here

**Comment by carsten-AEI** [comment]
`libsodium` is present but not picked up by debhelper:
```
dpkg-shlibdeps: error: cannot find library libsodium-a0cd10d3.so.23.3.0 needed by debian/salt-common/opt/saltstack/salt/lib/python3.10/site-packages/pyzmq.libs/libzmq-fc4fcd2d.so.5.2.4 (ELF format: 'elf64-x86-64' abi: '0201003e00000000'; RPATH: '')
[...]
find . -name "libsodium*"
./pkg/debian/salt-common/opt/saltstack/salt/lib/python3.10/site-packages/pyzmq.libs/libsodium-a0cd10d3.so.23.3.0
./build/onedir/salt/lib/python3.10/site-packages/pyzmq.libs/libsodium-a0cd10d3.so.23.3.0
```
Just for completeness as I'm currently out of ideas:
The docker image has the following pips install:
```
pip3 list
Package         Version
--------------- --------------
awscli          1.19.1
botocore        1.20.0
certifi         2020.6.20
chardet         4.0.0
colorama        0.4.4
devscripts      2.21.3+deb11u1
docutils        0.16
gpg             1.14.0-unknown
idna            2.10
jmespath        0.10.0
olefile         0.46
Pillow          8.1.2
pip             20.3.4
pyasn1          0.4.8
Pygments        2.7.1
python-apt      2.2.1
python-dateutil 2.8.1
python-debian   0.1.39
python-magic    0.4.20
pyxdg           0.27
PyYAML          5.3.1
requests        2.25.1
roman           2.0.0
rsa             4.0
s3transfer      0.3.4
setuptools      52.0.0
six             1.16.0
unidiff         0.5.5
urllib3         1.26.5
wheel           0.34.2
xdg             5
```
the build venv has
```
. ./build/onedir/venv/bin/activate
(venv) root@66d0bd7ab200:/salt# pip3 list
Package       Version
------------- -------
pip           20.3.4
pkg-resources 0.0.0
relenv        0.8.0
setuptools    44.1.1
```

**Comment by Ch3LL** [comment]
I'm actually able to replicate this now. This was working a week or two ago, so I'll dive in and figure out what's going on here. Thanks for testing.

**Comment by carsten-AEI** [comment]
With this fix, the Debian packages do build again (note, that I still need to install `patchelf` within the container, otherwise the build breaks half way through). Thank you!

Relocating also seems to work, again, full recipe:

1. Building docker image via [Dockerfile](https://github.com/saltstack/salt-ci-containers/blob/main/custom/packaging/debian-11.Dockerfile)
2. `mkdir -p /dev/shm/exchange; docker run -i -t -v /dev/shm/exchange:/dev/shm/exchange salttest /bin/bash`

Within container (and some arbitrary target location `/local/salt/saltstack`):
```
apt install -y patchelf
git clone https://github.com/saltstack/salt.git
cd salt
git checkout 3006.x
ln -sf pkg/debian/ .
grep -lri opt/salt | xargs sed -i 's!opt/saltstack!local/salt/saltstack!g'
debuild -uc -us
```

That builds the packages and I can continue testing those.

Thank you!

**Comment by Ch3LL** [comment]
Perfect, you okay to close this issue now?

**Comment by carsten-AEI** [comment]
I have not found the time to test the resulting packages but as I know me, that could take a couple of days, so, yeah!
