### ISSUE TITLE
[BUG] Check file is not empty before attempting to read pillar disk cache file

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt#63729]
**Description**
During investigation of a customer issue, it was noted that msgpack will produce errors if it attempts to unpack an empty file.

**Setup**
User had enabled pillar caching, and then removed all pillar cached files etc. The code then create the replacement cache files, but they are empty and msgpack then will error when trying to unpack an empty file.
This was on RHEL 7 with msgpack 0.5.6.

Please be as specific as possible and give set-up details.

- [X] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
```
2023-02-09 15:43:02,891 [salt.master      :1916][ERROR   ][22024] Error in function _pillar:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/master.py", line 1910, in run_func
    ret = getattr(self, func)(load)
  File "/usr/lib/python3.6/site-packages/salt/master.py", line 1604, in _pillar
    clean_cache=load.get("clean_cache"),
  File "/usr/lib/python3.6/site-packages/salt/pillar/__init__.py", line 83, in get_pillar
    clean_cache=clean_cache,
  File "/usr/lib/python3.6/site-packages/salt/pillar/__init__.py", line 432, in __init__
    minion_cache_path=self._minion_cache_path(minion_id),
  File "/usr/lib/python3.6/site-packages/salt/utils/cache.py", line 34, in factory
    return CacheDisk(ttl, kwargs["minion_cache_path"], *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/utils/cache.py", line 89, in __init__
    self._read()
  File "/usr/lib/python3.6/site-packages/salt/utils/cache.py", line 147, in _read
    fp_, encoding=__salt_system_encoding__, raw=False
  File "/usr/lib/python3.6/site-packages/salt/utils/msgpack.py", line 145, in unpack
    return msgpack.unpack(stream, **_sanitize_msgpack_unpack_kwargs(kwargs))
  File "/usr/local/lib64/python3.6/site-packages/msgpack/__init__.py", line 58, in unpack
    return unpackb(data, **kwargs)
  File "msgpack/_unpacker.pyx", line 200, in msgpack._unpacker.unpackb
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 0: invalid start byte
```

**Expected behavior**
Not to throw errors in log files, by checking if file is not empty before attempting to load (unpack) with msgpack

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

This version report shows msgpack 0.5.6 but a correct installation should show msgpack 0.6.2, hence this is not a correct installation, and questions have been asked of the customer about how they have installed Salt. Response has not been received at this time.

```yaml
   - Salt Version:
          Salt: 3005.1

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.6.8 (default, Aug 13 2020, 07:46:32)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 18.0.1
         smmap: Not Installed
       timelib: Not Installed
      Tornado: 4.5.3
           ZMQ: 4.1.4

Salt Extensions:
        SSEAPE: 8.9.0.5

System Versions:
          dist: rhel 7.9 Maipo
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-1160.76.1.el7.x86_64
        system: Linux
       version: Red Hat Enterprise Linux Server 7.9 Maipo
```
</details>

**Additional context**

**Comment by dmurphy18** [comment]
Closing PR https://github.com/saltstack/salt/pull/63732 merged
