### ISSUE TITLE
[BUG] mac_xattr execution module fails on binary plist attributes

### ISSUE THREAD

**Issue by sheagcraig** [saltstack/salt#63779]
**Description**
Apple stores some file attribute information as binary plists, and in such a way that the bytes return from xattr cause a `UnicodeDecodeError`.

**Setup**
Salt 3004.2, masterless, on an M1 Mac.
- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [x] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
- Download something with Safari. I did [ghostunnel](https://github.com/ghostunnel/ghostunnel/releases/download/v1.7.1/ghostunnel-darwin-universal) but I suspect basically anything works.
- `sudo salt-call xattr.read ~/Downloads/ghostunnel-darwin-universal com.apple.metadata:kMDItemWhereFroms`

```
sudo salt-call xattr.read ~/Downloads/ghostunnel-darwin-universal com.apple.metadata:kMDItemWhereFroms
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa2 in position 8: invalid start byte
Traceback (most recent call last):
  File "/opt/local/bin/salt-call", line 33, in <module>
    sys.exit(load_entry_point('salt==3004.2', 'console_scripts', 'salt-call')())
  File "/opt/salt/lib/python3.7/site-packages/salt-3004.2-py3.7.egg/salt/scripts.py", line 432, in salt_call
    client.run()
  File "/opt/salt/lib/python3.7/site-packages/salt-3004.2-py3.7.egg/salt/cli/call.py", line 55, in run
    caller.run()
  File "/opt/salt/lib/python3.7/site-packages/salt-3004.2-py3.7.egg/salt/cli/caller.py", line 111, in run
    ret = self.call()
  File "/opt/salt/lib/python3.7/site-packages/salt-3004.2-py3.7.egg/salt/cli/caller.py", line 219, in call
    self.opts, data, func, args, kwargs
  File "/opt/salt/lib/python3.7/site-packages/salt-3004.2-py3.7.egg/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/opt/salt/lib/python3.7/site-packages/salt-3004.2-py3.7.egg/salt/loader/lazy.py", line 1201, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/opt/salt/lib/python3.7/site-packages/salt-3004.2-py3.7.egg/salt/loader/lazy.py", line 1216, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/opt/salt/.pyenv/versions/3.7.12/lib/python3.7/site-packages/salt-3004.2-py3.7.egg/salt/executors/direct_call.py", line 10, in execute
    return func(*args, **kwargs)
  File "/opt/salt/lib/python3.7/site-packages/salt-3004.2-py3.7.egg/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/opt/salt/lib/python3.7/site-packages/salt-3004.2-py3.7.egg/salt/loader/lazy.py", line 1201, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/opt/salt/lib/python3.7/site-packages/salt-3004.2-py3.7.egg/salt/loader/lazy.py", line 1216, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/opt/cpe-salt/salt/_modules/mac_xattr.py", line 116, in read
    ret = salt.utils.mac_utils.execute_return_result(cmd)
  File "/opt/salt/lib/python3.7/site-packages/salt-3004.2-py3.7.egg/salt/utils/mac_utils.py", line 178, in execute_return_result
    ret = _run_all(cmd)
  File "/opt/salt/lib/python3.7/site-packages/salt-3004.2-py3.7.egg/salt/utils/mac_utils.py", line 117, in _run_all
    out = salt.utils.stringutils.to_str(out).rstrip()
  File "/opt/salt/lib/python3.7/site-packages/salt-3004.2-py3.7.egg/salt/utils/stringutils.py", line 90, in to_str
    raise exc  # pylint: disable=raising-bad-type
  File "/opt/salt/lib/python3.7/site-packages/salt-3004.2-py3.7.egg/salt/utils/stringutils.py", line 83, in to_str
    return _normalize(s.decode(enc, errors))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa2 in position 8: invalid start byte
Traceback (most recent call last):
  File "/opt/local/bin/salt-call", line 33, in <module>
    sys.exit(load_entry_point('salt==3004.2', 'console_scripts', 'salt-call')())
  File "/opt/salt/lib/python3.7/site-packages/salt-3004.2-py3.7.egg/salt/scripts.py", line 432, in salt_call
    client.run()
  File "/opt/salt/lib/python3.7/site-packages/salt-3004.2-py3.7.egg/salt/cli/call.py", line 55, in run
    caller.run()
  File "/opt/salt/lib/python3.7/site-packages/salt-3004.2-py3.7.egg/salt/cli/caller.py", line 111, in run
    ret = self.call()
  File "/opt/salt/lib/python3.7/site-packages/salt-3004.2-py3.7.egg/salt/cli/caller.py", line 219, in call
    self.opts, data, func, args, kwargs
  File "/opt/salt/lib/python3.7/site-packages/salt-3004.2-py3.7.egg/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/opt/salt/lib/python3.7/site-packages/salt-3004.2-py3.7.egg/salt/loader/lazy.py", line 1201, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/opt/salt/lib/python3.7/site-packages/salt-3004.2-py3.7.egg/salt/loader/lazy.py", line 1216, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/opt/salt/.pyenv/versions/3.7.12/lib/python3.7/site-packages/salt-3004.2-py3.7.egg/salt/executors/direct_call.py", line 10, in execute
    return func(*args, **kwargs)
  File "/opt/salt/lib/python3.7/site-packages/salt-3004.2-py3.7.egg/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/opt/salt/lib/python3.7/site-packages/salt-3004.2-py3.7.egg/salt/loader/lazy.py", line 1201, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/opt/salt/lib/python3.7/site-packages/salt-3004.2-py3.7.egg/salt/loader/lazy.py", line 1216, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/opt/cpe-salt/salt/_modules/mac_xattr.py", line 116, in read
    ret = salt.utils.mac_utils.execute_return_result(cmd)
  File "/opt/salt/lib/python3.7/site-packages/salt-3004.2-py3.7.egg/salt/utils/mac_utils.py", line 178, in execute_return_result
    ret = _run_all(cmd)
  File "/opt/salt/lib/python3.7/site-packages/salt-3004.2-py3.7.egg/salt/utils/mac_utils.py", line 117, in _run_all
    out = salt.utils.stringutils.to_str(out).rstrip()
  File "/opt/salt/lib/python3.7/site-packages/salt-3004.2-py3.7.egg/salt/utils/stringutils.py", line 90, in to_str
    raise exc  # pylint: disable=raising-bad-type
  File "/opt/salt/lib/python3.7/site-packages/salt-3004.2-py3.7.egg/salt/utils/stringutils.py", line 83, in to_str
    return _normalize(s.decode(enc, errors))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa2 in position 8: invalid start byte
```

For what it's worth, the bytes returned also fail when trying to `plistlib.loads` so there's not an easy path here to just use that.

**Expected behavior**
Ideally the plist would be parsed and returned in a nicely formatted str, but I can't figure out how to coerce the builtin plistlib to handle it.

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3004.2

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.0
     docker-py: Not Installed
         gitdb: 4.0.5
     gitpython: 3.1.12
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: 1.1.4
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.19
      pycrypto: 3.15.0
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.7.12 (default, May 13 2022, 19:05:09)
  python-gnupg: 0.4.4
        PyYAML: 5.4.1
         PyZMQ: 18.0.1
         smmap: 3.0.2
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.1

System Versions:
          dist: darwin 22.4.0
        locale: UTF-8
       machine: x86_64
       release: 22.4.0
        system: Darwin
       version: 13.3 x86_64
```
</details>

**Additional context**

**Comment by sheagcraig** [comment]
I'm happy to submit a PR to fix this; we've been providing our own mac_xattr.py to solve this, but I'm wondering if there's any direction preferred for the solution.
- Decode the binary plist bytes with the `errors` argument using either `ignore` or `replace` and just return a str.
- Use the xattr `-x` argument to just spit out the hex values
- Someone with mad skillz makes it work with plistlib.

**Comment by garethgreenaway** [comment]
@sheagcraig If you're able to provide a PR with the fix that would be great.

**Comment by sheagcraig** [comment]
Okay @garethgreenaway both PRs are up. The 3006.x one had some tests fail but I don't imagine it's due to my changes; probably just need to run again (100% passed on the Master branch).

**Comment by garethgreenaway** [comment]
@sheagcraig Thanks!  The one against 3006.x needs a changelog file.

**Comment by sheagcraig** [comment]
Just pending the https://github.com/saltstack/salt/pull/64039 to close this one out.
