### ISSUE TITLE
[BUG] Salt 3006.0.rc1 on Ubuntu 22.04: Python Salt modules fail to load due PYTHONPATH issue and cffi version mismatch 

### ISSUE THREAD

**Issue by justinclloyd** [saltstack/salt#63839]
**Description**
In Salt 3006rc1 on a new Ubuntu 22.04 server, `import salt` fails despite `/opt/saltstack/salt/lib/python3.10/site-packages` being in the default PYTHONPATH. Exporting PYTHONPATH with that value adds it again as the 2nd item in the list and then the import works, but other imports complain about mismatched `cffi` versioning between the onedir Salt vesion and the system version.

**Setup**
I am using a barebones Salt state

```
# top.sls
base:
  '*':
    - noop

# noop/init.sls
null_state:
  test.nop
```

Please be as specific as possible and give set-up details.

- [x] on-prem machine
- [x] Microsoft Hyper-V VM
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [x] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
```
/srv/salt/states # salt-call grains.get pythonpath
local:
    - /opt/saltstack/salt
    - /opt/saltstack/salt/lib/python310.zip
    - /opt/saltstack/salt/lib/python3.10
    - /opt/saltstack/salt/lib/python3.10/lib-dynload
    - /opt/saltstack/salt/lib/python3.10/site-packages

/srv/salt/states # python3 -c 'import salt'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'salt'

/srv/salt/states # export PYTHONPATH=/opt/saltstack/salt/lib/python3.10/site-packages

/srv/salt/states # salt-call grains.get pythonpath
local:
    - /opt/saltstack/salt
    - /opt/saltstack/salt/lib/python3.10/site-packages
    - /opt/saltstack/salt/lib/python310.zip
    - /opt/saltstack/salt/lib/python3.10
    - /opt/saltstack/salt/lib/python3.10/lib-dynload
    - /opt/saltstack/salt/lib/python3.10/site-packages

/srv/salt/states # python3 -c 'import salt'

/srv/salt/states # python3 -c 'import salt.runner'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/runner.py", line 9, in <module>
    import salt.loader
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/__init__.py", line 23, in <module>
    import salt.utils.event
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/event.py", line 63, in <module>
    import salt.channel.client
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/channel/client.py", line 13, in <module>
    import salt.crypt
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/crypt.py", line 55, in <module>
    from Cryptodome.Cipher import AES, PKCS1_OAEP
  File "/usr/local/lib/python3.10/dist-packages/Cryptodome/Cipher/__init__.py", line 27, in <module>
    from Cryptodome.Cipher._mode_ecb import _create_ecb_cipher
  File "/usr/local/lib/python3.10/dist-packages/Cryptodome/Cipher/_mode_ecb.py", line 29, in <module>
    from Cryptodome.Util._raw_api import (load_pycryptodome_raw_lib,
  File "/usr/local/lib/python3.10/dist-packages/Cryptodome/Util/_raw_api.py", line 81, in <module>
    ffi = FFI()
  File "/opt/saltstack/salt/lib/python3.10/site-packages/cffi/api.py", line 54, in __init__
    raise Exception("Version mismatch: this is the 'cffi' package version %s, located in %r.  When we import the top-level '_cffi_backend' extension module, we get version %s, located in %r.  The two versions should be equal; check your installation." % (
Exception: Version mismatch: this is the 'cffi' package version 1.14.6, located in '/opt/saltstack/salt/lib/python3.10/site-packages/cffi/api.py'.  When we import the top-level '_cffi_backend' extension module, we get version 1.15.0, located in '/usr/lib/python3/dist-packages/_cffi_backend.cpython-310-x86_64-linux-gnu.so'.  The two versions should be equal; check your installation.
[ERROR   ] An un-handled exception was caught by Salt's global exception handler:
Exception: Version mismatch: this is the 'cffi' package version 1.14.6, located in '/opt/saltstack/salt/lib/python3.10/site-packages/cffi/api.py'.  When we import the top-level '_cffi_backend' extension module, we get version 1.15.0, located in '/usr/lib/python3/dist-packages/_cffi_backend.cpython-310-x86_64-linux-gnu.so'.  The two versions should be equal; check your installation.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/runner.py", line 9, in <module>
    import salt.loader
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/__init__.py", line 23, in <module>
    import salt.utils.event
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/event.py", line 63, in <module>
    import salt.channel.client
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/channel/client.py", line 13, in <module>
    import salt.crypt
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/crypt.py", line 55, in <module>
    from Cryptodome.Cipher import AES, PKCS1_OAEP
  File "/usr/local/lib/python3.10/dist-packages/Cryptodome/Cipher/__init__.py", line 27, in <module>
    from Cryptodome.Cipher._mode_ecb import _create_ecb_cipher
  File "/usr/local/lib/python3.10/dist-packages/Cryptodome/Cipher/_mode_ecb.py", line 29, in <module>
    from Cryptodome.Util._raw_api import (load_pycryptodome_raw_lib,
  File "/usr/local/lib/python3.10/dist-packages/Cryptodome/Util/_raw_api.py", line 81, in <module>
    ffi = FFI()
  File "/opt/saltstack/salt/lib/python3.10/site-packages/cffi/api.py", line 54, in __init__
    raise Exception("Version mismatch: this is the 'cffi' package version %s, located in %r.  When we import the top-level '_cffi_backend' extension module, we get version %s, located in %r.  The two versions should be equal; check your installation." % (
Exception: Version mismatch: this is the 'cffi' package version 1.14.6, located in '/opt/saltstack/salt/lib/python3.10/site-packages/cffi/api.py'.  When we import the top-level '_cffi_backend' extension module, we get version 1.15.0, located in '/usr/lib/python3/dist-packages/_cffi_backend.cpython-310-x86_64-linux-gnu.so'.  The two versions should be equal; check your installation.
```

**Expected behavior**
This should have loaded `salt.runner` wthout error. This happens with other modules as well, such as `salt.client`.

**Versions Report**
```
Salt Version:
          Salt: 3006.0rc1
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.10.10 (main, Feb 23 2023, 05:21:34) [GCC 11.2.0]
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: ubuntu 22.04 jammy
        locale: utf-8
       machine: x86_64
       release: 5.15.0-1034-azure
        system: Linux
       version: Ubuntu 22.04 jammy
```

**Comment by justinclloyd** [comment]
It turns out that I was using the system python, not the Salt onedir binary. That is going to definitely cause me future problems when I forget to do that, but at least I've learned a lesson and it's not a bug.
