### ISSUE TITLE
ERROR: Unable to manage file: Jinja error: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by sooraj2589** [saltstack/salt#63843]
### Description of Issue

We are tying Salt rendering in the minions. But suddenly we got below issues in couple of servers, but the same script is working fine in other servers. 

### Error log
  Comment: Unable to manage file: Jinja error: [Errno 13] Permission denied
              Traceback (most recent call last):
                File "/ngs/app/vertext/salt/usr/lib/python3.7/site-packages/salt/utils/templates.py", line 394, in render_jinja_tmpl
                  output = template.render(**decoded_context)
                File "/ngs/app/vertext/salt/usr/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
                  self.environment.handle_exception()
                File "/ngs/app/vertext/salt/usr/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
                  reraise(*rewrite_traceback_stack(source=source))
                File "/ngs/app/vertext/salt/usr/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
                  raise value.with_traceback(tb)
                File "<template>", line 5, in top-level template code
                File "/ngs/app/vertext/salt/usr/lib/python3.7/site-packages/salt/modules/slsutil.py", line 171, in renderer
                  path_or_string = __salt__['cp.get_url'](path, saltenv=kwargs.get('saltenv', 'base'))
                File "/ngs/app/vertext/salt/usr/lib/python3.7/site-packages/salt/modules/cp.py", line 418, in get_url
                  path, dest, makedirs, saltenv, source_hash=source_hash)
                File "/ngs/app/vertext/salt/usr/lib/python3.7/site-packages/salt/fileclient.py", line 697, in get_url
                  **get_kwargs
                File "/ngs/app/vertext/salt/usr/lib/python3.7/site-packages/salt/utils/http.py", line 579, in query
                  result = download_client.fetch(url_full, **req_kwargs)
                File "/ngs/app/vertext/salt/usr/lib/python3.7/site-packages/salt/ext/tornado/httpclient.py", line 103, in fetch
                  self._async_client.fetch, request, **kwargs))
                File "/ngs/app/vertext/salt/usr/lib/python3.7/site-packages/salt/ext/tornado/ioloop.py", line 459, in run_sync
                  return future_cell[0].result()
                File "/ngs/app/vertext/salt/usr/lib/python3.7/site-packages/salt/ext/tornado/concurrent.py", line 239, in result
                  raise_exc_info(self._exc_info)
                File "<string>", line 4, in raise_exc_info
                File "/ngs/app/vertext/salt/usr/lib/python3.7/site-packages/salt/ext/tornado/stack_context.py", line 317, in wrapped
                  ret = fn(*args, **kwargs)

### Versions Report
Salt master 3004.2
Salt Minion 3000.2

**Comment by OrangeDog** [comment]
3000.2 is not supported.

Please provide a reproduction for a 3004+ minion, including full version report and details of what you're doing to cause it.
