### ISSUE TITLE
[BUG] [3006] [3006.0rc2] ImportError: sys.meta_path is None, Python is likely shutting down

### ISSUE THREAD

**Issue by onmeac** [saltstack/salt#63913]
**Description**
Not sure yet what the bug is so title probably needs to be changed.

**Setup**
works/init.sls
```
file_foobar:
  file.managed:
    - name: /foobar
    - source: salt://works/foobar.jinja
    - template: jinja
    - context:
        foobar: baz
```
breaks/init.sls
```
#!py
"""."""


def run():
    """."""
    return {
        "file_foobar": {
            "file.managed": [
                {
                    "name": "/foobar"
                },
                {
                    "template": "jinja"
                },
                {
                    "context": {
                        "foobar": "baz",
                    }
                },
                {
                    "source": "salt://breaks/foobar.jinja",
                }
            ]
        }
    }
```
both have a `foobar.jinja` file
```{{ foobar }}```

Please be as specific as possible and give set-up details.

- [x] on-prem machine
- [x] VM (Virtualbox, KVM, etc. please specify) -- kvm
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [x] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**

both state.apply are run on the salt-master itself.

```
$ sudo salt-call state.apply --output-diff works test=true
local:
----------
          ID: file_foobar
    Function: file.managed
        Name: /foobar
      Result: None
     Comment: The file /foobar is set to be changed
              Note: No changes made, actual changes may
              be different due to other states.
     Started: 19:45:25.981848
    Duration: 15.29 ms
     Changes:   
              ----------
              newfile:
                  /foobar

Summary for local
------------
Succeeded: 1 (unchanged=1, changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  15.290 ms
```

```
$ sudo salt-call state.apply --output-diff breaks test=true
local:
----------
          ID: file_foobar
    Function: file.managed
        Name: /foobar
      Result: None
     Comment: The file /foobar is set to be changed
              Note: No changes made, actual changes may
              be different due to other states.
     Started: 19:45:42.854943
    Duration: 30.345 ms
     Changes:   
              ----------
              newfile:
                  /foobar

Summary for local
------------
Succeeded: 1 (unchanged=1, changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  30.345 ms
Exception encountered while running stop method
Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/asynchronous.py", line 98, in close
    method()
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/channel/client.py", line 315, in close
    self.transport.close()
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/transport/zeromq.py", line 919, in close
    self.message_client.close()
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/transport/zeromq.py", line 538, in close
    self.stream.close(1)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 526, in close
    self.io_loop.remove_handler(self.socket)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/ext/tornado/ioloop.py", line 737, in remove_handler
    fd, obj = self.split_fd(fd)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/ext/tornado/ioloop.py", line 659, in split_fd
    return fd.fileno(), fd
  File "/opt/saltstack/salt/lib/python3.10/site-packages/zmq/sugar/socket.py", line 304, in fileno
    return self.FD
  File "/opt/saltstack/salt/lib/python3.10/site-packages/zmq/sugar/attrsettr.py", line 52, in __getattr__
    from zmq import ZMQError
ImportError: sys.meta_path is None, Python is likely shutting down
```

**Versions Report**
```
$ sudo salt --versions-report
Salt Version:
          Salt: 3006.0rc2
 
Python Version:
        Python: 3.10.10 (main, Feb 23 2023, 05:21:34) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
        relenv: 0.7.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: centos 7 Core
        locale: utf-8
       machine: x86_64
       release: 3.10.0-1160.81.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core
```

Tested on both rc1 and now rc2, same results.

**Comment by garethgreenaway** [comment]
Closed by #63924
