### ISSUE TITLE
[BUG] [3006] [3006.0rc2] file.managed gives ValueError: I/O operation on closed file on seccond state.apply

### ISSUE THREAD

**Issue by onmeac** [saltstack/salt#63920]
**Description**
ValueError: I/O operation on closed file when running state.apply with file.maged twice.

**Setup**
testing.sls
```
file_testing:
  file.managed:
    - name: /testing
    - contents: |
        testing
```

Please be as specific as possible and give set-up details.

- [x] on-prem machine
- [x] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [x] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**

```
$ sudo salt-call state.apply --output-diff testing
local:
----------
          ID: file_foobar
    Function: file.managed
        Name: /testing
      Result: True
     Comment: File /testing updated
     Started: 10:06:40.248795
    Duration: 14.089 ms
     Changes:   
              ----------
              diff:
                  New file

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  14.089 ms
```

run again
```
$ sudo salt-call state.apply --output-diff testing
local:

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:   7.983 ms
Exception ignored in: <function RemoteClient.__del__ at 0x7f95c57c3760>
Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/fileclient.py", line 1142, in __del__
    self.destroy()
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/fileclient.py", line 1157, in destroy
    channel.close()
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/asynchronous.py", line 105, in close
    io_loop.close(all_fds=True)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/ext/tornado/ioloop.py", line 718, in close
    self.remove_handler(self._waker.fileno())
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/ext/tornado/platform/posix.py", line 49, in fileno
    return self.reader.fileno()
ValueError: I/O operation on closed file
```

**Versions Report**
<details><summary>salt --versions-report</summary>

```yaml
Salt Version:
          Salt: 3006.0rc2
 
Python Version:
        Python: 3.10.10 (main, Feb 23 2023, 05:21:34) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
        relenv: 0.7.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: centos 7 Core
        locale: utf-8
       machine: x86_64
       release: 3.10.0-1160.81.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core

```
</details>

**Additional context**
state.apply was run on the salt-master itself, salt-minion already running or not makes no difference.

**Comment by onmeac** [comment]
without salt-call
```
$ sudo salt salt_master state.apply --output-diff testing
salt_master:

Summary for salt_master
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:   9.347 ms
```

using salt-call
```
$ sudo salt-call state.apply --output-diff testing
local:

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:  12.205 ms
Exception ignored in: <function RemoteClient.__del__ at 0x7f9fcf1ab760>
Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/fileclient.py", line 1142, in __del__
    self.destroy()
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/fileclient.py", line 1157, in destroy
    channel.close()
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/asynchronous.py", line 105, in close
    io_loop.close(all_fds=True)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/ext/tornado/ioloop.py", line 718, in close
    self.remove_handler(self._waker.fileno())
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/ext/tornado/platform/posix.py", line 49, in fileno
    return self.reader.fileno()
ValueError: I/O operation on closed file
```

**Comment by Ch3LL** [comment]
Fixed by https://github.com/saltstack/salt/pull/63984
