### ISSUE TITLE
[BUG] OnePackage Installer Broken - "Salt Minion is already installed via MSI" when it isn't

### ISSUE THREAD

**Issue by darkpixel** [saltstack/salt#64033]
This machine used to have salt installed using the older MSI.

I upgraded it using the OnePackage installer a few weeks ago and everything was running well.

I uninstalled salt using Add/Remove Programs so I could reinstall it while making a video for someone and ran into a bug.

The OnePackage installer insists Salt is already installed via the MSI--but ```c:\program files\salt*``` doesn't exist.  ```c:\programdata\salt*``` doesn't exist.  ```c:\program files (x86)\salt*``` doesn't exist.  The salt-minion service doesn't exist.  It doesn't show up in Add/Remove Programs.  No processes are running with "salt" in the name.

Quick video showing the issue: https://user-images.githubusercontent.com/158380/230410287-56dee2fb-7567-439f-a045-a8f42333c7ee.mp4

**Comment by darkpixel** [comment]
Tried downloading the latest Windows MSI.
Right-clicking and picking "uninstall" says "This action is only valid for products that are currently installed"
Double-clicking the MSI gives an error that the installation ended prematurely.

![Screenshot from 2023-04-06 07-50-12](https://user-images.githubusercontent.com/158380/230416681-b031f0c6-62ae-487c-8688-f8fbdbb9cf0c.png)

Two entries are logged in the event log by MsiInstaller:

```Product: Salt Minion 3005.1-4 -- Installation failed.```

and:

```
Windows Installer installed the product. Product Name: Salt Minion 3005.1-4. Product Version: 30.05.1. Product Language: 1033. Manufacturer: Salt Project. Installation success or error status: 1603.
```

**Comment by twangboy** [comment]
@darkpixel , Thanks for reporting this issue. I'll take a look at it next week. Hopefully, I can figure out what's going on here. I have a few questions that will help me reproduce this issue.

Do you remember what version of Salt you were running before you installed a onedir version?
Which OneDir version did you install?
Was it the `.exe` installer or the `.msi` installer that you used to upgrade to the onedir version?

As a workaround, you could try the `.exe` installer.

**Comment by darkpixel** [comment]
We had ```Salt-Minion-3004.2-1-Py3-AMD64.msi``` deployed everywhere.
We deployed ```salt-3005.1-4-windows-amd64.exe``` with the args ```/S /master=--redacted--```.

I tested the RC3 MSI and it said the same thing--that the wizard ended prematurely.
I tested the RC3 EXE and it installed successfully and the salt-minion is running, but it's not talking with my server.

When I manually run salt-call, I get this:

```
PS C:\Program Files\Salt Project\Salt> .\salt-call.exe -l info --master salt.--redacted--.net test.ping
[ERROR   ] An un-handled exception was caught by Salt's global exception handler:
ImportError: DLL load failed while importing _device: The specified module could not be found.
Traceback (most recent call last):
  File "C:\Program Files\Salt Project\Salt\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Salt Project\Salt\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Salt Project\Salt\salt-call.exe\__main__.py", line 7, in <module>
    sys.exit(salt_call())
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\scripts.py", line 444, in salt_call
    client.run()
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\cli\call.py", line 40, in run
    caller = salt.cli.caller.Caller.factory(self.config)
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\cli\caller.py", line 42, in factory
    return ZeroMQCaller(opts, **kwargs)
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\cli\caller.py", line 303, in __init__
    super().__init__(opts)
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\cli\caller.py", line 63, in __init__
    self.minion = salt.minion.SMinion(opts)
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\minion.py", line 928, in __init__
    io_loop.run_sync(lambda: self.eval_master(self.opts, failed=True))
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\ext\tornado\ioloop.py", line 459, in run_sync
    return future_cell[0].result()
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\ext\tornado\concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\ext\tornado\gen.py", line 309, in wrapper
    yielded = next(result)
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\minion.py", line 815, in eval_master
    pub_channel = salt.channel.client.AsyncPubChannel.factory(
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\channel\client.py", line 361, in factory
    transport = salt.transport.publish_client(opts, io_loop)
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\transport\base.py", line 87, in publish_client
    import salt.transport.zeromq
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\transport\zeromq.py", line 13, in <module>
    import zmq.error
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\zmq\__init__.py", line 136, in <module>
    from zmq import backend
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\zmq\backend\__init__.py", line 31, in <module>
    raise original_error from None
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\zmq\backend\__init__.py", line 26, in <module>
    _ns = select_backend(first)
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\zmq\backend\select.py", line 31, in select_backend
    mod = import_module(name)
  File "C:\Program Files\Salt Project\Salt\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (
ImportError: DLL load failed while importing _device: The specified module could not be found.
Traceback (most recent call last):
  File "C:\Program Files\Salt Project\Salt\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Salt Project\Salt\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Salt Project\Salt\salt-call.exe\__main__.py", line 7, in <module>
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\scripts.py", line 444, in salt_call
    client.run()
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\cli\call.py", line 40, in run
    caller = salt.cli.caller.Caller.factory(self.config)
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\cli\caller.py", line 42, in factory
    return ZeroMQCaller(opts, **kwargs)
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\cli\caller.py", line 303, in __init__
    super().__init__(opts)
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\cli\caller.py", line 63, in __init__
    self.minion = salt.minion.SMinion(opts)
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\minion.py", line 928, in __init__
    io_loop.run_sync(lambda: self.eval_master(self.opts, failed=True))
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\ext\tornado\ioloop.py", line 459, in run_sync
    return future_cell[0].result()
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\ext\tornado\concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\ext\tornado\gen.py", line 309, in wrapper
    yielded = next(result)
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\minion.py", line 815, in eval_master
    pub_channel = salt.channel.client.AsyncPubChannel.factory(
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\channel\client.py", line 361, in factory
    transport = salt.transport.publish_client(opts, io_loop)
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\transport\base.py", line 87, in publish_client
    import salt.transport.zeromq
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\transport\zeromq.py", line 13, in <module>
    import zmq.error
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\zmq\__init__.py", line 136, in <module>
    from zmq import backend
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\zmq\backend\__init__.py", line 31, in <module>
    raise original_error from None
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\zmq\backend\__init__.py", line 26, in <module>
    _ns = select_backend(first)
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\zmq\backend\select.py", line 31, in select_backend
    mod = import_module(name)
  File "C:\Program Files\Salt Project\Salt\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (
ImportError: DLL load failed while importing _device: The specified module could not be found.
PS C:\Program Files\Salt Project\Salt>
```

**Comment by twangboy** [comment]
I've tried several times to replicate the initial issue. Are you able to replicate this behavior on another machine?

I wonder if it's leaving something behind in the registry. Could you try removing the following registry key on the affected machine:

```
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{E44C05F8-335A-4FD7-9F51-38CE114B194F}
```

**Comment by darkpixel** [comment]
When the installer was complaining that Salt was already installed, I went hunting for that key and didn't find it.

**Comment by twangboy** [comment]
The above PR fixes the issue with the stacktrace on the 3006.0RC3 package. Don't know how that got through.

Not sure why MSIEXEC thinks that package is still installed. Maybe there is an msiexec process still running? I know it sounds cliche, but... have you tried rebooting?

**Comment by darkpixel** [comment]
LOL--not cliche.  It's Windows.  But yeah, I did reboot and that didn't fix it.
I tried installing a different app that uses Windows Installer just to make sure there wasn't a "hanged" install, and the different app installed just fine.

Maybe this is just a one-off thing that's strange with my Windows VM.

I'll try to do some more testing later this week.

**Comment by twangboy** [comment]
OK. I'm going to close this issue. If you are able to reproduce on another machine, please feel free to re-open.

**Comment by darkpixel** [comment]
Sounds good to me!
