### ISSUE TITLE
[BUG] 3006 Cannot install deb files

### ISSUE THREAD

**Issue by DaAwesomeP** [saltstack/salt#64157]
**Description**
Since updating to 3006 on the minion I cannot install deb packages from files.

**Setup**
Master was first updated to 3006 without issue. Issue only appeared after updating the minion.

```yaml
mystate:
  pkg.installed:
    - sources:
      - libmypkg1: 'salt:/path/to/libmypkg1_0.1.0-1_amd64.deb'
      - mypkg: 'salt://path/to/mypkg_0.1.0-1_amd64.deb'
```

- [x] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [x] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
1. Update minion to 3006
2. Apply states

**Expected behavior**
Should install/evaluate states as normal

**Screenshots**
```
Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/state.py", line 2385, in call
                  ret = self.states[cdata["full"]](
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 149, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1232, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1247, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1280, in wrapper
                  return f(*args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/states/pkg.py", line 1701, in installed
                  result = _find_install_targets(
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/states/pkg.py", line 762, in _find_install_targets
                  cached_path = __salt__["cp.cache_file"](
              TypeError: salt.loaded.int.module.cp.cache_file() got multiple values for keyword argument 'saltenv'
```

**Versions Report**
<details><summary>salt --versions-report</summary>
On the minion:

```yaml
Salt Version:
          Salt: 3006.0
 
Python Version:
        Python: 3.10.11 (main, Apr 14 2023, 05:57:16) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
        relenv: 0.11.2
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 11 bullseye
        locale: utf-8
       machine: x86_64
       release: 5.10.0-21-amd64
        system: Linux
       version: Debian GNU/Linux 11 bullseye
```
</details>

**Additional context**
N/A

**Comment by OrangeDog** [comment]
Duplicates #64118
