### ISSUE TITLE
salt.loaded.int.returner.local_cache:147 An extra return was detected from minion . 

### ISSUE THREAD

**Issue by rimskij** [saltstack/salt#64205]
Unexpectedly sometimes massive errors occur.
 example error from master:
[salt.loaded.int.returner.local_cache:147 ][ERROR   ][219973] An extra return was detected from minion  { host }, please verify the minion, this could be a replay attack

From minion: tornado.application:353 ][ERROR   ][864115] Future <salt.ext.tornado.concurrent.Future object at 0x7fb644fe73d0> exception was never retrieved: Traceback (most recent call last):
  File "salt/ext/tornado/gen.py", line 1064, in run
    yielded = self.gen.throw(*exc_info)
  File "salt/minion.py", line 2697, in handle_event
    yield _minion.req_channel.send(
  File "salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info

Salt-master version 3005.1

**Comment by OrangeDog** [comment]
See also #62959

**Comment by dwoz** [comment]
Fixed by #69481 (merged 2026-06-18, in 3006.x/3007.x/3008.x/master). The "replay attack" ERROR on duplicate returns caused by minion retry after `SaltReqTimeoutError` is now logged at DEBUG when payloads match (the retry-after-timeout case in this report) and WARNING without the misleading wording otherwise. See salt/returners/local_cache.py::_log_duplicate_return.
