### ISSUE TITLE
[BUG] lgpo_reg state doesn't work with User policy

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#64200]
**Description**
The lgpo_reg state doesn't work when specifying the User policy class

**Setup**
Given the following state (mystate.sls):
```
set_reg_pol_value:
  lgpo_reg.value_present:
    - key: SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    - name: HideFileExt
    - v_data: 0
    - v_type: REG_DWORD
    - policy_class: User
```

**Steps to Reproduce the behavior**
Apply the state:
```
salt-call --local state.apply mystate
```

**Expected behavior**
The state should apply successfully

**Screenshots**
```
salt-call --local state.apply mystate
local:
----------
          ID: set_reg_pol_value
    Function: lgpo_reg.value_present
        Name: HideFileExt
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\state.py", line 2385, in call
                  ret = self.states[cdata["full"]](
                File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\loader\lazy.py", line 149, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\loader\lazy.py", line 1232, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\loader\lazy.py", line 1247, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\loader\lazy.py", line 1280, in wrapper
                  return f(*args, **kwargs)
                File "C:\Program Files\Salt Project\Salt\Lib\site-packages\salt\states\win_lgpo_reg.py", line 156, in value_present
                  if str(new["data"]) == v_data and new["type"] == v_type:
              KeyError: 'data'
     Started: 21:14:58.686519
    Duration: 101.512 ms
     Changes:

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time: 101.512 ms
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
3006.0
and head of 3006.x
```
</details>

**Comment by s0undt3ch** [comment]
Fix will be available in the upcoming 3006.1 release
