### ISSUE TITLE
[BUG] macOS requirements missing for Python 3.7 and 3.8

### ISSUE THREAD

**Issue by pjcreath** [saltstack/salt#64238]
**Description**
`pip install salt` fails on macOS unless using Python 3.9 or higher.

**Setup**
macOS 12.6.5 Monterey, fully updated

**Steps to Reproduce the behavior**
`pip install salt`
<details><summary>pip output</summary>

```
Collecting salt
  Using cached salt-3006.0.tar.gz (20.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      <string>:1265: UserWarning: Warning: distutils is deprecated and shall be removed in Python 3.12, advise migrate to using setuptools
      Traceback (most recent call last):
        File "/Users/user/test/env/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/user/test/env/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/user/test/env/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/rn/dg2d9lv48xjf7l001s7gk_yh0000gn/T/pip-build-env-_9mfc3cz/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/rn/dg2d9lv48xjf7l001s7gk_yh0000gn/T/pip-build-env-_9mfc3cz/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/rn/dg2d9lv48xjf7l001s7gk_yh0000gn/T/pip-build-env-_9mfc3cz/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/private/var/folders/rn/dg2d9lv48xjf7l001s7gk_yh0000gn/T/pip-build-env-_9mfc3cz/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 1268, in <module>
        File "/private/var/folders/rn/dg2d9lv48xjf7l001s7gk_yh0000gn/T/pip-build-env-_9mfc3cz/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/rn/dg2d9lv48xjf7l001s7gk_yh0000gn/T/pip-build-env-_9mfc3cz/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "<string>", line 901, in __init__
        File "<string>", line 907, in update_metadata
        File "<string>", line 1023, in _property_install_requires
        File "<string>", line 183, in _parse_requirements_file
      FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/rn/dg2d9lv48xjf7l001s7gk_yh0000gn/T/pip-install-zxdk26wo/salt_9103846c7b8e43aeafc1262d2c0b35c0/requirements/static/pkg/py3.8/darwin.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
</details>

Sure enough, https://github.com/saltstack/salt/tree/master/requirements/static/pkg/py3.7 and https://github.com/saltstack/salt/tree/master/requirements/static/pkg/py3.8 are both missing darwin.txt.  It's present for 3.9-3.11.

**Expected behavior**
Successful installation of salt.

**Versions Report**
n/a since I can't install, but this regression was introduced in 3005 and persists through 3006.

**Comment by mrakitin** [comment]
Experiencing the same problem with Python 3.8. Are there plans to fix it?

**Comment by OrangeDog** [comment]
3006.2 ([files.pythonhosted.org](https://files.pythonhosted.org/packages/b0/a0/1199833f647b3b1324408106daf726edcb3d29ce48220ef313532cb23cb6/salt-3006.2.tar.gz)) appears to have darwin requirements for 3.9, and 3.10.

No 3.7, 3.8, or 3.11 though.

**Comment by dwoz** [comment]
Cannot reproduce on current 3006.x/3007.x/3008.x/master. `pip install salt` no longer reads `requirements/static/pkg/py3.X/darwin.txt` — commit 1a00da6ec91 ("Migrate packaging metadata to PEP 621") moved install-requires selection into `tools/pkg/salt_build_backend.py`, which uses the top-level `requirements/darwin.txt` (present in the sdist) for the default `pip install` path. Verified against the current `salt-3006.27` sdist on PyPI. Python 3.8 also reached upstream EOL 2024-10-07; supported Python range is 3.9+.
