### ISSUE TITLE
salt-ssh "target" test.ping -> produces "SyntaxError: future feature annotations is not defined"

### ISSUE THREAD

**Issue by perfecto25** [saltstack/salt#64272]
**Description**
when running salt-ssh basic test.ping, getting the following

```
root@saltmaster /h/salt salt-ssh -i qbtm-us2 test.ping
qbtm-us2:
    ----------
    retcode:
        1
    stderr:
        Traceback (most recent call last):
          File "/var/tmp/.salt_353866_salt/salt-call", line 26, in <module>
            from salt.scripts import salt_call
          File "/var/tmp/.salt_353866_salt/pyall/salt/__init__.py", line 140, in <module>
            import salt._logging  # isort:skip
          File "/var/tmp/.salt_353866_salt/pyall/salt/_logging/__init__.py", line 12, in <module>
            from salt._logging.impl import (
          File "/var/tmp/.salt_353866_salt/pyall/salt/_logging/impl.py", line 28, in <module>
            from salt._logging.handlers import DeferredStreamHandler  # isort:skip
          File "/var/tmp/.salt_353866_salt/pyall/salt/_logging/handlers.py", line 16, in <module>
            from salt.utils.versions import warn_until_date
          File "/var/tmp/.salt_353866_salt/pyall/salt/utils/versions.py", line 18, in <module>
            import looseversion
          File "/var/tmp/.salt_353866_salt/py3/looseversion/__init__.py", line 19
            from __future__ import annotations
            ^
        SyntaxError: future feature annotations is not defined
    stdout:
```

**Setup**

master - running on physical Rocky 9 linux
agent - running on ec2 with Centos 7

both servers have salt installed via virtualenv py pkgs

master is on py3.9

agent is py 3.6.8

**Steps to Reproduce the behavior**
from master, run salt-ssh "target" test.ping

**Versions Report**

master
```
root@saltmaster /h/salt salt-master --versions-report
Salt Version:
          Salt: 3006.1
 
Python Version:
        Python: 3.9.14 (main, Jan  9 2023, 00:00:00)
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.1.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.4
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 23.1
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.15.0
        pygit2: Not Installed
  python-gnupg: Not Installed
        PyYAML: 6.0
         PyZMQ: 25.0.2
        relenv: Not Installed
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: rocky 9.1 Blue Onyx
        locale: utf-8
       machine: x86_64
       release: 5.14.0-162.12.1.el9_1.0.2.x86_64
        system: Linux
       version: Rocky Linux 9.1 Blue Onyx
```

agent

```
Salt Version:
          Salt: 3004
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.0.2
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.11.0
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 6.0
         PyZMQ: 21.0.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.3
 
System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-1160.71.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core
```

**Comment by anilsil** [comment]
Salt 3004 is out of support, if you can test this with 3006.1 and confirm if issues still exists we'll plan this in upcoming releases.

**Comment by perfecto25** [comment]
upgraded agent to 3006.1 and not seeing this issue anymore, thanks
