### ISSUE TITLE
[BUG] Salt minion fails to start with "AttributeError: 'dict' object has no attribute 'select'" after update to salt-3005.1-4.fc37.noarch on Fedora 37

### ISSUE THREAD

**Issue by dukhat2259** [saltstack/salt#64437]
**Description**
I have 8 VMs with fedora 37. All their salt minions stopped working a few days ago.

```
# tail /var/log/salt/minion
2023-06-04 06:34:08,077 [salt.utils.parsers:284 ][ERROR   ][930] 'dict' object has no attribute 'select'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/salt/utils/parsers.py", line 212, in parse_args
    mixin_after_parsed_func(self)
  File "/usr/lib/python3.11/site-packages/salt/utils/parsers.py", line 905, in __setup_logging
    salt._logging.setup_logging()
  File "/usr/lib/python3.11/site-packages/salt/_logging/impl.py", line 971, in setup_logging
    setup_extended_logging(opts)
  File "/usr/lib/python3.11/site-packages/salt/_logging/impl.py", line 878, in setup_extended_logging
    providers = salt.loader.log_handlers(opts)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/salt/loader/__init__.py", line 857, in log_handlers
    _module_dirs(
  File "/usr/lib/python3.11/site-packages/salt/loader/__init__.py", line 153, in _module_dirs
    for entry_point in entrypoints.iter_entry_points("salt.loader"):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/salt/utils/entrypoints.py", line 29, in _wrapped
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/salt/utils/entrypoints.py", line 51, in iter_entry_points
    for entry_point in entry_points.select(group=group):
                       ^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'select'
```

**Setup**

Minon config different from default:
```
master: {{ pillar['saltmaster_hostname'] }}
backup_mode: minion
saltenv: {{ opts['saltenv'] | default(saltenv, True) | tojson }}
pillarenv_from_saltenv: True
state_output: changes
log_level: info
```

Running on proxmox KVM VMs. Fedora 37 server installations.
Reported as https://bugzilla.redhat.com/show_bug.cgi?id=2212190 , but that appears to be genuinely ignored.

**Steps to Reproduce the behavior**
Since it happened on 8 VMs at roughly the same time due to dnf auto upgrade a basic fedora 37 installation updated to the latest should suffice. Minions are installed as rpm salt-3005.1-4.fc37.noarch 

**Expected behavior**
Able to start minion

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```
# salt-call --versions-report
/usr/lib/python3.11/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 8, in <module>
    sys.exit(salt_call())
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/salt/scripts.py", line 441, in salt_call
    client.run()
  File "/usr/lib/python3.11/site-packages/salt/cli/call.py", line 18, in run
    self.parse_args()
  File "/usr/lib/python3.11/site-packages/salt/utils/parsers.py", line 175, in parse_args
    self.print_versions_report()
  File "/usr/lib/python3.11/site-packages/salt/utils/parsers.py", line 251, in print_versions_report
    print("\n".join(version.versions_report()), file=file, flush=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/salt/version.py", line 857, in versions_report
    ver_info = versions_information(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/salt/version.py", line 847, in versions_information
    extensions_info = extensions_information()
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/salt/version.py", line 823, in extensions_information
    for entry_point in salt.utils.entrypoints.iter_entry_points("salt.loader"):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/salt/utils/entrypoints.py", line 29, in _wrapped
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/salt/utils/entrypoints.py", line 51, in iter_entry_points
    for entry_point in entry_points.select(group=group):
                       ^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'select'
[ERROR   ] An un-handled exception was caught by Salt's global exception handler:
AttributeError: 'dict' object has no attribute 'select'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 8, in <module>
    sys.exit(salt_call())
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/salt/scripts.py", line 441, in salt_call
    client.run()
  File "/usr/lib/python3.11/site-packages/salt/cli/call.py", line 18, in run
    self.parse_args()
  File "/usr/lib/python3.11/site-packages/salt/utils/parsers.py", line 175, in parse_args
    self.print_versions_report()
  File "/usr/lib/python3.11/site-packages/salt/utils/parsers.py", line 251, in print_versions_report
    print("\n".join(version.versions_report()), file=file, flush=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/salt/version.py", line 857, in versions_report
    ver_info = versions_information(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/salt/version.py", line 847, in versions_information
    extensions_info = extensions_information()
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/salt/version.py", line 823, in extensions_information
    for entry_point in salt.utils.entrypoints.iter_entry_points("salt.loader"):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/salt/utils/entrypoints.py", line 29, in _wrapped
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/salt/utils/entrypoints.py", line 51, in iter_entry_points
    for entry_point in entry_points.select(group=group):
                       ^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'select'
```
</details>

**Comment by dukhat2259** [comment]
After being silently ignored like all my other bug reports, there is now suddenly a fix offered at https://bugzilla.redhat.com/show_bug.cgi?id=2212190.

**Comment by OrangeDog** [comment]
Duplicate: #62851
