### ISSUE TITLE
[BUG] TypeError: cannot pickle 'SSLContext' object when running napalm ros proxy minion when uring HTTPS

### ISSUE THREAD

**Issue by ggiesen** [saltstack/salt#64549]
**Description**
When I issue a command to a napalm ros proxy minion (for example `net.ping 8.8.8.8`, I receive the following error:

```
TypeError: cannot pickle 'SSLContext' object when running napalm ros proxy minion
```

```
[DEBUG   ] dummy proxy __virtual__() called...
[DEBUG   ] The functions from module 'napalm' are being loaded by dir() on the loaded module
[INFO    ] nxos proxy __virtual__() called...
[DEBUG   ] rest_sample proxy __virtual__() called...
[INFO    ] ssh_sample proxy __virtual__() called...
[DEBUG   ] Setting up NAPALM connection
[DEBUG   ] <--- '/login'
[DEBUG   ] <--- '=name=admin'
[DEBUG   ] <--- '=password=Iecee3quoh1Aimoh'
[DEBUG   ] <--- EOS
[DEBUG   ] ---> '!done'
[DEBUG   ] ---> EOS
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from /etc/salt/proxy
[DEBUG   ] Including configuration from '/etc/salt/proxy.d/mikrominion/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/proxy.d/mikrominion/_schedule.conf
[DEBUG   ] Including configuration from '/etc/salt/proxy.d/mikrominion/mikrominion.conf'
[DEBUG   ] Reading configuration from /etc/salt/proxy.d/mikrominion/mikrominion.conf
Traceback (most recent call last):
  File "/bin/salt-call", line 11, in <module>
    sys.exit(salt_call())
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/scripts.py", line 444, in salt_call
    client.run()
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/cli/call.py", line 40, in run
    caller = salt.cli.caller.Caller.factory(self.config)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/cli/caller.py", line 42, in factory
    return ZeroMQCaller(opts, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/cli/caller.py", line 303, in __init__
    super().__init__(opts)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/cli/caller.py", line 61, in __init__
    self.minion = salt.minion.SProxyMinion(opts)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 929, in __init__
    self.gen_modules(initial_load=True, context=context)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 3983, in gen_modules
    self.opts["grains"] = salt.loader.grains(self.opts, proxy=self.proxy)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/__init__.py", line 1106, in grains
    funcs = grain_funcs(
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/__init__.py", line 967, in grain_funcs
    _utils = utils(opts, proxy=proxy)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/__init__.py", line 534, in utils
    return LazyLoader(
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 249, in __init__
    opts = copy.deepcopy(opts)
  File "/opt/saltstack/salt/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/opt/saltstack/salt/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/opt/saltstack/salt/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/opt/saltstack/salt/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/opt/saltstack/salt/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/opt/saltstack/salt/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/opt/saltstack/salt/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/opt/saltstack/salt/lib/python3.10/copy.py", line 238, in _deepcopy_method
    return type(x)(x.__func__, deepcopy(x.__self__, memo))
  File "/opt/saltstack/salt/lib/python3.10/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle 'SSLContext' object
```

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)
_proxy.conf_
```
proxy:
  proxytype: napalm
  driver: ros
  host: 192.0.2.1
  username: admin
  passwd: Iecee3quoh1Aimoh
  multiprocessing: False
  optional_args:
    transport: https
    use_ssl_cert: False
```

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [x] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [x] onedir packaging
- [x] used bootstrap to install

**Steps to Reproduce the behavior**
```
# salt-call --proxyid=mikrominion test.ping 8.8.8.8
```

**Expected behavior**
```
# salt-call --proxyid=mikrominion test.ping 8.8.8.8
local:
    ----------
    comment:
    out:
        ----------
        success:
            ----------
            packet_loss:
                100
            probes_sent:
                5
            results:
                |_
                  ----------
                  ip_address:
                      8.8.8.8
                  rtt:
                      -1.0
                |_
                  ----------
                  ip_address:
                      8.8.8.8
                  rtt:
                      -1.0
                |_
                  ----------
                  ip_address:
                      8.8.8.8
                  rtt:
                      -1.0
                |_
                  ----------
                  ip_address:
                      8.8.8.8
                  rtt:
                      -1.0
                |_
                  ----------
                  ip_address:
                      8.8.8.8
                  rtt:
                      -1.0
            rtt_avg:
                -1.0
            rtt_max:
                -1.0
            rtt_min:
                -1.0
            rtt_stddev:
                -1.0
    result:
        True
```

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3006.1

Python Version:
        Python: 3.10.11 (main, May  5 2023, 02:31:54) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
        relenv: 0.12.3
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: almalinux 9.2 Turquoise Kodkod
        locale: utf-8
       machine: x86_64
       release: 5.14.0-284.11.1.el9_2.x86_64
        system: Linux
       version: AlmaLinux 9.2 Turquoise Kodkod
```
</details>

**Additional context**
Works without issue if I use HTTP transport.

Opened an issue on the `napalm-ros` side here:

https://github.com/napalm-automation-community/napalm-ros/issues/119

**Comment by OrangeDog** [comment]
Did you mean to leak the password?

**Comment by ggiesen** [comment]
> Did you mean to leak the password?

It's anonymized.

**Comment by dwoz** [comment]
Fix merged and shipped in a supported release. Closing per bulk triage. Reopen if this reproduces on a currently supported release (3006.x, 3007.x, 3008.x, master).
