### ISSUE TITLE
[BUG] New chocolatey version (2.x) - chocolatey states fail with an error

### ISSUE THREAD

**Issue by AGirin** [saltstack/salt#64622]
**Description**
States that ran fine with older version of chocolatey are now failing with latest chocolatey installed.

State that fails: 

```include:
  - {{ include }}
...
telegraf:
  {{ pkg }}:
    {{ refresh }}
    - source: 'Private source'
    - require:
      - sls: {{ include }}
    - version: some version
  service.running:
    - enable: True
    - watch:
      - {{ watch_pkg }}: telegraf
```

This state works just fine on older chocolatey... But with new one we get this:

``` ID: telegraf
    Function: chocolatey.installed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\state.py", line 2385, in call
                  ret = self.states[cdata["full"]](
                File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\loader\lazy.py", line 149, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\loader\lazy.py", line 1232, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\loader\lazy.py", line 1247, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\loader\lazy.py", line 1280, in wrapper
                  return f(*args, **kwargs)
                File "C:\Program Files\Salt Project\Salt\Lib\site-packages\salt\states\chocolatey.py", line 118, in installed
                  version_info = __salt__["chocolatey.version"](
                File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\loader\lazy.py", line 149, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\loader\lazy.py", line 1232, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\loader\lazy.py", line 1247, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "C:\Program Files\Salt Project\Salt\Lib\site-packages\salt\modules\chocolatey.py", line 1115, in version
                  available = list_(narrow=name, pre_versions=pre_versions, source=source)
                File "C:\Program Files\Salt Project\Salt\Lib\site-packages\salt\modules\chocolatey.py", line 488, in list_
                  raise CommandExecutionError(err)
              salt.exceptions.CommandExecutionError: Running chocolatey failed: When using the '--source' option with the 'choco list' command, only a named alternative source can be provided.
```

Looks like commands that choleatey uses changed with the new version...

Old version:
```sudo salt 'server id*' cmd.run 'choco list telegraf --source PRIVATE_SOURCE' shell=powershell 

    Chocolatey v0.11.3
    telegraf 1.27.1 [Approved] Downloads cached for licensed users
    1 packages found.
```

New version:
```salt 'second server id*' cmd.run 'choco list telegraf --source PRIVATE_SOURCE' shell=powershell

    Chocolatey v2.1.0
    When using the '--source' option with the 'choco list' command, only a named alternative source can be provided.
```
   
  Looks like salt module will have to be updated to work with new chocolatey version...

**Comment by AGirin** [comment]
For the record - I "fixed" it by removing this from chocolatey.py (under Install section):

```        version_info = __salt__["chocolatey.version"](
            name=name, check_remote=True, source=source
        )
to:
        version_info = __salt__["chocolatey.version"](
            name=name, check_remote=True
        )
        
```

**Comment by AGirin** [comment]
And this happens to all version of salt once Chocolatey is upgraded to 2.x..

**Comment by twangboy** [comment]
Hey @AGirin, thanks for reporting this issue. I'm working on a fix for this: https://github.com/saltstack/salt/pull/64673

Would you mind verifying those changes fix the issue for you?

**Comment by AGirin** [comment]
@twangboy Sure. Let me tkae a look at it.

**Comment by AGirin** [comment]
@twangboy I think you fixed module section.. We have issues with state one as well...

**Comment by AGirin** [comment]
@twangboy Unfortunately it does not seem to work... It does not error out now but I get nothing back..

```
sudo salt 'SERVER*' chocolatey.version telegraf
SERVER:
    ----------
```

Expected reslt is this:

```
SERVER:
    ----------
    telegraf:
        - 1.27.1

```

**Comment by twangboy** [comment]
OK, I think that's fixed here: https://github.com/saltstack/salt/pull/64922

**Comment by AGirin** [comment]
@twangboy I upgraded to 3006.2. Upraded choloatey to 2.2.2 and no luck...

```
chocolatey.chocolatey_version
<server>:
    ERROR: Chocolatey not installed. Use chocolatey.bootstrap to install the Chocolatey package manager.

chocolatey.version telegraf
<server>:
    ERROR: Chocolatey not installed. Use chocolatey.bootstrap to install the Chocolatey package manager.

chocolatey.bootstrap
<server>:
    WARNING: 'choco' was found at 'C:\ProgramData\chocolatey\bin\choco.exe'.
    WARNING: An existing Chocolatey installation was detected. Installation will not continue.

    For security reasons, this script will not overwrite existing installations.
```

So... Chocolatey is installed... But it is not.. 

Running commands on the server itself from PowerShell confirms that chocolatey is installed: 

```
choco info telegraf
Chocolatey v2.2.2
telegraf 1.27.4 [Approved] Downloads cached for licensed users.
```

**Comment by AGirin** [comment]
My "fix" still works though...
