### ISSUE TITLE
[BUG] Crash in win_pki: string indices must be integers

### ISSUE THREAD

**Issue by prensing** [saltstack/salt#64933]
**Description**
Trying to use win_pki to import a certificate into the key store. The module and state produce the same error, although the state gives a traceback.

The command is basically: 
```salt xx win_pki.import_cert name='salt://certificates/yyy.pfx' cert_format='pfx'```
which gives the error:
  Passed invalid arguments to win_pki.import_cert: string indices must be integers

If I do the same thing with a state file, I get the traceback:
```
xx:
----------
          ID: store_certificate
    Function: win_pki.import_cert
        Name: salt://certificates/yyy.pfx
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "C:\Program Files\Salt Project\Salt\bin\lib\site-packages\salt\state.py", line 2276, in call
                  ret = self.states[cdata["full"]](
                File "C:\Program Files\Salt Project\Salt\bin\lib\site-packages\salt\loader\lazy.py", line 149, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "C:\Program Files\Salt Project\Salt\bin\lib\site-packages\salt\loader\lazy.py", line 1228, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "C:\Program Files\Salt Project\Salt\bin\lib\site-packages\salt\loader\lazy.py", line 1243, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "C:\Program Files\Salt Project\Salt\bin\lib\site-packages\salt\loader\lazy.py", line 1276, in wrapper
                  return f(*args, **kwargs)
                File "C:\Program Files\Salt Project\Salt\bin\Lib\site-packages\salt\states\win_pki.py", line 77, in import_cert
                  cert_props = __salt__["win_pki.get_cert_file"](
                File "C:\Program Files\Salt Project\Salt\bin\lib\site-packages\salt\loader\lazy.py", line 149, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "C:\Program Files\Salt Project\Salt\bin\lib\site-packages\salt\loader\lazy.py", line 1228, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "C:\Program Files\Salt Project\Salt\bin\lib\site-packages\salt\loader\lazy.py", line 1243, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "C:\Program Files\Salt Project\Salt\bin\Lib\site-packages\salt\modules\win_pki.py", line 245, in get_cert_file
                  ret[key.lower()] = item[key]
              TypeError: string indices must be integers
     Started: 12:08:51.160840
    Duration: 2172.106 ms
     Changes:   
```

**Setup**
Relevant state entry:
```
store_certificate:
  win_pki.import_cert:
    - name: salt://certificates/{{ salt['pillar.get']('ssl_certificate:cert_name') }}.pfx
    - cert_format: pfx
    - context: LocalMachine
    - store: My
    - password: ''
```

Please be as specific as possible and give set-up details.

- [ x] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ x] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

**Expected behavior**
This worked fine in version 3004 (I think).

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
Salt on Windows:  version 3005.1

From the master:
```Salt Version:
          Salt: 3006.1
 
Python Version:
        Python: 3.10.11 (main, May  5 2023, 02:31:54) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
        relenv: 0.12.3
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: ubuntu 22.04.2 jammy
        locale: utf-8
       machine: x86_64
       release: 5.15.0-78-generic
        system: Linux
       version: Ubuntu 22.04.2 jammy
 ```
</details>

**Additional context**

**Comment by prensing** [comment]
More info: it is a bug in Salt, but it seems to be triggered by a problem with importing the certificate.

I tried to import the certificate manually using the GUI and it failed. Turns out the certificate is not compatible with older Windows (see https://stackoverflow.com/questions/69343254/the-password-you-entered-is-incorrect-when-importing-pfx-files-to-windows-cer). When I followed the instructions to create a compatible "legacy" certificate, the import worked.

**Comment by twangboy** [comment]
I generated a `.pfx` certificate:
```
# Generate the certificate
(venv) PS C:\src\salt> $certname = "test.pfx"
(venv) PS C:\src\salt> $cert = New-SelfSignedCertificate -Subject "CN=$certname" -CertStoreLocation "Cert:\CurrentUser\My" -KeyExportPolicy Exportable -KeySpec Signature -KeyLength 2048 -KeyAlgorithm RSA -HashAlgorithm SHA256

# Export the PFX certificate
(venv) PS C:\src\salt> $mypwd = ConvertTo-SecureString "PassWord1!" -Force -AsPlainText
(venv) PS C:\src\salt> Export-PfxCertificate -Cert $cert -FilePath 'C:\ProgramData\Salt Project\Salt\srv\salt\certs\test.pfx' -Password $mypwd

# Remove the certificate from the Cert Store
(venv) PS C:\src\salt> Get-ChildItem -Path Cert:\CurrentUser\My | Where-Object {$_.Subject -match "$certname"} | Select-Object Thumbprint, FriendlyName

Thumbprint                               FriendlyName
----------                               ------------
54C193F6A11F0D29D613362F43E7223F1477FEF9


(venv) PS C:\src\salt> Remove-Item -Path Cert:\CurrentUser\My\54C193F6A11F0D29D613362F43E7223F1477FEF9 -DeleteKey
```

Now I have a certificate. Let's try to add it to the minion:
```
(venv) PS C:\src\salt> salt * win_pki.import_cert name='salt://certs/test.pfx' cert_format='pfx'
dev15:
    Passed invalid arguments to win_pki.import_cert: string indices must be integers

        Import the certificate file into the given certificate store.

        :param str name: The path of the certificate file to import.
        :param str cert_format: The certificate format. Specify 'cer' for X.509, or
            'pfx' for PKCS #12.
        :param str context: The name of the certificate store location context.
        :param str store: The name of the certificate store.
        :param bool exportable: Mark the certificate as exportable. Only applicable
            to pfx format.
        :param str password: The password of the certificate. Only applicable to pfx
            format. Note that if used interactively, the password will be seen by all minions.
            To protect the password, use a state and get the password from pillar.
        :param str saltenv: The environment the file resides in.

        :return: A boolean representing whether all changes succeeded.
        :rtype: bool

        CLI Example:

        .. code-block:: bash

            salt '*' win_pki.import_cert name='salt://cert.cer'
ERROR: Minions returned with non-zero exit code
```

Hmm... something's not right... looks like a similar error... wait, I set a password for my cert... let's try passing the password:
```
(venv) PS C:\src\salt> salt * win_pki.import_cert name='salt://certs/test.pfx' cert_format='pfx' password='PassWord1!'
dev15:
    True
```
Ah, that worked... so, first I need to see what that error code was and have it give a better error.
And I think I need instructions on how to generate a `.pfx` certificate that is not compatible with Windows 10. Or perhaps we need the versions report for the minion you're running this on instead of the master.

Let's see if I can get the same stacktrace. I'm gonna remove the certificate. We'll need to use the thumbprint from above:
```
(venv) PS C:\src\salt> salt * win_pki.remove_cert 54C193F6A11F0D29D613362F43E7223F1477FEF9
dev15:
    True
```

Now let's import the certificate on the minion using salt-call instead of running from the master.
```
PS C:\src\salt> salt-call win_pki.import_cert name='salt://certs/test.pfx' cert_format='pfx'
```
That gives me the same return as the command from the master... let's add `-l debug`:
```
PS C:\src\salt> salt-call win_pki.import_cert name='salt://certs/test.pfx' cert_format='pfx' -l debug
```
OK, now I'm seeing the stacktrace in the debug output.
```
[DEBUG   ] stderr: Get-PfxCertificate : Windows PowerShell is in NonInteractive mode. Read and Prompt functionality is not available.
At line:1 char:75
+ ... putObject @(Get-PfxCertificate -FilePath 'C:\salt\var\cache\salt\mini ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-PfxCertificate], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,Microsoft.PowerShell.Commands.GetPfxCertificateCommand
[ERROR   ] Unable to parse return data as Json.

Passed invalid arguments: string indices must be integers.

Usage:

    Import the certificate file into the given certificate store.

    :param str name: The path of the certificate file to import.
    :param str cert_format: The certificate format. Specify 'cer' for X.509, or
        'pfx' for PKCS #12.
    :param str context: The name of the certificate store location context.
    :param str store: The name of the certificate store.
    :param bool exportable: Mark the certificate as exportable. Only applicable
        to pfx format.
    :param str password: The password of the certificate. Only applicable to pfx
        format. Note that if used interactively, the password will be seen by all minions.
        To protect the password, use a state and get the password from pillar.
    :param str saltenv: The environment the file resides in.

    :return: A boolean representing whether all changes succeeded.
    :rtype: bool

    CLI Example:

    .. code-block:: bash

        salt '*' win_pki.import_cert name='salt://cert.cer'

Traceback (most recent call last):
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\cli\caller.py", line 202, in call
    ret["return"] = self.minion.executors[fname](
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\loader\lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\loader\lazy.py", line 1232, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\loader\lazy.py", line 1247, in _run_as
    return _func_or_method(*args, **kwargs)
  File "C:\Program Files\Salt Project\Salt\Lib\site-packages\salt\executors\direct_call.py", line 10, in execute
    return func(*args, **kwargs)
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\loader\lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\loader\lazy.py", line 1232, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\loader\lazy.py", line 1247, in _run_as
    return _func_or_method(*args, **kwargs)
  File "C:\Program Files\Salt Project\Salt\Lib\site-packages\salt\modules\win_pki.py", line 307, in import_cert
    cert_props = get_cert_file(name=cached_source_path, cert_format=cert_format)
  File "C:\Program Files\Salt Project\Salt\Lib\site-packages\salt\modules\win_pki.py", line 245, in get_cert_file
    ret[key.lower()] = item[key]
TypeError: string indices must be integers
```
Looks like there's an error running the powershell command that isn't caught, and then it tries to parse the output later on.

This module hasn't been touched since 2016. There's probably a lot of work that could be done here to modernize this module and state.

**Comment by twangboy** [comment]
Should be fixed by the above PR.
