### ISSUE TITLE
[BUG] x509_v2.certificate_managed says m2crypto is unavailable, but everything else says it's installed

### ISSUE THREAD

**Issue by darkpixel** [saltstack/salt#65011]
**Description**

x509_v2.certificate_managed says m2crypto is unavailable, but everything else says m2crypto is installed

**Setup**
```
# salt-call --versions-report
Salt Version:
          Salt: 3006.1
 
Python Version:
        Python: 3.10.11 (main, May  5 2023, 02:31:54) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: 0.38.0   <---- installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
        relenv: 0.12.3
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 11 bullseye
        locale: utf-8
       machine: x86_64
       release: 5.15.107-2-pve
        system: Linux
       version: Debian GNU/Linux 11 bullseye
#
```

Pip also thinks it's installed in the saltstack virtual env:
```
#  /opt/saltstack/salt/bin/pip install m2crypto
Requirement already satisfied: m2crypto in /opt/saltstack/salt/lib/python3.10/site-packages (0.38.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip available: 22.3.1 -> 23.2.1
[notice] To update, run: /opt/saltstack/salt/bin/../bin/python3.10 -m pip install --upgrade pip
#
```

Even though salt should be looking in its virtual env, the system also has it installed:
```
# dpkg -l | grep -i m2crypto
ii  python3-m2crypto                     0.37.1-2                                   amd64        Python wrapper for the OpenSSL library (Python 3 modules)
#
```

State:

```
# cert-test.sls

/etc/ssl/certs/{{ salt['grains.get']('id') }}.pem:
  x509.certificate_managed:
    - mode: 0640
    - owner: root
    - group: ssl-cert
    - public_key: /etc/ssl/private/{{ salt['grains.get']('id') }}.key
    - ca_server: salt.--redacted--.com
    - signing_policy: test1
    - CN: {{ salt['grains.get']('id') }}
    - subjectAltName: 'DNS:{{ salt['grains.get']('id') }}, IP:{{ salt['grains.get']('ip4_interfaces:vmbr0')[0] }}, DNS:{{ salt['grains.get']('id')[0:7] }}rtr01.--redacted--'
    - days_valid: 30
    - days_remaining: 14
    - backup: False
```

**Steps to Reproduce the behavior**

```salt-call -l info state.sls cert-test```

```
----------
          ID: /etc/ssl/certs/--redacted--.pem
    Function: x509.certificate_managed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/state.py", line 2385, in call
                  ret = self.states[cdata["full"]](
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 149, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1232, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1247, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1280, in wrapper
                  return f(*args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/states/x509.py", line 709, in certificate_managed
                  contents = __salt__["x509.create_certificate"](text=True, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 149, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1232, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1247, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/modules/x509.py", line 1484, in create_certificate
                  raise salt.exceptions.SaltInvocationError(cert_txt)
              salt.exceptions.SaltInvocationError: 'x509' __virtual__ returned False: Could not load x509 module, m2crypto unavailable
```

x509_v2 is enabled in the minino's pillar per the docs:
```
# salt-call -l info pillar.get features
local:
    ----------
    x509_v2:
        True
```

**Comment by lkubb** [comment]
Note: The `x509_v2` modules don't rely on `m2crypto`. `features` has to be set in the Salt configuration, not in the Pillar, hence you're using the deprecated `x509` ones.

`m2crypto` should still be importable if it's reported as installed though.

**Comment by darkpixel** [comment]
*facepalm*

I missed this line:
```
# /etc/salt/minion.d/x509.conf
```
Here: https://docs.saltproject.io/en/master/ref/modules/all/salt.modules.x509_v2.html

Sorry for the noise.
