### ISSUE TITLE
[BUG] python-ldap module install fails in onedir 3006.2

### ISSUE THREAD

**Issue by Galewind** [saltstack/salt#65025]
**Description**
I upgraded my salt Master from 3005.2 (classic) to 3006.2 (onedir) and tried to install python-ldap for our SaltGUI's authentication using salt-pip.

**Setup**
The VM runs Debian 11 and uses salt-master/stable,now 3006.2 amd64 

- [ ] on-prem machine
- [x] VM (Proxmox Virtual Environment 7.4.13)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [x] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
salt-pip install python-ldap

<details>
```debian@saltmaster01:/etc/salt/master.d (master) $ salt-pip install python-ldap
Collecting python-ldap
  Using cached python-ldap-3.4.3.tar.gz (377 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Error in sitecustomize; set PYTHONVERBOSE for traceback:
      TypeError: expected str, bytes or os.PathLike object, not NoneType
      Fatal Python error: init_import_site: Failed to import the site module
      Python runtime state: initialized
      Traceback (most recent call last):
        File "/opt/saltstack/salt/lib/python3.10/site.py", line 617, in <module>
          main()
        File "/opt/saltstack/salt/lib/python3.10/site.py", line 610, in main
          execsitecustomize()
        File "/opt/saltstack/salt/lib/python3.10/site-packages/relenv/runtime.py", line 746, in wrapper
          import sitecustomize
        File "/tmp/pip-build-env-p0cbi0vs/site/sitecustomize.py", line 23, in <module>
          site.addsitedir(path)
        File "/opt/saltstack/salt/lib/python3.10/site.py", line 216, in addsitedir
          sitedir, sitedircase = makepath(sitedir)
        File "/opt/saltstack/salt/lib/python3.10/site.py", line 97, in makepath
          dir = os.path.join(*paths)
        File "/opt/saltstack/salt/lib/python3.10/posixpath.py", line 76, in join
          a = os.fspath(a)
      TypeError: expected str, bytes or os.PathLike object, not NoneType
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```
</details>
**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3006.2
 
Python Version:
        Python: 3.10.12 (main, Aug  3 2023, 21:47:10) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.13.3
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 11 bullseye
        locale: utf-8
       machine: x86_64
       release: 5.10.0-25-amd64
        system: Linux
       version: Debian GNU/Linux 11 bullseye
```
</details>

**Additional context**

**Comment by MKLeb** [comment]
related: https://github.com/saltstack/salt/issues/64962

**Comment by sticky-note** [comment]
Same here with `Debian 12` and salt `3006.6`, this is not related at all on issue #64962.
Temporary workaround is to pin python-ldap version to `v3.1.4`
```
salt-pip install python-ldap==3.1.4
```
But this version seems to be too old, security patches has been applied on versions `4.x.x`

**Comment by chateaulav** [comment]
> Same here with `Debian 12` and salt `3006.6`, this is not related at all on issue #64962. Temporary workaround is to pin python-ldap version to `v3.3.1`
> 
> ```
> salt-pip install python-ldap==3.3.1
> ```
> 
> But this version seems to be too old, security patches has been applied on versions `4.x.x`
> 
> I figured out another solution, installing python-ldap `v3.4.4` with pip `v22.3.1` is working:
> 
> ```
> # Working on fresh Debian bookworm install:
> apt install gcc libldap2-dev libsasl2-dev
> salt-pip install pip==22.3.1  # Downgrade pip on salt `3006.6` installation
> salt-pip install python-ldap
> salt-pip install -U pip
> ```

pinning pip at `22.3.1` solved for me

**Comment by baby-gnu** [comment]
Related to https://github.com/saltstack/relenv/issues/182 ?

**Comment by dwoz** [comment]
Underlying relenv issue (saltstack/relenv#182) fixed by saltstack/relenv#183 (June 2024). All supported Salt branches ship relenv 0.22.14+ which contains the fix (3006.x is on 0.22.16). Closing as fixed via the relenv bump — please reopen if reproducible against a current onedir build.
