### ISSUE TITLE
[BUG] metadata grains failing since 3006.3

### ISSUE THREAD

**Issue by c42-adam** [saltstack/salt#65184]
**Description**
metadata grain is not returning successfully since 3006.3. This did work in 3006.2.

**Setup**
EC2 host in AWS
`metadata_server_grains: True` in minion config

**Steps to Reproduce the behavior**
```
$ sudo salt-call grains.get dynamic:instance-identity --out=json
[CRITICAL] Failed to load grains defined in grain file metadata.metadata in function <LoadedFunc name='metadata.metadata'>, error:
Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/__init__.py", line 1150, in grains
    ret = funcs[key](**kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 159, in __call__
    ret = self.loader.run(run_func, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1245, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1260, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/grains/metadata.py", line 87, in metadata
    return _search()
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/grains/metadata.py", line 64, in _search
    ret[line] = _search(prefix=os.path.join(prefix, line + "/"))
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/grains/metadata.py", line 53, in _search
    linedata["headers"].get("Content-Type", "text/plain")
KeyError: 'headers'
{
    "local": ""
}
```

**Expected behavior**
command should return some valid json, along the lines of:
```json
{
  "accountId" : "xxx",
  "architecture" : "x86_64",
  "availabilityZone" : "us-east-1a",
  "billingProducts" : null,
  "devpayProductCodes" : null,
  "marketplaceProductCodes" : null,
  "imageId" : "ami-xxx",
  "instanceId" : "i-xxx",
  "instanceType" : "t2.large",
  "kernelId" : null,
  "pendingTime" : "2023-05-02T13:54:39Z",
  "privateIp" : "xxx.xxx.xxx.xxx",
  "ramdiskId" : null,
  "region" : "us-east-1",
  "version" : "2017-09-30"
}
```

Curl commands against the metadata API return expected results.
`curl http://169.254.169.254/latest/dynamic/instance-identity/document/`

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3006.3

Python Version:
        Python: 3.10.13 (main, Sep  6 2023, 02:11:27) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.14.6
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.13.10
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: ubuntu 22.04.3 jammy
        locale: utf-8
       machine: x86_64
       release: 6.2.0-1009-aws
        system: Linux
       version: Ubuntu 22.04.3 jammy
```
</details>

**Comment by c42-adam** [comment]
Still an issue in 3006.4, though it's no longer throwing a stack trace. It just returns an empty object instead of the correct data.

```
$ sudo salt-call grains.get dynamic:instance-identity --out=json
{
    "local": ""
}
```

<details>
<summary>salt --versions-report</summary>

```
Salt Version:
          Salt: 3006.4

Python Version:
        Python: 3.10.13 (main, Oct  4 2023, 21:54:22) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.13.12
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: ubuntu 22.04.3 jammy
        locale: utf-8
       machine: x86_64
       release: 6.2.0-1009-aws
        system: Linux
       version: Ubuntu 22.04.3 jammy
```

</details>

**Comment by c42-adam** [comment]
Just wondering if we are going to see some movement on this.

```
$ sudo salt-call grains.get dynamic:instance-identity --out=json
[CRITICAL] Failed to load grains defined in grain file metadata.metadata in function <LoadedFunc name='metadata.metadata'>, error:
Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/__init__.py", line 1154, in grains
    ret = funcs[key](**kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 159, in __call__
    ret = self.loader.run(run_func, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1245, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1260, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/grains/metadata.py", line 87, in metadata
    return _search()
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/grains/metadata.py", line 64, in _search
    ret[line] = _search(prefix=os.path.join(prefix, line + "/"))
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/grains/metadata.py", line 53, in _search
    linedata["headers"].get("Content-Type", "text/plain")
KeyError: 'headers'
{
    "local": ""
}
```

<details>
<summary>salt-call --versions-report</summary>

```
Salt Version:
          Salt: 3006.5

Python Version:
        Python: 3.10.13 (main, Nov 15 2023, 04:34:27) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.14.2
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: ubuntu 22.04.2 jammy
        locale: utf-8
       machine: x86_64
       release: 6.2.0-1009-aws
        system: Linux
       version: Ubuntu 22.04.2 jammy
```

</details>

**Comment by mdschmitt** [comment]
So, perhaps @garethgreenaway can weigh in here.  Is it possible that the behavior in the most recent commit was bugged..?
https://github.com/saltstack/salt/commit/f9fa9381efb7fb8e37baba2aa4c36cf5348f143b

**Comment by houstonj1** [comment]
@s0undt3ch do you think changes to http.query are related here?

**Comment by s0undt3ch** [comment]
> @s0undt3ch do you think changes to http.query are related here?

Without digging more, your guess is as good as mine, probably better since you've done some investigation already.

**Comment by s0undt3ch** [comment]
I just tried with 3006.6, the VM has metadata enabled, and IMDSv2 is set to optional. It works as expected.

**Comment by s0undt3ch** [comment]
If however IMDSv2 is set to required, then nothing comes back, but also no traceback.

Please confirm that this is still an issue on your end with the latest release.

**Comment by s0undt3ch** [comment]
With 3007.0rc1 is works with both IMDSv2 set to optional and required.

**Comment by c42-adam** [comment]
This doesn't appear to be working for me with 3006.6. Testing with salt-call locally is still the same result as above. If I test from the salt master, it just returns the empty string.

I converted my systems to use a custom grain to pull this info instead. That works perfectly fine (aside from the separate grains sync issue). I insert it under a different name so it doesn't conflict. I also re-confirmed that I can query the metadata API with curl.

Let me know if there's any other data I can gather.

```
$ sudo salt-call grains.get dynamic:instance-identity --out=json
[CRITICAL] Failed to load grains defined in grain file metadata.metadata in function <LoadedFunc name='metadata.metadata'>, error:
Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/__init__.py", line 1154, in grains
    ret = funcs[key](**kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 159, in __call__
    ret = self.loader.run(run_func, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1245, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1260, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/grains/metadata.py", line 87, in metadata
    return _search()
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/grains/metadata.py", line 64, in _search
    ret[line] = _search(prefix=os.path.join(prefix, line + "/"))
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/grains/metadata.py", line 53, in _search
    linedata["headers"].get("Content-Type", "text/plain")
KeyError: 'headers'
{
    "local": ""
}
```

salt minion config (redacted):
```
master:
  - salt.[xx].com
master_type: failover
retry_dns: 0
backup_mode: minion
master_finger: 'xx:xx:xx'
state_output: changes
log_level: warning
metadata_server_grains: True
```

<details><summary>salt-call -V</summary>
<p>
Salt Version:
          Salt: 3006.6

Python Version:
        Python: 3.10.13 (main, Nov 15 2023, 04:34:27) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.3
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.14.2
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: ubuntu 22.04.2 jammy
        locale: utf-8
       machine: x86_64
       release: 6.2.0-1017-aws
        system: Linux
       version: Ubuntu 22.04.2 jammy
</p>
</details>

**Comment by houstonj1** [comment]
I was able to confirm the same as @s0undt3ch for each version 3006.3 ... 3006.6. The IMDS is required to be set to V1 with V2 optional until a 3007 release gets cut with IMDSv2 support. 

I was running into the same issue as @c42-adam previously, but can't reproduce it again.

**Comment by s0undt3ch** [comment]
> This doesn't appear to be working for me with 3006.6. Testing with salt-call locally is still the same result as above. If I test from the salt master, it just returns the empty string.
> 
> I converted my systems to use a custom grain to pull this info instead. That works perfectly fine (aside from the separate grains sync issue). I insert it under a different name so it doesn't conflict. I also re-confirmed that I can query the metadata API with curl.
> 
> Let me know if there's any other data I can gather.
> 
> ```
> $ sudo salt-call grains.get dynamic:instance-identity --out=json
> [CRITICAL] Failed to load grains defined in grain file metadata.metadata in function <LoadedFunc name='metadata.metadata'>, error:
> Traceback (most recent call last):
>   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/__init__.py", line 1154, in grains
>     ret = funcs[key](**kwargs)
>   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 159, in __call__
>     ret = self.loader.run(run_func, *args, **kwargs)
>   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1245, in run
>     return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
>   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1260, in _run_as
>     return _func_or_method(*args, **kwargs)
>   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/grains/metadata.py", line 87, in metadata
>     return _search()
>   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/grains/metadata.py", line 64, in _search
>     ret[line] = _search(prefix=os.path.join(prefix, line + "/"))
>   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/grains/metadata.py", line 53, in _search
>     linedata["headers"].get("Content-Type", "text/plain")
> KeyError: 'headers'
> {
>     "local": ""
> }
> ```
> 
> salt minion config (redacted):
> 
> ```
> master:
>   - salt.[xx].com
> master_type: failover
> retry_dns: 0
> backup_mode: minion
> master_finger: 'xx:xx:xx'
> state_output: changes
> log_level: warning
> metadata_server_grains: True
> ```
> 
> salt-call -V
> 
> Salt Version: Salt: 3006.6
> 
> Python Version: Python: 3.10.13 (main, Nov 15 2023, 04:34:27) [GCC 11.2.0]
> 
> Dependency Versions: cffi: 1.14.6 cherrypy: 18.6.1 dateutil: 2.8.1 docker-py: Not Installed gitdb: Not Installed gitpython: Not Installed Jinja2: 3.1.3 libgit2: Not Installed looseversion: 1.0.2 M2Crypto: Not Installed Mako: Not Installed msgpack: 1.0.2 msgpack-pure: Not Installed mysql-python: Not Installed packaging: 22.0 pycparser: 2.21 pycrypto: Not Installed pycryptodome: 3.19.1 pygit2: Not Installed python-gnupg: 0.4.8 PyYAML: 6.0.1 PyZMQ: 23.2.0 relenv: 0.14.2 smmap: Not Installed timelib: 0.2.4 Tornado: 4.5.3 ZMQ: 4.3.4
> 
> System Versions: dist: ubuntu 22.04.2 jammy locale: utf-8 machine: x86_64 release: 6.2.0-1017-aws system: Linux version: Ubuntu 22.04.2 jammy

How did you install this minion?

**Comment by c42-adam** [comment]
> How did you install this minion?

I used salt-bootstrap, I don't recall the exact command but it used onedir and it was probably installed to version 3004 or 3005, and then upgraded via apt. I also recently downgraded everything to 3004 to work around the grains sync issue, and then upgraded this minion to 3006.6. This was all using apt and the official package repos.

It is possible the minion had a pre-onedir version of salt (some other affected servers did), but those packages would have been removed and the upgrade would have still been via bootstrap and onedir.

I will try an apt purge of the salt packages and reinstall via bootstrap.

**Comment by c42-adam** [comment]
I used `apt purge salt-common salt-minion` and then went and manually removed /etc/apt/sources.list.d/salt.list, /var/run/salt /opt/Saltstack and /var/cache/salt. I left my /etc/salt folder alone since it was just minion config and pki. 
I reinstalled with `sudo ./bootstrap-salt.sh onedir 3006` using bootstrap-salt version 2024.01.04. It overwrote my minion config anyway. There was one warning about not being able to write a log file, but no critical errors in the bootstrap.

I ran a minimal state that updates the salt minion config to my defaults, added `metadata_server_grains: True` and restarted the minion. Results are the same.

I don't see any differences in the error or in the versions-report.

```
$ date ; sudo salt-call grains.get dynamic:instance-identity --out=json
Tue Feb  6 18:57:58 UTC 2024
[CRITICAL] Failed to load grains defined in grain file metadata.metadata in function <LoadedFunc name='metadata.metadata'>, error:
Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/__init__.py", line 1154, in grains
    ret = funcs[key](**kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 159, in __call__
    ret = self.loader.run(run_func, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1245, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1260, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/grains/metadata.py", line 87, in metadata
    return _search()
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/grains/metadata.py", line 64, in _search
    ret[line] = _search(prefix=os.path.join(prefix, line + "/"))
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/grains/metadata.py", line 53, in _search
    linedata["headers"].get("Content-Type", "text/plain")
KeyError: 'headers'
{
    "local": ""
}
```

<details><summary>Details</summary>
<p>

$ sudo salt-call --versions-report
Salt Version:
          Salt: 3006.6

Python Version:
        Python: 3.10.13 (main, Nov 15 2023, 04:34:27) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.3
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.14.2
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: ubuntu 22.04.2 jammy
        locale: utf-8
       machine: x86_64
       release: 6.2.0-1017-aws
        system: Linux
       version: Ubuntu 22.04.2 jammy

</p>
</details>

**Comment by s0undt3ch** [comment]
@c42-adam and @mdschmitt , these VM's, do they have IMDS set to v1 or v2?

**Comment by mdschmitt** [comment]
Same.  `curl http://169.254.169.254/latest/meta-data` returns just fine, (IMDSv2 Optional), grain still busted (on 3007 as well).  @s0undt3ch

**Comment by nicholasmhughes** [comment]
I have a 3007.0 master, one 3007.0 minion, and two 3006.7 minions. The 3007.0 minion **does not** return metadata grains to the master when invoked with the `salt` command like so:

```
[root@ip-10-224-36-138 ~]# salt "*0*" grains.get meta-data:instance-id
minion01:
    i-018778a840b76e848
minion02:
    i-0eacb0a92d7daebdc
nifi01:
```

Interestingly, the `salt-call` command is able to pull the metadata grains just fine locally on that same 3007.0 minion.

```
[root@ip-10-224-36-168 minion]# salt-call grains.get meta-data:instance-id
local:
    i-0d63bdf67424557b6
```

I saw these event loop errors shown in the minion logs:

```
2024-03-26 16:43:21,878 [salt.loader.lazy :1155][ERROR   ][9261] Exception raised when processing __virtual__ function for salt.loaded.int.grains.metadata. Module will not be loaded: Cannot run the event loop while another loop is running
2024-03-26 16:43:21,883 [salt.loader.lazy :1155][ERROR   ][9261] Exception raised when processing __virtual__ function for salt.loaded.int.grains.metadata_gce. Module will not be loaded: Cannot run the event loop while another loop is running
```

This lead me to believe that it was some problem with tornado, the default backend for the `http` utils module. If you change the minion configuration on the 3007.0 minion to include a different backend:

```
backend: requests
```

...then it works just fine and does not show the error messages any longer:

```
[root@ip-10-224-36-138 ~]# salt "*0*" grains.get meta-data:instance-id
minion01:
    i-018778a840b76e848
minion02:
    i-0eacb0a92d7daebdc
nifi01:
    i-0d63bdf67424557b6
```

@s0undt3ch, can you think of any problems which may cause this issue since we moved away from the vendored tornado implementation?

ref: https://github.com/saltstack/salt/compare/3006.x...3007.x#diff-16

**Comment by mdschmitt** [comment]
Any update here? I use these grains pretty heavily so I’m actually blocked on upgrading…

**Comment by c42-adam** [comment]
@mdschmitt I ended up abandoning the built-in metadata and implemented my own. I based it on this: https://github.com/bluprince13/aws-metadata-json/tree/master
It pulls in things _slightly_ differently, for instance numbers instead of numbers in strings, so it forced me to change my logic a little, but the structure was all the same.

**Comment by mdschmitt** [comment]
Do you happen to have a gist of your custom grain? Perhaps I could piggyback

**Comment by c42-adam** [comment]
@mdschmitt unfortunately because it was for work policy prevents me from sharing it. Sorry.

**Comment by mdschmitt** [comment]
No problem, it was worth asking. :)

**Comment by klippo** [comment]
We've been having issues with meta-data grains since 2020, reported in https://github.com/saltstack/salt/issues/57000. This issue is more or less the same.

The issue, at least for us, is **still** caused by https://github.com/saltstack/salt/blob/v3006.9/salt/grains/metadata.py#L67. 

A  workaround for this was mentioned here https://github.com/saltstack/salt/issues/59541#issuecomment-1891240224


user-data:
``` curl 169.254.169.254/latest/user-data
#cloud-config

manage_etc_hosts: false
preserve_hostname: false
prefer_fqdn_over_hostname: true
fqdn: klippo01.local
hostname: klippo01.local

apt:
  preserve_sources_list: true

package_update: true
package_upgrade: true

network:

  ethernets:
    alleths:
      match:
        name: en*
      dhcp4: true

timezone: "Europe/Stockholm"
salt_minion:
  conf:
    master:
      - localhost
    id: klippo01.local
    metadata_server_grains: true
    mine_functions:
      grains.item:
      - fqdn
      - fqdn_ip4
      - ipv4
      - roles
  grains:
    env: devtest

runcmd:
  - salt-call -l warning state.apply
  - DEBIAN_FRONTEND=noninteractive apt-get clean && rm -rf /var/lib/apt/lists/*

power_state:
  mode: reboot
```

Running modified metadata.py 
```
{'body': 'ami-id\nami-launch-index\nami-manifest-path\nblock-device-mapping/\nhostname\ninstance-action\ninstance-id\ninstance-type\nlocal-hostname\nlocal-ipv4\nplacement/\npublic-hostname\npublic-ipv4\npublic-keys/\nreservation-id\nsecurity-groups', 'headers': <salt.ext.tornado.httputil.HTTPHeaders object at 0x7b4a7eb02d10>}
http://169.254.169.254/latest/meta-data/
--
{'body': 'ami\nroot', 'headers': <salt.ext.tornado.httputil.HTTPHeaders object at 0x7b4a7eb038e0>}
http://169.254.169.254/latest/meta-data/block-device-mapping/
--
{'body': 'availability-zone', 'headers': <salt.ext.tornado.httputil.HTTPHeaders object at 0x7b4a7eb02a70>}
http://169.254.169.254/latest/meta-data/placement/
--
{'body': '0=itops', 'headers': <salt.ext.tornado.httputil.HTTPHeaders object at 0x7b4a7eb553c0>}
http://169.254.169.254/latest/meta-data/public-keys/
--
{'body': 'openssh-key', 'headers': <salt.ext.tornado.httputil.HTTPHeaders object at 0x7b4a7eb555a0>}
http://169.254.169.254/latest/meta-data/public-keys/0
--
{'body': '#cloud-config\n\nmanage_etc_hosts: false\npreserve_hostname: false\nprefer_fqdn_over_hostname: true\nfqdn: klippo01.local\nhostname: klippo01.local\n\napt:\n  preserve_sources_list: true\n\npackage_update: true\npackage_upgrade: true\n\nnetwork:\n\n  ethernets:\n    alleths:\n      match:\n        name: en*\n      dhcp4: true\n\ntimezone: "Europe/Stockholm"\nsalt_minion:\n  conf:\n    master:\n      - localhost\n    id: klippo01.local\n    metadata_server_grains: true\n    mine_functions:\n      grains.item:\n      - fqdn\n      - fqdn_ip4\n      - ipv4\n      - roles\n  grains:\n    env: devtest\n    roles:\n      - devtest-server\n\n\nruncmd:\n  - salt-call -l warning state.apply\n  - DEBIAN_FRONTEND=noninteractive apt-get clean && rm -rf /var/lib/apt/lists/*\n\npower_state:\n  mode: reboot\n', 'headers': <salt.ext.tornado.httputil.HTTPHeaders object at 0x7b4a7eb56350>}
http://169.254.169.254/latest/user-data/
--
{'status': 400, 'error': 'HTTP 400: Bad request', 'body': '<html><body><h1>400 Bad request</h1>\nYour browser sent an invalid request.\n</body></html>\n'}
http://169.254.169.254/latest/user-data/  - DEBIAN_FRONTEND
```


Either skip user-data completely, or skip parsing of `=` in user-data

**Comment by marcdeop** [comment]
We recently run into this issue in some of our instances.

We narrowed it down to the instance type on AWS booting on `bios-legacy` mode and this triggered the problem.

Changing to an instance capable of booting on `uefi` mode doesn't present the problem.

I know is not a _fix_ on itself but it allowed us to move on with our work :-)
