### ISSUE TITLE
exception Maintenance-626 caught on salt-master

### ISSUE THREAD

**Issue by berney11** [saltstack/salt#65230]
### Description of Issue
salt-master runtime error 

[ERROR   ] An un-handled exception from the multiprocessing process 'Maintenance-626' was caught:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/modules/cmdmod.py", line 680, in _run
    proc = salt.utils.timed_subprocess.TimedProc(cmd, **new_kwargs)
  File "/usr/lib/python3/dist-packages/salt/utils/timed_subprocess.py", line 55, in __init__
    self.process = subprocess.Popen(args, **kwargs)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1453, in _execute_child
    restore_signals, start_new_session, preexec_fn)
BlockingIOError: [Errno 11] Resource temporarily unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/process.py", line 895, in wrapped_run_func
    return run_func()
  File "/usr/lib/python3/dist-packages/salt/master.py", line 249, in run
    salt.daemons.masterapi.clean_old_jobs(self.opts)
  File "/usr/lib/python3/dist-packages/salt/daemons/masterapi.py", line 161, in clean_old_jobs
    mminion = salt.minion.MasterMinion(opts, states=False, rend=False,)
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 986, in __init__
    self.opts["grains"] = salt.loader.grains(opts)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 819, in grains
    ret = funcs[key]()
  File "/usr/lib/python3/dist-packages/salt/grains/core.py", line 2199, in os_data
    osarch = __salt__["cmd.run"]("dpkg --print-architecture").strip()
  File "/usr/lib/python3/dist-packages/salt/modules/cmdmod.py", line 895, in _run_quiet
    success_retcodes=success_retcodes,
  File "/usr/lib/python3/dist-packages/salt/modules/cmdmod.py", line 685, in _run
    raise CommandExecutionError(msg)

### Setup
root@salt-master-sodium-78bb7444bf-dqbnn:/# more /etc/salt/master
state_top: salt://top.sls
pillar_roots:
  base:
    - /etc/salt/pillar
fileserver_backend:
  - roots
file_roots:
  base:
    - /etc/salt/base/
auto_accept: true
extension_modules: /etc/salt/extension_modules
# we keep the cache of minion in a persistent storage so as to survive pod restart
cachedir: /kube/mnt/cache/salt/master
keep_jobs: 4
timeout: 30
worker_threads: 28
ext_pillar_first: true
ext_pillar:
  - proxy_portal_pillar: []
  - locale_dependent_pillar: []
  - role_dependent_pillar: []
  - independent_pillar: []
max_event_size: 5242880
runner_dirs:
  - /etc/salt/runners/
schedule:
  clean_keys:
    function: manage.down
    hours: 24
    kwargs:
      removekeys: True

### Steps to Reproduce Issue
the issue happens from time to time

### Versions Report
Salt Version:
          Salt: 3002.6

Dependency Versions:
          cffi: 1.14.5
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.7.3 (default, Jan 22 2021, 20:04:44)
  python-gnupg: 0.4.4
        PyYAML: 3.13
         PyZMQ: 17.1.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.1

System Versions:
          dist: debian 10 buster
        locale: UTF-8
       machine: x86_64
       release: 5.4.134-el7.lime.2.x86_64
        system: Linux
       version: Debian GNU/Linux 10 buster

**Comment by OrangeDog** [comment]
Looks like the system has run out of pids or filehandles.

It could be a leak in anything (not necessarily Salt) or having the limits set too low for your workload.

**Comment by berney11** [comment]
Thanks for the suggestion, seems like its the PID run out, 
quite some number of zombie process:
I will dig more from my side, thanks.

root       31138  0.0  0.0      0     0 ?        Z    15:29   0:00 [salt-master] <defunct>
root       31246  0.0  0.0      0     0 ?        Zs   15:35   0:00 [salt-master] <defunct>
root       31247  0.0  0.0      0     0 ?        Z    15:35   0:01 [salt-master] <defunct>
Debian-+   31316  0.0  0.0      0     0 ?        Zs   15:36   0:00 [exim4] <defunct>
root       31339  0.0  0.0      0     0 ?        Zs   15:37   0:00 [salt-master] <defunct>
root       31340  0.0  0.0      0     0 ?        Z    15:37   0:01 [salt-master] <defunct>
Debian-+   31499  0.0  0.0      0     0 ?        Zs   15:45   0:00 [exim4] <defunct>
Debian-+   31665  0.0  0.0      0     0 ?        Zs   15:54   0:00 [exim4] <defunct>

**Comment by anilsil** [comment]
This is reported on Salt v3002.6, to address this,  we need confirmation that this issue exists in the latest of 3006.x

**Comment by berney11** [comment]
> This is reported on Salt v3002.6, to address this, we need confirmation that this issue exists in the latest of 3006.x

Thanks for checking this, may I know if we do have an issue link tracking the similar reported issue?

Further looking into the issue, seems like when I run some runners on the salt-master, it will give some exception, and when I call the salt-api to run those runners, it will remain as zombie process:

Exception ignored in: <function LocalClient.__del__ at 0x7fc209941a60>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/client/__init__.py", line 1994, in __del__
  File "/usr/lib/python3/dist-packages/salt/client/__init__.py", line 2014, in destroy
  File "/usr/lib/python3/dist-packages/salt/utils/event.py", line 788, in destroy
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/ioloop.py", line 722, in close
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/platform/posix.py", line 71, in close
TypeError: 'NoneType' object is not callable

**Comment by dwoz** [comment]
Not reproducible on any supported branch (3006.x/3007.x/3008.x/master). The reported traceback is a kernel-level fork failure (`BlockingIOError: [Errno 11] Resource temporarily unavailable`) from `subprocess.Popen` — the system was out of PIDs/file handles, which the reporter confirmed in-thread (many zombie `salt-master` and `exim4` processes). That is an environment/OS resource-exhaustion condition, not a Salt defect: any process attempting `fork()` under those conditions would fail the same way. Salt 3002.6 (Python 3.7) is well past EOL. Closing as not-planned; please reopen against a supported release with a reproducer if the underlying fork failure ever recurs on a system that isn't out of PIDs.
