### ISSUE TITLE
[BUG] [salt.utils.process] [ERROR] File "msgpack/_packer.pyx" in msgpack._cmsgpack.Packer._pack TypeError: can not serialize 'PosixPath' object

### ISSUE THREAD

**Issue by cFabij** [saltstack/salt#65445]
**Description**
I use Uyuni 2023.09 (https://www.uyuni-project.org/) as Salt Master. Salt Minion is a Ubuntu 22.04 VM running in OpenStack.

When I execute `salt --log-file='/var/log/salt/issue' --log-file-level='all' ubuntu2-uyuni-test state.apply` on Salt Master (Uyuni server) the following error is produced in /var/log/salt/minion on client (Ubuntu) and state.apply fails:

> 2023-10-23 08:40:37,097 [salt.utils.process:998 ][ERROR   ][82571] An un-handled exception from the multiprocessing process 
> 'ProcessPayload(jid=20231023083659364933)' was caught:
> Traceback (most recent call last):
>   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/process.py", line 993, in wrapped_run_func
>     return run_func()
>   File "/opt/saltstack/salt/lib/python3.10/multiprocessing/process.py", line 108, in run
>     self._target(*self._args, **self._kwargs)
>   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 1844, in _target
>     run_func(minion_instance, opts, data)
>   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 1838, in run_func
>     return Minion._thread_return(minion_instance, opts, data)
>   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 2074, in _thread_return
>     minion_instance._return_pub(ret)
>   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 2276, in _return_pub
>     ret_val = self._send_req_sync(load, timeout=timeout)
>   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 1609, in _send_req_sync
>     return event.fire_event(
>   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/event.py", line 815, in fire_event
>     dump_data = salt.payload.dumps(data, use_bin_type=True)
>   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/payload.py", line 173, in dumps
>     return salt.utils.msgpack.packb(
>   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/msgpack.py", line 133, in packb
>     return msgpack.packb(o, **_sanitize_msgpack_kwargs(kwargs))
>   File "/opt/saltstack/salt/lib/python3.10/site-packages/msgpack/__init__.py", line 35, in packb
>     return Packer(**kwargs).pack(o)
>   File "msgpack/_packer.pyx", line 292, in msgpack._cmsgpack.Packer.pack
>   File "msgpack/_packer.pyx", line 298, in msgpack._cmsgpack.Packer.pack
>   File "msgpack/_packer.pyx", line 295, in msgpack._cmsgpack.Packer.pack
>   File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
>   File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
>   File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
>   [Previous line repeated 3 more times]
>   File "msgpack/_packer.pyx", line 289, in msgpack._cmsgpack.Packer._pack
> TypeError: can not serialize 'PosixPath' object

The corresponding log file on Salt master reads as follows (see attached):
[salt_master_log_file.txt](https://github.com/saltstack/salt/files/13068547/salt_master_log_file.txt)

The time discrepancy between the Salt Minion log and the Salt Master log is due to Ubuntu (Salt Minion) not being configured to the same time zone (Ubuntu is 2 hours behind).

`salt ubuntu2-uyuni-test test.ping` works every time and responds back "True".

**Setup**
- [ ] on-prem machine
- [x] VM (Virtualbox, KVM, etc. please specify):
**OpenStack uses KVM**

- [x] VM running on a cloud service, please be explicit and add details
**Both Salt Master and Salt Minion are running in OpenStack**

- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [x] onedir packaging
- [x] used bootstrap to install
**Salt Minion installed via `curl -L https://bootstrap.saltproject.io | sudo sh -s --`. Salt Master is installed through Uyuni.**

**Steps to Reproduce the behavior**
Every time I try to apply state to Ubuntu 22.04 through Uyuni Salt Master. I even tried a fresh Ubuntu 22.04 VM but got the same problem.

**Expected behavior**
Expected behavior is that Salt Master can apply state on minion (here: on Ubuntu 22.04).

**Versions Report**

1. Salt Master (Uyuni)
<details><summary>salt --versions-report</summary>
Salt Version:
          Salt: 3006.0

Python Version:
        Python: 3.6.15 (default, Sep 23 2021, 15:41:43) [GCC]

Dependency Versions:
          cffi: 1.13.2
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: 0.38.0
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 20.3
     pycparser: 2.17
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 17.1.2
        relenv: Not Installed
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.3

System Versions:
          dist: opensuse-leap 15.5
        locale: UTF-8
       machine: x86_64
       release: 5.14.21-150500.55.19-default
        system: Linux
       version: openSUSE Leap 15.5
</details>

2. Salt Minion (Ubuntu 22.04)
<details><summary>salt-minion -V</summary>

Salt Version:
          Salt: 3006.3

Python Version:
        Python: 3.10.13 (main, Sep  6 2023, 02:11:27) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.13.10
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: ubuntu 22.04.2 jammy
        locale: utf-8
       machine: x86_64
       release: 5.15.0-67-generic
        system: Linux
       version: Ubuntu 22.04.2 jammy
</details>

**Additional context**
Interesting to me is:

1. When I run `salt-call state.apply` on the same Ubuntu 22.04 client, everything works (only "success").
2. Applying state though Salt Master works as expected on a CentOS 7.9 VM, also running in OpenStack (even in the same project). Installed also through bootstrap script.
<details><summary>CentOS salt-minion -V</summary>
Salt Version:
          Salt: 3006.3

Python Version:
        Python: 3.10.13 (main, Sep  6 2023, 02:11:27) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.13.10
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: centos 7.9.2009 Core
        locale: utf-8
       machine: x86_64
       release: 3.10.0-1160.80.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7.9.2009 Core
</details>

**Comment by cFabij** [comment]
When registering a new client through Salt, Uyuni automatically applies a state to get different information.

The following is a different failure log than above from the client (still Ubuntu 22.04) - though still failing due to "_can not serialize 'PosixPath' object_":
<details><summary>/var/log/salt/minion</summary>
2023-10-24 09:39:21,782 [salt.minion      :2028][WARNING ][13606] Passed invalid arguments to state.apply: can not serialize 'PosixPath' object

    .. versionadded:: 2015.5.0

    This function will call :mod:`state.highstate
    <salt.modules.state.highstate>` or :mod:`state.sls
    <salt.modules.state.sls>` based on the arguments passed to this function.
    It exists as a more intuitive way of applying states.

    .. rubric:: APPLYING ALL STATES CONFIGURED IN TOP.SLS (A.K.A. :ref:`HIGHSTATE <running-highstate>`)

    To apply all configured states, simply run ``state.apply``:

    .. code-block:: bash

        salt '*' state.apply

    The following additional arguments are also accepted when applying all
    states configured in top.sls:

    test
        Run states in test-only (dry-run) mode

    mock
        The mock option allows for the state run to execute without actually
        calling any states. This then returns a mocked return which will show
        the requisite ordering as well as fully validate the state run.

        .. versionadded:: 2015.8.4

    pillar
        Custom Pillar values, passed as a dictionary of key-value pairs

        .. code-block:: bash

            salt '*' state.apply stuff pillar='{"foo": "bar"}'

        .. note::
            Values passed this way will override Pillar values set via
            ``pillar_roots`` or an external Pillar source.

    exclude
        Exclude specific states from execution. Accepts a list of sls names, a
        comma-separated string of sls names, or a list of dictionaries
        containing ``sls`` or ``id`` keys. Glob-patterns may be used to match
        multiple states.

        .. code-block:: bash

            salt '*' state.apply exclude=bar,baz
            salt '*' state.apply exclude=foo*
            salt '*' state.apply exclude="[{'id': 'id_to_exclude'}, {'sls': 'sls_to_exclude'}]"

    queue : False
        Instead of failing immediately when another state run is in progress,
        a value of ``True`` will queue the new state run to begin running once
        the other has finished.

        This option starts a new thread for each queued state run, so use this
        option sparingly.

        .. versionchanged:: 3006.0
            This parameter can also be set via the ``state_queue`` configuration
            option. Additionally, it can now be set to an integer representing
            the maximum queue size which can be attained before the state runs
            will fail to be queued. This can prevent runaway conditions where
            new threads are started until system performance is hampered.

    localconfig
        Optionally, instead of using the minion config, load minion opts from
        the file specified by this argument, and then merge them with the
        options from the minion config. This functionality allows for specific
        states to be run with their own custom minion configuration, including
        different pillars, file_roots, etc.

        .. code-block:: bash

            salt '*' state.apply localconfig=/path/to/minion.yml

    state_events
        The state_events option sends progress events as each function in
        a state run completes execution.

        .. versionadded:: 3006.0


    .. rubric:: APPLYING INDIVIDUAL SLS FILES (A.K.A. :py:func:`STATE.SLS <salt.modules.state.sls>`)

    To apply individual SLS files, pass them as a comma-separated list:

    .. code-block:: bash

        # Run the states configured in salt://stuff.sls (or salt://stuff/init.sls)
        salt '*' state.apply stuff

        # Run the states configured in salt://stuff.sls (or salt://stuff/init.sls)
        # and salt://pkgs.sls (or salt://pkgs/init.sls).
        salt '*' state.apply stuff,pkgs

        # Run the states configured in a more deeply nested directory such as salt://my/organized/stuff.sls (or salt://my/organized/stuff/init.sls)
        salt '*' state.apply my.organized.stuff

    The following additional arguments are also accepted when applying
    individual SLS files:

    test
        Run states in test-only (dry-run) mode

    mock
        The mock option allows for the state run to execute without actually
        calling any states. This then returns a mocked return which will show
        the requisite ordering as well as fully validate the state run.

        .. versionadded:: 2015.8.4

    pillar
        Custom Pillar values, passed as a dictionary of key-value pairs

        .. code-block:: bash

            salt '*' state.apply stuff pillar='{"foo": "bar"}'

        .. note::
            Values passed this way will override Pillar values set via
            ``pillar_roots`` or an external Pillar source.

    queue : False
        Instead of failing immediately when another state run is in progress,
        a value of ``True`` will queue the new state run to begin running once
        the other has finished.

        This option starts a new thread for each queued state run, so use this
        option sparingly.

        .. versionchanged:: 3006.0
            This parameter can also be set via the ``state_queue`` configuration
            option. Additionally, it can now be set to an integer representing
            the maximum queue size which can be attained before the state runs
            will fail to be queued. This can prevent runaway conditions where
            new threads are started until system performance is hampered.

    concurrent : False
        Execute state runs concurrently instead of serially

        .. warning::

            This flag is potentially dangerous. It is designed for use when
            multiple state runs can safely be run at the same time. Do *not*
            use this flag for performance optimization.

    saltenv
        Specify a salt fileserver environment to be used when applying states

        .. versionchanged:: 0.17.0
            Argument name changed from ``env`` to ``saltenv``

        .. versionchanged:: 2014.7.0
            If no saltenv is specified, the minion config will be checked for an
            ``environment`` parameter and if found, it will be used. If none is
            found, ``base`` will be used. In prior releases, the minion config
            was not checked and ``base`` would always be assumed when the
            saltenv was not explicitly set.

    pillarenv
        Specify a Pillar environment to be used when applying states. This
        can also be set in the minion config file using the
        :conf_minion:`pillarenv` option. When neither the
        :conf_minion:`pillarenv` minion config option nor this CLI argument is
        used, all Pillar environments will be merged together.

    localconfig
        Optionally, instead of using the minion config, load minion opts from
        the file specified by this argument, and then merge them with the
        options from the minion config. This functionality allows for specific
        states to be run with their own custom minion configuration, including
        different pillars, file_roots, etc.

        .. code-block:: bash

            salt '*' state.apply stuff localconfig=/path/to/minion.yml

    sync_mods
        If specified, the desired custom module types will be synced prior to
        running the SLS files:

        .. code-block:: bash

            salt '*' state.apply stuff sync_mods=states,modules
            salt '*' state.apply stuff sync_mods=all

        .. note::
            This option is ignored when no SLS files are specified, as a
            :ref:`highstate <running-highstate>` automatically syncs all custom
            module types.

        .. versionadded:: 2017.7.8,2018.3.3,2019.2.0

    state_events
        The state_events option sends progress events as each function in
        a state run completes execution.

        .. versionadded:: 3006.0

2023-10-24 09:39:28,108 [salt.state       :323 ][ERROR   ][29585] Module function pkg.info_installed threw an exception. Exception: The following keyword arguments are not valid: attr=status,arch,epoch,version,release,install_date_time_t, errors=report
</details>

Maybe the last line

> **2023-10-24 09:39:28,108 [salt.state :323 ][ERROR ][29585] Module function pkg.info_installed threw an exception. Exception: The following keyword arguments are not valid: attr=status,arch,epoch,version,release,install_date_time_t, errors=report**

can help narrow it down?

**Comment by cFabij** [comment]
Issue can be closed.

The root of the problem was caused by Uyuni, which apparently doesn't support manually bootstrapping salt minions (at least when debian-based distros are concerned...) but needs its own WebUI-bootstrapping. This then installs/configures a special Salt bundle.

**Comment by cFabij** [comment]
closed - see above.
