### ISSUE TITLE
[BUG] pip.installed show stacktrace when user does not exists on testing

### ISSUE THREAD

**Issue by scornelissen85** [saltstack/salt#65458]
**Description**
When I'm creating a state with `pip.installed`, with an user given and will apply this state with `test=True` then there will be a stacktrace because it's trying to figure out which packages are installed under that user. However the user does not exists, so it will fail to check.

**Setup**

Install Salt 3006.3 on local linux machine. Install pip with your preferred package manager.

**Steps to Reproduce the behavior**
Create this state:

pip.sls:
```
Flask:
  pip.installed:
    - user: fred
```

The user `fred` does not exists. I'm applying the state:

```
# salt-call --local state.apply pip test=True
[ERROR   ] Pre-caching of PIP packages during states.pip.installed failed by exception from pip.list: User 'fred' is not available
Traceback (most recent call last):
  File "/salt/salt/modules/cmdmod.py", line 485, in _run
    pwd.getpwnam(runas)
KeyError: "getpwnam(): name not found: 'fred'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/salt/salt/states/pip_state.py", line 852, in installed
    pip_list = __salt__["pip.list"](
  File "/salt/salt/loader/lazy.py", line 159, in __call__
    ret = self.loader.run(run_func, *args, **kwargs)
  File "/salt/salt/loader/lazy.py", line 1245, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/salt/salt/loader/lazy.py", line 1260, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/salt/salt/modules/pip.py", line 1353, in list_
    result = __salt__["cmd.run_all"](cmd, **cmd_kwargs)
  File "/salt/salt/loader/lazy.py", line 159, in __call__
    ret = self.loader.run(run_func, *args, **kwargs)
  File "/salt/salt/loader/lazy.py", line 1245, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/salt/salt/loader/lazy.py", line 1260, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/salt/salt/modules/cmdmod.py", line 2329, in run_all
    ret = _run(
  File "/salt/salt/modules/cmdmod.py", line 487, in _run
    raise CommandExecutionError("User '{}' is not available".format(runas))
salt.exceptions.CommandExecutionError: User 'fred' is not available
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/salt/salt/modules/cmdmod.py", line 485, in _run
    pwd.getpwnam(runas)
KeyError: "getpwnam(): name not found: 'fred'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/salt/salt/state.py", line 2381, in call
    ret = self.states[cdata["full"]](
  File "/salt/salt/loader/lazy.py", line 159, in __call__
    ret = self.loader.run(run_func, *args, **kwargs)
  File "/salt/salt/loader/lazy.py", line 1245, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/salt/salt/loader/lazy.py", line 1260, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/salt/salt/loader/lazy.py", line 1293, in wrapper
    return f(*args, **kwargs)
  File "/salt/salt/states/pip_state.py", line 865, in installed
    out = _check_if_installed(
  File "/salt/salt/states/pip_state.py", line 276, in _check_if_installed
    or __salt__["pip.list"](
  File "/salt/salt/loader/lazy.py", line 159, in __call__
    ret = self.loader.run(run_func, *args, **kwargs)
  File "/salt/salt/loader/lazy.py", line 1245, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/salt/salt/loader/lazy.py", line 1260, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/salt/salt/modules/pip.py", line 1353, in list_
    result = __salt__["cmd.run_all"](cmd, **cmd_kwargs)
  File "/salt/salt/loader/lazy.py", line 159, in __call__
    ret = self.loader.run(run_func, *args, **kwargs)
  File "/salt/salt/loader/lazy.py", line 1245, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/salt/salt/loader/lazy.py", line 1260, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/salt/salt/modules/cmdmod.py", line 2329, in run_all
    ret = _run(
  File "/salt/salt/modules/cmdmod.py", line 487, in _run
    raise CommandExecutionError("User '{}' is not available".format(runas))
salt.exceptions.CommandExecutionError: User 'fred' is not available

local:
----------
          ID: Flask
    Function: pip.installed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/salt/salt/modules/cmdmod.py", line 485, in _run
                  pwd.getpwnam(runas)
              KeyError: "getpwnam(): name not found: 'fred'"

              During handling of the above exception, another exception occurred:

              Traceback (most recent call last):
                File "/salt/salt/state.py", line 2381, in call
                  ret = self.states[cdata["full"]](
                File "/salt/salt/loader/lazy.py", line 159, in __call__
                  ret = self.loader.run(run_func, *args, **kwargs)
                File "/salt/salt/loader/lazy.py", line 1245, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/salt/salt/loader/lazy.py", line 1260, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/salt/salt/loader/lazy.py", line 1293, in wrapper
                  return f(*args, **kwargs)
                File "/salt/salt/states/pip_state.py", line 865, in installed
                  out = _check_if_installed(
                File "/salt/salt/states/pip_state.py", line 276, in _check_if_installed
                  or __salt__["pip.list"](
                File "/salt/salt/loader/lazy.py", line 159, in __call__
                  ret = self.loader.run(run_func, *args, **kwargs)
                File "/salt/salt/loader/lazy.py", line 1245, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/salt/salt/loader/lazy.py", line 1260, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/salt/salt/modules/pip.py", line 1353, in list_
                  result = __salt__["cmd.run_all"](cmd, **cmd_kwargs)
                File "/salt/salt/loader/lazy.py", line 159, in __call__
                  ret = self.loader.run(run_func, *args, **kwargs)
                File "/salt/salt/loader/lazy.py", line 1245, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/salt/salt/loader/lazy.py", line 1260, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/salt/salt/modules/cmdmod.py", line 2329, in run_all
                  ret = _run(
                File "/salt/salt/modules/cmdmod.py", line 487, in _run
                  raise CommandExecutionError("User '{}' is not available".format(runas))
              salt.exceptions.CommandExecutionError: User 'fred' is not available
     Started: 12:08:06.766475
    Duration: 182.321 ms
     Changes:

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time: 182.321 ms
```
**Expected behavior**

When applying the state and test=True, something like this should be shown:

```
local:
----------
          ID: Flask
    Function: pip.installed
      Result: None
     Comment: User fred does not exist
     Started: 12:00:07.722631
    Duration: 216.618 ms
     Changes:
              ----------
              Flask:
                  ----------
                  new:
                      installed
                  old:

Summary for local
------------
Succeeded: 1 (unchanged=1, changed=1)
Failed:    0
------------
Total states run:     1
Total run time: 216.618 ms
```

**Versions Report**
<details><summary>salt --versions-report</summary>

```yaml
Salt Version:
          Salt: 3007.0

Python Version:
        Python: 3.9.16 (main, Jun 30 2023, 08:01:58)

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.3.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.7
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 23.2
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.19.0
        pygit2: Not Installed
  python-gnupg: Not Installed
        PyYAML: 6.0.1
         PyZMQ: 25.1.1
        relenv: Not Installed
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: almalinux 8.8 Sapphire Caracal
        locale: utf-8
       machine: x86_64
       release: 5.15.90.1-microsoft-standard-WSL2
        system: Linux
       version: AlmaLinux 8.8 Sapphire Caracal
```
</details>

**Additional context**
I have installed Salt from the github repository with pip, checked out on tag v3006.3.

**Comment by scornelissen85** [comment]
I'm not sure if the changes should be shown. Maybe, the result should even be False, because the user isn't found and it cannot check if the package should be installed.
