### ISSUE TITLE
Http error on windows11 minion

### ISSUE THREAD

**Issue by madurani** [saltstack/salt#65456]
**Description**
Attempt to install application on windows 11 is interrupted with error:

```
[root@tmv2007 win]# salt tml1115.minion pkg.install vlc
tml1115.minion:
    The minion function caused an exception: Traceback (most recent call last):
      File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\utils\http.py", line 639, in query
        result = download_client.fetch(url_full, **req_kwargs)
      File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\ext\tornado\httpclient.py", line 102, in fetch
        response = self._io_loop.run_sync(functools.partial(
      File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\ext\tornado\ioloop.py", line 459, in run_sync
        return future_cell[0].result()
      File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\ext\tornado\concurrent.py", line 249, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
      File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\ext\tornado\stack_context.py", line 317, in wrapped
        ret = fn(*args, **kwargs)
      File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\ext\tornado\simple_httpclient.py", line 308, in _on_timeout
        raise HTTPError(599, error_message)
    salt.ext.tornado.httpclient.HTTPError: HTTP 599: Timeout while connecting
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\minion.py", line 1943, in _thread_return
        return_data = minion_instance._execute_job_function(
      File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\minion.py", line 1902, in _execute_job_function
        return_data = self.executors[fname](opts, data, func, args, kwargs)
      File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\loader\lazy.py", line 159, in __call__
        ret = self.loader.run(run_func, *args, **kwargs)
      File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\loader\lazy.py", line 1245, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\loader\lazy.py", line 1260, in _run_as
        return _func_or_method(*args, **kwargs)
      File "C:\Program Files\Salt Project\Salt\Lib\site-packages\salt\executors\direct_call.py", line 10, in execute
        return func(*args, **kwargs)
      File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\loader\lazy.py", line 159, in __call__
        ret = self.loader.run(run_func, *args, **kwargs)
      File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\loader\lazy.py", line 1245, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\loader\lazy.py", line 1260, in _run_as
        return _func_or_method(*args, **kwargs)
      File "C:\Program Files\Salt Project\Salt\Lib\site-packages\salt\modules\win_pkg.py", line 1708, in install
        cached_pkg = __salt__["cp.cache_file"](
      File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\loader\lazy.py", line 159, in __call__
        ret = self.loader.run(run_func, *args, **kwargs)
      File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\loader\lazy.py", line 1245, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\loader\lazy.py", line 1260, in _run_as
        return _func_or_method(*args, **kwargs)
      File "C:\Program Files\Salt Project\Salt\Lib\site-packages\salt\modules\cp.py", line 546, in cache_file
        result = client.cache_file(
      File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\fileclient.py", line 187, in cache_file
        return self.get_url(
      File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\fileclient.py", line 787, in get_url
        query = salt.utils.http.query(
      File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\utils\http.py", line 644, in query
        exc.response.body,
    AttributeError: 'NoneType' object has no attribute 'body'
ERROR: Minions returned with non-zero exit code

```

```
[root@tmv2007 ~]# salt-master --versions-report
Salt Version:
          Salt: 3006.3
 
Python Version:
        Python: 3.10.13 (main, Sep  6 2023, 02:11:27) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.10
     gitpython: 3.1.32
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.13.10
         smmap: 5.0.0
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: oracle 8.8 n/a
        locale: utf-8
       machine: x86_64
       release: 4.18.0-477.13.1.el8_8.x86_64
        system: Linux
       version: Oracle Linux Server 8.8 n/a

```

**Comment by OrangeDog** [comment]
Is there a proxy or firewall between that minion and the Internet?

The URL it's trying to fetch would be `https://get.videolan.org/vlc/3.0.18/win64/vlc-3.0.18-win64.exe` but you should be able to confirm with the debug log.

**Comment by madurani** [comment]
no there isn't any FW or proxy

**Comment by OrangeDog** [comment]
Did you confirm with the debug log?
What does `salt-call cp.cache_file https://get.videolan.org/vlc/3.0.18/win64/vlc-3.0.18-win64.exe` do?

**Comment by madurani** [comment]
```
C:\Users\Administrator>salt-call cp.cache_file https://get.videolan.org/vlc/3.0.18/win64/vlc-3.0.18-win64.exe
C:\Program Files\Salt Project\Salt\lib\site-packages\salt\ext\tornado\netutil.py:493: DeprecationWarning: ssl.PROTOCOL_TLS is deprecated
  context = ssl.SSLContext(
[ERROR   ] An un-handled exception was caught by Salt's global exception handler:
AttributeError: 'NoneType' object has no attribute 'body'
Traceback (most recent call last):
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\utils\http.py", line 639, in query
    result = download_client.fetch(url_full, **req_kwargs)
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\ext\tornado\httpclient.py", line 102, in fetch
    response = self._io_loop.run_sync(functools.partial(
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\ext\tornado\ioloop.py", line 459, in run_sync
    return future_cell[0].result()
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\ext\tornado\concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\ext\tornado\stack_context.py", line 317, in wrapped
    ret = fn(*args, **kwargs)
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\ext\tornado\simple_httpclient.py", line 308, in _on_timeout
    raise HTTPError(599, error_message)
salt.ext.tornado.httpclient.HTTPError: HTTP 599: Timeout while connecting

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Salt Project\Salt\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Salt Project\Salt\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Salt Project\Salt\salt-call.exe\__main__.py", line 7, in <module>
    sys.exit(salt_call())
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\scripts.py", line 443, in salt_call
    client.run()
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\cli\call.py", line 50, in run
    caller.run()
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\cli\caller.py", line 95, in run
    ret = self.call()
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\cli\caller.py", line 202, in call
    ret["return"] = self.minion.executors[fname](
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\loader\lazy.py", line 159, in __call__
    ret = self.loader.run(run_func, *args, **kwargs)
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\loader\lazy.py", line 1245, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\loader\lazy.py", line 1260, in _run_as
    return _func_or_method(*args, **kwargs)
  File "C:\Program Files\Salt Project\Salt\Lib\site-packages\salt\executors\direct_call.py", line 10, in execute
    return func(*args, **kwargs)
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\loader\lazy.py", line 159, in __call__
    ret = self.loader.run(run_func, *args, **kwargs)
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\loader\lazy.py", line 1245, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\loader\lazy.py", line 1260, in _run_as
    return _func_or_method(*args, **kwargs)
  File "C:\Program Files\Salt Project\Salt\Lib\site-packages\salt\modules\cp.py", line 546, in cache_file
    result = client.cache_file(
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\fileclient.py", line 187, in cache_file
    return self.get_url(
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\fileclient.py", line 787, in get_url
    query = salt.utils.http.query(
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\utils\http.py", line 644, in query
    exc.response.body,
AttributeError: 'NoneType' object has no attribute 'body'
Traceback (most recent call last):
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\utils\http.py", line 639, in query
    result = download_client.fetch(url_full, **req_kwargs)
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\ext\tornado\httpclient.py", line 102, in fetch
    response = self._io_loop.run_sync(functools.partial(
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\ext\tornado\ioloop.py", line 459, in run_sync
    return future_cell[0].result()
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\ext\tornado\concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\ext\tornado\stack_context.py", line 317, in wrapped
    ret = fn(*args, **kwargs)
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\ext\tornado\simple_httpclient.py", line 308, in _on_timeout
    raise HTTPError(599, error_message)
salt.ext.tornado.httpclient.HTTPError: HTTP 599: Timeout while connecting

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Salt Project\Salt\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Salt Project\Salt\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Salt Project\Salt\salt-call.exe\__main__.py", line 7, in <module>
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\scripts.py", line 443, in salt_call
    client.run()
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\cli\call.py", line 50, in run
    caller.run()
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\cli\caller.py", line 95, in run
    ret = self.call()
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\cli\caller.py", line 202, in call
    ret["return"] = self.minion.executors[fname](
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\loader\lazy.py", line 159, in __call__
    ret = self.loader.run(run_func, *args, **kwargs)
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\loader\lazy.py", line 1245, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\loader\lazy.py", line 1260, in _run_as
    return _func_or_method(*args, **kwargs)
  File "C:\Program Files\Salt Project\Salt\Lib\site-packages\salt\executors\direct_call.py", line 10, in execute
    return func(*args, **kwargs)
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\loader\lazy.py", line 159, in __call__
    ret = self.loader.run(run_func, *args, **kwargs)
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\loader\lazy.py", line 1245, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\loader\lazy.py", line 1260, in _run_as
    return _func_or_method(*args, **kwargs)
  File "C:\Program Files\Salt Project\Salt\Lib\site-packages\salt\modules\cp.py", line 546, in cache_file
    result = client.cache_file(
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\fileclient.py", line 187, in cache_file
    return self.get_url(
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\fileclient.py", line 787, in get_url
    query = salt.utils.http.query(
  File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\utils\http.py", line 644, in query
    exc.response.body,
AttributeError: 'NoneType' object has no attribute 'body'

C:\Users\Administrator>
```

**Comment by OrangeDog** [comment]
What does `Invoke-WebRequest -Uri https://get.videolan.org/vlc/3.0.18/win64/vlc-3.0.18-win64.exe -OutFile temp` do in PowerShell?

**Comment by madurani** [comment]
[temp.txt](https://github.com/saltstack/salt/files/13164632/temp.txt)

**Comment by OrangeDog** [comment]
What about if you add `-NoProxy`?

**Comment by madurani** [comment]
```
PS C:\Users\Administrator> Invoke-WebRequest -Uri https://get.videolan.org/vlc/3.0.18/win64/vlc-3.0.18-win64.exe -OutFile temp1.txt -NoProxy
Invoke-WebRequest : A parameter cannot be found that matches parameter name 'NoProxy'.
At line:1 char:106
+ ... org/vlc/3.0.18/win64/vlc-3.0.18-win64.exe -OutFile temp1.txt -NoProxy
+                                                                  ~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-WebRequest], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```
