### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by gregorg** [saltstack/salt#65489]
**Description**

In module file.append, FileNotFoundError uncatched exception.

**Setup**

Salt 3006.4 on Linux Debian Bullseye. Python 3.10.

**Steps to Reproduce the behavior**

A reactor that append log to a file :
```
  local.file.append:
    - tgt: {{ data['id'] }}
    - args:
      - path: "/tmp/reactor.log"
      - text: "Test {{ data['id'] }} : {{data['1m']}} / {{data['5m']}} / {{data['15m']}}"
{% endif %}
```

Exception in minion log file : 
```
2023-10-30 16:11:30,709 [salt.minion      :2034][WARNING ][3011954] The minion function caused an exception
Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 1943, in _thread_return
    return_data = minion_instance._execute_job_function(
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 1902, in _execute_job_function
    return_data = self.executors[fname](opts, data, func, args, kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 159, in __call__
    ret = self.loader.run(run_func, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1245, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1260, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/executors/direct_call.py", line 10, in execute
    return func(*args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 159, in __call__
    ret = self.loader.run(run_func, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1245, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1260, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/modules/file.py", line 3388, in append
    with salt.utils.files.fopen(path, "rb+") as ofile:
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/files.py", line 393, in fopen
    f_handle = open(*args, **kwargs)  # pylint: disable=resource-leakage
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/reactor.log'
```

**Expected behavior**

Create the file if it doesn't exists.

**Versions Report**

```
Salt Version:
          Salt: 3006.3

Python Version:
        Python: 3.10.13 (main, Sep  6 2023, 02:11:27) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: 1.3.0
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: 1.7.0
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.13.10
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: debian 11 bullseye
        locale: utf-8
       machine: x86_64
       release: 5.10.0-25-amd64
        system: Linux
       version: Debian GNU/Linux 11 bullseye
```

**Comment by OrangeDog** [comment]
Please edit the title to e.g. `[BUG] FileNotFoundError in file.append`

**Comment by gregorg** [comment]
This behavior occured only via the reactor, on `local.file.append`. Not in a state.
