### ISSUE TITLE
[BUG] m2crypto 0.40.x release breaks x509 module

### ISSUE THREAD

**Issue by kobus-v-schoor** [saltstack/salt#65499]
**Description**
m2crypto made a [new release on 2023-10-24](https://gitlab.com/m2crypto/m2crypto/-/tags/0.40.0) with the following change:

```
BREAKING CHANGES:
   - complicated and error-prone __init__py has been
     cleaned and `import M2Crypto` doesn’t include everything
     anymore. Imports should specified as for example with `from
     M2Crypto import foo`.
```

This breaks salt states making use of the x509 module with errors such as these:

```
          ID: ensure  signing request has been generated
    Function: x509.csr_managed
        Name: /etc/ssl/csr/cert.csr
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "salt/state.py", line 2276, in call
                  ret = self.states[cdata["full"]](
                File "salt/loader/lazy.py", line 149, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "salt/loader/lazy.py", line 1228, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "salt/loader/lazy.py", line 1243, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "salt/loader/lazy.py", line 1276, in wrapper
                  return f(*args, **kwargs)
                File "/opt/saltstack/salt/run/salt/states/x509.py", line 375, in csr_managed
                  file_args["contents"] = __salt__["x509.create_csr"](text=True, **kwargs)
                File "salt/loader/lazy.py", line 149, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "salt/loader/lazy.py", line 1228, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "salt/loader/lazy.py", line 1243, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/opt/saltstack/salt/run/salt/modules/x509.py", line 1727, in create_csr
                  csr = M2Crypto.X509.Request()
              AttributeError: module 'M2Crypto' has no attribute 'X509'
     Started: 12:28:23.095849
    Duration: 13.644 ms
     Changes:
```

Pinning the `m2crypto` pip package using `sudo salt-pip install "m2crypto<0.40.0"` resolves the issue

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [x] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

**Expected behavior**

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3005.1

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: 5.0.3
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: 0.40.1
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.9.16 (main, Jan  6 2023, 22:50:07)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: ubuntu 22.04 jammy
        locale: utf-8
       machine: x86_64
       release: 5.15.0-87-generic
        system: Linux
       version: Ubuntu 22.04 jammy

```
</details>

**Additional context**

**Comment by OrangeDog** [comment]
Duplicate of #65474
