### ISSUE TITLE
[BUG] Timeout while running config.items

### ISSUE THREAD

**Issue by KBrand101** [saltstack/salt#65504]
**Description**
Not sure if this is really a bug but here it goes anyway:
I am trying to hook into salts config. Therefore I wanted to see what the current config is. Unfortunately I run into a timeout while doing so on the master. The minion has error messages in its log file.

**Setup**

- [x] on-prem machine
- [x] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [x] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [x] onedir packaging
- [ ] used bootstrap to install

- 3 minions (1x Deb 10, 1x Deb 11, 1x Deb 12)  + 1 master (also minion Deb 12)
- all 4 are VMs on a on-prem Proxmox hypervisor

**Steps to Reproduce the behavior**
1. Install master and minion packages on clean Debian systems
2. Accept Minions on Master
3. Try to get config by running
   ```
   salt --timeout=30 --verbose ausalttestclient10 config.items
   ```
5. Master reports following error for all 3 test clients (apart from job id and hostname):
   ```
   Executing job with jid 20231102141901454271
   -------------------------------------------

   ausalttestclient10:
       Minion did not return. [No response]
       The minions may not have all finished running and any remaining minions will return upon completion. To look up the return data for this job later, run the following command:
    
       salt-run jobs.lookup_jid 20231102141901454271
   ERROR: Minions returned with non-zero exit code
   ```
6. The log on the minion ```/var/log/salt/minion``` also shows the same error for all 3 (apart from job id and hostname):
   ```
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]: [ERROR   ] An un-handled exception from the multiprocessing process 'ProcessPayload(jid=20231102141901454271)' was caught:
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]: Traceback (most recent call last):
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/process.py", line 993, in wrapped_run_func
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:     return run_func()
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:   File "/opt/saltstack/salt/lib/python3.10/multiprocessing/process.py", line 108, in run
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:     self._target(*self._args, **self._kwargs)
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 1844, in _target
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:     run_func(minion_instance, opts, data)
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 1838, in run_func
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:     return Minion._thread_return(minion_instance, opts, data)
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 2074, in _thread_return
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:     minion_instance._return_pub(ret)
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 2276, in _return_pub
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:     ret_val = self._send_req_sync(load, timeout=timeout)
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 1609, in _send_req_sync
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:     return event.fire_event(
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/event.py", line 815, in fire_event
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:     dump_data = salt.payload.dumps(data, use_bin_type=True)
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/payload.py", line 173, in dumps
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:     return salt.utils.msgpack.packb(
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/msgpack.py", line 133, in packb
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:     return msgpack.packb(o, **_sanitize_msgpack_kwargs(kwargs))
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/msgpack/__init__.py", line 35, in packb
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:     return Packer(**kwargs).pack(o)
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:   File "msgpack/_packer.pyx", line 292, in msgpack._cmsgpack.Packer.pack
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:   File "msgpack/_packer.pyx", line 298, in msgpack._cmsgpack.Packer.pack
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:   File "msgpack/_packer.pyx", line 295, in msgpack._cmsgpack.Packer.pack
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:   File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:   File "msgpack/_packer.pyx", line 285, in msgpack._cmsgpack.Packer._pack
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/payload.py", line 168, in ext_type_encoder
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:     return dict(obj)
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:   File "/opt/saltstack/salt/lib/python3.10/_collections_abc.py", line 886, in __iter__
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:     yield from self._mapping
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/context.py", line 97, in __iter__
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:     return self.value().__iter__()
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]: AttributeError: 'NoneType' object has no attribute '__iter__'
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]: Process ProcessPayload(jid=20231102141901454271):
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]: Traceback (most recent call last):
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:   File "/opt/saltstack/salt/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:     self.run()
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/process.py", line 993, in wrapped_run_func
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:     return run_func()
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:   File "/opt/saltstack/salt/lib/python3.10/multiprocessing/process.py", line 108, in run
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:     self._target(*self._args, **self._kwargs)
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 1844, in _target
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:     run_func(minion_instance, opts, data)
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 1838, in run_func
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:     return Minion._thread_return(minion_instance, opts, data)
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 2074, in _thread_return
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:     minion_instance._return_pub(ret)
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 2276, in _return_pub
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:     ret_val = self._send_req_sync(load, timeout=timeout)
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 1609, in _send_req_sync
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:     return event.fire_event(
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/event.py", line 815, in fire_event
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:     dump_data = salt.payload.dumps(data, use_bin_type=True)
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/payload.py", line 173, in dumps
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:     return salt.utils.msgpack.packb(
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/msgpack.py", line 133, in packb
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:     return msgpack.packb(o, **_sanitize_msgpack_kwargs(kwargs))
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/msgpack/__init__.py", line 35, in packb
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:     return Packer(**kwargs).pack(o)
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:   File "msgpack/_packer.pyx", line 292, in msgpack._cmsgpack.Packer.pack
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:   File "msgpack/_packer.pyx", line 298, in msgpack._cmsgpack.Packer.pack
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:   File "msgpack/_packer.pyx", line 295, in msgpack._cmsgpack.Packer.pack
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:   File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:   File "msgpack/_packer.pyx", line 285, in msgpack._cmsgpack.Packer._pack
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/payload.py", line 168, in ext_type_encoder
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:     return dict(obj)
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:   File "/opt/saltstack/salt/lib/python3.10/_collections_abc.py", line 886, in __iter__
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:     yield from self._mapping
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/context.py", line 97, in __iter__
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]:     return self.value().__iter__()
   Nov 02 15:19:01 ausalttestclient10 salt-minion[367]: AttributeError: 'NoneType' object has no attribute '__iter__'
   ```

**Expected behavior**
Get a list/dict of some sort containing all the current configuration on the minion as well as non the master.

**Screenshots**
Not applicable.

**Versions Report**
<details><summary>salt --versions-report Master Version 3006.3 onedir on Debian 12</summary>

```yaml
Salt Version:
          Salt: 3006.3
 
Python Version:
        Python: 3.10.13 (main, Sep  6 2023, 02:11:27) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.13.10
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 12 bookworm
        locale: utf-8
       machine: x86_64
       release: 6.1.0-13-amd64
        system: Linux
       version: Debian GNU/Linux 12 bookworm
```
</details>

<details><summary>salt-minion --versions-report Minion Version 3006.3 onedir on Debian 10</summary>

```yaml
Salt Version:
          Salt: 3006.3
 
Python Version:
        Python: 3.10.13 (main, Sep  6 2023, 02:11:27) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.13.10
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 10 buster
        locale: utf-8
       machine: x86_64
       release: 4.19.0-25-amd64
        system: Linux
       version: Debian GNU/Linux 10 buster
```
</details>

<details><summary>salt-minion --versions-report Minion Version 3006.3 onedir on Debian 11</summary>

```yaml
Salt Version:
          Salt: 3006.3
 
Python Version:
        Python: 3.10.13 (main, Sep  6 2023, 02:11:27) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.13.10
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 11 bullseye
        locale: utf-8
       machine: x86_64
       release: 5.10.0-26-amd64
        system: Linux
       version: Debian GNU/Linux 11 bullseye
```
</details>

<details><summary>salt-minion --versions-report Minion Version 3006.3 onedir on Debian 12</summary>

```yaml
Salt Version:
          Salt: 3006.3
 
Python Version:
        Python: 3.10.13 (main, Sep  6 2023, 02:11:27) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.13.10
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 12 bookworm
        locale: utf-8
       machine: x86_64
       release: 6.1.0-13-amd64
        system: Linux
       version: Debian GNU/Linux 12 bookworm
```
</details>

**Additional context**
Nothing to say here.

**Comment by er0k** [comment]
I see the same behavior with 3007.1 master and minions: `config.items` results in an exception on the minion and a `Minion did not return. [Not connected]` error on the master.
```
2024-09-06 03:31:56,629 [salt.utils.process:1000][ERROR   ][2848471] An un-handled exception from the multiprocessing process 'ProcessPayload(jid=20240906033156379236)' was caught:
Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/process.py", line 995, in wrapped_run_func
    return run_func()
  File "/opt/saltstack/salt/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 1867, in _target
    run_func(minion_instance, opts, data)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 1864, in run_func
    return Minion._thread_return(minion_instance, opts, data)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 2100, in _thread_return
    minion_instance._return_pub(ret)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 2303, in _return_pub
    ret_val = self._send_req_sync(load, timeout=timeout)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 1637, in _send_req_sync
    return event.fire_event(
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/event.py", line 769, in fire_event
    event = self.pack(tag, data, max_size=self.opts["max_event_size"])
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/event.py", line 430, in pack
    serialized_data = salt.payload.dumps(data, use_bin_type=True)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/payload.py", line 161, in dumps
    return salt.utils.msgpack.packb(
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/msgpack.py", line 113, in packb
    return msgpack.packb(o, **_sanitize_msgpack_kwargs(kwargs))
  File "/opt/saltstack/salt/lib/python3.10/site-packages/msgpack/__init__.py", line 36, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 294, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 300, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 297, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 285, in msgpack._cmsgpack.Packer._pack
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/payload.py", line 156, in ext_type_encoder
    return dict(obj)
  File "/opt/saltstack/salt/lib/python3.10/_collections_abc.py", line 886, in __iter__
    yield from self._mapping
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/context.py", line 101, in __iter__
    return self.value().__iter__()
AttributeError: 'NoneType' object has no attribute '__iter__'```

**Comment by dwoz** [comment]
Fix merged and shipped in a supported release. Closing per bulk triage. Reopen if this reproduces on a currently supported release (3006.x, 3007.x, 3008.x, master).
