### ISSUE TITLE
[BUG] mac_power functions fail as "argument of type 'bool' is not iterable"

### ISSUE THREAD

**Issue by kbrewersq** [saltstack/salt#65671]
**Description**

When attempting to run the module `mac_power.py` functions `set_sleep_on_power_button` and `set_restart_power_failure` the module fails with the error: "argument of type 'bool' is not iterable"

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [ x ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ x ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

on macos mac mini, arm architecture
```
sudo salt-call power.set_restart_power_failure enabled=true -l debug
```
fails the following logs are relavent:
```
[DEBUG   ] The functions from module 'power' are being loaded by dir() on the loaded module
[DEBUG   ] LazyLoaded power.set_sleep_on_power_button
[DEBUG   ] The functions from module 'direct_call' are being loaded by dir() on the loaded module
[DEBUG   ] LazyLoaded direct_call.execute
[DEBUG   ] Execute return success systemsetup -setallowpowerbuttontosleepcomputer on: {'pid': 9484, 'retcode': 0, 'stdout': 'setallowpowerbuttontosleepcomputer: On', 'stderr': '2023-12-06 05:42:06.454 systemsetup[9484:12980662] ### Error:-99 File:/AppleInternal/Library/BuildRoots/11aa8fb2-5f4b-11ee-bc7f-926038f30c31/Library/Caches/com.apple.xbs/Sources/Admin/InternetServices.m Line:379'}
[DEBUG   ] Confirm update try: 0 func:<function get_sleep_on_power_button at 0x112fe5750> state:True value:on

Passed invalid arguments: argument of type 'bool' is not iterable.

Usage:

    Set whether or not the power button can sleep the computer.

    :param bool enabled: True to enable, False to disable. "On" and "Off" are
        also acceptable values. Additionally you can pass 1 and 0 to represent
        True and False respectively

    :return: True if successful, False if not
    :rtype: bool

    CLI Example:

    .. code-block:: bash

        salt '*' power.set_sleep_on_power_button True
    
Traceback (most recent call last):
  File "/opt/salt/lib/python3.10/site-packages/salt/cli/caller.py", line 202, in call
    ret["return"] = self.minion.executors[fname](
  File "/opt/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 159, in __call__
    ret = self.loader.run(run_func, *args, **kwargs)
  File "/opt/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1245, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/opt/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1260, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/opt/salt/lib/python3.10/site-packages/salt/executors/direct_call.py", line 10, in execute
    return func(*args, **kwargs)
  File "/opt/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 159, in __call__
    ret = self.loader.run(run_func, *args, **kwargs)
  File "/opt/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1245, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/opt/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1260, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/opt/salt/lib/python3.10/site-packages/salt/modules/mac_power.py", line 508, in set_sleep_on_power_button
    return salt.utils.mac_utils.confirm_updated(
  File "/opt/salt/lib/python3.10/site-packages/salt/utils/mac_utils.py", line 264, in confirm_updated
    if value in state:
TypeError: argument of type 'bool' is not iterable
```

**Expected behavior**

It should not fail. 

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Password:
Salt Version:
          Salt: 3006.4
 
Python Version:
        Python: 3.10.13 (main, Oct  4 2023, 21:57:46) [Clang 14.0.0 (clang-1400.0.29.202)]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.0
     docker-py: Not Installed
         gitdb: 4.0.5
     gitpython: 3.1.37
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.13.12
         smmap: 3.0.2
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: darwin 23.1.0 
        locale: utf-8
       machine: x86_64
       release: 23.1.0
        system: Darwin
       version: 14.1.1 x86_64
```
</details>

**Additional context**

I believe this is easily addressed by adding the `normalize_ret=True` in the function calls for `set_restart_power_failure` and `set_sleep_on_power_button`: 

```
    return salt.utils.mac_utils.confirm_updated(
        state,
        get_restart_power_failure,
        normalize_ret=True,
    )
```

**Comment by dwoz** [comment]
Fixed in 1bab15f901a (Nov 2023). `set_restart_power_failure` and `set_sleep_on_power_button` now pass `normalize_ret=True` to `confirm_updated`, which was your suggested fix. Present on 3006.x/3007.x/3008.x/master. Closing.
