### ISSUE TITLE
[BUG] Salt Client API raises KeyError(key) KeyError: 'saltutil.is_running'

### ISSUE THREAD

**Issue by leeclemens** [saltstack/salt#65778]
**Description**
Using the Salt Client API, the minion returns Exceptions during `highstate` and calling a specific sls state, with `KeyError: 'saltutil.is_running'`.

**Setup**
Minions and Master installed via OneDir on RHEL 7 and RHEL 8 systems. Master's python code is 3006.5 in virtual environment.

Please be as specific as possible and give set-up details.

- [X] VM (Virtualbox, KVM, etc. please specify)
- [X] onedir packaging

**Steps to Reproduce the behavior**
Call highstate or sls from Salt client API in python script connecting to minion.

**Expected behavior**
A proper response is returned.

**Screenshots**
N/A

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
PASTE HERE
```
</details>

**Additional context**
```
The minion function caused an exception:

Traceback (most recent call last):

File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 1943, in _thread_return return return_data
File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 1902, in _execute_job_function if self.opts["grains"].get("minion_blackout", False):
File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 159, in __call__ ret = self.loader.run(run_func, *args, **kwargs)
File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1245, in run return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1260, in _run_as return _func_or_method(*args, **kwargs)
File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/executors/direct_call.py", line 10, in execute return func(*args, **kwargs)
File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 159, in __call__ ret = self.loader.run(run_func, *args, **kwargs)
File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1245, in run return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1260, in _run_as return _func_or_method(*args, **kwargs)
File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/modules/state.py", line 1357, in sls conflict = _check_queue(queue, kwargs)
File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/modules/state.py", line 430, in _check_queue conflict = running(concurrent=kwargs.get("concurrent", False))
File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/modules/state.py", line 381, in running active = __salt__["saltutil.is_running"]("state.*")
File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/context.py", line 78, in __getitem__ return self.value()[item]
File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 349, in __getitem__ super().__getitem__(item) # try to get the item from the dictionary
File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/lazy.py", line 105, in __getitem__ raise KeyError(key) KeyError: 'saltutil.is_running'    
```

**Comment by mtorromeo** [comment]
This happens on all my RHEL machines when I upgrade the salt-minion package, until I restart the salt-minion service.

It would be nice if the service could be automatically restarted after an upgrade of its package.

**Comment by leeclemens** [comment]
Thanks, that seems to have been the case. Some systems ended up upgrading the salt packages and a manual (ssh) restart of the service seems to have resolved it.
