### ISSUE TITLE
_pygit2.GitError: unexpected http status code: 403

### ISSUE THREAD

**Issue by speedytom** [saltstack/salt#65820]
**Description**

<pre>
Jan 09 10:47:17 salt salt-master[46793]: Traceback (most recent call last):
Jan 09 10:47:17 salt salt-master[46793]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/gitfs.py", line 1991, in _fetch
Jan 09 10:47:17 salt salt-master[46793]:     fetch_results = origin.fetch(**fetch_kwargs)
Jan 09 10:47:17 salt salt-master[46793]:   File "/opt/saltstack/salt/extras-3.10/pygit2/remote.py", line 147, in fetch
Jan 09 10:47:17 salt salt-master[46793]:     payload.check_error(err)
Jan 09 10:47:17 salt salt-master[46793]:   File "/opt/saltstack/salt/extras-3.10/pygit2/callbacks.py", line 93, in check_error
Jan 09 10:47:17 salt salt-master[46793]:     check_error(error_code)
Jan 09 10:47:17 salt salt-master[46793]:   File "/opt/saltstack/salt/extras-3.10/pygit2/errors.py", line 65, in check_error
Jan 09 10:47:17 salt salt-master[46793]:     raise GitError(message)
Jan 09 10:47:17 salt salt-master[46793]: _pygit2.GitError: unexpected http status code: 403
</pre>

System Versions:
<pre>
root@salt:~# salt --versions-report
Salt Version:
          Salt: 3006.5
 
Python Version:
        Python: 3.10.13 (main, Nov 15 2023, 04:34:27) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.10
     gitpython: 3.1.31
        Jinja2: 3.1.2
       libgit2: 1.3.0
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: 1.7.2
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.14.2
         smmap: 5.0.0
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: ubuntu 22.04.3 jammy
        locale: utf-8
       machine: x86_64
       release: 5.15.0-91-generic
        system: Linux
       version: Ubuntu 22.04.3 jammy

</pre>

**Setup**
I tried upgrading to the latest version of pygit2:

<pre>
root@salt:/etc/apt# /opt/saltstack/salt/salt-pip install pygit2==1.13.1 --no-deps

root@salt:/etc/apt# /opt/saltstack/salt/salt-pip list |grep pygit2
pygit2             1.13.3

gitfs_remotes:
  - https://repo.tok.ipp.cas.cz/codac/deployment.git:
    - user: dddddd
    - password: XXXXXXXXXXXXXxxxxxxxxxxxxxx
    - update_interval: 360
    - mountpoint: salt://codac
    - base: main
  - 'https://repo.tok.ipp.cas.cz/compass-tokamak/ansys-batch-generator.git':
    - user: dddddddd
    - password: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    - update_interval: 360

salt@salt:~$ ldd /opt/saltstack/salt/extras-3.10/pygit2.libs/libgit2-cea5a825.so.1.7.1 
        linux-vdso.so.1 (0x00007fff20f72000)
        libssl-acd66275.so.3 => not found
        libcrypto-8fb34a01.so.3 => not found
        libpcre-9513aab5.so.1.2.0 => not found
        libssh2-c5cb4cb9.so.1.0.1 => not found
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f238d2a0000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f238d299000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f238d294000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f238d06c000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f238d461000)
salt@salt:~$ 
salt@salt:~$ 
salt@salt:~$ 
salt@salt:~$ LD_LIBRARY_PATH=/opt/saltstack/salt/extras-3.10/pygit2.libs ldd /opt/saltstack/salt/extras-3.10/pygit2.libs/libgit2-cea5a825.so.1.7.1 
        linux-vdso.so.1 (0x00007ffc14fc7000)
        libssl-acd66275.so.3 => /opt/saltstack/salt/extras-3.10/pygit2.libs/libssl-acd66275.so.3 (0x00007fef82272000)
        libcrypto-8fb34a01.so.3 => /opt/saltstack/salt/extras-3.10/pygit2.libs/libcrypto-8fb34a01.so.3 (0x00007fef81d19000)
        libpcre-9513aab5.so.1.2.0 => /opt/saltstack/salt/extras-3.10/pygit2.libs/libpcre-9513aab5.so.1.2.0 (0x00007fef81a00000)
        libssh2-c5cb4cb9.so.1.0.1 => /opt/saltstack/salt/extras-3.10/pygit2.libs/libssh2-c5cb4cb9.so.1.0.1 (0x00007fef81cc0000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fef81c9d000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fef81c96000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fef81c91000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fef817d8000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fef81c8c000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fef824cd000)

</pre>
I added Environment:
<pre>
root@salt:/etc/apt# cat /lib/systemd/system/salt-master.service
[Unit]
Description=The Salt Master Server
Documentation=man:salt-master(1) file:///usr/share/doc/salt/html/contents.html https://docs.saltproject.io/en/latest/contents.html
After=network.target

[Service]
Environment="HOME=/opt/saltstack/salt"
Environment="LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/opt/saltstack/salt/extras-3.10/pygit2.libs"
LimitNOFILE=100000
Type=notify
NotifyAccess=all
ExecStart=/usr/bin/salt-master

[Install]
WantedBy=multi-user.target

</pre>

I am able searching and deploying by salt:
<pre>
root@epicstest:~# salt-call  state.sls_exists codac.epicstest
local:
    True
root@epicstest:~# salt-call  state.sls_exists codac.bashrc
local:
    True

root@epicstest:~# salt-call  state.apply test=true codac.deployment
local:
----------
          ID: ca-certificates
    Function: pkg.installed
      Result: True
     Comment: All specified packages are already installed
     Started: 11:42:21.205253
    Duration: 7.72 ms
     Changes:   
----------
          ID: /etc/apt/sources.list
    Function: file.managed
      Result: True
     Comment: The file /etc/apt/sources.list is in the correct state
     Started: 11:42:21.214173
    Duration: 18.173 ms
     Changes:   
----------
          ID: ipp-local-repo-key
    Function: cmd.run
        Name: wget -q -O- http://intra.tok.ipp.cas.cz/repos/apt/deb/conf/dbr.gpg.key | sudo apt-key add -
      Result: True
     Comment: unless condition is true
     Started: 11:42:21.232972
    Duration: 358.171 ms
     Changes:   
----------
          ID: /etc/apt/trusted.gpg.d/intra.gpg
    Function: file.managed
      Result: True
     Comment: The file /etc/apt/trusted.gpg.d/intra.gpg is in the correct state
     Started: 11:42:21.591309
    Duration: 4.739 ms
     Changes:   
----------
          ID: /etc/apt/sources.list.d/ipp-local.list
    Function: file.managed
      Result: True
     Comment: The file /etc/apt/sources.list.d/ipp-local.list is in the correct state
     Started: 11:42:21.596149
    Duration: 11.797 ms
     Changes:   

................................
Summary for local
-------------
Succeeded: 14 (unchanged=1)
Failed:     0
-------------
Total states run:     14
Total run time:  454.853 ms
</pre>

Error message still persist after all my action:
<pre>
root@salt:/etc/apt# systemctl status salt-master.service 
● salt-master.service - The Salt Master Server
     Loaded: loaded (/lib/systemd/system/salt-master.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2024-01-09 11:36:26 CET; 41min ago
       Docs: man:salt-master(1)
             file:///usr/share/doc/salt/html/contents.html
             https://docs.saltproject.io/en/latest/contents.html
   Main PID: 55960 (/opt/saltstack/)
      Tasks: 46 (limit: 4558)
     Memory: 441.1M
        CPU: 31.796s
     CGroup: /system.slice/salt-master.service
             ├─55960 "/opt/saltstack/salt/bin/python3.10 /usr/bin/salt-master MainProcess"
             ├─56012 "/opt/saltstack/salt/bin/python3.10 /usr/bin/salt-master PubServerChannel._publish_daemon"
             ├─56013 "/opt/saltstack/salt/bin/python3.10 /usr/bin/salt-master EventPublisher"
             ├─56016 "/opt/saltstack/salt/bin/python3.10 /usr/bin/salt-master Engine(salt.loaded.int.engines.reactor) Reactor-3:1"
             ├─56017 "/opt/saltstack/salt/bin/python3.10 /usr/bin/salt-master Maintenance"
             ├─56018 "/opt/saltstack/salt/bin/python3.10 /usr/bin/salt-master ReqServer ReqServer_ProcessManager"
             ├─56019 "/opt/saltstack/salt/bin/python3.10 /usr/bin/salt-master ReqServer MWorkerQueue"
             ├─56020 "/opt/saltstack/salt/bin/python3.10 /usr/bin/salt-master FileServerUpdate"
             ├─56021 "/opt/saltstack/salt/bin/python3.10 /usr/bin/salt-master ReqServer MWorker-0"
             ├─56022 "/opt/saltstack/salt/bin/python3.10 /usr/bin/salt-master ReqServer MWorker-1"
             ├─56023 "/opt/saltstack/salt/bin/python3.10 /usr/bin/salt-master ReqServer MWorker-2"
             ├─56024 "/opt/saltstack/salt/bin/python3.10 /usr/bin/salt-master ReqServer MWorker-3"
             └─56025 "/opt/saltstack/salt/bin/python3.10 /usr/bin/salt-master ReqServer MWorker-4"

Jan 09 12:12:31 salt salt-master[56020]: Traceback (most recent call last):
Jan 09 12:12:31 salt salt-master[56020]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/gitfs.py", line 1991, in _fetch
Jan 09 12:12:31 salt salt-master[56020]:     fetch_results = origin.fetch(**fetch_kwargs)
Jan 09 12:12:31 salt salt-master[56020]:   File "/opt/saltstack/salt/extras-3.10/pygit2/remote.py", line 148, in fetch
Jan 09 12:12:31 salt salt-master[56020]:     payload.check_error(err)
Jan 09 12:12:31 salt salt-master[56020]:   File "/opt/saltstack/salt/extras-3.10/pygit2/callbacks.py", line 98, in check_error
Jan 09 12:12:31 salt salt-master[56020]:     check_error(error_code)
Jan 09 12:12:31 salt salt-master[56020]:   File "/opt/saltstack/salt/extras-3.10/pygit2/errors.py", line 65, in check_error
Jan 09 12:12:31 salt salt-master[56020]:     raise GitError(message)
Jan 09 12:12:31 salt salt-master[56020]: _pygit2.GitError: unexpected http status code: 403
</pre>

**Comment by speedytom** [comment]
<pre>
/etc/salt/master
# The user under which the salt master will run. Salt will update all
# permissions to allow the specified user to run the master. The exception is
# the job cache, which must be deleted if this user is changed. If the
# modified files cause conflicts, set verify_env to False.
user: salt
</pre>

**Comment by speedytom** [comment]
I deeply apologize. There is no bug in salt-master:

I realized that GitLab block my access from salt-master.

I fixed on the GitLab:
<pre>
 root@repo:/etc/gitlab# diff -u gitlab.rb.20240115 gitlab.rb
--- gitlab.rb.20240115  2024-01-15 12:54:28.400880416 +0100
+++ gitlab.rb   2024-01-15 13:33:08.761893993 +0100
@@ -410,7 +410,7 @@

  gitlab_rails['rack_attack_git_basic_auth'] = {
    'enabled' => true,
-   'ip_whitelist' => ["127.0.0.1"],
+   'ip_whitelist' => ["127.0.0.1", "12.1.137.236"],
    'maxretry' => 10,
    'findtime' => 60,
    'bantime' => 3600
</pre>
