### ISSUE TITLE
[BUG] Proxy usage for http broken in 3006.5

### ISSUE THREAD

**Issue by benfiedler** [saltstack/salt#65824]
**Description**
Using an archive.extracted / file.managed to pull down a remote file where a proxy is needed to get out stopped working in salt version 3006.5

**Setup**

`/etc/salt/minion.d/f_defaults.conf :`
```
proxy_host: my.local.proxy
proxy_port: 3128

no_proxy:
  - .local
  - 192.168.1.0/24
```

- [x] on-prem machine
- [x] VM (VMware)
- [x] onedir packaging
- [x] used bootstrap to install

**Steps to Reproduce the behavior**

e.g. to download the latest version of helm:
```
helm.download:
  archive.extracted:
    - name: /usr/local/bin
    - source: https://get.helm.sh/helm-v3.13.3-linux-amd64.tar.gz
    - source_hash: https://get.helm.sh/helm-v3.13.3-linux-amd64.tar.gz.sha256sum
    - options: |
      --wildcards 'linux-amd64/helm'
      --transform 's,linux-amd64/,,'
    - enforce_ownership_on: /usr/local/bin
    - user: root
    - group: root
    - mode: 0755
```

**Expected behavior**
The file(s) should download and extract as expected

**Logs**

Here is a debug minion log of the failure occurring:
```
2024-01-09 13:53:56,120 [salt.state       :2326][INFO    ][62674] Executing state archive.extracted for [/usr/local/bin]
2024-01-09 13:53:56,122 [salt.utils.http  :240 ][DEBUG   ][62674] Switching to request backend due to the use of proxies.
2024-01-09 13:53:56,123 [salt.utils.http  :288 ][DEBUG   ][62674] Requesting URL https://get.helm.sh/helm-v3.13.3-linux-amd64.tar.gz.sha256sum using GET method
2024-01-09 13:53:56,123 [salt.utils.http  :289 ][DEBUG   ][62674] Using backend: requests
2024-01-09 13:53:56,125 [urllib3.connectionpool:1019][DEBUG   ][62674] Starting new HTTPS connection (1): get.helm.sh:443
2024-01-09 13:53:56,127 [salt.state       :2437][DEBUG   ][62674] An exception occurred in this state: HTTPSConnectionPool(host='get.helm.sh', port=443): Max retries exceeded with url: /helm-v3.13.3-linux-amd64.tar.gz.sha256sum (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1a44fb8be0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/opt/saltstack/salt/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/opt/saltstack/salt/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/opt/saltstack/salt/lib/python3.10/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/opt/saltstack/salt/lib/python3.10/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/opt/saltstack/salt/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f1a44fb8be0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/saltstack/salt/lib/python3.10/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/opt/saltstack/salt/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='get.helm.sh', port=443): Max retries exceeded with url: /helm-v3.13.3-linux-amd64.tar.gz.sha256sum (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1a44fb8be0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/state.py", line 2423, in call
    ret = self.states[cdata["full"]](
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 159, in __call__
    ret = self.loader.run(run_func, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1245, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1260, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1293, in wrapper
    return f(*args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/states/archive.py", line 981, in extracted
    source_sum = __salt__["file.get_source_sum"](
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 159, in __call__
    ret = self.loader.run(run_func, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1245, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1260, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/modules/file.py", line 847, in get_source_sum
    hash_fn = __salt__["cp.cache_file"](
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 159, in __call__
    ret = self.loader.run(run_func, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1245, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1260, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/modules/cp.py", line 552, in cache_file
    result = client.cache_file(
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/fileclient.py", line 192, in cache_file
    return self.get_url(
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/fileclient.py", line 792, in get_url
    query = salt.utils.http.query(
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/http.py", line 423, in query
    result = sess.request(method, url, params=params, data=data, **req_kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='get.helm.sh', port=443): Max retries exceeded with url: /helm-v3.13.3-linux-amd64.tar.gz.sha256sum (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1a44fb8be0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-01-09 13:53:56,130 [salt.state       :323 ][ERROR   ][62674] An exception occurred in this state: Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/opt/saltstack/salt/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/opt/saltstack/salt/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/opt/saltstack/salt/lib/python3.10/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/opt/saltstack/salt/lib/python3.10/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/opt/saltstack/salt/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f1a44fb8be0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/saltstack/salt/lib/python3.10/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/opt/saltstack/salt/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='get.helm.sh', port=443): Max retries exceeded with url: /helm-v3.13.3-linux-amd64.tar.gz.sha256sum (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1a44fb8be0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/state.py", line 2423, in call
    ret = self.states[cdata["full"]](
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 159, in __call__
    ret = self.loader.run(run_func, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1245, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1260, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1293, in wrapper
    return f(*args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/states/archive.py", line 981, in extracted
    source_sum = __salt__["file.get_source_sum"](
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 159, in __call__
    ret = self.loader.run(run_func, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1245, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1260, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/modules/file.py", line 847, in get_source_sum
    hash_fn = __salt__["cp.cache_file"](
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 159, in __call__
    ret = self.loader.run(run_func, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1245, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1260, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/modules/cp.py", line 552, in cache_file
    result = client.cache_file(
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/fileclient.py", line 192, in cache_file
    return self.get_url(
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/fileclient.py", line 792, in get_url
    query = salt.utils.http.query(
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/http.py", line 423, in query
    result = sess.request(method, url, params=params, data=data, **req_kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='get.helm.sh', port=443): Max retries exceeded with url: /helm-v3.13.3-linux-amd64.tar.gz.sha256sum (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1a44fb8be0>: Failed to establish a new connection: [Errno 111] Connection refused'))

2024-01-09 13:53:56,130 [salt.state       :2493][INFO    ][62674] Completed state [/usr/local/bin] at time 13:53:56.130851 (duration_in_ms=10.359)
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3006.5

Python Version:
        Python: 3.10.13 (main, Nov 15 2023, 04:34:27) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.14.2
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: ubuntu 22.04.3 jammy
        locale: utf-8
       machine: x86_64
       release: 5.15.0-25-generic
        system: Linux
       version: Ubuntu 22.04.3 jammy
```
</details>

**Additional context**
I noticed that [this commit](https://github.com/saltstack/salt/commit/055d1daa23f1c123658f88ddcca3a5683f2ede1f) related to [this issue](https://github.com/saltstack/salt/issues/64371) was pulled in on 3006.5, although I don't see anything mentioned about proxy/tornado/pycurl in the changelog.
I am definitely in favor of this change - having to install pycurl+tornado was a bit of an annoyance we could do without, but I also need the new method to function for my environment :)

I do happen to have a similarly built Ubuntu 3006.4 minion (with pycurl+tornado) installed, and using the sls example above works perfectly fine there.

My ugly 'workaround' for 3006.5 minions was to 

1. install pycurl+tornado with `# salt-call pip.install pkgs=tornado,pycurl force_reinstall=true upgrade=true proxy=http://my.local.proxy:3128/`
2. Rollback `/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/http.py` to [the 3006.4 version](https://github.com/saltstack/salt/blob/v3006.4/salt/utils/http.py).
3. Bounce the salt-minion

As an aside rant, I don't like how the official salt package repos only have the latest minion package present, e.g. I can't simply rollback affected systems to the 3006.4 _using apt_ unless I happen to have it cached somewhere.

**Comment by max-arnold** [comment]
Minor versions are available https://repo.saltproject.io/salt/py3/ubuntu/22.04/amd64/minor/

**Comment by tkaehn** [comment]
You can also set an environment variable in the state file as a workaround:

```
set https_proxy environment variable:
   environ.setenv:
     - name: https_proxy
     - value: {{ https_proxy }}
     - prereq:
       - {{ state_that_needs_a_proxy }}
```

However the bug that the proxy from the minion config isn't used should be fixed.

**Comment by benfiedler** [comment]
> Minor versions are available https://repo.saltproject.io/salt/py3/ubuntu/22.04/amd64/minor/

Ah this is very helpful, thank you! I guess I didn't realize /latest/ repo is latest packages exclusively.

**Comment by shalashik** [comment]
As another workaround I set env variables for `salt-minion` service via systemd
```
 # cat /etc/systemd/system/salt-minion.service.d/http-proxy.conf
[Service]
Environment="HTTP_PROXY=http://<host>:<port>"
Environment="HTTPS_PROXY=http://<host>:<port>"
Environment="NO_PROXY=localhost,127.0.0.1"
```

Also I've noticed that you shouldn't remove `proxy_host` and `proxy_port` from minion's config file, but the values of these options are ignored in favour of env variables.

**Comment by whytewolf** [comment]
I was wondering if someone can test a possible fix for me. before i add this change to the code. 

on line 364, of the `utils.http` file should be this line

```
        if http_proxy_url is not None:
            sess.proxies = {"http": http_proxy_url}
```

change that to 

```
        if http_proxy_url is not None:
            sess.proxies = {"http": http_proxy_url, "https": http_proxy_url}
          
```

I'm wondering if it is just cause the https scheme was left off and requests doesn't know what to use for https proxies. 

If that works for one of the testers I'll add a quick bug fix for it.

**Comment by benfiedler** [comment]
> I was wondering if someone can test a possible fix for me. before i add this change to the code.
> 
> on line 364, of the `utils.http` file should be this line
> 
> ```
>         if http_proxy_url is not None:
>             sess.proxies = {"http": http_proxy_url}
> ```
> 
> change that to
> 
> ```
>         if http_proxy_url is not None:
>             sess.proxies = {"http": http_proxy_url, "https": http_proxy_url}
>           
> ```
> 
> I'm wondering if it is just cause the https scheme was left off and requests doesn't know what to use for https proxies.
> 
> If that works for one of the testers I'll add a quick bug fix for it.

Nice, I can confirm that this resolves the issue! This is the new minion debug log:

```yaml
2024-01-12 16:39:29,406 [salt.state       :2326][INFO    ][110295] Executing state archive.extracted for [/usr/local/bin]
2024-01-12 16:39:29,407 [salt.utils.http  :240 ][DEBUG   ][110295] Switching to request backend due to the use of proxies.
2024-01-12 16:39:29,408 [salt.utils.http  :288 ][DEBUG   ][110295] Requesting URL https://get.helm.sh/helm-v3.13.3-linux-amd64.tar.gz.sha256sum using GET method
2024-01-12 16:39:29,408 [salt.utils.http  :289 ][DEBUG   ][110295] Using backend: requests
2024-01-12 16:39:29,411 [urllib3.connectionpool:1019][DEBUG   ][110295] Starting new HTTPS connection (1): get.helm.sh:443
2024-01-12 16:39:30,327 [urllib3.connectionpool:474 ][DEBUG   ][110295] https://get.helm.sh:443 "GET /helm-v3.13.3-linux-amd64.tar.gz.sha256sum HTTP/1.1" 200 98
2024-01-12 16:39:30,333 [salt.loaded.int.module.file:4925][DEBUG   ][110295] file.extract_hash: Extracting any supported hash for file matching: https://get.helm.sh/helm-v3.13.3-linux-amd64.tar.gz
2024-01-12 16:39:30,335 [salt.loaded.int.module.file:4967][DEBUG   ][110295] file.extract_hash: Line 'bbb6e7c6201458b235f335280f35493950dcd856825ddcfd1d3b40ae757d5c7d  helm-v3.13.3-linux-amd64.tar.gz' matches source 'https://get.helm.sh/helm-v3.13.3-linux-amd64.tar.gz'
2024-01-12 16:39:30,336 [salt.loaded.int.module.file:5057][DEBUG   ][110295] file.extract_hash: Returning sha256 hash 'bbb6e7c6201458b235f335280f35493950dcd856825ddcfd1d3b40ae757d5c7d' as a match of https://get.helm.sh/helm-v3.13.3-linux-amd64.tar.gz
2024-01-12 16:39:30,339 [salt.loader.lazy :977 ][DEBUG   ][110295] The functions from module 'file' are being loaded by dir() on the loaded module
2024-01-12 16:39:30,339 [salt.utils.lazy  :99  ][DEBUG   ][110295] LazyLoaded file.cached
2024-01-12 16:39:30,340 [salt.loaded.int.module.file:4925][DEBUG   ][110295] file.extract_hash: Extracting any supported hash for file matching: https://get.helm.sh/helm-v3.13.3-linux-amd64.tar.gz
2024-01-12 16:39:30,341 [salt.loaded.int.module.file:4967][DEBUG   ][110295] file.extract_hash: Line 'bbb6e7c6201458b235f335280f35493950dcd856825ddcfd1d3b40ae757d5c7d  helm-v3.13.3-linux-amd64.tar.gz' matches source 'https://get.helm.sh/helm-v3.13.3-linux-amd64.tar.gz'
2024-01-12 16:39:30,341 [salt.loaded.int.module.file:5057][DEBUG   ][110295] file.extract_hash: Returning sha256 hash 'bbb6e7c6201458b235f335280f35493950dcd856825ddcfd1d3b40ae757d5c7d' as a match of https://get.helm.sh/helm-v3.13.3-linux-amd64.tar.gz
2024-01-12 16:39:30,342 [salt.utils.http  :240 ][DEBUG   ][110295] Switching to request backend due to the use of proxies.
2024-01-12 16:39:30,343 [salt.utils.http  :288 ][DEBUG   ][110295] Requesting URL https://get.helm.sh/helm-v3.13.3-linux-amd64.tar.gz using GET method
2024-01-12 16:39:30,343 [salt.utils.http  :289 ][DEBUG   ][110295] Using backend: requests
2024-01-12 16:39:30,344 [urllib3.connectionpool:1019][DEBUG   ][110295] Starting new HTTPS connection (1): get.helm.sh:443
2024-01-12 16:39:30,516 [urllib3.connectionpool:474 ][DEBUG   ][110295] https://get.helm.sh:443 "GET /helm-v3.13.3-linux-amd64.tar.gz HTTP/1.1" 200 16188560
2024-01-12 16:39:31,053 [salt.loaded.int.states.archive:1075][DEBUG   ][110295] file.cached: {'changes': {'hash': {'old': None, 'new': 'bbb6e7c6201458b235f335280f35493950dcd856825ddcfd1d3b40ae757d5c7d'}}, 'comment': 'File is already cached to /var/cache/salt/minion/extrn_files/base/get.helm.sh/helm-v3.13.3-linux-amd64.tar.gz with hash bbb6e7c6201458b235f335280f35493950dcd856825ddcfd1d3b40ae757d5c7d', 'name': 'https://get.helm.sh/helm-v3.13.3-linux-amd64.tar.gz', 'result': True}
2024-01-12 16:39:31,054 [salt.loaded.int.states.archive:85  ][DEBUG   ][110295] Using checksum file /var/cache/salt/minion/archive_hash/extrn_files/base/get.helm.sh/helm-v3.13.3-linux-amd64.tar.gz.hash for cached archive file /var/cache/salt/minion/extrn_files/base/get.helm.sh/helm-v3.13.3-linux-amd64.tar.gz
2024-01-12 16:39:31,057 [salt.loader.lazy :977 ][DEBUG   ][110295] The functions from module 'archive' are being loaded by dir() on the loaded module
2024-01-12 16:39:31,057 [salt.utils.lazy  :99  ][DEBUG   ][110295] LazyLoaded archive.list
2024-01-12 16:39:31,572 [salt.loaded.int.states.archive:1388][DEBUG   ][110295] Extracting /var/cache/salt/minion/extrn_files/base/get.helm.sh/helm-v3.13.3-linux-amd64.tar.gz to /usr/local/bin/
2024-01-12 16:39:31,574 [salt.loader.lazy :977 ][DEBUG   ][110295] The functions from module 'cmd' are being loaded by dir() on the loaded module
2024-01-12 16:39:31,574 [salt.utils.lazy  :99  ][DEBUG   ][110295] LazyLoaded cmd.run_all
2024-01-12 16:39:31,575 [salt.loaded.int.module.cmdmod:438 ][INFO    ][110295] Executing command tar in directory '/usr/local/bin/'
2024-01-12 16:39:31,962 [salt.loaded.int.module.cmdmod:922 ][DEBUG   ][110295] stdout: linux-amd64/helm
2024-01-12 16:39:31,963 [salt.loaded.int.module.cmdmod:438 ][INFO    ][110295] Executing command tar in directory '/root'
2024-01-12 16:39:31,966 [salt.loaded.int.module.cmdmod:922 ][DEBUG   ][110295] stdout: tar (GNU tar) 1.34
.... etc
```

**Comment by damon-atkins** [comment]
On a side note, there should be some doco pointing to the library doco as NO_PROXY/no_proxy  does not have any standards.
