### ISSUE TITLE
[BUG] ValueError: filedescriptor out of range in select() 

### ISSUE THREAD

**Issue by Stajl** [saltstack/salt#65878]
**Description**
[BUG] salt-ssh ValueError: filedescriptor out of range in select() 

**LOG /var/log/salt/salt-ssh.log**

```

[salt.utils.process:998 ][ERROR   ][2245013] An un-handled exception from the multiprocessing process 'Process-950' was caught:
Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/process.py", line 993, in wrapped_run_func
    return run_func()
  File "/opt/saltstack/salt/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/client/ssh/__init__.py", line 549, in handle_routine
    stdout, stderr, retcode = single.run()
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/client/ssh/__init__.py", line 1090, in run
    stdout, stderr, retcode = self.cmd_block()
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/client/ssh/__init__.py", line 1431, in cmd_block
    stdout, stderr, retcode = self.shim_cmd(cmd_str)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/client/ssh/__init__.py", line 1388, in shim_cmd
    return self.shell.exec_cmd(cmd_str)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/client/ssh/shell.py", line 337, in exec_cmd
    ret = self._run_cmd(cmd)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/client/ssh/shell.py", line 406, in _run_cmd
    stdout, stderr = term.recv()
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/vt.py", line 309, in recv
    return self._recv(maxsize)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/vt.py", line 530, in _recv
    rlist, _, _ = select.select(rfds, [], [], 0)
ValueError: filedescriptor out of range in select()

```

**Versions Report**
```
Salt Version:
          Salt: 3006.3
 
Python Version:
        Python: 3.10.13 (main, Sep  6 2023, 02:11:27) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: 0.40.1
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: 2.6.1
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.13.10
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: ubuntu 22.04.3 jammy
        locale: utf-8
       machine: x86_64
       release: 5.15.0-88-generic
        system: Linux
       version: Ubuntu 22.04.3 jammy
```

**Steps to Reproduce Issue**
```
salt-ssh -i -v --max-procs=100 '*' cmd.run 'uptime'
```

**Additional context**
In roster file, we have over  >500 hosts(objects)
when execute salt-ssh  from master 

in process
```
/opt/saltstack/salt/bin/python3.10 /usr/bin/salt-ssh -i -v --max-procs=100 * cmd.run uptime MainProcess
```

Get PID of MainProcess :
```lsof -p $PID  | grep FIFO```
...
/opt/salt 1050240 root  522r  FIFO   0,13      0t0 244257798 pipe
/opt/salt 1050240 root  523w  FIFO   0,13      0t0 244257795 pipe
/opt/salt 1050240 root  525w  FIFO   0,13      0t0 244257797 pipe
/opt/salt 1050240 root  527w  FIFO   0,13      0t0 244257799 pipe
...

```lsof -p $PID  | grep FIFO | wc -l``` # 1096 #for example
When counter FIFO over >1024 - python get error

```ulimit -n``` # 65536

```ulimit -p 16``` #bash: ulimit: pipe size: cannot modify limit: Invalid argument

```ulimit -a | grep pipe``` # pipe size                (512 bytes, -p) 8
This limit can`t increase  - **"increase a pipe's capacity will be denied"** [man](https://manpages.ubuntu.com/manpages/focal/en/man7/pipe.7.html)

**Look like similar issue without solution :**    [link](https://github.com/saltstack/salt/issues/63404)

If salt-ssh limit to single process, use options ```--max-procs=1```,  it finished main process job with over >500 objects, 
because the process manages to close the FIFO, before limit of PIPE buffer (1024)

**Comment by Stajl** [comment]
ping @s0undt3ch
