### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by madurani** [saltstack/salt#65875]
**Description**
Attempt to update win11 finish with error:

```
[root@tmv2007 ~]# salt 'tml1111*' win_wua.list drivers=True summary=True install=True 
tml1111.minion:
    The minion function caused an exception: Traceback (most recent call last):
      File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\minion.py", line 1982, in _thread_return
        return_data = minion_instance._execute_job_function(
      File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\minion.py", line 1941, in _execute_job_function
        return_data = self.executors[fname](opts, data, func, args, kwargs)
      File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\loader\lazy.py", line 159, in __call__
        ret = self.loader.run(run_func, *args, **kwargs)
      File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\loader\lazy.py", line 1245, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\loader\lazy.py", line 1260, in _run_as
        return _func_or_method(*args, **kwargs)
      File "C:\Program Files\Salt Project\Salt\Lib\site-packages\salt\executors\direct_call.py", line 10, in execute
        return func(*args, **kwargs)
      File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\loader\lazy.py", line 159, in __call__
        ret = self.loader.run(run_func, *args, **kwargs)
      File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\loader\lazy.py", line 1245, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\loader\lazy.py", line 1260, in _run_as
        return _func_or_method(*args, **kwargs)
      File "C:\Program Files\Salt Project\Salt\Lib\site-packages\salt\modules\win_wua.py", line 541, in list
        ret["Download"] = wua.download(updates)
      File "C:\Program Files\Salt Project\Salt\lib\site-packages\salt\utils\win_update.py", line 691, in download
        ret["Updates"][uid]["AlreadyDownloaded"] = bool(update.IsDownloaded)
      File "C:\Program Files\Salt Project\Salt\lib\site-packages\win32com\client\dynamic.py", line 628, in __getattr__
        ret = self._oleobj_.Invoke(retEntry.dispid, 0, invoke_type, 1)
    pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147024809), None)
ERROR: Minions returned with non-zero exit code
[root@tmv2007 ~]# 
```

```
[root@tmv2007 ~]# salt --versions-report
Salt Version:
          Salt: 3006.5
 
Python Version:
        Python: 3.10.13 (main, Nov 15 2023, 04:34:27) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.10
     gitpython: 3.1.32
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.14.2
         smmap: 5.0.0
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: oracle 8.9 n/a
        locale: utf-8
       machine: x86_64
       release: 4.18.0-513.11.0.1.el8_9.x86_64
        system: Linux
       version: Oracle Linux Server 8.9 n/a
```

**Comment by madurani** [comment]
When I disable option **drivers=True** then command work properly:
```
[root@tmv2007 ~]# salt 'tml1111*' win_wua.list summary=True install=True 
tml1111.minion:
    ----------
    Download:
        ----------
        Success:
            False
        Updates:
            Nothing to download
    Install:
        ----------
        Success:
            False
        Updates:
            Nothing to install
[root@tmv2007 ~]# 

```
