### ISSUE TITLE
[BUG] pkgrepo.managed - IndexError: list index out of range

### ISSUE THREAD

**Issue by colttt** [saltstack/salt#66195]
**Description**
it looks like that the pkgrepo.managed is damaged since 3007

**Setup**
sls-file:
```
bareos_repo_pw:
  file.managed:
    - name: /etc/apt/auth.conf.d/download_bareos_com.conf
    - user: root
    - group: root
    - mode: 600
    - template: jinja
    - source: salt://linux/bareos/files/download_bareos_com.conf

bareos-repos:
  pkgrepo.managed:
    - name: deb [signed-by=/etc/apt/keyrings/Release.key] https://download.bareos.com/bareos/release/22/Debian_{{ grains['osrelease'] }}
    - file: /etc/apt/sources.list.d/bareos.list
    - key_url: https://download.bareos.com/bareos/release/22/Debian_{{ grains['osrelease'] }}/Release.key
    - aptkey: false
    - require:
      - file: bareos_repo_pw
      - pkg: apt-transport-https

# install bareos-client
bareos-fd:
  pkg.latest:
    - refresh: true
```

got the following error:
```
2024-03-11 12:14:44,691 [salt.state       :325 ][ERROR   ][80253] An exception occurred in this state: Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/state.py", line 2430, in call
    ret = self.states[cdata["full"]](
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 160, in __call__
    ret = self.loader.run(run_func, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1233, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1248, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1281, in wrapper
    return f(*args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/states/pkgrepo.py", line 463, in managed
    pre = __salt__["pkg.get_repo"](repo=repo, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 160, in __call__
    ret = self.loader.run(run_func, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1233, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1248, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/modules/aptpkg.py", line 2004, in get_repo
    repo_entry = _split_repo_str(repo)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/modules/aptpkg.py", line 1773, in _split_repo_str
    entry = SourceEntry(repo)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/modules/aptpkg.py", line 189, in __init__
    self._parse_sources(line)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/modules/aptpkg.py", line 251, in _parse_sources
    self.dist = repo_line[2]
IndexError: list index out of range

2024-03-11 12:14:48,882 [salt.loaded.int.states.pkg:2764][ERROR   ][80253] No information found for 'bareos-fd'.
2024-03-11 12:14:48,882 [salt.state       :325 ][ERROR   ][80253] No information found for 'bareos-fd'.
```

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [x] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [x] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
use the above sls-file

**Expected behavior**
a working pkg-repo managed

**Versions Report**
<details><summary>salt --versions-report</summary>
Server is 3006.7 and Client 3007
client:
```yaml
salt-minion --versions-report
Salt Version:
          Salt: 3007.0
 
Python Version:
        Python: 3.10.13 (main, Feb 19 2024, 03:31:20) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.16.0
      cherrypy: 18.8.0
      dateutil: 2.8.2
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.3
       libgit2: Not Installed
  looseversion: 1.3.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.7
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 23.1
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: Not Installed
  python-gnupg: 0.5.2
        PyYAML: 6.0.1
         PyZMQ: 25.1.2
        relenv: 0.15.1
         smmap: Not Installed
       timelib: 0.3.0
       Tornado: 6.3.3
           ZMQ: 4.3.4
 
Salt Package Information:
  Package Type: onedir
 
System Versions:
          dist: debian 12.5 bookworm
        locale: utf-8
       machine: x86_64
       release: 6.1.0-18-amd64
        system: Linux
       version: Debian GNU/Linux 12.5 bookworm

```
server:
```yaml
salt --versions-report
Salt Version:
          Salt: 3006.7
 
Python Version:
        Python: 3.10.13 (main, Feb 19 2024, 03:31:20) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.10
     gitpython: 3.1.31
        Jinja2: 3.1.3
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.15.1
         smmap: 5.0.0
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 12 bookworm
        locale: utf-8
       machine: x86_64
       release: 6.1.0-18-amd64
        system: Linux
       version: Debian GNU/Linux 12 bookworm
```
</details>

**Additional context**

Edit also happens with 3007 master

**Comment by whytewolf** [comment]
it failed because that is not a valid oneline deb format. 

a valid oneline format has to have a valid distro. see `man sources.list`

**Comment by colttt** [comment]
you're right, I forgott the '/' at the end
