### ISSUE TITLE
[BUG] Salt 3007.0 Microsoft Visual C++ 2015

### ISSUE THREAD

**Issue by cdtylejenk** [saltstack/salt#66258]
**Description**
When attempting to run salt-call on 3007.0, the following error is returned:

```C:\Users\azureuser>salt-call test.ping
Traceback (most recent call last):
  File "C:\Program Files\Salt Project\Salt\Lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Salt Project\Salt\Lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Salt Project\Salt\salt-call.exe\__main__.py", line 7, in <module>
  File "C:\Program Files\Salt Project\Salt\Lib\site-packages\salt\scripts.py", line 437, in salt_call
    import salt.cli.call
  File "C:\Program Files\Salt Project\Salt\Lib\site-packages\salt\cli\call.py", line 3, in <module>
    import salt.cli.caller
  File "C:\Program Files\Salt Project\Salt\Lib\site-packages\salt\cli\caller.py", line 12, in <module>
    import salt.channel.client
  File "C:\Program Files\Salt Project\Salt\Lib\site-packages\salt\channel\client.py", line 14, in <module>
    import salt.crypt
  File "C:\Program Files\Salt Project\Salt\Lib\site-packages\salt\crypt.py", line 32, in <module>
    import salt.utils.event
  File "C:\Program Files\Salt Project\Salt\Lib\site-packages\salt\utils\event.py", line 68, in <module>
    import salt.config
  File "C:\Program Files\Salt Project\Salt\Lib\site-packages\salt\config\__init__.py", line 18, in <module>
    import salt.syspaths
  File "C:\Program Files\Salt Project\Salt\Lib\site-packages\salt\syspaths.py", line 129, in <module>
    ROOT_DIR = _get_windows_root_dir()
  File "C:\Program Files\Salt Project\Salt\Lib\site-packages\salt\syspaths.py", line 100, in _get_windows_root_dir
    root_dir = salt.utils.win_reg.read_value(
  File "C:\Program Files\Salt Project\Salt\Lib\site-packages\salt\utils\win_reg.py", line 536, in read_value
    registry = Registry()
  File "C:\Program Files\Salt Project\Salt\Lib\site-packages\salt\utils\win_reg.py", line 102, in __init__
    "HKEY_CURRENT_CONFIG": win32con.HKEY_CURRENT_CONFIG,
NameError: name 'win32con' is not defined

```

win_reg.py is trying to import a few different win32 libraries:

```
try:
    import win32api
    import win32con
    import win32gui

    HAS_WINDOWS_MODULES = True
except ImportError:
    HAS_WINDOWS_MODULES = False
```

If I import these individually, I see the culprits are actually win32api & win32gui:

```
>>> import win32con
>>> import win32api
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed while importing win32api: The specified module could not be found.
>>> import win32gui
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed while importing win32gui: The specified module could not be found.
```

I see that pythoncom310.dll & pywintypes310.dll refer to the following dependencies: 

```
pythoncom310.dll    
   OLEAUT32.dll
    ole32.dll
    USER32.dll
    python310.dll
    pywintypes310.dll
    KERNEL32.dll
    VCRUNTIME140_1.dll
    VCRUNTIME140.dll
    api-ms-win-crt-stdio-l1-1-0.dll
    api-ms-win-crt-string-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-utility-l1-1-0.dll
    api-ms-win-crt-runtime-l1-1-0.dll

pywintypes310.dll	
    ADVAPI32.dll
    USER32.dll
    ole32.dll
    OLEAUT32.dll
    python310.dll
    KERNEL32.dll
    VCRUNTIME140_1.dll
    VCRUNTIME140.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-stdio-l1-1-0.dll
    api-ms-win-crt-time-l1-1-0.dll
    api-ms-win-crt-string-l1-1-0.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-math-l1-1-0.dll
```

Looks like api-ms-win-crt-* refer to the 2015 redistributable. If I install the latest redistributable here, then salt-call works fine: 
https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

During the setup process, I see that the salt executable found here:
https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/windows.html#install-windows

Is still trying to install 2013:
![2013](https://github.com/saltstack/salt/assets/155474747/42454319-48aa-4acf-8b56-0d9166053317)

**Setup**
- [X] VM (Virtualbox, KVM, etc. please specify)

- Microsoft Windows 11 Enterprise running in Azure.
- Salt version 3007.0. 
- Python 3.10.13 (C:\Program Files\Salt Project\Salt\Scripts\python)

Installing Salt via the exe here:
https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/windows.html#install-windows

**Steps to Reproduce the behavior**

- Install salt via the windows executable https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/windows.html#install-windows
- Attempt to run salt-call test.ping

**Expected behavior**
Expecting Salt 3007.0 to install Microsoft Visual C++ 2015 instead of 2013 during the setup process. 

**Screenshots**
![winreg](https://github.com/saltstack/salt/assets/155474747/65bf35c9-fa05-4ac9-991a-726375a3d692)

**Versions Report**
salt-call --versions-report also returns the win_reg.py error message.

**Comment by hbonath** [comment]
Just jumping in here to confirm this affects Windows Server 2019 (And likely all other versions of windows)

**Comment by dwoz** [comment]
Fixed by #67784 (merged 2025-03-05 into 3007.x). The Windows installer now installs Visual C++ Redistributable 2022 on all supported branches (3006.x, 3007.x, 3008.x, master). Closing.
