### ISSUE TITLE
[BUG] 3007 master 4505 publish  port failed to respond  to salt commands unless restart 

### ISSUE THREAD

**Issue by tjyang** [saltstack/salt#66282]
**Description**

3007 master not responding salt commands unless restarting the master. But it does answer salt-call ran from minion
The timeout issue does not have log in /var/log/salt/master file with  log file level set to debug.
Currently trying the trace level.
```
log_level_logfile: trace
```

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [ x] on-prem machine
- [ x] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ x] onedir packaging
- [ x] used bootstrap to install

**Steps to Reproduce the behavior**
$sudo salt minion-on-saltmaster test.ping

**Expected behavior**
salt-master should answer the test.ping command quickly. In stead,it timeout.

**Screenshots**
- cmd line
```
[me@salt01 ~]$ sudo salt salt01  test.ping
salt01:
    Minion did not return. [No response]
    The minions may not have all finished running and any remaining minions will return upon completion. To look up the return data for this job later, run the following command:

    salt-run jobs.lookup_jid 20240328074306181473


-------------------------------------------
Summary
-------------------------------------------
# of minions targeted: 1
# of minions returned: 0
# of minions that did not return: 1
# of minions with errors: 0
-------------------------------------------
ERROR: Minions returned with non-zero exit code
[me@salt01 ~]$

```
- and this is trace log in /etc/salt/master when a minion not responding.

```
2024-03-28 02:36:29,940 [salt.loader.lazy ][DEBUG   ] The functions from module 'no_return' are being loaded by dir() on the loaded module
2024-03-28 02:36:29,940 [salt.utils.lazy  ][DEBUG   ] LazyLoaded no_return.output
2024-03-28 02:36:29,941 [salt.output      ][TRACE   ] data = {'salt01': 'Minion did not return. [No response]\nThe minions may not have all finished running and any remaining minions will return upon completion. 
To look up the return data for this job later, run the following command:\n\nsalt-run jobs.lookup_jid 20240328073609814061'}
```
- salt-master status
```
Mar 27 13:09:15 salt01 salt-master[2162920]: [ERROR   ] Publish server binding pub to /var/run/salt/master/master_event_pub.ipc ssl=None
Mar 27 14:00:04 salt01 salt-master[2163029]: [ERROR   ] Requested method not exposed: _ext_nodes
Mar 27 15:00:04 isalt01 salt-master[2163274]: [ERROR   ] Requested method not exposed: _ext_nodes
<snipped>
Mar 28 03:00:04 salt01 salt-master[2163147]: [ERROR   ] Requested method not exposed: _ext_nodes
Mar 28 04:00:07 salt01 salt-master[2163282]: [ERROR   ] Requested method not exposed: _ext_nodes

```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3007.0

Python Version:
        Python: 3.10.13 (main, Feb 19 2024, 03:31:20) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.16.0
      cherrypy: unknown
      dateutil: 2.8.2
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.3
       libgit2: Not Installed
  looseversion: 1.3.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.7
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 23.1
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: Not Installed
  python-gnupg: 0.5.2
        PyYAML: 6.0.1
         PyZMQ: 25.1.2
        relenv: 0.15.1
         smmap: Not Installed
       timelib: 0.3.0
       Tornado: 6.3.3
           ZMQ: 4.3.4

Salt Package Information:
  Package Type: onedir

System Versions:
          dist: rocky 8.9 Green Obsidian
        locale: utf-8
       machine: x86_64
       release: 4.18.0-513.18.1.el8_9.x86_64
        system: Linux
       version: Rocky Linux 8.9 Green Obsidian
```
</details>

**Additional context**

**Comment by tjyang** [comment]
@KiyoIchikawa, do you still have this issue ?

**Comment by tjyang** [comment]
PS: running salt-call from minion to pull formula is ok. It is master can't reach minion.

**Comment by tjyang** [comment]
<details><summary>/var/log/salt/master log with trace level enabled:  after running sudo salt salt01 test.ping  command it just time out on itsef , the master</summary>

```

2024-03-28 08:33:40,794 [salt.utils.event ][TRACE   ] _get_event() waited 0 seconds and received nothing
2024-03-28 08:33:40,804 [salt.utils.event ][TRACE   ] Get event. tag: (salt/job|syndic/.*)/20240328133320851221
2024-03-28 08:33:40,805 [salt.utils.event ][TRACE   ] _get_event() waited 0 seconds and received nothing
2024-03-28 08:33:40,805 [salt.utils.event ][TRACE   ] Get event. tag: salt/job/20240328133325868511
2024-03-28 08:33:40,806 [salt.utils.event ][TRACE   ] _get_event() waited 0 seconds and received nothing
2024-03-28 08:33:40,816 [salt.utils.event ][TRACE   ] Get event. tag: (salt/job|syndic/.*)/20240328133320851221
2024-03-28 08:33:40,817 [salt.utils.event ][TRACE   ] _get_event() waited 0 seconds and received nothing
2024-03-28 08:33:40,817 [salt.utils.event ][TRACE   ] Get event. tag: salt/job/20240328133325868511
2024-03-28 08:33:40,817 [salt.utils.event ][TRACE   ] _get_event() waited 0 seconds and received nothing
2024-03-28 08:33:40,827 [salt.utils.event ][TRACE   ] Get event. tag: (salt/job|syndic/.*)/20240328133320851221
2024-03-28 08:33:40,828 [salt.utils.event ][TRACE   ] _get_event() waited 0 seconds and received nothing
2024-03-28 08:33:40,828 [salt.utils.event ][TRACE   ] Get event. tag: salt/job/20240328133325868511
2024-03-28 08:33:40,829 [salt.utils.event ][TRACE   ] _get_event() waited 0 seconds and received nothing
2024-03-28 08:33:40,839 [salt.utils.event ][TRACE   ] Get event. tag: (salt/job|syndic/.*)/20240328133320851221
2024-03-28 08:33:40,840 [salt.utils.event ][TRACE   ] _get_event() waited 0 seconds and received nothing
2024-03-28 08:33:40,840 [salt.utils.event ][TRACE   ] Get event. tag: salt/job/20240328133325868511
2024-03-28 08:33:40,840 [salt.utils.event ][TRACE   ] _get_event() waited 0 seconds and received nothing
2024-03-28 08:33:40,851 [salt.utils.event ][TRACE   ] Get event. tag: (salt/job|syndic/.*)/20240328133320851221
2024-03-28 08:33:40,851 [salt.utils.event ][TRACE   ] _get_event() waited 0 seconds and received nothing
2024-03-28 08:33:40,852 [salt.utils.event ][TRACE   ] Get event. tag: salt/job/20240328133325868511
2024-03-28 08:33:40,852 [salt.utils.event ][TRACE   ] _get_event() waited 0 seconds and received nothing
2024-03-28 08:33:40,862 [salt.utils.event ][TRACE   ] Get event. tag: (salt/job|syndic/.*)/20240328133320851221
2024-03-28 08:33:40,863 [salt.utils.event ][TRACE   ] _get_event() waited 0 seconds and received nothing
2024-03-28 08:33:40,863 [salt.utils.event ][TRACE   ] Get event. tag: salt/job/20240328133325868511
2024-03-28 08:33:40,864 [salt.utils.event ][TRACE   ] _get_event() waited 0 seconds and received nothing
2024-03-28 08:33:40,874 [salt.utils.event ][TRACE   ] Get event. tag: (salt/job|syndic/.*)/20240328133320851221
2024-03-28 08:33:40,875 [salt.utils.event ][TRACE   ] _get_event() waited 0 seconds and received nothing
2024-03-28 08:33:40,875 [salt.utils.event ][TRACE   ] Get event. tag: salt/job/20240328133325868511
2024-03-28 08:33:40,875 [salt.utils.event ][TRACE   ] _get_event() waited 0 seconds and received nothing
2024-03-28 08:33:40,885 [salt.utils.event ][TRACE   ] Get event. tag: (salt/job|syndic/.*)/20240328133320851221
2024-03-28 08:33:40,886 [salt.utils.event ][TRACE   ] _get_event() waited 0 seconds and received nothing
2024-03-28 08:33:40,886 [salt.utils.event ][TRACE   ] Get event. tag: salt/job/20240328133325868511
2024-03-28 08:33:40,886 [salt.utils.event ][TRACE   ] _get_event() waited 0 seconds and received nothing
2024-03-28 08:33:40,887 [salt.client      ][DEBUG   ] return event: {'salt01': {'failed': True}}
2024-03-28 08:33:40,892 [salt.loader.lazy ][DEBUG   ] The functions from module 'localfs' are being loaded by dir() on the loaded module
2024-03-28 08:33:40,893 [salt.utils.lazy  ][DEBUG   ] LazyLoaded localfs.init_kwargs
2024-03-28 08:33:40,980 [salt.loader.lazy ][DEBUG   ] The functions from module 'localfs' are being loaded by dir() on the loaded module
2024-03-28 08:33:40,980 [salt.utils.lazy  ][DEBUG   ] LazyLoaded localfs.init_kwargs
2024-03-28 08:33:40,982 [salt.loader.lazy ][DEBUG   ] The functions from module 'no_return' are being loaded by dir() on the loaded module
2024-03-28 08:33:40,982 [salt.utils.lazy  ][DEBUG   ] LazyLoaded no_return.output
2024-03-28 08:33:40,982 [salt.output      ][TRACE   ] data = {'salt01': 'Minion did not return. [No response]\nThe minions may not have all finished running and any remaining minions will return upon completion. To look up the return data for this job later, run the following command:\n\nsalt-run jobs.lookup_jid 20240328133320851221'}
2024-03-28 08:33:40,982 [salt.transport.tcp][DEBUG   ] tcp stream to  closed, unable to recv
2024-03-28 08:33:41,973 [salt.utils.process][TRACE   ] Process manager iteration
2024-03-28 08:33:43,754 [salt.utils.process][TRACE   ] Process manager iteration
2024-03-28 08:33:51,983 [salt.utils.process][TRACE   ] Process manager iteration
2024-03-28 08:33:53,765 [salt.utils.process][TRACE   ] Process manager iteration


```
</details>

**Comment by KiyoIchikawa** [comment]
We tested on Windows minions and Linux minions. The Windows minions seem to be working better, but they both seem to be getting the following error(s) while applying a `state.test`.

Linux Minion (OEL 8)
```
2024-03-28 13:32:25,967 [salt.utils.extmods:155 ][ERROR   ][1375064] Failed to sync modules module: File client timed out after 60 seconds
```

Windows (Windows Server 2016 Datacenter)
```
2024-03-28 12:50:34,269 [salt.loaded.int.beacons.adb:23  ][ERROR   ][14288] Unable to load adb beacon: adb is missing.
2024-03-28 12:50:34,285 [salt.loaded.int.beacons.aix_account:23  ][ERROR   ][14288] Unable to load aix_account beacon: Only available on AIX systems.
2024-03-28 12:50:34,332 [salt.loaded.int.beacons.avahi_announce:62  ][ERROR   ][14288] Unable to load avahi_announce beacon: The 'python-avahi' dependency is missing.
2024-03-28 12:50:34,347 [salt.loaded.int.beacons.bonjour_announce:31  ][ERROR   ][14288] Unable to load bonjour_announce beacon: pybonjour library is missing.
2024-03-28 12:50:34,347 [salt.loaded.int.beacons.btmp:134 ][ERROR   ][14288] Unable to load btmp beacon: /var/log/btmp does not exist.
2024-03-28 12:50:34,519 [salt.loaded.int.beacons.glxinfo:23  ][ERROR   ][14288] Unable to load glxinfo beacon: glxinfo is missing.
2024-03-28 12:50:37,862 [salt.loaded.int.beacons.haproxy:24  ][ERROR   ][14288] Unable to load haproxy beacon: haproxy.get_sessions is missing.
2024-03-28 12:50:37,877 [salt.loaded.int.beacons.inotify:48  ][ERROR   ][14288] Unable to load inotify beacon: pyinotify library is missing.
2024-03-28 12:50:37,904 [salt.loaded.int.beacons.journald:26  ][ERROR   ][14288] Unable to load journald beacon: systemd library is missing.
2024-03-28 12:50:37,921 [salt.loaded.int.beacons.load:20  ][ERROR   ][14288] Unable to load load beacon: Not available for Windows systems.
2024-03-28 12:50:37,931 [salt.loaded.int.beacons.log_beacon:37  ][ERROR   ][14288] Unable to load log beacon: Not available for Windows systems or when regex library is missing.
2024-03-28 12:50:38,016 [salt.loaded.int.beacons.network_settings:86  ][ERROR   ][14288] Unable to load network_settings beacon: pyroute2 library is missing
2024-03-28 12:50:38,079 [salt.loaded.int.beacons.sensehat:26  ][ERROR   ][14288] Unable to load sensehat beacon: sensehat.get_pressure is missing.
2024-03-28 12:50:38,094 [salt.loaded.int.beacons.sh:24  ][ERROR   ][14288] Unable to load sh beacon: strace is missing.
2024-03-28 12:50:38,141 [salt.loaded.int.beacons.smartos_imgadm:42  ][ERROR   ][14288] Unable to load imgadm beacon: Only available on SmartOS compute nodes.
2024-03-28 12:50:38,173 [salt.loaded.int.beacons.smartos_vmadm:42  ][ERROR   ][14288] Unable to load vmadm beacon: Only available on SmartOS compute nodes.
2024-03-28 12:50:38,204 [salt.loaded.int.beacons.telegram_bot_msg:30  ][ERROR   ][14288] Unable to load telegram_bot_msg beacon: telegram library is missing.
2024-03-28 12:50:38,235 [salt.loaded.int.beacons.twilio_txt_msg:31  ][ERROR   ][14288] Unable to load twilio_txt_msg beacon: twilio library is missing.
2024-03-28 12:50:38,235 [salt.loaded.int.beacons.watchdog:77  ][ERROR   ][14288] Unable to load watchdog beacon: watchdog library is missing.
2024-03-28 12:50:38,251 [salt.loaded.int.beacons.wtmp:163 ][ERROR   ][14288] Unable to load wtmp beacon: /var/log/wtmp does not exist.
2024-03-28 12:51:37,367 [salt.utils.extmods:155 ][ERROR   ][19124] Failed to sync states module: File client timed out after 60 seconds
2024-03-28 12:53:55,975 [salt.utils.extmods:155 ][ERROR   ][19124] Failed to sync output module: message authentication failed
2024-03-28 12:55:05,277 [salt.utils.extmods:155 ][ERROR   ][19124] Failed to sync proxy module: File client timed out after 60 seconds
2024-03-28 12:56:14,469 [salt.utils.extmods:155 ][ERROR   ][19124] Failed to sync serializers module: File client timed out after 60 seconds
```

The Linux minion keeps getting timeouts, I have not increased the log-level on the master yet.

**Comment by tjyang** [comment]
@KiyoIchikawa , thanks for the update. When salt-master needed restart, it can't even issue command itself(sudo salt saltmaster01 test.ping" . And yet "saltmaster01$sudo salt-call test.ping" works.

**Comment by tjyang** [comment]
- I was looking at wrong place, the error message is log at minion side in /var/log/salt/minion.
when "sudo salt salt01 test.ping" ran, the salt01 minion client has following error
```
2024-03-28 12:50:50,314 [salt.transport.zeromq:396 ][ERROR   ][1544] Exception while running callback
Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/transport/zeromq.py", line 394, in consume
    await callback(msg)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/channel/client.py", line 484, in wrap_callback
    await callback(decoded)
TypeError: object NoneType can't be used in 'await' expression

```

**Comment by tjyang** [comment]
I collect more info when salt command can't be sent out.

- port 4505 failed the simple ncat port check.
```
[me@salt01 ~]$ date ;nc  -zv  salt01 4505;nc  -zv  salt01 4506
Fri Apr  5 11:09:23 CDT 2024
Ncat: Version 7.92 ( https://nmap.org/ncat )
Ncat: TIMEOUT.
Ncat: Version 7.92 ( https://nmap.org/ncat )
Ncat: Connected to 100.65.184.160:4506.
Ncat: 0 bytes sent, 0 bytes received in 0.02 seconds.
[me@salt01 ~]$
```
- result of  **netstat -antulp |egrep 4505** salt01 salt-master
```
# ip address masked
tcp     1001      0 0.0.0.0:4505            0.0.0.0:*               LISTEN      2443253/salt-master
tcp        0      0 1.6.1.0:4505     1.4.43.33:40224      ESTABLISHED 2443253/salt-master
tcp        0      0 1.6.1.0:4505     1.4.116.28:38806     ESTABLISHED 2443253/salt-master
<snipped>
tcp       11      0 1.6.1.0:4505     1.4.81.5:60514       CLOSE_WAIT  -
tcp       11      0 1.6.1.0:4505     1.4.81.5:40492       CLOSE_WAIT  -
tcp        0      0 1.6.1.0:4505     1.4.44.3:52474       ESTABLISHED 2443253/salt-master
tcp        0      0 1.6.1.0:4505     1.5.176.67:43538     ESTABLISHED 2443253/salt-master
tcp       11      0 1.6.1.0:4505     1.4.81.5:49436       CLOSE_WAIT  -
tcp        0      0 1.6.1.0:4505     1.4.226.19:36712     ESTABLISHED 2443253/salt-master
tcp        0      0 1.6.1.0:4505     1.5.178.42:35596     ESTABLISHED 2443253/salt-master
tcp        0      0 1.6.1.0:4505     1.4.11.76:48254      ESTABLISHED 2443253/salt-master
tcp        0      0 1.6.1.0:4505     1.4.29.8:40660       ESTABLISHED 2443253/salt-master

```

**Comment by compi-tom** [comment]
Small comment, we're facing the exact same issue since upgrading from 3006.7. 
At some point the master stops working and cannot send anything to the minions.

Restarting it doesn't fix anything as it cannot bind to its port:
`[salt.transport.tcp:1405][ERROR   ][1609] Publish server binding pub to /var/run/salt/master/master_event_pub.ipc ssl=None`

**Comment by tjyang** [comment]
@compi-tom, 
- I was in you current state running on RockyLinux 8 for past few weeks. For now I would suggest restart salt-master when zeromq pub 4505 resourced depleted or put a cronjob to restart daily. 
- I was on a VMWare VM with luxury of taking snapshots for rolling back. 
- I tried many things and ended up with an instance that can't even send out test.ping from salt-master to itself after a fresh reboot.
- In the end, I had to clone another running 3007.0( a two node multi-masters setup)  that is more stable that only has this issue occasionally.

**Comment by compi-tom** [comment]
We're already running a 3 nodes multi-masters. 
Restarting the master service doesn't solve the issue as it cannot bind to the 4505 port ==> reboot.

I'm considering downgrading to 3006.7

**Comment by tjyang** [comment]
I think I tried downgrade to 3006.7 once and it didn't help this issue so I decided use 3007.0 again. if downloading to older version approach is adopted the minion need to be downgraded to also. 
Interesting thing is that good 3007 salt-master(one that got cloned) now has same port 4505 malfunction issue.  a salt-master stop/start bring up the port 4505. 
They are many setting in /etc/salt/master config file. it is time for me to  study and understand the meaning zeromq settings.

**Comment by tjyang** [comment]
I am following this PR: https://github.com/saltstack/salt/pull/66335

**Comment by tjyang** [comment]
- 1.6% of 16G, this is the time port 4505 failed.
```
[me@salt01 srv]$ egrep '286129|MEM' salt-2024-04-24-06\:56.txt
    PID  STARTED     TIME %MEM   RSS    SZ    VSZ  SIZE
 286129 01:00:02 00:00:01  1.6 273528 185245 740980 273156
286129 /opt/saltstack/salt/bin/python3.10 /usr/bin/salt-master EventPublisher
[me@salt01 srv]$
```
- so bad that even port 4505 not responding to port poking by ncat.
```
[me@salt01 srv]$ nc -zv ilclsalt01 4505
Ncat: Version 7.92 ( https://nmap.org/ncat )
Ncat: TIMEOUT.
[me@salt01 srv]$
```

**Comment by tjyang** [comment]
- This is my effort using makefile to automate the tracking of EventPublish memory usage when it stop working
```
[me@salt01 srv]$ egrep 'DATEH|memory|pgrep' Makefile
DATEH           = $(shell date +"%Y-%m-%d-%R")
memory:
        ps  -o pid,start,time,%mem,rss,sz,vsz,size --sort -rss -p $$(pgrep -f salt-master) | head > salt-$(DATEH).txt
        pgrep -af salt-master |grep -v grep >> salt-$(DATEH).txt
[me@salt01 srv]$
```
- sample of memory usage on a 16G setting when EventPublisher stopped working
```
[me@salt01 srv]$ egrep '1\.6|MEM' salt-2024-04-25-06\:35.txt
    PID  STARTED     TIME %MEM   RSS    SZ    VSZ  SIZE
 896442 01:00:02 00:00:01  1.6 263128 182305 729220 261396  /opt/saltstack/salt/bin/python3.10 /usr/bin/salt-master EventPublisher
[me@salt01 srv]$

```

**Comment by tjyang** [comment]
my 2nd salt-master failed to test.ping itself, restart salt-master doesn't work anymore.
 I had to reboot the RL8 OS. this definitely  smell like  kernel network resource depletion. 
- OS restart log below.
```
[me@salt02 ~]$ sudo salt salt02  test.ping
salt02:
    True


-------------------------------------------
Summary
-------------------------------------------
# of minions targeted: 1
# of minions returned: 1
# of minions that did not return: 0
# of minions with errors: 0
-------------------------------------------
[me@salt02 ~]$ uptime
 06:11:19 up 4 min,  2 users,  load average: 0.66, 0.29, 0.12
[me@salt02 ~]$

```

**Comment by tjyang** [comment]
After downgrade from 3007 to 3006.8 version, my salt-master servers, the 4505 port is now stable and able to send out salt commands.

**Comment by compi-tom** [comment]
> After downgrade from 3007 to 3006.8 version, my salt-master servers, the 4505 port is now stable and able to send out salt commands.

I've done the same as this error was preventing our app to automatically add VMs to cope with the load.
No issues since downgrading.

**Comment by tjyang** [comment]
@compi-tom, Thanks for the confirmation.  Hopeful when 3007 turned into LTS from STS. This issue can be acked by core team  and resolved.

**Comment by amalaguti** [comment]
Any update on this issue ? I had two servers that were working as multimasters nodes thru multiple 3006 versions, just upgraded to 3007.1 and I get this problem in one of the servers only 

```
[DEBUG   ] PubClient connecting to <salt.transport.tcp.PublishClient object at 0x7f721b129130> '/local/data/saltwin/salt-master/3007.1/var/run/salt/master/master_event_pub.ipc'
[DEBUG   ] PubClient conencted to <salt.transport.tcp.PublishClient object at 0x7f721b129130> '/local/data/saltwin/salt-master/3007.1/var/run/salt/master/master_event_pub.ipc'
[DEBUG   ] Subscriber at  connected
[DEBUG   ] tcp stream to  closed, unable to recv
```

**Comment by JonasKrausch** [comment]
We also had to downgrade our master to 3006.8 to resolve this issue. 
3007.0 and 3007.1 did not work and we had to restart salt-master multiple times every day.

No logs are written with Loglevel WARNING. Master just refuses to connect to any minion (even itself). Salt-Call works without issues.

**Comment by gotsmth** [comment]
Hello,

Today i made update from latest 3005 to 3007.1 and i got a lot of messages in master log file:
`2024-08-25 10:10:10,192 [salt.transport.tcp:1082][DEBUG   ][81648] tcp stream to  closed, unable to recv

2024-08-25 10:10:10,192 [salt.transport.tcp:1102][DEBUG   ][81648] Subscriber at  connected

2024-08-25 10:10:10,193 [salt.transport.tcp:1082][DEBUG   ][81648] tcp stream to  closed, unable to recv

2024-08-25 10:10:10,193 [salt.transport.tcp:1102][DEBUG   ][81648] Subscriber at  connected

2024-08-25 10:10:15,199 [salt.transport.tcp:1082][DEBUG   ][81648] tcp stream to  closed, unable to recv

2024-08-25 10:10:15,199 [salt.transport.tcp:1102][DEBUG   ][81648] Subscriber at  connected

2024-08-25 10:10:15,200 [salt.transport.tcp:1082][DEBUG   ][81648] tcp stream to  closed, unable to recv

2024-08-25 10:10:15,201 [salt.transport.tcp:1102][DEBUG   ][81648] Subscriber at  connected
`

It seems 3007.1 is not stable and we cannot use it because communication with minions does not work (we have about 2500 minions connected to the master)
After rollback to latest 3006 all works okay.

Just for information that problem still exists.

Any fix around?

**Comment by afletch** [comment]
See also #66288 and potentially #66715
There are real issues on 3007+ with minion communications and very little in terms of response to all these.

**Comment by tjyang** [comment]
https://github.com/saltstack/salt/issues/65265

**Comment by rjel2159** [comment]
> Hello,
> 
> Today i made update from latest 3005 to 3007.1 and i got a lot of messages in master log file: `2024-08-25 10:10:10,192 [salt.transport.tcp:1082][DEBUG ][81648] tcp stream to closed, unable to recv
> 
> 2024-08-25 10:10:10,192 [salt.transport.tcp:1102][DEBUG ][81648] Subscriber at connected
> 
> 2024-08-25 10:10:10,193 [salt.transport.tcp:1082][DEBUG ][81648] tcp stream to closed, unable to recv
> 
> 2024-08-25 10:10:10,193 [salt.transport.tcp:1102][DEBUG ][81648] Subscriber at connected
> 
> 2024-08-25 10:10:15,199 [salt.transport.tcp:1082][DEBUG ][81648] tcp stream to closed, unable to recv
> 
> 2024-08-25 10:10:15,199 [salt.transport.tcp:1102][DEBUG ][81648] Subscriber at connected
> 
> 2024-08-25 10:10:15,200 [salt.transport.tcp:1082][DEBUG ][81648] tcp stream to closed, unable to recv
> 
> 2024-08-25 10:10:15,201 [salt.transport.tcp:1102][DEBUG ][81648] Subscriber at connected `
> 
> It seems 3007.1 is not stable and we cannot use it because communication with minions does not work (we have about 2500 minions connected to the master) After rollback to latest 3006 all works okay.
> 
> Just for information that problem still exists.
> 
> Any fix around?




> We also had to downgrade our master to 3006.8 to resolve this issue. 3007.0 and 3007.1 did not work and we had to restart salt-master multiple times every day.
> 
> No logs are written with Loglevel WARNING. Master just refuses to connect to any minion (even itself). Salt-Call works without issues.

Same here, we've had to downgrade a while back from 3007.0 to 3005.x and are still waiting for this bug to be fix before moving forward.
