### ISSUE TITLE
[BUG] Python renderer fails with attribute error when run under salt-ssh

### ISSUE THREAD

**Issue by nzlosh** [saltstack/salt#66376]
**Description**
Python renderer fails with attribute error when run under `salt-ssh` but functions correctly when run with `salt`/`salt-call` on 3007.0, 3006.7 and 3006.4.

**Setup**

Virtual machines running Debian with salt installed from salt package repository.

Please be as specific as possible and give set-up details.

- [x] on-prem machine
- [x] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [x] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**

1. Place `cp_fail.sls` in root of fileserver.
```
#!py

def run():
    __salt__.cp.get_file_str("salt://cp_fail.sls", saltenv="base")
    return {}
```
2. run `salt-call state.apply cp_fail test=true`
3. run `salt-ssh <host> state.apply cp_fail test=true`

**Expected behavior**
`salt-call` and `salt-ssh` render the same state without error.

**Screenshots**
**Example of salt-call**
```
# salt-call state.apply cp_fail test=true
local:

Summary for local
-----------
Succeeded: 0
Failed:   0
-----------
Total states run:    0
Total run time:  0.000 ms
```
**Example of salt-ssh**
```
# salt-ssh --priv=/root/.ssh/saltmaster_id_rsa host1.*******.*** state.apply cp_fail test=true
[INFO    ] Fetching file from saltenv 'base', ** done ** 'cp_fail.sls'
[CRITICAL] Rendering SLS 'base:cp_fail' failed: Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/templates.py", line 690, in py
    data = mod.run()
  File "/var/tmp/.root_caa0bf_salt/running_data/var/cache/salt/minion/files/base/cp_fail.sls", line 4, in run
    __salt__.cp.get_file_str("salt://cp_fail.sls", saltenv="base")
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/context.py", line 123, in __getattr__
    return getattr(self.value(), name)
AttributeError: 'FunctionWrapper' object has no attribute 'cp'

host1.*******.***:
    - Rendering SLS 'base:cp_fail' failed: Traceback (most recent call last):
        File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/templates.py", line 690, in py
          data = mod.run()
        File "/var/tmp/.root_caa0bf_salt/running_data/var/cache/salt/minion/files/base/cp_fail.sls", line 4, in run
          __salt__.cp.get_file_str("salt://cp_fail.sls", saltenv="base")
        File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/context.py", line 123, in __getattr__
          return getattr(self.value(), name)
      AttributeError: 'FunctionWrapper' object has no attribute 'cp'
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
# salt --versions-report
Salt Version:
          Salt: 3007.0
 
Python Version:
        Python: 3.10.13 (main, Feb 19 2024, 03:31:20) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.16.0
      cherrypy: unknown
      dateutil: 2.8.2
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.3
       libgit2: Not Installed
  looseversion: 1.3.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.7
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 23.1
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: Not Installed
  python-gnupg: 0.5.2
        PyYAML: 6.0.1
         PyZMQ: 25.1.2
        relenv: 0.15.1
         smmap: Not Installed
       timelib: 0.3.0
       Tornado: 6.3.3
           ZMQ: 4.3.4
 
Salt Package Information:
  Package Type: onedir
 
System Versions:
          dist: debian 11.9 bullseye
        locale: utf-8
       machine: x86_64
       release: 5.10.0-28-amd64
        system: Linux
       version: Debian GNU/Linux 11.9 bullseye

```
</details>

**Additional context**
n/a

**Comment by nzlosh** [comment]
The triage process failed. Is something I need to correct in created issue?
```
 Loaded Issue: Issue(title="[BUG] Python renderer fails with attribute error when run under salt-ssh", number=66376)
404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/teams/teams#get-a-team-by-name"}
Error: Process completed with exit code 1.
```

**Comment by OrangeDog** [comment]
Use `__salt__["cp.get_file_str"](...)`.

**Comment by nzlosh** [comment]
Thank you, this syntax has resolved the initial python exception.  I can confirm that using the simple test case, works with `salt-call` and `salt-ssh`.

This has now exposed a caching issue when running `state.highstate` via `salt-ssh` with a more complex python state (the state that initially used `__salt__.cp` that lead me to raise the issue).

The master is configured with multiple environments, but `base` is defined as follows:
```
file_roots:
  base:
    - /srv/salt/files
```
The base path contains the following files:
```
# ls /srv/salt/files/data/global/auth
groups.yaml  patterns.yaml  profile_prod.yaml  profile_rescue.yaml  service_accounts.yaml  user_accounts.json
```
The cache directory of the `salt-ssh` execution is missing numerous files:
```
ls /var/tmp/.root_caa0bf_salt/running_data/var/cache/salt/minion/files/base/data/global/auth/
groups.yaml  user_accounts.json
```
`groups.yaml` and `user_accounts.json` are referenced in sls files which are part of the highstate, however the files used by the python state, are not cached.

I've tried forcing the download of the missing files with `__salt__["cp.cache_file"](filename, saltenv=saltenv)` and `__salt__["cp.get_file"](filename, None, saltenv=saltenv, makedirs=True)`, but despite these calls, `__salt__["cp.get_file_str"](filename, saltenv=saltenv)` returns `False` because the file isn't not found in the cache.

Are there known issues with salt-ssh file caching or am I misusing this functionality?

**Comment by OrangeDog** [comment]
You need to add them to `--extra-filerefs`

**Comment by nzlosh** [comment]
Thank you once again!  I was unable to get `cp.cache_file` to cache the file when run under `salt-ssh`.  Here are the steps to reproduce the test I performed.

1. place `cp_fail.sls` in root of fileserver
```
#!py

import os

def run():
    # cache the file
    location = __salt__["cp.cache_file"]("salt://cp_fail.data", saltenv="base")
    file_cached = str(os.path.exists(location))
    # read contents of cached file.
    cp_fail_contents = __salt__["cp.get_file_str"]("salt://cp_fail.data", saltenv="base")

    return  {
        "cp_fail_contents": {
            "file.managed": [
                {"name": "/tmp/cp_fail_contents"},
                {"contents": "\n".join([location, str(cp_fail_contents), f"file in cache? {file_cached}"])}
            ]
        }
    }
```

2. place `cp_fail.data` in root of fileserver
```
hello world
```

3. run state apply with salt (success)
```
salt host1.******.*** state.apply cp_fail test=true
host1.******.***:
    ----------
    file_|-cp_fail_contents_|-/tmp/cp_fail_contents_|-managed:
        ----------
        __id__:
            cp_fail_contents
        __run_num__:
            0
        __sls__:
            cp_fail
        changes:
            ----------
            diff:
                --- 
                +++ 
                @@ -0,0 +1,4 @@
                +/var/cache/salt/minion/files/base/cp_fail.data
                +hello world
                +
                +file in cache? True
        comment:
            The file /tmp/cp_fail_contents is set to be changed
            Note: No changes made, actual changes may
            be different due to other states.
        duration:
            7.891
        name:
            /tmp/cp_fail_contents
        result:
            None
        start_time:
            21:36:14.247041

```

4. run state apply with salt-ssh (failure)
```
host1.******.***:
    ----------
    file_|-cp_fail_contents_|-/tmp/cp_fail_contents_|-managed:
        ----------
        __id__:
            cp_fail_contents
        __run_num__:
            0
        __sls__:
            cp_fail
        changes:
            ----------
            diff:
                --- 
                +++ 
                @@ -0,0 +1,3 @@
                +/var/tmp/.root_caa0bf_salt/running_data/var/cache/salt/minion/files/base/cp_fail.data
                +False
                +file in cache? False
        comment:
            The file /tmp/cp_fail_contents is set to be changed
            Note: No changes made, actual changes may
            be different due to other states.
        duration:
            6.584
        name:
            /tmp/cp_fail_contents
        result:
            None
        start_time:
            21:37:00.138754
```

**Comment by nzlosh** [comment]
In the mean time I'll try using `--extra-filerefs` as a workaround to the caching problem.

**Comment by lkubb** [comment]
Salt-SSH employs several crutches, one of them is that the template rendering -> highstate -> lowstate rendering happens on the master. It collects `salt://` file references from this lowstate and sends them along in an archive.

`cp.cache_file` did not work for sending files along in releases <3007, but should work from 3007 onwards. Another workaround that works in <3007 is to use the `file.cached` state.

The initial issue is caused by the `FunctionWrapper` not having a `__getattr__` defined like the usual `NamedLoaderContext`. I would assume it works in Jinja because it implements dict lookups as attributes itself. As pointed out before, I would advise to always use the `__salt__["mod.func"]` syntax because that's the most reliable.

**Comment by nzlosh** [comment]
To clarify, the 2nd set of tests with `cp.cache_file` were running using 3007.0.

**Comment by lkubb** [comment]
That's because `cp.cache_file` returns the path on the minion, while you're checking if the file exists on the master because it's during template rendering. If you used `__salt__["file.file_exists"](location)`, you would check on the minion. You can convert the file to the master cache using `cp.convert_cache_path` (this is a function specific to the wrapper module).
