### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by eg-ayoub** [saltstack/salt#66414]
**Description**
When using salt 3007 as a masterless minion it is impossible to generate a certificate when using a `signing_policy` with `x509_v2` states.

**Setup**
Applied this setup https://docs.saltproject.io/en/master/ref/states/all/salt.states.x509_v2.html on a masterless node running salt 3007 on Rocky Linux 8.  (copied x509.conf, www.sls, top.sls and ca.sls)
Removed `ca_server` argument from the `www` sls so it becomes 
```
Ensure PKI directory exists:
  file.directory:
    - name: /etc/pki

Create private key for the certificate:
  x509.private_key_managed:
    - name: /etc/pki/www.key
    - keysize: 4096
    - backup: true
    - require:
      - file: /etc/pki

Request certificate:
  x509.certificate_managed:
    - name: /etc/pki/www.crt
    - signing_policy: www
    - private_key: /etc/pki/www.key
    - CN: www.example.com
    - days_remaining: 7
    - backup: true
    - require:
      - x509: /etc/pki/www.key
```
salt onedir 3007 from yum package
docker container

**Steps to Reproduce the behavior**
run `salt-call --local` state.apply

**Expected behavior**
The certificate is managed on consecutive runs

**Actual behavior**
The state fails with the following error message if it is run more than once:
```
[root@a8da82304b0f /]# salt-call --local state.apply www
/opt/saltstack/salt/lib/python3.10/site-packages/salt/states/x509_v2.py:391: DeprecationWarning: The default value for `days_valid` will change to 30. Please adapt your code accordingly.
  salt.utils.versions.warn_until(
/opt/saltstack/salt/lib/python3.10/site-packages/salt/states/x509_v2.py:491: CryptographyDeprecationWarning: Properties that return a naïve datetime object have been deprecated. Please switch to not_valid_after_utc.
  current.not_valid_after
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/state.py", line 2430, in call
    ret = self.states[cdata["full"]](
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 160, in __call__
    ret = self.loader.run(run_func, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1233, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1248, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1281, in wrapper
    return f(*args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/states/x509_v2.py", line 507, in certificate_managed
    ) = _build_cert(
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/states/x509_v2.py", line 1604, in _build_cert
    builder, _, private_key_loaded, signing_cert = x509util.build_crt(
TypeError: build_crt() got multiple values for argument 'signing_private_key'
....
Summary for local
------------
Succeeded: 3
Failed:    1
------------
Total states run:     4
Total run time: 369.614 ms
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3007.0
 
Python Version:
        Python: 3.10.13 (main, Feb 19 2024, 03:31:20) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.16.0
      cherrypy: unknown
      dateutil: 2.8.2
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.3
       libgit2: Not Installed
  looseversion: 1.3.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.7
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 23.1
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: Not Installed
  python-gnupg: 0.5.2
        PyYAML: 6.0.1
         PyZMQ: 25.1.2
        relenv: 0.15.1
         smmap: Not Installed
       timelib: 0.3.0
       Tornado: 6.3.3
           ZMQ: 4.3.4
 
Salt Package Information:
  Package Type: onedir
 
System Versions:
          dist: rocky 8.9 Green Obsidian
        locale: utf-8
       machine: x86_64
       release: 6.6.27
        system: Linux
       version: Rocky Linux 8.9 Green Obsidian
```
</details>

**Additional context**

**Comment by lkubb** [comment]
Yup, can confirm this is an issue in all released versions of `x509_v2`. Fix coming in soon.

A workaround until the fix is released would be to remove `signing_private_key` from the policy and define it in the state itself. When signing locally, policies mostly serve convenience only, so it wouldn't be a much of a security issue.
