### ISSUE TITLE
[BUG] Import error for Tornado package in Bootstrap Installation and can't run any salt command.

### ISSUE THREAD

**Issue by caner-cetin** [saltstack/salt#66505]
**Description**
```bash
./bootstrap-salt.sh: line 6862: /etc/rc.d/salt-master: No such file or directory
 *  INFO: Running daemons_running_onedir()
 * DEBUG: Waiting 3 seconds for processes to settle before checking for them
 * ERROR: salt-master was not found running
 * ERROR: Failed to run daemons_running_onedir()!!!
nohup: ignoring input
Traceback (most recent call last):
  File "/usr/bin/salt-master", line 33, in <module>
    sys.exit(load_entry_point('salt==3007.0', 'console_scripts', 'salt-master')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/salt/scripts.py", line 79, in salt_master
    import salt.cli.daemons
  File "/usr/lib/python3.12/site-packages/salt/cli/daemons.py", line 14, in <module>
    from salt.utils.process import HAS_PSUTIL
  File "/usr/lib/python3.12/site-packages/salt/utils/process.py", line 23, in <module>
    from tornado import gen
ModuleNotFoundError: No module named 'tornado'
[ERROR   ] An un-handled exception was caught by Salt's global exception handler:
ModuleNotFoundError: No module named 'tornado'
Traceback (most recent call last):
  File "/usr/bin/salt-master", line 33, in <module>
    sys.exit(load_entry_point('salt==3007.0', 'console_scripts', 'salt-master')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/salt/scripts.py", line 79, in salt_master
    import salt.cli.daemons
  File "/usr/lib/python3.12/site-packages/salt/cli/daemons.py", line 14, in <module>
    from salt.utils.process import HAS_PSUTIL
  File "/usr/lib/python3.12/site-packages/salt/utils/process.py", line 23, in <module>
    from tornado import gen
ModuleNotFoundError: No module named 'tornado'
```

**Setup**
- [X] used bootstrap to install

![image](https://github.com/saltstack/salt/assets/92731060/79a44ab5-d84d-419f-adfb-5b2e07c75386)

**Steps to Reproduce the behavior**
```bash
curl -o bootstrap-salt.sh -L https://bootstrap.saltproject.io
sudo bash ./bootstrap-salt.sh -M -N -D
```

there is no problem if I install with

```bash
curl -o bootstrap-salt.sh -L https://bootstrap.saltproject.io
sudo sh bootstrap-salt.sh -M -N git master
```

**Versions Report**
<details><summary>salt --versions-report</summary>

```bash
[caner@archlinux ~]$ salt --versions-report
Traceback (most recent call last):
  File "/usr/bin/salt", line 33, in <module>
    sys.exit(load_entry_point('salt==3007.0', 'console_scripts', 'salt')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/salt/scripts.py", line 526, in salt_main
    import salt.cli.salt
  File "/usr/lib/python3.12/site-packages/salt/cli/salt.py", line 9, in <module>
    import salt.utils.parsers
  File "/usr/lib/python3.12/site-packages/salt/utils/parsers.py", line 34, in <module>
    import salt.utils.process
  File "/usr/lib/python3.12/site-packages/salt/utils/process.py", line 23, in <module>
    from tornado import gen
ModuleNotFoundError: No module named 'tornado'
```

</details>

**Additional context**

I cannot install a global package in Arch, at least not in a way I currently know.

```bash
[caner@archlinux ~]$ pipx install tornado

No apps associated with package tornado or its dependencies. If you are attempting to install a library, pipx should not be used. Consider using pip or a similar tool instead.
[caner@archlinux ~]$ pip install tornado
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try 'pacman -S
    python-xyz', where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Arch-packaged Python package,
    create a virtual environment using 'python -m venv path/to/venv'.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip.
    
    If you wish to install a non-Arch packaged Python application,
    it may be easiest to use 'pipx install xyz', which will manage a
    virtual environment for you. Make sure you have python-pipx
    installed via pacman.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```

_Latest Tornado package for Arch is python2-tornado, https://aur.archlinux.org/packages/python2-tornado, which, you know, it is for Python 2._

This issue occurs on every single command in Salt.

```bash
[caner@archlinux ~]$ salt --help
Traceback (most recent call last):
  File "/usr/bin/salt", line 33, in <module>
    sys.exit(load_entry_point('salt==3007.0', 'console_scripts', 'salt')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/salt/scripts.py", line 526, in salt_main
    import salt.cli.salt
  File "/usr/lib/python3.12/site-packages/salt/cli/salt.py", line 9, in <module>
    import salt.utils.parsers
  File "/usr/lib/python3.12/site-packages/salt/utils/parsers.py", line 34, in <module>
    import salt.utils.process
  File "/usr/lib/python3.12/site-packages/salt/utils/process.py", line 23, in <module>
    from tornado import gen
ModuleNotFoundError: No module named 'tornado'
```

thanks for any help.

**Comment by caner-cetin** [comment]
also see => https://github.com/saltstack/salt/issues/55555 maybe related

**Comment by omgroves** [comment]
Ran into this today on a clean `salt` install on Arch. Fixed by installing [python-tornado](https://archlinux.org/packages/extra/x86_64/python-tornado/) package from Extra manually

**Comment by caner-cetin** [comment]
boop, closing it then. havent worked with saltstack since eternity, so i am fully trusting you on this

**Comment by dmurphy18** [comment]
@caner-cetin FYI bootstrap repo https://github.com/saltstack/salt-bootstrap is a better place to log bootstrap issues.
