### ISSUE TITLE
[BUG] Linux acl state doesn't work with "X" permission

### ISSUE THREAD

**Issue by mikafouenski** [saltstack/salt#66693]
**Description**
The linux acl state doesn't work with the `X` permission flag.

> The X (uppercase x) option allows to conditionally set the execute permission of files and directories.
When used:
    If the target is a directory, then it sets the execute permission for the owner, the group, and the others, allowing them to list and enter the directory.
    If the target is a regular file, then it doesn’t set the execute permission, unless it is already enabled on at least one of the owner, the group, or the others.
This option is particularly useful when you want to recursively change the permission of a directory and its subdirectories, without affecting the regular files themselves.

**Setup**
Saltversion: v3007.1

**Problematic state**
Reproduce this command: `sudo setfacl -R -m u:testuser:rX /tmp/test`

```yaml
acl_test:
  acl.present:
    - name: /tmp/test
    - acl_type: user
    - acl_name: testuser
    - perms: "rX"
    - recurse: True
```
Using this result in:
```
          ID: acl_test
    Function: acl.present
        Name: /tmp/test
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/var/tmp/.it_5410e1_salt/pyall/salt/state.py", line 2430, in call
                  ret = self.states[cdata["full"]](
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
                File "/var/tmp/.it_5410e1_salt/pyall/salt/loader/lazy.py", line 160, in __call__
                  ret = self.loader.run(run_func, *args, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                File "/var/tmp/.it_5410e1_salt/pyall/salt/loader/lazy.py", line 1233, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                File "/var/tmp/.it_5410e1_salt/pyall/salt/loader/lazy.py", line 1248, in _run_as
                  return _func_or_method(*args, **kwargs)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                File "/var/tmp/.it_5410e1_salt/pyall/salt/loader/lazy.py", line 1281, in wrapper
                  return f(*args, **kwargs)
                         ^^^^^^^^^^^^^^^^^^
                File "/var/tmp/.it_5410e1_salt/pyall/salt/states/linux_acl.py", line 177, in present
                  octal_sum = sum(_octal.get(i, i) for i in perms)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              TypeError: unsupported operand type(s) for +: 'int' and 'str'
     Started: 10:19:19.360495
    Duration: 2.356 ms
     Changes:   
```

**Expected result should be:**
```shell
$ sudo getfacl /tmp/test
# file: tmp/test
# owner: root
# group: root
user::rwx
user:testuser:r-x
group::r-x
mask::r-x
other::r-x
```

**Comment by dwoz** [comment]
Closing as duplicate.
