### ISSUE TITLE
[BUG] nacl.keygen issues with generating key files

### ISSUE THREAD

**Issue by hurzhurz** [saltstack/salt#66772]
1. When giving a path for the private key where the file does not yet exist, it causes an exception instead of generating both keys:
```bash
# ls /tmp/test-key
ls: cannot access '/tmp/test-key': No such file or directory

# salt-call --local nacl.keygen /tmp/test-key
[ERROR   ] An un-handled exception was caught by Salt's global exception handler:
AttributeError: type object 'PublicKey' has no attribute 'generate'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    sys.exit(salt_call())
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/scripts.py", line 443, in salt_call
    client.run()
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/cli/call.py", line 50, in run
    caller.run()
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/cli/caller.py", line 95, in run
    ret = self.call()
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/cli/caller.py", line 202, in call
    ret["return"] = self.minion.executors[fname](
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 159, in __call__
    ret = self.loader.run(run_func, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1245, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1260, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/executors/direct_call.py", line 10, in execute
    return func(*args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 159, in __call__
    ret = self.loader.run(run_func, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1245, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1260, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/modules/nacl.py", line 185, in keygen
    return salt.utils.nacl.keygen(sk_file, pk_file, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/nacl.py", line 192, in keygen
    kp = nacl.public.PublicKey.generate()
AttributeError: type object 'PublicKey' has no attribute 'generate'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    sys.exit(salt_call())
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/scripts.py", line 443, in salt_call
    client.run()
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/cli/call.py", line 50, in run
    caller.run()
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/cli/caller.py", line 95, in run
    ret = self.call()
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/cli/caller.py", line 202, in call
    ret["return"] = self.minion.executors[fname](
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 159, in __call__
    ret = self.loader.run(run_func, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1245, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1260, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/executors/direct_call.py", line 10, in execute
    return func(*args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 159, in __call__
    ret = self.loader.run(run_func, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1245, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1260, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/modules/nacl.py", line 185, in keygen
    return salt.utils.nacl.keygen(sk_file, pk_file, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/nacl.py", line 192, in keygen
    kp = nacl.public.PublicKey.generate()
AttributeError: type object 'PublicKey' has no attribute 'generate'
```

2. When the private key file already exists and it should generate the public key out of it, it just copies the private key into the public key file:

```bash
# echo -n 'mBxVG0CmuwJwofpDmPrsGR5nqSFpA5HZ3q6J8FAHtXc=' > /tmp/test-key
# salt-call --local nacl.keygen /tmp/test-key
local:
    saved pk_file: /tmp/test-key.pub
# cat /tmp/test-key.pub
mBxVG0CmuwJwofpDmPrsGR5nqSFpA5HZ3q6J8FAHtXc=
```

This issue propably exists since https://github.com/saltstack/salt/commit/4cc13e2a0c3ce4ee846cbbeac598761c5f274681 (Replace libnacl with PyNaCl).

A PR with a fix will follow shortly.

**Comment by hurzhurz** [comment]
this was fixed in `3006.10` / `3007.2`
