### ISSUE TITLE
[BUG] photon4: Unsupported algorithm: OAEP-SHA1

### ISSUE THREAD

**Issue by tjyang** [saltstack/salt#66781]
**Description**

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [x ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
install salt-minion using tdnf per  https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/photonos.html

```
root@vc43 [ ~ ]# salt-call --master=salt.test.net test.version
[ERROR   ] Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7f7ae991c310>, <salt.ext.tornado.concurrent.Future object at 0x7f7ae999e3b0>)
Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/crypt.py", line 259, in decrypt
    return self.key.decrypt(
cryptography.exceptions.UnsupportedAlgorithm: This combination of padding and hash algorithm is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/ext/tornado/ioloop.py", line 606, in _run_callback
    ret = callback()
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/ext/tornado/stack_context.py", line 278, in null_wrapper
    return fn(*args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/ext/tornado/ioloop.py", line 628, in _discard_future_result
    future.result()
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/ext/tornado/gen.py", line 1064, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/crypt.py", line 738, in _authenticate
    creds = yield self.sign_in(channel=channel)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/ext/tornado/gen.py", line 1070, in run
    yielded = self.gen.send(value)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/crypt.py", line 876, in sign_in
    ret = self.handle_signin_response(sign_in_payload, payload)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/crypt.py", line 899, in handle_signin_response
    auth["aes"] = self.verify_master(
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/crypt.py", line 1327, in verify_master
    return self.extract_aes(payload, master_pub=False)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/crypt.py", line 1249, in extract_aes
    aes, token = self.decrypt_aes(payload, master_pub)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/crypt.py", line 1087, in decrypt_aes
    key_str = key.decrypt(payload["aes"], self.opts["encryption_algorithm"])
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/crypt.py", line 268, in decrypt
    raise UnsupportedAlgorithm(f"Unsupported algorithm: {algorithm}")
salt.exceptions.UnsupportedAlgorithm: Unsupported algorithm: OAEP-SHA1
^C
Exiting gracefully on Ctrl-c
root@vc43 [ ~ ]# egrep '^hash_type|^rejected_retry' /etc/salt/minion
rejected_retry: True
hash_type: sha256
root@vc43 [ ~ ]#rpm -qa |grep salt
salt-3006.9-0.x86_64
salt-minion-3006.9-0.x86_64
root@vc43 [ ~ ]#

```

**Expected behavior**
salt-call master test.version should report back version 3006.9.

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3006.9

Python Version:
        Python: 3.10.14 (main, Jun 26 2024, 11:44:37) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
  cryptography: 42.0.5
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.4
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.17.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: photon 4.0 Photon
        locale: utf-8
       machine: x86_64
       release: 5.10.210-2.ph4
        system: Linux
       version: VMware Photon OS 4.0 Photon


```
</details>

**Additional context**

**Comment by tjyang** [comment]
@dmurphy18 , Thanks for quick reply. I will recheck my setup again with your testing.

**Comment by dmurphy18** [comment]
@tjyang Have an internal report with the same issue (suspect they are using old EOL versions of Salt), but also unable to reproduce the problem a salt-master (rocky Linux 9) Salt 3007.1 and salt-minion (Photon 4 docker container) 3006.9 and no problems seen.

**Comment by dmurphy18** [comment]
@tjyang From the internal discussions with user on Photon 4.0 have the following

wondering if they upgraded from openssl v1.x to openssl v3.x which drops SHA-1 and that is the cause of the problem.
Given it appeared as an update on the container I suspect so
From a fresh container of Photon 4
```
root [ / ]# tdnf list | grep openssl
openssl.x86_64                              3.0.14-2.ph4             @System
openssl.x86_64                              1.1.1i-2.ph4        photon-release
openssl-c_rehash.x86_64                     1.1.1i-2.ph4        photon-release
openssl-devel.x86_64                        1.1.1i-2.ph4        photon-release
openssl-docs.x86_64                         1.1.1i-2.ph4        photon-release
openssl-perl.x86_64                         1.1.1i-2.ph4        photon-release
openssl.x86_64                              3.0.14-3.ph4        photon-updates
openssl-c_rehash.x86_64                     3.0.14-3.ph4        photon-updates
openssl-devel.x86_64                        3.0.14-3.ph4        photon-updates
openssl-docs.x86_64                         3.0.14-3.ph4        photon-updates
openssl-fips-provider.x86_64                3.0.8-2.ph4         photon-updates
openssl-perl.x86_64                         3.0.14-3.ph4        photon-updates
root [ / ]#
```
photon -release was openssl v1.x, and System is now openssl v3.x, suspect things were using SHA-1 at the time and after update, SHA-1 is now MIA. 

Wondering if system was recently updated

**Comment by dwoz** [comment]
@tjyang Is fips enabled? That would explain why `OAEP-SHA1` is not supported. If fips is enabled you should modify your master and minion configs:
```
# master.conf
fips_mode: True
publish_signing_algorithm: PKCS1v15-SHA224
```

```
# minion.conf
fips_mode: True                                           
encryption_algorithm: OAEP-SHA224
signing_algorithm: PKCS1v15-SHA224

**Comment by tjyang** [comment]
@dwoz , your input fixed my problem. Yes, FIPS was enabled on this vcenter 8.0.0(not latest 8.0U3) instance.
@dmurphy18 , Thanks for your inputs also.  
I see now the bug reports are responded more quickly by core team members. 
Thank you all. 
Please resolve this issue.

**Comment by dmurphy18** [comment]
@tjyang Marking this closed since FIPS settings resolved the issue
