### ISSUE TITLE
[BUG] SELinux.fcontext_add_policy failes when using hyphen in filespec.

### ISSUE THREAD

**Issue by Munteano** [saltstack/salt#66854]
**Description**
When running the SELinux fcontext_add_policy with a filespec that contains a hyphen in the name of the directory, the state fails with
ValueError: File context for /vol/apache/dummy/bla-bla(/.*)? is not defined
While setting the fcontext with SEmanage directly works with hyphens.

**Setup**
Salt-master on Rocky-Linux to salt-minion on Amazon Linux 2023

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [x] VM running on a cloud service, please be explicit and add details
 Running on latest Amazon Linux 2023 Image
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [x] onedir packaging
- [x] used bootstrap to install

**Steps to Reproduce the behavior**
Running the selinux state like this:

```
salt 'amazon2023-dev-1' selinux.fcontext_add_policy '/vol/apache/dummy/bla-bla(/.*)?' sel_type=httpd_sys_content_t
amazon2023-dev-1:
    ----------
    pid:
        24222
    retcode:
        1
    stderr:
        ValueError: File context for /vol/apache/dummy/bla-bla(/.*)? is not defined
    stdout:
```
Running the fcontext_get_policy returns

```
salt 'amazon2023-dev-1' selinux.fcontext_get_policy "/vol/apache/dummy/bla-bla(/.*)?"
amazon2023-dev-1:
    The minion function caused an exception: Traceback (most recent call last):
      File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 1969, in _thread_return
        return_data = minion_instance._execute_job_function(
      File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 1925, in _execute_job_function
        return_data = self.executors[fname](opts, data, func, args, kwargs)
      File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 160, in __call__
        ret = self.loader.run(run_func, *args, **kwargs)
      File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1269, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1284, in _run_as
        return _func_or_method(*args, **kwargs)
      File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/executors/direct_call.py", line 10, in execute
        return func(*args, **kwargs)
      File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 160, in __call__
        ret = self.loader.run(run_func, *args, **kwargs)
      File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1269, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1284, in _run_as
        return _func_or_method(*args, **kwargs)
      File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/modules/selinux.py", line 507, in fcontext_get_policy
        "filespec": parts.group(1).strip(),
    AttributeError: 'NoneType' object has no attribute 'group'

```

While running it directly on VM with semanage

```
[root@amazon2023-dev-1 apache]# semanage fcontext -a -t httpd_sys_content_t '/vol/apache/dummy/bla-bla(/.*)?'
[root@amazon2023-dev-1 apache]# semanage fcontext -l | grep bla-bla
/vol/apache/dummy/bla-bla(/.*)?                    all files          system_u:object_r:httpd_sys_content_t:s0

```

**Expected behavior**
Running the same state without hyphen

```
salt 'amazon2023-dev-1' selinux.fcontext_add_policy '/vol/apache/dummy/blabla(/.*)?' sel_type=httpd_sys_content_t
amazon2023-dev-1:
    ----------
    pid:
        24209
    retcode:
        0
    stderr:
    stdout:

```

**Screenshots**
![image](https://github.com/user-attachments/assets/fbbccabf-93b3-4ca0-a7ec-fe2575b77fe7)

**Versions Report**
Minion: 
[root@amazon2023-dev-1 /]# salt-minion --version
salt-minion 3007.1 (Chlorine)

<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3007.1

Python Version:
        Python: 3.10.14 (main, Apr  3 2024, 21:30:09) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.16.0
      cherrypy: unknown
      dateutil: 2.8.2
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.4
       libgit2: Not Installed
  looseversion: 1.3.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.7
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 23.1
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: Not Installed
  python-gnupg: 0.5.2
        PyYAML: 6.0.1
         PyZMQ: 25.1.2
        relenv: 0.16.0
         smmap: Not Installed
       timelib: 0.3.0
       Tornado: 6.3.3
           ZMQ: 4.3.4

Salt Package Information:
  Package Type: onedir

System Versions:
          dist: rocky 8.10 Green Obsidian
        locale: utf-8
       machine: x86_64
       release: 4.18.0-553.8.1.el8_10.x86_64
        system: Linux
       version: Rocky Linux 8.10 Green Obsidian

```
</details>

**Additional context**
Running the same command on a minion with Amazon Linux 2 works fine.
My first contribution to the SaltStack community, please let me know if you need more info. Thanks!

**Comment by omolenkamp** [comment]
This is happening because Salt is running something like `semanage fcontext -l | grep -E '^/some/path\-name\(/\.\*\)\?[ ]+all files[ ]+[^:]+:[^:]+:etc_t:[^:]+[ |	]*$'`, `grep` outputs a warning about the unnecessary `\` before the `-`, and Salt tries to parse that warning as a fcontext. (which then obviously fails)

```sh
$ echo a-b | grep 'a\-b'
grep: warning: stray \ before -
a-b
```

Ideally, Salt should be using a correct POSIX ERE instead of a Python RE when using `grep -E`, but at the very least, it shouldn't be parsing stderr output.

**Comment by andreasdijkman** [comment]
This is a workaround for the SELinux-module on newer systems, to skip the STDERR-output:
```diff
--- selinux.py-orig     2026-03-26 16:45:30.170639443 +0100
+++ selinux.py  2026-03-26 16:50:00.598954032 +0100
@@ -494,6 +494,7 @@
         + "'^{filespec}{spacer}{filetype}{spacer}{sel_user}:{sel_role}:{sel_type}:{sel_level}{ospacer}$'".format(
             **cmd_kwargs
         )
+        + " 2> /dev/null"
     )
     current_entry_text = __salt__["cmd.shell"](cmd, ignore_retcode=True)
     if current_entry_text == "":
@@ -616,7 +617,7 @@
     if "add" == action:
         # need to use --modify if context for name file exists, otherwise ValueError
         filespec = re.escape(name)
-        cmd = f"semanage fcontext -l | grep -E '{filespec} '"
+        cmd = f"semanage fcontext -l | grep -E '{filespec} ' 2> /dev/null"
         current_entry_text = __salt__["cmd.shell"](cmd, ignore_retcode=True)
         if current_entry_text != "":
             action = "modify"
@@ -766,6 +767,7 @@
         + "'^{sel_type}{spacer}{protocol}{spacer}((.*)*)[ ]{port}($|,)'".format(
             **cmd_kwargs
         )
+        + " 2> /dev/null"
     )
     port_policy = __salt__["cmd.shell"](cmd, ignore_retcode=True)
     if port_policy == "":
```

This is only tested with ports and file context but on EL10, the state isn't failing any more.

**Comment by dopheideb** [comment]
IMHO, part of the problem is that SaltStack is trying to be smart in fcontext_get_policy(), by allowing a user to supply a regular filename (i.e. the user doesn't have to escape dots/periods).

This smartness comes with a drawback: escaping. SaltStack has to escape the filename so RE special characters like the dot is will not actually be special. SaltStack uses re.escape() for the escaping, but re.escape() also escapes the hyphen! That is by design ("Only characters that can have special meaning in a regular expression are escaped."), but the hyphen is only special inside square brackets, and those square brackters are properly escaped, so the hyphen is actual not special.

So re.escape() is IMHO not the correct way to escape strings, because of the hyphen issue.

I think there are only 2 ways to properly fixed the hyphen issue:
1. Do not try to be smart. I.e. if user supplies "/.suspended" then use that verbatim. (Yes, this means that /Xsuspended is also match. Full power and full responsibility to the user.)
2. Ditch re.escape() and use an improved homebrew version. (Manual escaping is usually discouraged, because getting it wrong is often easy.)

Since I cannot oversee the consequences of the first way, I tried to go the second way.

Diff of version 3008.2:
```diff
--- /opt/saltstack/salt/lib/python3.14/site-packages/salt/modules/selinux.py-orig	2026-07-01 02:00:00.000000000 +0200
+++ /opt/saltstack/salt/lib/python3.14/site-packages/salt/modules/selinux.py	2026-07-16 15:00:31.844891495 +0200
@@ -487,13 +487,28 @@
 
         salt '*' selinux.fcontext_get_policy my-policy
     """
+    def re_escape(pattern: str) -> str:
+        """
+        Escape special characters in a string.
+        """
+        # The same as 
+        # https://github.com/python/cpython/blob/main/Lib/re/__init__.py, 
+        # but the hypen is not escaped (as it is not special outside 
+        # square brackets).
+        _special_chars_map = {i: '\\' + chr(i) for i in b'()[]{}?*+|^$\\.&~# \t\n\r\v\f'}
+        if isinstance(pattern, str):
+            return pattern.translate(_special_chars_map)
+        else:
+            pattern = str(pattern, 'latin1')
+            return pattern.translate(_special_chars_map).encode('latin1')
+
     se_file_type = SeFileType.from_code(filetype) if filetype else None
     re_spacer = "[ ]+"
-    re_optional_spacer = "[ |\t]*"
+    re_optional_spacer = "[ \t]*"
     cmd_kwargs = {
         "spacer": re_spacer,
         "ospacer": re_optional_spacer,
-        "filespec": re.escape(name),
+        "filespec": re_escape(re_escape(name)),
         "sel_user": sel_user or "[^:]+",
         "sel_role": "[^:]+",  # se_role for file context is always object_r
         "sel_type": sel_type or "[^:]+",
@@ -502,26 +517,21 @@
             "[[:alpha:] ]+" if se_file_type is None else se_file_type.description
         ),
     }
-    cmd = (
-        "semanage fcontext --list | grep -E "
-        + "'^{filespec}{spacer}{filetype}{spacer}{sel_user}:{sel_role}:{sel_type}:{sel_level}{ospacer}$'".format(
-            **cmd_kwargs
-        )
+    policy_re = r'^({filespec}){spacer}({filetype}){spacer}({sel_user}:{sel_role}:{sel_type}:{sel_level}{ospacer})$'.format(
+        **cmd_kwargs
     )
-    current_entry_text = __salt__["cmd.shell"](cmd, ignore_retcode=True)
-    if not current_entry_text:
-        return None
+    pattern = re.compile(policy_re)
+    cmd = ("semanage fcontext --list")
+    all_output = __salt__["cmd.run"](cmd, ignore_retcode=False)
+    for line in all_output.splitlines():
+        if parts := pattern.match(line):
+            ret = {
+                "filespec": parts.group(1).strip(),
+                "filetype": parts.group(2).strip(),
+            }
+            ret.update(_context_string_to_dict(parts.group(3).strip()))
+            return ret
 
-    if parts := re.match(
-        r"^({filespec}) +([a-z ]+) (.*)$".format(**{"filespec": re.escape(name)}),
-        current_entry_text,
-    ):
-        ret = {
-            "filespec": parts.group(1).strip(),
-            "filetype": parts.group(2).strip(),
-        }
-        ret.update(_context_string_to_dict(parts.group(3).strip()))
-        return ret
     raise CommandExecutionError(
         "Output from the fcontext command did not match the expected format"
     )
```

The above patch matches the "semanage fcontext --list" output lines only once (it doesn't use the grep anymore, thereby avoiding all kinds of pitfalls, like RE systems, grep giving warnings).

(It also fixes a bug with re_optional_spacer: the bar/pipe symbol is not a whitespace character.)

**Comment by dopheideb** [comment]
I got the thing about SaltStack being smart, wrong; SaltStack isn't trying to be smart (which is a good thing here IMHO).

However, I think that matching twice is wrong, especially when using to different matching tools (grep -E and Python). So my attempt may be a good start for someone else.

**Comment by dopheideb** [comment]
I think I got it right this time, see testcase at then end.

Note that re.escape() should be safe to use here, since we use the result in a re.compile(); both are from the same library.

Diff of version 3008.2:
```diff
--- /opt/saltstack/salt/lib/python3.14/site-packages/salt/modules/selinux.py-orig	2026-07-01 02:00:00.000000000 +0200
+++ /opt/saltstack/salt/lib/python3.14/site-packages/salt/modules/selinux.py	2026-07-16 20:16:58.866360281 +0200
@@ -489,7 +489,7 @@
     """
     se_file_type = SeFileType.from_code(filetype) if filetype else None
     re_spacer = "[ ]+"
-    re_optional_spacer = "[ |\t]*"
+    re_optional_spacer = "[ \t]*"
     cmd_kwargs = {
         "spacer": re_spacer,
         "ospacer": re_optional_spacer,
@@ -499,32 +499,26 @@
         "sel_type": sel_type or "[^:]+",
         "sel_level": sel_level or "[^:]+",
         "filetype": (
-            "[[:alpha:] ]+" if se_file_type is None else se_file_type.description
+            "[A-Za-z ]+" if se_file_type is None else se_file_type.description
         ),
     }
-    cmd = (
-        "semanage fcontext --list | grep -E "
-        + "'^{filespec}{spacer}{filetype}{spacer}{sel_user}:{sel_role}:{sel_type}:{sel_level}{ospacer}$'".format(
-            **cmd_kwargs
-        )
+    policy_re = r'^({filespec}){spacer}({filetype}){spacer}({sel_user}:{sel_role}:{sel_type}:{sel_level}{ospacer})$'.format(
+        **cmd_kwargs
     )
-    current_entry_text = __salt__["cmd.shell"](cmd, ignore_retcode=True)
-    if not current_entry_text:
-        return None
+    pattern = re.compile(policy_re)
+    cmd = ("semanage fcontext --list")
+    all_output = __salt__["cmd.run"](cmd, ignore_retcode=False)
+    for line in all_output.splitlines():
+        if parts := pattern.match(line):
+            ret = {
+                "filespec": parts.group(1).strip(),
+                "filetype": parts.group(2).strip(),
+            }
+            ret.update(_context_string_to_dict(parts.group(3).strip()))
+            return ret
 
-    if parts := re.match(
-        r"^({filespec}) +([a-z ]+) (.*)$".format(**{"filespec": re.escape(name)}),
-        current_entry_text,
-    ):
-        ret = {
-            "filespec": parts.group(1).strip(),
-            "filetype": parts.group(2).strip(),
-        }
-        ret.update(_context_string_to_dict(parts.group(3).strip()))
-        return ret
-    raise CommandExecutionError(
-        "Output from the fcontext command did not match the expected format"
-    )
+    # No exact match found.
+    return None
 
 
 def fcontext_add_policy(
```

Note that Python's re library doesn't support character classes like `[:alpha]`, so `[[:alpha:] ]` isn't valid.

(It also fixes a bug with re_optional_spacer: the bar/pipe symbol is not a whitespace character.)



Without patch, on an RHEL 10 box with SaltStack 3008.2:
```
[root@server ~]# salt-call --local selinux.fcontext_get_policy name='/usr/lib/wine/.+-windows/.+\.(exe|dll|acm|drv|sys)'
Error running 'selinux.fcontext_get_policy': Output from the fcontext command did not match the expected format
[root@server ~]# 
```

With patch, on an RHEL 10 box with SaltStack 3008.2:
```
[root@server ~]# salt-call --local selinux.fcontext_get_policy name='/usr/lib/wine/.+-windows/.+\.(exe|dll|acm|drv|sys)' 
local:
    ----------
    filespec:
        /usr/lib/wine/.+-windows/.+\.(exe|dll|acm|drv|sys)
    filetype:
        regular file
    sel_level:
        s0
    sel_role:
        object_r
    sel_type:
        textrel_shlib_t
    sel_user:
        system_u
[root@server ~]# 
```
