### ISSUE TITLE
[BUG]Exception getting pillar  TypeError: string indices must be integers

### ISSUE THREAD

**Issue by rimskij** [saltstack/salt#66872]
[DEBUG   ] Closing AsyncReqChannel instance
[ERROR   ] Exception getting pillar:
Traceback (most recent call last):
  File "salt/pillar/__init__.py", line 262, in compile_pillar
    ret_pillar = yield self.channel.crypted_transfer_decode_dictentry(
  File "salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "salt/ext/tornado/gen.py", line 1070, in run
    yielded = self.gen.send(value)
  File "salt/channel/client.py", line 187, in crypted_transfer_decode_dictentry
    aes = cipher.decrypt(ret["key"])
TypeError: string indices must be integers
[ERROR   ] Pillar data could not be refreshed. One or more masters may be down!

**Comment by dwoz** [comment]
Fix merged and shipped in a supported release. Closing per bulk triage. Reopen if this reproduces on a currently supported release (3006.x, 3007.x, 3008.x, master).
