### ISSUE TITLE
[BUG] cryptography module not installed on 3006.9

### ISSUE THREAD

**Issue by amalaguti** [saltstack/salt#66883]
**Description**
Recently ran a Salt 3006.9 pip installation on RHEL7.9 running python 3.8.
`python3 -m pip install salt==3006.9`
When starting salt-master I got the error message below, which is fixed by installing the cryptography module now in use by salt/crypt.py
`python3 -m pip install cryptography`

```
[saltwinqa@saltmaster-pip 3006.9]$ salt-master
[ERROR   ] An un-handled exception was caught by Salt's global exception handler:
NameError: name 'rsa' is not defined
Traceback (most recent call last):
  File "/local/data/saltwin/salt-master/3006.9/bin/salt-master", line 8, in <module>
    sys.exit(salt_master())
  File "/local/data/saltwin/salt-master/3006.9/lib/python3.8/site-packages/salt/scripts.py", line 86, in salt_master
    master.start()
  File "/local/data/saltwin/salt-master/3006.9/lib/python3.8/site-packages/salt/cli/daemons.py", line 199, in start
    super().start()
  File "/local/data/saltwin/salt-master/3006.9/lib/python3.8/site-packages/salt/utils/parsers.py", line 1053, in start
    self.prepare()
  File "/local/data/saltwin/salt-master/3006.9/lib/python3.8/site-packages/salt/cli/daemons.py", line 183, in prepare
    self.master = salt.master.Master(self.config)
  File "/local/data/saltwin/salt-master/3006.9/lib/python3.8/site-packages/salt/master.py", line 548, in __init__
    SMaster.__init__(self, opts)
  File "/local/data/saltwin/salt-master/3006.9/lib/python3.8/site-packages/salt/master.py", line 99, in __init__
    self.master_key = salt.crypt.MasterKeys(self.opts)
  File "/local/data/saltwin/salt-master/3006.9/lib/python3.8/site-packages/salt/crypt.py", line 451, in __init__
    self.key = self.__get_keys(passphrase=key_pass)
  File "/local/data/saltwin/salt-master/3006.9/lib/python3.8/site-packages/salt/crypt.py", line 516, in __get_keys
    gen_keys(
  File "/local/data/saltwin/salt-master/3006.9/lib/python3.8/site-packages/salt/crypt.py", line 147, in gen_keys
    gen = rsa.generate_private_key(e, keysize)
NameError: name 'rsa' is not defined
```

**Setup**
pip install of salt 3006.9
rhel 7.9
python 3.8

- [X ] VM running on a cloud service, please be explicit and add details

**Comment by dmurphy18** [comment]
Closing this since don't support RHEL 7 any more, Salt only supports Python 3.10 built into onedir architecture and not Python 3.8, and the correct method to install from PyPi for onedir architecture is to use ```salt-pip```, well documented.
```salt-pip install crypotography```

Using Salt with other version of Python, your mileage may vary, with best effort.

Sorry to be so blunt, but the Salt Core Team is very reduced.

**Comment by amalaguti** [comment]
Thanks David, I understand and makes sense.  I was doing a bit out of standard installation on some old containers. Will tweak to adapt to latest procedures

**Comment by lkubb** [comment]
@dmurphy18 Can this be reopened please? It's an issue whenever `salt==3006.9` is installed on Linux via `pip` (regardless of Python version).

Since `cryptography` is a hard dependency now (outside of salt-ssh), it should be added to https://github.com/saltstack/salt/blob/3006.x/requirements/base.txt. This was missed in https://github.com/saltstack/salt/pull/66589. It's in https://github.com/saltstack/salt/blob/3007.x/requirements/base.txt and https://github.com/saltstack/salt/blob/master/requirements/base.txt though.

This also breaks the Salt extension (integration) test suite on Linux (e.g. https://github.com/salt-extensions/saltext-dell/actions/runs/11371890796/job/31635162248?pr=1). I will have to drop `3006.9` from the test suite for this reason. On Windows and macOS, indirect dependencies ensure `cryptography` is installed regardless of the missing base requirement.

**Comment by dmurphy18** [comment]
@dwoz How do you feel about adding cryptography to base requirements etc.

**Comment by dmurphy18** [comment]
@amalaguti Reopening this but for Rocky Linux / Ubuntu supported version since seeing the same problem with salt extensions, namely development with saltext-cassandra (Ubuntu 24.04)
```
1143 2024-10-16T21:36:55.0424217Z 21:36:53,280 [salt.utils.decorators.jinja                    :26  ][DEBUG   ][       MainProcess(2888)] Marking 'yaml_squote' as a jinja filter
1144 2024-10-16T21:36:55.0425247Z 21:36:53,280 [salt.utils.decorators.jinja                    :26  ][DEBUG   ][       MainProcess(2888)] Marking 'yaml_encode' as a jinja filter
1145 2024-10-16T21:36:55.0426284Z 21:36:53,316 [salt.crypt                                     :515 ][INFO    ][       MainProcess(2888)] Generating master keys: /tmp/master-212e4x/pki
1146 2024-10-16T21:36:55.0427192Z An un-handled exception was caught: name 'rsa' is not defined
1147 2024-10-16T21:36:55.0427638Z Traceback (most recent call last):
1148 2024-10-16T21:36:55.0435067Z   File "/tmp/scripts/cli_salt_master.py", line 53, in <module> 
1149 2024-10-16T21:36:55.0435568Z     main()
1150 2024-10-16T21:36:55.0435951Z   File "/tmp/scripts/cli_salt_master.py", line 48, in main
1151 2024-10-16T21:36:55.0436366Z     salt_master()
1152 2024-10-16T21:36:55.0437294Z   File "/home/runner/work/saltext-cassandra/saltext-cassandra/.nox/tests-3/lib/python3.10/site-packages/salt/scripts.py", line 86, in salt_master
1153 2024-10-16T21:36:55.0438105Z     master.start()
1154 2024-10-16T21:36:55.0438954Z   File "/home/runner/work/saltext-cassandra/saltext-cassandra/.nox/tests-3/lib/python3.10/site-packages/salt/cli/daemons.py", line 199, in start
1155 2024-10-16T21:36:55.0440070Z     super().start()
1156 2024-10-16T21:36:55.0441014Z   File "/home/runner/work/saltext-cassandra/saltext-cassandra/.nox/tests-3/lib/python3.10/site-packages/salt/utils/parsers.py", line 1053, in start
1157 2024-10-16T21:36:55.0441831Z     self.prepare()
1158 2024-10-16T21:36:55.0442699Z   File "/home/runner/work/saltext-cassandra/saltext-cassandra/.nox/tests-3/lib/python3.10/site-packages/salt/cli/daemons.py", line 183, in prepare
1159 2024-10-16T21:36:55.0443567Z     self.master = salt.master.Master(self.config)
1160 2024-10-16T21:36:55.0444529Z   File "/home/runner/work/saltext-cassandra/saltext-cassandra/.nox/tests-3/lib/python3.10/site-packages/salt/master.py", line 548, in __init__
1161 2024-10-16T21:36:55.0445322Z     SMaster.__init__(self, opts)
1162 2024-10-16T21:36:55.0446218Z   File "/home/runner/work/saltext-cassandra/saltext-cassandra/.nox/tests-3/lib/python3.10/site-packages/salt/master.py", line 99, in __init__
1163 2024-10-16T21:36:55.0447082Z     self.master_key = salt.crypt.MasterKeys(self.opts)
1164 2024-10-16T21:36:55.0448073Z   File "/home/runner/work/saltext-cassandra/saltext-cassandra/.nox/tests-3/lib/python3.10/site-packages/salt/crypt.py", line 451, in __init__
1165 2024-10-16T21:36:55.0448906Z     self.key = self.__get_keys(passphrase=key_pass)
1166 2024-10-16T21:36:55.0450194Z   File "/home/runner/work/saltext-cassandra/saltext-cassandra/.nox/tests-3/lib/python3.10/site-packages/salt/crypt.py", line 516, in __get_keys
1167 2024-10-16T21:36:55.0451014Z     gen_keys(
1168 2024-10-16T21:36:55.0451845Z   File "/home/runner/work/saltext-cassandra/saltext-cassandra/.nox/tests-3/lib/python3.10/site-packages/salt/crypt.py", line 147, in gen_keys
1169 2024-10-16T21:36:55.0452677Z     gen = rsa.generate_private_key(e, keysize)
1170 2024-10-16T21:36:55.0453092Z NameError: name 'rsa' is not defined
1171 2024-10-16T21:36:55.0453338Z 
```
seeing pycryptodomex but no cryptography getting pulled in 
```
Requirement already satisfied: pycryptodomex>=3.9.8 in ./.nox/tests-3/lib/python3.10/site-packages (from salt>=3006->saltext.cassandra==0.1.dev3+g3850eb5) (3.21.0)
```

**Comment by dmurphy18** [comment]
@amalaguti @lkubb Closing this since PR https://github.com/saltstack/salt/pull/66977 is now merged and will be in the next release of Salt 3006.10, which should be soon.
