### ISSUE TITLE
[FEATURE REQUEST] Support for repo format DEB822

### ISSUE THREAD

**Issue by ppoudrier-omnimed** [saltstack/salt#66928]
**Is your feature request related to a problem? Please describe.**
Actually, when I use the following state, it always get executed.
```
suricata-repo:
  pkgrepo.managed:
    - ppa: oisf/suricata-stable
```
I digged deeper to find that the repo is never listed in `salt 'host' pkg.list_repos`
_Please note that le ppa of suricata for Ubuntu 24.04 always return the deb822 format and if I try to force the use of keyserver and keyid, the key is invalid to apt_

**Describe the solution you'd like**
I would like have a state that do not reinstall the repo each time so I can have a valid test=true to know if something need to be applied

**Describe alternatives you've considered**
I ended using file.managed

**Additional context**
- Tested with salt version 3006.9 (Master and Minion)
- Master on Ubuntu 20.04 and Minion on Ubuntu 24.04

**Please Note**
If this feature request would be considered a substantial change or addition, this should go through a SEP process here https://github.com/saltstack/salt-enhancement-proposals, instead of a feature request.

**Comment by teutat3s** [comment]
With https://github.com/saltstack/salt-install-guide/pull/6 merged it is now no longer possible to install `salt-*` packages with salt. Following the [official installation docs](https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/linux-deb.html) for Debian, this error appears on a Debian 12 minion:

```
----------
          ID: salt-minion
    Function: pkg.installed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/state.py", line 2440, in call
                  ret = self.states[cdata["full"]](
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 159, in __call__
                  ret = self.loader.run(run_func, *args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1245, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1260, in _run_as
                  ret = _func_or_method(*args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1296, in wrapper
                  return f(*args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/states/pkg.py", line 1703, in installed
                  result = _find_install_targets(
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/states/pkg.py", line 716, in _find_install_targets
                  resolved_latest = __salt__["pkg.latest_version"](
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 159, in __call__
                  ret = self.loader.run(run_func, *args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1245, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1260, in _run_as
                  ret = _func_or_method(*args, **kwargs)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/modules/aptpkg.py", line 484, in latest_version
                  refresh_db(cache_valid_time)
                File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/modules/aptpkg.py", line 609, in refresh_db
                  raise CommandExecutionError(comment)
              salt.exceptions.CommandExecutionError: E: Type 'X-Repolib-Name:' is not known on line 1 in source list /etc/apt/sources.list.d/salt.list
              E: The list of sources could not be read.
```
