### ISSUE TITLE
[BUG] Parallel states on spawning platforms are missing some global dunders

### ISSUE THREAD

**Issue by lkubb** [saltstack/salt#66996]
**Description**
On a spawning platform, running a state module relying on dunders like `__env__` via `parallel: true` fails with a `NameError` (this is probably an issue for `__low__`, `__running__`, `__instance_id__`, `__lowstate__` and `__user__` as well).

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [x] on-prem machine
- [x] onedir packaging

On bare-metal macOS with official 3007.1 package.

Note that Windows is a spawning platform as well.

**Steps to Reproduce the behavior**
```yaml
# /opt/srv/salt/fail.sls

foo:
  git.latest:
    - name: https://github.com/saltstack/salt.git
    - target: /tmp/salt
    - parallel: true
```

```bash
salt-call state.apply fail
```

**Expected behavior**
The clone works.

**Screenshots**
```console
----------
          ID: foo
    Function: git.latest
        Name: https://github.com/saltstack/salt.git
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/opt/salt/lib/python3.10/site-packages/salt/state.py", line 2161, in _call_parallel_target
                  ret = instance.states[cdata["full"]](*cdata["args"], **cdata["kwargs"])
                File "/opt/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 160, in __call__
                  ret = self.loader.run(run_func, *args, **kwargs)
                File "/opt/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1269, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/opt/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1284, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/opt/salt/lib/python3.10/site-packages/salt/states/git.py", line 726, in latest
                  saltenv=__env__,
              NameError: name '__env__' is not defined
     Started: 10:46:38.229375
    Duration: 7.989 ms
     Changes:
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3007.1

Python Version:
        Python: 3.10.14 (main, Apr  3 2024, 21:27:26) [Clang 15.0.0 (clang-1500.0.40.1)]

Dependency Versions:
          cffi: 1.16.0
      cherrypy: unknown
      dateutil: 2.8.2
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.4
       libgit2: Not Installed
  looseversion: 1.3.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.7
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 23.1
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: Not Installed
  python-gnupg: 0.5.2
        PyYAML: 6.0.1
         PyZMQ: 25.1.2
        relenv: 0.16.0
         smmap: Not Installed
       timelib: 0.3.0
       Tornado: 6.3.3
           ZMQ: 4.3.4

Salt Package Information:
  Package Type: onedir

System Versions:
          dist: darwin 23.6.0
        locale: utf-8
       machine: arm64
       release: 23.6.0
        system: Darwin
       version: 14.7 arm64
```
</details>

**Additional context**
`inject_globals` is defined in the parent process:

https://github.com/saltstack/salt/blob/d7b4d10f2a5b334961e48d0622bc0066826dc17c/salt/state.py#L2362-L2372

`__env__` is ensured to be defined in there as well:

https://github.com/saltstack/salt/blob/d7b4d10f2a5b334961e48d0622bc0066826dc17c/salt/state.py#L2414-L2416

The parent process' `State` instance sets the `inject_globals` attribute on its state loader:

https://github.com/saltstack/salt/blob/d7b4d10f2a5b334961e48d0622bc0066826dc17c/salt/state.py#L2422

When `parallel` is `True`, `self.call_parallel` is called

https://github.com/saltstack/salt/blob/d7b4d10f2a5b334961e48d0622bc0066826dc17c/salt/state.py#L2435-L2437

On spawning platforms, a new `State` instance has to be created, which also resets the `inject_globals` attribute on the state module loader:

https://github.com/saltstack/salt/blob/d7b4d10f2a5b334961e48d0622bc0066826dc17c/salt/state.py#L2283-L2291

And it's never redefined.

**Comment by lkubb** [comment]
Fixed by https://github.com/saltstack/salt/pull/66997 in 3006.10/3007.2/master.
