### ISSUE TITLE
[BUG] [3006.x] jaraco.functools needs to be updated to v4.0.0

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt#67070]
**Description**
During development of bootstrap-salt.sh, ran into a issue with jaraco.functools==2.0 being insufficient version, even though this was with Python 3.9 on Rocky Linux 9, problem applies to Python 3.10

```
177 jaraco.functools==2.0
178     # via
179     #   -c requirements/static/ci/../pkg/py3.10/linux.txt
180     #   cheroot
181     #   jaraco.text
182     #   tempora
```
```
10039 + echodebug 'Running '\''python3 setup.py --salt-config-dir=/etc/salt --salt-cache-dir=/var/cache/salt  bdist_wheel'\'''
10040 + '[' 0 -eq 1 ']'
10041 + python3 setup.py --salt-config-dir=/etc/salt '--salt-cache-dir=/var/cache/salt ' bdist_wheel
10042 Traceback (most recent call last):
10043   File "/tmp/git/salt/setup.py", line 7, in <module>
10044     import setuptools  # isort:skip
10045   File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 22, in <module>
10046     import _distutils_hack.override  # noqa: F401
10047   File "/usr/lib/python3.9/site-packages/_distutils_hack/override.py", line 1, in <module>
10048     __import__('_distutils_hack').do_override()
10049   File "/usr/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 89, in do_override
10050     ensure_local_distutils()
10051   File "/usr/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 75, in ensure_local_distutils
10052     core = importlib.import_module('distutils.core')
10053   File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
10054     return _bootstrap._gcd_import(name[level:], package, level)
10055   File "/usr/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 13, in <module>
10056     from .cmd import Command
10057   File "/usr/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 12, in <module>
10058     from . import _modified, archive_util, dir_util, file_util, util
10059   File "/usr/lib/python3.9/site-packages/setuptools/_distutils/_modified.py", line 6, in <module>
10060     from jaraco.functools import splat
10061 ImportError: cannot import name 'splat' from 'jaraco.functools' (/usr/lib/python3.9/site-packages/jaraco/functools.py)
10062 + return 1
```
```splat``` was only added in v4.0.0 of jaraco.functools.

Note: that this was with ```bootstrap-salt.sh git 3006```, so this is a problem with git installs.

Also a problem for master branch where jaraco.functools is 3.7.0

From  https://github.com/jaraco/jaraco.functools/blob/main/NEWS.rst
```
v4.0.0
Features
Added splat function.
```

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [x] used bootstrap to install

**Steps to Reproduce the behavior**
see above

**Expected behavior**
Got a requirements clash with insufficient version of jaraco.functools with git install.

**Additional context**

**Comment by dmurphy18** [comment]
Closing this since, once the 3006.x and 3007.x releases are made, the matter of the requirements will all need to be updated, esp. for master branch
