### ISSUE TITLE
salt-ssh --raw fails with BrokenPipeError: [Errno 32]

### ISSUE THREAD

**Issue by julianfirminger-united** [saltstack/salt#67077]
### Description of Issue
A command that works on a near identical system running CentOS79, fails on RHEL95.
Same result from a runner or just flat in the cli:
salt-ssh MINION-01.domain' --passwd '*****' --ignore-host-keys --raw 'ls'
```

[ERROR   ] An un-handled exception was caught by Salt's global exception handler:
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/bin/salt-ssh", line 11, in <module>
    sys.exit(salt_ssh())
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/scripts.py", line 468, in salt_ssh
    client.run()
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/cli/ssh.py", line 18, in run
    ssh = salt.client.ssh.SSH(self.config)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/client/ssh/__init__.py", line 319, in __init__
    self.mods = mod_data(self.fsclient)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/client/ssh/__init__.py", line 1816, in mod_data
    files = fsclient.file_list(env)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/fileclient.py", line 1367, in file_list
    return self._channel_send(
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/fileclient.py", line 1148, in _channel_send
    return self.channel.send(
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/fileserver/__init__.py", line 886, in send
    return getattr(self.fs, cmd)(load)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/decorators/__init__.py", line 863, in wrapped
    return function(*args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/fileserver/__init__.py", line 769, in file_list
    ret.update(self.servers[fstr](load))
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 160, in __call__
    ret = self.loader.run(run_func, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1269, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1284, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/fileserver/gitfs.py", line 190, in file_list
    return _gitfs().file_list(load)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/gitfs.py", line 3346, in file_list
    return self._file_lists(load, "files")
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/gitfs.py", line 3317, in _file_lists
    repo_files, repo_symlinks = repo.file_list(load["saltenv"])
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/gitfs.py", line 1509, in file_list
    tree = self.get_tree(tgt_env)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/gitfs.py", line 1171, in get_tree
    candidate = func(tgt_ref)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/gitfs.py", line 1616, in get_tree_from_sha
    return self.repo.rev_parse(ref).tree
  File "/opt/saltstack/salt/lib/python3.10/site-packages/git/repo/fun.py", line 409, in rev_parse
    obj = name_to_object(repo, rev)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/git/repo/fun.py", line 205, in name_to_object
    return Object.new_from_sha(repo, hex_to_bin(hexsha))
  File "/opt/saltstack/salt/lib/python3.10/site-packages/git/objects/base.py", line 149, in new_from_sha
    oinfo = repo.odb.info(sha1)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/git/db.py", line 41, in info
    hexsha, typename, size = self._git.get_object_header(bin_to_hex(binsha))
  File "/opt/saltstack/salt/lib/python3.10/site-packages/git/cmd.py", line 1678, in get_object_header
    return self.__get_object_header(cmd, ref)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/git/cmd.py", line 1661, in __get_object_header
    cmd.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/bin/salt-ssh", line 11, in <module>
    sys.exit(salt_ssh())
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/scripts.py", line 468, in salt_ssh
    client.run()
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/cli/ssh.py", line 18, in run
    ssh = salt.client.ssh.SSH(self.config)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/client/ssh/__init__.py", line 319, in __init__
    self.mods = mod_data(self.fsclient)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/client/ssh/__init__.py", line 1816, in mod_data
    files = fsclient.file_list(env)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/fileclient.py", line 1367, in file_list
    return self._channel_send(
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/fileclient.py", line 1148, in _channel_send
    return self.channel.send(
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/fileserver/__init__.py", line 886, in send
    return getattr(self.fs, cmd)(load)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/decorators/__init__.py", line 863, in wrapped
    return function(*args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/fileserver/__init__.py", line 769, in file_list
    ret.update(self.servers[fstr](load))
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 160, in __call__
    ret = self.loader.run(run_func, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1269, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1284, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/fileserver/gitfs.py", line 190, in file_list
    return _gitfs().file_list(load)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/gitfs.py", line 3346, in file_list
    return self._file_lists(load, "files")
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/gitfs.py", line 3317, in _file_lists
    repo_files, repo_symlinks = repo.file_list(load["saltenv"])
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/gitfs.py", line 1509, in file_list
    tree = self.get_tree(tgt_env)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/gitfs.py", line 1171, in get_tree
    candidate = func(tgt_ref)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/gitfs.py", line 1616, in get_tree_from_sha
    return self.repo.rev_parse(ref).tree
  File "/opt/saltstack/salt/lib/python3.10/site-packages/git/repo/fun.py", line 409, in rev_parse
    obj = name_to_object(repo, rev)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/git/repo/fun.py", line 205, in name_to_object
    return Object.new_from_sha(repo, hex_to_bin(hexsha))
  File "/opt/saltstack/salt/lib/python3.10/site-packages/git/objects/base.py", line 149, in new_from_sha
    oinfo = repo.odb.info(sha1)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/git/db.py", line 41, in info
    hexsha, typename, size = self._git.get_object_header(bin_to_hex(binsha))
  File "/opt/saltstack/salt/lib/python3.10/site-packages/git/cmd.py", line 1678, in get_object_header
    return self.__get_object_header(cmd, ref)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/git/cmd.py", line 1661, in __get_object_header
    cmd.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe

```

### Steps to Reproduce Issue
simply run the command

### Versions Report
```
Salt Version:
          Salt: 3007.1

Python Version:
        Python: 3.10.14 (main, Apr  3 2024, 21:30:09) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.16.0
      cherrypy: unknown
      dateutil: 2.8.2
     docker-py: Not Installed
         gitdb: 4.0.11
     gitpython: 3.1.43
        Jinja2: 3.1.4
       libgit2: Not Installed
  looseversion: 1.3.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.7
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 23.1
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: Not Installed
  python-gnupg: 0.5.2
        PyYAML: 6.0.1
         PyZMQ: 25.1.2
        relenv: 0.16.0
         smmap: 5.0.1
       timelib: 0.3.0
       Tornado: 6.3.3
           ZMQ: 4.3.4

Salt Package Information:
  Package Type: onedir

System Versions:
          dist: rhel 9.5 Plow
        locale: utf-8
       machine: x86_64
       release: 5.14.0-503.15.1.el9_5.x86_64
        system: Linux
       version: Red Hat Enterprise Linux 9.5 Plow
```
Not working on RHEL95:
```
[]# uname -a
Linux 5.14.0-503.15.1.el9_5.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Nov 14 15:45:31 EST 2024 x86_64 x86_64 x86_64 GNU/Linux
[]# cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="9.5 (Plow)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="9.5"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux 9.5 (Plow)"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:redhat:enterprise_linux:9::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9"
BUG_REPORT_URL="https://issues.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_BUGZILLA_PRODUCT_VERSION=9.5
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.5"
```

**Comment by bertdawg76** [comment]
@julianfirminger-united I am trying to recreate the issue, and so far haven't been able to recreate it.  Are you able to ssh into the rhel95 machine from the machine with salt on it, without using salt-ssh?  Also, are you able to share your contents of /etc/ssh/ssh_config on the RHEL9 host?  Could you share your /etc/salt/roster file also?  Let me know, I am trying to recreate the issue. thanks

**Comment by bertdawg76** [comment]
Issue cannot be replicated, closing
