### ISSUE TITLE
Rework Windows package manager to allow for rendering

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#6859]
This will allow for jinja and mako templating and the use of Pillar

**Comment by TheBigBear** [comment]
@UtahDave any idea as to when this issue might get resolved, or come back up to the surface?
I have done quite a few packages now, and a good number of them could really do with using some jinja foo to differentiate between a x86 pkg installed on a win32 OS or a win64 OS, particularly for un-install paths etc.

```%ProgramFiles%```  vs ```%ProgramFiles(x86)%```

**Comment by lorengordon** [comment]
There's hope! https://github.com/saltstack/salt/pull/22675

**Comment by twangboy** [comment]
#22675 allows jinja to be parsed using the winrepo.genrepo command. As it stands right now, this gets run on the master and then the resulting msgpack file gets pushed to the minions by running pkg.refresh_db. This only fixes part of the problem. In order to correctly detect the cpu architecture for the machine where the software is actually being installed, the repo will have to be generated on the minion and not on the master. We're working on a solution.

**Comment by dragon788** [comment]
Really excited for this to make it into production. We've been fighting some issues on upgrading packages on Windows due to the lack of grains to identify/maintain information about the state of the system.

**Comment by TheBigBear** [comment]
@eliasp I got the new templatized ```salt-minion``` winrepo sls file done, and made good use of your suggestion above, thanks. https://github.com/saltstack/salt/issues/6859#issuecomment-39366328 , but I got a jinja error, would you care to have a look and try to get the jinja line to work? 
see https://github.com/saltstack/salt-winrepo/blob/WIP_Berryllium+jinja/salt-minion.sls

**Comment by eliasp** [comment]
@TheBigBear 
The problem is most likely, that it shouldn't be:
```SaltStack
{% for version in '2015.5.3-2', '2015.8.0rc2', '2015.8.0rc3' %}
```
… but instead:
```SaltStack
{% for version in [ '2015.5.3-2', '2015.8.0rc2', '2015.8.0rc3' ] %}
```

**Comment by TheBigBear** [comment]
@eliasp sorry, I did not link to the full 'non-working' jijnja code.

https://github.com/saltstack/salt-winrepo/blob/71346c15c8fb931191b5e1eef8922231b7f13736/salt-minion.sls

The issue is with the ```install_flags:``` line, I am pretty sure.
```install_flags: ' /S /master={{ salt['pillar.get']('salt:master', 'salt.domain.tld') }} /minion-id={{ salt['pillar.get']('salt:minion:ids:{{ grains['host'] }}' }}'    <======================```

The full error and backtrace I get is:

```
[ERROR   ] Rendering exception occurred :Jinja syntax error: expected token ',', got 'host'; line 11

---
[...]
    {% if grains['cpuarch'] == 'AMD64' %}
    installer: 'https://repo.saltstack.com/downloads/Salt-Minion-{{ version }}-AMD64-Setup.exe'
    {% elif grains['cpuarch'] == 'x86' %}
    installer: 'https://repo.saltstack.com/downloads/Salt-Minion-{{ version }}-x86-Setup.exe'
    {% endif %}
    install_flags: ' /S /master={{ salt['pillar.get']('salt:master', 'salt.domain.tld') }} /minion-id={{ salt['pillar.get']('salt:minion:ids:{{ grains['host'] }}' }}'    <======================
    uninstaller: 'C:\salt\uninst.exe'
    uninstall_flags: '/S'
    refresh: true
    locale: en_US
    reboot: False
[...]
---
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
SaltRenderError: Jinja syntax error: expected token ',', got 'host'; line 11

---
[...]
    {% if grains['cpuarch'] == 'AMD64' %}
    installer: 'https://repo.saltstack.com/downloads/Salt-Minion-{{ version }}-AMD64-Setup.exe'
    {% elif grains['cpuarch'] == 'x86' %}
    installer: 'https://repo.saltstack.com/downloads/Salt-Minion-{{ version }}-x86-Setup.exe'
    {% endif %}
    install_flags: ' /S /master={{ salt['pillar.get']('salt:master', 'salt.domain.tld') }} /minion-id={{ salt['pillar.get']('salt:minion:ids:{{ grains['host'] }}' }}'    <======================
    uninstaller: 'C:\salt\uninst.exe'
    uninstall_flags: '/S'
    refresh: true
    locale: en_US
    reboot: False
[...]
---
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 224, in salt_call
    client.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\call.py", line 50, in run
    caller.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 133, in run
    ret = self.call()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 196, in call
    ret['return'] = func(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\modules\win_repo.py", line 69, in genrepo
    __opts__['renderer'])
  File "C:\salt\bin\lib\site-packages\salt\template.py", line 94, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "C:\salt\bin\lib\site-packages\salt\renderers\jinja.py", line 333, in render
    **kws)
  File "C:\salt\bin\lib\site-packages\salt\utils\templates.py", line 180, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "C:\salt\bin\lib\site-packages\salt\utils\templates.py", line 376, in render_jinja_tmpl
    tmplstr)
SaltRenderError: Jinja syntax error: expected token ',', got 'host'; line 11

---
[...]
    {% if grains['cpuarch'] == 'AMD64' %}
    installer: 'https://repo.saltstack.com/downloads/Salt-Minion-{{ version }}-AMD64-Setup.exe'
    {% elif grains['cpuarch'] == 'x86' %}
    installer: 'https://repo.saltstack.com/downloads/Salt-Minion-{{ version }}-x86-Setup.exe'
    {% endif %}
    install_flags: ' /S /master={{ salt['pillar.get']('salt:master', 'salt.domain.tld') }} /minion-id={{ salt['pillar.get']('salt:minion:ids:{{ grains['host'] }}' }}'    <======================
    uninstaller: 'C:\salt\uninst.exe'
    uninstall_flags: '/S'
    refresh: true
    locale: en_US
    reboot: False
[...]
---
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 224, in salt_call
    client.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\call.py", line 50, in run
    caller.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 133, in run
    ret = self.call()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 196, in call
    ret['return'] = func(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\modules\win_repo.py", line 69, in genrepo
    __opts__['renderer'])
  File "C:\salt\bin\lib\site-packages\salt\template.py", line 94, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "C:\salt\bin\lib\site-packages\salt\renderers\jinja.py", line 333, in render
    **kws)
  File "C:\salt\bin\lib\site-packages\salt\utils\templates.py", line 180, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "C:\salt\bin\lib\site-packages\salt\utils\templates.py", line 376, in render_jinja_tmpl
    tmplstr)
salt.exceptions.SaltRenderError: Jinja syntax error: expected token ',', got 'host'; line 11

---
[...]
    {% if grains['cpuarch'] == 'AMD64' %}
    installer: 'https://repo.saltstack.com/downloads/Salt-Minion-{{ version }}-AMD64-Setup.exe'
    {% elif grains['cpuarch'] == 'x86' %}
    installer: 'https://repo.saltstack.com/downloads/Salt-Minion-{{ version }}-x86-Setup.exe'
    {% endif %}
    install_flags: ' /S /master={{ salt['pillar.get']('salt:master', 'salt.domain.tld') }} /minion-id={{ salt['pillar.get']('salt:minion:ids:{{ grains['host'] }}' }}'    <======================
    uninstaller: 'C:\salt\uninst.exe'
    uninstall_flags: '/S'
    refresh: true
    locale: en_US
    reboot: False
[...]
---
``` 

And my salt-call --versions is:
```
C:\salt>salt-call --versions
Salt Version:
           Salt: 2015.8.0rc3

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.2
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
       pycrypto: 2.6.1
        timelib: Not Installed

System Versions:
           dist:
        machine: AMD64
        release: 8
         system: 8 6.2.9200  Multiprocessor Free
```

**Comment by eliasp** [comment]
You're using nested Jinja blocks:
```SaltStack
{{ salt['pillar.get']('salt:minion:ids:{{ grains['host'] }}' }}
```
this won't work.
Use this instead:
```SaltStack
{{ salt['pillar.get']('salt:minion:ids:' ~ grains['host'] }}
```
