### ISSUE TITLE
KeyError: 'success' when (re)starting minion using mysql returner [CentOS][0.16.4]

### ISSUE THREAD

**Issue by cedwards** [saltstack/salt#7518]
```shell
[root@summer ~]# service salt-minion restart
Stopping salt-minion daemon:                               [  OK  ]
Starting salt-minion daemon:                               [  OK  ]
[root@summer ~]# Process Process-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 232, in _bootstrap
    self.run()
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 88, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.6/site-packages/salt/utils/schedule.py", line 101, in handle_func
    self.returners[ret_str](ret)
  File "/usr/lib/python2.6/site-packages/salt/returners/mysql.py", line 134, in returner
    ret['success'], json.dumps(ret)))
  File "/usr/lib64/python2.6/contextlib.py", line 34, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.6/site-packages/salt/returners/mysql.py", line 108, in _get_serv
    yield cursor
  File "/usr/lib/python2.6/site-packages/salt/returners/mysql.py", line 134, in returner
    ret['success'], json.dumps(ret)))
KeyError: 'success'

[root@summer ~]# salt --versions-report
           Salt: 0.16.4
         Python: 2.6.6 (r266:84292, Jul 10 2013, 22:48:45)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
         PyYAML: 3.10
          PyZMQ: 2.2.0.1
            ZMQ: 3.2.3

**Comment by jfindlay** [comment]
It looks like @wrg, can't reproduce this anymore.  What do you think, @cedwards?

**Comment by cedwards** [comment]
I'd say it's safe to close.
