### ISSUE TITLE
SLS - variables content with braces - trace in some cases

### ISSUE THREAD

**Issue by ze42** [saltstack/salt#7650]
Hello,

I recently tried to get some data in my SLS, and hitted a wall, probably
because of a bug.

Quick exploration seems to indicate there is some unexpected (at least
for me) when the value I try to substitute include braces {}.
### test1.sls

```
{% set foo = '{ab}c' %}
foo:
  file.managed:
  - name: /tmp/bar
  - content: {{ foo }}
```

A variable starting with braces... **BUG**

```
# salt-call state.show_sls test1
[...]
    - Rendering SLS test1 failed, render error: while parsing a block mapping
    -   in "<string>", line 5, column 5:
    -       - content: {ab}c
    -         ^
    - expected <block end>, but found '<scalar>'
    -   in "<string>", line 5, column 18:
    -       - content: {ab}c
    -                      ^
    - Traceback (most recent call last):
    -   File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1929, in render_state
    -     rendered_sls=mods
[...]
    -     self.current_event = self.state()
    -   File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 439, in parse_block_mapping_key
    -     "expected <block end>, but found %r" % token.id, token.start_mark)
    - ParserError: while parsing a block mapping
    -   in "<string>", line 5, column 5:
    -       - content: {ab}c
    -         ^
    - expected <block end>, but found '<scalar>'
    -   in "<string>", line 5, column 18:
    -       - content: {ab}c
    -                      ^
```
### test2.sls

```
{% set foo = '.{ab}c' %}
foo:
  file.managed:
  - name: /tmp/bar
  - content: {{ foo }}
```

Variable with braces, but not at start... **OK**

```
# salt-call state.show_sls test2
[...]
            - content:
                .{ab}c
[...]
```
### test3.sls

```
{% set foo = {
        'foo': '{b}ar',
        'baz': [ '{def}4', 'a{bc}2' ],
        }
%}
foo:
  file.managed:
  - name: /tmp/bar
  - content: {{ foo }}
```

Dict, with braces in values... **OK**

```
# salt-call state.show_sls test3
[...]
            - content:
                ----------
                baz:
                    - {def}4
                    - a{bc}2
                foo:
                    {b}ar
[...]
```
### test4.sls

```
foo:
  file.managed:
  - name: /tmp/bar
  - content: {{ salt['ztest.data']() }}
```

Using module returning unicode with braces... **BUG**

```
# _modules/ztest.py
def data():
    return { 'foo': u'a{b}c', }
```

```
# salt-call state.show_sls test4
local:
    - Rendering SLS test4 failed, render error: while parsing a flow mapping
    -   in "<string>", line 4, column 14:
    -       - content: {'foo': u'a{b}c'}
    -                  ^
    - expected ',' or '}', but got '{'
    -   in "<string>", line 4, column 25:
    -       - content: {'foo': u'a{b}c'}
    -                             ^
    - Traceback (most recent call last):
    -   File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1929, in render_state
    -     rendered_sls=mods
    -   File "/usr/lib/python2.7/dist-packages/salt/template.py", line 69, in compile_template
    -     ret = render(input_data, env, sls, **render_kwargs)
[...]
    -   File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 98, in check_event
    -     self.current_event = self.state()
    -   File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 550, in parse_flow_mapping_key
    -     "expected ',' or '}', but got %r" % token.id, token.start_mark)
    - ParserError: while parsing a flow mapping
    -   in "<string>", line 4, column 14:
    -       - content: {'foo': u'a{b}c'}
    -                  ^
    - expected ',' or '}', but got '{'
    -   in "<string>", line 4, column 25:
    -       - content: {'foo': u'a{b}c'}
    -                             ^
```

Note: with non-unicode, it worked.

---

I'm not sure what is causing such errors, but it is kinda annoying. Is
there some known workaround, like a filter or something, that I just
missed ?

Edit:

Using filter |yaml tend to fix the issue for the first cases, but not for the
last one.

```
    - ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/unicode'
    -   in "<string>", line 4, column 20:
    -       - content: {foo: !!python/unicode 'a{b}c'}
```

Edit2:

While trying to find a workaround, it looks like sls doesn't handle
non-ascii values at all. (unicode, ...)

**Comment by ScoreUnder** [comment]
I'm getting this same bug on OSX on a recent commit.

```
local:
    Data failed to compile:
----------
    Rendering SLS 'base:apps.cleanAllTheThings' failed: could not determine a constructor for the tag 'tag:yaml.org,2002:python/unicode'
  in "<unicode string>", line 29, column 16:
        - {minute: !!python/unicode '*/5'}
                   ^
root@grape:~ # salt-call --version
salt-call 2016.11.0-1113-gf912b8c (Carbon)
```

The relevant portion of SLS source is:
```jinja
{% for part in ['minute', 'hour', 'daymonth', 'month', 'dayweek'] %}
    - {{ {part: when.get(part, '*')} | yaml }}
{% endfor %}
```
Where `when` is pulled from the pillar earlier.

**Comment by ze42** [comment]
@ScoreUnder Have you tried using `|json` filter? I found it often gives better result, as it is still valid yaml, but more one-liner, and without python-specific objects...

**Comment by ScoreUnder** [comment]
I didn't think of that, it works quite well. Thanks.
