### ISSUE TITLE
Stating #!stateconf -ps causes a critical exception to be raised

### ISSUE THREAD

**Issue by thedrow** [saltstack/salt#7916]
```
[default] Configuring cache buckets...
[default] Running provisioner: salt...
Copying salt minion config to vm.
Checking if salt-minion is installed
salt-minion found
Checking if salt-call is installed
salt-call found
Using Bootstrap Options:  -c /tmp -C
Salt binaries found. Configuring only.
stdin: is not a tty
 *  INFO:  sh -- Version 1.5.8
 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   3.2.0-23-generic
 *  INFO:   Distribution: Ubuntu 12.04

 *  INFO: Configuring minion
 *  INFO: Found function install_ubuntu_deps
 *  INFO: Found function config_salt
 *  INFO: Found function install_ubuntu_stable
 *  INFO: Found function install_ubuntu_restart_daemons
 *  INFO: Found function daemons_running
 *  INFO: Running config_salt()
 *  INFO: Running install_ubuntu_restart_daemons()
salt-minion stop/waiting
salt-minion start/running, process 15007
 *  INFO: Running daemons_running()
 *  INFO: Salt configured
Salt successfully configured!
Calling state.highstate... (this may take a while)
stdin: is not a tty
[DEBUG   ] Reading configuration from /etc/salt/minion
[INFO    ] Using cached minion ID: precise64
[DEBUG   ] loading log_handlers in ['/var/cache/salt/minion/extmods/log_handlers', '/usr/lib/python2.7/dist-packages/salt/log/handlers']
[DEBUG   ] Skipping /var/cache/salt/minion/extmods/log_handlers, it is not a directory
[DEBUG   ] None of the required configuration sections, 'logstash_udp_handler' and 'logstash_zmq_handler', were found the in the configuration. Not loading the Logstash logging handlers module.
[DEBUG   ] Configuration file path: /etc/salt/minion
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] loading grain in ['/var/cache/salt/minion/extmods/grains', '/usr/lib/python2.7/dist-packages/salt/grains']
[DEBUG   ] Skipping /var/cache/salt/minion/extmods/grains, it is not a directory
[DEBUG   ] loading module in ['/var/cache/salt/minion/extmods/modules', '/usr/lib/python2.7/dist-packages/salt/modules']
[DEBUG   ] Skipping /var/cache/salt/minion/extmods/modules, it is not a directory
[DEBUG   ] Loaded localemod as virtual locale
[DEBUG   ] Loaded groupadd as virtual group
[DEBUG   ] Loaded linux_sysctl as virtual sysctl
[DEBUG   ] Loaded sysmod as virtual sys
[DEBUG   ] Loaded parted as virtual partition
[DEBUG   ] Loaded apt as virtual pkg
[DEBUG   ] Loaded upstart as virtual service
[DEBUG   ] Loaded useradd as virtual user
[DEBUG   ] Loaded dpkg as virtual lowpkg
[DEBUG   ] Loaded cmdmod as virtual cmd
[DEBUG   ] Loaded debconfmod as virtual debconf
[DEBUG   ] Loaded virtualenv_mod as virtual virtualenv
[DEBUG   ] Loaded djangomod as virtual django
[DEBUG   ] Loaded linux_lvm as virtual lvm
[DEBUG   ] loading render in ['/var/cache/salt/minion/extmods/renderers', '/usr/lib/python2.7/dist-packages/salt/renderers']
[DEBUG   ] Skipping /var/cache/salt/minion/extmods/renderers, it is not a directory
[DEBUG   ] loading pillar in ['/var/cache/salt/minion/extmods/pillar', '/usr/lib/python2.7/dist-packages/salt/pillar']
[DEBUG   ] Skipping /var/cache/salt/minion/extmods/pillar, it is not a directory
[DEBUG   ] loading module in ['/var/cache/salt/minion/extmods/modules', '/usr/lib/python2.7/dist-packages/salt/modules']
[DEBUG   ] Skipping /var/cache/salt/minion/extmods/modules, it is not a directory
[DEBUG   ] Loaded localemod as virtual locale
[DEBUG   ] Loaded groupadd as virtual group
[DEBUG   ] Loaded linux_sysctl as virtual sysctl
[DEBUG   ] Loaded sysmod as virtual sys
[DEBUG   ] Loaded parted as virtual partition
[DEBUG   ] Loaded apt as virtual pkg
[DEBUG   ] Loaded upstart as virtual service
[DEBUG   ] Loaded useradd as virtual user
[DEBUG   ] Loaded dpkg as virtual lowpkg
[DEBUG   ] Loaded cmdmod as virtual cmd
[DEBUG   ] Loaded debconfmod as virtual debconf
[DEBUG   ] Loaded virtualenv_mod as virtual virtualenv
[DEBUG   ] Loaded djangomod as virtual django
[DEBUG   ] Loaded linux_lvm as virtual lvm
[DEBUG   ] loading returner in ['/var/cache/salt/minion/extmods/returners', '/usr/lib/python2.7/dist-packages/salt/returners']
[DEBUG   ] Skipping /var/cache/salt/minion/extmods/returners, it is not a directory
[DEBUG   ] Loaded syslog_return as virtual syslog
[DEBUG   ] Loaded couchdb_return as virtual couchdb
[DEBUG   ] Loaded carbon_return as virtual carbon
[DEBUG   ] Loaded sqlite3_return as virtual sqlite3
[DEBUG   ] loading states in ['/var/cache/salt/minion/extmods/states', '/usr/lib/python2.7/dist-packages/salt/states']
[DEBUG   ] Skipping /var/cache/salt/minion/extmods/states, it is not a directory
[DEBUG   ] Loaded saltmod as virtual salt
[DEBUG   ] Loaded virtualenv_mod as virtual virtualenv
[DEBUG   ] Loaded pip_state as virtual pip
[DEBUG   ] Loaded debconfmod as virtual debconf
[DEBUG   ] loading render in ['/var/cache/salt/minion/extmods/renderers', '/usr/lib/python2.7/dist-packages/salt/renderers']
[DEBUG   ] Skipping /var/cache/salt/minion/extmods/renderers, it is not a directory
[INFO    ] Executing command 'ps -efH' in directory '/root'
[DEBUG   ] output: UID        PID  PPID  C STIME TTY          TIME CMD
root         2     0  0 13:15 ?        00:00:00 [kthreadd]
root         3     2  0 13:15 ?        00:00:01   [ksoftirqd/0]
root         6     2  0 13:15 ?        00:00:00   [migration/0]
root         7     2  0 13:15 ?        00:00:00   [watchdog/0]
root         8     2  0 13:15 ?        00:00:00   [migration/1]
root         9     2  0 13:15 ?        00:00:00   [kworker/1:0]
root        10     2  0 13:15 ?        00:00:01   [ksoftirqd/1]
root        12     2  0 13:15 ?        00:00:00   [watchdog/1]
root        13     2  0 13:15 ?        00:00:00   [cpuset]
root        14     2  0 13:15 ?        00:00:00   [khelper]
root        15     2  0 13:15 ?        00:00:00   [kdevtmpfs]
root        16     2  0 13:15 ?        00:00:00   [netns]
root        17     2  0 13:15 ?        00:00:00   [kworker/u:1]
root        18     2  0 13:15 ?        00:00:00   [sync_supers]
root        19     2  0 13:15 ?        00:00:00   [bdi-default]
root        20     2  0 13:15 ?        00:00:00   [kintegrityd]
root        21     2  0 13:15 ?        00:00:00   [kblockd]
root        22     2  0 13:15 ?        00:00:00   [ata_sff]
root        23     2  0 13:15 ?        00:00:00   [khubd]
root        24     2  0 13:15 ?        00:00:00   [md]
root        25     2  0 13:15 ?        00:00:00   [kworker/1:1]
root        26     2  0 13:15 ?        00:00:00   [khungtaskd]
root        27     2  0 13:15 ?        00:00:02   [kswapd0]
root        28     2  0 13:15 ?        00:00:00   [ksmd]
root        29     2  0 13:15 ?        00:00:00   [fsnotify_mark]
root        30     2  0 13:15 ?        00:00:00   [ecryptfs-kthrea]
root        31     2  0 13:15 ?        00:00:00   [crypto]
root        39     2  0 13:15 ?        00:00:00   [kthrotld]
root        40     2  0 13:15 ?        00:00:00   [kworker/u:2]
root        41     2  0 13:15 ?        00:00:00   [scsi_eh_0]
root        42     2  0 13:15 ?        00:00:00   [scsi_eh_1]
root        43     2  0 13:15 ?        00:00:00   [scsi_eh_2]
root        66     2  0 13:15 ?        00:00:00   [devfreq_wq]
root       103     2  0 13:15 ?        00:00:03   [kworker/0:3]
root       196     2  0 13:15 ?        00:00:00   [kdmflush]
root       208     2  0 13:15 ?        00:00:00   [kdmflush]
root       217     2  0 13:15 ?        00:00:02   [jbd2/dm-0-8]
root       218     2  0 13:15 ?        00:00:00   [ext4-dio-unwrit]
root       361     2  0 13:15 ?        00:00:00   [iprt]
root       377     2  0 13:15 ?        00:00:00   [kpsmoused]
root       657     2  0 13:15 ?        00:00:00   [rpciod]
root       664     2  0 13:15 ?        00:00:00   [nfsiod]
root       897     2  0 13:15 ?        00:00:02   [flush-252:0]
root      6126     2  0 13:27 ?        00:00:01   [kworker/0:1]
root      9151     2  0 13:35 ?        00:00:00   [kworker/0:0]
root     14783     2  0 13:46 ?        00:00:00   [kworker/0:2]
root         1     0  0 13:15 ?        00:00:01 /sbin/init
root       305     1  0 13:15 ?        00:00:00   upstart-udev-bridge --daemon
root       307     1  0 13:15 ?        00:00:00   /sbin/udevd --daemon
root       356   307  0 13:15 ?        00:00:00     /sbin/udevd --daemon
root       357   307  0 13:15 ?        00:00:00     /sbin/udevd --daemon
root       464     1  0 13:15 ?        00:00:00   rpcbind -w
root       508     1  0 13:15 ?        00:00:00   upstart-socket-bridge --daemon
root       527     1  0 13:15 ?        00:00:00   dhclient3 -e IF_METRIC=100 -pf /var/run/dhclient.eth0.pid -lf /var/lib/dhcp/dhclient.eth0.leases -1 eth0
102        678     1  0 13:15 ?        00:00:00   dbus-daemon --system --fork --activation=upstart
syslog     692     1  0 13:15 ?        00:00:01   rsyslogd -c5
root       696     1  0 13:15 ?        00:00:00   rpc.idmapd
statd      706     1  0 13:15 ?        00:00:00   rpc.statd -L
root       745     1  0 13:15 tty4     00:00:00   /sbin/getty -8 38400 tty4
root       749     1  0 13:15 tty5     00:00:00   /sbin/getty -8 38400 tty5
root       759     1  0 13:15 tty2     00:00:00   /sbin/getty -8 38400 tty2
root       760     1  0 13:15 tty3     00:00:00   /sbin/getty -8 38400 tty3
root       763     1  0 13:15 tty6     00:00:00   /sbin/getty -8 38400 tty6
root       767     1  0 13:15 ?        00:00:00   cron
daemon     769     1  0 13:15 ?        00:00:00   atd
root       780     1  0 13:15 ?        00:00:00   /usr/sbin/irqbalance
root       837     1  0 13:15 ?        00:00:01   /usr/sbin/VBoxService
root       891     1  0 13:15 ?        00:00:00   dhclient eth0
root       894     1  0 13:15 tty1     00:00:00   /sbin/getty -8 38400 tty1
root      1035     1  0 13:15 ?        00:00:00   /usr/sbin/sshd -D
root     14784  1035  0 13:46 ?        00:00:00     sshd: vagrant [priv]
vagrant  14801 14784  1 13:46 ?        00:00:00       sshd: vagrant@notty 
root     15093 14801  0 13:46 ?        00:00:00         sudo -H bash -l
root     15094 15093  0 13:46 ?        00:00:00           bash -l
root     15096 15094 76 13:46 ?        00:00:00             /usr/bin/python /usr/bin/salt-call state.highstate -l debug
root     15120 15096  0 13:46 ?        00:00:00               ps -efH
ntp       1205     1  0 13:15 ?        00:00:00   /usr/sbin/ntpd -p /var/run/ntpd.pid -g -u 103:108
root     15007     1  3 13:46 ?        00:00:00   /usr/bin/python /usr/bin/salt-minion
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] loading grain in ['/var/cache/salt/minion/extmods/grains', '/usr/lib/python2.7/dist-packages/salt/grains']
[DEBUG   ] Skipping /var/cache/salt/minion/extmods/grains, it is not a directory
[DEBUG   ] loading module in ['/var/cache/salt/minion/extmods/modules', '/usr/lib/python2.7/dist-packages/salt/modules']
[DEBUG   ] Skipping /var/cache/salt/minion/extmods/modules, it is not a directory
[DEBUG   ] Loaded localemod as virtual locale
[DEBUG   ] Loaded groupadd as virtual group
[DEBUG   ] Loaded linux_sysctl as virtual sysctl
[DEBUG   ] Loaded sysmod as virtual sys
[DEBUG   ] Loaded parted as virtual partition
[DEBUG   ] Loaded apt as virtual pkg
[DEBUG   ] Loaded upstart as virtual service
[DEBUG   ] Loaded useradd as virtual user
[DEBUG   ] Loaded dpkg as virtual lowpkg
[DEBUG   ] Loaded cmdmod as virtual cmd
[DEBUG   ] Loaded debconfmod as virtual debconf
[DEBUG   ] Loaded virtualenv_mod as virtual virtualenv
[DEBUG   ] Loaded djangomod as virtual django
[DEBUG   ] Loaded linux_lvm as virtual lvm
[DEBUG   ] loading render in ['/var/cache/salt/minion/extmods/renderers', '/usr/lib/python2.7/dist-packages/salt/renderers']
[DEBUG   ] Skipping /var/cache/salt/minion/extmods/renderers, it is not a directory
[DEBUG   ] loading pillar in ['/var/cache/salt/minion/extmods/pillar', '/usr/lib/python2.7/dist-packages/salt/pillar']
[DEBUG   ] Skipping /var/cache/salt/minion/extmods/pillar, it is not a directory
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] loading module in ['/var/cache/salt/minion/extmods/modules', '/usr/lib/python2.7/dist-packages/salt/modules']
[DEBUG   ] Skipping /var/cache/salt/minion/extmods/modules, it is not a directory
[DEBUG   ] Loaded localemod as virtual locale
[DEBUG   ] Loaded groupadd as virtual group
[DEBUG   ] Loaded linux_sysctl as virtual sysctl
[DEBUG   ] Loaded sysmod as virtual sys
[DEBUG   ] Loaded parted as virtual partition
[DEBUG   ] Loaded apt as virtual pkg
[DEBUG   ] Loaded upstart as virtual service
[DEBUG   ] Loaded useradd as virtual user
[DEBUG   ] Loaded dpkg as virtual lowpkg
[DEBUG   ] Loaded cmdmod as virtual cmd
[DEBUG   ] Loaded debconfmod as virtual debconf
[DEBUG   ] Loaded virtualenv_mod as virtual virtualenv
[DEBUG   ] Loaded djangomod as virtual django
[DEBUG   ] Loaded linux_lvm as virtual lvm
[DEBUG   ] loading states in ['/var/cache/salt/minion/extmods/states', '/usr/lib/python2.7/dist-packages/salt/states']
[DEBUG   ] Skipping /var/cache/salt/minion/extmods/states, it is not a directory
[DEBUG   ] Loaded saltmod as virtual salt
[DEBUG   ] Loaded virtualenv_mod as virtual virtualenv
[DEBUG   ] Loaded pip_state as virtual pip
[DEBUG   ] Loaded debconfmod as virtual debconf
[DEBUG   ] loading render in ['/var/cache/salt/minion/extmods/renderers', '/usr/lib/python2.7/dist-packages/salt/renderers']
[DEBUG   ] Skipping /var/cache/salt/minion/extmods/renderers, it is not a directory
[DEBUG   ] loading module in ['/var/cache/salt/minion/extmods/modules', '/usr/lib/python2.7/dist-packages/salt/modules']
[DEBUG   ] Skipping /var/cache/salt/minion/extmods/modules, it is not a directory
[DEBUG   ] Loaded localemod as virtual locale
[DEBUG   ] Loaded groupadd as virtual group
[DEBUG   ] Loaded linux_sysctl as virtual sysctl
[DEBUG   ] Loaded sysmod as virtual sys
[DEBUG   ] Loaded parted as virtual partition
[DEBUG   ] Loaded apt as virtual pkg
[DEBUG   ] Loaded upstart as virtual service
[DEBUG   ] Loaded useradd as virtual user
[DEBUG   ] Loaded dpkg as virtual lowpkg
[DEBUG   ] Loaded cmdmod as virtual cmd
[DEBUG   ] Loaded debconfmod as virtual debconf
[DEBUG   ] Loaded virtualenv_mod as virtual virtualenv
[DEBUG   ] Loaded djangomod as virtual django
[DEBUG   ] Loaded linux_lvm as virtual lvm
[DEBUG   ] Jinja search path: '['/srv/salt']'
[DEBUG   ] Rendered data from file: /srv/salt/top.sls:
base:
  '*':
    - users
    - git
    - python
    - nodejs
    - dev-linux-toolchain
    - github
[DEBUG   ] Results of YAML rendering: 
OrderedDict([('base', OrderedDict([('*', ['users', 'git', 'python', 'nodejs', 'dev-linux-toolchain', 'github'])]))])
[DEBUG   ] Syncing all
[INFO    ] Creating module dir '/var/cache/salt/minion/extmods/modules'
[INFO    ] Syncing modules for environment 'base'
[INFO    ] Loading cache from salt://_modules, for base)
[INFO    ] Caching directory '_modules/' for environment 'base'
[DEBUG   ] Local cache dir: '/var/cache/salt/minion/files/base/_modules'
[INFO    ] Creating module dir '/var/cache/salt/minion/extmods/states'
[INFO    ] Syncing states for environment 'base'
[INFO    ] Loading cache from salt://_states, for base)
[INFO    ] Caching directory '_states/' for environment 'base'
[DEBUG   ] Local cache dir: '/var/cache/salt/minion/files/base/_states'
[INFO    ] Creating module dir '/var/cache/salt/minion/extmods/grains'
[INFO    ] Syncing grains for environment 'base'
[INFO    ] Loading cache from salt://_grains, for base)
[INFO    ] Caching directory '_grains/' for environment 'base'
[DEBUG   ] Local cache dir: '/var/cache/salt/minion/files/base/_grains'
[INFO    ] Creating module dir '/var/cache/salt/minion/extmods/renderers'
[INFO    ] Syncing renderers for environment 'base'
[INFO    ] Loading cache from salt://_renderers, for base)
[INFO    ] Caching directory '_renderers/' for environment 'base'
[DEBUG   ] Local cache dir: '/var/cache/salt/minion/files/base/_renderers'
[INFO    ] Creating module dir '/var/cache/salt/minion/extmods/returners'
[INFO    ] Syncing returners for environment 'base'
[INFO    ] Loading cache from salt://_returners, for base)
[INFO    ] Caching directory '_returners/' for environment 'base'
[DEBUG   ] Local cache dir: '/var/cache/salt/minion/files/base/_returners'
[INFO    ] Creating module dir '/var/cache/salt/minion/extmods/outputters'
[INFO    ] Syncing outputters for environment 'base'
[INFO    ] Loading cache from salt://_outputters, for base)
[INFO    ] Caching directory '_outputters/' for environment 'base'
[DEBUG   ] Local cache dir: '/var/cache/salt/minion/files/base/_outputters'
[DEBUG   ] MinionEvent PUB socket URI: ipc:///var/run/salt/minion/minion_event_56c02c9f39234bae85c5910942f731ec_pub.ipc
[DEBUG   ] MinionEvent PULL socket URI: ipc:///var/run/salt/minion/minion_event_56c02c9f39234bae85c5910942f731ec_pull.ipc
[DEBUG   ] Refreshing modules...
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] loading module in ['/var/cache/salt/minion/extmods/modules', '/usr/lib/python2.7/dist-packages/salt/modules']
[DEBUG   ] Skipping /var/cache/salt/minion/extmods/modules, it is not a directory
[DEBUG   ] Loaded localemod as virtual locale
[DEBUG   ] Loaded groupadd as virtual group
[DEBUG   ] Loaded linux_sysctl as virtual sysctl
[DEBUG   ] Loaded sysmod as virtual sys
[DEBUG   ] Loaded parted as virtual partition
[DEBUG   ] Loaded apt as virtual pkg
[DEBUG   ] Loaded upstart as virtual service
[DEBUG   ] Loaded useradd as virtual user
[DEBUG   ] Loaded dpkg as virtual lowpkg
[DEBUG   ] Loaded cmdmod as virtual cmd
[DEBUG   ] Loaded debconfmod as virtual debconf
[DEBUG   ] Loaded virtualenv_mod as virtual virtualenv
[DEBUG   ] Loaded djangomod as virtual django
[DEBUG   ] Loaded linux_lvm as virtual lvm
[DEBUG   ] loading states in ['/var/cache/salt/minion/extmods/states', '/usr/lib/python2.7/dist-packages/salt/states']
[DEBUG   ] Skipping /var/cache/salt/minion/extmods/states, it is not a directory
[DEBUG   ] Loaded saltmod as virtual salt
[DEBUG   ] Loaded virtualenv_mod as virtual virtualenv
[DEBUG   ] Loaded pip_state as virtual pip
[DEBUG   ] Loaded debconfmod as virtual debconf
[DEBUG   ] loading render in ['/var/cache/salt/minion/extmods/renderers', '/usr/lib/python2.7/dist-packages/salt/renderers']
[DEBUG   ] Skipping /var/cache/salt/minion/extmods/renderers, it is not a directory
[DEBUG   ] MinionEvent PUB socket URI: ipc:///var/run/salt/minion/minion_event_56c02c9f39234bae85c5910942f731ec_pub.ipc
[DEBUG   ] MinionEvent PULL socket URI: ipc:///var/run/salt/minion/minion_event_56c02c9f39234bae85c5910942f731ec_pull.ipc
[DEBUG   ] Jinja search path: '['/srv/salt']'
[DEBUG   ] Rendered data from file: /srv/salt/users/init.sls:
users:
  user.present:
    - name: ****

  file.directory:
    - name: /home/****/Documents/Projects
    - makedirs: True
    - recurse:
        - user
    - user: ****
[DEBUG   ] Results of YAML rendering: 
OrderedDict([('users', OrderedDict([('user.present', [OrderedDict([('name', '****')])]), ('file.directory', [OrderedDict([('name', '/home/****/Documents/Projects')]), OrderedDict([('makedirs', True)]), OrderedDict([('recurse', ['user'])]), OrderedDict([('user', '****')])])]))])
[CRITICAL] Rendering SLS git failed, render error: object.__new__(cStringIO.StringI) is not safe, use cStringIO.StringI.__new__()
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1939, in render_state
    rendered_sls=mods
  File "/usr/lib/python2.7/dist-packages/salt/template.py", line 69, in compile_template
    ret = render(input_data, env, sls, **render_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/renderers/stateconf.py", line 178, in render
    data = process_high_data(input, extract=False)
  File "/usr/lib/python2.7/dist-packages/salt/renderers/stateconf.py", line 124, in process_high_data
    data = copy.deepcopy(high)
  File "/usr/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python2.7/copy.py", line 329, in _reconstruct
    y = callable(*args)
  File "/usr/lib/python2.7/copy_reg.py", line 93, in __newobj__
    return cls.__new__(cls, *args)
TypeError: object.__new__(cStringIO.StringI) is not safe, use cStringIO.StringI.__new__()
[CRITICAL] Rendering SLS python failed, render error: object.__new__(cStringIO.StringI) is not safe, use cStringIO.StringI.__new__()
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1939, in render_state
    rendered_sls=mods
  File "/usr/lib/python2.7/dist-packages/salt/template.py", line 69, in compile_template
    ret = render(input_data, env, sls, **render_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/renderers/stateconf.py", line 178, in render
    data = process_high_data(input, extract=False)
  File "/usr/lib/python2.7/dist-packages/salt/renderers/stateconf.py", line 124, in process_high_data
    data = copy.deepcopy(high)
  File "/usr/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python2.7/copy.py", line 329, in _reconstruct
    y = callable(*args)
  File "/usr/lib/python2.7/copy_reg.py", line 93, in __newobj__
    return cls.__new__(cls, *args)
TypeError: object.__new__(cStringIO.StringI) is not safe, use cStringIO.StringI.__new__()
[DEBUG   ] Jinja search path: '['/srv/salt']'
[DEBUG   ] Rendered data from file: /srv/salt/nodejs/init.sls:
nodejs:
  pkgrepo.managed:
    - ppa: chris-lea/node.js

  pkg.installed:
    - name: nodejs

  npm.installed:
    - names:
      - yo
      - grunt
      - less
      - bower
[DEBUG   ] Results of YAML rendering: 
OrderedDict([('nodejs', OrderedDict([('pkgrepo.managed', [OrderedDict([('ppa', 'chris-lea/node.js')])]), ('pkg.installed', [OrderedDict([('name', 'nodejs')])]), ('npm.installed', [OrderedDict([('names', ['yo', 'grunt', 'less', 'bower'])])])]))])
[DEBUG   ] Jinja search path: '['/srv/salt']'
[DEBUG   ] Rendered data from file: /srv/salt/dev-linux-toolchain/init.sls:
linux-dev-toolchain:
  pkg.installed:
    - pkgs:
        - build-essential
        - python2.7-dev
        - python3-dev
[DEBUG   ] Results of YAML rendering: 
OrderedDict([('linux-dev-toolchain', OrderedDict([('pkg.installed', [OrderedDict([('pkgs', ['build-essential', 'python2.7-dev', 'python3-dev'])])])]))])
[DEBUG   ] Jinja search path: '['/srv/salt']'
[DEBUG   ] Rendered data from file: /srv/salt/top.sls:
base:
  '*':
    - users
    - git
    - python
    - nodejs
    - dev-linux-toolchain
    - github
[DEBUG   ] Results of YAML rendering: 
OrderedDict([('base', OrderedDict([('*', ['users', 'git', 'python', 'nodejs', 'dev-linux-toolchain', 'github'])]))])
[DEBUG   ] Rendered sls: OrderedDict([('extend', OrderedDict([('github::start', {'stateconf': [{'require': [{'stateconf': 'python::goal'}]}]})])), ('github', {'cmd': ['call', {'name': 'main'}, {'kws': {}}, {'args': []}, {'func': <function main at 0x3897de8>}]}), ('_slsmod_github', {'stateconf': ['set', {'require': [{'cmd': 'github'}]}, {'slsmod': <module 'github' from '/srv/salt/github/init.sls'>}]}), ('github::start', {'stateconf.set': [{'require_in': [{'cmd': 'github'}]}]}), ('github::goal', {'stateconf.set': [{'require': [{'cmd': 'github'}, {'stateconf': '_slsmod_github'}, {'stateconf': 'github::start'}]}]})])
[DEBUG   ] loading output in ['/var/cache/salt/minion/extmods/output', '/usr/lib/python2.7/dist-packages/salt/output']
[DEBUG   ] Skipping /var/cache/salt/minion/extmods/output, it is not a directory
[DEBUG   ] Loaded no_out as virtual quiet
[DEBUG   ] Loaded json_out as virtual json
[DEBUG   ] Loaded yaml_out as virtual yaml
[DEBUG   ] Loaded pprint_out as virtual pprint
local:
    Data failed to compile:
----------
    Rendering SLS git failed, render error: object.__new__(cStringIO.StringI) is not safe, use cStringIO.StringI.__new__()
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1939, in render_state
    rendered_sls=mods
  File "/usr/lib/python2.7/dist-packages/salt/template.py", line 69, in compile_template
    ret = render(input_data, env, sls, **render_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/renderers/stateconf.py", line 178, in render
    data = process_high_data(input, extract=False)
  File "/usr/lib/python2.7/dist-packages/salt/renderers/stateconf.py", line 124, in process_high_data
    data = copy.deepcopy(high)
  File "/usr/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python2.7/copy.py", line 329, in _reconstruct
    y = callable(*args)
  File "/usr/lib/python2.7/copy_reg.py", line 93, in __newobj__
    return cls.__new__(cls, *args)
TypeError: object.__new__(cStringIO.StringI) is not safe, use cStringIO.StringI.__new__()

----------
    Rendering SLS python failed, render error: object.__new__(cStringIO.StringI) is not safe, use cStringIO.StringI.__new__()
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1939, in render_state
    rendered_sls=mods
  File "/usr/lib/python2.7/dist-packages/salt/template.py", line 69, in compile_template
    ret = render(input_data, env, sls, **render_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/renderers/stateconf.py", line 178, in render
    data = process_high_data(input, extract=False)
  File "/usr/lib/python2.7/dist-packages/salt/renderers/stateconf.py", line 124, in process_high_data
    data = copy.deepcopy(high)
  File "/usr/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python2.7/copy.py", line 329, in _reconstruct
    y = callable(*args)
  File "/usr/lib/python2.7/copy_reg.py", line 93, in __newobj__
    return cls.__new__(cls, *args)
TypeError: object.__new__(cStringIO.StringI) is not safe, use cStringIO.StringI.__new__()
[default] Configuring cache buckets...
```

I have a PyDSL file that reported that git & python has no .goal so I tried copying the stateconf part of the shebang and that's what happened.

**Comment by thedrow** [comment]
I guess no one cares.
