### ISSUE TITLE
winrepo.genrepo fails if one of the packages in winrepo is malformed.

### ISSUE THREAD

**Issue by bogdanr** [saltstack/salt#8157]
I am testing with the git repo hosted here and apparently one of the packages is malformed so winrepo.genrepo fails making the whole git repository unusable.

I believe the malformed packages should be logged and handled gracefully so we can use the repo even if some of the packages are not OK.

nimblex:~# salt-run winrepo.update_git_repos
{'https://github.com/saltstack/salt-winrepo.git': True}
nimblex:~# 
nimblex:~# salt-run winrepo.genrepo
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: list indices must be integers, not str
Traceback (most recent call last):
  File "/usr/bin/salt-run", line 10, in <module>
    salt_run()
  File "/usr/lib64/python2.7/site-packages/salt/scripts.py", line 90, in salt_run
    client.run()
  File "/usr/lib64/python2.7/site-packages/salt/cli/**init**.py", line 346, in run
    runner.run()
  File "/usr/lib64/python2.7/site-packages/salt/runner.py", line 153, in run
    self.opts['fun'], self.opts['arg'], self.opts)
  File "/usr/lib64/python2.7/site-packages/salt/runner.py", line 85, in cmd
    return self.functions[fun](*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/salt/runners/winrepo.py", line 58, in genrepo
    revmap[repodata['full_name']] = pkgname
TypeError: list indices must be integers, not str
Traceback (most recent call last):
  File "/usr/bin/salt-run", line 10, in <module>
    salt_run()
  File "/usr/lib64/python2.7/site-packages/salt/scripts.py", line 90, in salt_run
    client.run()
  File "/usr/lib64/python2.7/site-packages/salt/cli/**init**.py", line 346, in run
    runner.run()
  File "/usr/lib64/python2.7/site-packages/salt/runner.py", line 153, in run
    self.opts['fun'], self.opts['arg'], self.opts)
  File "/usr/lib64/python2.7/site-packages/salt/runner.py", line 85, in cmd
    return self.functions[fun](*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/salt/runners/winrepo.py", line 58, in genrepo
    revmap[repodata['full_name']] = pkgname
TypeError: list indices must be integers, not str

**Comment by TheBigBear** [comment]
just ran into this as well. It would indeed be really nice if this failed a bit more meaningfully, or even 'ignored' the faulty sls file, giving a meaningful message, and worked on the rest of them, to update the winrepo.p file as best it can.

**Comment by UtahDave** [comment]
@TheBigBear what version are you seeing this in?  I thought I had fixed this.

**Comment by TheBigBear** [comment]
@UtahDave I see it when using winrepo.genrepo on a test materlsess windows minion runinng 2014.7.0 on win 7 64-bit
(sorry, just noticed the issue logged was for use of winrepo.genrepo in the subject or tilte, but the example was for when using winrepo.update_git_repos, maybe that'sthe one you fixed? ) I have been helped by eliasp on IRC just now, and he asked me to come and 'subscribe' to issue #8175 as well .

I had crudd in my c:\salt\win\repo subdirs and was only just managing to switch on windows minion in masterless mode to speed up my software installation testing. And because of the crud in some of the broken files, it failed, and did not update the winrepo.p file. 
I can provide the trace and try find the culprit file if this helps (there were only a handfull of them -s no big deal).

**Comment by TheBigBear** [comment]
OK, the "crudd' was in my early copy of my audacity.sls file. ;-) 
I had pasted it into a local file and forgotten to indent it for yaml or python. 
So it looks like this:

```
audacity:
2.0.6:
installer: http://sourceforge.net/projects/audacity/files/audacity/2.0.6/audacity-win-2.0.6.exe&nowrap
full_name: Audacity 2.0.6
locale: en_US
reboot: False
install_flags: ' /sp- /verysilent /norestart'
uninstaller: '%PROGRAMFILES(x86)%\Audacity\unins000.exe'
uninstall_flags: ' /verysilent'
```

And if I run ``salt-call --local -l debug winrepo.genrepo``` I get:
```
C:\salt>salt-call.exe --local -l debug winrepo.genrepo
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Mako not available
[ERROR   ] An un-handled exception was caught by salt's global exception
AttributeError: 'NoneType' object has no attribute 'iteritems'
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "__main__.py", line 726, in <module>
  File "__main__.py", line 332, in bootstrap
  File "__main__.py", line 359, in chainload
  File "__main__.py", line 715, in _chainload
  File "__main__.py", line 128, in <module>
  File "__main__salt-call__.py", line 14, in <module>
  File "salt/scripts.py", line 122, in salt_call
  File "salt/cli/__init__.py", line 419, in run
  File "salt/cli/caller.py", line 225, in run
  File "salt/cli/caller.py", line 129, in call
  File "salt/modules/win_repo.py", line 75, in genrepo
AttributeError: 'NoneType' object has no attribute 'iteritems'
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "__main__.py", line 726, in <module>
  File "__main__.py", line 332, in bootstrap
  File "__main__.py", line 359, in chainload
  File "__main__.py", line 715, in _chainload
  File "__main__.py", line 128, in <module>
  File "__main__salt-call__.py", line 14, in <module>
  File "salt/scripts.py", line 122, in salt_call
  File "salt/cli/__init__.py", line 419, in run
  File "salt/cli/caller.py", line 225, in run
  File "salt/cli/caller.py", line 129, in call
  File "salt/modules/win_repo.py", line 75, in genrepo
AttributeError: 'NoneType' object has no attribute 'iteritems'
```

```
