### ISSUE TITLE
ZMQError: Operation cannot be accomplished in current state

### ISSUE THREAD

**Issue by Mrten** [saltstack/salt#8676]
After having executed highstate over 10 times now, I *still* encounter minions that are not upgraded.

However, this is about something else: My last highstate returned a lot of ZMQErrors:

```
web-3:
----------
    State: - pkg
    Name:      salt-minion
    Function:  latest
        Result:    True
        Comment:   The following packages were successfully installed/upgraded: salt-minion.
        Changes:   salt-minion: { new : 0.17.2-2precise1
old : 0.17.2-1precise
}
                   salt-common: { new : 0.17.2-2precise1
old : 0.17.2-1precise
}

----------
    State: - file
    Name:      /etc/salt/minion.d/tcp-keepalive.conf
    Function:  managed
        Result:    False
        Comment:   Source file salt://all-salt-minion-config/tcp-keepalive.conf not found
        Changes:
----------
    State: - service
    Name:      salt-minion
    Function:  running
        Result:    False
        Comment:   One or more requisite failed
        Changes:
----------
    State: - file
    Name:      /etc/apt/salt-ppa.key
    Function:  managed
        Result:    False
        Comment:   An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/salt/state.py", line 1278, in call
    *cdata['args'], **cdata['kwargs'])
  File "/usr/lib/pymodules/python2.7/salt/states/file.py", line 1139, in managed
    **kwargs
  File "/usr/lib/pymodules/python2.7/salt/modules/file.py", line 1599, in get_managed
    source_sum = __salt__['cp.hash_file'](source, env)
  File "/usr/lib/pymodules/python2.7/salt/modules/cp.py", line 410, in hash_file
    return __context__['cp.fileclient'].hash_file(path, env)
  File "/usr/lib/pymodules/python2.7/salt/fileclient.py", line 825, in hash_file
    return self._crypted_transfer(load)
  File "/usr/lib/pymodules/python2.7/salt/fileclient.py", line 657, in _crypted_transfer
    return _do_transfer()
  File "/usr/lib/pymodules/python2.7/salt/fileclient.py", line 654, in _do_transfer
    timeout)
  File "/usr/lib/pymodules/python2.7/salt/payload.py", line 182, in send
    self.socket.send(pkg)
  File "socket.pyx", line 530, in zmq.core.socket.Socket.send (zmq/core/socket.c:4943)
  File "socket.pyx", line 577, in zmq.core.socket.Socket.send (zmq/core/socket.c:4700)
  File "socket.pyx", line 174, in zmq.core.socket._send_copy (zmq/core/socket.c:1925)
  File "checkrc.pxd", line 23, in zmq.core.checkrc._check_rc (zmq/core/socket.c:5754)
ZMQError: Operation cannot be accomplished in current state
[repeat again for lots more states in the highstate]
```

**Comment by rallytime** [comment]
Since we didn't hear back I am going to go ahead and close this issue. If this remains a problem on newer versions of salt (current stable is 2015.5.3) please let us know and we'll be glad to re-open or readdress.
