### ISSUE TITLE
Failed matching available minions with glob pattern

### ISSUE THREAD

**Issue by Mrten** [saltstack/salt#8678]
This morning I ran a highstate -b 10% which I ctrl-C'd. Returning to the master log in the afternoon to find a lead to some other problem I see this:

```
2013-11-20 09:27:47,888 [salt.utils.minions][ERROR   ] Failed matching available minions with glob pattern: ['yubiksm', 'yubikey', 'web-5', 'web-4', 'web-3']
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/salt/utils/minions.py", line 327, in check_minions
    }[expr_form](expr)
  File "/usr/lib/pymodules/python2.7/salt/utils/minions.py", line 56, in _check_glob_minions
    ret = set(glob.glob(expr))
  File "/usr/lib/python2.7/glob.py", line 16, in glob
    return list(iglob(pathname))
  File "/usr/lib/python2.7/glob.py", line 24, in iglob
    if not has_magic(pathname):
  File "/usr/lib/python2.7/glob.py", line 78, in has_magic
    return magic_check.search(s) is not None
TypeError: expected string or buffer
```
I thought you'd like to know (there's two more of these but they are the same but for the names of the minions).
0.17.2 (I think).

**Comment by lawrencelx** [comment]
I have a this same problem

**Comment by rallytime** [comment]
Hey @lawrencelx would you mind opening up a new issues with your specific details? I think more eyes will see it that way as this is a fairly old issue.
