### ISSUE TITLE
pyzmq >=14 breaks esky builds

### ISSUE THREAD

**Issue by hdonnay** [saltstack/salt#8956]
```
0.17.2
running bdist_esky
Traceback (most recent call last):
  File "setup.py", line 441, in <module>
    setup(**SETUP_KWARGS)
  File "/usr/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/hank/salt-freezer/salt/.env27/lib/python2.7/site-packages/esky-0.9.8-py2.7.egg/esky/bdist_esky/__init__.py", line 309, in run
    self._run()
  File "/home/hank/salt-freezer/salt/.env27/lib/python2.7/site-packages/esky-0.9.8-py2.7.egg/esky/bdist_esky/__init__.py", line 317, in _run
    self._run_freeze_scripts()
  File "/home/hank/salt-freezer/salt/.env27/lib/python2.7/site-packages/esky-0.9.8-py2.7.egg/esky/bdist_esky/__init__.py", line 342, in _run_freeze_scripts
    self.freezer_module.freeze(self)
  File "/home/hank/salt-freezer/salt/.env27/lib/python2.7/site-packages/esky-0.9.8-py2.7.egg/esky/bdist_esky/f_bbfreeze.py", line 45, in freeze
    f = bbfreeze.Freezer(dist.freeze_dir,includes=includes,excludes=excludes)
  File "/home/hank/salt-freezer/salt/.env27/lib/python2.7/site-packages/bbfreeze-1.1.2-py2.7.egg/bbfreeze/freezer.py", line 411, in __init__
    self.addModule(x)
  File "/home/hank/salt-freezer/salt/.env27/lib/python2.7/site-packages/bbfreeze-1.1.2-py2.7.egg/bbfreeze/freezer.py", line 459, in addModule
    self.mf.import_hook(name[:-2], fromlist="*")
  File "/home/hank/salt-freezer/salt/.env27/lib/python2.7/site-packages/bbfreeze-1.1.2-py2.7.egg/bbfreeze/modulegraph/modulegraph.py", line 257, in import_hook
    m = self.load_tail(q, tail)
  File "/home/hank/salt-freezer/salt/.env27/lib/python2.7/site-packages/bbfreeze-1.1.2-py2.7.egg/bbfreeze/modulegraph/modulegraph.py", line 341, in load_tail
    raise ImportError, "No module named " + mname
ImportError: No module named zmq.core
```

Changing the `pyzmq` line in `requirements.txt` seems to be a workaround:

```
pyzmq >= 2.1.9, <14
```

**Comment by msteed** [comment]
@esky, @hdonnay: it looks like this was fixed by #11506. Feel free to reopen if this is still an issue.
