### ISSUE TITLE
salt-virt seeding of EL based vm's fails

### ISSUE THREAD

**Issue by jcftang** [saltstack/salt#9477]
when following the tutorial... http://docs.saltstack.com/topics/tutorials/cloud_controller.html using salt 0.17.4

I've tried deploying both ubuntu and centos based guests, ubuntu appears to work fine, but when a centos based guest is deployed by

```
salt-run virt.init foo 2 512 salt://centos64.img
```

the minion returns this error

<pre>
2013-12-28 19:48:58,848 [salt.minion                                 ][WARNING ] The minion function caused an exception: Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 695, in _thread_return
    return_data = func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/modules/virt.py", line 382, in init
    install=install)
  File "/usr/lib/python2.6/site-packages/salt/modules/seed.py", line 128, in apply_
    'minion.pem'))
OSError: [Errno 2] No such file or directory
</pre>

however runners.virt doesnt return an error indicating it has failed and the fuse mount  is left on the hypervisor

**Comment by dmurphy18** [comment]
this maybe fixed given the age of the salt version, we need to look into this to see if fixed
