### ISSUE TITLE
puppet.run fails when 'execute' option is specified

### ISSUE THREAD

**Issue by mohanraj-r** [saltstack/salt#9859]
I have the following puppet command which works fine (installs/verifies apache, starts service etc).

```
puppet apply  --modulepath=/code/puppet --execute='include apache'
```

But when I try to do the same through salt, I get the following error

```
#salt 'vm1' puppet.run apply modulepath='/code/puppet' execute='include apache'

vm1:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 691, in _thread_return
        return_data = func(*args, **kwargs)
      File "/usr/lib/python2.7/site-packages/salt/modules/puppet.py", line 141, in run
        puppet.arguments(args[1:])
      File "/usr/lib/python2.7/site-packages/salt/modules/puppet.py", line 99, in arguments
        self.subcmd_args = [args[0]]
    IndexError: list index out of range
```

I get the same error when I run it through the python client

```
import salt
l = salt.client.LocalClient()

l.cmd('vm1', 'puppet.run', ['apply'], kwargs={'modulepath': '/code/puppet', 'execute': 'include apache'})                                                      
{'vm1': 'Traceback (most recent call last):\n  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 691, in _thread_return\n    return_data = func(*args, **kwargs)\n  File "/usr/lib/python2.7/site-packages/salt/modules/puppet.py", line 141, in run\n    puppet.arguments(args[1:])\n  File "/usr/lib/python2.7/site-packages/salt/modules/puppet.py", line 99, in arguments\n    self.subcmd_args = [args[0]]\nIndexError: list index out of range\n'}
```

But if I specify the full path of the puppet manifest file without the execute option, there is no error. But since in this case puppet just loads the class without executing it - nothing happens - state (of apache) is not affected.

```
salt 'vm1' puppet.run apply /code/puppet/apache/manifests/init.pp 
vm1:
    ----------
    pid:
        29537
    retcode:
        0
    stderr:

    stdout:
        notice: Finished catalog run in 0.01 seconds
```

If I add the execute option to the above command, it fails

```
# salt 'vm1' puppet.run apply /code/puppet/apache/manifests/init.pp   execute='include apache'
vm1:
    ----------
    pid:
        30331
    retcode:
        1
    stderr:
        Could not parse for environment production: Syntax error at end of file at line 1 on node localhost.localdomain
    stdout:
Adding modulepath=/code/puppet does not change the result.
```

Executing the above commands using salt-call gives the same error.

**Comment by rallytime** [comment]
Since we didn't hear back, I am going to close this issue. If the problem persists, please leave a comment and we'll glad re-open and address the situation. Thanks!
